### PR TITLE
QueryGroup: More efficient way to scroll to bottom when adding new queries

### PR DESCRIPTION
**Pull request by torkelo**
Fixes issue with scrolling for live queries

Alernative to #48306 and #48308

### CODE REVIEW

**Comment by ryantxu** [comment]
cc @lean257 and @nmarrs

**Comment by ryantxu** [comment]
@torkelo does this really need "add to changelog"?  Is that because it is a backport to a minor release branch?

**Comment by torkelo** [comment]
@ryantxu yea thought so but your right, it's not that interesting for users to know this

**Review by nmarrs — APPROVED** [review]
Tested locally and works great! Resolves streaming issue 💯

**Pull request merged**
