### PR TITLE
Chore: Add emotion object syntax rule to eslint

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- adds the emotion object syntax rule to eslint now that everywhere is using object styles 🥳 
- fixes the last pesky template literal style that was hiding in the angular folder and wasn't being picked up by betterer

**Why do we need this feature?**

- it's fully typed
- we have various linting rules that will only apply to object styles
- it's [our recommendation](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md#emotion-class-names)
- [it's emotion's recommendation](https://emotion.sh/docs/best-practices#use-typescript-and-object-styles)

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by tomratcliffe — APPROVED** [review]
🚀

**Review by joshhunt — COMMENTED** [review]
LGTM (Lets Go! Techdebt Managed)

**Review by joshhunt — APPROVED** [review]

**Comment by ashharrison90** [comment]
ah i forgot about enterprise! why do i always forget about enterprise... 😭 

will fix those on monday 😂

**Comment by tomratcliffe** [comment]
> LGTM (Lets Go! Techdebt Managed)

Lovely! Getridof The Mangledstyles

**Review by eledobleefe — APPROVED** [review]
🎉

**Comment by leeoniya** [comment]
@ashharrison90 @joshhunt 

with the move to object styles, does this have the side-effect of making it impossible to compile static styles using tagged template literals as we're trying to do in TableNG?

**Comment by ashharrison90** [comment]
> @ashharrison90 @joshhunt
> 
> with the move to object styles, does this have the side-effect of making it impossible to compile static styles using tagged template literals as we're trying to do in TableNG (and hopefully more codebase later)? #95251
> 
> https://linaria.dev/

looking at the linaria docs, i don't see anything that suggests it would support the object syntax so it means we'd have to convert back to template literal styles. fortunately it's a lot easier going that way (object -> template literal) than it is the other (template literal -> object), so we could write a codemod that would do this pretty easily. i think there might already be a function exposed by emotion to do this as well.

but imo we'd need a good reason to consider doing this, e.g. compelling performance comparisons, since we'd lose both type-safety and our custom lint rules (e.g. `no-border-radius`, `no-unreduced-motion`, etc.)

**Pull request merged**
