### PR TITLE
Alerting: Add error recovery during rule evaluations

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Add recovery support to the rule evaluation (eg in case a query panics).
This fix handles these cases and returns an error (before it would case the server to halt):
Screenshot 2021-06-15 at 4 16 46 PM

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The issue can be easily reproduced if creating a rule querying the test datasource using the `Server Error (500)` scenario like:
```
{
    "data": [
        {
            "refId": "A",
            "queryType": "",
            "relativeTimeRange": {
                "from": 21600,
                "to": 0
            },
            "datasourceUid": "000000004", // test datasource
            "model": {
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "refId": "A",
                "scenarioId": "server_error_500"
            }
        },
        {
            "refId": "B",
            "queryType": "",
            "relativeTimeRange": {
                "from": 0,
                "to": 0
            },
            "datasourceUid": "-100",
            "model": {
                "conditions": [
                    {
                        "evaluator": {
                            "params": [
                                3
                            ],
                            "type": "gt"
                        },
                        "operator": {
                            "type": "and"
                        },
                        "query": {
                            "params": [
                                "A"
                            ]
                        },
                        "reducer": {
                            "params": [],
                            "type": "last"
                        },
                        "type": "query"
                    }
                ],
                "datasource": "__expr__",
                "hide": false,
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "refId": "B",
                "type": "classic_conditions"
            }
        }
    ]
}
```

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]

**Comment by gotjosh** [comment]
is there more to it that this? Can we figure out the source of the panic? I agree that we should always recover here but in this case, I think we should find the source of the problem given it seems like it's coming from the within?

**Comment by papagian** [comment]
> is there more to it that this? Can we figure out the source of the panic? I agree that we should always recover here but in this case, I think we should find the source of the problem given it seems like it's coming from the within?

the source is the [specific](https://github.com/grafana/grafana/blob/4cb62e4292adb31a2eaaffdac10fa42c15c12631/pkg/tsdb/testdatasource/scenarios.go#L432) test datasource scenario.

**Comment by gotjosh** [comment]
Should that panic to begin with?

**Review by marefr — APPROVED** [review]
Might want to log the stacktrace/details and return a more user friendly error to the UI?

Might want to consider checking if error already set in recovery and log that as well (not sure that could happen though)

**Comment by marefr** [comment]
The panic is a good test scenario to verify that proper recovery is in place and server doesn't crash.

**Comment by papagian** [comment]
@marefr @kylebrandt thanks for approving
I have made some changes to address [this](https://github.com/grafana/grafana/pull/35450#pullrequestreview-682997898)
Would you mind to check once again, thank you!

**Review by kylebrandt — APPROVED** [review]

**Pull request merged**
