### PR TITLE
Scenes: Use @grafana/scenes 

### PR DESCRIPTION
**Pull request by dprokop**
This PR extracts Scenes code to [grafana scenes repo](https://github.com/grafana/scenes).

~~Since the package is not yet published, please follow the [grafana/scenes dev guide](https://github.com/grafana/scenes#development) to test this PR out locally.~~

Things, that were not moved to separate package:
- DashboardLoader & DashboardScene
- core Scene - which tightly integrates with core Page component
- scene Editor
- demos

Also, `panelBuilders` are for now left in core, as those rely on core plugin types and those need to become @grafana/schema citizens first.

### CODE REVIEW

**Comment by kaydelaney** [comment]
Moved this to "In Progress". Hope that's okay!

**Comment by torkelo** [comment]
@dprokop i think this looks good, what more do you need before merge?

**Comment by dprokop** [comment]
@torkelo just need to publish scenes to npm. I'm on PTO today, will do that first thing on Monday.

**Comment by torkelo** [comment]
@dprokop ok great, just wanted to check that you were not blocked / await review or anything :)

**Review by torkelo — APPROVED** [review]

**Pull request merged**
