### PR TITLE
Prometheus: Azure authentication in plugin proxy routes

### PR DESCRIPTION
**Pull request by kostrse**
**What this PR does / why we need it**:

This PR adds optional Azure authentication for Prometheus datasource controlled by configuration by JsonData (via configuration editor).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Prometheus datasource relies on plugin proxy routing and standard HTTP configuration. It has code that creates HTTP transport ([here](https://github.com/grafana/grafana/blob/a0dac9c6d9297bf0740a8689f37701f18215f588/pkg/tsdb/prometheus/prometheus.go#L40)) but it seems like never called in practice.
So, the only way to tap into the transport of Prometheus plugin is via the plugin proxy routes.

For this purpose I extended the route matcher to support matching by host name (in `ds_proxy.go`) additionally to matching by path. It allows me to specific Azure endpoints and apply Azure authentication to them while keep other endpoins unaffected.

### CODE REVIEW

**Comment by kostrse** [comment]
The list of routes in `plugin.json` looks verbose, I'm thinking to extend the logic in matcher to compact the list.

One option would be to add support for pass-thru rules. So one request could be matched with more than one rule, like:

```json
    {
      "host": "prometheus.azure.net",
      "authType": "{{if .JsonData.azureAuth}}azure{{else}}none{{end}}",
      "tokenAuth": {
        "scopes": ["https://management.azure.com/.default"],
        "params": {
          "azure_auth_type": "{{.JsonData.azureAuthType | orEmpty}}",
          "azure_cloud": "AzureCloud",
          "tenant_id": "{{.JsonData.azureTenantId | orEmpty}}",
          "client_id": "{{.JsonData.azureClientId | orEmpty}}",
          "client_secret": "{{.SecureJsonData.azureClientSecret | orEmpty}}"
        }
      },
      "matching": "continue"
    },
    {
      "method": "POST",
      "path": "api/v1/query",
      "reqRole": "Viewer"
    }
```

**Review by marefr — CHANGES_REQUESTED** [review]
> Prometheus datasource relies on plugin proxy routing and standard HTTP configuration. It has code that creates HTTP transport ([here](https://github.com/grafana/grafana/blob/a0dac9c6d9297bf0740a8689f37701f18215f588/pkg/tsdb/prometheus/prometheus.go#L40)) but it seems like never called in practice.
> So, the only way to tap into the transport of Prometheus plugin is via the plugin proxy routes.

Not true. The backend Prometheus code is used for Grafana alerting. Suggested solution could be accepted, but with the caveat that you cannot use Grafana alerting with Prometheus and azure authentication.

On another note, is there any plans for being able to configure azure auth in the UI?

**Comment by kostrse** [comment]
> the Prometheus backend and HTTPTransport is used for alerting, so a middleware should be added for prometheus alerting to also work with azure authentication.

Thanks for pointing out the alerting. I was thinking that alerting would rely on routes too.

**Comment by kostrse** [comment]
@marefr, @joshhunt please look at this PR: #36594. I implemented the Azure authentication in the Prometheus HTTP transport, specifically for alerts, but I anticipate that it will become the only Azure auth implementation once Prometheus migrated to Plugin SDK.

I will keep the work on the plugin proxy routes in this PR, to make the PRs smaller and easier to review.

**Comment by marefr** [comment]
Thanks. I'll have a look at that other PR.

In regards to "pass-thru rules" that feels/looks a bit advanced to me, but related to your other PR it might be possible to make use of/reuse that. Lets discuss this later.

**Pull request closed without merging**
