### PR TITLE
Chore: Update k8s.io dependencies

### PR DESCRIPTION
**Pull request by toddtreece**
**What is this feature?**

This updates `k8s.io` dependencies to `v0.31.0-rc.1`

**Why do we need this feature?**

This is needed by #91228

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by charandas — APPROVED** [review]
LGTM! Thank you ✍🏽

**Comment by toddtreece** [comment]
@charandas i had to update a couple things in standalone apiserver in https://github.com/grafana/grafana/pull/91692/commits/a8330ce775e5fad62770d8fe32d1a78c601b9c96 to make lint happy

**Review by ryantxu — APPROVED** [review]

**Pull request merged**
