### PR TITLE
(prometheus) show label name in paren after by/without/on/ignoring/group_left/group_right

### PR DESCRIPTION
**Pull request by mtanda**

### CODE REVIEW

**Comment by bergquist** [comment]
More work expected or should I start testing/reviewing?

**Comment by mtanda** [comment]
There is an obvious bug.
Need to show label list for target metrics name.

I'll fix it, then request review.

**Comment by mtanda** [comment]
@bergquist ready for review. please check!

**Comment by bergquist** [comment]
colors for `by(label)` and `without(label)` seems off.
image

**Comment by mtanda** [comment]
@bergquist I fix the highlight issue!

**Comment by bergquist** [comment]
:+1:

**Pull request merged**
