### PR TITLE
SignupInvitedPage: Show `orgName`

### LINKED ISSUE #94932: Invite signup page: Missing organization name
### What happened?

When a user is invited to an organization and they click on the invite link (of the form `https://<grafana_domain>/invite/<invite_code>`), the text on the page reads (verbatim)
> _Alice_ has invited you to join Grafana and the organization

(let's say in this case the invite was sent by Alice). This is not a complete sentence, and looking at [the code](https://github.com/grafana/grafana/blob/main/public/app/features/invites/SignupInvited.tsx#L70-L71), it's clear that the name of the organization ought to be included at the end:
```html
          <em>{invitedBy || 'Someone'}</em> has invited you to join Grafana and the organization{' '}
          <span className="highlight-word">{contextSrv.user.orgName}</span>
```
But this doesn't work because the user account doesn't actually exist yet (it only exists as a temporary account), therefore `contextSrv.user.orgName` is not set.

### What did you expect to happen?

The text should include the name of the organization that the user was invited to, e.g.

> _Alice_ has invited you to join Grafana and the organization **BigCorp**

### Did this work before?

I feel like I've seen this work correctly, so I assumed this was some sort of regression. But I've just tried this in every major Grafana version going back to v3, and it does not appear to work in any version.

### How do we reproduce it?

1. Under "Organization users" click "Invite". Generate an invite
2. Either get the invite link from the email, or just copy it from the list of pending invites
3. Open the invite link on a different browser or in incognito mode
4. Observe that the organization name is not included in the first sentence

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.0 (also tested with 3.1.0, 4.6.5, 5.4.4, 6.5.3, 7.5.4, 8.4.11, 9.4.17, 10.1.1
OS: macOS, running Grafana in Docker
Browser: Chrome 129.0.6668.100

### Grafana platform?

Docker

### Datasource(s)?

n/a

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #94932
at backend side, i add field `orgName` to return;
at frontend side, i use  `orgName` to show.

### CODE REVIEW

**Review by IevaVasiljeva — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by IevaVasiljeva** [comment]
Linters reports a small issue:
```
public/app/features/invites/SignupInvited.tsx:12:1 - error TS6133: 'contextSrv' is declared but its value is never read.
```

Once you've fixed it, we can go ahead and merge the PR :)

**Comment by yincongcyincong** [comment]
> Linter reports a small issue:
> 
> ```
> public/app/features/invites/SignupInvited.tsx:12:1 - error TS6133: 'contextSrv' is declared but its value is never read.
> ```
> 
> Once you've fixed it, we can go ahead and merge the PR :)

thanks for this review. i will fix it.

**Comment by yincongcyincong** [comment]
> Linter reports a small issue:
> 
> ```
> public/app/features/invites/SignupInvited.tsx:12:1 - error TS6133: 'contextSrv' is declared but its value is never read.
> ```
> 
> Once you've fixed it, we can go ahead and merge the PR :)

i delete `contextSrv`, please take a look. thanks

**Review by L-M-K-B — COMMENTED** [review]
Hi @yincongcyincong, thanks a lot for contributing to grafana. While running your changes locally I noticed that they are causing a TS error. The same error occurs in the [build pipeline](https://drone.grafana.net/grafana/grafana/203627/2/5). See error message below.
Screenshot 2024-10-22 at 15 34 56
Please have a look and fix the error.

**Review by joshhunt — COMMENTED** [review]
image


LGTM. Thanks for adding a test for this as well!

**Review by joshhunt — APPROVED** [review]

**Comment by mgyongyosi** [comment]
@yincongcyincong Could you please fix this linter error? https://drone.grafana.net/grafana/grafana/203627/2/5  Thanks!

**Comment by yincongcyincong** [comment]
thanks for 

> @yincongcyincong Could you please fix this linter error? https://drone.grafana.net/grafana/grafana/203627/2/5 Thanks!

thanks for your review. i fixed this linter error. please take a look

**Pull request merged**
