### PR TITLE
Tracing: Add more detail to HTTP Outgoing Request

### PR DESCRIPTION
**Pull request by bboreham**
**What is this feature?**

Adds more detail to the span for outgoing HTTP calls from Grafana backend.

image

**Why do we need this feature?**

This lets you see in the tracing view the relative contribution of each step - DNS request, establishing the connection, sending data, etc.

**Who is this feature for?**

Engineers investigating performance of Grafana and backend systems.

**Which issue(s) does this PR fix?**:

NA

**Special notes for your reviewer**:

OpenTelemetry by default will generate a bunch of sub-spans for DNS lookup, etc., but I prefer to have them as events, to save cluttering the view.

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
LGTM

**Review by xnyo — APPROVED** [review]
LGTM!

**Comment by wbrowne** [comment]
@bboreham I assume this one is fine for 9.5.0? (IE doesn't need to roll out into a patch). Let me know if you need a hand with the labelling to satisfy the checks

**Comment by bboreham** [comment]
No burning need to get it out, just something I thought would make an improvement.
I have no knowledge of grafana/grafana labeling, would welcome a pointer.

**Comment by bboreham** [comment]
I found some instructions about labels in the 'Details' against CI checks.

**Comment by bboreham** [comment]
I just noticed it's also putting extra attributes in for every http header (with some redacted):
image

Personally I don't need that so I'll probably turn it off.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by bboreham** [comment]
I have now pushed the commit turning off those extra attributes for headers.
Also note, although I work for Grafana Labs I am not authorized to merge to grafana/grafana myself, so someone else will have to merge this PR.

**Pull request merged**
