### PR TITLE
Chore: Add frontend platform code ownership

### PR DESCRIPTION
**Pull request by dprokop**
@aocenas I've also added ownership for observability squad (jaeger package and features/explore)

### CODE REVIEW

**Comment by aocenas** [comment]
@dprokop makes sense. Do we have any restrictions enabled in context of the owners file? Do we require owners approval for PRs?

**Comment by dprokop** [comment]
> Do we have any restrictions enabled in context of the owners file? Do we require owners approval for PRs?

This is a good question. For sure owners will be assigned for the review, but not sure this means, they have to give approval in order to merge. 

Maybe @aknuds1 or @marefr know something about this?

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
@dprokop I'm not a big expert on this, but I _think_ approval of code owners isn't required? They're probably just added as reviewers, although I could be wrong.

**Review by peterholmberg — APPROVED** [review]

**Review by hugohaggmark — APPROVED** [review]
Looks good! Let's try it out and see if we need to trim the list further.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
We can enable `Require review from Code Owners`, but we haven't currently. Right now we require 1 approved review before a PR can be merged.

**Pull request merged**
