### PR TITLE
Explore: Use new DS picker

### PR DESCRIPTION
**Pull request by ivanortegaalba**
Depends on:
* This PR which fixes the E2E https://github.com/grafana/grafana/pull/70071
* This PR which adds the props that Explore needs https://github.com/grafana/grafana/pull/70074

||Before|After|
|-|-|-|
|Global picker closed|Captura de pantalla 2023-06-14 a las 12 09 59|Captura de pantalla 2023-06-14 a las 12 09 52|
|Global picker open|Captura de pantalla 2023-06-14 a las 12 10 24|Captura de pantalla 2023-06-14 a las 12 10 15|
|Split view|Captura de pantalla 2023-06-14 a las 12 09 27|Captura de pantalla 2023-06-14 a las 12 09 19|

**What is this feature?**

The new DS picker was only used when editing a panel. Explore can benefit from it.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

The new DS picker has discoverability and UX improvements that Explore can benefit from.

**Which issue(s) does this PR fix?**: 
Relates to #66916 

**Special notes for your reviewer:**
I added support for `hideTextValue` and `width`, to make it work in split mode.

**IMPORTANT:** This probably involves changes in Explore documentation to update the screenshots (cc/ @imatwawana).

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Elfo404** [comment]
I think the milestone should probably be `10.1.x`, other than that looks good! (not sure why the e2e test is failing, you may want to double check that)

**Comment by ivanortegaalba** [comment]
I found a bug in the dropdown thanks to the e2e for explore. When filtering, the first item is not selected by default. I'll extract that commit to a different PR, to backport it. The explore changes can be in the major

**Comment by imatwawana** [comment]
> I think the milestone should probably be `10.1.x`, other than that looks good! (not sure why the e2e test is failing, you may want to double check that)

Just confirming, docs would need to be ready for 10.1 release, yes? Or sooner?

**Comment by ivanortegaalba** [comment]
> 10.1

10.1.0 @imatwawana, thank you so much!

**Review by Elfo404 — APPROVED** [review]
looks good 👍 
i guess we'll have to rebase when the other PRs get merged to make the build pass, but approving in the meantime as the diff won't likely change

**Review by juanicabanas — APPROVED** [review]

**Pull request merged**
