### PR TITLE
Prometheus: PromQAIL frontend, drawer, feature toggle, workflow, etc.

### LINKED ISSUE #75845: Prometheus: Merge promqail under feature flag
**What is this?**

We are building LLM and AI support into the Prometheus query builder. This is in the form of a drawer where a user can do the following:

1. ask for query suggestion by writing a prompt
2. ask for suggestions from a list of historical queries
3. get explanations for queries

[See this PR for more detailed information](https://github.com/grafana/grafana/pull/73020)

This issue is to track when we merge the AI assistant into main and turn the feature toggle on in ops.

**Why do we need it?**

The "Get started" and onboarding research around Prometheus found that new Prom users need help writing and understanding queries. This work aligns with the the Grafana goal of Onboarding.

**Who will use it?**

New prometheus users

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/75845

**What is this feature?**
This is PromQAIL, AI/ML + Prometheus. The Prometheus DS in Grafana + the LLM-app.
This is the entire frontend of PromQail wrapped behind a feature toggle `prometheusPromQAIL`.

1. select a metric
2. follow a workflow to get suggested queries from a prompt or historical queries
3. have each query explained by AI
4. use one of these queries and apply it to the query builder 

https://github.com/grafana/grafana/assets/25674746/803c09c8-8137-4ac0-980b-3be2c496e00d

Rudderstack feedback events: 
```
grafana_prometheus_promqail_suggestion_feedback
grafana_prometheus_promqail_explanation_feedback
```

Design below:
These can be seen in [this Figma board](https://www.figma.com/file/yG0a79rfRhfza8iawDgJ8z/PromQail---LLM-%2B-PromQL?type=design&node-id=5-6595&mode=design&t=muGOiGqGqgfOC1e4-0). 

**Why do we need this feature?**
PromQL is hard for new users. New users struggle to write useful queries. PromQAIL solves this problem by leveraging ML/AI to support these folk with query suggestions and explanations.

This is the drawer for the ML/AI integration for the Prometheus query builder. The best practices for [AI integration are described here](https://docs.google.com/document/d/1b9vBquh355FA9Qkt0-hhfwYULdyvmdlQRwpVKaT5O8I/edit).

**Who is this feature for?**
Beginning and intermediate Prometheus users.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by catherineymgui** [comment]
- [ ] Disable the AI button if there's no metric selected?
- [ ] Use the 16px AI icon in the button and in the drawer I sent it to you
- [ ] Is there a way to have the drawer automatically scroll to the bottom with each prompt / action?
- [ ] Use medium instead of small sized buttons here
Screenshot 2023-08-10 at 10 48 50

- [ ] Have 16px spacing between explainer button and the next query
Screenshot 2023-08-10 at 10 48 43

- [ ] Use 12px padding between the text and the output box (for each section)
Screenshot 2023-08-10 at 10 47 46

- [ ] Conversation bubble / output - use 16px padding on all sides 
Screenshot 2023-08-10 at 10 47 46

- [ ] Use the close icon instead of a x
Screenshot 2023-08-10 at 10 47 38

**Comment by bohandley** [comment]
@catherineymgui 

>  Is there a way to have the drawer automatically scroll to the bottom with each prompt / action?
Still haven't found it, yet!

> Have 16px spacing between explainer button and the next query
Since we're only doing 1 query suggestion now, I am thinking there is no next query after the explainer button?

**Comment by catherineymgui** [comment]
Yeah, but that's only the case for the flow with the user prompt. We're still doing 5 queries for the flow where there's no prompt and we're just finding getting the historical queries?

**Comment by catherineymgui** [comment]
Small nits:

- [ ] Add some padding between the AI icon and the 'Assistant'
Screenshot 2023-08-11 at 09 19 11

- [ ] Use the sm instead of md button here
Screenshot 2023-08-11 at 09 20 29


- [ ] Use body small (12px instead of 14px)? This is what it looks like in the screenshots
Screenshot 2023-08-11 at 09 17 56

- [ ] 24px padding between each section (examples here)
Screenshot 2023-08-11 at 09 18 26
Screenshot 2023-08-11 at 09 22 03

**Review by chri2547 — COMMENTED** [review]
Docs look fine, approved.

**Review by itsmylife — APPROVED** [review]

**Pull request merged**
