### PR TITLE
sending back panel targets to plugin incase they need it

### PR DESCRIPTION
**Pull request by Gauravshah**
need it for  meta queries plugin

https://github.com/grafana/grafana/issues/3677

### CODE REVIEW

**Comment by torkelo** [comment]
not sure I understand this PR, the problem is not accessing all the queries but getting the response from other queries. Do you want to reuse the mixed data source in your meta query data source? How and why? if you wan to issue queries from your meta data source then those will be issued twice if that is your plan (once by mixed data source, and one by your data source).

Either the Meta Queries data source needs to work similar to mixed (and be a mixed DS), so that it gets the targets array and can issue the queries to the underlying data sources and combine the response & apply transformations.

**Comment by Gauravshah** [comment]
@torkelo yes they are getting issued twice right now. we would need to make further changes to mixed_datasource so that it can send back the responses as well which meta queries can use. thinking to do that as step 2. 
We would need access to panelTargets irrespective because for `MovingAverage` or `TimeShift` we need to issue a re-query since the time range is different.

**Comment by torkelo** [comment]
> We would need access to panelTargets irrespective because for MovingAverage or TimeShift we need to issue a re-query since the time range is different.

If you will need to re-query then it's the wrong solution. Better to replace or extend the mixed data source and process timeshift before issuing .

**Comment by Gauravshah** [comment]
lets say we are printing Orders by day & then plotting week over week. At this point trying to make just one query and then divide the data is too much logic on frontend. Its cleaner code to issue 2 queries with different time range.

I definitely agree that if I am printing orders, active users and orders/AU then I should issue only 2 queries. 1 for orders and 1 for active users. But for time shift since the range is changing I would think its better to issue 2 queries

**Comment by torkelo** [comment]
what I meant is that if you need to query again and throw away the first query then it's the wrong solution. If you timeShift(#A), and #A is not hidden with eye then of course 2 queries will be issued (with different time ranges)

**Comment by Gauravshah** [comment]
then we would need panelTargets and yes I will continue working on avoiding duplicate query by making further changes to Mixed datasource as step 2. We can wait until then or merge this as step 1. Leave it up to you.

**Comment by torkelo** [comment]
ok, closing this as I still not sure why a datasource would need the all the queries (unless itself is a mixed data source, which in case it is it already gets all queries)

**Comment by Gauravshah** [comment]
@torkelo can you help understand a little bit. Is it enough if I create a plugin externally and give ` config `mixed: true` in `plugin.json`, will that all functionalities that "--Mixed--" get today ?

**Comment by torkelo** [comment]
Yes, think so

**Comment by Gauravshah** [comment]
absolutely silly of me. I was using grafana's `-- Mixed --` data source with my computed datasource. didn't realise I could mark my plugin as mixed and use it as  data source & skip `-- Mixed --` all together. Makes complete sense. I have Time Shift, Moving Average & artihmetic built. Will fix the mixed thingy and open source it in couple of days.

**Comment by torkelo** [comment]
Cool!

**Pull request closed without merging**
