### PR TITLE
grafana/ui: Migrate button components to @grafana/ui

### PR DESCRIPTION
**Pull request by dprokop**
#16221 

_Migration driven by the needs of #15533_

**Indirectly related TODOs:**
- [x] Bump storybook to v5 to enable easy emotion usage
- [x] Enable Emotion v10

**Directly related TODOs:**
- [x] Migrate button variants (primary, secondary, danger, inverse, transparent, link)
- [x] Migrate disabled button styles
- [x] Migrate button sizes (xs, sm, md, lg, xl) (cc @Ijin08 here I'm usng currently existing spacing variables meaning that new buttons have slightly different paddings than the legacy ones. We need to adjust that later on)
- [x] Implement stories

### CODE REVIEW

**Comment by dprokop** [comment]
@Ijin08 @torkelo I strongly suggest to look at the storybook when looking at this PR.

**Review by torkelo — COMMENTED** [review]
This looks mostly great, my only concern is the button factory functions that are executed at global scope & parse time. Any alternatives to that?

**Comment by Ijin08** [comment]
This looks mostly good. Was just thinking about the xl buttons that mostly uses a gicon that doesn't lie in the middle. Theses buttons works with those gicons?

(personally I am not a fan of those icons and wouldn't mind replacing them with a simple +).

**Comment by dprokop** [comment]
> This looks mostly good. Was just thinking about the xl buttons that mostly uses a gicon that doesn't lie in the middle. Theses buttons works with those gicons?

@Ijin08 yest they are. You can try it out in the storybook by going to `with icon` Button stories and selecting Alert icon from icons knob at the bottom.

**Comment by dprokop** [comment]
> my only concern is the button factory functions that are executed at global scope & parse time. Any alternatives to that?

@torkelo why does that bother you? Since this is a factory its behaviour is pretty much the same as with i.e. HOC which are also executed when given component is imported, i.e `export const ThemeableComponent = withTheme(Component)`.

The solutions that come to my mind is to either skip those higher order abstractions (`[Size]Button`) which I find rather useful, or implement them one by one without the factory. The former is gonna be pain to maintain tho.

**Comment by Ijin08** [comment]
I am not sure if that icon is used anymore. It was an old one that was used when adding alerts but has been replaced with an empty list CTA.
I was thinking of these icons that are pushed down a couple of pixels:
Screenshot 2019-03-27 at 09 39 18

**Comment by torkelo** [comment]
> @torkelo why does that bother you? Since this is a factory its behaviour is pretty much the same as with i.e. HOC which are also executed when given component is imported, i.e export const ThemeableComponent = withTheme(Component)

I guess they are the same, but just something that feels wrong having to execute functions to define components at parse time instead of when the actual component is used. But sometime's it's required (like with HOCs)

But looking at it more closely, do we need the sized buttons to be separate components? Is size prop not enough?

**Comment by dprokop** [comment]
> But looking at it more closely, do we need the sized buttons to be separate components? Is size prop not enough?

@torkelo it is enough but I personally find it easier to use `<LargeButton ...>` rather than `<Button size="ButtonSize.Large" ... >`. It's just a small thing but makes the code cleaner. Honestly speaking I would go even more radical and generate `<[Variant][Size]Button ... >` components to avoid direct usage of `size` and `variant` props.

**Review by Ijin08 — APPROVED** [review]
Looks good. The icons should be fixed in later pr when we have pixel gions.

**Comment by torkelo** [comment]
> it is enough but I personally find it easier to use <LargeButton ...> rather than <Button size="ButtonSize.Large" ... >. It's just a small thing but makes the code cleaner. Honestly speaking I would go even more radical and generate <[Variant][Size]Button ... > components to avoid direct usage of size and variant props.

True it easier to read but how many LargeButtons will we use? Think it's only used in CTA & Login page. 

Most buttons will use default size:
```jsx
<Button>Hello</Button>
```

could use small text type like ButtonSize = 'md' | 'lg' | 'sm'. 

``'jsx
<Button size="lg">Hello</Button>
```

But I do no have any strong opinions here, think a LargeButton etc will be great as well.

**Comment by dprokop** [comment]
> Most buttons will use default size:

@torkelo this is interesting input and it makes me feel that instead of having the size button components we should have the variant components (PrimaryButton, SecondaryButton, etc) which might be more useful.

For now I'm gonna merge it as it is and iterate over above concept if that sounds good to you.

**Comment by jschill** [comment]
From a developer perspective i think it's easier to remember `<Button>` and then the tooling will help you with the props and its values rather than remembering all variants like `<PrimaryButton>` `<InverseButton>` etc. Just my two cents re the naming.

**Comment by torkelo** [comment]
Yea agrees to change and import when wanting to dry different size or variant feels a bit hard to use.

**Comment by dprokop** [comment]
@jschill valuable input, thanks! This is that makes me convinced to simply use `Button` and it's props. Gonna remove the additional components soon!

**Comment by torkelo** [comment]
The only thing I would consider is to not use enums for size & variant, as that would be a bit of a pain to have to find the right import to set be able to set size & variant props.

**Comment by jschill** [comment]
> The only thing I would consider is to not use enums for size & variant, as that would be a bit of a pain to have to find the right import to set be able to set size & variant props.

We could provide them as statics on the Button component to avoid extra imports.
```jsx
const  {sizes, variants} = Button;
```
or
```jsx
<Button size={Button.sizes.sm} variant={Button.variants.inverse}>Plz click</Button>
```

**Comment by dprokop** [comment]
@jschill not sure i like the statics approach, nor I recall any place we use this pattern. It still creates a need for a `Button[Variant|Size]` type.

With simple types as @torkelo  suggests:

```ts
type ButtonVariat = 'primary' | 'secondary' | ....
```
the editors/IDE's support will be sufficient to achieve one's goal. Statics create this sort of "invisible" layer of information, that is not accessible to IDE, nor obvious for someone who's not familiar with the fact of statics being available for a given component. Hence the primary usage will most probably be `<Button variant="danger" ... />`

**Comment by jschill** [comment]
If you guys think thats better we should go with that. I have no strong opinion. I can see what you mean with "invisible layer" and at the same time I'm not a fan of refactoring magic strings so..

**Pull request merged**
