### PR TITLE
Elasticsearch: Fix query initialization action

### LINKED ISSUE #29651: Elasticsearch: Duplicate aggregation ids when creating new query
**What happened**:
When adding a new Metric or Bucket aggregation in the elasticsearch datasource, we assign them a progressive numeric id based on the previous ids. This is not true when creating a new query where the first ID for Metric & Bucket aggregations does not depend on previous state. This is causing the first metric and the first bucket aggregation to have the same ID when creating a new query, which causes issues when selecting Metric aggregations with pipeline variables. 

**What you expected to happen**:
At initialization, the first Metric and Bucket aggregations should have different IDs.

**How to reproduce it (as minimally and precisely as possible)**:
- Create new Elasticsearch query (either in Explore or in a dashboard)
- Inspect query sent or query model

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
Manually sets IDs when creating an elasticsearch query to avoid ID duplication and subsequent issues.

**Which issue(s) this PR fixes**:

Fixes #29651

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]
LGTM ⭐

**Comment by ivanahuckova** [comment]
As mentioned in slack, this fixes the issue and LGTM 🚀 . But if you decide to implement solution with default functions not returning `ids` (so other parts of code `datasource.ts, query_builder.ts` are handling this), I think that it would be more clear, solution. Cause it opens up a question on when/why do we use sometimes `1` and sometimes `2` as default values in `defaultBucketAgg()`.  I understand now why, and it makes sense, but it can be not super clear when you read code. So leaving it up to you. 🙂 🕺

**Comment by Elfo404** [comment]
@ivanahuckova it definitely makes sense to remove the ids from the default functions, I'm gonna mark the PR as a draft and update it ASAP. Thanks for the feedback! 🚀

**Comment by Elfo404** [comment]
@ivanahuckova I checked this again, and making it more explicit as we discussed breaks quite a few stuff in the query builder and it also highlighted how weak is the way we are assigning IDs to metrics and bucket aggregations. Since we are planning to remove the query_builder in a future (soon) release I'm merging this one as it is an create an issue to remind us to refactor the way we generate IDs

**Comment by ivanahuckova** [comment]
Yes, makes sense :)

**Pull request merged**
