### PR TITLE
Patch: 4 tooltip bugs

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

4 tooltip bugs corrected here in this PR :
- Order tooltip by yaxis by default #6174 ;
- Keep tooltip values format when reordering #6208 ;
- Hover correct points when reordering ;
- Correctly sort tooltip even with hidden series.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Also soves #6208 👍

**Comment by benrubson** [comment]
Thx @torkelo 👍

**Comment by torkelo** [comment]
had to revert the sorting by yaxis by default as it changes the order of the series (dont understand why really).

https://github.com/grafana/grafana/issues/6648

Might need a specific sort order option for yaxis

**Comment by benrubson** [comment]
Really strange.
We could try to get sorting by yaxis by default without breaking the order of the series.
Could you then re-open #6174 please ?

**Comment by benrubson** [comment]
See #6683.

**Pull request merged**
