### PR TITLE
fix CloudWatch id validation

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/pull/11624#issuecomment-428257734

### CODE REVIEW

**Review by daniellee — APPROVED** [review]

**Comment by mtanda** [comment]
thanks

**Comment by gipeshka** [comment]
Sorry for getting into this, but it is a bug of 5.3-beta, maybe it makes sense to put it into 5.3 milestone/version?

**Comment by gipeshka** [comment]
Sorry for getting into this, but this is a bug of 5.3-beta, maybe it makes sense to put this into 5.3 milestone/version?

**Comment by marefr** [comment]
@gipeshka thanks. It will be included in 5.3 stable

**Pull request merged**
