### PR TITLE
Storybook: Sort icons by name

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Currently it's quite challenging to find an icon in the list by name as there's a lot of them and the list isn't sorted.
Also fixed a bug with missing keys when rendering icons.

### CODE REVIEW

**Review by tskarhed — APPROVED** [review]
Looks good! Maybe we should have the possibility to search too?

**Comment by Clarity-89** [comment]
@tskarhed that sounds like a good idea, do you know if there's any plugins for that or how were you thinking to implement that?

**Comment by tskarhed** [comment]
@Clarity-89 I was just thinking about implementing it in the story. Just an input with a simple string search updating relevant results accordingly.

**Comment by Clarity-89** [comment]
Sounds good, I'll add it to this PR.

**Comment by Clarity-89** [comment]
Added some basic search. Also simplify the rendering code, don't think we need to render the icons in rows, as display flex with wrap aligns them nicely on all screen sizes. 

Screenshot 2020-03-26 at 19 45 43
Screenshot 2020-03-26 at 19 45 35

**Review by tskarhed — APPROVED** [review]
This is awesome! Good job! :smile:

**Pull request merged**
