### PR TITLE
Fix for org quota update

### LINKED ISSUE #14342: User/Org quota updating request fails when it is called multiple time
### What Grafana version are you using?

On the edge: 3c330c8e4c0b0f9fb258801ba8a7fe2586bbc819

### What datasource are you using?

N/A

### What OS are you running grafana on?

Linux and macOS with MySQL

### What did you do?

Request updating quota multiple time.

### What was the expected result?

It accepts a request and updates contents certainly.

### What happened instead?

A request is failed from the second time.

#### Client side error

```
$ curl -XPUT -H'Content-Type: application/json' -H'Accept: application/json' -H'Authorization:Basic XXXXXX' localhost:3000/api/orgs/1/quotas/org_user -d '{"limit":123}'
{"message":"Organization quota updated"}
$ curl -XPUT -H'Content-Type: application/json' -H'Accept: application/json' -H'Authorization:Basic XXXXXX' localhost:3000/api/orgs/1/quotas/org_user -d '{"limit":456}'
{"message":"Failed to update org quotas"}
```

#### Server side error

```
t=2018-12-05T13:34:54+0000 lvl=eror msg="Failed to update org quotas" logger=context userId=1 orgId=1 uname=admin error="UNIQUE constraint failed: quota.org_id, quota.user_id, quota.target"
t=2018-12-05T13:34:54+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/orgs/1/quotas/org_user status=500 remote_addr=172.17.0.1 time_ms=26 size=41 referer=
```

----

I've already prepared a patch. So if you don't mind, I can create a pull-request.
https://github.com/grafana/grafana/compare/master...moznion:fix_quota_updating?expand=1

### PR DESCRIPTION
**Pull request by torkelo**
Quota update now works as expected, fixes #14342

### CODE REVIEW

**Comment by moznion** [comment]
I've noticed you at #14342 

> I've already prepared a patch. So if you don't mind, I can create a pull-request.
https://github.com/grafana/grafana/compare/master...moznion:fix_quota_updating?expand=1

Does this patch have any problem?

**Comment by torkelo** [comment]
no, I did not notice that comment. Can you open a PR?

**Comment by torkelo** [comment]
I opened a PR with your fix, as it's better :)

**Comment by moznion** [comment]
Thanks a lot!

**Pull request closed without merging**
