### PR TITLE
Logs Panel: Add option extra UI functionality for log context

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

This PR fixes a bug where the `closeCallback` was not properly called.

Furthermore, it adds support for the `getLogRowContextUi` functionality. This allows log context in dashboards to show an extra UI e.g. for Loki data sources.

**Special notes for your reviewer:**

1. Open a logs panel in a dashboard
2. Open log context
3. You should see the extra filters for Loki now

FYI, this fixes a bug, thus I am also backporting this to v10.4.x.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
Code looks good, and I'm seeing the labels show up now, but every line has "no unique labels", besides the selected log line. I guess this is just a consequence of what a context-query is, but it makes me wonder why we display the label set inline within the table row and not somewhere else since they are always guaranteed to be the same across all logs?
image

Also I can trick the hover state to showing on multiple rows simultaneously, but that appears to be an issue on ops as well as this branch.
image
image

**Comment by svennergr** [comment]
> Code looks good, and I'm seeing the labels show up now, but every line has "no unique labels", besides the selected log line. I guess this is just a consequence of what a context-query is, but it makes me wonder why we display the label set inline within the table row and not somewhere else since they are always guaranteed to be the same across all logs?

That's just the implementation of the `LogRow` component - the same that is used in the logs visualisation in Explore and in Dashboards. With e.g. the `gdev-loki` datasource you see unique labels - in that case the "traceId".

image

**Comment by svennergr** [comment]
> Also I can trick the hover state to showing on multiple rows simultaneously, but that appears to be an issue on ops as well as this branch.

Yea, I can reproduce that. Will take a look.

**Comment by svennergr** [comment]
@gtk-grafana Sorry for the spam, but you are missing this piece in the screenshot. Basically this PR is about adding that UI component.
image

Can you confirm, that you don't see that component for a Loki data source?

**Comment by gtk-grafana** [comment]
False alarm! My frontend didn't appear to be building, after re-running yarn install && yarn start it shows up now.
image

**Review by gtk-grafana — APPROVED** [review]

**Pull request merged**
