### PR TITLE
AsyncSegment: Allow custom "no options" messages

### PR DESCRIPTION
**Pull request by Willena**
**What this PR does / why we need it**:

In AsyncSegment, some text is displayed when loading, on error, when no value is present. The "state to text" mapping is done in the `mapStateToNoOptionsMessage` method.  I think it would be nice if this mapping can be user customizable. It can be useful in plugins development to display a custom message during loading, when an error occurred or when no values are available. 

**Which issue(s) this PR fixes**:

No similar issues found. 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
@Willena thanks for your contirbution. This seems like an interesting idea. Do you mind adding a scenario to storybook so that we can see the effect of your changes?

The story you need to update is this one: https://developers.grafana.com/ui/latest/index.html?path=/story/data-source-segment-segmentasync--array-options

You can find the relevant code here: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Segment/SegmentAsync.story.tsx

**Comment by Willena** [comment]
Yes no problem, I'll add a new scenario very soon.

**Review by dprokop — APPROVED** [review]
Tested and it works good!

Please merge with master.

**Comment by Willena** [comment]
Oops I might have misinterpreted your message and I think I made a mistake... I updated my branch with all the changes from master (as the comment said), but wasn't a good idea. As a result of this mistake, all reviewers were added and all changes from master were added to this PR. 

I force pushed my original changes to revert to the previous state. But I could not remove the unnecessary reviewers. I'm sorry for all reviewers that were added without any "reason".

**Comment by dprokop** [comment]
@Willena PR is still failing, it needs sync with the master branch due to https://github.com/grafana/grafana/pull/32527 merged on Friday.

**Pull request merged**
