### PR TITLE
Reverse proxy: Skip flaky test for 5xx status codes

### PR DESCRIPTION
**Pull request by eleijonmarck**
Reverse proxy disable flaky test - [proxyutil/reverse_proxy_test.go](https://github.com/grafana/grafana/pull/95839/files#diff-09ee8ea28dc6395b479e07884e32b941a967dc219a32a83ff7a0485d4bbf7d10)

https://drone.grafana.net/grafana/grafana-enterprise/78522/4/7

### CODE REVIEW

**Comment by wbrowne** [comment]
@eleijonmarck Is this just for one occurrence? Just trying to get a sense of how flaky it is

**Comment by eleijonmarck** [comment]
@wbrowne i seem to recall to have seen it once before

**Review by wbrowne — APPROVED** [review]
Needs investigation so will +1 and see if can reproduce

**Review by xnyo — APPROVED** [review]

**Comment by xnyo** [comment]
> Needs investigation so will +1 and see if can reproduce

I couldn't reproduce either. Maybe related to this? https://github.com/grafana/grafana/pull/47957

**Pull request merged**
