### PR TITLE
Add monitoring mixing for Grafana

### PR DESCRIPTION
**Pull request by bergquist**
A foundation for monitoring Grafana instances. This will be deployed into our cloud env

Todo
 - [x] dashboard
 - [x] recording rule
 - [x] alert rule
 - [x] rewrite the make file into bash script for CI

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM, but why do we need to upgrade Go modules?

**Comment by bergquist** [comment]
No we shouldn't I think that was just because I installed mixtool within the grafana dir and bluntly fixed the go.mod problems.

**Review by tomwilkie — APPROVED** [review]

**Comment by bergquist** [comment]
Adding to 7.3.0 milestone be included in the changelog but this doesn't have to be cherry-picked since it wont be part of the Grafana package.

**Comment by kylebrandt** [comment]
(Removed CP label based on Carl's comment.)

**Pull request merged**
