### PR TITLE
Page: Remove footer from new page layout

### PR DESCRIPTION
**Pull request by torkelo**
Problem I am trying to solve: 

On scene pages where the height of panels adapts to the available space the footer takes valuable vertical space that could be used for visualizations and page content, normal dashboards, panel edit and explore don't show the footer for this reason. So one solution is to hide the footer on most pages other than maybe admin pages. 

This PR
* [x] Remove footer from the topnav Page.tsx standard layout 
* [x] Add the edition and update links to help menu (only footer links missing from help menu)
* [x] Show icons in topnav menu dropdowns (We only showed external link icon before, the rest was missing icons, this led to a mix of items with and without icons leading to anunaligned and messy look). Support bundles is a link in Help for example that was missing icon as it linked to internal page. 

Problem example: 
Screenshot from 2023-02-20 14-26-47

Footer links are shown in help menu (except for link to licence page which we could add to help menu) :    
Screenshot from 2023-02-20 14-31-23

### CODE REVIEW

**Comment by ashharrison90** [comment]
> but I think a better and more universal option would be to simply hide it on ALL pages as this information is already available in the help menu in the topnav / navbar.

+1 for doing this instead. then the changes just become removing `<Footer />` from `PageNew` right?

**Comment by torkelo** [comment]
> +1 for doing this instead. then the changes just become removing <Footer /> from PageNew right? 

@ashharrison90 yes, I think so

**Comment by amy-super** [comment]
I agree with removing it altogther - the version is available elsewhere. Let's free up some space. 

Though it might be nice to put the license type in the Help menu with the version for quick looks. Otherwise, users have to go find it in the Admin section.

**Comment by torkelo** [comment]
@amy-super awesome! will update this PR with the change to remove footer, and make sure the Help menu has all the needed info. Will leave the footer on the login page, as it is used by custom branding (enterprise) add more links there which I think some customers use (also already added to help menu).

**Comment by torkelo** [comment]
@joshhunt @ashharrison90 updated this PR to remove the footer

**Review by joshhunt — APPROVED** [review]
Yay. Inconsistent footer bothered me, glad this stuff is more visible elsewhere.

**Pull request merged**
