### PR TITLE
chore: Update golangci-lint to v1.45.2

### PR DESCRIPTION
**Pull request by mem**
Version 1.45.0 added support for Go 1.18:

https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md#v1450

Using previous versions causes an error like:

```
pkg/services/sqlstore/migrator/mysql_dialect.go:10:2: could not import github.com/VividCortex/mysqlerr (-: could not load export data: cannot import "github.com/VividCortex/mysqlerr" (unknown iexport format version 2), export data is newer version - update tool) (typecheck)
	"github.com/VividCortex/mysqlerr"
	^
```

Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>

### CODE REVIEW

**Comment by gabor** [comment]
NOTE: when i run this locally, it solves the problem, but it generates some (probably legitimate) linter-errors. i wonder why it does not generate them in the CI?

**Comment by mem** [comment]
> NOTE: when i run this locally, it solves the problem, but it generates some (probably legitimate) linter-errors. i wonder why it does not generate them in the CI?

My guess: CI uses a different version of golangci-lint, but in the checks that ran with this PR I don't actually see golangci-lint running anywhere (I might have just missed it).

**Comment by gabor** [comment]
i updated the linter-version in the ci-job too.

**Comment by gabor** [comment]
so, the story so far:
- to use go1.18 with `make lint-go`, we need to upgrade `golangci-lint` to a newer version
- if we switch to the newer version of the linter, there are new linter errors
- as first step, we should fix those linter errors
- i will ping all the squads that own the given files that have errors. please, when you find some time for this:
    - checkout this branch, and run `make lint-go` (you can do it with go1.17 too)
    - fix the linter-errors in "your" files, and commit those fixes to main-branch (not into this PR)
    - add a comment here that it has been fixed
- when all of them are fixed, we can merge this PR
- (and then we can start working on updating the CI-job's `golangci-lint` version too

@grafana/grafana-edge-squad  
- [ ] pkg/services/live/pushws/push_pipeline.go
- [ ] pkg/services/live/pushws/push_stream.go
- [ ] pkg/services/live/pushws/ws.go
- [ ] pkg/services/searchV2/extract/dashboard_test.go

@grafana/backend-platform 
- [ ] pkg/api/alerting.go
- [ ] pkg/services/contexthandler/contexthandler.go

@grafana/alerting-squad-backend 
- [ ] pkg/services/alerting/notifiers/hipchat.go

@grafana/grafana-release-eng 
- [ ] pkg/build/fs.go

thanks!

or, if you have an idea how to achieve this in a better way, just tell :)

**Comment by ying-jeanne** [comment]
backend platform fixes is done here : https://github.com/grafana/grafana/pull/47623

**Comment by lean257** [comment]
For edge squad, I ran `make lint-go` in this branch with `go1.18.1` and `golangci-lint version 1.45.2` and did not see any errors with these requested files. Would you be able to double check and confirm the errors are still there? 
* pkg/services/live/pushws/push_pipeline.go
* pkg/services/live/pushws/push_stream.go
* pkg/services/live/pushws/ws.go

**Comment by armandgrillet** [comment]
Not my team but https://github.com/grafana/grafana/pull/49357 open for `pkg/build/fs.go`.

**Comment by armandgrillet** [comment]
Looks like this is ready to go according to https://github.com/grafana/grafana/pull/47156#issuecomment-1094995320 👍.

**Review by sakjur — DISMISSED** [review]

**Comment by gabor** [comment]
keep it open pls.

**Comment by joeblubaugh** [comment]
keep it open please

**Comment by joeblubaugh** [comment]
@gabor are we ready for this? All the checkboxes are checked.

**Comment by gabor** [comment]
@joeblubaugh thanks for pinging me! actually, i did a quick check, and maybe we can just close this PR without merging. i ran `make lint-go` with go `1.19.1` and it produced no lint-errors. i assume the upgrades done in this PR happened already.

@mem would you agree that we can close this PR without merging?

**Pull request closed without merging**
