### PR TITLE
Docs: Update release-notes-7-5-3.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Fixed format errors. @gabor, please fix the code that correlates so they are not overwritten.

### CODE REVIEW

**Comment by gabor** [comment]
@oddlittlebird 

1. the change looks good to me, i just want to mention that the "colon is emphasied too" thing is not how it was done in the older release-notes. should we change the auto-generator for the changelog so that it will look like this automatically in the future?
2. your comment "please fix the code that correlates so they are not overwritten." , could you explain please? i do not understand 😿

**Comment by osg-grafana** [comment]
> @oddlittlebird
> 
> 1. the change looks good to me, i just want to mention that the "colon is emphasied too" thing is not how it was done in the older release-notes. should we change the auto-generator for the changelog so that it will look like this automatically in the future?
> 2. your comment "please fix the code that correlates so they are not overwritten." , could you explain please? i do not understand crying_cat_face

2. might mean, "Please change this upstream."

**Comment by oddlittlebird** [comment]
Yes, what @osg-grafana said

And yes, please change the colon in the generator as well.

**Review by gabor — APPROVED** [review]
looks good to me!

**Comment by gabor** [comment]
@oddlittlebird @osg-grafana i see. the changes that happen with this pull-request are "safe", nothing will overwrite them. whenever a release happens, only the changelog-file for the current release is modified (well, created), the old ones are not touched.

**Pull request merged**
