### PR TITLE
Add option to hide raintank share button

### LINKED ISSUE #2727: Disable raintank snapshot
It would be nice to be able to disable the possibility to make raintank snapshots, less confusion for users of a grafana  instance that runs on a server that does not have Internet access.

### PR DESCRIPTION
**Pull request by shoonoise**
I don't actually sure about my solution, but seems it should resolves #2727

### CODE REVIEW

**Comment by shoonoise** [comment]
@torkelo when you will have a time to look at the PR?

**Comment by torkelo** [comment]
Not sure, I think a better option would  be to have configuration to replace the button with another external receiver. So the configuration would be different, more like external_snapshot_url  external_snapshot_nane.  And I don't think the settings need to be global in frontend settings , could  be fetched lazily

**Comment by torkelo** [comment]
And a enable option you solve this case

**Comment by shoonoise** [comment]
>  I think a better option would be to have configuration to replace the button with another external receiver.

Seems sensibly. But if it option set as `None` or something like that, needs to hide the button. Are you agree?

> external_snapshot_nane
I'm sorry, what you mean?

> And I don't think the settings need to be global in frontend settings , could be fetched lazily
Ok, I'll work on it!

**Comment by torkelo** [comment]
Well I mean what the external button text should say. And yea, someway to disable the external snapshot feature as well

**Comment by shoonoise** [comment]
@torkelo hi! I updated the PR. Please look at this.

**Comment by torkelo** [comment]
nice, maybe an external_snapshot_enabled option?

**Comment by shoonoise** [comment]
@torkelo I believe that there is no need to add another one option, unset both of `external_snapshot_url` and `external_snapshot_name` will disable the button

**Comment by shoonoise** [comment]
@torkelo  May be it should be reflected in config comments.

**Comment by shoonoise** [comment]
@torkelo What do you think? I can add another one option if it really needed.

**Comment by torkelo** [comment]
not sure, I think i like external_snapshot_enabled just to make it more explicit and clear, 

Also maybe make it its own section?

```ini
[snapshots]
external_enabled = true
external_url = https://snapshots-origin.raintank.io
external_name =  Publish to snapshot.raintank.io
```

**Comment by shoonoise** [comment]
@torkelo Ok, look at the update.

**Comment by shoonoise** [comment]
@torkelo can I ask you for review?

**Comment by torkelo** [comment]
yes you can :)

**Comment by shoonoise** [comment]
@torkelo thank you :)

**Comment by shoonoise** [comment]
@torkelo when it would be released?

**Pull request merged**
