### PR TITLE
Alerting: Add escape and quote support to the matcher name

### LINKED ISSUE #83510: Alerting: Double quoting is not removed on left hand side of label matchers
In #81455, we added support for double quoting of the right hand side of label matchers. I must have forgotten to test this in the original PR, but we also need to use the same double quoting rules on the left hand side of label matchers too.

For example:

```
"bar with spaces"=baz🙂
"foo,bar"=baz
"foo,bar"=baz,"bar,baz"="qux"
```

is equivalent to:

```json
[
  {
    "name": "bar with spaces",
    "isEqual": true,
    "isRegex": false,
    "value": "baz🙂"
  }
]

[
  {
    "name": "foo,bar",
    "isEqual": true,
    "isRegex": false,
    "value": "baz"
  }
]

[
  {
    "name": "foo,bar",
    "isEqual": true,
    "isRegex": false,
    "value": "baz"
  },
  {
    "name": "bar,baz",
    "isEqual": true,
    "isRegex": false,
    "value": "qux"
  }
]
```

Screenshot 2024-02-27 at 12 39 05 PM

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
This PR fixes matcher name escaping and quoting

Fixes #83510

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
I tested this and it LGTM!

image
image

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM!

**Pull request merged**
