### PR TITLE
many-to-one requires explicit grouping

### PR DESCRIPTION
**Pull request by carlosjgp**
**What is this feature?**

Fix the current mixin Alert which is failing to be evaluated

The current query results in a many-to-one relationship which requires explicit grouping see more details here https://github.com/portefaix/portefaix-hub/pull/306

https://prometheus.io/docs/prometheus/latest/querying/operators/#many-to-one-and-one-to-many-vector-matches

**Why do we need this feature?**

It's currently broken

**Who is this feature for?**

Operators (people managing grafana)

**Which issue(s) does this PR fix?**:

#61664

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tonypowa** [comment]
hola @carlosjgp  
apologies for not taking action on this
i will internally ping the alerting team and send your open issue #61664  to them as well 👍

**Review by stevesg — APPROVED** [review]
LGTM

**Comment by carlosjgp** [comment]
Updated from upstream

**Comment by lpugoy** [comment]
Please see https://github.com/grafana/grafana/pull/63382/#issuecomment-1439132548.

**Pull request merged**
