### PR TITLE
Access control: Improve annotation delete performance

### PR DESCRIPTION
**Pull request by alexanderzobnin**
**What is this feature?**

This PR improves performance of annotation delete endpoint. 

**Why do we need this feature?**

When number of dashboards available to user is significant, there's a performance degradation. We simply use dashboard IDs/UIDs as a filter for access control query. This is inefficient in case of one annotation since it's only linked to one dashboard. So reducing filter to specific dashboard fixes a problem.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/identity-access-team/issues/606

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by eleijonmarck** [comment]
@alexanderzobnin would you mind posting some kind of time improvement of the query before and after?

**Comment by alexanderzobnin** [comment]
I didn't perform any specific load tests, but the problem was in `WHERE IN` filter size (depends on number of available dashboards). Now it's constant (1 dashboard), so it's linear vs constant time.

**Review by IevaVasiljeva — APPROVED** [review]
Nice! My only issue is with adding more DB query logic to `pkg/services/annotations/accesscontrol/accesscontrol.go` - it feels like maybe it would be better placed in annotation store 🤔 But no strong objections.

**Comment by alexanderzobnin** [comment]
@IevaVasiljeva I'll check it out, this is more a "dirty quick fix", but maybe there's a better way.

**Comment by alexanderzobnin** [comment]
@IevaVasiljeva well, I've found that it would be better to pass store into annotation accesscontrol implementation, but there's a problem - import cycle, so the annotations implementation needs to be refactored (store type could be moved to the top level). I would prefer to merge this one since it requires backports and then refactor.

**Comment by alexanderzobnin** [comment]
There's a chicken and egg problem - if I want to use Get() method from store, it requires list of available dashboards from access control, but to get it, I need to get annotation dashboard from store first. So I leave it as is, probably.

**Pull request merged**
