### PR TITLE
Elasticsearch: Implement modify query using a Lucene parser

### LINKED ISSUE #61765: Logs: Easier search and filter from log lines
### Summary

It's been mentioned that it would be useful for users to be able to filter log lines by clicking on parts of them which could add or remove labels from the query. It seems like a very interactive way of exploring data, which could enhance the logging experience for all of our users.

This feature was also identified during an internal UX exploration excercise.

Design doc: https://docs.google.com/document/d/1SZ6z6aI167mJY-0A0SCda204QixeBOYVoZi_SBK8ilU/edit

### Scope

We need to explore the technical feasibility of toggling filters by interacting with log lines and, with those results, work with UX to develop a proposal to support this feature.

### Solution

With the results of the technical exploration of this feature, we will work in combination with UX to come up with the best possible way to support interactive log filtering from long lines. The end result will be the availability of this feature for users, provided that UX and engineering concludes that it's something that we can support.

### Measurement

Users should interact with this feature, hopefully improving the way they filter and search through log lines. Metrics TBD.

### Resources

### LINKED ISSUE #72008: Dashboards: Adhoc filter does not work with double quotes
### What happened?

When I click on "filter for value" on a text value that contains double quotes, it shows nothing. If I escape these quotes in ad hoc filter, then the data is displayed.

https://github.com/grafana/grafana/assets/82204499/7dd94bd3-f25c-4f52-9da5-c6cf9f24ad60

I noticed that Grafana versions 9.1 and 10.0 use different queries for elasticsearch when using ad hoc filters.
It differs in that a separate parameter was used earlier `\"must\":[{\"match_phrase\":` But now the ad hoc filter is just added to the request
For 9.1:
```
data:"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"rx-log-error*\"}
{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1689845161005,\"lte\":1689848761005,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"logLevel: Error AND exceptionType: (\\\"critical\\\" OR \\\"noncritical\\\" OR \\\"unknown\\\")\"}}],\"must\":[{\"match_phrase\":{\"genericMessage\":{\"query\":\"Нет прав на выполнение операции \\\"{S}\\\" на \\\"{S}\\\" с ИД={N}.\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"genericMessage\",\"size\":500,\"order\":{\"_count\":\"desc\"},\"min_doc_count\":1,\"missing\":\"Empty\"},\"aggs\":{}}}}
"
```
For 10.0:
```
data:"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"rx-log*\"}
{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1689762519433,\"lte\":1689848919433,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"logLevel: Error AND genericMessage:\\\"Cannot unlock: the item \\\"{S}\\\" with ID {N} was not locked.\\\"\"}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"genericMessage\",\"size\":500,\"order\":{\"_count\":\"desc\"},\"min_doc_count\":1,\"missing\":\"Empty\"},\"aggs\":{}}}}
"
```

### What did you expect to happen?

The data should be filtered, including the value with double quotes

### Did this work before?

It worked in grafana versions 9.0.x, 9.1.x, 9.2.x
9.3 and higher does not work

### How do we reproduce it?

1. There must be a value with text data that contains double quotes
2. On the table panel, click "filter for value" or "filter out value".

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.0.2
OS: Linux Ubuntu (Grafana-oss in docker)
Browser: Chrome 114

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch 7.16

### PR DESCRIPTION
**Pull request by matyax**
In previous PRs we improved the ability to add and remove filters in Elasticsearch using Log Details controls. Now, we're changing the regex-driven implementation to one using a Lucene parser to read and modify the query. 

Additional changes:
- Removed the feature flag `elasticToggleableFilters` which is currently not in use, replaced with `toggleLabelsInLogsUI` which controls access to this feature.
- We are now using Lucene to parse terms and values in filters.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/61765
Fixes https://github.com/grafana/grafana/issues/72008

**Special notes for your reviewer:**

- Enable the feature flag elasticToggleableFilters.
- Play with the 🔍  icons from the Log Details component.

### CODE REVIEW

**Comment by matyax** [comment]
BTW I will deal with the merge conflicts after the review because depending on how long it takes I might have to do it more than once otherwise.

**Comment by matyax** [comment]
@gwdawson This could be a fun PR to review.

**Review by itsgareth — APPROVED** [review]
i would like to see a couple of tests for `removeNodeFromTree` but other than that, it LGTM!
i think this is a great improvement. 🎉

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
I tried to add this test related to whitespace between `:` - `expect(queryHasFilter('(this:"that" OR test :test) AND label:value', 'test', 'test')).toBe(true);`, but it returns false. It should return `true`, right?

**Comment by matyax** [comment]
> I tried to add this test related to whitespace between : - expect(queryHasFilter('(this:"that" OR test :test) AND label:value', 'test', 'test')).toBe(true);, but it returns false. It should return true, right?

According to the parser, that is not a valid query. We can workaround it with the normalization, but maybe we shouldn't support queries written in that way.

As for now, the code has been updated to support it.

**Comment by matyax** [comment]
> i would like to see a couple of tests for removeNodeFromTree
`removeFilterFromQuery` test cases are taking care of covering that code.

**Review by ivanahuckova — APPROVED** [review]

**Pull request merged**
