### PR TITLE
Fixed capitalization of 'volumes'

### PR DESCRIPTION
**Pull request by seanluce**
'Microsoft.NetApp/netAppAccounts/capacityPools/Volumes'  -> 'Microsoft.NetApp/netAppAccounts/capacityPools/volumes'

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kylebrandt** [comment]
Does this actually fix an error, or does it only update it match the documentation? (Not to say it is not good either way, but do not have the resource handy to test against, and curious if the calls are case sensitive or not).

**Comment by seanluce** [comment]
Possibly related to: https://github.com/grafana/grafana/issues/28350

https://docs.microsoft.com/en-us/azure/templates/microsoft.netapp/2019-07-01/netappaccounts/capacitypools/volumes#property-values

**Comment by seanluce** [comment]
> Does this actually fix an error, or does it only update it match the documentation? (Not to say it is not good either way, but do not have the resource handy to test against, and curious if the calls are case sensitive or not).

I am trying to figure out how I can test this. I do not that regardless of Azure Subscription, I cannot get a panel created for Azure NetApp Files' Volumes.

**Review by kylebrandt — APPROVED** [review]
Thank you

**Pull request merged**
