### PR TITLE
Annotations: Correct annotations that are displayed upon page refresh

### LINKED ISSUE #37160: Wrong annotations show on a given dashboard. Correct annotations show on page refresh.
### **What happened**:

- I created an annotations panel on my main (homepage) dashboard. 
- I clicked on an annotation which exists on another dashboard.
- Grafana loads that dashboard, but with the wrong annotations.
- When I refresh the page, the right annotation appears.

I load a dashboard with Annotations. It shows annotations on panels that were not created on that dashboard or those panels:
Screen Shot 2021-07-22 at 7 55 14 PM

When I refresh the page, the right annotation(s) load:
Screen Shot 2021-07-22 at 7 55 30 PM

### **What you expected to happen**:
- I select a dashboard, it should load the correct annotations.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an annotation on a panel in a dashboard
- Leave and come back to that dashboard. Wrong annotations show.
- Refresh dashboard. Right annotations shown.

### **Anything else we need to know?**:

- Grafana version: 8.1.0-beta2
- Data source type & version: CloudWatch
- OS Grafana is installed on: Used docker (grafana/grafana:8.1.0-beta2)
- User OS & Browser: MacOS/Firefox

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

A [new change](https://github.com/grafana/grafana/pull/36377/commits/460ebabac764092f236847995b49250c03cdb926#diff-f1386ecf8e451a84d16e901593385dbecf86e95242c70084a41c1c43f37830a9R55) was introduced for v8.1.0 in built-in annotations, there we started to use this method [`getDashboardSrv().getCurrent()`](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana/datasource.ts#L55) to get the current dashboard instance, and then with the `dashboardId` query the API to get the list of annotations that belong to that dashboard. 

The issue was that when we render let's say dashboard `A` and move back to the parent, the instance of that dashboard `A` is not being cleaned, so next time when we visit another dashboard, let's say Dashboard `B`, the following methods from [initDashboard](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/initDashboard.ts#L198) are being called:

```
    const runner = createDashboardQueryRunner({ dashboard, timeSrv });
    runner.run({ dashboard, range: timeSrv.timeRange() });
```

Where this `runner.run` in one point is calling the `query` method from the Grafana datasource used in the built-in annotations, but when this happens the `getCurrent()` dashboard is having the old reference (because was not properly cleaned), that results in calling the API with the wrong dashboard id.

https://user-images.githubusercontent.com/239999/128041377-334581bd-762b-4778-8d7b-2451aaa892bd.mp4

My current PR is a hack, I am moving the `dashboardSrv.setCurrent(dashboard)` before we run the DashboardQueryRunner. This will update the instance and the API will have the right dashboard ID.

The ideal solution will be to clean the old instance when the user moves back to the parent, but I could not find a way to do it :(.

*The hack, seems to work, but I am lacking a lot of context and knowledge in this part of the code.*

https://user-images.githubusercontent.com/239999/128041657-7fad7062-355c-454b-b39b-9f255634055c.mp4

**Which issue(s) this PR fixes**:

Fixes #37160

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by torkelo** [comment]
Nice job finding this one!

**Comment by axelavargas** [comment]
🤔 it seems the hack should not happen, one of the tests scenarios on `initDashboard` is explicitly saying I should not do this 😅  https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/initDashboard.test.ts#L292

Either I skip the test, or find a way to clean up the instance of the dashboard when moving back, @torkelo do you maybe know the reason behind this unit test?

**Comment by torkelo** [comment]
@axelavargas that test is very strange think you can remove the test  `it('Should not initialize other services`

**Review by tskarhed — APPROVED** [review]
I managed to reproduce the bug with next gen alerting. It seems to have been fixed with this PR! 😄

**Review by ashharrison90 — APPROVED** [review]
i tested the scenario hugo originally had in https://github.com/grafana/grafana/pull/24430 with slow loading dashboard variables and it seems to be working as expected, so all behaviour seems to be working fine. good job alexa! 🙌

**Comment by axelavargas** [comment]
@tskarhed @ashharrison90 Thanks a lot for testing this PR 🙌🏾

**Pull request merged**
