### PR TITLE
PostgreSQL: include numeric column type in Query Builder metaquery

### LINKED ISSUE #43444: [PG 12+] Grafana 8.3.3 - Numeric, boolean, and text columns not displaying in dropdown
### Discussed in https://github.com/grafana/grafana/discussions/37009

<div type='discussions-op-text'>

<sup>Originally posted by **mindfuucker** March 22, 2019</sup>

What happened:
I just installed grafana to connect to my postgresql database.
Installed the 6.0.0 beta3 version because I hoped postgreSQL 11 would be supported.

Created my first dashboard, added a graph and tried to select a Numeric(5,3) column. Only integer columns were displayed in the dropdown.

Manual adding of the column name displays the graph without any problems. Problem is just the dropdown.

What you expected to happen:
A dropdown containing all columns (numeric and integers).

How to reproduce it (as minimally and precisely as possible):
Install grafana 6.0.0 beta3
install postgresql 11.2
create table with numeric values.
Add dashboard, graph and select column.

Anything else we need to know?:
Table is partitioned using native postgresql 11 partitioning.

Environment:

Grafana version: 6.0.0 beta3
Data source type & version: PostgreSQL 11.2
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser: Firefox
Grafana plugins: none
Others: none

</div>

This is created out of the issue that was originally reported in the above linked discussion and continues to be unresolved to this point in time. 

**What happened**:
We host a Grafana instance that connects to a PostgreSQL database, and attempt to create panels and dashboards that display the information stored in the database.

When creating a panel connected to a a PostgreSQL data source and selecting a table that has numeric, boolean, or textual columns that represent valid data, the names of these columns do not show up in the selectable panel dropdown UI as valid values for the "Column" subfield of the SELECT clause. The column names that do show up in the dropdown  are for integer and real columns. 

Manually adding the columns names successfully retrieves the data from the database and displays it in the panel. The problem is just in displaying all the appropriate/available options in the dropdown menu. 

**What you expected to happen**:
The dropdown menu for Column selection in the SELECT clause of the panel query creation UI to display ALL possible columns from the table that could contain data of interest for creating graphs, tables, and other panels. This includes columns of numeric type, as well as booleans and text fields as well (the data we deal with has enumeration types, which are stored in their converted textual format).

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 8.3.3
install postgresql 13.5
create table with numeric, boolean, and textual values.
Add dashboard, graph and select column. 

**Anything else we need to know?**:
PostgreSQL data source is using TimescaleDB plugin 

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: PostgreSQL 13.5
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome
- Grafana plugins: pierosavi-image-it

### PR DESCRIPTION
**Pull request by nick-bowman**
Originally, the metaquery used in the PostgreSQL plugin to populate the
column dropdown menu in the Query Builder UI only included integer- and real-typed
columns. This change expands the list of acceptable types for plotting to
include numeric columns, boolean columns, and textual columns, as all are
types that could feasibly be desired to plot in a panel.

**What this PR does / why we need it**:
This PR expands the list of types of columns in a PGSQL table that are considered by the Query Builder meta query in the PostgreSQL plugin, which consequently affects what columns are shown in the UI dropdown menu for the SELECT clause of queries that are being built. Previously, only integer and real typed columns were shown – with this change, numeric, boolean, and textual columns will also be included.

**Which issue(s) this PR fixes**:
Fixes #43444 

**Special notes for your reviewer**:
This is a simple one-line change, so I don't expect much additional information to be necessary. 

Here is an example of the dropdown menu for one of our tables that has many different data type columns before the change
image

And here is an example of the dropdown menu for the same table after the change
image

### CODE REVIEW

**Comment by nick-bowman** [comment]
Sorry if this is mentioned in the documentation somewhere and I'm just missing it, but what is the necessary action in order to set a milestone for this PR? Is that something I can do myself or something that would have to be done by the approver?

**Comment by papagian** [comment]
@grafana/grafana-bi-squad has more context to review this one.

**Comment by zoltanbedi** [comment]
Hi @nick-bowman,
Thanks for creating a PR with such a detailed description. I understand that the visual query builder can't be used to create simple queries right now. It was designed to create time series queries that is why the columns selector only queries numeric data types. I've tried your change and when I select a non numeric column from the dropdown with time series format I see a backend error like this:
`convert value to float failed: metricIndex 2 type []*bool can't be converted to float`
Also I think that when you select a non numeric column the aggregation selector should not show up as that doesn't make sense.

I'm sorry but I can't accept your pr like this.

We are working on a visual query editor for SQL datasources but I can't give you an ETA sadly. If you can't wait for that and want to work on this more I'm happy to help you.

**Comment by nick-bowman** [comment]
Hi @zoltanbedi!

Thank you for your feedback and for reviewing this PR, I appreciate it. 

Your comments regarding the issues with including `boolean` and `text` types as part of the meta-query builder make a lot of sense – the type conversions and aggregation do not play well with these, so it would not make sense to include them as part of this component. 

However, I do believe including the `numeric` type as part of the query builder still makes sense, and does not raise the same issues you mentioned regarding selection of non-numeric columns. I have updated the code change to only add `numeric` types to the drop down menu via the meta query builder. 

With this change, would you be amenable to accepting the PR? Let me know what you think!

**Comment by zoltanbedi** [comment]
> With this change, would you be amenable to accepting the PR?
Yep, this makes sense. Thank you!

**Review by zoltanbedi — APPROVED** [review]

**Comment by nick-bowman** [comment]
@zoltanbedi Great, thank you very much!

**Pull request merged**
