### PR TITLE
DevEnv: update frontend dependencies - react-hot-loader

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Mar 23 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `react-hot-loader` - changes (4.8.0 -> 4.12.20): https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by tskarhed** [comment]
I get this waning, not related to the update though.
```
react-hot-loader.development.js:2375 React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
```
I think I never had hot reload work in Grafana. Why is that?

**Comment by Estrax** [comment]
@tskarhed that's probably because we don't have an appropriate react-dom alias set in our webpack config. Should be something like `resolve: { alias: { 'react-dom': '@hot-loader/react-dom'  } }`. I'll check that soon.

**Comment by dprokop** [comment]
@Estrax do you mind syncing this with master? I see some TS namespace errors when running `yarn start:hot` that should be already fixed on master

**Comment by Estrax** [comment]
@dprokop there you go. Updated.

**Comment by dprokop** [comment]
@Estrax I'm experiencing issues with Angular bootstrap when running `yarn start:hot`:
```
VM7533 angular.js:116 Uncaught Error: [ng:btstrpd] App already bootstrapped with this element 'document'
http://errors.angularjs.org/1.6.9/ng/btstrpd?p0=document
    at eval (VM7533 angular.js:116)
    at doBootstrap (VM7533 angular.js:1936)
    at Object.bootstrap (VM7533 angular.js:1976)
    at GrafanaApp.init (VM7147 app.ts:202)
    at eval (VM7146 dev.ts:14)
    at Module../public/app/dev.ts (VM7106 app.c3f9be2e07ef5c5ab6eb.js:22652)
    at __webpack_require__ (VM7106 app.c3f9be2e07ef5c5ab6eb.js:770)
    at fn (VM7106 app.c3f9be2e07ef5c5ab6eb.js:130)
    at Object.0 (VM7106 app.c3f9be2e07ef5c5ab6eb.js:27774)
    at __webpack_require__ (VM7106 app.c3f9be2e07ef5c5ab6eb.js:770)
```

**Comment by Estrax** [comment]
@dprokop weird. No errors on my end while running the same command. Maybe that's due to something in node_modules. Can you do a clean deps reinstall (and remove `public/build` content if you have anything there) and check it again?

**Comment by dprokop** [comment]
Yes, I'll do this:)

**Comment by dprokop** [comment]
@Estrax still can't run the app with yarn start:hot, this is super weird. Can you please someone elso to testi this too?

**Comment by Estrax** [comment]
Yep! @tskarhed & @mackn can you take a look at it?

**Comment by Estrax** [comment]
Yep! @tskarhed @mckn can you take a look at it?

**Comment by mckn** [comment]
> Yep! @tskarhed @mckn can you take a look at it?

Yes, I can have a look at it later today :)

**Comment by tskarhed** [comment]
I can run the app, but I'm getting invalid hook calls on a lot of pages. And it seems like there isn't a single page that is loaded correctly. And I get the same error as @dprokop 
Screenshot from 2020-04-02 10-37-49

**Comment by mckn** [comment]
I had a quick look at this and get the following errors:

errors

- The warning about the "react-🔥-dom patch is not detected" explains why some of the hooks errors occurs for you Tobias.
- The reason we get the error Dominik posted is because of this "WARNING: Tried to load AngularJS more than once.". I did some reading about when that happens and it can occur when angular tries to load a template that it can't find.

Both these two error makes me think that it is something wrong with our webpack configuration when running this. So maybe we can spend some time having a look at that one @dprokop ?

**Comment by Estrax** [comment]
Looks like the basic fixes from [react-hot-loader](https://github.com/gaearon/react-hot-loader) readme should do the job. Gonna check it soon.

**Pull request closed without merging**
