### PR TITLE
Elasticsearch: Adds cumulative sum aggregation support

### LINKED ISSUE #4130: Elasticsearch: Add Cumulative Sum Aggregation (Pipeline Agg)
i have a series that shows, say, the count of visitors over every 10 minutes
now i want to get the cumulative sum plotted
i understand i need to use pipelines for elasticsearch, but only see Derivative or Moving Average.

Any ideas on how to handle this?

### PR DESCRIPTION
**Pull request by retzkek**
Support cumulative_sum pipeline aggregation in Elasticsearch data source.

Fixes #4130

(Sorry it took so long to put this PR in)

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thanks. To be able to accept this backend code changes is needed as well to support cmulative sum to be used with Grafana Alerting. This can give some pointers to backend code https://github.com/grafana/grafana/search?l=Go&q=isPipelineAgg

Let us know if you need more help.

**Comment by retzkek** [comment]
:facepalm: sorry about that. I added it to the backend with tests, and did a functional test.

image

**Comment by retzkek** [comment]
Looks like circleci had some issues?

```
Starting container grafana/build-container:1.2.16
  image cache not found on this host, downloading grafana/build-container:1.2.16
1.2.16: Pulling from grafana/build-container
d51af753c3d3: Pulling fs layer
fc878cd0a91c: Pulling fs layer
6154df8ff988: Pulling fs layer
fee5db0ff82f: Pulling fs layer
38269bce5e46: Pulling fs layer
d034d5946a4f: Pulling fs layer
9b5c12c4f435: Pulling fs layer
8317b7f15c63: Pulling fs layer
7924a415b1cf: Pulling fs layer
d51af753c3d3: Waiting
9b5c12c4f435: Waiting
fc878cd0a91c: Waiting
8317b7f15c63: Waiting
d034d5946a4f: Waiting
fee5db0ff82f: Waiting
6154df8ff988: Waiting
38269bce5e46: Waiting
  error starting container grafana/build-container:1.2.16: Error: No such image: grafana/build-container:1.2.16

Error: No such image: grafana/build-container:1.2.16
```

**Comment by marefr** [comment]
Thanks, will test/review this next week.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana! Need to resolve some CI issues before we can merge this.

**Pull request merged**
