### PR TITLE
Geomap: Update documentation for 9.4

### PR DESCRIPTION
**Pull request by drew08t**
Update docs for 9.4 for Geomap.

Images being referenced:
1. https://grafana.com/media/docs/grafana/geomap-route-layer-basic-9-4-0.png
2. https://grafana.com/media/docs/grafana/geomap-route-layer-arrow-size-9-4-0.png

### CODE REVIEW

**Comment by drew08t** [comment]
I also noticed that when clicking a sub section like "Options" or "More Information" the page navigates to the first instance of each, because the section heads are not unique. Is this something we can address in this PR (please see below)?
Feb-10-2023 10-26-24

**Review by imatwawana — COMMENTED** [review]
Just made some small style edits

**Comment by nmarrs** [comment]
> I also noticed that when clicking a sub section like "Options" or "More Information" the page navigates to the first instance of each, because the section heads are not unique. Is this something we can address in this PR (please see below)?

I'm not sure there is an easy way to address this 🤔 one solution might be labeling each sub menu with a descriptor unique to that section (i.e. XYZ Options etc.) but not sure how ideal that is / repetitive. @grafana/docs-squad are you aware of a way to address this in markdown? Thanks!

**Review by nmarrs — APPROVED** [review]
🪄

**Comment by imatwawana** [comment]
Hey @drew08t, re: the linking issue from the page TOC, this definitely sems like 

> > I also noticed that when clicking a sub section like "Options" or "More Information" the page navigates to the first instance of each, because the section heads are not unique. Is this something we can address in this PR (please see below)?
> 
> I'm not sure there is an easy way to address this 🤔 one solution might be labeling each sub menu with a descriptor unique to that section (i.e. XYZ Options etc.) but not sure how ideal that is / repetitive. @grafana/docs-squad are you aware of a way to address this in markdown? Thanks!

The solution you've suggested is the only thing that would fix it in the markdown, but I'm hesitant to make that change because of the repetition that you bring up. I'd suggest opening this as in issue in on the website repo to see if there's something that can be fixed in the way the page is built or if we do have to reassess how we're building the page infrastructure.

**Review by imatwawana — APPROVED** [review]

**Pull request merged**
