### PR TITLE
Secrets: Fix unified secrets backwards compatibility

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

This PR makes it so we keep updating secrets on the data source table for backwards compatibility between 8.x and 9.x to allow for rollbacks.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by undef1nd — APPROVED** [review]

**Review by joanlopez — DISMISSED** [review]

**Review by joanlopez — CHANGES_REQUESTED** [review]
Changes present here look good, but aren't there more places where secrets are stored into the `SecretsKVStore`? (For instance, at data source creation).

Could you review & confirm it, please? Thanks!

**Comment by guicaulada** [comment]
@joanlopez I have added the fix to the AddDataSource function as well, usually I haven't seen SecureJsonData being sent on the cmd for that function by Grafana, but using the API it's probably possible to create Data Sources with SecureJsonData in place. Again.. I think it's better to be safe than sorry at this point since the changes are minimal.

**Comment by joanlopez** [comment]
@guicaulada I haven't had time to test it, but after looking at your commit https://github.com/grafana/grafana/pull/49719/commits/8d8701afeeccf2ad72da82a49952661bd4cf8493 I think part of the fix that @undef1nd mentioned is still not correct. Note that at `MigrateSecrets` you're decrypting every `v` in `ds.SecureJsonData` but the commit she mentioned https://github.com/grafana/grafana/pull/41704 was decrypting only the secrets not present in the incoming `UpdateDataSourceCommand.SecureJsonData`.

The rationale behind that idea is that in case one specific secret cannot be decrypted (e.g. got corrupted), it could still be updated from the Grafana UI -- that's why she suggested to decrypt only the ones not present in the incoming command, and take the remaining from it.

I guess same behavior could apply to some use cases of `MigrateSecrets` method, because I guess it does not make sense to decrypt and save into the `SecretsKVStore` the secrets that are already about to be saved through `UpdateDataSourceCommand`. Especially in case one of these decryption operations fail.

Thanks!

**Review by marefr — COMMENTED** [review]
Looks like it should work to be backward compatible. In hindsight maybe would have make sense to put unified secrets behind a feature toggle to limit risk in case of unexpected problems and/or to allow it to be completely turned off, but guess quite a lot of work now to fix? :smile: 

Still need something similar to https://github.com/grafana/grafana/pull/49027 to make sure datasource provisioning goes through datasource service and not directly to SQLStore - very important for v9.0.0

**Comment by guicaulada** [comment]
@marefr We tested provisioning and it still works properly, secrets are migrated as datasources get used.

**Comment by joanlopez** [comment]
> not a requirement.

Isn't it a requirement if we don't want to add implicit breaking changes? 🤔 

I agree it's probably not urgent (for beta2), but definitely think would be very interesting to have this for v9.0.0-stable.

**Comment by guicaulada** [comment]
It wouldn't introduct any breaking changes since provisioning would keep working as usual and the background migration would take care of migrating the provisioned secrets. I can focus on this during this week and get it done, I have a branch half way there but had to switch my focus to the AWS Secrets Manager plugin. I think it would be better to leave it for a different PR.

**Comment by joanlopez** [comment]
> It wouldn't introduct any breaking changes since provisioning would keep working as usual and the background migration would take care of migrating the provisioned secrets. I can focus on this during this week and get it done, I have a branch half way there but had to switch my focus to the AWS Secrets Manager plugin. I think it would be better to leave it for a different PR.

Sorry, I think I got confused with different messages. I was thinking about changes on this specific pull request and when I said "implicit breaking changes" I meant "backwards compatibility", in the sense that once updated, would not be possible to roll back (without changes present on this pull request).

Makes sense?

**Comment by guicaulada** [comment]
I would consider the following:
> Still need something similar to https://github.com/grafana/grafana/pull/49027 to make sure datasource provisioning goes through datasource service and not directly to SQLStore - very important for v9.0.0

An improvement, not a requirement for v9.0.0 since provisioning continues working properly.

The changes on this PR are a requirement if we don't want to introduce any breaking changes but the provisioning change (not in this PR) is not a requirement.

It did got confusing since the provisioning change is not related to this PR.

**Comment by marefr** [comment]
> We tested provisioning and it still works properly, secrets are migrated as datasources get used.

So I would consider this an improvement, not a requirement.

@guicaulada hmm, I cannot see how this works.

Datasource provisioning populates `SecureJsonDataField`:
https://github.com/grafana/grafana/blob/8fa8c9dc8b6922110d154705b9d822bb5319819d/pkg/services/provisioning/datasources/types.go#L242

SQLStore only stores `EncryptedSecureJsonData`:
https://github.com/grafana/grafana/blob/8fa8c9dc8b6922110d154705b9d822bb5319819d/pkg/services/sqlstore/datasource.go#L231

To me seems like there's no encryption happening at all of secrets with datasource provisioning currently, but please let me know if I'm wrong.

**Comment by guicaulada** [comment]
@marefr I think that wasn't changed by unified secrets and should still works as before, we have tested this feature during our bug bash, but I don't mind testing it again tomorrow to be sure! 👍 

The unified secrets PR's are: #45804 #48213 #48557 #48582

I don't think any of them changed how provisioning works.

**Comment by marefr** [comment]
@guicaulada yes, I already kind of suspected that. Very sorry, I'm stupid :smile: I interpreted this line incorrectly and thought that SQLstore was being provided as the datasource store, but missed that `datasourceService` was provided in the argument before :facepalm: 
https://github.com/grafana/grafana/blob/10f90a6615927ebb13cc73725f28ce9023cf9b48/pkg/services/provisioning/provisioning.go#L163 

Please disregard my comments, all good to go :+1:

**Review by joanlopez — APPROVED** [review]

**Pull request merged**
