### PR TITLE
Stackdriver heatmap support. Fixes #13559

### LINKED ISSUE #13559: Stackdriver: support the distribution metric type for heatmaps
Stackdriver can store data in buckets in its [distribution metric type](https://cloud.google.com/logging/docs/logs-based-metrics/distribution-metrics). This would work well with the Grafana Heatmap panel.

ref #13289

### PR DESCRIPTION
**Pull request by mtanda**

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @mtanda,

I have set up some test data in Stackdriver using log-based metrics. But I'm having some problems comparing the Grafana Heatmap to the Stackdriver Heatmap to make sure it everything is correct.

So the linear buckets were easy to test and compare:

image

Stackdriver:

image

Grafana Heatmap with data format set to Time Series buckets:

image

But exponential buckets were a bit harder. How did you configure the Grafana heatmap to match up with Stackdriver?

**Comment by daniellee** [comment]
Explicit buckets are also easy to test.

Stackdriver:

image

Grafana:

image

**Comment by daniellee** [comment]
You can ignore my previous question. I figured out how to test exponential buckets.

Stackdriver:
image

Grafana:
image

**Comment by daniellee** [comment]
There are two tasks to be done when merging this that are related. 

- On the frontend, we should round down the from and to dates to the nearest minute. It is very noticeable in the heatmap panel when comparing to the Stackdriver UI when the timestamps don't match up.

- The docs need to be updated describing how to configure the heatmap panel.

I can do the two tasks above (the first one will be a separate PR and is also related to caching)). 

I need to test a little bit more but it looks good. Thanks @mtanda

**Comment by daniellee** [comment]
Fixes #13559

**Comment by mtanda** [comment]
I'll fix frontend code.

About docs, would you write docs instead of me?
The important point is aligner/reducer setting.
Stackdriver UI's default setting is like following.
image

**Comment by mtanda** [comment]
~~I'll fix frontend code.~~
> I can do the two tasks above (the first one will be a separate PR and is also related to caching)).

Sorry I miss above comment, I'm not sure about caching, please fix frontend code...

**Comment by daniellee** [comment]
@mtanda You can see in the screenshots above that I am getting an extra bucket for the value 0 for explicit and linear buckets. 

image

For example, if I have an explicit histogram with the following bounds:

0,6,12,24,30,36,42,48,54,60

then the data returned from the Stackdriver API looks like this:

```json
{
  "interval": {
    "startTime": "2018-10-09T08:54:00Z",
    "endTime": "2018-10-09T08:55:00Z"
  },
  "value": {
    "distributionValue": {
      "count": "6",
      "mean": 25,
      "sumOfSquaredDeviation": 1749.9999999999995,
      "bucketOptions": {
        "explicitBuckets": {
          "bounds": [
            0,
            6,
            12,
            24,
            30,
            36,
            42,
            48,
            54,
            60
          ]
        }
      },
      "bucketCounts": [
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1"
      ]
    }
  }
}
```

In Grafana, this results in one bucket with bound `0 - 0` and one bucket with bound `0-6`. The Google Stackdriver UI does not show the extra `0 - 0` bucket. Am I doing something wrong or is this an off-by-one bug?

**Comment by mtanda** [comment]
@daniellee This is the definition of explicit bucket.

> Upper bound (0 <= i < N-1): bounds[i] Lower bound (1 <= i < N); bounds[i - 1]
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#explicit

From explicit bucket definition, the first and bucket (i=0,1)'s bound becomes like following.
when (i == 0): Upper bound == bounds[0] == 0, Lower bound == ??
when (i == 1): Upper bound == bounds[1] == 6, Lower bound == 0

I'm not sure whether it is correct or not, the upper bound of first bucket (i=0) becomes 0.
I consider sampled value should be positive number, because latency never becomes negative number.
Would you try how Stackdriver UI display if log-based metrics include negative value like -1?

**Comment by daniellee** [comment]
> I consider sampled value should be positive number, because latency never becomes negative number.

This is probably correct. The Stackdriver UI seems to not show the bucket (?? - 0).

> Would you try how Stackdriver UI display if log-based metrics include negative value like -1?

I'll test this now.

Anyway, think I will merge this now - we can fix/improve this later. Thanks @mtanda!

**Comment by daniellee** [comment]
So did some research on negative buckets. Stackdriver UI does not show them:

image

Maybe we should filter them out - I will ask the Stackdriver team and then create an issue for it.

**Review by daniellee — APPROVED** [review]

**Pull request merged**
