### PR TITLE
add variable $intervalSecond

### PR DESCRIPTION
**Pull request by mekalz**
Add a templated variable `$intervalSecond` for the data source of Elasticsearch.

### Issue:
#3773 

### Usage:

When I want to calculate the QPS from PV
```
_value / $intervalSecond
```

### CODE REVIEW

**Comment by torkelo** [comment]
I think $intervalMs makes more sense and btw, there is already kbn interval_to_ms  and kbn https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.js#L212

**Comment by mekalz** [comment]
I got it, will update the code. And I agree that the $intervalMs is better, and what's more, I think there can be also a $intervalSec (or $intervalS, which is better?), this can avoid the converting from Ms to Sec in data source configuration.

**Comment by torkelo** [comment]
the next step is making this more generic (available as global template variables for all data sources), but I can take that step.

**Comment by torkelo** [comment]
refactored this to be more generic and apply to all data sources, https://github.com/grafana/grafana/issues/7190

**Pull request merged**
