### PR TITLE
Prometheus: Add tooltip to metrics select in visual builder

### PR DESCRIPTION
**Pull request by aocenas**
Adds a `tooltip` attribute to `SelectableValue` which if set will show a tooltip next to the select item when item is focused (hover by mouse or highlighted by keyboard navigation)

https://user-images.githubusercontent.com/1014802/157250554-19b8917c-46e4-404d-9375-376508fdd7b0.mp4

### CODE REVIEW

**Comment by torkelo** [comment]
After testing this, the performance scrolling the select is significantly degraded. If I remove the intersection observer stuff it's a little bit better but still much slower / choppy than when I remove the tooltip entirely. Hmmm.. maybe it wont matter that much for metric select as users will likely search to narrow the list down and not scroll so much but this will impact all Selects, for some scrolling might be more common.

**Comment by torkelo** [comment]
Think I would opt to use the native tooltip (title prop) instead for now.

**Comment by aocenas** [comment]
@torkelo there seems to be something weird going on with the select. Even on main right now if I just keep scrolling and hovering over the options I get this for event listeners allocations:
Screenshot from 2022-03-09 10-49-12

The tooltip just makes it worse (and in mobile emulation it even goes into some allocation loop and freezes the browser) but seems like something is wrong in the select component. Will try to see if I can find the root cause, if not I will just leave it be for now.

**Comment by aocenas** [comment]
Going to abandon this for a while. There seem to be 2 separate issues
- usePopperTooltip that we use is using state for element refs here https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/usePopperTooltip.ts#L61. In some cases when I test with mobile emulation in chrome this creates an infinite update loop in the hook which freezes the browser.
- The Select itself is causing lots of rerenderings on every state change (like hovering over items) which is pretty inefficient and with the addition of the tooltip component can create performance issues for long lists. Could be mitigated a bit with virtual list but it would be best to rewrite the Select itself a bit to allow for component memoization.

**Pull request closed without merging**
