### PR TITLE
Alerting - Fix img rendering and/or uploading timeout preventing to send alerts notifications

### PR DESCRIPTION
**Pull request by hekmon**
The alerting process uses a context with a timeout set to `setting.AlertingNotificationTimeout`. But when img upload is activated, the upload will use the exact same context which can lead to an unpleasant situation:

- `(n *notificationService) SendIfNeeded(context *EvalContext) error` starts
- img upload times out (could be rendering or upload, meaning the context is cancelled)
- then `n.sendNotifications(context, notifierStates)` proceeds and try to send alerts with the same context
- context is already cancelled because of the upload (or rendering) timeout which will prevent sending the alert notifications

The idea here is to limit the time allocated to the rendering/upload section to prevent it to use all the time allocated for sending the alert notifications by creating a sub context with a timeout set at half the duration of the initial duration (`setting.AlertingNotificationTimeout/2`). This way even if the img process fails, there is still time to try to send the alert notifications without the img.

While poking around, I noticed that some of the img uploaders were not using the ctx at all ! So in addition, I fixed:
- s3uploader: the aws sdk does provide methods with context support
- webdavuploader: update `req` to use `ctx`
- azureblobuploader: update `req` to use `ctx` thru `FileUpload()` method

We are still working on the rendering section which could use some context improvements too.

### CODE REVIEW

**Comment by hekmon** [comment]
I think this could be related to: https://github.com/grafana/grafana/issues/8042

**Comment by hekmon** [comment]
The rendering section seems to properly use contexts. Even if the workflow is a bit weird:

- `(e *AlertEngine) processJob(attemptID int, attemptChan chan int, cancelChan chan context.CancelFunc, job *Job)`
  - first part using `AlertingEvaluationTimeout` as ctx timeout
  - before calling `e.resultHandler.handle(evalContext)` at the end, new ctx timeout based on `AlertingNotificationTimeout` (not derivated but overwritten)
  - which seems to lead to...
- `(handler *defaultResultHandler) handle(evalContext *EvalContext)`
  - do some stuff and call at the end `handler.notifier.SendIfNeeded(evalContext)`
  - which finally seems to lead to...
- `func (n *notificationService) SendIfNeeded(ectx *EvalContext) error`
  - get the "NeededNotifiers"
  - if img need to be uploaded, calls the `uploadImage()` with context, which:
    - start the rendering using ctx, but:
      - on the renderers, ctx is derivated (from the current based on `AlertingEvaluationTimeout`) with a child ctx with it's own timeout based this time on `AlertingEvaluationTimeout` + 2s (?)
    - try to upload with ctx on some uploaders (others fixed on this PR)
  - send the notifications (with ctx)

As #17691 points out, having the same value on `AlertingEvaluationTimeout` and `AlertingNotificationTimeout` (even with `AlertingEvaluationTimeout` + 2 == `AlertingNotificationTimeout`) can lead to a buggy situation: a timeout in the rendering will prevent the alert notifications to be sent because the parent ctx will timeout first.

But even by increasing `AlertingNotificationTimeout` to be greater than `AlertingEvaluationTimeout` + 2s (which fix timeout during rendering) there is still a bug if the upload times out: by using the same context on rendering/uploading and sending, the notifications will always be blocked by the context which timed out on the image part.

This is why I think that during the whole process (covered by the `AlertingNotificationTimeout` context): only a sub part of this time should be allocated to the rendering/upload graph part: failing to generate the graph should never prevent the alert notifications to be sent (or try to at least).

As the sending process can be split in two main parts:
- image
  - rendering
  - uploading
- alert sending

I set the sub context for the image part to use at maximum half (`setting.AlertingNotificationTimeout/2`) of the time allowed for the whole process.

**Comment by kylebrandt** [comment]
I'm wondering if the image uploads can be asynchronous (`go` routine(s)). Since the image upload is blocking network IO, it seems to me that should not compete with local processing. 

`uploadImage` seems to really be `renderAndUploadImage` as you pointed out. There also seems to be some other uploaders for specific notifiers such as slack, so that will happen later, but still depends on `ImageOnDiskPath` (rendering) to be complete -- so upload being in different places makes this a bit confusing.

Creating/Rendering/Building the notification to be sent is what requires `ImagePublicURL`, so I think that would be the place to wait, and then put something (maybe alternate link to Grafana dashboard?) alternatively in there if the image upload+image rendering timeout hits at that wait point.

**Comment by hekmon** [comment]
I guess the img upload could be in a goroutine but I am not familiar enough with the grafana code base to implement such change :)

I don't know about all the notifiers but for those we use (slack and pager duty) there is already a link back to graph which generated the alert (title is an hyperlink) so this feature seems already covered.

I agree that `uploadImage` should definitly be renamed as `renderAndUploadImage`: I will update the PR with a commit for this.

One thing for sure: Grafana should always try to sent the alert notifications no matter image rendering/uploading succeeded or not. I am pretty sure our SRE prefer to have the alert without the image than not having the alert at all ;)

There could be several solutions:
- Keep `AlertingEvaluationTimeout` ctx for local processing, switch to a new ctx (`AlertingImgTimeout` ?) only for rendering/uploading if requested then reswitch to a whole new ctx for sending (`AlertingNotificationTimeout`). Issue here is that img process is within the `SendIfNeeded()` method which already is within the `AlertingNotificationTimeout` ctx set by it's caller `(handler *defaultResultHandler) handle(evalContext *EvalContext)` more modifications to the code/architecture would be needed. This would be ideal but would need the introduction to a new parameter and code architecture change: is it really worth it ?

- Switch the rendering to the `AlertingEvaluationTimeout` ctx and share the time allocated for the `AlertingNotificationTimeout` for both img uploading and alert notification sending (not really a big fan of this as it would require non trivial code change and would increase complexity/confusion while reading the code).

- Stick to only 2 ctx but make sure img process can not entirely cancel the alert notification (minimal code change, easier to read, safety against img timeout --> this is why I prefered this solution on the initial PR commit). But using `setting.AlertingNotificationTimeout/2`, even if not bad, might be a bit arbitrary. I just don't see a simpler solution which would not involve a significant code change. Still, with the Grafana default parameter of 30s this means img process will have 15s to render and upload and notifications another 15s to be sent, with or without image, which is not bad. I truly believe this has the best ratio for simplicity/efficiency :)

**Comment by marefr** [comment]
We have two settings for timeouts in alerting:

https://github.com/grafana/grafana/blob/2c5400c61eeb8f228ec54492a7e5a69b29925e92/conf/defaults.ini#L529-L533

**Comment by kylebrandt** [comment]
Hi @hekmon , @marefr and I talked about this and both agree with you that this is better than the current state, and making async increases the scope of the solution to more than we want to deal with right now.

Would it be possible to get some tests added to this? In paricular

 1) A fake blocking image uploader stops the notification from being sent (or at least flagged for retry) (basically the test that fails without this change), timeouts can be much shorter in the test if relatively the same.
 2) With this change, an image upload that blocks still results in a notification
 (2b) and that the notification is not scheduled for retry if only the image upload part failed.

**Comment by hekmon** [comment]
> We have two settings for timeouts in alerting:
> 
> https://github.com/grafana/grafana/blob/2c5400c61eeb8f228ec54492a7e5a69b29925e92/conf/defaults.ini#L529-L533

Indeed but as detailed in the process breakdown:
- `evaluation_timeout_seconds` is used as timeout for the context in `processJob()`
-  at the end of the `processJob()` method, the context is replaced (not derivated/inherited) by a new context with a timeout set to `notification_timeout_seconds` before calling `handle()`
- this new context is used both for `handle()` and `SendIfNeeded()` (which `handle()` calls at the end of its body)
- the img generation & upload is handled by `uploadImage()` (or `renderAndUploadImage()` in this PR) which is called within `SendIfNeeded()`

This means img generation + img upload + alert sending are all processed under the `notification_timeout_seconds` context, preventing the alert to be sent if img generation or img upload consume all the time (timeout) allocated within the `notification_timeout_seconds` context.

My proposal is to isolate img generation + img upload within an inherited context to use at maximum half of the time allocated for `notification_timeout_seconds`, this way with the default 30s value:

- img generation & upload take 5s: there is still 25s for the alert to be sent (a bit would have been consummed within `handle()`)
- img generation or upload timeout: thanks to the already existing uploaders using context and the fix I provide the remaining one in this PR, the upload request is cancelled by the sub context and only 15s are consumed, leaving 15s more (remaining time) for the actual alert sending to proceed (which is the most important part)

**Comment by hekmon** [comment]
> Hi @hekmon , @marefr and I talked about this and both agree with you that this is better than the current state, and making async increases the scope of the solution to more than we want to deal with right now.
> 
> Would it be possible to get some tests added to this? In paricular
> 
> 1. A fake blocking image uploader stops the notification from being sent (or at least flagged for retry) (basically the test that fails without this change), timeouts can be much shorter in the test if relatively the same.
> 2. With this change, an image upload that blocks still results in a notification
>    (2b) and that the notification is not scheduled for retry if only the image upload part failed.

That's great ! I will try to make free some time this week and checkout the tests of the existing notifiers to add this use cases.

**Comment by hekmon** [comment]
It seems I won't be able to deliver the requested tests as to test the `SendIfNeeded()` method we need to:
- create a fake `EvalContext` (done)
- create a fake `NotificationService` (done)
- create a fake renderer service which will use too much time to render (done)
- create a fake uploader (not done)
- having the SQL components working (stuck, seems to be related to the recovery of notifiers)

Creating all the (fake) background bricks needed to properly test this method would require a far more better understanding (or time) of the grafana software architecture that I currently have.

I pushed the early test code in another branch [here](https://github.com/iguanesolutions/grafana/commit/b697ab8127bd7d41c2d1234be31a3d6553abd564) (branch `alertnotifimgctx_test`) just in case.

I see 3 solutions:
- accept this PR as is
- switch the target branch from `master` to a dev branch on the grafana project in order for a project developer to correctly set up the tests
- close this PR

Sorry guys I simply do not have enough time to tackle the discovery and understanding of entire grafana (backend) code base :(

**Comment by kylebrandt** [comment]
Thanks @hekmon for the attempt! I have moved it to devAlertImgTimeout branch and see if I will be able to get some tests in ... may end up in the same boat though :-) In which case I guess we will go forward without tests.

**Comment by hekmon** [comment]
Thanks for keeping it ! I wish u luck for emulating all the needed components for the test ;)

**Pull request merged**
