### PR TITLE
Select: Infer dropdown menu position

### LINKED ISSUE #41557: Query Editor gui issues / query breaking
**What happened**:
Since v8 (or maybe v8.1) , the query editor has been giving very unexpected output / changes.  IE will re-order or duplicate a query when selecting from the drop down menus and other un-expected behaviors.  I have tried my best to rule out browser-side causes (or other causes on my end), however I frequently see this occur both on Chrome and Firefox, as well as on entirely different physical PCs (ie to try to rule out browser / cache / cookie issues).

(in the past week i have purchased a brand new / fresh win11 based laptop, and im seeing the same issues occur on that laptop , as i do on my win10 based desktop pc)

**What you expected to happen**:
Query editor to preform as expected (and as it did pre grafana version 8-8.1)

**How to reproduce it (as minimally and precisely as possible)**:
Using a graphite data source, edit an existing panel (ie not create a new one) with several queries-  then change dropdown options and re-order queries (see screen video).

**Anything else we need to know?**:
Please see video at bottom showing the issue occur.  I can repeat this across any of my varied dashboards.

(in video i also show a prior, *unrelated* issue in regards to not being able to access the bottom elements of drop down lists, but that is not the focus of this bug report-  i have that filed seperately, under: https://github.com/grafana/grafana/issues/41011

thank you- LOVE GRAFANA!

**Environment**:
- Grafana version: v8.2.2
- Data source type & version: Graphite (v0.9.14)
- OS Grafana is installed on: Debian 8
- User OS & Browser: Win10 on Chrome
- Grafana plugins: N/A
- Others: 

doneGrafanaCAP

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

`react-select` should automatically set menu position to below/above the input depending on available space when `menuPlacement=auto`. This however doesn't work when: 

 * options are loaded asynchronously with `AsyncSelect` / `loadOptions`, and 
 * the menu is opened automatically with `isOpen={true}` (it happens in SegmentSelect but can happen with any AsyncSelect with isOpen=true). 

In dashboards scrolling is blocked making some menu items not accessible.

More details: https://github.com/JedWatson/react-select/issues/4936

**Which issue(s) this PR fixes**:

Fixes #41557 (remaining issue with menu not being accessible, other issues fixed in #42136

**Special notes for your reviewer**:

The drawback of this solution is that positioning in the case above always uses `maxHeight` to determine if there's enough space. It means that if the component is closer than 300px from the bottom edge it will always show the menu above (even if for example there's a single item in the menu that theoretically should fit below).

Before:

https://user-images.githubusercontent.com/745532/143882687-c765bdb3-6e06-4375-b360-00d42d26534c.mov

After:

https://user-images.githubusercontent.com/745532/143882758-5e54feea-8718-4ecd-9a5f-2b7dbe731617.mov

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Code looks good to me, but I am lacking quite some context for the `Select` component,  tagging to @ashharrison90 to do double-check :)

**Review by dprokop — COMMENTED** [review]
@ifrost isn't this already solved by setting `menuShouldPortal={true}` on the Select element? Thought we introduced that property for the exactly same reason (and few more;) )

**Comment by ashharrison90** [comment]
mmm think `menuShouldPortal` is already set and doesn't help in this case, because the menu options are retrieved whilst the menu is open. looks like it's an actual bug in `react-select`.

i think it'd be worth updating the comment in https://github.com/grafana/grafana/pull/42446/files#diff-40e717bd6568109346642e4696f3d244b37750409d065af5e2f8ac5b78b7e320R154 to make it clear that if the issue in `react-select` is fixed we can remove all this code. 🤔

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Pull request merged**
