### PR TITLE
Chore: more ts test fixes

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- stricter types in our test files

**Why do we need this feature?**

- better typing across grafana

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by joey-grafana — APPROVED** [review]
Tracing changes look good

**Review by matyax — COMMENTED** [review]
Loki part looks good 👌

**Review by aangelisc — APPROVED** [review]
Azure Monitor and Cloud Monitoring changes look good 👍

**Review by kevinwcyu — APPROVED** [review]
Cloudwatch 👍

**Review by itsmylife — APPROVED** [review]
opentsdb, graphite, influxdb, prometheus looks 👍

**Pull request merged**
