### PR TITLE
allow alert notification to take custom ID via API

### PR DESCRIPTION
**Pull request by xginn8**
Allowing custom alert IDs makes it possible to programmatically create dashboards and corresponding alerts.

### CODE REVIEW

**Comment by bergquist** [comment]
Using ID is not guaranteed to work in a multi org setup. Since the ID for the notifier you want to create might already exist in another org. 

I do understand that this causes some frustration when creating dashboards with alerts. But I think a better solution would be to create an alert notification and then query it to get the ID and then use that when creating dashboard.

**Comment by xginn8** [comment]
If I create a new alert_notification via a POST and there's an ID collision (within the same org), it'll be equivalent to any other collision in an alert_notification created via POST. Since the alert_notification ID is shared across orgs, this collision would cause a problem when trying to insert an alert notification using a supplied ID if another org already had the same ID. Is my understanding correct / what you're referring to? Are there use cases where this would be a problem, that I'm not considering?

**Comment by bergquist** [comment]
Currently I dont see any better automated way of solving it so this PR makes sense.

Could you please add some tests to https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/alert_notification_test.go

**Comment by torkelo** [comment]
should it not be named externalId or customId?

**Comment by torkelo** [comment]
> Allowing custom alert IDs makes it possible to programmatically create dashboards and corresponding alerts.

This should still be possible with if the dashboards are templated and the notifications created first.

**Comment by bergquist** [comment]
Closing this since the Solution torkel mentioned is good enough and avoids

**Pull request closed without merging**
