### PR TITLE
Segment multi select

### PR DESCRIPTION
**Pull request by sunker**
Support for multi select in segments will be necessary in Cloudwatch. 

It does get pretty messy, especially in SegmentSelect, when it supports both isMulti and single select. One thing that would address that is to expose two segment components - Segment and SegmentMulti. What do you think is better?

### CODE REVIEW

**Comment by torkelo** [comment]
This feels like it needs a lot more work. Switching to the select component in multi select mode with options already selected feels a bit wrong. 


 Maybe we should have the select component be single value and instead show the selected values  in separate labels with an x remove action. So the multi select becomes a high level component instead that uses the Segment AddButton and just normal gf-form-labels to show current value. 

So I think one option would be to make this into something like this:

SelectOption1 x| SelectedOption2 x | + (Segment using AddButton)

**Comment by torkelo** [comment]
no need for this anymore?

**Comment by sunker** [comment]
I thought we would need it for cloudwatch, but now we don't so I closed it. But I'm sure it will be useful in other scenarios. I think @srclosson might need something similar for dynatrace?

Regarding the Select component being single value - the downside with that is that then you won't get all features that react-select comes with when in multi mode. See this example: 
Skärmavbild 2019-11-07 kl  16 55 44
In this example the two options that are selected are being displayed, and possible to remove using, at the top in the label. Also they are not being displayed in the list of options in the dropdown. That's a pretty nice feature that would be hard to reproduce if we use single select.

**Comment by torkelo** [comment]
But if that is the case we should just use select in multi mode (but style it better)

**Comment by sunker** [comment]
Nice, I'll give it a shot! Regarding styling, what do you think about making the selected options look a bit like the tags, but without the colors?

**Pull request closed without merging**
