### PR TITLE
Remove last synchronisation field from LDAP debug view

### PR DESCRIPTION
**Pull request by undef1nd**
**What this PR does / why we need it**:
Removes last sync field from LDAP debug view and solves [this Enterprise issue](https://github.com/grafana/grafana-enterprise/issues/314 )

### CODE REVIEW

**Review by xlson — COMMENTED** [review]
Looks great but I think we should remove the prevSync field from the type as well.

**Comment by undef1nd** [comment]
@xlson 
not directly related to this issue, but I think this component is not used anywhere https://github.com/grafana/grafana/blob/master/public/app/features/admin/UserSyncInfo.tsx  Do I get it right?

**Comment by xlson** [comment]
@undef1nd I think so. @alexanderzobnin is this file used?

**Review by xlson — APPROVED** [review]
LGTM!

**Review by Clarity-89 — APPROVED** [review]
Looks good!

**Pull request merged**
