### PR TITLE
Chore/Tech debt: Remove (most) instances of $q angular service use

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Removes instances where the angular $q service is used and replaces them with native Promises.
Still used in template_srv and backend_srv, which I'll try to address in individual refactors of those
services.

### CODE REVIEW

**Comment by dprokop** [comment]
@kaydelaney great initiative!

**Review by ryantxu — APPROVED** [review]
@kaydelaney -- this is great. 

I previously had issues with removing $q from an angular control -- essentially the performance for Promise.all was significantly worse than $q until we added an extra `digest()` call somewhere -- I don not really know the pattern for when and why it was problematic.  The upshot is that I think we should change all this, but keep an eye out for anything that starts behaving badly

**Comment by torkelo** [comment]
This is a bit tricky. Think angular promise has some special logic that integrates with angular digest so that angular's dirty checking is executed after a promise is completed. But looked through the angular  $q code and did not find any details on how this works.

**Review by Estrax — APPROVED** [review]
LGTM

**Review by torkelo — APPROVED** [review]
let's merge this. We will need to keep an eye open on things that are not updating

**Comment by torkelo** [comment]
Free to merge when your ready :)

**Comment by davkal** [comment]
Needs another rebase.

**Pull request merged**
