### PR TITLE
Core: Update components to have standard radii

### LINKED ISSUE #64408: Check and remove deviations from standard border radius in Grafana UI, Command Palette, etc.
## How to make progress on this issue
- assign yourself to the task
- check the cases listed below and replace the border radius if it makes sense 
- please use `GrafanaTheme2` and set the border radius as follows: `theme.shape.radiues.default` or `theme.shape.radiues.default`
- please leave a comment in the list mentioned below in case the border radius needs to be kept as is

Please check the use of border radius in the following files. For more information and details refer to [this list](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=2134382337):
--

- [x] packages/grafana-ui/src/components/Badge/Badge.tsx
- [x] packages/grafana-ui/src/components/BarGauge/BarGauge.tsx (Currently 3px. As this is a visualization, maybe this is an exception?)
- [x] packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx
- [x] packages/grafana-ui/src/components/CallToActionCard/CallToActionCard.tsx
- [x] packages/grafana-ui/src/components/Collapse/Collapse.tsx
- [x] packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx
- [x] packages/grafana-ui/src/components/DateTimePickers/RelativeTimeRangePicker/RelativeTimeRangePicker.tsx
- [x] packages/grafana-ui/src/components/EmptySearchResult/EmptySearchResult.tsx
- [x] packages/grafana-ui/src/components/FileDropzone/FileListItem.tsx (This applies to the progress bar, which is very small. Does it make sense to change?)
- [x] packages/grafana-ui/src/components/Forms/InlineLabel.tsx
- [x] packages/grafana-ui/src/components/Logs/getLogRowStyles.ts
- [ ] packages/grafana-ui/src/components/Logs/LogDetailsRow.tsx (20px border-radius for hoverValueCopy. Need to check this in Grafana, as the functionality is not in Storybook.) Component is also marked as deprecated
- [x] packages/grafana-ui/src/components/Logs/LogRowContext.tsx
- [x] packages/grafana-ui/src/components/PageLayout/PageToolbar.tsx
- [x] packages/grafana-ui/src/components/PanelChrome/HoverWidget.tsx
- [x] packages/grafana-ui/src/components/PanelChrome/PanelStatus.tsx
- [x] packages/grafana-ui/src/components/PanelContainer/PanelContainer.tsx
- [ ] packages/grafana-ui/src/components/Switch/Switch.tsx (Container has correct border radius, the switch is expected to have deviating border radius)
- [x] packages/grafana-ui/src/components/Table/FilterPopup.tsx
- [x] packages/grafana-ui/src/components/Table/styles.ts (I cannot find where resizeHandle is used, but I'll change it to 2px as it is currently 3px)
- [x] packages/grafana-ui/src/components/Tabs/Tab.tsx
- [x] packages/grafana-ui/src/components/Tabs/VerticalTab.tsx
- [x] packages/grafana-ui/src/components/Tags/Tag.tsx (It changes the look quite a lot, but I'll update it)
- [x] packages/grafana-ui/src/components/TagsInput/TagItem.tsx
- [x] packages/grafana-ui/src/components/Tooltip/Tooltip.tsx
- [x] packages/grafana-ui/src/components/VizLegend/SeriesIcon.tsx (The change here is quite significant from 1px, but I'll change it)
- [ ] packages/grafana-ui/src/themes/mixins.ts (cardChrome and listItem has no usage. Consider removing these.)
- [ ] public/app/core/components/Login/LoginLayout.tsx (From theme.shape.borderRadius(4) it causes a significant change)
- [ ] public/app/core/components/PageNew/SectionNavItem.tsx
- [ ] public/app/core/components/QueryOperationRow/QueryOperationAction.tsx
- [ ] public/app/core/components/SplitPaneWrapper/SplitPaneWrapper.tsx
- [ ] public/app/features/commandPalette/CommandPalette.tsx
- [ ] public/app/features/commandPalette/ResultItem.tsx
- [ ] public/app/features/search/components/DashboardSearchModal.tsx
- [ ] public/app/features/search/components/SearchCard.tsx
- [ ] public/app/plugins/panel/news/component/News.tsx

**In case there are files another team is responsible for please let me know.**

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**
Reference the theme variable for border-radius.

**Why do we need this feature?**

Standardization

**Who is this feature for?**

Users :bust_in_silhouette: 

**Which issue(s) does this PR fix?**:

Fixes #64408

**Special notes for your reviewer**:

Please have a look at the login page. I do not think it should use the default border radius.

4xdefault
image
default
image

### CODE REVIEW

**Review by matyax — COMMENTED** [review]
Logs part looks good 👍

**Review by nmarrs — APPROVED** [review]
LGTM

**Review by mckn — APPROVED** [review]
LGTM!

**Review by L-M-K-B — COMMENTED** [review]
Just one thing: 
What about `packages/grafana-ui/src/themes/mixins.ts`? It's missing here but also `contains border-radius: ${theme.shape.borderRadius(2)};`

**Comment by tskarhed** [comment]
> Just one thing: What about `packages/grafana-ui/src/themes/mixins.ts`? It's missing here but also `contains border-radius: ${theme.shape.borderRadius(2)};`

The functions in that file are unused (in core at least), and should probably be removed. I guess I can update it for completeness sake.

**Pull request merged**
