### PR TITLE
Chore: uPlot v1.6.26

### LINKED ISSUE #63840: Time Series Logarithmic View Tick issue when ticks for decades<= 1e-09 needed
image
image
image

When using logarithmic (base 10) y-axis and the axis has to print ticks, which are smaller than 1e-09 every subtick will get a label, which ends in an unreadable mess of tick labels.

I'm expecting a tick-label for every decade.

Another Issue: Min Max must be specified - Auto does not work and results in a range from 1e0 to 1e2

DataSource MySQL ([v9.3.6 (978237e7cb)]
OS: Rocky9
Browser: Chrome Version 110.0.5481.105  (64-Bit)

DataSample: 
| 2023-02-27 16:03:17 | 0.00000000003162278 |
| 2023-02-27 16:03:22 | 0.00000000003162278 |
| 2023-02-27 16:03:27 | 0.00000000003162278 |
| 2023-02-27 16:03:32 | 0.00000000003162278 |
| 2023-02-27 16:03:37 | 0.00000000003162278 |
| 2023-02-27 16:03:42 | 0.00000000003162278 |
| 2023-02-27 16:03:47 | 0.00000000003162278 |
| 2023-02-27 16:03:52 | 0.00000000003162278 |
| 2023-02-27 16:03:58 | 0.00000000003162278 |

image

### LINKED ISSUE #65581: Restore additional log bases for graphing
### Discussed in https://github.com/grafana/grafana/discussions/65580

<div type='discussions-op-text'>

<sup>Originally posted by **virusdave** March 29, 2023</sup>
The [ancient FR](https://github.com/grafana/grafana/issues/452) for logarithmic Y-axis was closed with (what appeared to be) support for [additional log bases](https://github.com/grafana/grafana/commit/36a948965bd1051ea885434dcdf2e0f357d9a3ca) beyond just 2 and 10.

Somehow, this functionality appears to have been lost.  Log base 2 is fine, or rather, _would be_ fine if Y-axis gridlines were intelligently chosen to be readable, by dropping gridline labels that overlap each other.  Alternatively, allow user specification of the log base, then continue placing one gridline per order-of-base.

Example to illustrate the problem:
image

The left Y-axis is useless as-is, since the graphed series cross roughly 25 powers of two (32b/s min vs ~1Gbps max).
Intelligent selection of Y-axis gridline labels might have chosen between 4 and 8 labels (both [32b/s, 1Kib/s, 32Kib/s, 1Mib/s, 32Mib/s, 1Gib/s] and [1b/s, 1Kib/s, 1Mib/s, 1Gib/s] would have probably been reasonable choices).  Had I been able to choose, I would have selected a "base-32 logarithmic" graph for this purpose, although honestly just being intelligent in labelling and sticking with base-2 would probably be better.</div>

### LINKED ISSUE #69610: TimeSeries: 0-valued stacked bars bleed colors at narrow panel widths
### 
# What went wrong?

**What happened**:

See screenshots.

This is correct:
big

This is incorrect:
small

**What did you expect to happen**:

They should be the same.

### 
# How do we reproduce it?

This is a "Time series" panel with:
- style: bars
- stack series: normal
- added overrides to manually choose color for each field

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

[debug-Backend request status codes-2023-06-06 10 04 34.json.txt](https://github.com/grafana/grafana/files/11662088/debug-Backend.request.status.codes-2023-06-06.10.04.34.json.txt)

### Grafana Platform?

Docker

### User's OS?

openSUSE Tumbleweed

### User's Browser?

Firefox 113.0.2

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by leeoniya**
Bunch of internal & api adjustments to unblock tooltip rework in:
https://github.com/grafana/grafana/pull/70872
https://github.com/grafana/grafana/pull/71603

Fixes https://github.com/grafana/support-escalations/issues/6671

Fixes https://github.com/grafana/grafana/issues/69610
Fixes https://github.com/grafana/grafana/issues/65581
Fixes https://github.com/grafana/grafana/issues/63840

<details><summary>log-ticks-collision-uplot-fixes.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 630,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "log": 2,
              "type": "log"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "bytes"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 11,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "2,2e9"
        }
      ],
      "title": "Log 2",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 100,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": 3600000,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          },
          "unit": "reqps"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byRegexp",
              "options": "2.."
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "green",
                  "mode": "fixed"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byRegexp",
              "options": "3.."
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "yellow",
                  "mode": "fixed"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byRegexp",
              "options": "4.."
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "orange",
                  "mode": "fixed"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byRegexp",
              "options": "5.."
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "red",
                  "mode": "fixed"
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 27,
        "w": 3,
        "x": 11,
        "y": 0
      },
      "id": 5,
      "interval": "1m",
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "rawFrameContent": "[\n  {\n    \"schema\": {\n      \"refId\": \"Responses\",\n      \"meta\": {\n        \"executedQueryString\": \"Expr: sum by (res_statusCode) (rate ({hostname=\\\"portal-staging.golem.network\\\", user_unit=\\\"gp-portal-api.service\\\"} |= \\\"request completed\\\" | json [1m]))\\nStep: 1m0s\",\n        \"preferredVisualisationType\": \"graph\",\n        \"stats\": [\n          {\n            \"displayName\": \"Summary: bytes processed per second\",\n            \"unit\": \"Bps\",\n            \"value\": 6839691\n          },\n          {\n            \"displayName\": \"Summary: lines processed per second\",\n            \"value\": 43670\n          },\n          {\n            \"displayName\": \"Summary: total bytes processed\",\n            \"unit\": \"decbytes\",\n            \"value\": 441513\n          },\n          {\n            \"displayName\": \"Summary: total lines processed\",\n            \"value\": 2819\n          },\n          {\n            \"displayName\": \"Summary: exec time\",\n            \"unit\": \"s\",\n            \"value\": 0.064551595\n          },\n          {\n            \"displayName\": \"Ingester: total reached\",\n            \"value\": 112\n          },\n          {\n            \"displayName\": \"Ingester: total chunks matched\",\n            \"value\": 2\n          },\n          {\n            \"displayName\": \"Ingester: total batches\",\n            \"value\": 7\n          },\n          {\n            \"displayName\": \"Ingester: total lines sent\",\n            \"value\": 38\n          },\n          {\n            \"displayName\": \"Ingester: head chunk bytes\",\n            \"unit\": \"decbytes\",\n            \"value\": 0\n          },\n          {\n            \"displayName\": \"Ingester: head chunk lines\",\n            \"value\": 0\n          },\n          {\n            \"displayName\": \"Ingester: decompressed bytes\",\n            \"unit\": \"decbytes\",\n            \"value\": 0\n          },\n          {\n            \"displayName\": \"Ingester: decompressed lines\",\n            \"value\": 0\n          },\n          {\n            \"displayName\": \"Ingester: compressed bytes\",\n            \"unit\": \"decbytes\",\n            \"value\": 0\n          },\n          {\n            \"displayName\": \"Ingester: total duplicates\",\n            \"value\": 0\n          }\n        ],\n        \"type\": \"timeseries-multi\",\n        \"typeVersion\": [\n          0,\n          0\n        ]\n      },\n      \"name\": \"200\",\n      \"fields\": [\n        {\n          \"config\": {\n            \"interval\": 60000\n          },\n          \"name\": \"Time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\"\n          }\n        },\n        {\n          \"config\": {\n            \"displayNameFromDS\": \"200\"\n          },\n          \"labels\": {\n            \"res_statusCode\": \"200\"\n          },\n          \"name\": \"Value\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\"\n          }\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1686017160000,\n          1686017460000,\n          1686017580000,\n          1686017760000,\n          1686018060000,\n          1686018360000,\n          1686018420000,\n          1686018660000,\n          1686018900000,\n          1686018960000,\n          1686019260000,\n          1686019560000,\n          1686019860000,\n          1686020040000,\n          1686020160000,\n          1686020460000,\n          1686020760000,\n          1686021060000,\n          1686021360000,\n          1686021660000,\n          1686021840000,\n          1686021960000,\n          1686022260000,\n          1686022560000,\n          1686022800000,\n          1686022860000,\n          1686023160000,\n          1686023460000,\n          1686023760000,\n          1686024060000,\n          1686024360000,\n          1686024660000,\n          1686024720000,\n          1686024900000,\n          1686024960000,\n          1686025140000,\n          1686025260000,\n          1686025560000,\n          1686025860000,\n          1686026160000,\n          1686026460000,\n          1686026760000,\n          1686027060000,\n          1686027120000,\n          1686027360000,\n          1686027660000,\n          1686027960000,\n          1686028260000,\n          1686028560000,\n          1686028860000,\n          1686029160000,\n          1686029460000,\n          1686029760000,\n          1686030060000,\n          1686030360000,\n          1686030660000,\n          1686030960000,\n          1686031260000,\n          1686031560000,\n          1686031860000,\n          1686032160000,\n          1686032460000,\n          1686032760000,\n          1686033060000,\n          1686033360000,\n          1686033660000,\n          1686033960000,\n          1686034260000,\n          1686034560000,\n          1686034860000,\n          1686035160000,\n          1686035460000,\n          1686035760000,\n          1686035820000,\n          1686036060000,\n          1686036360000,\n          1686036420000,\n          1686036660000,\n          1686036960000,\n          1686037260000,\n          1686037560000,\n          1686037860000,\n          1686037980000,\n          1686038160000,\n          1686038460000\n        ],\n        [\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.03333333333333333,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.05,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.03333333333333333,\n          0.05,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.03333333333333333,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666,\n          0.016666666666666666\n        ]\n      ]\n    }\n  },\n  {\n    \"schema\": {\n      \"refId\": \"Responses\",\n      \"meta\": {\n        \"executedQueryString\": \"Expr: sum by (res_statusCode) (rate ({hostname=\\\"portal-staging.golem.network\\\", user_unit=\\\"gp-portal-api.service\\\"} |= \\\"request completed\\\" | json [1m]))\\nStep: 1m0s\",\n        \"preferredVisualisationType\": \"graph\",\n        \"type\": \"timeseries-multi\",\n        \"typeVersion\": [\n          0,\n          0\n        ]\n      },\n      \"name\": \"404\",\n      \"fields\": [\n        {\n          \"config\": {\n            \"interval\": 60000\n          },\n          \"name\": \"Time\",\n          \"type\": \"time\",\n          \"typeInfo\": {\n            \"frame\": \"time.Time\"\n          }\n        },\n        {\n          \"config\": {\n            \"displayNameFromDS\": \"404\"\n          },\n          \"labels\": {\n            \"res_statusCode\": \"404\"\n          },\n          \"name\": \"Value\",\n          \"type\": \"number\",\n          \"typeInfo\": {\n            \"frame\": \"float64\"\n          }\n        }\n      ]\n    },\n    \"data\": {\n      \"values\": [\n        [\n          1686024300000,\n          1686024600000,\n          1686024720000,\n          1686024900000,\n          1686029160000,\n          1686036420000\n        ],\n        [\n          0.06666666666666667,\n          0.03333333333333333,\n          0.03333333333333333,\n          0.06666666666666667,\n          0.016666666666666666,\n          0.016666666666666666\n        ]\n      ]\n    }\n  }\n]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Bleed",
      "transformations": [],
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "log": 10,
              "type": "log"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "bytes"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 11,
        "x": 0,
        "y": 9
      },
      "id": 3,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "2,2e9"
        }
      ],
      "title": "Log 10",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "log": 10,
              "type": "log"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "sci"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 11,
        "x": 0,
        "y": 18
      },
      "id": 4,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1e-14,1e-2"
        }
      ],
      "title": "Log 10",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2023-06-06T02:03:26.181Z",
    "to": "2023-06-06T08:02:53.069Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "log-ticks-collision-uplot-fixes",
  "uid": "cac9ea66-d7eb-404e-b74a-8fec69ab3909",
  "version": 8,
  "weekStart": ""
}
```
</details>

before:
image

after:
image

Also fixes an issue with the cursor being visible at 0,0 during initial panel load. i've seen this in many screenshots but found it hard to reproduce locally. finally did tho: https://github.com/leeoniya/uPlot/issues/834

image

Also fixes a clipping bug when explicitly-set axis min or max matches the data min or max:

before:
image 

after:
image

### CODE REVIEW

**Comment by leeoniya** [comment]
the `pointer-events` changes are needed likely due to https://github.com/leeoniya/uPlot/commit/bab8c11a10f5c3e884f8f1d863826dd2996d1ed2, which prevents uPlot itself from reacting to clicks / mouse events of stuff portalled into `.u-over`, which we plan to do in our tooltips/context menu refactor.

**Comment by ryantxu** [comment]
Still checking -- most things look good, but histogram tooltips do not seem to work:
http://localhost:3000/d/UTv--wqMk/panel-tests-histogram?orgId=1

**Comment by leeoniya** [comment]
im not sure histogram ever had them? 🤣

**Review by ryantxu — APPROVED** [review]
looks good!   yup... histogram has no tooltips

**Pull request merged**
