### PR TITLE
Optional search panel count

### PR DESCRIPTION
**Pull request by maumercado**
References #13950

### CODE REVIEW

**Comment by torkelo** [comment]
I am not sure we need settings for this. Maybe we can change the defaults to be more reasonable?

**Comment by maumercado** [comment]
Defaults are still 5 I could change them to X?, however changing the defaults without this PR means hardcoding different values on the client side, the difference now is that with this PR those values need not be hardcoded anymore, but can be easily modified without manipulating code directly.

Let me know I can make the appropriate changes.

**Comment by maumercado** [comment]
The other thing I can think of @torkelo is instead of a server setting make it a client setting modifiable through the admin panel?

**Comment by torkelo** [comment]
It's just I don't want options for everything, options clutter the settings files & docs. Maybe just changing the defaults here are good enough for 99% of usecases. 

Like increasing starrred to 20 & recent to 10?

**Comment by torkelo** [comment]
Created new PR which increase the hard coded limit to 30 for starred & recent

**Pull request closed without merging**
