### PR TITLE
Correcting a reference link in documentation

### PR DESCRIPTION
**Pull request by amalkurup89**
**What this PR does / why we need it**: Documentation fix

**Which issue(s) this PR fixes**: Correcting a reference link in documentation

### CODE REVIEW

**Review by oddlittlebird — CHANGES_REQUESTED** [review]
The link needs to be a [relref](https://github.com/grafana/grafana/tree/master/docs#using-relref-for-internal-links).

**Comment by amalkurup89** [comment]
> The link needs to be a [relref](https://github.com/grafana/grafana/tree/master/docs#using-relref-for-internal-links).

Changed to relative path, as asked

**Review by oddlittlebird — APPROVED** [review]
LGTM, thanks for contributing! Please merge master into this branch, hopefully that will fix the failing tests.

**Comment by amalkurup89** [comment]
> LGTM, thanks for contributing! Please merge master into this branch, hopefully that will fix the failing tests.

@oddlittlebird I have merged master into my forked branch, as asked

**Comment by amalkurup89** [comment]
@oddlittlebird Test failures are resolved now. Can you please merge

**Comment by oddlittlebird** [comment]
Thanks again for contributing to the docs!

**Pull request merged**
