### PR TITLE
Chore: Update and replace redundant wording

### PR DESCRIPTION
**Pull request by fridgepoet**
**What this PR does / why we need it**:
The first two paragraphs in the config editor were the same. I've replaced it with some wording from the [documentation](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/). A link to another required API which needs to be enabled (listed in the documentation) was also added.

**Special notes for your reviewer**:
The information in this tooltip panel is almost identical to the documentation. I wonder if we shouldn't just simply it greatly and keep the link to the [documentation](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/). What do you all think?

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
LGTM!

**Comment by vickyyyyyyy** [comment]
LGTM - might be worth running this past UX first too?

**Comment by fridgepoet** [comment]
Before:
Screen Shot 2021-12-15 at 15 51 33

This commit right now:
Screen Shot 2021-12-15 at 16 51 28

But I'm wondering if this could be OK (or even less, just that last line which links to the documentation):
Screen Shot 2021-12-15 at 17 09 42

**Comment by fridgepoet** [comment]
Thanks, Jess, for all the helpful feedback.
Here's a summary:
- Move the tooltip under the blue button
- Reduce the text of the tooltip to : `Don’t know how to get a service account key file? Read more in the documentation.`

Todo for me: I need to find out if the Grafana on GCE virtual machine users would land on this page.

**Review by andresmgot — APPROVED** [review]
:+1:

**Pull request merged**
