### PR TITLE
NewsPanel: Prevent titles being split onto multiple lines

### PR DESCRIPTION
**Pull request by jsws**
**What this PR does / why we need it**:

- When an RSS feed item has a small title and a small description (or the panel is made smaller) the title is unnecessarily split onto multiple lines because its `max-width` is limited. 
- Remove the `max-width` so the titles width isn't limited and it can fill the whole panel.

| Before | After |
|-------|-------|
| image | image |
|image |  image |

**Special notes for your reviewer**:
- [This RSS feed](https://gist.githubusercontent.com/jsws/add751189ff96c8115707a33c0d267dd/raw/34ab83287dd31f402cf3d9e49b0ac0441b891a04/rss.xml) can be used as an example.

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
hi @jsws 👋 

thanks so much for raising this!
looks like the `max-width` is set there for a reason, i _think_ to provide some differentiation from the main body of text.

however you've definitely highlighted some areas where this looks poor. i wonder if we can add `flex: 1;` to the `body` class on line 136 instead of removing the `max-width` on the title. that way the text will stretch to fit the panel, but still gives the differentiation between title and body.

what do you think? 🤔

**Review by torkelo — APPROVED** [review]
I do not see a reason for this max-width, seems to have been added in the initial version but I see only improved layout when I test removing it, in both layouts

**Comment by jsws** [comment]
I agree with @torkelo, it looks like it's been there since the NewsPanel was first added, perhaps to avoid the title running into the date, see https://github.com/grafana/grafana/pull/21128#issuecomment-566748225. But it doesn't seem to provide any purpose now

**Review by ashharrison90 — APPROVED** [review]
sounds good to me then 👍  thanks for the clarification!

**Pull request merged**
