### PR TITLE
Chore: Remove LocalStorageValueProvider from app/core/components

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

`LocalStorageValueProvider` was moved in `@grafana/o11y-ds-frontend` package with this PR https://github.com/grafana/grafana/pull/81284

In this PR I am cleaning up the duplicate code.

### CODE REVIEW

**Review by ivanahuckova — COMMENTED** [review]
I believe we don't want to use `LocalStorageValueProvider` from `@grafana/o11y-ds-frontend` packe in Grafana core. The  `@grafana/o11y-ds-frontend` package has  `LocalStorageValueProvider` because of decoupling of data sources, but Grafana core should still have its own `LocalStorageValueProvider`  as it is used in couple of core components.

**Comment by itsmylife** [comment]
> I believe we don't want to use `LocalStorageValueProvider` from `@grafana/o11y-ds-frontend` packe in Grafana core. The `@grafana/o11y-ds-frontend` package has `LocalStorageValueProvider` because of decoupling of data sources, but Grafana core should still have its own `LocalStorageValueProvider` as it is used in couple of core components.

Thanks for the input @ivanahuckova. Can't core components use it from `@grafana/o11y-ds-frontend`?

**Comment by ivanahuckova** [comment]
> Thanks for the input @ivanahuckova. Can't core components use it from @grafana/o11y-ds-frontend?

Personally I don't think it makes sense for Grafana to import wrapper around local storage from o11y data sources packages and create a new dependency on this package.

**Comment by itsmylife** [comment]
> Personally I don't think it makes sense for Grafana to import wrapper around local storage from o11y data sources packages and create a new dependency on this package.

I see your point. But I also feel bad about having duplicated code in the code base. And it is only duplicated because of Loki and Prometheus. So, I'd propose to move this to `@grafana/data` or `@grafana/runtime` packages. They are used in `core` so it doesn't create a new dependency. It might even be a bit more convenient. How does it sound?

**Comment by ivanahuckova** [comment]
> So, I'd propose to move this to @grafana/data or @grafana/runtime packages. They are used in core so it doesn't create a new dependency.

That makes sense.

**Comment by itsmylife** [comment]
I'll create a separate PR to move LocalStorageValueProvider into `@grafana/data`. This PR is already too complicated for that purpose.

**Pull request closed without merging**
