### PR TITLE
Alerting: Fix for data source filter on cloud rules.

### PR DESCRIPTION
**Pull request by soniaAguilarPeiron**
**What is this feature?**

This PR fix data source filter not working for cloud rules.
The bug was introduced by this [PR](https://github.com/grafana/grafana/pull/78910)

**Who is this feature for?**

All users.

**Special notes for your reviewer:**

After the fix: 

https://github.com/grafana/grafana/assets/33540275/c43d9c3f-d0ec-4428-9441-cf88f848e4b4

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
I’m not working on the front end, but could we add a regression test to ensure we don't break this again in the future?

**Comment by soniaAguilarPeiron** [comment]
> I’m not working on the front end, but could we add a regression test to ensure we don't break this again in the future?

💯

**Review by VikaCep — APPROVED** [review]
LGTM! I agree it would be great to add a test for it :)

**Comment by soniaAguilarPeiron** [comment]
test added @JohnnyQQQQ @VikaCep ✅

**Pull request merged**
