### PR TITLE
VisualizationSelection: Real previews of suitable visualisation and options based on current data 

### PR DESCRIPTION
**Pull request by torkelo**
Epic #40804

* [x] Real visualization previews that work at small scale. This works by first rendering them at large scale (~432x300) and then scaling it down to 144x100 
* [x] VisualizationSuggestionsBuilder abstraction that caches some data attributes so they can be shared
* [x] VisualizationSuggestionsAppender makes typing easier for each suggestion supplier 
* [x] Preview gets tweaked options to improve preview (increased line width, limit on values in panels that use VizRepeater etc).  
* [x] New updated action that can apply plugin change & options & fieldConfig in one action. 
* [x] Some basic inspection of data that adapts settings and what visualizations to show, these can only get refined over time. This feature will never be done.  
* [x] Bar chart suggestions 50%
* [x] Time series suggestions 20%
* [x] Pie chart suggestions
* [x] Bar gauge
* [x] Gauge
* [x] Stat 50%
* [x] Timeline
* [x] Unit tests
* [x] e2e tests

Long term:
* Currently these suggestions live in their own "tab" inside visualization select pane, think as this feature matures long term it should be the default visualization select view.  And long term I think this requires a bigger panel edit redesign but trying to keep this feature/PR small, so we can iterate on the basics before making a big panel edit re-design based on this capability. 

VIdeo demo (Still early in this features journey) 
https://user-images.githubusercontent.com/10999/137516407-6278fe83-f9e7-41f5-9e2c-b682f13e77c8.mp4

Data with a string & number field 
Screenshot from 2021-10-15 17-06-57

Time series
Screenshot from 2021-10-15 17-39-47

### CODE REVIEW

**Review by dprokop — COMMENTED** [review]
@torkelo I think this is awesome. I Like the general arch, left few comments to consider.

Major concern of mine is whether or not we want the previews of the suggestions in the end. I know I was like "hey, this would be cool" when we talked last week, but now when I see it I'm slightly more skeptical. I think we may be opening quite a dangerous territory that may affect performance of the panel edit unpredictably. I'm not afraid that much of built-in visualizations rather than the community ones. 

Maybe an alternative would be to show the top 3 suggestions (how to score which ones are the top ones...) and the following suggestions would be just shown as a regular list items as in the viz picker?

**Comment by torkelo** [comment]
@dprokop Major concern of mine is whether or not we want the previews of the suggestions in the end

I we definitely do, I mean that is the whole point to give the user a visual indication of how the data can be visualized. We can narrow it down to core panels and do externals async, and have good error boundaries. Not worried about performance, rendering these are quick. And we do not always show the suggestions, only on demand. I think some expensive panels like geomap could maybe show pre-rendered image instead of real viz?

**Review by hugohaggmark — COMMENTED** [review]
Amazing progress as usual 🎉  I would really like to have a Frontend Weekly session about this and the panel editor redux change soon. 

I think it's vital to spread this knowledge at least for @grafana/user-essentials

**Comment by torkelo** [comment]
@dprokop @hugohaggmark pushed some updates that adds unit tests, decided to place unit tests for suggestions at the top level (the function that get's all suggestions), that way all the data scenarios can be shared and we can in one place make sure the suggestions are in the right order and have correct options. Alternative would be to have each suggestion supplier have it's own tests but we will have like 15 of these suppliers and the scenarios will mainly be the same between them (the data scenarios). So by testing them all together I can re-use the scenarios and also verify order

https://github.com/grafana/grafana/pull/40527/files#diff-0cfdfc86edcb3355875f9aa19159c3af010d3e9cae2a10fecac29fa977a62936

**Review by ryantxu — APPROVED** [review]
This is great, and I think we should merge soon.  If there is much more TODO before merging, perhaps we should pull out the changes to 10ish files that are more general cleanup (partials + expanded types) just so this PR is easier to read and digest

**Review by eleijonmarck — COMMENTED** [review]
@torkelo has this been tested when we have alot of data?, maybe not in this particular place but in general
I am just wondering if we have substanstial performace decrease or lag due to evaluating massive amounts of labels/data/fields.

**If and only if** there is a performance issue; maybe should we take a subset of the data?

**Pull request merged**
