### PR TITLE
added AWS/States to the cloudwatch metrics

### PR DESCRIPTION
**Pull request by ghost**
#10386

### CODE REVIEW

**Comment by vikaskoppineedi** [comment]
I don't know why the tests are failing. can anyone please help me here.

**Comment by marefr** [comment]
First of all you've created the commits using different email addresses where one not seems to be connected to your github account. This is why it says that 1 of 2 commiters have signed the CLA. I think you have to create a new pull request using your correct email address for your github account in your commits. Another option would be if you rewrite your commits using git command line and push again.

Second, the tests fails because you've formatted the go code incorrectly:
```
running go fmt
pkg/tsdb/cloudwatch/metric_find_query.go
Executing 'test -z pkg/tsdb/cloudwatch/metric_find_query.go'
'test -z pkg/tsdb/cloudwatch/metric_find_query.go' returned 1.
```

**Comment by vikaskoppineedi** [comment]
Hi marefr,

I have formatted the code, the CircleCli tests passed and I have signed the CLA also. Can you tell me what is the next step?

**Comment by marefr** [comment]
Hey @vikaskoppineedi, seems like you have to create a new pull request to sort out the problems with the CLA.

**Comment by vikaskoppineedi** [comment]
What am i missing?

**Comment by marefr** [comment]
@vikaskoppineedi the problems lies in your first [commit](https://github.com/grafana/grafana/pull/10607/commits/7326e4a2a200e98e0d6b0fea66a3e0b33c3155ed) where you've used the email address viXXs.kXXXXXeedi.cXXXXltXnt@nXXXXXX.com when commiting. This have resulted in that the Contributor License Agreement cannot be identified as signed. 

In order for us to be able to merge this you need to:
* either 
  * create a new branch based on Grafana master and copy all your changes and commit using your correct github email address (probably easiest)
  * create a new branch in your forked repository from your forked repo (vikaskoppineedi:10386_AWS/States_Cloudwatch) and rewrite all your commit history using git and your correct github email address
* create a new pull request

Closing this pull request so that you can create a new one. Sorry for the inconvenience, but we cannot do anything about this without you creating a new pull request.

**Pull request closed without merging**
