### PR TITLE
Prometheus: make $__range more precise

### LINKED ISSUE #21689: $__range is excessively rounded (Prometheus)
**What happened**:

A Prometheus instant query using `[$__range]` on a time range of about 33 hours reported only over 24 hours. The query inspector shows that it was substituting `1d`.

**What you expected to happen**:

`$__range` should expand to the time range selected, to the nearest second.

**How to reproduce it (as minimally and precisely as possible)**:

In a Grafana connected to a Prometheus instance, create a singlestat with a range query using `$__range` e.g. `sum(increase(up[$__range]))`. Set the time range to cover a bit more than a day e.g. 33 hours. Look at the query in the query inspector. It will show a `1d` range.

**Anything else we need to know?**:

This was previously reported at https://community.grafana.com/t/solved-this-week-timerange-strange-behavior-range-with-slow-counter/12782 and in #12882, and was "fixed" by providing a new `$__range_s` which can be used as `${__range_s}s`. While it's nice to have the workaround, `$__range` is still broken (in the worst case, covering only *half* the selected time range).

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Prometheus 2.12
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 18.04, Firefox 72.0.1
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by bmerry**
**What this PR does / why we need it**:

It is now always equivalent to `${__range_s}s`, rather than rounding
down to an integer multiple of the biggest possible unit. For example,
a range of 47 hours is now represented as `169200s` rather than `1d`.

**Which issue(s) this PR fixes**:

Closes #21689.

**Special notes for your reviewer**:

It ideally needs a regression test, but I'm not a Javascript or Go developer and don't have the time to learn how to use a new unit test framework. It unfortunately looked like more than just adding a few extra lines because the time range in the current test seems to be shared across a whole bunch of tests. I'm hoping someone else can help out with that part.

### CODE REVIEW

**Comment by torkelo** [comment]
We already have $__range_s for a more precise range interval variable, so not sure why we need this.

**Comment by bmerry** [comment]
> We already have $__range_s for a more precise range interval variable, so not sure why we need this.

It's not immediately clear to users that `$__range` is horrifically inaccurate and that they should always use `${__range_s}s` instead. [This documentation](https://grafana.com/docs/grafana/latest/reference/templating/#global-built-in-variables) gives the impression that they're equivalent. I'd assumed that `__range_s` and `__range_ms` were there for doing computations with e.g. dividing a sum by the time interval to get an average.

But instead of updating the documentation to tell users "don't use this thing we gave you, it's broken, use this less convenient-to-type thing instead which will give you the right answer", why not just fix $__range? I can't imagine anyone is actually depending on its current behaviour.

**Comment by torkelo** [comment]
I think your right, not sure what the intended use case for $___range was and how it's being used today. 

will just doublecheck with the Prometheus crew :)

**Comment by aocenas** [comment]
Looking into this and this definitely looks strange. Seems like the `__range` itself was added [here](https://github.com/grafana/grafana/commit/6b6a23ff6a24c62955b48c9794c0b99023ceb608). @tskarhed do you remember if there was reason for `__range` to be from the inprecise `secondsToHms` transform? It seems like you thought it would give you `1h10m25s` string (that's what I thought at first) but in that case I would not expect there to be `__range_s` anyway.

**Comment by tskarhed** [comment]
@torkelo The use case was described here https://github.com/grafana/grafana/issues/7664#issuecomment-367257838, but I'm not sure if it is still relevant.
@aocenas I can't remember if there was a reason, do you want me to look deeper into this?

**Comment by sakjur** [comment]
@tskarhed That doesn't explain why `$__range` is imprecise, just why it's needed. It sounds to me as if the rounding down for large values is an oversight rather than intended behavior here?

#21997 was opened recently with a proposal to change the docs to describe how `$__range` works, but imo it would make more sense to merge this PR instead (maybe add a note to the documentation recommending `${__range_s}s` until the next release as well unless we cherry-pick this into 6.6.2).

**Comment by tskarhed** [comment]
It was probably an oversight that it is rounded, but I need to do some digging here. I'll check it out on Wednesday, unless someone has another opinion!

**Comment by aocenas** [comment]
@sakjur @tskarhed so I feel the issue may have been that we use this calculation to compute resolution of a graph. Ie say what is the minimal interval on the graph for example so that bar in bar graph has a reasonable width. This is rounded to something humanly reasonable so like the closest time unit.

I thought this may have some reasoning like that but this rounds the whole range not some smaller part of it so I assume we can merge this.

@sakjur this should reverted then right?

**Comment by sakjur** [comment]
@aocenas #22064 was never merged

**Comment by aocenas** [comment]
@sakjur uh 🤦‍♂yeah sorry.

Ok going to merge this one.

**Review by aocenas — APPROVED** [review]

**Comment by torkelo** [comment]
added add to changelog label and 6.7 milestone so this will show up in changelog

**Pull request merged**
