### PR TITLE
Jaeger: Add service dependency graph support

### PR DESCRIPTION
**Pull request by mszabo-wikia**
**What is this feature?**

Add support for visualizing Jaeger's service dependency graph via the
Jaeger data source, as discussed in https://github.com/grafana/grafana/discussions/52035 and https://github.com/grafana/grafana/issues/50254.

**Why do we need this feature?**

This allows service dependency data to be displayed alongside related information within a Grafana dashboard.

**Who is this feature for?**

Users of Grafana that leverage its Jaeger integration for visualizing trace data.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by mszabo-wikia** [comment]
Some observations:

* The panel looks reasonable enough, if a bit bland - maybe a different color scheme could be used:
Screenshot 2023-07-24 at 14 14 55

* Call count display is not great as there is not much context:

Screenshot 2023-07-24 at 14 15 01

* `preferredVisualisationType` does not seem to do what I expected it to do because it does not cause the UI to suggest that the user switch to `nodeGraph` when creating a panel using the Jaeger datasource with the Dependency Graph query type and a different visualization type.

**Review by lwandz13 — APPROVED** [review]

**Comment by lwandz13** [comment]
Does this need to be backported?

**Comment by mszabo-wikia** [comment]
For me personally it's not urgent, so I'll leave the backporting decision to you and other stakeholders :)

**Comment by mszabo-wikia** [comment]
Not stale, waiting for review.

**Comment by mszabo-wikia** [comment]
Not stale, waiting for review.

**Comment by mszabo-wikia** [comment]
Not stale, waiting for review.

**Comment by aocenas** [comment]
@mszabo-wikia thanks for the PR and sorry this took soooo long for us to review.

**Comment by mszabo-wikia** [comment]
Thanks for the fixups and landing this!

**Pull request merged**
