### PR TITLE
Squash conf file

### PR DESCRIPTION
**Pull request by emiquelito**
**What this PR does / why we need it**:

This is a patch to integrate Squash.io with Grafana. I believe this is going to be handy to the project so any project maintainers and developers can quickly check the branch changes deployed on its own isolated VM. 

Example of Grafana working with Squash: https://squash-integration-sz31y.squash.io/

admin/12qwaszx

Squash is free for Open Source, maintainers just need to [signup ](https://squash.io/signup/) and reach out to the support through the chat window and we will enable a forever free Open Source account. Once this is done, Squash will post a comment on each Pull Request like this:

squash-pr-comment

When you click on the Squash link in a new PR it will deploy the branch of code into a brand new VM, **this process takes about 2 minutes**.

### CODE REVIEW

**Comment by ryantxu** [comment]
IIUC, this takes every PR and deploys the results to VM where you can see the results.  Is that correct?

That is potentially interesting, but any real value would come from having testable/viewable dashboards to work with.  A fresh grafana install rarely shows much interesting

**Comment by bergquist** [comment]
Could be interesting if we could add provisioned datasources + dashboards. I guess we could host some demo datasources at play.grafana.org eventually.

**Comment by bergquist** [comment]
Not sure how it could be deployed within 2mins? What image does it work of? `grafana/grafana:latest` doesnt contain the latest changes for Grafana. Building the dockerfile in Grafanas root take way longer.

**Comment by emiquelito** [comment]
@bergquist thanks for this, regarding:

> Not sure how it could be deployed within 2mins? What image does it work of? grafana/grafana:latest doesnt contain the latest changes for Grafana. Building the dockerfile in Grafanas root take way longer.

The image is actually just ```grafana/grafana```, it uses the same build process as defined here https://hub.docker.com/r/grafana/grafana/  Let me know if I need to adjust the image in this patch.

The deployment actually takes about one minute, this is because Squash cashes the build process (docker build in this case). [See details](https://squash.io/docs/customizing/docker-img-cache.html). You can always turn off the cache if you like, and the cache automatically refreshes when there are changes in the Docker image itself. 

See screenshot below and you can try on this deployment (I've changed its auto-shutdown policy to automatically shut down when inactive for one hour):

https://squash-conf-file-bwsjl.squash.io/

grafana-build

**Comment by emiquelito** [comment]
@ryantxu thanks for your feedback, see comments below:

> IIUC, this takes every PR and deploys the results to VM where you can see the results. Is that correct?

Yes correct. An isolated and disposable VM for each branch of code.

> That is potentially interesting, but any real value would come from having testable/viewable dashboards to work with. A fresh grafana install rarely shows much interesting

Yes this is a common use case. Squash has an [assets storage](https://squash.io/docs/customizing/assets.html) to address this where you can upload files such as dev db dumps, json files, images/etc to feed the deployments. Many projects just update their build process to load a dump file during the build.

The assets storage works like this:

* you can upload files from the Squash UI or dynamically [from an API](https://squash.io/docs/api/assets.html#api-assets)
* the moment files are uploaded they become **immediately** available to any new deployments.
* Squash creates an ```/assets/``` mount point on each host machine. You can then either [copy any files](https://squash.io/docs/customizing/assets.html#using-the-copy-files-feature-in-the-yaml-file) in this folder to the correct location of your app, or [mount that folder as a docker volume](https://squash.io/docs/customizing/assets.html#docker-volumes).

**Comment by emiquelito** [comment]
Hi @ryantxu and @bergquist just checking to see if you have any thoughts on this patch. Please let me know, thanks.

**Comment by bergquist** [comment]
Thanks for taking the time to write this up.

It doesn't seem like that many are interested in this right now so I'm closing this for now. We might look into this later on again.

**Pull request closed without merging**
