### PR TITLE
Chore: Expose TimeSrv from grafana/runtime package

### PR DESCRIPTION
**Pull request by alexanderzobnin**
**What this PR does / why we need it**:
This PR makes it possible to use `TimeSrv` from `@grafna/runtime` package. This change required for extracting Elasticsearch data source (and potentially for other core data sources) into standalone plugin.

**Special notes for your reviewer**:
The only function used by elasticsearch data source is a `timeRange()`. `timeRangeForUrl()` required for initializing `locationUtil` in `GrafanaCtrl`. We can export more methods if we need it, but I only found these two so far.

### CODE REVIEW

**Comment by torkelo** [comment]
For evaluating index patterns it looks like https://github.com/grafana/es-open-distro-datasource/blob/483c6023d209aa91d942bdcb4d59ef1a4f97c35e/src/datasource.ts#L141

**Comment by alexanderzobnin** [comment]
@ryantxu unfortunately, there's no easy way to do it. Data source needs time range to calculate proper index name and this may happen not only inside `query()` method, but in places where time range in not passed to the plugin. So probably it's possible, but we need to investigate it. We don't have much time for that, so this looks like a fastest solution.

**Comment by torkelo** [comment]
@alexanderzobnin I think technically it can, all the methods are all used from  metricFindQuery(query: string) , which does take an options argument as the second option which does have a time range property. (But only for variables that have refresh on time range) .

https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/datasource.ts#L229

https://github.com/grafana/grafana/blob/d0f52d5334d1e3623c7360d0291d29deb5d3f6eb/public/app/features/variables/utils.ts#L127

So the question is what to default to when we do not have a range here (like for testDatasource)

**Comment by alexanderzobnin** [comment]
I guess default is `now-6h`, but I'll check it out. Probably we can get rid of TimeSrv completely in plugin.

**Comment by ryantxu** [comment]
As a quick work-around that does not commit to having timeSrv in the future... what about importing it directly with SystemJS or the angular injector?  like:  https://github.com/ryantxu/image-viewer-panel/blob/master/src/ImageViewer.tsx#L41

**Comment by alexanderzobnin** [comment]
Hm, that might be an option for the transition period. So I'll let this PR open until I find a solution for the plugin. Then we can discuss, do we need this or not.

**Comment by alexanderzobnin** [comment]
@ryantxu unfortunately, that hack doesn't work, I guess, it works in your case, because of 
https://github.com/grafana/grafana/blob/d0f52d5334d1e3623c7360d0291d29deb5d3f6eb/public/app/features/plugins/plugin_loader.ts#L145

But timeSrv is not exposed.

**Comment by alexanderzobnin** [comment]
Looks like it's possible to remove `timeSrv` completely: https://github.com/grafana/es-open-distro-datasource/commit/06901d3075e3e2d84178d7211ce175de68666e9b

**Comment by torkelo** [comment]
@alexanderzobnin can you do those changes to the core plugin and then copy them over? Important to not have the core & external plugins diverge

**Comment by alexanderzobnin** [comment]
@torkelo ok, sure, makes sense.

**Comment by mckn** [comment]
I looks like this PR isn't needed any more, correct? Great that you managed to solve it by using the `timeRange` being passed to `metricFindQuery`. 👍

**Review by mckn — COMMENTED** [review]
I looks like this PR isn't needed any more, correct? Great that you managed to solve it by using the `timeRange` being passed to `metricFindQuery`. 👍

**Comment by alexanderzobnin** [comment]
Yes, we've found a better way, so closing this one.

**Pull request closed without merging**
