### PR TITLE
LibraryPanels: Fixes error when importing plugin dashboard

### LINKED ISSUE #34490: LibraryPanels: Import fails for Datasource Dashboards
1. Navigate to http://localhost:3000/datasources
2. Open gdev-prometheus
3. Click on Dashboards tab
image
4. Try importing any of the listed dashboards
5. Fails [Not OK]
image
6. Navigate to imported dashboard
7. Dashboard opens [OK]

This is caused by https://github.com/grafana/grafana/blob/23939eab107443e0dc985195309a7fc732590cce/pkg/api/plugins.go#L229 because when I implemented this I assumed we always had a valid dashboard json passed in the command. Seems like in this case only a path is provided so we need to refactor this.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
I've tried to figure out the best approach to solve the import for plugin dashboards and this PR tries to solve this. Feels like a hackier approach than #34557.
Approach that doesn't involve changing the interface for plugin manager. Major drawback is that we need to make an unnecessary call to DB.

**Which issue(s) this PR fixes**:
Fixes #34490

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
Is this a draft at this stage or not?

**Comment by hugohaggmark** [comment]
> Is this a draft at this stage or not?
Changed to In Review

**Review by torkelo — APPROVED** [review]
Tricky, but cannot come up with a better solution that would not involve changing the http api or plugin manger interface

**Comment by hugohaggmark** [comment]
Closing this in favor of https://github.com/grafana/grafana/pull/34557

**Pull request closed without merging**
