### PR TITLE
BarChart: fix hovered series highlight in tooltip

### PR DESCRIPTION
**Pull request by leeoniya**
- reduces responsibilities of PlotTooltipInterpolator (moves quadtree probing into `cursor.dataIdx`, similar to `scatter.ts`).
- relies on uPlot's hover points for bar hover overlays.

one possible endgame for this is something closer to the State-timeline variant, with the core setup only exposing `onHover` and `onLeave` events, and the PlotTooltipInterpolator setup being done one level up. this does have the issue of needing an additional `setCursor` hook for hover-change tracking, so might need more refinement in both places.

https://github.com/grafana/grafana/blob/c1a0c2664c05f5628957c0d825b55ede025aedfb/public/app/plugins/panel/state-timeline/utils.ts#L114-L163

still to fix: reduce call tooltip updates by testing previous hovered vs current hovered.

also fixes this odd regression in Barchart tooltip:

https://user-images.githubusercontent.com/43234/156479149-d712ad71-0a07-400f-8b5f-6689d1f13f63.mp4

### CODE REVIEW

**Comment by nmarrs** [comment]
Is this WIP PR still needed? I believe that it may already be incorporated in [current revamp of uplot](https://github.com/grafana/grafana/pull/45845)

@leeoniya thoughts?

**Comment by dprokop** [comment]
@nmarrs think we can close this one, we will soon try to apply the new uPlot wrapper to Bar chart panel.

**Comment by leeoniya** [comment]
let's actually land this. what this fixes is orthogonal.

**Review by ryantxu — APPROVED** [review]
no more funky vertical highlights :tada: 
Peek 2022-03-03 08-37

**Pull request merged**
