### PR TITLE
Branding: Use AppTitle as document title

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR follows the quick discussion in #25235.
It tries to make the login page title inherit from the `AppTitle` variable, as in every other page.

Thank you for your help & support 👍

### CODE REVIEW

**Comment by benrubson** [comment]
It's not stale @stale 😉
Waiting for @hugohaggmark / @peterholmberg to review this, certainly to correct it as I'm not really pleased with react I must say...
Should not be a difficult fix though.
Many thanks again 👍

**Review by hugohaggmark — APPROVED** [review]
Thank you for contributing @benrubson this works as expected

**Comment by hugohaggmark** [comment]
Looks like you need to merge in master to get the CI to pass @benrubson

**Review by dprokop — APPROVED** [review]

**Comment by benrubson** [comment]
Thank you very much for your feedbacks and reviews @hugohaggmark & @dprokop 👍

> Looks like you need to merge in master to get the CI to pass @benrubson

Note that I'm not allowed to merge this PR myself :)

**Comment by hugohaggmark** [comment]
> Thank you very much for your feedbacks and reviews @hugohaggmark & @dprokop 👍
> 
> > Looks like you need to merge in master to get the CI to pass @benrubson
> 
> Note that I'm not allowed to merge this PR myself :)

@benrubson I know you can't merge to master sorry for being unclear, I meant that you need to update your branch/fork with latest master because it seems like CI is breaking.

**Comment by benrubson** [comment]
OK, I misunderstood :)
So, I updated this PR with the last master branch (https://github.com/grafana/grafana/commit/54284ed9f728152f8c35e2d46d3b9d7381197714, which passes tests).
However sounds like CI still fails here.
Feel free if I've missed something...

**Comment by dprokop** [comment]
@benrubson I've just re-ren the check, the problem is probably with flaky e2e test

**Comment by benrubson** [comment]
U're right @dprokop it did the trick, many thanks 👍

**Comment by hugohaggmark** [comment]
Thanks again @benrubson for contributing!

**Comment by benrubson** [comment]
@dprokop @hugohaggmark Do we need to merge this into another branch (`7.0.x` ?) to see it in next version update ?
Many thanks 👍

**Comment by dprokop** [comment]
@benrubson It will be released with 7.1, beta coming out next week :)

**Comment by benrubson** [comment]
Seems like #25366 removed this PR ?!
@tskarhed ?

**Comment by torkelo** [comment]
yes, it looks like that got lost in the refactor

**Comment by benrubson** [comment]
Thank you @torkelo for your feedback.
Could we then think about including it back please ?
Thank you again 👍

**Comment by torkelo** [comment]
yes, can you open a PR with a re-fix? sorry for this

**Comment by benrubson** [comment]
Here it is @torkelo : #26425
Thank you !

**Pull request merged**
