### PR TITLE
Docs: Remove tooltip-mode documentation from Histogram

### PR DESCRIPTION
**Pull request by grvsoni**
Remove tooltip-mode doc from Histogram as the feature itself is not present and causing a lot of confusion among the users. 

Steps to reproduce the problem:
- Create a Histgram on Grafana
- Trying to display a tooltip
- Tooltip mode isn't available

**What is this feature?**

Remove tooltip-mode doc from Histogram as the feature itself is not present and causing a lot of confusion among the users. 

**Why do we need this feature?**
The feature request for adding tooltip-mode was already raised last year but have no updates. 
To avoid the confusion among the customers we should remove the tooltip-mode segment from Histogram documentation.
Support ticket : https://grafana.zendesk.com/agent/tickets/103344

**Who is this feature for?**

Support ticket : https://grafana.zendesk.com/agent/tickets/103344

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by imatwawana** [comment]
@grvsoni - Sorry I missed this review request. I've tagged the DataViz team as they'll need to review for accuracy. In the meantime, please sign the [CLA agreement](https://cla-assistant.io/grafana/grafana?pullRequest=74110) so we can merge this if it gets approved.

**Review by nmarrs — APPROVED** [review]
Verified that histogram does not currently support tooltip. Thanks for this contribution!

**Comment by nmarrs** [comment]
@grvsoni we are good to merge your contribution :) all we need to do so now is for you to [please sign the CLA agreement](https://cla-assistant.io/grafana/grafana?pullRequest=74110). Thanks!

**Comment by tonypowa** [comment]
Thanks for your contribution. Please see the bellow before we can merge.

>@grvsoni we are good to merge your contribution :) all we need to do so now is for you to [please sign the CLA agreement](https://cla-assistant.io/grafana/grafana?pullRequest=74110). Thanks!

**Review by imatwawana — APPROVED** [review]

**Pull request closed without merging**
