### PR TITLE
Feature Request: Add custom render to table component

### PR DESCRIPTION
**Pull request by mudumat**
I reopen this Pull request which got automatically closed by stale bot. 

I need this functionality extensively in panel plugins I'm working on. For custom switches and so on. I would make the table component super useful. At the moment I have to rewrite a kind of table just because I need custom render cells.

So please!

### CODE REVIEW

**Comment by mudumat** [comment]
It's not my code. I just made a pull request cause the old one seemed to be closed by the bot.

**Comment by kaydelaney** [comment]
@leventebalogh Any thoughts on this? Does it need additional work before being merged?

**Comment by hugohaggmark** [comment]
Not sure what to do with this. The original PR https://github.com/grafana/grafana/pull/26985 had comments that are valuable input to this.

Also @mudumat because you opened the PR I think you need to sign the CLA.

**Comment by mudumat** [comment]
> Also @mudumat because you opened the PR I think you need to sign the CLA.
Even if I'm not the code owner. I just wanted to poke this thing because it was already closed and it seemed to be useful.

**Comment by hugohaggmark** [comment]
I'm going to close this PR but hopefully someone can pick it up and we can reopen it.

**Pull request closed without merging**
