### PR TITLE
Add Selector switches for Alert Fill and Lines -  #7258

### LINKED ISSUE #7258: [Feature request] Make alert threshold visibility in graphs optional
Hey 👋 

For my use-cases I don't really need to see the thresholds of an alert in my graphs and they're pretty stark visually (red and the whole alertable area is tinted as well). That's why I was thinking that perhaps it would make sense to make it optional. 

Maybe a checkbox "Show alert thresholds" in "Alert Config"? Or does "Display > Thresholds" make more sense for this?

### PR DESCRIPTION
**Pull request by ikkemaniac**
Fixes #7258

### CODE REVIEW

**Comment by pfeerick** [comment]
Not in a position to test this, but the concept looks nice... adding toggles for both fill and the line, without breaking any existing setups. Hope this gets implemented ASAP, unless there is some breakage. :) 

btw, CLA (above) is whining that it's not been agreed to.

**Comment by aknuds1** [comment]
Please sign the CLA :)

**Comment by ikkemaniac** [comment]
> Please sign the CLA :)

I must be an idiot because i can't figure it out :(

**Comment by pfeerick** [comment]
> I must be an idiot because i can't figure it out :(

Or perhaps it's a bit... obtuse...

Click on the goldish not signed button above. Then you'll get the agreement, to which you scroll to the bottom of, and sign into / link your github account to. At which point, the CLA bot will be happy. 

image

**Comment by ikkemaniac** [comment]
sorry this isn't going to work as i don't sign my commit with my email.

**Comment by jpalpant** [comment]
@pfeerick Is the only issue with this PR the CLA signing? Because, I don't know much about Grafana or this diff (it looks sane to me?) or how to test it well, but it looks like CI passed and I can manage forking, signing the CLA and even the commit.

**Pull request closed without merging**
