### PR TITLE
GraphNG: Hide grid for right-y axis if left x-axis exists

### PR DESCRIPTION
**Pull request by torkelo**
Fixes so we do not render double grid lines for both left and right axis

Todo
* Fix so it works if you only have a right axis

### CODE REVIEW

**Comment by torkelo** [comment]
working on an alternative solution now

**Comment by leeoniya** [comment]
any chance of squashing https://github.com/grafana/grafana/issues/9305 as part of this work?

**Comment by torkelo** [comment]
not sure I want new options for that yet, maybe once we have a way to hide advanced options

**Comment by torkelo** [comment]
Switched to a better soution

**Review by ryantxu — APPROVED** [review]

**Review by dprokop — APPROVED** [review]

**Pull request merged**
