### PR TITLE
Variables: Fix for flickering repeat panels

### LINKED ISSUE #43234: Table panel w/ repeat option flickers when loading data (flickering, goes black)
**What happened**:
If a table panel is repeated with a dashboard variable, all instances but the first will flicker (go black) on loading/refreshing the data

**What you expected to happen**:
Prior (Grafana 8.2.0) the panel did not go black, when loading new data

**How to reproduce it (as minimally and precisely as possible)**:
- Install a fresh version Grafana 8.3.3 (Windows)

- Make a new dashboard
 - Add a variable to your dashboard: Type: Custom, Values: "1,2,3", Include All option: YES

- Add a new panel to the dashboard
 - Type: Table, Title: $query0, Data Source: "-- Grafana --" Random Walk
 - Repeat option: Repeat by variable: "query0", Max per row: "3"
 - Hit save

- Refresh the dashboard manually and you will see the 2nd and 3rd panel go black during refresh
- Make sure, you really hit the "Reload"-Button hard several times in a row to see the flickering

**Anything else we need to know?**:

I tested the same setup with an old version 8.2.0 and saw no flickering.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Build-in Grafan source "-- Grafana --" Random Walk
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome, Edge
- Grafana plugins: no
- Others: no

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR #42828 fixed one issue but introduced flickering when the refreshing the dashboard. This PR tries to limit the flickering.

**Which issue(s) this PR fixes**:
Fixes #43234

**Special notes for your reviewer**:
Verified that this still works for #42761

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
The naming of VariablesChangedEvent throws me off here, as it's emitted on every time range change so is not only associated with variable value changes. More of a hand over from variable system to dashboard panel query system, saying ok your turn! "

* VariablesFinishedProcessingTimeRangeChangeEvent
* Or something less verbose but in the same vain?

**Comment by hugohaggmark** [comment]
> The naming of VariablesChangedEvent throws me off here, as it's emitted on every time range change so is not only associated with variable value changes. More of a hand over from variable system to dashboard panel query system, saying ok your turn! "
> 
> * VariablesFinishedProcessingTimeRangeChangeEvent
> * Or something less verbose but in the same vain?

Great feedback and I agree, I'll try to find a better name.

**Comment by hugohaggmark** [comment]
I split it up into 2 different events in the end @torkelo. Let me know if this makes more sense.

**Review by torkelo — APPROVED** [review]

**Comment by ashharrison90** [comment]
@empollard as far as i'm aware it's ready to go in, but hugo is out on holiday until next week and i'd want to wait until he's back to double check we're ok with merging it 👍 

so probably monday at the earliest 😄

**Comment by empollard** [comment]
@ashharrison90 Thanks for the update! I've let the customer know and we're set for now. :)

**Pull request merged**
