### PR TITLE
prometheus plugin: Migrate from GrafanaTheme to GrafanaTheme2

### LINKED ISSUE #35097: Explore: Migrate from `GrafanaTheme` to `GrafanaTheme2`
Multiple Explore-related components still make use of `GrafanaTheme`. 
Since Grafana 8.0 introduces `GrafanaTheme2` and deprecates `GrafanaTheme` we should migrate to the new theme.

This should probably be done in multiple small PRs that target a small amount of components to make review easy.

Also the following data sources have components that need to be migrated:
- [ ] Elasticsearch
- [ ] Loki
- [ ] Graphite
- [ ] Prometheus

### PR DESCRIPTION
**Pull request by Betula-L**
**Which issue(s) this PR fixes**:

Fix https://github.com/grafana/grafana/issues/35097

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by Betula-L** [comment]
@torkelo How could this PR merged after approved?

**Comment by torkelo** [comment]
Using the green button "Squash and merge"  :)

**Comment by torkelo** [comment]
what do you mean?

**Comment by Betula-L** [comment]
It seems something blocks.

**Comment by torkelo** [comment]
Sorry, thought you had merge rights :)

**Pull request merged**
