### PR TITLE
Alerting Notifications: Send alerts to matrix homeserver directly

### LINKED ISSUE #19777: [Feature Request] Matrix Notification Channel
**What would you like to be added**: Support sending Grafana alert notifications to [Matrix](https://github.com/matrix-org/synapse).

**Why is this needed**: Grafana currently supports other instant messaging / group chat systems (ie Slack, Discord, Telegram), and it would be nice to have the option to notify via Matrix as well.

### PR DESCRIPTION
**Pull request by yasharne**
**What this PR does / why we need it**:
This PR adds the ability to send the Alerting notifications directly to [Matrix](https://matrix.org/)
image

image

**Which issue(s) this PR fixes**:

Fixes #19777

### CODE REVIEW

**Comment by yasharne** [comment]
I have fixed errors generated from continuous-integration/drone/pr but I don't know how to deal with the below error as the URL used to make GET request varies based on the dashboard image:
```

+ golangci-lint run --config scripts/go/configs/.golangci.toml ./pkg/...
--
2 | pkg/services/alerting/notifiers/matrix.go:150:25: G107: Potential HTTP request made with variable url (gosec)
3 | dashboardImage, err := http.Get(imageURL)
```
I don't see any vulnerability as `imageURL`  is generated by the Grafana backend

**Comment by aknuds1** [comment]
Sorry, closing this PR since we're not adding more notifiers to Grafana core. We are planning to instead support new notifiers as plugins, although this is unfortunately not in place yet.

**Comment by yasharne** [comment]
@aknuds1  So we cannot send alerts to matrix until you define a new solution to add notifiers as plugins?

**Comment by aknuds1** [comment]
The notifier can't be part of core Grafana at least. There's always the possibility to fork Grafana on the other hand, and use your custom version with the notifier included. Doesn't there exist a bridge between Slack and the Matrix client Element? That might work in the meantime?

**Comment by yasharne** [comment]
@aknuds1 There is a third-party plugin on the matrix which sends slack-styled messages to the matrix but it is very buggy, we've been using this plugin for about a year and we came to the situation where grafana sends the alert to the plugin but the plugin didn't show the message in the room with no errors, that's why I decided to write this notifier.
If there is no possibility for this PR to be merged, how can I change my PR to work as a plugin? are there any documents about that?

**Comment by aknuds1** [comment]
To my knowledge we haven't implemented support yet for notifiers as plugins, but it's planned.

**Comment by CameronNemo** [comment]
@aknuds1 is there somewhere I can follow the progress of support for notifier plugins?

**Comment by aknuds1** [comment]
@CameronNemo we want to start work on it as soon as possible, but don't have anything concrete yet unfortunately.

**Comment by MurzNN** [comment]
@aknuds1 Already more than year passed after you decline this PR, with no alternatives provided and even no ETA for notifier plugins feature!
But Matrix.org ecosystem is growing and more users switches to it from Slack, Discord and other commercial services.

So can you PLEASE discuss this PR with management again, including described opinions? 

_...cuz Matrix users can't wait more XX years when notifier plugins feature will be available..._

**Comment by shukon** [comment]
Isn't Grafana all about open-source? And I mean yeah, forking the whole project works, but I feel like this feature is so much more in tune with the overall project philosophy:

> Open Source is at the heart of what we do at Grafana Labs. We believe building software in the open, with thriving communities, helps leave the world a little better than we found it.

Matrix is not niche anymore and it is certainly used a lot in the sysadmin world. Declining a ready-made PR for a main open network while supporting proprietary solutions like telegram or slack just feels a bit off. Also there is still nothing happening in the notifier plugin issue, though I get that things sometimes get stuck in the backlog when there is some sort of working solution in place.
But maybe, if plans changed with the plugins, reconsider this PR? :heart:

**Pull request closed without merging**
