### PR TITLE
User management: Use HMAC-SHA256 to generate time limit codes (password reset tokens)

### LINKED ISSUE #29384: Security: Use sha256 instead of sha1 when generating user invite codes
G401 (CWE-326):  Use of weak cryptographic primitive
`pkg/services/notifications/codes.go:40`

We use different parts of the invite links based on positions of the string, which we need to update as well.
https://github.com/grafana/grafana/blob/master/pkg/services/notifications/codes.go#L61

This code is quite old so some tests would be nice :)

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
**What this PR does / why we need it**:

* changes the time limit code generation function (which is used to create password reset tokens) to use HMAC-SHA256 instead of SHA-1
* adds multiple new testcases

Note: This PR updates the format of the reset codes, and therefore invalidates codes which may be already delivered to users' mailboxes. The default expiration time is 2 hours (and afaics cannot be changed), so codes sent two hours before upgrading Grafana will become invalid even though they should be valid - might be good to add this information to the changelog.

**Which issue(s) this PR fixes**:

Fixes #29384.
The above ticket mentions invite codes, but afaics the time limit codes are used for password reset tokens:
https://github.com/grafana/grafana/blob/d2c8b24d7222bda57c4cc3d2980b60d66deedf92/pkg/services/notifications/notifications.go#L151-L155

and not for invite codes:
https://github.com/grafana/grafana/blob/d2c8b24d7222bda57c4cc3d2980b60d66deedf92/pkg/api/org_invite.go#L59

**Special notes for your reviewer**:

The core logic is untouched, except `setting.SecretKey` is used for the HMAC key instead of being part of the message, and I've removed `minutes` from the message because it's already (indirectly) included in the `endStr` (which is part of the message).

I'm happy to add more test cases if any important ones are missing.

# Release notice breaking change

Password reset links sent before the upgrade will no longer work and have to be resent. Since the duration of those links are only two hours we decided to not support both token formats.

### CODE REVIEW

**Comment by andreasgerstmayr** [comment]
rebased on latest main branch

**Comment by andreasgerstmayr** [comment]
ping for review

**Comment by andreasgerstmayr** [comment]
rebased on latest main branch

**Comment by andreasgerstmayr** [comment]
no-one interested in replacing SHA-1 in favor of HMAC-SHA256 for password reset tokens?

**Comment by bergquist** [comment]
Sorry about the slow response! Resolving the merge conflicts and starting to look at the code.

**Review by bergquist — APPROVED** [review]
LGTM! Thank you for contributing to Grafana :)

**Comment by andreasgerstmayr** [comment]
Thanks for merging! 🎉

**Pull request merged**
