### PR TITLE
CommandPalette: Move quick add actions to top level

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

Quick add actions incorrectly had a parent set to their position in navtree. 

This changes quick add actions to move the to the top level of the command palette so they're easily visible.

~~Additionally, it changes "New Folder" and "New Dashboard" to use the 'Create' verb for consistency. Happy to change "Create alert rule" to "New" instead, or back out this change entirely.~~ I've backed out this change - we can do this indepedently to make sure we change to the correct thing.

**Why do we need this feature?**

So the actions are visible, rather than hidden behind command palette search

**Who is this feature for?**

People who want to create things!

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zsofiakm** [comment]
We might want to standardize on "New...". On `/dashboards`, that's what the split button is using. To me, "New" sounds more universal. But I don't have a strong opinion.

**Comment by amy-super** [comment]
Agree with @zsofiakm - we use "New" on the actual pages, so probably best to standardize on that. And that was probably my mistake on quick actions 😅

**Comment by chri2547** [comment]
> We might want to standardize on "New...". On `/dashboards`, that's what the split button is using. To me, "New" sounds more universal. But I don't have a strong opinion.

Docs Squad thoughts here...we favor "Create dashboard" and "Create alert rule" and not "New" or "Create new". Why? Because "Create" is a verb and it implies that what's being created is 'New'. Users never create an old dashboard or alert rule.

**Review by ashharrison90 — APPROVED** [review]
lgtm! 🙌

**Comment by joshhunt** [comment]
I've backed out changing the name of either of the actions, so this PR is _just_ moving them to the root.

**Pull request merged**
