### PR TITLE
v7.0.4 (Cherry picks,  version bump & backports)

### PR DESCRIPTION
**Pull request by torkelo**
* Provide correct field scoped vars for data links interpolation, (#25318), merge-sha: 0f5b894256f44da16ff058a11a915898f6284c4b
  * Search: Only move dashboards into expanded folders UI-wise, (#25363), merge-sha: 1790ece4d5f7421b381efc6fcbf543cec4cb2ba6
  * TablePanel: Sort numbers correctly , (#25421), merge-sha: 5f767e2c9ae12e004bf034f5943f22e8c4ab9ac4
  * Table: Support custom date formats via custom unit, (#25195), merge-sha: 6fe9982ff0698430965a9d1f22c60bed6f3576fa
  * Fix dense y-axis labels in heatmap using tsbuckets, (#24351), merge-sha: b15a401efa94630a4d8769890503e1dcd50b3514
  * Update Bitcoin currency to use proper symbol, add mBTC and μBTC, (#24182), merge-sha: d3c57ac251650c85a893c42def6ab42b501a030e
  * UI/Switch: Makes Switch ID generation more stable, (#25542), merge-sha: 12d2f2c026fe7ba5a824d564a7cf640becf669cd
  * Security: Use Header.Set and Header.Del for X-Grafana-User header, (#25495), merge-sha: 034abaa73a0684f624d30857f70fa8192d36ddf3
  * InfluxDB: Fix invalid memory address or nil pointer dereference when schema is missing in URL, (#25565), merge-sha: bd8a04a6a573e450d1feb57dff76a9f0f58d2f1f
  * Azure Monitor: fixes undefined is not iterable, (#25586), merge-sha: c0139b7d4212baf410ac695966bc4899be3d1fb1
  * package.json: Depend on es-check since we need it for CI, (#25593), merge-sha: cf2343fac82706bdb409ccd6401585f6f81fb8d1
  * Chore: Upgrade Jest to latest, (#25591), merge-sha: 91c24e1f560ec16a43312e05ff67e9982a2f5b00
  * Explore/Logs: Fix tooltip display for log graph, (#25544), merge-sha: bd76c66e5058b1820570044e21f4cbb9239d7a24
  * Stackdriver: Use default project name if project name isn't set on the query, (#25413), merge-sha: 4aff2d7469f45244768d050def3c87fd7a7d994a
  * Variables: Links that update variables on current dashboard does not trigger refresh / update, (#25192), merge-sha: aa5fb20cfd3944eb1a8d15e7e1a25d8fd2e3e562
  * Stackdriver: Fix creating Label Values datasource query variable, (#25633), merge-sha: e6a5e88054ae2063a6f58b3464636492a36d9095
  * API: Recognize MSSQL data source URLs, (#25629), merge-sha: d352c213b3c12d446eaab91162016a7106f39a24
  * Dashboard: Redirects for old (pre 7.0) edit & view panel urls, (#25653), merge-sha: d6ed8c522c63423a3442830956ba008dff74a444
  * Chore: Upgrades jQuery and @types/jQuery, (#25651), merge-sha: e2ba0731e284f7fe524c6dec2686594d6248daa5
  * Datasources: Handle URL parsing error, (#25742), merge-sha: 58cefe73ee922459ff17fd2d3cbc09a6c48b05a0
  * CircleCI: Upgrade build pipeline tool, (#25741), merge-sha: ba6aefb6ec0b3bed60e71d103dbea5d1bf2711bf
  * Templating: Fixes query variable with ${__searchFilter} value selection not causing refresh & url update, (#25770), merge-sha: b7d26b12dd681f2eb69abf36eaca0a6b7a5e9c2d

TODO: 
- [x] Version bump
- [x] Backports of template variable fixes 
- [ ] ~cherry pick  https://github.com/grafana/grafana/pull/25698  (or try at least)~ Can't do it, depends on #24430 which had few followup PRs

### CODE REVIEW

**Comment by aknuds1** [comment]
Shouldn't the target be v7.0.x @torkelo?

**Comment by aknuds1** [comment]
Waiting for merge conflicts to be fixed before I review.

**Comment by aknuds1** [comment]
#25651 hasn't been cherry-picked, @dprokop will try to include it later today and see if it doesn't have too many conflicts.

**Comment by aknuds1** [comment]
Apart from #25651 it all looks good.

**Comment by marefr** [comment]
- Please consider if https://github.com/grafana/grafana/issues/25771 will/can make it for 7.0.4, otherwise change milestone to 7.1.0. 
- Have added https://github.com/grafana/grafana/pull/25565 to 7.0.4 with cherry-pick needed label. Want me to cherry pick that one?
- https://github.com/grafana/grafana/pull/25586 feels like something we could include in 7.0.4. What do you think?

**Comment by dprokop** [comment]
@arve @torkelo cherrypicked jquery bump. Had to pick https://github.com/grafana/grafana/pull/25617 too

**Review by marefr — APPROVED** [review]
LGTM

**Review by aknuds1 — APPROVED** [review]
LGTM - verified with `grabpl verify-cherrypicks`.

**Pull request merged**
