### PR TITLE
Plugins: expose react-redux, redux

### LINKED ISSUE #18443: Plugins: Support accessing react-redux from plugins
systemjs fails to dynamically load imported modules such as react-redux, material-ui, etc.

Example React panel that imports Provider
import { Provider } from 'react-redux';

Screen Shot 2019-08-07 at 11 33 39 AM

A possible fix is to add plugin-babel to the SystemJS.config or to allow merging custom webpack configs the grafana-toolkit cli build command.
plugin_loader.js:
grafanaRuntime.SystemJS.config({
  …
  map: {
    …
    'plugin-babel': 'vendor/systemjs-plugin-babel/plugin-babel.js',
  }

See also #15341

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #18443

Expose react-redux and redux to plugins

### CODE REVIEW

**Comment by ryantxu** [comment]
Should we also expose `redux-thunk`?  or is that something we may not keep?  and/or could be safely imported directly in the plugin?

**Comment by dprokop** [comment]
@ryantxu see my coment here https://github.com/grafana/grafana/issues/18443#issuecomment-520308963

**Comment by ryantxu** [comment]
I'll close this now -- I need to understand redux more before I have a sense of what is possible

**Comment by ryantxu** [comment]
reopening after discussion in #18443

**Review by torkelo — APPROVED** [review]

**Review by dprokop — APPROVED** [review]
@ryantxu, LGTM, see this one https://github.com/grafana/grafana/issues/18443#issuecomment-521129488

**Pull request merged**
