### PR TITLE
Loki / Prometheus: Fix query builder select component in safari

### PR DESCRIPTION
**Pull request by itsgareth**
this pr fixes the behaviour shown in the linked escalation.

**How to test:**
1. follow the steps in this video to reproduce (**you must be using safari**): https://github.com/grafana/support-escalations/issues/6771#issuecomment-1640359381

2. confirm that this bug no longer exists and you can add aggregations without errors.

**Side effects of this fix:**

as you can see from the screenshots, the is a slight spacing difference between the labels and inputs of the query cards

Before & After:

 
ss-before

ss-after

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/support-escalations/issues/6771

### CODE REVIEW

**Comment by gabor** [comment]
hi @gwdawson could this be the same problem as in this bugreport? https://github.com/grafana/grafana/issues/69649

**Review by gabor — APPROVED** [review]
LGTM 👍

**Comment by matyax** [comment]
@gwdawson The screenshots in the PR are outdated.

**Review by matyax — COMMENTED** [review]
Current main:

imagen

This branch:

imagen

While it doesn't look problemtic, we don't now if these changes are going to produce unexpected visual changes.

**Review by matyax — APPROVED** [review]

**Pull request merged**
