### PR TITLE
tech(build): replace npm with yarn

### PR DESCRIPTION
**Pull request by bergquist**
`npm install` is not deterministic which can cause problems when people want to build older versions of grafana. A commit should always build the same content.

It also decreases the install time from 50s to 11s on my machine :)

### CODE REVIEW

**Comment by bergquist** [comment]
As recommended by @davidxcheng

**Comment by bergquist** [comment]
cuts about 1min on the grafana ci build.

**Comment by torkelo** [comment]
@bergquist nice! Do you feel this is ready for 4.1 & merge?

**Comment by bergquist** [comment]
Perhaps it should wait until 4.2 unless we do 4.1-beta2.

**Comment by torkelo** [comment]
4.1-beta2 seems pointless at this point as all bug fixes for 4.1 are solved

**Comment by torkelo** [comment]
strange, getting this error:

Fatal error: Unable to find local grunt.

**Comment by torkelo** [comment]
ah, sorry, my mistake, yarn did not complete successfully, needed node 6

**Pull request merged**
