### PR TITLE
TopNav: Panel edit changes

### PR DESCRIPTION
**Pull request by torkelo**
* [x] Make panel edit not absolutely positioned on top of dashboard instead hide dashboard 
* [x] Make panel edit work with new Page component and top nav
* [x] Make panel edit add "Edit panel" to breadcrumb
* [x] Add Custom Page layout type in order for PanelEditor to customize padding (extends to the edge)  and it does not need a scroll container.  
* [x] Make the panel edit toolbar actions adapt based on topnav enabled or not (Small size when topnav is enabled) 
* [x] Fixes the issue of ToolbarButton variant styling and supporting edge case uses of placing ToolbarButtons on the canvas (via TimeRangePicker and RefreshPicker). Was done by adding canvas variant and isOnCanvas props to TimeRangePicker

Breaking change
* [x] Remove the ability to open dashboard settings while panel edit is still open. This is just causing to many issues. Like what should the breadcrumb be? and when you leave panel edit and go back to dashboard (via breadcrumb) you trigger panel edit exit prompt / warnings (like save unsaved changes to library panel). Removing this cog icon just makes the actions so much cleaner in panel edit and it becomes a more self contained view. We did remove this ability once before during v7 development but had to add it back due to popular demand. But I am willing to try again as it is causing too many issues and feels so wrong and simplifies panel edit from a UX point of view. 

With topnav
Screenshot from 2022-09-06 11-11-53

Without:
Screenshot from 2022-09-06 11-14-03

# Release notice breaking change

Dashboards: Remove the ability to open dashboard settings while panel edit is still open.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey @torkelo 👋🏾 , here are some questions regarding this PR 😄 (my attempt to gather more understanding )

> Remove the ability to open dashboard settings while panel edit is still open[....] We did remove this ability once before during v7 development but had to add it back due to popular demand

Do you have the GitHub issue/discussion link or do you know what were the main concerns from the community to keep the "dashboard settings" available when editing a panel? I want to get more context and see what the potential issues will be and how we could handle them 

- I think the TimePicker style was broken on mobile (Currently display it in one line, now it takes more space) 

image
- Out of curiosity: Is kiosk mode changing its behavior in the new topnav? or is the implementation just missing? 
image
Thanks in advance!

**Comment by torkelo** [comment]
@axelavargas 
> Do you have the GitHub issue/discussion link or do you know what were the main concerns from the community to keep the "dashboard settings" available when editing a panel? I want to get more context and see what the potential issues will be and how we could handle them

I searched but could not find it. I think the main concern is being able to quickly go and edit variables. But I think we can solve that in other ways than opening dashboard settings. 

> I think the TimePicker style was broken on mobile (Currently display it in one line, now it takes more space)

I can't replicate this, it does not take up more space it just wrapps (instead of pushing itself out of viewport). Tested with some different scenarios (with variables). Looks to work a lot better (more responsive) in this PR than in main. 

> Out of curiosity: Is kiosk mode changing its behavior in the new topnav? or is the implementation just missing?

yes kiosk mode is not supported / handled yet. (on the todo)

**Review by ashharrison90 — COMMENTED** [review]
this looks great - it's gonna make it **so much clearer** where you are in the hierarchy when editing 🙌 

think i've found a bug. it's fairly minor, but could be tricky to pin down. editing anything other than a timeseries seems to need a state update to trigger the breadcrumbs correctly:

https://user-images.githubusercontent.com/20999846/189380867-bb28b8db-0606-4488-b045-7e0867bcb6fd.mp4

**Comment by torkelo** [comment]
@ashharrison90 thanks for finding that bug! I had scene it once but then could not replicate it (because I was only opening time series panels). But found the issue, fixed it and added support for "View panel" in breadcrumb as well

**Review by ashharrison90 — APPROVED** [review]
looks and works great! 🙌

**Review by axelavargas — APPROVED** [review]
Hi @torkelo, great job with this PR 🙌🏾, thanks for answering all my questions!

For our part (@grafana/dashboards-squad) we will keep an eye on how the community reacts to the removal of the "Dashboard settings cog in panel Edit". I'd say we should **add this "breaking change" to the changelog** to be clear that it's an intentional change and not a bug :)

Also, I was testing this PR and I think with your changes, [this a11y issue](https://github.com/grafana/grafana/issues/46493) will be resolved 🥳

**Pull request merged**
