### PR TITLE
Chore: use any rather than interface{}

### PR DESCRIPTION
**Pull request by ryantxu**
**What is this feature?**

Since go 18, `type any = interface{}` -- this PR updates our `interface{}` references to use the alias.

**Why do we need this feature?**

Not *needed* but a bit nicer to look at :) -- since so much code gets copy+pasta, better to get rid of all of it rather than a few things using any and others using interface{}

**Who is this feature for?**

go developers

### CODE REVIEW

**Review by xnyo — COMMENTED** [review]
Great work! I have reviewed the files owned by plugins-platform-backend and they look good, but the protobuf generated files should be excluded:

**Review by aangelisc — APPROVED** [review]
Changes look good for @grafana/partner-datasources 👍

**Review by zserge — APPROVED** [review]

**Comment by zserge** [comment]
Shall we have a linter or ruleguard rule for this maybe?

**Comment by ryantxu** [comment]
> Shall we have a linter or ruleguard rule for this maybe?

Yes... i'll look at some options, but will merge first since since bit rot will be fast with this PR!

**Pull request merged**
