### PR TITLE
ReleaseNotes: Update release notes for v8.2.3

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

ReleaseNotes: Update release notes for v8.2.3

### CODE REVIEW

**Review by malcolmholmes — APPROVED** [review]

**Comment by zoltanbedi** [comment]
@dsotirakis I think this should be backported to v8.2.x. The docs changes for sure not sure about the latest.json.

**Comment by dsotirakis** [comment]
@zoltanbedi you mean something like https://github.com/grafana/grafana/pull/41268/files?

**Comment by zoltanbedi** [comment]
dah, yeah. But the changelog.md changes are missing in that pr. is that in another pr?

**Comment by dsotirakis** [comment]
😱 yes - raising another PR for it, thanks for catching that @zoltanbedi!

**Comment by dsotirakis** [comment]
@zoltanbedi https://github.com/grafana/grafana/pull/41343

**Pull request merged**
