### PR TITLE
Cherry-picks for 6.7.1

### PR DESCRIPTION
**Pull request by xlson**
--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Check if the datasource is of type loki using meta.id instead of name., (#22877), merge-sha: ec9167e9728e742adeda2f9ee8a3ebb7056b0601
  * BackendSrv: only add content-type on POST, PUT requests, (#22910), merge-sha: 8d5c6053db07fa4ed0874ec85cbac8c0c4c5c23e
  * Azure: Fixed dropdowns not showing current value, (#22914), merge-sha: d16211b7827e70510456aac9336e14610854faba
  * Panels: Fixed size issue with panel internal size when exiting panel edit mode, (#22912), merge-sha: 8e131384e34f08ce7e1807e766cc918dc8b4036f

### CODE REVIEW

**Comment by marefr** [comment]
@dprokop [this one](https://github.com/grafana/grafana/pull/22754) have cherry pick needed and milestone 7.0. Should it really be included in 6.7.1?

**Comment by dprokop** [comment]
@marefr no, we talked about it with @xlson

**Comment by dprokop** [comment]
Also I see it's not included, it's only in the description

**Comment by marefr** [comment]
@dprokop sorry, got confused by the PR description. @xlson please remove https://github.com/grafana/grafana/pull/22754 from PR decsription,

**Review by marefr — APPROVED** [review]
LGTM

**Review by dprokop — APPROVED** [review]
no worries @marefr !

LGTM @xlson

**Comment by xlson** [comment]
Thanks, adding another PR with a docs fix so that CI becomes happy.

**Pull request merged**
