### PR TITLE
BackendSrv: Restructure response stream to resolve a retried request correctly

### PR DESCRIPTION
**Pull request by kalleep**
**What is this feature?**
I noticed that the retry logic in backend_srv don't work properly, [this part](https://github.com/grafana/grafana/blob/main/public/app/core/services/backend_srv.ts#L253-L291). 

My understanding of it is that in case we get a 401 we try to verify that the user is signed-in by hitting an endpoint and if that one succeeds the the original request should be retried. If I look a network tab I see that the original request failed with 401, then the call that we use to verify if the user is signed and if that one succeeds we retry the original request. This is all expected but it seems like the value we return to the caller is the failed request causing the front-end to be in a weird state

I manged to solve this by no longer split up the response stream into both success and failure branches and by wrapping the original steam in a defer. I could not get this to work with the two stream and merge setup that existed before

Disclaimer: this is the first time I have done anything with rxjs so maybe it is possible to solve this with the two stream setup that we have today.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

### CODE REVIEW

**Comment by joshhunt** [comment]
I'm not entirely familiar with this, but I _think_ this may actually be working as designed - both the first error and later success state should be emitted to the rxjs stream, and it's up to the caller to handle these, and I _think_ maybe some consumers (such as Dashboards?) do work this this properly.

However, most of the time we convert the rxjs stream to a Promise, which doesn't work with this pattern. A Promise can only emit a single value - It cannot be rejected and then later resolved to a success value, so we get into this weird state.

I'm not sure what the exact correct solution is, we'll have to have a play around.

**Comment by kalleep** [comment]
@joshhunt Yes maybe but I also noticed that test  for this seems to be incorrectly configured. If you look at my latest commit [d1f0c53](https://github.com/grafana/grafana/pull/66095/commits/d1f0c53c9ff4777033e7ca1ac401332b25214edf) I have changed so that we expect the request call to be made two times instead of always once. So the test branch that should fail first request then calll login ping and later retry the request was configured to only expect one call to the original request

**Comment by joshhunt** [comment]
Actually looking further, we use [`lastValueFrom`](https://rxjs.dev/api/index/function/lastValueFrom) which

> Converts an observable to a promise by subscribing to the observable, waiting for it to complete, and resolving the returned promise with the last value from the observed stream.

_Seems_  to do what we would want it to do. So I don't know :)

**Comment by kalleep** [comment]
Yes, but for some reason the last value is not the retired request but the original failed request. Seems to happen on every request path I have tried so far

**Comment by kalleep** [comment]
> I don't think the 401 error that was captured and later successfully "retried" and succeeded should be emitted, I don't think that was the intent at least. The intent was to have a way for API calls to succeed when the session token has expired and needs to be renewed if I remember correctly.

I admit I don't have full context on this is expected to work. Do you mean that we should get the successful response back on the happy path or the failed one?

Atm when this case is triggered I can see 3 request being made, one for the original request that returns 401, later the request rotate the token and then the original request again. But seems like the return value to the caller is the first one, the 401.

**Comment by kalleep** [comment]
@torkelo Yes that is how I expected it to work.

It requires some modifications to trigger this consistently. They easiest way it to enable clientTokenRotation feature toggle.

And then apply this patch:
```
diff --git a/pkg/services/authn/clients/session.go b/pkg/services/authn/clients/session.go
index 1c0204df55..384e50a5fe 100644
--- a/pkg/services/authn/clients/session.go
+++ b/pkg/services/authn/clients/session.go
@@ -55,7 +55,7 @@ func (s *Session) Authenticate(ctx context.Context, r *authn.Request) (*authn.Id
 	}
 
 	if s.features.IsEnabled(featuremgmt.FlagClientTokenRotation) {
-		if token.NeedsRotation(time.Duration(s.cfg.TokenRotationIntervalMinutes) * time.Minute) {
+		if token.NeedsRotation(10 * time.Second) {
 			return nil, authn.ErrTokenNeedsRotation.Errorf("token needs to be rotated")
 		}
 	}
diff --git a/pkg/services/contexthandler/contexthandler.go b/pkg/services/contexthandler/contexthandler.go
index 62c5972100..75613ad84b 100644
--- a/pkg/services/contexthandler/contexthandler.go
+++ b/pkg/services/contexthandler/contexthandler.go
@@ -492,7 +492,7 @@ func (h *ContextHandler) initContextWithToken(reqContext *contextmodel.ReqContex
 	}
 
 	if h.features.IsEnabled(featuremgmt.FlagClientTokenRotation) {
-		if token.NeedsRotation(time.Duration(h.Cfg.TokenRotationIntervalMinutes) * time.Minute) {
+		if token.NeedsRotation(10 * time.Second) {
 			reqContext.LookupTokenErr = authn.ErrTokenNeedsRotation.Errorf("token needs rotation")
 			return true
 		}
```

With this changes we bypass the scheduling we have to perform token rotation so that retry logic is triggered every 10 seconds.

**Comment by torkelo** [comment]
thanks, can't test this now, but can test next week

**Comment by torkelo** [comment]
pushed an update to fix and simplify the logic a bit, and make sure we only do one token rotation and not multiple concurrently. 

I think the biggest task now is updating the tests (Which does not look trivial)

**Comment by torkelo** [comment]
@kalleep any update on this?

**Comment by torkelo** [comment]
I think it's just about fixing the tests

**Comment by torkelo** [comment]
@mgyongyosi if we are to do this for G10 I think it needs to be merged tueday

**Comment by mgyongyosi** [comment]
@torkelo We are not planning to release this with G10. The clientTokenRotation functionality is behind a feature toggle (FeatureStateAlpha) and it is disabled by default, so it shouldn't cause any issues.

**Review by torkelo — APPROVED** [review]
been testing this some more and i I think it all seems to work really well :)

**Pull request merged**
