### PR TITLE
Fix empty contact point URLs when template parsing fails

### PR DESCRIPTION
**Pull request by santihernandezc**
**What this PR does / why we need it**:

We're using the `tmpl()` function on contact point URLs. This function is returned by `TmplText()` and depends on the correct execution of the template passed into that last function.
If there's an error while parsing the associated template, the URL ends up being an empty string. This causes notifications to never be sent.

This PR removes template parsing for URLs. This way, if there's an error while parsing the contact point's template, the URL would still be valid and the notification would be sent.

I also noticed that logs for requests have no `method` if that field is empty. I fixed this by first making sure the method is in place and then logging.

**Which issue(s) this PR fixes**:

https://github.com/grafana/support-escalations/issues/2261

**Special notes for your reviewer**:

There are no tests for URL parsing, or anything that seems like a valid reason to have this parsing in place. If there's indeed a reason for parsing the URL, then the fix would be to use the default contact point URL as a fallback.

### CODE REVIEW

**Comment by yuri-tceretian** [comment]
Unfortunately, the motivation for supporting templates in URLs is not clear (probably @codesome can explain). However, based on assumption that that was done intentionally, I think that removing the support for templates is a too big change and can brake some users. 
Instead, I think we should make it more clear if URL gets broken due to incorrect user input. What do you think about adding more validation for the rendered URL (I think that `url.Parse` can be enough), and providing some meaningful error when URL is not valid?

**Comment by santihernandezc** [comment]
@yuri-tceretian I agree, it can be a breaking change, that's why this PR is a draft. If someone from the team has more context about why we need this, I have another fix ready to be committed. 

What is weird is that there's already validation for the URL in place. If you enter invalid values you get errors like these:

Screen Shot 2022-03-29 at 21 06 20

Screen Shot 2022-03-29 at 21 05 45

Since we got validation for the URLs and I didn't find any tests for template variables in URLs or documentation about the subject, I don't know if parsing a URL as if it was a template is something that was added on purpose or just an error that got replicated for different notifiers.

If we actually need to parse URLs as templates, my proposed solution would be to use the value given to the validators' factory function as a fallback if it turns out to be an empty string after using `tmpl()`.

**Comment by codesome** [comment]
> Unfortunately, the motivation for supporting templates in URLs is not clear (probably @codesome can explain)

I don't remember at this point, but I can see the use case of having URLs to have templated GET URL parameters for example.

**Comment by yuri-tceretian** [comment]
> If we actually need to parse URLs as templates, my proposed solution would be to use the value given to the validators' factory function as a fallback if it turns out to be an empty string after using tmpl().

This is a good alternative, in my opinion. Please make sure that we indicate this situation in logs.

**Comment by santihernandezc** [comment]
@codesome Teams, DingDing, VictorOps and Google Chat don't give you the option to make a GET request, it's only POST, and these are the only 4 contact points that get their URL parsed as a template.
It could be to dynamically modify the url, but I don't really think so since we don't have tests or docs for this. That's why I don't know whether we should keep this parsing step or not.

**Comment by santihernandezc** [comment]
> Please make sure that we indicate this situation in logs.

@yuri-tceretian we're already logging a warning when template execution fails:
```
WARN[03-29|15:31:43] failed to template Teams message logger=alerting.notifier.teams err="template: prueba:9:12: executing \"myalert\" at <len .Annotations>: error calling len: reflect: call of reflect.Value.Type on zero Value"
```
Do you think another log with `INFO` level is appropriate for notifying we're using the default URL provided? We first need to define if we need this URL templating or not though.

**Comment by yuri-tceretian** [comment]
> Do you think another log with INFO level is appropriate for notifying we're using the default URL provided?

Yes, I think it still makes sense to write a separate log message that would mention that the URL could not be expanded and Grafana falls back to the raw URL.

> We first need to define if we need this URL templating or not though. 

That's a legitimate question. Personally, I can see some potential usefulness in the feature itself (ignoring how it is implemented right now). However, changing this in a patch release is not a good idea even though it's an undocumented feature (because code is open-source :) )

**Comment by yuri-tceretian** [comment]
The change looks good to me. However, I would recommend adding some tests to cover the changes.

**Review by yuri-tceretian — APPROVED** [review]
LGTM

**Comment by ethirolle** [comment]
@santihernandezc will this be in 8.4.7 release?

**Comment by santihernandezc** [comment]
@ethirolle yep!

**Pull request merged**
