### PR TITLE
keep track of elastic search version and generate query according to version

### PR DESCRIPTION
**Pull request by replay**
This is the pull request for what I've mentioned in my comment here:

https://github.com/grafana/grafana/issues/3236#issuecomment-158758427

### CODE REVIEW

**Comment by torkelo** [comment]
nice! 

Can you please sign the CLA? 
http://docs.grafana.org/project/cla/

**Comment by replay** [comment]
Sure, done!

**Comment by torkelo** [comment]
if you could add 1-2 unit tests that would be great.
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/query_builder_specs.ts

**Comment by replay** [comment]
Ok, gonna do that. Just wanted to confirm with you first that you're generally OK with the way I split it into the major versions and the format of storing it into the DB.

Will try to get the tests done today

**Comment by torkelo** [comment]
yes, that is fine

**Comment by replay** [comment]
Added some tests and I've also set the default version for newly added elastic search sources to 2.x https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/query_builder_specs.ts

**Pull request merged**
