### PR TITLE
SingleStat : Conditional Formatting

### LINKED ISSUE #11418: [Feat] Conditional formatting
## Introduction

As of writing (Grafana v5.1-pre) we have support for 
* coloring background/value in the Singlestat panel based on a numeric range and 3 colors
* coloring cell/value/row in the Table panel based on a numeric range and 3 colors

image

image

There are a lot of feature requests/issues requesting greater support of coloring in table panel and the singlestat panel:
* #7631 [Feature request] Allow Text to Value mappings in Singlestat panel
* #3601 table panel: colorize cell value based on regex pattern match
* #9500 Feature request: Allow thresholds for Time column in tables
* #3608 Thresholds with more than 3 comma-separated values
* #8404 [Feature request] Singlestat null value color 
* #4821 Table Panel coloring shouldn't require display of referenced column
* #9709 Single stat panel with gradient color
* #7411 [Feature request] Variable threshold values in Singlestats panel
* #7286 [Feature request] Row and/or Column styles in Table

Historically we've received a few PR's that tried to solve some of the issues above, but we haven't been able to merge them because we feel the solutions are either hard to understand from a user perspective or either it makes the Grafana code base/features more and more shattered.

## Proposal

This issue aims to find one solution for solving all (or most) of the issues above and by that delivering a good and consistent user experience. By that said, we probably want to split this up in smaller issues if we decide that this is a good way forward.

In general the *Conditions editor* for alerts are very similar to a rule/conditional formatting editor functionality and would probably fit quite nice with a few modifications. This is something to take into considerations when implementing this.

image

### Conditional rules evaluator

A panel needing conditional formatting shouldn't need to implement their own solution for evaluating conditional rules thus making this a core component/helper library is a must. 
It would be nice if this component also could return a list of rule types that it supports.

Examples of rule types:
* Value is empty
* Value is not empty
* Text contains
* Text does not contain
* Text starts with
* Text ends with
* Text is exactly
* Date is
* Date is before
* Date is after
* Greater than
* Greater than or equal to
* Less than
* Less than or equal to
* Is equal to
* Is not equal to
* Is between
* Is not between

### Singlestat panel - colorize background/value

Changes here compared to current functionality is that 
* it allow you to define unlimited amount of color formatting's compared to today's maximum of three.
* it allow support for coloring based on empty/non-empty values
* it allow support for coloring based on string/text values
* it allow support for coloring based on date/duration values

#### UX mockup/example to underline functionality needed/wanted

image

### Table panel - colorize cells/values/rows

Changes here compared to current functionality is that 
* it allow you to define unlimited amount of color formatting's compared to today's maximum of three.
* it allow support for coloring based on empty/non-empty values
* it allow support for coloring based on string/text values
* it allow support for coloring based on date/duration values
* it allow support for coloring a row based on a hidden/non-rendered column

Currently you can define thresholds for each defined *Column style*. Maybe we want to continue having this possibility since we can make smart decisions of what columns to apply the conditional formatting rules to. 

On the other hand it quite weird to continue using the column styles since they're basically provides options for how to render column cells/convert raw column value using specific data types and options etc. Regarding coloring we currently supports cell/value/row which affects cells or rows and rules are evaluated based on  the raw data returned from data source query, that is not after conversion/options. In the mockup below there's a really simple UX which basically would scan all rows and columns returned from data source query to apply conditional formatting.

One option to having conditional formatting inside the *Column style* tab would be to allow conditional formatting rules to be applied per columns basis under a specific tab. Basically like the mockup below but with additional logic to decide which columns the rules should be applied to. This solution have an advantage because it can support conditional formatting of rows based on a hidden/non-rendered column.

#### UX mockup/example to underline functionality needed/wanted

image

### Forward compatibility

Any changes needed to existing Singlestat and Table panel JSON models should be forward compatible, meaning that existing saved dashboards with Singlestat/Table panel having coloring/threshold enabled should be migrated/converted to the new solution when such a dashboard is rendered.

### PR DESCRIPTION
**Pull request by yesoreyeram**
**What this PR does / why we need it**:

Conditional formatting for singlestat.

image

image

**Which issue(s) this PR fixes**:

Fixes #11418

### CODE REVIEW

**Comment by yesoreyeram** [comment]
Hi @torkelo - Any thoughts on this PR ? Is it worth to proceed further or do you have different ideas for this?

**Comment by harsha217** [comment]
Hey guys! Appreciate you guys working to implement this feature request. Any update on this?

**Comment by yesoreyeram** [comment]
@harsha217  - I am busy with other stuff. WIll work on this after christmas holidays.

**Comment by DEvil0000** [comment]
is `null` value coloring considered now?

**Comment by torkelo** [comment]
Closing this, we have something similar coming with override rules (not exactly the same but close)

**Comment by MihaelBercic** [comment]
> Closing this, we have something similar coming with override rules (not exactly the same but close)

Do you have any resources regarding the thing you mentioned?

Thank you

**Pull request closed without merging**
