### PR TITLE
[v9.2.x] Prometheus: Provide label values match parameter API when supported prometheus instance is configured

### PR DESCRIPTION
**Pull request by grafanabot**
Backport 3cbbf706cf1685e572a607eda36d7658dc8c4f44 from #56510

### CODE REVIEW

**Comment by gtk-grafana** [comment]
Base PR doesn't backport nicely, converting to draft while I figure out if we can do this or not

**Comment by gguillotte-grafana** [comment]
#57551 reverted #56510

**Comment by marefr** [comment]
@gtk-grafana @gguillotte-grafana should this be closed then?

**Comment by gtk-grafana** [comment]
Yes, this functionality was merged in (https://github.com/grafana/grafana/pull/57563), https://github.com/grafana/grafana/pull/57564. Closing

**Comment by gtk-grafana** [comment]
@osg-grafana Why was this re-opened? This was already merged in https://github.com/grafana/grafana/pull/57563

**Pull request closed without merging**
