### PR TITLE
support region annotation

### LINKED ISSUE #10589: Add support for region annotations in datasources
Hello Grafana experts,

I am trying to use region/range annotations in grafana and hoping I can get that fed by a measurement table in influxDB. Currently only markers and single annotations are permitted.
If anyone has ideas that would help that would be much appreciated.

Thanks

-Achraf

### PR DESCRIPTION
**Pull request by mtanda**
Will fix https://github.com/grafana/grafana/issues/10589

### CODE REVIEW

**Comment by DanielGnzlzVll** [comment]
why closed?

**Comment by mtanda** [comment]
I misunderstood the implementation.
Grafana already support region annotation.

**Comment by DanielGnzlzVll** [comment]
grafana support it, but only for internal annotations, no for RDB or i wrong? this isnt in the documentation

**Comment by mtanda** [comment]
Yes, most of datasource doesn't support region annotation.

My PR doesn't intend to add region annotation support in RDB datasource.

MySQL datasource doesn't support it, you can try to add it, or sending feature request.
https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/mysql.md

**Comment by DanielGnzlzVll** [comment]
I think there are already enough related feature requests, and it does not seem to be such a appreciated feature, although it would be very good

**Pull request closed without merging**
