### PR TITLE
Add a new notifier : DingTalk

### PR DESCRIPTION
**Pull request by jiamliang**
Add a new notifier : DingTalk
DingTalk known as DingDing in China :
https://www.dingtalk.com/en/?spm=a3140.7858860.2231601.1.bBkEn7

We need Grafana send alert to DingDing(钉钉) .

### CODE REVIEW

**Comment by daniellee** [comment]
Run `gofmt -s -d ./pkg` to see what code is causing the go format error.

**Comment by jiamliang** [comment]
@daniellee 
I have modify the code, and no output after running   **gofmt -s -d ./pkg** 
```
[root@atlas-data grafana]# gofmt -s -d ./pkg
[root@atlas-data grafana]#
```
but,  tests failed all the same.

**Comment by daniellee** [comment]
One of the tests has a build error:

```
FAIL	github.com/grafana/grafana/pkg/services/alerting/notifiers [build failed]
```

**Comment by jiamliang** [comment]
@daniellee Thanks a lot.

**Comment by dikang123** [comment]
when will this feature release? @daniellee @jiamliang

**Comment by daniellee** [comment]
@dikang123 it will probably be included in the next release of Grafana, v4.4.0, in a few weeks time.

**Comment by firesh** [comment]
Excellent supporting DingTalk!

**Comment by lyonliquid** [comment]
Wonderful! I'm looking forward to this feature!

**Comment by daniellee** [comment]
This will be released in the 4.4.0 release. Thanks for the PR!

**Comment by daniellee** [comment]
Are there any instructions for using this notifier? Would it be possible to add a placeholder in the url field that shows what the url looks like? Here is an example from the Sensu notifier:

image

**Comment by lyonliquid** [comment]
https://open.dingtalk.com/
We visit this website to learn how to use dingtalk,but unfortunately there is only Chinese edition. @daniellee

**Comment by zhengheyi** [comment]
how  to use dingding   in  grafana ?

**Comment by jiamliang** [comment]
Yes, there is only Chinese edition.
https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.p2lr6t&treeId=257&articleId=105733&docType=1

In DingTalk PC Client:
1. Click "more" icon on left bottom of the panel
2. Click "Robot Manage" item in the pop menu, there will be a new panel call "Robot Manage"
3. in the  "Robot Manage" panel, select "customised: customised robot with Webhook" 
4. in the next new panel named "robot detail", click "Add" button.
5. in "Add Robot" panel, input a nickname for the robot and select a "message group" which the robot will join in. click "next".
6. there will be a Webhook URL in the panel, looks like this: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxx. copy this URL to the grafana Dingtalk setting page and then click "finish" bottom.

Dingtalk supports the following "message type": text, link and markdown. this plugin only supports sending "text" message.

**Comment by zhengheyi** [comment]
@jiamliang Thank you.

**Comment by daniellee** [comment]
@jiamliang thanks. Added those instructions to the docs: http://docs.grafana.org/alerting/notifications/#dingding-dingtalk

**Pull request merged**
