### PR TITLE
Export as CSV - Timezone Options

### PR DESCRIPTION
**Pull request by theangryangel**
- Addresses grafana/grafana#5059

Adds a modal that provide additional options for exporting as CSV to any timezone offset, including browser's timezone. Defaults to UTC to match current behaviour.

gif of changes in-action

### CODE REVIEW

**Comment by theangryangel** [comment]
The circleci errors seem to be npm. They do pass on my dev box at the moment. 

I don't know if you guys want me to make a small push to get circleci to re-do them later, or?

**Comment by bergquist** [comment]
@theangryangel I reran the CI build and there are still some sass lint errors from the time when you branched from master. Could you please rebase against master?

**Comment by theangryangel** [comment]
PR updated. Have switched to typescript for the controller. Not 100% sure if its completely right (first time I've touched TS). Let me know and I can update again if necessary.

**Comment by bergquist** [comment]
Ive been testing it and it looks good!

Only thing that I feel missing is the default value for timezone. The default value should be the timezone setting. You can find it by importing config from app/core/config at config.bootData.user.timezone. This PR will be merged once that is in place.

**Comment by theangryangel** [comment]
@bergquist the current default for export to CSV is to output in UTC. This PR defaults to the same to maintain compatibility.

I can make it default to config.bootData.user.timezone if you'd prefer, but that is a breaking change. Just wanted to check.

**Comment by bergquist** [comment]
@theangryangel Good point! But I think it makes more sense to user the user default setting.

**Comment by theangryangel** [comment]
No problem. I'll update the PR :)

**Comment by bergquist** [comment]
@theangryangel nice! I'm currently traveling so might take some time before I can merge it. But it will be merged! :)

**Comment by torkelo** [comment]
I would like to close this PR, without merging, think the simples way to fix https://github.com/grafana/grafana/issues/5059  is simply to use the user timezone setting (UTC or local).  No need to add a new modal for this

**Comment by theangryangel** [comment]
@torkelo the reason why I'd made it a modal was because I have the occasional need to export panels to CSV and not in my preferred timezone. Currently I'm fixing that with an external script, but I felt it was handy to be able to specify in grafana at export time.

I was also thinking it could be useful to add a separator option in the same modal *shrug*

Totally understand if you think it's still not worth while, and would prefer using the user preferred timezone. Would you still consider that a help-wanted for that change?

**Comment by ThiruKumar** [comment]
I am not able change the timezone for IST(GMT+5.30). 

but i am able to change to local timezone in settings and i am able to see it in graphs . but when i export it as csv i am not able to see the change of timezone. 

all (UTC,BROWSER TIME,DEFAULT) the times are in utc in exported csv. so is there any help that i could use?

**Comment by thiagolc3** [comment]
the graph display correctly local browser settings, but when i export to CSV, the time is UTC. Thanks for any

**Comment by thiagolc3** [comment]
help

**Comment by randomeleven** [comment]
I would love to be able to export in my timezone. The dashboards are basically useless in my usecase if they can't export CSV in my timezone.
How do I do that?

The issue seems to still be there: export always uses UTC time, even with latest Grafana v4.1.2

Any help?

**Comment by theangryangel** [comment]
@randomeleven I never altered or submitted a new PR for this feature after torkelo closed it. So yes it's still "broken".

My best advise is either to write a script to convert the timestamp into your preferred format - which is what I did when this was an issue for me. Or use this patch as the basis to meet torkelo's requirements, and submit a PR.

Right now it's still extremely unlikely that I'll do any further work on this PR myself, for several reasons.

**Comment by randomeleven** [comment]
@theangryangel alright, I will attempt to write a converter script then.
How can I use the script you wrote (I want to have the export button just spit out local time CSV with no options.)?
What do I have to familiarize myself with, to begin with? 
It would be ideal for me BTW to not go into the trouble of changing source code and building, for several reasons.
So is it possible to directly amend the Javascript code of my running grafana instance to accomplish the conversion?

**Comment by randomeleven** [comment]
@theangryangel
If I directly change .ts files in the source code, are the changes going to be immediately reflected? or I should compile them first? 
When is the compilation from .ts to .js taking place in Grafana?

**Pull request closed without merging**
