### PR TITLE
PublicDashboards: Typo in acknowledge checkboxes information

### PR DESCRIPTION
**Pull request by lovasoa**
This fixes a small typo.

### CODE REVIEW

**Review by juanicabanas — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by juanicabanas** [comment]
@lovasoa there's a lint issue. could you fix it?

**Comment by lovasoa** [comment]
I can't see where the problem is. I gave maintainers write access to this pr.

**Comment by juanicabanas** [comment]
@lovasoa sorry the delay and thanks for the contribution!

**Pull request merged**
