### PR TITLE
changed gicons height/width from em to pixels

### PR DESCRIPTION
**Pull request by Ijin08**

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure about this one, since icons mostly should follow font size I think em might be easier but not sure

**Comment by Ijin08** [comment]
I think it would get a more unified look if we had small, medium and big icons. Currently a lot of the icons gets special sizes instead of following the font of the text next to it. And the fonts calculated pixel size gets loads of decimals.

**Comment by torkelo** [comment]
Yes, your probably right

**Comment by torkelo** [comment]
Still draft mode? Did a quick test and could not find any issues at least. but a bit scary change :)

**Comment by torkelo** [comment]
Closing this, think icons should be sized default same way / relative to text size, so em makes sense I think

**Pull request closed without merging**
