### PR TITLE
CLI: Search perf test data

### PR DESCRIPTION
**Pull request by torkelo**
Adds new yarn cli command

```
yarn cli searchTestData -c 100
```

will create a 100 dashboards each with one team ACL entry (that has one user member). 

When adding 10000 dashboards and login with the searchTestUser1 user the search is unusably slow and in some cases grafana stops responding and I cannot do full page reload / login.

### CODE REVIEW

**Comment by bergquist** [comment]
Most developer related tools exist in`devenv`. How do we make this visible in devenv?

**Comment by torkelo** [comment]
Not sure, I definitely fits better there. But was conflicted with how to get it in there.

**Comment by torkelo** [comment]
So I am not working on this anymore but someone else can take over the investigation.

Turn on SQL logging:

```
log_queries = true
```

I can see that the GetSystemStats query taking 18 seconds with 10K dashboards

**Comment by aocenas** [comment]
Even though https://github.com/grafana/grafana/pull/17427 is merged I think we should merge this as I think it could be useful. I can take that over and do some changes:
- Move to devenv. I think we could use the same cli code and just add `cli:dev` to package that will go into devenv/cli
- Add optional params for user/password

**Comment by bergquist** [comment]
@aocenas sounds good!

**Comment by torkelo** [comment]
ok, merging this then and we can refine it in further PRs

**Pull request merged**
