### PR TITLE
Chore: Fix sqlite3 transaction retry condition operator precedence

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

Just noticed that transaction has a chance to stuck in an endless retry cycle with SQLite3 (maybe never happen on practice though).

See https://golang.org/ref/spec#Operator_precedence and https://play.golang.org/p/waKWtg_zt1C

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
Great catch! LGTM

**Review by aknuds1 — APPROVED** [review]
Nice one

**Comment by aknuds1** [comment]
Should we get this into 8 or 7.5?

**Comment by wbrowne** [comment]
Yeah no shame in having it sooner from my perspective @aknuds1

**Comment by aknuds1** [comment]
@FZambia shall we give it a milestone of 7.5.4 and flag it for backporting?

**Pull request merged**
