### PR TITLE
Plugins: Send PDC file paths and contents for backwards compatibility

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**

Ensures that Grafana is sending requests that will work on plugins created before and after SDK version https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.218.0.

**Why do we need this feature?**

To maximize compatibility of the PDC feature.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by summerwollin** [comment]
Does this affect on-prem? I've heard that we have some use cases of people using the secure socks proxy on on-prem. If that is true this needs to be backported to v11.0.x

**Comment by wbrowne** [comment]
> Does this affect on-prem? I've heard that we have some use cases of people using the secure socks proxy on on-prem. If that is true this needs to be backported to v11.0.x

Thanks for the heads up @summerwollin. Will open up a backport in that case

**Comment by wbrowne** [comment]
Backports:
- https://github.com/grafana/grafana/pull/85411
- https://github.com/grafana/grafana-enterprise/pull/6429

**Pull request merged**
