### PR TITLE
feat: adding a option to disable quotes as values in query (Datasourc…

### PR DESCRIPTION
**Pull request by vipin-pink**
This gives the possibility to disable quotes when needed for your template values (only applicable for PostgreSQL datasource for the time being)

Example : 
` select $columnName from myTable where column="value" `

`$columnName` gets wrapped with quotes " " i.e converted to string - this gives the possibility to use the original value as is. 

**Reason for having this feature :** 
- https://community.grafana.com/t/remove-single-quote-around-template-variable/4128
- https://github.com/grafana/grafana/issues/9030 

**Work Around being created:** 
- https://github.com/grafana/grafana/pull/9611 (this was reverted)

**Final Version after revert :**
- https://github.com/grafana/grafana/pull/9712
https://github.com/svenklemm/grafana/blob/master/public/app/plugins/datasource/postgres/datasource.ts#L16-L33 
(This gives the possibility to remove quotes only for single values)

## Pull request solution : 
disable-quotes-wrapped
- Adds the possibility to define when to disable quotes by adding a checkbox option - by default its disabled but if enabled it will remove the extra quotes being applied for both single and multi variable values - without breaking the current functionality. 

Please take my pull request with a pinch of salt if i have missed something as this is my first contribution to the community. 

CC: @daniellee  || @torkelo || @svenklemm 

Cheers,
V

### CODE REVIEW

**Comment by torkelo** [comment]
We are introducing new template variable interpolation syntax that allows for options to be passed to interpolation engine, think it’s better to use that method to control quotation

**Comment by vipin-pink** [comment]
Hi @torkelo 

Glad to know its already been taken care off.  

Are you able to explain how this syntax would work ?

Thanks,
V

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/11002

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/11002 is not about graphite it is about extending the template variable syntax

**Comment by vipin-pink** [comment]
OK - Although i see changes being made to graphite datasource as part of the pull request.
- https://github.com/grafana/grafana/pull/11002/files#diff-d7ae9ac800528ca8ff681d89ba6c42ae

**Comment by vipin-pink** [comment]
Are you able explain how the syntax works ? 

Is it applicable for postgres as well ?

Cheers,
V

**Comment by torkelo** [comment]
yes, so `${variable:raw}` or something would not quote it (but that raw option has to be added)

**Comment by daniellee** [comment]
@vipin-pink we don't want to introduce a new configuration option and the ${variable:raw} syntax would be a much better option. I'm closing this PR and have opened an issue describing this solution #11614

I included the issue in the 5.2 release so that someone on the core team might find time to work on it but it would be much appreciated if you have time to implement it.

**Comment by daniellee** [comment]
In the linked issue, @svenklemm pointed out that this it is already possible to use `${var:csv}` to get an unquoted comma-separated list. It is a new feature that was added a month ago.

**Pull request closed without merging**
