### PR TITLE
Grafana-UI: replace react-color with react-colorful

### PR DESCRIPTION
**Pull request by Elfo404**
**What this PR does / why we need it**:
Replace react-color with react-colorful and some minor UI fixes to the color picker:

Screenshot 2021-04-22 at 13 25 10
Screenshot 2021-04-22 at 13 25 19
Screenshot 2021-04-22 at 13 25 32

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks great!

**Comment by torkelo** [comment]
@Elfo404 please merge this asap these random frontend test errors due to react-color are so annoying :)

**Comment by Elfo404** [comment]
@torkelo i just need to add some throttling to onChange, I'll push it soon

**Comment by leeoniya** [comment]
bonus:

143.1 kB before:
https://bundlephobia.com/result?p=react-color@2.19.3

12.8 kB after:
https://bundlephobia.com/result?p=react-colorful@5.1.2

**Comment by Elfo404** [comment]
@leeoniya oh yep, forgot to mention that! 🚀

**Comment by omgovich** [comment]
Hi guys! I'm the author of react-colorful.
Just want to say thank you for choosing the library.
If you'll face any issues, I'm always glad to help!

**Comment by omgovich** [comment]
BTW: You can also migrate from **Tinycolor2** to my new library called **[Colord](https://github.com/omgovich/colord)**:
It's 3x faster and 3x lighter.

**Pull request merged**
