### PR TITLE
ReduceTransform: Include series with numeric string  names

### LINKED ISSUE #31580: Reduce Transform seems to skip decimal strings
**What happened**: When using the Reduce transform with series that have names that are numeric strings (i.e. strings composed of decimal digits like "1049") it seems they are not included in the transform output. Interestingly, if there is all series are named numerically, it seems to behave as expected. 

**What you expected to happen**: Ideally, these "decimal strings"  would be treated like any other string and transformed as expected.

**How to reproduce it (as minimally and precisely as possible)**: Create a table with 2 series, one with the name "a" and one with the name "1". Both should be available with data. Add a "Reduce" transform. Only "a" will be visible (See screenshot).

image

**Anything else we need to know?**:

**Environment**:
- Grafana version: Tested in `Grafana v7.3.4 (14c494085e)` and `Grafana v7.4.1 (07649d1313)`
- Data source type & version: Graphite (Metrictank)
- OS Grafana is installed on: Rhel7
- User OS & Browser: OSX & Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR makes sure that Reduce Transform includes any series names in the result, even if they're completely numeric. There is probably a more fundamental change that needs to be addressed but I opted to just solve the specific issue here.

**Which issue(s) this PR fixes**:
Fixes #31580

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Not sure I understand the fix, why was the series name with a numerical name skipped?

**Comment by hugohaggmark** [comment]
> Not sure I understand the fix, why was the series name with a numerical name skipped?

Sorry my bad, I should have explained this. This line checks for type and name diff:
https://github.com/grafana/grafana/blob/451fdd4cda30ac9ae6b3a3fc98514f4d48b77077/packages/grafana-data/src/transformations/transformers/reduce.ts#L154

I guess I could change the logic there instead if that makes more sense?

**Comment by torkelo** [comment]
Ah, yes think changing that is best, I really struggle to understand it :) 
> if (baseField.type !== field.type || baseField.name !== field.name) { 

What is baseField here and why are we ignoring fields with that type or name?

**Review by torkelo — APPROVED** [review]
Looks good

**Pull request merged**
