### PR TITLE
(cloudwatch) support interval template variable

### PR DESCRIPTION
**Pull request by mtanda**
Support interval template variable in CloudWatch data source plugin. (small enhancement)

### CODE REVIEW

**Comment by mtanda** [comment]
@bergquist This is very small enhancement. Would you check this?

**Comment by bergquist** [comment]
@mtanda this change should include a unit test. Should be fairly easy to add.

**Comment by mtanda** [comment]
Add test!

**Comment by mtanda** [comment]
@bergquist Would you check this PR?
The change is simple, it should not take too much time to review.

**Comment by mtanda** [comment]
Thanks!

**Pull request merged**
