### PR TITLE
NestedFolders: Add invalid state to NestedFolderPicker

### LINKED ISSUE #72091: NestedFolders: Add invalid state to NestedFolderPicker
Some consumers will need to show an error on the FolderPicker. The new NestedFolderPicker should show Field errors the same as regular inputs.

It should support the following markup:

```ts
<Field label="Folder" invalid error="Wowee an error!">
  <FolderPicker value={dashboard.meta.folderUid} onChange={onFolderChange} />
</Field>
```

To do this, we just need to add an `invalid` prop to NestedFolderPicker to render it with the red border. See grafana-ui's Input or Select for implementation inspiration ✨

### PR DESCRIPTION
**Pull request by karolstawowski**
**What is this feature?**

It adds invalid state to NestedFolderPicker.

**Why do we need this feature?**

[Nested folder picker #65745](https://github.com/grafana/grafana/issues/65745)

**Who is this feature for?**

[Nested folder picker #65745](https://github.com/grafana/grafana/issues/65745)

**Which issue(s) does this PR fix?**:

Fixes #72091

**Special notes for your reviewer:**

Hi! It is a pleasure to contribute to Grafana for the first time. I did not exactly know if it is all the work expected for this task, so please let me know if I have done something wrong or anything is missing.

Kind regards
Karol Stawowski

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by joshhunt** [comment]
Thanks for the contribution @karolstawowski! This is a great start.

It looks like we're missing the invalid (red border) styling on the Trigger component inside the nested folder picker. These two fields should have the same styling when they have error + invalid:

image

You should be able to pass the `invalid` prop into `Trigger`, `getStyles`, and `getInputStyles`. 

https://github.com/grafana/grafana/blob/88ca376f3f6b521a8b1a203d8cb0118d81891d3b/public/app/core/components/NestedFolderPicker/Trigger.tsx#L55-L56

Note that you may need to change how getStyles is called in Trigger to something like 

```ts
function Trigger({ isLoading, label, invalid }) { // etc
  const theme = useTheme2();
  const styles = getStyles(theme, invalid);
```

**Comment by joshhunt** [comment]
Also please be sure to merge/rebase from main after your changes - we've done a bunch of work in this area since this branch was created :)

**Comment by karolstawowski** [comment]
Thanks for a great and objective feedback @joshhunt! 

As you pointed out, I added missing code to display proper styling of the Trigger component. Now it should look similar to the Input component. I would like to ask if NestedFolderPicker should also take an `error` as a prop or should it be passed to the Field wrapping the NestedFolderPicker like it is done in case of Input component?

**Review by joshhunt — COMMENTED** [review]
Tested and it's looking good! Just remove the `sharedInputStyle` and this will be ready for merge!

**Comment by karolstawowski** [comment]
Done, just removed `sharedInputStyle` from `Trigger`!

**Review by joshhunt — APPROVED** [review]
Thanks for the contribution @karolstawowski. It looks great!

5687_2023-07-26-11-43_NVIDIA_Share

**Pull request merged**
