### PR TITLE
Chore: fix absolute public paths

### PR DESCRIPTION
**Pull request by AJDurant**
When serving Grafana from a subpath, some URLs still try to access the root for public files `server/public  `instead of `server/grafana/public`. These paths should be relative, like the others in the templates so that they don't 404.

### CODE REVIEW

**Comment by AJDurant** [comment]
fixed by #22413 apart from _buttons.scss updated conflicts

**Comment by AJDurant** [comment]
@sakjur ?

**Comment by sakjur** [comment]
@AJDurant Great find and thanks for the PR (apologies for not having seen it earlier)! There is a conflict that needs to be solved, can you merge master into your branch and fix the conflict? While doing that, we've introduced another problematic URL on the line listed below, could you fix that as well?

https://github.com/grafana/grafana/blob/305732478f82cbf4bd439df479883b2585a1a995/public/sass/components/_buttons.scss#L221

Ping me when that's done and I'll merge it 👍

**Comment by AJDurant** [comment]
Ah it looks like both these have changed in master now anyway: https://github.com/grafana/grafana/blob/master/public/sass/components/_buttons.scss#L210-L226

**Pull request closed without merging**
