### PR TITLE
Add a @grafana/runtime package with backendSrv interface

### LINKED ISSUE #16557: Expose services to react plugins
`@grafana/ui` exposes react UI elements to external developers.  It defines core types and UI components.  We need some way to use core grafana features, but keep a reasonable contract.

We could publish a `@grafana/runtime` or `@grafana/services` package that holds core interfaces, but only works if you are running in a grafana context/plugin etc

### PR DESCRIPTION
**Pull request by ryantxu**
fixes #16557

In looking for a solution to #15268, I tried moving a backendSrv interface to @grafana/ui, that isn't a great idea (see comments below)

This adds a new package `@grafana/runtime` and puts the backendSrv interface there.

I don't know if this is a good idea, but I'll post it rather than close it so the work may be used

### CODE REVIEW

**Comment by dprokop** [comment]
@ryantxu I'm not sure if backendSrv belongs go grafana/ui actually. AFAIR we briefly talked about that with Torkel some time age and considered having separate package for "runtime" code, but we haven't made any decisions on that yet.

I'm slightly afraid that this kind of ad hoc migrations to grafana/ui will make the library bloated with "random" stuff, making it hard to document(our POV) and making less accessible to the community. 

I would keep grafana/ui ui components focused only, while things like services I would migrate to another package basically.

**Comment by torkelo** [comment]
Argh, this is frustrating. I really want to unblock this and have a temporary solution so this not a blocker for you Ryan. And now I feel bad that I might have misspoken when I said: 

> Wish there was a way expose this via @grafana/ui

The main problem is that BackendSrv uses application state and so far we have been trying to keep @grafana/ui state less and only contain components and stateless data processing functions. 

The main problem with this is that backendSrv uses config (to access appSubUrl in order to logout). And  contextSrv in order to know if user signed in and user orgId. 

How to expose runtime application state & services with the new npm package approach for new plugins is not something we have figured out yet. 

So I almost prefer the last PR.

**Comment by ryantxu** [comment]
ha!   as noted, the easy path is #15268 :)  till you figure something better out.  many other things have the same issue

**Comment by ryantxu** [comment]
@dprokop -- here was my attempt at a public interface for backendSrv.  It looks like grafana core can no longer magicaly import from `@grafana/runtime`

**Comment by dprokop** [comment]
@ryantxu we talked about that with @torkelo last week and we agree about the need for @grafana/runtime. Let me review this PR ltr today and I suspect we will be able to merge it.

As we talked last week let's start with @grafana/runtime and down the road maybe introduce @grafana/data - this should happen organically as it happens now with @grafana/runtime

**Comment by ryantxu** [comment]
One thing I don't like about this approach is that the *setXXX* is a public API -- is there any way around that?

```

**Comment by ryantxu** [comment]
Thinking about this more... I wonder if the internal instance variables require trusting the system loaders too much --- maybe `getXxxLoader()` should really be:

```
return window.graganaRuntime.xxx
```

**Comment by dprokop** [comment]
>One thing I don't like about this approach is that the setXXX is a public API -- is there any way around that?

Actually I was thinking about @grafana/runtime as a container not only for the service interfaces, but also the implementations. If the implementations were there, then singleton instance creation could happen in `getXXX`. What's there that prevents us from moving service implementations into @grafana/runtime?

**Comment by ryantxu** [comment]
Most of the services get created via angular now, so it would be pretty complicated to keep that totally isolated

**Comment by dprokop** [comment]
@torkelo any additional thoughts on that? I feel like we can proceed with this approach.

Next step will be publishing this to NPM and adding some README with reasoning for this package

**Review by torkelo — APPROVED** [review]
Yes, we can proceed with this. Looks ok 👍

**Review by dprokop — APPROVED** [review]

**Pull request merged**
