### PR TITLE
Alerting hysteresis

### PR DESCRIPTION
**Pull request by sxmichael**
Solves https://github.com/grafana/grafana/issues/6202
With a little logical change, which in my opinion, simplifies the definition: instead of defining the condition to stop alerting, define condition to keep alerting. Referring to example from issue:

let's say i have an alert for latency, with a threshold at 1000ms.
if the number is fluctuating around 1000 (maybe 980->1010->990->1020-> etc), then each of those will trigger a change between critical and ok. constantly flapping.

* go to critical when it goes over 1000ms
* stay in alerting mode if it still more than 900ms.

Currently PR lacks some testing (WIP), but the implementation is ready I think.
Any suggestions/concerns/something I missed?

### CODE REVIEW

**Comment by torkelo** [comment]
have a separate class/type/array for conditions when in alerting state seems a bit heavy handed or inelegant. 

Maybe a toggle on the conditions would be simpler. Not sure about this. Needs a lot of UX / Design thought.

**Comment by torkelo** [comment]
Oh, sorry, forgot to mention that we are thankful for wanting to contribute and make Grafana better! alerting is an area where we welcome bigger more substantial contributions like this! And Alerting hysteresis is an important problem to solve. Just need to find a way to solve that does not add too much complexity to code & UX.

**Comment by sxmichael** [comment]
@torkelo thanks for the feedback. Totally understand your concerns. Do you have any idea of how it could be? The proposed implementation was pretty fast, and in my opinion also easy to implement/support/define:
from the implementation perspective - there was almost no changes (except for obvious storing/loading/validating). The only actual change on backend is: if PrevAlertState is Alerting then check ConditionsKeep conditions, regular Conditions otherwise. (in eval_handler.go)
If ConditionsKeep is empty, then regular Conditions are used instead (which preserves backward compatibility). This also works, if hysteresis functionality is not required. (in rule.go)
From the UI point of view I've added section of "Conditions to Keep Alerting State" which works exactly same way as regular Conditions section. Most of the times the conditions will be very same except for different thresholds, so I though about adding button of "Copy Conditions to Conditions to Keep Alerting State" and only adjusting the thresholds.

I'll be glad to hear your suggestion for other way of implementing this, maybe I'll be able implement this as well.

**Comment by sxmichael** [comment]
Hi @torkelo , just checking up on this...

**Comment by torkelo** [comment]
Not sure, this is really big change and needs a lot of thought, think there is a better way buy just a combination of regular conditions instead of a separate class of conditions

**Comment by sxmichael** [comment]
Hi @torkelo,

If I understood correctly you're thinking about single expression which will allow specifying both conditions? For example, Zabbix uses the following trigger condition scheme:
```
({TRIGGER.VALUE}=0 & {Oracle DB1:system.cpu.load.min(5m)} > 2)
|
({TRIGGER.VALUE}=1 & {Oracle DB1:system.cpu.load.min(10m)} > 0.5)
```
or in more general way:
```
(NotAlerting & <condition to start alerting>)
|
(IsAlerting & <condition to keep alerting>)
```

Am I right? If so, in my opinion it will be hard to impossible to achieve this without fully rewriting alerting logic. The main reason for this is that currently Grafana has no support for full bool expression trees including preceding control, and probably there won't be any, at least in short-medium time range. There was similar discussion when adding OR to the query syntax with @bergquist comment specifically on it: https://github.com/grafana/grafana/issues/6438#issuecomment-259696590
Not only backend logic, but the alerting UI also will require major change for this to continue support point-and-click alert definition, which i'm not sure if exists good implementation of this.
Another problem will be adding support for variables support (any variable or predefined grafana variables, like AlertingState) which will add more complexity to both alert logic and UI part, without too many use cases for it, except for AlertingState.

On the other hand, the proposed solution does not require any of those, is very easy to understand, implement and define for the user (as I mentioned, in 90% of the cases the KeepCondition will look exactly the same as simple Condition, except for the thresholds), introduces no breaking changes, and provides great functionality with minimal changeset - hysteresis is very important feature for any alerting system, as mentioned in https://github.com/grafana/grafana/issues/7886 - nobody wants to get "~60 Email+SMS alerts over a 4 hour period"

Honestly, I don't see full bool expressions + variables implemented without introducing breaking changes, so the hysteresis mechanism could be be migrated to new alerting way once it will happen.

Thanks for understanding,
Michael

**Comment by torkelo** [comment]
Not sure I agree with your evaluation of the possible solutions, think there is a simple way to extend the current conditions model to include alert state without breaking or adding much complexity. 

This solution double the UI for conditions and introduced a whole new class and group of conditions, new concepts to only solve a specific scenario of having  separate thresholds while in alerting state, feels inelegant. Just worried about introducing too many concepts for specific use cases, will create a very messy Alert UI. 

But you could be right, that adding this capability via normal thresholds could be tricky

**Comment by sxmichael** [comment]
@torkelo ok.. let me try to propose something that will look more coherent with current UI - we can add ConditionType (which is currently only Query) like QueryWhenAlerting or something, and it will add special condition of "When Alerting", and will allow to add new queries afterwards:

Hysteresis Preview

Is it looks better? If yes, I can try to think how it will look like on the backend.

**Comment by torkelo** [comment]
That is more in line with what I am thinking, as it builds on and uses current concepts

**Comment by sxmichael** [comment]
Ok, got you. Would you mind helping with how you think it should look like on the backend side? Here are the options I though about:
1. Leave it the way I already implemented: on the backend it still will be Condition and ConditionsKeep. Thus the change of proposal is only on the UI side
    Pros: 
    * easy to understand
    * two conditions are really separate, so no misunderstanding of how expression is parsed
    * very simple implementation (just IF before expression evaluation which decides which one should be used
    * evaluation performance will be good - only needed condition list is evaluated

    Cons:
    * introduces ConditionsKeep field for alert model
    * not generic - the implementation is specific to the use case

2. Add new Operator to QueryCondition (and others, like ConditionResult, etc), in addition to "and"/"or", for example: "whenAlerting"
    Pros:
    * reusing existing fields

    Cons:
    * not easy to understand - it's not really an operator
    * Need to change existing query evaluation, since you'd want to evaluate all conditions after this operator without all the data from previous conditions
    * Performance - if the results of all conditions before whenAlerting is not relevant, it makes sense to skip those, thus need to somehow find if wehnAlerting operator is in conditions, and if yes - start from its position, or if state is not alerting - stop when if see "whenAlerting" operator
    * Not so generic - how to add more similar conditions? Do you need to find "Start" and "End"  of  the condition sequence?

3. Add new field of AlertingState (or ConditionGroup to be more generic) to QueryCondition model, with values ("notAlerting", "whenAlerting"). And filter all conditions by this State (probaly with some pattern matching). Pseudocode:
    ```
   conditions = context.Rule.Conditions.Filter(cond.AlertingState == currentAlertingState)
   evalutate(conditions)
   ```

    Pros:
    * easier to understand than reusing Operator field

    Cons:
    * May create some confusion, since on UI side it's treated as single list, and being filtered on backend
    * Need to take care of default values (like if there is no "WhenAlerting" types, fallback to "NoAlerting")

4. Change Conditions from array to hash of arrays. Example: Conditions["NoAlerting"] = [], Conditions["WhenAlerting"] = []... It becomes very similar to bullet 1 (with having Conditions and CondtionsKeep) but more generic, and also similar to 3 since need to take care of default fallbacks, but only relevant condtions are evaluated.

What do you say? Any other way you could see?

**Comment by sxmichael** [comment]
@torkelo just checking on this. Sorry for being so pushy, we'd really want this feature, and I'd like to move forward with it's implementation.

**Comment by torkelo** [comment]
Sorry, this redesign requires a lot of thought. 

Maybe a whenRuleState condition, that contains a state to match against, and a condition list (so nested conditions). 

```
WHEN max() of query(A, 5m, now)  IS ABOVE 100
OR WHEN IN STATE = Alerting THEN
   WHEN max() of query(A, 5m, now) IS ABOVE 90
```

No idea how hard it will be to do nested conditions.

**Comment by vonox7** [comment]
@torkelo In my opinion hysteresis can be implemented with a simple hysteresis-percentage on the UI side:
Lets say I'm tracking a ping to a server and defined a threshold of 100ms. Therefore I want to get alerted as soon as this threshold is reached, so my values my look like 90 -> 95 -> 99 -> 97 -> 100.
But then, probably the next ping will be 99, followed by 104. Without hysteresis this would throw one OK and one alerting dialog. However, when a hysteresis of 5% is defined, the state transition from alerting to OK will be only triggered when the value reaches 95 again. 
The concept is called [Schmitt trigger](https://en.wikipedia.org/wiki/Schmitt_trigger) - just look at the chart ;)
It requires minimal effort on the UI side. You could go even one step further and define a global preselected value of 5% that applies for all alerts. So even without further hysteresis analysis, a user might just feel that "it works" without further noticing.

**Pull request closed without merging**
