### PR TITLE
Plugins: Fix loading of dist folders

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**

This PR rolls back some functionality introduced in https://github.com/grafana/grafana/pull/78042 and also fixes a bug where custom paths defined in plugin settings were not correctly following `dist` folders when they were previously.

The new change made involves treating external plugin sources as individual - this means that each directory under the [configured external plugins path](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#plugins) will be treated as a source, and therefore any top level folders named `dist` will still be treated like a normal plugin. Previously, the entire directory was a single source, which causes some issues with how plugin folders are walked.

**Why do we need this feature?**

This feature ensures that the correct plugin folders are followed during plugin loading across core, bundled, external and custom paths defined in plugin settings.

**Who is this feature for?**

Plugins Platform

**Special notes for your reviewer:**

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by xnyo — COMMENTED** [review]
Great work!! :clap: :clap: 

Leaving some minor comments, but looks good otherwise:

**Review by marefr — APPROVED** [review]
Nice LGTM. Seems to work as expected :tada: 

Nit. The existing logs of loading of plugin sources looks a bit odd now, especially the last one that tries to load some source and doesn't find any plugin. Not sure what the best solution would be, either remove these log messages or aggregate plugins per source before logging :shrug: Not a blocker though.  
```
DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=core                                
DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=core plugins="alertGroups, alertlist
, alertmanager, annolist, barchart, bargauge, candlestick, canvas, cloudwatch, dashboard, dashlist, datagrid, debug, elasticsea
rch, flamegraph, gauge, geomap, gettingstarted, grafana, grafana-azure-monitor-datasource, grafana-postgresql-datasource, grafa
na-pyroscope-datasource, grafana-testdata-datasource, graph, graphite, heatmap, histogram, influxdb, jaeger, live, logs, loki, 
mixed, mssql, mysql, news, nodeGraph, opentsdb, parca, piechart, prometheus, stackdriver, stat, state-timeline, status-history,
 table, table-old, tempo, text, timeseries, traces, trend, welcome, xychart, zipkin" duration=23.848433ms                      
DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=bundled                             
INFO [01-04|17:51:53] Plugin registered                        logger=plugins.registration pluginId=input                      
DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=bundled plugins=input duration=764.8
77µs                                                                                                                           
DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=external                            
DEBUG[01-04|17:51:53] Plugin has valid signature               logger=plugin.signature.validator id=agenty-flowcharting-panel  
INFO [01-04|17:51:53] Plugin registered                        logger=plugins.registration pluginId=agenty-flowcharting-panel  
DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=external plugins=agenty-flowcharting
-panel duration=144.995025ms                            
DEBUG[01-04|17:51:54] Loading plugin source...                 logger=plugin.loader source=external                            
DEBUG[01-04|17:51:54] Plugin source loaded                     logger=plugin.loader source=external plugins= duration=702.07µs
```

**Comment by wbrowne** [comment]
> Nice LGTM. Seems to work as expected 🎉
> 
> Nit. The existing logs of loading of plugin sources looks a bit odd now, especially the last one that tries to load some source and doesn't find any plugin. Not sure what the best solution would be, either remove these log messages or aggregate plugins per source before logging 🤷 Not a blocker though.
> 
> ```
> DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=core                                
> DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=core plugins="alertGroups, alertlist
> , alertmanager, annolist, barchart, bargauge, candlestick, canvas, cloudwatch, dashboard, dashlist, datagrid, debug, elasticsea
> rch, flamegraph, gauge, geomap, gettingstarted, grafana, grafana-azure-monitor-datasource, grafana-postgresql-datasource, grafa
> na-pyroscope-datasource, grafana-testdata-datasource, graph, graphite, heatmap, histogram, influxdb, jaeger, live, logs, loki, 
> mixed, mssql, mysql, news, nodeGraph, opentsdb, parca, piechart, prometheus, stackdriver, stat, state-timeline, status-history,
>  table, table-old, tempo, text, timeseries, traces, trend, welcome, xychart, zipkin" duration=23.848433ms                      
> DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=bundled                             
> INFO [01-04|17:51:53] Plugin registered                        logger=plugins.registration pluginId=input                      
> DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=bundled plugins=input duration=764.8
> 77µs                                                                                                                           
> DEBUG[01-04|17:51:53] Loading plugin source...                 logger=plugin.loader source=external                            
> DEBUG[01-04|17:51:53] Plugin has valid signature               logger=plugin.signature.validator id=agenty-flowcharting-panel  
> INFO [01-04|17:51:53] Plugin registered                        logger=plugins.registration pluginId=agenty-flowcharting-panel  
> DEBUG[01-04|17:51:53] Plugin source loaded                     logger=plugin.loader source=external plugins=agenty-flowcharting
> -panel duration=144.995025ms                            
> DEBUG[01-04|17:51:54] Loading plugin source...                 logger=plugin.loader source=external                            
> DEBUG[01-04|17:51:54] Plugin source loaded                     logger=plugin.loader source=external plugins= duration=702.07µs
> ```

I think that's actually because of the rendering service trying to load the renderer. We should probably add a `len` check in [here](https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/loader/loader.go#L78). Since it's not related, can do that in a follow up - WDYT?

**Review by xnyo — APPROVED** [review]
LGTM! Awesome! :rocket:

**Comment by marefr** [comment]
> I think that's actually because of the rendering service trying to load the renderer. We should probably add a `len` check in [here](https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/loader/loader.go#L78). Since it's not related, can do that in a follow up - WDYT?

- That make sense. After consideration we can probably keep it as it is for now. Remember now the use case of the logs was to understand what plugins are loaded and how long it takes to load each source.

**Pull request merged**
