### PR TITLE
Canvas: Limit connection vertex radius to numeric fields

### LINKED ISSUE #85019: Canvas: Limit connection vertex radius to numeric fields
See[ this comment](https://github.com/grafana/grafana/pull/84873#discussion_r1536013211) for context.

### PR DESCRIPTION
**Pull request by nmarrs**
Before

https://github.com/grafana/grafana/assets/22381771/c7e4d788-ce7f-45df-89b1-42fea9cc1844

After

https://github.com/grafana/grafana/assets/22381771/e9bdc5e0-2a9c-4295-8ff7-70ccc9b95200

Fixes https://github.com/grafana/grafana/issues/85019

### CODE REVIEW

**Review by codeincarnate — COMMENTED** [review]
The PR works with the field selection. However, I'm not seeing the field value applied to the radius thereafter 😿 

Screenshot 2024-04-01 at 12 43 55 PM

**Comment by nmarrs** [comment]
> The PR works with the field selection. However, I'm not seeing the field value applied to the radius thereafter 😿
> 
> Screenshot 2024-04-01 at 12 43 55 PM

Hmm @drew08t would you mind taking a look into this? 🤔

**Comment by nmarrs** [comment]
@codeincarnate I took a look into this and it seems like that is an existing bug that we will need to address (seeing the same result on both latest main and this PR's branch) - I've created this github issue (TBD) to address this as part of our bug bash

I think in meantime this PR should be good to merge as its addressing limiting the field selection to only numeric values :)

**Review by baldm0mma — APPROVED** [review]
> @codeincarnate I took a look into this and it seems like that is an existing bug that we will need to address (seeing the same result on both latest main and this PR's branch) - I've created [this github issue](https://github.com/grafana/grafana/issues/85679) to address this as part of our bug bash
> 
> I think in meantime this PR should be good to merge as its addressing limiting the field selection to only numeric values :)

Sounds good.

**Pull request merged**
