### PR TITLE
Add human readable timespan to the timepicker tooltip

### PR DESCRIPTION
**Pull request by ryantxu**
When you navigate the timeline, it can be difficult to quickly understand how much time you are looking at.

This adds readable info when the dates `isMoment`:
image
image
image

### CODE REVIEW

**Comment by torkelo** [comment]
Maybe when it's an absolute time range we only can show how long the range is?

**Comment by ryantxu** [comment]
What do you mean by an absolute time range?  When the times are not `isMoment` it assumes the text is legible.  For example, this does not need any extra info:
image

**Review by torkelo — CHANGES_REQUESTED** [review]
I mean when it's an absolute time range we do not need to show the absolute time range in the tooltip but only the duration.  

The code looks a bit too complicated, is there a way we can reuse the describe_interval from kbn.ts ?

**Comment by torkelo** [comment]
Closing this as the TimePicker component is now different (in React)

**Pull request closed without merging**
