### PR TITLE
@grafana/e2e: cherry picked 4fecf5a7a65f5b7b4c03fefb9a3da15cee938f02

### PR DESCRIPTION
**Pull request by stevenvachon**
See #22732.

### CODE REVIEW

**Comment by ryantxu** [comment]
Not sure the process here... need to be very careful and make sure @aknuds1 is in the driver seat...

**Comment by ryantxu** [comment]
@aknuds1 -- this would be GREAT to get in 6.7 beta... since the plugins could then use e2e it without canary.

What is the process?

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
@ryantxu I'm merging it.

**Pull request merged**
