### PR TITLE
Timeline: add spanNulls editor

### LINKED ISSUE #36616: Provide A "Connect Null Values" Option In State Timeline Visualization
**What would you like to be added**:

I would like to see an option added that allows for connecting null values as "Never, Always, Threshold" similar to how the Time series visualization works.

**Why is this needed**:

When dealing with event-based data sources like Grafana Loki, there can be gaps between states since there's potentially no "polling" being done by the collector to refresh a state within the $__interval Group By. In this example of viewing "Device On" or "Device Off" states - I want to connect each of the states rather than visible gaps (null values) between events.

**Nulls:**

nulls

**Connected:**

connected

Another example is where I'm mapping floats to integers for temperatures (one day we'll be able to round up floats to ints! :) )

_(Here I've had to do a 6h LogQL interval but it's not accurate)_

Loki Event Data - State Timeline

_(Here with a more normal $interval usage in LogQL)_

Loki Event Data - State Timeline (1m)

Would like to see this (all values connected mapped to values/colors):

connected_2

connected_3

Thanks!

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #36616

probably need to move the editor into the common panel config (under merge same values setting) but still have it apply to `field.config.custom.spanNulls`.

### CODE REVIEW

**Comment by ryantxu** [comment]
Works for numbers, but not strings?
image

**Review by ryantxu — APPROVED** [review]
This looks good -- but not sure how to resolve conflicts.

Can we target 8.1? (I thought this was already merged!)

**Comment by torkelo** [comment]
@leeoniya was there a reason this work got paused? can't remember now

**Comment by dmarks8427** [comment]
Following up on this issue to see if there was a reason it is still in progress

**Comment by leeoniya** [comment]
> Following up on this issue to see if there was a reason it is still in progress

yes, it's waiting on a re-factor of some internals.

this panel is built on top of GraphNG, which internally handles data alignment and null-spanning. this conflicts with additional features of this panel, such as converting raw values to mapped thresholds, then optionally merging same adjacent values. we need to do this in the proper order for it to work without issues, which requires pulling the data alignment step out of GraphNG, but GraphNG also supports numerous other panels that will have to be adjusted for this change.

we plan to work on this in the coming months.

**Comment by leeoniya** [comment]
closing in favor of https://github.com/grafana/grafana/pull/44811

**Pull request closed without merging**
