### PR TITLE
use clipboard.js

### LINKED ISSUE #7198: [Share Panel]: Flash required, switch to clipboard.js
Is the button made by flash?

### PR DESCRIPTION
**Pull request by mtanda**
Will fix https://github.com/grafana/grafana/issues/7198.

### CODE REVIEW

**Comment by torkelo** [comment]
this looks great! Is there any other place where zero clipboard is used? If not we should remove that dependency

**Comment by mtanda** [comment]
I grep the code and I can't find the place zero clipboard is used.
And, there is no dependency setting in package.json and bower.json.

I test this, and found strange behaviors.
If I set the breakpoint at the line, the copy action work.
https://github.com/zenorocha/clipboard.js/blob/v1.5.16/dist/clipboard.js#L243
But without the breakpoint, it doesn't work...

**Comment by mtanda** [comment]
And I'm not sure I should call `clipboard.destroy();` to prevent memory leak.

**Comment by mtanda** [comment]
Seems to this issue.

https://github.com/zenorocha/clipboard.js/issues/335
https://github.com/zenorocha/clipboard.js/issues/155

**Comment by mtanda** [comment]
By patching jQuery, clipboard.js work...

**Comment by utkarshcmu** [comment]
This is awesome, great work @mtanda!

**Comment by mtanda** [comment]
This PR is ready for review!!

**Comment by torkelo** [comment]
strange, it's not working on Chrome on linux (54.0.2840.100 (64-bit)) , it is working in firefox

**Comment by mtanda** [comment]
I may forget to disable browser cache when testing.
The monkey patch should be inserted before creating modal.

@torkelo It seems to work in Chrome/Firefox/Safari on Mac.
Please test again.

**Pull request merged**
