### PR TITLE
Trace View: Show number of child spans

### LINKED ISSUE #36862: Tracing: show number of child span in UI
**What would you like to be added**:
Show (at a glance) the amount of child spans a span has. This is useful information to understand how many operations a span created.

**Why is this needed**:
For instance, in Tempo we have an operation scanning our backend and this creates one span per request. Since we are scanning a lot of data it creates a ton of spans, multiple pages to scroll through.
It would help me to see at a glance how many requests this list contains.

Screenshot 2021-07-16 at 19 09 04

Screenshot 2021-07-16 at 19 10 18

I'm honestly not sure what the best place to show this is, maybe next to the ❗ sign in the collapsed view?

### PR DESCRIPTION
**Pull request by tharun208**
Signed-off-by: tharun <rajendrantharun@live.com>

**What this PR does / why we need it**: This PR introduces the total count of child spans for a span in view. Added the count in the expanded view of span detail page.
image

**Which issue(s) this PR fixes**: #36862

Fixes #36862

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by connorlindsey** [comment]
Thanks for opening this! This is a great first pass at the feature, but should also needs to account for:
- Formatting numbers to limit the # of digits/precision. Ex: 2,123 should be displayed as 2K in the sidebar
- Consistent vertical styling  - each span should display the same number of digits in the same column, and the border should line up when the detail view is expanded.

**Comment by tharun208** [comment]
@connorlindsey is there any util function available to do the formatting?

**Comment by connorlindsey** [comment]
Looking good, just a few more cases to test for. 
1) The detail border needs to stay aligned with the span bar border
Screen Shot 2022-01-25 at 10 29 29 AM

2) We need to test the scenario where spans at the same level in the tree have different numbers of span children and make sure they stay vertically aligned (if one span has 200 children and another below it has 3, the 3 should have extra spacing so they're aligned).

**Comment by tharun208** [comment]
> Looking good, just a few more cases to test for.
> 
> 1. The detail border needs to stay aligned with the span bar border
>    Screen Shot 2022-01-25 at 10 29 29 AM
> 2. We need to test the scenario where spans at the same level in the tree have different numbers of span children and make sure they stay vertically aligned (if one span has 200 children and another below it has 3, the 3 should have extra spacing so they're aligned).

sure, will test these

**Review by connorlindsey — APPROVED** [review]

**Pull request merged**
