### PR TITLE
OpenTSDB: consistent options for http requests

### PR DESCRIPTION
**Pull request by drewfarris**
The OpenTSDB datasource.js applies withCredentials / basicAuth to HTTP requests made from the performTimeSeriesQuery function, but not to requests made from the_get function that's used for suggest, search, aggregator and filter api calls. 

This patch adds those options to HTTP requests made from the _get function

### CODE REVIEW

**Comment by torkelo** [comment]
could you refactor this slightly so performTimeSeriesQuery also uses _get, less code duplication that way

**Comment by drewfarris** [comment]
Hi @torkelo - `performTimeSeriesQuery` does a `POST` and the structure of the method calls gets pretty nasty if `_get` is refactored to something like `_httpRequest` to support both http request methods. For example, in the `GET` case we're setting `params` into the `options` object, in the `POST` case we're setting `requestBody` in options - each of these need to be handled as separate parameters into `_httpRequest` never used in conjunction with each other. 

Perhaps is is better to add a _addCredentialOptions function? This will add the appropriate credential/auth values to the `options` object and can be re-used from both the `performTimeSeries` method and `_get` method to eliminate duplication.

**Comment by drewfarris** [comment]
Does the approach in a3f8198 appear to be a valid alternative? If not, I'll work through the originally suggested approach.

**Comment by drewfarris** [comment]
Any update? Does this look good or do I need to update?

**Pull request merged**
