### PR TITLE
Themes: Re-init graph on theme change

### PR DESCRIPTION
**Pull request by torkelo**
Fixes issue with time series not picking up theme change right away without a full page reload

### CODE REVIEW

**Comment by zoltanbedi** [comment]
@torkelo I wasn't able to reproduce this on play by using `t t` and on main `t t` shortcut doesn't work anymore and the only way to change the theme is going to preferences and changing there but then the page reloads so it shouldn't be a problem. Am I missing something?

**Comment by torkelo** [comment]
@zoltanbedi the keyboard shortcut has changed to `c t`

**Comment by torkelo** [comment]
@zoltanbedi and I am working on a theme related hackathon, adding more themes and need dynamic switching  :)

**Review by zoltanbedi — APPROVED** [review]
I can see it now. It was also not good in play. I think this should be fine but pinging @leeoniya just to let him know.

**Pull request merged**
