### PR TITLE
Stackdriver: Add possibility to authenticate using GCE metadata server

### PR DESCRIPTION
**Pull request by sunker**
Issue: #13669
Previous PR from @mtanda: #13486

When running Grafana on a GCE VM, it should be possible to authenticate using the default account that is setup for the VM. In order for this to be possible, the service account must have been given  read access to the scope `Stackdriver Monitoring API`. This has the advantage of not needing to generate a private key file for the service account and also not having to upload the key. 

This way of authenticating should also be supported when using provisioning. 

More on Service Accounts  [here](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances)

This closes #13486.

### CODE REVIEW

**Comment by sunker** [comment]
@mtanda I still need to write some documentation before this is ready for merging, but please review the code and that the authentication works for you.

**Comment by mtanda** [comment]
@sunker I'll check it tomorrow. Thank you for your work :-)

**Comment by mtanda** [comment]
I can't build docker image for this PR. `go run build.go build` is success.
```
❯ make build-docker-dev
Info: the frontend code is expected to be built already.
go run build.go -goos linux -pkg-arch amd64  build package-only latest
Version: 5.4.0-pre1, Linux Version: 5.4.0, Package Iteration: 1539798238pre1
rm -r ./bin/linux-amd64/grafana-server
rm -r ./bin/linux-amd64/grafana-server.md5
go version
go version go1.11.1 darwin/amd64
Targeting linux/amd64
go build -ldflags -w -X main.version=5.4.0-pre1 -X main.commit=fdcfe51bc -X main.buildstamp=1539708820 -o ./bin/linux-amd64/grafana-server ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/services/sqlstore/migrator
pkg/services/sqlstore/migrator/sqlite_dialect.go:88:27: undefined: sqlite3.Error
pkg/services/sqlstore/migrator/sqlite_dialect.go:89:32: undefined: sqlite3.ErrConstraintUnique
exit status 2
exit status 1
make: *** [build-docker-dev] Error 1
```
Do you know how to fix this.
I use Mac and build Linux image.

**Comment by sunker** [comment]
@mtanda `make build-docker-dev` will only work if you're on a amd64. 

If you're on mac you could use
```
cd grafana
make build-docker-full
```

or 

```git clone https://github.com/grafana/grafana
cd grafana
docker build -t grafana:dev .
docker run -d --name=grafana -p 3000:3000 grafana:dev```

**Comment by mtanda** [comment]
@sunker Thanks info, finally I success docker image and push it to gcr.

I test Stackdriver datasource, and success to display graph.

image

Thanks lot for your work!!

**Comment by sunker** [comment]
resolves #13669

**Review by daniellee — APPROVED** [review]
We maybe can move the gce code out of ds_auth_provider.go in the future if we can move all the frontend queries to the backend. Otherwise LGTM.

**Pull request merged**
