### PR TITLE
TSDB: show influxdb error message

### LINKED ISSUE #21647: Show influxdb error messages from HTTP 200 responses
**What would you like to be added**:

InfluxDB api has some cases where the query call returns HTTP 200 without series, but it includes error messages in the results blocks.
These error messages should be shown as warning/error in the Grafana GUI.

E.g. due to query execution restrictions you can get the following results:
- Query timeout:  
```
{"results":[{"statement_id":0,"error":"query-timeout limit exceeded"}]}
```

- No result due to abort on query limits: e.g.   
```
{"results":[{"statement_id":0,"error":"max-select-buckets limit exceeded: (1081/200)"}]}
```

**Why is this needed**:

On these results the user needs to know, why the data is missing.
Currently this can only be seen in the query inspector via the response object.

Currently only errors with HTTP 400 from Influx are shown in the Grafana Gui.
Here the response message looks different. e.g. 
```
{"error":"error parsing query: found wh, expected ; at line 1, char 59"}
```
But HTTP 400 is only returned on syntax errors.

### PR DESCRIPTION
**Pull request by zhulongcheng**
**Which issue(s) this PR fixes**:

Fixes #21647

### CODE REVIEW

**Comment by bergquist** [comment]
Looks good. Could you please add a test for this?

**Comment by zhulongcheng** [comment]
Sure.

**Comment by Estrax** [comment]
Does this one need any corresponding changes on the frontend side to display influx errors on 200 properly?

**Comment by bergquist** [comment]
@Estrax maybe. Influx have two implementations. One backend (only for alerting) and one for frontend used by dashboards. This will only make sure the backend handles the error correctly. Researching how frontend handles this would be a good idea.

**Review by bergquist — APPROVED** [review]
LGTM

Merging this even if it just affects the backend since its helpful when debugging alerting queries. 

Thank you for contributing!

**Pull request merged**
