### PR TITLE
Plugins: Migrate plugin instrumentation to middleware

### PR DESCRIPTION
**Pull request by wbrowne**
This should be functionally identical to how we instrument backend plugin requests currently. This change is beneficial as it allows more flexibility in making use of different instrumentation logic depending on the middleware chain. It also helps clean up the existing plugin client service.

There are some other small renaming changes as it makes things a bit clearer when writing tests . Also I have removed a JSON field from a test resource endpoint in the `testdata` plugin - this is because the `backend.PluginContext` it receives has `JSONData` set to `json.RawMessage{}` which throws the following error:
```
error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input
```

Rather than change core functionality, I think it makes more sense to just remove this field. It's considered bad practice to log the entire plugin context anyway

### CODE REVIEW

**Comment by bergquist** [comment]
I have a small change to the datasource logger that I would like to merge first since I want to backport it :) Give me a sec!

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/pull/61279

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by wbrowne** [comment]
Putting a pause on this for the time being

**Pull request closed without merging**
