### PR TITLE
Devenv: Create admin user for influxdb

### PR DESCRIPTION
**Pull request by jsoref**
**What this PR does / why we need it**:
I tried to use `make devenv sources=influxdb`, per [Developer guide: Add data sources](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#add-data-sources), but I get:
```shell
$ curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
HTTP/1.1 403 Forbidden
Content-Type: application/json
Request-Id: c9d05e29-c172-11ea-a46c-0242ac130002
X-Influxdb-Build: OSS
X-Influxdb-Error: error authorizing query: create admin user first or disable authentication
X-Influxdb-Version: 1.7.6
X-Request-Id: c9d05e29-c172-11ea-a46c-0242ac130002
Date: Wed, 08 Jul 2020 23:28:54 GMT
Content-Length: 87

{"error":"error authorizing query: create admin user first or disable authentication"}
```

There are two ways to fix this:

* [disable auth](https://github.com/jsoref/grafana/tree/influxdb-noauth)
* [set password](https://github.com/jsoref/grafana/tree/influxdb-with-password)

Based on, https://github.com/grafana/fake-data-gen/blob/ad9f6f10ded8b5b3cf91f326bde00d20912badf6/src/influx_data.js#L14-L15, I'm pretty sure it should be setting a password.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by papagian** [comment]
Thank you for contributing!

I'm not sure however if this is required; I can still query the API by passing the user credentials:
`curl -G http://localhost:8086/query -u grafana:grafana --data-urlencode "q=SHOW DATABASES"`

**Comment by aknuds1** [comment]
I'm not so familiar with InfluxDB yet, but I have the same impression as @papagian, that one should use the credentials already configured for this data source.

**Review by aknuds1 — COMMENTED** [review]
I'm not so familiar with InfluxDB yet, but I have the same impression as @papagian, that one should use the credentials already configured for this data source.

I could execute your query with the grafana:grafana credentials: 

```
$ curl -ugrafana:grafana -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: 4f0c088b-c5e4-11ea-811c-0242ac120002
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.6
X-Request-Id: 4f0c088b-c5e4-11ea-811c-0242ac120002
Date: Tue, 14 Jul 2020 15:11:35 GMT
Transfer-Encoding: chunked

{"results":[{"statement_id":0}]}
```

Does that solve your problem?

**Comment by jsoref** [comment]
I'll look next week.

**Comment by jsoref** [comment]
Seems ok. I can't find the thing which led me to expect a different outcome.

**Pull request closed without merging**
