### PR TITLE
Add metricFindQuery in KairosDB Datasource Plugin

### PR DESCRIPTION
**Pull request by masaori335**
metricfindquery_with_kairosdbplugin

### CODE REVIEW

**Comment by torkelo** [comment]
is there a way for this to also show tags or tag values? 
like: 

`metrics(kariosdb)` -> return metrics
`tags()` -> tags 
`tags_values(host)` -> tag values

**Comment by masaori335** [comment]
yes, when we call [Query Metric Tags](http://kairosdb.github.io/kairosdocs/restapi/QueryMetricTags.html) API of KairosDB like [KairosDBDatasource.prototype.performTagSuggestQuery](https://github.com/grafana/grafana/blob/kariosdb/public/app/plugins/datasource/kairosdb/datasource.js#L94).
but we need some flags to switch metrics and tags.

**Comment by masaori335** [comment]
do you mean set those functions (`metrics(kariosdb)`, `tags()`, `tags_values(host)`) in `Variable values query` ?

**Comment by torkelo** [comment]
yes

**Comment by masaori335** [comment]
ok, i'll fix this Pull-Request to support tags.

**Comment by masaori335** [comment]
Add tag support. We can use functions below in `Variable values query` now.
- `metrics()` : return metrics
- `tag_names()` : return tag names
- `tag_values()` : return tag values

**Comment by masaori335** [comment]
I'm not sure that arguments of `tag_names()` should be part of tag_names or metrics name.

**Comment by torkelo** [comment]
tag_names might be bad name, maybe just `tags()`

**Comment by masaori335** [comment]
The reason why I named the function `tag_names()` is that function returns list of tag names by calling [List Tag Names](http://kairosdb.github.io/kairosdocs/restapi/ListTagNames.html) API.
But if you think `tags()` is better, I'll rename it `tags()`.

**Pull request merged**
