### PR TITLE
WIP: Feature/Stackdriver: GCP Project selector proposal

### LINKED ISSUE #14764: Stackdriver: Add possibility to switch project in the query editor
As of now, when authenticating Stackdriver using a Google JWT file,  it's only possible to query stackdriver data using the default project id that was provided in the jwt file. However it's possible for the service account in the jwt file to be granted access to more project than the default account. Therefore a nice feature would be to provide possibility for the user to switch between all the projects within the query editor. 

The list of projects available for the service account should be retrieved from the [resource manager](https://cloud.google.com/resource-manager/reference/rest/v1/projects/list) api. It is possible that the service account needs to have the scope `cloudplatformprojects.readonly` for this to work. Default project (used when opening the query editor for the first time) should be the default project, the way it works today).

Project should also be a template variable.

### PR DESCRIPTION
**Pull request by NaurisSadovskis**
**What this PR does / why we need it**: This PR follows a discussion (#17353) and strives to address existing FR (#14764)

**Which issue(s) this PR fixes**:
Fixes #14764

**Special notes for your reviewer**:
This PR aims to change the handling of `defaultProject` within the plugin. Existing implementation gets and checks project ID from the existing credentials when making any request to Stackdriver. I believe a better way is to allow the user to set it ([since not always it can be fetched from credentials](https://github.com/grafana/grafana/issues/17353#issuecomment-496969630)). Once implemented all `getDefaultProject` logic can be removed and the user will be able to select any project from the UI with a single set of credentials. 

#### 1. Valid project ID
Screen Shot 2019-05-30 at 08 20 00

**Note**: This could be renamed to Google Default Credentials as that is more accurate. 

#### 2. Invalid Project ID
Screen Shot 2019-05-30 at 08 20 11

### Query Editor
Screen Shot 2019-05-30 at 08 20 53

proj

I'd like to get some feedback and help on how to best proceed from here. Would be really great to have this feature implemented and I'm willing to spend time to get it right. 

cc: @sunker @marefr @daniellee

### CODE REVIEW

**Comment by marefr** [comment]
Have assigned @daniellee to have a look at this. But you have a few failing tests in frontend and backend plus go linting issues that you maybe can have a look at for starters. See https://github.com/grafana/grafana/pull/17366/checks?check_run_id=138493116

**Comment by NaurisSadovskis** [comment]
@marefr thanks, I've fixed most of the test except FE test that relates to frontend changes I made. I'm not sure if the front end changes I made actually are idiomatic, so perhaps we can leave this for later.

**Comment by marefr** [comment]
There's a snapshot failing in FE test. You can run `yarn jest` and then jest should tell you that you have an outdated snapshot and allow you to update it (usually using `u` key).

**Comment by NaurisSadovskis** [comment]
@marefr : Thank you! Made changes and it's finally green :)

**Comment by marefr** [comment]
@NaurisSadovskis sorry that it's taking us long time to give you a proper review. This looks like a great first step, but I don't have all the stackdriver context so I may be missing some things. I'll make sure that someone take a closer look at this during the week.

**Comment by NaurisSadovskis** [comment]
@marefr no problem! I'm on hand to help with anything Stackdriver/Resource Manager-related.

**Comment by NaurisSadovskis** [comment]
@marefr , @daniellee - do you think this is worth keeping open for further discussions on how this can be best implemented? I'm happy to work separately and understand TypeScript, so the feature can be fully implemented and need to be only reviewed.

Let me know what you think.

**Comment by kustodian** [comment]
Any updates about this PR when will it get merged?

**Comment by sunker** [comment]
@NaurisSadovskis, I'll take a look at this as soon as I get the time. Hopefully next week. Sorry it's been taking so much time.

**Comment by kustodian** [comment]
@sunker sorry for nagging, but did you have any time last week to check this one out.

If it means anything, I would like to add that I when I created StackDriver sources for each project individually, did the following:
- created one service account
- gave it the monitoring viewer role (can't remember the exact role name) on all projects
- generated the json credentials for it
- when importing the credentials into Grafana I just used the same json file for all projects, I just changed the name of the project in the json file, and all this worked.

This means that same credentials file can be used for multiple projects, just the Grafana interface needs to support selecting a project. I guess you know all this, but it can't hurt to mention it.

**Comment by sunker** [comment]
No I did not know that @kustodian, thanks for the info. 
Unfortunately I did not have the time to look into this last, so I'm afraid this won't make it to 6.5.

**Comment by sunker** [comment]
@NaurisSadovskis, in your branch there's some 350 files changed, but I think there's only a few file that were changed intentionally. Can you look into that? While at it, could you also rebase from master and push the branch to a public repo so that I can test it, please.

**Comment by NaurisSadovskis** [comment]
Hi @sunker, I've deleted my fork, so I'm not able to push any more changes to this branch. I'll see if I have time to push to create a new PR only with the changes required. Sorry about that.

**Comment by Eraac** [comment]
I've recover the changes made here, create new branch (on my fork) without the mess https://github.com/Eraac/grafana/tree/stackdriver-project-selector

`vendor/` was change too but I haven't push it (`go mod vendor` should be good)

AFAIK what's missing to be finish 
* onChange function must be define
* projectId must be send to the backend
* backend must use projectId provided in the query, instead of using defaultProject

@NaurisSadovskis or anyone else feel free to use it

This feature will be **very** useful 🙏

**Comment by aknuds1** [comment]
@Eraac Would you mind creating a new PR from your branch please? Then we can continue the discussion there.

**Comment by aknuds1** [comment]
Closing this PR for now since the originating fork is deleted. Hopefully @Eraac will provide a new one.

**Pull request closed without merging**
