### PR TITLE
CI: Upgrade Go and Node versions in CI build image

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Upgrade our CI build image to use latest Go, which has some security fixes, and latest Node v12.

### CODE REVIEW

**Comment by sakjur** [comment]
These should probably be updated (or deleted, in case we're not using these files for anything anymore?)

https://github.com/grafana/grafana/blob/3f317e48e1031b93836b7c25a996eb4b69e4640f/Dockerfile.ubuntu#L19

https://github.com/grafana/grafana/blob/3f317e48e1031b93836b7c25a996eb4b69e4640f/Dockerfile#L19

**Comment by aknuds1** [comment]
@sakjur I already have an upgrade underway for grafana/Dockerfile, forgot about grafana/Dockerfile.ubuntu :/

**Comment by papagian** [comment]
also this should probably be updated:

https://github.com/grafana/grafana/blob/3f317e48e1031b93836b7c25a996eb4b69e4640f/Dockerfile.ubuntu#L1

**Comment by aknuds1** [comment]
@sakjur @papagian Please have another look.

**Review by papagian — APPROVED** [review]
LGTM

**Pull request merged**
