### PR TITLE
Improve err message for notifications

### PR DESCRIPTION
**Pull request by Alykoff**
**What this PR does / why we need it**: 
Improve error message in grafana log.
Without that PR a log file doesn't contain information where is a problem in dashboard json file:
```
t=2019-08-28T00:02:56+0000 lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=Prometheus error="Alert validation error: Neither id nor uid is specified, type assertion to string failed PanelId: 2 DashboardId: 1"
``` 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
This looks good. Anything else you want to change before marking this as Ready for review?

**Comment by Alykoff** [comment]
Hi, @marefr,
No, nothing to change.

**Comment by marefr** [comment]
@Alykoff okay thanks. You opened the PR as a work in progress and need to push the button "Ready for review", but I could do that for you.

**Comment by Alykoff** [comment]
@marefr thanks

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
