### PR TITLE
Add scale toggle to Singlestat panel

### PR DESCRIPTION
**Pull request by cinaglia**
This PR is an attempt to address the issue reported in https://github.com/grafana/grafana/issues/13800.

I'm not totally sold on the "Zero Scale" nomenclature. I considered "Auto Scale" as well but wasn't too sure. Open to feedback on the naming and also a what sensible default should be — I went with the behavior prior to https://github.com/grafana/grafana/pull/12010 but can definitely update.

Just a note that if approved, we'll need a new PR in [grafana.org](https://github.com/grafana/grafana.org) to add a new revision of the [singlestat-spark-options](singlestat-spark-options) screenshot.

### CODE REVIEW

**Comment by DanCech** [comment]
Looks great! We'll need some feedback from @torkelo on whether the change in #12010 should be considered a regression or not and therefore what the default should be.

**Comment by torkelo** [comment]
I think if we are going to add an option for Y axis scale it might just be worth adding a Min & Max option instead of this toggle. (leaving min blank will be same as zero = false). 

As to what should be the default, not sure. Maybe relative to zero is the best & most intuitive default?

**Comment by torkelo** [comment]
Closing this for lack of update. T

**Comment by pitr** [comment]
implemented in #17527

**Pull request closed without merging**
