### PR TITLE
Explore: Use new table component in explore

### PR DESCRIPTION
**Pull request by torkelo**
The new table component we are building (in @grafana/ui) uses new version of react-table that is complete rewire with different api compared to the old 6.x version used in Explore table. 

So in order to use the new table component we need to also update explore table component to use this new one. 

* [x] Change explore state to use DataFrame for tableResult
* [x] Handle merging many DataFrame's to one (join on time)
* [ ] The old table does not seem to care about available, think we need to change that so the height is adapted to available height. 
* [x] Figure out a way to support the cell click add filter action in the new table component. 
* [ ] It would be nice to support the table result for non-Prometheus data sources. Currently, we have to filter out time series and not show those in table. Think we can return an extra meta attribute for prometheus results that hides time series in the table. But this we can do later in a seperate PR.

### CODE REVIEW

**Comment by dprokop** [comment]
@davkal I see Explore's table is using pagination. We thought about new table as infinite scroll only - is pagination a thing that is a design constraint for Explore?


>Figure out a way to support the filtering action in the new table component.

@torkelo what do we need this for? Can't see any filtering in the Explore now

**Comment by torkelo** [comment]
> Figure out a way to support the filtering action in the new table component.
> @torkelo what do we need this for? Can't see any filtering in the Explore now

@dprokop this is the main feature in the explore table (you click on cell text to filter by that label). Same with angular table panel in dashboard with a datasource like Elastic: Hover over column cells in this dashboard: https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1

For the new table, thinking this will likely be done with a form of datalink. It's a bit tricky, linked to the current filterable property on FieldConfig

**Comment by torkelo** [comment]
I do not think pagination for the Explore table is needed, think windowed scroll will be better.

**Comment by dprokop** [comment]
> this is the main feature in the explore table (you click on cell text to filter by that label). Same with angular table panel in dashboard with a datasource like Elastic: Hover over column cells in this dashboard: https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1

all right, this I know.  I was thinking about filtering the table itself, like with an input in the header.

**Comment by torkelo** [comment]
Opened separate PR that implements a DataFrame join process

**Comment by davkal** [comment]
@torkelo there can be some long table results on prom queries like `{cluster="foo"}` that literally return all timeseries (easily 100K-1M) results for the table. Currently queries like this make the browser freeze (so I'd like to put a hard limit in the DS anyway), but the table should probably also enforce its own limits to keep render perf up. 

The graph component already does this:
Screenshot 2019-12-16 at 12 07 59
Then the user can click "Show all" at their own peril.

**Comment by torkelo** [comment]
The new table will use windowing (only render visible results), so it should handle it, but will need some pref testing to verify

**Pull request merged**
