### PR TITLE
PageNotFound: G10 Redesign

### PR DESCRIPTION
**Pull request by torkelo**
Just an early draft to get the conversation & design process going 

* [x] Align on a general design and default text 

Screenshot from 2023-04-27 14-52-10

Screenshot from 2023-04-27 14-53-15

Screenshot from 2023-04-27 14-54-28

### CODE REVIEW

**Comment by torkelo** [comment]
Did some refactoring to separate the inner component and made it reusable so that the Dashboard 404 can be more specific 

image

image

**Comment by amy-super** [comment]
Some thoughts on these questions:

> Should part of this page be a component in grafana/ui so plugins can also define 404 pages?

I like this idea so that we keep the experience consistent across plugins and Grafana core. Anything we can do to provide continuity goes a long way toward a unified experience.

> Should we have a version of this with section nav and inside page body? An app will also have 404 pages.

I would like to see this as it gives people more navigation choices than just using breadcrumbs or going back to start with the megamenu. I think we could do something similar to what is already up, but maybe just centering it in the page container.

**Comment by torkelo** [comment]
@amy-super image the grot image a bit smaller. See main description.

**Review by amy-super — APPROVED** [review]
I'm so excited about this - I really like how it's turned out.

**Pull request merged**
