### PR TITLE
CloudWatch: fix label handling

### PR DESCRIPTION
**Pull request by mtanda**
will fix the issue commented in https://github.com/grafana/grafana/pull/11624#issuecomment-478884988

### CODE REVIEW

**Comment by mtanda** [comment]
Metric Math query will return multiple time series, each time series has a unique label.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html

I misunderstand this point, I assume that the math query will return single time series.
To fix this, backend code check label and return multiple time series for those labels.
https://github.com/grafana/grafana/pull/16383/files?w=1

And, I fix SEARCH expression handling too in this PR.
https://docs.aws.amazon.com/ja_jp/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html

**Comment by torkelo** [comment]
I hate to ask this because you do so much to support the cloudwatch data source. But some unit tests for the executeGetMetricDataQuery would be nice. Maybe some refactoring, breaking it out into a separate file and smaller functions. That functions 336 lines long with a lot of nesting and uncommented code.

**Comment by mtanda** [comment]
should be better than before.

**Comment by mtanda** [comment]
@torkelo I add test and do refactoring. Would you check?

**Comment by torkelo** [comment]
Great job @mtanda !

**Comment by mtanda** [comment]
Thanks!

**Comment by erothmayer** [comment]
Awesome, thank you @mtanda ! Can't wait for this to land in release.

**Comment by erothmayer** [comment]
Hi @torkelo , do you have an estimate as to when this will make it into a release? This is a big blocker for a number of use cases against CloudWatch. Thanks!

**Comment by torkelo** [comment]
6.2 beta release is scheduled in 1-2 weeks , stable 1 week after

**Pull request merged**
