### PR TITLE
Docs: Add fixed role UUIDs to docs for terraform provisioning 

### PR DESCRIPTION
**Pull request by Jguer**
**What is this feature?**

Add role UUID to docs for use with provisioning. 

Fixes https://github.com/grafana/identity-access-team/issues/489

Generated using

```go
package main

import (
	"bufio"
	"crypto/sha1"
	"encoding/base64"
	"fmt"
	"os"
	"strings"
)

// PrefixedRoleUID generates a uid from name with the same prefix.
// Generated uid is 28 bytes + length of prefix: <prefix>_base64(sha1(roleName))
func PrefixedRoleUID(roleName string) string {
	prefix := strings.Split(roleName, ":")[0] + "_"

	// #nosec G505 Used only for generating a 160 bit hash, it's not used for security purposes
	hasher := sha1.New()
	hasher.Write([]byte(roleName))

	return fmt.Sprintf("%s%s", prefix, base64.RawURLEncoding.EncodeToString(hasher.Sum(nil)))
}

func main() {
	// Open the input file
	file, err := os.Open("input.md")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	// Create the output file
	outFile, err := os.Create("output.md")
	if err != nil {
		panic(err)
	}
	defer outFile.Close()

	// Create a buffered writer for the output file
	writer := bufio.NewWriter(outFile)

	// Create a scanner to read the input file line by line
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		// Check if the line contains a role name
		if strings.Contains(line, "`fixed:") {
			// Extract the role name
			start := strings.Index(line, "`fixed:")
			end := strings.Index(line[start:], "` ")
			roleName := line[start+1 : start+end]
			fmt.Println(roleName)

			// Generate the prefixed role UID
			uid := PrefixedRoleUID(roleName)

			// Replace the role name with the UID in the line
			line = strings.Replace(line, "| x", "| `"+uid+"`", 1)
		}

		// Write the line to the output file
		fmt.Fprintln(writer, line)
	}

	// Check for errors from the scanner
	if err := scanner.Err(); err != nil {
		panic(err)
	}

	// Flush the writer to make sure all output is written
	writer.Flush()
}

```

### CODE REVIEW

**Comment by eleijonmarck** [comment]
@Jguer should we add this generation somewhere perhaps?

**Comment by Jguer** [comment]
> @Jguer should we add this generation somewhere perhaps?

I don't think for now it's worth it

**Review by jdbaldry — APPROVED** [review]
LGTM

**Review by jdbaldry — COMMENTED** [review]
Though perhaps we should explain what the UUID means a bit somewhere before the table?

**Comment by IevaVasiljeva** [comment]
@Jguer - these UIDs will only be correct for new'ish instances (instances created after we introduced predetermined UIDs for fixed roles). Are we happy with documenting them like this before https://github.com/grafana/identity-access-team/issues/401 has been done?

**Comment by Jguer** [comment]
probably not great, I'd add a disclaimer at least

**Pull request merged**
