### PR TITLE
add __timeGroup macro for mysql

### PR DESCRIPTION
**Pull request by svenklemm**
@daniellee  This adds a $__timeGroup(column,'5m') macro for mysql similar to the one for postgres. Unfortunately you cant reference aliased columns in mysql but you can reference them by index. 

Example Query:
```sql
SELECT 
  $__timeGroup(time,'5m') as time_sec,
  avg(value) as value, 
  'foo' as metric 
FROM data_table 
GROUP BY 1 
ORDER BY 1
```

### CODE REVIEW

**Comment by daniellee** [comment]
I found one small bug - the code for parsing intervals for both Postgres and MySQL cannot handle spaces.

- This works: `$__timeGroup(time,'5m') as time_sec,`
- This does not: `$__timeGroup(time, '5m') as time_sec,`
- This does not: `$__timeGroup(time,'5m' ) as time_sec,`

Otherwise, the mysql change looks great.

Have a question about the change to the Postgres macro (as I am a postgres noob) - what advantage does:

```sql
extract(epoch from \"time_column\")/300)::bigint*300"
```

have over:

```sql
extract(epoch from '5m'::interval))::int*extract(epoch from '5m'::interval)
```

Is it performance?

P.S. Next time could you keep the mysql/postgres changes in separate commits if possible. Thanks!

**Comment by svenklemm** [comment]
@daniellee the postgres change is mostly to simplify the expression and use the same principle as the mysql version it might be slightly better performance but that wasnt my motivation.

I'll do separate PRs for mysql and postgres for further stuff.

The current version of the patch allows both $__timeGroup(time_column,5m) and $__timeGroup(time_column,'5m') maybe only unquoted should be allowed since you merged the other patch that removes quoting from variables so you can still do $__timeGroup(time_column,$__interval). What do you think?

**Comment by daniellee** [comment]
Is there any problem with supporting both with and without quoting? Seems like most date functions in postgres take strings - so would that be most natural for postgres users?

**Comment by svenklemm** [comment]
Supporting both is fine aswell, having it quoted would be more natural for postgres users.

**Pull request merged**
