### PR TITLE
Correcting the General Syntax

### PR DESCRIPTION
**Pull request by Mohit-Nain**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
Looks wrong to me.

**Comment by Mohit-Nain** [comment]
can we have a second opinion on this. @oddlittlebird , can you please have a review

**Comment by aknuds1** [comment]
Based on my technical understanding of the described functionality, your change looks objectively wrong.

**Comment by oddlittlebird** [comment]
Agree with @aknuds1. This change would reverse the meaning of the statement.

**Pull request closed without merging**
