### PR TITLE
Pyroscope: Rename phlare to grafana-pyroscope-datasource

### PR DESCRIPTION
**Pull request by ryantxu**
This PR renames the builtin "phlare" datasource to "grafana-pyroscope-datasource" and adds registers an alias in the plugin registry.  This will keep existing settings working while allowing us to rebrand the plugin.

Depends on https://github.com/grafana/grafana/pull/67867, starts to address https://github.com/grafana/grafana/issues/17186

Alternative to:
https://github.com/grafana/grafana/pull/67847
https://github.com/grafana/grafana/pull/67490

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]

**Comment by ryantxu** [comment]
@aocenas -- i think this is good to go, but will wait for your ✅ before merging :)

**Review by wbrowne — COMMENTED** [review]
LGTM other than the switch

**Comment by aocenas** [comment]
Looks like this works, don't really understand the code well enough to comment on that but seems like there was discussion enough about that already. Just wondering why `grafana-pyroscope-datasource` and not just `grafana-pyroscope`?

**Comment by ryantxu** [comment]
> Just wondering why grafana-pyroscope-datasource and not just grafana-pyroscope?

all normal plugins end with their plugin type... typically `{org}-{name}-{type}`

**Pull request merged**
