### PR TITLE
Add support for reading data source provisioner secrets from files

### LINKED ISSUE #12368: Support reading config value from file when provisioning datasources
By allowing the provisioning system to read config values from disk as an alternative to regular strings, we enable orchastrators such as k8s, mesos and open shift to provide the token value as a file. This way the token management/lifecycle will be completly managed to the orchastrator without changing the datasource.yaml file. 

Ex in kubernetes case
```
<brancz> concretely the service account token is located in /var/run/kubernetes.io/serviceaccount/token
```

cc @brancz

### PR DESCRIPTION
**Pull request by bobmshannon**
Closes #12368, which also includes background details on the use cases surrounding this feature.

### CODE REVIEW

**Comment by brancz** [comment]
The concrete example that we needed in #12368 was adding bearer tokens from file. Could you add this method here?

**Comment by bobmshannon** [comment]
With this change, I believe one can do something like this:
```
  secureJsonData:
    httpHeaderName1: "Authorization"
  secureJsonDataFromFiles:
    httpHeaderValue1: "/path/to/secret"
```

where `/path/to/secret` has some auth header value e.g. `Bearer 1234`.

That seems like it may be inconvenient to use though, so I've added a new `BearerToken` field to the data source provisioner which may be better suited for that use case. That way `/path/to/secret` can contain just a secret token and not a formatted HTTP auth header value.

**Comment by brancz** [comment]
I’m not familiar with the codebase so I can’t review this, but generally sounds good to me. Maybe @berquist can review :)

**Comment by bergquist** [comment]
Hi! Thanks you for looking into this. 
There are some problems with this pr that are currently beeing adressed at the same time in other PR's :)
1. The token is stored unencrypted in the database. We are currently moving away from that for obvious reasons in https://github.com/grafana/grafana/pull/16175
2. The content of the file is only read when Grafana start which I dont think is optimal. But it depends on how often the token might be rotated. 

Eg. Prometheus reads the bearer token from file for each requests.

ping @aocenas

**Comment by bergquist** [comment]
Another kind of related PR that's currently being worked on https://github.com/grafana/grafana/pull/16499

**Comment by bobmshannon** [comment]
Thanks - let update this PR once #16175 goes in to include the preferred approach for handling and storing encrypted secrets. I'll also make some adjustments such that the live reload-ability story is better for the token file.

**Comment by bobmshannon** [comment]
Sorry, looking this over again I may have misunderstood. As long as we're fine with following the Prometheus approach of reading the secrets file for each request (as you suggested) that'll address both concerns. I'll update the PR accordingly.

**Comment by bergquist** [comment]
Great work!

But the be able to merge this into Grafana we need to support this for all datasource implementations in the backend. In `/pkg/tsdb` The best way of doing that is to move the code that sets password and auth headers to a [RoundTrip](https://golang.org/src/net/http/client.go?s=4305:5534#L105) function in https://github.com/grafana/grafana/blob/master/pkg/models/datasource_cache.go#L20

**Comment by bobmshannon** [comment]
@bergquist I've added the round-tripper implementations and rebased against master.

It seems we may also want a round tripper that also handles reloading certificates, but that may be better addressed in another PR.

**Comment by bergquist** [comment]
@bobmshannon lovely I'll review this once I get the chance. Long todo list ATM so please be patient :)

Yes, the dataproxy in Grafana needs some improvements. Totally agree that those changes should be in another PR.

**Comment by marefr** [comment]
Hey @bobmshannon I've taken over this review from Carl. Sorry it taken some time for me to come back to this. 

In general it looks good, but I'm still not convinced regarding spreading provisioning details into other parts of the code base. There's no way to configure reading certain values from file in the UI for example. It would have been much cleaner if the provisioning could handle this and update the datasource properties in the database accordingly in the same manner as provisioning works today. I do understand that it's requested that files should be re-read due to changes in files, but maybe this can be solved other ways? For example, you can now reload datasource provisioning thru the HTTP API: https://grafana.com/docs/http_api/admin/#reload-provisioning-configurations. 

So one idea would be to skip reading file values on each request and let provisioning handle reading them once to start with. That could be a first step to get this PR merged and then later on try to resolve the update of file values. Thoughts?

If you still think it's best to continue with this I would be happy if we can remove some more code duplication between datasource proxy and datasource cache. Seems like you can provide a custom `Transport` to `httputil.ReverseProxy` , but I haven't tried it so don't know if that would be a way to re-use the `DataSource.GetHttpTransport` in the datasource proxy? What do you think?

**Comment by HemendraSingh** [comment]
Hi,

is there any update on this?
I want to access secureJsonFields value from the HTTP API /api/datasources/{id}.

Would it be possible after this change?

**Comment by bergquist** [comment]
Resurrecting this PR. I'll give it some thought soon.

**Comment by bergquist** [comment]
Thank you for your patience. I have been thinking about this and I'd like to see a different approach. 

I think `BearerToken` and `BearerTokenFile` should be part of the database schema https://github.com/grafana/grafana/blob/master/pkg/models/datasource.go#L53:2 so we can avoid using the jsonData field for settings that are well known for multiple types of data sources. This should also make provisioning more straight forward. We dont have to care about the UI for those setting for an initial PR, that we can solve later. 

@bobmshannon I totally understand if your not up for this considering the slow reviews but if you are. Please let me know and I'll make sure to review your work dailyisch.

**Comment by bergquist** [comment]
Closing this.

**Pull request closed without merging**
