### PR TITLE
Docs: Updates getting_started.md for spelling mistake "configuered" to "configured"

### PR DESCRIPTION
**Pull request by venkatbvc**
There was a spelling mistake. Corrected it.

**What this PR does / why we need it**:
There is spelling mistake in Getting Started guide.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by venkatbvc** [comment]
@HG00

**Comment by venkatbvc** [comment]
@nrchakradhar

**Comment by venkatbvc** [comment]
@hugohaggmark 
@tomwilkie 
Please review

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Pull request merged**
