### PR TITLE
Color picker is not opening when setting threshold colors#16019

### LINKED ISSUE #16019: [Bug] Color picker in graph visualisation threshold editor can disappear on some interactions
**What happened**:
When using custom color value for thresholds going to custom tab in color picker throws an error and the picker vanishes.

**What you expected to happen**:
To be able to pick custom color.

**How to reproduce it (as minimally and precisely as possible)**:
New panel -> Visualisation -> Add threshold -> select Color: custom -> click Fill Color -> click on Custom tab

Kapture 2019-03-15 at 10 41 57

**Anything else we need to know?**:
Issue is the `ColorPicker` expects `color` prop to be [defined](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/ColorPicker/ColorPicker.tsx#L26). In the threshold form though we are using it from Angular context so it is not typechecked and we do not [initialise the color properly](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/thresholds_form.ts#L25) when creating the threshold or changing the color type.

### PR DESCRIPTION
**Pull request by srid12**
**What this PR does / why we need it:**
 Fixes #16019 

**Special Notes**
Do i need to  use different colors for dark and light theme? Presently i initialised fillColor and lineColor to '#000000' in all cases

### CODE REVIEW

**Comment by dprokop** [comment]
> Do i need to use different colors for dark and light theme? Presently i initialised fillColor and lineColor to '#000000' in all cases

@Ijin08 do you have some thoughts on that? I feel like black works pretty well on dark theme, but it's quite heavy on light one: 

image

**Comment by torkelo** [comment]
fillColor & lineColor should be undefined/null when colorMode: 'critical',

**Comment by dprokop** [comment]
> fillColor & lineColor should be undefined/null when colorMode: 'critical',

Why is that Torkel?

**Comment by torkelo** [comment]
Because I think colorMode defines the color

**Comment by srid12** [comment]
@torkelo  In  addFlotOptions method , We are overwriting fillColor and lineColor for critical. 
https://github.com/grafana/grafana/blob/d9db457b87e59af05b0b770285b77d6b70c391e1/public/app/plugins/panel/graph/threshold_manager.ts#L202-L227 
Do you think , i need to add fillColor and lineColor conditionally only when custom is selected?

**Comment by dprokop** [comment]
@srid12 Actually we are not overwriting those colors, but setting those for flot. I have created a fix for this issue https://github.com/grafana/grafana/pull/16079 so you can take a look at what the root cause was.

**Pull request closed without merging**
