### PR TITLE
(prometheus) fix template variable expansion in legend

### PR DESCRIPTION
**Pull request by mtanda**
I accidentally break the function.
Fix it by this PR.

### CODE REVIEW

**Comment by millerjp** [comment]
@mtanda do you know which version this is broken in? 3.0.4, 3.10?

**Comment by mtanda** [comment]
This change might break the behavior, https://github.com/grafana/grafana/pull/5096/files

[v3.0.4](https://github.com/grafana/grafana/blob/v3.0.4/public/app/plugins/datasource/prometheus/datasource.ts#L259-L276) is ok.
[v3.1.0](https://github.com/grafana/grafana/blob/v3.1.0/public/app/plugins/datasource/prometheus/datasource.ts#L263-L271) is broken.

**Comment by yershalom** [comment]
@mtanda As i'm not so familiar with TS, how can I fix this in my grafana server?
Just change this line and compile the file?

**Comment by mtanda** [comment]
@yershalom Yes.
At first, modify this line at grafana v3.1.0.
And then, build it by following step.
http://docs.grafana.org/project/building_from_source/

The `grunt` process output minified javascript to `public_gen/app/plugins/datasource/prometheus/datasource.js`.
Copy it to your grafana-server, and overwrite `/usr/share/grafana/public/app/plugins/datasource/prometheus/datasource.js`.

**Comment by yershalom** [comment]
Hi @mtanda ,

I did the same as you described but i still see the same issue.

**Comment by mtanda** [comment]
Just confirm, did you clear browser cache?

**Comment by yershalom** [comment]
Yes.
And to be sure, tried this also from firefox and safari.

**Comment by mtanda** [comment]
hmm, it's strange...
I checkout this [commit](https://github.com/grafana/grafana/commit/51d2534f6a94d09d4596f19036d0fcb856f80674), and build it locally, I confirm the template variable is correctly replaced.

**Comment by mtanda** [comment]
I use Chrome, and use DevTools to disable browser cache.

**Pull request merged**
