### PR TITLE
WIP/GraphNG: support soft min max axis

### LINKED ISSUE #979: Graph: Limits on Y auto scale (min max)
I've got a graph displaying error rates, and I've set the axis max to `auto`.  The problem is that on quiet days, with a low error rate, the axis shrinks down to display tiny blips as large mountains.  I could set the max to a particular vaule. But, I don't want to aim to low and experience a graph that goes off the chart. And, I don't want to set the max so high as to not get readable "medium" graphs.  (I don't want to use thresholds, as I've got graphs on the other axis, and I don't want to cause confusion with those ranges.)

An ideal solution would to have a "min-max" setting.  I could set the min-max to 100, and the axis would never get smaller than that.  But, it would grow if need be.

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #979

Status:  this is currently just the settings scaffolding and does not implement the actual scaling

This adds an axis mode option:
image

TODO:
- [ ] words!  what language makes sense?
- [ ] implement the auto scalling

### CODE REVIEW

**Comment by leeoniya** [comment]
i can land the remainder by the end of this week.

**Comment by leeoniya** [comment]
another option supports both hard limits (clamping) and soft limits by using the Min/Max from "Standard options" for hard, and adds `Axis > SoftMin` and `Axis > SoftMax` numeric fields to the "Time series options" for the soft limits.

The soft limits will be inside the hard limits. The scale/axis range will start at the soft limits and expand to the hard limits when the data exceeds the softs, and will clip afterwards.

image

**Comment by torkelo** [comment]
> should the JSON store the full config (rather than a unary value), so we have more flexibility to expose more subtle behavior in the future?

I am not sure that is a good idea, then we have to support that more complex model forever. The simpler the persisted model, the easier for us to change this & improve defaults.

**Comment by torkelo** [comment]
I like this `Axis min & max mode` approach, only one new setting needed.

**Comment by leeoniya** [comment]
@torkelo please read the recent comments onwards from https://github.com/grafana/grafana/issues/979#issuecomment-759187310

i think they're valid concerns, and the there's quite a lot of added flexibility gained from having 2 numeric fields instead of a toggle that neuters/repurposes clamping ability. i'm not sure of another way to accomodate spike-squashing in a softMin/max scenario is you cannot set hard limits as well.

**Comment by torkelo** [comment]
@leeoniya yea, maybe your right that separate soft min & max options would allow hard limits. Wish we could hide some of these advanced options so they are not always expanded/visible (to not overwhelm new users)

**Comment by dprokop** [comment]
> @leeoniya yea, maybe your right that separate soft min & max options would allow hard limits. Wish we could hide some of these advanced options so they are not always expanded/visible (to not overwhelm new users)

@torkelo I was thinking along the same lines about this. I assume when we talk about the advanced options we consider the soft min/max numeric fields. I find the pattern we use for the axis scales something that could fit this use case as well when the numeric inputs are only shown when the soft mode is selected:

image

**Comment by torkelo** [comment]
@dprokop but that would still require an always present soft mode option, and what would soft mode mean if you have not specified any values in the inputs? feels better to have soft min & soft max inputs but hide them & axis width, (and other future advanced options) in an advanced section or something :)

**Comment by leeoniya** [comment]
superseded by #30326.

**Pull request closed without merging**
