### PR TITLE
grafana/ui: Export TextArea under Forms namespace

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Add `TextArea` component as a part of `Forms` export.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
👍

**Comment by dprokop** [comment]
@daniellee this ain't external :D @Clarity-89 is Alex ;)

**Comment by daniellee** [comment]
@dprokop omg, getting so big that I don't know everyone's GitHub handle anymore. Sorry @Clarity-89

**Comment by dprokop** [comment]
Haha, no worries @daniellee!

**Comment by Clarity-89** [comment]
Haha, no worries @daniellee. It does say 'Member' on the right hand side though ;)

**Pull request merged**
