### PR TITLE
Replaced LegacyForms in MetricSelect component

### LINKED ISSUE #76107: Chore [Epic]: Replace LegacyForms in core Grafana
**What is the chore?**:
We have a set of legacy form components, which essentially were deprecated over 3 years ago ( #22862). They all have modern replacement components.

We only [have 11 occurences in core left](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1&from=1680771811847&to=1696583011847&viewPanel=13), so I though I'd make a list:

`grep -r -o 'LegacyForms;' public/app`:

 - [ ] public/app/core/components/Select/MetricSelect.tsx
 - [x] public/app/plugins/datasource/loki/configuration/QuerySettings.tsx https://github.com/grafana/grafana/pull/76331
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/ConfigEditor.tsx https://github.com/grafana/grafana/pull/76382
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/InfluxFluxConfig.tsx https://github.com/grafana/grafana/pull/76495
 - [ ] public/app/plugins/datasource/influxdb/components/editor/config/InfluxInfluxQLConfig.tsx
 - [x] public/app/plugins/datasource/opentsdb/components/OpenTsdbDetails.tsx https://github.com/grafana/grafana/pull/76165
 - [x] public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx https://github.com/grafana/grafana/pull/76397
 - [x] public/app/features/admin/ldap/LdapPage.tsx https://github.com/grafana/grafana/pull/76156
 - [x] public/app/features/folders/FolderSettingsPage.tsx https://github.com/grafana/grafana/pull/76313
 - [ ] public/app/angular/angular_wrappers.ts

**Is there anything else we need to know?**:
 In some cases just changing the component might not be enough, as it is located in older code. In these cases, removing occurrences of `gf-form` might also be valuable. If you do, please mention #65513.

**Related issues**
https://github.com/grafana/grafana/issues/66479
https://github.com/grafana/oss-plugin-partnerships/issues/222

### PR DESCRIPTION
**Pull request by RoxanaAnamariaTurc**
**What is this feature?**

Removed the LegacyForms from the MetricSelect component

**Why do we need this feature?**

There are better components to use.

**Who is this feature for?**

Developers

**Which issue(s) does this PR fix?**:

Fixes #76107

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
hey @RoxanaAnamariaTurc! 👋 

sorry for the review delay, was trying to find where this component (`MetricSelect`) is actually used. looks like the only place we use it internally is to expose it as an angular directive. given that changing this will change the external types, i think we should just wait until we remove angular and then remove this file completely instead. wdyt @joshhunt? 🤔

**Comment by joshhunt** [comment]
agree @ashharrison90. though, it might be used in enterprise?

**Comment by ashharrison90** [comment]
@joshhunt naw there's no use in enterprise that i can see either. think the best bet is
> wait until we remove angular and then remove this file completely instead

sorry @RoxanaAnamariaTurc 🙏 hope everything's going well! 😄

**Comment by RoxanaAnamariaTurc** [comment]
> @joshhunt naw there's no use in enterprise that i can see either. think the best bet is
> 
> > wait until we remove angular and then remove this file completely instead
> 
> sorry @RoxanaAnamariaTurc 🙏 hope everything's going well! 😄

Hey, not a problem :) all going well. will get on other issues to fix:D

**Pull request closed without merging**
