### PR TITLE
Alerting: Move sending alerts from scheduler to state manager

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What this PR does / why we need it**:
Currently, the responsibility of sending notifications to Alertmanagers is on the scheduler side. The scheduler gets states that the state manager returns and converts them to a model that is accepted by the AlertsRouter (Alertmanager) and then calls AlertRouter. 
The logic of the conversion is intricate: 
https://github.com/grafana/grafana/blob/49b1182f342bf48fe5d86f1761a83e949d070d70/pkg/services/ngalert/schedule/compat.go#L122-L130

the conversion calls back the state manager to check whether the state needs to be sent to the router, mutates the states, and then updates the state manager with mutated states. 

Apart from the fact that it can be done by a state manager, there is another unobvious consequence - at the end of processing the states before returning them to the scheduler, the state manager saves the states to the database. However, the mutation that happens in the conversion util does not go to the database until the next evaluation. 

**Special notes for your reviewer**:
This PR just moves things around without changing unit tests. If this PR is merged, the next steps could be to refactor the unit tests and simplify them.

### CODE REVIEW

**Review by grobinson-grafana — COMMENTED** [review]
I'm not 100% convinced that sending alerts should be up to the State Manager and I am unsure whether state management should be responsible for sending alert notifications. Perhaps you can convince me otherwise?

**Comment by yuri-tceretian** [comment]
Few reasons:
1. The state manager decides what state needs to be sent to the notifier and what needs to be omitted. See logic in compat.go that checks `NeedsSending`. Also, the manager's ProcessResults itself holds this logic. Therefore, it is already aware of sending states, which makes that knowledge shared between two entities, which makes it hard to track what does what, spreads the decision logic in multiple places, which makes it hard to track and maintain.
2. State is mutated outside of the state manager. It contains LastSentAt which is updated after the state is flushed to the database but before it is actually sent. The proper flow should be: "Calculate new states -> Notify -> Set LastSentAt -> persist". If notify part is on the scheduler side, then it will have to be aware of the implementation details of the state manager. 
3. The rule evaluation loop has to import the state manager and notifier and then just pass the result from one to another without any other use of it.

**Comment by grobinson-grafana** [comment]
> The state manager decides what state needs to be sent to the notifier and what needs to be omitted. See logic in compat.go that checks NeedsSending. Also, the manager's ProcessResults itself holds this logic. Therefore, it is already aware of sending states, which makes that knowledge shared between two entities, which makes it hard to track what does what, spreads the decision logic in multiple places, which makes it hard to track and maintain.

I appreciate that's how it works at present, but I was thinking perhaps instead we should decouple state management from notification? For example, I'm not sure the state management should have a `NeedsSending` function. That should happen in the code where we take alert states and then dispatch them as alert notifications. In the future, I would expect state management to be separate from dispatching and notification? 

> State is mutated outside of the state manager. It contains LastSentAt which is updated after the state is flushed to the database but before it is actually sent. The proper flow should be: "Calculate new states -> Notify -> Set LastSentAt -> persist". If notify part is on the scheduler side, then it will have to be aware of the implementation details of the state manager.

`LastSentAt` is weird, what does it represent? The time we sent it to Alertmanager, which might not be the time we sent a notification? This field almost lacks meaning, I wonder if we can remove it in Grafana 10?

**Comment by yuri-tceretian** [comment]
> LastSentAt is weird, what does it represent? The time we sent it to Alertmanager, which might not be the time we sent a notification? This field almost lacks meaning, I wonder if we can remove it in Grafana 10?

LastSentAt is actually used by the same logic that calculates `NeedsSending`. We do not send a firing alert every time we evaluate the rule. Instead, we wait for 2 evaluations to refresh the alert in Alertmanager.

**Comment by yuri-tceretian** [comment]
Another point for moving the responsibility for notifying the state manager is that currently state management logic is split between scheduler and manager. The rule evaluation loop owned by the scheduler holds the version of the rule, which is part of the current state. Therefore, every time we need to reset a rule's state (when the rule is deleted or updated) we have to access the scheduler, which will access the rule evaluation loop via the synchronized channel (updateCh, which will be blocked until the ongoing evaluation ends), and then it will check that version is indeed changed and then reset the state in the state manager and notify. 

If the state manager can send notifications, that piece can live in the state manager and when a rule is changed, the API handler can just call the state manager, which will reset states, send notifications and then persist the current version so concurrent updates from a scheduler with lower version would not be processed at all. 

This will let us get rid of the update channel in the scheduler, get rid of the Update method in the scheduler, and be able to reset states for a specific rule as well as for the entire group. That will let us keep state management logic for rule group and individual rules within the manager rather than the scheduler.

**Pull request closed without merging**
