### PR TITLE
FieldDisplay: remove auto min/max for percent units

### LINKED ISSUE #31679: TimeSeries Panel: Auto scaling of Y-axis min & max does not work with precent units
**What happened**:
When converting from graph panel to time series panel, the auto scaling of the Y-axis doesn't appear to work with 0-100% as the unit. If changing from linear to log base2, the axis and data disappear completely.

**What you expected to happen**:
Y-axis to be auto scaled.

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph panel using 0-100% y-axis, with data not going above 40%, convert to time series panel.

**Anything else we need to know?**:
First is graph panel, second is timeseries.
Screen Shot 2021-03-04 at 22 17 37

**Environment**:
- Grafana version: 7.5.0-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL7
- User OS & Browser: Chome latest

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #31679

The fieldDisplayProcessor tries to use reasonable min/max values when they are not set.  This is usually fine, but also means that graphs can not be auto ranged and can not use the new softMin/Max features.

In 8.0, lets remove this automatic setting

### CODE REVIEW

**Comment by ryantxu** [comment]
@torkelo -- can you link the issue this fixes?

**Review by torkelo — APPROVED** [review]
Awesome ❤️

**Comment by torkelo** [comment]
Fixes

**Comment by torkelo** [comment]
Fixes https://github.com/grafana/grafana/issues/31679

**Pull request merged**
