### PR TITLE
fix "Cloudwatch panel does not allow arbitrary variable values in query"

### LINKED ISSUE #11925: Cloudwatch panel does not allow arbitrary variable values in query
I query cloudwatch with a Custom Variable as instance id (Dimensions: InstanceId = $instanceId).

This works fine when the value of the variable is one of the pre-configured ones, but when I type something else into the dashboard it doesnt work (it queries the previously configured value or selects the top pre-configured one if I reopen the dashboard with a `&var-instanceId=<some value not present in the custom variable configuration>` in the url)

I can use arbitrary variable values for other things (panel title, WHERE-clause for influx queries etc) without issues.

Grafana v5.1.2 (c3c690e21), CentOS

### PR DESCRIPTION
**Pull request by mtanda**
fix https://github.com/grafana/grafana/issues/11925

### CODE REVIEW

**Comment by daniellee** [comment]
@mtanda this does not seem to work for me. The `selectedVariables` length is always greater than 0 so the `currentVariables` variable is not used.

I typed in test:

image

but the query still uses the predefined instanceid.

**Comment by mtanda** [comment]
Sorry, I misunderstand the issue.
Try to fix.

**Comment by mtanda** [comment]
@daniellee I fixed it. Please test it.

**Comment by daniellee** [comment]
Thanks @mtanda !

**Review by daniellee — COMMENTED** [review]
Looks good.

**Pull request merged**
