### PR TITLE
Chore: Upgrade typescript to version 3.6.3

### PR DESCRIPTION
**Pull request by kaydelaney**
Upgrades typescript from version 3.5.3 to 3.6.3.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Great that you do these bumps!

**Comment by dprokop** [comment]
@kaydelaney great stuff. Did you have a chance to test out grafana-toolkit after the bumps?

**Comment by kaydelaney** [comment]
@dprokop Good idea, will do!

**Comment by dprokop** [comment]
@kaydelaney just follow what's described here to verify toolkit locally: https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/README.md#contributing-to-grafana-toolkit

As a followup action point I have created this https://github.com/grafana/grafana/issues/19347

**Comment by kaydelaney** [comment]
Okay, seems like it works just fine. Okay to merge?

**Review by dprokop — APPROVED** [review]
yas!

**Pull request merged**
