### PR TITLE
Access Control: Allow signed in users access to GET data sources endpoints

### PR DESCRIPTION
**Pull request by kalleep**
What this PR does / why we need it:
When using access control enable support to read data source that a user has access to

### CODE REVIEW

**Review by IevaVasiljeva — APPROVED** [review]
Nice! Looks good!

Does this also require updating role assignments to give `ActionDatasourcesRead` to viewers and editors?

**Comment by kalleep** [comment]
> 
Good, point. I have to look into that

**Comment by marefr** [comment]
Code wise looks good and works as expected. However, it just came to me that we already exposes /api/frontend/settings as a way to receive same data as `grafanaBootData` - I added a https://github.com/grafana/grafana/issues/39011#issuecomment-999469666 to the issue author. Very sorry for finding this now.

Still think these changes might be useful, but question if is admin should still be required by default. Something we'll discuss beginning of next year - we'll let you know the outcome.

**Review by marefr — CHANGES_REQUESTED** [review]
Adding a blocker here for now until we've discussed it with my team

**Review by marefr — APPROVED** [review]
LGTM

Please remove `Fixes: #39011` from the description before merging.

**Pull request merged**
