### PR TITLE
Prometheus: Update PromQL typeahead and highlighting

### LINKED ISSUE #36677: Missing syntax highlighting and typeahead for several promql functions
**What happened**:

Query editor should provide typeahead and syntax highlighting for some PromQL functions but it doesn't

**How to reproduce it (as minimally and precisely as possible)**:

Write some query using sgn/clamp/absent_over_time/group/etc. and observe that there's no typeahead or syntax highlighting
https://play.grafana.org/goto/ducPY0m7k?orgId=1

**Environment**:
- Grafana version: HEAD (`main@36cb3965`)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Mac/Chrome
- Grafana plugins: N/A
- Others:

I'm fairly certain this is just a change to https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/promql.ts and I am happy to submit a patch

### PR DESCRIPTION
**Pull request by ekpdt**
**What this PR does / why we need it**:

PromQL syntax highlighting and typeahead is missing several operators and functions

**Which issue(s) this PR fixes**:

Fixes #36677

### CODE REVIEW

**Review by ivanahuckova — COMMENTED** [review]
@ekpdt thank you for your awesome contribution! 🚀🙌 The tests are unfortunately failing on linting. You can run `yarn prettier:write` to fix all of the lintinig errors. Plus you also need to sign CLA.

**Comment by ekpdt** [comment]
I've run `prettier` and I think the build should work now.
I'm working with my employer to sign the CLA

**Comment by ivanahuckova** [comment]
The last remaining thing is to sign CLA https://cla-assistant.io/grafana/grafana?pullRequest=36730

**Comment by ivanahuckova** [comment]
@ekpdt Could you please sign CLA https://cla-assistant.io/grafana/grafana?pullRequest=36730 so we can merge your PR? 🙂

**Comment by ekpdt** [comment]
Still working on my employer's approval

**Review by ivanahuckova — APPROVED** [review]

**Comment by ivanahuckova** [comment]
I've merged the PR. Thank you for your contribution @ekpdt. 🧡

**Pull request merged**
