### PR TITLE
Units: Custom suffix and prefix units can now be specified, for example custom currency & SI & time formats

### PR DESCRIPTION
**Pull request by ryantxu**
When trying to nicely format strings, it is useful to know which part of the text is the value and which is prefix/suffix.

Units can now take a string.  If the string matches a known unit the saved values will work, otherwise it defaults to a fixed unit with a suffix.  Other supported formats are:
```
prefix:${the prefix text}
time:${time format}
si:${scale char ie: k,m, etc}${unit}
```

Our current formatting system just converts to a string -- this returns formats as:
```
export interface FormattedValue {
  text: string;
  prefix?: string;
  suffix?: string;
}
```
This will allow visualizations more control on how to display the surrounding text.. but will also require calling `formattedValueToString()` rather than simply `value.text` if you want the whole string.

This PR also (but maybe should be a different issue!) Updates the picker so you can enter any value and it is used as the suffix

TODO:
- [x] tests -- convert to table style
- [x] Use `formattedValueToString` in Gauge
- [x] Use `formattedValueToString` in BarGauge
- [x] Use `formattedValueToString` in Graph Legend
- [x] Use `formattedValueToString` in Graph Toolip
- [x] Use `formattedValueToString` in Piechart
- [x] The react unit picker in angular
- [ ] verify removing `dateDisplayFormat` is OK

### CODE REVIEW

**Comment by ryantxu** [comment]
@torkelo -- The bar gauge size calculation seems to still be off, can you take a look?

@dprokop -- Can you look at how this affects GraphTooltip and GraphLegend?

**Comment by ryantxu** [comment]
@torkelo -- I think we will also need to update the angular unit picker with the react one: 
image

**Comment by torkelo** [comment]
Fixed Stat Panel and Bar Gauge, they now use a shared component to render value (FormattedValueDisplay)

**Comment by ryantxu** [comment]
@dprokop -- I updated this so we remove `dateDisplayFormat` from fieldConfig.  We can now use `unit: 'time:YYYY'` to sent the display format.

I think I updated everything relevant, but can you check that things still work how you expect.

**Comment by torkelo** [comment]
tested with angular graph legend and tooltip and works. The react graph is not showing unit.

**Comment by ryantxu** [comment]
I updated the Graph2 legend & tooltip so it now uses the configured unit.

I think this is now ready to merge

**Review by torkelo — APPROVED** [review]

**Pull request merged**
