### PR TITLE
Logs: Allow dots in a label's name

### PR DESCRIPTION
**Pull request by loyd**
https://github.com/grafana/grafana/discussions/40645

### CODE REVIEW

**Comment by loyd** [comment]
@joshhunt @ashharrison90 @jackw any thoughts?

**Comment by gabor** [comment]
@loyd thanks for the pull request, two comments:

1. please sign the CLA.
2. could you also update the related test cases so they contain examples of labels-with-dots? around here: https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/logs.test.ts#L120-L147 , so that at least `getFields`, `getLabelFromField` and `getValueFromField` are tested

**Comment by ivanahuckova** [comment]
@loyd To continue with reviewing this PR, could you please:
-  sign the CLA.
- could you also update the related test cases so they contain examples of labels-with-dots? around here: https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/logs.test.ts#L120-L147 , so that at least getFields, getLabelFromField and getValueFromField are tested

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
@loyd To continue with reviewing this PR, could you please:
-  sign the CLA.
- could you also update the related test cases so they contain examples of labels-with-dots? around here: https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/logs.test.ts#L120-L147 , so that at least getFields, getLabelFromField and getValueFromField are tested

**Pull request closed without merging**
