### PR TITLE
Add WeCom Notification Channel

### LINKED ISSUE #21211: Support send WeCom alert message
**What would you like to be added**:
[WeChat Work](https://work.weixin.qq.com/) is a popular IM in china for working.
We can add an message webhook for it.
**Why is this needed**:
make more friendly to WeChat Work user

### PR DESCRIPTION
**Pull request by kevisong**
**What this PR does / why we need it**: 

Added WeCom Notification Channel Support

Test file passed and included

Documentation is updated accordingly

Fixes https://github.com/grafana/grafana/issues/21211.

**Special notes for your reviewer**:

I am excited to send this pull request to add WeCom notification channel support for Grafana.

WeCom is a communication platform for enterprises that is similar to WeChat.

Please do let me know if any other info is needed for this to be merged : )

### CODE REVIEW

**Comment by aknuds1** [comment]
Sorry, closing this PR since we're not adding more notifiers to Grafana core. We are planning to instead support new notifiers as plugins, although this is unfortunately not in place yet.

**Comment by KEVISONG** [comment]
> Sorry, closing this PR since we're not adding more notifiers to Grafana core. We are planning to instead support new notifiers as plugins, although this is unfortunately not in place yet.

Noted.

When will this plugin feature be supported? As WeCom channel support is desperately needed for ops engineer that uses WeCom : )

**Comment by aknuds1** [comment]
The plugin platform is on the planning stage, but I can't provide any ETA.

**Comment by KEVISONG** [comment]
> The plugin platform is on the planning stage, but I can't provide any ETA.

@aknuds1 

Understood. Looks like it's gonna be a long time for this exciting feature to be finally ready.

We're part of Tencent Cloud DevOps division and we really want this channel to be supported.

Is it possible for this pr to be merged and included for now.

**And when the plugin feature is released, we will provide all the support to switch from grafana core implementation to the plugin implementation for this channel**

**Comment by aknuds1** [comment]
I will check with the team.

**Comment by KEVISONG** [comment]
@aknuds1 

Thank you so much for the consideration. 

We will wait for your good news at your earliest convenience.

**Comment by aknuds1** [comment]
Have you considered using the [webhook notifier](https://grafana.com/docs/grafana/latest/alerting/notifications/#webhook) to connect to WeCom instead, as a temporary solution?

**Comment by KEVISONG** [comment]
> Have you considered using the [webhook notifier](https://grafana.com/docs/grafana/latest/alerting/notifications/#webhook) to connect to WeCom instead, as a temporary solution?

@aknuds1

Yeah we actually did. 

We have been using Grafana as internal monitoring platform for not only one, but numerous projects that distributed across all environments. These environments include public cloud, private cloud and hybrid cloud.

Webhook helped a lot when we only have one or two projects. As we can develop and deploy a dedicated backend API to interface with the webhook.

However as we engaged in more and more projects. **We begin to realize that it'll be so great if this widely used WeCom channel can be supported natively, and in the mean time, empowering not only our internal teams, but any user or enterprise that uses Grafana and WeCom.** This is the reason for issuing this pull request.

Really hope we can pull it off.

**Comment by torkelo** [comment]
Can you open a feature request for this notifier so we can gauge the interest in it? 

We are not accepting new notifiers without a big community interest in it. We would accept work on extending the plugin system to support external plugins for alert notifiers. There also possible to consider this as roadmap assurance if you're a Grafana Enterprise customer.

**Comment by aknuds1** [comment]
@torkelo there is a feature request already https://github.com/grafana/grafana/issues/21211.

**Comment by torkelo** [comment]
ah, good to know, was not mentioned in the PR description

**Comment by aknuds1** [comment]
Yeah should have been, I can add it to the description.

**Comment by KEVISONG** [comment]
@aknuds1 Thanks a lot for adding the corresponding feature request : )

**Comment by KEVISONG** [comment]
> Can you open a feature request for this notifier so we can gauge the interest in it?
> 
> We are not accepting new notifiers without a big community interest in it. We would accept work on extending the plugin system to support external plugins for alert notifiers. There also possible to consider this as roadmap assurance if you're a Grafana Enterprise customer.

@torkelo

Per #21211. We will provide additional info and support if necessary while you and the Grafana team gauging this.

**Comment by KEVISONG** [comment]
Hi guys. Any update on this pr? : )

**Comment by KEVISONG** [comment]
@aknuds1

Hi Mr. Arve

Any update on this pr?

Hoping to be merged : )

**Comment by KEVISONG** [comment]
@aknuds1 

Hi Arve. Any luck on merging this alert channel?

**Comment by aknuds1** [comment]
Have you considered Torkel's enterprise/roadmap assurance proposal above?

**Comment by KEVISONG** [comment]
> Have you considered Torkel's enterprise/roadmap assurance proposal above?

I will look into it. Thanks~

**Pull request closed without merging**
