### PR TITLE
playlist: introduce coremodel schema, swap in for backend DTO types

### PR DESCRIPTION
**Pull request by sdboyer**
**What this PR does / why we need it**:

Introduces a coremodel for playlists. This is following the same general goal as #55960 and #55622. It aims at being truly the _most_ minimal change that also gets the backend onto the contract:

* Add the canonical schema, using a maximalist definition decision rule for what fields to include: "all known fields, even deprecated ones"
  * For those which we anticipate getting rid of, there's a `@grafana(decisionNeeded)` attribute on them. This is a programmatic TODO for later, and we can write a linter that disallows such markers for anything sufficiently far along in its maturity journey (i'm workign on that doc)
* Uses a type alias for the existing `PlaylistItemDTO`, and a struct embedding for `PlaylistDTO` in order to add the internal-only `OrgId` field.
* Change only what's necessary for tests and the compiler to pass.

While it's plausibly a good goal to converge the `Playlist` and `PlaylistDTO` types, as in #55959, the goal of doing it this way is to, again, be minimal - _just_ what's necessary in order to have the backend shift over to rely on the generated type.

We'll also need to swap in the generated stuff for frontend types before playlists reach the threshold of "synchronized type" (again, a doc is coming for these maturity steps). That can be a follow-up too, though, which shouldn't _have_ to be difficult given that we know the schema is expressing a superset of [the existing frontend type](https://github.com/grafana/grafana/pull/55622#issuecomment-1255257291). The interesting discussion there will probably be around field optionality - but, one step at a time.

cc @sakjur @ryantxu 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ryantxu** [comment]
Can we close this in favor of #55960

The embedded orgId is an internal implementation detail... and not part of what we want returned

**Review by sakjur — APPROVED** [review]
LGTM

**Comment by sakjur** [comment]
I agree with @ryantxu that #55960 is preferable in some ways, but this doesn't change the API contract, so we're able to merge this as-is and then focus on fixing this service properly. That gives us a nice separation of pure refactoring (this) and changes (#55960).

**Comment by sdboyer** [comment]
to be clear, i also think #55960 is closer to the problems we'd actually like to solve - this is just the first, smallest step, and one that i think we can codify as a general procedure that will apply to other types.

**Pull request merged**
