### PR TITLE
Docs: Replace ampersands with and (#19294)

### LINKED ISSUE #19294: Remove ampersands from docs
Anywhere an ampersand is used as an abbreviation for "and", remove it.

However, *do not* remove the ampersand if it appears in UI text. Always match the UI.

### PR DESCRIPTION
**Pull request by brew-install-buzzwords**
**What this PR does / why we need it**:

Replaces ampersands in docs with the word "and"

**Which issue(s) this PR fixes**:

Fixes #19294

**Special notes for your reviewer**:

In order to maintain consistency, ampersands in reference to specific UI buttons were not changed. I only made changes to files in the `docs` directory. If there is documentation in other parts of the project that needs to be addressed, please let me know.

### CODE REVIEW

**Review by marcusolsson — APPROVED** [review]
This is great stuff! Thank you!

**Comment by marcusolsson** [comment]
We need you to [sign the CLA](https://cla-assistant.io/grafana/grafana?pullRequest=19584) before we can merge this. Let me know if you have any questions!

**Comment by brew-install-buzzwords** [comment]
I signed the CLA, but it looks like I didn't properly set up the git environment on this computer, so now the authorship is all weird . I tried amending the previous commit, but I only succeeded in adding the correct info without removing the incorrect info (it says it has two authors, but both are me).

**Comment by brew-install-buzzwords** [comment]
@marcusolsson Please see my new PR #19609

**Pull request closed without merging**
