### PR TITLE
Azure: Add new Azure infrastructure dashboards

### PR DESCRIPTION
**Pull request by yves-chan**
**What is this feature?**

Adding a set of Azure Infra dashboards to the Azure Monitor Datasource. The author of these dashboards is @judyer28 

**Why do we need this feature?**

Out of the box dashboards for variable Azure Infrastructure resources.

**Who is this feature for?**

Users of Azure Monitor datasource

**Which issue(s) does this PR fix?**:

image (4)
image (3)
image

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by yves-chan** [comment]
@aangelisc Can I get a review on these PRs? thanks!

**Review by aangelisc — COMMENTED** [review]
Hi @yves-chan,

Apologies for the delay in reviewing this PR.

I think the dashboards in this PR would benefit from an explanation of the `Workspace Scope` and `Resource Scope` template variables. At the moment it's unclear to a user what the correct value of these variables should be. 

Additionally, it's unclear what kind of configuration in Azure is required in order to get these dashboards to display data. I can't currently see any data in the dashboards as I'm not forwarding any metrics to a logs workspace.

I'd also suggest adding a blurb in each dashboard outlining which services each dashboard is intended to be useful for.

**Comment by judyer28** [comment]
Hello @aangelisc, the template variables themselves both have descriptions with further explanation:
image

image

The description for the dashboard itself has instructions for the configuration needed.
image

**Comment by aangelisc** [comment]
Hi @judyer28,

Thank you for clarifying. I think the template variable descriptions are fine. As the dashboard description is only accessible from the settings I think the additional description would've made more sense in the text panel but I'm happy to proceed with this as is!

**Comment by yves-chan** [comment]
thanks @aangelisc, should be updated now

**Review by aangelisc — APPROVED** [review]

**Comment by aangelisc** [comment]
Hi @yves-chan, thank you! Could you also merge main to this branch please?

**Comment by yves-chan** [comment]
@aangelisc oops sorry, just merged main to this branch!

**Comment by aangelisc** [comment]
Thank you for the contribution @yves-chan! Much appreciated 😊

**Pull request merged**
