### PR TITLE
TimeSeries: Fix overflowing exemplar modals causing content shifts

### LINKED ISSUE #38976: Dashboard jiggles around when exemplar view drops down at right of window
**What happened**:
As I mouse over exemplars, the whole window "jiggles".

https://user-images.githubusercontent.com/8125524/132492100-a341a5df-ee52-4952-94a6-2d2d700b005b.mp4

**What you expected to happen**:
Steady display.

**How to reproduce it (as minimally and precisely as possible)**:
Make a Timeseries panel with exemplars, and have it set against the right-hand-side of the window.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.0-33294pre (17f9bc138e)
- Data source type & version: Prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10; Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Grafana plugins: 
Alert Manager By Prometheus alertmanager, 
Alert groups By Grafana Labs, 
Alert list By Grafana Labs, 
Annotations list By Grafana Labs,
Azure Monitor By Grafana Labs,
Bar chart By Grafana Labs,
Bar gauge By Grafana Labs,
Canvas By Grafana Labs,
CloudWatch By Grafana Labs,
Dashboard list By Grafana Labs,
Debug By Grafana Labs,
Direct Input By Grafana Labs,
Elasticsearch By Grafana Labs,
Gauge By Grafana Labs,
Geomap By Grafana Labs,
Getting Started By Grafana Labs,
Google Cloud Monitoring By Grafana Labs,
Graph (old) By Grafana Labs,
Graphite By Grafana Labs,
Heatmap By Grafana Labs,
Histogram By Grafana Labs,
InfluxDB By Grafana Labs,
Jaeger By Grafana Labs,
Live By Grafana Labs,
Logs By Grafana Labs,
Loki By Grafana Labs,
Microsoft SQL Server By Grafana Labs,
MySQL By Grafana Labs,
News By Grafana Labs,
Node Graph By Grafana Labs,
OpenTSDB By Grafana Labs,
Pie chart By Grafana Labs,
Plugin list By Grafana Labs,
PostgreSQL By Grafana Labs,
Prometheus By Grafana Labs,
Stat By Grafana Labs,
State timeline By Grafana Labs,
Status history By Grafana Labs,
Table By Grafana Labs,
Table (old) By Grafana Labs,
Tempo By Grafana Labs,
TestData DB By Grafana Labs,
Text By Grafana Labs,
Time series By Grafana Labs,
Welcome By Grafana Labs,
XY Chart By Grafana Labs,
Zipkin By Grafana Labs

- Others:

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
Fix for OS's that provide scrollbar implementation within the content.

**Why do we need this feature?**
The content shifting is making it impossible to interact with exemplars

**Who is this feature for?**
Anyone using exemplars, not running Apple silicone.

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/38976

**Special notes for your reviewer**:
The max height solution seems to work well, and content is scrollable within the exemplar if there is more content then available height. Most importantly this stops the content shift.

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
slack thread for context: https://raintank-corp.slack.com/archives/C025WTVRBSN/p1677771583286709

not sure this is the correct solution tbh, and i think potentially causes more problems than it solves if it will be obscuring content (e.g. graph axes). 

think the solution would be to fix the exemplar tooltip positioning. it should not position itself outside of the page bounds

**Comment by gtk-grafana** [comment]
@ashharrison90 @leeoniya @bboreham if y'all have a few minutes to review this I'd really appreciate it!

**Review by leeoniya — APPROVED** [review]
:shipit:

**Comment by bboreham** [comment]
> slack thread for context: https://raintank-corp.slack.com/archives/C025WTVRBSN/p1677771583286709

(with apologies to folks outside Grafana Labs; that is to a private workspace)

**Comment by ashharrison90** [comment]
@gtk-grafana is there an easy way to reproduce this locally? 🤔

**Comment by gtk-grafana** [comment]
@ashharrison90 Yeah you can use the debug snapshot that I provided in the slack channel from the client's dashboard, otherwise you can use any exemplar modal that is taller then the viewport.

**Comment by leeoniya** [comment]
you also have to be on an OS/browser combo that does not do overlay scrollbars. for me it was EndeavourOS (Arch) x64, KDE/Plasma, Chromium/Firefox. however, a new dev version of Chrome did not have this issue, i suspect because they started using the os-supplied overlay scrollbars.

**Comment by gtk-grafana** [comment]
Thanks to @ashharrison90 for deteremining this can be reproduced on apple by setting scrollbar settings in system config!

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Review by bohandley — APPROVED** [review]
LGTM!

**Pull request merged**
