### PR TITLE
Resurrected nikita-graf's work for enhancing Playlist feature

### PR DESCRIPTION
**Pull request by utkarshcmu**
A bit of refactoring in @nikita-graf's work in #2649.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
@bergquist @torkelo Try merging this PR into a separate branch locally and see @nikita-graf's work. It is awesome. IMO, work left in this PR is to remove current Playlist feature.

Please review and let me know your opinions. Thanks for a tool like Grafana, its awesome !!!

**Comment by bergquist** [comment]
Ill check this out later today. 

I like the idea and I think this is a minimum requirement for kiosk mode :)

**Comment by utkarshcmu** [comment]
I will be pushing some more commits to this PR today, so that it is production ready. Things work right now but some polishing is needed on this PR.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/issues/791

**Comment by utkarshcmu** [comment]
Yes this PR also solves #791 :)

**Comment by bergquist** [comment]
I'm currently plowing through all our issues and found some regarding playlists so I'm linking them. Not saying we have to solve all of them. Lets focus on getting this in first but without limiting any future work for other issues :) 

https://github.com/grafana/grafana/issues/377

**Comment by utkarshcmu** [comment]
Ok. This PR is now ready for review. Thanks.

**Comment by bergquist** [comment]
I like the approach of solving the play list issue.
But there are still some issues that have to be resolved before merging it to master.

* Unittests. All big additions to Grafana should include some unittests that make it more obvious if something breaks in the future. 

* The UX is lacking. 
  - I don’t think its obvious what going on in the create play list view. perhaps @matt could give us some help?

* A relation table is preferred over using data as an json field.  
  - a relation table makes it possible to see how many play lists one dashboard is included in etc. 

This have to be improved before merging to master. 

Otherwise its a great solution to this problem and I really want to see this in Grafana 3.0.

I might have some time for this during this week. Could you update the PR to target the play list branch instead of master? That way we can work on this together.

**Comment by utkarshcmu** [comment]
If we go with the tabular/relational approach then we will be restricted to have a playlist of dashboards. 

2 more kind of playlists are required by users:

1. Playlist based on template variables, which is one of the most asked feature(P0:Critical) in Grafana.
2. Platylist based on dashboard tags.

I think JSON Data field can be a great field to hold URLs of the dashboards in a playlist, whether its a playlist based on selected dashboards, template variables or dashboard tags. This way we can enrich playlist feature for 3.0. What do you think? Do you still think we should go with relational approach for playlist in DB?

**Comment by utkarshcmu** [comment]
And how can I push this PR to a different branch, I do not have permissions to push to any branch in Grafana repo? May be I can push to a branch in your fork, if you can make me a Collaborator to your fork. Then we can work together on that.

**Comment by bergquist** [comment]
I just created the playlist branch in grafana/grafana. I think you should be able to target it with this PR.

Good point about supporting different ways of getting dashboards for the play list. Lets stay with the data field.

**Comment by utkarshcmu** [comment]
Closing via #3611 Thanks @bergquist

**Pull request closed without merging**
