### PR TITLE
Docs: Refactored Enterprise side menu

### PR DESCRIPTION
**Pull request by oddlittlebird**
Several topics were linked in two places in the documentation side menu. For these topics, when you clicked them in the Enterprise section, it would jump to another section of the side menu. For example, if you clicked Enterprise > SAML, you would jump to Authentication > SAML. This was annoying and confusing.

I moved the full content into the `enterprise` folder and changed the Enterprise side menu links to those topics. I removed most of the content from the topics in the other folders (auth, permissions, and so on) and provided links from there to the full topics.

**Special notes for your reviewer**: I did not do much content editing. All topics still need to be fully reviewed at some point in the future. The point of this was to reorganize content and fix the annoying menu jumping.

### CODE REVIEW

**Comment by daniellee** [comment]
I got a ton of errors when trying to build this:

```
ERROR 2020/02/14 10:54:38 [en] REF_NOT_FOUND: Ref "ldap.md": "/hugo/content/docs/grafana/latest/enterprise/enhanced_ldap.md:62:60": failed to resolve ref: page reference "ldap.md" is ambiguous
ERROR 2020/02/14 10:54:57 [en] REF_NOT_FOUND: Ref "github.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:43:18": failed to resolve ref:page reference "github.md" is ambiguous
ERROR 2020/02/14 10:54:57 [en] REF_NOT_FOUND: Ref "gitlab.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:44:18": failed to resolve ref:page reference "gitlab.md" is ambiguous
ERROR 2020/02/14 10:54:57 [en] REF_NOT_FOUND: Ref "auth-proxy.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:45:16": failed to resolve ref: page reference "auth-proxy.md" is ambiguous
ERROR 2020/02/14 10:55:08 [en] REF_NOT_FOUND: Ref "ldap.md": "/hugo/content/docs/grafana/latest/enterprise/enhanced_ldap.md:62:60": failed to resolve ref: page reference "ldap.md" is ambiguous
ERROR 2020/02/14 10:55:08 [en] REF_NOT_FOUND: Ref "github.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:43:18": failed to resolve ref:page reference "github.md" is ambiguous
ERROR 2020/02/14 10:55:08 [en] REF_NOT_FOUND: Ref "gitlab.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:44:18": failed to resolve ref:page reference "gitlab.md" is ambiguous
ERROR 2020/02/14 10:55:08 [en] REF_NOT_FOUND: Ref "auth-proxy.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:45:16": failed to resolve ref: page reference "auth-proxy.md" is ambiguous
ERROR 2020/02/14 10:55:09 [en] REF_NOT_FOUND: Ref "ldap.md": "/hugo/content/docs/grafana/latest/enterprise/enhanced_ldap.md:62:60": failed to resolve ref: page reference "ldap.md" is ambiguous
ERROR 2020/02/14 10:55:09 [en] REF_NOT_FOUND: Ref "github.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:43:18": failed to resolve ref:page reference "github.md" is ambiguous
ERROR 2020/02/14 10:55:09 [en] REF_NOT_FOUND: Ref "gitlab.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:44:18": failed to resolve ref:page reference "gitlab.md" is ambiguous
ERROR 2020/02/14 10:55:09 [en] REF_NOT_FOUND: Ref "auth-proxy.md": "/hugo/content/docs/grafana/latest/enterprise/team-sync.md:45:16": failed to resolve ref: page reference "auth-proxy.md" is ambiguous
```
I thought first that maybe it was due to me having an old version of Hugo but getting the same errors after upgrading to the latest version (0.64.1). When I changed the references to be absolute then it works.

@oddlittlebird do you know why the relative links aren't working for me? Which version of hugo are you using?

**Comment by oddlittlebird** [comment]
@daniellee , hopefully the latest commit will fix those.

**Review by daniellee — CHANGES_REQUESTED** [review]
The menu looks wrong to me. The first two links, Overview and Reporting are correct. Datasource permissions seems to be missing in the menu and everything else is off by one. There is no link to License expiration as the menu link points to White labeling.

image

http://localhost:3002/docs/grafana/latest/enterprise/white-labeling/
image

**Review by daniellee — APPROVED** [review]
LGTM once the menu is fixed

**Pull request merged**
