### PR TITLE
Show grafana admins

### LINKED ISSUE #4649: FR: Way to contact Grafana/Org admin
A user should be able to contact Grafana/Org admin in some way. The easiest way is to just display the admin emails in some view.

### PR DESCRIPTION
**Pull request by Jonnymcc**
Shows the contact info for admins at the bottom of dashboards. I'm sure my javascript code could be neater. Also, I'm wondering what would happen if an installation had a large number of admins. Would be a pretty large footer.

I also did not use the "footer" css class because I noticed it is hidden on dashboard views. For me I wish the footer, with the current version etc., was always shown.

Resolves https://github.com/grafana/grafana/issues/4649

### CODE REVIEW

**Comment by torkelo** [comment]
I would like to keep the dashboard body clean from footers. Maybe a new modal view under the help icon in the sidenav

**Comment by Jonnymcc** [comment]
Why close this? I was trying to add an item to the help menu here https://github.com/grafana/grafana/blob/master/pkg/api/index.go#L293 but the item doesn't show, am I missing something? 
Also, is a modal view the best way to display this information? An alternative could be an "email admin" item with a mailto: link. But then do we just grab the first admin email? Or send an email to all of the admins?

**Comment by Jonnymcc** [comment]
I'm past the above problem. I was using the wrong binary. Apparently `go run build.go build` does not update `$GOPATH/bin/grafana-server` and instead I had to use the build binary in the source directory.

I'm now working on the modal view, but am unable to get the modal template to populate and I'm unsure why. I've pushed my work so far to my branch.

**Comment by Jonnymcc** [comment]
@torkelo I've pushed change to my branch that displays the admins users in a modal view like you suggested. Do you want to re-open this PR or should I create a new one?

**Comment by torkelo** [comment]
there is not much demand for this feature, but I do see the utility. Not sure what the best way to present it is as there is no footer on the dashboard page. This requires some UX brainstorming.

**Comment by torkelo** [comment]
Can you show some screenshots in #4649 as a proposed solution? then I will loop in our head of UX for some feedback

**Comment by Jonnymcc** [comment]
@torkelo I added screenshots to #4649

**Pull request closed without merging**
