### PR TITLE
Tracing: Remove redundant types

### PR DESCRIPTION
**Pull request by ifrost**
Current situation:

* Types `TraceKeyValuePair` and `TraceLog` are duplicated in multiple places
* They are almost identical. The only difference being that `TraceKeyValuePair` in `@grafana/data` has not optional `type` property

b

Changes in the PR:

* Add `type` property to `TraceKeyValuePair` in `@grafana/data`
* Remove `TraceKeyValuePair` and `TraceLog` outside of `@grafana/data`
* Replace imports to removed types with the ones coming with `@grafana/data`

### CODE REVIEW

**Comment by ivanahuckova** [comment]
What did you use to create this? 👀 
image

**Comment by ifrost** [comment]
> What did you use to create this? 👀 image

That's PlantUML (with https://planttext.com/). But nothing automagically generated, just manually typed in 😅

**Review by joey-grafana — APPROVED** [review]
LGTM 👍

**Comment by ifrost** [comment]
@grafana/oss-big-tent could you please have a look at Jaeger changes?

**Review by ivanahuckova — APPROVED** [review]
LGTM for jaeger changes

**Pull request merged**
