### PR TITLE
Admin: Keeps expired api keys visible in table after delete

### LINKED ISSUE #31502: When deleting expired API keys, non deleted keys are also removed from page.
**What happened**:
After deleting an API key with "Show Expired" selected, all the other expired API keys are hidden until the screen is refrshed, or "show expired" is de-selected and selected again. 

**What you expected to happen**:
expired API keys to remain visible. 

**How to reproduce it (as minimally and precisely as possible)**:
Create 3 api keys with 1second expiry 
wait until they have expired. 
refresh the api key page. 
select "show expired" 
delete one of the keys. 

api_key_delete

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3 
- Data source type & version: n/a 
- OS Grafana is installed on: n/a
- User OS & Browser: windows & Firefox 
- Grafana plugins: n/a 
- Others: n/a

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
So many things in ApiKeysPage seem to be out of date/sync so I think I'm going to spend some time to add tests and clean things up so I'm pushing the milestone to 7.5 stable instead.

**Which issue(s) this PR fixes**:
Fixes #31502

**Special notes for your reviewer**:

### CODE REVIEW

**Review by mckn — APPROVED** [review]
LGTM! Works as expected. If you want to improve the UI a bit I would try to mark the row with the expired keys so they look disabled. Maybe ad a grayish tone to the text?

**Comment by hugohaggmark** [comment]
> LGTM! Works as expected. If you want to improve the UI a bit I would try to mark the row with the expired keys so they look disabled. Maybe ad a grayish tone to the text?

Great suggestion, will look into it!

**Comment by hugohaggmark** [comment]
@mckn I think I'm going to skip style changes in this PR, there are so many styles/components that need upgrading to the new FormStyles.

**Comment by mckn** [comment]
> @mckn I think I'm going to skip style changes in this PR, there are so many styles/components that need upgrading to the new FormStyles.

Ok ok, sounds good!

**Pull request merged**
