### PR TITLE
GraphNG: add gaps/nulls support to staircase & smooth interpolation modes

### PR DESCRIPTION
**Pull request by leeoniya**

### CODE REVIEW

**Comment by leeoniya** [comment]
progress so far (fixes for fills, leading/trailing nulls, proper spanning of staircase values across gaps):

image

image

**Comment by leeoniya** [comment]
this work is now complete and ready for review. (remember to `yarn install` to update uPlot).

image

**Review by dprokop — APPROVED** [review]
Great work on this one @leeoniya. Regarding the staircase display I think we would like to address this https://github.com/grafana/grafana/issues/7941 too at some point, but wouldn't consider this a high prio as of now.

**Comment by torkelo** [comment]
would be good to create more test dashboards and panels for different scenarios (checking under devenv/dev-dashboards) 

We have these for the old graph:
http://localhost:3000/d/5SdHCadmz/panel-tests-graph?orgId=1
http://localhost:3000/d/37Dq903mk/panel-tests-graph-gradient-area-fills?orgId=1  (something we will need eventually is gradient area fills in uPlot) 
http://localhost:3000/d/P7vAAhvZk/panel-tests-graph-y-axis-ticks?orgId=1 
http://localhost:3000/d/XMjIZPmik/panel-tests-graph-time-regions?orgId=1  (Time regions are not super important, can wait) 

uPlot 
http://localhost:3000/d/TkZXxlNG3/panel-tests-graph-ng?orgId=1  (needs to updated or split into separate dashboards, not sure which path is best) 
http://localhost:3000/d/29Yjn62Gk/panel-tests-graph-ng-y-axis-ticks?orgId=1

Maybe a separate test dashboard with all the scenarios for interpolation modes + gaps?

**Comment by ryantxu** [comment]
This looks great!  lets merge and fix the radio issue seperatly ;)    

image

**Pull request merged**
