### PR TITLE
Docs: updates for file-based menu

### PR DESCRIPTION
**Pull request by robbymilo**
**What this PR does / why we need it**:

Cleans up front-matter params for https://github.com/grafana/website/pull/2543

To test, ~~in docs dir run `make docs-file-based`~~ please run the website locally after checking out https://github.com/grafana/website/pull/2543.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by oddlittlebird — APPROVED** [review]
Huzzah!

**Comment by oddlittlebird** [comment]
Will this require the docs Docker to be rebuilt?

**Comment by robbymilo** [comment]
@oddlittlebird Yes, but if you run the command I mentioned it uses a different image.

**Comment by achatterjee-grafana** [comment]
Looking at this now.

**Comment by robbymilo** [comment]
@oddlittlebird This is ready to go - can you merge? After that I'll merge https://github.com/grafana/website/pull/2543.

**Pull request merged**
