### PR TITLE
Typo fix in User API doc example

### PR DESCRIPTION
**Pull request by nextMJ**
Very small typo fix in [doc](https://grafana.com/docs/grafana/latest/developers/http_api/user/). No need for additional description.

### CODE REVIEW

**Review by Eve832 — APPROVED** [review]

**Comment by nextMJ** [comment]
May I help somehow? But it looks as an internal problem.

**Comment by nextMJ** [comment]
@Eve832 may I help somehow?

**Comment by Eve832** [comment]
@jdbaldry any idea why this didn't auto-merge? I approved it months ago. Just updated backport labels/milestone today

**Comment by jdbaldry** [comment]
Screenshot 2024-04-23 at 17 18 37

Unfortunately the CI was still pending because it needs approval. I can approve it and assuming it passes this should merge.

**Pull request merged**
