### PR TITLE
Explore: updates clear all button to responsive button

### LINKED ISSUE #19352: Explore: Toolbar's Clear all not responsive
This toolbar is getting busier and looks messy in split views:

Screenshot 2019-09-24 at 10 40 41

Clear all could use an icon.

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Explore: updates "clear all" button to responsive button.

**Which issue(s) this PR fixes**:

Fixes #19352

### CODE REVIEW

**Comment by Estrax** [comment]
@kaydelaney @davkal wdyt?

**Comment by Estrax** [comment]
One test failing, as same as in #19710 - @ivanahuckova already made a fix: #19711

**Comment by ivanahuckova** [comment]
@Estrax The PR fixing that test has been approved and just merged to the master. 🙂

**Comment by davkal** [comment]
Looks good already, and code as well. 

Can we fix two things though (either this PR or a new one):

- the icons are vertically not aligned well with the text, perhaps 1 or 2 px off
- there is a bit too much padding on left/right when only the icon is shown
Screenshot 2019-10-09 at 09 44 56

**Review by davkal — APPROVED** [review]

**Comment by Estrax** [comment]
@davkal both fixed. There's still a need to move a zoom out icon by 1px or 2px to the top, but that will require an update of the time picker and a check if it doesn't break anything on the other pages (I don't think a hacky workaround with styles applying to this specific page is going to be a good solution).

Screenshot from 2019-10-10 10-23-36
Screenshot from 2019-10-10 10-23-25

**Comment by davkal** [comment]
LGTM. Feel free to merge this.

**Pull request merged**
