### PR TITLE
update minimum supported version for MySQL

### PR DESCRIPTION
**Pull request by irenerl24**
This PR bumps the minimum supported version of MySQL from 5.0 to 8.0 in the documentation of Grafana

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by jdbaldry — APPROVED** [review]
Thanks!

Do you know from which version of Grafana this support changed?

Do you also happen to know what changed in Grafana that prompted the bump?

Actually, following the MySQL link, it seems like maybe we just support the versions that MySQL themselves support?

**Comment by irenerl24** [comment]
this all comes from [this slack thread](https://raintank-corp.slack.com/archives/C036J5B39/p1724373246487489?thread_ts=1724371358.068989&cid=C036J5B39), not sure when it changed exactly

**Comment by jdbaldry** [comment]
> this all comes from [this slack thread](https://raintank-corp.slack.com/archives/C036J5B39/p1724373246487489?thread_ts=1724371358.068989&cid=C036J5B39), not sure when it changed exactly

That makes sense, I think you or I should ask these questions there. We'll need this context in GitHub because the Slack retention will mean that we can no longer refer back to that thread to understand why things changed or how to keep things up to date in the future.

**Comment by irenerl24** [comment]
> Do you know from which version of Grafana this support changed? 

Do you happen to know, @inf0rmer?

**Comment by hairyhenderson** [comment]
One factor is MySQL 5.7 reached EOL last year in October

**Review by inf0rmer — APPROVED** [review]

**Comment by inf0rmer** [comment]
@irenerl24 I can't remember the actual version but it was 9.5 something, I believe?

**Comment by hairyhenderson** [comment]
IIRC it was 9.4... @owensmallwood would remember I think!

**Pull request merged**
