### PR TITLE
Remove duplicate 'enabled' in configuration docs

### PR DESCRIPTION
**Pull request by flygare**

### CODE REVIEW

**Comment by daniellee** [comment]
I'm missing something here. I do not see a duplicate enabled in the smtp section. This PR looks incorrect to me.

**Comment by flygare** [comment]
Ah, you are correct, I missed the smtp tag when reading the docs.

**Comment by flygare** [comment]
@daniellee ,shouldn't the <hr /> tag be used before [smtp] as with [dashboards.json] for consistency?

**Comment by daniellee** [comment]
@flygare yes, good catch. There are a few missing ones on the page. Will fix.

**Pull request closed without merging**
