### PR TITLE
Update mysql.go

### PR DESCRIPTION
**Pull request by junneyang**
when add mysql datasource, it says:
this user requires clear text authentication. If you still want to use it, please add 'allowCleartextPasswords=1' to your DSN
 i suggest add the allowCleartextPasswords=1 as default uri configuration...

### CODE REVIEW

**Review by aknuds1 — CHANGES_REQUESTED** [review]
I'm not sure what causes the need for MySQL clear text passwords, but I don't think it should be hard coded. If we do decide to support this mode, it should most likely be configurable.

**Comment by aknuds1** [comment]
@junneyang Do you know why your MySQL server requires clear text passwords?

**Comment by junneyang** [comment]
> @junneyang Do you know why your MySQL server requires clear text passwords?

because we use a self-signed certificate to connect mysql with SSL:
image

when we use navicate or other mysql client to connect with ssl, it works, but with grafana it fails


@aknuds1
make the option configurable is reasonable

**Comment by junneyang** [comment]
please also ref this issue: #16539
it's the same case for us(allowCleartextPasswords=1)

**Comment by aknuds1** [comment]
> please also ref this issue: #16539
> it's the same case for us(allowCleartextPasswords=1)

Thanks.

**Comment by aknuds1** [comment]
You also need to sign the CLA for us to consider the PR.

**Comment by junneyang** [comment]
> You also need to sign the CLA for us to consider the PR.

i have agreed to the CLA for grafana/grafana just now, thanks

**Comment by aknuds1** [comment]
Do you know why clear text passwords is necessary when you use a self-signed certificate? I didn't get the connection.

**Comment by junneyang** [comment]
> Do you know why clear text passwords is necessary when you use a self-signed certificate? I didn't get the connection between the two.

i do not know the reason a lot, but my operation is:
1、use tsl client auth to connect:
image

2、it says x509: certificate signed by unknown authority
image

3、so i check Skip TLS Verify：
image

4、it says this user requires clear text authentication. If you still want to use it, please add 'allowCleartextPasswords=1' to your DSN

image


so, i do not know how to solve this problem...

**Comment by aknuds1** [comment]
I'm not sure if the need for clear text passwords is necessarily connected to your certificate situation.

**Comment by sakjur** [comment]
Taking a look at this and [client-side cleartext pluggable authentication in the MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/cleartext-pluggable-authentication.html), I think the reasonable thing would be to add this as an option, since if we were to support this by default or as an automatic downgrade, we'd increase the risk of someone getting access to the password by a MITM attack.

There seem to be strong enough reasons (such as the LDAP/PAM cases listed in the docs I linked) to support it, but the combination of increased risks and this not being the typical setup makes a case for not having this on by default.

**Comment by aknuds1** [comment]
@junneyang Can you modify the PR to make this a configurable option instead of hardcoding it?

**Comment by raymondchen625** [comment]
I don't get why there is a connection between clear-text password and TLS either. My guess is the implementation of [MySQL Pluggable Authentication](https://dev.mysql.com/doc/mysql-security-excerpt/5.6/en/pluggable-authentication.html) doesn't support chained plugins. When TLS plugin is used, it assumes this is the only auth plugin and whatever comes out of it must be a clear-text password. That could also explain why it works when TLS is not enabled because the default plugin is mysql_native_password or mysql_old_password. It works fine without allowCleartextPasswords=1.

**Comment by junneyang** [comment]
> I don't get why there is a connection between clear-text password and TLS either. My guess is the implementation of [MySQL Pluggable Authentication](https://dev.mysql.com/doc/mysql-security-excerpt/5.6/en/pluggable-authentication.html) doesn't support chained plugins. When TLS plugin is used, it assumes this is the only auth plugin and whatever comes out of it must be a clear-text password. That could also explain why it works when TLS is not enabled because the default plugin is mysql_native_password or mysql_old_password. It works fine without allowCleartextPasswords=1.

yes, When TLS plugin is used, It must be clear-text password.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
The allowClearTextPasswords setting should be configurable via the data source's UI, not dependent on whether TLS/SSL is used.

**Review by ying-jeanne — COMMENTED** [review]
hi @junneyang it seems e2e test is failing for the build, here is the guideline https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md, section `Run end-to-end tests` you could find how to run in local e2e testing.

**Comment by aknuds1** [comment]
Closing this PR as stale, since there hasn't been activity since January.

**Comment by enginecan** [comment]
I've created https://github.com/grafana/grafana/pull/63232 in an effort to solve this.

**Pull request closed without merging**
