### PR TITLE
Azure Monitor: Fix app insights source to allow for new __timeFrom and __timeTo

### LINKED ISSUE #21860: $__from and $__to don't work in Application Insights datasource
**What happened**:
Using a query that uses $__from or $__to used to result in an application insights query that said something like `datetime(2020-01-30T20:00:00Z)`, now it's just a number.  However, that number is meaningless in application insights, and the backend code here https://github.com/grafana/grafana/blob/20faef8de5fbdaa2395d5097e6d3f862b143f5d1/pkg/tsdb/azuremonitor/macros.go still seems to try to do the datetime replacement.

this query `results | where timesamp>$__from | summarize count() by bin(timestamp, 1m)` returns a "metrics request error" because the number being sent by $__from has no context in AI.

**What you expected to happen**:
The query should return fine, with a pretty boring time series.

**How to reproduce it (as minimally and precisely as possible)**:
Create an Azure Monitor data source pointing to an App Insights instance, change to raw query, and paste  `results | where timesamp>$__from | summarize count() by bin(timestamp, 1m)`

**Anything else we need to know?**:
This appears to have been a change in 6.0, since I'm pretty sure this worked before.  This change is highly suspect: https://github.com/grafana/grafana/issues/1909.

Several queries need the __from and __to, especially if they are using (make-series).  $__timeFilter() wasn't broken, but the make-series command needs the from and to values individually.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Azure Monitor - built in
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None

### PR DESCRIPTION
**Pull request by ChadNedzlek**
**What this PR does / why we need it**:

the change to the meaning of __from broke the app insights data source

https://github.com/grafana/grafana/issues/21860, the proposed "works as intended" doesn't work.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/21860

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Could someone review this? I haven't had any feedback at all on this.

**Comment by ChadNedzlek** [comment]
I'm not getting a lot of traction here... This is a simple fix to a crippling problem... I don't understand what more I need to do.

**Review by daniellee — APPROVED** [review]
Looks good to me. Can add more test after.

**Comment by daniellee** [comment]
Sorry for the delay in reviewing. Tested and it works. The test coverage is lacking for the macros which is why this slipped through so some follow up work to do on this.

**Pull request merged**
