### PR TITLE
Server: Switch from separate server & cli to a unified grafana binary

### PR DESCRIPTION
**Pull request by DanCech**
This PR is an investigation into whether we can optimize our download packages and docker images by compiling a single binary for grafana instead of separate grafana-server and grafana-cli binaries that contain much of the same code.

The current approach is to replace grafana-cli with a small binary that locates and executes the grafana-server binary while setting `argv[0]` to "grafana-cli".  grafana-server in turn detects this and runs the grafana-cli instead of the regular server.

This change by itself will save us over 65MB in each of our download packages.

Another alternative approach would be to do away with the separate binaries altogether and simply have a single `grafana` binary that detects the desired operation mode via `argv[1]`, so instead of executing `grafana-server` or `grafana-cli` the user would run `grafana server` or `grafana cli`.

This would simplify things even further and avoid the need for the helper binary, but would require changing the commands used to start grafana.

Another alternative I explored was to do away with the grafana-cli binary and instead symlink grafana-cli to grafana-server (to avoid the ~1.3MB helper) but I ran into more packaging challenges trying to get the symlinks to work properly.

### CODE REVIEW

**Comment by ryantxu** [comment]
does this mean we can get rid of the second wire dependency graph?

**Comment by hairyhenderson** [comment]
> but I ran into more packaging challenges trying to get the symlinks to work properly.

I guess this would be especially an issue in Windows?

> Another alternative approach would be to do away with the separate binaries altogether and simply have a single `grafana` binary that detects the desired operation mode via `argv[1]`,

IMO this is ideal, but obviously a breaking change that would need to wait for Grafana 10 or later. I wonder if a incremental step (in a followup PR) would be to allow `grafana-server` to be called with subcommands (`grafana-server server`/`grafana-server cli`) - then we could symlink `grafana` to it to help with the transition... Just a thought.

**Comment by DanCech** [comment]
> does this mean we can get rid of the second wire dependency graph?

Right now I haven't changed anything related to wire, will need more investigation.

> > but I ran into more packaging challenges trying to get the symlinks to work properly.
> 
> I guess this would be especially an issue in Windows?

Yeah, also the tarball handling is a bit strange.  Generally it seems like wrapper scripts are going to be easier to reason about.

> > Another alternative approach would be to do away with the separate binaries altogether and simply have a single `grafana` binary that detects the desired operation mode via `argv[1]`,
> 
> IMO this is ideal, but obviously a breaking change that would need to wait for Grafana 10 or later. I wonder if a incremental step (in a followup PR) would be to allow `grafana-server` to be called with subcommands (`grafana-server server`/`grafana-server cli`) - then we could symlink `grafana` to it to help with the transition... Just a thought.

Yes and no, we could provide wrappers that implement the `grafana-server` and `grafana-cli` commands and just call the new `grafana server` or `grafana cli` command to provide BC in the same way that I'm providing BC currently via the grafana-cli wrapper.  To save space on linux we could use a simple shell script instead of the relatively heavy golang wrapper (~1.4MB), though for windows we'd need to stick with the go afaik to avoid changing the filenames (vs say switching to grafana-cli.bat) though I'm open to suggestions there too.

**Comment by hairyhenderson** [comment]
> Yes and no, we could provide wrappers that implement the `grafana-server` and `grafana-cli` commands and just call the new `grafana server` or `grafana cli` command to provide BC in the same way that I'm providing BC currently via the grafana-cli wrapper. To save space on linux we could use a simple shell script instead of the relatively heavy golang wrapper (~1.4MB), though for windows we'd need to stick with the go afaik to avoid changing the filenames (vs say switching to grafana-cli.bat) though I'm open to suggestions there too.

Ah, yeah this sounds like a fine idea to me. 👍

As a deprecation process the wrappers could print warnings, and then eventually just fail once we're ready to totally move over to the single binary.

**Comment by DanCech** [comment]
The latest commit explores how we could move to a single `grafana` binary and just keep grafana-cli and grafana-server as BC helpers.

It's implemented by converting both grafanacli and grafana-server into commands in a new cli app.  For the cli this works natively but the server uses flags rather than urfave/cli so it is just implemented as a command that dispatches to the existing RunServer function after trimming off the extraneous "server" command-line argument.  We could potentially migrate the server over to urfave/cli as well which would tidy things up a bit.

There's still work needed to update all the build scripts, dockerfiles, etc.

**Comment by DanCech** [comment]
This is now at a point where we can build working packages that are fully backward compatible, there is still a lot more work we can do to clean up and unify things like command-line parsing and wire, but I think that's best left to follow-up PRs.

**Review by zserge — APPROVED** [review]

**Comment by andresmgot** [comment]
hey @DanCech, it seems this change caused that the [VScode debugger conf](https://github.com/grafana/grafana/blob/main/.vscode/launch.json#L9) no longer works. First it returns an error:

```
Error locating grafana: exec: "grafana": executable file not found in $PATH
```

If you add the grafana `bin` folder to the PATH, it doesn't fail but since I believe the code now just spins a new process executing the binary, breakpoints doesn't work. Is there any way of running the grafana-server directly?

**Pull request merged**
