### PR TITLE
CloudWatch: Enable Min time interval

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
Enable min_interval for CloudWatch

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/20259

### CODE REVIEW

**Comment by mtanda** [comment]
I know. I don't want to disturb his work.
@sunker Please consider to include this and https://github.com/grafana/grafana/pull/20263 for v6.5 release.

**Review by sunker — APPROVED** [review]
It looks good @mtanda. We'll aim for 6.5-beta2 on this one.

**Comment by torkelo** [comment]
Should it not also be set on datasource level to define the 1m minimum? 

Just set this.interval = '1m'  to define a global minimum 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/PanelQueryRunner.ts#L138

But is there no metrics that can go below 1m resolution?

**Comment by mtanda** [comment]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html#high-resolution-metrics
Custom Metrics resolution could be 1 second.

**Comment by sunker** [comment]
@torkelo @mtanda is this ready for 6.5-beta2?

**Comment by mtanda** [comment]
@sunker Of course, I'm ready :-)

**Comment by mtanda** [comment]
thanks!

**Pull request merged**
