### PR TITLE
1578 shared tooltip v2

### PR DESCRIPTION
**Pull request by gbrian**
https://github.com/grafana/grafana/issues/1578

### CODE REVIEW

**Comment by RichiH** [comment]
@bergquist Any timeline for merging this? This is very useful.

**Comment by bergquist** [comment]
I'm not 100% sure about merging this. I like the idea but the implementation feels unpolished and clunky. The shared tool-tip placement feels a bit off. I'm not sure about how to improve it either. 

Perhaps it would be possible to get the same effect by having a "hover" value in the legend that would updated dashboard wide.

**Comment by gbrian** [comment]
@bergquist agree, i did my best with the knowledge I have but I agree there should be a better way.
Suggestions are welcome. BTW any part of the implementation that can be moved/refactor ?
Thanks

**Comment by utkarshcmu** [comment]
@torkelo Any suggestions to refactor the code in this PR? This seems to be a very useful feature.

**Comment by torkelo** [comment]
Will take a look

**Comment by bergquist** [comment]
I do understand the need for this feature but I dont think the implementation is good enough for be merge at the moment.  Unless we find a better way to implement this I will close this PR within a few days.

**Comment by zdrummond** [comment]
@bergquist I am interested why you think this is clunky? New Relic dashboard do the same thing and it works great. 

Would your concern be alleviated if this feature was activated by holding a key down?

**Comment by torkelo** [comment]
closing this as it's a bit too old (too many conflicts with master). Sorry for being slow to merge this but we are not sure about this feature, I mean we are sure it's useful but not sure how to best implement it, with minimal added code complexity, and also performance

**Comment by torkelo** [comment]
This feature is now in master, merged via this PR #6274, with some changes.

The feature is using the sharedCrosshair option (renamed in UI to Shared tooltip), and the same shortcut (CTRL+O, or CMD+O)

**Pull request closed without merging**
