### PR TITLE
WIP Karma to Jest: heatmap renderer (refactor)

### PR DESCRIPTION
**Pull request by tskarhed**
Ref #12224 
Refactor of heatmap renderer, in same fashion as #12860.

All the current tests check for ticks which are generated in D3; does this test the relevant functionality? One solution could be to mock D3 and check the input data instead. Any thoughts?

@alexanderzobnin @torkelo @davkal @marefr 

Also: last Karma test to be converted. Yay!

### CODE REVIEW

**Comment by davkal** [comment]
It's certainly beneficial to check if the correct number of ticks is being generated and that they are coming out in the right markup with the correct CSS classes attached. The heatmap render class seems to be well-abstracted to wrap it in a react container, to be rendered by the react-test-renderer and then to be snapshot. I'd even spend a good day on this.
If this is a dead end, i'd continue extracting and purifying (no closure variables) the calculation functions and test those. IMO I'm happy to drop tests so we can finish this project, perhaps others have different opinions.

**Comment by dehrax** [comment]
Okay, I am trying this approach. If not done until Wednesday, we drop the test.

**Comment by torkelo** [comment]
the ticks are not generated by d3 (directly), but by the ticks utils 
https://github.com/grafana/grafana/blob/master/public/app/core/utils/ticks.ts 

which has tests as well. 

Not sure converting heatmap to react in order to complete this test is worth it (right now), think that could potentially take many days.

**Comment by dehrax** [comment]
I'm okay with dropping the test. I am assuming this will get new tests once converted to React. I take it most people are comfortable with just going with the refactor right now? If nobody disagrees I'll finish it up first thing tomorrow.

Maybe the React conversion should be part of a bigger conversion strategy?

**Review by marefr — APPROVED** [review]
LGTM and seems to work as expected

**Pull request merged**
