### PR TITLE
Elasticsearch: Added support for calendar_interval in ES date histogram queries

### PR DESCRIPTION
**Pull request by NikolayTsvetkov**
**What is this feature?**

Elasticsearch: Add support for calendar interval in date histogram queries

**Why do we need this feature?**

Since introducing the fixed_interval as the only option replacing the "interval" in the ES date histogram queries, Grafana has lost the functionality of serving plots with long aggregation intervals (1 week, 1 month, 1 year) accurately, and that was a breaking change for many users (some still forced to use Grafana v9). This missing functionality was mentioned in several issues and it has been discussed in https://github.com/grafana/grafana/discussions/55034

Currently only workaround is possible using 30d/365d but this is not accurate and the resulting bins are not matching the calendar intervals precisely.

**Who is this feature for?**

Users of Elasticsearch datasource queries aiming to do aggregation over longer intervals (1w, 1M, 1q, 1y) that are not supported within the ES fixed_interval range.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-aggregation

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Provides accurate aggregation intervals and remove the need of using 30d/365d workaround that creates wrong results.

Please check that:
- [X] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by matyax — COMMENTED** [review]
Just tested this, both with and without backend querying (feature flag `enableElasticsearchBackendQuerying = true `) and works as expected. There are some minor things to fix though.

**Comment by NikolayTsvetkov** [comment]
> Just tested this, both with and without backend querying (feature flag `enableElasticsearchBackendQuerying = true `) and works as expected. There are some minor things to fix though.

Hi @matyax, Thank you for the review! The comments have been addressed and it should be good to go now :)

**Comment by matyax** [comment]
Thank you! Looking at it shortly.

**Review by matyax — APPROVED** [review]

**Comment by matyax** [comment]
Thank you very much for this contribution and the follow up @NikolayTsvetkov . Don't hesitate to keep them coming.

**Pull request merged**
