### PR TITLE
devenv: Solving two of the code scanning fails

### PR DESCRIPTION
**Pull request by daniellee**
Removes new lines from user input that is logged. Fixes CWE-117 from CodeQL.

ref #43080

### CODE REVIEW

**Comment by daniellee** [comment]
Need to add also do a safe version of r.Header - these changes weren't enough.

**Comment by marefr** [comment]
Since this is devenv one alternative would be to add a `nolint` comment if it's tricky to solve

**Comment by daniellee** [comment]
@marefr I made the changes we discussed yesterday and instead comment out the logging of the request headers.

I kept the logging of the sleep and request url though as they are useful when using the slow proxy so that you know that you have configured it correctly and that requests are being proxied through it.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by daniellee** [comment]
It only solved one of the alerts. Will create a new PR to fix https://github.com/grafana/grafana/security/code-scanning/197?query=ref%3Arefs%2Fheads%2Fmain

**Pull request merged**
