### PR TITLE
refactoring: enterprise build/hooks refactorings

### PR DESCRIPTION
**Pull request by torkelo**
Some refactorings for working with enterprise build.

### CODE REVIEW

**Comment by mev** [comment]
I can't get any Grafana to work from this commit forward (I'm following the procedure from http://docs.grafana.org/project/building_from_source/ and everything works perfectly before this commit).

When I build Grafana with this commit, when I'm trying to open http://localhost:3000/, I'm getting the following error: "template: index:68:64: executing "index" at <.AppName>: can't evaluate field AppName in type *dtos.IndexViewData"

**Comment by torkelo** [comment]
Strange, how are you building Grafana? Looks like you need to rebuild the backend (not only the frontend)

**Comment by mev** [comment]
The first time I did it I followed to the letter the procedure from http://docs.grafana.org/project/building_from_source/

On that codebase I worked on some modifications. After I finished developing my modifications I decided that I shouldn't keep it local but save it on GitHub. So I forked grafana/grafana to mev/grafana and cloned the repository by doing:

`git clone git@github.com:mev/grafana.git mev_grafana`

in the same directory where I had already grafana/grafana cloned (so the rest of the Go environment and paths stay the same). Then, in `mev_grafana` I did:

`go run build.go setup`
`go run build.go build`
`yarn install --pure-lockfile`
`npm run watch` (in a terminal)
`~/go/bin/grafana-server` (in a second terminal)

At this I got the error I was mentioning when trying to open `localhost:3000`. I searched where there was any mention of `IndexViewData`, which got me to `pkg/api/dtos/index.go`, which got me to this commit, so I checked out the last commit before it, ran the previous commands and it just worked. So, unless I'm not getting this right (`go run build.go setup` and `go run build.go build` are building the backend from what I understand right now, right?), I have been rebuilding the backend. Am I doing something wrong? Am I missing something?

**Comment by torkelo** [comment]
It’s just super strange in that case, as no one else has reported issues building and running grafana. Same commands is used to build grafana nightly and they work fine.

I think I see your issue your running an old binary, the binary names produced by go run build have. Changed,

**Comment by mev** [comment]
I just double-checked and there is no other binary apart from `grafana-server` in `~/go/bin/`. What is the new binary supposed to be named?

**Comment by mev** [comment]
I figured it out.

It was a problem with rebuilding the backend. Because I cloned the Grafana repository in a new folder called `mev_grafana`, the paths in the import statements weren't matching any more (because they're relative to `${GOPATH}/src/`not to the Grafana root folder. Now I renamed the folders, it built the backend without any problems and it works perfectly.

**Pull request merged**
