### PR TITLE
Docs: Fix relrefs in access control API docs

### PR DESCRIPTION
**Pull request by gguillotte-grafana**
**What this PR does / why we need it**:

Fix broken relrefs in the access control API docs, so the links work in the published docs.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

None

### CODE REVIEW

**Comment by gguillotte-grafana** [comment]
Trying to figure out the Prettier failure; the message dropped in CI is useless, `yarn run prettier:checkDocs` locally produces nothing, `yarn prettier -c .` in `docs/` returns "All matched files use Prettier code style!".

cc @jdbaldry

**Comment by gguillotte-grafana** [comment]
Any clues on interpreting this or getting more details? Or why CI is blocking on a `warn`-level check?

```
$ yarn run prettier:checkDocs
[warn] docs/sources/developers/http_api/access_control.md
[warn] Code style issues found in the above file. Forgot to run Prettier?

$ yarn prettier -c .
Checking formatting...
[warn] sources/developers/http_api/access_control.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

**Comment by gguillotte-grafana** [comment]
Running with `--write` results in a lot of table formatting changes unrelated to the changes in this PR.

**Comment by gguillotte-grafana** [comment]
Drone is satisfied after adding 9ccce9f1 that includes the changes from `prettier --write`, but I'm still frustrated that Prettier can block CI over a warning about unrelated table formatting that isn't broken, and that CI (or Prettier) can't output anything more specific about Prettier's complaints than the affected file's name. cc @jdbaldry

**Comment by jdbaldry** [comment]
If I understand correctly, `prettier` failed in CI because the file with changes wasn't formatted with `prettier` either through `yarn prettier:write` or otherwise. The table formatting is a bit of form over function thing but since it can be auto-formatted, I don't mind enforcing the consistency. 

I have my editor run `prettier` on save so that I tend to not have to worry about any of the linting concerns.

In general, I prefer enforced linting over warnings because the consistent style is useful for readability across contributors. Without enforcement, consistency and style degrades quickly.

**Comment by gguillotte-grafana** [comment]
Removing Jack as he's out, adding @chri2547

**Review by chri2547 — APPROVED** [review]

**Pull request merged**
