### PR TITLE
Implements issue #9473

### PR DESCRIPTION
**Pull request by omki2005**
This implements #9473

### CODE REVIEW

**Comment by torkelo** [comment]
could you update/add a unit test for this?
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/specs/query_builder_specs.ts

**Comment by omki2005** [comment]
added

**Comment by omki2005** [comment]
Bump. Looks good?

**Comment by kichristensen** [comment]
Any update on this? I would really like to get this feature too

**Pull request merged**
