### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by RubenGamezTorrijos**
Hello, I would love to be able to belong to the Grafana community, and to be able to contribute to the translation of Grafana. It would be an honor to be able to help in any way I can. Thanks to the Grafana team.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by RubenGamezTorrijos — COMMENTED** [review]
New changes made in Spanish translation.

**Comment by mellieA** [comment]
@RubenGamezTorrijos thank you for contributing! I've moved this PR for review by the user-essentials squad that is working on translations.

**Comment by joshhunt** [comment]
Thanks for the contribution. We're not quite ready to accept outside contributions for translations (we should make that clear!) yet, but I don't want to lose the work here. 

I'll keep this open until we can find a way forward with these.

**Comment by joshhunt** [comment]
Again, thanks for the contribution, but we're currently not accepting translations from the community. We will be handling the translation for the first batch of languages, and hopefully sometime later have a process for community translations.

Sorry for the waste of effort on this one - we've updated our contributors and internationalisation documentation to make it clear that we're not accepting contributions for these at the moment.

**Pull request closed without merging**
