### PR TITLE
Parca: Use client dependency from buf.dev instead of generated sources

### PR DESCRIPTION
**Pull request by aocenas**
The same client that we generated manually before is actually available from buf.dev directly as a go module which makes handling this dependency easier.

### CODE REVIEW

**Review by joey-grafana — COMMENTED** [review]
Ok so I mean this works even though there are errors. Not sure why

Screenshot 2023-01-05 at 14 47 20

**Comment by joey-grafana** [comment]
It builds and runs with no errors and works great on the frontend and the code looks good. 

To be clear, we're not actually generating any code anymore (so don't need a readme)?

**Comment by aocenas** [comment]
@joey-grafana yes the readme isn't part of this PR anymore

**Review by marefr — APPROVED** [review]
Seems to work for me

**Pull request merged**
