### PR TITLE
Chore: Bump typescript version to 4.7.4

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Bumps typescript version from 4.6.4 to 4.7.4

### CODE REVIEW

**Comment by leventebalogh** [comment]
Levitate probably complains because there are some new features in this new TypeScript version, and it looks like optional function arguments (or at least some of them) get compiled differently (probably not a problem, but probably worth to know).

There was a previous Renove PR (#50847) which was trying to the same upgrade, but we decided not to merge it yet, and also a [Slack thread](https://raintank-corp.slack.com/archives/C01C4K8DETW/p1657107082312039), just linking them here for more information.

**Review by dprokop — APPROVED** [review]
Always happy to see those PRs :)

**Comment by kaydelaney** [comment]
Reverted the eslint-plugin-react upgrade as there is an issue with the react/display-name rule reporting false positives: https://github.com/jsx-eslint/eslint-plugin-react/issues/3300

**Comment by kaydelaney** [comment]
@leventebalogh Do you think this is okay to merge?

**Review by ivanortegaalba — APPROVED** [review]
Thanks, @kaydelaney for this upgrade!
* I ran locally the build, and the type checks, and no new warnings were found. So all should be ok with it
* The Levitate (BTW, really cool tool, I didn't know it) detects there is a change in how TS defines optional arguments. Before they were accepted as `undefined`, and now they are not. If we want to be 100% backward compatible, we can disable [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes) which enforces optional values to either have a value or not appear. Enable this rule is recommended, and I think if we can enforce it, it is ok to be safer when searching for a key in an object or operations like that.

From my side, LGTM!

**Review by leventebalogh — APPROVED** [review]
Thanks for bumping everything @kaydelaney!

Tested it out locally as well, looks good to me, too 👍

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
