### PR TITLE
Chore: Avoid explicit React.FunctionComponent<Props> when possible (round 3)

### PR DESCRIPTION
**Pull request by ryantxu**
Continuing... https://github.com/grafana/grafana/pull/64722

This PR replaces most explicit uses of React.FC with a typed function.

The explicit FC components exist everywhere so are often used as the copy from source :(

See:
* https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13
* https://github.com/facebook/create-react-app/pull/8177

### CODE REVIEW

**Review by leventebalogh — APPROVED** [review]
Nice one, LGTM! 🚀

**Comment by gabor** [comment]
logs things (logs-panel and elastic-datasource) are ok 👍

**Review by aangelisc — APPROVED** [review]
Azure LGTM 😊

**Review by nmarrs — APPROVED** [review]
✨

**Pull request merged**
