### PR TITLE
NestedFolders: Basic item selection

### PR DESCRIPTION
**Pull request by joshhunt**
Adds basic item selection state + logic to the nested folder tree

5137_2023-04-19-12-32_firefox

When selecting (or unselecting) an item we recursively set the state for all child items as well. We do this (instead of just storing state for items the user clicks on and _deriving_ children's checked state) because we also need to be able to unselect a child after selecting a parent, which becomes difficult if we don't actually store that the item is selected.

When loading children, we check if it's parent is selected so any those children will also be selected.

Now that there's a lot more state logic in here, and im pulling in immer myself, I think i want to store this in Redux instead.

Functionality in this PR:
 - Select and unselecting an item
 - Selecting an item selects all descendants, even descendants that aren't loaded yet
 - Unselecting an item unselects all descendants also
 - Unselecting an item unselects it's parent

To come in later PRs:
 - Indeterminate/mixed states
 - Move delete actions/logic

TODO:
 - [x] Tests (again - [I had written a whole bunch](https://github.com/grafana/grafana/commit/133a7e4ad23d026a427d21fc689f42057ecdb151#diff-c9efdb72fae6ebf04058787e16f8531651cc205a5431af5b4433b974b1a44844) but had to throw them out when I changed state stuff)
 - [x] Unselecting an item unselects it's parent

Part of #65604

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
Code looks good from my perspective!

Just trying to understand what the select process will be in the end, mainly for when we add the actions:
- If we select a folder, it selects all children, if we then delete it deletes the whole folder (+ children)
- If we select a folder, it selects all children, then we deselect a child, it will only delete the children that are still selected

Is this correct?

**Comment by joshhunt** [comment]
Yup @JoaoSilvaGrafana that sounds right.

**Comment by JoaoSilvaGrafana** [comment]
> oh, a point to clarify @JoaoSilvaGrafana -
> 
> > If we select a folder, it selects all children, if we then delete it deletes the whole folder (+ children)
> 
> When we go to perform this delete, we should identify that Folder A and all children are selected, and only issue a single DELETE for Folder A. The backend will cascade this and recursively delete all children.

Ah makes sense! 👍

**Review by JoaoSilvaGrafana — APPROVED** [review]
lgtm! 👏

**Pull request merged**
