### PR TITLE
Packaging: removes an unused dependency

### LINKED ISSUE #31346: Distribution: deb install fails on Rasperry Pi OS Lite due to missing libfontconfig1
**What happened**:

Debian install fails on raspberry pi due to missing `libfontconfig1` dependency.

**What you expected to happen**:

Successful install.

**How to reproduce it (as minimally and precisely as possible)**:

```
pi@raspberrypi:~ $ sudo apt-get install -y grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
grafana : Depends: libfontconfig1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

crazy that it does not seem to be possible to install libfontconfig1 at all:
```
pi@raspberrypi:~ $ sudo apt-get install libfontconfig1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libfontconfig1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libfontconfig1' has no installation candidate
```

**Anything else we need to know?**:

hi @xlson I just wonder if there are people requested about this issue?
I just run into the same problem: following your tutorial https://grafana.com/tutorials/install-grafana-on-raspberry-pi/#3 but when it comes to install I just get this error

is this something (really) needed by Grafana?

I was able to download and install directly via
curl -o grafana-7.4.0.linux-armv7.tar.gz https://dl.grafana.com/oss/release/grafana-7.4.0.linux-armv7.tar.gz
and start via ./bin/grafana-server but I'm unsure about installation-scripts and system service registration etc.

Thanks for some thoughts and please let me know, if it's just a too stupid comment, so I will delete for sure…

**Environment**:

Debian on Raspberry Pi

- Grafana version: latest
- OS Grafana is installed on:
```
pi@raspberrypi:~ $ uname -a Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
pi@raspberrypi:~ $ lscpu Architecture: armv7l Byte Order: Little Endian CPU(s): 4 On-line CPU(s) list: 0-3 Thread(s) per core: 1 Core(s) per socket: 4 Socket(s): 1 Vendor ID: ARM Model: 3 Model name: Cortex-A72 Stepping: r0p3 CPU max MHz: 1500.0000 CPU min MHz: 600.0000 BogoMIPS: 270.00 Flags: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

### PR DESCRIPTION
**Pull request by xlson**
**What this PR does / why we need it**:

`libfontconfig1` was a dependency of `phantomjs` but since we don't use it anymore there's no reason for our rpm and deb packages to depend on it.

**Which issue(s) this PR fixes**:

Fixes #31346

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dsotirakis — CHANGES_REQUESTED** [review]
@xlson, thanks for working on that!

There are some other places as well that need visiting I guess.

* `build/ci-build/Dockerfile`
* `docs/sources/debian.md`
* `docs/sources/upgrading.md`
* `packages/grafana-toolkit/docker/grafana-plugin-ci-e2e/scripts/deploy-slim.sh`
* `packages/grafana-toolkit/docker/grafana-plugin-ci/scripts/deploy/sh`

**Comment by xlson** [comment]
@dsotirakis Silly me, I ran find to check if it was used somewhere else but I must have misspelled libfontconfig :sweat_smile: I'll fix it.

**Comment by xlson** [comment]
@dsotirakis are you sure about the grafana-toolkit scripts? It doesn't necessarily seem directly related to the grafana phantomjs usecase so I think there could be another use there.

**Comment by dsotirakis** [comment]
> @dsotirakis are you sure about the grafana-toolkit scripts? It doesn't necessarily seem directly related to the grafana phantomjs usecase so I think there could be another use there.

@xlson, not at all, not familiar with it you know better!

**Review by dsotirakis — APPROVED** [review]

**Pull request merged**
