### PR TITLE
Tempo: Add migration to enable TraceQL streaming for Tempo datasources

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

As we plan to remove the `traceQLStreaming` feature toggle to replace it with a datasource config, we want to migrate the instances that have the feature toggle enabled to automatically enable the datasource config for all Tempo datasources available. 

Related to https://github.com/grafana/grafana/pull/88685

**Why do we need this feature?**

To automatically enable streaming if the feature toggle is enabled.

**Who is this feature for?**

Tempo datasource users

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ifrost** [comment]
Tested it locally and it nicely updates settings in all data sources (if streaming wasn't set up explicitly to true or false before). It also runs the migration only once the toggle is enabled. Non-provisioned data sources that are deleted during provisioning are not changed as they override themselves.

I wonder if it'd be good to already change the defaults for newly added data sources (should help with provisioned as well) 🤔 At the moment once the migration is run, any new data source will still have streaming disabled.

Also a question - it updates settings in all datasources - would it cause any issues if streaming is enabled for customers using Tempo 1?

**Review by ifrost — APPROVED** [review]

**Comment by 09jvilla** [comment]
> @09jvilla I included a change in this PR to require the datasource level config OR the feature toggle, instead of requiring both to be enabled for streaming to work.

Ack Andre. Thanks for the heads up. Will work with Kim to update docs accordingly.

**Comment by knylander-grafana** [comment]
I"ll update the docs in this PR: https://github.com/grafana/grafana/pull/91704

I'm already updating the data source docs.

**Comment by 09jvilla** [comment]
Glad to see this already merged. Just wanted to add LGTM. :)

**Pull request merged**
