### PR TITLE
Graph: Improves graph edit options in side pane

### PR DESCRIPTION
**Pull request by torkelo**
And some color alignments in graph legend table 

Screenshot from 2020-05-06 17-36-27

### CODE REVIEW

**Review by mckn — APPROVED** [review]
Looks really good! Great work!

One tiny thing that can improve this is to get the units "dropdown" aligned with the rest of the forms. It looks a little bit wider then the other fields.

**Comment by mckn** [comment]
> Looks really good! Great work!
> 
> One tiny thing that can improve this is to get the units "dropdown" aligned with the rest of the forms. It looks a little bit wider then the other fields.

Looks like there is a `margin-right: 4px` that is causing this issue.

**Comment by mckn** [comment]
> > Looks really good! Great work!
> > One tiny thing that can improve this is to get the units "dropdown" aligned with the rest of the forms. It looks a little bit wider then the other fields.
> 
> Looks like there is a `margin-right: 4px` that is causing this issue.

Not sure this is the best way but adding the following to `_gf-form.scss` seems to do the trick:

```scss
.editor-row {
  .gf-form-input,
  .gf-form-select-wrapper {
    margin-right: 0;
  }
}
```

**Comment by torkelo** [comment]
that will break a lot of margins in other scenarios where it is required

**Pull request merged**
