### PR TITLE
Support pin dashboard submenu bar.

### PR DESCRIPTION
**Pull request by xiaobeiyang**
### What would you like to be added:
Support pin submenu(variables and links bar) on top of dashboard.

### Why is this needed:
When I have a long dashboard, I have to scroll up and down when I need to re-select variable values.

### CODE REVIEW

**Comment by xiaobeiyang** [comment]
Please help review, implement FR https://github.com/grafana/grafana/issues/11166

**Comment by hugohaggmark** [comment]
Thanks for this PR, we're thinking about introducing a lot of improvements to the UX of the whole variable system. We'll take this design solution with us in that upcoming work but we're going to close this PR for now.

All the best  

@jessover9000 @pkolyvas

**Comment by xiaobeiyang** [comment]
Hi @hugohaggmark
   Is there any rough schedule about the improvements of variable system? We have many long dashboards and really expect the new feature.

**Comment by hugohaggmark** [comment]
@xiaobeiyang no schedule yet, we're still doing research. Would you like to be part and help out with the research?

**Comment by xiaobeiyang** [comment]
> @xiaobeiyang no schedule yet, we're still doing research. Would you like to be part and help out with the research?

@hugohaggmark I have no sense of research work. But I can provide 2 requirements we have about variables.

1. User can pin menu bar at dashboard top.
2. Better to have a way of showing each panel refers to which variables, or support panel level variables.

**Comment by hugohaggmark** [comment]
Thank you for that feedback @xiaobeiyang, you can click on the show usages button: 
image

to show where the variable is used:
image

**Comment by Mario-Hofstaetter** [comment]
> Thanks for this PR, we're thinking about introducing a lot of improvements to the UX of the whole variable system. We'll take this design solution with us in that upcoming work but we're going to close this PR for now.
> @jessover9000 @pkolyvas

@hugohaggmark Any news / results on the mentioned resource? Pinning the variable toolbar does not seem to be available in Grafana 9.0 still 😞 

The browser userscript mentioned in #11166 unfortunately does not work 100% in Grafana 8 / 9, the top bit of panels is overlapped by the floating variable panel... (will ask for help on that in the issue).

There does not seem to be any difference in Grafana 9 regarding the variables toolbar? <https://play.grafana.org/d/000000063/prometheus-templating>

**Pull request closed without merging**
