### PR TITLE
Testdata: generate data that can link to USA state codes

### PR DESCRIPTION
**Pull request by ryantxu**
While working on https://github.com/grafana/grafana/pull/36188, it will be important to sort how how we handle mapping response values to defined geographic regions.

This PR adds a new query type that will generate a variety of response flavors we can use in a spatial (or categorical) map.

At this stage, I am less concerned with how the values behave and more in getting a variety of layouts that should work.  The timeseries values will eventually be able to do something like:
https://grafana.com/grafana/plugins/citilogics-geoloop-panel/

### CODE REVIEW

**Comment by ryantxu** [comment]
@kylebrandt @sdboyer -- I'm tagging you here to help think about how this relates to "types".  Don't look at the code -- just the outputs in the `*.txt` files

**Comment by kylebrandt** [comment]
> @kylebrandt @sdboyer -- I'm tagging you here to help think about how this relates to "types". Don't look at the code -- just the outputs in the `*.txt` files

This looks okay to me. Structure seems to line up with what I expect from Backend SDK / SSE in terms of Labels. SSE itself doesn't handle multi-metric queries (so it expects one metric from a query in the sense of the "foo" metric, but can have different labels). So that is something it doesn't logically really support at the moment.

What I am unsure of is naming in terms of Frame name vs Field Names and when we should put what where.

**Review by marefr — APPROVED** [review]
LGTM

Not really an strong opinion of data formats and such, but this is something we could iterate on starting to use this scenario?

**Comment by ryantxu** [comment]
> but this is something we could iterate on starting to use this scenario?

Exactly!

**Pull request merged**
