### PR TITLE
Logs: Center `show context` modal on click

### LINKED ISSUE #51150: Show context modal and related log line will automatically scroll up to the center of the screen
### Background / Why we're doing this

**Problem**
Today the user can hover over a filtered log line and click on the button "show context" and a modal will appear. The "show context" modal is attached to the log line, therefore if the related log line appears towards the bottom of the screen, then the modal will also appear towards the bottom of the screen. 

This makes sense given that we want to locate the modal window around the actual log line that the 'context' belongs to, rather than a random line in the middle of the page. 

However, a downside of this is that when the user clicks show context on a line towards the bottom of the screen, the modal gets truncated, forcing the user to scroll down to see the entire modal window. 

Bildschirmfoto 2022-06-21 um 11 00 51
Bildschirmfoto 2022-06-21 um 11 03 26

### Deliverables

**Proposal**
We'd like the "show context" modal and the related log line to automatically scroll towards the center of the screen once the user clicks the "show context" button.

In this way, the modal remains centered around the log line that it is related to, but the user also has the modal front and center in their screen and doesn't have to scroll up or down to be able to see all the context lines. 

Bildschirmfoto 2022-06-21 um 11 00 51
Bildschirmfoto 2022-06-21 um 11 00 59

### PR DESCRIPTION
**Pull request by svennergr**
**What this PR does / why we need it**:
The modal opened by the `show context` button should be centred when clicked. Added this by scrolling the clicked element into view using https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView.

**Which issue(s) this PR fixes**:

Fixes #51150

**Special notes**:

Behavior on current main:

https://user-images.githubusercontent.com/8092184/191056244-fec61f33-1bba-46f2-8a26-96f25f418057.mov

Behavior with this branch:

https://user-images.githubusercontent.com/8092184/191057849-0f24c2f7-4cae-456d-a467-1e7e29cb6ee9.mov

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@svennergr would you mind adding recording of implemented change/comparison with main. Because I have tested this and don't see any difference I think

**Comment by svennergr** [comment]
> @svennergr would you mind adding recording of implemented change/comparison with main. Because I have tested this and don't see any difference I think

@ivanahuckova I don't know what exactly happened. I had the **wrong** implementation on the **wrong** component. Thanks for noticing, I fixed this PR and added recordings.

**Comment by ivanahuckova** [comment]
For me personally this is more confusing than if I had to do a little bit scrolling to see full context. At times, it looks like it opened context for different log line and I am also loosing sight of the log line.

https://user-images.githubusercontent.com/30407135/191205897-a3b85e17-93eb-4048-ba00-b6b7b866ab71.mov

What do you think about demoing this in UX feedback session to get more opinions.

**Comment by svennergr** [comment]
> What do you think about demoing this in UX feedback session to get more opinions.

Sure! I will talk with @niat22 next week and potentially get feedback in that session.

**Comment by svennergr** [comment]
@ivanahuckova 
After talking to @niat22 I did two small changes to indicate the centring a bit better:
- the logrow is now scrolling smoothly to the center
- if one context is open, the other context-buttons are hidden


https://user-images.githubusercontent.com/8092184/192739473-5e00713e-d772-4d16-89d7-039a41522f49.mov

**Comment by svennergr** [comment]
Moved this to draft in favor of https://github.com/grafana/grafana/pull/55934. https://github.com/grafana/grafana/pull/55934 needs to be merged before this.

**Pull request closed without merging**
