### PR TITLE
WIP: Fixing dashboard-solo login bug

### LINKED ISSUE #3769: Dashboard-Solo Requires Login for Snapshot
Edit: Sorry. Just read the actual text on that page and realised it specifically says if anon is not enabled etc etc - however is there a possibility of adding this as a feature request for the future?

I am trying to embed a single panel from a snapshot without any of the surrounding grafana interface like when you generate a dashboard-solo url from the sharing interface on a panel.

When i use the following it works unauthenticated

Entire Dashboard
http://grafana/dashboard/snapshot/XXXX

Single Panel view, i.e panel 1
http://grafana/dashboard/snapshot/XXXX?panelid=1&fullscreen

Now if i try use the following for logged in users in terms of it just showing the graph and nothing else it works but for unauthenticated users they are redirected to the login page

http://grafana/dashboard-solo/snapshot/XXXX?panelid=1&fullscreen

Is there a way to achieve this?

### PR DESCRIPTION
**Pull request by utkarshcmu**
Resolves #3769 , no login required for dashboard-solo urls anymore.

### CODE REVIEW

**Comment by bergquist** [comment]
This PR does not work for me.

I get the initial page but since the dashboard is loaded by angular I get rejected later. 

image

**Comment by utkarshcmu** [comment]
Clear your cache and then try it, if you have not. :)

**Comment by utkarshcmu** [comment]
Actually, I am able to reproduce your error. Let me fix it. Thanks for testing :)

**Comment by torkelo** [comment]
dashboard-solo should require login for non snapshot dashboards!

**Pull request closed without merging**
