### PR TITLE
Logs: move logs-components from grafana-ui to grafana-main

### PR DESCRIPTION
**Pull request by gabor**
this pull request moves the logs-related components from `grafana-ui` to the main grafana package.

(to keep backward compoatibility, they also remain in `grafana-ui`, they will be deleted in grafana10)

this pull request is quite large, i recommend reading it commit by commit. the first commit is the largest, but that just copies the files unmodified to the new place. the remaining commits adjust the files, and those commits are much smaller.

what is not included in the PR:
1. mark the original files in grafana-ui as deprecated, will be done in a separate PR when this is merged
2. new betterer-exceptions had to be added, because these exceptions already existed for the `grafana-ui` version of the files. i tried to fix all these betterer-exceptions at the new place, but not all have an easy fix, some require changes also to files not in this PR, so it will be better to do those as a separate PR

how to test:
- no specific instructions, run it, open the logs-visualization in both explore and in dashboard, try it out, make sure there are no errors.

### CODE REVIEW

**Review by matyax — APPROVED** [review]
👌

**Comment by matyax** [comment]
Would it make sense to have an issue to create, or attempt to create, a Storybook story for these components?

**Comment by gabor** [comment]
> Would it make sense to have an issue to create, or attempt to create, a Storybook story for these components?

hmm.. good question.. we do have such storybook for grafana-ui components, but i don't think we have one for "main-grafana" package yet... still, we can try looking into this.. when this gets merged i'll create a github-issue for "look into if it's possible/worthwile to create a storybook-thing for these components" 👍

**Comment by sakjur** [comment]
@gabor Changing the milestone to 9.3.0 since this was merged before the 9.2.0 branchoff.

**Pull request merged**
