### PR TITLE
Add Kubernetes icon

### PR DESCRIPTION
**Pull request by sd2k**
**What is this feature?**

This commit adds a new icon for Kubernetes. I've just taken the SVG from the Grafana K8S plugin and plopped it in the `unicons` directory following the [How to add a new icon](https://github.com/grafana/grafana/blob/main/public/img/icons/README.md) instructions (removing width/height etc), but I'm unsure whether we should modify the SVG to instead have a single-colour version. I did have a quick go at this but it doesn't look quite right due to the lack of surrounding shape; perhaps everything needs inverting? I couldn't figure out how to do that though - happy to have another go if you think that'd look better.

In the below Storybook screenshot, the first (`kubernetes`) is the version I've included in this PR, while the second (`kubernetes2`) is the result of using the second path as a mask and removing the fill attributes.

image

**Why do we need this feature?**

Despite Grafana being used for lots of infra monitoring we don't have a Kubernetes icon. We do have a Docker one, so this feels like a natural extension.

**Who is this feature for?**

Plugin developers who want to be able to include a Kubernetes icon when using the `Icon` component from `@grafana/ui`.

**Which issue(s) does this PR fix?**:

N/A

**Special notes for your reviewer:**

I [asked about this in Slack](https://raintank-corp.slack.com/archives/CHKLEJ668/p1707134844534069) a few months ago but never got round to it until now!

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mckn — COMMENTED** [review]
LGTM! But someone working more with the design system should probably do the approval.

**Comment by staton-hyse11** [comment]
Would it be better to have this without the mask and only be a SVG? We will need the design asset to remain in parity with the code asset anyhow. If so, I can take the lead here and generate the SVG icon for this via Figma and attach it.

**Comment by sd2k** [comment]
I think it might be better that way if it still looks correct without the mask yeah - I had a quick go at it but haven't really worked with SVGs before so didn't know what I was doing. Would really appreciate it if you could take a look @staton-hyse11!

**Comment by staton-hyse11** [comment]
@sd2k I've tagged you in a Figma file for the SVGs. Leave your thoughts there and I'll follow up with the final assets in this PR.

**Comment by Aires-Grafana** [comment]
Is this already solved?
The "kubernetes2" is not a solution. I have the official SVG icon in Figma from Kubernetes.io in this [Figma page](https://www.figma.com/file/nYiVUfeDEB1HNj0oLIczDZ/Saga-Iconography?type=design&node-id=2865-10471&mode=design).
If this is already solved, please disregard this message. Thanks!

**Comment by sd2k** [comment]
I've updated the icon to the [one provided in Slack](https://raintank-corp.slack.com/archives/C025WTVRBSN/p1713973825846459?thread_ts=1713969070.723679&cid=C025WTVRBSN). Storybook screenshot:

image

**Comment by jewbetcha** [comment]
Really like that one @sd2k , k8s app team approves 👍

**Review by staton-hyse11 — APPROVED** [review]
LGTM!

**Pull request merged**
