### PR TITLE
Prometheus: Offer hint for metrics with labels

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Follow up on https://github.com/grafana/grafana/pull/45288. We want to offer hint for query that includes counter metric + optionally label-value pairs. This PR fixes it. 

**Now:** 
image

**Before:**
image

### CODE REVIEW

**Comment by torkelo** [comment]
Testing this and not seeing any hints for this case
Screenshot from 2022-02-15 16-57-53

Also seeing some bugs where when I change metric I loose the labels (see this in the when preview is enabled, and if you go to code mode). I cannot replicate that in main branch

**Comment by torkelo** [comment]
Wait I am seeing that bug in main!

**Comment by ivanahuckova** [comment]
>Testing this and not seeing any hints for this case

Yes, good catch. I fixed the issuer for counter, but not buckets. Added fix for buckets as well.

**Review by torkelo — APPROVED** [review]
Works now with buckets as well!

**Pull request merged**
