### PR TITLE
TablePanel: Fix last table column to be centered

### LINKED ISSUE #50960: Last Table Column Not Centered
It seems like items in the last column of a table are not centered like other centered columns in the same table. See screenshot. I believe this may be occurring because the styling is calculating the scrollbar, which does not appear when data does not exceed the table height. It does not change if the column width is defined or not.

image

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Fixes table alignment when text in centered

**Which issue(s) this PR fixes**:

Fixes #50960

**Demo**
https://www.loom.com/share/94733c2f24614c54b76b636ddf4e38f6

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mellieA** [comment]
@gitstart thank you for your contribution, I've moved this to the right squad project for review

**Review by mdvictor — CHANGES_REQUESTED** [review]
Hey @gitstart! Thank you for your contribution! The Table panel vertical scrollbar has been updated recently and this seems to be a remnant of the old one. 

Your solution fixes the issue but I think the entire idea of adding a padding to the last column is no longer necessary since the new scrollbar is hidden by default and only appears on table focus. So instead of adding a new css style there, maybe we can remove the dynamic padding based on scrollbar width from [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/styles.ts#L17) and just use the given `cellPadding`.

What do you think?

**Comment by gitstart** [comment]
> Hey @gitstart! Thank you for your contribution! The Table panel vertical scrollbar has been updated recently and this seems to be a remnant of the old one.
> 
> Your solution fixes the issue but I think the entire idea of adding a padding to the last column is no longer necessary since the new scrollbar is hidden by default and only appears on table focus. So instead of adding a new css style there, maybe we can remove the dynamic padding based on scrollbar width from [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/styles.ts#L17) and just use the given `cellPadding`.
> 
> What do you think?

Hey @mdvictor! As you suggested, removing the dynamic padding makes sense. Made the necessary changes to the PR, please review

**Review by mdvictor — APPROVED** [review]
Looks great! Thank you for this!

**Pull request merged**
