### PR TITLE
PublicDashboards: HoverWidget in panel fix

### LINKED ISSUE #66545: Headerless panel menu overlap in public dashboards
**What happened**:
When accessing a public dashboard and hovering over a headerless panel that's at the top, the hover menu is not 100% visible

Image

**What you expected to happen**:
The menu should be visible. 

**How to reproduce it (as minimally and precisely as possible)**:
* Create a dashboard with a panel without a title. There should be no other elements above the panel.
* Share the dashboard publicly
* Access the public dashboard and hover over the panel. 

**Anything else we need to know?**:
Besides this it feels a bit odd to have the drag icon visible.

**Environment**: 
- Grafana version: latest main (v10.0.0-54392pre at the time of testing)
- Data source type & version: any 
- OS Grafana is installed on: Cloud
- User OS & Browser: Chrome, Firefox, Safari. iOS
- Grafana plugins: any
- Others:

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

- Adds padding to the dashboard grid to let the hover widget be shown well.
- Removes panel drag cursor when is not editable
- Removes HoverWidget drag icon when is not editable

**Which issue(s) does this PR fix?**:

Fixes [#66545](https://github.com/grafana/grafana/issues/66545)

**Special notes for your reviewer:**

Dashboard 
image

**Public dashboard before**
image

**Public dashboard now**
image

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey, @juanicabanas 😄  , the behavior of showing the hover widget even when the panel `title` is `undefined` was made by design. Our idea is to add an extra option to the panel configuration (maybe panel edit) that will allow users to show the hover widget even when the panel title is not present.  Here is the issue https://github.com/grafana/grafana/issues/59398

I think we need to find a different way of fixing the issue that the public dashboard has 🤔.

**Comment by juanicabanas** [comment]
> 

@axelavargas I don't know if I got you. 
The idea of that hover widget is to show the menu options for the panel itself and to be able to drag and drop when holding it, or am I wrong?
Both things (menu options and drag and drop behavior) don't have to be in a public dashboard view, since it's ready only and the viewer doesn't have to manipulate the panel.
So, since the hover widget doesn't make any sense if there's no menu and the `PublicDashboardPage` renders `DashboardGrid` with `hidePanelMenus` prop, I added the logic of not render the hover widget if there's no menu as prop.
Let me know if I'm wrong!

**Comment by axelavargas** [comment]
> The idea of that hover widget is to show the menu options for the panel itself and to be able to drag and drop when holding it.

Nope, the hover widget also displays other elements for the panel header, such as description, panel links, and any custom option that the component that uses wants to show there :)  


image

**Comment by juanicabanas** [comment]
> > The idea of that hover widget is to show the menu options for the panel itself and to be able to drag and drop when holding it.
> 
> Nope, the hover widget also displays other elements for the panel header, such as description, panel links, and any custom option that the component that uses wants to show there :)
> 
> image

Got it. So, I think we should work over that hover widget in order to hide some elements if it's public dashboard. For example, the menu options (which opens the edit panel, the movement behavior and so on)

**Review by axelavargas — APPROVED** [review]
Awesome work, @juanicabanas 🥳 , the code looks great, and everything works as expected! 

*P.S, nice unit tests* 🎆

**Pull request merged**
