### PR TITLE
support mysql2 connection string

### PR DESCRIPTION
**Pull request by bbodenmiller**
So you can use [`DATABASE_URL` var from Cloud Foundry](https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#DATABASE-URL)

### CODE REVIEW

**Comment by marefr** [comment]
Don't understand how this change correlate to the link you included. Please specify in detail what you're trying to achieve.

**Comment by marefr** [comment]
I find no information whatsoever of a connecting string on the format `mysql2://`, not even in the link you provided. This is too much of an edge case and you already have a working solution by using `mysql://`.  Sorry but we're going to close this. Will consider reopen if more users wants this feature.

**Comment by bbodenmiller** [comment]
Disappointing. A quick Google search shows it as a common connection string
format for MySQL.

**Comment by marefr** [comment]
Could you please link to that google search. I'm running out empty. Thanks

**Pull request closed without merging**
