### PR TITLE
Loki: Adds comment explaining usage of RFC3339Nano string

### LINKED ISSUE #17862: Loki: Show context in Explore doesn't work
**What happened**:
Selected `Show context` for a Loki log message and error message is displayed: "Error during context query. Please check JS console log".

**What you expected to happen**:
Surrounding/contextual log messages are loaded and displayed.

**How to reproduce it (as minimally and precisely as possible)**:
Using Loki in Explore and filtering a stream `{job="grafana"} eror`, then select `Show context`.

**Anything else we need to know?**:
Seems to be related to wrong date/time format being sent in parameter to loki, but not sure.

image

image

**Environment**:
- Grafana version: master (364f1f2)
- Data source type & version: Loki
- User OS & Browser: Chrome

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Adds comment explaining usage of RFC3339Nano string. Needed since it's not immediately obvious why it's being used.

### CODE REVIEW

**Comment by dprokop** [comment]
@kaydelaney we can't use ns epoch, as we lose precision(we don't ns precision math) and we get wrong results. Please refer to Hugo's changes here and discussion in this Loki's issue: https://github.com/grafana/loki/issues/597

**Review by marefr — APPROVED** [review]
Good. Please update the title of this PR to make it clear that we only adds a comment and not fixing any bug. 

Think you can close the referenced issue and label with "work as intended" and remove the issue reference from this PR before merging it.

**Comment by torkelo** [comment]
Does this make context queries work? I tried this but still got error, maybe I need to update loki to latest?

**Comment by kaydelaney** [comment]
> Does this make context queries work? I tried this but still got error, maybe I need to update loki to latest?

Yep, needs to be updated

**Pull request merged**
