### PR TITLE
Build: Nx improvements

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

#81873 introduced Nx to orchestrate tasks however little to no effort was put into fine tuning its usage.

**Why do we need this feature?**

To improve the usage of Nx features across the repo. This PR adds project.json files for each workspace so Nx can better understand how to cache them. Right now each plugin will be rebuilt whenever any file changes in the repo which I believe occurs because these plugins are nested "projects" to the root "project.json". With the changes in this PR Nx will only invalidate local plugin build cache when the plugins source code, its dependencies or its external dependencies change. It also adds icon generation as a dependency of `grafana:start` to guarantee the icons are available and caches the result for future runs.

It also introduces tags to each workspace which can be used within Nx for filtering. This feels like a much more powerful way for us to run commands against select workspaces in the future. This PR defines two tag scopes: "plugin" and "package" which are used by Nx to build the plugins and packages.

Note that this does make a change to how Nx sees projects. Prior to this PR `yarn nx run @grafana-plugins/tempo:build` could be used to build tempo. Due to adding `project.json` files this PR changes the project references to the name of the folder meaning the command now becomes `yarn nx run tempo:build`.

Note: Nx caching is not enabled for CI. It is only used locally to speed up development.

**Who is this feature for?**

Grafana contributors.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by dprokop** [comment]
@jackw - haven't been following the nx work to much, but making changes to any of the plugins is not reflected in the `yarn start` command. I assume this is expected, and plugin development should happen with a corresponding plugin build proces running independently from `yarn start`. Is that correct?

**Comment by jackw** [comment]
> @jackw - haven't been following the nx work to much, but making changes to any of the plugins is not reflected in the `yarn start` command. I assume this is expected, and plugin development should happen with a corresponding plugin build proces running independently from `yarn start`. Is that correct?

Yes, development of plugins is done with separate yarn commands now. That change happened in #81873 with the following description:

> However this changes workflows.. decoupled plugin devs now need to (potentially) run two commands to develop. One for building grafana core and one for building their plugin.
> 
> - To build all plugins and watch grafana core for changes -> `yarn start`
> - To build and watch all plugins -> `yarn plugin:build:dev`
> - To build and watch a single plugin -> `yarn workspace @grafana-plugins/grafana-testdata-datasource dev`
> 
> Whilst this might seem inconvenient they run in parallel and a plugin developer doesn't need to wait for all externalised plugins to build when making changes to their own plugin. If the work is only focused on the plugin you might not even need to run `yarn start`.

The frontend-ops direction with this is to speed up development by only building the pieces of the monolith as needed. Eventually I'd like to bring this to production / CI builds also but that's a bit of a long road. I've an associated [PR here](https://github.com/grafana/grafana/pull/88286) that updates the developer docs with these commands. Any feedback you have on this approach would be most appreciated @dprokop.

**Comment by dprokop** [comment]
Thank you @jackw, I have missed that PR you are mentioning. This is great!

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Review by aangelisc — APPROVED** [review]
Changes LGTM @jackw 😊

**Pull request merged**
