### PR TITLE
(cloudwatch) basic expression support

### PR DESCRIPTION
**Pull request by mtanda**
We need to calculation to get correct metric value for some of the CloudWatch metrics.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/MonitoringDynamoDB.html

> Use the Sum statistic to calculate the consumed throughput. For example, get the Sum value over a span of 1 minute, and divide it by the number of seconds in a minute (60) to calculate the average ConsumedReadCapacityUnits per second

This PR care about such situation.

cloudwatch_expression

### CODE REVIEW

**Comment by torkelo** [comment]
not sure I like this, would like to use the backend query processing stuff for doing transformations, its just prof of concept in querylab  branch where I built a backend for processing queries that can depend on each other to support a "meta" query that can transform another queries series results

**Comment by mtanda** [comment]
Read this,
https://github.com/grafana/grafana/blob/querylab/pkg/tsdb/brainstorming.txt
And this.
https://github.com/grafana/grafana/blob/querylab/pkg/tsdb/tsdb_test.go

I understand what "backend query processing" is.
It looks like rrdtool's CDEF.
https://oss.oetiker.ch/rrdtool/tut/cdeftutorial.en.html

It's very nice feature! I really want such feature, because I use several datasource, Prometheus and CloudWatch.
If I can calculate something from several datasource, it's very useful.

Is there any ticket about this feature?

Anyway, basic expression support is very required feature until "backend query processing" is available.
If basic expression support will be deprecated, it is acceptable for me.
I want to merge this, if possible.

**Comment by torkelo** [comment]
no there is no issue for it. Its something for the future :) Not sure what the best interim solution is.

**Comment by mtanda** [comment]
To notice about this problem, I create a issue.
https://github.com/grafana/grafana/issues/3187

Ofcouse, it is the isseu of CloudWatch, but I think they don't change current behavior.
We will need to fix it in Grafana side.

**Comment by mtanda** [comment]
resolve conflict

**Comment by bergquist** [comment]
Since #3445 have been merged I think the transformMetricData is growing to much. Could we please split it and add more tests for it?

**Comment by torkelo** [comment]
this should wait for some generic metric transformation feature in grafana that works with any data source.

**Comment by mtanda** [comment]
It's no problem, if https://github.com/grafana/grafana/issues/3187 is fixed.
(I don't want to calculation feature, just want to fix it.)

**Pull request closed without merging**
