### PR TITLE
Docs: Deprecating packages_api and removing it from our pipelines

### LINKED ISSUE #54452: Deprecate https://grafana.com/docs/grafana/latest/packages_api/
We would like to remove api-extractor script(s) that we use in our CI/CD to generate the [API Reference](https://grafana.com/docs/grafana/latest/packages_api/) page in our docs. This area is currently not really useful for developers internally as well as externally and only adds to confusion around documentation. 

In the future we want to have a solution that is adding value to developers reading the documentation and will think about ways to accomplish that.

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What this PR does / why we need it**:
This PR removes `packages_api` docs from our pipeline and changes currently known references. We agreed on deprecating the `packages_api` for now until we have a better solution that provides more value to developers.

**Which issue(s) this PR fixes**:

Fixes #54452

### CODE REVIEW

**Comment by tolzhabayev** [comment]
Note to myself: need to sync with enterprise build after this is merged

**Review by marefr — APPROVED** [review]
LGTM :boom:

**Comment by dsotirakis** [comment]
Thanks @tolzhabayev for removing a step from our CI ❤️ 
Just FYI - I get an error in `CODEOWNERS` file which says that it's wrong. Probably because we need to remove `@marcusolsson` from there I guess?

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Comment by tolzhabayev** [comment]
fyi @ryantxu

**Pull request merged**
