### PR TITLE
Add missing AWS/Cognito metrics

### PR DESCRIPTION
**Pull request by razor-x**
See https://docs.aws.amazon.com/cognito/latest/developerguide/metrics-for-cognito-user-pools.html

### CODE REVIEW

**Review by ifrost — APPROVED** [review]

**Review by sunker — CHANGES_REQUESTED** [review]
Thanks for contributing! 
I believe you also need to add the new metric dimensions? `UserPool`, `UserPoolClient` etc...See line 167

**Comment by razor-x** [comment]
Good call! It's late now, but I can add those tomorrow. I also contributed a couple of other PRs with similar updates and want to double check I didn't miss any unique dimensions for those.

**Comment by razor-x** [comment]
Should be good now. I added the new dimensions and I also removed CallCount and ThrottleCount since those are part of Usage. I checked my other merged PRs and they don' have these issues.

**Review by sunker — APPROVED** [review]
LGTM! Thanks again!

**Pull request merged**
