### PR TITLE
Alerting: Allow grafana-default-email contact point to be removed via API / provisioning

### LINKED ISSUE #66087: Non-blank value for UID required by Alerting Provisioning HTTP API for removing default contact point
**What happened**:

Trying to provision contact points from source code configurations and cleaning up anything users may have created to ensure consistency from code to instance.

**What you expected to happen**:

We expect to be able to delete the default contact point after updating the root notification policy to a different contact point. However, the UID of the default contact point is blank, and the API needs a non-blank one. 

**How to reproduce it (as minimally and precisely as possible)**:

Step 1: Update the root notification policy to a non-default contact point.

Step 2: List the contact-points

```
curl https://admin:pwd@grafana-hostname.companyname.com/api/v1/provisioning/contact-points

    {
        "uid": "",
        "name": "email receiver",
        "type": "email",
        "settings": {
            "addresses": "\u003cexample@email.com\u003e"
        },
        "disableResolveMessage": false
    }
```    
Step 3: remove the Contact point with a blank UID.

```
curl -X DELETE https://admin:pwd@grafana-hostname.companyname.com/api/v1/provisioning/contact-points/
{"message":"Not found"}
```
Note that the documentation mentioned a UID is required at the end of the URL, after "contact-points/{UID}" and we can't provide it as it's blank.

**Anything else we need to know?**:

The change request is here in the Pull Request:
https://github.com/grafana/grafana/pull/66089

**Environment**: Not applicable
- Grafana version: Grafana enterprise 9.4.7 
- Data source type & version: Not applicable
- OS Grafana is installed on: Not applicable
- User OS & Browser: Not applicable
- Grafana plugins: Not applicable
- Others: Not applicable

### PR DESCRIPTION
**Pull request by dugalp**
**What is this feature?**

In the documentation for the Alerting Provisioning HTTP API, the UID for the contact point is required to be passed, but the default contact point is blank and we don't want to use click-ops to remove it after the instance is up to then have to do human interaction. https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-delete-contactpoints. We want to straight away run a script to update all the contact points based on source code and cleanup any unreferenced/unused contact points such as the default one or ones the user may have created. We want those in source code instead, and deploy all of them from there.

**Why do we need this feature?**

This addresses the issue anyone would have when using a model where the non-provisioned contact points are deleted as part of a full deployment which includes auto-provisioning to ensure all configurations are in code based instead of relying on the DB (in case we need to rebuild the instance quickly with a new DB). We delete the default contact point as well but it's failing because the UID being returned is blank.

**Who is this feature for?**

Anyone using GitOps model to redeploy all contact points for a new instance, and delete the default as part of alerting provisioning which runs after the instance is up.

**Which issue(s) does this PR fix?**:
Fixes #66087

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by grobinson-grafana — APPROVED** [review]
LGTM!

**Review by grobinson-grafana — APPROVED** [review]
LGTM!

Tested deleting when in-use:

```
curl http://127.0.0.1:3000/api/v1/provisioning/contact-points/grafana-default-email -X DELETE
{"message":"change would result in an invalid configuration state: unexpected receiver (grafana-default-email) is undefined","traceID":""}
```

and when not in-use:

```
curl http://127.0.0.1:3000/api/v1/provisioning/contact-points/grafana-default-email -X DELETE
{"message":"contactpoint deleted"}
```

**Comment by grobinson-grafana** [comment]
Please just update the integration tests as the `uid` in the default configuration has changed 🙂

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]
Please just update the integration tests as the uid in the default configuration has changed 🙂

**Comment by tonypowa** [comment]
@dugalp 

thank you for your contribution 🚀 
as the next step, please review [this comment](https://github.com/grafana/grafana/pull/66089#pullrequestreview-1469606599)

**Comment by JacobsonMT** [comment]
@dugalp This is great! I came across this annoyance while writing the contact point export feature just recently.

@grobinson-grafana What do you think about also changing the integration name to match the contact point name, while we're making changes to this default. So, `email receiver` to `grafana-default-email`. Most of our code (especially in provisioning) assumes they should always be equal ([example](https://github.com/grafana/grafana/blob/9ad45aedcfeb89dcb47d7934f2b229163722dee1/pkg/services/ngalert/provisioning/contactpoints.go#L429-L432)).

**Comment by dugalp** [comment]
> Please just update the integration tests as the uid in the default configuration has changed 🙂

Hi @grobinson-grafana, do you mean that I need to update the uid value [here](https://github.com/grafana/grafana/blob/ad272b79840d958e5307e20a9b95f85265d67902/pkg/tests/api/alerting/api_notification_channel_test.go#L1950) from blank to `grafana-default-email`?

**Comment by JacobsonMT** [comment]
>It appears this might be a pretty big change, in multiple places. So if you can help create a PR for the integration tests, that would help a lot.

Yah, the tests were a bit more involved than I thought as some (mistakenly) relied on the uid being empty to work. I've fixed the tests and pushed to your branch.

**Comment by JacobsonMT** [comment]
This also has the added benefit of fixing a bug in the contact point export endpoints: Exporting the `grafana-default-email` if using the single contact export fails because the integration name didn't match the receiver name (so the query param filter filters it out).  Also, when exporting all of the contact points it used the name `email receiver` for the default instead of `grafana-default-email`.

Small bug, but still nice.

**Comment by Nemental** [comment]
@JacobsonMT what happened to this PR? I recently stumbled upon this when I wanted to implement contact points for unified alerting in `community.grafana` Ansible collection

**Pull request closed without merging**
