### PR TITLE
Auth: Skip email extraction when api url is not present

### LINKED ISSUE #85891: Auth: Fix login with generic OAuth when api_url is not configured
### What happened?

When trying to login with SSO using generic OAuth, the login failed with the following details in logs:
```
logger=oauth.generic_oauth t=2024-04-10T00:38:55.384768223Z level=error msg="Error getting email address" url=/emails error="Get \"/emails\": unsupported protocol scheme \"\""
logger=authn.service traceID=9ff48e209dba8c61b663087ad052a758 t=2024-04-10T00:38:55.384824283Z level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.userinfo.error] failed to get user info: Error getting email address: Get \"/emails\": unsupported protocol scheme \"\"
```
The `api_url` is not required for this SSO integration and it's left empty. 

Looking at [the implementation](https://github.com/grafana/grafana/blob/e3314f04e4813ae6a86e14a09c475e49a018840d/pkg/login/social/connectors/generic_oauth.go#L478) it seems that the authentication flow tried to retrieve the email by calling the `api_url` suffixed with the string `/emails`.

### What did you expect to happen?

The authentication flow for generic OAuth should not have attempted to call the `api_url + "/emails"` endpoint to retrieve the email because in this case the api_url is empty.

### Did this work before?

Did not try to reproduce this error in previous versions.

### How do we reproduce it?

1. Configure SSO for generic OAuth with no api_url endpoint configured.
2. Try to login with SSO using generic OAuth.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by PyAgni**
**What is this feature?**

This PR checks if `api_url` is configured in the SSO integration, and only tries to fetch private email when `api_url` is configured.

**Why do we need this feature?**

So that OAuth flow doesn't break in case API URL is not configured.

**Who is this feature for?**

Any user configuring Generic SSO in Grafana, without setting the API URL 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/85891

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by dmihai** [comment]
Hi @PyAgni, thank you for your contribution! Your change looks good.

One of the checks in the CI is failing, please take a look and fix the error reported by `golangci-lint/lint-go`.

**Comment by PyAgni** [comment]
> One of the checks in the CI is failing, please take a look and fix the error reported by `golangci-lint/lint-go`.

The cyclomatic complexity of the function increased because of the added condition. I've moved the conditions out in a separate method, that should fix it.

**Review by dmihai — APPROVED** [review]
It looks great, thank you again for your contribution!

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!

**Comment by yuri-tceretian** [comment]
Greetings from Release Guild. This PR has been successfully included in the Grafana 11.2 release branch. A backport PR was also created to ensure the v11.2.x branch is correctly synchronized with the release.

**Pull request merged**
