### PR TITLE
Add config option to control snapshots with no expiration

### PR DESCRIPTION
**Pull request by rbak**
https://github.com/grafana/grafana/issues/5704

### CODE REVIEW

**Comment by torkelo** [comment]
You can clean up snapshots in the snapshots view:

image

**Comment by torkelo** [comment]
Instead of a config option like this, maybe a max_expiration_time would be better? (defaults to Never)

**Comment by rbak1** [comment]
The way we're deploying Grafana is as a service to internal users, and we can't really force our users to clean out old snapshots, and would prefer not to have to clean them out for them.  The best way to enforce this is just to ensure that all snapshots have an expiration.  I'm happy to update the patch for max_expiration_time though.  That seems like a more flexible solution.

**Comment by bergquist** [comment]
In grafana 4.0 you can configure automatic cleanup of old snapshots.
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L165

Since that feature have been added I don't really see the need for this PR. So I'm gonna close this. But thank you for taking the time to find ways to improve Grafana.

**Pull request closed without merging**
