### PR TITLE
Plugins: Update PDC pattern from latest plugin SDK changes

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**

As a result of the changes in https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.182.0, this PR addresses the breaking changes:
- Passing `context.Context` to both `DataSourceInstanceSettings.HTTPClientOptions` and `AppInstanceSettings.HTTPClientOptions`
- Fixing the usage of PDC 

**Why do we need this feature?**

To address breaking changes in the latest plugin SDK update and ensure the PDC feature continues to work.

**Who is this feature for?**

Plugins Platform

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by xnyo — APPROVED** [review]
LGTM!

**Review by matyax — COMMENTED** [review]
Logs changes look good 👍

**Review by aangelisc — APPROVED** [review]
Azure, Google, and MSSQL changes LGTM 👍

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
