### PR TITLE
Alerting: Make Unified Alerting enabled by default

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What this PR does / why we need it**:
This PR makes the unified alerting enabled by default. 

|  `GF_ALERTING_ENABLED` |  `GF_UNIFIED_ALERTING_ENABLED`  | Result |
| ---------------------- | ------------------------------- | ------ |
| `true` | `true` | Error |
| `true` | `false` | Legacy |
| `true` | not set | Error |
| not set | `true` | UA |
| not set | `false` | Alerting disabled |
| not set | not set | UA |
| `false` | `true` | UA |
| `false` | `false` | Alerting disabled |
| `false` | not set | UA |

### Grafana 8 Alerting is enabled by default 
Starting with Grafana 8.3 Unified Alerting is enabled by default. 

Those that upgrade from the previous versions and have enabled legacy alerting explicitly (see documentation) will need to change the configuration and disable legacy alerting by changing the option `enabled` to `false` or completely removing the `[alerting]` section.

If you want to continue using legacy alerting, you will need to explicitly disable the unified alerting feature and enable the legacy alerting by changing the option `enabled` to `true` in the `[alerting]` section and changing the `enabled` option to `false` in the `[unified_alerting]` section.

The feature flag `ngalert` is not supported anymore and has no effect when used. Users should use `[unified_alerting]` configuration options instead.

### CODE REVIEW

**Comment by yuri-tceretian** [comment]
@papagian can you please review it as it looks like you worked on it more than anyone else?

**Review by papagian — COMMENTED** [review]
|  Legacy enabled |  UA enabled  | Result |
| ------------- | ------------- | ------------- |
| true | none | UA |

In the above case the command would look like:
`GF_ALERTING_ENABLED=true GF_LOG_LEVEL=debug make run`
and one would expect the legacy alerting would be enabled but it does not.
Therefore I would prefer to error in this case.

Also the [docs](https://grafana.com/docs/grafana/latest/administration/configuration/#enabled-3) need to be updated.

**Comment by yuri-tceretian** [comment]
> In the above case the command would look like:
> GF_ALERTING_ENABLED=true GF_LOG_LEVEL=debug make run
> and one would expect the legacy alerting would be enabled but it does not.

I did that intentionally. For 8.3 users (especially new) there should not be unified vs legacy alerting, in my opinion. If they enable alerting - we enable the current version of it. On other side, we give users a way to rollback to the legacy alerting by explicitly disabling unified alerting. 
I do not think that failing is a good user experience in terms of the upgrade:
1. we basically ask user to enable new alerting system (and disable legacy), ie prompt before starting the service.
2. when users upgrades from one minor to another minor, they probably expect that it will start if the configuration was not changed.

**Comment by armandgrillet** [comment]
I disagree for three cases (following @papagian's comment for one of those):
|  `GF_ALERTING_ENABLED` |  `GF_UNIFIED_ALERTING_ENABLED`  | Result |
| ---------------------- | ------------------------------- | ------ |
| `true` | `true` | UA |
| `true` | not set | UA |
| `false` | not set | Alerting disabled |

In my opinion, it should be:
|  `GF_ALERTING_ENABLED` |  `GF_UNIFIED_ALERTING_ENABLED`  | Result |
| ---------------------- | ------------------------------- | ------ |
| `true` | `true` | error |
| `true` | not set | error |
| `false` | not set | UA |

**Review by gotjosh — COMMENTED** [review]
Code-wide LGTM. 

I think we're missing:

- update https://grafana.com/docs/grafana/next/administration/configuration/#enabled-3 and https://grafana.com/docs/grafana/next/alerting/
- A breaking change notice so that this comes out as part of the changelog - See https://github.com/grafana/grafana/pull/41305 for an example.
- Fixing of the CI, unsure why this is failing.

**Review by papagian — APPROVED** [review]
The default values in the docs for [unified_alerting.enabled](https://grafana.com/docs/grafana/latest/administration/configuration/#enabled-3) and [alerting.enabled](https://grafana.com/docs/grafana/latest/administration/configuration/#enabled-4) should be updated as well otherwise LGTM

**Review by gotjosh — APPROVED** [review]
LGTM. I think we can make some tweaks to the wording on the breaking change notice:

Starting with Grafana 8.3 Unified Alerting is enabled by default. 

Those that upgrade from the previous versions and have enabled legacy alerting explicitly (see documentation) will need to change the configuration and disable legacy alerting by changing the option `enabled` to `false` or completely removing the `[alerting]` section.

If you want to continue using legacy alerting, you will need to explicitly disable the unified alerting feature and enable the legacy alerting by changing the option `enabled` to `true` in the `[alerting]` section and changing the `enabled` option to `false` in the `[unified_alerting]` section.

The feature flag `ngalert` is not supported anymore and has no effect when used. Users should use `[unified_alerting]` configuration options instead.

**Comment by yuri-tceretian** [comment]
Closing it in favor of less intrusive approach implemented in https://github.com/grafana/grafana/pull/42200

**Pull request closed without merging**
