### PR TITLE
Opentsdb 2.2 support without breaking 2.1

### PR DESCRIPTION
**Pull request by utkarshcmu**
Replaced #3981 because it shows commits from others in master branch. 

This PR has the exact same code which was in #3981 and has required tests for Opentsdb queryCtrl.

Please review/merge. Thanks.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Can this be reviewed/merged before 3.0.0-beta release?

**Comment by bergquist** [comment]
If I view a panel before going to the datasource config page I get an error saying tsdbVersion is missing. I think it would be a good idea to set a default value in the datasource constructor. 

Please don't take this in a bad way but It would also be nice to avoid all those merge commits with master in the future. See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
But dont bother for this PR, just for future PRs :)

If you fix the minor version error I will merge this. Keep up the good work! :+1:

**Comment by abraithwaite** [comment]
:+1: Can't wait for this to land.

**Comment by utkarshcmu** [comment]
Changes made as you suggested. Thanks for the feedback and link for "git rebase". All the feedback is good as it will improve the code quality :) :+1:

**Comment by utkarshcmu** [comment]
@bergquist Thanks for giving me the links to "Git Rebase". Did a rebase on my branch to resolve conflicts and those merging from grafana/master commits are gone. :)

**Comment by utkarshcmu** [comment]
Whenever this PR is merged, please close following issues:

#3271
#3077
#4040

**Comment by amalshah** [comment]
Does this change add group_by filter support? I couldn't see how to toggle this from the UI using the master build from 03/17?
This is pretty powerful feature, as you can easily aggregate or explode a set of timeseries from the query panel.
TSDB documentation is here: http://opentsdb.net/docs/build/html/api_http/query/index.html#example-with-show-summary-and-query
I had attached some code to support this in: #3077.

**Comment by amalshah** [comment]
Sorry, got the feature enabled by turning on Version=2.2 in the Data Source configuration.
However, there seems to be a bug with the labels display when you define multiple queries with filters each with a different alias. In this case, just one alias shows up in the labels for the time-series.
So, define two queries like: 
query: A, metric: my.metric, alias: A, filter: my.attr=regexp(A.*), groupBy=false
query: B, metric: my.metric, alias: B, filter: my.attr=regexp(B.*), groupBy=false
The graph is correct with two time-series, but the labels just show A for each line.

opentsdb_filters

**Comment by utkarshcmu** [comment]
@amalshah Alias is broken for Opentsdb datasource. It will be resolved with the release of Opentsdb 2.3. You can track the progress of this Alias issue with #1876

**Pull request merged**
