### PR TITLE
Themes: align hover and focus opacity

### PR DESCRIPTION
**Pull request by Ijin08**
Hover now has the same opacity as focus. This helps when hovering selected elements that can be de-selected

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Comment by Ijin08** [comment]
@jackw Could you merge it. I am not authorised.

**Comment by torkelo** [comment]
@Ijin08 you have to run yarn start when updating theme colors, as we check in the generates sass theme files (that are built from the typescript theme)

**Comment by Ijin08** [comment]
Thanks @torkelo 
Been a while since I have done changes in the code.

**Pull request merged**
