### PR TITLE
Datasources: add new tab and feature toggle

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Add a new tab and a feature toggle to enable a new Enterprise feature (Datasource Insights)

### CODE REVIEW

**Review by alexanderzobnin — COMMENTED** [review]
Is it OK that we have 404 on the insights page? Looks like there's no route in grafana to that pages. Or it will be implemented in future PR?

**Comment by AgnesToulet** [comment]
Yes, I just created the other PR in the Enterprise repo.

**Comment by alexanderzobnin** [comment]
Maybe it makes sense to show this only in Enterprise version to prevent confused 404 if feature toggled in open source?

**Comment by AgnesToulet** [comment]
You shouldn't be able to see the Insights tab without an Enterprise license even if the feature is enabled.

**Review by alexanderzobnin — APPROVED** [review]

**Pull request merged**
