### PR TITLE
Alerting: Warn about missing contact-point in notification policy

### PR DESCRIPTION
**Pull request by gillesdemey**
When a notification policy does not have a contact point assigned it will swallow all alert instances that match it and will never deliver any notifications for them.

This might be intentional but it might also _not_ be. In which case we've decided to show a warning indicating that no particular contact point has been assigned and might have been a mistake.

This also applies to "parent" policies that might have child policies as the parent might still be matched.

image

### CODE REVIEW

**Review by VikaCep — APPROVED** [review]
👏 👏 👏

**Review by konrad147 — APPROVED** [review]
LGTM! 🎉 👏

**Comment by jtheory** [comment]
@dhalachliyski FYI :wave: 

This is one way to signal to the user that something in their config probably has bad effects.

UX thoughts in my mind (in case this is useful):
* Where are the other place that we signal dangerous config? Are we doing this consistently?
* Are there other impt places where we should flag bad config?
* Should we be more explicit about what this means? E.g. mouse-over this to see that "Alert instances that match this policy will not trigger any notification, because there's no contact point."

**Comment by gillesdemey** [comment]
> Should we be more explicit about what this means? E.g. mouse-over this to see that "Alert instances that match this policy will not trigger any notification, because there's no contact point."

This one I've included :D 

https://github.com/grafana/grafana/pull/60728/files#diff-710aa1b39780e0e09e286bd6c7d82cd4a1063978c05cab3e8b98dee12e0a3e30R138

**Pull request merged**
