### PR TITLE
Bump grabpl to 2.6.3

### PR DESCRIPTION
**Pull request by idafurjes**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Weird it failed with signature errors. Did you forget to sign latest changes?

**Review by dsotirakis — APPROVED** [review]

**Comment by idafurjes** [comment]
I did not, this is a new generated .drone.yml

**Comment by marefr** [comment]
@dsotirakis have any ideas of why CI is failing?

```
+ ./bin/grabpl verify-drone 112s
* Comparing .drone.yml and .drone.yml.bak 112s
* Ignoring a signature 112s
.drone.yml is out of sync with .drone.star - regenerate it with drone starlark convert
```

**Comment by dsotirakis** [comment]
@marefr, checking... Think someone with an outdated/updated version of drone pushed things, and format broke.

**Comment by marefr** [comment]
@dsotirakis ohh this is 8.2.x. Makes sense. In main/8.3.x we're using bingo for pinning the drone version I remember now - maybe need to backport that?

**Comment by dsotirakis** [comment]
@marefr yes that's an old version 😩 . We can backport bingo, but will require some manual work on starlark which I think it doesn't worth it. Let me find another way.

**Pull request merged**
