### PR TITLE
Prometheus: Run default labels query only once

### LINKED ISSUE #20512: Grafana stuck on high cardinality prometheus query
**What happened**:
When writing the labels in the query, for each character typed the client send an XHR request to the backend, when messing with high cardinality time series, it crashes the browser.

**What you expected to happen**:
There should be some grace period until I'll finish to type my query instead of sending a query for each character.

**How to reproduce it (as minimally and precisely as possible)**:
Search for high cardinality Prometheus metric, for example in Kubernetes you always have `container_memory_usage_bytes` and start typing labels: `{app="bla-bla-bla"}`.
You'll notice that after each character you send a query to the backend which returns very big results and crash the browser.

**Environment**:
- Grafana version: 6.5.1-beta
- Data source type & version: Prometheus 2.8.0
- OS Grafana is installed on: Linux
- User OS & Browser: MAC Chrome/Safari
- Grafana plugins: None

<a href="https://ibb.co/6y0kBhf">Screen-Shot-2019-11-20-at-13-46-45</a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

### PR DESCRIPTION
**Pull request by aocenas**
Continuation of: https://github.com/grafana/grafana/pull/20718
Closes: https://github.com/grafana/grafana/issues/20512

The caching check was fixed but still worked only after the request returned, if it took longer, any char input would trigger additional requests. This fixes it by using `_.once` meaning the load will be done only once during the lifetime of the `language_provider`. This seems to be good enough as we do not invalidate the cache anyway. This also adds a LRU cache for the requests, caching the promise which prevents both memory issues and prevents firing multiple requests before the first one comes back.

### CODE REVIEW

**Review by davkal — CHANGES_REQUESTED** [review]
Fetching of non-default label values is still happening unchecked (the else clause). 

Instead of ‘once’ I’d  probably would have simply set the cache value to an empty object when starting the request which would satisfy the if conditions before requests are triggered.

**Comment by aocenas** [comment]
So this got into a bit bigger refactor. Added LRU caching for the metric labels requests instead of unbounded custom one that was there. This should prevent some requests but also the request is based on the current state of the label values in the query, so if query changes by one char it still needs separate request. This is alleviated a bit by increasing a debounce in suggestion plugin so the suggestion loop isn't run that often.

The sizing of the LRU cache is kinda arbitrary right now but should help with some out of memory problems and can be tweaked later on if needed.

**Review by davkal — APPROVED** [review]
Tried it already. Works really well. Let's get this in ASAP.

LRU seems to be a pretty low-key dependency as well.

**Review by Estrax — APPROVED** [review]
LGTM. Really like the usage of LRU cache there.

**Pull request merged**
