### PR TITLE
hackathon: we tried

### PR DESCRIPTION
**Pull request by gabor**
WIP

### CODE REVIEW

**Comment by gabor** [comment]
status update: dear stalebot, please don't close it yet.

**Comment by torkelo** [comment]
@gabor add the "no-stale" label

**Comment by bergquist** [comment]
@gabor fine closing this now? :)

**Comment by gabor** [comment]
@bergquist sorry, could we keep it open for a little more time?

**Comment by matyax** [comment]
This can finally be closed.

**Pull request closed without merging**
