### PR TITLE
Move Gnocchi datasource to core plugins

### PR DESCRIPTION
**Pull request by sileht**
Hi,

This change is to propose the Gnocchi datasource
from the grafana-plugins repository to core plugins.

Cheers,

### CODE REVIEW

**Comment by sileht** [comment]
The remaining error into "ci/circleci" seems unrelated to my change. Can you confirm ?

**Comment by sileht** [comment]
I proposed a separate PR, for the test issue: https://github.com/grafana/grafana/pull/2717

**Comment by sileht** [comment]
I have just moved the tests to the new "typescript" format to resolve the merge conflict.

**Comment by sileht** [comment]
Last update moves to the new range.to/range.from format (with moment).

**Comment by sileht** [comment]
Any tips to progress on the merge of this ? What the next step for me ?

**Comment by torkelo** [comment]
Tips is getting more interest and +1 votes, but I am afraid that new official data sources are not going to be added any time soon, too many already

**Comment by torkelo** [comment]
pull requests that make working and adding plugins easier would be great though :)

**Comment by jd** [comment]
Here's my :+1: :)

**Comment by bergquist** [comment]
I'm closing this PR since the demand has not been big enough.

We are also working on how we can improve the plug-in support so we expect it to be easier to install plug-ins in the future.

**Comment by ccamacho** [comment]
+1 for me

**Comment by jklare** [comment]
would be great to see this merged

**Comment by bergquist** [comment]
@sileht any chance of you publishing this as an plugin on grafana.net? Just ping me if you need any help.

**Comment by sileht** [comment]
I already maintain it in my own gerrit, I have some update to do for grafana 3 first. And then I will add it to grafana.net.

**Comment by mrunge** [comment]
I'd be very interested in getting this

**Comment by paramite** [comment]
+1 on this PR

**Comment by mykaul** [comment]
+1 on getting it in.

**Comment by sileht** [comment]
The Gnocchi data source for Grafana 3.x is ready here: https://github.com/sileht/grafana-gnocchi-datasource

**Comment by dongfeichen** [comment]
Thanks for all your contribution to gnocchi.I'm a gnocchi user. I want to use gnocchi with grafa.
My openstack is mitaka version  , and I use Gnocchi2.1.4, Gnocchiclient2.2.0 and Grafana3.1 .  
So I configured CORS followed by this article:   http://gnocchi.xyz/2.1.4/grafana.html
I use direct mode to add gnocchi database.So I set Keystone URL which is os_auth_url , A user : "admin",A project: "admin" ,A password: "admin".
But get error: "Keystone failure: No response status code, is CORS correctly configured ?"
Could you help me? Thank you very much.

**Pull request closed without merging**
