### PR TITLE
Fix opentsdb testDatasource; Pull aggregator list from opentsdb

### PR DESCRIPTION
**Pull request by mxk1235**
Currently, the list of aggregators is hard-coded.  However, opentsdb exposes it via the /api/aggregators endpoint, and opentsdb-2.2 is going to support an expanded list of these.  ( https://github.com/OpenTSDB/opentsdb/pull/423 https://github.com/OpenTSDB/opentsdb/commit/e36927b00e5c13a1c9ef00895ccbb0ee58d5c7c4 )

this change makes the call to $scope.datasource for the list of aggregators, and overwrites the hard-coded setting if successful.

### CODE REVIEW

**Comment by mxk1235** [comment]
tested with Grafana-2.0.0-beta1 (which looks pretty awesome btw) and it works as well as it did with 1.9.1.

**Comment by mxk1235** [comment]
@torkelo could i bother you about this PR?  i can't really switch to using grafana fully without this feature.  i think it's fairly straightforward and doesn't break any other functionality.

**Comment by mxk1235** [comment]
ping @torkelo

**Comment by JacobVanAssche** [comment]
Is there a reason this hasn't been merged yet? This functionality is very useful and I would like to build the latest RPM with this in it.
@torkelo

**Comment by utkarshcmu** [comment]
+1

**Comment by mxk1235** [comment]
@torkelo i noticed you removed this patch from 2.1 and 2.2 milestones.  i also noticed the 2.5 milestone.  has there been a release plan change?

also, i am getting merge conflicts.  i can try to untangle it again, but at a high-level, did the datasources behavior change in some way?  thanks!

**Comment by torkelo** [comment]
yes, been a lot of updates to datasources, some big changes in next release hence the 2.5 version number

**Comment by torkelo** [comment]
oh, and sorry for pushing this forward, reason is simple that its low prio, not many +1 votes etc, limited time :(

**Comment by HallsHalls** [comment]
+1

**Comment by jejenone** [comment]
+1

**Comment by mirkof** [comment]
+1
so why was this not merged?

**Comment by torkelo** [comment]
It was not?

**Comment by mirkof** [comment]
sorry, my bad. 
keep up the good work. :)

**Pull request merged**
