### PR TITLE
Fix notifiers table

### PR DESCRIPTION
**Pull request by dg-nvm**
**What this PR does / why we need it**: fixes docs

**Which issue(s) this PR fixes**:  None

Fixes #

**Special notes for your reviewer**: cheers bro

### CODE REVIEW

**Comment by alkuzad** [comment]
if you want I can reopen with this account which has CLA signed

**Comment by torkelo** [comment]
yes, please do that, it would help ❤️

**Comment by torkelo** [comment]
the important part is the account the commit comes from, so might need to rebase with a git user that is part of your github account

**Comment by torkelo** [comment]
so acctually you do not need to re-open it, just redo the commit and force push

**Comment by alkuzad** [comment]
@torkelo ok, just this has to wait for end of weekend so I will have access to my work acc.

**Comment by dg-nvm** [comment]
@torkelo, done, recommited

**Comment by torkelo** [comment]
Still an issue with CLA, so fixed this manually. Thanks for your contribution

**Pull request closed without merging**
