### PR TITLE
support panel repeat for datasource template variable

### LINKED ISSUE #7030: [Feature request] Panel repeat for datasource template variables
In my env, we have several Prometheus server.
I want to create overall dashboard for these Prometheus server.

### PR DESCRIPTION
**Pull request by mtanda**
Fixes https://github.com/grafana/grafana/issues/7030 .

Not sure, this implementation has bad side effects...
Need to test.

### CODE REVIEW

**Comment by bergquist** [comment]
This could be really powerful. 

I've tested it and it works fine. The only issue is that its not possible to use the All option. Which makes sense when you think about it but it might be a good idea to hide that option in the template configuration page. What do you think?

**Comment by mtanda** [comment]
Oops, I overlook `includeAll` field.
Adding it, 'All' works fine now.

**Comment by mtanda** [comment]
@torkelo Would you review this?

**Comment by mtanda** [comment]
resolve conflict

**Comment by mtanda** [comment]
@torkelo I'm worried about this change might cause bug. sorry.

> It only works with panel repeats but people will enable multi selection on ds variable and expect it to work in other ways like normal muli variables which it does not.

I'm not sure such use case is really exist.

> Maybe this is better solved with richer support for scripted dashboards and other ways to build dynamic dashboards?

I already make scripted dashboard for this. But you already know, scripted dashboard is not user friendly.
It isn't appeared in dashboard list, we need to bookmark or embed link in text panel or something.
If Grafana treat scripted dashboard like other normal dashboard, it might be better.
But I still strongly want this feature.

Keep track the interest for this feature, please reopen https://github.com/grafana/grafana/issues/7030 .

**Comment by torkelo** [comment]
I would like this feature as well, but worried about the complexity cost and how to support and maintain this feature int the future. 

> But you already know, scripted dashboard is not user friendly. It isn't appeared in dashboard list.

Would like to revamp the scripted dashboard feature from the ground up to make it possible for them to show in the dashboard list (be saved to db) and also have some ui to pick options before it loads etc.

**Comment by mtanda** [comment]
> Would like to revamp the scripted dashboard feature from the ground up to make it possible for them to show in the dashboard list (be saved to db) and also have some ui to pick options before it loads etc.

That's a really good news for me if you improve scripted dashboard!

I'll look the bug and try to fix it. If it is easy to fix, I'll make a PR.

**Pull request merged**
