### PR TITLE
[wip] Rebase #13429

### LINKED ISSUE #1459: Localize time_format in graphs
Hello dear developers team.
Thank you for a awesome product, but I have one problem.

Now there is a hadcoded US date format in [time_format function](https://github.com/grafana/grafana/blob/master/src/app/panels/graph/graph.js#L373).
The most annoying case is display month and day. When I see something like "2/3" I'm a bit confused. Is it "the second of Mart" or "the third of February"?
The most sad thing, that I can't to configure this behaviour. 

Unfortunately the simplest way (and may be the most proper) doesn't help here. I mean [toLocaleString](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) with additional options. You can return different array of options instead of hardcoded format pattern and this method convert date in accordance with a right locale.
But in our case there is a jquery plot and it requires date format for converting timestamp by itself.

So, the second way is make some kind of mapping locale -> format array. [Example](http://stackoverflow.com/questions/2388115/get-locale-short-date-format-using-javascript/9893752#9893752). It seems a bit ugly. But it could be a single working solution.

May be I missed some obvious and better solutions. That's why I didn't create a pull request. =)

### PR DESCRIPTION
**Pull request by andig**
Rebase https://github.com/grafana/grafana/pull/13429
Fixes #1459

/cc @davkal it's really your PR

### CODE REVIEW

**Comment by andig** [comment]
I have rebased most parts now but cannot run the application locally:

    make run
    yarn start

When I access http://localhost:3000 I see:

If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build
4. Sometimes restarting grafana-server can help

yarn console shows build success, backend shows login, yet I don't see a UI:
````
INFO[08-21|13:39:43] HTTP Server Listen                       logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
INFO[08-21|13:42:11] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/public/build/grafana.dark.6582d69736700c8e807f.css status=404 remote_addr=[::1] time_ms=45 size=23070 referer=http://localhost:3000/login
````

Would like to proceed with this but now I'm stuck :(

**Comment by LiamClarkeNZ** [comment]
@andig Hi mate, came across your PR, have cloned your repo and will see if I can help with the issues you've encountered, as a Kiwi trying to introduce Grafana to our company, having the strange US date format thrust on us is actually a significant issue. 

No promises, but I'll see if I can help.

**Comment by davkal** [comment]
Quick reminder that #13429 did not succeed because only the month format was addressed. If someone would like to help us with this, I suggest starting a design doc (e.g., on Google docs) based on the feedback in #13429. I'm happy to guide you through this. First step should be to add a comment on #1459 about your intentions, then join the public slack at slack.grafana.com.

**Comment by davkal** [comment]
Not going forward with this, see also #13429

**Pull request closed without merging**
