### PR TITLE
(templating) reflect panel repeat status when variable updated

### PR DESCRIPTION
**Pull request by mtanda**
By https://github.com/grafana/grafana/pull/4281 , template variable can be refreshed when time range changed.
This PR reflect variable changed to panel repeat status.

### CODE REVIEW

**Comment by mtanda** [comment]
I consider to use this with Auto-refresh.
Use this with https://github.com/grafana/grafana/pull/5007 , the dashboard only show graphs of current active host.

**Comment by torkelo** [comment]
not sure it is a good idea to rebuild the dynamic dashboard on every time refresh

**Comment by mtanda** [comment]
I can add check if list of variable values is changed, and change the code like "update only if changed".
I mentioned about auto-refresh, but main use case is time range changed.

This is useful for the very dynamic environment like AWS, auto scaling feature create/delete instance very often. 
Without this feature, there are too many EC2 instance graphs which isn't alive in the time range.

**Comment by torkelo** [comment]
that sounds like good idea

**Comment by mtanda** [comment]
I add variable update check code.

**Comment by torkelo** [comment]
did some refactoring to fix some issues and minor clean up:
https://github.com/grafana/grafana/commit/7c7e26bc181e6898438f1111810d53898b2a2fd7

**Comment by mtanda** [comment]
Wow, thanks! I really want this feature!!

**Pull request closed without merging**
