### PR TITLE
fix: remove $$hashKey from dashboard json export

### PR DESCRIPTION
**Pull request by eMerzh**
Hi,

here is a quick fix for #11551 
As @bergquist  suggested, we should only using angular instead of JSON to stringify the json.

### CODE REVIEW

**Comment by torkelo** [comment]
There should be no $$hashkey properties returned by getSaveModel so this is the wrong place to do this. Strange , unable to replicate your original issue , can you replicate this on new dashboard , what steps does it require?

**Comment by eMerzh** [comment]
i was able to replicated ...
you can do it by adding an annotation (even on the first dashboard on play.grafana.com )

you seems to suggest it's not the good place to do it, do you have any suggestion?

**Comment by torkelo** [comment]
Probably somewhere in the getSaveModel function chain, as we do not want to persist these angular properties either

**Comment by eMerzh** [comment]
@torkelo couldn't really find a way to sneak in the model, but i think i found the code that create the issue.
Is it a good way to go ?

**Comment by torkelo** [comment]
yes! that is much better.

**Comment by eMerzh** [comment]
Cool 🤗... Something else missing?

**Review by torkelo — CHANGES_REQUESTED** [review]

**Pull request merged**
