### PR TITLE
elasticsearch alerting

### PR DESCRIPTION
**Pull request by lvheyang**
* This pull request is my work on the elastic search alerting issue. https://github.com/grafana/grafana/issues/5893

Aggregation Metrics Supported (done)

- [x] Count
- [x] Avg
- [x] Sum
- [x] Min
- [x] Max
- [x] Percentiles
- [x] Extended Stats
- [x] Cardinality
- [x] Moving Average
- [x] Derivative

Aggregation Type supported (done)

- [x] Terms
- [x] Filters
- [x] Cardinality
- [x] Histogram
- [x] DateHistogram

Features Not Supported (won't be included in this pr)

- [ ] Aggregations' Missing Value parameter
- [ ] Extended  Stats' Sigma parameter
- [ ] Extended  Stats' std_deviation_bounds result

### CODE REVIEW

**Comment by torkelo** [comment]
this this based on https://github.com/grafana/grafana/tree/alerting-elasticsearch or have you implemented this from scratch?

**Comment by torkelo** [comment]
this is looking really good!

**Comment by lvheyang** [comment]
yes, i implemented this from scratch. since the alerting-elasticsearch branch is too far behind the master, I found difficult to modify.  :-)

**Comment by cherweg** [comment]
@lvheyang : I´ve tried your pull request, to see the elasticsearch alerting in action.
But ... When testing a simple series alarm, i got an error:
```
error tsdb.HandleRequest() error elastic: Error 400 (Bad Request): Validation Failed: 1: no requests added; [type=action_request_validation_exception] 
```

Any hints?

**Comment by lvheyang** [comment]
@cherweg sorry, i cannot reproduce this error.  Would you mind post the query, group by conditions, and the metrics you selected, to help me reproduce your condition? Thx

**Comment by cherweg** [comment]
@lvheyang : It was my fault...the elasticsearch datasource uses [msearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html).
```
1st Request:   header\n
2nd Request:  body\n
```
This is a problem behind a non sticky Loadbalancer 

thank you for your great work.

regards
Christian

**Comment by hc4** [comment]
Could this PR be merged into 4.4.4 branch?

**Comment by biro11** [comment]
Hello, Elasticsearch alerting feature is also available in the newest nighlty 5.x builds?

**Comment by Fumler** [comment]
I am getting `tsdb.HandleRequest() error type assertion to string failed`

Grafana built from source https://github.com/lvheyang/kirk-grafana/tree/cwz4.4.1
Elasticsearch 5.4.0

Metric http://d.pr/i/qBA4lB
Alert http://d.pr/i/gIKNlb

Any ideas?

**Comment by lvheyang** [comment]
@Fumler you can fill the Query condition with "*" to workaround. 
I will fix it next week. Thanks for your testing.

**Comment by Fumler** [comment]
@lvheyang I don't understand, where do I set "*"?

**Comment by cherweg** [comment]
@Fumler : your Elasticsearch Query is "" try "*"

**Comment by Fumler** [comment]
@cherweg aha, thanks!

**Comment by jhpanetta** [comment]
I have some issues when setting up alerting:
* Switching to the `Alert` tab causes a javascript error (from `alert_tab_ctrl.js` `ds.targetContainsTemplate is not a function`.  That function is not defined in `public/app/plugins/datasource/elasticsearch/datasource.js`)
* In the `Notifications` portion of the `Alert` tab, the `send to` setting is not sticky:  It does not get saved into `...alert.notifications` in the export json.  (See fragment below)

Also, the first issue seems to imply that the data source may not contain templating.  Does this mean that the query used may not contain a template parameter?  (See fragment below)

alert json fragment:
```
"alert": {
  "conditions": [
    {
      "evaluator": {
        "params": [
          0.7
        ],
        "type": "lt"
      },
      "operator": {
        "type": "and"
      },
      "query": {
        "params": [
          "A",
          "5m",
          "now"
        ]
      },
      "reducer": {
        "params": [],
        "type": "count"
      },
      "type": "query"
    }
  ],
  "executionErrorState": "alerting",
  "frequency": "60s",
  "handler": 1,
  "message": "$ingest_kiosk_name is down",
  "name": "Panel Title alert",
  "noDataState": "no_data",
  "notifications": []
},
```

Query json fragment:
```

"targets": [
  {
    "bucketAggs": [
      {
        "field": "time",
        "id": "2",
        "settings": {
          "interval": "1m",
          "min_doc_count": 0,
          "trimEdges": 0
        },
        "type": "date_histogram"
      }
    ],
    "dsType": "elasticsearch",
    "metrics": [
      {
        "field": "select field",
        "id": "1",
        "type": "count"
      }
    ],
    "query": "event:Heartbeat AND process:sync_driving_data AND beat.hostname:\"$ingest_kiosk_name\"",
    "refId": "A",
    "timeField": "time"
  }
],
```

**Comment by jhpanetta** [comment]
OK, ignore me on the notifications not saving above -- I hadn't set up any and that's what it required.  The traceback and question about templating remain.

**Comment by Yakud** [comment]
I have a error:


How I can fix it?

**Comment by Yakud** [comment]
I found how to fix this problem. I just init new elastic connection with transport InsecureSkipVerify param:

```go
httpClient := elastic.SetHttpClient(&http.Client{
  Transport: &http.Transport{
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // ignore expired SSL certificates
  },
})

cli, err := elastic.NewSimpleClient(url, basicAuth, httpClient)
```

**Comment by cmclaughlin** [comment]
I built this and started running it on a new instance.  It's awesome... thank you!

It would be to get it merged before v5 :)

**Comment by Yakud** [comment]
I try to use alert to percentiles metric but have a wrong behavior:
In metrics section i set only 75 percentile:

When i tested my alert rule i see another percentiles:

What i an doing wrong?

**Comment by brookssw** [comment]
> It was my fault...the elasticsearch datasource uses msearch.
> 
> 1st Request:   header\n
> 2nd Request:  body\n
> This is a problem behind a non sticky Loadbalancer
> 
> thank you for your great work.
> 
> regards
> Christian

@cherweg could you let me know how you resolved this? I have the same situation.

**Comment by cherweg** [comment]
@brookssw: For testing purposes i used a Single client-node.
After that i reconfigured my LB to be sticky by client-ip.

Regards
Christian

**Comment by lvheyang** [comment]
@Yakud Thank you for your comment, I've fixed this bug, you can sync this branch for verification.

**Comment by lvheyang** [comment]
@Fumler  Now I will replace empty query string to wildcard "*", thanks for your comment.

**Comment by jakijako** [comment]
Hi lvheyang !
I'm new to githut, so please, would you tell me where can i download you work about alerting with Elastic on Grafana ?
Running grafana v.4.4.3.1
thx :)

**Comment by missmaggiemo** [comment]
Is there any plan for this work to include queries built with templating variables? E.g.,
screen shot 2017-09-19 at 3 32 58 pm

I tried to create an alert based off of this graph, and it keeps saying "no data" when there is most certainly data.
screen shot 2017-09-19 at 3 34 36 pm

**Comment by lvheyang** [comment]
@missmaggiemo sorry, this feature would not be included in this pull request. I guess  https://github.com/grafana/grafana/issues/6557 is the issue you are looking for.

**Comment by rdsubhas** [comment]
@missmaggiemo yep grafana in general does now allow alerting with variables for all backends. You have to create a separate query without variables, hide it, and use that for alerting

**Comment by lvheyang** [comment]
hello @torkelo @bergquist , this feature was used in our production environment steadily for few months (so does some other github users). 
Do you think this pr should be merged? If your answer is yes, I want to know when to merge this pr. I want to get the time table of release 5.0. 

Thanks

**Comment by caneraydinbey** [comment]
We need to use alerting on elastic search. When can this feature be merged?

**Comment by icy-arctic-fox** [comment]
Thanks for getting this up to date with master. I was previously rebasing your code off of v4.5.2. This is much better. We have been using this in production for a while, and it has been solid.

For anyone with trouble building it, this is the Dockerfile I use:
https://gist.github.com/icy-arctic-fox/0a7dcced3ac1320e2e2fb2fdb39853e5

**Comment by rdsubhas** [comment]
Really looking forward to seeing this 👍

**Comment by bondeg** [comment]
Looks great

**Comment by berglh** [comment]
Cheering :+1:

**Comment by bondeg** [comment]
We've got an error with alerting.

We try to monitoring query like that:
Query

As you can see, data exists, but we haven't data for last 10 min due tech reason.
Graph example

But we got an alert while sum of values greater than 10.
Alerting settings

Grafana v4.7.0-pre1 (commit: eb949d6)

**Comment by leehambley** [comment]
> But we got an alert while sum of values greater than 10.

You have the setting "if no data or all values are set to null" set to "alerting", doesn't that mean this is working correctly?

**Comment by bondeg** [comment]
@leehambley 
> all values

Is the key. In our case not all values = 0 and data present. If change this option to `Ok` alert still exists.

**Comment by m2b** [comment]
@bondeg what does this all mean?  How do I get this onto my system?  Can I just upgrade?  To what version?

**Comment by arwineap** [comment]
@m2b They are hoping for q1 2018 (version 5.1)

https://github.com/grafana/grafana/issues/5893#issuecomment-344549566

**Comment by MarvAmBass** [comment]
hey guys sorry to bother everyone (wouldn't know where to post this since it's not official at the moment).

in the currently not merged branch I get the following error:

```
error:"tsdb.HandleRequest() error Get https://elasticsearch:9200/_msearch?pretty=true: x509: certificate signed by unknown authority"
```

I'm using a self signed certificate, but I also configured Grafana to skip TLS verification for this datasource.

Somehow the alerting implementation seems to have a problem with it.

@lvheyang maybe you can have a look - thanks

great feature by the way! thanks for the effort

**Comment by nhuray** [comment]
Hi guys any news on this feature ?

**Comment by ssoto** [comment]
More than one year later... Why don't you merge it?

**Comment by andydavidsmith** [comment]
Are you trying to keep this feature out for any reason

**Comment by rdsubhas** [comment]
@ssoto @andydavidsmith its answered before, they have a big release coming up with Grafana 5.0 (lots of core changes, grids, dashboards, etc) and don't want to pull in more stuff at this point. As per https://github.com/grafana/grafana/issues/5893#issuecomment-344549566 it could be planned for Grafana 5.1

**Comment by torkelo** [comment]
> Are you trying to keep this feature out for any reason 

No not at all, it's just that this is pretty massive PR that requires a lot of refactoring & testing and thought before merging and sadly had to prioritize other issues.  

This PR has support for both Elasticsearch v2 and v5, think we can drop support for v2. Is using elasticsearch golang library needed or can we do without it?

**Comment by leehambley** [comment]
> This PR has support for both Elasticsearch v2 and v5, think we can drop support for v2. 

I would tend to agree, at least we could decide only to support v5 to get this done. If lots of people using ancient ES with cutting edge Grafana come out of the woodwork we can look more into it.

> Is using elasticsearch golang library needed or can we do without it?
 
I 'm quite sure it's superfluous. `393` of the `415` changed files in the PR are pulling in this 3rd party lib that doesn't seem to be used in any big way, just for wrapping a standard HTTP client. At least from Ruby experience with ElasticSearch I can say that most of the time you don't need a "client" except for building queries which seems to be handled differently in our `tsdb` package that is common to all Grafana code.

- https://github.com/grafana/grafana/pull/8934/files#diff-2eaf2dfee35a2d86473cc6e1afc60304R19-22

**Comment by pakerwe** [comment]
Hi, elasticsearch doing paging where maximum data to return is 10, i made some stupid hack to fix this:

`currAggregation := elastic.NewTermsAggregation().MinDocCount(minDocCount).Field(field).Size(1000000)`

this is due to we can't set size to unlimited [https://github.com/olivere/elastic/issues/519](url)

**Pull request closed without merging**
