### PR TITLE
Docs: Add document for jsondata field `alertmanagerUid`

### PR DESCRIPTION
**Pull request by phongvq**
jsondata fields `alertmanagerUid` can be used to specify Alert Manager for a particular Prometheus/Loki data source.

### CODE REVIEW

**Comment by phongvq** [comment]
Please help to add necessary labels for it, since I don't have permission to do it I think.

**Comment by mellieA** [comment]
Thank you for contributing @phongvq! I've added the labels :)

**Review by gguillotte-grafana — APPROVED** [review]
I'm wary about the extraneous table formatting changes; they pass `prettier` but might complicate backporting.

**Comment by gguillotte-grafana** [comment]
Yep - table formatting changes have botched the table output. Will follow up and manually backport.

**Pull request merged**
