### PR TITLE
Web app manifest

### LINKED ISSUE #21905: Always Loading Bar on Top After Adding to Home Screen iOS
**What happened**: I use grafana on iPhone and iPad mostly. When I click the "Add to Home Screen" button, an icon appears. When I click it; grafana shows as usual however there's always a loading bar at the top. Since there is a loading bar; it also displays the URL which under normal circumstances it doesn't so Grafana doesnt fit properly.
Sample_Grafana

**What you expected to happen**: Grafana should fit to screen perfectly without a loading bar and URL at the top.

**How to reproduce it (as minimally and precisely as possible)**:
Well, you can try your own grafana installation. I'm not sure if this happens only on mine. Don't know any other grafana instances to check.

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.6.0
- Data source type & version: InfluxDb
- OS Grafana is installed on: Debian Docker
- User OS & Browser: iOS Safari
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by Park0**
Fixes #21905

Help wanted to verify this on different kind of iOS devices (@mckn)

### CODE REVIEW

**Comment by Park0** [comment]
@dprokop @marefr please review/comment

**Comment by Park0** [comment]
@dprokop @marefr please review/comment

**Comment by mckn** [comment]
Hello and thank you for adding this! I was trying to test this by running Grafana locally and I used an iOS 13.5 client but I still get the url-field/loading header described in the issue.

Any ideas on how to test this properly? @Park0

**Comment by mckn** [comment]
> Hello and thank you for adding this! I was trying to test this by running Grafana locally and I used an iOS 13.5 client but I still get the url-field/loading header described in the issue.
> 
> Any ideas on how to test this properly? @Park0

Trying to run it via HTTPS now. See if that helps.

**Comment by mckn** [comment]
> > Hello and thank you for adding this! I was trying to test this by running Grafana locally and I used an iOS 13.5 client but I still get the url-field/loading header described in the issue.
> > Any ideas on how to test this properly? @Park0
> 
> Trying to run it via HTTPS now. See if that helps.

Same issue when running via HTTP. Please give me some instructions on how to verify this @Park0 so we can get this one merged into master. Thanks for the help and contribution 🙏

**Review by mckn — CHANGES_REQUESTED** [review]
Need instructions on how to verify this before we can continue the review.

**Comment by Park0** [comment]
U have to use Google chrome on android or IOS (i do not have a IOS devices so i did not test it) with https. 
Go to your grafana page. Open your settings. Chose the option add to start screen (or homescreen or something). 
Add the icon.
If u launch the application on your home screen u won't see a address bar. But it will show like a app.

**Comment by mckn** [comment]
> U have to use Google chrome on android or IOS (i do not have a IOS devices so i did not test it) with https.
> Go to your grafana page. Open your settings. Chose the option add to start screen (or homescreen or something).
> Add the icon.
> If u launch the application on your home screen u won't see a address bar. But it will show like a app.

Hello,

So this is exactly what I did. I am using an iOS device and the address bar is still displayed when opening Grafana via the home screen link. So I think this one need some more work before we can merge it.

**Comment by Park0** [comment]
I do not own a IOS device. So it may take some time for me to test this.

**Comment by mckn** [comment]
> I do not own a IOS device. So it may take some time for me to test this.

Ah, I understand. I will try to help out here as much as I can. Do you have any resources to what needs to be done to get this working in iOS?

**Comment by Park0** [comment]
In the issues was linked to https://developer.apple.com/forums/thread/123486

**Comment by Park0** [comment]
@mckn did u test on a SSL encrypted version? Else it won't work.

**Comment by mckn** [comment]
> @mckn did u test on a SSL encrypted version? Else it won't work. I had someone try it on my instance and it worked as expected

Yes, I tried it via ngrok with SSL.

**Comment by mckn** [comment]
I will close this one until we have someone with an iOS device that can put some time to look into this one.

**Comment by Park0** [comment]
@QazCetelic Just apply the patch on your system. The changes are quite simple. U could do it manually. Than test it on a iphone. Make sure your test site runs https with letsencrypt.

**Comment by dugite-code** [comment]
@Park0 I've just tested this in android without any issues. I do note you didn't include the `"display":"standalone",` I wonder if ios requires more than chrome for a basic pwa?

Nginx config
```
sub_filter </head>
  '</head><link rel="manifest" href="/public/manifest.json">';
sub_filter_once on;
```

Then I added a volume to docker compose
```
    volumes:
      - ./volumes/manifest.json:/usr/share/grafana/public/manifest.json:ro
```

manifest.json
```
{
  "name": "Grafana",
  "short_name": "Grafana",
  "description": "Graphs for everyone everwhere anyhow",
  "start_url": "/",
  "background_color": "#000000",
  "theme_color": "#0f4a73",
  "display":"standalone",
  "icons": [{
    "src": "public/img/fav32.png",
    "sizes": "32x32",
    "type": "image/png"
  }]
}
```

**Pull request closed without merging**
