### PR TITLE
SQLStore: Close session in withDbSession

### LINKED ISSUE #31771: Database connection leak?
**What happened**:
Report of potential database connection leakage in the `sqlstore.withDbSession` function: https://github.com/grafana/grafana/issues/15316#issuecomment-785932485

**What you expected to happen**:
No leaked connections.

**How to reproduce it (as minimally and precisely as possible)**:
4 places in the code using this function. Suppose executing the code in these places and verify amount of connections in use with/without closing the connection.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master (451fdd4cda30ac9ae6b3a3fc98514f4d48b77077)

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Make `sqlstore.withDbSession` close the session on return, just as `SQLStore.WithDbSession` does, to avoid leakage. Also, make `SQLStore.ensureMainOrgAndAdminUser` use `SQLStore.WithTransactionalDbSession` in order to avoid it using `SQLStore.WithDbSession`, so you avoid requiring the latter to support a session stored in the context. AFAICT, this rewritten code is functionally equivalent to the old one, just easier to follow.

I would recommend diffing locally in a graphical tool, since a lot of the changes are just whitespace.

Fixes #31771.

### CODE REVIEW

**Comment by torkelo** [comment]
I think the caching/session reuse is to be able to share sql code within a single transaction, think @bergquist add this 
https://github.com/grafana/grafana/blob/9593d57914c2058ad577209394f80b8d743e7f5e/pkg/services/sqlstore/transactions.go#L26

**Comment by aknuds1** [comment]
@torkelo with session caching, how are you able to free the session after use (after the request processing is over?)?

**Comment by torkelo** [comment]
I have no idea, looks like something that was missed when this was added

**Comment by aknuds1** [comment]
@torkelo maybe it's better to make withDbSession/WithDbSession work independently of this cache that other functions might use?

**Comment by torkelo** [comment]
yea agree that, think when we need to reuse sql operations within different transactions/operations we can extract functions that can take in a session maybe?

**Comment by marefr** [comment]
> I think the caching/session reuse is to be able to share sql code within a single transaction

Yes. Think this PR should bring some historic context #12203. 

As an example I think this code is currently wrong given WithDbSession will close the session (and by that rollback the transaction). Not sure it has any effect though, maybe if starting multiple Grafana instances first time?
https://github.com/grafana/grafana/blob/5645b11e91fea42e074d22e838ec1b97388035a8/pkg/services/sqlstore/sqlstore.go#L145-L148

>  have no idea, looks like something that was missed when this was added

Yeah seems almost like withDbSession/WithDbSession was introduced solely with transactions in mind where transactions would commit/rollback and close the session outside of these.

**Comment by aknuds1** [comment]
> > I think the caching/session reuse is to be able to share sql code within a single transaction
> 
> Yes. Think this PR should bring some historic context #12203.
> 
> As an example I think this code is currently wrong given WithDbSession will close the session (and by that rollback the transaction). Not sure it has any effect though, maybe if starting multiple Grafana instances first time?
> https://github.com/grafana/grafana/blob/5645b11e91fea42e074d22e838ec1b97388035a8/pkg/services/sqlstore/sqlstore.go#L145-L148

Thanks @marefr for finding this usage of WithDbSession. I would suggest that the code you linked to avoids using WithDbSession and instead extracts the transaction from the context. It will be way less confusing, and will leave WithDbSession far less schizophrenic. WDYT? @torkelo?

**Comment by aknuds1** [comment]
@torkelo @marefr @bergquist please see the updated PR; I simplified the semantics of WithDbSession/withDbSession so that they never take a session on the context, and always close the session after use. To reach this goal, I also simplified `SQLStore.ensureMainOrgAndAdminUser` to use `SQLStore.WithTransactionalDbSession`.

**Comment by bergquist** [comment]
Nasty. This seems like unfinished work from my side. Not sure why. (I blame parental leave!)

This looks simpler but by not taking the session from the context we would have to verify that we dont start any transactions and then make updates using `withDbSession` as the inner DB operation would not be performed within a transaction.

I dont know how frequently that is but not being able to combine two DB operations into one in a simple way has been quite frustrating many times as it adds lots of code whenever we want to combine two operations. 

I think another solution would be to only close the session in `withDbSession` if you opened it. Thereby delegating that responsibility to the first caller.

**Comment by aknuds1** [comment]
@bergquist do you think there is any real problem with following the pattern I implemented in the PR though? I think the benefits outweigh any drawbacks, since the code becomes self explanatory and easy to follow for a reader. If a function should be performed in a transaction, I do think the right solution is to create a transactional session as I do in the PR, and pass it down. It makes the job of understanding the code (and avoiding bugs) much easier.

**Comment by bergquist** [comment]
With this solution, you need to expose `DBSession` everywhere a transaction is started and I'm not a big fan of that since all SQL statement outside the `sqlstore` package would have to reference `sqlstore` which I dont like since it's so big. The current idea (ignoring this bug) tried to avoid that. Starting transactions/sessions everywhere are quite repetitive and usually something that makes sense to solve with some kind of abstraction IMO. 

Having to create two function signature to support creating its own transaction or using the passed one is also quite annoying Ex https://github.com/grafana/grafana/pull/31775/files#diff-1f3c7427a56d224b852bab495861c8e746504825cb669b06d84079ff8b3a53f7R36

I think the best solution would be to move the DBSession + database related code to its own package and let sqlstore and "none sqlstore database code" depend on that new package. But that's too much for a patch release IMO. So I think we should merge this once we verified that we dont really on chained transactions somewhere and improve later.

**Comment by aknuds1** [comment]
@bergquist OK, sounds as if we should make an issue to investigate your proposed improvement.

**Comment by bergquist** [comment]
I think it would be cleaner if only the function that opens the session closes it as it would be more consistent.

**Comment by marefr** [comment]
@bergquist In my head my suggestion would do this unless a transaction is already started and the transaction is responsible for rollback/commit and closing the session. Your suggestion sounds like it requires a lot more changes to get right? Maybe you can provide more information

**Comment by aknuds1** [comment]
> What about doing something like this and only close the session if there's no transaction started?
> 
> ```diff
> diff --git a/pkg/services/sqlstore/session.go b/pkg/services/sqlstore/session.go
> index c6c0176d0e..83d64037fe 100644
> --- a/pkg/services/sqlstore/session.go
> +++ b/pkg/services/sqlstore/session.go
> @@ -9,7 +9,8 @@ import (
>  
>  type DBSession struct {
>         *xorm.Session
> -       events []interface{}
> +       events             []interface{}
> +       transactionStarted bool
>  }
>  
>  type dbTransactionFunc func(sess *DBSession) error
> @@ -42,6 +43,7 @@ func startSession(ctx context.Context, engine *xorm.Engine, beginTran bool) (*DB
>                 if err != nil {
>                         return nil, err
>                 }
> +               newSess.transactionStarted = true
>         }
>         return newSess, nil
>  }
> @@ -52,7 +54,10 @@ func (ss *SQLStore) WithDbSession(ctx context.Context, callback dbTransactionFun
>         if err != nil {
>                 return err
>         }
> -       defer sess.Close()
> +
> +       if !sess.transactionStarted {
> +               defer sess.Close()
> +       }
>  
>         return callback(sess)
>  }
> @@ -63,6 +68,10 @@ func withDbSession(ctx context.Context, callback dbTransactionFunc) error {
>                 return err
>         }
>  
> +       if !sess.transactionStarted {
> +               defer sess.Close()
> +       }
> +
>         return callback(sess)
>  }
> ```

@marefr I read your suggestion again and I think it's clearer to me than first time I read it. Can you exemplify with valid use cases where a transaction would be started and `withDbSession` shouldn't close the session?

**Review by bergquist — APPROVED** [review]
LGTM! 

I've checked all usages of `withDbSession` and this should work as expected. 

Looking forward to seeing if the affects the number of open connections in HG :)

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
