### PR TITLE
DOCS REMOVE uuid

### PR DESCRIPTION
**Pull request by mattclegg**
DOCS REMOVE uuid

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
Hi, thanks for the PR!

I'd like to understand the change a little before I merge this. My understanding is that setting a UID is important so that you can consistently reference the data source in other provisioning. What is the reason for wanting to remove the UID?

**Comment by mattclegg** [comment]
The uuid isn't relevant in this context. It was probably just copied when this example was created but it's not needed if it's not referenced elsewhere.

Or, the example should be a readable value like the values used in datasourceUid (in the same file).

**Review by jdbaldry — COMMENTED** [review]
@knylander-grafana I wonder if this snippet should have [placeholder variables](https://grafana.com/docs/writers-toolkit/write/style-guide/write-for-developers/#placeholder-variables) for all the `uid` and `datasourceUid` fields.

Then we'd need a bit of preamble that explains how to set them. It's present in the YAML comments for [`tracesToLogsV2`](https://github.com/grafana/grafana/pull/93183/files#diff-0bf2718c882c81c8d5f3fea951e7768f3a51388d1f41c80772c86dbfeb15ebf5L390-L391) but I think it's necessary for all of them.

**Comment by knylander-grafana** [comment]
@jdbaldry i'm not sure. We can investigate and figure out what the needs might be. I'm not sure if this snippet is used in other docs or not. 

Can you use variables to do replacements when they are in a code block?

**Comment by jdbaldry** [comment]
> @jdbaldry i'm not sure. We can investigate and figure out what the needs might be. I'm not sure if this snippet is used in other docs or not.

I'm not sure I understand.

My understanding of UIDs are they are specific to individual installations so should be decided by the user when they are provisioning so that they can reference them in other parts of the provisioning. That makes them something that should be specified using a placeholder variable in the snippet so that the user knows to update them. To help them decide, we can explain what that UID is and given an example and that should come in the preamble before the provisioning snippet.


> Can you use variables to do replacements when they are in a code block?

Not yet but I'd love to have that feature. It's gonna be something for the Docs platform team to implement.

**Comment by knylander-grafana** [comment]
> > @jdbaldry i'm not sure. We can investigate and figure out what the needs might be. I'm not sure if this snippet is used in other docs or not.
> 
> I'm not sure I understand.

Ah! I thought you meant replace the UID with an actual variable that Hugo would process, not to just use a <UUID> and then explain that in the text outside of the snippet (or we could use <UUID> # Comment with explanation

> My understanding of UIDs are they are specific to individual installations so should be decided by the user when they are provisioning so that they can reference them in other parts of the provisioning. That makes them something that should be specified using a placeholder variable in the snippet so that the user knows to update them. To help them decide, we can explain what that UID is and given an example and that should come in the preamble before the provisioning snippet.

Thank you. Your explanation here helped clarify some confusion I had. 

> > Can you use variables to do replacements when they are in a code block?
> 
> Not yet but I'd love to have that feature. It's gonna be something for the Docs platform team to implement.

oOoO! This could be a really cool feature! :)

**Comment by mattclegg** [comment]
A comment ~datasourceUid stating the above might make more sense.

**Pull request closed without merging**
