### PR TITLE
Encryption: Store 'alertmanager_configuration' as JSON string instead of raw bytes

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

The `re-encrypt` CLI command we introduced [here](https://github.com/grafana/grafana/pull/41454) is working properly in terms of functionality. However, the behavior of that CLI command is slightly different than expected because, once secrets present on `alert_configuration` table are re-encrypted, contents from the `alertmanager_configuration` column are stored as raw bytes instead of a plain string (containing the JSON value), which is the default formatting used by the alerting code.

So, changes on this pull request basically advocate for storing these contents as JSON string instead of raw bytes.

**Special notes for your reviewer**:

**Funny take-away from this minor fix** 👉🏻  if you use the IntelliJ embedded DB explorer, you need to be aware that it implicitly translates raw bytes into JSON string for the sake of DX, that was precisely what made me don't detect that behavior while working on the original pull request.

### CODE REVIEW

**Review by undef1nd — APPROVED** [review]

**Review by AgnesToulet — APPROVED** [review]
LGTM!

**Comment by davidmparrott** [comment]
@joanlopez can you hold off merging for the time being? I would like to get more context about why we're doing this and I think @gotjosh has some questions as well. Thank you!

**Comment by joanlopez** [comment]
> @joanlopez can you hold off merging for the time being? I would like to get more context about why we're doing this and I think @gotjosh has some questions as well. Thank you!

Sure, not urgent at all because the "impact" is minimal and behind a feature toggle (under customer's responsibility).
So, let's discuss it today before merging! Feel free to reach me out during the day @gotjosh @davidmparrott 

Thanks!! 🙌🏻

**Review by gotjosh — APPROVED** [review]
LGTM

**Pull request merged**
