### PR TITLE
remove alias from postgres $__timeGroup macro, add $__timeGroupAlias macro to all sql datasources

### LINKED ISSUE #12749: [postgres] $__timeGroup macro without alias
The ```$__timeGroup``` macro is at the moment handled differently between the sql datasources. Postgres is the only one that adds a column alias to make it more convenient to use. Since you can reference columns by their index there was no need to have it without alias for GROUP BY or ORDER BY. Unfortunately you cannot always reference columns by index for example in window functions ORDER BY 1 will not reference the first column but 1 will be interpreted as literal.
For the window function use case it would be very useful to have a $__timeGroup macro that doesn't add an alias. 

Should the postgres $__timeGroup macro be changed to make it identical to the other sql datasources or should another macro be added which doesn't add an alias. 
Changing the postgres macro will be a breaking change.

### PR DESCRIPTION
**Pull request by svenklemm**
This changes the postgres $__timeGroup macro to no longer include the alias so it can be used as part of ORDER BY clauses in window functions.

This also adds a  new macro $__timeGroupAlias to all sql datasources which is identical to $__timeGroup but adds an "AS time".

Fixes #12749

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
As I wrote in issue
> Long term having another macro which basically does the same thing will probably lead to more confusion than introducing a breaking change.

In window function you can only reference by column or query and not index?

> Maybe possible to interpret timeGroup not having an alias and add it for backward compatibility?

I understand that you'll need to find the timeGroup macro in the select clause for this to work, right? But should be possible. This would probably be the cleanest solution.

**Comment by svenklemm** [comment]
Yes in window functions you can not reference by column index but you can use columns or expressions.
But if you pair window functions with aggregates then you need to use the same expression for order as you use in your group by or postgres will complain that this is not a column you can reference.

In the following query in the OVER clause the order by 1 will not reference the $__timeGroup expression but 1 will be interpreted as literal.
```
SELECT
  $__timeGroup(time,1m),
  host AS metric,
  sum(sum(interrupts)) OVER (PARTITION BY host ORDER BY 1) AS "interrupts"
FROM kernel
WHERE
  $__timeFilter(time)
GROUP BY 1,2
ORDER BY 1
```

**Comment by svenklemm** [comment]
I've added some compatibility code and also added $__timeGroupAlias to the other sql datasources.

**Review by marefr — APPROVED** [review]
Looks good :+1:

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
