### PR TITLE
Alerting: Export of contact points to HCL

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
This PR introduces support for the export of contact points to HCL. 
1. The Terraform schema for contact points is very different from the API models:  it is strongly typed whereas the API model is a JSON blob. To make it work with HCL I had to implement new API models that for now are used only for export to API. 
2. The introduced models are pretty similar to the models described in the alerting repository with the only difference that optional fields are pointers. This is needed because the HCL encoder does not have any analog to JSON's "omitempty".
3. The PR contains two adapter functions: one is used to convert `ContactPointExport` to the new `ContactPoint` and is used in production code, whereas the second one is used only in tests and converts the new integration API model back to raw but this time its APIReceiver because it's simpler to assert the models in the tests.
4. I introduced the Secret type which is alias for string and currently, it is used to just indicate the fields that are secret.

**Why do we need this feature?**
This will let users export the contact point configuration in HCL format.

**Who is this feature for?**
Users of Grafana Terraform Provider.

**Special notes for your reviewer:**
I used the following configuration to test the endpoint. I created this config via UI to make sure that the field names are all correct. You need to build a Terraform provider to include https://github.com/grafana/terraform-provider-grafana/pull/1060 

<details> <summary> Alertmanager config </summary>

```json
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "route": {
      "receiver": "grafana-default-email",
      "group_by": [
        "grafana_folder",
        "alertname"
      ]
    },
    "templates": null,
    "receivers": [
      {
        "name": "grafana-default-email",
        "grafana_managed_receiver_configs": [
          {
            "name": "email receiver",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "<example@email.com>"
            }
          }
        ]
      },
      {
        "name": "Test",
        "grafana_managed_receiver_configs": [
          {
            "name": "Test",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "test@example.com\ntest2@example.com",
              "singleEmail": true,
              "message": "Gubergren rebum enim facilisis accusam",
              "subject": "Sit lorem aliquam ad est"
            }
          },
          {
            "name": "Test",
            "type": "prometheus-alertmanager",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost:3000/",
              "basicAuthUser": "test",
              "basicAuthPassword": "0c08d514d702448d98da9931172bc365"
            }
          },
          {
            "name": "Test",
            "type": "webex",
            "disableResolveMessage": false,
            "settings": {
              "room_id": "1231231231231231231231313",
              "api_url": "http://localhost",
              "message": "Et kasd dolore minim sed",
              "bot_token": "88c6b32e60474e1284d04c40a6cde87d"
            }
          },
          {
            "name": "Test",
            "type": "dingding",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost",
              "msgType": "link",
              "title": "Nihil adipiscing nonumy ipsum labore",
              "message": "Gubergren sanctus dolor lorem sadipscing"
            }
          },
          {
            "name": "Test",
            "type": "discord",
            "disableResolveMessage": false,
            "settings": {
              "url":"http://localhost/0302c0dd3fc04972ad8780b4e518abdf",
              "title": "Eros est at est dolores",
              "message": "Qui et invidunt sed sadipscing",
              "avatar_url": "http://localhost",
              "use_discord_username": true
            }
          },
          {
            "name": "Test",
            "type": "googlechat",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost",
              "title": "Iriure invidunt dolores delenit dolor",
              "message": "Vero clita sed labore sit"
            }
          },
          {
            "name": "Test",
            "type": "kafka",
            "disableResolveMessage": false,
            "settings": {
              "kafkaRestProxy": "http://localhost/977a62b024e3420a80afb802f18da055",
              "kafkaTopic": "57ac3967897548a39652746f800e71b8",
              "kafkaClusterId": "asdadasdasdasd",
              "username": "test",
              "password": "7186933038354a07ad88177f55103ed8",
              "apiVersion": "v3",
              "description": "Dolore in voluptua sit ipsum",
              "details": "Et velit sit lorem est"
            }
          },
          {
            "name": "Test",
            "type": "LINE",
            "disableResolveMessage": false,
            "settings": {
              "token": "7d38748ad8a048d1a7bc638fe16d9110",
              "title": "Sit eum dolore dolor volutpat",
              "description": "Ex dolor erat labore no"
            }
          },
          {
            "name": "Test",
            "type": "teams",
            "disableResolveMessage": true,
            "settings": {
              "url": "http://localhost",
              "title": "Ipsum sit minim takimata kasd",
              "sectiontitle": "Est at elit et eum",
              "message": "Clita dolore laoreet sit sed"
            }
          },
          {
            "name": "Test",
            "type": "opsgenie",
            "disableResolveMessage": false,
            "settings": {
              "apiUrl": "http://localhost",
              "apiKey": "0ddff7845bd2468297db75afa8a61a98",
              "message": "Eirmod sit eos tempor aliquyam",
              "description": "Et et magna tempor facilisi",
              "autoClose": true,
              "overridePriority": true,
              "sendTagsAs": "details"
            }
          },
          {
            "name": "Test",
            "type": "pagerduty",
            "disableResolveMessage": false,
            "settings": {
              "integrationKey": "832f1274e35a46dd93654683f672177a",
              "severity": "error",
              "class": "test",
              "component": "Gubergren ullamcorper soluta duo sanctus",
              "group": "Autem stet sadipscing et sed",
              "summary": "Takimata sea molestie ut at",
              "source": "Tempor kasd et rebum et",
              "client": "Et eos et diam sadipscing",
              "client_url": "http://localhost",
              "details": {
                "test": "Amet magna rebum dolores lorem",
                "value": "Consequat consetetur eum rebum volutpat"
              }
            }
          },
          {
            "name": "Test",
            "type": "pushover",
            "disableResolveMessage": false,
            "settings": {
              "device": "Magna ea sed eu rebum",
              "priority": "1",
              "okPriority": "0",
              "retry": "200",
              "expire": "222",
              "sound": "pushover",
              "okSound": "classical",
              "title": "Labore vulputate no et diam",
              "message": "Erat elitr diam clita no",
              "apiToken": "de0b7eba49384033ba0a6d9bbc3b03c8",
              "userKey": "1b8273aab8e747fcb909821943b8adf3"
            }
          },
          {
            "name": "Test",
            "type": "sensugo",
            "disableResolveMessage": false,
            "settings": {
              "apikey": "8cf0f9335d684e368e99cebf4d10f444",
              "url": "http://localhost",
              "entity": "Tempor amet stet et accusam",
              "check": "Et ipsum diam nibh diam",
              "handler": "Stet molestie eos labore amet",
              "namespace": "Eos possim sanctus consequat in",
              "message": "Consequat in takimata invidunt stet"
              
            }
          },
          {
            "name": "Test",
            "type": "slack",
            "disableResolveMessage": false,
            "settings": {
              "token": "d62eed03ee0843a996f6828390af213b",
              "recipient": "Voluptua et ipsum sea et",
              "username": "Dolores consetetur ea consetetur illum",
              "icon_emoji": "Sed invidunt rebum diam elitr",
              "icon_url": "http://localhost",
              "mentionUsers": "Ut sed blandit te eos",
              "mentionGroups": "Facilisis aliquam ipsum consetetur invidunt",
              "mentionChannel": "channel",
              "endpointUrl": "http://localhost",
              "title": "Et magna ut eirmod sed",
              "text": "Sed nonummy facilisis clita stet"
            }
          },
          {
            "name": "Test",
            "type": "telegram",
            "disableResolveMessage": false,
            "settings": {
              "bottoken": "99b5fb47afe54fc1b1e5e50a5d7f38c2",
              "chatid": "123345",
              "message": "Et veniam qui consequat et",
              "parse_mode": "HTML",
              "disable_web_page_preview": true,
              "protect_content": true,
              "disable_notifications": true
            }
          },
          {
            "name": "Test",
            "type": "threema",
            "disableResolveMessage": false,
            "settings": {
              "api_secret": "2f136c533b224c1d863316669fc7770a",
              "gateway_id": "*2345678",
              "recipient_id": "123456W3",
              "title": "Dignissim et consequat justo doming",
              "description": "Invidunt accumsan et suscipit ut"
            }
          },
          {
            "name": "Test",
            "type": "victorops",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost",
              "messageType": "CRITICAL",
              "title": "Wisi no et consectetuer ut",
              "description": "Sanctus duo no accusam amet"
            }
          },
          {
            "name": "Test",
            "type": "wecom",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost",
              "msgtype": "text",
              "message": "Esse no voluptua ipsum accusam",
              "title": "Feugiat sed odio voluptua facer",
              "touser": "Aliquyam no accusam tempor ea"
            }
          },
          {
            "name": "Test",
            "type": "webhook",
            "disableResolveMessage": false,
            "settings": {
              "url": "http://localhost",
              "httpMethod": "POST",
              "username": "test",
              "password": "ca2bd92fb81542b3890250a42cb40912",
              "maxAlerts": "23",
              "title": "Tempor et labore autem sit",
              "message": "Diam duis amet dolores at"
            }
          }
        ]
      }
    ]
  }
}
```
</details>

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by rwwiv — APPROVED** [review]
LGTM 🚀

**Review by konrad147 — APPROVED** [review]
FE LGTM!

**Pull request merged**
