### PR TITLE
DebugSnapshot: Change to use exisiting localstorage prop and open in new tab

### PR DESCRIPTION
**Pull request by torkelo**
Changes the debug snapshot to use the existing feature that we have for modifying a new or existing dashboard. That way supports opening it in a new tab, which I think
is better here as with the current method it causes unsaved changes warnings (if you have made changes).

This debug wizard is pretty cool, wonder how we can make it more accessible (very hidden now). And the Drawer -> opening drawer action is pretty akward.

### CODE REVIEW

**Comment by torkelo** [comment]
One way to make this more accessible is to make the Debug wizard a tab directly in Inspect drawer. (so we move the Snapshot and Code tabs into it the inspect drawer, think we can make those two tabs live in one tab, the Code tab seems not that important if we just have actions to get the github comment to clipboard, or the snapshot dashboard).

**Comment by ryantxu** [comment]
nice!   With this change, we can show the dashboard directly 🎉 
http://localhost:3000/d/MP-Di9F7k/candlestick?orgId=1&inspect=2&inspectTab=debug

iframe to the rescue 

image


> This debug wizard is pretty cool, wonder how we can make it more accessible (very hidden now). And the Drawer -> opening drawer action is pretty akward.

Totally -- I pushed what we have in its current state so we could start to use/test it, but really want to get it more accessible and loudly promoted for 9.2.

In https://github.com/grafana/grafana/pull/54678 -- I propose moving this to the main menu

**Comment by torkelo** [comment]
@ryantxu 

love the iframe! sneak peak of what scenes will enable :) 

> In https://github.com/grafana/grafana/pull/54678 -- I propose moving this to the main menu

Awesome, yea thinks it makes sense to have it there. Maybe also linked to from Inspect drawer/data. 

Wonder what the best word is, Debug vs Troubleshoot vs Support snapshot?

**Comment by ryantxu** [comment]
> Wonder what the best word is, Debug vs Troubleshoot vs Support snapshot?

🤣 I know -- I have been through all of them

**Comment by torkelo** [comment]
@ryantxu needs an approve :)

**Review by ryantxu — APPROVED** [review]
:)

**Pull request merged**
