### PR TITLE
Changelog: v6.6.0-beta1

### PR DESCRIPTION
**Pull request by xlson**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by jongyllen — APPROVED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Comment by papagian** [comment]
@xlson please don't merge it yet!
I need to push a fix!

**Comment by hugohaggmark** [comment]
Should we mention the removal of Angular dependencies in `backendSrv` in this changelog or should we wait for the stable release? @torkelo @dprokop

**Comment by dprokop** [comment]
@hugohaggmark I think it's worth mentioning that we are about to introduce this change in 6.7, maybe with a  link to a md file that describes what are the exact consequences and how to prepare for the migration? Just thought about this, but maybe in the stable release we should add a warning in the backend_srv code, informing about the upcoming change, same as React team does with deprecating unsafe methods.

**Comment by hugohaggmark** [comment]
@xlson we need to sort out the removal Angular dependency before merging this, can you hold the merge until about 10?

**Comment by hugohaggmark** [comment]
@xlson we'll add notice to 6.6 Changelog instead so we're ready to go

**Comment by xlson** [comment]
Thanks, I'll merge it now.

**Pull request merged**
