### PR TITLE
InfluxDB: Update InfluxQL querybuilder to qualify identifiers

### LINKED ISSUE #61335: Grafana Query Builder and Ad Hoc Filters for InfluxDB Datasources should use "::tag" syntax.
**What happened**: 
Using the Grafana Query Builder and Ad Hoc Filters on an InfluxDB Datasource that has tags and fields with the same name creates queries that perform poorly in large Databases.

The Grafana Query Builder and Ad Hoc Filters for InfluxDB Datasources do not explicitly add the "::tag" annotation in the query strings they build from the internal queries of "SHOW TAG NAMES".  As these are known to be Tags, it would be best to annotate them as such in the queries the builders produce.

Background:  In InfluxDB, it is legal (although not recommended) to have Flelds and Tags with the same name.  They are separate parts of data.  The Tags are used as indices to speed up search queries.  When you generate a query from the Builder like:

  SELECT * From "my_data" WHERE time >= 1653868799000ms AND time <= 1653868799000ms AND "thingy" = 'thing1';

The InfluxDB query planner looks at the Shards covering the time rang for any fields or tags named "thingy".  If there is a field in the time range named "thingy", the query plan becomes "thingy"::string = 'thing1' and results in a linear search through all of the data in the Shard looking for a field with that value.  If there are only a tag with named "thingy", the plan becomes "thingy"::tag = 'thing1' and the value lookup is performant for large databases (ours is 300GB and growing).  The problem is if both a field and a tag have the same name for ANY shard in the time range, the query planner emits "thingy"::string = 'thing1' and performance goes down the drain.

We have InfluxDB Enterprise with support and working with their support department, the fix is to use the explicit "::tag" annotations on things you know are Tags.  This works fine in Grafana for Raw Queries but InfluxQL produced by the Query Builder and Ad Hoc Filters have no mechanism to express the annotation.  In looking at the source, I traced the code and see that the values the Query Builder retrieves (for InfluxDB as Datasource) are ALWAYS tags.  As such, we should just add the "::tag" annotation by default (if we add support for querying for fields for the tool, those should have their type).  We have less sophisticated Grafana users who can handle the Ad Hoc filters but would be lost in trying to create a Raw Query, so I want to protect them from this problem.

Note: Per InfluxDB Enterprise Support,  removing the bad data points or Series cannot fix the problem.  Due to the nature of InfluxDB, I have to drop and rebuild this large DB to fix things when users slip in fields like this.

**What you expected to happen**:
To explicitly annotating Tags with "::tag" in queries produced by Ad Hoc Filter and the Query Builder for InfluxDB so that queries are performant on large databases.

**How to reproduce it (as minimally and precisely as possible)**:
Create a huge InfluxDB Enterprise (or OSS 1.8.x) database that spans across a long period of time and a 100 or so shards with TSI indices with Tag "filename".  

Do a SELECT COUNT(*) FROM "measurement" WHERE <time span> AND "filename" = 'my-test-filename.txt'

Do an EXPLAIN ANALYZE SELECT COUNT(*) From "measurement" WHERE <time span> AND "filename" = "my-test-filename.txt" and see how the planner is using "filename"::tag = 'my-test-filename.txt'

Then write a few records to a timestamp in the middle of the time span with a field named "filename".

Repeat SELECT and watch it timeout or take several orders of magnitude longer.

Repeat EXPLAIN ANALYZE and see the Planner is now using "filename"::string = 'my-test-filename.txt'

**Anything else we need to know?**:
I already have a working fix of the above that I'll submit as a PR for this ticket.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: InfluxDB 1.10.0
- OS Grafana is installed on: Alpine Container
- User OS & Browser: macOS 12.6.1, Chrome 108.0.5359.124 (Official Build) (x86_64)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by LudoVio**
**What is this feature?**

Update InfluxQL querybuilder to qualify identifiers. Like ::tag and ::field

**Why do we need this feature?**

When a tag and a field have the same name, InfluxDB doesn't know which one we refer too. So it has to fallback to searching on both. But fields are not indexed and so the query can become super slow on some use case, while if we specify that we want to filter by tag, then it is indexed and fast

**Who is this feature for?**

People using the same name for tag and field

**Which issue(s) does this PR fix?**:

Fixes #61335

### CODE REVIEW

**Comment by ksquaredkey** [comment]
Many thanks @LudoVio for running with this!  I can't test the results myself until early next week, but the code passes my (typescript ignorant) eyeball check.  Looks clean and straight-forward.

**Comment by gabor** [comment]
nice work 👍 , it works fine in general, but there seems to be a problem with group_by_tag functionality, sorry:

how to test:
- make devenv sources=influxdb
- measurement=cpu
- field=usage_idle
- add a group_by, choose `tag(cpu)`


this should draw multiple lines in the graph, one for each cpu, and one for `cpu-total`. works on main-branch.

but, if i do this in this PR, somehow i only get a single line in the graph.

**Review by itsmylife — APPROVED** [review]
This looks good to me. I would like to get additional approval from @gabor too.

**Review by gabor — APPROVED** [review]
LGTM 👍

**Pull request merged**
