### PR TITLE
Chore: Removes console.log in annotations_srv.test.ts

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Relates #45031

**Special notes for your reviewer**:

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
🤔 I am confused, are we removing the content of the test?

**Comment by hugohaggmark** [comment]
> 🤔 I am confused, are we removing the content of the test?

Everything in there is deprecated and the implementation should be removed before v9.

**Comment by hugohaggmark** [comment]
Look at https://github.com/grafana/grafana/blob/c25031fa492b91a7465901682321f6105d6290d9/public/app/angular/services/annotations_srv.ts#L69

**Review by axelavargas — APPROVED** [review]
🥳 good to go!

**Pull request merged**
