### PR TITLE
Docs: initial backend plugins development guide

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This is an initial version of the backend plugin developing guide. This is a part of #16066.
More details can be put into "Reference" documentation page I think. 
What do you think, should we put docs for developing plugin in other than Go language here or in the separate file?

### CODE REVIEW

**Review by daniellee — APPROVED** [review]
Made some changes. This is a good start.

**Comment by tomisaacson** [comment]
Has enough documentation and example been provided to start using this? If not what's the plan?

I'm happy to have a go if it's worth it.

**Comment by alexanderzobnin** [comment]
@tomisaacson You could take a look at [simple-json-backend-datasource](https://github.com/grafana/simple-json-backend-datasource) - it's a backed version of simple-json datasource. It's quite simple and can be a good reference.

**Comment by tomisaacson** [comment]
@alexanderzobnin I asked about that on #16066, the changes to get it to work haven't been completed.

**Comment by alexanderzobnin** [comment]
@tomisaacson It should work quite well for use as an example.

**Pull request merged**
