### PR TITLE
[Feature request] Wildcard search on not_analyzed fields for Elasticsearch datasource

### LINKED ISSUE #7451: [Feature request] Wildcard search on not_analyzed fields for Elasticsearch datasource
Grafana version: 4.1.1 
Datasource: Elasticsearch - Native Plugin v. 3.0.0
OS: linux

# Problem
With the current Elasticseach datasource plugin it is not possible to use wildcards in the Lucene query for `not_analyzed` fields. This concerns at least Elasticsearch version 2.3.

The reason is that the current `query_string` created by the plugin is not specifying `lowercase_expanded_terms: false`

## Lucene query example
```
computer:cs-ccr-*
```

# Resolution
The problem can easily be fixed by adding to [query_buider.js](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/query_builder.js) the missing `query_string` option 

See also Elasticsearch documentation:
 https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html

### PR DESCRIPTION
**Pull request by cherweg**
Please review my Feature for injection options to query_string querys.
I´s my first try of a grafana patch...so be lenient toward me :-)

Fixes #7451

regards
christian

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @cherweg 

Could you try to fix the tests first. If you click on the `Details` link for the circle ci check above, you can see which tests failed.  Check out the [Contributing Guide](https://github.com/grafana/grafana/blob/master/.github/CONTRIBUTING.md) for how to run the backend and frontend tests locally. In this case, you will want to fix the frontend tests in the following two specs files:

- [query_builder_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/query_builder_specs.ts)

- [datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/datasource_specs.ts)

**Comment by cherweg** [comment]
Hey.
I fixed the tests... howto update this pull request?

regards
christian

**Comment by cherweg** [comment]
Ahh. It´s magic :-)

**Comment by DvirM** [comment]
Hi Guys,

Any updates on this? :) 
Thanks!

**Comment by cherweg** [comment]
Everything ready to merge...from my point of view...

regards
christian

**Comment by ashwin31** [comment]
:+1:

**Comment by torkelo** [comment]
since this option was removed in Elastic 5.x closing this seems appropriate
https://github.com/elastic/elasticsearch/issues/9978 

In Elasticseach 5.x using wildcard search on keyword fields seems to work

**Pull request closed without merging**
