### PR TITLE
Dashboard data source: Return error when used in mixed data source

### PR DESCRIPTION
**Pull request by dprokop**
Based on top of [mdvictor/update-dashboard-ds-panel-if-source-changes](https://github.com/grafana/grafana/pull/85655).

I think this fixes an issue described by @ivanortegaalba  in https://github.com/grafana/grafana/pull/85655#issuecomment-2042960663. 

This is just a proposal, that honestly I'm not super happy with. But it brings the previous architecture behavior of Dashboard ds. It wasn't a real data source as it was not implementing `query` method, and it just used to throw an error when used from Mixed ds (mixed ds basically executes `ds.query`).

Intuitively the current implementation of the Dashboard ds should just work fine with Mixed ds, but I can't figure out why the observable returned from dashboard ds query method is not respected by mixed ds flow. @torkelo maybe you have some idea, you a bot more experienced with rxjs than I am.

### CODE REVIEW

**Review by ivanortegaalba — APPROVED** [review]

**Review by mdvictor — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
@dprokop there are 2 issues, one is related to scopedVars not being fully preserved in MixedDataSource , so that when queried via mixed the dashboard data source does not find the scene context in scopedVars. 

but the second problem is then that the Dashboard data source query does not fully complete the rxjs Observable (because it uses getResultStream and it does not provide any way to know when the query is fully complete). It's tricky, not sure how to solve it. 

We could solve it by completing the observable with state LoadingState.Done is emitted but some data source could be returning that when there are more data to return (but probably very rare). So that is probably the easiest solution

**Comment by dprokop** [comment]
Thanks @torkelo , i'll spend some more time on it next week. Doesn't sound like a prio, but a nice thing to finally support dashboard ds with Mixed :)

**Comment by torkelo** [comment]
@dprokop cool, yea not super high prio but seen some bugs when using dashboard data source where it get's stuck in loading state so think we need to update https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/dashboard/datasource.ts#L68 to return an observable that is completed when state changes from loading to Done 

btw also have this PR that I need to wrap up :) 
https://github.com/grafana/grafana/pull/83356

**Pull request merged**
