### PR TITLE
Chore: Generate shorter UIDs

### PR DESCRIPTION
**Pull request by ryantxu**
In https://github.com/grafana/grafana/pull/62731, we shifted the default UID generator to return real UUIDs that are also valid k8s names rather than using https://github.com/teris-io/shortid

This PR changes the approach to use a uid based on [snowflake ids](https://github.com/bwmarrin/snowflake) with random alpha prefix+suffix.  With this change:
```
cdangsdwe3ivrf
bdangsdwe3ivse
edangsdwe3ivtf
adangsdwe3ivuf
edangsdwe3ivvc
edangsdwe3ivwe
ddangsdwe3ivxa
ddangsdwe3ivya
fdangsdwe3ivzd
edangsdwe3iw0d
```

and a few seconds later:
```
bdanic22xanvee
bdanic22xanvfc
edanic22xanvga
ddanic22xanvhf
bdanic22xanvif
fdanic22xanvjf
cdanic22xanvkb
```

Downside is the timestamp is pseudo encoded in the short uid, and it may be easier to guess valid values *near* other  values.  

Before:
```
nba00926-5ca8-4016-818c-db9ca0f0adb8
p98fd744-db83-42a4-bf42-1f244fa83e89
caaf3b03-f2f9-4322-9404-a288bacc3c4f
bfcf9ff9-e6b0-4b9d-82cb-fba91609a44e
l838be3d-52e0-4b11-8a9a-2281556dbd76
c7cf09cf-2e58-4304-84e8-22ca20c42178
l2fb84a0-fcbb-4123-aa85-81986c5e58b0
e1f3a7c9-25ec-4408-8e51-6e0acdd88cdc
bd649328-90fd-4cb5-a437-141d0cc558bd
```

It does not really matter, but the shorter names are nicer

### CODE REVIEW

**Comment by torkelo** [comment]
This id definitively a lot nicer, as we use the uid in URLs and the longer guid makes urls harder to read (trickier to parse out the slug part )

**Comment by ryantxu** [comment]
An alternate -- non UUID approach that meets our needs and is even a bit shorter could be:
https://github.com/grafana/grafana/compare/main...shorter-uids. It produces:

```
praifzQdIg7q
r9stmBzQOIgVu
v9amfkQOIRIw
xramBkQdIgNy
z9amBzwOIRvA
B9amfkwOSROC
DrEFifzwdIgFG
H9IJmBzQdSgcK
LrMNifzQdSRpO
P9QRmBkwOSRhS
TraiBkwdSgoU
VrWXiBkQdSg0Y
Z9aiBzwdIR1a
b9cdiBkwOIgxe
f9amBzwdSRghi
jramfzwOIgfk
l9aiBzQdIRYm
nropiBzwdIgPq
```

**Comment by zserge** [comment]
Aren't Grafana UIDs potentially case-insensitive (due to MySQL historical behaviour)? I.e. https://github.com/grafana/grafana/pull/60494

**Comment by ryantxu** [comment]
@zserge -- I'm not sure if that is a hard requirement or one that just caused additional checks/inefficiencies (something about legacy alerting migrations).  With the https://github.com/teris-io/shortid algorithm, we had lots of duplicates very quickly -- with this the case insensitive collisions are infrequent.  See the attached test... I could bump that to 100M and have not hit a collision, but with shortid it collided within the first 500 iterations

@JacobsonMT thoughts?  If case insensitive uid is a requirement, we should also make that explicit!

**Comment by JacobsonMT** [comment]
> thoughts? If case insensitive uid is a requirement, we should also make that explicit!

The issue, as far as I remember it, was that the previous algorithm combined with an alphabet including both lower and upper case letters had a high chance of case-insensitive duplicates when generated in a large tight loop.

Handling of these collisions was variable in the codebase at the time. Most places either handled it well by ensuring the loop was not extremely tight and re-attempting the uid generation on collision. Others let the request fail so it could be retried. The main issues were places, like an early version of the legacy migration, where the loop was large and tight enough that every retry would fail. This issue has been fixed for the legacy migration but could still exist elsewhere in the codebase.

So, we technically do have a requirement for case-insensitive UUIDs but it's a soft requirement since infrequent collisions should be tolerable.

The change using base57 encoding is good idea and should be OK. 

The [shorter](https://github.com/grafana/grafana/compare/main...shorter-uids) change would bring back the problem for large tight loops + MySQL and while it's  "probably fine" given the main offender (legacy migration) has been independently fixed I think it might be safer to go with base57 encoding or try to get the https://github.com/teris-io/shortid algorithm to work with a base32 alphabet instead.

**Review by JacobsonMT — APPROVED** [review]
LGTM using the base57 encoding

**Comment by ryantxu** [comment]
@zserge -- I updated this so it is based on https://github.com/bwmarrin/snowflake -- so it no longer produces mixed case values, and the folders tests pass 🎉

**Review by zserge — APPROVED** [review]

**Pull request merged**
