### PR TITLE
(prometheus) support /api/v1/labels

### PR DESCRIPTION
**Pull request by mtanda**
https://github.com/grafana/grafana/issues/8253
By using new Prometheus API, support adhoc filter and add new templating function.

### CODE REVIEW

**Comment by mtanda** [comment]
@davkal I think you are module owner. Would you check this?

**Comment by davkal** [comment]
All query editor work is currently halted. We're investigating if it's feasible to bring the Explore query editor to the panels. See #15364

**Comment by mtanda** [comment]
hmm, this PR doesn't change the query editor.
Anyway, I wait for https://github.com/grafana/grafana/pull/15364 .
Thanks for the response.

**Comment by torkelo** [comment]
This has nothing to do with query editors but adding full ad hoc query support to Prometheus and adding a new templating query

**Review by daniellee — APPROVED** [review]
Looks good and can't find any bugs. This is a nice new feature for Prometheus.

The getTagKeys function in datasource.ts and labelNamesQuery function in metric_find_query.ts are exactly the same but in this case I think it is fine to duplicate them to avoid any unnecessary coupling.

**Comment by mtanda** [comment]
Thanks a lot! I'm really looking forward to using this feature!!

**Pull request merged**
