### PR TITLE
TraceView: Fix broken rendering when scrolling in Dashboard panel in Firefox

### LINKED ISSUE #54949: Unable to display very large traces in Dashboard
We're experiencing issues when displaying very large traces in Grafana (>100 spans). Display of traces gets cut midway through the trace, and some spans are not rendered.

This happens in dashboard view. When displaying the same trace in Explore, it gets rendered correctly.

image

Environment:
Grafana version: Grafana v9.1.1

### PR DESCRIPTION
**Pull request by zdg-github**
**What this PR does / why we need it**:
Because the value of scrollElement is undefined, the trace viewer displays 100 spans when scrolling
In order to solve this issues, we obtains asynchronously the correct value of the scrollElement in the component mount phase.

**Which issue(s) this PR fixes**:

Fixes #54949

**Special notes for your reviewer**:
After executing the callback of setScrollRef in the ancestor component, we can correctly obtain the new value of scrollElement

@mellieA  @aocenas I really appreciate your attention and review code in previous PR which is #55708 . I wish someone can check the code for me as soon as possible

### CODE REVIEW

**Comment by aocenas** [comment]
Hey @zdg-github yeah this seems like the right approach. Are you still working on the code? There are some errors that I assume need just some code cleanup.

**Comment by zdg-github** [comment]
> Hey @zdg-github yeah this seems like the right approach. Are you still working on the code? There are some errors that I assume need just some code cleanup.

@aocenas Yes, I'm still working on the code. Welcome to instruct the problem

**Comment by aocenas** [comment]
@zdg-github hey, not sure what you mean. I assume you are just missing arguments as `prevProps` isn't defined right now?

**Comment by zdg-github** [comment]
> @zdg-github hey, not sure what you mean. I assume you are just missing arguments as `prevProps` isn't defined right now?

Yes,I was missing a parameter as `prevProps`. Now, I've Fixed it.

**Review by aocenas — APPROVED** [review]
Thanks for the contribution @zdg-github

**Pull request merged**
