### PR TITLE
Alerting: Clarify that Threema Gateway Alerts support only Basic IDs

### PR DESCRIPTION
**Pull request by dbrgn**
Threema Gateway supports two types of IDs: Basic IDs (where the
encryption is managed by the API server) and End-to-End IDs (where the
keys are managed by the user).

This plugin currently does not support End-to-End IDs (since it's much
more complex to implement, because the encryption needs to happen
locally). Add a few clarifications to the UI.

(Note: There's also an "Info" key in the notifier plugin which contains more information, but I did not find out where in the UI this is being displayed 😕 Maybe it would be good to show this info text more prominently for alert plugins.)

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
Lgtm

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Oh sorry, I just recalled you need to update pkg/services/ngalert/notifier/, since that's our new alerting subsystem starting from v8.

**Comment by dbrgn** [comment]
Ah, thanks, I somehow missed that!

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Just closing and re-opening this to get checks unstuck.

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Pull request merged**
