### PR TITLE
Add "include zero" to graph Y-axis

### LINKED ISSUE #5541: [Feature request] Add "include zero" to graph Y-axis
* **I'm submitting a ...**
* [ ] Bug report
* [x] Feature request
* [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:

* What Grafana version are you using? 3.0.4
* What datasource are you using? Influx DB 0.13
* What OS are you running grafana on? Linux

When drawing graphs currently the only possible way to control the Y-axis is to set value limits or use automatic limits. While this is enough for most use cases, it would be nice to have a feature to always include zero to the Y-axis.

For example, when viewing a graph with positive values it's quite normal to set Y-min to 0. By setting this, the graph can be "normalized" to always include 0 value. However, when there are some points in which the value is below zero, the values are lost from the graph with this solution.

Couple screencaps to demonstrate the issue:
[without Y-min, only positive values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero1.png)
[without Y-min, a few negative values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero2.png)
[Y-min = 0, only positive values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero3.png)
[Y-min = 0, a few negative values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero4.png)

The logic of "include zero" as pseudo-code:

```js
if (include_zero) {
if (min(y) > 0) {
y_axis_min = 0;
}
if (max(y) < 0) {
y_axis_max = 0;
}
}
```

### PR DESCRIPTION
**Pull request by ilgizar**
Fix #5541

### CODE REVIEW

**Comment by torkelo** [comment]
hi, thanks for contributing to Grafana! 

I think this setting feels a bit too specific (only solve one small scenario). Think we are more interested in making the y scale limits more fexible (soft limits) to support more scenarios.

https://github.com/grafana/grafana/issues/979

**Comment by ilgizar** [comment]
I agree that the #979 is more flexible and broad.

**Comment by torkelo** [comment]
I am sorry, but closing this, If you have an idea for how to solve  #979 and wish to work on that please describe how you plan to make it work (UX / behavior), always good to discuss the feature in advance before implementing

**Comment by ilgizar** [comment]
Ok, but I think that in addition to Y-Min and Y-Max, one more parameter is needed - a Y-Level that would replace this PR. Y-Level is always visible value, in no dependence above or below it is a graph.

**Pull request closed without merging**
