### PR TITLE
show teams on profile

### LINKED ISSUE #12476: Profile page: list teams
A user should be able to see what teams the user belongs to.

### PR DESCRIPTION
**Pull request by Ijin08**
Added list of teams for profile page.

skarmavbild 2018-08-08 kl 11 24 03

fixes #12476

### CODE REVIEW

**Comment by Ijin08** [comment]
@marefr this needs a backend fix so one can collect team info.

@torkelo not sure how much information should be shown. I name of team enough or should other information be included such as email and number of team-members.

**Comment by marefr** [comment]
@Ijin08 added same response as when listing teams for an organization, see https://github.com/grafana/grafana/pull/12838/files#diff-53cdb29039de5602c7f2987a29ca2f2a

If you want to render same table as when listing teams for an organization, now you can.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
nice work @Ijin08 !

**Comment by marefr** [comment]
@torkelo please note that only teams for current/active organization is displayed. We found that to be the easiest and most straightforward way implementing this. Do you agree?

**Comment by torkelo** [comment]
I think that is best

**Review by marefr — CHANGES_REQUESTED** [review]
Seems like teams table are hidden when I'm testing it now. 

Looks a bit weird when Teams and Organization header are displayed together (when you don't have any teams)

**Review by marefr — APPROVED** [review]
Nice :+1:

**Pull request merged**
