### PR TITLE
DashboardPage: Remember scroll position when coming back panel edit / view panel

### PR DESCRIPTION
**Pull request by torkelo**
I noticed that the dashboard no longer remembers your scroll position after returning from panel edit.

Was I think accidentally removed by https://github.com/grafana/grafana/pull/42834

This adds back that same solution of using the setScroll callback on the CustomScrollbar, it's not ideal from a performance standpoint
as it will trigger re-renders of the DashboardPage.

I think another option is to use the scrollRefCallback and set the scrollElement in state instead, and use that to get scrollTop on-demand when entering edit/view

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]

**Comment by torkelo** [comment]
@kaydelaney what do you think of scrollRefCallback? that way DashboardPage can access the scroll element and via it get the scrollTop when we enter edit/view

**Comment by kaydelaney** [comment]
That could work nicely! Definitely seems like it'd be more performant than relying `onScrollTop`

**Comment by torkelo** [comment]
@kaydelaney I switched it to use the scrollRefCallback 

There is still one minor issue that I think https://github.com/grafana/grafana/pull/42834  introduced which this PR does not solve, the view panel mode has a scrollbar and you can scroll down to a bunch of black space (in a long dashboard).

**Comment by torkelo** [comment]
@kaydelaney if you have time can you give this a quick test & review. Since this is going into a backport want to make sure it's not introducing any new bugs. 

Al

**Review by kaydelaney — APPROVED** [review]

**Pull request merged**
