### PR TITLE
Datasource Config Editor: Add event-based funnel for measuring CVR

### PR DESCRIPTION
**Pull request by yaelleC**
## What this PR does / why we need it

This draft PR goes along side the [datasource usability design](https://docs.google.com/document/d/16yA53bJnlhZm5Ab06BKKrSWLTp1RoxVJ5mhFzqxrdes/) doc.
I've created it to show the funnel event on practice and gather feedback from the teams that it could interests / affect.

Grafana [does not currently do sessionization](https://raintank-corp.slack.com/archives/C020988GK4H/p1662472149145969?thread_ts=1662456165.238279&cid=C020988GK4H) so I am using the `datasource_id` as the equivalent of a `session_id` here (I will combine it with the slug when analysing as 2 instances could use the same dashboard id).

The purpose of the funnel is to measure datasource config conversion (CVR). Having them allows us (and any team that owns data source plugins) to answer questions such as:
* Out of all the users that enter the data source config page, how many actually click “save and test”. 
* Out of all the users that enter the data source config page, how many successfully set it up? 
* How many times, on average, do users click the save and test button per datasource creation? 
* How long does it typically take for users to set up an XYZ data source

Having this visibility would allow us to:
* identify the "worse" datasources (in term of CVR or time to set up) and prioritise work on them
  * If datasource A takes twice as long to set up as all the other datasources we own, and provided the config editor has just about the same number of fields, we could work with UX to make improvements
* quantify the impact of our work done in the config editor
  * by measuring CVR and time spent before and after a change (or better yet splitting traffic A/B), we could confirm the change that we introduce did make life easier for our users and quantify how much easier (CVR improved by 3%, users now take 1 minute less to set up the datasource etc.)

## Special notes for your reviewer

This is a WIP draft PR meant to show a first option for event-based funnels in the datasource world. I welcome feedback on it, especially on:

1. Naming: `grafana_ds_add_datasource_clicked` and `grafana_ds_test_datasource_clicked` , I used the same `grafana_ds` prefix as used in the [azure adoption metrics PR](https://github.com/grafana/grafana/pull/54286) for consistency, but maybe the `ds` is not needed here 🤷‍♀️ 
2. How I could get `datasource_version` too in props? I tried using the `getVersion()` method bt could not find any plugin that implemented that 🤔 
3. Where the event is emitted: same as for the azure adoption metrics, I initially thought to focus the first iteration on just the one datasource. But that would mean using the event bus again and has the same drawbacks, mainly the security concern that all events are available to all datasources. I thus turned to emitting the event for all datasources meaning:
    -   anyone owning data sources could use the funnel for free (by setting up a dashboard with the example SQL queries in the designdoc)
    -   we could compare CVR and time spent across all data sources to check the best/worst performing ones usability-wise
    -   I don't expect the amount of event triggered to be huge (as opposed to queries / dashboard loaded in the adoption metrics project) so the cost/value ratio seems worth it

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
I generally like the approach here :+1:  Simple and on point to the things that we want to track

> How I could get datasource_version too in props? I tried using the getVersion() method bt could not find any plugin that implemented that thinking

From the implementations I see (there is no documentation), that `getVersion` is used to return the version of the data source, not the plugin (e.g. the PostgreSQL version of the server). But there should be a way to do this, the plugins-platform should have more information or a good way of getting that.

**Comment by yaelleC** [comment]
@grafana/plugins-platform-frontend , any idea - if at all possible - how I could access the plugin JSON to get the version number (especially useful for external plugins)?
It's not necessarily needed for this MVP , but it something we would like in the future. If we want to measure the usability impact of a change we made , we need a way to group the data by version.
Thanks!

**Comment by mckn** [comment]
This is great stuff! Maybe we can team up and combine this PR together with this one: https://github.com/grafana/grafana/pull/56126

**Comment by yaelleC** [comment]
> Maybe we can team up and combine this PR together with this one: #56126

@mckn , absolutely! 
My rationale for putting my tracking in `actions` was:
1. to catch both datasources created via the `datasources/new` page AND the `plugin/datasourceXYZ` 
2. to have access to the `datasource_id` created after the click
2. to have access to whether or not the health check succeeded

Any idea how I could use your new plugin context while keeping these points? 

I suppose for 1) I could trigger the event on both button clicks instead (and then use your hook) but I'm not sure how I could have access to the `datasource_id` or the state `testingStatus` as they will not have been set when the user first clicks the buttons?

**Comment by mckn** [comment]
> > Maybe we can team up and combine this PR together with this one: #56126
> 
> @mckn , absolutely! My rationale for putting my tracking in `actions` was:
> 
> 1. to catch both datasources created via the `datasources/new` page AND the `plugin/datasourceXYZ`
> 2. to have access to the `datasource_id` created after the click
> 3. to have access to whether or not the health check succeeded
> 
> Any idea how I could use your new plugin context while keeping these points?
> 
> I suppose for 1) I could trigger the event on both button clicks instead (and then use your hook) but I'm not sure how I could have access to the `datasource_id` or the state `testingStatus` as they will not have been set when the user first clicks the buttons?

I totally understand and agree with your approach. What do you think about reusing the following factory functions to create the event properties? Just so we keep the same set of base properties?

https://github.com/grafana/grafana/pull/56126/files#diff-c3b6ef3a597d8b247d8ff6777eaee401b4c6a2c016a160dc3466c04fd70bec4bR27

**Comment by yaelleC** [comment]
Sounds great! 
💯 for consistency of props! I'll review your PR and I'll update the code here once it's merged

**Comment by yaelleC** [comment]
@mckn , any idea on a timeline for your PR? 
Maybe I could merge this one as is and update it with your factory function to update the props  once yours is merged?

**Comment by mckn** [comment]
> @mckn , any idea on a timeline for your PR? Maybe I could merge this one as is and update it with your factory function to update the props once yours is merged?

Yeah, sounds like a good idea. I guess it would be good if we align the naming of the properties in the payload?

**Review by mckn — APPROVED** [review]
LGTM!

**Pull request merged**
