### PR TITLE
Annotations: Fixes issues loading angular annotation query editors and updating annotation query model 

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Merging #31950 brought an eslint warning into master. This PR silences it. 

Unfortunately it seems that adding `annotation` or `onChange` to the dependency list causes angular to error with `Cannot read property '$$nextSibling' of null` and the AngularEditor to fail to load anything. I believe it's something to do with the `digest` that's being called within the useEffect but don't know enough about Angular to be able to figure it out.

### CODE REVIEW

**Comment by torkelo** [comment]
think I need to update this loader, the angular component destory/update stuff looks incorrect

**Comment by torkelo** [comment]
As I thought the current code (and this) has a bug in that the closure captures the annotation object, so for angular editors if you change the annotation name and then the annotation query via the angular editor your name change get's reset

**Comment by torkelo** [comment]
@jackw Discovered lots of bugs with loading and updating angular editor (some related to babel upgrade) some related to this hook and closure capture. Had to rewrite it to a class component to solve some of those issues

**Review by torkelo — APPROVED** [review]

**Comment by jackw** [comment]
Amazing! Thanks for taking the time to help me out here @torkelo ⚡

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
