### PR TITLE
InfluxDB: Add Missing Operators for Field based WHERE conditions

### LINKED ISSUE #77793: InfluxDB: Incorrect Handling of the `<>` Operator
### What happened?

The InfluxDB InfluxQL Query Builder offers `<>` as a possible operator when building `WHERE` conditions.

However, the backend's query building (specifically `renderTags()`) doesn't include support for this operator, so the value is coerced to a string.

The result is that
```
SELECT field FROM MEASUREMENT where field <> 4
```

becomes
```
SELECT field FROM MEASUREMENT where field <> '4'
```

### What did you expect to happen?

The value should not be wrapped in quotes

### Did this work before?

No

### How do we reproduce it?

1. Have an InfluxDB database
2. Use the editor to create a query which uses the `<>` operator in a WHERE condition
3. Observe the InfluxDB logs and note that the value has been quoted

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

_No response_

### Grafana platform?

None

### Datasource(s)?

_No response_

### LINKED ISSUE #77794: InfluxDB: It's not possible to include boolean fields in query conditions using the InfluxQL Editor
### What happened?

Using the InfluxQL Builder, it isn't possible to build a query like
```
SELECT field FROM measurement WHERE boolean_field = true
```

This is because, when an (in)equality operator is present, the backend assumes the value is a string and wraps the value in quotes, leading to InfluxDB receiving
```
SELECT field FROM measurement WHERE boolean_field = 'true'
```

### What did you expect to happen?

It should be possible to query based upon a boolean field value

### Did this work before?

No

### How do we reproduce it?

1. Write a point into an InfluxDB datasource, with a boolean field (e.g. `my_measurement,foo=bar a=1,b=true`)
2. Attempt to query it using InfluxQL based upon the field value

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

_No response_

### Grafana platform?

Other

### Datasource(s)?

InfluxDB

### PR DESCRIPTION
**Pull request by btasker**
**What is this feature?**

- Introduces missing query operators to the InfluxQL Query Builder
- Fixes type handling for an existing operator (`<>`: https://github.com/grafana/grafana/issues/77793)
- Implements support for including query conditions based upon boolean field values using new `Is` and `Is Not` operators (see note below) (https://github.com/grafana/grafana/issues/77794).

Screenshot_2023-11-07_12-07-14

**Why do we need this feature?**

- InfluxQL supports a [range of comparison operators](https://docs.influxdata.com/influxdb/v1/query_language/explore-data/#fields) for field values. Prior to this PR, Grafana did not include support for `>=` or `<=` at all.
- Handling for the operator `<>` was incorrect. It had been omitted from the `case` statement, so a submission of `field <> 4` would be coerced to `field <> '4'`.
- There's a pre-existing issue where [it isn't possible to query based on boolean fields](https://github.com/grafana/grafana/issues/2674#issuecomment-1446564677) because after submission, the value will be coerced to a string (e.g. `false` will be coerced to `'false'`).

**Who is this feature for?**

InfluxDB users who want to use the InfluxQL Query Editor to build queries which reference non-string fields in their query's `WHERE` condition.

**Relevant Issues**

- https://github.com/grafana/grafana/issues/4744 
- https://github.com/grafana/grafana/issues/2674
- https://github.com/grafana/grafana/issues/34577 (links out to others)
- https://github.com/grafana/grafana/issues/77793
- https://github.com/grafana/grafana/issues/77794

Fixes https://github.com/grafana/grafana/issues/77793
Fixes https://github.com/grafana/grafana/issues/77794

**Special notes for your reviewer:**

New operators (`Is` and `Is Not`) were used for boolean equality tests in order to preserve backwards compatibility: I originally implemented a solution that checked if the supplied value looked like a boolean (i.e. was `true` or `false`) so that `=` and `!=` could be used. However, on testing, I found that this broke any pre-existing (and query editor originated) dashboard cells which queried a *string* field for `true` or `false`

I have not added a test for the typescript changes - there didn't seem to be an existing test for the other operators, so I didn't think it was necessary (there **is** a test for the backend changes, however).

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by itsmylife** [comment]
@btasker Thanks for the contribution. This looks awesome! 
I see this PR is addressing two separate issues. I think it would make much more sense if you split it into two PRs. 
It'll be easier to review and easier to add to the changelog. 
Do you mind doing that?

**Comment by btasker** [comment]
@itsmylife sure - I'll try and take a look at doing that tomorrow.

One thing it occurred to me to check, so I'll ask you now:

There's probably potential for users to get confused by the addition of `Is` and assumed it's the same as `==`. If they then enter a string they won't get a result back. We *could* have `Is` apply some logic so that it works with strings (and only treats `true` or `false` as boolean - there'd be no b/c concern with that because existing cells obviously won't have `Is`).

**Comment by itsmylife** [comment]
@btasker I see your point. I got confused too while checking your PR. The best we can do is as you stated above _apply logic so that it works with strings_.

We can apply formatting to the values based on their types **for fields**. We got their types in the response. If the value is a string, we can apply quotes around; otherwise, we don't. For tags, we always need quotes around. The doc: https://docs.influxdata.com/influxdb/v2/query-data/influxql/explore-data/where/

But that requires some more change and careful testing. 

If you can provide a PR around this I'd be happy to help and review. Otherwise, I will create an issue for myself and put it in the backlog to prioritize/deliver this for upcoming months.

**Comment by btasker** [comment]
Ok first PR is up: https://github.com/grafana/grafana/pull/77917 adds the `>=` and `<=` operators.

I'm *not* putting a PR up to change the handling of `<>` because there's a b/c issue (it works as an inequality operator on strings too).

I'll get one up for `Is` / `Is Not` shortly

**Comment by btasker** [comment]
The Is / Is not change (with type inference) is at https://github.com/grafana/grafana/pull/77923

**Comment by itsmylife** [comment]
I am closing this in favor of these two PRs:
- https://github.com/grafana/grafana/pull/77917
- https://github.com/grafana/grafana/pull/77923

**Pull request closed without merging**
