### PR TITLE
Docs: Breaking changes guide in a directory

### PR DESCRIPTION
**Pull request by krishnemd**
**What is this feature?**
Breaking changes files were not well managed in /contribute directory. This PR fixes such issue by grouping the content together.

**Why do we need this feature?**
To manage documentation section and promote cleaner file structure.

**Who is this feature for?**

Software developers at Grafana.

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by chauchausoup** [comment]
@mckn

**Comment by mckn** [comment]
> @mckn

I have pinged @josmperez and he will review and move this PR forward.

**Review by josmperez — APPROVED** [review]
LGTM, thanks for the contribution. There are some unsuccessful checks, however, that will need to be addressed. I am assigning this to myself for the time being.

**Pull request merged**
