### PR TITLE
Chore: Fix position for RolePickerMenu being out of bounds

### PR DESCRIPTION
**Pull request by linoman**
**What is this feature?**

This feature adds an extra validation to ensure the RolePicker menu doesn't go out of bounds and instead stays in an absolute position to avoid flying out of the screen when too many entries are set.

**Why do we need this feature?**

Details about the current behaviour can be found [here](https://github.com/grafana/support-escalations/issues/9964).

**Who is this feature for?**

IAM and front-end.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/support-escalations/issues/9964

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by IevaVasiljeva — COMMENTED** [review]
I've tested the change, and it fixes the issue, but makes it hard to see the list of the assigned roles while the role picker is open as the role picker is on top of the roles. I wonder if it would be possible to have the role picker below the roles, but limit the max size of the role box (and either make it scrollable or say something like `...and 35 more` as you suggested).

Screenshot 2024-04-04 at 17 14 57

**Comment by linoman** [comment]
@IevaVasiljeva, thank you for your speedy review!

I decided against the `... and 35 more` because the list of permissions provides a clear snapshot of the big picture of all the roles/permissions added.

However, something really interesting might be to see if adding a set of permissions can be displayed as `Annotations +2,` which is the role plus the number of permissions.

Also, as per your screenshot, I noticed that the left side of the menu overlaps a bit with the right side. The arrows are not shown properly.

I'm converting this PR as a draft, and I'll rework it before requesting a review again.

**Review by IevaVasiljeva — APPROVED** [review]
Nice, looks much better now! I tested with a lot of roles, and couldn't get the role picker to disappear anymore, so I think we're good to merge this. Thanks again for handling it!

**Pull request merged**
