### PR TITLE
Update create-notification-policy.md

### PR DESCRIPTION
**Pull request by flopp999**
found an extra /

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by brendamuir** [comment]
thanks for the contribution! could you please sign the CLA then we can get this update merged - thanks!

**Comment by flopp999** [comment]
> thanks for the contribution! could you please sign the CLA then we can get this update merged - thanks!

done now

**Review by brendamuir — APPROVED** [review]

**Comment by brendamuir** [comment]
hi there -- could you update your branch, too, please?

**Comment by flopp999** [comment]
> hi there -- could you update your branch, too, please?

I don't know if I did it correct. I opened my fork and clicked on "Sync fork" then update. I was 48 commits behind.
Was this correct?

**Pull request merged**
