### PR TITLE
Transformations: Improve UX and fix refId issues

### PR DESCRIPTION
**Pull request by torkelo**
* Fixes strange h5 field label (replaced by normal Field) 
* Tries to fix the "Query undefined" issue for data sources that don't set refId 

But I am confused by this Select. It shows frames, but the value is the refId so it filters by refId but shows frames? Missing a group by / unique check? 

A single query that returns 50 frames will show 50 frames in that select all with the same refId 

Bug
Screenshot from 2023-04-05 09-48-03

### CODE REVIEW

**Comment by torkelo** [comment]
I pushed an update where I now show in the select only unique queries (refIds), and in the description I show the name of the frames (max 3) 

Screenshot from 2023-04-05 10-16-21

**Comment by ryantxu** [comment]
@torkelo I pushed a change to this that moves the core logic to the `@grafana/ui` matcher... so it is also used in the field override picker

**Review by ryantxu — APPROVED** [review]
@torkelo ... approving, but you should check my work (mostly moving yours!)

Also, IIUC, this should not be backported -- it does not seem urgent enough to require the extra attention needed for that.

**Comment by torkelo** [comment]
@ryantxu added a react testing lib unit test for the RefIDPicker component

**Pull request merged**
