### PR TITLE
Increase datasource limit to 1000 #3910

### PR DESCRIPTION
**Pull request by rubycut**
- Link the PR to an issue for new features
- Rebase your PR if it gets out of sync with master

### CODE REVIEW

**Comment by rubycut** [comment]
Fixes  #3910

**Comment by mattbostock** [comment]
Will this be released soon?

**Comment by bergquist** [comment]
@mattbostock available in the 4.0 beta.

**Comment by mattbostock** [comment]
@bergquist Great, thanks!

**Pull request merged**
