### PR TITLE
Register frontend logging endpoints as routes

### LINKED ISSUE #66099: Frontend logging endpoints are registered as a middleware
These two endpoints are registered as a middleware rather than as route handlers:

```
const sentryLogEndpointPath = "/log"
const grafanaJavascriptAgentEndpointPath = "/log-grafana-javascript-agent"
```

https://github.com/grafana/grafana/blob/c2cea076ee7b59faf0faf239dd0025d62273af16/pkg/api/frontend_logging.go#L145
https://github.com/grafana/grafana/blob/be9361cb9ec2f1ad0bc0cda139c56e3cd46deb16/pkg/api/http_server.go#L620

This should be registered as endpoints on the route register in `pkg/api/api.go`.

### PR DESCRIPTION
**Pull request by kousikmitra**
**What is this feature?**

This PR will remove frontend logging endpoint from middleware and add them in the route list.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #66099 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by papagian — COMMENTED** [review]
thank you for your contribution, LGTM!
As a follow up, I think that the [frontendLogEndpoints()](https://github.com/grafana/grafana/blob/ae373c662c65562def7f07f27f2218319ed6347e/pkg/api/frontend_logging.go#L101)
can be simplified a bit (no need to check for the method POST)

**Comment by kousikmitra** [comment]
> thank you for your contribution, LGTM! As a follow up, I think that the [frontendLogEndpoints()](https://github.com/grafana/grafana/blob/ae373c662c65562def7f07f27f2218319ed6347e/pkg/api/frontend_logging.go#L101) can be simplified a bit (no need to check for the method POST)

Done.

Remove `POST /log` api handler too, as it was already removed from the code.

**Review by zserge — APPROVED** [review]

**Comment by tonypowa** [comment]
@papagian 
dear reviewers, 
this PR seems to be ready to be merged 
could you please confirm? 

many thanks

**Pull request closed without merging**
