### PR TITLE
CloudMonitoring: Add possibility to use path for private key

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What is this feature?**

This PR updates the grafana/google-sdk-react to latest which adds the possibility to enter the authentication details by hand and also to specify a file for private key.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [x] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [x] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

**Comment by zoltanbedi** [comment]
@grafana/partner-plugins does this need to be behind a feature flag? WDYT?

**Review by aangelisc — APPROVED** [review]
Great work @zoltanbedi! Thank you for updating the plugin 😊 I would suggest putting this behind a feature flag for now and maybe adding some monitoring metrics so that we can see what the usage of this looks like.

**Review by aangelisc — APPROVED** [review]
Thank you for the updates!

**Comment by zoltanbedi** [comment]
We didn't put this behind a feature flag as this is not a breaking change just and addition.

**Pull request merged**
