### PR TITLE
Chore: Cherry Picks for 7.2.0-beta2

### PR DESCRIPTION
**Pull request by hugohaggmark**
--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Grafana-UI: Add docs for ConfirmButton, (#27477), merge-sha: 1a5c049883c50227f16d140c62abed1f759201a0
  * Update Input.mdx, (#26226), merge-sha: b01a64e146951d46c9cc047c6b2ce48bca502b1d
  * Alerting: Fix integration key so it's stored encrypted for Pagerduty notifier, (#27484), merge-sha: 91a8937e6c6b392bd725c9bfa8466e187d640fa4
  * Azure/Insights: Fix handling of legacy dimension values, (#27513), merge-sha: e85b266f2ead3fdca7f981d62e52d5868e9c129a
  * Prometheus: Fix min step variable interpolation, (#27505), merge-sha: a7ac3f141950734020598d049374655c222c60ba
  * Notifications: UX tweak to redesign of form and sections to make it left aligned and cleaner, (#27479), merge-sha: 0132bca93a25111b26d4cfecf2fbe62a1e9bb5c3
  * Provisioning: Remove provisioned dashboards without parental reader, (#26143), merge-sha: 6e3e0dead8629f1bf1007bda06ac96c68710078e
  * Binary-prefixed data rates, (#27022), merge-sha: 794333de3ddb7bbe186a4a861143ceee24c7e992
  * Revert "Alerting: New feature toggle for enabling standalone alerts (…, (#27531), merge-sha: 924224eefbfb55622d52a0687a098f43b202a8c0
  * Transforms: Fix for issue in labels to fields transform where the new option value field name did not work properly, (#27501), merge-sha: 61463aa123c705610deb09ef117760317786d6ed
  * BootData: Fix nav tree sort regression, (#27533), merge-sha: 1983de962c5543dbebf5d5f0b2d023fd3fdedd6e
  * Grafana-UI: Expand ConfirmModal docs, (#27541), merge-sha: 126683929c138eeffa725e7fe109cdbc46be1f56
  * Annotations: add standard annotations support (and use it for flux queries), (#27375), merge-sha: 5d11d8faa3b59a918d0c8d3036b775d7ce79a597
  * Alerting API: send 404 not found error and enrich delete with UID endpoint response with alert notification ID, (#27550), merge-sha: 0c4b7d3f5d4a1e315f822cd0bf200b2952cb424c
  * Toolkit: clean node_modules/@grafana/data/node_modules in prepare, (#27554), merge-sha: b3b72b8ae6e110ac7354f22d5237c0aa0159bcc3
  * Templating: global/system variables should be properly replaced in templated values., (#27394), merge-sha: 0c8390cea26b55126bfae9b0a48b738c8bd46ebc
  * PanelEdit: Drag and drop query order & UI tweaks, (#27502), merge-sha: 8759a912223ccd9d69289eb4d05b2eab558821d0
  * Org API: enrich add user to org endpoints with user ID in the response, (#27551), merge-sha: eb970a49855b74cc587ac01cdd7976956827c157
  * Annotations: Fixes issue with showing error notice for cancelled annotation queries, (#27557), merge-sha: b37e132cec29836df692f607e1ce72e8b4b2bb27
  * Instrumentation: Fix panicking if there is no response, (#27567), merge-sha: f52922345515b5cf558e233c860d0a0e3ce7a5bb
  * Auth: Replace maximum inactive/lifetime settings of days to duration, (#27150), merge-sha: 8d971ab2f2a834d7dd1b48073d5a67480a6a9809
  * Chore: use visualization name in field config header, (#27579), merge-sha: c180facba52fc6af74f3cc4698bed3efd05dd897
  * Postgres: Support request cancellation properly (Uses new backendSrv.fetch Observable request API), (#27478), merge-sha: a587bf4f5643bfc5a187e4f47666bd469675faf0
  * Variables: Limit rendering of options in dropdown to improve search performance , (#27525), merge-sha: 0d2fbd2acdba04f6e64d075bf24582125db77db0
  * Elasticsearch: Allow fields starting with underscore, (#27520), merge-sha: a0beaa3bbe979f0697dca9a38d0e0bdf6dec7b1d
  * Elasticsearch: Increase maximum geohash aggregation precision to 12, (#27539), merge-sha: e350e1fff6b1903621d69aaf2d603a82923cbb87
  * Field config: Add support for paths in default field config setup, (#27570), merge-sha: e04e3e7d4666093ab53f9e47ee8d83bcb405adf8
  * Annotation:  use DataFrame[] rather than a single DataFrame, (#27587), merge-sha: 1e4846d443ceee7d05d40c01f0db1ef5a34557b1
  * Docs: Field config docs update, Table docs update, Override matcher naming issue, (#27558), merge-sha: cade6dd01043895a67ea8d25ae40b80ba930afb4
  * Dashboard: Support configuring default timezone via config file, (#27404), merge-sha: 39eba5065bfdd86686bfe3422a2f84b49f0d32f9
  * Graph: only show range warning when all data is outside time range, (#27603), merge-sha: 54b677bda468fc5756fa2fe3747fef5666def058
  * NewsPanel: Fixed XSS issue when rendering rss links, (#27612), merge-sha: b58864792de7aedf7b1a0d6862b2e2177e0a277e
  * InputControl: Fixed using InputControl in unit tests from plugins, (#27615), merge-sha: 2ed91247362f81c4398c2ed23096f1e4b95824e5
  * backend-plugins: point to request Headers in the wrapper, (#27599), merge-sha: 50c680f3d7795256a88daa7a05728e8efe53ef45
  * ImageRendering: Fix rendering panel using shared query in png, PDF reports and embedded scenarios , (#27628), merge-sha: c450ffd711fcd0d8b0b98c8d1f290b1f595df449
  * SharedQuery: Error when switching to -- Dashboard -- data source caused "no data" no matter what source panel was selected, (#27627), merge-sha: 31e2b7e7c82870294b0a2c96a5740eb07969ec60
  * ApiKeys: Fixes close('X') button layout issue, (#27625), merge-sha: 5a06ed431cc3bd97759ed514589fbea4ba236777
  * DataLinks: Respects display name and adds field quoting, (#27616), merge-sha: e86ff52d44eb55f830c359c6e4ad0d08936811b9
  * Elasticsearch: Add support for date_nanos type, (#27538), merge-sha: 0e34474099cab7bf45281b88ef135f29a330f1b6
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x 1a5c049883c50227f16d140c62abed1f759201a0
  git cherry-pick -x b01a64e146951d46c9cc047c6b2ce48bca502b1d
  git cherry-pick -x 91a8937e6c6b392bd725c9bfa8466e187d640fa4
  git cherry-pick -x e85b266f2ead3fdca7f981d62e52d5868e9c129a
  git cherry-pick -x a7ac3f141950734020598d049374655c222c60ba
  git cherry-pick -x 0132bca93a25111b26d4cfecf2fbe62a1e9bb5c3
  git cherry-pick -x 6e3e0dead8629f1bf1007bda06ac96c68710078e
  git cherry-pick -x 794333de3ddb7bbe186a4a861143ceee24c7e992
  git cherry-pick -x 924224eefbfb55622d52a0687a098f43b202a8c0
  git cherry-pick -x 61463aa123c705610deb09ef117760317786d6ed
  git cherry-pick -x 1983de962c5543dbebf5d5f0b2d023fd3fdedd6e
  git cherry-pick -x 126683929c138eeffa725e7fe109cdbc46be1f56
  git cherry-pick -x 5d11d8faa3b59a918d0c8d3036b775d7ce79a597
  git cherry-pick -x 0c4b7d3f5d4a1e315f822cd0bf200b2952cb424c
  git cherry-pick -x b3b72b8ae6e110ac7354f22d5237c0aa0159bcc3
  git cherry-pick -x 0c8390cea26b55126bfae9b0a48b738c8bd46ebc
  git cherry-pick -x 8759a912223ccd9d69289eb4d05b2eab558821d0
  git cherry-pick -x eb970a49855b74cc587ac01cdd7976956827c157
  git cherry-pick -x b37e132cec29836df692f607e1ce72e8b4b2bb27
  git cherry-pick -x f52922345515b5cf558e233c860d0a0e3ce7a5bb
  git cherry-pick -x 8d971ab2f2a834d7dd1b48073d5a67480a6a9809
  git cherry-pick -x c180facba52fc6af74f3cc4698bed3efd05dd897
  git cherry-pick -x a587bf4f5643bfc5a187e4f47666bd469675faf0
  git cherry-pick -x 0d2fbd2acdba04f6e64d075bf24582125db77db0
  git cherry-pick -x a0beaa3bbe979f0697dca9a38d0e0bdf6dec7b1d
  git cherry-pick -x e350e1fff6b1903621d69aaf2d603a82923cbb87
  git cherry-pick -x e04e3e7d4666093ab53f9e47ee8d83bcb405adf8
  git cherry-pick -x 1e4846d443ceee7d05d40c01f0db1ef5a34557b1
  git cherry-pick -x cade6dd01043895a67ea8d25ae40b80ba930afb4
  git cherry-pick -x 39eba5065bfdd86686bfe3422a2f84b49f0d32f9
  git cherry-pick -x 54b677bda468fc5756fa2fe3747fef5666def058
  git cherry-pick -x b58864792de7aedf7b1a0d6862b2e2177e0a277e
  git cherry-pick -x 2ed91247362f81c4398c2ed23096f1e4b95824e5
  git cherry-pick -x 50c680f3d7795256a88daa7a05728e8efe53ef45
  git cherry-pick -x c450ffd711fcd0d8b0b98c8d1f290b1f595df449
  git cherry-pick -x 31e2b7e7c82870294b0a2c96a5740eb07969ec60
  git cherry-pick -x 5a06ed431cc3bd97759ed514589fbea4ba236777
  git cherry-pick -x e86ff52d44eb55f830c359c6e4ad0d08936811b9
  git cherry-pick -x 0e34474099cab7bf45281b88ef135f29a330f1b6

  --------------------------------------------------------------------
  grabpl verify-cherrypicks 7.2.0-beta2 27633
  --------------------------------------------------------------------
* Verifying cherry-pick PR 27633 for milestone "7.2.0-beta2"...
* Listing milestones, page 0
* Found 30 milestone(s) for page 0
* Listing milestones, page 2
* Found 30 milestone(s) for page 2
* Listing milestones, page 3
* Found 30 milestone(s) for page 3
* Milestone "7.2.0-beta2" is a match
* Listing issues with milestone number 194, state "closed" and label "cherry-pick needed" - page 0
* Got PR #27628 (ImageRendering: Fix rendering panel using shared query in png, PDF reports and embedded scenarios ) - merge commit c450ffd711fcd0d8b0b98c8d1f290b1f595df449
* Got PR #27627 (SharedQuery: Error when switching to -- Dashboard -- data source caused "no data" no matter what source panel was selected) - merge commit 31e2b7e7c82870294b0a2c96a5740eb07969ec60
* Got PR #27625 (ApiKeys: Fixes close('X') button layout issue) - merge commit 5a06ed431cc3bd97759ed514589fbea4ba236777
* Got PR #27616 (DataLinks: Respects display name and adds field quoting) - merge commit e86ff52d44eb55f830c359c6e4ad0d08936811b9
* Got PR #27615 (InputControl: Fixed using InputControl in unit tests from plugins) - merge commit 2ed91247362f81c4398c2ed23096f1e4b95824e5
* Got PR #27612 (NewsPanel: Fixed XSS issue when rendering rss links) - merge commit b58864792de7aedf7b1a0d6862b2e2177e0a277e
* Got PR #27603 (Graph: only show range warning when all data is outside time range) - merge commit 54b677bda468fc5756fa2fe3747fef5666def058
* Got PR #27599 (backend-plugins: point to request Headers in the wrapper) - merge commit 50c680f3d7795256a88daa7a05728e8efe53ef45
* Got PR #27587 (Annotation:  use DataFrame[] rather than a single DataFrame) - merge commit 1e4846d443ceee7d05d40c01f0db1ef5a34557b1
* Got PR #27579 (Chore: use visualization name in field config header) - merge commit c180facba52fc6af74f3cc4698bed3efd05dd897
* Got PR #27570 (Field config: Add support for paths in default field config setup) - merge commit e04e3e7d4666093ab53f9e47ee8d83bcb405adf8
* Got PR #27567 (Instrumentation: Fix panicking if there is no response) - merge commit f52922345515b5cf558e233c860d0a0e3ce7a5bb
* Got PR #27558 (Docs: Field config docs update, Table docs update, Override matcher naming issue) - merge commit cade6dd01043895a67ea8d25ae40b80ba930afb4
* Got PR #27557 (Annotations: Fixes issue with showing error notice for cancelled annotation queries) - merge commit b37e132cec29836df692f607e1ce72e8b4b2bb27
* Got PR #27554 (Toolkit: clean node_modules/@grafana/data/node_modules in prepare) - merge commit b3b72b8ae6e110ac7354f22d5237c0aa0159bcc3
* Got PR #27551 (Org API: enrich add user to org endpoints with user ID in the response) - merge commit eb970a49855b74cc587ac01cdd7976956827c157
* Got PR #27550 (Alerting API: send 404 not found error and enrich delete with UID endpoint response with alert notification ID) - merge commit 0c4b7d3f5d4a1e315f822cd0bf200b2952cb424c
* Got PR #27541 (Grafana-UI: Expand ConfirmModal docs) - merge commit 126683929c138eeffa725e7fe109cdbc46be1f56
* Got PR #27539 (Elasticsearch: Increase maximum geohash aggregation precision to 12) - merge commit e350e1fff6b1903621d69aaf2d603a82923cbb87
* Got PR #27538 (Elasticsearch: Add support for date_nanos type) - merge commit 0e34474099cab7bf45281b88ef135f29a330f1b6
* Got PR #27533 (BootData: Fix nav tree sort regression) - merge commit 1983de962c5543dbebf5d5f0b2d023fd3fdedd6e
* Got PR #27531 (Revert "Alerting: New feature toggle for enabling standalone alerts (…) - merge commit 924224eefbfb55622d52a0687a098f43b202a8c0
* Got PR #27525 (Variables: Limit rendering of options in dropdown to improve search performance ) - merge commit 0d2fbd2acdba04f6e64d075bf24582125db77db0
* Got PR #27520 (Elasticsearch: Allow fields starting with underscore) - merge commit a0beaa3bbe979f0697dca9a38d0e0bdf6dec7b1d
* Got PR #27513 (Azure/Insights: Fix handling of legacy dimension values) - merge commit e85b266f2ead3fdca7f981d62e52d5868e9c129a
* Got PR #27505 (Prometheus: Fix min step variable interpolation) - merge commit a7ac3f141950734020598d049374655c222c60ba
* Got PR #27502 (PanelEdit: Drag and drop query order & UI tweaks) - merge commit 8759a912223ccd9d69289eb4d05b2eab558821d0
* Got PR #27501 (Transforms: Fix for issue in labels to fields transform where the new option value field name did not work properly) - merge commit 61463aa123c705610deb09ef117760317786d6ed
* Got PR #27484 (Alerting: Fix integration key so it's stored encrypted for Pagerduty notifier) - merge commit 91a8937e6c6b392bd725c9bfa8466e187d640fa4
* Got PR #27479 (Notifications: UX tweak to redesign of form and sections to make it left aligned and cleaner) - merge commit 0132bca93a25111b26d4cfecf2fbe62a1e9bb5c3
* Listing issues with milestone number 194, state "closed" and label "cherry-pick needed" - page 2
* Got PR #27478 (Postgres: Support request cancellation properly (Uses new backendSrv.fetch Observable request API)) - merge commit a587bf4f5643bfc5a187e4f47666bd469675faf0
* Got PR #27477 (Grafana-UI: Add docs for ConfirmButton) - merge commit 1a5c049883c50227f16d140c62abed1f759201a0
* Got PR #27404 (Dashboard: Support configuring default timezone via config file) - merge commit 39eba5065bfdd86686bfe3422a2f84b49f0d32f9
* Got PR #27394 (Templating: global/system variables should be properly replaced in templated values.) - merge commit 0c8390cea26b55126bfae9b0a48b738c8bd46ebc
* Got PR #27375 (Annotations: add standard annotations support (and use it for flux queries)) - merge commit 5d11d8faa3b59a918d0c8d3036b775d7ce79a597
* Got PR #27150 (Auth: Replace maximum inactive/lifetime settings of days to duration) - merge commit 8d971ab2f2a834d7dd1b48073d5a67480a6a9809
* Got PR #27022 (Binary-prefixed data rates) - merge commit 794333de3ddb7bbe186a4a861143ceee24c7e992
* Got PR #26226 (Update Input.mdx) - merge commit b01a64e146951d46c9cc047c6b2ce48bca502b1d
* Got PR #26143 (Provisioning: Remove provisioned dashboards without parental reader) - merge commit 6e3e0dead8629f1bf1007bda06ac96c68710078e
* Found 39 PR(s)
* Getting the cherry-pick PR (27633)
* Getting commits included in cherry-pick PR
* Getting commits included in cherry-pick PR
* Got 10 commit(s) for cherry-pick PR
* Got 40 commit(s) for cherry-pick PR
* Correlating the cherry-pick PR's commits
* Found corresponding PR #27477 ("Grafana-UI: Add docs for ConfirmButton")
* Found corresponding PR #26226 ("Update Input.mdx")
* Found corresponding PR #27484 ("Alerting: Fix integration key so it's stored encrypted for Pagerduty notifier")
* Found corresponding PR #27513 ("Azure/Insights: Fix handling of legacy dimension values")
* Found corresponding PR #27505 ("Prometheus: Fix min step variable interpolation")
* Found corresponding PR #27479 ("Notifications: UX tweak to redesign of form and sections to make it left aligned and cleaner")
* Found corresponding PR #26143 ("Provisioning: Remove provisioned dashboards without parental reader")
* Found corresponding PR #27022 ("Binary-prefixed data rates")
* Found corresponding PR #27531 ("Revert \"Alerting: New feature toggle for enabling standalone alerts (…")
* Found corresponding PR #27501 ("Transforms: Fix for issue in labels to fields transform where the new option value field name did not work properly")
* Found corresponding PR #27533 ("BootData: Fix nav tree sort regression")
* Found corresponding PR #27541 ("Grafana-UI: Expand ConfirmModal docs")
* Found corresponding PR #27375 ("Annotations: add standard annotations support (and use it for flux queries)")
* Found corresponding PR #27550 ("Alerting API: send 404 not found error and enrich delete with UID endpoint response with alert notification ID")
* Found corresponding PR #27554 ("Toolkit: clean node_modules/@grafana/data/node_modules in prepare")
* Found corresponding PR #27394 ("Templating: global/system variables should be properly replaced in templated values.")
* Found corresponding PR #27502 ("PanelEdit: Drag and drop query order & UI tweaks")
* Found corresponding PR #27551 ("Org API: enrich add user to org endpoints with user ID in the response")
* Found corresponding PR #27557 ("Annotations: Fixes issue with showing error notice for cancelled annotation queries")
* Found corresponding PR #27567 ("Instrumentation: Fix panicking if there is no response")
* Found corresponding PR #27150 ("Auth: Replace maximum inactive/lifetime settings of days to duration")
* Found corresponding PR #27579 ("Chore: use visualization name in field config header")
* Found corresponding PR #27478 ("Postgres: Support request cancellation properly (Uses new backendSrv.fetch Observable request API)")
* Found corresponding PR #27525 ("Variables: Limit rendering of options in dropdown to improve search performance ")
* Found corresponding PR #27520 ("Elasticsearch: Allow fields starting with underscore")
* Found corresponding PR #27539 ("Elasticsearch: Increase maximum geohash aggregation precision to 12")
* Found corresponding PR #27570 ("Field config: Add support for paths in default field config setup")
* Found corresponding PR #27587 ("Annotation:  use DataFrame[] rather than a single DataFrame")
* Found corresponding PR #27558 ("Docs: Field config docs update, Table docs update, Override matcher naming issue")
* Found corresponding PR #27404 ("Dashboard: Support configuring default timezone via config file")
* Found corresponding PR #27603 ("Graph: only show range warning when all data is outside time range")
* Found corresponding PR #27612 ("NewsPanel: Fixed XSS issue when rendering rss links")
* Found corresponding PR #27615 ("InputControl: Fixed using InputControl in unit tests from plugins")
* Found corresponding PR #27599 ("backend-plugins: point to request Headers in the wrapper")
* Found corresponding PR #27628 ("ImageRendering: Fix rendering panel using shared query in png, PDF reports and embedded scenarios ")
* Found corresponding PR #27627 ("SharedQuery: Error when switching to -- Dashboard -- data source caused \"no data\" no matter what source panel was selected")
* Found corresponding PR #27625 ("ApiKeys: Fixes close('X') button layout issue")
* Found corresponding PR #27616 ("DataLinks: Respects display name and adds field quoting")
* Found corresponding PR #27538 ("Elasticsearch: Add support for date_nanos type")
* Couldn't determine cherry-picked commit from message of "d4514dd2d8b2b94aa449fc84f630c60eb2d694a4"

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good!

**Review by mckn — APPROVED** [review]
LGTM, exciting stuff on its way to out end users!

**Review by dprokop — APPROVED** [review]
Goodie!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
