### PR TITLE
Theme: Update old css class add-data-source-item to use card styling

### PR DESCRIPTION
**Pull request by torkelo**
This old class  `add-data-source-item`  is not used anywhere in the core app but is used by the synthetics app Probes list (this should be updated). 

But in the meantime this PR just updates the styling of this old class to follow the standard card background & hover. 

Before:
Screenshot from 2023-11-01 11-07-20

After:
Screenshot from 2023-11-01 11-03-38

### CODE REVIEW

**Review by L-M-K-B — COMMENTED** [review]
One question: As we have a Card component in grafana-ui wouldn't it make sense to use it in [grafana/synthetic-monitoring-app](https://github.com/grafana/synthetic-monitoring-app) and [grafana/iot-sitewise-datasource](https://github.com/grafana/iot-sitewise-datasource) instead of this sass class?

**Comment by torkelo** [comment]
> One question: As we have a Card component in grafana-ui wouldn't it make sense to use it in [grafana/synthetic-monitoring-app](https://github.com/grafana/synthetic-monitoring-app) and [grafana/iot-sitewise-datasource](https://github.com/grafana/iot-sitewise-datasource) instead of this sass class?

@L-M-K-B of course, as I said tin the PR this should be updated to use the card component but this is just a temporary quick fix

**Review by L-M-K-B — APPROVED** [review]
Then we are good to go with this PR. In order to make sure we don't forget about it could you please open a follow up issue for replacing the sass class?

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
