### PR TITLE
Add `--tries 3` arg when triggering e2e-tests upon releasing

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR will increase the total tries of the e2e tests from 2 (the default value) to 3, since we've seen e2e tests failing randomly. This will potentially be a good step to improve the passing pipelines when it comes to releases, but probably something to check with the Frontend in the future.

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
Should we use three tries for all builds? I thought of just using it for release builds, since otherwise it will take a while to tell that a build has broken e2e. I'm not sure though, what's best.

**Comment by dsotirakis** [comment]
> Should we use three tries for all builds? I thought of just using it for release builds, since otherwise it will take a while to tell that a build has broken e2e. I'm not sure though, what's best.

Hmm, is it going to run all 3 tries? I mean if it passes on the first try, the other two aren't going to be triggered, so from that point of view the pipeline running time isn't going to change? 
And another thing is, that maybe if an e2e on a PR for example fails 3 times, this may be a sign that something's wrong there and should be fixed before we merge to master and/or release? Not sure what's best either.

**Comment by aknuds1** [comment]
> > Should we use three tries for all builds? I thought of just using it for release builds, since otherwise it will take a while to tell that a build has broken e2e. I'm not sure though, what's best.
> 
> Hmm, is it going to run all 3 tries? I mean if it passes on the first try, the other two aren't going to be triggered, so from that point of view the pipeline running time isn't going to change?

I'm only thinking of the case where there's an actual bug in the PR that makes the e2e tests fail, then you have to wait for them to fail 3 times before the PR is flagged as broken. I'm not sure if it's a good idea or not?

> And another thing is, that maybe if an e2e on a PR for example fails 3 times, this may be a sign that something's wrong there and should be fixed before we merge to master and/or release? Not sure what's best either.

After e2e fails, you usually go through the errors and see if you've broken something. The only question is if you should have to wait for 3 e2e runs to see if it failed or not.

**Comment by dsotirakis** [comment]
@aknuds1 Yep, I think both arguments make sense and are equally valid or invalid. The straightest target here should be to ensure that the e2e are not flakey rather than anything else. But since that’s a standalone thing that should be opened on another issue, then better to only add the retry at the releases as you said at least for now and see how that goes. If the problem insists on PRs also, even if they are not blockers, we should do the same as well.

**Comment by torkelo** [comment]
yes, only on release builds. We want the pain on PRs & master so we can make the tests no be flaky :)  with retries there we might miss flaky tests and it will take longer for real errors to be reported

**Comment by aknuds1** [comment]
@torkelo's scheme sounds good, so just increase retries on releases :)

**Comment by dsotirakis** [comment]
Sounds good, thank you both, made the changes only on the release pipelines, feel free to have a look again.

**Review by aknuds1 — APPROVED** [review]
LGTM

**Pull request merged**
