### PR TITLE
GraphNG: Remove plot context

### LINKED ISSUE #38927: Get rid of PlotContext in GraphNG

### PR DESCRIPTION
**Pull request by dprokop**
Closes https://github.com/grafana/grafana/issues/38927

TODO:
- [x] TooltipPlugin/EventsCanvas throws warning about setState being called on unmounted component

### CODE REVIEW

**Comment by dprokop** [comment]
@zoltanbedi do you mind testing Exemplars agains this PR?

**Comment by zoltanbedi** [comment]
> @zoltanbedi do you mind testing Exemplars against this PR?

Checked and exemplars works as expected. Also there is an e2e test for exemplars workflow so we will know if it is broken.

**Comment by leeoniya** [comment]
does not seem to break anything in my testing, also checked for mem leaks.

we do a bunch of initial setup in `useLayoutEffect`, and inside of it we have various `isMounted()` checks, which themselves appear to be set up in a `useEffect` hook [1]. not sure if this can be simplified then by just using useEffect directly :shrug: 

these in combo with `plotInstance` existence checks leaves the whole init/re-render cycle somewhat confusing to me. but maybe we can simplify in a followup PR.

[1] https://github.com/streamich/react-use/blob/master/src/useMountedState.ts#L7

**Review by leeoniya — APPROVED** [review]

**Comment by dprokop** [comment]
> we do a bunch of initial setup in useLayoutEffect, and inside of it we have various isMounted() checks, which themselves appear to be set up in a useEffect hook [1]. not sure if this can be simplified then by just using useEffect directly 🤷


indeed, it probably can, but wanted to keep this PR focused on one thing :)

**Pull request merged**
