### PR TITLE
Live: Default to local engine if redis is unavailable

### PR DESCRIPTION
**Pull request by jcalisto**
**What is this feature?**

Avoid crashing Grafana when the Live Engine is configured for HA but Redis is not available.

**Why do we need this feature?**

Redis can be down for several reasons, preventing Grafana from starting. We suggest changing this behaviour to default to initialize the Live service with the local engine instead if Grafana cannot connect to redis.

**Who is this feature for?**

Grafana operators

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
LGTM -- thank you

**Comment by summerwollin** [comment]
Did you end up testing with the ephemeral instance looks like it had an error? This definitely feels like something that needs to be tested in a deployed environment before we merge

**Comment by ryantxu** [comment]
> If redis is unavailable. How would grafana instances reconnect once redis is available again?

Good question!   and worth exploring a solution;  however the downside seems pretty minor at the moment since the failure mode is limited distribution of dashboard change events and datasources that do use streaming would duplicate work for each instance rather than sharing results.

🤔 if people are using advanced streaming and this kicks in ideally we have some way to know things are running in a degraded mode

**Comment by jcalisto** [comment]
> Yea thats fine for Live. But not for alertmanager duplication which also uses redis pub sub.

alertmanager sets up their own Redis client [[see here]](https://github.com/grafana/grafana/blob/5c9aeaef41f5c35dbbb4daeee16d676a38bfa21f/pkg/services/ngalert/notifier/redis_peer.go#L82) (ideally, with a different redis server too but that is up to the operator). This change only affects the Live service and has no impact on the alertmanager. Although, I believe it has a similar problem, if redis is not available at startup, failed channel subscribes are not retried after redis is up.

> This PR makes things easier for the operator but potentially worse for the user

Not necessarily I think, from a user perspective it would be better to have their instance running without live ha vs not being able to access the instance at all. 

I can have a look at possible options for reconnecting, but that sounds like a more generic problem where we want to update the service if any dependencies change.

**Comment by jcalisto** [comment]
> Did you end up testing with the ephemeral instance looks like it had an error?

Not yet, there's an issue with the ephemeral instances. Waiting for it to be fixed before testing & merging.

**Pull request merged**
