### PR TITLE
social: Add org_roles_attribute_path

### PR DESCRIPTION
**Pull request by isodude**
Add support for adding several organizations to one user.
The user also get a role set per organization.

How metadata from an OAuth2 is provided is not defined in RFC,
but a common way to do it is to do provide it as Base64.

Example metadata set in OAuth2 user_info.

```
{
  "metadata": {
    "orgroles": {
      "org": "Admin"
    }
  }
}
```

This patch assumes that it's returned to Grafana as
```
{
  "metadata": {
    "orgroles": "eyJvcmciOiAiQWRtaW4ifQ"
  }
}
```

role_attribute_path and org_roles_attribute_path should not interfere.

Keep in mind that to fetch metadata the correct scope is needed.

Signed-off-by: Josef Johansson <josef@oderland.se>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by isodude** [comment]
I realize that I should add support for grafana admin as well.
And maybe the possibility to specify the expected format in userinfo.

**Comment by Jguer** [comment]
Hey @isodude, thanks for taking the time to making a PR. 

This is a valuable feature we want to support and we've received a lot of feedback on, so we're trying to get it right. We've considered this approach and reached the following conclusions: 

- it's hard to maintain across all of the oauth2 integrations (which are due for a refactor).
- the new config option would be confusing for users and would add more edge cases for supporting users in their config and documentation.
- the base64 encoding value is ingenious, I had not seen it before used but seems very uncommon and in some forms unusable for providers like azure (which provides UUIDs and not values)

We're looking for a way to support this feature in a uniform way across the different auth methods and as such cannot accept this PR.

Currently I can't find an encompassing issue for this feature, if you'd like to contribute to its implementation could you create an issue detailing what you're trying to accomplish with org role mapping and what's your auth provider?

cc @mjseaman

**Comment by isodude** [comment]
It's no problem to support  it over several oauth2 integrations I think. I made it for just generic_oauth since it was my use case and I didn't want to introduce a major change.

The base64-thingy is opt in, thus changing _encoding = "base64" will make it decode. If not specified it will just assume an object instead. It could easily be modded to just detect if the data is actually base64 and then decode instead.

The auth provider here is a local instance of Zitadel.

Sure, I'll create an issue detailing the problem.

**Comment by isodude** [comment]
See discussion https://github.com/grafana/grafana/discussions/54732

**Pull request closed without merging**
