### PR TITLE
Added missing metrics for Consumer Lag dimension

### LINKED ISSUE #36819: Missing Metrics and Dimension for Consumer Lag in CloudWatch datasource
**What happened**:
CloudWatch data source for Namespace AWS/Kafka is lacking of couple of metrics related to Consumer Lag and Replication:

- EstimatedMaxTimeLag
- EstimatedTimeLag
- MaxOffsetLag
- SumOffsetLag
- OffsetLag
- ReplicationBytesInPerSec
- ReplicationBytesOutPerSec

also there is no Consumer Lag dimension only Broker ID, Topic and Cluster Name

According to this documentation it should have it:
https://docs.aws.amazon.com/msk/latest/developerguide/metrics-details.html

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard with CloudWatch as data source try, to find one of the above metrics on the list or try to find Consumer Lag dimension.
Zrzut ekranu 2021-07-15 o 23 52 08

**Anything else we need to know?**:

**Environment**:
- Grafana version: HEAD(main@8de218d)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser:  Mac/Chrome
- Grafana plugins: N/A
- Others:

I think that adding those metrics and dimension to this:
https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/metric_find_query.go

should be sufficient to fix the issue.

### PR DESCRIPTION
**Pull request by dannyfreak**
**What this PR does / why we need it**:
Add Consumer Lag dimension for AWS/Kafka namespace in CloudWatch data source also adds missing metrics for this dimension

**Which issue(s) this PR fixes**:
Fixes #36819

**Special notes for your reviewer**:

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
Thanks for the contribution! Would you mind signing the CLA?

**Comment by dannyfreak** [comment]
> Thanks for the contribution! Would you mind signing the CLA?

I've signed yesterday but It's still marked as unsigned.

**Comment by andresmgot** [comment]
> > Thanks for the contribution! Would you mind signing the CLA?
> 
> I've signed yesterday but It's still marked as unsigned.

:thinking: Would you mind clicking in the link "recheck" above? https://cla-assistant.io/check/grafana/grafana?pullRequest=36821

**Comment by andresmgot** [comment]
maybe the account @danielfryc needs to do it since the commit comes from its account

**Comment by dannyfreak** [comment]
> maybe the account @danielfryc needs to sign it since the commit comes from its account

My two accounts got mixed and on the second account I can't sign CLA on the other account. Maybe I'll close this PR and create a new one from @dannyfreak account?

**Comment by danielfryc** [comment]
> > maybe the account @danielfryc needs to sign it since the commit comes from its account
> 
> My two accounts got mixed and on the second account I can't sign CLA on the other account. Maybe I'll close this PR and create a new one from @dannyfreak account?

Ok, It worked.

**Pull request merged**
