### PR TITLE
[v8.3.x] up plugin sdk to v0.118.0 (#42167)

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

Manual backport of https://github.com/grafana/grafana/pull/42167

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

Sorry, forgot to backport this one #41868

**Comment by marefr** [comment]
Seems like there's a `go mod tidy` missing perhaps - CI failing

**Comment by FZambia** [comment]
Oops, merged before tests passed - was tricked by approve ✅ icon. Fingers crossed.

**Comment by FZambia** [comment]
🎉

**Pull request merged**
