### PR TITLE
Chore: Replace ng-annotate with babel-plugin-angularjs-annotate

### PR DESCRIPTION
**Pull request by stevenvachon**
**What this PR does / why we need it**:
[ng-annotate](https://npmjs.com/ng-annotate) is deprecated and was preventing ES2015+ code from being compiled.

**Which issue(s) this PR fixes**:
(none)

**Special notes for your reviewer**:
See the commit messages for the breakdown.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
This looks great -- I tested locally hitting the angular bits and it seems to work OK.  We should wait for a +1 from @dprokop or @torkelo before merging.

I think we should merge ASAP so we are testing against this soon, and this is the one blocker for ESLint #21006, and that is the blocker/fix for #20430 (that I would really like solved for 6.6)

**Comment by dprokop** [comment]
This looks good, especially that we will probably have to introduce babel-loader for dev/prod webpack config because of https://github.com/grafana/grafana/pull/21535.

The one thing I think would be good to do here is adjusting the webpack.dev to also use babel instead of ts-loader, same as you did with prod webpack config.

**Review by torkelo — APPROVED** [review]
Yea, good timing here, as emotion 10 requires babel

**Comment by dprokop** [comment]
@torkelo @ryantxu @stevenvachon 

So, tested this and seems like it's working fine. Some nice things that I have noticed:

- `yarn build` time: drop from ~250s to ~100s
- `yarn start` time: drop from ~50s to ~30s


On the darker end. Bundle size increased from 4.7MB to 5MB

**Review by dprokop — APPROVED** [review]

**Comment by dprokop** [comment]
@stevenvachon merged this but reverting with #21554 as e2e tests started failing. Not sure how to debug this unfortunately, would use some help from @torkelo

**Comment by stevenvachon** [comment]
That PRs tests appear to be randomly failing (postgres and mysql tests). Are those the same as what was failing after merging this PR? 

There is a timezone issue with an unrelated test that does need fixing.

**Comment by dprokop** [comment]
@stevenvachon nope, those are not related

**Comment by dprokop** [comment]
Created https://github.com/grafana/grafana/issues/21583 to keep track of things to be addressed before merging this

**Comment by stevenvachon** [comment]
These changes have been moved to #21587.

**Comment by dprokop** [comment]
thanks @stevenvachon

**Pull request merged**
