### PR TITLE
Do not clear query results on transaction start

### LINKED ISSUE #14986: Explore: Do not clear old transaction (data) when starting new queries
Currently Explore clears current data and re-renders empty graphs & tables when starting new query which creates a very turkey / jumpy experience between every query execution, expecially in logs mode where the page scrollbar is shown, then hidden when log lines is cleared, then shown again as they are re-rendered (with new data).

Also would like to change the current loading indicator to the spinner we use in dashboard panels to align the UX a bit more.

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #14986

This one needs further investigation beyond this fix. According to `ExploreItemState` interface definition, the `[table|logs|graph]Results` properties are optional(and they are defined this way on e.g. `LogsContainer` props). But, when provided via `mapStateToProps`, Typescript ignores this fact and does not complain about check against `undefined`.

### CODE REVIEW

**Review by davkal — COMMENTED** [review]
Certainly less jumpy, so that fix works.

But now with the bright loader gone, it's harder to see that something is happening. I think it's important for the fast query interaction to have visual feedback. (The pale spinner makes sense in a dashboard, where you dont manually run queries all the time.)
If there are issues with the loading indicator, I suggest to revisit this in a separate issue.

**Comment by dprokop** [comment]
@davkal I think we gonna revisit loading indicators when working on garana-ui

**Comment by davkal** [comment]
LGTM.

**Comment by dprokop** [comment]
UX improvements to loading indicator added for a less obtrusive feel

**Comment by davkal** [comment]
Even nicer.

**Pull request merged**
