### PR TITLE
flamegraph: Support x-selection zoom

### LINKED ISSUE #58373: Flamegraph: Better zoom focus interaction
When investigating flamegraph, if one node is too big, the rest is too big to grab. It would be nice if we could have a way to hide big nodes via right+click or using a regex.

See the example below:

image

### PR DESCRIPTION
**Pull request by chancez**
**What is this feature?**

Enables visually hightlighting an area on the flamegraph and zooming into it. The existing behavior of clicking on an individual node is still available.

**Why do we need this feature?**

This differs from the current zoom because it allows zooming across multiple nodes, rather than into a single node and it's children.

This is useful because some smaller nodes in a flamegraph do not have a parent which can be zoomed (the root node) or, zooming to the parent doesn't provide enough of a zoom, due to other siblings taking a larger portion of the level.

**Who is this feature for?**

When viewing a flamegraph, if one node is too big, or certain nodes are simply too small, relative to their siblings, they aren't visible, and it's difficult to view what their contents are. Being able to visually select an area on the graph to zoom allows you to zoom into these areas incrementally.

**Which issue(s) does this PR fix?**:

Fixes #58373

**Special notes for your reviewer**: 

My usage of `useRef` on the selection and `setSelection` is probably suspect. I'm new to react and I found the selection values were not being updated immediately when calling `setSelection`. It is my understanding that stateful values are lazily updated after useEffect runs. Since I need to track the value of startX and endX in the event handlers to compare them, I need the values to be immediately available. To fix this  I used `setSelection` with a reference to work around it. This solution basically came straight from stackoverflow, so I'm not sure if there is a better way.

### CODE REVIEW

**Comment by chancez** [comment]
A short little video of the behavior:
https://user-images.githubusercontent.com/1400401/208786850-3874fe89-ffc1-4770-8fa1-12bf34ed9a57.mov

**Review by joey-grafana — COMMENTED** [review]
Hey thank you so much for your contribution. This looks really good. 

Just a couple of things that could be polished before we merge into main.

- x-selection zoom does not work if I don't mouseup on a block. In this case, the highlight gets stuck to the cursor until another click is made (on a block). 

https://user-images.githubusercontent.com/90795735/211832416-b73a5cea-b4bb-4441-aeef-e6448a4e9246.mov

- need to mouseup on a block on the same row. Sometimes this works, but most of the time if I mouseup on a block on a different row the highlight gets stuck to the cursor.

https://user-images.githubusercontent.com/90795735/211832512-f2359711-151c-47c3-94cc-fe8edf978088.mov

- x-selection resets top level index. I wonder is there a better way to avoid resetting the top level index with an x-selection. It's a bit jarring to see the colours all change to their darker versions (as the top level index basically shades anything above it) and feels like you may have lost your place in the flame graph.

https://user-images.githubusercontent.com/90795735/211832842-1c37e726-380d-46a3-9d8e-20b8b8d15632.mov

Thanks again (and apologies for the delay in reviewing)

**Comment by chancez** [comment]
@joey-grafana Thanks for the review, no worries about the delay, I understand you also probably weren't expecting someone to go and implement this, so I appreciate it.

I'll see what I can do about the comments.

> x-selection zoom does not work if I don't mouseup on a block. 
I hit this too but didn't realize that was the cause, so this helps a lot. I'll try and fix that.

> need to mouseup on a block on the same row.

That's interesting. I never hit this issue. I'll try and reproduce.

> x-selection resets top level index.

This was actually intentional, but it may not make sense. While iterating it felt weird retaining the top level index as selected, but perhaps with the other changes I made, it will feel better now if I keep it.

**Comment by chancez** [comment]
> x-selection zoom does not work if I don't mouseup on a block. In this case, the highlight gets stuck to the cursor until another click is made (on a block).

I see a few ways I can solve this. 
1. I could look at using the pointer lock API to constrain the mouse to within the canvas element while the selection is being made. Based on my reading, the pointer lock API is still using browser based prefixes, so I'm not sure if this is stable/standardized yet, or if there's a better option for this.
2. I can either cancel or end the selection when the mouse leaves the canvas. However, it's pretty easy to accidentally leave the canvas when near the edges, so I don't like this for UX reasons.
3. I could attempt to track the mouse X position when it leaves the canvas and translate continue the selection, and handle mouseUp outside of the canvas for ending the selection.

I'm going to try option 3, because option 1 is unclear if it's going to be a stable enough API at the moment, and would be relatively easy to change to if it proves to be the best choice. Option 2 I'm not going to try because the UX feels bad.

Let me know if you have any other thoughts.

For the other issues:

> need to mouseup on a block on the same row. 

I still cannot reproduce this issue. What browser are you using? Here's have another clip trying to reproduce it by moving all around, rapidly, slow, and I can't get it to cancel like it did for you. 

https://user-images.githubusercontent.com/1400401/212192344-b6ffa926-b1a4-48f0-bf44-2d74939570d3.mov

> x-selection resets top level index. 

Retaining the top level index was easy. I'll push a change with that once I fix these other issues.

**Comment by chancez** [comment]
Actually, for:

> x-selection zoom does not work if I don't mouseup on a block

It seems I can copy how the time series panel handles it. It seems to basically select either everything to the left, or right (depending on which direction your selection is, and if you mouse up while outside the element it uses that as the selection.

**Comment by chancez** [comment]
Okay, I've fixed 2/3 issues, where 1/3 I couldn't reproduce. I added them as new commits to ease review.

**Review by joey-grafana — COMMENTED** [review]
Thanks again for the follow up. 

This is looking better but there are still a few kinks.

- On my laptop the shaded area that indicates a drag is happening is appearing to the left of where I am actually dragging. Again, this is only on my laptops resolution, not on the desktop.

https://user-images.githubusercontent.com/90795735/212859957-45d57618-5a1a-43b0-a679-26407af522f9.mov

- Not always detecting mouseup

https://user-images.githubusercontent.com/90795735/212875708-e0cd196c-d842-411e-9d55-8851fbaf2523.mov

These remaining issues could mostly be detected by tests if you could please add some that tests from a range of startY, startX -> endX positions. You should be able to use `fireEvent.mouseDown` + `fireEvent.mouseMove` + `fireEvent.mouseUp`

**Comment by chancez** [comment]
Currently just a bit busy with other tasks, I'm hoping to pick this back up soon, but just haven't found the time yet.

**Comment by leeoniya** [comment]
hey @chancez thanks for your work. just an update on why this hasn't moved forward. we've been figuring out exactly how we want to proceed with integrating/merging Pyroscope into Grafana after our recent acquisition.

what we settled on last week is to use the Pyroscope flame graph and UI (also based on Flamebearer) in the short term. and in the long term evolve our native Flamegraph panel to reach feature parity while fitting better into Grafana's ui architecture. this will involve significant rewrites to the internals in the next couple quarters, so it's best that this brush-zoom work is deferred until that is in a stable state.

this feature is still on our radar but it will have to follow the refactoring work to keep the workload manageable.

thanks, and stay tuned!

**Comment by chancez** [comment]
@leeoniya no worries, I just haven't had much time at work do external OSS contributions, and I figured this may be less relevant depending on how Grafana decides to integrate pyroscope. Thanks for the update.

**Comment by aocenas** [comment]
@chancez yeah sorry for not updating you on this. Still, though we would like to incorporate this somehow in the end, so if you don't mind I would keep this open, and also if you don't have time we can just take this over and continue working on this to iron out the edge cases.

**Pull request closed without merging**
