### PR TITLE
Alerting: Fix AM config overwrite when SQLite db is locked during sync

### PR DESCRIPTION
**Pull request by JacobsonMT**
**What this PR does / why we need it**:

If SQLite is used and the database is locked temporarily (ex. heavy write-load) during periodic
AM config sync, it was possible for your AM config to be overwritten with the default one.

This fixes that by patching a bug in xorm v0.8.2 which was causing SQLITE_BUSY errors to be ignored
in certain cases.

**Which issue(s) this PR fixes**:

Relates to (probably fixes): https://github.com/grafana/grafana/issues/43347
Relates to (might fix): https://github.com/grafana/grafana/issues/42957

**Special notes for your reviewer**:

xorm patch: https://github.com/grafana/xorm/commit/2fcda7565af6917bc400f26f21d9fc70bfccf07d

Waiting on https://github.com/grafana/grafana/pull/50867 for integration tests to run on CI.

### CODE REVIEW

**Review by gotjosh — APPROVED** [review]
LGTM

Great Job 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

**Comment by yuri-tceretian** [comment]
Please create (or refer to existing one in this PR) an issue to upgrade to the upstream Xorm and assign it to a backend team. Otherwise, we'll forget about it.

**Comment by JacobsonMT** [comment]
> Please create (or refer to existing one in this PR) an issue to upgrade to the upstream Xorm and assign it to a backend team. Otherwise, we'll forget about it.

I can't find an issue but I see an open discussion (created by a maintainer of xorm) here: https://github.com/grafana/grafana/discussions/48097

**Comment by yuri-tceretian** [comment]
> Should I convert to an issue for better visibility? 

I think this is worth it

**Comment by gotjosh** [comment]
@papagian are you tracking the upgrade of xorm anywhere?

**Pull request merged**
