### PR TITLE
Elasticsearch: Add support for template variable in date histogram min_doc_count

### LINKED ISSUE #21052: Elasticsearch histogram aggregations using template variable as min_doc_count
I have an issue where I need the user to choose the `min_doc_count` parameter in the `group by` terms aggregation for elasticsearch. However, this doesn't seem to work in 6.5.1, as the value `${my_min_doc_count}` input is discarded and replaced with `1` after hitting the `<tab>` key.

### PR DESCRIPTION
**Pull request by faxm0dem**
Fixes #21052

### CODE REVIEW

**Review by marefr — DISMISSED** [review]
LGTM

**Review by marefr — COMMENTED** [review]
@faxm0dem Are you aware of that your changes only adds support for using template variable in date histogram?

**Comment by faxm0dem** [comment]
Yes, that's where I needed it ;-)
Would you like me to change that in other histogram aggs?

**Comment by marefr** [comment]
@faxm0dem sorry for late reply. I think adding support for this in other aggs would be nice, but not sure if it's as straight forward as your current change. Reason it being a number is to enforce selecting a numeric value, but with templating/text that's gone so maybe need some additional validation?

**Comment by faxm0dem** [comment]
it might indeed, but that's beyond the scope of my involvement/js-skills :'(

**Comment by faxm0dem** [comment]
So this is going away down the drain?

**Comment by faxm0dem** [comment]
...

**Comment by faxm0dem** [comment]
As I said the contribution is as-is and the suggested change is beyond my competence

**Comment by faxm0dem** [comment]
Ok let's play bot-pong

**Comment by faxm0dem** [comment]
```


|

                      o
                                                  |

```

**Comment by faxm0dem** [comment]
```

                                                  |j
|
                             o
                      


```

**Comment by marefr** [comment]
Sorry, haven't had time to look into this. 7.0 release have taken all time. Can you please rebase/merge with master and I'll have a look at this. Thanks

```

                                                  
|

 o                                                 |
                      


```

**Comment by faxm0dem** [comment]
```



     GAME OVER



```

damned !

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana! I will open a new PR to resolve using variable for min doc count for terms and histogram aggs since I wasn't allowed to push to your fork/branch.

**Pull request merged**
