### PR TITLE
Update behind_proxy.md

### PR DESCRIPTION
**Pull request by ch-hristov**
**What this PR does / why we need it**: I spent a few days wondering why i couldn't embed grafana while using an inbound rule (without adding a reverse proxy rule) so it's definitely worth instructing people about it.

**Which issue(s) this PR fixes**: Missing clarity about ARR

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
Isn't this documented here? https://grafana.com/docs/tutorials/iis/#how-to-use-iis-with-url-rewrite-as-a-reverse-proxy-for-grafana-on-windows

**Comment by ch-hristov** [comment]
@marefr

> Isn't this documented here? https://grafana.com/docs/tutorials/iis/#how-to-use-iis-with-url-rewrite-as-a-reverse-proxy-for-grafana-on-windows

No, this only documents that you need Url Rewrite but it doesn't explain the extra step of adding ARR and adding a reverse proxy to the website.

**Review by torkelo — APPROVED** [review]

**Comment by torkelo** [comment]
need to sign CLA for us to merge

**Review by marefr — CHANGES_REQUESTED** [review]
> No, this only documents that the steps to set up Url Rewrite but it doesn't explain the extra step of adding ARR and adding a reverse proxy to the website.

As far as I can see the link you've added doesn't mention requirement of ARR in any of the 3 articles.  Doesn't ARR give you functionality for load balancing and such?

My suggestion is to update https://grafana.com/docs/tutorials/iis/#how-to-use-iis-with-url-rewrite-as-a-reverse-proxy-for-grafana-on-windows if there's something missing. Then add a link to this guide from `### IIS URL Rewrite Rule (Windows) with Subpath` in behind_proxy.md.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the PR if you provide more information.

**Pull request closed without merging**
