### PR TITLE
cloudwatch: Cache executor-related things by id

### PR DESCRIPTION
**Pull request by patstrom**
This commit introduces changes that simplifies the AWS caching by
keeping one executor per data source id that keeps all caches as struct
fields. This is in contrast to the pre-commit behavior where different
things were kept in different global caches with keys that tried to
limit them to a data source.
    
The pre-commit behavior might have worked out but there are definitely
places where the global cache could have returned a false-positive cache
hit (for example one data source using another data sources
credentials).
    
The Custom Metrics caches can probably be simplified since they would
only need to use region and namespace as key but this commit is simply a
refactor that tries to keep all current functionality.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is part 2 of the PRs to replace https://github.com/grafana/grafana/pull/23439 and is based on https://github.com/grafana/grafana/pull/25555

It is probably appropriate for @aknuds1 to review this

### CODE REVIEW

**Comment by patstrom** [comment]
@aknuds1

**Comment by patstrom** [comment]
Ah sorry the status is that I have been on vacation on currently have a full plate at work. I hope to get to this (and the other PRs) in a week or two.

**Comment by aknuds1** [comment]
Sorry, thought I had removed the stale label on this one. Now that @papagian is back from holiday, I think she and I will try to review your PRs together, since at least the auth scheme PR needs several pairs of eyes.

**Comment by patstrom** [comment]
Great! I'll try to update all the relevant PRs as soon as possible!

**Comment by aknuds1** [comment]
@patstrom There's no need to rush, we need to work through the PRs and develop an idea of what changes should be made and the effect they will have.

**Comment by patstrom** [comment]
Let me know if you have any questions or just want some clarifications about what I had in mind!

**Comment by aknuds1** [comment]
No worries, we will ask when we review and are unsure about anything.

**Comment by aknuds1** [comment]
Can you sync this PR with master? We're interested in implementing session caching, in order to enable [the PR](https://github.com/grafana/grafana/pull/25548) to re-design the CloudWatch auth scheme.

**Comment by patstrom** [comment]
So you've already implemented the sessions cache in that PR I'll wait with this until the new authentication is merged. Otherwise there will just be even more conflicts.

**Comment by aknuds1** [comment]
Yeah, probably best to wait as I produced what I hope is an adequate quick fix in the meantime.

**Pull request closed without merging**
