### PR TITLE
AccessControl: Add group to role picker and standardize display

### PR DESCRIPTION
**Pull request by Jguer**
**What is this feature?**

AccessControl: Add group to role picker and standardize display

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by IevaVasiljeva — COMMENTED** [review]
LGTM, but I think if we do this, we should rename the fixed roles that have the group in the display name. Eg, `Annotation Reader` -> `Reader` etc.

**Review by eleijonmarck — APPROVED** [review]
> LGTM, but I think if we do this, we should rename the fixed roles that have the group in the display name. Eg, Annotation Reader -> Reader etc.

Yea we should definitely rename the fixed role display names

**Review by IevaVasiljeva — APPROVED** [review]
Nice! We have more fixed roles defined in other places, but I guess we can clean them up in later PRs as and when we spot them.

**Review by gamab — APPROVED** [review]

**Pull request merged**
