### PR TITLE
Alerting: move fake stores to store package

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What this PR does / why we need it**:
Currently, all fake stores that we use in testing are package-private and are placed in `schedule` package. This makes them impossible to use in other packages. This PR moves all fake stores to `store` package and makes them public.
**Which issue(s) this PR fixes**:
Rel: https://github.com/grafana/grafana/pull/45072

### CODE REVIEW

**Review by alexweav — APPROVED** [review]
LGTM - I like this a lot.

I'm assuming the fakes were simply moved and additional methods were exported, but otherwise did not have substantial changes. So, I only gave the content of the `testing.go` files a quick API-level review. Let me know if this isn't the case.

**Comment by yuri-tceretian** [comment]
Correct, there are 0 changes other than making some structs, fields and methods start with capital letter.

**Comment by gotjosh** [comment]
It's important that big changes like this to the testing structure are backported - without them, it makes it really hard to keep backport PRs that re-use them equal.

**Comment by gotjosh** [comment]
I gave up, this is too far down the list of PRs we need to backport to make it salvageable.

**Pull request merged**
