### PR TITLE
update grafana/experimental dependency

### PR DESCRIPTION
**Pull request by gabor**
in https://github.com/grafana/grafana/pull/90328 we switched from `react-beautiful-dnd` to `@hello-pangea/dnd`. but we are still using it indirectly, because we use `@grafana/experimental` and it uses `react-beautiful-dnd`.

so we removed `react-beautiful-dnd` from `@grafana/experimental` too (https://github.com/grafana/grafana-experimental/pull/125), made a new release for `@grafana/experimental`, and now we'll use this new release here.

how to test:
based on some quick checks, the places that use the code that was changed in `@grafana/experimental` are in the loki query builder:
- https://github.com/grafana/grafana/blob/d3061ab61ad98513deb92d7abf0f07449427480b/public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx#L12
- https://github.com/grafana/grafana/blob/d3061ab61ad98513deb92d7abf0f07449427480b/public/app/plugins/datasource/loki/components/LokiQueryEditor.tsx#L9

i tried to drag&drop move a couple boxes in the loki query editor around, they seemed to work.

(NOTE: we need this to do https://github.com/grafana/grafana/pull/87741 )

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]
LGTM! Tested and works as expected.

**Comment by gabor** [comment]
> LGTM! Tested and works as expected.

sorry @ivanahuckova , could you please test it one more time? (there was a CI error with the package-version, i fixed it but would be great to test it one more time)

**Review by ivanahuckova — APPROVED** [review]
Still works!

**Comment by gabor** [comment]
it seems renovate-bot was faster :) https://github.com/grafana/grafana/pull/91067

**Pull request closed without merging**
