### PR TITLE
Performance: Code split login page

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

This PR adds more code splitting to Grafana routes to reduce the size of the initial bundle.

With both PRs combined we can see the following changes to initial chunk sizes:

|     | Before   |   After       |
| ---------- | -------- | -------- |
| Unminified | 21.8 MiB | 20.6 MiB |
| Minified   | 8.64 MiB | 8.17 MiB |

This is mostly due to removing the dependency "node-forge" from the initial chunks due to [the associated enterprise branch](https://github.com/grafana/grafana-enterprise/pull/7125)

**Why do we need this feature?**

To reduce the amount of unused javascript we load to boot the app.

**Who is this feature for?**

Everyone.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by tskarhed — APPROVED** [review]

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Pull request merged**
