### PR TITLE
Add onDataSourceChange to optional components

### PR DESCRIPTION
**Pull request by MasslessParticle**
Enterprise work on recorded queries requires components from to be able to control the main data source dropdown in the query editor. Recording expressions requires the editor to be in mixed mode so that all queries have the appropriate datasource information before they are recorded.

As part of this work, we also discovered a bug where a user could select `-- Mixed --` twice by typing it into the dropdown after selecting it. This caused all child queries to also be set as `-- Mixed --` and broke everything. We've fixed that issue in this PR by only accepting a change to the `-- Mixed --` datasource if the current datasource isn't already `-- Mixed --`.

### CODE REVIEW

**Comment by hugohaggmark** [comment]
I understand why you need this change, but I'm not sure if this is the best way to do this. @torkelo @ryantxu any thoughts on adding this extra prop?

**Review by hugohaggmark — COMMENTED** [review]
I understand why you need this change, but I'm not sure if this is the best way to do this. @torkelo @ryantxu any thoughts on adding this extra prop?

**Review by torkelo — COMMENTED** [review]
> Recording expressions requires the editor to be in mixed mode so that all queries have the appropriate datasource information before they are recorded.

Not sure I understand this either, if you always want mixed data source, why not skip the data source picker? (and have it only on the query level), like alerting ui

**Comment by MasslessParticle** [comment]
Ideally, this we shouldn't force `mixed` at all. It's a workaround -- for expressions specifically -- to ensure all query objects have their associated datasource name attached when they're sent to the Recorded Queries backend.

Is there a better way to achieve that goal?

**Pull request closed without merging**
