### PR TITLE
OpenAPI spec improvements

### PR DESCRIPTION
**Pull request by dhftah**

### CODE REVIEW

**Comment by dhftah** [comment]
hola lovely people; this is definitely not complete — its just API deltas that I discovered while trying to use grafana-openapi-client-go

**Comment by ryantxu** [comment]
@dhftah -- thanks!  the problem is that this file is auto-generated 😬 

Try running:
```
make swagger-clean && make openapi3-gen
```
I suspect we need to change/improve something in the autogenertated logic, not the final output

**Comment by ryantxu** [comment]
https://github.com/grafana/grafana/blob/main/pkg/api/README.md#openapi-generation

**Comment by ryantxu** [comment]
I'll close this one -- but please open a new PR if we can keep the auto-generted parts up-to-date

**Comment by pointerpower** [comment]
> Try running:
> 
> ```
> make swagger-clean && make openapi3-gen
> ```

@ryantxu Apologies for the noob question, I'm running into the same issue.  The fix you suggest above, do you mean building from grafana source and running the steps above?  

Will this eventually get fixed in one of the releases?

**Pull request closed without merging**
