### PR TITLE
Build: Streamline and sync dockerfiles

### LINKED ISSUE #58921: make build-docker-full* fails
**What happened**:
When trying to follow [Developer Guide](https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#build-a-docker-image) to build a docker image, building fails at:

```
$ make build-docker-full

...snip...

(re)installing /go/bin/wire-v0.5.0
go: downloading github.com/google/subcommands v1.0.1
go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b
generate code from .cue files
go generate ./pkg/plugins/plugindef
go: downloading github.com/grafana/codejen v0.0.2
go: downloading github.com/deepmap/oapi-codegen v1.10.1
go: downloading github.com/grafana/cuetsy v0.1.1
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading golang.org/x/mod v0.7.0
go: downloading github.com/labstack/echo/v4 v4.9.0
go: downloading github.com/labstack/gommon v0.3.1
go: downloading github.com/valyala/fasttemplate v1.2.1
/grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
make: *** [Makefile:69: gen-cue] Error 1
The command '/bin/sh -c make build-go' returned a non-zero code: 2
make: *** [Makefile:157: build-docker-full] Error 2
```

This issues affects tested branches/tags v9.3.0-beta1 and  main BUT current release branch v9.2.5 DOES NOT show this behavior and builds as expected.

**What you expected to happen**:

`make build-docker-full`  creates an image on every branch.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ git clone https://github.com/grafana/grafana.git
$ cd grafana
$ make build-docker-full
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.0-beta1 , v9.3.x, main
- Data source type & version: --
- OS Grafana is installed on: docker (20.10.21)
- User OS & Browser: Ubuntu, WSL2(Ubuntu) n.a.
- Grafana plugins: n.a.
- Others: n.a.

### PR DESCRIPTION
**Pull request by DanCech**
While working on #58005 I noticed many inconsistencies between our various dockerfiles as well as opportunities to streamline them.

This PR attempts to take the best parts of our various dockerfiles and align between alpine and ubuntu as well as between dev and packaging.  It also syncs and streamlines the custom dockerfiles.

- adds a header to the **2** main dockerfiles reminding devs that they need to be kept in sync
- optimizes the build containers for cacheability (separating dependencies from our code)
- combines `RUN` statements to reduce layer count
- standardizes multi-line `RUN` indentation
- combines and removes unneeded `COPY` statements
- uses `USER "$GF_UID"` across all images for maximum compatibility
- standardizes on `/tmp/grafana` for build & temp files
- standardizes on `ARG GF_GID="0"`
- removes unneeded apk/apt upgrade in custom dockerfiles
- switches from gdebi to apt-get for chrome installation

After the dockerfiles were in sync I observed that the differences between alpine and ubuntu dockerfiles were relatively small and isolated to the RUN commands and underlying images, so by updating the RUN commands to detect alpine or ubuntu and updating the build scripts to pass the correct images as build args we can consolidate to 2 docker images.

In a follow-up PR we should be able to use buildkit to combine the main and packaging dockerfiles into a single dockerfile that detects whether a tarball is provided and either extracts that or builds the source.

### CODE REVIEW

**Comment by zuchka** [comment]
this PR potentially fixes #58921

**Review by kminehart — APPROVED** [review]

**Comment by mpeaton-ng** [comment]
This does build cleanly for me, less some minor mods for injecting ca-certifcates.  However it failes at runtime:
`/run.sh: line 80: exec: grafana-server: not found`

**Comment by DanCech** [comment]
> This does build cleanly for me, less some minor mods for injecting ca-certifcates. However it failes at runtime: `/run.sh: line 80: exec: grafana-server: not found`

Hmm, might be an issue with the `PATH` changes, thanks for the feedback I'll check it out.

**Comment by DanCech** [comment]
> > This does build cleanly for me, less some minor mods for injecting ca-certifcates. However it failes at runtime: `/run.sh: line 80: exec: grafana-server: not found`
> 
> Hmm, might be an issue with the `PATH` changes, thanks for the feedback I'll check it out.

I haven't been able to duplicate the problem, test images built using all 4 of these methods work as expected:
```
make build-docker-full
make build-docker-full-ubuntu
GRAFANA_TGZ=grafana-9.2.3.linux-amd64.tar.gz ./build.sh --fast 9.2.3
GRAFANA_TGZ=grafana-9.2.3.linux-amd64.tar.gz ./build.sh --fast --ubuntu 9.2.3
```

You mentioned mods to inject ca-certificates, did you possibly do something that would change the PATH setting?

We set the path to `ENV PATH="/usr/share/grafana/bin:$PATH"` which is what allors run.sh to find the grfana-server binary without an explicit path being specified, so if the PATH does not include /usr/share/grafana/bin it won't work.

**Comment by mpeaton-ng** [comment]
I did not.
I did, however, what I believe to be a working patch to main in the comments on make build-docker-full* fails · Issue #58921 · grafana/grafana (github.com)<https://github.com/grafana/grafana/issues/58921>.

From: Dan Cech ***@***.***>
Sent: Sunday, November 20, 2022 5:08 PM
To: grafana/grafana ***@***.***>
Cc: Eaton, Michael [US] (DS) ***@***.***>; Comment ***@***.***>
Subject: EXT :Re: [grafana/grafana] Build: Streamline and sync dockerfiles (PR #58101)


This does build cleanly for me, less some minor mods for injecting ca-certifcates. However it failes at runtime: /run.sh: line 80: exec: grafana-server: not found

Hmm, might be an issue with the PATH changes, thanks for the feedback I'll check it out.

I haven't been able to duplicate the problem, test images built using all 4 of these methods work as expected:

make build-docker-full

make build-docker-full-ubuntu

GRAFANA_TGZ=grafana-9.2.3.linux-amd64.tar.gz ./build.sh --fast 9.2.3

GRAFANA_TGZ=grafana-9.2.3.linux-amd64.tar.gz ./build.sh --fast --ubuntu 9.2.3

You mentioned mods to inject ca-certificates, did you possibly do something that would change the PATH setting?

We set the path to ENV PATH="/usr/share/grafana/bin:$PATH" which is what allors run.sh to find the grfana-server binary without an explicit path being specified, so if the PATH does not include /usr/share/grafana/bin it won't work.

**Comment by DanCech** [comment]
> I did not. I did, however, what I believe to be a working patch to main in the comments on make build-docker-full* fails · Issue #58921 

That should not be required with this branch, it includes an update that fixes the problem that patch was trying to solve.

**Comment by DanCech** [comment]
I did some more investigation here and found that the `/run.sh: line 80: exec: grafana-server: not found` error occurs when trying to run binaries compiled against glibc on an alpine image without the glibc libraries installed.  We work around this in the packaging Dockerfile by installing the glibc compatibility libraries.  For the full docker build it isn't an issue because we only compile grafana against glibc for the ubuntu image, the alpine version is built against musl.

@mpeaton-ng can you please provide more detail on exactly what you did to produce an image that fails with that error?

**Comment by grongor** [comment]
Hi! I might be wrong, but shouldn't there be a semicolon before the backslash? https://github.com/grafana/grafana/pull/58101/files#diff-dfdb3f200d18eadfb7dca9193b67c2b8b5c8e59472317372b14bb9f3ad1fe04fR15

```shell
if [ $GF_INSTALL_IMAGE_RENDERER_PLUGIN = "true" ]; then \
  apk add --no-cache udev ttf-opensans chromium \
fi
```
->
```shell
if [ $GF_INSTALL_IMAGE_RENDERER_PLUGIN = "true" ]; then \
  apk add --no-cache udev ttf-opensans chromium ; \
fi
```

**Comment by DanCech** [comment]
you're absolutely correct, I'll open a PR to fix that!

**Pull request merged**
