### PR TITLE
Update Prettier checks to parse also JSON files

### PR DESCRIPTION
**Pull request by fabrizio-grafana**
Currently, JSON files are not check by Prettier. This has caused some PRs proposing opposing changes to files such as `package.json` and `tsconfig.json`. For example, since commas are optional before closing brackets, it happened to have a PR that was proposing to add them, and some time later to have a new PR proposing to revert the changes. In both cases, the CI checks passed because JSON files are excluded when running Prettier. 

This PR proposes to include also JSON files when running Prettier, making the CI failing accordingly. Example:
image
Screenshot 2024-02-07 at 09 48 17

The PR also updates all JSON files by running `prettier:fix` to make the `lint-frontend` check pass even after then proposed changes.

### CODE REVIEW

**Review by gabor — APPROVED** [review]
👍 nice.  (the sql part is fine)

**Comment by ashharrison90** [comment]
@joshhunt @L-M-K-B will this conflict with crowdin at all? 🤔

**Review by matyax — APPROVED** [review]
<3

**Review by aangelisc — APPROVED** [review]

**Comment by fabrizio-grafana** [comment]
> @joshhunt @L-M-K-B will this conflict with crowdin at all? 🤔

@ashharrison90 do you think we can merge this PR anyway for the moment, and potentially revert it in the future if we notice it can cause problems?

**Comment by ashharrison90** [comment]
@fabrizio-grafana lemme ping them in slack... the problem is we have json files that periodically get pulled from crowdin that almost certainly won't have been prettified 😬

**Comment by fabrizio-grafana** [comment]
Yeah good point. Let's double check on Slack!

**Review by joshhunt — APPROVED** [review]

**Review by ashharrison90 — APPROVED** [review]
lgtm 🚀

**Pull request merged**
