### PR TITLE
Search: Check whether re-indexing required

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

In order to avoid rather expensive re-indexing, here is an attempt to avoid it by comparing data in database with data in index. For best case scenario this mostly reduces time to loading dashboards from DB, with extra milliseconds to do the comparison.

### CODE REVIEW

**Comment by FZambia** [comment]
The only real problem I found with this approach is that in Enterprise we are appending extra information to the index, so if re-indexing based on steps here won't happen - then Enterprise data won't be updated. Think it's possible to add some code to re-index more rarely than now – but is it worth it?

**Comment by ryantxu** [comment]
I like this approach -- for enterprise, I think we should either:
1. explicitly reindex after stats are updated (infrequently)
2. add something to the entity table that will trigger a full reindex (async)

**Comment by FZambia** [comment]
Yep, so changing how enterprise extension work is first step here.

**Comment by FZambia** [comment]
Closing in favour of https://github.com/grafana/grafana/pull/52807

**Pull request closed without merging**
