### PR TITLE
AsyncSegment: Fetch options based on user input

### LINKED ISSUE #21005: Grafana-ui: SegmentAsync remote typeahead
The contract for `SegementAsync` includes a `query` param however I don't think it's supplied anywhere. https://github.com/grafana/grafana/blob/7d6bd78e0b592bcb9e9904a3f222953655019903/packages/grafana-ui/src/components/Segment/SegmentAsync.tsx#L10

Would love to be able to use this for async-typeahead in the case where there are too many results to fetch for the dropdown.

### PR DESCRIPTION
**Pull request by Willena**
**What this PR does / why we need it**:

The signature of the loadOptions props is ` loadOptions: (query?: string) => Promise<Array<SelectableValue<T>>>; `
At the moment, we have no feedback on what the user typed in the "search" input. Having this feedback is important so that options can be fetched based on the user input. In the current version of Grafana, the method is called but with an always `undefined` query. 
This PR improves the AsyncSegment and the AsyncSelect components so that options can be updated based on what the user typed in the search field.

**Which issue(s) this PR fixes**: 

Fixes #21005

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
> The signature of the loadOptions props is loadOptions: (query?: string) => Promise<Array<SelectableValue<T>>>;
At the moment, we have no feedback on what the user typed in the "search" input. 

That id what the query parameter is for

**Comment by Willena** [comment]
As stated in the linked issue,  the query parameters was intended to be used for filtering options based on user input, but never fully implemented. I implemented it as I needed this feature in a custom data source plugin where I can't load all options at start (I would end up with more than 100 000 options otherwise, and it is a bit too much for the browser)

**Comment by torkelo** [comment]
Can you use AsyncSelect directly? Not sure what the future is for Segment components

**Comment by Willena** [comment]
Yeah of course. This is what i've used before using Segments. I saw that Segments were used in the elasticsearch datasource and thought they have a better look in the QueryEditor. 

> Not sure what the future is for Segment components

Does this means they are deprecated components and should not be used anymore ?

**Comment by torkelo** [comment]
@sunker can you take a look at this? Not sure. I thought this was possible already

**Comment by sunker** [comment]
This was not possible to do before this PR. 

The segment components are a bit weird. We're replacing them with regular select components in all the cloud data sources. Do you think we'll be deprecating them anytime soon @torkelo? Is it worth adding new capabilities to it? If so, can you please rebase the main branch and also add an example to storybook @Willena?

**Comment by Willena** [comment]
>
>  If so, can you please rebase the main branch and also add an example to storybook @Willena?

I'll do that once we have @torkelo answer about the deprecation (or not) of segment components and if it is worth to spend time updating them. I'll update the PR to resolve conflicting files and update with main, once things would have been clarified.

**Comment by torkelo** [comment]
> The segment components are a bit weird. We're replacing them with regular select components 

If that is the case then maybe it's better to deprecate them

**Comment by Willena** [comment]
Should I close this PR then ?

**Comment by torkelo** [comment]
yes, let's close this. We will soon be working on new components and designs for query editors

**Pull request closed without merging**
