### PR TITLE
Tempo: Fix search table duration unit

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

It's a bug fix.

**Why do we need this feature?**

Fixes issue where the search results table in Tempo was incorrectly formatting the duration col values.

**Who is this feature for?**

Tempo users who search for traces

**Which issue(s) does this PR fix?**:

No issue created.

**Special notes for your reviewer**:

Before

Screenshot 2022-11-11 at 12 23 16

After

Screenshot 2022-11-11 at 12 22 11

### CODE REVIEW

**Review by aocenas — APPROVED** [review]

**Comment by oysstr** [comment]
Why was this not merged? 
This is still an issue in 9.3.0

**Comment by oysstr** [comment]
This is how it looks for me: 
image

**Comment by oysstr** [comment]
I am not up-to-date on the merge/release process of Grafana, but the tag v9.3.0 is still `ns`; 
https://github.com/grafana/grafana/blob/v9.3.0/public/app/plugins/datasource/tempo/resultTransformer.ts#L580

**Comment by oysstr** [comment]
Main branch have this patch though, so I guess it will be part of the next patch-release.

**Pull request closed without merging**
