### PR TITLE
Prometheus: Change alignment of range queries to end before now and not in future

### LINKED ISSUE #13419: Current values shows 0 for Prometheus with 5.x Grafana
Please include this information:
### What Grafana version are you using?
`Grafana v5.2.4 (0bbac5c)`
### What datasource are you using?
`Prometheus`
### What OS are you running grafana on?
Ubuntu 16.04 + Docker official image
### What did you do?
Load Dashboard, with `current` value enabled for graph. 
### What was the expected result?
See current value, as it was with 4.x Grafana
### What happened instead?
I see all values as 0, but as far as I can see, several reload can give 0 or something in between or even correct value. 
screen shot 2018-09-25 at 8 45 10 pm

### LINKED ISSUE #15385: Prometheus step alignment issue
### What Grafana version are you using?

6 beta 1

### What datasource are you using?

prometheus

### What did you do?

loog at graph

inco

Last range is partly in the future so we have the impression the rate drops

### What was the expected result?

I should see a warning that the range is partly in the future:

inco2

### PR DESCRIPTION
**Pull request by davkal**
-  future alignment caused issues with rate charts and the display of last
values
- this change modifies the alignment to use the last available aligned
end date and no longer possibly requests data from the future

Fixes #15385 
Fixes #13419 (although if the step is too big and the data too recent, this can't be made to work)

### CODE REVIEW

**Comment by bergquist** [comment]
```bash 
make build-docker-full
``` 
if you want to try this without installing all deps

**Comment by bergquist** [comment]
The gap is small enough that I dont care. 

LGTM :+1: 

master
image

this pr

image

**Comment by beorn7** [comment]
Thanks 1M!

**Comment by roidelapluie** [comment]
I have deployed it. It is cool!

**Comment by husoule** [comment]
Why does my grafana still showing future data? grafana:v7.1.2
image
image

**Comment by husoule** [comment]
> * future alignment caused issues with rate charts and the display of last
>   values
> * this change modifies the alignment to use the last available aligned
>   end date and no longer possibly requests data from the future
> 
> Fixes #15385
> Fixes #13419 (although if the step is too big and the data too recent, this can't be made to work)

Why does my grafana still showing future data? grafana:v7.1.2
image
and now is: 
image

**Pull request merged**
