### PR TITLE
added span with folder title that is shown for recently and starred

### LINKED ISSUE #11056: [Feat] Include folder name in recently viewed dashboard list
Using Grafana 5.0 (actually a slightly earlier version) built from source
Using MetricTank as the data source.

We have hundreds of folders and over 1,000 dashboards.  Teams clone the dashboard and can save it without renaming it.  Therefore the dashboard may exist twice (just by name).

Please have in the auto-complete search for dashboards by name to prefix with the directory, e.g.

my_dir/scott_dashboard
your_dir/scott_dashboard

### PR DESCRIPTION
**Pull request by Ijin08**
created a new class for folder title

fixes #11056

skarmavbild 2018-09-11 kl 15 22 56

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Quick feedback/thoughts. Shouldn't General folder be shown as well to be consistent?

Would it be better to have the folder title to the left of the dashboard title - maybe easier for eyes first spotting which folder and then dashboard. Not sure, a UX discussion.

**Comment by davkal** [comment]
> Would it be better to have the folder title to the left of the dashboard title - maybe easier for eyes first spotting which folder and then dashboard.

Folder first would be consistent with how it's displayed on the dashboard page. And it's nicely readable for a single item.

A larger question is, what’s more important? The folder or the dashboard title.
I’m bringing this up because of scanability issues due to ragged edges. If my mental reference to what I’m looking for is the dashboard title, I’ll have a harder time finding it scanning down the list while the varying folder titles are messing up the left alignment of the dashboard titles. A special usecase could be comparing dashboards of the same title that are in different folders: here again they would be grouped better by dashboard title first.
N.b. the reverse case exists too: scanning for all recent dashboards of a certain folder, although the user could rely on memory of the dashboard titles there too, as they are probably more engrained than folder titles in the first place.

**Comment by Ijin08** [comment]
Placing folder title under or over dashboard title:

search-folder-under

search-folder-over

**Comment by torkelo** [comment]
Below is best I think, and we would need to reduce padding to align height so it's not higher than other rows.

image

**Comment by Ijin08** [comment]
skarmavbild 2018-09-11 kl 13 37 34

**Comment by Ijin08** [comment]
Updated pr and placed folder under dashboard keeping the same height as other items.
Thoughts? @davkal @torkelo

**Comment by marefr** [comment]
So should we merge this or are we waiting for something?

**Pull request merged**
