### PR TITLE
Fix for deprecating packages

### PR DESCRIPTION
**Pull request by srclosson**
Not sure why it was ever expected that the previous version would work... 
This one is simpler and will do the trick. If unpublish fails, deprecate. If deprecate fails, fail the build.

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
Do you mind adding `set -eo pipefail` at the beginning of the script, so it will exit if any step fails? Should help in catching errors from my experience.

CI also fails in front-end tests for some reason.

**Comment by srclosson** [comment]
done

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
> done

Thanks!

**Review by ryantxu — APPROVED** [review]

**Review by dprokop — APPROVED** [review]

**Pull request merged**
