### PR TITLE
Auth: Add key_id config param to auth.jwt

### LINKED ISSUE #71665: JWT Auth failing due to missing Key Id in keySet code structure when loading signing public key from PEM file
### What happened?

Grafana supports user authentication using JWT coming in inbound request in HTTP header. For any application that accepts JWT as user's identity, it must validate the JWT signature before reading claims in that JWT. To validate that JWT, it requires the public key used to sign that JWT. 

In this case, Heracles authenticates the user and calls Secure Access to get the JWT before sending that JWT to backend application. Secure Access signs the token using Token-Signing private key. Grafana will need that Token-Signing public key to validate the JWT signature once it receives from Heracles.

As per Grafana documentation, the public key can be loaded in 3 different ways:

    1. Load JSON Web Key Set (JWKS) with public keys by calling Token provider's URL.
        a. This does not work in our case, as the Token-provider which is Secure Access is exposing its URL in a MTLS connection, so it is expecting Grafana to send a client certificate.
        b. Grafana does not support MTLS for this particular connection, as this connection as per industry standards it must be a well-known public (one way TLS - HTTPS) URL.
        c. Even if Grafana supports MTLS connection, the way Secure Access is generating its public key set is not an industry standard.

    3. Load JSON Web Key Set (JWKS) with public keys from the local filesystem.
        a. We can get the Secure Access keys from Secure Access URL and copy those into a JWKS.json file and load it from the local filesystem. But this did not work because of a special character that cannot be decoded by GoLang's x509 crypto package. @Visam, Venkatesh updated that package and rebuilt it to accept that special character while decoding and it was tested, and it was good.
        b. But this package is not owned by Grafana. It's from core GoLang that Google owns.
        c. So, we may not get support from Grafana to make those changes.

    4. Load JWT Signing public key from a PEM file from the local filesystem.
        a. As we only have one token signing cert, we were able to get the public key from that cert, create a PEM file and load it into Grafana. But it failed during testing with an error "Invalid JWT, no keys found"
        b. After going through their code on Friday, I understood how they are loading that key from PEM file:
            i. This is the block of code where they were able to parse the PEM file and load the key into memory:

            ii.             s.keySet = &keySetJWKS{
                                  jose.JSONWebKeySet{
                                        Keys: []jose.JSONWebKey{{Key: key}},
                                  },
                            }

            iii. This is the struct they are mapping that key to: jose package - gopkg.in/square/go-jose.v2 - Go Packages
            iv. As you can see, they are mapping the "Key", but not the "KeyID"
            v. When Grafana receive JWT in inbound request, they are trying to find the Key in memory using the "kid" field in JWT header. 

            vi.       keys, err := s.keySet.Key(ctx, token.Headers[0].KeyID)
                      if err != nil {
                            return nil, err
                      }
                      if len(keys) == 0 {
                            return nil, errors.New("no keys found")
                      }

            vii. But, as they haven't set the "KeyID" during step ii in above code, they will not find the key to use to validate that JWT, so they are throwing that error.
        c. I changed their code to insert KeyID into that struct with static string of keyID.

            i.                  s.keySet = &keySetJWKS{
                                        jose.JSONWebKeySet{
                                                Keys: []jose.JSONWebKey{{Key: key, KeyID: "88773-API_Enablement_Synapse_PDP"}},
                                        },
                                }

        d. rebuilt the app and tested user authentication with JWT coming from Heracles and I can see SSO worked:

            i. INFO [07-11|08:15:28] Request Completed  logger=context userId=2 orgId=1 uname=e048689 method=GET path=/api/live/ws status=400 remote_addr=10.157.244.22 time_ms=5 duration=5.237465ms size=12 referer= handler=/api/live/ws

        e. This should be under Grafana's control as it's their own code. So, if they can fix it, probably by getting that KeyID from the config, we can make use of it.

### What did you expect to happen?

The JWT signature to be validated

### Did this work before?

no

### How do we reproduce it?

as described above

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 9.5.3
OS: Oracle Linux
Browser:

### Grafana platform?

A downloaded binary

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by mgyongyosi**
**What is this feature?**
This PR adds a new configuration option to `auth.jwt` to specify a predefined key id (`key_id`) for the public key when the public key is configured as a PEM formatted file (using the `key_file` configuration option).

**Why do we need this feature?**

It is possible (and supported by Grafana) to use a PEM formatted public key instead of the recommended JWKS url/file, and it can happen that the JWT token's header contains a `kid` for specifying the key id that should be used to verify the signature. Previously when the `kid` was specified the verification failed, because the key with the specified key id was not found.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #71665

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by linoman — APPROVED** [review]
Looks pretty good! Shouldn't we update `default.ini` and `sample.ini`?

**Comment by mgyongyosi** [comment]
> Looks pretty good! Shouldn't we update `default.ini` and `sample.ini`?

Thanks, I updated defaults.ini, but forgot to update sample.ini, I'm gonna update it!

**Review by Jguer — APPROVED** [review]

**Review by Jguer — APPROVED** [review]

**Review by IevaVasiljeva — APPROVED** [review]
LGTM, and thanks for remembering to extend the docs!

**Review by chri2547 — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
