### PR TITLE
cloudwatch: Add templating query tg_to_alb()

### PR DESCRIPTION
**Pull request by rickard-von-essen**
When getting metrics for a TargetGroup (TG) most of these metrics are collected on the ALB which the TG is connected to (e.g. `HTTPCode_Target_2XX_Count`). To filter out such a metric the AWS CloudWatch API requires that you provide dimensions for both `TargetGroup` and `LoadBalancer`.

This PR adds a templating query function `tg_to_alb(region, names...)` which will return the ALB dimensions for the (`names`) TG's in `region`. Or all ALB's connected to TG's in that region.

Examples:
```
tg_to_alb(,service-a) => [app/my-alb-1/4234234234]
tg_to_alb(,service-a,service-b,service-c) => [app/my-alb-1/4234234234,app/my-alb-2/2111111]
tg_to_alb(eu-west-1,) => [list of all ALB's connected to TG's in eu-west-1]
tg_to_alb(,) => [list of all ALB's connected to TG's in default region]
```

### CODE REVIEW

**Comment by bergquist** [comment]
This will have to wait until https://github.com/grafana/grafana/pull/8050 is merged.

**Comment by rickard-von-essen** [comment]
~Rebased~Rewritten on top of #8050 (bad timing).

**Comment by torkelo** [comment]
the syntax of empty arguments seems unintuitive and clunky is there another approach?

**Comment by rickard-von-essen** [comment]
I tried to mimic the other cloudwatch variables.

Is it `tg_to_alb(,)` you whink is akward, I guess we could also allow `tg_to_alb()`. But what you really want in practice is `tg_to_alb(, <target_group>)` for exactly on TG so you can filter a CW metric on dimension `LoadBalancer = <alb>, TargetGroup = <targetgroup>`.

**Comment by rickard-von-essen** [comment]
> the syntax of empty arguments seems unintuitive and clunky is there another approach?

This syntax tries to follow the other templating query function for CloudWatch and the underlying AWS API for `DescribeTargetGroups`.

Any suggestions to move this forward?

**Comment by bergquist** [comment]
@rickard-von-essen Sorry for the slow response. 

I think this is ok considering the current code format. Any chance you could rebase this onto master? I'll babysit this PR and merge it once its been rebased.

**Comment by torkelo** [comment]
closing this, as there has been no rebase in ~1month, we can reopen it again.

**Comment by rickard-von-essen** [comment]
I'll get back to this eventually, but it might take some more time before I
get to it on my list.

**Pull request closed without merging**
