### PR TITLE
Improve dashboard grid layout migration WIP

### LINKED ISSUE #9888: [v5]: Improve dashboard grid migration
Migration code: 
https://github.com/grafana/grafana/blob/develop/public/app/features/dashboard/dashboard_model.ts#L915

- When importing some dashboards the current migration has some issues. For example import this dashborad http://play.grafana.org/dashboard/db/alerting?orgId=1  and see that the first row & panel get the height wrong. 

New grid system works like this, each panels is in a single array on the dashboard model. Each panel has a gridPos {x, y, w, h} these are in grid dimensions (width is 24 columns wide). 

- Try the schema migration for many dashboards and identify issues and fix or improve the migration (might need to look at panel height as well). Ignore dashboards with panel/row repeats for now. 

- Currently rows are ignored (or all rows are merged), need to detect if rows are used in the dashboard we import. And by used I mean if the row title is shown or if a row is collapsed. If either of those is true then add "row" panels to the dashboard.panels array.

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR closes #9888
WIP

### CODE REVIEW

**Comment by torkelo** [comment]
I think we should move the schema upgrade logic to a seperate file as the dashboard_model seems to be getting large and this seems like an isolated concern

**Comment by alexanderzobnin** [comment]
Yes, agree.

**Comment by torkelo** [comment]
remember to add a few tests for the migration code (and move the current migration tests from dashboard_model.jest.ts) 
https://github.com/grafana/grafana/blob/develop/public/app/features/dashboard/specs/dashboard_model.jest.ts#L87

It's also worth testing writing a failing test for a migration scenario before you solve it :)

**Comment by torkelo** [comment]
the karma tests are failing with some strange error

**Comment by torkelo** [comment]
let me know if you think this is ready to be merged into develop

**Comment by alexanderzobnin** [comment]
Ok, I'm still finding new test cases.

**Comment by alexanderzobnin** [comment]
I think it's ready to merge.

**Pull request merged**
