### PR TITLE
Chore: Convert CloudWatch metrics to data frames

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Convert CloudWatch metrics queries to return data frames.

Implemented for both back-end and front-end.

### CODE REVIEW

**Comment by aknuds1** [comment]
@kaydelaney Will you be taking care of the front-end duties of this PR?

**Comment by hugohaggmark** [comment]
Not very familiar with this data source so I'm assigning @kaydelaney as reviewer.

**Comment by torkelo** [comment]
@ryantxu is there more needed to expose cloudwatch from the new tsdb api backend api and switch frontend data source to extend DataSourceWithBackend ?

**Comment by aknuds1** [comment]
> @ryantxu is there more needed to expose cloudwatch from the new tsdb api backend api and switch frontend data source to extend DataSourceWithBackend ?

@ryantxu Ping.

**Comment by ryantxu** [comment]
In an ideal world, things that support DataFrames can have the most basic fronted and simply extend [DataSourceWithBackend](https://github.com/grafana/google-sheets-datasource/blob/master/src/DataSource.ts#L6)

This looks like it does a bit more -- that is OK, but requires someone who knows that to validate.  Who is working on the frontend side of this?

**Comment by aknuds1** [comment]
@ryantxu I only know that @kaydelaney handled frontend duties on this PR. Really not sure if there's anyone else who knows it better!

**Comment by aknuds1** [comment]
@torkelo Do you know who can review the front-end part, so we can finish up the PR?

**Review by ryantxu — APPROVED** [review]
Code looks fine to me -- I do not have enough context with cloudwatch to know if it is still behaving as expected though, so maybe get a final signoff from @kaydelaney ?

We should also revist the frontend datasource implementaiton and see if we can extend DataSourceWithBackend to simplify as much as possible

**Comment by aknuds1** [comment]
I'm going to test this before eventually merging.

**Comment by aknuds1** [comment]
From testing this, I'd say it works.

**Pull request merged**
