### PR TITLE
LibraryPanels: Separates name from panel title

### LINKED ISSUE #35518: LibraryPanels: Make library panel title separate from panel title
Users many times want to have panels without title, especially for text panels and some times for stat panels. Think of a text panel with a logo or some links. The current library panels enforce that library panels have the same title as the panel title.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Separates the library panel name from the library panel title.

| **Before** |  **After** |
:-----------:|:----------:
|image|image

**Which issue(s) this PR fixes**:
Fixes #35518

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks great! 

Some ux feedback: 
Can we have the Name first (feel more important), and then have `Library panel information` second? and would rename the label for `Library panel information` to something like just `Information` 
The bottom spacing for libary panel info seems higher than the spacing between two options

**Comment by hugohaggmark** [comment]
Wow, that was fast, this is currently not working but great feedback!

**Comment by hugohaggmark** [comment]
Trying to wrap my head around the UX, I find it super confusing that we're both updating/saving the library panel and changing the title (panel) in the same edit view. How do I know as a user when I'm changing the library panel and when I'm changing the panel on the dashboard?

I think we need to rethink this.

**Comment by hugohaggmark** [comment]
@ying-jeanne @idafurjes let me know if anything is unclear. I don't think this change will affect the cue schema, but feel free to correct me if I'm wrong.

**Comment by hugohaggmark** [comment]
Fixed an issue when creating a library panel, thanks @oscarkilhed for finding it 🎉

**Review by oscarkilhed — APPROVED** [review]
Looks good!

**Pull request merged**
