### PR TITLE
Tempo: Prevent text to be replaced by autocompletion

### LINKED ISSUE #74021: Accepting a suggestion just before a value replaces such value
For instance, if we have `{.foo = 300}` as in the image
image
and we accept one of the suggestions when the cursor is exactly before `300`, the `300` gets replaced:
image

This behavior seems to be due to these piece of code:
image

### PR DESCRIPTION
**Pull request by harrymaurya05**
Which issue(s) does this PR fix?:
prevent text got replaced by autocomplete

Fixes https://github.com/grafana/grafana/issues/74021

https://github.com/grafana/grafana/assets/22474692/3fffc839-0150-430b-a622-04e4c77f2f9e

### CODE REVIEW

**Comment by harrymaurya05** [comment]
@fabrizio-grafana 
Please Review!

**Comment by fabrizio-grafana** [comment]
Thanks for the PR! I'll add it to the squad's review list.

**Review by fabrizio-grafana — COMMENTED** [review]
Hey @harrymaurya05 👋 Sorry for the delay, I got stuck with other tasks, but thanks for taking care of this! 

Are you able to reproduce the bug when your fix is not applied? I'm not, and I suspect it might be because we removed the `+1` ([see image attached in the issue](https://private-user-images.githubusercontent.com/135109076/264053670-69372209-3bd6-40ef-9477-7f20deea92df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDU5MzcsIm5iZiI6MTcwODYwNTYzNywicGF0aCI6Ii8xMzUxMDkwNzYvMjY0MDUzNjcwLTY5MzcyMjA5LTNiZDYtNDBlZi05NDc3LTdmMjBkZWVhOTJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMjQwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODQyZWQzMDY0MDU4MjhmNTNjNDUzNzgyMjg2YmIyMmFhNTc1MzhlYTY2MWYxZWYzOTA3YjZkMTU5NjFlZDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TRluiEM5sINvv4A7FdVSUzk1lxO92VlnaqZ_RH2zWQ8)) at the line you are also changing. Maybe that was enough to fix the issue. Let me know if you can reproduce the bug, which would confirm we still need the fix. 

In any case, thanks to your contribution, we now know exactly what was the problematic line of code, so thank you!

**Comment by harrymaurya05** [comment]
@fabrizio-grafana 
Hi yes i am able to reproduce the issue on main branch.
Current branch is main
Screenshot 2024-02-22 at 7 39 12 PM


https://github.com/grafana/grafana/assets/22474692/f7361aa9-841d-4753-a2e4-2d809f4ff969

**Comment by fabrizio-grafana** [comment]
The fix seems to work for what concern the addressed issue 🚀 
I'm just not sure that we want all calls of `getRangeAndOffset` to be affected. That is a generic function intended to be use to get the correct range and offset, so maybe the called might be puzzled by the fact that the end column is actually the start column 🤔 
I'll think more about this. I'm leaving this open for now, but we can consider the issue as fixed, so thanks for taking care of it @harrymaurya05!

**Comment by fabrizio-grafana** [comment]
Closing for now while waiting to investigate the issue and source code better.

**Pull request closed without merging**
