### PR TITLE
Loki: Fix code editor not correctly responding to window resize

### PR DESCRIPTION
**Pull request by itsgareth**
**What is this feature?**
fixed a bug where the code editor does not correctly resize.

**Why do we need this feature?**
...

**Who is this feature for?**
...

**Which issue(s) does this PR fix?**:
Fixes #

**Special notes for your reviewer**:
Before:
https://user-images.githubusercontent.com/34524710/210841581-a0841891-a6c3-4993-8330-a1d43866aeb7.mov

After:
https://user-images.githubusercontent.com/34524710/210841636-1554a06b-b8c1-4873-89c4-0171774c124e.mov

### CODE REVIEW

**Review by svennergr — APPROVED** [review]
Spongebob Many Thumbs

Feel free to backport as a bugfix.

**Comment by gwdawson** [comment]
> Feel free to backport as a bugfix.

@svennergr no backport necessary, i cant reproduce on any older version, just on main

**Review by matyax — CHANGES_REQUESTED** [review]
I think the source of the bug is https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/components/monaco-query-field/MonacoQueryField.tsx#L180

Please wait till I check something.

**Comment by matyax** [comment]
Confirmed that the bug comes from that. With this we're adding a patch but not fixing the original trouble.

**Comment by matyax** [comment]
So, the problem I had with all this is that `updateElementHeight()` was supposed to update the element height, but it is actually setting both values, and there is no workaround for that as it's required. I'll take note to update that to be more accurate. Thanks @gwdawson !

**Review by matyax — APPROVED** [review]
Great work!

**Pull request merged**
