### PR TITLE
Makes the singlestat threshold to scale based on the Unit selected

### PR DESCRIPTION
**Pull request by thuck**
This should help with the request #8679
There is two possibilities; the first one implemented here do not include the Unit in front of the thresholds on the gauge:
Imgur

The second one is basically the same thing, but with the Unit in front of the thresholds (small update necessary):
Imgur

@torkelo which one would you prefer?

### CODE REVIEW

**Comment by torkelo** [comment]
tricky, first on looks better but wont work if the thresholds have different magnitude (say 10ms, 1 second, 2m)

**Comment by thuck** [comment]
So I guess for now we should use the second option, and maybe in the future another idea comes up to improve this.

**Comment by torkelo** [comment]
unsure about this PR, will break some existing usage. Not sure what the right solution is. Hate to add a new option.

**Comment by thuck** [comment]
Do you prefer to postpone this until we find a better solution?
The only thing for me is that the way that the values are displayed today it's not useful for anything that doesn't fit the 0-100% scale. It gets mashed very easily.

**Comment by torkelo** [comment]
closing this for now until we find a better solution

**Pull request closed without merging**
