### PR TITLE
Docs: add `Provisioning` section to `Install on Kubernetes` docs

### PR DESCRIPTION
**Pull request by ppcano**
This PR adds a **Provision Grafana resources using configuration files** section to the [Install Grafana on Kubernetes docs](https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/). 

It provides step-by-step instructions for provisioning Grafana resources within Kubernetes, using a persistent volume to supply the configuration files to the Grafana pod.

Follow-up note: after this, we could add similar Provisioning instructions on the [Grafana on Helm Charts documentation](https://grafana.com/docs/grafana/latest/setup-grafana/installation/helm/).

### CODE REVIEW

**Comment by Eve832** [comment]
@ppcano - can you find another technical review, so this PR doesn't get blocked? @usmangt doesn't have the bandwidth.

**Comment by ppcano** [comment]
> can you find another technical review, so this PR doesn't get blocked?

@usmangt, do you have anyone in mind?

**Comment by usmangt** [comment]
@ppcano Apologies for the long delay as I forgot to update it.

Yes, I think the best source will be to ask in our slack #kubernetes channel

**Review by eamonryan — APPROVED** [review]
Tech review: LGTM

**Pull request merged**
