### PR TITLE
Correction for repeat panels introduction

### PR DESCRIPTION
**Pull request by Mohit-Nain**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
The original language looks fine, sorry.

**Comment by Mohit-Nain** [comment]
can we have a second opinion on this. @oddlittlebird , can you please have a review

**Comment by aknuds1** [comment]
Based on my understanding of the technical process described by these docs, the original language is how I would write it also.

**Review by oddlittlebird — COMMENTED** [review]
This is a very subtle change, but it makes the sentence clearer.

**Review by oddlittlebird — APPROVED** [review]

**Pull request merged**
