### PR TITLE
Use dateMath in ScriptedDashboard

### PR DESCRIPTION
**Pull request by mtanda**
I want to parse time string, 'now-6h', in ScriptedDashboard.
So, pass dateMath to ScriptedDashboard.
(Not sure, this is correct. If there is any other way, please tell me...)

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo Would you check this?
This changes is required due to kbn API change.
(If possible, I want to merge this for 2.5 release.)

**Comment by mtanda** [comment]
@torkelo This is very simple PR.
And, this is backward compatibility issue.
Please check...

**Comment by torkelo** [comment]
for what do you use dateMath for in scripted dashboard?

**Comment by mtanda** [comment]
@torkelo I use for parsing the time string, 'now' or 'now-6h'.
For getting current active EC2 instance list, my scripted dashboard query to datasource with timerange parameter.

The default time range is 'now-6h' to 'now'.
Same as this example code.
https://github.com/grafana/grafana/blob/fde11be2793d63b8671ee6731ceead4efd1dd13f/public/dashboards/scripted_async.js#L39-L42

The time range parameter should be unix time.
So, I use dateMath to parse(convert) the time string.

**Pull request merged**
