### PR TITLE
Support Casbin as the authorization backend/middleware.

### PR DESCRIPTION
**Pull request by hsluoyz**
This PR tries to solve: https://github.com/grafana/grafana/issues/8584

### CODE REVIEW

**Comment by torkelo** [comment]
one really big downside with this is that urls are specified in two places. So if we change an api route we need to remember to change it in the auth config as well.

**Comment by hsluoyz** [comment]
@torkelo ,

> one really big downside with this is that urls are specified in two places.

Policy can be stored in three places: 1) file, 2) DB or 3) dynamically initialized in code. If we want to put the policy rules and the routes in the same place, we can just initialize the rules in ``api.go`` like:

```go
e := NewEnforcer("examples/rbac_model_with_domains.conf")

e.AddPolicy("admin", "domain1", "data1", "read")
e.AddPolicy("admin", "domain1", "data1", "write")
e.AddPolicy("admin", "domain2", "data2", "read")
e.AddPolicy("admin", "domain2", "data2", "write")

e.AddGroupingPolicy("alice", "admin", "domain1")
e.AddGroupingPolicy("bob", "admin", "domain2")
```

So if we change an api route we need to remember to change it in the auth config as well.

Even if one forgets to add auth config, there will be no too much harm. For example, a developer forgets to add the rule after he adds an API route. Then this new API route will use the default policy rule: 

```csv
# rules for organization viewer.
p, is, org_viewer, /*, *, allow
```

So only a logged-in user can access this route.

And if he adds a route under ``/admin*``, it will be controlled access to grafana admin by default because of this rule:

```csv
# rules for Grafana admin.
p, is_not, grafana_admin, /admin*, *, deny
```

So the developer actually doesn't need to do any change to the auth config. He's allowed to forget it.

The only exception is that he wants to do something new, like permitting a normal juser to access route like ``/admin/abc``. But I don't think this usage matches what the route means literally.

**Comment by hsluoyz** [comment]
Hi @torkelo ,

I have moved the auth rules to ``api.go``'s ``InitRouteAuthRules()`` function via the dynamic policy injection. So now API routes and auth rules are in the same place. Please review.

**Comment by torkelo** [comment]
this was interesting was definitely something we considered, but we opted not to use this.

**Pull request closed without merging**
