### PR TITLE
Plugins: Hide controls for renderer plugins

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
Ensure that catalog controls are hidden for the image renderer plugin

image

### CODE REVIEW

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by ryantxu** [comment]
I assume we are hiding it because the install does no work? this seems like an extra nice one to have a button so we can install it :)

**Comment by wbrowne** [comment]
Exactly @ryantxu. The rendering service still needs work to support this smoothly (also the plugin itself potentially since shutdowns don't appear graceful in their current form).

We'll get to it soon!

**Pull request merged**
