### PR TITLE
Alerting: Add Kavenegar notification channel.

### PR DESCRIPTION
**Pull request by amirajorloo**
**What this PR does / why we need it**:
Hi
I added the Kavenegar notification channel in this PR.
[Kavenegar](https://kavenegar.com/) is the best Iranian service for Sending a message and calling.
Because most Iranian developers can't pay for international services (because they have not an international credit card), This notification channel will be a great way to notify their developers.

### CODE REVIEW

**Comment by theSinner** [comment]
Hi
Can you please review this PR and tell me your opinion?
@joshhunt @ying-jeanne 

Thanks

**Comment by torkelo** [comment]
Can you open a feature request for this channel? We are not adding more channels unless there is a huge community demand.

But would be open to extensions (PRs) to our backend plugin system to support this via external plugins

**Comment by torkelo** [comment]
Btw, sorry to close your first PR like this, but taking on more notification channels is hard as we have to support and maintain them

**Comment by theSinner** [comment]
Hi @torkelo

It's okay, I totally understand that. I think the Iranian developers are not a large part of the Grafana users and adding it is not valuable comparing to its usage for the rest of the developers. But on the other hand, Iranian developers can’t use calling and messaging because of not having international credit cards.
I will try developing a backed plugin for it and beside that, I think it's better to keep my repo updated with the main repo plus some features like that.

Thank you for replying.

**Pull request closed without merging**
