### PR TITLE
Encryption: CLI rollback command

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

It adds a new CLI command within the subgroup of `secrets-migration` commands which does the opposite of `secretsmigrations.ReEncryptSecrets`. For every secret stored into the Grafana data base, decrypt it (either using legacy encryption or envelope encryption) and encrypt it again with legacy encryption.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise/issues/2647

**Special notes for your reviewer**:

I'm not 100% sure if it should happen within a transaction and/or how should we handle errors here. What if a specific secret has been corrupted but I want to roll back the healthy ones, for instance?

Note this is a CLI command because it is intended to be executed under maintenance mode. It should be pretty safe to execute it with a running instance (punctual errors may happen but nothing serious, if I'm not wrong) but then some secrets might be encrypted again with envelope encryption, so the only way to ensure all of them are rolled back is by stopping all the instances.

### CODE REVIEW

**Comment by undef1nd** [comment]
@xlson and I tested it a bit and we were wondering if the `data_keys` table should be truncated after rolling back to legacy encryption. Are there cases when we may want to use DEKs again?

**Review by undef1nd — APPROVED** [review]
Apart from the comment I left above and error handling you mentioned, looks good!

**Comment by undef1nd** [comment]
@joanlopez I found another issue - decrypting secrets that have metadata prepended after rolling back to legacy encr and downgrading to OSS. Here's the PR https://github.com/grafana/grafana/pull/44392

**Comment by undef1nd** [comment]
One more issue, sorry, Joan! 😅
I have a few secrets encrypted with the default grafana provider during our first encryption bug bash. 
The command fails to roll them back: it can't find a `secretKey` provider when decrypting secrets, because now default provider's id is `secretKey.v1` 
```
logger=secrets t=2022-01-24T19:47:27.01+0200 lvl=eror msg="Failed to lookup data key" name=2021-11-14/root@secretKey error="could not find encryption provider 'secretKey'"
```

**Comment by joanlopez** [comment]
> @xlson and I tested it a bit and we were wondering if the `data_keys` table should be truncated after rolling back to legacy encryption. Are there cases when we may want to use DEKs again?

Yeah, I agree it would be a great idea, gonna add that change! Thanks @undef1nd  @xlson  😊 

> Apart from the comment I left above and error handling you mentioned, looks good!

Let's go forward and discuss it later. I think the same discussion applies to all the CLI commands we're introducing, so I suggest to merge it then analyze its resiliency to make it better. I see pros & crons from every approach, so I'm still not 100%  sure. In any case, the feature is still in BETA and behind a feature toggle, so I think it should be safe to commit to a minimum set of features and then evaluate how to make them better. However, any other input is more than welcome, of course. 

> @joanlopez I found another issue - decrypting secrets that have metadata prepended after rolling back to legacy encr and downgrading to OSS. Here's the PR #44392

Discussed offline and discarded -- anyway thanks for taking care of these details, I really appreciate it.

> One more issue, sorry, Joan! 😅 I have a few secrets encrypted with the default grafana provider during our first encryption bug bash. The command fails to roll them back: it can't find a `secretKey` provider when decrypting secrets, because now default provider's id is `secretKey.v1`
> 
> ```
> logger=secrets t=2022-01-24T19:47:27.01+0200 lvl=eror msg="Failed to lookup data key" name=2021-11-14/root@secretKey error="could not find encryption provider 'secretKey'"
> ```

Again, thanks for pointing this out! 🙏🏻  It should be fixed here: https://github.com/grafana/grafana/pull/44721 💪🏻

**Review by xlson — APPROVED** [review]

**Pull request merged**
