### PR TITLE
Chore: Upgrade grafana-plugin-sdk-go

### PR DESCRIPTION
**Pull request by marefr**
**What is this feature?**

Upgrade SDK to v0.213.0. Verified with [test-datasource](https://github.com/grafana/test-datasource) it works as expected given the gRPC dependency update.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by toddtreece — COMMENTED** [review]
@marefr i might be missing it, but it doesn't seem like the plugin SDK is upgraded?

**Review by ryantxu — APPROVED** [review]

**Review by toddtreece — APPROVED** [review]

**Comment by marefr** [comment]
> @marefr i might be missing it, but it doesn't seem like the plugin SDK is upgraded?

Doh! Sorry I only removed the replace directive and forgot adding the sdk upgrade 😂 I'll fix

**Comment by ryantxu** [comment]
@marefr I already fixed it :) press merge if it looks ok to you (it is green now)

**Comment by marefr** [comment]
Thanks. I got a change running `go mod tidy` so will push that

**Pull request merged**
