### PR TITLE
Geomap: Base layer server configuration

### PR DESCRIPTION
**Pull request by euniceek**
**What this PR does / why we need it**:
This PR implements the configuration sections in the backend to allow users to provision tile servers for the new GeoMaps plugin, addressing part of #36585 - Server settings for base layer. A separate PR will be filed to use these variables in the frontend to set the default base map.

Examples of various default base layer config from `defaults.ini`:

```
geomap_default_baselayer = `{
      "type": "xyz",
      "config": {
        "url": "[custom tile server]",
        "attribution": "Tiles &copy; <a href=http://www.openstreetmap.org/copyright>OpenStreetMap</a>"
      }
    }`
geomap_disable_custom_baselayers = true
```

```
geomap_default_baselayer = `{
      "type": "carto",
      "config": {
        "theme": "light",
        "showLabels": false
      }
}`
geomap_disable_custom_baselayers = false
```

```
geomap_default_baselayer = ` {
    "type": "esri-xyz",
        "config": {
            "server": "world-physical"
        }
} `
geomap_disable_custom_baselayers = false
```

cc @alolita

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure I understand the option geomap_disable_custom_baselayers 

Having a json string in a setting is a bit problematic, makes it a bit tricked to set only the url for the title server via env variable.

**Comment by torkelo** [comment]
But a json string could still be an ok option if the flexibility to set all of those optimism in at once is an important/frequency use case

**Comment by eunice98k** [comment]
> Not sure I understand the option geomap_disable_custom_baselayers

`geomap_disable_custom_baselayers` disables all other basemap, other than the default configured map. The main use case will be for Amazon Managed Service for Grafana, where only the tile server that uses a service endpoint is allowed and the rest of the base layers has to be removed.


> But a json string could still be an ok option if the flexibility to set all of those optimism in at once is an important/frequency use case

I believe this will be a frequent use case for all Grafana users who want to configure their default base maps - not just the tile server but the style as well. Also having it as a json string prevents expanding the front end settings with lots of default values.

**Comment by ryantxu** [comment]
> Not sure I understand the option geomap_disable_custom_baselayers

For amazon managed service, they want to force a basemap that people can not change :shrug: 


> Having a json string in a setting is a bit problematic, makes it a bit tricked to set only the url for the title server via env variable.

If we only had one basemap type, it might make sense to have explicit values for each leave of the config (url, attribution, min/max zoom, etc)

I expect this to be rare and rather advanced -- but a json config give us full control

**Review by ryantxu — APPROVED** [review]

**Pull request merged**
