### PR TITLE
Docs: Sync master docs against next version

### PR DESCRIPTION
**Pull request by torkelo**
* Changes github sync action to sync against  docs/grafana/next  in website repo 
* Updates all aliases from docs/grafana/latest to docs/grafana/next 

website repo PR: https://github.com/grafana/website/pull/3892

### CODE REVIEW

**Review by robbymilo — APPROVED** [review]

**Comment by oddlittlebird** [comment]
@torkelo, why did you update the aliases? I thought aliases were redirects for old pages, so that if something tried to link to an old page location, it will go to the new location. Since the `next` folder is new, nothing could have linked to it.

**Comment by torkelo** [comment]
@oddlittlebird the same regex replaced all paths, hm.. maybe the aliases should not have been updated, will make backports tricker. what do you think @robbymilo  ?

**Comment by oddlittlebird** [comment]
Another thing to consider is whether we want to link to next or latest within the documentation. I would think that since latest is the current latest and next is basically beta, we should probably link to latest in most, possibly all, cases.

The best case would to have links in the next folder go to topics in the next folder and links in latest go to latest topics, but I don't think we have the architecture for that yet. We discussed this a while back in the context of old versions, where if you are looking at an old version of docs and click a link, the link will go to the current version (in latest), not whatever you are looking at.

**Comment by torkelo** [comment]
Links should use the relref (so be relative) and not contain next or latest , but do you mean links between products?

**Comment by osg-grafana** [comment]
> Links should use the relref (so be relative) and not contain next or latest , but do you mean links between products?

+1 to no baked in `next` or `latest`.

**Comment by oddlittlebird** [comment]
I fixed the non-relref links that could be fixed in #32916 (when it gets merged), but the alias links still need to be fixed.

**Pull request merged**
