### PR TITLE
Transformations: Add field from calc - avoid frame joining in some cases

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/hyperion-planning/issues/91

in our `Add field from calculation` transform, the Binary mode always joins multiple time series frames into one (via `ensureColumns`). this joining process affects our [rather complex] automatic field naming, especially in the `__series.name` data macro.

this PR tries to avoid the join when the `right` value is a static number (`fixed`) rather than a field name. it doing so, it does potentially alter the final field naming as shown in the legend, tooltips, and used in the panel override matchers. therefore, it could cause some limited breakage, but i'm not sure how we can maintain full backwards compatibility with the previous auto-naming design that doesnt introduce even more complexity.

### CODE REVIEW

**Review by baldm0mma — APPROVED** [review]

**Review by drew08t — COMMENTED** [review]
Need to confirm that "replace all fields" is working properly with multiple queries and no filter applied to the transformation.

**Comment by drew08t** [comment]
I went through 3 branches: 11.2.x, main, and this PR. For 2 queries containing number fields, I looked at all these combinations to get a handle on "replace all" behavior. Appears the only discrepancy we need to fix is for a single field selection and no filter. Looking into a fix for this now that I've documented the behavior. 

image

**Comment by drew08t** [comment]
As an alternative, `${__field.name}` or `${__field.labels}` can be used instead. If that's acceptable, I'd prefer not to merge these changes due to the impact on `replace all fields`.

**Review by drew08t — CHANGES_REQUESTED** [review]
As an alternative, `${__field.name}` or `${__field.labels}` can be used instead. If that's acceptable, I'd prefer not to merge these changes due to the impact on `replace all fields`.

**Review by drew08t — APPROVED** [review]

**Pull request merged**
