### PR TITLE
Switch: Improve disabled active state

### LINKED ISSUE #86953: Saga Toggle: on/off state unclear when disabled
When a toggle is disabled it is difficult to differentiate between the on/off state. The left/right orientation of the toggle is not enough to communicate it's state. See images below

**Enabled states**
Image
Image

**Disabled states**
Image
Image

**Potential directions**
- Provide an indication of a color difference between on/off states when disabled (see: [Nord Health](https://nordhealth.design/components/toggle/?example=disabled#examples))
- Include an additional checkmark to the toggle to better indicate on state (see: [Twilio](https://paste.twilio.design/components/switch#disabled-on))

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- enhances the disabled active state to distinguish it from inactive

|  | before | after |
| --- | --- | --- |
| dark | image | image |
| light | image | image |

**Why do we need this feature?**

- so it's clearer what state a disabled switch is in

**Who is this feature for?**

- everyone!

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/86953

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by tskarhed** [comment]
Maybe it is the screenshots, but I can't seem to see the difference

**Comment by ashharrison90** [comment]
> Maybe it is the screenshots, but I can't seem to see the difference. Are they all in a disabled state?

yes, they're all disabled and active

**Review by tskarhed — COMMENTED** [review]
LGTM, although I think some color savvy person should have a look at it.

**Review by joshhunt — COMMENTED** [review]
image

It's better, but I think the background still is just so slightly subtle. I had to actually put them side-to-side to understand what the image in your PR was showing (it wasn't clear that they were active).

I don't really have a good better suggestion - i think the blue needs more vibrance when it's disabled...

**Comment by ashharrison90** [comment]
> @ashharrison90 I don't know if it's better, but another approach could be to leave the colours the same, but use opacity to fade it out when disabled
> 
> image
> 
> Here I've also changed the inactive + disabled state to use the same colours + opacity, though I think it's not lacking a lot of contrast from the background.

hmmmm, that makes me a little nervous cause now we're making other things transparent (border, toggle, etc) 😬 

there's also a `borderTransparent` token which is stronger (0.25 opacity vs 0.15 for the `transparent`)

|  | transparent | borderTransparent |
| --- | --- | --- |
| dark | image | image |
| light | image | image |

but i'm nervous about that as well cause it's not really the correct semantic token for this 🤔 

i still lean towards just using the `transparent` token. i agree it's subtle, but i think we can afford to be subtle in this case and it is (arguably) the most correct token. but ofc i'll defer to the popular vote 🙇 

wdyt @staton-hyse11 ?

**Comment by staton-hyse11** [comment]
The approach is good, but I'm concerned that `disabled-inactive` vs `inactive` are too similar. Is anyone concerned there?

**Comment by ashharrison90** [comment]
> The approach is good, but I'm concerned that `disabled-inactive` vs `inactive` are too similar. Is anyone concerned there?

yeah i gotcha 👍 i'm not _overly_ concerned, but if anyone's got suggestions i can try them?
i've pushed a small change to use the disabled color for the toggle always. before it was only setting it when it was active.

but honestly you won't visually notice as the difference between secondary (0.65 opacity) and disabled (0.60 opacity) is so small. maybe that's part of the problem? 🤔

**Comment by staton-hyse11** [comment]
I'm wondering if an addition to the active state would help any confusion around a toggle being `active-disabled` or `inactive-disabled`. Adding a checkmark icon to the active states would provide an extra affordance that it's active. Either maintaining the current disabled state or using the `transparent` token would be an improvement.

image

**Comment by ashharrison90** [comment]
@staton-hyse11 i think our switches might be a little too small for that to work, the ✅ icon ends up looking a little off:

image

or maybe it's fine? idk, what do you think? 😄

**Comment by staton-hyse11** [comment]
IDK, It's not horrible. Also, it's a bit hard to tell in the screen shot because of scaling.

**Comment by ashharrison90** [comment]
ok have added the check mark, lmk what you think:

https://github.com/grafana/grafana/assets/20999846/f1edf2c2-1f27-4f74-9e0a-de87580cd179

**Comment by staton-hyse11** [comment]
@ ashharrison90, it helps clarify the state. I'm wondering if the check should be a touch darker when disabled. Thoughts?

@torkelo what are your thoughts on this? The goal is to provide more indication of the active state when a toggle is active-disabled.

**Comment by torkelo** [comment]
@staton-hyse11 looks good!

**Comment by ashharrison90** [comment]
> @ ashharrison90, it helps clarify the state. I'm wondering if the check should be a touch darker when disabled. Thoughts?
> 
> @torkelo what are your thoughts on this? The goal is to provide more indication of the active state when a toggle is active-disabled.

@staton-hyse11 assuming you're talking mostly about dark mode disabled? idk, it's tricky to find a semantically correct theme color token that works in both light and dark cases. plus, if we go darker we start to lose contrast with the toggle 🤔 

i'd vote for sticking with this and see how we go since it's already an improvement 😅

**Review by staton-hyse11 — APPROVED** [review]
I think this is a great step to improving the understanding of the state of the toggle.

LGTM!

**Review by Clarity-89 — APPROVED** [review]

**Pull request merged**
