### PR TITLE
Expression: Fix a bug of the display name of the threshold expression result

### PR DESCRIPTION
**Pull request by lingyufei**
**What is this feature?**

Fix the display name of the threshold expression result.

**Why do we need this feature?**

Before this fix, when I created a threshold expression [C], the result's name was displayed as [A] which is wrong and confusing.
image
image

After this fix, the name of the result displays correctly. The display name should be the same as the refID.
image
image

**To fix this issue, when creating a math command for this threshold expression, the RefID should be used rather than the ReferenceVar. Please refer to the the change I made in the code in "file changed".** 

**Who is this feature for?**

Users who use the threshold expression.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by lingyufei** [comment]
@kylebrandt Could you please have a a look at this issue?

**Comment by lingyufei** [comment]
Another example. 
Before this fix, if I use the following configuration, I even couldn't differentiate the data result which is confusing.
image

So, The refID should be displayed rather than the ReferenceVar ID as below.
image

**Review by kylebrandt — APPROVED** [review]
Thank you for catching this and the fix.

**Comment by lingyufei** [comment]
@kylebrandt @itsmylife 
I updated the unit test of Hysteresis to pass the CI/CD test.
The unit test of Hysteresis asserts that the name of the returned/output result should be the same as the reference ID after executing the threshold expression.
However, after this fix, the name of the returned/output result should be the same as its ref ID.
Please check if this is good for you. Thanks!
image
image

**Comment by itsmylife** [comment]
@lingyufei I think it is ok to me. @kylebrandt has more context than me though. What do you think @kylebrandt ?

**Review by yuri-tceretian — APPROVED** [review]
Nice catch! Thanks for fixing!

**Comment by lingyufei** [comment]
@yuri-tceretian 
Sorry...
I want to fix the e2e test. It seems that the docker image of the playwright has been updated and my branch is not update to date. So I merged the main branch, and the label messed up. I have reverted it.
Could you please clean these labels? Sorry about that.

**Comment by lingyufei** [comment]
It seems that the latest playwright docker image is required to pass the e2e test. However, this branch/PR was not checked out from the latest main branch. 
Do you have any idea on how to fix this? Do we need to create a new PR with the latest main branch?
image

**Comment by lingyufei** [comment]
@yuri-tceretian @itsmylife @kylebrandt 
I have rebased my code onto the latest main branch to fix the e2e test error caused by the inconsistency between the version of e2e Chrome and the playwright image. Rebasing onto the latest main branch could fix this issue.

Please review this PR again, and re-trigger the CI test. Sorry for any inconvenience.

**Comment by itsmylife** [comment]
I am not sure why this is failing the `remote-alertmaanger-integration-tests` step. Could you please merge the `main` branch once more? Worst case we can have another PR. @kylebrandt do you have any other solutions?

**Comment by lingyufei** [comment]
@itsmylife 
The rebase action did fix the playwright e2e test.
Now I have rebased the main branch again. Could you please trigger the CI again? Let's see if this could fix the `remote-alertmaanger-integration-tests` step.
Thanks for your patience.

**Comment by itsmylife** [comment]
@lingyufei it looks like there is a problem with our CI pipeline. I should have been resolved already but I'll investigate it and keep you posted. Thanks for **your** patience.

**Review by itsmylife — APPROVED** [review]
LGTM 🚀 
Thanks for your patience.
Finally CI is all green

**Comment by itsmylife** [comment]
For our future selves here is why it wasn't working https://raintank-corp.slack.com/archives/C036J5B39/p1705920407966359

I just did the following and rerun the pipeline
```
gh pr checkout <PR>
git push origin <branch>
```

**Comment by lingyufei** [comment]
Great! Thanks for your help!

**Pull request merged**
