### PR TITLE
reports multiple prometheus instances

### LINKED ISSUE #20104: prometheus stats 2.0 does not handle multiple prometheus instances
**What would you like to be added**:
Support to see the status of all the prometheus instances

**Why is this needed**:
To monitor a prometheus cluster

I tried to update the public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json file in github but it seems complicated.
so please find attached a working version (for me at least).

Capture d’écran de 2019-10-30 14-54-12

[Prometheus 2.0 Stats.zip](https://github.com/grafana/grafana/files/3789217/Prometheus.2.0.Stats.zip)

### PR DESCRIPTION
**Pull request by mobidyc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes grafana/grafana-prometheus-datasource#95

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aocenas** [comment]
Hey @mobidyc can you provide a bit more info what are you trying to fix with this PR?

**Comment by mobidyc** [comment]
Hello,

this PR to fix https://github.com/grafana/grafana/issues/20104
integrated prometheus-2.0 dashboard does not handle multiple prometheus instances (using federation for instance).

**Comment by aocenas** [comment]
Thanks @mobidyc.
@torkelo can you take a look at this when you have time, seems like you looked at the issue this was started with.

**Comment by torkelo** [comment]
Would prefer if someone with more specialized Prometheus experience could review this @davkal @RichiH maybe?

**Review by davkal — CHANGES_REQUESTED** [review]
This PR is overriding an importable dashboard with a simple JSON copy of a modified dashboard. It loses the ability to import it properly (e.g., `__inputs`) is missing. 

From what I can tell the main motivation for this update are the `instance` breakdowns in the queries. My suggestions is to simply change those in the existing `prometheus_2_stats.json` and publish those as a PR, leaving the rest of the JSON intact.

**Comment by davkal** [comment]
@mobidyc would you be able to make the change according to my last comment?

**Pull request closed without merging**
