### PR TITLE
Add alerting notifier for Matrix

### PR DESCRIPTION
**Pull request by paukstis**
Hi, was looking for alert notifier for Matrix (https://matrix.org/docs/spec/), couldn't find anything and then thought maybe native notifier would be good. I'm not a Go pro, the code is assembled from existing notifiers, but it builds and so far looks like it works.

### CODE REVIEW

**Comment by bergquist** [comment]
At this point we wont add more notifiers to grafanas core. We are currently working on supporting backend plugins https://github.com/grafana/grafana/issues/6841 once that have been released it should be fairly easy to build this as a plugin.

**Comment by paukstis** [comment]
alright, thanks, I'll check it out.

**Comment by bergquist** [comment]
@paukstis I strongly suggest creating an issue first. That way we can respond to that before you invest time building the feature. 

Again, thank you for contributing. even thou this change didn't make it.

**Comment by chevdor** [comment]
Thanks for taking the time to make this PR @paukstis, I think that would be a valid addition to Grafana.

@bergquist, could that not be merged until backend plugins are supported? I see #6841 is still open.

**Comment by lovelaced** [comment]
Backend plugin support has just been moved to longterm. :(

**Comment by marefr** [comment]
@lovelaced longterm in this case means v6.4 stable, but at the same time can be split in multiple releases. However, first official support for backend plugins will probably not include alert notifiers. We currently discussing the future of Grafana alerting and before we've settle some things there alert notifier backend plugin support have to wait.

**Comment by marefr** [comment]
#16004 is the issue in question regarding alert notifier backend plugin support.

**Comment by lovelaced** [comment]
@marefr Thank you for the update!

**Comment by moepman** [comment]
Really sad to find out that matrix is not easily supported and has been delayed into the far feature until some plugin infrastructure is in place.

**Pull request closed without merging**
