### PR TITLE
Add Panel pie chart

### PR DESCRIPTION
**Pull request by jmaitrehenry**
Hi,

I add a panel pie chart base on work of @bahadir for issue #568.
It's a really simple panel for now but I will maybe add more option to it when I will use it in production.

Thanks,

### CODE REVIEW

**Comment by torkelo** [comment]
Awesome! Looks like a great start. Would like to have some units tests, and would also like to see some refactoring, so that more code could be shared between this and singlestat (some duplicated code between them), not sure how to do that yet thought. Will take a while before this might be merged. 2.5 Beta is to be released soon, then stable and then... so no ETA on when it could be merged. But it looks like a good start and I would like to see it merged sometime in the coming 2 months.

**Comment by jmaitrehenry** [comment]
Thanks for the feedback!
I will add some test soon and try to refactor panel because I reuse some code from single stats and from graph.

I will try to add gauge soon and the refactor will help.

**Comment by utkarshcmu** [comment]
@jmaitrehenry - check this out for gauge: https://github.com/toyoty99/flot.gauge

**Comment by jmaitrehenry** [comment]
@utkarshcmu interesting, but I maybe try to use http://justgage.com/
I didn't start yet on it, I will try to finish this PR before :)

**Comment by sxd** [comment]
Hi @jmaitrehenry your work looks awesome, you know when we can start using it at production? or at least see it merge into mainstream so I can start using on my QA

**Comment by jmaitrehenry** [comment]
Hi Jonathan,

I already use it in production, for when this one will be merge, you have to ask owner of the repository, if you want to help me to made some refactor as asked, feel free to make a PR on my fork.
My branch can be updated with remote master and be use if you want to manually build grafana.

Thanks,
Julien

**Comment by karma1911** [comment]
Any update ? :)

**Comment by bergquist** [comment]
I've moved the code into a plugin repository for grafana.
If enough people start using it we will merge it into core grafana.

Closing this PR for now.

**Pull request closed without merging**
