### PR TITLE
DashboardScene - Variables: cancel out margin-bottom of placeholder in loading state

### LINKED ISSUE #86570: DashboardScene: Variable Editor: Run Query loading placeholder has margin-bottom which pushes the text up too much
### What happened?

When selected a query based variable in the variable editor and pressing the run query button the loading state of the button adds 32px margin to the bottom of the showing the weird bug shown below.

https://github.com/grafana/grafana/assets/6132021/0d97aeb3-60c5-4d93-a397-89732522a4e1

### What did you expect to happen?

That the button would look the same just change text.

### Did this work before?

Yes but i think there is a different UI for variable editor form now.

### How do we reproduce it?

1. Create Dashboard
2. add query variable
3. click run query to test query

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11 / bugbash
OS: mac
Browser: chrome

### Grafana platform?

None

### Datasource(s)?

I was testing with New Relic

### PR DESCRIPTION
**Pull request by Multimo**
**What is this feature?**

This is a bug fix to fix the css issue demonstrated in the screenshot on gf 11 preview. 

Fixes #86570

### Before:
image

### After:
image

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey @Multimo 👋🏾 , thanks a lot for helping us with this one ❤️ . The code looks good to me, but it seems there is an issue with CLA, can you check?

**Review by axelavargas — APPROVED** [review]
🥳

**Comment by Multimo** [comment]
oped this pr as a fork but e2e is failing so opened this pr: https://github.com/grafana/grafana/pull/87107

**Comment by axelavargas** [comment]
closing in favor of https://github.com/grafana/grafana/pull/87107 😄

**Pull request closed without merging**
