### PR TITLE
Cherry picks for 7.1.0

### PR DESCRIPTION
**Pull request by dprokop**
--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Docker: Make sure to create default plugin provisioning directory, (#26017), merge-sha: e25c6db7e98ebe64cfe5db3208e6bcef88b6cd88
  * Explore/Loki: Escape \ in labels for show context queries, (#26116), merge-sha: 52f12d10c5df97873c2fb09afb0cc571ff4b2cd3
  * Elastic: Fix error "e.buckets[Symbol.iterator] is not a function" when using filter, (#26217), merge-sha: 6d8545da63f05498fb62904e430e38cb9fe38c00
  * Backend: use latest go plugin sdk (0.74.0) to sort wide frames, (#26207), merge-sha: c1ede4fc71b6c496c3adf4f5aeee6e18c8703f32
  * Login: fixes footer inconsistency, (#26255), merge-sha: f4b6abb05e39a5a4fcc45c5897eeb313a1a19418
  * Removes erroneous $ while deleting organisation, (#26257), merge-sha: c136f7da39dda5b782a9308096920d35b795884c
  * Jaeger/Zipkin: URL-encode service names and trace ids for API calls , (#26115), merge-sha: 73468e14817f073d8feaa1312a22253d593faa55
  * Chore: Fix failing master due to strictNullCheck error , (#26283), merge-sha: 95bf064776984d0e2b6e9707c964041e736c3bd6
  * BarGauge: Fixed width of unfilled region not being correct when value is close to 100%, (#26193), merge-sha: b1e48f429fb82af33f65e57f549b1a099a89d33e
  * Prometheus: Fix prom links in mixed mode, (#26244), merge-sha: 0dd2bc895307e87780481e838eb933850be98daa
  * Fix: Make the JSON in JSONCell Tooltip more visible, (#26048), merge-sha: 7cdbae4ae6d6abda90231e18e8457eecfac92a16
  * AdminUsers: reset page to zero on query change, (#26293), merge-sha: e63028e8c601b3d98f03990cfcc93c7ab305b09b
  * Docs: Flux support in influxdb data source in 7.1, (#25551), merge-sha: d28b62740bfaf5365d55573c80e0566649d25b1c
  * implicit import symbol-observable to avoid inconsistent symbol, (#26288), merge-sha: 077aec465cec3103ebe26cf07ae187374f0a6345
  * PluginsListPage: More plugins button should open in new window, (#26305), merge-sha: 7bbfb57dd1df61e8449715f3b68dd042e0d7dfa1
  * CloudWatch Logs: Fixes grouping of results by numeric field, (#26298), merge-sha: 54ad5b869e686bb61993a84bae06b5996cc74dfc
  * SignIn button - use correct url, (#26239), merge-sha: 187612ca8d809c23cca93c1dd5ec404bf486f260
  * ThemeContext: Fix useStyles memoization, (#26200), merge-sha: 72cd9a322243d801f9964c4610e913aa9ee20685
  * DashboardLinks: do not over-query search endpoint, (#26311), merge-sha: 23e93175d1741e74bbdf488af885075ab17faab3
  * Admin: Update org list after delete, (#26277), merge-sha: 208f95a76cd8db5312683ebb748b38d7378aff56
  * Docs: Add info about logs/metrics unification to What's New docs, (#26325), merge-sha: 1de810b26af3d6d41944a9ad84a0cde3c55e525d
  * Docs: Add derived field datasourceUid information, (#26285), merge-sha: 5b2ff4498e165b67bed6e62faa10d784321e43c2
  * Elasticsearch: Create Raw Doc metric to render raw JSON docs in columns in the new table panel, (#26233), merge-sha: 3fd810417fc4ba5a2afb016bfd6bcce75754dae1
  * Azure: Handle real type nan/inf values in Log/Insights Analytics, (#26342), merge-sha: 590702c497ac0c99222766787432353fa68ffb8d
  * Cloud monitoring: add query parameter in the deep link, (#26354), merge-sha: 9d8ae39108af42ab7ba25ea8a043d21a9bd91604
  * Login: Update background color based on theme, (#26359), merge-sha: 21971a4df841a30056af162b2ff6c8307d2a9545
  * Azure: Insights Analytics, fix possible panics and return error body, (#26361), merge-sha: c980f3750931515387ea4147baa1ea15c4092dff
  * Provisioning: Fix bug when provision app plugins using Enterprise edition, (#26340), merge-sha: b97d1f41707dd9311ecbe8bf672a5ed028700095
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x e25c6db7e98ebe64cfe5db3208e6bcef88b6cd88
  git cherry-pick -x 52f12d10c5df97873c2fb09afb0cc571ff4b2cd3
  git cherry-pick -x 6d8545da63f05498fb62904e430e38cb9fe38c00
  git cherry-pick -x c1ede4fc71b6c496c3adf4f5aeee6e18c8703f32
  git cherry-pick -x f4b6abb05e39a5a4fcc45c5897eeb313a1a19418
  git cherry-pick -x c136f7da39dda5b782a9308096920d35b795884c
  git cherry-pick -x 73468e14817f073d8feaa1312a22253d593faa55
  git cherry-pick -x 95bf064776984d0e2b6e9707c964041e736c3bd6
  git cherry-pick -x b1e48f429fb82af33f65e57f549b1a099a89d33e
  git cherry-pick -x 0dd2bc895307e87780481e838eb933850be98daa
  git cherry-pick -x 7cdbae4ae6d6abda90231e18e8457eecfac92a16
  git cherry-pick -x e63028e8c601b3d98f03990cfcc93c7ab305b09b
  git cherry-pick -x d28b62740bfaf5365d55573c80e0566649d25b1c
  git cherry-pick -x 077aec465cec3103ebe26cf07ae187374f0a6345
  git cherry-pick -x 7bbfb57dd1df61e8449715f3b68dd042e0d7dfa1
  git cherry-pick -x 54ad5b869e686bb61993a84bae06b5996cc74dfc
  git cherry-pick -x 187612ca8d809c23cca93c1dd5ec404bf486f260
  git cherry-pick -x 72cd9a322243d801f9964c4610e913aa9ee20685
  git cherry-pick -x 23e93175d1741e74bbdf488af885075ab17faab3
  git cherry-pick -x 208f95a76cd8db5312683ebb748b38d7378aff56
  git cherry-pick -x 1de810b26af3d6d41944a9ad84a0cde3c55e525d
  git cherry-pick -x 5b2ff4498e165b67bed6e62faa10d784321e43c2
  git cherry-pick -x 3fd810417fc4ba5a2afb016bfd6bcce75754dae1
  git cherry-pick -x 590702c497ac0c99222766787432353fa68ffb8d
  git cherry-pick -x 9d8ae39108af42ab7ba25ea8a043d21a9bd91604
  git cherry-pick -x 21971a4df841a30056af162b2ff6c8307d2a9545
  git cherry-pick -x c980f3750931515387ea4147baa1ea15c4092dff
  git cherry-pick -x b97d1f41707dd9311ecbe8bf672a5ed028700095

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM! Verified with `grabpl verify-cherrypicks`.

**Comment by papagian** [comment]
I have changed base in #26331 to target this branch. I'm waiting for the build to finish so we can merge it to this one.

**Comment by dprokop** [comment]
> I have changed base in #26331 to target this branch. I'm waiting for the build to finish so we can merge it to this one.

Thanks Sofia, I was wondering if using the 0.74 sdk is fine with that PR.

**Review by marefr — APPROVED** [review]
LGTM when other PR have been merged to this one

**Review by daniellee — APPROVED** [review]
LGTM

**Comment by papagian** [comment]
> > I have changed base in #26331 to target this branch. I'm waiting for the build to finish so we can merge it to this one.
> 
> Thanks Sofia, I was wondering if using the 0.74 sdk is fine with that PR.

the only an additional fix in 0.75:
https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.74.0...v0.75.0
so I think it's fine to upgrade it.

**Pull request merged**
