### PR TITLE
[v9.3.x] Server: Switch from separate server & cli to a unified grafana binary

### PR DESCRIPTION
**Pull request by grafanabot**
Backport de99ce139c96e7229bb5e194aed225e3321d8685 from #58286

### CODE REVIEW

**Comment by DanCech** [comment]
@dsotirakis if we want to backport this we'll likely need to backport some of the supporting PRs also, I can look into that if so

**Comment by dsotirakis** [comment]
> @dsotirakis if we want to backport this we'll likely need to backport some of the supporting PRs also, I can look into that if so

Yes @DanCech that would be awesome 🙇 I was about to do it myself but since you are here please do so!

**Comment by DanCech** [comment]
We'll definitely need #59890, not sure what else

**Comment by DanCech** [comment]
It looks like that might actually do it, this change was much more isolated from the unified dockerfile work than I remembered.  We could/should also backport #60684 for completeness but that is better done as a separate backport I think.

**Comment by dsotirakis** [comment]
Thanks @DanCech, trying to see if all the pipelines work for `v9.3.x` before we merge 🙇

**Review by dsotirakis — APPROVED** [review]
Thanks @DanCech!

**Pull request merged**
