### PR TITLE
Search: cleanup old Angular files

### LINKED ISSUE #23667: Search: clean up unused Angular files
**What would you like to be added**:

- [ ] Remove Angular files for search functionality.
- [ ] Remove unused functionality from `search_srv` and look into refactoring it. 

**Why is this needed**:
Part of Search migration.

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
- Remove old angular files for search functionality 
- Remove redundant functionality from `search_srv`
- Unify search related types 

**Which issue(s) this PR fixes**:

Fixes #23667

**Special notes for your reviewer**:

### CODE REVIEW

**Review by alexanderzobnin — APPROVED** [review]
Looks good to me!

**Review by dprokop — APPROVED** [review]
Great! Do you mind updating https://github.com/grafana/grafana/issues/21484 ?

**Comment by Clarity-89** [comment]
@dprokop will do!

**Comment by dprokop** [comment]
Thank you @Clarity-89 . Please check https://github.com/grafana/grafana/issues/22862 also

**Pull request merged**
