### PR TITLE
Navigation: Fixes closing submenus on scrolling

### LINKED ISSUE #48194: Navigation: Submenu does not open when tabbing into trigger that is not in view because of scroll
**What happened**:

If the collapsed menu has too many items and it needs to scroll and the user is using keyboard to navigate, sometimes when tabbing into a nav trigger it won't open the corresponding side menu:

https://user-images.githubusercontent.com/100691367/165104496-effb84ae-f20e-437d-bf2b-efd4bc02c845.mov

**What you expected to happen**:

Submenu is open whenever you tab to that trigger.

**How to reproduce it (as minimally and precisely as possible)**:

Make the window smaller until the navigation has to be scrollable and has some hidden items, then use the keyboard 'Tab' to go through the nav triggers.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: n/a
- OS Grafana is installed on: -
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What this PR does / why we need it**:

The submenus now stay open if the user tabs into them and that forces a scroll. Previously the menu would automatically close when the navigation was scrolled.

https://user-images.githubusercontent.com/100691367/165133853-c5068e4a-82fc-4260-a2db-468a6c822d47.mov

**Which issue(s) this PR fixes**:

Fixes #48194

**Special notes for your reviewer**:

It would be great if someone else could test using the navigation with keyboard and mouse, to make sure nothing is broken by removing that check. The check was added for a reason that I do not remember but everything seems to work if I remove it!

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hallo 😃  , great job on giving this a try! 

I found a small issue, whenever we click in one of the submenus, it does not close the menu (I tested in the main branch and there this problem is not present)


Current Branch

https://user-images.githubusercontent.com/239999/165328277-dfdf4f72-bb0b-4ab6-99b6-57fbece6d63c.mp4

Main Branch


https://user-images.githubusercontent.com/239999/165328269-e6737c7b-f740-42a9-adcc-33e5171c90f8.mp4

**Comment by JoaoSilvaGrafana** [comment]
> I found a small issue, whenever we click in one of the submenus, it does not close the menu (I tested in the main branch and there this problem is not present)

Ah so THAT is what it was used for 😅 I can do a bit more digging to see if we can go around that.

**Comment by JoaoSilvaGrafana** [comment]
@axelavargas Fixed that issue by calling `setMenuIdOpen(undefined)` in the `onAction` callback. Had to duplicate the `NavBarItemMenuItem` in the `Next` folder, but it was the only one that was missing so it makes sense either way

**Review by axelavargas — APPROVED** [review]
Works as expected 👏🏾, great job @JoaoSilvaGrafana, I agree with you, duplicating the file makes sense, it will be easier to clean up later when we remove the feature flag :)

**Pull request merged**
