### PR TITLE
Add Norwegian Krone currency

### PR DESCRIPTION
**Pull request by jskarpe**
See http://www.xe.com/symbols.php for currency symbols reference

### CODE REVIEW

**Comment by bergquist** [comment]
No way! `kr` is Swedish kronor.

**Comment by Yuav** [comment]
Actually, it's the same symbol across the Nordics. I'll update the PR

**Comment by bergquist** [comment]
@Yuav great!

Thank you for contributing! :)

**Comment by zhongqin0820** [comment]
@imranhum1 Have you rebuild the front-end resources?

**Comment by imranhum1** [comment]
No, how do i do that?

**Comment by imranhum1** [comment]
i just restarted the grafana service after changing the kbn.js & kbn.ts

**Comment by zhongqin0820** [comment]
@imranhum1 Refer to README.md. Or you may check below:
- [ ] 1. Install node.js
- [ ] 2. `cd` the project directory, use `npm install ` to install the dependencies
- [ ] 3. Run `npm build` to rebuild the front-end resources or run `npm start` to reload the front-end resouces in hot-load mode. For more `npm ` commands, you can refer to `package.json` file -> `scripts` keyword

**Pull request merged**
