### PR TITLE
GrafanaUI: Update FilterPill active state and ToolbarButton active state 

### PR DESCRIPTION
**Pull request by torkelo**
Addressing these problems with filter pill 

* Current active / selected state is very faint in light theme (okish in dark theme) 
* Align active / selected state 

Before: 

Screenshot from 2023-06-19 14-09-10

After: 

image
image

ToolbarButton 

* The active state was using a color from the old v1 theme
* Explore was using a very old sass class (with the same old color) to override the default design system Button to have orange border 

Before: 

image

After:

image
image

There an issue in Explore where they set active state to many ToolbarButtons wrapped in ButtonGroup:

image

Looks like this now: 
image

* Keep it as is in this PR (looks ok), can be refined I think to only have active state on the actual link button not the others. That change could be done in separate PR. 
* Only set active state on the link button in this PR 

Explore was also overriding the default Button styles using an old css class: 

Before: 
image

I changed this to ToolbarButton with variant=active:

image

* Only difference is that ToolbarButtons have only 8px left/right padding (compared to 16px for normal Button). We could add active state to normal Button but not sure that is a good idea.

### CODE REVIEW

**Comment by staton-hyse11** [comment]
I'm good with these changes and we can revisit the pills in the future. @catherineymgui do you think these will perform as well as what you had tested?

**Comment by tskarhed** [comment]
I have seen another implementation (or maybe it was just in Figma) for the FilterPill, where the active state was a border around the entire pill instead of just under. Just mentioning it for reference.

**Comment by gelicia** [comment]
Not sure if this is an issue we would want to address here, but I think the calculations on when to split into secondary actions gets interfered with. Under some widths, the right "widen pane" button gets cut off by the database picker. This doesn't happen in play under the same width, it splits to the kebab menu as expected. 
issue1

This is an issue both here and play, but the following is a very minor, edge case UI bug I noticed
1. In split view with the secondary action kebab button on both panes, open right pane's kebab menu
2. On the left pane, click the kebab menu and select close
3. In this single pane view, click split. The left pane's kebab menu will initialize as open

**Comment by staton-hyse11** [comment]
@gelicia It might be best to pull that into a separate issue so it can get addressed. That is focusing on something different than this PR

**Comment by diegoadams** [comment]
I like the new active states, they seem tidier than the outline border. The only suggestion I have is on the Explore time range sync ButtonGroup. 

As the primary on/off state of this function relies on the link icon, perhaps we could emphasise the icon further, thereby making it more evident that the control of the action resides here in the highlighted colour.

We could apply this logic to similar patterns to this. 

Screenshot 2023-06-22 at 12 48 12 PM

**Comment by diegoadams** [comment]
@Elfo404 , is something like this what you meant?
Screenshot 2023-06-22 at 12 56 34 PM

**Comment by ifrost** [comment]
> @gelicia It might be best to pull that into a separate issue so it can get addressed. That is focusing on something different than this PR

But that makes it looks sloppy. Why can't we fix it right away?

**Comment by staton-hyse11** [comment]
> > @gelicia It might be best to pull that into a separate issue so it can get addressed. That is focusing on something different than this PR
> 
> But that makes it looks sloppy. Why can't we fix it right away?

I figured keeping this focused on styling and another implementation would keep things tidy — that's all. By all means, do whatever is best.

**Review by Elfo404 — APPROVED** [review]
we wanted to change this for a while and i def think this is an improvement 👍 

@diegoadams let's create a follow up issue for that specific styling issue and analyze it there, we may also decide this looks ok as it is

@gelicia i think it's unrelated to this change (or the toolbar in general) but to the new ds picker instead. in play we use the old one still. I'll create a follow up issue for that. EDIT: opened https://github.com/grafana/grafana/issues/70598

**Comment by catherineymgui** [comment]
Thanks Torkel! I appreciate the consideration for component consistency.

Since my user testing was on the pill w/ the full border, it's hard to say if having the bottom border would work just as well.

However, I do have concerns on having just a bottom border vs a full border for the pill (I know @staton-hyse11 also mentioned this). One sided border on a pill isn't really seen as a common pattern (most other design systems use full border / background colour or both). I worry that this would be confusing.

**Comment by torkelo** [comment]
@catherineymgui confusing?  I would think that it would be a lot more confusing mixing too very similar active state designs.

I highly doubt that it would be confusing. Maybe not look like the most common design, very hard to find any norm here, I can't find many FilterPill designs, those I do find use background + icon for the active state, can't find any that use border. but maybe this component is named something else in other design systems. 

But since we have this pattern already and theme token I figured it would be nice to reuse the pattern and get the consistency and simplicity it would bring.

**Comment by catherineymgui** [comment]
Hm you're right that most pills change background. Here's a couple examples of components that change border colour for the active state (but they had borders in the default state as well):
https://paste.twilio.design/components/form-pill-group
https://primer.style/design/components/token/figma

The reason why we wanted to add a border to begin with was that when performing user testing for the new transformations redesign - users were skipping over the filters.

I think the component theme makes sense! But could we add another color? ( #FF780A if we're taking it from the old orangeDark theme?)

**Comment by torkelo** [comment]
@catherineymgui pushed an update that adds a new theme color token (theme.colors.action.selectedBorder). I used the current orange color we have for v8 theme (#FF9900), same color used for token theme.colors.warning.main , this orange color is the same in both light and dark theme (color palette names are palette.orangeDarkMain and palette.orangeDarkLight)

**Comment by torkelo** [comment]
forgot to attach screenshots: 

Screenshot from 2023-07-06 08-55-52
Screenshot from 2023-07-06 08-56-22

Can't say I am super happy with the esthetics (not linked to the border specifically), just something with the FilterPill that looks amateurish/ugly , think the shape, icon (and colored border) adds to that feeling but can't figure out a way right now to make it look more clean & professional

**Comment by catherineymgui** [comment]
Thanks @torkelo! I think this is one of the cases where the filter pill may not be the right pattern, since it's more of a multiselect than a filter.

**Pull request merged**
