### PR TITLE
Live: channel leader node for highly-available streaming from plugins

### PR DESCRIPTION
**Pull request by FZambia**
## Problem

Currently we have a half-working solution for HA Grafana setup when streaming from plugins. We send updates to local Node subscribers only. Thus several Grafana nodes can have stream open between Grafana and plugin.

But this is a bit hacky and will ruin when:

* we introduce Live pipeline – since in this case pipeline logic may be executed many times on different Grafana nodes
* we introduce remote plugins – since plugin instance can get two or more RunStream requests to the same channel

## Proposal

The only way we see to solve everything is make sure that there is only one stream for a certain channel exists across all Grafana nodes.

## Implementation

This pr contains a feature-toggle protected (`live-channel-leader`) implementation of channel leader selection using Redis to keep leadership information. The algorithm used here is similar to technique described in https://redis.io/topics/distlock in general.

Integration tests located here: https://github.com/grafana/grafana-live-integration-tests

Design document: https://docs.google.com/document/d/18yA449e6MAO-8OOEaW_VBeq6qT3TuY9OuhS2VKr-IRM/edit

After the review, some things should still be finished:

1. Pin to tagged Centrifuge
2. Pin to tagged Centrifuge-js
3. Optimize Lua script execution by using EVALSHA

Also, in the current implementation with a single node Redis there is a chance that 2 streams for the same channel will run for some time. We think this is acceptable, and may be improved using Redlock with N Redis masters.

Another possible improvement is to avoid channel leadership check on every packet coming from plugin. We can do checks and cache TTL – but seems like an optimization for the future.

### CODE REVIEW

**Comment by ryantxu** [comment]
9.0.0 :rofl:

**Comment by sdboyer** [comment]
Just seeing this for the first time, so have only skimmed docs. Some immediate OTTOMH questions:

Is the problem space here more amenable to at-most-once or at-least-once message delivery?

> The algorithm used here is similar to technique described in https://redis.io/topics/distlock in general.

Are we rolling our own distributed locking algorithm? If so, why?

Of the available distributed locking algorithms, why redlock?

And, similar to, or a faithful implementation of redlock as antirez designed it?

i recall when antirez put redlock out, and there was a furor in the distsys world. Kleppmann did [an analysis suggesting it is unsafe in some circumstances](https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html) (which antirez links to at the bottom, as well as his rebuttal).

**Comment by FZambia** [comment]
@sdboyer thanks!

> Is the problem space here more amenable to at-most-once or at-least-once message delivery?

We want at most once. But as mentioned in pr description we still see the possible corner cases when duplicate streams can work in parallel for some time. For our tasks this seems acceptable at the moment. But of course would be ideal to avoid. It seems to me that with N Redis masters we can avoid this – but we are not using N masters yet.

> Are we rolling our own distributed locking algorithm? If so, why?

I think the only reason to stick with Redis lock is the absence of common third-party solution or built-in solution for OSS Grafana which we can recommend to install (Consul? Etcd?). So I thought sticking with Redis could be a reasonable thing for the first approach.

> And, similar to, or a faithful implementation of redlock as antirez designed it?

This is a version for a single node Redis (maybe with replication) of locking with the downsides described in https://redis.io/topics/distlock. Redlock involves several Redis masters for concensus – but as I mentioned above we are not using it yet.

> Kleppmann did an analysis suggesting it is unsafe in some circumstances (which antirez links to at the bottom, as well as his rebuttal).

Thanks, I'll read the analysis and disagreement from Antirez. But even if Redlock is not safe in 100% case - do we have a better alternative to stick with at the moment?

**Comment by FZambia** [comment]
If we had Grafana nodes connected with Raft and primitives on top of that (like locks and possibility to transfer requests to the object leader)– so that we could not avoid requiring third-party server for this – things could be much more straightforward to implement. But this seems like a massive investment..

**Comment by marefr** [comment]
> If we had Grafana nodes connected with Raft and primitives on top of that (like locks and possibility to transfer requests to the object leader, seems we need multi-raft)– so that we could avoid requiring third-party server for this – things could be much more straightforward to implement. But this seems like a massive investment..

Would embedding nats potentially solve this?

**Comment by sdboyer** [comment]
> Would embedding nats potentially solve this?

nats was also my first thought. Not recommending, just saying it was my first thought.

Will ponder on other points from @FZambia and respond

**Comment by FZambia** [comment]
As you know I already tried to embed Nats + Jetstream during hackathon - in https://github.com/grafana/grafana/pull/36403 - it works and provides a way to push events into a stream, so that consumers get at least once guarantee but I don't really see how it can help us for the task here. Because what we need here is transfer subscription requests to the channel leader and maintain single stream between Grafana and plugin throughout all Grafana nodes. I don't think it's possible to do on top Jetstream. Or maybe I just can't wrap my head around.

Or do you mean embedding Nats without Jetstream? In this case we won't get Raft if I remember right (only full mesh and a way to communicate between nodes) - this is very similar to Redis at the end and we will need to implement consensus and various primitives ourselves on top of it.

**Comment by FZambia** [comment]
There is https://github.com/lni/dragonboat which seems interesting, it provides multi-raft and seems more close to what I've meant when saying about Raft - so maybe if we embed it then we can pass subscriptions to state machine and thus make sure streams established on channel leader nodes. Not sure though – requires time to dive into.

**Comment by marefr** [comment]
> As you know I already tried to embed Nats + Jetstream during hackathon - in #36403 - it works and provides a way to push events into a stream, so that consumers get at least once guarantee but I don't really see how it can help us for the task here. 

Yes I know you did. I don't have any answers, but my idea was something like this. Given nats (or something else) running embedded in each Grafana instance - when a request comes in to a Grafana instance for initiating some live stream, initiate the stream with backend plugin and push a broadcast message to all Grafana instances informing about active stream/leader. All streaming data will be sent to nats and broadcasted to subscribers (Grafana instances) which can push things out via  websocket without HA requirement. Not sure if this makes sense with Live pipeline or what that actually means - that streaming data updates can come in to any Grafana node? 

> Because what we need here is transfer subscription requests to the channel leader and maintain single stream between Grafana and plugin throughout all Grafana nodes. I don't think it's possible to do on top of Jetstream. Or maybe I just can't wrap my head around.

If we can route the request via nats to the channel leader it should work in my head. Obviously haven't looked into the details.

**Comment by FZambia** [comment]
> All streaming data will be sent to nats and broadcasted to subscribers (Grafana instances) which can push things out via websocket without HA requirement.

This already works this way for non-plugin streams. But over Redis instead of Nats at the moment. We can replace Redis to Nats for such broadcasting - and this should not be a problem (already had this working but rejected the idea since Redis seems fine too and does not introduce additional configs).

But the issue we are trying to solve here is that plugin streaming requests can come to any Grafana node, we want to make sure only one stream from plugin is running throughout all Grafana nodes. Currently it's not true. We can have some side effect logic inside stream processing - in this case having duplicate streams on different Grafana nodes is not a good thing as we will always have to think about de-duplicating data. That's why channel leader concept seems what we need.

**Comment by marefr** [comment]
> But the issue we are trying to solve here is that plugin streaming requests can come to any Grafana node, we want to make sure only one stream from plugin is running throughout all Grafana nodes. Currently it's not true. We can have some side effect logic inside stream processing - in this case having duplicate streams on different Grafana nodes is not a good thing as we will always have to think about de-duplicating data. That's why channel leader concept seems what we need.

Yes, I had this in mind with by earlier example, but a bit hard to explain. These requests comes in via websocket today, right? If request comes in we can create a new nats subscriber for specific stream, if it doesn't exist on that specific Grafana instance. Data streaming from plugin on one Grafana instance can broadcast the data over nats which will send it to all consumers (grafana instances).

Side note: Just noticed that nats jetstream has a builtin [Key/Value store](https://docs.nats.io/nats-concepts/jetstream/key-value-store) now.

**Comment by sdboyer** [comment]
i'd strongly prefer, to the point of blocking, that we pull together a list of the cases we have for various classic distributed systems decision problems and select a single approach that we believe can reasonably accommodate all of them. My initial position is to be considerably more concerned with the complexity involved in operating such systems - and therefore the cost of having more than one - than i am with the complexity of addressing any individual problem by having to work atop something that may not do exactly what we want, right out of the box.

The premise that led to the creation of [Chubby](https://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf) is that the simplest primitive on which to build is locking. Our context differs in that we can't assume the universal existence of a persistent store within our system topology in the same way. That might render the analogy useless, but it's still where i'd start thinking from.

If possible, we should design our approaches to problems such that only ephemeral state needs to be coordinated between nodes. i.e., if a Grafana cluster dies, the state of coordination between the nodes is gone. On restarting the cluster, if a distributed task needs to be picked back up, then nodes re-coordinate on whatever the task is based on some state they observe in canonical, persistent storage. If attainable, this property would mean any distribution communications could not take away the property of Grafana being [crash-only software](https://www.usenix.org/conference/hotos-ix/crash-only-software)). If we don't do it, we risk creating subtle dependencies between the state of multiple persistent storage layers, and that's where the dragons are.

That doesn't preclude the use of JetStream - restricting ourselves to the use of it in memory-backed mode will enforce (albeit with a big, kludgy hammer) crash-only. And it does seem plausible to me, prima facie, that K/V should be sufficient for providing a locking primitive.

**Comment by FZambia** [comment]
@marefr 

> If request comes in we can create a new nats subscriber for specific stream, if it doesn't exist on that specific Grafana instance. Data streaming from plugin on one Grafana instance can broadcast the data over nats which will send it to all consumers (grafana instances).

In this case we will have a way to deliver a message to all Grafana nodes and thus to all subscribers on all nodes. But we already can do this. The problem we are solving here is the need to maintain only one instance of GRPC stream between Grafana and plugin in a distributed environment. Sorry, maybe I just don't get the idea with raw Nats - but for me it's almost the same we currently have with Redis.

> Side note: Just noticed that nats jetstream has a builtin Key/Value store now.

That seems interesting! I have not seen it before - maybe it will allow us to built primitives on top. But Jetstream is not a lightweight dependency and I had non-obvious panics on Grafana start when embedded it last time. Sure some of them fixed till this point, but we still risk to introduce a pretty heavy-weight dependency with hard-to fix issues. In this perspective Redis is just much simpler to reason about.

@sdboyer 

Well, we see various challenges in different areas of Grafana in HA setup, some I know about are:

* General Live streams - we are using Redis PUB/SUB to deliver events to all nodes 
* Live plugin streams - need to maintain single entity to not care about de-duping data in external systems (this pr)
* Alerting squad de-dupes on alertmanager data data coming from alert schedulers all running simultaneously on different nodes and uses gossip protocol to communicate things between nodes
* Dashboard previews require cron-like scheduler also and ideally only run one instance on it, sth like having built-in a periodic job queue service - I think this is also very related.

Since the pr here does not add new dependencies and protected by a feature toggle – can we proceed with it somehow so that we have it available in the code base, but with the conclusion that we are starting a separate discussion about common approach for HA setups. We won't remove the feature toggle and release this until we have a decision on that approach. Just  don't want the work here stayed far behind main branch and we could evolve keeping this work in mind.

**Comment by sdboyer** [comment]
>  so that we have it available in the code base

If we don't intend to release without having reached consensus on a common approach and common abstraction, then there's obviously a limit on how far anything depending on this can go. What benefit are you expecting to derive from letting it exist in feature limbo?

**Comment by FZambia** [comment]
This solution is pretty simple and while not being optimal could allow us evolve keeping leadership in mind. But I understand your point – let's come to the consensus on approach before proceeding with this.

**Comment by sdboyer** [comment]
@FZambia i appreciate it! i don't think it necessarily needs to be a huge process.

**Pull request closed without merging**
