### PR TITLE
Toggletip: Add ability to set maxWidth

### PR DESCRIPTION
**Pull request by adela-almasan**
As part of the WIP DashGPT project, we needed a wider toggletip to acomodate the current design.
PR for visibility of changes.

Screenshot 2023-10-02 at 3 43 28 PM

Extracted from https://github.com/grafana/grafana/pull/75204

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by nmarrs — COMMENTED** [review]
It seems like this change is adversely impacting other places that we use the toggletip 🤔

perhaps the solution here is to make the `maxWidth` attribute settable via an optional prop with the default fallback being the original `400px`?  

E.g. `NeedHelpInfo.tsx` in alerting
Main
Screenshot 2023-10-02 at 4 59 48 PM


This branch

Screenshot 2023-10-02 at 5 00 46 PM

It looks like toggletip is used in the following areas:
[NeedHelpInfo.tsx](https://github.com/grafana/grafana/blob/68a6b2477f93d20c88f8b898a4bf59848ffc54d5/public/app/features/alerting/unified/components/rule-editor/NeedHelpInfo.tsx#L17)
[QueryOptions.tsx](https://github.com/grafana/grafana/blob/68a6b2477f93d20c88f8b898a4bf59848ffc54d5/public/app/features/alerting/unified/components/rule-editor/QueryOptions.tsx#L34)
[Math.tsx](https://github.com/grafana/grafana/blob/68a6b2477f93d20c88f8b898a4bf59848ffc54d5/public/app/features/expressions/components/Math.tsx#L39)
[MetricsModel.tsx](https://github.com/grafana/grafana/blob/68a6b2477f93d20c88f8b898a4bf59848ffc54d5/public/app/plugins/datasource/prometheus/querybuilder/components/metrics-modal/MetricsModal.tsx#L237)

**Review by nmarrs — APPROVED** [review]
LGTM

**Review by JoaoSilvaGrafana — CHANGES_REQUESTED** [review]
You can achieve almost the exact same if you just set `fitContent` to `true`, so I don't think we need this extra prop 😅 

If there is any other nuance to this let me know, but I don't think this PR is needed.

**Comment by adela-almasan** [comment]
oops, we wasn't aware of that, thanks @JoaoSilvaGrafana!

**Pull request closed without merging**
