### PR TITLE
Variable: removed __user.name/___.user.email from global variables and added docs for the rest of the __user variable.

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
After merging https://github.com/grafana/grafana/pull/23378 into master I opened this PR to add documentation of the added variable.

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM! ⭐

**Comment by allomorphy** [comment]
Hi mckn,

This is super 🤩 . Thank you and to  @aidanmountford 
Is this the correct use in the query:
`SELECT value FROM dxdata WHERE deviceOwner='${__user.email}'`

image

If I put the literal email into the query, then I see the data.
How to I expand the variable? 
Surely, I am missing something 
PS. In my iterations -- trying everything I could think of -- I managed to get the variable S__dashboard to expand in the Query Inspector (to the dashboard ID of course). But I cannot reproduce that again! 🙃 

Thanks for this feature and for your help.

**Comment by mckn** [comment]
> Hi mckn,
> 
> This is super 🤩 . Thank you and to @aidanmountford
> I am using `Grafana v7.1.0-db3b38efpre (467348bded)` from the container image with the `master` tag
> 
> Is this the correct use of the variable in the query:
> `SELECT value FROM dxdata WHERE deviceOwner='${__user.email}'`
> 
> image
> 
> If I put the literal email into the query, then I see the data.
> How to I expand the variable?
> Surely, I am missing something
> PS. In my iterations -- trying everything I could think of -- I managed to get the variable `$__dashboard` to expand in the Query Inspector (to the dashboard ID of course). But I cannot reproduce that again! 🙃
> 
> Thanks for this feature and for your help.

Hello :)

We actually removed the `__user.email` until we found a good usecase for it to be added. But at the same time the login would probably be the email. So does it work better if you use the `${__user.login}`

**Comment by allomorphy** [comment]
Thanks and that was quick :)
Silly and careless me, of course, I followed your thread.
Halleluljah ... I should have callled for help sooner.
Love this. thanks mckn 
image

**Comment by mckn** [comment]
> Thanks and that was quick :)
> Silly and careless me, of course, I followed your thread.
> Halleluljah ... I should have callled for help sooner.
> Love this. thanks mckn
> image

Haha, I am happy to help! Thanks for reaching out and giving feedback on this 🙌

**Comment by allomorphy** [comment]
I was looking for weeks for this feature and also posted my quest to the forum.
then I just checked now before giving up (and implementing some hack with statically generated provisioned dashboards to give the same effect) and I saw your commit -- delayed by what your CEO calles CDD ;-) -- of yesterday.
This is JIT development.
Please checkout what we are using it for : https://meterbolic.org?voucher=r3t3mresew0n&email=eric.smith@trustfood.org

Made a good launch and big plans for Grafana at the cutting edge.

BTW, single quotes required around the variable to protect the `@`

**Comment by allomorphy** [comment]
Hi again @mckn 

It seems that there is some flakiness with the expansion of the variable.
I can reproduce it by on a fresh login, the variable expands and produces data in the query analyser.
However the data falls outside the time range of the dashboard and the dashboard now has a button with "Zoom to data".
When I press that button, then it says "no data".
Then the expansion of the varable is broken in Query Analyser.

Curious if you find this as well 🤔 

If I discover anything else, then I will report.

**Comment by hugohaggmark** [comment]
@allomorphy can you report that last issue as a separate issue with reproducible steps? I'm afraid your issue will be lost in this thread otherwise.

**Comment by allomorphy** [comment]
Sure @hugohaggmark , I did it https://github.com/grafana/grafana/issues/25359#issue-630704788
I hope that you are able to reproduce easily (and address it too 😊 ).
Happy to help.

**Comment by hugohaggmark** [comment]
> Sure @hugohaggmark , I did it [#25359 (comment)](https://github.com/grafana/grafana/issues/25359#issue-630704788)
> I hope that you are able to reproduce easily (and address it too 😊 ).
> Happy to help.

Thank you so much for taking the time doing that @allomorphy 🌟

**Comment by garyyang85** [comment]
> > Hi mckn,
> > This is super 🤩 . Thank you and to @aidanmountford
> > I am using `Grafana v7.1.0-db3b38efpre (467348bded)` from the container image with the `master` tag
> > Is this the correct use of the variable in the query:
> > `SELECT value FROM dxdata WHERE deviceOwner='${__user.email}'`
> > image
> > If I put the literal email into the query, then I see the data.
> > How to I expand the variable?
> > Surely, I am missing something
> > PS. In my iterations -- trying everything I could think of -- I managed to get the variable `$__dashboard` to expand in the Query Inspector (to the dashboard ID of course). But I cannot reproduce that again! 🙃
> > Thanks for this feature and for your help.
> 
> Hello :)
> 
> We actually removed the `__user.email` until we found a good usecase for it to be added. But at the same time the login would probably be the email. So does it work better if you use the `${__user.login}`

Hi why did we disable this posiability __user.name or __user.email.   I need to filter some dashboard options by email with grafana built-in variable, but seems this was disabled intentionally.  🙃

**Comment by mckn** [comment]
> > > Hi mckn,
> > > This is super 🤩 . Thank you and to @aidanmountford
> > > I am using `Grafana v7.1.0-db3b38efpre (467348bded)` from the container image with the `master` tag
> > > Is this the correct use of the variable in the query:
> > > `SELECT value FROM dxdata WHERE deviceOwner='${__user.email}'`
> > > image
> > > If I put the literal email into the query, then I see the data.
> > > How to I expand the variable?
> > > Surely, I am missing something
> > > PS. In my iterations -- trying everything I could think of -- I managed to get the variable `$__dashboard` to expand in the Query Inspector (to the dashboard ID of course). But I cannot reproduce that again! 🙃
> > > Thanks for this feature and for your help.
> > 
> > 
> > Hello :)
> > We actually removed the `__user.email` until we found a good usecase for it to be added. But at the same time the login would probably be the email. So does it work better if you use the `${__user.login}`
> 
> Hi, why did we disable this posiability __user.name or __user.email? I need to filter some dashboard options by email with grafana built-in variable, but seems this was disabled intentionally. 🙃

We want to limit the amount of data exposed about the user as much as possible. Have you tried to use the suggested `${__user.login}` variable?

**Comment by yunusemrecatalcam** [comment]
Hey from the future, 
I have tried but it does not work. Did you guys removed all the user data variables?
I think this is an important feauture, thanks! @mckn

**Comment by hugohaggmark** [comment]
@yunusemrecatalcam have you tried to use the suggested ${__user.login} variable? If you're still experience issues I suggest that you open a new issue with reproducible steps with that which is not working because it's really hard for us to solve anything with just your comment.

All the best

**Pull request merged**
