### PR TITLE
API: adds redirect helper to simplify http redirects

### PR DESCRIPTION
**Pull request by xlson**
**What this PR does / why we need it**:

Makes http redirects in Grafana more clean in the backend code.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by xlson** [comment]
Not sure if we need the capability to set the status code, in my experience, it's very rare to do anything but a 302 redirect so I skipped it to simplify usage.

**Review by marefr — APPROVED** [review]
LGTM

There's a few places in the code using custom response status, but it can easily be added later if needed :+1:

**Comment by xlson** [comment]
@marefr do you have an example of that use case?

**Comment by marefr** [comment]
@xlson Here for example setting a 301 in the response: https://github.com/grafana/grafana/blob/master/pkg/middleware/validate_host.go#L24

**Comment by xlson** [comment]
But we can't use our api-helpers in that method right? Or can we?

**Comment by marefr** [comment]
Yeah that's a good point! Sorry :smile:

**Comment by xlson** [comment]
np :)

**Pull request merged**
