### PR TITLE
[cr] whitelist flexbox styles in text panel editor

### PR DESCRIPTION
**Pull request by jewbetcha**
In an effort to allow for more customization in dashboards, as a first step we can whitelist flexbox styles to pass through HTML sanitization. Previously, the whitelist defaults would filter out/default many commonly used flex styles.

A possible next step (if folks are interested) could be allowing for a `<style>` tag inside the editor to create classes, and inline the styles during sanitization.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey @jewbetcha , I took a look at this PR, and codewise looks good 🙌🏾 , there was one minor thing that I found while giving it a spin, in Markdown mode, not all the flex properties are passed, is it the expected behavior

https://user-images.githubusercontent.com/239999/146750145-fc327212-e414-4561-9cde-ae62d1342bcc.mp4

?

**Comment by jewbetcha** [comment]
Updated with a separate `renderMarkdown` function for the text panel. I experimented with adding another argument to the existing `renderMarkdown` to determine which sanitize function to use, but it's pretty widely used already so I figured separating would be safest (despite a bit of code repetition). Open to either though :)

**Review by axelavargas — APPROVED** [review]
Great job @jewbetcha 🙌🏾

**Comment by jewbetcha** [comment]
🙌 🙌 🙌

**Pull request merged**
