### PR TITLE
Fix dead key issue in slate

### LINKED ISSUE #29080: Explore: Issues writing LogQL queries using international keyboard layout
**What happened**:
I've recently started noticing a weird behavior when writing LogQL queries around quotes using the `U.S. International - PC` keyboard layout on mac:

Kapture 2020-11-12 at 15 02 10

Note that it only manifests within the "log pipeline" portion of the query. It works as expected when working within the "log stream selector" section.

I've not been able to replicate this using a different keyboard layout.

**How to reproduce it (as minimally and precisely as possible)**:
1. Switch to the `U.S. International - PC` keyboard on a Mac
2. Open Explore & type `{name="test"} |= "`.
3. The query editor should now start to misbehave.

**Environment**:
- Grafana version: 7.3.x
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS/Chrome (International keyboard)

### LINKED ISSUE #31968: Dead-key behaviour break query editor
**What happened**:
I'm unable to type in query characters like `~`. There is some bad character making some sort of offset and the cursor does  not appear where it should be. 

**What you expected to happen**:
The tilde is inserted correctly and there is no offset.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query on Macos where you need a regex on a label. Press space to insert it. Try to edit the regex, the characters are not inserted on the cursor but 2 characters behind.

**Anything else we need to know?**:
It is probably related to dead-key behavior when you need to press another key to insert it. 
Found one post about it : https://community.grafana.com/t/cannot-type-deadkey-tilde-into-query-editor-on-macos/37154

**Environment**:
- Grafana version: v7.4.3 (010f20c1c8)
- Data source type & version: Loki / Prometheus (Loki) 
- OS Grafana is installed on: Docker grafana/grafana ID fe0c28e2beb32c36b0dee9f0f1df9250b9cb66a713a434f2bd6f3127438042e7 on Ubuntu 20.04
- User OS & Browser: MacOS 11.2.2 (20D80) on Firefox Developer Edition 87.0b8
- Grafana plugins: ~ 
- Others:

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

Update `grafana/slate-react` that include a fix for the dead key behaviour. To reproduce the issue you need to type a dead key (in macos a key that has an orange border) after a decorated (one that is syntax highlighted) character.
Screenshot 2021-04-29 at 21 17 58

This is still an issue in the slate editor itself see https://github.com/ianstormtaylor/slate/pull/3205

**Which issue(s) this PR fixes**:

Fixes #31968
Fixes #29080

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aocenas** [comment]
I am not sure if I have a way to test this. I thought I could reproduce it on master with Slovak layout where you have to input alt+shitf+1 or ~ key to insert the tilde:
Screenshot from 2021-05-04 16-16-35

First on master it inserted tilde and then removed it after I tried to write something else. Then on this branch behavior I get is a bit strange because if I try to insert tilde with the left most key it works if I try with the `1` key I have to press it 2 times even though they both need alt+shift :man_shrugging:. Now though when I go back to master I actually get correct behavior, no disappearing character or need for double press so not sure what is going on, don't have any changes in work dir but feel like ubuntu is acting up on me somehow.

@ivanahuckova can you also check this on mac whether you can test this in better way?

**Review by ivanahuckova — COMMENTED** [review]
I have tested this out and this PR:
- Fully fixes the dead key behaviour
- Mostly fixes issues writing LogQL queries using international keyboard layout. There is still one issue - when you write `"` after `|=` the cursor position is incorrect - it ends up before the `"`. However, it works correctly with second `"`. Not sure if there is anything we can do about it. 

https://user-images.githubusercontent.com/30407135/117131285-881eec80-ada1-11eb-8b2f-b7766c4b6df0.mov

**Comment by aocenas** [comment]
@ivanahuckova
> Mostly fixes issues writing LogQL queries using international keyboard layout. There is still one issue - when you write " after |= the cursor position is incorrect - it ends up before the ". However, it works correctly with second ". Not sure if there is anything we can do about it.

is that a regression? If that is separate issue that was there before, lets merge this fix and handle this one separately.

**Comment by ivanahuckova** [comment]
Not a regression. :) Just thought i would mention it. Approving PR.

**Review by ivanahuckova — APPROVED** [review]
Nice work Zoltan!

**Pull request merged**
