### PR TITLE
fixing up init script exit codes

### PR DESCRIPTION
**Pull request by tmonk42**
http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

Also added the "UID 0" check to rpm init script (was in deb already)

### CODE REVIEW

**Comment by tmonk42** [comment]
Addresses #2106

**Comment by tmonk42** [comment]
Updated to remove trailing exit 0 from deb init script, matching cleanup that was done for rpm init script in https://github.com/grafana/grafana/pull/1854

**Comment by torkelo** [comment]
Nice!  looks great, Thanks!

**Comment by tmonk42** [comment]
Any chance this can get added into 2.0.3 and get that packaged and released?

**Comment by torkelo** [comment]
@tmonk42 not sure if I have time to prepare a patch release, flying out to the states for next week (Monitorama conference), and when I get back I will focus on getting 2.1 out

**Pull request merged**
