### PR TITLE
Dashboard: Remove old panel code and leave only new panel design

### LINKED ISSUE #70790: Dashboard: Remove `newPanelChromeUI` feature flag
In Grafana, we've rolled out a new panel header for our panels. Initially, these changes were behind the `newPanelChromeUI` feature flag. However, following substantial discussion and positive feedback, we've decided it's time to remove the feature flag and make this new panel header available to all Grafana users.

```[tasklist]
### Tasks
- [x] Remove old code that the old panel header was using
- [x] Update e2e and unit tests as needed
- [x] Ensure this change is introduced in a major or minor version
```

```[tasklist]
### Leftover tasks
- [ ] Remove not used anymore `ErrorIndicator` from grafana/ui
- [ ] Remove `loadingBar()` e2e-selector if not used
- [ ] Refactor the `PanelEditorTableView` component to utilize the new properties of `PanelChrome`
```

```[tasklist]
### Testing tasks
- [ ] Add e2e test: interacting with panel menu
- [ ] Add e2e test: interacting with panel header links, description, time range
- [ ] Add e2e test: interacting with panel error
- [ ] Add e2e test: interacting with panel drag-n-drop with and without header
- [ ] Add e2e test: interacting with panel notices (graphite DS)
- [ ] Add e2e test: interacting with panel streaming data
- [ ] Add e2e test: interacting with panel hovering header
```

### PR DESCRIPTION
**Pull request by polibb**
**What is this feature?**

- Remove the `newPanelChromeUI` feature flag that we have already enabled by default.
- Remove old code that the old panel header was using: `PanelHeader`, `PanelHeaderLoadingIndicator`, `PanelHeaderMenuTrigger`
- Leave whichever components from the old panel are used elsewhere, but move them to the places they are used, instead of leaving them where it's not relevant for them anymore:
`PanelHeaderMenuItem` is only used by `PageHeader`, hence moved there
`PanelHeaderCorner` is only used by `PanelEditorTableView`, hence moved there
- Removed components that had corresponding components with the word "New" in them, as the latter will be the only ones now: ~`PanelHeaderMenuWrapper`~ -> `PanelHeaderMenuWrapperNew`, ~`PanelHeaderMenu`~ -> `PanelHeaderMenuNew`

**Why do we need this feature?**

Because we are not supporting the old panel setup and should have only the new one in place.

**Who is this feature for?**

Grafana users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/70790

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

# Release notice breaking change

<Breaking change description>
Removed all components for the old panel header design.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Great progress on this PR, @polibb! 🙌🏾 I took a look and noticed something else we might need to address.

It appears that we overlooked refactoring the `PanelEditorTableView` component to utilize the new properties of `PanelChrome`. Currently, "PanelHeaderCorner" is being used to display errors, but this is the old approach. Additionally, there is some blank space.

P.S Also I don't understand the levitate breaking change 🤔 

https://github.com/grafana/grafana/assets/239999/ef8da56a-f3ad-4010-9c9e-59c302d0c227

**Comment by polibb** [comment]
Thank you for checking it out, @axelavargas! I did notice that we haven't updated the PanelEditorTableView, but thought this was our plan for some reason - that the table has a life of its own 😄. Anyway, I will look into it to update it. Could we do it in a separate following PR? If yes, I'll add it to the leftover tasks: https://github.com/grafana/grafana/issues/70790. 
The breaking change is the removed FF, is that not how it usually goes with removing feature flags?

**Comment by polibb** [comment]
Hello there, @grafana/plugins-platform-frontend 👋. Would you help me understand how to move past the breaking-changes failing check on this PR? Is it because I'm aiming a minor version of Grafana, and I should be aiming at a major one with a breaking change in the PR? 
> We can make breaking changes less painful if they are only happening between major releases of Grafana.

**Comment by axelavargas** [comment]
> Thank you for checking it out, @axelavargas! I did notice that we haven't updated the PanelEditorTableView, but thought this was our plan for some reason - that the table has a life of its own 😄. Anyway, I will look into it to update it. Could we do it in a separate following PR? If yes, I'll add it to the leftover tasks: #70790. The breaking change is the removed FF, is that not how it usually goes with removing feature flags?

Yes, we can do it in a separate PR :).

**Review by axelavargas — APPROVED** [review]

**Pull request merged**
