### PR TITLE
Monaco: Add javascript and typescript support

### LINKED ISSUE #38700: CodeEditor using javascript/typescript causes an error in the console
Currently the monaco editor integrated into Grafana has removed typescript types.<https://github.com/grafana/grafana/blob/bafe16368ae945f4627e445280a63f53e2cfcf7a/scripts/webpack/webpack.common.js#L85-L88> Which makes it hard to use types.
image

_Originally posted by @ZuperZee in https://github.com/grafana/grafana/discussions/38430_

### PR DESCRIPTION
**Pull request by ZuperZee**
**What this PR does / why we need it**:

This will make it possible to use typescript types (in Javascript and Typescript) for autocompletion without getting errors in the console.

**Which issue(s) this PR fixes**:

Fixes #38700 

**Special notes for your reviewer**:

The typescript files are not loaded to the browser until typescript or javascript is set in the CodeEditor language.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
I think this is fine.  Having out-of-the-box typescript/javascript is useful and the cost is not paid unless it is used.

The zipped size is ~800kb, uncompressed is 4mb (not 10!)
image

**Comment by mckn** [comment]
I spoke with @joshhunt and if I understood everything correct this should be loaded lazily. So the `404` you get is probably a result of failing to load it lazily.

Will this change bundle it into the app bundle or just add it to the dist so it can be lazily loaded?

**Comment by ZuperZee** [comment]
This will only be loaded to the browser when the language is set to javascript or typescript and the code editor is also loaded.

**Comment by ZuperZee** [comment]
> Will this change bundle it into the app bundle or just add it to the dist so it can be lazily loaded?
It will be added to the monaco folder.
image
Which is in public/lib/monaco.

**Comment by ZuperZee** [comment]
Easiest way to test it is to use the Text Panel and write script in the html. This will lazy load the tsMode and tsWorker.

https://user-images.githubusercontent.com/39485579/131644379-92647171-f4b9-4e0a-98c9-435b846622a3.mp4

**Comment by mckn** [comment]
@ZuperZee awesome, thanks for fixing this 🙌🏻

**Pull request merged**
