### PR TITLE
Implement a twilio alert notifier

### PR DESCRIPTION
**Pull request by Gui13**
Implements #13318 with tests.

This is a Twilio notifier that allows you to send SMS or MMS to a phone number, using your Twilio account.

Be gentle, this is my first dab in the Go language.

### CODE REVIEW

**Comment by torkelo** [comment]
Rebase on master should fix it

**Comment by Gui13** [comment]
Sadly it doesn't seem to be OK, I rebased just right now and it still fails.
It seems that my Gopkg.toml is not sufficient. Should I also update the Gopkg.lock ?

**Comment by torkelo** [comment]
Think it’s because of the dependency is not checked in under vendor.

Will sadly close this for now, we are not adding more notifiers (unless there is a big demand for one)

**Comment by Gui13** [comment]
Ok, I understand the maintenance burden.
Maybe think about adding a pluggable notifier plugin system, the same way you have pluggable data sources? This will let others take care of the maintenance for you.

Cheers!

**Comment by justinnamilee** [comment]
Darn, I really needed this!

**Comment by rafed-bs23** [comment]
This would be a really nice feature.

**Comment by safadig** [comment]
Would love to have Twilio added

**Pull request closed without merging**
