### PR TITLE
FieldValues: Use plain arrays instead of Vector (part 3 of 2)

### PR DESCRIPTION
**Pull request by leeoniya**
now for the fun part!

previously: https://github.com/grafana/grafana/pulls?q=is%3Apr+fieldvalues+is%3Aclosed+milestone%3A10.0.0

This PR updates core so we now use simple arrays rather than the Vector accessors

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Review by nmarrs — APPROVED** [review]
👀 a lot of changes - any concern here about things breaking that are not covered by existing tests? If build is working we should have some degree of confidence as any issue should be caught by static linting / compiling

**Review by torkelo — APPROVED** [review]
Looks good, looked at most files (causal 109 files) to double check, and did some manual clicking around testing some dashboards and explore. 

Seems to be working :)

**Review by svennergr — APPROVED** [review]
Loki & logs changes LGTM!

**Review by nmarrs — APPROVED** [review]
👀 lot of changes - any concern about this breaking things not covered by current tests? Feel like if local build / static linting is happy with these changes we should have some degree of confidence

**Pull request merged**
