### PR TITLE
What's New: Add image for the Loki Query Validation feature

### PR DESCRIPTION
**Pull request by matyax**
Adding an illustrating image to the Loki validation part in the document.

### CODE REVIEW

**Review by ivanahuckova — COMMENTED** [review]
In https://raintank-corp.slack.com/archives/CH34H23HD/p1674581630965619, it says that `New assets should only be uploaded under the https://grafana.com/media/` directory , but your image is under `static`. Could you change its location to under `media`. 

I used `/media/docs/grafana`.

**Comment by matyax** [comment]
@ivanahuckova I used this path becuse is what the rest of the changelog uses, and because https://grafana.com/media/img/logs/logs-loki-query-validation-whats-new-9-4.png.png doesn't work. I don't know how to interpret this, i.e. is it ok/expected that the URL doesnt work?

**Comment by ivanahuckova** [comment]
Where did you upload the image? It should be under the path where you uploaded it.

**Comment by matyax** [comment]
Completely missed the `media` folder. Moved there now.

**Review by ivanahuckova — APPROVED** [review]

**Pull request merged**
