### PR TITLE
Add a basic Tables component (multiple tables)

### PR DESCRIPTION
**Pull request by ryantxu**
This component is an extension to the Table component, but it supports a list of tables and you can select the one you want to see with a list of buttons along the bottom.  

Eventually something like google sheets:
image

The styles need help.  my CSS foo is not up to the task, but this lets you switch through all the table results.

Note -- there is only one table until: #15864

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure about this, seems to be a bit premature, maybe when the new table component is more mature and in use. What is the use case for this? similar to https://github.com/grafana/grafana/issues/13261 ?

**Comment by ryantxu** [comment]
It is for sure premature to be in any non-alpha component 100%.  And for sure needs help with styles, implementation.

The goal is to see the whole result from a query.  If we change the interface to return TableData[], I want to be able to see TableData[], not just TableData[0] or whatever

**Comment by torkelo** [comment]
For multiple tables I guess we would have to try to merge them into one :)

**Comment by ryantxu** [comment]
maybe...  and that is often a good way to do it, but would still like to know what they were before we merged.  Do we merge all the columns?  or join on some column value?  

This is really aiming to show the same thing that you see in excel/google sheets.

**Comment by ryantxu** [comment]
closing this since it is now considered part of #20709

**Pull request closed without merging**
