### PR TITLE
ValueMappings: Make value mapping row focusable

### LINKED ISSUE #46494: A11y : Cannot easily drag/reorder rows in Value Mappings modal via keyboard
**Steps to reproduce**:

try to reorder the rows inside the value mappings modal using only a keyboard. 

**Actual Result**:

It is possible but when the drag handle is active only the left button is in focus. 

**Expected Result**

workflow accessible for keyboard-only users

Might be more intuitive if the whole row was focused?

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by lpskdl**
**What this PR does / why we need it**:
Moved drag handle to the draggable container. This will make the value mapping row focusable which will improve accessibility for keyboard-users

**Which issue(s) this PR fixes**:

Fixes #46494 

**Special notes for your reviewer**:
- I removed the drag handle functionality from the  `dragglabledots` icon as this doesn't bring any value since the whole row is a drag handle itself already

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
This change looks good! I think the title should be something other than "Dimensions" though 🤔 maybe "A11y: ..."?

Also, while I was playing around with this to try it out I noticed that the whole keyboard usage of the value mappings is not great in other places. There are two other issues I found:
- When you press space to start dragging, you can keep tabbing onto other elements without ending the drag. Not sure how we can prevent this from happening, if we don't have any great ideas this is more minor.
- When you drop a row, the focus goes back to the index of the row when it started the drag... This happens in the parent component of the one with your change, but I think we could fix it as part of this. [This is the line](https://github.com/grafana/grafana/blob/main/public/app/features/dimensions/editors/ValueMappingsEditor/ValueMappingsEditorModal.tsx#L114) it happens (`key={index.toString()}`). I think we should try to fix this one to make the experience better. wdyt?

**Comment by lpskdl** [comment]
> This change looks good! I think the title should be something other than "Dimensions" though 🤔 maybe "A11y: ..."?
> 
> Also, while I was playing around with this to try it out I noticed that the whole keyboard usage of the value mappings is not great in other places. There are two other issues I found:
> 
> * When you press space to start dragging, you can keep tabbing onto other elements without ending the drag. Not sure how we can prevent this from happening, if we don't have any great ideas this is more minor.
> * When you drop a row, the focus goes back to the index of the row when it started the drag... This happens in the parent component of the one with your change, but I think we could fix it as part of this. [This is the line](https://github.com/grafana/grafana/blob/main/public/app/features/dimensions/editors/ValueMappingsEditor/ValueMappingsEditorModal.tsx#L114) it happens (`key={index.toString()}`). I think we should try to fix this one to make the experience better. wdyt?



> This change looks good! I think the title should be something other than "Dimensions" though 🤔 maybe "A11y: ..."?
>  ✅ I changed it to Accessibility
> Also, while I was playing around with this to try it out I noticed that the whole keyboard usage of the value mappings is not great in other places. There are two other issues I found:
> 
> * When you press space to start dragging, you can keep tabbing onto other elements without ending the drag. Not sure how we can prevent this from happening, if we don't have any great ideas this is more minor.
> I've check the `react-beautiful-dnd` library and so far they haven't exposed any events that we can use when focus is move to the child elements. This could be also solve with a custom solution but It could be tricky and a hacky-ish one.
> * When you drop a row, the focus goes back to the index of the row when it started the drag... This happens in the parent component of the one with your change, but I think we could fix it as part of this. [This is the line](https://github.com/grafana/grafana/blob/main/public/app/features/dimensions/editors/ValueMappingsEditor/ValueMappingsEditorModal.tsx#L114) it happens (`key={index.toString()}`). I think we should try to fix this one to make the experience better. wdyt?
> ✅ I was able to solve this by providing a unique id(thanks for the tip!) when generating the row data in the modal. Let me know if the solution is fine. Otherwise, im happy to change it. BTW, i used uniqueId of lodash , not sure if there are is an existing that we can use here

Both issues raised above were an existing ones and It become more obvious after adding the improvement 🙈

**Comment by JoaoSilvaGrafana** [comment]
Thanks for fixing that other issue even though it was already broken before, works great now 😄
I'm not sure why the title is not changelog accepted, Maybe it doesn't accept numbers? 🤷 I'd say if we change it I'd change the area to 'ValueMappings', what do you think?

**Review by JoaoSilvaGrafana — APPROVED** [review]
🎉

**Pull request merged**
