### PR TITLE
Security: Fix vulnerability GHSA-9763-4f94-gfch

### PR DESCRIPTION
**Pull request by pie-r**
This PR bumps github.com/cloudflare/circl to v1.3.7

Partially closes:
https://github.com/grafana/grafana/issues/80316

### CODE REVIEW

**Comment by pie-r** [comment]
Any chance to have this approved and merged?
@tolzhabayev @papagian @zserge

**Review by tolzhabayev — APPROVED** [review]

**Comment by tolzhabayev** [comment]
@pie-r thanks for taking care of that, I will let the pipelines run add the proper labels and milestones and merge once everything is good to go.

**Comment by djsly** [comment]
@tolzhabayev  when is the next expected release ?

**Comment by tolzhabayev** [comment]
@djsly we don't have fixed dates that we communicate. Probably somewhere around march.

**Comment by djsly** [comment]
Could we look into cherry picking into 10.3.X. We really need that vulnerability fixed and deployed asap :(. On Jan 22, 2024, at 5:11 PM, Timur Olzhabayev ***@***.***> wrote:﻿
@djsly we don't have fixed dates that we communicate. Probably somewhere around march.

**Comment by tolzhabayev** [comment]
> Could we look into cherry picking into 10.3.X. We really need that vulnerability fixed and deployed asap :(. On Jan 22, 2024, at 5:11 PM, Timur Olzhabayev ***@***.***> wrote:﻿ @djsly we don't have fixed dates that we communicate. Probably somewhere around march. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

it is now backported to 10.3.x branch but I can't tell when and if we are going to do a patch release yet.

**Comment by djsly** [comment]
thanks @tolzhabayev , at least there are two streams where a release could be made now, and hopefully 10.3.X will see a release before 10.4.X

**Pull request merged**
