### PR TITLE
Geomap: Legend and scale overlapping

### LINKED ISSUE #47398: Geomap: Legend and scale overlapping

### PR DESCRIPTION
**Pull request by adela-almasan**
Legend and scale were overlapping in the bottom left corner of geomap. This PR resolves that issue.

Screen Shot 2022-04-11 at 4 06 35 PM

Updated ---

https://user-images.githubusercontent.com/88068998/166483459-9dedc77a-4b49-4350-9cc7-32ffcc8486ac.mov

Fixes #47398

### CODE REVIEW

**Comment by ryantxu** [comment]
Another approach would be to move the legend "up" when scale exists 🤔 

The centered approach is OK, but will be weird when the windows is small

**Comment by adela-almasan** [comment]
> Another approach would be to move the legend "up" when scale exists 🤔

@ryantxu Yes, that's what I started with, but I felt like it was a bit crowded. I can change it if you think that would work better.

Screen Shot 2022-04-11 at 4 28 49 PM

**Review by nmarrs — APPROVED** [review]
I think the center approach looks / works great (more spaced out than stacking everything on top of each other).

One nit is that on smaller screen sizes the `absolute` styling easily breaks, though when we do start optimizing for smaller screen sizes we could just have a media query switch styling to have UI stack in the bottom left corner instead, so not sure this is a big deal for now until we systematically start targeting responsive design 🤷

**Comment by adela-almasan** [comment]
Updated to move the legend up when scale is displayed, as per the UX discussions.

**Review by nmarrs — APPROVED** [review]
LGTM

**Pull request merged**
