### PR TITLE
Loki: Bring back processed bytes as meta information

### LINKED ISSUE #33994: Loki: Bring back processed bytes as meta info
**What would you like to be added**:
Total bytes processed was removed in https://github.com/grafana/grafana/commit/1c838f58723e113f3fd546f859b20a33461cd4cb as this was considered temporary solution before we implement Inspector. However, based on feedback, this is valuable information for every query and therefore we should bring it back.

### PR DESCRIPTION
**Pull request by mmenbawy**
**What this PR does / why we need it**:

Bring back total bytes processed as meta info. It was removed 1c838f5. However, based on feedback it is a valuable information for every query.

**Which issue(s) this PR fixes**:

Closes https://github.com/grafana/grafana/issues/33994

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mmenbawy** [comment]
@ivanahuckova Any hints on why `public/app/core/logs_model.ts` is failing `prettier --list-different "**/*.{ts,tsx,scss}"`!
I've tried some changes but no luck, yet.

**Comment by ivanahuckova** [comment]
@mmenbawy you can run `yarn prettier:write` to fix all the linting errors.

**Review by ivanahuckova — APPROVED** [review]
Awesome! Works like a charm. Thank you for your contribution! 🧡

**Comment by mmenbawy** [comment]
> Awesome! Works like a charm. Thank you for your contribution!

The pleasure is all mine :pray:. Would be glad to help with other issues.

**Pull request merged**
