### PR TITLE
Units: add Nm/A

### PR DESCRIPTION
**Pull request by Maddin-619**
**What this PR does / why we need it**:

Adds the unit of the torque-constant

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dprokop** [comment]
@Maddin-619 thanks for contribution!

We will gladly merge this but before that, it would be good with a unit test for each new unit.

**Review by dprokop — CHANGES_REQUESTED** [review]
@Maddin-619 thanks for contribution!

We will gladly merge this but before that, it would be good with a unit test for each new unit.

**Comment by ryantxu** [comment]
After #20763, this will not be necessary anymore -- you can just type `Nm/A` in the unit picker

**Comment by torkelo** [comment]
We have just merged support for custom units, so this is no longer needed.
#20763

**Pull request closed without merging**
