### PR TITLE
Annotations: Fix keyboard a11y in Annotation list

### LINKED ISSUE #56564: PO: Unable to select existing annotation via keyboard
Note the outline skipping over the name of the annotation.
annotation-keyboard

### PR DESCRIPTION
**Pull request by yaelleC**
**What this PR does / why we need it**:

Currently the annotation name is not focusable so a keyboard user could not update an annotation:

This PR fixes that using a button to wrap the annotation name:

| Before | After | Variables tab (for comparison) |
| ------ | ------ | ------ |
| before-focus | Screenshot 2023-01-24 at 18 24 52 | after |

**Which issue(s) this PR fixes**:

Fixes #56564

**Special notes for your reviewer**:

1. I have no idea who the code owners are, feel free to assign other reviewers 😃 

2. For consistency with the template variable list (much more needed in the matter - delete button / reorder is different) I removed the comment icon. 

I don't mind adding it back if reviewers would rather we keep it. If so here are a few options we can use for focus:

| 1. icon + text | alt2 |
| ------ | ------ |
| 2. icon only | alt3 |
| 3. text only | alt1 |

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
I'm also not sure who owns this, UE owns "Annotations list panel", Dashboard owns "Panel annotations" and then there is an "Annotations" in the needs ownership list... Maybe its dashboards?

Either way, I agree with removing the icons, the comment Icon makes it look like you can comment on the annotation which you can't.

It all looks good apart from when I pull this brach, the annotation name does not show up in blue, but in an italic muted grey. I prefer the blue in your screenshot that matches variables so could we change it to that?

**Comment by yaelleC** [comment]
> the annotation name does not show up in blue, but in an italic muted grey

@JoaoSilvaGrafana  the built-in annotation is the one that appears in italic muted grey, if you add a new annotation it will show up blue. I think it kind of make sense to keep the built-in grey... but I don't feel very strongly about it 😃 Happy to make everything blue if that's the preference!

Adding @grafana/dashboards-squad as reviewers too for a second 👀

**Comment by JoaoSilvaGrafana** [comment]
> if you add a new annotation it will show up blue

Ah yes! The disabled ones are grey as well that's why mine didn't show up in blue. I personally think that makes it seem like those are not clickable which then might make it seem like you can't reenable a disabled one for instance! So I'm in favor of making them all blue. But up for seeing what dashboards think about the whole thing as well
Screenshot 2023-01-03 at 15 41 39

**Comment by ivanortegaalba** [comment]
Let's ask @Ijin08 😄

**Comment by yaelleC** [comment]
@Ijin08 - gentle nudge 🙂

**Comment by Ijin08** [comment]
Hey!
These lists/tables do have a lot of issues.
But here are my thoughts:
1. Great to be able to reach the annotation with keyboard
2. Removing the icon makes total sense so lets do it(this needs to be done with the dashboard link list as well at some point)
3. Not sure about the blue to be honest. I think the blue is suppose to represent that it is a variable, it used to be teal I think at some point. My opinion is probably the opposite to remove the blue from variable list/table.

**Comment by yaelleC** [comment]
Thanks @Ijin08 !

@JoaoSilvaGrafana , asking the Design System champion: the `<Button fill="text">` component uses the blue colour. I don't really want to override that (our DS goal is for eng to stop writing css 😆 !), is there another accessible component that I could use (that would not be blue 😉 ). 
What is your take for removing the blue?

**Comment by JoaoSilvaGrafana** [comment]
@yaelleC You can set the Button `variant="secondary"` and it will have white text, that should work!

**Comment by yaelleC** [comment]
@ivanortegaalba / @JoaoSilvaGrafana I removed the blue. Could one of you ✅  🙏 ?

**Review by JoaoSilvaGrafana — APPROVED** [review]
Nice! 👏

**Pull request merged**
