### PR TITLE
Flamegraph: Add self to tooltip

### PR DESCRIPTION
**Pull request by aocenas**
Update tooltip to also show the Self values and change the layout a bit

Screenshot from 2022-11-01 15-38-52

### CODE REVIEW

**Comment by cyriltovena** [comment]
Based on the screenshot I'm wondering if this is the right number, self value should be close to 0 ?

**Comment by aocenas** [comment]
@cyriltovena probably just because of the numbers, with 5.5 billion to 5.5k that's 1/1milion which won't be even 1pixel diff in the flamegraph.

**Comment by cyriltovena** [comment]
Ho yes I was off by couple of billions

**Comment by cyriltovena** [comment]
Can we have the % of self compared to the total? Maybe later though.

**Comment by aocenas** [comment]
Does it make sense to restructure it a bit in that case:
```
Count
Total: 5Bil (33%)
Self: 5K (0,5%)
```
I feel like we don't need the `of total` in the percentages as not sure if anything else makes sense. Also is `Total` for good name? Or Self/Cumulative | Self/Value?

**Comment by joey-grafana** [comment]
That looks like a good format to restructure to.

Maybe cumulative but it feels like people will be asking cumulative of what or what does value mean. At first glance total is easy to understand.

**Comment by aocenas** [comment]
@joey-grafana update description with screenshot of the new layout

**Review by joey-grafana — APPROVED** [review]

**Pull request merged**
