### PR TITLE
Explore: no data returned

### LINKED ISSUE #45998: Explore: Improve UI when Explore returns no results
**What happened**:

A query that returns nothing in Explore is just an empty page, nothing that really indicates the query was executed and that there were no errors, just no data returned.

image

**What you expected to happen**:

Display somehow that the query did not return any data.

We could use something similar to what we have in Dashboards:

Screen Shot 2022-03-01 at 08 38 23

or 

image

**How to reproduce it (as minimally and precisely as possible)**:

Run a query that returns no results in Explore (e.g. Prometheus for non-existing labels).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.0
- Data source type & version: any
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by TsotosA**
**What this PR does / why we need it**:
As per [comment](https://github.com/grafana/grafana/issues/45998#issuecomment-1055408230), on successful execution of a query if no data were returned a "no data" message should be displayed.

**Which issue(s) this PR fixes**:

Fixes #45998

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gelicia — CHANGES_REQUESTED** [review]
Thanks so much for your first time contribution! Just a couple things - I'm seeing the No Data screen in loki when there is data. Secondly, the UX team recommended the following design for how it should look:
https://user-images.githubusercontent.com/745532/156126197-d35eab72-4f95-47fc-b068-df21d3823921.png

I've attached what I see with the Loki query for comparison. Can you double check the logic on when it should show and tweak the styling a little? Thank you! 
Screen Shot 2022-03-28 at 2 17 07 PM

**Comment by TsotosA** [comment]
@gelicia  Thank you for the feedback! 
I believe both styling and display logic should be ok now, tried to test as much as i could.

**Comment by gelicia** [comment]
@TsotosA I wanted to be sure we were being comprehensive with when No Data should show, so I added some other checks. To be honest with you, I am not as familiar with where different datasources keep queries as I could be, so I'm going to run this by the team and get back to you. Thank you for your patience, I just want to be sure we're only showing that pane when it's relevant.

**Comment by TsotosA** [comment]
@gelicia Well, its a new to me code base, so it is totally possible that i have missed something.  Thanks for being thorough in this, helps me understand the code base better 👍🏻

**Comment by ifrost** [comment]
FYI: We discussed if "no data" panel should be shown when Explore is opened - this happens in Prometheus, but apparently it's a [bug](https://github.com/grafana/grafana/issues/47560) so it shouldn't be a blocker.

**Review by gelicia — APPROVED** [review]

**Pull request merged**
