### PR TITLE
[v7.2.x] Docs: Add missing alt text

### PR DESCRIPTION
**Pull request by imatwawana**

### CODE REVIEW

**Review by jdbaldry — APPROVED** [review]

**Comment by imatwawana** [comment]
@jdbaldry - I thought I had added a note to this before, but must not have hit a button. There's no 7.2 milestone; should I just create one?

**Comment by jdbaldry** [comment]
If CI doesn't complain about a missing milestone, I wouldn't worry about adding it

**Comment by jdbaldry** [comment]
I think it's gonna be a bit hard to get this in given the age of the branch. It may be easier to make the changes in the website repository directly: https://github.com/grafana/website/tree/master/content/docs/grafana.

It seems that for old and unsupported branches, we have been making changes in the website repository directly. The oldest branch that's still updated from this repository is v9.0

**Comment by imatwawana** [comment]
Replaced by website https://github.com/grafana/website/pull/20648

**Pull request closed without merging**
