### PR TITLE
Build: Add optional build-args for COMMIT_SHA and BUILD_BRANCH

### PR DESCRIPTION
**Pull request by guicaulada**
**What is this feature?**

Remove COPY .git from Dockerfile, added on https://github.com/grafana/grafana/pull/65870

The COMMIT_SHA and BUILD_BRANCH build-args were added to allow for the same functionality.

**Why do we need this feature?**

We need this to solve a conflict mentioned on https://github.com/grafana/grafana/commit/ac09372abfef66ca6cc598f243db6134adce2b5a#r107807055

### CODE REVIEW

**Comment by kminehart** [comment]
oof. I wonder how much extra space this requires now.

**Comment by sakjur** [comment]
If this should go in to v9.5.x it needs a backport.

I'd prefer it if we could read the shasum from the outside and provide it to the Docker build's context over copying the entirety of .git into the Docker build step 🤔

**Comment by guicaulada** [comment]
Makes sense, I'm looking into that now 👍

**Comment by guicaulada** [comment]
@sakjur @kminehart Let me know what you think of this approach :)

**Review by sakjur — APPROVED** [review]
LGTM!

**Pull request merged**
