### PR TITLE
Alerting: Option for Discord notifier to use webhook name

### LINKED ISSUE #40430: Discord notifier overwrites webhook name
**What happened**:  When using discord notifier, messages are forced to come through as "Grafana" instead of the user's customized name used for the webhook

**What you expected to happen**:  User's preferred webhook name is used.  

**Why**:  This allows projects to customize the name.  For instance, in our discord, we have all our development bots renamed & profile pictures set to be thematically appropriate for our game universe.  (It's a small thing, but you might be surprised how excited people got about our build bot once we started personifying it :P)

**How**:  Simply not setting the `username` parameter on [Discord's webhook API](https://discord.com/developers/docs/resources/webhook) will allow the default to be used.  This may alternatively be done as an option to users (ie: '_use default username_', or '_override username_').

**Environment**:
- Grafana version:  8.2.1 (Docker)

### PR DESCRIPTION
**Pull request by Skyedra**
Added an option to discord notifier to use discord's webhook name (useful for customizing notifications).

image

**What this PR does / why we need it**:

If server is configured like this (in Discord):

image

Previous behavior / behavior when option is off:

image

Newly enabled behavior (respect discord webhook configuration):

image

**Which issue(s) this PR fixes**:

Fixes #40430

**Special notes for your reviewer**: #hacktoberfest

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thank you for the contribution. This feels like something we could accept. However, since new alerting solution introduced with Grafana 8 there's actually currently two different/similar implementations of each alert notifier.

Would like to see an update of this code as well: https://github.com/grafana/grafana/blob/740444680cd2432da40aeab4b79e16cebe8a3544/pkg/services/ngalert/notifier/channels/discord.go#L64

**Review by marefr — APPROVED** [review]
LGTM

**Review by gotjosh — APPROVED** [review]
LGTM, minus one nit.

**Review by marefr — CHANGES_REQUESTED** [review]
Sorry, but forgot about documentation. These pages would need an update for the discord settings:
- https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#discord ([repo ref](https://github.com/grafana/grafana/blob/main/docs/sources/alerting/old-alerting/notifications.md#discord))
- https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-channels ([repo ref](https://github.com/grafana/grafana/blob/main/docs/sources/administration/provisioning.md#alert-notification-discord))

**Review by marefr — APPROVED** [review]
LGTM

**Review by gotjosh — APPROVED** [review]
LGTM

**Review by achatterjee-grafana — APPROVED** [review]

**Pull request merged**
