### PR TITLE
Dashboard: Try to parse 8 and 15 digit numbers as timestamps if parsing of time range as date fails

### LINKED ISSUE #19738: Error parsing fixed date range in ms from 10.000.000 to 100.000.000
**What happened**:

We use grafana to draw chart of data with a strange date frame
`1970-01-01 01:30:00` to `1970-01-01 10:00:00`

So that translates to url 
```&from=1800000&to=32400000```

:smile: 

And it works fine. But if you copy & paste the url into other tab, the `to` date errors as "invalid format". 

**What you expected to happen**:
Graphs should load the date properly

**How to reproduce it (as minimally and precisely as possible)**:
Paste to any chart a parameter `&to=` with values from range 10.000.000 to 100.000.000

**Anything else we need to know?**:
Please don't ask why we use this date-range.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: MySQL but I don't think it matters
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Chrome
- Grafana plugins: 
- Others:

### PR DESCRIPTION
**Pull request by jessetan**
The `from` and `to` url parameters can be used to set a time range. Values with a length of 8 digits or 15 digits are assumed to be in `YYYYMMDD` or `YYYYMMDDTHHmmss` format. If the numbers are actually ms since epoch of length 8 or 15, this will not parse correctly. The time range on the dashboard will be "Invalid date".

This PR attempts to parse 8 and 15 digit numbers as ms since epoch if the existing behavior does not produce a usable datetime.
Note: If the number is intended as ms since epoch but it can be parsed using the format `YYYYMMDD` or `YYYYMMDDTHHmmss`, it will not be interpreted as ms since epoch.

Fixes #19738.

### CODE REVIEW

**Comment by jessetan** [comment]
ping @marefr (as a member of Grafana Labs to prevent the bot from marking this as stale)

**Comment by hugohaggmark** [comment]
Thanks for contributing @jessetan , this looks ok but would you mind adding tests for these new cases?

**Comment by jessetan** [comment]
Added tests, failed test seems unrelated to me.

**Review by hugohaggmark — APPROVED** [review]
Looks good to me, thank you for contributing to Grafana @jessetan !

**Pull request merged**
