### PR TITLE
7.0.0 cherry-picks

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Cherry-picks for v7.0.0.

* TablePanel: Fix JSON tooltip positioning, (#24420), merge-sha: f714357fbfa5863d786434a6ff87cd23617d27bd
* Minor UI touches, (#24371), merge-sha: 63d25944c424a820350fd00ce306cdea7cabddcb
* Reporting: tzdata is needed for reporting, (#24422), merge-sha: de8c1b9ad7d793205a73a0b36e28ae8ae88c115a
* Storybook: Position panel to right, (#24429), merge-sha: 8257633b1d9eaabe7313067629b669588e1c8526
* Chore: move dataFramesReceived event to @grafana/data, (#24443), merge-sha: 7e6ac12b9aa7e0644b0806805c03a6891864217e
* Explore: Revert QueryRows refactor, (#24444), merge-sha: 221042c29370898955cf2a99d664e3631e282417
* Logs: Clicking "Load more" from context overlay doesn't expand log row, (#24299), merge-sha: 35c097e47508dda43ffa8c376ab2d08ec636a01c
* Datasource/CloudWatch: Add data links to CloudWatch logs for deep linking to AWS, (#24334), merge-sha: a655aa1ca8fea5b468d1ffaa2387ef05f9a44647
* OldTable: Make old table options align & look better, (#24485), merge-sha: e333d61b97de46fddd911be63beffcfbc0c0ebf7
* Fix: Use correct color for secondary button, (#24439), merge-sha: c671fdbbf824ec51e9588219c149b604de116845
* Dashboard: Fix for strange "dashboard not found" errors when opening links in dashboard settings , (#24416), merge-sha: 352f22042c5f0dc22b1885a9d7d749da29d4276a
* grafana/toolkit: Support paging in cherrypick task, (#24402), merge-sha: c5fc18ac02ccebe945586c8f49aea138618d754b
* Reduce Transform: sort order is preserved as entered by user, (#24494), merge-sha: e341d4b26f50115ccacbcde6069c19e799cbc91d
* TimeZone: added E2E-tests to verify the custom time zone support., (#24442), merge-sha: a521a39ebf47b90d8156228bca2adfbede55b151
* CloudWatch/Logs: Add error message when log groups are not selected, (#24361), merge-sha: d385045d16cae1905f5f46c47e853dbd6b3aac45
* CloudWatch/Log: Fix field autocomplete suggestions inside function, (#24406), merge-sha: b16202acc28ac2ff5a496a5788bf482504f680f6
* Editor: No default suggestion selected, (#24479), merge-sha: 34f61934a1e6d3ca601c2418557da6cb0ba25bc3
* TablePanel: Fixed persisting column resize for time series fields, (#24505), merge-sha: f13a15ae48d8fed899cda40723256414e6940815
* PluginsList: Remove unused panel options, (#24501), merge-sha: 2e69b869904b848e8e6441d21f1a025fdb0224e0
* CloudWatch/Logs: Language provider refactor and test, (#24425), merge-sha: 876011d931bb8f4214ccfb172f1c0c8ca86d448a
* Datasource/CloudWatch: Usability improvements, (#24447), merge-sha: c26374b0b26a1d44cc745cfd82b465db8e84a50b
* CloudWatch/Logs: Fix suggestions of fields after comma, (#24520), merge-sha: 2d29997bdae241186e05e2a44846375de7547b28
* GraphLegend: Only display scrollbar if necessary, (#24527), merge-sha: cb74bc68285a9ad06e3f9062e5e82f1744c83515
* CloudWatch/Logs: Fix fields not being refetched when log group changed, (#24529), merge-sha: 55533d12fd66811142d549a3d0fd24e58c22a135
* Datasource/CloudWatch: Switch to metrics mode, logs API, when choosing stats query from cheatsheet, (#24398), merge-sha: ae7f0aeb7a47625bf5e3453e38da0e18ffd73126
* azuremonitor: Deep linking from Log Analytic queries to the Azure Portal, (#24417), merge-sha: 67ed579647866d0279b6682415ae3c506f31151b
* Datasource/CloudWatch: Results of CloudWatch Logs stats queries are now grouped, (#24396), merge-sha: db91961405f5c7fefb648e420f68005e8cc54b77
* PanelEditor: Fixed issue changing a panel from transparent back to normal , (#24483), merge-sha: 5caf7f59e6273919e4baaf37614fe4ffcbe44a7c
* LabelsToFields: avoid MutableDataFrame, (#24493), merge-sha: c8d3d15292f18f9b9fe9f4a8d419649f17947b63
* Explore/Prometheus: Show results of instant queries only in table, (#24508), merge-sha: 143a26769b111249b12033cae0c6b891e6c11d24
* PanelEditor: Fix so defaults is selected when datasource can't be found., (#24526), merge-sha: cb4266bae0371eeaf0597b885dc699a7c8e21f7b
* Graphite: makes query annotations work again, (#24556), merge-sha: 7992f8bfbcb97d22118f5c24f0e8b4b29f3a8bda
* azuremonitor: limit macro regex to known macros, (#24528), merge-sha: 64046e9a27cebeb89bd539902c08b8d5509f8556
* TimePicker: fixed so you can enter a relative range in the time picker without being converted to absolute range, (#24534), merge-sha: 28f54bc2f76a7a5b4189a236d69ea2497ccb49fb
* Admin Settings: makes long settings values line break, (#24559), merge-sha: 74ddfe07a207e564c154ec773fd2baa63f33aba4
* Update light variable theme for dropdown, (#24566), merge-sha: 67dab0b7674180eb4934d53ee8e421c24b34b575
* UI spelling: use US  form visualization, (#24558), merge-sha: bffa0fa4f6ebe01bef58f0407a89c44a0661b52a
* e2e: adds verify release, (#24568), merge-sha: 7d800e73189873240f13bb107ccf17d830720379
* Search: Save folder expanded state, (#24496), merge-sha: 0396b220a362163d780bfb9a491a00726df61186
* Data sources: Don't fail if URL doesn't specify protocol, (#24497), merge-sha: 164242f5fd8fd8efa0e455ea70051f181cb1e09c
* Security: Tag value sanitization fix in OpenTSDB data source, (#24539), merge-sha: 125ba95686df79989626ac1e8aa48e582c0efd98
* Field: UI & Code consistency Title -> Display name , (#24507), merge-sha: 8de10a8b9fe64ded8aed11165b543959e9934862
* CloudWatch/Logs: Fix suggestion for already inserted field, (#24581), merge-sha: 20f0ee2f223cd1149f6e80a0f4626dd5914faf91
* Plugins: Fix manifest validation, (#24573), merge-sha: 892f9f789c7b1a14d5cd4a3c8ec6ec38b1536f0f
* Search: Safari UI fixes, (#24567), merge-sha: 15ac76a47bc218bea6b1c30787cbfbf2ac7c1aaf
* OrgUsersTable: Fix width when there are long cells in table, (#24533), merge-sha: 0c1f1dd8fd13d47dfaa498c98c543abf25b8997b
* Loki: Allow multiple derived fields with the same name, (#24437), merge-sha: a50cb6aa1f005da0168e513f09a968fd7cfea068
* Datasource/CloudWatch: Fixes various autocomplete issues, (#24583), merge-sha: c1919944eacd5a5e539e1ee1315b42ef9b93f676
* CircleCI: Update grabpl to 0.4.5 in order to include manifest with GEL, (#24577), merge-sha: 824eb94efecd7d3516e0a65adc484d4c1b503623
* CloudWatch/Logs: Make stats hint show consistently, (#24392), merge-sha: 5feef22034a05222ecbbce935174ba868f8ca4cd
* Table: fixes Cannot read property subRows of null, (#24578), merge-sha: 2d19c046f2d11f4049888e0138a4009b6ad93980
* TimePicker: some fixes and polish after testing feedback, (#24585), merge-sha: cab066f8ceae49459c05f61baf7bcaa8dc5de996
* Onboarding: New getting started panel, (#23826), merge-sha: 36fa54a28887679e006b5744f0ad6e63b8d857c3
* Chore: Fix strict null errors on getting started, (#24605), merge-sha: 184890007032cb3f7be82bd2747fd6b3056f90de
* CircleCI: Upgrade grabpl in order to fix package publishing, (#24609), merge-sha: 03940c847131a58c5ee8cfe67cc958f9401b4cb5
* grafana/ui: Fix Icon alignment on Safari, (#24610), merge-sha: 04c75265b5bd2814fe82bc6b44e7a202554c3815
* Transformations: Make transform dropdowns not cropped, (#24615), merge-sha: 9e24c0944f9dcd8a41e4d17900329b3c25bb2374
* Inspect: Allow showing data without transformations and field config applied, (#24314), merge-sha: f23ecc40b43e85f0ec91cd39eb72c18a9f9ce9e2
* Transformers: fix binary operation, (#24604), merge-sha: 97e2837d7c28199fb73a73edcd8c54c4a4c0ee82
* SharedPreferences: fixes so UI Theme can be set back to Default, (#24628), merge-sha: cd9cbe5e16d44f2ef5feda448660773c62d1e793
* Datasource/CloudWatch: Prevents hidden dataframe fields from displaying in tables, (#24580), merge-sha: 277aee864269753d45a2a2e725998aac59f592e9
* Datasource/CloudWatch: Correctly interpolate variables in logs queries, (#24619), merge-sha: bfd337dd004ef837eec112ee94ba64d5e213b8b8
* Explore: Fix rendering of react query editors, (#24593), merge-sha: 285ea7595d8a5056ca881ea979e039e9caaf7955
* CloudWatch: Handle errors that are not awserr.Error instances, (#24641), merge-sha: 8e5a3a578a493f08f3695940739e5d3338d8b96a
* Zipkin: Fix error when span contains remoteEndpoint, (#24524), merge-sha: 0f964c02147dffdd548d18469fb296d5554925d1
* Templating: fixes so Textbox variables read value from url, (#24623), merge-sha: 622246d56de65978acf6d0a68eacd21fabfd2646
* Templating: fixes filtering options with more than 1000 entries, (#24614), merge-sha: 083a2ce220e6414d8a65a0280ca797393831e337
* PanelEdit: Make sure side pane is displayed with tabs by default, (#24636), merge-sha: f769ed035d2934897a7314b6219508d5e3055d75
* @grafana/ui: RadioButtonGroup documentation, (#23143), merge-sha: f1386c78929595a99ba28a39449a4350a908a186
* Search: Fix select item with appSubUrl and pressing enter, (#24634), merge-sha: 37a2ac20c321e5411b4c6faaa0d6125039beb07b
* @grafana/ui: Buttons documentation, (#23144), merge-sha: 54a90166a5e07aa11a89dc52b3b95144a4497304
* Datasource Config: adds back correct styles for autofill fields, (#24671), merge-sha: 9481b7bcf2478cf14007dbf377f1c9a560993c2e
* Changelog and Readme: Update packages to beta and add Select breaking change, (#24670), merge-sha: 85ae144a87710578e1e891496ed759f2034140d0
* Orgs: Add future deprecation notice, (#24502), merge-sha: 2f22781cd8963fc810e24e550dee06b04f8f066e
* Provisioning: Use proxy as default access mode in provisioning, (#24669), merge-sha: 7610d5717aa46be6afef6bd15cbd94051e038f0e
* grafana/toolkit: Use process.cwd() instead of PWD to get directory, (#24677), merge-sha: 660f2b4e99c6e8ba321747419d186a12de7f57dc
* SaveDashboard: Allow editing provisioned dashboard JSON and add confirmation when JSON is copied to dashboard, (#24680), merge-sha: cfac591234b1330ca7be8d1eb62412f446ee4cc6
* Units: adds scale symbol for currencies with suffixed symbol, (#24678), merge-sha: 51509bb2ffdb6794933456cec401174245198285
* CloudWatch/Logs: Fix panic on multiple aggregations queries, (#24683), merge-sha: c60765a178dcb4ad8b4527262d6abb10aa5b0a54
* Docs: Updated instructions on screens for Dashboard Import, (#24584), merge-sha: abfa1b5d747a892a1b278f43f7d9c1756bdc59d8
* CloudWatch: Unify look of query mode select between dashboard and explore, (#24648), merge-sha: e754bcdcf9a0045a536a7c0c70e0761e254023ba
* Datasources: fixes async mount errors, (#24579), merge-sha: e11504dcd24bac55d6b7f26bfcb3a49122c2b35f
* Editor: New line on Enter, run query on Shift+Enter, (#24654), merge-sha: 01bbcf4eea366f7fccf145a5d24520f483adcc48
* Add deprecation note about the unofficial first version of backend plugins, (#24675), merge-sha: 0c8ee5b2c92835a6d9229e9926321a665732863e
* CloudWatch/Logs: Fix autocomplete after by keyword, (#24644), merge-sha: 2b9cc8ba30c968f71dbc9ee4b46639824293788a
* TablePanel: Do not include angular options in options when switching from angular panel, (#24684), merge-sha: c59f5436c0307fc5b2d82c3d16e011ee33ab6755
* MySQL/Postgres/MSSQL/Azure Monitor/StackDriver: Fix help content formatting, (#24687), merge-sha: 7fbed90b89befa73a2ecb1d26bab96a412e4c5e2
* @grafana/ui: When to use Checkbox docs, (#23141), merge-sha: 405145fdd3a8677981e922b6e9cc8a969893c306
* Logs: Fix total bytes process calculation, (#24691), merge-sha: 25e1238022c9335601207a2867b054413e416ba4
* Strict null fixes: updates return type of getMessageFromError, fixes QueryOperationAction props, (#24690), merge-sha: ee12f5e7422afa4226eb37cebf57be2eff6b7606
* Docs: Panel inspector release highlights, (#24686), merge-sha: e4cbeb5cb3da0d0017133edafc566a3bed5fed99
* Explore: fixes loading more logs in logs context view, (#24135), merge-sha: d3a8f6d0269f6dd9a55cd6c8f6841147d63d9d87
* Datasource/CloudWatch: Handle invalidation of log groups when switching datasources, (#24703), merge-sha: 1b29d3460e9fcc44fec738a716bfdbca2c8f9630
* PanelInspect: Make header names reflect the field name in the exported CSV file, (#24624), merge-sha: bf1e5aa16ccec249fdc2c21de163221d4b08b327
* CloudWatch/Logs: Fix query error when results were sparse, (#24702), merge-sha: bc8c05137bce3babcc89d2d66dcb2889c49e3725
* Datasource/CloudWatch: Allows a user to search for log groups that aren't there initially, (#24695), merge-sha: 0e8638ec925b0d73e15a0ffc783b5a2becd5264e
* Transform: fixes so we match the field based on the proper name., (#24659), merge-sha: 96f26cbd5b9e7d9a7e89a3bd0dd4bc843b1469ef
* Fix: changing so we are using date/time values  in UTC during test, (#24707), merge-sha: 98d56336016066fad0758b1f18841eeb2fd920e4
* Docs: generated a 7.0 version of the packages reference docs., (#24708), merge-sha: 6a0abf895e9d9f37eb08c66ab90a1049f03420df
* Query: do not require datasource name and id, (#24718), merge-sha: b73d237bf8d1235932f1942c7cb99d106e65cf36
* Metrictank: Fixed updated schema and dedupe strategy, (#24685), merge-sha: 7fcf2615e15512170e72fbe1325f43fdfe55eb81

### CODE REVIEW

**Comment by marefr** [comment]
@aknuds1 missing commit for versioning update? Just to verify, there was 101 PR's to cherry pick. Again, easier if output from cherry pick task is included in PR description.

**Comment by aknuds1** [comment]
@marefr Sorry, it's actually a draft until I've verified it :) Should have made that clear, but didn't think of it.

**Review by marefr — APPROVED** [review]
LGTM

**Review by papagian — APPROVED** [review]
LGTM

**Pull request merged**
