### PR TITLE
Tempo: Search using TraceQL improvements

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

This PR improves the new Search UI based on the early usage feedback:

- [x] Validate the duration fields, make sure a unit is added
- [x] Prevent second load of options when the dropdown menu is opened and the list is already filled in
- [x] Remove `{<, <=, >, >=}` from the operators list when all values in value dropdown are of type string for dynamic fields
- [x] Move plus button to last dynamic field of list
- [x] Change the Service Name static field to use `resource.service.name` 
- [x] Add scope dropdown to dynamic fields - Unscoped, Resource, Span

image

image

image

**Who is this feature for?**

Everyone who uses the Tempo Search tab with TraceQL.

### CODE REVIEW

**Comment by 09jvilla** [comment]
Adding myself to follow along

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 

Some observations worth considering;

- When pressing a key in the duration field, 4 requests are made for values in other fields (2 unique requests x 2). This also causes the service name and span name loading indicator to appear momentarily.

Screenshot 2023-03-21 at 08 22 59

- Entering 1day for the duration is marked as invalid.. this could actually be valid? (e.g. if a request neither returned nor timed out, although it would of course be terrible).

- Spaces are treated as invalid in the field but actually run a valid query.

Screenshot 2023-03-21 at 08 43 25

**Comment by joey-grafana** [comment]
Excellent stuff. Thanks for fixing/following up, André.

**Comment by 09jvilla** [comment]
@radiorental - Great point. 

Looking at the Otel spec 
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md
I see:

```
A duration is the elapsed time between two events.

The minimal precision is milliseconds.
The maximal precision is nanoseconds.
```

I tried hunting around in the code a bit more but I don't know if that means that durations are integers or floating point values. I *think* it means that they're integers. I was hunting around because if we always expected that durations were something like 1.2342348234ns or 6.387872s, I would think that it makes sense to have `>` and `<` and just ditch `=` since practically speaking you'll never get the `=` case. 

But since I think that they're integers, I'm with you and would vote for `<=` and `>=` and dropping `<` and `>` with the same rational that you have that >100ms is the same as >=101ms for all intents and purposes. 

> I can then maybe come up with a pattern that the user just enters in the lower and upper limits.
This would be nice :)

**Comment by knylander-grafana** [comment]
Docs published: https://grafana.com/docs/grafana-cloud/data-configuration/traces/traces-query-editor/

**Pull request merged**
