### PR TITLE
Add support for converting two annotations into a region via http_api

### LINKED ISSUE #12546: Support PATCH verb in annotations http api
### What Grafana version are you using?
v5.3.0

### What did you do?
Calling a PUT for /api/annotations/ to update an existing annotation

### What was the expected result?
The values passed in would be added to the annotation, without loss of existing data

### What happened instead?
Fields not passed in are nulled out

An example request looks like the following:
`curl -vv -X PUT -H "Content-Type: application/json"  -H "Authorization: Bearer eyJrIjoiTj...iOjF9" -d '{"text":"Annotation Description"}' http://localhost:3000/api/annotations/1`

Before the `PUT`, the annotation contains several other data (e.g., tags, time, etc.). When updating the annotation with `"text":"Annotation Description"`, fields not passed in are nulled out.

### PR DESCRIPTION
**Pull request by calebtote**
Fixes #12546 and #12547

### CODE REVIEW

**Comment by torkelo** [comment]
I think the feature request is interesting but feels like the implementation requires a bit too much complex code to be worth it. Wonder if there is a simpler way to do this?

**Comment by calebtote** [comment]
Thanks for the feedback! Which part seems too complex? I didn't actually add that much for the new feature; instead I mostly moved around existing logic into an if check to make the new feature available. 

The majority of this PR is actually just trying to preserve data that may not have been explicitly passed in.

**Comment by torkelo** [comment]
The whole PR adds about 100 line of code and looks to complicate annotation API & update logic. I think we will wait to see if this feature is more boradly in demand & applicable, or a simpler implementation can be devised. Sorry, just really worried about keeping down complexity & feature creep. Will definitly revist this if there is more demand.

**Comment by calebtote** [comment]
Ok, I'll see what alternatives there are. In the meantime, I may submit a separate PR for at least keeping the existing data on annotations if those fields aren't explicitly passed into the API. Currently, if you try to update an annotation that has tags associated, but you fail to include those tags in the update, the tags will be overwritten in the DB with `[]`.

**Comment by marefr** [comment]
@calebtote then you'll need to introduce a new API endpoint that supports http patch. Http put should always update all properties.

**Comment by calebtote** [comment]
Good call, thanks @marefr!

**Pull request closed without merging**
