### PR TITLE
Inconsistent keyboard behaviour when interacting with panel

### LINKED ISSUE #47005: Inconsistent keyboard behaviour when interacting with panel
Grafana has recently added the ability to navigate through panels in a dashboard using the keyboard, which is amazing! However, I have noticed that this behaviour can be somewhat inconsistent.

I'm aware that this is a relatively new feature, and is a part of https://github.com/grafana/grafana/issues/36776. I'm not sure if this is covered in that card.

**Steps to reproduce**:
Use the keyboard to navigate to panels in your Grafana dashboard. Attempt to edit or view the panels currently selected by keyboard focus by pressing the 'e' or 'v' keys.

**Actual Result**:
The result I'm seeing is varying a lot. Sometimes nothing happens, other times it loads a panel that I don't currently have keyboard access to.

In the video below, you can see me using my keyboard (by pressing 'tab') to navigate to the panels, with keyboard focus on each panel I am pressing both 'e' and 'v', with nothing happening. Around the 20 second mark, I use my mouse pointer to click on the `status history with time series` panel, which then allows me to use 'e' and 'v' for that panel. However, if I change my keyboard focus to one of the other panels, I am still redirected to the `status history with time series` panel, regardless of where my keyboard focus is.

https://user-images.githubusercontent.com/63413067/160582407-2ab89360-4fda-479a-9d70-a7e28abe2a54.mp4

**Expected Result**:
By pressing 'e' or 'v' I'd be able to edit or view the panel which my keyboard is currently focussed on.

**Relevant WCAG Criteria**:
 [2.1.1 keyboard](https://www.w3.org/TR/WCAG21/#keyboard)

**Environment**:
I am using https://play.grafana.org/ (on 29/03/2022)
- Grafana version: 8.4.4 (fcfb01fae)
- User OS & Browser: Windows 11 + Microsoft Edge

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Enableded shortcuts of keyboard when interacting with panel.

**Which issue(s) this PR fixes**:

Fixes #47005

**Demo**
https://www.loom.com/share/d258bb19eb3a4c69a19b6614a315cff8

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mckn** [comment]
> Hey @mckn! Kindly review the PR

Thanks for the ping, I have added the proper reviewers for this PR.

**Comment by mellieA** [comment]
@gitstart I assigned the project too, it will help the reviewers to see this on their project board

**Review by polibb — COMMENTED** [review]
Thank you for contributing to the accessibility of the dashboard using a keyboard! 
Testing this it seems to be alright, except that the inner selection of the panels is still there and it could be confusing: 

https://user-images.githubusercontent.com/13227501/193842793-5f4b8375-48bd-4559-8785-604ad262a9e9.mov

This seems to be a separate issue though (?). 

However, having both `querySelectors` `':hover, :focus-visible'` it creates a confusion when one panel is hovered and another is selected with the Tab:

https://user-images.githubusercontent.com/13227501/193844609-976c4da1-cdc5-41bd-a160-9dcd27f1645c.mov

See the URL parameters in the above recording.

**Comment by gitstart** [comment]
Thank you for the review @polibb, will get back to you with required changes

**Comment by gitstart** [comment]
Hi @polibb! Kindly review the new changes

**Review by polibb — COMMENTED** [review]
Thank you @gitstart. The above mentioned issues are fixed indeed! I will look into the solution itself and come back with feedback/approval.

**Review by polibb — APPROVED** [review]
Looks good :)

Edit: 

- I'm seeing now that `betterer` checks are failing because of the added type assertion. Please avoid using `as` and instead type check if it is an HTMLElement when you are using it.  
- There is a failing test. Please merge `grafana:main` branch into your branch to re-run the build and see if all is alright.

**Comment by polibb** [comment]
@gitstart Sorry, we cannot merge a PR without the CLA signed. Since you are no longer authorised to sign it, I will close the PR.

**Pull request closed without merging**
