### PR TITLE
same issue as #4144, graphite requires a pipe separator

### PR DESCRIPTION
**Pull request by zeph**
issue #4144 related

### CODE REVIEW

**Comment by torkelo** [comment]
graphite uses a glob format. 

and it is not specified in plugin.json anymore it is specified in code by the caller to the templating engine 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/datasource.ts#L63

**Comment by zeph** [comment]
@torkelo well, that is a problem , cause my CustomFinder of graphite-api uses a pipe, and the change in 3.0.0-beta1 of Grafana broke my code. Ideas/suggestions how can I solve this?

**Comment by torkelo** [comment]
Not really, maybe change your code so you conform to Graphite query spec?

**Comment by zeph** [comment]
sure, can you point me to those?

**Comment by torkelo** [comment]
http://graphite.readthedocs.io/en/latest/render_api.html

**Comment by zeph** [comment]
I only found a reference here as "Value List" - http://graphite.readthedocs.io/en/latest/render_api.html#paths-and-wildcards, but does not seem binding requirements for the Custom Finders

**Comment by torkelo** [comment]
```
Value list
Comma-separated values within curly braces ({foo,bar,...}) are treated as value lists, and match if any of the values matches the current point in the path. For example, servers.ix01ehssvc04v.cpu.total.{user,system,iowait} will match the user, system and I/O wait total CPU metrics for the specified server.
```

binding requirement?

**Comment by zeph** [comment]
nevermind, I think a pipe separate listing works as well, and was easier to describe in a grammar

```
tag+=WORD['|']
```
that means, one or more words separated by a pipe... I do not have to take care of the { }

**Comment by torkelo** [comment]
that may be the case, but graphite queries use `{word,word2}` so...

**Comment by zeph** [comment]
so, may i contribute to some code that will accomodate both or this is THE way ?

**Comment by torkelo** [comment]
it is THE way, why support anything else, this is how graphite queries look.

**Comment by zeph** [comment]
got it, fine. thanks for the clarification

**Pull request closed without merging**
