### PR TITLE
Run strict typecheck on PRs

### PR DESCRIPTION
**Pull request by dprokop**

### CODE REVIEW

**Comment by aknuds1** [comment]
Why shouldn't this be done as part of the normal front-end tests job?

**Comment by dprokop** [comment]
> Why shouldn't this be done as part of the normal front-end tests job?

It could. I'll update this

**Comment by dprokop** [comment]
Ah, wait - it couldn't becouse on master it would be performed twice - once for metrics reporting purposes and one just for check. On PRs we do not report metrics, so that's why I have separated it @aknuds1

**Comment by aknuds1** [comment]
@dprokop I think it's better to modify the script to determine if it should report metrics or not. It can do that with the help of CircleCI environment variables.

**Comment by aknuds1** [comment]
The script already only reports metrics if on the master branch, so you can just use it.

**Pull request closed without merging**
