### PR TITLE
Plugins: Adds preliminary support for UI Transformer plugins

### LINKED ISSUE #33154: [FeatureRequest] Allow to create transform plugins
**What would you like to be added**: The ability to create plugins that adds a custom type of transform

**Why is this needed**: Some kind of data requieres some ad-hoc preprocess that may be too complex for the underlying DB.

Now a days this can be done by very complex queries repeated across many panels (which makes it hard to maintain) or by re-doing panel/datasource plugins to inject such kind of ad-hoc preprocesses. Probably a worse solution that the other one but sometimes, in fact, actually is the only possible way to do it.

### PR DESCRIPTION
**Pull request by Willena**
**What is this feature?**

This feature adds a simple (and maybe naive, but working) interface to implement Transformer plugins. 
For now, transformers have (almost) the same signature as the built-in ones. At initial Grafana loading, they are appended to the default once to be later available for use. The plugin interface allows multiple transformations to be added, to create for example packs of transformation. 
A quick usage example can be found in https://github.com/Willena/grafana-plugin-examples/blob/feature/transformer-plugin-example/examples/transformer-basic/src/module.ts

**Why do we need this feature?**

It allows implementing custom transformation plugin to extends list of Grafana built-in transformations. I (in 2021) suggested it, and it seems I'm not the only one interested in that functionality. 

For references: 
https://github.com/grafana/grafana/issues/36228#issuecomment-897077347
https://github.com/grafana/grafana/discussions/38540

**Who is this feature for?**

Transformers in the Grafana UI are very useful, but for domain specific transformations they are not very helpful as a custom piece of code would be required. 

**Which issue(s) does this PR fix?**:

Fixes #33154

**Special notes for your reviewer:**

Comments are very welcomed. I don't know if it is implemented the best way. 

Please check that:
- [X] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ryantxu** [comment]
Interesting -- I am pretty torn on this now.  The (undocumented/unsupported) reality is that you can already register new transformations from any plugin.   https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/transformer/RegisterTwinMakerLinksEditor.tsx#L205

Transformers offer a super powerful way to inject last mile logic into, but the wild west leads to so much confusion around the feature in general.  

Are there transformers that make sense to publish as standalone plugins, that should not just be added to the core transformer library?

**Comment by Willena** [comment]
Hello @ryantxu ,

> The (undocumented/unsupported) reality is that you can already register new transformations from any plugin.

I wasn't aware of that (and never thought the registry was made available to plugins, I should have tried). 

Your example seams to be a great candidate for the creation of a nested transformer plugin in the app plugin. In my opinion having an "official"  interface that does not  require to write an empty app plugin (or datasource plugins) that "hacks" the built-in (but exposed) transformation registry is making things cleaner. 
In the situation where i'm satisfied with core data sources and core panels, and the only things missing is a small transformation, it very simple to write a quick and easy transformation plugin. 

Even core transformations can be easily migrated to a single built-in "core transformations" plugin (following was has been made for data sources and panels)


One other idea I have (but I really don't like it for multiple reasons) would be to add a core transformation that takes a JavaScript code snippet as input. The reality is that it removes the ability to share the transformer code easily,  it is not good for the user experience (especially if they are not JavaScript programmers) and probably more...

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
Hello @Willena! First off, I want to say thank you for putting in the effort to contribute to our plugins platform. Your code looks great, and it's clear you put thought into it.

However, right now we're focusing on enhancing our core with new transformations, rather than expanding our plugin types. The introduction of new types, whilst powerful, can bring additional challenges for our own maintenance within Grafana, as well as discoverability for users and plugin developer experience. If you have any transformations in mind that you think are missing, we'd be more than happy to welcome your contributions there!

While we won't be able to merge your pull request at this time, please know that we appreciate your work and may revisit this type of plugins in the future. We hope you understand our current priorities, and thanks again for your input!

**Comment by Willena** [comment]
Hello, @tolzhabayev ,

No worries, I can understand you have different priorities. 

To be honest, I dream of Grafana with a very powerful and flexible plugin platform (to extend anything that makes a little bit of sense in the UI or API). 
I'll keep all my ideas for later. 

Feel free to do whatever you want with this PR.

**Pull request closed without merging**
