### PR TITLE
Add CloudFoundry OAuth adapter

### PR DESCRIPTION
**Pull request by amenzhinsky**
Hi there!

My company is interested and committed to CloudFoundry integration for Grafana and it would be nice to see it in upstream.

Here's the first piece code.
There're more upcoming changes like roles, multi-tenancy, etc.

### CODE REVIEW

**Comment by torkelo** [comment]
could it be possible to use the generic oauth for this? https://github.com/Altoros/grafana/blob/96d32b57f610d5df5a9662f974221af37f41e6d2/conf/defaults.ini#L243

**Comment by amenzhinsky** [comment]
@torkelo, Yes and no. Authentication works well, I mean users can sign in and sign up.

But we need to be able to make API calls to fetch user's data (organizations, spaces, permissions, etc.) from the CF in order to implement authorization logic.

The userinfo structure is also a little bit different from the generic one.

**Comment by torkelo** [comment]
think more custom auth will have to wait for a backend plugin API / design. 
https://github.com/grafana/grafana/issues/6416

**Comment by amenzhinsky** [comment]
It would be really good to have it in upstream and keep on maintaining the source code. And as soon as the backend api is brought out we can easily port it, otherwise I guess it's going to take much time

**Comment by torkelo** [comment]
We are approaching a limit to number of built in auth mechanisms Grafana core can support, more will have to be supported via backend plugins:
https://github.com/grafana/grafana/issues/6841

**Comment by torkelo** [comment]
but leaving this open so people can up vote it, (backend plugins might take some time to get implemented)

**Comment by torkelo** [comment]
Or better, created a feature request issue for this instead, https://github.com/grafana/grafana/issues/6842

**Comment by kkonrad** [comment]
@amenzhinsky great that you have implemented this!

I was wondering - can it be done so that it works using only UAA, without CF (CloudControler in particular?). AFAIK UAA is used not only with CF.

CF could be handled as proper configuration of this particular UAA OAuth adapter. Also, probably CF could be a good example in documentation on how to use this plugin.

**Comment by amenzhinsky** [comment]
@kkonrad I'm glad to help you.

In this case we consider UAA as a part of CF and currently we work on deeper [CF integration](https://github.com/Altoros/grafana/tree/cf-metrics), e.g. correct groups and roles assignment.

But if you want only UAA authentication, simply comment out 66..73 lines in the `cloudfoundry_oauth.go` file. Then it should work perfectly well.

**Pull request closed without merging**
