### PR TITLE
Server: Should fail when server is unable to bind port

### LINKED ISSUE #20385: Grafana hangs on start when port is in use
**What happened**:
I started Grafana locally while already having another instance running, and it hung due to the port being taken.

**What you expected to happen**:
I expected Grafana to report the error and exit.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start an instance of Grafana
2. Start another instance of Grafana
3. Observe that the second instance hangs due to the port being taken

**Environment**:
- Grafana version: Git revision 073e9ef9e7f380f7f53900953337491806462ca9
- OS Grafana is installed on: OS X

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Make Grafana server exit when unable to bind the configured port.

**Which issue(s) this PR fixes**:
Fixes #20385

### CODE REVIEW

**Comment by marefr** [comment]
@aknuds1 had a quick look at this and seems like this PR changed the behavior for running services, see https://github.com/grafana/grafana/pull/19796/files#diff-3cdb64b7bf6080d966eab886d1907124R128-R139

I think the code before that PR's changes was more correct.

**Review by marefr — CHANGES_REQUESTED** [review]
See comment above

**Comment by aknuds1** [comment]
@marefr Thanks for your input! I think the issue that PR introduced was not passing on errors from failing services to the `errgroup.Group`. When changing back to bubbling the error in this PR, the server exits as I at least would expect.

**Review by marefr — APPROVED** [review]
Great :+1: LGTM

Can I suggest to remove these two lines from bra.toml: 
https://github.com/grafana/grafana/blob/master/.bra.toml#L20-L21

To me they seem to do more worse than good. When I send interrupt of `make run` or `bra run` it doesn't seem to do any difference:
```bash
Makefile:53: recipe for target 'run' failed
make: *** [run] Interrupt

marcus at efra in ~/go/src/github.com/grafana/grafana on bugfix/fix-20385 ✔  [ddd18c9] × 1:14
marcus at efra in ~/go/src/github.com/grafana/grafana on bugfix/fix-20385 ✔                                                                                                  [ddd18c9] × 1:14
> WARN[11-16|01:14:16] plugin failed to exit gracefully         logger=plugins plugin-id=grafana-oracle-datasource
WARN[11-16|01:14:18] plugin failed to exit gracefully         logger=plugins plugin-id=grafana-simple-json-datasource
INFO[11-16|01:14:18] Stopped PluginManager                    logger=server reason="context canceled"
EROR[11-16|01:14:18] Server shutdown                          logger=server reason=nil
```

However, when running `make run` or `bra run` with above two lines in bra.toml and make changes to a go file and save I get the following when bra restarts grafana-server it outputs from the old process:
```bash
INFO[11-16|01:17:12] Initializing provisioningServiceImpl     logger=server
WARN[11-16|01:17:13] plugin failed to exit gracefully         logger=plugins plugin-id=grafana-oracle-datasource
INFO[11-16|01:17:13] Backend rendering via phantomJS          logger=rendering
WARN[11-16|01:17:13] phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. logger=rendering
INFO[11-16|01:17:13] Initializing Stream Manager 
INFO[11-16|01:17:13] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=
WARN[11-16|01:17:15] plugin failed to exit gracefully         logger=plugins plugin-id=grafana-simple-json-datasource
WARN[11-16|01:17:17] plugin failed to exit gracefully         logger=plugins plugin-id=grafana-simple-json-backend-datasource
INFO[11-16|01:17:17] Stopped PluginManager                    logger=server reason="context canceled"
EROR[11-16|01:17:17] Server shutdown                          logger=server reason=nil
```

When running without above two lines I don't get output from the old process and seems to work as expected anyway.

Can you please try this out on your machine and see if you get same results?

**Comment by aknuds1** [comment]
@marefr When I tested now, the difference seems to be that when those two lines are intact, bra takes a bit of time to stop the server before it restarts it and when I remove the lines, it restarts the server instantly.

I've removed them, I don't know if they are of any help.

**Review by torkelo — COMMENTED** [review]
Looks good!

**Pull request merged**
