### PR TITLE
CircleCI: Download grabpl from GCS

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Download Grafana Build Pipeline tool from GCS instead of cloning from GitHub, since we are having permissions problems.

### CODE REVIEW

**Comment by xlson** [comment]
Do we still want to do this if we're having problems in general with accessing GitHub?

**Comment by aknuds1** [comment]
@xlson Not 100% sure, but I figured we might want to lock down the grabpl version anyway, in order to ensure stable builds?

**Comment by bergquist** [comment]
pinning the build pipeline seems like a good idea regardless of how. 
Perhaps its easier to host the binaries as releases on github?

**Comment by aknuds1** [comment]
@bergquist How does one access a release from a private repo? Haven't tried before, so not sure.

**Review by xlson — APPROVED** [review]
Looks good.

**Comment by aknuds1** [comment]
@xlson Can you force merging as an admin? I can't merge since CI fails.

**Pull request merged**
