### PR TITLE
PluginProxy: Split implementations of token providers

### PR DESCRIPTION
**Pull request by kostrse**
The plugin proxy in Grafana supports different authentication modes used by different cloud providers.
And more authentication modes can be added in future.

The goal of this PR is to reorganize and split implementation of existing token provider to have different implementations for different authentication modes abstracted out behind a common interface. This strategy injection pattern will help to independently maintain different authentication implementations in isolation without risking to unexpectedly break others.

There're no functional changes to existing logic.

I wanted to have each token provider in a separated file, so they would be easier to review and maintain in future.
Let me know it it makes sense to organize them into separate Go packages.

### CODE REVIEW

**Comment by aknuds1** [comment]
Thanks, can you fix the CI errors?

**Review by dsotirakis — COMMENTED** [review]
LGTM! Thanks for your contribution, would you be so kind to fix the CI failure?

```
pkg/api/pluginproxy/token_provider_jwt.go:6: File is not `goimports`-ed (goimports) "golang.org/x/oauth2"
```

**Comment by ying-jeanne** [comment]
LGTM, after fixing the lint , you need to rebase on master to fix the build.

**Review by ying-jeanne — APPROVED** [review]

**Comment by kostrse** [comment]
Fixed racing in unit-tests

**Comment by kostrse** [comment]
@ying-jeanne could you please approve again?

**Review by dsotirakis — APPROVED** [review]

**Pull request merged**
