### PR TITLE
DatasourceList: Fixes using sub path on datasources URL

### LINKED ISSUE #58290: Config: Datasources url is not honoring root_url when using sub-path
**What happened**:
When navigating to /datasources page the datasources components being generated aren't honoring the root_url
This isn't immediately noticeable, as the javascript intercepts the request if you click it.
However, if you Ctrl/Cmd + Click the link (or "copy the link", or open the source in developer tools) you see the URLs generated for the datasources are not honouring the root_url setting.

**What you expected to happen**:
I expect the same behaviour as the /plugins which generates the list of plugins with correct urls (i.e. honouring root_url).
Instead of all links starting with /datasources, I expect links to honour root_url/datasources
In the below case, this would mean root_url/grafana/datasources and not root_url/grafana

**How to reproduce it (as minimally and precisely as possible)**:
If using the container just use the env vars:
GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana"
GF_SERVE_FROM_SUB_PATH=true
My datasources are pre-provisioned with a datasources.yml file in /etc/grafana/provisioning

**Anything else we need to know?**:
I believe this is something to do with
Line 74 of DataSourcesList (in main - current commit 3f654b932abbd82532c58850fa0126ac23533be1)
              <Card href={dataSourcesRoutes.Edit.replace(/:uid/gi, dataSource.uid)}>
https://github.com/grafana/grafana/blob/bdb8fe3b025f8f5eb11d85f8287901e73ac4b35b/public/app/features/datasources/components/DataSourcesList.tsx#L74

I currently have a lot to handle but, if this is the bug source, I could probably pick this up in the beginning of 12/2022. 
I am more versed in VueJS than React however, so feel free to pick it up

**Environment**:
- Grafana version: 9.2.3 (docker tag)
- Data source type & version: All
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Windows + firefox + chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

At the moment the URL on each datasource link on the datasources list does not take into account if grafana is served via a subpath (i.e. `serve_from_sub_path = true` and `root_url` configured in `custom.ini`).
This also happens when creating a new one through the "add new datasource" button and going to a new dashboard through the "build a dashboard button"

Example
CleanShot 2022-11-29 at 10 20 39@2x

**Why do we need this feature?**

To honour the sub path in the root url when navigating to a datasource/creating a new one.

**Who is this feature for?**

Anyone who uses sub paths

**Which issue(s) does this PR fix?**:

Fixes #58290

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
@JoaoSilvaGrafana wdyt about changing the constants [here](https://github.com/grafana/grafana/blob/main/public/app/features/datasources/constants.ts#L7) to have the `appSubUrl` instead? 🤔

**Comment by JoaoSilvaGrafana** [comment]
> wdyt about changing the constants [here](https://github.com/grafana/grafana/blob/main/public/app/features/datasources/constants.ts#L7) to have the appSubUrl instead? 🤔

@ashharrison90 I have tried this but when I access the data sources list through navigation it just shows a 404, I am assuming it is because it is used [here](https://github.com/grafana/grafana/blob/main/public/app/routes/routes.tsx#L130) and somewhere the comparison of the route and the url is failing? 😐

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana ah... guess we could call `stripBaseFromUrl` in the routes file, but that's kinda ugly as well. we really need to standardise somewhere how we work with appSubUrl 😭 

ok in that case this looks good for now, thanks for trying! 🙌

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Pull request merged**
