### PR TITLE
SingleStat: The gauge option in now disabled/hidden (unless it's an old panel with it already enabled) 

### PR DESCRIPTION
**Pull request by ryantxu**
Gauges should be implemented in the Gauge panel, not the singlestat panel.

This PR just removes the option to create a new gauge in singlestat, but any existing gauges will keep working the same.

TODO:
- [x] Update this with the text we want in the changelog

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

**Comment by patricktokeeffe** [comment]
>Gauges should be implemented in the Gauge panel, not the singlestat panel.

Is there more context for the above "should"? Why is it bad for SingleStat to have a gauge? 

* Gauge panel does not support spark lines, aka time-series in panel background. 
* Gauge panel has no prefix/postfix fields for arbitrary unit display. 
* Gauge panel does not support colored backgrounds for statuses. 

Yes Gauge panel supports more than 2 thresholds, which is nice, but it's not a drop-in replacement for SingleStat+gauge overlay. I'd like to see this PR reversed. Does having gauges block something else?

**Comment by ryantxu** [comment]
Hi @patricktokeeffe -- the gauge implementation in angular SingleStat is really really really hard to maintain.  In particular as everything moves to react we need to fix how these are developed.  We would love any help with that process :)

* sparkline: perhaps a difference of opinion... but the sparkline on gauge is ugly and not very clear.  In 6.4beta, (with alpha plugins enabled) you can now share data between panels.  This will let you put a gauge next to a small graph using the same query results.
* Arbitrary unit display is an issue that needs to be solved.  See #16038, other approaches may make sense too
* Colored backgrounds for statuses... feel free to open a PR.  Like sparklines+gauge, this usually looks pretty bad and may be better represented with two panels sharing data.

**Comment by ryantxu** [comment]
Here is a link to the larger issues around gauge in SingleStat:
https://github.com/grafana/grafana/issues/14554

**Comment by patricktokeeffe** [comment]
HI @ryantxu these are very helpful to understand - thank you!

**Pull request merged**
