### PR TITLE
TableCell: show JSON rather than [object Object]

### PR DESCRIPTION
**Pull request by ryantxu**
Currently if you have a field with an 'other' value, it will simply render as `toString()` this is often just "object Object"

This PR adds a new cell type that will show the JSON text and a JSON explorer on popup.

This is super useful when using ArrayDataFrame with results from random APIs :)

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Is there a way to test this? Would be nice if testdata data source had a scenario for this

**Review by aknuds1 — APPROVED** [review]
Back-end part looks fine.

**Comment by ryantxu** [comment]
@torkelo -- I added a 'grafana_api' scenario to test data... it simply calls the grafana apis and returns them as dataframes, now we can see:

image

**Review by dprokop — APPROVED** [review]
Great addition!

**Pull request merged**
