### PR TITLE
OpenTSDB gexp query support

### PR DESCRIPTION
**Pull request by dehotot**
This PR ports @utkarshcmu 's unfinished work to support OpenTSDB's "gexp" query format to the current version of Grafana.

It has been discussed in Issue #3805 and a few users (myself, @mjb512) are using it with success.

### CODE REVIEW

**Comment by dehotot** [comment]
Hmm, weird, this still seems to be sticking on @mjb512 's signing

**Comment by marefr** [comment]
You've made a commit using en email address that's not have any github accont - if you insert that email address in your github account you should be all set.

**Comment by torkelo** [comment]
This is missing a backend implementation as well. I wonder if we should try to find a maintainer for the OpenTSDB plugin and make it an external plugin (at some point). It is a little bit too much code for us to support and maintain when non on the core team has any OpenTSDB experiance or use it. Out of all the core data sources it is the least used data source. 

On the flip side a lot big companies are using it.

**Comment by Vehyla** [comment]
Hello, we are on of those companies that are using OpenTSDB.  I was wondering if this will be merged into a future release?  I see in your comment a few days ago this is missing some backend implementation stuff.  I was wondering if that is a blocker, or if you have more information on what is needed so we can evaluate if we have people on staff that could help.

**Comment by dehotot** [comment]
@torkelo between us we can probably create a gexp backend, but I can only dedicate my free time if Grafana core will accept improvements to OpenTSDB in core.

If you need sponsored development then perhaps @Vehyla's group can take the gexp work to completion.

**Comment by UglyTroLL** [comment]
What do I need to do if I want to patch this onto our own Grafana?

**Comment by torkelo** [comment]
Closing this as it's missing the backend part still.

**Pull request closed without merging**
