### PR TITLE
Enterprise: List 7.0 features

### PR DESCRIPTION
**Pull request by sakjur**
List newly added features in Grafana Enterprise 7.0 on the upgrade page.

### CODE REVIEW

**Comment by sakjur** [comment]
Not very happy about the layout when adding more things on the feature side without doing anything on the support side.

Screen Shot 2020-04-27 at 17 49 54

**Comment by torkelo** [comment]
Maybe if we moved the Get Grafana Enterpris section to top on the right (or the bottom) it might make the two columns more aligned

**Review by torkelo — APPROVED** [review]

**Comment by sakjur** [comment]
I'll try that :+1:

**Comment by sakjur** [comment]
That's a lot better imo

Screen Shot 2020-04-28 at 09 38 13

**Review by torkelo — APPROVED** [review]

**Pull request merged**
