### PR TITLE
ReleaseNotes: Updated changelog and release notes for 7.5.3

### PR DESCRIPTION
**Pull request by grafanabot**
This exciting! So much has changed!

### CODE REVIEW

**Review by gabor — APPROVED** [review]
it's ok.

**Comment by osg-grafana** [comment]
@oddlittlebird would you like a Docs Squad reviewer for PRs like this?

**Comment by oddlittlebird** [comment]
Yes. @gabor, why is there a change to the Singlestat panel listed? It's been deprecated in favor of the Stat panel. Also, the colons should be inside the bold, not outside and "drop-down" should be hyphenated.

@achatterjee-grafana, is this something we can fix in text or do we need to change code somewhere?

**Comment by achatterjee-grafana** [comment]
@oddlittlebird, can you clarify my ask - I am not sure what you mean. Thanks!

**Pull request merged**
