### PR TITLE
CI: Update CircleCI docker images to new `cimg` type

### PR DESCRIPTION
**Pull request by eddiewebb**
These new images from CircleCI are engineered to have faster spinup times through a smaller footprint and more shared layers with other languages run on CircleCI (means more cache hits!)

They also add stability with more deterministic versioning.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
Thanks, these images are still in beta though aren't they?

**Comment by eddiewebb** [comment]
@aknuds1 - yes they are still in beta, I'll keep this PR in draft mode.

We're actively trying to exercise the images in some of our most popular open source builds to see how the experience and migration is coming from our previous types, and uncover any issues before we declare any of them GA.

So while I hope that this change is ultimately beneficial to the grafana community, the learning has already been valuable to our team.

**Comment by aknuds1** [comment]
Thanks for clarifying that @eddiewebb 🙂

**Comment by aknuds1** [comment]
Is there any update wrt. the status of these new images?

**Comment by eddiewebb** [comment]
Our base image should go GA this week or next, with language following that. (@felicianotech we dont have any public issue tracking that do we?)

**Comment by felicianotech** [comment]
Correct, next week they'll be GA'd. I can comment back here when they do.

> we dont have any public issue tracking that do we?

Not for GA dates no.

@eddiewebb We should undo the `sudo` changes in this PR though.

**Comment by marefr** [comment]
Thanks. We'll close this for now since we've made changes to our circle ci config recently. If your still interested in this, please open a new PR applied to our latest circle ci config.

**Pull request closed without merging**
