### PR TITLE
Added moment+locale and ability to detect first day of the week 

### LINKED ISSUE #3003: Feature Request: Let "This week" starts with Monday
In Germany the week starts normally with Monday.
The perfect way would be a setting, where you can change the start day of the week.

http://momentjs.com/docs/#/get-set/iso-weekday/

### PR DESCRIPTION
**Pull request by toni-moreno**
This PR fixes  https://github.com/grafana/grafana/issues/3003 .

Gets locale from browser preferences.

### CODE REVIEW

**Comment by torkelo** [comment]
argh, moment.js with locale formats is just humongous, is there not a slimmed down version with only week day starts for some big locales?

**Comment by toni-moreno** [comment]
I have to say that grafana loads really fast even with moment+locales in the same file,  IMHO is a good workarround for the  issue (https://github.com/grafana/grafana/issues/3003) but could be improved.

### Proposed Improvement 1

There is no way if working with ""official versions". But we can download locale files and moment.js from github ( https://github.com/moment/moment/tree/develop/locale).

we can create a "vendor/moment/i18n/" directory and place all moment locale files on it , and restore the original moment.js file.

On the app.js we could load  dynamically this locale file by doing

```
var selected_lang=navigator.userLanguage || navigator.language;
var moment_locale_file= "public/moment/i18n/"+selecte_lang+".js";
$.getScript( moment_locale_file)
  .done(function( script, textStatus ) {
    moment.locale(selected_lang);
    console.log('OK Languaje: '+selected_lang+' have been loaded');
  })
  .fail(function( jqxhr, settings, exception ) {
    console.log('ERROR on load locale Languaje: '+selected_lang);
});
```
do you like this improvement?

### Proposed Improvement 2

Could be interesting if administrator could force a certain lang from configuration on grafana.ini ( by example)

```
locale_use_default="fr"
locale_use_from_browser=true
```
with these two options administrators give users the posibility to configure locale from their browsers but it no language detected the default will be "frech".

To do that I need some help.

There is any way to access to grafana server variables from the JS frontend ?

**Comment by toni-moreno** [comment]
Hi @torkelo some feedback would be appreciated !!

**Comment by toni-moreno** [comment]
Well bad news..

The $.getScript() method seems to break something related to angular, 

image

I will look for other solutions

**Comment by toni-moreno** [comment]
Hi @torkelo I've finally loaded just by attach to the file to be loaded in the preBootReruires Array

````
  // add plugin modules
  for (var i = 0; i < pluginModules.length; i++) {
    preBootRequires.push(pluginModules[i]);
  }
  //initialize locale from browser preferences
  var selected_lang=navigator.userLanguage || navigator.language;
  var moment_locale_file= "public/vendor/moment/locale/"+selected_lang+".js";
  preBootRequires.push(moment_locale_file);
```
With this solution once loaded there is no needed to execute moment.locale() , the loaded file will be the default locale.
If you agree this solution I will commit and rebase to simplify merge.

I will need also some feedback on the "Proposed Improvement 2"

**Comment by toni-moreno** [comment]
ping @torkelo @bergquist .. 

I don't have skills on angular, so I would like you can review the proposed solution , this is load locale js file dynamically pushing on the preBootRequires list.

There is any way to get some properties from grafana.ini as proposed in https://github.com/grafana/grafana/pull/3529#issuecomment-165110722.

Thank you very much!

**Comment by toni-moreno** [comment]
Definitely preBootRequires is not the solution. The grafana loading is crashing when no locale found.

image

**Comment by toni-moreno** [comment]
I've finally added a locale section  in the grafana server configuration witch let grafana administrator force the locale or be selected from browser preferences.

````
#################################### Locale ####################################
[locale]
#load default users language for date/time customization (full translation not ready yet)
set_default = en
#when set_from_browser = true try load language settings from  Accept-Language header sent by browser
set_from_browser = true
````
Al posible languages are sent and configured dynamically  for each user if set_from_browser = true

**Comment by torkelo** [comment]
would prefer a PR that only solves the monday problem, like a config option or browser locale detection for that.

**Comment by toni-moreno** [comment]
Hi @torkelo I'm sad  and a little surprised for your decision. with this PR you can fix a great issue, and also give support for momentjs translations adding only 40kb of locale info.

With this PR and this other FR( https://github.com/grafana/grafana/issues/3591) we can add Grafana the ability to build custom dashboards with automatic language support for time data for up than 80 native languages  like the following . ( no other change is needed) 

image

image

image

I'm open to discuss, about this PR (and https://github.com/grafana/grafana/issues/3591 )    if you would like to reopen it.

**Comment by bachi76** [comment]
So @torkelo and @toni-moreno - has this PR still not been merged? Seems proper internationalisation is already there, simply not merged? This is *really* a show stopper for the other 6 billion people on the planet...

**Comment by torkelo** [comment]
This PR was not merged, but this was https://github.com/grafana/grafana/pull/5517

**Comment by dewi-ny-je** [comment]
I set timezone according "to local browser" but it doesn't seem to switch to Monday as it should.
The documentation seems also to be missing.

**Pull request closed without merging**
