### PR TITLE
Installing Grafana on IBM Cloud

### PR DESCRIPTION
**Pull request by Sumithkr**
Add to documentation page 
how to install Grafana on ibm cloud

Step 1 provision Kubernetes Cluster
•	Click the Catalog button on the top
•	Select Service from the catalog
•	Search for Kubernetes Service and click on it
 

•	You are now at the Kubernetes deployment page, you need to specify some details about the cluster
•	Choose a plan standard or free, the free plan only has one worker node and no subnet, to provision a standard cluster, you will need to upgrade you account to Pay-As-You-Go
•	To upgrade to a Pay-As-You-Go account, complete the following steps:
•	In the console, go to Manage > Account.
•	Select Account settings, and click Add credit card.
•	Enter your payment information, click Next, and submit your information
•	Choose classic or VPC, read the docs and choose the most suitable type for yourself

 
•	Now choose your location settings, for more information please visit Locations
•	Choose Geography (continent)
 
•	Choose Single or Multizone, in single zone your data is only kept in on datacenter, on the other hand with Multizone it is distributed to multiple zones, thus safer in an unforseen zone failure
 
•	If you wish to use Multizone please set up your account with VRF or enable Vlan spanning
•	If at your current location selection, there is no available Virtual LAN, a new Vlan will be created for you
•	Choose a Worker node setup or use the preselected one, set Worker node amount per zone
 
•	Choose Master Service Endpoint, In VRF-enabled accounts, you can choose private-only to make your master accessible on the private network or via VPN tunnel. Choose public-only to make your master publicly accessible. When you have a VRF-enabled account, your cluster is set up by default to use both private and public endpoints. For more information visit endpoints.
 
•	Give cluster a name
 
•	Give desired tags to your cluster, for more information visit tags
 
•	Click create
 
•	Wait for you cluster to be provisioned
 
•	Your cluster is ready for usage
 
Step 2 deploy IBM Cloud Block Storage plug-in
The Block Storage plug-in is a persistent, high-performance iSCSI storage that you can add to your apps by using Kubernetes Persistent Volumes (PVs).
•	Click the Catalog button on the top
•	Select Software from the catalog
•	Search for IBM Cloud Block Storage plug-in and click on it
 
•	On the application page Click in the dot next to the cluster, you wish to use
•	Click on Enter or Select Namespace and choose the default Namespace or use a custom one (if you get error please wait 30 minutes for the cluster to finalize)
 
•	Give a name to this workspace
•	Click install and wait for the deployment
 

Step 3 deploy Grafana

We will deploy MySQL on our cluster
•	Click the Catalog button on the top
•	Select Software from the catalog
•	Search for Grafana and click on it

 

•	Please select IBM Kubernetes Service
 
•	On the application page Click in the dot next to the cluster, you wish to use
 

•	Click on Enter or Select Namespace and choose the default Namespace or use a custom one
 
•	Give a unique name to workspace, which you can easily recognize
 
•	Select which resource group you want to use, it's for access control and billing purposes. For more information please visit resource groups
 

•	Give tags to your Grafana, for more information visit tags
 

•	Click on Parameters with default values, You can set deployment values or use the default ones

 

•	Please set the Grafana root password in the parameters
 
•	Please change the service.type from ClusterIP to LoadBalancer in the parameters
 
•	After finishing everything, tick the box next to the agreements and click install
 
•	The Grafana workspace will start installing, wait a couple of minutes
•	Your Grafana workspace has been successfully deployed
 

Verify Grafana installation
•	Go to Resources in your browser
•	Click on Clusters
•	Click on your Cluster

 

•	Now you are at you clusters overview, here Click on Actions and Web terminal from the dropdown menu
 
•	Click install - wait couple of minutes
 

•	Click on Actions
•	Click Web terminal --> a terminal will open up
•	Type in the terminal, please change NAMESPACE to the namespace you choose at the deployment setup:
$ kubectl get ns
 

$ kubectl get pod -n NAMESPACE -o wide 
 

$ kubectl get service -n NAMESPACE
 
•	Running Grafana service will be visible
•	Copy the External IP and Port number, you can access the website on this IP
•	Paste it into your browser
•	Grafana welcome message will be visible
 

[Grafana.docx](https://github.com/grafana/grafana/files/5610562/Grafana.docx)

### CODE REVIEW

**Comment by oddlittlebird** [comment]
Thanks for the contribution! Let me check with the devs on this.

**Review by aknuds1 — COMMENTED** [review]
I think documenting installation on a certain cloud provider requires too specialized knowledge, and is out of scope for us. Thoughts @sakjur @xlson?

**Comment by Sumithkr** [comment]
that docs includes all instruction how to install grafana on ibm cloud

**Comment by aknuds1** [comment]
> that docs includes all instruction how to install grafana on ibm cloud

If included, we would still have to vet and maintain such docs. It's a significant burden.

**Comment by Sumithkr** [comment]
https://mariadb.com/kb/en/installing-mariadb-on-ibm-cloud/

such docs is also uploaded on mariadb have a look please 
we want same on grafane

**Comment by sakjur** [comment]
@Sumithkr That is MariaDB's wiki, not their docs. That is equivalent to you posting this as a guide on https://community.grafana.com — which you are welcome to do 🙂

> Content reproduced on this site is the property of its respective owners, and this content is not reviewed in advance by MariaDB. The views, information and opinions expressed by this content do not necessarily represent those of MariaDB or any other party.

There are a few things that comes to my mind when looking at this PR:

- The Helm charts used are [Bitnami's Grafana charts](https://bitnami.com/stack/grafana) and not the [Grafana Community Helm charts](https://github.com/grafana/helm-charts). AFAIK we have no official relationship with Bitnami, so refering to them as a best practice for installing Grafana on IBM Cloud seems a little bit odd.
- Most of the content in the guide is for setting up Kubernetes, not Grafana itself. Provisioning a full Kubernetes cluster to set up Grafana is not something I think we should recommend.
- Like @aknuds1 says, vetting and maintaining these kind of docs is a lot of work. We're expanding all of our teams at the moment, so maybe in a year the answer for "should we have docs for specific cloud best practices" will be a different one, particularly if the cloud vendors were willing to collaborate with us on providing those docs. But even then we'll have to prioritize which clouds we can support, and at the moment IBM Cloud has a rather marginal market share compared to the AWS, Azure, and Google Cloud.

I'd recommend posting this to our community site. I think it could make sense to link to high quality and maintained community guides from our docs in something like an "Install on other platforms" documentation page (that'd allow us to keep a lower standard of vetting while still promoting community provided content), but at the moment, I don't think this belongs in the docs.

**Comment by aknuds1** [comment]
@sakjur Shall we close the PR then?

**Comment by sakjur** [comment]
@aknuds1 I suggest letting the docs team do that if they agree with us. It's their domain after all 🙂

**Comment by aknuds1** [comment]
@sakjur ok, I got the impression they would depend on our technical expertise though.

**Comment by oddlittlebird** [comment]
Please do not post it on the Community forums. There are better places to put it. We are still discussing where this content should live.

**Comment by Sumithkr** [comment]
May i know at which stage we are currently now?

**Comment by oddlittlebird** [comment]
Thanks for taking the time to contribute. At this time, we aren't able to accommodate adding deployment instructions specific to different cloud providers in our official documentation. For some context, our documentation team focuses on publishing and maintaining for Grafana's supported OS distributions. Unfortunately, bandwidth doesn't allow us to commit to going through our standard editorial process and ongoing maintenance over time for different hosting providers. You're welcome to publish this elsewhere and share a link to it on our community forums (community.grafana.com) if you'd like to promote it to the wider Grafana community.

**Pull request closed without merging**
