### PR TITLE
Chore: Switch Grafana to using faro libraries

### PR DESCRIPTION
**Pull request by tolzhabayev**
This PR switches from using @grafana/agent-core and @grafana/agent-web to using the new packages:
- https://www.npmjs.com/package/@grafana/faro-core
- https://www.npmjs.com/package/@grafana/faro-web-sdk

What it does not do is renaming all config options to be called faro-something. This has to be more coordinated in a separate PR to see if that will be a breaking change, how it affects grafana cloud config, etc.

### CODE REVIEW

**Review by jackw — COMMENTED** [review]
I believe these packages are also dependencies of runtime. See: https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/package.json

**Comment by tolzhabayev** [comment]
@jackw correct, thanks https://github.com/grafana/grafana/pull/58186/commits/60493ddc1bf512117f30c2b37b7d66e094560376

**Review by ashharrison90 — APPROVED** [review]
great work! lgtm 🙌

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
