### PR TITLE
Dashboards: Provide better error messages in SaveDashboardAsForm

### PR DESCRIPTION
**Pull request by joeblubaugh**
The existing code uses `instanceof Error` to check for a `message` field on the thrown object. The objects that are thrown are never instances of the error interface. This change locally uses `any` so we can check for a `message` field to display instead.

### CODE REVIEW

**Comment by joeblubaugh** [comment]
The code needs to use `any` because throws can only have `unknown` or `any` types. I chose not to use `new Error()` because the `type` field isn't in the constructor. I suppose a custom `extends Error` interface might be usable too.

Before:
Screenshot 2022-10-31 at 10 00 18 AM

After:
Screenshot 2022-10-31 at 9 59 42 AM

**Comment by joeblubaugh** [comment]
How can you override the betterer precommit check? Avoiding the "any" type would require a pretty significant chunk of added work for the same end-user benefit.

**Comment by ashharrison90** [comment]
@joeblubaugh same end-user benefit but worse dev experience 😅 here's a few options in order of preference:
- create a new class that extends Error and throw that instead in `ValidationSrv`
  - either 1 new class (e.g. `ValidationError`) with a `type` property or 2 new classes (e.g. `RequiredError`/`ExistingError`), i'm not sure what our preference is here 🤔 my guess would be the first.
  - check in the catch for whether the error is an `instanceof` that class(/classes)
- wait until the new version of typescript when [this PR](https://github.com/microsoft/TypeScript/pull/50666) is merged
  - this will let you do something like:
  ```typescript
    } catch (e) {
      return e && typeof e === 'object' && 'message' in e ? e.message : 'Dashboard name is invalid';
    }
  ```
- ignore it in betterer by doing `yarn betterer -u`. this will add it to the list of ~4600 `any`s and we'll fix it later i guess.

1 is definitely the preferred option as you can do it right now, it will maintain the stack trace correctly, it's type safe, etc.

**Comment by joeblubaugh** [comment]
I went for the "new class" option. PTAL

**Review by ashharrison90 — APPROVED** [review]
great job! 🙌 lgtm

**Pull request merged**
