### PR TITLE
Add SumoLogic plugin

### PR DESCRIPTION
**Pull request by sasklacz**
**What is this feature?**

SumoLogic enterprise data source

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/plugins-private/issues/940

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by sasklacz** [comment]
Should this be backported ?

**Comment by L-M-K-B** [comment]
@sasklacz What would be the reason to backport it?

**Comment by sasklacz** [comment]
> @sasklacz What would be the reason to backport it?

I don't see one but it's the first plugin I'm adding so just wanted to double check

**Comment by sympatheticmoose** [comment]
> > @sasklacz What would be the reason to backport it?
> 
> I don't see one but it's the first plugin I'm adding so just wanted to double check

If you don't, the the default docs `/latest` wont show this until 10.3.0 is cut...

**Comment by sasklacz** [comment]
> > > @sasklacz What would be the reason to backport it?
> > 
> > 
> > I don't see one but it's the first plugin I'm adding so just wanted to double check
> 
> If you don't, the the default docs `/latest` wont show this until 10.3.0 is cut...

Oh, right. Which version should I set as the backport then ? 10.0 or 10.2 ?

**Review by sympatheticmoose — APPROVED** [review]
docs look fine to me 👍 

Not sure where the source for this and whether its automatically generated, may need to check the website repo https://grafana.com/docs/plugins/

**Comment by sympatheticmoose** [comment]
@sasklacz 10.2 should do it, just current minor

**Pull request merged**
