### PR TITLE
context selection for span name

### PR DESCRIPTION
**Pull request by alburthoffman**
**What is this feature?**

Tempo NativeSearch Console lists all span names without filter by defined service name. The list will be super long and no one could use it without filters. 

**Why do we need this feature?**

As more and more data comes in, there will be more and more span names. At present there are more than 10K span names in our system. It would be helpful if the console only shows possible span names when the end user selects a service name.

**Who is this feature for?**

End users

**Which issue(s) does this PR fix?**:

Fixes # https://github.com/grafana/tempo/issues/1977#issuecomment-1782016945

### CODE REVIEW

**Comment by alburthoffman** [comment]
@joe-elliott @mapno please take a look at this PR. thx

**Comment by joe-elliott** [comment]
This is a cool PR, but I will defer to @grafana/observability-traces-and-profiling to review. I am not an expert at Grafana's codebase :).

Is this using the new filtered labels endpoint to reduce span names by the selected service? Very nice. We should extend this to  any other relevant fields as well.

**Comment by alburthoffman** [comment]
@joe-elliott YES. it will use the new V2 api if defined service name. If no selected service name, it will simply query V2 api.

**Comment by alburthoffman** [comment]
@adrapereira thx for sharing. In that case, we don't need this PR any more. thx

**Review by fabrizio-grafana — COMMENTED** [review]
Closed, as suggested.

**Pull request closed without merging**
