### PR TITLE
disables gosec until identified performance problems

### PR DESCRIPTION
**Pull request by bergquist**

### CODE REVIEW

**Review by markelog — APPROVED** [review]
Oh, damn, yeah we definitely should disable it for right now 
/cc @gcmurphy

**Comment by markelog** [comment]
@bergquist https://discuss.circleci.com/t/increase-4g-memory-limit/9070/4
What do you think?

/cc @xlson

**Comment by xlson** [comment]
@markelog Can you  try to figure out roughly how much memory gosec consumes? Then we can see if it's worth trying to increase the memory on circleci, I presume there is an extra cost associated with that.

**Comment by gcmurphy** [comment]
fwiw https://github.com/securego/gosec/pull/307 fixes this and should be in the latest release..

**Comment by markelog** [comment]
Thank you for the heads up!

Regards,
Oleg

**Pull request merged**
