### PR TITLE
Annotations: Prevent orphaned annotation tags cleanup when no annotations were cleaned

### LINKED ISSUE #33948: Annotation cleaner runs an expensive cleanup query when configured to clean nothing
**What happened**:
We are running Grafana configured with default annotation cleanup options(`max_age` and `max_annotation_age` is not configured in any of the appropriate sections). However, periodically, we encounter availability hits due to e.g. annotations API  endpoints timing out, even saturating serving processes causing failed health checks.

These availability hits were traced to the following query archetype holding locks on `annotation_tags`: 
```
DELETE FROM annotation_tag WHERE id IN ( SELECT id FROM (SELECT id FROM annotation_tag WHERE NOT EXISTS (SELECT 1 FROM annotation a WHERE annotation_id = a.id)  LIMIT 100)
```

**What you expected to happen**:
No annotation cleanup queries. No availability hits :)

Looking at the code, there is no way to configure this query to not be run. I don't understand Grafana well enough to stipulate all scenarios where a row in `annotation_tag` becomes orphaned. However, if the only scenario that this query accounts for is the annotations cleanup, there's a trivial fix: don't run the `annotation_tag` [cleanup](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/annotation_cleanup.go#L51)  when `totalCleanedAnnotations == 0`

If that is all that's needed to fix this, I'd be happy to submit a patch.

**How to reproduce it (as minimally and precisely as possible)**:
To repro you'd have to generate a fairly large `annotation_tags` table and a moderate amount of annotations API traffic.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5-beta3
- Data source type & version: custom
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser: All
- Grafana plugins: lots
- Others: mySQL

### PR DESCRIPTION
**Pull request by afayngelerindbx**
Fixes #33948

### CODE REVIEW

**Comment by bergquist** [comment]
Thanks for catching this. 

@marefr are we sure there won't be any other patch releases before stable 8? Getting this out in 7.5.7 sounds reasonable to me but I guess it depends on how many fixes there are.

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
@bergquist 

> are we sure there won't be any other patch releases before stable 8? 

No, not at the moment. Haven't discussed that with anyone

> Getting this out in 7.5.7 sounds reasonable to me but I guess it depends on how many fixes there are.

As soon as we've branched of Grafana v8.x that means that releasing another 7.x patch needs to make sure backporting into both 8.x and 7.x and there's a potential risk of missing backporting things. But if there's only a few fixes guess we should be able to handle it. If we merge this now we can open backport PR directly and this will automatically be included in 8.x.

I'll create a new 7.5.7 milestone for now and moves this to it.

**Comment by marefr** [comment]
Seems like there was already a 7.5.7 milestone created with a fix in it. So guess we would do at least one more 7.5.x release sometime.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
