### PR TITLE
Grafana/ui: Enable removing values in multiselect opened state

### LINKED ISSUE #77698: MultiSelect: Cannot remove values in opened state
### What happened?

* The remove value button does not work while multi-select is open (This does work in plain [react-select](https://react-select.com/home)) 
* There is no hover effect on the remove button 

[Forms-Select---Multi-Select-Basic-⋅-Storybook.webm](https://github.com/grafana/grafana/assets/10999/03066beb-529e-4467-b0af-9a56cd58d523)

### What did you expect to happen?

For remove button to work. 

### Did this work before?

not sure

### How do we reproduce it?

Go to https://developers.grafana.com/ui/canary/index.html?path=/story/forms-select--multi-select-basic  add values, then try to remove them 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Fe8N**
**What is this feature?**

1. Enabling remove values in opened state
2. Add storybook dev script to the package.json

**Why do we need this feature?**

https://github.com/grafana/grafana/issues/77698

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes #77698 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by FOWind** [comment]
> This pull request has been automatically marked as stale because it has not had activity in the last 30 days. It will be closed in 2 weeks if no further activity occurs. Please feel free to give a status update now, ping for review, or re-open when it's ready. Thank you for your contributions!

@joshhunt If I need to add more information about this PR?

**Comment by Clarity-89** [comment]
@FOWind could you update this branch to the latest main?

**Comment by FOWind** [comment]
> @FOWind could you update this branch to the latest main?

Done

**Review by Clarity-89 — APPROVED** [review]
Looks good! Thank you for the contribution! 🎉

**Comment by Clarity-89** [comment]
@FOWind unfortunately this solution doesn't work for cases where we have other elements in portals that are supposed to be top level: 

Screenshot 2024-01-24 at 15 23 24

I'll revert this PR until we find a better solution for this issue.

**Pull request merged**
