### PR TITLE
TimeSeries: Use graph min/max for percentage threshold

### LINKED ISSUE #37681: Percentage thresholds do not apply
**What happened**:

Percentage thresholds works same as Absolute thresholds. The value I input is treated as an absolute value.

**What you expected to happen**:
Percentage thresholds based on percentage.

**How to reproduce it (as minimally and precisely as possible)**:
bug

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-30560pre (b78a67cec7)
- Data source type & version:
- User OS & Browser: Edge  Beta 93.0.961.11

### PR DESCRIPTION
**Pull request by oscarkilhed**
Fixes #37681

**What this PR does / why we need it**:
Currently the percent threshold is based on data min max. This is confusing when graph min/max is set. The PR sets the threshold to configured hard or soft min/max which should keep the same behaviour for dynamic ranges and make graphs with static ranges less confusing.

### CODE REVIEW

**Comment by torkelo** [comment]
think this looks ok, but the only issue could be if used with soft min/max, what will it use?

**Comment by oscarkilhed** [comment]
> think this looks ok, but the only issue could be if used with soft min/max, what will it use?

Good question, did not think of that. After poking around a bit it looks like the % threshold will move down if the soft min is exceeded and up if the soft max is exceeded. I guess the expected behaviour would be for the threshold to respect the soft min/max, wdyt?

**Comment by leeoniya** [comment]
i think the logic here needs to be more nuanced.

if the min/max of the scale is not user-defined, it is derived from the data y range + ~20% headroom for to allow for an opportunity for the next tick & gridline to show. this means you will never be able to reach thresholds above 80%.

we need to know from the config if the max and/or min is user-set rather than dynamic to determine if either yMin or yMax should be used in place of dataMin and dataMax.

**Comment by oscarkilhed** [comment]
I think it's a bit weird to use the min max of the graph as the basis for the threshold calculation. Using the min/max of the data also seems off. Trying to think of a use-case here. What would actually be useful is to have it be calculated from a query as you said. So that it could be used for a percentage of disk quota or total memory.

**Comment by leeoniya** [comment]
> I guess the expected behaviour would be for the threshold to respect the soft min/max, wdyt?

maybe:

```js
opts.hardMax ?? opts.softMax ?? yMax
opts.hardMin ?? opts.softMin ?? yMin
```

**Comment by leeoniya** [comment]
@oscarkilhed @torkelo 

i've pushed my proposed implementation to this branch for your reviewing pleasure (or horror).

**Review by ryantxu — APPROVED** [review]
LGTM

**Pull request merged**
