### PR TITLE
Add keystone authentication

### PR DESCRIPTION
**Pull request by rbak**
Adds authentication using OpenStack's identity service,Keystone, as well as enables tokens from the keystone authentication to be used in datasources.

### CODE REVIEW

**Comment by torkelo** [comment]
So this looks interesting, as I said in the email (moving conversation here). 


I understand that it can be tricky to picture this as an external component. But might be worth
investigating how the feature can be implemented as proxy to grafana (and to data sources). The integration would then use the Grafana auth proxy feature (or an extension of that feature if it needs to be more capable). 

But if that is not possible and the feature gets many +1 votes then if might make it into mainline grafana. But I am a little hesitant of adding a non standard auth system to Grafana.

**Comment by rbak1** [comment]
The auth proxy feature certainly couldn't handle this right now, but I'll take a closer look today and see if it can be extended.

**Comment by jobrs** [comment]
:+1: 

would be nice to have support for pluggable identity providers

**Comment by roland-hochmuth** [comment]
+1, Would also like to see this added. This will be useful for Monasca as well as potentially useful for Gnocchi (https://github.com/grafana/grafana-plugins/tree/master/datasources/gnocchi) and other OpenStack services.

**Comment by witekest** [comment]
+1 oh yes, it would be great to have

**Comment by rbak1** [comment]
After looking into the auth proxy method yesterday I think I’ve got a handle on how the auth proxy method could work for us, although after discussing it with other members of my team the convoluted solution we came up with was described as “horrific”.  The short version is that Grafana’s concept of orgs is similar to Keystone’s projects, but without any direct communication, keeping the mapping between the two, and ensuring the current org matches the project that’s being used for authentication gets ugly fast. If you want more detail let me know.

Adding a Keystone authentication method to Grafana makes the mapping between the identity systems a lot more seamless. Trying to use the proxy method, even with modifications, would be an ugly solution and might deter other companies hoping to setup Monasca, or any other OpenStack project, with Grafana.

**Comment by bklei** [comment]
+1 on this PR -- and I also share the concerns rbak mentions with the auth proxy method!

**Comment by torkelo** [comment]
@rbak1 can you see any other way? If we change or extend the auth proxy feature? is there a way for Grafana to implement a generic auth provider schema/integration? 

I am just worried about merging in something like this that is hard for the core team to test and evaluate, or support when bugs are issued.

**Comment by Kuckkuck** [comment]
+1 on this PR

**Comment by rbak1** [comment]
@torkelo We're looking into other options for integration at the moment.  I'll get back to you when we know more.

**Comment by Krylon360** [comment]
I wouldn't hard code the API version, but instead parse out of the identity_uri.
Though keystone v2.0 is on its way out the door, it's still widely used in deployments such as RDO Kilo and Mirantis OpenStack 7.0.
Hard coding the API to v3 will cause unnecessary complications.

**Comment by kfox1111** [comment]
+1. This would help our site.

**Comment by nopzor1200** [comment]
We are reviewing how to best add keystone support into Grafana. We are very interested in enabling better support for OpenStack.

**Comment by dhague** [comment]
+1 to this. I already have several changes that would go on top of this code, from minor bugfixes to refactorings, and also various enhancements in the works which are built on using this PR as a base. OpenStack v3 authentication is important to our use-case, and it would be nice to work from and contribute to Grafana's master branch.

**Comment by torkelo** [comment]
as soon as Grafana 3.0 stable is released (1-3 weeks), OpenStack integration is something we will look at for Grafana 3.1 or 3.2

**Comment by dhague** [comment]
Cool - please let me know if I can help in any way.

**Comment by haad** [comment]
+1

**Comment by kornicameister** [comment]
@rbak1 do you plan on pushing this further ?

**Comment by rbak1** [comment]
This patch is actually fairly out of date, but we've been talking with Raintank about how to get keystone auth integrated.  I don't know if it will be in this form, but we're still hopeful to have this at some point.

**Comment by haad** [comment]
Any updates on this, if some work is required I can help as this is quite important feature for us.

**Comment by witekest** [comment]
@rbak1 @torkelo @nopzor1200 Do you know something more about the effort to integrate Keystone authentication to Grafana?

**Comment by rbak1** [comment]
Apparently this PR was to far out of date to update cleanly.  I'll open a fresh pull request.

**Comment by nopzor1200** [comment]
Hi all, we hope to circle back around on this, now that 4.0 is out the door. Thanks to @rbak1 for the recent PR. We will review.

**Pull request closed without merging**
