### PR TITLE
DataFrame: more robust type info

### PR DESCRIPTION
**Pull request by ryantxu**
We currently have a type property:
```
type: string | number | time | boolean | other
```
This is OK, but really does not represent what we need and requires more info as we consider things like arrays of data and 'time' may actually be a number or a string!

This PR replaces the simple type with another nested object:
```
export enum FieldType {
  number = 'number',
  string = 'string',
  boolean = 'boolean',
  other = 'other',
}

export enum MetricType {
  counter = 'counter',
  gauge = 'gauge',
  histogram = 'histogram',
  summary = 'summary',
}

export enum SemanticType {
  time = 'time',
  latitude = 'latitude',
  longitude = 'longitude',
  geo = 'geo', // GEOJSON object
}

export interface TypeInfo {
  value: FieldType;
  isArray?: boolean; // The values in a cell are an array (currently not really supported)
  metric?: MetricType;
  semantic?: SemanticType;
}
```

### CODE REVIEW

**Comment by marefr** [comment]
Can you give some examples of usage and/or how this would be encoded in arrow?

**Comment by ryantxu** [comment]
> Can you give some examples of usage and/or how this would be encoded in arrow?

Similar/identical to how we set the `config` -- essentially a JSON object saved in the metadata under the 'type' object.

**Comment by ryantxu** [comment]
@kylebrandt -- any thoughts?  most of the PR is dealing with changing `field.type` to `field.type.value` -- and weird things that fall from using "time" as a type on the same level as "number" (even though times are actually represnted as strings or numbers!)

**Comment by kylebrandt** [comment]
**Field Type:**

Currently the backend has no corresponding `Field.Type` property:

```
// Field represents a column of data with a specific type.
type Field struct {
	Name   string
	Config *FieldConfig
	Vector Vector // TODO? in the frontend, the variable is called "Values"
	Labels Labels
}
```

This is because the Vector is typed so that information exists in the type itself (or methods on the Generic-ish `Vector` to get the underlying primitive slice type. So in the backend it doesn't currently have a place ... but I think where this goes is getting a bit ahead...

**Semantic Type:**

I am a bit fuzzy on the intent of this one. Conceptually I understand that one might store time in a database as an some type of integer. However, I am concerned that we might be conceptually overloading this property.

To continue the example of time as an integer, a semantic type of "time" is not enough information to deterministically reconstruct a datetime from the field. This is because the format of the time is information that is needed but not present.

So my concern is that what we are doing for Semantic type is not specific enough, or perhaps that some of this might be more appropriate for the Field's config (if this is more fuzzy and for display only). 

I think maybe more specific use cases around Semantic type could clarify?

**Comment by ryantxu** [comment]
When using arrow, two of the properties on `TypeInfo` are not relevant -- they should be derived from the arrow structure:
```
export interface TypeInfo {
  value: FieldType;    // <<< not needed with arrow... derived from the actual type
  isArray?: boolean;  // <<< same (but array not really supported yet)
  metric?: MetricType;
  semantic?: SemanticType;
}
```

Semantic type could give us a way to say "this column means something" independent from what the data is.  The examples I proposed are:
```
  time = 'time',
  latitude = 'latitude',
  longitude = 'longitude',
  geo = 'geo', // GEOJSON object
````
time, lat, lon -- are all just numbers...  geojson would be a JSON object (string in arrow)

**Comment by ryantxu** [comment]
In go, I think it would be added something like:
```
type Field struct {
	Name   string
	Config *FieldConfig
	TypeInfo *TypeInfo
	Vector Vector // TODO? in the frontend, the variable is called "Values"
	Labels Labels
}
```

In go/arrow we could also drop the `value` and `isArray` attribute since they should be derived from the arrow type.

**Comment by ryantxu** [comment]
alternatively we could consider adding `semanticType` and `metricType` to FieldConfig.

In javascript -- we would still need some indication of isArray.

For dates represented as strings, we will also need a place to specify what the incoming format is 🤔

**Comment by kylebrandt** [comment]
> For dates represented as strings, we will also need a place to specify what the incoming format is

I think is true of numbers as well. For example in many of my apps, I store time in the database as a centisecond count since my personal birth datetime.

**Comment by torkelo** [comment]
Any status on this? What is left?

**Pull request closed without merging**
