### PR TITLE
Explore/Tooltip: Fix label value in tooltip

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Brought up by @marcusolsson on slack: 
>In the dashboard, the tooltip shows the name of the time series, whereas in Explore more, it says “Value” for any time series, which makes it difficult to know which time series you’re looking at.

**React graph:**
image
**Angular graph:** 
image

This PR fixes this by preferring `field.config?.displayName` or `field.state?.displayName` and fallbacks to `field.name` which is in many cases **Value**.

**What should the reviewer know:**

In Loki, the series name was under `field.state.displayName`  and not the `field.config.displayName`. Is this correct?

### CODE REVIEW

**Review by tskarhed — APPROVED** [review]
Looks good to me! Can't say for sure about Loki, but I tried it; seems to work!

**Comment by torkelo** [comment]
Should use the function getFieldDisplayName it has does the logic of figuring out what display name to show (from field name or display name etc)

**Comment by ivanahuckova** [comment]
Thanks @torkelo! Updated. 🙂

**Review by dprokop — APPROVED** [review]
Looks good!

**Pull request merged**
