### PR TITLE
New icon for alert list

### LINKED ISSUE #16990: Alert icons for alerting and ok are to similar
We are currently using a green heart for OK and a broken red heart for alerts. The shape of these icons are very similar and relies a lot on color to show the user when there is an alert. This can make it difficult for users that are color blind. 

Current:
Screenshot 2019-05-10 at 09 38 43

My suggestion for a first step:
Screenshot 2019-05-10 at 09 51 42

### PR DESCRIPTION
**Pull request by Ijin08**
Created red version of alert icon.
Replaced icon for alerting in alert list with new red icon

Screenshot 2019-05-29 at 09 44 56

fixes #16990

### CODE REVIEW

**Comment by torkelo** [comment]
This requires an update to panel title & alert list & alert history view as well so we are consistent. 

Screen Shot 2019-05-29 at 09 52 39

We also have red hearts in the threshold handles. 

Not 100% sure what the best solution for this is. What do other alerting solutions do?

**Comment by torkelo** [comment]
ah, this updated the def file so it should update everywhere. Can you show screenshots of all locations where this will change?

**Comment by Ijin08** [comment]
It didn't update anywhere that I could find except for the alert list panel. Haven't checked alert history yet. Will look into updating panel title.

**Comment by bergquist** [comment]
Hm. Not sure I like the new icon. the OK/Critical followed the same pattern.

**Comment by Ijin08** [comment]
@bergquist The thing with the current Ok/Critical is that they look too similar. If a user has it hard to differentiate red and green it also makes it hard to see if there is an alert. I agree with that the bell and the green heart don't go that well together. My hope is that the heart will be replaced soon as well since it is a legacy icon. 
Maybe this should wait until we have new icons for Ok, no data and pending?

**Comment by torkelo** [comment]
> Maybe this should wait until we have new icons for Ok, no data and pending?

I think so as using heart and bell feels strange, For the alert list we could remove the icon and just use text, but for the panel & drag handle an icon feels more appropriate.

**Comment by bergquist** [comment]
> For the alert list we could remove the icon and just use text
Agree!

**Comment by torkelo** [comment]
Closing this PR as this approach (changing icon) feels like it needs a bigger icon redesign

**Pull request closed without merging**
