### PR TITLE
Send test notification fixed

### PR DESCRIPTION
**Pull request by utkarshcmu**
Was not able to send test notification and was getting "panic: runtime error: index out of range" so fixed that here!

### CODE REVIEW

**Comment by bergquist** [comment]
The problem is fixed with this commit. https://github.com/grafana/grafana/commit/5542b0ab9eff0bfbda574c57e4108fa9be0dc4ba

**Comment by utkarshcmu** [comment]
The problem is not fixed with that commit. I am still not able to send a "Test" incident to pagerduty from current grafana master. Try clicking on "Send Test" using master branch!

**Comment by utkarshcmu** [comment]
The notifications from the alerts will work with that fix commit but the Test notification will be fixed by the change in this PR.

**Comment by bergquist** [comment]
Sorry! your right :)

**Comment by utkarshcmu** [comment]
@bergquist Awesome. Thanks!

**Pull request merged**
