### PR TITLE
tech(config): add log.mutes as an option for silencing logs

### PR DESCRIPTION
**Pull request by gotjosh**
**What this PR does / why we need it**:

This commit adds a new configurable option to mute/silence logs from the config file.

Users can specify the name of the logger in question thus avoiding any output from that particular logger.

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Not sure about this as configuration. If the need is to mute the info logs from certain loggers we should be able to do that in code either using existing `filters = logger:error` functionality by calling some code from the cli or either initialize services/loggers with a certain level - Not sure whether any of this is possible though?

**Comment by gotjosh** [comment]
@marefr the current implementation does not allow that. The key here is part of:

https://github.com/grafana/grafana/blob/d0852f061807f1e6f379091483cf99c775f43745/pkg/infra/log/log.go#L252-L271

which as per lines 262 and 269 checks for anything below the specified log level. 

I opted to implemented the feature as both @xlson and I were under the impression this was currently a part of `filters` config option and it seems to be useful for us to control output as continue to make CLI improvements.

**Comment by torkelo** [comment]
Not sure i understand this. I can change the log level from the default to silence messages with filters as well. 

example: 

level = info
filters = context:error

I now no longer get any info log message from the context logger.

**Comment by gotjosh** [comment]
Sorry about this one @torkelo and @marefr - this was entirely on me. I've used the debug as a level when I was testing which could cause to include the info logs as well.

**Pull request closed without merging**
