### PR TITLE
Search: Migrated impressions to use dashboardUID

### LINKED ISSUE #52065: Migration: Impression server should be based on UID, not IDs
In an effort to remove dependencies on internal IDs, we should update the https://github.com/grafana/grafana/blob/68757cfa73cb675b8f3013f5e33a0e43ae40849a/public/app/core/services/impression_srv.ts#L9

So we track and manage UIDs in the frontend, not numeric IDs.

Right now the numeric IDs need to be converted to UIDs before we can use them:
https://github.com/grafana/grafana/blob/5ad27679549d6c9f2ea49a1fcb5ef9de6754ff1c/public/app/features/search/page/components/FolderView.tsx#L37-L38

In addition to this... it seems the impression server does not save values unless *something* has been starred -- I don't know if that is a related or independent bug

### PR DESCRIPTION
**Pull request by lpskdl**
**What this PR does / why we need it**:

This change will use `dashboardUID` instead of using `dashboardId` when retrieving impressions/recently view dashboards. This is needed to support the [backend migration](https://github.com/grafana/grafana/issues/48331f ) from using dashboardId with dashboardUID of nested folders for the new Search feature.

https://user-images.githubusercontent.com/108552997/182319951-7ac16437-3301-4667-9627-8f8ed79a4598.mov

**Which issue(s) this PR fixes**:

Fixes #52065 

**Special notes for your reviewer**:
- ~~This might impact the recently viewed dashboard by our users as the ids saved in their `localstorage` are based in `dashboardids`. After this implementation, previous recently view dashboards will not be visible but only the new recently ones. **_Do we need to inform our users about this?_** or we _**should support both type of ids until the migration is done**_? or _**it's totally fine to not include previous recently viewed dashboard after we release this change**_?~~

https://user-images.githubusercontent.com/108552997/182318401-63504706-a9a3-4e83-8ea3-522925faecac.mov

This is solved by converting ids to uids and saved it back to the storage. A separate [issue](https://github.com/grafana/grafana/issues/53193) is created to remove it after migration.
https://user-images.githubusercontent.com/108552997/182565595-db3989d3-f2b2-4eea-bed5-53e3ed09ff2c.mov

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Great job, @lpskdl 🎉 , answering your questions,

> Do we need to inform our users about this? or we should support both types of ids until the migration is done? or it's totally fine to not include the previously recently viewed dashboard after we release this change?

I think it can be disrupted for our users if their "recent's dashboards" disappear, especially when we have Grafana instances with thousands of dashboards.


**simple idea:** maybe we could add an extra check (sort of migration) in our code:
if we find an existing array of `ids` in the local storage, do an extra HTTP request, with those `ids`, get the UID's and update the local storage?

**Comment by lpskdl** [comment]
Hi @axelavargas ,
Thank you for the idea. I'm checking where `impression_srv` is used. It is being used in several areas, which are `search_srv`, `DashboardLoaderSrv`, `plugin_loader`, `FolderView`, and `DashList`. I am thinking to do this right after app initialization, like firing an action which will run a thunk that converts this ids to uids in the localstorage. Could you guide me how I could achieve this in a grafana way. Not so sure where to touch stuff. Thanks a lot

**Comment by axelavargas** [comment]
> Hi @axelavargas , Thank you for the idea. I'm checking where `impression_srv` is used. It is being used in several areas, which are `search_srv`, `DashboardLoaderSrv`, `plugin_loader`, `FolderView`, and `DashList`. I am thinking to do this right after app initialization, like firing an action which will middleware a thunk that converts this ids to uids in the localstorage. Could you guide me how I could achieve this in a grafana way. Not so sure where to touch stuff. Thanks a lot

🤔 maybe we could add this into the constructor of `ImpressionSrv`?

**Comment by lpskdl** [comment]
> 🤔 maybe we could add this into the constructor of `ImpressionSrv`?

yeah. I thought of that but it could cause a raise condition as this will be an asynchronous call 🤔

**Comment by lpskdl** [comment]
im also thinking to convert getDashboardOpened() to asynchronous calling getBackendSrv inside it get the equivalent UIDs but it feels like hack-ish approach

**Comment by lpskdl** [comment]
Hi @axelavargas , I've pushed a way how to solve the issue on preserving the recently viewed dashboards of the user. Let me know if that's fine or I need to revise. thanks a lot

https://user-images.githubusercontent.com/108552997/182596556-cf5d1711-6910-491d-9482-b1053fee021d.mov

**Comment by axelavargas** [comment]
Hey @lpskdl , the approach looks awesome, but there was one minor thing while testing, for a weird reason when disabling the feature flags, the impression service is not converting to UIDS 🤔, take a look at the video

Side note: I did the test with a different org

https://user-images.githubusercontent.com/239999/182624423-08eb6f21-29ec-42c6-b4e9-80ec444dd6a9.mp4

**Comment by lpskdl** [comment]
> Hey @lpskdl , the approach looks awesome, but there was one minor thing while testing, for a weird reason when disabling the feature flags, the impression service is not converting to UIDS 🤔, take a look at the video
> 
> Side note: I did the test with a different org
> 
>  FeatureToggleOffDoesNotConvertToUID.mp4 
> Ps, while testing your PR, I found a different issue, 🤔 it could be related? #53231

Thanks @axelavargas , While playing around it, It seems the issue is related to `annotations/api` it is failing when `panelTitleSearch` is off.  

Hi @ying-jeanne , do you know if we could support it again when toggle is off? It seems to behave like that before(`after checking out my branch about annotations migration`)

**Comment by lpskdl** [comment]
Hi @axelavargas , It seems the issue on the backed is fixed. I was now able to test the scenarios on both feature toggle state

https://user-images.githubusercontent.com/108552997/183369412-0c11fe90-325b-4703-b55b-8b5e2d7ccde8.mov

Could you please check again whenever you are free. Thanks a lot!

**Review by axelavargas — APPROVED** [review]
@lpskdl You did an amazing job with this issue 🥳, everything works as expected with and without the feature flag!

**Pull request merged**
