### PR TITLE
Chore: Remove deprecated layout components from Plugins Platform

### LINKED ISSUE #86878: Deprecated layout components: get rid of `Layout.tsx` including `HorizontalGroup` and `VerticalGroup`
**What is the chore?**:
The grafana-frontend-platform squad has created a ['non-roadmap' epic](https://github.com/grafana/grafana/issues/85510) to remove the usage of the deprecated layout components: `Layout`, `HorizontalGroup` and `VerticalGroup`. 

**Is there anything else we need to know?**:
- This is a side project. No prioritization. Just keep in mind when there are downtimes, or you need a break and work on something less complicated.
- In most cases, you just will need to:

Replace `HorizontalGroup`
```jsx 
<HorizontalGroup spacing="lg">
...
</HorizontalGroup>
```
with `Stack`
```jsx 
<Stack gap={3}>
...
</Stack>
```
or replace `VerticalGroup`
```jsx 
<VerticalGroup spacing="md">
...
</VerticalGroup>
```
with `Stack` using `direction`
```jsx 
<Stack direction="column" gap={2}>
...
</Stack>
```
- To change `spacing` to `gap` you can take a look at the equivalences in [the `Layout` component](https://github.com/grafana/grafana/blob/f6e472f8797cde4dfdc3ab4f1fc3fc5969b7c8fe/packages/grafana-ui/src/components/Layout/Layout.tsx#L172).

#### Remove `Layout`
- [ ] public/app/features/plugins/admin/components/PluginDetailsPage.tsx
#### Remove `HorizontalGroup`
- [ ] public/app/features/plugins/admin/components/Badges/PluginEnterpriseBadge.tsx
- [ ] public/app/features/plugins/admin/components/InstallControls/ExternallyManagedButton.tsx
- [ ] public/app/features/plugins/admin/components/InstallControls/InstallControlsButton.tsx
- [ ] public/app/features/plugins/admin/components/InstallControls/InstallControlsWarning.tsx
- [ ] public/app/features/plugins/admin/components/PluginActions.tsx
- [ ] public/app/features/plugins/admin/components/PluginListItemBadges.tsx
- [ ] public/app/features/plugins/components/PluginsErrorsInfo.tsx

**Thanks in advance for your collab! 🙌**

### PR DESCRIPTION
**Pull request by PhishyFish**
**What is this feature?**

Replaces `Layout`, `HorizontalGroup`, and `VerticalGroup` with `Stack` in:
- public/app/features/plugins/admin/components/PluginDetailsPage.tsx
- public/app/features/plugins/admin/components/Badges/PluginEnterpriseBadge.tsx
- public/app/features/plugins/admin/components/InstallControls/ExternallyManagedButton.tsx
- public/app/features/plugins/admin/components/InstallControls/InstallControlsButton.tsx
- public/app/features/plugins/admin/components/InstallControls/InstallControlsWarning.tsx
- public/app/features/plugins/admin/components/PluginActions.tsx
- public/app/features/plugins/admin/components/PluginListItemBadges.tsx
- public/app/features/plugins/components/PluginsErrorsInfo.tsx

**Why do we need this feature?**

Removes deprecated components

**Who is this feature for?**

@grafana/plugins-platform-frontend

**Which issue(s) does this PR fix?**:

Fixes #86878

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
Hi @PhishyFish,
Looks good to me, but I'd appreciate a ✅ from the @grafana/plugins-platform team, since they are the owners of these files.

**Comment by PhishyFish** [comment]
Hi @sympatheticmoose and @eledobleefe, it seems like the build is erroring out because it is attempting to pull this branch from the main repository, but it only exists on my fork. Is there anything I can do to move this along?

**Comment by sympatheticmoose** [comment]
Hi @PhishyFish - thanks again for your contribution. @Ukochka would you be able to take a look to confirm these changes are good to merge? I've ran locally and seems fine but would still appreciate your review 🙏

**Review by Ukochka — APPROVED** [review]
LGTM!

**Comment by jackw** [comment]
@PhishyFish many thanks for contributing to Grafana! 🏅

It seems we have a few issues with this PR which I think can mostly be solved with syncing upstream with the branch. Once that's done we should be able to solve the conflict with betterer by running `yarn betterer -u`.

Apologies for any bother this causes you. If you prefer I'm happy to help get this over the line by pushing the changes to the branch/PR directly.

**Comment by PhishyFish** [comment]
Hi @jackw, thanks for the follow-up. I've synced the branch and ran Betterer on the changes. Hopefully this resolves the issue!

**Comment by jackw** [comment]
Awesome stuff @PhishyFish. Thanks again for contributing! 🚀

**Pull request merged**
