### PR TITLE
Add support for Swift as external image store

### LINKED ISSUE #8189: [Feature request] Swift for external image storage
It would be nice to be able to store generated pngs in Openstack Swift as well as S3 and Webdav. 
(PR will be opened in a minute)

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #8189.

The integration test requires access to a Swift installation, I extracted the connection details so they are set via environment vars for those.

### CODE REVIEW

**Comment by carlpett** [comment]
Forgot to vendor the gophercloud lib, fixing that!

**Comment by torkelo** [comment]
Do we need to include the google swift library for this? hm.. this might have to wait for backend plugins: https://github.com/grafana/grafana/issues/6841

**Comment by carlpett** [comment]
There is a google Swift library? It seems like I actually didn't fix the vendoring properly, though, I'll try to fix the fix. For some reason govendor pulled in nested vendor directories, so I did a bit of manual pruning, seems like I overdid it.

**Comment by carlpett** [comment]
@torkelo Could you expand on your comment? I do not believe any further libraries are needed, if that affects the go/no-go of this before the plugin system is implemented.

**Comment by torkelo** [comment]
I was just wondering if we could just use http client, so we do not need the swift dependency

**Comment by carlpett** [comment]
@torkelo Sorry for the delay. 
Regarding eliminating the dependency, it would involve a substantial amount of code to do so. So I do not think that would be a worthwhile trade-off. Especially the login flow is rather complex and depends a lot on the individual deployments.

**Comment by bergquist** [comment]
Thanks for contributing but we have to reject this PR. We cannot take on the maintenance burden of something we know so little about. The amount of vendoring for this nisch feature is also troubling. 

Once we add support for backend plugins ( https://github.com/grafana/grafana/issues/6841 ) this could be made into a plugin. Until then you could build Grafana yourself and apply this patch. I hope this wont discourage you from contributing in the future.

**Pull request closed without merging**
