### PR TITLE
Datatrails: hide empty breakdown panels, improve loading status

### PR DESCRIPTION
**Pull request by darrenjaneczek**
**What is this feature?**

Detect panels with no data, and omit them from being shown.
This avoids "No data" panels, and the confusing `<unspecified>` No data panel.

A status message indicates that there are no results for the current selection.

Loading states have been improved somewhat.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by catherineymgui** [comment]
Could we update the empty state message from `No data available for current selection...` to `This is no data available. Try adjusting your filters.` 

Looks nice otherwise!

**Comment by darrenjaneczek** [comment]
Updated to the following, @catherineymgui: 

> There is no data available. Try adjusting your filters or selecting a different label.

**Comment by darrenjaneczek** [comment]
May also want to mention the time range, which could impact "no data".

**Comment by catherineymgui** [comment]
Try selecting a different label or time range?

**Comment by darrenjaneczek** [comment]
Updated to the following, @catherineymgui: 

> There is no data available. Try adjusting your filters, adjusting your time range, or selecting a different label.

**Comment by darrenjaneczek** [comment]
@catherineymgui 

image

**Review by catherineymgui — APPROVED** [review]
looks good, thank you!

**Pull request merged**
