### PR TITLE
Docs: Adds video embed for the Understanding Dashboards youtube video

### PR DESCRIPTION
**Pull request by tomglenn**
Adds youtube embed on dashboards page for https://www.youtube.com/watch?v=vTiIkdDwT-0

### CODE REVIEW

**Comment by tomglenn** [comment]
Hi @imatwawana, please let me know if there's anything else you need from me on this one. :)

**Comment by imatwawana** [comment]
Hey @tomglenn, I was away at an offsite last week so I'm just catching up on PR reviews today. I'll let you know if there are any changes needed.

**Comment by imatwawana** [comment]
@tomglenn, the feature landing page where you've added this video is not meant to be a page that readers stay on, but use it to get a quick overview and move on to other pages. This is a standard we're spreading across docs, so it doesn't align for us to add it here. I'm going to push a change on this PR to a page where I think this will make more sense.

**Review by imatwawana — COMMENTED** [review]
@tomglenn, the feature landing page where you've added this video is not meant to be a page that readers stay on, but instead use to get a quick overview and move on to other pages. This is a standard we're spreading across docs, so it doesn't align for us to add the video here. I'm going to push a change on this PR to add the video a page where I think it will make more sense. Take a look and let me know if this works for you.

**Comment by tomglenn** [comment]
@imatwawana that makes total sense! Happy for the change to go ahead. 👍

**Review by imatwawana — APPROVED** [review]

**Pull request merged**
