### PR TITLE
Added currency units, time units, tests

### PR DESCRIPTION
**Pull request by utkarshcmu**
Added the following:
1. 2 more currency units - Euro, Yen
2. Time units - Minute, Hour, Day.
3. Unit tests for Second, Minute, Hour, Day units.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Also, fixed #1950.

**Comment by utkarshcmu** [comment]
Can we get this PR merged if it does not add too much complexity? need "Yen" as the currency unit mainly. :)

**Comment by marcoalbarelli** [comment]
+1 for this PR

**Comment by utkarshcmu** [comment]
@torkelo ping :)

**Comment by mohierf** [comment]
:+1:

**Comment by addshore** [comment]
+1

**Pull request merged**
