### PR TITLE
[Feature] Custom Default Colors Palette

### PR DESCRIPTION
**Pull request by CME64**
**[Recreated] with updates**:

- Changed files reduced by untracking public/dist directory and adding it to the ignore file
- A [feature request was created for this PR](https://github.com/grafana/grafana/issues/17092) and seems to have gotten some interest so far
- Screenshots added
- minor addition to the expectations section

**New Features**:

- New control called "ColorsLine" to select multiple colors for better adjacent visibility and easy control
- Dashboard panels' series default colors can be customized per panel or dashboard with respect to old features like aliasColors and the default color pallette (backward compatible)

Dashboard settings:
image

Graph panels:
image
 

**Expectations**:
1. You will find a new setting in the dashboard settings page with a switch button and a ColorsLine control
2. You will find a new setting in the graph panel (only this panel so far because it's the only one using coloring for series in the package) settings page with a switch button and a ColorsLine control
3. When you apply a custom colors pattern into the dashboard settings it will apply to all panels that implement that feature within the same dashboard (inherit the colors)
4. When you apply a custom colors pattern into the panel (graph so far) it will apply only to that panel overriding the inherited colors
5. If you don't apply any customization the default colors pattern will be used
6. Series will cycle colors among the pattern defined in respective order
7. Alias colors will override all colors settings for the specified series
8. If custom colors is activated you'll see an indicator saying (custom) next to the colors label meaning that you're seeing the defined custom colors you defined on the chart, otherwise it will show where it's coming from either (dashboard) to indicate custom dashboard colors or (global) for default custom colors[check the below photos for reference].
9. An information indicator is shown in edit mode (custom) to hint for the removal action using CTRL

image

image

**how to use the control**:
1. If the switch is turned off (custom colors) the colors cannot be modified (view only mode), turn it on to start the customization
2. Click the plus (+) button in order to add more colors (there are (+) buttons between each couple of colors too to insert in the middle and they appear on hovering the area)
3. New colors will be added randomly everytime you add one (using the original colors pattern as the source)
4. Click on the color to display the color picker (with named colors enabled) and change it to your liking
5. Use CTRL+Click on the color to remove it

**notes**:
1. Changing colors will only affect the rendering and it will not request the query or update the data on every change.
2. Series will use the colors from the color pattern in respective order and cycle back if the colors are less than the series
3. Even if you define custom colors, alias colors will still apply and cannot be affected until unconfigured
4. You can set the colors from the json of the panel or the dashboard by adding string hex colors array in the property "colors" (to keep things clean in the UI you should set customPalette to true when filling the colors)
5. The control can still be enhanced to add a popup text editing feature although it is available from the panel/dashboard json text settings.

**Why it should be merged**:
- All of our clients who we used grafana dashboards for requested this feature
-  I found another [old request about the exact same topic](https://github.com/grafana/grafana/issues/843) and it got also [some interest by people](https://github.com/grafana/grafana/issues/843#issuecomment-374345749) and it was closed for low priority as it seems and I'm sure more people would want to have it too
- I understand that when more than one user asks for some feature then there is a need for it, and priority is defined depending on the need, cost of development and implication of that feature
- Priority to develop the feature should be ignored if the feature has been already developed with 0 cost for merging  and having it.
- I don't really know why you're putting walls denying my contribution to this great project when it indeed adds more value to the solution and you already know that it has been requested before

### CODE REVIEW

**Comment by CME64** [comment]
@torkelo I have done what you asked in [this comment](https://github.com/grafana/grafana/pull/17076#issuecomment-492600998) 
kindly review the changes and check the "why it should be merged" part

**Comment by CME64** [comment]
@torkelo if you're too busy to review it before it becomes obsolete, please tag someone who can do it.

**Comment by torkelo** [comment]
Hi, 

Sorry. We are not sure this is the right thing to add right now. If we are to do this it would have to start as a backend setting feature to add custom named color palettes that would hook into our named colors  feature. 

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/namedColorsPalette.ts

So closing this until we see more interest in this feature.

**Comment by CME64** [comment]
@torkelo 
can you please explain why your suggested solution is better than mine?
I don't see it is for the following reasons:

1. you will have to access the server in order to add colors to a config file
2. you will have to do that every time you map it to something like orgs, teams, dashboards or whatsoever.
3. it doesn't provide much flexibility in terms of reconfiguration and specific dashboards/panels.
4. it does't show how colors will look like next to each other without external tools (important to see the expected results before applying them)

I can think of more reasons that my solution is better than the quick thought you threw in your comment.
I think that was a rash decision and it was based on this feature not being designed by your team or following your style even though it wasn't in your plan at all (I checked the project's board and you have already said that it's not planned yet). but let me remind you that this product is for the community too and people asked for it when you dodged the topic 4 years ago and some are still asking if it will ever get implemented.

If contribution has to be just coding your designed solutions to save your time then I don't want to do that. In fact I have lost interest to contribute to this project anymore, I feel like I stepped an unwelcoming territory even though I had more ideas and contributions in mind. I'll just let it go.

**Comment by CanKattwinkel** [comment]
@CME64 @torkelo hi there,
 
in a few weeks, I will be entrusted with adapting a Grafana based monitoring to the CI of the customer. During my research, I came across this ticket, what is currently the best way to create your own Grafana theme?

The question is probably a bit whether the settings are used at runtime or compile time, the AngularJS and React Mix don't make it any easier either. It would be great if a theming could be applied without forking the project - from what I see the styles are generated at compile time, which is IMHO good. But it would also be nice if a custom style could be generated and attached to Grafana e.g. at Runtime or applied in a custom build that more or less does not require a fork but e.g. additional build steps that could fit into a Dockerfile.

What are your thoughts on this?

**Comment by torkelo** [comment]
> What is currently the best way to create your own Grafana theme?

This issue has nothing to do with custom UI theme, for that you need to fork Grafana and modify the theme variable files (we have 2 for the dark & light themes)

**Comment by CME64** [comment]
@CanKattwinkel Hi,
There is no compile time for either of the methods.
The current implementation uses a config file on the server which applies globally on the whole instance of the system and can be read in run-time. What I added was a way to do the same customization from the UI (not requiring server access) and not for the whole system instance but instead for a specific dashboard or panel also in run-time. Torkelo has dismissed the idea in favor of using more config files for each custom dashboard/organization.

let's try a scenario here. Let's say we are defining the colors per dashboard or organization or whatever and call that unit X.

The steps using UI should be (no server files access):
1- add X using UI tools
2- customize colors of X using UI tools

this allows anyone with edit permissions to change the colors per dashboard or panel depending on their access permissions on the system, so you can actually give the permission to the client to change the colors template themselves.

but using config files will make it like this:
1- add X using UI tools
2- access the server config files (using FTP or whatever and you have to have access to the server files)
3- create a new colors config/config file for X

you can't actually give the client access to your server files especially if you are using the same system instance for multiple clients. so you have to do the change from the server config files every time someone adds a new X.

**Comment by mountrcg** [comment]
@CME64 that might be a stupid question, but I spent 45min trying to find the 2 options you show in your screenshots in the original post. Could you give me a hint? I am 2 days into Grafana.

**Comment by ellieatmerqury** [comment]
I'm assuming after 2 years this won't be merged?

**Comment by BrianLeishman** [comment]
> Hi,
> 
> Sorry. We are not sure this is the right thing to add right now. If we are to do this it would have to start as a backend setting feature to add custom named color palettes that would hook into our named colors feature.
> 
> https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/namedColorsPalette.ts
> 
> So closing this until we see more interest in this feature.

Since your link is dead now, will you consider this again?

**Pull request closed without merging**
