### PR TITLE
Loki: Decouple from `infra/tracing`

### PR DESCRIPTION
**Pull request by fabrizio-grafana**
Following our last meeting on decoupling, I've investigated `pkg/infra/tracing`, but it seems quite different from `grafana-plugin-sdk-go/backend/tracing`, so I don't think we can use the latter one directly in the Loki plugin.

This is a first PR to decouple the Loki plugin from pkg/infra/tracing. At the moment it simply pkg/infra/tracing into the plugin itself. We can consider moving some stuff into `grafana-plugin-sdk-go/backend`, although IIRC there were some concerns on this during the meeting, so it has to be investigated more.

Let me know what you think of this first proposal, so that we can iterate on this.

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@fabrizio-grafana Could you share more details on - "but it seems quite different from grafana-plugin-sdk-go/backend/tracing".

**Comment by fabrizio-grafana** [comment]
> @fabrizio-grafana Could you share more details on - "but it seems quite different from grafana-plugin-sdk-go/backend/tracing".

Sure. I simply mean that, looking at the code in `grafana-plugin-sdk-go/backend/tracing`, this seems quite limited compared to the one of `pkg/infra/tracing`. In fact, `grafana-plugin-sdk-go/backend/tracing` contains less than 100 LOCs, which only seem to deal with basic setups of tracers, while instead `pkg/infra/tracing` has ~500 LOCs that deal with more convoluted tracers. 

I can investigate more the differences, but so far `grafana-plugin-sdk-go/backend/tracing` doesn't look like a drop-in replacement for `pkg/infra/tracing`. As such, trying to use and potentially adapt the former for Loki could take some time and even cause some regressions, that's why I was proposing to do use `grafana-plugin-sdk-go/backend/tracing` only later.

Of course if I'm missing something and you have more knowledge of what the two packages do, feel free to correct me!

**Comment by ivanahuckova** [comment]
@svennergr curious about your thoughts on this, but I would personally probably go with `grafana-plugin-sdk-go/backend/tracing` as that's what azure/tempo/pyroscope/influx/... are using and only if we see that it is not sufficient, I would go with copying `infra/tracing`. As we are the only current consumers of that traces, we can re-evaluate.

**Comment by svennergr** [comment]
> @svennergr curious about your thoughts on this, but I would personally probably go with `grafana-plugin-sdk-go/backend/tracing` as that's what azure/tempo/pyroscope/influx/... are using and only if we see that it is not sufficient, I would go with copying `infra/tracing`. As we are the only current consumers of that traces, we can re-evaluate.

Agree. Took a quick stab at using the otel tracer: https://github.com/grafana/grafana/pull/85213

Looks like it's working well? Feel free to take over my PR @fabrizio-grafana

**Comment by fabrizio-grafana** [comment]
> Took a quick stab at using the otel tracer: https://github.com/grafana/grafana/pull/85213

Thanks for the initial testing! 

> Looks like it's working well?

Just to understand and avoid misunderstandings: Did you already check that the tracer from `grafana-plugin-sdk-go/backend/tracing` preserves all functionalities, or just that we don't have compile and runtime errors if we use it instead of the one from `github.com/grafana/grafana/pkg/infra/tracing`? For example, did you check if it preserves things like the trace ID? (If you remember, we discussed that `github.com/grafana/grafana/pkg/infra/tracing` seems to have a [dedicated wrapper](https://github.com/grafana/grafana/blob/main/pkg/infra/tracing/tracing.go#L80) for logs to always include the trace ID.)

**Comment by fabrizio-grafana** [comment]
@svennergr ping for this 🙏

**Comment by svennergr** [comment]
> Just to understand and avoid misunderstandings: Did you already check that the tracer from `grafana-plugin-sdk-go/backend/tracing` preserves all functionalities, or just that we don't have compile and runtime errors if we use it instead of the one from `github.com/grafana/grafana/pkg/infra/tracing`? For example, did you check if it preserves things like the trace ID? (If you remember, we discussed that `github.com/grafana/grafana/pkg/infra/tracing` seems to have a [dedicated wrapper](https://github.com/grafana/grafana/blob/main/pkg/infra/tracing/tracing.go#L80) for logs to always include the trace ID.)

Sorry. IIRC I checked that it preserved the traceID, yes.

**Comment by fabrizio-grafana** [comment]
> Did you experience something else?

Nothing that I could reproduce so far. I just wanted to check since I was saying the code seems quite different, and I don't know all the ins and outs of Loki plugin.

**Pull request closed without merging**
