### PR TITLE
Added missing enterprise plugins in upgrade page

### PR DESCRIPTION
**Pull request by yesoreyeram**
Added missing enterprise plugins in upgrade page
* New Relic
* Amazon Timestream

### CODE REVIEW

**Review by sakjur — APPROVED** [review]

**Comment by sakjur** [comment]
Thank you for noticing + taking the time to fix this 😄

**Comment by aknuds1** [comment]
Sorry, we're having some CI issues due to what looks like the Yarn registry.

**Comment by aknuds1** [comment]
Looks like your changes aren't properly formatted (with `prettier`): https://drone.grafana.net/grafana/grafana/973/1/12.

**Comment by torkelo** [comment]
Timestream is not an enterprise plugin, right? @ryantxu

**Comment by sakjur** [comment]
@torkelo It is listed as one https://grafana.com/grafana/plugins?enterprise=1

**Pull request merged**
