### PR TITLE
Chore: Refactor TimeRangePicker for aria-label selectors 

### PR DESCRIPTION
**Pull request by joshhunt**
Refactors TimeRangePicker to move aria-label e2e selectors to data-testid.

While I was there I also changed the close calendar button to an IconButton, which ended up being a rats nest of adjusting the design to account for it. Hopefully things should be a bit better now :) 

image

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
great work 👏  

minor nit which i'm not 100% sure about, but i'll throw it out here anyway:

| before | after |
| --- | --- |
| image | image |

i think if we want to be really consistent, we should flip the order of the buttons so primary is furthest right and right align them like our other modals. appreciate this isn't strictly using the modal component, but i think it still makes sense to have the same pattern? 🤔 

storybook example:
image

**Comment by joshhunt** [comment]
Hmmmm. I understand what you're proposing, but I'm also not quite sure how I feel about it. 

image

I think the main problem is that this 'modal' is so small that right aligning them just looks like awkward spacing rather than deliberate alignment.

**Comment by ashharrison90** [comment]
yep, maybe just swap the order and leave as space-between then? 🤔

**Comment by joshhunt** [comment]
pushed! 
image

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Pull request merged**
