### PR TITLE
Alerting: fix saving LINE contact point

### LINKED ISSUE #37425: Cannot add LINE contact point in ngalert
* **What happened**: cannot add `LINE` contact point in ngalert 
image

* **What you expected to happen**: add `LINE` contact point successfully

* **How to reproduce it (as minimally and precisely as possible)**:
   * enable `ngalert` in grafana configuration file ( `enable = ngalert` )
   * run grafana-server 
   * click alerting button of side menu --> click `contact points` tab
   * create new contact point with `LINE` type 

* **Anything else we need to know?**:  please see below..

> **Environment**:

- Grafana version: v8.0.6
- Data source type & version: None
- OS Grafana is installed on: centos 6
- User OS & Browser: chrome
- Grafana plugins: None
- Others: None

----

I think it is caused by the code below.
https://github.com/grafana/grafana/blob/22a357cc7d09f00b165a827231a7bd6ab3528b1a/pkg/services/ngalert/notifier/alertmanager.go#L478

And I changed this line like below, it works.
```suggestion
		case "LINE":
```

### PR DESCRIPTION
**Pull request by xy-man**
* **What this PR does / why we need it**
  * add new contact points (LINE and the others) successfully
* **Which issue(s) this PR fixes**
  * Fixes #37425

* **Special notes for your reviewer**
  * None

### CODE REVIEW

**Review by papagian — APPROVED** [review]
Thank you for fixing it!

**Comment by papagian** [comment]
@xy-man Can you also fix the tests [here](https://github.com/grafana/grafana/blob/880102761c26f898b7dd7dd0963d61973ad7559e/pkg/tests/api/alerting/api_notification_channel_test.go#L726) and [here](https://github.com/grafana/grafana/blob/880102761c26f898b7dd7dd0963d61973ad7559e/pkg/tests/api/alerting/api_notification_channel_test.go#L1220)? thanks!

**Comment by xy-man** [comment]
Hi @papagian 

I fixed codes you said, but I couldn't test it with environment of my laptop. 
So I just commit codes and I'll check it on PR test pipelines.

**Comment by gotjosh** [comment]
@xy-man We'd need you to sign the CLA which needs to be done through the UI, could you please address that?

**Comment by xy-man** [comment]
@gotjosh 
I did it again. 😄 
image

**Comment by papagian** [comment]
closing and re-opening so that in hope to unblock the pending checks

**Comment by xy-man** [comment]
@papagian 

https://github.com/grafana/grafana/pull/37718#issuecomment-896020999 👍 👍

**Comment by papagian** [comment]
@xy-man For unblocking the CI build you need to  sync your branch with the latest grafana `main`.

**Comment by xy-man** [comment]
@papagian 

Should I close this PR and make a new PR?
This PR seems to be invalid..

What do you think about it?

**Comment by xy-man** [comment]
@papagian 

I created new PR : https://github.com/grafana/grafana/pull/37744 // and I'll close this PR without merge. 
I am sorry for making unnecessary PR by my mistake

**Pull request closed without merging**
