### PR TITLE
NavBarMenu: Section as links and design tweak 

### LINKED ISSUE #55100: Navigation: Adjust Megamenu to work with topnav
TODO:
- [ ] Make section headers clickable (e.g. `Dashboards` goes to the `/dashboards` page)
- [ ] Make hover/active states consistent with `SectionNav`
- [x] Investigate removing storing state of expanded items

### PR DESCRIPTION
**Pull request by torkelo**
Builds on ash alt PR https://github.com/grafana/grafana/pull/55487 

* [x] Removes hover background for the section (having the hover background there that stops so far from the edge toggle button looks so strange) 
* [x] Adds text underline on hover to make it clear things are links 
* [x] Makes section links medium bold (Makes sense but not super important)
* [x] Adds some spacing around the expand button and increase angle down/up button by 2 size steps
* [x] Make the hover background on child items not as high contrast
* [x] Adds some spacing/indent around child items does not increase indent of link of child items but makes the hover highlight feel better and have some indentation
* [x] Removed the exit animation as it was causing a delay that felt unnatural, you would click a link (section or child item), you would see the page change behind the backdrop and then the animation would trigger to close the mega menu. Having close instantly feels snappier and better (change made after demo video)

(Video demo with thoughts below) 

Screenshots (hovering over toggle button)
Screenshot from 2022-09-21 06-53-17

hovering over Contact points 
Screenshot from 2022-09-21 06-53-12

Video:
[Alerting---Alerting---Grafana.webm](https://user-images.githubusercontent.com/10999/191420188-c6582192-4953-4059-b165-0f7d612ca8cb.webm)

Screenshot of smaller section icons (Not in PR but just something that I tested, looks promising):
Screenshot from 2022-09-21 06-55-10

Fixes https://github.com/grafana/grafana/issues/55100

### CODE REVIEW

**Comment by torkelo** [comment]
I removed the exit animation as it was causing a delay that felt unnatural, you would click a link (section or child item), you would see the page change behind the backdrop and then the animation would trigger to close the mega menu. Having close instantly feels snappier and better.

**Comment by lpskdl** [comment]
Hi @torkelo , I liked the improvements on the hover styles of menu items with the collapsible icon. It looks neat. In my opinion, It reduces the number of clicks needed from the user navigate on a landing page. Also it's consistent behaviour that clicking an item in the megamenu will lead to a new page(but not for the Starred).

One small thing I noticed in mobile view, if you have a bigger finger, it could be a bit challenging to click the collapsible icon to see the sub items

**Review by ashharrison90 — APPROVED** [review]
pushed a commit that aligns the button/title centrally + aligns the empty message correctly

lgtm! 🙌

**Comment by amy-super** [comment]
@torkelo I absolutely ❤️ how this turned out! 

Only one comment and it's unrelated to the hover/styling: are we ready to remove the left chevron when the megamenu is open? I'd like to just use the hamburger icon to toggle open/closed instead of having the second interaction for close only.

**Comment by torkelo** [comment]
@amy-super great! Yea I think that close toggle could be removed, we can try

**Comment by ashharrison90** [comment]
@torkelo @amy-super i would avoid removing that close button for accessibility reasons. the keyboard focus is trapped within the menu when it is open, so we need some way within the menu to close it. 😬

**Comment by torkelo** [comment]
@ashharrison90 esc key closes it

**Comment by staton-hyse11** [comment]
These changes are fantastic and very clean. To me, things just feel right. 

Regarding keyboard navigation, it would be good to allow the user to tab back to the menu icon to close it as well to avoid this tab trap.

**Pull request merged**
