### PR TITLE
Chore: Remove CircleCI

### PR DESCRIPTION
**Pull request by idafurjes**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Remember to switch this out of draft mode.

**Comment by aknuds1** [comment]
Also set the correct milestone.

**Comment by idafurjes** [comment]
will do all of that, was just trying to figure out how to remove the circle ci build error check that failed

**Comment by aknuds1** [comment]
@idafurjes you can ignore the Circle build error, but to fix it go to the CircleCI UI and disable the project.

**Pull request merged**
