### PR TITLE
Added MaximumUsedTransactionIDs metric to list of AWS RDS metrics.

### PR DESCRIPTION
**Pull request by activeshadow**
I've made a super simple addition to the AWS CloudWatch TSDB code to support getting the `MaximumUsedTransactionIDs` metric for an AWS RDS instance (useful per [this](https://aws.amazon.com/blogs/database/implement-an-early-warning-system-for-transaction-id-wraparound-in-amazon-rds-for-postgresql/) link), but I cannot for the life of me figure out how to correctly build a new Docker image so I can test it.

Any advice on building a Docker image to test with prior to merging would be greatly appreciated.

### CODE REVIEW

**Comment by bergquist** [comment]
```bash
make build-docker-full
```
Should build the current code and tag it with `dev`

**Comment by marefr** [comment]
This should be fine to merge based on the small change and looking at [this](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MonitoringOverview.html#monitoring-cloudwatch) and comparing with existing metrics it looks like it should just work.

**Comment by torkelo** [comment]
this need a rebase with master and merge conflict resolution

**Comment by activeshadow** [comment]
@torkelo done!

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
