### PR TITLE
[v7.5.x] Plugins: Add validation for plugin manifest

### PR DESCRIPTION
**Pull request by wbrowne**
Backport 6d066a7aa89615315002875125900ff168fd2420 from #52787

### CODE REVIEW

**Review by tolzhabayev — APPROVED** [review]

**Comment by tolzhabayev** [comment]
@wbrowne can be closed.

**Comment by wbrowne** [comment]
⚰️

**Comment by tolzhabayev** [comment]
Boat missed @wbrowne close it

**Comment by wbrowne** [comment]
:rip: sweet prince. Maybe another day

**Pull request closed without merging**
