### PR TITLE
Plugins: Set backend metadata property if executable is set

### LINKED ISSUE #42648: Recorded queries doesn't work for some of the builtin data sources
**What happened**:
Wanted to create a recorded query using the postgres datasource, but I can't.

**What you expected to happen**:
To be able to create a recorded query using the postgres datasource.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Doesn't look like `backend: true` in the `plugin.json` for postgres datasource. Not sure the backend property is something we require to be set. Should be enough if executable is defined or if it's a backend for a core datasource. Need to look into whether usage of this `backend` property has never been used until now (recorder queries).

**Environment**:
- Grafana version: v8.3.0/main branch

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Always set `backend: true` for core backend datasources and always set `backend: true`if `executable` is not empty.

**Which issue(s) this PR fixes**:
Fixes #42648

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ryantxu** [comment]
what about just removing/ignoring "Backend" flag entirely?  is it entirely equivalent to `Executable != ""`?

(there is likely something I am not thinking about)

**Comment by marefr** [comment]
@ryantxu `backend` flag is currently being used by recorded queries to decide whether a data source supports recorded queries. What to use instead if we remove this? The `alerting` flag already used by alerting to check if data source supports alerting?

**Comment by ryantxu** [comment]
:thinking: are all of these really just flags if grafana core can send `QueryData` requrest (grpc or builtin)?

For now, we can set the flag, but it seems better to remove "backend" AND "alerting" flags and just check if we can call query data or not

**Comment by wbrowne** [comment]
I'd like to see if we can remove use of the `backend` flag and use something more tailored for the recorded queries feature. I experimented a bit with removing the flag and I think we should be good as long as we can change Core plugins back to being un-managed.

**Comment by marefr** [comment]
Opened alternative/short term solution in #43349

**Comment by marefr** [comment]
@ryantxu for alerting to function properly a data source might need to interpolate certain variables in the backend such as intervals, I think that's the reason why we have this property to explicitly specify if it's supported or not and in addition with the old alerting system time series data was a requirement and with the new I don't think that's true any longer.

Agree that it would simplify removing these flags. This @wbrowne has a good use case for keeping the backend flag in the backend, but maybe we can skip exposing it in the frontend?

**Comment by marefr** [comment]
Going to close this based on we have a fix (#43349) merged. Might come back to this one in the future.

**Pull request closed without merging**
