### PR TITLE
Included OFFSET and SOFFSET for influxdb

### LINKED ISSUE #6401: [Feature Request] Add Offset to Influxdb Query Editor
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  Influxdb
- What OS are you running grafana on?
  offical docker image

When calculating derivatives and non-negative-derivatives on counts with influxdb the first data point will periodically be way off because it thinks the first data point is a zero and is then jumping to the count. To combat this, it is useful to use OFFSET to drop the first data point. I'd think it would go best on it's own row after GROUP BY in the query editor as it is appended on the end of queries and is independent of GROUP BYs. It might make sense to also include support for SOFFSET, LIMIT, and SLIMIT at the same time. I could see LIMIT being quite useful when working with tables.

### PR DESCRIPTION
**Pull request by unixninja92**
Fixes #6401

### CODE REVIEW

**Comment by daniellee** [comment]
Thanks for the PR!

Reading the documentation on [SOFFSET](https://docs.influxdata.com/influxdb/v1.2//query_language/data_exploration/#the-soffset-clause):

> Using the SOFFSET clause without an SLIMIT clause can cause inconsistent query results. There is an ongoing issue that requires queries with SLIMIT to include GROUP BY *. N

Same thing for OFFSET. Is this something that should be guarded against here?

This PR also needs some minor UX changes before it can be merged.

**Comment by torkelo** [comment]
man InfluxDB query language is a true mess. supporting all these keywords and options in a consitent way is going to make the query editor pages long by the year end. Maybe there is better way to add these options as query parts that the user can add on demand rather than as always visible input fields

**Comment by unixninja92** [comment]
We could add limits and offsets to a + menu similar to Group By or Select. 

And I've been running OFFSET without a LIMIT without seeing any issue for a while. From my brief testing SOFFSET does not seem to work without SLIMIT though.

**Comment by torkelo** [comment]
closing this due to lack of interest in the feature request (https://github.com/grafana/grafana/issues/6401), can open again if the interest gets bigger.

**Comment by yellowpattern** [comment]
This should be re-opened. 1 day between a comment from "unixnijna92" before "torkelo" decides there's a lack of interest? Seriously dude.

Discussion on the influxdb side:
https://github.com/influxdata/influxdb/issues/6451#issuecomment-255583038

**Pull request closed without merging**
