### PR TITLE
draft Work-in-progress datasource/elasticsearch 7.0

### LINKED ISSUE #15622: Elasticsearch 7.x support
### What Grafana version are you using?
6.0.0 beta 3
### What datasource are you using?
Elasticsearch 7.0.0 beta 1
### What OS are you running grafana on?
Ubuntu
### What did you do?
After upgrading a Elasticsearch cluster from 6.6 to 7.0 beta 1, I can no longer add new indices as seperate datasources to grafana, due to the following error:
image

However, current data sources that were created when the cluster was 6.6.0 now no longer work, all charts display the following error:
image

Some useful F12 sceenshots to help:
1. Response when using old data sources after upgrading to Elasticsearch 7.0:
image

2. Response when trying to create new data sources that are 7.0:
the _mapping Json is the following:
```
{"logging-2019.02.24":{"mappings":{"properties":{"@timestamp":{"type":"date"},"@version":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-City":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Country-Code":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Env":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"HostName":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Log-Event":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},,"host":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"port":{"type":"long"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}
```
Which clearly shows the @timestamp field as being of type 'date', even though grafana complains that @timestamp field does not exist

### PR DESCRIPTION
**Pull request by alcidesv**
Adds support for Elasticsearch 7.0 data sources

**This is work in progress**

Fixes #15622

It seems to be working. 
Summary of changes:

- Added "70" as an acceptable value for `esVersion` here and there
- Remove "type" level from "_mapping" in responses from ES for `esVersion >= 70`

We will put this beauty in our development environment with our Elasticsearch 7 and see what doesn't work yet. 
And of course, I have no idea of what I'm doing.

### CODE REVIEW

**Comment by alcidesv** [comment]
OBS: For the time this is WIP, I will keep the latest stable version as base branch...

**Comment by holiiveira** [comment]
About #16602 

The problem is that the return of the Search API has changed.

In versions prior to 7.0.0:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/_the_search_api.html

The `Total` attribute was:
```
...
hits" : {
    "total" : 1000,
...
```

Now it is:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-search-API.html

```
...
"hits" : {
    "total" : {
        "value": 1000,
        "relation": "eq"
    },
...
```

I believe that the file you take care of would be the [models.go (L45)](https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/models.go#L45)

That's what I was able to track.

**Comment by alcidesv** [comment]
@holiiveira hmm, if I comment line 45, the Go code still compiles. I tried running the backend tests but I didn't manage, they fail --either way-- with some errors that are above my Go competence.

Beyond that, I have been playing with the code of this PR for a day with no issues.

**Comment by marefr** [comment]
@alcidesv This looks like a good start. However I noticed that you was targeting this pr to be merged to branch cp-6.1.3. Merged with master but then noticed that you've based your work on the branch cp-6.1.3 which is wrong - you should always base your work on master and target a pr to be merged to master. 

You have a few alternatives here, but the easiest is probably to start on a fresh branch based on master and cherry pick your ES7 commits from this branch, close this PR and open a new PR. I want you to do this since otherwise those commits will look like I've authored them.

**Review by marefr — CHANGES_REQUESTED** [review]
Need to rebase commits on master or close and open a new PR where your commits are based on master branch.

**Comment by alcidesv** [comment]
Obsoleted by #16646

**Pull request closed without merging**
