### PR TITLE
Query: make queryType a top level property

### PR DESCRIPTION
**Pull request by ryantxu**
The [DataQuery](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/datasource.ts#L373) interface is the root interface expected from all datasources.  This should include properties where we can advertise a consistent use in many data sources.

A few datasources already use `queryType` including:
* stackdriver
* azure monitor
* ADX
* newrelic

If we specify a consistent string for type -- the backend can use the value to serialize the rest of the object.  This is not inheritance best practices, but it is better than nothing ;)

This PR:  https://github.com/grafana/grafana-plugin-sdk-go/pull/76  tried the same idea using `path` property.

Grafana 7.0 seems like a good time to make this potentially breaking change -- it would only affect people that have `queryType` mapped to an object

### CODE REVIEW

**Comment by torkelo** [comment]
what would example queryType's be?

**Comment by ryantxu** [comment]
For stackdriver it is: 
`metrics` |  `slo`

For azure monitor it is: 
`Azure Monitor` |  `Azure Log Analytics`

for newrelic it is: 
`newRelic` | `insights`

etc

**Review by marefr — APPROVED** [review]
> This is not inheritance best practices, but it is better than nothing ;)

I agree :) This makes sense. Great

LGTM

**Review by kylebrandt — APPROVED** [review]
This should allow backend plugin developers to use this property to the DataQuery.JSON property on the backend "is a" whatever query. Then it can be unmarshalled to a well typed struct in the plugin, which makes additional development in the plugin cleaner. 

Hopefully we can use this to make some helper in the SDK

**Comment by ryantxu** [comment]
This will help if you have a single object that should be interpreted many ways depending on the `queryType`

However, most existing data sources use the pattern of adding a new [property for each type](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/stackdriver/types.ts#L80):
```
export interface StackdriverQuery extends DataQuery {
  queryType: QueryType;
  metricQuery: MetricQuery;
  sloQuery?: SLOQuery;
}
```

On the backend, this would enable the alternate (but I am not sure better) behavior:
```
export interface StackdriverQuery extends DataQuery {
  queryType: QueryType;
  details: MetricQuery | SLOQuery;
}
```

regardless, given that `queryType` is used pretty often already it is something we can/should add the parts of the structure we expect to control.

**Pull request merged**
