### PR TITLE
MS SQL: Integrated security

### LINKED ISSUE #11876: [Feat] MSSQL Integrated Security
### What Grafana version are you using?
v5.1.1
### What datasource are you using?
MSSQL
### What OS are you running grafana on?
Windows 2012R2
### Feature request
Being able to setup a data source using Integrated Security including Encrytion.
For example an jdbc url: jdbc:sqlserver://myhost.acme.com:1433;databaseName=myDB;integratedSecurity=true;encrypt=true
### What was the expected result?
Connectivity to the MSSQL database server using the credentials of the Grafana service.

### PR DESCRIPTION
**Pull request by daniellee**
Fixes #11876

## The Xorm workaround

This feature works if the [login/user id is empty](https://github.com/denisenkom/go-mssqldb#common-parameters). It will then fallback to Windows authentication (providing the user is on Windows and Sql Server has Windows Auth enabled and the user has been given access). 

~~I couldn't figure out how to set the user id to empty (same problem has always existed with the password field). Xorm will ignore empty fields when [updating the database table](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/datasource.go#L257).~~

~~My workaround/hack is to set the user id to `' '` (one space). Is there a better way to do this? Should I instead send a reset flag in the update command or explicitly overwrite the User field with the empty value in datasource.go?~~

## How to test

This feature adds support for Windows authentication and therefore can only really be tested on Windows. 

On Linux, the user will see the error message:

`Login error: mssql: Login failed for user ''.`

Steps for testing:
1. Install Sql Server (Developer Edition and Managment Studio). There are a [couple of settings that will need to set](https://stackoverflow.com/questions/12774827/cant-connect-to-localhost-on-sql-server-express-2012-2016). 
2. Create a database for unit tests ([create a database and user](https://github.com/grafana/grafana/blob/master/pkg/tsdb/mssql/mssql_test.go#L22))
3. Set the mixed mode authentication for your Sql Server instance to be able to run the unit tests and remove the [Skip from this line](https://github.com/grafana/grafana/blob/master/pkg/tsdb/mssql/mssql_test.go#L32) 
4. Run [devenv setup](https://github.com/grafana/grafana/blob/master/devenv/setup.sh) to get the provisioned data source and dashboards for MSSQL. You will need to restart Grafana on Windows afterwards for Grafana to detect them. 
5. To run the unit tests with Windows authentication then change the [connection string](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/sqlutil/sqlutil.go#L65) to: `server=%s;port=%s;database=grafanatest`
6. `go test ./pkg/tsdb/mssql/...`

### CODE REVIEW

**Comment by aknuds1** [comment]
Having a look.

**Review by aknuds1 — APPROVED** [review]
Backend changes look fine to me, though AFAICT only tests changed between revisions b91950f658ec and 1e08a3fab204 in go-mssqldb? Am I missing something?

**Comment by daniellee** [comment]
@aknuds1 you seem to be right. Maybe only the frontend changes are needed. The SSPI support was added years ago and then [NTLMv2 support](https://github.com/denisenkom/go-mssqldb/pull/551) was added just before b91950f658ec.

**Review by aknuds1 — APPROVED** [review]

**Comment by daniellee** [comment]
Used the [MustCols](https://godoc.org/github.com/go-xorm/xorm#Engine.MustCols) to always update the user field and that sets the field to empty when Windows auth is chosen. Think that should be fine for other data sources too - I tested Prometheus and a few others.

**Pull request merged**
