### PR TITLE
i18n: Markup QueryEditorRow Component for translations

### LINKED ISSUE #77686: i18n: Markup `QueryEditorRow` for translations
Provide translation keys for QueryEditorRow component.

Follow instructions https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-translation-phrase

### PR DESCRIPTION
**Pull request by aditipatelpro**
**What is this feature?**

This PR adds support for i18n in one of the `Explore` components. This PR targets the `QueryOperationHeader` component.

**Why do we need this feature?**

To add support for i18n in the `QueryOperationHeader` component.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #77686

**Special notes for your reviewer:**
I have added i18n support for the `QueryOperationHeader` components in the `Explore` Component.

@ifrost can you please provide your feedback on the PR?

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gabor** [comment]
hi @aditipatelpro , thank you for the pull request! i think there may have been a misunderstanding. the referenced github issue https://github.com/grafana/grafana/issues/73984 deals with `explore` components, but one of the files changed in this PR is : `public/app/plugins/datasource/postgres/CheatSheet.tsx`. that file is not part of `explore`, it is part of the postgres data source plugin. please do not change that one
(we are planning some larger changes there and adding internalization to that file would complicate things a lot).
thanks 👍 .

**Comment by aditipatelpro** [comment]
Hi @polibb, @Clarity-89, @eledobleefe, @ifrost is this good to go?

**Comment by aditipatelpro** [comment]
Hi, @gelicia, @ifrost , @axelavargas , @polibb, @Clarity-89 , @eledobleefe can you please provide your feedback on this PR?

**Comment by ifrost** [comment]
> Hi, @gelicia, @ifrost , @axelavargas , @polibb, @Clarity-89 , @eledobleefe can you please provide your feedback on this PR?

Looking good! I think you can also wrap line _Data source plugin does not export any Query Editor component_ and it should be good to go!

https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryEditorRow.tsx#L304

**Comment by aditipatelpro** [comment]
> 
> Looking good! I think you can also wrap line _Data source plugin does not export any Query Editor component_ and it should be good to go!
> 
> https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryEditorRow.tsx#L304

@ifrost, I have included _Data source plugin does not export any Query Editor component_ line. Can you please have a look at the prefixes used for it? I tried to come up with these with my best guess as I don't have a thorough context of the app.

**Comment by ifrost** [comment]
@grafana/dashboards-squad I think after updating [this](https://github.com/grafana/grafana/pull/76312#discussion_r1387708059) it should be good to merge. What do you think?

**Comment by ifrost** [comment]
@grafana/grafana-frontend-platform (`/public/app/core/` codeowners), @grafana/dashboards-squad (`/public/app/features/query/` codeowners). After [fixing this](https://github.com/grafana/grafana/pull/76312#discussion_r1387708059) I think it should be good to merge. What do you think?

**Review by joshhunt — APPROVED** [review]

**Review by axelavargas — APPROVED** [review]
Looks good to me 🥇, thanks for contributing @aditipatelpro 🙌🏾

**Comment by aditipatelpro** [comment]
> @grafana/grafana-frontend-platform (`/public/app/core/` codeowners), @grafana/dashboards-squad (`/public/app/features/query/` codeowners). After [fixing this](https://github.com/grafana/grafana/pull/76312#discussion_r1387708059) I think it should be good to merge. What do you think?

@ifrost, I have fixed it. Thanks for the feedback.

**Review by ifrost — APPROVED** [review]
Brilliant stuff! Thanks a lot for that contribution ❤️

**Pull request merged**
