### PR TITLE
[WIP] Plugins: Introduce Plugins specific config

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
Incorporates the `setting.ConfigProvider` when building plugin configuration

### CODE REVIEW

**Comment by wbrowne** [comment]
@mmandrus Do you want to take this for a spin?

**Comment by mmandrus** [comment]
> @mmandrus Do you want to take this for a spin?

will have a look!

**Review by marefr — APPROVED** [review]
LGTM, just need to fix the failing test :+1:

**Review by mmandrus — APPROVED** [review]
LGTM

**Pull request merged**
