### PR TITLE
Canvas: Add vertex control to connections

### LINKED ISSUE #83267: Canvas: Ability to break up arrows via mid point control
Add midpoint control for arrows to allow custom routing.

### PR DESCRIPTION
**Pull request by drew08t**
Add vertex control of connections in canvas.

- [x] Add vertices array to save model
- [x] Mouse events for vertex creation
- [x] Mouse events for vertex edit
- [x] ~Hover~ Click on line or path to show midpoint controls
- [x] Auto generation of midpoint controls
- [x] basic constraints: max number of vertices, ~close to orthogonal snapping~ https://github.com/grafana/grafana/issues/83269
- [x] Handle zoom
- [x] Clean up code

Mar-12-2024 15-09-41
Mar-12-2024 15-11-29

Mar-07-2024 17-55-55

Closes #83267

### CODE REVIEW

**Comment by baldm0mma** [comment]
Screenshot 2024-03-14 at 12 17 19 PM

**Comment by drew08t** [comment]
> Screenshot 2024-03-14 at 12 17 19 PM

I was not expecting that. LOL

**Review by baldm0mma — APPROVED** [review]
Vertex control works for me as I would expect!

**Review by Develer — APPROVED** [review]

**Comment by drew08t** [comment]
Capturing one issue found during testing, not related to vertices, but connections in general when they don't have a target: https://github.com/grafana/grafana/issues/84604

**Pull request merged**
