### PR TITLE
Chore: Update target in go.mod to 1.20 and golangci-lint to v1.52.2

### PR DESCRIPTION
**Pull request by sakjur**
**What is this feature?**

Use a newer version of golangci-lint and target Go 1.20 in the go.mod-file (which prompts warnings about `rand.Seed` being deprecated leading to the updates to mssql_test, mysql_test, and postgres_test).

**Why do we need this feature?**

Keeping up-to-date makes it easier to avoid big bang changes when we finally need to update.

**Who is this feature for?**

Grafana devs.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by papagian — APPROVED** [review]
LGTM and works for me locally

**Comment by armandgrillet** [comment]
I think some workflows need to be updated as well, like in https://github.com/grafana/grafana/commit/da9c646f242fd16ba8a789fa5d1c50094d761ae7#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by sakjur** [comment]
@armandgrillet Thank you for highlighting that, I had forgotten we added that 🙂

**Review by zoltanbedi — APPROVED** [review]
sql changes lgtm

**Pull request merged**
