### PR TITLE
Chore: Upgrade xorm

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Smallest possible upgrade to new xorm module path.

**Note**: According to @marefr we need to be very careful before we upgrade xorm, because it tends to have breaking changes. Let's evaluate if we wish to do this.

### CODE REVIEW

**Comment by bergquist** [comment]
Upgrading xorm makes us all nervous :) But once we branched of the 6.7 release branch I think we can test this extensively and merge it to master.

**Comment by torkelo** [comment]
And try to add some performance counters for SQL queries / commands, would be so good. But where no hooks that could be used in xorm so not sure how.

**Comment by bergquist** [comment]
> And try to add some metric counters & timers for SQL queries / commands, would be so good. But where no hooks that could be used in xorm so not sure how.

Whenever I think about this subject I get frustrated. Let's pick up this topic next week. I'd like to figure something out.

**Comment by marefr** [comment]
Suggest handling instrumentation of sqlstore separately. Would be nice to be able to use this https://github.com/opencensus-integrations/ocsql, but not sure it's possible to get it to work with XORM?

**Review by marefr — CHANGES_REQUESTED** [review]
Verified that gdev dashboards for mysql, postgres and mssql works as expected.

Have went through all commits in xorm.io/builder, xorm.io/core and xorm.io/xorm. 

Nothing substantial found in xorm.io/builder and xorm.io/core.

xorm.io/xorm:
v0.7.1 => v0.7.2: https://gitea.com/xorm/xorm/commits/tag/v0.7.2
~40 commits
Adding support for context is nice https://gitea.com/xorm/xorm/commit/5750e3f90a96167c5f72053755d0f9e550350d97
MSSQL connectionstring https://gitea.com/xorm/xorm/commit/ff094ebc3e23006154a68cb17cf71bfe9fed1cec think this would allow usage of a PR we had to revert https://github.com/grafana/grafana/issues/17665#issuecomment-532679148 

v0.8.0
Seems this was the proper tag for moving to xorm.io
Depends on 
xorm.io/builder v0.3.6
xorm.io/core v0.7.2

v0.8.1
Support local sql log https://gitea.com/xorm/xorm/commit/1735906dcc9597a73446b463d9194a5bc48953ec 
Enable log per session if I understand the Changes

v0.8.2
Potential breaking change? https://gitea.com/xorm/xorm/pulls/1505

Would suggest to upgrade to xorm.io/xorm v0.8.1 for now. v.0.8.2 looks a bit scary for those using custom Postgres schema which we already have had issues with after upgrading xorm #17357.

**Comment by marefr** [comment]
@aknuds1 just noticed #22376 upgrades to v0.8.1 so suggest we try to get that into a merge:able state so that we can merge it after 6.7 stable.

**Comment by aknuds1** [comment]
Sounds good to me @marefr!

**Comment by aknuds1** [comment]
Closing in favour of #22376.

**Pull request closed without merging**
