### PR TITLE
Change templateCaptureValue to support using template functions

### LINKED ISSUE #37393: Using {{ $value }} doesnt return value
Using {{ $value }} on alert description returns:

lvl=eror msg="error in expanding template" logger=ngalert name=description value="Value is expected:  {{ $value }}" err="error parsing template __alert_Under_Replicated_Partitions: template: __alert_Under_Replicated_Partitions:1: u**ndefined variable \"$value\""**

While I was expecting to return the value 

To reproduce just add {{ $value }} on description of ngalert 

image

Environment:
- Grafana version: 8.0.6
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What this PR does / why we need it**:

This commit changes templateCaptureValue to use `float64` for the value instead of `*float64`. This change means that annotations and labels can use the `float64` value with functions such as printf and avoid having to check for `nil`. It also means that absent values are now printed as `0`.

**Which issue(s) this PR fixes**:

Fixes #37393

### CODE REVIEW

**Comment by davidmparrott** [comment]
My concern with this change is that a missing value does not mean 0 and this eliminates that distinction.

**Comment by kylebrandt** [comment]
> My concern with this change is that a missing value does not mean 0 and this eliminates that distinction.

Could return `NaN` when 0. Still muddles up a distinction, but probably less important than a distinct 0 value.

**Review by gotjosh — COMMENTED** [review]
Overall, this LGTM. I like Kyle's idea of applying `math.NaN()` to nil values.

**Review by gotjosh — APPROVED** [review]
LGTM

**Comment by nidhinkumar06** [comment]
@gerobinson Does this fix available in V8.1.3

**Comment by torkelo** [comment]
@gerobinson moving this to 8.2 milestone

**Pull request merged**
