### PR TITLE
Chore: Removes gf-form from admin/user_

### PR DESCRIPTION
**Pull request by khushijain21**
Part of #65513

image

### CODE REVIEW

**Comment by khushijain21** [comment]
@Clarity-89 I did not extra div here and instead used the CSS class as the an extra div would not have given 40px margin anyway, lmk

**Comment by Clarity-89** [comment]
> @Clarity-89 I did not add extra div here and instead used the CSS class as the an extra div would not have given 40px margin anyway, lmk

This one is a bit tricky and the way I'd do it is to remove the gf-form classes from each component of `UserAdminPage` and then wrapp the `Page.Contents` children into Stack inside that page to keep the spacing consistent instead of adding margin to individual sections.

**Comment by Clarity-89** [comment]
> I have one more query, this would still not work right because these last three child components have more margin between them than the first two
> 
> image
> 
> here, it is 40px+16px, whereas for the profile and preference it is only 16px

I think it'd work if you remove `gf-form` classes from all those components.

**Comment by khushijain21** [comment]
done!

**Comment by Clarity-89** [comment]
Could you update your branch to the latest main as there seem to be some conflicts?

**Review by Clarity-89 — APPROVED** [review]

**Pull request merged**
