### PR TITLE
[authn]: add GetIDClaims() to Requester

### PR DESCRIPTION
**Pull request by drclau**
**What is this feature?**

* add `GetIDClaims()` to `Requester`

**Why do we need this feature?**

n/a

**Who is this feature for?**

n/a

**Which issue(s) does this PR fix?**:

Fixes #n/a

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ryantxu** [comment]
Generally I like the idea -- but this means everything needs to depend on authlib + go-jose + gRPC

That is why I proposed the zero dependency module in authlib

**Comment by drclau** [comment]
> Generally I like the idea -- but this means everything needs to depend on authlib + go-jose + gRPC
> 
> That is why I proposed the zero dependency module in authlib

@ryantxu, we are in agreement, and we're not dismissing this, but we want to get things functional before making the other changes. wdyt?

**Review by ryantxu — APPROVED** [review]
Good quick fix -- but let's see if we can reduce the dependencies in the future

**Review by gamab — APPROVED** [review]

**Pull request merged**
