### PR TITLE
Let apps include pages as tabs

### PR DESCRIPTION
**Pull request by ryantxu**
Application plugins can add pages, and the navigation is currently in the left sidebar. It would be great to include the pages in the plugin tabs.

This patch lets a configuration like:

```
{
"type": "page", "name": "Fields", "component": "FieldsPageCtrl",
"addToNav": true, "showAsTab": true, "icon": "fa fa-fw fa-tachometer"
},
{
"type": "page", "name": "Faults", "component": "FaultsPageCtrl",
"addToNav": true, "showAsTab": true, "icon": "fa fa-fw fa-bullhorn"
},
{
"type": "page", "name": "Electrical", "component": "ElectricalPageCtrl",
"addToNav": true, "showAsTab": true, "icon": "fa fa-fw fa-sitemap"
},
```

Create the structure:
image

I don't see any infrastructure to test existing app plugins, or add an example configuration... so I'm not sure what to do there. The `example-app` configs don't even register the pages correctly :cry: -- I posted a PR for that in 2016 https://github.com/grafana/example-app/pull/4

### CODE REVIEW

**Comment by torkelo** [comment]
not sure about this, as clicking on the tab will not open the tab but another page. So it will look like a tab but not function as a tab. 

Maybe there is another way we can link to these pages?

**Comment by ryantxu** [comment]
In this patch, the linked pages have the same tab structure.  The tabs both look and act like tabs.  Yes, the linked URL is on a different page, but this behavior is identical other places in grafana like: /org/*, /profile/* etc

**Comment by torkelo** [comment]
I understand. Tricky. I can see that this is a clear improvement in navigation & discoverability of these pages but not sure I like the option (the dual nature of it) where page is either stand alone or as tab. Would prefer if we only had one way to define pages. And also a bit buggy (in some cases) that these tabs show up even when the app is not enabled. 

But having all addToNav pages show up as as tabs will be problematic if the app has lots of pages so an option might be tricky to avoid. 

thoughts @mattttt ?

**Comment by ryantxu** [comment]
I updated things so it only shows the tabs for enabled apps.  I toyed with a variety of configuration options, but this seems like a good tradeoff with simple to configure and totally backwards compatible.

Another option that would be nice is for the plugin page to be able to set the `navModel` from code.  Given the existing page lifecycle, i think this would be a difficult change.

**Comment by ryantxu** [comment]
In addition to tabs, we could/should also make the sidebar include pages links to the page (when the app is enabled).  I just added this change to the pull request also:

image

**Comment by ryantxu** [comment]
Closing this, and hoping to solve it as part of #16433

**Comment by ryantxu** [comment]
reopening for an old fork... will close after CI

**Pull request closed without merging**
