### PR TITLE
Bugfix/fix 1032: Allow custom mapping of template variable value -> display text

### LINKED ISSUE #1032: Allow custom mapping of template variable value -> display text
Use Case: You may store metrics based on an 'ID' property but wish to have the template variable selection UI use a more human friendly label. e.g. You track metrics by domain with an internal domain ID but wish to use the domain's URL in the template variable selector UI. 

@torkelo I can take a cut at implementing this, what are your thoughts on implementation? For my specific use case I would want to be able to provide an arbitrary JS function to perform the value -> text conversion as I need to hit an external service for the lookup. I was thinking an initial implementation could be adding a config value in the dashboard JSON that defines the mapping function. UI support could be added later to handle more trivial mappings with pre built mapping functions (e.g. regex substitutions). 

Also connected to this would be the ability to edit the full dashboard JSON via the UI, although export -> edit -> import would function as a workaround if this proves to be difficult.

### PR DESCRIPTION
**Pull request by marcoklaassen**
Fixes #1032
use a json array to define variable lists with mapping of value and display text.
if you don't need a mapping, you can use the feature as before (comma separated list).
there is also an additional info-box containing a description how to build the json array.

### CODE REVIEW

**Comment by marcusolsson** [comment]
Please provide a relevant title and description of the change in this pull request.

**Comment by siegmund42** [comment]
One comment for discussion (I like your pragmatic way):
Do we want to include this in that implicit way or add an extra variable type for being more explicit?

I really like to see some progress on this!

**Comment by marcoklaassen** [comment]
> One comment for discussion (I like your pragmatic way):
> Do we want to include this in that implicit way or add an extra variable type for being more explicit?
> 
> I really like to see some progress on this!
> 
> [EDIT] Bonus question: Is it then possible to refer to both `$my_var.text` and `$my_var.value`?

Thanks for your comment.
I think we should start with an implicit way like this. 
If our users like this feature and use ist more and more, we can introduce a new variable type later.

Bonus answer: no, `$my_var.text` is just used for any labels; `$my_var.value` is the value for the queries.

**Comment by maxilampert** [comment]
@torkelo @marcusolsson Any idea if that is something that can be merged as a starting point such feature would be really helpful to give more flexibility to the custom values without having to build a dummy datasource?

**Comment by siegmund42** [comment]
I would like to ping this for review - it's a pretty nice feature that was already demanded in several requests. The approach of @marcoklaassen is pragmatic and a good point to start from.

**Comment by mareksimunek** [comment]
I really want this feature as many others. Could you please  @marcusolsson check again? Or where it got stucked?

**Comment by torkelo** [comment]
Thanks for contributing! 

I do not think this addresses #1032, this adds value & text support to the custom variable, https://github.com/grafana/grafana/issues/1032 is about dynamic query based id -> text lookup for query variable options. 

We can't realy merge this, we are rewriting the template variable system to redux & react. https://github.com/grafana/grafana/pull/22434 

Dont think json text in the input is the right answer here. Either a UI or support for CSV table (with text & vale columns) would be better.

**Pull request closed without merging**
