### PR TITLE
Don't animate panels on initial render

### LINKED ISSUE #10127: Grafana v5.0 - Dont animate panels on initial render
now that the grid uses css transitions it has this effect of moving all panels on initial render when you switch dashboards. Do not find this very good. 

Find a way to disable the initial animations. Think it can be done by adding a class that is removed after mount. 

https://github.com/STRML/react-grid-layout/issues/103

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR closes #10127 by using trick described in https://github.com/STRML/react-grid-layout/issues/103#issuecomment-202127519

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
Sorry, forgot to make `--amend`. Please, squash these 2 commits into one.

**Comment by torkelo** [comment]
this seems to have broken the size me stuff or something, because now it wont resize dashboard after changing browser size (or toggling the sidemenu off)

**Comment by torkelo** [comment]
think I have a fix for it, 1sec

**Comment by torkelo** [comment]
had to revert this as it stopped the sizeMe stuff rom working (as that code was moved to constructor), think maybe just moving to render would have worked though.

**Comment by alexanderzobnin** [comment]
Is it due to changing `GridWrapper` from function to class style?

**Comment by torkelo** [comment]
yes, and you moved the size stuff into a constructor. If you make a component out of a function (like it is now) it is called a pure function component, which basically acts like a component with a render function.

**Pull request merged**
