### PR TITLE
Chore: Replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
**What this PR does / why we need it**:

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring)  which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gillesdemey — COMMENTED** [review]
LGTM as far as the files under `public/app/features/alerting` are concerned.

**Comment by aocenas** [comment]
@grafana/plugins-platform-frontend does anybody know why the breaking changes step is failing here?

**Comment by joshhunt** [comment]
@aocenas If we've removed all .substr() usage and we feel strongly about ensuring it doesnt come back, we can just add a regular eslint rule. Personally, I wouldn't bother, but i haven't thought about it too much. Betterer can remain for changes that we want to make gradually - looks like we've done a good job of tackling them all here.

I am surprised that the function isn't marked as `@deprecated` in Typescript's type defs tbh.

**Comment by joshhunt** [comment]
Levitate warning looks like a false positive (perhaps due to not being rebased recently?)

**Comment by CommanderRoot** [comment]
I would not mind adding an ESLint rule like I did here https://github.com/vercel/next.js/commit/b21e3c258e24becc3c33397c023c0c9d9af59f75 if that's something that's wanted.

**Review by mckn — APPROVED** [review]
LGTM! FYI: I have not tested all affected scenarios.

**Comment by aocenas** [comment]
@CommanderRoot thanks for the contribution

**Pull request merged**
