### PR TITLE
Update version of docker-compose.yaml

### PR DESCRIPTION
**Pull request by lnnt**
**What is this feature?**

It's not a feature.

**Why do we need this feature?**

When I run the latest stable version of Grafana using Docker Compose, `docker compose` gives the error `'version' is obsolete`.

**Who is this feature for?**

The user who want to run Grafana via Docker Compose.

**Which issue(s) does this PR fix?**:

N/A

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by usmangt** [comment]
looking into it now

**Comment by usmangt** [comment]
@lnnt 

I think this will happen again once there is another new version in the future.

Please test out by copying the yaml except for the version line and see if you still get the error message.

That way we can make some minor changes in this PR

Thanks again for submitting it and informing us.

**Review by usmangt — CHANGES_REQUESTED** [review]
Please see comment

**Comment by lnnt** [comment]
> @lnnt
> 
> I think this will happen again once there is another new version in the future.
> 
> Please test out by copying the yaml except for the version line and see if you still get the error message.
> 
> That way we can make some minor changes in this PR
> 
> Thanks again for submitting it and informing us.

Good idea. I didn't get the error message.

**Review by usmangt — APPROVED** [review]
Thanks for testing.

@chri2547  LGTM !! you can do one final check please.

**Review by chri2547 — APPROVED** [review]
Thank you for working on this!

**Pull request merged**
