### PR TITLE
Discord integration

### LINKED ISSUE #7964: [Feature request] Discord.gg integration
Discord.gg is slack-like platform for gamers. It seems to be popular also with dev teams, because of free voice chat, unlimited messages and unlimited number of uploaded files.

PR that implements integration: https://github.com/grafana/grafana/pull/7926

### PR DESCRIPTION
**Pull request by andrzejressel**
This pull request implements integration with Discord platform (https://discord.gg)

Discord has [slack webhook integration](https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook), but I found it very unreliable (on our production server I got "Context timeout" and on newest master "500 Bad Request"), so I decided to implement native solution.

Fixes #7964

### CODE REVIEW

**Comment by daniellee** [comment]
@jereksel can you open a feature request issue and link to this PR, please. We have a lot of integrations for alerting in Grafana core now and are a little hesitant to merge more unless we know they are going to be used. If the feature request gets lots of :+1: then we will merge this.

**Comment by torkelo** [comment]
closing this PR for now until we see more interest. 

We also have plans to implement backend plugins so features like this can be added without being merged to core code base

**Comment by jleclanche** [comment]
I'm interested FWIW, I've been using the Slack webhook integration in the mean time.

**Comment by ShadowKitten** [comment]
Interested in this!

**Comment by LucaDev** [comment]
I'd love a propper Discord integration!

**Comment by Scrayos** [comment]
I'm also very interested in this  getting merged!

**Comment by zpremio** [comment]
Wow! A very good PR! Really would like to see a discord integration in grafana!

**Comment by radekkut** [comment]
Would love this to be merged, 👍 from me

**Comment by phit** [comment]
I found this small proxy which fixes slack webhooks to work properly with Discord, works well as a temporary solution.

https://gist.github.com/brussell98/a865ecc2284e958226596accc852ee28

**Comment by carlbennett** [comment]
I'd like the support for Discord notifications. Thank you.

**Comment by Fank** [comment]
@torkelo enought interest?

**Comment by shish** [comment]
Commenting to show interest and subscribe, as more and more of the of the communities I'm involved in are moving to discord :)

**Comment by RedSpid3r** [comment]
+1 to this please

**Comment by carlbennett** [comment]
I found this nodejs relay that works real well for anybody who _needs_ this _right now_ in the current version of Grafana. Instructions in the comments of the Gist.
https://gist.github.com/brussell98/a865ecc2284e958226596accc852ee28

**Comment by Mcdostone** [comment]
Is there someone that can fix the conflict ? I'm so exciting about the discord integration :dancer:

**Comment by torkelo** [comment]
tested this with free discord server and works pretty good. 

image

**Pull request merged**
