### PR TITLE
datasource: support POSTing to Prometheus /series endpoint

### LINKED ISSUE #16519: Feature request: Support POSTing to Prometheus series endpoint
**What would you like to be added**:
The newest Prometheus v2.9.0 rc0 supports POSTing to /series endpoint

**Why is this needed**:

we need compatible with Prometheus.

### PR DESCRIPTION
**Pull request by eahydra**
Signed-off-by: Joseph Lee <joseph.t.lee@outlook.com>

**What this PR does / why we need it**:

The newest Prometheus v2.9.0 rc0 supports POSTing to /series endpoint, we need compatible with Prometheus.

**Which issue(s) this PR fixes**:

Fixes #16519

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Think this would require some version to be set when configuring Prometheus datasource so that users of pre-v2.9.0 rc0 still can use POST for /query and /query_range.

Here's an example of Elasticsearch datasource allowing configuration of version: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/config_ctrl.ts#L25
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/partials/config.html#L26-L31

In this case we should probably have two versions available for selection:
* empty (non set/undefined/0)
* v2.9+ (290)

Then in `querySeries` the version should be checked to decide if POST can be used.

**Comment by eahydra** [comment]
> Think this would require some version to be set when configuring Prometheus datasource so that users of pre-v2.9.0 rc0 still can use POST for /query and /query_range.
> 
> Here's an example of Elasticsearch datasource allowing configuration of version:
> https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/config_ctrl.ts#L25
> https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/partials/config.html#L26-L31
> 
> In this case we should probably have two versions available for selection:
> 
> * empty (non set/undefined/0)
> * v2.9+ (290)
> 
> Then in `querySeries` the version should be checked to decide if POST can be used.

Good advice. I will do change the code later.

**Comment by marefr** [comment]
@eahydra We try to only keep relevant issues and PR's open. Closing this due to lack of response. Let us know when you want to continue work on this and need review and we'll reopen this PR. Thank you

**Comment by aocenas** [comment]
Fixes: https://github.com/grafana/grafana/issues/17342

**Pull request closed without merging**
