### PR TITLE
Alerting: New API endpoint to delete individual rule

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
Currently, when a user deletes a rule via UI, and that rule belongs to a group of multiple rules, the front end has to pull the entire group, modify it and submit it back. 
1. This requires login on the front-end side
2. If the group is changed in a concurrent request between those two operations, the changes made by another user will be reset.

Another problem is a bug described in https://github.com/grafana/grafana/issues/53357 where there are many rules in a group that refer to a deleted datasource. In this case, the user cannot delete\update bad rules via UI. This PR will let this possible.

This PR introduces a new endpoint that allows to delete of a rule by simply providing its UID. The backend code will do all calculations and update the group correctly.

A new endpoint is available by path `/api/v1/ngalert/rules/uid/{RuleUID}` (the section `uid` is to match how folders and dashboards are addressed).

Fixes #
Contributes to https://github.com/grafana/grafana/issues/53357
**Special notes for your reviewer**:

### CODE REVIEW

**Review by gotjosh — COMMENTED** [review]
Can we hold off on merging this one? Doing something like this will further fuel the complexity of our plans, I think.

I’d like other members of our team to review it too.

**Comment by alexweav** [comment]
I don't think we should work around https://github.com/grafana/grafana/issues/53357 by introducing a new special endpoint that works, while the main API doesn't. I think we should fix that bug in the main API, orthogonally, first.

Otherwise, it's really difficult for clients to understand. Users will get frustrated not understanding the minute differences in semantics for how we authz access to resources from different endpoints.

**Comment by alexweav** [comment]
If that bug is out of the way, and we still think this route is useful by that time, I'm good with this change. I just don't think we should add API surface if the main motivator is a temporary workaround.

**Comment by gotjosh** [comment]
I've had an offline discussion with @JacobsonMT and @yuri-tceretian to expand on my thinking with the comment above - The main gist is that I wanted either @alexweav or @JohnnyQQQQ opinions on this. 

Introducing a new endpoint that attaches itself to a database ID **of an alerting specific resource** is without precedent (You can see that in the [temporary spec](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json) this is not done) and my main driver for the block was a sanity check on whether this is detrimental to our future plans on the move to non-transactional storage.

With @alexweav's opinion on deck - I no longer have any concerns about this PR.

**Comment by yuri-tceretian** [comment]
As far as I understand from the comments above, that pretty much ignore the fact that the provisioning API is built on UIDs and address a single rule\contact point etc, the opinion is against the introduction of the endpoint. Fine.

**Comment by gotjosh** [comment]
> As far as I understand from the comments above, that pretty much ignore the fact that the provisioning API is built on UIDs and address a single rule\contact point etc

My bad, I could have been more precise, the provisioning API already has precedent for different semantics as it is part of core Grafana as opposed to part of core alerting (we just happen to own it). 

Realistically, in the future, the alerting API and provisioning API might be served by the same thing.

**Comment by yuri-tceretian** [comment]
I think I will keep it closed as there are too many arguments against it which I think outweigh the reasons for adding this API:
1. an API that addresses a single rule, which increases the complexity of migration to different storage.
2. it does not solve the problem that the rules group POST API would still fail to handle such situations. After the initial investigation, there was a feeling that the fix in the API is more difficult than the introduction of the API.

**Pull request closed without merging**
