### PR TITLE
AzureMonitor: Set Logs portal URL from resource URI

### LINKED ISSUE #52294: Azure Monitor/Dashboard: Panel TimeSeries link does not properly forward to Azure Log Analytics (subscription ID missing in URL)
**What happened**:

Azure Log Analytics link in a TimeSeries table does not properly forward.
When clicked it shows unexpected error in Azure Log Analytics (as shown below).
Upon inspecting the URL generated by Grafana, it seems the subscription ID is absent from the URL.

See the GIF below:
Grafana_Link_Issue

**What you expected to happen**:
Upon clicking Azure links, it should properly forward it to a Sharable Log Analytics Query Link.

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard Panel with a Kusto querying from Log Analytics, formatted as a TimeSeries data.
image

Sample query:

```kusto
customLog_CL
| where $__timeFilter(Date_t) 
   and container == 'container'
   and k_app_s == 'some-app'
   and log == "log.name" 
   and Zone has_any ('eastus','westus2')

| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s
| extend Zone=Zone, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s
| project AppType, Zone, 75th, 90th, 95th, 98th
| order by AppType, Zone asc
```

**Anything else we need to know?**:

Upon inspecting the URL generated by Grafana, the subscription id seems to be missing.

Example URL Generated by Grafana:
```
%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F%2Fresourcegroups%2Frg-ngsa-asb-dev%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fla-aks-avcdefghijkl
                                                                   ^
                                                                   | Subscription ID misssing
```

Modified above URL with subscription ID added:
```
%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F698dcb5a-ae1e-b8b2-cf6b-fc6ef28a315f%2Fresourcegroups%2Frg-ngsa-asb-dev%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fla-aks-avcdefghijkl
                                                                   ^
                                                                   |Here it is added manually
```

**Environment**:
- Grafana version: 8.4.7, 8.5.5
- Data source type & version:
- OS Grafana is installed on: Grafana Docker
- User OS & Browser: Edge, Chrome, Firefox
- Grafana plugins: Azure Monitor
- Others:

### PR DESCRIPTION
**Pull request by aangelisc**
Correctly uses the resource URI to set the portal deep link.

Fixes #52294

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
Tested and working fine for me. I wonder if there is any way preventing us from breaking this again. The only solution I can think of that really ensures that it's working is doing an e2e test. In any case, that's too complicated because it would imply that it should login into the Azure portal too. It's not worth it.

As a low hanging fruit, we could expose `buildDeepLink` (currently private) so at least we can verify that the link is correct with the metadata we expect (even though that doesn't protect us if we change the metadata of the frame).

**Comment by andresmgot** [comment]
BTW, you want to use the label `backport/9.3` not `backport/9.2` :sweat_smile:

**Comment by aangelisc** [comment]
> As a low hanging fruit, we could expose buildDeepLink (currently private) so at least we can verify that the link is correct with the metadata we expect (even though that doesn't protect us if we change the metadata of the frame).

I'm not sure this provides much value as a test because the `buildDeepLink` function doesn't perform any complex logic besides essentially filling in a template string. I think I'll leave this for now and consider alternative options on how we could test this.

**Comment by andresmgot** [comment]
fair point, up to you

**Pull request merged**
