### PR TITLE
Single stat alerts

### LINKED ISSUE #6983: [Feature request] Add Alert support for singlestats
Please include this information:
- What Grafana version are you using?
 v4.0.2 (commit: v4.0.2)

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Mac OS

- What did you do?
Went to a dashboard, clicked on a single stat and expected to find the "Alert" tab.

- What was the expected result?
I was expecting to see the "Alert" tab

- What happened instead?
The "Alert" tab was not present for the Singlestat. It is present for Graph though.

If it relates to *alerting*
- An image of the test execution data fully expanded.
screen shot 2016-12-16 at 02 28 33

### PR DESCRIPTION
**Pull request by rickymoorhouse**
Add support for alerting on single stat alerts 

Verified UI setup, alert state changes in UI with graphite data source with trigger, resolve and no-data.

Fixes: https://github.com/grafana/grafana/issues/6983

### CODE REVIEW

**Comment by rickymoorhouse** [comment]
Looking into test failures...

**Comment by bergquist** [comment]
The code works fine.

But there are some parts that I'm not sure about. 

* When configuring the state dropdown in options it might not align with the reducer in alerting. This might cause confusion about what data grafana is alerting on. 
* It should be possible to connect the Single stat Text/Background color to the state of the alert. 

Without these changes, alerting on the singlestat panel feels too weak.

**Review by bergquist — CHANGES_REQUESTED** [review]
The code works fine.

But there are some parts that I'm not sure about.

When configuring the state dropdown in options it might not align with the reducer in alerting. This might cause confusion about what data grafana is alerting on.
It should be possible to connect the Single stat Text/Background color to the state of the alert.
Without these changes, alerting on the singlestat panel feels too weak.

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana.

Any chance you want to try to solve those problems as well? Otherwise, I will close this PR. I think the solution you have works fine in an environment where everybody understands how it works. But there are currently too many edge cases for this to be merged.

**Comment by rickymoorhouse** [comment]
My use case for this has gone away and whilst I'd like to enhance this to cover more I'm unlikely to have time to at present - I may revisit in the future though. 

Closing.

**Pull request closed without merging**
