### PR TITLE
PanelEdit: Move visualization picker to the top

### PR DESCRIPTION
**Pull request by torkelo**
Step one in v8 panel edit changes. 

Todo:

* [ ]  Fix scrolling 

Screenshot from 2021-02-16 21-05-19

### CODE REVIEW

**Review by mckn — COMMENTED** [review]
I think this works as expected! I'm missing the scrolling in the visualization area (see picture below). 

Skärmavbild 2021-02-17 kl  12 01 02

Also, I don't think the way we have structured the new control feels 100% intuitive. I would like to group the UI elements in a different way. 

Maybe group everything that will change when changing the visualization within a area that feels more connected to the change visualization control. I guess the overrides won't change when you change visualization? Also, the chevron indicating if settings is displayed feels wrong. Maybe have it going in/out from the side.

I will see if I can think of a better way of structuring this. But it is a tricky thing to fit into the current design.

**Comment by mckn** [comment]
This might be an alternative, but I'm not sure.

Skärmavbild 2021-02-17 kl  12 23 28

**Comment by aknuds1** [comment]
Does this PR contain other commits than it should?

**Comment by torkelo** [comment]
@aknuds1 it's targeting a Grafana 8 dev branch, synced it with the master, the non-relevant commits should go away

**Comment by leeoniya** [comment]
i'd prefer not to lose the "Visualization" label. maybe...

```
Visualization    [⬛ Time Series ^]
```

**Comment by osg-grafana** [comment]
Use sentence-case headings. "Time series" rather than "Time Series".

**Comment by torkelo** [comment]
Playing around , this is hard 
Screen Shot 2021-02-20 at 10 17 18

**Comment by torkelo** [comment]
Screenshot from 2021-02-21 07-52-31

**Comment by oddlittlebird** [comment]
At a glance, it doesn't look like this change will require too much documentation change. Possibly just the Add a panel and Panel editor topics.

**Comment by torkelo** [comment]
@oddlittlebird this is just a first step in a few further iterations that will merge the Panel and Field tabs into one named Options. So we will have one Options tab with both panel level settings and field defaults, and an override tab. That will require quite a bit of doc changes I can imagine

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/pull/32124

**Pull request closed without merging**
