### PR TITLE
Remove Origin and Referer while proxying requests

### LINKED ISSUE #13328: [Bug] Grafana data proxy should drop origin header
Using Elasticsearch 5.6 the datasource (in proxy mode) passes tests and connects properly however its impossible to perform any query in a panel. Seems like Grafana proxying is POST'ing requests to ES instead of performing a GET which is causing a 502.

Grafana 5.2.2

`t=2018-09-18T20:15:03+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=1 username=admin datasource=elasticsearch uri=/api/datasources/proxy/2/_msearch method=POST body="{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"my_stats_2018\",\"max_concurrent_shard_requests\":256}\n{\"size\":500,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1521407703352\",\"lte\":\"1537301703352\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"business.objId:6435\"}}]}},\"sort\":{\"@timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}},\"script_fields\":{},\"docvalue_fields\":[\"@timestamp\"]}\n"
`

### LINKED ISSUE #13949: Grafana backend doesn't remove Referer header from request
When datasource is configured with _Server_ Access mode, grafana backend includes `Referer` header which was originally set by browser into request. 
Sometimes it causes some kind of unexpected behaviour, like an [issue with Splunk 7.2](https://github.com/grafana/splunk-datasource/issues/27). In that case, Splunk server returns `401 Unauthorized` if Referer set to URL different from splunk server URL, but if there's no Referer set, it works. Seems, splunk uses `Referer` as a kind of restricting cross-site request forgery. This is legal usage of `Referer`, but server should not rely on this, because this header may be absent in request.

So, it's may be helpful in some cases to remove `Referer` on the backend. I'm not sure, should it be a default behaviour, or an option in datasource config, because [RFC](https://tools.ietf.org/html/rfc7231#section-5.5.2) says

> Some intermediaries have been known to indiscriminately remove
   Referer header fields from outgoing requests.  This has the
   unfortunate side effect of interfering with protection against CSRF
   attacks, which can be far more harmful to their users.
   Intermediaries and user agent extensions that wish to limit
   information disclosure in Referer ought to restrict their changes to
   specific edits, such as replacing internal domain names with
   pseudonyms or truncating the query and/or path components.

, but I'm not sure Grafana is an _Intermediary_ in this case (I think no, because grafana not just a proxy for queries, it may invoke requests by itself, like for alerting).

Let's discuss what's a proper solution accordingly with RFC docs.
https://tools.ietf.org/html/rfc7231#section-5.5.2

### PR DESCRIPTION
**Pull request by roidelapluie**
Fix #13949
Fix #13328

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Do not merge yet

**Comment by roidelapluie** [comment]
now it can be merged

**Review by bergquist — APPROVED** [review]

**Comment by roidelapluie** [comment]
5.3.4 or 5.3.3?

**Comment by torkelo** [comment]
5.3.4 , 5.3.3. will only be a security fix

**Pull request merged**
