### PR TITLE
Chore: Enable whitespace linter

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
As part of effort to harmonize the Go linting with the plugin SDK, enable whitespace linter.

**Special notes for your reviewer**:
This PR is pretty huge, but it's almost all whitespace changes. If you want I can divide it into several smaller PRs, but I might recommend using `git diff` locally to verify that it's almost all whitespace.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by bergquist** [comment]
Borderline if this is valuable or annoying. 

Can we solve this with husky instead? https://github.com/grafana/grafana/blob/master/package.json#L58

**Comment by aknuds1** [comment]
I guess it's down to personal preference, but I really like avoiding unnecessary newlines since I find them noisy when reading code.

**Comment by bergquist** [comment]
A code formatting tool might be able to delete those lines. 

I don't mind getting rid of the white lines. But linting also comes with a cost of increased response time.

**Comment by aknuds1** [comment]
@bergquist Once we've got rid of the extraneous blank lines in this PR, how will it slow us down in daily work? New ones will be caught quickly. If we have a formatter that removes them anyway, the linter will just be there to verify that the formatter did its job.

**Comment by aknuds1** [comment]
@bergquist more importantly, which formatter will remove extra blank lines (corresponding to this linter)? AFAICT `gofmt -s` doesn't.

**Review by bergquist — APPROVED** [review]
I'm concerned about the feedback cycles of this linter. But let's give it a try. We can remove the linting step if it's annoying. The other changes are good :)

**Comment by aknuds1** [comment]
OK thanks @bergquist - let's just disable it if it turns out to be annoying. I think it should result in quick feedback cycles though, since CI fails quickly on linting.

**Pull request merged**
