### PR TITLE
Millisecond tooltip after optimum/minimum analysis of data

### PR DESCRIPTION
**Pull request by utkarshcmu**
Some screenshots:

Without millisecond resolution turned off (by default):
screen shot 2016-02-18 at 10 58 07 pm

With millisecond resolution turned on:
screen shot 2016-02-18 at 10 58 11 pm

### CODE REVIEW

**Comment by utkarshcmu** [comment]
This might be a good starting point for resolving:
#2865
#2248
#1172

**Comment by torkelo** [comment]
cant this be enabled automatically somehow, like a property on the time series returned by the datasource? dont like having an option for something like this

**Comment by utkarshcmu** [comment]
I implemented that in #3124 which is exactly the same as you are saying. But in the tooltip controller, we have to check whether we should show millisecond or just second, and that is what I did in #3124.

**Comment by utkarshcmu** [comment]
But, yeah in #3124 it was only for Opentsdb and not generic. If you want generic, then I can do that.

**Comment by utkarshcmu** [comment]
For screenshots, please check #2865 :)

**Comment by torkelo** [comment]
I think the property should not be on the data source but on the series.

**Comment by utkarshcmu** [comment]
Got your point, will try modify this PR to work like that. Thanks for the feedback!!!

**Comment by utkarshcmu** [comment]
This work is complete. Added bunch of test to test different scenarios as I do not want to break tooltip feature. :)

Please review/merge. Thanks.

**Comment by utkarshcmu** [comment]
If this looks good and can be merged, I can work on enabling millisecond option for Opentsdb. :)

**Comment by utkarshcmu** [comment]
Rebased with master.

**Comment by utkarshcmu** [comment]
The only way to find out whether the tsd is millisecond compatible automatically to parse the timstamps. If we have few timstamps showing millisecond values, that should be enough to enable millisecond time in the tooltip. And that is what is done in this PR. This PR has more tests than the actual code change as tooltip is one of the main features of Grafana, so we make sure we analyze all the scenarios efficiently.

**Comment by utkarshcmu** [comment]
Any feedback here?

**Comment by bergquist** [comment]
I think the millisecond detection should be done in https://github.com/grafana/grafana/blob/master/public/app/core/time_series2.ts then any panel should be able to use it if wanted.

**Comment by torkelo** [comment]
that was my thinking as well

**Comment by utkarshcmu** [comment]
Thanks for the feedback, will move the millisecond detection in the file suggested by @bergquist

**Comment by utkarshcmu** [comment]
Closing this in favor of #4203

**Pull request closed without merging**
