### PR TITLE
Chore: Add new drone step to validate OpenAPI specification

### LINKED ISSUE #73267: Add CI step to validate Grafana's OpenAPI specification
## Problem

There is no automation that validates the OpenAPI specifications. As a result, the upstream specifications are occasionally invalid.

## Acceptance Criteria

- There is already a `make validate-api-spec` in the Makefile of the Grafana codebase, which needs to be added to CI.

### PR DESCRIPTION
**Pull request by yangkb09**
This PR adds a new drone step to validate the OpenAPI specification

Fixes https://github.com/grafana/grafana/issues/73267

Part of larger effort #47827's Milestone 2: OpenAPI Automation

### CODE REVIEW

**Review by papagian — APPROVED** [review]
LGTM, as a future improvement we could change it so that is only runs if the Swagger/OpenAPI specification has changed.

**Comment by nikimanoledaki** [comment]
@papagian that's true! Since we will run the spec validation after the spec generation (when we add this to CI as well), would a `depends_on` block the validation and only run it if the generation happened? I'm not sure if this is how `depends_on` works in Drone (coming from GitHub Actions).

**Comment by papagian** [comment]
> @papagian that's true! Since we will run the spec validation after the spec generation (when we add this to CI as well), would a `depends_on` block the validation and only run it if the generation happened? I'm not sure if this is how `depends_on` works in Drone (coming from GitHub Actions).

I think that we can achieve this with [triggers](https://docs.drone.io/pipeline/triggers/#by-reference)
for example: [pr-lint-backend](https://github.com/grafana/grafana/blob/ae32d43e2b1efa9e0acd969edb7cf9f374b823d3/.drone.yml#L442)
is executed only if there are any backend files modified

**Comment by nikimanoledaki** [comment]
Sounds good! We can do this through the spec generation issue (since it contains a list of [triggers](https://github.com/grafana/grafana/pull/58029/files)). We can move the validation command to run after the spec generation. :)

Added this to the acceptance criteria of that issue: https://github.com/grafana/grafana/issues/73266

**Review by nikimanoledaki — APPROVED** [review]

**Comment by kminehart** [comment]
@nikimanoledaki @yangkb09 I would discourage a trigger specifically for changes on those files. There's a lot that can affect whether this step continues to pass, and we've seen some issues lately with delayed failure because of these triggers. For example, I changed the base image for the step that publishes the "canary" NPM packages, but I wasn't aware that it was broken because the step didn't trigger until someone changed something in `packages/*`. Unless it takes several minutes for this command to pass, I think it'd be fine to run on every PR. :)

**Pull request merged**
