### PR TITLE
grafana.com sign up

### PR DESCRIPTION
**Pull request by Ijin08**
added div for sign up info, 
added function for second animation/view change, 
added styling
skarmavbild 2018-06-13 kl 09 49 50

### CODE REVIEW

**Comment by bulletfactory** [comment]
Had this in the slack channel, but moving to here so it doesn't get lost:

my $.02 on the look and feel:
- I see the convention you’re using is similar to the input box, but not
exact - I’d probably make that more consistent (add slight rounded corners,
1px stroke)
- Typography: Are we using our standard sizes here? I would consider
reducing the size of the bulleted list text and increase the bottom margin
slightly on the <li> - the way it’s wrapping and the tightness makes it
difficult to skim
- I’d also consider adding a bit more bottom margin to the heading to
better establish visual hierarchy and help readability (of course we can’t
get crazy - we don’t want to risk scrolling)
- the button alignment creates weird negative space. Perhaps make it the
full width of the box, like on the “sign in with google/GitHub” buttons?
Left aligning could also solve the issue for me.

**Comment by Ijin08** [comment]
@bulletfactory thanks for great feedback! 
Followed most of your points and it was a huge improvement. Updated the image. M
Might still be some tweaking left.

**Comment by bulletfactory** [comment]
nicely done @Ijin08!

**Comment by torkelo** [comment]
@mattttt @nopzor1200 felt that this approach was not ideal and wants to revisit the option of signing up in the form as you change password, so in addition to having the change password form, you have an email input and a checkbox for grafana.com signup. 

I am not sure how this form should be designed especially around the messaging of the signup textbox. It's going to be tricky as it's an email field that will have 2 purposes, set admin user email & signup for grafana.com.

**Pull request closed without merging**
