### PR TITLE
support alertmanager notification

### PR DESCRIPTION
**Pull request by mtanda**
Implement https://github.com/grafana/grafana/issues/7481

### CODE REVIEW

**Comment by bergquist** [comment]
The problem with this PR is that Grafana will only notify the alertmanager once when state changes. 
The alertmanager expects Grafana to send notifications until the alert stops. So we have to do some refactoring in alerting that would allow a notifier to keep sending notifications even when its already alerting.

**Comment by lucklucif** [comment]
@bergquist 
Do you know when this feature (sending notifications until the alert stops) will be released ? for grafana 5 ?

**Comment by bergquist** [comment]
Depends on https://github.com/grafana/grafana/issues/7330

**Comment by bergquist** [comment]
Since https://github.com/grafana/grafana/pull/10153 have been merged. It should be possible to always return `true` in the alertmanagers ShouldNotify function. Any chance you want to update this PR? :)

**Comment by iksaif** [comment]
I think @Thib17  already has an updated version of that (https://github.com/criteo-forks/grafana/commits/v4.6.x-criteo)

**Comment by bergquist** [comment]
Closing this since we merged https://github.com/grafana/grafana/pull/10192

**Comment by mtanda** [comment]
👍

**Pull request closed without merging**
