### PR TITLE
Add CircleCI step trigger-docs-update

### PR DESCRIPTION
**Pull request by adeverteuil**
**What this PR does / why we need it**:

When commits are pushed to master, I want to trigger a job in the new documentation site's CI/CD to pull changes to documentation content and publish them to staging. I will test how this works for a few days/weeks before going to production.

The new docs staging site: http://staging.docs.grafana.com.s3-website-us-west-2.amazonaws.com/
Repo (private) for the new docs site: https://github.com/grafana/docs.grafana.com

The curl command triggers the `pull-submodule-changes` job defined in the `docs.grafana.com` repository (the new docs site, work in progress). This job runs `scripts/git-pull-changes-from-
upstream.sh` which pulls the `grafana/grafana` repo and checks for updates in any files under `docs/` before building and publishing the docs site.

1. A commit is pushed to `grafana/grafana` branch `master` on GitHub.
2. CircleCI runs the `build-master` workflow for `grafana/grafana`.
3. The `trigger-docs-update` job in `grafana/grafana` triggers the `pull-submodule-changes` CircleCI job for the `grafana/docs.grafana.com` project.
4. The `pull-submodule-changes` job pulls `grafana/grafana` master branch in a Git submodule, checks if any files under `docs/` have changed.
5. If there are any changes, the new Git submodule revision is committed to `docs.grafana.com` modules and pushed to the master branch on GitHub.
6. This triggers CI/CD in the `docs.grafana.com` project to build and publish the new docs site.

**Special notes for your reviewer**:

I'm not experienced with this and I would like someone to validate logic and best practices and look for potential problems.

Is this the right place in the CI/CD workflow to add the job? Will the commit be merged into master by the time the `pull-submodule-changes` job runs? Or should I add a check in `git-pull-changes-from-upstream.sh` to wait for the `build-master` workflow to finish successfully?

I also need to define the `DOCS_CIRCLE_TOKEN` environment variable in the `grafana/grafana` project on CircleCI before merging this PR.

### CODE REVIEW

**Comment by DanCech** [comment]
This looks good to me. The commit happens before circleci runs so that isn't a concern.

**Comment by torkelo** [comment]
Nice! 

Wonder if there is a way to detect docs changes already in this part of trigger? But maybe there is an advantage to have that check in the docs repo check?

**Comment by adeverteuil** [comment]
> Wonder if there is a way to detect docs changes already in this part of trigger?

I gave it some more thought and it's quite easy.

    git diff --name-only HEAD^ | grep -q "^docs"

I made some changes and pushed them to the PR branch.

I would leave the same logic in the docs repo as well in case we want to to trigger the same API call in a different context. For example, we could set a time based trigger to pull changes on a regular basis. Grafana is not the only external repository for docs (enterprise, loki, hm-api), and I haven't checked if all the other ones have CI/CD.

**Comment by bergquist** [comment]
Great work! Love it :)

**Comment by adeverteuil** [comment]
I created the environment variable DOCS_CIRCLE_TOKEN in the CircleCI project "grafana".

It's the value of a personal API key defined in my CircleCI profile. Personal API keys are required for any "write" actions. Project API keys provide read-only permissions so I couldn't use that.
https://circleci.com/docs/2.0/managing-api-tokens/

I'm ready to give this a try. You can merge.

**Review by torkelo — APPROVED** [review]
Great job!

**Pull request merged**
