### PR TITLE
Search add sorting picker

### LINKED ISSUE #22840: Add a sorting picker to search
**What would you like to be added**:

Add a sorting picker to search (which shows when there are multiple searching options register).

**Why is this needed**:

### LINKED ISSUE #22842: Search: fetch available sorting options from the backend
**What would you like to be added**:

It should be possible to fetch available sorting options from the API endpoint (#22839)

**Why is this needed**:

We are going to add ways to sort the search results in different ways. So we need to get available sorting options.

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Add sorting options to Dashboard search and manage dashboards:
- Update Dashboard Search layout
- When using sorting, layout is switched to `list`, i.e. no folder rows are shown.
- Sorted list has all the dashboards available.
- After this PR is merged the sorted result list will be virtualized via #23710 to speed up rendering times and improve UI interaction. 

Screenshots:

Screenshot 2020-04-22 at 15 43 07
Screenshot 2020-04-22 at 15 43 34

**Which issue(s) this PR fixes**:

Fixes #22840 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Wonder if the search results should have a max result width? something like 1300px
Screenshot from 2020-04-22 16-57-10

**Comment by torkelo** [comment]
Would it make sense to always switch to List result when you start searching?

**Comment by Clarity-89** [comment]
> Wonder if the search results should have a max result width? something like 1300px

Yeah, good idea.

> Would it make sense to always switch to List result when you start searching?

I thought about it as well, same when user selects tags. But then what would happen if user switches back to Folder view? Resetting sort in this case makes sense since we're showing folders now, not sure about resetting query and tags.

**Comment by torkelo** [comment]
Yea, maybe the choice between nesting and not nesting should just be something the user can select and we persist it in local storage. 

I discovered some big bugs with search:
https://github.com/grafana/grafana/issues/23792 

You cannot expand a folder you searched for, and when switching to list view the result is empty (would expect to see the dashboards the folder contains)

**Comment by tskarhed** [comment]
Just added support for icons in RadioButtonGroup, if you want to try it here :)

**Comment by Clarity-89** [comment]
@tskarhed awesome news! I was thinking to fix that after 7.0, but will it give it a try in this PR instead :)

**Review by torkelo — APPROVED** [review]

**Comment by Clarity-89** [comment]
@tskarhed I think the icons might need a bit of padding/margin:
Screenshot 2020-04-22 at 19 04 22

**Comment by tskarhed** [comment]
@Clarity-89 Agreed, I just tried them for an icon-only case

**Pull request merged**
