### PR TITLE
ClipboardButton: Use a fallback when the Clipboard API is unavailable

### LINKED ISSUE #45617: Grafana 8.4.0: Copy Invite for Pending User Doesn't Copy Invite Text
**What happened**:

When creating a new user, clicking on the "Copy Invite" button for a pending invite should copy the invite text to the clipboard. It didn't, instead I get a JavaScript error. Error follows:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at ClipboardButton.tsx:35:8
    at Object.Ue (react-dom.production.min.js:52:317)
    at Ke (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at kr (react-dom.production.min.js:100:68)
    at Er (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ne (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ar (react-dom.production.min.js:105:469)
(anonymous) @ ClipboardButton.tsx:35
Ue @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
kr @ react-dom.production.min.js:100
Er @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ne @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Ar @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
ze @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
```

**What you expected to happen**:

The invite text should have been copied to the clipboard.

**How to reproduce it (as minimally and precisely as possible)**:

Click the ⚙️ for Configuration;
Click "Users";
Add a new user;
Click "Pending Invites";
Click "Copy Invite";
Paste from clipboard somewhere.

Note that the contents of the clipboard are whatever was in the clipboard before clicking "Copy Invite".

**Anything else we need to know?**:

Possibly:

* I've just completed a reconfiguration of Nginx and Grafana to get past cross-domain issues when running Grafana behind a reverse proxy;
* I have not configured Grafana to send emails for invites (or anything else).

**Environment**:
- Grafana version: 8.4.0 (Docker)
- Data source type & version: n/a
- OS Grafana is installed on: Docker on Debian 11
- User OS & Browser: Mac OS 11.6.2; Brave Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (x86_64)
- Grafana plugins: default only, none added
- Others: n/a

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- whilst the clipboard api is now supported by most browsers, it's only supported in secure contexts (e.g. over https/localhost)
- let's provide a standard fallback for when that's not the case

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/45617

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]
LGTM 👍

**Comment by alvintownsend** [comment]
Woohoo! Many thanks! 💯

**Comment by bijwaard** [comment]
I guess this will end up in grafana 8.4.3 or higher? In 8.4.2 it is not yet working for me on ubuntu 20.04.4 with firefox and chromium.

**Comment by ashharrison90** [comment]
@bijwaard yep, it'll be released in 8.4.3 soon™️ 👍

**Pull request merged**
