### PR TITLE
Include org id in urls

### LINKED ISSUE #1613: Feature request: include org. name in dashboard URL
In a mutli-tenant setup, when we created a shared link from an specific organization context, then visiting this link only works when the current organization is the same as when the shared link was created.
This is logical, but I think it would be better if the shared link would also contain the organization information, so that grafana could try to automatically switch organization (if user is also part of the organization) when visiting a shared link.

### LINKED ISSUE #2777: Include Organization in urls
I have a problem that I have access to many organizations. Every now and then, someone gives me a link to something on grafana and it doesn't work, because it links to, for example, a dashboard in another organization. If I want to see it, I'm forced to change organization manually and then open that link.

If the organization id were already included in the url, Grafana could figura that automatically (of course, checking if my user has permission for that organization)

### PR DESCRIPTION
**Pull request by shoonoise**
Closes #2777 
Closes #1613
- Add orgId in dashboard URLs
- Change current orgId for user in case it's not the same as in url.

### CODE REVIEW

**Comment by shoonoise** [comment]
@torkelo please review the PR :)

**Comment by shoonoise** [comment]
@torkelo ping

**Comment by bbinet** [comment]
Any chance this can be merged for the next 3.0 release?

**Comment by bergquist** [comment]
I don't like the idea of having orgid in every dashboard url. 

Switching org based on dashboard access could be done without adding the orgid to every url. Please see my suggestion in https://github.com/grafana/grafana/issues/1613

**Comment by syndicut** [comment]
:+1:

**Comment by bergquist** [comment]
I do not like having the orgId in the url. It would require all code that links to a dashboard to include an orgid. Sounds simple but it gets very messy in my opinion.

I would rather suggest a feature to map a subdomain to an organisation. Ex org1.grafana.local/dashbaord/db/dash and org2.grafana.local/dashboard/db/dash

What do you think?

**Comment by shoonoise** [comment]
> I would rather suggest a feature to map a subdomain to an organisation. Ex org1.grafana.local/dashbaord/db/dash and org2.grafana.local/dashboard/db/dash

For me it seems even better! I guess I could implement this in few weeks.

**Comment by bergquist** [comment]
@shoonoise I'm closing this PR. lets keep any future discussion about this in #1613

**Pull request closed without merging**
