### PR TITLE
Move testdata backend to its new location

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

Move testdata code to its new location and adapt the rest of code. 

Now the plugin is fully functional when running in external mode.

**Which issue(s) does this PR fix?**:

Ref https://github.com/grafana/grafana/issues/68973

**Special notes for your reviewer:**

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by xnyo — COMMENTED** [review]
I have tested the plugin in Grafana (with and without the feature flag) and it works great! :rocket: 

Both GoLand and vscode pick up the imports with the `go.work` file properly.

I have left a couple of nits and also something to discuss before approving:

Currently, the tests for decoupled core plugins won't be run.

A possible solution is changing the Makefile to run tests for decoupled plugins. I have forked your branch [here (giuseppe/testdata-decoupled-backend-makefile)](https://github.com/grafana/grafana/tree/giuseppe/testdata-decoupled-backend-makefile) and done so, if you want to take a look.

By doing so I am not sure if we need any changes in drone but we can take a look from the CI if the decoupled plugin tests are run, if not we can address it.

Also, the following file contains the test from the example which always fails:

```
public/plugins/testdata/pkg/plugin/datasource_test.go
```

So that file should be removed.

Apart from that, awesome work!! :rocket:

**Comment by andresmgot** [comment]
Thanks @xnyo, really good catch! The lint was being skipped too, I fixed it as well :+1:

**Review by xnyo — APPROVED** [review]
LGTM :rocket: ! Thanks for addressing the feedback! :pray: 

Just one small thing left regarding tests. It looks like drone uses `go test` directly rather than the `Makefile` target in the `test-backend` step:

https://github.com/grafana/grafana/blob/f3ffc850aaf0b0c46336c6af1a83db97c85dd793/scripts/drone/steps/lib.star#L570

Example: https://drone.grafana.net/grafana/grafana/129292/3/8

This would need to be changed to `make test-go-unit` or similar, or tests for decoupled plugins won't be run in CI. However maybe there's another reason why `make` was not used for that step. I think we can leave it for a follow-up PR.

On the other hand, the lint step in CI uses the `Makefile` target so that's great: https://drone.grafana.net/grafana/grafana/129292/4/6 :tada: 

```
+  make lint-go
```

**Comment by andresmgot** [comment]
> It looks like drone uses `go test` directly rather than the `Makefile` target in the `test-backend` step:

argh, right. Thanks for pointing out, I'll open a follow-up PR to avoid tagging more people to this PR

**Pull request merged**
