### PR TITLE
[WIP] Auto-generate: Split user and migration diffs into separate API calls

### LINKED ISSUE #76985: Auto-generate: Break user changes and migration changes into two separate calls
Break out userDiff + migrationDiff into two separate openAI calls to improve feature stability / determinism.

This will require supporting triggering two different streams from the same genAI button click which is not currently supported.

### PR DESCRIPTION
**Pull request by SandersAaronD**
**What is this feature?**

This updates the OpenAI call logic for diff summarization to call OpenAI separately for user changes and for migration changes.

**Why do we need this feature?**

To improve quality of generated diff summaries.

**Who is this feature for?**

Anyone using DashGPT.

**Which issue(s) does this PR fix?**:

Fixes #76985 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by SandersAaronD** [comment]
In my opinion this should undergo at least a little cleanup before being pushed out. In particular, error handling is off still. It does work though.

**Comment by SandersAaronD** [comment]
On further review this propagates errors well and should be just fine. History will need some extra work, but history on the diff was not functional previously so it's not a regression.

**Review by nmarrs — COMMENTED** [review]
I'm not as confident on this one 😬 between increased cost of maitenance due to code re-use and possibility for infinite generation 🤯 



https://github.com/grafana/grafana/assets/22381771/a598f6ee-df4f-4764-bb37-5e20da86a50f


I think for diff generation we should maybe take a step back, collect user feedback (like Roblox etc) and go from there - I'm worried if we shoehorn this optimization in for ObsCon that we will introduce more regressions vs increased stability 😬 

I will note when this was working it was super fast and seemed like the approach we will most likely want to go with - but we probably should do that in a more deliberate / scalable way IMO

**Comment by SandersAaronD** [comment]
> I'm not as confident on this one 😬 between increased cost of maitenance due to code re-use and possibility for infinite generation 🤯
> 
>  infinite.generation.mov 
> I think for diff generation we should maybe take a step back, collect user feedback (like Roblox etc) and go from there - I'm worried if we shoehorn this optimization in for ObsCon that we will introduce more regressions vs increased stability 😬
> 
> I will note when this was working it was super fast and seemed like the approach we will most likely want to go with - but we probably should do that in a more deliberate / scalable way IMO

This wasn't reproducing for me before but is now, appears to be an error in the plugin itself. Since I've got plugin work queued regardless I'll try to track it down; I've (further) tweaked the dashgpt functionality and think it's clean when it doesn't hit the cases where the plugin is sending error messages.

**Pull request closed without merging**
