### PR TITLE
adding ebs_volume_attribute to use DescribeVolumes API

### LINKED ISSUE #8014: [Bug] ebs_volume_ids only accepts a single instanceId
**Use case:** We are monitoring a group of servers from Amazon Web Services. We are using templating to pull in the correct group of servers (1 or more). We also want to monitor Disk I/O on that group of servers so we attempt to create another template using the _ebs_volume_ids_ function and pass in the variable with the list of servers we would like to monitor. 

**Result**: We get an error that we are using incorrect instnaceIds. The _ebs_volume_ids_ function will work if there is a single server returned from the first template query and the "Include All option" is not selected. If we select more that one instanceId or the all option the _ebs_volume_ids_ query will break.

- What Grafana version are you using? - **v4.1.2**
- What datasource are you using? - **AWS Cloudwatch**
- What OS are you running grafana on? - **CentOS 7**

 Please let me know if you need any additional details or screenshots and I can capture and provide those.

### PR DESCRIPTION
**Pull request by davis190**
Adds a new template function for cloudwatch that allows searching for EBS volumes by using filters. Almost identical to the current ec2_instance_attribute template function.

Fixes #8014 in a different way allowing you to pull multiple volumeIds at a time using filters.

### CODE REVIEW

**Comment by jonathanwalker** [comment]
+1 Would like the ability to search EBS volumes through filters in order to get disk i/o for EBS volumes associated to the EC2 instance. Looks good!

**Comment by IngmarStein** [comment]
@torkelo are you considering merging this?

**Comment by torkelo** [comment]
closing this as there are merge conflicts & no unit tests. 

I am really sorry for letting this PR be without feedback for one year! That is not acceptable. We will make sure we respond & give feedback in a timely fashion in the future.

**Comment by AdilHoumadi** [comment]
@torkelo, Is there any alternative to this feature ?

**Pull request closed without merging**
