### PR TITLE
Build: removed circular dependencies to make grafana/ui build again

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
This PR fixes a couple of things:

1. Refactored so we don't have circular dependencies in the grafana-ui. This causes the rollupjs bundling to explode and we can't publish the grafana-ui npm package.
2. Removed warning about OrganizeTransformEditor imported types from grafana-data as local package.

**Which issue(s) this PR fixes**:
Should make master build again

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by mckn** [comment]
@dprokop so when running this locally everything is green except the `@grafana/toolkit`.

I get the following error:


```
lerna ERR! yarn run build exited 1 in '@grafana-plugins/input-datasource'
lerna ERR! yarn run build stdout:
$ grafana-toolkit plugin:build
  Created: /Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/.prettierrc.js
  
  
  
  /Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/src/InputConfigEditor.tsx
    59:114  error  Replace `⏎··········datasource.·This·is·an·appropriate·place·to·enter·a·few·values.·Large·datasets·will·perform·better·in·other⏎·········` with `·datasource.·This·is·an·appropriate⏎··········place·to·enter·a·few·values.·Large·datasets·will·perform·better·in·other`  prettier/prettier
  
  /Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/src/InputDatasource.test.ts
    3:9  error  Replace `⏎··DataFrame,⏎··DataFrameDTO,⏎··DataSourceInstanceSettings,⏎··MutableDataFrame,⏎··PluginMeta,⏎··readCSV,⏎` with `·DataFrame,·DataFrameDTO,·DataSourceInstanceSettings,·MutableDataFrame,·PluginMeta,·readCSV·`  prettier/prettier
  
  /Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/src/testHelpers.ts
    4:59  error  Replace `⏎··options:·Partial<DataQueryRequest<TQuery>>⏎` with `options:·Partial<DataQueryRequest<TQuery>>`  prettier/prettier
  
  ✖ 3 problems (3 errors, 0 warnings)
    3 errors and 0 warnings potentially fixable with the `--fix` option.
  
  
  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
- Preparing
✔ Preparing
- Linting
  Trace: Error: 3 linting errors found in 8 files
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/tasks/plugin.build.ts:107:11
      at step (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:107:62)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/utils/useSpinner.ts:13:15
      at step (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
✖ 3 linting errors found in 8 files
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@grafana-plugins/input-datasource'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dprokop** [comment]
@mckn this is a new thing introduced by @ryantxu (https://github.com/grafana/grafana/pull/20850). Think you need to fix the prettier issues in the input datasource plugin ;)

**Comment by mckn** [comment]
> @mckn this is a new thing introduced by @ryantxu (#20850). Think you need to fix the prettier issues in the input datasource plugin ;)

Haha, your are right! Should I add it to this PR as well?

**Review by dprokop — APPROVED** [review]
<3

**Comment by mckn** [comment]
With the prettier formatting fixed I am getting another error. Do you know where I can find that config file that is missing? @ryantxu @dprokop 

```
- Preparing
✔ Preparing
- Linting
✔ Linting
- Running tests
  Trace: Error: ENOENT: no such file or directory, copyfile '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/node_modules/@grafana/toolkit/src/config/jest.plugin.config.local.js' -> '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/jest.config.js'
      at Object.copyFileSync (fs.js:1790:3)
      at Object.exports.loadJestPluginConfig (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/config/jest.plugin.config.ts:105:8)
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/tasks/plugin/tests.ts:16:24
      at step (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:117:57)
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:106:16)
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/tasks/plugin/tests.ts:9:20
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/utils/useSpinner.ts:10:13
      at step (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:117:57)
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:106:16)
      at Object.testPlugin (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/utils/useSpinner.ts:6:27) {
    errno: -2,
    syscall: 'copyfile',
    code: 'ENOENT',
    path: '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/node_modules/@grafana/toolkit/src/config/jest.plugin.config.local.js',
    dest: '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/jest.config.js'
  }
      at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/src/cli/utils/useSpinner.ts:13:15
      at step (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
✖ ENOENT: no such file or directory, copyfile '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/node_modules/@grafana/toolkit/src/config/jest.plugin.config.local.js' -> '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/plugins-bundled/internal/input-datasource/jest.config.js'
error Command failed with exit code 1.

```

**Comment by ivanahuckova** [comment]
Good job @mckn. I have a question, does this have any performance/other impact?
image

**Review by ivanahuckova — APPROVED** [review]

**Comment by mckn** [comment]
> Good job @mckn. I have a question, does this have any performance/other impact as we are also exporting it in themes/index.ts?
> image

Thanks! 🙏 Good question! 

No, it is the same thing. I think I probably changed it during debugging to try to find the root cause of the circular dependency. We can probably revert that one. Good find! 👍

**Comment by ivanahuckova** [comment]
> > Good job @mckn. I have a question, does this have any performance/other impact as we are also exporting it in themes/index.ts?
> 
> Thanks! 🙏 Good question!
> 
> No, it is the same thing. I think I probably changed it during debugging to try to find the root cause of the circular dependency. We can probably revert that one. Good find! 👍


Okay, just making sure. 🙂And thank you for fixing my imports from `grafana/ui` that are within `grafana/ui`.

**Pull request merged**
