### PR TITLE
Influxdb measurements limit conf #8593

### PR DESCRIPTION
**Pull request by thuck**
This PR includes the ability to configure the measurements limit per datasource for influxdb. #8593 

[Demo](http://i.imgur.com/bF7oV1J.gifv)

### CODE REVIEW

**Comment by torkelo** [comment]
I would prefer to not have an option for this. Is this option needed in your case for templating variable or for the query editor dropdown?

**Comment by thuck** [comment]
More for the query editor dropdown in the case where we could have more than 100 measurements.

**Comment by thuck** [comment]
@torkelo we could also implement some kind of pagination using the limit + offset.
So if an user do not input any value it would do a pagination, if an user starts to type it would run a show measurements with a regex. It would be a cleaner solution, no options necessary.
My only concern with this would be the fact that it's not a real pagination, influx do not return how many pages are left, what would mean that all the control over this would be a grafana logic.

**Comment by torkelo** [comment]
but for that case you can filter and search measurements

**Comment by thuck** [comment]
Sure, but if you don't the have measurement name it's complicated to explore.
Which strategy would you prefer to solve the #8593 ?

**Comment by torkelo** [comment]
but you must know the first letter or so of the measurement name?

**Comment by torkelo** [comment]
don't know how a paging solution would work. but an option for this seems bad, need a better solution.

**Pull request closed without merging**
