### PR TITLE
LogsPanel: Show all received logs 

### LINKED ISSUE #31247: Logs panel only shows first batch of query results
**What happened**:
When querying a Loki data source and the result is split over multiple objects (i.e. response.data.result is an array or objects - see image attached below), the logs panel only shows the results from the first item in the array. This same limitation applies to the 'data' tab of the query inspector, where this only shows the first item in the results array.

**What you expected to happen**:
All items in the result array should be shown.

**How to reproduce it (as minimally and precisely as possible)**:
Query a (Loki?) data source with a stream query and the results to be displayed in a Log panel, where you know there will be a number of different labels (this may also require a parser expression) resulting in a number of results objects returned.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Loki 2.1.0
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS 10.15 / FireFox / Chrome
- Grafana plugins: Logs panel

image

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Only first 500 logs were shown in logs panel as we wren't sending the rowLimit. RowLimit then defaulted to 500.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31247

### CODE REVIEW

**Review by Elfo404 — COMMENTED** [review]
I'm not sure about this, shouldn't the default behavior of the LogRows be "do not limit" if no limit is passed to the component? 🤔

**Comment by ivanahuckova** [comment]
Hmmm, yeah. That is a good point. @aocenas do you remeber why was this defaulted to 500 and not logRows.length?

**Comment by aocenas** [comment]
@ivanahuckova didn't really add that limit, seems to be there a long time. I guess just part of it being an alpha panel at some point and nobody noticed. I think it would make more sense to remove this prop completely as we limit the rows on the data source side.

**Review by Elfo404 — APPROVED** [review]
Looks great! 🚀

**Pull request merged**
