### PR TITLE
FlameGraph: Refactor and simplify styles

### PR DESCRIPTION
**Pull request by torkelo**
While working on https://github.com/grafana/grafana/pull/66411 I could not help but remove all the complex height and width logic that can all be handled by css.

### CODE REVIEW

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 

This is a great simplification but appears to add a scroll bar in explore instead of being tall enough to fit the content - honestly though I think that's fine for the simplification it brings.

**Comment by torkelo** [comment]
>  This is a great simplification but appears to add a scroll bar in explore instead of being tall enough to fit the content - honestly though I think that's fine for the simplification it brings.

@joey-grafana  that is strange, I don't see any different on this branch compared to ops which also show scrollbar (for the full explore page) 

https://ops.grafana-ops.net/explore?orgId=1&left=%7B%22datasource%22:%22s-9W0n5Vz%22,%22queries%22:%5B%7B%22scenarioId%22:%22flame_graph%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22testdata%22,%22uid%22:%22s-9W0n5Vz%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by torkelo** [comment]
@joey-grafana ok, pushed an update. Should be identical now.

**Comment by joey-grafana** [comment]
> @joey-grafana ok, pushed an update. Should be identical now.

That's fixed it! 👍

**Pull request merged**
