### PR TITLE
WIP: add Chart.js renderer

### PR DESCRIPTION
**Pull request by mtanda**
Just proposal.
The jQuery Flot is good graph plot library, but the development is stopped.
Grafana modify the Flot locally, but Grafana teams doesn't want to modify it so much.

I think if Grafana support another actively development library, we can add feature to the library, and make Grafana graph better.

So, I propose to support Chart.js renderer as second renderer.

The library is actively developed and have a lot of star.
https://github.com/chartjs/Chart.js

How do you think?

### CODE REVIEW

**Comment by torkelo** [comment]
Interesting, will definitly need a lot of architectural work to handle two graph libs with out super messy code. 

Will have to investigate the plugin architecture in chartjs and see how extensible it is. It would be nice to be able to move to a more maintained graph lib, just no other graph lib is as feature rich as flotcharts so to reach feature parity would require a lot of custom extensions (I think) to chartjs

**Comment by mtanda** [comment]
I understand there are so many problem. But there are advantage to use newer library.

I notice that the Chart.js doesn't support some of Flot feature.
For example, Chart.js doesn't support Staircase plot.
Support all Flot feature at once is not realistic, provide Chart.js renderer as alpha, and add feature incrementally is realistic.

Do you know OffscreenCanvas?
https://wiki.whatwg.org/wiki/OffscreenCanvas
> Making canvas rendering contexts available to workers will increase parallelism in web applications, leading to increased performance on multi-core systems.

It will increase canvas rendering performance.

Chrome will support OffscreenCanvas.
https://bugs.chromium.org/p/chromium/issues/detail?id=563816

If OffscreenCanvas is supported in major browser, the Chart.js will consider supporting OffscreenCanvas.

Using newer library provide benefits in the future.

**Comment by mtanda** [comment]
Currently status of Chart.js support.
chartjs

**Comment by majj** [comment]
+1

**Comment by mtanda** [comment]
I think live chart is very good feature for Grafana Live.
https://github.com/chartjs/Chart.js/pull/3399

**Comment by utkarshcmu** [comment]
Live charts are awesome! 👍  to Chart.js

**Comment by torkelo** [comment]
closing this as it's drifted a bit too far from master, and is perhaps better to start this as an external plugin

**Pull request closed without merging**
