### PR TITLE
Metrics: Fix internal metrics endpoint not accessible from browser if basic auth is enabled

### LINKED ISSUE #86902: grafana: internal metrics endpoint not accessible from browser if basic auth is enabled
### What happened?

```
#################################### Internal Grafana Metrics ############
# Metrics available at HTTP URL /metrics and /metrics/plugins/:pluginId
[metrics]
enabled              = true
interval_seconds     = 10
# Disable total stats (stat_totals_*) metrics to be generated
disable_total_stats = false
# The interval at which the total stats collector will update the stats. Default is 1800 seconds.
total_stats_collector_interval_seconds = 1800

#If both are set, basic auth will be required for the metrics endpoints.
basic_auth_username = foo
basic_auth_password = bar
```

If basic auth is enabled for the internal metrics endpoint, it is not accessible via the browser. (The browsers do not pop-up the dialog box to provide basic auth credentials).

### What did you expect to happen?

If basic auth is enabled, the browser should pop-up the dialogue box to fill the username and password of the metrics endpoint and the metrics should be visible ic case of right credentials.

### Did this work before?

no

### How do we reproduce it?

1. enable internal metrics and set the basic auth username and password in the ini file
2. start the grafana and open the http://<IP>:3000/metrics endpoint

**I have identified the fix for this issue and would like to open the PR.**

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: latest (I have checked by building the binary from main branch)
OS: Ubuntu
Browser: Chrome/Edge

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by wasim-nihal**
**What is this feature?**

fix internal metrics endpoint not accessible from browser if basic auth is enabled

**Why do we need this feature?**

enable access of /metrics endpoint from the browsers if basic auth is enabled.

**Who is this feature for?**

All Grafana users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/86902

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by wasim-nihal** [comment]
@mgyongyosi could you please review this change or direct it to the right team?

**Comment by wasim-nihal** [comment]
@gelicia can you please take a look?

**Comment by gelicia** [comment]
@wasim-nihal this is not something I am knowledgable enough to review, but I sent it to @grafana/backend-platform to take a look at

**Comment by gelicia** [comment]
@wasim-nihal I am pinging a team internally about this one. Thank you for your patience!

**Comment by wasim-nihal** [comment]
> @wasim-nihal I am pinging a team internally about this one. Thank you for your patience!

Thank you @gelicia !!

**Review by mgyongyosi — APPROVED** [review]

**Review by IevaVasiljeva — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by mgyongyosi** [comment]
@wasim-nihal Could you please rebase this branch on main?

**Comment by wasim-nihal** [comment]
@mgyongyosi, @IevaVasiljeva thanks for reviewing this change. I have rebased the branch.

**Comment by linoman** [comment]
@wasim-nihal Thank you for your contribution.

**Pull request merged**
