### PR TITLE
Add color to prefix and postfix in singlestat panel

### PR DESCRIPTION
**Pull request by ApsOps**
| Before | After |
|-------|-------|
| before | after |

### CODE REVIEW

**Review by Ijin08 — APPROVED** [review]

**Comment by bergquist** [comment]
Thank you for contributing to Grafana!

**Comment by ApsOps** [comment]
@3IWOH There you go https://github.com/grafana/grafana/pull/11892

**Comment by torkelo** [comment]
was there a strong reason to add this (feature request)? the prefix is usually added as a label / heading and was not designed to be given the value color. Now we might need 2 new options to support original behavior :)

**Comment by torkelo** [comment]
I can buy that postfix gets the color as it is commonly used as unit, but not prefix. but then I guess it gets a bit random / inconsistent  :)

**Comment by 3IWOH** [comment]
Thanks for this @ApsOps! Here is an example of when we would not like to color the postfix:
image

**Pull request merged**
