### PR TITLE
Cherry picks for 7.1.0-beta2

### PR DESCRIPTION
**Pull request by papagian**
--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Fix build-in plugins failing to load in windows, (#25982), merge-sha: bcaa42fbb3ff28eb289d62c43145f8f1484180a7
  * Plugins: Provide license token directly via plugin environment, (#25987), merge-sha: b5ca2381bc9f4b7c5747a6d11149b6d02973ec2c
  * Explore: Fix href when jumping from Explore to Add data source, (#25991), merge-sha: c9751707c5630ba721bd45a7bdf4fdd66f422d02
  * Value Mappings: remove unused operator property from interface, (#25989), merge-sha: 73e82af4df77931acedcce5a73e6a2267826f1d2
  * Loki: Allow aliasing Loki queries in dashboard, (#25706), merge-sha: 5789f80e14fab219890166af75193f00c733ef9c
  * Panel Loading: spin clockwise, not counter clockwise, (#25998), merge-sha: 90a5a85eb1f1b67a7abfe2d079cc78767c9c6c5a
  * Reset password: Fix styling, (#26002), merge-sha: 9e47114c45bac0acf921c6811b40967e025dc917
  * Monaco: check suggestions against current word, (#25992), merge-sha: 085b2f3dbf85c7a4ce03d675215ab1d8ab6428ad
  * CircleCI: Upgrade build pipeline tool, (#26006), merge-sha: 3e9e2db384361e847d15842c489bf93f33ab2164
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x bcaa42fbb3ff28eb289d62c43145f8f1484180a7
  git cherry-pick -x b5ca2381bc9f4b7c5747a6d11149b6d02973ec2c
  git cherry-pick -x c9751707c5630ba721bd45a7bdf4fdd66f422d02
  git cherry-pick -x 73e82af4df77931acedcce5a73e6a2267826f1d2
  git cherry-pick -x 5789f80e14fab219890166af75193f00c733ef9c
  git cherry-pick -x 90a5a85eb1f1b67a7abfe2d079cc78767c9c6c5a
  git cherry-pick -x 9e47114c45bac0acf921c6811b40967e025dc917
  git cherry-pick -x 085b2f3dbf85c7a4ce03d675215ab1d8ab6428ad
  git cherry-pick -x 3e9e2db384361e847d15842c489bf93f33ab2164

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM - verified with `grabpl verify-cherrypicks`.

**Comment by marefr** [comment]
I can see there's still one PR open in beta2 milestone #25992. But doesn't seem to be reviewed so guess it should be in a different milestone?

**Comment by papagian** [comment]
> I can see there's still one PR open in beta2 milestone #25992. But doesn't seem to be reviewed so guess it should be in a different milestone?

good catch!

**Comment by aknuds1** [comment]
CI fails on building enterprise due to picking the wrong grafana-enterprise committish again. I'll see if I can figure it out.

**Comment by papagian** [comment]
> I can see there's still one PR open in beta2 milestone #25992. But doesn't seem to be reviewed so guess it should be in a different milestone?

It is merged now and I have cherry-picked it too.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
I have a fix incoming for the CI failure.

**Comment by aknuds1** [comment]
Fix for CI: https://github.com/grafana/grafana/pull/26006.

**Pull request merged**
