### PR TITLE
Logs: Handle clicks on legend labels in histogram

### LINKED ISSUE #48450: Log volume legend-buttons do not filter the logs
**Describe the bug**
When attempting to filter the log levels down, the toggles are not filter the actual logs. The Log Volume panel updates, but not the Log panel.

**To Reproduce**
1. Go To Explore Loki
2. Select some logs that produce multiple log levels (info, debug, error, warning, etc.)
3. Select a single Log Level to filter on

**Expected behavior**
The Log lines filter down to only the selected Log Level

**Actual behavior**
All Logs are still showing, regardless of the Log Level toggle that was selected. No filtering is happening.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Version: First noticed this when I updated to 8.4.6 and it is still broken in the newly released 8.5.0
 
Info
Error
Error_Info

### PR DESCRIPTION
**Pull request by gabor**
Fixes https://github.com/grafana/grafana/issues/48450

in the old-histogram, when the user clicked on the labels in the legend (on the log-levels basically), the logs were filtered too.

this does not work in new-histogram.

this PR handles that use-case. we do these things:
1. we move the new-histogram next to the old-histogram in the code (we need this because how callbacks are connected)
2. we remove the "title" of the log-volume-box to blend in more visually
3. we add the necessary callback-functions to new-histogram.

NOTE: i tried to not do any visual changes, if possible. hopefully it looks "good enough". if not, we can of course tune it more, if needed.

i consider this as the first step, to fix the regression.

as next steps, i'd like to move the code so that both from-old-data and from-new-data the same widget draws the same `ExploreGraph` object. otherwise we risk that sometimes we "forget" the old-histogram-mode.

### CODE REVIEW

**Comment by ifrost** [comment]
Why the histogram is sad? :D 

Screen Shot 2022-06-01 at 09 46 04

**Comment by gabor** [comment]
> Why the histogram is sad? :D
> 
> Screen Shot 2022-06-01 at 09 46 04

😂 fixed.

**Review by ivanahuckova — APPROVED** [review]
Actually, I would maybe even add this to 9.0. The changes seem big, but they are pretty straight forward. LGTM!

**Comment by gabor** [comment]
> Actually, I would maybe even add this to 9.0. The changes seem big, but they are pretty straight forward. LGTM!

hmm. interesting idea ... i'll try to backport it somehow to 9.0.1.

**Comment by tonychoe** [comment]
This fix missed 9.1.x, right? when will be the release?

**Comment by gabor** [comment]
hi @tonychoe, it was included in 9.1.x, i have just tried with 9.1.4, and it works in it (clicking on the log-labels in the histogram filters the logs).

**Pull request merged**
