### PR TITLE
Chore: Update typescript to v4.2.4

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Typescript v4.2 brings a [number of small improvements and bug fixes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/) and it doesn't seem like we're affected by the [breaking changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#breaking-changes). More importantly it fixes the issue with maximum call stack exceeded (happens when updating some of the packages, e.g. react-hook-form, to the latest version) error when running `yarn start`. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Clarity-89** [comment]
@kaydelaney do you have any idea how to fix those slate-related type errors?

**Review by hugohaggmark — COMMENTED** [review]
Code looks good, strict errors are failing though. Wow, all my strict errors work is undone 😢

**Comment by Clarity-89** [comment]
> Code looks good, strict errors are failing though. Wow, all my strict errors work is undone 😢

Will look at fixing those errors. If not for your work, that number would be way higher now 😄

**Review by zoltanbedi — APPROVED** [review]
lgtm, maybe as a next step we could also update the grafana/eslint-config dependency.

**Pull request merged**
