### PR TITLE
Time series/Bar chart panel: Add ability to sort series via legend

### LINKED ISSUE #35429: Time series panel: add ability to sort series via legend
Missing thing from flot->uPlot migration is ability to sort the legend items when the legend table shows series calcs:

https://user-images.githubusercontent.com/2376619/121360826-0c323a00-c935-11eb-9bfb-b8c45675cf5b.mp4

- [ ] When sorting the series via legend the sort order should affect the stacking of the series.
- [ ] Legend sort should be persistent

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it:**
This pr adds the long awaited feature for the time series panel to be able to sort the legends.

## TODO

- [x] Stacking should follow the ordering
- [x] Tests
- [x] Bar chart sorting?
- [x] Documentation

## Issues to be worked on later

- [ ] Barchart stacking values not shown in tooltip, different parts are not highlighted

https://user-images.githubusercontent.com/13729989/138090156-0b572327-4093-4e2e-b2da-8bf537811fdb.mp4

- [ ] Barchart stacking with ordered legend doesn't take effect for the first render

https://user-images.githubusercontent.com/13729989/138099796-0bec7036-2ebf-4c00-a1ed-e435ca648c4d.mp4

**Which issue(s) this PR fixes**:

Fixes #35429

**Special notes for your reviewer**:

<details>
<summary>Panel JSON for testing</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 204,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 4,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "C-series"
            },
            "properties": [
              {
                "id": "custom.stacking",
                "value": {
                  "group": "B-g",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "D-series"
            },
            "properties": [
              {
                "id": "custom.stacking",
                "value": {
                  "group": "B-g",
                  "mode": "normal"
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [
            "min",
            "max"
          ],
          "displayMode": "table",
          "placement": "right",
          "sortBy": "Max",
          "sortDesc": false
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,2,3"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,1,1"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,1,1"
        },
        {
          "hide": false,
          "refId": "D",
          "scenarioId": "csv_metric_values",
          "stringInput": "2,2,2"
        }
      ],
      "title": "Stacking groups(Time Series)",
      "type": "timeseries"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 4,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "max": true,
        "min": true,
        "rightSide": true,
        "show": true,
        "sort": "max",
        "sortDesc": false,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "8.3.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {
          "$$hashKey": "object:310",
          "alias": "C-series",
          "stack": "D"
        },
        {
          "$$hashKey": "object:317",
          "alias": "D-series",
          "stack": "D"
        }
      ],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,2,3"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,1,1"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,1,1"
        },
        {
          "hide": false,
          "refId": "D",
          "scenarioId": "csv_metric_values",
          "stringInput": "2,2,2"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Stacking groups(Graph)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "$$hashKey": "object:58",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "$$hashKey": "object:59",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 4,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 9
      },
      "id": 9,
      "options": {
        "legend": {
          "calcs": [
            "min",
            "max"
          ],
          "displayMode": "table",
          "placement": "right",
          "sortBy": "Max",
          "sortDesc": true
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "-10,20,10"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,10,10"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,20,20"
        }
      ],
      "title": "Stacking(Time Series)",
      "type": "timeseries"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 9
      },
      "hiddenSeries": false,
      "id": 10,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "max": true,
        "min": true,
        "rightSide": true,
        "show": true,
        "sort": "max",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "8.3.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "-10,20,10"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,10,10"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,20,20"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Stacking(Graph)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "$$hashKey": "object:58",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "$$hashKey": "object:59",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 30,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 18
      },
      "id": 12,
      "options": {
        "legend": {
          "calcs": [
            "max"
          ],
          "displayMode": "table",
          "placement": "right",
          "sortBy": "Max",
          "sortDesc": true
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "pluginVersion": "8.3.0-pre",
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "-10,20,10"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,10,10"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,20,20"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Stacking bars(Time Series)",
      "type": "timeseries"
    },
    {
      "aliasColors": {},
      "bars": true,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 18
      },
      "hiddenSeries": false,
      "id": 11,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "max": true,
        "min": false,
        "rightSide": true,
        "show": true,
        "sort": "max",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": false,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": false
      },
      "percentage": false,
      "pluginVersion": "8.3.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "-10,20,10"
        },
        {
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "10,10,10"
        },
        {
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "20,20,20"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Stacking bars(Graph)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "$$hashKey": "object:58",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "$$hashKey": "object:59",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMin": 0,
            "fillOpacity": 40,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 16,
        "w": 24,
        "x": 0,
        "y": 27
      },
      "id": 14,
      "options": {
        "barWidth": 0.79,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [
            "last"
          ],
          "displayMode": "table",
          "placement": "right",
          "sortBy": "Last",
          "sortDesc": true
        },
        "orientation": "auto",
        "showValue": "never",
        "stacking": "none",
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "csvFileName": "js_libraries.csv",
          "refId": "A",
          "scenarioId": "csv_file"
        }
      ],
      "title": "Bar chart",
      "type": "barchart"
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMin": 0,
            "fillOpacity": 40,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 16,
        "w": 24,
        "x": 0,
        "y": 43
      },
      "id": 15,
      "options": {
        "barWidth": 0.79,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [
            "last"
          ],
          "displayMode": "table",
          "placement": "right",
          "sortBy": "Last",
          "sortDesc": false
        },
        "orientation": "auto",
        "showValue": "never",
        "stacking": "normal",
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "csvFileName": "js_libraries.csv",
          "refId": "A",
          "scenarioId": "csv_file"
        }
      ],
      "title": "Bar chart stacking",
      "type": "barchart"
    }
  ],
  "refresh": "",
  "schemaVersion": 31,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-15m",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Legend ordering",
  "uid": "9R-feoDnz",
  "version": 14
}
```
</details>

### CODE REVIEW

**Review by dprokop — COMMENTED** [review]
Great progress @zoltanbedi .

Few UI/UX things that would be good to fix with this PR. Take a look at the video below and mind the legend table behavior when sorting:

https://user-images.githubusercontent.com/2376619/137103776-b062760b-eeef-4881-a721-ac9811df8d94.mov

I think we should implement the following updates to the legend:
- [x] Add space in each header that accommodates the sort order icon - to avoid jumping of the legend columns.
- [x] I think then legend values and headers should be left-aligned
- [x] Let's make the sort order icon `xs` rather than `sm` and make sure the default 8px margin of the icon is not there. 
- [x] If it's a quick fix then let's make the header row bottom border span over the entire legend, not only the part there the calculations are.

**Review by dprokop — COMMENTED** [review]
Looks great @zoltanbedi . I found one UI issue. When you sort the series in the Bar chart the values rendered on top of the stacked bars remain unchanged regardless the sort order:

https://user-images.githubusercontent.com/2376619/137934962-295edcf9-4a87-4f2f-90df-ad1e9a3349b4.mov

Other than that all seems to work 👍

**Review by dprokop — APPROVED** [review]
🔥

**Review by osg-grafana — APPROVED** [review]

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

**Comment by contentfree** [comment]
I arrived here while looking for the answer to "How to sort the order of items in the legend" – this PR doesn't seem to actually accomplish that (from this newb's perspective) but instead answers the question "How to sort additional calculated values related to items in the legend?".

Is that a true interpretation? How does one sort the order of the legend items in List mode?

**Comment by dmgeurts** [comment]
> Is that a true interpretation? How does one sort the order of the legend items in List mode?

There are several options for ordering legend items.

1. Split them into separate queries and then sort those in your preferred order
2. Use the Organise Fields transformation (preferred)

There may be other options, but I find #2 most versatile

**Comment by contentfree** [comment]
@dmgeurts Organize Fields doesn't work with a time-series. It complains that "Organize fields only works with a single frame. Consider applying a join transformation or filtering the input first."

**Comment by dmgeurts** [comment]
> @dmgeurts Organize Fields doesn't work with a time-series. It complains that "Organize fields only works with a single frame. Consider applying a join transformation or filtering the input first."

That's down to your data source, use merge or change your data query to get all your data in a single frame.

**Comment by contentfree** [comment]
But yeah, this does seem like a shortcoming of Prometheus. We're investigating swapping it out with VictoriaMetrics.

**Comment by ltning** [comment]
Why do values have to be shown in the legend (I don't want to waste the space!) in order to sort the legend? Old Graph visualization was var superior in this regard.

**Comment by euanmacinnes** [comment]
The alphabetical (or some other form of label sort) seems to still not be present as of 8.4. I can sort the query to return the results in the desired order, but Grafana's changing this order to something indeterminite...

**Comment by frittentheke** [comment]
> The alphabetical (or some other form of label sort) seems to still not be present as of 8.4. 
@euanmacinnes  see https://github.com/grafana/grafana/issues/82569

**Pull request merged**
