### PR TITLE
Show Grafana version and build in Help menu

### PR DESCRIPTION
**Pull request by davkal**
* establishes Help as the single place to look for the Grafana version
* version is passed as menu sub-title to side menu
* added rendering of sub-title, plus styles
* sub-title was used by profile menu (its value is the login string),
but was not shown; now showing this value on condition that login name
is different from user name

screen shot 2018-04-16 at 13 43 05

### CODE REVIEW

**Comment by torkelo** [comment]
nice! I think it makes more sense to have this above the help links. It would be more consistent with the profile menu which has this divider above. 

image

It would be nice if it could fit on one line and not wrap, for example:
image but not that important.

**Comment by davkal** [comment]
Moved version to top:

screen shot 2018-04-16 at 16 24 07

**Comment by torkelo** [comment]
nice!

**Review by Ijin08 — APPROVED** [review]
Looks good!

**Pull request merged**
