### PR TITLE
A11y: Fix the accessibility of FileUpload component

### LINKED ISSUE #46501: A11y : Cannot use FileUpload component via keyboard
**Steps to reproduce**:

[FileUpload component](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/FileUpload/FileUpload.tsx#L45-L56): Try to click "Upload JSON file" button inside import modal

**Actual Result**:

not accesible via keyboard

**Expected Result**

workflow accessible for keyboard-only users

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What this PR does / why we need it**:

The `FileUpload` is not currently accessible by keyboard as it was just a `label` pretending to be a `Button`, so I have replaced the content of that label with a `Button` that can be tabbed into.

Image comparing what the `FileUpload` in storybook looked like before and after the changes:
Screenshot 2022-03-09 at 14 40 15

**Which issue(s) this PR fixes**:

Fixes one of the issues on the list of A11y hackathon issues:
https://docs.google.com/spreadsheets/d/1e3sjrB3wjgQfttK5ANNkac5wmDwLszhgW0fO1kWT2LI/edit#gid=0

**Special notes for your reviewer**:

For the `Button` to work with the `input` it needs to "redirect" its own click to a click on the hidden `input`, hence why we need the `ref`.

### CODE REVIEW

**Review by zuchka — COMMENTED** [review]
tested and it works like a charm. Nice!

I don't know what impact these changes might have on compatibility, so another reviewer should approve ❤️

**Review by Elfo404 — CHANGES_REQUESTED** [review]
while this fix keyboard usage i don't think it improves accessibility as labels may only contain one input element. in this case we have 2 (the file input itself and the button). in this case there's no way to tell which input the label is labelling.

**Comment by JoaoSilvaGrafana** [comment]
> while this fix keyboard usage i don't think it improves accessibility as labels may only contain one input element. in this case we have 2 (the file input itself and the button). in this case there's no way to tell which input the label is labelling.

This is a good point, I actually don't think the `label` is necessary here, since the button has its own content now as a label and the `input` is hidden anyway. wdyt @Elfo404 ? I have tested it with a screen reader and that reads in a similar way to a native HTML file input.

**Comment by tolzhabayev** [comment]
@JoaoSilvaGrafana https://github.com/grafana/grafana/pull/47497 I am fine with whatever version we decide to go with. I think user-essentials team can pick one :) I did not know you are working on this, sorry for the collision.

**Comment by JoaoSilvaGrafana** [comment]
> @JoaoSilvaGrafana #47497 I am fine with whatever version we decide to go with. I think user-essentials team can pick one :) I did not know you are working on this, sorry for the collision.

Hadn't worked on it since the hackathon so no worries :) I think we can go with your version, it maintains the use of the input/label so should be a safer replacement, I'll close this one and approve yours!

**Pull request closed without merging**
