### PR TITLE
Implement datasource proxy throttling

### PR DESCRIPTION
**Pull request by sylr**
Implement throttling for datasource proxying.

### CODE REVIEW

**Comment by sylr** [comment]
cc @bergquist

**Comment by sylr** [comment]
@bergquist What do you think ? How do you like the approach ?

**Comment by bergquist** [comment]
This is a good idea. But I want more features to be included so I think it might be a good time to look for other solutions. I'd like to include timeout, retries, and backoffs as well. Something like https://github.com/Netflix/Hystrix

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana but I'm closing this PR since I would like a more complete solution for this problem. If you want to solve that It would be very appreciated.

**Pull request closed without merging**
