### PR TITLE
ColorPickerInput: Enable input clearing

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
 - Enable clearing the input in `ColorPickerInput`, in which case it will send an empty string to its `onChange` callback. 
 - Add tests for the component

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
This looks good, great job adding the tests! 🎉 

I don't know if this is something that you already had in mind to sort in a different PR, but I have tested this using the `SpectrumPalette` story as well and there is a weird behaviour where when you clear the input, it always sets it to "rgb(128, 128, 128)" which is a regression from before where it would leave the previously selected color. Do we want to fix that before merging this?

**Comment by Clarity-89** [comment]
> I don't know if this is something that you already had in mind to sort in a different PR, but I have tested this using the `SpectrumPalette` story as well and there is a weird behaviour where when you clear the input, it always sets it to "rgb(128, 128, 128)" which is a regression from before where it would leave the previously selected color. Do we want to fix that before merging this?

That seems like an intended behavior for that component, or at least that's how has it always worked. I don't really have any context about its usages to decide if the change in that behavior is necessary there, but I thought there might be a reason for it being non-clearable and nobody has raised an issue for that so far.

**Comment by JoaoSilvaGrafana** [comment]
> That seems like an intended behavior for that component, or at least that's how has it always worked. I don't really have any context about its usages to decide if the change in that behavior is necessary there, but I thought there might be a reason for it being non-clearable and nobody has raised an issue for that so far.

But before it used to keep to the color that was selected before while now it has a strange behavior because it tries to clear it:

Before:

https://user-images.githubusercontent.com/100691367/184165383-9635d125-6af0-4a4f-80c8-aa80b6ee248c.mov

After:

https://user-images.githubusercontent.com/100691367/184165412-503dc3fa-8eb9-46c3-a72e-582336edeeb6.mov

If we don't want to go into the `SpectrumPalette` to try to solve it maybe we can introduce a prop into the `ColorInput` `isClearable` and set it to `false` by default?

**Comment by Clarity-89** [comment]
> But before it used to keep to the color that was selected before while now it has a strange behavior because it tries to clear it:

Ah ok, missed that, good catch! I'll look into that.

**Review by axelavargas — APPROVED** [review]
👏🏾 great job @Clarity-89 , code looks good to me 🚀 ( really cool unit tests)

**Review by JoaoSilvaGrafana — APPROVED** [review]
👏 looks good!

**Pull request merged**
