### PR TITLE
Chore: Group auth docker blocks

### PR DESCRIPTION
**Pull request by linoman**
**What this PR does / why we need it**:

This PR will group all Docker images that fall under the Authorization/Authentication scope.

**Special notes for your reviewer**:

Provide feedback on the README file for the parent folder.

Pending work:
- Rework all `notes.md` to `README.md` for each docker block
- ~Change ownership of `auth/` to AuthNZ team~

### CODE REVIEW

**Review by IevaVasiljeva — APPROVED** [review]
Looks good!

Some suggestions and questions:
* I think we can also move JWT proxy and SAML under auth folder (and maybe also Apache proxy);
* are [these notes](https://github.com/grafana/grafana/tree/d993438c50782164c62213c1b5a4b809ae21fc17/devenv#docker-compose-with-databases) still up to date after these changes?
* we could maybe add ourselves as [code owners](https://github.com/grafana/grafana/blob/main/.github/CODEOWNERS) for these devenvs? I wonder what the rest of the team thinks about that.

**Comment by linoman** [comment]
@IevaVasiljeva you are totally right. I missed the JWT proxy and SAML environments. I'll take a look at the Apache env too.

> are [these notes](https://github.com/grafana/grafana/tree/d993438c50782164c62213c1b5a4b809ae21fc17/devenv#docker-compose-with-databases) still up to date after these changes?
Good catch! I'll update them.

> we could maybe add ourselves as [code owners](https://github.com/grafana/grafana/blob/main/.github/CODEOWNERS)
Big yes! We discussed changing the ownership during the tech debt meeting and I'll include this.

**Comment by linoman** [comment]
@IevaVasiljeva I've updated the PR with your suggestions. Thank you for the feedback.

I've moved not only the `apache_proxy`'s blocks but also the `nginx`'s and `prometheus_basic_auth_proxy` since they're been used for logging in users.

I updated the code ownership as suggested.

**Comment by IevaVasiljeva** [comment]
> @IevaVasiljeva I've updated the PR with your suggestions. Thank you for the feedback.
> 
> I've moved not only the `apache_proxy`'s blocks but also the `nginx`'s and `prometheus_basic_auth_proxy` since they're been used for logging in users.
> 
> I updated the code ownership as suggested.

Nice! All looks good to me now 🚢

**Pull request merged**
