### PR TITLE
Graphite: Change font-family for query editor to monospace

### LINKED ISSUE #15414: monospaced font for metrics query edition
Please include this information:

### What datasource are you using?
graphite

### If related to metric query / data viz:
on the metric query tab, it would be nice to have a monospaced font.
current:
grafana-current

nice to have:
grafana-mono

### PR DESCRIPTION
**Pull request by olbo98**
**What this PR does / why we need it**:
This PR changes the font-family for the query editor for Graphite to monospace.

**Which issue(s) this PR fixes**:

Fixes #15414

**Special notes for your reviewer**:
I added the style change as an inline style attribute. Since the code is going to be converted from angular to react i thought this solution would make it easier for the people doing the rework.

### CODE REVIEW

**Comment by olbo98** [comment]
@grafana/observability-squad It would be awesome if you could take a look at this and give me your feedback!

**Review by ifrost — APPROVED** [review]
LGTM 👍

**Review by ivanahuckova — APPROVED** [review]
Great first PR! 🎉  🎉  🎉  LGTM!

**Comment by jouve** [comment]
awesome !

**Pull request merged**
