### PR TITLE
Table Panel: Text wrapping fix inspect viewing issues

### PR DESCRIPTION
**Pull request by codeincarnate**
This PR fixes an issue that came up with #83642 in which values aren't wrapping correctly when `Inspect Cell` is enabled.

It also simplifies the styling logic as undefined values for colors are acceptable and can be used when calling `buildCellContainerStyle`

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
Looks like the bug with inspect is fixed now, but the functionality of default overflow on hover has changed from overflowing horizontally to vertically.
Ops/main:
image
This branch:
image
image

**Comment by codeincarnate** [comment]
@gtk-grafana I believe I have it all working now if you could take a look 😄

**Review by gtk-grafana — APPROVED** [review]
🤦  after taking a look at the original PR I see that 140 chars is the cutoff for wrapping down vs over, which appears to be what I am experiencing.
As this is fixing a bug I approve this PR, but this feature feels like a bug to me when the behavior is inconsistent within the column/field, getting different hover behavior on every other line is frustrating.

**Comment by codeincarnate** [comment]
@gtk-grafana yep, that's correct 😄. The idea behind the PR was to improve readability in circumstances like this, so at least in this case that would be the intended behavior. Would love to have your feedback and there's more discussion here #82872

**Pull request merged**
