### PR TITLE
Tempo: Normalize static filter queries

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Static filter does not render properly is tag is not defined.

**Why do we need this feature?**

So we only render static filters when a tag is defined for the filter.

**Who is this feature for?**

Tempo users.

**Special notes for your reviewer:**

Before

Screenshot 2023-08-03 at 08 43 10

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by aocenas** [comment]
I wonder, this seems like a problem with sort of malformed query right? Should we instead just normalize and save the query instead of just hiding the bad filter? Like if this sort of thing is happening we will leave the queries saved for example in dashboards in a weird state just hiding it from the user.

**Review by fabrizio-grafana — APPROVED** [review]

**Comment by joey-grafana** [comment]
> Should we instead just normalize and save the query instead of just hiding the bad filter?

So in this case; 
- if it has a scope of span but no tag, normalize to use the name tag
- if it has a scope of resource but no tag, normalize to use the service.name tag
- if it has a scope of unscoped but no tag, normalize to use the name tag (or perhaps better don't even all unscoped to be selected)

**Review by adrapereira — CHANGES_REQUESTED** [review]
This looks to be an issue on the configuration side, we shouldn't allow users to save static filter configurations without a tag, however we can't force this behaviour for provisioned data sources. 
I think that normalising and setting the tag to a default value is not the best option since we're changing what the user configured for the data source.

I propose we stylise the filter differently when it's invalid in some way, for example change the border/background to a red tone and add a ⚠️ icon next to it with a description of the error as a tooltip. This way users know that this filter is misconfigured and can work to fix it.

**Comment by joey-grafana** [comment]
> This looks to be an issue on the configuration side, we shouldn't allow users to save static filter configurations without a tag, however we can't force this behaviour for provisioned data sources. I think that normalising and setting the tag to a default value is not the best option since we're changing what the user configured for the data source.
> 
> I propose we stylise the filter differently when it's invalid in some way, for example change the border/background to a red tone and add a ⚠️ icon next to it with a description of the error as a tooltip. This way users know that this filter is misconfigured and can work to fix it.

I added a warning is the same location we show an error if we cannot retrieve tags. I wouldn't be a big fan of showing a red line around the select while showing an orange warning below it - feels like a contradiction.

**Review by adrapereira — APPROVED** [review]

**Pull request merged**
