### PR TITLE
Fixes: #28015 Updated relref link to Anonymous authentication section in grafana/la…

### LINKED ISSUE #28015: Broken link to anonymous authentication
The following anchor point doesn't exist:
https://grafana.com/docs/grafana/latest/auth/#anonymous-authentication

It's being used here:
https://grafana.com/docs/grafana/latest/administration/configuration/#authanonymous

Should likely refer to:
https://grafana.com/docs/grafana/latest/auth/grafana/#anonymous-authentication

### PR DESCRIPTION
**Pull request by achatterjee-grafana**
Fixed broken relref, as reported by Marcus. The issue reported by Marcus is Fixes: #28015

### CODE REVIEW

**Comment by oddlittlebird** [comment]
Please add the following from the PR template to the description of this PR:

Fixes: #28015

^ That will both add a notification in [28015](https://github.com/grafana/grafana/issues/28015) that a PR mentions it and will close the issue when this PR is merged.

**Comment by oddlittlebird** [comment]
Also, if you take a look at 28015 now, you'll see a notification that I mentioned it. Not sure if the comment is enough to trigger the closing...but it's a good idea to put that Fixes bit in the description when you're addressing issues anyway.

**Review by oddlittlebird — CHANGES_REQUESTED** [review]
Please update the description to add the Fixes text.

**Review by achatterjee-grafana — COMMENTED** [review]
Made the change to the title @oddlittlebird

**Review by oddlittlebird — APPROVED** [review]
I updated the formatting in the description. GitHub actually needs the "Fixes: #PRnumber" text exactly like that in order to close the issue when this PR is closed.

**Pull request merged**
