### PR TITLE
Expressions: Move GEL into core as expressions

### LINKED ISSUE #28993: Move Server-Side Expressions (GEL) into Grafana
Take https://github.com/grafana/gel-app/, and move into Grafana, renaming to expressions. (The frontend piece of this is already in core grafana).

Because:
 - Flow with alerting makes more sense (instead of stuff flowing from grafana, to expression plugin, back to gel)
 - Should be easier to iterate on if in core, in particular with any context we want to carry through to alerting. 
 - Don't have to worry about signing + embed plugin for it (other than cleanup)

TODO:
 - [x] Decide where the code lives and rename from gel to expressions 
 - [x] Replace Transform endpoints with calls to expressions

Cleanup TODO:
 - [ ] Remove embedded plugin 
 - [ ] Cleanup gel-app repo
 - [ ] cleanup builds for embedded plugin

Note: Not sure if there is anything I need to think about when cleaning up old GEL that might break backport / older builds which may delay changing the buildings are archiving the repo.

### PR DESCRIPTION
**Pull request by kylebrandt**
**What this PR does / why we need it**:
Take https://github.com/grafana/gel-app/, and move into Grafana, renaming to expressions. (The frontend piece of this is already in core grafana).

**Which issue(s) this PR fixes**:

Fixes #28993

**Special notes for your reviewer**:

 - [x] ~Still needs plugins-bundled figured out~ (Update: removed the entry from external.json)
 - The transform plugin pieces have been removed (removing from SDK would be follow up I think https://github.com/grafana/grafana-plugin-sdk-go/issues/237)
 - This should still be behind the feature flag (so review request is really for all the stuff outside expr)
 - If you have the gel plugin in your plugins dir, Grafana will not start, so maybe we should add removal of the Transform endpoint just in case someone discovered it.
 - Package structure: I do not like the way things are falling under `expr/`. To much stuff is going to end up in mathexpr (e.g. the types for series etc, resample, reduce). This can be for a follow up PR. The correct layout is not apparent to me at the moment. Although Node being an interface (set of methods) probably allows for some flexibility here.

### CODE REVIEW

**Review by papagian — COMMENTED** [review]
I found some references to the `transform` plugin type that I think they are obsolete:

https://github.com/grafana/grafana/blob/1024e652e85a61f8de2de4a2c5f028a36f02ba2b/pkg/plugins/plugins.go#L358-L366

https://github.com/grafana/grafana/blob/1024e652e85a61f8de2de4a2c5f028a36f02ba2b/pkg/plugins/plugins.go#L376-L379

Note also that if `ngalert` is enabled but `expressions` are disabled then one can still evaluate an alert definition using the API.
If we decide that we don't want this we can disabling `ngalert` if `expressions` are disabled [here](https://github.com/grafana/grafana/blob/43f580c299d7ed237ec79c19a205139fbff9c066/pkg/services/ngalert/ngalert.go#L44).

**Review by aknuds1 — APPROVED** [review]
That's a whole lotta code! Just skimmed it since most of it is just moving code into pkg/expr.

**Review by marefr — APPROVED** [review]
LGTM great :+1: 

Moving forward when expression are a core thing maybe could make sense to remove the hack with data source id -100. I don't have all the details and it's maybe hard, but worth to consider. I guess we had this earlier to be able to send the data GEL needed in the data query request. Now you can change the Grafana HTTP API request model to whatever GEL needs, Maybe having a specific HTTP API for expressions would make sense as well in case we would like request metrics specifically for that endpoint and so on.

**Review by papagian — APPROVED** [review]

**Comment by Gauravshah** [comment]
this removes the ability of external plugins to be able to do similar things.  we are looking to add backend support for https://github.com/GoshPosh/grafana-meta-queries.
Had raised an issue as well earlier
https://github.com/grafana/grafana/issues/15696

**Pull request merged**
