### PR TITLE
DatasourcePlugin: Adds per-mode StartPage components

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Adds per-mode StartPage components, `ExploreLogsStartPage` and `ExploreMetricsStartPage`, and corresponding setters `setExploreLogsStartPage` and `setExploreMetricsStartPage`, for data sources that might require different "Cheat sheets" depending on the query mode (e.g. CloudWatch).

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Comment by aocenas** [comment]
@kaydelaney how will this tie into the logs/metric unification work? It seems like that just won't work anymore and we will have to figure out something else anyway afterwards.

**Comment by kaydelaney** [comment]
@aocenas You're right, but I really just want it as a temporary measure for Cloudwatch Logs

**Comment by aocenas** [comment]
And what about inverting it so that we add `getStartPage(context: { page: 'explore', mode: ExploreMode, queryEditor: Editor})` kind of thing on datasource? Because one issue I see here is that in Metrics > Logs API this won't works. We basically need to know also the state of the editor itself to know what start page to show in this case.

**Comment by aocenas** [comment]
Or maybe that could be a method on QueryEditor that way we don't need to pass the queryEditor instance into datasource. Not sure if that will make for easier API and typing but conceptually start page feels like concern for query editor itself as you may won't different help if you use some sort of raw editor, visual editor or which api you want to communicate with.

**Comment by kaydelaney** [comment]
@aocenas I agree with what you're saying, but maybe something for a different PR?

**Comment by aocenas** [comment]
@kaydelaney well will this fix the issue? Because what I am saying is that I think we will still have an issue when we have Metrics > Logs API and we won't be able to solve that with this approach anyway so we will have to rethink this and rework the coda afterwards. If I am wrong than cool but if I am not I would rather not rush this. Not ideal but I think we can add it later in the beta.

**Pull request closed without merging**
