### PR TITLE
Pausing/un alerts now updates new_state_date

### PR DESCRIPTION
**Pull request by xlson**

### CODE REVIEW

**Review by bergquist — APPROVED** [review]
Looks good. Do you want to merge this into 5.0 or after we branch of 5.0?

**Comment by xlson** [comment]
@bergquist doesn't really matter to me. Perhaps we'd better just wait. Doesn't feel like its super important.

**Comment by torkelo** [comment]
Since paused is a state, is this not correct? Is there an issue describing the problem with updating new_state_date?

**Comment by bergquist** [comment]
@torkelo not sure I understand. The problem was that `new_state_date` wasn't updated. 
https://github.com/grafana/grafana/issues/10191 kinda weak issue. 

It was raised by a user on IRC who thought it was weird that nwe_date_date wasn't updated when an alert was paused/unpaused.

**Comment by torkelo** [comment]
Ah, sorry, read the PR title wrong :)

**Pull request merged**
