### PR TITLE
Added feature request "predict value" in moving averages pipeline agg

### PR DESCRIPTION
**Pull request by vaibhavinbayarea**
issue-id: #5688 

Compilation / Grunt results:

```
root@ip-172-31-4-169:~/src/github.com/grafana/grafana# grunt test
Version 4.0.0-pre1
Running "jscs:src" (jscs) task
>> 99 files without code style errors.

Running "jshint:source" (jshint) task

✔ No problems


Running "jshint:tests" (jshint) task

✔ No problems


Running "tslint:source" (tslint) task
>> 150 files lint free.

Running "clean:gen" (clean) task
>> 1 path cleaned.

Running "copy:node_modules" (copy) task
Created 92 directories, copied 1429 files

Running "copy:public_to_gen" (copy) task
Created 263 directories, copied 2215 files

Running "phantomjs" task
Phantomjs already imported from node

Running "sass:src" (sass) task

Running "concat:cssDark" (concat) task
File public_gen/css/grafana.dark.min.css created.

Running "concat:cssLight" (concat) task
File public_gen/css/grafana.light.min.css created.

Running "concat:cssFonts" (concat) task
File public_gen/css/fonts.min.css created.

Running "styleguide" task

Running "sasslint:target" (sasslint) task

Running "postcss:dist" (postcss) task
>> 6 processed stylesheets created.
>> 6 sourcemaps created.

Running "typescript:build" (typescript) task
471 files created. js: 157 files, map: 157 files, declaration: 157 files (7700ms)

Running "karma:test" (karma) task
29 07 2016 21:27:55.678:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
29 07 2016 21:27:55.684:INFO [launcher]: Starting browser PhantomJS
29 07 2016 21:27:56.486:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#MnX9MmBSrWBvQtS9AAAA with id 97937473
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
..............
PhantomJS 2.1.1 (Linux 0.0.0): Executed 894 of 896 (skipped 2) SUCCESS (1.996 secs / 0.545 secs)

Running "no-only-tests" task

Done, without errors.
```

Result:
screen shot 2016-07-29 at 12 06 26 pm

### CODE REVIEW

**Comment by vaibhavinbayarea** [comment]
Hmm.. I have signed the CLA, it redirects back to this page.. Yet I'm getting a message not signed! Does anyone know whats happening?

**Comment by VJean** [comment]
Hi ! Any news about this PR ?
Prediction would be nice. (Being able to set the settings field would be even nicer : alpha, beta, gamma parameters depending on the selected model )

Also, you might want to check that the email adress you are using in your commits is linked to your Github account.

**Comment by vaibhavinbayarea** [comment]
Thanks! Its probably that. 

Since last posting this PR, I have added alpha, gamma, beta etc based on algorithm selected. I need to create unit tests and probably rebase with top of the tree. Will try to get it done by EOW.

**Comment by vaibhavinbayarea** [comment]
@VJean PR with settings field has been filed https://github.com/grafana/grafana/pull/7154

**Pull request merged**
