### PR TITLE
Docs: Add plugin publishing and signing criteria

### PR DESCRIPTION
**Pull request by marcusolsson**
**What this PR does / why we need it**:

Adds documentation that lists the requirements and criteria for publishing a plugin to Grafana.com to improve the chances of a plugin submission being approved and published.

### CODE REVIEW

**Review by GrafanaWriter — COMMENTED** [review]
Minor nits on the content :).

One q - and perhaps we have this captured elsewhere - do we want to add a section that covers what we require for documentation? Perhaps explain that each plugin requires:
- Overview
- Installation
- changelog

**Comment by marcusolsson** [comment]
@GrafanaWriter I think your suggestions make sense to add to this document, though would it be ok to merge this as for now and add those in at a follow-up PR?

**Review by mckn — APPROVED** [review]
LGTM

**Comment by mckn** [comment]
Closed/reopen to trigger new CI build

**Comment by leventebalogh** [comment]
Do you need any help with this @marcusolsson?

I think the Prettier check is breaking because of [this line](https://github.com/grafana/grafana/pull/40154/files#diff-f69a8ae8fdad9aebb0baff7a4b6cd7551f42b90f8318fc911927736b2534b427R25):
```markdown
- Usage of 3rd party software or dependencies within the plugin must be licensed for the intended use. For example, using open source dependencies must be credited/licensed; embedding logos or trademarks;
```

**Comment by marcusolsson** [comment]
The PR is ready, but I've been having issue with failing tests seemingly unrelated to the changes:

```
FAIL	github.com/grafana/grafana/pkg/tests/api/alerting	158.120s
```

I've been re-running this without success. I'd love help on figuring out why 🙏

**Comment by tolzhabayev** [comment]
@marcusolsson I've just merged `main` into this branch, hopefully it will resolve the build

**Pull request merged**
