### PR TITLE
API: Include IP address when logging request error

### LINKED ISSUE #21310: Log “Invalid username or password” plus IP of the request (Allow detection of attacks with fail2ban)
**What would you like to be added**:

I would like to be added in the logs of Grafana the IP of the request within the line who say “Invalid username or password”

Grafana is logging failed attemps of logins but do not write the IP of the request

**Why is this needed**:

I think it could help to improve the security.

Some people have Fail2Ban protecting services, and Grafana can not be protected because Fail2Ban can read that has been an failed trying of login but not the IP.

Here is an example of the log of Grafana:
```
t=2019-10-15T09:11:04+0200 lvl=info msg=“Request Completed” logger=context userId=2 orgId=1 uname=user1 method=GET path=/api/datasources/proxy/1/query status=400 remote_addr=190.720.751.765 time_ms=20 size=77 referer=“https://myserver .com/graf/d/jOI1Ku7Wk/principal-fv?orgId=1&refresh=30s&fullscreen&edit&panelId=40”

t=2019-10-15T15:58:19+0200 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=GET path=/d/jOI1Ku7Wk/principal-fv status=302 remote_addr=190.720.751.765 time_ms=0 size=34 referer=

t=2019-10-15T15:58:43+0200 lvl=eror msg=“Invalid username or password” logger=context userId=0 orgId=0 uname= error=“Invalid Username or Password”
```

I would like that Grafana write: or something else
`t=2019-10-15T15:58:43+0200 lvl=eror msg=“Invalid username or password from 177.166.155.44” logger=context userId=0 orgId=0 uname= error=“Invalid Username or Password”`

I opened a post in the community of Grafana:
https://community.grafana.com/t/how-can-we-set-up-fail2ban-to-protect-our-dashboard/21962

@tkohhh

### PR DESCRIPTION
**Pull request by thedeveloperr**
**What this PR does / why we need it**:
This will provide additional security information on failed login
and also help integrate services like Fail2Ban to detect brute
force attacks.

**Which issue(s) this PR fixes**:

Fixes #21310

**Special notes for your reviewer**:
In my local dev setup, e2e tests were failing due to some phantomjs installation issue, I create this PR to run tests on circle ci to ensure my changes are not failing any tests. Also this log line didn't fail any backend test so didn't write my own test. Do you need me to write test for this change ?

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
@thedeveloperr thanks. Sorry it taken me long time to come back to this one. After consideration I've notice that our router logging middleware (when enabled) includes `remote_addr, <ip>` why I suggest to revert your change to middleware.go and in addition log IP address on error in common.go:
```diff
diff --git a/pkg/api/common.go b/pkg/api/common.go
index 0f81e30..7f87925 100644
--- a/pkg/api/common.go
+++ b/pkg/api/common.go
@@ -47,7 +47,7 @@ func Wrap(action interface{}) macaron.Handler {
 
 func (r *NormalResponse) WriteTo(ctx *m.ReqContext) {
        if r.err != nil {
-               ctx.Logger.Error(r.errMessage, "error", r.err)
+               ctx.Logger.Error(r.errMessage, "error", r.err, "remote_addr", ctx.RemoteAddr())
        }
 
        header := ctx.Resp.Header()
```

**Comment by thedeveloperr** [comment]
Shall I change in both places or just here ?

**Comment by thedeveloperr** [comment]
So remove changes from middleware.go but add here in common.go ?

**Comment by bergquist** [comment]
Yes, please :)

Eager to merge once its been fixed.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
