### PR TITLE
Alerting: Modify prometheus endpoints for proxying using the datasource UID

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
follow-up of #47829
This is part of work of removing the sequential IDs from the API and store layers. For more details you can refer to [this doc](https://docs.google.com/document/d/1LN55IDeLXQEPbuIJR2l02VM5I5GJLNpOlUQDfThDKe8/edit).

More specifically, it:
* modifies the prometheus endpoints so that expect a `DatasourceUID` path parameter
* updates authorisation actions for the modified endpoints

Example of a successful request to a known datasource UID:
```
curl -X 'GET' \
  'http://localhost:3000/api/prometheus/7DEsN5_Mk/api/v1/alerts' \
  -H 'accept: application/json' \
  -H 'authorization: Basic YWRtaW46YWRtaW4='
{"status":"success","data":{"alerts":[]}}
```

Example of requesting an unknown datasource UID:
```
curl -X 'GET' \
  'http://localhost:3000/api/prometheus/unknown/api/v1/alerts' \
  -H 'accept: application/json' \
  -H 'authorization: Basic YWRtaW46YWRtaW4='
{"error":"unexpected backend type (unknown)","message":"unexpected backend type (unknown)","traceID":"00000000000000000000000000000000"}
```

# Release notice breaking change

Grafana alerting endpoints prefixed with `api/prometheus/` that proxy requests to a Cortex/Loki data source now expect the data source UID as a path parameter instead of the data source numeric identifier.

### CODE REVIEW

**Review by yuri-tceretian — CHANGES_REQUESTED** [review]
please update the authz code with the suggested changes

**Review by joeblubaugh — CHANGES_REQUESTED** [review]
I want to finish the discussion we're having on #47978 about the structure of the path before this is merged.

**Review by gillesdemey — COMMENTED** [review]
The changes in `public/app/features/alerting/unified/api/prometheus.ts` look good but manual testing returns a `403` on the `/api/prometheus/{datasourceUID}` paths – this does not happen on `main` so either RBAC doesn't work correctly on this branch or a fix was pushed to `main` that is not included here.

@yuri-tceretian can you double check?

Screenshot 2022-05-03 at 10 54 51

**Comment by papagian** [comment]
@gillesdemey thank you for your review, good catch! I think I fixed the authorisation; can you check once again?

**Review by joeblubaugh — APPROVED** [review]
LGTM on the .go files.

**Review by gillesdemey — APPROVED** [review]
LGTM!

**Review by yuri-tceretian — APPROVED** [review]

**Comment by yuri-tceretian** [comment]
Sorry, I did not know it waited for my review :| I thought it was dismissed

**Pull request merged**
