### PR TITLE
Plugins: Use semver fallback check when fetching plugins from repo by version

### PR DESCRIPTION
**Pull request by wbrowne**
**Which issue(s) this PR fixes**:
#41996

### CODE REVIEW

**Comment by marefr** [comment]
Earlier dependencies has been installed using `latest` version I guess? I'm a little bit afraid this could open a can of worms :smile: Yeah, I see both pros and cons with this. For example, what if you have two plugins, one of them have a dependency of plugin A with version `>=1.x` and other one a dependency of plugin A with version `>=2.x` - who win?

**Comment by wbrowne** [comment]
>Earlier dependencies has been installed using latest version I guess

No, they don't get installed at all because the version field is not parsed at all so it results in a 404. 

>what if you have two plugins, one of them have a dependency of plugin A with version >=1.x and other one a dependency of plugin A with version >=2.x - who win?
We have the same issue right now even without semver 😅 

Yeah this is a bit of a strange one. We can be explicit and just deny this instead and maybe add it to the the linting process so no other plugins suffer from being published this way.

Looping in @marcusolsson in case you have some thoughts from your experience with seeing all the different shapes and sizes plugins come in

**Comment by marcusolsson** [comment]
This feels like a step towards implementing a proper package management system for plugins? If we officially start supporting this behavior, we may want to have an idea of how we want to solve auto-resolution of plugin versions beforehand. @sdboyer might have some valuable insights here.

**Comment by sdboyer** [comment]
Apologies for slow response!

i mean...phew. The possibilities, sorted from least to most painful, are:

* Don't allow plugins to depend on other plugins. (But if you must, then...)
* Allow multiple versions of plugins. (But if you can't, then...)
* Implement a proper version selection algorithm and . (But if you don't, then...)
* Default, accidental, implicit failure mode: half-ass a bunch of bits and bobs together that seem to solve the problem at small scale but have complex and unforseeable failure modes that will haunt us forever 👿

**Pull request closed without merging**
