### PR TITLE
Profiling: Enable flame graph & Phlare/Parca data sources for all users

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

This PR removes the flame graph feature toggle.

**Why do we need this feature?**

The toggle is no longer needed.

**Who is this feature for?**

Users of Phlare/Parca/Flame graph.

**Special notes for your reviewer**:

Also removes the beta badge from the flame graph panel in dashboards.

### CODE REVIEW

**Comment by joey-grafana** [comment]
I'd imagine it's ok that levitate is detecting a breaking change (as we're removing a feature toggle)

Screenshot 2023-02-21 at 14 23 27

**Comment by ifrost** [comment]
Out of curiosity, why is the flag being removed instead of rolling it out gradually to Cloud?

**Comment by ifrost** [comment]
This will be added to change og. Should it also be included in "what's new?" (there's a separate label for it). I think changing the title to something more meaningful for the changelog would be good.

**Review by ifrost — APPROVED** [review]
Explore changes LGTM 🎉 

I've noticed that suggested visualizations don't list Flame graph, it'd be nice to have it there:

Screenshot 2023-02-23 at 11 47 02

**Review by aocenas — APPROVED** [review]
Looks good

**Comment by L-M-K-B** [comment]
You might want to consider changing the headline of the PR as it's going to be added to the changelog. What about something like _Profiling: Enable flame graph for all users_ ?

**Review by chri2547 — APPROVED** [review]
Docs lgtm! Thank you for making these changes!

**Comment by joey-grafana** [comment]
Updated the PR title and added the `add to what's new` label :) 

Suggested visualizations is a nice tip, thanks. I've made a note to check that out.

**Pull request merged**
