### PR TITLE
Alerts not sent when state is changed from "initialized" to "ok"

### LINKED ISSUE #6415: No alert should be sent when alert evaluation goes from initial_state to ok
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Master build
- What datasource are you using? Graphite/OpenTSDB
- What OS are you running grafana on? Amazon Linux
- What did you do? Created an alert with high enough threshold to not send an alert.
- What was the expected result? Alert should not be sent as alert evaluation was "ok" when checked after "initial_state".
- What happened instead? Alert was sent.

### PR DESCRIPTION
**Pull request by utkarshcmu**
Resolves #6415

### CODE REVIEW

**Comment by bergquist** [comment]
Seems like a good idea but Im not sure about introducing another state for this. 
I guess this could be avoided when going from no_data to ok as well?

**Comment by utkarshcmu** [comment]
@bergquist I think we need the "initialization" state because it will solve two valid use cases:

1. No notification should be sent when state changes from "initialized" to "ok".
2. Notification should be sent when state changes from "initialized" to "no_data".

If we do not introduce the new "initialized" state, we can still solve the 1st use case by using "state_changes" column (when value changes from 0 to 1) but we won't be able to solve the 2nd use case.

Any thoughts?

**Comment by bergquist** [comment]
I don't think we should send notifications when setting state to no_data. If the user want to be notified about getting no_data its possible to configure 
image

Does this make sense?

**Comment by utkarshcmu** [comment]
Yes, that works too. So, there will be 4 values for alert_state (OK, Alerting, NoData, ExecError) but 3 values for which notifications will be sent out(OK, Alerting, ExecError). Is that correct?

Also, should we give the same option to set state to Alerting if there is ExecError? Hence in this case, there will still be 4 values for alert_state (OK, Alerting, NoData, ExecError) but only 2 values will be alerting (OK, Alerting). What do you think?
screen shot 2016-11-01 at 2 13 04 am

**Comment by torkelo** [comment]
> I don't think we should send notifications when setting state to no_data. If the user want to be notified about getting no_data its possible to configure 

I think this should be configured on the notification, I mean we send out no_data notifications today

**Comment by torkelo** [comment]
I do not like the Initialized state either, but maybe it's just the name I dont like (like Initial or Pending more). 

We also have the case where an alert can be paused (basically disabled), what should the rule be when going from paused -> ok ?

**Comment by utkarshcmu** [comment]
So, there can be two cases where no need to send notifications:

1. No_Data to OK (When alert is created.)
2. Paused to OK (When alert is un-paused.)

And all other state_changes should send notifications. How about this? If we agree I can make changes in this PR and resubmit.

**Comment by bergquist** [comment]
After some discussions with torkel narrowed this issue down to..
- Rename `Initialized` to `Pending`.
- Don't send notifications when changing state from `Pending` to `OK`
- Un pausing alert rules should set the rule state to `Pending`.

I will open a new issue/discussion for how to handle the no_data state.

**Comment by utkarshcmu** [comment]
Made the required changes suggested above. Please review/merge. Thanks!

**Comment by bergquist** [comment]
@utkarshcmu great!

**Pull request merged**
