### PR TITLE
PanelEdit: Places all variables below Toolbar

### PR DESCRIPTION
**Pull request by dessen-xu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

https://github.com/grafana/grafana/issues/32307

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — COMMENTED** [review]
@torkelo not sure about this one, what do you think?

**Comment by torkelo** [comment]
@hugohaggmark what does it look like? I actually had a plan to fix this as part of panel edit ux work. My plan was to put all variables in a big dropdown

**Comment by hugohaggmark** [comment]
just a sec

**Comment by hugohaggmark** [comment]
**Before**
image

**After**
image

**Comment by torkelo** [comment]
yea, that is not great.

**Comment by torkelo** [comment]
We will try to solve this a different way, hopefully in v8. Where if there are more than say 2 variables they get collapsed into a single dropdown and shown vertically in one popover

**Pull request closed without merging**
