### PR TITLE
Add fine-grained access control information to the features which now support it

### PR DESCRIPTION
**Pull request by vtorosyan**
**What this PR does / why we need it**:

PR adds notes and information about fine-grained access control to the features which now support fine-grained permissions. The following list of features now support new permissions:
- Configure access for viewing admin settings
- Configure access for updating admin settings via API
- Control access to LDAP configuration
- Configure access for Explore
- Configure access for reading admin stats

### CODE REVIEW

**Comment by sakjur** [comment]
I think this needs a backport tag for 8.1.x if this is for features added in 8.1.0

**Review by kalleep — APPROVED** [review]
LGTM! You need to add the backport label as @sakjur mentioned

**Comment by achatterjee-grafana** [comment]
The docs at `next` are still at 8.0, so the backport is not needed. The information will become GA when 8.1 is general and 8.1 docs are available in `latest`.

**Comment by sakjur** [comment]
Do the docs' latest tag build off of the main branch and not the versioned branch?

**Comment by achatterjee-grafana** [comment]
The main branch. Adding @robbymilo to keep me honest.

**Comment by vtorosyan** [comment]
I just asked in the [Slack](https://raintank-corp.slack.com/archives/C010WU9Q5TJ/p1627546910096800?thread_ts=1627546845.096500&cid=C010WU9Q5TJ) and it appears we do need to backport, since the 8.1.0-beta3 was branched from main.

**Pull request merged**
