### PR TITLE
Docs: fix 2 broken links on 'Publish a plugin' topic

### PR DESCRIPTION
**Pull request by josmperez**
**What is this feature?**

Fixes 2 broken links on 'Publish a plugin' topic.

**Why do we need this feature?**

Improve user experience.

**Who is this feature for?**

Plugin developers.

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]

**Comment by xnyo** [comment]
Suggestion as a a side note (not related to this PR), wouldn't it make more sense to have those two articles ("Publishing and signing criteria" and "Publish or update a plugin") under "Publish a plugin" as well, rather than having them under the main "Plugins" folder?

Current structure:
immagine


Proposed structure:
immagine

**Review by xnyo — APPROVED** [review]
LGTM!

**Comment by sympatheticmoose** [comment]
@xnyo agree its odd at the moment - the next phase of doc PRs will be restructuring. Actually looking at the content in the signing criteria page now, I'd rather move the license info into the policy page and probably delete that page entirely.

We've still got a link which 404s:
`WARN 2023/05/18 08:30:04 [en] REF_NOT_FOUND: Ref "plugin.json": "/hugo/content/docs/grafana/latest/developers/plugins/reference/_index.md:10:4": page not found` 
Screenshot 2023-05-18 at 09 33 13

Will take a look and push to this branch

**Review by sympatheticmoose — CHANGES_REQUESTED** [review]
Tested locally and this fixes the change. We've still got a broken link though as described in my earlier comment.

For simplicity I'd suggest just removing the recently introduced reference folder `/developers/plugins/reference` - its not actually used yet, so we can figure that out more in phase 2. (For example the reference link from here http://localhost:3002/docs/grafana/latest/developers/plugins/ just points directly to metadata.md)

Alternatively, we'd need to move the metadata file under /reference, check for other broken links and redirects etc - as well as figure out what we want to do with the plugin.schema.json file and metadata.md.tpl.

**Review by mckn — APPROVED** [review]
I agree with @xnyo, maybe something we can do in a follow up PR?

**Comment by josmperez** [comment]
@sympatheticmoose - I have deleted the References folder and page for now.

**Comment by josmperez** [comment]
Let's look at the publishing criteria doc during phase 2 and/or 3. Before deleting it in the Plugins docs, I would want to ask the question: Would it benefit plugin developers to summarize some of the key points here AND link to the full document? The potential problem with linking is that most users don't want to read long pages of legalese and may avoid it altogether.

**Review by sympatheticmoose — APPROVED** [review]

**Comment by josmperez** [comment]
PR is ready, merging has been requested.

**Pull request merged**
