### PR TITLE
add nested support to fieldname autocomplete; fixes #4526 Also:

### LINKED ISSUE #4526: [Feature Request] getFields() doesn't support nested mapping; fails if current date's index is absent
in the panel graph editor mode, while trying to select fields for example, under Metric 'Average', if an elasticsearch document is nested, then the autocomplete feature doesn't show up. 

Also, I've observed that on debugging, when the index name using a daily pattern, doesn't have "today's date" in it, getFields feature fails to run smooth, since  _mapping for the index to which my datasource belongs, is not present..

Would be nice to have this sorted out. 

--
* What grafana version are you using?
3.0.0 (latest from master branch)

* What datasource are you using?
elasticsearch

* What OS are you running grafana on?
fedora 23

### PR DESCRIPTION
**Pull request by arcolife**
This adds nested doc support to fieldname autocomplete feature in dashboard panel query editor; Previously it only used to show fields which had a 'type' only in the first hierarchial structure itself.
Also:
    - update _mapping to first use given time range
      for deducting index mapping, then fallback to
      today's date based index name

### CODE REVIEW

**Comment by arcolife** [comment]
@torkelo hey the current date feature is failing tests. I don't know why that is a necessity? when the issue revolves exactly around this feature, in addition to nested autocomplete.
```
PhantomJS 2.1.1 (Linux 0.0.0) ElasticDatasource When testing datasource with index pattern should translate index pattern to current day FAILED
```

**Comment by torkelo** [comment]
you need to update the unit tests, and add a few more tests for new logic

**Comment by arcolife** [comment]
@torkelo Working on the unit tests. Dealing with typescript and control flow here. Getting a hang of it. 

I'm also working on another PR to add nested type option in bucket aggregations. Will add a reference here, since this and that other PR are connected.

**Comment by arcolife** [comment]
closing this in favor of PR https://github.com/grafana/grafana/pull/4694 (which encompasses functionality added within this PR).

**Pull request closed without merging**
