### PR TITLE
Explore: Update tooltips for live tailing buttons

### LINKED ISSUE #21958: Logs Live tailing: Change button coloring, add tooltip
Change button coloring:
- border to lightest shade of orange (#FFB357) in light and dark theme
- font color to lightest shade of orange in dark theme (light theme can stay the same)
- The glow can stay the same.

Also add a tooltip on hover: "Live stream your logs."

Reason for this change is user feedback from public slack:

I didn't know what this 'live' button did so i pressed it and i know the button has a 'play' symbol but the amount of bright red that suddenly appeared startled me and had me worried i'd accidentally pressed a record button instead

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Updates text in tooltip. We have updated the color of border and text before. I have also updated text for tooltips for Pause and Stop buttons. 

image
image
image

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/21958

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]
LGTM!
I do think that this PR raises an interesting issue in that perhaps the `content` prop of the `Tooltip` component should support just passing strings so as to avoid users having to wrap everything in angle brackets.

**Comment by ivanahuckova** [comment]
> I do think that this PR raises an interesting issue in that perhaps the `content` prop of the `Tooltip` component should support just passing strings so as to avoid users having to wrap everything in angle brackets.

Yes, I totally agree! However, I am not sure if we have any more complex tooltips that would require component. 🤔

**Comment by jessover9000** [comment]
I would change the text for pause and stop as follows: "Pause the live stream" and "Stop and exit the live stream". Then I think it's good :)

**Comment by ivanahuckova** [comment]
@jessover9000 updated in https://github.com/grafana/grafana/pull/26799/files

**Pull request merged**
