### PR TITLE
Alerting: Store sensitive settings encrypted for alertmanager notifier

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
Store basic auth user/password in secure setting.

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/25967

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thanks. Looks good. Suggests we encrypt basic auth password, but not basic auth username. In #26170 we decided to skip encrypting username because we don't do that for data sources and in addition could be hard for users to understand what account is used when not seeing the username.

**Comment by mtanda** [comment]
I revert basicAuthUser change. Please check :-)

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
