### PR TITLE
Explore: return to grid layout for logs table

### LINKED ISSUE #14288: Explore: Logging columns are hard to distinguish on big screens
Wall of text as reported by @torkelo 

image

### PR DESCRIPTION
**Pull request by davkal**
- better column control than flexbox
- increased gutter and row spacing

Fixes #14288

### CODE REVIEW

**Comment by davkal** [comment]
Before:
image

After:
screenshot 2018-12-04 at 10 49 18

**Comment by torkelo** [comment]
looks ok as an interim solution. But really think we should move to react-virtualized, and built a generic & reusable grid component, For logs, it should probably not scroll (or have a very high max height). But the cell measurement stuff could be really useful to format the table and adapt it to dynamic width & height of content. 

https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer

**Comment by davkal** [comment]
Not sure I follow. What property or behavior is missing for which react-virtualized would provide a solution?

**Comment by torkelo** [comment]
Not sure actually :) when we need toggles to expand / collapse, for large stack traces etc & dealing with large ES log events. Fixed table headers etc.

**Pull request merged**
