### PR TITLE
SingleTopNav: Flip collapse arrows for better alignment

### LINKED ISSUE #94080: Unified AppChrome bar: Adjust megamenu arrow/icon positions for better alignment

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- flips the megamenu arrows to the end so there's better alignment with other header elements
- also changes the arrows to be up/down instead of right/down

| before | after |
| --- | --- |
| image | image |

**Why do we need this feature?**

- better alignment

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/94080

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by tskarhed** [comment]
How well does this work with bookmarking?

**Comment by ashharrison90** [comment]
same as always i think

https://github.com/user-attachments/assets/f2afe0cd-a536-42b3-b01b-ae99166c451e

**Review by L-M-K-B — APPROVED** [review]
Funny that we are moving these arrows back after a year but I agree that the alignment is a lot better now. 😅

**Pull request merged**
