### PR TITLE
Update target folder for docs

### PR DESCRIPTION
**Pull request by achatterjee-grafana**
Issue: fixed incorrect target folder path. For reference, see: https://raintank-corp.slack.com/archives/CH34H23HD/p1650896131488619

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
I believe this PR to be correct but I'm unsure why this change was not already made as part of the release steps.

**Comment by achatterjee-grafana** [comment]
Can someone approve the PR? 
Right now, the changes in next are not showing up in the latest, and that is a change, especially for the What's New 8.5 topic.

**Review by gillesdemey — APPROVED** [review]
LGTM 📖

**Comment by achatterjee-grafana** [comment]
Question: Will the changes from next show up in `latest` when we merge this PR? Do we need to do anything else? TY

**Pull request merged**
