### PR TITLE
CloudWatch: Fix display name of metric and namespace

### LINKED ISSUE #54727: CloudWatch Metrics does not display Metric Namespace/Values in Explore Mode
**What happened**: I created a dashboard for CloudWatch data source. Inside the dashboard, I created a panel which referred to a metric from custom namespace. The panel displays the metric value correctly - however when I go to Explore mode or Edit mode, the metric namespace and name are empty. 

**What you expected to happen**: Expected the Explore and Edit mode to show the correct namespace and metric name. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Run Grafana locally, and configure the CloudWatch datasource. 
2. Create a dashboard, and a panel which displays a metric from custom namespace. 
3. Save the dashboard.
4. Click on the panel and go to `Edit`. Observe that the metric is correctly displayed but the Namespace field is empty. 
5. Click on the panel and go to `Explore`. Observe that the metric namespace and metric name is completely empty.   

**Environment**: OS Linux/Firefox 
- Grafana version: 8.4.7
- Data source type & version: CW Logs (Core plugin)
- OS Grafana is installed on: Linux
- User OS & Browser: Linux Ubuntu/Firefox
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:
This PR ensures that metric name and namespace is displayed in the UI. Before this fix, they would not be displayed correctly in case their values wasn't in the list of options. This is circumvented by passing the selectable value object as value to the `Select` component instead of passing just the string value.

**Which issue(s) this PR fixes**:

Fixes #54727

**Special notes for your reviewer**:
This issue was found in AMG, version 8.4.7 so I might need to be backported to 8.4.x. Will investigate this and report back here.

### CODE REVIEW

**Review by fridgepoet — APPROVED** [review]
Is it possible to add a test?

**Comment by sunker** [comment]
> Is it possible to add a test?

Done!

**Review by fridgepoet — APPROVED** [review]

**Review by iwysiu — APPROVED** [review]

**Comment by rondutt** [comment]
Hey @sunker , was this ever backported to Grafana 8.5? We have an AMG customer (slack) running into this issue, and they're unable to update to Grafana 9 right now.

**Comment by sunker** [comment]
@rondutt at this point, we only backport security issues to 8.x.

**Pull request merged**
