### PR TITLE
Access control: Roles and permissions for access control endpoints

### PR DESCRIPTION
**Pull request by vtorosyan**
**What this PR does / why we need it**:
The PR introduces new permissions and scope for applying to the access control endpoints. For more information please see the [enterprise PR](https://github.com/grafana/grafana-enterprise/pull/1292)

The new permissions are bundled together under new predefined roles, which are only attached to the Grafana Admin now.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise/issues/1274

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sakjur** [comment]
I think it'd be better to define these in Grafana Enterprise, since they don't serve a purpose for open source Grafana.

**Comment by vtorosyan** [comment]
@sakjur That sounds good to me and was also my initial though. There was probably a misunderstanding from my side with [this comment](https://github.com/grafana/grafana-enterprise/pull/1233#discussion_r616975031), as I meant the same thing and took your answer as we keep everything in one place.

**Comment by sakjur** [comment]
Haha, yes

> I'd rather see that we merge two lists together.

was supposed to be expanded to "I'd like us to have the same _structure_ in both OSS and Enterprise, and then feed both of them here to create one combined list".

**Comment by vtorosyan** [comment]
Closing to move to the enterprise code source

**Pull request closed without merging**
