### PR TITLE
DevEnv: update frontend dependencies - mixed 2/2

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 12 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `sinon` - changes (1.17.6 -> 8.1.1): https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md
- `eventemitter3` - changes (2.0.3 -> 4.0.0): https://github.com/primus/eventemitter3/releases

Changes - less significant:
- `file-saver` - changes (1.3.8 -> 2.0.2): https://github.com/eligrey/FileSaver.js/blob/master/CHANGELOG.md
- `mousetrap` - changes (1.6.3 -> 1.6.5): https://github.com/ccampbell/mousetrap/releases
- `prism` - changes (1.16.0 -> 1.19.0): https://github.com/PrismJS/prism/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by dprokop** [comment]
@Estrax 

``` [
  {
    rawMessage: "ERROR TS2749: 'EventEmitter' refers to a value, but is being used as a type here.",
    message: 'ERROR in /go/src/github.com/grafana/grafana/public/app/core/utils/emitter.ts(5,20):\n' +
      "TS2749: 'EventEmitter' refers to a value, but is being used as a type here.",
    location: { line: 5, character: 20 },
    file: '/go/src/github.com/grafana/grafana/public/app/core/utils/emitter.ts'
  }
]
```

**Comment by mckn** [comment]
> @Estrax
> 
> ```
>   {
>     rawMessage: "ERROR TS2749: 'EventEmitter' refers to a value, but is being used as a type here.",
>     message: 'ERROR in /go/src/github.com/grafana/grafana/public/app/core/utils/emitter.ts(5,20):\n' +
>       "TS2749: 'EventEmitter' refers to a value, but is being used as a type here.",
>     location: { line: 5, character: 20 },
>     file: '/go/src/github.com/grafana/grafana/public/app/core/utils/emitter.ts'
>   }
> ]
> ```
> 
> I assume exported type changes in the updated version

I get the same issue

**Comment by mckn** [comment]
This solves that issue @Estrax 

ee3

**Review by mckn — DISMISSED** [review]
After applying the fix that I posted everything seems to be running great and all tests are green. Did some manual testing as well and it looks good 🙌

**Comment by Estrax** [comment]
Seems like tests are all green now. Thanks @mckn!

**Review by dprokop — APPROVED** [review]

**Pull request merged**
