### PR TITLE
add a placeholder to DingTalk Url

### PR DESCRIPTION
**Pull request by jiamliang**
add a placeholder in the dingtalk url field.

### CODE REVIEW

**Comment by daniellee** [comment]
@jiamliang the change looks fine but it looks like the commit author is wrong in this commit: https://github.com/grafana/grafana/pull/8818/commits/d69c7d2442b79f1749a320355cc6130ea56dfb1f

It should be jiamliang instead of root.

**Comment by daniellee** [comment]
If you know how to do it then an interactive rebase (and squash the commits) and then a force push would probably fix it.

**Comment by jiamliang** [comment]
new pr:  #8820

**Comment by bulletfactory** [comment]
Hello juamliang - We'd like to make you this week's Most Valuable Contributor on our blog series called timeShift [(here's last week's issue)](https://grafana.com/blog/2017/07/07/timeshiftgrafanabuzz-1w-issue-3/). 

To say thanks, we'd like to send you a Grafana shirt. Please email me at trent [at] grafana.com with your shippng address and t-shirt size and I'll take care of the rest.

**Pull request closed without merging**
