### PR TITLE
CircleCI: Run golangci-lint in two batches

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
To try to fix issues of golangci-lint OOM-ing, run it in two batches, one half of the linters at a time.

### CODE REVIEW

**Review by sakjur — APPROVED** [review]
Looking to see if I can get a memory usage flamegraph as well

**Review by marefr — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Sounds great @sakjur.

**Review by bergquist — APPROVED** [review]

**Comment by aknuds1** [comment]
The build is now failing consistently on the frontend tests job :/

**Review by Estrax — APPROVED** [review]

**Comment by Estrax** [comment]
@aknuds1 merged changes that remove few typescript strict-null errors, frontend tests should be green now.

**Pull request merged**
