### PR TITLE
Added GCS (Google Cloud Storage) support for image store

### PR DESCRIPTION
**Pull request by chuhlomin**
This PR covers #8370

### CODE REVIEW

**Comment by chuhlomin** [comment]
I'll refactor this to use JSON API instead of SDK.

**Comment by bergquist** [comment]
@chuhlomin This pr still contains lots of new packages in the vendor folder. Are those needed for the json api? other wise please remove those.

**Comment by bergquist** [comment]
This PR still uses two external packages for client oauth2 authentication.  
* golang.org/x/oauth/google 
* cloud.google.com/go/compute/metadata

Re-implementing that in grafana seems like an error prone task.

Another option would be to use Api keys but thats not recommended by GCP. 
```For security reasons, we recommend using service accounts for calling GCP APIs```
https://cloud.google.com/docs/authentication/

I think we should include those packages and trim to only include the code that we use and merge after some refactoring.
Google cloud platform is major platform after all.

**Comment by bergquist** [comment]
This pr have been merged in https://github.com/grafana/grafana/commit/87308fd97fc63bbcc2b5fe64a9f56f5016f19e77
forgot --no-ff when merging :/

**Pull request closed without merging**
