### PR TITLE
Update Explore CODEOWNERS

### PR DESCRIPTION
**Pull request by jdbaldry**
From @lwandz13 

> The Explore Squad technically no longer exists.

### CODE REVIEW

**Review by lwandz13 — APPROVED** [review]
thanks Jack!

**Review by tolzhabayev — APPROVED** [review]

**Comment by jdbaldry** [comment]
@graph-andrew @zhehao-grafana are you happy with these changes? You'll be sent a GitHub notification to review the PRs for any modifications to the Explore documentation

**Comment by jdbaldry** [comment]
@graph-andrew @zhehao-grafana

I am concerned that you don't have time to regularly triage GitHub notifications for these changes and review PRs in a timely manner. If that's the case, I'll take over as CODEOWNER instead.

**Review by graph-andrew — APPROVED** [review]

**Review by zhehao-grafana — APPROVED** [review]

**Comment by jdbaldry** [comment]
Adding @irenerl24 for review because, by removing this line, she now becomes the CODEOWNER for this section

**Review by irenerl24 — APPROVED** [review]

**Pull request merged**
