### PR TITLE
Add a new notifier : WeChat Work（企業微信）

### LINKED ISSUE #21211: Support send WeCom alert message
**What would you like to be added**:
[WeChat Work](https://work.weixin.qq.com/) is a popular IM in china for working.
We can add an message webhook for it.
**Why is this needed**:
make more friendly to WeChat Work user

### PR DESCRIPTION
**Pull request by n0vad3v**
**What this PR does / why we need it**:

This is the notifier for WeChat Work(https://work.weixin.qq.com/), WeChat Work works like DingTalk (DingDing/釘釘)，and is widely used by corporations in China, this notifier will allow Grafana to send notifications directly to WeChat Work.

**Which issue(s) this PR fixes**:
Closes #21211

**Special notes for your reviewer**:

Wechat Work's notifier is just another type of webhook, however it's in a weird json form, previously I've created a project called [n0vad3v/g2ww](https://github.com/n0vad3v/g2ww) to do so, while it will introduce another service for this, I've decided to try to write an notifier directly on Grafana.

Example run on local development screenshot as below:
Screenshot from 2020-07-07 15-15-39

### CODE REVIEW

**Review by oddlittlebird — COMMENTED** [review]
Docs look good.

**Comment by bergquist** [comment]
Hi! Not completely sure about this. I'm not sure we can keep maintaining this codebase as the integration changes.

**Comment by n0vad3v** [comment]
> Hi! Not completely sure about this. I'm not sure we can keep maintaining this codebase as the integration changes.

Should be no problem, I will continuously follow up both sides, and make adaptions if necessary.

**Comment by n0vad3v** [comment]
Hi!

Is there any update on this PR, I see the `continuous-integration/drone/pr Expected — Waiting for status to be reported
` seems jamed for the whole day.


Looking forward to the merge of this PR as this would greatly improve Grafana's experience on lots of China users.

**Comment by aknuds1** [comment]
To fix the CI issue, please just merge with latest master, to get the Drone configuration.

**Comment by n0vad3v** [comment]
> To fix the CI issue, please just merge with latest master, to get the Drone configuration.

Thanks, I've merged latest master and pushed.

**Comment by aknuds1** [comment]
Seems like CI triggered properly.

**Comment by n0vad3v** [comment]
Yeah, CI is passed, thanks for the tip.
`continuous-integration/drone/pr — Build is passing`

**Comment by n0vad3v** [comment]
Hi!

Is there any update on this PR, still looking forward on it.

**Comment by aknuds1** [comment]
I think we have to wait for @bergquist to return from vacation (should be in 1-2 weeks).

**Comment by n0vad3v** [comment]
Hi~ I'd like some review on this PR, please.
@bergquist could you help me on this?

Thanks!

**Comment by marefr** [comment]
I share the comment by @bergquist:

> Hi! Not completely sure about this. I'm not sure we can keep maintaining this codebase as the integration changes.

In addition, the referenced issue has barely no activity/upvotes. Compared with wechat (#12333) which has more activity/upvotes and we still haven't accepted a PR for that one. There's also a proper workaround using the existing webhook notifier.

@n0vad3v  thank you for the contribution, but I'm closing this for now. We would consider reopen this in the future given our stand on the maintainability aspect and activity/upvotes changes.

**Comment by n0vad3v** [comment]
No, WeChat work is widely used by Chinese corporations.

Speaking of  activity/upvotes, may be you can have a look at this:
Screenshot from 2020-08-26 09-46-53

The "proper workaround" might be the `https://g2ww-serverless.nova.moe/` developed by myself which implements an small adapter on Cloudflare Workers, but I still don't think is a so called  "proper workaround", it may cause many problems especially in some air-gapped environments (Such as banks).

**Comment by marefr** [comment]
> No, WeChat work is widely used by Chinese corporations.

I don't say no to that. We're hoping to have a plugin model for alert notifiers in the future and this would fit perfectly into that. Until then using a service in-between Grafana and WeChat work is a workaround.

**Pull request closed without merging**
