### PR TITLE
feat(loki-monaco-editor): update e2e test with autocomplete steps

### PR DESCRIPTION
**Pull request by matyax**
**What is this feature?**

This PR properly adds back the testing steps that were missing by a test commit made to https://github.com/grafana/grafana/pull/58080.

In short, the editor has been updated to Monaco, so we want to have E2E coverage of the autocomplete feature.

**Which issue(s) does this PR fix?**:

Part of https://github.com/grafana/grafana/issues/44985

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gabor — APPROVED** [review]
LGTM!

**Comment by matyax** [comment]
Checking if we can use `e2e().get('.monaco-editor textarea:first')` to get the editor value.

**Comment by matyax** [comment]
Build passed, so I'm going to use the previous approve here.

**Comment by svennergr** [comment]
> Build passed, so I'm going to use the previous approve here.

Sorry! Glad it passed with that solution.

**Pull request merged**
