### PR TITLE
Variables: Fixes so Textbox variables read value from url

### LINKED ISSUE #24576: Templating: TextBox variable not updated from url
**What happened**:
When I access a dashboard from url including a variable (`var-project=project3`), the default variable value is still used in the text field (_project1_ in the example).
Nevertheless, if I change the variable in the textbox the url is correctly updated.

image

**What you expected to happen**:
Variables set in the url should update the dashboard accordingly

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version:  Random data
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 - Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When we created the new variable system, we forgot to set the `query` when reading value from url and hence the textbox value was not updated.

**Which issue(s) this PR fixes**:
Fixes #24576

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Works great! 👍

**Comment by hugohaggmark** [comment]
@mckn any feedback on this?

**Comment by mckn** [comment]
> @mckn any feedback on this?

have not had the time to look into this one yet 🙈 Focusing on getting this one ready:
https://github.com/grafana/grafana/pull/24659

**Comment by hugohaggmark** [comment]
> > @mckn any feedback on this?
> 
> have not had the time to look into this one yet 🙈 Focusing on getting this one ready:
> #24659

No worries @mckn, then I'll squash this, anyway.

**Pull request merged**
