### PR TITLE
Issue #3078: Add a UID field to allow group membership search to be different to CN

### PR DESCRIPTION
**Pull request by mjh43**
Am a Go newbie so no doubt it needs some work...

### CODE REVIEW

**Comment by torkelo** [comment]
wont this break the feature for current setups?

**Comment by mjh43** [comment]
Have added logic to revert to old behaviour if UID field is not specified

**Comment by torkelo** [comment]
might be better to make group_search_filter to support template strings so a user can chose what property to use like 
```ini
group_search_filter = "(&(objectClass=posixGroup)(memberUid={{.UID\}}))"
```

```ini
group_search_filter = "(&(objectClass=posixGroup)(memberUid={{.Username\}}))"
```

would have support `%s` for backward compatibility as well

**Comment by torkelo** [comment]
sorry, closing this as there has been no updates & little interest in this feature

**Comment by nickjones** [comment]
I still need this feature.

**Pull request closed without merging**
