### PR TITLE
WIP: Spawn backend plugins v2

### LINKED ISSUE #19683: Plugins: Support loading new version of backend plugin
When new SDK/plugin model in #19666 have been merged we need to add support for loading this new version of backend plugins when scanning for plugins. Old backend plugins version from grafana-plugin-model should still be supported through the tsdb http query endpoint, i.e. continue to work as today.

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #19683

**Special notes for your reviewer**:
Requires this [branch](https://github.com/grafana/grafana-plugin-sdk-go/tree/export-datasource-plugin) of grafana-plugin-sdk-go

The server fails to start with this error:
```
[Bra] 10-15 19:34:19 [DEBUG] Running: ./bin/grafana-server [-packaging=dev cfg:app_mode=development]
panic: proto: duplicate enum registered: models.RowValue_Kind

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
	/Users/josefk/go/src/github.com/grafana/grafana/vendor/github.com/golang/protobuf/proto/properties.go:458
github.com/grafana/grafana-plugin-sdk-go/genproto/datasource.init.0()
	/Users/josefk/go/src/github.com/grafana/grafana/vendor/github.com/grafana/grafana-plugin-sdk-go/genproto/datasource/datasource.pb.go:865 +0x418

```
The above error is resolved by [this](https://github.com/grafana/grafana/pull/19835#issuecomment-542555892).

### CODE REVIEW

**Comment by kylebrandt** [comment]
I am not entirely sure I understand correctly, but I think protoc makes enums globally scoped (to work with old C stuff).

Thinking about this more, we probably should not repeat these protobuf types in the new version. Rather, the SDK can include import the old types and include methods to convert them into newer types, but the new proto api doesn't actually communicate any of the old types. @marcusolsson ?

**Comment by papagian** [comment]
The duplicate error is resolved by [renaming](https://github.com/grafana/grafana-plugin-sdk-go/commit/c9da9db681fd81fc077c2d203efc05783b0dcc3e) the Enum.

**Comment by kylebrandt** [comment]
> The duplicate error is resolved by [renaming](https://github.com/grafana/grafana-plugin-sdk-go/commit/c9da9db681fd81fc077c2d203efc05783b0dcc3e) the Enum.

Logs the following on startup though:

```
2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceRequest
2019/10/16 08:16:10 proto: duplicate proto type registered: models.Query
2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeRange
2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceResponse
2019/10/16 08:16:10 proto: duplicate proto type registered: models.QueryResult
2019/10/16 08:16:10 proto: duplicate proto type registered: models.Table
2019/10/16 08:16:10 proto: duplicate proto type registered: models.TableColumn
2019/10/16 08:16:10 proto: duplicate proto type registered: models.TableRow
2019/10/16 08:16:10 proto: duplicate proto type registered: models.RowValue
2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceInfo
2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceInfo.DecryptedSecureJsonDataEntry
2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeSeries
2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeSeries.TagsEntry
2019/10/16 08:16:10 proto: duplicate proto type registered: models.Point
```

**Comment by papagian** [comment]
> > The duplicate error is resolved by [renaming](https://github.com/grafana/grafana-plugin-sdk-go/commit/c9da9db681fd81fc077c2d203efc05783b0dcc3e) the Enum.
> 
> Logs the following on startup though:
> 
> ```
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceRequest
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.Query
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeRange
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceResponse
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.QueryResult
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.Table
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.TableColumn
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.TableRow
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.RowValue
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceInfo
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.DatasourceInfo.DecryptedSecureJsonDataEntry
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeSeries
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.TimeSeries.TagsEntry
> 2019/10/16 08:16:10 proto: duplicate proto type registered: models.Point
> ```

Indeed! I hadn't noticed that.

**Review by kylebrandt — APPROVED** [review]
LGTM once it passes @marefr's doesn't-seem-to-break-stuff manual testing

**Pull request merged**
