### PR TITLE
State Timeline: Prevent Label Text from Overflowing Labeled Segment

### LINKED ISSUE #56687: State timeline: consider truncating string values which exceed the segment length
In the state timeline panel, if the rendered string of an item is longer than the timeline segment it's associated with, it overflows in the neighbor segment(s).

Screenshot from 2022-10-11 12-41-19

Screenshot from https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1&editPanel=63 after editing one of the strings.

Maybe it would look better to handle this cases by truncating the string and adding an ellipsis symbol `...`. When hovering with the mouse cursor, the tooltip (if enabled) would still show the full string.

### PR DESCRIPTION
**Pull request by Azornak**
Rework of #52779.

Fixes https://github.com/grafana/grafana/issues/56687

Fixing labels overflowing in state timeline.
Added extra check to limit the usage of measureText.

It now makes a guesstimate on the text width via the text length, and only does measureText if the calculation is within 25% of the segment's width.

### CODE REVIEW

**Comment by leeoniya** [comment]
@Azornak maybe let's try rendering part of the label and chop off the stuff that overflows, unless we only have like 1 or 2 chars that would fit, then hide completely. there's still a lot of info in the first 3-4 chars :)

**Comment by Azornak** [comment]
@leeoniya Thanks for the feedback, sounds like a good idea. I'll look into it!

**Comment by leeoniya** [comment]
thanks for the updates!

i tried it out and wasnt too happy with the squished text look...that strategy maybe works better with fixed width fonts.

i pushed a commit to another branch with some adjustments and moved some early exit conditions up. can you try my changes out and see what you think? if you like it, feel free to cherry pick that commit into this branch or just incorporate those changes directly.

https://github.com/grafana/grafana/commit/dac446846c3ee09e31ad7a615aaa433bb8ad6bf3

this is the dashboard i've been testing with (just resizing the panel):

<details><summary>timeline-labels-test.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 488,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "fillOpacity": 80,
            "lineWidth": 1,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "alignValue": "center",
        "colWidth": 0.9,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": true,
        "rowHeight": 0.98,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "7.5.0-pre",
      "targets": [
        {
          "alias": "SensorA",
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "LOW,HIGH,NORMAL,NORMAL,NORMAL,LOW,LOW,NORMAL,HIGH,CRITICAL"
        },
        {
          "alias": "SensorB",
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "NORMAL,LOW,LOW,CRITICAL,CRITICAL,LOW,LOW,NORMAL,HIGH,CRITICAL"
        },
        {
          "alias": "SensorA",
          "hide": false,
          "refId": "C",
          "scenarioId": "csv_metric_values",
          "stringInput": "NORMAL,NORMAL,NORMAL,NORMAL,CRITICAL,LOW,NORMAL,NORMAL,NORMAL,LOW"
        }
      ],
      "title": "State changes strings",
      "type": "state-timeline"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "timeline-labels-test",
  "uid": "fD1L38S4k",
  "version": 2,
  "weekStart": ""
}
```
</details>

**Comment by Azornak** [comment]
Looks good to me! Incorporated your changes.

**Comment by leeoniya** [comment]
syned with main here: https://github.com/grafana/grafana/pull/59169

**Pull request closed without merging**
