### PR TITLE
handle wrong responses coming from  datasource backend requests

### PR DESCRIPTION
**Pull request by kkoehler**
Hi,

we're currently faced the situation where our backend (we are using a proxy in front of Grafana installation) accidently returns a redirect to a login page (HTTP response 403/200) and not a 401 HTTP response code when the user session timed out.
What happens is that the dashboard will show errors and the client tries again and again to get data but will never have success.... because the session in timed out.
In our cause the user has left the office and will return next morning... so there are lot of requests like this especially when it is a big dashboard ;-)

So, this patch will catch the response and check if it is a HTML response or not.

Not sure if this is also important to the "normal" Grafana installation but this might help others and does not harm the normal workflow.

Thanks,
Kristian

### CODE REVIEW

**Comment by kkoehler** [comment]
forgot to mention that we "redirect" to the root page if there is such an error

**Comment by torkelo** [comment]
dont think this solution works very well, it will redirect users to grafana root url if data source request return html, not good

**Comment by kkoehler** [comment]
For us the root url brings the user to the login page. So in our case this works well... 

Do you have an other idea where to redirect the user to? Configurable?

Or do you think the mechanism of redirecting in cause of an HTML response is wrong? We dont't see another option to our problem yet. Do you have another idea?

**Comment by torkelo** [comment]
closing this for lack of interest / unit tests

**Pull request closed without merging**
