### PR TITLE
Alerting: Fix navigating to URLs with "%"

### PR DESCRIPTION
**Pull request by gillesdemey**
Reverts https://github.com/grafana/grafana/pull/95407

`react-router-dom-compat-v5` does use `history@5.x.x` as a dependency however;

It still defers `useHistory` to its peer dependency (which is still `react-router-dom@5.x.x`
https://github.com/remix-run/react-router/blob/09ff7a0795ed1f6bef6da5b9221d75eebf0e3209/packages/react-router-dom-v5-compat/lib/components.tsx#L5-L7

Our `interceptLinkClicks` patch (hack?) still calls `locationService.push()` which would incorrectly _encode_ the URLs, resulting in a crash because the pathname is only partially encoded.

https://github.com/grafana/grafana/blob/df628951f5f60b526991528dd65190eafa50699d/public/app/core/navigation/patch/interceptLinkClicks.ts#L41

### CODE REVIEW

**Review by konrad147 — APPROVED** [review]
LGTM!

**Comment by tomratcliffe** [comment]
The other long term potential fix is to upgrade `history` to v5, right? As I believe its fixed in that version

**Comment by konrad147** [comment]
> The other long term potential fix is to upgrade history to v5, right? As I believe its fixed in that version

Yes! Unfortunately, history v5 is not compatible with react-router v5, so we need to migrate to react-router v6 and then upgrade history

**Pull request merged**
