### PR TITLE
datasources: change to optimistic concurrency

### PR DESCRIPTION
**Pull request by bergquist**
prerequisite for #9504

I made this a separate PR since its a topic itself. Should we support this? The only downside I can think about currently is that API operations for updating datasources will requiring getting a datasource before inserting one. But that's gonna be easier with configuration anyway.

### CODE REVIEW

**Comment by torkelo** [comment]
For the api operations we could make version optional, afraid otherwise it could break a lot of automation scripts

**Comment by bergquist** [comment]
I had to introduce nullable int since the initial value for version is 0. So there is no good way to detect missing version unless we support nullable.

**Comment by torkelo** [comment]
but a update call will always have version > 1   (if version was supplied), if 0 it was not supplied. 

Just afraid that we will break a lot of automation for data sources if we change API to require current version in order to update.

**Comment by bergquist** [comment]
When you create a new datasource the version is set to 0.
So if you want to update that datasource using version you need to send 0. 
If you dont care about version it will default to 0.


But that call will look the same as if you dont want to use version. that's why nullable is needed. To differentiate those two queries.

**Comment by torkelo** [comment]
version 0 should not be the initial value, 0 always indicates a unsaved value (at least with nhiberante .net orms). Version should be 1 after first save (it is for dashboards).

**Comment by bergquist** [comment]
Currently Grafana set version to 0 for new datasources. Adding a sql migration for that would be easy. But iIm not sure its worth it?

**Comment by torkelo** [comment]
It would I think as 0 is unsaved for a version field. And it would allow us to differentiate between unsaved and saved.

**Comment by bergquist** [comment]
Updated and squashed commits.

**Pull request merged**
