### PR TITLE
Dashboard: Add week start option to global and dashboard preferences

### LINKED ISSUE #18968: Start of week to be platform or per dashboard setting, not user-specific
As already reported in #3003 users outside of US/Canada/Japan expect the week to start on Monday, instead of Sunday. This is now somewhat addressed via #5517, however this solution is deferred to the user.

**What would you like to be added**:

I'd like to request to have the "start of week" definition not derived from the user's locale or timezone setting but instead make it either a "per installation" setting or have it configurable per dashboard.

**Why is this needed**:

As the start of the week is relevant to calculations with dashboards looking at "previous week" the results will differ for users with a US locale (often just listed as English in the browser) vs. people with other locale settings.

It's confusing and unintuitive when colleagues of different locations try to work together on last weeks results as some of these would be shifted by a day.

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

This PR implements the "Start of Week" option described on #18968.

As described on the issue the start of the week is relevant to calculations with dashboards looking at "previous week" and the results will differ for users with a US locale (often just listed as English in the browser) vs. people with other locale settings.

The option is implemented both on Shared Preferences and dashboard Time options in the format of a select.
Screen Shot 2021-10-05 at 15 59 36

The option selected can be applied to a specific dashboard or on Shared Preferences can be selected for the whole organization.

The selected option will be applied to any relative range that considers a week period, for example on "Previous Week".

Panels will start the week on the selected day.

**Which issue(s) this PR fixes**:

Fixes #18968

This PR is also needed for grafana/grafana-enterprise#1879

**Special notes for your reviewer**:

### CODE REVIEW

**Review by achatterjee-grafana — COMMENTED** [review]
Added doc review.

**Review by achatterjee-grafana — COMMENTED** [review]
Doc looks good.

**Review by sakjur — DISMISSED** [review]
The migration needs to allow null here, which shouldn't be a problem since there's a reasonable default to go back to.

I also have a question regarding the default, I think it should keep being depending on the browser's locale to avoid breaking current behavior, but you've documented it as being Monday? 🤔

**Review by hugohaggmark — COMMENTED** [review]
Sorry I missed this one, did a shallow code review and left some comments. Going to take it for a test drive right after this.

**Review by ashharrison90 — COMMENTED** [review]
minor nit

**Review by hugohaggmark — APPROVED** [review]
Frontend parts look great! 🎉

**Comment by guicaulada** [comment]
@sakjur helped me find an issue with the default value of the organization week start being set to 0 for existing databases instead of the configured default value, I am working on that issue now.

**Review by sakjur — APPROVED** [review]
LGTM :+1:

**Pull request merged**
