### PR TITLE
Update Faro to 1.2.5 and enable session tracking

### PR DESCRIPTION
**Pull request by cedricziel**
**What is this feature?**

Update the Faro Web SDK. This change is adding persistent session tracking.

**Why do we need this feature?**

Users of Faro can now follow the user journey across multiple page-loads. This should ultimately help using Faro and Grafana Cloud Frontend O11y to understand better root-causes of anomalies.

**Who is this feature for?**

Anyone who is developing Grafana and who wants to be able to get a better understanding of misbehavior.

### CODE REVIEW

**Review by codecapitano — APPROVED** [review]

**Comment by codecapitano** [comment]
@cedricziel 
I think the changelog is missing

**Comment by codecapitano** [comment]
@cedricziel question: since we no persist sessions in local storage, is there any need to update the privacy statement? Or at least to give someone a heads up that tracked sessions are enabled?

**Comment by cedricziel** [comment]
> @cedricziel question: since we no persist sessions in local storage, is there any need to update the privacy statement? Or at least to give someone a heads up that tracked sessions are enabled?

There is verbiage in the current terms about this

**Review by codecapitano — APPROVED** [review]

**Review by ivanortegaalba — APPROVED** [review]
Great addition! 💯

**Comment by cedricziel** [comment]
Superseded by #78578

**Pull request closed without merging**
