### PR TITLE
FieldConfig: expose nullValueMode and respect Ignore for react panels

### LINKED ISSUE #18785: Bar Gauge: do not display rows if there is no data
**What happened**:
For stats that have no data points, Bar Gauge shows full bar. Even using "Last (not null)" reducer (introduced in #17911) doesn't change it:

Screen Shot 2019-08-29 at 15 13 03

**What you expected to happen**:
Stats that have no data points should either be set to 0 (?) or, better, not be present in the graph.

**How to reproduce it (as minimally and precisely as possible)**:
1. Graph something that once existed that no longer exists (eg. CPU usage of servers which have been shut down)
2. Use Bar Gauge visualization, grouping by server, with Calc set to "Last (not null)"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: kairosdb
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS/Chrome
- Grafana plugins: -
- Others:

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes: #18785

~~Totally untested, but I needed something simple to do :)~~ alas simple things never are 😢

### CODE REVIEW

**Comment by pitr** [comment]
Is this only for SingleStat panel type?

**Comment by dprokop** [comment]
@pitr this should work for single-statish visualizations, like BarGauge, Gauge and SingleStat

**Review by torkelo — COMMENTED** [review]
Tested this but cannot see it having any effect on min or mean value reducers (calcs), or sparkline.

**Comment by torkelo** [comment]
Screen Shot 2019-09-09 at 19 46 37

This is still a bit confusing to me. 

1) Having last value be null and reducer to "last" and null option be "As Zero" leaves a blank display.
2) The Ignore option has no effect on the reducer, like if you want the Mean, should Ignore have an impact there? Not sure. I discovered what Ignore does below :) 
3) What does Ignore mean in the context of a single stat? I tested now with a multi series result and then it does filter out the null values (does not show them). So I think this is correct. If there is nothing to show (all have null) it shows "No data". and I think this is fine as well.

**Comment by ryantxu** [comment]
> This is still a bit confusing to me.

😢 -- see what happens when I try "something simple"

That said, I am happy this points out issues with the existing settings and helps clarify how we want it to behave.

We have two places this is used:
A. reducer calculations.  Obviously not used consistently, and it should be.
B. (added in this PR) ignoring fields with null values in BarGauge/Gauge/etc

Should this be the same setting or different?  I think the same is OK since `B` is really just the 'ignore' case.

> What does Ignore mean in the context of a single stat?

If we have a panel where everything is null, there should be at least one thing saying "No Data"

**Comment by torkelo** [comment]
> If we have a panel where everything is null, there should be at least one thing saying "No Data"

yea, agree.

**Comment by torkelo** [comment]
Can we move it to the display box under Calc? It just feels more logical there (can still live on FieldConfig).

**Comment by ryantxu** [comment]
letting this one go...  can revist

**Pull request closed without merging**
