### PR TITLE
Docs: Time series panel, bar alignment docs

### PR DESCRIPTION
**Pull request by dprokop**
Adds docs for https://github.com/grafana/grafana/pull/30499

@oddlittlebird could you please add screenshots for this one?

### CODE REVIEW

**Comment by achatterjee-grafana** [comment]
We will need images to be consistent with the rest of the content on this page.

**Comment by oddlittlebird** [comment]
What release does this apply to? I didn't see these options when I was doing documentation for 7.4.

**Comment by ryantxu** [comment]
Part of 7.4 -- the option was merged 4 hours ago

**Review by oddlittlebird — APPROVED** [review]
I cleaned up the text a bit. Images are in https://github.com/grafana/website/pull/3350

**Pull request merged**
