### PR TITLE
makes tag colors more accessible

### LINKED ISSUE #22396: Accessibility: not all Tag colors are accessible
Tag colors used within Dashboard settings are assigned randomly. Some of them do not comply with accessibility regulations and do not have a minimum color contrast of 4.5 with the font color of #F2F2F2.

**Steps to reproduce**:
Go to Dashboard settings and add around 20-30 Tags. All of them are assigned randomly.

**Actual Result**:
Background colors like:
HEX: '#E24D42'
HEX: '#1F78C1'
HEX: '#BA43A9'
do not have enough color contrast

**Expected Result**
For example:
HEX: '#d32d20'
HEX: '#1e72b8'
HEX: '#b240a2'
are similar to listed above but have enough color contrast with #F2F2F2 color of a font

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion]
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast

**Environment**:

- Grafana version: 6.7.0-pre
- Data source type & version: TestData DB coming with Simple dummy streaming example
- User OS & Browser: MacOS Mojave, Mozilla and Chrome

### PR DESCRIPTION
**Pull request by MaximKipot**
Fixes #22396

### CODE REVIEW

**Comment by torkelo** [comment]
Can you show a before and after picture with examples tags?

**Comment by MaximKipot** [comment]
Here are some before and after examples with corresponding color contrasts. (I also changed a bit layout so one can see all the tags presented in several lines, do not wonder as it looks different than official version):
Before:
tag-colors-before
After:
tag-colors-after

Hope it helps.

**Comment by dprokop** [comment]
From my POV(colour blind) the updated colors look OK

**Review by torkelo — APPROVED** [review]
looks ok

**Pull request merged**
