### PR TITLE
New dropdown menu to surface the snapshot feature, basic styling in p…

### PR DESCRIPTION
**Pull request by mattttt**
…lace. Want to extend menu to include summary text of each feature

### CODE REVIEW

**Comment by mattttt** [comment]
I should have included an animated gif when I submitted it originally:

new-share-dropdown

**Comment by mattttt** [comment]
bah, just realized the Link icon in the menu doesnt match the popup icon. Will fix and resubmit quickly.

**Comment by nopzor1200** [comment]
I like it. Maybe the text could be a bit clearer re: actions, eg. "send
link to live dashboard" and "take snapshot of current data"

Raj Dutt

co-founder/ceo, raintank
+1-917-664-1310
dutt@raintank.io

**Comment by mattttt** [comment]
@nopzor1200 Completely. I want to extend the menu to include summary text of each feature, but that will be additional styles & design that do not currently exist in Grafana today. I wanted to get this incremental feature pushed, and then go back and improve upon it.

**Comment by mattttt** [comment]
Updated:

new-share-dropdown-2

**Pull request merged**
