### PR TITLE
Update latest.json for 6.2.3, and then 6.2.4

### PR DESCRIPTION
**Pull request by gotjosh**
6.2.3 was released with a bug and we had to quickly release 6.2.4. Due to that, the `latest.json` was delayed on being updated. 

This PR updates it to 6.2.3 and then subsequentially to 6.2.4

### CODE REVIEW

**Review by marefr — DISMISSED** [review]
Let's wait with this until we have released 6.2.4 and then update this PR with 6.2.4 version.

**Comment by gotjosh** [comment]
Sounds good to me @marefr.

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
@marcusoftnet this should be good now. I can't merge without your approval, can I get a quick pair of 👀?

**Pull request merged**
