### PR TITLE
Add the ability to vertically zoom on graphs using the crosshair-drag

### LINKED ISSUE #9457: [Feature request] Allow vertical zoom in graph panel
* Grafana version: v4.5.2
* What datasource: Graphite, Prometheus.

Grafana graphs currently support horizontal zoom, e.g. to focus on a particular subset of the current time range. It would be very helpful to also support vertical zoom. In order words, to temporarily override the Y-axis min and max.

This can enable much better understanding of the data in a more granular level. Especially for one-off cases. Without requiring one to edit the graph settings. (Apart from being a big barrier, also not all viewers will have edit rights.)

Here is an example from the London Datastore that provides this ability:

<https://data.london.gov.uk/>

==============================
‣ Zoom 
‣ Result 
------------------------------

\==============================

==============================
‣ Zoom 
‣ Result 
------------------------------

\==============================

### PR DESCRIPTION
**Pull request by jsferrei**
Fixes #9457

Screenshots of feature in action:
screen shot 2018-10-09 at 3 27 41 pm 2
screen shot 2018-10-09 at 3 27 48 pm

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thank you for your contribution.

I'm on Ubuntu using Google Chrome. Cannot get this to work. According to shortcut help I should use `mod + click + drag` to Zoom in y-axis. For me that's `ctrl + click + drag` and triggers creation of an annotation. Looking at the code seems that I maybe should use `alt` instead, but that doesn't work either. 

Please include detailed information of how to use this feature for us to be able to review this PR further.

I should add that the referenced issues doesn't have that many upvotes so there's no promises that we merge this feature/PR short term. But it's definitely an interesting feature.

**Comment by jsferrei** [comment]
@marefr my bad, The shortcut help info is incorrect, 'alt' should be the modifier key. I'll update it.

**Comment by marefr** [comment]
@jsferrei As I wrote I tried `alt` but couldn't get that to work either.

**Comment by jsferrei** [comment]
@marefr Apologies missed that. Are you holding 'alt' and dragging in the vertical direction?

**Comment by marefr** [comment]
Yes, holding my left alt, clicking and dragging vertical downwards. Attaching some animated gifs.

peek 2018-10-10 19-41
peek 2018-10-10 19-42

**Comment by jsferrei** [comment]
@marefr thank you for the added detail. I'll have to grab an Ubuntu machine and test this out.

**Comment by marefr** [comment]
@jsferrei any updates to bring regarding this?

**Comment by jsferrei** [comment]
@marefr None really. I haven't had time to revisit this as other things have taken priority.

**Comment by marefr** [comment]
@jsferrei Okay thanks. If you don't plan to work on this in near time I suggest we close this now. Basically since we want open PR's to reflect work in progress/review needed. 

When you're ready to work on this again let me know and I'll reopen it. How does this sound?

**Comment by marefr** [comment]
We want open PR's to reflect work in progress/review needed. When you're ready to work on this again let me know and we'll reopen it.

**Comment by jsferrei** [comment]
@marefr Makes complete sense -- thanks!

**Pull request closed without merging**
