### PR TITLE
Auth: Lockdown non-editables in frontend when external auth is configured

### PR DESCRIPTION
**Pull request by Jguer**
**What this PR does / why we need it**:

Block frontend editing of attributes that will just be reset by the user logging back in.

- Profile info from signed in profile page
- Adding users to new orgs when they'll just be removed after

Before:
swappy-20220713_143847

swappy-20220713_143941

-------

After:

swappy-20220713_151758

swappy-20220713_153954

swappy-20220713_151612

(Save button was greyed out after this screenshot)

In future PRs:

- we'll block on the backend side as well
- we'll stop org users from being removed from org member view if they'll just be added right back by Auth

### CODE REVIEW

**Review by IevaVasiljeva — APPROVED** [review]
Awesome, really great to see this fixed! I'll test it out, but the code looks good.

**Comment by napstr** [comment]
This appears to break installations that run `oauth_skip_org_role_update_sync = true` and want to manage roles manually for external users 😕

**Comment by Jguer** [comment]
Hey @napstr , I've created an issue linked to this https://github.com/grafana/grafana/issues/54688. As a workaround currently you should still be able to use the API endpoints directly

**Comment by napstr** [comment]
Thanks for the hint, I resorted to editing the db tables in sqlite directly for the meantime.

**Pull request merged**
