### PR TITLE
Docs: Create the Azure AD application section has outdated information.

### PR DESCRIPTION
**Pull request by ej25a**
**What is this feature?**

This update removes outdated information in step 8 of the Create the Azure AD application section to remove the Expires option from Never to Select an expiration period

**Why do we need this feature?**

Outdated docs

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes # https://github.com/grafana/support-escalations/issues/6304

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by chri2547** [comment]
@ej25a , please sign the CLA. Thank you.

**Comment by chri2547** [comment]
@IevaVasiljeva , @linoman , can you please technically review this PR. Thank you.

**Comment by linoman** [comment]
@ej25a Thank you so much for your contribution. We agree the docs need a well-deserved facelift! The good news is that we're already working on them! The bad news is that we haven't updated the docs for Azure AD integrations yet.

While your PR makes a lot of sense, the docs for Azure AD will be updated very shortly. One of the key improvements is to remove the step-by-step guide to 3rd party IdPS, and instead, refer them to the [latest documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal) of the IdPs.

We already did something similar with the Okta documentation. [Check it out](https://github.com/grafana/grafana/blob/main/docs/sources/setup-grafana/configure-security/configure-authentication/okta/index.md#steps)!

Expect some major improvements with the Azure AD integration documentation.

**Review by linoman — APPROVED** [review]
@ej25a after some consideration we decided to include your PR as is! Please sign the CLA for the Grafana repo in order to have this ready to merge.

**Pull request merged**
