### PR TITLE
Alerting: Fix refetching grafana rules on alert list panel

### LINKED ISSUE #71593: Alerting: The Alert list won't be refreshed automatically after upgrade to 10.0.2
### What happened?

The Alert list won't be refreshed automatically after upgrade to 10.0.2

### What did you expect to happen?

should be automatically refreshing the Alert list.

### Did this work before?

working without issue on 10.0.1

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 10.0.2
OS: Debian 11 ARM64 on RaspberryPi 4
Browser: Chrome, FireFox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
This PR fixes the re-fetching of Grafana-managed alerts on the alert list panel

**Which issue(s) does this PR fix?**:

Fixes #71593 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by soniaAguilarPeiron — APPROVED** [review]
LTGM! no nits! 🚀

**Review by VikaCep — APPROVED** [review]

**Pull request merged**
