### PR TITLE
Elasticsearch: Convert Timeseries and Tables to Dataframes

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR is responsible for removing deprecated packages and converting timeseries and table objects to dataframes for Elasticsearch.

### CODE REVIEW

**Comment by Elfo404** [comment]
I took this for a quick ride, and I seems to work nice! 🚀 

i think we have some issue on how we name series though:
For example:

FE: `Count`
BE: `value`
NOTE: Multiple count returns 0 for each series

All other metrics seems to return “@value” as a series name, and are not deduped (but not deduping also happens in FE):
FE: `Average @value`
BE: `@value`

Probably would be a good idea to check the current naming patterns in both BE and FE and come up with a solution that will also serve future total BE  migration.

But aside from this I think this is an excellent starting point! 🔥 🔥 🔥

**Comment by Elfo404** [comment]
I pushed a failing test case that i found happening when Elasticsearch is booting up, when issuing a query this response makes grafana panic:

```json
{
  "error": null,
  "aggregations": null,
  "hits": null
}
```
I'm investigating the reason

**Comment by Elfo404** [comment]
Apparently i'm not able to reproduce that issue anymore. i reverted the commit introducing the failing test, but I'll try to keep an eye on it if it happens again.

**Comment by dsotirakis** [comment]
Maybe a random failure then, having to do with your configuration @Elfo404 ?

**Review by Elfo404 — APPROVED** [review]
Works as expected 🚀

**Comment by Elfo404** [comment]
@dsotirakis yeah, could be. i also tried different docker configurations & different ES versions but couldn't reproduce it. 🤷

**Pull request merged**
