### PR TITLE
Support timeFilter in query templating for InfluxDB

### PR DESCRIPTION
**Pull request by kichristensen**
After support for queries in template variables was added to InfluxDB, it can be necessary to added dymanic time constraints. This can now be done changing the variable refresh to "On Time Range Changed" for InfluxDB

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
a unit test for this would be good.

**Comment by kichristensen** [comment]
Of course, I'll do that later this week

fre. 13. jul. 2018 21.11 skrev Torkel Ödegaard <notifications@github.com>:

**Comment by kichristensen** [comment]
@torkelo I've now added a unit test for this

**Comment by kichristensen** [comment]
Ahh timezone issues :( I'll fix it

**Comment by kichristensen** [comment]
@torkelo The test should have been fixed now

**Review by torkelo — APPROVED** [review]

**Comment by kichristensen** [comment]
@marefr Done

**Pull request merged**
