### PR TITLE
PanelContext: Adds app property of type CoreApp enum to inform panel about what the outer container/app is

### PR DESCRIPTION
**Pull request by torkelo**
Instead of adding a isEditing or isViewing bools to PanelContext I figured it could be better to make this a little more generic and be something we can use for other things, to communicate to the panel in what context it is being rendered in.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by torkelo** [comment]
@ryantxu changed this to use CoreApp think this makes more sense, but it is a bit off as before we used CoreApp.Dashboard for query editors which I changed to now default to CoreApp.PanelEditor  , dont think this is used by any external plugins to have special logic in Dashboard vs Explore (if any it should be logic to check for Explore).

**Comment by torkelo** [comment]
@ryantxu changed this to use CoreApp think this makes more sense, but it is a bit off as before we used CoreApp.Dashboard for query editors which I changed to now default to CoreApp.PanelEditor  , dont think this is used by any external plugins to have special logic in Dashboard vs Explore (if any it should be logic to check for Explore).

**Comment by ryantxu** [comment]
:+1: I think this is good

**Review by dprokop — COMMENTED** [review]
Makes sense!

**Pull request merged**
