### PR TITLE
database: add support for defining additional database connection string args

### PR DESCRIPTION
**Pull request by tpetr**
This PR makes it easier to use [Vitess](https://github.com/vitessio/vitess) as a database backend for Grafana. The biggest blocker here is that Vitess does not support prepared statements, so `extra_connection_string_args` allows you to set `interpolateParams=true` which prevents the golang mysql driver from using prepared statements by default.

Let me know if there's anything else I can do to clarify or make this PR merge sooner. Thanks!

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
Grafana already supports a url connection string setting. Sadly this is parsed and only a few properties is extracted. 

Would be better to improve the use of that setting so that additional args can be parsed and used that way. Then we do not need to introduce another setting for this feature. 

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L80

**Comment by tpetr** [comment]
@torkelo makes sense. 👍 Updated PR to append query params from the URL to the end of `cnnstr`.

**Comment by tpetr** [comment]
@torkelo I'm sure you're super busy, but any chance you could take another peek at this? We'd love to be able to move off of our fork and back onto mainline.

**Review by marefr — APPROVED** [review]
Looks good :+1:

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
