### PR TITLE
Migration: snapshot list

### PR DESCRIPTION
**Pull request by ademidoff**
https://github.com/grafana/grafana/issues/21484

Notes to the reviewer: 
1. Is mutating `NavModel` in components an informed decision (see [here](https://github.com/grafana/grafana/blob/master/public/app/core/selectors/navModel.ts#L18-L49)), or maybe we could update the `active` prop in `state.navIndex.dashboards.children` by just dispatching an action to the store? If yes, which action?
2. What is the minimum requirement for tests? Just components?
3. For some reason `React.useEffect` wouldn't work in `SnapshotListPage`. Do you know of any particular reason why?
4. Is there a better place to store the `Snapshot` interface rather than in `public/app/features/manage-dashboards/types.ts`?
5. Is there a library function to do this: `const absUrl = window.location.href;`?
6. Noticed that `GET /api/dashboard/snapshots` is not REST-compliant. Should I create an issue or a pull request?

### CODE REVIEW

**Comment by torkelo** [comment]
> Is mutating NavModel in components an informed decision (see here), or maybe we could update the active prop in state.navIndex.dashboards.children by just dispatching an action to the store? If yes, which action?

There is no mutation there, see https://github.com/grafana/grafana/blob/master/public/app/core/selectors/navModel.ts#L24

**Comment by tskarhed** [comment]
> 3. For some reason `React.useEffect` wouldn't work in `SnapshotListPage`. Do you know of any particular reason why?

You can't use hooks in class components. I think in this case it can actually be rewritten to a functional component.

**Comment by atymchuk** [comment]
> > 1. For some reason `React.useEffect` wouldn't work in `SnapshotListPage`. Do you know of any particular reason why?
> 
> You can't use hooks in class components. I think in this case it can actually be rewritten to a functional component.

At first,  I made it functional, but couldn't get `useEffect` to work. It was just not firing, although the dependencies seemed to be OK.

**Comment by atymchuk** [comment]
> > Is mutating NavModel in components an informed decision (see here), or maybe we could update the active prop in state.navIndex.dashboards.children by just dispatching an action to the store? If yes, which action?
> 
> There is no mutation there, see https://github.com/grafana/grafana/blob/master/public/app/core/selectors/navModel.ts#L24

@torkelo  Oh, you are right - the items get copied properly. But still, it's very unusual to see the Store mutated outside of reducers.

**Review by tskarhed — CHANGES_REQUESTED** [review]
The entire list disappears when I remove an item. I would have an extra look at `doRemoveSnapshot`.
Screencast-from-2020-05-05-12_07_17

**Comment by tskarhed** [comment]
Overall good work! If you need some inspiration, you can have a look at https://github.com/grafana/grafana/pull/23821/files

**Comment by atymchuk** [comment]
> The entire list disappears when I remove an item. I would have an extra look at `doRemoveSnapshot`.
> Screencast-from-2020-05-05-12_07_17

Thanks, fixed now & tested.

**Review by tskarhed — APPROVED** [review]
This looks good to me! Thanks for the contribution! :smiley:

**Comment by atymchuk** [comment]
@tskarhed Now that this is merged, could you please update the relevant checkbox [here](https://github.com/grafana/grafana/issues/21484)?

**Pull request merged**
