### PR TITLE
expose Emitter to plugins

### PR DESCRIPTION
**Pull request by ryantxu**
I’m not sure this is widely used, but I have a datasource that creates its own events (and special panels that listen to them)

### CODE REVIEW

**Comment by torkelo** [comment]
This is kind of an internal lib that we might want to change without breaking plugins. Not sure it should be exposed. Maybe....

**Comment by ryantxu** [comment]
Isn't Emitter just a thin wrapper around eventemitter3?  plugins already use the Emitter#on() and Emitter#emit()

Exposing Emitter still lets you change eventemitter3 without changing the API

**Comment by bergquist** [comment]
How are the emitter instance shared between datasource and panels? 

Perhaps you could just use appEvents instead.

**Comment by torkelo** [comment]
> Isn't Emitter just a thin wrapper around eventemitter3? plugins already use the Emitter#on() and Emitter#emit()

Yes. But only through PanelCtrl.events do you want to create your own emitter?

**Comment by ryantxu** [comment]
> do you want to create your own emitter

Yes -- I have a datasource that creates an emitter and some special panels that listen to these events.  I have a datasource that keeps itself in sync (via websockets and/or http) with hardware, most things flow through standard grafana polling APIs -- but some things need special push notification.

I could use appEvents -- but then the `data` packet would need to include the source and each listener would need to check the source before using it.

**Comment by ryantxu** [comment]
Looking more... I can just convert from using Emitter to rxjs/Observable

**Pull request closed without merging**
