### PR TITLE
UserTable:  fix issue when search query contains "."

### LINKED ISSUE #94296: User search API : Fail to find user when using email addresses
### What happened?

I create users where name/email/username are all set to the email of that person: `person1@organization.com`

Recently looks like I can't search the user by email, it returns empty results

When searching users in this page `/admin/users`, searching `person1@organization` works `person1@organization.com` doesn't

```
/api/users/search?perpage=50&page=0&query=person1@organization\.com&activeLast30Days=false
```

Running the API call locally I can see results if I remove the dot escape 

`query=person1@organization.com` ✅  
`query=person1@organization\.com` ❌ 

### What did you expect to happen?

searching users by full username should work `person1@organization.com`

### Did this work before?

yes, not sure where the error started

I'm running 11.1.7 (just upgraded from 11.1.3 while looking at this issue)

### How do we reproduce it?

1. Have an user with name/email/username like user@app.com
2. Search user by full email address on 'Users' page
3. Find no results

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 11.1.7 (and 11.1.3)
OS: Ubuntu 24
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #94296
image

### CODE REVIEW

**Comment by aarongodin** [comment]
Thanks for the contribution! Taking a look at the referenced issue, I'm finding that I'm only able to recreate the problem in SQLite. Due to the fact that Grafana supports multiple RDBMS, this is likely better fixed by doing the following:

1. Use [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to convert the query to a URI-safe format before applying it to the query string on the GET request.
2. Check on the backend that the query is decoded correctly (this is probably handled by default) and that the string value is exactly what the user typed into the search input.
3. Check that the query passed to this helper method returns the expected results: https://github.com/grafana/grafana/blob/19844220db28e55c9c5e61730b6df036bc2b7cf9/pkg/api/org_users.go#L295

**Comment by yincongcyincong** [comment]
> Thanks for the contribution! Taking a look at the referenced issue, I'm finding that I'm only able to recreate the problem in SQLite. Due to the fact that Grafana supports multiple RDBMS, this is likely better fixed by doing the following:
> 
> 1. Use [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to convert the query to a URI-safe format before applying it to the query string on the GET request.
> 2. Check on the backend that the query is decoded correctly (this is probably handled by default) and that the string value is exactly what the user typed into the search input.
> 3. Check that the query passed to this helper method returns the expected results: https://github.com/grafana/grafana/blob/19844220db28e55c9c5e61730b6df036bc2b7cf9/pkg/api/org_users.go#L295

thanks for the review. actually, the search api is https://github.com/grafana/grafana/blob/main/pkg/services/searchusers/searchusers.go#L65
 and i don't find any function to handle `query` string.
https://github.com/grafana/grafana/blob/main/pkg/services/searchusers/searchusers.go#L74

at frontend part. just use https://github.com/grafana/grafana/blob/a3764ebeba5dc1ff02bc7a73f7ab8628d981f473/packages/grafana-data/src/text/string.ts#L8
this function to handle `query` string, not encodeURIComponent.

**Comment by yincongcyincong** [comment]
@aarongodin bro, i modified the way i fix this bug. i check if db is sqlite or not at backend part. if yes, i will use unescape function to remove \ to empty string.
and add a function base blow code.
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/text/string.ts#L3

**Comment by yincongcyincong** [comment]
@aarongodin bro, could you please take a look this pr. thanks.

**Comment by yincongcyincong** [comment]
@aarongodin bro, could you please take a look this pr. thanks.

**Review by aarongodin — APPROVED** [review]

**Comment by yincongcyincong** [comment]
@aarongodin bro, could you please merge this pr?

**Review by kalleep — CHANGES_REQUESTED** [review]
Hey, lets not perform this in the backend.

Taking a look on the front-end code it seems like the filtering was done there at some point. 

Your original commit was correct so could you please revert to that https://github.com/grafana/grafana/pull/94389/commits/5bd5b3a3fe4fe9ac73576da2db9bcc67affe7d7e

**Comment by yincongcyincong** [comment]
> Hey, lets not perform this in the backend.
> 
> Taking a look on the front-end code it seems like the filtering was done there at some point.
> 
> Your original commit was correct so could you please revert to that [5bd5b3a](https://github.com/grafana/grafana/commit/5bd5b3a3fe4fe9ac73576da2db9bcc67affe7d7e)

thanks for your reply. actually i'm not sure it can correctly work on other db. such as mysql.
but i will revert it.

**Comment by yincongcyincong** [comment]
@kalleep bro. i revert it. please take a look. thanks

**Review by kalleep — APPROVED** [review]

**Comment by yincongcyincong** [comment]
@kalleep bro. could you please merge this pr. thanks

**Pull request merged**
