### PR TITLE
Barchart Panel: Fix threshold colors changing when data is refreshed

### LINKED ISSUE #47297: Threshold colors not loading properly
**What happened**:
The Bargraph is set up for mysql Table, Threshold color is setup. The color are working properly at the time of dashboard loading and once any  variable changes at dashboard top and bar graph values are changed the threshold colors are not working properly.
The dashboard is setup to reload every 5s. also tried with overide property, same issue exist.

The threshold color setup like this base red,>70 yellow,>90 Green
Graph at time of loading of dashboard
s1

Graph showing incorrect threshold colors when variables and values are changed
s2

**What you expected to happen**:
The threshold color needs to be changed when the values of the graph changes in the dynamic dashboards

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: MySQL 8.0.28
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: Mysql

### PR DESCRIPTION
**Pull request by mingozh**
**What this PR does / why we need it**:
Fix bar color from thresholds show incorrectly when data changed by changing time range.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/47297

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mellieA** [comment]
Thank you for your contribution @mingozh, I've forwarded this on to the squad for comment and review

**Comment by mingozh** [comment]
Reference the signature of function "getColor" in another place:
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/barchart/bars.ts#L52

**Review by codeincarnate — APPROVED** [review]
Tested this out and looks good. For typing we generally try to stay away `any` in the case of the value. However I can follow up to change that.

**Comment by codeincarnate** [comment]
Thanks for the contribution @mingozh!

**Pull request merged**
