### PR TITLE
Tempo: Reduce initial bundle size

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

This PR reduces the initial bundle of tempo datasource to speed up dashboard loading.

Additionally I've externalised `rxjs/operators` in the plugin-configs webpack config (it's been shared via systemjs for a long time) and added a `stats` env var which adds the webpack-bundle-analyser for devs to debug bundle sizes.

**Why do we need this feature?**

The tempo datasource seems to be weighing in at 3.39MB for a production build. This PR changes the module.ts to lazy load the query editor, config editor and the cheat sheet.

| Before | After |
| --- | --- |
| image | image |

I'm not sure where this occurred but it seems related to importing `languages` from monaco-editor in [this PR](https://github.com/grafana/grafana/pull/96943/files#diff-666e28cd8f4263c8acbeec76db74f0d091d0d7a4c1221e906f9c29325c195a61R1).

**Who is this feature for?**

Grafana users

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

I have not tested these tempo changes - will put it on an ephemeral instance for testing shortly.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by adrapereira — APPROVED** [review]
Thank you for these changes! 🙏

**Comment by jackw** [comment]
@adrapereira you're welcome. Can you confirm the plugin and its various editors continue to function correctly please before merging.

**Pull request merged**
