### PR TITLE
MSSQL: Mention excluded databases in the doc

### LINKED ISSUE #67296: MsSQL: Mention excluded databases in docs
**What is the chore?**:

We don't include tempdb,model,msdb, master databases in the query editor dropdown. We need to mention this in our doc.

**Is there anything else we need to know?**:

### PR DESCRIPTION
**Pull request by Soham-glitch**
fixes #67296 
updates the doc and includes excluded databases

### CODE REVIEW

**Comment by Soham-glitch** [comment]
it would be great if someone reviews it and merge it or tell me what changes should I do.

**Review by zoltanbedi — APPROVED** [review]
LGTM, Thank you @Soham-glitch!

**Comment by zoltanbedi** [comment]
@lwandz13 do you also want to take a look or can I merge it?

**Comment by lwandz13** [comment]
Looks good!  I still can't merge PRs, so feel free @zoltanbedi .  :-)

**Review by lwandz13 — APPROVED** [review]

**Pull request merged**
