### PR TITLE
Postgres: Fix timeGroup macro converts long intervals to invalid numbers when TimescaleDB is enabled

### PR DESCRIPTION
**Pull request by kurokochin**
**What this PR does / why we need it**: This bug occurs when we passed more (or equals) than 12d as an argument for timeGroup inside TimescaleDB/Postgres query

**Which issue(s) this PR fixes**: #27253 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kurokochin** [comment]
Fix and test based on @marefr on this [comment](https://github.com/grafana/grafana/issues/27253#issuecomment-775277528).

**Comment by acedrew** [comment]
@kurokochin Thanks so much for picking this up!

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
