### PR TITLE
misc: Update to Go 1.18

### PR DESCRIPTION
**Pull request by sdboyer**
**What this PR does / why we need it**:

Updates us to Go 1.18

Motivation for this: i'm introducing some generics in Thema (grafana/thema#63) which require go 1.18, and will shortly be putting up a PR against grafana that depends on those. This PR just separates out the Go version bump so we can deal with it first, separately from that other, large PR.

### CODE REVIEW

**Comment by sakjur** [comment]
I think we'll also need to upgrade the Go version we're using to build since we're currently on 1.17.11, #52321 starts that. We'll need a new version for grabpl as well.

**Comment by torkelo** [comment]
I think updating go requires a bit more. 

For references: 
https://github.com/grafana/grafana/pull/38608/files

**Comment by sdboyer** [comment]
Ahhh yes

**Comment by sdboyer** [comment]
closing this laziest PR ever in favor of #52321 😄

**Comment by sdboyer** [comment]
Reopening, as this didn't get bumped with the other change that did all the actual hard parts #54902 :)

We _could_ bump this to `go 1.19`, but all i specifically need is generics from 1.18, so safer to just do this for now.

**Review by sakjur — APPROVED** [review]

**Pull request merged**
