### PR TITLE
add support for oauth secured prometheus datasources

### PR DESCRIPTION
**Pull request by jeremyeder**
Resending #9619 after signing the CLA.

### CODE REVIEW

**Comment by jeremyeder** [comment]
I believe the quotes were changed by sasslint? As they weren't in my original patch.

**Comment by torkelo** [comment]
yes, we ran prettier on all files (and added a pre commit hook that formats all files). 

Thanks for contributing to Grafana!

Not sure about this approach, hardcoding a token in the data source settings does not seem like the right approach to support oauth. Should it not be clientId and secret? Also storing the token like this will expose it to the frontend (so any grafana role will be able to access token). Think the token should only be added in the grafana data proxy code.

We also need to solve this in the alerting tsdb code

**Comment by bergquist** [comment]
How is Prometheus oauth secured? afaik Prometheus itself does not support authentication. 

In 5.0 you will be able to whitelist cookies that will be sent to the data source. https://github.com/grafana/grafana/commit/cf7a49977f601d684d6df3ce9415f57901e210a9 Would that solve the issue?

**Comment by mrsiano** [comment]
@bergquist 
right,
but this one is more dedicated to openshift solution.
prometheus secured by oauth proxy and tls, see the openshift prometheus deployment:

https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml

Implanted it as a generic, sounds good approach, but I assume it will be better to introduce it by another PR.

**Comment by mrsiano** [comment]
In continuing to https://github.com/grafana/grafana-docker/issues/124 and configuration injection efforts.
openshift prometheus that runs behind oauth proxy needs that token in prometheus/datasource.ts, having a cross site tokens is something we should have as future task i guess?!
but on the other hand, token might be not useful for other datasources.

any chance to approve this PR meanwhile?!

**Comment by mrsiano** [comment]
I forgot to mention that I'm using grafna:master
I've injected the prometheus datasource that carries the oauth token, but it didnt work since it requires this PR work.

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana. We have decided not to merge this PR but we do want to solve the underlying problem. We really want to avoid solving problems that all datasources suffer from only for one datasource. Diverging datasources is bad from a maintainability point of view which I'm sure you understand since you work for the biggest open source company in the world :) 

I've created a new issue where I describe how we want this to be implemented. If you are willing to do that I will make sure to put aside time to give you feedback as fast as I can. As much as I want to solve this problem, it cannot be solved at the cost of maintainability. 

New issue https://github.com/grafana/grafana/issues/10971

**Pull request closed without merging**
