### PR TITLE
TableNG: Multi-column sorting

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This PR introduces a multi-column sorting feature and resets the sorting state.

https://github.com/user-attachments/assets/16dbcd7b-213a-4cbf-9020-fa563f7e1d2d

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/94777

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by staton-hyse11** [comment]
Removing the combo-key is a nice feature and removes some hidden functionality — this points at act 3 users. I think an improvement can be made by limiting this 2 columns and disabling or adding some sort of context of the feature limitations. Similar to what GitHub does here:
image

**Comment by drew08t** [comment]
Can we connect this PR to this issue? https://github.com/grafana/grafana/issues/94777

**Comment by Develer** [comment]
> Can we connect this PR to this issue? https://github.com/grafana/grafana/issues/94777

yes, we can 😄

**Review by drew08t — APPROVED** [review]
LGTM, perhaps we can circle back in Phase 2 and update the comments a bit to make it a bit more clear how this works.

**Pull request merged**
