### PR TITLE
update bump-version.yml

### LINKED ISSUE #31456: CI/Release: Ensure correct version in package.json is present before proceding with a release (when pushing a tag)
**What would you like to be added**:

Add a check in the release process that at the very beginning checks that the NPM package version bump has happened and matches the tag just pushed.

**Why is this needed**:
It might happen that we push a release tag without having run the bump version GitHub action. this causes the whole CI to release a new Grafana version but npm packages won't get published to NPM/GitHub because `package.json`s are not updated.

Therefore we'll be forced to run the version bump, release npm packages manually, remove the wrong tag and create a new one.

This will cause a new release to trigger, so we also have to remeber to stop the release process as we don't want to perform an actual release.

If we check this at an early stage in the release process we can surface this error earlier and the solution would just be running the version bump action, removing the old tag and pushing a new one, which will trigger the release.

cc. @aknuds1 @jackw @ying-jeanne

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ying-jeanne** [comment]
pull request still on-going, not tested yet.

**Review by aknuds1 — COMMENTED** [review]
Is there a particular reason why this is implemented as a GitHub workflow? The solution discussed during the meeting was to add a test to the Drone pipeline(s). I think regardless of any GitHub workflow, that such a test would be good to have in the Drone pipeline(s).

**Review by torkelo — APPROVED** [review]
Looks ok, but wondering if this is not easier to make part of the action code instead, and would then be a bit easier to test. 

https://github.com/grafana/grafana-github-actions/blob/main/bump-version/index.ts#L21

**Review by aknuds1 — COMMENTED** [review]
Which version does this workflow test? The one in the package.json files, or the tagged version?

**Pull request merged**
