### PR TITLE
Chore: Remove `react-popper` from `DataLinkInput` and `SuggestionsInput`

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- uses `@floating-ui/react` in `DataLinkInput`
- uses `@floating-ui/react` in `SuggestionsInput`

**Why do we need this feature?**

- so we can standardise on `@floating-ui/react` for our popover needs

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

how to test:
- `DataLinkInput`
  - create a panel, go to edit view
  - click `Add data link`
  - type $ in the url field
- `SuggestionsInput`
  - create a dashboard
  - add some variables
  - add the `Limit` transformation
  - type $ in the limit field 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by eledobleefe** [comment]
I tested this on local and it caught my eye that it is using 'Roboto' instead of 'Inter' 🤔 Shouldn't we always have 'Inter'?
Captura de pantalla 2024-02-09 a las 11 51 18

**Comment by eledobleefe** [comment]
> I tested this on local and it caught my eye that it is using 'Roboto' instead of 'Inter' 🤔 Shouldn't we always have 'Inter'? Captura de pantalla 2024-02-09 a las 11 51 18

It wants a monospace font and 'Inter' does not have a monospace variant 👌

**Review by joshhunt — APPROVED** [review]
Tested, looks good.

Did spot one edge case where on small screens the popover extends off the screen with no way to get it all into view. The previous implementation also did this, so this is not a regression, so I think this is still fine to ship.

image

If you're interested, I think maybe the `size` middleware could be used to address this https://floating-ui.com/docs/size

**Comment by ashharrison90** [comment]
> Tested, looks good.
> 
> Did spot one edge case where on small screens the popover extends off the screen with no way to get it all into view. The previous implementation also did this, so this is not a regression, so I think this is still fine to ship.
> 
> image
> 
> If you're interested, I think maybe the `size` middleware could be used to address this https://floating-ui.com/docs/size

will leave this for a follow up PR 👍

**Pull request merged**
