### PR TITLE
GrafanaUI: Implement new component Toggletip

### LINKED ISSUE #63494: Implementation of new component Toggletip
**Why is this component needed**:

___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
- Cloud Home Admin plugin
- SLO Guidance
___
- [x] Post screenshots possible.
- [x] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [x] Component has a story in Storybook.
- [x] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [x] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**

- [x] Properties are documented.
- [x] Use cases are described.
- [x] Code examples for the different use cases.
- [x] Dos and don'ts.
- [x] Styling guidelines, specific color usage (if applicable).

### PR DESCRIPTION
**Pull request by yduartep**
**What is this feature?**

Toggletips, provide contextual support for users when needed and are persistent until a user takes action to dismiss them by clicking on x (close button).

**Why do we need this feature?**

It's used when users need further context to understand or learn a topic and when an interactive element must be placed within the popover.

**Who is this feature for?**

This feature is for any kind of user.

**Special notes for your reviewer**:
The toggletip will looks like this:
Screenshot 2023-02-21 at 13 00 04

### CODE REVIEW

**Comment by yduartep** [comment]
@mckn and @JoaoSilvaGrafana I had to create a new branch and a new PR to solve the problem with the license/cla check. Could you approve again the PR please?

**Comment by mckn** [comment]
> @mckn and @JoaoSilvaGrafana I had to create a new branch and a new PR to solve the problem with the license/cla check. Could you approve again the PR please?

Ah - usually it get resolved by close/re-open the PR. But I can approve this one instead. No worries.

**Review by mckn — APPROVED** [review]
LGTM!

**Review by JoaoSilvaGrafana — APPROVED** [review]
👍

**Pull request merged**
