### PR TITLE
Dashboards: Migrate from aria-label e2e selectors to data-testid

### PR DESCRIPTION
**Pull request by khushijain21**
Part of https://github.com/grafana/grafana/issues/78409

Corrects following files
1 issue in public/app/features/dashboard/components/PanelEditor/VisualizationSelectPane.tsx
2 issues in public/app/features/dashboard/components/SaveDashboard/SaveDashboardButton.tsx
3 issues in public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx

Corrected corresponding tests also

### CODE REVIEW

**Comment by khushijain21** [comment]
@joshhunt any update?

**Comment by ivanortegaalba** [comment]
@khushijain21 can you sign the CLA? Thank you!

https://cla-assistant.io/grafana/grafana?pullRequest=82156

**Comment by khushijain21** [comment]
@ivanortegaalba can you check now?

**Comment by ivanortegaalba** [comment]
Still not signed. Can you access to the following link https://cla-assistant.io/grafana/grafana?pullRequest=82156 ?

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Pull request closed without merging**
