### PR TITLE
Database: Update the xorm dependency to v0.8.1

### PR DESCRIPTION
**Pull request by novalagung**
**What this PR does / why we need it**:
Upgrade xorm to 0.8.1.

The required dependency xorm is moved into gitea and the module name is changed. this causing go get on grafana generate an error

```bash
$ go get -u github.com/grafana/grafana/pkg/tsdb
go: finding github.com/grafana/grafana v6.1.6+incompatible
go: downloading github.com/grafana/grafana v6.1.6+incompatible
...
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: extracting github.com/teris-io/shortid v0.0.0-20171029131806-771a37caa5cf
go: extracting golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: github.com/grafana/grafana/pkg/tsdb imports
        github.com/go-xorm/core: github.com/go-xorm/core@v0.6.3: parsing go.mod:
        module declares its path as: xorm.io/core
                but was required as: github.com/go-xorm/core
```

### CODE REVIEW

**Comment by aknuds1** [comment]
Thanks, I will have a look at it.

**Comment by aknuds1** [comment]
@novalagung Would you be able to fix the failing tests?

**Comment by novalagung** [comment]
@aknuds1 sure

**Comment by novalagung** [comment]
@aknuds1 just pushed some updates. all tests are passed now

**Comment by aknuds1** [comment]
@novalagung Great, how did you fix the tests? I can't tell from the diff.

**Comment by novalagung** [comment]
@aknuds1 actually my changes did not touch the test codes at all. I only modified the go dot files and import paths. but somehow it cause the test to fail.

Then I performed the `go mod tidy && go mod vendor` again, push it and the test result back to normal (all passed)

**Comment by novalagung** [comment]
@aknuds1 I found some uncommitted changes after my last `go mod vendor` command. likely I forgot to commit those remaining files.

**Comment by aknuds1** [comment]
@novalagung I found that the very last version of xorm (0.8.2) causes tests to fail. I am able to upgrade to 0.8.1 though, while your PR is on 0.8.0. I'm going to push my changes to your branch.

**Comment by novalagung** [comment]
@aknuds1 sure, thank you

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by aknuds1** [comment]
I'd like to hear from my team mates before merging it, hopefully they can chime in.

**Comment by aknuds1** [comment]
@novalagung I'm unable to reproduce your issue BTW:
```
➜  ~ go get -u github.com/grafana/grafana/pkg/tsdb 
➜  ~ 
```

**Comment by novalagung** [comment]
the error only occur when `go get` performed inside go module.

```bash
➜  ~ mkdir app
➜  ~ cd app
➜  ~ go mod init app
➜  ~ go get -u github.com/grafana/grafana/pkg/tsdb

go: finding github.com/grafana/grafana/pkg latest
go: finding github.com/grafana/grafana/pkg/tsdb latest
...
go: github.com/grafana/grafana/pkg/tsdb imports
        github.com/go-xorm/core: github.com/go-xorm/core@v0.6.3: parsing go.mod:
        module declares its path as: xorm.io/core
                but was required as: github.com/go-xorm/core
```

**Comment by aknuds1** [comment]
@marefr What's your take on this, since you said there have been troubles upgrading xorm in the past. Would you want for this PR to upgrade only to the first xorm version (0.8.0) after their module path changed (to xorm.io/xorm)?

**Comment by marefr** [comment]
@aknuds1 I'm a bit skeptic accepting this for the sake of supporting using tsdb package as dependency since there's not a problem currently for Grafana . We have had a lot of problems related to upgrading xorm historically with hidden breaking changes and upgrading needs detailed comparison/review of all their changes. If you still want to upgrade I agree that upgrading to the lowest version first is the way to go, but still detailed comparison/review of all their changes (all xorm packages that Grafana uses) is needed.

**Comment by marefr** [comment]
@novalagung out of curiosity what are you using Grafana's tsdb package for?

**Comment by aknuds1** [comment]
@marefr Thanks for the clarification! I guess we should make it a future task for ourselves to go through the paces of upgrading xorm, including reviewing and testing. At the time being, I figure it's not enough of a priority.

**Comment by novalagung** [comment]
@marefr actually I didn't use tdsb package exclusively on my work. I found out about the issue when I was stumble upon in stackoverflow, looking for recent unanswered questions. I found the issue and then decide to test it.

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
I merged with latest Grafana master and pushed to your repo. Will merge it once the checks finish :)

**Review by marefr — APPROVED** [review]
LGTM

**Comment by novalagung** [comment]
@marefr @aknuds1 thank you

**Comment by marefr** [comment]
@novalagung Thank you for contributing to Grafana!

**Pull request merged**
