### PR TITLE
support json format templating

### LINKED ISSUE #15291: [Feature Request] json variable formatting
The input template variable.
var => `foo,bar,baz`.

The result of `${var:json}`.
`["foo", "bar", "baz"]`.

Some of CloudWatch template query take json input.
I want to use this feature to change input by other template variable.

### PR DESCRIPTION
**Pull request by mtanda**
Fixes #15291

### CODE REVIEW

**Comment by mtanda** [comment]
@marefr Would you check this?
I describe use case in https://github.com/grafana/grafana/issues/15291 .

**Comment by marefr** [comment]
Sure, will let someone else with greater knowledge of template variable interpolation formats review this, but one thing I can see is that documentation needs to be updated - both [variables](http://docs.grafana.org/reference/templating/#advanced-formatting-options) and an example of how to use this with Cloudwatch in the [Cloudwatch documentation](http://docs.grafana.org/features/datasources/cloudwatch/#using-aws-cloudwatch-in-grafana) would be nice.

**Comment by mtanda** [comment]
I got it, I'll update doc in this PR.

**Comment by torkelo** [comment]
This could be useful. Great PR @mtanda , we will merge after some docs ! :heart:

**Comment by mtanda** [comment]
Thanks for review, I updated the docs 😄

**Pull request merged**
