### PR TITLE
FieldDisplay: move threshold and mapping to Field

### PR DESCRIPTION
**Pull request by ryantxu**
This is an alternative to #16925, helps #16912

This PR moves `thresholds[]` and `mappings[]` from FieldDisplay to the Field interface.  This will allow the mappings and thresholds to be managed at the datasource *or* the panel.

This also:
* drops `index` field on Threshold and uses the order to define the order.  
* explicitly assumes first value is -Infinity (previously set with the editor)
* moves the null value support (-Infinity in JSON) out of PanelModel and into fieldDisplay

NOTE:  dropping `index` is not necessary, but bothered me and I had already done the work in  #16925

### CODE REVIEW

**Comment by ryantxu** [comment]
@torkelo -- now that we are on a 6.4 branch, I think this is ready for a more serious look.

I apologise that this PR is really two things:
1. move threshold & mapping to Field
2. rework threshold to use array index rather than `index` field.

**Comment by torkelo** [comment]
Code looks good, but testing it found an issue with Bar Gauge. 

Check for exampel the Bar Gauge Demo Dashboard (provisioned by devenv setup)

Or use this panel json:

```json
{
  "datasource": "gdev-testdata",
  "gridPos": {
    "h": 10,
    "w": 16,
    "x": 0,
    "y": 7
  },
  "id": 4,
  "links": [],
  "options": {
    "fieldOptions": {
      "calcs": [
        "mean"
      ],
      "defaults": {
        "decimals": null,
        "max": 100,
        "min": 0,
        "unit": "celsius"
      },
      "override": {},
      "values": false,
      "default": {
        "mappings": [],
        "thresholds": [
          {
            "value": null,
            "color": "blue"
          },
          {
            "value": 20,
            "color": "green"
          },
          {
            "value": 40,
            "color": "orange"
          },
          {
            "value": 80,
            "color": "red"
          }
        ],
        "decimals": null,
        "max": 100,
        "min": 0,
        "unit": "celsius"
      }
    }
  },
  "pluginVersion": "6.4.0-pre",
  "targets": [
    {
      "alias": "Inside",
      "refId": "H",
      "scenarioId": "csv_metric_values",
      "stringInput": "100,100,100"
    },
    {
      "alias": "Outhouse",
      "refId": "A",
      "scenarioId": "random_walk"
    },
    {
      "alias": "Area B",
      "refId": "B",
      "scenarioId": "random_walk"
    },
    {
      "alias": "Basement",
      "refId": "C",
      "scenarioId": "random_walk"
    },
    {
      "alias": "Garage",
      "refId": "D",
      "scenarioId": "random_walk"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Gradient mode",
  "type": "bargauge"
}
```

**Comment by ryantxu** [comment]
@torkelo -- oops:
image

also looks like the migration for gauge was missing some settings

**Review by torkelo — APPROVED** [review]
Seems to be working now!

**Pull request merged**
