### PR TITLE
Traces: update metrics

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:

This PR updates some of our spanmetric's metric names and labels based on the [work done here](https://github.com/grafana/tempo/pull/1478#event-6784262255). These changes were made to match OTel's spanmetrics spec.

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by connorlindsey — APPROVED** [review]

**Review by mapno — APPROVED** [review]
LGTM

**Review by yvrhdn — COMMENTED** [review]
This changes look good to me. I'm not able to test it locally though, for some reason the go process within `make run` keeps crashing with a segmentation fault, even though I can run Grafana from main.

**Comment by connorlindsey** [comment]
@kvrhdn What's the make run error? Can message me in Slack as I was having similar issues recently

**Comment by kvrhdn** [comment]
> @kvrhdn What's the make run error? Can message me in Slack as I was having similar issues recently

I've attached them here. I see Mario has also reviewed it in the meantime, so I'm fine with merging this 👍🏻 

<details>
  <summary>Logs from `make run`</summary>
  
```
go build -ldflags -w -X main.version=9.0.0-pre -X main.commit=247205eaf8 -X main.buildstamp=1655731396 -X main.buildBranch=joey/traces-apm-update-metrics -o ./bin/grafana-cli ./pkg/cmd/grafana-cli
[Bra] 06-21 15:59:50 [DEBUG] Running: [GO_BUILD_DEV=1 LC_CTYPE=UTF-8 SHELL=/bin/zsh _=/usr/bin/make __CFBundleIdentifier=com.googlecode.iterm2 INFOPATH=/opt/homebrew/share/info: PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Users/koenraad/.cargo/bin:/Users/koenraad/go/bin:/Users/koenraad/Downloads/shellcheck-v0.7.2:/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin LSCOLORS=Gxfxcxdxbxegedabagacad SPACESHIP_VERSION=3.11.2 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nIHiIx42us/Listeners PWD=/Users/koenraad/Repositories/grafana/grafana HOMEBREW_CELLAR=/opt/homebrew/Cellar MANPATH=/opt/homebrew/share/man:: HOME=/Users/koenraad LOGNAME=koenraad ZSH=/Users/koenraad/.oh-my-zsh XPC_FLAGS=0x0 COLORTERM=truecolor SHLVL=1 USER=koenraad TERM_SESSION_ID=w0t2p0:4692D65D-6353-4066-BB87-77858E1A9612 LESS=-R OLDPWD=/Users/koenraad/Repositories/grafana/cloud-docs TERM_PROGRAM=iTerm.app TMPDIR=/var/folders/fv/6b9k_kqs56lb0dzf91xtsnsr0000gn/T/ LC_TERMINAL=iTerm2 MAKEFLAGS= MFLAGS= TERM_PROGRAM_VERSION=3.4.15 XPC_SERVICE_NAME=0 LC_TERMINAL_VERSION=3.4.15 HOMEBREW_PREFIX=/opt/homebrew ITERM_SESSION_ID=w0t2p0:4692D65D-6353-4066-BB87-77858E1A9612 HOMEBREW_REPOSITORY=/opt/homebrew COLORFGBG=7;0 __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0 COMMAND_MODE=unix2003 ITERM_PROFILE=My profile PAGER=less SPACESHIP_ROOT=/Users/koenraad/.oh-my-zsh/custom/themes/spaceship-prompt GPG_TTY=/dev/ttys002 TERM=xterm-256color STARSHIP_COMNFIG=/Users/koenraad/.config/starship.toml MAKELEVEL=1] make [build-server]
build server
go run build.go -dev  build-server
Version: 9.0.0, Linux Version: 9.0.0, Package Iteration: 1655819993pre
building grafana-server ./pkg/cmd/grafana-server
go build -ldflags -w -X main.version=9.0.0-pre -X main.commit=247205eaf8 -X main.buildstamp=1655731396 -X main.buildBranch=joey/traces-apm-update-metrics -o ./bin/grafana-server ./pkg/cmd/grafana-server
[Bra] 06-21 15:59:57 [DEBUG] Running: ./bin/grafana-server [-packaging=dev cfg:app_mode=development]
unexpected fault address 0x4f9f9c3
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x4f9f9c3 pc=0x1026ea648]

goroutine 1 [running, locked to thread]:
runtime.throw({0x1048b01ee?, 0x105a66310?})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/panic.go:992 +0x50 fp=0x1400018a850 sp=0x1400018a820 pc=0x102652700
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/signal_unix.go:825 +0x1a4 fp=0x1400018a880 sp=0x1400018a850 pc=0x102669814
reflect.name.readVarint(...)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/reflect/type.go:501
reflect.name.name({0x1400018a8f8?})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/reflect/type.go:528 +0x58 fp=0x1400018a8b0 sp=0x1400018a890 pc=0x1026ea648
reflect.(*structType).Field(0x105896860, 0x4)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/reflect/type.go:1248 +0x84 fp=0x1400018a950 sp=0x1400018a8b0 pc=0x1026ecfd4
reflect.(*rtype).Field(0x1050c488e?, 0x7?)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/reflect/type.go:973 +0x50 fp=0x1400018aa60 sp=0x1400018a950 pc=0x1026ebe20
encoding/gob.newTypeObject({0x1050cd0fc, 0x8}, 0x1400018ad58?, {0x105a811c8, 0x105896860})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:526 +0xc54 fp=0x1400018acc0 sp=0x1400018aa60 pc=0x102cc6c54
encoding/gob.getType({0x1050cd0fc, 0x8}, 0x1400018ad68?, {0x105a811c8, 0x105896860})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:598 +0x7c fp=0x1400018ad30 sp=0x1400018acc0 pc=0x102cc71dc
encoding/gob.getBaseType({0x1050cd0fc, 0x8}, {0x105a811c8?, 0x105896860?})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:585 +0x50 fp=0x1400018ad70 sp=0x1400018ad30 pc=0x102cc7120
encoding/gob.buildTypeInfo(0x14000060d00, {0x105a811c8, 0x105896860})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:715 +0x194 fp=0x1400018aeb0 sp=0x1400018ad70 pc=0x102cc79a4
encoding/gob.getTypeInfo(0x14000060d00)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:702 +0xe0 fp=0x1400018af10 sp=0x1400018aeb0 pc=0x102cc77f0
encoding/gob.mustGetTypeInfo({0x105a811c8?, 0x105896860?})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:766 +0x2c fp=0x1400018af50 sp=0x1400018af10 pc=0x102cc817c
encoding/gob.init()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/encoding/gob/type.go:259 +0x1da8 fp=0x1400018b070 sp=0x1400018af50 pc=0x102cca898
runtime.doInit(0x1071f3fa0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6222 +0x138 fp=0x1400018b1b0 sp=0x1400018b070 pc=0x102662898
runtime.doInit(0x1071fa000)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b2f0 sp=0x1400018b1b0 pc=0x1026627d0
runtime.doInit(0x107211ac0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b430 sp=0x1400018b2f0 pc=0x1026627d0
runtime.doInit(0x1071e5e00)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b570 sp=0x1400018b430 pc=0x1026627d0
runtime.doInit(0x1072077a0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b6b0 sp=0x1400018b570 pc=0x1026627d0
runtime.doInit(0x107200180)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b7f0 sp=0x1400018b6b0 pc=0x1026627d0
runtime.doInit(0x1072070a0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018b930 sp=0x1400018b7f0 pc=0x1026627d0
runtime.doInit(0x10720a580)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018ba70 sp=0x1400018b930 pc=0x1026627d0
runtime.doInit(0x107203f20)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018bbb0 sp=0x1400018ba70 pc=0x1026627d0
runtime.doInit(0x10721eda0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018bcf0 sp=0x1400018bbb0 pc=0x1026627d0
runtime.doInit(0x107204ee0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018be30 sp=0x1400018bcf0 pc=0x1026627d0
runtime.doInit(0x1071e0100)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:6199 +0x70 fp=0x1400018bf70 sp=0x1400018be30 pc=0x1026627d0
runtime.main()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:233 +0x1fc fp=0x1400018bfd0 sp=0x1400018bf70 pc=0x102654bec
runtime.goexit()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 +0x4 fp=0x1400018bfd0 sp=0x1400018bfd0 pc=0x1026860d4
[Bra] 06-21 15:59:58 [ WARN] Fail to execute command: ./bin/grafana-server [-packaging=dev cfg:app_mode=development] - exit status 2
^Cmake: *** [run] Interrupt: 2
```

</details>

**Comment by connorlindsey** [comment]
Hmm not sure, maybe just a weird mismatch between branches/go versions or something.

**Pull request merged**
