### PR TITLE
CherryPicks 7.0.1

### PR DESCRIPTION
**Pull request by hugohaggmark**
grafana git:(cp-7.0.1) ./node_modules/.bin/grafana-toolkit cherrypick
Running in local/linked mode
Running Cherry pick task task
  --------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Dashboard/Links: Fixes open in new window for dashboard link, (#24772), merge-sha: 7b18b101b42beeffc0d8fda0611f9a54fa0707d5
  * Search: make anchor full-height, (#24783), merge-sha: 7b6deef46d133f6c3c21d97d57d135c373f3cf57
  * TablePanel: Adding sort order persistance, (#24705), merge-sha: b709f6ad7139dffe460b49aaa7271879a14a5588
  * Datasource/CloudWatch: Makes CloudWatch Logs query history more readable, (#24795), merge-sha: 2f01f1320f4b50023a3a0f571599ccf8331c7d85
  * Explore: fix undo in query editor, (#24797), merge-sha: 29afc2feb80fe00886f10f87f7c12f8e85d19bc3
  * Transforms: Allow custom number input for binary operations, (#24752), merge-sha: 793299af147edbb275af13637fa0260085473561
  * Dashboard/Links: Fixes dashboard links by tags not working, (#24773), merge-sha: e2368e623e3a9f539e674cc3802287395da2c9b6
  * PanelInspect: makes sure Data display options are visible, (#24902), merge-sha: 5a6026a8c0f2adaed998d6d8c76574015fba5d94
  * LogsPanel: Fix scrollbar, (#24850), merge-sha: 4f6fb2d46e5e6825abb38aea9dddcbdf0036d98d
  * Fix: adding missing icons in the elastic query editor and the single stat editor., (#24914), merge-sha: 731deb96286c0251f8a306c84b54034fd54b1efc
  * Explore: Fix wrap lines toggle for results of queries with filter expression, (#24915), merge-sha: 966b0a97b1767e9e9f89c45c1ba9a6bf1ab51165
  * Datasource/CloudWatch: Field suggestions no longer limited to prefix-only, (#24855), merge-sha: 0f174de760742a5834655e08bb334ebe7814cf70
  * PanelEditor Fix missing labels and description if there is only single option in category, (#24905), merge-sha: bb099cb141a0155ef9f60720bfad238c85275bb6
  * Panel: shows correct panel menu items in view mode, (#24912), merge-sha: 460847f3edb255ad8662f3f96b776769f165a496
  * PanelInspector: hides unsupported data display options for Panel type, (#24918), merge-sha: 0b5d8187715005c9f0e969224ca44c137d9ab0d4
  * Graph: Legend decimals now work as expected, (#24931), merge-sha: 8aedf8113371f933b8afcafe7a392641fda69f47
  * Dashboard: Render PanelChrome on refresh, (#24940), merge-sha: 77633db00e24036089c39b2b889b9846c2c80d2b
  * Datasource/CloudWatch: Better handling of stats grouping, (#24789), merge-sha: e1f4287f70d4169fb25723a8b70e9ebf8de9c1e2
  * Prometheus: Fix recording rules expansion, (#24977), merge-sha: 4d18bda2e1ff4237a377a4b4e35af0de79d40733
  * Updates broken link to time range docs, (#25008), merge-sha: b5bf54f5ac2abf9073ddb64947df339a733b7fe7
  * LoginPage: Fix hover color for service buttons, (#25009), merge-sha: 84031649e3099948b71e25078090c269df555cc3
  * PanelMenu: Make menu disappear on button press, (#25015), merge-sha: 5f4526ca64302fc8ffd72a4a66d0d11ae6cf9a2e
  * Explore: refactors LogRowContextProvider to get rid of unnecessary dimensions, (#24899), merge-sha: 8c1307e704891cbb964f4caf65894d6ac1dfeeec
  * DataLinks: Bring back variables interpolation in title , (#24970), merge-sha: ad870c07cf7d2aa9215fc32de6d5c991ef76b082
  * Download CSV: format the dates, (#24992), merge-sha: 81d1f6653f70cfbdd2574bd9441ee09138dd7efc
  * Stackdriver: Fix creating Service Level Objectives (SLO) datasource query variable, (#25023), merge-sha: a1ee62877ee7ed173d2716ea369fe58836c107c6
  * Explore: fix word break in type head info, (#25014), merge-sha: dca03a3b4a57ac570ba9e6b14468500e80a5c5bf
  * Organize transformer: Use display name in field order comparer, (#24984), merge-sha: 9a59f387d949eeb986af5ef29dd67bfb4684edaf
  * Loki/Prometheus: updates addLabelToQuery method to prevent it from adding labels outside of selector when using Loki datasource, (#25059), merge-sha: 60e7b63c33d81fb680166f2234bd87d42bae03b4
  * MoveDashboard: Fix for moving dashboard caused all variables to be lost, (#25005), merge-sha: 3a469f6ca25fa7bb56c58f9921dfe02e82df4d26
  * PanelEditor: Overrides name matcher still show all original field names even after Field default display name is specified , (#24933), merge-sha: 923faf78f188d66a7eae25148e66b07e137a62ad
  * Transform: Display correct field name when using reduce transformation, (#25068), merge-sha: 880a11773b19d07d1a23ebd6749a76947c8f015a
  * Table: Make last cell value visible when right aligned, (#24921), merge-sha: 0da72131b9d1d0962e63fec97dd263a6052433a9
  * DashboardLinks: variables are resolved and limits to 100, (#25076), merge-sha: 83d933d0100297f0af73fdb55193922f933de12a
  * Explore/Table: Keep existing field types if possible, (#24944), merge-sha: f5a9b23d83297f2acb4d2c6d8707a6387ed15400
  * Cloudwatch: Fix AWS WAF and AWS DDoSProtection metrics, (#25071), merge-sha: 1e4e2642bf8652251088f75b1f8d8150ae716575
  * Chore: fixes throwing errors on 200 response with influxdb datasource, (#24848), merge-sha: 7bf5b395b653a80e3420a0d1e55ab6cacfdc35fb
  * Postgres: Fix add button, (#25087), merge-sha: 231a32c4a3dfa653e5fe3650502453822e8586ea
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x 7b18b101b42beeffc0d8fda0611f9a54fa0707d5
  git cherry-pick -x 7b6deef46d133f6c3c21d97d57d135c373f3cf57
  git cherry-pick -x b709f6ad7139dffe460b49aaa7271879a14a5588
  git cherry-pick -x 2f01f1320f4b50023a3a0f571599ccf8331c7d85
  git cherry-pick -x 29afc2feb80fe00886f10f87f7c12f8e85d19bc3
  git cherry-pick -x 793299af147edbb275af13637fa0260085473561
  git cherry-pick -x e2368e623e3a9f539e674cc3802287395da2c9b6
  git cherry-pick -x 5a6026a8c0f2adaed998d6d8c76574015fba5d94
  git cherry-pick -x 4f6fb2d46e5e6825abb38aea9dddcbdf0036d98d
  git cherry-pick -x 731deb96286c0251f8a306c84b54034fd54b1efc
  git cherry-pick -x 966b0a97b1767e9e9f89c45c1ba9a6bf1ab51165
  git cherry-pick -x 0f174de760742a5834655e08bb334ebe7814cf70
  git cherry-pick -x bb099cb141a0155ef9f60720bfad238c85275bb6
  git cherry-pick -x 460847f3edb255ad8662f3f96b776769f165a496
  git cherry-pick -x 0b5d8187715005c9f0e969224ca44c137d9ab0d4
  git cherry-pick -x 8aedf8113371f933b8afcafe7a392641fda69f47
  git cherry-pick -x 77633db00e24036089c39b2b889b9846c2c80d2b
  git cherry-pick -x e1f4287f70d4169fb25723a8b70e9ebf8de9c1e2
  git cherry-pick -x 4d18bda2e1ff4237a377a4b4e35af0de79d40733
  git cherry-pick -x b5bf54f5ac2abf9073ddb64947df339a733b7fe7
  git cherry-pick -x 84031649e3099948b71e25078090c269df555cc3
  git cherry-pick -x 5f4526ca64302fc8ffd72a4a66d0d11ae6cf9a2e
  git cherry-pick -x 8c1307e704891cbb964f4caf65894d6ac1dfeeec
  git cherry-pick -x ad870c07cf7d2aa9215fc32de6d5c991ef76b082
  git cherry-pick -x 81d1f6653f70cfbdd2574bd9441ee09138dd7efc
  git cherry-pick -x a1ee62877ee7ed173d2716ea369fe58836c107c6
  git cherry-pick -x dca03a3b4a57ac570ba9e6b14468500e80a5c5bf
  git cherry-pick -x 9a59f387d949eeb986af5ef29dd67bfb4684edaf
  git cherry-pick -x 60e7b63c33d81fb680166f2234bd87d42bae03b4
  git cherry-pick -x 3a469f6ca25fa7bb56c58f9921dfe02e82df4d26
  git cherry-pick -x 923faf78f188d66a7eae25148e66b07e137a62ad
  git cherry-pick -x 880a11773b19d07d1a23ebd6749a76947c8f015a
  git cherry-pick -x 0da72131b9d1d0962e63fec97dd263a6052433a9
  git cherry-pick -x 83d933d0100297f0af73fdb55193922f933de12a
  git cherry-pick -x f5a9b23d83297f2acb4d2c6d8707a6387ed15400
  git cherry-pick -x 1e4e2642bf8652251088f75b1f8d8150ae716575
  git cherry-pick -x 7bf5b395b653a80e3420a0d1e55ab6cacfdc35fb
  git cherry-pick -x 231a32c4a3dfa653e5fe3650502453822e8586ea

➜  grafana git:(cp-7.0.1)

**Also added to fix build errors in CircleCI**
* Chore: Add IAM to list of ignored terms for codespell, (#25013), merge-sha: 4f1bbdfc0a8bec2dd2e961cf76ee6c7d2246150a
git cherry-pick -x 4f1bbdfc0a8bec2dd2e961cf76ee6c7d2246150a

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Review by dprokop — APPROVED** [review]
LGTM

**Review by papagian — APPROVED** [review]
LGTM

**Review by aknuds1 — APPROVED** [review]
LGTM (verified with tool)

**Pull request merged**
