### PR TITLE
Explore: use GrafanaTheme2 (AdHocFilter component)

### LINKED ISSUE #37389: Explore: all components should use GrafanaTheme2
This is a plan to refactor all components in explore to make sure they use GrafanaTheme2 instead of the old GrafanaTheme.

### Components that still use GrafanaTheme

- [x] AdHocFilter (PR: #37434)
- [x] Explore (PR: #37445)
- [x] ExploreGraphNGPanel (PR: #37450)
- [x] LiveLogs (PR: #37452)
- [x] LiveTailButton (PR: #37516)
- [x] Logs (PR: #37305)
- [x] LogsNavigation (PR: #37518)
- [x] LogsNavigationPages (PR: #37523)
- [x] MetaInfoText (PR: #37539)
- [x] NoDataSourceCallToAction (PR: #37542)
- [x] SecondaryActions (PR: #37543)

### PR DESCRIPTION
**Pull request by olbo98**
**What this PR does / why we need it**:
This PR is a part of #37389 to refactor all components in explore to use GrafanaTheme2

**Which issue(s) this PR fixes**:

Fixes # 37389

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gabor** [comment]
@olbo98 hmm.. i checked where this is used and it seems it is only used in https://github.com/grafana/grafana/blob/main/public/app/features/explore/AdHocFilterField.tsx , which is only used in https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/influxdb/components/InfluxLogsQueryField.tsx which is not used anywhere ... so maybe we can just delete this code. i will double check this and come back 😄

**Comment by ifrost** [comment]
Yeah, I think it was refactored in https://github.com/grafana/grafana/pull/25890/files#r449191902 but the component was not removed.

**Review by ifrost — CHANGES_REQUESTED** [review]
I think you can remove the component with all hanging parents 👍

**Comment by olbo98** [comment]
> Yeah, I think it was refactored in https://github.com/grafana/grafana/pull/25890/files#r449191902 but the component was not removed.

@ifrost So i can just go ahead and delete the whole file?

**Comment by olbo98** [comment]
@ifrost okay nice! 👍

**Review by ifrost — APPROVED** [review]

**Pull request merged**
