### PR TITLE
Fix famous TypeError: Cannot read properties of undefined (reading '…

### PR DESCRIPTION
**Pull request by msveshnikov**
…toLowerCase')

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by itsmylife** [comment]
Thanks for the contribution. But this is only attempting to fix the symptom and not the cause. [This PR](https://github.com/prometheus/prometheus/pull/13633) will fix the issue on the Prometheus side. In the meantime, people can downgrade to a version below `v2.50.0`. Soon we will have a [new version of Prometheus](https://github.com/prometheus/prometheus/pull/13641).

**Comment by msveshnikov** [comment]
Thanks, I downgraded Prometheus but still have this with any metric:
Screenshot_2024-02-26-11-29-34-120_com android chrome

I would say if you start using ?. operator you should stick to ?. otherwise this fallback doesn't make sense 

Anyway, should I clean my Prometheus storage after downgrade? Bug is quite nasty and completely blocking me

**Comment by itsmylife** [comment]
I think it is related to the browser cache. Could you please clean it and try it again?

**Comment by msveshnikov** [comment]
Thanks a lot! Now fixed 🥰

**Pull request closed without merging**
