### PR TITLE
Graph: On over highlight series

### PR DESCRIPTION
**Pull request by mtanda**
rebase and little modify https://github.com/grafana/grafana/pull/4599.

### CODE REVIEW

**Comment by torkelo** [comment]
The more I used this feature it feels kind of distracting, it changes the width of the lines drawn and flickers a lot when you move around a dashboard. 

The purpose to isolate or highlight a specific series can be done by clicking or shift clicking on the legend. But I will try it out some more. And would love for others to try it and give feedback.

**Comment by mtanda** [comment]
I try to improve the UX by switching behavior by ctrl key.

But, the flot doesn't pass whether ctrlKey is pressed or not, it is difficult to switch behavior by ctrl key.
https://github.com/grafana/grafana/pull/7224/files#diff-9017b4828a142560a195eaa3fb21a140R134

The original event is lost at here.
https://github.com/grafana/grafana/blob/v4.1.2/public/vendor/flot/jquery.flot.js#L2998

**Comment by torkelo** [comment]
closing this for now. Is there a feature request for this? Might be good to open a feature request with  a video showing it of, if many think this is an good improvement then we can reconsider. 

But having tested it a couple of times I found it mostly distracting, sometimes useful. But trying to keep feature creep low (and not adding unnecessary features)

**Comment by mtanda** [comment]
I open issue.

**Pull request closed without merging**
