### PR TITLE
Enforce domain (#1732)

### PR DESCRIPTION
**Pull request by gummiboll**
Fix for issue #1732, not sure if this should be configurable from the config-file or, as it is now, on by default?

Im a golang noob so all feedback is welcome!

### CODE REVIEW

**Comment by torkelo** [comment]
Why is this important? and if it is, could be handled by nginx?

**Comment by gummiboll** [comment]
Its probably more 'nice to have' rather than 'important' but I think the issuer explained the use-case pretty well and yes, it can be handled by nginx/apache if you have that infront of it.

But tbh, was looking for a easy fix and found that open issue. :)

**Comment by JordanMilne** [comment]
It's important because when internal web applications don't verify that the `Host` header is correct before serving a (possibly sensitive) response, rogue websites may be able to violate same-origin policy and read its pages crossdomain through DNS rebinding attacks. Due to how DNS rebinding attacks work, this mostly matters when anonymous users have access to "interesting" stuff, so it's not as big of an issue for public-facing applications.

[Wikipedia's page on DNS rebinding attacks](https://en.wikipedia.org/wiki/DNS_rebinding#Protection) mentions checking the Host header will fix protect against such attacks.

**Comment by dewski** [comment]
@gummiboll thanks for tackling this :+1:

**Comment by dewski** [comment]
@gummiboll a test would be good to have for this behavior.

**Comment by gummiboll** [comment]
@dewski Not sure if @torkelo wants merge this, but if he does I can make a test for it. :)

**Comment by torkelo** [comment]
merged, refactored a little, added an option to enable this (disabled by default).

```ini
# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false
```

**Pull request merged**
