### PR TITLE
Dashboard: Refactor panel cleanup

### LINKED ISSUE #46510: Dashboard freeze "infinitely" when template variable selected, when time range change or dashboard refreshed
**What happened**:
When dashboard is started all template variables are loaded fast in ~1s (first picture), sometimes might take longer due few larger queries.

Dashboard freeze for few minutes when time range is changed (5m --> 15m) or dashboard is reloaded. 
Dashboard freeze for 1min in one variable list is opened and one variable is selected (variable used on most panels)
Template variables animation "in progress" is shown until query completed. Sometimes few variable stay in "in progress" for 10-15 minutes.

Dashboards contains ~40 templated chained variable. All dependent on job (loaded on dashboard load), some also dependent on other few variables which are used for further filtering. All other variables are refreshed on time range change.

Dashboard panels are located under tens of rows, each rows contain one or more repeating panel utilizing templated variables.
All panels are located inside collapsing rows which often use repeating panels.

All panels are under rows to minimize unnecessary loads while updating time range. Naturally only few are expanded on need based.

Grafana version 8.2.15 works, no freeze. 
Grafana version 8.3.4 - grafana-8.5.0-54667pre, freeze
Grafana 8.3.0Beta1-8.3.3 cannot be properly tested as dashboards load fails to error. Simpler dashboards works
```
Templating init failed Minified Redux error #3; visit https://redux.js.org/Errors?code=3 for the full message or use the non-minified dev environment for full errors.
```

Using inspector/Network the following pattern can be seen.
- complete freeze 10-30s, burst of 20-30 template variable queries in pending (10s-30s)
- After 10-30s the queries exit pending state and completed in ~100ms
- 1-4 new template variable queries in pending state for 10-30s
- After 10-30s the queries exit pending state and completed in ~100ms
- next 1-4 queries template variable 
- until all template variables queried
Some queries fails, when takes too long time. Failure is not due long response time from Prometheus but probably freeze interrupt the query again.

When variable is selected the above pattern repeats 2 times (thus UI freeze for 1min), because only few variables get refreshed I think.
When time range change or dashboard is refreshed the freeze takes 5min because all variables are reloaded.
 
Dashboard launched (~1s), always fast-
image

One variable selected (instead of default all, freeze for 1min. Picture shows first everything freeze for 20s)
image

Dashboard refresh few second after launch
image

After 3min
image

After 5min queries completed
image

Inspector/Performance indicate all +99% time spent on scripting.
Inspector cannot be started during freeze, must be started before, takes very long time to stop after 5min.
Result looks like this 2min after pressing refresh (Windows 8.4.2, separate take, takes 10m to stop, after 5min will never stop)
image

image

**What you expected to happen**:
- All variables should be loaded before starting to refresh panels, should not take more than few second
- Panels under collapsed rows must not be refreshed.
- if some panels are not under collapsing row or row is open the panels should be refreshed only after variables are updated.

**How to reproduce it (as minimally and precisely as possible)**:
Can be simulated with datasource which contains enough metrics/cardinality/labels. Just create tens of "dependent" template variables and tens of rows with collapsing dashboard each using different template variable sets.
Issue can be seen also on smaller dashboards but seems that the larger the number of template/queries under rows the slower and longer the freeze.
I did not find a way to query variables from testData DB.

I suspect this is regression due
Variables: Only update panels that are impacted by variable change. https://github.com/grafana/grafana/pull/39420, [@hugohaggmark](https://github.com/hugohaggmark)

What this PR does / why we need it:
This PR tries to resolve what panels are impacted during a variable change. It takes a naive approach to chained variables and parses the dashboard json in order to resolve the dependencies. This means if a variable query is faulty or if the user cancels the variable query the affected panels for that variable will still be refreshed.

It looks that 
- dashboard json is analyzed too early breaking variable loading
- analysis is too compute intensive eating all threads
- analysis is done done multiple times 
- does not make any sense to analyze dependencies when rows are collapsed.

Dashboards with tens of template variables and tens of rows with collapsing panels could have hundreds or thousands of queries with template variables to be analyzed, might require scanning JSON once per template variable to see if refresh is needed.

I tested another simpler production dashboards which aggregates the alerts from selected time range.
Dashboard has 25 "dependent" template variables which are used to list only variables which are part of alerts and 15 rows with collapsing panels showing then all alerting dashboards. As seen from graph after few variables queried the is 1s freeze between. 1s freeze is probably due json scanning. This hints that quite simple dashboard from data source with large amount of metrics regress clearly. And larger dashboards slow down exponentially making dashboards unusable.

image

Same dashboard refresh when using 8.2.7 (one query is longer and some other are dependent on it)
image

We had to revert 8.3/8.4 Grafana back to 7.5.15 due freeze. Probably due breaking change "Variables: Do not save repeated panels, rows and scopedVars. https://github.com/grafana/grafana/pull/32436, [@torkelo](https://github.com/torkelo)" some dashboards lost their Prometheus data source when opened in 7.5. Will try to fix by migrating to 8.2.15.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.x/8.4.x/8.5.x
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL 7.9, WIndows 10
- User OS & Browser: Chrome
- Grafana plugins: Prometheus
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Refactors panel cleanup so instead of being done on panel unmount, we're more explicit about how and when it occurs.
This was done specifically so cleanup of panels on leaving a dashboard would be batched, rather than dispatching a single action for every panel, which could cause Grafana to hang for a (very) large dashboard.

**Which issue(s) this PR fixes**:
Closes #46510

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
I'm really excited for this. I think the shift here you've made, to be more explicit about when dashboard cleanup happens makes a lot of sense.

**Review by ashharrison90 — APPROVED** [review]
minor nit/question otherwise looks great! 😄 

i did a performance comparison on our horrible dashboard:

| version | results |
| --- | --- |
| v8.2.7 | image |
| main | image |
| this branch | image |

**Review by torkelo — APPROVED** [review]
Looks good!

**Comment by jtorkkel** [comment]
Unfortunately no improvements seen in 8.5.0. dashboard still freeze for minutes.

**Comment by kaydelaney** [comment]
Mistakenly didn't backport this PR, so it seems like it wasn't included in 8.5.0, sorry about that. I'll backport it and it should be in the next patch release.

**Pull request merged**
