### PR TITLE
Karma to Jest: prometheus datasource

### PR DESCRIPTION
**Pull request by tskarhed**
Ref #12224 
Issues with execution order somehow. Try to switch places between the two first `it()`. Then the failing test will pass.

### CODE REVIEW

**Comment by marefr** [comment]
@dehrax Moving response in to beforeEach seems to solve the problem. Seems like response transformer changes the response.

**Comment by dehrax** [comment]
Reponses added to `beforeEach`.

I think this test would be a whole lot better if it tested each method of the class, instead of always running the query and checking the URL. Too many moving parts.

**Comment by marefr** [comment]
> I think this test would be a whole lot better if it tested each method of the class, instead of always running the query and checking the URL. Too many moving parts.

Your welcome to change the the tests as you see fit.

**Review by marefr — CHANGES_REQUESTED** [review]
1. We want to move the _datasource.jest.ts into existing datasource.jest.ts.
2. Some cleanup, remove comments and replace function() with arrow function to be consistent.
3. Are you still planning to make refactoring of tests?

**Review by marefr — APPROVED** [review]

**Pull request merged**
