### PR TITLE
Alerting: Update forking request handlers to use the same errors

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What this PR does / why we need it**:
This PR unifies error handling in "forking" request handlers. It introduces two new package private errors in `api` package and a few methods that produce errors in the correct format and a method that converts errors to HTTP responses. 

Notable changes. Now, if data source is not found by UID taken from the path, the response will be 404 (instead of 400). 

Also, PR removes some duplicate code that verifies the backend type is expected in the request handler. 

### Changelog
- Alerting API returns 404 if datasource mentioned in the URL path does not exist

### CODE REVIEW

**Comment by armandgrillet** [comment]
I have set reviewers manually as we don't do automatic reviewers anymore.

**Review by papagian — COMMENTED** [review]
I think we need to add `404` as a possible response status for the [alertmanager](https://github.com/grafana/grafana/blob/ae7160a094098ae2989e2644df10fc61d24d75b6/pkg/services/ngalert/api/tooling/definitions/alertmanager.go) routes

**Review by papagian — APPROVED** [review]
LGTM

since [api.json](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/api.json) is modified we have to re-generate also [the merged swagger specification](https://github.com/grafana/grafana/blob/main/public/api-merged.json) (that includes both alerting and Grafana routes); to do so you can run:
`rm public/api-merged.json && make public/api-merged.json`

Also it would be nice (not necessarily now) to align this work with [these guidelines](https://github.com/grafana/grafana/blob/main/contribute/architecture/backend/errors.md#declaring-errors) for declaring Grafana errors.

**Comment by yuri-tceretian** [comment]
> since [api.json](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/api.json) is modified we have to re-generate also [the merged swagger specification](https://github.com/grafana/grafana/blob/main/public/api-merged.json) (that includes both alerting and Grafana routes); to do so you can run:
rm public/api-merged.json && make public/api-merged.json


This command generates enormous diff! Something is not right. 

> Also it would be nice (not necessarily now) to align this work with [these guidelines](https://github.com/grafana/grafana/blob/main/contribute/architecture/backend/errors.md#declaring-errors) for declaring Grafana errors.

I will backport this PR to branches that may not have such framework. However, I will create an issue for our team to migrate.

**Comment by yuri-tceretian** [comment]
I opened PR https://github.com/grafana/grafana/issues/53136 to migrate to the new guidelines

**Comment by yuri-tceretian** [comment]
I decided to not backport it and go with changes with a much smaller footprint for 9.1.x and other branches

**Pull request merged**
