### PR TITLE
Plugins: Enable feature toggle angularDeprecationUI by default

### PR DESCRIPTION
**Pull request by xnyo**
**What is this feature?**

Enable feature toggle angularDeprecationUI by default.

**Why do we need this feature?**

Displays warnings on Angular dashboards and panels by default.

**Who is this feature for?**

On-prem Grafana users relying on Angular plugins.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by sympatheticmoose — APPROVED** [review]
Let's go 🚀

**Review by tolzhabayev — APPROVED** [review]

**Comment by CptHolzschnauz** [comment]
How to remove the warning again? angularDeprecationUI  to No?
A short guide would be nice, my dashboards rely on Angular, these warnings are annoying for the end user.
Thx

**Comment by sympatheticmoose** [comment]
@CptHolzschnauz I appreciate this warnings are intrusive. Given the deprecation of Angular and the upcoming change of behaviour where support will be turned off by default, we felt it was better to risk annoyance now than shock later when plugins fail to load in Grafana 11. 

As with any [feature toggle](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/), you can change the behaviour through your [configuration file](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/).

**Comment by xnyo** [comment]
To add on David's answer, you can disable those warnings completely by adding the following to your `config.ini` file:

```ini
[feature_toggles]  
angularDeprecationUI = false
```

Alternatively, you can disable the warnings only for some plugins with:

```ini
[plugins]
hide_angular_deprecation = grafana-polystat-panel,some-other-angular-plugin-id
```

**Comment by CptHolzschnauz** [comment]
> @CptHolzschnauz I appreciate this warnings are intrusive. Given the deprecation of Angular and the upcoming change of behaviour where support will be turned off by default, we felt it was better to risk annoyance now than shock later when plugins fail to load in Grafana 11.
> 
> As with any [feature toggle](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/), you can change the behaviour through your [configuration file](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/).

I do understand your intention but the end user doesn't know what Angular or React is at all. They just see that threatening sign.. Thank you for your answer.

@xnyo Thanks a bunch.

@Grafana : Maybe an addtional line in the config is an idea, also to give an example to the [feature_toggles] section, something like:

```
[feature_toggles]
# there are currently two ways to enable feature toggles in the `grafana.ini`.
# you can either pass an array of feature you want to enable to the `enable` field or
# configure each toggle by setting the name of the toggle to true/false. Toggles set to true/false
# will take presidence over toggles in the `enable` list.
;angularDeprecationUI = false
;enable = feature1,feature2
;feature1 = true
;feature2 = false
```

**Pull request merged**
