### PR TITLE
Geomap: Spatial operations location options transform e2e test

### LINKED ISSUE #54066: Geomap: Geohash e2e test

### PR DESCRIPTION
**Pull request by adela-almasan**
https://user-images.githubusercontent.com/88068998/186512920-7f1f6b3f-cd5e-4c72-b432-504cd564a5d4.mov

e2e test for Spatial Operations location options (Auto, Coords, Geohash and Lookup).

Fixes #54066

### CODE REVIEW

**Comment by ryantxu** [comment]
Can we extend this test all 4 options?

**Comment by adela-almasan** [comment]
@ryantxu - ofc, I'll update!

**Comment by nmarrs** [comment]
Not sure how feasible this is but it might be cool to include screencast / footage of added e2e tests as part of this type of PR in the description 🤔

**Review by nmarrs — APPROVED** [review]
This looks great! Great job! 🔥

**Review by ryantxu — APPROVED** [review]
❤️ ❤️ ❤️ ❤️

**Pull request merged**
