### PR TITLE
Add Snyk Scanning workflow

### PR DESCRIPTION
**Pull request by SadFaceSmith**
Hello, this PR adds a workflow to automate code scanning via Snyk. The Grafana Labs Security Engineering manages a Snyk tennent which will ingest these results. Adding this workflow will allow our Snyk Dashboards to be updated on every release and merge to the 'main' branch. If you have any questions, please reach out to '@security-team' or '#security-engineering'

[_Created by Sourcegraph batch change `ethan.smith/snyk-monitor-workflow`._](https://grafana.sourcegraph.com/users/ethan.smith/batch-changes/snyk-monitor-workflow)

### CODE REVIEW

**Review by timlevett — APPROVED** [review]
LGTM

**Comment by tleopold** [comment]
Hi

As this is a change to the delivery pipeline I would like to have this change discussed with the RelEng team before we enable it so that we can understand the reasoning and how it works to allow us to be able to support our delivery processes.

Thanks
T

**Comment by SadFaceSmith** [comment]
> Hi
> 
> As this is a change to the delivery pipeline I would like to have this change discussed with the RelEng team before we enable it so that we can understand the reasoning and how it works to allow us to be able to support our delivery processes.
> 
> Thanks T

Sounds good @tleopold Happy to answer any questions!

**Comment by SadFaceSmith** [comment]
Going to reopen this PR due to issue with SourceGraph and CLA check. @tleopold @timlevett

**Pull request closed without merging**
