### PR TITLE
Prometheus: Highlight operations added in the query builder

### PR DESCRIPTION
**Pull request by aocenas**
https://user-images.githubusercontent.com/1014802/164244781-3f16f2a4-b8a1-4734-903a-edf75e8a428a.mp4

### CODE REVIEW

**Comment by torkelo** [comment]
Nice! 

One drawback with this approach is that when you remove an operation (the first), the remaining all flash. 

I tried a few different animation styles. Very hard to pick a favorite. 

One alternative is to not use boxShadow but just animate the border. 

border: `1px solid ${theme.colors.primary.border}`,

also changed the transition to:
 transition: 'all 1s ease-in 0s', 

Can't record a video now, need to pick up a my daughter. I don't know if the above is better that your animation, it's a bit stronger/visible but shorter. I think I actually prefer the shadow version more (but maybe a bit shorter) as using blue border makes it feel too similar to the focus state

**Comment by aocenas** [comment]
> One drawback with this approach is that when you remove an operation (the first), the remaining all flash.

hmm interesting. It does not happen for me for some reason. Though it probably should, the diffing should see it as a change so not sure if that is some race condition that does not trigger on my side or what is wrong.

**Comment by torkelo** [comment]
by first I mean the left most

**Comment by aocenas** [comment]
@torkelo yeah it did not happen for me. I could see that the state change happened and it should highlight it, but still did not see anything so not sure what is going on. I changed the diff anyway so it should not do that anymore, also should not highlight the whole stack if an operation is added at the first position.

**Comment by aocenas** [comment]
I tried both the border (I also think the contrast is better) with a bit of blur shadow and shorter:


https://user-images.githubusercontent.com/1014802/164276360-b906488a-69c4-40e2-999b-6d9031520531.mp4

I think I like this most but there is a very slight difference it seems between how the shadow and border fades out. Not sure what it is I assume sort of interpolation issue for different types of styles and not sure if it's noticeable for others.

**Review by torkelo — APPROVED** [review]
I like this!

**Pull request merged**
