### PR TITLE
Bug: Allow to uninstall a deprecated plugin

### LINKED ISSUE #45281: Plugins: can't uninstall deprecated plugin via the plugin catalog
**What happened**:
If you have a plugin installed that gets deprecated it can not be uninstalled via the plugin catalog. The reason is that the property `isPublished` is returned from the backend with the value `false` which makes the frontend think that this is a plugin not managed via grafana.com.

Backend is returning `isPublished: false` because as soon as the plugin is deprecated it is excluded from the data returned from grafana.com. 

See example below:
image

**What you expected to happen**:
I can uninstall the plugin even if it gets deprecated.

**How to reproduce it (as minimally and precisely as possible)**:
1. install the `grafana-k6cloud-datasource` via the grafana-cli
2. go to the plugin catalog in the UI and find the k6 datasource plugin.
3. try to uninstall the plugin via the UI.

**Anything else we need to know?**:
Proposed solution:
- Extend the garafan.com API with a new boolean property `deprecated` that will include deprecated plugins in the result if specified.
- Check the status returned from the API when fetching the data from the grafana.com API and act accordingly.
- It might be a good idea to expose some kind of information to the frontend about the plugin being deprecated so we can display that to the end user.

**Environment**:
- Grafana version: 8.4
- Grafana plugins: grafana-k6cloud-datasource

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

Allow to uninstall a plugin if it is "not published". Useful when a plugin is deprecated and is no longer published.

image

**Which issue(s) does this PR fix?**:

Fixes #45281

**Special notes for your reviewer:**

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by sympatheticmoose** [comment]
@andresmgot great work getting this resolved. My only concern is that, as far as I can see from the screenshot, this removes any indication of deprecation in the UI (few plugins will update their readme). 

We may want to hold off merging until this is close to being ready https://github.com/grafana/grafana/issues/74515

**Comment by andresmgot** [comment]
that's a good point, not sure why the generic deprecation notice dissapeared. It should be fixable :+1:

**Comment by andresmgot** [comment]
@leventebalogh do you mind giving a review here?

**Review by leventebalogh — APPROVED** [review]
LGMT 👍

**Pull request merged**
