### PR TITLE
NodeJS: Update to LTS (14)

### PR DESCRIPTION
**Pull request by torkelo**
Todo
* [ ] Rebuild and publish new build container, I tried to do this but failing on osx cross build steps so need help with that @aknuds1 

For building & testing frontend I think we should be able to do that in a standard node container, instead of using our custom build-container (which is required for any binary build) But maybe some advantage to using our own?

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

**Review by jackw — APPROVED** [review]
LGTM! 👍

**Comment by torkelo** [comment]
@aknuds1 when you have time can you try to rebuild and publish a new build-container (ci-build), based on changes in this PR, I failed due to osx compiler issues when trying to build ci-build

**Review by aknuds1 — APPROVED** [review]
LGTM, but could you also bump the version in scripts/build/ci-build/build-deploy.sh to 1.3.0? After merging I can build and publishing a new version of the CI build Docker image.

**Comment by aknuds1** [comment]
> @aknuds1 when you have time can you try to rebuild and publish a new build-container (ci-build), based on changes in this PR, I failed due to osx compiler issues when trying to build ci-build

I saw your request only now @torkelo :) Could you bump the version first, as I ask above?

**Comment by aknuds1** [comment]
Ah, the build fails. I can build a new image and upload it, so we can try it in this PR.

**Comment by torkelo** [comment]
thanks, yea I downloaded the osx sdk and put it in that folder but still failed with an osx compiler related error

**Comment by aknuds1** [comment]
@torkelo Why should it be necessary for you to download OSX SDK? Everything should be handled within the Dockerfile?

**Comment by kylebrandt** [comment]
With

```
$ cat /etc/issue
Linux Mint 20 Ulyana \n \l
```

the build would not complete for me (on master @ 2c535a9583). Got `Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime` with node version 14/15, started working again for me at 12.

(Ryan suggested I leave this as a comment on this pr)

**Comment by aknuds1** [comment]
@torkelo Published new image and updated the PR to use it.

**Comment by torkelo** [comment]
thanks! let's hope it will be green :)

**Pull request merged**
