### PR TITLE
Metric Units: fix unit symbols and description consistency

### PR DESCRIPTION
**Pull request by Pwuts**
**What this PR does / why we need it**:
Currently, both "metre" and "meter", "litre" and "liter" are used in the unit descriptions, which is not consistent or desirable. Also, the symbol for Litre is an uppercase 'L', not lowercase.

I fixed this in `valueFormats/categories.ts`.

The unit Watt-minute was also abbreviated as `W/Min`, but the unit is defined as Watt *times* minute, not Watt per minute. I changed it to `W-Min`.

**Which issue(s) this PR fixes**:
There were a lot of unit-related issues but I couldn't find any directly related issues.

**Special notes for your reviewer**:
I checked the surrounding code and these unit-definitions seem to be standalone as far as I can see. This is a very minor fix in which only a few text strings were altered and code semantics remain the same.

### CODE REVIEW

**Comment by ryantxu** [comment]
Do you mind splitting our meter vs the other changes "l-L"?

Meter vs. metre -- until we have localization, I think we should stick with "Meter" -- I have no idea if this is the internet telling me what I want to hear, but [the grammarist](https://grammarist.com/spelling/meter-metre/) suggests that it should be "Meter" for things that get measured:

image

**Comment by Pwuts** [comment]
@ryantxu Ah, right. I actually read that piece of text but only half of it. :p I would actually prefer "meter" but at the moment the file was inconsistent so I looked it up and went with the "metre is preferred everywhere else".

**Review by ryantxu — APPROVED** [review]
LGTM

**Comment by ryantxu** [comment]
Thanks @Pwuts

**Comment by Pwuts** [comment]
:D

**Pull request merged**
