### PR TITLE
CircleCI: Skip enterprise builds for forked PRs

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix builds of forked PRs by:

* Skipping enterprise build jobs (enterprise will fail for forked PRs due to required SSH key not being shared)
* Downloading the Grafana Build Pipeline tool from GCS, since cloning it from GitHub will fail for forked PRs (see above point for reason)

### CODE REVIEW

**Comment by torkelo** [comment]
Is CIRCLE_PR_NUMBER only true for for forked PRs?

**Comment by aknuds1** [comment]
> Is CIRCLE_PR_NUMBER only true for for forked PRs?

@torkelo [Yes](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables).

**Review by torkelo — APPROVED** [review]

**Review by marefr — APPROVED** [review]
LGTM

Still don't understand why this is needed now when it wasn't needed before?

**Comment by aknuds1** [comment]
@marefr Me too, brother...

**Comment by aknuds1** [comment]
There are still some issues that need working out, i.e. end to end tests fail.

**Comment by ryantxu** [comment]
> > Is CIRCLE_PR_NUMBER only true for for forked PRs?
> 
> @torkelo [Yes](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables).

Weird... I guess you are right :)  But CIRCLE_PULL_REQUEST(S) exists for all PRs:

image

**Pull request merged**
