### PR TITLE
Docs: add variable indexing and selection guidance

### PR DESCRIPTION
**Pull request by NimJ**
Indexing and selecting values from a variable

**What is this feature?**

Indexing and selecting values from a variable

**Why do we need this feature?**

These is no specific documentation available. 

**Who is this feature for?**

Data scientist and Developers who are using Variables in SQL queries and at other places.

**Which issue(s) does this PR fix?**:

Updating existing documentation.

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by jdbaldry — DISMISSED** [review]
Hi Nimesh, 

Thank you for your contribution!

I think the expected behavior when indexing into variables is dependent on your goals. I'm not sure that the example here is the _essential_ way in which people might use these values.

I'm also not sure that the documentation is specific to the Postgres data source.

I think this information might be better suited to a page like https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/ where as far as I can tell, we don't properly explain indexing into variables and a version of this documentation could be really useful.

**Comment by NimJ** [comment]
@jdbaldry Agree with you that the addition would be pertinent in variable-syntax docs. made changes accordingly. Thanks

**Comment by imatwawana** [comment]
Hi @NimJ, thanks for the contribution! I've tagged the dashboards squad so they can give this a technical review. Once that's completed, I'll circle back and do a wording review. I've also updated the title of the PR to make it more descriptive.

**Comment by jdbaldry** [comment]
@grafana/dashboards-squad are you able to take a look at this?

**Comment by axelavargas** [comment]
Hey @jdbaldry  I will bring the PR to the team, I also added to our board to bring more visibility 😄

**Comment by NimJ** [comment]
@axelavargas is the PR still in consideration? Thanks

**Comment by NimJ** [comment]
@ivanortegaalba

**Review by axelavargas — COMMENTED** [review]
Hey @NimJ 👋🏾,

Thank you for being patient with this one. I brought this to the team and have some answers.

When checking why there was no documentation, we noticed that there is no concept of variable indexing. The documentation you added was referring to an internal implementation of the raw variable formatting. 😅

In Grafana, we have different variable types that support multi-value selection: query, custom, and datasource.

In your case, when you were using one of these variable types in combination with the raw formatting, you were getting an array of values that you could access using the index:

${variable_name.index:raw}

Unfortunately, that syntax was relying on how we implemented the raw formatting.

This means we can't accept this PR because internal implementations are subject to change, and this one is no exception.

I checked how this is working in the new architecture (we are undergoing a migration of the whole dashboard rendering), and it looks like this is not supported anymore.

#### New architecture
image

#### Old architecture
image

Thank you again for bringing this up 🏅. It sparked a good conversation and some digging.

P.S. I will keep the PR open for a week to see if you have any comments. :)

**Comment by NimJ** [comment]
Thank you for your comment @axelavargas . 
You may close the request.

**Pull request closed without merging**
