### PR TITLE
Plugins: Bump plugin-related backend dependencies

### PR DESCRIPTION
**Pull request by xnyo**
**What is this feature?**

Bumps some plugin-related backend dependencies to their latest version:

- github.com/hashicorp/go-plugin v1.4.3 -> v1.4.9
- github.com/hashicorp/go-hclog v1.2.0 -> 1.5.0
---
- google.golang.org/protobuf already on latest (v1.30.0)
- google.golang.org/grpc already on latest (v1.54.0)

Corresponding dependencies bump for SDK: https://github.com/grafana/grafana-plugin-sdk-go/pull/672

I have done the following tests:

- [x] new sdk dependencies with new grafana dependencies
- [x] new sdk dependencies with old grafana dependencies (main, 9.5, 9.4, 8.5, 8.0)
- [x] old sdk dependencies with new grafana dependencies

Making sure that:

- [x] Backend plugins start and function correctly
- [x] Nothing weird is being logged to Grafana's stdout

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
:+1:

**Review by wbrowne — APPROVED** [review]
🚀

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Question though - shouldn't this PR use your SDK PR as dependency to get a proper test?

**Comment by xnyo** [comment]
> Question though - shouldn't this PR use your SDK PR as dependency to get a proper test of newer Grafana (your SDK changes as dependency) and backend plugins using older dependency of the SDK?

Yep, I have tested with `go mod replace` pointing to a local directory rather than replacing in this PR. I will open a new PR for Grafana once a new version of the SDK is released

**Comment by ahrycej** [comment]
Will this update resolve End of life protobuf version present in 9.5.1?
github.com/golang/protobuf   v1.5.2  /usr/share/grafana/bin/grafana

**Pull request merged**
