### PR TITLE
Cherrypicks for 6.5.0

### PR DESCRIPTION
**Pull request by marefr**
* grafana/ui: Add Icon component, (#20353), merge-sha: 17fe704ae8151e28fd2db93bb530acb3c9dcf9d0                                                                                                                                             
  * 6.5.0-beta1 Changelog, (#20350), merge-sha: 771ee549fbc78e80b4484ccddc25402a6df9f24c                                                                                                                                                      
  * Docs: What's new in Grafana v6.5 Draft, (#20368), merge-sha: 073e9ef9e7f380f7f53900953337491806462ca9                                                                                                                                     
  * Data links: Fix URL field turns read-only for graph panels, (#20381), merge-sha: d602da20f657be7174ebf915e309e00ecaa6c6a1                                                                                                                 
  * NavLinks: Make ordering in navigation configurable, (#20382), merge-sha: d4e013fd44f0915d9f1ae6abda504f66fe4e2fc3                                                                                                                         
  * Chore: Log actual error when oauth pass thru fails, (#20419), merge-sha: dfa2f3d2fbd04c5cd5e88fefbd13baaf25e566a2                                                                                                                         
  * Packages: stable release tags update, (#20417), merge-sha: de9ea829a443414b01437ca7416079c79fd13f28                                                                                                                                       
  * Server: Should fail when server is unable to bind port, (#20409), merge-sha: 82f4fc27831ea63cb4e276b721513224eef64bb0                                                                                                                     
  * Provisioning: Fix unmarshaling nested jsonData values, (#20399), merge-sha: 3f144bdd053a7e5540ef2703b55ab52485ad22aa                                                                                                                      
  * Reporting: Handle timeouts in rendering, (#20415), merge-sha: 7a8c6a9b54f210274ab22f50c7b1d000e36c8685                                                                                                                                    
  * Dashboard Migrator: persist thresholds param if already set, (#20458), merge-sha: 836cf8e63914a04d0317f63d2e125dab611da10b                                                                                                                
  * UsersPage: Removed icon in external button, (#20441), merge-sha: 785584a6907400551a24349e920025757fcba1f1                                                                                                                                 
  * CloudWatch: Make sure period variable is being interpreted correctly, (#20447), merge-sha: 38d5abfadb200586601e4baaef1b79a4e5c36dde                                                                                                       
  * CloudWatch: Fix high resolustion mode without expression, (#20459), merge-sha: af35e081c29208a97eb4287275d8e255079cc269                                                                                                                   
  * Docs: Add explore images to What's new in v6.5, (#20442), merge-sha: c2e401667cea724ad84ad483277e5426ab259d67                                                                                                                             
  * TimePicker: Should update after location change, (#20466), merge-sha: 322c110b8966ac1c000312d5e2d027d93df58890                                                                                                                            
  * Image-rendering: Cleanup of rendering code, (#20496), merge-sha: 1b38d94537466adb5e43c4568844fcccc83f0093                                                                                                                                 
  * CloudWatch: Remove HighResolution toggle since it's not being used, (#20440), merge-sha: ec18e2bfc3ab8c48ac79cea483487719ee5ae12b                                                                                                         
  * MySQL: Fix TLS auth settings in config page, (#20501), merge-sha: d3d595a776172f22e6735667279fce2427a03381                                                                                                                                
  * grafana/ui: Expose Icon component, (#20524), merge-sha: 9f94e059cfc3fe4b8ebf7c94ef08d5a292cb9f10                                                                                                                                          
  * What's new in 6.5 - adding CloudWatch topics, (#20497), merge-sha: 49685a92fdd4373525f6a3299b58de311b58879a                                                                                                                               
  * docs: what's new fixes, (#20535), merge-sha: 2079386a7d15b572bcb7fff272f24002eab88bb5                                                                                                                                                     
  * Templating: Prevents crash when $__searchFilter is not a string, (#20526), merge-sha: e03d702d0c14b214a57ddd5094ff756e845cdd2b                                                                                                            
  * Cloudwatch: Fix LaunchTime attribute tag bug, (#20237), merge-sha: 359416b89f4849ea3e68ef6106f6f2092d495bbc                                                                                                                               
  * Alerting: Propagate failures to delete dashboard alerts, (#20507), merge-sha: ea7ccda647f0341d2c6f4fa7a254082ef780d50e                                                                                                                    
  * CI: Build all platforms for Enterprise, (#20389), merge-sha: d630ac4b68883ff06525ef16782121a687260fb9                                                                                                                                     
  * CloudWatch: Add curated dashboards for most popular amazon services, (#20486), merge-sha: 22edacd4a83c3b9ac2adccac6a1713bcf44e2e94                                                                                                        
  * CI: fix release script remove filtering, (#20552), merge-sha: 65bacf2df63d3fbc0c3c3e51d47a609a9a9bd2c3                                                                                                                                    
  * CloudWatch: Enable Min time interval, (#20260), merge-sha: e33cf32b97e3bb4722fbf3da7240c2b185215f82                                                                                                                                       
  * Explore: UI improvements for log details, (#20485), merge-sha: c9645a96c6d8cdbb45ad6c9c614fcf2543404800                                                                                                                                   
  * Explore: Updates responsive button to forward ref, (#19815), merge-sha: 4ddb113b79c96db1c0162165fd14065db5d3c908                                                                                                                          
  * Enable theme context mocking in tests, (#20519), merge-sha: bff08ab99ffed6f59e1032700f39a813cade430a                                                                                                                                      
  * Changelog: Reference a few more issues that were fixed, (#20562), merge-sha: 83fa91b1f4a293ed2ec5b6e153678e17ef037377                                                                                                                     
  * Tooltip: Fix issue with tooltip throwing an error when retrieving values, (#20565), merge-sha: caff9146eac49e4ef6f05df0c9f4c5e8994f8f89
  * Docker: Custom dockerfiles, docker and image rendering docs update, (#20492), merge-sha: 2484b24c757ef33c847614e71b50bb772346178a
  * Explore: UI changes for derived fields, (#20557), merge-sha: 569c81d07e17878fb71effb31a25fd5f5f88be62
  * Docs: Update Explore docs for 6.5 (time-sync button & log details), (#20390), merge-sha: 11304b14b63fe25407a5f3bd3cf1808a3a95f6ce
  * TextPanel: Fixes issue with template variable value not properly html escaped , (#20588), merge-sha: f47759b98e34d119cbaf5b23c4eaa8f9ab6d6d87
  * Table: Use the configured field formatter if it exists, (#20584), merge-sha: f78b3b132902b2c04eaa0558c9bb54f20584845a
  * grafana/toolkit: Smaller output after successful upload, (#20580), merge-sha: d9abf01ce1c7c563d7c72ef3469074e1022bba54
  * Instrumentation: Edition and license info to usage stats, (#20589), merge-sha: bccc5397f6737465e13bc10fdfd9c015f3c08d28
  * Explore: Keep logQL filters when selecting labels in log row details, (#20570), merge-sha: c6a9a83bf3d69855b4126ac5afc9321398e95ac4
  * Explore: UI changes for split view and live tailing, (#20516), merge-sha: 29b46f7a2809a223ca8629c32170f1ae54c28901
  * CloudWatch: Fix high CPU load, (#20579), merge-sha: 3fc5f4552ac3f9439c3115999358b563581340eb
  * Cloudwatch: Docs improvements, (#20100), merge-sha: de94298d3a11e80647cb1a2cb28983cd626a815c
  * Docs: CloudWatch docs fixes, (#20609), merge-sha: 161f481f128973a6ca137d1a1915b1f2f0b43f98
  * BarGauge/Gauge: Add back missing title option field display options, (#20616), merge-sha: 6c50feb252c917d81cff3374daaddddb0ee5f655
 * Chore: Improve grafana-server profiling and tracing, (#20593), merge-sha: b16cb92b32e96e69e99785374f7c21489d6ccb85

**Left to do:**
- [x] Cherry pick last commits
- [x] Update versions to 6.5.0

### CODE REVIEW

**Review by papagian — CHANGES_REQUESTED** [review]
[This](https://github.com/grafana/grafana/pull/20592) is also assigned to milestone 6.5.0 but it is not labeled for cherry-picking.

**Comment by marefr** [comment]
@papagian yeah checked with Dominik and it didn't need cherry pick.

**Review by papagian — APPROVED** [review]
LGTM

**Review by aknuds1 — APPROVED** [review]
LGTM

**Pull request merged**
