### PR TITLE
Feature Management: UI improvements

### PR DESCRIPTION
**Pull request by jcalisto**
**What is this feature?**

The feature management admin page allows admin users to view a list of feature toggles and their status on their grafana instance.
This is a UI update to add default sorting by name, improve the tooltips and components visibility depending on whether we allow editing. 

**Who is this feature for?**

Grafana Administrators

Related with https://github.com/grafana/grafana-enterprise/issues/4897

### CODE REVIEW

**Review by mmandrus — COMMENTED** [review]
The changes you've made look good!

One remaining issue with the page is that once the instance is pending a restart, the Save button is still active. Do you think it would make sense to fix that in this PR as well? We could permanently disable the restart button and give it a tooltip about a pending restart.

If you think we should do a separate PR for that, that's fine too

**Comment by jcalisto** [comment]
> One remaining issue with the page is that once the instance is pending a restart, the Save button is still active. Do you think it would make sense to fix that in this PR as well? 

When I discussed with the UX team, they didn't think it was necessary to block further updates while awaiting a restart, as the updates will be processed sequentially and Grafana's state will eventually be consistent. 
Do you agree?

**Comment by mmandrus** [comment]
> > One remaining issue with the page is that once the instance is pending a restart, the Save button is still active. Do you think it would make sense to fix that in this PR as well?
> 
> When I discussed with the UX team, they didn't think it was necessary to block further updates while awaiting a restart, as the updates will be processed sequentially and Grafana's state will eventually be consistent. Do you agree?

In that case, I don't think we quite have the UI right at the moment. The following sequence seems wrong:

1. Open the feature toggle admin page
2. Disable a toggle e.g. `useCachingService` and click save
3. Save button is still enabled after a successful post
4. If I re-enable the `useCachingService` toggle, the button goes gray again because I am back to the original state

If we want to allow sequential updates, we would need to reset the base state after we click `save` and see if that's a bit clearer

**Review by mmandrus — APPROVED** [review]
LGTM! Nice work

**Pull request merged**
