### PR TITLE
NewsDrawer: Add grot to news drawer (after news items) 

### PR DESCRIPTION
**Pull request by torkelo**
Ok final version a more subtle one hidden after the last news item:

[Grafana (1).webm](https://github.com/grafana/grafana/assets/10999/e14c41a4-95d8-45f2-a1b7-51f8953fb804)

Discarded ideas (placing him in the header before the drawer title) 
image

A bit bigger 
image

A lot bigger:
Screenshot from 2023-05-10 09-57-29

### CODE REVIEW

**Comment by ergoerik** [comment]
@torkelo i think this doesn't quite feel right. Grot has to get too big for the meaning of the image to be clear. In this placement I think the larger it gets the more distracting and out of place it feels. We can try for a simpler version but I would probably skip.

**Comment by ergoerik** [comment]
@torkelo here's an updated image with little spiral on the newspaper

Newspaper Grot small spiral

**Comment by ergoerik** [comment]
@bogdanracles @jdcarolyne FYI

**Review by amy-super — APPROVED** [review]
I think it's cute to include Grot here for sure and love the updated image with our spiral on the newspaper. I just wonder if having it at the bottom means it will be invisible. This doesn't hurt anything so I'm game to include it, but I wonder if we can pull down how often news is being read.

**Comment by torkelo** [comment]
@amy-super yea, I don't think it will be very common for people to scroll to the bottom, which this is more of a easter egg :) 

But I can't think of another way to fit him in that doesn't feel out of place. Do you have any ideas?

**Comment by ergoerik** [comment]
What about something like this @torkelo @amy-super 
Screenshot 2023-05-10 at 4 22 10 PM

**Comment by torkelo** [comment]
@ergoerik the drawer opens under topnav so there is not that much room for a larger grot 

Something like this could maybe work? @amy-super what do you think? 
image

**Comment by torkelo** [comment]
Or this 
image

**Comment by amy-super** [comment]
Agree I prefer the centered one - and dropping the amoeba should be OK in dark mode as well. And in the end, I think it's OK that Grot is a little smaller but more visible (over the idea of dropping it at the end).

**Comment by torkelo** [comment]
Ok pushed an update. 

I think this size works pretty well, you clearly see what Grot is doing but it's not taking too much space from the drawer (news items). 

@ergoerik @amy-super @staton-hyse11 

image

**Review by staton-hyse11 — APPROVED** [review]
LGTM

**Comment by amy-super** [comment]
With the border! Looks great ❤️

**Pull request merged**
