### PR TITLE
Storybook: Update categories

### PR DESCRIPTION
**Pull request by tskarhed**
Updating with a new Storybook structure
Screenshot from 2020-02-03 15-46-55

### CODE REVIEW

**Comment by mckn** [comment]
Awesome work, will have a look and do some thinking regarding this. Get back with a review asap.

**Comment by dprokop** [comment]
Yeah, when looked at the Inputs category I have second thoughts. Let's talk this through today

**Comment by dprokop** [comment]
https://github.com/grafana/grafana/pull/21326#issuecomment-571029964

**Review by mckn — APPROVED** [review]
Love it! Awesome job @tskarhed 

chuck approves

**Pull request merged**
