### PR TITLE
Usage stats: Start tracking tempo

### PR DESCRIPTION
**Pull request by bergquist**
Would be nice if we could get this into 7.3.2 and start tracking it as soon as possible. 

Signed-off-by: bergquist <carl.bergquist@gmail.com>

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

**Comment by bergquist** [comment]
Should I just merge it now?

**Comment by aknuds1** [comment]
I don't see why not. You know this functionality better than I do.

**Comment by bergquist** [comment]
I was thinking about the backport labels :)

**Comment by aknuds1** [comment]
Yes, they make grot create a backport PR. It's the new procedure.

**Pull request merged**
