### PR TITLE
Icons: expand static cache to include all internally used icons

### LINKED ISSUE #32776: Icons: Some icons are missing
**What happened**:
On our hosted admin-ops-tools instance that runs on master, some icons are missing. Might be related to https://github.com/grafana/grafana/pull/32387
image
image

**Environment**:
- Grafana version: master Grafana v7.5.0-16732pre (c1061d038c)

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #32776

this does not exactly match https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/icon.ts. i don't think that's quite up to date anyhow.

i grepped for any icon names i could find. it took a good while. some are in `.go` files, patterns like `<Icon name="..."`, `<IconButton icon="..."`, `Icon: '...'`, some are inside conditioned props `name={foo ? 'angle-left': 'angle-right'}`, etc.

i'm not sure if these are all even used, as they could be in files that are no longer part of active builds, etc.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Review by ivanahuckova — COMMENTED** [review]
Is there a reason why we are not implementing all icons from `icon.ts`? I have just quickly checked and there are some missing - e.g. `cube`, `mobile-android` that is used in `public/app/features/alerting/AlertTabCtrl.ts`? I can check this in more detail cause I've seen couple of this cases, if you want. Also, shouldn't all cached icons that you have added (e.g. `presentation-play`) be also in `icon.ts`? It should probably be the same list.

**Comment by ivanahuckova** [comment]
And I see that you have added `key` icon that is used just at one place, and at other, we are using `key-skeleton-alt`. Maybe we could just change `key` to `key-skeleton-alt` and unify it instead of adding new icon.

**Comment by leeoniya** [comment]
good points. if fixed what i could find still being used.

there are icons in the typedef that don't appear to be used any more, and in general, keeping this all in sync is really tedious work, since there isnt a standard way or location for people to use icons due to their by-string nature and cross-language sharing. i'd like to get this merged and maybe you can do a followup PR for the `key-skeleton-alt` situation and to sync & clean the remaining items in `icon.ts`.

i'll add these in a bit:

- angle-double-down
- angle-double-right
- bell-slash
- bolt
- cube
- envelope
- mobile-android
- slack

i could not find `x` used anywhere, but it's really easy to miss. do you know where it might be used?

the full diff is below.

image

**Comment by leeoniya** [comment]
here is the spreadsheet i'm using to manage all the madness, might be helpful:

[icons.zip](https://github.com/grafana/grafana/files/6286938/icons.zip)

(rename the extension from .zip -> .ods), Github wouldn't let me attach it otherwise. (and ods files are also technically zip files, too :)

**Comment by ivanahuckova** [comment]
>i could not find x used anywhere, but it's really easy to miss. do you know where it might be used?

It seems like it was added in https://github.com/grafana/grafana/commit/47d2a8085ba2581ab6429bef6b820601e9b95753#diff-8b1e2d1548b7fb154b9b6554060875c584f5704395ffb05e02156ac753a45976R51 but at the end, we are not using it. So I would say it is safe to remove.

Just keep in mind, that some icons could have been added also by our plugins developers and are used in external plugins.

**Comment by leeoniya** [comment]
> Just keep in mind, that some icons could have been added also by our plugins developers and are used in external plugins.

this thing is a hot cache, it is meant to include only icons that are needed by 90% of cases. the reason they were not loading is not because they were missing from here but because when icons are lazy loaded on that server, they have to be loaded from a different path than they have in this repo. adding them to the cache fixes the problem only because they dont need to be fetched anymore. as i mentioned in the issue, this will still fail to lazy load any non-cached icons on that server, but that needs to be fixed by fixing the path resolution, and not by working around it and bloating this cache.

**Pull request merged**
