### PR TITLE
Explore: Reorganized data viz components

### LINKED ISSUE #65369: Explore: Reorganize viz components and define ownership
In order to decrease clutter and define clear ownership of Explore visualizations, we need to refactor each Viz component to be in separate sub directory and assign ownership to the relevant squad.

A good way to go is everything that gets rendered separately [here](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Explore.tsx#L504) should be moved to its own folder and assigned a different team as a code owner (update the CODEOWNERS file)

Example files to be updated: 
- Anything logs related
- Flame graph
- Raw Prometheus container
- Table Container
- Node Graph

### PR DESCRIPTION
**Pull request by harisrozajac**
This feature decreases clutter and defines clear ownership of Explore visualizations. 

Visualizations reorganized:
| Visualization | Ownership |
| ------------ | ----------- |
|  Logs | @grafana/observability-logs  | 
| Flame graph | @grafana/observability-traces-and-profiling  |
| Raw Prometheus container | @grafana/observability-metrics  |
| Table Container | @grafana/explore-squad  |
| Node Graph | @grafana/observability-traces-and-profiling |

Fixes https://github.com/grafana/grafana/issues/65369

Please check that:
- [x] Files are properly organized 
- [x] That ownership of each reorganized visualization is correct

### CODE REVIEW

**Review by svennergr — APPROVED** [review]
Logs changes LGTM. I think it might also be worth to move log related util functions from `app/explore/utils` to a better place to suite the viz-separation, WDYT?

**Comment by harisrozajac** [comment]
> Logs changes LGTM. I think it might also be worth to move log related util functions from `app/explore/utils` to a better place to suite the viz-separation, WDYT?

@svennergr That makes sense, we could move them into `Logs/utils`. Also, would it makes sense to have `observability-logs` team own everything in `Logs` folder? Currently, the `CODEOWNERS` file shows that `observability-logs` owns `Logs.tsx` and `LogsContainer.tsx`, but I was wondering if we should update that to the whole folder.

**Review by joey-grafana — APPROVED** [review]
Node / flame graph LGTM 👍

**Review by itsmylife — APPROVED** [review]
RawPrometheusContainer LGTM 👍

**Review by gelicia — APPROVED** [review]

**Pull request merged**
