### PR TITLE
Change to superscript and /(per)

### PR DESCRIPTION
**Pull request by flopp999**
#11211

### CODE REVIEW

**Comment by marefr** [comment]
As long as the key of the unit aren't changed it should not be a breaking change

**Review by torkelo — CHANGES_REQUESTED** [review]
tests needs to updated and maybe new tests added

**Comment by marefr** [comment]
@flopp999 please rebase on master and fix failing tests for us to be able to review this further

**Comment by flopp999** [comment]
You can close this PR and I will open a new.

**Pull request closed without merging**
