### PR TITLE
Chore: Move immutable, is-hotkey, and react-inlinesvg deps to grafana-ui

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Moves dependencies that are only used in grafana-ui from main package.json to grafana-ui/package.json

**Which issue(s) this PR fixes**:
Relates to #34129

### CODE REVIEW

**Comment by jackw** [comment]
It looks like yarn has removed the inlinesvg package and its dependencies from the lock file. Is this correct? I'd expect them to still exist. 🤔

**Comment by kaydelaney** [comment]
> It looks like yarn has removed the inlinesvg package and its dependencies from the lock file. Is this correct? I'd expect them to still exist. 🤔

You're right, think I need to regenerate the lock file, hold on

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Review by mckn — APPROVED** [review]
LGTM

**Pull request merged**
