### PR TITLE
Docs: Data Sources subsection naming

### PR DESCRIPTION
**Pull request by olcbean**
In the data sources docs two similar subsection names were used.
This PR renames `Adding the data source to Grafana` subsection to
`Adding data source` so that all data sources have the same
subsection name.

### CODE REVIEW

**Comment by aocenas** [comment]
@olcbean thanks for the contribution, can you fix the [spelling issue](https://circleci.com/gh/grafana/grafana/177610?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) to unblock the build?
@marcusolsson can you take a look at this and review?

**Review by marcusolsson — APPROVED** [review]
LGTM

**Comment by olcbean** [comment]
Thanks! Let's see if this will unblock the CI

**Comment by marcusolsson** [comment]
Hm, looks like there are conflicts. Could you try rebasing your branch on master to get the latest changes?

**Comment by olcbean** [comment]
@marcusolsson I accidentally deleted my original repo, so am no longer able to update this PR. Please refer to https://github.com/grafana/grafana/pull/20127 for the changes you requested.

**Pull request closed without merging**
