### PR TITLE
Chore: InlfuxDB testing update

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Update the structure of the testing with different responses and golden files.

### CODE REVIEW

**Review by kylebrandt — COMMENTED** [review]
If you look at prom the queries go in json files as well, and then the main test body can just loop over a list of files. Can we do that here so we don't need a manual t.Run for each?

**Comment by itsmylife** [comment]
@kylebrandt I did the change but not every test can be written that way. So I moved most of the json data to json files.

**Review by gabor-grafana — DISMISSED** [review]
LGTM 👍

**Review by gabor — APPROVED** [review]
LGTM 👍

**Pull request merged**
