### PR TITLE
Chore: Update otel deps

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

Prepare for the update of the SDK here: https://github.com/grafana/grafana-plugin-sdk-go/pull/804

### CODE REVIEW

**Comment by andresmgot** [comment]
@xnyo do you mind updating [grpc_plugin.go](https://github.com/grafana/grafana-enterprise/blob/main/src/pkg/extensions/pluginsintegration/remote/grpc_plugin.go)? It needs the same kind of change you did in   https://github.com/grafana/grafana-plugin-sdk-go/commit/1ed8e7be74e4cd750de1de6d392bb60b4f648f28

**Comment by xnyo** [comment]
> @xnyo do you mind updating [grpc_plugin.go](https://github.com/grafana/grafana-enterprise/blob/main/src/pkg/extensions/pluginsintegration/remote/grpc_plugin.go)? It needs the same kind of change you did in [grafana/grafana-plugin-sdk-go@1ed8e7b](https://github.com/grafana/grafana-plugin-sdk-go/commit/1ed8e7be74e4cd750de1de6d392bb60b4f648f28)

Done :)

https://github.com/grafana/grafana-enterprise/pull/6037

**Comment by xnyo** [comment]
@andresmgot can you re-trigger drone please I am not able to do so for some reason. The linter should pass now

**Review by xnyo — APPROVED** [review]
LGTM! :rocket:

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
