### PR TITLE
Plugin: AzureMonitor - Reapply MetricNamespace support

### LINKED ISSUE #17220: AzureMonitor: Support for custom metrics
AzureMonitor provides a defined set of metrics for all its services but it is also possible to save custom metrics - for example, you can use the Telegraf collector to save any custom metric you want. These are currently not available in the AzureMonitor datasource.

Ported from the now deprecated plugin repository: https://github.com/grafana/azure-monitor-datasource/pull/79

### PR DESCRIPTION
**Pull request by raphaelquati**
**What this PR does / why we need it**:
Plugin: Azure Monitor
Implementation of MetricNamespace to support custom metrics

**Which issue(s) this PR fixes**:
Fixes #17220

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by daniellee** [comment]
@raphaelquati The merge conflicts are my fault - I merged a PR that moves the query code from the backend to the frontend. I fixed the merge conflicts locally but I have some questions before I can merge this.

The `Metric Namespace` and `Namespace` dropdowns look almost the same. What's the difference and how does this fix the custom metrics problem? It was confusing to me to have to pick namespace twice.

image

This is a breaking change and we would have to add a migration too so that existing dashboards keep on working.

**Comment by raphaelquati** [comment]
MatricNamespace is a Azure Monitor information (https://docs.microsoft.com/en-us/rest/api/monitor/metricnamespaces)
image

**Comment by daniellee** [comment]
@raphaelquati I don't understand what you are trying to say.

I'm looking at the [docs for the metrics api endpoint](https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list) and I see that there is a querystring parameter called `metricnames`.

Before your change:

```
https://management.azure.com/subscriptions/b324c52b-4073-4807-93af-e07d289c093e/resourceGroups/grafanastaging/providers/Microsoft.Storage/storageAccounts/grafanastaging/blobServices/default/providers/microsoft.insights/metrics?aggregation=Average&api-version=2018-01-01&interval=PT1H&metricnames=BlobCapacity&timespan=2019-07-07T14%3A34%3A52Z%2F2019-07-07T20%3A34%3A52Z
```
And with your change:

```
https://management.azure.com/subscriptions/b324c52b-4073-4807-93af-e07d289c093e/resourceGroups/grafanadev/providers/Microsoft.Storage/storageAccounts/grafanadevdiag/blobServices/default/providers/microsoft.insights/metrics?api-version=2018-01-01&timespan=2019-07-07T14:24:55Z/2019-07-07T20:24:55Z&interval=PT1H&aggregation=Average&metricnames=BlobCapacity&metricnamespace=Microsoft.Storage%2FstorageAccounts%2FblobServices
```

The only difference is the `metricnames` querystring. 

So two questions:
- do we need a new dropdown or can we reuse the existing `Namespace` dropdown? The lists of namespaces look the same to me.
- how does this solve the custom namespace problem?

I will test with some custom namespace tomorrow if you don't know the answers to the 2 questions above.

**Comment by raphaelquati** [comment]
Yes, we need the two dropdowns.

First dropdown "Namespace", is used to filter resources available in "Resource Group", to populate "Resource Name" dropdown.

With "ResourceGroup", "NameSpace" and "ResourceName", we query [MetricNamespace List](https://docs.microsoft.com/en-us/rest/api/monitor/metricnamespaces/list), to populate "Metric NameSpace" dropdown.

With "ResourceGroup", "NameSpace", "ResourceName" and "MetricNameSpace", we query the query
(https://docs.microsoft.com/en-us/rest/api/monitor/metricdefinitions/list) to populate "Metric" dropdown.

And with "ResourceGroup", "NameSpace", "ResourceName", "MetricNameSpace" and "Metric" we call https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list.

There's a problem is with your merge.

**Comment by raphaelquati** [comment]
The metrhod MetricNamespace List is returning:

```
{
  "value": [
    {
      "id": "<resourceUri>/providers/microsoft.insights/metricNamespaces/Telegraf-rabbitmq_node",
      "name": "Telegraf-rabbitmq_node",
      "type": "Microsoft.Insights/metricNamespaces",
      "classification": "Custom",
      "properties": {
        "metricNamespaceName": "Telegraf/rabbitmq_node"
      }
    },
    {
      "id": "<resourceUri>/providers/microsoft.insights/metricNamespaces/Telegraf-rabbitmq_queue",
      "name": "Telegraf-rabbitmq_queue",
      "type": "Microsoft.Insights/metricNamespaces",
      "classification": "Custom",
      "properties": {
        "metricNamespaceName": "Telegraf/rabbitmq_queue"
      }
    },
    {
      "id": "<resourceUri>/providers/microsoft.insights/metricNamespaces/Telegraf-rabbitmq_overview",
      "name": "Telegraf-rabbitmq_overview",
      "type": "Microsoft.Insights/metricNamespaces",
      "classification": "Custom",
      "properties": {
        "metricNamespaceName": "Telegraf/rabbitmq_overview"
      }
    },
    {
      "id": "<resourceUri>/providers/microsoft.insights/metricNamespaces/Telegraf-rabbitmq_exchange",
      "name": "Telegraf-rabbitmq_exchange",
      "type": "Microsoft.Insights/metricNamespaces",
      "classification": "Custom",
      "properties": {
        "metricNamespaceName": "Telegraf/rabbitmq_exchange"
      }
    },
    {
      "id": "<resourceUri>/providers/microsoft.insights/metricNamespaces/Microsoft.OperationalInsights-workspaces",
      "name": "Microsoft.OperationalInsights-workspaces",
      "type": "Microsoft.Insights/metricNamespaces",
      "classification": "Platform",
      "properties": {
        "metricNamespaceName": "Microsoft.OperationalInsights/workspaces"
      }
    }
  ]
}
```

For me, the last entry should be "Default" and not "Microsoft.OperationalInsights/workspaces". But Azure API can change this.  
I even thought about renaming this to default (using when "classification" == "Platform). But I don't know if it's a good idea.

image

image

image

**Comment by raphaelquati** [comment]
I've made the merge with master here, but I don't know  what to do with this line (azure_monitor_datasource.ts)

image

**Review by daniellee — APPROVED** [review]

**Comment by daniellee** [comment]
@raphaelquati thanks for your patience. I tested with telegraf metrics in a vm and it worked great.

I fixed the merge conflict due to moving logic from the frontend to the backend and added some docs too.

**Pull request merged**
