### PR TITLE
grafana/data: Reorganise code

### LINKED ISSUE #18822: DataFrame filenames & organization
Today we have

* utils/dataFrameHelper.ts (contains FieldCache & MutableDataFrame)
* utils/dataFrameHelper.test.ts 
* utils/dataFrameView.ts  (DataFrameView)
* utils/dataFrameView.test.ts  (DataFrameView)
* utils/processDataFrame.ts 
 
Think we should move FieldCache & tests to its own file and rename files to match their primary export (except maybe processDataFrame). 

It's a bit tricky to only change letter casing in file names like utils/dataFrameView -> utils/DataFrameView

So one option would be to move all of the data frame related stuff to a top level dir /dataframe or /DataFrame (not sure which I prefer, tricky with casing and consistency) . Now everything in data package is under utils. Maybe transformers and matchers should be top level dirs? 

thoughts @ryantxu ?

### PR DESCRIPTION
**Pull request by dprokop**
Closes #18822 

As follow-up:
- [ ] cleanup processDataFrame.ts as its huuuuge
- [ ] Decide on what to do with fieldReducers/fieldParser

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
LGTM -- this will be nice to have a good pattern we can follow.  Thanks!

Some minor notes:
* `registry.ts` to `Registry.ts`

What do you think about putting transformers/mastchers in a folder called 'processing'?
```
src/processing
   + transformers
   + matchers
   + (reducers?)
```

I don't like the export `transformersRegistry` -- That seems better as `transformers` because it will have the fluent API attached to it.

`transformers.reduce( data, options )` seems better than `transformersRegistry.reduce( data, options )`

I vote we:
1. combine `transformDataFrame.ts` and `transformersRegistry.ts` into `transformers.ts` and keep it at the root of that folder
2. move `matchers/matchers.ts` to the root, so it looks the same as `transformers.ts`
3. move `utils/fieldReducers` to this same folder.

**Comment by dprokop** [comment]
> What do you think about putting transformers/matchers in a folder called 'processing'?

No strong feelings about it, neither `transformations`. Both work for me in the same good wat. Let's stick with transformations for now (it's directory name, changing it will not affect APIs exposed from grafana-data) and possibly rename when we work on the UX around transformers. Who knows if we won't come up with some better name when working on UI for this feature.

> I don't like the export transformersRegistry -- That seems better as transformers because it will have the fluent API attached to it.

Totally agree, it didn't feel right when I renamed it.

**Comment by ryantxu** [comment]
much better ❤️

**Review by torkelo — APPROVED** [review]
Looks great, glad we got this in before branch off

**Pull request merged**
