### PR TITLE
Stat: Support no value in spark line

### LINKED ISSUE #52789: Stat panel does not apply "No Value" mapping
**What happened**:
This is the raw graph that I am working with:

image

I want the top line, that stopped receiving new datapoints, to be mapped to zero. As a graph panel, I was able to do this using the "No Value" field: 
image

This resulted in the following graph:
image

Now I can use the fact that the green line is 0 to create my threshold.

The thing is I want this to be a stat panel, which shows SRVS00308 as red and SRVS00309 as green.

When I convert this to a stat panel, having the No Value set to 0 aswell, it does not seem to be applied in the same way, as can be seen here, where the graph just ends instead of dropping to 0:

image

This means I am not able to set it as red. There was no change besides setting it to a stat panel.

**What you expected to happen**:
I would have expected that the graph on the left in the last picture would drop to 0, such that I can take the last value in my stat panel and use the threshold on that.

**Environment**:
- Grafana version: 9.0.4
- Data source type & version: prometheus

### PR DESCRIPTION
**Pull request by Fe8N**
**What is this feature?**
[Add a brief description of what the feature or update does.]
1. make stat panel support  no value 
2.  add storybook case for  BigValue component's noValue  case

**Why do we need this feature?**
[Add a description of the problem the feature is trying to solve.]
https://github.com/grafana/grafana/issues/52789

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #52789

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by nmarrs — COMMENTED** [review]
Hi @FOWind! Thank you for your contribution!

On closer review it seems like the [original issue](https://github.com/grafana/grafana/issues/52789) seems to have a viable fix via the stat value options calculation (choosing `Last` vs `Last*`)

Given this fix above, I am not sure if we need these code changes / what exactly these code changes are doing. Maybe I am missing something though 😅 - if I am please let me know :)

 
[#52789 Stat panel no no value-1704906273213.json.txt](https://github.com/grafana/grafana/files/13890744/52789.Stat.panel.no.no.value-1704906273213.json.txt)


https://github.com/grafana/grafana/assets/22381771/b7cbe075-9665-4835-ba10-163b04bbcb93

**Comment by FOWind** [comment]
> Hi @FOWind! Thank you for your contribution!
> 
> On closer review it seems like the [original issue](https://github.com/grafana/grafana/issues/52789) seems to have a viable fix via the stat value options calculation (choosing `Last` vs `Last*`)
> 
> Given this fix above, I am not sure if we need these code changes / what exactly these code changes are doing. Maybe I am missing something though 😅 - if I am please let me know :)
> 
> [#52789 Stat panel no no value-1704906273213.json.txt](https://github.com/grafana/grafana/files/13890744/52789.Stat.panel.no.no.value-1704906273213.json.txt)
> 
>  Screen.Recording.2024-01-10.at.9.05.06.AM.mov


As shown in the video, the sparkline in the stat panel doesn't  draw  the no value  with current version.

This PR will draw the null value if setted  as below.

image

**Comment by nmarrs** [comment]
> As shown in the video, the sparkline in the stat panel doesn't draw the no value currently.
> With this PR's patched it will draw the null value if setted as below.
@FOWind thank you for the response! I didn't notice the difference in the spark line on the first review 😅

I think this change makes sense - to get it merged in you will need to rebase this branch onto latest main. To do so you should first pull latest `main` and then, on the feature branch run `git merge origin main` and push up the result. Thanks

**Review by nmarrs — APPROVED** [review]

**Comment by leeoniya** [comment]
the original issue this fixes talks about this relating to thresholds, but this might only address it for sparkline vis but not the Stat background color, which is also threshold based.

i think we need to address this more holistically and not just sparkline sub-component.

**Comment by codeincarnate** [comment]
@leeoniya I would agree we need to address more scenarios, but `nullToValue` needs to be applied in each of scenarios right? This takes us in the right direction IMO

**Review by codeincarnate — APPROVED** [review]
This looks fine to me overall, but may need to revise based on the conversation above 😄

**Comment by leeoniya** [comment]
>  I would agree we need to address more scenarios, but `nullToValue` needs to be applied in each of scenarios right?

my main question is whether this needs to be applied once (above the Sparkline component), and this data shared for stat background and sparkline, instead of being done only in sparkline and then doing it second time for stat background threshold.

**Comment by nmarrs** [comment]
> my main question is whether this needs to be applied once (above the Sparkline component), and this data shared for stat background and sparkline, instead of being done only in sparkline and then doing it a second time for stat background threshold. feels like it should be moved up, and done in one place to accommodate both scenarios.

My vote here is that we move forward and merge this PR and address this refactor in [a follow-up issue](https://github.com/grafana/grafana/issues/80930). Thank you for your contribution @FOWind!

**Pull request merged**
