### PR TITLE
Datasources: Allow changing uid 

### PR DESCRIPTION
**Pull request by torkelo**
Part of #48611
Screenshot from 2022-06-14 11-38-12
Screenshot from 2022-06-14 11-11-17

If you provision / sync dashboards between instances but not data sources, but create data sources manually via the UI then the uid will not match. Not sure the best way to solve this but allowing for changing uid in the UI / API is one solution. 

I am however very unsure what this should do, short-term and long-term. 

Currently, data source uids are referenced from
* Dashboard json models 
* Alert query json models
* Secrets 
* ?? ( permissions scopes for enterprise RBAC) ??

Solutions
* A) Updating references in the backend within one db transaction, even though it would involve reading all dashboards, alert rules etc for references and updating many. 
* B) Updating references in the backend in separate transactions 
* C) List references in the frontend and update them one by one from the frontend (automatically). Highlight provisioned resources that need to be updated manually. 
* D) Update no references
* E) Update no references,  but show references in frontend so user can update them manually 

If not done in one transaction, do we need a table to record the uid change so we can resume it if the process fails? 

Should I create design doc for this to discuss this more in gdoc?

### CODE REVIEW

**Comment by bergquist** [comment]
> Should I create design doc for this to discuss this more in gdoc?

I think that would be a good idea. 

> A) Updating references in the backend within one db transaction, even though it would involve reading all dashboards, alert rules etc for references and updating many.

I'd be worried about locking the dashboard table for a long time. If we go down this route we would have to make the operationg admin only and be explicit about the impact IMO. 

> B) Updating references in the backend in separate transactions

Storing an "work item" as uncompleted in the database and updating dashboards in the background until all migrated and then marking that item as completed could be an interesting capability for Grafana. I see other use-cases for such feature as well. Ex the database expand/collapse pattern or re-encrypting keys using envelope encryption.

**Comment by sakjur** [comment]
> > Should I create design doc for this to discuss this more in gdoc?
> 
> I think that would be a good idea.

:+1:

> > B) Updating references in the backend in separate transactions
> 
> Storing an "work item" as uncompleted in the database and updating dashboards in the background until all migrated and then marking that item as completed could be an interesting capability for Grafana. I see other use-cases for such feature as well. Ex the database expand/collapse pattern or re-encrypting keys using envelope encryption.

I like this idea. Queued up work items and resource name aliases would make it possible to provide a migration with zero downtime that also eventually corrects the services referencing the old name and allows for the removal of the alias (or not, we might not want to do that).
We could create a main task with subtasks attached to it and let the different services listen for their subtasks.

I think C and E are impractical because they rely on the frontend to deliver what should be a reproducible result. I'd rather avoid to have an instruction saying "keep your browser window open while Grafana processes this migration".

D seems to be "allow copying and deleting the data source with a given UID", I'd assume the backend would already support that. But it's probably not what the user would expect.

**Comment by sdboyer** [comment]
In general, i think there's a whole can of worms kept closed if we avoid allowing changes to an object's fundamental identifier. Updating known referents is far saner than updating identifiers.

One key bit of semantics that is not explicitly treated in the OP is the question of which of the following semantics are desired. Given:

* `T0`, the "moment" (n.b. [there is no now](https://queue.acm.org/detail.cfm?id=2745385)) at which a user initiates the change
* An old datasource uid, `OLD`
* A new datasource uid, `NEW`

Do we want:

* All instances (both identifier and referent) of `OLD` that exist at **SOME** moment equal to or logically following `T0` to become `NEW`
* All instances (both identifier and referent) of `OLD` that exist at **ALL** moments equal to or logically following `T0` to become `NEW`

Let's call these "batch" and "redirect" semantics, respectively.

The distinction here is significant for the known case of provisioning, at least - if a datasource is provisioned with `OLD`, or a dashboard/alert is provisioned with a reference to `OLD`, then batch semantics may miss at least some of them on the next provisioning round. If we can unambiguously decide whether that's a good or bad thing, i think picking the right path here might be easier.

It seems to me that the two approaches demand significantly different implementations. Batch semantics are going to be a bit of a lie no matter what, per above-linked article; redirect semantics are going to be far more complex to implement. (Like, i think that redirect semantics would entail rename-on-the-fly during RBAC checks, requiring queries to the database to look up the rename list. 😱)

Just spitballing a bit, my current guess is that a reasonable balance of tradeoffs here results in a strategy like this:

* We maintain the invariant that a UID, once set, is immutable. We do not open the can of worms.
* We introduce a system to support the batch semantics on an async basis. It would focus _solely_ on searching for and updating referents, and accept that it will always be flawed because time is a lie.
* We introduce a [tombstone-like](https://en.wikipedia.org/wiki/Tombstone_(data_store)) system: a new object type that would specify both the old and new UIDs (`OLD` and `NEW`).
  * The existence of the tombstone will cause attempts to create an object with uid `OLD` to fail informatively
  * The existence of the tombstone will cause newly-created or re-provisioned objects with references to `OLD` to be dynamically rewritten to `NEW`. i think? or fail? not fully sure here (really not sure how feasible this is for plugin-defined objects)
  * The existence of the tombstone will cause API updates to objects containing references to `OLD` to...fail? not sure here
* Creating a tombstone triggers the batch semantics. Should probably be supported via UI/API/CLI, and provisioning. Basically, stick an item in a queue. So...

> > B) Updating references in the backend in separate transactions

> Storing an "work item" as uncompleted in the database and updating dashboards in the background until all migrated and then marking that item as completed could be an interesting capability for Grafana. I see other use-cases for such feature as well. Ex the database expand/collapse pattern or re-encrypting keys using envelope encryption.

This would be is using the database as a queue, which is ~fine, arguably even good in the context of a database with transactions, which we can use to ~ensure only-once behavior. 

The other cases listed here are interesting. i would be wary of allowing it to overexpand, however. There's a long path here through queuing and distributed systems theory that i think winds up at actor models, and/or Kubernetes' decision to be [level-triggered rather than edge-triggered](https://hackernoon.com/level-triggering-and-reconciliation-in-kubernetes-1f17fe30333d).

---

It's kinda hard to address the rest directly if we do not actually allow UID changes. But:

> A) Updating references in the backend within one db transaction, even though it would involve reading all dashboards, alert rules etc for references and updating many.

No, it doesn't handle future cases/tombstoning at all, and no sense in hanging up an interface for it to wait doing it all sync.

> C) List references in the frontend and update them one by one from the frontend (automatically). Highlight provisioned resources that need to be updated manually.

Sure, this is probably best in a world where uid changes aren't actually allowed. See above spitball strategy about handling the tombstone on updates.

The big thing that's beneficial here is, in an approach where we don't open the can of worms and do not allow changing the uid of an existing object, this is a way of enumerating to the user what the `OLD` uids actually are

> D) Update no references

No, non-starter

**Comment by sdboyer** [comment]
Semi-orthogonal, but throwing it in as a related note: i think we might benefit from having a purely internal, non-exported, non-writable property that durably tracked object identity, akin to [k8s UIDs](https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/overview/working-with-objects/names/).

However i wouldn't want these until we have standardized object metadata

**Pull request closed without merging**
