### PR TITLE
EmptyState: use `not-found` empty state variant everywhere in core

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- uses the `not-found` variant of `EmptyState` in lots of places in core
- adds a couple of translations 

| before | after |
| --- | --- |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

**Why do we need this feature?**

- consistency

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

For https://github.com/grafana/grafana/issues/84516

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
Generally fine, but I feel like the Not Found page was better before, with the big heading up top.

**Review by L-M-K-B — COMMENTED** [review]
I think the pages look great now.
While checking the changes locally I saw that the alert rules list (/alerting/list) wasn't included here. Is this on purpose?

Referring to @joshhunt:
> Generally fine, but I feel like the Not Found page was better before, with the big heading up top.
I can see why the big heading may be nicer but I think it clashes with this PR's purpose of creating a consistency.

**Comment by ashharrison90** [comment]
> I think the pages look great now. While checking the changes locally I saw that the alert rules list (/alerting/list) wasn't included here. Is this on purpose?
> 
> Referring to @joshhunt:
> 
> > Generally fine, but I feel like the Not Found page was better before, with the big heading up top.
> > I can see why the big heading may be nicer but I think it clashes with this PR's purpose of creating a consistency.

yeah i didn't want to mess with that page as it's quite different 😄 i did silences because it was easy, but i think i'll leave that one to the alerting experts to implement themselves once i've socialised the new components

**Comment by joshhunt** [comment]
I think you can easily draw a line between like Error Page as one thing, and these smaller states as another.

I don't feel very strongly about this - it's not a hill I'll die on - but i just wanted to share my preference here :)

**Comment by ashharrison90** [comment]
i also have a _slight_ preference for the look of the previous page (like 5% or something)

**but** using this allows us to delete all the code from core that currently exists which i think outweighs the 5%

**Review by L-M-K-B — APPROVED** [review]
I guess we are good to go then. Let's merge this PR. 🥳

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
