### PR TITLE
Docs: Add role UIDs for fixed and basic roles to RBAC documentation

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
**What is this feature?**

Adding UIDs for fixed and basic roles to the documentation.

**Why do we need this feature?**

User needs to know role UIDs when calling RBAC API or using provisioning. Having the UIDs documented makes it easier to quickly find them.

UIDs for fixed roles are deterministic since https://github.com/grafana/grafana/pull/76239 was merged.

**Who is this feature for?**

RBAC users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/identity-access-team/issues/489

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gamab** [comment]
I was holding off on this one as we currently only have the `prefix + base64(sha1(name))` on newly created fixed roles. So already created roles won't match this template yet.

**Comment by IevaVasiljeva** [comment]
> I was holding off on this one as we currently only have the `prefix + base64(sha1(name))` on newly created fixed roles. So already created roles won't match this template yet.

Ouph, I should have checked in with you before making this change 😄 Are we planning to update all fixed roles (https://github.com/grafana/identity-access-team/issues/401 hints at it)?

**Comment by IevaVasiljeva** [comment]
Yeah, breaking changes are tough. I think the "break things for the next major" approach doesn't really hold up anymore with the focus on cloud. I think we need a bigger conversation about this topic.

> we try a smoother approach where we redirect, with a warning, the previous role UIDs to their new value for a couple of versions. I wonder how the terraform provider is going to like that 🤔

Hmm, as in support two role UIDs in parallel? That seems pretty risky to me, but I guess we haven't tried anything like that in the past so it might be worth exploring.

**Review by jdbaldry — COMMENTED** [review]
Reading through the PR conversation, I think that a docs review is not yet required because it's not clear that these changes will be technically accurate.

The changes look good to me purely syntactically but please re-request review when this is ready to go :)

**Comment by IevaVasiljeva** [comment]
You're right @jdbaldry, we're not ready to merge this yet. I'll convert it to draft for now.

**Pull request closed without merging**
