### PR TITLE
CI: Run e2e tests in parallel using multiple suites

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Currently, our end-to-end tests run as a huge monolith step that takes ~8 minutes. It's not only that the number is huge, it's also that running everything at once is not easy to reproduce things quickly, or focus on fixing a single end to end test.

This PR introduces parallelisation between end to end steps. That actually means that we can now run end to end test suites in parallel and reduce the build times significantly. For this restructuring to work, the installation of the cypress binary was extracted to a different step (`install_cypress`) which can be improved even further as we can use cypress directly as a docker image. 

With these changes, we are now able to run 4 e2e test suites in parallel, which reduces our step times to 2 minutes (**~75% improvement**).

**Special notes for your reviewer**:

Before this PR:

Screenshot 2021-11-23 at 4 46 22 PM

After this PR: 
Screenshot 2021-11-23 at 4 48 22 PM

### CODE REVIEW

**Comment by leeoniya** [comment]
hey @dsotirakis 

i noticed test-frontend failed pretty early in https://drone.grafana.net/grafana/grafana/41847 but did not immediately cause the whole thing to fail despite being required.

not sure if this PR improves the feedback loop.

**Comment by dsotirakis** [comment]
Hello @leeoniya 👋 
Well, that's a Drone thing we cannot avoid unfortunately. I am seeing some requests about this but nothing implemented yet.
However, I think the feedback looped is improved as we breakdown things a bit more. Even if one failed pipeline doesn't stop the others, you are sure that the other pipelines are fixed and you can only focus on fixing the failing test for example.
Otherwise in the monolith pipeline, we may had the `test-frontend` step failing, and when fixed that we may have another failure at a later stage, so we'll need to restart. Now we know exactly where the problem is :)

**Comment by leeoniya** [comment]
> Even if one failed pipeline doesn't stop the others, you are sure that the other pipelines are okay and you can only focus on fixing the failing test for example.

it makes sense though, i personally dont start fixing anything until i see a failed build on GH (which can mean waiting 20min for feedback instead of 3min); i doubt many people watch individual pipelines in the drone UI :(

**Review by hugohaggmark — APPROVED** [review]
Awesome work on this 🎉  I think the experience locally with `yarn e2e` or `yarn e2e:dev` might not work any longer but we can fix that in a later PR.

### yarn e2e:dev
image

### yarn e2e
image

**Comment by hugohaggmark** [comment]
Created a new issue for fixing running e2e locally here https://github.com/grafana/grafana/issues/42178

**Pull request merged**
