### PR TITLE
Maintain column widths when deleting columns

### LINKED ISSUE #67686: Datagrid: Bug Bash - Column width changes when deleting the previous column
**Found during bug bash 10:**
When deleting a column, the width following one resizes to the width of the deleted one. 

**Steps to reproduce:**
1. create a datagrid with entries (file attached that i used - modified mine though)
2. create a new column
3. adjust the width of the new column by dragging the separator 
4. delete the previous column

**Expected Result:**
I expected that the only previous column gets deleted and the newly created moves to the space.

**Actual Result:**
The previous column gets deleted, the new created one moves to the new space BUT the column width is adjusted to be the same width of the deleted one.  (See video)

Environment:
Grafana Version: v10.0.0-55187pre (ea536411f1)
Chrome Version: 112.0.5615.137 (Official Build) (arm64)
macOS: 13.3.1 (22E261)

[Expenses_CSV.csv](https://github.com/grafana/grafana/files/11377510/Expenses_CSV.csv)

https://user-images.githubusercontent.com/110845248/235778913-ce6d7043-8bdf-41f8-b0fb-56d203cab057.mov

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**

Fixes a bug in the Datagrid panel. When deleting a column, the widths of the other columns are no properly maintained

**Why do we need this feature?**

Have proper column widths

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #67686

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by baldm0mma — APPROVED** [review]
Sick bruh.

**Review by zoltanbedi — CHANGES_REQUESTED** [review]
Renaming column also resets its width.

https://user-images.githubusercontent.com/13729989/235912892-fff899fc-5ec9-4fb9-a3e4-333550dcf051.mov

**Comment by supilee** [comment]
@zoltanbedi this looks like it should. the header length changes and it adjusts to it.

**Review by supilee — APPROVED** [review]

**Comment by zoltanbedi** [comment]
> @zoltanbedi this looks like it should. the header length changes and it adjusts to it.

If @mdvictor accepts that I'm also fine with it.

**Comment by supilee** [comment]
drummroll.....

**Review by zoltanbedi — APPROVED** [review]
sounds good @mdvictor

**Pull request merged**
