### PR TITLE
Explore: highlight typed text in suggestions

### PR DESCRIPTION
**Pull request by davkal**
- add highlighting (color and border) to the matching substring of the
  suggested items in the typeahead
- extracted match finding from logging datasource
- created new utils/text.ts class for text-related functions
- generalized logging's Entry component to be the MatchedText component
- added more types

### CODE REVIEW

**Comment by davkal** [comment]
Using highlighter lib in suggestions, simplifies things.
Need to keep our text highlighter around for logging results until react-highlight-words supports regexp.

**Comment by torkelo** [comment]
nice. think react-highlight-words supports regex, if not you can override findChunks with your own implementation:

https://github.com/bvaughn/react-highlight-words/pull/45

not sure how much that helps with the logs highlight use case though.

**Comment by davkal** [comment]
Now using react-highlight-words for all matching. PTAL.

**Comment by torkelo** [comment]
Nice!

**Pull request merged**
