### PR TITLE
Tempo: Add placeholder for the Limit field under the Search tab

### PR DESCRIPTION
**Pull request by CrypticSignal**
When a query is made using Tempo's `Search` tab, if the user does not specify a value for the `Limit` field, the default value set in the query object is 20. This means that the maximum number of traces returned is 20. However, the UI provides no indication to the user that the default limit is 20.

This PR adds a `Default: 20` placeholder to the `Limit` field, so the user knows the default behaviour.

image

### CODE REVIEW

**Comment by joey-grafana** [comment]
Can you add this to Jaeger as well?

**Comment by CrypticSignal** [comment]
@joey-grafana I can. Would you like me to push the changes to this PR?

**Comment by CrypticSignal** [comment]
@joey-grafana Just checked and it seems like no limit is set by default when using Jaeger, so adding adding `Default: x` placeholder wouldn't make sense unless I implement a default limit. So there are two options: 
1. Implement a default limit for Jaeger which is the same as the limit for Tempo (I would say in another PR?). Once that PR is merged, add a placeholder for Jaeger's `Limit` field in this PR.
2. Don't implement a limit for a Jaeger query and merge this PR as-is

**Comment by joey-grafana** [comment]
Ahh fair enough. In that case, option 2 is best.

**Review by joey-grafana — APPROVED** [review]

**Pull request merged**
