### PR TITLE
Direct Input datasource (alpha)

### PR DESCRIPTION
**Pull request by ryantxu**
This lets you either enter data in the panel or in the shared datasource:

image

vs

image

### CODE REVIEW

**Comment by ryantxu** [comment]
I update the PR and changed the name to 'Input' -- open to other possible names, but I think this is getting close to what it intends to do

**Comment by torkelo** [comment]
One idea I have that could maybe elevate the usefulness of this would be to store the csv data in the Grafana database. An have a separate http API to write / read from it, that way the data source can query that api and if you make changes they would be visible directly in dashboards without a full page reload.

**Comment by ryantxu** [comment]
> would be to store the csv data in the Grafana database

perhaps -- I was thinking about this more in the context of https://github.com/ryantxu/file-system-datasource.  Ideally that could let you write files to disk somewhere that could be stored.

**Comment by ryantxu** [comment]
@torkelo -- can you take another look at this?

If we are ok with the name, I think it is safe to commit to master.  It is alpha :)

In particular, this would be useful to have included while working on #16528 since it has a config page that does not need HTTP settings!

**Comment by ryantxu** [comment]
I give up trying to track down the one type error failing the build 😱 

I converted `public/app/plugins/datasource/mixed/datasource.ts` to strong types to make up for it :)

**Comment by ryantxu** [comment]
I changed the display name to 'Direct Input`:
image

The id and folder name are still `input`, but I think that is ok.

We can explore saving the shared data to the SQL database, but I don't think that should hold up merging this alpha state plugin

**Pull request merged**
