### PR TITLE
TimeSeries/BarChart/XYChart: Allow hiding x axis

### PR DESCRIPTION
**Pull request by dprokop**
This PR brings a missing _Hide x-axis_ feature that was not implemented in the new Time series panel. Additonaly, the same config is now possible for the BarChart and XYChart(alpha).

The solution uses the axis placement field config and does not introduce any new options. 

Additional notes:
- In the future, we may want to consider limiting the available options per field context, as currently, the override created for the x-axis field allows to set the placement to left/right while those values do not have any impact on the visualization. 
- ~~There is no migration for **Hide x axis** old Graph panel's option, as the migrations happen way before the graphable fields are created. And in order to migrate this option, we need to create an override for the particular x field which is not known until React render cycle.~~

### CODE REVIEW

**Comment by torkelo** [comment]
Nice!  i was just playaround with something like this for another side project (multi-chart, graph rows, with only one graph having a time axis)

**Review by oscarkilhed — COMMENTED** [review]
This could be a bit weird for users who have selected to hide the axis but is expecting only the Y axis to be hidden (current behavior). Is it possible to have a migration path where any panel with axis hidden uses the override instead?

**Review by oscarkilhed — APPROVED** [review]

**Comment by dprokop** [comment]
> This could be a bit weird for users who have selected to hide the axis but is expecting only the Y axis to be hidden (current behavior). Is it possible to have a migration path where any panel with axis hidden uses the override instead?

@oscarkilhed this is an excellent observation. I think I've figured out how to have a migrations for both time series and old graph panel. Will update the PR soon.

**Comment by dprokop** [comment]
@oscarkilhed  - I've just pushed migrations that address both your concern and graph(old) -> time series panel switch. Would appreciate one more look at this:)

**Review by oscarkilhed — APPROVED** [review]
Nice!

**Pull request merged**
