### PR TITLE
Influxdb operators

### PR DESCRIPTION
**Pull request by thuck**
This patch includes some missing comparators/operators for influxdb:
`>  - greater than`
`<  - less than`
`<> - not equal`
`!~ - doesn't match against`

It includes the tag.operator fields to facilitate identification of the operators on the segments.
It keeps the logic for the regex syntax; although it changes the way to validate it
 to handle the new operators use case.

### CODE REVIEW

**Comment by torkelo** [comment]
Thanks for contributing! looks like a great start, tests needs to updated and new ones added. Also think about existing graph panels with targets that do not have a tag.operator property

**Comment by thuck** [comment]
hi @torkelo ; could you give an example where it would happen to the tag.operator to not be in the target?

**Comment by torkelo** [comment]
for old queries before this patch

**Comment by thuck** [comment]
Yes, sure; I forgot to test using older graphs. I did a small modification so we have some sane defaults when we we don't have the tag.operator.

**Pull request merged**
