### PR TITLE
Fix Explore not collapsing whitespace

### LINKED ISSUE #15673: Explore: Disabling log options doesn't collapse space on Firefox
Please include this information:
### What Grafana version are you using?
6.0.0
### What datasource are you using?
Loki
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
Browsing Loki logs in Explore mode, I disabled all the log panel options so I could make more room for the application log output.

### What was the expected result?
The columns for timestamp, local time and labels would fully disappear and there would be no whitespace, maximizing application log real estate.
### What happened instead?
The columns for timestamp, local time and labels did not fully collapse, leaving leftover whitespace:

image

 (Ignore the extra timestamps in the app logs, I submitted a Loki [enhancement](https://github.com/grafana/loki/issues/358) to support containerd's log format)

### PR DESCRIPTION
**Pull request by steven-sheehy**
Fixes #15673

Main issue in explore mode is that the column widths were not spaced properly with some columns having whitespace. This was especially problematic with the level column that was tiny but would take up 20% of the screen if all column options disabled. This was due to using max-width and min-width on columns.

- Set container width to 100% so column widths can be calculated properly
- Sets duplicates, level, timestamp, local time to a fixed width based upon em units since the size of these are static
- Sets labels to be 20%
- Remove min-width:80% on message column so that it now consumes remaining space
- Additionally fixes long labels from overflowing into the messages column by properly setting a max-width per label and hiding overflow

### CODE REVIEW

**Comment by davkal** [comment]
Before looking at this, I quite like to repro the issue (https://github.com/grafana/grafana/issues/15673#issuecomment-469275192)

**Comment by steven-sheehy** [comment]
@davkal I just noticed even in Chrome that the duplicates column had the issue as well, so I just committed a fix for that as well.

**Comment by davkal** [comment]
Thanks for your contribution @steven-sheehy 🎉

**Pull request merged**
