### PR TITLE
CI: Retry rate limited github requests

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

Retry on CI failures to check for forks before cloning enterprise due to GH rate limits based on [these instructions](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#handle-rate-limit-errors-appropriately)
Example [clone-enterprise](https://drone.grafana.net/grafana/grafana/171245/5/2) CI step execution (not fork)

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by kminehart** [comment]
I'm not sure that I like this, as it could have an impact of up to an hour of waiting in the absolute worst case. I suspect that on average this will make just about all pipelines that would have normally failed wait at least a few minutes.

That, and I think it will be very tricky to maintain a python script in starlark that is converted to yaml.

Instead, I think it's OK to occasionally have these errors but we should try to reduce the amount of them that happen or find a way to determine if the pipeline is in a fork without querying the API. When I tried I couldn't find a way but maybe someone else could.

We should start with lower hanging fruit IMO. For example, this pipeline is running using the grafana bot github token which is used in a lot of different places. If we were to replace this with a github app or a dedicated token then I think we'd see basically zero of these errors. I'm sure we could find the exact number but I very much doubt that this process alone would be anywhere close to reaching the rate limit.

**Comment by DanCech** [comment]
Have we checked the content of the drone-provided env vars in this case to see whether we'd get eg DRONE_REPO set to the fork?

**Comment by kminehart** [comment]
@DanCech yeah that was the first thing I checked. It's been a while, but since the PR is opened in the Grafana repository, everything looks as if it's coming from Grafana.

**Comment by papagian** [comment]
Closing in favour of an alternative approach

**Pull request closed without merging**
