### PR TITLE
MegaMenu: Fixes mega menu showing scroll indicator when it shouldn't

### LINKED ISSUE #65394: Down arrow appearing when it shouldn't while using topnav
**What happened**:
While using an instance with `topnav` enabled I experienced an arrow that (to me) indicates there's scrollable content, but in reality there's no additional content to scroll. This feels like a bug and is a confusing user experience.

**What you expected to happen**:
I would expect the down-scroll-arrow to only appear when there's actually scrollable content.

**How to reproduce it (as minimally and precisely as possible)**:

Using Safari 16.3 do the following...

1. Set browser zoom to 85%
2. Login to a Grafana instance with `topnav` enabled
3. Open the navigation
4. Collapse any open headers so they're all closed
5. Open just the "Dashboards" heading
6. (**Problem should be visible here**) A slight overlay with a down-scroll-arrow should appear over the "Administration" heading

**Anything else we need to know?**:
I _assume_ the issue is related to the page zoom in some way. When I flip between 85% zoom and 100% zoom I experience different behavior. At 100% zoom the navigation and down-scroll-arrow work as expected.

Here's a screen recording of me replicating the behavior. Note, when the video starts my browser is at 85% zoom and I go up and down using cmd +/-.

https://drive.google.com/file/d/1Lht7DzlOqScwh2IZ9crGus2wvEZAgkKq/view?usp=sharing

**Environment**:
- Grafana version: Grafana v9.5.0-53754pre
- User OS & Browser: 2021 14-inch MacBook Pro (`13.2.1 (22D68)`) with Safari (`16.3`)
- Others: I'm using Safari with 85% page zoom instead of 100%.

### PR DESCRIPTION
**Pull request by torkelo**
Fixes https://github.com/grafana/grafana/issues/65394

Noticed this hover indicator in the MenuMenu last couple of days. 

This PR fixes 
* Make sure the content expands to full height so we don't show the scroll indicator when we don't need to
* Fixes the position of the close button for mobile views (was not aligned with the topnav top section). Also adds a border bottom to the mega menu mobile header (so that it looks the same as the normal bottom half of topnav) 

This is the bug I am seeing
Screenshot from 2023-03-28 15-32-50

Not sure if we should backport this or not? (as topnav is being rolled out more and more to cloud in 9.4.x ?)

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure if we should backport this or not? (as topnav is being rolled out more and more to cloud in 9.4.x ?)

**Review by ashharrison90 — COMMENTED** [review]
padding looks good 👍 

but these changes regress showing the scroll indicator in mobile view. with the mobile header, setting `height: 100%` makes it taller than the screen so it doesn't work anymore 😢 

i've never been able to repro the bug with the scroll indicator so i can't tell if this fixes it or not... i **really** hope it does 🤞 are there any specific steps you needed to take to see it? 🤔

**Comment by ashharrison90** [comment]
also re: backporting - i think we should, same as we would for any other bugfix 👍

**Comment by torkelo** [comment]
@ashharrison90 fixed the mobile issue, was easy standard flex fix :)

**Review by ashharrison90 — APPROVED** [review]
looks great! 🥳 

hope it fixes the issue for everyone 🤞

**Pull request merged**
