### PR TITLE
Prometheus/Promlib: Remove the PrometheusDataplane feature so always enabled

### PR DESCRIPTION
**Pull request by kylebrandt**
**What is this feature?**

Enables dataplane compliant output from prometheus

**Why do we need this feature?**

Been enabled by default since 10, so mostly cleanup. Also want to eliminate the possibility of accidental regression on this.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by kylebrandt** [comment]
Forgot there was a FE part to this as well:

```src/result_transformer.ts:57:29 - error TS2339: Property 'prometheusDataplane' does not exist on type 'FeatureToggles'.```

**Review by bohandley — APPROVED** [review]
LGTM!

**Review by ryantxu — APPROVED** [review]
🎉

**Comment by pbannykh** [comment]
Hi, I’ve been using Grafana for sending alerts via webhooks, and the evalMatches payload includes a metric label. After enabling PrometheusDataplane, I noticed that the value of metric changed, which affected my webhook processing. Because of this, I had to manually disable the feature.

Now that this feature is always enabled, how can I ensure compatibility with the previous format? Is there a recommended workaround?

Thanks!

**Comment by itsmylife** [comment]
@pbannykh Since this feature is enabled by default and will stay that way there is no option to go back to old format. I'd say you need to ensure your process is compatible with the dataplane. Please see the documentation here: https://grafana.github.io/dataplane/

**Comment by pbannykh** [comment]
Would it be possible to get customName in alerts in the future?

https://github.com/grafana/grafana/pull/92218/files?diff=unified&w=0#diff-60590cacf315814342c4ade3cefde61832b8248b35fb022831625040c69062b9R120-L129

**Comment by itsmylife** [comment]
@pbannykh I don't think so. But I'd suggest using [transformations](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/) or [field overrides](https://grafana.com/docs/grafana-cloud/visualizations/panels-visualizations/configure-overrides/).

**Comment by pbannykh** [comment]
https://github.com/grafana/grafana/issues/75027

**Pull request merged**
