### PR TITLE
Prometheus: Disable hasLabelsMatchAPISupport for Thanos

### PR DESCRIPTION
**Pull request by ye-will**
**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

As mentioned in issue https://github.com/thanos-io/thanos/issues/6338 & https://github.com/thanos-io/thanos/issues/3639,

`/api/v1/label/<label_name>/values` does not work as expected right now.

We should disable hasLabelsMatchAPISupport() for Thanos.

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by itsmylife** [comment]
LGTM. @gtk-grafana could you please take a look at as you have more insight about this?

**Comment by gtk-grafana** [comment]
@ye-will It looks like Thanos is still planning to address this issue, instead of Grafana forcing all users with Thanos versions selected to use the /series endpoints, users can select a compatibility version (or just not select any version), and then get the fallback API calls, that way when Thanos is able to address this bug people can start using the new functionality without waiting for Grafana to implement and ship another fix?

**Comment by gtk-grafana** [comment]
@ye-will I'll reach out to the CNCF and see if we can get an update from them as to the status of those issues. If Thanos doesn't support the match[] parameter on the label/.../values then Grafana & CNCF should do a better job of documenting that.

**Comment by gtk-grafana** [comment]
I reached out via the CNCF Thanos slack channel, but I have yet to hear a response. I'll try to check back in with them this week.

**Comment by gtk-grafana** [comment]
My request was acked: https://cloud-native.slack.com/archives/CK5RSSC10/p1685018637397729, but still waiting on response

**Comment by GiedriusS** [comment]
Fixed in Thanos in https://github.com/thanos-io/thanos/pull/6816.

**Comment by itsmylife** [comment]
@GiedriusS Thanks for pinging us. Much appreciated! 
@gtk-grafana This is fixed in Thanos. Is there anything we should do right now? I know you said we should have something better for version-checking but just want to update my information.

**Comment by gtk-grafana** [comment]
Nope, this issue can be closed out as the bug was fixed in Thanos.

**Pull request closed without merging**
