### PR TITLE
Logs Panel: Improve performance for panels with a lot of logs

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

This PR is to discuss potential fixes to https://github.com/grafana/grafana/issues/34038#issuecomment-851968266

**Problem**

Rendering log panel with too many logs may cause performance issues, i.e.
- delay of showing the context menu (when the panel header/chevron is clicked)
- laggy dragging

I haven't found the root cause yet. It still needs more investigation. Both issues seem to be related, though. This PR is to discuss solutions and it also presents an idea how to mitigate the problem by reducing number of log rows.

**Delayed context menu opening**

It is somehow related to `react-draggable-transparent-selection` class being added/removed to the body element [here](https://github.com/react-grid-layout/react-draggable/blob/v4.0.3/lib/utils/domFns.js#L157) even when the panel header is not dragged, but just clicked. This means the class is added/removed when the context menu is opened:

Screenshot 2021-06-02 at 11 34 47

Note: in theory to prevent it we could also stop event propagation in PanelHeaderMenuTrigger but on capture phase because react-draggable uses capture phase for all events:

```diff
   const onMouseDown = useCallback(
     (event: MouseEvent<HTMLDivElement>) => {
+      event.stopPropagation();
       setClickCoordinates(eventToClickCoordinates(event));
     },
     [setClickCoordinates]
   );
 
   return (
-    <div {...divProps} className="panel-title-container" onClick={onMenuToggle} onMouseDown={onMouseDown}>
+    <div {...divProps} className="panel-title-container" onClick={onMenuToggle} onMouseDownCapture={onMouseDown}>
       {children({ panelMenuOpen, closeMenu: () => setPanelMenuOpen(false) })}
     </div>
   );

```

Adding the class to the root element should not be the problem per-se. Something else is probably triggering recalculation of all log rows (?). I thought it was related to `DraggableCore` and layout changes/calculation but removing suspects did not improve on the delay for the context menu. However, removing the code that adds/removes the class removes the problem for the delay of the context menu. 

*This problem is visible only when there's a lot of logs so fixing laggy dragging can potentially fix it as well.*

**Laggy dragging**

Laggy dragging could be caused by the fact that all rows are rendered (also not visible on the screen). Some elements are positioned relatively so I guess updating the layout may take a bit longer when the parent container moves (?). I'm not 100% sure yet what's the bottleneck.

It could be improved with virtualization but in case of logs the rows have dynamic height. The height changes when details are shown or details about fields are expanded. To make it work it requires some fiddling with react-window `VariableSizeList` component. It still could be an option but probably worth getting to the root cause first.

In case this issue proves to be a pain and there are no other easy fixes, this PR introduces lazy rendering. The user has to click on "show more rows" to render more logs. It improves performance of loading the context menu and dragging:

https://user-images.githubusercontent.com/745532/120461272-26e73a80-c39a-11eb-831d-01e2b39263e5.mov

**Which issue(s) this PR fixes**: 

N/A

**Special notes for your reviewer**:

It can be tested with test data and a panel with ~1000 logs.

### CODE REVIEW

**Comment by aocenas** [comment]
This won't solve the delay because of the recalculation but I found that on resizing we do rerender all the logs https://github.com/grafana/grafana/pull/35379.

**Comment by zoltanbedi** [comment]
Can we close this? #35379 fixed the issue isn't it?

**Comment by ifrost** [comment]
> Can we close this? #35379 fixed the issue isn't it?

I think #35379 improved performance on resizing a bit but it didn't solve the problem.

**Comment by aocenas** [comment]
Yup this is still an issue, not sure how big it is I would wait whether it bothers other people before spending too much time on it. You can still just limit the number of logs in the panel options, right?

**Comment by ifrost** [comment]
> Yup this is still an issue, not sure how big it is I would wait whether it bothers other people before spending too much time on it. You can still just limit the number of logs in the panel options, right?

Yep (as long as you know this is causing the problem :)). I'll close this one for now, we can come back to it if it proves to be a problem.

**Pull request closed without merging**
