### PR TITLE
Alerting: Add metadata field with editor_settings to alert rule

### PR DESCRIPTION
**Pull request by alexander-akhmetov**
**What is this feature?**

Adds the `metadata.editor_settings` field to the API and the AlertRule model:

```
metadata:
  editor_settings: {
    simplified_query_and_expressions_section: true
  }
}
```

It's a JSON because `simplified_query_and_expressions_section` is only the first field, and there will be more.

**Why do we need this feature?**

Related to https://github.com/grafana/grafana/pull/93022. Adds rule-level persistence for the editor settings used to change and save the rule.

**Which issue(s) does this PR fix?**:

Part of https://github.com/grafana/alerting-squad/issues/849

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM from the FE perspective! (new field data structure)

**Review by yuri-tceretian — COMMENTED** [review]
WDYT About more generic field like `metadata`, and then store editor settings in a nested field? 
This will be useful when we migrate to K8s API. We will be able to store some random info like creator and created timestamp.

**Review by yuri-tceretian — APPROVED** [review]
LGTM.

It would be great if we follow up and add more fields there, like user that created and modified, timestamp.

**Pull request merged**
