### PR TITLE
Prometheus: Refactor exemplar sampler

### PR DESCRIPTION
**Pull request by toddtreece**
**What is this feature?**

* Adds `Sampler` interface with new no-op and existing standard deviation implementations
* Split label tracking out of sampler
* Implement `Framer` for exemplars

**Why do we need this feature?**

Should simplify disabling sampling in #60105 with the no-op sampler, and sets up a structure for adding another sampling approach that @leeoniya requested in https://github.com/grafana/grafana/pull/60281

**Who is this feature for?**

@leeoniya 

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by itsmylife — APPROVED** [review]
This looks awesome 🚀 
`Sampler` interface is quite useful. 
~~I will create a separate issue for us to have unit tests to cover the new code.~~
You have the tests here: https://github.com/grafana/grafana/pull/60281

**Comment by toddtreece** [comment]
@itsmylife i'll sync with `main` and pull those tests into this branch before merging later today or tonight

**Review by nmarrs — APPROVED** [review]
LGTM - any blockers on this being merged (other than resolving current merge conflicts?)

**Review by chri2547 — COMMENTED** [review]
No docs to review.

**Pull request merged**
