### PR TITLE
Panel exports in share modal

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**

Moves panel exports from the initial panel menu to the share modal and adds more options.

**Why do we need this feature?**

Bring more options to a export a panel

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Setup instructions with the image renderer plugin:
- Set the following params in your config for `[rendering]`:
```
[rendering]
server_url = http://localhost:8081/render
callback_url = http://host.docker.internal:3000
```

- Run `docker run --platform=linux/amd64 -p 8081:8081 -e AUTH_TOKEN='-' grafana/grafana-image-renderer:latest`
- Use the Share modal -> Image tab to download a panel image

TODO:
- [ ] Tests
- [ ] Check functionality with scenes
- [ ] Add a ff
- [ ] Docs

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by codeincarnate — CHANGES_REQUESTED** [review]
Maybe I'm crazy but I haven't been able to get this to work 😢. I don't have the image renderer plugin installed. I know it's not needed but is this messing up if it isn't installed?

**Comment by torkelo** [comment]
Can we wait with this a few weeks? We are currently rewriting the share modal for scene dashboards, this old share modal & components are soon to be deleted, to be replaced by https://github.com/grafana/grafana/tree/main/public/app/features/dashboard-scene/sharing , we are currently working through all these components and rewriting them

**Comment by mdvictor** [comment]
@codeincarnate, this version of panel exports does need the image renderer plugin. Using it makes sure that any panels can be exported. There were some problems in exporting the canvas directly that caused issues in some panels (e.g geomap if I recall). To run the image renderer locally I'm doing this:

`docker run --platform=linux/amd64 -p 8081:8081 -e AUTH_TOKEN='-' grafana/grafana-image-renderer:latest`

and set the grafana `rendering` config to:

```
[rendering]
server_url = http://localhost:8081/render
callback_url = http://host.docker.internal:3000
```

Probably should have put these instructions in the PR description 😅

**Comment by mdvictor** [comment]
@torkelo I think this can be continued now? Is the scenes migration finished for the Share modal?

**Comment by mdvictor** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/79325

**Pull request closed without merging**
