### PR TITLE
Docs: Add Cloud content links

### PR DESCRIPTION
**Pull request by oddlittlebird**
This PR adds links to two new Grafana Cloud topics that are related to Grafana content.

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
These look great, thanks!

**Comment by oddlittlebird** [comment]
@robbymilo, is the website build failing because the Docker build is not updated to include the new files?

**Review by achatterjee-grafana — APPROVED** [review]
LGTM!

**Comment by oddlittlebird** [comment]
@robbymilo , can you tell me what is wrong with my links?

**Comment by robbymilo** [comment]
@oddlittlebird Two things:
- The grafana cloud docs are not included in the docker image, so even a correct relref would not work in the preview. We can consider adding them once we start building the image more often.
- It should be [Grafana Cloud Linux host Quickstart](/docs/grafana-cloud/quickstart/)

**Comment by oddlittlebird** [comment]
> * The grafana cloud docs are not included in the docker image, so even a correct relref would not work in the preview. We can consider adding them once we start building the image more often.

Please do this. We will be crosslinking more and more often between the different doc sets as we continue to expand and integrate the documentation.

**Pull request merged**
