### PR TITLE
DashboardScene: Fixes react panels with old angular options

### LINKED ISSUE #77260: DashboardScene: Legacy panel migrations are not executed
We have an issue with running panel migration handlers. Those migration handlers assume the argument passed to them is the full `PanelModel`. But, in scenes' `VizPanel` only [a limited PanelModel](https://github.com/grafana/scenes/blob/main/packages/scenes/src/components/VizPanel/VizPanel.tsx#L133C31-L133C31) is passed to those migration handlers, skipping options that might have been attached to the root of the `PanelModel`. A good example is [dashlist panel migration](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/dashlist/migrations.ts#L39). In a dashboard using `DashboardScene` this  migration will have no effect.

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #77260 

Problem
* Angular panels that change from angular to react (Without any change to panel plugin id), only rely on using the panel migration handler to transfer old angular options to the new options structure. In scenes we only support this when the plugin id changes as well (as then we call the onPanelTypeChanged migration handler). But when it's the same plugin Id we just call the normal "version" migration handler and to this handler we do not pass the old root level properties. 

Tested with an old version of the home gev dashboard (has old dashlist panels with panel model root level options):
https://github.com/grafana/grafana/blob/v7.5.15/devenv/dev-dashboards/home.json

### CODE REVIEW

**Review by ivanortegaalba — APPROVED** [review]
Tested with graph panel in dashboards and it works 💯 

Maybe @nmarrs can have a quick look at it, since he has been working a lot on Angular viz migration

**Comment by torkelo** [comment]
> Tested with graph panel in dashboards and it works 

graph panel? that panel changes plugin id, so is not affected by this change 

@ivanortegaalba

**Comment by ivanortegaalba** [comment]
> > Tested with graph panel in dashboards and it works
> 
> graph panel? that panel changes plugin id, so is not affected by this change
> 
> @ivanortegaalba

I'm sorry, I'm having trouble understanding when the pluginId changes and when it doesn't. Can you please provide more context or information to help me to undertand?

**Comment by torkelo** [comment]
@ivanortegaalba we have some panels like dashlist and heatmap that where previously angular panels, timeseries has always been a react panel, the angular panel had a plugin id of "graph" , so it's a change of pluginId which triggers a different migration path (onPanelTypeChanged).

**Pull request merged**
