### PR TITLE
Dashboard link rendering

### PR DESCRIPTION
**Pull request by bgranvea**
**What this PR does / why we need it**:
This PR adds a new type of dashboard links: rendering links. This allows to create a link to get a PNG rendering of the full dashboard.

**Which issue(s) this PR fixes**:
This is an implementation of feature request #21556.

### CODE REVIEW

**Comment by hugohaggmark** [comment]
@dprokop @torkelo is this new feature something that we've planned to implement?

**Comment by torkelo** [comment]
no, this is a new feature request that I have not seen requested before. 

I think it's interesting but would need to know more about the use case / demand for this. And start with adding image render option/tab to dashboard share modal

**Comment by bgranvea** [comment]
> no, this is a new feature request that I have not seen requested before.
> 
> I think it's interesting but would need to know more about the use case / demand for this. And start with adding image render option/tab to dashboard share modal

My use case is to add an "Export to PDF" link on my dashboards. Besides this PR, I also need https://github.com/grafana/grafana-image-renderer/pull/80 and https://github.com/grafana/grafana/pull/21307 to achieve this.

Maybe this link should be added to the dashboard share modal. The problem that I see is that for a clean PDF rendering, I have to set several options (paper size, margins...). In particular, I set a scaling factor so that the rendering fits on a single page (it seems difficult to manage multi-page PDF). This scaling factor is some magical number that the designer of the dashboard chooses, not the end user. 

I also have some technical and specific parameters for the renderer like CSS rules in order to disable some elements of the page (side menu, scroll canvas) but I suppose this could be done another way?

**Comment by dprokop** [comment]
@bgranvea thanks for your PR. We have discussed it and we don't feel like adding this feature to Grafana now.

**Pull request closed without merging**
