### PR TITLE
Drone: Use ${DRONE_TAG} in release pipelines, since it should work

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
From the release build of v7.3.1-beta1, it did look as if ${DRONE_TAG} is available after all, so this PR makes the release pipelines use it (additionally fixes a bug). There's also some mixin linting enabled, since .drone.yml hadn't been re-generated on master.

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]

**Comment by kylebrandt** [comment]
Just curious, what does the double `$$` do?

**Comment by aknuds1** [comment]
> Just curious, what does the double `$$` do?

@kylebrandt Good question! It's necessary to escape `$` in .drone.yml since Drone uses it to substitute its own variables, f.ex. `${DRONE_TAG}`.

**Comment by aknuds1** [comment]
@bergquist This one [fails](https://drone.grafana.net/grafana/grafana/4700/1/6) due to the mixin linting you introduced.

**Comment by kylebrandt** [comment]
Removed cp label because it is in beta2, and see this in the v7.3.x branch already

**Pull request merged**
