### PR TITLE
Handle unpublish by deprecating package

### LINKED ISSUE #23308: Better support canary packages publish
We currently publish new "canary" packages whenever something in the packages files change on master.  However if the time between changes is longer than npms unpublish rules, the build fails and a new package is not published.

See:
image

We should update this logic so we:
1. catch the error
1. call `npm deprecate -f '@grafana/... `
1. continue publishing the new artifact

With the current behavior the canary packages get left in a weird state and fail to load.  It requires another change to a packages file to be pushed before trying to publish again

### PR DESCRIPTION
**Pull request by srclosson**
Fixes #23308

Why? Simple: We want to handle a non 0 exit code from npm unpublish with a little more logic.
If the package cannot be unpublished, deprecate the previous package. 
If that fails, I've still opted to log the error code, and return it. But we may want to ignore the error? Not sure... depends I guess.

### CODE REVIEW

**Comment by dprokop** [comment]
Ok, this sort of makes sense, but... What exact situations do you address here? Can't really recall much troubles with unpublishing.  I assume you are referring to situations when the next canary version failed to publish, but the previous one was already unpublished?

**Comment by srclosson** [comment]
Maybe @ryantxu can comment a little bit more. As I understand it if you are publishing a canary version frequently, the unpublish works fine, but less frequently it does not. There was some documentation somewhere that said, deprecate the version. Ryan can you comment with more details?

**Comment by ryantxu** [comment]
@dprokop see https://github.com/grafana/grafana/issues/23308

This happened again yesterday...  and happens every month or two.  End result is that anything depending on canary does not build consistently

**Comment by dprokop** [comment]
Ok, I see your point. After 72h we can only deprecate. Let's do it.

**Review by dprokop — APPROVED** [review]

**Pull request merged**
