### PR TITLE
SupportSnapshots: SceneObject as state manager pattern test 

### PR DESCRIPTION
**Pull request by torkelo**
Just a fun test to see how the SceneObject state pattern could simplify a component that uses a heavy amount of useState, useAsync and event handlers. 

* As a simpler alternative to redux or useReducer + createSlice + thunks 
* Capturing what is good with functional components and some hooks while preserving a simple state system and simple React code with no need for useCallback or hooks with dependency lists. 

Todo 
* [ ] add some tests
* [x] Add a plain version of SceneObject base that has none of the nesting or other scene-related stuff but only the state bit 

To compare
 * SupportSnapshot with useState, useAsync and event handlers: https://github.com/grafana/grafana/blob/aeb5c2251d6e45be69ec1eeaa14b1bd5a49c1059/public/app/features/dashboard/components/SupportSnapshot/SupportSnapshot.tsx
 * After moving all state and logic to a "SceneObject" https://github.com/grafana/grafana/blob/2362cc8db5eb9593c64949da41ac59d6231b1220/public/app/features/dashboard/components/SupportSnapshot/SupportSnapshot.tsx
*  The SceneObject (poorly named, not sure what to call it) https://github.com/grafana/grafana/blob/2362cc8db5eb9593c64949da41ac59d6231b1220/public/app/features/dashboard/components/SupportSnapshot/SupportSnapshotService.ts

### CODE REVIEW

**Comment by ryantxu** [comment]
interesting -- this moves all the state logic into something easier to reason about 🎉 

If `StateManagerBase` is feeling like a good path forward for scenes, then this is a great place to test it out (and hopefully soon use a real scene!  it won't have template variables so much easier)

If that object is still a WIP that we are not sure we want to support then maybe better to leave with the more verbose version?

**Comment by torkelo** [comment]
@ryantxu I don't think StateManagerBase works that wela l as base for SceneObjects as SceneObjects has some added complexity of parents set in ctor, and state updates, events emitted by setState, so it would basically override everything in StateManagerBase, StateManagerBase just takes the bare minimum concepts from SceneObject (state subject, & useState). 

Any ideas for alternative names for StateManagerBase? 

* SimpleStateObject
* StateClass
* StateManagerClass
* StateAndLogicContainer 
* MakesReactGreatAgain

**Comment by torkelo** [comment]
merged into https://github.com/grafana/grafana/pull/55059

**Comment by dprokop** [comment]
@torkelo I really like this pattern TBH, think it's very elegant and simple. The only thing I'm slightly anxious about is the `forceUpdate` when updating the model state. I mean - I have the same concern in the Scene's work. What would usually be handled by React, now requires a cautious implementation of underlying components, that will use this model, to avoid costly re-renders - maybe this is a good thing in the end to pay attention what and how a component renders. I would expect this pattern to result in more React.memo and pure components. 

I haven't checked yet, but I think it's interesting to see how does TimeSeries and other uPlot based visualizations lifecycle look like now with this forceUpdate in the Scene's work. I hope this does not cause the entire uPlot to re-init when not necessary.

**Comment by torkelo** [comment]
@dprokop 
> The only thing I'm slightly anxious about is the forceUpdate when updating the model state

not sure I understand you, the same behavior is there for useSelector or useState, also triggers a re-render. What do you mean handled by React?  if we used redux we would use useSelector or some other hook that does the same exact thing (Subscribe to something that when called triggers a re-render)

>  I hope this does not cause the entire uPlot to re-init when not necessary.

Not sure how that relates to what triggers a re-render from parent. Today we also have events that forceUpdates: 
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L177  
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/DashboardGrid.tsx#L57

useForceUpdate is implemented using useState, so there is nothing magical about it. 

What we could do make SceneObject useState more advanced/efficient is to have it support a  state selector, then we can use useSyncExternalStore to limit re-renders to only when that selector returns something different. But so far I have not seen any need for that. But if we start seeing really large Scene objects with a lot of state that many different other react components subscribe to then that is an option 

https://reactjs.org/docs/hooks-reference.html#usesyncexternalstore

**Comment by torkelo** [comment]
@dprokop but I agree that there could be something we are missing, that could cause issues. The thing I was worried about are possible timing issues, and lack of batching state changes (technically we can batch changes if they are done from parent/roots) but they would require new model instances for children to be considered one in a single batch. But if a parent wanted to update state of many children (without creating new SceneObject instances) it would cause one update per child object. Similar afraid of timing issues of deletes and cleanup happening while child updates. But I think due to the single threading of javascript (single event loop) that should not be a problem but not 100% sure yet

**Comment by dprokop** [comment]
> if we used redux we would use useSelector or some other hook that does the same exact thing

I didn't know it uses `forceUpdate` under the hood, but now when I think about it it makes sense.

**Pull request merged**
