### PR TITLE
Transformations: Move transformation variables to general availability

### PR DESCRIPTION
**Pull request by samjewell**
From Slack [here](https://raintank-corp.slack.com/archives/C04J73AAQ87/p1717028049855119?thread_ts=1716917051.229979&cid=C04J73AAQ87)
and [here](https://raintank-corp.slack.com/archives/C04J73AAQ87/p1717398166405599?thread_ts=1716917051.229979&cid=C04J73AAQ87):

> it should have been GA like 5 months ago :sweat_smile:

> I agree it was way too cautious putting this behind a feature flag. Just caused a lot of unnecessary process which ultimately led to it being stagnant and forgotten. I'm fine with just setting this to GA

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by ryantxu** [comment]
or remove the feature toggle entirely?

**Comment by leeoniya** [comment]
it looks like there are diffetent code paths for this feature. so removing the toggle means also removing all the `else` branches :)

probably okay to first GA it so we can easily turn it off if anyone has issues first. then remove the toggle and code once it has baked on Slow for a while.

**Comment by samjewell** [comment]
> The base branch restricts merging to authorized users

Would one of you mind merging this also @ryantxu or @leeoniya? I don't have permission.

I took a stab a the `backport` and `changelog` labels, but please update these if you think I've made the wrong call.

**Comment by samjewell** [comment]
> Would one of you mind merging this also @ryantxu or @leeoniya?

Updated the title to meet the needs of the changelog check, so I think this is good now.

**Review by nmarrs — APPROVED** [review]

**Comment by ifrost** [comment]
Moving it 11.2.x milestone as it was merged after the cut-off of 11.1.x. Please create a backport to 11.1.x if you'd like it be included in next monthly patch release (11.1.1)

**Pull request merged**
