### PR TITLE
Chore: Add go-redis v8 dependency

### PR DESCRIPTION
**Pull request by toddtreece**
**What this PR does / why we need it**:

`go-redis` added support in version 8 for passing `context.Context` to commands. This is needed for the following changes to query caching:
* https://github.com/grafana/grafana-enterprise/issues/1927
* https://github.com/grafana/grafana-enterprise/issues/1915

**Which issue(s) this PR fixes**:

Fixes:
* https://github.com/grafana/grafana-enterprise/issues/1930

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kminehart** [comment]
How much work would it be to replace v5 with v8 instead of having 2 separate dependencies?

If v8 is only used in Grafana Enterprise, you need to add an empty import in `pkg/extensions/main.go`

**Comment by toddtreece** [comment]
@kminehart sure, no prob. i can update them

**Comment by kminehart** [comment]
I didn't look to see if they were gigantic files or anything so if there's like 50+ changes necessary then we can save it for another PR. your call

**Comment by toddtreece** [comment]
@kminehart it looks like `remotecache` is used in multiple repos.  i'm guessing the breaking change to the `remotecache` API might need to wait for a major release unless you think it's ok to use `context.TODO()` for now

**Comment by kminehart** [comment]
`context.TODO()` is totally fine for now. This will help with our effort to use context everywhere which I think we want to do in the next couple months. :)

**Review by kminehart — APPROVED** [review]
Makes sense! the v5 `WithContext` function wasn't used so we don't have to worry about that here.

**Pull request merged**
