### PR TITLE
Chore: use Wrap for all admin API

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Standardize the API to use the `Wrap` function for all `/api/admin` endpoints.

**Special notes for your reviewer**:
Having a standardized API makes it easier to add feature across the whole API like auditing.

### CODE REVIEW

**Comment by kylebrandt** [comment]
I think ... *maybe* ... the test is failing because of `ServerError(err)`?

```
func Wrap(action interface{}) macaron.Handler {
	return func(c *models.ReqContext) {
		var res Response
		val, err := c.Invoke(action)
		if err == nil && val != nil && len(val) > 0 {
			res = val[0].Interface().(Response)
		} else {
			res = ServerError(err)
		}

		res.WriteTo(c)
	}
}
```

```
var (
	NotFound = func() Response {
		return Error(404, "Not found", nil)
	}
	ServerError = func(err error) Response {
		return Error(500, "Server error", err)
	}
)
```

**Comment by aknuds1** [comment]
@kylebrandt Interesting. At least the tests are doing their job :D

**Comment by aknuds1** [comment]
@AgnesToulet Can you look into why the tests are failing?

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Tests need fixing.

**Review by aknuds1 — APPROVED** [review]
Looks great AFAICT.

**Pull request merged**
