### PR TITLE
Add Prometheus datasource

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
@torkelo As discussed.

/cc @juliusv @fabxc

**Comment by torkelo** [comment]
merge conflicts due to the squashing of the previous commits :(

**Comment by jimmidyson** [comment]
Well yeah we knew that... I can rebase against the prometheus branch if you'd like?

**Comment by torkelo** [comment]
sorry, yea, that would be great.

**Comment by jimmidyson** [comment]
Done.

**Comment by torkelo** [comment]
Awesome!

**Comment by fabxc** [comment]
\o/

**Comment by jimmidyson** [comment]
@fabxc Don't get carried away- this is only merged to Prometheus branch, not master.

@torkelo Let me know if there's anything I can do to help get this into master ready for next release.

**Comment by torkelo** [comment]
some basic docs here https://github.com/grafana/grafana/tree/master/docs/sources/datasources would be good, unit test for metricFindQuery , have some ideas to improve the editor but that could wait until after merge

**Comment by fabxc** [comment]
I know :) but we are going somewhere.

**Comment by torkelo** [comment]
@jimmidyson actually I think it is pretty close the more I look at it, might even make it for 2.5 release (beta soon), mostly because the code & editor is pretty minimal and not so complex. There is no real big change / refactor that needs to be happen before merge I think (some things like change schema / query model is good to rethink before major release/merge to master as it is harder to change the model later)

**Comment by jimmidyson** [comment]
Ah that's great news! I'll get to docs & unit tests tomorrow I hope.

**Comment by juliusv** [comment]
I gave this a test drive today and these are my thoughts about the experience:

https://gist.github.com/juliusv/0b2f5db67c1b65153688

Only one real bug / critical issue. The others are important UX-wise too, but shouldn't be blockers for inclusion of the datasource in Grafana AFAICS.

**Comment by juliusv** [comment]
And yeah, I didn't file those each as GitHub issues yet because they are more of a collection of thoughts for discussion at the moment, but can do so later if desired.

**Pull request merged**
