### PR TITLE
Plugins: Let descendant plugins inherit their root's signature

### LINKED ISSUE #27364: App plugin marked as signed but data source can't start
**What happened**:
Signed application plugin with data source included can't run data source backend.

Screenshot from 2020-09-03 12-30-57

**What you expected to happen**:
Backend data source up and running.

**How to reproduce it (as minimally and precisely as possible)**:
Get the [latest Zabbix plugin version](https://github.com/alexanderzobnin/grafana-zabbix/releases/download/v4.0.1/alexanderzobnin-zabbix-app-4.0.1.zip), install it and run Grafana.

**Anything else we need to know?**:
That's happened because grafana scans plugins folder and loads plugins from every folder containing the `plugin.json` file. Then grafana checks every plugin for valid signature. So if app has tree similar to this:
```
example-app
|-- example-datasource
|  |-- plugin.json
|  |-- datasource_executable
|-- example-panel
|  |-- plugin.json
|-- plugin.json
|-- MANIFEST.txt
```
then datasource will be treated as unsigned, however plugin has correct MANIFEST file with all files insluded.

Logs from grafana:
```
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Scanning external plugins directory" logger=plugins dir=/var/lib/grafana/plugins
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=alexanderzobnin-zabbix-datasource
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Invalid Plugin Signature" logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginD
ir=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix state=unsigned
t=2020-09-03T15:17:03+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" i
s unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=alexanderzobnin-zabbix-app
t=2020-09-03T15:17:04+0000 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=alexanderzobnin-zabbix-app
```

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Zabbix
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Let plugins embedded beneath a root plugin inherit their root's signature, if they don't have a valid one themselves.

Had to generally rewrite the plugin loading logic a bit to enable the goal.

**Which issue(s) this PR fixes**:

Fixes #27364.

### CODE REVIEW

**Comment by aknuds1** [comment]
@alexanderzobnin Are you able to test and see if this works for you?

**Review by alexanderzobnin — CHANGES_REQUESTED** [review]
Tried to test this out, but it still fails with unsigned plugin error:
```
DBUG[10-02|11:24:15] Getting signature state of plugin        logger=plugins plugin=alexanderzobnin-zabbix-datasource hasRoot=false
DBUG[10-02|11:24:15] Invalid Plugin Signature                 logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginDir=/home/alex/development/grafana-zabbix/dist/alexanderzobnin-zabbix-app/datasource-zabbix state=unsigned
EROR[10-02|11:24:15] Failed to load plugin                    logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/home/alex/development/grafana-zabbix/dist/alexanderzobnin-zabbix-app/datasource-zabbix
INFO[10-02|11:24:15] Registering plugin                       logger=plugins name="Zabbix Problems"
INFO[10-02|11:24:15] Registering plugin                       logger=plugins name=Zabbix
WARN[10-02|11:24:15] Some plugins failed to load              logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
```

As you can see in the logs, datasource plugin included in the bundle is not recognized as a part off app plugin (`hasRoot=false`). So probably, issue somewhere in the 2nd pass of plugin scanner
https://github.com/grafana/grafana/pull/27970/files#diff-0ef6be628408cceaa1218dbe764e9885R232

You can try to use my signed plugin from the latest release assets:
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.0.1

**Comment by aknuds1** [comment]
@alexanderzobnin Thanks, having a look.

**Comment by aknuds1** [comment]
Found the problem, thinking up a fix.

**Comment by aknuds1** [comment]
@alexanderzobnin Can you please try the latest revision? From my testing it loads zabbix-datasource successfully.

**Review by wbrowne — APPROVED** [review]

**Review by alexanderzobnin — APPROVED** [review]
Works well now! Thanks!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
