### PR TITLE
Traces: Filter by service/span name and operation in Tempo and Jaeger

### LINKED ISSUE #48047: Tempo Search UI: Service Name and Span Name prefix search do not work
**Describe the bug**
Tempo search on Grafana explorer has selects with prefix search for **Service Name** and **Span Name**, the prefix search does not filter the service/span lists.

**To Reproduce**
1. Run tempo-search example (https://github.com/grafana/tempo/tree/main/example/docker-compose/tempo-search)
2. Go to Grafana explorer, then select tempo datasource, and then select the tap **Search-Beta**
3. In the section **Service Name** type any value from the provided list (Same for **Span Name**)
image

**Expected behavior**
The list of services should show just the services that match the specified prefix.

**Anything else we need to know?**:
I can't reproduce the issue on `8.5.0-50432pre commit: eb9d85a2bf`. I can reproduce in `8.4.7`, `8.5.0-beta1` and in `main` (9.0.0)

**Environment**:
- Grafana version: `8.4.7`, `8.5.0-beta1` and in `main` (9.0.0)

- Data source type & version: Tempo 1.3.2

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:
Previously when you typed into the service/span name `AsyncSelect` filed in Tempo or the service name/operation `AsyncSelect` field in Jaeger it would not filter the results based on what you typed in. This PR allows us to filter by service/span name and operation in Tempo and Jaeger.

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/grafana/issues/48047

### CODE REVIEW

**Review by connorlindsey — APPROVED** [review]
LGTM although do you think it'd be worth using fuzzy search here?

**Comment by joey-grafana** [comment]
> LGTM although do you think it'd be worth using fuzzy search here?

Agreed! Added 👍

**Comment by faustodavid** [comment]
Hey @joey-grafana thanks for fixing this bug! 

I see in the milestone was set for Grafana `8.5.2`, but the issue is present there, it is not present in `main`.

**Comment by joey-grafana** [comment]
Thanks for following up. I believe the release went out just before the PR was merged. I have changed the milestone to 9.0.0

**Pull request merged**
