### PR TITLE
Plugins: Fix plugin URL paths on Windows

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix plugin URL paths on Windows.

Agnès discovered that plugin URLs had backslashes in them on Windows, and it looks to me as if this should be the culprits.

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
Was this broken just because it's an URL and it was treated as a filesystem path?

**Comment by aknuds1** [comment]
> Was this broken just because it's an URL and it was treated as a filesystem path?

Yes. I haven't tested on Windows yet, but I hope these are the culprits. Looks like it from how it's supposed to be base URLs. Hopefully @AgnesToulet can confirm.

This bug happened because I fixed the opposite type of problem, i.e. that we were using `path.Join` for filesystem paths (`path.Join` is for network paths).

**Review by AgnesToulet — CHANGES_REQUESTED** [review]
I still have issues with these changes. I don't really understand where and when these variables are used but this is working on Windows:
```
fp.Module = path.Join("plugins", fp.Id, "module")
fp.BaseUrl = filepath.Join("public/plugins", fp.Id)
```

**Comment by aknuds1** [comment]
> I still have issues with these changes. I don't really understand where and when these variables are used but this is working on Windows:
> 
> ```
> fp.Module = path.Join("plugins", fp.Id, "module")
> fp.BaseUrl = filepath.Join("public/plugins", fp.Id)
> ```

@AgnesToulet Oh that's strange, maybe I should try to reproduce. Do I need to do anything special to reproduce on Windows?

**Comment by AgnesToulet** [comment]
Nothing special, I just checked out your branch and tried to access one of the provisionned data source.

**Comment by aknuds1** [comment]
@AgnesToulet Please have another look. AFAICT both those fields should have forward slashes.

**Review by AgnesToulet — APPROVED** [review]
Works on Windows! LGTM!

**Comment by papagian** [comment]
For context: `fp.Module` is the JS import path imported here:
https://github.com/grafana/grafana/blob/3b9523fad7304c1e0abf9e87dfa002d30e54dcbf/public/app/features/plugins/plugin_loader.ts#L181-L191
 and `fp.BaseUrl` is a url so both should use '/' regardless of the running OS.

**Pull request merged**
