### PR TITLE
Implemented Opentsdb MultiSelect Templating.

### PR DESCRIPTION
**Pull request by utkarshcmu**

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Fixed #2465

**Comment by torkelo** [comment]
Nice! 

The PR needs a unit test, and the pipe format should be added to as an All format options as well.

**Comment by utkarshcmu** [comment]
Done. Please let me know if we should make any more changes in this PR.

**Comment by torkelo** [comment]
looks great!

**Comment by torkelo** [comment]
added a new the new per datasource option "defaultMatchFormat" to OpenTSDB, now pipe will be automatically selected for a variables allFormat and multiFormat

**Comment by utkarshcmu** [comment]
@torkelo I think the default "All Format" should be wildcard as Opentsdb support "*" and may be queries with "*" are more optimized than queries with all tag values piped together. So my suggestion is that we keep "All format" as "wildcard" and "Multi Format" as "pipe" for Opentsdb datasource. What do you think about this? If you agree than I can submit another PR to make this change.

**Comment by torkelo** [comment]
Right now the default is the same. If people want wildcard they can use wildcard

**Comment by RuralHunter** [comment]
This change is not in the latest release(2.3) yet right?

**Comment by utkarshcmu** [comment]
The latest release of Grafana was 2.1.3 on 08/24. This PR is merged after that. So, this change should be a part of the next release. 😊

**Comment by RuralHunter** [comment]
Got it, thanks!

**Pull request merged**
