### PR TITLE
FrameGraphTopTable: Use standard Table component

### PR DESCRIPTION
**Pull request by torkelo**
I noticed this was using react-table directly and duplicating large parts of our core Table component (with different styling). 

Was pretty easy to replace with core Table component just have to build the correct DataFrame. 

Todo 
* [x] Move logic one level up 
* [x] Fix tests

The source table data is built in a component one level up: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/flamegraph/components/TopTable/FlameGraphTopTableContainer.tsx#L41 

I would build the data frame there instead ( and remove FlameGraphTopTable as it has no purpose really now being just a wrapper for Table)

Before:
Screenshot from 2023-04-12 20-03-27

After
image

### CODE REVIEW

**Comment by torkelo** [comment]
Ok pushed an update where I moved the logic up one level. @joey-grafana think this is looking good now, Also pushed an update to improve use for the search input & "Reset view" button (which was bad name for this button that only clears the search). 

Now the "Reset view" is implemented using a input suffix like we do in other places:
image

**Comment by joey-grafana** [comment]
This is looking good overall, thank you for the simplification.

I see you now have the logic pushed for total/self unit.

Few nits;
- We now have to click on the blue link itself, rather than anywhere on the row to select the row (should prob remove `cursor: pointer`)
- A selected row does not have a grey background color
- The reset button feels like it fits into the UI much better, however the reset view button would also reset the flame graph if a particular block was focused (left click on flame graph -> focus block)

**Comment by torkelo** [comment]
@joey-grafana maybe the reset view for "focused block" action can be a small button above the flame graph (next to the text). 
So we separate these two actions 
image

**Review by joey-grafana — APPROVED** [review]
This looks good! Thank you :)

**Pull request merged**
