### PR TITLE
AzureMonitor: Fix Azure Resource Graph queries in Azure China

### LINKED ISSUE #31662: Azure China log analytics error
**What happened**: I set the datasource of Azure China
Azure Monitor cannot get subscriptions
image

Azure Log Analytics cannot get workspaces
The previous one was set up that got the workspace, but when test it returned "3. Azure Log Analytics: Bad Request: Bad Request"
image

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.3.7
- Data source type & version: Azure China
- OS Grafana is installed on: docker
- User OS & Browser: Edge
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kostrse**
**What this PR does / why we need it**:

This PR fixes Azure Resource Graph queries and Resource Picker in Azure China:
1. Routes are optimized and duplicated routes were removed to workaround #35231
2. API version of Resource Picker queries was updated because old API version not supported in Azure China.

**Special notes for your reviewer**:

I found that routes actually can support * method match, so I removed all duplicated routes to Azure Management API.
Was tested in Azure Public Cloud and Azure China.

Fixes #31662

### CODE REVIEW

**Comment by sunker** [comment]
cc @andresmgot

**Review by sunker — APPROVED** [review]
Tested and it works fine. Would be nice if someone else could test this too now that we're so close to release.

**Review by andresmgot — APPROVED** [review]
Did some quick testing for this and it's also working for me. Thanks!

**Comment by joshhunt** [comment]
Gave Metrics, Logs, Resource Picker, App Insights, and Insights Analytics, and template variable queries a test and it's all looking good. 

Thanks for your help on testing Azure China!!!!!

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
