### PR TITLE
Drone/CircleCI: Upgrade build pipeline tool

### LINKED ISSUE #23567: Convert our musl builds to static linking
**What would you like to be added**:
I think we should convert our musl builds to statically link musl, for robustness reasons. The size increase is probably minimal.

**Why is this needed**:
After solving #23500, that our master Docker images were broken on ARM v7, I realized that the issue arose from the fact that Go builds targeting musl v1.2.x are incompatible with musl v1.1.x (f.ex. Alpine 3.10/3.11). The incompatibility is because v1.2.x switches to 64-bit time types, and the Go binaries have references to these types, which are not present in musl v1.1.x, and a dynamic linking error happens as a result.

Another thing worth mentioning, is that we are now stuck at musl v1.1.x, in order to not break compatibility with Alpine.

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Upgrade to new version of the build pipeline tool, with static musl libc linking. Should make our musl (Alpine Linux compatible) binaries more portable, since they become independent of the system's version of musl (1.2 breaks compatibility with 1.1 on 32-bit archs).
 
**Which issue(s) this PR fixes**:
Fixes #23567.

### CODE REVIEW

**Review by wbrowne — COMMENTED** [review]
Not sure if relevant but there's some [other references](https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/docker/grafana-plugin-ci-alpine/scripts/deploy.sh#L46) to `grabpl` installs in the grafana-toolkit. Should they be bumped in this PR too?

**Comment by aknuds1** [comment]
@wbrowne I wasn't really aware of that. I guess I might as well bump it?

**Comment by aknuds1** [comment]
@wbrowne Thanks for finding additional references, bumped them all.

**Review by wbrowne — APPROVED** [review]
🕺

**Pull request merged**
