### PR TITLE
add help link to menu bar

### PR DESCRIPTION
**Pull request by gesquive**
Created issue #5895 

Basically, just want a link in grafana so users can go directly to the online documentation.

### CODE REVIEW

**Comment by gesquive** [comment]
Here is a screen shot of the placement of the link, it's the question mark to the right of the gear.
grafana_help_link

**Comment by bergquist** [comment]
@mattttt what do you think?

**Comment by bulletfactory** [comment]
Currently, all of the links in the topbar of the dashboard directly relate
to actionable items for that dashboard. Adding a link for help/docs doesn't
seem to follow this, and I'm concerned that it paves the way for a slippery
slope of throwing additional links into the top bar to clutter up the UI.

I could see a better case to adding it to the sidebar menu, and/or making
it more visible in the footer of non-dashboard pages. We could also add a
link or something to the default home dashboard. This would help people new
to Grafana.

**Comment by bergquist** [comment]
Thank you for this Pull request but I totally agree with @bulletfactory regarding this issue. We will add a better link to docs but not like that.

**Pull request closed without merging**
