### PR TITLE
Fix percent_diff calculation when points are nulls

### LINKED ISSUE #15443: percent_diff percent_diff with only nulls leads to slice bounds out of range
Please include this information:
### What Grafana version are you using?
Grafana v5.4.3 (6539180)

### What happened instead?
```
t=2019-02-14T13:04:40+0000 lvl=eror msg="Alert Panic" logger=alerting.engine error="runtime error: slice bounds out of range" stack="[engine.go:174 asm_amd64.s:522 panic.go:513 panic.go:54 reducer.go:135 query.go:53 eval_handler.go:31 engine.go:185]"
```
The loop below is evaluated and  `i` become -1.
```for i = len(points) - 1; i >= 0; i-- {...}```

### PR DESCRIPTION
**Pull request by mneverov**
closes #15443

### CODE REVIEW

**Comment by torkelo** [comment]
@bergquist this is technically a bug fix, and looks low impact. Cherry pick for next v6 beta?

**Comment by torkelo** [comment]
sorry that comment was for another PR

**Review by torkelo — CHANGES_REQUESTED** [review]
Looks like diff has the same bug, and it also looks like the code in diff & precent_diff can be extracted and shared.

**Comment by max-neverov** [comment]
Updated PR, @torkelo please take a look

**Review by bergquist — APPROVED** [review]
LGTM. 
Should be squashed when merged and include issue ref in the commit.

**Pull request merged**
