### PR TITLE
Update query_builder.ts

### LINKED ISSUE #15870: Elasticsearch terms group by 'No limit' is misleading as it sets a 500 limit
**What happened**:
The percentage of items of a very long list are calculated wrong if the list size is set to "no limit". If I set the list size manually to a size far bigger than the list itself (99999 in my case) the percentages are calculated correctly.

**What you expected to happen**:
I expect to get correctly calculated percentages if the list size is set to "no limit".

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.3.4
- Data source type & version: Elastic search 
- OS Grafana is installed on: Linux
- User OS & Browser: Ubuntu 18.04
- Grafana plugins: - 
- Others: -

### PR DESCRIPTION
**Pull request by tanishq-dubey**
**What this PR does / why we need it**:
This should be zero, otherwise the "No Limit" label is misleading and doesn't actually return a "No Limit" (Int max value: 2147483647). 

I realize that this may cause performance issues, but that shouldn't be a concern, as it is up to the user to define this?

**Which issue(s) this PR fixes**:
Sets the No-Limit to zero

Fixes #15870

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
I think you're referring to fix #15870? If so, update `Fixes #` in PR description with `Fixes #15870` and please see https://github.com/grafana/grafana/issues/15870#issuecomment-475946948 for suggestion on fixing this and what's need to be done. Thanks

**Comment by torkelo** [comment]
Please update failed unit tests

**Comment by torkelo** [comment]
and also needs fixing in backend code

**Comment by torkelo** [comment]
closing due to no update in 24 days, please comment if we should re-open (or open new PR)

**Pull request closed without merging**
