### PR TITLE
Macros: Support parentheses within macro functions

### LINKED ISSUE #8411: [Feature request] Allow parentheses in macro expansion for MySQL data source
With 4.3 beta 1, because (as far as I can tell from a quick inspection of [the regex](https://github.com/grafana/grafana/blob/ae5e004b6980e4cacf7cc9b50b4beef5eea99340/pkg/tsdb/mysql/macros.go#L12)) the macro expansion parameter terminates at the first closing parenthesis, using expressions including MySQL functions as the parameter for a macro gives unexpected results that can give confusing syntax errors.

Allowing functions here to work as naively expected would make individual macros significantly more flexible (IMO).

### LINKED ISSUE #10380: [Feature request] Allow parentheses in macro expansion for Postgres data source
Effectively a clone of issue #8411 (which applies only to MySQL), but for Postgres.

Using:
Grafana v4.6.3 (commit: 7a06a47)
Postgres data source

Given:
```
"SELECT $__time(timezone('PST',p.last_updated_date)), p.position FROM p inner join x using (x_id) WHERE $__timeFilter(timezone('PST',p.last_updated_date)) ORDER BY 1 asc "
```

Expected:
```
"SELECT timezone('PST', p.last_updated_date) AS "time", p.position FROM p inner join x using (x_id) WHERE extract(epoch from timezone('PST', p.last_updated_date)) BETWEEN 1514490490 AND 1514512090) ORDER BY 1 asc "
```

Actual:
```
"SELECT timezone('PST' AS "time"), p.position FROM p inner join x using (x_id) WHERE extract(epoch from timezone('PST') BETWEEN 1514490490 AND 1514512090) ORDER BY 1 asc "
```

and

Given:
```
"SELECT $__time(extract(epoch from p.last_updated_date)), p.position FROM p inner join x using (x_id) WHERE $__unixEpochFilter(extract(epoch from p.last_updated_date)) ORDER BY 1 asc "
```

Expected:
```
"SELECT extract(epoch from p.last_updated_date) as "time", p.position FROM p inner join x using (x_id) WHERE extract(epoch from p.last_updated_date) >= 1514491287 AND extract(epoch from p.last_updated_date <= 1514512887 ORDER BY 1 asc "
```

Actual:
```
"SELECT extract(epoch from p.last_updated_date AS "time"), p.position FROM p inner join x using (x_id) WHERE extract(epoch from p.last_updated_date >= 1514491287 AND extract(epoch from p.last_updated_date <= 1514512887) ORDER BY 1 asc "
```

### PR DESCRIPTION
**Pull request by chaitan94**
**What this PR does / why we need it**:

This pull request aim is to fix the long-standing, closely related issues https://github.com/grafana/grafana/issues/10380 and https://github.com/grafana/grafana/issues/8411

For a brief context, when using SQL based data sources in grafana like postgres or MySQL, we have the feature of macros, which allow for dynamic queries to be built. While we can have custom SQL code within these macro calls, because of the current regex-based parsing of the macros, parentheses are not processed as expected.

So to be honest, the current fix does complicate the regex a bit. But in my opinion, this is still a decent solution as any other option seems to need us to rewrite the parsing logic without doing any regex. A similar argument was rightly pointed out by @ikirker earlier in his issue (https://github.com/grafana/grafana/issues/8411) as well.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/10380
Fixes https://github.com/grafana/grafana/issues/8411

**Special notes for your reviewer**:

I've ran the tests using: `go test -v ./pkg/...` and all PASS as expected

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hi @chaitan94! Thank you for your contribution! A maintainer will review your change and provide feedback within the next week or so. In the meantime, refer to our guide on [how to create a pull request](https://github.com/grafana/grafana/blob/master/contribute/create-pull-request.md) for more information.

**Comment by marefr** [comment]
We're still planning to review this soon.

**Comment by ryantxu** [comment]
@briangann hymmmm... Another approach

**Comment by chaitan94** [comment]
@ryantxu Wait, was another approach already attempted to solve this issue?

Honestly, my approach does feel a bit awkward. Would like to know more about this alternate, if anyone could elaborate?

**Comment by kylebrandt** [comment]
> hymmmm... Another approach

....

> @ryantxu Wait, was another approach already attempted to solve this issue?
> 
> Honestly, my approach does feel a bit awkward. Would like to know more about this alternate, if anyone could elaborate?

@ryantxu can you give some context (...make some sense ;-) )

**Comment by chaitan94** [comment]
@kylebrandt since there hasn't been any response from @ryantxu since about 2 months now, probably we should not wait and proceed for the code review regardless.

**Pull request closed without merging**
