### PR TITLE
Transformers: fix npe on convert null value to number

### PR DESCRIPTION
**Pull request by mushroom-cn**
**What is this feature?**

fix null point exception while convert null value  to number.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by ryantxu** [comment]
@mushroom-cn -- looks good!  I updated the logic and added a test.  Can you click the CLA, and I can them merge.  thanks!

**Comment by zoltanbedi** [comment]
@bohandley fyi there are a lot of issues that are complaining about this.
https://github.com/grafana/grafana/issues/63947
https://github.com/grafana/grafana/issues/59807
https://github.com/grafana/grafana/issues/57737

**Review by bohandley — APPROVED** [review]
LGTM!

**Comment by bohandley** [comment]
@mushroom-cn Thank you for your contribution! Please click and sign the CLA and then we can get this merged.

**Comment by zoltanbedi** [comment]
This was fixed in https://github.com/grafana/grafana/pull/66807 so I'm going to close this. Thanks anyway @mushroom-cn

**Pull request closed without merging**
