### PR TITLE
(snapshot) save original url

### PR DESCRIPTION
**Pull request by mtanda**
I just wonder why Grafana doesn't save original dashboard url.

### CODE REVIEW

**Comment by bergquist** [comment]
This could expose internal info to the public if you share snapshots to snapshots.raintank.io.

**Comment by mtanda** [comment]
Thanks for feedback.
I fixed it, save original url for local snapshot only.

**Comment by bergquist** [comment]
Im not sure that this should be placed under the share menu. Very few people will discover it. Maybe it should be a new icon next to the share button?

**Comment by mtanda** [comment]
Exactly. I move the link from menu, and make button.

**Comment by bergquist** [comment]
Great work! Merging this :)

**Comment by mtanda** [comment]
Thanks!!

**Pull request merged**
