### PR TITLE
Stackdriver: Fix creating Service Level Objectives (SLO) datasource query variable

### LINKED ISSUE #24660: Dashboard variable Query for Stackdriver's Service Level Objective (SLO) seems not to be saving SLO Service value
**What happened**:
When trying to create dashboard variable querying Stackdriver for Service Level Objectives, I selected my SLO Service in the appropriate field. Saved the variable, but no values were visible. When I opened variable again, value of the SLO Service field was set to $myvariable (first value on the list).
My hunch is that the field value is not being saved, some equivalent of None value is used for query (returning no results) and when I am opening variable edition page, it is displaying the first value on the list.
Other Query Type values are working fine and Service Level Objectives are added in 7.0.0, having custom form values, so I expect problem is somewhere over there.

**What you expected to happen**:
My selected SLO Service to be persisted and used in variable query, producing actual results.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a custom service in GCP project with Stackdriver enabled: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services/create
* Create Stackdriver datasource, create a new dashboard. Go to settings>variables. Try to create a new variable:
name: anything
type: query
data source: stackdriver
query type: service level objective (SLO)
project: your project
slo service: your service
* Save
* After reopening the variable SLO Service value would be set to the variable name you choose, not the SLO Service

**Anything else we need to know?**:
It seems to be a bug with a new feature and not a regression in already existing function, so probably not a top urgency.

**Environment**:
- Grafana version: v7.0.0-beta3 (2169fc1a3f)
- Data source type & version: Stackdriver
- OS Grafana is installed on: Docker on Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04, Chrome 81.0.4044.129
- Grafana plugins: only things provided by docker image
- Others:
Docker version 19.03.6, build 369ce74a3c

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:

This PR fixes creating a Service Level Objectives (SLO) datasource query variable. The problem was that the `selectedSLOService` was not stored. As a result there were no values under Preview of values and the value of SLO service was not correct after reopening the variable.

In addition to this, It prevents from querying for Service Level Objectives (SLO) if the `selectedSLOService` is empty (this happens when selecting `Service Level Objectives` for `Query Type` and no SLO service is selected yet.

**Which issue(s) this PR fixes**:

Fixes #24660

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bergquist** [comment]
There is a fix for the codespell issue in master so please merge/rebase

**Comment by bergquist** [comment]
Looks good.  
This PR also fixes https://github.com/grafana/grafana/issues/24694 based on my testing. Perhaps you want to test that as well :)

**Comment by papagian** [comment]
> Looks good.
> This PR also fixes #24694 based on my testing. Perhaps you want to test that as well :)

I'm no more able to reproduce this error so I think that it's irrelevant with this fix.

**Review by bergquist — APPROVED** [review]
LGTM

**Review by daniellee — APPROVED** [review]
LGTM and confirmed that the fix works.

**Pull request merged**
