### PR TITLE
Allow special characters in column selection

### PR DESCRIPTION
**Pull request by steven-aerts**
The influxdb query editor is great.
The query editor currently does not propose column names when the series name contain a special character like a '/'.
Also the proposed column names are by this patch properly escaped by the editor.

### CODE REVIEW

**Comment by torkelo** [comment]
Since the series names can be regexes with '/' I am not sure the editor should escape it. And I am a little worried that applying this patch will break existing queries where poeple have already escaped series names.

**Comment by steven-aerts** [comment]
Ok, I agree, removed the first commit.  So column names are at least properly escaped.
What do you think for a similar solution for serie names, where we escape all regexp characters from suggested serie names?

**Comment by steven-aerts** [comment]
47197a8 will escape all regexp characters from the suggested series name.
Do you think this is less likely to break things?

**Comment by torkelo** [comment]
@steven-aerts I am not sure that will work. If you have a series name like "test/server1/cpu" will it still work?

**Comment by steven-aerts** [comment]
This is exact the use case I am trying to fix.
As currently `test/server1/cpu` will result in a syntax error from influxdb while querying for all columns:
```
syntax error, unexpected SIMPLE_NAME, expecting $end
SELECT * from /test/server1/cpu/ limit 1
                    ^^^^^^^
```
This is due to the fact that the serie name is interpreted as a Regexp by surrounding it with a '/'.
With 47197a8 the series name will be escaped so it cannot break the regexp anymore.
The escaped serie name will in influxdb both work as a string as as a regexp.

The main thing I am puzzled about is that for column suggestions, the serieName is by default interpreted as a regexp.  While in the query for the data, the serie Name is only seen as a regexp when it is surrounded by '/'.

So while the `influxqueryBuilder.js` says:
```js
if(!seriesName.match('^/.*/') && !seriesName.match(/^merge\(.*\)/)) {
  seriesName = '"' + seriesName+ '"';
}
```

The `influxdbDataSource.js` says:
```js
if (interpolated[0] !== '/') {
  interpolated = '/' + interpolated + '/';
}
```

I tried to keep this behavior.  But if you do not mind to line it up I will adapt the pull request to do so.
I am rather sure that the escaping of the serie names is then not necessary anymore.  
15c3527 is still usefull however.

What do you think?

**Comment by torkelo** [comment]
I think I solved it in a way that works for every case.

**Comment by steven-aerts** [comment]
Validated it on my side and it works.

Thanks

**Pull request closed without merging**
