### PR TITLE
Upgrade npm packages

### PR DESCRIPTION
**Pull request by Nepomuceno**
Upgraded NPM packages with the master goal being upgrading typescript to the version 2.* the changes that it brings and the ability to remove the dependency on TSD are an improvement on itself. took the opportunity to actually upgrade to newer version of the other packages in order to remove deprecated messages and remove more dependencies.

Some of the files needed to be corrected since the new js linter it is capable of detecting errors that were passed before.

grunt-exec was included in order to replace the grunt-typescript and grunt-tslint that were not being updated and incompatible with the newer typescript version.

### CODE REVIEW

**Comment by torkelo** [comment]
This looks great!!! thanks for this!

**Comment by torkelo** [comment]
the only problem I could find is that the grunt watch command now recompiles all typescript files when it detects a .ts file change. Before it only recompiled the changed file. The typescript compiler, at least the 1.7x was really slow on some laptops

**Comment by Nepomuceno** [comment]
I will Write a pr to change the watch method tsd has a watch built in  no no need to actually use an external watch.

**Comment by torkelo** [comment]
please do not use the typescript watch, much faster to have a custom watcher. So expensive if every tool has their own watcher instead of one for everything. 

This call need to somehow give the file changed to tcs 
https://github.com/grafana/grafana/blob/master/tasks/options/watch.js#L67

**Comment by torkelo** [comment]
I mean we do not have a watcher for jslint, tslint, sass etc :)

**Comment by torkelo** [comment]
but everything is handled in https://github.com/grafana/grafana/blob/master/tasks/options/watch.js#L67

Before I used grunt watch but that was too slow. and running multiple watchers is not very developer friendly :)

**Comment by Nepomuceno** [comment]
Mo problem will change the compiler to compile only the changed files them
:)

**Comment by torkelo** [comment]
typescript source maps seem to have stopped working as well so can't debug typescript anymore :(

**Comment by torkelo** [comment]
fixed sourcemap issue :)

**Comment by fg2it** [comment]
@Nepomuceno @torkelo 
while you are polishing this, could you take a look at the files that are copied for release during `copy`  grunt task and end up in `.deb` and `tar.gz`. I suspect some of them should be removed (.sass, .ts, scripts/, ...).
`copy:public_gen_to_temp` is reponsible for most of the files but `copy:backend_files` is responsible for `scripts/`.

**Pull request merged**
