### PR TITLE
Fixes compatability with Raspberry PI 1st gen

### LINKED ISSUE #15209: Debian armel package fails to install on raspian
I realize official builds for armv6 is very new, but I have not found any other reports of this issue so I figured I would open one here. I was unable to get it installed using the .deb on a raspberry pi model b (and I assume this is what most people want an armv6 build for).

I think the issue (at least with the dep) is that it's looking for `libfontconfig:armel` but the raspbian repo uses `armhf` as it arch rather than `armel`. In other words, I have `libfontconfig:armhf` installed as armv6 and `libfontconfig:armel` is not available.

Please include this information:
### What Grafana version are you using?
6.0.0 beta 1

### What datasource are you using?
Can't install

### What OS are you running grafana on?
raspbian stretch armv6

### What did you do?
I first simply tried installing the .deb file and encountered an error:
```
pi@raspberrypi:~ $ sudo dpkg -i grafana_6.0.0-beta1_armel.deb
Selecting previously unselected package grafana:armel.
(Reading database ... 80783 files and directories currently installed.)
Preparing to unpack grafana_6.0.0-beta1_armel.deb ...
Unpacking grafana:armel (6.0.0-beta1) ...
dpkg: dependency problems prevent configuration of grafana:armel:
 grafana:armel depends on libfontconfig.

dpkg: error processing package grafana:armel (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (232-25+deb9u8) ...
Errors were encountered while processing:
 grafana:armel
```

However, that package is already installed:
```
pi@raspberrypi:~ $ sudo apt-get install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
libfontconfig1 is already the newest version (2.11.0-6.7).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 grafana:armel : Depends: libfontconfig:armel but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

I tried just ignoring the error using `--force-depends` and the installation completed. However, when trying to run grafana it seg faults:
```
pi@raspberrypi:~ $ grafana-server
Segmentation fault
```

### What was the expected result?
The installation to succeed and the program to run.

### What happened instead?
The installation fails and the program seg faults.

### LINKED ISSUE #15695: ARM package not compatible with Raspberry Pi Zero
### What Grafana version are you using?
6.0.0

### What datasource are you using?
~

### What OS are you running grafana on?
Raspbian buster/sid

### What did you do?
Installed grafana from repo. The service won't launch.

### What was the expected result?
Running Grafana?

### What happened instead?
Crash:
```
Illegal instruction
```

---------

Grafana server doesn't run on Raspberry Pi Zero (W). These devices use `armhf` on ARMv6 processors.

This renders official Grafana packages unusable on these awesome devices.

### PR DESCRIPTION
**Pull request by xlson**
Builds and publishes armv6 compatible with Raspberry Pi 1.

**Which issue(s) this PR fixes**:
Fixes #15695
Fixes #15209

**Special notes for your reviewer**:

Are we fine with the raspberry pi package being named grafana-rpi instead of grafana. This is to make it so that it doesn't conflict with the armv7 package that will have the same name. Alternatively, we could put up a second repository for raspberry pi or not provide one.

**Release note**:

```release-note
build: Fixes compatability with Raspberry PI 1st gen

```

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Look great!

**Comment by Majkl578** [comment]
@xlson Using different package name is a bit unfortunate and strange decision. As a consequence, trying to install the grafana-rpi will result in errors (you'd need a [proper renaming transition](https://wiki.debian.org/RenamingPackages) using `Replaces`):
```
dpkg: error processing archive grafana-rpi_6.1.0-beta1_armhf.deb (--install):
 trying to overwrite '/usr/share/grafana/tools/phantomjs/render.js', which is also in package grafana 6.1.0-pre
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
Maybe separate repo would be really better, i.e:
```
deb https://packages.grafana.com/oss/deb stable-rpi main
deb https://packages.grafana.com/oss/deb beta-rpi main
```

**Comment by xlson** [comment]
@Majkl578 I should have cought that. One of the problems of not having a pi around to test on. Yeah, a separate repo like that is a better option. I will make that change.

**Comment by Majkl578** [comment]
@xlson Awesome, let me know if you need testing. 👍

**Comment by xlson** [comment]
@Majkl578 Will do. I haven't had the chance to work on it yet and it's not a big priority atm, but I will get back to you when we get on it.

**Comment by Marooned-MB** [comment]
@xlson after a year and and half.. was it done? How could I install Grafana on RPi model B rev 2? Thanks

**Pull request merged**
