### PR TITLE
Users: Resurrect org picker's search functionality

### LINKED ISSUE #78885: Return org picker's searching functionality
**Why is this needed**:

Our use-case has hundreds of organizations in a self-hosted instance of Grafana. An administrator trying to add a user to an org is an incredibly tedious process since the org list is unsorted and extremely long. 

**What would you like to be added**:

We recently upgraded from v6 to v10 and v6 had this org picker with search enabled. I would like to resurrect this functionality. Seems like an easy fix since it will all be frontend-based.

**Who is this feature for?**

A grafana instance with multiple organizations that are managed by humans.

### PR DESCRIPTION
**Pull request by ManiacMaxo**
**What is this feature?**

Supplies a filterOption prop to the OrgPicker component to enable client filtering of organizations as to make the select searchable.

**Why do we need this feature?**

As described in the issue: this eases the process of adding a user in an org if there are many organizations.

**Who is this feature for?**

A grafana instance with multiple organizations that are managed by humans.

**Which issue(s) does this PR fix?**:

Fixes #78885

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by metalgrid** [comment]
This would be great to have back. We have a few thousand organizations and is making it very tedious when trying to add a user to a certain organization. Or at least, sort them so that it doesn't feel like searching for a needle in a haystack.

**Comment by ManiacMaxo** [comment]
ping? I don't want to see this get closed without anyone even looking at it

**Comment by Clarity-89** [comment]
@ManiacMaxo could you update this PR to the latest main branch?

**Review by Clarity-89 — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
