### PR TITLE
Refactor: flexible Y-Min and Y-Max settings

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Refactor of #5720

### CODE REVIEW

**Comment by cfra** [comment]
I just tried this out and am not able to use it very well.
a) plain negative numbers for limits don't seem to work anymore
b) I am not able to set ymax in a way so that it defaults to e.g. 150 but will scale up if data becomes too 
    large
c) I cannot define ymax for multiple graphs from a template

It might also be that I am doing it wrong, I just skimmed over the code because I did not find any documentation.

**Comment by torkelo** [comment]
@alexanderzobnin can you check those this ^ (a, b, c)

**Comment by alexanderzobnin** [comment]
@torkelo ok, will check this.

**Comment by alexanderzobnin** [comment]
@cfra can you explain b) and c) ?

**Comment by cfra** [comment]
b) c) relate to the same usecase:
I have a dashboard with a large set of graphs showing the distribution of wifi clients over ap locations, each showing a different timerange. I would like to have all graphs default to the Y-Range 0-1000 so that total client count is easily comparable. However I don't want a graph to be clipped if I encounter more than 1000 clients, but I would like it to be automatically scaled to a sufficient Y-Range, e.g. 0-1500. (This is speaking about a single graph now, not all graphs in the dashboard)

b) I tried achiving this with different modifiers. Toying around with it now, the behavior seems somewhat errativ. I leave Y-Min at 0 and play with Y-Max. The test graph peaks at 126. If I don't enter anything for Y-Max, it ends up at 150. For other inputs it seems somewhat erratic as displayed in this table.

| Input | Resulting Metric |
|-------|------------------|
| <10   | 10               |
| <100  | 150              |
| <200  | 150              |
| >10   | 150              |
| >100  | 100              |
| >150  | 150              |
| >200  | 200              |

Maybe my expectations about the semantics are incorrect and what I want is not possible. The behavior of `>x` seems to be almost what I need, but I do not comprehend why `>10` yields 150 and `>100` yields 100. For `<`, I also do not comprehend why `<10` and `<100` yield different results.

c) I would like to adjust all graphs at once to another scale e.g. to go from 0..1000 to 0..1500. For this, it would be very useful if I could define Y-Max as `>$ymax` with ymax being a dashboard variable instead of having to adjust it separately for all graphs.

**Comment by alexanderzobnin** [comment]
@cfra ok, I will check this.

**Comment by alexanderzobnin** [comment]
@cfra can you attach screenshots with incorrect behaviour?

**Comment by cfra** [comment]
@alexanderzobnin Here you go, let me know if you need anything else: http://nowhere.ws/dump/cropped/

**Comment by alexanderzobnin** [comment]
Do you use stack mode in this graph? I think, problem's root is here.

**Comment by cfra** [comment]
Yes, the graph uses stacked mode. I uploaded the json of the graph here, if that helps. https://np.tl/paste/nMgDevPm#vBOJgWSOar1-Tz8EMl0tAY/ZVH7de+BA8DdnlENIaga

**Comment by alexanderzobnin** [comment]
@cfra thanks. I need to add more tests for stack mode.

**Comment by alexanderzobnin** [comment]
@torkelo seems, we need to move Y-min and Y-max calculating to `jquery.flot.js`. Because if stack mode enabled, stacked series values calculates there. So we need to place `autoscaleSpanOverride()` after this loop: https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js#L1247

**Comment by torkelo** [comment]
@alexanderzobnin I think I have a solution for that

**Comment by vaizki** [comment]
I've tried this with the docker image grafana/grafana:master which reports itself as v4.2.0-pre1 (commit: 457d6c8) and the y-axis disappears completely if I enter any of these special expressions (such as >100). Has this been reverted or replaced but I just can't spot it in GitHub or is it just broken?

**Comment by DevBOFH** [comment]
I see the same behavior as vaizki.

**Comment by robfredtwitch** [comment]
For anyone else who ended up here like I did, it says in the closed issue above that this PR was reverted https://github.com/grafana/grafana/issues/13076#issuecomment-416981777

**Pull request merged**
