### PR TITLE
Prometheus: Show initial hint on builder mode when metric lookup disabled

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

We disable the metric label load on editor mode when the metric lookup is disabled but we do not check this on builder mode. This PR is addressing that issue.

image

**Who is this feature for?**

Prometheus datasource `Builder Mode` users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/support-escalations/issues/5464

**Special notes for your reviewer:**

- Run Grafana dev environment with Prometheus datasource
- Set `Disable metrics lookup` enabled on datasource config page
- Save and click `Explore`
- On code mode observe metric lookup is disabled and a hint is being shown
- On builder mode, it is not disabled
- Switch to this branch and refresh the page
- See it is disabled and not clickable and a hint is being shown

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [x] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [x] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

**Comment by bohandley** [comment]
This would break the metric encyclopedia which relies on the metric lookup. Maybe if the metric lookup is disabled and metric encyclopedia toggle is on we can fallback to the metric select which allows users to still type in a metric when the lookup is disabled.

**Review by ivanahuckova — APPROVED** [review]
LGTM!

This is not related to your PR, but maybe we want to fix it in here as well. The hint says `Labels and metrics lookup was disabled in data source settings.`, but user is still able to lookup/work with labels in both `code` and `builder`. Also the tooltip in data source config says that it should disable both metrics and labels. So we should probably disable that as well.

**Comment by itsmylife** [comment]
> Would break the metric encyclopedia which relies on the metric lookup? Maybe if the metric lookup is disabled and metric encyclopedia toggle is on we can fallback to the metric select which allows users to still type in a metric when the lookup is disabled.

Can we look up only when the `Metric encyclopedia` button is clicked? Because I believe creating such a condition is confusing to the users.

**Comment by itsmylife** [comment]
@ivanahuckova @bohandley Should I backport this to `v9.4.x` and `v9.5.x`?

**Comment by gtk-grafana** [comment]
image
You can still set labels when metric look-ups are disabled, but I'm wondering why we're making this change? Doesn't this feature already force people to use the code editor as there is no way to create a valid query in this state?

**Comment by gtk-grafana** [comment]
@bohandley @itsmylife I believe this will absolutely break the metric encyclopedia and that's kinda the point, if I understand correctly. If this is set, we don't ever want to query the metric names in the application, which means no query builder, and no metric encyclopedia.

**Review by ivanahuckova — COMMENTED** [review]
>I do not understand your point. When it is disabled we don't load the labels so the user should write them manually. There is no code hinting. So there is no lookup. Am I missing something?

As @gtk-grafana showed, it is still suggesting labels (therefore doing labels and values lookup). You can trigger it in code editor by typing `{`, or in query builder by clicking on `Label filter`. Based on the text `Labels and metrics lookup was disabled in data source settings`, I would expect no suggestions of metrics/labels/values fetched from Prometheus.

>@ivanahuckova @bohandley Should I backport this to v9.4.x and v9.5.x?

As this is bug fix, I'd backport to the last minor version, which will be probably `9.5.x` at the time when this gets merged.

> Doesn't this feature already force people to use the code editor as there is no way to create a valid query in this state in the query builder?

@gtk-grafana you can always also type into label/value select and press enter.

But now thinking about it @itsmylife , I don't think metrics selector should be disabled and we should only disable lookup - so you can still use metric selector to type there your metrics.

image

**Comment by bohandley** [comment]
> @bohandley @itsmylife I believe this will absolutely break the metric encyclopedia and that's kinda the point, if I understand correctly. _If this is set, we don't ever want to query the metric names in the application, which means no query builder, and no metric encyclopedia._
> 
> But I missed your point about still allowing backend search... I'm not sure about that, I'd think that this setting would be used on instances that know a bad query could crash their instance, so allowing folks around that could be bad?

I would consider disabling the entire query builder if this is enabled. I think this would be less confusing. Seeing the query builder open and two thirds of it disabled would make me have to think more than I want to. The original feature was implemented for the code editor and I would argue the the query builder's purpose is to allow a user to select prometheus query elements from lists of metrics and labels that are "looked up." 

This behavior/config feature is an older way of handling slow performance due to high cardinality and we have implemented a variety of ways of improving the performance without having to turn it off. I wouldn't argue to remove this feature but I think it would be clearer if we kept it's scope to the code editor, disabled the query editor and updated the config tooltip description.

[Adding on off switch for disabling](https://github.com/grafana/grafana/pull/24034)

**Comment by gtk-grafana** [comment]
@bohandley Thanks for the context, that is super helpful! It sounds like we wanted to turn off the query builder entirely, and that the labels shouldn't be querying either if I'm reading that PR correctly, 

> Yeah, we need to make clear that the metrics chooser will be off/disabled/not working if the user enables this option.
> "Checking this option will disable the Metrics chooser and metric/label support in the query field's tab-completion. This helps if you have performance issues with bigger Prometheus instances."

So the current documentation makes it sound like the query builder should be disabled entirely.
image

**Comment by itsmylife** [comment]
@bohandley @gtk-grafana @ivanahuckova Thanks for the discussion. Here are my takeaways.

1. We should disable the label look up too since we can trigger it as @ivanahuckova and @gtk-grafana showed. I will add this too in this PR.
  - I will disable the mode switch toggle and add a tooltip to state that was disabled because of the data source config.
2. If this option is selected we should disable builder mode entirely. As @bohandley stated that was an older way to solve a problem in code mode. Trying to adapt it in builder mode causes more problems. To solve a similar problem in builder mode we have other solutions in the pipeline. @gtk-grafana and @leeoniya did a great job.
  - https://github.com/grafana/grafana/pull/62932 (incremental queries)
  - https://github.com/grafana/grafana/pull/65244 (browser cache)

How does this sound? @gtk-grafana @ivanahuckova @bohandley ?

**Comment by ivanahuckova** [comment]
> I will disable the mode switch toggle... If this option is selected we should disable builder mode entirely.

My opinions is to not disable toggle/query builder as you are still able to use query builder to build query - but you just need to manually type the metric/label/value. In my opinion, it works the same/similar as code mode where you need to type these as well.

**Comment by itsmylife** [comment]
@bohandley I agree with Ivana. Disabling the toggle makes things a bit complicated. So instead of disabling we can leave it as it is and the user should type the metric manually. But we can disable the metric encyclopedia. WDYT?

**Review by bohandley — APPROVED** [review]
LGTM!

**Pull request merged**
