### PR TITLE
DataProxy: Ignore empty URL's in plugin routes

### PR DESCRIPTION
**Pull request by domasx2**
**What this PR does / why we need it**:
If a datasource plugin defines routes with no `url` property,  datasource proxy will replace request schema & host with empty strings, resulting in an invalid request and 502 being returned. I believe It should instead keep the original schema & host, same as plugin proxy.
This PR adds a check to see if `route.url` is empty, and in such case does not modify request schema & host.

Use case: restrict some paths and/or http methods to certain roles without overwriting the host & schema.
Needed for alerting ui plugin: https://github.com/grafana/alerting-ui-plugin/issues/113

Example `plugin.json`:

```json
{
  "type": "datasource",
  "name": "Alert Manager",
  "id": "grafana-alertmanager-datasource",
  "metrics": false,
  "routes": [
    {
      "method": "POST",
      "reqRole": "Editor"
    },
    {
      "method": "PUT",
      "reqRole": "Editor"
    },
    {
      "method": "DELETE",
      "reqRole": "Editor"
    }
  ],
...
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — APPROVED** [review]
Make sense :+1: LGTM

**Comment by marefr** [comment]
Just some linting problems left to fix, see build details

**Comment by domasx2** [comment]
> Just some linting problems left to fix, see build details

Embarrasing! Fixed

**Comment by marefr** [comment]
Great. Usually happens me as well and absolutely no worries :+1:

**Pull request merged**
