### PR TITLE
Feature: provide multildap server configuration

### PR DESCRIPTION
**Pull request by markelog**
* Add multildap server configuration for devenv

* Change some of the notes for openldap devenv configuration

* Change the maintainer label for *main* dockerfile and of the devenv one

Re-checked the multildap logic - everything seems to be working fine

### CODE REVIEW

**Review by xlson — APPROVED** [review]
Great work!

One small thing, can we rename plebs to users instead? :)

**Comment by markelog** [comment]
> One small thing, can we rename plebs to users instead? :)

Sure thing, my line of thought was that admins also users and "plebs" is relatively popular name for general population :)

**Comment by xlson** [comment]
@markelog it has a bit of a negative connotation which is why I'd rather go with something else. Are plebs a commonly used term? I've seen it, but not often.

**Comment by markelog** [comment]
I think so, it’s used in some colleges and in the army.

But totally never mind about that :). I will rename it!

Regards,
Oleg

**Pull request merged**
