### PR TITLE
Search: use prom metrics rather than metric queries for search stats

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
https://raintank-corp.slack.com/archives/C13QEUGLB/p1661330009579529?thread_ts=1661250400.532999&cid=C13QEUGLB

### CODE REVIEW

**Review by nmarrs — COMMENTED** [review]
In this PR in general just adding logs to help debug an issue occurring in hosted grafana instances? If so I'm good to approve, else I'm probably out of my depth a little here 😬

**Comment by ryantxu** [comment]
I don't have a sense if these metrics that happen infrequently are best reported in loki or in prometheus.

Prometheus seems good -- except that it is measuring a sample every 5ish mins, so not sure how that works.  @bergquist

**Comment by bergquist** [comment]
Prometheus would be okisch but I think we can improve the loki queries we built and use some loki recording rules. Lets see how fast we can make those queries.

**Comment by ArturWierzbicki** [comment]
I think the performance of metric queries is OK for now - thanks @bergquist for help!

**Pull request closed without merging**
