### PR TITLE
Move dashboard scuemata to grafana-schema

### LINKED ISSUE #38043: Add subcommand to `grafana-cli` for generating `cue/` from `packages/` and run it in CI
The completion criteria for #38033 is that we're automatically generating `cue/` based on the contents of `packages/`. We need a specialized `grafana-cli` subcommand to do that - it needs to know how to load and search the dir, what to do with each kind of file it finds, what (if any) validation criteria to apply to those files, how to combine it with other files, and where to ultimately dump the result.

Depends on #38042

### PR DESCRIPTION
**Pull request by sdboyer**
This relocates the dashboard scuemata file, previously at `cue/data/gen.cue`, to a more proper home at `packages/grafana-schema/src/dashboard/dashboard.cue`. We intend to follow a scuemata-per-directory pattern like this for all other objects we define going forward.

This was...a lot of really hacky changes in a bunch of different places. I really need to have a think about how  we present this path-oriented API.

Fixes #38043 by obviating the need for it (🎉 🎉 🎉 )

### CODE REVIEW

**Comment by sdboyer** [comment]
Ended up doing a few more things, here:

* Got rid of `cue/ui/gen.cue`, putting the contents of what wasn't already present in individual files under `schema` into `mudball.cue`
* Updated all the import paths in `models.cue` files to point to this new, central location
* Actually used `src/scuemata/dashboard` as the parent directory for dashboard scuemata. That subdir will be where we put all core object type scuemata declarations.

**Review by ryantxu — APPROVED** [review]
Soon we should move these out of a package names "schema" into (likely) "Viz" and "data"

Do we want a different root folder for things expecting the whole scumata? (Right now only dashboard)

**Review by ying-jeanne — APPROVED** [review]
LGTM, seems a lot of cue file formatting is done during the same time :), thinking which formatter you use, might worth to put it in the precommit script inside of package.json.

**Comment by sdboyer** [comment]
> thinking which formatter you use, might worth to put it in the precommit script inside of package.json.

Heated agreement - just trying to avoid introducing a dependency on the `cue` binary. IIRC i noticed the other day that the bits to write our own `cue fmt` in `grafana-cli` or wherever are exposed in a package now, so it shouldn't be hard. Just, haven't done it yet.

**Pull request merged**
