### PR TITLE
Graph-Panel: Center option for bar charts

### PR DESCRIPTION
**Pull request by clamber**
This PR adds a 'center'-option for bar charts.
We already used different visualization tools and we really missed this option in grafana.
So we decided to add it by ourselves and contribute.

The 'center'-option looks very nice if you have daily aggregated data, so the bar is shown right above the date.

Here are 2 Images to visualize the impact:

Bar-Chart - not centered:
Graph-Panel

Bar-Chart - centered:
Graph-Panel-Center

### CODE REVIEW

**Comment by torkelo** [comment]
Interesting, did not know flot had this option. 

Do we need an option for this? Maybe center should be the default?

thoughts @ryantxu?

**Comment by ryantxu** [comment]
@clamber -- this looks great.  I don't think "center" should be an option, we can just make it the default.

Can you update the PR?  I think it would just be a one-line change in `graph.ts`

**Review by ryantxu — CHANGES_REQUESTED** [review]
@clamber -- this looks great, but I think we should just make it the default option.

**Comment by clamber** [comment]
@ryantxu -- I just adapted the PR to use the center as new default option and removed center from the graph panel options. It was just the one-line change in graph.ts as expected.

**Review by ryantxu — APPROVED** [review]

**Comment by jrgilman** [comment]
Since this PR introduced a pretty massive regression with the tooltip, would rolling it back until a fix for #25102 is completed be an option? It seems like that fix has been pushed back several times now (was supposed to come out in 7.1 but now 7.2)...

**Pull request merged**
