### PR TITLE
Elasticsearch: Respect time range in ad hoc filters

### LINKED ISSUE #51381: Adhoc Filter: Wrong time range for Elasticsearch
**What happened**:

When using adhoc filter with Elasticsearch data-source, the filter options for given field X are mostly empty - `No Options found`.
(There are only options for fields which datasets are up to 6 hours old.)

**What you expected to happen**:

For a given time range, all options should be in the adhoc filter which are found in Elasticsearch query.
This was the case in Grafana version 6.4

**How to reproduce it (as minimally and precisely as possible)**:

* Set up an Elasitsearch index (Elasticsearch version 7.10+).
* Create a data-source with this index.
* Create a new dashboard with an adhoc filter for this index.
* Entries in index have to be at least 6 hours old.
* Select a index field as filter -> click on `select value` 
image

You might think now there is just no value for this field available, but this is not the case, as you see in the table of the attached image. The problem is, that the Elasticsearch query for filter values only looks for the Elasticsearch entries of the past 6 hours.

**Anything else we need to know?**:

I also opened an grafana community issue:
https://community.grafana.com/t/adhoc-filter-do-not-find-options/60379

Here again what I found out in my research:

The request payload to find the filter options loos like this:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"my_index"}
{"size":0,"query":{"bool":{"filter":[{"range":{"general.data_source_time_field":{"gte":"1654660925962","lte":"1654682525962","format":"epoch_millis"}}}]}},
"aggs":{"1":{"terms":{"field":"my_field","size":500,"order":{"_key":"asc"}}}}}
```
As you can see the query time-range is quite short:
```
"filter":[{"range":{"general.data_source_time_field":{"gte":"1654660925962","lte":"1654682525962","format":"epoch_millis"}
```
Make Unix time-stamp human readable shows:

    1654670375696 → Wednesday, 8. June 2022 06:39:35.696
    1654691975696 → Wednesday, 8. June 2022 12:39:35.696

So the time range is 6 hours and not related in any way to the range choose in dashboard.

Now, if there is no  entry in my_field for the last 6 hours (which is common in my case), Elasticsearch will give an empty result which leaves to an empty drop down for adhoc filter values.
Even if there would be some entries in the last 6 hours, the shown options will not correlate with the dataset of the chosen time range.

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: Elasticsearch 7.15
- OS Grafana is installed on: Sorry, not sure. Some Linux
- User OS & Browser: Chrome
- Grafana plugins: No
- Others:

### PR DESCRIPTION
**Pull request by gabor**
(fixes https://github.com/grafana/grafana/issues/51381)

when using the ad-hoc filters with Elasticsearch, to fill in the label-values, we send a query to Elasticsearch, and we need to specify the time-range.

currently we send a hard-coded 6hour-time-range.

we want to use the currently-selected-time-range, but that information does not arrive in the API call (it's the `datasource.getTagValues` call). other datasources use the `getTimeSrv` function to get access to the time-range, we do the same here.

how to test:
- make devenv soures=elasticsearch
- create a dashboard, save it
- go to dashboard-settings, variables, add a variable of type 'ad-hoc-filter', name it `hello`, choose the elasticsearch datasource for it, press [update], save dashboard
- go back to the dashboard
- at the top-left corner you should be able to see the `hello` text with a `[+]` next to it. click it. you should be able to choose label-names and label-values there
- open the browser-devtools, look at the AJAX-requests
- everytime you open the label-values (not label-keys) select-box, an ajax request `_msearch` will run. look at the data sent from the browser, it will be a JSON-ish structure. find this part: `{"@timestamp":{"gte":"number1","lte":"number2"`. those two numbers are the time-range, in milliseconds. calculate the difference of those two numbers `number2 - number1`, it should be the same as the currently chosen time-range, in milliseconds
- change the currently selected time-range to a different value, and repeat the test, and verify that `number2 - number1` is still correct

### CODE REVIEW

**Review by matyax — APPROVED** [review]
Verified that works as expected.

**Comment by matyax** [comment]
@gabor what do you think about adding a test for this change, to make sure we don't have a regression in the future?

**Comment by gabor** [comment]
@matyax wrote:
> @gabor what do you think about adding a test for this change, to make sure we don't have a regression in the future?

good idea! i added one.

**Review by matyax — APPROVED** [review]
Great work!

**Pull request merged**
