### PR TITLE
Logs Panel: Limit displayed characters to MAX_CHARACTERS

### LINKED ISSUE #96020: Grafana explorer - Fail fast when processing logs with extremely long lines (more than 100,000 characters)
### What happened?

Using Grafana v11.1.5, in the explorer view and loki datasource.

I have a query that returns 20 log lines and 20MB. 

1 of the 20 log lines is massive with over 19M characters. don't judge me :)

Grafana freezes for almost 30seconds, then shows the 19 lines, a blank line and message:

> Logs with more than 100,000 characters could not be parsed and highlighted

Message above is probably coming from [this bit of code](https://github.com/grafana/grafana/blob/e55100fa90848872eb1e31a75e3abee51fa9f480/public/app/features/explore/Logs/LogsMetaRow.tsx#L127)

Adding this to the end of the query makes it return instantly **and** shows the first 100K lines of the massive log line.

```
 | line_format `{{ __line__ | trunc 100000 }}` 
```

### What did you expect to happen?

I agree that grafana shouldn't be displaying the massive log line, but it should fail fast when dealing with a massive line and at show the first 100K of the massive log line instead of not showing anything.

### PR DESCRIPTION
**Pull request by matyax**
Closes https://github.com/grafana/grafana/issues/96020

As a measure to improve how the logs panel responds when dealing with excessively long lines, this PR limits the displayed characters to MAX_CHARACTERS, which is currently 100.000.

https://github.com/user-attachments/assets/e586562b-e6a7-4ad7-9b99-054c1fb380e0

### CODE REVIEW

**Comment by matyax** [comment]
A smaller limit might be used, but that opens a whole different discussion, as this is meant to allow users to use Grafana under extreme conditions.

Some background about the existing limit:
- https://github.com/grafana/grafana/pull/26405
- https://github.com/grafana/grafana/issues/19869

**Review by svennergr — COMMENTED** [review]
I think the visual should be different to the usual log line content. Also, maybe add a space before the ellipsis?

image

**Comment by matyax** [comment]
Good point @svennergr. I also felt that something was missing. How about:

secondary

Uses a secondary type button. I think primary is too flashy:

primary

**Review by svennergr — APPROVED** [review]

**Comment by matyax** [comment]
Yeah! Let's go with fill.

**Pull request merged**
