### PR TITLE
renderer: add device scale support

### LINKED ISSUE #22472: Renderer: Support rendering panels into images in different scales
**What would you like to be added**:

Grafana is able to receive an additional parameter named `scale` in its `/render` API and provide images in higher resolutions. For example, a call to `/render` API with `width=100&height=80&scale=2` will generate an image 200x160 in size. Also note that it is different from one generated with `width=200&height=160`, because the text is large on the former one.

**Why is this needed**:

The resulting images can be used for different device pixel ratios.

### PR DESCRIPTION
**Pull request by shankerwangmiao**
**What this PR does / why we need it**:

This pull request adds support for `scale` parameter to the renderer, make it able to render images for different scale ratios. This include 3 rendering backends: phantomjs, plugin_mode, and http_mode.

For interoperability with the current version of Image Renderer, the `scale` parameter passed to it will be simply ignored and the image with 1x scale will be generated.

**Which issue(s) this PR fixes**:

Fixes #22472

**Special notes for your reviewer**:

This PR is now a draft, because it relies on https://github.com/grafana/grafana-plugin-model/pull/3. After it is merged, I will remove the `replace` statements in `go.mod` and this PR will be able to be merged.

### CODE REVIEW

**Comment by shankerwangmiao** [comment]
@marefr I wonder if there is any progress on this pr?

**Comment by marefr** [comment]
@shankerwangmiao thank you for the contribution. Looks interesting and useful. However, we're in the process of removing PhantomJS from Grafana. In addition, the grafana-plugin-model is old (legacy) and not something we would like to make changes to - we're going to create a v2 of the renderer api.

**Comment by shankerwangmiao** [comment]
> @shankerwangmiao thank you for the contribution. Looks interesting and useful. However, we're in the process of removing PhantomJS from Grafana. In addition, the grafana-plugin-model is old (legacy) and not something we would like to make changes to - we're going to create a v2 of the renderer api. We've planned to add device scale factor for Grafana 7.0 if everything goes according to plan.
> 
> For now we have to wait with reviewing this, but since above will probably make most of your changes obsolete maybe we should close this and continue discussions, if any, in the issue you opened?

I understand your description about the current status of the renderer api. It's okay to close this pr if necessary.

**Comment by marefr** [comment]
Thanks @shankerwangmiao 

Closing in favor of #23625

**Pull request closed without merging**
