### PR TITLE
Sort Option for Raw Data and Raw Document Types For Elasticsearch Datasource Plugin 

### PR DESCRIPTION
**Pull request by vvvprabhakar**
# :bulb: Description:

Issue: Not able to sort raw documents, if I want to find the top N based on any attribute in ES Document 

For example, A ES document contains duration as an attribute, if I want to find top N in a specified time range, it was not possible

So, Added the options for ES Raw document and Raw Data for sortBy and OrderBy options

### CODE REVIEW

**Comment by vvvprabhakar** [comment]
For Issue #23991

**Comment by zoltanbedi** [comment]
Thanks for opening a pr. can you try to merge your branch with the upstream master  to resolve the conflicts?

**Comment by oddlittlebird** [comment]
Um, wow. 406 files. Are there any doc files actually touched with this? 

Or any way to make a new PR with just the files you updated?

**Comment by kaydelaney** [comment]
Can we rebase this against main?

**Comment by zoltanbedi** [comment]
@vvvprabhakar I'm going to close this now as there was no response from you. Send us a new PR please if you still looking forward this. Thank you.

**Pull request closed without merging**
