### PR TITLE
Correlations: Fix flaky integration tests

### LINKED ISSUE #63958: Build failures due to Explore

### PR DESCRIPTION
**Pull request by Elfo404**
Correlations tests are currently flaky due to hardcoded OrgIDs in generated requests.
This PR is an attempt to fix that by using instead the return value from the generated users on tests setup.
While what we did should have been mostly safe in an isolated env, this decouples the OrgID generation logic from the test itself in case - for instance - the created users' OrgId is different than 1 because of other tests running before this one, which should make the test more reliable. 

(hopefully) Fixes #63958

### CODE REVIEW

**Comment by Elfo404** [comment]
Hey Grot! what'sup?

This PR hopefully fixes flaky tests, we want to backport it so @grafana/grafana-release-eng will have an easier life releasing!

**Review by sakjur — APPROVED** [review]

**Review by zserge — APPROVED** [review]

**Comment by Elfo404** [comment]
Heads up: in https://drone.grafana.net/grafana/grafana/103961/3/9 the create tests failed, all API calls resulted in a 401, which is leading to believe there's some error happening with the users creation outside of the scope of this PR. i can't see any evident error in `CreateUserForTests` though. any idea? cc. @grafana/backend-platform

**Comment by papagian** [comment]
> Heads up: in https://drone.grafana.net/grafana/grafana/103961/3/9 the create tests failed, all API calls resulted in a 401, which is leading to believe there's some error happening with the users creation outside of the scope of this PR. i can't see any evident error in `CreateUserForTests` though. any idea? cc. @grafana/backend-platform

I'm also 👀 `CreateUserForTests()` for another flaky test

**Comment by dsotirakis** [comment]
@Elfo404 @papagian any chance we can merge this before EOD today?
We'd ideally like to re-run those tests for next week, combined with a PR we merged, and see the results 😌

**Comment by papagian** [comment]
> @Elfo404 @papagian any chance we can merge this before EOD today? We'd ideally like to re-run those tests for next week, combined with a PR we merged, and see the results 😌

I don't think that anything blocking this one to get merged
I have also opened this one #64125 that would hopefully improve things

**Comment by dsotirakis** [comment]
> > @Elfo404 @papagian any chance we can merge this before EOD today? We'd ideally like to re-run those tests for next week, combined with a PR we merged, and see the results 😌
> 
> I don't think that anything blocking this one to get merged I have also opened this one #64125 that would hopefully improve things

image

**Comment by Elfo404** [comment]
@papagian didn't look at your changes and i think there's a conflict now, sorry!

**Pull request merged**
