### PR TITLE
Chore: Add betterer test to track conversion of enzyme tests

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- adds `betterer` as a precommit + CI check
  - this will auto commit the betterer results file if the tests get better
  - if you need to force push an update to the results file (e.g. you've added something that makes the test worse, but can't fix it immediately) you can do so by running `yarn betterer -u`
- adds a test to track number of enzyme tests
  - it does this with a regex for `from 'enzyme'` to look for files with the import
- adds an emitted metric so we can create a nice graph on https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zoltanbedi** [comment]
So I tried this and when I changed something in a DerivedField.test.tsx I couldn't commit it. Is this expected? Other than that looks good.

**Comment by ashharrison90** [comment]
@zoltanbedi ah that's not good - what did you change? 🤔 

it should just auto commit the update if the test has gotten better. i wonder whether it was an error with the lint step that got swallowed by the following `&& betterer precommit`. i've swapped the order to see if that helps reporting the error, and i'll also add a comment to explain how to update the betterer results

**Comment by zoltanbedi** [comment]
I've tried your changes and it still fails. This is kind of confusing for me that I've only corrected a typo in the `DerivedField.test.tsx` file and the precommit hook fails. I guess this is expected that if you make changes in a file that is in the error list you should make it "better".

**Comment by ashharrison90** [comment]
@zoltanbedi ah ok i see the same problem:
```
   \ | /     _         _   _                     
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __ 
---ooooo--- | '_ \/ _ \ __| __/ _ \ '__/ _ \ '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |   
   / | \    |_.__/\___|\__|\__\___|_|  \___|_|   
 
🎉 Betterer (151ms): 1 test done!
✅ no enzyme tests: "no enzyme tests" stayed the same. (124 issues) 😐

1 test got checked. 🤔
1 test stayed the same. 😐

husky - pre-commit hook exited with code 1 (error)
```

don't worry, that's not the behaviour we want at all, i'll invesigate!

**Comment by ashharrison90** [comment]
ah looks like the problem is actually in betterer, it's been fixed here: https://github.com/phenomnomnominal/betterer/pull/954 but not released yet.

i'll move it to blocked for now and i'll reach out to see when that's likely to be released.

**Comment by ashharrison90** [comment]
@zoltanbedi latest version of betterer has now landed! should work fine now 😄

**Review by zoltanbedi — APPROVED** [review]
Awesome!

**Pull request merged**
