### PR TITLE
grafana-mixin: Fix expression for GrafanaRequestsFailing alert

### PR DESCRIPTION
**Pull request by lpugoy**
The intent of the alert is to get the ratio of 5xx to all status codes[^1]. With the original expression, the left hand side can have more than one row with the same labels except for the status code. This results in a promql error because it is doing a many-to-one matching. Doing a sum on the left hand side first should preserve the intent of the alert and resolve the issue.

[^1]: https://github.com/grafana/grafana/pull/43116

**What is this feature?**

Fixes the expression for the GrafanaRequestsFailing alert.

**Why do we need this feature?**

The promql expression will raise an error in some circumstances.

**Who is this feature for?**

Users of the grafana mixin.

**Which issue(s) does this PR fix?**:

No raised issue.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lpugoy** [comment]
Screenshot showing the promql error.
rule error

**Comment by lpugoy** [comment]
I see that a similar PR was just merged: https://github.com/grafana/grafana/pull/58174. I would like you to reconsider using this approach instead.

The merged PR does a `group left` to make the many to one matching explicit. While this does resolve the promql error, I feel it doesn't preserve the intent of the alert.

By its name and message annotation, the alert should fire if requests for the handler are failing above a threshold, which means all `5xx` status codes. By doing a `group left`, the error threshold is being compared against _each_ `5xx` status code. For example:

`group left` approach:
```
threshold: 50
{handler="/api/datasources/:id/resources", job="grafana", namespace="grafana", status_code="502"} = 30
{handler="/api/datasources/:id/resources", job="grafana", namespace="grafana", status_code="500"} = 30
```
Alert wouldn't fire. :x:

`sum without (status_code)` approach:
```
threshold: 50
{handler="/api/datasources/:id/resources", job="grafana", namespace="grafana", status_code="502"} = 30
{handler="/api/datasources/:id/resources", job="grafana", namespace="grafana", status_code="500"} = 30
```
Alert fires. :white_check_mark:

**Comment by pharaujo** [comment]
I agree with @lpugoy , this was my original intent ^

**Review by bergquist — APPROVED** [review]
Yea this looks great! Thank you for contributing

**Pull request merged**
