### PR TITLE
PublicDashboards: Orphaned public dashboard deletion script added

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

PublicDashboards: When a dashboard was deleted, public dashboard was not also deleted. There was already a change to delete also public dashboards, but there can be remaining orphaned public dashboards before this chain deletion which can appear in Audit table.

This feature makes a deletion on public dashboard table, for those who don't have a dashboard.

**Why do we need this feature?**

Deletes orphaned public dashboards.

**Which issue(s) does this PR fix?**:

Fixes [#478](https://github.com/grafana/grafana-enterprise/issues/4591)

**Special notes for your reviewer**:

### CODE REVIEW

**Review by owensmallwood — APPROVED** [review]
Bulk deletion migrations are scary. This is a great Halloween PR 😱 

Tested it out just be sure, and works as expected. LGTM 👍

**Review by jalevin — CHANGES_REQUESTED** [review]
Let's hold off on this. Will discuss at standup

**Comment by jalevin** [comment]
Discussion follow-up post standup.

We did not previously delete public dashboards when deleting a dashboard so it is possible that instances have orphaned public dashboards. This migration deletes those. We are also merging (today) the ability for a user to delete dashboards from the audit table. Orphaned dashboards will be shown as well with the ability to delete them.

@bergquist How do you feel about this destructive migration?

**Review by owensmallwood — COMMENTED** [review]
Did we decide to go ahead with this? Can't remember, it was so long ago lol

**Comment by jalevin** [comment]
I followed up directly with @bergquist and @grafana/hosted-grafana-team via slack.

**Review by jalevin — APPROVED** [review]
Per discussion with @hairyhenderson: There is no way to run this same sql across instances in cloud that are archived. We do have an alternative to do this in the UI, however, it's straight forward, basically idempotent, and an edge case that is covered moving forward, so we'll run this one.

**Pull request merged**
