### PR TITLE
DataLinks: Do not add empty links

### LINKED ISSUE #24016: Panel: Add data/panel link can clicking Cancel/Close still adds the link
**What happened**:
Edited a panel add clicked on Add link in Data Links sections. In the opened modal clicked Cancel, but link was still added. Same applies if click on Close icon (X) of modal.

**What you expected to happen**:
No link added.

**How to reproduce it (as minimally and precisely as possible)**:
1. Edit a panel
2. For data/panel links click Add link
3. Click on Cancel or Close icon of modal
4. Observe empty link added to list of links

**Anything else we need to know?**:
image

**Environment**:
- Grafana version: 7.0.0-beta1

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #24016

### CODE REVIEW

**Review by tskarhed — CHANGES_REQUESTED** [review]
While the modal is open the list still displays an uncreated link. (Disappears on cancel though)
Screenshot from 2020-04-30 14-47-24

**Comment by dprokop** [comment]
> While the modal is open the list still displays an uncreated link
:D

**Comment by marefr** [comment]
Waiting to review this until Tobias comment is addressed.

**Comment by dprokop** [comment]
@tskarhed @marefr -> ready for the review

**Review by tskarhed — APPROVED** [review]
LGTM!

**Pull request merged**
