### PR TITLE
[v.8.2.x] Chore: Backport for missing tslib import

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉

**Comment by hugohaggmark** [comment]
Verified that this solution works and that the base branch seems correct

image

**Comment by joshhunt** [comment]
@hugohaggmark agree that it shouldn't matter, but i rebased this back to latest 8.0.x

**Comment by hugohaggmark** [comment]
Let me know when I can retry to verify it.

**Comment by joshhunt** [comment]
oops sorry. wrong PR. was talking about 8.0.x 🤦

this one was not touched.

**Comment by axelavargas** [comment]
Closing this PR, in favor of https://github.com/grafana/grafana/pull/43556 , because we could get a version missmatch between the typescript version used to build the plugin and the one used to build Grafana.

**Pull request closed without merging**
