### PR TITLE
ReleaseNotes: Updated changelog and release notes for 7.4.0

### PR DESCRIPTION
**Pull request by grafanabot**
This exciting! So much has changed!

### CODE REVIEW

**Review by Elfo404 — DISMISSED** [review]

**Comment by torkelo** [comment]
@Elfo404 let me do a manual tweak here, the automation does not handle combining the beta and stable in the release notes (for docs site)

**Comment by Elfo404** [comment]
@torkelo was actually going to ask about this as it felt a bit weird.

**Review by torkelo — APPROVED** [review]
@Elfo404 done

**Review by Elfo404 — APPROVED** [review]
sweet!

**Pull request merged**
