### PR TITLE
Elasticsearch: Fix view percentiles metric in table without date histogram

### LINKED ISSUE #3786: Elasticsearch table view Percentiles metric
Hi!
I try to use table view as describe here https://github.com/grafana/grafana/issues/3578 and bring Percentiles. And table show a empty cell. Here an example

### PR DESCRIPTION
**Pull request by Ihor-Ratsuk**
closes #3786

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thanks. Overall looks good. 

However, comparing table using date histogram and without date histogram  the selected metric of the percentile should be included in the column name.

image

**Comment by snowberrylee** [comment]
May I ask whether this change is included in grafana 6? 
Can you also show me how to view percentiles in a non-time series table? (Just as your second table panel in your screenshot )

**Comment by marefr** [comment]
@snowberrylee this is an open pull request for adding the support as shown in the second table panel so no this is not included in Grafana 6.

**Comment by snowberrylee** [comment]
@marefr then is it possible for me to make use of this request currently?

**Comment by marefr** [comment]
@snowberrylee it's not that easy. You must checkout the authors branch and build Grafana from source

**Comment by snowberrylee** [comment]
@marefr Oh I see. What grafana version will be most likely to include this change?

**Comment by marefr** [comment]
@snowberrylee no ETA right now

**Comment by Yukinoshita-Yukino** [comment]
This is awesome!
Just a question.
The changes are made on `elastic_response.ts` so I guess this will make alert on ES percentile values possible?

**Comment by marefr** [comment]
@Yukinoshita-Yukino alert on ES percentile using group by date histogram should already be working. This change fixes so that ES percentile without using date histogram can be properly visualized in table panel, but that's a tabular query which are not supported in alerting scenarios - only time series queries are.

**Comment by marefr** [comment]
@Igor-Ratsuk Have you had any change looking into my requested changes?

**Comment by Igor-Ratsuk** [comment]
Hello @marefr, I'm sorry for the delay, will update my PR today.

**Review by marefr — APPROVED** [review]
Great :+1:

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
