### PR TITLE
Alerting: Fix overflow for long receiver names

### PR DESCRIPTION
**Pull request by gillesdemey**
**Before**
image

**After**
image

### CODE REVIEW

**Comment by tomratcliffe** [comment]
Thanks! What do you think about doing a `lineBreak: 'anywhere'` or similar, to force it to go onto another line? It'll already line break if there's a long contact point name with spaces in it. WDYT?

**Comment by gillesdemey** [comment]
Not a huge fan of tackling it as such (as you've pointed out it does weird things with other components in the header but that can be fixed); really long names should be rather extra-ordinary and using `truncate` on the `Text` component will ensure it renders a popover too for those rare occasions. 

In fact I think long names with spaces should probably also just overflow but I'll defer on that for now :D

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM!

**Review by konrad147 — APPROVED** [review]
LGTM!

**Pull request merged**
