### PR TITLE
Proposal to improve the alert rules page for instances with many alerts

### PR DESCRIPTION
**Pull request by jsferrei**
@torkelo I'm toying around with this as an option to solve https://github.com/grafana/grafana/issues/14269

Still needs some work (or perhaps some help from someone with better React skills than me), so don't want to move to PR just yet.

### CODE REVIEW

**Comment by torkelo** [comment]
not sure infinite scroll is the right way to handle pagination for this page. Feels like pagination in the api and on the page is better but would require more substantial changes.

**Comment by torkelo** [comment]
Closing this for now, please re-open new or ping me on this if you have another approach.

**Comment by jsferrei** [comment]
@torkelo Don't have anything right now, but it looks like https://bvaughn.github.io/react-virtualized/#/components/WindowScroller exists. We could attempt to get that working. That way the page _looks_ the same, but renders faster. Other options besides changing the API to support pagination I've seen implemented are [this](https://codesandbox.io/s/mm3kvjo0z9)

**Comment by jsferrei** [comment]
@torkelo Implemented the WindowScroller approach. It looks and behaves nearly identically to the original page (just needs a little styling help -- I lost the margins between the AlertRule elements).  

Do you think pagination at the API level is the preferred approach still? One downside to it I can see is search may become a little more cumbersome.

**Pull request closed without merging**
