### PR TITLE
Alerting: Add more context to delete modals

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

Adds additional context to the delete modal so the user is aware of what they're asked to delete.

Affected modals in this PR:

* Delete alert group
* Delete alert

### CODE REVIEW

**Comment by dhalachliyski** [comment]
Could you reverse the order of the buttons so that the destructive button is on the right?
Also, how about instead of "Yes, delete policy", just have "Delete"?

**Comment by brendamuir** [comment]
Do we need the info on the matchers? 
Could we just say "Are you sure you want to delete this notification policy?"
If not -- "Are you sure you want to delete this policy with the following label matchers?"

**Comment by dhalachliyski** [comment]
On the label matching topic:
What if don't call them out specifically, but instead just say "Are you sure you want to delete this notification policy?" as suggested. Then we visualize the policy not just by the matchers, but by a full width rectangular container that has the matchers left-aligned, and the contact point right-aligned (kind of what is being done currently for the Routing Preview)? The we'll also not need the horizontal line.

**Comment by gillesdemey** [comment]
Yea I think that would work better, but those components are a work-in-progress and I'd rather not duplicate our efforts there; I'll revert the changes for the notification policies modal for now and that way we can at least merge some incremental improvements.

**Review by konrad147 — APPROVED** [review]
LGTM!

**Pull request merged**
