### PR TITLE
Release: Bump version to 7.5.7

### PR DESCRIPTION
**Pull request by grafanabot**
Executed:

npm version 7.5.7 --no-git-tag-version

npx lerna version 7.5.7 --no-push --not-git-tag-version --force-publish --exact --yes

### CODE REVIEW

**Comment by dafydd-t** [comment]
FYI this is related to [this thread](https://raintank-corp.slack.com/archives/CMSUYD6H3/p1623144267417700) - we noticed the version on this `v7.5.x` branch is one behind the latest release (7.5.7), resulting in prerelease builds having the wrong version ([example](https://drone.grafana.net/grafana/grafana/25546/3/34))

**Review by marefr — APPROVED** [review]
LGTM

**Review by dsotirakis — APPROVED** [review]

**Comment by dafydd-t** [comment]
@dsotirakis I don't have permissions to merge on here, could you do it please?

**Comment by dsotirakis** [comment]
@dafydd-t Done! Thanks for that!

**Pull request merged**
