### PR TITLE
Cloudwatch: Add MeteredIOBytes metric for EFS

### PR DESCRIPTION
**Pull request by xlagg5**
**What is this feature?**

Adds missing metric from EFS Cloudwatch which is MeteredIOBytes.

**Why do we need this feature?**

We need this from improved CloudWatch plugin.

**Who is this feature for?**

For Cloudwatch EFS users.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sarahzinger** [comment]
@xlagg5 thank you for your PR! Would you be able to sign our CLA so we might be able to merge this change?

**Comment by xlagg5** [comment]
> @xlagg5 thank you for your PR! Would you be able to sign our CLA so we might be able to merge this change?

Done!

**Review by sarahzinger — CHANGES_REQUESTED** [review]
@xlagg5 thanks for signing the CLA! Taking a closer look and I'm wondering, does this work for you? It looks like it's under EC2Spot and not under EFS. Mind taking another look?

**Comment by xlagg5** [comment]
> @xlagg5 thanks for signing the CLA! Taking a closer look and I'm wondering, does this work for you? It looks like it's under EC2Spot and not under EFS. Mind taking another look?

Oh no! It was a mistake. Now it is fine.

**Review by idastambuk — APPROVED** [review]

**Review by sarahzinger — APPROVED** [review]

**Pull request merged**
