### PR TITLE
Dashboards: Variables - Improve slow template variable loading due same variable loaded multiple times on time range change

### LINKED ISSUE #53388: Slow template variable loading due same variable loaded multiple times on time range change
**What happened**:
Most template variables are loaded multiple times on time range change, which slow down template variable loading maybe 3-10x.

**What you expected to happen**:
Template variables should be loaded only once in dependency order.

Loading large number of template variables (+10) already now result now queuing/waiting because Grafana has limited number of threads for loading, and similarly Prometheus process only limited number of parallel queries. Some queries might be also slow and making them multiple time is also expensive.

**How to reproduce it (as minimally and precisely as possible)**:
It Looks that dependent template variables are reloaded every time when dependent template variable value is changes (template variables refreshed "on time range change"). 

We have dependencies in template variables. We use following kind of template variables queries to filter the desired uservices:

```
job = label_values(system_cpu_usage{},job)
dc = label_values(system_cpu_usage{job=~"$job"},dc)
hostall = label_values(system_cpu_usage{job=~"$job", dc=~"$dc"},host)
teamname = label_values(system_cpu_usage{job=~"$job"}, teamname)
country = label_values(system_cpu_usage{job=~"$job"}, country)
severity = label_values(system_cpu_usage{job=~"$job"}, severity)
```

Then we use created variables to create list of uservices called "appall" and "dnsname" (appall enables "Include All option" and can be used on system wide panels, whereas dnsname disables "Include All option" and used in panels using repeating panels preventing huge number of repeating panels)

```
appall = label_values(system_cpu_count{job=~"$job", dnsname=~"$appall", teamname=~"$teamname", country=~"$country", severity=~"$severity", host=~"$hostall"}, dnsname)
dnsname = label_values(system_cpu_count{dnsname=~"$appall"}, dnsname)
```

This allow fillering uservices by team, country, severity and host. And further selecting specific dnsnames from filtered lists.
Job is needed to filter the env, same prometheus have data from multiple env like dev/test

Then other template variables reuse job and dnsname/appall (job could be removed from some queries because dnsname/appall already filtered using job)

Examples:
```
pool_netty_appall = label_values(reactor_netty_connection_provider_active_connections{job=~"$job", dnsname=~"$dnsname"}, dnsname)
statementType = label_values(datasource_seconds_count{job=~"$job", dnsname=~"$appall"}, statementType)  
```

Some template variables has still additional dependencies:
```
clientName = label_values(http_client_requests_seconds_count{job=~"$job", dnsname=~"$appall"}, clientName)
clientNameUriAll = label_values(http_client_requests_seconds_count{job=~"$job", dnsname=~"$appall", clientName=~"[[cnameall]].*"}, uri)
```

The F12 network debug shows that instead of requesting each template variable once, many template variables like dnsname, pool_netty_appall and statementType are requested multiple times.

Test result from dashboard having 19 dependent template variables: 
When teamname, country and severity, appall are "All" (wildcard) then 60 template variables are loaded instead of 19.
When teamname, country and severity, appall are filtered with specific values then 77 template variables are loaded instead of 19.
If dashboards ~40 template variables, most dependent, it result ~150-200 template variable loading, an dloading might take tens of seconds.

It seems that dnsname/appall template variable is reloaded up to 5 times, but also all template variables which has dnsname/appall dependency are also releaded "up to 5 times".

I suspect that this is due dnsname/appall dependency which has dependencies like
dc, teamname, country, severity --> job
hostall--> job, dc
appall --> teamname, country, severity, hostall
dnsname-->appall

It looks that Grafana queries all template variables immediately (result some queuing/stalling when more than 10 variables), it takes up to 1s to resolve all variables (takes longer if some variables are queried over specific timerange, when timerange is > 1d) . 
When teamname, country, job or hostall variable is updated it probably will trigger dependent template variables to be reloaded again and again (4 times due 4 dependent variables).

When time range change then also possible values of template variables might change, which justify the reload but this is not optimal because large number of queries result blocking, and result are still discarded. 

It would be better to load template variables once but in correct order 
1. load variables which does not have dependencies to other template variables (like job, dc, teamname, country,severity in above)
2. load template variables which has dependencies to other template variables in groups as needed 
  A) appall, hostall
  B) dnsname
3. load remaining template variable

In practice this means using available dependency graph information and loading variables in groups in dependency order when needed instead of loading all parallel and reloading again and again.
BTW Dependency graph visualization is not showing dependencies "clearly" when there are many dependencies, visualization is simply too flat.

How to optimize template variable loading
- minimize use of dependent template variable (but this removes filtering capabilities)
- minimize use of refresh "On Time range change" (but refresh "On dashboard load" loads too early, for example when job/env needs to be changed, and all other variables depends on job)
- use fixed values in template variables instead of dynamic (only works for small fixed set of variable values)

**Anything else we need to know?**:

**Environment**:
- Grafana version: All versions at least 8 and 9
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux, Windows
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**
Refactor function `variablesRefreshTimeRange` to use the dependency graph to prevent resolving variables multiple times. 

##### Current Behaviour: Case # 1 - Basic chained variable

In this case, `variablesRefreshTimeRange=[A, B, C]` we trigger all the 3 variables in parallel, then when A is resolved, B and C trigger again. This will trigger in total 5 API requests instead of 3. 

variables system_3

##### Proposal

Design Doc: [Design Doc - Template variables are loaded multiple times](https://docs.google.com/document/d/1CqlO3B63EI59Vrsiob84IcKXcnuMMeK963RGIOpfhvI/edit#)

The idea is to avoid returning all the variables that have a time range configured. Instead, we should return only the variables that are time range and don't have dependent nodes, as well as variables that are time range and have dependent nodes. We should not return dependent nodes that are time range, as the parent variable will cause a cascading update as soon as the variable is resolved.

- Create a graph based on all template variables.

- Loop through all the variables and perform the following checks for each variable:

	- If a variable A is a query variable, it’s time range, and has no dependent nodes, it should be added to the variablesRefreshTimeRange.
	- If a variable A is a query variable, it’s time range, and has dependent nodes (B, C), add the variable A to variablesRefreshTimeRange and skip all the dependent nodes (B, C). Here, we should traverse the tree using DFS (Depth First Search), as the dependent nodes will be updated in cascade when the parent variable is updated.

### **Note: Changes behind feature flag: `refactorVariablesTimeRange`: ** 
This PR does not fix the issue 100% but provides a significant improvement.  The changes are behind a feature flag called `refactorVariablesTimeRange`.  Why? Because template variables are a complex piece of code and we want to make sure to test this first.  

#### Results on case # 1:
With the algorithm, `variablesRefreshTimeRange=[A]`, here we trigger `A` initially, then when A is resolved, B and C are triggered. 

```
Improvement (%) = ((Old API calls - New API calls) / Old API calls) * 100
Improvement (%) =  ((5 - 3) / 5) * 100) = 40%

```

#### Results on case # 3: Multiple variables depend on 2 main variables (all of the variables are time range)
variables system_8

Old Algorithm total API calls = Initial calls 15 +  when A is resolved: 13 + when B is resolved: 13 = 41

New Algorithm total API calls =Initial calls 2 +  when A is resolved: 13 + when B is resolved: 13 = 28
```
Improvement (%) = ((Old API calls - New API calls) / Old API calls) * 100
Improvement (%) =  ((41 - 28) / 41) * 100) = 31.7%


```
**Why do we need this feature?**

When variables are configured on time range, our current function triggers all the variables in parallel, and then per each variable that has dependant nodes, variables are triggered again. 

**Who is this feature for?**

Everyone
**Which issue(s) does this PR fix?**:

Fixes #53388

**Special notes for your reviewer:**

There are some `console.logs` here, this is for testing purposes :) 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by kaydelaney — COMMENTED** [review]
Looks good to me!

**Review by torkelo — COMMENTED** [review]
I think I understand the scenario. 

It something like this

A <- B  <- C    (C depends on B, depends on A)

If both A and C have "refresh on time range" then C will be updated twice. 

think it looks ok, but my god it will good to get rid of this template variable system madness. The scenes system is radically simpler

**Review by dprokop — APPROVED** [review]
@axelavargas this is looking good flow-wise. Thanks for providing plenty of code comments, this will be very helpful in the future.

**Comment by mthomann17** [comment]
@torkelo is there any chance this issue also exists on initial dashboard load and it did not get fixed with this PR? We have a dashboard with 23 variables with most of them dependent on the preceding variables. So for variables A, B, C, & D, D depends on A, B, & C, C depends on A & B, B depends on A, etc.

What we are seeing is when we started to get to ~20+ variables the initial dashboard load really started slowing down. With the final version of the dashboard with all 23 variables, the dashboard takes 2.5 minutes to load. Once the dashboard is loaded performance within the dashboard is fast including when updating the variables. If I update variable A the rest of the variables all update within a second.  We also noticed the amount the time to load the dashboard increases more with each new variable we added. Finally when I updated the variables to not be dependent on each other the dashboard loads instantaneously. 

The issue sounds a lot like this one so we wanted to check to see if this is a similar issue. We are using Grafana Community v10.2.0 and our datasource is MySQL.

**Comment by torkelo** [comment]
it should be ready for general use in a couple of months, we are just finishing all the "view" features, and will soon start focus on editing

**Comment by mthomann17** [comment]
@torkelo I just tried that out and the dashboard loaded instantaneously so that will do the trick. Looking forward to the release to the general public. I like the fact that the variables are sticky at the top now as you scroll down, but was wondering if there going to be a way to collapse the variable view? With the 23 variables and multiple selections across them it ends up taking half the screen real estate. Love the product btw we use it quite a bit at my company!

**Comment by torkelo** [comment]
@mthomann17 well it loads, you can then see each variable as it's query is being executing (spinner), all the panels with queries that use a variable still in loading state will wait for it. 

How long does it take for all variables to finish and for the panels to show data?

**Comment by mthomann17** [comment]
@torkelo all the dashboard variables now load in about 1 second and all the panels are loaded shortly after. That is compared with the dashboard taking 2.5 minutes to load with v10.2.0. After the dashboard is initially loaded performance is similar for both, it is really just that initial load which is way faster now.

**Pull request merged**
