### PR TITLE
Telegram notifier improvements

### PR DESCRIPTION
**Pull request by wf1nder**
- Add ability to attach rendered graph into telegram chat, even if external sotrage is not used, see issue #8246
  - Some cosmetic changes in message formatting

### CODE REVIEW

**Comment by wf1nder** [comment]
Here screenshots how it looks in desktop and mobile telegram.

desktop
<br>
mobile

**Comment by torkelo** [comment]
not sure I like this, the code becomes pretty messy, the image upload etc. Can we just have the imageUrl (that requires the external image store) ? 

Maybe this is fine as it's simpler to use and not requiring an external image store makes it easier to start using. But the code needs to be cleanup up and refactored to make it easier to read & maintain. 1-3 unit tests would also help a lot.

**Comment by wf1nder** [comment]
It is not always possible and conveniently to use external image storage, but this patch making possible to send images natively inside message. 
I am afraid I do not have sufficient skills to make the code less messy. I would be grateful if someone helped me to improve it. Anyway, we already using this patch in our project, so we can just continue using our own fork :(

**Comment by torkelo** [comment]
ok, that's a shame. Will close it then if you do not have time to work on it more. Maybe someone else will find it and continue the work

**Comment by rburchell** [comment]
@torkelo Can you be a bit more specific in what you'd like to see here? I can't promise anything but I'd really like to see this happen.

**Comment by torkelo** [comment]
Code cleanup and refactoring plus unit tests

**Pull request closed without merging**
