### PR TITLE
Change Public Dashboard text in Enterprise Users section

### PR DESCRIPTION
**Pull request by lucychen-grafana**
**What is this feature?**

Update the texts for public dashboards under Users section 

**Why do we need this feature?**

Naming change to be consistent with sharing dashboard path moving forward

**Who is this feature for?**

Customers

**Which issue(s) does this PR fix?**:

Fixes #https://github.com/grafana/grafana-enterprise/issues/7029

**Special notes for your reviewer:**
In conjunction with this pr https://github.com/grafana/grafana-enterprise/pull/7051

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by lucychen-grafana** [comment]
/deploy-to-hg --enterprise-ref lucychen/change_pd_text_users_section

**Review by juanicabanas — APPROVED** [review]
LGTM!

**Pull request merged**
