### PR TITLE
Added a checkbox to templates that refreshes template values on time range change

### LINKED ISSUE #3427: FR: Refresh Template Variable on time range change
The "Refresh on load" option for template values seems to work well.
However, it would be nice if it was also possible to refresh when the timespan changes.
For example, if I have metric A, for which the most recent data is from 5 seconds ago, and metric B, for which the most recent data is from 1 day ago, I run into the following issue:
I set up the template while my time span is set to "last 5 minutes".  The results of the query at this point only contains metric A.  If I later change my time span to "last 7 days", it still only displays metric A in the template, even though the result of the query at this point would be both metric A and metric B

### PR DESCRIPTION
**Pull request by NickG123**
If the checkbox is selected, the query for the values of the template is re-run whenever the refresh button is clicked, or the time range changes.

Ui Changes:
template

This closes #3427

### CODE REVIEW

**Comment by torkelo** [comment]
I would like to combine the Refresh option into one, so instead of having two refresh boolean options on the annotation model have a single "refresh" property that can either be "Never", "OnDashboardLoad" eller "OnTimeChange". So instead of having two checkboxes have a single dropdown option. 

You might have to add a schema upgrade block to dashboardSrv

**Comment by NickG123** [comment]
Done.  Here's the new UI changes:
grafana2
Let me know what you think.

**Comment by torkelo** [comment]
great, will review

**Comment by mtanda** [comment]
@NickG123 Sorry, my recent change might cause conflict.
Would you resolve the conflict?

**Comment by NickG123** [comment]
Closed in favor of #4281

**Pull request closed without merging**
