### PR TITLE
Connections: Simplify connections nav

### PR DESCRIPTION
**Pull request by torkelo**
**Slack thread:** https://raintank-corp.slack.com/archives/C034LMXLXQU/p1681835191084819

As discussed over slack this simplifies and flattens the nav hierarchy in Connections 

* Make Connect data a normal page and not a section with no children
* Remove the nested section "Your connections" as it has so few children (only 1 in OSS) 
* Rename Connect data to "Add new connection" to make it clear that this is where you go to create new connections.

Could need help from the connections devs (@leventebalogh ?) to complete this PR as it might need changes in plugins (and in plugin nav config). 

I also did not change any urls in this PR (they still include /your-connections) I think it might be good to change those as well. And the connect data page that was renamed is connect-data in URL as I assume that is referenced by  a plugin config to override that URL. 
 
image

### CODE REVIEW

**Comment by leventebalogh** [comment]
Thanks for opening this @torkelo! 👍 

I think technically this change is not complicated, we have to pay attention to change things in other places accordingly as you said. I also agree that we should update the URLs (and the nav-ids), too, to keep the code in a consistent state. 


**Changes required in other places**
- [ ] Update the page paths in the grafana-easystart-app [here](https://github.com/grafana/cloud-onboarding/blob/main/plugin/src/plugin.json#L118) (it is needed to be able to register them correctly under the Connections section using the Grafana config)
- [ ] Update the hosted-grafana configuration [here](https://github.com/grafana/hosted-grafana/blob/main/pkg/hgapi/instance/config_ini.go#L196) (It is the Grafana INI configuration that is setting which section the standalone pages from the plugin should be registered to. In case we update the URLs in core - which I believe we should - then these need to updated, too.)


**Another question:** as the cloud instances would break if we publish the updates of core and the plugins separately, how do we make sure that they get deployed "at the same time"?

Also summoning @mikkancso and @jarben.

**Comment by mikkancso** [comment]
> As the cloud instances would break if we publish the updates of core and the plugins separately, how do we make sure that they get deployed "at the same time"?

I think that's the critical question. WDYT about adding that config to the default Grafana config? That way probably we wouldn't have to synchronize the config update in Hosted-Grafana-API with the release. I'm gonna ask the Grafana SaaS team about this.

**Comment by mikkancso** [comment]
Once https://github.com/grafana/hosted-grafana/issues/3859 is done, we should be fine and we can move forward with this PR.

**Comment by jarben** [comment]
> Once https://github.com/grafana/hosted-grafana/issues/3859 is done, we should be fine and we can move forward with this PR.

@mikkancso isn't this already supported [here](https://github.com/grafana/hosted-grafana/blob/main/pkg/hgapi/features/features.go#L21)? Or could we just use `if inst.ActualVersion.Compare(semver.MustParse("10.0.0-0")) >= 0` if we want to keep one feature flag only? 

Also this change may affect this [issue in hg-cloud-home-admin](https://github.com/grafana/hg-cloud-home-admin/issues/291). @yduartep I'd suggest to wait with implementing this issue after G10. Looks like the current [redirect](https://github.com/grafana/cloud-onboarding/blob/main/plugin/src/pages/Routes/ConnectionRoutes.tsx#L55) in the plugin will handle this change without an issue @mikkancso ? 

We also need to update the [PDC plugin](https://github.com/grafana/grafana-pdc-app/issues/44) to reflect this, cc @fabienne-m

**Comment by yduartep** [comment]
> > Once [grafana/hosted-grafana#3859](https://github.com/grafana/hosted-grafana/issues/3859) is done, we should be fine and we can move forward with this PR.
> 
> @mikkancso isn't this already supported [here](https://github.com/grafana/hosted-grafana/blob/main/pkg/hgapi/features/features.go#L21)? Or could we just use `if inst.ActualVersion.Compare(semver.MustParse("10.0.0-0")) >= 0` if we want to keep one feature flag only?
> 
> Also this change may affect this [issue in hg-cloud-home-admin](https://github.com/grafana/hg-cloud-home-admin/issues/291). @yduartep I'd suggest to wait with implementing this issue after G10. Looks like the current [redirect](https://github.com/grafana/cloud-onboarding/blob/main/plugin/src/pages/Routes/ConnectionRoutes.tsx#L55) in the plugin will handle this change without an issue @mikkancso ?
> 
> We also need to update the [PDC plugin](https://github.com/grafana/grafana-pdc-app/issues/44) to reflect this, cc @fabienne-m

I have not worked on this issue yet because I have seen that there is an automatic redirect and then I wanted to wait for a complete rollout of the nav. In any case, I will wait after Grafana 10 to see what happens.

**Comment by mikkancso** [comment]
> @mikkancso isn't this already supported [here](https://github.com/grafana/hosted-grafana/blob/main/pkg/hgapi/features/features.go#L21)? Or could we just use if inst.ActualVersion.Compare(semver.MustParse("10.0.0-0")) >= 0 if we want to keep one feature flag only?

Thanks, I haven't realized that. I think we should go with your latter suggestion.

> Also this change may affect this https://github.com/grafana/hg-cloud-home-admin/issues/291. @yduartep I'd suggest to wait with implementing this issue after G10. Looks like the current [redirect](https://github.com/grafana/cloud-onboarding/blob/main/plugin/src/pages/Routes/ConnectionRoutes.tsx#L55) in the plugin will handle this change without an issue @mikkancso ?

Yeah, I think we can prepare the plugin to redirect to the correct url based on the Grafana version. I'll look into this now in depth.

**Comment by mikkancso** [comment]
I updated this PR with the renaming of the URLs, component names and navIDs.
I also opened PRs in cloud-onboarding and hosted-grafana repos (see above :point_up: ). They are all draft PRs at the moment, but the whole thing together seems to be working.

**Comment by torkelo** [comment]
@mikkancso @leventebalogh so when can we merge this?

**Review by mikkancso — APPROVED** [review]

**Comment by mikkancso** [comment]
> @mikkancso @leventebalogh so when can we merge this?

I think we can merge this as soon as checks pass on this PR

**Pull request merged**
