### PR TITLE
Docs:  standardize image shortcodes, assets paths (/latest)

### PR DESCRIPTION
**Pull request by robbymilo**
**What this PR does / why we need it**:

Standardizes all image shortcodes to use `figure`, which ultimately uses the figure partial.

Needed for https://github.com/grafana/website/pull/4580

See also https://github.com/grafana/grafana/pull/34826

### CODE REVIEW

**Comment by osg-grafana** [comment]
7.5.x has already shipped. Why are we touching it?

**Review by osg-grafana — APPROVED** [review]
Approving, but why are we touching 7.5 docs still?

**Comment by robbymilo** [comment]
@osg-grafana Still need to update the shortcodes for old versions.

**Comment by oddlittlebird** [comment]
@osg-grafana, because all the versions are in the same branch, as far as Hugo is concerned, it's all one site. Changing the shortcodes for 8.0 also changes them for all the other versions. A related question is, are the other versions going to be updated?

**Comment by robbymilo** [comment]
@oddlittlebird Yes, see the website PR.

**Comment by oddlittlebird** [comment]
You rock, @robbymilo. If you ever get to the Pac NW, I'm buying you donuts or something.

**Review by achatterjee-grafana — APPROVED** [review]

**Pull request merged**
