### PR TITLE
Panel Inspect: Hide minimap in json view

### PR DESCRIPTION
**Pull request by torkelo**
I have personally never find vscode's minimap useful, and find it more distracting than good. And in the inspect drawer it's blocking content that I rather see.  

thoughts? 

Screenshot from 2020-07-04 12-25-25

### CODE REVIEW

**Comment by ryantxu** [comment]
Can we increase the length where it turns on?  I find it super useful when scrolling through super long lists.  Things like this:

image

**Comment by torkelo** [comment]
> Can we increase the length where it turns on? 

Can we make it more depend on screen width?

**Comment by torkelo** [comment]
But I see now that for large responses and many series, you see a pattern in the minimap that I usually fail to see (in code)

**Comment by torkelo** [comment]
think it's fine, changed my mind :)

**Pull request closed without merging**
