### PR TITLE
InfluxDB: Use explicit Tag annotation for tag keys in InfluxDB queries

### LINKED ISSUE #61335: Grafana Query Builder and Ad Hoc Filters for InfluxDB Datasources should use "::tag" syntax.
**What happened**: 
Using the Grafana Query Builder and Ad Hoc Filters on an InfluxDB Datasource that has tags and fields with the same name creates queries that perform poorly in large Databases.

The Grafana Query Builder and Ad Hoc Filters for InfluxDB Datasources do not explicitly add the "::tag" annotation in the query strings they build from the internal queries of "SHOW TAG NAMES".  As these are known to be Tags, it would be best to annotate them as such in the queries the builders produce.

Background:  In InfluxDB, it is legal (although not recommended) to have Flelds and Tags with the same name.  They are separate parts of data.  The Tags are used as indices to speed up search queries.  When you generate a query from the Builder like:

  SELECT * From "my_data" WHERE time >= 1653868799000ms AND time <= 1653868799000ms AND "thingy" = 'thing1';

The InfluxDB query planner looks at the Shards covering the time rang for any fields or tags named "thingy".  If there is a field in the time range named "thingy", the query plan becomes "thingy"::string = 'thing1' and results in a linear search through all of the data in the Shard looking for a field with that value.  If there are only a tag with named "thingy", the plan becomes "thingy"::tag = 'thing1' and the value lookup is performant for large databases (ours is 300GB and growing).  The problem is if both a field and a tag have the same name for ANY shard in the time range, the query planner emits "thingy"::string = 'thing1' and performance goes down the drain.

We have InfluxDB Enterprise with support and working with their support department, the fix is to use the explicit "::tag" annotations on things you know are Tags.  This works fine in Grafana for Raw Queries but InfluxQL produced by the Query Builder and Ad Hoc Filters have no mechanism to express the annotation.  In looking at the source, I traced the code and see that the values the Query Builder retrieves (for InfluxDB as Datasource) are ALWAYS tags.  As such, we should just add the "::tag" annotation by default (if we add support for querying for fields for the tool, those should have their type).  We have less sophisticated Grafana users who can handle the Ad Hoc filters but would be lost in trying to create a Raw Query, so I want to protect them from this problem.

Note: Per InfluxDB Enterprise Support,  removing the bad data points or Series cannot fix the problem.  Due to the nature of InfluxDB, I have to drop and rebuild this large DB to fix things when users slip in fields like this.

**What you expected to happen**:
To explicitly annotating Tags with "::tag" in queries produced by Ad Hoc Filter and the Query Builder for InfluxDB so that queries are performant on large databases.

**How to reproduce it (as minimally and precisely as possible)**:
Create a huge InfluxDB Enterprise (or OSS 1.8.x) database that spans across a long period of time and a 100 or so shards with TSI indices with Tag "filename".  

Do a SELECT COUNT(*) FROM "measurement" WHERE <time span> AND "filename" = 'my-test-filename.txt'

Do an EXPLAIN ANALYZE SELECT COUNT(*) From "measurement" WHERE <time span> AND "filename" = "my-test-filename.txt" and see how the planner is using "filename"::tag = 'my-test-filename.txt'

Then write a few records to a timestamp in the middle of the time span with a field named "filename".

Repeat SELECT and watch it timeout or take several orders of magnitude longer.

Repeat EXPLAIN ANALYZE and see the Planner is now using "filename"::string = 'my-test-filename.txt'

**Anything else we need to know?**:
I already have a working fix of the above that I'll submit as a PR for this ticket.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: InfluxDB 1.10.0
- OS Grafana is installed on: Alpine Container
- User OS & Browser: macOS 12.6.1, Chrome 108.0.5359.124 (Official Build) (x86_64)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ksquaredkey**
**What is this feature?**

Modifies the Query Builder and Ad Hoc Filters to put the explicit "::tag" annotations that the builder pulls from the InfluxDB Datasource list of tags.  This prevents problems when using Grafana against InfluxDBs where there are Measurements with Tags and Fields with the same name.  Since we know that these query items are Tags, it is safe to put the explicit tag annotation on them.

**Why do we need this feature?**

When an InfluxDB has Tags and Fields with the same Name (not recommended, but legal), the query optimizer flips to a linear search on the field through the entire database unless the query has the "::tag" annotation, telling the DB we are looking for just Tags of the given value.  Keeps from destroying performance.  See Issue #61335 for more details.

**Who is this feature for?**

Folks who want to continue to use the Query Builder and Ad Hoc Filters with InfluxDB when their DB has measurements with tags and fields with the same name.  Keeps them from having to change to Raw Queries.

**Which issue(s) does this PR fix?**:

Fixes #61335 

**Special notes for your reviewer**:

This solution was worked out with recommendations from InfluxDB Enterprise Support.

### CODE REVIEW

**Comment by ksquaredkey** [comment]
Not sure why the second CLAassistant isn't clearing.  I did have to add my new E-mail address to my Github profile to clear the first one.  The second one still won't clear when I hit Recheck but when I hit the link, it says I've already signed the Contributor License Agreement.

**Comment by LudoVio** [comment]
frontend test are failing due to the added `::tag` string

**Comment by gtk-grafana** [comment]
@itsmylife

**Comment by itsmylife** [comment]
@ksquaredkey Thanks for the PR and the nice description. It looks like the enterprise check step is failing. Could you please merge `main` into your branch? It should fix this problem.

**Comment by gtk-grafana** [comment]
@itsmylife enterprise always fails on forks AFAIK, we'll need to manually merge in when all other status are running, or we can create another non-fork PR and run the enterprise tests there.

**Comment by itsmylife** [comment]
> @itsmylife enterprise always fails on forks AFAIK, we'll need to manually merge in when all other status are running, or we can create another non-fork PR and run the enterprise tests there.

I was about to say no that error is different but when I check the error again you are right. I will double-check things and see if everything is ok. And then I will merge.

**Review by itsmylife — APPROVED** [review]

**Comment by gabor** [comment]
hi @ksquaredkey , thanks for the PR, very nice work 👍 . unfortunately, there's a corner case that we will have to handle somehow.

you see, in the `WHERE` section, the autocomplete system only offers `influxdb tags`.
but, the user can just write whatever they want into that text-box, so they can also write `influxdb field` names there, and they can filter by fields.

and if they do that, with this PR it will not work because we add `::tag` to the name of the tag-or-field.

i understand that this seems like something unsupported, but there's some evidence that we support it:
- if you check the list of operators for the WHERE section, it contains `<` and `>` too, and those do not work with influxdb-tags.
- if you use the `>` or `<`operators, we do not put quotes around the "value", so that you can use numeric values there


so this is the problem... i'm not sure how to move forward here, some ideas:
1. we accept this tradeoff, and those who need to do a `WHERE` with field-names, they will have to switch to raw-query-mode.
    - this is technically a backward-incompatible change
2. the user can always enter into the tag-name field something like `thing::tag`, so that should be a possible workaround, BUT currently we quote that, so it does not work. so maybe, when we build the influxql query, we could check if the tag-or-field-name ends with `::tag`,  and only quote the part before it
    - in theory there might be people who use a tag-or-field-name with `::tag` in it 😄 , but they can switch to raw-query-mode probably
3. we could do [2] and additionally, find the place which fetches the tag-names from influxdb, and add `::tag` to the end of them.
    - this would make the ui a little "uglier" with all the `::tag` parts, but maybe that's OK


i'm not sure about which is the best way to go, perhaps some other way even.

**Comment by LudoVio** [comment]
@gabor like the [2] + [3]. For the ugly UI we could only display the name and add the `::tag` only when selected

**Comment by itsmylife** [comment]
@gabor Thanks for the input. That's an important point. So if we ship this and theoretically, if there are some dashboards using fields for filtering would be broken. We can let them know as a breaking change but as @gabor stated it looks like we support fields since the beginning. 

So I think solution proposal #2 is a good thing we can implement. We do not break anything that we already have and we will have additional improvements. For #3, it can be also doable. I think UI won't be that much ugly. But we have to provide a good explanation of why we have those like this way right now.

**Comment by ksquaredkey** [comment]
Aloha @gabor - Thanks for the sanity check!  I am not a front-end person, never touched typescript code before, so it is very plausible I missed that fields were actually supported.  I was looking at the queries where the auto-completion drop-downs to select from are generated, which is what made me think they were all tags.  I like 2 and 3 and, being a guy who knows he is horrible at UX and lets the pros handle that end, 3 sounds beautiful to me! It is explicitly tells me exactly what I am about to do.

I was in the air when this came in and am on the road for the next 2 weeks with work so I won't be able to dig into this until I get back (and dig out from 2 weeks on the road...). If someone who actually knows Typescript can code the changes you are discussing, I'd be very happy to hand off this project to them.  Otherwise, I'll be back to learning enough to just be dangerous...

**Comment by LudoVio** [comment]
I will take care of this by creating a new PR with the UI changes. Thanks for the contribution @ksquaredkey, that is a nice improvement opportunity.

**Comment by LudoVio** [comment]
Created a new PR with changes following @gabor's feedback:
https://github.com/grafana/grafana/pull/62230

Closing this one

**Pull request closed without merging**
