### PR TITLE
Slack Alert: Fix slack notifications

### LINKED ISSUE #42768: Preview of slack notifications in the new alerting is not displayed
**What happened**:
After upgrade to the new alerting system, When an alert is triggering a notification to slack, the preview of the message is "This content can't be displayed".

**What you expected to happen**:
When there is a notifications sent from grafana to slack, I expect to see a preview of the message, maybe the message title.
It's happend on all slack apps including mobile and desktop.

**Anything else we need to know?**:
I think it's maybe related to the blocks message feature of slack. If you use blocks and you don't put a global text field for the message, you are getting that "Content can't be displayed" message.
https://stackoverflow.com/questions/56317962/message-notifications-produce-this-content-cant-be-displayed/56327506

**Environment**:
- Data source type & version:
- ubuntu 18.04
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by jgillick**
**What this PR does / why we need it**:
When a user is mentioned in a slack alert, the push notifications are broken and simply say "This content can't be displayed". This is a [limitation of slack](https://api.slack.com/messaging/composing/layouts#limitations) with a pretty easy workaround. Simply adding a top-level "text" element will allow the push notification to come through as expected.

**Which issue(s) this PR fixes**:
Fixes #42768

### CODE REVIEW

**Review by konrad147 — APPROVED** [review]

**Comment by armandgrillet** [comment]
@jgillick Thank you for this PR! The CI seems to be failing but I don't think this is due to this commit. Can you please rebase and force push your changes?

**Comment by jgillick** [comment]
@armandgrillet I rebased/pushed and it looks like there are still failing tasks. Do you have any recommendations?

**Comment by grobinson-grafana** [comment]
Hi, here are the changes required to make the tests pass!

```
git diff .
diff --git a/pkg/tests/api/alerting/api_notification_channel_test.go b/pkg/tests/api/alerting/api_notification_channel_test.go
index 686de9827a..c36a3da307 100644
--- a/pkg/tests/api/alerting/api_notification_channel_test.go
+++ b/pkg/tests/api/alerting/api_notification_channel_test.go
@@ -2123,6 +2123,7 @@ var expNonEmailNotifications = map[string][]string{
        "slack_recv1/slack_test_without_token": {
                `{
                  "channel": "#test-channel",
+                 "text": "Integration Test [FIRING:1] SlackAlert1 ",
                  "username": "Integration Test",
                  "icon_emoji": "🚀",
                  "icon_url": "https://awesomeemoji.com/rocket",
@@ -2152,6 +2153,7 @@ var expNonEmailNotifications = map[string][]string{
        "slack_recvX/slack_testX": {
                `{
                  "channel": "#test-channel",
+                 "text": "[FIRING:1] SlackAlert2 ",
                  "username": "Integration Test",
                  "attachments": [
                        {
```

**Comment by armandgrillet** [comment]
@grobinson-grafana figured it out, something is missing in the tests now:
```
git diff .
diff --git a/pkg/tests/api/alerting/api_notification_channel_test.go b/pkg/tests/api/alerting/api_notification_channel_test.go
index 686de9827a..c36a3da307 100644
--- a/pkg/tests/api/alerting/api_notification_channel_test.go
+++ b/pkg/tests/api/alerting/api_notification_channel_test.go
@@ -2123,6 +2123,7 @@ var expNonEmailNotifications = map[string][]string{
        "slack_recv1/slack_test_without_token": {
                `{
                  "channel": "#test-channel",
+                 "text": "Integration Test [FIRING:1] SlackAlert1 ",
                  "username": "Integration Test",
                  "icon_emoji": "🚀",
                  "icon_url": "https://awesomeemoji.com/rocket",
@@ -2152,6 +2153,7 @@ var expNonEmailNotifications = map[string][]string{
        "slack_recvX/slack_testX": {
                `{
                  "channel": "#test-channel",
+                 "text": "[FIRING:1] SlackAlert2 ",
                  "username": "Integration Test",
                  "attachments": [
                        {
```

This makes me wonder if this PR is gonna be adding a regression for users having notifications not containing text 🤔.

**Comment by jgillick** [comment]
@grobinson-grafana Thanks for the diff. I've made the update.

@armandgrillet I don't believe so because the `Text` slack property isn't defined by the user.

**Comment by jgillick** [comment]
Looks like the e2e tests are having trouble installing Cypress?
> The cypress npm package is installed, but the Cypress binary is missing.

This wouldn't be related to the changes in this PR, would it? I have not been able to run the e2e tests on my M1 MacBook, so I cannot verify it locally. (it requires bash 4+, which isn't rosetta compatible and the upgrade breaks other things in my primary development environments)

**Comment by jgillick** [comment]
@armandgrillet Any idea why the tests are failing due to cypress install? Could it just be a hiccup and need to be run again?

```
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /root/.cache/Cypress/9.5.1/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
```

**Comment by jgillick** [comment]
@konrad147, @armandgrillet  Can this PR be reopened and merged? I believe the last thing it was waiting on was final approval.

**Pull request closed without merging**
