### PR TITLE
SideMenu: Remove live section from main side menu

### PR DESCRIPTION
**Pull request by torkelo**
This if true statement looks like it was a test that was accidentally merged to main (and hence added to main sidemenu).

Should these new pages be behind a feature toggle and under configuration or server admin section?

image (7)

### CODE REVIEW

**Comment by FZambia** [comment]
Definitely should be under `live-pipeline` feature toggle.

**Comment by torkelo** [comment]
@FZambia can you update this PR super quick, think beta1 branch of is very soon!

**Comment by FZambia** [comment]
I think we can merge with your changes. We will just put this back separately.

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Pull request merged**
