### PR TITLE
chore: remove executable permissions of source files and docs

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
**What this PR does / why we need it**:

Removes executable permissions of some source files and docs.

**Which issue(s) this PR fixes**:

Some source files and docs have the unix executable bit set, however these files are not intended to be executed directly (and don't have a shebang).

**Special notes for your reviewer**:

No functional change otherwise.

### CODE REVIEW

**Comment by andreasgerstmayr** [comment]
ping for review

**Review by leventebalogh — APPROVED** [review]
Thanks a lot for the contribution @andreasgerstmayr! 👏 

I am not sure why some of those files permissions have changed (e.g. [here](https://github.com/grafana/grafana/pull/29250/files#diff-65862696b913d4fc89d7ba62cdf603a251ce3e5764c7c9cec5fa3b64e9e6b609)) or why they were created with `0755`, I guess it was accidental.

Thanks a lot for finding and fixing them 👍  

Will look into why some of the CI steps are failing and come back.

**Comment by andreasgerstmayr** [comment]
> Thanks a lot for the contribution @andreasgerstmayr! clap

You're welcome!
 
> I am not sure why some of those files permissions have changed (e.g. [here](https://github.com/grafana/grafana/pull/29250/files#diff-65862696b913d4fc89d7ba62cdf603a251ce3e5764c7c9cec5fa3b64e9e6b609)) or why they were created with `0755`, I guess it was accidental.

I didn't use Windows for a long time, but if I remember correctly newly created files used to have 0755 permissions by default when added to Git. Same when using e.g. FAT32 on OS X - i.e. for all filesystems which don't store the executable permission bit.
There is a `core.fileMode` git setting to influence this (https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode).

**Comment by leventebalogh** [comment]
@andreasgerstmayr yea, that can be a reason why these file changes are happening every now and again!

I have a feeling that the builds are failing because the branch is not up-to-date with the latest main - could you please update the branch? (Either by merging main or rebasing.) Thanks!

**Comment by leventebalogh** [comment]
Thanks @andreasgerstmayr! 🙏

**Comment by andreasgerstmayr** [comment]
Thanks for merging! :)

**Pull request merged**
