### PR TITLE
Chore: Upgrade Docker images to Go 1.13.1

### LINKED ISSUE #18878: Upgrade go to 1.13.1
Go 1.13 have been released: https://golang.org/doc/go1.13

- [x] Fix so go 1.13.1 can be used to build Grafana
- [x] Update CircleCI/build scripts to use go 1.13.1

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Upgrade Docker images to Go 1.13.1.

**Which issue(s) this PR fixes**:
Fixes #18878.

### CODE REVIEW

**Review by marcusolsson — APPROVED** [review]

**Review by marefr — CHANGES_REQUESTED** [review]
Guess you already know, but need to build and publish 1.2.10 of grafana/build-container. Lets have a look at that tomorrow.

**Comment by aknuds1** [comment]
> Guess you already know, but need to build and publish 1.2.10 of grafana/build-container. Lets have a look at that tomorrow.

Yes, I need your advice on how to do this :)

**Comment by marefr** [comment]
You've already updated the version in build-deploy.sh in this PR (https://github.com/grafana/grafana/pull/19576/files#diff-82d853c1d9b59609fa12d3e70738b5ffR3) so you'll need to run it to build and deploy version 1.2.10 to docker hub. The build will take quite some time. You should have access to push to docker hub based on what I can see. 

Let me know if you have any questions.

**Comment by aknuds1** [comment]
@marefr It's fixed now - I had to upgrade golangci-lint to the master revision, that seems to take care of the memory issues.

**Review by marefr — APPROVED** [review]
Great :+1:

**Pull request merged**
