### PR TITLE
Bump npm packages related to the dev process

### LINKED ISSUE #15935: Bump Webpack and Jest versions

### PR DESCRIPTION
**Pull request by jschill**
**What this PR does / why we need it**:
Upgrades NPM packages related to `yarn start`, `yarn start:hot`, `yarn build`, `yarn jest` except for the ones related to angular and enzyme. 

When developing in `yarn start`-mode the incremental build-times (including type checking) went from 10s to 4.5s.

Updating the jest packages did not improve the performance.

**Which issue(s) this PR fixes**:
Fixes #15935

**Special notes for your reviewer**:
- Please test `yarn start` incremental build times in master and then in this branch to make sure this one performs better.
- Make sure `yarn start:hot` works as expected. 
- Cache for Terser (ex-Uglify) is turned OFF now in prod build. 
- Don't forget to squash when/if merged 👍 

**Release note**:
NONE

### CODE REVIEW

**Comment by peterholmberg** [comment]
Tested this but results showed none or very slight performance improvements. But I think we should find a more objective way of testing this and collecting metrics. Can this be included in the build step perhaps?

**Comment by jschill** [comment]
@peterholmberg Did you try with `watch` or `watch:hot`?

The biggest speed increase for me was updating the `fork-ts-checker-webpack-plugin` package and that is not used when running `watch:hot`.

Great idea to include this in the build process. There were some discussions about adding more build metrics to our dashboards and this should definately be included.

**Comment by jschill** [comment]
Background for the interested. The latest version of `fork-ts-checker-webpack-plugin` is using typescript's new incremental watcher which is much faster than before (More info: https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/v1.0.0).

Skipping the `fork-ts-checker-webpack-plugin`-package completely and use typescripts own typechecking saves me ~2 more seconds. But I dont want to scope-creep this issue.

**Comment by peterholmberg** [comment]
I did `yarn start` and `yarn start:hot`. Typescript checking is faster on the `bump-webpack` branch. 

This is my results

```
Master

yarn start:
compile time: 3190ms
ts: 8517

yarn start:hot:
compile time: 2954
ts: 14437
```

```
bump-weback

yarn start: 
compile time: 3181
ts: 8329

yarn start:hot:
compile time: 3079
ts: 8686
```

**Comment by torkelo** [comment]
I added one for test frontend step yesterday, open ci code stats dashboard, see last panel

**Comment by peterholmberg** [comment]
on play site?

**Comment by jschill** [comment]
Uh those numbers are not as funny to read as mine. Oh well at least they're not worse.

**Comment by dprokop** [comment]
**master**
  yarn start
    wp: 3238ms
    ts: 9080ms

  yarn start:hot
    wp: 4523ms
    ts: 8803ms

**bump-webpack**
  yarn start 
    wp: 2248ms
    ts: 2680ms

  yarn start:hot:
    wp: 4837ms
    ts: 4348ms

**Comment by jschill** [comment]
Think this should be tested and merged asap since its not that funny to solve conflicts in the lock files.

**Review by dprokop — COMMENTED** [review]
Deps bump is a good thing 👍

**Review by dprokop — APPROVED** [review]

**Comment by torkelo** [comment]
Need to merge this :) just has some conflicts

**Comment by jschill** [comment]
Lockfile conflicts are such a mess. It ended up I regenerated a new file.

**Pull request merged**
