### PR TITLE
Docs: Fix data source (jaeger, zipkin, tempo) provisioning yaml TracesToLog query example

### LINKED ISSUE #86604: Doc/Tempo/Data source provisioning: bad "traces to logs" configuration
### What happened?

The actual documentation mentioned an example of a tempo datasource provioning using tracestologs which is quite good but the given "custom query" does not work: https://github.com/grafana/grafana/blob/ec1af89a024f283469d498e08707893264ca97c7/docs/sources/datasources/tempo/configure-tempo-data-source.md?plain=1#L241

image

The dollar sign should be escaped like: `method="$${__span.tags.method}"`

### What did you expect to happen?

After fixing the configuration, the variable is well integrated:

image

### Did this work before?

Yes

### How do we reproduce it?

1. Create a tempo datasource by copy pasting the one from the doc (https://github.com/grafana/grafana/blob/ec1af89a024f283469d498e08707893264ca97c7/docs/sources/datasources/tempo/configure-tempo-data-source.md?plain=1#L241
)
2. Edit the configuration and check that the variable is available
3.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.4.1

### Grafana platform?

None

### Datasource(s)?

tempo

### PR DESCRIPTION
**Pull request by cboudereau**
Fixes #86604

### CODE REVIEW

**Comment by cboudereau** [comment]
Hi @jdbaldry it seems I have an issue with the Changelog Check but I don't know what to change ?

**Comment by kminehart** [comment]
The Changelog is generated from pull request titles and contents; to add this pull request to the changelog, we just need to add the "Add to changelog" label on the pull request. I've added the "Add to changelog" label; I would remove the changes in CHANGELOG.md as they will be automatically generated in the next release.

**Comment by cboudereau** [comment]
Thank you @kminehart. I just removed the changelog commit 👍

**Comment by jdbaldry** [comment]
FYI @knylander-grafana

**Review by jdbaldry — APPROVED** [review]
Thank you for your contribution!

We don't typically add documentation updates to the CHANGELOG so I've updated the PR labelling to reflect this.

I've notified the Tempo writer to double check but having read the issue. I believe this is the correct fix.

**Pull request merged**
