### PR TITLE
Prometheus: Show executed query in inspector

### PR DESCRIPTION
**Pull request by torkelo**
This changes so the prometheus (and loki) backends set the meta property ExecutedQueryString so that it's easy from the frontend to see what the query was evaluated to.

* Makes it easy to see what $__rate_interval or $__interval was evaluated to 
* Also appends Step to the ExecutedQueryString so we can view this from the frontend 

Screenshot from 2022-02-14 08-23-30

### CODE REVIEW

**Review by gabor — CHANGES_REQUESTED** [review]
nice :) 

one problem is that the loki dataframe-snapshots currently say:
```
"executedQueryString": "Expr: \nStep: 0s"
```

i'd recommend adjusting this line: 
https://github.com/grafana/grafana/blob/main/pkg/tsdb/loki/framing_test.go#L44

the `lokiQuery{}` part to something like `lokiQuery{{Expr: "up(ALERTS)", Step: time.Second * 42}`

and regenerating the test-snapshots, to make them nicer.

**Comment by gabor** [comment]
question is whether we should embrace these multi-line query-descriptions, and just put all the data into it.. for example, for example, the start & end timestamp.

(this can be useful for Prometheus, because there we adjust the start&end timestamp to be better aligned, so that could get easier to debug... though we should probably format the timestamps into a readable-and-utc format..)

**Comment by torkelo** [comment]
@gabor yea, I was thinking the same thing, to include start & end time

**Comment by gabor** [comment]
just to share more context here, there are two somewhat-related feature-requests (we don't have to do any of them here, of course.. we aren't even sure if these are the best ways to solve the problems):

1. add a "copy as CURL" functionality there (like it's done in browsers' dev-tools).. the idea is that if the user needs to investigate something deeper, they get an easy way to get a CURL url.
2. add a way to show somehow the "raw" prometheus/loki output in the query-inspector... this is useful for debugging, and also when we get bug-reports, with backend-components it's hard to find out what data the user receives from the database.

**Comment by torkelo** [comment]
@gabor yea, showing raw request / response would be useful

**Review by gabor — COMMENTED** [review]
Loki changes are OK 👍 

(i did not approve the PR because someone should check the Prometheus part too)

**Comment by torkelo** [comment]
@gabor since you requested changes I think you have to

**Review by gabor — APPROVED** [review]
Loki changes are good! (someone should review the prometheus changes too)

**Review by aocenas — APPROVED** [review]
Looks good to me definitely a nice thing to have for debugging. Two semi-related things for the future:
- Is there a way to not have the test data as base64 arrow structure? It makes these diffs just hard to review.
- Wonder if it wouldn't make sense to change `executedQueryString` to something else, like executionMetaData, and have key-value pairs there. I think having some other params could be useful for other datasources too as not everything just goes into a single string query (like params in the API call etc).

**Comment by gabor** [comment]
@aocenas wrote:

> * Is there a way to not have the test data as base64 arrow structure? It makes these diffs just hard to review.

i'd love that too..... well, at least one can know that the things that are represented textually too ( datframe-columns/values), those did not change.

**Pull request merged**
