### PR TITLE
build/vendor: vendor deps for scripts mod, GOFLAGS=mod=-vendor in Makefile 

### PR DESCRIPTION
**Pull request by kylebrandt**
prevent go.mod/go.sum in scripts from updating. 

Should probably keep as two commits (rebase and merge) because of vendor.

### CODE REVIEW

**Comment by marefr** [comment]
Is the only alternative to vendor it? Adds a loooot of vendored files :smile:

**Comment by kylebrandt** [comment]
Need to figure out gosec problem. Also exclude vendor folder from spell checking.

**Comment by kylebrandt** [comment]
> Is the only alternative to vendor it? Adds a loooot of vendored files

No, we could lock the versions of things with `require` and not using vendoring for this.

**Comment by marefr** [comment]
@kylebrandt can we lock the versions then using `require` or what stopping us/are the cons?

**Comment by kylebrandt** [comment]
> @kylebrandt can we lock the versions then using `require` or what stopping us/are the cons?

With `require` version locking things will get stuck at old versions when we would probably be fine with an upgrade most of the time (vs time spent in discovery that is just already solved issue in the dep)

**Comment by marefr** [comment]
> With require version locking things will get stuck at old versions when we would probably be fine with an upgrade most of the time

@kylebrandt I thought the whole point of this PR was to lock the version to not automatically update and show up as git changes in go.mod/go.sum? Sorry for being stupid and don't understand :smile:

**Comment by kylebrandt** [comment]
> > With require version locking things will get stuck at old versions when we would probably be fine with an upgrade most of the time
> 
> @kylebrandt I thought the whole point of this PR was to lock the version to not automatically update and show up as git changes in go.mod/go.sum? Sorry for being stupid and don't understand

Given this is the case of vendoring:
 1. It won't update the mod/sum during normal running (because of mod vendor)
 2. It will still update things when we run `go mod vendor`, whereas if we had something specified in `replace` it would not. (Note, above when we said `require` should have said `replace` (irony alert)

**Comment by kylebrandt** [comment]
closing for now, don't want to add this many files to the repo just for tools

**Pull request closed without merging**
