### PR TITLE
Actions: Improve drag and drop experience

### LINKED ISSUE #92337: Actions: Improve drag and drop experience
Improve the drag and drop experience by improving the styling when an action is dragged/dropped.

https://github.com/user-attachments/assets/600a7b8a-ba9d-4997-a8ee-31eeaaef7abb

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This PR fixes datalinks drag-n-drop jumping behaviour.

Before:

https://github.com/user-attachments/assets/600a7b8a-ba9d-4997-a8ee-31eeaaef7abb

After:

https://github.com/user-attachments/assets/5f002fa8-e85e-4ad7-93e7-157a023a9279

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/92337

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by drew08t** [comment]
Cool! Can you please include both before and after captures?

**Comment by Develer** [comment]
Small description what was done in this PR.

The main jumping problem was fixed by moving <Draggable /> component up a level by removing an unnecessary wrapper, which allows it to operate as expected.

For the on-click border placeholder, I implemented a somewhat hacky solution: I made the placeholder a separate element that sticks to the top.

A couple of things to note:

	1.	I’m not a fan of using fixed pixel values.
	2.	I generally avoid using the absolute positioning property.

That said, everything is working smoothly so far. Let me know your thoughts!

cc @adela-almasan @drew08t

**Comment by adela-almasan** [comment]
@Develer good job on this one, it's working really smooth! 🎉 

The only think I've notice is that the one-click doesn't account for the [compact url](https://github.com/grafana/grafana/blob/268ef69022c4e3dcd94d952dbf0d9359234ea673/packages/grafana-ui/src/components/DataLinks/DataLinksInlineEditor/DataLinksListItem.tsx#L30) errors anymore. I think this should be good to go once the issue is fixed.

https://github.com/user-attachments/assets/7a51d88e-17e1-4031-8b5d-4b5518029ca4

**Comment by Develer** [comment]
> @Develer good job on this one, it's working really smooth! 🎉
> 
> The only think I've notice is that the one-click doesn't account for the [compact url](https://github.com/grafana/grafana/blob/268ef69022c4e3dcd94d952dbf0d9359234ea673/packages/grafana-ui/src/components/DataLinks/DataLinksInlineEditor/DataLinksListItem.tsx#L30) errors anymore. I think this should be good to go once the issue is fixed.
> 
>  Screen.Recording.2024-08-24.at.2.09.53.PM.mov

Oh, I see, this happened because one-click border block has a fixed height. Yeah, probably it's not the best solution, let me think about it.

**Review by baldm0mma — APPROVED** [review]

**Pull request closed without merging**
