### PR TITLE
Grafana supports Millisecond resolution for Opentsdb

### PR DESCRIPTION
**Pull request by utkarshcmu**
Millisecond resolution compatibility with Opentsdb completed. But tooltip breaking when hovered over the graph. Will fix it asap. 

Implementing #2865

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Ready for review/merge.

**Comment by utkarshcmu** [comment]
@torkelo : Chances of getting this PR merged sometime soon?

**Comment by CamJN** [comment]
Well, there are merge conflicts now. Might want to address those first.

**Comment by utkarshcmu** [comment]
@bergquist Do you think this PR can be merged once the conflicts are resolved, so that Grafana will be able to support millisecond resolution queries for Opentsdb?

**Comment by torkelo** [comment]
not sure about this PR, seems a bit invasive, and not many who have requested it

**Comment by utkarshcmu** [comment]
Closing this PR then.

**Comment by utkarshcmu** [comment]
Reopening this PR as #2865 is still open. We can close this PR if we are closing #2865.

**Comment by utkarshcmu** [comment]
@tomcfoglio @CamJN If you think this PR can be helpful, please +1 to this. Thanks :)

**Comment by CamJN** [comment]
def +1 👍🏻

**Comment by tomcfoglio** [comment]
+1

**Comment by utkarshcmu** [comment]
@torkelo / @bergquist What changes should I make in this PR so that it can make into Grafana. This will increase support for Opentsdb users. Please review and let me know what changes need to be made to make the code more reliable. Thanks.

**Comment by torkelo** [comment]
not sure, just dont like the added complexity of checking of the datasource is in "millisecond" mode in places like the tooltip etc.

**Comment by sslupsky** [comment]
+1

**Comment by utkarshcmu** [comment]
@torkelo Then I guess we need to create a new tooltip object for Opentsdb millisecond mode, if we do not want it to interfere with Grafana core.

**Comment by utkarshcmu** [comment]
Closing this in favor of #4074

**Comment by utkarshcmu** [comment]
Hopefully #4227 gets reviewed/merged into master before 3.0.0 and Opentsdb metrics can be plotted with millisecond resolution. :)

**Comment by digrich** [comment]
It's great to see the data of millisecond resolution but it's really missing the resolution of time. It would be ideal and complete solution to show the millisecond time in x-axis and tooltip. In table panel, it becomes very obvious to see the same time for multiple data points. 

Would be great if grafana natively supports the time resolution at the millisecond level. 

As grafana is getting more and more popular we have started using it for the display/monitoring of business data, i.e. FX prices, which changes every few milliseconds.

**Comment by digrich** [comment]
Table panel looks fine and shows the time in milliseconds after changing the date format in Column Style to YYYY-MM-DD HH:mm:ss,SSS

**Pull request closed without merging**
