### PR TITLE
Increment Grafana version

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Increment Grafana's version.

### CODE REVIEW

**Review by xlson — CHANGES_REQUESTED** [review]
I think we might want to change this to 7.0.0-pre rather than 6.8.0-pre. @torkelo?

**Comment by ryantxu** [comment]
is it 6.8?  I think it is 7.0-dev

**Comment by aknuds1** [comment]
Also unsure about that @xlson @ryantxu.

**Comment by xlson** [comment]
I'd set 7.0.0-pre

**Review by xlson — APPROVED** [review]

**Pull request merged**
