### PR TITLE
Core: Add loki/logproto dependency

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

Add `github.com/grafana/loki/pkg/logproto` package to push logs to the Loki HTTP API (used in auditing extension).

**Special notes for your reviewer**:
- Note that a new `replace` statement has been added [inherited from Loki](https://github.com/grafana/loki/blob/master/go.mod#L72).
- Since some shared dependencies has been updated, I also updated the `logWrapper` implementation to keep it compatible with the latest version of the `hclog.Logger` interface.

### CODE REVIEW

**Comment by xlson** [comment]
I agree, lets remove the catch and test since that bug has been fixed.

**Review by xlson — APPROVED** [review]
Looks good to me, but I'd like to see a review from @marefr or someone else on the backend squad since this touches logging for the backend plugins.

**Comment by joanlopez** [comment]
Pipeline fixed by applying the discussed changes.

Thanks!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
