### PR TITLE
Dashboard: Hide time picker option will hide only time range picker

### LINKED ISSUE #11782: "Hide time picker" also hides refresh button
### What Grafana version are you using?
v5.1.0

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
CentOS 7

### What did you do?
Tried to hide the time picker

### What was the expected result?
The users shouldn't be able to select a time range because that dashboard only uses panels with time overwrite and shows the current value. Refreshing makes sense because the current data changes by definition.

### What happened instead?
The refresh button is also hidden

### Use case
Having a dashboard showing the current status, maybe an average over the last hour.

### LINKED ISSUE #83691: Dashboards: Refresh button is hidden when time picker is hidden
### What happened?

When hiding time picker from dashboard the refresh button also gets hidden

### What did you expect to happen?

Hiding both time range picker and refresh button with hide time picker is bit miss leading.
That refresh button sometimes is required, when dashboard does not need a time picker we hide it, but then the refresh button will disappear and to reload a new set of data we need to refresh the whole dashboard page... Also the auto refresh dropdown will go away and we will not be able to set the refresh interval in that case.

### Did this work before?

I was since my first use of grafana ~ v4.x

### How do we reproduce it?

1. Create dashboard
2. Hide time picker from dashboard general settings
3. Go back to dashboard

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: <= 11.x
OS: Any
Browser: Any

### Grafana platform?

Kubernetes

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by Bujupah**
**What is this feature?**
On dashboard hide time picker, only time range picker will be hidden
image

**Why do we need this feature?**
Hiding both time range picker and refresh button with hide time picker is bit miss leading. 
That refresh button sometimes is required, when dashboard does not need a time picker we hide it, but then the refresh button will disappear and to reload a new set of data we need to refresh the whole dashboard page... Also the auto refresh dropdown will go away and we will not be able to set the refresh interval in that case.

**Who is this feature for?**
Grafana enthusiasts and users

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/11782

**Special notes for your reviewer:**
👋

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Bujupah** [comment]
That is a suggestion, Not quite sure if that's the best right way in term of UX. 
If we should keep that refresh button eternally or add a new separate option in dashboard general option like `Hide refresh button`

**Review by dprokop — CHANGES_REQUESTED** [review]
I think this change does make sense, thank you for your contirbution. Could you please apply this change also to https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/scene/DashboardControls.tsx#L40 which is used in the new, scenes base architecture?

Looping in @thanos-karachalios and @Ijin08 for thoughts and approval or rejection :)

**Comment by Bujupah** [comment]
Are we going with this by any chance? @dprokop

**Review by dprokop — APPROVED** [review]

**Review by axelavargas — COMMENTED** [review]
Hey @Bujupah 👋🏾 , thank you for helping with this one 🥇 .  To move forward, we need a couple of things:

- Fix the CI --  Our CI is failing to pass in the linting step:

> + yarn run prettier:check
> [warn] public/app/features/dashboard-scene/scene/DashboardControls.tsx
> [warn] public/app/features/dashboard/components/DashNav/DashNavTimeControls.tsx
> [warn] Code style issues found in 2 files. Run Prettier to fix.

This might happen because the prettier formatting is not properly configured and you don't have the pre-commit hooks :)
[main/contribute/developer-guide.md#configure-precommit-hooks](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md?rgh-link-date=2024-05-14T09%3A40%3A50Z#configure-precommit-hooks)

- Add unit test 😄 ---  For `DashNavTimeControls.test.tsx`, we just need to add an extra test case, and for `DashboardControls` we need to create a unit test, you can take a look at other tests, but if you get blocked, let us know, we will help :)

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Comment by Bujupah** [comment]
@diegommm, @dprokop over to you to review again.

**Comment by axelavargas** [comment]
Hey @Bujupah 👋🏾 , thank you for creating the test. Unfortunately, there are still CI failures 🤔 , did you run `yarn run prettier:check`?  I suggest you merge with the latest `main` branch and run prettier.

**Review by ivanortegaalba — CHANGES_REQUESTED** [review]
Hi @Bujupah, thank you so much for your contribution.

We merged this https://github.com/grafana/grafana/pull/88920 that affects this PR. It implements options to set the visibility of dashboard controls for playlists. The options groups time picker with refresh picker. If we merge this PR we won't be able to hide refresh picker from Kiosk mode. This will be a problem for TVs that are displaying dashboards without controls.

So, in order to merge this PR, first we need to close this issue https://github.com/grafana/grafana/issues/89469

This PR is part of that work, but we need to implement the options in Dashboards settings and playlist start modal too.

So, I'm marking this PR as "Request changes" to not merge it, and break Kiosk mode. This PR can be merged when the PR for playlist controls and settings are ready

**Pull request closed without merging**
