### PR TITLE
Plugins: GraphPanel: Add an option to toggle single series with normal click

### LINKED ISSUE #17697: Enable toggling single series on mobile
**What would you like to be added**:
Simple On / Off option to toggle a series in a graph on a mobile phone.
I think a simple "strikethrough" like view would make more sense then this CTRL+MouseButton configuration which is not really intuitive.

**Why is this needed**:
On a PC i'm able to select a series with CTLR + MouseButton but i don't have this option on a mobile device. I have a graph with 3 series and can only show one or all of them on a mobile device like a phone or a tablet.

### PR DESCRIPTION
**Pull request by ghost**
Plugins:
GraphPanel: Add an option to toggle single series with normal click without ctrl or shift.
Fixes #17697

### CODE REVIEW

**Comment by torkelo** [comment]
Hi, Thanks for contributing! 

https://github.com/grafana/grafana/issues/17697 is not seeing a lot of demand, and adding an edge case UI option for this is not yet warranted. Sorry for closing this, we have to be careful not to add to many options in the UI for every possible edge case/user wish.

**Comment by BenProb** [comment]
Hi @torkelo,
whats is your preferred solution to allow single click toggle of series?
Would you like a url-parameter or a global parameter to set the toggle option?
Every user I have seen doesn't understand the current toggle logic.
Thanks for your answer, Ben

**Comment by torkelo** [comment]
No matter what we have as default (one click to isolate series, or just hide it) it going to be confusing depending on what you want / expect to happen on single click. 

The way it works now seems to most intuitive as it behaves the same as file lists on windows, mac, linux etc (single click single selects, CMD+click multi selects) 

> whats is your preferred solution to allow single click toggle of series?

Unless we have a big demand to change the default behavior we see no reason to have an option

**Comment by BenProb** [comment]
> Unless we have a big demand to change the default behavior we see no reason to have an option
@torkelo Have you seen that I moved our discussion into the ticket. Have you the time to give me an answer there?

**Pull request closed without merging**
