### PR TITLE
Lazy loading OMG (from scrollTop)

### PR DESCRIPTION
**Pull request by ryantxu**
yet-another-lazy-loading-pull-request!

Following @torkelo idea on #15272, this does not use an intersection observer, but (approximately) calculates visibility from the existing scroll events in DashboardGrid.tsx

This seems to work well!

Open questions:
- Is there a better way to get the height?  
- Is the visibility calculation accurate enough?  missing GRID_CELL_VMARGIN may be an issue for very large dashboards

See also: #7452 #5216 #8365 #8500 #12200 #14731

### CODE REVIEW

**Comment by simPod** [comment]
Looking forward to try it! But I still think it should be configurable per dashboard as [I explained here](https://github.com/grafana/grafana/pull/14731#issuecomment-451441245)

**Comment by ryantxu** [comment]
> But I still think it should be configurable per dashboard as [I explained here](https://github.com/grafana/grafana/pull/14731#issuecomment-451441245)

Give it a try and then let me know what you think 😁  As written, only the panels that are *not visible* are lazy loaded.  Panels that are visible are loaded immediately.

I have been through many many many versions of this, and finally feel like it performs well enough that you hardly notice.  This makes a HUGE difference on large dashboards

**Comment by torkelo** [comment]
I would love to have time to test and play with this, but so much stuff to do (v6 bug fixes) and GrafanaCon talk & workshop prep. 

One thing I am worried about with this approach is that it triggers react re-renders of the dashboard grid for every refresh tick. But maybe no way around that.

**Comment by ryantxu** [comment]
>  but so much stuff to do...

No worries -- totally understand.  I have kept this alive for a while so it is nice to see a light at the end of the tunnel :)

> riggers react re-renders of the dashboard grid for every refresh tick

I assume you mean "change in scrollTop" not "refresh tick".  Good point!  I just changed the patch to change the scrollTop every 25 pixels.  (The match is currently buffering by 50px so this should be fine)
```
const approximateScrollTop = Math.round(scrollTop / 25) * 25;
```
This approach was super important in previous versions, but it seems fast enough even without it

**Comment by buroa** [comment]
I'm going to give this a shot... give me a few to test it out.

**Comment by simPod** [comment]
Same here, wrapping some of my WIP so I can rebase my grafana fork onto this.

**Comment by buroa** [comment]
https://github.com/buroa/grafana/tree/15310 build with latest master. I do not see any logs of lazy loading and my "big" dashboards do not seem to be lazy loading at all.

**Comment by simPod** [comment]
Same here, doesn't seem it lazy loads 
image

**Comment by ryantxu** [comment]
I just merged with master and tested again... it seems to work fine for me so I'm not sure what is going on.  To be clear the potential match is aggressive -- many false positives since it overestimates the container size and buffers by 100px.  You would only see lazy loading if you have a dashboard with many graphs that are not visible.  

With this dashboard: https://gist.github.com/ryantxu/a832f416c59f02127dca82cdcdd1b7a7

I see new items pop up in the console as you scroll down:
image

**Comment by ryantxu** [comment]
ugg -- looks like some prettier change touches everything so this has 60 files :(

**Comment by torkelo** [comment]
Strange, we upgraded prettier yesterday, make sure you run yarn install. But it should only run on staged files so not sure why it modified other files. Can you do a soft revert if last commit and yarn install and try commit again?

**Comment by ryantxu** [comment]
I tried fixing the branch, but have given up and must made a new PR: #15554 

@torkelo, i think my problem was caused by:
```
git fetch grafana  
git merge grafana/master
```
This had conflicts that had to be manually changed.  I fixed the conflicts and ran commit again.  This triggered prettier in the pre-commit hook on all the files that were in the merge :(

**Pull request closed without merging**
