### PR TITLE
Alerting: Exclude expression refIDs from NoData state

### LINKED ISSUE #71993: Alerting: No data alerts fires two instance for one rule for classic condition, due to labelling issue.
### What happened?

Classic condition rule with expression set as alert criteria, sets labels for dashboard_uid and ref_id ,  which instantiate multiple instance for same rule. 

When we hit NO DATA state , (nodata=nodata),  we receive notification that two instance have hit nodata state, instead of the one (for the one rule) 

issue appears to be caused by this labelling issue https://github.com/grafana/grafana/issues/71467 

discussed https://raintank-corp.slack.com/archives/C01LJ5F8NRX/p1689722105737669  and raising issue as requested. 

Classic condition:
image
two instances with unique ref_id and datasource_uid:
image
multiple notification:
image

### What did you expect to happen?

When hitting nodata state for single rule, we should only get notified of one instance of state. 

### Did this work before?

-

### How do we reproduce it?

1.write classic condition, set alert criteria to an expression; set nodata=nodata or error=error
2.hit nodata or error state ,  observe rule dimensions and unique labelling
3.check notifications and see duplicates. 

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
Fixes alerting evaluator to not include expression RefID to NoData result

**Why do we need this feature?**
This removes an extra state that mentions refID of expressions when no data result is executed as NoData state.

<details><summary>Example</summary>

firefox_kUGehpZzsH

</details>

**Who is this feature for?**
Those who configure execution of NoData as NoData.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/71993

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
Were you able to figure out how this broke in the first place?

**Comment by yuri-tceretian** [comment]
I did not try to. Perhaps one of the PRs where we improved NoData handling of server-side expressions. I can track it down if you think it is important.

**Comment by JacobsonMT** [comment]
Perhaps the change should be [here](https://github.com/grafana/grafana/pull/72219/files#diff-51dba59230dace49838d6ba40c323aafa6c76d3c119c5ceae36f3bdae4b913ddL350) instead with something like

```go
if s, ok := datasourceUIDsForRefIDs[refID]; ok && !expr.IsDataSource(s) {
```

Likely a casualty of the `-100` -> `__expr__` change, WDYT?

**Comment by yuri-tceretian** [comment]
`expr.IsDatasource` does not include the ML expression. The approach I chose was supposed to replace this function (see PR https://github.com/grafana/grafana/pull/70106) but then Kyle and I decided to keep it. See [comment](https://github.com/grafana/grafana/pull/70106#discussion_r1230848564). Also, this function is used in other places of the alerting `eval` https://github.com/grafana/grafana/blob/8dd3eb856de497b53b6065c533a181908286b6f1/pkg/services/ngalert/eval/eval.go#L648-L663

**Review by JacobsonMT — APPROVED** [review]
LGTM

**Review by grobinson-grafana — APPROVED** [review]
LGTM!

**Pull request merged**
