### PR TITLE
feat(ErrorPage.tsx, _errorpage.scss): New ui for error page

### PR DESCRIPTION
**Pull request by thealpha93**
New ui for error page
Remove the navModel and header
Disconnect store from the page

### CODE REVIEW

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
@thealpha93 thank you for contributing, I'm not sure this is something we're going to take in as is without a proper explanation and reason for this change.

**Comment by thealpha93** [comment]
> @thealpha93 thank you for contributing, I'm not sure this is something we're going to take in as is without a proper explanation and reason for this change.

it was a mistake I meant to merge to my forked repo's master branch. Lol... But since we're here, it's up to you to make the decision.

**Comment by thealpha93** [comment]
@hugohaggmark 
image
This is how the error page looks now

**Comment by hugohaggmark** [comment]
@torkelo is this something we're interested in, re-designing the error page?

**Comment by torkelo** [comment]
Not really, think i prefer our current one

**Comment by hugohaggmark** [comment]
Closing this PR because this is not something we're going to consider.

**Pull request closed without merging**
