### PR TITLE
WIP: Panel Inspector: minor cleanup and show error

### PR DESCRIPTION
**Pull request by ryantxu**
This is a minor chance to the (alpha) inspector so that it:

* shows any errors more clearly (not just in JSON)
* removes the "Issue" tab

### CODE REVIEW

**Comment by peterholmberg** [comment]
I have also started on the show error tab in this branch https://github.com/grafana/grafana/tree/add-error-panel-inspect

**Comment by ryantxu** [comment]
@peterholmberg -- I think your approach makes sense.  If you are close, we shoudl close this and focus on yours :)

Key things to add though are:
* only add the Errors tab if an error exists :)
* if an error exists, we should default to the Error tab
* (mabye) if an error exists, put just the message above the tabs?

**Comment by peterholmberg** [comment]
Yeah, I agree that it makes sense to have conditional tabs (only show the tab if it actually contains something). Will update my PR with this :)

**Comment by ryantxu** [comment]
see #21565

**Pull request closed without merging**
