### PR TITLE
Postgres/mysql engine cache was not being used, fixes #12636

### LINKED ISSUE #12636: SQL connection leak
https://github.com/grafana/grafana/blob/21e5d61de665383a0b9c26e8f74f144c84b8c047/pkg/tsdb/sql_engine.go#L57

There has been quite a few issues (which surprisingly seems to have been solved) about this: #8513, #9827 .... The problem is as soon as you have a dashboard and opening a second one in a browser or even keep refresh rate very low, you will see that new connections to postgres Server are made (I think other SQL Servers have the same problem as they also use this SQL generic engine). 
After some digging I found out this part where the cache is looked up for a version. But this version is never set -or I don't see it at least- that is why a new engine is always created instead of using the one from cache.
So a possible fix would be this:
`engineCache.versions[dsInfo.Id] = dsInfo.Version `in line 70 somewhere. 
At least this works in my case, but I don't know fully if this breaks something else? Or why are you using versions at all?

### PR DESCRIPTION
**Pull request by torkelo**
fix: postgres/mysql engine cache was not being used, fixes #12636

### CODE REVIEW

**Comment by sylr** [comment]
@torkelo @marefr We need this in v5.2.x.

Can we backport it and release v5.2.2 ?

**Comment by torkelo** [comment]
@marefr can you try to do the cherry picks and get a 5.2.2 out this week?

**Comment by sylr** [comment]
@torkelo Just a though, does this fix applies to postgres as datasource, as db backend or both ?

**Comment by marefr** [comment]
@torkelo yes, I've already planned a 5.2.2 this week.

@sylr this only applies to postgres/mysql/mssql datasources.

**Pull request merged**
