### PR TITLE
MarketTrend: rename to candlestick panel

### PR DESCRIPTION
**Pull request by ryantxu**
Naming is hard :cry:  -- I think we should make this panel beta in 8.3, but should release it with a name we want to live with.

@leeoniya points out a bunch of reasons why Candlestick or OHLC may not be a great name.  See:
https://github.com/grafana/grafana/pull/40909#issue-1035785034

The biggest argument against "candlestick" is that the panel includes a "volume" mode that will overlay volume bar graph in the same panel, so it is no longer strictly a candlestick chart.

Although the use-case is primarily financial -- the visualization is also useful to show trends in aggregated data.  We may want to clean up some of the language around "Price + volume" too.  Perhaps:
* Value + volume?

Related... seems like the difference between this and a "boxplot" is just that that people use "candlestick" when financial, and "boxplot" otherwise.  Also boxplots are sometimes horizontal :man_shrugging: 

This is built on top of #41574

Thoughts?

### CODE REVIEW

**Comment by leeoniya** [comment]
> Related... seems like the difference between this and a "boxplot" is just that that people use "candlestick" when financial, and "boxplot" otherwise. Also boxplots are sometimes horizontal 🤷‍♂️

there's actually a lot of differences. enough that a single candestick panel cannot be reused without a lot of additions, imo.

box plot candles represent quantiles, medians, means, distributions, and outlier points. the candles are rarely conditionally colored and typically do not represent trends of a single thing in time (nor candle-to-candle changes via coloring) but are closer to barcharts with labeled x to compare distributions. but yes, you can do temporal box plots too, similar to heatmap-esque view of how a distribution changes over time.

really the main similarity is that they're rendered as candles. but even these differ completely in semantics and a lot in appearance.

image

image

image

**Comment by ryantxu** [comment]
>  enough that a single candestick panel cannot be reused without a lot of additions, imo.

Totally agree -- but I would want that panel to be called "Boxplot" not "Statistical trends"

**Comment by ryantxu** [comment]
Added suggestions:
image

When #41613 is merged, this should be move to the top when it finds matches

**Comment by ryantxu** [comment]
I commented out the suggestions for now -- we can include them when this is not an alpha panel :)

**Review by torkelo — APPROVED** [review]
I much prefer the name Candlestick to Market trend even if it can do some other scenarios as well.

**Review by leeoniya — APPROVED** [review]

**Pull request merged**
