### PR TITLE
Elasticsearch: Implement CheckHealth method in the backend

### LINKED ISSUE #63727: ElasticSearch: Implement `CheckHealth` method in backend
**What happened**:
ElasticSearch does not have a `CheckHealth` method in the backend code implemented. This makes calls to the `/health` endpoint not working. 

Ref:
- https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health
- https://grafana.com/tutorials/build-a-data-source-backend-plugin/#add-support-for-health-checks

**What you expected to happen**:

- `/api/datasources/uid/:uid/health` to return valid information

**How to reproduce it (as minimally and precisely as possible)**:
Call `/api/datasources/uid/:uid/health` with the `uid` set to a ElasticSearch ds.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.0

### PR DESCRIPTION
**Pull request by mikelv92**
**What is this feature?**

ElasticSearch does not have a CheckHealth method in the backend code implemented. This PR adds a CheckHealth so that the `/api/datasources/uid/:uid/health` endpoint will return the health information.

**Why do we need this feature?**

Currently the /health endpoint is not working.

**Who is this feature for?**

Users that want to check the health of the datasource when using Elasticsearch

**Which issue(s) does this PR fix?**:

Fixes #63727

**Special notes for your reviewer:**

1. Start ES locally `make devenv sources=elastic`
2. With the `gdev-elasticsearch` datasource, open 
http://localhost:3000/api/datasources/uid/gdev-elasticsearch/health

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by matyax** [comment]
Hey @mikelv92 ! Thanks for your contribution. We'll reviewing as soon as we have some bandwidth. Stay tunned!

**Comment by mikelv92** [comment]
Thank you in advance for the review. I have already signed the CLA but I think the bot isn't updating the workflow...

**Comment by svennergr** [comment]
> Thank you in advance for the review. I have already signed the CLA but I think the bot isn't updating the workflow...

Thanks @mikelv92. Just to be sure, did you add the email used for the commit to your Github account? That's needed for the CLA to be marked as signed.

**Comment by mikelv92** [comment]
Unfortunately, I used the wrong email in the first commit...

**Review by svennergr — APPROVED** [review]
Nice, LGTM! Thank you for your contribution, @mikelv92!

**Pull request merged**
