### PR TITLE
Build: Remove usage of Go vendoring

### PR DESCRIPTION
**Pull request by kylebrandt**
With go modules and the proxy, I don't think we need the vendor folder anymore.

Having vendored code makes many backend PRs frustrating to review, because there is a bunch of distracting code in the diff that also slows down github. (Click "Files Changed" of this PR if you don't understand). I expect this makes it more likely for things to be missed during review.

We have been using the non-committed vendor and/or no vendor folder pattern with recent plugin and sdk development, and it seems to be much better experience.

Also we don't commit js dependencies for Grafana, so this seems more consistent with frontend development.

 - This adds `vendor/` to `.gitignore` as well, so one can still `go mod vendor` locally if that is their preference.
 - This removes vendoring code from `build.go` and the vendoring steps in the instructions for upgrading dependencies.
 - Build passes
 - `make run` works with oss
 
Any Enterprise concerns @xlson ? I'd be happy to look into them.

Will not merge without combined approval of xlson, (marefr or bergquist).

### CODE REVIEW

**Comment by kylebrandt** [comment]
remove vendor things from build.go: fixes `make run` with no vendor folder.

**Comment by ryantxu** [comment]
I see your game here:
image

**Review by aknuds1 — COMMENTED** [review]
Looks like a great idea, but why didn't CI run?

**Review by xlson — APPROVED** [review]
I have no objections and it seems to work fine with Enterprise.

**Comment by kylebrandt** [comment]
> Looks like a great idea, but why didn't CI run?

I was updating a readme, and didn't want the push to cancel the previous build so I ci skipped it. So it did run.

**Comment by marefr** [comment]
Caching of go modules can be a good idea to speed things up. Some information in caching section at the bottom [here](https://circleci.com/blog/circleci-matrix-jobs/).

@aknuds1 something for you to look into later maybe?

**Comment by bergquist** [comment]
Merging master might solve the build error.

**Review by marefr — APPROVED** [review]
image

**Comment by kylebrandt** [comment]
> Merging master might solve the build error.

Master is failing for same reason I think right now.

**Comment by aknuds1** [comment]
> Caching of go modules can be a good idea to speed things up. Some information in caching section at the bottom [here](https://circleci.com/blog/circleci-matrix-jobs/).
> 
> @aknuds1 something for you to look into later maybe?

Yes, we probably want to cache Go dependencies.

**Review by bergquist — APPROVED** [review]
This sounds like a good idea. :+1:

**Pull request merged**
