### PR TITLE
Plugins: Don't forward cookies for app plugins

### PR DESCRIPTION
**Pull request by marefr**
Fix so that cookies are not forwarded for app plugins

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]

**Review by andresmgot — APPROVED** [review]
LGTM

**Review by xnyo — APPROVED** [review]
LGTM!

**Review by tolzhabayev — APPROVED** [review]

**Review by dannyc-grafana — APPROVED** [review]

**Comment by jkroepke** [comment]
@marefr There is an opt-in possibility that Cookie still forward to clients?

I have an app which is doing request against the grafana API. The externalServiceAccount feature flag doesn't help here, because different users has different permissions and the serviceAccount has permissions to everything.

Is there an grafana native implementation to inherit the permissions from the user to an app?

**Comment by marefr** [comment]
@jkroepke no opt-in possibility.

Please refer to https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-rbac and the feature toggles `externalServiceAccounts` and `idForwarding`.

**Pull request merged**
