### PR TITLE
Update scripts and Dockerfiles to use Go 1.16.1

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR is responsible for upgrading Go version to `1.16.1`

Steps:

- [x] Update scripts and Dockerfiles
- [x] Publish images to Dockerhub
- [x] Update Drone related srcipts

### CODE REVIEW

**Comment by dsotirakis** [comment]
Will also have to backport against `v7.5.x`

**Comment by aknuds1** [comment]
You're going to update Drone as part of this PR too?

**Comment by dsotirakis** [comment]
Can do, no problem to open a new PR though.

**Comment by aknuds1** [comment]
It looks as if it should be done in this PR though since you made it part of the checklist.

**Comment by dsotirakis** [comment]
> It looks as if it should be done in this PR though since you made it part of the checklist.

Yep, I just wanted to first add those files for a review to be sure I didn't forget anything before I publish to the hub.

**Review by aknuds1 — COMMENTED** [review]
The files look right to me, good job.

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Remember to upgrade Drone config in enterprise also.

**Pull request merged**
