### PR TITLE
optimization in git clone using --depth

### PR DESCRIPTION
**Pull request by rajpratik71**
optimize the git clone using --depth flag in term of size of clone
and also in term's of time taken to fetch the files and commit history
of whole repository .

More detail can be found at blog
https://www.atlassian.com/git/tutorials/big-repositories

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
@Rajpratik71 thanks for the contribution, this looks reasonable. Can you also update https://github.com/grafana/grafana/blob/ed92b41d471d8788257e743076a11bebe8a5de4a/packages/grafana-toolkit/src/cli/tasks/plugin/create.ts#L108 ?

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Your branch is out of date and needs to be merged with master, otherwise CI won't work.

**Comment by Rajpratik71** [comment]
@torkelo  @oddlittlebird requesting review

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Pull request merged**
