### PR TITLE
fix cloudwatch ec2_instance_attribute

### PR DESCRIPTION
**Pull request by mtanda**
Fixes, https://github.com/grafana/grafana/issues/9667
Sorry, I may confirm that this feature is working, but not...

### CODE REVIEW

**Comment by torkelo** [comment]
Maybe a unit test as well?

**Comment by mtanda** [comment]
I add test. Please check.

**Comment by mtanda** [comment]
Not sure why fail test in CircleCI.
```
% go test ./pkg/tsdb/...
ok      github.com/grafana/grafana/pkg/tsdb     0.082s
ok      github.com/grafana/grafana/pkg/tsdb/cloudwatch  0.021s
ok      github.com/grafana/grafana/pkg/tsdb/graphite    0.034s
ok      github.com/grafana/grafana/pkg/tsdb/influxdb    0.050s
ok      github.com/grafana/grafana/pkg/tsdb/mysql       0.035s
ok      github.com/grafana/grafana/pkg/tsdb/opentsdb    0.028s
ok      github.com/grafana/grafana/pkg/tsdb/postgres    0.033s
ok      github.com/grafana/grafana/pkg/tsdb/prometheus  0.029s
```

**Comment by mtanda** [comment]
Pass test. Ready to merge.

**Comment by mtanda** [comment]
@bergquist @torkelo please check.

**Comment by torkelo** [comment]
@mtanda thank you! looks great

**Pull request merged**
