### PR TITLE
Dashboard metadata docs

### PR DESCRIPTION
**Pull request by utkarshcmu**

### CODE REVIEW

**Comment by bergquist** [comment]
Thank you for spending time on documentation.
Its very rare that people actually spend time on this in the open source community.

But I'm not sure about adding this. The dashboard meta data view is very simple and straight forward. I don't think there is any need for explain it in the documentation.

**Comment by utkarshcmu** [comment]
Np, I understand. Is the metadata a good feature to make into CHANGELOG for 3.0?

**Comment by utkarshcmu** [comment]
@torkelo How will we notify the users about the availability of this new dashboard metadata information available in Grafana's next version? via CHANGELOG or docs on the website or no need to notify explicitly about this new information about the dashboards?

**Comment by torkelo** [comment]
not sure, what do you think? Changelog woud be a good place to start

**Comment by utkarshcmu** [comment]
Keeping in mind that more information will be added to the metadata later. In my opinion, Changelog + Snapshot in website docs should be enough to notify users about the availability of metadata. #3744

**Pull request closed without merging**
