### PR TITLE
Explore: Sync timepicker and logs after live-tailing stops

### LINKED ISSUE #19954: Explore: After live-tailing stops, logs from pre-selected time range are not displayed
**What happened**:
In Explore, after live-tailing stops, logs from selected time range are not displayed. Instead of that, last logs that were displayed in live-tailing are shown. TimePicker and displayed logs are not synced. 
ezgif com-video-to-gif (3)

**What you expected to happen**:
See either logs for my selected time range OR change the time range according displayed logs. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Open Loki in Explore
2. Select Yesterday in TimePicker
3. Run live tailing
4. Stop live tailing
5. See that logs that are displayed don't correspond with time range Yesterday.

**Anything else we need to know?**:
Live-tailing is initialised with runQueries function. When user stop live-tailing, we display last values from the live-tailing. We don't run new runQueries function with range from time picker OR we don't change time picker based on logs.

**Environment**:
- Grafana version: 6.4.
- Data source type & version: Loki

### LINKED ISSUE #20628: Explore: Expanding LogRow after Live session doesn't show labels correctly
**What happened**:
Expanding LogRow after Live session doesn't show the details for that log row correctly.

**What you expected to happen**:
Expanding LogRow after a Live session should show the same labels as before Live session.

**How to reproduce it (as minimally and precisely as possible)**:
1. Goto Explore in Grafana
2. Enter any Loki query for a Loki data source that supports streaming, preferably a query that will return results during Live session.
3. Expand any LogRow and notice the labels in the expanded section.
4. Turn on Live session.
5. Wait for a result.
6. Turn off Live session.
7. Expand any LogRow and notice that the labels in the expanded section are no longer the same as before Live session. 👎 
image
8. Hit the `Run Query` button
9. Expand any LogRow and notice that the labels in the expanded section are the same as before Live session. 🆗 

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.0-beta1
- Data source type & version: Loki
- OS Grafana is installed on: docker
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

- [Design doc](https://docs.google.com/document/d/18HjaTS1ZJ2wqpJVt4Z3tbgNi7QaSWGofByU0J8Bh6B0/edit#heading=h.ejymv9t9d80r)

In Explore, after live-tailing stops, logs from previously selected timepicker range are not displayed. Instead of that, we display logs that were shown in live-tailing. This means, that timepicker and displayed logs are not synced. This PR fixes the issue by running the new runQueries function with range from timepicker. Secondly, it removes the live-tailing button animation, as it was quite often _slow_/_out of sync_ with other parts of the button. This was even more visible after implementation of `runQueries function`.

ezgif com-video-to-gif (13)

**Which issue(s) this PR fixes**:

Fixes #19954
Fixes #20628

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@davkal based on the feedback from people on UX session and in design doc, most of the people prefer solution, where users return to Explore and see logs based on previously selected time-picker range. We've had 2 implementation options in design doc and this PR implements the first one, that I personally consider a better option due to the reasons mentioned in the design doc. Could you please look at it and let me know what do you think! 🙏

**Review by davkal — COMMENTED** [review]
Really happy with the solution.
I found one thing confusing: When looking at a past range and then going live, the live mode is populated with the old entries, which are definitely not "live". Can we change that?

**Review by aocenas — APPROVED** [review]
Looks good to me. Regarding the issue @davkal mentioned I think we should do it in separate PR as that one is there for a long time and seems like a separate thing to me.

**Comment by ivanahuckova** [comment]
@davkal I am going to create a new PR with the fix for the issue you are mentioning. 🙂

**Pull request merged**
