### PR TITLE
Canvas: Refactor utils for ConnectionSVG component

### PR DESCRIPTION
**Pull request by krishnemd**
**What is this feature?**

Component code refactored to required utils

**Why do we need this feature?**

Refactoring

**Who is this feature for?**

Frontend devs

**Which issue(s) does this PR fix?**:

Fixes this TODO:

https://github.com/grafana/grafana/blob/150d4d68ad74bc342ee9bf4d6db85cfe5b5fd918/public/app/plugins/panel/canvas/components/connections/ConnectionSVG.tsx#L129C63-L129C63 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by chauchausoup** [comment]
@adela-almasan did the sync few days ago. Let me know if I have to do it again.

**Review by adela-almasan — APPROVED** [review]
⭐

**Comment by adela-almasan** [comment]
Hey @chauchausoup, all looks good but the build is still failing, would you mind re-merging the latest `main`? Thanks!

**Comment by chauchausoup** [comment]
@adela-almasan Please check now.

**Comment by adela-almasan** [comment]
@chauchausoup unfortunately the build keeps failing so I pulled your branch into a new [PR](https://github.com/grafana/grafana/pull/77578) to be able to merge it. Thank you for your contribution! ⭐

**Pull request closed without merging**
