### PR TITLE
Azure Monitor: Add support for alerting in multiple resources queries, chained dimension filters, multi-select template variables and fix multi-select init bug

### LINKED ISSUE #19170: Azure Monitor: Add support for alerting in Multiple Resources queries
Alerting is already implemented for single resource queries. It should be implemented also for multiple resources.

### LINKED ISSUE #19221: Azure Monitor: Resource Type dropdown not populated
When in query mode `Multiple Resources` and a new query is created, the Resource Type dropdown should be populated with values. As of now it isn't, but I get populated with values once the subscription dropdown is changed.

### LINKED ISSUE #19310: Azure Monitor: Make it possible to chain filter conditions
As of now it's only possible to add one filter condition in the query editor. However, the azure monitor API supports multiple filter conditions so it be supported in the query editor aswell.

### LINKED ISSUE #19316: Azure Monitor: Add support for template variables in cross resources multi-select
The new query mode `Multiple Resources` in Azure Monitor has a new component which supports multiselect. As of now, this component does not support template variables.

Feature request: Make sure all available template variables are added add "selectable" in the multiselect dropdown.

### PR DESCRIPTION
**Pull request by sunker**
Lots of refactoring both in backend and frontend in order to add support for alerting in multiple resources queries, chained dimension filters, template variables in new multi-select dropdown and also fixing multi-select init bug.  

closes #19170
closes #19310
closes #19221
closes #19316

### CODE REVIEW

**Review by briangann — CHANGES_REQUESTED** [review]
The resource types are not coming back to the UI

image

I do see the request returning data though:

image

**Comment by briangann** [comment]
The query for cross-resource alerting seems to be using a different query (from a different panel)

This is the query:

image

And the alert test:

image

log:

image

**Comment by briangann** [comment]
also saw an "Unauthorized" error when switching from Single Resource to Cross Resource.  I think the fields need to be reset completely (emptied/etc) when switching between types.

**Comment by briangann** [comment]
the cross-resource query i have has remnants of single-resource:

            "metricDefinition": "Microsoft.Storage/storageAccounts",
            "metricName": "UsedCapacity",
-->            "metricNamespace": "Microsoft.Compute/virtualMachines",

**Comment by sunker** [comment]
> The resource types are not coming back to the UI
> 
> image
> 
> I do see the request returning data though:
> 
> image

This is a separate issue, so I put it in another [pr](https://github.com/grafana/grafana/pull/19229)

**Comment by sunker** [comment]
Great that you found that issue with metricNamespace not being reset when switching between query modes. 
https://github.com/grafana/grafana/pull/19225/commits/3b59e5a273f99eb78d91407cf9ab9f1b9316649b should address that problem. Also guarding up in the backend so that those that have already stored metricNamespace on the multi resources query json model are safe.

**Pull request closed without merging**
