### PR TITLE
move panel focus by key (hjkl)

### PR DESCRIPTION
**Pull request by mtanda**
Implement option 3 of https://github.com/grafana/grafana/issues/8289 .

### CODE REVIEW

**Comment by torkelo** [comment]
I did plan to add something like this (big vim user myself), but not sure it's a good idea to use these keys as this will make it impossible to use `h,j,k,l` as part of shortcuts or shortcut sequences

**Comment by mtanda** [comment]
I like vim too :-)
I often use `j,k` shortcut key of Gmail and Github.

Use `Alt` key with `h,j,k,l` is better than no shortcut.
This might be useful for Notebook dashboard (https://github.com/grafana/grafana/issues/8254).

**Comment by mtanda** [comment]
`h` and `mod+h` is already assigned. use `ctrl` as the prefix key.

**Comment by bergquist** [comment]
I think its more important to support arrows since that will target a wider audience. 
[hjkl] is fun and all but... arrows is better :)

**Comment by mtanda** [comment]
Sorry, I do it because too much love for vim key binding :)

**Comment by bergquist** [comment]
@torkelo will this work with 5.0? Otherwise, I think we should close it :/

**Comment by torkelo** [comment]
no, think this has to be redone in with new v5 grid

**Pull request closed without merging**
