### PR TITLE
Backend plugins: Allow backend component for apps

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Allow an app plugin to have a backend component.

### CODE REVIEW

**Comment by ryantxu** [comment]
Is this needed for 7.0?  if we wait till 7.1, are we breaking anything?

**Comment by bergquist** [comment]
It sounds like a reasonable idea but I agree with Ryan. The lines between app/panel and app/datasources might need a few eye concept wise. We probably want to think about this a bit more before introducing it. Seems like all plugins could have backends so codewise I think we should solve it for all plugins in one place rather than per plugin type.

**Comment by marefr** [comment]
Reverted backend component for panel plugins. Lets discuss this tomorrow

**Comment by marefr** [comment]
Closing this. May pick it up for 7.1

**Pull request closed without merging**
