### PR TITLE
Azure Monitor: Add Microsoft.Network/natGateways

### LINKED ISSUE #29383: Enhancement: Add "Microsoft.Network/natGateways" to Azure Monitor
**What would you like to be added**:  Support for the "Microsoft.Network/natGateways" namespace in Azure Monitor

**Why is this needed**:  My company needs to monitor the metrics for our NAT Gateways in Azure.

This _should_ just be a matter of adding the namespace to the SupportedNamespaces class in supported_namespaces.ts -- I did exactly that in my local repo, compiled it, and everything seems to work as expected.  The only problem is that I cannot test the Bytes metric:  for some reason, we don't have any data there in our Azure subscriptions (the Azure portal shows nothing as well), so I'm a little wary of just throwing in a pull request and getting yelled at.  :)

### PR DESCRIPTION
**Pull request by JoeyLemur**
**What this PR does / why we need it**:  Adds Microsoft.Network/natGateways to the supported namespaces in Azure Monitor Datasource.  This allows Grafana to display metrics associated with NAT Gateways in Azure.

**Which issue(s) this PR fixes**: 29383

Fixes #29383

### CODE REVIEW

**Review by papagian — APPROVED** [review]
Even though I don't have metrics under this namespace in any Azure subscriptions I think that the modification is legitimate.
Thank you for your contribution!

**Comment by aknuds1** [comment]
Is this documented anywhere?

**Review by aknuds1 — APPROVED** [review]

**Comment by JoeyLemur** [comment]
Best I could find in Microsoft's documentation:

https://docs.microsoft.com/en-us/azure/virtual-network/nat-metrics
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-07-01/natgateways

**Comment by aknuds1** [comment]
Thanks!

**Pull request merged**
