### PR TITLE
Packages: update package.json files 

### PR DESCRIPTION
**Pull request by dprokop**

### CODE REVIEW

**Comment by dprokop** [comment]
@torkelo, I hope https://github.com/grafana/grafana/pull/18173/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3 is fine?

**Comment by dprokop** [comment]
@ryantxu I've adde packages cross-references to package.json. When the package.json's version of the local package matches lerna.json's major, then the local package will be used. Adding this as it feels legit to have the same set of dependencies (not versions) in package.json thats in the repo and in the registry.

**Review by ryantxu — COMMENTED** [review]
won't this download something when we run `yarn install`?

I agree it makes sense.... but aren't we using workspaces to do the same thing?  or can they live happily together without messing anything up?

If we do add the dependencies.... should we also add to the root `package.json`:
```
    "@grafana/data": "^6.4.0-alpha",
    "@grafana/ui": "^6.4.0-alpha",
    "@grafana/runtime": "^6.4.0-alpha",
```

**Comment by dprokop** [comment]
> won't this download something when we run yarn install?

As far as I have tested it, it doesn't download anything.

**Review by torkelo — APPROVED** [review]

**Pull request merged**
