### PR TITLE
Grafana UI: Add implicit submit to TimeRangeForm for A11y

### LINKED ISSUE #52577: A11y: Time range form - Implicit Submission
**Steps to reproduce**:

1. Open a time range form (Dashboards - from/to range or Silence interval in Alerts)
2. Change a value in the from/to input field
3. With the input field still focused hit enter

**Actual Result**:

No change happens.

**Expected Result**

The form should be submitted and the time range changed.

**Relevant WCAG Criteria:** [2.1 Keyboard](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#qr-keyboard-operation-keyboard-operable)

**Environment**:
- Grafana version: 9.1.0-pre
- Data source type & version: -
- User OS & Browser: MacOS Big Sur, Chrome 103
- Others:

### PR DESCRIPTION
**Pull request by matejkubinec**
**What this PR does / why we need it**:

Adds support for implicit submission by pressing
the enter key when input field is focused.

**Which issue(s) this PR fixes**: #52577

Fixes #52577

### CODE REVIEW

**Comment by mellieA** [comment]
Thank you for your contribution @matejkubinec! I've added this to the squad's project board for review

**Review by axelavargas — APPROVED** [review]
Hey @matejkubinec 👋🏾 , great work, the code looks good to me, I gave it a try, and it works as expected!

**Review by codeincarnate — APPROVED** [review]
Took a look and seems to be working fine. Was asked to take a look to make sure this interacts fine with fiscal years as well which it appears to. Entering the appropriate string for the relative times and hitting enter worked in that case.

**Comment by matejkubinec** [comment]
@axelavargas Synced, should be good to go.

**Pull request merged**
