### PR TITLE
fix: library panels not geting imported over dashboard API

### LINKED ISSUE #44003: Importing Dashboard through Grafana API does not import panels
**What happened**:
Using gdg (https://github.com/netsage-project/gdg) for trying to import Dashboard to Grafana result with Error connecting Panels
Screenshot 2022-01-10 at 21 14 51

**What you expected to happen**:
Panel in Dashboard to be imported and linked properly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Export any Dashboard with panels
2. Try to POST that Dashboard to Grafana that does not yet have it.

**Anything else we need to know?**:

It works if Imported through Grafana UI
PR with fix: https://github.com/grafana/grafana/pull/43525

**Environment**:
- Grafana version: 8.3.3 and main branch
- Data source type & version: 
- OS Grafana is installed on: Alpine
- User OS & Browser: MacOS BigSur
- Grafana plugins: NA
- Others: NA

### PR DESCRIPTION
**Pull request by efekete**
What this PR does / why we need it:
fix for library panels not getting imported over dashboard API
original feature for import/export of library panels (over Grafana UI) is here:
https://github.com/grafana/grafana/pull/39214

Fixes #
https://github.com/grafana/grafana/issues/44003
**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hugohaggmark** [comment]
Hi @efekete can you explain in more detail in what use case this fix is necessary?

**Comment by efekete** [comment]
Hi @hugohaggmark 

so the problem you solved was importing dashboard panels. It all works great when I am importing dashboard through UI. The problem we ran into is when using a tool like https://github.com/netsage-project/gdg. 
It uses dashboard API and there import of panels is not implemented. The import works well, but the panels that dashboard is referring does not exist and therefor can not be used. This PR should fix that issue.

**Comment by hugohaggmark** [comment]
> Hi @hugohaggmark
> 
> so the problem you solved (in above linked PR) was importing dashboard panels while importing the dashboard itself. It all works great when we are importing dashboard through UI. The problem we ran into was when we tried using a tool like https://github.com/netsage-project/gdg. It uses dashboard API and there import of panels is not implemented. The import works well, but the panels that dashboard is referring does not exist and therefor can not be used. This PR should fix that issue.

Just so I understand, you're using the post dashboard api to import dashboards? There is an import dashboard api for that case. Not sure we'll consider this solution for this use case.

**Comment by efekete** [comment]
Can you point me in right direction for that API?

https://grafana.com/docs/grafana/latest/http_api/dashboard/
Here, I only found POST which the tool above use. I don't think it is transparent enough what should be used for what.

I think it would be good feature to import panels even when posting dashboard through dashboard API either way.

**Comment by hugohaggmark** [comment]
> Can you point me in right direction for that API?
> 
> https://grafana.com/docs/grafana/latest/http_api/dashboard/ Here, I only found POST which the tool above use. I don't think it is transparent enough what should be used for what.
> 
> I think it would be good feature to import panels even when posting dashboard through dashboard API either way.

You're absolutely correct and my vacation was too long it seems 🙈  The import endpoint doesn't seem to be documented at all, maybe this is more important.

**Comment by efekete** [comment]
So what would be the best approach to mitigate this issue?

**Comment by hugohaggmark** [comment]
Maybe someone from @grafana/backend-platform can chime in here?

**Comment by efekete** [comment]
Also, if relevant, while trying to import dashboard that has panels that does not exist, I get an error:

```bash
time="2022-01-10T21:10:09+01:00" level=info msg="error on Exporting dashboard Apps / Generic per pod HTTP error 500: returns Error while connecting library panels"
```

One more reason I think this fix should probably be merged. 

Although, even when that happen I get dashboard imported, but not fully working.

Screenshot 2022-01-10 at 21 14 51

**Comment by hugohaggmark** [comment]
> Also, if relevant, while trying to import dashboard that has panels that does not exist, I get an error:

When you exported the dashboard did you make sure to export it with `Export for sharing externally`?
image

**Comment by efekete** [comment]
I am not 100% sure, but if I import the same dashboard through Grafana UI, it imports as expected with all library panels imported and linked. 
As the code for "dashboard POST" is already linking all the panels present, I do not see the downside of those getting imported before that happens.

**Comment by hugohaggmark** [comment]
We don't support importing using the dashboard post api so we'll close this issue and PR. We can always revisit this if more feedback is received from the community. Thank you 🙏

**Comment by efekete** [comment]
So is there any officially supported API we can use for that?
We have staging and production Grafana with large number of dashboards with shared panels and we want to  automate cloning all dashboard to production once we are satisfied with state of those on staging.

**Comment by marefr** [comment]
Not really. You have to figure out how to use non-documented `POST /api/dashboards/import` endpoint that UI are using for importing dashboards. One way figuring that out is to use Chrome Developer Tools or similar and inspect the network interaction when importing a dashboard

**Comment by efekete** [comment]
I guess that is ok if you are not planing to remove that API in future. Should I, if I find time, try to write documentation for that or someone else is already working on that?

**Comment by marefr** [comment]
We're currently not planning to remove it. Would that change in the future it will follow deprecation notice and breaking change in a major Grafana version. I'm not sure how easy it is to document it, but if you're interested you're welcome to give it a go.

**Pull request closed without merging**
