### PR TITLE
Cloudwatch: Add AWS/DDoSProtection metrics and dimensions

### LINKED ISSUE #31273: TSDB/Cloudwatch: missing new AWS Shield metrics and dimensions
**What would you like to be added**: 

AWS Shield recently announced new metrics available on Cloudwatch (see [blog post](https://aws.amazon.com/about-aws/whats-new/2021/01/aws-shield-advanced-now-provides-mitigation-metrics-and-network-traffic-timelines/)).

There are new metrics and dimensions now available in CloudWatch:
- metrics: `VolumePacketsPerSecond`, `VolumeBitsPerSecond` 
- dimensions: `MitigationAction`, `Protocol`, `SourcePort`, `DestinationPort`, `SourceIp`, `SourceAsn`, `TcpFlags`

**Why is this needed**:

Unless those new metrics are added [here](https://github.com/grafana/grafana/blob/2b5a88bf8cfe51656d735e7a03c084b898e9a3c0/pkg/tsdb/cloudwatch/metric_find_query.go#L63) and new dimensions [here](https://github.com/grafana/grafana/blob/2b5a88bf8cfe51656d735e7a03c084b898e9a3c0/pkg/tsdb/cloudwatch/metric_find_query.go#L159) respecitvely, it won't be possible to use them via Grafana.

I'm happy to submit a PR myself if that'll make things easier on Grafana's side.

### PR DESCRIPTION
**Pull request by relvira**
**What this PR does / why we need it**:

AWS Shield recently announced new metrics available on Cloudwatch (see [blog post](https://aws.amazon.com/about-aws/whats-new/2021/01/aws-shield-advanced-now-provides-mitigation-metrics-and-network-traffic-timelines/)).

This PR adds those to `tsdb/cloudwatch/metric_find_query.go` so that they can be discovered via Grafana.

**Which issue(s) this PR fixes**:

Fixes #31273 

**Special notes for your reviewer**:

These metrics and dimensions have not yet been added to AWS Shield metrics documentation, AWS Shield engineers have send me a list of these so we can get them added to Grafana. I can provide output from the CloudWatch API proving these exist if needed.

### CODE REVIEW

**Review by sunker — COMMENTED** [review]
Great, thank you so much for contributing @relvira! 

Please note that you need to sign the contributor license before this can be merged.

**Review by sunker — APPROVED** [review]

**Comment by relvira** [comment]
thanks for jumping in @sunker! I was waiting for confirmation from my employer to sign the CLA, to which I've been given green light and is now signed 🙌🏼.

The Go tests were cancelled for this PR, not sure what happened there. Let me know if there's anything else I can do to move this forward. Happy to contribute!

**Comment by relvira** [comment]
hey @sunker, just touching base on this PR again. As it's approved and CLA has been signed, anything else pending for it to be merged?

Thanks!

**Comment by sunker** [comment]
thanks @relvira!

**Pull request merged**
