### PR TITLE
DataSourceRef: use reference rather than id where possible

### PR DESCRIPTION
**Pull request by ryantxu**
After #41172, the query endpoint will now prefers to accept the type+uid rather than the internal `datasourceId`

This PR updates many datasources that call the endpoint directly so that we begin to wean ourselves from using internal ids primarily

### CODE REVIEW

**Comment by ryantxu** [comment]
@dprokop / @sunker -- this should be pretty straightforward, but would be great to get someone in cloud-data sources and bi (SQL*) to verify that everything still looks OK :grimacing:

**Review by torkelo — APPROVED** [review]
Looks good

**Review by sunker — APPROVED** [review]
Nice! Tested the cloud data sources and they work as expected.

**Comment by dprokop** [comment]
@ryantxu yes, I'll test it against BQ soon.

**Comment by ryantxu** [comment]
@dprokop -- since this will not affect BQ at all... i'll go ahead with this as is

**Pull request merged**
