### PR TITLE
Provide additional technical IDs to webhook

### PR DESCRIPTION
**Pull request by schnobbl**
**What this PR does / why we need it**: Add some extra information to webhook body (OrgId, DashboardId, PanelId)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by schnobbl** [comment]
hi, reminder to add some reviewers thx

**Comment by schnobbl** [comment]
still waiting for reviewers

**Comment by aknuds1** [comment]
Thanks, will have a look.

**Comment by aknuds1** [comment]
Thanks again for submitting the PR, I'm verifying with my colleagues what the ramifications would be of making this change.

**Comment by aknuds1** [comment]
Thanks for the contribution, but apparently these changes were already made in #20420! Closing since all changes in the PR are already in master.

**Pull request closed without merging**
