### PR TITLE
Tempo: Select performance improvements

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Select performance improvements.

**Why do we need this feature?**

Improve performance of loading large numbers of tags into our tags select in the query editor.

**Who is this feature for?**

Tempo users.

**Special notes for your reviewer:**

https://github.com/user-attachments/assets/4b4ea7df-bc38-4f92-959b-6395fd714d2b

Appears as though the browser is creating its own limit of sorts.

Screenshot 2024-08-09 at 10 32 03

### CODE REVIEW

**Review by adrapereira — APPROVED** [review]
LGTM! Thank you for looking into this!

**Review by adrapereira — COMMENTED** [review]
We might also need to do this for the values Select though, it can also have cardinality issues.

**Comment by joey-grafana** [comment]
Yeah, sure I think we should get ahead of potential issues of a similar nature before an issue is raised.

One other potential improvement is to tell the user when we have limited the dropdown to 10k tags. Although I think this has little impact overall as they're probably not going to be going through the 10k list, more likely they will just start typing. So, we should tell them when their typed search is limited to 10k results.

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!

**Pull request merged**
