### PR TITLE
fixed slack exception

### LINKED ISSUE #35969: Cannot send alerts to slack
**What happened**:
After upgrading to version `8.0.1`  we couldn't get slack notifications, here is the error log (upgrading to `8.0.2` and `8.0.3` didn't find the issue):

```
lvl=eror msg="Alert Panic" logger=alerting.engine error="interface conversion: interface {} is nil, not bool" stack="[engine.go:177 panic.go:965 iface.go:261 slack.go:390 slack.go:325 notifier.go:138 notifier.go:178 notifier.go:183 notifier.go:125 result_handler.go:102 engine.go:220]"
```
So I checked the code, and the exception is rising from the bellow section in `slack.go`:
```go
		var rslt map[string]interface{}
		// Slack responds to some requests with a JSON document, that might contain an error
		if err := json.Unmarshal(body, &rslt); err == nil {
			if !rslt["ok"].(bool) {
				errMsg := rslt["error"].(string)
				sn.log.Warn("Sending Slack API request failed", "url", sn.url.String(), "statusCode", resp.Status,
					"err", errMsg)
				return fmt.Errorf("failed to make Slack API request: %s", errMsg)
			}
		}
```
The `!rslt["ok"].(bool)` is causing exception as `rslt` has no `ok` field: 
```
map[queued:true success:true]
```
I will add a PR regarding this issue

### PR DESCRIPTION
**Pull request by yasharne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #35969 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by codesome — COMMENTED** [review]
Thanks for the PR. Have you tested this and are you able to get the notifications with this?

This part of code comes after having attempted sending notification to slack, so an error here should actually not result in failed notification delivery.

Moreover, the slack api docs ([1](https://api.slack.com/methods/chat.postMessage), [2](https://api.slack.com/messaging/webhooks)) say it should be `"ok"`, so not sure if this change is right.

**Comment by yasharne** [comment]
Hi @codesome yes, I have tested this PR and it works fine in my case. the `rlst` conent is either `map[queued:true success:true]` or `map[error:'ERROR MESSAGE' success:false]`
So as I mentioned in the issue #35969 the current config causes the bellow exception:
```
lvl=eror msg="Alert Panic" logger=alerting.engine error="interface conversion: interface {} is nil, not bool" stack="[engine.go:177 panic.go:965 iface.go:261 slack.go:390 slack.go:325 notifier.go:138 notifier.go:178 notifier.go:183 notifier.go:125 result_handler.go:102 engine.go:220]"
```
`Test` alerts and `OK` alerts are working as expected but the alerting state alerts get the above error

**Comment by codesome** [comment]
Are you using the slack messaging API or the webhook? And do you have any proxy in between? The response that you got does not match the ones in the docs.

**Comment by yasharne** [comment]
@codesome  I'm using webhook and there are no proxy in the middle

**Comment by codesome** [comment]
Reading through the [docs](https://api.slack.com/messaging/webhooks) again, the response should be a _plain text_ `ok`, and that is inline with what I tested just now. So the code should not reach that point in the first place. If you are getting a JSON with `success` in it, you might want to double check if you have something in between doing the translation.

And I would be hesitant in making any API call changes that is not inline with the official docs.

**Comment by yasharne** [comment]
@codesome Can you check the content of `rlst` variable when sending alerts to the slack?

**Comment by codesome** [comment]
> the response should be a plain text `ok`, and that is inline with what I tested just now

Hence the json unmarshal fails, since the response is plain text and not json, hence `rlst` is not populated at all

From the [docs](https://api.slack.com/messaging/webhooks):
> Though in most cases you'll receive a "HTTP 200" response with a plain text `ok` indicating that your message posted successfully

**Comment by yasharne** [comment]
Thanks for your kind review @codesome , I will close the PR

**Comment by codesome** [comment]
I am curious to know if you were able to find the cause. Since the code is following the official docs, a different response means there is something in between which is translating the response. I would like to close https://github.com/grafana/grafana/issues/35969 if that is the case.

**Comment by yasharne** [comment]
@codesome We use a middleware to translate the slack styled messages to matrix homeserver, and that was the problem, I had a PR to add the ability to send messages directly to the matrix (#29931) but grafana team is not accepting any new notifiers and we are stuck with the buggy middleware

**Pull request closed without merging**
