### PR TITLE
Add enable ok alert option

### PR DESCRIPTION
**Pull request by davewat**
#12330 

Add option to config file to disable the 'OK' message from Alerts.  Defaults to enabled (send OK Alerts).

### CODE REVIEW

**Comment by torkelo** [comment]
Thanks for contributing to Grafana! 

This feature needs a more general approach, for example introducing state change filters to notification channels. 

https://github.com/grafana/grafana/issues/6696

**Comment by davewat** [comment]
@torkelo did you see my reasoning here #12330 ?  (I think) we have a strong use case to just turn them off globally.  However, if still no, are you suggesting that moving the option to the Notification Channel configuration would be acceptable?  Something more specific?

**Comment by torkelo** [comment]
Yes, making it an option on the notification channel makes more sense and is more discoverable & flexible.

**Comment by aditimittal** [comment]
When will this feature be officially released in the version?

**Pull request closed without merging**
