### PR TITLE
alerting: Support Pending with NoData

### PR DESCRIPTION
**Pull request by kylebrandt**
WIP For #16290

### CODE REVIEW

**Comment by kylebrandt** [comment]
I'm not sure if when "No Data" is set to "NoData" if the NoData state should be considered `Firing` or not ...

**Comment by kylebrandt** [comment]
Perhaps related, in regards to how no_data set to no_data should be handled: https://github.com/grafana/grafana/issues/17780 

My impression is that just how that option and the resulting state should be handled was maybe never clearly defined. ShouldNotify in the base notifiers behavior is to send a notification unless a condition is meant that prevents it. So it is possible the use of No Data to become "No Data" notifications was not intended, and the creators thought in this case it would be set to "Alerting".

**Comment by kylebrandt** [comment]
A possible bug that may possibly be related if it is a bug https://github.com/grafana/grafana/issues/17591

**Comment by marefr** [comment]
@kylebrandt This looks like it's ready for review? Any outstanding questions?

**Comment by torkelo** [comment]
Anything left here?

**Comment by marefr** [comment]
Will close this since we've closed #17780 which fixes the first part when not using For and No Data. There's other issue regarding second part.

**Pull request closed without merging**
