### PR TITLE
Dashboard Scene: Fix permissions and error handling in creating alert from panel  

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this PR fixing?**

- Add missing check for showing the "create alert rule" menu option

- Handles errors when creating an alert from the panel menu. We missed this from the migration.

https://github.com/user-attachments/assets/3934d48c-7bd7-49be-9c29-1d81fd7bf346

**Which issue(s) does this PR fix?**:

Related [#12783](https://github.com/grafana/support-escalations/issues/12783)

**Special notes for your reviewer:**

**Steps to test the PR:**

- Create a dashboard and a panel with a single query using Prometheus Datasource 
- To simulate the error, go to the dashboard JSON, and in the `target` section(this is what we call query) add the following
```
 "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "ddk13noiiiakgd"
          },
```
- Save the Dashboard and refresh the page
- Then click `New Alert Rule` on any of the panels using the panel menu
- An error should be trigger, something like `Error getting rule values from the panel: {"message":"Datasource ddk13noiiiakgd was not found"}`

TODO:
- [x] Add error handling.
- [x] Add unit test.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Works great. Unit test would be useful for this!

**Comment by axelavargas** [comment]
> Works great. Unit test would be useful for this!

@dprokop thanks for the review, actually while creating the test for the menu, I discovered we missed a permission check for the "create Alert Rule". I have added that condition back and also the missing tests from the old implementation and two new test cases for the the error handling

**Review by soniaAguilarPeiron — COMMENTED** [review]
LGTM!

**Review by soniaAguilarPeiron — APPROVED** [review]
:shipit:  LGTM!

**Pull request merged**
