### PR TITLE
test: use `T.TempDir` to create temporary test directory

### PR DESCRIPTION
**Pull request by Juneezee**
**What this PR does / why we need it**:
We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.

Reference: https://pkg.go.dev/testing#T.TempDir

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yuri-tceretian** [comment]
Good change! Thanks for the contribution! This also causes problems when tests are run in Windows. Test suites are marked as failed because clean up fails due to the log file is used and cannot be deleted.

**Comment by Juneezee** [comment]
> Good change! Thanks for the contribution! This also causes problems when tests are run in Windows. Test suites are marked as failed because clean up fails due to the log file is used and cannot be deleted.

@yuri-tceretian Thanks for reviewing this PR! 

There is a known issue where Windows would report "Access is denied" when the temporary directory is being cleaned up. A workaround has been implemented, see https://github.com/golang/go/commit/d407a8c3c49f11980f224d204147eff8fcb087f4. This workaround is now available in Go 1.18 Beta 2.

The tests could also fail on Windows when we did not do proper cleanup (e.g. close file). `t.TempDir()` can help us detect those

**Review by yuri-tceretian — APPROVED** [review]
LGTM. You're right it does not fix the problem with Windows it just moves it inside the testing framework. Anyway, the overall change is good

**Comment by Juneezee** [comment]
@grafanabot Mark as not stale please

**Pull request merged**
