### PR TITLE
chore: update core plugin descriptions

### LINKED ISSUE #83447: chore: plugins are missing descriptions
The description and keywords field is empty for a number of plugins which impacts their discoverability.

Description is exposed to the user in the plugin details page and provides a quick summary of the plugin, it may be used in the future to impact search rankings. Keywords were used on searches on grafana.com, they have recently been incorporated in searches within grafana.com/plugins as well as within grafana `/connections` and `/plugins`

```[tasklist]
### Add descriptions
- [x] alertmanager
- [x] candlestick
- [x] histogram
- [x] xychart
- [x] grafana-enterprise-logs-app
- [x] grafana-metrics-enterprise-app
- [x] grafana-enterprise-traces-app
- [x] grafana-opensearch-datasource
```
```[tasklist]
### Tasks
- [ ] Update via api
```

### PR DESCRIPTION
**Pull request by sympatheticmoose**
**What is this feature?**

This adds suggested `description` and `keywords` values to Core plugins - information on which can be found in the [plugin.json](https://grafana.com/developers/plugin-tools/reference-plugin-json) reference. 

**Why do we need this feature?**

Improves discoverability of these plugins when a user searches.

**Who is this feature for?**

Grafana users searching for a plugin

**Which issue(s) does this PR fix?**:

Fixes #83447 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by tolzhabayev — APPROVED** [review]
LGTM

**Review by nmarrs — APPROVED** [review]
LGTM

**Review by baldm0mma — APPROVED** [review]

**Comment by baldm0mma** [comment]
Looks like drone had some broken tests. Maybe flaky, maybe not. Going to trigger a CI drone rerun.

**Comment by sympatheticmoose** [comment]
@baldm0mma maybe needs `updateSnapshotFlag` set? https://github.com/grafana/grafana/blob/main/pkg/tests/api/plugins/api_plugins_test.go#L92 wdyt

**Comment by baldm0mma** [comment]
> @baldm0mma maybe needs `updateSnapshotFlag` set? https://github.com/grafana/grafana/blob/main/pkg/tests/api/plugins/api_plugins_test.go#L92 wdyt

Yeah, it looks like that could be the issue. I'll try to update this...

**Comment by baldm0mma** [comment]
@sympatheticmoose looks like that didn't change anything. I'm going to revert the change. Possibly @DanCech or @aocenas know what this issue is?

**Comment by nmarrs** [comment]
@baldm0mma / @sympatheticmoose your hunch was correct and very close to fixing it :) in future to update the snapshot you need to:
1) set the update `updateSnapshotFlag` to `true`
2) run the test locally, you should see the snapshot file change appear
3) set the `updateSnapshotFlag` back to `false`
4) push up snapshot files changes
5) profit :)


https://github.com/grafana/grafana/assets/22381771/99b968b5-2bc3-42e0-9236-ab9c6c3cb66e

**Comment by baldm0mma** [comment]
> @baldm0mma / @sympatheticmoose your hunch was correct and very close to fixing it :) in future to update the snapshot you need to:
> 
> 1. set the update `updateSnapshotFlag` to `true`
> 2. run the test locally, you should see the snapshot file change appear
> 3. set the `updateSnapshotFlag` back to `false`
> 4. push up snapshot files changes
> 5. profit :)
> 
>  tutorial.mov

Thanks homie!!!

**Comment by sympatheticmoose** [comment]
Awesome - thanks for all the help!

**Review by gillesdemey — APPROVED** [review]
Alerting changes LGTM

**Pull request merged**
