### PR TITLE
Opentsdb 2.2 filters support without modifying current dashboards

### LINKED ISSUE #3271: Grafana support for Opentsdb v2.2.0 and above
There are big differences between Opentsdb 2.1 and 2.2.

1. Opentsdb deprecated tags in v2.2.0 and introduced filters. This is one of the major change which we need to make in Grafana query control. 

2. /api/query takes a new parameter "showQuery" to identify request queries, which throws 400 with any version lower than Opentsdb v2.2.0.

So, how should we support these two different kinds of Opentsdb version? There are two options I can think of:

1. Stop supporting Opentsdb 2.1.1 for Grafana 2.6 and above. If Grafana 2.6 and above is used, people need to upgrade Opentsdb to 2.2.0. This is the **easy** option to implement :smile: 

2. Have two datasources for Opentsdb which are 
a.) 2.1.1 and lower 
b.) 2.2.0 and above
like we have for InfluxDB. This is the **harder** option to implement and won't affect users even if they upgrade Grafana.

My vote is option 2.

### PR DESCRIPTION
**Pull request by utkarshcmu**
Resolves #3271 & #3077.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
This PR is completed. Following are the changes:

1. Supports Opentsdb 2.2.
2. Supports Filters and tags both.
3. The old dashboards will work as they were working with tags even if they upgrade Opentsdb or Grafana.
4. If Opentsdb version 2.1 or lower is selected (by default), then no extra features of Opentsdb 2.2. will be displayed in QueryCtrl.
5. Added tips and primary checks to either use tags or filters. Both cannot be used together as Opentsdb ignores tags if sent with filters in the HTTP query.
6. Correct label formation with filters.

Please review and merge.

**Comment by utkarshcmu** [comment]
Any chances to get this merged soon? :)

**Comment by bobrik** [comment]
@utkarshcmu can you add some screenshots?

**Comment by utkarshcmu** [comment]
Here are some screenshots:

When we merge this PR into master and you build Grafana from master, you will see the following image when you edit your existing opentsdb datasource:
[By default opentsdb will point to "<=2.1" version like the following image]
screen shot 2016-02-13 at 1 24 28 pm

And on your queryCtrl, you will see all the 2.1 options as it is, for example:
screen shot 2016-02-13 at 1 24 43 pm


Now when you go again to edit your datasource and point it to opentsdb version 2.2 as in the following image:
screen shot 2016-02-13 at 1 25 09 pm
And then save it.

And go back again to your dashboard to any panel's queryCtrl, you will see Opentsdb 2.2 options added in QueryCtrl as following:
screen shot 2016-02-13 at 1 25 29 pm

Here you can see that we added FillPolicy and Filters support in the queryCtrl. We can use filters but when we are not using tags, both are mutually exclusive. So, for using filters, you may need to remove all the applied tags and apply filters.

**Comment by utkarshcmu** [comment]
This is a smooth upgrade with new features. In the next release tags support can be deprecated completely when Opentsdb removes supporting tags in its next version 2.3.

**Comment by bobrik** [comment]
:+1:

**Comment by utkarshcmu** [comment]
@torkelo Added required tests for this PR. Please review/merge. Thanks :)

**Comment by utkarshcmu** [comment]
Any chances to get this merged soon, before it get too different what we have in master? :)

**Comment by utkarshcmu** [comment]
Resolved conflicts and merged with Grafana master.

**Comment by utkarshcmu** [comment]
Closing in favor of #4138

**Comment by godfreyhe** [comment]
I expect a lot

**Comment by utkarshcmu** [comment]
@godfreyhe Please follow #4138 for updates :)

**Pull request closed without merging**
