### PR TITLE
DataTrails: Fixes heatmap 

### PR DESCRIPTION
**Pull request by torkelo**
https://github.com/grafana/grafana/pull/80170 broke the heatmap, the heatmap query after that change is missing the `format: heatmap`

Before:
Screenshot 2024-01-17 at 10 09 06

After:
Screenshot 2024-01-17 at 10 10 56

### CODE REVIEW

**Comment by torkelo** [comment]
@leeoniya I am setting unit to "s" (for seconds unit) but not getting any unit suffix on the y axis, is there a way to do that?

**Comment by leeoniya** [comment]
hmm, that heatmap doesnt look like it's de-accumulating properly. are you sure you have "Heatmap" selected in the query editor format? the `{{le}}` thing shouldn't be needed either.

see the y axis units here: https://nativehistogram.grafana-dev.net/d/dc5080b6-5d30-40cf-8e97-c0b82100cecb/histogram-demo?query=&orgId=1&var-container=compactor&var-route=All

**Comment by torkelo** [comment]
@leeoniya ah, good comment! I realized https://github.com/grafana/grafana/pull/80706 PR broke it by removing the format

**Review by leeoniya — APPROVED** [review]
did not test 🙈 , but lgtm 👍

**Pull request merged**
