### PR TITLE
Cassandra data source

### PR DESCRIPTION
**Pull request by pjta**
#9683 Support for cassandra data source

### CODE REVIEW

**Comment by torkelo** [comment]
Hi, Thanks for contributing to Grafana. 

This data source is not something we think should be built-in but should be an external plugin. We are still working on backend plugins however to enable datasources like this to be installed without requiring a fork of Grafana.

**Comment by pjta** [comment]
Hi Torkel,

Thanks for the answer. I think that plugguble backend datasources will be a great feature of Grafana.

I still will be glad if this PR is of any use for the future external Cassandra plugin. Or if it will be useful for those people who are impatient to have a Cassandra data source right now. (BTW, do you have an approximate estimates for when backend plugins are going to be supported?)

This is my first experience with Go, so the implementation might not be perfect. But it's working - my team is using it for about thee months already.

**Comment by bergquist** [comment]
Backend plugins are currently only our 4-8 roadmap. https://github.com/grafana/grafana/blob/master/ROADMAP.md 

This roadmap is not set in stone and might be updated in the future but I would say its very likely that backend plugins will stick to this schedule.

**Comment by bergquist** [comment]
We appreciate that you want to contribute back but I'm closing this since we won't merge it. Looking forward to helping you turn this into a plugin once we release initial support for backend plugins

**Comment by pjta** [comment]
ok bergquist. Thank you for the answer.

**Comment by discostur** [comment]
@pjta backend plugins are available for grafana for a long time ... do you think you can create a Cassandra datasource plugin from your old pull request?

**Pull request closed without merging**
