### PR TITLE
CloudWatch: Add additional Events metrics

### PR DESCRIPTION
**Pull request by LeonardoBoleli**
**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by LeonardoBoleli** [comment]
Thanks for advice, done!!

Em seg., 20 de mai. de 2024 às 10:42, Ida Štambuk ***@***.***>
escreveu:

**Comment by LeonardoBoleli** [comment]
image

guys, may you help me to sign in CLA? I've done all the steps right and apparently not worked...

**Comment by idastambuk** [comment]
Hi again @LeonardoBoleli, I was actually referring to the `EventSourceName` dimension at the bottom of the docs, that should be added in the `NamespaceDimensionKeysMap` in the metrics.go file. Sorry for the confusion!

**Comment by idastambuk** [comment]
> image
> 
> guys, may you help me to sign in CLA? I've done all the steps right and apparently not worked...

Hmm, can you double check that you've signed the CLA with the same Github user that submitted the PR? This is the error Im seeing from the CLA Assistant: 

> Leonardo Silva seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by LeonardoBoleli** [comment]
Did the commit on dimensions, thanks for advice and sorry for confusions!!

**Comment by LeonardoBoleli** [comment]
LeonardoSilva account is my enterprise account, i cant edit my emails, how i can remove this account link on this PR?

**Pull request closed without merging**
