### PR TITLE
Plugins: Standardize Golang enum naming convention

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**

Tidy up inside `pkg/plugins` by standardizing how enums are named.

For example:

```go
type FooBar string

const (
	FooBarSomething     FooBar = "something"
	FooBarSomethingElse FooBar = "somethingelse"
)
```

**Why do we need this feature?**

Consistency / clearer APIs

**Who is this feature for?**

Plugins Platform

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by marefr** [comment]
Make sense to me. Haven't found convention for this, but normally this is good if there's a chance of mixing up things/name-clashes in larger packages. If a package is small might give more context/be more expressed skipping the enum type name. So definitely on a case-by-case. Found some std lib examples:
- https://pkg.go.dev/log@go1.16.6#pkg-constants
- https://pkg.go.dev/net/http#pkg-constants
- https://pkg.go.dev/image/color#pkg-variables

I don't mind trying to standardize on this, but might want to ask @grafana/backend-platform what they think and/or whether to include something in https://github.com/grafana/grafana/blob/main/contribute/backend/style-guide.md.

**Review by andresmgot — APPROVED** [review]
Definitively more readable so :+1:

**Review by ryantxu — APPROVED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Review by xnyo — APPROVED** [review]
LGTM!

**Pull request merged**
