### PR TITLE
Devenv: Add compose block for elastic 8

### PR DESCRIPTION
**Pull request by torkelo**
Was the simpliest compose block I could get working. Is missing filebeat and metricbeat modules / config. Maybe someone can help me with that or add it later?

### CODE REVIEW

**Comment by svennergr** [comment]
I added those configurations and did some smaller changes in the `docker-compose.yaml`. Most interestingly the filebeat config in the elastic7 is not working with our grafana logs, as filebeat will only add logs with debug level labels as `lvl`:
e.g. 

```
include_lines: ['lvl=info']
```

I opened https://github.com/grafana/grafana/pull/55217 in order to fix this also for elastic7.

**Review by svennergr — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
@svennergr I am unable to start the compose, think the filebeat is causing an error 
> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/torkel/dev/grafana/data/log" to rootfs at "/var/log/grafana": mkdir /var/lib/docker/overlay2/3086a59ce5071c841f0321be6a839be93425b1246a071490798a1c2fb2a1a477/merged/var/log/grafana: read-only file system: unknown

**Comment by svennergr** [comment]
> @svennergr I am unable to start the compose, think the filebeat is causing an error

Oh that's interesting. Are you able to start the `elastic7` devenv? All I can think of is that your docker daemon is maybe not running as root?

**Comment by svennergr** [comment]
@torkelo I can confirm that the same happens on my Ubuntu machine:
```
ERROR: for filebeat7  Cannot start service filebeat7: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/sgrossmann/repos/grafana/data/log" to rootfs at "/var/log/grafana" caused: mkdir /var/lib/docker/overlay2/affca18ede02ce93d83a34858b07d97f806dfa591bf70dee60447ff50ae68e76/merged/var/log/grafana: read-only file system: unknown
```
I'll take another look tomorrow!

**Review by svennergr — COMMENTED** [review]
Just to remove the LGTM for now.

**Review by svennergr — CHANGES_REQUESTED** [review]
Sorry for the spam, but I want to remove the ✅ until the mount issue is solved.

**Comment by gabor** [comment]
hi @torkelo , we are trying to not have the version-number in the file-name, because now that we only support elastic7 and elastic8 the docker-files are basically the same. for the `elastic` devenv we do the same thing as the `grafana` devenv does with an env-file, so you can do:
`make devenv sources=elastic` (gives you elastic8, the default), or `make devenv sources=elastic elastic_version=7.10.2`.

but that one does not run the *-beats services, so... what do you think about the following plan?:
- we rename `elastic8` to `elastic-beats` in this PR, and do the same `elastic_version` trick as in the `elastic` devenv
- (afterwards, separate PR) we delete the `elastic7` and `elastic77` devenvs.

would this be ok for you?

**Comment by torkelo** [comment]
@gabor not sure I understand, if we support elastic7 don't we need those still? 

The point of the elastic8 docker-compose file is to get the metrics as well and kibana , maybe name it elasticstack ?

**Comment by gabor** [comment]
> @gabor not sure I understand, if we support elastic7 don't we need those still?

we do support them. well, there are two approaches:

A:
- when i want to run elastic8-devenv: `make devenv sources=elastic`
- when i want to run elastic7-devenv: `make devenv sources=elastic elastic_version=7.10.2`

B:
- when i want to run elastic8-devenv: `make devenv sources=elastic8`
- when i want to run elastic7-devenv: `make devenv sources=elastic7`

they both do the same at the end, it's more like an "user-interface" difference? currently we have `A`. 
we can also discuss this in a video-call, if you prefer to go that way 👍

**Comment by gabor** [comment]
> The point of the elastic8 docker-compose file is to get the metrics (beats) as well and kibana , maybe name it elasticstack ?

that's a good name 👍

**Comment by gabor** [comment]
@torkelo to summarize, i see two possible devenv-configs:

A:
two devenv-folders: `elastic` , `elasticstack`, you run them like:
- `make devenv sources=elastic` (elastic8 with fake data, minimal size)
- `make devenv sources=elastic elastic_version=7.10.2` (elastic7 with fake data, minimal size)
- `make devenv sources=elasticstack` (elastic8 with *-beats)
- `make devenv sources=elasticstack elastic_version=7.10.2` (elastic7 with *-beats)

or

B:
four devenv-folders: `elastic7`, `elastic8`, `elastic7stack`, `elastic8stack`, you run them like:
- `make devenv sources=elastic8`
- `make devenv sources=elastic7`
- `make devenv sources=elastic8stack`
- `make devenv sources=elastic7stack`

currently we are moving in the direction of [A], but i can see the value of [B] too.

**Comment by torkelo** [comment]
@gabor sure, no idea how to make all the config files work for both 7 and 8 though, or are they backward compatible?

**Comment by gabor** [comment]
@torkelo , we did the changes, could you please try it if it works on your computer? `make devenv sources=elasticstack` should be enough to run it with latest elastic version.

(you will of course need a datasource that has the correct index-name configured, `[metricbeat-]YYYY.MM.DD` and `[filebeat-]YYYY.MM.DD`, port 9200.

(we will work with @svennergr on cleaning up the `gdev` datasources afterwards to map nicely to these configs).

**Comment by torkelo** [comment]
@gabor nice!!

**Comment by torkelo** [comment]
@svennergr can you approve? It's working pretty well for me

**Comment by svennergr** [comment]
> @svennergr can you approve? It's working pretty well for me

Yep, I fixed the docker mount bug in https://github.com/grafana/grafana/pull/55214/commits/0ca652d0323bcc1d6a6ecafe0d1e796aeb67c058 and it worked for me as well 👍

**Review by svennergr — APPROVED** [review]

**Pull request merged**
