### PR TITLE
Bump to go-duck v0.1.0

### PR DESCRIPTION
**Pull request by samjewell**
This fixed ordering of the columns

**What is this feature, why do we need it?**

See https://github.com/scottlepp/go-duck/pull/14 for a description of the improvement we're including here

**Who is this feature for?**

Anyone who uses SQL Expressions. This is still an experimental feature, and only used by a very small number of instances.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by samjewell** [comment]
Please could someone merge this for me?

> You’re not [authorized](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) to merge this pull request

**Comment by mildwonkey** [comment]
@samjewell the blocker to merging this PR is probably the changelog check. It might work if you add the required label (no-changelog or add-to-changelog) and try again? (i will merge for you if that doesn't do it, but we need the check to pass before I do)

**Comment by samjewell** [comment]
Thanks @mildwonkey - I've addressed the changelog check.

I'm still not authorized to merge, so if anyone can do the honours that would be grand 🙏

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!

**Pull request merged**
