### PR TITLE
Explore: lookup datasource by name when present in legacy URLs

### PR DESCRIPTION
**Pull request by cwbriones**
**What is this feature?**

This adds another check when loading legacy compact URLs so that their datasources are resolved correctly.

**Why do we need this feature?**

It appears that in older versions of Grafana, certain explore URLs in the "compact" format could have their datasource set on non-mixed queries using the name of the datasource. Prior to https://github.com/grafana/grafana/pull/66286 (up to v10.0.x), these were handled correctly because explore would take no action on modifying the queries [unless their datasource fields were not all the same](https://github.com/grafana/grafana/blob/838cbf22da1a8df9d3a7ba3aa6a44d362dc3f4ac/public/app/features/explore/ExplorePaneContainer.tsx#L103-L107). Even if they were not, it would choose the datasource as set on the first query but retain the others to be treated as imported queries.

In Grafana 10.1.X this behavior changed to remove all queries whose `datasource` field was set and not equal to that of the root value. In particular, [the code assumes that if the field is set to a string then it is the datasource UID](https://github.com/grafana/grafana/blob/v10.2.5/public/app/features/explore/hooks/useStateSync/index.ts#L307-L310). Since it is instead the name in these URLs, the queries are removed by the filter.

By modifying the filter to allow the name these URLs work again correctly in the latest version of Grafana. Since the decision was made to continue supporting legacy URLs, it seems appropriate to fix this.

**Who is this feature for?**

This is likely most useful for long term users of Grafana who may have older explore URLs sprinkled in docs, code comments, or other tooling.

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gelicia** [comment]
Have a datasource with the uid `P6798F81BB5440721` and the name `gdev-graphite`

Tested with the following URLs , all work as expected

http://localhost:3000/explore?schemaVersion=1&panes={"rag":{"datasource":"gdev-graphite","queries":[{"refId":"A","datasource":{"type":"graphite","uid":"P6798F81BB5440721"}}],"range":{"from":"now-1h","to":"now"}}}&orgId=1

http://localhost:3000/explore?schemaVersion=1&panes={"rag":{"datasource":"P6798F81BB5440721","queries":[{"refId":"A","datasource":{"type":"graphite","uid":"P6798F81BB5440721"}}],"range":{"from":"now-1h","to":"now"}}}&orgId=1

http://localhost:3000/explore?schemaVersion=1&panes={"rag":{"datasource":"gdev-graphite","queries":[{"refId":"A"}],"range":{"from":"now-1h","to":"now"}}}&orgId=1

http://localhost:3000/explore?schemaVersion=1&panes={"rag":{"datasource":"P6798F81BB5440721","queries":[{"refId":"A"}],"range":{"from":"now-1h","to":"now"}}}&orgId=1

Note: Both org ID/name and org ID/UID are unique indexes on data_source
https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/datasource_mig.go#L68
https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/datasource_mig.go#L132

**Review by gelicia — APPROVED** [review]

**Comment by cwbriones** [comment]
@gelicia would you consider backporting this to 10.x? Is there a reason why that is not appropriate here?

**Comment by cwbriones** [comment]
> It can be backported to 10.4.x but you will need to create a manual backport because the code was moved around

Is it as simple as making another PR to merge into branch `v10.4.x` or is there a different procedure I should follow?

> Just for the context. How your URLs look like and how were they created? Are they just very old Explore URLs or they were generated with some tools? 

They're similar to this url on the `grafana` test datasource [http://localhost:3000/explore?orgId=1&left=["now-5m","now","grafana",{"datasource":"grafana","queryType":"measurements","refId":"A","channel":"plugin/testdata/random-2s-stream","filter":{"fields":["Time","Value"]}}]](http://localhost:3000/explore?orgId=1&left=%5B%22now-5m%22%2C%22now%22%2C%22grafana%22%2C%7B%22datasource%22%3A%22grafana%22%2C%22queryType%22%3A%22measurements%22%2C%22refId%22%3A%22A%22%2C%22channel%22%3A%22plugin%2Ftestdata%2Frandom-2s-stream%22%2C%22filter%22%3A%7B%22fields%22%3A%5B%22Time%22%2C%22Value%22%5D%7D%7D%5D)

To be honest I'm not entirely sure how they were created since some of these are years old (2020 or earlier). I suspect for the most part they were simply copy-pastes from explore and so they're just very old URLs.

**Comment by cwbriones** [comment]
If there's nothing else blocking this, could we get this merged so that I can work with the team to get it backported?

**Pull request merged**
