### PR TITLE
Panel: Keyboard focus shortcuts prioritization

### LINKED ISSUE #47005: Inconsistent keyboard behaviour when interacting with panel
Grafana has recently added the ability to navigate through panels in a dashboard using the keyboard, which is amazing! However, I have noticed that this behaviour can be somewhat inconsistent.

I'm aware that this is a relatively new feature, and is a part of https://github.com/grafana/grafana/issues/36776. I'm not sure if this is covered in that card.

**Steps to reproduce**:
Use the keyboard to navigate to panels in your Grafana dashboard. Attempt to edit or view the panels currently selected by keyboard focus by pressing the 'e' or 'v' keys.

**Actual Result**:
The result I'm seeing is varying a lot. Sometimes nothing happens, other times it loads a panel that I don't currently have keyboard access to.

In the video below, you can see me using my keyboard (by pressing 'tab') to navigate to the panels, with keyboard focus on each panel I am pressing both 'e' and 'v', with nothing happening. Around the 20 second mark, I use my mouse pointer to click on the `status history with time series` panel, which then allows me to use 'e' and 'v' for that panel. However, if I change my keyboard focus to one of the other panels, I am still redirected to the `status history with time series` panel, regardless of where my keyboard focus is.

https://user-images.githubusercontent.com/63413067/160582407-2ab89360-4fda-479a-9d70-a7e28abe2a54.mp4

**Expected Result**:
By pressing 'e' or 'v' I'd be able to edit or view the panel which my keyboard is currently focussed on.

**Relevant WCAG Criteria**:
 [2.1.1 keyboard](https://www.w3.org/TR/WCAG21/#keyboard)

**Environment**:
I am using https://play.grafana.org/ (on 29/03/2022)
- Grafana version: 8.4.4 (fcfb01fae)
- User OS & Browser: Windows 11 + Microsoft Edge

### PR DESCRIPTION
**Pull request by tskarhed**
**What is this feature?**

If a panel (or its children) is in focus, that panel shortcut will take effect rather than wherever the mouse is.

**Why do we need this feature?**

It causes very confusing behaviour for keyboard users.

**Who is this feature for?**

Keyboard users

**Which issue(s) does this PR fix?**:

Fixes #47005
Solves number 4 in #79627

**Special notes for your reviewer:**
Are there any cases where these bindings may override panel interaction?

Test by (and compare)

1. Tab focus a panel
2. Hold the mouse over another panel
3. Press any of the panel shortcuts (e or v)
4. The focused panel should change view

Without keyboard focus:
1. Make sure there is not a panel in focus
2. Hold the mouse over a panel
3. Press any of the panel shortcuts (e or v)
4. The hovered panel should change view

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Great work @tskarhed 🏅 , the code looks good to me. I was testing it with the old dashboard architecture and works as expected. 

As we discussed, we just the implementation in the new one. I am leaving the link to the file just for future reference https://github.com/grafana/grafana/blob/panel-focus-shortcut/public/app/features/dashboard-scene/scene/keyboardShortcuts.ts#L146

**Review by axelavargas — APPROVED** [review]
🥳 works as expected in dashbaords scene architecture :)

**Comment by ckbedwell** [comment]
This is great but I did want to highlight that there is one aspect of it that doesn't work as expected:

If you click a panel then hover a different panel, the clicked panel receives the keyboard shortcut as that is actually what currently has focus but there is no visual indicator for it. If you click a non-panel element the hover aspect works again as no panels have non-visible focus.

I wonder if there's a further ticket so that we show the focus indicator on panels with `:focus` and not just `:focus-visible`? 🤔

**Comment by tskarhed** [comment]
I see the problem, kinda the opposite of the issue that was solved. We can either do that with the focus (maybe it might be a bit intrusive?) or we can disregard anything that isn't `:focus-visible`

**Pull request merged**
