### PR TITLE
Authn: ensure Grafana Admin are Admin in all Orgs

### LINKED ISSUE #78582: GrafanaAdmin should be made Admin in all Orgs
**Why is this needed**:

By default, a user Server Admin is only admin in the default Org.

**What would you like to be added**:

Adding an option which, when enabled, will add Admin Role in all Orgs when a user is logged as GrafanaAdmin.

Proposal: https://github.com/grafana/grafana/pull/78560

**Who is this feature for?**

Users with multiple orgs

### PR DESCRIPTION
**Pull request by sathieu**
**What is this feature?**

Before this PR, GrafanaAdmins were not Admin in Orgs.

NB: This is a behavior change. Maybe some users depend on the previous behavior.

**Why do we need this feature?**

This is particularly useful when `role_attribute_path` config (for Oauth or others) returns GrafanaAdmin.

**Who is this feature for?**

Users with multiple orgs

**Which issue(s) does this PR fix?**:

Fixes #78582

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by sathieu** [comment]
OK. I created https://github.com/grafana/grafana/issues/78582.

I'll gate this behind an option (disabled by default)

**Comment by kalleep** [comment]
Thanks, will take this up with the team and we will discuss if we want to move forward with this :)

**Comment by sathieu** [comment]
@kalleep Have you talked to the team about this PR?

I've rewritten it to be behind a boolean setting `grafana_admin_to_org_admins = true`.

See https://github.com/sathieu/grafana/pull/1/commits/613199e47e634823ca220ebff71d6fec75a7a86b.

**Comment by sathieu** [comment]
(force-pushed 869a97d3312 to branch)

**Pull request closed without merging**
