### PR TITLE
Add 95Pctl reducer so it can be shown in Legend

### PR DESCRIPTION
**Pull request by simPod**
**What this PR does / why we need it**:

I tried to readdress displaying pctl95 in Legend. 

The original argument against https://github.com/grafana/grafana/pull/6054 was

> tricky, as most time series queries apply some form of aggregation (avg for example), doing percentiles on aggregated data can be very misleading. This is better done in the metric query.

> Max, mean , avg works great and can be accurate, just need to match the aggregation used in the query.

That does not stand since Max, mean , avg are accurate exactly in the same way as percentile - calculated not from raw data but from data in panel so it behaves exactly the same.

That said `Max, mean , avg works great and can be accurate` implies that also pctl95 can be accurate. Also it means that max, mean, avg and pctl95 can be inaccurate. 

_See [following replies in the thread](https://github.com/grafana/grafana/issues/6053#issuecomment-780878242) that support my logic here._

**Which issue(s) this PR fixes**:

https://github.com/grafana/grafana/issues/6053

### CODE REVIEW

**Comment by torkelo** [comment]
> That does not stand since Max, mean , avg are accurate exactly in the same way as percentile - calculated not from raw data but from data in panel so it behaves exactly the same.

What I mean is that if your query has a max aggregation function, then max in legend will always be correct. If your query has a min aggregation method then min in legend values will be correct. But you cannot aggregate your data using a percentile calculation. So the legend p95 value will never be correct if there is any query aggregation used (Which the vast majority of queries use).

**Comment by simPod** [comment]
> if your query has a max aggregation function

Do you mean like if the values returned from datasource are max? Or what do you mean by that? If I query for max-aggregated data, no other aggregation will be "correct".

> But you cannot aggregate your data using a percentile

Not sure what you mean by that? Why cannot I aggregate it using a percentile?

@torkelo I kind of get your point but it is not true. It is simply responsibility of the user to know what values are provided and therefore are precise or approximate in the legend.

**Comment by simPod** [comment]
I see your point now. But when I return max aggregations I cannot expect `min` in legend to be correct either.

Personally, I use a Grafana fork where I have this implemented and works as intended -> Query returns non-aggregated timeseries data and I can compute aggregations in legend for several metrics (`max`, `min`, `pctl`) out of that.

There were a lot of users (as per linked issue) that wanted to do the same but `pctl` was not available while e.g. `min` is available. We also cannot min on max over time which is something totally different as well.

The issue is in aggregating aggregations which basically works like never. If user does that he must bear the results.

**Comment by torkelo** [comment]
> I see your point now. But when I return max aggregations I cannot expect min in legend to be correct either.

Well obviously

> Query returns non-aggregated timeseries data

For most databases Grafana supports there is a group by time (interval aggregation) so you can view different time regions without requesting a million data points, so having queries that return raw data points always no matter time range is very rare / not recommended. 

If you want the p95 I would recomend putting this in a different panel beside the graph. If you do not want to duplicate the query you can reuse the same query result, then add the histogram transform to view a complete histogram for the data

**Comment by simPod** [comment]
We do sum over time and let legend do aggregations over that. E.g. pctl is more valuable than max as it filters out outliers. 
I believe many other users could benefit it the similar way.

That said, there's no math-based argument to prefer one aggregation over the other.

**Comment by torkelo** [comment]
Not sure what you mean sum over time, if you do sum aggregation in the query , the percentile will be on those summed values? Sounds strange.

**Comment by simPod** [comment]
Yes, we sum bytes per 5m buckets. If the timerange is too wide, we respect Grafana's interval and average those buckets. Then we always have P95 in legend even for those averages. We know that values in legend are aggregation of aggregation so not precise but close enough.

**Comment by torkelo** [comment]
Not sure i understand , you sum by 5m, and then average by time when does interval? Then p95 on those values, how can that be accurate?

**Comment by simPod** [comment]
It is not accurate. It's approximate – same as is e.g. `max` or `min`. Since data must be aggregated per Grafana interval variable (`avg`), real peaks disappears so `max` is not accurate, it's approximate in the same way as `p95` is.

**Comment by torkelo** [comment]
> Since data must be aggregated per Grafana interval variable (avg), 

Grafana never aggregates by interval variable, and that is not set by default to avg. That is all handled by the query and whatever query aggregation is used. 

> t is not accurate. It's approximate – same as is e.g. max or min

No it's not, you can use min or max aggregation in your interval query aggregation as well so they are 100% correct, always, no matter the time range. 

-------------

a p95 on summed values (per 5min), then averaged based on some dynamic time window is not approximate, but just wrong. 

Percentile calculations on any aggregated data are always wrong, as to do percentile calculations correctly you need to know the number of original measurements. You can aggregate (sum) pre-buckeded data (which are just counts in different value range buckets) and then interpolate a percentile (This is what prometheus does).

**Comment by simPod** [comment]
> Grafana never aggregates by interval variable, and that is not set by default to avg.

I know, those were all just examples in reaction to your statement `without requesting a million data points, so having queries that return raw data points always no matter time range is very rare / not recommended.`.

Those are all things grafana users do in real world. We aggregate data using some function so there are no million data points. And sometimes we also incorporate interval variable, depending on the timerange size.

> No it's not, you can use min or max aggregation in your interval query aggregation as well so they can be 100% correct, always, no matter the time range.

I don't understand. If I aggregate query data
- by `avg`, `min` and `max` metrics won't be correct, since avg will smooth out extremes. Averaging these two buckets `[0,10], [4,6]` (imagine there are million of datapoints)  gives `[5, 5]` where max and min are `5` even though when evaluating underlying million of datapoints, it should be `0` and `10`. Min and max are therefore "wrong".
- by `max`, `min` and `avg` metrics won't be correct.

So I don't really see how to make aggregation of aggregation the same. Unless you're talking about doing max aggregation of max aggregation, but that's very narrow use-case, we use several aggregations in legend, not just one.

> Percentile calculations on any aggregated data are always wrong

Similar to max calcs on avg-aggregated data as shown above.  🤷🏾‍♀️  
I know how percentile is to be calculated but we can't do that without taking those million data points into account. 

But still, other metrics have similar problem.

**Comment by torkelo** [comment]
Not sure how you can be misunderstanding me :( 

If you use max aggregation in the query then max will be 100% correct in legend values. You should almost never have more than one legend value in the legend at the same time (as only 1 can be accurate at a time).

> we use several aggregations in legend, not just one.

This is not recommended if you are dealing with aggregated data in the query. 

> But still, other metrics have similar problem.

No they don't. You can write a query that does aggregation and get correct Min. Max. Avg etc in legend (not at the same time), but you cannot do the same for p95!

**Comment by torkelo** [comment]
Yea that is a good point, if your not interested in actual p9 , but just the p95 shown in in the graph then my concerns are not valid. Wondering if this is not best solved with a transform and another panel beside graph showing percentiles? With a transform we can have options in what exact percentiles to calculate. You can use the dashboard data source to share the query results of the main graph

**Comment by simPod** [comment]
> we can have options in what exact percentiles to calculate

this would be nice though we and other users preferred to have aggregations next to the series name in legend. But yes, it is not very flexible for `n` in `P_n`.

--------

I guess the way we use legend is not a way Grafana intends it to be used so the PR is invalid. And people who want to use it the same way as I do will have to use the patch.

**Comment by joshhunt** [comment]
Hey @simPod - based on the conversation here (and similar ones in the previous issues and PRs) we're not going to merge this one. To summarize:

 - Providing 95th percentile of the time series data you often get in Grafana could be misleading to consumers of the panel that might not be immediately obvious - we think this could be too big of a "footgun" to introduce.
 - _95th_ Percentile is a common, but somewhat arbitrary percentile. Users that want 90th or 98th could not be served by this (and we don't add arguments to reducers like these), and are instead better served by separate queries, transforms, or panels.

Thanks for the contribution and the healthy discussion about the feature. We hope to see future issues raised and contributions.

**Comment by gonchik** [comment]
Do you have any other workarounds?

**Pull request closed without merging**
