### PR TITLE
Logs: Support implicit reset codes for ANSI coloring 

### LINKED ISSUE #35166: Grafana is showing the ANSI reset code 'ESC[m' in logs view
**What happened**: Grafana is showing the ANSI reset code 'ESC[m' in logs view.

**What you expected to happen**: The 'ESC[m' is hidden and interpreted as reset code.

**How to reproduce it (as minimally and precisely as possible)**: View a log like the following in Grafana:
```
[1;30m[2021-05-31 19:12:27.976][m[32m[ INFO][m[35m[10][m[34;1m[][m[32;1m[][m[33;1m[][m[30m[blablabla runner][m[36m[blablabla=>blabla$blabla$1][m[Starting service for blabla... ],815416643a099f0150f01c4c120f139c_A,NaN
```

Note that the `ESC` char is represented with `` in the above log.

Colored log with ANSI reset code shown

We can see that only the reset coloring codes (`ESC[m`) are those that are not well printed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Loki and Promtail 2.2.0
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10 & Chrome Latest
- Grafana plugins: default plugins
- Others:

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

[ansicolor.ts](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/utils/ansicolor.ts) was a copy from https://github.com/xpl/ansicolor with added types. The latest version of aniscolor has TS types and [the fix for escaping](https://github.com/xpl/ansicolor/pull/15) so we can use it as an npm dependency now.

**Which issue(s) this PR fixes**:

Fixes #35166

**Special notes for your reviewer**:

How to test it? Ingest a line provided in the example in #35166. It should render as in the example [here](https://github.com/grafana/grafana/issues/35166#issuecomment-863986696).

ansicolor was part of public grafana-ui API, but after this change it won't show up in [docs](https://grafana.com/docs/grafana/latest/packages_api/ui/ansicolor/).

### CODE REVIEW

**Review by mckn — APPROVED** [review]
Great work with this!

**Review by ivanahuckova — APPROVED** [review]
LGTM. 🚀 

Btw you have currently selected backport to 7.5.x branch which I think (based on milestone) should be 8.0.x branch.

**Comment by ifrost** [comment]
> LGTM. 🚀
> 
> Btw you have currently selected backport to 7.5.x branch which I think (based on milestone) should be 8.0.x branch.

Oh, good point @ivanahuckova, thanks! I was actually thinking about back porting it to both 7.5.x and 8.0.x. Do you think it makes sense or should it be in only in 8.0.x?

**Comment by ivanahuckova** [comment]
I think that 8.0.x is enough. Not sure if we will do more 7.5.x releases as there are no security issues/critically breaking bugs.

**Comment by ifrost** [comment]
> I think that 8.0.x is enough. Not sure if we will do more 7.5.x releases as there are no security issues/critically breaking bugs.

Makes sense! Actually it can probably go out with 8.1.0 :)

**Pull request merged**
