### PR TITLE
Plugins: Add support for fetching plugin includes from plugin CDN

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**

Reworks some existing logic to make it possible to load nested plugins from the CDN.

For example if `foobar-app` includes a panel `foobar-panel`, all that is necessary is the following*:

```ini
[plugin.foobar-app]
cdn = true
```

*the app plugin must exist on the CDN and have the panel listed in its `includes` in the plugin.json

**Why do we need this feature?**

Enables us to make use of more plugins on the CDN.

**Who is this feature for?**

Plugins Platform.

**Special notes for your reviewer:**
Enterprise changes: https://github.com/grafana/grafana-enterprise/pull/6846/files

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Review by andresmgot — APPROVED** [review]
LGTM

**Review by xnyo — APPROVED** [review]
LGTM, awesome work! :raised_hands:

**Pull request merged**
