### PR TITLE
Gradually remove Macaron web framework

### PR DESCRIPTION
**Pull request by zserge**
This PR embeds a small subset of Macaron web framework, that Grafana actually uses into `pkg/macaron`.

From here we can start:

* rewriting middleware to be compatible with `http.Handler`
* rewriting handlers to use `context.Context` and helper functions instead of `macaron.Context`
* removing parts of macaron API that are barely used (as usual, 80% of the APIs are used in 20% of the handlers and vice versa), we can trim macaron APIs significantly.

Please consult "Replacing Macaron" design doc for more details.

### CODE REVIEW

**Comment by torkelo** [comment]
Nice!

**Comment by zserge** [comment]
Working on a design doc for it now. But this approach looks way more promising than "stop-the-world" and "rewrite all middleware and handlers overnight".

We only have ~1800 lines of code remained from Macaron and all its dependencies. Now we can slowly move to net/http.HandlerFunc everywhere and start using Context everywhere. Once done - we can replace this package with any other HTTP router and get a performance boost, as well as type safety.

**Comment by bergquist** [comment]
image

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
