### PR TITLE
Loki: Fix query error for step parameter

### PR DESCRIPTION
**Pull request by davkal**
- Loki does not fully support float steps like prometheus and returns a
query error
- this change makes sure that the step parameter is rounded to an
integer

### CODE REVIEW

**Comment by marefr** [comment]
@davkal sounds like Grafana 6.5 material?

**Review by cyriltovena — APPROVED** [review]
LGTM,

We want to fix this btw ! I was waiting on this https://github.com/grafana/loki/pull/1211

**Review by aocenas — APPROVED** [review]
Makes sense though I am not sure how to simulate any error, tried playing with max data points and range in a panel but no luck. Also would it make sense to have a test for this?

**Comment by davkal** [comment]
@marefr not for 6.5, the new API paths that produce this error are not part of 6.5.

Adding a test....

**Comment by davkal** [comment]
Hmm, something went wrong with git. New PR: #20607

**Pull request closed without merging**
