### PR TITLE
Implemented OR condition in alerting queries!

### LINKED ISSUE #6438: Alerting: Support OR condition in alerts
Currently, we evaluate alert conditions with AND operators only. So, the alert is sent only when all conditions are met. If I need to send alerts if any of the condition is met, I should have an OR operator as a choice with the AND operator.

### PR DESCRIPTION
**Pull request by utkarshcmu**
Resolves #6438

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Please review & merge! Thanks!

**Comment by utkarshcmu** [comment]
Can this PR make to 4.0.0-beta2?

**Comment by torkelo** [comment]
so this allows mixing OR and AND?

**Comment by utkarshcmu** [comment]
Yes, we can have both OR and AND between the conditions and the end result will be calculated in a serial manner. I have added example in the docs as well and a few tests too.

**Comment by torkelo** [comment]
I think if we allow mixing we need a way to visualize how it works in the UI, which is a bit tricky I guess

**Comment by utkarshcmu** [comment]
In the UI, it is very evident that we have conditions one after another and we have operator (either OR or AND) between them. So that is very clear to the users.

The tricky part is how to make it clear that the condition evaluation will happen serially. I am trying to come up with some ideas but if we want a quick solution then a tooltip near the word "Conditions" in alert_tab might be a quick way to let users know the evaluation method.

**Comment by utkarshcmu** [comment]
When someone tests the rule, one can see how Grafana evaluates the conditions with respective operators. Two previews one with round brackets and other with square:

screen shot 2016-11-17 at 12 55 25 am

screen shot 2016-11-17 at 12 55 48 am

What do you guys think about this? If it looks OK, I can add this functionality to the PR!

**Comment by torkelo** [comment]
@utkarshcmu that looks really great!

**Comment by utkarshcmu** [comment]
@torkelo Added the firingEvaluation string as show above in the screenshots. Added tests as well.
Please review, test & merge. Thanks :)

**Comment by torkelo** [comment]
merged!

**Pull request merged**
