### PR TITLE
Input: Prevents alpha numeric chars in number inputs

### LINKED ISSUE #29207: Grafana/ui: Input type="number" should consider various browser implementations
**What happened**:
Issue #28487 has highlighted that Firefox and Safari allow a user to type any character into an `input[type="number"]` field rather than Chromes approach of limiting numeric character input. If a browser doesn't enforce numeric input the user can be left confused as currently there is no visual feedback or implementation alignment.

**What you expected to happen**:
If a user inputs invalid characters into a numeric field they should either be blocked from entering such values or the input should reflect an invalid state to indicate something is wrong.

**How to reproduce it (as minimally and precisely as possible)**:
In Firefox open the panel editor, then in Query Options type alphanumeric characters into Max Data Points.

**Environment**:
- Grafana version: Grafana v7.3.3 (2489dc4d3a)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Mac OS X Firefox and Mac OS X Safari
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Alternative solution to #29558, needs lots of testing I guess. But it works on MacOS:
image

with Browsers:
image
image
image

**Which issue(s) this PR fixes**:
Fixes #29207

**Special notes for your reviewer**:
This doesn't currently handle decimals in inputs. For that we would need to use onInput instead and things get more complicated.

### CODE REVIEW

**Comment by hugohaggmark** [comment]
@jackw @dprokop if you think this solution is a better way forward than #29558 I think we should close that one.

**Comment by hugohaggmark** [comment]
Any feedback @jackw or @dprokop? As this doesn't solve decimals, I'm tempted to improve this by using `onInput` instead of `onBeforeInput`.

**Comment by lionbee** [comment]
I am new to the Grafana source code, and from what I can see Alerting is using Angular, so this change won't affect that. Making `type='number'` behave in this manner could have unexpected side effects. As you already pointed out this does not handle decimals, but it also does not handle exponentials like `1e5`.

In Chromium it is currently possible to enter an invalid number into an input field of type number by entering a number that ends with `e`.

**Comment by hugohaggmark** [comment]
> I am new to the Grafana source code, and from what I can see Alerting is using Angular, so this change won't affect that. Making `type='number'` behave in this manner could have unexpected side effects. As you already pointed out this does not handle decimals, but it also does not handle exponentials like `1e5`.
> 
> In Chromium it is currently possible to enter an invalid number into an input field of type number by entering a number that ends with `e`.

Great input, yeah, exponentials and decimals could be handled by moving this to `onInput` instead. Regarding Angular, this change is just for the React Input components.

**Comment by lionbee** [comment]
I was considering filtering out invalid keypresses with onKeyPress and then bumped into this issue with the exponentials. the rules around number fields seem simple, but coding it can be challenging since `event.currentTarget.value`will return nothing for invalid input, even though the input field is populated. You could maintain the value in state and use that for validation OR use `ref` to change the input type to text to read the current value (that seems a bit ugly though)

- all digits are allowed
- maximum one decimal
- maximim one `e`
- decimal in any location, except after `e`
- `e` not at the beginning

`e` at the end will always have to be a silent failure

**Comment by dprokop** [comment]
Min/Max input in test ds does not accept speciach characters (-)

**Comment by hugohaggmark** [comment]
I've concluded that we would need a parser/tokenizer to solve this in a perfect way. So I'm going to close this PR now.

**Pull request closed without merging**
