### PR TITLE
Adding Marcus to Hall of Fame and updating codeowners

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What is this feature?**

Fixing codeowners and adding Marcus to the hall of fame

### CODE REVIEW

**Review by xnyo — APPROVED** [review]
LGTM :cry: :heart:

**Comment by moxious** [comment]
LGTM 😢 ❤️

**Review by wbrowne — APPROVED** [review]
❤️

**Review by andresmgot — APPROVED** [review]
🌟

**Comment by marefr** [comment]
❤️

**Pull request merged**
