### PR TITLE
DashboardScene: Fix explore to dashboard flow

### LINKED ISSUE #85139: Explore to dashboard: Does not work with scenes based architecture
The flow od adding a panel from Explore to a Dashboard is not working.

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/85139

This brings a possibility to add a panel to a dashboard from Explore.

Since new and old arch use different `fetchDashboard` methods, I had to add `keepDashboardFromExploreInLocalStorage` property to the one that's gonna be primary when we remove old code.

 It's required as `DashboardPageProxy` pre-fetches dashboard using `DashboardScenePageStateManager.fetchDashboard`, but then `initDashboard` thunk has it's own implementation. So for the old architecture to work we don't want to clear the local storage until the old arch code is executed.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good ,maybe a unit test in dashboard scene state manager unit tests ?

**Review by gelicia — APPROVED** [review]

**Review by gelicia — CHANGES_REQUESTED** [review]
Wondering where the "save" option is here

1. create a random walk in Explore
2. Add > Add to Dashboard
3. Select Existing dashboard, select any dashboard, hit open either in a new tab or not
4. On not-scenes, there's a save icon here indicating the user can save with the new panel added. On scenes, it's not obvious what to select. When adding to a new dashboard with scenes there is an obvious save dashboard button.

**Comment by dprokop** [comment]
@gelicia  / @torkelo  - pushed some updates to address Kristina's comment, please re-review.

**Review by gelicia — CHANGES_REQUESTED** [review]
1. Follow steps for adding to an existing dashboard from explore - new tab or not does not matter
2. Get to new dashboard and note the save button. Hit "Exit edit" then "Discard" 
3. New panel still shows, when dialog indicates changes would be discarded

There is no equivalent button to "Exit edit" in the non-scenes scenario, nor in the scenes add to new dashboard scenario.

**Comment by dprokop** [comment]
Thanks @gelicia, fixing this is kind of trickier than I thought. Will take me a bit more to get landed an update.

**Comment by dprokop** [comment]
@gelicia  - i need to add some tests to my latest commit, but the flow that you have identified as buggy should now be fixed, please have a look one more time :)

**Review by gelicia — APPROVED** [review]
Functionality and code look good!

**Pull request merged**
