### PR TITLE
Navigation: add explore button to new topnav

### PR DESCRIPTION
**Pull request by fionera**
**What is this feature?**

Add a button to link to Explore
Screenshot 2022-12-09 at 02 08 06

**Why do we need this feature?**

In the new Nav it requires multiple clicks to start exploring data. With this its a single click to that area.

**Who is this feature for?**

-

**Which issue(s) does this PR fix?**:

-

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
not sure about this, there is too many buttons there already.

**Comment by mxey** [comment]
> not sure about this, there is too many buttons there already.

That might be a problem with the new design. But with the old design, Explore was only ever one click away.

**Comment by torkelo** [comment]
@mxey yes, but as Grafana grows and adds more pages and sections, everything cannot be a single click away 

But I think it could make sense to allow some customization of the top right icons, so a user can specify if they want "Quick Add, News, Help" and other app icons there. (and remove news or help if they don't want them)

**Comment by torkelo** [comment]
Closing this for now, can you open a feature request for customizing options that allow users to add apps/features to the top nav?

**Pull request closed without merging**
