### PR TITLE
VariableEditor: Use new form styles

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Uses new form styles with the variable editor as part of [ongoing UI/UX improvements](https://github.com/grafana/grafana/issues/52832)

**Which issue(s) this PR fixes**:
See #52832

**Special notes for your reviewer**:
I put this together while not feeling 100%, so I apologize if there are any obvious mistakes 😅

### CODE REVIEW

**Comment by torkelo** [comment]
Nice!! It's a good start from which we can tweak layout and change the workflow later, to make type and data source selection more deliberate and upfront for new variables.

I took this for a spin but not seeing the variable query editor change when I change data source, each data source has different query editors but nothing happens after data source change.

**Comment by kaydelaney** [comment]
> I took this for a spin but not seeing the variable query editor change when I change data source, each data source has different query editors but nothing happens after data source change.

Hmm, strange. Seems to be working for me. Is it working now with the changes I just pushed?

**Comment by dprokop** [comment]
Nice! @Ijin08 - would be worth using your eye to spot some spacing inconsistencies, i.e. between different query editors and preview modes :)

**Review by polibb — COMMENTED** [review]
Hey @kaydelaney 💭, the order of the fields in the new design is great - it's much easier to distinguish where one's at when creating a new variable. 

1 (Nit) Suggestion: I like the slimmer big fields as well, though why don't we have the Description, Query, and Regex larger fields all of the same length? Maybe Query is easier to read in a long horizontal space like this indeed, but it also creates the illusion that Description and Regex are also two different lengths.

2 Suggestion: More space between the subtitles and their respective previous subsection. 
For example this:
image 
vs. this:
image

It seems the upper section is always closer to the subtitles' own subsection. 
Especially visible when having a preview of values:
image


3 Suggestion: Keep the placeholders the same - either all start with capital letter, or none of them. 
image

Love the descriptions under each variable type in the list of types! Also, much better "Show on dashboard" options than "Hide" dropdown 😊.

**Review by polibb — APPROVED** [review]
Looks good to go to me ⛷! 
There's this [new-query-variable.spec.ts](https://drone.grafana.net/grafana/grafana/82902/3/15) failing the build, probably because of "Descriptive text" vs. "descriptive text" (?).

**Pull request merged**
