### PR TITLE
RabbitMQ Notifier

### PR DESCRIPTION
**Pull request by RichardGreen-IS2**
Added a new RabbitMQ notifier which will publish the notification for alerts to a specified exchange. 

Added UI for configuration of the notifier which allows the RabbitMQ Host, Username, Password, VHost and Exchange to be specified.

The notifier requires the RabbitMQ REST API to be enabled and uses SendWebhookSync internall to post to RabbitMQ. 

Tests are provided for the configuration options required by the notifier.

### CODE REVIEW

**Comment by envintus** [comment]
Would be great if there was a way to configure properties of a Grafana alert prior to the message being published to a queue. This could be useful for monitoring applications, like Sensu that natively support pub/sub.

**Comment by torkelo** [comment]
Thank you for contributing to Grafana. 

Can you open a feature request issue for this? Want to see if there is any interest in this before any possible merge.

**Comment by richard-green** [comment]
I honestly cannot comprehend that a fellow developer, also called Richard Green, is working on RabbitMQ and using Grafana like I am. I mean, what are the odds??

**Comment by torkelo** [comment]
Yes, that seems very improbable, I think he is you from an alternate dimension :)

**Comment by torkelo** [comment]
can you open a feature request for this, want to see if this is something more than a few users actually will use

**Pull request closed without merging**
