### PR TITLE
Add support for OpenTSDB metrics with multi-value variables

### PR DESCRIPTION
**Pull request by Maxime999**
This PR adds support for multi-value variables in metrics for OpenTSDB datasource.
It has been discussed in issue #7754

### CODE REVIEW

**Comment by pfalgowski** [comment]
Hello,

Any plans to merge the PR to the master?

**Comment by pfalgowski** [comment]
Variables in format {[[var]]} or {$var} are only expanded in metric field. 

example:
Metric: {[[device]]}/ifHCIOctets_ifHCIOctets
Tags: key:Devices/{[[device]]}/os/interfaces/P1
variable $device = server1|server2

It ends up in with query where key is in format: Devices/server1|server2/os/interfaces/P1
where it would be nice if it will be expanded as well.

**Comment by Maxime999** [comment]
Hi,
I see your point, multi-valued variables are only processed in the metric name. Adding support for tag keys would make sense.
Sadly I don’t have access to an OpenTSDB Grafana instance anymore so I won’t be able to do these changes right now, let alone test them. The current patch was extensively tested and is running on our production servers though.

**Comment by torkelo** [comment]
This is not how the templating system should be used. It's only for string interpolation. If you need to later then parse and split the result of a multi-valued variable something is wrong. 

Sorry, will close this. To support use cases like this there there the TSDB query language has no native string based multi-valued syntax requires a more fundamental change to Grafan (or to the TSDB query api) .

**Pull request closed without merging**
