### PR TITLE
[v8.5.x] Chore: Update slate and related packages (#54566)

### PR DESCRIPTION
**Pull request by kaydelaney**
Backport a70aba1384d9c4ce4735d3a0e855020bab2b5d4f from #54566

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
lgtm, great job as always @kaydelaney  🙌

**Comment by rrva** [comment]
this would be great to get docker images for

**Comment by markmsmith** [comment]
Is there an `8.5.12` release somewhere with this fix?  I don't see it in the releases page:  
https://github.com/grafana/grafana/releases  
and I only see an `8.5.13` in progress on the milestones page, so I'm not sure if I'm missing something:  
https://github.com/grafana/grafana/milestones?state=open  

We're eager to upgrade to the latest 8.5.x release, since this issue is impacting our users.  
I really appreciate how fast this was back-ported!, now I'm just trying to figure out how best to pick it up.

**Comment by avg07** [comment]
Image [8.5.13](https://hub.docker.com/layers/grafana/grafana/8.5.13/images/sha256-e50578a25326b1b443fce526dca3b2d447ae02dfaea7a4f1f52235c6f8336057?context=explore) solves the problem!

**Comment by markmsmith** [comment]
Awesome, thank you!

**Pull request merged**
