### PR TITLE
[Bug Fix] Opentsdb Alias issue

### LINKED ISSUE #1876: Improve OpenTSDB query to series matching using new OpenTSDB 2.2 show_query feature
When you use pipe to specify more than one possible value for tags in openTSDB backend, the Alias feature breaks. It seens grafana is no longe able to match queries with it's results.

For example, you add a tag "host"  = "host1|host2". This will result in 2 timeseries, but the Alias you specify will not be applied. It does work when using a single value or *

### PR DESCRIPTION
**Pull request by utkarshcmu**
Fixes #1876 
Rebased with master.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Please review/merge. Thanks !!!

**Comment by utkarshcmu** [comment]
Should I make this PR point development branch?

**Comment by utkarshcmu** [comment]
Can this make to 3.0.0, its a huge fix for Opentsdb users? :)

**Comment by utkarshcmu** [comment]
Is this PR a good fit for 3.0.2 or 3.1.0?

**Comment by mattttt** [comment]
Received another request to get this merged!  It would make @bobrik happy. 😄

**Comment by utkarshcmu** [comment]
And it will make other OpenTSDB users happy as well. :)

**Comment by bergquist** [comment]
@utkarshcmu not sure if this should go into master or development.

**Comment by utkarshcmu** [comment]
So, how should we make this bug fixing PR to reach Grafana's opentsdb users,  as the alias issue has been prolonged now since over a year now? May be @torkelo can tell us the right way to merge this PR or make any changes if needed. :)

**Comment by bobrik** [comment]
I can remove links to this issue from my graphs 🎉

**Comment by utkarshcmu** [comment]
@torkelo Thanks for merging this PR. 👍

**Comment by rajeshksv** [comment]
[Not sure, if this is right place to raise the issue. Kindly let me know if otherwise]
The issue is still seen on Opentsdb 2.3 and Grafana 4.3. 

Exact issue - https://github.com/grafana/grafana/issues/1915

**Pull request merged**
