### PR TITLE
[DOC] Adding deprecation for Loki query in Tempo data source

### PR DESCRIPTION
**Pull request by knylander-grafana**
**Who is this feature for?**

Adds a deprecation for the Loki query tab in the Tempo data source. 

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by joey-grafana — APPROVED** [review]

**Review by jdbaldry — COMMENTED** [review]
One thought is that we could avoid having to remember to remove this note by only adding it to `v10.4.x` and not to `main`.

**Comment by knylander-grafana** [comment]
> One thought is that we could avoid having to remember to remove this note by only adding it to `v10.4.x` and not to `main`.

Great idea, Jack. Maybe I can change the PR to just go to 10.4 instead of main and then 10.4?

**Comment by gtk-grafana** [comment]
@knylander-grafana something went wrong with this PR, can you open another one without all the conflicts/unwanted changes?

**Comment by knylander-grafana** [comment]
> @knylander-grafana something went wrong with this PR, can you open another one without all the conflicts/unwanted changes?

I'll fix this and redo the PR itself. Sorry about that. I tried changing the base and that made a mess. I reverted that change and I'll close the PR so we don't end up with it.

**Pull request closed without merging**
