### PR TITLE
WIP: Generate metric/dimension list from awsdocs

### LINKED ISSUE #11239: Auto generate metrics/dimensions list from CloudWatch document
CloudWatch documents becomes open source.
Parse markdown format and generate metrics/dimensions list will reduce maintenance cost.

Generate https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go
From
https://github.com/awsdocs/amazon-cloudwatch-user-guide/tree/master/doc_source

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/11239

### CODE REVIEW

**Comment by mtanda** [comment]
Placing json data to somewhere directory which include release.
`public` directory is one of the candidates.

This could be useful to user create json data for custom metrics, and use it.

**Comment by marefr** [comment]
Interesting. Not sure about the public folder, but see that email templates are put there so may be a way forward. 

Random thought, don't know if it's a good or bad idea yet. How about creating a separate repository and use something like go code generation (go generate) based on aws documentation or your custom tool. Then it's easy to distribute this and easy to upgrade. Or alternatively use code generation in grafana repo which generates codes instead of json files. Thoughts about this?

**Comment by mtanda** [comment]
I didn't have the experience to use go code generation. I'll try it.
The separate repository is a good idea, but I can't maintain it.
The purpose of this PR is reducing the maintenance cost of all related people.
I hope AWS officially provide metrics/dimensions list...

**Comment by marefr** [comment]
Understood. Maybe easier if you include your tool for generating the json files in the PR and then we can see how to take it from there.

**Comment by mtanda** [comment]
Thanks for your help.
This is my tool.
https://github.com/grafana/grafana/pull/12373/files#diff-c21c541b257042cdbc9fe662c61bfc93

**Comment by torkelo** [comment]
This PR seems to have stalled in WIP state. think generating Go files is a good idea, or json but then they need to be placed in a folder that is included in the actual distribution packages. 

Closing this, but will re-open if there is new activity.

**Pull request closed without merging**
