### PR TITLE
Duplicate button for template variables

### PR DESCRIPTION
**Pull request by utkarshcmu**
For Feature Request: #2811

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Any chance of this PR getting merged? :)

**Comment by torkelo** [comment]
not sure, maybe if it gets some +1 votes :) It has low added complexity/code so it could be merged in for next release (after 2.5)

**Comment by utkarshcmu** [comment]
Merging this in 2.6?

**Comment by utkarshcmu** [comment]
Idk whats stopping this trivial PR to get merged, it has been pending since a month now. Users need this feature to save them typing everything for each template variable. Even people from other organizations asked for it. Please check #2811.

Thanks and let me know if any changes are needed in the PR. Would be happy to make them if needed.

**Comment by utkarshcmu** [comment]
@torkelo - also please create more labels like "wont merge" , "may be merged" etc , so that we know that whether our PRs will be merged or not timely.

Thanks for all the support. :)

**Pull request merged**
