### PR TITLE
(prometheus) templating by query result

### PR DESCRIPTION
**Pull request by mtanda**
Use this with topk() query, we can get instance label values of worst 5.
worst5

I think it is helpful, quickly find bad state hosts (if there is too many host to monitoring).

### CODE REVIEW

**Comment by torkelo** [comment]
But template variables are only reloaded on dashboard load, not when you change time range.

**Comment by mtanda** [comment]
hmm, it's not big problem for my use case.
I only want to know what host is bad states now.

If I use scripted dashboard for creating such dashboard, there is same issue.
To create templated dashboard is much easier than scripted dashboard, so this feature is enough for me.

**Comment by mtanda** [comment]
If time range template value is provided (https://github.com/grafana/grafana/issues/1909) and the value is updated by time range changed (https://github.com/grafana/grafana/issues/3427), adding "offset $val" to query will resolve this issue (https://github.com/grafana/grafana/pull/3472#issuecomment-163164370) .

**Comment by mtanda** [comment]
Or simply create custom template value, which has "offset 1h", "offset 1d", "offset 1w"....

**Comment by torkelo** [comment]
looks ok but the code code need some refactoring. The metricFindQuery function is starting to become to large. Maybe break it out into it's own component that can be tested is isolation and break out the different types of metric find queries to their own functions.

**Comment by mtanda** [comment]
Code refactoring.

**Comment by mtanda** [comment]
resolve conflict

**Comment by bergquist** [comment]
@mtanda this PR now have merge conflicts since I merged https://github.com/grafana/grafana/pull/2883 Could you please solve them? I merge asap once its done.

**Comment by mtanda** [comment]
@bergquist I resolve conflicts.

**Comment by mtanda** [comment]
thank you! :smile:

**Comment by bergquist** [comment]
@mtanda thanks you! For all your great contributions! =)

**Comment by RichiH** [comment]
@bergquist Those two recent merges make me wonder if a point release will happen or if I should switch over to master branch.

**Comment by RichiH** [comment]
Also, thanks to all involved.

**Comment by bergquist** [comment]
@RichiH We are most likely releasing 3.0beta within a few weeks. So chances for a point release are kinda slim. If you can run two instances in parallel I suggest you try master to get these two new features :)

**Pull request merged**
