### PR TITLE
ShareDrawer: Wrap render logic and add `shareView` query param

### LINKED ISSUE #92059: ShareDrawer: open with query param
Add `shareView` query param to ShareDrawer, so the drawer gets open thanks to this query param.

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

1. It wraps the logic of what to render inside ShareDrawer
2. It wraps the title inside every share option
3. It adds `shareView` query param behavior.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/92059

**Special notes for your reviewer:**

Related [enterprise PR](https://github.com/grafana/grafana-enterprise/pull/7078)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Review by evictorero — COMMENTED** [review]
Nice refactor. I've tested everything with and without Scenes.
It looks good but I found one bug, when opening a share panel modal with Scenes it is not possible to close it.

**Comment by juanicabanas** [comment]
> Nice refactor. I've tested everything with and without Scenes. It looks good but I found one bug, when opening a share panel modal with Scenes it is not possible to close it.

that's already fixed [here](https://github.com/grafana/grafana/pull/92267) and it's not part of this code

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref juanicabanas/share-view-qp-redesign

**Review by evictorero — APPROVED** [review]
LGTM!

**Pull request merged**
