### PR TITLE
CLI: Fix installing plugins on windows

### LINKED ISSUE #19022: grafana-cli fails to install plugin on Windows
**What happened**:
Installing plugin on Windows using grafana-cli fails with an error:

image

**What you expected to happen**:
Plugin to be installed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
- Tried to install grafana-piechart-panel, but that throws the same error.
- Verified that manually downloading zip file and extracting it into plugin folder and restarts Grafana works as expected. 

**Environment**:
- Grafana version: v6.4.0-pre (fa00742)
- OS Grafana is installed on: Windows

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Fixes installing plugins on Windows and hopefully not breaks installing plugins on linux and mac.

**Which issue(s) this PR fixes**:
Fixes #19022 

**Special notes for your reviewer**:
Some grafana-cli tests was failing on Windows. Couldn't get some of them to succeed so suggest skipping those if on Windows. When running all the tests, there's other ones failing but suggests fixing those separately later (#19062).

### CODE REVIEW

**Comment by aocenas** [comment]
@marefr looks sensible but does that mean we do not need to change the `RemoveGitBuildFromName` to use Os specific separator?

**Review by torkelo — APPROVED** [review]
Looks good

**Comment by marefr** [comment]
> @marefr looks sensible but does that mean we do not need to change the `RemoveGitBuildFromName` to use Os specific separator?

@aocenas first thing tried to change that, but didn't make any difference so as far as I understand the answer would be yes, we shouldn't need to change this.

**Review by papagian — APPROVED** [review]
LGTM!

**Pull request merged**
