### PR TITLE
support AWS SNS notification

### PR DESCRIPTION
**Pull request by mtanda**
related to https://github.com/grafana/grafana/issues/8066

AWS SNS can send email without SMTP server.
https://aws.amazon.com/sns/details/

It is very handy tool to notify alert in AWS.

### CODE REVIEW

**Comment by mtanda** [comment]
@daniellee I think this is good notification method for AWS user.
The 5.0 release will include this? Or, need more interesting about this feature?

**Comment by mtanda** [comment]
resolve conflict

**Comment by bergquist** [comment]
First of all. thanks for all the great contributions!

We started to be kind of reluctant about adding new alert notifications. the burden of keeping up to sync with each API is just to much work. Putting alert notifications on amazon SNS seems like a solution for people who can write good custom apps. They should be able to use the web hook notifier and place such message on amazon SNS by them self. What do you think?

**Comment by mtanda** [comment]
I understand you worry about maitenance cost.

Actually..., we can send SNS or calling Lambda by using AWS API Gateway as webhook destination.
But..., API Gateway expose the API in public place, we need to protect it by adding some authentication.

If Grafana can send SNS, we can rely EC2 IAM role, it is very secure.

SNS can kick Lambda, Lambda can call any AWS API, it means Grafana can trigger EC2 Auto Scaling.
"SNS support" provides great power for AWS resources, basic authentication is not enough for protecting it.

Of course, I can implement SNS notification plugin when backend plugin is ready.
I don't insist, Grafana should support it :)

**Comment by bergquist** [comment]
This notifier will have to wait until we support backend plugins.

Knowing that you have the technical skills to maintain your own fork with this pr made my decision easier :)
Lets make this a plugins once we support that.

**Comment by mtanda** [comment]
roger! 🤝

**Comment by niklasR** [comment]
@asanka88 This branch supports EC2 roles already, yes.

**Pull request closed without merging**
