### PR TITLE
Variables: Fix variables not updating inside a Panel when the preceding Row uses "Repeat For"

### LINKED ISSUE #38853: Variables not updating inside a Panel when the preceding Row uses "Repeat For"
**What happened**: Variables are not updating inside a Panel when the preceding Row uses "Repeat For"

**What you expected to happen**: The panel content should update when changing their value.

**How to reproduce it (as minimally and precisely as possible)**: Changing the variable "host" a couple of times should bring up the issue.

**Anything else we need to know?**: The variables are not updating inside the panel, but the title updates as expected. I've attached the .json and hopefully it´s self-explained.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: None. The variables are custom.
- OS Grafana is installed on: Centos 8.4.2105
- User OS & Browser: Windows 10, Google Chrome and Firefox
- Grafana plugins: Happens with several type of panels: Text, Graph, Table, etc
dashboard_variable_bug
[dashboard_variable_bug.txt](https://github.com/grafana/grafana/files/7106383/dashboard_variable_bug.txt)

- Others:

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

Variables were not updating inside a Panel when the preceding row was using "Repeat For"

Why?

- On `DashboardGrid` we are using the function `isInView`, which decides if we should refresh the content of a panel when is on view mode. The logic of that function heavily relies on the `panel.gridPos.y` value.

The problem (an edge case):

- Panels that were rendered after a repeated row 
- And that repeated row depends on a Variable that only accepts a single value

VariablesSingleValueRepeatedRows

As soon as the user changed the variable value from the dropdown, the `panel.GridPos.y` was being accumulated, causing the `isInView=false` and leading to not refreshing the variables inside the panel. 

https://user-images.githubusercontent.com/239999/132377509-f7abe0c3-a89d-43aa-895c-47eab59880a7.mp4

Digging in..

The issue was is the `ProcessRepeats->repeatPanel()->repeatRow()` function, 

The `repeatRow` is repeating rows depending on the # of values selected in the variable dropdown, and it was updating all the panels `gridPos` that were below (even if no new repeated rows were added)

The Fix:

I just added a condition to only update GridPos if we actually rendered more than 1 repeated row.

Now is working:

- When selecting single values

https://user-images.githubusercontent.com/239999/132381020-97242548-3ae1-4067-9272-5b756a641fe6.mp4

- When selecting Multiple values

https://user-images.githubusercontent.com/239999/132381003-0dcf3a53-9638-4920-b3f4-6b355d3d8a00.mp4

**Which issue(s) this PR fixes**:

Fixes #38853

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
Looks good but there is still some edge cases when the panel is almost in view. Not sure how much time we should spend on finding all the edge cases here. The panel is updated when I scroll it into view. Seems that maybe the buffer is to large?


https://user-images.githubusercontent.com/562238/132447409-d675caa5-ade8-4390-8df7-85be34c4982f.mp4

**Comment by hugohaggmark** [comment]
I double checked if this also fixed #38805 but it didn't.

**Comment by axelavargas** [comment]
> Looks good but there is still some edge cases when the panel is almost in view. Not sure how much time we should spend on finding all the edge cases here. The panel is updated when I scroll it into view. Seems that maybe the buffer is to large?
> 
>  bug.mp4

Hey, @hugohaggmark thank you for reviewing this PR 🙌🏾 , indeed this bug it's an edge case, I think for now I gonna skip the fix, maybe we can work on this in the future if the issue is causing too much trouble to the community :).

**Comment by amir-am** [comment]
it seems still not working!

**Comment by axelavargas** [comment]
> it seems still not working!

Hey @amir-am 👋🏾, thank you for your feedback. Unfortunately, the information provided is not complete to do a follow up. Would you mind sharing more details? Which version of Grafana are you using?(the bugfix was released on `v8.1.4`), what happened?, how to reproduce it?(the steps), etc. This will help us understanding your case. 😄 

Feel free to create a [new issue](https://github.com/grafana/grafana/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md) reporting this problem, we will take a look.

**Comment by jostrasser** [comment]
Hi @axelavargas ,

Your changes in version 8.1.4 are not solving my issues:
https://github.com/grafana/grafana/issues/37778

I have to stay on 8.0.6, all newer versions starting with 8.1.x are unusable on mobile devices. 

Do you need any informations?

Thanks!

**Comment by axelavargas** [comment]
> Hi @axelavargas ,
> 
> Your changes in version 8.1.4 are not solving my issues: #37778
> 
> I have to stay on 8.0.6, all newer versions starting with 8.1.x are unusable on mobile devices.
> 
> Do you need more informations?
> 
> Thanks!

Hi @jostrasser 👋🏾 ,

Yes, unfortunately, this PR does not fix the issue you mentioned in your comment.  It looks like that one it's related to [another bug reported before](https://github.com/grafana/grafana/issues/38805) (currently in progress). As soon as that fix is out, we will verify if your issue is solved 🤞🏾 or if we need to do a further investigation.

**Comment by jostrasser** [comment]
Hi @axelavargas ,
I think this issue is also related to this problem:
https://github.com/grafana/grafana/issues/38771

Keep me posted please ;) 

Thanks!

**Pull request merged**
