### PR TITLE
Prometheus: Reduce allocations parsing exemplars

### PR DESCRIPTION
**Pull request by simonswine**
This reduces allocations for parsing exemplars. #go-performance-workshop-brussels

```
name            old time/op    new time/op    delta
ExemplarJson-8    24.7ms ±15%    17.6ms ± 2%  -28.72%  (p=0.008 n=5+5)

name            old alloc/op   new alloc/op   delta
ExemplarJson-8    4.70MB ± 0%    3.58MB ± 0%  -23.79%  (p=0.008 n=5+5)

name            old allocs/op  new allocs/op  delta
ExemplarJson-8     72.6k ± 0%     69.1k ± 0%   -4.81%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Comment by simonswine** [comment]
@zserge @mildwonkey @ying-jeanne any chance for a review?

**Review by itsmylife — APPROVED** [review]
LGTM

**Review by toddtreece — APPROVED** [review]

**Comment by gtk-grafana** [comment]
@simonswine This was closed from inactivity, is this something we want to merge?

**Comment by itsmylife** [comment]
@simonswine looks like "Enterprise PR check" is failing. You should merge `master` in. Please see the thread for more context https://raintank-corp.slack.com/archives/C01ME9ZS1SS/p1669721553895629

**Pull request merged**
