### PR TITLE
Playlist: Start moving over to coremodel based single point of truth

### PR DESCRIPTION
**Pull request by sakjur**
This is similar in some senses to #54005, but focused more on using core models as the single source of truth for current interaction between the frontend and the backend.

As of the first commit, this isn't compiling but rather being shared as a mode of communicating a bug in the code generator where it removes prefixes in a breaking manner.

### CODE REVIEW

**Comment by sdboyer** [comment]
Ooof, picking out this particular case to avoid renaming is trickier than i initially thought. My simple approach results in a bunch of other compile errors in the other generated code:

```
# github.com/grafana/grafana/pkg/coremodel/dashboard
../../../pkg/coremodel/dashboard/dashboard_gen.go:176:23: undefined: DashboardGraphTooltip
../../../pkg/coremodel/dashboard/dashboard_gen.go:198:8: undefined: DashboardStyle
../../../pkg/coremodel/dashboard/dashboard_gen.go:329:14: undefined: DashboardDashboardLinkType
../../../pkg/coremodel/dashboard/dashboard_gen.go:372:7: undefined: DashboardGraphPanelType
../../../pkg/coremodel/dashboard/dashboard_gen.go:407:7: undefined: DashboardHeatmapPanelType
../../../pkg/coremodel/dashboard/dashboard_gen.go:528:18: undefined: DashboardPanelRepeatDirection
../../../pkg/coremodel/dashboard/dashboard_gen.go:590:9: undefined: DashboardRowPanelType
../../../pkg/coremodel/dashboard/dashboard_gen.go:634:7: undefined: DashboardThresholdsConfigMode
../../../pkg/coremodel/dashboard/dashboard_gen.go:684:8: undefined: DashboardVariableModelType
# github.com/grafana/grafana/pkg/coremodel/pluginmeta
../../../pkg/coremodel/pluginmeta/pluginmeta_gen.go:276:7: undefined: PluginmetaType
../../../pkg/coremodel/pluginmeta/pluginmeta_gen.go:339:10: undefined: PluginmetaDependencyType
../../../pkg/coremodel/pluginmeta/pluginmeta_gen.go:382:7: undefined: PluginmetaIncludeType
```

Will figure it out 😄

**Comment by ryantxu** [comment]
This is what the frontend is currently working with: https://github.com/grafana/grafana/blob/main/public/app/features/playlist/types.ts#L12
everything else is ignored
```
interface Playlist {
  uid: string;
  name: string;
  interval: string;
  items?: {
    type: ('dashboard_by_uid' | 'dashboard_by_tag' | 'dashboard_by_id');
    value: string;
  }[];
}
```

**Comment by sdboyer** [comment]
That did end up being more work than i thought initially, but really, it forced some discipline on that prefix dropper logic. I added a test, and i think our cases are now pretty exhaustively covered.

**Comment by sakjur** [comment]
> This is what the frontend is currently working with: https://github.com/grafana/grafana/blob/main/public/app/features/playlist/types.ts#L12 everything else is ignored

✅ I think that somewhat overlaps with what I marked as deprecated (not quite, but mostly— and we can extend that, I'd just want a good notice for the title/IDs where just tossing them away risks leaving the consumer confused)? Though we don't target just the frontend with the API. Full compatibility is key for my purposes. It's easy to argue that playlists isn't the most important of APIs and little harm would be done if we'd cheat here, but that would defeat the point of starting here, as if we'd take shortcuts when making the first attempt at doing this we'd learn less and risk providing the wrong guidance to the introduction of coremodels to APIs which see more practical use.

And, for this PR, an important detail is that I basically just want to be able to type alias the current definitions in Go to see if we can practically do that, which requires Cue to (to a large extent) faithfully represent the current state. I hope to be able to have it make sense once I get this to a proper compiling stage and can write a little bit of a writeup of what this approach is angling for.

**Comment by ryantxu** [comment]
Closing this now that #56048 is merged

**Pull request closed without merging**
