### PR TITLE
LDAP: refactoring 

### PR DESCRIPTION
**Pull request by markelog**
* Make login service an explicit dependency

* Rename some of the public methods and change their behaviour

* Remove outdated methods

* Simplify logic

* More tests
  There is no and never were tests for settings.go, added tests for helper
  methods (cover is now about 100% for them). Added tests for the main
  LDAP logic, but there is some stuff to add. Dial() is not tested and not
  decoupled. It might be a challenge to do it properly

* Restructure tests:
    * they wouldn't depend on external modules
    * more consistent naming
    * logical division

* More guards for erroneous paths

* Use only models.ExternalUserInfo

* Add additional helper method :/

* Move all the helpers to one module

### CODE REVIEW

**Comment by torkelo** [comment]
Just did a quick glance through the changes, looks like a solid refactoring! @carl or @xlson should probably do a more detailed review but just want to say really like that we take the time to do these refactorings and raising the code quality as we add more features/complexity

**Comment by markelog** [comment]
Thanks for good word @torkelo! :)

**Review by xlson — APPROVED** [review]
Great work Oleg.

I did a pass over the code and it looks good. Is there anything, in particular, you want me to look at in more detail?

**Comment by markelog** [comment]
@xlson I think it might be cool if you could do a test for the cases mentioned in the docs - https://grafana.com/docs/auth/ldap/. It doesn't have to be all of the stuff in there, but I am specifically concerned with binding - https://grafana.com/docs/auth/ldap/#bind

I tested it myself couple times, but there is always a chance I might be misinterpreting/missing something :). 

Second pair of eyes are always helpful!

**Comment by xlson** [comment]
Discussed this with @markelog today and decided to do in-depth testing after merge.

**Comment by markelog** [comment]
Found and fix the bug for multiple users, also simplified the `helpers` module and increased the coverage

**Comment by torkelo** [comment]
Is it ready to merge?

**Comment by xlson** [comment]
@torkelo afaik, I'm going to merge this now.

**Pull request merged**
