### PR TITLE
fix diff and percent_diff

### PR DESCRIPTION
**Pull request by jessetane**
https://github.com/grafana/grafana/issues/11563

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Looks good. 

But would be nice with some tests of the diff and diff_percent in reducer_test.go. Should be fairly straight forward to add based on the existing tests.

**Comment by jessetane** [comment]
good point, will update

**Comment by jessetane** [comment]
ok cool 7f3fc34 with updated tests appears to be failing now:

https://circleci.com/gh/grafana/grafana/23571?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by marefr** [comment]
But the old test should still not fail right having only two points or am I missing something?

You can run test locally using `go test ./pkg/services/alerting/...`

**Comment by jessetane** [comment]
the old test doesn't fail, the updated one fails

**Comment by marefr** [comment]
Okay sorry for my confusion :+1:

**Comment by jessetane** [comment]
github has the order of my comments and when the commits landed wrong, that makes it a bit confusing to follow

**Review by marefr — CHANGES_REQUESTED** [review]
Added some useful tests and the percent_diff one point are failing, please include these tests and fix failing test. Then ready for merge.

```diff
diff --git a/pkg/services/alerting/conditions/reducer_test.go b/pkg/services/alerting/conditions/reducer_test.go
index 1058b99..89a631f 100644
--- a/pkg/services/alerting/conditions/reducer_test.go
+++ b/pkg/services/alerting/conditions/reducer_test.go
@@ -115,11 +115,30 @@ func TestSimpleReducer(t *testing.T) {
                        So(result, ShouldEqual, float64(10))
                })
 
+               Convey("diff one point", func() {
+                       result := testReducer("diff", 30)
+                       So(result, ShouldEqual, float64(0))
+               })
+
+               Convey("diff two points", func() {
+                       result := testReducer("diff", 30, 40)
+                       So(result, ShouldEqual, float64(10))
+               })
+
                Convey("percent_diff", func() {
                        result := testReducer("percent_diff", 30, 40, 40)
                        So(result, ShouldEqual, float64(33.33333333333333))
                })
 
+               Convey("percent_diff one point", func() {
+                       result := testReducer("percent_diff", 30, 40, 40)
+                       So(result, ShouldEqual, float64(0))
+               })
+
+               Convey("percent_diff two points", func() {
+                       result := testReducer("percent_diff", 30, 40)
+                       So(result, ShouldEqual, float64(33.33333333333333))
+               })
        })
 }
```

**Comment by jessetane** [comment]
I think the failure is from a typo in your percent_diff one point test, I corrected it

**Comment by jessetane** [comment]
also, lmk if you prefer i squash this last commit with 7f3fc34

**Pull request merged**
