### PR TITLE
Revert "SQLStore: Prevent concurrent migrations"

### PR DESCRIPTION
**Pull request by papagian**
Reverts grafana/grafana#44101 cause it breaks [enterprise](https://github.com/grafana/grafana/pull/44101#issuecomment-1040549292) because of dependency cycle.

### CODE REVIEW

**Comment by papagian** [comment]
no backport is required because the reverted PR was not finally backported in `v8.4.x`

**Comment by nicolaerosia** [comment]
can't it be fixed? would be nice to have this in 8.4.0 - I'm always afraid to do upgrades on Kubernetes because of this.
I've switched to updateStrategy type Recreate because of this.

**Review by marefr — APPROVED** [review]
LGTM if needed, we can revert and hopefully still have time to get it merged for v8.4.0 stable. Otherwise we can include it in a 8.4.x patch since it's behind a feature toggle

**Comment by papagian** [comment]
Closing this in favour of #45427

**Pull request closed without merging**
