### PR TITLE
S3 storage

### PR DESCRIPTION
**Pull request by paulkearney**
This pull request adds support for saving and loading dashboards from S3. I largely followed the model of saving/loading from gists.

You'll note in dashboard.js, when retrieving a list of dashboards, I could not get the AWS sdk to return the result in json when using $http. By using the AWS client, it returns in json. However, this means I needed to wrap the AWS client call in my own Promise.

### CODE REVIEW

**Comment by szibis** [comment]
Any ETA with that ?

**Comment by scoates** [comment]
:boat: ?

**Comment by cemo** [comment]
@torkelo would be a nice asset :)

**Comment by torkelo** [comment]
with grafana 2.0 and it's own database for users and accounts and dashboards this PR is not appropriate any more. something  like this could be implemented using s3sync and the grafana Http Api

**Comment by maria** [comment]
I would have love this. I don't want to install a mysql database or something else when I am running in a container, for example, just to store my data. Especially with container orchestrations these days.

**Comment by torkelo** [comment]
@maria you don't need mysql, local built in sqlite3 works as well.

**Comment by maria** [comment]
I know, it was an example. Running sqlite3 in a docker container is a bad idea as well. No actual persistence there.

**Comment by torkelo** [comment]
you just need to mount / map a persisted volume

**Comment by maria** [comment]
> Especially with container orchestrations these days, when you can open a container anywhere in the infrastructure.

Take a look at Mesos, Kubernetes or DC/OS, you can't do that. :) Thanks.

**Pull request closed without merging**
