### PR TITLE
Fix multi-value templating for OpenTSDB

### PR DESCRIPTION
**Pull request by HugoMFernandes**
See #12625

### CODE REVIEW

**Comment by HugoMFernandes** [comment]
Note: I fixed this on opentsdb's plugin side by using `templateSrv` to convert to a glob (and then expand) in order to use `templateSrv`'s logic without having to do a major refactor just for opentsdb (as `templateSrv` assumes a 1:1 mapping between input metrics and output ones, which doesn't work for opentsdb's use case). I appreciate this could be approached differently by refactoring the entire templating logic though.

**Comment by torkelo** [comment]
I am sorry, I don't think the templating system is a good fit for OpenTSDB metric names. The templating engine is built around string interpolation. I think this needs to be fixed on the OpenTSDB side, so OpenTSDB can handle some kind of multi-value matching on metric names (glob/regex/pipe/etc).

**Comment by HugoMFernandes** [comment]
Hey @torkelo,

I can't speak for OpenTSDB's maintainers, but I don't think enabling multi-value matching on metric names can be considered a "fix" (since OpenTSDB does support multi-value matching by specifying multiple queries in the same request, which was the approach taken here).

This is a bit of a grey area, but I think doing it on OpenTSDB actually feels more like a "feature just for grafana's sake" (i.e. because grafana's templating system wasn't built to support all core datasources) than the other way around. I believe defining these mechanisms should be up to the datasources themselves (and not imposed by grafana or any other consumer).

@manolama thoughts?

**Comment by torkelo** [comment]
It just that that I don't think this is an acceptable use of the templating system. 

```javascript
explodeMetricNames(metric, scopedVars) {
   // Parse into a glob (and expand it afterwards) so we can reuse templateSrv without having to refactor the entire
   // templating logic.
   var glob = this.templateSrv.replace(metric, scopedVars, 'glob');

   return expand(glob);
}
```

**Comment by HugoMFernandes** [comment]
Alright, that's a different problem then. Would you mind suggesting something that you find acceptable?

**Comment by torkelo** [comment]
Not sure, as I said , the templating system as it works now is not a good fit for this

**Comment by HugoMFernandes** [comment]
Closing this as it's clearly going nowhere (we'll just patch it internally until there's some direction for this).

I'll open an issue with the bug in case someone wants to pick it up.

**Comment by manolama** [comment]
We can add wildcard and regex support in 3.0, it wouldn't work well in 2.x. Referencing https://github.com/OpenTSDB/opentsdb/issues/1274

**Pull request closed without merging**
