### PR TITLE
AzureMonitor: Add new starter dashboards

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What this PR does / why we need it**:
To add more starter dashboards for the Azure Monitor data source

**Which issue(s) this PR fixes**:
NA

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jcolladokuri** [comment]
Hey @joshhunt! Let me know if you have any questions regarding this PR!

**Comment by sunker** [comment]
Thanks for contributing @jcolladokuri. Can you please provide a description for each of the new dashboards so that it's easier for us to understand what it is that we're reviewing?

**Comment by jcolladokuri** [comment]
This PR adds dashboards for alerts curated to the Azure Monitor datasource.

- v1Alerts: a summary of all alerts for the subscription and other filters selected
- v1AlertsAtScale: A summary of alerts per severity with an overall count of total alerts, alert rules and action rules
- alertRules: a summary of all alert rules for the subscription selected and following filters.

**Comment by jcolladokuri** [comment]
> Hello! Thanks again for your contribution! A couple of things:
> 
> * can you change the name of the dashboards to be prefixed with Azure so for example "Alert consumption" to "Azure Alert consumption"? We have our own alerting in grafana and it could be kind of confusing to users which ones we're talking about.
> * can you make sure you select "Export for sharing externally" when creating these dashboards? Here's a recording of how to do it: https://recordit.co/ijd8sYvBpy Without that your dashboards have hardcoded ids that could conflict with other user's dashboards.

Both of these are done! @sarahzinger

**Review by sarahzinger — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
