### PR TITLE
Variables: Fixes issue with upgrading legacy queries

### LINKED ISSUE #29373: Variables - Queries are not shown in Variable editor
Repro steps:
1. Checkout 5ae72802495a2a46c4554a872a264299245513e0 which is the version before #28217
2. Import the following dashboard
```json
{
  "__inputs": [
    {
      "name": "DS_GDEV-TESTDATA",
      "label": "gdev-testdata",
      "description": "",
      "type": "datasource",
      "pluginId": "testdata",
      "pluginName": "TestData DB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.3.3"
    },
    {
      "type": "datasource",
      "id": "testdata",
      "name": "TestData DB",
      "version": "1.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1606304926387,
  "links": [],
  "panels": [],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_GDEV-TESTDATA}",
        "definition": "*",
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "testdata",
        "options": [],
        "query": "*",
        "refresh": 0,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Variables - Queries are not shown in Variable editor",
  "uid": "lDKg5iAMk",
  "version": 2
}
```
5. Goto Dashboard settings > Variables > click on the testdata variable
6. Variable Editor is shown __`[Ok]`__
6. The query input field is shown with the stored query. __`[Ok]`__
3. Checkout latest master and refresh the dashboard
5. Goto Dashboard settings > Variables > click on the testdata variable
6. Variable Editor is shown __`[Ok]`__
6. The query input field is empty __`[Not Ok]`__ expected to be able to view the stored query.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
When we refactored the variable system in #28217 we added a function for migrating/upgrading the query property for variables that use the StandardVariableSupport. This worked for most cases like importing and for variables with the refresh setting set to `OnDashboardLoad` or `OnTimeRangeChanged` but I forgot about those with refresh setting set to `Never`. This PR moves the logic into the initialization of variables instead.

**Which issue(s) this PR fixes**:
Fixes #29373

**Special notes for your reviewer**:
Instructions on how to test this is in the repro steps for #29373

### CODE REVIEW

**Review by mckn — APPROVED** [review]
The code looks really good! I have not tested it but will do that as well later today.

**Comment by hugohaggmark** [comment]
@mckn did you have a chance to test this PR?

**Comment by mckn** [comment]
> @mckn did you have a chance to test this PR?

Will take it for a spin now.

**Comment by mckn** [comment]
Works really well! Go go go!

**Pull request merged**
