### PR TITLE
transform: changes to support sdk v0.2.0

### PR DESCRIPTION
**Pull request by kylebrandt**
- [x] depends on https://github.com/grafana/grafana-plugin-sdk-go/pull/18
- [x] vendor/ changes included

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by marefr** [comment]
@kylebrandt is this something that needs be included in 6.5 stable?

**Comment by kylebrandt** [comment]
@marefr I don't think so. The goal was really to get things into Master for development, not a particular release as I understand it.

So whatever makes the release process easier is fine with me.

**Comment by marefr** [comment]
Cool :+1:

**Pull request merged**
