### PR TITLE
A11y: Make the Library Panel "clear filter" buttons accessible

### PR DESCRIPTION
**Pull request by zuchka**
**What this PR does / why we need it**:

For A11y:

When using the Library Panels manager, the user can filter by folders and/or panel types. Also, when adding a library panel via the "New Panel" widget, the user can filter by panel types. When filters are added, a button appears that the user can press to clear all options. This button is not keyboard accessible, nor is it screen-reader accessible.

This PR changes that button from a `span` to a `button`. This makes it accessible to keyboard-only users and screen-reading users.

Before:

https://user-images.githubusercontent.com/37156449/157353847-be1c1894-2f5a-4891-b39c-e97b667bf36f.mp4

After:

https://user-images.githubusercontent.com/37156449/157353625-dfdf22cb-5b0d-48e4-9fad-1f126da6e3fa.mp4

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Elfo404 — COMMENTED** [review]
Nice! what if we replace those custom styles with: 
```
<Button
          size="xs"
          icon="trash-alt"
          variant="link"
          className={styles.clear}
          onClick={() => onChange([])}
          aria-label="Clear folders"
        >
          Clear folders
        </Button>
 ```
(we already have a link variant for buttons)

then custom styles could be used only for positioning, ie:
```
clear: css`
      label: clear;
      font-size: ${theme.spacing(1.5)};
      position: absolute;
      top: -${theme.spacing(4.5)};
      right: 0;
    `,
```

Screenshot 2022-03-09 at 11 59 59

**Comment by zuchka** [comment]
thanks, @Elfo404! Updated with the suggested changes 👍

**Review by Elfo404 — APPROVED** [review]
looks great! 🚀

**Review by axelavargas — APPROVED** [review]
🚀 good to go!

**Pull request merged**
