### PR TITLE
dashboard: Close/hide 'Add Panel' before saving a dashboard

### LINKED ISSUE #10472: Close/hide 'Add Panel' before saving a dashboard
I find it quite weird that you can save a dashboard when you have the *Add Panel* opened. This will result in that the *Add Panel* are visible next time you visit your saved dashboard.

~~Shouldn't we always close the *Add Panel* before saving a dashboard?~~

We should close/hide the *Add Panel* if open before saving a dashboard.

Kind of related to #10299

### PR DESCRIPTION
**Pull request by marefr**
Fixes #10472

### CODE REVIEW

**Comment by torkelo** [comment]
it's probably easier to do this in the DashboardModel.getSaveModelClone()  function, it is used by all save functions. Just find any panel of type add-panel and remove it. 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboard_model.ts#L131

**Comment by marefr** [comment]
Good point, however seems like getSaveModelClone are called other times as well. Just tried and implemented this in getSaveModelClone and created a new dashboard. The Add Panel are visible from beginning then. A few seconds later it gets removed, i.e. another call to getSaveModelClone are made from somewhere.

**Comment by marefr** [comment]
I could move the closeAddPanel function from dashboard_srv.ts to a removeAddPanelPanels function in dashboard_model.ts. Would that be better?

**Comment by torkelo** [comment]
that cannot possibly be correct. if you remove the panel from the clone the function returns. Changes you make to the returned clone cannot effect the current live dashboard).

> A few seconds later it gets removed. 

This is probably done by the unsaved changes srv that waits 1-2 seconds to get the pristine (unchanged version). But dont see how one call to this function can effect the current dashboard. it only returns copies.

**Comment by marefr** [comment]
I screwed up. You're right :+1:

**Pull request merged**
