### PR TITLE
Add Chris Trott to the Grafana team

### PR DESCRIPTION
**Pull request by daniellee**
Chris Trott has been proposed as a new team member and the vote achieved the super majority required.

@trotttrotttrott can you approve the PR to confirm that you accept, please. Welcome to the team!

### CODE REVIEW

**Comment by roidelapluie** [comment]
The list is sorted alphabetically (which will also prevent merge conflicts)

**Review by trotttrotttrott — APPROVED** [review]
Absolutely! Thank you!

Although, I must note that I'd be breaking the alphabetical order of the list. I should probably go up between you and Carl 🙈

**Comment by daniellee** [comment]
Thanks! Beginner mistake - fixed now.

**Review by trotttrotttrott — APPROVED** [review]
🎉

**Pull request merged**
