### PR TITLE
Do not show alerts tab when alerting is disabled

### LINKED ISSUE #25143: Visible alerting UI features while alerting is disabled
**What happened**:
Despite configuration like below
```
[alerting]
enabled = false
```
there is still visible UI to create alert in the edit mode of a graph

graph_edit
graph_edit_alert

**What you expected to happen**:

Any kind of alerting UI is not visible, since feature has been disabled.

**How to reproduce it (as minimally and precisely as possible)**:

Disable alerting in the config, then edit a graph. 

**Environment**:
- Grafana version: 7.0.1
- Data source Graphite 1.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Firefox 76.0.1
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #25143

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM! 🌟  Nit: is it a lot of work to add a test for this?

**Comment by dprokop** [comment]
> Nit: is it a lot of work to add a test for this?

Nope, not at all. Good catch!

**Review by hugohaggmark — APPROVED** [review]
Exceptional work! 🏅

**Comment by dprokop** [comment]
@hugohaggmark fixed. Added some more basic tests to the tabs selectors. I know this is against the rule of 1 PR = 1 fix, but these were such low hanging fruits:)

**Pull request merged**
