### PR TITLE
NodeGraph: Edge color and stroke-dasharray support

### PR DESCRIPTION
**Pull request by morrro01**
Adds support for providing color, highlighted color, and visual display of node graph edges as dashed lines via stroke-dasharray.

**What is this feature?**

Adds support for setting additional visual properties of a node graph edge. In particular:

- `color` is an optional field for specifying the default color of an edge. Falls back to the default "#999999" when not provided.
- `highlightedColor` is an optional field for specifying the highlighted color of an edge. Falls back to the default "#a00" when not provided. Requires that `highlighted` be `true` for use.
- `strokeDasharray` is an optional field that allows specifying a [stroke dash array](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray) to enable visual display of the edge as a dashed line if desired.

**Why do we need this feature?**

Allows for more granular control of the visual display of the node graph in instances where the relationship between nodes requires further visual context. Consider a scenario in which the node graph is to display the status of a network topography that conveys the status and routing of network traffic. While some nodes may be capable of receiving traffic, they might not be the node actually receiving traffic (e.g., load balancer pool). In this scenario, we may wish to visually convey available-but-not-active edges as a green dashed line.

**Who is this feature for?**

Users wishing for more granular visual control of edges within a node graph panel.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by imatwawana — APPROVED** [review]
Thanks for the contribution @morrro01. I've approved the documentation portion of this PR, but the code still requires review.

**Review by fabrizio-grafana — COMMENTED** [review]
LGTM! I've left some minor comments and I suggest to wait for someone from @grafana/observability-traces-and-profiling that is more experienced on this part, but I think the changes should be fine!

**Comment by morrro01** [comment]
Thank you kindly to both @imatwawana and @fabrizio-grafana. Good suggestions around verbiage, and they've been implemented.

**Comment by aocenas** [comment]
Code looks good but I have one thing here. We added `highlighted` because we thought we just needed a single way to differentiate some edges (who needs more than 2 colors, right?). If we allow custom coloring for edges I don't think the `highlighted` column and `highlighted` color make sense anymore, just use whatever color and edge thickness that makes sense for for the thing you want to convey to the user. This would be a bit of a breaking change but mostly visual one and we can first just mark it deprecated before actually dropping it. @morrro01 are you ok making such changes? So we would just add `color` and `strokeDasharray` for now and just add `@deprecated` to the `highlighted` column.

**Comment by morrro01** [comment]
> Code looks good but I have one thing here. We added `highlighted` because we thought we just needed a single way to differentiate some edges (who needs more than 2 colors, right?). If we allow custom coloring for edges I don't think the `highlighted` column and `highlighted` color make sense anymore, just use whatever color and edge thickness that makes sense for for the thing you want to convey to the user. This would be a bit of a breaking change but mostly visual one and we can first just mark it deprecated before actually dropping it. @morrro01 are you ok making such changes? So we would just add `color` and `strokeDasharray` for now and just add `@deprecated` to the `highlighted` column.

100%. This was initially my thought as well as it's not only unlikely that an efficient node graph structure would expose unnecessary visual state properties, but streamlines the logic under the hood to a simple "if custom color, use it; otherwise fall back to the default `highlighted`-based color assignment". Ultimately decided against it due to this being my first contribution, and didn't want to rock the boat too much.

I'll make those updates. I appreciate the feedback.

**Comment by morrro01** [comment]
@imatwawana - Per request by @aocenas, documentation has been updated to reflect the removal of the `highlightedColor` property and a caution admonition is added to note the deprecation of `highlighted` in favor of `color`. I made a best guess at the expected release version.

@aocenas - Code has been updated with deprecation notices around `highlighted`, and the `highlightedColor` property removed. Use of `highlighted` will still work using the default red color, but is superseded by `color` if both are provided.

**Comment by aocenas** [comment]
@morrro01 thanks for the updates. Looks good, I added just some testing scenario into our test data source so it's easier to visually check how things work together.

**Pull request merged**
