### PR TITLE
Graph: On over highlight series 

### PR DESCRIPTION
**Pull request by bergquist**
make sure the highlight stay as long as you hovering the legend.

### CODE REVIEW

**Comment by bergquist** [comment]
image

**Comment by bergquist** [comment]
https://files.slack.com/files-tmb/T02S4RCS0-F0TQC0ULS-4f81570de1/output_360.gif

**Comment by torkelo** [comment]
can review and merge this weekend

**Comment by torkelo** [comment]
highlights should use the in built flot feature to highlight points and bars, this is done on the overlay canvas. This way the hole graph does not need to be rerendered only the overlay canvas. The built in highlight feature need to be extended a little bit to support lines as well, but this seems doable.

For reference here is a highlight plugin (not sure we can use this but maybe draw inspiration from). 
http://brian.peiris.name/highlightSeries/jquery.flot.highlightSeries.js?v=1.1

**Comment by mtanda** [comment]
I tried to use the plugin, the highlighting works for hover series line event.
To make it works for hover legend, need to change code more, but it might be possible.

https://github.com/bergquist/grafana/compare/legend_highlight...mtanda:legend_highlight_overlay?expand=1

**Comment by mtanda** [comment]
finally, I success to make it works for hover legend event.
@torkelo @bergquist Would you check the code?

**Comment by bergquist** [comment]
@mtanda awesome! where can we check out the code?

**Comment by mtanda** [comment]
@bergquist I  put the code in this branch.
https://github.com/grafana/grafana/compare/master...mtanda:legend_highlight_overlay?expand=1

**Comment by bergquist** [comment]
Closing this in favor of #4599

**Pull request closed without merging**
