### PR TITLE
BackendSrv: Adds missing props back to response object in datasourceRequest

### LINKED ISSUE #21662: backendSrv: (datasource)request interface changed
**What happened**:
With #20999 there where some changes in the datasourceRequest interface. Since that a successfull request returned the whole response (statuscode, header, loctaion, etc.). Now only the data field.
https://github.com/johntdyer/grafana/commit/782074ac0e2fa6f7fdfe51cecb654bd33dbeb512#diff-ee2adfbba2f0547ca6b2c9bc2fde339aR216

**What you expected to happen**:
Many plugins where developed with the old interface using the statuscode and header. For example  parsing the location out of the header in a post request response.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Master 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Adds status, headers, statusText, redirect, type and url back to response after refactor in #20999 

**Which issue(s) this PR fixes**:
Fixes #21662

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Think we are also missing the request, which was also part of the response. 

Used by query inspector, which is now missing the request:
image

**Comment by torkelo** [comment]
compared to on 6.5.3 (play site):
image

**Comment by hugohaggmark** [comment]
> Think we are also missing the request, which was also part of the response.
> 
> Used by query inspector, which is now missing the request:
> image

So basically the options going into fetch?

**Comment by torkelo** [comment]
yea, think so

**Comment by hugohaggmark** [comment]
> yea, think so

So I looked into the `QueryInspector` and that expects a `.config` prop to be present. This is using that Angular `IHttpResponse<any>` I mentioned. I'm gonna change QueryInspector too.
   if (response.config) {
      response.request = response.config;
      delete response.config;
      delete response.request.transformRequest;
      delete response.request.transformResponse;
      delete response.request.paramSerializer;
      delete response.request.jsonpCallbackParam;
      delete response.request.headers;
      delete response.request.requestId;
      delete response.request.inspect;
      delete response.request.retry;
      delete response.request.timeout;
    }

**Review by torkelo — APPROVED** [review]
Looks good!

**Pull request merged**
