### PR TITLE
next version 6.7.0

### PR DESCRIPTION
**Pull request by xlson**
**What this PR does / why we need it**:

Updated version to v6.7.0-pre

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Think the package.json in packages (grafana/ui etc) should be updated as well? Did you run `yarn packages:prepare`?

**Comment by xlson** [comment]
@marefr that makes sense,I did not. That step wasn't mentioned in the guide (unless I missed it) but I should have caught on to that.

**Comment by ryantxu** [comment]
Can we drop the final .0?

**Comment by marefr** [comment]
Yeah the `.0` shouldn't be there

**Comment by xlson** [comment]
@dprokop it seems the tooling added a .0 to pre  in lerna.json as well. Should I fix it manually or is it easy to fix with the tooling?

**Comment by dprokop** [comment]
@xlson let's fix it manually

**Review by marefr — APPROVED** [review]
LGTM

**Review by dprokop — APPROVED** [review]

**Pull request merged**
