### PR TITLE
added datasource as variable type

### PR DESCRIPTION
**Pull request by toni-moreno**
With this PR now it is posible use variable to change datasources in query variables and graphs

image

Solves (https://github.com/grafana/grafana/issues/816)

image

image

### CODE REVIEW

**Comment by toni-moreno** [comment]
Hi @torkelo.

Let me know if you need some change before merging  this PR, and also if you need I resolve merge conflicts or perhaps you will prefer resolve it yourself.

**Comment by torkelo** [comment]
I did do some work on it in https://github.com/grafana/grafana/commit/41b727bbe032b140cac885678d64d5e3d635c0d7 But needs more work with the settings, submenu, testing etc.

**Comment by torkelo** [comment]
Ah, sorry that was the wrong commit, ment this branch: https://github.com/grafana/grafana/commits/toni-moreno-add_datasource_variable

**Comment by toni-moreno** [comment]
Hi @torkelo, I know that this will be a new feature in grafana 2.0 .  you have a date set for their release?

**Comment by torkelo** [comment]
@toni-moreno no, the code will appear in a develop branch in a few days, so that people can start trying it and coming with feedback and bug reports, then a beta by end of February or early march. 

A lot of what is in milestone 2.0 will probably be pushed to 2.1 because I think it is better to release 2.0 (with the backend) as soon as possible and then add more features and polish in minor release shortly after.

**Comment by toni-moreno** [comment]
Hi @torkelo.

We are close to 2.1 release.
What about any  this PR ?

**Comment by torkelo** [comment]
@toni-moreno not sure, requires more work, and there is a lot or more work on more top rated 2.1 issues

**Comment by panda87** [comment]
+1
Using InfluxDB datasource as a templating variable will be a huge improvement.

**Comment by torkelo** [comment]
will close this, I do want this feature, but have to find a way that is not so intrusive & complex.

**Pull request closed without merging**
