### PR TITLE
Prometheus: Add pluginVersion to query

### PR DESCRIPTION
**Pull request by toddtreece**
**What this PR does / why we need it**:

This adds the current Grafana version to new Prometheus data source queries. This will be useful if we need to alter behavior for queries that were saved in previous Grafana versions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ryantxu** [comment]
As implemented, this looks like it will always send a version -- even if it was saved *before* we save versions with the query.

For panels we save the "pluginVersion" with every panel that has migration scripts.  This is different than the dashboard `schemaVersion` -- an incrementing integer that changes whenever we know we made a change.

I see two issues here:
1. When do we actually save/update the value
2. What value makes sense to save (explicit number version, or the plugin version)

**Comment by toddtreece** [comment]
@ryantxu i added test coverage to make sure that this is only added to queries where the expression is blank in [01ddfe7](https://github.com/grafana/grafana/pull/49414/commits/01ddfe74325a5563f5b1df9eb8488aedce9ce9c0)

**Comment by ryantxu** [comment]
Is the plan that we only set this the first time the query is created, or maybe changed in some dramatic way?

I'm trying to understand how we can use it :).  

I dont think it makes sense to just set the value before executing -- that is the same signal as 9.0 or anything before it.   Would be nice to have empty mean "anything before 9", and it it is set, it means "the query was created at version X.Y.Z"

(but still not sure how/if we could upgrade them!)

**Comment by toddtreece** [comment]
> Is the plan that we only set this the first time the query is created, or maybe changed in some dramatic way?

my intention was to only set it when the query is created, but from my understanding "created" is a bit of a fuzzy concept currently since the query can be passed in from a previous data source selection.

> Would be nice to have empty mean "anything before 9", and it it is set, it means "the query was created at version X.Y.Z"

yeah, that's what i'm going for here, but i might be missing something obvious

**Comment by toddtreece** [comment]
> (but still not sure how/if we could upgrade them!)

same here. there was this old PR: https://github.com/grafana/grafana-plugin-sdk-go/pull/394

not sure if it's worth revisiting, or if cue is ready to be used instead

**Comment by toddtreece** [comment]
> What is this for? What problem does this solve?

this is one possible way for us to identify when a query was created in case there are backwards compatibility issues for pre-9.x saved queries and changes like the streaming JSON parser.

>  Is there a context where that is not true

the intent is to set this for new queries, so that when they are saved in the dashboard we know if they were created in pre-9.x (pluginVersion would be blank), 9.0, 9.1, etc

**Comment by aocenas** [comment]
> this is one possible way for us to identify when a query was created in case there are backwards compatibility issues for pre-9.x saved queries and changes like the streaming JSON parser.

Isn't this something more general in that case? I would assume saved queries can be also from other data sources, or are you talking about some prometheus specific feature?

**Comment by toddtreece** [comment]
closing this since it's not going to make it into 9.0 at this point, and it won't help with identifying pre-9.0 queries

**Pull request closed without merging**
