### PR TITLE
WIP/Select: show cursor at the beginning, not end of select

### PR DESCRIPTION
**Pull request by ryantxu**
I must be going mad... the blinking cursor at the *end* of the select component is pretty confusing when you start typing:

image

delete key does not do anything and typing feels awkward

The default react-select shows the cursor at the beginning:
Peek 2021-11-12 18-05
:

Updating library and :crossed_fingers:

### CODE REVIEW

**Comment by torkelo** [comment]
Yes this had also driven me mad! Will test later!

**Comment by ryantxu** [comment]
@torkelo sadly no simple solution here -- looks like we have customized everythign and not super easy to change ;(

Green box is the input wrapper and red box is the Single value display.  

Peek 2021-11-14 20-33


The upgrade to 5x will involve some more involved typings work (maingly with groups), but it does not seem to magically fix anything, so may not be worth it

**Comment by torkelo** [comment]
By looking how it works in v5 I was able to copy that idea and apply it to our custom styles: https://github.com/grafana/grafana/pull/41693

**Comment by torkelo** [comment]
Opened a new PR that just explores upgrading the lib: https://github.com/grafana/grafana/pull/41724 

And fixing the cursor position:  #41693

**Comment by ryantxu** [comment]
closing... as this is not doing anything too interesing

**Pull request closed without merging**
