### PR TITLE
PanelEditor: Tweak category design

### PR DESCRIPTION
**Pull request by torkelo**
I have seen this design in a few figma designs, think it's the right change esp now that we changed to this design in the main mega menu. 

* More space efficient (needs less indenting) 

Open question

* Size of caret (collapse/expand) button (Changed it to md in PR ) 

https://github.com/user-attachments/assets/b5dc9090-da1e-4791-90ce-ae4fc641c675

### CODE REVIEW

**Comment by staton-hyse11** [comment]
This is a move in the right direction! Can the chevron directions be adjusted with this PR too? 

Have **pointing down when collapsed** and have it **pointing up when expanded**

**Comment by torkelo** [comment]
@staton-hyse11 yes, changed it so that it's the same as in the mega menu (Down when collapsed, up when expanded)

**Review by staton-hyse11 — APPROVED** [review]
LGTM!

**Review by Ijin08 — APPROVED** [review]
LGTM!

**Pull request merged**
