### PR TITLE
Azure Monitor: Fix multi-resource bug "Missing required region params, requested QueryParams: api-version:2017-12-01-preview..."

### PR DESCRIPTION
**Pull request by bossinc**
Resource group was not added to the query when multiple resources were selected. I removed the check when building the resource uri. This fixes https://github.com/grafana/support-escalations/issues/8761 

Old:
image

Now:
image

This did not seem to affect any of the other queries I tested. This check was originally added with https://github.com/grafana/grafana/pull/70864 VM instances with "Inbound Flows" still works as expected.
@asimpson Let me know if you know of something unexpected that this change will cause.

### CODE REVIEW

**Comment by aangelisc** [comment]
I'm unconvinced this is the problem. Testing on our instance I see this right now:

image

I'd also be careful removing this incase we encounter a similar issue that @asimpson fixed by introducing this 😊

**Review by asimpson — CHANGES_REQUESTED** [review]
The bug that was fixed in #70864 is re-introduced if we do this change. 

To see this:

* Select two virtual machines 
* Attempt to query 'Inbound Flows''
* Note the `400` error.

image

**Review by asimpson — APPROVED** [review]
Let's go :rocket: nice work on this! 

Merge whenever drone builds :white_check_mark:

**Review by aangelisc — APPROVED** [review]
Nice work @bossinc 😊 We should definitely investigate the `customNamespace` bug you discovered. Would you mind opening an issue for it?

**Pull request merged**
