### PR TITLE
Explore: Remove data source onboarding page

### LINKED ISSUE #66290: Dashboards: Explore page is not accessible when /api/datasources/ fails
### Background

The related issue described in https://github.com/grafana/grafana/issues/66181

### Issue and steps to reproduce

When `datasourceOnboarding` is enabled and `/api/datasources/` endpoint fails:

* The code in https://github.com/grafana/grafana/blob/v9.4.7/public/app/features/datasources/state/actions.ts#L151 throws an exception and the state is stuck at `isLoading = true`
* The code in https://github.com/grafana/grafana/blob/v9.4.7/public/app/features/explore/EmptyStateWrapper.tsx#L19 returns false and keeps rendering `EmptyStateNoDatasource`
* In EmptyStateNoDatasource: `loading` is then always set to `true` and  https://github.com/grafana/grafana/blob/v9.4.7/public/app/features/datasources/components/EmptyStateNoDatasource.tsx#L50 renders an empty page
* There's a similar code in https://github.com/grafana/grafana/blob/v9.4.7/public/app/features/dashboard/containers/NewDashboardPage.tsx#L19 but this component will be removed soon

### Possible solutions

* ~Do not render EmptyStateNoDatasource if `/api/datasources/` fails, just render the main component.~
* Remove EmptyStateWrapper and EmptyStateNoDatasource to be consistant with the removal of NewDashboardPage.

### PR DESCRIPTION
**Pull request by harisrozajac**
**What is this feature?**

Since Dashboards team is removing their version of this page (`NewDashboardPage`), we are removing ours too to be consistent. I haven't removed `EmptyStateNoDatasource` as a part of this PR. I imagine Dashboard team will remove it as a part of removing `NewDashboardPage`. 

Fixes https://github.com/grafana/grafana/issues/66290

### CODE REVIEW

**Review by gelicia — DISMISSED** [review]
The original issue ticket wasn't super clear here and left some wiggle room on what we wanted to show when the datasource list didn't work, but I'm fairly certain we just wanted an empty Explore page with the error to display. Is that right @Elfo404 ?

**Comment by harisrozajac** [comment]
> The original issue ticket wasn't super clear here and left some wiggle room on what we wanted to show when the datasource list didn't work, but I'm fairly certain we just wanted an empty Explore page with the error to display. Is that right @Elfo404 ?

In addition to @gelicia comment, I'm wondering when datasource list doesn't work, do we show an empty Explore page only when `datasourceOnboarding` is disabled or we show an empty Explore page in either case? I thought that when `datasourceOnboarding` is enabled it would still make sense to show `EmptyStateNoDatasource` even when the datasource list didn't work, because `EmptyStateNoDatasource` is not relying on the datasource list, but is hitting a different endpoint: /api/plugins.

**Comment by harisrozajac** [comment]
I've updated PR description to reflect the change in direction on this issue.

**Comment by Elfo404** [comment]
2 things: the title should probably be something like `Explore: Make explore page accessible when /api/datasources/ fails` or potentially something more meaningful for users, like `Explore: Remove data source onboarding page`.

2: if we want this to be out for 10.0.0, then we should change the milestone to `10.0.0`, this will make sure the changelog entry will be generated for the correct release.

**Review by Elfo404 — APPROVED** [review]

**Pull request merged**
