### PR TITLE
Core: Replace deprecated jest matcher toBeCalledWith

### PR DESCRIPTION
**Pull request by krishnemd**
**What is this feature?**

Replacing deprecated matcher **toBeCalledWith** in a test code with native counterpart **toHaveBeenCalledWith** .

**Why do we need this feature?**

If this approves will do similar replacement for other test files too.

**Who is this feature for?**

Frontend Testing.

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by chauchausoup** [comment]
Team let me know, there are 38 files still left to be replaced for the same matcher. Give me a green signal and I will work on them on the same PR.

**Comment by chauchausoup** [comment]
I want to comment on yarn:pseudo which is on pre commit hook but on recent changes we have removed it from package.json file. I have skipped pre commit hook to get this PR. May be someone can comment on that one ?

**Comment by chauchausoup** [comment]
Hey @ashharrison90 sorry to bother you, aren't you guys planning to review the PR ?😁

**Review by ashharrison90 — APPROVED** [review]
> Hey @ashharrison90 sorry to bother you, aren't you guys planning to review the PR ?😁

sorry! grafana is a big project. unless something gets put on our board, i'm very unlikely to be browsing through the ~300 open PRs 😅 

thanks for this, lgtm 👍

**Comment by ashharrison90** [comment]
@chauchausoup we recently moved up a go version, so i think you may need to merge or rebase with main to get the CI to pass correctly

**Review by aangelisc — APPROVED** [review]

**Comment by joshhunt** [comment]
Thanks for the work on this @chauchausoup!

**Pull request merged**
