### PR TITLE
Dashboard: Adds recording of requests/responses

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Sometimes as a frontend maintainer of Grafana it's very hard to reproduce incoming issues. Usually we ask the reporter if they can share their dashboard json or data using the Panel Inspect feature. We've tried to solve this earlier by creating a "complete" report package in this PR #32536. That PR never got merged.

This PR tries to solve the struggle of reproducing issues in a different way. There are two main processes involved in this PR, the first is recording a dashboard and the second is the replay of the recorded dashboard. But  we already have a similar feature for this called snapshots. That's true but the main difference between the feature described in this PR and snapshots is that we can debug/investigate issues from the point a response is received from the backend all the way to the visualisations. Snapshots have the data already attached to panels so you can't really investigate the whole data pipeline and you need to access the snapshot which isn't always possible.

The recording process is initiated by a customer / user with the issue and the second process is initiated by the maintainer trying to reproduce the issue.

### The recording process
The recording process starts with the user clicking on the Share dashboard button
image

A new tab named Record has been added to the Share dashboard modal
image
(If this feature ever goes live we need some help with the english on this tab @achatterjee-grafana)

When the user clicks Start recording we reload the dashboard page and start to record all outgoing requests and incoming responses in `BackendSrv` and record a indicator will indicate the recording status:
dark_stop_recording

To stop the recording the user needs to click the record indicator and then an Export recording modal will appear (this dialog needs some polishing):
image
(If this feature ever goes live we need some help with the english on this dialog too @achatterjee-grafana)

### The replay process
The current solution uses the dashboard import feature to import the exported recordings. As soon as the imported dashboard is loaded all requests to the backend will be intercepted with the recorded responses if Grafana can't find a matching recorded response the "normal" call to the backend will be used instead.
image

A small badge is added to the dashboard header to indicate that this is a recorded dashboard:
image

### Limitations
- Recording dashboards with a relative time range will be needed to be replayed fairly soon after recording, otherwise there wont be data to look at. Maybe the record process should do this?
- Streaming data will not work
- Tested with influx, prom, postgres, mixed but there need to test with more data sources
- Limited to dashboards only

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey Hugo 👋🏾 , this PR is a cool and useful idea, fantastic job 🙌🏾  

I am leaving some feedback regarding user experience, codewise I am a bit lost in the whole flow, I would love to gather more context 🤓 (I will ping you)


**"Record" option living on share:**

I am wondering if adding this option on the share option will confuse users, does it make sense to add a new option instead? 🤔  we could have a "Report  dashboard issue" with the same modal you implemented: 

Starting de recording

> Record dashboard option (the same modal you have right now)

But when stopping the recording:

> Save to file and the link to the GitHub issue template 

**As well, some minor things I found while giving it a spin**

- In the modal, it says that the record stops if we move away from the dashboard, but when I selected a new visualization in the Panel Edit, the recording picked that change, maybe we could add:  

"The recording will automatically stop when you navigate away from the dashboard (the recording will continue working when editing a panel)" ??

- I was able to modify a recorded dashboard, but the "recorded" badge went away, it makes sense because I change the recording, but I think the badge should stay, maybe with a different badge "modified recording" or something like this.

- When I click on "stop recording" if I press "cancel", the record is stopped, but it should continue with the recording.


https://user-images.githubusercontent.com/239999/145823733-86f1c042-e0c1-4fa0-b28b-7c475fd26463.mp4

**Comment by hugohaggmark** [comment]
Great feedback @axelavargas 🙌   

Let's have a chat tomorrow and I can explain the code and you can explain your feedback 👍

**Comment by jessover9000** [comment]
Thanks for the demo earlier today @hugohaggmark , looks awesome :) One thing that came to mind looking at the screenshots here again:

> To stop the recording the user needs to click the record indicator and then an Export recording modal will appear (this dialog needs some polishing)

Could we give a calculation/estimate of the size of the recording in that dialog? If that would make sense to users, that is. We're sort of theoretically warning users there but without actual data it's hard to say whether the warning is useful/needed. Also is there a limit where the recording could lead to problems for free/limited-bandwidth Cloud users or something like that?

**Comment by hugohaggmark** [comment]
> Thanks for the demo earlier today @hugohaggmark , looks awesome :) One thing that came to mind looking at the screenshots here again:

My pleasure!

> > To stop the recording the user needs to click the record indicator and then an Export recording modal will appear (this dialog needs some polishing)
> 
> Could we give a calculation/estimate of the size of the recording in that dialog? If that would make sense to users, that is. We're sort of theoretically warning users there but without actual data it's hard to say whether the warning is useful/needed. Also is there a limit where the recording could lead to problems for free/limited-bandwidth Cloud users or something like that?

Good points. I think the user creating the recording might not care about the size of the recording except when they try to email it and they hit some kind of limit perhaps? The user receiving the recording might care though but as I said I'm not sure. My biggest concern right now is that this doesn't seem to be an OSS feature.
 
> Oh and also, would the recorded dashboard be a duplicate of the original, so if you delete the recorded dashboard the original one is persisted? Maybe there should be feedback about how the recording is saved and how you can delete it again, but without deleting the original dashboard 🤔

So in most cases the recorded dashboard and the original would be in two separate places, the original would be at the customer and the recording would be with the customer support peeps or anyone else investigating the problem. But to answer your question, it depends. When you import the recorded dashboard you'll see a warning if you already have the same dashboard in your system. In the import moment you could choose to either overwrite an existing dashboard or create a duplicate dashboard. This is how dashboard import works today and this PR does not introduce any changes to that. But as I said it's highly unlikely that both the original and the recorded dashboard are on the same Grafana instance. Or at least that is not how this feature is supposed to be used. 

Also, if you delete the recorded dashboard you will only delete that dashboard not the original because they're 2 separate things.

**Comment by hugohaggmark** [comment]
After discussion yesterday I'm not sure this feature is a useful OSS feature, so I'm going to close it.

**Pull request closed without merging**
