### PR TITLE
Test specified AWS Region and not hardcoded us-east-1

### PR DESCRIPTION
**Pull request by utkarshcmu**

### CODE REVIEW

**Comment by mtanda** [comment]
The Billing metrics is only available some of the region.
NOT cn-north-1: it is us-east-1.
cn-north-1: it is cn-north-1.

So the ListMetrics response becomes empty in most of region.
Anyway, current test code doesn't check the response, it is no problem for testing datasource.
If we use other metrics (e.g. CPUUtilization), the response could be empty, we can't avoid the problem.

looks good for me.

**Comment by utkarshcmu** [comment]
Actually, I agree with @mtanda , this solution is just a short term fix and does not guarantee a connection to AWS Cloudwatch. 

Ideally, we should have just 2 checks, hardcoded for now:

1. For **all AWS Regions** : us-east-1
2. For **cn-north-1** : cn-north-1

Also, we should verify the response from AWS, to make sure that Grafana backend connects to AWS for querying Cloudwatch metrics.

I'll make the change to this PR. @mtanda What do you think, doing this is better to make sure that the users really connect to AWS?

**Comment by mtanda** [comment]
In my opinion, we don't have to check the response, because if there is problem in using credentials, we can't get any response.
I'm not sure billing metrics is always available, if user only use free tier service, how the billing metrics become?
So if we check the response, there is possibility to get wrong result for test.

> Ideally, we should have just 2 checks, hardcoded for now:
>    1. For all AWS Regions : us-east-1
>    2. For cn-north-1 : cn-north-1
I agree this part.

**Comment by utkarshcmu** [comment]
Ok, then lets go ahead with this fix only. No changes needed for now in this PR.

@torkelo , please review/merge this PR so that CloudWatch datasource can be used for cn-north-1 region. Currently they are not able to use it, as mentioned in #3114

**Pull request merged**
