### PR TITLE
Add transport cache for reverse proxy

### PR DESCRIPTION
**Pull request by stuartnelson3**
This addresses https://github.com/grafana/grafana/issues/6759

### CODE REVIEW

**Comment by stuartnelson3** [comment]
Note: This could be improved so that non-tls reverse proxies all share the same default transport, instead of creating a reusable transport for each client.

**Comment by bergquist** [comment]
Great! But cache need to be cleared somehow without restarting the servers. Otherwise it would be impossible to fix broken datasource configuration.

I think this should be solved by comparing the cached datasource updated field with the datasource passed to the DataProxyTransport function.

**Comment by stuartnelson3** [comment]
It seems like the only information from the datasource being used is the TLS information (`tlsAuth` and `tlsAuthWithCert`) -- ah so if someone enters a broken tls cert, the only way they could update that in the transport would be turn off tls, and then turn it back on.

Is the datasource updated field already cached somewhere? Or would it be good to have the cache contain a struct of *http.Transport and updatedAt?

**Comment by bergquist** [comment]
Im thinking something like this https://github.com/grafana/grafana/pull/6786

Its such a pain to add code to other peoples PR so I just submitted a new one :/

**Comment by bergquist** [comment]
@torkelo How do you feel about this solution?

I think the code can be cleaned up bit but otherwise I think its ok

**Comment by stuartnelson3** [comment]
Actually I ended up doing exactly what you did pretty much :)

there are a couple small changes, like how the updated at time is being compared

**Comment by bergquist** [comment]
Closed the wrong PR... sorry!

**Comment by stuartnelson3** [comment]
Not a problem, as long as one of them gets merged !

**Comment by bergquist** [comment]
@stuartnelson3 thank you for contributing! :)

**Pull request merged**
