### PR TITLE
DashboardScene: Action toolbar progress

### PR DESCRIPTION
**Pull request by torkelo**
Improving the toolbar actions design to be closer to what we want / latest design by patrick. 

https://github.com/grafana/grafana/assets/10999/99a6aec5-be05-4803-8314-302fce4606b7

### CODE REVIEW

**Comment by torkelo** [comment]
Switch to view mode with confirm:
Uploading switch_to_view_with_confirm.mp4…

I really like this option switch to view mode initially, but as soon as user makes a change the switch to view mode switches to a destructive "Discard changes" making very clear that you have unsaved changes. 
https://github.com/grafana/grafana/assets/10999/e73d8ade-cc38-4f94-a58c-abd6b5c03421

**Review by dprokop — APPROVED** [review]
Think this looks and works great!

**Pull request merged**
