### PR TITLE
use default region to call DescribeRegions

### LINKED ISSUE #13797: Cloudwatch using a hardcoded region when retrieving regions thru DescribeRegions
Team,

[Related to AWS isolated regions only]

I tested the latest changes with the Cloudwatch hardcode issue (https://github.com/grafana/grafana/pull/12337). In deployment, the Grafana server automatically tries to connect to us-east-1, instead of my default region issued to my datasource, which would be us-iso-east-1. I manaully built a new version using us-iso-east-1, and it works just fine. Is there a way we can assume the client to use the datasource default region instead of using us-east-1?

This line is the issue: https://github.com/grafana/grafana/pull/12337/files#diff-1bc1bcaa896482730fda8a2d539fb247R242

Steve

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/13797

### CODE REVIEW

**Comment by buroa** [comment]
Thanks @mtanda

**Comment by buroa** [comment]
This worked in the region today. Thanks.

**Comment by mtanda** [comment]
Thanks for testing!

**Comment by torkelo** [comment]
Thanks mtanda!

**Pull request merged**
