### PR TITLE
Scenes/Dashboards: Add support for systemPanelFilterVar and systemDynamicRowSizeVar variables in scenes

### PR DESCRIPTION
**Pull request by kaydelaney**
This PR adds support for the `systemPanelFilterVar` and `systemDynamicRowSizeVar` variables in scenes via a new behavior, `PanelSearchBehavior`.
As a follow-up to this PR, I'd like to expose the SceneGridLayout `_skipOnLayoutChange` property so changes to the layout caused by this feature aren't persisted.

Edit: Follow-up PR https://github.com/grafana/scenes/pull/849

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
Hey @kaydelaney 👋🏾 , very nice progress with this one, I did a local test and found a couple of issues:

**Searching by panel title**
- Searching by panel title does not work for interpolated variables, in my case, I repeated a panel by a variable and I was searching for it, but did not work.

https://github.com/user-attachments/assets/550c8919-f880-4d77-a988-efc8997fe458


- When a search doesn't return results, I see the empty dashboard state, that's a bit confusing, I think we should show no results or something.
image

**Resize rows**
- Resizes rows are not working for repeated panels

https://github.com/user-attachments/assets/54c794f6-3c30-4de1-bc00-027d4b4828ce

- When I am using both options, they are conflicting with each other, and sometimes the filtering by title does not work


https://github.com/user-attachments/assets/7537cf87-33a2-47f6-a5a7-def0df23dbe3

**Comment by kaydelaney** [comment]
Spent some time yesterday refamiliarizing myself with the issue and the code written so far. Before PTO I think I had tried to fix the issue with searching for a panel title substring after vars etc. have been processed by just finding every `VizPanel` and filtering for any whose interpolated title matches the search string, but this won't work in every case since row repeats are lazily evaluated/activated and won't be present in the scene tree unless the repeat panel has been scrolled into view.
I guess to work around this you could generate the list of panel titles based on what variable values are currently selected and then add/activate any repeats whose title matches the search string, but I don't really like the idea of doing that, especially since it seems messier and more work than the previous approach https://github.com/grafana/scenes/pull/845

What do you think @axelavargas ? Do you have any ideas?

**Comment by axelavargas** [comment]
> What do you think @axelavargas ? Do you have any ideas?

🤔 I believe we have hit a limitation with the behavior approach.  As I understand when searching in panel repeat scenarios this code returns false:

https://github.com/grafana/grafana/blob/37a703a8d3835fef017e0d89fdf758e0aca8ba75/public/app/features/dashboard-scene/scene/PanelSearchBehavior.tsx#L76

As you mentioned, there are two problems, the match not finding the repeated panel that contains a variable interpolation and panel repeats not being present in the scene tree if they are not scrolled into view.  

For the first problem, I tried extending the logic of this code to consider the `repeatedPanels` property, however, when trying to interpolate the titles of each panel, I got the interpolated values in a format like this `Panel title {var1, var1}`, making it impossible to filter the right repeated panel. 

I don't have any more ideas in mind 😅 , let's revisit the initial approach (Scenes PR).

**Review by axelavargas — COMMENTED** [review]
btw forgot to add a playground branch with the extended logic of checking `repeatedPanels` prop
https://github.com/grafana/grafana/compare/panel-search-behavior...axleav/play-branch-panel-search-behavior

**Review by axelavargas — COMMENTED** [review]
Hey @kaydelaney 👋🏾 ,  I gave it another test using a static dashboards (no repeats involved) and I found a bug 🐛.

#### Panels are removed from Dashboard JSON after searching by title and editing a panel

https://github.com/user-attachments/assets/01bbbf52-cd26-4b33-948e-eee68d57481d

**Comment by kaydelaney** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/93670

**Pull request closed without merging**
