### PR TITLE
PostgreSQL should not cast all times to uint64

### LINKED ISSUE #11530: PostgreSQL datasource generates invalid query with dates before 1970
When trying to query dates before 1970, the SQL connector generates incorrect query.

With the time range: 1960-1980:
&from=-315622800000&to=315529200000

The query generated from `$__timeFilter(column)`
```
AND extract(epoch from date) BETWEEN 18446744073393928816 AND 315529200
```

When I try using `$__timeFrom()` it will generate:
```
AND date between to_timestamp(18446744073393928816) and to_timestamp(315529200)
```

### PR DESCRIPTION
**Pull request by ryantxu**
The PostgreSQL (and it looks like some other) SQL connectors cast the date to uint64.  This breaks things before the epoch (1970) and does not really add precision in the future since the original value is an int64

The patch is really just search and replace for uint64

This fixes #11530

### CODE REVIEW

**Comment by ryantxu** [comment]
I added the same change to MSSQL and MYSQL, but don't have anyway to test them

------

For the number of times this calls 'int64(m.TimeRange.GetFromAsMsEpoch()/1000))', perhaps we should just add these functions to `time_range.go`
```
func (tr *TimeRange) GetFromAsEpoch() int64 {
	return tr.MustGetFrom().UnixNano() / int64(time.Seconds)
}

func (tr *TimeRange) GetToAsEpoch() int64 {
	return tr.MustGetTo().UnixNano() / int64(time.Seconds)
}
```

**Comment by marefr** [comment]
Hey @ryantxu if you have docker and docker-compose installed you can do the following to get postgres, mysql and mssql test containers suitable for running the tests.

```bash
cd docker
./create_docker_compose.sh mssql_tests mysql_tests postgres_tests
docker-compose up
```

**Comment by svenklemm** [comment]
@ryantxu I had a quick look at this before i saw your pr and did some debugging and I think those casts are there only to make the tests happy cause it seems if you initialize a timerange without setting now now is max uint. So the cast was necessary to make the checks happy. I think its probably best to change the tests and add an explicit now that is less then max int64

**Comment by ryantxu** [comment]
Thanks @svenklemm!  I was wondering why every test is failing (i have no real understanding of go).  Yes, i think it makes sense to change the test so it does not default now() to the max value

**Comment by marefr** [comment]
@ryantxu if you can fix the failing tests for mysql, apply same fixes for mssql and include the epoch before 1970 test for mysql and mssql I can review and test (manually). You should still be able to verify the tests sql macros tests in go since they not require db access. That is if you have any golang environment setup :smile: 

```bash
go test -v ./pkg/tsdb/...
```

Otherwise let me know and we can take it from here.

**Comment by ryantxu** [comment]
thanks @marefr -- I won't have time to focus on this for a few days, so if you can take a look that would be great.  

My go environment will build but not run tests :(  I'll bite the bullet someday and fix that.

**Comment by marefr** [comment]
@ryantxu gonna take a look. Will push my changes to your repo. Probably need to rebase and force push.

**Comment by ryantxu** [comment]
Looks great.  Do we want the cast to int64 now that you added a function already returns an int64
> int64(m.TimeRange.GetFromAsSecondsEpoch())

**Comment by marefr** [comment]
Good catch will fix Thanks :+1:

**Review by daniellee — APPROVED** [review]
Looks good to me.

**Pull request merged**
