### PR TITLE
Grafana.net OAuth login support

### PR DESCRIPTION
**Pull request by DanCech**
This PR implements #6076

It relies on functionality on Grafana.net which is not yet released, but any feedback on coding style etc is appreciated.

The code itself is based on the Github authentication provider.

### CODE REVIEW

**Comment by torkelo** [comment]
looks good. 

Just confused by the allowedOrganizations option. I thought the oauth clientId & secret would be associated with a Grafana.net organization already.

**Comment by DanCech** [comment]
That's a good question, the thought was that users might want to support members of multiple grafana.net orgs logging into their instance.  Also the grafana instance doesn't "know" which grafana.net org it's registered as a client under.

We could change things around so that grafana.net only allows members of the same org the client is registered under to authorize it, or to allow specifying the allowed orgs in the grafana.net client definition and blocking non-authorized users that way.

**Comment by DanCech** [comment]
The latest commit adds support for `social` `BasicUserInfo` to include a `Role` element, which will override the `users.auto_assign_org_role` config setting if it's returned by the OAuth module.

**Comment by bergquist** [comment]
This should also be documented in https://github.com/grafana/grafana/blob/master/docs/sources/installation/configuration.md#authgithub before merging.

**Comment by DanCech** [comment]
Now I'm under the gun ;)

**Pull request merged**
