### PR TITLE
Geomap: Dynamic geojson reset on data refresh

### LINKED ISSUE #55626: Geomap: Dynamic Geojson Style Mapping
**What happened**
When using the **awesome** Geomap plugin, when you use the dynamic Geojson configuration for your layer, the mapping between the query & the geojson layer does not reset itself when refreshing the data.

**What you expected to happen**
The mapping between the 2 should reset, for instance if you want to Zoom in or out on the timerange to colorize elements.

To fix, i think you probably need to fix : 

geojsonDynamic.ts:172
```
if (frame) {
          const field = findField(frame, config.idField);
          if (field) {
            field.values.toArray().forEach((v, i) => idToIdx.set(v, i));
          }

          style.dims = getStyleDimension(frame, style, theme, config.dataStyle);
        }

```

to
```
if (frame) {
          const field = findField(frame, config.idField);
          if (field) {
            idToIdx.clear():
            field.values.toArray().forEach((v, i) => idToIdx.set(v, i));
          }

          style.dims = getStyleDimension(frame, style, theme, config.dataStyle);
        }

```

**Environment**:
- Grafana version: 9.1.6

### PR DESCRIPTION
**Pull request by janicaud**
**What this PR does / why we need it**:
Reset the mapping table for Dynamic Geojson

**Which issue(s) this PR fixes**: 

Fixes #55626

### CODE REVIEW

**Comment by janicaud** [comment]
Should i do something ?

**Comment by mellieA** [comment]
@janicaud thank you for contributing this fix! I've added the PR to the Edge squad's project board for review.

**Review by nmarrs — APPROVED** [review]
LGTM

**Comment by nmarrs** [comment]
@drew08t If this looks good to you, let's merge and include as patch to 9.1.x / in 9.2 release 👍

**Review by drew08t — APPROVED** [review]
LGTM

**Pull request merged**
