### PR TITLE
Variables: improve performance of transformMetricFindResponse

### PR DESCRIPTION
**Pull request by DireLines**
Hello, I use Grafana dashboards at work with Postgres as the datasource and we have had performance issues looking at data over any timescale larger than a few days. The graphs load just about as fast as the SQL queries, but the variable dropdowns take absolutely ages (~4 minutes when looking at the past 30 days) even though the queries to populate them run very quickly (~200 ms), and the client spends a lot of CPU in the process.

We have very high cardinality dropdowns on our dashboards. Removing them or artificially reducing the cardinality of the fields fixes the long page load times. Based on [Firefox profiler output](https://share.firefox.dev/3ww9ZDH) I believe the code in `transformMetricFindResponse` is taking O(n^2) time where n is the number of values returned from the SQL query. This PR makes the runtime O(n) for the last step of deduping the text-value pairs by text, as can be seen in [this example](https://ramdajs.com/repl/#?const%20keepFirstSlow%20%3D%20values%20%3D%3E%20Array.from%28new%20Set%28values.map%28%28v%29%20%3D%3E%20v.text%29%29%29.map%28%28text%29%20%3D%3E%20%28%7Btext%2Cvalue%3A%20values.find%28%28v%29%20%3D%3E%20v.text%20%3D%3D%3D%20text%29.value%7D%29%29%0Aconst%20keepFirst%20%3D%20uniqBy%28prop%28%27text%27%29%29%0Aconst%20uniqueBy%20%3D%20%28fn%2Clist%29%20%3D%3E%20%7B%0A%20%20const%20set%20%3D%20%7B%7D%3B%0A%20%20const%20result%20%3D%20%5B%5D%3B%0A%0A%20%20for%20%28const%20item%20of%20list%29%20%7B%0A%20%20%20%20const%20appliedItem%20%3D%20fn%28item%29%3B%0A%20%20%20%20if%20%28%21%28appliedItem%20in%20set%29%29%20%7B%0A%20%20%20%20%20%20set%5BappliedItem%5D%20%3D%200%3B%0A%20%20%20%20%20%20result.push%28item%29%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20result%3B%0A%7D%0Aconst%20keepFirstHandmade%20%3D%20values%20%3D%3E%20uniqueBy%28%28%7Btext%7D%29%3D%3Etext%2Cvalues%29%20%2F%2Fno%20dependencies%0Aconsole.log%28%22correctness%3A%22%29%0Aconst%20example%20%3D%20%5B%0A%20%20%7Btext%3A%22a%22%2Cvalue%3A5%7D%2C%7Btext%3A%22a%22%2Cvalue%3A6%7D%2C%7Btext%3A%22b%22%2Cvalue%3A5%7D%2C%7Btext%3A%22a%22%2Cvalue%3A7%7D%2C%7Btext%3A%22b%22%2Cvalue%3A1%7D%2C%7Btext%3A%22c%22%2Cvalue%3A5%7D%2C%0A%5D%0Aconsole.log%28%22keepFirstSlow%3A%22%2CkeepFirstSlow%28example%29%29%0Aconsole.log%28%22keepFirst%3A%22%2CkeepFirst%28example%29%29%0Aconsole.log%28%22keepFirstHandmade%3A%22%2CkeepFirstHandmade%28example%29%29%0A%0A%0A%0Aconst%20getRandomInt%20%3D%20max%20%3D%3E%20%7B%0A%20%20return%20Math.floor%28Math.random%28%29%20%2A%20max%29%3B%0A%7D%0Aconsole.log%28%22array%20of%20length%2030000%2C%20with%20mostly%20unique%20keys%3A%22%29%0Aconst%20stuff%20%3D%20Array.from%28Array%2830000%29%29.map%28%28%29%3D%3E%28%7Btext%3AgetRandomInt%28100000%29%2Cvalue%3AgetRandomInt%283000%29%7D%29%29%0A%0Aconst%20elapsedTimeLogger%20%3D%20namespace%20%3D%3E%20%7B%0A%20%20let%20startTimeThisStage%20%3D%20Date.now%28%29%0A%20%20const%20prefix%20%3D%20namespace%20%3F%20%60%24%7Bnamespace%7D%3A%20%60%3A%20%27%27%0A%20%20return%20message%20%3D%3E%20%7B%0A%20%20%20%20const%20now%20%3D%20Date.now%28%29%0A%20%20%20%20const%20elapsed%20%3D%20now%20-%20startTimeThisStage%0A%20%20%20%20startTimeThisStage%20%3D%20now%0A%20%20%20%20console.log%28%60%24%7Bprefix%7D%24%7Bmessage%7D%20took%20%24%7Belapsed%7D%20ms%60%29%0A%20%20%7D%0A%7D%0Aconst%20logElapsedTime%20%3D%20elapsedTimeLogger%28%29%0AkeepFirst%28stuff%29%0AlogElapsedTime%28%27keepFirst%27%29%0AkeepFirstHandmade%28stuff%29%0AlogElapsedTime%28%27keepFirstHandmade%27%29%0AkeepFirstSlow%28stuff%29%0AlogElapsedTime%28%27keepFirstSlow%27%29).

Things that still need done if approved:

- Move the `uniqueBy` helper function to some shared library so that it isn't duplicated in all 3 response parsers that follow this pattern. Alternatively, if there is some 3rd party library grafana devs prefer, like Ramda or Underscore, the `uniqBy` function probably exists for it.
- If this does not improve the runtime with high cardinality dropdowns, there may be another expensive step I missed.

### CODE REVIEW

**Comment by mdvictor** [comment]
Hello and thanks for submitting! 
I am not sure that this fixes an issue. The modification does reduce complexity to O(n) but I think it will still perform more slowly with larger length arrays because the function is looping through all values while the initial code maps through a list of unique values resulted from the `Set`.

**Comment by DireLines** [comment]
I see where you're coming from but the timing measurements say otherwise.

There are two parameters here, the size of the array _n_ and the number of distinct elements in the array _d_.
When _d_ is small, both versions perform fine for large _n_, so changing between them doesn't matter. When _d_ and _n_ are both large, my version still performs fine but the current code does not.

I will adjust my code examples to show timings on different input sizes. Please read the examples carefully so you can see what I tested. [Here](https://ramdajs.com/repl/#?const%20keepFirstSlow%20%3D%20values%20%3D%3E%20Array.from%28new%20Set%28values.map%28%28v%29%20%3D%3E%20v.text%29%29%29.map%28%28text%29%20%3D%3E%20%28%7Btext%2Cvalue%3A%20values.find%28%28v%29%20%3D%3E%20v.text%20%3D%3D%3D%20text%29.value%7D%29%29%0Aconst%20keepFirst%20%3D%20uniqBy%28prop%28%27text%27%29%29%0Aconst%20uniqueBy%20%3D%20%28fn%2Clist%29%20%3D%3E%20%7B%0A%20%20const%20set%20%3D%20%7B%7D%3B%0A%20%20const%20result%20%3D%20%5B%5D%3B%0A%0A%20%20for%20%28const%20item%20of%20list%29%20%7B%0A%20%20%20%20const%20appliedItem%20%3D%20fn%28item%29%3B%0A%20%20%20%20if%20%28%21%28appliedItem%20in%20set%29%29%20%7B%0A%20%20%20%20%20%20set%5BappliedItem%5D%20%3D%200%3B%0A%20%20%20%20%20%20result.push%28item%29%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20result%3B%0A%7D%0Aconst%20keepFirstHandmade%20%3D%20values%20%3D%3E%20uniqueBy%28%28%7Btext%7D%29%3D%3Etext%2Cvalues%29%20%2F%2Fno%20dependencies%0Aconsole.log%28%22correctness%3A%22%29%0Aconst%20example%20%3D%20%5B%0A%20%20%7Btext%3A%22a%22%2Cvalue%3A5%7D%2C%7Btext%3A%22a%22%2Cvalue%3A6%7D%2C%7Btext%3A%22b%22%2Cvalue%3A5%7D%2C%7Btext%3A%22a%22%2Cvalue%3A7%7D%2C%7Btext%3A%22b%22%2Cvalue%3A1%7D%2C%7Btext%3A%22c%22%2Cvalue%3A5%7D%2C%0A%5D%0Aconsole.log%28%22keepFirstSlow%3A%22%2CkeepFirstSlow%28example%29%29%0Aconsole.log%28%22keepFirst%3A%22%2CkeepFirst%28example%29%29%0Aconsole.log%28%22keepFirstHandmade%3A%22%2CkeepFirstHandmade%28example%29%29%0A%0Aconst%20elapsedTimeLogger%20%3D%20namespace%20%3D%3E%20%7B%0A%20%20let%20startTimeThisStage%20%3D%20Date.now%28%29%0A%20%20const%20prefix%20%3D%20namespace%20%3F%20%60%24%7Bnamespace%7D%3A%20%60%3A%20%27%27%0A%20%20return%20message%20%3D%3E%20%7B%0A%20%20%20%20const%20now%20%3D%20Date.now%28%29%0A%20%20%20%20const%20elapsed%20%3D%20now%20-%20startTimeThisStage%0A%20%20%20%20startTimeThisStage%20%3D%20now%0A%20%20%20%20console.log%28%60%24%7Bprefix%7D%24%7Bmessage%7D%20took%20%24%7Belapsed%7D%20ms%60%29%0A%20%20%7D%0A%7D%0Aconst%20getRandomInt%20%3D%20max%20%3D%3E%20%7B%0A%20%20return%20Math.floor%28Math.random%28%29%20%2A%20max%29%3B%0A%7D%0A%2F%2Flarge%20array%20with%20few%20distinct%20values%0Aconst%20fewDistinct%20%3D%20Array.from%28Array%28100000%29%29.map%28%28%29%3D%3E%28%7Btext%3AgetRandomInt%28100%29%2Cvalue%3AgetRandomInt%283000%29%7D%29%29%0Alet%20logElapsedTime%20%3D%20elapsedTimeLogger%28%22n%3D100000%2Cd%E2%89%88100%22%29%0AkeepFirst%28fewDistinct%29%0AlogElapsedTime%28%27keepFirst%27%29%0AkeepFirstHandmade%28fewDistinct%29%0AlogElapsedTime%28%27keepFirstHandmade%27%29%0AkeepFirstSlow%28fewDistinct%29%0AlogElapsedTime%28%27keepFirstSlow%27%29%0A%0A%2F%2Ffind%20can%20still%20iterate%20over%20the%20entire%20array%20in%20the%20worst%20case%0Aconst%20worstCaseFind%20%3D%20Array.from%28Array%28100000%29%29.map%28%28%29%3D%3E%28%7Btext%3A0%2Cvalue%3AgetRandomInt%283000%29%7D%29%29%0Afor%20%28let%20i%20%3D%201%3B%20i%20%3C%2020%3B%20i%2B%2B%29%7B%0A%20%20worstCaseFind.push%28%7Btext%3Ai%2Cvalue%3AgetRandomInt%283000%29%7D%29%0A%7D%0AlogElapsedTime%20%3D%20elapsedTimeLogger%28%22n%3D100000%2Cd%3D20%2Cworst%20case%22%29%0AkeepFirst%28worstCaseFind%29%0AlogElapsedTime%28%27keepFirst%27%29%0AkeepFirstHandmade%28worstCaseFind%29%0AlogElapsedTime%28%27keepFirstHandmade%27%29%0AkeepFirstSlow%28worstCaseFind%29%0AlogElapsedTime%28%27keepFirstSlow%27%29%0A%0A%2F%2Flarge%20array%20with%20many%20distinct%20values%0Aconst%20manyDistinct%20%3D%20Array.from%28Array%28100000%29%29.map%28%28%29%3D%3E%28%7Btext%3AgetRandomInt%28100000%29%2Cvalue%3AgetRandomInt%283000%29%7D%29%29%0AlogElapsedTime%20%3D%20elapsedTimeLogger%28%22n%3D100000%2Cd%E2%89%88100000%22%29%0AkeepFirst%28manyDistinct%29%0AlogElapsedTime%28%27keepFirst%27%29%0AkeepFirstHandmade%28manyDistinct%29%0AlogElapsedTime%28%27keepFirstHandmade%27%29%0AkeepFirstSlow%28manyDistinct%29%0AlogElapsedTime%28%27keepFirstSlow%27%29%0A) is the code being run and here is the timing output:
```
n=100000,d≈100: keepFirst took 6 ms
n=100000,d≈100: keepFirstHandmade took 5 ms
n=100000,d≈100: keepFirstSlow took 6 ms
n=100000,d=20,worst case: keepFirst took 4 ms
n=100000,d=20,worst case: keepFirstHandmade took 6 ms
n=100000,d=20,worst case: keepFirstSlow took 20 ms
n=100000,d≈100000: keepFirst took 8 ms
n=100000,d≈100000: keepFirstHandmade took 12 ms
n=100000,d≈100000: keepFirstSlow took 9758 ms
```

As you can see, all approaches are very quick when _d_ is small. The case I want to fix is when _d_ is large, and the asymptotic behavior really does matter.

I know I didn't formally raise an issue that this PR fixes, but it really is causing daily slowness for my team on a dashboard we check all the time, and I thought surely there must be somebody else who uses these dropdown variables as a way to filter on many distinct values. Thanks for your consideration.

**Comment by mdvictor** [comment]
I see what you mean and I agree with you.
It is true that in the case of a large array with already distinct items the old code is rather slow.

The handmade code does a really good job, but since we have `lodash` we should make use of its `uniqBy` function for this. 

It seems to perform fairly similar to your handmade version (although your code is faster in small array length cases), but is really fast in the case presented above with large *n* and *d*, cutting even the handmade version with some good miliseconds. Here is an example:
https://stackblitz.com/edit/typescript-lodash-playground-vm13vs?file=index.ts

**Comment by DireLines** [comment]
Excellent, yes please use the lodash code and ignore the handmade one. I just made that because I wasn’t sure which library grafana typically uses for little utils like that. Thank you!

**Comment by DireLines** [comment]
Hey @mdvictor I was trying to change the code to use lodash but I’m on vacation right now and don’t have a good work setup. Last I checked I think I made the linter happy but there were new tests introduced since I forked grafana that my code failed, so this needs a rebase or something before merge

**Review by mdvictor — APPROVED** [review]

**Comment by mdvictor** [comment]
Thank you for your contribution @DireLines. This is great! Merging it right away!

**Pull request merged**
