### PR TITLE
Increase the height of the spark lines

### PR DESCRIPTION
**Pull request by skundrik**
Simple change to increase the canvas height to allow better space usage for small panels in background mode. I think it looks much neater and makes the changes more visible.

**After change:**

image

### CODE REVIEW

**Comment by torkelo** [comment]
do you have a before / after comparison screenshot?

**Comment by skundrik** [comment]
This is one from before

image

**Comment by skundrik** [comment]
@torkelo Is this good to merge?

**Comment by utkarshcmu** [comment]
How about making this a configurable field instead of hardcoding values?

**Comment by skundrik** [comment]
I know what you mean and I was already thinking about how to make it better. However this PR was just supposed to fix a simple problem making the sparklines more useful. If I get some time over Christmas I'll put something together as a new pull.

**Comment by utkarshcmu** [comment]
:+1:

**Comment by bergquist** [comment]
This change makes sense. And it looks better for small panels but I prefer the old height for larger panels. So I made it dynamic instead https://github.com/grafana/grafana/commit/5de69b288f0ff4540188b5415b1073e3ad20c256

**Pull request closed without merging**
