### PR TITLE
Add doc-validator tool to CI

### PR DESCRIPTION
**Pull request by jdbaldry**
**What this PR does / why we need it**:

Adds a CI step for pull requests that validates links in technical documentation and performs linting of technical documentation source files.

Source code:
https://github.com/grafana/technical-documentation/tree/main/tools/doc-validator

**Special notes for your reviewer**:

- There's a lot to fix before we can merge this.
- The tool is still in early development so each error should be scrutinized for validity.

### CODE REVIEW

**Comment by brendamuir** [comment]
Let me know if/how I can help fix anything to make this work! I think it'll help our Grafana repo a lot!

**Comment by brendamuir** [comment]
@armandgrillet for visibility.

**Review by chri2547 — APPROVED** [review]

**Comment by armandgrillet** [comment]
Could we run the validator only on files updated in the PR so that we can iterate on this? Otherwise we could just fix everything before this PR gets merged (we will do so for Alerting docs, according to a 1:1 I had with @brendamuir today).

**Comment by jdbaldry** [comment]
> Could we run the validator only on files updated in the PR so that we can iterate on this? Otherwise we could just fix everything before this PR gets merged (we will do so for Alerting docs, according to a 1:1 I had with @brendamuir today).

Not with a change to the tool and a change to the GitHub workflow. I don't think I will have time to make both of these changes before I leave for holiday tomorrow.

The tool needs to be updated to accept a list of files to consider, and to maintain backwards compatibility, it will need to check all files if no arguments are provided.

Not with a change to the tool and a change to the GitHub workflow. I don't think I will have time to make both of these changes

The CI needs to be updated to determine just the changed files and pass them to the subsequent doc-validator step.

**Pull request merged**
