### PR TITLE
Navigation: Independent docked state

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- separates the docked/open megamenu states so they behave as separate independent toggles

**Why do we need this feature?**

- clearer behaviour (see e.g. [this feedback](https://raintank-corp.slack.com/archives/C01LENC4MD5/p1700485636567279))

**Who is this feature for?**

- everyone!

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by eledobleefe** [comment]
@ashharrison90, looks good! Why is this a draft PR? Is there something missing?

**Comment by ashharrison90** [comment]
nothing missing behaviour-wise, just wanna confirm we're happy with that behaviour and then refactor the code slightly

**Review by eledobleefe — APPROVED** [review]
Tested on local and looks good 🎉 
It even keeps the menu docked on a new window 👌

**Pull request merged**
