### PR TITLE
Add Google Hangouts Chat notifier.

### PR DESCRIPTION
**Pull request by PatrickSchuster**
Addressing my feature request: https://github.com/grafana/grafana/issues/11221

### CODE REVIEW

**Comment by PatrickSchuster** [comment]
Hi,
even though it says "Contributor License Agreement is not signed yet.", it tells me that I have already signed the CLA for grafana/grafana when I click on "Details". :confused:

**Comment by innovia** [comment]
Can anyone can please review this PR?

**Comment by fabianschoenleitner** [comment]
Can anyone please review this PR? 
Thank you

**Comment by ondrejFuchs** [comment]
Please, can you post (or send) more information about how to set this pull request (two new files) in official grafana instalation to start use it. I have official grafana in docker, but I don't know how change it to add this feature. I set up google webhook and now I need to setup grafana.

Thanks to your reply.

**Comment by PatrickSchuster** [comment]
@ondrejFuchs you can checkout this pull request and build grafana from source. see the documentation: http://docs.grafana.org/project/building_from_source/

**Review by bergquist — CHANGES_REQUESTED** [review]
This alert notifier needs to be added to the docs in https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md 

Once that is added this can be merged.

**Comment by bergquist** [comment]
Google chat rewrites any links back to grafana from http to https. Which makes sense for a publicly hosted Grafana but on-prem grafana might not always have https. Not sure how this should be handled. One option would be to only link back to grafana if its https.

**Comment by MPV** [comment]
@PatrickSchuster Will you add this to the readme as a supported notification type, so this can be merged? 😊 

https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md#supported-notification-types

**Comment by MPV** [comment]
@PatrickSchuster Oh, of course! 
🎉 Enjoy the holiday. ⛱

**Comment by PatrickSchuster** [comment]
@MPV I just updated the ReadMe, although codecov does not seem to be happy with my latest change. Did I do something wrong? 🤔

**Comment by MPV** [comment]
@PatrickSchuster Seems there's a conflict in `docs/sources/alerting/notifications.md` that you need to merge. 😊

**Comment by MPV** [comment]
@bergquist What's your view on the failing `codecov`, how can we help @PatrickSchuster here? 😊

**Comment by marefr** [comment]
You probably need to merge in master/rebase to get rid of the codecov stuff plus the conflict.

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
Thank you for contributing to Grafana! :) Sorry for my slow reviews.

**Comment by wreiske** [comment]
Now we need https://rocket.chat/ !

**Pull request merged**
