### PR TITLE
DSPicker: Use new DS picker everywhere

### LINKED ISSUE #66916: Use new DS Picker in the rest of Grafana products
Having the DS picker stable in the dashboard panel edit, we can implement the picker everywhere else.

- [x] Find and replace any usage of DataSourcePicker from `@grafana/data` and use the DataSourcePicker from `app/features/datasources/picker`
- [x] Add any missing prop to `DataSourcePicker` that might be required out of the edit panel

### PR DESCRIPTION
**Pull request by ivanortegaalba**
**What is this feature?**

Use the new DS picker in the rest of the Grafana UI.

The new DS picker contains different improvements:
1. Aggregated category to indicate the type of DS you're selecting
2. An advanced DS picker based on a modal to improve the discoverability of Grafana Data Sources
3. SVG uploader if enabled
4. CTA to add a new DS in case there are no results

This PR affects the following places:

**`public/app/core/components/TraceToLogs/TraceToLogsSettings.tsx`**
Test it by adding a new Jaeger DS.

|Before|After
|-|-|
Captura de pantalla 2023-07-12 a las 20 23 56|Captura de pantalla 2023-07-12 a las 20 23 34

**`public/app/core/components/TraceToMetrics/TraceToMetricsSettings.tsx`**
Test it by adding a new Jaeger DS.
|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 32 28|Captura de pantalla 2023-07-12 a las 20 31 30

**`public/app/features/alerting/unified/components/rule-editor/CloudRulesSourcePicker.tsx`**
Test it by adding a new alert using Mimir or Loki. 
|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 33 56|Captura de pantalla 2023-07-12 a las 20 45 50

**public/app/features/correlations/Forms/ConfigureCorrelationSourceForm.tsx** and **`public/app/features/correlations/Forms/ConfigureCorrelationTargetForm.tsx`**
Configure a new correlation. Enable `correlations` FF
|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 35 04|Captura de pantalla 2023-07-12 a las 20 49 15

**public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx** 
Add an annotation to an existing dashboard
|Before|After
|-|-|
Captura de pantalla 2023-07-12 a las 20 52 54|Captura de pantalla 2023-07-12 a las 20 52 22

**`public/app/features/manage-dashboards/components/ImportDashboardForm.tsx`**
Export a dashboard for public consumption. Then import that dashboard. A DS picker will be offered to choose the new DS to use.

|Before|After
|-|-|
Captura de pantalla 2023-07-13 a las 17 24 45|Captura de pantalla 2023-07-13 a las 17 20 44

**`public/app/features/variables/adhoc/AdHocVariableEditor.tsx`**
Add an ad-hoc variable to a dashboard

|Before|After
|-|-|
Captura de pantalla 2023-07-13 a las 17 23 46|Captura de pantalla 2023-07-13 a las 17 26 49

**`public/app/features/variables/query/QueryVariableEditor.tsx`**
Add a query variable to a dashboard
|Before|After
|-|-|
Captura de pantalla 2023-07-13 a las 17 28 13|Captura de pantalla 2023-07-13 a las 17 27 41

**`public/app/plugins/datasource/cloudwatch/components/XrayLinkConfig.tsx`**
Add a Cloudwatch DS and the DS picker is part of the config form
|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 00 32|Captura de pantalla 2023-07-14 a las 12 00 40

**`public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx`**
Add a Elastic DS and the DS picker is part of the config form
|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 03 21|Captura de pantalla 2023-07-14 a las 12 03 45

**`public/app/plugins/datasource/loki/configuration/DerivedField.tsx`**
Add a Loki DS and the picker is part of the configuration

|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 08 25|Captura de pantalla 2023-07-14 a las 12 09 16

**`public/app/plugins/datasource/prometheus/configuration/ExemplarSetting.tsx`**
Add a Prometheus DS, add an exemplar and select "internal link"

|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 13 02|Captura de pantalla 2023-07-14 a las 12 14 40

**`public/app/plugins/datasource/tempo/configuration/LokiSearchSettings.tsx`**
Add a Tempo DS, open "Aditional settings" and DS piker is part of Loki search

|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 17 49|Captura de pantalla 2023-07-14 a las 12 17 39

**`public/app/plugins/datasource/tempo/configuration/ServiceGraphSettings.tsx`**
Add a Tempo DS, open "Aditional settings" and DS piker is part of Service graph

|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 21 44|Captura de pantalla 2023-07-14 a las 12 21 54

**`public/app/plugins/panel/alertlist/module.tsx`**
Add a panel to a dashboard using "Alert list" as panel type

|Before|After
|-|-|
Captura de pantalla 2023-07-14 a las 12 24 37|Captura de pantalla 2023-07-14 a las 12 24 01

**Why do we need this feature?**

To keep consistency and get value from the DS picker improvements.

**Which issue(s) does this PR fix?**:

Fixes #66916 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by gtk-grafana — DISMISSED** [review]
Can we address the keyboard accessibility of this component before merging this in everywhere? It looks like that [issue is in progress](https://github.com/grafana/grafana/issues/69109)?

**Review by ifrost — APPROVED** [review]
Explore/Correlations LGTM :tada:

**Comment by idastambuk** [comment]
Cloudwatch part looks good!

However, trying to navigate the dropdown with a keyboard, I find it a bit difficult to notice which selection I'm currently on: 
ezgif-5-272f668ae6


I feel like the contrast should be higher between the hovered and the not selected options?
This is probably not be the best place to bring this up, @ivanortegaalba LMK if there's a better one 🙏🏻

**Review by mckn — APPROVED** [review]
LGTM! Looks like the e2e-selector changes are compatible with e2e tests running outside of Grafana.

**Review by joey-grafana — COMMENTED** [review]
Tracing overall looks good. One observation though, we may want to add padding between the ds name and type `gdev-elasticsearch-metricbeat` is squashed but any ds with a sufficiently long name would probably look similar

Screenshot 2023-07-24 at 14 54 54

**Comment by ivanortegaalba** [comment]
> 

@idastambuk good catch! Here is a PR where we're trying to fix it. For now we found something hacky, but we will try to have something good for today.

I 100% agree with the contrast, we are working on it :)

**Comment by ivanortegaalba** [comment]
> Can we address the keyboard accessibility of this component before merging this in everywhere? It looks like that [issue is in progress](https://github.com/grafana/grafana/issues/69109)?

Good catch @gtk-grafana, we're working on it in this PR https://github.com/grafana/grafana/pull/72134. 
It will be backported, so it will be fixed. It is a little bit tricky since we need to hack the tab index, so it is taking some time. However, do you think this is a blocking issue? We cut today the 10.1 and I'd like to have it in this release. Then we have a week of bug bash where we can get the a11y issue merged and backported to 10.0 too.

**Comment by gtk-grafana** [comment]
@ivanortegaalba it's your call if we want to merge it at this point, I won't block the PR, but I personally think that any known accessibility issues should be addressed before merge. If this feature didn't work for users in Safari would we merge it in?

**Pull request merged**
