### PR TITLE
Moved Server Admin and children to separate menu item on Side Menu

### LINKED ISSUE #15591: Move out Server Admin to a separate menu item on SideMenu

### PR DESCRIPTION
**Pull request by hugohaggmark**
Closes #15591

### CODE REVIEW

**Review by marefr — APPROVED** [review]
Looks good :+1: 

Only weird thing is that the link to style guide is displayed in sidemenu. Tried to hide it from menu using `HideFromMenu` property, but that didn't work :)

**Comment by hugohaggmark** [comment]
@marefr thanks but I'm not sure what the link to style guide comment is about. Is that something we should be hiding, I feel that I don't have all the background information to make that decision myself?

**Comment by torkelo** [comment]
We could probably just remove it from nav for now it’s not like it’s adding much value as it is.

**Comment by hugohaggmark** [comment]
I removed style guide from navigation as suggested

**Comment by bergquist** [comment]
The icon is too dark in light theme
image

**Pull request merged**
