### PR TITLE
Docs: Adds a requirements page

### LINKED ISSUE #16487: Docs: Performance guide
Hardware requirements for Grafana have always been very low due to low resource consumption. With alerting and PhantomJS memory consumption it would be nice to have some information about this in relation to [installation instructions](https://grafana.com/docs/installation/).

Related to #8520 but we should only focus on giving some pointers here regarding spec.

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Adds a new requirements page to the installation docs. 
Wanted/needed some place to document known browser issues and thought that adding this missing page together with OS, hardware, database and browser requirements would be a good thing.

**Which issue(s) this PR fixes**:
Fixes #16487
Ref #18690

**Special notes for your reviewer**:
Hope that we could extend the requirements page eventually so please see this as a first step towards a great requirements page.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Great start! I think this doc is super good to have (and something we should expand on).

For example we should have a table I think for supported operating systems, and browsers: 
See: https://www.elastic.co/support/matrix

**Comment by DeeGeeGit** [comment]
Love the start here, a few comments.

It's fine that we have minimum specifications, but I'd really like us to suggest *recommended* specifications along with some form of sizing... X simultaneous users, Y dashboards auto refreshing every Z seconds, W alerts.

I *know* so much of this is YMMV, but if we could just add something that has a bit more meaning than just the minimum spec that'd be great.

As a first step if we could use some of the sizes we provision for a few of our larger hosted grafana cloud  instances, along with under what circumstances we increase those (adding plugins etc?).

Could we also share the spec we use for play.grafana.com given that has a lot of varying dashboards and varying usage?

**Comment by torkelo** [comment]
Anything left to do with this initial version?

**Comment by marefr** [comment]
I'm going to merge it as is and create a new issue to improve it.

**Comment by marefr** [comment]
@DeeGeeGit added #19101 for improving the requirements page. Please comment in issue if there's more you would like to see in the page.

**Pull request merged**
