### PR TITLE
Docs: Add cloud docs

### PR DESCRIPTION
**Pull request by oddlittlebird**
By request of @sfingerhut and @Dieterbe , added the Grafana Cloud docs to the Grafana documentation.

These documents have received minimal editing, so they are not up to the quality standards of our newer docs, but I checked links and they will at least be findable.

### CODE REVIEW

**Comment by marefr** [comment]
Shouldn't these be added to website repo?

**Comment by oddlittlebird** [comment]
Not if they are part of the Grafana documentation.

**Comment by DanCech** [comment]
The Grafana Cloud docs source is in the website repo, we shouldn't copy them here.

Please make the same edits to the Grafana Cloud content in the website repo.

We can then add links in this repo to https://grafana.com/docs/grafana-cloud/ and/or add a nice page to live at https://grafana.com/docs/ that can link to https://grafana.com/docs/grafana-cloud/ and https://grafana.com/docs/grafana/latest/

**Comment by Dieterbe** [comment]
> By request of @sfingerhut and @Dieterbe , added the Grafana Cloud docs to the Grafana documentation.

FWIW, I never asked for this. I don't have an opinion on where the source of the docs should live. So, whatever works best for the website team. What Dan said is fine for me.  I care much more about having the docs actually be available.

**Pull request closed without merging**
