### PR TITLE
feat(explore): let plugins define the height of the panels when rende…

### PR DESCRIPTION
**Pull request by Umaaz**
…red in explore

**What is this feature?**

I would like to be able to change the size of a panel in the explore page. Following on from my previous change I would like to be able to change the height of the plugin panel on the explore page.

**Why do we need this feature?**

The default size of 400px is not enough for my new panel.

**Who is this feature for?**

Datasource plugin developers that want to provide a good user experience on Explore.

As an example usage:
```go
	frame := &data.Frame{
		Name: "Snapshot",
		Fields: []*data.Field{
                   ...
		},
		Meta: &data.FrameMeta{
			PreferredVisualization:            "table",
			PreferredVisualizationPluginID:    "intergral-deep-panel",
			PreferredVisualizationPanelHeight: 600,
		},
	}
```

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Umaaz** [comment]
Looking at this again - if we remove the height completely then the panel will just scale to fit the plugin panel.

**Comment by ifrost** [comment]
Thanks, @Umaaz for the PR and sorry for late response.

Removing `height` from PanelChrome won't work, unfortunately :( PanelChrome requires specifying both width/height or none (for autosizing). You should see the error when you build Grafana:

```
    Property 'height' is missing in type '{ children: (innerWidth: number, innerHeight: number) => Element; title: string; width: number; loadingState: LoadingState; }' but required in type 'FixedDimensions'.

56       <PanelChrome title={plugin.name} width={width} loadingState={state}>
          ~~~~~~~~~~~

  packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx:62:3
    62   height: number;
         ~~~~~~
    'height' is declared here.


Found 1 error in public/app/features/explore/CustomContainer.tsx:56
```

What is more this solution may work for your plugin which controls it's height, but may not work for other plugins. In most cases plugins do not control their size but fill in the space provided by the container. You can check it by running on your branch the following raw frames with the test data source:

<details><summary>Raw frames</summary>

```json
[
  {
    "meta": {
      "preferredVisualisationPluginId": "stat"
    },
    "fields": [
      {
        "name": "value",
        "values": [1]
      }
    ]
  }
]
```

Use Test data source / Raw Frames scenario:

Screenshot 2024-03-13 at 11 18 07


</details>



| main | PR branch |
|------|-----------|
|  Screenshot 2024-03-13 at 11 14 59 | Screenshot 2024-03-13 at 11 16 38 |


Going back to your first idea of passing `PreferredVisualizationPanelHeight` in data frames meta. The height of the visualization is quite specific to the panel implementation. **Data source** plugins would need to know that when data frames are created but the only way would be to hardcode it. Imagine the implementation of the panel plugin changes and different height is now required. In such case, a change in the data source plugin would also be needed.  

It would be great if we could find a better place to store the preferred height of the visualization. Maybe we could add "preferred minimum height" to [PanelPluginMeta](https://github.com/grafana/grafana/blob/6ee2bd4d29413882164db55833034985ad30b4e6/packages/grafana-data/src/types/panel.ts#L23)? In Explore we could use that information to adjust the size of the container. Dashboards could also use that information to show a warning of a panel that is too small for the panel. @grafana/plugins-platform-frontend wdyt?

**Comment by Umaaz** [comment]
@ifrost thanks for the response.

I agree with you about `PreferredVisualizationPanelHeight` always seemed wrong, just did not know where else such a config could go. I will take a look at using `PanelPluginMeta` as you suggest. It seems to make more sense to me.

**Comment by gelicia** [comment]
Hello @Umaaz this PR is getting stale and I think we've all agreed another solution is needed here. I'm going to close this PR, please open a new one with any different changes you'd like to make to solve this problem.

**Comment by ifrost** [comment]
@Umaaz - just for the context - could also share a screenshot of the panel in 400px and 600px?

**Pull request closed without merging**
