### PR TITLE
NewsPanel: Prevent date and title collapsing to single row

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- manual backport of https://github.com/grafana/grafana/pull/40016

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/41256

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
@ashharrison90 why a manual backport? could not see that grot failed to backport https://github.com/grafana/grafana/pull/40016

**Comment by ashharrison90** [comment]
@torkelo oh i didn't realise it would do it after it had already been merged. does that mean i can just add the backport label to the old PR and it'll generate a new one?

**Comment by torkelo** [comment]
@ashharrison90 yes

**Comment by torkelo** [comment]
@ashharrison90 but it looks like it failed, strange, has there been any other changes to NewsPanel in 8.3?

**Comment by ashharrison90** [comment]
@torkelo not that i'm aware. 🤷  i'll run the manual backport process and see what the conflict is

**Comment by torkelo** [comment]
@ashharrison90 ah it failed due to  the news panel PR changing the strict errors file

**Comment by ashharrison90** [comment]
@torkelo ahhhhhhh ok, then i'll reopen this i guess? serves me right for sneaking in things to PRs that don't involve them 😬

**Review by axelavargas — APPROVED** [review]
Good job @ashharrison90 👏🏾

**Pull request merged**
