### PR TITLE
Search: Replace search implementation

### PR DESCRIPTION
**Pull request by sakjur**
**What this PR does / why we need it**:

1. Sets the new search engine implementation as default search.
2. The new search engine supports being extended and manipulated externally in a way that isn't done for the old search engine, including introducing custom sorting options.

### CODE REVIEW

**Comment by marefr** [comment]
Have there been any performance tests when having thousands of folders/dashboards? Mostly the additional order by columns I'm concerned of.

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by sakjur** [comment]
I just checked, we're missing an index for `dashboard.title`. I'll add that.

We haven't done performance tests with thousands of dashboards. The sole difference in the query itself is what you mention, we've removed the `order by id` step and moved the `order by title` to the inner query (which previously meant that if you had more than a thousand results the results would be somewhat wrong).

I'll run some tests and get back.

**Comment by sakjur** [comment]
I'm benchmarking (for SQLite, will try MySQL as well) and with 100 000 dashboards I get 100 searches/s with and index and ~50 without it. I'm also looking at using a functional index since we want the sorting to be case-insensitive. That operation slows down the query quite a bit both with an index and without one (80/30), but it gives a more correct result so I'd say that's worth it.

**Comment by sakjur** [comment]
The benchmark, in case you're curious:

```
func BenchmarkBuilder(b *testing.B) {
	user := &models.SignedInUser{
		UserId:  1,
		OrgId:   1,
		OrgRole: models.ROLE_VIEWER,
	}

	db := setupTestEnvironment(b)
	err := createDashboards(0, 100000, user.OrgId)
	require.NoError(b, err)

	builder := &searchstore.Builder{
		Filters: []interface{}{
			searchstore.TitleSorter{},
		},
		Dialect: dialect,
	}

	res := []sqlstore.DashboardSearchProjection{}
	err = db.WithDbSession(context.Background(), func(sess *sqlstore.DBSession) error {
		b.ResetTimer()
		var err error
		for i := 0; i < b.N; i++ {
			sql, params := builder.ToSql(1000, 1)
			err = sess.SQL(sql, params...).Find(&res)
		}
		return err
	})
	require.NoError(b, err)
}
```

**Comment by sakjur** [comment]
😞 Oh. MySQL/MariaDB doesn't support functional indices in the way SQLite and Postgres does. Well. That complicates things a bit.

**Comment by torkelo** [comment]
I recommend `npx grafana-toolkit searchTestData`

https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/cli/tasks/searchTestDataSetup.ts

It creates a team with and user who is in the team, and then it creates N amount of dashboards in that folder, and each dashboard has an ACL permission for that team. 

So if have 3000 thousands dashboards it means 3000 ACL items as well :)

**Comment by sakjur** [comment]
@torkelo Tested with that as well Friday (but more manually since I don't think I can include that in my benchmark code, but it's a good complement).

However tried to add more dashboards today (I have ~4500, and would like at least ten times more or so to really stress my computer) but got 404 for the npm registry, have we removed the package since then or is npm just unstable?

```
npx grafana-toolkit searchTestData --count 50000
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/grafana-toolkit - Not found
npm ERR! 404
npm ERR! 404  'grafana-toolkit@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by torkelo** [comment]
strange, are you executing that in repo root? Try removing node_modules and re-install with `yarn install --pure-lock-file`

**Comment by sakjur** [comment]
Ah! No, that explains it, I'm in my homedir

**Comment by sakjur** [comment]
(I was in the repo root dir before, but had to open a new terminal and didn't know it was bound to the repo) 😅 Thanks for the pointer!

**Comment by sakjur** [comment]
Checked manually with 50 000 dashboards created with `grafana-toolkit`, and the performance is definitely okay even with that amount of dashboards. Compared to master it's ~ the same when comparing a few searches.

Attaching some reference images.

New:
Screen Shot 2020-04-27 at 12 31 26

Old:
Screen Shot 2020-04-27 at 12 56 31

**Review by xlson — APPROVED** [review]

**Pull request merged**
