### PR TITLE
Flame Graph: Fix for dashboard scrolling

### LINKED ISSUE #56477: Flamegraph: Fix scrolling in dashboard panel
Right now in the dashboard the scrolling is broken both for table and flamegraph view as table even if it has scroll has a height much bigger than the panel viewport and the same goes for flamegraph but there is no scroll for it at all.

https://user-images.githubusercontent.com/1014802/194339243-bf06ac63-4e63-4539-afbc-b82262535d14.mp4

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:

This PR ensures that when the flame graph panel is used in a dashboard that it can be vertically scrolled if it is too tall to fit in the given vertical space. Also adds sticky header.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/56477

**Special notes for your reviewer**:

Explore

- Top table scrolls. Flame graph does not scroll. Height of container set to flame graph height.
- Container scroll exists.
- Header will stick to top.

Non-explore

- Top table and flame graph scroll separately.
- No container scroll.
- Header will not stick to top (having two separate scrolls for the top table and flame graph offers better usability - rather than outer (container) and inner scrolls, where the sticky would be applied based on the outer scroll).

Potential improvements

- Place a shadow below the sticky header when it is _stuck_ to the top

### CODE REVIEW

**Comment by aocenas** [comment]
This is better than before but I wonder if we can make the scrolling more reasonable.

https://user-images.githubusercontent.com/1014802/195360956-6aea3961-9d27-479d-8e97-0143ac2f1076.mp4

- The header would be great if it was fixed in some way so it does not scroll away.
- If I show just the table it would be nice to have just a single scroll bar for the table instead of 2

Would it be possible to make the table and flame graf separate scroll areas and the whole visualization to just take the size of the container? Possible only in Dashboard and keep it the same in Explore.

We can possibly merge this one so that we have it fixed in dashboards in this shape and keep the improvements for later PR. No idea how complex those are.

**Comment by aocenas** [comment]
Looks great. You mention `Height of container set to flame graph height.` does not seem to work that way for me right now:

Screenshot from 2022-10-20 14-46-32

Screenshot from 2022-10-20 14-43-30

Testing with the test datasource and flamegraph scenario and there seems to be a lot of white space on the bottom of the flamegraph. Checked if it's a case of items not being visible due to some threshold but seems like the data is really only 50levels deep and the space is much larger.

In any case, to me this does not prevent merging. This already works great even with the bigger white space.

**Comment by joey-grafana** [comment]
Thanks for brining it up. 

Agreed. That's a potential improvement I added to the description yesterday but removed again to keep the PR a bit more specific.

**Comment by joey-grafana** [comment]
@aocenas haha looks like you didn't accept the pr :D Same thing has happened to me a few times!

**Review by aocenas — APPROVED** [review]

**Pull request merged**
