### PR TITLE
Canvas: Update metric value text for no data

### LINKED ISSUE #63760: Canvas: Metric value displays select value when datasource is broken
If there is no data return from the data source the metric element shows  "double click fields to set field". The fields are already set, but no data is returned due to data source error. It would be nice if the data was shown as NA or you could select a message/value via value mapping when no data is returned and the field is mapped.

From [canvas community discussion](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-5048647)

220043165-cd53343e-7069-4e04-b848-4ba9da67e5b8

### PR DESCRIPTION
**Pull request by adela-almasan**
https://user-images.githubusercontent.com/88068998/227975912-2cfe97be-2144-4e53-b57a-131906df16e8.mov

Fixes #63760 

**Special notes for your reviewer:**
Not sure how to reproduce broken datasource..

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

**Review by nmarrs — COMMENTED** [review]
Hm it seems that when a data source is broken that the data object is still returned with an empty string for text. This means that even after clearing the non existent field in the data, we still display "NA" vs "Double click to set field" -> it seems there are no cases where we display the latter now given this behavior

We probably want to consider if a field is set or not for determining whether or not to show "NA" vs the double click message. A future improvement could be displaying an error ! with hover displaying field is not found, but for now NA or maybe even "Field not found" is good enough
Screenshot 2023-03-27 at 8 44 41 AM

**Comment by adela-almasan** [comment]
> 

Yes, also noticed that - a bit odd, but wasn't sure exactly how it was supposed to work. Pushed an update.

**Review by nmarrs — APPROVED** [review]
LGTM 🔥

**Comment by UdoRat** [comment]
The solution is failing when I use InfluxDB as data source.
See https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-5754578

**Pull request merged**
