### PR TITLE
Update Singlestat Docs

### PR DESCRIPTION
**Pull request by mattttt**
Need some additional clarification in Spark Line and Value to text before this is merged.

### CODE REVIEW

**Comment by mattttt** [comment]
Need
singlestat-basesettings
singlestat-coloring
singlestat-sparklines
singlestat-valuemapping



 to add these images:

**Comment by torkelo** [comment]
Nice!

**Comment by torkelo** [comment]
images/RYG.png and images/GYR.png missing

**Comment by mattttt** [comment]
Argh, sent you those images on slack while I figure out what's going on with my branch

**Pull request merged**
