### PR TITLE
Feature to restrict suggested metrics/tag entries based on existing metr...

### PR DESCRIPTION
**Pull request by kylemallory**
This feature uses the OpenTSDB search/lookup API to return a list of metrics and associated tags that match any currently specified metric & tags within the series interface.  This restricts returned suggestions to only those values which match the current metric, etc.  If no metric or other tags are specified, or if the search/lookup API returns an error, the return is the same as was previously defined (the results of the /suggest api).

### CODE REVIEW

**Comment by tulva** [comment]
@kylemallory I think you need to open a feature branch with just the commits for this PR as your alias commits are showing up here too. Keen to see this feature merged myself.

**Comment by jtakkala** [comment]
@kylemallory I think you need to open a feature branch with just the commits for this PR as your alias commits are showing up here too. Keen to see this feature too.

**Comment by kylemallory** [comment]
My apologies, all.  Thanks Jari for the heads up.  I've since tracked 
down a Git expert who has corrected my bad behavior.... Hopefully.  I've 
retracted the old pull request and submitted a new, proper pull from a 
new feature branch.   I'm still learning this whole git/github thing, so 
feel free to continue to steer me in the right direction, should I 
continue to drift.

--Kyle

**Comment by kylemallory** [comment]
Submitted pull-request for this feature. "Restricted suggestions" #1433

**Pull request closed without merging**
