### PR TITLE
Escape backslashes in regexps in Loki label browser (#45809, #47039).

### LINKED ISSUE #45809: Loki: If label value includes backslash it is not escaped and query is invalid
**What happened**:
In log browser, we are not escaping backslash, but it seems like we do it for Prometheus. We should probably do the same here and also look at autocomplete.

**What you expected to happen**:

When I choose value from autocomplete or label browser, backslash it should be correctly escaped.

**How to reproduce it (as minimally and precisely as possible)**:
1. You have to have logs with label values that include backslash
2. Open log browser and pick label + value with backslash
3. backslash should be escaped and query should produce result without error

### PR DESCRIPTION
**Pull request by glintik**
**Which issue(s) this PR fixes**:

Fixes #45809, #47039.

**Special notes for your reviewer**:

@ivanahuckova please take a look.

### CODE REVIEW

**Comment by glintik** [comment]
This PR is based on @ivanahuckova commit 5e77e76e0ff25391500d7f43f6d817ec0457be60, I slightly modfied it and tested. Now label query field should correctly handle values from filters and label suggester.

**Review by ivanahuckova — COMMENTED** [review]
@glintik I am sorry that it took that long to review this PR. It looks great! However, there has been some bigger changes on main branch (import ordering) and therefore it created merge conflicts. Could you please try to solve them or create same PR from current main once again.

Thank you!

**Comment by glintik** [comment]
Hi @ivanahuckova,

I rebased PR to fresh main branch and it works well. But I found that new feature "Builder" was added recently and as I can see, it doesn't work properly with Loki escaping:
Screenshot 2022-05-02 at 23 26 07

As you can see, "select" component doesn't escapes properly backslashes. Any thoughts or instructions where to add escaping?

**Comment by ivanahuckova** [comment]
> ll. But I found that new feature "Builder" was added recently and as I can see, it doesn't work properly with Loki escaping:

Nice catch! I am thinking about this place where we can map trough value and based on selected operator, we can add escaping:
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilder.tsx#L26

What do you think?

**Comment by glintik** [comment]
@ivanahuckova thank you for guiding, I added values escaping in onGetLabelValues(). Looks good, but more testing will be appreciated.

**Comment by ivanahuckova** [comment]
I like the refactor that you included! 🤩 

I have tested your fix for query builder, but I think escaping should be directly here: 
image

The reason is that if we would like to have escaping in `onGetLabelValues`, we would have to escape both cases - when we have previous label-value pair and when we don't. You fix only includes the case when we have previous label-value pair. So we would need to add escaping to the line 55 as well So also this on line 55: `return await datasource.languageProvider.fetchLabelValues(forLabel.label);`. 

Moreover, this would produce incorrect escaping, if you select value and decide to change operator. 

What do you think?

**Comment by glintik** [comment]
@ivanahuckova,

> I have tested your fix for query builder, but I think escaping should be only directly here:
onChange() is not suitable for escaping because it called every time you add/remove variables, so values will be escaped every time more and more.

> So we would need to add escaping to the line 55 as well So also this on line 55
Thank you for pointing this, I added a fix.

> Moreover, this would produce incorrect escaping, if you select value and decide to change operator.
You are right, but this is the same behavior as in Prometheus code builder, so I considered it as well-established. You want to change this?

**Comment by ivanahuckova** [comment]
> onChange() is not suitable for escaping because it called every time you add/remove variables, so values will be escaped every time more and more.

Hmmm good point, I didn't realize that. Your solution then makes more sense. 

LGTM.

**Review by ivanahuckova — APPROVED** [review]
LGTM

**Pull request merged**
