### PR TITLE
Docs: correct tracesToLogsV2 example span time shifts

### PR DESCRIPTION
**Pull request by jvaelen**
According to the [documentation](https://grafana.com/docs/grafana/next/datasources/tempo/configure-tempo-data-source/#configure-trace-to-logs), `spanStartTimeShift` shifts the start time for the logs query based on the span's start time, and a negative value extends the time to the past. Conversely, `spanEndTimeShift` shifts the end time for the logs query based on the span's end time.

This means the example had the values the wrong way around.

To fix this, the values have been corrected to -1h for `spanStartTimeShift` and 1h for `spanEndTimeShift`, which will extend the logs query time range to 1 hour before the span's start time and up to 1 hour after the span's end time

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by jdbaldry** [comment]
Looping in @knylander-grafana who may be the best served to validate this change (or confirm with the Tempo team)

**Comment by jvaelen** [comment]
@jdbaldry is there anything I could do to help this along? The documentation seems a bit misleading here.

**Comment by jdbaldry** [comment]
I'm sorry that this got dropped. I believe this is a correct change so I'll get this merged :)

**Comment by jdbaldry** [comment]
Thank you for the contribution and for chasing it up too! :)

**Review by jdbaldry — APPROVED** [review]

**Pull request merged**
