### PR TITLE
Editor: Ignore closing brace when it was added by editor

### LINKED ISSUE #14553: Explore: Prometheus range completion too eager
User feedback suggests that they tend to type `[1m]`, but the brackets get automatically closed so the result is `[1m]]`. 

Perhaps dont close them, or, better, when typed, override the existing closed one.

### LINKED ISSUE #18787: Explore/QueryField: Manually entering the closing bracket of an auto-completed pair should move caret forward
**What would you like to be added**:
Currently entering a closing bracket after a pair of brackets have been auto-completed inserts a new closing bracket rather than moving the caret forward, contrary to the behavior of most modern text editors. Having the caret move forward would help towards having a less frustrating user experience.

**Why is this needed**:
Less frustrating user experience.

### LINKED ISSUE #21161: Explore: parenthesis added by auto completion conflict while typing a straight query
**What happened**:

In the Explore, while typing a straight Prometheus query, auto completion triggers to add closing parenthesis. These added parenthesis conflict with the user just typing a straight query and force the user to use keyboard arrows while typing to move the cursor after the added parenthesis before continuing writing the query.

For example, if I just try to type a valid query `sum(up) by(cluster)` the query will end up be `sum(up) by(cluster)))` (two additional closing parenthesis at the end):

**What you expected to happen**:

When typing a closing parenthesis, it should advance the cursor instead of inserting the parenthesis if the parenthesis was added by autocompletion.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Explore and select a Prometheus data source
2. Go straight typing `sum(up) by(cluster`
3. The resulting query is invalid

**Environment**:
- Grafana version: `v6.6.0-pre (e9079c3faa)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: OSX 10.13.6 & Chrome 79.0.3945.79
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by davkal**
- brace completion gets annoying if the user still types closing brace
- this change marks automatically added closing braces and when the user
types a closing brace at that position, it will be overridden instead of
added

Fixes #21161
Fixes #14553
Fixes #18787

### CODE REVIEW

**Comment by aocenas** [comment]
Right now this is skipping all parenthesis:

Kapture 2019-12-18 at 15 26 54

Not sure if it is understandable from the video but basically it skips adding parenthesis even though I added them and they weren't added by the plugin. tbh not sure if that is worse or better but does not seem to be the intention in the PR.

**Comment by davkal** [comment]
@aocenas could you give steps for repro?

**Comment by aocenas** [comment]
@davkal 

Basically I just inserted bunch of right parenthesis myself (`)`) then put the cursor in front of the (`(|)))))`) and try to insert another `)` there. It will be skipped until you come to the end of the input and then it will start adding them again.

Also while skipping it seems to first select the parenthesis not just move the cursor:
Screenshot 2019-12-18 at 16 11 09

**Comment by pracucci** [comment]
Thanks @davkal for working on it. I did few manual tests and looks pretty solid to me. It's true that it skips any closing parenthesis (as mentioned by @aocenas), but looks significantly better than the behaviour in `master` to me.

**Comment by davkal** [comment]
Should be fixed now. PTAL

**Comment by pracucci** [comment]
Thanks @davkal! Looks way better after this PR.

**Pull request merged**
