### PR TITLE
Search: Sync state on read for HA consistency

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

This is a bit esoteric idea (maybe can be optional?), but it seems to work fine 🤔 

This PR synchronises index state on every read request – so results are always actual, even in HA setup case.

Requires a bit more careful testing/evaluation if we decide it worth going with it.

### CODE REVIEW

**Comment by ryantxu** [comment]
I think this is a great approach!  the only downside would be if there are a LOT of updates to process, but that should be rare.

I like this this means we do not have to get too hand wavy around HA 😬

**Comment by ArturWierzbicki** [comment]
Neat! 🧹🧹 solves a big problem + the performance impact is minimal in majority of cases and we could make up for it with caching user/perms in the initial phase of the request

**Comment by FZambia** [comment]
At the moment of re-indexing the goroutine that manages indexes and applies updates can be blocked for a reasonably large time – I think this can be improved though (re-index asynchronously).

**Comment by ArturWierzbicki** [comment]
@bergquist 
> Worst case would be that we have to keep the old search enabled for them until we fixed it. Is there any way we could detect instances processing lots of events each time? Logs should be fine :)

We can track it per HG slug using metric queries based on the logs: https://ops.grafana.net/d/oeFR_Tlnz/searchv2-backend-monitoring?orgId=1 :)

**Review by ryantxu — APPROVED** [review]
9.1 FTW

**Review by ryantxu — APPROVED** [review]
approved again :)

**Pull request merged**
