### PR TITLE
Nav: Grafana Incident's sidebar navigation should be plural

### PR DESCRIPTION
**Pull request by clord**
It makes sense for users to see the sidebar and breadcrumb as plural,
and not the partial product name, singular. See referenced issue below
for more discussion and screenshots.

**What is this feature?**

Renames a menu option to plural

**Why do we need this feature?**

Users expect the sidebar to be plural, since the specific page is a listing of incidents.

**Who is this feature for?**

Users of Grafana Incident

**Which issue(s) does this PR fix?**:

- Fixes https://github.com/grafana/irm/issues/3145
- Also see https://github.com/grafana/incident/pull/2893

**Special notes for your reviewer**:

I'll update tests shortly.

### CODE REVIEW

**Review by matryer — APPROVED** [review]
This feels more appropriate to me.

**Review by matryer — APPROVED** [review]
Thank you

**Comment by clord** [comment]
@sakjur fyi

**Review by sakjur — APPROVED** [review]
:+1: Do you have merge permissions or do you need help merging?

**Comment by clord** [comment]
I do not have merge permissions. 
Screenshot 2023-06-05 at 9 11 54 AM

**Comment by clord** [comment]
@sakjur ☝️ could you merge please?

**Pull request merged**
