### PR TITLE
Navigation: Adjust megamenu to work with topnav

### LINKED ISSUE #55100: Navigation: Adjust Megamenu to work with topnav
TODO:
- [ ] Make section headers clickable (e.g. `Dashboards` goes to the `/dashboards` page)
- [ ] Make hover/active states consistent with `SectionNav`
- [x] Investigate removing storing state of expanded items

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- adds `Browse` back under the `Dashboards` section
- adds an active state for children (previously only the top level item could have an active state)
- megamenu now doesn't remember active state anymore. everything is collapsed by default unless it contains an active page.
- ensures megamenu overlays explore drawer consistently

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/55100

**Special notes for your reviewer**:

### CODE REVIEW

**Review by eledobleefe — COMMENTED** [review]
I've run it and checked the behaviour. It worked fine except for this:

Navigation55440

As you can see in the snapshot if the screen is less than 768px wide the `hamburger icon` is duplicated.

**Comment by ashharrison90** [comment]
@eledobleefe yeah haven't really handle the mobile behaviour yet 😄 agreed that needs changing

**Review by lpskdl — COMMENTED** [review]
Fantastic work on Megamenu 🚀 @ashharrison90 .

Tested it on both topnav states and with screen reader.

I do have a question though, the hover state between megamenu and secondary menu is different. Is it covered by this change or we are not going to change it the same way it hovers the megamenu?

https://user-images.githubusercontent.com/108552997/191281565-7d727638-ce8b-47b6-b8c4-caaae90225f9.mov

**Comment by torkelo** [comment]
A big improvement from what is in main! Although I would I prefer a real links first approach :)  

**Browse** 

And adding browse to the breadcrumbs does make going from dashboards to folder page or root browse a bit awkward (The breadcrumbs add a Browse, but opening a dashboard removes Browse from breadcrumb).

I think we can solve that by specifying Browse as "HideFromBreadcrumbs" , and make it the section home (So Dashboards section should point to same url as Browse). That feels pretty good when I test it.

Code
```diff
diff --git a/pkg/api/dtos/index.go b/pkg/api/dtos/index.go
index 9ae6797231..28a7d4c073 100644
--- a/pkg/api/dtos/index.go
+++ b/pkg/api/dtos/index.go
@@ -58,25 +58,26 @@ const (
 )
 
 type NavLink struct {
-	Id               string     `json:"id,omitempty"`
-	Text             string     `json:"text"`
-	Description      string     `json:"description,omitempty"`
-	Section          string     `json:"section,omitempty"`
-	SubTitle         string     `json:"subTitle,omitempty"`
-	Icon             string     `json:"icon,omitempty"` // Available icons can be browsed in Storybook: https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-icon--icons-overview
-	Img              string     `json:"img,omitempty"`
-	Url              string     `json:"url,omitempty"`
-	Target           string     `json:"target,omitempty"`
-	SortWeight       int64      `json:"sortWeight,omitempty"`
-	Divider          bool       `json:"divider,omitempty"`
-	HideFromMenu     bool       `json:"hideFromMenu,omitempty"`
-	HideFromTabs     bool       `json:"hideFromTabs,omitempty"`
-	ShowIconInNavbar bool       `json:"showIconInNavbar,omitempty"`
-	RoundIcon        bool       `json:"roundIcon,omitempty"`
-	Children         []*NavLink `json:"children,omitempty"`
-	HighlightText    string     `json:"highlightText,omitempty"`
-	HighlightID      string     `json:"highlightId,omitempty"`
-	EmptyMessageId   string     `json:"emptyMessageId,omitempty"`
+	Id                  string     `json:"id,omitempty"`
+	Text                string     `json:"text"`
+	Description         string     `json:"description,omitempty"`
+	Section             string     `json:"section,omitempty"`
+	SubTitle            string     `json:"subTitle,omitempty"`
+	Icon                string     `json:"icon,omitempty"` // Available icons can be browsed in Storybook: https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-icon--icons-overview
+	Img                 string     `json:"img,omitempty"`
+	Url                 string     `json:"url,omitempty"`
+	Target              string     `json:"target,omitempty"`
+	SortWeight          int64      `json:"sortWeight,omitempty"`
+	Divider             bool       `json:"divider,omitempty"`
+	HideFromMenu        bool       `json:"hideFromMenu,omitempty"`
+	HideFromTabs        bool       `json:"hideFromTabs,omitempty"`
+	HideFromBreadcrumbs bool       `json:"hideFromBreadcrumbs,omitempty"`
+	ShowIconInNavbar    bool       `json:"showIconInNavbar,omitempty"`
+	RoundIcon           bool       `json:"roundIcon,omitempty"`
+	Children            []*NavLink `json:"children,omitempty"`
+	HighlightText       string     `json:"highlightText,omitempty"`
+	HighlightID         string     `json:"highlightId,omitempty"`
+	EmptyMessageId      string     `json:"emptyMessageId,omitempty"`
 }
 
 // NavIDCfg is the id for org configuration navigation node
diff --git a/pkg/api/index.go b/pkg/api/index.go
index fce0af4cfc..6e9fdbd372 100644
--- a/pkg/api/index.go
+++ b/pkg/api/index.go
@@ -196,7 +196,7 @@ func (hs *HTTPServer) getNavTree(c *models.ReqContext, hasEditPerm bool, prefs *
 
 		dashboardChildLinks := hs.buildDashboardNavLinks(c, hasEditPerm)
 
-		dashboardsUrl := "/dashboards"
+		dashboardsUrl := "/dashboards/browse"
 
 		dashboardLink := &dtos.NavLink{
 			Text:       "Dashboards",
@@ -513,10 +513,11 @@ func (hs *HTTPServer) buildDashboardNavLinks(c *models.ReqContext, hasEditPerm b
 
 	dashboardChildNavs := []*dtos.NavLink{}
 	browseNavLink := &dtos.NavLink{
-		Text: "Browse",
-		Id:   "dashboards/browse",
-		Url:  hs.Cfg.AppSubURL + "/dashboards",
-		Icon: "sitemap",
+		Text:                "Browse",
+		Id:                  "dashboards/browse",
+		Url:                 hs.Cfg.AppSubURL + "/dashboards",
+		HideFromBreadcrumbs: true,
+		Icon:                "sitemap",
 	}
 
 	if hs.Features.IsEnabled(featuremgmt.FlagTopnav) {
```

**Comment by ashharrison90** [comment]
@torkelo have pushed that change + also hid it from the SectionNav. clicking `Browse` in the megamenu now lands you on a page that looks like this:
image

**Comment by torkelo** [comment]
@ashharrison90 I don't like hiding the Browse in the section nav that feels very confusing to have it in the mega menu but not there. I really like that child page is the section default (active) rather than the section itself, feels more natural

**Comment by ashharrison90** [comment]
ok np i can revert that 😅 the one thing i'm trying to fix is the section header being some weird thing. right now it's either:
- a landing page that can't be accessed from the breadcrumbs
- a link that can't be clicked because it's the same link as the `Browse` page

**Comment by ashharrison90** [comment]
@torkelo kk reverted it, only weird thing is the section header link on the `Browse` page now pointing to the same link

**Review by torkelo — COMMENTED** [review]
@ashharrison90 I think it's ok, 

But we could in SectionNav detect if the first child's url is the same as the section url and make the main section a span instead anchor

**Comment by ashharrison90** [comment]
closing in favour of https://github.com/grafana/grafana/pull/55538

**Pull request closed without merging**
