### PR TITLE
Chore: remove strict errors for azure-monitor

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Remove errors related to Azure Monitor from #40460.

**Which issue(s) this PR fixes**:

Reference #40460

**Special notes for your reviewer**:

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
Awesome stuff on getting these strict errors down 😌

**Review by joshhunt — APPROVED** [review]

**Comment by joshhunt** [comment]
Might be worth getting someone from @grafana/plugins-platform to give this a once over to triple check it, as it's in the core plugin API.

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
lgtm, but don't forget to update the number of strict errors in `ci-check-strict`

**Review by ashharrison90 — APPROVED** [review]
**awesome**

**Pull request merged**
