### PR TITLE
Logo takes you Home instead of toggling side menu #15482

### LINKED ISSUE #15482: Remove toggle sidemenu feature and make logo goto home
A lot of people find the use of the Grafana logo as a way to toggle sidemenu unintuitive thinking it will go to the home view / landing page instead (ie home dashboard). 

The reasoning for the current state is mostly that in v2-v4 the icon doubled as a menu (turned into a menu icon after hover) and had a caret down. After introducing the small sidemenu I was afraid to force this be a persistent thing and wanted to keep the sidemenu less view that Grafana had before which is why the sidemenu toggle logic was still kept. 

But do not think we need the sidemenu toggle logic, we have the TV mode button for users that want to remove it while in dashboard. 

* Remove sidemenu open/closed state logic & handling
* Make Grafana logo go to home route.

### PR DESCRIPTION
**Pull request by jschill**
It's still possible to toggle side menu by going to tv-/kiosk-mode.

Fixes #15482

### CODE REVIEW

**Review by peterholmberg — APPROVED** [review]
Yay!

**Comment by torkelo** [comment]
would like to clean up all sidemenu toggle & open state classes as well. Only thing we still need is the collapsed mobile view. For kiosk & tv mode the full sidemenu can be hidden using the existing classes. 

The css and the logic in GrafanaCtrl that deals with sidemenuOpen state can all be removed (except the mobile dropdown menu state)

**Review by torkelo — CHANGES_REQUESTED** [review]
See comment above.

**Comment by jschill** [comment]
> would like to clean up all sidemenu toggle & open state classes as well. Only thing we still need is the collapsed mobile view. For kiosk & tv mode the full sidemenu can be hidden using the existing viewstate classes.
> 
> The css and the logic in GrafanaCtrl that deals with sidemenuOpen state can all be removed (except the mobile dropdown menu state)

Don't we need to keep that logic since we are disabling the menu on some pages:
https://github.com/grafana/grafana/blob/56682cb1eb8f961f5e637c09668aeb226f35623d/public/app/core/controllers/login_ctrl.ts#L18

Or do you mean we should show the menu on those pages as well? (login, reset password, sign up, select org, invited)

**Comment by torkelo** [comment]
we have a class for pages where it should be hidden (sidemenu-hidden) that can be set in routes.ts so do not think that is needed. Just need to make sure it's set in the routes file.

**Review by torkelo — APPROVED** [review]
Looks great now, nice to be rid of all that sidemenu open state handling :)

**Pull request merged**
