### PR TITLE
Allow datasource provisioning to specify multiple orgIds per definition

### LINKED ISSUE #12717: Same datasource provisioning for different organisations is hard to achieve
Since Grafana 5.0 provisioning datasources is much easier thanks to the new functionalities.

However, in our environment we are in the need of managing several organisations (40+) and provide a set of base datasources (~15) for all of them and keep them up to date.

In the current scenario we would need to write a datasource definition per organisation, so 15*40 datasources definitions, of course this could be scripted, but though it would make more sense to add the functionality directly in the Grafana provisioning tools.

In terms of making the change I already started a PR:
https://github.com/grafana/grafana/pull/12713

Would this be this something interesting for someone else?

### PR DESCRIPTION
**Pull request by kazeborja**
Fixes #12717

Datasource provisioning with multiple organisations can be a bit repetitive in the current scenario.
This is a small change that allows datasource provisioning to specify a new field "orgIds", allowing it to provide a list of organisations to add the datasource into.

An example of the yaml fille will look like:

```
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    OrgIds: [1,2]
```

And also allows to delete from multiple organisations:

```
deleteDatasources:
  - name: Graphite
    orgIds: [1,2]
```

It respects all the previous functionality, so this is just an optional usage of the provisioning API.

### CODE REVIEW

**Comment by marefr** [comment]
Unsure of this feature. What's the use case of having multiple organizations with the same datasource instances? Could you please open an issue to track this feature request so we can see if other users wants/needs this.

For now I'm going to give you some feedback:
* I would recommend that you only add support for this in the v1 schema, v0 is the legacy one which shouldn't be used.
* In your failing test I think you've mixed up v0 and v1 (forgot version in yaml test file) since props are named differently in v0 and v1 - orgIds and org_ids.
* Run the tests locally by running `go test ./pkg/...` or `go test ./pkg/services/provisioning/...` to only run the provisioning tests

**Comment by kazeborja** [comment]
Sure, for example, we use Puppet in order to provide the provisioning file, and I'm also changing things there in the puppet-grafana upstream module.

But when doing it looked to me like this would have make more sense as part of the provisioning rather than generating the different files there as part of the configuration. Of course that's mainly my opinion :D

**Comment by torkelo** [comment]
> But when doing it looked to me like this would have make more sense as part of the provisioning rather than generating the different files there as part of the configuration. Of course that's mainly my opinion :D

Yes, it might make sense. If this is a common requirement.

**Comment by kazeborja** [comment]
Agree, there is no sense for this if it's only a one user thing

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana. But I think this is too much of an edge case to support. It would be fairly easy to script this for those users who need it.

**Comment by vivekgautam91** [comment]
> Fixes #12717
> 
> Datasource provisioning with multiple organisations can be a bit repetitive in the current scenario.
> This is a small change that allows datasource provisioning to specify a new field "orgIds", allowing it to provide a list of organisations to add the datasource into.
> 
> An example of the yaml fille will look like:
> 
> ```
> datasources:
>   - name: Graphite
>     type: graphite
>     access: proxy
>     url: http://localhost:8080
>     OrgIds: [1,2]
> ```
> 
> And also allows to delete from multiple organisations:
> 
> ```
> deleteDatasources:
>   - name: Graphite
>     orgIds: [1,2]
> ```
> 
> It respects all the previous functionality, so this is just an optional usage of the provisioning API.

OrgIds is not working in my server,is there any other changes i need to do ?

**Pull request closed without merging**
