### PR TITLE
Add more info in route logging

### PR DESCRIPTION
**Pull request by piotr1212**
Some small improvements in route logging.
- Add remote address
- Add method
- Add protocol
- Add response size
- Use consistent unit for response time (us) https://github.com/grafana/grafana/issues/3229

### CODE REVIEW

**Comment by piotr1212** [comment]
I'm also trying to get the username into the log, but when I request the session it is empty. I suspect this can have something to do with the logger middleware being initialized before the session middleware. Any thoughts?

**Comment by toni-moreno** [comment]
@piotr1212 I've been also reviewing the code with the same goal.

In some test I've captured login name adding at the end of pkg/middleware/middleware.go ( func GetContextHandler())

this command to store login name in the context.

```
c.SetParams("req-user",ctx.SignedInUser.Login)
```

And after retrieve it at pkg/middleware/logger.go (func Logger())
````
```
    rw := res.(macaron.ResponseWriter)
    c.Next()
    req_user := c.Params("req-user")
````

I hope this could help you.

**Comment by piotr1212** [comment]
Ah, thank you! I just took the username from the cookie, see the second commit in the PR. I'm not sure what the "right thing to do" is but the cookie seems to work.

**Comment by toni-moreno** [comment]
I 'm sure is a right way. 

I was also reviewing the way to get org, datasourceid, dashboard, panelid , and target . And the only way I know ( sorry I'm begginer in goland ) is intercepting data from different points and attach to the context with c.SetParams()  an recovering after as described above in the logger.go file.

**Comment by toni-moreno** [comment]
By example we can get datasource, org and  Ip origin from /pkg/api/dataproxy.go

```
func ProxyDataSourceRequest(c *middleware.Context) {
        ds, err := getDatasource(c.ParamsInt64(":id"), c.OrgId)
        c.SetParams("remote-datasource",c.Params(":id"))
        c.SetParams("org",c.OrgId) //perhaps c.OrgName also works
....
        c.SetParams("ip-origin",c.Req.Request.RemoteAddr)
...
}
```

**Comment by toni-moreno** [comment]
The main problem I found is when trying to get Extended data( the backend query itself) , and PanelID

### About PanelID

This data is not mapped anywhere in the HTTP request from the browser, we should also add some JS code to put PaneliD info into the HTTP request.

### About extended data

If I parse request  data with c.Req.Request.ParseForm() at func ProxyDataSourceRequest() at pkg/api/dataproxy.go

````


        if ds.Type == m.DS_CLOUDWATCH {
                cloudwatch.HandleRequest(c, ds)
        } else {
                proxyPath := c.Params("*")
                
                //CODE TO GET FORM DATA 

                c.SetParams("ip-origin",c.Req.Request.RemoteAddr)
                c.Req.Request.ParseForm()
                fmt.Printf("DEBUG FORM DATA: %+v\n",c.Req.Request )

                //END CODE TO GET FORM DATA

                proxy := NewReverseProxy(ds, proxyPath, targetUrl)
                proxy.Transport = dataProxyTransport
                proxy.ServeHTTP(c.RW(), c.Req.Request)

        }

```

I can log the all query data ( bold marked)


DEBUG: {Method:POST URL:/api/datasources/proxy/2/render Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[application/json, text/plain, */*] Content-Type:[application/x-www-form-urlencoded] Referer:[http://192.168.1.102:3000/dashboard/db/dashboard_not_autoupdate_test] Accept-Language:[es,ca;q=0.8,en;q=0.6,en-US;q=0.4] Cookie:[grafana_sess=f490055dcd866306; grafana_user=admin; grafana_remember=ccf96b6ea401bb4dd8ffd61084326092a812be9c5e00697a] Connection:[keep-alive] Content-Length:[106] Origin:[http://192.168.1.102:3000] User-Agent:[Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36] Accept-Encoding:[gzip, deflate]] Body:0xc20835e080 ContentLength:106 TransferEncoding:[] Close:false Host:192.168.1.102:3000 __Form:map[until:[now] format:[json] maxDataPoints:[1920] target:[aliasByMetric(testreload.d4.{d40,d41}.*)] from:[-15min]] PostForm:map[target:[aliasByMetric(testreload.d4.{d40,d41}.*)] from:[-15min] until:[now] format:[json] maxDataPoints:[1920]]__ MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.1.98:57006 RequestURI:/api/datasources/proxy/2/render TLS:<nil>}

But The request through proxy fails.

![image](https://cloud.githubusercontent.com/assets/5883405/11558720/9487af54-99b4-11e5-8649-47e1da7ff49a.png)

If I don't call c.Req.Request.ParseForm(), the data is not mapped to the previous From:map[] struct, but  request through proxy runs ok.

@torkelo @piotr1212 , do you have any suggestion to fix this  strange behaviour

**Comment by piotr1212** [comment]
I'm sorry, don't know.

Let's keep the discussion for further log improvements in your original issue https://github.com/grafana/grafana/issues/3229 to keep this PR clean. 

I want to improve some more logging in other parts of the application but will submit that as separate PR's.

**Comment by toni-moreno** [comment]
Ok thank you @piotr1212

**Comment by toni-moreno** [comment]
Hi @piotr1212 , I've just updated last 2.6.0 grafana with this PR applied.

Now I'm getting this information:

```
2015/12/16 15:48:47 [I] Completed A.B.C.D, W.X.Y.Z - "POST /render HTTP/1.1" 200 OK 2436 bytes in 344156us
2015/12/16 16:01:47 [I] Completed E.F.G.D - "POST /render HTTP/1.1" 200 OK 78752 bytes in 365098us
`````
3 comments about this info.

a) I can not see the userid , perhaps cookie is not the best place to get it.
b) I can not understand why I can see 2 different IP's (A.B.C.D, W.X.Y.Z ) what they mean? , sometimes are 2 IP's and some other just one. ( could be interesting to maintain the same number of fields in each line of log)
c) could be better/easy parse response time  if unit separated from number , this is  "344156 us" better than "344156us"  ( I'm thinking in bash tools like awk or other parser tools like https://github.com/toni-moreno/collectd-apachelog-plugin )

IMHO  the desired format should be  discussed and agreed at least with @torkelo . Are you agree?

**Comment by piotr1212** [comment]
a) this seems an issue specific to the /render call. looking into it
b) I can't reproduce it. Do the IP's make sense to you, are they valid IP's, both the same? Do you use loadbalancers/xforwardfor/realip headers?
c) don't really see the issue, I'm ok with adding a space if people prefer that. 

I actually would like to get some log framework in which support kv type of logging and multiple formatting like logstash-json and configurable outputs for example directly to redis. But this will take me some time.

**Comment by toni-moreno** [comment]
Sorry @piotr1212 , thank you very much for your work and the fast reply.


* About userid : I'm doing logging  through a reverse proxy with mod_ldap, for grafana  are all anonymous users. Should be for this reason that userid is not shown . ( As  a suggestion perhaps could be interesting to log "anonymous"   or "-" to see something where is the expected userid field , like apache does) 

* About IP's .. should be a proxy perhaps I don't know.. but I would like to see only source (user computer) IP.

* About Response Time format: The most standard format should be like apache log ... ( not units , only number ).

Do you have plans to add more fields in the log line like these?

* org which user belongs to
* dashboard that is doing the request
* panelid which renders the returned data.
* datasource from which we are sending the request.
* target/query detailed on the request.

Thank you very much for your work

**Comment by piotr1212** [comment]
Op 16 dec. 2015 5:40 PM schreef "Toni Moreno" <notifications@github.com>:
>
> Sorry @piotr1212 , thank you very much for your work and the fast reply.
>
> About userid : I'm doing logging through a reverse proxy with mod_ldap,
for grafana are all anonymous users. Should be for this reason that userid
is not shown . ( As a suggestion perhaps could be interesting to log
"anonymous" or "-" to see something where is the expected userid field ,
like apache does)

If you Auth in Apache grafana has no way of knowing the user. Grafana has
full ldap support, you could try that. The - is there if grafana can't find
the user.

>
> About IP's .. should be a proxy perhaps I don't know.. but I would like
to see only source (user computer) IP.

Yes, the two ip's is clearly a bug, which I have not been able to
reproduce. Any info about your configuration will help me.

>
> About Response Time format: The most standard format should be like
apache log ... ( not units , only number ).
>
> Do you have plans to add more fields in the log line like these?
>
> org which user belongs to
> dashboard that is doing the request
> panelid which renders the returned data.
> datasource from which we are sending the request.
> target/query detailed on the request.
>

Yes I want these but don't know if router log is the right place to add all
this logic.

**Comment by piotr1212** [comment]
/render missing username logging is fixed here https://github.com/piotr1212/grafana/commit/e29e3416dbeb9fdcb6ec433ef5982cee107d4fb4
space is added in this commit https://github.com/piotr1212/grafana/commit/c197c4073ee93b517ba17860fb78e354d4bcab2b

Will create PR after some internal testing.

I really cannot reproduce the double IP adresses, even not with an apache mod_proxy in front. Could you please open an issue with description how to reproduce?

**Pull request merged**
