### PR TITLE
Alerting: SIGNL4 Notification Channel Added

### PR DESCRIPTION
**Pull request by rons4**
Added SIGNL4 notification channel as another alerting option in Grafana.

**What this PR does / why we need it**:

SIGNL4 is an additional alerting option for Grafana users in the IT or IoT field. It allows app-based alerting including escalations, collaboration, duty planning and resolutions  (according to the alert status in Grafana).

**Which issue(s) this PR fixes**:

New notification channel.

Fixes #

**Special notes for your reviewer**:

I have tested the alerting and resolution functionality and this works great. If you would like to test this you can get the SIGNL4 app in the Google App Store or Apple Play Store or here: https://www.signl4.com/free-trial-test/

If you have any questions or if you should need any additional information please just let me know.

### CODE REVIEW

**Comment by aknuds1** [comment]
We have to discuss internally first if we want to accept this notifier or not.

**Comment by rons4** [comment]
Thanks @aknuds1. Just let me know if I can be of any assistance here.

**Comment by aknuds1** [comment]
Thank you for submitting this PR, but we have decided to reject it since we're generally not accepting new notifiers into Grafana core and it's also not linked to a feature request with enough upvotes.

We are hoping to have a plugin model for notifiers in place in the future, and that will be the solution going forward. Unfortunately it isn't implemented yet.

**Comment by rons4** [comment]
Thanks for considering the PR, @aknuds1 and I understand your point.
We surely see some demand and I hope you can reconsider this option in the future. A plugin model for notifiers would also be nice.

**Pull request closed without merging**
