### PR TITLE
Add Dynamic Datasources

### PR DESCRIPTION
**Pull request by jonnyreeves**
Rebase toni-moreno's DataSource Variables branch and modify it so that `datasourceSrv.js` treats dynamic data-sources as first-class concepts.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
This PR continues the work started by @toni-moreno in issue #1055.  I've rebased the code and bought it up to date with master and altered the implementation so it no longer makes use of [`Object.setPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf).

Thanks for this fantastic project! :+1:

**Comment by toni-moreno** [comment]
Wow !!!  Great Job @jonnyreeves . 

I'm greatly surprised and grateful for this PR. I like somebody can finish my work. 

@torkelo: I think now is time to merge !!!! 

:)

Than you very much to everybody  who is contributing to grafana !!

**Comment by mwitkow** [comment]
This is precicely what we need for https://github.com/grafana/grafana/issues/816! Finally we'll be able to use single Grafana template for multiple Prometheus servers in different datacenters :)

@juliusv, this reminds me of my struggle with Promdash to get cluster URL variable interpolation :D

**Comment by juliusv** [comment]
@mwitkow yeah, we got it added for you back then :)

If I understand it correctly, this PR here requires specifying the entire datasource name as a variable, as opposed to only templating part of it? PromDash solves this by allowing you to put variables into the URL of a datasource, like `http://prometheus-some-team-{{zone}}:9090/`. In the dashboard you then just define the `zone` variable and it gets inserted into the datasource URL. This also means that you don't actually need to create 20 data sources if you have 20 datacenters, but only a single templated one. I wonder if this could be possible in Grafana too?

/cc @grobie, who requested this feature at GrafanaCon (https://www.youtube.com/watch?v=cXVI08iEu60).

**Comment by mwitkow** [comment]
@juliusv, I think doing an interpolated URL inside a datasource would be way harded than this change. A nice middle ground would be an ability to only show in the dropdown the datasources that match a given substring.
This way you do need to maintain the datasources, but they automatically populate the variable. But I do believe that would be another PR on top of this.

**Comment by jonnyreeves** [comment]
Rebased against master and added basic test-coverage.

@torkelo please let me know your thoughts on this pull.

**Comment by grobie** [comment]
Great work!

My idea included indeed your suggested match string, I think a regex would provide the user with a good interface. I'd separate the idea of making it easier to maintain many servers from this PR. There are probably more use cases than our one-server-per-region one. I expect many setups which don't necessarily have a pattern in their server names like in @juliusv's example `http://prometheus-some-team-{{zone}}:9090/`. For these the current implementation makes sense. I have an idea for that use case which could be implemented separately.

LGTM!

**Comment by jonnyreeves** [comment]
This PR now allows the user to supply a regex to use as the dynamic datasource.  2015 was not the year for this PR, but I am hopeful for 2016 :fireworks:

**Comment by torkelo** [comment]
the approach of this PR is much simpler and better I think, https://github.com/grafana/grafana/pull/3178

**Comment by jonnyreeves** [comment]
> the approach of this PR is much simpler and better I thin

Which PR?  You've linked to this one :)

**Comment by torkelo** [comment]
Sorry, this one https://github.com/grafana/grafana/pull/2860

**Pull request closed without merging**
