### PR TITLE
Support `$`-replacements in KairosDB like the InfluxDB datasource.

### PR DESCRIPTION
**Pull request by csm**
The InfluxDB 0.8 datasource let you add the following in your alias:
- `$g`, which gets replaced by the grouping value (here, if there are multiple group by columns, they're made into a comma-separated list).
- `$s`, replaced by the series name.
- `$<n>`, for integers `n`, gets replaced by the nth element of the series name, split by periods.

We are looking to add this so the KairosDB datasource has closer parity with the InfluxDB datasource, which we had been using before. We also don't like that you can't control what grouping labels get added to series names.

### CODE REVIEW

**Comment by torkelo** [comment]
I would be great if the series naming and KairsDB response handling and mapping to Grafana time series was abstracted out to its separate component and unit tested. 

There is to much code in the KairosDB data source component and too few unit tests. Look at the InfluxDB 0.9 component InfluxSeries and its unit tests as reference 
ping @masaori335

**Comment by masaori335** [comment]
I agree there are too few unit tests for KairosDB datasource plugin.
It sounds good that separating in components like InfluxDB plugin.

**Comment by newpcraft** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
최중연(choe.jungyeon@naverc...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [grafana] Support `$`-replacements in KairosDB like the InfluxDB datasource. (#2398)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
최중연(choe.jungyeon@naverc...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-07-30 00:00 ~ 2015-07-30 23:59 GMT +09:00]<br>7/30(목) 휴가 입니다. NDOT/NPOT 문의는 조지원 대리님께 부탁드립니다.
--------------------------------------------

**Comment by csm** [comment]
No arguments that abstracting and testing this more is a better way to go. It even might make sense to somehow make some of these things shared among different datasources.

My primary goal was to just get feature parity with the InfluxDB datasource for our internal users. I can look into refactoring this if I have the time.

**Pull request closed without merging**
