### PR TITLE
Loki: Replace hardcoded css values

### LINKED ISSUE #55949: features/logs/components: Use theme styling instead of hardcoded values
In `public/app/features/logs/components` we use a lot of hard-coded stylings (e.g. `10px`). We should update all of these to use values from GrafanaTheme2.

### PR DESCRIPTION
**Pull request by itsgareth**
**What is this feature?**

this PR replaces all hardcoded css values in `public/app/features/logs/components/`

**Why do we need this feature?**

...

**Who is this feature for?**

...

**Which issue(s) does this PR fix?**:

Fixes #55949 

**Special notes for your reviewer**:

...

### CODE REVIEW

**Review by matyax — COMMENTED** [review]
Great work! I'm a bit concerned about some of the values used here, like 0.625 and 0.094. I'm not sure if we should address those in a different way instead of magic multipliers.

**Comment by gwdawson** [comment]
> Great work! I'm a bit concerned about some of the values used here, like 0.625 and 0.094. I'm not sure if we should address those in a different way instead of magic multipliers.
@matyax do you have any suggestions on what would be a better solution?

**Comment by matyax** [comment]
@gwdawson no suggestions from me. Pinging @grafana/observability-logs

**Review by matyax — CHANGES_REQUESTED** [review]
Like it was discussed in Slack, let's only replace values that are multiples of 0.25 and leave the others as fixed values.

**Review by matyax — APPROVED** [review]
👏 👏

**Pull request merged**
