### PR TITLE
Add support for InfluxDB fields in where clause

### LINKED ISSUE #2674: FR: Support field in where clause in InfluxDB query editor
With the influx query editor it isn't possible to select "value" in the where clause. This would be very useful for me. At the moment i do not use the editor to solve this problem:
2015-09-04 14_03_08-grafana - meg-pxy - internet explorer

### PR DESCRIPTION
**Pull request by kichristensen**
Add support for InfluxDB fields in where clause. Values are only shown for tags as there most likely is way too many for fields.

closes #2674

### CODE REVIEW

**Comment by techge** [comment]
I am very glad to see this PR, as I stumbled across this problem yesterday... thank you very much!

I tested this by including this file directly to the grafana/grafana:master docker container, but I still couldn't use the fields in the where-clause. Any idea, what went wrong?

You write the Values are not shown, but the field keys should get listed, right?

PS: my docker-compose.yml setup, as a sanity-check :wink: the query_ctrl.ts is in the same folder as the docker-compose.yml...
```
  grafana:
    image: grafana/grafana:master
    volumes:
      - ./query_ctrl.ts:/usr/share/grafana/public/app/plugins/datasource/influxdb/query_ctrl.ts
...
```

**Comment by kichristensen** [comment]
Yes the field keys should get listed. I'll rebase this and check that it still works.

**Comment by kichristensen** [comment]
@techge I've just rebased and the fields are still shown to me. Maybe in your case the plugin is already packed in the Docker images.
But I found a little error in the PR at the same time. It is not possible to filter on tags after a field has be added. I'll work on that

**Comment by kichristensen** [comment]
The reason tags won't show up in the editor after adding a field is because the available tags are filtered using the ```SHOW TAG KEYS```query, but this does not handle fields in the ```WHERE``` clause. What is needed is some kind of metadata on the segments in the ```WHERE``` clause, any suggestions on how this should be implemented, while still making sense in non InfluxDB editors?

**Comment by torkelo** [comment]
Not sure this is worth the extra complexity of having to do an extra lookup query here, and as raised it makes it unclear on what the where clauses is filtering on (is it a tag or value). 

Think the raw text edit mode can handle this scenario. #2674 is an old feature request with not a lof demand which is also a reason this feels like something we can live without.

**Comment by stoyan-SLN** [comment]
Hello All,

It's been almost 3 years and I still see this as a valuable feature in Grafana.

Imagine you have a group of engineers(not familiar with SQL/InfluxQL/Flux) that need to build their queries by themselves and at the same time they need to select a field that is present only in data that has a specific tag on it. 

This is possible with the InfluxDB Explore widget/page, but not possible with Grafana. Since Grafana shall be a better visualization tool, why do we still argue if this feature shall be added - it is clearly needed!

**Comment by homeseer666** [comment]
> InfluxDB Explore widget/page,

I have to agree on this, took a while to find the workaround and hoping this feature can be added to the roadmap if not already on it... thx

**Comment by homeseer666** [comment]
> Hello All,
> 
> It's been almost 3 years and I still see this as a valuable feature in Grafana.
> 
> Imagine you have a group of engineers(not familiar with SQL/InfluxQL/Flux) that need to build their queries by themselves and at the same time they need to select a field that is present only in data that has a specific tag on it.
> 
> This is possible with the InfluxDB Explore widget/page, but not possible with Grafana. Since Grafana shall be a better visualization tool, why do we still argue if this feature shall be added - it is clearly needed!

I have to agree on this, took a while to find the workaround and hoping this feature can be added to the roadmap if not already on it... thx

**Pull request closed without merging**
