### PR TITLE
DataFrame: Add explicit histogram frame type

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/support-escalations/issues/4731

also adds automatic xMin or xMax inference, so a frame can contain only `xMin,count1,count2...` or only `xMax,count1,count2...`. the caveat being this will only work for frames with > 1 bucket, which i hope is most histograms!

this also contains some adjustments to Histogram legend which fixes the series to legend mappings in several cases.

### CODE REVIEW

**Comment by leeoniya** [comment]
@mdvictor can you take a look at this one?

i think it reverts your https://github.com/grafana/grafana/pull/53284 PR, but i could not get the legend calcs to fail in the updated gdev dashboard [1] and there is not test dashboard or test cases attached there, so not sure what to validate against. cc @zoltanbedi 

EDIT: actually, this revert may _fix_ the legend calcs:

before:

image

after:

image

[1] http://localhost:3000/d/UTv--wqMk/panel-tests-histogram?orgId=1

**Comment by leeoniya** [comment]
added `backport-9.3.x` due to legend fix.

**Review by leventebalogh — COMMENTED** [review]
Gave it a quick check (even though these declarations were marked as alpha) in our [plugin imports dashboard](https://ops.grafana-ops.net/d/bML5aAb7k/plugins-imports?orgId=1) and in https://cs.github.com and it seems nothing is depending on these props, so I think it's all good from a breaking changes perspective. 👍

**Comment by leeoniya** [comment]
> Are there any migration paths defined for the old histograms which are pre-aggregated with "bucketMin" and "bucketMax" kind of naming convention?

this format has never been official or documented as far as i know. we originally made it as a placeholder and have always treated it as alpha and always said it will change/break.

**Comment by mdvictor** [comment]
> @mdvictor can you take a look at this one?
> 
> i think it reverts your #53284 PR, but i could not get the legend calcs to fail in the updated gdev dashboard [1] and there is not test dashboard or test cases attached there, so not sure what to validate against. cc @zoltanbedi
> 
> ~EDIT: actually, this revert may _fix_ the legend calcs:~
> 
> EDIT2: never mind, i understand what #53284 was doing. i wonder what we should do for pre-computed histograms (or histograms created from already aggregated data -- none of the calcs make sense, but i guess that's on the user.
> 
> before:
> 
> image
> 
> after:
> 
> image
> 
> [1] http://localhost:3000/d/UTv--wqMk/panel-tests-histogram?orgId=1

Looked over the new format and legend calcs are working properly with the new implementation. Awesome work!

**Comment by ryantxu** [comment]
@yesoreyeram -- I added a function so we can accept both for a while.

> this format has never been official or documented as far as i know

@leeoniya true... but looks like new-relic plugin figured out how to use it, so we should support it

**Review by ryantxu — APPROVED** [review]
LGTM

**Pull request merged**
