### PR TITLE
Chore: Update @testing-library/dom to v9.3.3

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Update @testing-library/dom to v9.3.3

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by domasx2 — APPROVED** [review]

**Comment by itsmylife** [comment]
I just wanted to upgrade the version 🤦 
image

**Comment by itsmylife** [comment]
I am not sure what's the reason and here is the comparison between v9.3.1 and v9.3.3 https://github.com/testing-library/dom-testing-library/compare/v9.3.1...v9.3.3
Even v9.3.2 is causing the failures.

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Comment by itsmylife** [comment]
For the future here is the thread to handle the problem https://raintank-corp.slack.com/archives/C02FLGJJEG4/p1697039051845429
`yarn dedupe` is the answer.

**Pull request merged**
