### PR TITLE
DashboardSrv: export getDashboardSrv to react

### PR DESCRIPTION
**Pull request by ryantxu**
Simple part of #16660 -- gives react access to the current dashboardSrv

### CODE REVIEW

**Comment by mtanda** [comment]
@ryantxu If React panel plugin want to access DashboardSrv, is it possible?
Or, need to add DashboardSrv to `grafana-runtime`?

**Comment by torkelo** [comment]
what do you want to do? It should preferably only be one via PanelProps as we want a panel plugin to be usable outside a dashboard context

**Comment by mtanda** [comment]
@torkelo I want to switch Visualization from panel plugin. (I'm not sure, it is possilble by using DashboardSrv.)
The panel plugin access external API endpoint, and receive JSON, render panel.
So, I want to create Scripted panel plugin.

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/pull/15620 is one of the use case of the panel plugin.

**Comment by torkelo** [comment]
>The panel plugin access external API endpoint, and receive JSON, render panel.

Is that not what every panel do? you have queries to a data source => data => render panel

**Comment by mtanda** [comment]
@torkelo 
I imagine the API endpoint respond to panel properties.
Sorry for confusing you. It is one of the use case of the plugin.

Like scripted dashboard, the panel plugin execute script which storead at Grafana server side.
The plugin set panel properties generated from script.
The special type plugin doesn't have visualization, it need to switch visualization after setting panel properties.

1. Panel plugin get script from Grafana server side
2. Panel plugin execute script and generate panel properties, if external resource is required, get it from remote endpoint
3. Set panel properties to panel
4. Switch visualization to Graph/Table/SingleStat, which specified in panel properties

To switch visualization, I guess the panel plugin need to call `onPluginTypeChange()`.
https://github.com/grafana/grafana/blob/v6.3.3/public/app/features/dashboard/dashgrid/DashboardPanel.tsx#L64-L66

I want to call it from panel plugin.

**Comment by mtanda** [comment]
Why I want to make Scripted panel plugin is, the Scripted dashboard is hard to maintain.
Scripted dashboard can't utilize templating, because the script is not re-evaluated after variable is changed.

**Comment by ryantxu** [comment]
interesting -- the biggest issue I see is with how to deal with the panel editor.  In #15620, I just hide it.  Maybe we should start a different issue to discuss this more?

In this case, yes you can get `getDashboardSrv()` via `@grafana/runtime` -- and then access to the raw PanelModel (complete with changePlugin) via the id.

**Comment by mtanda** [comment]
@ryantxu Sorry, I'm not familiar with React panel plugin. I imagine Scripted panel plugin itself has panel editor, it could has some properties to pass some input for script.

When the panel visualization is changed to Graph or other panels, the panel editor of Scripted panel itself is hided. If user want to modify Scripted panel, switch back the visualization to Scripted panel, and modify it by panel editor of Scripted panel.

**Comment by mtanda** [comment]
In my opinion, the feature, reusing the same panel in multiple dashboards should be provided Official Grafana release.

Scripted panel plugin is hacky solution, so it is better to provide as 3rd party panel plugin.
If Grafana provides the way to switch Visualization, I'll try to make the plugin.

**Pull request merged**
