### PR TITLE
@grafana/e2e: improvements

### PR DESCRIPTION
**Pull request by stevenvachon**
See commit message(s).

### CODE REVIEW

**Comment by ryantxu** [comment]
This seems like a bad idea... maybe 6 hours max?

many timestream databases become very expensive for "large" (more than a few hours) and not recent data.  likely it does not matter much, but we should be very careful before promoting a larger time range query by defualt

**Comment by stevenvachon** [comment]
The query editor seems to default the limit to 25 if that helps? I was just trying to get any data at all to display by default, mainly for ServiceNow at the moment.

**Comment by ryantxu** [comment]
Can you pass in the date range easily?  changing the default seems odd since ServiceNow is a very very non standard datasource

**Comment by stevenvachon** [comment]
> Can you pass in the date range easily?

Yup, it's a config option: `openDashboard({ timeRange: { from: '', to: '' } })`

I've made some new changes too; pushing now.

**Review by ryantxu — APPROVED** [review]
LGTM

in master/7.1+ the timezone is also configured in the same popup -- should it be moved to the same structure and set at the same time?

**Comment by stevenvachon** [comment]
Oh, nice, I hadn't noticed that change. Maybe we can update the flows later when we have other flows for the settings window? In its current state, it at least tests that UI a bit.

**Pull request merged**
