### PR TITLE
@grafana/ui: Add support for showing selected options in `Select`

### PR DESCRIPTION
**Pull request by aangelisc**
This PR adds the `hideSelectedOptions` prop to the `Select` component which provides us with flexibility in displaying options to users.

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
Is this specifically to work with a MultiSelect? Do you have an example of what you would like to achieve?
We have a task to rethink our Select component and one of the complaints is that it has too many props 😬 so want to double check what the use case is in case we can do a workaround.

**Comment by aangelisc** [comment]
Hey @JoaoSilvaGrafana! This is for a multi-select component. I've built this component with custom options and when an option is selected I'd like for it to remain in the list (makes it easier for users to edit the list as they go).
image

**Review by JoaoSilvaGrafana — APPROVED** [review]
Thanks for the example @aangelisc ! Seems ok to have this 😄
In our future exploration of this component we will want to make all Selects at Grafana more consistent, so might ask for your feedback then about what would you like to see in it!

**Comment by aangelisc** [comment]
Sounds great, thank you for the review @JoaoSilvaGrafana 💯

**Pull request merged**
