### PR TITLE
Add wechat notifier

### LINKED ISSUE #12333: Add WeChat Notifier
Add a new notifier : WeChat
WeChat is popular in China, you can get more info here: https://www.wechat.com/en/

We need Grafana send alert to WeChat.

### PR DESCRIPTION
**Pull request by robbinfan**
Fix #12333

### CODE REVIEW

**Comment by robbinfan** [comment]
ping @daniellee

**Comment by marefr** [comment]
Thank you for contributing. Could you please create an issue to track this feature and then reference that issue in PR description, like `Fixes #<issue number>`? We already have a lot of alert notifiers in core Grafana and would only consider merging this if the issue got a lot of upvotes, i.e. if it's popular enough. 

Long term we would like to support alert notifiers thru a plugin system, but we don't have that in place right now.

**Comment by jgli** [comment]
Good job!

**Comment by jgli** [comment]
Good job!

**Comment by bergquist** [comment]
Hi @robbinfan thank you for taking the time to contribute to Grafana! But we are currently not merging new alert notifiers unless they have proven very popular. We already have more notifiers than we can maintain. So this has to wait until we support alert notifiers as backend plugins. In the meantime, I suggest you write a custom web server that integrates Grafanas alert notification webhooks with Wechat.

**Comment by qdsang** [comment]
@bergquist This is really important in China.

**Comment by lightningMan** [comment]
This is really important in China.

**Comment by forestlzj** [comment]
This is really important in China.

**Comment by fzqdyyd** [comment]
Hello, there is no wechat option in the version grafana-6.7.1-1.x86_64 that I am using. When will this function be available? Urgently!Thank you very much!

**Comment by bergquist** [comment]
This is too old to reopen. But if anyone wants to submit a PR for Wechat I would be happy to review

**Comment by fzqdyyd** [comment]
Hi, Carl Bergquist   

https://github.com/wangriyu/docker-grafana/tree/master/wechat-notifier

This is a wechat notification function module written by a Chinese friend two years ago. Maybe due to too much time, some online modules that we rely on have changed, resulting in compilation failure.I really want to use wechat module, but I don't understand the go, so can you help me to look at the inside of the reason for the error, or can repair, add wechat alarm type to grafana, now in China, we are very like grafana, the wechat is the first big social inform APP, trouble to increase this option, this will let grafana is more popular in China, also facilitate users in China, thank you!The eldest brother!


> This is too old to reopen. But if anyone wants to submit a PR for Wechat I would be happy to review

**Comment by ijintong** [comment]
什么时候官方能加上企业微信的呢？

**Comment by 141Mr-liu** [comment]
When will the official WeChat be added?

**Pull request closed without merging**
