### PR TITLE
Plugins: Fix colon in CallResource URL returning an error when creating plugin resource request

### LINKED ISSUE #79745: Elasticsearch: broken cross-cluster search
### What happened?

I added a new Elasticsearch data source with index name like `foo,othernode:foo`. I clicked "Save & Test". This is a completely valid Elasticsearch syntax in the remote clusters feature: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html.

### What did you expect to happen?

Everything to work.

### Did this work before?

Yes, it broke somewhere between 9.5.3 and 10.2.2.

### How do we reproduce it?

1. Go to data source settings
2. Add new elasticsearch data source
3. Ensure that the index name field contains a colon character
4. Click "Save & Test"
5. See a call to _mappings that fails

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.2.2

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch

### PR DESCRIPTION
**Pull request by GiedriusS**
url.Parse() does not handle the given input correctly when the input contains a colon character. The user will see the following error message when trying to use remote cluster in Elasticsearch:

```
level=warn msg="Failed for create plugin resource request" error="parse \"foo-*,*:foo-*/_mapping\": first path segment in URL cannot contain colon" traceID=
```

As far as I can tell, we only want to set the path here + rawquery so avoid url.Parse() altogether.

**What is this feature?**

N/A

**Why do we need this feature?**

N/A

**Who is this feature for?**

N/A

**Which issue(s) does this PR fix?**:

Fixes #79745

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by GiedriusS** [comment]
@zserge @mildwonkey @idafurjes anyone?

**Comment by xnyo** [comment]
Hi and thank you for your contribution!

From a `CallResource` point of view, the changes make sense to me. From my testing and by comparing with the curent `main`, we are only interested in the relative path, which is `Path` + `RawQuery`.

I have also merged the latest `main` branch so CI can run fine.

However, if I try to reproduce the original issue described in #79745 (adding an Elasticsearch datasource with `foo,othernode:foo` index), the `/resources/foo,othernode:foo/_mapping` request still fails with a 500 error:

```
ERROR[01-24|16:02:03] Failed to parse data source path         logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName=elasticsearch-1 dsUID=b2d54c90-8ff5-403f-940d-e0937ff68240 uname=admin error="parse \"foo,othernode:foo/_mapping\": first path segment in URL cannot contain colon" url=foo,othernode:foo/_mapping
ERROR[01-24|16:02:03] Plugin Request Completed                 logger=plugin.instrumentation endpoint=callResource pluginId=elasticsearch dsName=elasticsearch-1 dsUID=b2d54c90-8ff5-403f-940d-e0937ff68240 uname=admin status=error duration=72.045µs eventName=grafana-data-egress time_before_plugin_request=723.449µs error="[plugin.downstreamError] client: failed to call resources: parse \"foo,othernode:foo/_mapping\": first path segment in URL cannot contain colon" statusSource=plugin
ERROR[01-24|16:02:03] Internal server error                    logger=context userId=1 orgId=1 uname=admin error="[plugin.downstreamError] client: failed to call resources: parse \"foo,othernode:foo/_mapping\": first path segment in URL cannot contain colon" remote_addr=127.0.0.1 traceID=
ERROR[01-24|16:02:03] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/uid/b2d54c90-8ff5-403f-940d-e0937ff68240/resources/foo,othernode:foo/_mapping status=500 remote_addr=127.0.0.1 time_ms=0 duration=859.996µs size=116 referer=http://127.0.0.1:3000/connections/datasources/edit/b2d54c90-8ff5-403f-940d-e0937ff68240 handler=/api/datasources/uid/:uid/resources/*
```

This is because the Elasticsearch plugin itself uses `url.Parse` to extract the index name from the URL, here:

https://github.com/grafana/grafana/blob/0cf6b94fa24b3d7e13c5b975989ec09470d22ed1/pkg/tsdb/elasticsearch/elasticsearch.go#L210-L214

So this would need to be changed as well. Alternatively, I would also consider using a POST request instead, and putting the index name in the body rather than in the URL.

cc @ivanahuckova

**Comment by GiedriusS** [comment]
Thanks for testing out and seeing if this helps, I had a hard time running Grafana on my computer so I couldn't test thoroughly if this PR is the only one that needs to be merged for fixing the original problem. :bow: I am deeply grateful for your work

**Comment by xnyo** [comment]
> Elastic API expects `GET` request https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html so I'd prefer to use that. Also I like the idea of keeping this simple and just fixing using `GET` on both grafana resource call and when sending to Elastic. So if this PR is good from your perspective, feel free to merge and I create additional PR to tackle the logic in Elastic. 🙂

Another option could be encoding the index name in base64 so it's url-safe.

If we decide to keep the current request, this PR makes sense to me from a `CallResource` point of view, but I would also wait on @marefr or @wbrowne before merging to double check that I am not missing anything. @ivanahuckova then you can go ahead and do the changes on the Elasticsearch plugin side.

**Comment by marefr** [comment]
> > Elastic API expects `GET` request https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html so I'd prefer to use that. Also I like the idea of keeping this simple and just fixing using `GET` on both grafana resource call and when sending to Elastic. So if this PR is good from your perspective, feel free to merge and I create additional PR to tackle the logic in Elastic. 🙂
> 
> Another option could be encoding the index name in base64 so it's url-safe.

Can we URL encode the index before making the request or doesn't matter? Don't you have to do that before calling the ES mapping endpoint as well? `foo-*,*:foo-*` => `foo-%2A%2C%2A%3Afoo-%2A`
 
> If we decide to keep the current request, this PR makes sense to me from a `CallResource` point of view, but I would also wait on @marefr or @wbrowne before merging to double check that I am not missing anything. @ivanahuckova then you can go ahead and do the changes on the Elasticsearch plugin side.

Think this make sense, but curious why we used `url.Parse` in the first place and if it was for some specific use case. I guess to make sure URL is valid but also that all fields of URL would be populated correctly. Would using https://pkg.go.dev/net/url#ParseRequestURI instead be a better solution? Would be good with a test perhaps verifying that query parameters are properly included in the `CallResourceRequest.URL` field since that's what the code seems to solve?

**Comment by ivanahuckova** [comment]
> Can we URL encode the index before making the request or doesn't matter? 

I tried encoding with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent but it doesn't work and returns the same error ☹️

image

```WARN [01-24|17:28:17] Failed for create plugin resource request logger=context traceID=cc1e20ca445cf305254be397b84e9f5e userId=1 orgId=1 uname=admin error="parse \"abc,def:ghi/_mapping\": first path segment in URL cannot contain colon" traceID=cc1e20ca445cf305254be397b84e9f5e```

**Comment by xnyo** [comment]
> Would using https://pkg.go.dev/net/url#ParseRequestURI instead be a better solution?

I tried `url.ParseRequestURI(rawURL)` instead of `url.Parse(rawURL)` and it returns the same error. Under the hood they both call the same function that checks for colons (`url.parse`), so unfortunately it doesn't work.

> Would be good with a test perhaps verifying that query parameters are properly included in the `CallResourceRequest.URL field` since that's what the code seems to solve?

I can add a test case for query params, I tested those manually and they were working fine but a test case is definitely a good idea :+1:

**Comment by marefr** [comment]
Was curious and backtracked the introduction of this code from 3,5 years ago and of course by me https://github.com/grafana/grafana/pull/25472/commits/5b951c7725a519c0ba15ae9e6a6be720b2b4d445 #25472 :sweat_smile:  No tests or anything so hard to tell why exactly I added it, but I guess I realized somehow query parameters was not forwarded correctly. 
https://github.com/grafana/grafana/blob/c0f3b2929c8f62104745adf65968973c42e96237/pkg/plugins/backendplugin/manager.go#L281-L292

**Comment by xnyo** [comment]
> Would be good with a test perhaps verifying that query parameters are properly included in the `CallResourceRequest.URL` field since that's what the code seems to solve?

I have added more tests to ensure query parameters are forwarded correctly

**Review by marefr — APPROVED** [review]
LGTM

**Comment by ivanahuckova** [comment]
@xnyo @marefr some tests are failing in this PR, so we are not able to merge. Whenever you have time, could you please have a look. 🙂

**Comment by xnyo** [comment]
@ivanahuckova CI is now passing and we can merge. I don't think this requires backporting (not a critical bugfix), WDYT?

**Comment by ivanahuckova** [comment]
> I don't think this requires backporting (not a critical bugfix), WDYT?

+1

**Comment by xnyo** [comment]
@ivanahuckova PR is now merged. You can now make the required changes in the Elasticsearch plugin to handle colons on the plugin's side  :partying_face:

**Pull request merged**
