### PR TITLE
Added move row to top and bottom and insert row capability.

### PR DESCRIPTION
**Pull request by utkarshcmu**
PR for #1994

### CODE REVIEW

**Comment by utkarshcmu** [comment]
PR for #1142

**Comment by utkarshcmu** [comment]
@torkelo - Do you want to keep this PR for Milestone 3.0(as this resolves 2 issues in Milestone 3.0) or can this be merged in 2.5 as it does not have too much complexity?

**Comment by gdubicki** [comment]
Where is that "move row to top" and "move row to bottom"? I don't see it in this menu:
screenshot 2017-05-03 16 20 32

**Comment by daniellee** [comment]
It got removed in a redesign in October: https://github.com/grafana/grafana/commit/c609586ff0c9c79444e79aa54eb7f8518ee78447#diff-d4c9756e0a8ae0eef410cbbc12a511da

**Pull request merged**
