### PR TITLE
New Editor: add json diff view

### PR DESCRIPTION
**Pull request by ryantxu**
this is the first draft at having the JSON show up as a diff view...

I'm not sure this library is the best to work with

### CODE REVIEW

**Comment by dprokop** [comment]
Eh, same branch open locally here...

**Comment by dprokop** [comment]
I find the styles quite odd though

**Comment by ryantxu** [comment]
you mean you don't like this:
image
!

**Comment by dprokop** [comment]
hehe, it looks "quite" better in light theme ;)

**Pull request closed without merging**
