### PR TITLE
Gauge/BarGauge: Improvements to auto value font size 

### LINKED ISSUE #17261: Gauge Panel Font Size
**What happened**:
image
using the "Gauge"-Panel the font size is quite small and difficult to read if displayed on a wall mounted TV for example.

**What you expected to happen**:
image
Using the "Singlestat"-Panel you can manually adjust the font size. It should be automatically scaled or manually adjustable again.

**How to reproduce it (as minimally and precisely as possible)**:
use a Gauge-Panel to display an percent value.

```json
{
  "datasource": "<--->",
  "gridPos": {
    "h": 3,
    "w": 3,
    "x": 6,
    "y": 9
  },
  "id": 23,
  "links": [],
  "options": {
    "fieldOptions": {
      "calcs": [
        "last"
      ],
      "defaults": {
        "max": 1,
        "min": 0,
        "unit": "percentunit",
        "decimals": 0
      },
      "mappings": [],
      "override": {},
      "thresholds": [
        {
          "color": "green",
          "index": 0,
          "value": null
        },
        {
          "color": "#EAB839",
          "index": 1,
          "value": 0.3
        },
        {
          "color": "red",
          "index": 2,
          "value": 0.8
        }
      ],
      "values": false
    },
    "orientation": "auto",
    "showThresholdLabels": false,
    "showThresholdMarkers": true
  },
  "pluginVersion": "6.2.0",
  "repeatIteration": 1558605055169,
  "repeatPanelId": 18,
  "repeatedByRow": true,
  "scopedVars": {
    "prom": {
      "selected": false,
      "text": "<--->",
      "value": "<--->"
    }
  },
  "targets": [
    {
      "expr": "sum(container_memory_usage_bytes{id=\"/\"}) / sum(machine_memory_bytes)",
      "format": "time_series",
      "instant": true,
      "intervalFactor": 1,
      "legendFormat": "Usage",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "transparent": true,
  "type": "gauge"
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v6.2.0 (5d16da7)`
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image on ubuntu host
- User OS & Browser: Chrome 75.0.3770.51 (beta), Firefox 67.0 on macOS 10.14.5
- Grafana plugins: none
- Others: -

### PR DESCRIPTION
**Pull request by torkelo**
Tweaks to auto font size logic for Gauge and Bar Gauge 

Fixes #17261

### CODE REVIEW

**Comment by DanielG27** [comment]
Hi, I am still having trouble with Gauge/BarGauge font size in Grafana 6.2.1. Is there something I am missing? Thanks!

**Comment by torkelo** [comment]
Can you describe / show your  problem?

**Comment by DanielG27** [comment]
I have the exact same problem as issue #17621. The font size is quite small and I don't see an option to manually to change the font size.

**Comment by torkelo** [comment]
Can you show? There is not room to increase font size (without adding scrolling )

**Comment by PureSkillz** [comment]
I have the complete opposite. Text size to big.

image

**Comment by mcmara** [comment]
Also for me text size is too big to the point that some gauges are unreadable:
image
How can I force a smaller text size?

**Comment by ryantxu** [comment]
> How can I force a smaller text size?

Might be supported in:
https://github.com/grafana/grafana/pull/29476

**Pull request merged**
