### PR TITLE
[v9.2.x] Chore: Fix vulnerabilities in webpack loader-utils

### PR DESCRIPTION
**Pull request by mckn**
Manual backport from https://github.com/grafana/grafana/pull/57288. We could not apply the same code as in https://github.com/grafana/grafana/pull/57288 because we have different dependencies in `v9.2.x` compared to `main`. So we basically redid all steps but with `v9.2.x` as base.

Before these changes:
```bash
├─ @grafana-plugins/input-datasource@workspace:plugins-bundled/internal/input-datasource
│  ├─ @grafana/toolkit@workspace:packages/grafana-toolkit (via 9.2.2)
│  └─ @grafana/ui@workspace:packages/grafana-ui [6806b] (via 9.2.2 [6806b])
│
├─ @grafana/e2e@workspace:packages/grafana-e2e
│  ├─ babel-loader@npm:8.2.5 [2eb60] (via npm:8.2.5 [2eb60])
│  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  └─ ts-loader@npm:6.2.2 [2eb60] (via npm:6.2.2 [2eb60])
│     └─ loader-utils@npm:1.4.0 (via npm:^1.0.2)
│
├─ @grafana/runtime@workspace:packages/grafana-runtime
│  └─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
│
├─ @grafana/toolkit@workspace:packages/grafana-toolkit
│
├─ @grafana/ui@workspace:packages/grafana-ui
│  ├─ @storybook/addon-docs@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  ├─ @mdx-js/loader@npm:1.6.22 [f6141] (via npm:^1.6.22 [f6141])
│  │  │  └─ loader-utils@npm:2.0.0 (via npm:2.0.0)
│  │  ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │  ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │  │  ├─ babel-loader@npm:8.2.3 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  │  │  │  └─ loader-utils@npm:1.4.0 (via npm:^1.4.0)
│  │  │  │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  │  │     └─ loader-utils@npm:1.4.0 (via npm:^1.2.3)
│  │  │  ├─ babel-loader@npm:8.2.3 [800b9] (via npm:^8.0.0 [800b9])
│  │  │  │  └─ loader-utils@npm:1.4.0 (via npm:^1.4.0)
│  │  │  ├─ css-loader@npm:3.6.0 [800b9] (via npm:^3.6.0 [800b9])
│  │  │  │  └─ loader-utils@npm:1.4.0 (via npm:^1.2.3)
│  │  │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  │  ├─ html-webpack-plugin@npm:4.5.2 [800b9] (via npm:^4.0.0 [800b9])
│  │  │  │  └─ loader-utils@npm:1.4.0 (via npm:^1.2.3)
│  │  │  ├─ postcss-loader@npm:4.3.0 [800b9] (via npm:^4.2.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  │  ├─ raw-loader@npm:4.0.2 [800b9] (via npm:^4.0.2 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  │  ├─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  ├─ @storybook/core@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │  └─ @storybook/core-server@npm:6.4.21 [01697] (via npm:6.4.21 [01697])
│  │  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │     ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │     ├─ @storybook/manager-webpack4@npm:6.4.21 [5aa49] (via npm:6.4.21 [5aa49])
│  │  │     │  ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │     │  ├─ babel-loader@npm:8.2.3 [800b9] (via npm:^8.0.0 [800b9])
│  │  │     │  ├─ css-loader@npm:3.6.0 [800b9] (via npm:^3.6.0 [800b9])
│  │  │     │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │     │  ├─ html-webpack-plugin@npm:4.5.2 [800b9] (via npm:^4.0.0 [800b9])
│  │  │     │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │     │  ├─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │     │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  │     └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  ├─ @storybook/addon-essentials@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/addon-controls@npm:6.4.21 [16cb9] (via npm:6.4.21 [16cb9])
│  │  │  └─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  └─ @storybook/addon-docs@npm:6.4.21 [16cb9] (via npm:6.4.21 [16cb9])
│  │     ├─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │     ├─ @mdx-js/loader@npm:1.6.22 [f6141] (via npm:^1.6.22 [f6141])
│  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     ├─ @storybook/core@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  ├─ @storybook/addon-storysource@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  ├─ @storybook/builder-webpack5@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │  ├─ babel-loader@npm:8.2.3 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  ├─ babel-loader@npm:8.2.3 [ae092] (via npm:^8.0.0 [ae092])
│  │  │  └─ loader-utils@npm:1.4.0 (via npm:^1.4.0)
│  │  ├─ css-loader@npm:5.2.7 [ae092] (via npm:^5.0.1 [ae092])
│  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  └─ style-loader@npm:2.0.0 [ae092] (via npm:^2.0.0 [ae092])
│  │     └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  ├─ @storybook/manager-webpack5@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  ├─ babel-loader@npm:8.2.3 [ae092] (via npm:^8.0.0 [ae092])
│  │  ├─ css-loader@npm:5.2.7 [ae092] (via npm:^5.0.1 [ae092])
│  │  └─ style-loader@npm:2.0.0 [ae092] (via npm:^2.0.0 [ae092])
│  ├─ @storybook/react@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.4 [bff28] (via npm:^0.5.1 [bff28])
│  │  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  │  ├─ @storybook/core@npm:6.4.21 [bff28] (via npm:6.4.21 [bff28])
│  │  │  └─ @storybook/core-server@npm:6.4.21 [b1050] (via npm:6.4.21 [b1050])
│  │  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [4607d] (via npm:6.4.21 [4607d])
│  │  │     │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │     │  ├─ babel-loader@npm:8.2.3 [800b9] (via npm:^8.0.0 [800b9])
│  │  │     │  ├─ css-loader@npm:3.6.0 [800b9] (via npm:^3.6.0 [800b9])
│  │  │     │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │     │  ├─ html-webpack-plugin@npm:4.5.2 [800b9] (via npm:^4.0.0 [800b9])
│  │  │     │  ├─ postcss-loader@npm:4.3.0 [800b9] (via npm:^4.2.0 [800b9])
│  │  │     │  ├─ raw-loader@npm:4.0.2 [800b9] (via npm:^4.0.2 [800b9])
│  │  │     │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │     │  ├─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │     │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  │     ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │     ├─ @storybook/manager-webpack4@npm:6.4.21 [4607d] (via npm:6.4.21 [4607d])
│  │  │     │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │     │  ├─ babel-loader@npm:8.2.3 [800b9] (via npm:^8.0.0 [800b9])
│  │  │     │  ├─ css-loader@npm:3.6.0 [800b9] (via npm:^3.6.0 [800b9])
│  │  │     │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │     │  ├─ html-webpack-plugin@npm:4.5.2 [800b9] (via npm:^4.0.0 [800b9])
│  │  │     │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │     │  ├─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │     │  └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  │     └─ webpack@npm:4.46.0 [800b9] (via npm:4 [800b9])
│  │  └─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  ├─ babel-loader@npm:8.2.5 [2eb60] (via npm:8.2.5 [2eb60])
│  ├─ raw-loader@npm:4.0.2 [601d3] (via npm:4.0.2 [601d3])
│  │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│  ├─ react-docgen-typescript-loader@npm:3.7.2 [601d3] (via npm:3.7.2 [601d3])
│  │  └─ loader-utils@npm:1.4.0 (via npm:^1.2.3)
│  └─ ts-loader@npm:8.4.0 [601d3] (via npm:8.4.0 [601d3])
│     └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
│
├─ @jaegertracing/jaeger-ui-components@workspace:packages/jaeger-ui-components
│  ├─ @grafana/runtime@workspace:packages/grafana-runtime [44900] (via 9.2.2 [44900])
│  └─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
│
└─ grafana@workspace:.
   ├─ @grafana/e2e@workspace:packages/grafana-e2e (via workspace:*)
   ├─ @grafana/toolkit@workspace:packages/grafana-toolkit (via workspace:*)
   ├─ @jaegertracing/jaeger-ui-components@workspace:packages/jaeger-ui-components (via workspace:*)
   ├─ ngtemplate-loader@npm:2.1.0 (via npm:2.1.0)
   │  └─ loader-utils@npm:1.4.0 (via npm:^1.0.2)
   ├─ @grafana/runtime@workspace:packages/grafana-runtime [44900] (via 9.2.2 [44900])
   ├─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
   ├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.7 [655a6] (via npm:0.5.7 [655a6])
   │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
   ├─ babel-loader@npm:8.2.5 [655a6] (via npm:8.2.5 [655a6])
   │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
   ├─ file-loader@npm:6.2.0 [655a6] (via npm:6.2.0 [655a6])
   │  └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
   └─ raw-loader@npm:4.0.2 [655a6] (via npm:4.0.2 [655a6])
      └─ loader-utils@npm:2.0.0 (via npm:^2.0.0)
```

After these changes:

```bash
├─ @grafana-plugins/input-datasource@workspace:plugins-bundled/internal/input-datasource
│  ├─ @grafana/toolkit@workspace:packages/grafana-toolkit (via 9.2.2)
│  └─ @grafana/ui@workspace:packages/grafana-ui [6806b] (via 9.2.2 [6806b])
│
├─ @grafana/e2e@workspace:packages/grafana-e2e
│  ├─ babel-loader@npm:8.2.5 [2eb60] (via npm:8.2.5 [2eb60])
│  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  └─ ts-loader@npm:8.4.0 [2eb60] (via npm:8.4.0 [2eb60])
│     └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│
├─ @grafana/runtime@workspace:packages/grafana-runtime
│  └─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
│
├─ @grafana/toolkit@workspace:packages/grafana-toolkit
│
├─ @grafana/ui@workspace:packages/grafana-ui
│  ├─ @storybook/addon-docs@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  ├─ @mdx-js/loader@npm:1.6.22 [f6141] (via npm:^1.6.22 [f6141])
│  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │  ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │  │  └─ babel-loader@npm:8.2.5 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  │  │     └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  ├─ babel-loader@npm:8.2.5 [800b9] (via npm:^8.0.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  ├─ postcss-loader@npm:4.3.0 [800b9] (via npm:^4.2.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  ├─ raw-loader@npm:4.0.2 [800b9] (via npm:^4.0.2 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  │  └─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │     └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  ├─ @storybook/core@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │  └─ @storybook/core-server@npm:6.4.21 [01697] (via npm:6.4.21 [01697])
│  │  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │  │     ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │     └─ @storybook/manager-webpack4@npm:6.4.21 [5aa49] (via npm:6.4.21 [5aa49])
│  │  │        ├─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  │        ├─ babel-loader@npm:8.2.5 [800b9] (via npm:^8.0.0 [800b9])
│  │  │        ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │        ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │        └─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  ├─ @storybook/addon-essentials@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/addon-controls@npm:6.4.21 [16cb9] (via npm:6.4.21 [16cb9])
│  │  │  └─ @storybook/core-common@npm:6.4.21 [800b9] (via npm:6.4.21 [800b9])
│  │  └─ @storybook/addon-docs@npm:6.4.21 [16cb9] (via npm:6.4.21 [16cb9])
│  │     ├─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │     ├─ @mdx-js/loader@npm:1.6.22 [f6141] (via npm:^1.6.22 [f6141])
│  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     ├─ @storybook/core@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  │     └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  ├─ @storybook/addon-storysource@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  └─ @storybook/source-loader@npm:6.4.21 [f6141] (via npm:6.4.21 [f6141])
│  ├─ @storybook/builder-webpack5@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │  └─ babel-loader@npm:8.2.5 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  ├─ babel-loader@npm:8.2.5 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  ├─ css-loader@npm:5.2.7 [ae092] (via npm:^5.0.1 [ae092])
│  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  └─ style-loader@npm:2.0.0 [ae092] (via npm:^2.0.0 [ae092])
│  │     └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  ├─ @storybook/manager-webpack5@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  ├─ babel-loader@npm:8.2.5 [3ce1d] (via npm:^8.0.0 [3ce1d])
│  │  ├─ css-loader@npm:5.2.7 [ae092] (via npm:^5.0.1 [ae092])
│  │  └─ style-loader@npm:2.0.0 [ae092] (via npm:^2.0.0 [ae092])
│  ├─ @storybook/react@npm:6.4.21 [601d3] (via npm:6.4.21 [601d3])
│  │  ├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.8 [bff28] (via npm:^0.5.1 [bff28])
│  │  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  │  ├─ @storybook/core@npm:6.4.21 [bff28] (via npm:6.4.21 [bff28])
│  │  │  └─ @storybook/core-server@npm:6.4.21 [b1050] (via npm:6.4.21 [b1050])
│  │  │     ├─ @storybook/builder-webpack4@npm:6.4.21 [4607d] (via npm:6.4.21 [4607d])
│  │  │     │  ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │     │  ├─ babel-loader@npm:8.2.5 [800b9] (via npm:^8.0.0 [800b9])
│  │  │     │  ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │     │  ├─ postcss-loader@npm:4.3.0 [800b9] (via npm:^4.2.0 [800b9])
│  │  │     │  ├─ raw-loader@npm:4.0.2 [800b9] (via npm:^4.0.2 [800b9])
│  │  │     │  ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │     │  └─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  │     ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │     └─ @storybook/manager-webpack4@npm:6.4.21 [4607d] (via npm:6.4.21 [4607d])
│  │  │        ├─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  │  │        ├─ babel-loader@npm:8.2.5 [800b9] (via npm:^8.0.0 [800b9])
│  │  │        ├─ file-loader@npm:6.2.0 [800b9] (via npm:^6.2.0 [800b9])
│  │  │        ├─ style-loader@npm:1.3.0 [800b9] (via npm:^1.3.0 [800b9])
│  │  │        └─ url-loader@npm:4.1.1 [800b9] (via npm:^4.1.1 [800b9])
│  │  └─ @storybook/core-common@npm:6.4.21 [ae092] (via npm:6.4.21 [ae092])
│  ├─ babel-loader@npm:8.2.5 [2eb60] (via npm:8.2.5 [2eb60])
│  ├─ raw-loader@npm:4.0.2 [601d3] (via npm:4.0.2 [601d3])
│  │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
│  └─ ts-loader@npm:8.4.0 [2eb60] (via npm:8.4.0 [2eb60])
│
├─ @jaegertracing/jaeger-ui-components@workspace:packages/jaeger-ui-components
│  ├─ @grafana/runtime@workspace:packages/grafana-runtime [44900] (via 9.2.2 [44900])
│  └─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
│
└─ grafana@workspace:.
   ├─ @grafana/e2e@workspace:packages/grafana-e2e (via workspace:*)
   ├─ @grafana/toolkit@workspace:packages/grafana-toolkit (via workspace:*)
   ├─ @jaegertracing/jaeger-ui-components@workspace:packages/jaeger-ui-components (via workspace:*)
   ├─ ngtemplate-loader@npm:2.1.0 (via npm:2.1.0)
   │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
   ├─ @grafana/runtime@workspace:packages/grafana-runtime [44900] (via 9.2.2 [44900])
   ├─ @grafana/ui@workspace:packages/grafana-ui [44900] (via 9.2.2 [44900])
   ├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.7 [655a6] (via npm:0.5.7 [655a6])
   │  └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
   └─ babel-loader@npm:8.2.5 [655a6] (via npm:8.2.5 [655a6])
      └─ loader-utils@npm:2.0.3 (via npm:^2.0.0)
```

### CODE REVIEW

**Comment by gabor** [comment]
note: this is the backport PR for https://github.com/grafana/grafana/pull/57533

**Review by gabor — DISMISSED** [review]
looks fine for a backport PR 👍

**Comment by gabor** [comment]
@mckn , the change in `.yarnrc.yml` changed double-quotes to single-quotes. i assume it will still work, but it might make later backports harder. is that ok?

**Comment by mckn** [comment]
> @mckn , the change in `.yarnrc.yml` changed double-quotes to single-quotes. i assume it will still work, but it might make later backports harder. is that ok?

I will revert that one. Thanks 🙏🏻

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Review by gabor — APPROVED** [review]
LGTM!

**Pull request merged**
