### PR TITLE
Cheery picks for v6.7.2

### PR DESCRIPTION
**Pull request by torkelo**
* Select: Fixed select text positition, (#22952), merge-sha: 89203136eced4417c83a731bfc984584ba8f371a
  * Toolkit: pin babel presets version, (#22974), merge-sha: d8b346f4412587c07d56037e185907d3022b7263
  * DataLinks: make sure we use the correct datapoint when dataset contains null value., (#22981), merge-sha: 41bc1aa3ae5d7218bc8ccf30a6ff73e01c25a465
  * BackendSrv: Adds config to response to fix issue for external plugins that used this property , (#23032), merge-sha: 40d195e4a71e9ffefb50ad4ed2439df285650790
  * Plugins: Fixed issue for plugins that imported dateMath util , (#23069), merge-sha: f75387bd146e6b0c91ede0f01203485f6964885b
  * Dashboard: Fixed issue with saving new dashboard after changing title , (#23104), merge-sha: 046d9c1af46c2d397f30703b82bebbec959190d1
  * Variables: Fixes issue with too many queries being issued for nested template variables after value change, (#23220), merge-sha: 49d2910e393e92eb06c2a78cfe5e2fd4b286ac10
  * Plugins: Expose promiseToDigest, (#23249), merge-sha: ccb8187ccd7cbc978095b5b479d423bbeacddbeb
  * Security: Fix for dashboard snapshot original dashboard link could contain XSS vulnerability in url, (#23254), merge-sha: fb114a75241aaef4c08581b42509c750738b768a
* AzureMonitor: Log Analytics and Application Insights for Azure China #22753

* Bumped version to 6.7.2  (and ran yarn run packages:prepare)

### CODE REVIEW

**Comment by torkelo** [comment]
@aknuds1 anything else we should add (build/ci related)

**Comment by ryantxu** [comment]
If we are allowed, can the whole `@grafana/e2e` folder get merged?
https://github.com/grafana/grafana/tree/master/packages/grafana-e2e

This would let plugins adding e2e testing not need to rely on `canary` (with yarn lock that fails after the next push to grafana master)

**Comment by aknuds1** [comment]
> @aknuds1 anything else we should add (build/ci related)

I'm not aware of anything that should be updated for v6.7.x. We made a lot of changes to CI on master, which would be risky to merge into v6.7.x, and I'm not aware of any CI changes we _need_ for this release?

**Comment by torkelo** [comment]
Good was just double-checking :)

**Comment by aknuds1** [comment]
I'll look over the PR now :)

**Comment by aknuds1** [comment]
#22753 hasn't been cherrypicked and it has milestone 6.7.2, is this intentional @torkelo?

**Comment by aknuds1** [comment]
#22754 was cherrypicked even though it has milestone 7.0. Shall we change its milestone to 6.7.2?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/22753 should be included, need to cherrypick that as well (was merged late yesterday). 

https://github.com/grafana/grafana/pull/22754 looks like a mistake, should not have the cherrypick needed label.

**Comment by aknuds1** [comment]
I guess you will be including #22753 and removing #22754 then :)

**Comment by daniellee** [comment]
For some reason, this PR just makes me feel happy :wink:

**Comment by aknuds1** [comment]
@torkelo I see you fixed up the cherry-picks, can you update the PR description though to reflect the removed and added PRs?

**Review by aknuds1 — APPROVED** [review]
LGTM

**Pull request merged**
