### PR TITLE
Alerting: Fix authorisation to use namespace UIDs for scope

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

follow up of #74600 to address [this comment](https://github.com/grafana/grafana/pull/77076/files#r1465305324)

fetching rules [under specific folder](https://ephemeral1511182181231papagia.grafana-dev.net/api/ruler/grafana/api/v1/rules/bdariz01j93b4b) seems to works fine with the fix

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by IevaVasiljeva — COMMENTED** [review]
Nice! I think there's three more places where this change should be applied:
* https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/authorization.go#L35
* https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/authorization.go#L39
* https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/store/alert_rule.go#L581

Otherwise looks good, but let's wait for someone from the alerting team to review as well.

**Review by yuri-tceretian — APPROVED** [review]
LGTM

**Pull request merged**
