### PR TITLE
UI for disabling users

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This is PR which adds UI for disabling users (part of #11188). It's based on the extended API from #17305.
This is a draft, so let's discuss how the UI should look like.

Screenshot 2019-05-28 at 20 28 27

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
Changes regarding discussion with @dprokop 

Screenshot from 2019-05-31 10-50-44

Screenshot from 2019-05-31 10-51-03

**Comment by dprokop** [comment]
Alex, I think the label should be dimmed as well. What we could do here is also move the delete button to the user view to keep all the actions together. Then the actions in that view should be somehow separated, as now the deactivate button looks like it belongs to Organisations section.

**Comment by dprokop** [comment]
Feels like the dimmed row only might not be enough to indicate the user being not active. What about having two lists, one for active and one for non-active users?

**Comment by alexanderzobnin** [comment]
@dprokop I can do list sorted by enabled/disabled flag on the backend side

**Comment by torkelo** [comment]
yes, needs some text & icon or icon + tooltip to indicate disabled

**Comment by torkelo** [comment]
Any progress on this PR?

**Comment by alexanderzobnin** [comment]
@dprokop do you mean something like this?

Screenshot from 2019-06-18 16-23-02

**Comment by dprokop** [comment]
@alex this looks good. Is the "Deactivate" button dimmed on purpose? I think it should be regular danger button.

**Comment by alexanderzobnin** [comment]
@dprokop it's dimmed because for external users it's inactive (not possible to disable it). I can hide it if it's better. What's about an icon for disabled users in the user list?

**Comment by torkelo** [comment]
will need some tooltip to describe why you cannot disable the user in that case.

**Comment by alexanderzobnin** [comment]
Now it looks like

Screenshot from 2019-06-20 14-09-45

@torkelo could you explain this e little bit more?
>needs some text & icon or icon + tooltip to indicate disabled

**Comment by alexanderzobnin** [comment]
@torkelo @dprokop maybe we should put information about auth modules (LDAP, OAuth, etc) to the edit user page as well?

**Comment by torkelo** [comment]
That looks really bad, a tooltip on hover for the button instead?

, is there a reason why you can’t disable external users? Seems like a useful thing to be able to do.

**Comment by torkelo** [comment]
The spacing between form and buttons look wrong , are you using gf-form-group class?

**Comment by torkelo** [comment]
Yes, more info on this page would be good , auth mode, last login etc. maybe the delete action as well

**Comment by alexanderzobnin** [comment]
@torkelo 
>That looks really bad, a tooltip on hover for the button instead?

What do you mean? That's a tooltip on hover. Printscreen just removed mouse pointer.

>is there a reason why you can’t disable external users? Seems like a useful thing to be able to do.

It's by design and there's API restriction as well:
https://github.com/grafana/grafana/blob/57dadebbd8228ac451ea5c0bfb948ce891c9c131/pkg/api/admin_users.go#L118
The reason is that external users are managed outside Grafana. If you have LDAP sync enabled, disabled user can be re-enabled on the next sync.

**Comment by alexanderzobnin** [comment]
> The spacing between form and buttons look wrong , are you using gf-form-group class?

This is `gf-form-button-row` inside `gf-form-group`
```html
<form name="userForm" class="gf-form-group">
  <div class="gf-form-button-row">
     <button type="submit" class="btn btn-danger"
```

**Comment by torkelo** [comment]
Sorry did not see that it was a tooltip , looked like text above the buttons

**Comment by alexanderzobnin** [comment]
@torkelo should I work on this?
>needs some text & icon or icon + tooltip to indicate disabled

**Review by torkelo — APPROVED** [review]
The edit user page needs a redesign but will do that after the reactify user profile / edit user PR is merged

**Pull request merged**
