### PR TITLE
Histogram: auto-skip x tick labels to avoid overlap

### LINKED ISSUE #44614: histogram x-axis is too cramped
**What happened**:

I made a histogram out of some timeseries data (I believe it's all integers, representing seconds of duration). The bucket size is Auto (that's the default). I set the units to Seconds.

The bucket size and the width of the numbers and units on the X axis conspire to make the histogram hard to read:

Screen Shot 2022-01-28 at 1 56 22 PM

That screenshot is not even too bad. I've seen worse, where there's actual overlap between neighbors.

I can mess with the bucket size and get it in a reasonable shape, but it really depends on the current data. And anyway, the spacing issue should never happen, at least not on Auto - and even with a fixed bucket size the app should still figure out the best spacing between symbols.

**What you expected to happen**:

I expected Grafana to make reasonable choices about the bucket size and the spacing of the units on the X axis.

**How to reproduce it (as minimally and precisely as possible)**:

I think I've described it in good detail.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: MySQL
- OS Grafana is installed on: it's a Helm chart on Kubernetes somewhere
- User OS & Browser: Chrome on various OSs
- Grafana plugins: this is pretty much stock install
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #44614

before:

https://user-images.githubusercontent.com/43234/156112907-c4c3c9b9-6d87-401a-9e2d-8b611cacde95.mp4

after:

https://user-images.githubusercontent.com/43234/156112953-cd4df202-74f4-4914-a07e-5fe1be482271.mp4

### CODE REVIEW

**Comment by torkelo** [comment]
Can we use the same x axis formatting as we have for time series ? Seeing strange time formats with pm/am in the new heat map panel

**Comment by ryantxu** [comment]
> Can we use the same x axis formatting as we have for time series ? Seeing strange time formats with pm/am in the new heat map panel

You are mixing heatmap with histogram :)  I keep doing the same thing.  In histogram, the x axis is rarely time.  In heatmap it is often time!  and yes should match the timeseries time strategy

**Comment by torkelo** [comment]
lol, histogram != heatmap , yea yea, learning every day :facepalm:

**Review by ryantxu — APPROVED** [review]
LGTM -- I am not sure we need to backport to 8.3 though

**Comment by leeoniya** [comment]
> LGTM -- I am not sure we need to backport to 8.3 though

the issue was reported in 8.3.4, and the fix is simple enough to backport so 🤷.

**Pull request merged**
