### PR TITLE
fix panel repeat for cloudwatch

### PR DESCRIPTION
**Pull request by mtanda**

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo Sorry, I found one problem in CloudWatch data source.
It can't use Panel Repeat.
Please check.

**Comment by torkelo** [comment]
thanks! if you have time and want to help more, would love some info on templating in the Cloudwatch docs, https://github.com/grafana/grafana/blob/master/docs/sources/datasources/cloudwatch.md  it's just very bare bones right now (wanted to have some basic docs before release, but can be improved, and there is nothing about templating)

**Comment by mtanda** [comment]
Hi, I write docs about templating.
I'm not sure the docs is enough to understand who didn't use it.
Anyway, I explain basic usage about the queries.

https://github.com/grafana/grafana/pull/3085

**Comment by torkelo** [comment]
@mtanda great, thank you. It's better than nothing :)

**Pull request merged**
