### PR TITLE
Dockerfile: Bump Go and Alpine versions

### PR DESCRIPTION
**Pull request by hairyhenderson**
**What this PR does / why we need it**:

Go 1.17.0 and Alpine 3.14.2 are out-of-date and using these will trigger Docker image scans.

See https://golang.org/doc/devel/release#go1.17.minor for Go changes, and https://alpinelinux.org/posts/Alpine-3.14.3-released.html for Alpine changes.

**Which issue(s) this PR fixes**:

n/a

Fixes #

**Special notes for your reviewer**:

See conversation in [internal Slack](https://raintank-corp.slack.com/archives/C036J5B39/p1637262157469600)

Signed-off-by: Dave Henderson <dave.henderson@grafana.com>

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
LGTM, thanks @hairyhenderson!

**Review by leventebalogh — APPROVED** [review]
LGTM 👍

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by hairyhenderson** [comment]
@dsotirakis @leventebalogh @mckn can one of you merge this? I'm probably not in the right team 😉

**Comment by daniellee** [comment]
@hairyhenderson do you need more help with this? Looks like the backport PR failed and needs to be done manually.

**Comment by dsotirakis** [comment]
Can do @hairyhenderson, @daniellee

**Comment by hairyhenderson** [comment]
thanks @dsotirakis 🙇‍♂️

**Comment by marefr** [comment]
Seems like we forgot to update grabpl so alpine 3.14.2 is still being used

**Pull request merged**
