### PR TITLE
Database: Order results in UserSearch by username/email

### LINKED ISSUE #22348: Users list on server admin page is not alphabetically ordered
**What happened**:
Users list is not alphabetically ordered by username.

**What you expected to happen**:
Users list should be alphabetically ordered by username

**How to reproduce it (as minimally and precisely as possible)**:
Goto:
Server Admin->Users

**Environment**:
- Grafana version: Latest
- Data source type & version: latest
- OS Grafana is installed on: MacOS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Ensure that the user list on the admin page is ordered by username first and email address second.

Also adding an index on (user.login, user.email) for speedy ordering.

I've checked with MariaDB (MySQL compatible) and it looks as if the new index gets used:

```
MariaDB [grafana]> explain select id, login,email from user order by login ASC, email ASC\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: user
         type: index
possible_keys: NULL
          key: IDX_user_login_email
      key_len: 1524
          ref: NULL
         rows: 1
        Extra: Using index
1 row in set (0.000 sec)
```

**Which issue(s) this PR fixes**:
Fixes #22348.

### CODE REVIEW

**Comment by kylebrandt** [comment]
Have you done a describe on say at least mysql to make sure we not changing the performance characteristics (e.g. index needed?).

**Comment by aknuds1** [comment]
@kylebrandt Good point! I included you as a reviewer for a reason ;)

**Comment by aknuds1** [comment]
@kylebrandt Index is added now.

**Review by kylebrandt — APPROVED** [review]

**Review by marefr — APPROVED** [review]
Great. LGTM

**Pull request merged**
