### PR TITLE
Default AWS Region selection from dropdown

### PR DESCRIPTION
**Pull request by utkarshcmu**

### CODE REVIEW

**Comment by mtanda** [comment]
Hi, utkarshcmu.

The field is optional field, it is used for default value when creating panel first time.

Please see this line.
https://github.com/grafana/grafana/blob/d7ee7cb88fa1c65e99ae4b2c3a14da9d33374023/public/app/plugins/datasource/cloudwatch/query_ctrl.js#L19

Why do you want to change it?

**Comment by utkarshcmu** [comment]
@mtanda, I checked out the code which you sent above and agree that this field should not be "required". Will remove the "required" check. 

But I think there needs to be some kind of validation that whether the user is entering valid regions and not just anything. See #3109 for reference. Will add some other validation which makes sure that a valid region is entered if anyone tries to enter text into the datasource config field.

**Comment by mtanda** [comment]
I agree with you, we need to improve the field edit UI.

I think auto-complete support is good options for this problem.

I already think about the possibility.
https://github.com/grafana/grafana/pull/2445#issuecomment-133825742
https://github.com/grafana/grafana/pull/2445#issuecomment-134036809

Due to my poor understanding about AngularJS, I think auto-complete support is difficult at that time.
Currently, I think auto-complete support is possible by adding directive for the region field.

**Comment by utkarshcmu** [comment]
I am almost done with putting a select box as mentioned in https://github.com/grafana/grafana/pull/2445#issuecomment-134036809 for the Default Region config. Will be committing the code in a couple of hours. :)

**Comment by utkarshcmu** [comment]
This is not complete yet, missing an API. An API to returning list of regions even if the datasource does not have an id.

**Comment by mtanda** [comment]
Thanks!
Looks very nice :+1: 

> An API to returning list of regions even if the datasource does not have an id.

It's hard problem.
Without id, the grafana backend can't distinguish what type of datasource.
Moving the "__GetRegions" code to frontend, is only way, I think.

**Comment by mtanda** [comment]
@torkelo How do you think?

**Comment by utkarshcmu** [comment]
Another option instead of moving "GetRegions" to frontend is to add a new API which takes the type of the datasource and use the backend/proxy to query any data from it based on the datasource.

**Comment by utkarshcmu** [comment]
This PR is going to remove the confusion of typing region or the region names completely and all the issues associated with them. Also, this will validate the AWS regions automatically. Because the user cannot type any garbage values in the region field now (See #3129). He can only select the available regions in the specified list. :)

@mtanda - Need a quick review.

@torkelo - Ready for review/merge

**Comment by mtanda** [comment]
@utkarshcmu sorry for late response.
looks good for me. thanks for contribution :)

**Pull request merged**
