### PR TITLE
Table panel: add option for preserving text formatting

### LINKED ISSUE #6617: [Feat Req Table Panel]: Column style that preserves formatting/indentation (like pre tag)
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 
3.0.1
- What datasource are you using? 
Elasticsearch
- What OS are you running grafana on? 
Ubuntu 14.04
- What did you do? 
Visualize logs with stacktraces
- What was the expected result?
Stacktrace message render with indents and hyphenations
- What happened instead?
Stacktrace message render in one line

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR fixes #6617

### CODE REVIEW

**Comment by torkelo** [comment]
The code looks great. 

The options don't look very good, not aligned. 
image

**Comment by alexanderzobnin** [comment]
@torkelo ok, fixed

**Comment by daniellee** [comment]
@alexanderzobnin Torkel had already approved the code and the frontend changes look good so merging to master.

**Comment by alexanderzobnin** [comment]
@daniellee great

**Pull request merged**
