### PR TITLE
Migrate PR pipeline

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Migrate PR CircleCI pipeline to the "build-pipeline" workflow.

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
It would be nice to think about what optimizations we can do, feels like we do not need to build for all platforms and packages , but maybe having them as close to identical is also an advantage

**Review by marefr — APPROVED** [review]
LGTM

Agree with Torkel regarding optimizations and/or throwing more resources on certain steps to speed it up - right now seems like every step uses Docker Medium 2 CPU / 4 GB RAM.

Maybe consider running codespell step before build-docs-website?

**Comment by aknuds1** [comment]
> It would be nice to think about what optimizations we can do, feels like we do not need to build for all platforms and packages , but maybe having them as close to identical is also an advantage

@torkelo Are there any particular optimizations you have in mind? I tried to mirror the original PR pipeline by not building the ARM architectures at least.

**Comment by aknuds1** [comment]
> LGTM
> 
> Agree with Torkel regarding optimizations and/or throwing more resources on certain steps to speed it up - right now seems like every step uses Docker Medium 2 CPU / 4 GB RAM.
> 
> Maybe consider running codespell step before build-docs-website?

@marefr I can modify the config to run codespell before build-docs-website, sure.

**Comment by bergquist** [comment]
Do we have an issue for such a discussion?
Id prefer if PR's dont get stuck on discussions like this :)

**Review by torkelo — APPROVED** [review]
Let's go with this and think about optimizations later, could not find any great optimizations, possibly skipping building ubuntu docker images in PRs and only do the musl one.

**Pull request merged**
