### PR TITLE
Correcting abbreviation

### PR DESCRIPTION
**Pull request by amalkurup89**
**What this PR does / why we need it**: Documentation fix

**Which issue(s) this PR fixes**: Correcting abbreviation

### CODE REVIEW

**Comment by amalkurup89** [comment]
@oddlittlebird Can you please review & merge accordingly

**Comment by amalkurup89** [comment]
@oddlittlebird Gentle reminder, if in case you missed this

**Comment by amalkurup89** [comment]
@oddlittlebird Gentle reminder, if in case you missed this

**Review by oddlittlebird — APPROVED** [review]
LGTM. Thanks for contributing to Grafana!

**Pull request merged**
