### PR TITLE
Stats: Correct the number of arguments for SQL call

### PR DESCRIPTION
**Pull request by sakjur**
**What this PR does / why we need it**:
Adds a missing integration test + fixes the admin stats page.

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Review by bergquist — APPROVED** [review]
:+1:

**Comment by bergquist** [comment]
Dupe of https://github.com/grafana/grafana/pull/27181 but this PR have a test.

**Comment by sakjur** [comment]
@bergquist Yes, the test already exists (it's why the enterprise build fails), but it's not marked as an integration test.

**Pull request merged**
