### PR TITLE
PublicDashboards: Email validation on submit

### LINKED ISSUE #64219: Task: improve email validation UI
Improve **when** the error is shown in email input for email feature

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It validates the email when the user clicks on submit button
Enteprise PR: https://github.com/grafana/grafana-enterprise/pull/4754

**Which issue(s) does this PR fix?**:

Fixes [#64219](https://github.com/grafana/grafana/issues/64219)

### CODE REVIEW

**Review by evictorero — APPROVED** [review]

**Comment by owensmallwood** [comment]
Why don't we want to also validate the email on the frontend?

**Comment by juanicabanas** [comment]
> Why don't we want to also validate the email on the frontend?

@owensmallwood we're validating it, but after the user clicks on "Invite" button. Otherwise, once he starts writing the email, he will receive an error message which doesn't look good based on UX and based on how Grafana inputs work.
The request won't be fired until it matches the regex

**Comment by owensmallwood** [comment]
Screenshots would be nice here. Kind of unclear for the before vs after.

**Review by owensmallwood — APPROVED** [review]
Tried it out, works as expected 🚀 🔥

**Pull request merged**
