### PR TITLE
Bump typescript and jest

### PR DESCRIPTION
**Pull request by jschill**
**What this PR does / why we need it**:
typescript 3.4 (in root and grafana/ui)
jest 24.6
babel-jest 24.6

Needed to fix some typings to go under the "Typescript errors limit".

### CODE REVIEW

**Comment by dprokop** [comment]
Cool stuff

**Comment by dprokop** [comment]
Can u pls bump ts in grafana/ui as well to keep versions in sync?

**Comment by jschill** [comment]
@dprokop 👍 I missed that one the last time as well by the looks of the version.

**Comment by torkelo** [comment]
tested this, seems to work  :)

**Pull request merged**
