### PR TITLE
Breadcrumbs: Improve responsiveness

### PR DESCRIPTION
**Pull request by torkelo**
Problems

* Breadcrumbs only use 50% of the width of the screen, so for app plugins (and other views) that have deep hierarchy the breadcrumbs get ellipsed very early when there is still lots of space remaining. 
* The ellipsis happens evenly on all breadcrumbs, instead of prioritizing the more recent breadcrumbs 
* Dashboard name is hidden on mobile (the last breadcrumb) 

Fixes
* Allow breadcrumbs to take more than 50% 
* Improve media queries 
* Make later breadcrumbs have a bit of priority over earlier ones. 
* Show dashboard title on mobile. Now always the last 2 breadcrumbs are shown. But the last is given more space/priority
* Add titles to breadcrumb so you can see full title even when ellipsified   

[Metrics---api-usage-dashboard-dashboardID-views-recent---HTTP-handlers---Grafana-Monitoring---Scenes---Dashboards---Grafana.webm](https://user-images.githubusercontent.com/10999/236611222-a1ba839a-afe7-4a65-a9c9-1cbddd925e2c.webm)

Dashboard on mobile now shows dashboard name: 
image

### CODE REVIEW

**Comment by torkelo** [comment]
Long term we need an even better system I think that collapses breadcrumbs into a sort of pulldown menu.

**Comment by amy-super** [comment]
@torkelo I had worked up the logic to solve the same problem in #62266 - we should look at these side-by-side and decide how to reconcile. We will definitely need to handle this well with the advent of nested folders, where the breadcrumb trail will get quite long.

**Comment by torkelo** [comment]
@amy-super I think I have come as close as possible I can to what you describe in https://github.com/grafana/grafana/issues/62266  using css 

Doing more complex things like collapsing multiple breadcrumbs into a single "..." (only when needed) would require a more complex solution, which I think we should do but not sure we have time for G10.  

thoughts @ashharrison90 ?

**Comment by torkelo** [comment]
can give a demo and we can discuss ideas for how to preceed, what to do for Grafana 10.0 and what to do for Grafana 10.1

**Comment by amy-super** [comment]
I'm fine holding off on any more complex work until after G10 - this mostly will come up for nested dashboard folders, which are still behind the feature toggle. We have a lot of UI refinement to do between 10 and 10.1.

**Review by ashharrison90 — COMMENTED** [review]
behaviour looks mostly good. if you have a long dashboard name it can overlap which doesn't look great:

image

can we fix that before merging? 🤔 

agree we shouldn't really do any more until we actually look at breadcrumbs properly post g10

**Comment by ashharrison90** [comment]
@torkelo i can repro pretty easily at mobile widths 
image

given we know we're going to do something completely different to properly handle this, wdyt about simplifying the logic slightly?
- keep title (this is very much needed)
- keep showing last 2 breadcrumbs
- just adjust the `maxWidth` of the breadcrumbs based on a media query?

https://github.com/grafana/grafana/assets/20999846/e5d4b5fe-9ade-4f7a-98ef-0c9faa45abae

changes would look something like https://github.com/grafana/grafana/compare/ash/responsive-breadcrumbs?expand=1

**Comment by torkelo** [comment]
@ashharrison90 but the screenshot you showed looks fine? better than now. Not sure I see what the problem is
image

**Comment by ashharrison90** [comment]
@torkelo share icon/overflow menu heavily overlapping

**Comment by torkelo** [comment]
the video you showed does not work well for scenes, loose to many bredcrumbs too early. We need 3 breadcumbs for as long as possible to go back when we have pages with tabs

**Comment by torkelo** [comment]
@ashharrison90 but that is a problem with the actions not collapsing properly (a bigger problem for a public dashboard)

**Comment by torkelo** [comment]
@ashharrison90 pushed an update that reduces the min-width a bit on mobile to give more space to the actions 
image

**Comment by ashharrison90** [comment]
@torkelo i know these are edge cases, but: 
image
image

**Comment by torkelo** [comment]
@ashharrison90 it's strange, not seeing that with super long titles 
image

**Comment by torkelo** [comment]
@ashharrison90 the breadcrumbs element should not extend 50% , maybe something different on osx? can you try adding a max-width: 50% ? 
image

**Comment by ashharrison90** [comment]
@torkelo i use this dashboard for testing:
```json
{
  "__inputs": [],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.1.0-pre"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "uid": "VdqTxaXnk",
  "version": 7,
  "weekStart": ""
}
```

obviously not representative of what anyone would actually make 😅 

the changes set `min-width` instead of `max-width`, is that intentional? https://github.com/grafana/grafana/pull/67955/files#diff-2e249048bad62bf7c3d98f4b22c6dc84faf26ecf9220ea450cc07ddbafc31cceR81

with `max-width` it seems to be working better 👌

**Comment by torkelo** [comment]
@ashharrison90 sadly max-width makes it not use space when it is available 
image

**Comment by torkelo** [comment]
@ashharrison90 this is what it looks like for me on my actual iphone 12

**Comment by torkelo** [comment]
@ashharrison90 tested with your dashboard name that was 445 characters long and I can replicate the problem then but don't think that is realistic :) 

After testing it only happens when title is more than 100 characters long which is pretty extreme.  

So a title like this works fine: 
`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem3 3 3 33 3 asdasd a44 44`

**Review by ashharrison90 — APPROVED** [review]
@torkelo sorry for the delay, been in meetings 😬 

completely agree that is unrealistic, but it is highlighting a problem that this behaves differently based on **overall** length of the breadcrumbs which i don't think is a good thing. with nested folders/scenes it feels pretty possible to have something that big in multiple parts.

but we can go with this for now 👍 scenes/nested folders aren't live yet so we can cross that bridge when we come to it 😄

**Pull request merged**
