### PR TITLE
3514 per panel refresh round2 fight

### PR DESCRIPTION
**Pull request by gbrian**
**What this PR does / why we need it**:
Implement feature: per panel/graph refresh https://github.com/grafana/grafana/issues/3514

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure when I can find time to review this, but hopefully in the next few weeks.

**Comment by kl4n4** [comment]
@torkelo any updates on that? It would be great to have this feature integrated

**Comment by torkelo** [comment]
A lot of the panel & query architecture has changed and is changing now. So want to hold off on this a few more months. 

Worth revisiting after after new year.

**Comment by szerwi** [comment]
@torkelo any updates about this feature?

**Comment by Zangoran** [comment]
@torkelo Any update?

**Comment by NotProgramer** [comment]
@torkelo Something?

**Comment by scaarup** [comment]
It's been almost 2 years now - come on.

**Comment by nicolaerosia** [comment]
@torkelo you haven't specified which new year, is it 2021?

**Pull request closed without merging**
