### PR TITLE
chore: Move canvas and geo feature folders into visualization parent directory (refactor part 2 of 2)

### PR DESCRIPTION
**Pull request by nmarrs**
Moving canvas and geo feature folders inside of the visualization feature folder. In future visualization folder can also be a catch all for things like legend etc. - basically for things that we want in Grafana core and not in @grafana/ui package.

[Part 1 of refactor](https://github.com/grafana/grafana/pull/68863)

### CODE REVIEW

**Comment by ryantxu** [comment]
why are these better out of the panel?  I don't think they are worse, but they all have a 1:1 mapping for things that live in a single panel, so I'm not sure there is a huge advantage.  

The geo bits have some things that live in transformations -- but arguably that should not live in a "visualizations" subdirectory

**Comment by nmarrs** [comment]
> why are these better out of the panel? I don't think they are worse, but they all have a 1:1 mapping for things that live in a single panel, so I'm not sure there is a huge advantage.
> 
> The geo bits have some things that live in transformations -- but arguably that should not live in a "visualizations" subdirectory

That's a good point - it may make more sense that these directories are moved into the canvas panel / geomap panel directories instead given the direct relation. The other route here I guess is just `do nothing` and leave it as is 🤷‍♂️ thoughts? 

For the geo bits living in transformations are you referring to the `spatial` and `lookupGazetteer`  transforms?

**Comment by ryantxu** [comment]
> For the geo bits living in transformations are you referring to the spatial and lookupGazetteer transforms?

Yes -- the parts that are really about handling spatial data, but not the display aspects

**Comment by nmarrs** [comment]
Decided to not move forward with refactoring canvas / geo feature folders for the time being. In the future it may make sense to move them into their respective panel folders.

**Pull request closed without merging**
