### PR TITLE
NodeGraph: Allow to set node radius in dataframe

### LINKED ISSUE #74966: NodeGraph: Allow to set node radius in dataframe
**Why is this needed**:

Currently admin is unable to set different sizes for nodes in a graph.

**What would you like to be added**:

Allow to have an optional nodeRadius column in nodes dataframe to control node sizes.

**Who is this feature for?**

Admin users managing node graph

### PR DESCRIPTION
**Pull request by piggito**
**What is this feature?**

Allow to have an optional `nodeRadius` column in nodes dataframe to control node sizes.

**Why do we need this feature?**

Currently all nodes have a fixed radius of 40 and different node radius could improve visualization.

**Who is this feature for?**

Admin users managing node graph

**Which issue(s) does this PR fix?**:

Fixes #74966 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by imatwawana — APPROVED** [review]
Thanks for the contribution! The update to the docs looks good. This just needs technical review now.

**Comment by aocenas** [comment]
Hey @piggito, thanks for the PR, this look like a good feature and the code looks good so far but I am seeing some compilation issues. Are you able to fix those so we can test this?

**Comment by piggito** [comment]
hi @aocenas , thank you for your feedback.
I fixed the failing tests please can you recheck the PR?

**Comment by aocenas** [comment]
Hey @piggito thanks for fixing those. Trying to test it now but when I try our test data source there are bunch of errors where it seems the edge is not computed correctly. I assume there is some issue with the node radius not being defaulted somewhere and thus creating NaNs. The node radius should be optional and so it should still work the same if it's not passed in the data frame.

On main:
Screenshot 2023-09-22 at 14 58 56

On this branch:
Screenshot 2023-09-22 at 15 03 17

Error:
Screenshot 2023-09-22 at 15 06 17

**Comment by piggito** [comment]
@aocenas I fixed the NaN errors, please can you have another look at it?

**Comment by aocenas** [comment]
@piggito looks good now. Thank you very much for the contribution 👍

**Pull request merged**
