### PR TITLE
Chore: Upgrades rxjs to 7.3.0

### LINKED ISSUE #36374: Upgrade RxJs to latest
We're falling behind with one of our biggest dependencies so I think we should put in some time to upgrade our RxJs version:

What's new article:
https://medium.com/volosoft/whats-new-in-rxjs-7-a11cc564c6c0

- [x] Main package
- [x] grafana-data
- [x] Replace all instances or `toPromise()` and other deprecated operators/functions
- [ ] ~~other package?~~

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR upgrades RxJs to 7.3.0. Read about the most important changes here: https://medium.com/volosoft/whats-new-in-rxjs-7-a11cc564c6c0

I replaced all instances of [`toPromise`](https://github.com/ReactiveX/rxjs/blob/b1af18888d7903c38cc9f0996e5e31e974ee6e91/src/internal/Observable.ts#L451-L468) with [`lastValueFrom`](https://github.com/ReactiveX/rxjs/blob/b1af18888d7903c38cc9f0996e5e31e974ee6e91/src/internal/lastValueFrom.ts#L11-L54).

As this PR touches on a lot of different central places, and data sources I'd appreciate help in testing those by their respective code owners. Thank you.

**Some transpilation errors identified after upgrade that need special review:**

- Mock setup in a Cloudwatch test here https://github.com/grafana/grafana/commit/6685ff056d3dc63902905ce7f04f6ea97660738d. I removed it, as I couldn't find that we used `delay` anywhere in CloudWatch. @kaydelaney 
- Chaining of subscription adds PieChartPanel, I just changed it to call them sequentially: https://github.com/grafana/grafana/commit/73804790feba6662603eaddf383f6ab0a87f5b49 @oscarkilhed @ryantxu 
- Fixed transpile error in ElasticSearch, I added the options property for `generate` and changed the check in `skipWhile`: https://github.com/grafana/grafana/commit/375ce65170b96e3d42eab9b75c43792572288b0d @Elfo404 

**Which issue(s) this PR fixes**:
Fixes #36374

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hugohaggmark** [comment]
RxJs upgrade causes `@grafana/api-extractor` to report 95 new warnings. I think it's because of RxJs 7.3.0 is targeting TypeScript > 4.0. I need help to update `@grafana/api-extractor` and `@grafana/api-documenter` to later versions of TypeScript.

@mckn when you get back from PTO maybe we can do this together? Or maybe @jackw or @dprokop know the details about the extractor/documentor?

**Comment by ying-jeanne** [comment]
Tested with SQLs, that owned by backend team, seems working fine.

**Review by ying-jeanne — APPROVED** [review]
LGTM, tested the SQLs which is currently owned by backend team, works fine.

**Comment by jackw** [comment]
I'm afraid I don't know about the extractor or documentor @hugohaggmark but I'm happy to pair up with you and figure it out together if you like!

**Review by Elfo404 — APPROVED** [review]
LGTM, tested Elasticsearch and seems to work as expected 🚀

**Comment by hugohaggmark** [comment]
I updated the api-extractor to upstream and run the commands locally using `yarn link`. All of the RxJs errors disappeared, but the new updated api-extractor found a lot more errors (of course). This might be because of me not knowing enough about the api extractor to make a good upgrade to upstream, but it might also be because the new api-extractor finds more.

So I identified the following paths to get this PR merged:
- Update api-extractor and raise the warnings count limit in https://github.com/grafana/grafana/blob/f6c9c196ba798325a2cef935bd20857f34cbc97a/scripts/ci-reference-docs-lint.sh#L32 
- Update api-extractor and fix 100+ new errors
- Filter the warnings in https://github.com/grafana/grafana/blob/f6c9c196ba798325a2cef935bd20857f34cbc97a/scripts/ci-reference-docs-lint.sh#L31 to only include api-extractor warnings and ignore TS transpile errors.

As the api-extractor is a completely unknown domain for me and @mckn is on PTO I went with the last alternative, i.e. the script `ci-reference-docs-lint.sh` will only count api-extractor warnings and ignore any TS warnings. As soon as Marcus is back from PTO we'll come up with a better solution moving forward.

Suggestions, feedback?

**Review by oscarkilhed — APPROVED** [review]
:heavy_check_mark: Pie Chart changes :tada:

**Review by domasx2 — APPROVED** [review]
tested alerting parts, lgtm!

**Review by jackw — APPROVED** [review]
LGTM! 🚀 

Amazing work on this @hugohaggmark. I think the approach you've taken regarding the api-extractor is fine until Marcus is back.

My only remaining questions are if we need to bump `rxjs-spy` (or remove it if it's not used) [here](https://github.com/grafana/grafana/blob/main/package.json#L198) and if we need to tackle [this rxjs resolution](https://github.com/grafana/grafana-starter-datasource-backend/blob/main/package.json#L22-L24) in the datasource-backend starter template?

**Review by ifrost — APPROVED** [review]
Graphite looks good 😎  👍

**Comment by hugohaggmark** [comment]
> LGTM! 🚀
> 
> Amazing work on this @hugohaggmark. I think the approach you've taken regarding the api-extractor is fine until Marcus is back.
> 
> My only remaining questions are if we need to bump `rxjs-spy` (or remove it if it's not used) [here](https://github.com/grafana/grafana/blob/main/package.json#L198) and if we need to tackle [this rxjs resolution](https://github.com/grafana/grafana-starter-datasource-backend/blob/main/package.json#L22-L24) in the datasource-backend starter template?

Great catch @jackw! I bumped the rxjs-spy version and opened a [PR](https://github.com/grafana/grafana-starter-datasource-backend/pull/30) for the  datasource-backend starter template.

**Review by sunker — APPROVED** [review]
Tested CloudWatch metrics, CloudMonitoring and Azure Monitor and it works as expected. Great work @hugohaggmark! 

@aocenas can you take a peek at CloudWatch logs?

**Review by jackw — APPROVED** [review]
LGTM! 👍

**Review by ryantxu — APPROVED** [review]
works with streaming datasources :taco:

**Review by aocenas — APPROVED** [review]
Also seems to work with CW logs

**Pull request merged**
