### PR TITLE
PanelChrome: New Panel Header design Feature Flag

### LINKED ISSUE #56396: Create frontend feature flag `newPanelHeader`
Part of #56163 

New Panel Header design will be under feature flag `newPanelHeader`.

### PR DESCRIPTION
**Pull request by polibb**
**What this PR does / why we need it**:

Adds feature flag `newPanelHeader`.

**Which issue(s) this PR fixes**:

Fixes #56396 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
might be better to name it newPanelChrome as the feature will replace  the panel chrome, header and menu

**Comment by polibb** [comment]
> might be better to name it newPanelChrome as the feature will replace the panel chrome, header and menu

Yes, good point. It's just that "PanelChrome" doesn't mean anything to anyone not familiar with the name of the component itself. From user's point of view maybe something like `newPanelDesign` is better?

**Comment by polibb** [comment]
> > might be better to name it newPanelChrome as the feature will replace the panel chrome, header and menu
> 
> Yes, good point. It's just that "PanelChrome" doesn't mean anything to anyone not familiar with the name of the component itself. From user's point of view maybe something like `newPanelDesign` is better?

I changed the flag's name to `newPanelChromeUI` in regards to the new design being implemented in `grafana/ui` and because the flag will also be used by PMs, designers, and beta users who may not know about the naming of PanelChrome, which is indeed the central component being changed.

**Review by axelavargas — APPROVED** [review]
Looks great 🚀 , I also agree with the new feature flag name 🙌🏾

**Pull request merged**
