### PR TITLE
Loki: Always display log context toggle

### LINKED ISSUE #66132: Loki: Log context is not offered with non-equal line filters
In Loki, we offer log context toggle only is user selects `line contains string` and `line contains regex match` filter. It is not offered for `line does not contain string/regex` filter. We should fix that.

image

### PR DESCRIPTION
**Pull request by matyax**
The changes in this PR are to always offer Logs Context, independent of the current query.

The reason for this is that log context is created from all labels defining the stream for the selected log line. And it has basically nothing to do with filter being present/not being present. I think that showing log context only when filter is present is actually more confusing as it makes log context associated with line filters, when it should be associated with log line labels/streams.

~This PR adds support for offering logs context for logs lines generated using negative filters.~

~Since deciding to show or not show the logs context toggle depends on the presence of search words https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/datasource.ts#L821 ; and search words were based on the presence of `PipeExact` or `PipeMatch` nodes, the code has been changed to also look for `Neq` and `Nre` nodes. When these are present, the search words are prepended with `-`. For example, `!= word` is processed as `-word`.~

~The other alternative was adding a new function to look for `Neq` and `Nre` in the query, and add a new `custom` property returned from the `backendResultTransformer` as, for example, `custom.hasNegativeExpressions` https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/backendResultTransformer.ts#L4 ; and then updating `logsSeriesToLogsModels` and the `LogsModel` type, to pick up this property and return it for every row. https://github.com/grafana/grafana/blob/main/public/app/core/logsModel.ts#L426~

~I decided for the alternative I sent in this PR because it was simpler and didn't require more parsing, new properties, or type updates.~

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/66132

**Special notes for your reviewer:**

~Returning negative expressions as negative search words didn't seem to have any visible harmful effect, and allowed us to offer logs context for these queries. Nothing should be broken after these changes.~

~To test, write any query with negative expressions and see the logs context toggle for each row:~

Now we will always display the button for logs.

### CODE REVIEW

**Comment by ivanahuckova** [comment]
I think that to fix https://github.com/grafana/grafana/issues/66132, we should consider always showing log context. And the more I am thinking about it, the more I think it make sense to always show log context toggle.

The reason for this is that log context is created from all labels defining the stream for the selected log line. And it has basically nothing to do with filter being present/not being present. I think that showing log context only when filter is present is actually more confusing as it makes log context associated with line filters, when it should be associated with log line labels/streams.

So before moving with this PR that introduces negative searchWords (that still acts in Highlight component like normal searchWords because `-` has no effect on showing/not showing highlighted text), I would consider just showing context all the time.

**Review by ivanahuckova — COMMENTED** [review]
I think that to fix https://github.com/grafana/grafana/issues/66132, we should consider always showing log context. And the more I am thinking about it, the more I think it make sense to always show log context toggle.

The reason for this is that log context is created from all labels defining the stream for the selected log line. And it has basically nothing to do with filter being present/not being present. I think that showing log context only when filter is present is actually more confusing as it makes log context associated with line filters, when it should be associated with log line labels/streams.

So before moving with this PR that introduces negative searchWords (that still acts in Highlight component like normal searchWords because `-` has no effect on showing/not showing highlighted text), I would consider just showing context all the time. 

What do you think @grafana/observability-logs?

**Comment by svennergr** [comment]
> What do you think https://github.com/orgs/grafana/teams/observability-logs?

Makes sense to me. Should we do it before G10?

**Comment by matyax** [comment]
Thank you @ivanahuckova. Always showing the context button makes sense to me as well 👍 

I can do that in this PR if we all agree.

**Comment by gabor** [comment]
> What do you think @grafana/observability-logs?

:+1:

**Comment by matyax** [comment]
@svennergr One thing I noticed after this is that it seems to be ignoring the log line immediately above the one I'm expanding:

imagen

imagen

**Review by svennergr — APPROVED** [review]
LGTM. 

I am wondering if we should mark `showContextToggle` here https://github.com/grafana/grafana/blob/0457291ac2cfc987985c805e0f03282861c695e9/packages/grafana-data/src/types/logs.ts deprecated and remove that functionality at one point completely.

**Comment by matyax** [comment]
I think we should, @svennergr , as every `showContextToggle` I see is just returning true. https://github.com/grafana/grafana/issues/66819

**Pull request merged**
