### PR TITLE
IAM: Server Admin now implies Org Admin Privileges by default

### PR DESCRIPTION
**Pull request by aarongodin**
**What is this feature?**

Server Admins can become org members and assign the Admin basic role to themselves for any organization (due to their implicit permissions in the global org through the special `Server Admin` role). We want to allow a Grafana Server Admin to be authorized as though they are both a member of the given org and that they have the permissions of the Admin basic role for the org, even if they are not assigned org membership.

**Note** - this PR focuses on only adding the authorization checks. This does change the frontend but that would likely be done as a second PR.

**Why do we need this feature?**

Increases the ability for org admins to manage an entire Grafana instance without requiring them to be listed as a member of the org (can be undesired by some Grafana Server Admins).

Server Admins implicitly have these permissions anyway since they have global permissions to manage org memberships and role assignments.

**Who is this feature for?**

Grafana Server Admins

## References

https://github.com/grafana/grafana/issues/91339
https://github.com/grafana/grafana/issues/92792
https://github.com/grafana/grafana/issues/88924

### CODE REVIEW

**Review by IevaVasiljeva — COMMENTED** [review]
Nice! The approach looks good to me!

As I said, it doesn't feel great that the role in the DB will not necessarily match user's role. But we have been doing this in the same hacky way for the global org already, so I think it's fine.

Let me know when this is ready for manual testing and I'll give it a go :)

**Comment by eleijonmarck** [comment]
I love ittttttttttt! 💘 

> As I said, it doesn't feel great that the role in the DB will not necessarily match user's role. But we have been doing this in the same hacky way for the global org already, so I think it's fine.


my two cents is that we should enforce "Admin" role on each org if the user becomes the ServerAdmin. This is more intuitive and make reasoning easier and the overall concept of a ServerAdmin easier to think about.

**Review by IevaVasiljeva — COMMENTED** [review]
I've tested this with several scenarios, and it mostly works, but I think there are cases where we don't correctly apply org admin role.

What worked:
* having admin rights on an org where the sever admin user had a lower role (eg, I could create teams/folders etc in an org where the user was Viewer + Server Admin);
* having admin rights in an org that a server admin user doesn't belong to (same tests as above);
* adding another user to an org where sever admin has low rights or that the server admin doesn't belong to (eg, granting another user Admin rights in an org that server admin is a Viewer in).

What didn't work:
* some scenarios where we call [GetOrgRole](https://github.com/grafana/grafana/blob/2e60f28044f39c6f54353063e0650a075058592d/pkg/services/user/identity.go#L253) instead of `GetOrgRoles`:
   * when checking if a server admin user can create a service account with Admin role in an org where the server admin is not an Admin;
   * accessing plugin routes...

I think some options for fixing the remaining cases are:
1. also change the `GetOrgRole` logic similarly as `GetOrgRoles` has been changed;
1. patch the current use cases of `GetOrgRole` to pass if the user has Server Admin rights (not future proof);
1. refactor the places where `GetOrgRole` is used to call [HasRole](https://github.com/grafana/grafana/blob/21d26de4d8e97f363866a9efeff5bc8221af08f0/pkg/services/authn/identity.go#L245-L248) instead (but this might be a lot of work, as requires moving from `SignedInUser` to `Identity`);
1. move the logic for setting org Admin role if user is a Server Admin higher up (where we authenticate the user; this might also be a lot of work, as we need to cover all auth providers).

If you decide to go with one of the options 1 - 3, I'm happy for that to be covered in a separate PR so that this one doesn't grow too huge.

**Comment by aarongodin** [comment]
Closing this one, but will leave the branch intact.

**Pull request closed without merging**
