### PR TITLE
Chore: Add disabled transformations icons

### PR DESCRIPTION
**Pull request by codeincarnate**
This is a straightforward PR which adds disabled icons for transformations. We currently have more disabled icons than we have transformations that are currently able to utilize them as we're still building out applicability tests for them.

This PR adds the remaining icons created by UX for this purpose so that they don't have to be added each time we decide to tackle this for a particular transformation.

### CODE REVIEW

**Comment by baldm0mma** [comment]
> hmm, do we need new icons?
> 
> can we just get away with desaturating them with css filters?
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/filter
> 
> e.g. grayscale + opacity
> 
> image

This certainly would seem easier and lighter weight. I wonder of the design team cares in either direction?

**Comment by codeincarnate** [comment]
We could do that potentially, though not sure what exact process was used to make these icons. I'll ask @catherineymgui to see what she thinks 😄

**Comment by catherineymgui** [comment]
Ooh I like this approach. Maybe like 20-30% opacity or so?

**Comment by codeincarnate** [comment]
Closed this in lieu of https://github.com/grafana/grafana/pull/85566

**Pull request closed without merging**
