### PR TITLE
Add glossary

### LINKED ISSUE #19133: Add glossary.md
The glossary topic should be included in the Getting Started section. This topic will help both new users and contributors so that everyone is using words the same way and knows what they mean.

Starting word suggestions:
- Grafana
- Graph
- Panel
- Grafana CLI
- Go (http://golang.org/)
- Loki live streaming
- Loki context queries
- Elasticsearch
- Alias
- Target
- Query
- Time Series (including general concept vs. what’s in the JSON returned in a query, which has multiple series)
- Org
- Admin (special user, has global rights)
- Plugin
- Data Source
- App
- Pretty much everything on the menu
- Variable
- grafana-server
- session
- user
- folder
- embedded

### PR DESCRIPTION
**Pull request by oddlittlebird**
Working with @marcusolsson  to add a Glossary to the Grafana documentation.

Fixes #19133 

**Special notes for your reviewer**: I think some of the suggested terms are pretty basic and could be removed, but I left them in case Grafana uses the terms in ways I am not familiar with. Folder, user, app, and org all seem pretty basic.

### CODE REVIEW

**Comment by marcusolsson** [comment]
I suggest that we start with a small set of core concepts so that we can get a basic glossary to which many can contribute individual items to.

I'm thinking:

- Dashboard: A set of one or more _Panels_ organized and arranged into one or more rows.
- Panel: Basic building block in Grafana, composed by a _query_ and a _visualization_. 
- Query: Used to request data from a _data source_. 
- Visualization: A graphical representation of the result from a _query_.
- Graph: Most commonly used _visualization_.
- Time series: A series of measurements, ordered by time.
- Data source: A file, database, or service providing the data.

The descriptions need further polish, but those should be a good starting point.

**Comment by marcusolsson** [comment]
I tried building the docs and doesn't seem like we have any decent styling for the dl, dd, dt tags right now. For now, I'm thinking we could format it like:

```
- __Dashboard__: A set of one or more Panels organized and arranged into one or more rows.
```

Basically, focusing on content for now and we'll figure out proper styling as the next step.

**Comment by oddlittlebird** [comment]
Best practice is to avoid using underline for formatting. Underlined words
can be mistaken for links, which is frustrating for users.

I will run some experiments on formatting after I get home tonight. I do
like the idea of starting with a small group of terms, but I do not want to
lose the terms suggested by the community.

**Comment by marcusolsson** [comment]
Oh, on Github the double underscores makes the text bold. These are the same:

```
**Dashboard**
__Dashboard__
```

I have no personal preference to which we use.

I will create and share a Google Docs to keep track of all the suggested phrases for now. Once strong candidates emerge, we'll create issues for those.

**Comment by oddlittlebird** [comment]
Learn something new every day. :)

Thanks!

**Comment by oddlittlebird** [comment]
VSC applied ** when I hit Ctrl+B, so that is that. I really need to
download Toast UI at some point and try that out.

Anyway, please let me know what you think. I spaced the terms and
definitions out a bit to aid scanning. Another option is a table like the
one MSG uses in term lists:
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/security-terms

Whichever format we decide on, I will add it to the style guide as
something a format we should use for definitions to maintain consistency.

**Comment by marcusolsson** [comment]
Here's the current styling vs. the table inspired from MSG.

Screen Shot 2019-09-19 at 16 07 05

Screen Shot 2019-09-19 at 16 11 32

I kind of like the table actually. Basically just:

```
<table>
  <tr>
    <td>Dashboard</td>
    <td>A set of one or more panels organized and arranged into one or more rows.</td>
  </tr>
  <tr>
    <td>Data source</td>
    <td>A file, database, or service providing data.</td>
  </tr>
   ...
</table
```

**Comment by oddlittlebird** [comment]
Cool. I will apply that tonight.

**Comment by marcusolsson** [comment]
I tried to improve the definitions a bit, but feel free to change them as you see fit. Also added entries for plugins, which is a major concept that ties into the other ones.


Dashboard: 
A set of one or more Panels organized and arranged into one or more rows, to provide users with an at-a-glance view of related information.

Panel: 
Basic building block in Grafana, composed by a query and a visualization. Can be moved and resized within a dashboard.

Query: 
Used to request data from a data source. The structure and format of the query depends on the specific data source.

Visualization: 
A graphical representation of the result from a query. 

Graph: 
A commonly used _visualization_ that displays data as points, lines, or bars.

Time series: 
A series of measurements, ordered by time. Time series are stored in data sources, and returned as the result of a query.

Data source: 
A file, database, or service providing the data. Grafana supports a several data sources by default, and can be extended to support additional ones through _plugins_.

Plugin:
An extension of Grafana that allows users to provide additional functionality to enhance their experience. The types of plugins currently supported are _panel plugins_, _data source plugins_, and _app plugins_.

Panel plugin:
A _plugin_ that extends Grafana with additional _visualization_ options.

Data source plugin:
A _plugin_ that extends Grafana with support for additional _data sources_.

App plugins:
A plugin that contains a set of _panel_ and _data source plugins_, as well as custom pages, to provide a customized experience.

**Review by marcusolsson — CHANGES_REQUESTED** [review]
Nice!

I noticed that the last closing tag of table is incomplete:

`</table` -> `</table>`

Once that's fixed, I think we can merge this!

**Comment by oddlittlebird** [comment]
Grr. It looked fine in my VSC preview.

Oh and this is a great example of why external contributors need to be able
to build the docs, in case you need ammunition to convince people.

**Review by marcusolsson — APPROVED** [review]
Thank you! This is a great start!

**Pull request merged**
