### PR TITLE
Prometheus: Migrate from aria-label to data-testid for selectors

### LINKED ISSUE #78413: O11y Logs: Migrate from aria-label e2e selectors to data-testid
Hi @grafana/observability-logs!

A while back to changed to prefer using `data-testid` for E2E selectors instead of `aria-label`. There's only a few of these old `aria-label`-based selectors left, so we've made this list of files that your team owns so we can tidy them up 🙌.

For some guidance on how exactly to fix these, check out [this comment](https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512).

There are 2 issues over 2 files:

- [ ] 1 issue in `public/app/plugins/datasource/loki/components/LokiQueryEditor.tsx` 
- [ ] 1 issue in `public/app/plugins/datasource/loki/components/monaco-query-field/MonacoQueryField.tsx`

### LINKED ISSUE #78414: O11y Metrics: Migrate from aria-label e2e selectors to data-testid
Hi @grafana/observability-metrics!

A while back to changed to prefer using `data-testid` for E2E selectors instead of `aria-label`. There's only a few of these old `aria-label`-based selectors left, so we've made this list of files that your team owns so we can tidy them up 🙌.

For some guidance on how exactly to fix these, check out [this comment](https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512).

There are 10 issues over 6 files:

- [ ] 1 issue in `public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx` 
- [ ] 1 issue in `public/app/plugins/datasource/prometheus/configuration/ExemplarSetting.tsx` 
- [ ] 1 issue in `public/app/plugins/datasource/prometheus/configuration/ExemplarsSettings.tsx` 
- [ ] 3 issues in `public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx` 
- [ ] 1 issue in `public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryEditorSelector.tsx` 
- [ ] 3 issues in `public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx`

### PR DESCRIPTION
**Pull request by bohandley**
Fixes https://github.com/grafana/grafana/issues/78414
Fixes https://github.com/grafana/grafana/issues/78413

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by matyax — APPROVED** [review]
Thank you!

**Comment by bohandley** [comment]
I am super confused as to why this e2e test is failing with 

```
  1 failing

  1) Loki query builder
       should be able to use all modes:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-testid="data-testid Select label"]`, but never found it.
      at Context.eval (webpack://grafana/./e2e/various-suite/loki-query-builder.spec.ts:69:46)
```

The selector is there, the aria-label has been switched to data-testid, the selector in the component is written like the others 🤷🏻. @grafana/observability-logs do you have any idea why this might be? I must have missed something somewhere. If you have some extra eyes to help with this that would be appreciated 🙏🏻 

https://github.com/grafana/grafana/blob/6f3febdb6077ffb4f8194aff849cf5d22c7d34c0/public/app/plugins/datasource/prometheus/querybuilder/shared/LabelFilterItem.tsx#L79

Screenshot 2023-11-22 at 5 57 14 PM

**Comment by matyax** [comment]
I'll take a look.

**Comment by matyax** [comment]
@bohandley it looks like the Select component is not passing the `data-testid` to the actual component.

imagen

I checked out the branch and quickly queried ( document.querySelectorAll('[data-testid]') ) for all data-testid and found only these:

imagen

**Comment by bohandley** [comment]
@matyax You are correct, the SelectBase component is only passing in the aria-label. @joshhunt I have started to update the SelectBase but it doesn't seem to be working yet, passing in data-testid. Is there another way you would suggest to do this? Maybe wrap the component in a div and add data-testid there instead of updating the SelectBase? I am open to suggestions.

**Comment by joshhunt** [comment]
it could pass it through (could be done on this PR if it's relatively straight forward). Otherwise, I've seen others put it on the containing div.

**Comment by bohandley** [comment]
@joshhunt @matyax Hmmm, this is frustrating 🤣 Both options are not feasible in using data-testid for the SelectBase component.

Wrapping it in a div, the scroll manager is blocking it and the select component is not visible. e2e tests fail for Loki when selecting anything with the SelectBase component.
Screenshot 2023-11-27 at 5 36 05 PM

Passing data-testid into the SelectBase does not work either, as it does not accept data-testid as common props, even when I explicitly set it, it does not show up. aria-label is the only attribute that is passed. 

I will ask in slack of any code examples of using data-testid with this component for e2e tests. If I cannot find any I will revert to the aria label for these and label this part of the epic blocked.

**Comment by bohandley** [comment]
@joshhunt sorry for the spam! I was able get the tests to pass by passing `data-testid` as far as I could into the component(into the `ValueContainer`) and then traverse the dom in the cypress tests to access the input. Can you please advise if this is an ok solution for now, or if not, I will do the option I mentioned above, revert to aria-label to get the tests working. What are your thoughts?

**Comment by bohandley** [comment]
Just want to ping @grafana/observability-logs and @grafana/grafana-frontend-platform to see what you think about passing data testid into the select component and then traversing the dom in the e2e tests to get the tests to pass.

**Comment by matyax** [comment]
```diff
- e2e.components.QueryBuilder.labelSelect().type('instance{enter}');
+ e2e.components.QueryBuilder.labelSelect().children('div').children('input').type('instance{enter}');
```

@bohandley Apologies if you already explained why and I missed it, but: why can't we assign `data-testid` to the same node where the `aria-attribute` was applied to?

If we're limited by the component design and there's no easy workaround, it's fine, but otherwise I'd try to make it work in the same way.

What do you think @joshhunt @grafana/grafana-frontend-platform ?

**Comment by bohandley** [comment]
> @bohandley Apologies if you already explained why and I missed it, but: why can't we assign data-testid to the same node where the aria-attribute was applied to?

@matyax no apology necessary! We are limited to the component. It does not pass in data-testid as easily as it does aria-label. The grafana/ui `Select` component is a wrapper for grafana `SelectBase` component which is a wrapper for the React component `ReactSelectComponent` which is a wrapper for the actual React `Select` component. The aria-label targets exactly where we need it but, because data-testid is not part of the React Select props it does not get passed deeper into the component. The best I can do is to pass it as far as I can into the components modified in grafana/ui for the React Select and this is the `ValueContainer` which lives in grafana/ui.

So, currently there is no way to use data-testid on the React Select in e2e selectors without traversing the DOM.

**Review by matyax — APPROVED** [review]
Looks good to me!

**Comment by matyax** [comment]
In that case, I'm okay with being more specific with the selectors. It shouldn't change so often. Thank you for fixing this!

**Comment by matyax** [comment]
@bohandley Is there anything pending here?

**Comment by bohandley** [comment]
I am going to merge this as it fixes the original issue but creates this new one:

Using data test id in the select component requires traversing the DOM because the React select component does not support using data test id.

Merging it!

**Pull request merged**
