### PR TITLE
HACKATHON: Grafana Sharing Slack App

### LINKED ISSUE #87566: Grafana Sharing Slack App
**Why is this needed**:

An additional way to share dashboards and also allow for preview in slack

**What would you like to be added**:

New feature to share dashboard to slack from Grafana and unfurl URL

**Who is this feature for?**

Grafana users

### PR DESCRIPTION
**Pull request by lucychen-grafana**
**Grafana Sharing Hackathon**
Please, do not review it yet

### CODE REVIEW

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
https://grafanasharin-tqx1468.slack.com/archives/C06D1R2CUUA/p1704982186583949

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by AgnesToulet** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by evictorero** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Comment by juanicabanas** [comment]
/deploy-to-hg --enterprise-ref lucychen/grafana-sharing-slack-app

**Pull request closed without merging**
