### PR TITLE
Chore: Add tool for verifying cherry-picks

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Add a CLI tool for verifying that a cherry-pick PR has all the PRs targeting a certain milestone and flagged for cherry-picking. This tool is super helpful when it comes to making sure that your cherry-pick PR is complete when making a release, since these PRs can easily be broken in some way or other (typically one or more PRs not having been picked).

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
looks good --- my only real question is if this should be here or in grabpl.  (I don't know the answer, but grabpl seems appropriate)

**Comment by aknuds1** [comment]
> looks good --- my only real question is if this should be here or in grabpl. (I don't know the answer, but grabpl seems appropriate)

@ryantxu Thanks for bringing that up I guess. I'm unsure if this command should go into grabpl or not, to be perfectly honest. The reason I went this route is that I figured it's easier for someone conducting a release to run a tool within the Grafana repo, than to download grabpl, but I could be convinced otherwise :)

Thinking it over again, maybe a benefit of having it in grabpl is that the version is independent of Grafana. For example if there's a bug fix to this tool, you won't miss it because you're on the wrong branch of Grafana when running it (that could always happen).

**Comment by ryantxu** [comment]
My gut says grabpl makes more sense since it is independent of the grafana build and should be able to be used across grafana versions.

but again, I trust your judgement on this one :)

**Comment by aknuds1** [comment]
> My gut says grabpl makes more sense since it is independent of the grafana build and should be able to be used across grafana versions.

@ryantxu Let's move it to grabpl, since you also think it's best independent of the Grafana branch you're on :)

**Comment by bergquist** [comment]
Sweet!

grapl repo makes a little more sense. I guess we could have a scripts folder there? Or do we want to put everything in grabpl?
It would be very nice if we could replace the cherry-pick script with a program that try to cherry-pick PR if they haven't been cherry-picked already. That way we could rerun this program multiple times without worrying about missing cherry-picks or creating problems.

**Comment by aknuds1** [comment]
> Sweet!
> 
> grapl repo makes a little more sense. I guess we could have a scripts folder there? Or do we want to put everything in grabpl?

@bergquist I think it should be another grabpl sub-command, akin to how `git` or `gcloud` have many sub-commands in different categories.

> It would be very nice if we could replace the cherry-pick script with a program that try to cherry-pick PR if they haven't been cherry-picked already. That way we could rerun this program multiple times without worrying about missing cherry-picks or creating problems.

I'm not sure how to best do what you outline above, but I have been thinking that we should re-consider our cherry-picking approach. I don't have a better solution yet, but I'd like to think about it in depth once we've released 7.0.

**Comment by bergquist** [comment]
> but I'd like to think about it in depth once we've released 7.0. 

Yes. We should make this a high prio after 7.0. I think we will do 7.0.x and 7.1 fairly soon after.

**Comment by aknuds1** [comment]
Closing this in favour of adding a sub-command to grafana/build-pipeline.

**Pull request closed without merging**
