### PR TITLE
Log Panel: Improve log row hover contrast and visibility

### PR DESCRIPTION
**Pull request by Seyaji**
Screenshot 2022-06-15 at 22 30 58

Fixes #50861

As requested in the above issue the contrast has been changed to provide higher visibility. 

:)

### CODE REVIEW

**Comment by codeincarnate** [comment]
Just checked out the change and looks great! Also tested in light mode and thankfully the contrast there is also appropriate:

contrast-light-mode

**Review by codeincarnate — APPROVED** [review]
LGTM

**Comment by codeincarnate** [comment]
Not sure why the enterprise PR check is failing 😖, I _think_ it should be OK but asking about that one.

**Comment by Seyaji** [comment]
Hopefully I didn't do something wrong when I initiated it 🙏

**Comment by codeincarnate** [comment]
@Seyaji not on your side at all, just my lack of familiarity with some of our processes. Thank you for the contribution!

**Pull request merged**
