### PR TITLE
InfluxDB: Add new truthiness operators (`Is` and `Is Not`) to InfluxQL Query Builder

### LINKED ISSUE #77794: InfluxDB: It's not possible to include boolean fields in query conditions using the InfluxQL Editor
### What happened?

Using the InfluxQL Builder, it isn't possible to build a query like
```
SELECT field FROM measurement WHERE boolean_field = true
```

This is because, when an (in)equality operator is present, the backend assumes the value is a string and wraps the value in quotes, leading to InfluxDB receiving
```
SELECT field FROM measurement WHERE boolean_field = 'true'
```

### What did you expect to happen?

It should be possible to query based upon a boolean field value

### Did this work before?

No

### How do we reproduce it?

1. Write a point into an InfluxDB datasource, with a boolean field (e.g. `my_measurement,foo=bar a=1,b=true`)
2. Attempt to query it using InfluxQL based upon the field value

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

_No response_

### Grafana platform?

Other

### Datasource(s)?

InfluxDB

### PR DESCRIPTION
**Pull request by btasker**
**What is this feature?**

Implements support for including query conditions based upon boolean field values using new Is and Is Not operators (see note below) (https://github.com/grafana/grafana/issues/77794).

**Why do we need this feature?**

There's a pre-existing issue where [it's not possible](https://github.com/grafana/grafana/issues/2674#issuecomment-1446564677) because after submission, the value will be coerced to a string (e.g. false will be coerced to 'false').

**Who is this feature for?**

Users who want to use the InfluxQL Query Builder to build WHERE conditions based on Boolean fields

**Which issue(s) does this PR fix?**:

Fixes #77794

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by btasker** [comment]
@itsmylife - this should be ready for review.

The latest 3 commits add type inference so that `Is` and `Is Not` work with string/int/float fields (if the key indicates a tag the value will always be quoted). If needed, they can safely be dropped/reverted out of the PR before merge so that it simply adds `Is` and `Is Not`.

The front-end code has also been updated so that correct translation occurs when the user switches between builder and raw mode (I didn't think to check that on the previous PR)

**Review by itsmylife — COMMENTED** [review]
That looks good! ❤️ 
Could you please provide tests for influx_query_model too? 
Thanks in advance!

**Comment by btasker** [comment]
@itsmylife FYI, that pending check just shows "Build is blocked, please, contact repo admin in order to proceed" (same on the other PR too).

**Comment by itsmylife** [comment]
@btasker I will enable it when we'll fix the problem in our CI pipeline. There is an unrelated thing broken right now.

**Comment by btasker** [comment]
:+1: Thanks - was just double checking **I** hadn't broken anything :)

**Comment by itsmylife** [comment]
@btasker I merged [the other PR](https://github.com/grafana/grafana/pull/77917) and we got conflicts with this one. Could you please resolve them? I tried on github UI and failed :) And I don't want to mess your PR up.

**Review by itsmylife — APPROVED** [review]
LGTM it just needs the conflicts to resolve

**Comment by btasker** [comment]
:+1: Sure will look at these a little later (I had a feeling we might get some)

**Comment by btasker** [comment]
Github's UI was failing me too, so I've rebased on `main` and resolved the conflicts

**Comment by itsmylife** [comment]
@btasker now there is a linting issue. But we are quite close to merge it :) 

```
+ yarn run prettier:check
[warn] public/app/plugins/datasource/influxdb/components/editor/query/influxql/visual/TagsSection.tsx
[warn] public/app/plugins/datasource/influxdb/influx_query_model.test.ts
[warn] public/app/plugins/datasource/influxdb/influx_query_model.ts
[warn] Code style issues found in 3 files. Run Prettier to fix.
```

**Pull request merged**
