### PR TITLE
Plugins: opentsdb ds: interpolate filter variables in expressions

### PR DESCRIPTION
**Pull request by ugtar**
Use the same code path to interpolate both metric variables and filter/tag variables when the data source is accessed either directly or via the expressions datasource.

partial fix for #48141 (opentsdb datasource only)

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ugtar** [comment]
can't add labels..

**Comment by ugtar** [comment]
I can't add any labels. this PR is essentially an enhancement. it doesn't need a backport, milestone can be the next major .x version, and I don't care if it's in the changelogs

**Comment by bohandley** [comment]
Thank you for your contribution @ugtar! This looks good to me. I will get the labels added. Thank you again!

**Review by bohandley — APPROVED** [review]

**Comment by itsmylife** [comment]
@ugtar Those checks will run after the merge. So I think it is ok to be merged so I merged. Thanks for your contribution.

**Pull request merged**
