### PR TITLE
SQL: Add timeFilter macro to query builder

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What is this feature?**

This PR will add back the ability to add timeFilter macro to the SQL query builder. Not fixes the #68750 entirely as we still need to add some defaults to it. I decided to do that in another PR.

**Which issue(s) does this PR fix?**:

Part of [#68750](https://github.com/grafana/grafana/issues/68750)

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by aangelisc — APPROVED** [review]
This LGTM, I'm surprised this was removed in general 🤔

**Review by gabor — COMMENTED** [review]
tested it and it worked fine (adding the time-macro works fine).

the diff looks good, but i do not know how `AwesomeQueryBuilder.tsx` is supposed to work. again, all the lines there look reasonable, but i have no idea how to use that library.

**Review by lwandz13 — APPROVED** [review]
Looks good!

**Comment by kerrygibian** [comment]
hi @zoltanbedi do we know when this will be released? have a customer who needs it. thank you!

**Comment by zoltanbedi** [comment]
Hi @kerrygibian,
it will be released in 10.3.0 on January.

**Comment by kerrygibian** [comment]
hi @zoltanbedi was this included in the 10.3 release on January 23rd?

**Comment by zoltanbedi** [comment]
it was yes @kerrygibian

**Comment by bobemoe** [comment]
Fantastic! Great to see the time macros available again! Looking forward to having
them back as defaults as its quite a few clicks to enable and also remove the 50 limit. 

@zoltanbedi do you have link to the separate PR with the defaults so I can track progress.

**Pull request merged**
