### PR TITLE
GraphPanel: show results for all SeriesData

### PR DESCRIPTION
**Pull request by ryantxu**
With SeriesData, we can show results for stuff that comes back as TableData or TimeSeries:

image

After #16659, we should look at how to have a MetricsPanelCtrl ask to get results as `SeriesData[]` rather than `LegacyResponseData[]`

To get the display to work OK, I also added 'name' to TableData

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Looks great, but think we need some tests for the getTimeSeries function

**Comment by torkelo** [comment]
> we should look at how to have a MetricsPanelCtrl ask to get results as SeriesData[] rather than LegacyResponseData[]

Will that not break plugins?

**Comment by ryantxu** [comment]
I meant to say have `GraphCtrl` as `MetricsPanelCtrl` for SeriesData[] -- so that this panel gets SeriesData directly, but others would still default to LegacyResponseData[]

**Comment by torkelo** [comment]
> I meant to say have GraphCtrl as MetricsPanelCtrl for SeriesData[] -- so that this panel gets SeriesData directly, but others would still default to LegacyResponseData[]

ah that makes more sense :)

**Comment by ryantxu** [comment]
@torkelo -- I added a test.  In the future, I think we should use the same loop in  `getTimeSeries` to

* calculate the flotPairs using `getFlotPairs` from grafana ui
* calculate the stats using fieldReducers

This would let us avoid the unnecessary extra array `datapoints` -- it will also force us to understand what stats are required off the *time* field vs the *data* field.

I did not give this a try because I do not understand the `type=docs` support and don't want to wade into that right now :)

**Comment by torkelo** [comment]
Great, regarding docs you can completely disregard that as it was just an attempt long ago to support Elasticsearch raw docs , never got it working

**Comment by torkelo** [comment]
removed some of the old unused code to handle table & docs data and did some super minor refactoring. 

histogram mode seems to be broken.

**Comment by ryantxu** [comment]
Histogram fixed -- never seen that option before :)

**Comment by torkelo** [comment]
Streaming with the old angular graph is not working for some reason, working with the new react panels.

**Comment by ryantxu** [comment]
@torkelo - without looking, I bet it is getting the data but not setting the new time range, so any updates are outside the graph view


I'll take a look tomorrow

**Pull request merged**
