### PR TITLE
Legend: Sort by name

### LINKED ISSUE #18186: legend table -> sort by name
on a graph panel, when creating a legend "as table", one can have summary stats like avg, total, etc and sort by those.
but it would very helpful if we could sort by series name as well.

not a good example, but anyway

sort

### PR DESCRIPTION
**Pull request by adela-almasan**
Added the ability to sort legend by name.
Removed viz sorting from Barchart as this functionality was already removed from time series (as discussed with @leeoniya).
Updated docs.

https://github.com/grafana/grafana/assets/88068998/49d7396b-ced6-4766-a68a-2e95a0e63afa

Fixes #18186

**Special notes for your reviewer:**
- added the "Name" header just to the sortable legends [Timeseries, Bar chart, Histogram]

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by leeoniya** [comment]
> In table bottom - the legend stretches and the column name is displayed too far away from the actual value

any reason we can't always left-align the first header cell the same way the names are left-aligned? 🤔

**Comment by adela-almasan** [comment]
I don't think there's any. To me it doesn't make sense to be that stretched out..

align_left

**Review by leeoniya — APPROVED** [review]
LGTM, works for me :)

thanks!

**Review by imatwawana — APPROVED** [review]
LGTM!

**Pull request merged**
