### PR TITLE
PanelEdit: Display drag indicators on draggable sections

### LINKED ISSUE #24665: PanelEditor: Add UI drag indicator for the sidebar and bottom pane
We need to add a handle for sidebar and visualisation – it's not at all obvious it can be dragged. Users already struggled with this during community call. We can use the one from the `Query History` drawer.
image
image

_Originally posted by @sarlinska in https://github.com/grafana/grafana/issues/23551#issuecomment-628053212_

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- adds draggable indicators to the sections that can be dragged in `PanelEdit`
- this matches the style seen in `Explore`'s query history

| before | after |
| --- | --- |
| image | image |
| image | image |
| image | image |

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/24665

**Special notes for your reviewer**:

not sure if this is the way we wanna go or not, but i thought i'd give it a go anyway and see what everyone thinks.
the main reason for hesitation is that the explore page is slightly different in that the draggable element is a drawer, whereas here the draggable element is the gap between the 2 sections.

my preference would be something akin to a [handlebar between the sections](https://uxdesign.cc/handlebars-in-ui-design-4b36af67733b)

edit: here's what that would look like:
image

### CODE REVIEW

**Comment by torkelo** [comment]
@ashharrison90 I think prefer the handlebars in between sections. Can you record a short video of each option and share in #ux? 

@jessover9000 thoughts?

**Comment by ashharrison90** [comment]
# handlebars
Kapture 2021-11-16 at 12 05 28

# style similar to explore
Kapture 2021-11-16 at 11 48 05

**Comment by lukasztyrala** [comment]
In between version looks and works better.

**Comment by ashharrison90** [comment]
so far we have 3 votes for handlebars between the sections, so i've updated this PR to do that instead. feel free to pull down and have a play around 👍

**Comment by hugohaggmark** [comment]
I vote for in between as well, looks great 🎉

**Review by torkelo — APPROVED** [review]

**Review by thisisobate — APPROVED** [review]
Looks good!

**Pull request merged**
