### PR TITLE
AnnoList: add alpha annotations list plugin

### LINKED ISSUE #11323: Annotation List panel
There is currently a built-in panel to show: `dashboards`, `plugins`, and `alerts`

It would be nice to have a supported way to list and navigate the (newish) built-in editable Annotations. 

I have started a custom panel, but it feels like something that could/should be a core feature.

image

Clicking a row takes you to:

image

See:
https://github.com/ryantxu/annotations-panel

Is there interest in doing this (soon) in grafana core?  Or should I keep it as a plugin?  (I'm fine either way)

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #11323, This is an alpha panel that:
* ports https://github.com/ryantxu/annotations-panel to react
* Add `annolist` as a standard built in plugin 

My real motivations for this are:
* a real example of a plugin that should support migrating from an old plugin id.  See #17186
* begin typings for annotations
* More typical plugin configuration example for @dprokop to think about with #16773
* Template for pluginlist & dashlist

TODO:
- [x] format date
- [x] finish config UI
- [x] link to panels

Should not block adding this as an alpha panel:
 * ~~react `baron__scroller`~~
 * react tags editor?

### CODE REVIEW

**Comment by ryantxu** [comment]
@torkelo -- can I get your early thoughts on this?

In particular, this panel points out a few general features that still need react support -- what process makes sense?

**Comment by ryantxu** [comment]
@dprokop -- can you take a look at this?  It is an alpha panel, and now everything works.  This would be helpful to have while working on #17673

**Comment by torkelo** [comment]
We can merge this as an alpha panel and decide later what to do with it, easier than having a long lived PR and keeping it up to date :)

**Review by torkelo — APPROVED** [review]

**Comment by marefr** [comment]
@torkelo @ryantxu I guess this and the issue should be added to the 6.3-beta1 milestone? Also "add to changelog"? Please update as you see fit.

**Comment by ryantxu** [comment]
@marefr -- I don't think we want it in the changelog.  It is essentially a hidden feature right now.

I don't know about "6.3-beta1 milestone" tag.  What does adding to the milestone trigger?

**Comment by marefr** [comment]
@ryantxu That's totally optional putting it in the changelog. 6.3-beta1 milestone is only "tagging" PR's and issues so it's easy to understand what is included in a milestone - it's optional as well, but I find it convenient to have a milestone assigned instead of comparing git tags for finding out where one PR landed.

**Comment by Dieterbe** [comment]
does this mean the plugin is in grafana core?

**Comment by torkelo** [comment]
An alpha version at least :) (have to enable server setting to test/use alpha panels). 

We will evaluate later where this fits best

**Pull request merged**
