### PR TITLE
AzureMonitor: Add curated dashboards for Azure services

### PR DESCRIPTION
**Pull request by avidhanju**
**What this PR does / why we need it**:

This PR adds the following curated dashboards to the Azure Monitor data source.
- Azure Storage Insights
- Azure Key Vault Insights
- Azure CosmosDB Insights
- Azure SQL Database Insights

**Which issue(s) this PR fixes**:

Doesn't fix any issue.

**Special notes for your reviewer**:
We have already published these dashboards to the Grafana dashboards gallery.

### CODE REVIEW

**Comment by mitulmk** [comment]
@avidhanju/ @shuotli please add ADX insights as well

**Comment by joshhunt** [comment]
@avidhanju When importing the "Key vault Insights" dashboard it fails with an error on the backend `error="Dashboard input variable: VAR_NS missing from import command"`

**Comment by joshhunt** [comment]
Also I get some errors when trying to use the SQL Database dashboard

> Templating [SqlInstance]
> Error updating options: The provided credentials have insufficient access to perform the requested operation

But I think this might be a regression we introduced in 8.0 - I'll investigate.

**Comment by avidhanju** [comment]
> @avidhanju/ @shuotli please add ADX insights as well

Done.

**Comment by avidhanju** [comment]
> @avidhanju When importing the "Key vault Insights" dashboard it fails with an error on the backend `error="Dashboard input variable: VAR_NS missing from import command"`

I removed that.

**Comment by avidhanju** [comment]
> Also I get some errors when trying to use the SQL Database dashboard
> 
> > Templating [SqlInstance]
> > Error updating options: The provided credentials have insufficient access to perform the requested operation
> 
> But I think this might be a regression we introduced in 8.0 - I'll investigate.

It is loading fine for me in 8.0. Do you have the contributor access to the workspace you are trying to load this dashboard for?

**Review by joshhunt — APPROVED** [review]
Looks great, thanks for contributing!

**Pull request merged**
