### PR TITLE
Graph panel: the alert marks are not being aligned with the data points on the graph

### PR DESCRIPTION
**Pull request by lessenko**
**What this PR does / why we need it**: PR makes  the right match for the alert marks and the data points on the graph

**Which issue(s) this PR fixes**:

Fixes # https://github.com/grafana/grafana/issues/17727

### CODE REVIEW

**Comment by lessenko** [comment]
Hi,
I see notice  "backend-lint | Failed,  File is not `gofmt`-ed with `-s` (gofmt)".
I tried to do:  gofmt -s models.go > models.go2 (on local computer) and reload files.
I see similar results.
  Thanks.

**Comment by torkelo** [comment]
Think you have misunderstood the alert annotations events, they are not directly linked to when data points that triggered the alert happened, but when the alert fired.  So I am not sure we need this logic. 

There is also the problem of having multiple conditions, what time to use?

**Comment by lessenko** [comment]
Thank you. If to compare two illustrations first and last from (https://github.com/grafana/grafana/issues/17727), 
it seems it's problem (for user) to find the event point at last illustration.

About multiple condition. You are right. 
It is needed to add a  final solver before marking graph. 
It will use time if all conditions (statuses of other conditions from DB) 
permit to do that.

I suppose currently it's used similar solver.
If it exists, it's needed to modify it.

It's very draft idea. I have to try example with different condition. 

Regards

**Comment by lessenko** [comment]
It's two samples with different logic (OR - first, AND - second) and same times in query.
It seems it's similar on true. It's needed more samples and different times in query. 

Screenshot_OR_20190626_114215


Screenshot_AND_20190626_113508

Screenshot_Rule_20190626_114453

**Comment by lessenko** [comment]
I would like to suggest the following:
The current (Grafana's) logic is used by default, and the proposed logic can be as option for users  through the configuration or UI. 
It may be useful if a user wants to know where on graph the parameters are out from permissible  conditions (alert reason).
What do you think?

Thanks.

**Comment by torkelo** [comment]
Can you open a feature request for that option so we can gauge how many users are interested in that option? 

Closing this for now. Sorry, we appreciate your contribution and helping make Grafana better but we are worried about feature creep and adding options and features for edge cases that very few will ever use or need.

**Comment by lessenko** [comment]
Thank you! I'll open the feature request.
And I would like to thankful to you and your team for the wonderful product.

Best regards.

**Pull request closed without merging**
