### PR TITLE
Chore: Remove prettier-plugin from ESLint

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
An extension of grafana/eslint-config-grafana/pull/22 this PR removes the eslint-plugin-prettier from the repo to speed up frontend linting (mostly) in CI.

| Before | After |
| --- | --- |
| Screenshot 2022-02-25 at 14 33 36 | Screenshot 2022-02-28 at 11 51 32 |

Before (locally):

```
Rule                                       | Time (ms) | Relative
:------------------------------------------|----------:|--------:
prettier/prettier                          | 47121.683 |    73.1%
jsdoc/check-alignment                      |  3051.863 |     4.7%
react/no-deprecated                        |  2758.311 |     4.3%
react/display-name                         |  2591.744 |     4.0%
react/no-direct-mutation-state             |  2117.436 |     3.3%
react/no-string-refs                       |  1578.806 |     2.4%
react/require-render-return                |  1235.619 |     1.9%
@typescript-eslint/naming-convention       |  1076.987 |     1.7%
no-redeclare                               |   320.645 |     0.5%
@typescript-eslint/type-annotation-spacing |   239.294 |     0.4%
```

After (locally):
```
Rule                                       | Time (ms) | Relative
:------------------------------------------|----------:|--------:
jsdoc/check-alignment                      |  3698.093 |    18.0%
react/no-deprecated                        |  3270.812 |    15.9%
react/display-name                         |  3054.202 |    14.9%
react/no-direct-mutation-state             |  2677.127 |    13.0%
react/no-string-refs                       |  1943.171 |     9.5%
react/require-render-return                |  1493.245 |     7.3%
@typescript-eslint/naming-convention       |  1104.044 |     5.4%
no-redeclare                               |   384.001 |     1.9%
jest/no-focused-tests                      |   319.223 |     1.6%
@typescript-eslint/type-annotation-spacing |   230.898 |     1.1%
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
~_WIP right now as using an alpha publish of `@grafana/eslint-config` to make sure everything is working as it should._~
Successfully published eslint-config@3.0.0 which this branch is now using.

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]

**Review by Elfo404 — COMMENTED** [review]
~shall we also add `prettier --check` to some ci step?~

nevermind, it's already in there

**Review by Elfo404 — APPROVED** [review]
🚀

**Comment by jackw** [comment]
> shall we also add `prettier --check` to some ci step?

I believe `yarn prettier:check` is in [lint frontend](https://drone.grafana.net/grafana/grafana/53281/1/9. I've pushed a commit that adds `ts,tsx,js` to the file extensions.

**Comment by Elfo404** [comment]
yeah, i checked 20 seconds after writing that comment instead of doing it before, sorry for the noise 🙏

**Review by nmarrs — APPROVED** [review]
LGTM! Great time savings for our CI builds!

**Review by dprokop — APPROVED** [review]

**Pull request merged**
