### PR TITLE
Do not sanitize cell link in table panel if disableSanitizeHtml option is set to true

### PR DESCRIPTION
**Pull request by ae3e**
To be coherent with the [links panel](https://github.com/grafana/grafana/blob/31ad86ffc086d1f04e1b7b570456d7e2c1621cb3/public/app/features/panel/panellinks/link_srv.ts#L257)

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure about this, what's the argument for not sanitizing here?

**Comment by ae3e** [comment]
If `disableSanitizeHtml=true` in custom.ini file, links in graph panel are not sanitized but in table panel they are. I though it would be better to make it consitent.

Furthermore, I'm using it in a hacky way to update variables 😊 . This way, when I click on a table or a chart panel, I can update others panels without to reload the whole dashboard and then have a better user experience... but it's maybe a feature on the roadmap... 😁

**Comment by ae3e** [comment]
Wow! Thanks! It' really great! 👍 
I was using Grafana 6.5 and I guess this feature was introduced in Grafana 6.6 (PR #21480).

...so, my PR is only to make code more consistent ?! 😕

**Comment by torkelo** [comment]
> ...so, my PR is only to make code more consistent 

true, but unless there is a strong need for insecure links I would prefer to not add this

**Pull request closed without merging**
