### PR TITLE
End2end: Make it possible to run e2e tests with BASE_URL

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Make it possible to run e2e tests with custom host and port

```bash
# like current will use localhost and 3001
> ./e2e/run-suite
# custom port
> PORT=3000 ./e2e/run-suite
# custom host and port
> HOST=10.0.20.149 PORT=3000 ./e2e/run-suite
```

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Review by hugohaggmark — APPROVED** [review]
Outstanding work!

This https://github.com/grafana/grafana/blob/master/contribute/style-guides/e2e.md or maybe this https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md needs updates too, could be a separate PR.

**Comment by marefr** [comment]
@hugohaggmark seems like documentation is a lot outdated. Looking at this now, wonder if grafana's npm/yarn scripts for e2e actually should run "start and run suite" - that doesn't feel feel the most common thing since when developing you're 99% using localhost:3000. Would suggest that "run suite" doesn't wait for grafana to start and add a new script called wait for grafana that's being used when running "start and run suite". Then "run suite" can take the "BASE_URL" environment variable for override. Thoughts?

**Comment by hugohaggmark** [comment]
> @hugohaggmark seems like documentation is a lot outdated. Looking at this now, wonder if grafana's npm/yarn scripts for e2e actually should run "start and run suite" - that doesn't feel feel the most common thing since when developing you're 99% using localhost:3000. Would suggest that "run suite" doesn't wait for grafana to start and add a new script called wait for grafana that's being used when running "start and run suite". Then "run suite" can take the "BASE_URL" environment variable for override. Thoughts?

I think that should be fine any thoughts @torkelo ?

**Comment by torkelo** [comment]
>  that doesn't feel feel the most common thing since when developing you're 99% using localhost:3000.

that is the point, so the e2e is run on a separate port to not conflict with your dev server 

> Would suggest that "run suite" doesn't wait for grafana to start and add a new script called wait for grafana that's being used when running

yea that sounds like a good idea

**Review by aknuds1 — APPROVED** [review]

**Review by torkelo — APPROVED** [review]

**Comment by hugohaggmark** [comment]
Amazing work as always @marefr !

**Pull request merged**
