### PR TITLE
Plugins: Hide plugins page from viewers, and limit /api/plugins to only core plugins when called by viewer role 

### LINKED ISSUE #18927: Prevent Viewer from seeing plugins list
**What would you like to be added**:

When I log in as a user that only has Viewer permissions, it's possible to access the Plugins list from the Configuration menu to the left. I'd like it to be possible to hide the Plugins list from Viewer users.

**Why is this needed**:

When the user is only a viewer, the plugins list is not useful for them, and its presence can be confusing.

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #18927

### CODE REVIEW

**Comment by marefr** [comment]
Do we want to make this change? :) The plugin list panel shows plugins for viewers currently.

**Comment by dprokop** [comment]
Yes it does, but what's the value of it? :) The issue has some upvotes though and is(was until I have changed it;)) classified by @torkelo as 6.6.1

**Comment by torkelo** [comment]
Yes, the plugin list panel should be removed. That api should only be for org admins

**Comment by marefr** [comment]
If the plugin list panel is removed I'm fine doing this. But we may want to change the permissions in HTTP API regarding listing plugin details? This change should be added to breaking changes.

**Comment by dprokop** [comment]
> Yes, the plugin list panel should be removed. 

@torkelo I'm not really sure this should be done. The dashboard using plugins list panel will then have an empty space when the panel was present. This is super confusing when I have tested it agains some dashboards. I think the primary issue described bu the author was to make the plugins list not accessible from the side menu. I would probably leave the plugins list panels in place as they links lead only to plugins readme page.

**Comment by torkelo** [comment]
Not sure the plugin list panel needs to exist, sure it will be an empty panel on existing dashboards. But doubt that this is a common panel used in custom dashboards. 

was thinking of adding that "plugins have updates" to the useful links panel (homelinks), and improve the configuration/plugins list so you can sort by plugins that have updates etc. 

The problem with that plugin is that we need to lock down that api so only admins can use it so it will be empty for editors and viewers.

**Comment by Krylanc3lo** [comment]
Hello,
it would be really great. Could we help to test for example ?
Thanks!

**Comment by torkelo** [comment]
Made a slight change to the /api/plugins api, so that it only returns core plugins for users with viewer role.

**Comment by dprokop** [comment]
@torkelo thanks!

**Comment by torkelo** [comment]
so think this can be merged now

**Pull request merged**
