### PR TITLE
Docs: Moves http api docs to the developer docs

### PR DESCRIPTION
**Pull request by chri2547**
Refactors http-api docs into the developer docs.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by marefr** [comment]
@chri2547 think alias is missing for all HTTP API pages, e.g. https://grafana.com/docs/grafana/next/http_api/ is a 404 rather than redirecting to https://grafana.com/docs/grafana/next/developers/http_api/.

**Comment by jdbaldry** [comment]
Hmm, yes. Is it the case that we need both "next" and "latest" version aliases when we are working with aliases for the latest Grafana docs. Or should we only have the "next" aliases and expect that they are renamed as part of the release process?

**Comment by marefr** [comment]
I see. Didn't know that we used latest as part of the aliases at all. I guess we should be fine then?

**Comment by jdbaldry** [comment]
Assuming we want all published docs to have no 404s including `next`, I think we still want to fix the next aliases here and we will need to think about how to maintain these over time with backporting and multiple versions at play.

**Comment by marefr** [comment]
Think next resulting in 404s is fine as long as latest aliases works as expected

**Pull request merged**
