### PR TITLE
Viz: Fix loading bar shifts text

### LINKED ISSUE #88104: Viz: The loading bar causes text to shift
### What happened?

A loading bar is shown for slow queries for the panel, which causes text to shift.
blur-bug-1

Only happens when there is no title for the panel.
blur-bug-panel-title-1

This issue is similar to #82214 but was only fixed for panels with a title.

It only happens on Chromium-based browsers like Chrome, Edge, Brave, Etc.
It doesn't happen on Firefox.

### What did you expect to happen?

The text to not shift when retrieving data.

### Did this work before?

It worked in v9.4 and broke in v9.5.
It was partially fixed in v11, but only for panels with a title.

### How do we reproduce it?

blur-bug-reproducable-1

1. Create a new stat panel with the `TestData` data source
2. Change the query scenario to be `Slow Query`
3. Change `Show` under `Value options` to `All values`
4. Change `Fields` under `Value options` to `time`
5. Remove the panel title
6. Refresh the panel (the text shifts)

### Is the bug inside a dashboard panel?

Removed some of the data points since I got `There was an error creating your Issue: body is too long (maximum is 65536 characters).`

| Key | Value |
|--|--|
| Panel | stat @ 11.0.0 |
| Grafana | Grafana v11.0.0 (277ef258d4) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "type": "stat",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "custom": {
                    "customStat": 10
                  }
                },
                "fields": [
                  {
                    "name": "time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "A-series",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "labels": {},
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1716210855578,
                    1716210870578,
                    1716210885578,
                    1716210900578,
                    1716210915578,
                    1716210930578,
                    1716210945578,
                    1716210960578,
                  ],
                  [
                    31.494190733870685,
                    31.4360624052497,
                    31.41956566114027,
                    31.1754770651706,
                    31.12398544924021,
                    31.23567247094241,
                    31.212607552630143,
                    31.429187433477672
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "reduceOptions": {
          "values": true,
          "calcs": [
            "lastNotNull"
          ],
          "fields": "/^time$/"
        },
        "orientation": "auto",
        "textMode": "auto",
        "wideLayout": true,
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "showPercentChange": false
      },
      "fieldConfig": {
        "defaults": {
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "pluginVersion": "11.0.0",
      "title": "Reproduced with embedded data"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >stat @ 11.0.0</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 1440 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v11.0.0 (277ef258d4) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"type\": \"stat\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"datasource\": {\n    \"uid\": \"cdc7hj45r7474f\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"id\": 1,\n  \"targets\": [\n    {\n      \"scenarioId\": \"slow_query\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"cdc7hj45r7474f\"\n      },\n      \"stringInput\": \"1s\"\n    }\n  ],\n  \"options\": {\n    \"reduceOptions\": {\n      \"values\": true,\n      \"calcs\": [\n        \"lastNotNull\"\n      ],\n      \"fields\": \"/^time$/\"\n    },\n    \"orientation\": \"auto\",\n    \"textMode\": \"auto\",\n    \"wideLayout\": true,\n    \"colorMode\": \"value\",\n    \"graphMode\": \"area\",\n    \"justifyMode\": \"auto\",\n    \"showPercentChange\": false\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"11.0.0\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: undefined // 2024-05-20 21:38:34",
  "tags": [
    "debug",
    "debug-stat"
  ],
  "time": {
    "from": "2024-05-20T13:38:34.177Z",
    "to": "2024-05-20T19:38:34.178Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 11.0.0 (277ef258d4)
OS: Windows 11
Browser: Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build)  (64-bit)

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by ZuperZee**
**What is this feature?**

Fixes an issue where when the loading bar animation is rendered, the text shifts.

Before:
blur-bug-1

After:
blur-bug-fix-1

**Why do we need this feature?**

Stops the shifting of text.
It's more of an annoyance that it changes.

**Who is this feature for?**

Most would probably not notice, as it's pretty obscure and only seems to happen on Chromium-based browsers.
It happens for any panel with some colored text (usually red-ish).

The main group would be those who use https://github.com/gapitio/gapit-htmlgraphics-panel, as it's very visible on SVG text elements.

**Which issue(s) does this PR fix?**:

Fixes #88104

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ZuperZee** [comment]
This PR is very similar to #82218, but it was closed since I thought it was fixed by a different PR.

**Comment by ZuperZee** [comment]
I tested again on the main branch, and the issue is still there. I rebased the main branch (just because xD).
@Clarity-89 @JoaoSilvaGrafana
Pinging @torkelo @codeincarnate as well (as they looked at the last PR #82218, which was very similar to this)

**Comment by ashharrison90** [comment]
hi @ZuperZee 👋 

can you help me find a reliable way to recreate this?

here's my initial attempt, but i don't see the problem you're describing at all:

https://github.com/grafana/grafana/assets/20999846/9b837bb6-8cc8-43a7-b199-3e5dfa037a5d

few additional questions:
- what grafana version are you running?
- what browser are you using?
- what OS are you using?

**Comment by ZuperZee** [comment]
I've' tested it on multiple Grafana versions, but the one used in the GIF is v11.
The GIF is with Brave browser (tested in Chrome and Edge as well). This bug does not happen in Firefox.
I use Windows 11 with WSL. I tested it on Ubuntu v24.04 as well.

<details><summary>The dashboard json for the dashboard used in the GIF</summary>
<p>

```json
{
  "__inputs": [
    {
      "name": "DS_GRAFANA-TESTDATA-DATASOURCE",
      "label": "grafana-testdata-datasource",
      "description": "",
      "type": "datasource",
      "pluginId": "grafana-testdata-datasource",
      "pluginName": "TestData"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "panel",
      "id": "bargauge",
      "name": "Bar gauge",
      "version": ""
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "11.1.0-pre"
    },
    {
      "type": "datasource",
      "id": "grafana-testdata-datasource",
      "name": "TestData",
      "version": "11.2.0-pre"
    },
    {
      "type": "panel",
      "id": "stat",
      "name": "Stat",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "red",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 10,
        "x": 0,
        "y": 0
      },
      "id": 3,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "percentChangeColorMode": "standard",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "/^time$/",
          "values": true
        },
        "showPercentChange": false,
        "textMode": "auto",
        "wideLayout": true
      },
      "pluginVersion": "11.1.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
          },
          "refId": "A",
          "scenarioId": "slow_query",
          "stringInput": "2s"
        }
      ],
      "type": "stat"
    },
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "red",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 14,
        "x": 10,
        "y": 0
      },
      "id": 4,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "percentChangeColorMode": "standard",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "/^time$/",
          "values": true
        },
        "showPercentChange": false,
        "textMode": "auto",
        "wideLayout": true
      },
      "pluginVersion": "11.1.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
          },
          "refId": "A",
          "scenarioId": "slow_query",
          "stringInput": "2s"
        }
      ],
      "type": "stat"
    },
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "red",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 18,
        "w": 24,
        "x": 0,
        "y": 10
      },
      "id": 2,
      "options": {
        "displayMode": "gradient",
        "maxVizHeight": 300,
        "minVizHeight": 16,
        "minVizWidth": 8,
        "namePlacement": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "allValues"
          ],
          "fields": "/^time$/",
          "values": true
        },
        "showUnfilled": true,
        "sizing": "auto",
        "valueMode": "color"
      },
      "pluginVersion": "11.1.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "${DS_GRAFANA-TESTDATA-DATASOURCE}"
          },
          "refId": "A",
          "scenarioId": "slow_query",
          "stringInput": "2s"
        }
      ],
      "type": "bargauge"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "blur bug",
  "uid": "de7c8ac1-4a61-42dc-9247-97cd0b0923db",
  "version": 3,
  "weekStart": ""
}
```

</p>
</details>

**Comment by ZuperZee** [comment]
@ashharrison90
This is probably the fastest way to do it:


https://github.com/grafana/grafana/assets/39485579/590b7afd-b500-4d7c-abbc-e22ff4610f8a

**Comment by ashharrison90** [comment]
@ZuperZee ok looking into it
created a repro dashboard here: https://play.grafana.org/d/edpfs0vntj01se/23-88104-loading-bar?orgId=1
can't repro this on mac at all, but can repro on a windows machine 👍

**Comment by ashharrison90** [comment]
hi again @ZuperZee 👋 

thanks again for raising this. it was a little tricky to pinpoint since it only seems to affect webkit browsers on windows/linux, your repro steps were really helpful 🥳 

we don't really want to replace `transform` since it's more performant. instead, have found a smaller fix and raised it in https://github.com/grafana/grafana/pull/89538. will close this PR and merge that instead.

please try the fix in the smaller linked PR and let me know if it doesn't completely fix your problem. it did for me at least on a windows machine 👍

**Comment by ZuperZee** [comment]
@ashharrison90 , just to let you know. The #89538 PR fixed the #88104 issue. Thanks <3

**Pull request closed without merging**
