### PR TITLE
Hex units

### PR DESCRIPTION
**Pull request by bmundt**
Adds hex units to the column formatter in table.

### CODE REVIEW

**Comment by bmundt** [comment]
For some reason, its showing that I have not signed the CLA in the latest check. But there is only one user for the commits and I have signed the CLA and linked to that user, as you can see by the previous checks.

**Comment by torkelo** [comment]
could you describe the use case for this? Any why hex time formats?

**Comment by bmundt** [comment]
The use case is that I want to show something in a table, which is currently stored in the database as an integer, but it really only makes sense when it is displayed in hexadecimal. I'm not sure what you're second question is asking.

**Comment by torkelo** [comment]
You added the  format to the time category.  Was that on purpose? 

I will mark this as a feature request and we will have to wait and see if this is something that others would be interested in

**Comment by bmundt** [comment]
i did not mean to add the format into the time category. I will fix that. 

Examples: We have IDs that we use internally and are stored as integers, but only make sense to our operators if they are displayed hexadecimally. Another example is register values are often displayed as hexidecimal values.

**Comment by bmundt** [comment]
I meant to put it in the none category

**Comment by bmundt** [comment]
I have integers stored in my database that are actually bit fields, and displaying them hexadecimally is more preferred.

**Comment by sunnos9** [comment]
@torkelo We use a lot of integers that map alarm conditions as bit fields from various sensors/devices. A hex display is the preferred wat, currently the only option is to store it as string, which is not the correct data type for this, 
e.g for a GPS receiver we use (http://www.brandywinecomm.com/products/commercial-gps-synchronized-clocks/42-products/commercial-gps-synchronized-clocks/213-rg-2111-redundant-gps-reference-frequency-generator-with-ntp)
The bit(s) of the FaultStatus byte will be turned on according to the below sources:
Bit 7 -> 10MHZ J4
Bit 6 -> 10MHZ J3
Bit 5 -> 10MHZ J2
Bit 4 -> 1PPS output
Bit 3 -> Phase Error > 100us
Bit 2 -> FPGA Failure
Bit 1 -> GPS Failure
Bit 0 -> OCXO Current out of range"

If this is available now we'll re-do our data sources!

**Comment by sunnos9** [comment]
@torkelo or is there a better way to define custom column format, not taking the branching route and duplicating the code for the sake of a single unit or a minor custom conversion

**Comment by torkelo** [comment]
Maybe storing the data as strings in a log database like Elasticsearch is a good solution?

**Comment by torkelo** [comment]
ok, maybe this is ok, not that much code, and could be useful for others. 

Could you sign the CLA? 
https://cla-assistant.io/grafana/grafana?pullRequest=5474

**Comment by bmundt** [comment]
I have signed the CLA already, using the google form on the grafana site. Also, I have tried multiple times using the link you gave (signing in with github) but yet it still does not update saying that I have signed it. However, it does say that I have signed it for one of my previous pull requests: [#5466](https://github.com/grafana/grafana/pull/5466)

**Comment by bmundt** [comment]
I think this might be because I originally had some commits with a different user (without a github account), so I just edited the author on those commits, but for some reason CLA didn't update. Would making a new PR fix this?

**Comment by torkelo** [comment]
yea, try doing a new commit

**Comment by torkelo** [comment]
I mean a new PR

**Comment by bmundt** [comment]
Created new PR to fix CLA issues, new PR: [#5474](https://github.com/grafana/grafana/pull/5474)

**Comment by bmundt** [comment]
wrong link, here is the new PR: [#5530](https://github.com/grafana/grafana/pull/5530)

**Pull request closed without merging**
