### PR TITLE
GrafanaUI: Add icon to links on Plugin configuration page

### LINKED ISSUE #49644: [HG] URLs in the header of /plugins/[plugin_name] in Grafana doesn't appear as a URL
On the /plugins/[pluginname] page, the name of the plugin is not a URL but it should be! Also docs and license should be underlined.

[Internal reference](https://grafana.productboard.com/feature-board/4266220-self-serve-feature-ux-docs-requests/features/13434656/detail)

### PR DESCRIPTION
**Pull request by leandro-deveikis**
**What this PR does / why we need it**:
Small fix to add underline to links under the theader

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/49644

**Special notes for your reviewer**:
Before: 
image

After: 
image

### CODE REVIEW

**Review by owensmallwood — APPROVED** [review]

**Comment by evictorero** [comment]
I am wondering if these should be underlined or colored or with an icon button like other links.
Also this PR seems to address the productBoard issue but the issue related suggests also we should add a link to the name of the plugin.

**Comment by leandro-deveikis** [comment]
Thanks for the feedback. 
I actually tried with different color, but it didn't look ok to me. Also, those links are a dynamic list from the plugin config. Those are not the same for every plugin. So it would be difficult to set an icon for them. 

As for the title, I forgot to mention on the issue, but the title is a link to the same page the user is on, dont really know why, but it seemed not worth it.

**Comment by leandro-deveikis** [comment]
image

Due to @evictorero feedback, I changed it like the image above

**Comment by leandro-deveikis** [comment]
Thanks to @evictorero feedback I am about to change it like this:

image


@owensmallwood do you agree this is better?

**Comment by owensmallwood** [comment]
@leandro-deveikis Yeah that looks a little nicer 👍

**Review by evictorero — APPROVED** [review]

**Pull request merged**
