### PR TITLE
Fix CircleCI config syntax

### PR DESCRIPTION
**Pull request by simPod**
**What this PR does / why we need it**:

The syntax was invalid

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
How is the syntax wrong? To me it doesn't look as if you're fixing anything. I can only see whitespace changes and removing curly braces from shell variable expansions (which shouldn't be a good change).

**Comment by simPod** [comment]
Whitespace changes are significant in YAML. The whitespace indent is invalid and won't run in CircleCI (syntax error).

The same applies for `"${` combination.

After this change CI runs. Before it does not because of invalid syntax. CircleCI cannot parse it.

**Comment by simPod** [comment]
https://app.circleci.com/pipelines/github/simPod/GrafanaJsonDatasource/171/workflows/2c908635-0af6-4def-8963-9f03ff883a57/jobs/358

**Comment by aknuds1** [comment]
> Whitespace changes are significant in YAML. The whitespace indent is invalid and won't run in CircleCI (syntax error).

Yeah I know whitespace is significant in YAML, but bad indentation can be difficult to spot. I see the problem you're fixing now, thanks.

> The same applies for `"${` combination.

Are you sure `${}` is a syntax problem in this YAML? I see you removed those changes in the meantime?

**Comment by aknuds1** [comment]
@srclosson Can you review this? I don't work on this CircleCI logic.

**Comment by simPod** [comment]
@aknuds1 

> Are you sure ${} is a syntax problem in this YAML?

no, seems insignificant. I must have misinterpreted something CircleCI tried to say to me. Nvm. Only indentation change matters here.

**Review by dprokop — APPROVED** [review]
This looks good to me, but let's see what @srclosson says :)

**Review by srclosson — APPROVED** [review]
Yes, looks fine to me too. We don't really use this circleci config anymore. It's a long story, and frankly I suspect a lot of this can be cleaned out since we are moving to drone in enterprise plugins eventually anyway. It does make me wonder though, if this needed to get fixed, who's using it?

**Comment by simPod** [comment]
I'm using it for building my plug-in. Is there better way now?

**Comment by srclosson** [comment]
Not right now. Go ahead and keep using it so long as it's working for you. There is no intent to update it anymore though. Heads up.

**Comment by simPod** [comment]
Just FYI I used the grafana toolkit command to update the CircleCI definition.

**Pull request closed without merging**
