### PR TITLE
@grafana/ui: Create Icon component and replace icons

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR creates a new icon component and replaces some of the icons in Grafana.
https://github.com/grafana/grafana/pull/23197
https://github.com/grafana/grafana/pull/23266
https://github.com/grafana/grafana/pull/23356

PR was failing on publish storybook due to Javascript heap out of memory. This [PR](https://github.com/grafana/grafana/pull/23402/commits/96a1def58d910b8c5d8c48d4f0c603b0a202bdb0) adjusting TerserPlugin sourceMap to false to prevent running out of memory fixed the problem.

### CODE REVIEW

**Review by kylebrandt — COMMENTED** [review]
For the backend Go code. It would be a bit cleaner I think to make an `icon` package or something like that, and then export constants for each icon.

Then something like:

```go
Icon:       "bell",
```

becomes

```go
Icon:       icon.Bell,
```

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
* If I edit a dashlist panel it crashes / becomes empty 
* The info icons are positioned wrong in gf-form  labels image

The dashboard toolbar buttons are much worse / harder to read in this branch
image

Not sure if it's the size or the icons that make the current icons look so much clearer 
image

**Comment by torkelo** [comment]
Alert State history is not showing any icon
image

**Comment by torkelo** [comment]
Also I think we can skip the big monochrome versions for now, they are not working

**Comment by torkelo** [comment]
For the add panel icon I would like to keep our current icon, think it's much better: 
image

image

**Comment by torkelo** [comment]
> If I edit a dashlist panel it crashes / becomes empty

This is a bug in master as well, so not related to this PR

**Comment by ivanahuckova** [comment]
@torkelo 
1. I have updated the size of dashnav icons, which I think helps a lot. 
2. Secondly, what do you think about monochrome add panel icon? I
image
image
3. Alerting icons fixed
image
4. Big monochrome icons skipped
image

**Comment by torkelo** [comment]
The dash nav button now look much better!

But still prefer our current add panel icon

**Comment by ivanahuckova** [comment]
@torkelo 
image

**Review by torkelo — APPROVED** [review]

**Pull request merged**
