### PR TITLE
Alerting: correct property names for Slack bot icons

### PR DESCRIPTION
**Pull request by ChipWolf**
**What this PR does / why we need it**: The identifiers for the Slack notifier's icon URL and icon emoji properties didn't match the tests or the logic in the notifier. This change seeks to remediate this issue which currently renders the two optional settings inoperable.

### CODE REVIEW

**Comment by ChipWolf** [comment]
It's a shame the tests don't pick up on this type of issue, perhaps there's a more intelligent way to enumerate through the properties in the notifiers from the test logic.

**Review by dsotirakis — APPROVED** [review]
Good catch, thanks @ChipWolf

**Comment by daniellee** [comment]
@dsotirakis is this good to merge?

**Comment by dsotirakis** [comment]
Yep, didn't merge since we were considering using the new Slack API version which already solved the issue, but it's good to have it for backport compatibility. Thanks for reminding me @daniellee!

**Pull request merged**
