### PR TITLE
Design System: Improve a11y of ConfirmModal

### LINKED ISSUE #66046: ID 256053: [Programmatic Access - Simon - Delete]: Visual label and aria label is not same for 'Yes' button under "delete' pop up.
### **User Experience:** 
Visually impaired users who depend on screen readers will get disoriented and will face difficulty in understanding the control if correct `aria-label` will not be defined for the controls. 
_Note: User credentials should NOT be included in the bug._

### **Repro Steps:**

1. Open #Url: [play.grafana.org](https://play.grafana.org/). 
2. Sign in with valid credentials. "Home" page appears. 
3. Navigate the Feature Showcase pane. Select any one of the data such as ,"Time Series Graphs". 
4. "Visualizations" page opens. Navigate to the "Soft Min Max" pane and expand it. 
5. Select the "Delete" button. Navigate the "Delete Row" pop-up. 
6. Turn on narrator. Verify the issue.

**Actual Result:** 
Issue: Visual label and `aria-label` is not same for 'Yes' button under "delete' pop up. 

**Observation:** 
Screen reader is reading 'Confirm modal danger button' when `focus` moves on yes button.

**Expected Result:**
Solution: Visual label and `aria-label` should be same as 'Yes' for 'Yes' button under "delete' pop up. Example: Screen reader should read as 'Yes' button.

_Note: The same issue exists with NVDA and JAWS. Same issue appears for Library Panels->Create New Panel->Save folder Same issue exists with Feature showcases->edit->dashboard list->Library Panels->filtered data->Replace with library panel->Replace._

### **Severity:**
`SEV2`

### **Area:**
`Confirm Modal` (Saga Design System)

### PR DESCRIPTION
**Pull request by L-M-K-B**
Fixes #66046

My goal was it to make the screenreader read the description of the modal in order to enable users to decide on all the important information. I also tried `aria-labeledby` and `aria-describedby` which didn't lead to the right effect. That's why I decided to use `aria-live="polite"` although it doesn't seem to be the right property according to the use cases in it's documentation.

**How to test it:**
1. Open localhost:3000
2. Navigate to an existing dashboard
3. Add a row by using the _Add_ dropdown in the header
4. Navigate to the _delete_ button in the row header and open the _Delete row_ modal
5. Check what the screen reader tells users when opening the modal and navigating to different buttons

### CODE REVIEW

**Comment by L-M-K-B** [comment]
@ashharrison90 You converted the aria-label to the test id which makes absolutely sense. What I did here additionally is to enable the screen reader to read the modal's description because getting the button content only doesn't enable the users to make an informed decision.
What do you think?

**Comment by ashharrison90** [comment]
yeah i'm also not sure. https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/ suggests using `aria-describedby`... if we were to use that we should be doing it in our generic `Modal` component tho. something like setting an `id` on the children element and setting `aria-describedby={id}` where `overlayProps`/`dialogProps` are. **but** then we run into the issue that we don't have a dedicated section in the modal for actions and they're instead included in the children, and so read out by `aria-describedby`... 

image

all a bit messy tbh 😬

**Comment by L-M-K-B** [comment]
It is, that's why I added `aria-live="polite"` in the first place but I will look into whether it works when I set `aria-describedby=""` in the Modal component. That's what I didn't try yet.

**Comment by L-M-K-B** [comment]
There are plenty of issues that are related to Modal and ConfirmModal. Since the solution in this PR doesn't cover the general a11y issue with Modal I'm closing it.
In order to find a more general solution I opened a dedicated issue for it: https://github.com/grafana/grafana/issues/67297
The epic summarising all a11y issue with modal can be found here: https://github.com/grafana/grafana/issues/67302

**Pull request closed without merging**
