### PR TITLE
Auth: Custom oauth provider denied login error message

### LINKED ISSUE #88031: OAUTH provider denied login custom message
**Why is this needed**:

For high skilled people, the current behavior is enough to understand what to do, but for my hundreds of business people, they open an IT ticket instead of requesting access on the tooling to request access.

**What would you like to be added**:
A way to customize the following error: "login provider denied login request"

**Who is this feature for?**

Server Administrators with Oauth Provider where Oauth Provider does Authentication AND Authorization before redirecting to Grafana

### PR DESCRIPTION
**Pull request by EvertonSA**
**What is this feature?**

This PR will allow Grafana server administrators to configure the message showed back to the user when Oauth provider denies the login. For high skilled people, the current behavior is enough to understand what to do, but for my hundreds of business people, they open an IT ticket instead of self requesting access on SailPoint. 

image

**Why do we need this feature?**

This will enhance Grafana user experience on errors not caused by Grafana.

**Who is this feature for?**

Server Administrators 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/88031

**Special notes for your reviewer:**

I'm very new at golang, please take this into account.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by tskarhed** [comment]
There is another issue about this [#84639](https://github.com/grafana/grafana/issues/84639)

**Comment by wardbekker** [comment]
Thank you @EvertonSA I've brought this under the attention of engineering

**Comment by kalleep** [comment]
Hey, tanks for taking the time to make this contribution. 

While I agree that `login provider denied login request` is not a great error message I am not a fan of having this config option but would rather change this to a more user friendly message in general. Can I ask what you had plan to set this message as?

**Comment by EvertonSA** [comment]
> Hey, tanks for taking the time to make this contribution.
> 
> While I agree that `login provider denied login request` is not a great error message I am not a fan of having this config option but would rather change this to a more user friendly message in general. Can I ask what you had plan to set this message as?

In my case, I need somehthing like "You are not authorized based on your SailPoint entitlements. Please open SailPoint portal and request xxxxxx. Access this link if you need more information zzzzz".

The part of accessing the link is not required, but it would be nice to allow to add a link to my internal company confluence.

**Comment by EvertonSA** [comment]
Hi @kalleep would you be willing to accept this as a low hanging fruit for 11.1? I see this being very very useful with new grafana oidc organization mapping that is coming on 11.1

**Comment by EvertonSA** [comment]
any feedback is appreciated. closing this is also ok.

**Comment by EvertonSA** [comment]
I'm leaving my employer and I am not taking any further action here, thanks anyway.

**Pull request closed without merging**
