### PR TITLE
Adds a description field to plugin.json's pages:role field

### PR DESCRIPTION
**Pull request by joeblubaugh**
There's no description of what a page object's "role" setting does. It controls whether a page will appear in the navigation menu for a user with a given role.

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]

**Review by marefr — CHANGES_REQUESTED** [review]
Please also update https://github.com/grafana/grafana/blob/66b54e2dbd10fd399e2034b3367bbb579b8a0635/pkg/plugins/plugindef/plugindef.cue#L110-L111

**Review by mckn — COMMENTED** [review]
Great initiative! As @marefr said. Please update the schema so they are in sync. We will start to generate the plugin.json from the schema in a not to distant future.

**Review by marefr — APPROVED** [review]
LGTM, but you need to run `make gen-cue` to generate code as well

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by joeblubaugh** [comment]
@marefr @mckn would one of you merge this when it goes green? I'm not in the requisite groups to merge grafana/grafana

**Pull request merged**
