### PR TITLE
DevEnv: update frontend dependencies

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 9 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Did not update:
- `sass-lint` 1.12.1 -> 1.13.1 because they are almost identical, 1.13.1 is a revert to 1.12.1 from 1.13.0 that included a lot of breaking changes. https://github.com/sasstools/sass-lint/releases

Changes - DEV dependencies:

More significant:
- `css-loader` - changes (2.1.1 -> 3.4.2): https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md
- `enzyme` - changes (3.9.0 -> 3.11.0): https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md
- `enzyme-to-json` - changes (3.3.5 -> 3.4.4): https://github.com/adriantoine/enzyme-to-json/releases
- `file-loader` - changes (3.0.1 -> 5.0.2): https://github.com/webpack-contrib/file-loader/blob/master/CHANGELOG.md
- `fork-ts-checker-webpack-plugin` - changes (1.0.0 -> 4.0.3): https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases
- `husky` - changes (1.3.1 -> 4.2.1): https://github.com/typicode/husky/blob/master/CHANGELOG.md & https://github.com/typicode/husky/releases
- `jest` - changes (24.8.0 -> 25.1.0): https://github.com/facebook/jest/blob/master/CHANGELOG.md
- `lint-staged` - changes (8.1.5 -> 10.0.7): https://github.com/okonet/lint-staged/releases
- `mocha` - changes (4.1.0 -> 7.0.1): https://github.com/mochajs/mocha/blob/master/CHANGELOG.md
- `node-sass` - changes (4.12.0 -> 4.13.1): https://github.com/sass/node-sass/releases
- `puppeteer-core` - changes (1.15.0 -> 2.1.1): https://github.com/puppeteer/puppeteer/releases
- `sass-loader` - changes (7.1.0 -> 8.0.2): https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md
- `sinon` - changes (1.17.6 -> 8.1.1): https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md
- `style-loader` - changes (0.23.1 -> 1.1.3): https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md
- `terser-webpack-plugin` - changes (1.2.3 -> 2.3.4): https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/CHANGELOG.md

Less significant:
- `@emotion/core` - changes (mostly small, 10.0.10 -> 10.0.27): https://github.com/emotion-js/emotion/blob/master/packages/core/CHANGELOG.md
- `autoprefixer` - changes (9.5.0 -> 9.7.4): https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md
- `es6-promise` - changes (3.3.1 -> 4.2.8): https://github.com/stefanpenner/es6-promise/blob/master/CHANGELOG.md
- `expect-puppeteer` - changes (4.1.1 -> 4.4.0): https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/CHANGELOG.md
- `grunt` - changes (1.0.1 -> 1.0.4): https://github.com/gruntjs/grunt/blob/master/CHANGELOG
- `grunt-cli` - changes (1.2.0 -> 1.3.2): https://github.com/gruntjs/grunt-cli/blob/master/CHANGELOG.md
- `grunt-contrib-clean` - changes (1.0.0 -> 2.0.0): https://github.com/gruntjs/grunt-contrib-clean/blob/master/CHANGELOG
- `lerna` - changes (3.15.0 -> 3.20.2): https://github.com/lerna/lerna/blob/master/CHANGELOG.md
- `load-grunt-tasks` - changes (3.5.2 -> 5.1.0): https://github.com/sindresorhus/load-grunt-tasks/releases
- `pixelmatch` - changes (4.0.2 -> 5.1.0): https://github.com/mapbox/pixelmatch/releases
- `react-hot-loader` - changes (4.8.0 -> 4.12.9): https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md
- `rimraf` - changes (2.6.3 -> 3.0.1): https://github.com/isaacs/rimraf/blob/master/CHANGELOG.md
- `ts-node` - changes (8.5.0 -> 8.6.2): https://github.com/TypeStrong/ts-node/releases
- `webpack` - changes (4.29.6 -> 4.41.5): https://github.com/webpack/webpack/releases
- `webpack-cli` - changes (3.2.3 -> 3.3.10): https://github.com/webpack/webpack-cli/releases
- `webpack-dev-server` - changes (3.2.1 -> 3.10.3): https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md

Changes - dependencies:

More significant:
- `angular` - changes (1.6.9 -> 1.7.9): https://github.com/angular/angular.js/blob/master/CHANGELOG.md
- `nodemon` - changes (1.18.10 -> 2.0.2): https://github.com/remy/nodemon/releases
- `react-transition-group` - changes (2.6.1 -> 4.3.0): https://github.com/reactjs/react-transition-group/releases

Less significant:
- `eventemitter3` - changes (2.0.3 -> 4.0.0): https://github.com/primus/eventemitter3/releases
- `file-saver` - changes (1.3.8 -> 2.0.2): https://github.com/eligrey/FileSaver.js/releases
- `react-use` - changes (12.8.0 -> 13.24.0): https://github.com/streamich/react-use/releases

### CODE REVIEW

**Comment by Estrax** [comment]
Still a lot of work remaining - few small csv issues, then some work needed to get it all within the limit of strict errors.

**Comment by ryantxu** [comment]
are you trying to update all deps in one go?  It may be a better approach to tackle that in steps.. ie, updating all the react libs is a very different issue than some of the less often used ones

**Comment by ryantxu** [comment]
and things like upgrading slate should *for sure* be in their own issue and get extra/explicit review

**Comment by ryantxu** [comment]
I would strongly recommend trying this in a few batches.

Also note, the angular 1.6.9 -> 1.7.9 is a BIG change that is likely not worth trying

**Comment by Estrax** [comment]
@ryantxu no, no no - it's not going to be one big PR with all deps update in one go. It's just a draft PR, made only to aggregate all the notable changes in the packages in one place, so we can discuss it with the frontend platform team and decide which one we go forward with and which one we don't want to update (e.g. angular 1.6.9 -> 1.7.9 that's a pretty big update and probably not worth our time considering our rewrite from angular to react).

It's going to be split to small PRs with at most few packages updated in one batch and a proper description to make it all easier.

**Comment by Estrax** [comment]
Comment to keep the track of deps update.

Yet to be updated, other ones are in progress:
- `@types/react-select`
- `@types/slate`
- `@types/slate-plain-serializer`
- `@types/slate-react`

Not to be updated:
- `@types/angular`
- `angular`
- `angular-route`
- `angular-sanitize`
- `angular-mocks`
- `grunt-angular-templates`

**Comment by torkelo** [comment]
Closing this as we have to do this in smaller chunks

**Pull request closed without merging**
