### PR TITLE
Navigation: Add responsive behaviour to `ToolbarButtonRow`

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- Adds responsive behaviour to `ToolbarButtonRow`
- this uses `IntersectionObserver` to check when child elements intersect with the parent container
- when a child element overflows the container we set `visibility: hidden;` and render them in a clickable overflow container showing these children
- any hidden children are still in the dom, but not interactable/tabbable. in fact they need to be there so the `InteractionObserver` will still monitor them. when we drag the window big enough such that one of the hidden children no longer overflows, the `InteractionObserver` fires again and we can remove it from the overflow menu and readd it to the visible children.

# main, no toggle
https://user-images.githubusercontent.com/20999846/184648938-7e30cd6c-faec-4f03-9709-5bd1814f8019.mp4

# this branch, no toggle
https://user-images.githubusercontent.com/20999846/185906138-db307faf-e45f-40b9-8ba8-3c1d718e1648.mp4

# main, `topnav`
https://user-images.githubusercontent.com/20999846/184648947-ce5a31db-d767-44d9-b78d-18bf4d53774f.mp4

# this branch, `topnav`
https://user-images.githubusercontent.com/20999846/185906188-ea1ecf1a-c182-4146-ab00-2b9b5d28a24a.mp4

**Which issue(s) this PR fixes**:

For https://github.com/grafana/grafana/issues/53592

**Special notes for your reviewer**:

there's still some tidy up to do, but i'd like to get some feedback before i dive too much into it.

questions: 
- do we like this behaviour?
- should this logic live in `ToolbarButtonRow`, or should we create a new component to manage it?
- currently there are 2 alignment options: `left` and `right`. when `left` aligned, children are removed from right to left. when `right` aligned, children are removed from `left` to `right`. are we happy with that? i **think** most places put their most important buttons on the LHS so it might be a bit weird for them to be removed first. 😕 we could probably fix that behaviour, but it would make the logic a bit trickier to follow.

### CODE REVIEW

**Comment by torkelo** [comment]
This is looking great! 

Seems to be some issues with the time picker popover, it hides very easily by hovering out of the timepicker button or dropdown area, could be tricky to solve though

**Comment by ashharrison90** [comment]
> This is looking great! Amazing work ❤️ !
> 
> Seems to be some issues with the time picker popover, it hides very easily by hovering out of the timepicker button or dropdown area, could be tricky to solve though

@torkelo yeah it's a little tricky... there's a few issues:
- events that bubble up to `Dropdown` trigger the `onOverlayClicked` function which closes the overlay, so parts of the time picker are unusable atm
  - think this is an easy(ish) fix of just making sure we stop propagating certain events in the time picker
- `Dropdown` has `delayHide=0`, so it's a little unforgiving when the mouse accidentally leaves the overlay area.
  - again, probably quite easy to just add `delayHide=200` or something.
- items that have a tooltip (e.g. the timepicker button)... when hovering the tooltip it counts as being outside of the overlay, so closes the overlay.
- `Dropdown` uses a portal which has a higher z-index than modals. this one is the trickiest...
  - at smaller screen sizes, the calendar in the timepicker appears in a modal.
  - so either the dropdown overlay sits on top of the modal backdrop, which looks weird, or we override the z-index... **but** anything that overlays the tooltip (e.g. a modal...) causes the tooltip to close. that makes sense for a normal tooltip, but this isn't really a _normal_ tooltip... maybe that means i'm trying to use the wrong component here? 🤔

**Comment by lpskdl** [comment]
Hi @ashharrison90 ,
Great Work!. Please find my feedback below:

> should this logic live in ToolbarButtonRow, or should we create a new component to manage it?

I don't have a strong opinion about it, we can lift it up somewhere until we find a reason to reuse it.

> About the alignment

my personal opinion the first time I run the app, I thought it is hiding the item always from right to left because that is what I used to have where my most important items were always placed from left to right. But it could be different from people who used to have RTL orientation like from `IL`. 


I like the behaviour overall. Great Job! However, I have a small comment about the toolbar, Should we display the time picker in mobile view? 

Screenshot 2022-08-22 at 09 43 37

**Comment by ashharrison90** [comment]
@torkelo @lpskdl have updated with some tweaks. here's a summary:
- stopped using `Dropdown` to show the overflow items, handled the state manually instead
  - think this alleviates pretty much all the problems with interacting with some of the overflow buttons
- added an active state to the overflow button
- added some basic documentation to the storybook

@lpskdl i agree about the order of the buttons being removed... can't find a nice way to do it at the moment unfortunately. open to suggestions if anyone has an idea 💡 an alternative could be to swap the order of those buttons such that the most important buttons are always on the RHS, then they'd be removed last? not overly in love with that idea either though. 🤔

**Comment by lpskdl** [comment]
Hey @ashharrison90 ,

I've tested the changes from my side and looks good.

**Review by torkelo — APPROVED** [review]
Took this for another spin and it works really great! Feels great! 

I think the responsive rule we have to breadcrumbs (not related to this I know) needs more work, just hiding all but the last feels too crude.

**Pull request merged**
