### PR TITLE
Build: Enable persistent cache for faster Webpack builds

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
This PR introduces Webpack persistent cache to both development and production builds to speed up local FE builds. It also adds typescript incremental mode to cache typechecks and lastly adds a parameter to the webpack production build config so devs can disable minification (@leeoniya I seem to recall you asked for this a little while ago?).

### Cold start without cache

```
yarn start

SASS variable files generated
assets by status 64.6 KiB [cached] 2 assets
assets by path *.js 119 MiB 191 assets
assets by path ../ 17 MiB
  assets by path ../lib/monaco/min/vs/basic-languages/ 409 KiB 73 assets
  assets by path ../lib/monaco/min/vs/language/ 12.4 MiB 17 assets
  assets by path ../lib/monaco/min/vs/editor/ 3.85 MiB 12 assets
  assets by status 12.1 KiB [emitted] 2 assets
  assets by path ../lib/monaco/min/vs/base/ 242 KiB
    asset ../lib/monaco/min/vs/base/worker/workerMain.js 177 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/base/worker/workerMain.js] [copied]
    asset ../lib/monaco/min/vs/base/browser/ui/codicons/codicon/codicon.ttf 64.5 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf] [copied]
  asset ../lib/monaco/min/vs/loader.js 31.4 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/loader.js] [copied]
assets by path *.css 557 KiB
  asset grafana.dark.148443320d1bd72dcf9c.css 279 KiB [emitted] [immutable] (name: dark)
  asset grafana.light.148443320d1bd72dcf9c.css 278 KiB [emitted] [immutable] (name: light)
Entrypoint app 52.1 MiB = runtime~app.js 33.1 KiB app.js 52.1 MiB
Entrypoint dark 292 KiB = runtime~dark.js 11.8 KiB grafana.dark.148443320d1bd72dcf9c.css 279 KiB dark.js 941 bytes
Entrypoint light 291 KiB = runtime~light.js 11.8 KiB grafana.light.148443320d1bd72dcf9c.css 278 KiB light.js 948 bytes
orphan modules 2.89 MiB (javascript) 937 bytes (runtime) [orphan] 471 modules
runtime modules 15.5 KiB 31 modules
modules by path ./.yarn/ 27.1 MiB (javascript) 18.8 KiB (css/mini-extract) 75 bytes (asset)
  modules by path ./.yarn/cache/ 21.8 MiB (javascript) 2.08 KiB (css/mini-extract) 75 bytes (asset) 2853 modules
  modules by path ./.yarn/__virtual__/ 5.07 MiB (javascript) 16.7 KiB (css/mini-extract) 468 modules
  modules by path ./.yarn/unplugged/ 235 KiB 332 modules
modules by path ./public/ 6.26 MiB (javascript) 519 KiB (css/mini-extract) 1993 modules
modules by path ./packages/ 1.76 MiB 659 modules
modules by path data:image/ 4.01 KiB
  data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTMiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCA1MyAzNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4NCjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMCkiPg0KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00OC4wMzY0IDQuMDEwNDJINC4wMDc3OUw0LjAwNzc5IDMyLjAyODZINDguMDM2NFY0LjAxMDQyWk00LjAwNzc5IDAuMDA3ODEyNUMxLjc5NzIxIDAuMDA3ODEyNSAwLjAwNTE4Nzk5IDEuNzk5ODQgMC4wMDUxODc5OSA0LjAxMDQyVjMyLjAyODZDMC4wMDUxODc5OSAzNC4yMzkyIDEuNzk3MjEgMzYuMDMxMiA0LjAwNzc5IDM2LjAzMTJINDguMDM2NEM1MC4yNDcgMzYuMDMxMiA1Mi4wMzkgMzQuMjM5MiA1Mi4wMzkgMzIuMDI4NlY0LjAxMDQyQzUyLjAzOSAxLjc5OTg0IDUwLjI0NyAwLjAwNzgxMjUgNDguMDM2NCAwLjAwNzgxMjVINC4wMDc3OVpNOC4wMTA0MiA4LjAxMzAySDEyLjAxM1YxMi4wMTU2SDguMDEwNDJWOC4wMTMwMlpNMjAuMDE4MiA4LjAxMzAySDE2LjAxNTZWMTIuMDE1NkgyMC4wMTgyVjguMDEzMDJaTTI0LjAyMDggOC4wMTMwMkgyOC4wMjM0VjEyLjAxNTZIMjQuMDIwOFY4LjAxMzAyWk0zNi4wMjg2IDguMDEzMDJIMzIuMDI2VjEyLjAxNTZIMzYuMDI4NlY4LjAxMzAyWk00MC4wMzEyIDguMDEzMDJINDQuMDMzOVYxMi4wMTU2SDQwLjAzMTJWOC4wMTMwMlpNMTYuMDE1NiAxNi4wMTgySDguMDEwNDJWMjAuMDIwOEgxNi4wMTU2VjE2LjAxODJaTTIwLjAxODIgMTYuMDE4MkgyNC4wMjA4VjIwLjAyMDhIMjAuMDE4MlYxNi4wMTgyWk0zMi4wMjYgMTYuMDE4MkgyOC4wMjM0VjIwLjAyMDhIMzIuMDI2VjE2LjAxODJaTTQ0LjAzMzkgMTYuMDE4MlYyMC4wMjA4SDM2LjAyODZWMTYuMDE4Mkg0NC4wMzM5Wk0xMi4wMTMgMjQuMDIzNEg4LjAxMDQyVjI4LjAyNkgxMi4wMTNWMjQuMDIzNFpNMTYuMDE1NiAyNC4wMjM0SDM2LjAyODZWMjguMDI2SDE2LjAxNTZWMjQuMDIzNFpNNDQuMDMzOSAyNC4wMjM0SDQwLjAzMTJWMjguMDI2SDQ0LjAzMzlWMjQuMDIzNFoiIGZpbGw9IiM0MjQyNDIiLz4NCjwvZz4NCjxkZWZzPg0KPGNsaXBQYXRoIGlkPSJjbGlwMCI+DQo8cmVjdCB3aWR0aD0iNTMiIGhlaWdodD0iMzYiIGZpbGw9IndoaXRlIi8+DQo8L2NsaXBQYXRoPg0KPC9kZWZzPg0KPC9zdmc+DQo= 1.6 KiB [built] [code generated]
  data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTMiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCA1MyAzNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4NCjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMCkiPg0KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00OC4wMzY0IDQuMDEwNDJINC4wMDc3OUw0LjAwNzc5IDMyLjAyODZINDguMDM2NFY0LjAxMDQyWk00LjAwNzc5IDAuMDA3ODEyNUMxLjc5NzIxIDAuMDA3ODEyNSAwLjAwNTE4Nzk5IDEuNzk5ODQgMC4wMDUxODc5OSA0LjAxMDQyVjMyLjAyODZDMC4wMDUxODc5OSAzNC4yMzkyIDEuNzk3MjEgMzYuMDMxMiA0LjAwNzc5IDM2LjAzMTJINDguMDM2NEM1MC4yNDcgMzYuMDMxMiA1Mi4wMzkgMzQuMjM5MiA1Mi4wMzkgMzIuMDI4NlY0LjAxMDQyQzUyLjAzOSAxLjc5OTg0IDUwLjI0NyAwLjAwNzgxMjUgNDguMDM2NCAwLjAwNzgxMjVINC4wMDc3OVpNOC4wMTA0MiA4LjAxMzAySDEyLjAxM1YxMi4wMTU2SDguMDEwNDJWOC4wMTMwMlpNMjAuMDE4MiA4LjAxMzAySDE2LjAxNTZWMTIuMDE1NkgyMC4wMTgyVjguMDEzMDJaTTI0LjAyMDggOC4wMTMwMkgyOC4wMjM0VjEyLjAxNTZIMjQuMDIwOFY4LjAxMzAyWk0zNi4wMjg2IDguMDEzMDJIMzIuMDI2VjEyLjAxNTZIMzYuMDI4NlY4LjAxMzAyWk00MC4wMzEyIDguMDEzMDJINDQuMDMzOVYxMi4wMTU2SDQwLjAzMTJWOC4wMTMwMlpNMTYuMDE1NiAxNi4wMTgySDguMDEwNDJWMjAuMDIwOEgxNi4wMTU2VjE2LjAxODJaTTIwLjAxODIgMTYuMDE4MkgyNC4wMjA4VjIwLjAyMDhIMjAuMDE4MlYxNi4wMTgyWk0zMi4wMjYgMTYuMDE4MkgyOC4wMjM0VjIwLjAyMDhIMzIuMDI2VjE2LjAxODJaTTQ0LjAzMzkgMTYuMDE4MlYyMC4wMjA4SDM2LjAyODZWMTYuMDE4Mkg0NC4wMzM5Wk0xMi4wMTMgMjQuMDIzNEg4LjAxMDQyVjI4LjAyNkgxMi4wMTNWMjQuMDIzNFpNMTYuMDE1NiAyNC4wMjM0SDM2LjAyODZWMjguMDI2SDE2LjAxNTZWMjQuMDIzNFpNNDQuMDMzOSAyNC4wMjM0SDQwLjAzMTJWMjguMDI2SDQ0LjAzMzlWMjQuMDIzNFoiIGZpbGw9IiNDNUM1QzUiLz4NCjwvZz4NCjxkZWZzPg0KPGNsaXBQYXRoIGlkPSJjbGlwMCI+DQo8cmVjdCB3aWR0aD0iNTMiIGhlaWdodD0iMzYiIGZpbGw9IndoaXRlIi8+DQo8L2NsaXBQYXRoPg0KPC9kZWZzPg0KPC9zdmc+DQo= 1.6 KiB [built] [code generated]
  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII= 175 bytes [built] [code generated]
  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAz0lEQVRIx2NgYGBY/R8I/vx5eelX3n82IJ9FxGf6tksvf/8FiTMQAcAGQMDvSwu09abffY8QYSAScNk45G198eX//yev73/4///701eh//kZSARckrNBRvz//+8+6ZohwCzjGNjdgQxkAg7B9WADeBjIBqtJCbhRA0YNoIkBSNmaPEMoNmA0FkYNoFKhapJ6FGyAH3nauaSmPfwI0v/3OukVi0CIZ+F25KrtYcx/CTIy0e+rC7R1Z4KMICVTQQ14feVXIbR695u14+Ir4gwAAD49E54wc1kWAAAAAElFTkSuQmCC 390 bytes [built] [code generated]
  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMTZEaa/1AAAAHUlEQVQYV2PYvXu3JAi7uLiAMaYAjAGTQBPYLQkAa/0Zef3qRswAAAAASUVORK5CYII= 268 bytes [built] [code generated]
7 modules
webpack 5.58.1 compiled successfully in 32870 ms

```

### Cold start with cache

```
yarn start

SASS variable files generated
assets by status 64.6 KiB [cached] 2 assets
assets by path *.js 119 MiB 191 assets
assets by path ../ 17 MiB
  assets by path ../lib/monaco/min/vs/basic-languages/ 409 KiB 73 assets
  assets by path ../lib/monaco/min/vs/language/ 12.4 MiB 17 assets
  assets by path ../lib/monaco/min/vs/editor/ 3.85 MiB 12 assets
  assets by status 12.2 KiB [emitted] 2 assets
  assets by path ../lib/monaco/min/vs/base/ 242 KiB
    asset ../lib/monaco/min/vs/base/worker/workerMain.js 177 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/base/worker/workerMain.js] [copied]
    asset ../lib/monaco/min/vs/base/browser/ui/codicons/codicon/codicon.ttf 64.5 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf] [copied]
  asset ../lib/monaco/min/vs/loader.js 31.4 KiB [compared for emit] [from: .yarn/cache/monaco-editor-npm-0.27.0-35ef31e333-766ce20ea6.zip/node_modules/monaco-editor/min/vs/loader.js] [copied]
assets by path *.css 557 KiB
  asset grafana.dark.2f8b8930aec406fa4a50.css 279 KiB [emitted] [immutable] (name: dark)
  asset grafana.light.2f8b8930aec406fa4a50.css 278 KiB [emitted] [immutable] (name: light)
Entrypoint app 52.1 MiB = runtime~app.js 33.1 KiB app.js 52.1 MiB
Entrypoint dark 292 KiB = runtime~dark.js 11.8 KiB grafana.dark.2f8b8930aec406fa4a50.css 279 KiB dark.js 941 bytes
Entrypoint light 291 KiB = runtime~light.js 11.8 KiB grafana.light.2f8b8930aec406fa4a50.css 278 KiB light.js 948 bytes
cached modules 37.3 MiB (javascript) 75 bytes (asset) 7.33 KiB (runtime) [cached] 7132 modules
runtime modules 9.05 KiB 19 modules
orphan modules 563 KiB [orphan] 2 modules
built modules 538 KiB (css/mini-extract) 118 KiB (javascript) [built]
  css modules 538 KiB
    modules by path ./.yarn/ 18.8 KiB 6 modules
    modules by path ./public/sass/*.scss 519 KiB
      css ./.yarn/__virtual__/css-loader-virtual-2a8b0f4666/0/cache/css-loader-npm-6.4.0-b541b3e985-e842905fce.zip/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./.yarn/__virtual__/postcss-loader-virtual-6b0514ff7d/0/cache/postcss-loader-npm-6.1.1-cf5e0f6586-3c32d12381.zip/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./.yarn/__virtual__/sass-loader-virtual-758cfb7ed2/0/cache/sass-loader-npm-12.1.0-6188089e12-69c66ea348.zip/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!./public/sass/grafana.dark.scss 260 KiB [built]
      css ./.yarn/__virtual__/css-loader-virtual-2a8b0f4666/0/cache/css-loader-npm-6.4.0-b541b3e985-e842905fce.zip/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./.yarn/__virtual__/postcss-loader-virtual-6b0514ff7d/0/cache/postcss-loader-npm-6.1.1-cf5e0f6586-3c32d12381.zip/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./.yarn/__virtual__/sass-loader-virtual-758cfb7ed2/0/cache/sass-loader-npm-12.1.0-6188089e12-69c66ea348.zip/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!./public/sass/grafana.light.scss 259 KiB [built]
  javascript modules 118 KiB
    ./public/sass/grafana.dark.scss 50 bytes [built]
    ./public/sass/grafana.light.scss 50 bytes [built]
    ./public/app/plugins/panel/nodeGraph/layout.worker.js 118 KiB [not cacheable] [built]
webpack 5.58.1 compiled successfully in 11669 ms

```

**Which issue(s) this PR fixes**:

Related PR #40986

**Special notes for your reviewer**:
Ping @dsotirakis can we investigate the possibility of persisting this webpack production build cache between builds?

### CODE REVIEW

**Comment by leeoniya** [comment]
> adds a parameter to the webpack production build config so devs can disable minification (@leeoniya I seem to recall you asked for this a little while ago?).

:100: :pray:

**Comment by leeoniya** [comment]
i currently use a local repo during dev, is it possible to disable caching for `link:` and `file:` dependencies in `package.json`, or is the caching strategy based on file/package hashes and does not need special treatment?

e.g.

```
"uplot": "link:/home/leeoniya/uPlot/",
```

**Review by torkelo — APPROVED** [review]
This is great!

**Review by kaydelaney — APPROVED** [review]
Love this!

**Comment by jackw** [comment]
> i currently use a local repo during dev, is it possible to disable caching for `link:` and `file:` dependencies in `package.json`, or is the caching strategy based on file/package hashes and does not need special treatment?
> 
> e.g.
> 
> ```
> "uplot": "link:/home/leeoniya/uPlot/",
> ```

Will take a look at this tomorrow before merging @leeoniya . 👍

**Comment by jackw** [comment]
@leeoniya I've taken what I think is your workflow for a spin with this branch and it doesn't look like we need to do anything special for Webpack to invalidate the cache. Details below...

1) Build Grafana in production without minification and caching enabled (`yarn build:nominify`).
2) Use `link:` protocol to point uPlot to a clone for local development.
3) Make changes to uPlot, build uPlot, and build Grafana again (as per step 1).
4) See changes in the browser.

https://user-images.githubusercontent.com/73201/141110454-54741353-eb17-4e2e-8a4e-1ceb3d2ed633.mp4

Let me know if I've missed anything.

**Comment by leeoniya** [comment]
@jackw you nailed it. looks great!

**Pull request merged**
