### PR TITLE
API keys: Return 410 Gone status from POST /auth/keys endpoint

### PR DESCRIPTION
**Pull request by dmihai**
**What is this feature?**

Return 410 Gone status on POST /auth/keys instead of redirecting to the new service accounts endpoint that users should be using instead.

**Why do we need this feature?**

The input for the endpoint on creating a new service account does not match the one for creating a new API key.

**Who is this feature for?**

everybody

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by eleijonmarck** [comment]
@dmihai great one. look at https://github.com/grafana/grafana/pull/92144 for the docs update as well 👍 

Update the docs, and then also (retrigger drone until tests pass) 🗡️

**Review by eleijonmarck — CHANGES_REQUESTED** [review]
just update the docs as well 🦖 , thx for getting this in quick

**Comment by dmihai** [comment]
> just update the docs as well 🦖 , thx for getting this in quick

@eleijonmarck can you please expand on what exactly to update on the docs? The docs already say that the endpoint is obsolete. Also I think we should keep the original input, output and required permissions for people using older versions of Grafana.

**Comment by eleijonmarck** [comment]
@dmihai 
https://github.com/grafana/grafana/pull/92144/files#diff-9dde46df3335d10198c85f8deec03609a43ce526be8a8fafb157568481201252R129

it's really just this line

**Review by eleijonmarck — APPROVED** [review]

**Comment by eleijonmarck** [comment]
💯

**Pull request merged**
