### PR TITLE
Docs: remove checked-in generated package api docs.

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
Since the following PR #27879 will generate the packages documentation from the packages gode when syncing to the website repository we do not need to keep this documentation in the grafana repository.

### CODE REVIEW

**Comment by oddlittlebird** [comment]
Okay, so you're removing the docs, but you still need docs. Where will the documentation live?

**Comment by mckn** [comment]
> Okay, so you're removing the docs, but you still need docs. Where will the documentation live?

They will live in `https://grafana.com/docs/` but instead of having the auto generated docs in this repository we will auto generate them when syncing this docs to the website.

**Comment by oddlittlebird** [comment]
Will the page addresses be the same?

**Comment by mckn** [comment]
> Will the page addresses be the same?

Yes, everything will be exactly the same. The only difference is that we will do this automatically. We will also start to track so we don't add new code without documentation. If anyone will do that we will fail the build so the PR can't be merged.

**Review by oddlittlebird — APPROVED** [review]
Sounds good to me.

**Review by DanCech — APPROVED** [review]

**Review by robbymilo — APPROVED** [review]

**Review by dprokop — APPROVED** [review]
great!

**Pull request merged**
