### PR TITLE
Heatmap panel

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This is heatmap panel implementation. Unit test are in progress. Don't merge before it done, but you can do code review.

### CODE REVIEW

**Comment by torkelo** [comment]
looks really great! 

Found one bug, when you reload the panel in edit mode (so you load directly to edit mode):

You get this error: 

image

I think the color schemes, we need to remove all these color schemes, we only need one I feel. And it needs to be reversed. So that low value count is blue (cold), and high value count is red (heat = high). 

The opacity mode can stay, it looks pretty good when using white theme. 

The tooltip says `values` which is a bit ambiguous. I think `count` makes more sense (since it just just count of values in the bucket, not the a value). And the series stats is also a bit misleading. Maybe counts per series is more clear? 

But overall this looks really great.

**Comment by alexanderzobnin** [comment]
I've fixed that error. Also, CircleCI says tests are failed. But on my side all tests are passed. Is there another reason?

**Comment by alexanderzobnin** [comment]
I also want to decide which options should be set by default. Any ideas (what should we change)?

**Comment by torkelo** [comment]
Not sure, think your current defaults are pretty good. 

I think we can remove most of the color schemes (and invert spectral scheme as it seems to be the wrong way around). 

Great that you added a few unit tests! 
The class that seems best suited for unit test (the data converter) seems to be missing tests however, any plans to add some for this class? Given the data in -> data out scenario this class seems very well suited for for this.

**Comment by alexanderzobnin** [comment]
Yea, data converter should be tested, going to add it after rendering test (it took more time than I expected, unfortunately).

**Comment by torkelo** [comment]
After merge (or if your waiting for feedback), it would be great if you start working on supporting Histogram aggregation with Elasticsearch, and have that work with this panel.

**Pull request merged**
