### PR TITLE
Variables: Removes the never refresh option

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR removes the `never` refresh option for Query variables and `On dashboard load` will be the new default for new Query variables. Old dashboards with query variables that use the `never` refresh option will be migrated and will use `On dashboard load` refresh option instead, and all stored options in the dashboard json will be removed too. 

# Release notice breaking change
Removes the `never` refresh option for Query variables. Existing variables will be migrated and any stored options will be removed.

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
Doc change is good. Will this get mentioned in the changelog/release notes?

**Comment by hugohaggmark** [comment]
> Doc change is good. Will this get mentioned in the changelog/release notes?

Yes it will

**Review by torkelo — APPROVED** [review]
Looks good!

**Comment by linar-jether** [comment]
@hugohaggmark @torkelo What was the reason for removing this? For queries that take a long time to run, this will either cause the dashboard to load very slowly, or force users to run the query externally and save the result as custom constant values.

**Comment by hugohaggmark** [comment]
@linar-jether I think the main reason is to keep the dashboard json small.

**Comment by linar-jether** [comment]
@hugohaggmark Any chance to revert? this is a pretty useful feature

**Comment by hugohaggmark** [comment]
@linar-jether if the negative feedback is overwhelming we always take that into consideration; yes.

**Comment by oddlittlebird** [comment]
Please file an issue if you wish to discuss this further. Merged PRs are not the place for discussions. Thank you!

**Pull request merged**
