### PR TITLE
BarGauge: Fix percentage-based thresholds

### LINKED ISSUE #31756: BarGauge: Gradient mode does not handle percentage based thresholds
**What happened**:

The Bar Gauge and Gauge panels handle threshold percentages differently.

**What you expected to happen**:

The Bar Gauge and Gauge should have consistent behavior, or at least it should be less confusing.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Gauge using a metric where the value is a percentage value (0-1).

image

Change the Gauge to a Bar Gauge and observe the threshold renders completely differently.

image

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: v7.4.3 (010f20c1c8)
- Data source type & version: Bar Gauge (7.4.3), Gauge (7.4.3)
- OS Grafana is installed on: Linux (Kubernetes)
- User OS & Browser: Windows 10 (Chrome)
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes handling of percentage-based thresholds for the BarGauge UI component and panel.

**Which issue(s) this PR fixes**:
Closes #31756

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good!

**Review by thisisobate — APPROVED** [review]
Works as expected!

**Review by jackw — APPROVED** [review]
Awesome work Kay! 👏

**Comment by cyanide-16** [comment]
Hi, I didn't understand how to solve this gradient gauge issue. Can someone help me out please? TIA

**Pull request merged**
