### PR TITLE
Docs: Added $__rate_interval to Prometheus help

### PR DESCRIPTION
**Pull request by dotdc**
The variable '$__rate_interval' was added in Grafana 7.2.0. This commit
adds the missing help information to Grafana's Prometheus PromQueryEditor.

Signed-off-by: David Calvert <davidcalvertfr@gmail.com>

**What this PR does / why we need it**: This will add the '$__rate_interval' variable in the PromQuery Editor help (variable added in 7.2.0)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dotdc** [comment]
Sorry, the CI is failing for some reason. Will try to install a compatible version of yarn to run tests. (yarn > 1.4 on my archlinux setup)

**Comment by dotdc** [comment]
Ok everything seem's fine now.

**Review by zoltanbedi — APPROVED** [review]
Thank you for your contribution @dotdc this looks good to me.

**Review by achatterjee-grafana — APPROVED** [review]
Doc changes look OK. Thank you for your contribution.

**Pull request merged**
