### PR TITLE
CloudWatch: Added missing MemoryDB Namespace metrics

### PR DESCRIPTION
**Pull request by james-deee**
**What this PR does / why we need it**:
Adds Cloudwatch metrics for "AWS/MemoryDB". 

**Special notes for your reviewer**:
Used the following command to get the Metrics and Dimensions:
```
aws cloudwatch list-metrics --namespace "AWS/MemoryDB" --output json | grep MetricName | sort | uniq
            "MetricName": "ActiveDefragHits",
            "MetricName": "AuthenticationFailures",
            "MetricName": "BytesUsedForMemoryDB",
            "MetricName": "CommandAuthorizationFailures",
            "MetricName": "CPUUtilization",
            "MetricName": "CurrConnections",
            "MetricName": "CurrItems",
            "MetricName": "DatabaseMemoryUsagePercentage",
            "MetricName": "DB0AverageTTL",
            "MetricName": "EngineCPUUtilization",
            "MetricName": "Evictions",
            "MetricName": "FreeableMemory",
            "MetricName": "GetTypeCmds",
            "MetricName": "HashBasedCmds",
            "MetricName": "IsPrimary",
            "MetricName": "KeyAuthorizationFailures",
            "MetricName": "KeyBasedCmds",
            "MetricName": "KeyspaceHits",
            "MetricName": "KeyspaceMisses",
            "MetricName": "KeysTracked",
            "MetricName": "MaxReplicationThroughput",
            "MetricName": "MemoryFragmentationRatio",
            "MetricName": "NetworkBandwidthInAllowanceExceeded",
            "MetricName": "NetworkBandwidthOutAllowanceExceeded",
            "MetricName": "NetworkBytesIn",
            "MetricName": "NetworkBytesOut",
            "MetricName": "NetworkConntrackAllowanceExceeded",
            "MetricName": "NetworkPacketsIn",
            "MetricName": "NetworkPacketsOut",
            "MetricName": "NetworkPacketsPerSecondAllowanceExceeded",
            "MetricName": "NewConnections",
            "MetricName": "PrimaryLinkHealthStatus",
            "MetricName": "Reclaimed",
            "MetricName": "ReplicationBytes",
            "MetricName": "ReplicationDelayedWriteCommands",
            "MetricName": "ReplicationLag",
            "MetricName": "SetTypeCmds",
            "MetricName": "SortedSetBasedCmds",
            "MetricName": "SwapUsage",

```

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
Thanks for the contribution @james-deee.

From the [documentation page](https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.memorydb.html), I see that there are more aggregations of commands. Can you add the ones that are missing here?

Also, can you sign the CLA? Thanks

**Comment by james-deee** [comment]
> Thanks for the contribution @james-deee.
> 
> From the [documentation page](https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.memorydb.html), I see that there are more aggregations of commands. Can you add the ones that are missing here?
> 
> Also, can you sign the CLA? Thanks

@andresmgot I keep signing the CLA, here's a screenshot of the completed screen, but I'm not sure why it's not recording here: 


Taking a look at missing metrics.... surprised the CLI would return less than what's available.

**Comment by james-deee** [comment]
@andresmgot Hmmm, yeah I'm seeing that the chart you referenced here: https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.memorydb.html 

Actually has less metrics than what I've added (the ones in this PR are on the left, and the ones from that table is on the right)
image

If you're referencing the bottom chart (e.g. `GeoSpatialBasedCmds`), those don't appear to be actual things available in Cloudwatch:
image

Also, it doesn't look like I can add labels here, but I would like to add the label `backport v7.5.x`.

Thanks!!!

**Comment by Shegox** [comment]
@james-deee RE CLA: 
It seems that the commit (97eb7b4d3525d99e4b5aa192f64c2d6e9b263a9c) is done with an unassociated email (check the [raw patch](https://github.com/grafana/grafana/commit/97eb7b4d3525d99e4b5aa192f64c2d6e9b263a9c.patch) and you will see `james.demichele@redfin.com`). This causes the above message: 
> James DeMichele seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

If that is a valid email, you can add the email to your Github account and afterwards trigger a recheck to get the CLA approved. Or if the email is wrong/has a typo, you need to amend the commit and recreate it using the proper email. E.g. by using this commands: 
```
# Recreate last commit using a different Git author 
git commit --amend --author="John Doe <your-email-associated-with-your-GitHub-com-account@doe.org>"
# Force update the branch to overwrite the old commit
git push --force
```

**Comment by james-deee** [comment]
@Shegox Thank you thank you thank you!

**Comment by james-deee** [comment]
@Shegox Thanks. I added my email to my account, and when I signed it, it looks like it stuck this time on that CLA page.... but it still sees it as Pending here on the PR. Is there something i need to do to trigger that check here?

image

**Comment by Shegox** [comment]
Yes, exactly you can/need to trigger the check again via this: 
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=47290) it.

I already did this and now it reflects the status correctly as signed. All good from that side now. ✅

**Comment by andresmgot** [comment]
> The ones in this PR are on the left, and the ones from that table is on the right: 

The ones missing seems to be in this other page: https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.HostLevel.html

> If you're referencing the bottom chart (e.g. `GeoSpatialBasedCmds`), those don't appear to be actual things available in Cloudwatch:

Note that in Cloudwatch it will only show you the metrics that you have available (for example, none of the ones you are adding in this PR show up for me). It could be that you don't have the resources that those metrics refer. The source of truth should be the documentation.

> 
> Also, it doesn't look like I can add labels here, but I would like to add the label `backport v7.5.x`.

The branch v7.5.x will no longer include new features (unless special cases), only security patches. I have added the backport label for v8.4.x

**Comment by andresmgot** [comment]
Also, note that there are some lint errors: https://drone.grafana.net/grafana/grafana/56839/1/8

**Comment by james-deee** [comment]
> The ones missing seems to be in this other page: https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.HostLevel.html

@andresmgot I still don't think I'm missing anything :) This PR has *all* of those Metrics in this document you have linked here. If you think I'm missing some particular metrics would you be able to tell me the ones I'm missing? Sorry for the hassle, but I believe I have all of them already.

**Comment by andresmgot** [comment]
Yes, sorry for the confusion, what I meant that are missing are some of the metrics from https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.memorydb.html, even if those don't appear for you:

- EvalBasedCmds
- GeoSpatialBasedCmds
- HyperLogLogBasedCmds
- ListBasedCmds
- PubSubBasedCmds
- SetBasedCmds
- StringBasedCmds
- StreamBasedCmds

**Comment by james-deee** [comment]
Got it! Thanks. Updated with those missing metrics.

**Review by andresmgot — APPROVED** [review]
Thanks for the changes @james-deee ! This is ready to be merged but there was some transient error in `main` yesterday. Do you mind updating `main` and merging here so all the check pass?

**Review by sarahzinger — APPROVED** [review]
🎉

**Pull request merged**
