### PR TITLE
highlight graph line by hover legend

### PR DESCRIPTION
**Pull request by mtanda**
Highlight graph line corresponds to hovered legend.

### CODE REVIEW

**Comment by bergquist** [comment]
I like this! 
But do we really need to require ctrl/shift/meta being held down?
I would also like it to stay until the mouse leaves the legend instead of 500ms

What do you think?

**Comment by mtanda** [comment]
I think, redrawing graph should be suppressed if user just scroll window.
But, I might misunderstand "mouseenter" behavior, it isn't triggered when window scrolling.

I tried to "mouseleave" event, but it doesn't work in my environment.
This is the reason why I use timeout event.

**Comment by mtanda** [comment]
will close https://github.com/grafana/grafana/issues/1134

**Comment by mtanda** [comment]
```diff
diff --git a/public/app/plugins/panel/graph/legend.js b/public/app/plugins/panel/graph/legend.js
index 6bf399a..4f29edd 100644
--- a/public/app/plugins/panel/graph/legend.js
+++ b/public/app/plugins/panel/graph/legend.js
@@ -113,6 +113,7 @@ function (angular, _, $) {
             $container.on('click', '.graph-legend-icon', openColorSelector);
             $container.on('click', '.graph-legend-alias', toggleSeries);
             $container.on('mouseenter', '.graph-legend-alias', toggleHighlightSeries);
+            $container.on('mouseleave', '.graph-legend-alias', function(e) { console.log(e); });
             $container.on('click', 'th', sortLegend);
             firstRender = false;
           }
```

I retry to use "mouseleave", and I confirm that it works, but not every time.
Sometimes, the event isn't triggered.

**Comment by bergquist** [comment]
Yea its kinda buggy. 

But maybe its ok if all other series are reset before highlighting a new.

**Comment by bergquist** [comment]
@mtanda what do you think about this https://github.com/grafana/grafana/pull/4417 ?

**Comment by bergquist** [comment]
Im not sure how to suggest another implementation without opening a new PR :/

**Comment by mtanda** [comment]
Oh, thanks! (and, sorry late reply)
It's looks really nice :+1:

**Pull request closed without merging**
