### PR TITLE
TestData: Improve what's new in v7.4

### PR DESCRIPTION
**Pull request by leeoniya**
this is a followup to #30568.

this PR fixes some panel titles, wording inaccuracies and improves the multi-axis demo panel.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by torkelo** [comment]
@leeoniya no need to backport this

**Comment by leeoniya** [comment]
would be good to get this into the public `play.grafana.org` dashboard by 7.4 announcement, since it fixes some inaccuracies.

**Comment by torkelo** [comment]
@leeoniya I updated it just a couple of minutes ago.

**Comment by leeoniya** [comment]
awesome :)

**Pull request merged**
