### PR TITLE
Explore: Keep logQL filters when selecting labels in log row details

### LINKED ISSUE #19512: Explore: Filter disappear when adding a label matcher via the UI
**What would you like to be added**:

Currently in Explore with Loki datasource when you have a multiple filter expressions:

```
{app="foo"}  != "not that errror" != "no that one too" != "neither this one"...
```

And you click on the `+` button to add a new label matcher from a label value, it will add the label matcher but also remove all filter ending up with `{app="foo",new="matcher"}`.

**Why is this needed**:

It would be better if we don't have to rewrite filter expressions from scratch when adding a label matcher from the UI.

### LINKED ISSUE #20553: Explore: Selecting labels in log row detail removes logql filter
**What happened**:

xxxy
xxxy2
xxxy3

**What you expected to happen**:

The changed log line still contains my filter != "ERROR"

**How to reproduce it (as minimally and precisely as possible)**:

see screenshot

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.0-pre (6a4ad136dc)
- Data source type & version: loki 1.0.0

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
When selecting labels from log row details (Explore + Loki), logQL filters were removed from the query. This PR fixes this and adds unit tests.

**Which issue(s) this PR fixes**:
Fixes #20553
Fixes #19512

ezgif com-video-to-gif (2)

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]
LGTM

**Review by Estrax — APPROVED** [review]
LGTM.

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Found a small issue, it works but there are some ugly chars `(?i)` appended before `chunk` which looks weird
1. Enter a query like `{app="myapp"} chunk`
2. Add a filter
3. Resulting in {app="myapp",myfilter="some filter value"}  `(?i)chunk` NOT OK
4. Rows are filtered correctly OK

**Comment by ivanahuckova** [comment]
@hugohaggmark I have looked into it, and it seems that adding of  `(i)` was created on purpose [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/query_utils.ts#L16) by @davkal. So I am not sure, if it should be removed, or what is the purpose of that.

**Review by hugohaggmark — APPROVED** [review]
Approving this for now, but we need to investigate this behaviour.

**Comment by ivanahuckova** [comment]
> Approving this for now, but we need to investigate this behaviour.

I have created an issue for this: https://github.com/grafana/grafana/issues/20591

**Pull request merged**
