### PR TITLE
Docs: Added missing enterprise plugins

### PR DESCRIPTION
**Pull request by yesoreyeram**
**What this PR does / why we need it**:

* Add missing enterprise plugins to the add data source page
* Add missing enterprise plugins to the upgrade page
* Remove Amazon Timestream from enterprise plugin category

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
don't know too much about this area of the code, but all looks sane to me 👍  
is there no svg for jira? i have an irrational hatred of `.png`s 😂

**Comment by yesoreyeram** [comment]
it is not only JIRA. There are lots of other plugins that use `png` as defined in their respective `plugin.json`. I will leave this to png to maintain the **_inconsistency_** :)

**Review by mjseaman — APPROVED** [review]
LGTM, thank you @yesoreyeram !

**Review by achatterjee-grafana — APPROVED** [review]
Doc update looks ok.

**Pull request merged**
