### PR TITLE
Tempo: Always use time range even if timeShiftEnabled is false

### PR DESCRIPTION
**Pull request by ogxd**
Issue: https://github.com/grafana/grafana/issues/85476

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] ~~The docs are updated~~ Initial behavior had never been documented. This PR removes this specific behaviour, so there is no need to document it now.

### CODE REVIEW

**Comment by joey-grafana** [comment]
Hey @ogxd this looks great, thank you for the PR and apologies for the delay.

Before we merge, can you please pull the latest from main and merge to this PR so we have the latest code?

Also, it appears there is a small lint issue, a leftover import in `datasource.ts` from a closer inspection. Please remove this.

Screenshot 2024-05-14 at 12 50 38

**Comment by joey-grafana** [comment]
Also, please ensure tests in `public/app/plugins/datasource/tempo/datasource.test.ts` are passing :)

**Comment by ogxd** [comment]
Thank you for the review @joey-grafana! I have pulled main, fixed the unused import and changed the test to the new behavior.

**Comment by aocenas** [comment]
Fyi depending on when is what merged this can create a merge conflict https://github.com/grafana/grafana/pull/87980 but should be easy to resolve.

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 Thank you for the PR!

**Pull request merged**
