### PR TITLE
Heatmap: Fix missing value in legend

### PR DESCRIPTION
**Pull request by kurokochin**
**What this PR does / why we need it**: We need this to fix the logic to handle where the min value > 0 for heatmap panel

**Which issue(s) this PR fixes**: #24849

**Special notes for your reviewer**: I haven't been able to fix the legend text if the difference between minValue and maxValue is too small (attached pictures for clarity, first pic: 65-129, second pick: 66-129)
Screenshot 2021-02-24 at 1 03 24 AM
Screenshot 2021-02-24 at 1 03 34 AM

### CODE REVIEW

**Comment by kurokochin** [comment]
@hugohaggmark fyi :)

**Review by hugohaggmark — COMMENTED** [review]
Thanks for taking the time to look into fixing this @kurokochin 🎉  would be outstanding if you could add some tests so this doesn't happen again, I guess. Let me know if you need help with that.

**Comment by kurokochin** [comment]
Hi @hugohaggmark, I'd love to write the test(s) for my changes! If it's ok with you, can give me some pointers? (existing unit test, etc..) It'll help me a lot compare to wondering around the code base by myself 😄

**Comment by hugohaggmark** [comment]
Hmm, looking closer it seems like it would be hard to get tests into place here. We'll need to test this manually then.

**Review by torkelo — APPROVED** [review]
Looks good! thanks for contributing!

**Review by dprokop — APPROVED** [review]

**Pull request merged**
