### PR TITLE
Docs: Added queried table to start of Time Series section

### LINKED ISSUE #44494: Docs feedback: /datasources/mysql.md
The Time Series Queries would be MUCH clearer and easier to understand if the table used as an example was shown at the beginning of that section.

Basically, do `select * from test_data limit 10;` and show the output at the start of that section.

### PR DESCRIPTION
**Pull request by sjd210**
**What is this feature?**

Adding SQL table being queried to beginning of "Time Series" section, and updating result tables of each query so they have suitable data.

**Why do we need this feature?**

Makes the Time Series queries easier to understand.

**Who is this feature for?**

Those learning to use the MySQL datasource

**Which issue(s) does this PR fix?**:

Fixes #44494

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mdvictor — APPROVED** [review]
LGTM!

**Review by baldm0mma — APPROVED** [review]
Stellar! I would add a technical writer to the list of folks for approval as well. :)

**Comment by imatwawana** [comment]
@mdvictor - @lwandz13 is our data sources technical writer, so she's been correctly tagged for review. Gonna go ahead and remove myself.

**Comment by mdvictor** [comment]
> @mdvictor - @lwandz13 is our data sources technical writer, so she's been correctly tagged for review. Gonna go ahead and remove myself.

Sorry and thanks for letting me know @imatwawana!

**Review by lwandz13 — APPROVED** [review]

**Pull request merged**
