### PR TITLE
RangeSlider: updates story from knobs to control

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR updates story from knobs to control.
**Which issue(s) this PR fixes**:

Relates to #30182

### CODE REVIEW

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
I think the orientation needs to be a toggle or select. Also, when I toggle `tooltipAlwaysVisible` Storybook crashes.
image

**Comment by thisisobate** [comment]
Yeah...just noticed the `tooltipAlwaysVisible` issue on local. I'm wondering what must have gone wrong here? Any ideas? @hugohaggmark

**Comment by hugohaggmark** [comment]
> Yeah...just noticed the `tooltipAlwaysVisible` issue on local. I'm wondering what must have gone wrong here? Any ideas? @hugohaggmark

Sorry, but I can't think of anything at the top of my head. Could be related to our Storybook decorators or the RangeSlider itself.

**Comment by thisisobate** [comment]
would have a look and see where the issue is coming from.

**Review by hugohaggmark — APPROVED** [review]
Poked around on why this crashes and I think this might be because of the RC-Slider not being properly constructed, so let's exclude the `tooltipAlwaysVisible` prop for now.

**Comment by thisisobate** [comment]
Alrighty. Thanks!

**Pull request merged**
