### PR TITLE
Add support for InfluxDB's time zone clause

### LINKED ISSUE #10322: [RFE] Add support for InfluxDB `tz` clause
- What Grafana version are you using? 4.6.3
- What datasource are you using? InfluxDB

InfluxDB supports timezone for queries since 1.3:
 - https://github.com/influxdata/influxdb/issues/6541
 - https://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/#the-time-zone-clause

Grafana currently does not allow to configure it (unless you switch to the edit mode) and does not automatically set a `tz` clause.  It means that InfluxDB uses UTC to calculate time buckets which is annoying when you are trying to visualize metrics that should be bucketed according to a given timezone rather than UTC. 

It would be great to be able to explicitly set a `tz`. I am also wondering if Grafana shouldn't automatically set `tz` to the dashboard time zone. Compatibility with InfluxDB < 1.3 should also be taken into account.

### PR DESCRIPTION
**Pull request by jkreileder**
This fixes #10322 by adding support for Influx DB's time zone clause.

### CODE REVIEW

**Comment by jangaraj** [comment]
I would like to have an option to use dashboard timezone. It will be useful, especially if dashboard uses browser time zone.

**Comment by jkreileder** [comment]
Good idea but probably not in the scope of the issue and this pull request as it is a more global thing:
You can get the browser's timezone with Intl.DateTimeFormat().resolvedOptions().timeZone but this should be made available for all of Grafana and not just the influxdb plug-in.

(My use case is actually the other way round, I want Grafana panels to use the timezone of the data. This pull requests is one step required for that. The other is #558; I'll probably make a pull request for that sometime soon.)

**Comment by rmiggily** [comment]
Finally! A feature to resolve all the time zone related headaches of InfluxDB! Thanks for your commit. Could somebody please merge this change?

**Comment by cykl** [comment]
Any blocker? These 20 LOCs are super useful. How can I help to get them merged?

**Comment by blalor** [comment]
Are there any blockers to getting this merged?  I'd really like to have this feature!

**Comment by cby016** [comment]
+1 for this feature

**Comment by cykl** [comment]
@torkelo I apologize for the direct ping, but this PR has been stalled since this summer without any positive or negative feedback from Grafana team. How can we move forward?

I just tested this PR against v5.4.1 and InfluxDB 1.6.0. Works for me.

**Comment by torkelo** [comment]
Sorry for lack of feedback. Think it needs some UX changes to it does not take up space in the query editor when not used (similar to some other option that can be added via the plus button after group by).

Also needs corresponding backend update (influxdb code in backend go code)

**Comment by torkelo** [comment]
Another PR (that was a continuation on this PR) was now merged! 

Thank you for contributing to Grafana!

**Comment by rmiggily** [comment]
@torkelo  Thanks for your time.

**Pull request closed without merging**
