### PR TITLE
Table Panel: Fixes inaccessible sorting and filtering when table panel has no title

### LINKED ISSUE #64021: Table filter funnels not clickable when panel title is empty
**What happened**:
I enabled column filtering from the table panel settings, left the panel title empty as not needed for GUI design. The filter funnel icons show but cannot be clicked.

**What you expected to happen**:
I should be presented with a drop-down menu to filter the chosen table column.

**How to reproduce it (as minimally and precisely as possible)**:
Enable column filtering on the table panel and then try click on the funnel icon at the top row of a column, Nothing happens.

**Anything else we need to know?**:
When I populate the panel title, the column filtering works. Seems it has be filled out otherwise the the panel title HTML element sits over the top row so you cannot sort or filter columns. Same outcome with using Edge web browser.

**Environment**:
- Grafana version: v9.3.4
- Data source type & version: MySQL (Bundled with Grafana)
- OS Grafana is installed on:
- User OS & Browser: Windows 10 and Google Chrome version 110.0.5481.177
- Grafana plugins: MySQL

### PR DESCRIPTION
**Pull request by baldm0mma**
**What is this feature?**

Fixes a bug in the Table Panel in which when a the title is removed from the Table Panel, the table flexes upward to take up the space the title previously comprised, making clicking on the sorting or filtering options impossible.

**Why do we need this feature?**

So that user can sort and filter in the expected way.

**Who is this feature for?**

All users.

**Which issue(s) does this PR fix?**:

Fixes #64021

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [na] If this is a pre-GA feature, it is behind a feature toggle.
- [na] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [x] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [na] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

Previous behavior when title is remove -> sorting and filtering is inaccessible:

https://user-images.githubusercontent.com/46619047/228036740-05ffc67f-46e0-4c4d-84dd-18e3276c5079.mov

Fixed behavior when title is removed:

https://user-images.githubusercontent.com/46619047/228036796-965bbe00-bd9e-46c8-a359-e5e906c66eaf.mov

### CODE REVIEW

**Comment by supilee** [comment]
Works as expected from UI perspective. Please review code as well.

**Review by torkelo — CHANGES_REQUESTED** [review]
@supilee @baldm0mma 

I don't think we need this, this breaks the main utility of removing the title (the point is to free up more space for the visualization) 

This problem however is real and present in Table panel and other panels but is already fixed by the new panel frame & menu (that was explicitly designed to fix this problem). The new panel frame and header have a new mode when there is no title that no longer obstructs the top of the panel. 

Screenshot from 2023-03-28 15-37-51

**Comment by torkelo** [comment]
you can try the new panel chrome and menu with the feature toggle "newPanelChromeUI" set to true, it is going to be enabled by default in 9.5

**Comment by baldm0mma** [comment]
@torkelo Awesome! Thanks for the info; I'll close this PR and make sure I mention the fix on the community issue, and close that also.

**Pull request closed without merging**
