### PR TITLE
Webpack 4 (WIP)

### PR DESCRIPTION
**Pull request by torkelo**
Continuation of work done in https://github.com/grafana/grafana/pull/12066 

* [x] Fixed angular js issue (was not related to webpack but lax version restriction in package.json for angularjs)
* [x]  Changed from awesome-typescript-loader to the more common ts-loader & forked type checking combo
* [ ] Major blocker that is not working is the build mode that hangs on the uglify js step 
* [ ] You get a warning about "Tapable.plugin is deprecated. Use new API on `.hooks` instead"   seems to be related to https://github.com/webpack-contrib/extract-text-webpack-plugin They recommend not using ExtractTextPlugin for css in webpack v4, so we should use https://github.com/webpack-contrib/mini-css-extract-plugin

# Investigate

Use optimization minimizer section in webpack config, might fix UglifyJsPlugin hang issue:

```javascript 
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        sourceMap: true // set to true if you want JS source maps
      }),
      new OptimizeCSSAssetsPlugin({})
    ]
  },
```

Also this section in both dev & prod looks stange:

```javascript
 optimization: {
    splitChunks: {
      cacheGroups: {
        manifest: {
          chunks: "initial",
          test: "vendor",
          name: "vendor",
          enforce: true
        },
        vendor: {
          chunks: "initial",
          test: "vendor",
          name: "vendor",
          enforce: true
        }
      }
    }
  },
```

looks like text name are wrong in for the manifest chunk, and there is no cacheGroup for app entrypoint?

### CODE REVIEW

**Comment by davkal** [comment]
Comparison of production builds: 
https://gist.github.com/davkal/e6f7fa77f0a8d5b809b2581743d56a23

Highlights:

Before
```
           0.ade6e8232805338ecdad.js     721 kB       0  [emitted]  [big]  
      vendor.ade6e8232805338ecdad.js    2.44 MB       2  [emitted]  [big]  vendor
         app.ade6e8232805338ecdad.js    1.63 MB       3  [emitted]  [big]  app
       light.ade6e8232805338ecdad.js  103 bytes       4  [emitted]         light
        dark.ade6e8232805338ecdad.js  102 bytes       5  [emitted]         dark
    manifest.ade6e8232805338ecdad.js    1.45 kB       6  [emitted]         manifest
                    grafana.dark.css     274 kB       5  [emitted]  [big]  dark
                   grafana.light.css     273 kB       4  [emitted]  [big]  light
           1.ade6e8232805338ecdad.js    82.3 kB       1  [emitted]         explore
```

After
```
    vendors.1c796985b104c80f53d2.js   3.23 MiB       0  [emitted]  [big]  vendors
    explore.1c796985b104c80f53d2.js   37.7 KiB       2  [emitted]         explore
          3.1c796985b104c80f53d2.js    544 KiB       3  [emitted]  [big]  
      light.1c796985b104c80f53d2.js   1.52 KiB       4  [emitted]         light
       dark.1c796985b104c80f53d2.js   1.52 KiB       5  [emitted]         dark
        app.1c796985b104c80f53d2.js    695 KiB       6  [emitted]  [big]  app
                    grafana.app.css   73 bytes       6  [emitted]         app
                   grafana.dark.css    267 KiB       5  [emitted]  [big]  dark
                  grafana.light.css    267 KiB       4  [emitted]  [big]  light
          1.1c796985b104c80f53d2.js   40.4 KiB       1  [emitted]         
```

What's still failing is karma tests.

**Comment by torkelo** [comment]
ok, updated and replaced the extact text plugin with new plugin.  Still get the warning of use of depricated api being used, not sure where that is coming from. 

also changed moved uglify & minify stuff to optimization section, but cannot test it as I cannot run the build, still hangs on uglify js (or at least taking more than 5min). 

One issue with the change to how vendors chunk is extracted is that it also applies to css., so we get a vendors css (for grid component css). Need to fix that as it could cause issues with theming. Wont be able to work more on this today, kid waking up soon.

**Comment by torkelo** [comment]
ok, the prod build did not hang, just needed a tiny bit more patience (uglify js is slooow, complete prod build to 5min)

**Comment by davkal** [comment]
> One issue with the change to how vendors chunk is extracted is that it also applies to css., so we get a vendors css (for grid component css). 

Changing the splitChunks test to `/[\\/]node_modules[\\/].*[tj]s$/,` seems to work for me.

**Comment by torkelo** [comment]
is there anything else we need to do here? this should be mergeable (if all tests pass again) ?

**Pull request merged**
