### PR TITLE
Dashboard: Fix UIDs are not preserved when importing/creating dashboards thru importing .json file

### LINKED ISSUE #37944: Dashboard UIDs are not preserved when importing/creating dashboards thru importing .json file
**What happened**:
When i import an existing .json dashboard file, i see the UID for the imported dashboard is getting changed, when import is completed.
[Kubernetes_Compute Resources_Namespace(Pods).txt](https://github.com/grafana/grafana/files/6996122/Kubernetes_Compute.Resources_Namespace.Pods.txt)

**What you expected to happen**:
Dashboard UIDs preserved when importing dashboards as .json (unless there is a colllsion between UIDs between whats imported v whats already in the grafana instance)

**How to reproduce it (as minimally and precisely as possible)**:
    
See an attached sample dashboard. UID in there is '85a562078cdf77779eaa1add43ccec1e'. But in my case after import i see a shorter/modern UID 'Wx8Ori77z'.  Grafana version i am trying to import it in to is 'Grafana v8.0.6 (68fe9e3431)' .

**Anything else we need to know?**:

- Grafana version:
 v8.0.6 (68fe9e3431)

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

By default input field is disabled in the form. 

disabledInputField

Values of disabled input are not submitted, I added a fallback to the original dashboard uid, if the user did not change the uid through the form.

**Which issue(s) this PR fixes**:

Fixes #37944

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]

**Comment by marefr** [comment]
This should probably be added to the changelog, see [Merge a pull request](https://github.com/grafana/grafana/blob/main/contribute/merge-pull-request.md)

**Comment by hugohaggmark** [comment]
@axelavargas backport failed so you need to do it manually ☝️

**Comment by axelavargas** [comment]
> @axelavargas backport failed so you need to do it manually

Hello, @hugohaggmark 😄 , actually yesterday the backport was merged correctly [here](https://github.com/grafana/grafana/pull/38892), but I made a mistake by removing and adding again the backport label when I was adding the `add to changelog label` (I clicked the wrong label 🙈 )

**Comment by hugohaggmark** [comment]
> > @axelavargas backport failed so you need to do it manually
> 
> Hello, @hugohaggmark 😄 , actually yesterday the backport was merged correctly [here](https://github.com/grafana/grafana/pull/38892), but I made a mistake by removing and adding again the backport label when I was adding the `add to changelog label` (I clicked the wrong label 🙈 )

All good, great work 👍

**Pull request merged**
