### PR TITLE
A11y/DashList: Make star button tab-navigable

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Moves the `onClick` property from a `span` to an `IconButton` and adds an appropriate aria-label.
Also adds the `alert` role to the Alert component so alerts are read aloud for those using screen readers.

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]

**Review by Elfo404 — APPROVED** [review]
This is for sure an improvement 🚀 

In general I think we should use toggle buttons (or checkboxes) in this particular case as I think a normal button doesn't have any information about its state and would be hard for screen readers users to determine the current state

**Comment by kaydelaney** [comment]
> In general I think we should use toggle buttons (or checkboxes) in this particular case as I think a normal button doesn't have any information about its state and would be hard for screen readers users to determine the current state.

This is a very good point! I'll try a few things.

**Comment by kaydelaney** [comment]
Leaving it a bit messy at the moment because I'd like to see how well my last commit works with some other screen readers I don't have access to. @joshhunt If you get a free moment could you check out if tabbing onto the star checkbox works well with NVDA and/or Narrator?

**Review by joshhunt — APPROVED** [review]
https://user-images.githubusercontent.com/46142/142446923-51709758-64ca-40cd-b91e-90c854b3a5b3.mp4

This is the experience with Narrator + Chrome on Windows. I think it's good and works as expected 👍🏻

**Comment by Elfo404** [comment]
@kaydelaney do we want to add a backport label to get this in 8.3?

**Comment by kaydelaney** [comment]
Yes we do 😅

**Pull request merged**
