### PR TITLE
Dashboard: Call destroy when panel is removed

### LINKED ISSUE #76846: Dashboards: Panel does not unsubscribe from Observable when removed from dashboard
### What happened?

When developing a datasource plugin returning streaming data from an observable, the subscription should be unsubscribed when the panel is removed from the dashboard.

This causes a resource leak where an observable is still subscribed and the panel that contains the query has been removed.

It appears to me that `DashboardModel.removePanel(panel)` should call `panel.destroy()` on the provided panel. `panel.destroy()` subsequently calls `this.queryRunner.destroy()` which then unsubscribes from the observable.

### What did you expect to happen?

The panel's queries to unsubscribe from it's observables.

### Did this work before?

No

### How do we reproduce it?

1. Install a data source plugin that returns an observable.
2. Create a dashboard
3. Create a panel that uses the data source in the dashboard
4. Remove the panel from the dashboard

### Is the bug inside a dashboard panel?

I believe this a a problem with all panels that use a data source that returns an observable.

### Environment (with versions)?

Grafana: 10.1.5
OS: MacOS and Linux
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gregington**
**What is this feature?**

Fixes a bug where when a panel is removed from a dashboard, `destroy()` was not called on the removed panel.

**Why do we need this feature?**

`destroy()` calls cleanup methods for the panel, including unsubscribing from an observable that may have been obtained from a datasource. Not calling `destroy()` can leak resources.

**Who is this feature for?**

All users as this fixes a resource leak.

**Which issue(s) does this PR fix?**:

Fixes #76846

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Yes, this makes sense. Thanks for your contribution @gregington!

**Comment by gregington** [comment]
Pinging for review to prevent closure due to staleness.

**Comment by axelavargas** [comment]
Hey @gregington 👋🏾 , thank you for contributing to Grafana 🏅. I wonder, is it possible for you to update your branch with the latest main branch? It might fix some CI failures we are getting in this PR and those failures are preventing the merge.

Thank you 🙏🏾

**Comment by gregington** [comment]
@axelavargas I've updated my branch to latest master.

**Review by axelavargas — APPROVED** [review]

**Pull request merged**
