### PR TITLE
DataLinks: Encoded URL fixed

### LINKED ISSUE #67701: Dashboard: Data links on a table is wrongly encoded
### 
# What went wrong?

**What happened**:

  - Since Grafana v9.5.0 the data links on a table is seems wrongly encoded or templated. 
  - The URL ist taken from a Query and refered to in "Data links" wither ${__data.fields.url}
  - In the table cell the URL is correctly shown: https://mysecondurl.corp.com/ui
  - If click on the table and want to open the link a 404 page is displayed. The URL seems strange:
    https://grafana.corp.com/https%3A%2F%2Fmysecondurl.corp.com%2Fui

**What did you expect to happen**:

  - I expect that the new tab opens "https://mysecondurl.corp.com/ui/" if I click on the table cell

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create a table with an URL.

**Step 2**:

- Configure a data link which referes to the cell with the url in it.
- Also configure to open the url in a new tab

**Step 3**:

- Save the dashboard

**Step 4**:

- Click on the table row to open the url

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Windows 10 22H2

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

JSON API

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It fixes data link issue, where using ${__data.fields.FIELD_NAME} doesn't work.

**Which issue(s) does this PR fix?**:

Fixes [#5536](https://github.com/grafana/support-escalations/issues/5536)

Fixes #67701

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by juanicabanas** [comment]
are labels and milestone correctly set?

**Review by torkelo — APPROVED** [review]

**Review by nmarrs — COMMENTED** [review]
LGTM

**Comment by nmarrs** [comment]
I think we will also want to merge these changes into main branch and not just 9.5.x - if we don't then v10 will have the same regression

For this the typical flow is merging into main branch and then backporting to the relevant version branches (via the backport v9.5.x tag etc)

**Comment by juanicabanas** [comment]
@nmarrs that's already done. I made this backport cherry picking 2 commits already in main.

**Pull request merged**
