### PR TITLE
AppChrome: Add display flex to prevent multiple scrollbars

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

When adding a notification banner in [this enterprise PR](https://github.com/grafana/grafana-enterprise/pull/6704), we noticed that this caused multiple scrollbars to be shown on long pages:
Screenshot 2024-05-30 at 15 48 59

Making `main` in `AppChrome` have `flex` fixes this behavior:

Screenshot 2024-05-30 at 15 49 22

**Why do we need this feature?**

So the page doesn't behave strangely for instances with enterprise banners.

**Who is this feature for?**

Enterprise instances with banners.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Clarity-89** [comment]
I'm still seeing the double scrollbar on [this page](https://ephemeral1511182188512joaosil.grafana-dev.net/a/grafana-kowalski-app/apps) for example.

**Comment by JoaoSilvaGrafana** [comment]
> I'm still seeing the double scrollbar on [this page](https://ephemeral1511182188512joaosil.grafana-dev.net/a/grafana-kowalski-app/apps) for example.

Good spot. I think this is hard to fix because of how different apps can customize their pages, this will mean the scrolling behaviours will be different across all of them... If we added `min-height: 0px` to that page it seems to fix it. Do you have any other ideas on how to fix it more broadly?

**Comment by JoaoSilvaGrafana** [comment]
So now in some pages the content scrolls and the header is sticky while in others they scroll together 🤷  It's better than the previous attempt.

**Comment by eledobleefe** [comment]
> So now in some pages the content scrolls and the header is sticky while in others they scroll together 🤷 It's better than the previous attempt.

Forgive me if this is not right but, did we not agree in the daily to move the banner to the top of the page? 🤔

This is more of a generic question: Whilst looking into this on local, I realise there are a lot of links that open the content in a new window, like "Account usage" on the home page. Does the banner need to be also in the new window? 🤔

**Comment by JoaoSilvaGrafana** [comment]
> Forgive me if this is not right but, did we not agree in the daily to move the banner to the top of the page? 🤔

Yep, but unfortunately Ash was right that the drawer also assumes the size of the navigation
Screenshot 2024-06-04 at 15 57 43

So that is no longer be the simpler option 😢 

> This is more of a generic question: Whilst looking into this on local, I realise there are a lot of links that open the content in a new window, like "Account usage" on the home page. Does the banner need to be also in the new window? 🤔

Hmm I dont see an "Account usage" button... but yes the banner should show in all the pages in the instance.

**Review by eledobleefe — APPROVED** [review]
Since this is the best solution right now, LGTM 👌

**Review by Clarity-89 — APPROVED** [review]

**Pull request merged**
