### PR TITLE
Restartable playlists

### PR DESCRIPTION
**Pull request by nikita-graf**
Сurrently, it is impossible to replay playlist in grafana if it is stopped. If stop button is pressed, I have to select dashboards from the list again to restart the previous playlist.
It was really disappointing, so I wrote this feature. Now you can save playlists and each of them has unique url and title, so any time you can restart them.
At this moment organizations aren’t supported here, so everyone can see all playlists and edit them. If you're interested in this PR, I'll be glad to add this feature too.

Screenshots 
https://cloud.githubusercontent.com/assets/2078870/9628899/5b7c5410-5177-11e5-9bfe-e9cfa18e4072.png
https://cloud.githubusercontent.com/assets/2078870/9628903/683af6e8-5177-11e5-9ac1-3e00679a9e14.png

### CODE REVIEW

**Comment by torkelo** [comment]
looks like a great start to a an improved playlist feature! yes, this needs to support org id

**Comment by nikita-graf** [comment]
Thanks! I'll add organizations support ASAP.

**Comment by nikita-graf** [comment]
Is there any chance to accept this PR without organizations support?

**Comment by torkelo** [comment]
no :(

**Comment by nikita-graf** [comment]
I've added organizations here, take a look pls.

**Comment by w495** [comment]
Is there any real activity in this issue?

**Comment by shoonoise** [comment]
:+1:

**Comment by Mellanore** [comment]
:+1: :+1:

**Comment by utkarshcmu** [comment]
+1

**Comment by nikita-graf** [comment]
Hi! Can I do something here to have this merged?

**Comment by torkelo** [comment]
@nikita-graf not sure, its not a going into 2.5 as that is just about to be released. And after that alerting and table panel is top prio. But might have time to squeeze it into 2.6 or 2.7

**Comment by nikita-graf** [comment]
ok, pls keep updated, I'm willing to help if needed. It's really painful to live without this feature.

**Comment by mtanda** [comment]
+1

**Comment by utkarshcmu** [comment]
@nikita-graf This work is awesome. I am trying to resurrect your work. Will be submitting a PR soon. :+1:

**Comment by bergquist** [comment]
closed by #3655

**Pull request closed without merging**
