### PR TITLE
(prometheus) support label name/value completion

### PR DESCRIPTION
**Pull request by mtanda**
Implement this feature.
https://github.com/grafana/grafana/pull/9167#discussion_r137081348

### CODE REVIEW

**Comment by mtanda** [comment]
this change breaks auto complete feature. https://github.com/grafana/grafana/commit/e5f84484eb1210d835c06f4f60229abc3b05d9a8

Not label value is shown in popup.
image

**Comment by mtanda** [comment]
@torkelo adding css style for new token is difficult?

**Comment by torkelo** [comment]
No, if we need to do that we can do that

**Comment by mtanda** [comment]
image
I check the output of my code, it seems to correct.

Maybe `string` token is too common, it mixes some extra things.
I don't know the Ace editor internal, but I can say it is not safe to use very common token to special token, it may cause unexpected behavior.

@torkelo Please consider to add css style for `label.name` and `label.value`.

**Comment by mtanda** [comment]
Try to fix. The token name is not intuitive, but works.

**Comment by torkelo** [comment]
this is really nice, great work @mtanda . 

We need to figure out a way to write unit tests for the completer.ts as the code there is getting a bit complex.

**Comment by mtanda** [comment]
@torkelo
I want to add test, but I'm not familiar to build test code base.
If you help to prepare stub or some other required component, I can add test.
Please assist me.

**Comment by torkelo** [comment]
sure! added a simple test to get you started, https://github.com/grafana/grafana/commit/3c162301580d60d18f902d9b60c8ce41927eb000

**Comment by mtanda** [comment]
Really nice, and helpful!
Thanks!!

**Comment by torkelo** [comment]
@mtanda is this ready for merge?

**Comment by mtanda** [comment]
@torkelo Yes, it's ready.

**Comment by bergquist** [comment]
@mtanda Great work! :)

**Comment by mtanda** [comment]
Thanks! I really want this feature.

**Pull request merged**
