### PR TITLE
Prometheus: remove carriage-return characters from queries

### LINKED ISSUE #32159: Failed query if \r erroneously ends up in the query text
**What happened**:
If somehow, an carriage return character ('\r') ends up in a query URL, it is not shown in the metric query text box, but it is submitted to the backend

**What you expected to happen**: the \r to be displayed in some way 

**How to reproduce it (as minimally and precisely as possible)**:
The following URL has a \r encoded in the first query 
```
https://snctest.grafana.net/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22grafanacloud-snctest-prom%22,%7B%22expr%22:%22probe_all_duration_seconds_sum%7Binstance%3D%5C%22https:%2F%2Fbbc.co.uk%2F%5Cr%5C%22%7D%22,%22requestId%22:%22Q-65a9909a-bc25-4fa2-8f94-a91d2385dbc9-0A%22%7D%5D&right=%5B%22now-6h%22,%22now%22,%22grafanacloud-snctest-prom%22,%7B%22expr%22:%22probe_all_duration_seconds_sum%7Binstance%3D%5C%22https:%2F%2Fbbc.co.uk%2F%5C%22%7D%22,%22requestId%22:%22Q-235f3ec7-3646-4cd0-9f00-02da40f3bcc0-0A%22%7D%5D
```
URL decoded this is 
```
https://snctest.grafana.net/explore?orgId=1&left=["now-6h","now","grafanacloud-snctest-prom",{"expr":"probe_all_duration_seconds_sum{instance=\"https://bbc.co.uk/\r\"}","requestId":"Q-65a9909a-bc25-4fa2-8f94-a91d2385dbc9-0A"}]&right=["now-6h","now","grafanacloud-snctest-prom",{"expr":"probe_all_duration_seconds_sum{instance=\"https://bbc.co.uk/\"}","requestId":"Q-235f3ec7-3646-4cd0-9f00-02da40f3bcc0-0A"}]
``` 
As you can see, there is a `\r` right before the closing quote in the `instance` filter. 

This results in the following 
image

As you can see, there is no indication of any hidden character in the query making it very hard to detect why the query is returning no results. 

Grafana should show some indication there is a non-printable character in the query. 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.4.5 
- Data source type & version: n/a 
- OS Grafana is installed on: Grafana Cloud 
- User OS & Browser:  Windows / Firefox 
- Grafana plugins: n/a 
- Others: n/a

### PR DESCRIPTION
**Pull request by conorevans**
Signed-off-by: Conor Evans <coevans@tcd.ie>

**What this PR does / why we need it**: This PR replaces `\r` (carriage-return) characters in Prometheus queries. As seen in the screenshot in the linked issue, nothing appears wrong with the text (the carriage-return character is not visible) and no error is shown - just "0 series returned".

image

In this case, as noted by @ivanahuckova, the user copied the text from Excel, which has its own formatting/parsing. To be user-friendly, we should replace these characters.

**Which issue(s) this PR fixes**:

Fixes  #32159

**Special notes for your reviewer**: @ivanahuckova I am not sure if this is your area to review but I wanted to check in with you here because I didn't find the issue to be at ` public/app/core/utils/explore.ts` as mentioned [here](https://github.com/grafana/grafana/issues/32159#issuecomment-808160321). I console logged at that point but nothing was present - did I miss something?

The first place in the chain that I did find it was `locationSearchToObject` in `LocationService`, which is called at `GrafanaRoute.render()`

```javascript
return <RouteComponent {...props} queryParams={locationSearchToObject(props.location.search)} />;
```

But I figure this is just passing the query back to the frontend, whereas, as the `datasource/prometheus` tag you applied to the issue suggests, the issue should be cleaned on the backend (such that the query resolves as the user expects).

Please let me know if I've misunderstood anything there! Thanks 🙏 

Below I've explicitly added a carriage-return character because I actually don't have Excel, but I verified that the URL encoding was the same as if it were invisible, like in the linked issue,

image

### CODE REVIEW

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
This should be fixed in QueryField component in grafana/ui, so we don't have to fix it individually in each data source.

**Comment by conorevans** [comment]
> This should be fixed in QueryField component in grafana/ui, so we don't have to fix it individually in each data source.

Yeah, totally - thanks for pointing to that parent component. Will fix this up soon.

**Comment by conorevans** [comment]
Hi @ivanahuckova I had another look at this. The `QueryField` has `QueryFieldProps`, one of which is an optional lambda/function/method property `cleanText`, and the value of this is set in the `QueryField` component in the various datasource components, e.g. `PromQueryField`. But therein, the `cleanText` of the `QueryField` is actually determined by a given datasource's language provider, e.g. for `PromQueryField`:

```typescript
...
const cleanText = languageProvider ? languageProvider.cleanText : undefined;
...
  render() {
...
    return (
...
            <QueryField
...
              cleanText={cleanText}
```

There are currently four language providers - `Loki`, `Prometheus`, `CloudWatch`, and `ElasticSearch`. The first three implement a `cleanText` while `ElasticSearch` does not. I'm no expert in TypeScript, but I couldn't see how a global cleanText could be propagated down from `QueryField`. So I took a look at implementing in `Prometheus` first but, unless I'm missing something, `cleanText` does not achieve what we need it to here, it only deals with the end of the query string?

https://user-images.githubusercontent.com/43791257/113364669-6b336b80-9354-11eb-90a9-21553e19d7fc.mp4

Whereas you can see that the current approach in `datasource/prometheus.ts`  does clean the received query, and returns results (as per screenshot in original post).

Additionally, if it were possible to implement via cleaning the Query Field, I'm not sure it would solve the case here - which is copy/paste, so the user would probably never type or do any other action that would trigger the state refresh. They would likely go straight to "Run query", see no results and be confused. WDYT?

Let me know if I've missed anything, thanks!

**Comment by ivanahuckova** [comment]
Sorry for late reply @conorevans, I was out of office around Easter holidays. So what I was thinking about implementing `carriage return` removing directly in `QueryField`. [We are passing to](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/QueryField/QueryField.tsx#L153) `QueryField` `onChange` and then we are using it to update the query based on value from input field. So when you copy-paste the value with `carriage return`, we would use in onChange cleaned value. That way, this would work for all queyr editor that use QueryField. 

What do you think?

**Review by ivanahuckova — COMMENTED** [review]
Sorry for late reply @conorevans, I was out of office around Easter holidays 🐰. I was thinking about implementing removing of carriage return directly in QueryField. [We are passing to QueryField onChange and then we are using it to update the query based on value from input field](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/QueryField/QueryField.tsx#L153). So when you copy-paste the value with carriage return, we would use in onChange cleaned value. That way, this would work for all queyr editor that use QueryField.

What do you think?

**Review by ivanahuckova — COMMENTED** [review]
Disregard, I accidentally added duplicate same review. 🙈

**Comment by conorevans** [comment]
> Sorry for late reply @conorevans, I was out of office around Easter holidays 🐰

No worries at all, hope it went well!

> What do you think?

Yeah your suggestion is naturally correct. I think I got caught up with the name `cleanText` and that led me down a rabbit hole - forgetting of course that state changes are the relevant way to handle this sort of thing in a React frontend 🙃

**Comment by lionbee** [comment]
Instead of only stripping `\r`, is there value in stirpping all non-printable characters?

**Comment by gabor** [comment]
should we maybe remove other forms of "newline" too? like `\r\n` (windows) and `\n` (linux) ?

**Comment by ivanahuckova** [comment]
I would just be careful with other characters to not break the editor. For example, we are using Line feed in QueryEditor.
image

**Comment by ivanahuckova** [comment]
Hello @conorevans! Just wanted to check if you are still planning to work on this? 🙂

**Comment by conorevans** [comment]
Hi @ivanahuckova I can take a look this weekend, but if it's prioritized that's no problem - I don't mind handing it off.

**Comment by ivanahuckova** [comment]
I was just checking 🙂. Thanks for the answer @conorevans.

**Comment by conorevans** [comment]
Hey @ivanahuckova I didn't get to this unfortunately, and probably won't for some time yet.

**Comment by ivanahuckova** [comment]
That's totally okay! 🙂 Thank you for all your work. 💙

I will close this PR so it is clear that the issue is not being worked on and that if someone want's to pick it up, the issue is free and available.

**Pull request closed without merging**
