### PR TITLE
Prometheus: We fixed the issue where the system did not reuse TCP connections when querying from Grafana alerting.

### LINKED ISSUE #40366: Prometheus: TCP connections not reused and cause lots of unnecessary connections when querying from Grafana alerting
**What happened**:
Since v8.2.0, increased amount of goroutines and the Grafana server eventually runs out of TCP connections.

**What you expected to happen**:
Non-increased amount of goroutines. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a Grafana alert using Prometheus. Each time it evaluates the query you should see a growing number of goroutines. Alternatively query prometheus datasource using the the /api/ds/query endpoint.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.0, 8.2.1
- Data source type & version: Prometheus

### PR DESCRIPTION
**Pull request by kminehart**
The function returned by `newInstanceSettings` is ran every time the data source is saved. Instead of initializing the client on every request, we initialize the client in this function, and simply fetch the initialized client whenever we need it.

Fixes #40366

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
See comments

**Review by marefr — COMMENTED** [review]
Code looks good. Great 👍 But want to test it and going to do that first thing tomorrow

**Review by radiohead — APPROVED** [review]
🚀

**Review by marefr — APPROVED** [review]
LGTM

**Querying Prometheus via /api/ds/query endpoint each second:**

_Before fix:_
image (1)

_After fix:_
Selection_1060

**Pull request merged**
