### PR TITLE
Nav: Handle app plugin installation/uninstallation

### LINKED ISSUE #47276: Plugins: App plugins should auto appear/disappear from the nav when installed/uninstalled
**What happened**:

https://user-images.githubusercontent.com/1173299/161573666-795c7d27-975d-4d22-a32f-8b334a679be2.mov

**What you expected to happen**:
App plugins should auto appear/disappear from the nav bar when installed/uninstalled

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

- When uninstalling an app plugin, remove it from the navigation.
- When installing one, show a notice that the page needs to be refreshed.

[Screencast from 24-02-23 10:57:36.webm](https://user-images.githubusercontent.com/4025665/221149711-6db5cb79-5a2e-4a5c-bcdf-87965e94e9c0.webm)

**Why do we need this feature?**

At the moment, the navigation item for uninstalled app plugins are not removed when ethe plugin is uninstalled. There is also no feedback of what's needed when you install one.

**Which issue(s) does this PR fix?**:

Fixes #47276

**Special notes for your reviewer**:

My original idea was to also add the plugin navigation item when installing it without having to refresh but the navigation tree is generated at boot time (saved at  `window.grafanaBootData`) and as far as I can see, there is no easy way to regenerate it  from a component. Let me know if you know a way of doing that.

cc/ @wbrowne

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
Have tested and LGTM 🚀 

Will let @grafana/plugins-platform-frontend have the final say on the code changes

**Review by jackw — APPROVED** [review]
Awesome work on this @andresmgot! 🚀 

>My original idea was to also add the plugin navigation item when installing it without having to refresh but the navigation tree is generated at boot time (saved at window.grafanaBootData) and as far as I can see, there is no easy way to regenerate it from a component. Let me know if you know a way of doing that.

I don't think there currently is a way. I wondered about `/api/frontend/settings` but then I realised it only contains a subset of the grafanaBootData. 😞

**Review by leventebalogh — APPROVED** [review]
Nice one! 👏 

Would make sense to provide a way from the backend to fetch the up-to-date navtree using an API? I think there will be more and more places where we are going to need this functionality.

**Comment by andresmgot** [comment]
> Would make sense to provide a way from the backend to fetch the up-to-date navtree using an API? I think there will be more and more places where we are going to need this functionality.

It would make sense to me :shrug: Thanks!

**Pull request merged**
