### PR TITLE
Logs: Derived fields link design

### PR DESCRIPTION
**Pull request by aocenas**
Idea from @tomwilkie about improving the design:

Screenshot from 2020-04-20 12-06-16

Fields are sorted, with links first then alphabetically. The links themselves are Tag elements and if it is external then hostname is shown, otherwise the datasource name. The Tag element by default assigns color based on label hash, so the same labels have same colors but otherwise they are assigned randomly same as dashboard tags, may be useful or we can just use single color for it no strong feelings about that.

### CODE REVIEW

**Comment by jessover9000** [comment]
This is probably just me lacking product knowledge, but what's the added benefit of having the level links at the top? also what's the benefit of having links colored the same color as the label tags? If there are too many colors here it might get overwhelming.

**Comment by sarlinska** [comment]
@aocenas a couple of questions:
1. Why do we show the ones with links first and then alphabetically?
2. "The links themselves are Tag elements" – I think it works. "if it is external then hostname is shown, otherwise the datasource name" what happens if you click on those?
3. "so the same labels have same colors but otherwise they are assigned randomly same as dashboard tags" would there be any reason to not do it randomly? 
4. "may be useful or we can just use single color for it no strong feelings about that" will there be several identical links in one view?

**Comment by aocenas** [comment]
@jessover9000 
> This is probably just me lacking product knowledge, but what's the added benefit of having the level links at the top?

Well as I said I just changed the ordering so it is alphabetical but links first. Links first was a suggestion to make the links more prominent and visible.

> also what's the benefit of having links colored the same color as the label tags?

Not sure what you mean. As I said I just used the same component which behaves this way. Whether it is useful I am not sure, could be but don't have strong opinion on that so if you say it would be better to have a single color for them than I will change it.

@sarlinska 
> Why do we show the ones with links first and then alphabetically?

As mentioned "Links first was a suggestion to make the links more prominent and visible.
". Regarding alphabetical ordering, well I suppose it is better than having them random.

> "The links themselves are Tag elements" – I think it works. "if it is external then hostname is shown, otherwise the datasource name" what happens if you click on those?

External is just normal link that will open it in new tab by default. Internal will open a new explore split with the predefined datasource and query. At the moment the internal cannot be opened in separate tab by cmd-click or similar but want to fix that.

> "so the same labels have same colors but otherwise they are assigned randomly same as dashboard tags" would there be any reason to not do it randomly?

Again just how tags work at the moment. It may be useful to  color code the same links but really no strong feelings about that.

> "may be useful or we can just use single color for it no strong feelings about that" will there be several identical links in one view?

User defines those so maybe. Could be a traceId going to full trace and spanID going to just that span, both pointing to the same external hostname. Or multiple links to some internal admin panel one going to user profile second to his shop history or something.

**Review by jessover9000 — APPROVED** [review]
Ok, after some explanation from @aocenas I think this works fine. It absolutely makes sense to sort alphabetically, and if the links are important and need visibility, sure let's put them to the top.

**Comment by tomwilkie** [comment]
My comment to @aocenas was that it take too much clicking and scrolling to get to the trace, the link is too small and generally this feature is very undiscoverable:

image

(It also seem to be broken in master, but that unrelated).

**Comment by aocenas** [comment]
@tomwilkie opening the link in separate tab is know issue, this https://github.com/grafana/grafana/pull/23757 will fix that.

Regarding the discover-ability, yes this probably won't help that much in general, that probably needs change of how logs are shown before opening the log detail, but should at least make the links more obvious.

I think we won't be able to improve it much more before Monday branch of unless someone has a idea that would be super quick to implement.

**Comment by aocenas** [comment]
Decided to use single color for the links as not all the colors looked good in both themes:

Screenshot from 2020-04-22 13-52-07
Screenshot from 2020-04-22 13-52-22

**Comment by davkal** [comment]
> Regarding the discover-ability, yes this probably won't help that much in general, that probably needs change of how logs are shown before opening the log detail, but should at least make the links more obvious. I think we won't be able to improve it much more before Monday branch of unless someone has a idea that would be super quick to implement.

I think it's massively helpful to be able to jump to something related to a log message w/o having to open the details. We considered inline decorations before and never got past their downsides. 

My quick solution would be a div container that floats on the right side of each log line and contains the matched field buttons. Ideally with an icon to show that you will go somewhere else if you interact with it. Very crude mockup:

Screenshot 2020-04-22 at 22 12 20

**Comment by aocenas** [comment]
@davkal Yeah I can play with something like that. Could be also done as link icon and on hover of that it would show all the links that way we could show the icon in relevant rows without occluding any of the text (but you would not see what kind of links there are until you hover).

In any case if that's ok I would merge this and as I said bit strapped on time so would take a look at the the improvement later on.

**Comment by tomwilkie** [comment]
> on hover

Yes please :-)

**Review by ivanahuckova — APPROVED** [review]
I have tested this locally. Looks good, works smoothly and as expected. 
Good job Andrej!
LGTM 🚀

**Pull request merged**
