### PR TITLE
grafana/toolkit: Support paging in cherrypick task

### LINKED ISSUE #22891: grafana/toolkit: cherrypick subcommand should ignore unmerged PRs
**What happened**:
`npx grafana-toolkit cherrypick` listed a PR that was closed. It should be ignored even if it has the "cherry-pick needed" label and the right milestone. AFAICT, only PRs _merged to master_ should be considered.  

**What you expected to happen**:
For PRs not merged to master to be ignored.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PR with label "cherry-pick needed" and the next version as its milestone, run `npx grafana-toolkit cherrypick`. The PR should be listed.

### PR DESCRIPTION
**Pull request by dprokop**
Quick fix for the cherrypick task

Closes #22891

### CODE REVIEW

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Making a couple of suggestions, I think they are right.

**Comment by dprokop** [comment]
Yes they are, commited

**Review by aknuds1 — APPROVED** [review]
LGTM! Bit difficult to tell if it actually works without testing though :)

**Comment by dprokop** [comment]
@aknuds1 you can test. Just change tle label and number of items per page

**Comment by dprokop** [comment]
then ` ./node_modules/.bin/grafana-toolkit cherrypick` from grafana root dir

**Comment by marefr** [comment]
For beta1 I did a quick fix for paging when generating changelog which you should be able to reuse, #23997

**Comment by dprokop** [comment]
@aknuds1 in 8064ff4 I'm fixinf the issue with closed PRs being listed for cherry picking (#22891)

**Review by hugohaggmark — APPROVED** [review]
Wow that was fast LGTM!

**Pull request merged**
