### PR TITLE
[v9.0.x] Fix website build errors 

### PR DESCRIPTION
**Pull request by jdbaldry**

### CODE REVIEW

**Comment by jdbaldry** [comment]
CI failure is unrelated and due to a failing Alertmanager integration test. I think this should be merged ignoring that CI failure unless someone from @grafana/alerting-squad wants to fix it.

**Comment by armandgrillet** [comment]
I've added a commit that should fix the alerting test.

**Comment by armandgrillet** [comment]
CI is passing now ✅

**Comment by jdbaldry** [comment]
> CI is passing now white_check_mark

Thank you so much!

**Review by Eve832 — APPROVED** [review]

**Pull request merged**
