### PR TITLE
Explore: Avoid sending panelId header unless we are in a dashboard

### PR DESCRIPTION
**Pull request by ryantxu**
Queries from explore currently include the panel-id in its request metadata even though the value does not map to anything useful.

This PR removes the useless header

### CODE REVIEW

**Comment by aocenas** [comment]
We should check graphite as it may be using this for cancelation. @grafana/observability-metrics can you maybe check this if the panelId is needed or not?

**Comment by bohandley** [comment]
> We should check graphite as it may be using this for cancelation. @grafana/observability-metrics can you maybe check this if the panelId is needed or not? There is some reference in the code
> 
> https://github.com/grafana/grafana/blob/dbec8465e571b80f1d384f95d2fdf680f0e62404/public/app/plugins/datasource/graphite/datasource.ts#L243
> 
> but not sure if this is important or not.

Hi @aocenas, this reference to panel id was done 7 years ago here. I'm honestly confused as to why or how this is used or how to test this as it was years before my time. https://github.com/grafana/grafana/commit/ddf579f204057f86d05330f98fb2b4fa4bf92278

https://github.com/grafana/grafana/issues/5617

If we can confirm that dashboards squad has a fix for a mixed data source with two graphite data sources, I am fine with this. But also know, graphite was never fully migrated as a backend data source so there might be some weird effects.

**Comment by ifrost** [comment]
> I'm honestly confused as to why or how this is used or how to test this as it was years before my time. [ddf579f](https://github.com/grafana/grafana/commit/ddf579f204057f86d05330f98fb2b4fa4bf92278)

It seems Graphite doesn't extend DataSourceWithBackend but adds the header manually [here](https://github.com/grafana/grafana/blob/dbec8465e571b80f1d384f95d2fdf680f0e62404/public/app/plugins/datasource/graphite/datasource.ts#L262). I don't have full context but it was added in https://github.com/grafana/grafana/pull/12089.

This needs to be approved by the codeowners (@grafana/grafana-frontend-platform and @grafana/plugins-platform-frontend). Might be worth checking with data source plugin devs using DataSourceWithBackend.

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Review by svennergr — APPROVED** [review]
Seems this is causing more confusion than is helpful. I approve, even though I am not part of 
> This needs to be approved by the codeowners (@grafana/grafana-frontend-platform and @grafana/plugins-platform-frontend). Might be worth checking with data source plugin devs using DataSourceWithBackend. Explore code doesn't rely on this header so I'll remove Explore squad from reviewers.

**Pull request merged**
