### PR TITLE
EventsCanvas: Clean up action to avoid memory leak

### PR DESCRIPTION
**Pull request by lean257**
**What this PR does / why we need it**:

We need to ensure the component is mounted before we do any change to state, otherwise we leak memory.
**Which issue(s) this PR fixes**:
We were getting this error in the console when switching legend mode to hidden.
Screen Shot 2021-08-05 at 8 30 35 AM

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ryantxu** [comment]
@lean257 -- what is the state of this PR?  should we try to fix before 8.1.2?

**Review by ryantxu — APPROVED** [review]
LGTM

**Comment by ryantxu** [comment]
Hymm -- I think this caused a real issue with e2e tests :( and exemplars

image

**Comment by hugohaggmark** [comment]
Skipping the failing e2e test (https://github.com/grafana/grafana/pull/37991) for now until the issue Ryan mentioned is fixed. Please revert the e2e test `skip` when you've fixed the issue @lean257. Thank you 🙏

**Pull request merged**
