### PR TITLE
Id name mapping

### PR DESCRIPTION
**Pull request by IzakMarais**
Pull request to implement #1153. Please see that issue for comments on implementation as well as gifs demoing functionality.

### CODE REVIEW

**Comment by IzakMarais** [comment]
When looking up an ID, elasticsearch should not use fuzzy matching; switched to [Term Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html). Ensure your 'id' field mapping is set to "not_analyzed".

**Comment by IzakMarais** [comment]
@torkelo I *have* signed the CLA. I signed it again now using the [Details](https://cla-assistant.io/grafana/grafana?pullRequest=3334) link above. However I do not see the status updating.

Is _This branch has conflicts that must be resolved_ referring to the CLA? Or have new changes to master branch introduced merge conflicts? If so, am I responsible for rebasing my feature branch onto the latest master?

**Comment by torkelo** [comment]
I am not sure about this PR, adds a lot of complexity. Will need to think about it more. And will need some more interest from community (+1 votes).

**Comment by IzakMarais** [comment]
> will need some more interest from community

So far, 7 people have expressed interest in #1153.

**Comment by mtanda** [comment]
+1

I want to prepare "mapIdQuery" for CloudWatch plugin when this PR is merged.
For AWS environment, I want to use this to map "instance id" to values of EC2 instance tags.
It is very useful, because instance id (like "i-0123abcd") is meaning less, we want to know instance name (like "www-0001").

**Comment by utkarshcmu** [comment]
+1 for instance-id to ip mapping

**Comment by torkelo** [comment]
I would prefer, at least as preliminiary step to only support hard coded ip maps in the dashboard model. To really use this feature would require some automation around dashboard creation, but since this is such an advanced feature I think that is ok. The problem with the current implementation is that it introduces a lot of new code and complexity for a very advanced edge case.

**Comment by IzakMarais** [comment]
Very fair comments; hard coded maps in the dashboard model will be much simpler. We already use scripted dashboards for some automatic dashboard creation, so that could have worked.  

Rather than change the implementation now, I will maintain the fork for our internal use until either:
* maintaining the fork becomes more painful than making the changes, or 
* someone else implements the required, simpler behaviour

**Comment by g00g1e** [comment]
I need this feature

**Comment by CME64** [comment]
I think if variables were to be equipped with a mapping feature where you can map some value with another it will act the same way as this change

**Pull request closed without merging**
