### PR TITLE
Chore: Fix dev profiling

### PR DESCRIPTION
**Pull request by toddtreece**
**What is this feature?**

* set `-profile-addr` to `0.0.0.0` in dev so that the self-instrumentation devenv agent can hit grafana
* update the self-instrumentation profile port to `6000` to match the CLI arg

**Why do we need this feature?**

the self-instrumentation devenv profiling is broken on linux

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by JohnnyQQQQ — APPROVED** [review]
LGTM

**Comment by andresmgot** [comment]
hi @toddtreece @JohnnyQQQQ, after this change, Mac OSX complains that you are opening a network connection everytime you start Grafana:

image

This also happens if you don't set the Grafana `http_addr`, but that can be modified through configuration. Is there a way to configure this so devenv agent can still hit grafana but run it with `127.0.0.1` if you are just running `make run` locally?

**Comment by toddtreece** [comment]
@andresmgot i have to approaches for this:
https://github.com/grafana/grafana/pull/91914
https://github.com/grafana/grafana/pull/91916

**Comment by andresmgot** [comment]
FWIW #91914 sounds good to me! Thanks for taking a look!

**Pull request merged**
