### PR TITLE
StateTimeline: also insert terminating null value for 1-datapoint frames

### LINKED ISSUE #46805: [State Timeline] Absence of data not represented anymore (part 3)
**What happened**:

This is a follow up of https://github.com/grafana/grafana/issues/45852 which should have been fixed by https://github.com/grafana/grafana/pull/45997 in 8.4.4 but some glitches remain (see https://github.com/grafana/grafana/issues/45852#issuecomment-1074190354). Ping @leeoniya.

In some cases, bars from the state timeline panel still remain open while should be be closed (time-series vanished, value should be null).

**What you expected to happen**:

See https://github.com/grafana/grafana/issues/45852

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a proper reproducer yet but here is my initial observation / gut feeling. I think remaining issue is related to the frame having a single data point.

Here is a truncated & redacted response leading to bar not being closed.

```
{
	"frames": [
		{
			"schema": {
				"name": "<redacted>",
				"refId": "A",
				"meta": {
					"custom": {
						"resultType": "matrix"
					}
				},
				"fields": [
					{
						"name": "Time",
						"type": "time",
						"typeInfo": {
							"frame": "time.Time"
						},
						"config": {
							"interval": 120000
						}
					},
					{
						"name": "Value",
						"type": "number",
						"typeInfo": {
							"frame": "float64",
							"nullable": true
						},
						"labels": {
							"exported_app": "<redacted>",
							"fqdn": "<redacted>"
						},
						"config": {
							"displayNameFromDS": "<redacted>"
						}
					}
				]
			},
			"data": {
				"values": [
					[
						1647875040000
					],
					[
						0
					]
				]
			}
		}
	]
}
```

Real response has many similar frames all leading to similar behaviors. Same response has a frame with multiple timestamps and its bar behave like expected

```
{
	"data": {
		"values": [
			[
				1647869880000,
				1647870000000,
				1647870120000
			],
			[
				503,
				503,
				503
			]
		]
	}
}
```

**Environment**:
- Grafana version: 8.4.4
- User OS & Browser: Firefox 98

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #46805

not strictly for StateTimeline, but the most visible effect is there.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by leeoniya** [comment]
the `interval` failures look unrelated to this changeset (also seeing them on `main`). will rebase this once they're fixed.

**Comment by cykl** [comment]
@leeoniya I'm trying to understand which Grafana versions contain the fix. 

 * This MR says backport 8.4.x and 8.4.7 milestone
 * Changelog says nothing about it (I checked 8.5.0 and 8.4.6)
 * git tag --contains says v8.5.0, v8.5.0-beta1
 * I manually inspected v8.4.x and failed to find relevant commit

I would be if Grafana changelog remained as accurate as they used to be. I had already had to use git tag --contains earlier this year for other issues, which make me think that their is problem somewhere.

**Comment by leeoniya** [comment]
ugh, i'm still learning the art of PR tagging :roll_eyes: 

8.4.6 was a security release, so it contained no additional features or bug fixes. but this is not often known in advance, so even though i tagged it for 8.4.6, there was no way for it to make it into that release.

https://github.com/grafana/grafana/commit/0606c66b8de0b587950eb9bb0064dd56032e9657 i guess never merged into the 8.4.x branch. i dunno why @grafanabot did not auto-create a backport PR for it, so it woul dnot have been in 8.4.7 either.

i ususally check what PRs a release contains by looking at the `release*` branch:

image

indeed, the commit appears on the 8.5.0-beta1 release branch:

https://github.com/grafana/grafana/commits/release-8.5.0-beta1?after=01948735a788719fbdc664d87fcd795d2367dbd6+34&branch=release-8.5.0-beta1

**Comment by CourchesneA** [comment]
I am having a bit of trouble understanding all the versionning, but it seems my instance of grafana cloud it using the most recent release and it does not contain this fix. Any idea when this will be merged into 9.0.0 ?

**Comment by leeoniya** [comment]
we might have re-broken this recently :grimacing: 

probable fix: https://github.com/grafana/grafana/pull/50988

**Pull request merged**
