### PR TITLE
Logs: Relocate "show context" button, add copy line log button 

### LINKED ISSUE #50871: Relocate "Show context" button and add copy of log line button
### Background / Why we're doing this

Problem
Today the "Show context" button is located at the end of a log line text and appears when hovering over a log line. The implemented button is not the one we currently use. Additionally is the position of the button not consistent, but it alters by the length of the log line text.
Bildschirmfoto 2022-06-15 um 13 46 55

### Is there existing research for this?

No research yet

### Problems or tasks

_No response_

### Deliverables

**Proposal**
We'd like to change the text button to an icon button. Additionally we'd like to add a "copy" button to let the user copy the whole log line text with one click.  Both buttons will be moved the the the upper right corner within the highlighted/hover log line and they will be placed on a rectangle. The rectangle will have a shadow (z2).
These buttons will only appear when the user hovers over a log line.

Here's a mockup of what it would look like after this change:
Bildschirmfoto 2022-06-15 um 13 30 26
Bildschirmfoto 2022-06-15 um 13 30 33
Bildschirmfoto 2022-06-15 um 13 30 44
Bildschirmfoto 2022-06-15 um 13 57 59
Bildschirmfoto 2022-06-15 um 13 58 10

### PR DESCRIPTION
**Pull request by Seyaji**
Fixes #50871

After implementing this locally I have discovered some issues when following the mockup, mostly when dealing with single-line log displays. Functionally it does what it's supposed to (if I'm not mistaken).

Screenshot 2022-06-16 at 17 34 13

Issue 1:  Box overlap
The sizing parameters that were given cause the box to overlap on single-line log entries.

Screenshot 2022-06-16 at 17 06 12

Issue 2: Misalignment on show context display
The height of the box causes the logos to be out of line and makes them almost unreachable. The alignment requested also makes the box stick out to the side.

Screenshot 2022-06-16 at 17 06 00

More to note: 
The z2 shadow doesn't match the mockup I have used z3 in the examples above.
I cant find the logo used for show context in [developers.grafana.com](https://developers.grafana.com/)
 
Possible solution: 
I quickly made some changes and have a potential alternate, this needs some tweaking but might work.

Screenshot 2022-06-16 at 17 15 34
Screenshot 2022-06-16 at 17 15 43

Perhaps have the logos appear the same way as the copy icon requested on label values?
Screenshot 2022-06-16 at 05 11 46

I await further guidance from the UX team on this. 
Thanks 🙂

### CODE REVIEW

**Comment by svennergr** [comment]
Hi @Seyaji,

first of all: thank you so much for your contribution - much appreciated.

The placement and size of the `show context`-button is indeed not a trivial improvement and, as you showcased, the currently envisaged solution might not be perfect.
We are currently discussing this with our UX team and will come back to you, as soon as we have an update to share.

Best regards,
@svennergr

**Comment by Seyaji** [comment]
@svennergr Thanks for your response, happy to help!

**Comment by svennergr** [comment]
Hi @Seyaji,

we decided to not further persue an implementation of a new "show context"-button, as your development covered up some UX difficulties with it. 

Nevertheless, thank you so much for your contribution and sorry to close this now.

**Comment by svennergr** [comment]
Hi @Seyaji,

sorry - I missread some internal messages. I will reopen this PR and come back before end of the week, how we proceed with the show-context buttons.

**Comment by svennergr** [comment]
Hi @Seyaji,

just to provide an update regarding your initial UX question: 
We are currently planning to go with the initial plan and deliberately chose the overlapping of the buttons.

The designated icon will be provided soon, but are you able to proceed with this information or do you need anything besides the icon to get this PR out of the "draft"-state?

Thank you again for your contribution! 🤩

**Comment by Seyaji** [comment]
@svennergr Thats good for me, once the icon is provided I can update it and submit the final request

**Comment by svennergr** [comment]
Hi @Seyaji,

we decided to move on with the `align-center-v` icon. To use that, you first need to add that string to https://github.com/grafana/grafana/blob/bump-slate/packages/grafana-ui/src/types/icon.ts#L8 and then can use it at that button.

Please let me know if you need further guidance.

Thanks!

**Review by svennergr — APPROVED** [review]
LGTM

**Comment by svennergr** [comment]
Thanks for your contribution @Seyaji - much appreciated! 

Alt Text

**Pull request merged**
