### PR TITLE
Auth: Show user sync external Authentication status

### PR DESCRIPTION
**Pull request by lokeswaran-aj**
**What is this feature?**
related #56189. 
Checks if user is sign in with external authentication and show `Synced via [authenticator]` text beside `Change role` button.

**Why do we need this feature?**
When assigning roles for users in Grafana that have been synced via an external auth provider it clearly says the admin why he/she could not change the role of the user.

**Which issue(s) does this PR fix?**:
related #56189 

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Jguer** [comment]
Hey @lokeswaran-aj , we are interested in merging your PR

can we move to the option 1 you proposed?

image

**Comment by lokeswaran-aj** [comment]
@Jguer I have updated the branch to the latest commit. I could not remember the context, what do you mean by option 1?

**Comment by Jguer** [comment]
The tooltip on the right of the "Synced via x" instead of on the left :slightly_smiling_face:

**Comment by lokeswaran-aj** [comment]
@Jguer Sure, will update the code and push the code

**Review by Jguer — APPROVED** [review]

**Pull request merged**
