### PR TITLE
Added W/m2(energy), l/h(flow) and kPa(pressure)

### PR DESCRIPTION
**Pull request by flopp999**
all as .fixedUnit

https://github.com/grafana/grafana/issues/5483

https://github.com/grafana/grafana/issues/2968#issuecomment-278057277

### CODE REVIEW

**Comment by flopp999** [comment]
check error, is this something I did wrong?

**Comment by marefr** [comment]
@flopp999 no the failing test is not related to your changes. We'll look into why that tests sporadically failing.

**Comment by flopp999** [comment]
Will this be added to a milestone soon?

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
