### PR TITLE
Thresholds for Right Y axis

### LINKED ISSUE #7107: [Feature Request] Thresholds for Right Y axis
Grafana 4.1 beta.

I can only define thresholds for Left Y axis, not Right Y axis.

### PR DESCRIPTION
**Pull request by ilgizar**
Fix #7107

### CODE REVIEW

**Review by Ijin08 — CHANGES_REQUESTED** [review]
This looks good and works as it should. But there is one issue. When I open a graph panel that has a threshold from before trying this branch I get this:
image
image

**Review by ilgizar — COMMENTED** [review]
Thank you, I corrected the mistake you found.

**Review by Ijin08 — APPROVED** [review]

**Comment by torkelo** [comment]
can be merged after we branched of v5.0

**Comment by bergquist** [comment]
5.0.0 is released. Merging this!

**Pull request merged**
