### PR TITLE
Allow variables in Axis boundaries

### LINKED ISSUE #3935: Feature Request: variables in X/Y-Max/Min
Let's say you have a set of network graphs for several servers. They all have different scale as Y-Max is set to auto. You can set it to 1073741824 ( 1 gigabit ) for all the graphs but it won't make much sense. Defining a max value with a template variable could be really helpful in this case.

### PR DESCRIPTION
**Pull request by simPod**
Resolves #3935

### CODE REVIEW

**Comment by torkelo** [comment]
thanks for contributing to Grafana! We are a bit overloaded with PRs but hope to get to review & decide on this one soon.

**Comment by torkelo** [comment]
Min & Max are numbers, and the inputs do store them as strings, numbers is also supported. Think having these inputs accepts strings is wrong and likely something we want to fix in the future. 

Will close this for now, think dynamic thresholds can be implemented in a different way maybe using a revamped scripted dashboard feature that we hope to do sometime next 1-2 years.

**Comment by simPod** [comment]
@torkelo IMO this could be simply tweaked and merged as a temporary replacement until that revamp is done. 1-2 years sound like ages. According to https://github.com/grafana/grafana/issues/3935 it looks like it would be appreciated not by me only...

Do not understand what is meant by
> Min & Max are numbers, and the inputs do store them as strings, numbers is also supported

This seems to be handling it all `return _.toNumber(this.ctrl.templateSrv.replace(value, this.ctrl.panel.scopedVars));`

**Comment by brandond** [comment]
You're gonna block a long-requested feature pending a complete rewrite that you hope to have done in TWO YEARS!?

**Comment by hb0nes** [comment]
After applying this patch, how would I go about actually using metrics as a max value? I can't seem to do it.
FYI, I just edited the graph.ts file and restarted Grafana.

**Pull request closed without merging**
