### PR TITLE
support AWS V4 sign in proxy

### LINKED ISSUE #7245: [Feature Request] Support AWS SigV4 authentication for Elasticsearch Datasource
I would like to use an [Amazon Elasticsearch Service](https://aws.amazon.com/elasticsearch-service/) cluster as an Elasticsearch datasource in Grafana. This works just fine if I allow public access to the cluster, but I'd prefer to lock it down to authenticated users only.

The only user-level access control Amazon ES supports is [through AWS SigV4 signing the HTTP requests to Elasticsearch with IAM credentials](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies). For example, [here's how the Golang `elastic` client does it](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service).

I had a look at how the `proxy` mode of the ElasticSearch datasource works, and it looks like it would be pretty straightforward to build this signing into `dataproxy.go`, similarly to [how it's handled for the CloudWatch data source.](https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go#L81-L84)

### PR DESCRIPTION
**Pull request by mtanda**
Fixes https://github.com/grafana/grafana/issues/7245

### CODE REVIEW

**Comment by torkelo** [comment]
not sure this is a good idea, this should probably be in the elasticsearch tsdb go code (that is yet to be merged to master):

Hope to move Elasticsearch query & response handling to 100% backend 
https://github.com/grafana/grafana/tree/alerting-elasticsearch

But in the mean time I am not sure I like making the data proxy code this complicated, this needs a lot of refactoring & cleanup to be maintainable.

**Comment by mtanda** [comment]
I intend to use this for not only AWS Elasticsearch.
For example, we create datasource for simple json plugin by API Gateway.
API Gateway can restrict access by IAM, so I need this feature for protecting API Gateway.

I change the code, add `awsutil` components.

By this change, elasticsearch backend can use this feature easily.
Just calling `awsutil.SignV4(req, targetUrl)` at this line, 
https://github.com/grafana/grafana/blob/b80da6ecf00bf89026f0a345f6400797a46f0e76/pkg/tsdb/elasticsearch/elasticsearch.go#L148 .

**Comment by mtanda** [comment]
AWS has a lot of feature, but safety access for these feature needs IAM.
It is the reason why CloudWatch datasource is implemented in `backend`.

If this feature is merged, plugin developer can create datasource plugin.
- get logs from `CloudWatch Logs` and display it in table panel
- get operation history from `CloudTrail` or `AWS Config` and display it in table panel
  - Datadog support it, http://docs.datadoghq.com/integrations/awscloudtrail/
- integrate with AWS IoT, get data and visualize it

**Comment by mtanda** [comment]
This is a use case of API Gateway.
https://www.linkedin.com/pulse/using-aws-lambda-api-gateway-server-less-grafana-adapters-jonas-birm%C3%A9

I want to make safe by using IAM to restrict API access, and let Grafana has the privilege.

**Comment by bergquist** [comment]
Hmm. This makes sense. But I\m not sure about how to implement it. I guess the prefered way would be something like a middle ware but for out going requests for proxy/tsdb requests.

**Comment by mtanda** [comment]
Recently, I found good module for nginx.
https://github.com/adobe-apiplatform/api-gateway-aws
I use it for calling Lambda from Prometheus, and planned to use it for Grafana.

But, if Grafana itself has such proxy feature, it is very useful.

**Comment by torkelo** [comment]
Not sure about this. Need a more generic solution that can work for both proxy and backend calls (alerting).  

Maybe an external proxy solution is better? (https://github.com/adobe-apiplatform/api-gateway-aws)  but this seems like a popular feature request so I am open a have this in Grafana if we can find a nice generic solution that works for all outgoing DS requests.

**Pull request closed without merging**
