### PR TITLE
Dashboard: Fix Prometheus instant queries

### LINKED ISSUE #16661: Using the "Today" time view causes Prometheus to return empty result for instant queries
**What happened**: When changing Grafana to the "Today" view, Prometheus returns the following response to all "instant" queries:
```
{"status":"success","data":{"resultType":"vector","result":[]}}
```
Which results in Grafana errors:
Screen Shot 2019-04-17 at 6 09 05 PM

**What you expected to happen**: Prometheus should return a "good" value for instant queries when the time range in Grafana is set to Today, as shown in this "Last 12 Hours" view:
Screen Shot 2019-04-17 at 6 08 45 PM

**How to reproduce it (as minimally and precisely as possible)**:  Create a chart that uses instant queries to Prometheus, such as the one in the screen shots, and then change the view to "Today" in the time range selector. In my example case, the instant query is `prometheus_build_info` populating a Singlestat with "version" selected for the column. The label, which normally displays the Prometheus version, will show "N/A" when in Today view.

**Anything else we need to know?**: When I use the Today view, Grafana is adding a time parameter onto all instant queries with an epoch time representing midnight my local time tomorrow, which at the time of this report is just over 5 hours into the future. Since Prometheus doesn't have data for the future, the returned result set is _always_ empty. You should use the current epoch timestamp for the instant `time` parameter (as is done with the relative-from-now views) instead of midnight tomorrow when in the Today view.

**Environment**:
- Grafana version: 6.1.4 (fef1733)
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: coreos? (Official Docker Container: grafana/grafana:6.1.4)
- User OS & Browser: MacOS 10.14.4, Chrome 73
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by jakeg12**
**What this PR does / why we need it**:
This PR changes the logic used to prepare the request to the Prometheus API to overwrite future-dated time parameters to a blank string, causing the most recent information to be returned from Prometheus.

Prior to this change, the future-dated request would return no data and an "N/A" would be displayed in users' dashboards.

**Which issue(s) this PR fixes**:

Fixes #16661 

**Special notes for your reviewer**:
I went this route rather than trying to handle the datetime being sent by the UI because the blast radius was _much_ smaller. The added benefit of rewriting the parameter is that any other/new callers of the Prometheus instant query functions wouldn't have to replicate that logic. I also didn't straight-up hard code the date parameter because there may be cases when an instant query at a previous datetime is useful.

--Jake

### CODE REVIEW

**Comment by jakeg12** [comment]
Only one test failed, due to #18054

**Comment by torkelo** [comment]
is not more accurate that future dated requests return no data?

**Comment by alastrange** [comment]
Future dated requests should probably return no data.

In the original issue #16661 the behavior of the Today timeframe using Instant returned no data because the requested time was 12AM the next day.

If you choose “24 hour” when using instant, the current time stamp is requested.  I would expect the same request to be generated using “Today”

**Comment by jakeg12** [comment]
I think you could probably split this into two cases.

1) I have a dashboard that represents my system today. In that I have instant queries like the version of a dependency. In that case I want the same behavior as the graphs show, which is the most recent info (what this handles)

2. I am specifically looking at instant queries and I’m picking a single point in time that is in the future. In which case I should see N/As for future dated data in this case. (Possibly I have other instant metrics that do have future dated data?)

A way to solve for this would be checking if both ends of the range are the same before rewriting the request to Prometheus.

How likely is it that someone will do the second though? You’d have to be using custom timeframes. But maybe it’s an easy enough fix that it’s worth it?

**Comment by jakeg12** [comment]
The other thing that I definitely need to change is if both the start and the end of the range is in the future, in which case I’d expect an N/A.

I’ll make that change later today.

**Comment by davkal** [comment]
IMO this change makes a lot of sense:

When looking at time ranges that lead into the future you'll see data leading up to "now", and it's clear when "now" is, because that's when the data stops on time series. Results from instant queries then relate to that "now" that's essentially visible on all time series graph. 

I have a hard time coming up with examples where this can be confusing. But to be sure, we should document this behavior in the instant queries section in the `prometheus.md` docs.

**Comment by SuperQ** [comment]
I'm fairly sure this is not something that should be done. This is going to greatly mess up correctly working queries.

For example, it's common to combine Grafana's `$__range` variable with instant queries to get some Prometheus `_over_time()` aggregation. For example, `avg_over_time(cpu_utilization[$__range])`.

Say I have a graph of "Today", and I want Prometheus to calculate the daily average as an instant query, if the end time of the instant query is changed to now, it will look back into the past farther than expected.

I made a simple [example dashboard](https://dashboards.gitlab.com/d/_W4xKboWk/time-range-test?orgId=1) to demonstrate the problem.

**Comment by beorn7** [comment]
I think @SuperQ 's example is relevant. I would definitely not change the current behavior to silently manipulate the timestamp of the instant query.

Perhaps the suggested behavior could be opt-in via a checkbox “limit timestamp to now” in the instant query form?

**Comment by SuperQ** [comment]
I thought about a checkbox, but I think that would needlessly complicate the UI.

The root problem here is a misunderstanding of how to use Prometheus data, not a bug in Grafana.

**Comment by beorn7** [comment]
@SuperQ I guess most of the times there is a solution, as you suggested in #16661. But there is no `latest_over_time` function in PromQL. If in your example dashboard, you also wanted to display the latest version used, what PromQL function or aggregation could you use?

**Comment by SuperQ** [comment]
That's a very good question, when dealing with info metrics series like these and alerts, there are a bunch of missing functions. For example, we have a `timestamp()` function that works with instant vectors, but we don't have functions like this: `first_timestamp(prometheus_build_info[1d])`, or `last_timestamp(prometheus_build_info[1d])`.

If we had `last_timestamp()` in PromQL, I would do something like this:

```
topk(1, last_timestamp(prometheus_build_info[$__range]))
```

**Comment by davkal** [comment]
Thanks for all the great feedback. I'm also hesitant to add a new config checkbox. And definitely don't want to mess with the parameters and `$__range` variable.

For queries that guaranteed return only one timeseries, a query like  `avg_over_time(prometheus_build_info[$__range])` works fine as an instant query with a timepicker setting of `Today`.

If your query returns multiple series in a `over_time` query like above, you can use the new SingleStat (react) panel that can handle multiple series. (Need enable alpha panels in grafana ini.)

Closing this PR since the approach has too many unintended consequences.

**Comment by beorn7** [comment]
I'm not opposed to closing this, just as a follow up to @SuperQ 's comment: One might argue that such a function should not exist in PromQL because it is really only a dashboarding concern (compare to how we always said that https://github.com/prometheus/prometheus/issues/586 is not really something that should be solved within Prometheus – and eventually it got solved beautifully [within Grafana](https://www.robustperception.io/graph-top-n-time-series-in-grafana)). From that perspective, _something_ within Grafana should be able to deal with it.

**Pull request closed without merging**
