### PR TITLE
SQL Query Editor: Fix label-for IDs, associate "Table" label

### PR DESCRIPTION
**Pull request by timo**
**What is this feature?**

The inline switches for filter, group, order, and preview were fixed about 7 months ago to have unique IDs, which fixed the wrong switches being flipped when you have multiple editors open. However, the way the code uses uuidv4() to generate the IDs causes the ID of the input element to de-synchronize from the label's for=... attribute, making them unclickable.

While fixing this, I also noticed the "Table" selector doesn't have a working label, so I also added that.

**Why do we need this feature?**

UI / Accessibility Bugfix

**Which issue(s) does this PR fix?**:

I didn't create an issue for this, and I didn't search yet if there already is one.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by timo** [comment]
[labels_fixed_before.webm](https://github.com/grafana/grafana/assets/25167/1f549bb5-a7b1-4a21-89d0-7aa52ac9e61a)
[labels_fixed_after.webm](https://github.com/grafana/grafana/assets/25167/69c14462-b915-4631-8e02-01698e3c88be)

**Comment by timo** [comment]
before:
labels_fixed_before

after:
labels_fixed_after

**Review by aangelisc — APPROVED** [review]
LGTM, however there are some lint issues in the test files due to these changes @timo. Are you able to run the lint command and fix the broken tests?

**Comment by timo** [comment]
I had some trouble with my devcontainers setup and didn't have time to look too closely until now. With my latest commit, locally typecheck and lint are both clean and prettier:write does nothing :)

**Comment by zoltanbedi** [comment]
Nice, the only thing that is failing is the e2e test. I'm going to take a look at it now.

**Review by zoltanbedi — APPROVED** [review]
Thanks for fixing this for us @timo!

**Pull request merged**
