### PR TITLE
Add template variables to the annotations tags

### LINKED ISSUE #9735: Annotation filtering based on template variable
- What Grafana version are you using? 4.6
- What did you do?
Added a new Grafana annotation (using the internal —Grafana— datasource) to a templated dashboard. The machine or server that is inspected is templated on our dashboard. I then choose another machine (changed template variable). 
- What was the expected result?
The annotation should disappear it is only valid in the context of the template variable I selected. 
- What happened instead?
The annotation remained visible. I would like to specify the template variables as annotation context in the annotation definition view.

### PR DESCRIPTION
**Pull request by Strech**
Resolves https://github.com/grafana/grafana/issues/9735

Hola grafana comunity 👋 
I want to add my tiny contribusion to the great project.

Template variables are nice way to squize repeative dashboards to one. I've found that it's impossible to use `$var` in annotations when you try to filter them by tags.

### Motivation

As far we have 2 template variable which make annotation of deployments completely unusable for us. It's `environment` and something like `project`. With environment it's quite easy, just <5 possible values, but projects already count more than 10 ...

First of all we have tried to put `$project` right inside the tag value and as you know – it's not working. In the linked issue @PaulKuiper suggest to have some filter to filter out annotations, but I think we should follow less surprising approach and as soon as you expect that template variables are working in graphs, you will expect them working in tags also.

### UI

general view

### Implementation

Solution is quite simple – single value template variables is replaced with one `tag` option, multi – with multiple `tag`

requests

### CODE REVIEW

**Comment by shudayo** [comment]
❤️ 💟

**Comment by torkelo** [comment]
the templating system is a string interpolation based system, so not sure this is the right approach. Need a different way to support multi valued variables. 

Originally when I worked on the annotations feature I tried to make a special kind of annotation toggle that allowed tag selection directly from the dashboard top section (instead of a checkbox like how annotation queries work now)

**Comment by Strech** [comment]
@torkelo Not sure that I understood what you mean. Maybe you can highlight your idea how you would like to see tags in annotations + template usage there (maybe a screenshot of current things to change) and I will try to suggets implementation?

Would ❤️ to help.

**Comment by torkelo** [comment]
closing this in favor of this simpler approach  (https://github.com/grafana/grafana/pull/10163)

**Comment by Strech** [comment]
@torkelo thanks!

**Pull request closed without merging**
