### PR TITLE
API: Get swagger spec up to date

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
`make swagger-api-spec` produces these changes

Might have to do some digging to see what milestone makes most sense
EDIT: Looks like 8.5.0 is fine

### CODE REVIEW

**Review by marefr — APPROVED** [review]
I guess it makes sense. I'll wait for Sofia to see what she thinks.

**Comment by papagian** [comment]
I think that the changes are also included [here](https://github.com/grafana/grafana/pull/46037) and only consist of re-ordered parameters but if you spot something more, please point it to me!

**Comment by gillesdemey** [comment]
All ready for this PR to be rebased :)

**Comment by wbrowne** [comment]
Looks like just ordering is left @papagian - is there anything that's making the spec generation inconsistent?

**Comment by papagian** [comment]
> Looks like just ordering is left @papagian - is there anything that's making the spec generation inconsistent?

I think that it's because of [the tool](https://github.com/go-swagger/go-swagger/issues/2299).

**Pull request closed without merging**
