### PR TITLE
Dashboard: Tweak resize handle style

### PR DESCRIPTION
**Pull request by torkelo**
Related to scenes bugfix: https://github.com/grafana/scenes/pull/566 

Always felt the resize handle a bit too subtle, exploring making it a bit bigger: 

Current: 
Screenshot 2024-02-04 at 18 38 46
Screenshot 2024-02-04 at 18 39 17

Proposed change A (bigger, using strong border theme color) 
Screenshot 2024-02-04 at 18 40 07
Screenshot 2024-02-04 at 18 40 38

To discuss:
* Placement: ontop of the panel border or slightly inside it (like it is today)

Unrelated:
* Bug in new visualization tooltips where the resize handle shows through it 

In scenes we could make it even more noticeable because we have the edit mode, so we could if we wanted to make it use blue text (link) color (not in PR): 
Screenshot 2024-02-04 at 18 21 30

Or blue + dotted line:

Screenshot 2024-02-04 at 18 46 16
Screenshot 2024-02-04 at 18 46 23

### CODE REVIEW

**Comment by Ijin08** [comment]
I agree we should make it more prominent. With edit mode I think we actually push it a bit further and make it even more prominent. I don't think it would be a bad idea to always have it visible and make it blue on hover:
Screenshot 2024-02-05 at 09 29 23

**Comment by dprokop** [comment]
I like the last proposal from @Ijin08.

**Comment by torkelo** [comment]
@Ijin08 @dprokop something like this? (Only in scenes does it have this blue hover and always visible in edit mode on all panels)

https://github.com/grafana/grafana/assets/10999/9cdbc584-d967-451e-9066-13c84602220c

The look of the resize handle could also look a bit like this, which I think is one of the more common styles:

https://github.com/grafana/grafana/assets/10999/422c0a3e-b7b3-4fa6-bec5-1f025e961635

**Comment by dprokop** [comment]
I like both versions, but if were to choose I would pick the latter one.

**Comment by Ijin08** [comment]
I think both looks good and probably works as good. Lets try the second one.

**Review by ivanortegaalba — APPROVED** [review]

**Review by dprokop — APPROVED** [review]

**Comment by torkelo** [comment]
With the new custom styling I do not need to change anything in core https://github.com/grafana/scenes/pull/579

**Pull request closed without merging**
