### PR TITLE
Doc - fix broken link

### PR DESCRIPTION
**Pull request by pgiraud**
I updated the doc for repeating panels and rows (with my knowledge) so that it reflect current state.
Please review.

### CODE REVIEW

**Comment by pgiraud** [comment]
Actually, we should probably point to the #repeating-panels section.

And at the same time, the doc should be updated since there doesn't seem to be any "on row hover" menu anymore. Also there's no `row` repeat mode but a `direction` dropdown instead.

I'll provide an updated documentation.

**Comment by pgiraud** [comment]
This requires more work. I just discovered the "Row" in the "add panel" menu. I'll add more documentation tomorrow.

**Comment by pgiraud** [comment]
I updated the doc for repeating panels and rows (with my knowledge) so that it reflect current state.
Please review.

**Review by marefr — CHANGES_REQUESTED** [review]
Great! Have some comments/ideas of changes which would be good if you can have a look at.

**Comment by pgiraud** [comment]
> Great! Have some comments/ideas of changes which would be good if you can have a look at.

Taken into account.

**Review by marefr — APPROVED** [review]
Excellent :+1:

**Pull request merged**
