### PR TITLE
Improve "Allowed cookies" terminology

### PR DESCRIPTION
**Pull request by myrle-krantz**
Updating text to be more descriptive and inline with our values.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
looks good to me @myrle-krantz 🙌 

just needs the CLA signing 👍

**Comment by natellium** [comment]
Looks good! 🧜

**Review by natellium — APPROVED** [review]

**Comment by Elfo404** [comment]
This should fix https://github.com/grafana/grafana/issues/38888, but I think there's the need for quite a few documentation updates; "Whitelisted Cookies" can be found in a few places, IMHO we should either update the docs to reflect this change asap or revert this if we can't update the docs before 8.2.0:

- https://github.com/grafana/grafana/blob/e32e135c7310f185508af22c84078512156e64c8/docs/sources/datasources/influxdb/_index.md#L38
- https://github.com/grafana/grafana/blob/b78a67cec745b11b05ba2cf7ff12d848798b07a5/docs/sources/datasources/opentsdb.md#L22
- https://github.com/grafana/grafana/blob/bbaf6a23bbb0d2c423eb3304781c57029e2df9be/docs/sources/datasources/loki.md#L28

cc @achatterjee-grafana

**Comment by ashharrison90** [comment]
@Elfo404 good point - i've raised a follow up PR for the docs ☝️

**Comment by osg-grafana** [comment]
See https://github.com/grafana/grafana/blob/main/contribute/style-guides/documentation-style-guide.md#allowing-and-blocking. "Accepted" is to be "allowed" per style guide.

**Pull request merged**
