### PR TITLE
Explore: makes toolbar's "Live tailing" button responsive

### LINKED ISSUE #19350: Explore: Toolbar's "Live tailing" needs to be made responsive
This toolbar is getting busier and looks messy in split views:

Screenshot 2019-09-24 at 10 40 41

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Adds a fold of "Live tailing" button while in either normal and split view. Adds a tooltip for the live button and updates its text.

**Which issue(s) this PR fixes**:

Fixes #19350

### CODE REVIEW

**Review by kaydelaney — COMMENTED** [review]
LGTM, but should probably get the opinion of @davkal as well. Nice work!

**Comment by davkal** [comment]
Any reason why this breaks later than Run Query?

**Comment by Estrax** [comment]
> Any reason why this breaks later than Run Query?

No reason. Refactored it to ResponsiveButton then.

**Review by davkal — APPROVED** [review]
LGTM

**Pull request merged**
