### PR TITLE
Alerting: Fix dashboard nav drawers disappearing

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
This PR changes the way in which DashNav modals are rendered to fix disappearing modals when Toolbar buttons gets removed.
It happens on narrow screens when buttons in DashNav toolbar need to be collapsed and moved to the `Show more items` section.
If a button belonging to that section renders a modal the modal gets removed after any click due to removal of `Show more items` component

**Why do we need this feature?**
To prevent disappearing modals created by Toolbar buttons

**Special notes for your reviewer:**

**BEFORE**

https://github.com/grafana/grafana/assets/6293563/66f3cb09-cd11-41e0-9db5-386353b98b8b

**AFTER**

https://github.com/grafana/grafana/assets/6293563/1469a119-bbd7-4dc4-bcc4-5018d06ab299

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM! 🚢

**Review by gillesdemey — APPROVED** [review]
Changes LGTM, but best to check with @grafana/dashboards-squad too

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Pull request merged**
