### PR TITLE
Auto-generate sample.ini file from defaults.ini

### PR DESCRIPTION
**Pull request by santihernandezc**
This PR adds a script to update `conf/sample.ini` using `conf/defaults.ini` as input, making it easier to keep these files in sync. This script can be run from the root directory with `make sample.ini`.

### CODE REVIEW

**Comment by DanCech** [comment]
Neat idea, there's definitely a lot of drift there!

I do wonder about the items where sample.ini currently includes non-default values as examples, maybe we should add comments to defaults.ini to demonstrate usage for those cases where it might be non-obvious?

**Comment by santihernandezc** [comment]
@DanCech as far as I see `sample.ini` includes non-default values in sections that haven't been updated for a long time (check [this 9 year old PR](https://github.com/grafana/grafana/pull/1883/commits/4c6d7630cd398c95b85e6c2f8c9d30d881c10afb#diff-3f8a56cf48f018d19dd5378a288ed6b9180d60ef82649c98339f93b3523bd7ce) for `paths.data`), I don't think these inconsistencies are intentional.

I see two viable options here:
1. Copying the setting in `defaults.ini` including default values (this PR)
2. Copying the setting names, omitting the values

> Maybe we should add comments to defaults.ini to demonstrate usage for those cases where it might be non-obvious?

Good idea, every setting should ideally be documented, but I see that as an improvement over what we currently have. We can do that in a future PR.

**Review by aangelisc — APPROVED** [review]
This is a step in the right direction IMO. I'd suggest updating the developer documentation to make it clear that this exists (I wonder if we could have a workflow to actually enforce/suggest this change also).

**Comment by tolzhabayev** [comment]
are you sure you have accounted for the deviations that are intentional? it might break a lot of on prem installations https://github.com/grafana/grafana/pull/62316#issuecomment-1419167499

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Pull request closed without merging**
