### PR TITLE
IconButton: IconButtons are now correctly aligned in Safari

### LINKED ISSUE #48499: newNavigation: icons misaligned on Safari
image
Customer requested to enable newNavigation and it is working well in general. They did report that on Safari 15.4 (17613.1.17.1.13) there is an alignment issue with arrow icon for the menu. We have attached a screenshot. They also confirmed that it renders properly in Chrome so seems isolated to Safari.

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- our icons are `inline-block` at the moment. on safari this causes them to be misaligned as i think they're reserving space for the text content. by setting the `line-height` to 0 this makes the positioning consistent across the browsers
- for some reason our icons have a random `margin-bottom: 2px` which also causes some layout issues
  - can't centre icons properly when they're 2px higher than they should be

| before | after |
| --- | --- |
| image  | image |

**Which issue(s) this PR fixes**:

Fixes #48499 

**Special notes for your reviewer**:

i've done a quick sniff test but it's obviously very hard to check every place that has icons 😱

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]
I'm sure this has broken/caused other weird alignment issues, but lets merge in now and spot them

**Comment by jackw** [comment]
> I'm sure this has broken/caused other weird alignment issues, but lets merge in now and spot them

There's a good chance it's gonna break the layout in a few plugins too. The `<Icon />` component is used by [24 plugins](https://ops.grafana.net/d/dmb2o0xnz/imported-property-details?orgId=1&var-propertyName=Icon&var-packageName=@grafana/ui) that are published to gcom.

**Comment by jackw** [comment]
> i would say the chance of it completely breaking layout is pretty small.
Maybe that was a bit dramatic of me. I mean the alignment of elements as @joshhunt mentioned. 😄

**Comment by joshhunt** [comment]
I think the one comfort is that it hasn't really broken much in core Grafana, so I think the chances of it causing many problems in other plugins is reasonably low.

**Comment by ashharrison90** [comment]
i'm gonna merge this as i think it makes our use of icons much more consistent. if there's any places that have changed slightly, i'm happy to fix them as we spot them.

**Pull request merged**
