### PR TITLE
Fix issue #3341 New series option: hide/show in tooltip.

### PR DESCRIPTION
**Pull request by ilgizar**
To issue #3341
This patch will add series option "tooltip: show|hide" and hide tooltip according invisibility of series on legend.

### CODE REVIEW

**Comment by ilgizar** [comment]
How it works.

Create stack A: RX = RX_1 + RX_2 + RX.
tooltip01

Hide lines from diagram and from legend to series RX_1 and RX_2.
tooltip01 5

Hide tooltips of series according legend visibility: simple check "Hide invisible" on "Tooltip" section.
tooltip02

If need show tooltip of some series (ex, RX_2), but hide from legend: set series option "tooltip" to "show".
tooltip03

**Comment by bergquist** [comment]
Looks good. But I think "Hide invisible" needs a better name. I will think about it.

**Comment by ilgizar** [comment]
Sorry my English.

**Comment by nerk01** [comment]
Maybe default to not showing and flipping the logic?  Then the option name can be "Show hidden metrics".

**Comment by torkelo** [comment]
closing this PR as it's drifted a bit too far from master. There does not seem to be a great interest in the feature request, so not sure the added complexity of a new feature/option is warrented (but maybe)
https://github.com/grafana/grafana/pull/4410

**Pull request closed without merging**
