### PR TITLE
Loki: Allow queries to be made either forward or backward

### LINKED ISSUE #20394: Allow for Forward search in explore Loki
**What would you like to be added**:

I want an option to search forward within logs currently we can only do backward.

**Why is this needed**:

Backward is nice when you're looking at the last logs of an applications but forward is more useful when you're scanning past incidents. 

It would be also nice to be able to page from the last logs received so we can move within the same timeframe but show missing logs cut by the limit.

Loki API support both forward and backward search.

### PR DESCRIPTION
**Pull request by jdbaldry**
**What this PR does / why we need it**:
Allow Loki queries to be made either forward or backward.
 
This can be configured on a per query basis and on a per data source
basis where query configuration overrides data source configuration.
For backwards compatibility the default direction in the data source
configuration is 'BACKWARDS' which is the only direction previously
supported. The data source configuration becomes the default
configuration for new queries created in Explore or via a panel but
the user can change this with a toggle.

**Which issue(s) this PR fixes**:
Addresses the bulk of https://github.com/grafana/grafana/issues/20394 but does not touch add paging functionality.

Fixes #20394

**Special notes for your reviewer**:
I have essentially no experience with React or frontend development so hacked at syntax until this worked in manual testing. I thought I'd open up a PR early and I would really appreciate some advice on the following:
- What needs to be tested
- Whether the hierarchy of "data source default and specific query override" is a reasonable UX
- Correctness of some of the direction selection logic (`{ query.direction ?? datasource.direction ?? 'BACKWARD' }` for example)
- What can be done to clean this up (perhaps defining an direction type in `types.ts`?) 

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@jdbaldry Thank you for your contribution! I see that the drone build is failing on linting. You can run `yarn prettier:write` that should fix all the linting errors. 🙂

**Comment by davkal** [comment]
This is going to be tricky to get right: 

- Backward search vibed well with the lastest-to-oldest sorting order of the result display. In forward search, you'll get the latest of the limit window at the top, which is somewhere unpredictably in the middle of the time range starting the user off in an essentially random place. Perhaps flip the result search order in forward search?
- Logs navigation (the time chunks on the left) looks broken now: in forward search it shows the full range on one chunk 
- The top graph has a different behavior now: in backward search it shows the time range of the available data in the response (the row-limited time), in forward search it shows the full time range (time picker range)
- the meta information (that a limit was reached and how many lines were processed) are no longer correct in forward search, i suspect that logic makes a couple of assumptions how the result set relates to the time picker range. 
- the direction is not stored in the URL which makes sharing this view of the results impossible

**Review by davkal — CHANGES_REQUESTED** [review]
As is, this will be very confusing. I wonder if this can be resolved. Before progressing, I'd like to understand the use case a lot more.

**Comment by jdbaldry** [comment]
Sorry, have been busy over the last two weeks. Will review this again today.

**Comment by jdbaldry** [comment]
The use case I have that extends those noted in https://github.com/grafana/grafana/issues/20394 is that I had been playing with a `diff` logQL function that would behave similar to the Unix `uniq` tool or `diff` depending on how it was invoked. This function is not commutative and querying backwards is rarely the diff you want to see.

With regards to having this a data source configuration, I don't believe there are many situations where the data source provisioner would want to change the default but I saw that another query parameter (line limit) was configurable there so I followed suit.

> Backward search vibed well with the lastest-to-oldest sorting order of the result display. In forward search, you'll get the latest of the limit window at the top, which is somewhere unpredictably in the middle of the time range starting the user off in an essentially random place. Perhaps flip the result search order in forward search?

Absolutely.

> Logs navigation (the time chunks on the left) looks broken now: in forward search it shows the full range on one chunk.
> The top graph has a different behavior now: in backward search it shows the time range of the available data in the response (the row-limited time), in forward search it shows the full time range (time picker range)
the meta information (that a limit was reached and how many lines were processed) are no longer correct in forward search, i suspect that logic makes a couple of assumptions how the result set relates to the time picker range.
the direction is not stored in the URL which makes sharing this view of the results impossible

Thanks for the thorough investigation and noticing these. I had tunnel vision while implementing this, focusing just on the bit I wanted to work (diff works in the right direction).

I'll look into fixing each of those issues and report back afterwards.

**Comment by TewWe** [comment]
@jdbaldry may you had time to go ahead with @davkal's suggestions? If not may we provide some contribution to go ahead with this? Thanks!

**Comment by jdbaldry** [comment]
Hey @TewWe, sorry for the late reply, I had a long holiday period :)

This work came out of a hackathon project in a previous quarter and I'm probably too far removed from this project and Loki to get this over the line. If you are interested in picking this up, that would be brilliant!

**Comment by BaDo2001** [comment]
@jdbaldry I am going to try my best to get this merged in #43860

**Pull request closed without merging**
