### PR TITLE
[v9.3.x] Update doc-validator to latest release

### PR DESCRIPTION
**Pull request by grafanabot**
Backport f4be855e3055f231cf6a9f1a5040e6d78d802d3c from #62170

### CODE REVIEW

**Review by jdbaldry — APPROVED** [review]

**Comment by jdbaldry** [comment]
test-frontend CI failure appears to be unrelated (https://drone.grafana.net/grafana/grafana/101217/1/6) but is blocking merging this PR.

**Comment by jdbaldry** [comment]
@grafana/frontend-ops Are you the right team to review the failing `test-frontend` check in CI? It is blocking the merging of this backport.

**Comment by jdbaldry** [comment]
> @jdbaldry we moved to node 18 in 9.4.0: #62079
> 
> as part of that PR, this unit test had to be changed. looks like a bug was fixed in node which meant our expect was wrong. you can see the diff here: https://github.com/grafana/grafana/pull/62079/files#diff-25154eb0e0bd3b02bf9f042d61e520977cc84ff485f7d28fb047dd444044e8b4
> 
> our docker container is running node 18 now but the change never got backported to the 9.3.x branch, hence the failure. you can make the same change to the test and add it to the this PR to unblock yourself.
> 
> hope that makes sense!

Thanks for the explanation, you've saved me a lot of time digging around. I'll look to do the backport soon.

**Review by osg-grafana — APPROVED** [review]
Approving with doc nits, and expect an engineer to have a look too

**Comment by osg-grafana** [comment]
Meta: Stepping in for Eve, who is on PTO.

**Comment by jdbaldry** [comment]
This is a backport PR so any proposed changes would need to be made on `main` and backported.

**Comment by ashharrison90** [comment]
yeah i wanna pull in @dsotirakis as well and just ask a question... 😅 

dimitris, looks like a unit test fix for node 18 was pulled in to the 9.3.x branch but not the rest of the node 18 changes [here](https://github.com/grafana/grafana/pull/62079)... was this intentional? 🤔 i remember discussing this a while back but can't think why we'd do that. either we'd pull in all the changes or none of them. 

we could either:
- pull in the rest of the node 18 changes (as this PR now does)
- revert the test fix so that it works in node 16 (but presumably we needed this fix for a reason...? do we have a separate build system that's running node 18 or something? 🤔 )

**Comment by ashharrison90** [comment]
yeah i know of no reason why it shouldn't work on node 18. all the changes that were needed were in the original PR. 

i think i understand why the test fix was backported now... the drone image used in this branch has been bumped to a newer image (presumably for some other reason)... as part of that, it's now running node 18 in the CI. i think in that case it makes most sense to backport the node 18 changes as this PR does. thanks!

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Pull request merged**
