### PR TITLE
Update OpsGenie Notifier to support different api domains.

### PR DESCRIPTION
**Pull request by bkaganyildiz**
**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana.

Could you please elaborate a little about the use case for this PR? I thought opsgenie was a hosted service?

**Comment by bkaganyildiz** [comment]
Sure thing. Currently OpsGenie api hosted at https://api.opsgenie.com but we're relasing new api domain for EU https://api.eu.opsgenie.com. In order grafana users to use EU domain api they need to send callbacks to that domain. I've just added an another field for api url and update notifier a bit.

**Comment by bkaganyildiz** [comment]
As far as I can see there is a problem with test but I have not seen any stack trace, that's why I'm not sure how to solve it. If you are familiar with it any help would be greatly appreciated.

**Comment by bergquist** [comment]
The error is due to code formating. Please run `gofmt -w -s ./pkg` in the grafana folder to fix it. 

I think it would make more sense to have the default url as a placeholder in the input field.

**Comment by bkaganyildiz** [comment]
Thanks for review and I've updated accordingly. If you can merge it, would be much appreciated.

**Comment by bergquist** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
