### PR TITLE
Chore: Remove the old log format

### LINKED ISSUE #47299: Clean up : Remove feature toggle and the level mapping we did in syslog and alerting
We are currently mapping log levels from log15 to gokit-log, after we remove completely the log15, we need to remove all the mappings:
- syslog : https://github.com/grafana/grafana/pull/47209/files#diff-b2c588f054d28a7c67f03829c44164c6710634c0f7ba946376369e106fcb2ba0R215
- log.go : https://github.com/grafana/grafana/pull/47195/files#diff-b2c588f054d28a7c67f03829c44164c6710634c0f7ba946376369e106fcb2ba0R216
- alerting: 
- also alert in hosted grafana, we need to clean it up.
- feature toggles in hosted grafana to be remove
- remove the old time_ts in our context log

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #47299

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Nice. Just one comment. Is the `level.NewFilter` working exactly the same as we had earlier?

**Comment by ying-jeanne** [comment]
> Nice. Just one comment. Is the `level.NewFilter` working exactly the same as we had earlier?

Yes, the implementation is the same, at the time I just copied the level implementation of gokit/log, see here https://github.com/go-kit/log/blob/main/level/level.go#L38

**Comment by marefr** [comment]
Great. Just need to fix the conflicts and failing CI and then we should be able to approve this

**Review by yuri-tceretian — APPROVED** [review]
LGTM

**Review by sakjur — APPROVED** [review]
LGTM

**Pull request merged**
