### PR TITLE
Config: Change jwt config value to be "expect_claims"

### LINKED ISSUE #58231: [JWT Authentication] GF_AUTH_JWT_EXPECT_CLAIMS environment variable does not seem to work
This is similar to https://github.com/grafana/grafana/issues/57072.

**What happened**:
In JWT Authentication I tried to use the [expect_claims](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#validate-claims) option in Docker with `GF_AUTH_JWT_EXPECT_CLAIMS`. It does not seem to get parsed (does not appear in the logs) and it doesn't work: I'm passing a JWT with invalid claims and it gets accepted.

**What you expected to happen**:
1. There should be a log entry like `logger=settings t=2022-11-04T12:09:52.333644005Z level=info msg="Config overridden from Environment variable" var="GF_AUTH_JWT_EXPECT_CLAIMS=...`
2. A JWT with invalid claims should be rejected

**How to reproduce it (as minimally and precisely as possible)**:
Cannot provide steps easily, as it requires an otherwise valid (non-expired) JWT except the invalid claims. You can follow similar steps as described in https://github.com/grafana/grafana/issues/57072.

**Anything else we need to know?**:
When using `GF_AUTH_JWT_EXPECTED_CLAIMS` (with `expected` instead of `expect`) there is a log entry verifying that the env var was successfully overridden. Nevertheless, the option still doesn't seem to work since a token with invalid claims gets accepted.

Note the difference:
`expected_claims` here: https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L642
`expect_claims` in the docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#validate-claims

**Environment**:
- Grafana version: grafana/grafana-oss:9.2.3
- Data source type & version:
- OS Grafana is installed on: MacOS
- User OS & Browser: Brave Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)(https://brave.com/latest/)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by conorevans**
Signed-off-by: Conor Evans <coevans@tcd.ie>

**Which issue(s) does this PR fix?**:

Fixes #58231

```go
cfg.JWTAuthExpectClaims = valueAsString(authJWT, "expect_claims", "{}")
```

### CODE REVIEW

**Comment by eleijonmarck** [comment]
@conorevans thanks for your contribution to Grafana! On the surface this seems like the change that is needed.

Let me have a look at this and test this out locally on my machine 🙌

**Comment by eleijonmarck** [comment]
We could have opted to change the variable to `expected_claims` in the configuration settings, but since the official docs says `expect_claims` we should merge this change.

**Review by eleijonmarck — APPROVED** [review]
LGTM

**Comment by conorevans** [comment]
> We could have opted to change the variable to expected_claims in the configuration settings, but since the official docs says expect_claims we should merge this change.

Yeah I considered it, as `expected_claims` probably seems more natural (grammatically), but I thought this was less intrusive/breaking. If somebody had been using the configuration in a broken version, they wouldn't need to change in their configuration in the fixed version.

**Pull request merged**
