### PR TITLE
Create annotations

### PR DESCRIPTION
**Pull request by torkelo**

### CODE REVIEW

**Comment by torkelo** [comment]
This is starting to come together! 

Feedback
1) The region background (region_area_marker) is over the graph so you cannot zoom in or interact with the graph. Think the region needs to use the flot markings feature (used by thresholds). Not sure if it is possible to add markings from the flot events plugin however.  If that is tricky we can skip the region area, easy to add later. 
2) Regions are not shown if only one end (start or end) is in view.
3) Graphs without annotations still have the margin between the graph & x-axis.
4) When creating regions it should be visualized as a region (event_manager.event)

**Comment by alexanderzobnin** [comment]
@torkelo Ok, will work on that.

**Comment by alexanderzobnin** [comment]
@torkelo I've added a lot of changes. Now you can edit and delete events and regions. Can you review these changes when you have a time?

**Comment by bergquist** [comment]
I think we should try to get this into 5.0 

Lets solve the conflicts are review it.
thoughts @torkelo ?

**Comment by torkelo** [comment]
maybe, if we can  solve the outstanding UX issues.

**Comment by torkelo** [comment]
Added support for storing and filtering annotation events by tags. 

Right now annotation db & apis are also used for alert history. So I figured that we want to (in the future) support filtering by key value tags as well. So if an alert query returns datacenter and host tags we can store those in the alert annotation and filter alert history by "datacenter=us-east". But for manually entered tags when creating annotations having to specify key & value feels cumbersome so we made it possible to have tags without values (tag with empty value). 

The input api: 
```http
POST `/api/annotations`
{
	"dashboardId": 1,
	"panelId": 1,
	"time": 1,
	"title": "test server2",
	"text": "test",
	"tags": "error, outage, dc:us-east, server:server2"
}
```

Tags are specified in a csv string where each element can have key only or `key:value`. 

Tags are stored in tag table 

| Id     |      Key     |  Value |
| ------ | ------------- | ------
|  1 |  error |  |
|  2 |  outage |  |
|  3 |  dc | us-east |
|  4 |  server | server2 |

annotation - tag link table

| annotation_id    |      tag_id
| -------------------- | -------------
|  1 |  1 |  1  |
|  2 |  1 |  2 |
|  3 |  1 | 3 |
|  4 |  1 | 4 |


Query API: 

```http
POST `/api/annotations?from=1507110880467&limit=100&tags=server:server10&to=1507114641671&type=event`
```

Tags search filter is also csv and can include either key only tags or key value pairs. If you have multiple
tag filters all have to match (AND semantics. Could have an query param to change it to OR. 


thoughts @woodsaj @DanCech  ?

**Comment by DanCech** [comment]
Seems reasonable to me, we might want to look into supporting a graphite-compatible url for submitting events so that people can easily transition.

http://graphite.readthedocs.io/en/latest/events.html#adding-events

**Pull request merged**
