### PR TITLE
Alerting: Add landing page

### LINKED ISSUE #58576: Create an initial version of the landing page
As the first steps, we're going to use a layout similar to the one used by machine learning
The content will be as follows:

1. Header with 3 CTA buttons
	- Create a new rule
	- Configure notification policies
	- Configure the default contact point
2. How it works at a glance
Use the vertical flow diagram and add additional copy content
3. Getting started section
	- Link to docs
	- Link to Grafana University
4. Alerting introductory video

### PR DESCRIPTION
**Pull request by konrad147**
**What is this feature?**
A new landing page for Alerting

**Which issue(s) does this PR fix?**:
Fixes #58576

**The difference between old and new navigation**
For the old navigation, there is a new `Home` tab which is now the default one for Alerting
For the new navigation, there is no `Home` tab. The landing page is the default page for the `Alerting` section

**Special notes for your reviewer**:
**V1**
image

**V2**
image

**V3**
image

**V4**
Screenshot 2022-12-09 at 16 20 15

**V5**
image

**V6 Light & Dark**
image
image

**V7 with New Navigation**
image

### CODE REVIEW

**Comment by brendamuir** [comment]
Also--re first time users and existing users; any change of behaviour in display of the landing page? Can the system detect that and display different content? Is there a way an existing user can easily x out of this and get a list view of their existing alert rules, etc. for example..?

**Comment by brendamuir** [comment]
Text for the how it works at a glance:

**Review by gillesdemey — APPROVED** [review]
🚀 🚀 🚀

**Comment by alexmobo** [comment]
AWE-SOME

**Review by soniaAguilarPeiron — APPROVED** [review]
Great job!!! 🚀🙌

**Pull request merged**
