### PR TITLE
Table: Fix JSON tooltip closing when extended in a larger screen

### LINKED ISSUE #34553: Table: JSON Tooltip closes when extended
**What happened**: Same as #30727, which was closed by #34120. 

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**: The patch in #34120 works except when the tooltip is initially <70vh tall AND already nearly touching the bottom edge upon initial hovering on the cell- expanding a json element within extends it to the maximum set of 70vh, but this is out of window, so the tooltip auto-closes as before. 

Also, trying to view a json cell which initially doesn't have a scrollbar while the cell is roughly in the middle of the window instantly closes it still, though this is somewhat inconsistent and I can't figure out exactly why. Might be the tooltip box being near 70vh and trying to extend out-of-window downwards? The tooltips with a scrollbar by default don't experience this, from what I can tell

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2
- Data source type & version: Postgresql
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10 / Chrome 90.0.4430.212
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR fixes the JSON tooltip closing when extended in a larger screen.
**Which issue(s) this PR fixes**:

Fixes #34553

### CODE REVIEW

**Review by hugohaggmark — COMMENTED** [review]
Great work trying to solve this, but will min-height not make all tooltips 60vh? Not sure we want that.
image

**Comment by thisisobate** [comment]
Yeah...I just pushed a much effective solution: increasing open dropdowns to 5 instead of 4. That way, the user doesn't have to click to expand the dropdown thereby removing the flakiness by default.

**Comment by hugohaggmark** [comment]
> Yeah...I just pushed a much effective solution: increasing open dropdowns to 5 instead of 4. That way, the user doesn't have to click to expand the dropdown thereby removing the flakiness by default.

This solution is also not a long term solution if the user has a big JSON object. This might be caused by Popper (not sure), maybe we should spend some time investigate that more and report an issue if we can repro it.

**Comment by hugohaggmark** [comment]
@thisisobate any progress on this one or should we put it on hold?

**Comment by thisisobate** [comment]
I already propagated this issue to the React Popper community. Awaiting their feedback. So I feel it makes sense for us to place it on hold 👍 @hugohaggmark

**Comment by hugohaggmark** [comment]
Should we close this PR and write something in the issue then @thisisobate?

**Comment by thisisobate** [comment]
Sure thing!

**Pull request closed without merging**
