### PR TITLE
#6419 Add max and min values for sparkline

### PR DESCRIPTION
**Pull request by the-daria**
https://github.com/grafana/grafana/issues/6419

### CODE REVIEW

**Review by Ijin08 — CHANGES_REQUESTED** [review]
This is nice feature! Good job.

But there are a few issues. If the single stat = Min I get an error. Negative values when Min is 0 also doesn't look as expected. 
In the image there are four identical series except for the last value. The first three has a Max of 150 and min of 0. The last one doesn't have a Max.
image

**Comment by darly-s** [comment]
Thanks @Ijin08  for checking this feature! I have fixed issues and now it looks much better. But I want to notice that problem with "N/A" has already reported here https://github.com/grafana/grafana/issues/8139 and it has not caused by current task so I would propose to fix that as described in docs that posted in comment to reported issue.

**Review by Ijin08 — CHANGES_REQUESTED** [review]
Hi!

So i have reviewed again and realized a couple of things. It's a bit unclear what the Min and Max actually represent. Below I have two singelstats with same data. One shows current value and the other max value. Sparkline Max is set to 100 in both. The expectation is that setting a Min and Max creates an invisible y-axis. So in the image below the sparklines give the impression that the left panel has lower values than the right but they are the same. The problem is that the height of the sparkline is set by the Stat value which defeats the purpose of comparing them. Also if there are points in the sparkline that are more than max they should be cut of as in the graph panel. 

image

Lastly the issue with sparkline Min having the same value as singelstat resulting in N/A. I don't understand the connection in the link you gave. 

I hope what I have written makes sense.

**Comment by darly-s** [comment]
@Ijin08, Thank you for review, changes has been done. New error handler has been added.

**Comment by rnovikovP** [comment]
Hi, is there any news on this feature?

**Comment by torkelo** [comment]
Reviewing this PR is a bit tricky as it also included a refactoring of var -> let (please to this in seperate PR as it makes reviewing actual changes easier). Aslo see some mistakes in this rename (scopedVars > 
 scopedlets)! 

I am not sure I agree with adding min and max options here. The singlestat sparkline feature is not designed to provide axis options but just provide a simple trend. 

If you want to have rich graphing options & singlestat big numbers, maybe this new Graph Big Legend mode would serve that purpose better? https://github.com/grafana/grafana/issues/11684 

But maybe your right, sparkline could need a min/max. But think the current code & options is too messy and needs to be simplified. Why is min/max options disabled when spark line is set to full height? I would like to remove the full height option, maybe find a good middleground between sparkline at the bottom and full height.

**Comment by darly-s** [comment]
Thank you for review. I fixed problems with refactoring code. 
  Using min and max options make possible to visualize proportions for different sparklines if they are placed on the same page. It is useful for case of comparing  different sparklines that has the same y axis in situation when we don't need more complicated graph as described above [#11684](https://github.com/grafana/grafana/issues/11684)

**Comment by torkelo** [comment]
I think https://github.com/grafana/grafana/pull/12010#issuecomment-391794505 will improve the auto scale behavior. 

And the broader use case I think will be better solved using https://github.com/grafana/grafana/issues/10358 (New multi stat panel) that will address visualizing many singlestats with common setttings.

**Comment by jamessewell** [comment]
@torkelo Could this be changed to automatically scale in this way if and only if the data type is a percentage?

**Pull request closed without merging**
