### PR TITLE
Dev alert img timeout

### PR DESCRIPTION
**Pull request by kylebrandt**
From https://github.com/grafana/grafana/pull/17688 in order to attempt to create tests.

Tests were started in https://github.com/iguanesolutions/grafana/commit/b697ab8127bd7d41c2d1234be31a3d6553abd564

### CODE REVIEW

**Comment by kylebrandt** [comment]
To Figure out / to do:

- Does the bus name argument serve a purpose?
- Not sure about the errors, somehow I guess I need to hook up a logger and check the log output since errors are not returned?
- Maybe with the Bus mocking, I should be using pointers and modifying the state, or maybe that is already happening?
- Not sure what the "pending" state is about
- Type "ImageTimeout" is repeated and should be a constant. 
- Need to understand underlying SQL model for this stuff
- Revisit whatever purpose I had in the tests here before I got lost trying to just get stuff not to panic due to reflection everywhere
- Maybe the UIDs in a couple places matter
- Probably other stuff...

**Comment by kylebrandt** [comment]
Note to self: Maybe these tests are more appropriate in the `notifiers` pkg

**Comment by kylebrandt** [comment]
I'm thinking maybe the `ShouldNotify` logic maybe shouldn't be in the notifiers package but the alerting package?

**Review by torkelo — COMMENTED** [review]
Pending is the provisional alerting state (during the For time), to get rid of flapping we have the For option to say how long an alert rule need to be firing for the alert rule to send notifications

**Comment by torkelo** [comment]
> Does the bus name argument serve a purpose?

name argument? No the name of the first param of the function handler

**Comment by kylebrandt** [comment]
Putting this on hold for a while. Need to add comments and maybe some renaming to grok the alert code. The people that can verify that those changes would be correct are all out for a few weeks.

**Comment by marefr** [comment]
We decided to put this on hold until people are back from vacations.

**Comment by torkelo** [comment]
What is the status of this PR? In new of discussion & review?

**Comment by marefr** [comment]
Thanks for reminding me. We need to pick this up soon

**Comment by skuxy** [comment]
Hey guys, do you have any update on this? Do you need some help?

**Comment by hekmon** [comment]
Just avoiding, the staling state...

**Comment by marefr** [comment]
Still looking into it

**Comment by marefr** [comment]
This have been replaced/obsoleted by #21536 so closing.

**Pull request closed without merging**
