### PR TITLE
dont quote numbers for influxdb, closes #4163

### LINKED ISSUE #4163: InfluxDB "WHERE value < number" forces string
Hey there,
the query editor for InfluxDB will always convert "WHERE value < 500" to:
`WHERE "value" < '500'`
even though it should be the following in order to be evaluated as a number:
`WHERE "value" < 500`

In other words, only the second expression will produce a graph.
Bug or Feature? ;)

tested with InfluxDB 0.10 and Grafana 2.6.0

### PR DESCRIPTION
**Pull request by nlf**
I'm pretty sure I got the spots where the quoting was happening. Let me know if there's more

### CODE REVIEW

**Comment by nlf** [comment]
and for the record, i did sign the CLA so I'm not sure why it's saying i didn't.. it was within two minutes of submitting this pull request though, so maybe there's a delay?

**Comment by torkelo** [comment]
How do you know it's a number value column in influxdb? Could be a tag value with a number as a string value, won't this break such scenarios ?

**Comment by nlf** [comment]
that's a fair point.. my hunch here is to err on the side of *not* quoting, however, since a user can add quotes themselves but they can't take them away.

unless of course there's something that determines what data types columns are that i could inspect here instead?

**Comment by bbinet** [comment]
This patch has caused a regression as influxdb tags must be of type string.

With this patch, if we have tag values which look like numbers ("001", "0x3", ...) the tag values won't be quoted, and the influxdb query will silently fail.

I think the correct way to fix this issue should be:
  1. if tag value => always quote value
  2. if field value => inspect field type and quote if string

Until issue influxdata/influxdb#3451 is implemented, we could try to guess value type as in @nlf patch when the where clause is using a field, but for tags, the value should always be quoted.

**Comment by bbinet** [comment]
Should I create a new issue for this, or can this issue be reopened?

**Comment by bbinet** [comment]
FYI, influxdb issue influxdata/influxdb#3451 has been implemented with PR influxdata/influxdb#6592 which has just been merged.
So we should now be able to check if the field type is a string to add quotes.

**Pull request merged**
