### PR TITLE
Added a link for more information

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Added a link to TimescaleDB so that users can get additional information if need be.

**What this PR does / why we need it**:
Provides a link for additional information about TimescaleDB option.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by brendamuir — APPROVED** [review]

**Review by GrafanaWriter — APPROVED** [review]
Thank you

**Comment by Rajakavitha1** [comment]
@jdbaldry please let me know if any changes need to be made to this PR.

**Comment by GrafanaWriter** [comment]
@jdbaldry is currently out of office. Do you need more to merge this update?

**Comment by Rajakavitha1** [comment]
> @jdbaldry is currently out of office. Do you need more to merge this update?

@GrafanaWriter It would be great if you could merge this update. I don't seem to to have the authorization to merge this update as an external contributor.

**Comment by Rajakavitha1** [comment]
Hi!!! @gguillotte-grafana  I did fix the table formatting for CI check. However, the check does not seem to pass. Can you please help in taking this PR to the merge?

**Comment by Rajakavitha1** [comment]
Hi @GrafanaWriter !!!! I did fix the table formatting for CI check. However, the check does not seem to pass. Can you please help in taking this PR to the merge?

**Comment by gguillotte-grafana** [comment]
CI is failing with:

```
+ ./scripts/ci-reference-docs-lint.sh ci

/bin/sh: 39: ./scripts/ci-reference-docs-lint.sh: not found
```

The `main` branch updated to remove this script since your branch was created. The `main` branch needs to be merged into your branch.

**Comment by gguillotte-grafana** [comment]
CI has let us down here - I've updated the branch and filed #56134 so we can get this in. I'm sorry this has been such a rough experience.

**Pull request closed without merging**
