### PR TITLE
Alerting: Keep legacy alert rule maxDataPoints and intervalMs during migration

### LINKED ISSUE #71988: Alerting: Legacy migration does not retain maxDataPoints or intervalMs
Currently, the legacy migration does not retain `maxDataPoints` or `intervalMs`.

This means that legacy alert rules which by default run with `maxDataPoints`=`1500` and `intervalMs`=(some value determined by time range and `1500`, approximately `time range / 1500`) will, after migration, run with `maxDataPoints`=`43200` and `intervalMs`=`1000`. This has two main drawbacks:

1. The UA query is different than the legacy query and might cause nuanced differences in results.
2. The old query with the new limits can cause errors if requesting too much data from the datasource. For example, a legacy prometheus query running over the last `4h` once migrated would result in `exceeded maximum resolution of 11,000 points per timeseries`.

### PR DESCRIPTION
**Pull request by JacobsonMT**
**What is this feature?**

This feature retains legacy values for `maxDataPoints` and min interval (`intervalMs`) during legacy -> UA migration.

**Why do we need this feature?**

Currently, the legacy migration does not retain these two fields. This means that legacy alert rules which were running with `maxDataPoints`=`1500` and `intervalMs`=(some value determined by time range and `1500`, approximately `time range / 1500`) will, after migration, run with `maxDataPoints`=`43200` and `intervalMs`=`1000`. This has two main drawbacks:

1. The UA query is different than the legacy query and might cause nuanced differences in results.
2. The old query with the new limits can cause errors if requesting too much data from the datasource. For example, a legacy prometheus query running over the last `4h` once migrated would result in `exceeded maximum resolution of 11,000 points per timeseries`.

**Who is this feature for?**

Users migrating from legacy to UA.

**Which issue(s) does this PR fix?**:

Fixes #71988

**Special notes for your reviewer:**

~Should not be merged without https://github.com/grafana/grafana/pull/71986 as users would not be able see or edit the migrated `intervalMs`~ Merged.

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
I'm just testing this but I think I'm doing something wrong, here is the screenshot from legacy alerting: 

Screenshot 2023-07-24 at 5 54 23 pm

and here is the screenshot from the alert rule after migration to Grafana alerting:

Screenshot 2023-07-24 at 5 54 45 pm

**Comment by JacobsonMT** [comment]
> I'm just testing this but I think I'm doing something wrong, here is the screenshot from legacy alerting:
> 
> Screenshot 2023-07-24 at 5 54 23 pm
> and here is the screenshot from the alert rule after migration to Grafana alerting:
> 
> Screenshot 2023-07-24 at 5 54 45 pm

Legacy alerting runs with max data points = `1500` regardless of the value in the panel.

**Review by grobinson-grafana — APPROVED** [review]
Tested this and can see that 1500 and `min_interval` are migrated to the new rule.

image

**Review by yuri-tceretian — APPROVED** [review]
LGTM

**Pull request merged**
