### PR TITLE
PublicDashboards: Warnings when creating a public dashboard are not properly aligned

### PR DESCRIPTION
**Pull request by aditipatelpro**
**What is this feature?**

This PR resolves the alignment issue of the warning box when creating a public dashboard.

**Why do we need this feature?**
This PR resolves a bug in UI.

**Before Resolution**
image

**After Resolution**
image

**Who is this feature for?**
End user

**Which issue(s) does this PR fix?**:
#72260

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by aditipatelpro** [comment]
Hi @natellium, I have completed working on issue  #72260, could you please review it?

**Review by juanicabanas — CHANGES_REQUESTED** [review]
Hi @aditipatelpro . Thanks for your contribution! ☺️

This change should not be done in this way. 
If you take a look, this component is not only used in the CreatePublicDashboard component, but also in the ConfigPublicDashboard component, which uses a display flex property for its children and gap 4. If you set this margin bottom, this last component will not be shown as it should, when the Alert component renders.

Therefore, the proper way would be:
- add a container style in CreatePublicDashboard div with: 

```
display: flex;
flex-direction: column;
gap: 4
```

- Wrap the title and the description in a single `div` (so gap 4 doesn't affect them)
- Change Description margin bottom style to be just 0, instead of 3 for its container and 1 for the `p`

Let me know if you want to make those changes

**Comment by aditipatelpro** [comment]
Hi @juanicabanas,  I am new to the project and have recently started contributing. Thanks for your feedback it is helpful, I will work on those and make changes in the code accordingly.

**Comment by aditipatelpro** [comment]
Hi @juanicabanas, I have completed working on the feedback you provided. 
I have also refactored a few things(deleted the **Description** component, since it was only used by **CreatePublicDashboard**) for simplicity's sake, let me know if you think otherwise.

**Review by juanicabanas — APPROVED** [review]
Excellent work! 
- Yes, the Description component used to have more things but after some refactors, it ended up being just a single paragraph. So, it's perfect to remove the component and put the paragraph in its parent

Well done, approved! 🚀

**Pull request merged**
