### PR TITLE
Select: fixed broken layout in safari when select have description

### LINKED ISSUE #24513: Broken layout for [Panel Edit → Display → Value] options in drop-down
**What happened**:The display of options for `Value` (`Panel Edit` → `Display`) select is broken

**What you expected to happen**: Display of Names + descriptions

**How to reproduce it (as minimally and precisely as possible)**: Edit panel and select Value selectbox

**Anything else we need to know?**:

When opening the select for the first time:

Zrzut ekranu 2020-05-11 13 09 49

After typing something, that results in short list, the layout is OK:

Zrzut ekranu 2020-05-11 13 24 32

Broken for longer lists:

Zrzut ekranu 2020-05-11 13 26 04

Seems like when the list overflows the drop-down window, the layout breaks:

Zrzut ekranu 2020-05-11 13 26 22

**Environment**:
- Grafana version: Version: 7.1.0-pre, Linux Version: 7.1.0, Package Iteration: 1589191595pr
- Data source type & version: DevEnv
- OS Grafana is installed on: MacOS 10.15.4 (19E287)
- User OS & Browser: Safari 13.1 (15609.1.20.111.8)
- Grafana plugins:
- Others: runnig on localhost (go+yarn)

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
When the select options have a description the line got the wrong height in Safari. Forcing the min line height to be 55px when a description is rendered for a select option.

**Which issue(s) this PR fixes**:
Fixes #24513

### CODE REVIEW

**Comment by dprokop** [comment]
Good stuff. Found one issue with options that do not have description: 

image

**Comment by mckn** [comment]
> Good stuff. Found one issue with options that do not have description:
> 
> image

Yes, how is that in the current implementation? Do we want it to still keep the same size or be smaller? I am happy to fix either way :)

**Comment by dprokop** [comment]
In the current implementation is padding: 8px + line height which adds up to 36px. Think this should be basically the min height of any of the select elements :)

**Comment by mckn** [comment]
> In the current implementation is padding: 8px + line height which adds up to 36px. Think this should be basically the min height of any of the select elements :)

How did you find the drop down that had a mix of values with and without description?

**Comment by dprokop** [comment]
@mckn go to Stat panel and try creating override. When you select property to override it shows up :)

**Comment by mckn** [comment]
> @mckn go to Stat panel and try creating override. When you select property to override it shows up :)

ah, thanks! 🙌

**Comment by mckn** [comment]
@dprokop should be fixed now.

**Comment by Clarity-89** [comment]
@mckn I've fixed the same issue by adding `flex-shrink: 0` to the options: https://github.com/grafana/grafana/pull/24567/files#diff-8d7015a62520f7fb39f7008c194a0e4bR25. Seems to be working well with multiline options as well. Another way would be to switch the display from flex to block on the option. Have you tried any of those? Wonder which way is best.

**Comment by mckn** [comment]
> @mckn I've fixed the same issue by adding `flex-shrink: 0` to the options: https://github.com/grafana/grafana/pull/24567/files#diff-8d7015a62520f7fb39f7008c194a0e4bR25. Seems to be working well with multiline options as well. Another way would be to switch the display from flex to block on the option. Have you tried any of those? Wonder which way is best.

Nice! I looked into changing it to `display: block` but didn't know about the `flex-shrink: 0`. If that one makes it work I would say lets go for that one. Feels like a elegant solution! Great work!

**Comment by mckn** [comment]
@Clarity-89 I will close this one i favor of your referenced PR. Ok?

**Comment by Clarity-89** [comment]
> @Clarity-89 I will close this one i favor of your referenced PR. Ok?

Sounds like a plan! :)

**Pull request closed without merging**
