### PR TITLE
Cloudwatch: Add AWS/Events Metrics

### PR DESCRIPTION
**Pull request by LeonardoBoleli**
**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by iwysiu — APPROVED** [review]
Hi @LeonardoBoleli ! Thanks for the pr, I'll finish up the CI and get it through.

**Comment by LeonardoBoleli** [comment]
Thanks Isabella, if you need other changes let me know to help the
community!!

Just for curiosity's sake, do you have an estimated date for the new
grafana version with my changes?

Em seg., 20 de mai. de 2024 às 12:47, Isabella Siu ***@***.***>
escreveu:

**Comment by iwysiu** [comment]
@LeonardoBoleli , I checked and it looks like we currently expect the 11.1.0 version (which this will be in) to be released on June 25th.

**Comment by LeonardoBoleli** [comment]
Hi Isa,

Is there any date to resolve this issue?
When provisioned, panels with mixed datasources only work for the first
introduced datasource · Issue #84121 · grafana/grafana (github.com)
<https://github.com/grafana/grafana/issues/84121>

I need a lot for this to resolve because there are so many graphs to do in
this area.
May you advise devs to take some priority in this problem?



Em ter., 21 de mai. de 2024 às 14:42, Isabella Siu ***@***.***>
escreveu:

**Comment by iwysiu** [comment]
Hi @LeonardoBoleli ! I would recommend replying to those issues to ping the teams in question about them.

**Pull request merged**
