### PR TITLE
DashboardScene: View panel scene 

### PR DESCRIPTION
**Pull request by torkelo**
* Fixes bug view panel where it would not get notified of a dependent variable being completed. The cause was that the panel parent row is not active when viewing a panel and variable dependency notifications are only propagated to active objects. 
* To fix that I need to create a separate scene with a clone of the panel to view. And for panels inside repeated rows I need to copy the row variable.

### CODE REVIEW

**Review by axelavargas — COMMENTED** [review]
👋🏾  I think I understand the changes. The old behavior was reusing the same viz scene object for the view mode, and in the new approach, we create a clone of the viz scene object, this clone gets activated and is added to the scene object tree (the debugger shows the `ViewPanelScene`). 

I tested and it solves the problem of variables not being updated if the viewed panel is inside a row, however, this part is a bit confusing for me:

> The cause was that the panel parent row is not active when viewing a panel and *variable dependency notifications are only propagated to active objects*. 

Do you know which file I can check to have more clarity?

**Comment by torkelo** [comment]
@axelavargas sure thing, the relevant logic is in SceneVariableSet , it stop change notification propagations when it encounters scene objects that are not active:
https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/sets/SceneVariableSet.ts#L315

**Review by dprokop — APPROVED** [review]
Great finding about the root cause for this but. Not much to comment code-wise, think it's clever to have a separate view scene, potentially we can expand it in the future to the idea you had about the scene showing not only the panel but also some additional breakdowns (if applicable).

**Review by axelavargas — APPROVED** [review]
Thanks for the explanation, Torkel 🏅. I get it now :)

**Review by ivanortegaalba — APPROVED** [review]
I was thinking about: would be possible if we just subscribe to the original panel state, and we add state on top of it? So we create an scene object subscribed to the panel object that adds the variables state and some other on top... could we do that instead of copying the object. If we copy the object, we miss the opportunity to receive any state update from the original object

Sorry if it is an stupid question, just trying to understand if that is a possibility and what possible downside it would have

**Comment by torkelo** [comment]
> I was thinking about: would be possible if we just subscribe to the original panel state

@ivanortegaalba no that would not work, when you view a single panel the original panel (that could be nested inside a row and grid item) is not active (rendered), nor are the row and grid item. So this new scene solves the problem of rendering a single panel, but to do that we need to copy the variable scope that can exist on the row level.

**Pull request merged**
