### PR TITLE
Chore: adds report.xxxx.json to gitignore

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
So that no other dev has their complete environment pushed up to Github I added report.xxxxxxxxxxx.json file to .gitignore.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by sakjur — APPROVED** [review]
:+1: Seems reasonable 🙂

**Comment by sakjur** [comment]
(is it always dumped in the root or can this happen anywhere in the file hierarchy?)

**Comment by hugohaggmark** [comment]
> (is it always dumped in the root or can this happen anywhere in the file hierarchy?)

I only got it in the root, so I'm not 100% sure.

**Review by peterholmberg — APPROVED** [review]
Yass!

**Pull request merged**
