### PR TITLE
Explore: Fix graph not updating when changing config

### LINKED ISSUE #60871: Profiling: Y-axis is showing the wrong units for CPU
**What happened**:
 Y-axis is showing the wrong units for CPU
I think this happens when I switch from one kind of profile to another.

**What you expected to happen**:
The Y-axis to change when selecting a new type of profile

**How to reproduce it (as minimally and precisely as possible)**:

Select memory profile then switch to CPU.

**Anything else we need to know?**:

image

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

cc @aocenas @joey-grafana

### PR DESCRIPTION
**Pull request by Elfo404**
**What is this feature?**

Fixes Explore Graph not correctly incrementing structureRev when config from within the dataframe itself was changing.
This replaces the custom explore logic which was incomplete with the same one used in dashboard.

**Which issue(s) does this PR fix?**:

Fixes #60871

**Special notes for your reviewer**:

While this should be safe, when testing please make sure uPlot does not unnecessarily re initialize the graph. it should happen only if:
- number of frames changes
- structure of frames changes
- config changes

(you can check if uplot is being reinitialized if the `canvas` containing the graph gets recreated in the DOM)

### CODE REVIEW

**Review by ifrost — CHANGES_REQUESTED** [review]
With this change the total number of series is incorrect (it uses `{dataWithConfig.length}`):

Screenshot 2023-01-30 at 13 58 50

Also, it's quite complex piece of code we're getting regression on not the first time. Would it be possible to add some tests so it's easier to change it in future? (could be a separate task)

**Comment by Elfo404** [comment]
@ifrost good catch! fixed it in [d8fd28e](https://github.com/grafana/grafana/pull/62473/commits/d8fd28e9857bed8ccc7df4f51408d35fc63844c8), also moved the structureRev logic in a separate hook so that that logic can be tested autonomously and added tests for conditions we (afaik) are interested in

**Review by ifrost — COMMENTED** [review]
Great work on extracting the logic and testing in a separate file 👍 

There's something weird that I see happening in this branch but not in `main`, though. When a legend is selected and I change labels or aliases the graph is not re-rendered correctly:

https://user-images.githubusercontent.com/745532/216025416-073319cd-be81-416c-ab74-74126d06de7f.mov

**Comment by Elfo404** [comment]
@ifrost thanks for spotting this. it is a quite interesting one!
actually the "bug" is on main. the previous method of comparison and logic to decide if to reinitialize the graph or not only took the number of series into account. The actual reason is a bit more complex and involves mutability.

the tldr is we have a few different bug in main because of the logic behind the reinitialization, for instance: look at this 

https://user-images.githubusercontent.com/1170767/216060286-27efb455-d2ca-42c0-ac6b-e3ce22dcebff.mov

while i agree the the UX deriving from this changes with the use case you recorded is not perfect, i still think this is the correct behaviour. clicking on an item in the legend should mean i want to specifically see onlyTHAT specific series. if the series changes (and i mean the actual series changes, not only its values, like for instance when it has a new set of labels), we shouldn't just assume the new one IS the old one just because their positional order is the same.

one last note: although i assume what you experienced may be quite an uncommon edge case, we may want to do something when the graph has all series hidden; i am thinking something on the line of
Screenshot 2023-02-01 at 13 53 31

or even automatically unhide all of them of after a run all the resulting series are hidden. but we should probably discuss this specific problem in a different issue. wdyt?

**Review by ifrost — APPROVED** [review]

**Pull request merged**
