### PR TITLE
Loki: When parser added, filter label as parsed labels

### LINKED ISSUE #30856: Loki: Filtering doesn't work correctly for parsed labels
**What happened**:

When using Explore to view Loki Logs in JSON format, after using `| json` parser expression, it is possible to filter for parsed label values. However, the query is modified to use a stream selector, which does not work since it's a parsed label and not a loki label.

**What you expected to happen**:

Filters on parsed labels have to be added as Label Filter Expression, for this grafana explore has to know/remember which labels have been parsed.

**How to reproduce it (as minimally and precisely as possible)**:

- Setup loki to contain any JSON logs with properties
- Query any stream, my example: 
```
{Service="frontendservice"}
```
Example log message (prettified):
```json
    {
        "@t": "2021-02-03T09:32:58.2573405Z",
        "@m": "Request \"WeatherBackend\" from http://localhost:5001/",
        "@i": "e0f0659c",
        "@l": "Debug",
        "Path": "WeatherBackend",
        "ServiceAddress": "http://localhost:5001/",
        "SourceContext": "FrontendService.Controllers.WeatherFrontendController",
        "Controller": "WeatherFrontendController",
        "ActionId": "4edb6d32-0927-4bfd-b45b-fd8eebbf2f87",
        "ActionName": "FrontendService.Controllers.WeatherFrontendController.GetWeatherForecast (FrontendService)",
        "RequestId": "0HM683KDIUR1O:00000001",
        "RequestPath": "/weatherfrontend",
        "SpanId": "b5f6d53dc54a5d4c",
        "TraceId": "378b8f033df64b4a8b0d0d4c4492ae9f",
        "ParentId": "0000000000000000",
        "ConnectionId": "0HM683KDIUR1O",
        "Scope": [
            "WeatherFrontendController"
        ]
    }
```
Screenshot (notice the four actual `Log Labels`):
grafik

- Parse log as JSON, Query: 
```
{Service="frontendservice"} | json
```

grafik

- "Filter for value" for any of the parsed labels, e.g. `TraceId`, generated explore query: 
```
{Service="frontendservice",TraceId="378b8f033df64b4a8b0d0d4c4492ae9f"} | json
```
grafik

Which obviously does not return any logs since `TraceId` is no label in loki.
Correct result would have been: 
```
{Service="frontendservice"} | json | TraceId="378b8f033df64b4a8b0d0d4c4492ae9f"
```

**Anything else we need to know?**:

Sorry if this is a dupe, didn't know what keywords to search for really.

**Environment**:
- Grafana version: `Grafana v7.3.5 (11f305f88a)`
- Data source type & version: `Loki 2.1.0`
- OS Grafana is installed on: Docker image in WSL2 on Windows 10 `20H2`
- User OS & Browser: Windows 10 `20H2`, Firefox `85.0`
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
When using Explore/Dashboard to view Loki Logs, after using parser expression (`| json`, `| logfmt`, ...) we get labels which are actual labels and labels which are parsed. At this moment, there is no way for us to know which labels are actual and which are parsed. This is a problem when it comes to filtering for/out labels trough logs detail view. When user filters labels which are parsed, the query is modified to use a stream selector (actual labels), which does not work since it's a parsed label and not a loki label. 

This might be in the future fixed by Loki and there will be a way for us to check which labels are which. There is an issue grafana/loki#3057 and also design doc https://docs.google.com/document/d/1DP_piybk4WBs_NWwWuMS4FRQSUK0eeAUY3pT0td7ueQ for this.

However, as this is a big problem, we (read @cyriltovena ) came up with great workaround. If parser is used, we can filter any label (normal or extracted) trough this syntax `{app="foo"} | json | key="any label"`. If parser is not used, then we know all labels are normal and we can use label filtering. The filtering is added at the end of query

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/30856

**Special notes for your reviewer**:
To test, use Loki datasource and try to use 2 types of query:
1. Query without parser e.g.: `{job="grafana"}
- Run query
- Open details view
- Try filtering for label - the new query should be `{job="grafana", newLabel="newValue"}`
- Try filtering out label - the new query should be `{job="grafana", newLabel!="newValue"}`

2. Query without parser e.g.: `{job="grafana"} | logfmt`
- Run query
- Open details view
- Try filtering for label - the new query should be `{job="grafana"} | logfmt | newLabel="newValue`
- Try filtering out label - the new query should be `{job="grafana"} | logfmt | newLabel!="newValue`

### CODE REVIEW

**Review by ifrost — APPROVED** [review]
👍 Nice one! Could you also add some tests?

**Comment by ivanahuckova** [comment]
@ifrost I have added tests in this commit https://github.com/grafana/grafana/pull/35610/commits/c918da56e47b6ec6c727b08439be11b4d5d3cf36. Do you want to review or is it okay to merge as only tests were added.

**Comment by ifrost** [comment]
> @ifrost I have added tests in this commit [c918da5](https://github.com/grafana/grafana/commit/c918da56e47b6ec6c727b08439be11b4d5d3cf36). Do you want to review it again?

It's splendid. You can meeeeeeerge it!

**Comment by ivanahuckova** [comment]
🕺 🕺 🕺

**Comment by ivanahuckova** [comment]
@SSvilen could you please create feature request for this. It should definitely be in our backlog. 🙂

**Comment by cromeroprofile** [comment]
I am trying to add filter of value clicking on + button in log labels but my query does not change and still return the same result. Here you are an screenshot:


loki-filter-error

**Pull request merged**
