### PR TITLE
Cloudwatch: Add AWS DocDB metrics

### LINKED ISSUE #16535: Add AWS DocumentDB support
**What would you like to be added**:
Support for the namespace AWS/DocDB
https://docs.aws.amazon.com/documentdb/latest/developerguide/cloud-watch.html

**Why is this needed**:
In order to support monitoring of AWS DocumentDB

### PR DESCRIPTION
**Pull request by utkarshcmu**
**Adds the AWS DocDB metrics in CloudWatch Datasource Plugin**:

**Fixes #16535**:

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Will this PR make to 6.3.0? Thanks!

**Comment by bergquist** [comment]
OFC! I guess we just missed it :)

Thanks!

**Review by bergquist — APPROVED** [review]
LGTM

**Comment by utkarshcmu** [comment]
THank you so much @bergquist

**Pull request merged**
