### PR TITLE
[WIP] Dashboard Panels Settings

### PR DESCRIPTION
**Pull request by ryantxu**
Managing large dashboards is kind of a pain... in 4x the `rows` editor gave you a high level view.  This adds a page to the dashboard settings that lets you configure multiple panels in one view.  Currently this lets you:

1. edit panel title
1. edit panel description
1. edit alert name/interval (if exist)
1. edit panel datasources / see which sources are used
1. raw edit gridPos: x/y/w/h
 
I don't know if there is any interest in this generally... but i'll post here just in case.

If you do want to merge... a few things I think need some work are:
- [x] Panel icon aligns weird: "gicon gicon-link" vs "icon-gf icon-gf-panel"
- [x] css rather than style='...' for table style
- [x] Hide `Repeat` panels?  Configure repeat properties?
- [x] update layout after changes to gridPos?
- [x] Audit how this is linking to panels and datasources.
- [ ] Convert to react

Here are some screenshots:
image
image
image
image

(Note, this is a copy of #10304... but my git foo isn't good enough to get the branch back in sync :( )

### CODE REVIEW

**Comment by ryantxu** [comment]
@daniellee -- I think this is worth looking at now.  Any feedback would be great.  Thanks

**Comment by torkelo** [comment]
This looks really useful in some cases. But not sure it is common enough a use case (at least the batch update grid pos).   There are some issues with this. 

1) Would like to explore other ways to layout this UI. Perhaps not in a table but in a list and give each panel the space they need for these options. Having these toggles that changes what options you can set feels unconventional (but space efficient). 

2) Sadly this quite a bit of new angular code & markup. We are trying to limit all new angular code and write all new stuff in React. 

We are using a component that make it possible to use react components from angular.  See here:
https://github.com/grafana/grafana/blob/master/public/app/core/angular_wrappers.ts

**Comment by ryantxu** [comment]
> This looks really useful in some cases.

I have been using this for a while, and it is *really* helpful for auditing consistent naming style in the: titles / descriptions / etc.  In particular the naming conventions and configurations on alarms since you can not seen them in the dashboard.

Despite all my efforts, our org keeps making very long dashboards with lots of panels, so this is very useful.

I agree editing the raw gridPos is not generally useful.  However it is significantly better than trying to drag the newly created panel at the top of a long dashboard to the bottom (or somewhere in the middle)

I'll take a look at migrating this to react.

**Comment by ryantxu** [comment]
I'll wait for #13397 then give this another stab

**Comment by torkelo** [comment]
Closing this for now. Might be good to open a feature request that outlines the use case & scenario so that users can vote for this.

**Pull request closed without merging**
