### PR TITLE
Added string thresholds for singlestat and table panel

### PR DESCRIPTION
**Pull request by bmundt**
Related issue/feature request: [#3601](https://github.com/grafana/grafana/issues/3601)

This will allow you to input regex for threshold values in both the singlestat and table panels.
The regex works like this: Enter regex, seperated by commas for more regex. Make sure the regex starts with a forward slash, so it can determine between a number and regex. Anything that does not match a regex, will be mapped to the first color, this is similar to how the thresholds with numbers work, where anything <= the first number is mapped to the first color.

The getColorForValue function seems redundant to be in both the table panel and singlestat, I am considering moving it to somewhere common, like /public/app/core/utils/kbn.js . However, this would break the current tests for singlestat, requiring that they be moved to kbn_specs. The file singlestat_panel_specs.ts would then be useless and have to be removed, not sure how that works with a pull request.

### CODE REVIEW

**Comment by bmundt** [comment]
Table thresholds will be added shortly

**Comment by zarbis** [comment]
Is this PR abandoned? Would love to see this feature.

**Comment by torkelo** [comment]
closing this, think it complicates the code to much and is confusing number thresholds with text -> color mappings. Something that if implemented needs it's own concept, feel it makes the code to hacky to use the thresholds for this

**Comment by lucasrodcosta** [comment]
Hi @zarbis and @torkelo. I created a concept for this in #7631.
What do you think? Makes sense?

**Pull request closed without merging**
