### PR TITLE
Feature: LDAP refactoring

### PR DESCRIPTION
**Pull request by markelog**
What this does –
1. incapsulates multipleldap logic under one module
1. abstracts users upsert and get logic
1. changes some of the text error messages and import sort sequence
1. heavily refactors the LDAP module – LDAP module now only deals with LDAP related behaviour
1. integrates affected `auth_proxy` module and their tests

This pull already can be merged. But there is couple things that I want to improve here -
1. add tests to multildap module
1. multipleldap/ldap/user defined as services – not sure if that's correct?
1. LDAP and user upsert logic was previously coupled together, their tests still are

### CODE REVIEW

**Comment by markelog** [comment]
Had to introduce new commits, since I dependent on them for bench tests

**Review by xlson — COMMENTED** [review]
Great work!

I think defining ldap and others as services are fine for now. Not sure where else we would put them.

Two minor things, I'm a bit skeptical about the multiline func definitions, we don't do them anywhere else (that I'm aware of) so they are a bit of a step away from our code style. I can def see it for really long ones, but I don't think the ones I've seen it used for are long enough to warrant it. Perhaps something to talk about on a backend weekly.

Also wondering what the thinking is with the named imports? That's also a bit of a step away from the current code style.

I think we can merge the code before adding the tests to multildap, but make sure to add those in as well after this is merged.

**Comment by markelog** [comment]
> Perhaps something to talk about on a backend weekly.

Will put it on the notes!

> Also wondering what the thinking is with the named imports? That's also a bit of a step away from the current code style.

Well :), "LDAP" is an abbreviation and I am bit shivery when I type `ldap` since abbreviation should be capitalized! In other words I think that's my idiosyncrasy popping up :)

**Comment by xlson** [comment]
While you are techincally correct in using LDAP over ldap, I don't think it's the right choice for our code, it pops out and forces the reader to think twice (or at least me :) )

**Comment by markelog** [comment]
Gotcha, will rename those things in subsequent pr!

Regards,
Oleg

**Comment by xlson** [comment]
@markelog I'd suggest doing it now. No need for a separate PR for that.

**Comment by markelog** [comment]
Ok-ok

Regards,
Oleg

**Comment by markelog** [comment]
Removed the named imports.

Good to go?

**Review by xlson — APPROVED** [review]

**Comment by torkelo** [comment]
This needs an update to enteprise as well, current master build is failing.

Screen Shot 2019-05-18 at 19 02 47

**Pull request merged**
