### PR TITLE
DataLinks: Enable value time windowing in TimeSrv

### PR DESCRIPTION
**Pull request by dprokop**
This PR introduces changes to TimeSrv that enables value time windowing.

Given a value time and custom time window size TimeSrv will set time range to be narrowed down to a specified window. I.e given a 5s window and value timestamp, dashboard's time range will be set to (valueTs - 2.5s) - (valueTs + 2.5s).

The change introduced to TimeSrv is about enabling support for `valueTime` & `valueTimeWindow` query params that's translated to a custom time range.

### CODE REVIEW

**Comment by dprokop** [comment]
@torkelo This supports only symmetrical windows around value time. WDYT about introducing syntax support for value time windowing when the valueTime is a limit value for the time range? I mean:

?valueTime=TS&valueTimeWindow=+window would result in time range:

```
{ 
  from: valueTimeTS,
  to: valueTimeTS+window
}
```

?valueTime=TS&valueTimeWindow=-window would result in time range:

```
{ 
  from: valueTimeTS-window,
  to: valueTimeTS
}
```

**Review by ryantxu — COMMENTED** [review]
`valueTime` and `valueTimeWindow` seem kinda specific

what about the parameters `time` and `timeWindow`, or maybe `time.window`?

I would expect `time.window` to take a duration string, like '5m' or '10s' and then do the math to put `time` in the middle of the window.  If you don't want the middle, then you can calculate and set the to/from parameters directly?

I'm not sure now is the time for this change, but I think `time` should be saved in `TimeSrv` along with to/from -- this will be useful for anything trying to query or display based on a single time, not the range

**Comment by dprokop** [comment]
> what about the parameters time and timeWindow

Yeah, this sounds better.

> I would expect time.window to take a duration string, like '5m' or '10s' and then do the math to put time in the middle of the window. If you don't want the middle, then you can calculate and set the to/from parameters directly?

Actually I don't think you could calculate it now, as we don't have support for any expressions in the data links and this would be necessary to increment/decrement value of `valueTime` variable.

**Comment by torkelo** [comment]
> Actually I don't think you could calculate it now, as we don't have support for any expressions in the data links and this would be necessary to increment/decrement value of valueTime variable.

Not sure I understand what you mean. nothing needs to be done in the data links for this:
Imagine an url like
http://localhost:3000/d/5SdHCadmz/panel-tests-graph?time=${__value_time}&time.window=30s

TimeSrv will check for url params time & time.window and set from & to accordingly.  At least that is how I imagined this would work.

**Comment by dprokop** [comment]
@torkelo I was refering to :

> If you don't want the middle, then you can calculate and set the to/from parameters directly?

I have confused from/to with from/to query params :)

**Comment by dprokop** [comment]
Changed params and added support to time window being specified as interval string or in ms. Discussed with @torkelo and we are not gonna focus on ranges relative to __value_time. I.e. case when you want to specify `?from=${value_time}&to=${value_time}+5s`. Followup issue for supporting such case https://github.com/grafana/grafana/issues/18679

**Review by torkelo — APPROVED** [review]
Looks good!

**Pull request merged**
