### PR TITLE
DashboardSchema: Add options to VariableModel

### LINKED ISSUE #67639: Missing parameters on VariableModel schema
While working on Grafonnet, I missed a few parameters:

- `regex`
- `refresh`
- `multi`
- `includeAll`
- `allValue`
- `sort`

I've worked around it by providing some veneer in Grafonnet but that shouldn't be necessary.

https://github.com/grafana/grafana/blob/15d41698138f250b85ccd423f2f252dea7cf3c93/kinds/dashboard/dashboard_kind.cue#L174-L197

### PR DESCRIPTION
**Pull request by someden**
Add `includeAll`, `allValue` and `regex` options to `VariableModel`

Fixes: #67639

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by someden** [comment]
@imatwawana Is there anything else I need to do in this PR?

**Comment by imatwawana** [comment]
@someden, this requires technical review, but the teams tagged for review weren't quite correct. I've tagged the team that should review this.

**Review by L-M-K-B — COMMENTED** [review]
Hi @someden, Thanks a lot for contributing to Grafana. I have a questions regarding your changes. You added 3 of the parameters mentioned in the original issue. What about the other 3?

**Comment by someden** [comment]
Hi @L-M-K-B, other parameters already exist, looks like they were added before.

**Review by torkelo — APPROVED** [review]

**Review by ivanortegaalba — APPROVED** [review]

**Comment by spinillos** [comment]
I added the backport to 10.1.x and 10.2.x to promote them to the kind-registry.

We need these changes to add them to the builders: https://github.com/grafana/grafana-foundation-sdk/issues/17

**Pull request merged**
