### PR TITLE
Azure Monitor: Add support for cross resource queries

### LINKED ISSUE #18302: AzureMonitor: Add cross-resource metrics query
Out of box Top N and Bottom N queries; with N configurable, customers can select Top vs Bottom (ASC vs. DSC order)

### PR DESCRIPTION
**Pull request by sunker**
This feature makes it possible to query over multiple resources in multiple subscriptions in one single query. 

fixes #18302

### CODE REVIEW

**Review by briangann — APPROVED** [review]
LGTM, changes work, we'll open separate issues for additional enhancements

**Review by daniellee — APPROVED** [review]
Mostly LGTM, found three issues:

- We talked about renaming Cross Resource to Multiple Resources?
- Alerting for cross-resource queries doesn't work
- Caching issue with the Resource Type field. Need to select something from one of the previous fields to trigger the dropdown getting populated.

**Review by daniellee — CHANGES_REQUESTED** [review]
Have to change my LGTM to alerting needs to be fixed and this breaks alerting for both single and multiple resource queries.

The problem is that the json saved in the dashboard does not look like this anymore: https://github.com/grafana/grafana/blob/18302-azure-monitor-cross-resource/pkg/tsdb/azuremonitor/azuremonitor-datasource_test.go#L36-L48

When alerting executes, these 3 fields are now set to nil:
https://github.com/grafana/grafana/blob/18302-azure-monitor-cross-resource/pkg/tsdb/azuremonitor/azuremonitor-datasource.go#L93-L95

**Review by daniellee — APPROVED** [review]
This is a bit last minute before the beta release - have seen the changes that Erik is pushing in a minute and they are good enough for now.

**Pull request merged**
