### PR TITLE
Revert "Chore: Remove components from the graveyard folder in grafana/ui"

### PR DESCRIPTION
**Pull request by academo**
Reverts grafana/grafana#83545

Some of the components removed in this PR are still used by external plugins.

### CODE REVIEW

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by torkelo** [comment]
@academo what plugins are using these components??

**Comment by academo** [comment]
@torkelo 

the first obvious one is our plugin examples https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-basic but of course that is easy to fix by simply changing it.

There are also other plugins such as opennms-helm-flow-datasource, bmchelix-ade-datasource (and more) that are reported by our internal dependency analyzer.

**Comment by torkelo** [comment]
@academo I don't see any usage of the old angular graphs components

**Pull request merged**
