### PR TITLE
Data Sources: Remove Admin/Data sources page in favour of Connections/Data sources

### PR DESCRIPTION
**Pull request by mikkancso**
**What is this feature?**

This PR removes the **Admin/Data sources** page and introduces a redirection to the **Connections/Data sources** page.
The same is true for
- New datasource page (datasources/new)
- Edit datasource page (datasources/edit)
- Datasource dashboards page (datasources/edit/:uid/dashboards)

As we will serve these pages only from under Connections, I moved the files of these from the `features/datasources` folder to the `features/connections` folder.
In fact, I moved almost everything from the `features/datasources` folder to the `features/connections` folder, as I thought the only thing that is still relevant to `datasources` is the old routes where these pages used to live.

I didn't set up a redirect for the datasources details page, because we would have to redirect from `plugins/:id`, but it's not only data sources that are served at that URL. So we would have to detect if that ID is of a data source, and then redirect, which feels a little bit twisted.
I did, however, change the link on the Admin/Plugins page's cards for datasources, so if users click that, they will go to `/connections/datasources/:id`.

Demo:
[Screencast from 2023-07-17 11-13-11.webm](https://github.com/grafana/grafana/assets/13637610/ef9b5513-4375-4384-991a-b298e9567004)

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/cloud-onboarding/issues/4008

**Special notes for your reviewer:**
I informed the docs team about this change. I'm not sure about the status of this on their side, though.

There is something wrong with the navigation around the datasource dashboards page. In fact, it is already broken on `main`: https://github.com/grafana/grafana/issues/71843
I tried to fix it, but couldn't.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ifrost** [comment]
Looks nice 🙌  but I only checked Explore-related flows (setting up a data source from the data source picker, and going from connections to Explore)

One note: If I understand correctly with `dataConnectionsConsole` disabled there's no way to access data source settings. Is that expected? Is it documented?

**Comment by mikkancso** [comment]
> Looks nice raised_hands but I only checked Explore-related flows (setting up a data source from the data source picker, and going from connections to Explore)
> 
> One note: If I understand correctly with `dataConnectionsConsole` disabled there's no way to access data source settings. Is that expected? Is it documented?

I intend to remove that feature toggle entirely soon. IIUC I should do it before the 26th, so I don't have much time left.

**Comment by mikkancso** [comment]
I'm converting this PR to draft, because I separated out the main part to another PR: https://github.com/grafana/grafana/pull/72102

**Comment by mikkancso** [comment]
I'm closing this outdated PR now. Please let me know if you'd still like to see the move from the `features/datasources` folder to the `features/connections` folder happening, and I can put together a PR for it.

**Pull request closed without merging**
