### PR TITLE
Second to HH:mm:ss formatter

### PR DESCRIPTION
**Pull request by gladdiologist**

### CODE REVIEW

**Comment by gladdiologist** [comment]
Related issue #11107

**Comment by torkelo** [comment]
We already have this for millisecond epoch, think that unit should be extended to detect  if value is seconds epoch

**Comment by torkelo** [comment]
Oh, sorry, disregard that comment, this is not a timestamp

**Comment by torkelo** [comment]
This looks good, just needs unit tests :)

**Comment by gladdiologist** [comment]
Hi Torkel,

Sure :)
Can you help me to do it??

**Review by torkelo — DISMISSED** [review]
with some unit tests I think this could be merged

**Comment by gladdiologist** [comment]
Perfect, i will update kbn.jest.ts!

**Review by gladdiologist — COMMENTED** [review]
Add some unit tests

**Comment by bergquist** [comment]
The changes look's good.

If you rebase this PR I will merge it.

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
Thank you for contributing! :)

**Pull request merged**
