### PR TITLE
Alerting: Fix return code on silences (#61966)

### LINKED ISSUE #61966: POST to /api/alertmanager/grafana/api/v2/silences returns 202, while docs say it should return 201
**What happened**: A Grafana Labs prospect was trying out calls to the alerting API, based on our documentation here: 
https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json

Per the documentation, the call should return a 201 upon success. However the current experience is that a 201 is returned; therefore the prospect's automation needs to differ from our published documentation.

**What you expected to happen**: 201 on successful POST to /api/alertmanager/grafana/api/v2/silences

**How to reproduce it (as minimally and precisely as possible)**: I reproduced this simply by creating a Silence in the UI, and watching the network tab; call succeeded, 202 was the response code.

**Anything else we need to know?**:
Screen Shot 2023-01-21 at 8 14 32 AM

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: n/a
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: MacOSX/Chrome
- Grafana plugins: n/a
- Others: none

### PR DESCRIPTION
**Pull request by bla2ej**
**What is this feature?**

Currently return code for create silences with POST to /api/alertmanager/grafana/api/v2/silences returns 202 instead of 201 as specified in documentation.
This PR fixes #61966

**Why do we need this feature?**

POST used to create something should use 201 return code which means CREATED.
202 means ACCEPTED and is misleading.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #61966

**Special notes for your reviewer**:

Simple change of return code.

### CODE REVIEW

**Comment by bla2ej** [comment]
Anyone can help me why Enterprise PR check is failing?

**Review by alexmobo — CHANGES_REQUESTED** [review]
Hi @bla2ej! Thanks for your PR!

It would be best if you change the return of the endpoint status to 200.

**Comment by bla2ej** [comment]
Thanks @alexmobo,
Of course I will update it to 200. 
Just to be sure. Should I update also `pkg/services/ngalert/api/tooling/definitions/alertmanager.go` to reflect the change in swagger?

And maybe one additional question, what should I do to make this check not failing?
- Enterprise PR check / dispatch (pull_request)

I'm new in this project and I couldn't find what to do to make this working.

**Comment by bla2ej** [comment]
Thanks @alexmobo, 
I have regenerated definitions. I hope it's correct.

**Comment by alexmobo** [comment]
Hi @bla2ej, thanks for your contribution. Unfortunately, we are going to update the documentation instead of making this change. Understand that this change brakes compatibility.

My bad. It was a misunderstanging on my part.

Hope you continue contributing to Grafana!

**Pull request closed without merging**
