### PR TITLE
Kindsys: Extend DocsJenny with support for 'allOf'

### PR DESCRIPTION
**Pull request by joanlopez**
**What is this feature?**

It extends the [`DocsJenny`](https://github.com/grafana/grafana/blob/main/pkg/codegen/jenny_docs.go) to add support for [`allOf` keyword from JSON Schema spec](https://json-schema.org/understanding-json-schema/reference/combining.html#allof).

It is used, for instance, when "struct embedding" into struct schemas (like `common.DataQuery` [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/testdata/dataquery.cue#L33)).

Note, this does not imply the support of other JSON Schema keywords like `oneOf`, `anyOf` or `not`, which hopefully will come at later stage - we still consider worthful to have this partial support for one of those than none.

**Why do we need this feature?**

Because docs for schemas aren't being generated properly, as discussed [here](https://github.com/grafana/grafana/pull/62112#discussion_r1086942811), for instance.

**Who is this feature for?**

Anyone who's directly or indirectly involved with Grafana schemas and codegen.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/schematization-and-as-code-project/issues/62 and https://github.com/grafana/schematization-and-as-code-project/issues/57

Also fixes https://github.com/grafana/schematization-and-as-code-project/issues/61 thanks to https://github.com/grafana/grafana/pull/62638.

**Special notes for your reviewer**:

### CODE REVIEW

**Review by undef1nd — APPROVED** [review]
This is such a huge improvement, in my opinion! ❤️ Thanks, Joan.

**Review by sdboyer — APPROVED** [review]
This looks great.

The only thing to note is that we're now assigning words to logical operations - e.g. "extends," "inherits" - and i'm not entirely sure those are always the right words to use everywhere that we see these operations.

However, i don't think that's a problem we can reasonably tackle until after we have a good testing system that lets us deal with these issues one at a time.

**Comment by joanlopez** [comment]
> This looks great.
> 
> The only thing to note is that we're now assigning words to logical operations - e.g. "extends," "inherits" - and i'm not entirely sure those are always the right words to use everywhere that we see these operations.
> 
> However, i don't think that's a problem we can reasonably tackle until after we have a good testing system that lets us deal with these issues one at a time.

I couldn't agree more! hahaha And as I mentioned many times, as a non-native speaker, even more! 
So, I'm not sure how much could I help with that one, but I'm all ears; and I'm completely in favor of being accurate with wording, it's generally superhelpful!

**Comment by sdboyer** [comment]
Yeah we're gonna have to invest some effort in picking words here, for sure. But, future problem, coming only after having a test corpus :)

**Pull request merged**
