### PR TITLE
Add the file label to dashboard provisioning errors

### PR DESCRIPTION
**Pull request by nabokihms**
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

**What this PR does / why we need it**:

It is unclear which dashboard caused an error. 

Logs example:
```
logger=provisioning.dashboard type=file name=GrafanaDashboardDefinition t=2022-08-03T11:13:47.92+0000 lvl=eror msg="failed to save dashboard" error="alert validation error: error in condition 0: evaluator 'IS ABOVE' is missing the threshold parameter PanelId: 21"
```

### CODE REVIEW

**Comment by nabokihms** [comment]
@aknuds1 Hello! I remember that we were working together on provisioning PRs a couple of years ago.
This is a small change that will help to debug problems while using provisioning.

I do not know who is in charge of reviewing external backend PR's at the current time. Could you please give me a hint how I can get this PR merged?

**Comment by nabokihms** [comment]
@kylebrandt @zserge @idafurjes could you please give me feedback on this change? I'd love to take it to a future release.

**Comment by nabokihms** [comment]
I'm still waiting here. Still thinking that this is a small yet valuable change.

**Review by idafurjes — APPROVED** [review]
looks good to us

**Pull request merged**
