### PR TITLE
Cloudwatch: Add FraudDetector namespace with metrics and dimensions

### PR DESCRIPTION
**Pull request by ffje**
**What is this feature?**

The PR adds missing FraudDetector namespace, metrics and dimensions for Cloudwatch

**Why do we need this feature?**

When you're using the Cloudwatch as a data source and you're trying to search for 'FraudDetector' namespace grafana shows that it's missing

**Who is this feature for?**

Anyone who uses Amazon Fraud Detector

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by iwysiu** [comment]
Hi @ffje , thanks for the contribution! From looking at the [docs](https://docs.aws.amazon.com/frauddetector/latest/ug/monitoring-cloudwatch.html#YourService-metrics), it seems like there should be more dimensions listed?

**Comment by ffje** [comment]
> 

that's right @iwysiu, thanks for noticing! Will add it soon.

**Comment by ffje** [comment]
hey @iwysiu I've updated the PR. However, I'm not sure it worth to keep something beside my initial proposed metrics: GetEventPrediction, GetEventPredictionLatency, GetEventPrediction4XXError, GetEventPrediction5XXError. And the only dimension - DetectorID.

AWS Cloudwatch console does not show any metrics except those. Could you please advice, should I keep as is or revert it back?
image
image

**Comment by ffje** [comment]
@iwysiu Thanks for suggestion. For my own FraudDetector setup it does nothing, however there are multiple FraudDetector types, so it might be useful for other ones. I'd keep it as is for now.

Any further steps should I do to proceed with PR? Thanks in advance.

**Review by iwysiu — APPROVED** [review]
LGTM! Nope, there's nothing else you have to do, I'll handle the CI checks. Thanks again for contributing!

**Pull request merged**
