### PR TITLE
[WIP] Add panel visibility flag and delay metric refresh

### PR DESCRIPTION
**Pull request by ryantxu**
Spinning out from #12200

This patch adds a `visible` property to each panel and keeps it updated with a callback.

The MetricsPanelCtrl will delay refresh requests until the panel is visible

TODO:
- [x] Decide/evaluate `IntersectionObserver` vs `Scroll Listener`
- [x] If `IntersectionObserver` make sure reasonable fallback when not supported by browser
- [ ] Decide... should this be a dashboard option?  or always enabled?
- [ ] Unit tests

### CODE REVIEW

**Comment by mtanda** [comment]
Only Safari doen't support IntersectionObserver.
https://caniuse.com/#search=IntersectionObserver

I compare the performance and Safari polyfill.

Diff:
https://github.com/ryantxu/grafana/compare/panel-visibility-flag...mtanda:panel-visibility-flag

Dashboard:
https://gist.github.com/mtanda/93fa3dd84d68738dca14dfa054820ce0

OS:
macOS

Browser and version:
- Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Firefox 61.0.1 (64-bit)
- Safari Version 11.1.1 (13605.2.8)

Chrome result:
chrome

Firefox result:
firefox

Safari result:
safari

**Comment by mtanda** [comment]
The IntersectionObserver is slower than scroll event, but the difference between scroll and IntersectionObserver is very small.
And polyfill works enough fast.

I think IntersectionObserver is usable for lazy load :-)

**Comment by ryantxu** [comment]
thanks @mtanda -- i added the polyfill and removed the scroll option.

I'll look at adding some tests.

Do you know if there is a way to force the intersection checks? Or is that not necessary?

**Comment by mtanda** [comment]
> Do you know if there is a way to force the intersection checks? Or is that not necessary?

I don't know, but I guess it is impossilbe to force the check.

I didn't read it, but MDN has most helpful document.
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

I think we don't need force check, when user scroll fast, some panel loading is skipped, but it is correct behavior.

**Comment by ryantxu** [comment]
@torkelo - can you take a look at this and see if it fits in the panel roadmap?  

I have been using it in production for a while and it has been working great.

If it looks reasonable, I can add some tests and get it ready for a real review.

**Comment by torkelo** [comment]
I think I have another simpler way to solve this that I hope to do in v6 or v6.1

**Pull request closed without merging**
