### PR TITLE
Update datasource before the loading has started

### LINKED ISSUE #14976: Explore: After changing data source the error state is very confusing
After changing to data source that causes an error the data source picker is still the old value (before change) but the page only shows error.  

screen shot 2019-01-21 at 21 37 49

Here I changed from Loki (a working data source) to one that causes a test failure. But it looks like Loki is still selected. To get a working explore again I have to select Loki again from the data source picker even though it is already selected. 

I think the data source validation (testDatasource) should not cancel the data source selection. the switch should still take place. And the data source picker should show the changed data source. 

thoughts @davkal?

### PR DESCRIPTION
**Pull request by dprokop**
Fixes #14976 

New action, `UpdateDatasourceInstance`, added to handle the UI change before loading disaptched.

### CODE REVIEW

**Review by davkal — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
I am looking at the merge conflict, and trying to review the code. the datasource state is also way to complicated in explore, with intiialDatasource, datasourceInstance, & requestedDatasource. Has to be easier way :)

**Comment by davkal** [comment]
> I am looking at the merge conflict, and trying to review the code. the datasource state is also way to complicated in explore, with intiialDatasource, datasourceInstance, & requestedDatasource. Has to be easier way :)

I'm sure there is a way to combine two of those, but that would make it less explicit, and then properties have multiple semantics. That makes code slimmer, but not easier. Explore is trying to model intermediate state of async operations. That state has to be represented somewhere. (I'm not sure how dashboard panels do it, either there are fewer async actions there, resulting in fewer properties to notify the user of what is happening, or they are not signalling to the user what is happening.)

**Comment by torkelo** [comment]
well initialDatasource was not used anywhere :)

I do not think this solves the complete issue. It still leaves explore in a semi broken state just because a network issue.

**Comment by torkelo** [comment]
I think the loadDatasourceSuccess sets a number of flags that should always be set when switching data source no matter if the testDatasource succeeded or not.

**Comment by dprokop** [comment]
Gonna take a deeper look on that now

**Pull request merged**
