### PR TITLE
CamelCase files

### PR DESCRIPTION
**Pull request by user10x**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
https://github.com/grafana/grafana/issues/51230

**Special notes for your reviewer**:
Not Ready

### CODE REVIEW

**Comment by user10x** [comment]
Remaining datasources, should open another PR? Trying an issue for the first time, do not want to clutter a browser crashing change with too many files being renamed

```
tree  public/app/plugins/datasource | grep _ | grep .ts$
│   ├── aws_url.ts
│   ├── language_provider.test.ts
│   ├── language_provider.ts
│   │   └── query_def.test.ts
│   │   ├── query_ctrl.ts
│   │   ├── azure_log_analytics_datasource.test.ts
│   │   ├── azure_log_analytics_datasource.ts
│   │   └── response_parser.ts
│   │   ├── azure_monitor_datasource.test.ts
│   │   ├── azure_monitor_datasource.ts
│   │   ├── response_parser.ts
│   │   ├── url_builder.test.ts
│   │   └── url_builder.ts
│   │   ├── azure_resource_graph_datasource.test.ts
│   │   └── azure_resource_graph_datasource.ts
│   │   ├── querystring_builder.test.ts
│   │   └── querystring_builder.ts
│   ├── time_grain_converter.test.ts
│   ├── time_grain_converter.ts
│   ├── datasource_integration.test.ts
│   ├── graphite_query.ts
│   │   ├── graphite_query.test.ts
│   ├── influx_query_model.ts
│   ├── influx_series.ts
│   ├── query_builder.ts
│   ├── query_part.ts
│   ├── response_parser.ts
│   │   ├── influx_query_model.test.ts
│   │   ├── influx_series.test.ts
│   │   ├── query_builder.test.ts
│   │   ├── query_part.test.ts
│   │   └── response_parser.test.ts
│   ├── config_ctrl.ts
│   ├── query_ctrl.ts
│   ├── response_parser.ts
│   ├── meta_query.ts
│   ├── mysql_query_model.ts
│   ├── query_ctrl.ts
│   ├── response_parser.ts
│   ├── sql_part.ts
│   ├── query_ctrl.ts
│   │   └── query_ctrl.test.ts
│   ├── config_ctrl.ts
│   ├── meta_query.ts
│   ├── postgres_query_model.ts
│   ├── query_ctrl.ts
│   ├── response_parser.ts
│   │   └── postgres_query.test.ts
│   ├── sql_part.ts
│   ├── language_provider.ts
```

**Comment by ivanahuckova** [comment]
Hello [user10x](https://github.com/user10x) and thank you for this contribution. There is a lot of changes in this PR and we are usually trying to do smaller/incremental changes. Would you mind splitting this into couple of PRs:
- public/app/plugins/datasource/loki
- public/app/plugins/datasource/elasticsearch
- public/app/core/logs_model.ts

Also I noticed that you have done changes for Prometheus which would would be again awesome if it was separate PR as well as changes for `app_events`, `table_model` and `time_series2`.

Secondly in [File and directory naming conventions](https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions) it is mentioned that `When the primary export is a class or React component, use PascalCase.` and there are couple files that export defaultly Class. In this case, they should be named using `PascalCase` (e.g.  language_provides, but also others).

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
Hello [user10x](https://github.com/user10x) and thank you for this contribution. 🧡 There is a lot of changes in this PR and we are usually trying to do smaller/incremental changes. Would you mind splitting this into couple of PRs:
- public/app/plugins/datasource/loki
- public/app/plugins/datasource/elasticsearch
- public/app/core/logs_model.ts

Also I noticed that you have done changes for Prometheus which would would be again awesome if it was separate PR as well as changes for `app_events`, `table_model` and `time_series2`.

Secondly in [File and directory naming conventions](https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions) it is mentioned that `When the primary export is a class or React component, use PascalCase.` and there are couple files that export defaultly Class. In this case, they should be named using `PascalCase` (e.g.  language_provides, but also others).

**Comment by user10x** [comment]
> Hello [user10x](https://github.com/user10x) and thank you for this contribution. 🧡 There is a lot of changes in this PR and we are usually trying to do smaller/incremental changes. Would you mind splitting this into couple of PRs:
> 
> * public/app/plugins/datasource/loki
> * public/app/plugins/datasource/elasticsearch
> * public/app/core/logs_model.ts
> 
> Also I noticed that you have done changes for Prometheus which would would be again awesome if it was separate PR as well as changes for `app_events`, `table_model` and `time_series2`.
> 
> Secondly in [File and directory naming conventions](https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions) it is mentioned that `When the primary export is a class or React component, use PascalCase.` and there are couple files that export defaultly Class. In this case, they should be named using `PascalCase` (e.g. language_provides, but also others).

thanks for the feedback, i will put up multiple component PRs for smaller merges 🛳  and post them here

**Comment by ivanahuckova** [comment]
I am closing this pull request as we agreed that this should be done in smaller, more focused  PRs.

**Pull request closed without merging**
