### PR TITLE
chore(76107): Removed LegacyForm from FolderSettingsPage

### LINKED ISSUE #76107: Chore [Epic]: Replace LegacyForms in core Grafana
**What is the chore?**:
We have a set of legacy form components, which essentially were deprecated over 3 years ago ( #22862). They all have modern replacement components.

We only [have 11 occurences in core left](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1&from=1680771811847&to=1696583011847&viewPanel=13), so I though I'd make a list:

`grep -r -o 'LegacyForms;' public/app`:

 - [ ] public/app/core/components/Select/MetricSelect.tsx
 - [x] public/app/plugins/datasource/loki/configuration/QuerySettings.tsx https://github.com/grafana/grafana/pull/76331
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/ConfigEditor.tsx https://github.com/grafana/grafana/pull/76382
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/InfluxFluxConfig.tsx https://github.com/grafana/grafana/pull/76495
 - [ ] public/app/plugins/datasource/influxdb/components/editor/config/InfluxInfluxQLConfig.tsx
 - [x] public/app/plugins/datasource/opentsdb/components/OpenTsdbDetails.tsx https://github.com/grafana/grafana/pull/76165
 - [x] public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx https://github.com/grafana/grafana/pull/76397
 - [x] public/app/features/admin/ldap/LdapPage.tsx https://github.com/grafana/grafana/pull/76156
 - [x] public/app/features/folders/FolderSettingsPage.tsx https://github.com/grafana/grafana/pull/76313
 - [ ] public/app/angular/angular_wrappers.ts

**Is there anything else we need to know?**:
 In some cases just changing the component might not be enough, as it is located in older code. In these cases, removing occurrences of `gf-form` might also be valuable. If you do, please mention #65513.

**Related issues**
https://github.com/grafana/grafana/issues/66479
https://github.com/grafana/oss-plugin-partnerships/issues/222

### PR DESCRIPTION
**Pull request by carlqt**
**What is this feature?**

Removing legacy form components from `FolderSettingsPage.tsx`

**Why do we need this feature?**

According to #76107, these components are deprecated and have modern replacements.

**Who is this feature for?**

devs

**Which issue(s) does this PR fix?**:

Related to #76107

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

# Screenshots
## Before
image

## After
image

### CODE REVIEW

**Comment by Clarity-89** [comment]
Hi, thank you for the contribution! Do you have before and after screenshots for this change?

**Comment by carlqt** [comment]
Hi @Clarity-89 , I'm still new so I'm trying to figure out where can I check the component. I did a little search and I can't find any place this component is being used.

**Comment by Clarity-89** [comment]
> Hi @Clarity-89 , I'm still new so I'm trying to figure out where can I check the component. I did a little search and I can't find any place this component is being used.

I have double checked with the team and apparently this component is not used anymore. If you'd modify your PR to remove it instead, that'd be great :)

**Comment by Clarity-89** [comment]
@carlqt, sorry for the confusion, it looks like this page can only be visible by explicitly setting the `newBrowseDashboards` feature flag to false. So if you add `newBrowseDashboards = false` to your `custom.ini`, you'd see the `Settings` tab when you go to folder. 

To properly remove the LegacyInput here, you'll also need to wrap the new `Input` component into a Field and remove all the CSS classes from it, so it'll look smth like this:
```js
        <Field label={'Name'}>
            <Input type="text" id="folder-title" value={folder.title} onChange={this.onTitleChange} />
         </Field>
```

**Comment by carlqt** [comment]
> @carlqt, sorry for confusion, it looks like this page can only be visible by explicitly setting the `newBrowseDashboards` feature flag to false. So if you add `newBrowseDashboards = false` to your `custom.ini`, you'd see the `Settings` tab when you go to folder.
> 
> To properly remove the LegacyInput here, you'll also need to wrap the new `Input` component into a `Field` and remove all the CSS classes from it, so it'll look smth like this:
> 
> ```js
>         <Field label={'Name'}>
>             <Input type="text" id="folder-title" value={folder.title} onChange={this.onTitleChange} />
>          </Field>
> ```

Hi @Clarity-89, sorry I wasn't able to reply sooner, I was a bit busy.

So I've tried adding `newBrowseDashboards = false` in the `custom.ini` file but I still couldn't find it.

I'm not sure if I'm doing this right but I've created a `folder` in the `Dashboard` page but I couldn't see where the `FolderSettingsPage` component is.
image

**Comment by Clarity-89** [comment]
@carlqt when you hover on the dashboard name, you'd see `Go to folder` action show up, clicking it will go to the folder detail view.

**Comment by carlqt** [comment]
> @carlqt when you hover on the dashboard name, you'd see `Go to folder` action show up, clicking it will go to the folder detail view.

I've tried hovering to most text displayed in the screen but I never saw the `Go to folder` show up. I've added a screenshot that shows where I've tried hovering.

image

**Comment by Clarity-89** [comment]
You'd be able to see the link show when hovering on `gdev dashboards` name or any other dashboard name, except `General`. Alternatively, if you right click on the dashboard name and inspect the element, you'd see the `a` tag with the URL to the folder, which you can use. 
Screenshot 2023-10-17 at 8 26 00

**Comment by carlqt** [comment]
Thanks for the screenshot. I can see that the table is a little different from what I'm seeing. There's also the set of icons beside the `Sort` element.

From the clues here, I'm guessing that I wasn't able to get the `newBrowseDashboards` flag to work properly. I even tried adding `newBrowseDashboards = false` in `default.ini` but I still couldn't see any change

**Comment by Clarity-89** [comment]
> From the clues here, I'm guessing that I wasn't able to get the `newBrowseDashboards` flag to work properly. I even tried adding `newBrowseDashboards = false` in `default.ini` but I still couldn't see any change

Did you add it under the `[feature_toggles]` section, like so:
```
// custom.ini
[feature_toggles]
newBrowseDashboards = false
```

**Comment by carlqt** [comment]
Hi @Clarity-89 , I've figured out what's wrong with my setup. I didn't place the `custom.ini` file inside the `conf` directory that's why the feature flags aren't being read. Once I've done it, I'm able to see the components.

Thanks for being patient and helping out and sorry if this thread became a bit like "tech support help"

**Comment by carlqt** [comment]
Hi @Clarity-89, I've updated the PR with new changes let me know if there's anything I missed

**Review by Clarity-89 — APPROVED** [review]
Great work! 🎉  Thank you for fixing this!

**Pull request merged**
