### PR TITLE
(cloudwatch) assume role support

### PR DESCRIPTION
**Pull request by mtanda**
https://github.com/grafana/grafana/issues/3522

Reuse "profile" field and if profile is started from "arn:.*", try to assume role.

### CODE REVIEW

**Comment by tmonk42** [comment]
Did a local build and test, works great for me! This is perfect and will be a huge win for my team (instead of having a deploy of grafana for each AWS account).

Thanks!!!

**Comment by mtanda** [comment]
Add new field "assumeRoleArn" in Json data, and don't reuse "profile".
Set credential provider when calling assume role.

**Comment by mtanda** [comment]
@tmonk42 Thanks for testing!!
I don't test this well, only run this locally, don't run so long time.
If you notice anything, please feed back to me :-)

**Comment by torkelo** [comment]
@mtanda if you have time it would be great if could do a small PR that mentions this in the changelog and maybe a small comment about it in the cloudwatch docs?

**Comment by mtanda** [comment]
@torkelo I got it. I'll do it.

**Pull request merged**
