### PR TITLE
Status History Panel: Show X-Axis Value in Tooltip

### LINKED ISSUE #54034: Status History panel doesn't show date/time in tooltip in
**What happened**:
In earlier versions of Grafana, Status History panel showed timestamp in tooltip when mousing-over graph, however in 9.1, it doesn't:

V 9.1:
image

**What you expected to happen**:
in V 8.5.2:
image
Encountered this issue while testing upgrade to 9.1.0.  Panels were copied directly from 8.5.2 to 9.1 install.

**How to reproduce it (as minimally and precisely as possible)**:
Compare behavior on older version to 9.1 for tooltip content on Status History panel.
**Anything else we need to know?**:

**Environment**:
- Grafana version:  Tested 8.5.2 (works), 9.1 (doesn't work)
- Data source type & version:
- OS Grafana is installed on:  Linux Docker Compose
- User OS & Browser:  Windows, Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Adds date/time in tooltip of Status History panel

**Which issue(s) this PR fixes**:

Fixes #54034

**Special notes for your reviewer**:
https://www.loom.com/share/93a230072c29463f93a669b7167f16e3
image

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @codeincarnate @dprokop Please review the PR 🙏

**Comment by mellieA** [comment]
@gitstart thanks for this contribution too! I'm moving this to the right squad for review.

**Comment by gitstart** [comment]
Hi @codeincarnate @dprokop Please review the PR 🙏

**Comment by codeincarnate** [comment]
Thanks for the contribution @gitstart! I've been out of office but I'll be reviewing this week 😄

**Review by codeincarnate — APPROVED** [review]
Tested out and looks good to me 👍 . We have slightly differing behavior for the tooltips for each respective panel and there _might_ be a small issue but I don't believe it's a result of these changes.

**Pull request merged**
