### PR TITLE
fix relative time override for absolute time range

### LINKED ISSUE #5872: [Bug] Panel Dashboard shared URL time overriding panel time override
Please include this information:
- What Grafana version are you using? 
       v3.1.1
- What datasource are you using? 
      OpenTSDB 2.2
- What OS are you running grafana on? 
      Linux
- What did you do? 
      Overridden the time on Panel and shared the dashboard/panel URL with current dashboard time range.
- What was the expected result?
      Graph panel should consider the overridden time from 'Time Range' section. 
- What happened instead?
      Graph panel is taking the time range from shared URL.

### PR DESCRIPTION
**Pull request by mtanda**
Fix https://github.com/grafana/grafana/issues/5872 .

### CODE REVIEW

**Comment by torkelo** [comment]
This breaks sharing a panel with relative time range. If you zoom into a region in a graph with relative time range override, then try to share it, it will not use the the zoomed in time range. 

In fact this breaks zooming in on a panel with relative time range override.

**Comment by mtanda** [comment]
@torkelo
1. Create the dashboard which has a graph with relative time range override
    dashboard time range = "now-6h to now"
    relative time range override = "last 24h"
2. Reload the dashboard
3. Zoom in the graph, I select "Jan 8, 2017 12:00:00 to Jan 8, 2017 14:00:00"
4. The graph time range still be overriden, not `zoomed in time range`, it displays "Jan 7, 2017 14:00:00 to Jan 8, 2017 14:00:00"
5. Share panel, the time range is not `zoomed in time range`

I'm not sure expected behavior, you means the time range should be `zoomed in time range` in step 4?
So, If I select "Jan 8, 2017 12:00:00 to Jan 8, 2017 14:00:00" in graph, the graph time range should be "Jan 8, 2017 12:00:00 to Jan 8, 2017 14:00:00"?

**Comment by torkelo** [comment]
@mtanda yes you should be able to zoom in to panels with relative time override. The override is only active when the dashboard time is relative.

**Comment by torkelo** [comment]
when I tested this PR the behavior when I zoomed in on

**Comment by torkelo** [comment]
described the issue here https://github.com/grafana/grafana/issues/5872#issuecomment-271237046

**Pull request closed without merging**
