### PR TITLE
Docker: Fix grafana-cli path on binaries COPY step

### PR DESCRIPTION
**Pull request by guicaulada**
**What this PR does / why we need it**:

Currently fails to build container due to path for grafana-cli being wrong on the Dockerfile.

This PR corrects the path so it points correctly to `/grafana/bin/*/grafana-cli` instead of `/go/src/github.com/grafana/grafana/bin/*/grafana-cli`.

**Which issue(s) this PR fixes**:

Necessary for grafana/grafana-enterprise-partnerships-team#2

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by xlson** [comment]
@guicaulada I just ran `docker build .` against latest main and it worked for me (only with oss, not enterprise which I don't think has ever worked). Am I missing something?

Regarding this Dockerfile, it exists for dev and testing but is not used to produce the real grafana docker image. The production ones are in `main/packaging/docker`.

**Comment by guicaulada** [comment]
@xlson It seems other people are having the same issue as me on the COPY step, it's not related to an enterprise build, the issue would happen for me on OSS as well. This fixes #41313.

**Comment by guicaulada** [comment]
It does make sense to use `main/packaging/docker` instead though.

**Comment by guicaulada** [comment]
Apparently the issue happens only on platform `linux/arm64` which would be the M1 Macs, the issue doesnt happen on `linux/amd64` or if you pass the argument `--platform linux/amd64`.

**Comment by xlson** [comment]
I'm on the go but I'll give the pr a 👍when I get back to my computer.

**Review by dsotirakis — APPROVED** [review]

**Pull request merged**
