### PR TITLE
Canvas: Ability to move and resize elements freely

### LINKED ISSUE #40033: Ability to move and resize elements freely

### PR DESCRIPTION
**Pull request by nmarrs**
**What this PR does / why we need it**:
Improves canvas panel by adding the ability to move and resize both individual and multiple elements at a time.

Single Element
single

Multiple Elements
multiple

**Which issue(s) this PR fixes**:

Fixes #40033

### CODE REVIEW

**Comment by nmarrs** [comment]
@leeoniya Multi resize functionality is currently just the default that moveable + selecto library has. There may be some tweaks we can make to this, and if not and / or we don't like current behavior we could alternatively disable resizing multiple elements (and just limit multi selection to moving elements for the time being)

**Review by hugohaggmark — APPROVED** [review]
Looks good, I just did a shallow code review. 

Something to consider in a follow up PR, I think the Edge squad should be the owner of this panel? Maybe the CODEOWNERS file should reflect this?

**Review by ryantxu — APPROVED** [review]
:taco: looks great!

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Pausing this until we've figured out what is happening to the `yarn.lock` file (ping @jackw)

**Review by hugohaggmark — APPROVED** [review]
After a discussion with @jackw and @axelavargas we reverted `yarn.lock` and `package.json` to main branch and re-added the new dependencies again using `yarn2`.

**Comment by nmarrs** [comment]
Thanks @hugohaggmark for fixing the` yarn.lock` file and getting the PR to a mergeable state! 🎊

**Pull request merged**
