### PR TITLE
Adding support for Azure AD Authentication

### PR DESCRIPTION
**Pull request by palmamartin**
Hi, this implements the feature request for supporting Azure AD authentication of issue #5877. In order to make Azure OAuth work I had to update the `golang/oauth2` packages to the latest release. 

Please let me know what you think.

### CODE REVIEW

**Comment by cristianocumer** [comment]
This would be useful also for me!

**Comment by torkelo** [comment]
Is there way to use the generic oauth implementation? maybe with a few changes to make the generic oauth more flexible? 

Feel like we have enough specific oauth implementations.

**Comment by NicolaiPetri** [comment]
Can we get this merged ? I don't see any reasons not to ? Or is there already another working alternative ?

**Comment by torkelo** [comment]
We need a backend plugin system to support more oauth systems (so we can support oauths like this via external plugins that can live outside main repo)

**Comment by hpbieker** [comment]
@torkelo , any chance to get this added? I see that it was just closed, but there is currely not any alternative for people using Azure AD?

**Comment by abelladerocap** [comment]
@mazebuhu  it is possible to obtain the grafana.deb to be used in a docker container. 
I have many problems to get compile the code. Would it help me get the .deb

**Pull request closed without merging**
