### PR TITLE
Datasource: Move onDashboardLoaded to data source api

### PR DESCRIPTION
**Pull request by sunker**
**What this PR does / why we need it**:

The `onDashboardLoaded` is an event that is emitted on the event bus whenever a dashboard is loaded. It contains information about queries in the dashboard. It can be useful if for example a data source would like to track what features in the query editor are being used. 
 
This PR moves the `onDashboardLoaded` event that was previously triggered using the event bus to become a method on the datasource API. 

There are a few reasons to why I'd like to make this change:
* In the as-is solution, an event containing a map of queries per data source is triggered when a dashboard is loaded. Any plugin can subscribe to events on the event bus, which means that any plugin can consume queries belonging to other data sources. Since data source queries may contain sensitive data such as instance names etc, this becomes a security risk. 
* The as-is solution is hard to use. The plugin needs to register in `module.ts` and at that time there's no access to the datasource file so the plugin needs to load it and that is messy. 
* Using a map of queries per data source type ( `Record<string, DataQuery[]>` ), it's hard to provide a strongly typed api. Consumers of the event have to use type guards to assert the right type. Using the datasource api, the correct type will be inferred.

### CODE REVIEW

**Comment by tolzhabayev** [comment]
@sunker 

> In the as-is solution, an event containing a map of queries per data source is triggered when a dashboard is loaded. Any plugin can subscribe to events on the event bus, which means that any plugin can consume queries belonging to other data sources. Since data source queries may contain sensitive data such as instance names etc, this becomes a security risk.

So now every datasource that has `onDashboardLoaded` function will get the queries which is more or less the same level of security risk or am I missing something?

**Comment by sunker** [comment]
> So now every datasource that has `onDashboardLoaded` function will get the queries which is more or less the same level of security risk or am I missing something?

No now every data source that has implemented the onDashboardLoaded method will receive its own queries only. 

The way it's currently designed (before this change), any plugin can subscribe to the onDashboardLoadedEvent. The subscriber would receive query data not only for its own queries, but for queries that are associated with other data sources too. Actually, the subscribing plugin doesn't even need to have queries in the loaded dashboard at all - it would still receive the event.

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
Initial PR https://github.com/grafana/grafana/pull/52052
Relevant PR https://github.com/grafana/grafana/pull/53722

I don't have the whole background story but should definitely align first.

**Comment by sunker** [comment]
Had a chat to @yaelleC and we decided to use a different approach for collecting adoption stats for our plugins. I'll close this PR as there's no obvious need for it now. Think @yaelleC will follow up with a PR deprecating the dashboardOnLoaded event sometime soon.

**Comment by mckn** [comment]
@sunker question regarding this PR. Do we want to track usage of executed queries or how the query editor UI is used? If we want to track executed queries I would recommend doing that on the backend.

**Comment by sunker** [comment]
> @sunker question regarding this PR. Do we want to track usage of executed queries or how the query editor UI is used? If we want to track executed queries I would recommend doing that on the backend.

We would like to be able to measure to what extent certain features in a plugin are being used. For example, the proportion between `Builder` vs `Code` mode. Customers are wondering, and also it would be helpful for us to know we're putting effort into the features that are most widely used. Measuring this in the backend would be tricky since counters would be heavily affected by things such as dashboard refresh interval and if the feature is part of an alert query.

**Comment by mckn** [comment]
Yupp, totally agree! So basically how the query editor is used 👍🏻

**Pull request closed without merging**
