### PR TITLE
Build: Introduce webpack manifest plugin

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Some Grafana services rely on the webpack `[hash]` in filenames from compiled frontend assets to understand if uploads completed successfully. After merging #47625 these services encountered build issues. This PR introduces the Webpack manifest plugin to output the names of all compiled assets to a json file for easier consumption.

Currently the output is placed in `public/build/manifest.json` and contains:

```json5
{
  "app.js": "public/build/app.b226142f7f31e5cfcb2a.js",
  "dark.css": "public/build/grafana.dark.4aa093e77b236c135586.css",
  "dark.js": "public/build/dark.13d60784ae3ab488dee4.js",
  "light.css": "public/build/grafana.light.c2aab27160e4d8b58a67.css",
  "light.js": "public/build/light.ab5bef8058f32ad84c7d.js",
  "runtime.js": "public/build/runtime.aa21ce3cd2876d911a33.js",
  //... all other js (chunks and entries), css and html output from webpack
}
```

The entries in this json file can be filtered and the file itself can be placed in another directory if necessary. @hairyhenderson @filewalkwithme let me know what works best for you.

### CODE REVIEW

**Review by filewalkwithme — APPROVED** [review]
Looks good to me!

I have filled a new issue in Hosted Grafana, so we can refactor our build pipeline after this gets merged;

Thanks so much for this!

**Review by hairyhenderson — APPROVED** [review]

**Review by dprokop — APPROVED** [review]

**Comment by jackw** [comment]
@hairyhenderson @filewalkwithme apologies for not merging this sooner. Do you still need this PR to make your pipeline more robust?

**Comment by filewalkwithme** [comment]
> @hairyhenderson @filewalkwithme apologies for not merging this sooner. Do you still need this PR to make your pipeline more robust?

Hey @jackw , no worries :D

Yes, it would make our build pipeline a bit more robust, indeed. But there is no rush at all.

**Comment by jackw** [comment]
@hairyhenderson @filewalkwithme from chatting with the frontend-ops working group we decided it would be best (for the time being) to not put this manifest in the build directory. It will be placed in the root of the project. I've also filtered out `.map` files from the manifest as they're only required for debugging fe code in production. This will arrive in 9.2.

**Comment by filewalkwithme** [comment]
@jackw thanks a lot!!!

**Pull request merged**
