### PR TITLE
Search: Avoid requesting all dashboards when in Folder View

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What this PR does / why we need it**:

Someone complained that the folder search seemed slower since upgrading to 9, after investigating we figured out that the folder view was making an unnecessary search. These are the requests it makes on load of that view:
- Request ALL dashboards
- Request all folders
- 1 request per expanded folder to request the dashboards in that folder

That first request is unnecessary and never used. It is done because the search input is empty, so it requests all dashboards, but the result is only used if in list view. This PR stops that request from happening.

**Which issue(s) this PR fixes**:

Fixes part of https://github.com/grafana/support-escalations/issues/3857

**Special notes for your reviewer**:

Someone who helped implement search should double check if my assumption that the request is not used is correct, as search is a bit confusing and I'm not too familiar

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
the `FolderView` as implemented really needs to go away 😬

**Comment by ryantxu** [comment]
I changed the backport flags since this seems worth backporting to 9.1.x

**Review by ivanortegaalba — APPROVED** [review]

**Comment by torkelo** [comment]
@ryantxu what is wrong with the FolderView, is it just technical? I find it much better than table view as it has recent & starred, nice big cards that are easier to read, wish search had supported this view as well.

**Comment by torkelo** [comment]
> 1 request per expanded folder to request the dashboards in that folder

is this for the new search or old? 

that is strange, it used to be a single call, search api has support for a list of folderIds,

**Comment by JoaoSilvaGrafana** [comment]
> is this for the new search or old?

@torkelo From what I've seen it happens for both. They call different endpoints but both old and new have the same request structure now

**Pull request merged**
