### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by roelbeun**
**What is this feature?**

Added steps to enable Azure AD via Grafana Cloud

**Why do we need this feature?**

There does not seem to be existing documentation around how to do this. Only for on-prem. These steps may need to be added to the cloud docs as well. 

**Who is this feature for?**

Grafana cloud users

**Which issue(s) does this PR fix?**:

n/a

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Ruvetuve** [comment]
Thank you for looking into this @chri2547. The page where I made the change also states it's applicable for Grafana Cloud.

The link you provide does mention howto but not as specific, so maybe we can use my change for that.

I've also asked internally to change the link from the Grafana Cloud Portal > Azure AD to reflect the one you provided. 

Maybe on this page just a reference to the cloud doc around howto enable?

**Comment by chri2547** [comment]
@Ruvetuve , I'm still concerned that Cloud users won't see this content. I suggest opening a PR against the topic in the Cloud docs and adding it there. I'm afraid it'll remain buried in the OSS docs. What do you think of doing that? And then closing this PR? Would you be up for opening a Cloud docs PR for this and adding expanding the content in this section - https://grafana.com/docs/grafana-cloud/account-management/authentication-and-permissions/authorization/#enable-the-azure-client-on-your-grafana-instance

**Comment by Ruvetuve** [comment]
> @Ruvetuve , I'm still concerned that Cloud users won't see this content. I suggest opening a PR against the topic in the Cloud docs and adding it there. I'm afraid it'll remain buried in the OSS docs. What do you think of doing that? And then closing this PR? Would you be up for opening a Cloud docs PR for this and adding expanding the content in this section - https://grafana.com/docs/grafana-cloud/account-management/authentication-and-permissions/authorization/#enable-the-azure-client-on-your-grafana-instance

Will do good point! thanks for sticking with me on this. Until the next one!

**Comment by chri2547** [comment]
@Ruvetuve has agreed to make the updates in the cloud docs and to close this PR.

**Pull request closed without merging**
