### PR TITLE
Datasource Config: Remove feature toggle "dataSourcePageHeader"

### PR DESCRIPTION
**Pull request by ktw4071**
**What is this feature?**

Remove feature toggle - dataSourcePageHeader. 

**Why do we need this feature?**

This feature has been deployed to all hosted grafana instances. Removal of feature flag in the next release of minor grafana will be needed.

**Who is this feature for?**

Teams that are in charge of datasource config page and connection data source config page.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] ~If this is a pre-GA feature, it is behind a feature toggle.~
- [ ] ~The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.~

### CODE REVIEW

**Review by sasklacz — APPROVED** [review]
Looks ok to me but would still prefer someone who dealt with feature toggles to review this before merging

**Comment by mmandrus** [comment]
I can take a look today!

**Review by mmandrus — APPROVED** [review]
LGTM (on behalf of the operator experience team). Did you mean to add this to the 10.1.x milestone instead?

**Comment by sasklacz** [comment]
> > LGTM (on behalf of the operator experience team). Did you mean to add this to the 10.1.x milestone instead?
> 
> The feature toggle was added in [PR](https://github.com/grafana/grafana/pull/66999) with the milestone of `10.1.x`. This PR should remove feature toggle in the next minor release of `10.2.x`. Thanks.

So when do we merge it ?

**Comment by sasklacz** [comment]
Ping @ktw4071 , can this go live ?

**Comment by cletter7** [comment]
@ktw4071 Should we still merge this?

**Pull request closed without merging**
