### PR TITLE
Azure Monitor: Fix Application Insights API key field to allow input

### LINKED ISSUE #21737: Azure Monitor: Application Insights API Key Field Not Allowing Input
API Key field for Applications Insights section on Azure Monitor config not allowing input.

### PR DESCRIPTION
**Pull request by shavonn**
Fixes #21737

### CODE REVIEW

**Comment by marefr** [comment]
This feels like a quite important bug fix. Should probably be targeted for next 6.6 patch release?

**Review by sunker — COMMENTED** [review]
Don't have knowledge/background to test this and cannot really understand the impact of this change. Would be great to get a demo and some explanations after today's standup.

**Comment by shavonn** [comment]
> This feels like a quite important bug fix. Should probably be targeted for next 6.6 patch release?

@marefr Yes, it is and should be!

**Comment by marefr** [comment]
Thanks. Added it to 6.6.1

**Comment by srclosson** [comment]
Testing this has been a nightmare. There is something else going on in the latest version of grafana, and since this branched off of master, it would seem something pushed in the last couple of days causes saving the datasource to logout the grafana user.

Looking at these changes though, I cannot see why this would have any affect. Approving.

**Review by srclosson — APPROVED** [review]

**Pull request merged**
