### PR TITLE
Alerting: Propagate failures to delete dashboard alerts

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Currently we suppress failures to delete dashboard alerts during dashboard deletion. With this fix we propagate the errors.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
As discussed, better to return errors than logging them.

**Comment by aknuds1** [comment]
@papagian I edited the description to reflect the change to propagate errors :)

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Added this to beta2 milestone

**Pull request merged**
