### PR TITLE
DashboardList/AlertList: Fix for missing All folder value

### LINKED ISSUE #39454: Cannot select "All" in the Folder list
**What happened**:
In the Dashboard list visualization I was selecting different folders to test which ones I wanted to use. Then I realized I was unable to go back to the "All" default option.

**What you expected to happen**:
I expect to be able to select the "All" option and have it show me all folders.

**How to reproduce it (as minimally and precisely as possible)**:
- open a dashboard
- add a new panel
- choose the "Dashboard list" visualization
- enable the "Search" option
- notice that the default option selected in the "Folder" list is "All"
- click on the "Folder" list and the "All" option will be highlighted
- click on a different folder
- apply/save your changes to the dashboard
- edit the panel you just added
- notice that the "All" option is displayed as the selected value in the "Folder" list.
- click on the "Folder" list and notice that the folder you last selected is highlight still, as well as the "All" option
- click on the "All" option
- apply/save your changes to the dashboard
- notice that all of the folders are not showing in your panel, instead, the contents will still be those of the folder that you chose which is not "All"
- clear your cache, try a new browser, notice that all can never be selected again
- delete the panel and create a new one in order to get access to the "All" option again

**Environment**:
- Grafana versions tried: 8.1.2 and 8.2.0-beta1
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser: MacOS with Brave and Chrome
- Grafana plugins: only Core plugins

grafana-folder-list

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
I couldn't find yet another `hack` in the FolderPicker that would solve this issue so I took the time to create another one, yeah I know :( I called it `ReadOnlyFolderPicker` because you can't create new folders with this one. 

But you can add your own `extra folders` with the `extraFolders` property. Not super happy with the naming of that property, so please leave some feedback on that and on the rest. 

**Which issue(s) this PR fixes**:
Fixes #39454
Related #38102

**Special notes for your reviewer**:
I deliberately put this for 8.2.0 milestone because beta2 goes out tomorrow and not sure if we have time to review and merge it before that.

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
i don't love having a new component, but i don't think you do either and it's way more effort to create a new one, so i trust it's the right call 👍 

code looks good and it definitely fixes the original issue 🙌 

re: `extraFolders`, i think it's _ok_. also struggling to think of a better term. `additionalFolders`? `customFolders`? 🤷

**Comment by hugohaggmark** [comment]
> i don't love having a new component, but i don't think you do either and it's way more effort to create a new one, so i trust it's the right call 👍

I think we need to look into this further and actually solve #38102 but I didn't want to do this at this point

> code looks good and it definitely fixes the original issue 🙌

This is great news 🎉 

> re: `extraFolders`, i think it's _ok_. also struggling to think of a better term. `additionalFolders`? `customFolders`? 🤷

I was thinking about `additionalFolders`? `customFolders`? too but settled with `extraFolders`. My main challenge with all `additionalFolders` and  `extraFolders` is that it implies they are added to existing, which is true but they're added first. 🤷  Hard thing, naming things 😓

**Comment by hugohaggmark** [comment]
> > i don't love having a new component, but i don't think you do either and it's way more effort to create a new one, so i trust it's the right call 👍
> 
> I think we need to look into this further and actually solve #38102 but I didn't want to do this at this point before stable release.
> 
> > code looks good and it definitely fixes the original issue 🙌
> 
> This is great news 🎉
> 
> > re: `extraFolders`, i think it's _ok_. also struggling to think of a better term. `additionalFolders`? `customFolders`? 🤷
> 
> I was thinking about `additionalFolders`? `customFolders`? too but settled with `extraFolders`. My main challenge with all `additionalFolders` and `extraFolders` is that it implies they are added to existing, which is true but they're added first. 🤷 Hard thing, naming things 😓

**Comment by ashharrison90** [comment]
> I think we need to look into this further and actually solve #38102 but I didn't want to do this at this point before 8.2.0 stable.

makes sense. another candidate for gardening week? 🤔 

> I was thinking about `additionalFolders`? `customFolders`? too but settled with `extraFolders`. My main challenge with all `additionalFolders` and  `extraFolders` is that it implies they are added to existing, which is true but they're added first. 🤷  Hard thing, naming things 😓  

yup, i think they're all fairly similar so `extraFolders` is fine 👍

**Review by ashharrison90 — APPROVED** [review]
looks even better 👍  good catch on the edge case 🙌

**Pull request merged**
