### PR TITLE
Loki: Add structured metadata keys to autocomplete

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

This PR adds structured metadata keys to the autocomplete of Loki's code editor.

**Special notes for your reviewer:**

1. Use `lokiStructuredMetadata` feature flag.
2. Start Grafana & Loki.
3. You should start seeing the `nonIndexed` label being suggested in the autocomplete:
image

### CODE REVIEW

**Comment by matyax** [comment]
FYI there's an error in:

```
ERROR in ./public/app/plugins/datasource/loki/components/monaco-query-field/monaco-completion-provider/CompletionDataProvider.test.ts:81:77
```

**Comment by svennergr** [comment]
> FYI there's an error in:
> 
> ```
> ERROR in ./public/app/plugins/datasource/loki/components/monaco-query-field/monaco-completion-provider/CompletionDataProvider.test.ts:81:77
> ```

Thanks - fixed!

**Comment by matyax** [comment]
Do we have structured metadata in our devenvs? Should we add it?

**Review by matyax — APPROVED** [review]
Works perfectly 👌 
When we combine this with the log details filter it's going to be pretty cool.

**Comment by svennergr** [comment]
> Do we have structured metadata in our devenvs? Should we add it?

https://github.com/grafana/grafana/pull/78587

**Comment by msvechla** [comment]
should this also be working in the visual query builder? Because it looks like thats not the case

**Pull request merged**
