### PR TITLE
Search: Fix not being able to clear sort value

### LINKED ISSUE #60335: Search: query.sort now insists on "name_sort" instead of null when nothing is selected
a recent search refactor (maybe #57973) broke our double-super-secret fontend-only dashboard fuzzy search [1] which is gated not only behind the `panelTitleSearch` feature toggle [2] but _also_ `&do-frontend-query`. it previously expected `query.sort` to be `null` when no explicit sorting strategy was selected from the `ActionRow` dropdown. however, we're now getting "name_sort" when nothing is selected. this search strategy currently only sorts by Relevance [3], since alphabetical sorting yields poorer results.

there is a hack PR [4] that i don't want to merge, since i believe this new behavior is fundamentally incorrect.

[1] http://localhost:3000/?orgId=1&search=open&do-frontend-query
[2] https://github.com/grafana/grafana/blob/main/docs/sources/search/_index.md#search-dashboards-using-panel-title
[3] https://github.com/grafana/grafana/pull/56475
[4] https://github.com/grafana/grafana/pull/59450

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

 - Fix issue introduced in https://github.com/grafana/grafana/pull/62248 where you're unable to clear the selected sort value
 - Stop setting default sort value in SearchStateManager - individual searchers will set it instead
 - Don't show default sort mode in sort picker

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
mob 🔱

**Comment by leeoniya** [comment]
hmm, still hitting the original issue. only the third `console.log()` gets `name_sort` :thinking: 

http://localhost:3000/?orgId=1&search=open&do-frontend-query

https://github.com/grafana/grafana/blob/fcecf4d3cbcf1977560ea3d8ff91a169c1a72a9e/public/app/features/search/service/frontend.ts#L18-L21

image

**Comment by leeoniya** [comment]
`main` looks like this:

image

**Comment by ashharrison90** [comment]
@leeoniya thanks for spotting, we'd missed a place where we needed to clear the sort state from `localStorage` when clearing it in the UI 🤦 

should be fixed now if you can take a look again 👀 

same for @grafana/user-essentials (particularly @joshhunt i guess), can we make sure we're happy with the latest commit?

**Review by joshhunt — COMMENTED** [review]
image

✅  Approved

**Comment by leeoniya** [comment]
sorry, still broken for me as before (no change with last commit). not sure how onSortChange tweaking would affect this. i'm not touching the sort field at all. i just open an Incognito tab to this page: http://localhost:3000/?orgId=1&search=open&do-frontend-query

**Comment by ashharrison90** [comment]
@leeoniya think that's because your frontend searcher `getFolderViewSort` method falls back to using bluge's `getFolderViewSort` method (https://github.com/grafana/grafana/blob/ue-search/public/app/features/search/service/frontend.ts#L80) which returns `name_sort`. if you try it in list view, or start typing a query, it should be `undefined`.

**Comment by leeoniya** [comment]
ah, i missed this landing in https://github.com/grafana/grafana/pull/57078

**Review by leeoniya — APPROVED** [review]
:shipit:

**Comment by leeoniya** [comment]
i removed "Fixes #60335" from this issue, to keep that open until the `getFolderViewSort` thing gets sorted (pardon the pun) :D

**Comment by ashharrison90** [comment]
@leeoniya is that something you/artur are gonna fix? basically, can we move the ticket somewhere so it's not on our board anymore? 😄 

_must... kill... tickets..._

**Comment by leeoniya** [comment]
> _must... kill... tickets..._

lol. yeah just assign it to me and you can take it off your board.

**Pull request merged**
