### PR TITLE
Chore: Add tracing to tempo, parca and pyroscope datasource backends

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

Adds tracing to Pyroscope, Parca and Tempo datasource backends.

**Why do we need this feature?**

Improve instrumentation of datasource backends.

**Who is this feature for?**

Grafana developers and maintainers. 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by joey-grafana** [comment]
Just fyi you can run `./bin/parca` and connect on localhost:7070 once you checkout the [parca repo](https://github.com/parca-dev/parca). Will also take a look in review :)

**Review by joey-grafana — APPROVED** [review]
Looks great (Tempo, Pyroscope) 👍 

Not tested Parca, as mentioned in Slack.

We're tracing lots here which is great. There may be other bits of info, like tags/profile type/id etc that would be valuable to trace in a supplementary PR. This is certainly enough for now/this PR :) 

This may be unrelated to the PR, but there seems to be an empty value in the dropdown. Even though there are only 4 values returned.

Screenshot 2023-10-12 at 14 10 33

After a couple of queries that builds up!

Screenshot 2023-10-12 at 14 13 55

**Review by marefr — COMMENTED** [review]
Please use the SDK tracer rather than the Grafana one. We're trying to remove grafana dependencies within core plugins. See https://github.com/grafana/grafana/pull/75927 as example

**Review by xnyo — APPROVED** [review]
LGTM! Great work!

**Pull request merged**
