### PR TITLE
Chore: Release 7.1.2

### PR DESCRIPTION
**Pull request by hugohaggmark**
**This PR resulted in an empty commit so I skipped it** Tab: Make active tab clickable and add hyperlink functionality, (#25546), merge-sha: 615b000acd0ae301a159e24bdc6e32f870aaf974  

--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Tab: Make active tab clickable and add hyperlink functionality, (#25546), merge-sha: 615b000acd0ae301a159e24bdc6e32f870aaf974
  * Explore: Don't run queries on datasource change, (#26033), merge-sha: 081f954a2b538edd6af56d42dba1b580f71a191e
  * Grafana-UI: Add time range input, (#26158), merge-sha: 718d6fb25d61d73614e48982c01a7c0a52c42bd8
  * Grafana-UI: Enable empty time range, (#26320), merge-sha: 7b183971fdf416d4e0144f107f55df93590cfaeb
  * Grafana-UI: Pass timeZone to TimePickerButtonLabel in TimeRangeInput, (#26454), merge-sha: 9c3f47aa239c5ce7038dd3176f209011ba0936cb
  * TimePicker: Fix position and responsive behavior, (#26570), merge-sha: 93a4b8e8e40d2711279341f8bef85920d0c5efc3
  * Units: Remove duplicate SI prefix from mSv and µSv, (#26598), merge-sha: 9d68a1fa62c86d38e15c42f12ec99a086a3dcc57
  * TextPanel: Fix content overflowing panel boundaries , (#26612), merge-sha: ae3c2853121801434d6eb6bb3e349e83d416fc8d
  * QueryOptions: Fix not being able to change cache timeout setting, (#26614), merge-sha: cc0a8464ff1ab1427ba21da5558a3ab3dc5fddf8
  * Dashbard: Fix refresh interval settings to allow setting it to equal min_refresh_interval, (#26615), merge-sha: e3ea725387c916845fc8b37092f5da4e6365cfc4
  * TemplateSrv: Formatting options for ${__from} and ${__to}, unix seconds epoch, ISO 8601/RFC 3339 , (#26466), merge-sha: 6c49fdb57d4962bf4e877bdaa04004cea4ba40ce
  * StatPanel: Fix stat panel display name not showing when explicitly set, (#26616), merge-sha: cbe1d7b08c8d1a9338e86df7efe56f0b139b29fa
  * Toolkit/Plugin: throw an Error instead of a string, (#26618), merge-sha: bdbea6d1f233bdf8d56fb1b7f8136fe85fe9bce8
  * Templating: Fixed access to system variables like __dashboard, __user & __org during dashboard load & variable queries, (#26637), merge-sha: 34c2f440dbd701e31faa0949ddfc8921a8c6f460
  * Grafana-UI: Reverse TimeRangeInput range pickers, (#26652), merge-sha: 0b8ad9176d594be335433e5e991d838ee788e759
  * Dashboard: Fixed disable draggable panels on correct breakpoint, (#26636), merge-sha: ef223d4143440d5d19838dcbe9fa4fe13d7f3234
  * TextPanel: Remove semicolon in markup, (#26680), merge-sha: 3075b718483aa6fd6d32f1679ecea0ed4fb3e06b
  * Inspect: Fix link to error tab from panel header, (#26682), merge-sha: eb0b9de04436d717ad899cd29c962c2774b788ff
  * LDAP: users without org mappings are marked as disabled, (#26650), merge-sha: c266f45858fea971c2feaf658224822184133edf
  * Flux: Ensure connections to InfluxDB are closed, (#26735), merge-sha: ec756f3729758ddb4cf92fde9a69ff6ced18b690
  * Cloud monitoring: do not create deep link if there are no timeseries, (#26737), merge-sha: 41f7bccb249e51eeccec3f069bbea78048540258
  * TimePicker: Fixes app crash when changing custom range to nothing, (#26775), merge-sha: 353b3822c1169334bd7bec46738fa62919438b71
  * Query history: Fix search filtering if null value, (#26768), merge-sha: 6a86e66d76f27f567921a221b0c976f7b016d4e5
  * Test datasource: fix query editor html partial, (#26788), merge-sha: 9e5fe8dbdbbcdd0b16405f9389fd505b6433d6db
  * Fields: __field.name as field name and __field.displayName as displayName, (#26531), merge-sha: ec783fbff47b78991e9488583375c114df082786
  * Explore: Run queries on Metrics to Logs transition, (#26704), merge-sha: 744e108b0481b51b0e5f95a1a14a78b2d46ae481
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x 615b000acd0ae301a159e24bdc6e32f870aaf974
  git cherry-pick -x 081f954a2b538edd6af56d42dba1b580f71a191e
  git cherry-pick -x 718d6fb25d61d73614e48982c01a7c0a52c42bd8
  git cherry-pick -x 7b183971fdf416d4e0144f107f55df93590cfaeb
  git cherry-pick -x 9c3f47aa239c5ce7038dd3176f209011ba0936cb
  git cherry-pick -x 93a4b8e8e40d2711279341f8bef85920d0c5efc3
  git cherry-pick -x 9d68a1fa62c86d38e15c42f12ec99a086a3dcc57
  git cherry-pick -x ae3c2853121801434d6eb6bb3e349e83d416fc8d
  git cherry-pick -x cc0a8464ff1ab1427ba21da5558a3ab3dc5fddf8
  git cherry-pick -x e3ea725387c916845fc8b37092f5da4e6365cfc4
  git cherry-pick -x 6c49fdb57d4962bf4e877bdaa04004cea4ba40ce
  git cherry-pick -x cbe1d7b08c8d1a9338e86df7efe56f0b139b29fa
  git cherry-pick -x bdbea6d1f233bdf8d56fb1b7f8136fe85fe9bce8
  git cherry-pick -x 34c2f440dbd701e31faa0949ddfc8921a8c6f460
  git cherry-pick -x 0b8ad9176d594be335433e5e991d838ee788e759
  git cherry-pick -x ef223d4143440d5d19838dcbe9fa4fe13d7f3234
  git cherry-pick -x 3075b718483aa6fd6d32f1679ecea0ed4fb3e06b
  git cherry-pick -x eb0b9de04436d717ad899cd29c962c2774b788ff
  git cherry-pick -x c266f45858fea971c2feaf658224822184133edf
  git cherry-pick -x ec756f3729758ddb4cf92fde9a69ff6ced18b690
  git cherry-pick -x 41f7bccb249e51eeccec3f069bbea78048540258
  git cherry-pick -x 353b3822c1169334bd7bec46738fa62919438b71
  git cherry-pick -x 6a86e66d76f27f567921a221b0c976f7b016d4e5
  git cherry-pick -x 9e5fe8dbdbbcdd0b16405f9389fd505b6433d6db
  git cherry-pick -x ec783fbff47b78991e9488583375c114df082786
  git cherry-pick -x 744e108b0481b51b0e5f95a1a14a78b2d46ae481

**Added**
* Templating: Restore lost TemplateSrv test file, (#26453), merge-sha: fba329f3acaba5d2b7db327e1fd31531887ae880

git cherry-pick -x fba329f3acaba5d2b7db327e1fd31531887ae880

### CODE REVIEW

**Review by aknuds1 — COMMENTED** [review]
Why is https://github.com/grafana/grafana/pull/25546 not cherry-picked?

**Review by aknuds1 — COMMENTED** [review]
Sorry, my reviews get submitted twice for some reason :/

**Comment by hugohaggmark** [comment]
> Why is #25546 not cherry-picked?

haha just added it first in the PR comment, it resulted in an empty commit so I skipped it. Must have already been merged?

**Comment by aknuds1** [comment]
> > Why is #25546 not cherry-picked?
> 
> haha just added it first in the PR comment, it resulted in an empty commit so I skipped it. Must have already been merged?

Aha I see, we might want to remove the "cherry-pick needed" label from it then.

**Comment by hugohaggmark** [comment]
> > > Why is #25546 not cherry-picked?
> > 
> > 
> > haha just added it first in the PR comment, it resulted in an empty commit so I skipped it. Must have already been merged?
> 
> Aha I see, we might want to remove the "cherry-pick needed" label from it then.

Thank you for reminding me but I think the tool for closing the milestone does that :)

**Comment by aknuds1** [comment]
I see you added the 7.1.2 milestone and the "cherry-pick needed" label to that PR today, why was that needed?

**Review by aknuds1 — APPROVED** [review]

**Comment by papagian** [comment]
> > > Why is #25546 not cherry-picked?
> > 
> > 
> > haha just added it first in the PR comment, it resulted in an empty commit so I skipped it. Must have already been merged?
> 
> Aha I see, we might want to remove the "cherry-pick needed" label from it then.

Actually, the milestone is incorrect. It should be `7.1.0-beta1` (same as the linked issue) but I don't think is possible to change it since it's a closed one.
``` git log v7.1.0-beta1|grep "Tab: Make active tab clickable and add hyperlink functionality"
    Tab: Make active tab clickable and add hyperlink functionality (#25546)`
```

**Comment by aknuds1** [comment]
Front-end tests fail.

**Review by papagian — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Thanks for clearing that up @papagian. Since it has the add to changelog label, should we add it for 7.1.0-beta1 in the changelog?

**Review by Clarity-89 — APPROVED** [review]

**Comment by papagian** [comment]
The `test-frontend` fails though

> Thanks for clearing that up @papagian. Since it has the add to changelog label, should we add it for 7.1.0-beta1 in the changelog?

good point; yes this should be done manually
I will remove it also from `7.1.2` milestone otherwise the `changelog` script will pick it.

**Comment by hugohaggmark** [comment]
> The `test-frontend` fails though
> 
> > Thanks for clearing that up @papagian. Since it has the add to changelog label, should we add it for 7.1.0-beta1 in the changelog?
> 
> good point; yes this should be done manually
> I will remove it also from `7.1.2` milestone otherwise the `changelog` script will pick it.

thanks for helping out @papagian and @aknuds1 

I'm looking into the failing tests, seems we're missing this PR in the cherrypicks https://github.com/grafana/grafana/pull/26453

**Pull request merged**
