### PR TITLE
Add Fredrik Enestad as member

### PR DESCRIPTION
**Pull request by fredr**

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]
LGTM! 🚀🎉

**Comment by daniellee** [comment]
@fredr welcome to the team! Do you want to merge the PR yourself? You should have permision to now.

**Comment by fredr** [comment]
> welcome to the team! 

Thank you! 

> Do you want to merge the PR yourself? You should have permision to now.

I'm not able to merge because of the restrictions on master

Screenshot from 2020-10-01 17-19-57

**Comment by ivanahuckova** [comment]
@daniellee do you know why @fredr can't merge the PR?

**Comment by daniellee** [comment]
@fredr can you try again? I had to add you to the list of people who have access to the master branch (a protected branch).

**Comment by fredr** [comment]
@daniellee cheers, now it works! 🙏🍾🥂

**Pull request merged**
