### PR TITLE
Chore: Resolved circular dependency warnings in grafana/ui

### PR DESCRIPTION
**Pull request by mckn**
**What is this feature?**

Seems like we have a bad habit of importing modules from the entry point which most likely will result in circular dependencies.

**Why do we need this feature?**

It removes some of the circular dependencies which will slow down the build and potentially make tests fail. 
I have fixed all the "simple" ones which basically is because we are importing from index-files. The rest needs a bit of a refactoring and needs to be handled in separate PRs.

Before:

```bash
npx dpdm --no-warning --no-tree ./src/index.ts 
✔ [432/432] Analyze done!
• Circular Dependencies
  01) src/themes/index.ts -> src/themes/GlobalStyles/GlobalStyles.tsx
  02) src/types/index.ts -> src/types/completion.ts -> src/utils/index.ts -> src/utils/dataLinks.ts -> src/components/Menu/MenuItem.tsx
  03) src/components/Menu/MenuItem.tsx -> src/components/Menu/SubMenu.tsx
  04) src/types/index.ts -> src/types/completion.ts -> src/utils/index.ts -> src/utils/searchFunctions.ts
  05) src/types/index.ts -> src/types/completion.ts -> src/utils/index.ts -> src/utils/searchFunctions.ts -> src/utils/fuzzy.ts
  06) src/components/index.ts -> src/components/Forms/Legacy/Switch/Switch.tsx
  07) src/index.ts -> src/components/index.ts -> src/components/TabbedContainer/TabbedContainer.tsx
  08) src/components/Cascader/Cascader.tsx -> src/components/Cascader/optionMappings.ts
  09) src/components/ColorPicker/ColorPickerPopover.tsx -> src/components/ColorPicker/SpectrumPalette.tsx -> src/components/ColorPicker/ColorInput.tsx
  10) src/components/index.ts -> src/components/DateTimePickers/TimeRangePicker.tsx -> src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx
  11) src/components/index.ts -> src/components/DateTimePickers/TimeRangePicker.tsx -> src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx -> src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx
  12) src/components/index.ts -> src/components/DateTimePickers/TimeRangePicker.tsx -> src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx -> src/components/DateTimePickers/TimeRangePicker/TimeRangeContent.tsx
  13) src/index.ts -> src/components/index.ts -> src/components/DateTimePickers/TimeRangePicker.tsx -> src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx -> src/components/DateTimePickers/TimeRangePicker/TimeRangeContent.tsx
  14) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarBody.tsx
  15) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarFooter.tsx
  16) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarHeader.tsx
  17) src/index.ts -> src/components/index.ts -> src/components/DateTimePickers/TimeOfDayPicker.tsx
  18) src/components/index.ts -> src/components/DateTimePickers/DateTimePicker/DateTimePicker.tsx
  19) src/components/index.ts -> src/components/ConfirmModal/ConfirmModal.tsx
  20) src/index.ts -> src/components/index.ts -> src/components/QueryField/QueryField.tsx
  21) src/components/index.ts -> src/components/Monaco/CodeEditor.tsx -> src/components/Monaco/ReactMonacoEditorLazy.tsx
  22) src/components/index.ts -> src/components/PageLayout/PageToolbar.tsx
  23) src/components/Table/Table.tsx -> src/components/Table/ExpandedRow.tsx
  24) src/components/Table/utils.ts -> src/components/Table/BarGaugeCell.tsx
  25) src/components/Table/utils.ts -> src/components/Table/DefaultCell.tsx -> src/components/Table/CellActions.tsx
  26) src/components/Table/utils.ts -> src/components/Table/DefaultCell.tsx
  27) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts
  28) src/components/PanelChrome/PanelContext.ts -> src/components/PanelChrome/index.ts
  29) src/components/uPlot/Plot.tsx -> src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  30) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx -> src/components/uPlot/config/UPlotAxisBuilder.ts
  31) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx -> src/components/uPlot/config/UPlotAxisBuilder.ts -> src/components/uPlot/config/UPlotScaleBuilder.ts
  32) src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  33) src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  34) src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  35) src/components/GraphNG/utils.ts -> src/components/GraphNG/nullInsertThreshold.ts
  36) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/config/UPlotSeriesBuilder.ts
  37) src/components/Table/utils.ts -> src/components/Table/SparklineCell.tsx
  38) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx
  39) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx -> src/components/Table/FilterPopup.tsx
  40) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx -> src/components/Table/FilterPopup.tsx -> src/components/Table/FilterList.tsx
  41) src/components/BigValue/BigValue.tsx -> src/components/BigValue/BigValueLayout.tsx
  42) src/components/index.ts -> src/components/Graph/GraphWithLegend.tsx -> src/components/VizLegend/VizLegend.tsx -> src/components/VizLegend/utils.ts
  43) src/components/Text/Text.tsx -> src/components/Text/utils.ts
  44) src/components/index.ts -> src/components/Collapse/CollapsableSection.tsx
  45) src/index.ts -> src/components/index.ts -> src/components/DataLinks/DataLinksInlineEditor/DataLinksInlineEditor.tsx -> src/components/DataLinks/DataLinksInlineEditor/DataLinkEditorModalContent.tsx -> src/components/DataLinks/DataLinkEditor.tsx -> src/components/DataLinks/DataLinkInput.tsx
  46) src/components/index.ts -> src/components/DataLinks/DataLinksInlineEditor/DataLinksInlineEditor.tsx -> src/components/DataLinks/DataLinksInlineEditor/DataLinkEditorModalContent.tsx -> src/components/DataLinks/DataLinkEditor.tsx -> src/components/DataLinks/DataLinkInput.tsx
  47) src/components/index.ts -> src/components/DataLinks/DataLinksInlineEditor/DataLinksInlineEditor.tsx -> src/components/DataLinks/DataLinksInlineEditor/DataLinkEditorModalContent.tsx -> src/components/DataLinks/DataLinkEditor.tsx -> src/components/DataLinks/DataLinkInput.tsx -> src/components/DataLinks/DataLinkSuggestions.tsx
  48) src/components/ErrorBoundary/ErrorBoundary.tsx -> src/components/ErrorBoundary/ErrorWithStack.tsx
  49) src/index.ts -> src/components/index.ts -> src/components/DataSourceSettings/DataSourceHttpSettings.tsx -> src/components/DataSourceSettings/BasicAuthSettings.tsx
  50) src/components/Segment/index.ts -> src/components/Segment/Segment.tsx
  51) src/components/Segment/index.ts -> src/components/Segment/SegmentAsync.tsx
  52) src/components/Segment/index.ts -> src/components/Segment/SegmentInput.tsx
  53) src/components/index.ts -> src/components/FileUpload/FileUpload.tsx
  54) src/components/FileDropzone/FileDropzone.tsx -> src/components/FileDropzone/FileListItem.tsx
  55) src/index.ts -> src/options/index.ts -> src/options/builder/index.ts -> src/options/builder/axis.tsx
  56) src/index.ts -> src/options/index.ts -> src/options/builder/index.ts -> src/options/builder/hideSeries.tsx
  57) src/index.ts -> src/options/index.ts -> src/options/builder/index.ts -> src/options/builder/stacking.tsx
```

After:

```bash
❯ npx dpdm --no-warning --no-tree ./src/index.ts 
✔ [433/433] Analyze done!
• Circular Dependencies
  01) src/components/Menu/MenuItem.tsx -> src/components/Menu/SubMenu.tsx
  02) src/types/index.ts -> src/types/completion.ts -> src/utils/index.ts -> src/utils/searchFunctions.ts
  03) src/types/index.ts -> src/types/completion.ts -> src/utils/index.ts -> src/utils/searchFunctions.ts -> src/utils/fuzzy.ts
  04) src/components/Cascader/Cascader.tsx -> src/components/Cascader/optionMappings.ts
  05) src/components/ColorPicker/ColorPickerPopover.tsx -> src/components/ColorPicker/SpectrumPalette.tsx -> src/components/ColorPicker/ColorInput.tsx
  06) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarBody.tsx
  07) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarFooter.tsx
  08) src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx -> src/components/DateTimePickers/TimeRangePicker/CalendarHeader.tsx
  09) src/components/Text/Text.tsx -> src/components/Text/utils.ts
  10) src/components/ErrorBoundary/ErrorWithStack.tsx -> src/components/ErrorBoundary/ErrorBoundary.tsx
  11) src/components/Table/Table.tsx -> src/components/Table/ExpandedRow.tsx
  12) src/components/Table/utils.ts -> src/components/Table/BarGaugeCell.tsx
  13) src/components/Table/utils.ts -> src/components/Table/DefaultCell.tsx -> src/components/Table/CellActions.tsx
  14) src/components/Table/utils.ts -> src/components/Table/DefaultCell.tsx
  15) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts
  16) src/components/uPlot/Plot.tsx -> src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  17) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx -> src/components/uPlot/config/UPlotAxisBuilder.ts
  18) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx -> src/components/uPlot/config/UPlotAxisBuilder.ts -> src/components/uPlot/config/UPlotScaleBuilder.ts
  19) src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  20) src/components/uPlot/utils.ts -> src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  21) src/components/GraphNG/utils.ts -> src/components/GraphNG/GraphNG.tsx
  22) src/components/GraphNG/utils.ts -> src/components/GraphNG/nullInsertThreshold.ts
  23) src/components/uPlot/types.ts -> src/components/uPlot/config/UPlotConfigBuilder.ts -> src/components/uPlot/config/UPlotSeriesBuilder.ts
  24) src/components/Table/utils.ts -> src/components/Table/SparklineCell.tsx
  25) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx
  26) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx -> src/components/Table/FilterPopup.tsx
  27) src/components/index.ts -> src/components/Table/Table.tsx -> src/components/Table/HeaderRow.tsx -> src/components/Table/Filter.tsx -> src/components/Table/FilterPopup.tsx -> src/components/Table/FilterList.tsx
  28) src/components/BigValue/BigValue.tsx -> src/components/BigValue/BigValueLayout.tsx
  29) src/components/FileDropzone/FileDropzone.tsx -> src/components/FileDropzone/FileListItem.tsx
```

**Who is this feature for?**

Grafana developers

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**
I did look into adding an eslint rule to detect if we have any circular dependencies available but it has a pretty big performance impact so I'm not sure we want to enable that.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by oscarkilhed — APPROVED** [review]
Looks good! Took the liberty to merge main into this as I was testing, might have messed up the .betterer.results

Would have been helpful to have the sub tables refactoring in a different PR :)

**Comment by jackw** [comment]
>Would have been helpful to have the sub tables refactoring in a different PR :)

I think it might be a good idea to move the table refactoring to a different PR if we want to solve its circular dependencies.

**Comment by mckn** [comment]
> Looks good! Took the liberty to merge main into this as I was testing, might have messed up the .betterer.results
> 
> Would have been helpful to have the sub tables refactoring in a different PR :)

Yeah, I agree. I will update this PR and move table things into its own. Thanks for the feedback!

**Review by oscarkilhed — APPROVED** [review]
Nice! Assign me to review the table refactoring when it's done :)

**Pull request merged**
