### PR TITLE
WIP: Reuse panels across dashboards

### PR DESCRIPTION
**Pull request by mtanda**
I have so many composite graph for performance monitoring.
I want to reuse the panel setting.
https://github.com/grafana/grafana/issues/1803

This PR will fix the issue.

@torkelo How do you think about this approach?

### CODE REVIEW

**Comment by akrus** [comment]
Any progress here?

**Comment by mtanda** [comment]
nothing from me..

**Comment by bergquist** [comment]
I think reusable panels should be a different entity rather then symlinking to other dashboards. But I'm not sure.

**Comment by mtanda** [comment]
@bergquist 
Honestly, I don't need to reuse panel itself. I want to reuse panel definition (e.g. query expression, style, etc...)
So, I want the feature like "templated panel".
I want to define "templated panel" and embed the panel to several dashboard.

"Copy and paste panels" doesn't fit my use case.
If same panel is copied to several dashboard, and if want to update all panel definition, it is very hard.

I tried to reuse the panel definitions by defining panel in file based dashboard, the panel definition contains template variables, and load the panel definition by panel id.

The good point of loading panel directly is, user can edit the definition by the same panel editor, and check the result quickly.
The bad point is, we should handle "refereed panel is missing" error.

Maybe https://github.com/grafana/grafana/issues/4940 is similar feature what I want.
And I think the feature takes better approach, if the feature support updating all panel definitions when updating original one.

**Comment by mtanda** [comment]
After the read issue again, I notice I misunderstand what the feature is.
But, I think save panel definition to template is good idea, so I agree with the point "should be a different entity rather then symlinking to other dashboards".

**Comment by mtanda** [comment]
This approach is not good. So close this. (If I have a time, try to make PR by another approach.)

**Pull request closed without merging**
