### PR TITLE
CloudWatch: Clean up code

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Clean up CloudWatch code, in order to improve readability and to prepare for future work.

No functionality is changed, the PR is only for cleaning up code.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
LGTM

**Review by marefr — APPROVED** [review]
LGTM

**Review by papagian — APPROVED** [review]
LGTM

I include a list of the several renames to keep track of:
`CloudWatchExecutor` -> `cloudWatchExecutor`
`DatasourceInfo` -> `datasourceInfo`
`CustomMetricsCache` -> `customMetricsCache`
`getClient` -> `getCWClient`
`getLogsClient` -> `getCWLogsClient`
`retrieveDsInfo`  -> `getDSInfo`
`cache` -> `envelope`
`awsCredentialCache` -> `awsCredsCache`
`credentialCacheLock` -> `credsCacheLock`

**Comment by aknuds1** [comment]
Thanks @papagian. The renaming from PascalCase to camelCase is to avoid exporting more symbols than necessary. The renaming of `getClient` etc is in anticipation of future harmonization of the client logic (as per patstrom's PR). The renaming from `cache` to `envelope` is that this type is not a cache, but a cache "envelope", which gets stored in the cache.

**Pull request merged**
