### PR TITLE
Changelog: Updated changelog for 10.0.0-preview

### PR DESCRIPTION
**Pull request by grafanabot**

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
needs `yarn prettier:write`, otherwise LGTM!

(@torkelo)

**Comment by torkelo** [comment]
@dsotirakis is there a bug in the changelog github action? yarn prettier:write should happen on commit right?

**Comment by dsotirakis** [comment]
> @dsotirakis is there a bug in the changelog github action? yarn prettier:write should happen on commit right?

Maybe? I am not sure, I haven't touched this part for a long time now :( We'll revisit.

**Comment by zerok** [comment]
> @dsotirakis is there a bug in the changelog github action? yarn prettier:write should happen on commit right?

Yes, it's a known issue and on our list 🙂

https://github.com/grafana/grafana-github-actions-go/issues/42

**Pull request merged**
