### PR TITLE
Alerting: Add support for `keep_firing_for` field from external rulers

### LINKED ISSUE #75029: Alerting: Update ruler proxy to support `keep_firing_for` alert rule field
This was added to the Prometheus ruler in [this commit](https://github.com/prometheus/prometheus/commit/ce55e5074d05f570ddc619619e877e011dc270e2) and Mimir ruler was updated to support the new field in [this commit](https://github.com/grafana/mimir/commit/5ac2d2686b3a3e6b5c87c985cca5ace6970b2197).

We need to update [`ApiRuleNode`](https://github.com/grafana/grafana/blob/0815d7f6275eb7b9266c8907ebddf770b12a65c4/pkg/services/ngalert/api/tooling/definitions/cortex-ruler.go#L260) to include this field, though ideally we would support setting this in the UI as well.

---

This can be tested with the following rule group:

```yaml
test-group:
  - name: alerts
    rules:
      - alert: AlwaysFiring
        expr: count(up) >= 0
        keep_firing_for: 1m
```

### PR DESCRIPTION
**Pull request by rwwiv**
**What is this feature?**

This PR adds backend support for the alert rule field `keep_firing_for` coming from external rulers.

**Why do we need this feature?**

This fixes a bug where this field being present in an alert rule definition causes a yaml unmarshal error on the backend, which is passed to the frontend on the "Alert rules" page.

**Who is this feature for?**

Users who are managing external Alertmanagers through Grafana and wish to make use of this new field.

**Which issue(s) does this PR fix?**:

Fixes #75029

**Special notes for your reviewer:**

See the linked issue for a minimal reproducible example.

---

Please check that:
- [x] It works as expected from a user's perspective.

### CODE REVIEW

**Review by VikaCep — APPROVED** [review]
LGTM! 👏 👏 👏

**Comment by grobinson-grafana** [comment]
Should I be able to see this field in the UI when both creating and editing rules? I can't see it in either.

**Comment by gillesdemey** [comment]
@grobinson-grafana nope this PR simply preserves the field if it's set, there's no UI for it yet because we don't know if Prometheus, Mimir and Cortex are forwards compatible (ie. They might reject the API request if the field is sent but not recognized)

**Review by grobinson-grafana — APPROVED** [review]
LGTM! Tested the API changes, including updating an existing rule that has KeepFiringFor.

**Pull request merged**
