### PR TITLE
build: update scripts go.(mod|sum)

### PR DESCRIPTION
**Pull request by kylebrandt**
Can use tag of golangci-lint now instead of hash

### CODE REVIEW

**Review by marefr — APPROVED** [review]
May want to lock gosec to https://github.com/securego/gosec/releases/tag/v2.1.0 but lets start with this and see how it turns out :+1:

**Review by aknuds1 — APPROVED** [review]
Looks good as far as I can tell.

**Comment by kylebrandt** [comment]
Can't seem to tag gosec because it doesn't have v2 in the module name (https://github.com/securego/gosec/issues/404).

That being said I think maybe this is all just wrong... importing the tools to then build them. Will discuss with @aknuds1 since he is looking at the build. Seems more sane to just install the tools in a docker container and run and the checks instead of our underscore imports.

**Comment by marefr** [comment]
I agree that this feels wrong and something we should look into solving. But merged this now to remove some current headaches around go.mod/sum files updating when running `make run`.

**Pull request merged**
