### PR TITLE
Build: bundle file name will be generated based on bundle content hash.

### LINKED ISSUE #24063: v7.0.0-beta1: Graph x-axis labels showing "MM/DD" rather than actual date
**What happened**:
Upgraded Grafana from version 6.7.3 to 7.0.0-beta1. The x-axes on our graph panels began displaying "MM/DD" rather than the actual date. After downgrading to 6.7.3, dates are back to normal. Please see screenshot from v7.0.0-beta1:
Screen Shot 2020-04-29 at 1 58 59 PM

**What you expected to happen**:
Month and day to appear on x-axis, e.g. "04/29"

**Environment**:
- Grafana version: 6.7.3 upgraded to 7.0.0-beta1
- Data source type & version: Postgres
- OS Grafana is installed on: Alpine (Docker)
- User OS & Browser: Mac OS, Chrome

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
This makes sure that we only change the bundle file name when the content of the file is changed. This will enable users to cache bundles between versions only if the content isn't changed.

**Which issue(s) this PR fixes**:
Fixes #24063

### CODE REVIEW

**Comment by hugohaggmark** [comment]
Maybe add to changelog label too, @mckn?

**Review by hugohaggmark — COMMENTED** [review]
Looks good, but I'm not an Webpack expert so maybe @dprokop can approve?

**Review by dprokop — APPROVED** [review]
Good overview of hashes: https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208

Btw I'm not sure this fixes the issue you have referenced. `hash` should be change if ANY file in the build changes, so any grafana build that touches front-end resources should invalidate the hash.

**Comment by dprokop** [comment]
As a side note we should drop hashes in dev env, this should speed things up a bit.

**Comment by mckn** [comment]
> Good overview of hashes: https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208
> 
> Btw I'm not sure this fixes the issue you have referenced. `hash` should be change if ANY file in the build changes, so any grafana build that touches front-end resources should invalidate the hash.

hmm, yeah - so it is the hash of the build. Weird, then it might not be this that is the cause of the issue.

**Comment by mckn** [comment]
> Good overview of hashes: https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208
> 
> Btw I'm not sure this fixes the issue you have referenced. `hash` should be change if ANY file in the build changes, so any grafana build that touches front-end resources should invalidate the hash.

Just found this one on play: https://play.grafana.org/d/000000097/influxdb-default-fill-value?orgId=1

So it is some other reason behind it. Will see if I can reproduce it locally with influxdb.

**Comment by mckn** [comment]
> > Good overview of hashes: https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208
> > Btw I'm not sure this fixes the issue you have referenced. `hash` should be change if ANY file in the build changes, so any grafana build that touches front-end resources should invalidate the hash.
> 
> Just found this one on play: https://play.grafana.org/d/000000097/influxdb-default-fill-value?orgId=1
> 
> So it is some other reason behind it. Will see if I can reproduce it locally with influxdb.

So I was totally wrong 🙈

**Comment by dprokop** [comment]
@mckn 🙈

**Comment by mckn** [comment]
> @mckn 🙈

hmm, but I can't reproduce it locally :P

**Comment by mckn** [comment]
> @mckn 🙈

and it will go away in play if I do a force refresh. So I was probably right 🙈

**Comment by mckn** [comment]
> @mckn 🙈



> @mckn 🙈

I wil stop spamming you here :)

**Comment by hugohaggmark** [comment]
yeah, I couldn't repro this issue the first time I visited play:
image

**Pull request closed without merging**
