### PR TITLE
Chore: Adjust unit tests so they work with react 18

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- many unit tests fail when attempting to update to react 18 (see https://github.com/grafana/grafana/pull/64428)
- adjusts unit tests so they work with react 18
  - this tackles maybe half of the failing tests
  - a lot of these are moving from `fireEvent` to `userEvent`

**Why do we need this feature?**

- so we can move to react 18!

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ifrost — APPROVED** [review]
Explore LGTM 👍

**Review by aangelisc — APPROVED** [review]
Approved for Azure 😊

**Review by kevinwcyu — APPROVED** [review]
LGTM for cloudwatch

**Review by matyax — COMMENTED** [review]
Loki part looks good! 👍

**Pull request merged**
