### PR TITLE
Fix: do not allow changing variable when fullscreen with repeated panel

### LINKED ISSUE #21455: Graph in View repeat Panel disappear after change dashboard variables
**What happened**:
when view repeated panel, changing variable will make graph disappeared

**What you expected to happen**:
all repeated panel view as first repeat panel

**How to reproduce it (as minimally and precisely as possible)**:
there is a dashboard which has a repeat panel graph,
image
after entering view mode of a repeated panel which should not be edited
image
everything is ok.
but after change variables, graph disappeared.
image

but everything is ok when changing variables in first repeat panel which should be edit

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by okhowang**
**What this PR does / why we need it**:

we can disable variable changing currently.
by just do nothing when click on variables.

**Which issue(s) this PR fixes**:

Fixes #21455

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
This needs to be more subtle as only variables that are linked to the repeat variable should be locked.

**Comment by okhowang** [comment]
changing variables which panel don't depend on
will also refresh dashboard and make repeated panel's `fullscreen` state undefined.
maybe we should keep fullscreen panel information when refresh dashboard?

**Comment by okhowang** [comment]
I have change to allowing change variables which is not repeat by.
and keep fullscreen state when processRepeat.

**Comment by okhowang** [comment]
is there anything blocking merge?

**Review by torkelo — COMMENTED** [review]
Maybe a better solution is to stop the repeat process from being done while in edit mode? then remember to trigger it when we leave edit mode

**Comment by okhowang** [comment]
it sounds like good, I will implement it later

**Comment by okhowang** [comment]
at now, I trigger `templateVariableValueUpdated` after `PanelEvents.viewModeChanged`
there is a `setTimeout` to prevent render panel when it is not InView,
is there some better approach? @torkelo

**Comment by okhowang** [comment]
@torkelo can we continue to merge?

**Comment by torkelo** [comment]
Not sure, we are rewriting the template variable state to redux and components to react, so think it makes sense to wait and see how this applies to that new system,

**Comment by okhowang** [comment]
I notice that template variable has been rewrite in redux.
but component is also in angular.
when can we consider to merge this bugfix?

**Comment by torkelo** [comment]
Sorry for late feedback on this issue. 

Not sure this is the correct approach, not sure what is. Maybe the variable should be locked so you cannot change it in view mode for a repeated panel?

**Pull request closed without merging**
