### PR TITLE
Reporting: Handle timeouts in rendering

### PR DESCRIPTION
**Pull request by jongyllen**
**What this PR does / why we need it**:
The rendering plugin needs improvement to make sure rendering can proceed after timeouts occur.
* Changed default concurrence to 3 from 30 for performance.
* Added timeout in grpc call to plugins for rendering

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Can you describe the reduction in the concurrency limit from 30 to 3 and how that increased performance? 

This limit is a hard limit that just returns an error image (so there is no wait if it is breached). The reason that is that not to cause wait times to generate alert notifications.  

But because this limit is hard 3 is a very low default. I think if the limit caused just serial queuing when breached it would be fine. 

Might need two options to control concurrency. One that is a hard limit with no waiting if breached, and one that will cause waiting.

**Comment by jongyllen** [comment]
Ah, I see now - misunderstood the concurrency limit, thinking it only affected parallelism (cpu and memory, hence the perf comment). I see now how it also interacts with multiple calls for alerting.
I guess 30 is a sensible default in that case. And as you point out - having 2 limits and/or configurable with config would be a great future improvement

**Review by torkelo — APPROVED** [review]
Looks good!

**Review by xlson — APPROVED** [review]
Looks good

**Pull request merged**
