### PR TITLE
Prometheus: Upgrades the prometheus http client to 1.13

### PR DESCRIPTION
**Pull request by yesoreyeram**
PR to validate the fix https://github.com/prometheus/client_golang/pull/1022

### CODE REVIEW

**Comment by bboreham** [comment]
Results of trying this out - solid lines are incidences of the error, and dotted line is when we rolled out the fix.

Screenshot from 2022-05-05 11-02-47

**Comment by bboreham** [comment]
Was this change made somewhere else?

**Comment by yesoreyeram** [comment]
@bboreham - The fix was tested in https://github.com/grafana/grafana-private-mirror/commits/v8.5.0-felmo1. Actual fix will be implemented once the promclient released and tested (in a separate PR). This PR was just here to validate the fix.

**Comment by yesoreyeram** [comment]
nvm. Will keep this PR open and update this once the promclient released.

**Comment by bboreham** [comment]
I see it's been added to a [1.13.0 milestone](https://github.com/prometheus/client_golang/milestone/4), but no date attached.

**Comment by bboreham** [comment]
Prometheus client library has now been released with the fix.
https://github.com/prometheus/client_golang/releases/tag/v1.13.0

**Comment by bergquist** [comment]
Creating a new PR was faster than resolving merge conflicts :) https://github.com/grafana/grafana/pull/53901

**Pull request closed without merging**
