### PR TITLE
AzureMonitor: Add Links to Azure Portal for VM Insights dashboards

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What this PR does / why we need it**: Adds linking back to the Azure portal for existing VM insights dashboard

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by andresmgot** [comment]
Hi @jcolladokuri,

I believe the only change here are the new URLs like:


```
                    "url": "https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourcegroups/${__data.fields[\"Resource Group\"]}/providers/microsoft.compute/${__data.fields.Type/Name}/infrainsights"
```

Is that correct?

For those URLs I get the same error that @sarahzinger described here: https://github.com/grafana/grafana/pull/45187#discussion_r808152320

I managed to "fix" the URL changing two things:

 - `@microsoft.onmicrosoft.com` should be `@grafana.com` in our case. I am not sure how you can retrieve that but there it should be the domain in which the resource is deployed.
 -  `${__data.fields.Type/Name}` returns for me `virtualmachines%2Fgithubtestdatavm` rather than `virtualmachines/githubtestdatavm`. It's escaping the `/` and making the URL invalid, can you fix that?

**Comment by andresmgot** [comment]
Hi @jcolladokuri,

I believe the only change here are the new URLs like:


```
                    "url": "https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourcegroups/${__data.fields[\"Resource Group\"]}/providers/microsoft.compute/${__data.fields.Type/Name}/infrainsights"
```

Is that correct?

For those URLs I get the same error that @sarahzinger described here: https://github.com/grafana/grafana/pull/45187#discussion_r808152320

I managed to "fix" the URL changing two things:

 - `@microsoft.onmicrosoft.com` should be `@grafana.com` in our case. I am not sure how you can retrieve that but there it should be the domain in which the resource is deployed.
 -  `${__data.fields.Type/Name}` returns for me `virtualmachines%2Fgithubtestdatavm` rather than `virtualmachines/githubtestdatavm`. It's escaping the `/` and making the URL invalid, can you fix that?

**Comment by jcolladokuri** [comment]
@andresmgot I have fixed both issues you pointed out. there were some additional configs I had to make to the queries. 

Just an FYI, Contoso is a special case where cross-tenant management is being used to share access to resources in one tenant to users of another.

Two approaches, [Cross-tenant management experiences - Azure Lighthouse | Microsoft Docs](https://docs.microsoft.com/en-us/azure/lighthouse/concepts/cross-tenant-management-experience) or [Cross-tenant access overview - Azure AD | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/external-identities/cross-tenant-access-overview)

These are the cases where the user of the dashboard may not be in the same tenant as the VM. It more of a corner case than the norm.

If you are able to test with VMs that are not with Contoso that would be great!

**Review by andresmgot — APPROVED** [review]
Links are now working for me, thanks!

**Pull request merged**
