### PR TITLE
Encryption: De-duplicate encryption code with extensible service

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

Refactor of the encryption service to make it extensible from Enterprise instead of having lot of code duplication.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise/issues/3334

**Special notes for your reviewer**:

Goes with https://github.com/grafana/grafana-enterprise/pull/3607

### CODE REVIEW

**Review by undef1nd — COMMENTED** [review]
Thanks, Joan, for making this improvement 🚀 
I've reviewed the code, but want to test it manually to make sure we are not missing anything.

**Review by undef1nd — APPROVED** [review]

**Review by andresmgot — COMMENTED** [review]
hi @joanlopez, it seems that there are a lot of unrelated style changes. Not sure if that was caused by some config on your side, can you remove them to avoid noise?

**Comment by andresmgot** [comment]
thanks!

**Comment by joanlopez** [comment]
> hi @joanlopez, it seems that there are a lot of unrelated style changes. Not sure if that was caused by some config on your side, can you remove them to avoid noise?

Yes, sorry for the noise! 🙏🏻  I need to check what's wrong with the lint & style check tools in my local env!

**Pull request merged**
