### PR TITLE
AzureMonitor: Avoid instantiating appInsights for AppInsights for gov cloud

### LINKED ISSUE #35708: Azure Monitor: "The cloud not supported" after upgrading from v7.5 to v8.0.2
**What happened**:
Unable to use existing or create new Azure Monitor data sources that use Azure US Government Cloud.
When attempting to use the data source, use existing dashboards on the data source, create new dashboards from the data source, or create a new data source, an error notification of "the cloud not supported" appears and prevents any further action.
image

**What you expected to happen**:
Data source to continue to function as it did in v7.5.*

**How to reproduce it (as minimally and precisely as possible)**:
Running Grafana v8.0.2, create new Azure Monitor data source, select "Azure US Government", click "Save and Test"

**Anything else we need to know?**:
I was able to replicate this issue on Ubuntu 18.04, fresh install of Win10Pro, and in Grafana Cloud

**Environment**:
- Grafana version: v8.0.2
- Data source type & version: Azure Monitor - Azure US Government cloud
- OS Grafana is installed on: Ubuntu 18.04, Win10Pro, and Grafana Cloud
- User OS & Browser: Brave & Edge Chromium
- Grafana plugins: Azure Monitor

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

`AppInsights` and `InsightAnalytics` are not supported in the `gov` cloud (they are actually deprecated). Trying to validate or use them in the different panels causes the error described in #35708.

**Which issue(s) this PR fixes**:

Fixes #35708

**Special notes for your reviewer**:

I was able to reproduce the issue when trying to create a new datasource and simply selecting "Azure Goverment" and trying to save it (no need to actually access the cloud).

### CODE REVIEW

**Review by sarahzinger — APPROVED** [review]
Looks good to me!

**Review by joshhunt — APPROVED** [review]
Looks good! 

I would want to test this (once it's merged into main with one of the nightly docker images??) with someone who has access to US Gov cloud, if possible to be 100% sure we've fixed this and any other issues

**Review by kostrse — CHANGES_REQUESTED** [review]
One suggestion is to use `getAzureCloud` instead of directly accessing jsonData to check the current cloud. In case of managed identities the cloud determined from the Grafana configuration, rather than plugin settings and `getAzureCloud` handles this.

**Comment by andresmgot** [comment]
> However, when attempting to explore the data source using any namespace/metric (tried VM, app service, SQL server), it errors out with the same error of
> 
> ```
> Get "https://management.usgovcloudapi.net/subscriptions/XXXXXXXXXXXXXXXXXXX/resourceGroups/XXXX-rg-virginia/providers/Microsoft.Compute/virtualMachines/XXXXX-vm-virginia/providers/microsoft.insights/metrics?aggregation=Average&api-version=2018-01-01&interval=PT1M&metricnames=Percentage+CPU&metricnamespace=Microsoft.Compute%2FvirtualMachines&timespan=2021-06-16T17%3A14%3A43Z%2F2021-06-16T18%3A14%3A43Z": failed to retrieve azure access token: context canceled
> ```

mmh, that seems like a different issue. I wonder if it's related to the refactoring that is going on `main` (that will be released with Grafana 8.1). @cryocaustik once this PR is merged a backport PR will be created for the branch `v8.0.x` can you give that branch a try? Thanks a lot for testing this BTW!

@kostrse any idea of how we can debug that issue?

**Pull request merged**
