### PR TITLE
ManageDashboard: Fix dashboard list that overflows its parent container

### LINKED ISSUE #35313: ManageDashboards: Dashboard list overflowing its parent container
**What happened**:
Dashboard list page overflows its parent container by default thereby making the UI inconsistent.
**What you expected to happen**:
The parent container should be able to contain the dashboard list items appropriately.
**How to reproduce it (as minimally and precisely as possible)**:
Go to the sidemenu
Click on the Dashboard icon
Go to Manage
**Anything else we need to know?**:
Screenshot 2021-06-07 at 09 19 48

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR fixes dashboard list overflowing its parent container.
**Which issue(s) this PR fixes**:

Fixes #35313

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]
Great catch!

**Comment by jackw** [comment]
Tested locally and works great! Well done @thisisobate. 🚀

**Review by jackw — APPROVED** [review]

**Comment by torkelo** [comment]
Did anyone test this? it fails to show any items in search view now  (after switching to list view)

**Comment by jackw** [comment]
Ah my bad I tested the changes locally but didn't check list view. Sorry, I'll be more careful in the future.

**Pull request merged**
