### PR TITLE
fix: Faro usage issue

### PR DESCRIPTION
**Pull request by codecapitano**
# What
We discovered Faro that the Grafana Faro instance is crashing.

Screenshot 2024-01-05 at 10 42 13

This caused by an unintended usage of the Faro `FetchTansport` in the `GrafanaJavascriptAgentBackend` setup.

# Why
Due to the new pricing model Faro now adds a custom `x-faro-session-id` header to each requests it sends to the collector.
It receives the `sessionId` from the `SessionMeta` and attaches it to the `x-faro-session-id` header (`x-faro-session-id: mySessionId`).

Screenshot 2024-01-05 at 10 43 24

## What is the reason for the issue

The `GrafanaJavascriptAgentBackend` instantiates a `new FetchTransport` if it finds a custom endpoint in the config.

```ts
 if (options.customEndpoint) {
      this.transports.push(new FetchTransport({ url: options.customEndpoint, apiKey: options.apiKey }));
    }
```

This `FetchTransport` was never added to the Faro transports property such it was never registered on the Faro instance.

This is a problem because Faro maintains a bunch of runtime data, like the meta objects, which are automatically attached to the `FetchTransport` instance, so it's guaranteed that meta data is always available in the instance.

See this image taken from the browser debugger. You can see that the meta object is empty.
Screenshot 2024-01-05 at 10 31 16

See this image taken from the browser debugger which shows a `FetchTrasnport` registered on Faro. You see the metas object is available.
 
Screenshot 2024-01-05 at 10 41 49

## What caused the issue

The `GrafanaJavascriptAgentBackend` provides the `addEvent` function which iterates over the transports array which includes the `FetchTransport` which is **not** under the control of Faro.

```ts  
 addEvent = (e: EchoEvent) => {
    this.transports.forEach((t) => t.send(e.payload));
  };
```

What now happens is that the `send()` function of the transport is called, which wants to receive the session meta, but the metas object is empty, which caused above issue.

## What fixes the issue
If a custom transport  is needed, instantiate it and add register it on the Faro instance so all meta information is automatically updated.

When calling the `addEvent` function receive the registered transports to iterate and call `send()` on each.

```ts
addEvent = (e: EchoEvent) => {
    this.faroInstance.transports.transports
      // don't call 'EchoSrvTransport' because it already calls addEvent() internally.
      .filter((t) => t.name !== EchoSrvTransport.name)
      .forEach((t) => t.send(e.payload));
  };
```  

**Edit (24/05/01)**
Because the registered `EchoSrvTransport` already broadcasts all signals emitted by the Faro API we make this a noop function. Otherwise every signal is sent twice

## Other things done in this PR
* Update tests
* As discussed with @tolzhabayev we remove the custom session-id-generator and use the internal session-id-generator built into Faro

# Result 
Tested locally with the following `conf/custom.ini`

```
[log.frontend]
enabled = true
provider = grafana
custom_endpoint = /log-grafana-javascript-agent
instrumentations_errors_enabled = true
instrumentations_console_enabled = true
instrumentations_webvitals_enabled = true
apiKey = testingCustomApiKey
```

* Issue does not appear anymore
* Metadata is correctly attached to each beacon

https://github.com/grafana/grafana/assets/47627413/973ec026-a0c6-4339-9389-bb04b707697b

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by tolzhabayev — APPROVED** [review]
didn't test it out myself locally, but codewise lgtm!

**Comment by tolzhabayev** [comment]
Took it for a spin locally, seems to work fine!

**Review by ivanortegaalba — APPROVED** [review]
The code looks good to me! @tolzhabayev already tested locally. And the explanation is amazing. Thank you @codecapitano!

**Review by tolzhabayev — APPROVED** [review]

**Comment by tolzhabayev** [comment]
@codecapitano 

last thing - this test has to be adjusted https://drone.grafana.net/grafana/grafana/152853
```
GrafanaJavascriptAgentEchoBackend › will forward events to transports

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      157 |     backend.addEvent(event);
      158 |
    > 159 |     expect(mockTransports[0].send).toHaveBeenCalledTimes(1);
          |                                    ^
      160 |     expect(mockTransports[0].send).toHaveBeenCalledWith(event.payload);
      161 |
      162 |     expect(mockTransports[1].send).toHaveBeenCalledTimes(1);
```

**Comment by codecapitano** [comment]
> @codecapitano
> 
> last thing - this test has to be adjusted https://drone.grafana.net/grafana/grafana/152853
> 
> ```
> GrafanaJavascriptAgentEchoBackend › will forward events to transports
> 
>     expect(jest.fn()).toHaveBeenCalledTimes(expected)
> 
>     Expected number of calls: 1
>     Received number of calls: 0
> 
>       157 |     backend.addEvent(event);
>       158 |
>     > 159 |     expect(mockTransports[0].send).toHaveBeenCalledTimes(1);
>           |                                    ^
>       160 |     expect(mockTransports[0].send).toHaveBeenCalledWith(event.payload);
>       161 |
>       162 |     expect(mockTransports[1].send).toHaveBeenCalledTimes(1);
> ```

Thanks Timur,
removed the test because since we now let Faro handle to send beacons and don't use `addEvent()` anymore, we don't this test.

**Pull request merged**
