### PR TITLE
Chore: Bump MSW

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

Updates MSW npm dependency to fix a [dependabot warning](https://github.com/grafana/grafana/security/dependabot/99)

### CODE REVIEW

**Review by gabor — APPROVED** [review]
LGTM! (i did not test it. the diff looks ok)

**Comment by jackw** [comment]
@grafana/alerting-squad-frontend I would really appreciate it if someone could take this PR for a spin to help make sure nothing breaks with this patch bump. ✌️

**Comment by gillesdemey** [comment]
@konrad147 can you take this for a spin since you've used `msw` in some test I think?

**Review by gillesdemey — APPROVED** [review]
Tested and everything checks out!

**Comment by jackw** [comment]
@gillesdemey really appreciate you taking the time to test this branch. Thanks! 🙏

**Pull request merged**
