### PR TITLE
Organization Roles: Add None role with no permissions.

### PR DESCRIPTION
**Pull request by Freyert**
**What this PR does / why we need it**:
Having a `None` role would make the `auto_assign_role` with an `allow_users_to_sign_up` a little bit more secure.

The idea being that the `None` role has _no_ permissions and can't do anything until an administrator grants them permissions. Maybe this is a failure in the docs, but there doesn't seem to be a way to currently grant a user zero permissions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
@Freyert thank you for contribution. However, the existing issue #13474 haven't got any upvotes in over a year and this change have big implications even though your change is small code wise. We cannot accept this currently so will close it. With that said we can reopen this PR at any later stage given that more users showing interest in this or #13474 . 

Our current suggestion would be to use: either of
- `allow_users_to_sign_up=false` and invite users instead 
- use external auth provider like LDAP, OAuth or auth proxy
- give all users the viewer role by default and create folders only allowing certain users/teams to view.
- use two organizations, one that new users signing up get access to and another one which needs to be granted access by an admin.

Thinking some more of your described problem it feels to me that a more proper solution would be that newly signed up users needs to be approved by an admin, but that's a new concept in Grafana and a possible new feature request. 

Let me know if you any questions/concerns. Again, thanks for showing interest in contributing to Grafana.

**Comment by leepfrog-ger** [comment]
I think this would be a very sensible addition.

My use case:

- We have a set of dashboards that is regularly edited/expaneded
- There is a group of users that should be able to view select dashboards, but not all. Especially not all newly created ones
- LDAP authentication is used

My understanding is:

- that for LDAP signin to work I need to assign at least one role (so in this case the `Viewer` role)
- newly created dahsboards/folders automatically have the `Viewer` role mapped 
, which would mean that this group of useres can access those dashboards

This is risky because forgetting to remove the default `viewer` permissions when creating a new dashboard would grant access that is not intended. A much better approach would be to be able to either let users login via LDAP without assigning any roles at all or have - like in this PR - a role that does not grant any access to newly created items.

Am I missing another way to realize my requirements?

**Comment by aknuds1** [comment]
@leepfrog-ger Maybe you could comment in the corresponding [feature request](#13474)?

**Comment by levkar** [comment]
@marefr 
Even if you use oauth, there is no way to restrict users from using grafana if they are in the realm. If user can sign-up then they become  viewers by default.

PR #22383 allows restricting users to have on of those roles or denies user to login to grafana.

**Pull request closed without merging**
