### PR TITLE
Sign Drone's configuration YAML file

### PR DESCRIPTION
**Pull request by julienduchesne**
This is needed to protect the repository

### CODE REVIEW

**Review by joanlopez — COMMENTED** [review]
If I understand it correctly, this will prevent anyone running non-authorized commands in our Drone runners by creating a pull request that modifies the pipelines definition, because it'd require to update the signature with a valid credential. Am I right? 🤔  Thanks!

**Comment by aknuds1** [comment]
> If I understand it correctly, this will prevent anyone running non-authorized commands in our Drone runners by creating a pull request that modifies the pipelines definition, because it'd require to update the signature with a valid credential. Am I right? 🤔 Thanks!

@joanlopez that sounds about right.

**Comment by julienduchesne** [comment]
More info here: https://github.com/grafana/deployment_tools/blob/master/docs/infrastructure/drone/signing.md

**Review by jvrplmlmn — APPROVED** [review]
👍

**Review by zserge — APPROVED** [review]

**Review by dsotirakis — APPROVED** [review]
LGTM - let's see how that flies.

2 things:

* Could you please add some more info on the PR description? Like what's changed, what to do in order to sign the yaml etc? (or maybe add documentation - there may is, I may not see it 👀 )
* Does it make any sense to have `make drone` as a pre-commit hook?

Thanks @julienduchesne 🙏

**Comment by julienduchesne** [comment]
> LGTM - let's see how that flies.
> 
> 2 things:
> 
> * Could you please add some more info on the PR description? Like what's changed, what to do in order to sign the yaml etc? (or maybe add documentation - there may is, I may not see it 👀 )
> * Does it make any sense to have `make drone` as a pre-commit hook?
> 
> Thanks @julienduchesne 🙏

1. I added some info as a header in the `.drone.star` file
2. Only Drone users (Grafana employees) can do `make drone`, so it would fail for external contributors as well as employees who aren't logged in, so not really a good match for a hook IMO. The build won't start in a PR if the file isn't signed, so it will be pretty quick to figure out that something is wrong

**Comment by dsotirakis** [comment]
> Only Drone users (Grafana employees) can do make drone, so it would fail for external contributors as well as employees who aren't logged in, so not really a good match for a hook IMO. The build won't start in a PR if the file isn't signed, so it will be pretty quick to figure out that something is wrong

Yep, I meant local pre-commit hook!

**Comment by julienduchesne** [comment]
> > Only Drone users (Grafana employees) can do make drone, so it would fail for external contributors as well as employees who aren't logged in, so not really a good match for a hook IMO. The build won't start in a PR if the file isn't signed, so it will be pretty quick to figure out that something is wrong
> 
> Yep, I meant local pre-commit hook!

The drone token is refreshed every week, so you would have to reauthenticate. That might get annoying, but other than that, it should work

**Comment by zserge** [comment]
> > Only Drone users (Grafana employees) can do make drone, so it would fail for external contributors as well as employees who aren't logged in, so not really a good match for a hook IMO. The build won't start in a PR if the file isn't signed, so it will be pretty quick to figure out that something is wrong
> 
> Yep, I meant local pre-commit hook!

Of course, run `make drone` in a pre-commit hook only when the Drone files have been changed. Otherwise it will be too noisy, since a vast majority of commits never touch the CI/CD pipeline.

**Pull request merged**
