### PR TITLE
Docs: Replace links with relrefs

### PR DESCRIPTION
**Pull request by oddlittlebird**
One side effect of PR #32602 is that it showed us all the non-relref links in our documentation. 

This PR replaces the links with relrefs in all cases except for links to packages_api and glossary.md.

I also made a few extremely minor format edits.

@torkelo - This PR would be a great test for any Grot updates, as the changes in this large PR should apply to both `latest` and `next` docs.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by oddlittlebird** [comment]
If I add a backport now, will this merge to both `next` and `latest`?

**Comment by torkelo** [comment]
it will merge to master, then @grafanabot will open a NEW PR that will be target v7.5.x , this PR you have to merge manually.  

grot may fail to backport the PR if there are merge conflicts (very likely with a big PR like this). So then you will have to backport the changes manually using git and cherry pick the merge commit from this PR into v7.5.x (and open a PR based on that).

**Comment by achatterjee-grafana** [comment]
> it will merge to master, then @grafanabot will open a NEW PR that will be target v7.5.x , this PR you have to merge manually.
> 
> grot may fail to backport the PR if there are merge conflicts (very likely with a big PR like this). So then you will have to backport the changes manually using git and cherry pick the merge commit from this PR into v7.5.x (and open a PR based on that).

We will need some education on how to "backport the changes manually using git and cherry pick the merge commit from this PR into v7.5.x" ...

@oddlittlebird, once you have this figured out, can you add the instructions to a readme file or place similar within (https://github.com/grafana/grafana/tree/master/contribute) for others in the squad for reference. Thank you!

**Comment by osg-grafana** [comment]
> > it will merge to master, then @grafanabot will open a NEW PR that will be target v7.5.x , this PR you have to merge manually.
> > grot may fail to backport the PR if there are merge conflicts (very likely with a big PR like this). So then you will have to backport the changes manually using git and cherry pick the merge commit from this PR into v7.5.x (and open a PR based on that).
> 
> We will need some education on how to "backport the changes manually using git and cherry pick the merge commit from this PR into v7.5.x" ...
> 
> @oddlittlebird, once you have this figured out, can you add the instructions to a readme file or place similar within (https://github.com/grafana/grafana/tree/master/contribute) for others in the squad for reference. Thank you!

@daniellee made a note today in our 1:1 to have Torkel and friends create a flow diagram for how this works.

**Comment by oddlittlebird** [comment]
@torkelo, I was able to get this branch and fix the conflicts, but I cannot merge to the backport branch because it is protected. The instructions from Grot don't work in this case. Any suggestions? 
image

**Comment by torkelo** [comment]
you are very close , just open a new PR and select v7.5.x as the base base your backport-32916-to-v7.5.x  branch as the compare branch 
Screen Shot 2021-04-14 at 21 27 33

**Pull request merged**
