### PR TITLE
Show message when visualization search results in no hits 

### LINKED ISSUE #15330: Make the vis-picker input show error state when no panels match
When no panels match the picker, it would be good to show an error (red highligh?) state rather than the cool blue:
image

### PR DESCRIPTION
**Pull request by jschill**
Notify user by using red ($brand-warning, maybe it's too orange?) border color on zero hits with vizpicker.

screenshot 2019-02-12 17 12 02

screenshot 2019-02-12 17 18 16

Fixes #15330

### CODE REVIEW

**Comment by torkelo** [comment]
not sure if this a common approach to no hits. I think a "no panels found" message of some kind would be clearer. 

thoughts @Ijin08 ?

**Comment by jschill** [comment]
I totally agree. My opinion is that this ux pattern should be used when the actual input is bad (too long, wrong chars, wrong formatted email/tel/zip etc).

Will add a "No panels found" instead.

**Comment by jschill** [comment]
And in the longer run, this should be synced with the plugins page:

screenshot 2019-02-13 07 37 51

**Comment by jschill** [comment]
"Find more visualizations at Grafana.com <https://grafana.com/plugins?type=panel>"

**Comment by jschill** [comment]
Light:
screenshot 2019-02-13 09 17 26

Dark:
screenshot 2019-02-13 09 18 13

**Pull request merged**
