### PR TITLE
PlaylistPage: Skeleton loading state 💀 

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- makes `<Card>` actions more responsive by using `flex`+`gap` instead of `margin-right` to space the actions apart
- adjusts the skeleton theme to ensure skeletons are visible on secondary backgrounds
- refactors code out from `PlaylistPageList` into a separate `PlaylistCard` component
- adds skeleton for `PlaylistCard`
- adds skeleton for `PlaylistPageList`
- refactors `New playlist` button to be a page action
- replaces `PlaylistPage` loading state with skeleton

| before | after |
| --- | --- |
| image | image |

here's a video as well:

https://github.com/grafana/grafana/assets/20999846/f285f4fc-20a1-439e-852a-d3b2b7a1e3f9

**Why do we need this feature?**

- better loading state

**Who is this feature for?**

- everyone! 🙌 

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
LGMT 👌

**Comment by Clarity-89** [comment]
This looks really good! I wonder if we'd make it built-in into the Card component instead of building custom components like this? The way I see it working, is to add a `loading` prop to the Card and when that's true show the skeleton for each of the card's elements.

**Comment by ashharrison90** [comment]
> This looks really good! I wonder if we'd make it built-in into the Card component instead of building custom components like this? The way I see it working, is to add a `loading` prop to the Card and when that's true show the skeleton for each of the card's elements.

@Clarity-89 yeah i was originally going to do this. but i think `Card` is too generic tbh... you can pass _anything_ as the `Card.Heading` or `Card.Actions`, so it's hard to show a skeleton that matches nicely 🤔 open to suggestions tho 😄

**Comment by Clarity-89** [comment]
> > This looks really good! I wonder if we'd make it built-in into the Card component instead of building custom components like this? The way I see it working, is to add a `loading` prop to the Card and when that's true show the skeleton for each of the card's elements.
> 
> @Clarity-89 yeah i was originally going to do this. but i think `Card` is too generic tbh... you can pass _anything_ as the `Card.Heading` or `Card.Actions`, so it's hard to show a skeleton that matches nicely without doing these more specific implementations 🤔 open to suggestions tho 😄

I was thinking that each Card component, e.g. `Card.Heading` will render either children or skeleton based on the loading prop. But I guess we'd need to know the exact dimensions of the children for these components to render skeletons properly 🤔

**Comment by ashharrison90** [comment]
> > > This looks really good! I wonder if we'd make it built-in into the Card component instead of building custom components like this? The way I see it working, is to add a `loading` prop to the Card and when that's true show the skeleton for each of the card's elements.
> > 
> > 
> > @Clarity-89 yeah i was originally going to do this. but i think `Card` is too generic tbh... you can pass _anything_ as the `Card.Heading` or `Card.Actions`, so it's hard to show a skeleton that matches nicely without doing these more specific implementations 🤔 open to suggestions tho 😄
> 
> I was thinking that each Card component, e.g. `Card.Heading` will render either children or skeleton based on the loading prop. But I guess we'd need to know the exact dimensions of the children for these components to render skeletons properly 🤔

@Clarity-89 yep exactly, so it kinda ends up just being easier to pass the exact dimensioned skeletons in, and then you've just created `PlaylistCard.Skeleton` 😅

**Pull request merged**
