### PR TITLE
Cherry picks for v7.0.5

### PR DESCRIPTION
**Pull request by torkelo**
* Graphite: Fix tag value dropdowns not showing in query editor , (#25889), merge-sha: 75d8853aac367ae02dbca54a65948d5c01809a90
* Datasource: Make sure data proxy timeout applies to HTTP client, (#25865), merge-sha: 942a14b4ce2591b254e77d9cb02b3c02cd0014a2

* [x] Bumped version

### CODE REVIEW

**Comment by aknuds1** [comment]
This targets the wrong branch, it should be targeting v7.0.x.

**Comment by marefr** [comment]
I fixed the base branch. Weird I'm the author of the version bump :)

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
The build fails on enterprise, I wonder if the wrong branch is picked when building enterprise?

**Comment by aknuds1** [comment]
I re-triggered the build, actually it seems to fetch the right enterprise branch now, maybe it failed due to the wrong target branch.

**Comment by aknuds1** [comment]
Yep, enterprise back-end built this time around.

**Review by mckn — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
Fixed base

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
