### PR TITLE
XYChart: Fix numerous axis options

### LINKED ISSUE #74975: XY Chart: Axis placement set to hidden is still faintly visible
### What happened?

image
image
You can still see the lines with the number on the y axis, but in a very dark colour instead if gone.

### What did you expect to happen?

I expect those lines and numbers to disappear (like the x axis) when I set the placement to hidden.

### Did this work before?

I have not used this panel before, I do not know.

### How do we reproduce it?

1. Create panel
2. Set a datasource/query that can be displayed on an XY chart
3. Set the axis placement to hidden

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | xychart @ 10.0.2 (b2bbe10fbc) |
| Grafana | 10.0.2 (b2bbe10fbc) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "type": "xychart",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "meta": {},
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  },
                  {
                    "name": "Min",
                    "type": "number",
                    "config": {}
                  },
                  {
                    "name": "Max",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1694987669386,
                    1694987669436,
                    1694987669486,
                    1694987669536,
                    1694987669586,
                    1694987669636,
                    1694987669686,
                    1694987669736,
                    1694987669786,
                    1694987669836,
                    1694987669886,
                    1694987669936,
                    1694987669986,
                    1694987670036,
                    1694987670086,
                    1694987670136,
                    1694987670186,
                    1694987670236,
                    1694987670286,
                    1694987670336,
                    1694987670386,
                    1694987670436,
                    1694987670486,
                    1694987670536,
                    1694987670586,
                    1694987670635,
                    1694987670686,
                    1694987670736,
                    1694987670786,
                    1694987670836,
                    1694987670885,
                    1694987670936,
                    1694987670986,
                    1694987671036,
                    1694987671086,
                    1694987671136,
                    1694987671185,
                    1694987671236,
                    1694987671286,
                    1694987671336,
                    1694987671386,
                    1694987671436,
                    1694987671486,
                    1694987671536,
                    1694987671586,
                    1694987671636,
                    1694987671686
                  ],
                  [
                    30.38900907549287,
                    29.890506570998717,
                    30.002940383985262,
                    30.487779215660233,
                    30.944370704107744,
                    31.245805509016193,
                    31.059738815846217,
                    30.806838474821816,
                    30.780254854356176,
                    30.337183070602457,
                    30.20651212186423,
                    30.038395316798084,
                    30.36990587028565,
                    30.433491409848738,
                    30.815467197931863,
                    30.920155880654306,
                    30.88996983857162,
                    30.39246338144228,
                    30.62511847270726,
                    31.019037648690745,
                    30.95799596365587,
                    31.191816945857912,
                    31.574269349867677,
                    31.302855356613936,
                    31.048553958635445,
                    31.083761110137456,
                    31.53348590700656,
                    31.770154109592767,
                    31.3045468512101,
                    31.454729148620512,
                    31.180890178787806,
                    31.49753840723917,
                    30.99872558618051,
                    30.607708447645035,
                    30.389543309406527,
                    30.048672466240937,
                    30.089887691415534,
                    29.922410269541583,
                    29.88161787879063,
                    29.54234541133212,
                    29.144189291156888,
                    28.674771110177154,
                    28.965659276493554,
                    28.583775809610824,
                    28.99542443618201,
                    29.181212262122393,
                    28.682152281314245
                  ],
                  [
                    -7.895223913439676,
                    -7.717462769440175,
                    27.44013044653949,
                    15.975418552488573,
                    26.96721563091461,
                    -13.30147958379846,
                    25.099901212823678,
                    20.758771713519874,
                    1.562003777005188,
                    -6.090544502836096,
                    -14.01721194520777,
                    -1.7933608528830653,
                    15.164434368167347,
                    -17.82422638789713,
                    -18.961463672767,
                    -7.811190854478625,
                    -3.6470276835682434,
                    3.8932852701654497,
                    -12.026562847665158,
                    1.1273405299708301,
                    5.503949248802169,
                    -1.1331412421604306,
                    12.35841081950327,
                    29.119834370780605,
                    29.070243405576132,
                    -9.403779967525832,
                    -15.340031924214191,
                    -1.3413854451699123,
                    0.6210617188348486,
                    8.387342946757023,
                    13.65614709649018,
                    30.07466348248571,
                    12.975500905639759,
                    29.669900015836745,
                    26.31791295549347,
                    29.777616544176997,
                    12.883759099815354,
                    -16.648620751616118,
                    22.493343919726414,
                    -10.714123112186428,
                    -3.9056702299527295,
                    5.392413327134104,
                    5.566236721543039,
                    11.259518240056607,
                    21.924503175434147,
                    20.949268921193607,
                    -2.944301851875217
                  ],
                  [
                    34.181230861620506,
                    37.9739852469354,
                    55.60405323812081,
                    35.22167621309418,
                    33.59914546724551,
                    39.18523082069993,
                    41.585023935575094,
                    43.51724387301203,
                    41.682970613190236,
                    64.52286684216679,
                    53.254285138951616,
                    61.24461830112157,
                    64.87685743193698,
                    74.43470248985665,
                    72.69909976682763,
                    55.936198444005974,
                    51.62876091503226,
                    64.99103175704687,
                    66.30499822891201,
                    62.89364729808321,
                    74.48711657722188,
                    56.05468648355703,
                    73.45177098377985,
                    49.16050746802091,
                    38.724261922124015,
                    63.5398464408874,
                    70.01300159259442,
                    35.412805483298925,
                    78.64251922661039,
                    41.31849949805715,
                    31.296405434896375,
                    41.30386056820462,
                    66.04439562956372,
                    47.21967543554988,
                    49.66424561163484,
                    64.92696680318122,
                    48.11511493415946,
                    75.865794444724,
                    41.115167707924115,
                    62.38282393458602,
                    73.82038159082191,
                    38.99577125129374,
                    41.64272134072009,
                    39.276663593198904,
                    50.394968957744155,
                    54.8169913546252,
                    56.04185540150769
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "seriesMapping": "auto",
        "series": [],
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "show": "points",
            "axisPlacement": "hidden",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "axisGridShow": false
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          }
        },
        "overrides": []
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >xychart @ 10.0.2 (b2bbe10fbc)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 4 fields, 47 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.0.2 (b2bbe10fbc) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"type\": \"xychart\",\n  \"title\": \"Panel Title\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"datasource\": {\n    \"uid\": \"grafana\",\n    \"type\": \"datasource\"\n  },\n  \"id\": 2,\n  \"targets\": [\n    {\n      \"queryType\": \"measurements\",\n      \"datasource\": {\n        \"type\": \"datasource\",\n        \"uid\": \"grafana\"\n      },\n      \"refId\": \"A\",\n      \"channel\": \"plugin/testdata/random-20Hz-stream\"\n    }\n  ],\n  \"options\": {\n    \"seriesMapping\": \"auto\",\n    \"series\": [],\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"show\": \"points\",\n        \"axisPlacement\": \"hidden\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"axisGridShow\": false\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2023-09-17 17:54:44",
  "tags": [
    "debug",
    "debug-xychart"
  ],
  "time": {
    "from": "2023-09-17T15:54:44.881Z",
    "to": "2023-09-17T21:54:44.881Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.0.2
OS: Windows 10
Browser: Firefox 117.0.1 (64-bit)

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/74975

since uPlot will auto-add any missing axes, we have to explicitly add the axis with `show: false` rather than omitting it.

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
Tested locally and this resolved the issue - but while testing I noticed that the `Show grid lines` option doesn't seem to be working and might not make sense to appear for when the axis is hidden.

We might want to consider addressing this as either part of this PR or in a follow-up one

https://github.com/grafana/grafana/assets/22381771/f8c176a3-ce16-4d36-a532-278ea63eb562

**Comment by leeoniya** [comment]
> We might want to consider addressing this as either part of this PR or in a follow-up one

fixed, plus disabled some other opts when axis is hidden (color, border)

image

**Review by nmarrs — COMMENTED** [review]
Changes look good overall! I noticed a few lingering inconsistencies / broken functionality though

Primarily:
- width setting seems to have no impact for axis
- Color setting doesn't seem to have any impact
- Show axis option doesn't seem to have any impact

https://github.com/grafana/grafana/assets/22381771/2e019bcf-745d-42f4-bec5-0ea47a1d2191


[debug-Panel Title-2023-09-19 10_46_32.json.txt](https://github.com/grafana/grafana/files/12665005/debug-Panel.Title-2023-09-19.10_46_32.json.txt)

**Comment by leeoniya** [comment]
i'll take a look at the axis width and show [border] setting

i think the color setting is gonna be blocked on first figuring out the larger story for where we get point colors from (dim supplier, fixed point color, schemes, mappings, thresholds, etc.)

**Review by nmarrs — APPROVED** [review]
code looks good / works well locally 🚢

**Pull request merged**
