### PR TITLE
Login: OAuth: Allow logging in from all domains

### PR DESCRIPTION
**Pull request by n0emis**
**What this PR does / why we need it**:
When having multiple domains configured for grafana (e.g. in a loadbalancing-setup or internal/external domains), it is currently not possible to log in via OAuth on a secondary domain, since the oauth-state cookie is stored on the first url but the oauth-redirect always points to the `root_url`. Therefor the state-cookie cannot be read here. This PR set't the redirect_url to the url on which the user first visited grafana, to allow logging in on all domains.

**Which issue(s) this PR fixes**:
Being unable to log in via OAuth when visiting grafana on a url != the configured `root_url`.

### CODE REVIEW

**Comment by n0emis** [comment]
This would be (in my opinion better) alternative to #29324, because the other fix would only work if both installations are under the same domain.

**Comment by SimonDreher** [comment]
Is there anything I could help towards getting this merged?

We're also stuck with the same problem of two domains and editing the redirect-url manually works perfectly (so the same as this PR would do automatically)

**Comment by maxkondr** [comment]
@n0emis 
Could you please extend sign out action as well in order to send to OAuth server sign out action and return back to the grafana domain (I am referring to the following config option in grafana.ini):
```
[auth]
signout_redirect_url = https://<auth server>/login/signout?fromURI=https://<grafana domain that originally user used in browser>
```

**Comment by vincentnonim** [comment]
Hi,

This is exactly the feature I'm looking for. I have a similar setup with internal/external domain for the same Grafana instance and the OAuth is only working for 1 domain.
It could be great to have an OAuth redirect url based on Host header or even proxy header like `X-Forwarded-Host`.

**Pull request closed without merging**
