### PR TITLE
Docs: Fix formatting of docs file

### PR DESCRIPTION
**Pull request by torkelo**
Fixes broken main build

### CODE REVIEW

**Review by sakjur — APPROVED** [review]

**Comment by achatterjee-grafana** [comment]
Hi @torkelo, I indented the code block otherwise steps 12 and 13 show as steps 1 and 2.

**Comment by torkelo** [comment]
@achatterjee-grafana not sure I understand?

This just corrects the mardown formatting (auto corrected via markdown formatter prettier)

**Comment by kylebrandt** [comment]
8.4.x is also broken by this @achatterjee-grafana / @torkelo blocking a backport of mine https://github.com/grafana/grafana/pull/46415 - What does one do to get this backported after it has been merged?

**Comment by achatterjee-grafana** [comment]
I can revert the changes in 8.4.x. I did make the docs locally. I was able to see the doc content, without any errors.

**Comment by jdbaldry** [comment]
I believe the numbering issue is unrelated to the broken build but is something we will likely want to address also.

**Comment by torkelo** [comment]
@kylebrandt backport is here: https://github.com/grafana/grafana/pull/46417#pullrequestreview-906062585

**Comment by kylebrandt** [comment]
@jdbaldry / @achatterjee-grafana able to work out conflicts in https://github.com/grafana/grafana/pull/46417 then?

**Pull request merged**
