### PR TITLE
6.7.0 cherrypicks

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Cherry-pick changes for v6.7.0.

* DashboardSave: Autofocus save dashboard form input, (#22748), merge-sha: b441b7334568ce1175cd193e8faaffd6a3a666ff                                                           
* Datasource: making sure we are having the same data field order when using mixed data sources., (#22718), merge-sha: f44c0f06438076d257e06539e7cd400a3027d9a0               
22754 missing milestone!                                                                                                                                                      
* Add support for sending health check to datasource plugins., (#22771), merge-sha: ebc9549cbca74a6facd79de35048aa4924aadcda                                                  
* Core: Pass the rest of props to Select, (#22776), merge-sha: 451c95808d48454df14d3673ceab3b61abe0f8ca                                                                       
* Chore: remove expressions flag and allow, (#22764), merge-sha: c65db9bf25bff74efacf6e018f9fcbb4926e3ea7                                                                     
* DataSourceWithBackend: use /health endpoint for test, (#22789), merge-sha: 8b067a5fe016d6e14a46907469a1caf3df150de6                                                         
* BackendSrv: makes sure provided headers are correctly recognized and set, (#22778), merge-sha: b30f4c7bb05cd2379013dab23c0c65b95c449f28                                     
* AngularPanels: Fixed inner height calculation for angular panels , (#22796), merge-sha: f78501f3b59b48e1db061192adf7e5c9d8546e08                                            
* Forms: Fix input suffix position (caret-down in Select) , (#22780), merge-sha: ab0238eced0c56f7341e8597bff085d71d9813aa                                                     
* SaveDashboard: Updated modal design/layout a bit, (#22810), merge-sha: 46165a7f7b3652bfa2a08504551e86db4c32678d                                                             
* Grafana-UI: Add invalid state to Forms.Textarea, (#22775), merge-sha: cd50da3dbe8531bcb93ecfcf9b408dfafcb73555                                                              
* Core: Fix dashboard picker's props, (#22815), merge-sha: 2fac83441364902908ce18980415f3029c603110                                                                           
* TablePanel: Enable new units picker , (#22833), merge-sha: 58298919c8fb370fa3575bee71c47da034efa3dc                                                                         
* Rich History: UX adjustments and fixes, (#22729), merge-sha: 544690060a1b5ed3966a2e384b99b6b0dc95fe31                                                                       
* Upgrade backend plugin SDK to 0.30.0, (#22846), merge-sha: b0407b3578f40d86e6029976a16a3e0d05611b39                                                                         
* Datasource config was not mapped for datasource healthcheck, (#22848), merge-sha: 0a094a7319f5ed521630f4df3221c4bf48eaf665                                                  
* Rich history: Test coverage, (#22852), merge-sha: 8edf8e39829502223588e75d6e0608fd759e236e                                                                                  
* @grafana/runtime: Add cancellation of queries to DataSourceWithBackend, (#22818), merge-sha: eb96a8fcc8ca0949ccbe515ec56a059a90190138                                       
* Stackdriver: Fix GCE auth bug when creating new data source, (#22836), merge-sha: 1cd7ce24c7653fe8ecca5d9a79ab65b4bab381d0                                                  
* Graphite: Fixed issue with query editor and next select metric now showing after selecting metric node , (#22856), merge-sha: aa4ed76a004b345cd9b2f90151b898d29eb434c1      
* Backend plugins: Exclude plugin metrics in Grafana's metrics endpoint, (#22857), merge-sha: 60e3437fc13c11f3ebfd0ebf90aa344ded55a035                                        
* Plugins: Return jsondetails as an json object instead of raw json on datasource healthchecks., (#22859), merge-sha: 579abad9cc2059767ccc5c3b9d7d432731934cd8                
* SQLStore: Add migration for adding index on annotation.alert_id, (#22876), merge-sha: bb05989e4306a38e1afd6e2e1c2b8b751f3eb658                                              
* AzureMonitor: support workspaces function for template variables, (#22882), merge-sha: 3b9a4e6444a8c8a500f9dc88fb808c355e8c145a                                             
* Rich history UX fixes, (#22783), merge-sha: db85c3e7b933f61973ee9815bb3db268bb772417                                                                                        
* Rich history: Design updates, (#22886), merge-sha: 8ba75e77b1dca573f467c98ebdceb30d1f3fd782

### CODE REVIEW

**Comment by marefr** [comment]
I would normally include the output in the PR description because then all related PR's will get an update from this PR in their timeline.

  * DashboardSave: Autofocus save dashboard form input, (#22748), merge-sha: b441b7334568ce1175cd193e8faaffd6a3a666ff                                                                         
  * Datasource: making sure we are having the same data field order when using mixed data sources., (#22718), merge-sha: f44c0f06438076d257e06539e7cd400a3027d9a0                             
  22754 missing milestone!                                                                                                                                                                    
  * Add support for sending health check to datasource plugins., (#22771), merge-sha: ebc9549cbca74a6facd79de35048aa4924aadcda                                                                
  * Core: Pass the rest of props to Select, (#22776), merge-sha: 451c95808d48454df14d3673ceab3b61abe0f8ca                                                                                     
  * Chore: remove expressions flag and allow, (#22764), merge-sha: c65db9bf25bff74efacf6e018f9fcbb4926e3ea7                                                                                   
  * DataSourceWithBackend: use /health endpoint for test, (#22789), merge-sha: 8b067a5fe016d6e14a46907469a1caf3df150de6
  * BackendSrv: makes sure provided headers are correctly recognized and set, (#22778), merge-sha: b30f4c7bb05cd2379013dab23c0c65b95c449f28
  * AngularPanels: Fixed inner height calculation for angular panels , (#22796), merge-sha: f78501f3b59b48e1db061192adf7e5c9d8546e08
  * Forms: Fix input suffix position (caret-down in Select) , (#22780), merge-sha: ab0238eced0c56f7341e8597bff085d71d9813aa
  * SaveDashboard: Updated modal design/layout a bit, (#22810), merge-sha: 46165a7f7b3652bfa2a08504551e86db4c32678d
  * Grafana-UI: Add invalid state to Forms.Textarea, (#22775), merge-sha: cd50da3dbe8531bcb93ecfcf9b408dfafcb73555
  * Core: Fix dashboard picker's props, (#22815), merge-sha: 2fac83441364902908ce18980415f3029c603110
  * TablePanel: Enable new units picker , (#22833), merge-sha: 58298919c8fb370fa3575bee71c47da034efa3dc
  * Rich History: UX adjustments and fixes, (#22729), merge-sha: 544690060a1b5ed3966a2e384b99b6b0dc95fe31
  * Upgrade backend plugin SDK to 0.30.0, (#22846), merge-sha: b0407b3578f40d86e6029976a16a3e0d05611b39
  * Datasource config was not mapped for datasource healthcheck, (#22848), merge-sha: 0a094a7319f5ed521630f4df3221c4bf48eaf665
  * Rich history: Test coverage, (#22852), merge-sha: 8edf8e39829502223588e75d6e0608fd759e236e
  * @grafana/runtime: Add cancellation of queries to DataSourceWithBackend, (#22818), merge-sha: eb96a8fcc8ca0949ccbe515ec56a059a90190138
  * Stackdriver: Fix GCE auth bug when creating new data source, (#22836), merge-sha: 1cd7ce24c7653fe8ecca5d9a79ab65b4bab381d0
  * Graphite: Fixed issue with query editor and next select metric now showing after selecting metric node , (#22856), merge-sha: aa4ed76a004b345cd9b2f90151b898d29eb434c1
  * Backend plugins: Exclude plugin metrics in Grafana's metrics endpoint, (#22857), merge-sha: 60e3437fc13c11f3ebfd0ebf90aa344ded55a035
  * Plugins: Return jsondetails as an json object instead of raw json on datasource healthchecks., (#22859), merge-sha: 579abad9cc2059767ccc5c3b9d7d432731934cd8
  * SQLStore: Add migration for adding index on annotation.alert_id, (#22876), merge-sha: bb05989e4306a38e1afd6e2e1c2b8b751f3eb658
  * AzureMonitor: support workspaces function for template variables, (#22882), merge-sha: 3b9a4e6444a8c8a500f9dc88fb808c355e8c145a
  * Rich history UX fixes, (#22783), merge-sha: db85c3e7b933f61973ee9815bb3db268bb772417
  * Rich history: Design updates, (#22886), merge-sha: 8ba75e77b1dca573f467c98ebdceb30d1f3fd782

**Review by marefr — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Thanks for the tip @marefr - I wasn't sure, but it wasn't mentioned in the release guide. I'll make sure to update it.

**Comment by papagian** [comment]
LGTM!

**Pull request merged**
