### PR TITLE
Elasticsearch: Add word highlighting to search results

### LINKED ISSUE #23283: For elasticsearch datasource, search results can be highlight
For the elasticsearch datasource type, search results can be highlighted when using the explore function. like kibana search results highlights.

**Steps to reproduce**:
query:  o.s.w.s.DispatcherServlet

**Actual Result**:
No highlighting
image

**Expected Result**
highlighted
image

**Environment**: 
- Grafana version: 6.7
- Data source type & version: elasticsearch  6.0+
- User OS & Browser: chrome
- Others:

### PR DESCRIPTION
**Pull request by simianhacker**
**What this PR does / why we need it**:

This PR closed #23283 by adding search phrase highlighting to the Elasticsearch results. This PR also fixes a bug introduced in the "show context" feature from when we converted the `this.post()` request to an observable.

image

**Which issue(s) this PR fixes**:

Fixes #23283

### CODE REVIEW

**Review by Elfo404 — APPROVED** [review]
This works like a charm! 🚀 

I'm wondering if it makes sense to hide / not add to the dataframe the field relative to `highlight` by either:

```ts
    // do not add highlight field
    if (propName === 'highlight') {
      continue;
    }
```
in https://github.com/grafana/grafana/blob/91dff12cff6bfba4df21337489076db01ea5d8d9/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L683

or by
```ts
        custom: {
          hidden: propName === 'highlight',
        },
```

in https://github.com/grafana/grafana/blob/91dff12cff6bfba4df21337489076db01ea5d8d9/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L685

the reason is that it will get shown like this when revealing detected fields, which is not really useful. thought @ivanahuckova ?
Screenshot 2021-02-24 at 13 19 42

**Comment by simianhacker** [comment]
@Gio Good catch on the `highlight` field showing up. I will push a fix.

**Comment by Elfo404** [comment]
@simianhacker there's no need to push a fix for it now, I don't think it's really an issue. I was just wondering if it makes sense from a UX point of view 😄 

I'm gonna merge this as it is, but feel free to create a follow-up PR 🚀 

And thanks again for your contribution!

**Comment by ilyad91** [comment]
@simianhacker any chance you'd take a look at #33691 ? 👼 🙏

**Pull request merged**
