### PR TITLE
Explore: Allows a user to cancel a running query

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Allows a user to cancel a running query. Useful for datasources that may have long-running queries.

### CODE REVIEW

**Comment by aocenas** [comment]
So how does this actually cancel the query? Does it just count on datasource to implement correct cancelation on the returned observable?

@davkal mentioned he would prefer having a separate cancel button for this
> Re cancel vs run button, IMO it should be separate, in case you click multiple times

but to be honest I would be ok with having this as a run button state and if I assume we can change to 2 buttons in case case this becomes an issue. 

I think this would be good enough standalone but they also mentioned the panel edit case which is also part where user can run expensive query and could need a cancel button especially when they are run on blur without users explicit action. As the way to run the queries is inconsistent here it may not be required to have consistent cancelation ux but this may be a consideration before we merge this.

Any thoughts on this @davkal or @jessover9000?

**Comment by jessover9000** [comment]
> > Re cancel vs run button, IMO it should be separate, in case you click multiple times
> 
> but to be honest I would be ok with having this as a run button state and if I assume we can change to 2 buttons in case case this becomes an issue.

On one hand, I agree that if you click twice by accident, that could be annoying. on the other hand, how likely is it that people actually click that button? when I use the dropdown log labels thing to run queries, I actually really like the change of the button because it makes it very clear that the query is running now. and when I type something in the query input, I'll probably just run the query using the enter key, right?

**Comment by davkal** [comment]
I'm happy to start with a single-button solution. More interestingly is if we should always show Cancel for running queries and what that means for other datasources. It could just mean discarding the next responses?

**Comment by aocenas** [comment]
@davkal yeah that is a good point I don't think we can actually detect what datasource does on cancellation and so default would be just ignoring the response, is that right @kaydelaney ? We would need some other API or plugin config attribute to say it actually does meaningful cancelation, but I think even with that you may not get 100% assurances of what happens, ie I am not sure how RxJS handles any error when canceling.

**Comment by davkal** [comment]
I think discarding by default would be a start, and it's what I would expect (i.e., I'd be surprised if new results render after I cancel).

In future work we can revisit other datasources' APIs to see if they support cancellation. Some might already support it on an HTTP level, while others need an extra termination request.

**Comment by kaydelaney** [comment]
Re: actual cancellation of a running query, you're right @aocenas that this is something that would need to be implemented at the datasource level.
Maybe an optional method `stopQuery` that a datasource can implement which is called when the `cancelQueries` action is dispatched?

**Comment by torkelo** [comment]
Looks like a good solution! 

> Maybe an optional method stopQuery that a datasource can implement which is called when the cancelQueries action is dispatched?

Not sure what this would add.  The observable unsubscribe is exactly there to handle cancellations

**Comment by kaydelaney** [comment]
@torkelo Certain datasources might have long-running queries that need to be explicitly stopped which wouldn't be handled by `unsubscribe`. (See https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StopQuery.html)

**Comment by torkelo** [comment]
>  Certain datasources might have long-running queries that need to be explicitly stopped which wouldn't be handled by unsubscribe

But that should be easy just return a custom unsubscribe function in the data source and call the stop api. 

```typescript
return new Observable<PanelData>(subscriber => {
   const promise = apiStartQuery().then(res => {
      subscriber.next(res);
  }); 
     
  // Provide a way of canceling and disposing the interval resource
  return function unsubscribe() {
      promise.reject();
      apiStopQuery(); 
  };
});
```

**Comment by aocenas** [comment]
I agree with @torkelo here that the RxJS api should be enough also for this usecase. What I meant with new APIs is for DataSource to indicate that it actually does custom cancelation on top of just ignoring the response (which may be just a static property somewhere) but I agree that this would be a very much a nice to have feature and not something we have to consider now.

**Comment by aocenas** [comment]
I am happy with this right now so if there aren't any major objections I think we can iterate on it later on and separately figure out the panel edit usecase. @davkal @jessover9000 @torkelo

**Review by aocenas — APPROVED** [review]

**Pull request merged**
