### PR TITLE
PanelChrome: adding support to display error messages.

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
This PR adds support for adding error to the new PanelChrome component. This is useful when you want to indicate that we have some kind of errors with the configuration or query feeding the panel with data.

Skärmavbild 2021-04-07 kl  15 05 34

Skärmavbild 2021-04-07 kl  15 15 38

### CODE REVIEW

**Comment by torkelo** [comment]
The plan is to move away from corner errors and use an icon to the right of the text

**Comment by torkelo** [comment]
to have a unified way to show state icons (description icon, panel link icon, alert state icon, error notice, meta data notice) etc. Currently for example panel links & description get overriden (hidden) when you have a panel error

**Comment by mckn** [comment]
> to have a unified way to show state icons (description icon, panel link icon, alert state icon, error notice, meta data notice) etc. Currently for example panel links & description get overriden (hidden) when you have a panel error

Ah, ok ok! Even better 🙌🏻 Do we have any figma sketches on this? I am happy to change the implementation.

**Comment by torkelo** [comment]
no figma sketches

**Comment by mckn** [comment]
> no figma sketches

Would this work?

**Review by torkelo — APPROVED** [review]
Think this is ok for now

**Pull request merged**
