### PR TITLE
Query history:  Empty queries in query history fix 

### LINKED ISSUE #51328: Query history: Empty queries are being saved in history
**What happened**:
Empty queries are being saved in Query history. This is for example with Loki. I
image

I am able to reproduce it when I click to Line limit and query is empty. 
https://user-images.githubusercontent.com/30407135/175315163-80f9ad0e-1acc-4869-bc94-42fb1963b0ef.mov

In Query history, before sending it to DB, we have a check that `notEmptyQuery` in `public/app/core/utils/richHistory.ts`, but it is basic. I am wondering, if we are able to universal `notEmptyQuery`, or if data source needs to implement this. 

**What you expected to happen**:

Empty query shouldn't be saved. Also I think that duplicated queries right after each other shouldn't be saved.

**How to reproduce it (as minimally and precisely as possible)**:

See video above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0

### PR DESCRIPTION
**Pull request by Seyaji**
**What this PR does / why we need it**:
FIxes #51328

This is a fix for empty queries being stored in the query history. 

It seems that  loki adds and sends a '.expr'  property to the richHistory, this property is not available as a type in DataQuery so I had to use a ts-ignore for now, if this is expected then perhaps DataQuery should be updated to include the loki .expr property.

Currently I just put in a couple edge cases getting sent from loki to be checked against that are preventing empty history additions. 

https://user-images.githubusercontent.com/67058118/175438383-3f218a50-ecc3-4f9a-8c69-d0933de2b04c.mov

### CODE REVIEW

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
Unfortunately this is not a correct fix, as this would fix the issue only for Loki data source as it checks only for loki-specific query. I am not sure what would be the correct fix. One of the things I came up with is checking `getQueryDisplayText` method and if it is empty, then the query is empty. But not sure if @grafana/observability-experience-squad have any other/better idea.

**Comment by Elfo404** [comment]
unfortunately i think `getQueryDisplayText` is not a solution either as it's not required to be implemented by datasource plugins and can just return an empty string.

i also can't think of a proper fix to this with our current APIs, but sometime ago someone brought up the idea of adding a validation API to datasource plugins, it could be useful in this scenario as we could only save to history queries that pass validation (con: each datasource plugin would need to implement validation, for those who don't we'd still save empty/invalid queries in history)

wdyt?

**Comment by Seyaji** [comment]
IMG_0112

Sorry for my incomplete solution I'm still quite new to Grafana.

I'm just wondering at what point in the call chain the validator would be located. Is this for outbound too or simply flow control for inbound display data? 

Empty outbound calls don't seem like too much of an issue as there probably wont be many but in my mind the functionality should live at this point.

If its inbound then could the notEmptyQuery logic in richHistory be replaced with a more thorough 'validator' check that covers all the datasources? With some regex here you could filter out empty queries quite well. I Also see that the datasource is mentioned in the response object (if I'm not mistaken) so it would be quite easy to direct the validator.

I made a very basic diagram to visualise the flow.

**Comment by Elfo404** [comment]
@Seyaji no need to apologize at all, if anything thanks for contributing!
me and @ivanahuckova had a chat about this offline and we are still unsure what is the best path to move forward. Query validation is just one of possible solutions and i think it should sit before sending the query to the BE (in your diagram between datasources and API call).

Unfortunately we cannot make assumptions based on the shape of the query object (ie. checking for the presence of any keys - like `expr` in your PR - because each datasource specific query has a different shape, to the extent that for an hypothetical datasource, an object containing no keys (or empty) may be a totally valid query.

The idea of query validation is to extend the datasource API to allow plugins to specify their own specific validation logic to test queries objects against, allowing grafana to know wether a given query is valid or not, but this also comes with other issues.

As said we are still not quite sure yet what the best solution is yet, but we are planning on discussing it further soon

**Comment by Seyaji** [comment]
@Elfo404 Thanks for the explanation! It makes sense to extend the datasource api with validation on the outbound. I hope you make good progress on a solution to this  🙂

**Pull request closed without merging**
