### PR TITLE
CI: Fix missing vendor dependencies

### LINKED ISSUE #91871: Dockerfile: cannot load module pkg/promlib listed in go.work file
### What happened?

Same as #84342 and #83362 but with the following error:
```
 => ERROR [go-builder 14/27] RUN go mod download                                                                                                                                                       0.3s 
------                                                                                                                                                                                                      
 > [go-builder 14/27] RUN go mod download:                                                                                                                                                                  
0.222 go: cannot load module pkg/aggregator listed in go.work file: open pkg/aggregator/go.mod: no such file or directory                                                                                   
------                                                                                                                                                                                                      
Dockerfile:66                                                                                                                                                                                               
--------------------                                                                                                                                                                                        
  64 |     COPY pkg/semconv/go.* pkg/semconv/                                                                                                                                                               
  65 |                                                                                                                                                                                                      
  66 | >>> RUN go mod download                                                                                                                                                                              
  67 |     RUN if [[ "$BINGO" = "true" ]]; then \                                                                                                                                                           
  68 |           go install github.com/bwplotka/bingo@latest && \
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```

### What did you expect to happen?

Image building without error

### Did this work before?

yes

### How do we reproduce it?

```
make build-docker-full
```

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 427dad2
OS:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```
```
docker -v 
Docker version 27.1.1, build 6312585
```


### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by mehr74**
**What is this feature?**

Fix the issue #91871 

**Why do we need this feature?**

To build docker images correctly.

**Who is this feature for?**

Who builds docker image from Grafana repository.

**Which issue(s) does this PR fix?**:

Fixes #91871

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by mehr74** [comment]
@DanCech and @aangelisc, could you please double check this pull request?

**Comment by DanCech** [comment]
@mehr74 I understand us needing the missing go.mod/sum files, can you add some detail on why we need the conf defaults.ini and bash?

**Comment by mehr74** [comment]
Sure, here's the error I receive without `bash`.

```
make build-docker-full
...
 => CACHED [go-builder 27/28] COPY .github .github                                                                                                                                                            0.0s
 => ERROR [go-builder 28/28] RUN make build-go GO_BUILD_TAGS= WIRE_TAGS=oss                                                                                                                                  47.2s
------                                                                                                                                                                                                             
 > [go-builder 28/28] RUN make build-go GO_BUILD_TAGS= WIRE_TAGS=oss:                                                                                                                                              
0.648 generate go files                                                                                                                                                                                            
0.648 go run  ./pkg/build/wire/cmd/wire/main.go gen -tags oss ./pkg/server                                                                                                                                         
46.88 wire: github.com/grafana/grafana/pkg/server: wrote /tmp/grafana/pkg/server/wire_gen.go                                                                                                                       
47.07 updating workspace                                                                                                                                                                                           
47.07 bash scripts/go-workspace/update-workspace.sh
47.07 make: bash: No such file or directory
47.07 make: *** [Makefile:175: update-workspace] Error 127
------
Dockerfile:89
--------------------
  87 |     ENV BUILD_BRANCH=${BUILD_BRANCH}
  88 |     
  89 | >>> RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}
  90 |     
  91 |     FROM ${BASE_IMAGE} as tgz-builder
--------------------
ERROR: failed to solve: process "/bin/sh -c make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}" did not complete successfully: exit code: 2
make: *** [Makefile:312: build-docker-full] Error 1
```

**Comment by mehr74** [comment]
Here's the issue with Dockerfile without `defaults.ini`.

```
31.62 > nx run grafana:build                                                                                                                                                                                       
31.62                                                                                                                                                                                                              
32.94 [webpack-cli] Failed to load '/tmp/grafana/scripts/webpack/webpack.prod.js' config                                                                                                                           
32.94 [webpack-cli] Error: ENOENT: no such file or directory, open './conf/defaults.ini'                                                                                                                           
32.94     at readFileSync (node:fs:448:20)                                                                                                                                                                         
32.94     at getEnvConfig (/tmp/grafana/scripts/webpack/env-util.js:5:27)                                                                                                                                          
32.94     at Object.<anonymous> (/tmp/grafana/scripts/webpack/webpack.prod.js:26:19)                                                                                                                               
32.94     at Module._compile (node:internal/modules/cjs/loader:1358:14)                                                                                                                                            
32.94     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)                                                                                                                                     
32.94     at Module.load (node:internal/modules/cjs/loader:1208:32)                                                                                                                                                
32.94     at Module._load (node:internal/modules/cjs/loader:1024:12)
32.94     at Module.require (node:internal/modules/cjs/loader:1233:19)
32.94     at require (node:internal/modules/helpers:179:18)
32.94     at WebpackCLI.tryRequireThenImport (/tmp/grafana/node_modules/webpack-cli/lib/webpack-cli.js:223:30) {
32.94   errno: -2,
32.94   code: 'ENOENT',
32.94   syscall: 'open',
32.94   path: './conf/defaults.ini'
32.94 }
32.95 Error: Command failed: "webpack" "--config" "scripts/webpack/webpack.prod.js"
32.95     at genericNodeError (node:internal/errors:984:15)                                                                                                                                                        
32.95     at wrappedFn (node:internal/errors:538:14)
32.95     at checkExecSyncError (node:child_process:890:11)
32.95     at execSync (node:child_process:962:15)
32.95     at Object.nxExecCommand (/tmp/grafana/node_modules/nx/src/command-line/exec/exec.js:33:38)
32.95     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
32.95     at async Object.handler (/tmp/grafana/node_modules/nx/src/command-line/exec/command-object.js:11:13) {
32.95   status: 2,
32.95   signal: null,
32.95   output: [ null, null, null ],
32.95   pid: 30645,
32.95   stdout: null,
32.95   stderr: null
32.95 }
32.98 
32.98 
32.98 
32.98  NX   Running target build for project grafana and 11 tasks it depends on failed
```

```
docker -v 
Docker version 27.1.2, build d01f264
» lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

**Review by DanCech — APPROVED** [review]
LGTM

**Pull request merged**
