### PR TITLE
Scenes: Adjust styles to allow shrinking of variable selectors

### LINKED ISSUE #87051: DashboardScene: Panel edit with variable with many values make panel options invisible / impossible to resize
Looks like css issue for the Select component not compressing (or at least that is the root cause not sure what the solution will be) 

Example here: 
https://ops.grafana-ops.net/d/Gw-kpCGGz/enterprise-plugin-stats?var-Plugin=abhisant-druid-datasource&var-Plugin=ae3e-plotly-panel&var-Plugin=agenty-flowcharting-panel&var-Plugin=aggregations-io-datasource&var-Plugin=aidanmountford-html-panel&var-Plugin=akumuli-datasource&var-Plugin=alertlist&var-Plugin=alertmanager&var-Plugin=alexanderzobnin-zabbix-app&var-Plugin=alexandra-trackmap-panel&var-GrafanaMajorVersion=$__all&from=now-30d&to=now&timezone=browser&tab=queries&editPanel=11

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes https://github.com/grafana/grafana/issues/87051

### CODE REVIEW

**Comment by torkelo** [comment]
@kaydelaney great job figuring this out. Does fix the issue, only side-effect is the time picker now appears below the viz:
Screenshot 2024-04-30 at 10 16 45

Also, think we should also have overflow ellipsis on the variable name? if the variable name is long it does not compress. 

Also we have the same issue in the dashboard (variable select does not compress).

**Comment by kaydelaney** [comment]
@torkelo Hmm, not seeing the issue with the time picker appearing behind panels - Do you have some dashboard json I could take a look at?

**Comment by kaydelaney** [comment]
@torkelo Looking into it, we might need to portal the time picker, might be tricky

**Review by axelavargas — APPROVED** [review]
The simplified approach fixed this issue 🥳

**Pull request merged**
