### PR TITLE
Webpack: output js in `.min.js` ext

### LINKED ISSUE #63934: Grafana 9.4 proxy issue (Cloudflare)
**What happened**:
Running a simple Grafana instane in a Docker on Ubuntu 22.04
Protected by Cloudflare Tunnel
Upgraded grafana from 9.3 to 9.4
Grafana doesn't load anymore, shows an error page:
"If you're seeing this Grafana has failed to load its application files"

**What you expected to happen**:
Grafana to load

It does load via the direct IP+port internally, so I understand one would think that Cloudflare is the issue, however the upgrade is the thing that breaks it, so I am looking for the breaking change and how to reconfigure Cloudflare if needed.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy standard cloudflare tunnel
Deploy docker container for grafana 9.4

If i revert the image to 9.3 it works perfectly.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4
- Data source type & version: 
- OS Grafana is installed on: Ubuntu LTS 22.04
- User OS & Browser: Firefox  110
- Grafana plugins: none
- Others:

### PR DESCRIPTION
**Pull request by trim21**
**What is this feature?**

make webpack build js files as `.min.js` extension

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

Cloudflare can't minify js bundle currectly, but with `.min.js`, cloudflare will not try to minify it.

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

Running grafana with cloudflare proxing
[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/63934

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ryantxu** [comment]
@trim21 -- can you check the CLA button?  This PR looks good, but will let our webpack gurus verify and approve

**Comment by trim21** [comment]
@ryantxu Hi, I'm new to grafana, and I'm not very familiar with workflows, but this is a fix for 9.4.x, why `9.5.0` and `no-backport`? 🤔

**Comment by ryantxu** [comment]
In general we only backport bugs/security fixes to older releases -- i set that as a default.  After reading the description more in https://github.com/grafana/grafana/issues/63934, i think 9.4 is reasonable

**Comment by trim21** [comment]
Looks like all code related ci passed, is there anything else I need to do?

**Comment by ryantxu** [comment]
Nothing more needed -- the people who should merge this are in europe, so likely will get sorted out tomorrow.

Thanks for your help!

**Review by jackw — CHANGES_REQUESTED** [review]
Many thanks for contributing to Grafana. 🏅  

I believe this happened due to a change in our frontend tooling however I'm not :100: sure we should merge this PR.

We make no assurances to running Grafana behind Cloudflare and auto-minifying already minified code is going to produce issues at some point with any modern web app. The CF control panel mentions this in the Auto-Minify setting:

>Note: Please note that this feature may not be fully compatible with certain newer CSS and JS language features, which could potentially affect the functionality of your site.

Given the Grafana browserslist targets modern browsers I'm surprised this didn't happen sooner.

I think we would rather users running Grafana behind CF make the necessary changes in the CF control panel (either by disabling auto-minify for JS or creating a page rule) than introduce changes to the codebase that might impact how other services treat the code.

I'm gonna ping @grafana/frontend-ops for any further opinions.

**Comment by trim21** [comment]
> I think we would rather users running Grafana behind CF make the necessary changes in the CF control panel (either by disabling auto-minify for JS or creating a page rule) than introduce changes to the codebase that might impact how other services treat the code.

what kind of "impact how other services treat the code" there might be 🤔

**Comment by zoltanbedi** [comment]
@trim21 thanks for opening this pr. We decided to not to merge this. I think @jackw summarised it pretty well why. Thanks for bearing with us anyway.

**Comment by tolzhabayev** [comment]
https://github.com/grafana/grafana/issues/63934#issuecomment-1489934010

**Pull request closed without merging**
