### PR TITLE
Chore: upgrade eslint and fork-ts-checker-webpack-plugin

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Eslint used to have a bug where it ignored symlinked files, it has been fixed in the latest v7.21. Now when running `yarn start` for ex., eslint errors will be reported for the symlinked files as well (e.g. enterprise files). fork-ts-checker-webpack-plugin has to be updated to the latest version for this to work properly as well.

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Whohoo. I've tried it and it is working now. Would it make sense to update eslint in the `@grafana/eslint-config` and also in the toolkit package?

**Comment by Clarity-89** [comment]
> Would it make sense to update eslint in the `@grafana/eslint-config` and also in the toolkit package?

I was wondering about that as well, I guess it's a good idea to have the version synced across the packages.

**Review by mckn — APPROVED** [review]
Awesome work on this! Have you published the `@grafana/eslint-config` to npm and github registry?

**Comment by Clarity-89** [comment]
> Awesome work on this! Have you published the `@grafana/eslint-config` to npm and github registry?

No I haven't, do I just run `npm publish` in that repository? Couldn't find any other instructions.

**Comment by mckn** [comment]
> > Awesome work on this! Have you published the `@grafana/eslint-config` to npm and github registry?
> 
> No I haven't, do I just run `npm publish` in that repository? Couldn't find any other instructions.

hmm, yes - but you need to do it twice. One for npm and one for github registry. 
Do you want me to do it for you? What version number should the new one have?

**Comment by Clarity-89** [comment]
> Do you want me to do it for you? What version number should the new one have?

That would be great! I think the new package version should be `"2.3.0",` as it's a minor change.

**Comment by mckn** [comment]
> > Do you want me to do it for you? What version number should the new one have?
> 
> That would be great! I think the new package version should be `"2.3.0",` as it's a minor change.

It should now be available :)

**Comment by Clarity-89** [comment]
> > > Do you want me to do it for you? What version number should the new one have?
> > 
> > 
> > That would be great! I think the new package version should be `"2.3.0",` as it's a minor change.
> 
> It should now be available :)

Awesome! Thanks a lot for the help! I'll update `@grafana/eslint-config` version in this PR as well.

**Comment by zoltanbedi** [comment]
Please don’t forget to update `@grafana/eslint-config` in grafana-toolkit as well.

**Comment by zoltanbedi** [comment]
Last request and this is ready to go. Can you ran `yarn install` please so the lock file is updated properly?

**Review by zoltanbedi — APPROVED** [review]
🎉

**Pull request merged**
