### PR TITLE
Graph NG: adding support for displaying graph as bar char.

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
This is very much work in progress.

### CODE REVIEW

**Comment by dprokop** [comment]
Woo hoo! Will take a look at this first thing in the morning if that's fine @mckn ?

**Comment by mckn** [comment]
> Woo hoo! Will take a look at this first thing in the morning if that's fine @mckn ?

Yes, it is not yet working. But hopefully soon :)

**Comment by mckn** [comment]
I'm having trouble getting the drawPath function to be triggered. @leeoniya do you know what I might have done wrong? Would be super happy for your input 🙏

**Comment by leeoniya** [comment]
quite a bit going on here. nothing immediately obvious without running the code, seeing the full state, etc. would be happy to take a look if there's an isolated jsfiddle tho :), but don't have enough spare cycles right now to clone, build, debug, etc.

**Comment by mckn** [comment]
> quite a bit going on here. nothing immediately obvious without running the code, seeing the full state, etc. would be happy to take a look if there's an isolated jsfiddle tho :), but don't have enough spare cycles right now to clone, build, debug, etc.

Hehe, yeah! I agree it isn't really obvious what is happening in this code. But this is the final uPlot config that is being generated and I can't get it to execute the `drawPaths` function in the `barChart` plugin.

Do you see any obvious reason?

```json
{
    "focus": {
        "alpha": 1
    },
    "cursor": {
        "focus": {
            "prox": 30
        }
    },
    "legend": {
        "show": false
    },
    "series": [
        {},
        {
            "width": 1,
            "points": {
                "show": false
            },
            "scale": "__fixed",
            "stroke": "#808080",
            "fill": "rgba(128, 128, 128, 0.1)"
        }
    ],
    "hooks": {},
    "width": 1193,
    "height": 90,
    "plugins": [
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        },
        {
            "hooks": {}
        }
    ],
    "axes": [
        {
            "scale": "x",
            "show": true,
            "size": 80,
            "stroke": "#c7d0d9",
            "side": 2,
            "grid": {
                "show": true,
                "stroke": "#555555",
                "width": 0.5
            },
            "ticks": {
                "show": true,
                "stroke": "#555555",
                "width": 0.5
            },
            "values": [
                [
                    31536000,
                    "{YYYY}",
                    7,
                    "{YYYY}"
                ],
                [
                    2419200,
                    "{{YYYY}-{MM}",
                    7,
                    "{MMM}\n{YYYY}"
                ],
                [
                    86400,
                    "{{MM}/{DD}",
                    7,
                    "{MM}/{DD}\n{YYYY}"
                ],
                [
                    3600,
                    "{{HH}:{mm}",
                    4,
                    "{HH}:{mm}\n{MM}/{DD}"
                ],
                [
                    60,
                    "{{HH}:{mm}:{ss}",
                    4,
                    "{HH}:{mm}:{ss}\n{MM}/{DD}"
                ],
                [
                    1,
                    ":{ss}",
                    2,
                    ":{ss}\n{MM}/{DD} {HH}:{mm}"
                ],
                [
                    0.001,
                    ":{ss}.{fff}",
                    2,
                    ":{ss}.{fff}\n{MM}/{DD} {HH}:{mm}"
                ]
            ]
        },
        {
            "scale": "__fixed",
            "label": "",
            "show": true,
            "size": 60,
            "stroke": "#c7d0d9",
            "side": 3,
            "grid": {
                "show": true,
                "stroke": "#555555",
                "width": 0.5
            },
            "ticks": {
                "show": true,
                "stroke": "#555555",
                "width": 0.5
            }
        }
    ],
    "scales": {
        "x": {
            "time": true
        },
        "__fixed": {
            "time": false
        }
    }
}
````

**Comment by mckn** [comment]
> > quite a bit going on here. nothing immediately obvious without running the code, seeing the full state, etc. would be happy to take a look if there's an isolated jsfiddle tho :), but don't have enough spare cycles right now to clone, build, debug, etc.
> 
> Hehe, yeah! I agree it isn't really obvious what is happening in this code. But this is the final uPlot config that is being generated and I can't get it to execute the `drawPaths` function in the `barChart` plugin.
> 
> Do you see any obvious reason?
> 
> ```json
> {
>     "focus": {
>         "alpha": 1
>     },
>     "cursor": {
>         "focus": {
>             "prox": 30
>         }
>     },
>     "legend": {
>         "show": false
>     },
>     "series": [
>         {},
>         {
>             "width": 1,
>             "points": {
>                 "show": false
>             },
>             "scale": "__fixed",
>             "stroke": "#808080",
>             "fill": "rgba(128, 128, 128, 0.1)"
>         }
>     ],
>     "hooks": {},
>     "width": 1193,
>     "height": 90,
>     "plugins": [
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         },
>         {
>             "hooks": {}
>         }
>     ],
>     "axes": [
>         {
>             "scale": "x",
>             "show": true,
>             "size": 80,
>             "stroke": "#c7d0d9",
>             "side": 2,
>             "grid": {
>                 "show": true,
>                 "stroke": "#555555",
>                 "width": 0.5
>             },
>             "ticks": {
>                 "show": true,
>                 "stroke": "#555555",
>                 "width": 0.5
>             },
>             "values": [
>                 [
>                     31536000,
>                     "{YYYY}",
>                     7,
>                     "{YYYY}"
>                 ],
>                 [
>                     2419200,
>                     "{{YYYY}-{MM}",
>                     7,
>                     "{MMM}\n{YYYY}"
>                 ],
>                 [
>                     86400,
>                     "{{MM}/{DD}",
>                     7,
>                     "{MM}/{DD}\n{YYYY}"
>                 ],
>                 [
>                     3600,
>                     "{{HH}:{mm}",
>                     4,
>                     "{HH}:{mm}\n{MM}/{DD}"
>                 ],
>                 [
>                     60,
>                     "{{HH}:{mm}:{ss}",
>                     4,
>                     "{HH}:{mm}:{ss}\n{MM}/{DD}"
>                 ],
>                 [
>                     1,
>                     ":{ss}",
>                     2,
>                     ":{ss}\n{MM}/{DD} {HH}:{mm}"
>                 ],
>                 [
>                     0.001,
>                     ":{ss}.{fff}",
>                     2,
>                     ":{ss}.{fff}\n{MM}/{DD} {HH}:{mm}"
>                 ]
>             ]
>         },
>         {
>             "scale": "__fixed",
>             "label": "",
>             "show": true,
>             "size": 60,
>             "stroke": "#c7d0d9",
>             "side": 3,
>             "grid": {
>                 "show": true,
>                 "stroke": "#555555",
>                 "width": 0.5
>             },
>             "ticks": {
>                 "show": true,
>                 "stroke": "#555555",
>                 "width": 0.5
>             }
>         }
>     ],
>     "scales": {
>         "x": {
>             "time": true
>         },
>         "__fixed": {
>             "time": false
>         }
>     }
> }
> ```

oh, that looks weird. Let me check that I posted the right config.

**Comment by mckn** [comment]
@leeoniya you can ignore this. I manage to get it working. It was me who run the example with bad time range settings 🙈

**Comment by leeoniya** [comment]
@mckn 

while working on this, keep https://github.com/leeoniya/uPlot/issues/184 in mind.

i'd like to extract some generic logic for drawing boxes and/or computing metrics given a cfg of some layout parameters. this would allow reusing quite a bit of code for:

- grouped bars
- stacked bars
- grouped & stacked bars
- OHLC candles
- box & whisker plots
- timeline plots
- maybe even latency heatmaps, if you squint hard enough

vertical bars must be horizontally sized and distributed. and something like timeline plots also shares a common thing with [y-shifted series](https://leeoniya.github.io/uPlot/demos/y-shifted-series.html) - both need to be vertically distributed, padded/gapped and sized.

some ideas for input parameters into a generic boxmetics function could be:

- current full dim of plotting area
- current scale range
- qty of items
- qty of groups
- min/max item width
- min/max group width
- min/max item gaps
- min/max group gaps
- overall alignment
- additional min/max padding (for possible scale expansion)

probably lots of other stuff.

i haven't thought too hard about this, but there's quite a lot of overlap and it would be good to flesh out some common set of patterns for the logic needed to distribute and arrange rectangular elements.

**Pull request closed without merging**
