### PR TITLE
Fix bar width issue in aligned prometheus queries

### LINKED ISSUE #12379: prometheus query time alignment cause bar width to fluctuate
bug

to reproduce: create a bar graph panel

zoom it zoom out move forward ... after a few attemps the problem shows.

in real condition it shows up randomly.

### PR DESCRIPTION
**Pull request by davkal**
This was broken because null values were filled in with unaligned times.

* use aligned times for result transformation
* add tests

An earlier version of this fix aligned the times again in the transformer, but
I think it's safe to only deal with aligned times in the response.

Fixes #12379 
Related: #12417

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by torkelo** [comment]
question is if this should be marked for patch release or not

**Comment by grobie** [comment]
@torkelo it's not a critical issue for us, we'd have rolled back to 5.1.0 otherwise.

**Comment by dswarbrick** [comment]
I would really appreciate if this could be released as a 5.2.x patch. It's pretty annoying, and unless 5.3 is around the corner, we may go back to "jumpy-but-correct-thickness" bars.

**Comment by marefr** [comment]
Probably a good idea. Will change milestone to 5.2.2. No planned release date for 5.2.2 yet though

**Pull request merged**
