### PR TITLE
Opentsdb: Add tag values into the opentsdb response

### LINKED ISSUE #47092: Add tag values to the opentsdb response for alert messages.
**What happened**:

I usually construct a panel in a way that separates each metric into several tags using one metric_name.
For example, Such like bellow.
image

With this, I created alert(on ngalert) and test it.
And I found that tag values are not included into alert messages.
So I had to see the panel to check which metric had a problem.

alert messages 
```
title: [FIRING:1]
message: **Firing**

Value: [ metric='xxx.for-oncall' labels={} value=46 ]
```

---

**What you expected to happen**:

I thought, if tag values are included in alert message.
I fixed codes ( only 8 lines over 3 files with test case ), and I could get expected result. 😄 

Changed codes are bellow, 
image

And bellow is alert message i received after change codes.
```
title: [FIRING:1]
message: **Firing**

Value: [ metric='xxx.for-oncall' labels={host=host1, location=loc1, Type=type1, streamId=sid1, svc_type=real}} value=46 ]
```
I think this is not a bug. 
I don't know if it was intentional, but is there a problem if I change it like this? 😅 

---

**How to reproduce it (as minimally and precisely as possible)**:

Any alerts that included a metric with multiple tags.

**Anything else we need to know?**:

nothing..

----

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: opentsdb
- OS Grafana is installed on: Centos7
- User OS & Browser: windows10
- Grafana plugins: none
- Others: none

### PR DESCRIPTION
**Pull request by xy-man**
**What this PR does / why we need it**:

- What this PR does
  - Add tag values into the opentsdb response. 
  - With this PR, we can see tag values of metric which had a problem in alert messages.
- Why we need it
  - Tag values are not included into alert messages.
  - So we have to see the panel to check which metric had a problem.

**Which issue(s) this PR fixes**:

- resolve issue: https://github.com/grafana/grafana/issues/47092

Fixes #47092 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by joeblubaugh** [comment]
Can you update the "Why we need it" section of the PR message? What's wrong about missing tag values?

**Comment by xy-man** [comment]
@joeblubaugh 
I updated PR message. 😅

**Comment by xy-man** [comment]
Hi @joeblubaugh. 

how's going this issue?

**Comment by Jack1007** [comment]
Could someone review this issue?

**Review by joeblubaugh — APPROVED** [review]
Sorry for the delay, and thanks for the contribution!

**Comment by joeblubaugh** [comment]
@xy-man could you please run `make lint-go` in your local environment and clean up the lint errors:
```
pkg/tsdb/opentsdb/opentsdb_test.go:64: File is not `goimports`-ed (goimports)
			data.NewField("value", map[string]string{"env":"prod", "app":"grafana"}, []float64{
```

**Comment by joeblubaugh** [comment]
And one minor change to the PR title to pass the Changelog check, capitalize the first word after the section. "add" becomes "Add"

**Comment by xy-man** [comment]
@joeblubaugh 

I changed title of this PR and fix lint-go error. (format error)

**Comment by joeblubaugh** [comment]
Sorry, one more request, from looking at the CI build failures: can you merge main from grafana/grafana? There's a change to the tools used in the pr-build-e2e check that's causing the faiulre.

**Comment by xy-man** [comment]
@joeblubaugh 

I merged grafana:main to this PR branch. 
But `Enterprise PR check` is still failing. 
What is a problem?

**Comment by joeblubaugh** [comment]
@xy-man That's no problem - the Enterprise check only works on grafana/grafana because of the way the CI job for it is written. That's why it's not a required check to merge.

I appreciate how responsive you've been when updating this - merging now!

**Pull request merged**
