### PR TITLE
Variables: fix so the variable picker will remember selected options between filtering

### LINKED ISSUE #24990: Variable multi value selection is broken in Grafana 7
**What happened**: In Grafana 6 it was possible to select multiple values from a variable by searching, clicking, searching another one, and clicking again. But this doesn't work in Grafana 7 anymore, on the second search the previous selected value gets unselected.

**What you expected to happen**: Keep the selected values while searching for a new one

**How to reproduce it (as minimally and precisely as possible)**:

I've attached a dashboard to illustrate the problem, there is a variable with the values server00 to server99 in it. Search for let's say server50 in the search box and click on the resulting entry, and then search for server90 and try to select that without losing server50.

[test.json.txt](https://github.com/grafana/grafana/files/4663166/test.json.txt)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: none
- OS Grafana is installed on: Linux
- User OS & Browser: Brave and Firefox
- Grafana plugins: none
- Others: n/a

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
Have done some refactoring to make the options picker a bit more robust and to resolve reported and issues found during testing. Also have added some more tests to make sure we don't introduce this kind of errors again.

Todo:
- [x] write test to verify that we use the values from `selectedValues` and not the options values when closing the picker.
- [x] write test to verify that you still can select by highlight after filtered options.
- [x] change so you can select a value with space even if you have written anything in the input.
- [x] Improve tags select/de-select code in reducer.
- [x] Add some more tests to verify tags select/de-select.

**Which issue(s) this PR fixes**:
1. The variable options picker was a bit buggy when navigating with the keyboard and select items with space.
2. The following issue: #24990

### CODE REVIEW

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Haven't looked through the code yet, but when I do a search and add selected options. The result is that only the last selected options are remembered:
temp-vars-picker

OBS you need to search and then select some other options. I've been refactoring webpack the whole morning so this might be in my box only though.

**Comment by mckn** [comment]
> Haven't looked through the code yet, but when I do a search and add selected options. The result is that only the last selected options are remembered:
> temp-vars-picker
> 
> OBS you need to search and then select some other options. I've been refactoring webpack the whole morning so this might be in my box only though.

Ahh, good! I think I probably just have missed mapping from selectedValues when closing the picker. Will fix! Great findings!

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Works a lot better and you added back the space selection which is great!! 

But now when I use ENTER to close the picker, the last selected value doesn't seem to be included. See movie below:
temp-vars-picker-enter

**Comment by mckn** [comment]
> Works a lot better and you added back the space selection which is great!!
> 
> But now when I use ENTER to close the picker, the last selected value doesn't seem to be included. See movie below:
> temp-vars-picker-enter

Awesome findings! I am guessing it is de-selecting the last item when you press enter.

**Comment by mckn** [comment]
@hugohaggmark it should be fixed in last commit

**Comment by hugohaggmark** [comment]
> @hugohaggmark it should be fixed in last commit

Looks good, unfortunately the opposite is true now. If search and then you deselect the an item with SPACE and press ENTER the item remains selected :)

**Comment by mckn** [comment]
> > @hugohaggmark it should be fixed in last commit
> 
> Looks good, unfortunately the opposite is true now. If you search and then you deselect an item with SPACE and press ENTER the item remains selected :)

Ah, but enter is equal to select and close. So I think this is correct. Otherwise we might need to change so enter is only close.

**Comment by hugohaggmark** [comment]
> > > @hugohaggmark it should be fixed in last commit
> > 
> > 
> > Looks good, unfortunately the opposite is true now. If you search and then you deselect an item with SPACE and press ENTER the item remains selected :)
> 
> Ah, but enter is equal to select and close. So I think this is correct. Otherwise we might need to change so enter is only close.

Aha ok, gotcha!

**Review by hugohaggmark — APPROVED** [review]
Great work as usual and works as expected!

**Comment by datamuc** [comment]
Looks good to me 👍

**Pull request merged**
