### PR TITLE
Upgrading packages

### PR DESCRIPTION
**Pull request by Nepomuceno**
Upgrading all the packages to keep up to date and avoid bugs

### CODE REVIEW

**Comment by daniellee** [comment]
Looks like this broke the tests. Do you have the time to investigate it and fix them?

**Comment by bergquist** [comment]
Thanks for the effort but I'm closing this due to inactivity. 

Please ping me/open a new issue if you want to fix this.

**Comment by torkelo** [comment]
was this not a good PR and work we should do anyway? not sure what the broken test was though, maybe something easy to fix.

**Comment by Nepomuceno** [comment]
Sorry this got lost on my inbox I will check to update the packages and fix the tests

**Comment by bergquist** [comment]
@Nepomuceno No worries! PR's like this is extremely valuable but we just want to reduce the amount of inactive PR. Opening a new PR would be very appreciated.

**Pull request closed without merging**
