### PR TITLE
Add Icinga2 notification channel

### LINKED ISSUE #16120: Add Icinga2 as Notification Channel
**What would you like to be added**:
Sending notifications to Icinga2 as passive check results

**Why is this needed**:
It enables the user to manage notifications streams central in their Icinga2 instance along with their already existing system monitoring and notifications.

### PR DESCRIPTION
**Pull request by bomba1988**
**What this PR does / why we need it**:
This PR implements the Icinga2 Notification Channel, which enables Grafana to send alerts to Icinga2 as passive check results

**Which issue(s) this PR fixes**:
Fixes #16120

**Special notes for your reviewer**:

**Release note**:

```release-note
Alerting: Added Icinga2 notification channel
```

### CODE REVIEW

**Comment by torkelo** [comment]
We are very conservative on adding new notification channels at this point (hope to add a backend plugin system for it sometime). If there is a large demand for this we can reconsider, so closing this and keeping the feature request issue open to gauge interest.

**Comment by stevenschlansker** [comment]
Too bad this PR was not considered. We would have used the icinga / grafana integration but there still seems to be no supported way. If you use a webhook, each user has to write their own custom integration, effectively...

**Comment by davixd** [comment]
> Too bad this PR was not considered. We would have used the icinga / grafana integration but there still seems to be no supported way. If you use a webhook, each user has to write their own custom integration, effectively...

We also try to reach a icinga / grafana integration. So a integrated Icinga2 notification channel right out of the box would be really great.

**Comment by phil-or** [comment]
this feature would be nice!

**Comment by commockl** [comment]
To Bad Feature has not been implemented. We would Like to inject Alerts of trendanalysis to icinga2.

**Comment by chbrem** [comment]
this feature would be very nice!

**Pull request closed without merging**
