### PR TITLE
v7.3.0-beta2 cherry-picks

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Cherry-picks for v7.3.0-beta2.

```
  --------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
--------------------------------------------------------------------
Printing PRs with cherry-pick-needed, in ASC merge date order
--------------------------------------------------------------------
* Add monitoring mixing for Grafana, (#28285), merge-sha: 6002df580ff22f0f5f6df84c074f39bda67cb7b4
* Jaeger: timeline collapser to show icons, (#28284), merge-sha: e93bd23353ff43195bfe0e480e9bcd57b116f95e
* CloudWatch: Missing Namespace AWS/EC2CapacityReservations, (#28309), merge-sha: c9cc82ea5583bbc100f7e3a62ec33b487bcc765b
* API: Fix short URLs, (#28300), merge-sha: a2c7c5b912695361c6f5d852df1ed69ec118b233
* SQLStore: Run tests as integration tests, (#28265), merge-sha: 4937f0daabb42304f1ee544da02bcf35d1336fe1
* Drone: Fix grafana-mixin linting, (#28308), merge-sha: 847dc0bec7bfada0485c9f4c59f769914c7600f8
* Graph: Fix for graph size not taking up full height or width  , (#28314), merge-sha: 448114f649356aabda6f685d00cb54e5414ecb71
* Drone: Use ${DRONE_TAG} in release pipelines, since it should work, (#28299), merge-sha: 392c5bdf7357ebf5b485d51d63d6f08136782cf9
* Explore: respect min_refresh_interval, (#27988), merge-sha: 1760fdd55ddd9c83b6523ad5bb0da11474b16218
* Loki: Base maxDataPoints limits on query type, (#28298), merge-sha: 8db5d750d0cc8d2f5a09fef3d86a1f2355a5de60
* Loki: Run instant query only when doing metric query, (#28325), merge-sha: 8e9181e7d1e9920c25558ad847cabdc1c84c15d7
* Dashboard links: Places drop down list so it's always visible, (#28330), merge-sha: cdab6028e19d451eb4a15644d99c9f8124099cc4
* Add unique ids to query editor fields, (#28376), merge-sha: 1cce13b5018fa718d5486189d45001adc72fab2c
* CloudWatch: Adding support for additional Amazon CloudFront metrics, (#28378), merge-sha: 0e17a15fbd2cabe65087207b347d5a21f95206bd
* Instrumentation: Add counters and histograms for database queries, (#28236), merge-sha: 74d1d3c6a82872ed05e9122d3d47d684797c4f20
* Explore: Fix date formatting in url for trace logs link, (#28381), merge-sha: ad657dcdc3e50a36fc2c1b46a06572354640dcc1
* Instrumentation: Remove status label from database duration histogram, (#28387), merge-sha: b036112444d896ccc8fc636da5d1e98a7177c274
* Instrumentation: Add histogram for request duration, (#28364), merge-sha: edbaa9d681a8619e35e348730da40fe6c39a4c5a
* Docs: Adds basic frontend data request concepts, (#28253), merge-sha: b497063f646058a108c864e1d898a470af62efea
* Grafana/ui: pass html attributes to segment, (#28316), merge-sha: 04c06f228626f5a9ca2f722e5a3a2a9e34801d7c
* FieldColor: Remove inverted color scheme, (#28408), merge-sha: 84992adf2a9a437bbfec0018ed7052c42bb73e5a
* Prometheus: fix parsing of infinite sample values (#28287), (#28288), merge-sha: f3c09e8bcc4c5269580c425eca0d05c379645e72
* Database; Remove database metric feature flag and update changelog, (#28438), merge-sha: 62f5641aa9c8509a4ad3b01471b84b036f231f91
* CloudWatch/Athena - valid metrics and dimensions., (#28436), merge-sha: a71eadf3794ba89e7777974f380b1758961a19bf
--------------------------------------------------------------------
Commands (in order of how they should be executed)
--------------------------------------------------------------------
git cherry-pick -x 6002df580ff22f0f5f6df84c074f39bda67cb7b4
git cherry-pick -x e93bd23353ff43195bfe0e480e9bcd57b116f95e
git cherry-pick -x c9cc82ea5583bbc100f7e3a62ec33b487bcc765b
git cherry-pick -x a2c7c5b912695361c6f5d852df1ed69ec118b233
git cherry-pick -x 4937f0daabb42304f1ee544da02bcf35d1336fe1
git cherry-pick -x 847dc0bec7bfada0485c9f4c59f769914c7600f8
git cherry-pick -x 448114f649356aabda6f685d00cb54e5414ecb71
git cherry-pick -x 392c5bdf7357ebf5b485d51d63d6f08136782cf9
git cherry-pick -x 1760fdd55ddd9c83b6523ad5bb0da11474b16218
git cherry-pick -x 8db5d750d0cc8d2f5a09fef3d86a1f2355a5de60
git cherry-pick -x 8e9181e7d1e9920c25558ad847cabdc1c84c15d7
git cherry-pick -x cdab6028e19d451eb4a15644d99c9f8124099cc4
git cherry-pick -x 1cce13b5018fa718d5486189d45001adc72fab2c
git cherry-pick -x 0e17a15fbd2cabe65087207b347d5a21f95206bd
git cherry-pick -x 74d1d3c6a82872ed05e9122d3d47d684797c4f20
git cherry-pick -x ad657dcdc3e50a36fc2c1b46a06572354640dcc1
git cherry-pick -x b036112444d896ccc8fc636da5d1e98a7177c274
git cherry-pick -x edbaa9d681a8619e35e348730da40fe6c39a4c5a
git cherry-pick -x b497063f646058a108c864e1d898a470af62efea
git cherry-pick -x 04c06f228626f5a9ca2f722e5a3a2a9e34801d7c
git cherry-pick -x 84992adf2a9a437bbfec0018ed7052c42bb73e5a
git cherry-pick -x f3c09e8bcc4c5269580c425eca0d05c379645e72
git cherry-pick -x 62f5641aa9c8509a4ad3b01471b84b036f231f91
git cherry-pick -x a71eadf3794ba89e7777974f380b1758961a19bf
```

### CODE REVIEW

**Comment by papagian** [comment]
@aknuds1 
have you kept the output of the cherry-pick script?
can you add it into the description?

**Comment by aknuds1** [comment]
@papagian Oh I forgot about that :facepalm:.

**Comment by aknuds1** [comment]
@papagian I re-generated the output, and included in the PR description.

**Comment by marefr** [comment]
Seems some PR's are missing cherry pick needed and/or backport, e.g. https://github.com/grafana/grafana/pulls?q=is%3Apr+milestone%3A7.3.0-beta2+is%3Aclosed+-label%3A%22cherry-pick+needed%22+-label%3Abackport+-label%3A%22backport+v7.3.x%22+

Also a couple backport pr's open that haven't been merged. Are these for 7.3 stable or planning to merge after this pr?
- https://github.com/grafana/grafana/pull/28454

Since we don't have CI builds for v7.3.x it could be tricky to verify the builds works as expected before pushing the tag? Meaning would be good to merge any backports to this pr branch to verify pr build works as expected. WDYT?

**Comment by aknuds1** [comment]
@marefr About the build, all backports will be tested as part of the build of this PR?

**Comment by marefr** [comment]
@aknuds1 Sorry if I wasn't clear. I guess you know what would be the best/easiest thing to do. 

But in regards to #28454 we can either merge that directly to v7.3.x now. Then you'll probably have to rebase this pr. Or we can merge #28454 to this branch instead so you don't have to rebase.

Regarding PR's missing cherry pick needed and/or backport we'll cherry pick the needed ones into this pr branch. Maybe have to check with each pr author if they should be included in 7.3

**Comment by aknuds1** [comment]
@marefr No, it's clear. I will merge the missing backport PRs to v7.3.x and rebase this branch.

**Comment by aknuds1** [comment]
Will rebase this after merging some missing backports.

**Comment by aknuds1** [comment]
Ready for review again!

**Comment by papagian** [comment]
I think that this is missing?
* FieldColor: Remove inverted color scheme, (#28408), merge-sha: 84992adf2a9a437bbfec0018ed7052c42bb73e5a

**Comment by aknuds1** [comment]
@papagian I already tried that one:

```
$ git cherry-pick 84992ad                                                                                           
On branch cp-7.3.0-beta2
Your branch is up to date with 'origin/cp-7.3.0-beta2'.

You are currently cherry-picking commit 84992adf2a.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
```

**Comment by papagian** [comment]
> @papagian I already tried that one:
> 
> ```
> $ git cherry-pick 84992ad                                                                                           
> On branch cp-7.3.0-beta2
> Your branch is up to date with 'origin/cp-7.3.0-beta2'.
> 
> You are currently cherry-picking commit 84992adf2a.
>   (all conflicts fixed: run "git cherry-pick --continue")
>   (use "git cherry-pick --skip" to skip this patch)
>   (use "git cherry-pick --abort" to cancel the cherry-pick operation)
> 
> nothing to commit, working tree clean
> The previous cherry-pick is now empty, possibly due to conflict resolution.
> If you wish to commit it anyway, use:
> 
>     git commit --allow-empty
> 
> Otherwise, please use 'git cherry-pick --skip'
> ```

ok, it [is backported](https://github.com/grafana/grafana/pull/28418)

**Review by papagian — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
This looks good :+1: However, just double-checked [7.3.0 milestone](https://github.com/grafana/grafana/pulls?q=is%3Apr+is%3Aclosed+milestone%3A7.3.0) and there's 2 pr's there that was added 2 hours ago by @ivanahuckova. @ivanahuckova was your intent to include those in 7.3-beta2?

**Comment by ivanahuckova** [comment]
@marefr I already reached out to Arve, they can be part of next release. :)

**Comment by aknuds1** [comment]
OK, let's merge then and get the ball rolling.

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
