### PR TITLE
MSSQL: Simplify proxy logic

### LINKED ISSUE #79128: mssql: simplify proxy code
currently, the way we initiate the proxy-support in mssql ( https://github.com/grafana/grafana/blob/9f0fc60477aee5021615914c2fa88c13f1768b49/pkg/tsdb/mssql/proxy.go#L20 ) registers a completely new database driver.

this is for historical reasons (we used the xorm-package, but we do not anymore), now it should be possible to only override the dialer, see https://github.com/grafana/grafana/pull/64630#issuecomment-1470031067

### PR DESCRIPTION
**Pull request by aangelisc**
As we've moved away from Xorm there is no need to create a new driver when attempting to use the secure socks proxy. Instead, the dialer can be overridden by the custom creation of the database connector.

I've shamelessly mimicked the logic used in the Postgres data source for this.

Fixes #79128 

For convenience I have created two SQL Server resources in Azure. One for testing Azure authentication and one for testing the PDC connection.

Steps to test:
- Login to the Ephemeral instance (link in comments below).
- Either review the two MSSQL data sources and ensure querying and other functionality works as expected or create your own for testing.

If you require the credentials for connecting to any VMs drop me a pm 😊

### CODE REVIEW

**Comment by bossinc** [comment]
@aangelisc Can i get access to the ephemeral instance? thx dawg

**Comment by gabor** [comment]
nice work 👍 , the diff looks fine.

**Review by bossinc — APPROVED** [review]
:tada:

**Pull request merged**
