### PR TITLE
AuthN: Set uid during authentication

### PR DESCRIPTION
**Pull request by kalleep**
**What is this feature?**
Follow up from https://github.com/grafana/grafana/pull/87206. Change to store `NamespaceID` type for uid:s on `authn.Identity` struct. Make sure this value is set during sync and later set for `SignedInUser` after authentication is performed.

I also removed `GetNamespacedUID` from `Requester` interface and changed to use `GetUID` instead.

Fixes https://github.com/grafana/identity-access-team/issues/680

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ryantxu** [comment]
nice!  Is this the UID we should use when saving things in the new app-platform?  Currently we are sticking the internal id as a string, but this seems like a much better path

**Review by IevaVasiljeva — APPROVED** [review]
LGTM

**Comment by kalleep** [comment]
> nice! Is this the UID we should use when saving things in the new app-platform? Currently we are sticking the internal id as a string, but this seems like a much better path

Yes I think we wan't to store UID:S instead of the sequential ids. Are you currently storing with namespace prefix e.g. `user:2`, `service-account:2` so we can map it to different kinds? 

Also right now we sign our id tokens with sequential version of namespace id (in subject). We probably need to add uid:s to those tokens as well. Another thing to consider is that all current api:s for grafana only knows how to handle sequential ids but not sure if that is a problem when talking about app-platform.

**Comment by ryantxu** [comment]
> Are you currently storing...

We have a stub not, waiting for a long term solution :).  (currently "user:%d", internalId)

> ... not sure if that is a problem when talking about app-platform. ...

We need to save some string indicating who changed what when for each resource.  I think saving the type:uid makes the most sense, but we do need to make sure uid is available in every request before we can do this consistently.

**Pull request merged**
