### PR TITLE
Cloudflare colo lookup Gazetteer

### PR DESCRIPTION
**Pull request by 0xste**
**What is this feature?**

Added Cloudflare COLO information as a gazetteer - this seems to be different to what we'd see from airports.geojson lookup that's included.

The data is held here -> https://speed.cloudflare.com/locations

**Why do we need this feature?**

To allow for lon/lat lookups for cloudflare sourced COLO codes

Fixes https://github.com/grafana/support-escalations/issues/6673 

Please check that:
- [ ✅ ] It works as expected from a user's perspective.
- [ ❌ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ❌ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by 0xste** [comment]
PR is WIP - i need to add in the wikis etc and perform some validation etc, but thought i'd raise early for some discussion on this -> i do have a script that i use to generate the geojson format file form the cloudflare speed API if that'd be useful to put into this repo (somewhere)

**Comment by ryantxu** [comment]
@0xste -- nice.  note you can reference any gejson by typing it into the selector, so it should not be necessary to have this in the main software for you to get what you need working.

I am nervous about trying to keep cloudflates colo database up-to-date in the software vs pointing to a file hosted anywhere else that could be managed more efficiently

**Comment by ryantxu** [comment]
@0xste -- it looks like the gazetter already just works with the data directly from cloudflare:
image

just paste the URL into the gazetter and it tries to make a lookup.  I'll close this PR, but feel free to holler if somethign is missing

**Comment by 0xste** [comment]
Hi Ryan, thanks for the info here, wasn't aware it would let me parse any geojson! Definitely does the job for my requirements.

---
I'm having some issues when trying to apply this, looks like it's finding the geojsons in the Gazetteer window

Screenshot 2023-07-10 at 23 51 30

But when i apply the lookup to some data, it only populates the first 6 records (pretty consistently it seems)

Screenshot 2023-07-10 at 23 52 29

I can see the other records in cloudflare's json, seems somewhat odd that it's partially filling the data.

I checked the browser console and it looks like it may be making some kind of audit request to https://api-iam.intercom.io/messenger/web/events stating it's reaching some kind of limit?

```
{
    "type": "error.list",
    "request_id": "004bueluj0kvabmbii20",
    "errors": [{
        "code": "422",
        "message": "A user cannot be associated with more than 500 events and the workspace cannot have more than 200 active event names"
    }]
}
```

Would appreciate any pointers on how to proceed on this 🙏

**Comment by nmarrs** [comment]
@ryantxu do you have any insight on whether or not we have rate limits internally or is this just cloudflare limiting the amount of data that can be retrieved?

**Comment by nmarrs** [comment]
Hey @0xste!

@drew08t and I dug into this today and it seems there was a bug in the field lookup transform code - [created a PR addressing it which seems to fix the issue](https://github.com/grafana/grafana/pull/71805)

**Comment by ryantxu** [comment]
> A user cannot be associated with more than 500 events...

This is not an error from grafana -- if you are hitting this from cloudflare, maybe stick the file elsewhere 🤷🏻

**Pull request closed without merging**
