### PR TITLE
Configuration to handle enable/disable requirement of email in oauth.

### LINKED ISSUE #13549: Generic OAuth support users without email
### What Grafana version are you using?
v5.1.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
CentOS 7.5
### What did you do?
Do Generic OAuth with Keycloak, with no "email" set in Keycloak "User" -> "Details"
### What was the expected result?
OAuth goes correctly, forward from Keycloak auth page to Grafana
### What happened instead?
Forward to Grafana error page, with "login.OAuthLogin(get info from generic_oauth)" on UI
and, in grafana log, following error is shown,
t=2018-10-02T12:45:38+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="Error getting user info: default backend - 404"

### PR DESCRIPTION
**Pull request by pwcorbett**
Add parameter to enable OAuth without requiring an email.

Currently login fails if your OAuth user does not have an email or the OAuth provider does not support the `apiUrl + "/emails"` endpoint.

The default is for an email to be required `email_required = true`

Closes #13549

### CODE REVIEW

**Comment by mzaret** [comment]
Any word on whether or not this is going to be implemented? Hoping to finish OAuth integration with a provider that doesn't supply the email endpoint.

**Comment by pwcorbett** [comment]
I have had no word. I'm hoping someone will look at it soon.

**Comment by pwcorbett** [comment]
@xlson Could you review this?

**Comment by dtrejod** [comment]
➕ 1 for getting this PRed. @torkelo, @bergquist seem active in this repo.

**Comment by okushchenko** [comment]
@marefr can you take a look at this once again, please? This issue is really blocking an integration of Grafana with some OAuth providers.

**Comment by Lord-Y** [comment]
It's been a while since it's opened. Any plan to fix conflicts soon?

**Comment by pwcorbett** [comment]
@Lord-Y Conflicts have been fixed.

**Comment by marefr** [comment]
@pwcorbett thank you for the contribution. Currently the issue doesn't have a lot upvotes and we currently think that not having email returned from oauth provider is not a common thing. Therefore we're not going to accept this PR for now.

**Comment by okushchenko** [comment]
@marefr it's the 7th most upvoted PR out of 100 open PRs, and the 21st most upvoted issue out of 2000 open issues. Moreover, the code change itself is pretty small.

**Comment by haarchri** [comment]
any progress here ?

**Comment by jiangytcn** [comment]
What's the decision on this PR ? 
The PR is quite useful as our Oauth server doesn't implement the emails endpoint

**Comment by MatthewMiles0** [comment]
Can this be reopened? This is clearly a wanted feature

**Comment by t4ir1** [comment]
Here trying to give some visibility to this issue!

**Pull request closed without merging**
