### PR TITLE
Docs: Added command to upgrade instructions

### PR DESCRIPTION
**Pull request by alejandroscf**
**What this PR does / why we need it**:
I added a missing apt command in the debian/Ubuntu upgrade instructions.
**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by oddlittlebird** [comment]
@xlson, what say you? I tested these instructions extensively without this command.

**Comment by alejandroscf** [comment]
I think it was simply an typo between 'update' and 'upgrade'. In the previous paragraph (line 80) it says:
> If you installed Grafana from our APT repository, then Grafana will automatically update when you run apt-get **upgrade** to upgrade all system packages.

Maybe with 'sudo apt-get upgrade' it will be enough for the documentation, but for me looks more complete with the 'sudo apt-get update' in order to be sure the package index is updated with the latest releases before trying to upgrade.

**Review by xlson — APPROVED** [review]
Good catch! Thanks for contributing :)

**Comment by xlson** [comment]
@oddlittlebird the rest of it is correct, but the upgrade part is needed for a newer version to be installed if the one previously installed on the local system is older. And the update only upates the information about what version are available, not the actual install.

**Pull request merged**
