### PR TITLE
Spike - BrowseDashboards but with window virtualisation

### PR DESCRIPTION
**Pull request by joshhunt**
Experimental new browse dashboards page, but the virtual list scrolls the window. This will free up space concerns, especially on mobile.

It should also use entirely generated RTK Query api clients for api state management.

 - `newNewBrowseDashboards` feature toggle
 - New generated API slice for apis for browse dashboards
 - NewBrowseDashboardsPage which has virtualised window scrolling
 - Using `msw` for mocked API responses

### CODE REVIEW

**Comment by tomratcliffe** [comment]
MSW work is here as well if you would like this 😌 
https://github.com/grafana/grafana/pull/89223

**Comment by joshhunt** [comment]
I'm pretty happy with the approach and work here, but we're not going to merge this in and continue on it in this form.

In the near future, it's likely we have a much more coordinated effort for a new Browse Grafana UI, which the work here can be used for!

**Pull request closed without merging**
