### PR TITLE
Changed how react panels store their options

### PR DESCRIPTION
**Pull request by torkelo**
While working on the new Bar Gauge panel I discovered some big issues with how react panels store their options and how defaults are exposed. Think solving these before in v6 will be important as it's going to be more difficult to do later. 

* [x] Changes to store react panel options inside a "options" panel property instead of a "options-`<panel-id>`"  property. Added migration for gauge panel. 
* [x] Fix an issue with how panel defaults are exposed (currently a bug with gauge panel) where it got nested options in the json. 

# React Panel exports

The PluginExports interface is a bit messy with many components that can be exported for both panel and data source plugins. There is no interface for panels only for example. And for every new thing we want for example panels to expose to grafana (components, functions, or defaults) we would have to add to this messy interface. And there would be no way to provide typings & auto complete for PluginExports to plugin authors as there is no way specify an interface for what a module can/should export. 

So to fix this I created the ReactPanelPlugin class that panel plugins can now export an instance of. This will contain all panel plugin componets and can act as place where panel plugins can define defaults, migrations, and custom compatibility handling of options (keep settings when switching panels). 

Before: 
```ts
export { 
  GaugePanel as Panel, 
  GaugePanelOptions as PanelOptions, 
  defaultProps as PanelDefaults
};
```

After: 
```ts
export const reactPanel = new ReactPanelPlugin<GaugeOptions>(GaugePanel);
reactPanel.setEditor(GaugePanelEditor);
reactPanel.setDefaults(defaults);
```

Also renamed PanelOptionsProps to PanelEditorProps and the options components are now suffixed Editor instead of Options. Reasoning here is that the GaugePanelOptions (UI component), GaugeOptions (type for panel options) was too similar and confusing, having the suffix Editor for the UI component more clearly sets it apart from the panel options type. 

These are some big changes that I really wish not have to do so late in the beta. We could wait to 6.1 and break every new react plugin that will be developed for 6.0, but that feels bad but is an option. 

The bug impact here is relatively minor and will only impact current react panels (Gauge).

### CODE REVIEW

**Comment by ryantxu** [comment]
FYI, I hit this issue with #15313

On the first load, properties exist on `props.options.options` rather than `props.options`?!

I added this hack just to get things to work:
```
    // TODO thre must be some better way to start with defualt options!
    let opts = props.options;
    if (opts && opts['options']) {
      opts = opts['options'];
      console.log('WEIRD!', opts);
    }
```

**Comment by torkelo** [comment]
This was squashed to aid cherry picking, so only cherry pick abddb442a188101e86d6b160f830527cd8b5afb5

**Comment by WillDeuz** [comment]
Hi ! is this also related to the plugins like Zabbix which credentials are being exposed in the frontend ?

Thanks!

**Comment by marefr** [comment]
@WillDeuz no. Please see https://github.com/alexanderzobnin/grafana-zabbix/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+encrypt

**Pull request merged**
