### PR TITLE
CDN: Add CDN upload step to enterprise and release pipelines

### PR DESCRIPTION
**Pull request by torkelo**
Also updates the ContentDeliveryURL to not include public/ as the is not part of the CDN path. 

* Updates build-pipeline

### CODE REVIEW

**Comment by torkelo** [comment]
@aknuds1 same problem again :( built and uploaded 0.5.38 the same you did 

Why does the docker build images action not find it while the other steps can?  What os are you building on?

**Comment by aknuds1** [comment]
@torkelo I'm currently doing it on OSX, but have been doing it on Linux no problem. I really don't know what goes wrong in your case, but I see you haven't uploaded any Windows binary. I've uploaded the Windows binary, and will try again to see if it helps.

**Comment by torkelo** [comment]
But the error is not for the windows binary it just missing /bin/grabpl 

gsutil says it uploaded, tried again now 
Screenshot from 2021-02-10 08-04-14

**Comment by aknuds1** [comment]
Uploaded a statically linked 0.5.38 Linux binary and restarted build.

**Comment by aknuds1** [comment]
@torkelo build is fixed :)

**Pull request merged**
