### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
**What this PR does / why we need it**:

This fixes a number of spelling errors.

**Special notes for your reviewer**:

Misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

It reported: https://github.com/jsoref/grafana/commit/ce17ad538a329a5a1081a2a5fd6d143a383f1eff#commitcomment-39000726

And it validated that the changes in this PR made it happy: https://github.com/jsoref/grafana/commit/db4053e585b090b20d0ea75004d52967ed419f55

--
I'm aware that this has merge conflicts and that there were new typos introduced between my branch point and now.

The action is *NOT* included in this PR. It's used separately (partially by me just to validate that I haven't missed things, and also to show that one could add it if one wanted to).

Note: GitHub doesn't like PRs that exceed 250 commits. For fun, this PR was made using the GitHub website (all commits are signed by its key).

Some projects ask for large PRs to be split. It's possible to split by:
* comments
* local variables
* local functions
* APIs
* UI strings
* Debug messages

That said, if I can avoid doing that, I'd be quite happy not to :-).

### CODE REVIEW

**Comment by marcusolsson** [comment]
This is golden! 🥇

**Comment by aknuds1** [comment]
This PR is enormous, it would be preferable if you split it into several smaller ones.

**Comment by aknuds1** [comment]
Sorry, we can't accept this PR, it encompasses far too much at once. Also, it adds a GitHub Action right? That shouldn't be part of a PR to fix spelling errors.

**Comment by jsoref** [comment]
It doesn't add the Action, it's intentionally separate.

**Comment by aknuds1** [comment]
Ah, you're right, I was diffing against the wrong branch (spelling-with-spellcheck instead of spelling) I see now. It doesn't change the fact that the PR is far too large and unfocused though. I would suggest you make a PR targeting only documentation first.

**Comment by jsoref** [comment]
Splitting out that way may be possible, slices by directory sometimes work. They often explode though if something is both misspelled and documented as-is. I can try that slice and see what happens.

**Comment by jsoref** [comment]
In this case, that chunk won't take much out of the PR:
```
$ git diff master..spelling --stat -- docs
 docs/sources/auth/generic-oauth.md         |  2 +-
 docs/sources/auth/google.md                |  2 +-
 docs/sources/guides/whats-new-in-v3.md     |  2 +-
 docs/sources/guides/whats-new-in-v4-1.md   |  2 +-
 docs/sources/guides/whats-new-in-v6-0.md   |  2 +-
 docs/sources/guides/whats-new-in-v6-6.md   |  2 +-
 docs/sources/http_api/playlist.md          | 24 ++++++++++++------------
 docs/sources/installation/configuration.md |  2 +-
 8 files changed, 19 insertions(+), 19 deletions(-)
```
vs.
```
...
 313 files changed, 602 insertions(+), 603 deletions(-)
```

**Comment by sakjur** [comment]
This is an awesome initiative and it would be great to get most of this merged, a lot of it is just silly misspellings in comments, internal variable names, and documentation. Parts of what isn't in that category is unfortunately some external APIs 😞

I found a few cases where the API is broken by the spellfixes, I've pasted one example below where we break [dateTimeFormatWithAbbrevation from `@grafana/data`](https://grafana.com/docs/grafana/latest/packages_api/data/datetimeformatwithabbrevation/). The spelling is undoubtedly improved, but merging it as-is would break the API for current users without warning.

We'll need to isolate anything that breaks any kind of APIs to separate PRs so they can be reviewed separately by the code owners of that component and worked on in isolation. If we break the API we want it to be clearly marked in the changelogs and we want to be very aware about doing it.

```diff
diff --git a/packages/grafana-data/src/datetime/formatter.ts b/packages/grafana-data/src/datetime/formatter.ts
index 5d0034e0af73..58406e1f7dbb 100644
--- a/packages/grafana-data/src/datetime/formatter.ts
+++ b/packages/grafana-data/src/datetime/formatter.ts
@@ -24,10 +24,10 @@ export const dateTimeFormatISO: DateTimeFormatter = (dateInUtc, options?) =>
 export const dateTimeFormatTimeAgo: DateTimeFormatter = (dateInUtc, options?) =>
   toTz(dateInUtc, getTimeZone(options)).fromNow();
 
-export const dateTimeFormatWithAbbrevation: DateTimeFormatter = (dateInUtc, options?) =>
+export const dateTimeFormatWithAbbreviation: DateTimeFormatter = (dateInUtc, options?) =>
   toTz(dateInUtc, getTimeZone(options)).format(`${DEFAULT_DATE_TIME_FORMAT} z`);
 
-export const timeZoneAbbrevation: DateTimeFormatter = (dateInUtc, options?) =>
+export const timeZoneAbbreviation: DateTimeFormatter = (dateInUtc, options?) =>
   toTz(dateInUtc, getTimeZone(options)).format('z');
```

**Comment by jsoref** [comment]
@sakjur: a couple of possible approaches:

1. Include a shim for 7.0 and break it for 8.0
2. Just split out the changes into a distinct PR

Both are fairly manageable.

Assuming API items always have `export` in them, doing either is fairly easy...

```sh
$ git diff master..spelling |egrep '^diff|^[-+]\s*export'|egrep -B1 export
diff --git a/packages/grafana-data/src/datetime/formatter.ts b/packages/grafana-data/src/datetime/formatter.ts
-export const dateTimeFormatWithAbbrevation: DateTimeFormatter = (dateInUtc, options?) =>
+export const dateTimeFormatWithAbbreviation: DateTimeFormatter = (dateInUtc, options?) =>
-export const timeZoneAbbrevation: DateTimeFormatter = (dateInUtc, options?) =>
+export const timeZoneAbbreviation: DateTimeFormatter = (dateInUtc, options?) =>
--
diff --git a/packages/grafana-data/src/datetime/rangeutil.ts b/packages/grafana-data/src/datetime/rangeutil.ts
-export const describeTimeRangeAbbrevation = (range: TimeRange, timeZone?: TimeZone) => {
+export const describeTimeRangeAbbreviation = (range: TimeRange, timeZone?: TimeZone) => {
--
diff --git a/packages/grafana-data/src/transformations/standardTransformersRegistry.ts b/packages/grafana-data/src/transformations/standardTransformersRegistry.ts
-export interface TransformerRegistyItem<TOptions> extends RegistryItem {
+export interface TransformerRegistryItem<TOptions> extends RegistryItem {
-export const standardTransformersRegistry = new Registry<TransformerRegistyItem<any>>();
+export const standardTransformersRegistry = new Registry<TransformerRegistryItem<any>>();
--
diff --git a/packages/grafana-toolkit/src/plugins/workflow.ts b/packages/grafana-toolkit/src/plugins/workflow.ts
-export const agregateWorkflowInfo = (): WorkflowInfo => {
+export const aggregateWorkflowInfo = (): WorkflowInfo => {
-export const agregateCoverageInfo = (): CoverageInfo[] => {
+export const aggregateCoverageInfo = (): CoverageInfo[] => {
-export const agregateTestInfo = (): TestResultsInfo[] => {
+export const aggregateTestInfo = (): TestResultsInfo[] => {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/CalculateFieldTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/CalculateFieldTransformerEditor.tsx
-export const calculateFieldTransformRegistryItem: TransformerRegistyItem<CalculateFieldTransformerOptions> = {
+export const calculateFieldTransformRegistryItem: TransformerRegistryItem<CalculateFieldTransformerOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/FilterByNameTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/FilterByNameTransformerEditor.tsx
-export const filterFieldsByNameTransformRegistryItem: TransformerRegistyItem<FilterFieldsByNameTransformerOptions> = {
+export const filterFieldsByNameTransformRegistryItem: TransformerRegistryItem<FilterFieldsByNameTransformerOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/FilterByRefIdTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/FilterByRefIdTransformerEditor.tsx
-export const filterFramesByRefIdTransformRegistryItem: TransformerRegistyItem<FilterFramesByRefIdTransformerOptions> = {
+export const filterFramesByRefIdTransformRegistryItem: TransformerRegistryItem<FilterFramesByRefIdTransformerOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/LabelsToFieldsTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/LabelsToFieldsTransformerEditor.tsx
-export const labelsToFieldsTransformerRegistryItem: TransformerRegistyItem<LabelsToFieldsOptions> = {
+export const labelsToFieldsTransformerRegistryItem: TransformerRegistryItem<LabelsToFieldsOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/OrganizeFieldsTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/OrganizeFieldsTransformerEditor.tsx
-export const organizeFieldsTransformRegistryItem: TransformerRegistyItem<OrganizeFieldsTransformerOptions> = {
+export const organizeFieldsTransformRegistryItem: TransformerRegistryItem<OrganizeFieldsTransformerOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/ReduceTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/ReduceTransformerEditor.tsx
-export const reduceTransformRegistryItem: TransformerRegistyItem<ReduceTransformerOptions> = {
+export const reduceTransformRegistryItem: TransformerRegistryItem<ReduceTransformerOptions> = {
--
diff --git a/packages/grafana-ui/src/components/TransformersUI/SeriesToFieldsTransformerEditor.tsx b/packages/grafana-ui/src/components/TransformersUI/SeriesToFieldsTransformerEditor.tsx
-export const seriesToFieldsTransformerRegistryItem: TransformerRegistyItem<SeriesToColumnsOptions> = {
+export const seriesToFieldsTransformerRegistryItem: TransformerRegistryItem<SeriesToColumnsOptions> = {
--
diff --git a/packages/grafana-ui/src/utils/standardTransformers.ts b/packages/grafana-ui/src/utils/standardTransformers.ts
-export const getStandardTransformers = (): Array<TransformerRegistyItem<any>> => {
+export const getStandardTransformers = (): Array<TransformerRegistryItem<any>> => {
--
diff --git a/public/app/features/dashboard/state/reducers.ts b/public/app/features/dashboard/state/reducers.ts
-export const dashboardReducer = dashbardSlice.reducer;
+export const dashboardReducer = dashboardSlice.reducer;
--
diff --git a/public/app/features/users/SignupInvited.tsx b/public/app/features/users/SignupInvited.tsx
-export default hot(module)(connect(mapStateToProps, mapDispatchToProps)(SingupInvitedPageUnconnected));
+export default hot(module)(connect(mapStateToProps, mapDispatchToProps)(SignupInvitedPageUnconnected));
--
diff --git a/public/app/features/variables/adhoc/actions.ts b/public/app/features/variables/adhoc/actions.ts
-export const changeFilter = (id: string, update: AdHocVariabelFilterUpdate): ThunkResult<void> => {
+export const changeFilter = (id: string, update: AdHocVariableFilterUpdate): ThunkResult<void> => {
--
diff --git a/public/app/features/variables/adhoc/reducer.ts b/public/app/features/variables/adhoc/reducer.ts
-export interface AdHocVariabelFilterUpdate {
+export interface AdHocVariableFilterUpdate {
--
diff --git a/public/app/features/variables/state/selectors.ts b/public/app/features/variables/state/selectors.ts
-export const getNewVariabelIndex = (state: StoreState = getState()): number => {
+export const getNewVariableIndex = (state: StoreState = getState()): number => {
--
diff --git a/public/app/plugins/datasource/dashboard/index.ts b/public/app/plugins/datasource/dashboard/index.ts
-export { SHARED_DASHBODARD_QUERY } from './types';
+export { SHARED_DASHBOARD_QUERY } from './types';
--
diff --git a/public/app/plugins/datasource/dashboard/types.ts b/public/app/plugins/datasource/dashboard/types.ts
-export const SHARED_DASHBODARD_QUERY = '-- Dashboard --';
+export const SHARED_DASHBOARD_QUERY = '-- Dashboard --';
```

**Pull request closed without merging**
