### PR TITLE
Auth: Add missing skipOrgRoleSync property to SocialBase for GenericOAuth

### PR DESCRIPTION
**Pull request by eleijonmarck**
**What is this feature?**
 Customers using GenericOAuth are still able to change the orgrole for their users until login. This sets the skipOrgRoleSync correctly for genericOAuth providers that have been setup, we were missing this field when populating the social struct.

Adds the skipOrgRoleSync field to the socialBase for GenericOAuth.

**Why do we need this feature?**
Upon login again from the user, it would reset their organization role to the defaultRole specified. This makes it so that if we change the org role to editor, it persists throughout login from the user (as expected from the feature)

Before
image

After
image

**Who is this feature for?**

**Which issue(s) does this PR fix?**:
https://github.com/grafana/grafana/issues/69639

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by Jguer — APPROVED** [review]

**Review by IevaVasiljeva — COMMENTED** [review]
I think we're also missing it for Google, could you please add it?

**Comment by eleijonmarck** [comment]
@IevaVasiljeva implemented but removed due to the fact that google does not sync the roles. We only submit back an emptyRole.

We should perhaps have a look at this 🤔 
https://github.com/grafana/grafana/blob/1b93f3c0ab2f7fcf4ccf16d9c54bac4e719d42c1/pkg/login/social/google_oauth.go#L66

**Comment by tobhv** [comment]
Hello, thx for this. since i think the commit is related to an issue part of 10.1.0 as pointed out here: https://github.com/grafana/grafana/issues/73752 
And as far as i could see the commit https://github.com/grafana/grafana/pull/72752 is not part of the 10.1.0 release.
Can you perhaps share whether indeed this commit is not part of 10.1.0 and when it will be part of a grafana release ?

thanks!

tobias.

**Comment by eleijonmarck** [comment]
> Hello, thx for this. since i think the commit is related to an issue part of 10.1.0 as pointed out here: https://github.com/grafana/grafana/issues/73752 
> And as far as i could see the commit https://github.com/grafana/grafana/pull/72752 is not part of the 10.1.0 release.
> Can you perhaps share whether indeed this commit is not part of 10.1.0 and when it will be part of a grafana release ?
> 
> thanks!
> 
> tobias.

We have backported this to 10.1.X which means it was included in the latest patch release. I am not able to check the release currently but if you update to 10.1X 

Are you looking at the changelog perhaps? It should be included, the backport of this was deemed to little to be part of the changelog.

**Comment by tobhv** [comment]
hey. thanks for response.
i checked: 
- changelog and 2 other things:
- a reference to your commits in https://github.com/grafana/grafana/tree/v10.1.0/pkg/login/social 
- https://github.com/grafana/grafana/compare/v10.1.0...release-9.5.8 
in all cases i could not find a reference to your commit.
Anything i missed ?

**Comment by eleijonmarck** [comment]
@tobhv hmm i can see that now. it should have been included. let me check on this tomorrow and how come it is in the `v10.1.x` [branch] but was not included in the release of `v10.1.0`.

https://github.com/grafana/grafana/tree/v10.1.x/pkg/login/social

**Pull request merged**
