### PR TITLE
Docs: URL update to Relref to repair broken links

### LINKED ISSUE #22378: Docs feedback: /administration/provisioning.md
The link behind  `provisioning/dashboards` under [Dashboards](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) is pointing to a non existing page. (https://grafana.com/installation/configuration#provisioning)

### PR DESCRIPTION
**Pull request by RobinJoe**
**What this PR does / why we need it**:

Fixes broken URL links between documents by rewriting the Markdown URL to Relref format, which Hugo can read to build the website and form the links.

**Which issue(s) this PR fixes**:

https://github.com/grafana/grafana/issues/22378

Fixes #22378

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
This PR is more significant than just updating links though, since it introduces a Markdown contributor's guide?

**Comment by aknuds1** [comment]
I pushed a sync with Grafana master to the branch, in order to get around some CI issues.

**Comment by oddlittlebird** [comment]
We already have a markdown style guide. https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-markdown-guide.md

**Comment by RobinJoe** [comment]
> This PR is more significant than just updating links though, since it introduces a Markdown contributor's guide?
> 
> @marcusolsson @oddlittlebird What do you think about the style guide being added?

You're right, it is adding significantly more. tldr: we can merge this now, or I can try again with a cleaned up fork?

Longer version:
My PR added older commits because my local fork was ahead of the upstream repository. I just ran ``$ git merge --ff-only origin master`` on my local copy of my grafana fork, followed by ``$ git push -f origin HEAD^:master``. This appears to have cleaned the extra commits - the style guide and others - from my fork. It should keep future commits free of old changes. 

As for this one, we can either close this branch, and I will re-apply the changed reref, but with a cleaned up fork, or merge the changes added in your https://github.com/grafana/grafana/pull/23783/commits/262ef4c9c383ca89338fc00618f570e1417e8596 synch to Grafana Master.

**Comment by aknuds1** [comment]
@RobinJoe Why don't you just remove contribute/style-guides/markdown-style-guide.md from this branch? I.e., `git rm contribute/style-guides/markdown-style-guide.md && git commit -m"Remove stale file" contribute/style-guides/markdown-style-guide.md`.

**Comment by aknuds1** [comment]
@oddlittlebird You want to give it another look?

**Review by oddlittlebird — APPROVED** [review]
LGTM! Thanks for contributing!

**Pull request merged**
