### PR TITLE
Table: Fix text wrapping applying to wrong field

### PR DESCRIPTION
**Pull request by codeincarnate**
This PR fixes a customer reported issue in which text wrapping will be applied to the incorrect field. 

Previously the code had been looking directly at configuration values on each field. However, the default configuration is applied to all fields so this would incorrectly cause the last field of the frame to be the one selected for text wrapping.

This updates that behavior so that if enabled at the top level the field with the longest text will be selected for text wrapping. Otherwise, the last field that is matched by field overrides and with text wrapping enabled will be used to wrap text.

### Before

Screenshot 2024-09-25 at 12 54 48 PM

### After

Screenshot 2024-09-25 at 12 48 28 PM

Dashboard for testing:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 989,
  "links": [],
  "panels": [
    {
      "datasource": {
        "default": true,
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto",
              "wrapText": true
            },
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "cellHeight": "sm",
        "footer": {
          "countRows": false,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "11.3.0-pre",
      "targets": [
        {
          "csvContent": "time,long_message,short_message\n1,\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\",short\n2,\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\",short\n3,\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\",short\n4,\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\",short\n5,\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\",short",
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "Asia/Tokyo",
  "title": "Text Wrapping Issue",
  "uid": "adyym2icp845cd",
  "version": 1,
  "weekStart": ""
}
````

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by adela-almasan** [comment]
Hey @codeincarnate, I'm noticing an odd behavior on resizing, sorting but also when the long text is not in the first or last position. But overall definitely an improvement! 

https://github.com/user-attachments/assets/b8a00dd9-8933-4ea2-a9dd-dbce6a3ba886

**Review by Develer — COMMENTED** [review]
LGTM! 👍 

This jumping thing can be annoying, but it can be something for follow-up:

https://github.com/user-attachments/assets/9c585bc1-5e40-4cd2-bca3-54077cbc6e52

**Comment by Develer** [comment]
> LGTM! 👍
> 
> This jumping thing can be annoying, but it can be something for follow-up:
> 
>  Screen.Recording.2024-09-27.at.14.31.04.mov

`word-break: break-word;` is added on cell hover, so that causes the "jumping" issue. I can address it in a separate PR.

**Comment by codeincarnate** [comment]
@adela-almasan not seeing the issue when re-sizing the editor here. I do see it happening when re-sizing columns, currently it's the way the virtualizer updates size with it happening at the end of drag event. As for the sort issue, I _believe_ we're tracking that elsewhere. I'd suggest another PR there and at least get this bug fixed. 

What do you think?

**Comment by drew08t** [comment]
One approach to consider here is to add the field selector used for footer calculations, instead of only applying wrapping to the longest field (or via overrides):

image
image

**Comment by Develer** [comment]
> One approach to consider here is to add a field selector, similar to what's used for footer calculations, instead of only applying wrapping to the longest field (or via overrides):
> 
> image image
> 
> Default behavior would be to apply to all fields.

@drew08t I like the idea, we can explore and work on this as a follow-up task.
Also, it would be great to have @staton-hyse11 opinion on this.

**Comment by staton-hyse11** [comment]
I agree that this should default to all fields.

**Comment by adela-almasan** [comment]
I think there's an index mismatch somewhere - the 3rd row seem to be accommodating the longer text, but the longer text is actually at the bottom of the table. When resizing you can't read the beginning of the text 😕 

https://github.com/user-attachments/assets/9fdc3588-6ffd-41c0-8791-8225834dce8c

**Comment by Develer** [comment]
> I think there's an index mismatch somewhere - the 3rd row seem to be accommodating the longer text, but the longer text is actually at the bottom of the table. When resizing you can't read the beginning of the text 😕
> 
>  Screen.Recording.2024-10-17.at.10.52.31.AM.mov

I remember Kyle mentioned this as a major ReactTable issue - to sync ReactTable internal index and grafana field index. I'll look at it closer, thank you for noticing.

**Comment by Develer** [comment]
> > I think there's an index mismatch somewhere - the 3rd row seem to be accommodating the longer text, but the longer text is actually at the bottom of the table. When resizing you can't read the beginning of the text 😕
> > Screen.Recording.2024-10-17.at.10.52.31.AM.mov
> 
> I remember Kyle mentioned this as a major ReactTable issue - to sync ReactTable internal index and grafana field index. I'll look at it closer, thank you for noticing.

Can't reproduce it though:

https://github.com/user-attachments/assets/8bdd348b-d665-42b8-ac73-969806916241

**Review by adela-almasan — APPROVED** [review]
🚀

**Pull request merged**
