### PR TITLE
Grafana UI: Create Text component use case example

### LINKED ISSUE #68246: Use `Text` component in `DashboardEmpty` to show how it should be used
We want to use the `DashboardEmpty` page as an example to show how the experimental component, `Text`, should be used.

Captura de pantalla 2023-05-10 a las 18 01 01

### PR DESCRIPTION
**Pull request by eledobleefe**
**What is this feature?**
We want to indicate how the `Text` component should be used through a real use case.

**Why do we need this feature?**
To show the use of the experimental component, `Text`.

**Who is this feature for?**
Everybody

**Which issue(s) does this PR fix?**:
Fixes #68246 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by torkelo** [comment]
I think we missed exporting Text component from the unstable file, I could not import it from the App, only the H1-6 etc are exported not the component itself

**Comment by eledobleefe** [comment]
> I think we missed exporting Text component from the unstable file, I could not import it from the App, only the H1-6 etc are exported not the component itself

Hi @torkelo!
We did that on purpose. After discussing it ([see messages here](https://github.com/grafana/grafana/pull/66932#discussion_r1180115699)), we agreed not to expose the Text component but do so with `H1`, `H2`, and so on. We also created a `TextModifier` so users can modify, for example, the font weight of a word inside a phrase.

**Comment by torkelo** [comment]
@eledobleefe thats a real shame, find using the Text component much more natural and easy. Like what would I use for normal text? I don't end to import a P component or Span component, please just export the Text component , using that feels much better than importing a Span component

**Comment by eledobleefe** [comment]
> @eledobleefe thats a real shame, find using the Text component much more natural and easy. Like what would I use for normal text? I don't end to import a P component or Span component, please just export the Text component , using that feels much better than importing a Span component

Hi @torkelo,
This is an 'experimental' component and what we want to accomplish while it is in the _unstable_ package is gathering feedback about it. One topic we are debating is whether to use H1-H6/P/Span components or Text with `as` prop, but don't want to have to export both. Besides really appreciating your comment, we will take it into account for this process.

**Comment by JoaoSilvaGrafana** [comment]
> ok, I would never think of imporing a H3 or a Span component form a component library. never seen a component library have them.

Thanks for your feedback @torkelo ! There are a few component libraries that do it, for instance [MongoDB](https://www.mongodb.design/component/typography/example/) (you can see it if you press the show code bit) and [Uber](https://baseweb.design/components/typography/) which exports not the element names themselves but their own concepts like HeadingLarge, HeadingMedium, HeadingSmall, etc.

In the original PR there was a debate about keeping it as `Text` or having one component per element (you can see it [here](https://github.com/grafana/grafana/pull/66932#discussion_r1172867565)) and the fact that we had different opinions is part of the reason why we put this component in this "limbo" state so that we could get feedback on if people liked using the separate elements or not. Personally, I am on your camp that I find that having one component is easier, but other people did not, that is why we wanted to test it out.

**Review by dprokop — APPROVED** [review]

**Review by JoaoSilvaGrafana — APPROVED** [review]
Nice!

**Pull request merged**
