### PR TITLE
S3 IAM support

### LINKED ISSUE #6985: Support IAM Roles for Imageuploader S3 External Image Storage
- What Grafana version are you using? 4.0.1
- What datasource are you using? Cloudwatch / InfluxDB
- What OS are you running grafana on? Docker
- What did you do? Configure External Image Storage without AWS Credentials
- What was the expected result? Failover to IAM Role in AWS SDK
- What happened instead? Received error: ```lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Could not find accessKey setting for image.uploader.s3"```

Considering that the Cloudwatch Datasource Plugin already supports IAM Roles and that AWS Best Practices put a high amount of pressure upon using IAM Roles instead of AWS Credentials, I suspect this should be pretty easy to fix as the AWS SDK for Go quite easily provides IAM Role support in the Credential provider.

Relevant code portion: https://github.com/grafana/grafana/blob/92121ea656dd6bad61c9aef1e438ff9ae9cf9b95/pkg/components/imguploader/imguploader.go#L30

https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/

https://github.com/aws/aws-sdk-go/blob/master/example/service/s3/listObjects/listObjects.go#L29

Heck, all the work was already done for this on the cloudwatch datasource plugin.. https://github.com/grafana/grafana/blob/master/pkg/api/cloudwatch/cloudwatch.go#L144

Unfortunately, I am not (nor am I willing to be) a Golang dev; although I can't provide a PR to go with this, I kindly ask that you guys to put this on the roadmap in order to make IAM management for us DevOps / SecDevOps guys in AWS-land more manageable and to make our Accounts more secure!

### PR DESCRIPTION
**Pull request by mtanda**
Will fix https://github.com/grafana/grafana/issues/6985 .

- [x] handle acl
- [x] add expire time option for pre-signed url

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo I think this is fundamentally required for new alert feature.
please check this.

**Comment by torkelo** [comment]
Looks great, the original pr said WIP I think, is it ready for review and merge?

**Comment by mtanda** [comment]
Yes, it is ready to review and merge.

**Comment by mtanda** [comment]
When I rewrite the uploader, I add 3 options.
- region
- acl
- expires

Current Grafana implementation always uses "public-read" ACL.
But, I think it is not secure, user may want to use "private" and pre-signed url.
http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

By using pre-signed url, it becomes possible to expose captured image only a short period of time.
The "expires" is option to set the lifetime of the pre-signed url.

**Comment by torkelo** [comment]
Since this changes the s3 upload code, this needs to be tested with the current config 

So if a user has this

```ini
[external_image_storage.s3]
bucket_url = http://some_url.s3.amazonaws.com
access_key = AAAAAAA
secret_key = AAAAAAAA
```

Just want to make sure this PR does not break s3 upload for existing users who have no region or acl settings.

**Comment by torkelo** [comment]
So I test this and I do get an error:

```
ROR[01-02|16:03:12] Failed to upload alert panel image.      logger=alerting.notifier error="Could not find region setting for image.uploader.s3"
```

So this is a breaking change. I need you to make it work with the existing settings as well.

**Comment by mtanda** [comment]
I re-read the docs, and I understand if region is omitted in bucket url, it use `us-east-1` region.
(e.g. http://grafana.s3.amazonaws.com/ use `us-east-1` region and `grafana` bucket.)

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
> If you don’t specify a region, Amazon S3 creates the bucket in the US East (N. Virginia) Region.

So I change the implementation, remove region option.
Now the configuration is 100% compatible with current version.

**Comment by mtanda** [comment]
@torkelo sorry for breaking change. Please test this again.

**Comment by torkelo** [comment]
Ok, this is working now. 

But before merge I have some questions. I hope to simplify this a bit. 

Do we need the ACL setting? Can't we always use `public-read` ? I do not see any case where `public-read-write` should be needed. If that is the case we can remove this option. 

expires does not have a default value. Maybe we should add a default value for this option?

**Comment by mtanda** [comment]
We need the ACL setting, I prefer to use `private` acl for snapshot image.
S3 has several acl options, not only `public-read` and `public-read-write`.
http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html

The `public-read` means anyone who know the URL can access the snapshot.
We can block such access by specifying `private` and pre-signed url.
(Please see https://github.com/grafana/grafana/pull/7058#issuecomment-269347213 )

Actually, `public-read-write` is not appropriate for snapshot image uploading.
But, I'm not sure the Grafana user never use the acl, so I need to care about the acl.

**Comment by mtanda** [comment]
> expires does not have a default value. Maybe we should add a default value for this option?

I'm not sure what is good value, but 15 minutes is enough to Ops engineer notice alert and open Slack or something.
So I set "15m".

**Comment by torkelo** [comment]
@mtanda how does pre signed urls work with uploading images? can you create a pre signed urls for a folder that can be used to upload many images? How is slack able to access it, it does not seem to solve the issue of uploading an image and making it public? 

I found the docs very confusing (http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html)

**Comment by mtanda** [comment]
@torkelo It is short lifetime, very long length url.
The url is accessible for anyone who know the url.
But the url becomes not accessible if it is expired.

It behaves like short lifetime public url, no need to sepecial care for the url.

**Comment by mtanda** [comment]
The url format is like following.
```
https://s3.amazonaws.com/my-bucket-name/folder-name/file.zip?AWSAccessKeyId=xxx&Expires=xxx&Signature=xxx
```
http://stackoverflow.com/questions/23443966/uploading-a-file-to-a-s3-presigned-url

The file extension is preserved.

**Comment by torkelo** [comment]
but that only works for one file right?

**Comment by torkelo** [comment]
or can you change folder-name/file.zip  but keep access key and signature the same? Or do you generate that url and signature on the fly in the grafana server backend and then give that to slack?

Can you describe the scenario for how it would work in case of s3 image upload, (then the an url that slack can use access image)

**Comment by mtanda** [comment]
> but that only works for one file right?

Yes, S3 will make one pre-signed url per each file.

> or can you change folder-name/file.zip but keep access key and signature the same?

I'm not sure it is possible...

> Or do you generate that url and signature on the fly in the grafana server backend and then give that to slack?

Yes, the url is generated at https://github.com/grafana/grafana/pull/7058/files#diff-8d93abc04873e9a9dab5f7e01662b5bdR91 .

If the `acl` is not set as `public-read` or `public-read-write`, the grafana backend generate pre-signed url.
`s3uploader.go` will return pre-signed url, then alert notifier post the url.
Only difference is that, the `s3uploader.go` return public url or pre-signed url.

**Comment by torkelo** [comment]
so the expires option does not control how long the file exists in s3? 

I would assume that option controls how long the file exists, and it is removed after the expire period. Is the file not removed? does it only control the "accessibility" of the presigned url?

**Comment by torkelo** [comment]
What is the purpose for `public-read-write` when is that ever desirable?  

I still don't understand the point of pre-signing the url & the expire property. Seems like creating a s3 bucket with a file lifetime of 15m is better (under lifecycle), you do need to enable anonymous access, which you do not need with pre signed url. But since the files are guids would be hard to guess one. 

Another thing I do not understand with this PR is that the same ACL is used for the presigned url and when uploading the file. Which seems to make the pre-sign url thing pointless? If I put "public-read" in the ACL that will be used when uploading the file AND when creating the public pre-signed url. Wont that defeat the purpose of the pre-signed url (making the file publicly readable even when your not using the pre-signed url)

**Comment by mtanda** [comment]
> so the expires option does not control how long the file exists in s3?

Yes, it still exists in S3 after expiration.
To set actual lifetime of S3 object, need to set bucket lifecycle setting.
http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

**Comment by mtanda** [comment]
> What is the purpose for public-read-write when is that ever desirable?

I don't know, I never use it, but there is possibility Grafana user set it.
Let's consider about if Grafana user specify the `public-read-write`, we can take two options.
1. Accept the `acl` and treat it like `public-read`, publish image url (not presigned url)
2. Deny the `acl`, output the error, then user change the `acl` to `public-read`.

I take the option 1, but I'm OK to just deny the `acl`.

> Seems like creating a s3 bucket with a file lifetime of 15m is better (under lifecycle), you do need to enable anonymous access, which you do not need with pre signed url. But since the files are guids would be hard to guess one.

It is not documented, so I didn't know you assume the Grafana user should set lifecycle in short time.
http://docs.grafana.org/installation/configuration/

I agree the point, url has random part, it is hard to guess.

Anyway, you can't set such short lifetime, because the unit of lifecycle expiration is "Days".
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html

**Comment by mtanda** [comment]
> If I put "public-read" in the ACL that will be used when uploading the file AND when creating the public pre-signed url.

If you set `public-read`, the Grafana just return the bucket object url, not creating pre-signed url.
User can access the url until user delete the file. (no expiration)

To create pre-signed url, you should use NOT `public-read` or `public-read-write`.

Sorry for my poor english, I can't understand well what you think...

**Comment by mtanda** [comment]
@torkelo I want to moving forward, so I remove `acl` and `expires` from PR.
Now, the code might become more favorable for you.

**Comment by mtanda** [comment]
thanks

**Comment by torkelo** [comment]
Sorry for taking time to merge. I was not against the acl and expires properties, but just wanted to understand the them and the use case for them, to see if they really where needed (trying to keep the number of options and the code as simple as possible)

**Comment by mtanda** [comment]
No problem, I couldn't explain clearly, it is my fault.
So, I create feature request for this, and ask for feedback from S3 image upload user.

**Comment by ljagiello** [comment]
@mtanda
```
rBucket := regexp.MustCompile(`https?:\/\/(.*)\.s3(-([^.]+))?\.amazonaws\.com\/?`)
```

this part will limit uploader to only AWS S3 and close plugin for other S3 implementations like http://ceph.com/

**Comment by mtanda** [comment]
@ljagiello Sorry, I didn't consider about Ceph when I implement.
The line is required to get region information from bucket url.

If you want to support Ceph, please try it 😄

**Comment by aphawk** [comment]
AWS Beijing use is a different domain. 
http://bucket_name.s3.cn-north-1.amazonaws.com.cn

**Comment by DanCech** [comment]
This is going to break configs using urls like `https://s3.amazonaws.com/<bucket>` since they won't match the regex.

**Comment by guydavis** [comment]
Good day, I am testing Grafana 4.2.0 beta 1 with hopes of getting s3 external image upload to work for IAM.  However, I am not able to provide the role_arn for IAM role switch in the grafana.ini file.  My understanding is that s3 upload in my case requires access_key, secret_key, and a **role_arn**.   I am using bucket_url=https://_my-bucket-name_.s3.amazonaws.com/ and providing my access_key and secret_key.

Grafana is logging:

`eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: CF2EAE84B65245121D" `

For the purposes of testing, the s3 bucket has full read/write for Everyone. Does this closed issue for IAM support allow one to provide role_arn to Grafana?  If not, how should I be configuring Grafana?  Thanks much!

**Comment by DanCech** [comment]
@guydavis is your bucket in `us-east-1`? If not you'll need to specify the url like `https://<bucket-name>.s3-<region>.amazonaws.com/`

**Comment by guydavis** [comment]
Yes, in us-east-1.  Grafana logging at trace level doesn't provide any additional help as to the request error.

**Comment by guydavis** [comment]
Just upgraded to Grafana: 4.2.0.1 and tested again with grafana.ini including:

```
[external_image_storage]
provider = s3
[external_image_storage.s3]
bucket_url = https://<bucket-name>-dcos-grafana-slack.s3.amazonaws.com/
access_key = <AWS_ACCESS_KEY>
secret_key = <AWS_SECRET_KEY>
```

Please note I am a IAM user with zero privileges by default.  I must Role Switch in the AWS console and all other tools I use to script AWS must be given the role_arn for that switch.   My concern is that Grafana 4.2 doesn't seem to use role_arn for S3 uploads.

Here's trace output in the Grafana log:

```
t=2017-03-22T21:36:03+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-03-22T21:36:11+0000 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/eFvrgQS0gJIbAEOiaN4S.png
t=2017-03-22T21:36:11+0000 lvl=dbug msg="Uploading image to s3%!(EXTRA []interface {}=[bucket =  <bucket-name> , key =  V3w9CbV5vSNe3RXtYBCa.png])"
t=2017-03-22T21:36:11+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: 2ACA48576761EF95"
```

AWS Console for S3 shows my bucket with Group of Everyone having Read,Write for Object access.  I'm really hoping that I have misconfigured either S3 or Grafana and that IAM users are truly supported in 4.2 now.  Any help is much appreciated!

**Comment by DanCech** [comment]
The way I'd recommend you solve this problem is to create a dedicated AWS user for Grafana image upload, which can be given only the permissions required to upload images into the correct bucket.

**Comment by torkelo** [comment]
@mtanda can you help this guy, he cannot get EC2RoleProvider to work  https://community.grafana.com/t/s3-upload-using-ec2-metadata-credentials/250/1

**Comment by mtanda** [comment]
I'll take a look.

**Pull request merged**
