### PR TITLE
Theme: Fix wrong code segment in theme.md

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

Adding 
```
const getStyles = (theme: GrafanaTheme2) => css({
padding: theme.spacing(1,2)
});
```

to the code paragraph.

### CODE REVIEW

**Comment by osg-grafana** [comment]
@robbymilo, wanna grab this one?

**Comment by robbymilo** [comment]
@osg-grafana Would love to help but I have no knowledge around themes.

**Comment by jdbaldry** [comment]
@grafana/docs-grafana ping for review.

**Comment by svennergr** [comment]
@osg-grafana @jdbaldry This PR is just moving a line. Could I get a review on that please?

**Review by jdbaldry — APPROVED** [review]

**Pull request merged**
