### PR TITLE
singlestat: change threshold check in flot gauge

### LINKED ISSUE #5515: [Bug]: Singlestat Gauge thresholds are inclusive while value color thresholds are exclusive
- [X] Bug report

(A tiny UI one :)

singlestatscreenshot

On this screenshot, the value is 58.9%, and the threshold value is 60%. The number is correctly displayed in red. However, the gauge above looks already beyond the marker.

Please include this information:
- What Grafana version are you using? 2.0.4
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 14.04

### PR DESCRIPTION
**Pull request by daniellee**
Fixes #5515. Flot gauge has its own threshold check that is different from the threshold check in singlestat. This changes the flot check to be exclusive (same as the singlestat check). E.g. if the threshold is
10, then the value 10 is over the threshold.

### CODE REVIEW

**Comment by daniellee** [comment]
@torkelo I had to take a decision about whether to change the threshold check in the singlestat panel or in the flot gauge code. I decided that an exclusive check makes more sense for a threshold - just want to doublecheck with you before merging.

**Comment by torkelo** [comment]
Looks good, do we want to include this in 4.4.2? If so a rebase on 4.4.x would be good

**Comment by daniellee** [comment]
ok, rebase coming up.

**Comment by daniellee** [comment]
oh, strange. As Alex's commit isn't merged to master it is included in this PR.

**Pull request merged**
