### PR TITLE
Generic Oauth Support for ADFS

### PR DESCRIPTION
**Pull request by DanCech**
ADFS may return the user's email address in a `upn` field instead of `email`, this PR adds support for it.

### CODE REVIEW

**Comment by sylr** [comment]
Tested, works great!

**Comment by torkelo** [comment]
Nice, the UserInfo function is starting to become a bit messy and could need some minor refactoring and unit tests. maybe breaking getting the email out into a function and add unit test for that?

**Comment by sylr** [comment]
Can we merge this please ?

**Comment by DanCech** [comment]
@torkelo I took a look at this, and I'm not sure what the best way would be to break it apart, did you want to just break out the code that handles extracting the email address?

**Comment by torkelo** [comment]
it's just that the UserInfo function is getting long with 10 if statements and no unit tests. So breaking out the response handling and adding a 1-3 unit tests for at least the email handling

**Pull request merged**
