### PR TITLE
Short Links: Add setting for changing expiration time

### LINKED ISSUE #83009: Make short links expiration timeout configurable
### Discussed in https://github.com/grafana/grafana/discussions/37331

<div type='discussions-op-text'>

<sup>Originally posted by **Mario-Hofstaetter** July 29, 2021</sup>
## What would you like to be added

It would be nice to be able **to configure a larger expiration time than 7 days for shortended links created in Explore.**

## Why is this needed

Explore Links may become **very _very_ long** (especially LogQL queries), increased by the URL escaping of many characters in Queries. Using such links in IM / E-Mail / Ticket systems is not pleasant.

Which is why you added short-links. But these appear to expire after 7 days of inactivity (see below).
When adding a link to a bug report ticket system, it may not be needed for days or even weeks and therefore expire too soon.

## Current state

In <https://grafana.com/docs/grafana/latest/explore/#share-shortened-link> it says

> A shortened link that is never used will automatically get deleted after seven (7) days.

Since it is nowhere found in <https://grafana.com/docs/grafana/latest/administration/configuration/> it does not appear to be configurable? Or is it just not documented yet? :-)

## PS

Not sure if "General" is the correct category for this feature request.</div>

### PR DESCRIPTION
**Pull request by gelicia**
**What is this feature?**

In Grafana, users can generate shortlinks for Dashboard and Explore URLs to make them easier to send. Performing this action creates an entry in a database table where Grafana can look up what the URL should be fully by an identifier.

Because we do not want these entries to stay in a database forever if they are not used, we have a stale-ness check on them. If a shortlink was never accessed, it will be deleted in 7 days. If a shortlink is accessed once, it is never deleted. 

**Why do we need this feature?**

We had users that wanted to configure this to their own value of days, so this enables that ability

**Which issue(s) does this PR fix?**:

Fixes #83009

**Special notes for your reviewer:**
Questions I have:
1. Besides making a short link, changing the setting to be a day and checking that it gets deleted, is there a good way to automated test this? Any other testing I should think about?
2. I'm thinking a barebones what's new entry might be useful here - no video or anything because it's not really demo-able but something people might want to know about. The discussion had 10 upvotes and 5 thumbs up, so it had some buzz. Thoughts?  
3. Should the config value be placed somewhere else?

Tested this by adding entries for old shortlinks and waiting for them to get deleted. The cleanup runner goes every 10 minutes. The insert into the database looks like 
`INSERT INTO short_url (org_id, uid, path, created_by, created_at, last_seen_at)
VALUES (1, 'ta7ORIaIR', 'explore', 1, 1712660877, 0);`

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gelicia** [comment]
Questions I have as someone who doesn't write go often
1. Besides making a short link, changing the setting to be a day and checking that it gets deleted, is there a good way to automated test this? Any other testing I should think about?
2. I'm thinking a barebones what's new entry might be useful here - no video or anything because it's not really demo-able but something people might want to know about. Thoughts?

**Review by juanicabanas — APPROVED** [review]
LGTM!

**Review by juanicabanas — APPROVED** [review]

**Review by lwandz13 — APPROVED** [review]
looks great!

**Review by chri2547 — APPROVED** [review]

**Review by harisrozajac — APPROVED** [review]
🚀

**Pull request merged**
