### PR TITLE
Chore: Use theme.shape.radius.circle everywhere

### LINKED ISSUE #70502: Update places that are still using border-radius: 50% or 100% to use radius.circle
**What is the chore?**:

Currently there are a lot of places that still use `border-radius: 50%;` or `border-radius: 100%;` to represent that the element should be a circle, we should change this everywhere to use the new `theme.shape.radius.circle` token.

Information on the new tokens (internal access only): https://internal-ops-us-east-0.grafana.net/design-system/Styling/border-radius/

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- Use `theme.shape.radius.circle` everywhere instead of `border-radius: 50/100%`

**Why do we need this feature?**

- tidy 🧹 

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/70502

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
LGTM 👌

**Review by svennergr — APPROVED** [review]
Logs LGTM!

**Review by IevaVasiljeva — APPROVED** [review]
Licensing page LGTM :)

**Review by tskarhed — APPROVED** [review]
LGTM because I want to feel like I participated :smiling_face_with_tear:

**Pull request merged**
