### PR TITLE
VizLegend: Move onSeriesColorChanged to PanelContext (breaking change) 

### PR DESCRIPTION
**Pull request by ryantxu**
The current approach to support color changes from the legend requires everything above it to pass a function -- this leads to complex and not very efficient memoization... or more likely just re-rendering everything every time.

This PR adds `onSeriesColorChange` to the panelContext so it can be accessed only when needed

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
This is looking really good! (OBS have not tested it but code wise it looks good), and very promising pattern f or other things (time range & timezone)

**Comment by oscarkilhed** [comment]
Is this something we should do for `onLegendClick` too?

**Comment by ryantxu** [comment]
> Is this something we should do for onLegendClick too?

Yes there are a few things like it, but wanted to start easy.  For `onLegendClick` I think we really want something like `toggleSeriesVisibility( name )`

**Comment by dprokop** [comment]
@ryantxu - great PR. @oscarkilhed is going to do the same thingy with series toggle.

**Pull request merged**
