### PR TITLE
add keyboard shotcuts for collapse/expand rows

### PR DESCRIPTION
**Pull request by mtanda**
Fixes, https://github.com/grafana/grafana/issues/552

I add keyboard shortcuts. Please see following comment.
https://github.com/grafana/grafana/pull/7536#issuecomment-279347385

### CODE REVIEW

**Review by bergquist — CHANGES_REQUESTED** [review]
Looks good! 

You also need to add the shortcuts to https://github.com/grafana/grafana/blob/master/public/app/core/components/help/help.ts

Will merge once help text is added.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/5a30b08b14a1587b39a85e60c006cc701b4711fd

**Comment by mtanda** [comment]
Sorry, I miss your message.
Thanks for adding the feature!

**Comment by perlun** [comment]
Anyone else discovering this a few years later (like me), the shortcuts have now changed to this:

https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/core/services/keybindingSrv.ts#L281-L284
https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/core/services/keybindingSrv.ts#L286-L289

**Pull request closed without merging**
