### PR TITLE
RefreshPicker: migrated style from sass to emotion

### LINKED ISSUE #30354: Migrate grafana/ui sass to emotion
SASS styles to migrate to Emotion, all in grafana/ui package:

- [x] [FormField](https://github.com/grafana/grafana/blob/1c58202b26cc738e1b51e1add6606b7e602cfda8/packages/grafana-ui/src/components/FormField/FormField.tsx)
- [x] [ColorPicker](https://github.com/grafana/grafana/blob/1c58202b26cc738e1b51e1add6606b7e602cfda8/packages/grafana-ui/src/components/ColorPicker/ColorPicker.tsx)
- [x] [RefreshPicker](https://github.com/grafana/grafana/blob/1c58202b26cc738e1b51e1add6606b7e602cfda8/packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx) 
- [x] [CustomScrollbar](https://github.com/grafana/grafana/blob/1c58202b26cc738e1b51e1add6606b7e602cfda8/packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx)
- [x] [Tooltip](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Chart/Tooltip.tsx) 
- [x] [TableInputCSV](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/TableInputCSV/TableInputCSV.tsx)

Migrated scss files should be removed both from the codebase and from the grafana/ui scss index file (https://github.com/grafana/grafana/blob/61b9d811cb7878660acdef82d3154462d5e3e287/packages/grafana-ui/src/components/index.scss)

Some getting sarted guide for the styling with Emotion at Grafana: https://github.com/grafana/grafana/blob/master/contribute/style-guides/styling.md

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR migrates style from sass to emotion
**Which issue(s) this PR fixes**:

Relates #30354

### CODE REVIEW

**Comment by torkelo** [comment]
Let's pause this one, it's super complicated and using SelectButton and some legacy styles with the navbar button (which now have a new component for https://github.com/grafana/grafana/pull/30333)

but is complicated by the fact that this component looks very different explore compared to dashboard.

**Comment by thisisobate** [comment]
Alright, will do @torkelo

**Comment by thisisobate** [comment]
I guess I will have to convert this PR to a draft @torkelo

**Comment by torkelo** [comment]
yes, let's do that

**Comment by torkelo** [comment]
This was done as part of  https://github.com/grafana/grafana/pull/30510

**Pull request closed without merging**
