### PR TITLE
added top-n functionality to opentsdb

### PR DESCRIPTION
**Pull request by senthilr2k**
Files changed 

grafana/grafana/public/app/plugins/datasource/opentsdb/document.ts

grafana/grafana/public/app/plugins/datasource/opentsdb/partials/query.editor.html

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marefr** [comment]
Thanks. Do you know of any open issue to track this feature? If not, I would suggest open a new one and reference that in this PR. 

First, seems to be an issue with frontend tests. Running `yarn jest` should be able to reproduce locally. Second, opentsdb also has a backend part in go to support alerting so we expect you to also implement changes in backend to add the same support to function in alerting scenario.

**Comment by torkelo** [comment]
Sorry, this kind of logic needs to be implemented in the OpenTSDB query api, not in Grafana.

**Comment by senthilr2k** [comment]
Hi thanks. But this feature is not available with opentsdb. Idea here is to
filter the results based on the count.

Thanks,
Senthil R

**Comment by torkelo** [comment]
Then your best course of action is to open feature request and PR for this feature in OpenTSDB as this type of feature is a backend api feature not something that should be done in the client api

**Pull request closed without merging**
