### PR TITLE
grafana-ui: Improve PartialHighlighter error handling

### LINKED ISSUE #39679: prometheus query field: error when pressing "space"
how to reproduce:

1. open a prometheus 
1. open a prometheus data-source in explore
1. start writing this query `go_goroutines{job=`
    - at this point you should have autocomplete options
1. press `space`
    - you get an error

the error is `TypeError: Cannot read properties of undefined`
it happens at https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Typeahead/PartialHighlighter.tsx#L38

it seems `highlightParts` is an empty (zero length) list.

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
PartialHighlighter was throwing an error because it wasn't correctly checking if highlightParts had values and was accessing the array without checking first. This caused an error when loading autocomplete values for the Prometheus query editor.

**Which issue(s) this PR fixes**:
Fixes #39679

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ifrost — CHANGES_REQUESTED** [review]
In [BrowserLabel#84](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/BrowserLabel/Label.tsx#L84) and [TypeaheadItem#86](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Typeahead/TypeaheadItem.tsx#L86) we check for the condition below to render PartialHighlighter: 

```typescript
highlightParts !== undefined         
```

Is this error happening because we're passing highlightParts as `null`? If yes I think we should probably either:
* change `highlightParts !== undefined` to consider nulls or...
* if we're changin PartialHighlighter API we should update `Props` to indicate highlightParts can be optional and update tests.

**Comment by ifrost** [comment]
BTW. Does it need backporting?

**Comment by connorlindsey** [comment]
We're passing an empty array which is causing the error. I think checking for that in PartialHighlighter makes the most sense (the component should be robust rather than having the component's using it duplicate that extra error handling).

And this doesn't need backporting since the feature that affected this is going out in 8.2

**Comment by ifrost** [comment]
Right! Could you just add a unit test to cover empty array case?

**Review by ifrost — APPROVED** [review]

**Comment by connorlindsey** [comment]
Yeah, I'll add a test case

**Comment by gabor** [comment]
@connorlindsey right now the branch that will produce grafana8.2 has already been branched out from `main`, so if this wants to land in grafana8.2, it will have to be "backported" to the 8.2.x-branch.

**Pull request merged**
