### PR TITLE
Build: Bundle plugins

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Bundle internal and external (GEL) plugins with Grafana packages.

- [x] Bundle internal plugins
- [x] Bundle external plugins

### CODE REVIEW

**Comment by torkelo** [comment]
Is this making sure that we run the grafana-toolkit plugin:bundle-managed  ? so that plugins in https://github.com/grafana/grafana/tree/master/plugins-bundled get built and included in the release packages

**Comment by aknuds1** [comment]
@torkelo I'm actually not familiar with `grafana-toolkit plugin:bundle-managed`. The reason for this PR (which is very much WIP) is that I'm tasked with bundling plugins into Grafana packages. So far I only know that the GEL plugin should be included.

**Review by ryantxu — APPROVED** [review]
:heart:

**Comment by torkelo** [comment]
Does this mean Input datasource also gets built ?

**Comment by aknuds1** [comment]
@torkelo Yes, it does. It should be built and included with the packages, right? That was how I understood it at least.

**Pull request merged**
