### PR TITLE
Made sure we only resetTypeahead if mounted

### LINKED ISSUE #15081: Explore QueryField setState after unmount
The resetTypeahead on QueryField runs sometimes after unmount casing an error (in log)

### PR DESCRIPTION
**Pull request by hugohaggmark**
Fixes #15081

### CODE REVIEW

**Review by davkal — COMMENTED** [review]
Tracking `mounted` works, but is usually an antipattern. Have you traced who's calling the reset?

**Comment by hugohaggmark** [comment]
It is an antipattern :) I saw this happen on @torkelo machine when the component is unmounted and sometimes later the timeout tries to clear the state. Can't reproduce it locally so I can't say whats calling the reset except for the unmount.

**Comment by torkelo** [comment]
I could replicate this every time I used the label button, which causes a query change that switches the key (a bug in my mind) as it causes a unmount of the query editor and then the resetTypeahead is called on the unmounted QueryField. Not sure why, might be related to the onChange event that is also fired: https://github.com/grafana/grafana/issues/15011

**Comment by davkal** [comment]
Query editors arent controlled components, hence they can only be reset by wiping them via react keys. More details here:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key

**Pull request merged**
