### PR TITLE
Keybinds: Allow move time range shortcuts  (t left / t right) to be chained

### LINKED ISSUE #86710: Multiple Commands While Holding a Meta
**Steps to reproduce**:
Hold a pseudo meta key and type a command key, then _without releasing the meta_ type another command;  

For instance: Hold **t** and press **left arrow** twice, where **t** is the meta and **left arrow** is the **Move time range back** command.

**Actual Result**:
Only the first command press is honored.  _The meta key must be released and reengaged_ before a second command press is honored.

**Expected Result**
As long as the meta key is held, subsequent presses of command keys should all be honored.  In the case above holding **t** and pressing **left arrow** twice should Move time range back two times.

In another example holding **g** while pressing **h** then **d** then **e** then **p** should go to each of Home Dashboard, Dashboards, Explore and finally Profile.  All without releasing **g**.

In the same way holding **d** while pressing **r** repeatedly should refresh the charts for every **r** press without ever releasing **d**. 

**_This behavior mimics the OS behavior of the ctrl/command keys, reducing the number and complexity of keystrokes._**

**Environment**:
- Grafana version: v10.4.2
- Data source type & version: Any (Tested with InfluxDB)
- User OS & Browser: Windows 11 & Chrome 123
- Others:

### PR DESCRIPTION
**Pull request by joshhunt**
**What is this feature?**

Grafana has the `t left` and `t right` sequence shortcuts to adjust the selected time range of dashboards and Explore. This PR allows for the shortcuts to be more easily chained without having to repeat the common prefix e.g. `t left left left right` will shift the time range back three times and forwards once.

**Why do we need this feature?**

For easier navigating through Dashboards.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/86710

**Special notes for your reviewer:**

Note - this does not allow shortcuts to be chained in this way across multiple pages. This is because Grafana resets all keyboard shortcuts when navigating between pages. I've already spent probably too much time on this enhancement, where I think the main advantage is to more quickly do things on the same page.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
Learning a lot of shortcuts with all of this 🫣 
Checked on the ephemeral instance and it works 👌

**Review by tskarhed — COMMENTED** [review]
I think this behaviour is a little bit weird

- I press (not hold) t, and then I can press left/right whenever
- A sequence also works as a key combination

What I expected is that if I press and hold t, then I should be able to press left/right whenever. This should porbably only apply to combinations rather than sequences `t+left` instead of `t left`.

**Comment by joshhunt** [comment]
@tskarhed I removed press-and-hold repeats, so now holding down `d` will no longer infinitely dupe panels.

Expected behaviour for `t left` is - tap `t` and tap multiple `left` / `right` to shift the time range either way. You _can_ press and hold `t`, but you could before (and was a misunderstanding of issue OP i believe) and this is undocumented/unsupported behaviour.

I think this PR is in a good spot now

**Comment by tskarhed** [comment]
@joshhunt No, you can't press and hold `t` and then do multiple left/right at the moment. That is what OP is requesting.

>**As long as the meta key is held**, subsequent presses of command keys should all be honored. In the case above holding t and pressing left arrow twice should Move time range back two times.

**Review by tskarhed — APPROVED** [review]

**Comment by ifrost** [comment]
Moving it 11.2.x milestone as it was merged after the cut-off of 11.1.x. Please create a backport to 11.1.x if you'd like it be included in next monthly patch release (11.1.1)

**Pull request merged**
