### PR TITLE
Live: Fix support for `StreamingFrameAction.Replace`

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
Fixes https://github.com/grafana/grafana/pull/46086

**What this PR does / why we need it**:

The new frontend live data pipeline I added in https://github.com/grafana/grafana/pull/41492 does not support the `StreamingFrameAction.Replace` streaming buffer option - this PR re-adds that support

TODO:
- [x] unit tests for `StreamingDataFrame.ts`
- [x] unit tests for `LiveDataStream.ts`
- [x] manual exploratory tests

cc @sd2k

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
:heart:

**Comment by ArturWierzbicki** [comment]
Issue reported by @sd2k 

https://user-images.githubusercontent.com/23451458/156426483-6adbddcb-6a0f-4313-a8d4-9bd94778123c.mov

Will check out the [tokio console plugin](https://github.com/grafana/grafana-tokio-console-datasource) and try to reproduce the issue before merging

**Comment by sd2k** [comment]
> Issue reported by @sd2k 
> 
> https://user-images.githubusercontent.com/23451458/156426483-6adbddcb-6a0f-4313-a8d4-9bd94778123c.mov
> 
> Will check out the [tokio console plugin](https://github.com/grafana/grafana-tokio-console-datasource) and try to reproduce the issue before merging
> 

FWIW this panel is _not_ using a stream configured to 'replace' so I don't think it's related to this issue/PR but I could be wrong!

**Comment by ArturWierzbicki** [comment]
> FWIW this panel is not using a stream configured to 'replace' so I don't think it's related to this issue/PR but I could be wrong! 

that's even more interesting!

**Comment by ArturWierzbicki** [comment]
Reproduced locally. This log message is being printed on each new packet: https://github.com/grafana/grafana/blob/7bf25f62e154886686b436b4201242f4ba7435c3/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L216

image

**Comment by ArturWierzbicki** [comment]
> 
>  Screen.Recording.2022-03-02.at.13.23.25.mov 
> Will check out the [tokio console plugin](https://github.com/grafana/grafana-tokio-console-datasource) and try to reproduce the issue before merging

Reproduced the same issue on branch `v8.3.0beta1` which does not include changes from https://github.com/grafana/grafana/pull/41492. 
Will do some more manual testing related to this PR, merge it and create a separate issue for the issue from the video.

**Pull request merged**
