### PR TITLE
TimePicker accessibility: remove `stopPropagation` from everywhere

### LINKED ISSUE #60400: A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/DateTimePickers/DateTimePicker/DateTimePicker.tsx`

### LINKED ISSUE #60401: A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerCalendar.tsx`

### LINKED ISSUE #60402: A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/DateTimePickers/TimeZonePicker/TimeZoneGroup.tsx`

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- removes a load of `onClick` handlers which call `stopPropagation`
  - i'm not sure why these were there. i've removed them and played around and i can't seem to find any functional differences

**Why do we need this feature?**

- stop adding `onClick` handlers to elements which aren't interactive (e.g. `div`s)

**Who is this feature for?**

- everyone!

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/60400
Fixes https://github.com/grafana/grafana/issues/60401
Fixes https://github.com/grafana/grafana/issues/60402

**Special notes for your reviewer**:

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
This is specifically for the `DateTimePicker`, not for the one used in the Dashboards. If you go to https://play.grafana.org/alerting/grafana/xPXbVXNnz/view and scroll to the bottom where there is a visualization there is a `DateTimePicker` there. Which in your branch is broken because I'm guessing the `stopPropagation` was stopping it from immediately closing...
Maybe we need to think about merging these two different components so that they work in similar ways instead of maintaining different TimePickers with different behaviours.

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana spicy 🌶️ i'll see if i can fix it there/combine them 😬

**Comment by ashharrison90** [comment]
ok should be fixed now 👍 completely agree we need to unify these going forward. @grafana/alerting-squad-frontend, i've made some changes to `DateTimePicker` to be much more keyboard friendly. there's a _slight_ change in behaviour in that clicking on the input no longer automatically shows the overlay (you have to click the calendar button), but i think that keeps the responsibilities clearer. lmk what you think 😄

**Review by JoaoSilvaGrafana — APPROVED** [review]
lgtm! 👏 

> there's a slight change in behaviour in that clicking on the input no longer automatically shows the overlay (you have to click the calendar button)

This is how the time range picker works, so from a component perspective I think this makes it more consistent. I have also created this issue to deal with the multiple date/time picker components: https://github.com/grafana/grafana/issues/60621

**Comment by ashharrison90** [comment]
> lgtm! 👏
> 
> > there's a slight change in behaviour in that clicking on the input no longer automatically shows the overlay (you have to click the calendar button)
> 
> This is how the time range picker works, so from a component perspective I think this makes it more consistent. I have also created this issue to deal with the multiple date/time picker components: #60621

yup, it also makes most sense from a keyboard accessibility point of view. when you open the calendar, focus moves + is trapped in the calendar until you close it. before, the calendar would open as soon as you focus the input but the only way to then access it via the keyboard would be to tab through the entire document 😬

**Review by gillesdemey — APPROVED** [review]
So I've tested this with alerting and seems to work as intended – I actually _prefer_ the behavior of clicking on the calendar icon and keeping the input separate.

**Pull request merged**
