### PR TITLE
Patch to CSVexport file to resolve #2401

### LINKED ISSUE #2401: Change CSV export seperator
This one was discussed before in https://github.com/grafana/grafana/issues/1855 but closed because only one person raised it.

It's also an issue for me.

As far as I can tell, your experience with this depends on where you live...

In some locales a semicolon separated file will work fine as a CSV file in Excel without any config changes. In others it will not. In my own Excel setup (UK) it opens with all of the fields (and semicolons) appearing in a single column... which is not what most people want.

For sure it is possible to persuade Excel (using "Data/Text to Columns") to split the data into three columns but it's not a very slick user experience. A similar observation applies to dealing with the date/time format.

The rest of Grafana is very slick indeed, so the CSV export could definitely benefit from some further thought. 

I believe that there are at least three questions to consider:-
1. CSV column separator - currently ';' which does not work 'out of the box' in some locales (e.g. UK)
2. Decimal separator - currently '.' which is fine for me here in the UK but it may be worth checking whether it works in countries that use a comma for decimals
3. Date/time format - currently a format which looks like ISO8601

FWIW, here is what Grafana produces on my machine

Series;Time;Value
total throughput;2015-07-26T08:02:00.000Z;4821
total throughput;2015-07-26T08:03:00.000Z;5293
total throughput;2015-07-26T08:04:00.000Z;5347

and here is how I needed to change it to make it display correctly in Excel (2010)

Series,Time,Value
total throughput,2015-07-26 08:02:00,4821
total throughput,2015-07-26 08:03:00,5293
total throughput,2015-07-26 08:04:00,5347

Leaving the decimals in the timestamp doesn't prevent Excel from *interpreting* the value correctly but it does display in a very odd way (minutes:seconds plus a single decimal place) and then requires explicit reformatting in Excel to produce a sensible result on the screen.

I don't honestly know whether there is a 'one size fits all' answer for the time format (probably not) so perhaps it would be possible to make this a configurable option?

Changing the column separator to be a comma would fit with the RFC4180 definition of CSV. If this is a backwards step in other locales then making the separator configurable should suit everyone.

With regard to decimal separator, I don't know whether this causes any issues in countries that use a comma so I can't answer that one. If a comma is used for a decimal separator in the file then the values will most likely need to be quoted.

### PR DESCRIPTION
**Pull request by dalesit**
resolves #2401

Prepended first line to export file containing
`sep=;\n`
which I believe should be all that is required for Excel to interpret the CSV file as semicolon delimited. I have verified the changed output file would be correct, but not that this is the only change required to produce that output file, so needs verification by someone more familiar with the code than me.

### CODE REVIEW

**Comment by dalesit** [comment]
As I haven't actually made any code changes, I'm assuming the failing tests are a separate issue

**Comment by bergquist** [comment]
@dalesit npm install issues on build server.

**Comment by bergquist** [comment]
@dalesit are there any documentations on this behavior?

**Comment by dalesit** [comment]
Haven't found it directly in the Excel documentation, but have found numerous examples of the information on the net:
https://kb.paessler.com/en/topic/2293-i-have-trouble-opening-csv-files-with-microsoft-excel-is-there-a-quick-way-to-fix-this
http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel

This might be an Excel specific fix for the issue.

It might make more sense to move to [rfc4180](https://tools.ietf.org/html/rfc4180) compliant CSV files which have the fields with " " around them, and separated by commas. This resolves the issue that European regional settings use commas as the decimal delimiter. However, I'm not sure how these files are dealt with automatically with Excel regional settings set to semicolons as the field delimiter by default.

**Comment by daledude** [comment]
This should probably also be made to the exportTableDataToCsv function for exporting table data.

**Pull request merged**
