### PR TITLE
GraphNG: Fix issue with graphs having white background on print

### LINKED ISSUE #38460: Some panels show white background in dark mode when printing to PDF in Google Chrome
**What happened**:

When printing a Grafana dashboard to PDF in Google Chrome, with Grafana in dark mode, some panels show a partially or completely white background.

I have seen it happen with the following panels:
* Time series
* Stat

Example screenshot of "Time series" panels:

Screenshot from 2021-08-23 12-18-05

Example screenshot of a "Stat" panel:

Screenshot from 2021-08-23 12-34-29

Note: there is another open issue, #36656, which might be related.

**What you expected to happen**:

The panels should show a dark background, matching the dark theme.

**How to reproduce it (as minimally and precisely as possible)**:

One quick way to see it is to navigate to https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 and print the page to PDF in Chrome. The result should look similar to the first screenshot above.

To reproduce it in a local Grafana 8.1.2 installation: set the theme option to dark mode, create a new dashboard, add a "Time series" or "Stat" panel with the "--Grafana--" datasource (setting the query type to Random Walk), and use Google Chrome to navigate to this dashboard and print it to PDF.

**Anything else we need to know?**:

There is another open issue, #36656, which might be related.

**Environment**:
- Grafana version: 8.1.2.
- Data source type & version: This seems to happen regardless of datasource; tried it with MySQL and the built-in --Grafana-- datasource.
- OS Grafana is installed on: I used Grafana installed in Ubuntu 20.04 for reproducing it locally.
- User OS & Browser: Ubuntu 20.04; Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dprokop**
Fixes https://github.com/grafana/grafana/issues/38460

### CODE REVIEW

**Comment by leeoniya** [comment]
hey @dprokop 

can you elaborate why this strategy is necessary?

uPlot uses https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect, which should always result in a transparent canvas:

https://github.com/leeoniya/uPlot/blob/4fa2d2f65a6ff26eaffa0e26598af0caf60feb44/src/uPlot.js#L1812-L1813

**Comment by leeoniya** [comment]
it looks like we use gofpdf to handle rendering, so this may be relevant: https://github.com/jung-kurt/gofpdf/issues/261

perhaps this needs to be fixed on the enterprise side in `/src/pkg/extensions/report/pdf.go`?

**Comment by dprokop** [comment]
> it looks like we use gofpdf to handle rendering, so this may be relevant: [jung-kurt/gofpdf#261](https://github.com/jung-kurt/gofpdf/issues/261)
> 
> perhaps this needs to be fixed on the enterprise side in `/src/pkg/extensions/report/pdf.go`?

@leeoniya This has nothing to do with Grafana's server. Try printing out (on a printer) any dashboard using uPlot, backgrounds are white. Same when printing to PDF. 

Seems to affect Chrome only, tho

**Comment by leeoniya** [comment]
i'd like to root-cause this, it's very odd. if you disable all uPlot plugins does it still happen?

this PR is gonna be pretty expensive. my proposed work-around for now is to only reset the background during print, without adding more drawClear hooks:

```js
// example canvas
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
ctx.fillStyle = 'blue';
ctx.fillRect(10, 10, 100, 100);

function printPrep(background) {
  for (const can of document.querySelectorAll('canvas')) {
    let ctx = can.getContext('2d');

    // draw under
    ctx.globalCompositeOperation = 'destination-over';
    ctx.fillStyle = background;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    // revert to draw over (default)
    ctx.globalCompositeOperation = 'source-over';
  }
}

printPrep('red');
```

https://jsfiddle.net/Lqsfgdu5/1/

**Comment by dprokop** [comment]
> i'd like to root-cause this, it's very odd. if you disable all uPlot plugins does it still happen?

Yeah, it happens even in your demos: https://leeoniya.github.io/uPlot/bench/uPlot.html ;) Doubt this is plugin related

**Comment by leeoniya** [comment]
> You mean it's gonna affect uPlots performance? Or you mean the maintenance cost?

performance.this PR does two things that are explicitly called out [1] as having known slowness:

1. Try different ways to clear the canvas (clearRect() vs. fillRect() vs. resizing the canvas).
2. Avoid unnecessary canvas state changes.

> Yeah, it happens even in your demos: https://leeoniya.github.io/uPlot/bench/uPlot.html ;) Doubt this is plugin related

hmm, i'll test this later today, but sounds like a uplot bug then. (if flot can avoid it, so can uplot!) we're gonna have a uPlot bump before 8.2 anyhow, so in this case i would hold off on patching it here.

i wonder if [turning off alpha during ctx init](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#turn_off_transparency) have an effect? 🤔 

> This solution will not work as we don't have knowledge outside of the dashboard/panel context which panels are transparent vs which ones are not. Unless we add multiple handlers for each GraphNG component to attach this event handler.

we could always add a class to the wrapper and a data-bg attr, and still rely on one global handler, but let's see if this all of this can be avoided anyways.

can you plz attach a demo dashboard i can test that has non-transparent (and non white!) bg panels that also contain uplot-based charts? or is this something like stat with bg based on thresholds?

[1] https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

**Comment by leeoniya** [comment]
so far, this looks like an extremely bizarre Chrome bug that has to do with canvas resizing. isolating a minimal test case is proving to be tricky; i'll need to start stripping uPlot down to make an actionable Chrome bug report.

removing these two lines makes the bug go away:

https://github.com/leeoniya/uPlot/blob/4fa2d2f65a6ff26eaffa0e26598af0caf60feb44/src/uPlot.js#L1797-L1798

also, wrapping them in `setTimeout/0` causes the _first_ print attempt to exhibit the white bg bug, but followup print attempts do not.

**Comment by leeoniya** [comment]
the fix for this is here: https://github.com/leeoniya/uPlot/commit/84a966040a60938600e69dda57bceecbb2951bb0

**Comment by leeoniya** [comment]
here's the Chrome bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1245805

the 5 specific conditions all required to trigger this are:

1. a media query crafted to detect `devicePixelRatio` changes. Chrome has a bug that fires it during printing even though there are no changes to this value.
2. setting `canvas.width` or `canvas.height` (even to existing values)
3. calling `ctx.clearRect()`
4. a non-white page background
5. attempting to print the page or export to PDF, in Chrome

this was not a fun one to isolate :exploding_head:

**Comment by dprokop** [comment]
> this was not a fun one to isolate 🤯

Amazing investigation @leeoniya, truly! I'm gonna close this for now and wait for the next uPlot release to get that fix included.

**Pull request closed without merging**
