### PR TITLE
Instrumentation: Implemented FileLogWriter Formattedlogger

### LINKED ISSUE #45941: custom.ini log.file format to json setting not working
**What happened**:
grafana.log logs are in text format even though I changed the format settings in custom.ini to json
image

**What you expected to happen**:
I expected logs in json format.

**How to reproduce it (as minimally and precisely as possible)**:
In custom.ini under Logging set [log.file] `format = json` then start Grafana service and check the grafana.log format.

**Anything else we need to know?**:
NA

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: NA
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: NA
- Others: NA

### PR DESCRIPTION
**Pull request by gurpartb**
**What this PR does / why we need it**:
Implements Formattedlogger instead of the default logger.

**Which issue(s) this PR fixes**:
logs in grafana.log file are formatted (text, json, console) as specified in the defaults/custom.ini file and not as default text. 

Fixes #45941 

**Special notes for your reviewer**:
This is my first PR for Grafana, any feedback is much appreciated. Thanks!

### CODE REVIEW

**Comment by gurpartb** [comment]
@zserge @idafurjes @ying-jeanne need your help completing this PR :)
-  It needs backport label 8.4.x since functionality broke in release [Garfana 8.4.0-beta1](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-0-beta1/#:~:text=Instrumentation%3A%20Logger%20migration%20from%20log15%20to%20gokit/log.%20%2341636%2C%20%40ying%2Djeanne).
- Needs Milestone check label
- Is the changelog auto updated or do I update it?

Thanks

**Comment by gurpartb** [comment]
Hi @CharityAnderson I'm trying to get this PR merged can you please help :)

**Comment by nicolaerosia** [comment]
the issue was not fixed by https://github.com/grafana/grafana/pull/46970 ?

**Comment by ying-jeanne** [comment]
it is done already by https://github.com/grafana/grafana/pull/46970

**Comment by nicolaerosia** [comment]
you can't technically say "already" because this PR is much older than the one that got merged...

**Comment by ying-jeanne** [comment]
> 

:) well make sense, fair enough. but the other one is merged somehow quicker.

**Comment by nicolaerosia** [comment]
@ying-jeanne it's still broken, the JSON format is back but without the fields that were previously there. Can you please check https://github.com/grafana/grafana/issues/46996?

Re. the other one being merged quicker, yes, it's probably because the PR author is from Grafana. However, from my point of view, this discourages external contributions. This guy here even mentioned `This is my first PR for Grafana, any feedback is much appreciated. Thanks!` and instead got closed without any thanks or whatsoever

**Pull request closed without merging**
