### PR TITLE
set threshold values by variable

### PR DESCRIPTION
**Pull request by benickj**
**What this PR does / why we need it**:

this feature will give the availability to use a dashboard variable to set the threshold lines
(for example to sync these with a pie chart division)

**Which issue(s) this PR fixes**:

feature request

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
You need to rebase

**Comment by benickj** [comment]
hopefully now it is the right base branch, otherwise please tell me which i have to choose.

**Comment by ryantxu** [comment]
@benickj -- something is still wrong.  Make sure the number of changed files is small... otherwise it is totally impossible to understand what you are proposing:
sss

**Comment by benickj** [comment]
@ryantxu  ok i get it but i don't know exactly where this big number is coming from.....I just tried to place a new feature idea/request.

sorry i m not so familiar with github yet.

**Comment by ryantxu** [comment]
I'll close this. you can try creating a new one.  before you submit the PR (clicking the button) you can preview what it will look like.  Keep trying till you find something that looks readable.  there is obviously no way we can look at 2000 changes and understand what you are tying to do :)

**Pull request closed without merging**
