### PR TITLE
add extra post data for LINE image alerts

### PR DESCRIPTION
**Pull request by tarjosuinarjo**
just add extra post data for LINE image alerts

### CODE REVIEW

**Comment by huydx** [comment]
I think you have some works left:
- squash commits
- sign CLA
- format code using `go fmt`

**Comment by tarjosuinarjo** [comment]
hi @huydx , i've sign the cla with cla-assistant and get "You have signed the CLA for grafana/grafana"
it's not directly update to the PR ? or something else that i missing ?

**Comment by huydx** [comment]
@tarjosuinarjo CI failed, and I think that you forgot to
>format code using go fmt

**Comment by tarjosuinarjo** [comment]
i think i've used go fmt and do squash. but somehow it's not reflected on the PR
anyway. thanks @huydx for helping this. hope will be usefull for anyone

**Pull request closed without merging**
