### PR TITLE
Variables: migrates interval variable type to React/Redux 

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Relates to #22564

**Special notes for your reviewer**:

### CODE REVIEW

**Review by mckn — APPROVED** [review]
Love the builder pattern!

LGTM

**Review by torkelo — APPROVED** [review]
The code looks good but the problem with time range not causing a refresh is making testing a bit tricky :) 

Found one bug:  When you select a value it does not commit it, it should close & commit value for variables that are not multi value. 

When I click a value here it should select and close the dropdown (commit value)
image

**Comment by hugohaggmark** [comment]
> The code looks good but the problem with time range not causing a refresh is making testing a bit tricky :)
> 
> Found one bug: When you select a value it does not commit it, it should close & commit value for variables that are not multi value.
> 
> When I click a value here it should select and close the drop-down (commit value)
> image

Great finding, so do I understand correctly this behavior is only valid for non-multi value pickers then?

**Comment by hugohaggmark** [comment]
> The code looks good but the problem with time range not causing a refresh is making testing a bit tricky :)
> 

Will definitely focus on getting this fixed after this PR!

**Comment by torkelo** [comment]
Yea all single value variables should just require one click

**Comment by hugohaggmark** [comment]
> Yea all single value variables should just require one click

I think I will fix this in a separate PR.

**Pull request merged**
