### PR TITLE
GraphNG: refactor by-value color schemes

### LINKED ISSUE #37629: Time series panel - graph colour scheme rendering in Firefox
**What happened**: A new colour scheme for time series graphs based on thresholds render wrongly in Firefox (messed up colours of the graph). Better in Chromium based browsers, but still graph colour is shifted away from the threshold.

**What you expected to happen**: Graphs rendered properly with colours reflecting defined thresholds.

**How to reproduce it (as minimally and precisely as possible)**:
* Edit/create a panel with a Time Series type of graph
* Configure minimum required options:
  - Gradient mode: Scheme
  - Color scheme: From thresholds (by value)
  - Thresholds: choose any that is in the middle of presented data (e.g. 0*C for temperature chart)
  - Show thresholds: As lines

**Anything else we need to know?**: Works much better in Chrome(ium) based browsers but still not very accurate.

**Environment**:
- Grafana version: 8.1.0 (both installed and clean Docker container)
- Data source type & version: n/a (can be observed with "Random Walk" too)
- OS Grafana is installed on: Debian/Ubuntu (Docker)
- User OS & Browser: Windows/Linux, Firefox ESR/Latest.
- Grafana plugins: n/a
- Others: n/a

Chromium based browser:
image

Firefox:
image

### LINKED ISSUE #37658: "Color scheme from thresholds" is changing the color below the threshold value
**What happened**: When I set the series color scheme to `From thresholds` using the new 8.1.0 feature, the color of the line is adjusted just below the intended value.

**What you expected to happen**: I expected the line color to change at exactly the threshold value.

**How to reproduce it (as minimally and precisely as possible)**:
Create a series
Set the color scheme to `From thresholds (by value)`
See this video demonstrating the behavior: https://youtu.be/J4BDTJvCDhA

**Anything else we need to know?**:
I was also testing out the new transformation Config from Query in this panel (though the query was disabled), so I wonder if there was some interaction between the two?

**Environment**:
- Grafana version: 8.1.0-beta3
- Data source type & version: TestData DB
- OS Grafana is installed on: Docker
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes #37658
Fixes #37629

image

Summary:

- uPlot update
  - some api additions to support future stuffs
  - various perf optimizations for cursor hover points
  - hover point css has changed to use `background-clip: padding-box` rather than `content-box`, which reduces odd bullseye rendering artifacts in Chrome. before/after:
  image
- New gradient builder
  - fixes Firefox rendering, without having a gradient stop fudge (e.g. 0.001 or 0.0000001)
  - fixes various odd bugs when data, thresholds and y axis ranges mismatch
- Use gradient builder for rendering threshold areas
- Implemented hover point color interpolation for thresholds and color scales
- Implemented % thresholds (data-relative, per unit)
- Fixed % color scales (data-relative, per unit)
- Optimizations
  - sharing and re-using gradients
  - reduce use of tinycolor
  - round fractional pixels for crisp rendering.

<details>
<summary>dashboard</summary>
<pre>
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 273,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 30,
            "gradientMode": "scheme",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "light-orange",
                "value": 80
              },
              {
                "color": "red",
                "value": 90
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 15,
        "w": 7,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "70,80,90,100"
        }
      ],
      "title": "Thresholds: Base, 80, 90",
      "type": "timeseries"
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 30,
            "gradientMode": "scheme",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "light-orange",
                "value": 80
              },
              {
                "color": "red",
                "value": 90
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 15,
        "w": 8,
        "x": 7,
        "y": 0
      },
      "id": 3,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "85,90,100"
        }
      ],
      "title": "Thresholds: Base, 80, 90",
      "type": "timeseries"
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 30,
            "gradientMode": "scheme",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "light-orange",
                "value": 80
              },
              {
                "color": "red",
                "value": 150
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 15,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 4,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "85,90,100"
        }
      ],
      "title": "Thresholds: Base, 80, 150",
      "type": "timeseries"
    }
  ],
  "refresh": false,
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "wrong-gradient-threshold",
  "uid": "54RYBBM7k",
  "version": 7
}
</pre>
</details>

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Thanks for fixing this!

**Comment by torkelo** [comment]
@leeoniya fixed the other issue (the middle in your screenshot) , at least one case of it

**Comment by torkelo** [comment]
Not sure why firefox is not ok with the discrete gradients, https://github.com/grafana/grafana/issues/37629

**Comment by torkelo** [comment]
Ok fixed firefox issue as well now, seems firefox and chrome has different limits for how close gradient stops can be until they are ignored.

**Comment by torkelo** [comment]
@leeoniya Is there more to do in this PR? Want to include this in next patch release

**Review by ryantxu — APPROVED** [review]
Looking good!

image


you get what you ask for:
image

**Review by torkelo — APPROVED** [review]
Awesome job on this one"

**Pull request merged**
