### PR TITLE
WIP: Add @grafana/toolkit package

### PR DESCRIPTION
**Pull request by dprokop**
Introduces @grafana/toolkit package and migrates cli tools there.

TODO: 
- [x] Enable building app/plugin using shared rollup config
- [x] If there is more than one module.ts entry then add manual chunks
- [x] Enable running tests on app/plugin
- [x] Introduce common tsconfig
- [x] Introduce common tslint config
- [x] Do not expose internal cli commands 
- [ ] Validate plugin name/org
       - OK for plugins in grafana repo to skip the org 
- [ ] Run typecheck before linting 
- [ ] Add watch option to enable easy development (rollup watch, plugin:[dev|watch])

Currently trying with:
 * ✅ [GraphQL Datasource](https://github.com/ryantxu/grafana-graphql-datasource)
 * ✅ [Salesforce Datasource](https://github.com/grafana/salesforce-datasource)
 * [Ajax Panel](https://github.com/ryantxu/ajax-panel/pull/36) fails with `app/plugin/sdk`
 * [k8s app](https://github.com/grafana/kubernetes-app/pull/69) fails with `app/plugin/sdk`
 * [Worldmap Panel](https://github.com/grafana/worldmap-panel/pull/206)
 * [RSS panel](https://github.com/grafana/rss-panel) builds, but fails to load
 * [Clock Panel](https://github.com/grafana/clock-panel/pull/50) fails... rollup?
 * [Lapnap Live App](https://github.com/lapnap/grafana-live-app) fails... test import relative path?
 * [Tail Datasource](https://github.com/lapnap/grafana-tail-datasource/pull/2)  fails... test import relative path?
 * [influx flux](https://github.com/grafana/influxdb-flux-datasource/pull/41) test failure

### CODE REVIEW

**Comment by torkelo** [comment]
It feels a bit strange to move the big project tasks (theme watching, changelog, cherrypick) to this toolkit package that I thought would be more focused on building & testing plugins. 

But maybe mixing these is fine?

**Comment by dprokop** [comment]
@ryantxu @torkelo see 4caadbf28ec8c82481e13405d7399c59b8a330d5 for first attempt for having shared tsconfig for plugins. I assume that there will be cases when extending tsconfig will be necessary. 

According to https://github.com/Microsoft/TypeScript/issues/29172 some paths are resolved relatively to tsconfig.json location. For example, if I extend the base config from grafana/toolkit (btw got it working only with such extend: `"extends": "./node_modules/@grafana/toolkit/src/config/tsconfig.plugin.json"`), then in Ryan's grafana-live-app the absolute imports does not work until I override `baseUrl` in local tsconfig.json . This sucks a little bit unfortunately, seems like the plugin will have to have tsconfig.json specified anyways.

Another issue is that in order for the IDE to pickup grafana/toolkit tsconfig we need to extend it in the local tsconfig. Couldn't make it work with `"extends": "@grafana/toolkit"` only, as rollup fails when extendig that config.


FYI for testing purposes use `yarn link` in grafana toolkit root dir.

**Comment by dprokop** [comment]
@torkelo @ryantxu see https://github.com/grafana/rss-panel/pull/1 for grafana-toolkit usage reference. Especially interesting is tsconfig.json. Apparently, all path specific options need to be defined in that file for `tsc` to pickup correct directories (otherwise paths are resolved relatively to original tsconfig file).

I don't like how the default config is extended though, as it requires either path to node modules (as in the example PR https://github.com/grafana/rss-panel/pull/1/files#diff-e5e546dd2eb0351f813d63d1b39dbc48), or we could also introduce package with default tsconfig for plugin. I don't like this idea though. 

But to be honest I think that with any of the approaches we take there will be possibility to override defaults, so maybe we should basically provide a basic tsconfig.json file when we will introduce some plugin boilerplate?

**Comment by ryantxu** [comment]
I think we should merge this soon even if the plugin build stuff still needs work.

**Comment by ryantxu** [comment]
@dprokop -- I'm trying to make this work with old plugins like:
https://github.com/grafana/kubernetes-app/tree/using-toolkit

I added the option to use the local tslint.json if it exists, this way plugins could migrate slowly if necessary.

I also added the `fix=true` flag.  We could have a second task, but with git I think autofix is the better behavior

**Comment by dprokop** [comment]
@ryan I have created https://github.com/grafana/grafana/issues/17819 to keep track of the progress/todos

**Review by torkelo — APPROVED** [review]

**Pull request merged**
