### PR TITLE
Alerting: Add additional customisation to ngalert MS Teams notifier

### LINKED ISSUE #46366: Customize Microsoft Teams contact point header message
### Discussed in https://github.com/grafana/grafana/discussions/40475

<div type='discussions-op-text'>

<sup>Originally posted by **AlbMor** October 14, 2021</sup>
## What Grafana version and what operating system are you using?
Docker: grafana/grafana:8.1.2 on Windows Docker Desktop with wsl2### Discussed in https://github.com/grafana/grafana/discussions/40475

<div type='discussions-op-text'>

<sup>Originally posted by **AlbMor** October 14, 2021</sup>
## What Grafana version and what operating system are you using?
Docker: grafana/grafana:8.1.2 on Windows Docker Desktop with wsl2

## What are you trying to achieve?
Send Alert to Microsoft Team contact point and have a desired Header message

## How are you trying to achieve it?
Using the new Grafana Managed Alert system

## What happened?
In the Microsoft Team contact point the header message is created using the alert label.

## What did you expect to happen?
I would like to have control over the header message of the Microsoft Teams contact point. For example the Slack contact point has Title parameter that can be set.</div>

----
This is also discussed in https://github.com/grafana/grafana/discussions/44222 and https://github.com/grafana/grafana/discussions/38526.

In the Microsoft Teams notifier in the new alerting service, the 'Title' and 'Section Title' are hard-coded, which is frustrating as it prints all the label values in the title.

### PR DESCRIPTION
**Pull request by mucho-al-dente**
Makes the Title and Section Title of the Teams message customisable.
Closes #46366

image

### CODE REVIEW

**Comment by cianooooo** [comment]
@alexweav @JacobsonMT I have just rebased this PR and fixed the conflicts that had arisen since I originally made it. I've also made sure all the tests are passing, and it looks good. What are the chances of getting this merged?

**Comment by JacobsonMT** [comment]
Hi @cianooooo, thanks for the contribution! At a glance the changes look clean and well-done. I'll make time asap to take a closer look, test, and get back to you.

**Comment by cianooooo** [comment]
@JacobsonMT Amazing, that'd be great, thanks a million. If it helps any, I'm running a custom build of Grafana with these changes in production and it's all good!

**Review by JacobsonMT — APPROVED** [review]
LGTM! Great PR :rocket:

**Pull request merged**
