### PR TITLE
BarChart: updates component to use new theme functions.

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR updates component to use new theme functions.
**Which issue(s) this PR fixes**:

Relates to #33264

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
This must surely break a lot of other things? the BarChart extends Themeable which uses the old theme and all the UPlot config builders use the old theme. Did you test the BarChart after this?

**Comment by thisisobate** [comment]
My bad. Actually, I felt since we have `withTheme2`, Themeable should be updated with the new theme model as well.
I tested using storybook and it seems to be working fine.

Any plans to update Themeable with the new Theme model soon? if yes, then I can pause this for now. Otherwise, I could open a PR that updates Themeable and its corresponding components that use it.

WDYT? @torkelo

**Comment by torkelo** [comment]
need a Themeable2

**Comment by thisisobate** [comment]
Okay. Would open a PR for Themeable 2 then

**Comment by thisisobate** [comment]
fixed: #33502

**Pull request closed without merging**
