### PR TITLE
Docs: Add `implementation` key in data source table

### PR DESCRIPTION
**Pull request by elthariel**
The implementation field that seems to be used by the alertmanager data source config wasn't documentated

**What is this feature?**

A minor documentation update about a missing field

**Why do we need this feature?**

It's used by the UI but was hard to use in automated provisionning since it wasn't documented

**Special notes for your reviewer**:

Hey !

I hope you're having a great day !

### CODE REVIEW

**Comment by daniellee** [comment]
@grafana/alerting-squad this PR looks correct but also shows up some inconsistencies with casing:

- The values for `prometheusType` are in camel case (Cortex, Mimir, Prometheus, Thanos) : https://github.com/grafana/grafana/blob/main/public/app/types/unified-alerting-dto.ts#L58-L63
- The values for `implementation` are in lower case (cortex, mimir, prometheus): https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/alertmanager/types.ts#L292-L296

**Comment by elthariel** [comment]
@daniellee. Yeah, I've notived, but I preferred documenting the values I've seen working. Is this case-insensitive ?

**Comment by brendamuir** [comment]
@grobinson-grafana can you confirm on the values?

**Comment by gillesdemey** [comment]
I think we're all looking at the wrong enum for the AM implementation type :) 

The correct one is

https://github.com/grafana/grafana/blob/16c6f223baa7303b183657333ddee3119fcb8ab8/public/app/plugins/datasource/alertmanager/types.ts#L292-L296

**Review by gillesdemey — APPROVED** [review]

**Pull request merged**
