### PR TITLE
EmbeddedDashboard: Fix padding issue

### LINKED ISSUE #85961: EmbeddedDashboard: The height of the grid is 0
### What happened?

Captura de pantalla 2024-04-11 a las 16 49 35

The height is 0 when the container doesn't have 100% of height

### What did you expect to happen?

The grid should get the height of the content

### Did this work before?

This broke because of [this change](https://github.com/grafana/scenes/pull/658/files#diff-8c644dc1964a11531c0b83bf5a2b2d8c70714575018c852146d894a8de03a262L20)

### How do we reproduce it?

1. Run Grafana locally and go to the route http://localhost:3000/dashboards/embedding-test
2. Remove `layout={PageLayoutType.Canvas}` from `EmbeddedDashboardTestPage` component
3. You will see the height is 0 for the grid layout

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by torkelo**
Fixing the extra padding around controls that was introduced in the scopes PR 

Also fixes https://github.com/grafana/grafana/issues/85961

### CODE REVIEW

**Review by bfmatei — APPROVED** [review]

**Comment by ivanortegaalba** [comment]
Testing it in different scenarios 👀

**Comment by ivanortegaalba** [comment]
@torkelo this is an alternative approach, so we don't force consumers to have flex parents or parents with height. It just grows with the content.

https://github.com/grafana/scenes/pull/693

**Comment by torkelo** [comment]
@ivanortegaalba nice! Was going to try disabling height there, that is better!

**Comment by torkelo** [comment]
@ivanortegaalba any update on that?

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Pull request closed without merging**
