### PR TITLE
Plugins: Make "README" the default markdown request param

### PR DESCRIPTION
**Pull request by wbrowne**
**What is this feature?**
Replaces the default plugin markdown file request from `help.md` to `README.md`

**Why do we need this feature?**
All core plugins have `README.md` as well as (seemingly) most community plugins. We will still try fallback to `help.md/HELP.md`, but will instead prioritize `README/readme` first.

**Who is this feature for?**
All Grafana users browsing plugins via the catalog / details page

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Review by jackw — APPROVED** [review]
Awesome work @wbrowne! 🚀

**Review by leventebalogh — APPROVED** [review]
🙌

**Comment by Bujupah** [comment]
LNGTM actually... :/
This broke how the help is working in most of datasource plugins.

**Comment by murtazaqa** [comment]
Was the default plugin markdown file replaced from `help.md` to `README.md` or is the other way round?

**Comment by wbrowne** [comment]
@Bujupah Can you share what plugins were affected? `HELP.md`/`help.md` should be still used as a fallback.

@murtazaqa the change was to prioritize `README.md`/`readme.md` first, otherwise we will still try fallback to `HELP.md`/`help.md`.

**Comment by Bujupah** [comment]
@wbrowne 
I tried Postgres, Json API, Promethius, etc... 

The rest api call is always going to `/api/plugins/<plugin-id>/markdown/query_help`

query_help is hardcoded in this file public\app\features\query\components\QueryGroup.tsx
```tsx
<Modal title="Data source help" isOpen={true} onDismiss={this.onCloseHelp}>
  <PluginHelp plugin={dsSettings.meta} type="query_help" />
</Modal>
```

**Comment by wbrowne** [comment]
Ah I see what's wrong - apologies for that @Bujupah. Will get a fix up and into the next 9.3 patch release

**Pull request merged**
