### PR TITLE
Chore: Remove md5 dependency and use uuid/v5 instead

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Removes the `md5` dependency used to generate IDs and uses `uuid/v5` instead, which uses SHA-1.

**Special notes for your reviewer**:
Relates to #34129

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]
Looks good, works as expected. 🙂

**Review by jackw — APPROVED** [review]
Great stuff @kaydelaney! 🚀

**Review by hugohaggmark — COMMENTED** [review]
@kaydelaney should we change all existing v4 to v5 too?

**Comment by hugohaggmark** [comment]
@kaydelaney you need to merge with main to get a fix for those failing backend tests

**Comment by jackw** [comment]
Can the `@types/md5` dependency be removed too?

**Comment by kaydelaney** [comment]
> @kaydelaney should we change all existing v4 to v5 too?

Not sure! Main reason I used v5 here is because it seemed like the existing code called for a hash, but I suppose there might be other instances where that's appropriate as well? Could investigate and make a separate PR if so.

**Pull request merged**
