### PR TITLE
Navigation: Use navid and pagnav in alert rules pages

### LINKED ISSUE #55109: Page layout: Alert rules -> New alert

### LINKED ISSUE #55112: Page layout: Alerting -> Alert rules -> View alert rule

### LINKED ISSUE #55113: Page layout: Alerting -> Alert rules -> Edit alert rule
- [ ] convert to use `navId` instead of `navModel`
- [ ] add `subTitle`
- [ ] add `pageNav` (see `TeamPages`)

### PR DESCRIPTION
**Pull request by lpskdl**
**What this PR does / why we need it**:
- use navId and pageNav for alert rules' edit, add and view rule pages
- move smaller components inside `RuleEditor` to its own file
- adjusted padding and margins to fit the new layout

**with topnav on**
Screenshot 2022-09-26 at 10 14 35**
Screenshot 2022-09-26 at 13 39 43
Screenshot 2022-09-26 at 13 39 31

**with topnav off**

**Which issue(s) this PR fixes**:
Screenshot 2022-09-26 at 13 38 21
Screenshot 2022-09-26 at 13 37 38
Screenshot 2022-09-26 at 13 37 31

Fixes #55112
Fixes #55109
Fixes #55113 

**Special notes for your reviewer**:
- I replaced `PageToolbar` with `HorizontalGroup`. Let me know if its ok. The reason is that it is going to be redundant to display the title again in that toolbar and also to remove the grey background provided by `PageToolbar`(this is to be consistent how other pages displays the action buttions)

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
think this looks great, but we should definitely wait for a review from @grafana/alerting-squad-frontend as these aren't trivial changes 🙂

**Comment by lpskdl** [comment]
Hi @torkelo ,

About the width size of the page. I compared the size of the empty space between **main** and this **branch** and it seems pretty much the same it is just placed differently. This branch placed the page at the center while the one in the main branch placed the page on the left side. 

**Main branch (view and add/edit)**
Screenshot 2022-09-28 at 09 17 35
Screenshot 2022-09-28 at 09 14 56

**This branch (view and add/edit)**
Screenshot 2022-09-28 at 09 19 30
Screenshot 2022-09-28 at 09 12 08

With these observation, is it ok if we stick with the one we have with this branch(page is placed at the center) to avoid additional complexity supporting full page width and also be consistent with how other pages are displayed?

let me know your thoughts

**Review by torkelo — COMMENTED** [review]
@lpskdl yea, I agree. Looks good!

**Review by gillesdemey — APPROVED** [review]
Great work! Changes LGTM 🚀

**Pull request merged**
