### PR TITLE
Provisioning: orgs

### PR DESCRIPTION
**Pull request by sathieu**
**What is this feature?**

Add support for provisioning Orgs thru files.

**Why do we need this feature?**

We currently create several orgs, manually.

We want to automate this.

**Who is this feature for?**

Users with multiple Orgs wanting to create those with provisioning.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
Will hold off on docs review until a maintainer has reviewed the feature and the code.

Please @ me or re-request my review once that has happened.

**Comment by ryantxu** [comment]
Thanks for the contribution!  The grafana provisioning system is pretty gnarly and each type requires lots of special handling. 
 We do not want to add more to this system 😬.  For automation, i recommend writing against the api endpoints.  https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/grizzly/ may be a good place to look. 

Longer term -- we are shifting everything towards k8s resource models.  This will allow (almost) everything to be provisioned using standard kubectl style tooling

**Comment by sathieu** [comment]
@ryantxu OK. I created https://github.com/grafana/grizzly/issues/268.

Still, I find it sad to refuse this contribution. This is adding value.

**Comment by sathieu** [comment]
@ryantxu I'm coming again on this PR (that you closed).

This is hard to find a complete solution for my usecase, all of the evaluated solutions have missing features :

- Provisioning orgs:
  - Grafana provisioning is not able to create Orgs, unless *this PR* is merged
  - Grizzly has no Org management (https://github.com/grafana/grizzly/issues/268). This would need an Admin token.
  - Grafana Operator has no Org support (see [here](https://github.com/grafana-operator/grafana-operator/blob/d1d71a9e4d1592b92232d5a61e766a683d5dce83/controllers/client/grafana_client.go#L150)), and this would need a complete redesign
- Using OrgName instead of OrgId for datasources and dashboards:
  - Grafana provisioning is not able to use OrgName for datasources and dashboards (I created [grafana#76937](https://github.com/grafana/grafana/pull/76937) which is blocked by an [unscheduled UID migration](https://github.com/grafana/grafana/issues/77282#issuecomment-1810721909))
  - Grizzly has no support for OrgName in datasources and dashboards (I just created https://github.com/grafana/grizzly/issues/278). This is probably no possible as Grizzly uses SDK which has no support for OrgName either
  - Grafana Operator has no OrgName eiher, with the same limitations as Grizzly

Also we currently don't use Grizzly or Grafana Operator. Adding another item in the stack would increase complexity.

You are saying that provisioning has special handling (readonly/editable). I have not done any of this. If wanted I can.

Any chance to reconsider you closing?

**Comment by sathieu** [comment]
Hello,

We ended up writing our Kubernetes Operator to manage:

- GrafanaInstances (i.e. connection to API)
- GrafanaOrgs
- GrafaOrgDatasources
- GrafanaOrgDashboards

It' available at: https://gitlab.com/kubitus-project/grafana-org-operator/#grafana-org-operator. Feedback welcome!

**Pull request closed without merging**
