### PR TITLE
Convert TOML front matter to YAML

### PR DESCRIPTION
**Pull request by jdbaldry**
**What this PR does / why we need it**:

Uses front matter consistent with all other Grafana repositories, resulting in less mental overhead for technical writers.

### CODE REVIEW

**Review by chri2547 — APPROVED** [review]
LGTM!

**Comment by jdbaldry** [comment]
Thank you @chri2547 and @achatterjee-grafana for taking a look at this PR. If you are happy, it would be good to get this merged so that it can reduce the timeframe for conflicts.

**Comment by achatterjee-grafana** [comment]
Does it need a backport?

**Comment by jdbaldry** [comment]
Good question, I think a backport would be useful to have consistent front matter across all files but I believe it is likely that this specific patch will have conflicts on the older branches. I could open individual PRs instead, one for each release branch?

**Comment by achatterjee-grafana** [comment]
> Good question, I think a backport would be useful to have consistent front matter across all files but I believe it is likely that this specific patch will have conflicts on the older branches. I could open individual PRs instead, one for each release branch?

Makes sense, change the label to `no-backport`.

**Pull request merged**
