### PR TITLE
Update behind_proxy.md

### PR DESCRIPTION
**Pull request by vskubriev**
Grafana has an issue since some latest versions:

https://github.com/grafana/grafana/issues/5964

I'd like to add some info how to fix he problem.

How we can update site documentation ?

http://docs.grafana.org/installation/behind_proxy/

### CODE REVIEW

**Comment by torkelo** [comment]
There has been no change here and nginx has no relation to this problem. 
#5964 is an old issue for influxdb 0.8 when it is behind an nginx proxy (not grafana).

**Comment by vskubriev** [comment]
May be I must re-write my doc update regards influxdb, not grafana and create a new pull request ?

I think it is important info, many of users can use old (out-dated) versions of influx with grafana.

One possible reason is that tutum/influxdb docker image is very powerful compared to library/influxdb image. And tutum/influxdb uses influxdb 1.0 which is slightly out-dated.

**Comment by torkelo** [comment]
not sure why though, not seeing anything different with  tutum/influxdb and we have no other reports of this problem. Must be something specific to your setup?

**Comment by vskubriev** [comment]
Suggested solution "change datasource type to proxy" solving the issue. This additional info will may be useful. Okey, forget. If you think so.

**Comment by torkelo** [comment]
that is the default value for that option.

**Pull request closed without merging**
