### PR TITLE
BarGaugePanel - Set max value to max of data sample when input is empty

### LINKED ISSUE #17206: Bar Gauge should have option for automatically detecting min/max width
Currently the Bar Gauge works very well when know know the range of values ahead of time. But in cases where the max value is unbounded, it is less useful. You end up having to pick an arbitrary max value. In cases where that max is too high, the bars end up taking a small fraction of the available real-estate. If the max is too low you end up with multiple bar that reach the end and are truncated, making the values look identical.

**What would I like to be added:**

There should be an "auto" option for both the max and min values. It would go through the repeated series fine the actual range, and use that. Just as it would work for any timeseries on a normal Graph.

**Why is this needed:**

Grafana allows you a lot of flexibility with templates and date controls to change the target of a query, and if you are using Bar Gauge to measure anything that does not have a clear cut range, with well-defined thresholds, it does not work as well as it could. Letting the max and min values be auto-detected from the data series would make it a good tool for visualizing data where you want to see the values relative to themselves, not a predefined range.

**Example use-case:**

If you wanted to visualize a user's time spent working with various applications over the past variable amount of time (or even lifetime) with the aim to show a preference, or help visualize productivity. The Bar Gauge is a clean, visually appealing way of displaying that data, but there is no good way to pick a good max value that will work for every user and every timerange.

### PR DESCRIPTION
**Pull request by YuriSS**
Fixes https://github.com/grafana/grafana/issues/17206

### CODE REVIEW

**Comment by torkelo** [comment]
@ryantxu maybe this should not be on the panel level and inside the getFieldDisplayValues?

**Comment by ryantxu** [comment]
I was thinking about this today -- for sure it should not be *just* in BarGauge, the same issue exists in other panels that want a %

I think `getFieldDisplayValues` or more likely its sucessor :) is the right place.  The key question is how to know that we should calculate min/max.  Perhaps we need to add a parameter like `wantsScale` or `wantsPercent` -- in d3 "scale" is 0-1 and typically maps to color scale

**Comment by YuriSS** [comment]
If we put inside a successor of getFieldDisplayValues we will need to pass all data forward. I will try a new approach passing a parameter like you said.

**Comment by tiger-seo** [comment]
@YuriSS please, suggest, how can i use your fixed bargauge plugin on the existing grafana instance in docker

**Comment by torkelo** [comment]
Closing this due to in-activity, if you have a new approach that is more generic then open a new PR or we can re-open this PR

**Pull request closed without merging**
