### PR TITLE
Revert "Test datasource: Returns always float values (#34986)"

### PR DESCRIPTION
**Pull request by papagian**
This reverts commit 51afde34bd935cd3b6c65032fabebe5db7ccdf4f.

**What this PR does / why we need it**:
After merging #34996 this change in test datasource is no more required 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]

**Review by kylebrandt — DISMISSED** [review]
I question if an Int is correct... I understand that this change was made so it would work with SSE, and now that it does, that is why we are reverting it.

But if this loads CSV values, don't we want to be able to parse floats?

**Comment by papagian** [comment]
> I question if an Int is correct... I understand that this change was made so it would work with SSE, and now that it does, that is why we are reverting it.
> 
> But if this loads CSV values, don't we want to be able to parse floats?

If it fails to parse int, it will [try](https://github.com/grafana/grafana/blob/4ee7e81d6bfec19098628f46fc6c90d1f27a5ea2/pkg/tsdb/testdatasource/csv_data.go#L207) to parse floats, but honestly I don't know if we actually want to revert this: I have just opened the PR mainly for discussing this option.

**Comment by ryantxu** [comment]
I added support for int values so we could easily create them for tests :)  It appears some things break unexpectedly when we give it int values rather than floats :)

If we are talking about generic csv support than yes always float64 makes sense

**Review by ryantxu — APPROVED** [review]
Thanks @papagian -- this is useful so we can make int fields easily.... that apparently break alerting :)

**Comment by papagian** [comment]
> Thanks @papagian -- this is useful so we can make int fields easily.... that apparently break alerting :)

@ryantxu do you think that it should go to 8.0.1 milestone then? (currently it's targeting 8.1.0)

**Pull request merged**
