### PR TITLE
Add GitHub action labeler, first for alerting

### PR DESCRIPTION
**Pull request by armandgrillet**
This action will automatically labels PRs changing specific files.
This will first be used to add a label `area/alerting` to PRs affecting files related to alerting. This label will trigger some automation on Slack.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
we have this already for PRs, can you check with @marefr just so we don't introduce two systems/tools to do the same thing

**Comment by torkelo** [comment]
this file looks to be relevant: https://github.com/grafana/grafana/blob/main/.github/pr-commands.json

**Comment by armandgrillet** [comment]
@torkelo Oh thanks for catching this, I had done a grep for `labeler` and looked at the filenames in `.github` but didn't notice that this existed already.

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
