### PR TITLE
Reduce the amount of thresholds values to two in singlestat panel

### LINKED ISSUE #3248: Coloring in singlestats panel can't handle negative values
Hey @torkelo , thanks for the super great software!

In one of our usecases we calculate change in percentage over time and displays the data in a single stats panel. If nothing has changed we show 0%, positive change +X % and negative -Y%. 

I can't get coloring to work if a value is negative, as soon as it goes below 0 the coloring disappears, no matter what values I configure (or at least the ones I have tested). Should it work or am I missing something? For us it would be cool because in some cases negative change is actually positive, so it would be nice make that more understandable :)

Best
Peter

### PR DESCRIPTION
**Pull request by bergquist**
fixes #3248

50,80 will produce: <50 = Green, 50:80 = Yellow, >80 = Red

### CODE REVIEW

**Comment by daniellee** [comment]
:star2: Great fun pair programming on this and figuring out that it was more logical with two thresholds than with three when you have three colors.

**Comment by bbinet** [comment]
Great, it actually makes sense to have only 2 threshold for 3 colors!

It would also be great if we could configure some more thresholds with additional colors.

**Comment by daniellee** [comment]
@bbinet Configurable thresholds will hopefully come in the future when the [alerting feature](#2209) is built.

**Comment by clongbottom** [comment]
Good work. What about an option for a gradient between the two colours chosen?

**Comment by bbinet** [comment]
Great, thanks!

**Comment by daniellee** [comment]
@clongbottom how would that work? Not sure I follow.

**Comment by clongbottom** [comment]
@daniellee let's say user picks 0,100 for thresholds, and red, orange and green for colours. Although discrete information is useful, being able to represent 50 as being half way between orange and green allows the user to figure spot trends. A simple way to arrive at the resultant colour is by using the HSL values of the two colours and then taking proportions from each. so assuming the orange and green have the same saturation and lightness, 50 would represent a hue halfway between green and orange. This value can then be converted back to hex RGB value, or whatever is required.

**Pull request merged**
