### PR TITLE
Docs: Update README.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Minor grammar and format edits

### CODE REVIEW

**Review by marcusolsson — APPROVED** [review]
Great stuff as always! 👍 I commented on a few things that wasn't part of your fix, but could be improved. Let me know if you want to fix them, or I'll merge this as is.

**Comment by oddlittlebird** [comment]
Thanks for catching the typos!

Per Merriam-Webster, "prerelease" is not hyphenated. https://www.merriam-webster.com/dictionary/prerelease

I suggest we leave it as-is.

**Comment by marcusolsson** [comment]
Oh, didn't know that! Let's leave it as is then! This pull request has a conflict we need to fix before merging. Let me know if you need any help with this.

**Comment by oddlittlebird** [comment]
Conflicts resolved, please have an SME review the instructions to make sure they are not missing anything important.

**Pull request merged**
