### PR TITLE
Implement 'message_thread_id' for Telegram Alert Channel

### LINKED ISSUE #82692: Telegram topics support
### Discussed in https://github.com/grafana/grafana/discussions/68527

<div type='discussions-op-text'>

<sup>Originally posted by **hoboroten** May 16, 2023</sup>
Hi.
Recently Telegram added support for Topics in Groups in Bot API. Will it be added to Telegram Alert Channel configuration? As far as i can see - there must be an opportunity to set message_thread_id parameter.</div>

### PR DESCRIPTION
**Pull request by TFyre**
**What is this feature?**

Add `message_thread_id` configuration for Telegram Alert Channel (https://core.telegram.org/bots/api#message)

**Why do we need this feature?**

Allows the user to send telegram messages to a specific message thread.

**Who is this feature for?**

Users who want fine grained control over Telegram alerts.

**Which issue(s) does this PR fix?**:

Fixes #82692

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by grobinson-grafana — CHANGES_REQUESTED** [review]
Hello! 👋 Thanks for the contribution, however I'm afraid you've updated Legacy Alerting which is deprecated and is being removed in Grafana 11. If you are looking to add it to Grafana Alerting, I'm afraid someone else has added this feature [here](https://github.com/grafana/alerting/pull/143).

**Comment by TFyre** [comment]
can you please link some documentation on setting that up?

the only i found is this: https://grafana.com/blog/2023/12/28/how-to-integrate-grafana-alerting-and-telegram/

and this doesnt seem to have `message_thread_id` available for configuration.

**Comment by grobinson-grafana** [comment]
Hi! :wave:

I don't think it will be in that blog post as it's from December, and the feature was merged just this month. Most of our contact points use documentation within the UI:

Screenshot 2024-02-25 at 12 56 04 PM

You should be able to use this feature from Grafana versions 10.4 and 11.

**Comment by TFyre** [comment]
Neither does the current UI... which is why I wanted to merge this...

**Comment by grobinson-grafana** [comment]
Hi! So if you are using Grafana open source and enterprise then it should be released in the upcoming versions of Grafana 10.4 and Grafana 11. The pull request was merged just a couple weeks ago, so it won't be available until those versions are released.

**Pull request closed without merging**
