### PR TITLE
TablePanel: Fix annotations display issue (backport)

### PR DESCRIPTION
**Pull request by ryantxu**
Fixing #17639 for the 6.2x branch

#17646 fixed this in 6.3x branch, but applying that to 6.2 does not work

### CODE REVIEW

**Comment by marefr** [comment]
This would only be needed in case we do another 6.2 patch release before v6.3 stable. But currently it looks like that will happen.

**Review by torkelo — APPROVED** [review]

**Comment by marefr** [comment]
@simPod we're currently releasing v6.3-beta1 which includes #17646. 

This was added to v6.2.6 milestone, but we currently have any plans releasing v6.2.6 in case anything more urgent needs to be patched and/or more users are reporting need of v6.2.6.

**Comment by simPod** [comment]
@marefr I tried `master` branch 2h ago but there were probably some breaking changes and no panels were able to display any data, had no time to investigate that yet.

**Comment by marefr** [comment]
@simPod sorry for that, would recommend trying again :smile: Or use v6.3.0-beta1 which was released yesterday.

**Comment by simPod** [comment]
@marefr  I noticed tagged beta3, rebased my fork on top and it works. Thanks!

**Comment by marefr** [comment]
@simPod thanks for the confirmation

**Pull request merged**
