### PR TITLE
Auth AzureAD: Add details for enabling group attributes to docs

### PR DESCRIPTION
**Pull request by nathanwebsterdotme**
**What this PR does / why we need it**:
Documentation update to ensure the Application Manifest in Azure AD is configured correctly to allow the `allowed_groups` configuration option to work.

### CODE REVIEW

**Review by oddlittlebird — APPROVED** [review]
Thanks for contributing to the docs! Please sign the CLA and then we can merge this.

**Comment by nathanwebsterdotme** [comment]
@oddlittlebird I've signed it twice but not sure why it's not passing the test!

**Comment by nathanwebsterdotme** [comment]
@oddlittlebird good to go!

**Comment by oddlittlebird** [comment]
Thanks for the contribution!

**Pull request merged**
