### PR TITLE
Prometheus: Add Uniform Exemplar Sampler

### PR DESCRIPTION
**Pull request by toddtreece**
**What is this feature?**

This sampler splits the time range into 100 buckets, and returns a max of 10 samples per bucket for each series.

**Why do we need this feature?**

Requested by @leeoniya 

**Who is this feature for?**

@leeoniya 

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by chri2547 — COMMENTED** [review]
Docs change looks fine. Thank you!

**Review by itsmylife — APPROVED** [review]
🚀

**Review by nmarrs — APPROVED** [review]
LGTM - any blockers on getting this one merged as well?

**Comment by toddtreece** [comment]
@itsmylife @gtk-grafana i'm going to close this one since the approach needs to be changed to the value bucketing we discussed

**Pull request closed without merging**
