### PR TITLE
DevEnv: update frontend dependencies - rc

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Mar 23 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

No significant changes.

### CODE REVIEW

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
I get this error locally:
```
ERROR in /Users/hugo/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Cascader/Cascader.tsx(199,13):
[Webpack] TS2740: Type 'SelectableValue<string[]>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.
```

looks to be the same on CI:
```
{
    rawMessage: "ERROR TS2740: Type 'SelectableValue<string[]>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.",
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/Cascader/Cascader.tsx(199,13):\n' +
      "TS2740: Type 'SelectableValue<string[]>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.",
    location: { line: 199, character: 13 },
    file: '/root/project/packages/grafana-ui/src/components/Cascader/Cascader.tsx'
  }
```

Storybook fails locally too:
```
ERROR in /Users/hugo/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/ButtonCascader/ButtonCascader.tsx(21,4)
      TS2322: Type '{ children: Element; expandIcon: null; options: CascaderOption[]; disabled?: boolean | undefined; value?: string[] | undefined; fieldNames?: { label: string; value: string; children: string; } | undefined; loadData?: ((selectedOptions: CascaderOption[]) => void) | undefined; onChange?: ((value: string[], selectedOpt...' is not assignable to type 'Partial<Pick<Readonly<CascaderProps> & Readonly<{ children?: ReactNode; }>, "onChange" | "value" | "children" | "disabled" | "defaultValue" | ... 17 more ... | "loadingIcon">>'.
  Types of property 'onChange' are incompatible.
    Type '((value: string[], selectedOptions: CascaderOption[]) => void) | undefined' is not assignable to type '((value: string[], selectOptions: CascaderOption[]) => void) | undefined'.
      Type '(value: string[], selectedOptions: CascaderOption[]) => void' is not assignable to type '(value: string[], selectOptions: CascaderOption[]) => void'.
        Types of parameters 'selectedOptions' and 'selectOptions' are incompatible.
          Type 'import("/Users/hugo/go/src/github.com/grafana/grafana/node_modules/rc-cascader/lib/Cascader").CascaderOption[]' is not assignable to type 'import("/Users/hugo/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Cascader/Cascader").CascaderOption[]'.
            Type 'import("/Users/hugo/go/src/github.com/grafana/grafana/node_modules/rc-cascader/lib/Cascader").CascaderOption' is not assignable to type 'import("/Users/hugo/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Cascader/Cascader").CascaderOption'.
              Property 'value' is optional in type 'CascaderOption' but required in type 'CascaderOption'.
```

**Comment by mckn** [comment]
Had a look at the issues and there are a lot of changes in the `rc-cascader`. I think @tskarhed would be a lot of help doing this upgrade.

**Comment by tskarhed** [comment]
Did some changes to re-map the values

**Comment by mckn** [comment]
@Estrax me and @tskarhed have done some work to get the `rc-cascader` to work. Will do some more testing tomorrow to see that everything else works as expected.

**Comment by Estrax** [comment]
@mckn @tskarhed awesome! Thanks guys!

**Review by hugohaggmark — APPROVED** [review]

**Comment by ivanahuckova** [comment]
I can see that rc-slider was updated from  8.7.1 -> 9.2.3 in grafana-ui package. 8.7.1 is the version we want because in later ones, the tooltip was buggy due to one of the rc-slider's dependency (and also easy-fixable problem). I will create PR to set it to 8.7.1, but should I add comment somewhere (not sure where) so we don't update it/check if the new versions slider's tooltip is working smoothly and as expected?

**Pull request merged**
