### PR TITLE
Add plugin spellcheck docs

### PR DESCRIPTION
**Pull request by cletter7**
Recently the spellcheck CI step became mandatory for all internal plugins. When spellcheck is not configured for the plugin, the CI step fails and gives a link to the docs with explanation on how to configure it ([example](https://drone.grafana.net/grafana/grafana-iot-twinmaker-app/382/1/4)). Initially this docs page was put inside private repo, which makes it inaccessible for people outside the organization. So we are putting it in a public space.

We are thinking to link the `*.md` file in the CI and not the page on grafana.com. Let me know please if there is more suitable place for this.

### CODE REVIEW

**Review by yesoreyeram — APPROVED** [review]

**Comment by jdbaldry** [comment]
@josmperez @cletter7 This page is appearing in our technical documentation for Grafana without a title and is causing an empty menu item in the ToC: https://grafana.com/docs/grafana/v9.4/developers/plugins/plugin-spellcheck/.

I am not certain that this should be in the website technical documentation but if it should, it needs the front matter defined in https://grafana.com/docs/writers-toolkit/writing-guide/front-matter/.

**Comment by cletter7** [comment]
@jdbaldry I didn't know that.
I can add the front matter, though since the spellcheck is enforced only for internal plugins at the moment, it's not needed to make this page public. Is there a way to hide it? Or maybe is there a better place for it? Do you have any advice here?

**Comment by jdbaldry** [comment]
Thanks for the quick reply!

If we don't want to list the page on the website but still link to the URL we can "unlist" the page with the following front matter:
```yaml
_build:
  list: false
```

If we don't want the page to be built at all we can "draft" the page with the following front matter:
```yaml
draft: true
```

**Comment by cletter7** [comment]
Thank you.
Added `draft: true`
PR: https://github.com/grafana/grafana/pull/64113

**Pull request merged**
