### PR TITLE
grafana/ui: Update react-hook-form to version 7.5.3

### LINKED ISSUE #34200: Can't save notification channel
**What happened**:
When creating a notification channel and clicking on the Save button nothing happens and the new notification channel is not being saved.

https://user-images.githubusercontent.com/1170767/118482002-11241500-b70c-11eb-822c-eea8acf88f70.mov

**What you expected to happen**:
The notification channel should be saved correctly

**How to reproduce it (as minimally and precisely as possible)**:
Try to create a new notification channel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8 (beta1)
- Data source type & version: N/A
- OS Grafana is installed on: Mac OS
- User OS & Browser: Mac OS / Firefox 89
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Upgrade react-hook-form to version 7.5.3, as the previous versions seem to have a bug where the fields are not being unregistered properly when they're removed. I tried upgrading to the latest 7.6.0 version, but it had some bug with Select `onChange` not working properly, so better wait till that is fixed.  
**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/34200

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Elfo404 — DISMISSED** [review]
🚀

**Comment by domasx2** [comment]
oh nooo I have to test everything again now :D

**Review by hugohaggmark — APPROVED** [review]
Tested:
- ChangePassword
- Folder permissions
- Login
- UserCreatePage

Seems to work great AFAIK

**Review by domasx2 — APPROVED** [review]
tested unified alerting stuff, did not find any issues :+1:

**Pull request merged**
