### PR TITLE
Tempo: Add `}` when `{` is inserted automatically

### PR DESCRIPTION
**Pull request by harrymaurya05**
**Which issue(s) does this PR fix?**:
Adding } when { is inserted automatically

Fixes #74027

https://github.com/grafana/grafana/assets/22474692/4ce2c77f-a317-40dd-b72d-44d003fb3175

### CODE REVIEW

**Review by fabrizio-grafana — APPROVED** [review]
Well done! Thank you!
It just seems some tests fail locally. Could you check and possibly fix them?

**Review by fabrizio-grafana — COMMENTED** [review]
This is the test suite that seems to fail: public/app/plugins/datasource/tempo/traceql/autocomplete.test.ts

**Comment by harrymaurya05** [comment]
> Well done! Thank you! It just seems some tests fail locally. Could you check and possibly fix them?

Thanks for highlighting the failing test suite in `autocomplete.test.ts`. I'll investigate the issue and work on resolving the test failures. I'll provide updates as soon as I have more information or when the issue is resolved.

**Comment by harrymaurya05** [comment]
Hi @fabrizio-grafana 
Issue identified:
Test case are not updated as per new change for empty input. now fixes are added in current changes please review and provide you valuable inputs.

yarn test summary:
2 test case are still but its not related to current changes. you can correct me if i am missing something.

Summary of all failing tests
 FAIL  public/app/features/explore/spec/split.test.tsx (70.239 s)
  ● Handles open/close splits and related events in UI and URL › handles split size events and sets relevant variables

    thrown: "Exceeded timeout of 30000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      180 |   });
      181 |
    > 182 |   it('handles split size events and sets relevant variables', async () => {
          |   ^
      183 |     setupExplore();
      184 |
      185 |     const splitButton = await screen.findByText(/split/i);

      at public/app/features/explore/spec/split.test.tsx:182:3
      at Object.<anonymous> (public/app/features/explore/spec/split.test.tsx:38:1)

 FAIL  public/app/features/explore/spec/queryHistory.test.tsx (139.943 s)
  ● Explore: Query History › updates the state in both Explore panes › deleted queries are synced

    thrown: "Exceeded timeout of 30000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      141 |
      142 |   describe('updates the state in both Explore panes', () => {
    > 143 |     beforeEach(async () => {
          |     ^
      144 |       const urlParams = {
      145 |         left: serializeStateToUrlParam({
      146 |           datasource: 'loki',

      at public/app/features/explore/spec/queryHistory.test.tsx:143:5
      at public/app/features/explore/spec/queryHistory.test.tsx:142:3
      at Object.<anonymous> (public/app/features/explore/spec/queryHistory.test.tsx:81:1)


Test Suites: 2 failed, 1 skipped, 1278 passed, 1280 of 1281 total
Tests:       2 failed, 27 skipped, 11610 passed, 11639 total
Snapshots:   334 passed, 334 total
Time:        557.762 s
Ran all test suites.

**Comment by harrymaurya05** [comment]
> @harrymaurya05 it seems the [CI linting check is failing](https://drone.grafana.net/grafana/grafana/153259). Can you run `yarn run prettier:check` and push the changes? Thanks!

Hi @fabrizio-grafana 
can you please help with what should do to find and fix issue mentioned in command `yarn run prettier:check ` output.
Harioms-MacBook-Air:grafana hariommaurya$ yarn run prettier:check 

[warn] public/app/plugins/datasource/tempo/traceql/autocomplete.test.ts
[warn] public/app/plugins/datasource/tempo/traceql/autocomplete.ts
[warn] Code style issues found in 2 files. Run Prettier to fix.

**Comment by harrymaurya05** [comment]
> Amazing job! Merged!

Hello @fabrizio-grafana ,

Thank you so much for your kind words and for merging the pull request! This is my first even contribution in open source project. I really appreciate your guidance and support throughout this process. I've learned a many things by working on this issue.
Looking forward to continuing to contribute more in grafana. Thanks again!

Best regards,
Hariom Maurya @harrymaurya05

**Pull request merged**
