### PR TITLE
Tempo: Trace View - Search bar to absolute position instead of sticky

### LINKED ISSUE #57273: Tempo explore panel scrolling to the top all the time
**What happened**:
1. Go to explore tab
2. Select Tempo data source
3. Enter a Trace-Id
4. Search
5. Trace graph displays. 
6. For long traces that covers the whole screen, one has to scroll down.
7. After scrolling down, move the mouse cursor.
8. :warning: The trace view automatically scrolls up to the top again whenever the mouse cursor is just moved.

**What you expected to happen**:
Trace graph displays, possible to scroll down, move the mouse and click inside the trace to expand rows.

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
This worked fine in Grafana 9.1.6

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: Tempo
- User OS & Browser: Firefox

### LINKED ISSUE #57985: Minified React error #185 on Grafana Cloud trace view
**What happened**:

- Browse to **trace view** on Grafana Cloud 'Explore' page
- Open a trace by ID and expand some of the spans + span fields

**What you expected to happen**:

I can browse the fields and spans properly, highlighting any text to copy paste etc

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

Reproduced in Incognito tab with no extensions, does **not** reproduce on Chromium 107.0.5304.68

image

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

f@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:4425:2518
jt@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:5050:594
WithTheme(undefined)
div
U@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:5229:58
WithTheme(undefined)
R@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:7624:145
div
div
div
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:247:390
Qs@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/explore.278ac94d79c0c9010b9c.js:480:1986
c@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:301
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:855
c@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:301
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:855
main
div
t@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:1168940
div
div
div
t@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:681364
p@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:420:3558
Ys@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/explore.278ac94d79c0c9010b9c.js:480:3181
WithTheme(undefined)
g@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:999564
div
so@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/explore.278ac94d79c0c9010b9c.js:501:2811
g@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:999564
WithTheme(Connect(so))
c@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:301
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:855
div
div
po@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/explore.278ac94d79c0c9010b9c.js:517:157
g@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:999564
Suspense
c@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:301
kn@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:5514:360
t@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:1014882
t@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:1016903
main
st@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:5475:13057
t@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:1011500
div
o@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:2035:4592
19175/t.KBarProvider@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:261503
l@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:6236:19191
c@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:301
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:1194:855
y@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:2892428
u@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:6229:10875
l@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/4713.232e2ff90daf715727af.js:2:997607
ss@https://grafana-assets.grafana.net/grafana-pro/9.2.2-eb6f0ffe76/public/build/3191.b435f28b2412ca47983f.js:5527:167
```

**Environment**:
- Grafana version: Cloud
- Data source type & version: Tempo (whatever version is on Cloud)
- OS Grafana is installed on: Cloud
- User OS & Browser: Arch Linux + Firefox 106.0.1 
- Grafana plugins: unknown

### LINKED ISSUE #59490: TraceView: List rendering broken in Firefox
When scrolling in a trace view with more than 200 spans in Firefox, the trace view throws an error:

Screenshot from 2022-11-29 14-30-54

Reason seems to be the virtualized scroll view which renders items on demand when user scrolls the view. This line in particular https://github.com/grafana/grafana/blob/a2f1d2e102b37106bc4b91e0b32be1c41de1373f/packages/jaeger-ui-components/src/TraceTimelineViewer/ListView/index.tsx#L314 returns different value in Chrome vs Firefox.

In Chrome when new items are added to the list, this does not alter the scroll position. In firefox though this changes the scroll position in the view which then triggers another loop of adding new items which again changes the scroll position creating a loop that then React detects and throws.

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

This PR changes the positioning of the Trace View search bar from sticky to absolute.

Why?

Because it was messing with the scroll list in firefox and causing all kinds of havoc like:

Fixes #59490 
Fixes #57985
Fixes #57273
Fixes https://github.com/grafana/support-escalations/issues/4454

With this change the Find bar is no longer stickied to the top of the page when scrolling but we're planning on removing it soon anyway and replacing with a Span Filters section.

### CODE REVIEW

**Review by joey-grafana — COMMENTED** [review]
This does seem to fix the issue! 💯 

One thing though it would be great to position the search within the trace view section. Right now it's floating above it, and if you expand the node graph then it is effectively inside the node graph!

Screenshot 2023-01-13 at 13 59 27

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 

Note: It does make it more difficult to navigate the traces found, however we plan to change the way search works next. Given the number of issues this fixes I think it's important to fix this now.

**Comment by ishworg** [comment]
Excellent. Look forward to it the cut release 👍🏼

**Comment by ishworg** [comment]
I can no longer reproducible on Firefox tested with tag `9.4.0-beta1` (dockerhub). thanks folks

**Pull request merged**
