### PR TITLE
AddPanelWidget: Add padding to prevent top being cut off

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:

This adds a wrapping element with padding-top to the AddPanelWidget wrapper (due to padding removed here: https://github.com/grafana/grafana/pull/34602) so the add new panel chrome isn't cut off.

| Before | After |
| --- | --- |
| before | after |

**Which issue(s) this PR fixes**:

Related issue #33187

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Wont this make the paddings un-even? Can't this be added to the AddPanelWidget instead? I tested adding a 4px top margin the the wrapper element in AddPanelWiget and seems to do the trick

**Comment by jackw** [comment]
Yeah it does make padding slightly un-even. If I add the margin-top to the AddPanelWidget wrapper element it causes weirdness with the dashboard grid positioning. 🤔 

Screenshot 2021-05-27 at 12 44 35

I'll have another think on this.

**Review by torkelo — APPROVED** [review]

**Review by dprokop — COMMENTED** [review]
This works, but in a scenario with multi-column dashboard when you add a new panel it's slightly uneven with the panel to the right:

image

**Comment by dprokop** [comment]
Guess the issue is with the pulsating outline being cut. What about making the "new" panel's border slighlty pulsate to blue rather than adding this outline? Then we wouldn't have to do anything about the paddings?

**Pull request merged**
