### PR TITLE
Prometheus: Min step defaults to seconds when no unit is set

### LINKED ISSUE #30464: Prometheus: Min step value requires unit if used in alert but not on querying.
**What happened**
- I want to create alert based on number on my critical docker swarm service containers.
- After clicking `Test rule` on Alert tab, error appeared. 
```json
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "4.520ms",
  "error": "tsdb.HandleRequest() error time: missing unit in duration \"100\"",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1611187489137,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "count by (container_label_com_docker_swarm_service_name) (container_tasks_state{clustername=\"kr-develop\", container_label_com_docker_swarm_service_name=~\".*service-api.*\", state=\"running\"})",
              "format": "time_series",
              "instant": false,
              "interval": "100",
              "legendFormat": "{{ container_label_com_docker_swarm_service_name }}",
              "refId": "A"
            },
            "datasource": {
              "id": 4,
              "name": "Prometheus"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1611187789137
      }
    }
  ]
}
```

**What you expected to happen**:
- Alert should be firing (Not firing at the moment)
- Test Rule should be passed

**How to reproduce it (as minimally and precisely as possible)**:
- query: `count by (container_label_com_docker_swarm_service_name) (container_tasks_state{clustername="kr-develop", container_label_com_docker_swarm_service_name=~".*service-api.*", state="running"})`
- Alert configuration
image

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.6 (as docker)
- Data source type & version: Prometheus 2.23.0 (as docker)
- OS Grafana is installed on: CentOS Linux release 7.4.1708
- User OS & Browser: macOS Catalina & Chrome 87.0.4280.141
- Grafana plugins: (not related to the issue) alexanderzobnin-zabbix-app,grafana-clock-panel,grafana-simple-json-datasource
- Others:

### PR DESCRIPTION
**Pull request by nutmos**
**What this PR does / why we need it**:
I have fixed the scenario that alert test rule cannot work when Prometheus min step is not set with unit.

**Which issue(s) this PR fixes**:
#30464
Add step to check whether unit is set or not. If unit not set, it will set s before perform query.

Fixes #30464

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Hi @nutmos thanks for fixing this for us. This looks good to me and works as expected. Would you mind adding a test for it?

**Comment by zoltanbedi** [comment]
@aocenas can you please also take a look at it?

**Comment by nutmos** [comment]
I'll add and commit a change soon.

**Comment by nutmos** [comment]
Testcases added as requested. Please review.

**Review by zoltanbedi — APPROVED** [review]
Thank you again @nutmos, lgtm.

**Review by aocenas — APPROVED** [review]
Looks good, thanks for the contribution

**Pull request merged**
