### PR TITLE
CircleCI: Update grabpl to 0.4.5 in order to include manifest with GEL

### LINKED ISSUE #24538: Sign external plugins (GEL) as part of CI
**What happened**:
Sign external bundled plugins (GEL) as part of CI pipelines. cc: @kylebrandt 

The CI build for gel should run the signing tool... likely another target here:
https://github.com/grafana/gel-app/blob/master/Magefile.go#L79

perhaps the `zip` task should also be moved to grabpl?   Should be:
* build
* create manifest
* zip (includes manifest)

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Update the build pipeline tool in order to include manifest with bundled GEL plugin. Also GEL gets updated, due to an incompatibility the older version's plugin.json file.

**Which issue(s) this PR fixes**:

Fixes #24538.

### CODE REVIEW

**Review by bergquist — APPROVED** [review]
Without looking into the grabpl change :)

**Comment by aknuds1** [comment]
I need to make a little fix in the CircleCI config, I realize.

**Comment by papagian** [comment]
Friendly, reminder: it seems that 0.4.5 tag and release are missing from build-pipeline.

**Comment by aknuds1** [comment]
@papagian Yes, I'm testing via this PR first :)

**Comment by aknuds1** [comment]
The CI build is currently breaking due to an incompatibility in GEL's plugin.json - I've made a [PR](https://github.com/grafana/gel-app/pull/74) for it.

**Pull request merged**
