### PR TITLE
Templating: Custom variable edit UI, change options input into textarea 

### LINKED ISSUE #28312: Templating: Custom variable input box switch to area input
The custom varuable now supports key value pairs after this PR https://github.com/grafana/grafana/pull/27829 

Would be nice to expand the input to be a text area so it's easier to edit many entries. 

Here is the editor for custom variables:
https://github.com/grafana/grafana/blob/master/public/app/features/variables/custom/CustomVariableEditor.tsx#L47

### PR DESCRIPTION
**Pull request by darrylsepeda**
**What this PR does / why we need it**:
https://github.com/grafana/grafana/issues/28312, expand the input to be textarea so it's easier to edit many entries.

**Which issue(s) this PR fixes**:

Fixes #28312 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Should use TextArea from @grafana/ui and need to fix typescript errors

**Review by mckn — CHANGES_REQUESTED** [review]
Agree with what @torkelo said in previous comment.

**Review by hugohaggmark — COMMENTED** [review]
Any updates on this @darrylsepeda?

**Comment by darrylsepeda** [comment]
ohh, I was looking for any reply on my PR, didn't realised you guys talk in here. Will do this ASAP. thanks

**Comment by darrylsepeda** [comment]
Will update this soon, sorry I was waiting on the `issue`, didn't realise you guys are discussing here.

**Comment by darrylsepeda** [comment]
I'm successfully run grafana on my local, but I couldn't find this field example as shown in:
https://user-images.githubusercontent.com/5708022/94491237-b0f05b00-019c-11eb-83ef-e96221bdccec.png

I tried to add elastic search data source, but still couldn't find the field.
Can you tell me where can I find this field?
I've imported TextArea from @grafana/ui, but can't validate if the result is already expected.
Please help to re-check. Thank you

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
No worries @darrylsepeda you need to add a Custom Variable (change the type) like this:
image

I think it still needs some work, WDYT?

**Comment by darrylsepeda** [comment]
Thanks @hugohaggmark, but how to see that kind of form? Is it in the dashboard editing page or where?

**Comment by hugohaggmark** [comment]
Aha sorry @darrylsepeda, dashboard settings => variables => add new variable => change type to custom
image

image

**Comment by darrylsepeda** [comment]
Got it! Thanks @hugohaggmark.
I think I will add cols and rows properties to this TextArea to make it looks steady and change the field label and description, do you have any other suggestions?

**Comment by hugohaggmark** [comment]
> Got it! Thanks @hugohaggmark.
> I think I will add cols and rows properties to this TextArea to make it looks steady and change the field label and description, do you have any other suggestions?
> 
> It will be like this:
> image

I think the part in the description that is the same as the text area placeholder is redundant :) Looks good otherwise!

**Comment by darrylsepeda** [comment]
> > Got it! Thanks @hugohaggmark.
> > I think I will add cols and rows properties to this TextArea to make it looks steady and change the field label and description, do you have any other suggestions?
> > It will be like this:
> > image
> 
> I think the part in the description that is the same as the text area placeholder is redundant :) Looks good otherwise!

Noted, I've removed the description. Please help to review again, thank you! :)

**Review by torkelo — APPROVED** [review]
Looks good now! Thanks for contributing!

**Pull request merged**
