### PR TITLE
Explore: Save log results sort order

### LINKED ISSUE #32013: Save the choice of "Flip results order" in Loki
**What would you like to be added**:
A way to save the choice of "Flip results order" would be great. Maybe it could be added with the other check boxes, which are saved :
image
**Why is this needed**:
Currently we have to click "Flip results order" on every page reload / new query. Saving this choice would be useful because in our team we often need the results order to be flipped rather than in the default order.

### LINKED ISSUE #33058: Add an option to display logs flipped by default
**What would you like to be added**:

I would like to have an option to display logs flipped by default in Loki.

**Why is this needed**:
Most of the developers click this button **each time** they use Loki. I think it's possible to add a dashboard option to set the logs flipped by default and let developer (user) decide how they would like to see logs.

All advantages of flipped (native ordered) logs are here https://github.com/grafana/grafana/issues/16555

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
Other settings in this area are saved to local storage and are kept regardless of navigating to other pages or refreshing. Add the sort order to this as well. 

One interesting thing is there's nothing visibly in the UI to show if the sort order is ascending or descending. I'm guessing it may be because the sort was never saved, so it would have to be an explicit action to change it to not be the default. Did we want to add something to the UI to indicate the sort order along with this change? There was conversation about this in the issue linked to this PR as well. @nadinevehling 

**Which issue(s) this PR fixes**:
Fixes #32013
Fixes #33058

### CODE REVIEW

**Review by ifrost — APPROVED** [review]
LGTM 👍 It'd be good if it's possible to add a quick test for it.

**Comment by ifrost** [comment]
Looping in @grafana/observability-logs-and-traces, I hope you're okay with the changes :)

**Comment by ivanahuckova** [comment]
I would wait with merging and tackle `wording should be more specific`, because in this state, user doesn't know if the logs are ordered `newest -> oldest` or `oldest->newest`. Also I would be careful with wording to make it clear that we are not flipping the order in request (forward search) and only results. Maybe we could loop in @grafana/docs-squad to help with wording.

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
I would wait with merging and tackle `wording should be more specific`, because in this state, user doesn't know right away if the logs are ordered `newest -> oldest` or `oldest->newest`. Also I would be careful with wording to make it clear that we are not flipping the order in request (forward search) and only results. Maybe we could loop in @grafana/docs-squad to help with wording. 

Edit: Here also @jessover9000 mentions that if we want to save state, it would make sense to change button to toggle https://github.com/grafana/grafana/issues/32013

**Comment by gelicia** [comment]
@ivanahuckova @jessover9000 What do you think about using a `RadioButtonGroup` here? Is this what you had in mind? 

Screen Shot 2022-02-17 at 6 39 18 AM

**Comment by ivanahuckova** [comment]
I like it! 1 nit pick `Display Results` -> `Display results` and ` `Oldest First` ->  `Oldest first`, ... . Otherwise I think that is a good solution!

**Comment by ivanahuckova** [comment]
Btw I think that this would also close this issue: https://github.com/grafana/grafana/issues/33058. Also, when/if you implement this radio button, would you update labels in logs panel as well so we have uniform naming: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/logs/module.tsx#L77-L78 🙂

**Comment by jessover9000** [comment]
Looks great! Thanks for pointing out the wording consistency, Ivana! I prefer "Oldest/newest first" because it's less ambiguous than decending/ascending :)

**Review by ivanahuckova — APPROVED** [review]
This looks great. Awesome job. 🚀 LGMT!

**Review by ifrost — APPROVED** [review]
Great stuff! 👍 I like how a small dev task included also some nice UX improvements!

**Comment by nadinevehling** [comment]
Great work to indicate the sort order more clearly! Thanks @jessover9000 for stepping in :)

**Pull request merged**
