### PR TITLE
[v8.4.x] Chore: Update Go version (#47914)

### PR DESCRIPTION
**Pull request by sakjur**
* Remove makefile (it's not used anymore)

* Directly download and install nodejs package

The Packages file for deb.nodesource.com/node_16.x doesn't list older
versions, so only the most recent version of nodejs is available. We
don't want to require every update to the build container to have to
update nodejs if a never version is available, so I manually download
the deb and install it with dpkg.

* Update Go version

* Update lib.star

* Generate new .drone.yml

(cherry picked from commit 24038d99852a647bdae623d731de4033ba9d9916)

Backport of #47914

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM, however quite a few versions difference of grabpl. Would ask @grafana/grafana-release-eng to confirm we're not missing anything

**Comment by sakjur** [comment]
@marefr grabpl sometimes gets a new patch release for single lines, so this jump isn't quite as big as the versions would imply, I'll take a look at https://github.com/grafana/build-pipeline/compare/v2.9.32..v2.9.41 to see whether anything seems significant for us

**Comment by dsotirakis** [comment]
I am checking as well if there are any chances on `.drone.yml` we missed and they are necessary to be included. 👀

**Comment by dsotirakis** [comment]
@marefr @sakjur I cherry-picked all the changes I think they should be in `v8.4.x` for the new version to work.
Apart from [this commit](https://github.com/grafana/grafana/pull/47923/commits/414f5fb56149e05a892688b2d2d3591b9e86fe88) I don't think that anything else would break the build really. Let's see though!

**Comment by dsotirakis** [comment]
> @marefr @sakjur I cherry-picked all the changes I think they should be in v8.4.x for the new version to work.
Apart from [this commit](https://github.com/grafana/grafana/pull/47923/commits/414f5fb56149e05a892688b2d2d3591b9e86fe88) I don't think that anything else would break the build really. Let's see though!

Otherwise, we can just keep the current `grabpl` version and update CI after `8.4.7` release.

**Review by dsotirakis — APPROVED** [review]
LGTM - can be merged after rebased https://github.com/grafana/grafana/pull/47923

**Pull request merged**
