### PR TITLE
AzureMonitor: Add support for Microsoft.AppConfiguration/configurationStores namespace

### LINKED ISSUE #28733: Support for the Microsoft.AppConfiguration/configurationStores namespace
**What would you like to be added**: Support for the App Configuration namespace, Microsoft.AppConfiguration/configurationStores

**Why is this needed**:
The absence of app configuration metrics prevents Grafana being a complete monitoring platform for our Azure environment

### PR DESCRIPTION
**Pull request by deesejohn**
**What this PR does / why we need it**:

* Added Azure Monitor support for Microsoft.AppConfiguration/configurationStores namespace

**Which issue(s) this PR fixes**:

Fixes #28733

**Special notes for your reviewer**:

@marefr, I added the line mentioned by @Ginginho then tested it in my subscription, and everything appeared to work just fine (see screenshot). Let me know if you have any concerns.

image

### CODE REVIEW

**Comment by joshhunt** [comment]
@deesejohn Just trying to test this myself - forgive me because I'm not totally familiar with Azure's names for everything, but what Azure service does this expose? Can I query this within Azure Monitor Metrics in the Azure Portal? AppConfiguration or configurationStores doesn't seem to come up with anything

also @bhozar @Ginginho if you know :)

**Comment by Ginginho** [comment]
Hi Josh,

This exposes metrics for Azure App Configuration (https://azure.microsoft.com/en-us/services/app-configuration/), specifically:


  *   HttpIncomingRequestCount
  *   HttpIncomingRequestDuration
  *   ThrottledHttpRequestCount

As documented here: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported.

Best regards,
Shane

Shane Sullivan
Infrastructure Engineer
***@***.***D72F8F.52460BB0]<https://www.kallidus.com/>

www.kallidus.com<http://www.kallidus.com/>
Registered Office: Kallidus Limited, 5 Fleet Place, London, EC4M 7RD
Registered in England Number: 3984404 VAT Registration Number: 945 7763 74

**Comment by bhozar** [comment]
@joshhunt You can view the metrics for **Azure App Configuration** service in the Azure Portal:

image

**Review by joshhunt — APPROVED** [review]
Tested and looks good to me!

**Pull request merged**
