### PR TITLE
StateTimeline: Fix tooltip not showing when transformation applied

### LINKED ISSUE #40042: State timeline: tooltip is not visible
**What happened**:

v8.2.0-beta2 (a2306d2765)

image

**What you expected to happen**:

v8.0.2 (5c5d45e19f)

image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.0-beta2 (a2306d2765)
- Data source type & version: MSSQL
- OS Grafana is installed on: Window10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by zoltanbedi**
**What this PR does / why we need it**:

This is a fix for a regression introduced by me in #39438. I assumed that the `data` is always a return value of multiple queries but this is not the case when there is one query with transformation that adds another field. The guard I added only compares the length of the `alignedData` with the length of the data if aligned data doesn't have a refId which means that it was created by multiple queries.

**Which issue(s) this PR fixes**:

Fixes #40042

### CODE REVIEW

**Comment by dprokop** [comment]
> if aligned data doesn't have a refId which means that it was created by multiple queries.

@zoltanbedi can you point me to the code that's responsible for that?

**Review by dprokop — APPROVED** [review]
Ok, I think i get it now. This was confusing:
> aligned data doesn't have a refId which means that it was created by multiple queries.

Lack of refId is a result of a transformation, not multiple queries, right?

**Comment by zoltanbedi** [comment]
Yeah, refId was not that good instead I changed it to check there is a transformation in place. @dprokop

**Review by dprokop — APPROVED** [review]

**Comment by axelavargas** [comment]
Hola @zoltanbedi, another one that needs some adjusting on the title of the PR 😄 


> 
> Ensure all titles are in imperative form with a meaningful prefix, e.g.:

> Good: Dialog: Fix dialog box in left-hand menu
> 
> Bad: Change: Fixed dialog box in left-hand menu
>
> 
> Good: Dialog: Update button in confirmation dialog
> 
> Bad: Change: Confirmation dialog has a new button

We are preparing for the next release this Thursday (October 21) 🚀

**Pull request merged**
