### PR TITLE
Update auth-proxy.md

### PR DESCRIPTION
**Pull request by J-F-Far**
Fix a minor grammar mistake: 'handling' to 'handle'.

**What this PR does / why we need it**:
Fixes minor grammar mistake in auth-proxy.md
**Which issue(s) this PR fixes**:
As per the Documentation contributing guide, Issue was raised as this is such a simple fix.

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Thanks!

**Comment by aknuds1** [comment]
@torkelo Backport PR Creator tried to backport this branch. Is it because I added it to milestone 7.4? Should we stop assigning PRs that shouldn't be backported to a milestone?

**Comment by torkelo** [comment]
Not sure what you mean? I see no backport PR for this

**Comment by torkelo** [comment]
The backport action is only triggered by PR merge and label added , does not care about milestones

**Comment by aknuds1** [comment]
@torkelo I got this [backport error](https://github.com/grafana/grafana/actions/runs/311997989) for the PR.

**Comment by torkelo** [comment]
Yes, the backport will fail if merged on a fork PR as it does not have access to the token repo secret. Not sure if there is a solution for that

**Comment by aknuds1** [comment]
@torkelo Why did it try to backport though? Isn't it only with a certain label?

**Comment by torkelo** [comment]
It did not try to backport. It runs every time we merge a PR or a PR is labeled. Then it checks if the PR is merged & has the label matching `backport <branch>`

**Comment by aknuds1** [comment]
@torkelo Ah, so that's what went wrong. Sounds as if it needs to be fixed then? Since the error will happen for every merged PR from a fork.

**Comment by torkelo** [comment]
not sure how, as it's GitHub who is running the action and seeing the token is not supplied. Could make the token optional and check if it was not supplied, then add a comment to PR that i could not be backported (if it has the correct label)

**Pull request merged**
