### PR TITLE
TimeSeries: add UI slider input for "Bar width factor"

### PR DESCRIPTION
**Pull request by bastidest**
**What is this feature?**

This PR adds a slider input in the TimeSeries configuration menu to allow changing the width of the bar relative to minimum space between data points. The feature existed before, but the functionality was not exposed to the UI yet.

image

Screenshot from 2023-10-29 21-35-32

**Why do we need this feature?**

This feature allows to display seamless bar charts, which can be useful for overlaying momentary data with averaged data.

For example, if you want to inspect the energy consumption of a device which switches off and on, a gapless bars are much more helpful than bars with gaps, because they span the entire time period they reference:

image

This also allows us to produce gnuplot "histeps"-like plots: http://www.bersch.net/gnuplot-doc/histeps.html

**Who is this feature for?**

Anyone?

**Which issue(s) does this PR fix?**:

* Relates to #37192

**Special notes for your reviewer:**
I tried updating the docs, but I didn't figure out how to insert pictures.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by bastidest** [comment]
Some additional handling might be necessary to increase the maximum bar width for the case `barWidthFactor = 1.0`. 200px per bar might be too small if the graph spans the entire screen.

https://github.com/grafana/grafana/blob/86833237602118498fce75abb167de1e6a5a8b4b/packages/grafana-ui/src/components/uPlot/config/UPlotSeriesBuilder.ts#L244

**Comment by leeoniya** [comment]
thanks for the PR :)

the described use case and appearance feel pretty much the same as stepped line with a fill, correct?

**Comment by bastidest** [comment]
Almost, the steps are missing the last interval when compared to the bars.

image

**Comment by leeoniya** [comment]
it might be better to provide an option for bringing back this: https://github.com/grafana/grafana/pull/65657, though there is a valid case for having control over bar width as well. for your use case the bars rendering and width control looks like a work-around for not having a UI option for `extend: true` in the stepped renderer.

**Comment by bastidest** [comment]
The stepped renderer with the `extend: true` attribute sounds better aligned with my use-case. Then the bar-width does not have to be (ab)-used to re-implement the steps and can remain purely cosmetic.

**Comment by bastidest** [comment]
I tried your suggestion with `extend: true` and it does not achieve the desired effect. 

* Whereas bars only show up when data is present in the specific time-frame, the bridge the gap, no matter how large it is, between adjacent data points.
* As `extend: true` suggests, the last data point is extended until the very end, not for a fixed width

image

**Comment by leeoniya** [comment]
would you mind attaching a debug dashboard for this panel so i can also test with your raw data?

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

**Comment by bastidest** [comment]
Sure, here you go:

| Key | Value |
|--|--|
| Panel | timeseries @ 10.3.0-pre (89611217b3) |
| Grafana | 10.3.0-pre (89611217b3) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "bars",
            "lineInterpolation": "linear",
            "barAlignment": 1,
            "barWidthFactor": 1,
            "lineWidth": 0,
            "fillOpacity": 50,
            "gradientMode": "none",
            "spanNulls": false,
            "insertNulls": false,
            "showPoints": "always",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "axisBorderShow": false,
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": false,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "timestamp",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "metric",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "2023-10-29 06:30:00",
                    "2023-10-29 07:00:00",
                    "2023-10-29 07:30:00",
                    "2023-10-29 08:00:00",
                    "2023-10-29 09:00:00",
                    "2023-10-29 09:30:00",
                    "2023-10-29 10:00:00"
                  ],
                  [
                    50,
                    13,
                    27,
                    31,
                    49,
                    28,
                    13
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "transformations": [
        {
          "id": "convertFieldType",
          "options": {
            "conversions": [
              {
                "destinationType": "time",
                "targetField": "timestamp"
              }
            ],
            "fields": {}
          }
        }
      ],
      "type": "timeseries"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.3.0-pre (89611217b3)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>convertFieldType</td>\n  </tr>\n    <tr><th>Data</th><td> 1 frames, 2 fields, 7 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.3.0-pre (89611217b3) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"type\": \"grafana-testdata-datasource\",\n    \"uid\": \"ce2227ff-76e8-4372-82d1-31d1b2292474\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"bars\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 1,\n        \"barWidthFactor\": 1,\n        \"lineWidth\": 0,\n        \"fillOpacity\": 50,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"insertNulls\": false,\n        \"showPoints\": \"always\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"axisBorderShow\": false,\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 80\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  },\n  \"gridPos\": {\n    \"h\": 6,\n    \"w\": 3,\n    \"x\": 3,\n    \"y\": 0\n  },\n  \"id\": 2,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": false,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"targets\": [\n    {\n      \"csvContent\": \"timestamp,metric\\n2023-10-29 06:30:00,50\\n2023-10-29 07:00:00,13\\n2023-10-29 07:30:00,27\\n2023-10-29 08:00:00,31\\n2023-10-29 09:00:00,49\\n2023-10-29 09:30:00,28\\n2023-10-29 10:00:00,13\\n\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"ce2227ff-76e8-4372-82d1-31d1b2292474\"\n      },\n      \"refId\": \"A\",\n      \"scenarioId\": \"csv_content\"\n    }\n  ],\n  \"title\": \"Bar width factor = 1.0\",\n  \"transformations\": [\n    {\n      \"id\": \"convertFieldType\",\n      \"options\": {\n        \"conversions\": [\n          {\n            \"destinationType\": \"time\",\n            \"targetField\": \"timestamp\"\n          }\n        ],\n        \"fields\": {}\n      }\n    }\n  ],\n  \"type\": \"timeseries\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Bar width factor = 1.0 // 2023-10-30 18:54:44",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2023-10-29T03:45:00.000Z",
    "to": "2023-10-29T10:45:00.000Z"
  }
}
```
</details>

**Comment by leeoniya** [comment]
hmm, yeah. we might also need to init the stepped pathBuilders with `alignGaps: 1` or `alignGaps: -1` [1]. maybe something also with setting the disconnect threshold in your case since we need the `null` values in the data to show gaps and disconnect/threshold does that null insertion.

[1] if you're bored and want to read some details: https://github.com/leeoniya/uPlot/pull/694

**Comment by bastidest** [comment]
Just so that I understand correctly: For the described use-case you would still favor stepped line interpolation instead of bars? To my understanding the bars already calculate the minimum width between two ajacent data-points. Therefore missing values do not have to be filled with `null` values or some disconnect threshold has to be determined.

In my eyes bars with `barWidthFactor: 1.0` and `barMaxWidth: inf` would be the straightforward solution. Maybe it could be exposed to the UI as a single option (e.g. `gapless bars: true`).

**Comment by leeoniya** [comment]
> Just so that I understand correctly: For the described use-case you would still favor stepped line interpolation instead of bars?

technically, yes. it's what stepped is _meant for_.

but practically, making stepped work as you want requires quite a few more changes, probably to the _default_ stepped behavior, which is more risky and will need extra scrutiny. i think we've had prior requests to expose control over the timeseries bar width so i dont see this PR as only catering to your specific use case.

> In my eyes bars with `barWidthFactor: 1.0` and `barMaxWidth: inf` would be the straightforward solution. Maybe it could be exposed to the UI as a single option (e.g. `gapless bars: true`).

i don't see much of a reason for this restriction vs a slider since it's the same number of opts.

**Comment by leeoniya** [comment]
hey @bastidest !

motivated by the use-case in the first comment in https://github.com/grafana/grafana/issues/86868, i think we should go ahead with this. while that specific case can be solved by changing the default factor from 0.6 to 0.5, i think it looks better with 0.3:

image

i'd maybe like to do a follow-up to change this "bar width" and drop "factor", to be consistent with BarChart, but this can be done later.

**Review by leeoniya — APPROVED** [review]

**Pull request merged**
