### PR TITLE
Remove Angular dependencies from KeybindingSrv

### PR DESCRIPTION
**Pull request by dprokop**
Based on https://github.com/grafana/grafana/pull/31463

Closes https://github.com/grafana/grafana/issues/31553

Needs manual testing 

Refactors `CoreEvents.showModal*` events to EventBus

### CODE REVIEW

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
I've not looked at the code but I did some manual testing on the branch and I found:

- Import dashboard doesn't work, it imports the dashboard correctly but then it shows errors
- Trying to delete the imported dashboard doesn't work, it deletes the dashboard but never closes the confirm dialog
bug
- Using the `x` keybinding to navigate to Explore doesn't work, it opens Explore but the url is wrong as it doesn't change the datasource
- Using the mouse to navigate to Explore doesn't work, nothing happens
bug

**Comment by torkelo** [comment]
Explore is has yet to be updated to use router/history so that is expected

**Comment by hugohaggmark** [comment]
> Explore is has yet to be updated to use router/history so that is expected

Aha, so this is part of the Router migration. Now I see the merge branch, my bad.

**Review by hugohaggmark — APPROVED** [review]
Good to go!

**Review by torkelo — APPROVED** [review]
Looks great! :100:  

But think we need to have some restraint in routing-ng not to refactor and change things when not strictly needed to limit changes/merge conflicts/introduce bugs/etc. I know it's hard as there is so much now that can be cleaned up and simplifed or removed. But Let's just keep a record of potential cleanup / refactorings and do them after we merge routing-ng

**Comment by dprokop** [comment]
@torkelo agree, I don't aim that much to merge this to routing branch, just kept the base to it to make sure we see only relevant changes

**Comment by torkelo** [comment]
@dprokop you do not indent to merge it? not sure I understand that, won't we need to touch some of this code in routing-ng branch before merge?

**Comment by dprokop** [comment]
I do intend to merge it, just saying that if we want to limit the changes in routing branch to the routing only ones, then we can wait with merging this one.

**Pull request merged**
