### PR TITLE
Explore: Show a drawer with tabs for the library and query history

### LINKED ISSUE #86120: Explore: Show a drawer with tabs for the library and query history
Part of https://github.com/grafana/grafana/issues/83095

Scope:
* Change query history container to be tabbed, containing tabs for query history and query library
* Add a button in the toolbar to toggle the drawer
  * Each pane shows that button for now. This will be revisited when we work on Explore Toolbar improvements.
  * Button remebers last selection (per session / not persisted). Defaulting to "query library"
* Query History button from an Explore's pane triggers the same drawer
* When `queryLibrary` toggle is enabled: 
  * both tabs are shown
  * Query Library tab is just empty. Content will be loaded in https://github.com/grafana/grafana/issues/86122
* When `queryLibrary` toggle is disabled:
  *  only query history tab is shown
  * there's no button in the toolbar
* Implement user tracking as defined in the parent task

### PR DESCRIPTION
**Pull request by ifrost**
Fixes #86120 

Requires enabling a feature toggle:

```
[feature_toggles]
queryLibrary = true
```

* When the toggle is disabled, there are no changes
  * No extra button in the toolbar
  * Query History button loads preferred tab (starred or queries)
  * No extra tab for query library
* When the toggle is enabled:
  * Extra button to select Query Library and a dropdown shortcut to access query history (persisted during session)
  * Additional query library tab is opened and it's selected by default
  * Query library tab is empty. Loading items to be implemented in https://github.com/grafana/grafana/issues/86122
  * Query History button below queries triggers whatever is selected in the top dropdown. (⚠️ )
* Also regardless to flag being enabled:
  * Tracking contains which tab was loaded when the drawer is opened

> [!NOTE]  
> _Query History button below queries triggers whatever is selected in the top dropdown. (⚠️ )_
> This might be confusing, some options:
>  * Change Query History button to always set Query History and use preferred settings (adds some complexity to the code)
>  * Change label of the Query History button below queries so it changes to "Query Library" when Query Library was selected in the top dropdown
>  * Do nothing, it's behind a feature toggle and gives more visibliity to the new tab

### CODE REVIEW

**Review by gelicia — COMMENTED** [review]
Code changes look great, I love how you simplified the state logic and made that all more clean 🧹 

A couple things, I'm wondering about the behavior of the button on the top. Should clicking it when the drawer is open close it? What do we think a good icon might be for the kebab menu in split view? 

Screenshot 2024-04-16 at 5 19 14 PM


I'm going to get an ephemeral going so Diego can play around with it.

**Comment by ifrost** [comment]
Just had a chat with Diego and here's what we have discussed:

> A couple things, I'm wondering about the behavior of the button on the top. Should clicking it when the drawer is open close it? 

- [ ] Yes! That's a very good point. It should work as a toggle

> What do we think a good icon might be for the kebab menu in split view?

- [ ] The icon should be the "book" icon and it should be used in the split view and also in the drawer (need to update the drawer). The icon may change in the future but that will be easy to address, we go with "book" for now.

> Query History button below queries triggers whatever is selected in the top dropdown. (⚠️ )
> This might be confusing, some options: (...)

- [ ] To avoid confusion around having 2 buttons to open the drawer, let's remove Query History button (when toggle is on).

Other things:
- [ ] Drawer should span 3/4 of the screen (let's do it only when it's behind the toggle)
- [ ] The top button should have an icon as well in non-split mode.

Other notes:
- Saving "Query Library" / "Query History" selection per session is fine. We don't need to persist it in browser storage.
- Having a dropdown in the split view (and no quick action button) is fine. It means you always need two clicks in split view but gives more clarity.

**Comment by gelicia** [comment]
Couple scenarios

1.) Explore, go to split mode
2.) With minimized query library/ history button, you can bring in the drawer but not dismiss the drawer (the same for both kebab and non kebab)

1.) Explore, click query library
2.) Select query history from dropdown (would we want this to toggle immediately?)
3.) Selecting query history closes panel, not change tab

**Comment by ifrost** [comment]
> Couple scenarios
> 
> 1.) Explore, go to split mode 2.) With minimized query library/ history button, you can bring in the drawer but not dismiss the drawer (the same for both kebab and non kebab)

This was intentional. We want a compact mode without both (the button and the dropdown) so we decided to keep the dropdown as it gives more clarity what's being selected. However since the other issue is happening...

> 1.) Explore, click query library 2.) Select query history from dropdown (would we want this to toggle immediately?) 3.) Selecting query history closes panel, not change tab

...and this is confusing maybe we can change interactions a bit:

(1) The TabbedContainer doesn't allow to have controlled state (just defaults) so it's hard to change the selected tab in the toolbar. We can refactor TabbedContainer to allow controlling the state and pulling it up but that can be done in a separate PR (it's a grafana/ui component). 
(2) In theory we could close and re-open the drawer but it will look odd with drawer opening again. Also the implementation-wise we would need to do it asynchronously (close, and later open) which may require adding more noisy state handling.
(3) Another, alternative solution is to turn the dropdown into a close button so the user needs to close it first. This way we could also have ability to close it in split view. What do you think @gelicia / @diegoadams ?

Here's how it would look like (19bdb9ce13670c5f772d9a62ac6af16922097a94):

https://github.com/grafana/grafana/assets/745532/850882a1-7a41-4e7a-b9c4-7bb5deadbcd5

We would need a different icon though. Simple "X" will be confusing in split view..

**Comment by harisrozajac** [comment]
> Here's how it would look like ([19bdb9c](https://github.com/grafana/grafana/commit/19bdb9ce13670c5f772d9a62ac6af16922097a94)):

I really like this approach! This PR looks good to me, but probably wait for input from Kristina and Diego.

**Comment by diegoadams** [comment]
@ifrost , I like your option 3 (dropdown into a close button). It flows well in the video. And makes the selection clear. 

On another note, there is something strange about the Query Libray icon moving into the kebab in split or when the screen size is reduced. it's almost hidden. Is there anyway we could get it to stay on the view next to the add button.  

Screenshot 2024-04-23 at 22 32 29
b-05e0080a07ee">

**Comment by ifrost** [comment]
Here's an updated version:

https://github.com/grafana/grafana/assets/745532/76cc49ec-9a38-4daf-9c24-b7e62b2b6939

It's actually simpler overall -> basically the text "Query library" is hidden in split view. Everything else remains the same.

> Also, I've noticed an issue with the Query Library icon shifting into the kebab menu in split view or when the screen size is reduced.

It should show the button when there's enough space. We're using grafana/ui component for it and it seems it doesn't work as expected all the time. I'll create a follow up issue to have a look at this.

**Review by gelicia — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
