### PR TITLE
[WIP] Github Actions: Add `go mod tidy` github action

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Recently, we got onto an issue about go modules de-syncronisation between `grafana` and `grafana-enterprise`, resulting to failing pipelines on the enterprise side. This was due to an outdated `go.sum` between `v7.5.x` versions of the repos.

Until today, `dependabot` was responsible for tidying the go modules, but after Go 1.16, there are some known issues where `dependabot` cannot perform the command.

About a month ago, we removed `tidy-checks` from lint steps on our pipelines, since it was preventing us from running lints properly and proceeding to next steps.

A (temporary until dependabot is fixed?) solution, is to introduce a new github action to perform `go mod tidy` checks daily, to be sure we don't face de-sync issues between `grafana` and `grafana-enterprise` and branches per se.

**Special notes for your reviewer**:

You can check the first commit in this PR, where I triggered the job manually, and it produced the desired output.

- Github action: https://github.com/grafana/grafana/runs/2129407679
- Commit: https://github.com/grafana/grafana/pull/32052/commits/947d10a0880fe08ce94b004cadd41977c7d8879a

### CODE REVIEW

**Comment by dsotirakis** [comment]
Maybe it would make sense to have it running on every push on `master` and `vx.x.x` branches?

**Comment by joanlopez** [comment]
In general terms, it looks like it could work as a temporary solution. It's much better to proactively be notified about this kind of de-synchronization issues that having to figured it out on our own. That being said, some of my thoughts are:

- I'd trigger it after every new change. It's still far from ideal, but I'd say that the sooner we get alerted, the better.
- It definitely needs to be added to version branches as well. In fact, we suffered that as well.
- For the back ports, it's bit trickier because depending on how we set it up, the "tidy up" commits on the `master` branch may be not compatible with version branches.

Finally, an interesting question: how do you plan to integrate it with the Enterprise repository? AFAICS, the current proposal would keep the Go modules files tidied up only for the OSS repository, right? 🤔 

Thanks!! 🙏🏻

**Comment by dsotirakis** [comment]
I agree with you @joanlopez on the bullets - maybe better to have it running after every push to master.

About enterprise, since it doesn't have its own go modules, I guess we can follow the same pattern we follow when we merge something to `master` or `vx.x.x` branch for example. 

Another thought I have is that maybe we can follow this as a fail-safe method, meaning that we can have it as a cron as it is in this PR (and add it to `vx.x.x` versions also) and then do something on `grabpl` (like what you had done with `tidy-check`), but probably force update `go.sum` like this github action does.
Thoughs @aknuds1?

**Comment by aknuds1** [comment]
@joanlopez @dsotirakis it sounds to me also as if we should trigger `go mod tidy` via a GitHub action after every push to relevant branches (master, release branches). Did we consider yet to add it as a Git commit hook?

**Comment by dsotirakis** [comment]
> @joanlopez @dsotirakis it sounds to me also as if we should trigger `go mod tidy` via a GitHub action after every push to relevant branches (master, release branches). Did we consider yet to add it as a Git commit hook?

Sounds like a valid consideration, but I'd personally go to a more global solution like GitHub actions, since if someone hasn't set up the hooks at all, may break the pipelines again :/ We can try if you have a strong preference on that though.

**Comment by aknuds1** [comment]
> > @joanlopez @dsotirakis it sounds to me also as if we should trigger `go mod tidy` via a GitHub action after every push to relevant branches (master, release branches). Did we consider yet to add it as a Git commit hook?
> 
> Sounds like a valid consideration, but I'd personally go to a more global solution like GitHub actions, since if someone hasn't set up the hooks at all, may break the pipelines again :/ We can try if you have a strong preference on that though.

@dsotirakis yes, the commit hook would be in addition to the GitHub Action. The benefit is that in most cases it would make the GitHub Action unnecessary, and cause less trouble for that reason.

**Comment by dsotirakis** [comment]
@aknuds1 Ah okay, got you. Agree 👍

**Comment by marefr** [comment]
My 2 cents here. Don't really have anything else to add here about the actual changes. Talked with Dimitris earlier and the thing I couldn't understand is why this problem wasn't caught in a release branch before actually tagging and building a release - seems like some CI is missing on Enterprise side in regards to release branches, like when backporting a change to release branch in enterprise?

**Comment by dsotirakis** [comment]
My understanding is that since OSS clones some Enterprise bits, in case the Enterprise bits have some new dependencies that are not already into OSS repo, then running `go mod tidy` after symlinking Enterprise, may lead to new additions/removals. That being said, remember that the Enterprise repo doesn't have go modules - solely depends on OSS repo, so every time something changes on the Enterprise side, the process:

* Checkout same release branch version (or master) on both Enterprise and OSS
* Symlink on enterprise
* Run `go mod tidy` on OSS

should be followed to sync go modules across both repos.

**Comment by dsotirakis** [comment]
Closing as not needed for now.

**Pull request closed without merging**
