### PR TITLE
Edit dashboard UI text

### PR DESCRIPTION
**Pull request by oddlittlebird**
Minor text edits

### CODE REVIEW

**Comment by hugohaggmark** [comment]
@oddlittlebird you have build errors caused by your edits. Not sure what the best process is but I think you need to run the build locally? See: https://github.com/grafana/grafana/pull/32451#pullrequestreview-623890164

**Review by hugohaggmark — COMMENTED** [review]
@oddlittlebird you have build errors caused by your edits. Not sure what the best process is but I think you need to run the build locally? See: https://github.com/grafana/grafana/pull/32451#pullrequestreview-623890164

**Comment by dsotirakis** [comment]
> @oddlittlebird you have build errors caused by your edits. Not sure what the best process is but I think you need to run the build locally? See: [#32451 (review)](https://github.com/grafana/grafana/pull/32451#pullrequestreview-623890164)

Hello @hugohaggmark, they are formatting failures, most likely `Prettier` or `ESLint` are not properly set up in Diana's machine, will try to set them up today :)

**Comment by mckn** [comment]
> > @oddlittlebird you have build errors caused by your edits. Not sure what the best process is but I think you need to run the build locally? See: [#32451 (review)](https://github.com/grafana/grafana/pull/32451#pullrequestreview-623890164)
> 
> Hello @hugohaggmark, they are formatting failures, most likely `Prettier` or `ESLint` are not properly set up in Diana's machine, will try to set them up today :)

Yeah, but I think making changes like this requires them to be setup. Super that you are helping out!

**Review by dsotirakis — APPROVED** [review]
Some tests needed fixing, LGTM!

**Pull request merged**
