### PR TITLE
BarGauge: Fixed an issue where the cell color was lit even though there was no data.

### LINKED ISSUE #39548: LCD Bar Gauge shows as full when no data
Hello everyone,

I would like to know how to disable the "led" inside the "Bar Gauge" graph when it is not active, that is when there is **"No data"** as in this case:

OEE AGOSTINO

**Versione di Grafana in uso: v7.5.7
Versione Bar Gauge: Versione integrata in Grafana 7.5.7 è viene mostrato il seguente messaggio: No plugin help or readme markdown file was found
Database utilizzato: Microsoft SQL Server 2012**

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- unfortunately, `positionValue > NaN` resolves to false
- add an explicit check for if the value is `NaN` to mark the cell as off

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/39548

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉

**Review by hugohaggmark — APPROVED** [review]
I did almost add a comment during my last review, that we might extract this to a testable external function, but then I didn't because it was such a minor change. 

And then you did it anyway, impressive ⭐  🤩  🤯

**Review by torkelo — APPROVED** [review]
Awesome fix! :100:

**Comment by torkelo** [comment]
@ashharrison90 don't forget to add `add to changelog` label and change PR to something that explains the fix from the users point of view (not the technical reasons)

**Comment by torkelo** [comment]
Example `BarGauge: Fixes cell color being lit when there was no data or NaN value`

**Pull request merged**
