### PR TITLE
Elasticsearch: Frontend PPL Support

### PR DESCRIPTION
**Pull request by euniceek**
**What this PR does / why we need it**:

This PR contains all the changes required for basic PPL support from the Elasticsearch plugin on the client-side, minus the UI changes. Basic PPL support entails being able to write PPL queries in the query editor and visualize responses from Elasticsearch instances with the ODFE SQL plugin installed. Expected functionality such as variable interpolation and ad hoc filtering will also work with PPL queries.

This PR merges all the PPL query handling logics from the following PRs:  `Add PPL query builder` #29425, `Add PPL response parser for logs and table format`, `time series format` #29426 #29554, `Add Ad hoc filters support for PPL` #29454, and `Add PPL support to ElasticDatasource` #29427.
The reason for merging all these branches into a separate branch is to include integration tests in Elasticdatasource which requires the implementation of the PPL query builder and query response.

Ultimately, merging this PR, along with the PPL Backend Alerting #29734 and the UI changes will provide full PPL support for the ODFE plugin.

**Which issue(s) this PR fixes**:

Partially resolves issue #28674

**Special notes for your reviewer**:

Please rebase the upstream branch `elasticsearch-ppl-support`

cc: @alolita

### CODE REVIEW

**Comment by oddlittlebird** [comment]
Is there any way to submit this PR without all of the old PR content? I don't know what, if anything, I should edit.

**Comment by ahlaw** [comment]
> Is there any way to submit this PR without all of the old PR content? I don't know what, if anything, I should edit.

Someone with write permissions could rebase this [branch](https://github.com/grafana/grafana/tree/elasticsearch-ppl-support) on to master, that should get rid of the old content

**Comment by oddlittlebird** [comment]
There are 13 conflicts that I don't know how to resolve if I try to rebase it.

**Comment by ahlaw** [comment]
> There are 13 conflicts that I don't know how to resolve if I try to rebase it.

Hmm rebasing the target remote branch [`elasticsearch-ppl-support`](https://github.com/grafana/grafana/tree/elasticsearch-ppl-support) shouldn't have any conflicts when rebasing onto master. I was able to rebase it locally onto master without conflicts, but I don't have write access to the remote branch. I can make another PR for it though.

**Pull request closed without merging**
