### PR TITLE
Grafana-UI: Extend Layout props

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
There are often cases when `Layout` styling needs to be extended beyond `width`, mostly its padding and margin. Adding a `className` to the container div solves this issue. Additionally Layout should also accept all native HTML props.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tskarhed** [comment]
As we have been hesitant to add className (and spreading restProps?) on other components, I'm not so sure about this. Maybe just adding props for marign, padding and border to cover the box model is enough? Would really like to hear @dprokop's take on this

**Comment by Clarity-89** [comment]
I wasn't 100% sure either but I think in this case it's just a wrapper div with predefined flex props. Plus we might need to be able to add stuff like `aria-label` for testing, etc.

**Comment by torkelo** [comment]
> As we have been hesitant to add className (and spreading restProps?) on other component

not sure I agree, think most should have className & restProps so we can set aria-label etc other html attributes on all our react components

**Comment by dprokop** [comment]
@Clarity-89 Thinking behind Layout was to be able to primarily set flex props. I'm not against adding className attribute, but this may have consequences we might not have control over if we change the internal implementation or API. 

Padding&margin can be controlled with Container component:

```
<Container ...>
  <Layout .../ >
</Container>
```

I would skip enabling `className` property (rest HTML props is OK) and probably slightly adjust the Container component implementation to allow various paddings/margins on different axes (now it only allows to set margin/padding on all axes at the same time)

**Comment by dprokop** [comment]
The major drawback of adding className is that it's a pandora box that when opened can allow complete redesign of the grafana-ui component. And with grafana-ui our goal is to deliver consistent UIs

**Comment by Clarity-89** [comment]
> Padding&margin can be controlled with Container component

Missed that one, that solves my issue. I'll remove the `className` prop.

> The major drawback of adding className is that it's a pandora box that when opened can allow complete redesign of the grafana-ui component. And with grafana-ui our goal is to deliver consistent UIs

That is a valid concern, but on the other hand we might end up with come components that have a ton of css-like props, which could be replaced by allowing to use `className`. Probably this should be considered on a case-by-case basis.

**Review by dprokop — APPROVED** [review]

**Pull request merged**
