### PR TITLE
GraphNG: Pass query results revision from panel query runner 

### PR DESCRIPTION
**Pull request by dprokop**
This is built on top of https://github.com/grafana/grafana/pull/33098 and part of it is cherry-picked from https://github.com/grafana/grafana/pull/32906

This basically adds resultsRevision to PanelData that changes whnever a new query is performed. It "simplifies" the way GraphNG detects data and config changes (together with work from #33098). The resultsRevision is especially useful for clear indication that the actual new data was returned from the query. Otherwise we will always get new data frame passed to the visualization making it hard to make a data vs config update decision based on the structureRev only.

The alignment, as opposite to #32906, still happens in GraphNG rather than PQR. I think this is fine, though I think it's much nicer to get aligned data directly from PQR, as then we don't need to do uPlot index -> frame/field index mapping and stuff. And we could get rid of GraphNG context that exposes those APIs for data inspection.

But, I agree with @ryantxu that data alignment in PQR feels like GraphNG specific thing and I'm really on a fence here whether or not we should do that.

I'm happy to hear some more opinions from @torkelo and @leeoniya.

Neverthelss, both approaches make the getDerivedStateFromProps gone as well as make the uPlot not over-initialize.

TODO:
- [ ] Update PQR tests
- [ ] Fix TS issues
- [ ] Test this change against transformations
- [ ] Add GraphNG tests for result/structureRev updates

### CODE REVIEW

**Comment by ryantxu** [comment]
Why is the additional data revision needed?  Is that the same as checking equality on panelData.series?

**Comment by torkelo** [comment]
> nope, there is no referential equality between these two, so we would have to do deep equal on the panelData.series(DataFrame).

Why is this? Due to alignment always creating new series?

**Comment by dprokop** [comment]
> Why is this? Due to alignment always creating new series?

Nope @torkelo, this is about data comming from panel query runner. It's creating a new data frame every time. Or I'm missing sth.

**Comment by leeoniya** [comment]
i was looking at how [BarGaugePanel.tsx](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/bargauge/BarGaugePanel.tsx) is structured and wondering if we cannot do the same thing for TimeSeries/GraphNG/UPlotChart -- move the synchronous `preparePlotFrame()` call into [TimeSeriesPanel.tsx](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx) and out of the vis components. would this not completely simplify or eliminate all the plotcontext/graphngcontext stuff, the uPlot index -> frame/field index mapping, and reduce the need for many async hooks & memoization at each level.

i'm not seeing anything that requires data prep for uPlot based charts to be done deep at the component level instead of in the panel, but i might be under-engineering things :thinking:

**Comment by ryantxu** [comment]
> It's creating a new data frame every time

Right you will get new panel & panel.series array on each `next()` but that seems fine.  But that seems fine, next is only called when there are new results, so I don't get what this is for.

Ooooh -- is this to avoid updates when only the schema changes, but not the data?  Like when you are in the editor changing things?  do we need/want to optimize this path?  or is there a non-edit case where this happens?

**Comment by torkelo** [comment]
> Nope @torkelo, this is about data coming from panel query runner. It's creating a new data frame every time. Or I'm missing sth.

Well of couse, but is it not supposed to do that? PanelQueryRunner will only emit when there is new data, so a new data frame is ok

**Comment by torkelo** [comment]
> move the synchronous preparePlotFrame() call into TimeSeriesPanel.tsx and out of the vis components

Yes, think this could be a good option to get rid of all the mapping of indices. thoughts @ryantxu ?

**Comment by dprokop** [comment]
> oooh -- is this to avoid updates when only the schema changes, but not the data? Like when you are in the editor changing things? do we need/want to optimize this path? or is there a non-edit case where this happens?

There are three cases currently - edit panel, toggle series from legend and change series color from the legend icon. None of them will create intense amount of changes tho.


> TimeSeries/GraphNG/UPlotChart -- move the synchronous preparePlotFrame() call into TimeSeriesPanel.tsx and out of the vis components

this actually is an excellent suggestion, it creates an arch similar to a situation when aligned data comes from PQR. Gonna try this out

**Comment by dprokop** [comment]
> Yes, think this could be a good option to get rid of all the mapping of indices. thoughts @ryantxu ?

Think this might be still needed, I had some troubles with Legend to get it working without reference to original DF (mainly because of display name calculation being wrong for some reason).


But, I'm closing this now in favor of https://github.com/grafana/grafana/pull/33215

**Pull request closed without merging**
