### PR TITLE
DataSourceWithBackend: Add `queryGroupId` to find correlated/related queries

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

We are currently adding query chunking to the Loki datasource. This means a 30day query is split into 30 individual 1day queries. This PR is adding a `correlationId`, which is send via a HTTP header, to still see the relations/correlations of those individual queries.

**Why do we need this feature?**

Queries might potentially influence each other. This ID is good to detect relevant queries.

**Special notes for your reviewer**:

This implementation is quite generic, as query chunking might be something also other datasource can implement in the future.

**How to test this:**

1. Setup a Loki datasource
2. `make devenv sources=loki`
3. Go to Explore
4. Run the following query over the last 7 days: `sum(count_over_time({job="\"grafana/data\""} |= `` [$__interval]))`
5. Observe network requests in e.g. the network tab of devtools
6. See 7 1day queries in the network tab. Each of the HTTP request has the same `X-Correlation-Id` header.

### CODE REVIEW

**Review by gabor — COMMENTED** [review]
great work, i like all of it, except the name "correlation", i think some other name would be better, but will have to think about it more 😄 , and come back to you.

**Comment by marefr** [comment]
I think this is acceptable. So this will always be a client-side feature only? I know there's been historic discussions, with CloudWatrch for example I believe, where they had possibly other needs. Basically the batching was happening on the CloudWatch side and they needed to correlate it based on some ID coming back from CloudWatch request.

Agree that the naming of header can be adjusted, but naming is hard :smile: X-Correlation-Is is often used as trace identifier I believe. Some discussion of X-Request-Id and X-Correlation-Id https://stackoverflow.com/a/56070263

**Comment by svennergr** [comment]
> I think this is acceptable. So this will always be a client-side feature only?

Thanks @marefr. Hard to talk about "always", but the way we are doing query chunking should live in the frontend for now. Hope that answers your question.

> Agree that the naming of header can be adjusted, but naming is hard 😄 X-Correlation-Is is often used as trace identifier I believe. Some discussion of X-Request-Id and X-Correlation-Id https://stackoverflow.com/a/56070263

What do we think about `X-Query-Group-Id` / `queryGroupId`?
@gabor @matyax react with 👍 if `X-Query-Group-Id` / `queryGroupId` is fine for you.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
> warning   **Possible breaking changes**
> 
> _(Open the links below in a new tab to go to the correct steps)_
> 
> **`grafana-data`** has possible breaking changes ([more info](https://github.com/grafana/grafana/actions/runs/4385266562/jobs/7677832074?check_suite_focus=true#step:8:1))
> 
> [Console output](https://github.com/grafana/grafana/actions/runs/4385266562/jobs/7677832074?check_suite_focus=true#step:8:1) [Read our guideline](https://github.com/grafana/grafana/blob/main/contribute/breaking-changes-guide.md)

No breaking change so you can remove the breaking change label after merge

**Review by gabor — APPROVED** [review]
LGTM!

**Pull request merged**
