### PR TITLE
Added Basic Auth to Kafka notifier

### LINKED ISSUE #41176: Kafka REST Proxy authentication
### Discussed in https://github.com/grafana/grafana/discussions/41175

<div type='discussions-op-text'>

<sup>Originally posted by **rruckley** November  2, 2021</sup>
I work for a Telco and security is a big deal. We want to use Grafana alerting into a Kafka topic via the Kafka REST proxy notifier but it doesn't support any forms of authentication.

I'm no go programmer but I will have an attempt at creating a PR for this, looks straight forward so far. 

Anything else I should be aware of?</div>

### PR DESCRIPTION
**Pull request by rruckley**
**What this PR does / why we need it**:
Adds option for Basic Auth to the Kafka REST Proxy Notifier
**Which issue(s) this PR fixes**:
41176

Fixes #41176

**Special notes for your reviewer**: First time submitting PR for Grafana in Go, be gentle.

### CODE REVIEW

**Comment by rruckley** [comment]
Build is failing on frontend lint but I haven't modified anything front end. I forked from main so must be a 8.3 dev issue?

**Comment by rruckley** [comment]
@malcolmholmes  How can I get the build working? I haven't changed any front-end code in my PR but the frontend lint step is failing, related to strict checks ?

**Comment by dprokop** [comment]
@rruckley can you please sync with the latest main?

**Comment by rruckley** [comment]
Sync completed, build now running.

**Comment by rruckley** [comment]
Spurious yarn dependency injected, now removed to match main:package.json

**Comment by rruckley** [comment]
@dprokop I've updated my branch, I believe all the issues are resolved, can we try the build again?

**Comment by rruckley** [comment]
@dprokop  Build passing now.

**Comment by rruckley** [comment]
@malcolmholmes  , @ying-jeanne  Any chance this can be included in 8.4.x?

**Comment by ColbyReed** [comment]
Why was this not merged? It looks like it's complete.

**Comment by rruckley** [comment]
> Why was this not merged? It looks like it's complete.

I've no idea, kept getting bumped then aged out? Such a simple thing. 

Ryan

**Pull request closed without merging**
