### PR TITLE
Prometheus nested query support

### PR DESCRIPTION
**Pull request by mtanda**
Try again! https://github.com/grafana/grafana/pull/9983

### CODE REVIEW

**Comment by bergquist** [comment]
Sorry but we cannot merge this.

The code looks good, both frontend and backend. But due to how alerting works* it's currently not possible to use nested queries with alerting. Which is a blocker. 

* Alerting saves the metric query per alert rule into a new table. So when alerting can only access the query specified in the alert tab and not the queries that should be nested.

**Comment by mtanda** [comment]
Just idea to implement this feature.
If Grafana can provide, expressions in panel menu as template variable like "__refId.A.expression__", this feature can be implemented by templating feature.

**Comment by bergquist** [comment]
@mtanda that's an interesting idea. Unfortunately, that's would not work in Grafanas alerting system either since templating is not supported. We have been discussing Grafanas alerting a lot recently and I think we might revisit the architecture soon to not block features like this. But until then this is not possible so I'm closing this PR. We can continue the discussion in https://github.com/grafana/grafana/issues/8791

**Comment by mtanda** [comment]
There is a difficulty to support some type of feature in datasource plugin.
I know the implementation of templated alert must be very complicated, so I'm ok to close this.
Continue to think about how we can implement feature more simply.

**Pull request closed without merging**
