### PR TITLE
Fixes bug in cloudwatch regarding credentials

### LINKED ISSUE #8891: [Bug] Grafana logs an IAM credentials error when running in an ECS task
- What Grafana version are you using?
```
# /usr/sbin/grafana-server  -v
Version 5.0.0-pre1 (commit: af56cc4)
```

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Docker in ECS (official grafana/grafana docker image)

- What did you do?
Tried to authorize with the container instance's ECS task role.

- What was the expected result?
Successful/correct authentication as the ECS task role.

- What happened instead?
The following error:

```
t=2017-07-19T21:27:06+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I updated to master because I had the same problem as noted #8750. Maybe that isn't fully fixed yet?

### LINKED ISSUE #9309: CloudWatch integration doesn't work with ECS task IAM role
After upgrade from 4.2.0 to 4.5.1 ECS task IAM role stopped working with Grafana.
Grafana is in AWS ECS container task and role assigned to ECS task worked before upgrade fine, as there was no configuration for that plugin.
Error in log
```
docker/grafana[481]: t=2017-09-19T16:06:44+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=19 orgId=1 uname=konstantin.shcherban error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

I've tried manually set both ec2 instance or ecs task role arns in CloudWatch data source configuration but it doesn't work as well.

If i disable ECS task IAM role grafana container works fine with underlying ec2 instance IAM role.

### PR DESCRIPTION
**Pull request by bwhaley**
Use package defaults for endpoint provider configuration rather than the ec2metadata config and handlers. 

closes #9309 
closes #8891

### CODE REVIEW

**Comment by bergquist** [comment]
Seems like `go fmt` is failing.
```bash
running go fmt
pkg/tsdb/cloudwatch/credentials.go
Executing 'test -z pkg/tsdb/cloudwatch/credentials.go'
'test -z pkg/tsdb/cloudwatch/credentials.go' returned 1.
```
Please run `gofmt -w -s ./pkg` in the root of the grafana folder and push the changes.

**Comment by bwhaley** [comment]
Thanks! Sorry for that oversight.

**Comment by bwhaley** [comment]
Ping - Any chance of having this one merged soon? I'd like to switch back to grafana/master rather than my fork. Thanks!

**Comment by bergquist** [comment]
Sorry! Got lost in a sea of notifications :)

Thanks for contributing to Grafana!

**Pull request merged**
