### PR TITLE
Navigation: Refactor existing menu to allow for scrolling 

### LINKED ISSUE #46726: Navigation: Refactor existing menu to allow for scrolling (need to portal the hover menu)
Refactor existing menu to allow for scrolling (need to portal the hover menu)

### PR DESCRIPTION
**Pull request by axelavargas**
**What this PR does / why we need it**:

We refactored the navbar code to `portal` the overlay menu for each navbar item on mouseover or keyboard navigation. The behavior should be the same as we currently have, this change is needed to implement this [issue](https://github.com/grafana/grafana/issues/47072)

*Important Approach Notes*

- We can't use our `Portal` component because the current navbar is using react aria hooks (they are not compatible)
- For each menu in the navbar, we must use `OverlayContainer` and `useOverlayPosition` from `react-aria`
- To control whether we show or hide the menu overlay (now located at the end of the `body`) on mouseover or keyboard navigation:
	  - Added a new prop called `menuIdOpen` which stores which menu is open
	  - The main purpose of this property is to keep the menu overlay open when we focus on the sub-items of the menu.
	  - The prop is passed via `NavBarContext` to each navBarItem
	  - As soon as we change the focus on the top navbar items (icons), the property is reset to null and a new value is assigned if there is one.

- [ ] Add a comment with an explanation about the responsibilities of `menuIdOpen`.

IAmAPortal

**Which issue(s) this PR fixes**:

Fixes #46726

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
think we need to fix this before merging. menu doesn't close when unhovering

https://user-images.githubusercontent.com/20999846/161075650-7976036b-b413-4e2b-9a8d-c33d83dd73aa.mp4

**Comment by axelavargas** [comment]
> think we need to fix this before merging. menu doesn't close when unhovering
> 
>  Screenshare.-.2022-03-31.3_06_17.PM.mp4

yeap, I think we got some merge conflicts and some things need to be fix

**Review by joshhunt — APPROVED** [review]
Beautiful! 🚀

**Review by ashharrison90 — APPROVED** [review]
minor nit: navbar item doesn't preserve it's hover state when you're hovering in the menu

| before | after |
| --- | --- |
| image | image |

doesn't have to hold out delivering this, but will need adding to the papercut list

**Pull request merged**
