### PR TITLE
Plugins: Fix file extension in development authentication guide

### PR DESCRIPTION
**Pull request by pbzona**
**What this PR does / why we need it**:
This is a small fix for what I believe to be a typo in the authentication guide for plugins. The file to edit is a Typescript file, not Go.

**Which issue(s) this PR fixes**:

n/a

**Special notes for your reviewer**:
Thanks for the great documentation!

### CODE REVIEW

**Review by wbrowne — APPROVED** [review]
LGTM. Thanks for the contribution @pbzona!

**Comment by wbrowne** [comment]
@pbzona Once you sign the CLA, we're good to merge 🚀

**Review by marefr — APPROVED** [review]
LGTM thanks

**Comment by marefr** [comment]
@pbzona can you please sign the CLA https://github.com/grafana/grafana/pull/53838#issuecomment-1218114565

**Comment by pbzona** [comment]
Sorry about that, missed the notification! All set now

**Pull request merged**
