### PR TITLE
Add new Redshift metrics and dimensions for Cloudwatch datasource

### PR DESCRIPTION
**Pull request by A21z**
AWS/Redshift has new dimensions (`latency`, `service class`, `wmlid`) and metrics (`QueriesCompletedPerSecond`, `QueryDuration`, `QueryRuntimeBreakdown`, `WLMQueriesCompletedPerSecond`, `WLMQueryDuration`, `WLMQueueLength`) in Cloudwatch: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rs-metricscollected.html

### CODE REVIEW

**Comment by marefr** [comment]
Hey. Sorry for feedback taken long time. If you could resolve the conflicts I'll have a look at this. Thanks

**Comment by A21z** [comment]
Thanks @marefr !
AWS added even more metrics/dimensions in the mean time (cf. https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rs-metricscollected.html):
Metrics: `WLMQueueLength`, `QueryRuntimeBreakdown`
Dimensions: `service class`

Can you take the conflict resolving opportunity to add them (I can do it otherwise)?

**Comment by marefr** [comment]
If you can do it that would be awesome. Thanks

**Comment by A21z** [comment]
@marefr I just rebased and add the new dimensions/metrics

Please note the `service class` dimension has a space in it, I'm not sure if this is the first one, it may break something.

**Review by marefr — APPROVED** [review]
Looks good :+1:

**Comment by marefr** [comment]
Thank you for your first contribution to Grafana! Very appreciated!

Thanks for the heads up regarding the space. We'll see if that would cause any issues, but merging this for now.

**Pull request merged**
