### PR TITLE
Themes: Unify secondary button and ToolbarButton

### LINKED ISSUE #68255: Saga DS - Secondary button styling adjustment
@torkelo's recent design changes to the secondary button styling need to be captured for the Figma components.

PR for reference https://github.com/grafana/grafana/pull/68250

```[tasklist]
### Tasks
- [ ] Update dark theme secondary button styles
- [ ] Update light theme secondary button styles
- [ ] Update Saga site assets
```

### PR DESCRIPTION
**Pull request by torkelo**
Problem

* The secondary button and the toolbar button (when placed on canvas or primary) looks different. Especially when placed on primary. Like the refresh picker, and some of the buttons in explore. 
* The ToolbarButton when placed on primary looks bad as it only has a weak border and nothing else (as ToolbarButton background is set to primary bg) 
* The gray secondary buttons look pretty bad, or they just look out of style a bit. Maybe it's because of the gray scale does not match the primary and secondary colors? 

Current state:
image
Current state:
image

Proposal:

* Use a new style for secondary that can work for both ToolbarButton and that looks good on both canvas and primary. Making the UI more consistent (and look a bit better). 

Screenshot from 2023-05-12 13-10-54
Screenshot from 2023-05-10 19-21-48
Screenshot from 2023-05-12 13-12-21
image

ToolbarButton on canvas (from storybook story) 
image

### CODE REVIEW

**Comment by staton-hyse11** [comment]
Capture UI changes here so design assets and documentation can be updated accordingly:
https://github.com/grafana/grafana/issues/68255

**Comment by torkelo** [comment]
Sadly ran into trouble making the normal secondary button   look like the outline button (with white bg) in the light theme. It broken the real outline version of the secondary button (that uses the secondary.main color as basis for a hover color). So instead opting for a shade of gray, this way the dark & light theme are more consistent (And there is a difference between normal secondary and outline secondary in both themes). The only problem is that when placing a secondary button or toolbar button on canvas it is not ideal right now (gray on gray). but works. And can be improved by further theme tweaks in the future (like making canvas color slightly brighter and less gray).

Screenshot from 2023-05-12 11-12-19

Screenshot from 2023-05-12 11-12-04

Screenshot from 2023-05-12 11-03-49

**Comment by torkelo** [comment]
@staton-hyse11 here are the colors:

Dark theme:

secondary button background (main): 
new value = `rgba(204, 204, 220, 0.10)`   (prev value: `rgba(204, 204, 220, 0.16)`

secondary button hover background (shade): 
new value =  `rgba(204, 204, 220, 0.14)`     (prev value: `rgba(204, 204, 220, 0.20)`

secondary button border
new value =  `rgba(204, 204, 220, 0.08)`  prev  transparent

Light theme:

secondary button background (main): 
new value = `rgba(36, 41, 46, 0.08)`   (prev value: `rgba(36, 41, 46, 0.16)`

secondary button hover background (shade): 
new value =  `rgba(36, 41, 46, 0.15)`     (prev value: `rgba(36, 41, 46, 0.20)`

secondary button border
new value =  `rgba(36, 41, 46, 0.12)`   (prev value transparent)

The values are the same for canvas variant of ToolbarButton, not sure if we have ToolbarButton component in figma. Maybe indirectly via RefreshPicker & TimePicker? ToolbarButton is a bit tricky as it has two variants currently a "canvas" variant and a default variant. The default variant is for when it lives in the actual nav toolbar, this variant has no background or border. This default version of the ToolbarButton has no changes in this PR. Long term we will try to not use this and move these buttons down into the page/canvas. 

Want me to update in figma? you will have to show me how, I have never done a figma component / theme change :)

**Review by staton-hyse11 — APPROVED** [review]
Figma changes have been merged — this is G2G

**Pull request merged**
