### PR TITLE
Style: Add emotion/syntax-preference to betterer

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

Introduces `@emotion/syntax-preference` rule to betterer

**Why do we need this feature?**

To prevent additional css template literals being added to the codebase. (See #71374.)

**Who is this feature for?**

Grafana developers

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
> but the eslint rule added in that pr only appears to apply to styled. syntax which we don't use.

pretty sure it applies to any syntax, it just only applies in `@grafana/ui` at the moment because it's the only place that's been fully converted to using the object syntax. you can test by trying to add any `css` template string anywhere in `@grafana/ui`. 

think having a betterer rule is a good idea, but we can simplify and just use the `@emotion/syntax-preference` rule to handle it 👍

**Comment by jackw** [comment]
> pretty sure it applies to any syntax, it just only applies in @grafana/ui at the moment because it's the only place that's been fully converted to using the object syntax. you can test by trying to add any css template string anywhere in @grafana/ui.

> think having a betterer rule is a good idea, but we can simplify and just use the @emotion/syntax-preference rule to handle it 👍

Ah thanks for taking a look @ashharrison90. You're right it is working as intended. I've reverted the custom rule and added `@emotion/syntax-preference` to the betterer file. 👍

**Review by ashharrison90 — APPROVED** [review]
lgtm, just need to run `yarn betterer` locally and commit 👍

**Review by ashharrison90 — APPROVED** [review]
lgtm 🔧💪

**Pull request merged**
