### PR TITLE
Logs: Allow to reach the bottom of the log list before loading more logs

### PR DESCRIPTION
**Pull request by matyax**
As it was proposed in https://github.com/grafana/grafana/pull/84318 (commit https://github.com/grafana/grafana/pull/84318/commits/d876f45c2ea523495f44fe7f4ced5f7ab4e1d7c1) when top scroll used to be enabled, we're adding the edge implementation to the bottom scroll, to give users a chance of reaching the bottom before triggering a new request.

Demo:

https://github.com/user-attachments/assets/e67740ac-22cc-4a9e-b705-b8e7d812a504

### CODE REVIEW

**Comment by matyax** [comment]
Ready for review.

**Comment by gtk-grafana** [comment]
I'm seeing infinite scroll broken on this branch
* backward - oldest first
* backward - newest first
* forward - newest first
* forward - oldest first

`logsInfiniteScrolling` is enabled, and I'm seeing everything work fine in on main.
Here's the [query/datasource I'm testing with](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22nhk%22:%7B%22datasource%22:%22OP27Xzxnk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22aggregator%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22OP27Xzxnk%22%7D,%22editorMode%22:%22code%22,%22maxLines%22:20%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)

**Comment by matyax** [comment]
Great catch @gtk-grafana. Updated for trackpad.

**Comment by gtk-grafana** [comment]
@matyax now it's working as long as my line limit is over 100 AND I scroll to the bottom of the log lines without dragging the scroll bar (i.e. I only scroll with the trackpad). 

Also I see the log lines shifting a pixel or two while it's loading:
https://github.com/user-attachments/assets/9da13d23-a501-486b-a994-a0fed3c59507

**Comment by matyax** [comment]
I suspect some of that should be a byproduct of a recent scroll component change because is not related with any of these changes. Will investigate.

**Comment by matyax** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/96668

**Pull request closed without merging**
