### PR TITLE
Prometheus: Render missing labels in legend formats as an empty string

### LINKED ISSUE #16041: Make label rendering optional for labels that don't exist on metrics in Prometheus
**What would you like to be added**: Currently if a metric is missing a label that you've included in the legend format, 
# Current Behavior
Series with labels {'label1": "value1, "label2": "value2", "label3": "value3"}
Template string: "Readable Label: {{ label1 }} - {{ label2 }} - {{ label3 }}"
Rendered Result "Readable Label: value1 - value2 - value3

Series with labels {'label1": "value1, "label3": "value3"}
Template string: "Readable Label: {{ label1 }} - {{ label2 }} - {{ label3 }}"
Rendered Result "Readable Label: value1 - label2 - value3

# Proposed Change

Series with labels {'label1": "value1, "label3": "value3"}
Template string: "Readable Label: {{ label1 }} {{ - || label2 }} {{ label3 }}"
Rendered Result "Readable Label: value1 - value3

**Why is this needed**:
Sometimes you may want to show values for mixed cardinality metrics in the same visualization, and still maintain readable and friendly legend formats, this feature allows additional flexibility to the user in that situation. 
However, this does have the potential to be precedent setting for other datasources, so it's worth consideration to make sure it's at the right abstraction level. My goal in this implementation was to leave all existing legend formats unaffected with no breaking changes.

### PR DESCRIPTION
**Pull request by Hixon10**
Fixes https://github.com/grafana/grafana/issues/16041

### CODE REVIEW

**Comment by Hixon10** [comment]
@aocenas hello! Could you review my PR, please?

**Review by torkelo — COMMENTED** [review]
I think this change looks good.

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by Hixon10** [comment]
@aknuds1 hello, could you merge this pr then?

**Comment by torkelo** [comment]
Thanks for contributing!

**Comment by Hixon10** [comment]
@torkelo thanks for helping with my first PR in your project. It was awesome! I should say, you really have perfect guideline how to contribute to project (rules, how to build and start project, etc)

**Comment by torkelo** [comment]
thanks

**Pull request merged**
