### PR TITLE
Core: Implement aria attributes for query rows, improve a11y

### LINKED ISSUE #53924: A11y: Implement aria-expanded for query rows
to make query rows more accessible consider the following: 

- [aria-expanded](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded)
- https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.

Questions to be discussed:

- What's the position of a11y-wg on that topic? 
- Are there people using Grafana with screen readers? What data do we have on this topic? Did somebody do a user interview with an affected person?
- What about other places in Explore, e.g. query history?

### PR DESCRIPTION
**Pull request by L-M-K-B**
Fixes #53924

### CODE REVIEW

**Comment by Elfo404** [comment]
note that only using `aria-expanded` is not sufficient, it should also be paired with `aria-controls` that references the controlled element. see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#buttons for example

**Comment by Elfo404** [comment]
it tells assistive technologies which section of the document is controlled by that toggle button (and in turn, which control controls a section).
section stating it's being controlled by a pushbutton:
Screenshot 2022-09-22 at 10 59 39
pushbutton saying it controls a specific section of the document:
Screenshot 2022-09-22 at 11 01 58

not every screen reader makes use of this AFAIK, and not using it (or any aria attribute for that matter) still works because aria attributes do not "add" functionality to the underlying document

**Comment by L-M-K-B** [comment]
Thanks a lot. I added the attribute.

**Review by eledobleefe — APPROVED** [review]
Looks good to me 👍  but I don't have full context so you might want to wait for another review.

**Review by Elfo404 — CHANGES_REQUESTED** [review]
Screenshot 2022-09-23 at 15 20 39

the collapsible content doesn't seem to have any `id`, it should match the one used in the toggle button. 

~ think you may be able to achieve this just by ~passing the id to `renderPluginEditor` in `public/app/features/query/components/QueryEditorRow.tsx`~

doing `<div className={rowClasses} id={id}>` in `public/app/features/query/components/QueryEditorRow.tsx` on line 478

**Comment by L-M-K-B** [comment]
Screenshot 2022-09-27 at 15 48 19

@Elfo404 After my latest change the id appears in the shown div.

**Comment by Elfo404** [comment]
looks good! one thing i noticed while testing though is that we can end up in a situation where IDs are duplicated, for instance in Explore split view when queries in the right and left pane have the same refId, given the id here is the refId of the query. can we make sure ids are always unique?

**Comment by L-M-K-B** [comment]
I checked the query object but there is nothing unique in there which I could use. 
So there are two possible options:
1. prefix the refId with left/right in case the split pane is used. (This doesn't prevent having the same IDs in case the user renames the query rows and chooses the same names for all of them.)
2. combine the refId with a random number created by uuid which would create a really unique ID

Which option do you prefer or do you have another idea?

**Review by Elfo404 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
