### PR TITLE
i18n: Fix unnecessary ampersand escaping

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
The text "Browser & OS" was set as "Browser \&amp; OS" in the JSON, but I think manually escaping like that isn't necessary and resulted in the text being escaped twice.

Before:
Screenshot 2022-10-10 at 16 16 45

After:
Screenshot 2022-10-10 at 16 17 47

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Review by joshhunt — APPROVED** [review]
hmm, thanks for this. Lets get this in, and see if there's another change we need to make elsewhere to prevent this sort of thing from happening again...

**Comment by ashharrison90** [comment]
ah yeah, actually isn't this just gonna get overwritten as soon as someone runs `yarn i18n:extract` again? 🤔

**Comment by kaydelaney** [comment]
Ah, my bad, forgot it was generated. Hold on

**Review by ashharrison90 — APPROVED** [review]
ok _now_ it looks good 😅

**Pull request merged**
