### PR TITLE
Chore: Switch yarn 2 to plug-n-play strategy

### LINKED ISSUE #40488: node_modules improperly deduped/symlinked/hoisted after yarn upgrade
cc @kaydelaney @jackw @gabor @joshhunt 

on `main`:

- 5 copies of lodash
- 2 copies of uPlot
- 2 copies of immutable
- 2 copies of slate-react
- ...

these should all have been hoisted/symlinked/deduped by yarn, i think.

here's an updated `webpack-bundle-analyzer` branch you can use for testing `yarn install && yarn build` (it also has Terser disabled for faster production builds): https://github.com/grafana/grafana/tree/leeoniya/webpack-bundle-analyzer-4.5.0

image

comparing downloaded packages generated by CI (left 8.2.1 vs right 8.3.0-pre):

image

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Changes our setup to allow for yarn's [plug and play](https://yarnpkg.com/features/pnp) installation strategy, which promises faster installs, more consistent/logical dependency resolution, and a smaller dependency footprint, among other benefits. After briefly messing around, it seems like most things work. Integration and e2e tests seem to pass, grafana builds successfully, etc. but there are still some things that should be investigated before we take the plunge.

A (non-exhaustive) list:
- [x] Check impact on bundle sizes (6.38 MB entry point, vs 7.37 on main)
- [x] Check if monaco is broken / fix it if necessary
- [x] Check impact on grafana-toolkit / plugins
- [x] Check if storybook is broken / fix if necessary

Some additional setup might be required for full editor support: See https://yarnpkg.com/getting-started/editor-sdks for details

### CODE REVIEW

**Comment by leeoniya** [comment]
> Check impact on bundle sizes (6.38 MB entry point, vs 7.37 on main)

i wonder if this fixes https://github.com/grafana/grafana/issues/40488? :thinking:

**Review by jackw — COMMENTED** [review]
@kaydelaney amazing stuff! 🚀 

I cloned this and took it for a spin. I hit a hurdle with getting webpack running from a clean clone of the repo due to unicons copy plugin. After I got past that `yarn dev` and `yarn build` both appear to work. Looks like Storybook is missing a `terser-webpack-plugin` dependency preventing it from starting. 🤔 

The only other thought that came to mind whilst playing with this is IDE support for PnP and how it might affect contributors. I cannot find a definitive list of what does or does not support PnP.

**Review by hugohaggmark — COMMENTED** [review]
This is massive work. I haven't tried it out locally yet though. Would be great to hear a talk about yarn2+ and pnp in a future Frontend Weekly. I think it's vital that we spread the knowledge about this change.

**Review by mckn — COMMENTED** [review]
Exciting stuff! I need to do some more testing but a couple of questions:

- Should we update the .gitignore (https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored)
- How will this affect external plugin developers? Will it work in all environments/editors?

**Comment by mckn** [comment]
Locally for me it works really good! I think we should try to build `grafana-toolkit`, link it and test it locally with a plugin. Just to verify that the plugin still builds without any changes.

What do you think about that?

**Review by dprokop — APPROVED** [review]
Works like a charm! Awesome work @kaydelaney, as always!

**Review by zoltanbedi — APPROVED** [review]
This is exciting! Awesome job on this!

I've run `yarn dlx @yarnpkg/sdks vscode` which created some diffs maybe it is worth running that again and committing the changes.

**Review by jackw — APPROVED** [review]
Taken it for another spin and it is working great locally for `start`, `build` and `storybook` scripts @kaydelaney.

Do we need to add anything to the contributing docs like mentioning devs need the latest version of yarn v1 before running `yarn install`? (Not really tied to this PR but asking none the less.)

This will have an impact on others that build Grafana (e.g. [homebrew](https://github.com/Homebrew/homebrew-core/blob/e177391af5eee63f7e189c00e9d82ce84e277a53/Formula/grafana.rb#L34)). Don't know if there's anything we can do to help there or wait until closer to 8.3.0 release and get involved?

**Review by mckn — APPROVED** [review]
great work

**Pull request merged**
