### PR TITLE
RolePicker: Adjust dynamic position

### PR DESCRIPTION
**Pull request by linoman**
**What is this feature?**

Adjust the dynamic position of the RolePicker menu.

**Why do we need this feature?**

The menu showed up at the cursor position and closed again immediately.

**Who is this feature for?**

IAM

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by IevaVasiljeva — COMMENTED** [review]
I tested this, and I think it reintroduces the issue of role picker disappearing when a large number of roles is selected (the same issue that was fixed in https://github.com/grafana/grafana/pull/85604).

But it does fix the issue of role picker not staying open 😄

**Comment by tskarhed** [comment]
Should ownership of this component be transferred to the Identity Access team? Feel free to update the CODEOWNERS file.

**Comment by linoman** [comment]
@tskarhed Having front-end specialists review and approve our work can greatly improve the quality of our output.

**Review by IevaVasiljeva — APPROVED** [review]
Nice, looks much better! I can still see an issue when viewing the role picker on a smaller screen when I have a very large amount of roles assigned (the role picker gets slowly pushed off the screen, and then is not visible at all when I try to open it). I'll attach a recording with it. However, I don't think people in practice assign that many roles, and this is a way smaller issue than what you're trying to fix (the role picker opening and immediately closing). So I think - let's ship it, and see if anyone complains.

https://github.com/grafana/grafana/assets/9482349/a609eb20-6765-40b3-b997-6123722b1513

**Comment by linoman** [comment]
I agree with you @IevaVasiljeva and this leds me to believe that the role picker might benefit from an overhaul. With that in mind, I want to revisit it with the help of @vesnadean 

I'll keep you posted. Thanks for the review.

**Pull request merged**
