### PR TITLE
Auth: Enable `None` role for 10.2

### PR DESCRIPTION
**Pull request by eleijonmarck**
**What is this feature?**
This removes the featuretoggle for the `noBasicRole` as part of being GA in 10.2

Part of #
https://github.com/grafana/identity-access-team/issues/134

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by aarongodin — APPROVED** [review]
LGTM

**Review by buccarel — APPROVED** [review]
🚀

**Review by IevaVasiljeva — APPROVED** [review]
Nice! I'm excited to GA this!

**Comment by eleijonmarck** [comment]
let's GA the `None` role! 💯

**Pull request merged**
