### PR TITLE
fix to match table column name and order

### LINKED ISSUE #11690: panel/table columns' title don't change when rearrange queries.
*Suggested label: "type/bug" label:"comp: panel/table"*
### What Grafana version are you using? & What OS are you running grafana on?
Grafana:5.0.4 on Docker
### DataSource
Prometheus
### What did you do?&What was the expected result?&What happened instead?

When using panel/table with multiple queries. The columns' titles should match with queries, which is true until you rearrange the queries with "Move up/Move down". The queries and columns are rearranged but the columns' title remain alphabetical `Value #A` `Value #B` `Value #C`

screen_shot_2018-04-23_at_10_01_20_am

screen_shot_2018-04-23_at_10_01_40_am_1

### What's the influence? 
**This will mess up the `Column Styles` completely which match the tables with their names(*Apply-to-columns-named*)** Especially when you have values of different data types.

### PR DESCRIPTION
**Pull request by mtanda**
Fixes #11690

### CODE REVIEW

**Comment by bergquist** [comment]
:+1: Possible to add some tests?

**Review by marefr — CHANGES_REQUESTED** [review]
These changes needs some tests

**Comment by mtanda** [comment]
add test!

**Review by marefr — APPROVED** [review]
Great

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
