### PR TITLE
Docker: Upgrade Ubuntu to 19.10

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Upgrade our Dockerfiles to latest Ubuntu version (19.10). Hoping it will fix our CircleCI build failures.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
hope this helps 🙏

**Comment by aknuds1** [comment]
We just feel a bit iffy about upgrading before version 6.6.2, but we don't know yet if we can fix the build either without upgrading the repos to v19 :/

**Comment by papagian** [comment]
> We just feel a bit iffy about upgrading before version 6.6.2, but we don't know yet if we can fix the build either without upgrading the repos to v19 :/

yes, but I think that we cannot make the release without this.
on top of this:
`grafana-docker-ubuntu-pr` job [succeeds](https://circleci.com/gh/grafana/grafana/265346?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)
so I guess that's it!

**Comment by aknuds1** [comment]
@papagian After discussing with Marcus and Leonard, looks as if we might try 18.04 LTS for 6.6.2, since our theory is that it will be less disruptive than going up to 19. I'm going to build an image based on 18.04 now and scan it for security issues.

**Comment by aknuds1** [comment]
@papagian @dprokop I made a separate 18.04 PR to v6.6.x branch, since it's only for 6.6. Merging this one :D

**Pull request merged**
