### PR TITLE
9903 fix templating

### PR DESCRIPTION
**Pull request by osius**
This PR should fix the issue #9903:

Steps to verify that templating is working with cloudwatch:

* Add a aws-cloudwatch datasource to grafana
* Add a new dashboard 
* Add a variable to the new dashboard
  * Name: "instanceId"
  * Type: "Query"
  * Data source: select the aws-cloudwatch datasource
  * Query: "ec2_instance_attribute(<your-region>, InstanceId, {})"
  * Select:  "Multi-value" and "Include All option"
* Add Graf to Dashboard:
  * under General: 
    * Title: $instanceId
    * select Repeat-> "For each value of" -> instanceId (name of var)
  * under metic:
    * select same Datasource
    * add a query with region, 
      * Namespace=AWS/EC2,
      *  metric=CPUUtilization 
      * Dimensions: InstanceId=$instanceId
  * save and reload the dashboard
* go an select "All" for instanceId
* The result should be one CPUUtilization graph for each instance you have running in the aws.

### CODE REVIEW

**Comment by bergquist** [comment]
I cant verify that this will solve the issue but its a good fix regardless since its a spelling error.

**Comment by mholland** [comment]
@osius and @bergquist, can confirm this does indeed fix #9903 ! Thanks very much 👍 

Was wondering if this fix will make it into a new 4.6.x release any time soon? Would love to get upgraded asap. 

Thanks.

**Comment by bergquist** [comment]
@mholland I don't think we will make a 4.6.x release. Our goal is to make a 5.0 beta release next week. And unless we get really bad feedback on that we want to roll forward instead.

**Comment by mholland** [comment]
That sounds good, thanks.

**Comment by sbrandtb** [comment]
@bergquist Please, make a 4.6.x bugfix release.

In my company, we want to use 4.6 badly and cannot because we have run into three issues so far:

* [issue in plugin related to new plugin architecture](https://github.com/Vonage/Grafana_Status_panel/issues/81)
* [template filtering broken in cludwatch data source](https://github.com/grafana/grafana/issues/9667)
* _this_ issue

I'm afraid that with 5.0, the story will repeat. I really want to believe that it's just cloudwatch that is crap and no one cares for it and thus the data source is broken, but after all, it gave my trust into Grafana a huge bump. I'm kind of sure that there are others out there with the same issues, so why not make a bugfix release?

**Comment by torkelo** [comment]
the issue with Grafana_Status_panel as been fixed in latest version of the status pane plugin. 

This second issue you link to is supposed to be fixed by this PR so why do you think your problem will remain in v5?

**Comment by sbrandtb** [comment]
@torkelo Sorry, I forgot to mention: The first two issues are solved. Only the last one remains. Since it renders CloudWatch data source virtually unusable for everyone with more than one instance, it would be great to make a bugfix release.

**Comment by torkelo** [comment]
> Only the last one remains. Since it renders CloudWatch data source virtually unusable for everyone with more than one instance, it would be great to make a bugfix release. 

what issue is that? you only referred to two issues, both solved. (your list included three lines but the last line says `this issue` but this issue solves the issue you linked to on the second line). 

> Also, I'm not talking about that my issue will remain in 5.0 - I'm talking about that I expect that at least three new bugs will appear in 5.0 for the new code, making me still stuck with 4.5

What new bugs are that?

**Comment by sbrandtb** [comment]
I try to phrase it differently.

We're running Grafana 4.5 with CloudWatch as our only data source.

When trying to upgrade to 4.6, we ran into at least three issues that *blocked* us from upgrading:

* [bug](https://github.com/Vonage/Grafana_Status_panel/issues/81) due to new plugin infrastructure in a plugin we use - *fixed*
* [bug](https://github.com/grafana/grafana/issues/9667) that rendered `ec2_instance_attribute` template filters unusable *fixed*
* [bug](https://github.com/grafana/grafana/issues/9903) that prevented iterating over instances in variables.

The last one is the one this pull request fixes. My point is: Why not make a bugfix release that includes this fix?

> What new bugs are that?

I don't know. Usually I don't expect a whole bunch of blocking bugs when upgrading to a new stable version. Again, my whole point is: Why not try to make 4.6 stable instead of forcing users to try 5.0? Maybe there will be new bugs, maybe not.

You can as well say "releasing a bugfix is hell of work and that's why we don't want to do this", but until now, no one explained why this won't be in a bugfix release.

**Comment by torkelo** [comment]
It was only merged 6 days ago, no confirmation yet that it truly fixed https://github.com/grafana/grafana/issues/9903 

We do of course release patches for bugs last stable release when there is a critical bug. This was a bit obscure bug in a feature for Cloudwatch that was accidentally added (supporting multi valued variables should never have been added in the first place as Cloudwatch api support it so poorly and requires a hacky solution in Grafana). We are very close to v5.0 release so we do prefer skip doing a patch release but if this solution appears to fix the issue and there is enough demand for a patch release then that is of course something we will consider.

**Pull request merged**
