### PR TITLE
Generic timeseries tooltip

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This is an initial implementation of #14085.
Now it implements tooltip for the graph panel with the same features as a previous one.

### Design goals
The main goal is to make tooltip more abstracted from the graph panel and potentially reusable for the other panels which work with time-sereis data. The second goal is split it out into small parts, each with its own independent functions. It allows inheriting more specific components from more general. Also, components should work with a new interface to time series view models - [TimeSeriesVM](https://github.com/grafana/grafana/blob/master/public/app/types/series.ts#L63).

#### TimeAxisTooltip 
Created by `withTimeAxisTooltip()` HOC. Implements generic behaviour for time-based tooltips.

```ts
interface TimeAxisTooltipProps {
chartElem: any;
panelId: number;
sharedTooltip?: boolean;
hoverEvent?: string; // Event which tooltip is showing on. Default is 'plothover'
useCSSTransforms?: boolean;
getOffset: (x) => number; // Function converting timestamp into offset on chart
onMouseleave?: (event?) => void;
}
```

Components gets `chartElem` and subscribes to hover event. Default hover event is `plothover`, triggered by the `flot.js` library, but may be any event (not implemented yet) with mouse coordinates, like `mousemove`. Also, components listen to global `graph-hover` event (which now is triggering by the panel when user hovers a mouse over the chart) and shows shared tooltip if it's enabled. Position for shared tooltip is calculated through the `getOffset()` function, passed in component props.

Component doesn't take series or any other data related to event. The main purpose of this component is to display tooltip in the appropriate place and inject few props (`position` and `item` from the plothover event) into the underlying component.

#### TimeSeriesTooltip
Created by `withTimeSeriesTooltip()` HOC. Implements behaviour for time-series tooltips. This component takes `series` and other related params (allSeriesMode, hideEmpty, hideZero, etc) and calculates "series hover info" - information about hovered series and datapoint. Alongside with this, components calls `onHighlight()` and `onUnhighlight()` callbacks for highlighting hovered points on the chart. Component injects `series`, `hoverInfo` and `item` (from plothover event, if present) into wrapped component.

#### GraphTooltip
Component which implements graph panel tooltip itself. Just controls how to present information about series on the TimeSeriesTooltip.

So a quick summary looks like:

* **TimeAxisTooltip** - handles hover events and controls tooltip position
* **TimeSeriesTooltip** - makes time series-related calculations (hover info)
* **GraphTooltip** - renders tooltip content

### Pitfalls
Generic `TimeAxisTooltip` component still rely on flot hover event:

```ts
handleHoverEvent = (event, position: FlotPosition, item?: FlotHoverItem) => {
```

it should be improved and can handle different events, like `mousemove` or `mouseover`, which have no `position` argument.

High order components with _Injector_ pattern look a bit tricky to use. [Here's](https://medium.com/@jrwebdev/react-higher-order-component-patterns-in-typescript-42278f7590fb) a good article about types usage in HOCs.

### Improvements
Tooltip placement was changed - now it doesn't change Y position (pinned to the bottom of graph) and X position is restricted by the panel bounds. 
I also added throttling for the series hover info calculation. Too frequent calculation of this info may cause a lot of re-renders and eventually lags in tooltip, especially with shared tooltips. So reasonable default throttling make sense in this case.
Tooltip now positioned with `transform: translate()` CSS property by default - it's faster and smoother than `top, left` approach (this can be changed by `useCSSTransforms` property).

Let's discuss it. Any thoughts appreciated.

### CODE REVIEW

**Comment by torkelo** [comment]
Looks like a great start Alex, will try to find time to review & test soon, and might take help from others as well. 

I wonder if using render props is better then HOC for some these components:

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L83

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/DataPanel.tsx#L23

**Comment by alexanderzobnin** [comment]
Yes, that might be an option, I'll try it out.

**Comment by alexanderzobnin** [comment]
@torkelo this work gets stuck, should we continue on this? The related issue is till open.

**Comment by torkelo** [comment]
We can leave it open a bit, we still have to do a generic visualization hover tooltip for @grafana/ui and this might come in handy and parts can be taken from this then

**Comment by alexanderzobnin** [comment]
Yes, there are some performance tricks, so hopefully, it will be useful.

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/pull/20046

**Pull request closed without merging**
