### PR TITLE
DashboardGrid: Refactorings and performance improvements 

### PR DESCRIPTION
**Pull request by torkelo**
This PR makes me so happy, have tried this like 5 times last few years but always struggled with some strange react-grid-layout issue or other 

* [x] Change how we calculate if a panel is in view by using panel grid position instead of using element position, this speeds up a lot and we no longer need two render paths to figure out if a panel is in view or not. This double render was required before (discovered and fixed in https://github.com/grafana/grafana/pull/35906 as removing double render made the isInView logic no longer work properly as it needed the element reference that is only set on first render path). But now there is no longer any need for element references! 
* [x] Improve and simplify the logic for knowing when a panel is below or above the viewport 
* [x] Limit access of window.innerHeight (can trigger page re-flow) 
* [x] Remove size-me in DashboardGrid and replace with AutoSizer, we can now remove this dependency
* [x] Remove the AutoSizer in DashboardPanel and instead use width and height set by react-grid-layout The fact that we have had this AutoSizer has always annoyed me when the grid already knows exactly the dimensions of the panel.

### CODE REVIEW

**Comment by axelavargas** [comment]
@torkelo these are very nice improvements, the logic is definitely cleaner 🙌🏾. I was testing locally and I found a small issue:

When resizing each panel using the mouse the panel gets resized, but the content doesn't. (I experimented a bit adding the `forceUpdate` on the `onLayoutChange` and kinda solved the problem, maybe this has to do with the fact that we only update the gridPos in the `OnResizeStop` function?)

rendering-problems

**Comment by torkelo** [comment]
@axelavargas good catch! 😢 not sure I can get rid of the AutoSizer then :(

**Comment by torkelo** [comment]
@axelavargas found a very different solution that allows me to receive the width and height set by react grid layout & react resizable

**Comment by axelavargas** [comment]
> @axelavargas found a very different solution that allows me to receive the width and height set by react grid layout & react resizable

@torkelo amazing, the issue is fixed, but I found another one 😢, it seems like now the dashboard elements are not draggable.

In the console, there are some errors: one related to `GridItem` not having unique props and the other error

```
Uncaught Error: <DraggableCore> not mounted on DragStart!
    at DraggableCore.handleDragStart
```


dashboard-not-dragabble

**Comment by torkelo** [comment]
@axelavargas thanks for testing and finding another bug! I fixed this one now, I needed to use React.forwardRef for the GridItem component so that the Draggable component has access to the grid item div ref

**Review by axelavargas — APPROVED** [review]
Really nice cleanup Torkel 🙌🏾 , I did the last review/testing (I only could test on chrome, firefox, and mobile) and everything works as expected 🎉

**Comment by axelavargas** [comment]
🎗️ Also a small reminder, the milestone is missing 😄 (_I was not sure how we want to approach this one, because is an improvement, not a bug fix, I am thinking on to 8.1.0_)

**Comment by torkelo** [comment]
@axelavargas merged this, super good help with testing on this one!

**Comment by hugohaggmark** [comment]
Causes this issue https://github.com/grafana/grafana/issues/38853

**Comment by hugohaggmark** [comment]
Causes this issue #38805

**Pull request merged**
