### PR TITLE
Bookmarks: Create Bookmarks landing page

### LINKED ISSUE #90722: Navigation: Bookmarks page is not updated with new items until refresh
When you bookmark an item, it is automatically added to the bookmarks on the menu but not to the Bookmark page. As you can see in this screenshot, this happens with 'Playlists' being on the menu but not on the page; even after going from one page to another, when you return to the Bookmark page, it is not still there. You need to refresh the page to see the addition.
Captura de pantalla 2024-07-17 a las 10 42 49

_Originally posted by @eledobleefe in https://github.com/grafana/grafana/issues/90280#issuecomment-2232774581_

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What is this feature?**

This creates a `BookmarksPage` component based on the `NavLandingPage`.

**Why do we need this feature?**

Using `NavLandingPage`, the page is not refreshed when a new bookmark is added, while this one updates when `pinnedItems` changes.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #90722

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
Now it updates its content right after clicking to bookmark a menu item 🙌

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady [11.2.x Release Branch](https://github.com/grafana/grafana/tree/v11.2.x) was cut this week, and that it includes the changes committed up to https://github.com/grafana/grafana/commit/b4126d3bce3627e9460e2db0e870c8d984be8e84. This PR was merged after it, so we wanted to let you know that you can add the `backport v11.2.x` label to to backport it and make it part of the next 11.2.x Patch Release, just in case you may have missed the news.

Thank you!

**Pull request merged**
