### PR TITLE
Chore: Removes gf-form from profile/user

### PR DESCRIPTION
**Pull request by khushijain21**
Part of https://github.com/grafana/grafana/issues/65513

image

### CODE REVIEW

**Comment by khushijain21** [comment]
@Clarity-89

**Review by Clarity-89 — APPROVED** [review]

**Comment by Clarity-89** [comment]
@khushijain21 it looks like you need to run `yarn run betterer` and commit the result of that to fix the build.

**Comment by khushijain21** [comment]
uh I ran betterer, that didn't change anything. It also ran on pre-commit hook

**Comment by Clarity-89** [comment]
> uh I ran betterer, that didn't change anything. It also ran on pre-commit hook

Strange, try merging the latest main into your branch and running `yarn run betterer` again.

**Pull request merged**
