### PR TITLE
Added radiation units

### PR DESCRIPTION
**Pull request by victorclaessen**
Add common units in radiation and health physics monitoring, Bq, Ci, Gy, rad, Sv, rem. C/kg, R, Sv/h.

### CODE REVIEW

**Comment by bergquist** [comment]
The commits from this PR should be squashed when we merge it into 5.1

**Review by bergquist — APPROVED** [review]

**Comment by victorclaessen** [comment]
Yes, sorry about that; still a bit unsure on branching and squashing commits sometimes. Took about an hour to fix :-S. I hope it's alright now.

**Comment by gabrielklein** [comment]
In Geiger Counter, radiation exposure is μsv/h and not Sv/h. Would it make sense to add this unit? 

Common values are around 0.100-0.300 μsv/h

**Comment by marefr** [comment]
@gabrielklein please open an issue with your suggested change/addition and/or open a PR with suggested changes.

**Comment by victorclaessen** [comment]
@gabrielklein In issue #11559 I describe this in a more general sense. Greek-letter prefixes for numbers smaller than 1 would be helpful for many things, not only dose rates. So far this issue has not generated a lot of traction.

**Comment by NgTrThanh** [comment]
Please add 
name: 'Normal cubic meter per hour', id: 'Nm3/h', fn: toFixedUnit('Nm³/h')

**Pull request merged**
