### PR TITLE
Displaying Last UpdatedBy as Metadata

### PR DESCRIPTION
**Pull request by utkarshcmu**
Added 2 columns to dashboard table for recording created_by userId and updated_by userId.

So that this can be displayed in Metadata info panel. 

To support #3047

### CODE REVIEW

**Comment by utkarshcmu** [comment]
@torkelo Is there any scope of getting this PR merged? I understand not right now but in the future?

**Comment by torkelo** [comment]
yes!

**Comment by utkarshcmu** [comment]
Thanks :)

**Comment by utkarshcmu** [comment]
Can this be merged in the master now as 2.6 is already released? :)

**Comment by utkarshcmu** [comment]
@torkelo , @bergquist Also, we can have the default value for "created_by" and "updated_by" as "Unknown" or "Anonymous". What do you guys think? 

Any more work needed to get this PR merged? Once this gets merged, I can work on getting the "created_by" and "updated_by" columns populated with the correct user via Code.

**Comment by bergquist** [comment]
I prefer "Anonymous" since it align with the configuration "[auth.anonymous]"

**Comment by utkarshcmu** [comment]
@torkelo / @bergquist This PR is ready for review/merge. Here are some screenshots of what it will show on the UI:

Scenario:

Dashboard created by Anonymous user:
screen shot 2015-12-18 at 3 45 40 am

Dashboard updated by Admin user:
screen shot 2015-12-18 at 3 46 05 am

Dashboard then again updated by Utkarsh user:
screen shot 2015-12-18 at 3 46 27 am

Please let me know if there should be any other change has to be made in this PR.

**Comment by bergquist** [comment]
I'll check it out later today or tomorrow

**Pull request merged**
