### PR TITLE
plugins-platform: fix: plugin extension component to receive context

### PR DESCRIPTION
**Pull request by darrenjaneczek**
**What is this feature?**

The documentation mentions that it's possible receive the extension `context` object as a prop of the component extension:
- https://grafana.com/developers/plugin-tools/ui-extensions/register-an-extension

E.g., 

```ts
type Props = {
  context: PluginExtensionSampleContext;
};

export const MyExtension = ({ context }: Props) => (
  <Button onClick={() => {}} variant="secondary" type="button">
    Create incident from {context.name}
  </Button>
);
```

However, I wasn't able to get the context.

This PR seems to fix that.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mckn — COMMENTED** [review]
LGTM but waiting for @leventebalogh to review this one. Thanks for opening this PR @darrenjaneczek 🙏🏻

**Comment by leventebalogh** [comment]
Thanks for contributing to this one @darrenjaneczek 🙏 

Hmm, this is a very good point actually, and I just realised, that this feature is not well documented at all.

```js
type MyContext = { foo: string };

const extensionPointId = 'foo';
const context: MyContext = { foo: 'bar' };

// Option 1)
// ---------
// This is how it works currently, and this is how I ideally imagined it, however it's probably
// not clear, as it differs from how the context is passed for other extension types (where
// it is passed to the `getPluginExtensions()` function)
const { extensions } = getPluginComponentExtensions<({ extensionPointId });

return (
  <>
    {extensions.map(extension => {
      const ExtensionComponent = extension.component;
      return <ExtensionComponent foo={context.foo} />;
    })}
  <>
);


// Option 2)
// ---------
// It is what you proposed basically, so passing the context directly to the `getPluginExtensions` function.
const { extensions } = getPluginComponentExtensions<({ extensionPointId, context });

return (
  <>
    {extensions.map(extension => {
      const ExtensionComponent = extension.component;
      return <ExtensionComponent />;
    })}
  <>
);

```

I am not sure which one is more intuitive to be honest. I like **Option 1)** because it's closer to how we generally pass props to components, however it goes against the pattern that we have with other extension types. **Option 2)** is not bad either, my only problem there is that it will allow two different ways to pass the context for the component (as a prop or as a function parameter), which can be confusing. What do you both think?

**One thing is for sure: however we decide we have to focus on adding examples for this and update our docs around this to make it more clear.**

**Comment by leventebalogh** [comment]
After discussing it with @mckn we came to a conclusion that we would rather like to keep the current pattern and pass contextual information to components as props. Sorry for the confusion @darrenjaneczek and thanks a lot for your contribution. 

I have created a PR which tries to make the typing better for the `getPluginComponentExtensions()` function, please let me know what you think: https://github.com/grafana/grafana/pull/84295

**Review by leventebalogh — CHANGES_REQUESTED** [review]
After discussing it with @mckn we came to a conclusion that we would rather like to keep the current pattern and pass contextual information to components as props. Sorry for the confusion @darrenjaneczek and thanks a lot for your contribution.

I have created a PR which tries to make the typing better for the getPluginComponentExtensions() function, please let me know what you think: https://github.com/grafana/grafana/pull/84295

**Comment by darrenjaneczek** [comment]
Ok, I will adapt to option 1 after https://github.com/grafana/grafana/pull/84295 is merged.

Let's keep this open for the tests. I will rebase and adapt what @mckn added, and add a few more to ensure the use-cases I had in mind still work.

**Comment by darrenjaneczek** [comment]
In favor of the approach in:
- https://github.com/grafana/grafana/pull/84295

**Pull request closed without merging**
