### PR TITLE
Navigation: Updates to the docs for admin subsections

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- updates the docs to account for the new `navAdminSubsections` feature toggle we're about to enable

**Why do we need this feature?**

- so the docs are correct

**Who is this feature for?**

- everyone

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

i'm not sure when this should be delivered? i think we'll probably turn the feature toggle on in cloud tomorrow, but this won't be in an OSS release for a couple of months 🤔 

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by jdbaldry** [comment]
If this is going live in Cloud, I think it is important for the documentation to be up to date.

If the feature toggle is not likely to be enabled by default in the next release of Grafana, we might need to note that this UI change is behind a feature toggle.

**Comment by ashharrison90** [comment]
yep it'll be going live in cloud imminently, and enabled by default in the next release of Grafana 👍

**Comment by jdbaldry** [comment]
Ah in that case, it seems less concerning that we might need to have both sets of instructions coexist.

Phew!

I think you have it right to just merge to `main`. Grafana Cloud uses "next" documentation from Grafana which is the stuff that is in the `main` branch.When the next version branch is cut from `main`, this will be there.

**Review by jdbaldry — APPROVED** [review]
Patch looks consistent throughout but I haven't spun up the UI to check.

I can approve to unblock but let me know if you would like someone to step through those instructions for technical accuracy.

**Comment by ashharrison90** [comment]
@jdbaldry ah i see how my comment could be confusing... when i say it won't be in an OSS release for a couple of months, that's because the next minor release (10.3.0) won't be until the new year. so it will be in the next minor release, it's just that the next minor release is so far away 😄

**Pull request merged**
