### PR TITLE
A11y: Focus disappears when closing Time Picker menu on a dashboard

### LINKED ISSUE #56192: A11y: Focus disappears when closing Time Picker menu on a dashboard
**What happened**:
When closing the Time Picker on a dashboard with the Esc key, the focus disappears. The user does not know where their selection focus is now.

**What you expected to happen**:
Focus is kept on the Time Picker, as it was before it was open. The tooltip on the Time Picker can be closed as well.

**How to reproduce it (as minimally and precisely as possible)**:
Navigate to the Time Picker on a dashboard with Tab. Open it with Enter. Hit Escape to close it.

https://user-images.githubusercontent.com/13227501/193606818-ba8a8587-ad3a-4b6e-8676-8261411e8b22.mov

Press Shift+Tab now. The focus is on the on the Time Picker.

**Relevant WCAG Criteria**:
[2.4.7 Focus visible - Level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#focus-visible)

**Environment**:
- Grafana version: 9.3.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Restore Focus in TimePicker when press ESC key

**Which issue(s) this PR fixes**:

Fixes #56192

**Demo**
https://www.loom.com/share/ab3b98fcd7bf45eea0604e2bcef99bde

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ashharrison90** [comment]
as far as i remember we deliberately removed this because restoring focus causes the tooltip to appear, see https://github.com/grafana/grafana/pull/51836 cc @torkelo

**Comment by gitstart** [comment]
> as far as i remember we deliberately removed this because restoring focus causes the tooltip to appear, see #51836 cc @torkelo

Thank you for the review @ashharrison90.
So we have to find a way to restore the focus on TimePicker without using `restoreFocus` where when pressed Esc key focus returns to TimePicker but does not open the tooltip, right?

**Comment by torkelo** [comment]
Yes, the tooltip showing after closing it was super annoying

**Comment by polibb** [comment]
Hi @torkelo and @ashharrison90, thanks for reviewing this PR! I need to ask why is the tooltip annoying since it is showing only when the focus is on the time picker?

**Comment by torkelo** [comment]
@polibb it was showing after you closed the time picker

**Comment by torkelo** [comment]
or after you selected a value

**Comment by ashharrison90** [comment]
think this will need some more significant changes to `TimeRangePicker` to get the desired behaviour. we'll discuss internally and see if we can either implement a fix or describe the problem clearly so that a community member can pick up the ticket.

thanks for taking the time to raise this! 🙌

**Pull request closed without merging**
