### PR TITLE
Chore: Rewrite playlist sqlstore test from GoConvey to stdlib and testify

### PR DESCRIPTION
**Pull request by ceh**
**What this PR does / why we need it**:

Convert test from GoConvey to stdlib and testify.

**Special notes**:

Part of #22844.

### CODE REVIEW

**Comment by ceh** [comment]
What do you think @aknuds1, @papagian, et al?

**Comment by aknuds1** [comment]
Having a look.

**Review by aknuds1 — APPROVED** [review]
LGTM :+1:

**Comment by aknuds1** [comment]
Thanks, great work!

**Pull request merged**
