### PR TITLE
Auth: Guarantee consistency of signed SigV4 headers

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
Uses latest SigV4 changes from `grafana-aws-sdk`. See https://github.com/grafana/grafana-aws-sdk/pull/48

SigV4 config might be best placed under `[aws]` in the future to better discoverability...

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM, but needs an update of the [configuration documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#sigv4_auth_enabled) as well

**Comment by wbrowne** [comment]
Look okay to you @marefr? https://github.com/grafana/grafana/pull/45054/commits/866410397967d75640b98aadfe545ddc2977e7d5

**Comment by marefr** [comment]
@wbrowne Go go go :+1:

**Comment by marefr** [comment]
> Edit: might be better to say 8.3.6+?

Yeah probably

**Pull request merged**
