### PR TITLE
CSP: Allow all image sources by default (#34265)

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Backport #34265 to v8.0.x.

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]

**Comment by marefr** [comment]
Maybe we should backport this one to 7.5.x as well?

**Review by marefr — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
> Maybe we should backport this one to 7.5.x as well?

Wouldn't that be bad, since it's a functional change?

**Comment by marefr** [comment]
Maybe. Let's skip for now then and see if someone requests it

**Pull request merged**
