### PR TITLE
MySQL Datasource: Fix issue preventing CA cert from being added

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What is this feature?**

This makes it possible to add CA cert for mysql even when not using tls client auth. This bug was introduced with the angular migration

**Why do we need this feature?**

To be able to add a root certificate used for tls.

**Which issue(s) does this PR fix?**:

fixes: https://github.com/grafana/support-escalations/issues/4403

### CODE REVIEW

**Comment by mckn** [comment]
@oscarkilhed could this be related to the following issue?

https://github.com/grafana/grafana/issues/57556#issuecomment-1301555012

**Review by codeincarnate — COMMENTED** [review]
Tested out and looks good to me!

**Review by codeincarnate — APPROVED** [review]

**Comment by codeincarnate** [comment]
Does look like a spec file needs to be updated, and this seems changelog worthy 😄

**Comment by codeincarnate** [comment]
@mckn I'm thinking that's not related as this just had to do with the fields showing or not and there weren't any errors coming along with that. BI Squad can take a look at that one separately.

**Comment by kurianm** [comment]
@mckn When is this change expected to be rolled out? Since it is blocking us.

**Comment by oscarkilhed** [comment]
@kurianm This was released yesterday in 9.2.4

**Pull request merged**
