### PR TITLE
Variables: add graceful circular dependency failure

### PR DESCRIPTION
**Pull request by bradenhs**
**What this PR does / why we need it**:

Currently if a dashboard has circular dependencies in its variables configuration you are unable to load it. Instead you get stuck on this loading screen:

Screenshot 2022-03-15 105200

This behavior can be triggered with a setup as simple as this:

image

Admittedly the above case is unlikely but users of an internally used plugin where I work have encountered this issue with more complicated variable setups.

Unfortunately getting into this state isn't easy to recover from b/c the cancel loading button takes you back to the home screen. Ideally you'd still be able to load the dashboard with an error message then proceed to change the variables configuration. This PR enables this scenario. Now rather then getting stuck on the loading page this error message will display:

Screenshot 2022-03-15 105343

**Which issue(s) this PR fixes**:

Not a complete fix for it but this issue is related: https://github.com/grafana/grafana/issues/8583

Also, I attempted to write tests for this but the command `yarn test` hangs with no output. I can run the development server fine. Is there any special setup needed to make `yarn test` work? Is this something others have encountered recently? If not, I'll return to debugging why I don't seem to be able to get it to work on my machine.

### CODE REVIEW

**Comment by mitulmk** [comment]
@hugohaggmark @daniellee

**Review by ashharrison90 — APPROVED** [review]
i think this looks really nice 👍 

for tests, there should be no special magic tbh... can you share some information to see if we can help get you up and running:
- OS
- node version
- any output you see when running `yarn test`

you can try running just a specific file to see if running the whole suite is the problem, e.g. run `yarn test variables/state/actions.ts` instead and see if that helps?

**Review by axelavargas — COMMENTED** [review]
This looks fantastic @bradenhs 👏🏾, the code looks good to me, I gave it a spin and it works as expected.

As @ashharrison90 mentioned, please let us know if we can provide more support for you to create the tests.

***ps,*** it might be a good idea to merge with the latest `main` branch.
***ps2,***  I added this fix into version 8.5.0  because this code is using a [refactor](https://github.com/grafana/grafana/pull/44642) that will be released in that version

Thank you!

**Comment by ashharrison90** [comment]
@bradenhs we've actually just had someone in our team hit the same problem. we recently updated our version of yarn which is what's causing it (https://github.com/grafana/grafana/pull/45714). fix is to make sure you've upgraded your node version to at least node 16.14.0

hope that helps! 🙌

**Comment by bradenhs** [comment]
Thanks @ashharrison90! Got it working and added a test.

**Comment by ashharrison90** [comment]
looks great @bradenhs 🙌 

thanks for the contribution! 😄

**Pull request merged**
