### PR TITLE
NestedFolders: Add search to NestedFolderPicker

### PR DESCRIPTION
**Pull request by joshhunt**
Adds search into NestedFolderPicker

 - Search results are currently limited to 100 items until we get in pagination/lazy-loading in
 - Search result folders are expandable so you can view folders in them. Those children are not filtered by the search term

5589_2023-06-28-15-30_firefox

...this was surprisingly straight forward to do, so I'm not sure if i missed much?

### CODE REVIEW

**Review by ashharrison90 — CHANGES_REQUESTED** [review]
having now played around with it, i don't think we should allow expanding child folders when searching. think it should be a flat list. example of why: 

https://github.com/grafana/grafana/assets/20999846/6e57b8a0-dc49-48d5-a3a8-c5475f5c0177

**Comment by joshhunt** [comment]
lol. I think that's fair. more trouble than whatever questionable value comes from it.

**Comment by joshhunt** [comment]
Could you please give it another go now @ashharrison90 and let me know what you think?

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Pull request merged**
