### PR TITLE
Fix two ini-file typos regarding LDAP

### PR DESCRIPTION
**Pull request by peter-toft-greve**
Fixes 
* two simple typos in conf/sample.ini and conf/defaults.in regarding LDAP

### CODE REVIEW

**Comment by peter-toft-greve** [comment]
Take this whenever it fits the release cadence. I suggest that the maintainer merge this.

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Thanks, can you please sign the CLA? Otherwise we can't merge this.

**Comment by peter-toft-greve** [comment]
> Thanks, can you please sign the CLA? Otherwise we can't merge this.
@aknuds1 I have signed it 3-4 times.... Seems that it is not detected
image

**Comment by peter-toft-greve** [comment]
@aknuds1 My bad - I committed from my work email. Fixed now.

**Comment by peter-toft-greve** [comment]
@aknuds1 seems that all flags are ok now :)

**Comment by aknuds1** [comment]
Thanks for the fix!

**Pull request merged**
