### PR TITLE
typeahead support in datasource selection (with mixed datasource)

### PR DESCRIPTION
**Pull request by mtanda**
We have too many datasources. I want to support this.

Fixes, https://github.com/grafana/grafana/issues/7697 .

### CODE REVIEW

**Comment by bergquist** [comment]
I'm sorry but I don't see any type ahead support when building this PR. Maybe I'm missing something?

I guess you want to support the same type ahead support as template variables?

**Comment by bergquist** [comment]
I think this is a great idea. But I think we can improve the UX.

When I added a new query and want to add a second query the dropdown is empty.
I have to start typing again which is kinda confusion. 

I think `mixedDatasourceChanged` should reset back to the default value if a new query is added.

**Review by bergquist — CHANGES_REQUESTED** [review]
I think this is a great idea. But I think we can improve the UX.

When I added a new query and want to add a second query the dropdown is empty.
I have to start typing again which is kinda confusion.

I think mixedDatasourceChanged should reset back to the default value if a new query is added.

**Comment by mtanda** [comment]
Oops, okay...
I agree with that, this implementation is not so good.

Should I create feature request?

**Comment by bergquist** [comment]
@mtanda that would be awesome :)

**Comment by mtanda** [comment]
After checking metric segment code, I notice that, it is difficult to support the behavior.
> I think mixedDatasourceChanged should reset back to the default value if a new query is added.

To trigger input change, the segment value should not same as all datasource name.
https://github.com/grafana/grafana/blob/v4.1.2/public/app/core/directives/metric_segment.js#L38

If I set "default", I can't select "default".

**Comment by torkelo** [comment]
this looked great @mtanda :heart: merged!

**Comment by mtanda** [comment]
Thank you 😄

**Pull request merged**
