### PR TITLE
add export to csv in table panel

### PR DESCRIPTION
**Pull request by xadhoom**
This little addition allows to export the table panel to csv, whatever table is displayed.

### CODE REVIEW

**Comment by bergquist** [comment]
Great!

But since the export code for seriesToCsv is in kbn.js I think this should be solved in kbn as well.
Perhaps even move both of them into a export.js file. But its not a requirement.

As long as they are both in the same place I will accept this PR.

**Comment by xadhoom** [comment]
well, there's a reasoning behind that.
The export seriesToCsv in kbn.js is time series related, which is not suitable at all for tables.
This kind of export is very table specific, that's why I've placed it into the table controller.

If is ok to add a specific export function in kbn.js only for tables, I'll add it and update the pull request.

**Comment by bergquist** [comment]
A new method would be ok.
Something like exportTableDataToCsv .

**Comment by xadhoom** [comment]
PR updated.

**Pull request merged**
