### PR TITLE
SQLStore: Fix folder migration for MySQL < 5.7

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

Starting `9.4.0-beta` with MySQL `5.6` used to fail with:
```
logger=migrator t=2023-01-30T15:23:15.064448928Z level=debug msg="Executing sql migration" id="Add unique index for folder.title and folder.parent_uid" sql="CREATE UNIQUE INDEX `UQE_folder_title_parent_uid` ON `folder` (`title`,`parent_uid`);"
logger=sqlstore.metrics t=2023-01-30T15:23:15.064704862Z level=debug msg="query finished" status=error elapsedtime=211.198µs sql="CREATE UNIQUE INDEX `UQE_folder_title_parent_uid` ON `folder` (`title`,`parent_uid`);" error="Error 1071: Specified key was too long; max key length is 767 bytes"
```
This fixes the migration however, according to the [docs](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases), it seems that MySQL `5.6` is not supported, so I'm not sure whether we want to merge it or not.

Note also that [the entity migration](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/entity_store_mig.go) (that is behind a feature flag though) also fails for the same reason: in MySQL < 5.7 with encoding `utf8mb4`, varchar columns participating in an index should not exceed 191 length.

However, the above migration [runs during tests](https://github.com/grafana/grafana/blob/b4682fe3cbb37bf7efdaa3fe6645544782f36237/pkg/services/sqlstore/sqlstore.go#L501) ~therefore I have temporarily disabled it for the folder service tests in order to test this fix~

for testing the migration:
```
# make devenv sources=mysql_tests mysql_version=5.6
# GF_DATABASE_TYPE=mysql \
GF_DATABASE_HOST=127.0.0.1:3306 \
GF_DATABASE_USER=grafana \
GF_DATABASE_PASSWORD=password \
make run
```

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by zserge — APPROVED** [review]

**Review by ying-jeanne — APPROVED** [review]

**Comment by papagian** [comment]
I have removed the breaking changes notice about folders with longer titles than `189` characters (the new column size) because even before it was impossible to create a nested folder folder with longer title (during creation we insert a record both in the `folder` and `dashboard` table and the respective column in the `dashboard` is `189` so creation would fail)

**Comment by diwanshu97** [comment]
Will this change be released to 9.4.0-beta?

**Comment by papagian** [comment]
> Will this change be released to 9.4.0-beta?

`9.4.0-beta1` is already released but the fix is back-ported and it will be released in the next `9.4.0` release

**Comment by diwanshu97** [comment]
> 9.4.0-beta1 is already released but the fix is back-ported and it will be released in the next 9.4.0 release

Is the fix in place in the latest [9.4.0-beta1](https://hub.docker.com/r/grafana/grafana/tags?page=1&name=9.4) image? If not, what's the latest image version which has this fix?

**Comment by joepallotta39** [comment]
@papagian any chance we can get a new docker image for 9.4-beta1 that has the fix?

**Pull request merged**
