### PR TITLE
Chore: Split folder store and dashboard store interfaces

### PR DESCRIPTION
**Pull request by papagian**
**What is this feature?**

The FolderStore interface:
https://github.com/grafana/grafana/blob/872df59de5a93791cd6ccc4eab770055f987f9c6/pkg/services/dashboards/dashboard.go#L93-L100
used to be [inherited](https://github.com/grafana/grafana/blob/872df59de5a93791cd6ccc4eab770055f987f9c6/pkg/services/dashboards/dashboard.go#L87) by the dashboards Store interface.

This PR:
* splits the two interfaces
* explicitly passes the FolderStore as dependency to other services
* updates wire
* re-generates dashboards and folders mocks
* updates the tests appropriately

**Why do we need this feature?**

It reduces complexity since there is a separate folder service now.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by idafurjes — APPROVED** [review]
LGTM

**Review by joanlopez — COMMENTED** [review]
JOOC, Is there any plan to split interface implementation (dashboard store) as well? 
It feels a bit weird to pass the same instance twice here and there.

**Review by IevaVasiljeva — APPROVED** [review]
LGTM

**Review by joanlopez — APPROVED** [review]
LGTM!

**Pull request merged**
