### PR TITLE
InfluxDB: Refactor frame and field creation

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

The old logic wasn't covering edge cases like `SHOW TAG VALUES FROM custom_influxdb_cardinality WITH KEY = "database"`. This query was treated as a cardinality query.  I rewrite the logic with better checks. 

**Who is this feature for?**

InfluxDB users

### CODE REVIEW

**Comment by knollet** [comment]
Is this PR supposed to cover all corner cases?
Because it seems even with the new code you could throw off the parser by adding a comment like this

    SHOW TAG VALUES FROM somewhere WHERE some = 'query'  -- some alternative 'show field key cardinality' query doesn't work here
    
And it breaks again. It may be unlikely somebody stumbles over this, but comments having effects is extremely hard to debug, especially for users without insight into the code.

And I see this problem with all the `strings.Contains()`-Code.

Perhaps the alternative is to document that grafana needs some "magic comments" to tell it what kind of query something is, instead of guessing what it could be by not really parsing influxql correctly... idk.

**Comment by itsmylife** [comment]
@knollet You are right. The comments can break this easily, so I'll try to come up with a better code. Thanks for pointing it out. There shouldn't be any `contains` code. Let's see if I can do this without magic.

**Comment by knollet** [comment]
Ah, I believe this is way better.

**Review by aangelisc — APPROVED** [review]
Nice work on this @itsmylife, this is a much improved method!

**Pull request merged**
