### PR TITLE
Tests: removes unused stuff and replaces monaco transpile with mock

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Cleans up some unused files and dependencies. Also changes so we don't transpile Monaco but use mock instead. Not an enormous impact at all, but at least not slower.

**Before**
| yarn jest --watch-all        | yarn jest public/app/features/variables/constant/reducer.test.ts |
| ----------------------------:| ----------------------------------------------------------------:|
| 101.4                        | 7.394                                                            |
| 107.77                       | 5.427                                                            |
| 119.155                      | 6.269                                                            |
| 100.921                      | 5.263                                                            |
| 122.251                      | 5.225                                                            |
| 106.902                      | 5.271                                                            |
| 101.059                      | 5.257                                                            |
| 94.759                       | 5.189                                                            |
| 105.001                      | 5.391                                                            |
| 117.772                      | 5.329                                                            |
| Average: 107.699 | Average: 5.6015                                                               

**After**
| yarn jest --watch-all        | yarn jest public/app/features/variables/constant/reducer.test.ts |
| ----------------------------:| ----------------------------------------------------------------:|
| 109.269                      | 5.612                                                            |
| 110.051                      | 5.244                                                            |
| 109.868                      | 5.252                                                            |
| 102.779                      | 5.227                                                            |
| 105.819                      | 5.337                                                            |
| 106.081                      | 5.311                                                            |
| 94.403                       | 5.714                                                            |
| 100.575                      | 5.259                                                            |
| 101.443                      | 5.22                                                             |
| 102.194                      | 5.26                                                             |
| Average: 104.2482 | Average: 5.3436                                                              

**Some random drone builds before** 
image
image
image
image
image

**This PRs drone build**
image
image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hugohaggmark** [comment]
@ivanahuckova I remove some `react-unicons` transpile in this PR and the tests seem to work without it. If you have any input on this change, I'd appreciate it 🙏

**Review by mckn — APPROVED** [review]
Seems to work as a charm! Great job @hugohaggmark!

Not sure about the `@iconscout/react-unicons` package so I guess it would be nice to get a second approval regarding that one.

**Comment by hugohaggmark** [comment]
> Seems to work as a charm! Great job @hugohaggmark!
> 
> Not sure about the `@iconscout/react-unicons` package so I guess it would be nice to get a second approval regarding that one.

I think it's fine as the tests are green, but @ivanahuckova can double check when she's back from vacation.

**Comment by ivanahuckova** [comment]
> @ivanahuckova I remove some react-unicons transpile in this PR and the tests seem to work without it. If you have any input on this change, I'd appreciate it 🙏

Awesome! Unicons added support for CommonJS after we started to use them. So initially, we needed a workaround. Thanks for removing this now unnecessary code. 🙂

**Pull request merged**
