### PR TITLE
Add MSSQL sqlstore

### LINKED ISSUE #8674: [Feature request] MS SQL Server as DB (not datasource)
We're using Grafana 4.3.2 with our own custom datasource on Windows 2012. 

Currently we're using MySQL or SQLLite as the Grafana database (not as a datasource) but because we're predominately the windows stack we'd like to be able to use MS SQL Server instead of MySQL for high availability configurations. 

I'd imagine [SQL Server Express](https://www.microsoft.com/en-us/sql-server/sql-server-editions-express) would be good enough as this allows for a 10GB database and it's available for free.

### PR DESCRIPTION
**Pull request by captncraig**
Fixes #8674 

Adds mssql dialect to the migrator, and allows you to store dashboards and other grafana data in microsoft sql server.

Tested on Azure SQL, and on SQL server 2012R2. All migrations succeed, and what I've done in the ui so far has worked. Not sure how to test it more extensively.

### CODE REVIEW

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana. Adding support for yet another database for storing dashboards is quite an undertaking, considering maintenance and development. 

We will get to this PR eventually but please be patient.

**Comment by MarcoJ-CID** [comment]
Any updates about the possibility to merge this PR?

**Comment by camunoz7** [comment]
hi, I am waiting for this PR, when is possible to have this characteristic?

**Comment by R-i-c-h-B** [comment]
Morning all.... any update on what sounds like a marvelous advance for mankind?

**Comment by torkelo** [comment]
Echo what @bergquist said that we appreciate wanting to contribute. Talking on another backend DB is a big maintenance burden and we are already spread so thin supporting mysql & postgres & sqlite (with CI automation for all) as well as all the data source plugins. 

So at this stage with generally quite low demand for MSSQL as a config store we wish to hold off on merging this. We will likely revisit this decision later this year or next year.

**Comment by yamac-kurtulus** [comment]
Did you have a chance to revisit this idea, now that it's been about a year?

**Comment by aviadbi1** [comment]
Hi, is there any progress with the PR? 
Have you guys revisit that request?

**Comment by qiuylin** [comment]
We also have same requirements to add mssql sqlstore support on Grafana. I had implemented this feature in my private branch before I realized the community actually discussed the requirement here. 
I would like to contribute this change to the community if it helps. It is totally understandably that adding another DB is a big maintenance burden for the community. Based on my experience, due to the specific grammar of MSSQL, the order of the migration statements needs to be more carefully. But I think it might be worthy to push this feature since the MSSQL is wider used on Windows, Linux and Azure platforms. If you agree that, I would like to work with @bergquist, @captncraig or others member, to improve this change and test the change more extensively.

**Comment by NathanaelHuber** [comment]
Hi there, any update?

**Comment by MeikelLP** [comment]
@torkelo Hey,
we are a very Microsoft influenced company and use Microsoft SQL Server in our company only. Did the plans to officially support another database provider change since 2019?

If no, are there any do add it as a community-supported provider (maybe call it 'experimental'?).

**Pull request closed without merging**
