### PR TITLE
SQLStore: Add support of MS SQL Server as backend database

### PR DESCRIPTION
**Pull request by Stuv7CB**
**What this PR does / why we need it**:
This PR adds support of MS SQL Server as backend alongside with mysql, postgres and sqlite3.
It will add ability to use grafana in environments with MSSQL database.

Originally idea of adding support of new backend raises because on my workplace IT department doesn't support hosting MySQL or Postgres and we have choice to either use MSSQL or host MySQL on our own in case we want to support high availability for our instance of grafana.
I hope that this issue is not specific only for my workplace and people with similar issues would use new backend.

Original discussion: #51671
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

I have tested work of this backend with SQL Server 2019, but it should work with SQL Server 2014+

### CODE REVIEW

**Comment by sakjur** [comment]
:eyes: It’ll take a bit of time to figure out what to do with this. I think what Carl said in #12204 is still true:
 
> Adding support for yet another database for storing dashboards is quite an undertaking, considering maintenance and development.
 
We are interested in adding support for more databases now, but we haven’t landed in which ones or what level of support to provide for them. We're leaning toward a number of databases that would drastically change the available storage options for Grafana users rather than being an incremental addition of more SQL stores. That said, if we would want to support another SQL store, I _think_ MSSQL would be high up on the list due to how widespread it is and the similarity of its testing story with that of Postgres and MySQL since MSSQL supports being hosted in Docker.
 
That said, since #8674 was created asking for this five years ago, the general interest for MSSQL support has been relatively low. We have to ensure that high maintenance comes with equally high value.
 
Anyway, thank you for this contribution. It’s clear that you’ve put quite a bit of time and effort into making this happen, and I’m very impressed by the quality of the PR in general. _If_ we want to support MSSQL, I think this is how we’d want to do it. Now it’s on us to figure out that _if_ 😛 Because of vacations and whatnot, that'll probably take about a week.

To be clear: Even in case we decide to support MSSQL (which is more unlikely than not), it’d probably be a multi-stage introduction so that we can test it out for an extended period of time without officially supporting it. That’d require some rewriting of this PR. Some of the teams I removed the request for review from would need to chime in. I’d probably give you a bunch of patches to make sure that we can merge this as soon as possible, but the steps from there to full support would take some time.
 
Related:
* #8674
* #12204

**Comment by Stuv7CB** [comment]
Not stale :) 
> Because of vacations and whatnot, that'll probably take about a week.

Yeah, summer is a vacation time, I  didn't merge updates from main branch for same reason

**Comment by Stuv7CB** [comment]
Not stale

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/issues/8674#issuecomment-1410780088

**Pull request closed without merging**
