### PR TITLE
BarChart: fix constant re-init due to legend prop strict inequality

### PR DESCRIPTION
**Pull request by leeoniya**
this fixes a performance regression introduced by https://github.com/grafana/grafana/pull/40226 which added `'legend'` to `propsToDiff`, which by default uses shallow comparison to determine if the viz should be re-initialized.

the fix is to use an fn-style signature and do a deep compare of `legend` objects...or alternatively stop re-creating `legend` to make the shallow compare sufficient.

@zoltanbedi @dprokop plz make sure this doesnt break the features introduced in your prior PR :pray: . also would be good to understand why adding `'legend'` to `propsToDiff` only affected BarChart re-init, but not TimeSeries re-init, since they look basically the same. are we doing something different for the barchart legend that re-creates its config on every re-render, while the TimeSeries legend config is referentially stable?

### CODE REVIEW

**Comment by leeoniya** [comment]
this might be the culprit for legend opts not being shallow-equal in BarChart:

https://github.com/grafana/grafana/blob/8be4182e49ae85d4cbb92ae60632e29a8407cf36/public/app/plugins/panel/barchart/BarChart.tsx#L94-L95

@ryantxu do we still need this?

**Comment by leeoniya** [comment]
ok, so it looks like `cloneDeep()` was in fact the issue here. this was added in the the value sizing PR (https://github.com/grafana/grafana/pull/34229). however, value sizing went through a large refactoring since then and now appears to work properly without the clone when changing options, resizing the panel, and updating the data using the attached dashboard. updated the fix to simply remove the clone.

<details><summary>dynamic-barchart-data.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMin": 0,
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "orientation": "auto",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "pluginVersion": "8.4.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 5
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "reduce",
          "options": {
            "reducers": [
              "max",
              "min",
              "first",
              "mean"
            ]
          }
        }
      ],
      "type": "barchart"
    }
  ],
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "version": 0,
  "weekStart": ""
}
```
</details>

**Review by ryantxu — APPROVED** [review]

**Comment by zoltanbedi** [comment]
Took this for a spin and the legend ordering is still working as expected.

**Comment by leeoniya** [comment]
The legend ordering may have regressed in a subtle way: it no longer re-orders the series when new data causes the legend to re-order based on new calcs, like min/max/avg. i don't know if this was ever intended behavior, and it might be odd because it also affects stacking order which i would expect to stay stable across data updates, and would find it rather suprising if my bars reordered on every 5s due to the legend being sorted by some calculation.

if we need to have the legend sorting affect the viz display then perhaps we should add something similar to `onSeriesColorChange`  to the PanelContext which can re-init the viz when legend calcs/sorting changed, such as:

```js
  /**
   * Called when order of series changes due to data updates and legend re-calcs
   * this can affect stacking order and/or bar render order in BarChart
   * which in turn may require a viz invalidation & re-init
   *
   * @alpha -- experimental
   */
  onSeriesOrderChange?: () => void;
```

i'm not sure what we want to do here, but i think it's a bit strange to control the stacking order or barchart bar order based on dynamically computed things in the legend which can fluctuate between updates. bar race charts are a thing, but i'm not certain that's what we're going for here: https://app.flourish.studio/@flourish/bar-chart-race

**Comment by dprokop** [comment]
> i'm not sure what we want to do here, but i think it's a bit strange to control the stacking order or barchart bar order based on dynamically computed things in the legend which can fluctuate between updates.

IMO we can re-draw the chart when the user interacts with the legend, rather than each data update. I also doubt this is a useful thing to reorder bars when the calc changes. 

Another thing is whether or not this is an actual problem. I can see your point with 5s dashboard refresh etc, but we don't know if this is even a use case for this panel. 

Thankfully Barchart is still marked as a beta so introducing this behavior change should be ok as long as we add info that we are changing it :)

**Pull request merged**
