### PR TITLE
Alerting: Fix state manager to not keep datasource_uid and ref_id labels in state after Error

### LINKED ISSUE #71467: Alerting does not remove datasource_uid from the state label after Error
### 
# What went wrong?

**What happened**:

Evaluation of an alert rule with classic condition (because the single result does not provide any labels) that results in an error creates labels `datasource_uid` and `ref_id` that never go away, even after normal evaluation.

**What did you expect to happen**:

 - the labels are removed as soon as the evaluation is normal.

### 
# How do we reproduce it?

**Step 1**:

- Create a classic condition rule that for example queries a data source that can be stopped. For example, a Prometheus data source. Wait until the first evaluation happens and the state is created.

**Step 2**:

- Stop the data source or cause an error. Wait until the evaluation happens and the state will get two more labels: `datasource_uid` and `ref_id`

**Step 3**:

- Start data source or restore the connection to it. Wait until the next evaluation and observe that the labels are not gone.

### 
# What Grafana version are you using?

9.5.5 and observed in the master branch as well

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

This happens because those labels are added after the state hash is calculated and in the case of classic condition the state hash is a metric of rule's labels. Therefore, in the case of error, the only state is matched with the error result and the labels are added. When things get back to normal the result is matched to the current state that contains the extra labels and the state is reused.

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**
This PR fixes a bug in the state manager that is described in https://github.com/grafana/grafana/issues/71467. It updates the state manager to clean up the labels sneaked after the cacheID was calculated. I added safety to remove only if the result does not contain these labels.

This is a temporary change to remediate the problem and will be changed in https://github.com/grafana/grafana/pull/68142

<details><summary>Before</summary>

https://github.com/grafana/grafana/assets/25988953/587410ac-f1e1-4bd9-8312-24428326ad6b

</details>

<details><summary>After</summary>

https://github.com/grafana/grafana/assets/25988953/b20212e4-3994-4f05-857d-af15139fa6cc

</details>

**Why do we need this feature?**
This happens only in the case when the result does not have any labels, usually when the rule uses the classic condition. The normal evaluation uses labels from the rule only. When an error happens, the error result does not have labels either, and therefore it is matched to the normal state instead of being a new state (in multi-dimensional alerts when each normal result contains labels). The state manager adds extra labels __after the state identifier is calculated__. Therefore, this makes the normal result match the state that contains the extra labels, and therefore the extra labels (datasource_uid and ref_id) never go away from the state.

**Who is this feature for?**
Those who use classic condition and execution of Error as an error.

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/71467

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by grobinson-grafana — DISMISSED** [review]

**Comment by grobinson-grafana** [comment]
Just before I approve this quick fix, what is needed to get https://github.com/grafana/grafana/pull/68142 finished?

**Comment by yuri-tceretian** [comment]
> Just before I approve this quick fix, what is needed to get https://github.com/grafana/grafana/pull/68142 finished?

- rewrite or add new tests for ProcessEvalResults
- add feature flag

**Review by JacobsonMT — APPROVED** [review]
LGTM :rocket:

It's not clear to me how [68142](https://github.com/grafana/grafana/pull/68142) will inherently fix this though, unless you mean you will take this case into account when working there.

**Comment by yuri-tceretian** [comment]
> It's not clear to me how https://github.com/grafana/grafana/pull/68142 will inherently fix this though

I would like to move the population of these labels to the `eval` package and make it the responsibility of the evaluator instead of the state manager. Initially, I went that way (see [commit](https://github.com/grafana/grafana/commit/fcfca7df46cb3660103a452563e472c14c4dc8c3) to another branch) but this caused a side-effect in the case of execution of Error as Alerting: it started to behave the same way it behaves in the case of multi-dimensional alerting, i.e created a new alert instance instead of reusing existing, which I want to fix in https://github.com/grafana/grafana/pull/68142. So, I decided to patch the bug and then revisit it in the follow-up PR when we change the behavior of mapping of an Error to Alerting state.

**Review by grobinson-grafana — APPROVED** [review]
LGTM

**Pull request merged**
