### PR TITLE
Docs: Update stat-panel.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Fix alias links

### CODE REVIEW

**Comment by oddlittlebird** [comment]
@robbymilo , I applied your fix. What is up?

**Comment by robbymilo** [comment]
@oddlittlebird Looks good. Once this is merged and synced the previews should be fixed.

**Comment by oddlittlebird** [comment]
@robbymilo , I can't merge it due to the end to end test failing.

**Comment by robbymilo** [comment]
@oddlittlebird Rerunning the checks looks like it made it work.

**Comment by oddlittlebird** [comment]
Cool. Could you approve it, please?

**Review by robbymilo — APPROVED** [review]

**Pull request merged**
