### PR TITLE
Fixes typos

### PR DESCRIPTION
**Pull request by dugalp**
**What is this feature?**

Updates documentation to reflect correct English usage according to Microsoft and Google style guides for the word **on-premise** and replaces with correct usage in Grafana documentation. I have signed the CLA.

**Why do we need this feature?**

Improves proficient use of English.

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

#64480

### Microsoft Style Guide
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/cloud-computing-terms

**on-premises, off-premises**
Hyphenate in all positions.

Premises is plural. Don't use on-premise, off-premise.

Don't use _on-premises cloud_ or _off-premises cloud_.

### Google Style Guide
https://developers.google.com/style/word-list

**on-premises**; not _on prem_ or _on premise_ or _on-premise_

Use to refer to a customer's resources that they manage in their own facilities. Don't use peer. Hyphenate when used as any part of speech. It can be acceptable to use on-premises as a noun when it would be awkward to repeatedly write out a full phrase like an on-premises environment. However, it's preferable to use the more complete phrase whenever possible.

**Recommended**: An _on-premises_ database
**Recommended**: The database runs _on-premises_
**OK**: Moving data from _on-premises_ to Google Cloud

### CODE REVIEW

**Comment by dugalp** [comment]
I have signed the CLA, yet the CLA check is saying it's not done. When I click on the Details link next to license/cla check, it is showing as completed.

**Review by Eve832 — APPROVED** [review]

**Review by GrafanaWriter — APPROVED** [review]

**Comment by dugalp** [comment]
I'm unsure how to progress this PR. 

The following checks are not yet successful and appear to be required

- `Milestone Check` - Milestone not set
- `license/cla`  - Pending

Can anyone provide any guidance on the above, to progress this PR?

Thanks in advance,

-Patrick

**Comment by jdbaldry** [comment]
Occasionally the CLA assistant can get stuck when under heavy load. I have triggered the job again by making a GET request to https://cla-assistant.io/check/grafana/grafana?pullRequest=64367. 

@Eve832 Any member of the Grafana org (possibly anyone) should be able to make a similar request in the future if required. Of course, the `pullRequest` parameter value will need to be updated to match the PR number.

**Comment by jdbaldry** [comment]
@dugalp The CLA assistant is still insisting that you have not signed the CLA.

Have you performed actions requested by the assistant in its comment? Specifically about configuring the email address on your GitHub account.

> [CLA assistant check](https://cla-assistant.io/grafana/grafana?pullRequest=64367) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=64367) before we can accept your contribution.
> 
> **Patrick Dugal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=64367) it.

**Review by Eve832 — APPROVED** [review]

**Comment by dugalp** [comment]
> @dugalp The CLA assistant is still insisting that you have not signed the CLA.
> 
> Have you performed actions requested by the assistant in its comment? Specifically about configuring the email address on your GitHub account.
> 
> > [CLA assistant check](https://cla-assistant.io/grafana/grafana?pullRequest=64367) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=64367) before we can accept your contribution.
> > **Patrick Dugal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=64367) it.

I have an email address on my profile but it is private and don’t wish to expose it publicly.

“Keep my email addresses private” is selected, so that I can prevent receiving spam.

**Comment by jdbaldry** [comment]
Do you have the correct email in your profile?

You can check the email used for this commit with:

```console
$ git show --no-patch --pretty=format:%ae 56243f21063eb0127c5e322adfb7751dc044519f
```

**Pull request closed without merging**
