### PR TITLE
Chore: update `react-inlinesvg` and use new icon caching mechanism

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- updates `react-inlinesvg` to new version
- changes icon caching behaviour:
  - before it would load and cache all icons up front
  - now it incrementally adds icons to the cache as they're loaded
  - this cache persists indefinitely in the browser _unless the version of grafana changes_ (since it's parameterised by the commit hash)
  - if the commit hash changes, we start a new cache and clear any old ones
- have also added a fallback empty div whilst the icon is loading to prevent layout shift
- massive thanks to @jackw for testing this still works with a plugin bundling grafana-ui 🙇 

**Why do we need this feature?**

- can utilise better caching mechanism provided by the library

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by eledobleefe — APPROVED** [review]
Checked the behaviour on the ephemeral instance and it works as expected (icons loaded on demand and added to cache the same way) so LGTM

**Comment by tomratcliffe** [comment]
(are the additional changes unintended? The go files etc)

**Comment by ashharrison90** [comment]
> (are the additional changes unintended? The go files etc)

yeah the go files are just linting changes that happened when i merged and committed main

i could undo them, but i suspect anyone who edits + commits in those files will have the same changes so might as well just commit them now 🤷

**Review by gillesdemey — APPROVED** [review]
Tested on my local instance and it also worked just fine, no FOUCs :)

**Review by jackw — COMMENTED** [review]
LGTM! 🚀

**Review by jackw — APPROVED** [review]

**Pull request merged**
