### PR TITLE
Dashboard: Revert LayoutItemContext

### PR DESCRIPTION
**Pull request by leeoniya**
we've switched to using global portals in https://github.com/grafana/grafana/pull/81986, so this is no longer needed.

originally introduced in https://github.com/grafana/grafana/pull/80116

### CODE REVIEW

**Review by baldm0mma — APPROVED** [review]
Looks like there **_were/are_** some breaking changes check issues in drone? But other than that, this works as expected in all tested panel types.

**Review by codeincarnate — APPROVED** [review]
Looks good 👍

**Review by mckn — COMMENTED** [review]
LGTM! I like that we are removing things and making the API surface smaller 🙌🏻 

I noticed that we use this in scenes. What it the replacement for LayoutItemContext? Do we have any or are they left on their own to figure this out? I guess that applies to potential external plugins as well.

**Review by torkelo — APPROVED** [review]

**Comment by dprokop** [comment]
@leeoniya this requires some kind of revert of https://github.com/grafana/scenes/pull/530 as well, do you mind picking this up?

**Comment by leeoniya** [comment]
that pr has more changes in it that im not familiar with. was hoping you peep could pick it up: https://github.com/grafana/scenes/issues/622

**Pull request merged**
