### PR TITLE
add `wechat work` notifier and test

### PR DESCRIPTION
**Pull request by lumincui**
Usage:

    add alert and select `wechat work` notifier, type webhook url.
    you can use msgtype and template as default,
    or edit template if you need.

May this PR help you :)

### CODE REVIEW

**Comment by vincenthcui** [comment]
#12333 is related

**Comment by marefr** [comment]
@vincenthcui is wechat and wechat work two different things?

**Comment by bergquist** [comment]
Hi @vincenthcui thank you for taking the time to contribute to Grafana! But we are currently not merging new alert notifiers unless they have proven very popular. We already have more notifiers than we can maintain. So this has to wait until we support alert notifiers as backend plugins. In the meantime, I suggest you write a custom web server that integrates Grafanas alert notification webhooks with Wechat.

**Comment by vincenthcui** [comment]
@marefr yes, they are different things. You can think of WeChat Work as WeChat for business. WeChat is IM tool for personal relationship, so there is no open API to send notifications (there may be, but it is regarded as 'illegal'). WeChat Work is different which is designed for working scene, so we can easily use open API to send notifications, and use group bot to send machine alerts to a group of people.

**Pull request closed without merging**
