### PR TITLE
Chore: Bumps prettier version for new typescript syntax support

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Upgrades to the latest version of Prettier which adds support for the latest version of typescript that we recently upgraded to.

### CODE REVIEW

**Review by Estrax — APPROVED** [review]
LGTM.

**Comment by torkelo** [comment]
Looks like updated prettier will update a few files :) wonder how it will change formatting

**Comment by kaydelaney** [comment]
Oops, forgot to re-run prettier to update the formatting based on the new rules

**Comment by dprokop** [comment]
@kaydelaney can we bump prettier version in grafana-toolkit a well? Maybe as a separate PR.

**Pull request merged**
