### PR TITLE
Dashboard: Toggle for alert threshold display in panels

### LINKED ISSUE #7258: [Feature request] Make alert threshold visibility in graphs optional
Hey 👋 

For my use-cases I don't really need to see the thresholds of an alert in my graphs and they're pretty stark visually (red and the whole alertable area is tinted as well). That's why I was thinking that perhaps it would make sense to make it optional. 

Maybe a checkbox "Show alert thresholds" in "Alert Config"? Or does "Display > Thresholds" make more sense for this?

### PR DESCRIPTION
**Pull request by bashgeek**
**What this PR does / why we need it**:
As you can see in the related issue, it often happens that the displayed alert thresholds make no sense - especially in graphs showing multiple datasets. It often looks like the whole graph is in alert mode, while it simply shows a one threshold of many.

This implements a simple toggle function for each panel (analog to the "toggle legend" functionality), which simply doesn't include the thresholds in the rendering.

Simple change, but a huge help for many of us.

**Which issue(s) this PR fixes**:

Fixes #7258 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bashgeek** [comment]
How nice, little bot! Still waiting on someone from the project to review.

**Comment by torkelo** [comment]
We are planning to make alert rules standalone and separate from the graph panel / dashboard definition (hopefully later this year). So not sure we want to introduce more options like this to the current model.

**Comment by bashgeek** [comment]
Well, but it's certainly a quick and easy fix for an, in my opinion, pretty severe visual bug, that a lot of users reported for more than 3 years now (see linked issue) and probably existed before that.

I can certainly understand that if a system overhaul is planed that touching this again now makes no sense, but your timeline sounds pretty vague and we might end up adding 1-2 more years onto an issue that effects quite a few of us :-)

However, will be accepting with either decision, I'll simply run a patched version for me and our clients, but having it in the upstream codebase would certainly be easier ;-)

**Comment by stingalleman** [comment]
I agree with @bashgeek - this is a really severe visual bug, and it's really annoying and polluting otherwise beautiful graphs. We've been waiting a really long time for this and a quick fix would really be appreciated.



@torkelo

**Review by stingalleman — APPROVED** [review]

**Comment by torkelo** [comment]
Not sure this implementation is correct, better to allow the graph to remove the thresholds after the alert UI added them

**Comment by bashgeek** [comment]
Still nothing stale in here

**Pull request closed without merging**
