### PR TITLE
Transformations: Fix Select menu position issue

### LINKED ISSUE #24107: EditPanel: Transformations dropdown goes up and under tab
**What happened**:

When adding transformations with insufficient vertical space below the **+ Add transformations** button (forcing the options to be displayed above the button) some options disappears behind the tabs in the tab bar.

Screen Shot 2020-04-29 at 15 18 13

**What you expected to happen**:

The dropdown is rendered above the tab bar/panel and all options are visible + selectable.

**How to reproduce it (as minimally and precisely as possible)**:

For any panel, have a small-ish vertical space for the transform tab in the edit panel view and try to add more transformations until the dropdown changes from being below the **+ Add transformations** button to being above it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master @ 2e4a8d4d5a0cc28dfaaf38a3ec37e5a6f9ea3929 (2020-04-30T14:18Z)
- Data source type & version: any 
- OS Grafana is installed on: MacOS 10.15
- User OS & Browser: Safari 13.1 and Chrome 81
- Grafana plugins: -
- Others: -

### PR DESCRIPTION
**Pull request by tskarhed**
I will investigate this further, but the current fix is removing the custom scrollbar. If nothing else comes up, I'd suggest we go with that.

Fixes #24107
Screenshot from 2020-05-11 12-17-23

### CODE REVIEW

**Comment by dprokop** [comment]
@tskarhed think the problem might be on Windows/Edge or when user has visible scrollbars enabled. Can you check how this looks in such scenario?

**Comment by tskarhed** [comment]
@dprokop What problem are you refering to? The screenshot is Ubuntu/Chrome

**Comment by dprokop** [comment]
@tskarhed I'm taking about this for instance (macOS, system scrollbars visible enabled, Firefox)
image


I wonder how it looks on Windows by default

**Comment by torkelo** [comment]
Can't we make the dropdown go down instead?

**Comment by tskarhed** [comment]
> Can't we make the dropdown go down instead?


@torkelo Then we have the same issue in the opposite direction.
Screenshot from 2020-05-11 15-48-24


> @tskarhed I'm taking about this for instance (macOS, system scrollbars visible enabled, Firefox)
> image
> 
> I wonder how it looks on Windows by default

That's a bit unfortunate :slightly_frowning_face:

**Comment by dprokop** [comment]
@tskarhed closing in favour of https://github.com/grafana/grafana/pull/24615

**Pull request closed without merging**
