### PR TITLE
DashboardSettings: Migrates history diff view from angular to react

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
This PR is a first pass at migrating the Dashboard Settings History Diff View from Angular to React. The Angular version was a bit tricky as most of the HTML was sent via the backend `compare-diff` endpoint. This PR also removes the dependency on `compare-diff` endpoint and does the diffing entirely in the frontend. Right now It lacks function parity with master as it's missing the buttons to navigate to specific lines.

| After | Before |
| --- | --- |
| Screenshot 2021-03-15 at 15 47 17 | Screenshot 2021-03-15 at 15 22 05 |

**Which issue(s) this PR fixes**:

Related Epic #21484

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dprokop** [comment]
>  Right now It lacks function parity with master as it's missing the buttons to navigate to specific lines.

@jackw I don't think there is anything missing about this, as it wasn't working anyways :D

**Review by torkelo — APPROVED** [review]
This is looking great! 

Would love to get a diff view into the "You have unsaved changes" modal (in the future). When the version history feature was built (By external contributor). I was very frustrated that the diff was done in the backend and done in a way that it was impossible to do a diff for a dashboard you had yet to save, I started refactoring the version history backend implementation to take in json from the frontend to support diffing unsaved changes but never completed that (was years ago). 

So AWESOME that you moved the diffing to the frontend!!!!  :heart:

**Review by dprokop — APPROVED** [review]
Works awesome @jackw. Testes it and haven't found any issues. Totally agree with @torkelo about moving the diff to FE, I think this is a very good step.

**Review by mckn — APPROVED** [review]
I think this looks great and working like a charm! Awesome work on this @jackw.

Wohoo

**Pull request merged**
