### PR TITLE
Chore: Prevent branches beginning with "v*" from being considered as versioned branches

### LINKED ISSUE #35547: Build: seems like branches started with `v` will be treated as a release branch by drone.
**What happened**:
Comparing these tow PR:s I get different build pipelines in drone. Feels like we need to make sure that the release branches matches the version tag rather than just start with an `v`.

https://github.com/grafana/grafana/pull/35248 <-- running release pipeline (branch named: view-alert-rule-page)
https://github.com/grafana/grafana/pull/35546 <-- running test pipline (branch named:  mkcn/view-alert-rule-page)

**What you expected to happen**:
I was expecting the test-pr pipeline to run for my PR.

**How to reproduce it (as minimally and precisely as possible)**:
Open a PR based off a branch starting with `v`.

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Due to lack of regular expressions package in `go-starlark`, we are considering every branch that starts with `v` as versioned branch, which is wrong. It also triggers the build twice, once as a regular `test-pr` and once as a release branch. We only care about `vX.X.X` format, where X is a digit. There is an open PR to add `regex` package in `go-starlark` --> https://github.com/google/starlark-go/pull/369. We can start using it and after the aforementioned PR is merged.

**Which issue(s) this PR fixes**:

Fixes #35547

**Special notes**:

This is safe for v8 (`v8.x.x`) and v9 (`v9.x.x`) branches.

### CODE REVIEW

**Review by zserge — APPROVED** [review]
Assuming that the glob approach works, I approve it. Otherwise I would suggest including all ten digits to the list, so that Grafana 10 wouldn't be a surprise to those who would release it.

**Comment by dsotirakis** [comment]
@zserge it should, according to https://docs.drone.io/pipeline/docker/syntax/trigger/

> You can use wildcard matching in your triggers. Note that triggers use glob pattern matching, not regular expressions.

🤞

**Comment by aknuds1** [comment]
Actually the lack of regular expressions is not in Starlark, but in the Drone server's evaluation of [trigger expressions](https://docs.drone.io/pipeline/docker/syntax/trigger/).

As such, in order to be able to use regular expressions, you have to implement the support in the Grafana Drone Extension. My [PR](https://github.com/grafana/grafana-drone-extension/pull/24) was an attempt to do so, but got rejected by the platform team due to backwards compatibility concerns.

**Comment by dsotirakis** [comment]
Yeah let's hope after the `go-starlark` PR is merged there will be some work on the Drone side too - maybe we can raise something on their end

**Comment by aknuds1** [comment]
I don't understand how `go-starlark` will affect the Drone server. It's a design choice by Drone to use glob patterns for trigger expressions, it's not for the lack of regexp technical capability.

**Comment by aknuds1** [comment]
Starlark is, unless I'm missing something, not relevant to the Drone server at all. It's just one of several languages supported by the extension to convert into YAML.

**Comment by dsotirakis** [comment]
No it isn't relevant, what I was thinking was (maybe) a simpler implementation of your PR if regex is merged but didn't give it more thought, since we are covered for now with the current implementation. We can always discuss.

**Pull request merged**
