### PR TITLE
Logs: Only display prettify json toggle if logs are json

### LINKED ISSUE #62872: Logs: Hide "prettify json" option when there is no JSON in display
## Problem

`Prettify JSON` is display in the UI even when there's no JSON in the logs. When no JSON logs are displayed, toggling it on and off has no effect. 

![imagen](https://user-images.githubusercontent.com/1069378/205034050-e0c137c4-5848-495c-

We think we could be smarter and simplify the UI according to the results in display, preventing options with no visible effect to being displayed.

## Solution

Only show the option when JSON logs are in display.

### PR DESCRIPTION
**Pull request by itsgareth**
**What is this feature?**
currently the `Prettify JSON` toggle is always displayed. this pr changes that so it is only displayed if the logs are in json format.

**Why do we need this feature?**
...

**Who is this feature for?**
...

**Which issue(s) does this PR fix?**:
Fixes #62872

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by svennergr** [comment]
I am not sure if we really should just remove the toggle if no present line is in JSON format. E.g. I planned to use those options to also be used in the LogContext. I.e. there might not be a log line in JSON in the results of the displayed logs at first, but there might be JSON formatted lines in the results of the context queries.

What would make sense though - and I realise this is a larger task - is to unify/improve log display options in Explore, e.g. by putting them in a collapsible container, where space is not really a problem and descriptions could guide the user better. WDYT @matyax?

**Comment by matyax** [comment]
>  there might be JSON formatted lines in the results of the context queries.

And can we know and react to that information?

> What would make sense though - and I realise this is a larger task - is to unify/improve log display options in Explore

Absolutely. I think all these `Getting starter tasks` should be treated as larger/research tasks, unless it's a very simple change. I'll be sure to make it more clear in the issues description.

@svennergr what do you think should be the next step here?

**Comment by svennergr** [comment]
> And can we know and react to that information?

We can't, because JSON lines might not be present until the context queries. And the LogContext is opened as a modal in front of the options.

> @svennergr what do you think should be the next step here?

Honestly I would like to redesign those options into something like a collapsible, where not all of those options would be present if collapsed and descriptions in the expanded panel might guide the user better. I feel that's a better approach to just remove items/options. Could also be a good medium sized task for @gwdawson imo. WDYT?

**Comment by matyax** [comment]
I think we would have to sync with UX on that one. I think the next step could be to update the issue with this discussion and plan to work with UX on Q1/Q2. I believe there's a lot of room for improvement in that section.

**Comment by svennergr** [comment]
> I think we would have to sync with UX on that one. I think the next step could be to update the issue with this discussion and plan to work with UX on Q1/Q2. I believe there's a lot of room for improvement in that section.

Agree! Let me update the issue tomorrow with what have been discussed.

I guess the PR can be closed then, agree @gwdawson @matyax ?

**Comment by matyax** [comment]
Agree.

**Pull request closed without merging**
