### PR TITLE
Expand "All" template variable in URL

### LINKED ISSUE #2368: Passing "All" values to another dashboard without enabled "All" option
Hi, this issue is related with the fixed bug on #2297 .

The _"All"_ variables is passing correctly (the bug was fixed) to another Dashboard (DS).

As an example:
The DS1 has metrics of _bk1,bk2,bk3_ as host.

The DS2 can show detailed metrics of more than one host, using repeat templating feature, but only if its passed by parameter ,_mutiple selection_ and _"All"_ **disabled**.
The host available on DS2 are _bk1,bk2,bk3_ (same as DS1) and _bk4,bk5,bk6_.

The first problem is that if DS2 doesn't have "All values" enabled, it doesn't recognize the passing value:
`&var-host=All`

The second problem is, if I activate, the "All" value on DS2 and I want to see detailed metrics of bk1,bk2,bk3, on the DS2, the "All" values shows, obviously, the bk1,bk2,bk3 and undesired bk4,bk5,bk6.

Would like to ask if its possible to pass the "All" values as it works on multiple selection feature:
`&var-host=bk1&var-host=bk2&var-host=bk3`

Thanks for all.

### PR DESCRIPTION
**Pull request by mtanda**
try to fix https://github.com/grafana/grafana/issues/2368.

### CODE REVIEW

**Comment by torkelo** [comment]
not sure if this is a good idea

**Comment by mtanda** [comment]
There are at least three cases, template variables are expanded to URL.
1. Dashboard sharing link
2. Panel sharing link
3. Drill down link in panel

For 1 and 2, I think expand actual values is good choice in most of cases.
If "Refresh on load" is set for template variable, the correspond values for "All" could be not same between creating sharing link, and open shared link.
If someone want to share "the result (view) of current dashboard", they indent to share same result to another one. (Escpecially with "Current time range", same graphs should be shown in another one's screen.)
If someone want to share "dashboard (not result)", they don't select "Include template variables", they share dashboard with default setting. ("All" in default setting is not expanded)


For 3, I'm not sure expand actual values is good idea or not.
```
dashboard1 (which has drill down link) => dashboard2 (destination of drill down link)
```
If the templating query is differ between dashboard1 and dashboard2, the correspond values for "All" could be not same. (this problem is mentioned at https://github.com/grafana/grafana/issues/2368#issue-96010165)
In this case, expand actual values is good choice.

If the templating query is same between dashboard1 and dashboard2, "which one is better" is depend of the situation.

**Comment by mtanda** [comment]
> If the templating query is same between dashboard1 and dashboard2, "which one is better" is depend of the situation.

May be "expand actual values" is better choice, because the query is same, the actual value is same in most of case.

**Comment by torkelo** [comment]
this has drifted a bit from master, and not many seem to be faced with https://github.com/grafana/grafana/issues/2368

**Pull request closed without merging**
