### PR TITLE
7.1.0-beta3 cherrypicks

### PR DESCRIPTION
**Pull request by aocenas**
* Chore: do not bundle rxjs with @grafana/data, (#26039), merge-sha: b7792de16da66deb89ba673f5f018fdadd25b8ea
  * Elastic: Fix displaying of correct log message, (#26020), merge-sha: 8b4665536178209ff4493f367dd0ea119d1d8dff
  * Graph panel: Move Stacking and null values before Hover tooltip options (#26035), (#26037), merge-sha: dec76b4556d5cba805178a57fe652bb2bb8f457d
  * AdminUsersTable: Fix width issues, (#26019), merge-sha: b06d2cf30f5dc4e690263025d69852c2e1853962
  * @grafana/e2e: close options panel before interacting with the query form, (#26036), merge-sha: 634d8d60d6e4a10e7400c97ee82ef15b6c298096
  * Table: JSON Cell should try to convert strings to JSON, (#26024), merge-sha: 3acc2a6ac2e91fe485fb88c48dd71b0560e62324
  * InfluxDB: Fixed new group by dropdown now showing after first use , (#26031), merge-sha: 66460ae740f04d2f167618931bcc04847a1196c5
  * Instrumentation for total count of dashboard versions and annotations in the database, (#26044), merge-sha: 26852ca788b83a4c757d5495dd0b57103f314acb
  * TextPanel: Fixed issue with height of inner content , (#26061), merge-sha: 8be735a6ec4809b2eae9f1c43651dbb129d68ce4
  * Panel Inspect: improve structure display, (#26065), merge-sha: af5dff8a1bc8cad60a8668e6f7dc1eb3fc427295
  * LDAP: Get all groups for all group base search DNs, (#25825), merge-sha: a2737c0896ce527bc091a24a55bae23c1dd6ca7f
  * ThemeContext: Make useStyles type-aware, (#26056), merge-sha: 390c80d7f530cea8473f56dfb6f7d19302d3063f
  * Auth: Fix POST request failures with anonymous access, (#26049), merge-sha: 44dff6fdd039f12f40571a49dd3dc63f61265635
  * Docs: Add guidelines for inclusive language, (#25533), merge-sha: 0f41ca620b91beb5efe6627ee7cea21755f770e3
  * Fix: Icon and Tooltip on Variables editor, (#26086), merge-sha: 8f1115c6acf351313fb1bbf118a10a6662be7645
  * StatPanel: Fixes issue with name showing for single series / field results, (#26070), merge-sha: c9f22b72e3c22b3e1ad446e2c63049efbc3fd94f
  * Chore: Bump rxjs to latest, (#26084), merge-sha: aa671c863e32dfa68689592123a0b562ca745ee0
  * Grafana UI: Make FileUpload button size customizable, (#26013), merge-sha: c3d4e69a3229906f5c6d028a7ee48152590d1c1b  
  * CircleCI: Upgrade build pipeline tool, (#26112), merge-sha: e7e854ea330fb73f30d65c0a100f951da1e1d1f6
  * Do not rename export for InlineFormLabel, (#26118), merge-sha: eb4391a228b5d97fb23f46dff5413d0b27debc68
  * Azure: Restore Insights Metrics alias feature, (#26098), merge-sha: 9164a35240d68d9be06a3cacaa6097ee733af03c
  * DataSourceWithBackend: add internal comment for new method, (#26139), merge-sha: 2b6833d0da5e1169692f69cfa9dbd00ef810ab4b
  * Do not break dashboard settings UI when time intervals end with trailing comma, (#26126), merge-sha: 30a682a4da6b9568a2da84c7fedef87de693c3a0
  * CSV: force UTF-8 encoding for download, (#26145), merge-sha: b26ef1db2592bbdb2207bc4772b124d0cb038423
  * DataLinks: Fixed interpolation of repeated variables used in Graph data links, (#26147), merge-sha: 89b56782c61fd9ee86d47032093086b30bda0a70
  * Transform: adding missing "table"-transform and "series to rows"-transform to Grafana v7-transforms., (#26042), merge-sha: 17d87071e6850827528e109e6fe5701ce057b649
  * Dashboard: Allow removing min refresh interval from refresh options (5s or other), (#26150), merge-sha: 8ab5d2ddd9dbacffcecc7d16e5ef9e4d0e56e726
  * Templating: Fixed recursive queries triggered when switching dashboard settings view, (#26137), merge-sha: cace879c96dd5bdc75132de090618da9db565ffb
  * Backend: use latest Go plugin SDK, (#26162), merge-sha: fd29b952a6790089f0bd35a6bd4f050826a859ff
  * Docs: Azure Monitor data source changes for 7.1, (#26096), merge-sha: c6a3afb4b839831093539009c683f627bc21fb26
  * BarGauge: Fix space bug in single series mode, (#26176), merge-sha: 7b80e300d97fa20d771c75f9323209c997f2eb0f
  * Loki: Improve error message for unescaped \ and add LogQL link to docs, (#26136), merge-sha: d3dcb19a5bb59db12ba4beba2c8fe3af8fc5fc5e
  * Templating: Fix recursive loop of template variable queries when changing ad-hoc-variable , (#26191), merge-sha: 0428f271949fe0d2f2d63c0048b28c11f8bdf24f
  * Explore: Run query on splitOpen action, (#26161), merge-sha: 53eb856d2086a9254897becaf03e5ce264e25a8e
  * Datasource/CloudWatch: More robust handling of different query modes, (#25691), merge-sha: 2ac1bfcc797c391ba0abe60a75f872d14dc03a64
  * Fix: Redirect to correct url after creating a folder, (#26160), merge-sha: 9948e9298faf3493f8a0c1007974a2c0fdae4670
  * Explore: Unification of logs/metrics/traces user interface, (#25890), merge-sha: 64bc85963b2b2afe86ad3c61510b9b1e41e9fb7a
  * Issue Template: @grafana/ui component request, (#25981), merge-sha: 5a3eb413d926d508e85c4c2012b7ece17e64d29e
  * DataLinks: add internal flag in comments, (#26215), merge-sha: 3d98641a45540d7a89c5c4e398f5a1786711e849
  * Flux: use monaco query editor, (#26179), merge-sha: 33acf4c056ef5621be6639c8d13fa58778c89727
  * AppPlugin: give full control to page layout when navigation is missing, (#26247), merge-sha: 5f8eb93db1f952c0575437a96c95983bc1ee5eff

### CODE REVIEW

**Comment by papagian** [comment]
Can you cherry-pick [this one](https://github.com/grafana/grafana/pull/26013) too; I have added the label a few time ago, thanks!

Also, this need to target the `v7.1.x` branch instead.

**Comment by aocenas** [comment]
@papagian added. I assume it's not an issue if it's out of order.

**Comment by papagian** [comment]
> @papagian added. I assume it's not an issue if it's out of order.

actually if it's out of order you can get some conflicts but it's not a big one so hopefully you won't.

**Review by aknuds1 — APPROVED** [review]

**Comment by ryantxu** [comment]
If possible, can we also add:
https://github.com/grafana/grafana/pull/26179

**Comment by ryantxu** [comment]
And one more.... i am terrible!  https://github.com/grafana/grafana/pull/26247    but it is for the easy start team :)

**Pull request merged**
