### PR TITLE
Prometheus: Implement region annotation

### LINKED ISSUE #18174: Region annotation with source prometheus
We can create a region annotation via web-interface (https://grafana.com/docs/reference/annotations/#adding-regions-events) or grafana API (https://grafana.com/docs/http_api/annotations/) by parameter "isRegion":true.

If we use data source prometheus we cannot make region annotation. 
On web intarface "Annotations > Edit" for "Data source" prometheus we add search expression with bool value like "increase(updater{job="our-job"}[60s]) == bool 0" and our expression true for a long time we get sequence of single annotations with step specified on the same web-interface. It's look a little noisy.

It will be great if in annotation web-interface for "Data source" prometheus  will be added a check box like "isRegion". If "isRegion" is active then sequence of single annotations (points) while the expression is true convert to region annotation.

### PR DESCRIPTION
**Pull request by secustor**
**What this PR does / why we need it**:
This PR implements the ability to create region annoations if querying a Prometheus datasource

**Which issue(s) this PR fixes**:
Fixes #18174

### CODE REVIEW

**Comment by secustor** [comment]
Query step == annotation query step == 15s
image

Query step (15s) != annotation query step == 60s
image

**Comment by secustor** [comment]
rebased and squashed commits. 

Could you restart the CI Job? The error seam to indicate that the process simple got killed.

**Review by aocenas — APPROVED** [review]

**Comment by aocenas** [comment]
@secustor thanks for the contribution. Hope you don't mind, I did a small refactor and added some more tests.

**Comment by secustor** [comment]
@aocenas No, I absolutely don't mind.    
 It's my third contribution/program in Typescript/JavaScript so I have been aware that there is for sure improvement potential in my code.

**Pull request merged**
