### PR TITLE
Schema: Use Options and FieldConfig types from schema package

### PR DESCRIPTION
**Pull request by dprokop**
Since https://github.com/grafana/grafana/pull/64723 is merged, we should use the types provided by grafana/schema. These types have standardized names for Options and FieldConfig.

@sdboyer / @spinillos - do you mind helping me with updating the script that generates the types, to no longer generate the `panelcfg.gen.ts` next to the original cue file?

### CODE REVIEW

**Comment by sdboyer** [comment]
Hmm, that seems to run counter to my understanding discussed previously (though i know it's been a while):

* Types generated inside the directory of the core plugins are used by the plugins themselves, including any veneers they write
* Types generated in `@grafana/schema` for a particular plugin are used by anything _other_ than that plugin that wants to declaratively create an instance of that plugin's type

This "self-use" vs "use by others" is the same distinction we make for everything else in codegen land, except that "use by others" is only generated in grok. If we do this, how would core plugins interact with their own TS types after we move all this out to grok?

**Comment by dprokop** [comment]
> This "self-use" vs "use by others" is the same distinction we make for everything else in codegen land, except that "use by others" is only generated in grok. If we do this, how would core plugins interact with their own TS types after we move all this out to grok?

Ok, seems we have both understood it slightly differently. IMO with types like `Options` and `FieldConfig` there should be no differentiation between self-use vs use-by-others - but I may be wrong. Those are technically public APIs of the plugin, so what's the point of duplicating the source of it? It is a different story from other types which indeed need to be curated for grok.  But in general, is see no point in duplicating type definitions.

If we move these types to grok, would they no longer live within grafana/schema? Think this brings up a discussion about the grafana/schema and it's future - seems like we treat it as a temporary solution before we expose everything via grok? If so, then this inevitably leads us to a place, where grok becomes a dependency in core, similar to grafana/schema. And I don't see other types being duplicated in a way you're suggesting for plugins. Is that specific to `kind` types?

@sdboyer - sorry for so many questions. I think you may have a valid point here, but just want to understand the approach a bit more.

**Comment by sdboyer** [comment]
Sorry, let try putting it a different way: if we do this, then it's taking a step towards making core plugins look _less_ like external plugins. The more different core plugins look than external plugins, the more they require special handling and tooling.

That cuts directly against the general goal of making core plugins look the same as external plugins. That's especially salient now given ~consensus earlier today in app platform wg meeting about leaning hard into just having one SDK (entailing that plugins platform folks start making moves to unify things _now_).

**Comment by sdboyer** [comment]
> If we move these types to grok, would they no longer live within grafana/schema? Think this brings up a discussion about the grafana/schema and it's future - seems like we treat it as a temporary solution before we expose everything via grok?

i do think it's worth making sure we're basically clear on longer term plan, yeah.

One option we ought to at least consider is that `@grafana/schema` just gets published out of grafana/grok, rather than out of grafana/grafana.

**Pull request closed without merging**
