### PR TITLE
Multiple occurrences removed to overcome typo

### PR DESCRIPTION
**Pull request by Mohit-Nain**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
@aknuds1 think you can merge this since it's only removal of typo.

**Comment by aknuds1** [comment]
> @aknuds1 think you can merge this since it's only removal of typo.

@marefr Was just waiting on CI :)

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Pull request merged**
