### PR TITLE
Chore: Fixed a typo in AnalyticsConfig.test.tsx file

### PR DESCRIPTION
**Pull request by Mikheil-A**
Fixed a typo in "reseting".

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

**Comment by dprokop** [comment]
@Mikheil-A please sign CLA before we can merge this.

**Comment by andresmgot** [comment]
Hi @Mikheil-A. Thanks for fixing the typo! We would need you to sign the CLA in order to be able to merge the PR. You can find more info [here](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla).

**Comment by Mikheil-A** [comment]
> @Mikheil-A please sign CLA before we can merge this.

Signed.

**Review by andresmgot — APPROVED** [review]
thanks for fixing the typo!

**Pull request merged**
