### PR TITLE
Alerting docs: vale fixes

### PR DESCRIPTION
**Pull request by brendamuir**
Fixes another set of vale errors as per the excel sheet.

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
We've actually revised the "we" rule to be more clear that it's OK to use it if you mean Grafana Labs. The main reason for the rule is to avoid using "we" when you mean "you"

https://github.com/grafana/writers-toolkit/blob/main/vale/Grafana/We.yml

I think passive the voice "it is VERBed" rather than "we VERB" may be an undesirable change.

**Comment by jdbaldry** [comment]
Are you ready for a full review? I ask because I saw commits coming in as I started the review.

**Comment by brendamuir** [comment]
ah ok. hadn't realised that one. i'll change back the we ones. and yes, after that ready for a full review.

**Review by jdbaldry — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
