### PR TITLE
DevEnv: update frontend dependencies - react

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 12 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `react-transition-group` - changes (2.6.1 -> 4.3.0): https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md
- `react-use` - changes (12.8.0 -> 13.24.0): https://github.com/streamich/react-use/blob/master/CHANGELOG.md

Changes - less significant:
- `react-hot-loader` - changes (4.8.0 -> 4.12.9): https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md
- `react-sizeme` - changes (2.5.2 -> 2.6.12): https://github.com/ctrlplusb/react-sizeme/releases
- `react-window` - changes (1.7.1 -> 1.8.5): https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md
- `react-popper` - changes (1.3.3 -> 1.3.7): https://github.com/popperjs/react-popper/releases

### CODE REVIEW

**Comment by Estrax** [comment]
@dprokop this one seems to have issues with resolving `node_modules` routes via webpack, can you take a look at it?

**Review by mckn — CHANGES_REQUESTED** [review]
When trying to build this one I get the following errors:

```bash
[Webpack] [./public/sass/grafana.dark.scss] 4.08 KiB {dark} [built] [failed] [1 error]
[Webpack] [./public/sass/grafana.light.scss] 4.08 KiB {light} [built] [failed] [1 error]
[Webpack]     + 3472 hidden modules
[Webpack] 
[Webpack] ERROR in ./public/sass/grafana.dark.scss
[Webpack] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[Webpack] ModuleNotFoundError: Module not found: Error: Can't resolve '../../node_modules/rc-drawer/assets/index.css' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/public/sass'
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/Compilation.js:823:10
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:397:22
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:130:21
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:224:22
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:2830:7
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:6877:13
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:214:25
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:213:14
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
[Webpack]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[Webpack] 
[Webpack] ERROR in ./public/sass/grafana.light.scss
[Webpack] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[Webpack] ModuleNotFoundError: Module not found: Error: Can't resolve '../../node_modules/rc-drawer/assets/index.css' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/public/sass'
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/Compilation.js:823:10
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:397:22
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:130:21
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:224:22
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:2830:7
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:6877:13
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:214:25
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:213:14
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
[Webpack]     at eval (eval at create (/Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
[Webpack]     at /Users/marcusandersson/development/go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
[Webpack]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx
[Webpack] Module not found: Error: Can't resolve 'bizcharts' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/BigValue'
[Webpack]  @ ./packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx 26:0-40 186:33-38 220:75-79 227:30-34
[Webpack]  @ ./packages/grafana-ui/src/components/BigValue/BigValue.tsx
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/Drawer/Drawer.tsx
[Webpack] Module not found: Error: Can't resolve 'rc-drawer' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Drawer'
[Webpack]  @ ./packages/grafana-ui/src/components/Drawer/Drawer.tsx 44:0-33 75:29-37
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx
[Webpack] Module not found: Error: Can't resolve 'react-calendar/dist/entry.nostyle' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/TimePicker/TimePickerContent'
[Webpack]  @ ./packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerCalendar.tsx 113:0-57 212:29-37
[Webpack]  @ ./packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimeRangeForm.tsx
[Webpack]  @ ./packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimePickerContent.tsx
[Webpack]  @ ./packages/grafana-ui/src/components/TimePicker/TimePicker.tsx
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx
Module not found: Error: Can't resolve 'react-custom-scrollbars' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/CustomScrollbar'
[Webpack]  @ ./packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx 36:0-49 143:33-43
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/Forms/index.ts
[Webpack] Module not found: Error: Can't resolve 'react-hook-form' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Forms'
[Webpack]  @ ./packages/grafana-ui/src/components/Forms/index.ts 1:0-61 25:16-28
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/Forms/Form.tsx
[Webpack] Module not found: Error: Can't resolve 'react-hook-form' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Forms'
[Webpack]  @ ./packages/grafana-ui/src/components/Forms/Form.tsx 8:0-42 15:17-24
[Webpack]  @ ./packages/grafana-ui/src/components/Forms/index.ts
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] 
[Webpack] ERROR in ./packages/grafana-ui/src/components/Table/Table.tsx
[Webpack] Module not found: Error: Can't resolve 'react-table' in '/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Table'
[Webpack]  @ ./packages/grafana-ui/src/components/Table/Table.tsx 12:0-66 39:18-26 46:5-14 46:16-30
[Webpack]  @ ./packages/grafana-ui/src/components/index.ts
[Webpack]  @ ./packages/grafana-ui/src/index.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
[Webpack] No type errors found
[Webpack] Version: typescript 3.7.2
[Webpack] Time: 8664ms
```

**Comment by mckn** [comment]
Since there are a lot of breaking changes it might be a good idea to split those up into multiple PRs and take the package one by one, what do you think about that?

**Comment by Estrax** [comment]
Sure, let's try to do it one by one. I'll split it sometime over the weekend.

**Comment by Estrax** [comment]
Moved to small PRs.

**Pull request closed without merging**
