### PR TITLE
Graph panel: Add toggle X-Axis action

### LINKED ISSUE #21021: Graph panel: Toggle X Axis
**What would you like to be added**:

A toggle X axis next to toggle legend

xax

**Why is this needed**:
While X axis is not often needed, when I share a particular graph, I like to toggle legend and X axis.

### PR DESCRIPTION
**Pull request by roidelapluie**
Closes #21021

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
tested locally.

**Review by dprokop — APPROVED** [review]
Thanks for this contribution! @torkelo anything against merging this?

**Comment by torkelo** [comment]
Not sure what the use case for this is. 
> While X axis is not often needed, when I share a particular graph, I like to toggle legend and X axis. 

This makes little sense to me, to share with x axis off you then need to save the dashboard as well, so why not make this change in edit mode instead?

**Comment by roidelapluie** [comment]
@torkelo I share the PNG or screenshot.

**Comment by torkelo** [comment]
> @torkelo I share the PNG or screenshot.

You mean you temporarily remove x-axis then take a screenshot (but do not save dashboard)

**Comment by roidelapluie** [comment]
I temporarily add the X-Axis, which is hidden because in some dashboards we hide it by default because we have small sized panels.

**Comment by torkelo** [comment]
Still feels like a strange option to have there, closing this until it becomes more of a common request / usage.

**Pull request closed without merging**
