### PR TITLE
SSE: (WIP) SSE specific query endpoint

### PR DESCRIPTION
**Pull request by kylebrandt**
**What this PR does / why we need it**:
SSE (Server Side Expressions) specific endpoint. Queries are executed via SSE even if there isn't an expression.

Primary meant for visualization with alerting, also introduces per query times ranges.

**Special notes for your reviewer**:

- Perhaps this should be an endpoint under alerting and more specific.
- There should maybe be a containing object for this array for other properties
- from and to are unix epoch timestamps (and per query) (this is different from the saved alerting query model with is relative time).
- data source is identified solely by UID

This is pretty dirty but trying to unblock FE.

Example:
```

POST http://admin:admin@localhost:3000/api/ds/sse/query
Content-Type: application/json

[
  {
    "points": [],
    "stream": {
      "type": "signal",
      "speed": 250,
      "spread": 3.5,
      "noise": 2.2,
      "bands": 1
    },
    "pulseWave": {
      "timeStep": 300,
      "onCount": 3,
      "onValue": 2,
      "offCount": 3,
      "offValue": 1
    },
    "csvWave": {
      "timeStep": 60,
      "valuesCSV": "0,0,2,2,1,1"
    },
    "stringInput": "",
    "scenarioId": "predictable_pulse",
    "lines": 10,
    "refId": "A",
    "alias": "",
    "datasourceUid": "000000004",
    "timeRange": {
      "from": 161883908000,
      "to": 161883928000
    }
  },
  {
    "type": "reduce",
    "datasourceUid": "-100",
    "reducer": "mean",
    "expression": "A",
    "refId": "B"
  },
  {
    "type": "math",
    "datasourceUid": "-100",
    "expression": "$B > 10",
    "refId": "C"
  }
]
```

Response is like (frames json encoded, not base64): 

```
  "results": {
    "C": {
      "frames": [
        {
...
```

### CODE REVIEW

**Comment by mckn** [comment]
Great work with this! Would it be a good idea to have some kind of `queryType` that indicates if the query is an expressionQuery or a dataQuery?

**Comment by kylebrandt** [comment]
> Great work with this! Would it be a good idea to have some kind of `queryType` that indicates if the query is an expressionQuery or a dataQuery?

Presently that is the `datasourceUid`, `datasourceUid == "-100" == expression`

**Comment by mckn** [comment]
> > Great work with this! Would it be a good idea to have some kind of `queryType` that indicates if the query is an expressionQuery or a dataQuery?
> 
> Presently that is the `datasourceUid`, `datasourceUid == "-100" == expression`. Any other datasourceUid is an data source query.

Ah, just saw that in the code. Super!

**Review by mckn — APPROVED** [review]
LGTM

**Comment by kylebrandt** [comment]
For now leaving this un-merged.

Right now this operates on something closer to what I believe the dashboard sends (no model property, abs time ranges).

After talking to @mckn think it is better to have an endpoint that accepts a payload closer to the stored model, (so closer to alerting save endpoint for grafana alert rules). This should also help make sure their are not inconsistency between evaluation and visualization. 

But I think this means an additional alerting-api test endpoint. cc @papagian

**Comment by kylebrandt** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/33174

**Pull request closed without merging**
