### PR TITLE
Graph: Deprecate Graph (old) and make it no longer a visualization option for new panels 

### PR DESCRIPTION
**Pull request by torkelo**
This makes the Graph (old) panel no longer a selectable panel for new panels.

Was thinking of adding a feature toogle that when enabled force a migration of all graphs to time series.

### CODE REVIEW

**Comment by ryantxu** [comment]
> Was thinking of adding a feature toogle that when enabled force a migration of all graphs to time series.

YES.  Would be great to get it turned on soon so we can see what happens in our infra.  The migration path we have is pretty good, but we need real test data to make sure it really works :)

**Review by ryantxu — APPROVED** [review]

**Review by dprokop — APPROVED** [review]
🥳

**Comment by sgbenner** [comment]
With graph (old) deprecated, how do I set up a time series bar chart with dual X axis? The old graph option had a way to do this. I'm not seeing an option with the time series plugin.

**Comment by WojciechKuk** [comment]
we can't migrate, because we have ~2000 graphs/dashboards with dual (left-right) Y-axis.
"Graph (old)" was one of the best panels in Grafana, why was it removed (from selection) in 9.x?

**Pull request merged**
