### PR TITLE
Plugins: verify manifest signature

### PR DESCRIPTION
**Pull request by ryantxu**
We now have a real signing service... just need to decode them :)

This adds my attempt... still missing:

- [x] test signature
- [x] go mod vendor
- [x] test running
- [x] real public key (p521)

### CODE REVIEW

**Comment by ryantxu** [comment]
@bergquist can you take a look?  I *think* this is close, but can't figure out how to `go mod vendor` and actually run it!

**Comment by bergquist** [comment]
Looks like we need another private key :/ 
https://github.com/golang/go/issues/23421

**Comment by ryantxu** [comment]
@bergquist -- these are the easy options... which should we use:
https://github.com/openpgpjs/openpgpjs#generate-new-key-pair

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/issues/22961

**Review by bergquist — APPROVED** [review]
I think this looks good. Let's merge and add support for multiple public keys in an other PR?

**Pull request merged**
