### PR TITLE
Add flot plugin Candlestick with dependent library

### PR DESCRIPTION
**Pull request by ilgizar**
To fix #516 need add the necessary plugin. Some examples of the work of the new panel plugin:

In this PR the panel plugin is not present, it while in development. It will be a separately installed plugin. But for his work, these changes are necessary.

### CODE REVIEW

**Comment by JamesGalt** [comment]
Hi,
I really would like to have candlesticks.
Will you make your plugin grow also classic graph so i can draw BBands or EMA into it?
Would be amazing
Thanks

**Comment by ilgizar** [comment]
@JamesGalt The implementation of analytical charts is complicated by the principle of obtaining data. For the construction of indicators, data for previous periods are needed, as long as there is no such possibility.

**Comment by JamesGalt** [comment]
@ilgizar I'm not talking about adding analytical charts directly, as I can compute them, just adding the possibility to draw line graphs so I can display them.
Thanks

**Comment by ilgizar** [comment]
@JamesGalt Draw metrics from external sources - not a problem.

**Comment by JamesGalt** [comment]
Nice, 
Will be amazing!
Thanks!

**Comment by ilgizar** [comment]
@JamesGalt like this?

**Comment by JamesGalt** [comment]
@ilgizar Perfect! 
You're the man, waiting for this feature for almost a year now! 
If you need a beta tester I'm in!
Should volume have an histogram option?

**Comment by ilgizar** [comment]
@JamesGalt Thanx.
How do you imagine overlaying a histogram on a time series? Grafana natively does not yet support the second x-axis.
PS: although in my plugin I can add one more x-axis (to top or bottom).

**Comment by JamesGalt** [comment]
@ilgizar Sorry, by histogram I was meaning bar view.
But histogram can be an idea for price repartition. Not sure how useful id would be.
Again, Thanks!

**Comment by ilgizar** [comment]
I moved flot candlestick plugin inside to panel grafana plugin.
@JamesGalt beta version was placed here https://github.com/ilgizar/ilgizar-candlestick-panel/raw/master/pack/ilgizar-candlestick-panel.zip

**Comment by JamesGalt** [comment]
@ilgizar Brillant!
First impressions:
I dont know why but boxes are two wide
see screenshot
capture d ecran 2018-02-22 a 00 55 20

which version of grafana are you using? thanks

**Pull request closed without merging**
