### PR TITLE
Plugins: Remove requestInstrumentationStatusSource feature toggle

### LINKED ISSUE #80534: Feature toggle removal `requestInstrumentationStatusSource`
Remove the feature toggle and enable the functionality by default.

Reference: https://github.com/grafana/grafana/issues/68480

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Remove the feature toggle `requestInstrumentationStatusSource` and enable the functionality by default.

**Why do we need this feature?**

We need the functionality enable by default.

**Who is this feature for?**

This is necessary for https://github.com/grafana/grafana/issues/68480

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/80534

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by academo — APPROVED** [review]

**Comment by xnyo** [comment]
@marefr Please can you take a look?

**Review by marefr — APPROVED** [review]
LGTM

**Review by xnyo — APPROVED** [review]
You have to merge main and change the milestone to 11.0.x but apart from that LGTM! :tada:

**Comment by oshirohugo** [comment]
@xnyo @marefr  It seems like since this PR was open the feature toggle was already removed by another PR:

https://github.com/grafana/grafana/pull/81617 

two weeks ago.

If you confirn I'll close this PR.

**Comment by xnyo** [comment]
> @xnyo @marefr It seems like since this PR was opened the feature toggle was already removed by another PR:
> 
> #81617
> 
> two weeks ago.
> 
> If you confirn I'll close this PR.

Looks like it, this PR can be closed :+1:

**Comment by oshirohugo** [comment]
Closing because of https://github.com/grafana/grafana/pull/81617

**Pull request closed without merging**
