### PR TITLE
fix_readme_doc organizations get & create organization

### PR DESCRIPTION
**Pull request by zhengkai6**
* Link the PR to an issue for new features
* Rebase your PR if it gets out of sync with master

**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by xixikaikai** [comment]
related issue here:
https://community.grafana.com/t/organization-http-api-can-not-be-used/3390

**Comment by bergquist** [comment]
@xixikaikai the git commit author have to match the github user. Otherwise, you won't be able to sign the CLA.

**Comment by xixikaikai** [comment]
Hello @bergquist  I've changed the codes in another PR:
https://github.com/grafana/grafana/pull/9651

**Comment by xixikaikai** [comment]
This PR changed into https://github.com/grafana/grafana/pull/9651.
Close this PR.

**Pull request closed without merging**
