### PR TITLE
Accept URL parameter [database] config

### PR DESCRIPTION
**Pull request by Soulou**
For instance, accept and use in priority

``` toml
[database]
url = "mysql://user:password@host:port/database"
```

instead of

``` toml
[database]
type = "mysql"
user = "user"
password = "secret"
host = "host:port"
name = "database"
```

Why? Beging configurable with only one environment variable:

```
GF_DATABASE_URL=mysql://user:secret@host:port/database
```

### CODE REVIEW

**Comment by torkelo** [comment]
I agree that having one option for this is better, which it was that from the start. But not sure it's enough of an issue to add this code and support both options.

**Comment by Soulou** [comment]
Hi there, a lot of database as a service are providing an URL like this. When linked to a PaaS hosting solution, it eases the workflow a LOT to be able to configure grafana automatically. The purpose of this pull request could be for instance to allow 'one click' deployment to such platforms.

I didn't really get why you've closed the issue, can you provide more information?

Thanks

**Comment by torkelo** [comment]
Like a said:
> But not sure it's enough of an issue to add this code and support both options.

But you could convince me :) 

> A lot of database as a service are providing an URL like this. 

What do you mean? They provide only a single ENV property? Why can't you specify the Grafana DB using multiple ENV properties?  I know that a single one would be easier & simpler but is it making it impossible to use?

**Comment by Soulou** [comment]
Yes using a single ENV property, that's the point:

1. It would let us implement 'one click' deployment of grafana, spreading the project further. By 'one click', I mean having a button 'Deploy to X' and 2 minutes later it's live. (Database connection string are always represented as URL there)

2. It would respect the 12 factor, which are great to make app more flexible and scalable: http://12factor.net/backing-services

3. When upgrading the database addon in a Platform as a Service, to get for instance, HA or master-slave or anything else, the URL is changing and the linked application is restarted automatically. If Grafana handles the URL, there is nothing to do, it just works, otherwise you need to read the newly generated URL in your environment and split it... again. (not mentionning downtime has the connection params have changed)

**Comment by torkelo** [comment]
Not sure how point 2 is relevant as you can configure everything with ENV variables.

Do you have a spec for how PaaS formats the database URL for different databases (mysql / postgres), is there an established standard?

**Comment by Soulou** [comment]
There is no 'spec', it's more of a convention, that an external resource, like a database is represented as a single environment variable, defined as an URL, the app has to read it and handle it by itself.

Redeploying the app in another environment should not been harder than changing this single environment variable.

**Pull request merged**
