### PR TITLE
AdminUser: add reset_admin_every_time_run in cfg security

### LINKED ISSUE #49055: Changed Environment Variables do not get picked up in Grafana even though the `env` command has the updated values
**What happened**:

1. Bring a Grafana Docker container up using the repository mentioned below. Use `make build` to generated `docker-compose.yml` file and then `make run` to bring the container up. The `GF_SECURITY_ADMIN_USER`, `GF_SECURITY_ADMIN_PASSWORD` are set via the `conf/grafana/.env`. Initial Values are set to `admin` and `supersecretpass` respectively
2. Grafana works and one can login with the credentials value as mentioned above on http://localhost:3000
3. Change the `GF_SECURITY_ADMIN_PASSWORD` in `conf/grafana/.env` to `supersecretpass123` and bring the container down using `make clean`
4. Create the updated `docker-compose.yml` file using `make build` and bring the container up using `make run`
5. This should make the container available on the same URL, however when one tries to login with the updated `GF_SECURITY_ADMIN_PASSWORD`, the login does not work. Grafana logs me in only with the previous password set

Grafana_Env_Var_Docker_bug

**What you expected to happen**:

Assuming the container is brought down and brought back up again, the new environment variables should be used to let the user login into Grafana.

Since `GF_SECURITY_ADMIN_PASSWORD` is now changed and is also reflected within the container's environment, the value should be the actual password for admin login and should not rely on the older password previously set.

**How to reproduce it (as minimally and precisely as possible)**:

- Test Environment Reproduction Repository: [Repo on GitHub](https://github.com/shantanoo-desai/compose-v2-env-vars-problem)

The repository provides a very simple example of reproducing the bug with all the relevant documentation necessary. It does not require any other dependency except an updated Docker Engine to v20.10.14 with the compose CLI v2.5.0 which is now shipped within the environment.

**Anything else we need to know?**:
The only possible way to overcome this bug, is to actually purge the docker volumes which may contain other valuable data. It is rather unfeasible to purge a complete docker volume to reset the new Admin password.

**Environment**:
- Grafana version: 8.4.0, 8.4.5
- Data source type & version: Docker Image: `grafana/grafana-oss:8.4.5` from Docker Hub
- OS Grafana is installed on: Tested with Docker on GNU/Linux, Docker with WSL2 on Windows 10
- User OS & Browser: Mozilla Firefox, Google Chrome
- Grafana plugins: N/A
- Others: docker version 20.10.14 and docker compose version v2.5.0

Output of `docker info` (if relevant)

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 16
  Running: 1
  Paused: 0
  Stopped: 15
 Images: 8
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.78GiB
 Name: docker-desktop
 ID: AM3A:EIDA:J3BS:FMN2:MZMR:3CBY:YHXN:US7Q:BIKM:7POA:WAGC:MRWX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by BobDu**
Signed-off-by: BobDu <i@bobdu.cc>

**What this PR does / why we need it**:

Now, we can only set admin password once on first-run. It's maybe no problem in orignal deploy method.
But, more and more choices deploy grafana in k8s/docker.
In this way, we need set password with env and ensure password always equal env value.

**Which issue(s) this PR fixes**:

Fixes #49055 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kundkingan — APPROVED** [review]

**Comment by mellieA** [comment]
@BobDu thank you for your contribution!  I've added this to the backend platform project for review and comments.

**Comment by BobDu** [comment]
> @BobDu thank you for your contribution! I've added this to the backend platform project for review and comments.

some update?

**Comment by BobDu** [comment]
ping @mellieA @osg-grafana ?

**Comment by mellieA** [comment]
Noticed that this closed while waiting on someone from grafana to review. Reopened. 

@zserge  @mildwonkey would one of you be able to comment/review this external pr?

**Comment by ying-jeanne** [comment]
@BobDu the pr seems good and backward compatible, could you rebase it?

**Review by ying-jeanne — APPROVED** [review]

**Comment by BobDu** [comment]
@grafanabot ping. I update branch to rebase it, please reopen this PR?
@mellieA

**Comment by sakjur** [comment]
@BobDu I think you'll have to recreate the PR, I'm not able to reopen it. 
Screenshot 2023-05-02 at 15 37 01

**Comment by mildwonkey** [comment]
Hey @BobDu - first of all, sorry for how long this taken! We want to give this PR another look, but we can't reopen it for you, as @sakjur mentioned. If you reopen this (or open a new PR), I'll make sure it's (re-)reviewed this week and get it merged.
Thanks!

**Pull request closed without merging**
