### PR TITLE
Prometheus: Metrics explorer usability test improvements

### PR DESCRIPTION
**Pull request by bohandley**
**What is this feature?**
The metrics explorer (previously the metric encyclopedia) is a component in the Prometheus data source query builder. It allows users to browse metrics with a fuzzy search by name and description, filter by type, and more. In the last week we performed user interviews for usability testing.

[This is the synthesis of the findings.](https://docs.google.com/document/d/16bScxYnRE7sqVQ9GO3u8lDrcLQqmXi_FqVKC3XBXHKA/edit?usp=sharing)

**Notable improvements include** 
- add button to select metric instead of clicking entire row. A user can still use keyboard controls to select a highlighted or tabbed row. Users often moused over metrics and the modal was abruptly closed as they explored. This makes mouse clicking more explicit.
- Remove inferred metrics setting. Interviewees find inferred metrics confusing and generally do not trust inferred types.
- Open modal button option now persists after typing in the metric select. 
- Add options for “unknown” and `undefined` type in filter by type.
  - unknown metrics are metrics that are given a type that is invalid and prometheus will give these an explicit "unknown" type
  - undefined type metrics are most likely metrics written to prometheus and have no documented type, and therefore the type is undefined in prometheus.
- Add highlighting for regex search.
- Add (summary) to metrics that are created from summaries to make consistent with how we are showing some counters are made from histograms.
- Change setting wording for “Include search with type and description” to "Include description in search"
- Remove type from input search. Having type is redundant with filter by type (thanks @leeoniya! Confirmed in usability tests).

Screenshot 2023-06-06 at 5 40 41 PM

**Why do we need this feature?**
This feature was developed as a finding from the 2022Q4 Getting Started: Prometheus research. Users wanted to know more about their metrics, to search more meaningfully, and to have a UI that is improved upon for browsing 10s of thousands or more metrics.

[See this PR for more context about the history of this component's development.](https://github.com/grafana/grafana/pull/68421)

**Who is this feature for?**
This feature is for beginning and intermediate Prometheus users who want to know more about their metrics.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by catherineymgui — CHANGES_REQUESTED** [review]
- [x] Cursor changes to hand on hovering table row —> can we remove this cursor change as it infers something is clickable? Cursor change makes sense on the button still
- [x] Can you add 4px between the counter (histogram) and tooltip
- [x] Can you have the tooltip pop out from top-left instead of top-right (having the user read from left to right instead)
- [x] Noticed a div — is there a reason for this here? If not, can it be removed and we have 16px padding b/w the two elements (instead of 16px, div, 16px) 
Screenshot 2023-06-07 at 13 04 42

- [x] Column with select button — can the items in the column be aligned horizontally as well?
- [x] Noticed select button has a border but I don't see that styling in the button component. Could you check?

**Comment by bohandley** [comment]
Updated! All changes were able to be done. Details below:

> * [x]  Cursor changes to hand on hovering table row —> can we remove this cursor change as it infers something is clickable? Cursor change makes sense on the button still
> * [x]  Can you add 4px between the counter (histogram) and tooltip
> * [x]  Can you have the tooltip pop out from top-left instead of top-right (having the user read from left to right instead)
> * [x]  Noticed a div — is there a reason for this here? If not, can it be removed and we have 16px padding b/w the two elements (instead of 16px, div, 16px)
_the div was for the loading spinner, but I placed this on the right of the type filter so we can have the 16px padding between the input and the select._
> 
> Screenshot 2023-06-07 at 13 04 42
> * [x]  Column with select button — can the items in the column be aligned horizontally as well?
> * [x]  Noticed select button has a border but I don't see that styling in the button component. Could you check?
_I removed the border, and I'm not sure where that came from! None of the elements have a border as far as I can see. If you want, I can remove the border from the "Additional Settings" button too_

**Comment by catherineymgui** [comment]
> I can remove the border from the "Additional Settings" button too

Yes, that would be great!

Could we also increase the size of the button (from sm to md)? And the button's column width by 2.5% (and shrink the name column by 2.5%).

The tap target on the button is small, which was less obvious when the cursor changed on row hover.

Other than that it's all good!

**Comment by bohandley** [comment]
@catherineymgui updated! 🕺🏻 
Screenshot 2023-06-07 at 6 40 47 PM

**Review by catherineymgui — APPROVED** [review]
Looks good, thanks!!

**Pull request merged**
