### PR TITLE
Table: Add minimum column width field for auto resizing

### LINKED ISSUE #24759: Table Panel: Auto width not works on small width
**What happened**:
Auto width not works on small width
third column is not visible

image

**What you expected to happen**:

In old version works fine

image

**How to reproduce it (as minimally and precisely as possible)**:
small width of table panel 

**Anything else we need to know?**:
related issue #24719

**Environment**:
- Grafana version: v7 beta-3
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by pricek**
**What this PR does / why we need it**:
The table panel cannot resize the columns based on its contents. This allows users to enter the minimum width to mimic that fucntionality
**Which issue(s) this PR fixes**:

Fixes #24759

### CODE REVIEW

**Review by tskarhed — DISMISSED** [review]
Thanks for the PR! We think this issue should be handled entirely in the Table component. Adding to the FieldConfig introduces unnecessary complexity.

**Comment by pricek** [comment]
Can I get clarification on what you mean by Table component, like should it be constrained to specific files being updated? My understanding from #25722 was that true automatic resizing was not possible using the new table format.

**Comment by zorkin82** [comment]
Are there any news how this will go on?
We are tying to migriate to Grafana 8 but nearly all tables are broken because of this issue.

**Comment by tskarhed** [comment]
Maybe @torkelo want to chime in on this. If automatic column resizing is impossible, is introducing minWidth to the FieldConfig a reasonable solution?

**Review by torkelo — APPROVED** [review]
Think this makes some sense

**Review by torkelo — CHANGES_REQUESTED** [review]
Need to update the docs with this new setting as well:
https://github.com/grafana/grafana/blob/main/docs/sources/panels/visualizations/table/_index.md#column-width

**Comment by torkelo** [comment]
@pricek will you have time to update the docs or do you want us to take over?

**Comment by pricek** [comment]
@torkelo I should be able to get the docs updated this weekend. Sorry about the delay.

**Review by torkelo — APPROVED** [review]

**Pull request merged**
