### PR TITLE
Encryption: Convert functions into global variables

### PR DESCRIPTION
**Pull request by joanlopez**
**What this PR does / why we need it**:

We need to extend the encryption / decryption features from other components, so we decided to go with this intermediate step of making these functions as global (package) variables to make them overwritable. In a later stage we will convert these into an injectable service that will have multiple implementations as we usually do with other services.

### CODE REVIEW

**Comment by ying-jeanne** [comment]
I am not that expert on go, i saw 2 types of multiple implementation on go, whether we pass by interface or as you did by global variables as you did. From the unit test point of view, i think the two methods should be equal. Otherwise out of curiosity why you chose the current approach?

**Comment by joanlopez** [comment]
> I am not that expert on go, i saw 2 types of multiple implementation on go, whether we pass by interface or as you did by global variables as you did. From the unit test point of view, i think the two methods should be equal. Otherwise correct me if i am wrong, just out of curiosity why you chose the current approach?

These functions are package-scope functions now and they're being directly called as global functions from custom data structures (structs) methods (not from services, for instance). So, it's hard to add a new dependency defined as an interface. That's why decided to go with making the global functions modifiable (especially due to time constraints) and then explore an alternative approach with a service (i.e. using interfaces).

Does that make sense? 🤔 Thanks!

**Review by xlson — APPROVED** [review]
I think it it's okay to start off like this but I'd really like to get this into a service as soon as possible. Having it so that any code in grafana can easily swap out the encryption/decryption logic seems like a bit of a risk.

**Review by undef1nd — APPROVED** [review]

**Comment by joanlopez** [comment]
> I think it it's okay to start off like this but I'd really like to get this into a service as soon as possible. Having it so that any code in grafana can easily swap out the encryption/decryption logic seems like a bit of a risk.

Yeah, I agree! Making it as an injectable and extendable service is part of the plan! Thanks!! 😄

**Pull request merged**
