### PR TITLE
Chore: Fix $HOME_PATH for enterprise e2e tests

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
This was okay for OSS as it relies on the default, but Enterprise is different - hence why it was only caught now.

Enterprise build fails here:
```
+ ./e2e/start-server
Copying grafana backend files to temp dir...
Found package tar file dist/grafana-enterprise-8.3.0-11277pre.linux-amd64.tar.gz, extracting...
Copy provisioning setup from devenv
Starting Grafana Server port 3001
Grafana server is running with elevated privileges. This is not recommended
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
```

Fixes https://github.com/grafana/grafana-enterprise/pull/2123

**Special notes for your reviewer**:
This recent home path change to ensure it's an absolute path is a current requirement for plugin management

### CODE REVIEW

**Comment by wbrowne** [comment]
@dsotirakis might be something interesting for you to be aware of 

e2e testing is broken up into  `end-to-end-tests-server` and `end-to-end-tests`. In this particular case Drone thinks the `server` step succeeded, but the tests themselves fail. However, the server never started and says it failed according to the logs. Just an FYI in case that's an easy fix 🤔 

Screenshot 2021-11-01 at 11 44 55

**Comment by dsotirakis** [comment]
@wbrowne, can you please send me the Drone link so I can have a look?

**Comment by wbrowne** [comment]
> @wbrowne, can you please send me the Drone link so I can have a look?

:doh: https://drone.grafana.net/grafana/grafana-enterprise/11277/1/26

**Comment by dsotirakis** [comment]
`end-to-end-tests-server` is a service really, which doesn't run like a service but like a detached step, so the problem is that `end-to-end` tests failed due to the server not starting. I assume that it's a random error (reran it now), but we should fail gracefully if the `e2e/start-server` script fails.

**Review by xlson — APPROVED** [review]

**Comment by wbrowne** [comment]
> `end-to-end-tests-server` is a service really, which doesn't run like a service but like a detached step, so the problem is that `end-to-end` tests failed due to the server not starting. I assume that it's a random error (reran it now), but we should fail gracefully if the `e2e/start-server` script fails.

Not random sadly - it needs this PR merged in order to fix

**Pull request merged**
