### PR TITLE
Datasource: Azure Monitor - Fix 401 due to missing authorization header for existing datasources

### LINKED ISSUE #21868: 6.6.0 Azure Monitordata source / log analytics authentication error
**What happened**:
It would appear that there is a regression in how the authentication request to log analytics is being created.

The data source now gives the following error:

```
www-authenticate: Bearer authorization_uri="https://login.windows.net/3aacc835-4b83-483d-841d-cd787f6f1486", error="invalid_token", error_description="The authentication failed because of missing 'Authorization' header."
```

Mitigation was to rollback to 6.5.1

**What you expected to happen**:
Log Analytics queries should work as per 6.5.x

**How to reproduce it (as minimally and precisely as possible)**:
* Upgrade to 6.6.0
* Visit any existing dashboard with log analytics graphs, they will be broken
* Go to data source config, press f12, click test, ensure that you have the log analytics section populated.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Azure Montior
- OS Grafana is installed on: Docker (non ubuntu)
- User OS & Browser: Win 10/ Chrome
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by chelnak**
**What this PR does / why we need it**:
This PR fixes an issue in 6.6.0/6.6.1 where existing Azure Monitor sources that have been configured with provisioning fail to authenticate due to a missing authorization header.

Older datasources still expect the `sameasloganalyticsazure` route. Re adding this allows the correct settings to be retrieved and the authorization header is built as expected.

**Which issue(s) this PR fixes**:

Fixes #21868

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by shavonn** [comment]
@chelnak This will re-introduce another issue where users are unable to use sameas with any cloud that is not the default. I will look into an alternate solution.

**Comment by chelnak** [comment]
Thank you. Happy to lend a hand with the implementation if needed.

**Comment by chelnak** [comment]
@shavonn Did you get any further with this?

**Comment by shavonn** [comment]
This route can't be expected because it isn't saved in the provision file. The `azureLogAnalyticsSameAs` value is saved which just tells it which credentials to use. The `loganalyticsazure` route has the same headers. I believe it is an issue the route using the `logAnalyticsTenantId` variable in the route. I will work on this. Thanks.

**Pull request closed without merging**
