### PR TITLE
TimePicker: Should display in kiosk mode

### LINKED ISSUE #21815: Datepicker is not displayed in "kiosk=tv" mode
**What happened**:
Datepicker is not displayed in the `kiosk=tv` mode (grafana v6.6.0):
grafana_6 6 0

**What you expected to happen**:
The datepicker button is displayed the same as in the v6.5.3:
grafana_6 5 3

**How to reproduce it (as minimally and precisely as possible)**:

1. Open dashboard in `kiosk=tv` mode.

**Anything else we need to know?**:

This bug takes place as the datepicker button has the `navbar-button--zoom` class (instead of `navbar-button--tight`) which makes the element hidden in the mentioned mode.

**Environment**:
- Grafana version: 6.6.0 (5c11bbdfb4)
- OS Grafana is installed on: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by evgbibko**
Fixes #21815

### CODE REVIEW

**Comment by dprokop** [comment]
I think this works fine as a quick fix. But some next steps to be taken around here is to probably get rid of the sass that controls the visibility of the button and don't render the component if the mode is kiosk (!==tv) @mckn

**Comment by dprokop** [comment]
@evgbibko thanks for the contribution! Do you mind signing the CLA to get this merged?

**Comment by evgbibko** [comment]
@dprokop Sure. Done.

**Comment by marefr** [comment]
Same issue with folder dashboard title in this mode, seems to miss the arrow separating them
image

If easy fix, maybe can include that here as well? Otherwise I'll open separate issue.

**Comment by evgbibko** [comment]
@marefr yep, it's a separate bug but I've added a fix for it.

**Review by dprokop — APPROVED** [review]

**Comment by marefr** [comment]
@evgbibko Thank you for contributing to Grafana!

**Pull request merged**
