### PR TITLE
Chore: Check version compatibilty when installing a plugin

### PR DESCRIPTION
**Pull request by andresmgot**
**What is this feature?**

When installing a plugin without specifying a version, Grafana list all the possible versions and looks for the latest compatible one. It was checking the system arch (e.g. `linux` & `amd64`) but not if the Grafana version is compatible (with the API returns as `isCompatible`).

**Why do we need this feature?**

Ensures that when specifying no-version, the latest fully compatible version is installed.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana-community-team/issues/191

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by xnyo — APPROVED** [review]
LGTM!

**Review by wbrowne — COMMENTED** [review]
Just want to take this for a spin first - will circle back!

A question though, does this affect installing core plugins from catalog?

**Review by wbrowne — COMMENTED** [review]
Since the frontend is already doing the `isCompatible` check itself, it may be worth highlighting as part of this change that it'll be breaking change for the CLI. It's change for the better IMO but breaking nonetheless.

Just a couple things to mention!

**Review by andresmgot — COMMENTED** [review]
> Since the frontend is already doing the isCompatible check itself, it may be worth highlighting as part of this change that it'll be breaking change for the CLI. It's change for the better IMO but breaking nonetheless.

That's a very good point.  I checked, and the endpoint that was used to list versions changed in 10.2 so I'd rather not break this just in case someone is relying on the bug to install plugins at startup. We can re-enable the check for Grafana 12. I have udpated the code just for the Grafana CLI. WDYT?

**Review by wbrowne — APPROVED** [review]
Awesome 👏

**Pull request merged**
