### PR TITLE
Enable suppression of empty panels

### PR DESCRIPTION
**Pull request by LLIyRiK**
Hi there.
This is implementation of suppress empty panels functionality as described in issue #4470.
We reused the idea from the #5320 pull request. The repeated panels that have no data to show will not appear on the dashboard, making it much easier to interpret.

This feature has made things much easier for me, and, as I see from groups.io discussions and github issues, it could come in handy for quite a number of people.

Would be great to see it in the upstream.

Options:

Before:
image
After:
image

### CODE REVIEW

**Comment by daniellee** [comment]
This looks pretty good but there is one UX change we would like to make. Instead of a toggle in the dashboard settings, it would be better to have an indicator/toggle that shows that there are suppressed panels in the sub menu bar after the template variable drop downs. 

image

The indicator/toggle should show the number of suppressed panels and clicking on it would show them. 

The reasoning is that as it is implemented now, for most users it will not be obvious why there are fewer panels than they expected. For example, if I create a new dashboard with repeating panels for my 5 servers and there are only 3 panels repeated due to 2 of the servers having no data then it will not be obvious why.

**Comment by xginn8** [comment]
I think you'll also want to consider dropping panels with all null data or errors due to empty sequences.

**Comment by torkelo** [comment]
The basic requirement to hide panels with no data is well reasoned and appropriate. Just needs a lot of UX thought of how to make this feature usable and make the fact that the dashboard contains hidden panels more visible. 

closing this PR due lack of updates. We can update again if there are UX changes.

**Comment by martinler** [comment]
Hello, so is this feature present in some public version? Because it's prepared for few months, but not available for public, and i really would like to see this for my case as well.

**Comment by antonsoroko** [comment]
@martinler 
Hi.
We use this feature without problems. (Of course it would be reasonable to change UX to be more user-friendly, but...)

You can apply this commit to your fork - https://github.com/grafana/grafana/pull/7529/commits/f580783109be766a483cc454f27b5ceaf9d9ddc0 (or https://github.com/Altoros/grafana/commit/f580783109be766a483cc454f27b5ceaf9d9ddc0)

Or if you just want to take a look at this feature you can build grafana from this branch - https://github.com/Altoros/grafana/tree/add-suppressing-empty-panels

**Comment by martinler** [comment]
@antonsoroko 
Hi Anton,
noob question here - i would like to use your commits with current 4.6 release, it should work with your commits?
Thanks!

**Comment by antonsoroko** [comment]
@martinler 
Hi.
I have not tried to patch version 4.6.
I hope it would work :-)

**Comment by matemaciek** [comment]
Has this feature made it's way to Grafana 5?

**Comment by antonsoroko** [comment]
I don't think so.

**Comment by daixiang0** [comment]
Any update?
Does it merge to any release version?

**Comment by davebiffuk** [comment]
This would be a really handy feature to have, if anyone is able to include it?

**Pull request closed without merging**
