### PR TITLE
EmptyState: Apply `call-to-action` variant in core

### LINKED ISSUE #84515: Empty State [epic]
The empty state experience across Grafana could be better and definitely not consistent. We're looking to improve on this experience and tighten up the overall consistency.

1. Review existing empty state requirements and patterns
2. Create general best-fit versions to be implemented across the product
3. Pull together design explorations done by UXers to leverage any recent research
4. Build new components, include slim/full variations
5. Expand Grot illustration
6. Build Figma components to support
7. Create documentation for Saga to provide How-tos, when to, when not documentation

```[tasklist]
### Related work
- [ ] https://github.com/grafana/grafana/issues/84516
- [ ] https://github.com/grafana/grafana/issues/84517
```

### LINKED ISSUE #84516: Empty state components (dev)
internal design doc [here](https://docs.google.com/document/d/1EmjGm84SQtxrfi9qDreyWWAg0id8L-3B8pu5FQo3mMk/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/84891
- [ ] https://github.com/grafana/grafana/pull/85017
- [ ] https://github.com/grafana/grafana/pull/85007
- [ ] https://github.com/grafana/grafana/pull/86448
- [ ] https://github.com/grafana/design-system/pull/141
- [ ] https://github.com/grafana/grafana/pull/86497
- [ ] https://github.com/grafana/design-system/pull/143
- [ ] https://github.com/grafana/grafana/pull/86504
```

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- applies the EmptyState `call-to-action` variant in a bunch of places
- as a bonus, adds translations for a bunch of these strings 🥳 

| before | after |
| --- | --- |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

**Why do we need this feature?**

- better empty states!

**Who is this feature for?**

- everyone 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/84516
Fixes https://github.com/grafana/grafana/issues/84515

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by joshhunt** [comment]
Hmm. I don't think the info `<Alert />` box is the greatest, but not enough to block it.

I wonder if that content could be shortened and put in the EmptyState body instead?

image

**Comment by eledobleefe** [comment]
> Hmm. I don't think the info `<Alert />` box is the greatest, but not enough to block it.
> 
> I wonder if that content could be shortened and put in the EmptyState body instead?
> 
> image

Yeah, I'm not sure about this option either 🤔 
Otherwise, looks good 😉

**Comment by ashharrison90** [comment]
i'll put some options and tag dashboards squad for their opinion 👍

**Comment by ashharrison90** [comment]
some options below

# info alert below
image

# info alert above
image

# information inline
image

@eledobleefe @joshhunt @grafana/dashboards-squad which do you prefer? 🤔

**Comment by joshhunt** [comment]
Of these three options, I think I have a _slight_ preference for the third option of showing the full info in the EmptyState body.

However, upon merging I think the @grafana/dashboards-squad should take another look at this and edit the copy to shorten it, and link out to documentation for more details.

**Review by joshhunt — APPROVED** [review]

**Review by gillesdemey — COMMENTED** [review]
Alerting changes LGTM

**Review by gillesdemey — APPROVED** [review]

**Pull request merged**
