### PR TITLE
Docs: Sync docs with website repo via GitHub Action

### PR DESCRIPTION
**Pull request by robbymilo**
**What this PR does / why we need it**:
Adds a GitHub action that syncs any changes in the `docs/sources` directory with the website repo. 

Todo:
- [ ] Add `GH_PAT` - a Grafana Bot personal access token as a secret in this repo.

**Special notes for your reviewer**:
-https://github.com/grafana/grafana/pull/20693 Needs to occur first to bring the docs inline with the website.

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
What about the existing docs trigger in our circleci config, https://github.com/grafana/grafana/blob/master/.circleci/config.yml#L962-L989? Either remove that or change it and remove these changes.

**Comment by robbymilo** [comment]
Removed the `trigger-docs-update` job.

**Review by torkelo — COMMENTED** [review]
Looks good, but if we want to reuse this from multipe repos should the action itself not be in it's own repo?

**Comment by daniellee** [comment]
@robbymilo any thoughts on how to test this locally? Or how do you test it?

Is it worth trying to test it with a tool like [act](https://github.com/nektos/act)?

**Comment by robbymilo** [comment]
> Looks good, but if we want to reuse this from multipe repos should the action itself not be in it's own repo?

Yes, should we make a new repo under the grafana org?

**Comment by robbymilo** [comment]
> @robbymilo any thoughts on how to test this locally? Or how do you test it?
> 
> Is it worth trying to test it with a tool like [act](https://github.com/nektos/act)?

If you look here: https://github.com/grafana/website/pull/596 I have two example repos (source-repo and website-repo) where this is being used. Can also look into using act.

**Comment by torkelo** [comment]
> Yes, should we make a new repo under the grafana org?

Yes, but can't also wait until we add this to Loki and other repos.

**Comment by daniellee** [comment]
I thought I wrote a comment about Act but seems not to have been saved. It doesn’t have support for V2 of GitHub Actions so won’t be any use for this.

**Review by daniellee — APPROVED** [review]
LGTM

**Pull request merged**
