### PR TITLE
[v.8.0.x] Chore: Backport for missing tslib import

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉

**Comment by hugohaggmark** [comment]
Verified that this solves the tslib error but the branch of this PR is not based on the latest version of v8.0.x branch. Shouldn't matter though.

image

**Comment by joshhunt** [comment]
@hugohaggmark agree that it shouldn't matter, but i rebased this back to latest 8.0.x

able to be reverified now.

**Comment by hugohaggmark** [comment]
Thank you @joshhunt

**Comment by hugohaggmark** [comment]
Verified and correct base-branch 🙌  👍 
image

**Pull request merged**
