### PR TITLE
CloudMonitoring: switch from ApplyRoute to AuthMiddleware

### LINKED ISSUE #40786: Google: stop using ApplyRoute in CloudMonitoring
Part of #39907

Use grafana-google-go-sdk/tokenprovider.AuthMiddleware instead of ApplyRoute in the CloudMonitoring plugin.

### PR DESCRIPTION
**Pull request by iwysiu**
**What this PR does / why we need it**:
Changes the google cloud monitoring plugin to use Grafana-google-go-sdk/tokenprovider.AuthMiddleware instead of pluginproxy.ApplyRoute

**Which issue(s) this PR fixes**:

Fixes #40786 

**Special notes for your reviewer**:
- I hardcoded in the route settings from plugin.json in because I wasn't sure how to pull them in before the instance was done being created.

### CODE REVIEW

**Review by sunker — COMMENTED** [review]
Fantastic work on this! What an amazing improvement. And thanks for breaking out the utils into a separate file. 

Added a few minor comments that I think can simplify things a little bit. 

Did a quick test locally with jwt token auth, and it seems to work as expected. If possible you can do the following test just to make sure that new config is registered correctly. 
1. Create a new data source for CloudMonitoring and upload the JWT file you normally use.
2. Make sure it works to query data in the panel
3. Go to the data source config page and upload a new JWT file that has access to a different project in GCP (I'll DM you a file).
4. Go to the panel and make sure you can see query data for the new project

This should confirm that the data source receives new config when save is clicked in the data source config page, and also that this config is passed to the token provider correctly and the cache key is correct. I think :)

**Review by iwysiu — COMMENTED** [review]
I tested it with the jwt file and it works

**Review by andresmgot — APPROVED** [review]
LGTM! Just a minor comment from my side (I'll let @sunker do the final review).

**Review by andresmgot — APPROVED** [review]
:+1: thanks for the change.

**Review by sunker — COMMENTED** [review]
Just one nit :)

**Review by sunker — APPROVED** [review]
Great work!

**Pull request merged**
