### PR TITLE
Alerting: Separate overlapping legacy and UA alerting routes

### PR DESCRIPTION
**Pull request by JacobsonMT**
To facilitate upcoming feature flag and migration/upgrade page improvements, it's necessary to separate the shared legacy alerting and unified alerting routes / api endpoints. 

This renames the legacy routes/api's and keeps the UA ones the same, this should limit impact of unintentional problems. Changes:

- `api/alert-notifiers` -> `api/alert-notifiers-legacy`
  - The purpose of this api endpoint is to return the list of available integration types for notification channels.
- `alerting/list` -> `alering-legacy/list`
  - The is the route for the the main alert rules list view.
- `alerting/notifications` and various subpaths such as `/alerting/notifications/receivers/:id/edit` -> `alerting-legacy/...`
  - This is the route and sub-routes related to viewing and editing notification channels.

**Special notes for your reviewer:**

I don't think we reference the legacy routes and apis in the docs anymore, but if you know of a spot I can update it.

Extracted from: https://github.com/grafana/grafana/pull/76074

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by konrad147 — COMMENTED** [review]
Does legacy alerting generate any links in notification messages that might require updates?
I mean e.g. links in emails?

**Comment by JacobsonMT** [comment]
> Does legacy alerting generate any links in notification messages that might require updates? I mean e.g. links in emails?

Good question, only notification channels have deep links that would change with this PR, alert rules would link to the dashboard (which doesn't change in this PR). I wouldn't expect us to embed a deep link to the channel, but I'll fish around. Of course, if they manually add a link in the notification message it will break as well.

**Review by soniaAguilarPeiron — APPROVED** [review]
FE changes LGTM!🚀

**Review by konrad147 — APPROVED** [review]
FE LGTM!

**Comment by JacobsonMT** [comment]
deploy-to-hg

**Pull request merged**
