### PR TITLE
create annotation on non-editable dashboard

### PR DESCRIPTION
**Pull request by mtanda**
I'm not sure current behavior is intended...
If user has editor privilege, creating annotation is not problem, I think.

@daniellee Would you check this?

### CODE REVIEW

**Comment by daniellee** [comment]
Hi @mtanda I don't think this change is correct. 

If the user has edit permissions then they will be allowed to add an annotation. 

image

If the user has the editor role but an admin has changed the permissions so that they do not have edit access, then they cannot add annotations.

image

What problem are you seeing?

**Comment by mtanda** [comment]
@daniellee 
I often use file-based provisioned dashboard, which is not editable.
I want to add an annotation to `not editable` dashboard.

image

The annotation data table is separated from dashboard data table.
Whether dashboard is editable or not, adding dashboard should be allowed if the user has edit permission.

Actually, it is allowed in past version.
https://github.com/grafana/grafana/commit/3ae1bf0c16a9115203df38ec529979603f93a62b#diff-73b6d2d157efa75a5bf386d69674b2ffL669

But, now it is not allowed.
Holding ctrl + mouse drag select is not work.

**Comment by mtanda** [comment]
When using API, adding annotation is allowed.
UI should allow it too, I think.

**Comment by daniellee** [comment]
> Actually, it is allowed in past version.
3ae1bf0#diff-73b6d2d157efa75a5bf386d69674b2ffL669

It still is allowed. The only thing that has changed that the edit permission is checked instead of checking for the editor role.

> I want to add an annotation to not editable dashboard.

This doesn't work but it doesn't work for an admin either so I don't see how this PR will fix that. 

> When using API, adding annotation is allowed.

I agree, the UI and API should be the same.

I will test more tomorrow with a provisioned, read-only dashboard.

**Comment by daniellee** [comment]
@mtanda I don't understand the problem you are trying to fix with this PR and all it does it change the frontend code. There are two permissions checks, the one on the frontend and one on the backend.

1. Using your branch, I created a dashboard (in a folder) and gave the editor role, view rights:

image

2. Then I tried to create an annotation and got this error:

image

So you see when using the API, it is not allowed. The [guardian check] will not allow it: https://github.com/grafana/grafana/blob/master/pkg/api/annotations.go#L55

I don't see anything wrong - the permission system is working the way it should.

**Comment by mtanda** [comment]
@daniellee 

Hmm, sorry.
Do I misunderstand something, or my explanation is bad...

For API, admin user can add annotation to read only dashboard.
/ ------------------------------------------------------------------- /
https://gist.github.com/mtanda/610559f427b0073fe59c0c6f4a3996f3#file-gistfile1-txt-L167-L173
`meta.canEdit`=`true` => The admin user has priviledge for editing dashboard.
`dashboard.editable`=`false` => The dashboard itself is not editable.

https://gist.github.com/mtanda/610559f427b0073fe59c0c6f4a3996f3#file-gistfile1-txt-L180-L190
Then, try to add annotation.

https://gist.github.com/mtanda/610559f427b0073fe59c0c6f4a3996f3#file-gistfile1-txt-L193-L235
Success to add annotation.
/ ------------------------------------------------------------------- /

But, admin user cannot add annotation from Grafana Web UI.

The reason is following code overwrite `meta.canEdit=false` if `dashboard.editable=false`.
https://github.com/grafana/grafana/blob/v5.1.2/public/app/features/dashboard/dashboard_model.ts#L124

So, if the UI code check `meta.canEdit` value to add annotation, it never allowed if `dashboard.editable=false`.
https://github.com/grafana/grafana/blob/v5.1.2/public/app/plugins/panel/graph/graph.ts#L676

Directly calling API, admin can add annotation.
From UI, admin cannot add annotation, it still allowed, but UI doesn't show adding annotation popup...

**Comment by mtanda** [comment]
In another scenario.
User which has edit permission, can add annotation if `dashboard.editable=true`.
But, same user cannot add annotation after `dashboard.editable` becomes `false`.

**Comment by daniellee** [comment]
Sorry for being slow to understand. I missed that in dashboard_model.ts that canEdit is set to false if the dashboard is not editable.

It would be better if we did not go back to using `isEditor` as that does not follow the permissions system.

I think this would work:

```js
if ((ranges.ctrlKey || ranges.metaKey) && (dashboard.meta.canEdit || dashboard.meta.canMakeEditable)) {
```

Thanks for your patience!

**Comment by mtanda** [comment]
Sorry for my explanation is not enough too...
The suggested code work correctly. Change to use canMakeEditable.

**Comment by mtanda** [comment]
Thanks for merging!

**Pull request merged**
