### PR TITLE
Add common type for oauth authorization errors

### PR DESCRIPTION
**Pull request by amenzhinsky**
Since we have to maintain our own oauth adapter, we would like to return user-friendly authorization errors like the github adapter does, without changing the `api` package.

### CODE REVIEW

**Comment by DanCech** [comment]
This is looking good so far, but to be useful it will need some way to actually display the error messages, since right now the actual messages that are displayed are defined in [public/app/core/controllers/login_ctrl.js](https://github.com/grafana/grafana/blob/master/public/app/core/controllers/login_ctrl.js)

**Comment by amenzhinsky** [comment]
@DanCech, I thought of that, but didn't come up with anything better. 

Let's say we could redirect with the `errorMessage` parameter instead of the `errorCode` but this is not the best solution because messages can get really long and they cannot be I18ned in the future.

Any ideas?

**Comment by DanCech** [comment]
We definitely don't want to do that, since it opens the door to phishing attacks using that parameter to place a random message onto the login screen (it used to work that way before the login codes).  We might be able to leverage the session so the oath provider can place the message into a session variable then redirect the user back to /login.

Now that the state variable is being used, it would actually be relatively safe to support displaying error messages returned by the provider as long as the redirect includes a valid state var, since a potential attacker wouldn't know that value.  Those would still have to go through the session to make their way from the oauth return url back to /login though.

**Comment by amenzhinsky** [comment]
@DanCech probably session flash messages is a good idea

**Comment by amenzhinsky** [comment]
@DanCech done, please have a look

**Comment by DanCech** [comment]
Hmm, I'm not sure whether there are existing mechanisms that can be leveraged for this rather than using angular-cookie.  @torkelo might have some input.

**Comment by torkelo** [comment]
yea, think this needs some refactoring

**Comment by amenzhinsky** [comment]
@torkelo could you clarify what kind of refactoring?

**Comment by amenzhinsky** [comment]
@torkelo I wasn't able to find cookies management mechanisms, that's why I added angular-cookies since the project uses angularjs.
I do not understand what kind of refactoring is needed, could you be more precise?

Thanks in advance.

**Comment by torkelo** [comment]
what are you using cookies for? maybe local storage could be an alternative?

**Comment by DanCech** [comment]
Don't we have a server-side session we can use?

**Comment by torkelo** [comment]
yes

**Comment by amenzhinsky** [comment]
@torkelo I pass error messages from backend to frontend, thus local storage is not an option.

**Comment by amenzhinsky** [comment]
@DanCech js code doesn't have access to server-side session because they're usually encrypted.

**Comment by torkelo** [comment]
the way that is usually solved is with Flash storage (term used by MVC libs), storage that lives temporarily between 2 requests (ex redirects). Normally the flash is stored in sessions, and removed after first fetch (the second request)

**Comment by amenzhinsky** [comment]
@torkelo I do understand how sessions work but we cannot use the same approach here, since pages are not rendered on the server we cannot embed them in html code. 

We need something that works on both sides: server and the sp js application.

**Comment by torkelo** [comment]
after redirect the message can then be passed to frontend code via https://github.com/grafana/grafana/blob/master/pkg/api/login.go#L34

**Comment by amenzhinsky** [comment]
Thanks! That's I needed

**Comment by amenzhinsky** [comment]
@torkelo by some reason github doesn't pull up changes made to the same branch, so I'm closing this one. Please have a look at #6428

**Comment by amenzhinsky** [comment]
I'm sorry, #7426

**Pull request closed without merging**
