### PR TITLE
NewPanelEdit: Experimenting with tabs in the sidebar

### PR DESCRIPTION
**Pull request by dprokop**
Playing with another layout for options sidebar in new panel editor

This PR also adds general settings of the panel (description, links, title etc) as a separate tab. 

cc @sarlinska @jessover9000  if you wanna test it out :)

### CODE REVIEW

**Comment by torkelo** [comment]
after the last merge this no longer works, crashes for bar gauge at least

**Comment by dprokop** [comment]
ah shit, gonna look in a sec

**Comment by dprokop** [comment]
@torkelo forgot to push merge fixes, check it out now

**Comment by dprokop** [comment]
ah, still not, fixin now

**Comment by dprokop** [comment]
@torkelo you can check it out now. Been using fieldOptions instead of fieldConfig and haven't updated the reference after master merge

**Comment by ryantxu** [comment]
@dprokop -- I looked at this with torkel. looks good -- separating defaults & overrides really helps.

"Custom" is awkward and I think that should be included at the top of the "defaults" section

**Comment by torkelo** [comment]
looking good. Pushed some updates. 

Think we should only have 3 tabs, as I think the difference between field level settings and panel settings will be very hard for users to understand I am afraid. 

So I think panel options should live at the top next field defaults.

**Comment by dprokop** [comment]
> "Custom" is awkward and I think that should be included at the top of the "defaults" section

@ryantxu agree with that, it felt wrong. I mean, not sure if it's the naming, but having those uptions under defaults is OK!

**Comment by ryantxu** [comment]
We should also change "defaults" tab to something else... but not sure what!  Likely either "settings" or "options"

then somewhere in the text/docs structure explain how the settings are really default setting unless defined elsewhere

**Comment by dprokop** [comment]
"Defaults" are now options.

Also added the panel options below the defaults

**Comment by dprokop** [comment]
@torkelo the "legacy" panel options are now shown in a vertical layout in the sidebar. Hacky, but we cannot remove legacy class names :/

**Comment by dprokop** [comment]
Btw the icons in the bottom tabs look cool Torkel!

**Comment by ryantxu** [comment]
> Also added the panel options below the defaults

I would think *above* makes more sense

UGLY for old panels... but I think it makes more sense

**Comment by dprokop** [comment]
> UGLY for old panels... but I think it makes more sense

yeah, was thinking about this, but... I think it's nice that the common defaults are always shown in the same position. Not sure, will bring this up on our sync with UX tomorrow.

**Comment by torkelo** [comment]
Looking better, think we need a way to not show (hide) field configs settings for angular panels. think the outer "Common options", And "Panel Option" groups can be removed as they cause some nesting (panel option groups inside panel option groups (see react table).)  And I think we might want to use the options groups inside legacy panels like angular to make the options easier to find

**Review by torkelo — APPROVED** [review]
Looks good to merge

**Pull request merged**
