### PR TITLE
Docs: RBAC update for insights and query caching

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Adds the permissions and roles added for query caching and insights features.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gamab — COMMENTED** [review]
Looks good. Are there some endpoints impacted? We tend to list the `required permissions` in the API docs as well. [Example with data sources](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#get-all-data-sources)

Nit. I think `dashboards.insights` should go before `dashboards.permissions`, `datasources.caching` before `datasources.id`, `datasources.insights` before `datasources.permissions` in the tables as someone has ordered alphabetically.

**Review by IevaVasiljeva — COMMENTED** [review]
Looks good apart from what Gabriel mentioned.

I know that Agnes is off for a while. Should one of us pick this PR up and make the changes or are you fine dealing with it @grafana/administration-experience-squad?

**Comment by joanlopez** [comment]
> Looks good apart from what Gabriel mentioned.
> 
> I know that Agnes is off for a while. Should one of us pick this PR up and make the changes or are you fine dealing with it @grafana/administration-experience-squad?

I can take care of it! Thanks for the input! :)

**Review by IevaVasiljeva — APPROVED** [review]
Looks good to me! Sorry for not reviewing this sooner!

**Review by gguillotte-grafana — APPROVED** [review]

**Pull request merged**
