### PR TITLE
DevEnv: update frontend dependencies - mixed 1/2

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 12 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `husky` - changes (1.3.1 -> 4.2.1): https://github.com/typicode/husky/releases
- `lint-staged` - changes (8.1.5 -> 10.0.7): https://github.com/okonet/lint-staged/releases
- `monaco-editor` - changes (0.15.6 -> 0.19.6): https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md

Changes - less significant:
- `rimraf` - changes (2.6.3 -> 3.0.1): https://github.com/isaacs/rimraf/blob/master/CHANGELOG.md
- `@emotion/core` - changes (10.0.10 -> 10.0.27): https://github.com/emotion-js/emotion/blob/master/packages/core/CHANGELOG.md
- `autoprefixer` - changes (9.5.0 -> 9.7.4): https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md
- `axios` - changes (0.19.0 -> 0.19.2): https://github.com/axios/axios/blob/master/CHANGELOG.md
- `es6-promise` - changes (3.3.1 -> 4.2.8): https://github.com/stefanpenner/es6-promise/blob/master/CHANGELOG.md
- `lerna` - changes (3.15.0 -> 3.20.2): https://github.com/lerna/lerna/blob/master/CHANGELOG.md
- `postcss-browser-reporter` - changes (0.5.0 -> 0.6.0): https://github.com/postcss/postcss-browser-reporter/blob/master/ChangeLog.md

### CODE REVIEW

**Comment by torkelo** [comment]
Since this updated the monaco editor we need to test this with the Azure data source (think azure logs query editor is using monaco). 

Or @daniellee did we update that to slate?

**Comment by daniellee** [comment]
We updated to using Slate so I think you can just remove the Monaco dependency.

**Comment by daniellee** [comment]
@Estrax anything else you are stuck on? Do you want me to test this branch?

**Comment by Estrax** [comment]
@daniellee I made changes yesterday but forgot to push it. The monaco rollback is going to be there in up to few mins. For the review and test I'll ping @tskarhed and @peterholmberg.

**Comment by torkelo** [comment]
Problems in the lock file in CI so can't merge this

**Comment by dprokop** [comment]
@Estrax can you sync this with master, and I think we should be good to merge?

**Comment by Estrax** [comment]
@dprokop Synced!

**Review by dprokop — APPROVED** [review]

**Pull request merged**
