### PR TITLE
Add missing `deps-go` target to `deps`

### PR DESCRIPTION
**Pull request by simPod**
I think the target for go deps was missing.

### CODE REVIEW

**Comment by marefr** [comment]
This commit (https://github.com/grafana/grafana/commit/3c0f61511d5ecd3d436e829c6628179bba0faa43) removed it 3 years ago. Something changed since then you think?

**Comment by aknuds1** [comment]
@marefr The original reasoning for removing it makes sense. There's probably no need to revert that change?

**Review by aknuds1 — COMMENTED** [review]
Considering the original reasoning for not including `deps-go` among the dependencies of the `deps` target I guess this PR doesn't make sense.

**Comment by simPod** [comment]
Ok, I did not search the history for removal, I thought it was a bug as go dependencies are still dependencies, therefore -> `deps`. 

Don't know how it works on your side but for me grafana often does not compile without updating dependencies 🤔

**Comment by aknuds1** [comment]
@simPod How do you need to update dependencies in order to compile Grafana Go code exactly?

**Comment by simPod** [comment]
@aknuds1 I use to run `make all` to install deps and build.

**Comment by aknuds1** [comment]
@simPod

1. How does it fail if you don't update dependencies
2. How do you update dependencies so it doesn't fail?

**Comment by simPod** [comment]
@aknuds1 TBH don't know, how to reproduce. Especially, I'm not friend with go ecosystem that much.

Often go compile error occurs, with failure on some dependencies (I often work with different Grafana versions). Running `deps-go` fixes the issue then.

Maybe the target naming is confusing then? If it is not related, `deps-js` `deps-go` and `deps` should be somehow distinguished.

**Comment by aknuds1** [comment]
I don't really know what you're doing, but it it's not necessary to install dependencies in order to compile Go code. The Go compiler fetches dependencies as necessary itself.

**Comment by simPod** [comment]
Ok, if the current state is ok with you let's close this. I can reopen when I encounter the issue. Thanks!

**Pull request closed without merging**
