### PR TITLE
AzureMonitor: Alphabetically sorted variables

### PR DESCRIPTION
**Pull request by JohnJMartins**
**What this PR does / why we need it**: Configures variable edit pages on grafana dashboards to automatically alphabetically sort the listed value previews.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by andresmgot** [comment]
Hi @JohnJMartins, sorry for the late response. Some questions/requests here:

 - Can you sign the CLA?
 - What's the benefit of sorting these variables in alphabetical order (vs using the order the Azure API returns)?
 - Can you merge the latest state of main into this PR to fix CI issues?
 
 Thanks for the contribution!

**Comment by JohnJMartins** [comment]
@andresmgot Sorry for the late reply as well. I have signed the CLA and merged the latest main. In this PR, sorting variables alphabetically (ignored upper/lowercase) simply makes it easier for users to find the specific variable value they are looking for in the list. This is a process that can sometimes be time-consuming when there is a long list of retrieved variable values and/or the values are long strings of letters and numbers.

**Comment by andresmgot** [comment]
It seems that the CLA is not properly detected as signed:

> **John Martins** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

It may be because the initial commits where commited by "John Martins" and the others by "JohnJMartins" (a valid GitHub user). It may be fixed if you squash your commits, verifying that the email configured in `git` is the one matching your GitHub account.

**Review by andresmgot — APPROVED** [review]
LGTM, thanks

**Pull request merged**
