### PR TITLE
Alerting: Fix a typo in alerting rule annotation docs

### PR DESCRIPTION
**Pull request by theneva**
**What this PR does / why we need it**:

It fixes what I think is a typo in the docs.

**Which issue(s) this PR fixes**:

No issue, I just encountered it while reading the docs.

~Fixes #~

**Special notes for your reviewer**:

I think this makes sense, but I was reading the docs to learn, so I'm not an expert :sweat_smile:

### CODE REVIEW

**Comment by theneva** [comment]
I, uh, I don't think I have access to see the build output for the `Enterprise PR check / dispatch (pull_request)` action, so I don't know what's wrong. Please point me in the right direction and I'll be happy to fix it :smile:

**Review by brendamuir — APPROVED** [review]

**Comment by brendamuir** [comment]
Hi! It's ok if that fails-feel free to merge!

**Comment by theneva** [comment]
Cool, thanks! I don't think I'm authorised to merge myself, or maybe I misunderstood? 😅

**Comment by brendamuir** [comment]
:) Done!

**Pull request merged**
