### PR TITLE
Bump github.com/grafana/grafana-plugin-sdk-go to v0.260.1

### PR DESCRIPTION
**Pull request by ivanahuckova**
This PR bumps github.com/grafana/grafana-plugin-sdk-go to v0.260.1.

### CODE REVIEW

**Comment by ivanahuckova** [comment]
I am not sure why these are failing. I have run `make update-workspace` and it [added some changes](https://github.com/grafana/grafana/pull/97329/commits/ae9646b21ef2f741ba32dc1d367a7405da16d9fd), but the check is still failing and whenever I run it again, no changes are added. It is not required check, so I am not sure if we can just ignore, or if someone knows how to fix.
image

**Comment by andresmgot** [comment]
I am getting the same differences than the GH action:

```patch
--- a/go.sum
+++ b/go.sum
@@ -2326,6 +2326,7 @@ github.com/grafana/grafana-openapi-client-go v0.0.0-20231213163343-bd475d63fb79
 github.com/grafana/grafana-openapi-client-go v0.0.0-20231213163343-bd475d63fb79/go.mod h1:wc6Hbh3K2TgCUSfBC/BOzabItujtHMESZeFk5ZhdxhQ=
 github.com/grafana/grafana-plugin-sdk-go v0.114.0/go.mod h1:D7x3ah+1d4phNXpbnOaxa/osSaZlwh9/ZUnGGzegRbk=
 github.com/grafana/grafana-plugin-sdk-go v0.260.1 h1:KzbooQP9mv/9CPsn+SoUwGuomA8oUxO0iuIq6Rg/ekE=
+github.com/grafana/grafana-plugin-sdk-go v0.260.1/go.mod h1:JriieK5Oc5v120QKhMs/LO55N0P3YI2ttEiVT1wfYsw=
 github.com/grafana/grafana/apps/playlist v0.0.0-20241105090059-facca37f4d1f h1:zZN/Jy7PjoqtrMiBRV5O3x4xAArcSbUznuyAPACrKXI=
 github.com/grafana/grafana/apps/playlist v0.0.0-20241105090059-facca37f4d1f/go.mod h1:e97Zxn1WX4Wn9TXEvwTjMNwU6yrjX/K7uVNSCZyEwxY=
 github.com/grafana/grafana/pkg/aggregator v0.0.0-20240813192817-1b0e6b5c09b2 h1:2H9x4q53pkfUGtSNYD1qSBpNnxrFgylof/TYADb5xMI=
@@ -3225,6 +3226,7 @@ github.com/stretchr/testify v1.8.3/go.mod h1:sz/lmYIOXD/1dqDmKjjqLyZ2RngseejIcXl
 github.com/stretchr/testify v1.8.4/go.mod h1:sz/lmYIOXD/1dqDmKjjqLyZ2RngseejIcXlSw2iwfAo=
 github.com/stretchr/testify v1.9.0/go.mod h1:r2ic/lqez/lEtzL7wO/rwa5dbSLXVDPFyf8C91i36aY=
 github.com/stretchr/testify v1.10.0 h1:Xv5erBjTwe/5IxqUQTdXv5kgmIvbHo3QQyRwhJsOfJA=
+github.com/stretchr/testify v1.10.0/go.mod h1:r2ic/lqez/lEtzL7wO/rwa5dbSLXVDPFyf8C91i36aY=
 github.com/subosito/gotenv v1.4.1/go.mod h1:ayKnFf/c6rvx/2iiLrJUk1e6plDbT3edrFNGqEflhK0=
 github.com/subosito/gotenv v1.6.0 h1:9NlTDc1FTs4qu0DDq7AEtTPNw6SVm7uBMsUCUjABIf8=
 github.com/subosito/gotenv v1.6.0/go.mod h1:Dk4QP5c2W3ibzajGcXpNraDfq2IrhjMIvMSWPKKo0FU=
@@ -3740,6 +3742,7 @@ golang.org/x/oauth2 v0.17.0/go.mod h1:OzPDGQiuQMguemayvdylqddI7qcD9lnSDb+1FiwQ5H
 golang.org/x/oauth2 v0.18.0/go.mod h1:Wf7knwG0MPoWIMMBgFlEaSUDaKskp0dCfrlJRJXbBi8=
 golang.org/x/oauth2 v0.19.0/go.mod h1:vYi7skDa1x015PmRRYZ7+s1cWyPgrPiSYRe4rnsexc8=
 golang.org/x/oauth2 v0.24.0 h1:KTBBxWqUa0ykRPLtV69rRto9TLXcqYkeswu48x/gvNE=
+golang.org/x/oauth2 v0.24.0/go.mod h1:XYTD2NtWslqkgxebSiOHnXEap4TF09sJSc7H1sXbhtI=
 golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
 golang.org/x/sync v0.0.0-20181108010431-42b317875d0f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
 golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
 ```
 
I usually need to run the `make` task twice to get the final result but if you have already done that maybe it's because of the go version or something similar. Mine is `go version go1.23.1 darwin/arm64` fwiw.
 
 If you get stuck, you can always manually edit the file (just the go.sum) and push it.
 
 Regarding the Trivy error, we may ignore it here but we probably want to update it. I see @zserge did it [last time](https://github.com/grafana/grafana/pull/92857/), not sure who is the owner of that.

**Comment by ivanahuckova** [comment]
>I usually need to run the make task twice to get the final result but if you have already done that maybe it's because of the go version or something similar. Mine is go version go1.23.1 darwin/arm64 fwiw.

Yeah, I run it couple times and no difference. Also my go version is the same  go1.23.1 darwin/arm64. 

> If you get stuck, you can always manually edit the file (just the go.sum) and push it.

@andresmgot I don't have experience with workspaces, so not sure how/what to edit. Would you mind sharing more, or even pushing a commit if it would be less work for you.

**Comment by andresmgot** [comment]
there you go, there was also a conflict with main

**Review by andresmgot — APPROVED** [review]

**Pull request merged**
