### PR TITLE
Allow unescaped strings in tables, closes #4596

### LINKED ISSUE #4596: [bug]/ Annotation in table panel are not clickable anymore
* What grafana version are you using? grafana beta 3
* What datasource are you using? graphite
* What OS are you running grafana on? centos 6

Ok Now i can see my events in table since last fix.

But in grafana 2.6 the html link was interpreted and clickable:

Now i can't do this anymore

image

In previous 2.6 :: i got ::

image

### PR DESCRIPTION
**Pull request by bobrik**
I've used some of previous work from @bergquist. Hopefully it's ok.

image

### CODE REVIEW

**Comment by torkelo** [comment]
not sure escape is the right approach, think we should run it through the sanitizer to prevent js attacks

**Comment by bobrik** [comment]
@torkelo I build urls to drill-down dashboards for each row, how is it going to work with sanitizer?

Right now it's:

```
<a href="/dashboard/db/foo?var-app={{ app }}">{{ app }}</a>
```

**Comment by torkelo** [comment]
The sanitizer  will allow anchor tags and some other simple tags (and filter out script tags etc) 

what are the `{{ app }}` in you table cell value? where is that interpolated/evaluated ?

**Comment by bobrik** [comment]
Prometheus metrics look like `foo_bar_cpu_time{app="myapp"}`, table looks like this:

| App     | CPU usage |
|---------|-----------|
| myapp   | 10%       |
| example | 936%      |

Here myapp and example link to drill-down dashboards.

**Comment by torkelo** [comment]
ok, not sure I understand where the data for the table is coming from and where  `{{ app }}` is interpolated. The table panel does not support drill down links in the table cells.

**Comment by bobrik** [comment]
> The table panel does not support drill down links in the table cells.

Yes, because html is not allowed. It worked before.

Hopefully this will help you understand what I'm doing:

image

image

**Comment by torkelo** [comment]
ok, so it's a legend format and the cell text does not actually contain `{{ app }}` .

**Comment by bobrik** [comment]
```
<a href="/dashboard/db/foo?var-app={{ app }}">{{ app }}</a>
```

It does contain `{{ app }}` (well, `{{ marathon_app_id }}` to be fair).

**Comment by torkelo** [comment]
I think the table panel should allow unescaped html. What could be allowed is sanitized html (to allow links etc)

**Comment by bobrik** [comment]
I don't follow. This is exactly what I did:

> I think the table panel should allow unescaped html.

**Comment by torkelo** [comment]
Yes, but not script tags and all html, only specific allow tags, that is what sanitize html means

**Pull request closed without merging**
