### PR TITLE
fix duplicate tag value suggestions and relax limit on /api/search/lookup

### PR DESCRIPTION
**Pull request by Dieken**
This fixes issue https://github.com/grafana/grafana/issues/2749.

### CODE REVIEW

**Comment by Dieken** [comment]
Glanced at the build log, seems not my fault....

**Comment by torkelo** [comment]
why is OpenTSDB returning duplicates?

**Comment by Dieken** [comment]
I gave an example response in #2749, maybe not so obvious;-)

The lookup api returns tagk and tagv pairs for some TSUIDs of a metric name, notice different TSUIDs have some same tag kv pairs(not bug, it's natural). Grafana collects all tag values for all TSUIDs so duplication happens, better to fixe on Grafana side before OpenTSDB provides a better suggestion API.

**Comment by Dieken** [comment]
This is really not a bug on OpenTSDB side, could you merge this two lines change?  I hate to maintain own fork for very small fix :-)

**Pull request merged**
