### PR TITLE
i18n: Markup `QueryEditor` for translations 

### PR DESCRIPTION
**Pull request by aditipatelpro**
**What is this feature?**

This PR adds support for i18n in one of the `Explore` components. This PR targets the `QueryEditor` component.

**Why do we need this feature?**

To add support for i18n in the `QueryEditor` component.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes a part of #73984 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by aditipatelpro** [comment]
hi @ifrost, I am trying to add i18n in a few components, namely

1.  [public/app/features/plugins/sql/components/QueryHeader.tsx](https://github.com/grafana/grafana/blob/6bea937bc12062645749615a588585a824d59ca3/public/app/features/plugins/sql/components/QueryHeader.tsx)
2. [public/app/features/plugins/sql/components/TableSelector.tsx](https://github.com/grafana/grafana/blob/6bea937bc12062645749615a588585a824d59ca3/public/app/features/plugins/sql/components/TableSelector.tsx)
3. [public/app/features/plugins/sql/components/visual-query-builder/SelectRow.tsx](https://github.com/grafana/grafana/blob/6bea937bc12062645749615a588585a824d59ca3/public/app/features/plugins/sql/components/visual-query-builder/SelectRow.tsx)

However, I am failing to import `t` and `Trans` from `app/core/internationalization` due to the `no-restricted-imports` rule implemented in `public/app/features/plugins/sql/.eslintrc`

> `{
>   "rules": {
>     "no-restricted-imports": [
>       "error",
>       {
>         "patterns": ["app/*"]
>       }
>     ]
>   }
> }`

Let me know if there is any workaround for the imports in these files.

**Comment by aditipatelpro** [comment]
@ifrost, Can you please guide me in importing internationalization modules in the components I listed above?

**Comment by ifrost** [comment]
Hey @aditipatelpro! Thanks for another submission.

Sorry, we won't be able to fully translate everything yet because of some work to extract/refactor some plugin code in the core. The eslint rule that is failing was added to make that work easier. The rule will be kept until the rework is done. Util then we are not able to add translation support to plugin files (anything under `/features/plugins`)

**Comment by aditipatelpro** [comment]
> Hey @aditipatelpro! Thanks for another submission.
> 
> Sorry, we won't be able to fully translate everything yet because of some work to extract/refactor some plugin code in the core. The eslint rule that is failing was added to make that work easier. The rule will be kept until the rework is done. Util then we are not able to add translation support to plugin files (anything under `/features/plugins`)

@ifrost, Thanks for letting me know. Should I keep this PR open until the refactoring is done?

**Comment by ifrost** [comment]
> @ifrost, Thanks for letting me know. Should I keep this PR open until the refactoring is done?

This may take a while so probably better to close it.

**Pull request closed without merging**
