### PR TITLE
Alerting: adds additional command palette actions

### PR DESCRIPTION
**Pull request by gillesdemey**
**What this PR does / why we need it**:

This PR adds additional alerting navigation items to the command palette and fixes a small bug that prevents some navigation actions from showing up.

https://user-images.githubusercontent.com/868844/175574532-85b93176-6f8c-4873-a12e-1da9d9bf1c90.mp4

**Special notes for your reviewer**:

I got confused initially about why the alerting command wouldn't show up and I traced it down to a bug where we assert what navigation commands are available based on the items in the `navBarTree`. 

We'd previously do an URL path comparison (using `===`) but we should be checking instead if the `navBarTree` item's URL starts with the URL we defined on the navigation command since alert's URL is `/alerting/list` instead of `/alerting`.

### CODE REVIEW

**Comment by gelicia** [comment]
@gillesdemey did you test this with some finer grained access control configurations? like for example, you have permission to read alerting, but not alerting notifications, I'd be interested in knowing if alerting notifications shows up on the command palette. I'm going to look into a better source of permissions than what shows in the nav bar since that won't scale as we add more than just the main sections of grafana to the action list

**Comment by gillesdemey** [comment]
Great point, I haven’t tested this with RBAC yet but my thinking is that it will show you items you don’t have access to because we don’t check if we can access any child navigation items from the sidebar 🤔

**Comment by gelicia** [comment]
> we don’t check if we can access any child navigation items from the sidebar
Fixed! Let me know what you think of this solution.

**Comment by gillesdemey** [comment]
> Fixed! Let me know what you think of this solution.

Much nicer! 🥳

**Comment by gelicia** [comment]
@Elfo404 - I know you looked at the original permissions related things with the command palette.. Could you review this change where we flatten the nav tree to get all the URLs out to make sure nothing jumps out at you as wrong?

**Review by Elfo404 — APPROVED** [review]
Took this for a ride and everything looks good. 👍 
AFAICT there should be no issues with permissions  in this case (also with RBAC enabled) since - as a user with no alerting permissions - i can still navigate to all the pages in the navbar, i just won't see any data or be able to perform any action i don't have permission for. And we are not adding the "admin" and "create rule" pages to the command palette anyway, which are the only dynamic ones in the navbar.

disabling alerting (which removes everything from the navbar) also makes all alerting related commands disappear.

**Pull request merged**
