### PR TITLE
Variables: fixes so single value picker closes dropdown on select

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Relates #22564

**Special notes for your reviewer**:

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
LGTM

**Comment by hugohaggmark** [comment]
This fix (maybe) stresses the need for 2 separate components, one for single value variables and one for multi value variables. I think this would further reduce complexity. Your thoughts @torkelo @mckn?

**Comment by mckn** [comment]
> This fix (maybe) stresses the need for 2 separate components, one for single value variables and one for multi value variables. I think this would further reduce complexity. Your thoughts @torkelo @mckn?

I agree, lets split them up!

**Comment by hugohaggmark** [comment]
> > This fix (maybe) stresses the need for 2 separate components, one for single value variables and one for multi value variables. I think this would further reduce complexity. Your thoughts @torkelo @mckn?
> 
> I agree, lets split them up!

But not in this PR I think, right?

**Pull request merged**
