### PR TITLE
Dashboard: Add Duplicate dashboard links button to links list

### PR DESCRIPTION
**Pull request by Hmerac**
**What this PR does / why we need it**: This PR allows users to duplicate individual `Dashboard Links` to work faster. I wish this feature was already implemented when I was creating `Dashboard Links `for all regions that we have deployments in. Pressing `New` button and copy-pasting each textbox was quite a burden. With this feature, users can easily duplicate the links and change only the needed/required areas. For example: region parts of the URL, title...

Screenshot 2020-07-25 at 17 21 47

**Which issue(s) this PR fixes**: _None of the existing ones_

**Special notes for your reviewer**: First contribution :) ~I wasn't really sure which button type to use. I've decided `repeat` is the most appropriate, although `copy` also looks appropriate.~ Changed to `copy`.

### CODE REVIEW

**Comment by torkelo** [comment]
Please use same icons & buttons as the variables list

**Review by torkelo — CHANGES_REQUESTED** [review]
Needs to look the same as variables list (That also has duplicate button)

**Comment by Hmerac** [comment]
> Needs to look the same as variables list (That also has duplicate button)

I believe the button types in the screenshot is what you meant:

Screenshot 2020-07-26 at 20 46 12

**Review by torkelo — APPROVED** [review]
Looks good, thanks for contributing ❤️

**Pull request merged**
