### PR TITLE
Gauges

### PR DESCRIPTION
**Pull request by keis**
WIP PR to add a gauge option to singlestat. Based on the work of @utkarshcmu but that branch sadly is a bit outdated after some refactoring.
- [x] I would like to it make a bit more configurable
- ~~and have dynamic min/max values~~
- [x] grafana look and feel, colors etc

The second part I have no idea how to approach and ideally the max should be possible to source from a different metric

### CODE REVIEW

**Comment by utkarshcmu** [comment]
@keis Great work !!! 

Please add this line in "$GRAFANA_HOME/public/test/test-main.js" file under **paths**:
```
"jquery.flot.gauge": "vendor/flot/jquery.flot.gauge"
```
to fix the above circleci / grunt test failure. :)

**Comment by keis** [comment]
Thanks, that fixed it. I'll get on CLA but I guess I have to involve the legal department of $employer but it should only be a formality.

**Comment by skundrik** [comment]
@keis Do you have any eye candy (pictures) of what they look like?

**Comment by keis** [comment]
Basically the only thing you can change for now is the threshold colour

gauge

**Comment by bergquist** [comment]
I'm not sure about adding this to Grafana core or the single stat panel. I think it belongs in https://github.com/grafana/panel-plugin-piechart don't you?

**Comment by keis** [comment]
I guess having it as external plugin would work but I'll leave that call to you.

It should not be bundled with the piechart because it really has nothing to do with that. But I guess something like panel-plugin-gauge could work

**Comment by skundrik** [comment]
@keis Looks nice

**Comment by mattttt** [comment]
I'd like to see the gauge as its own plugin (panel-plugin-gauge) instead of bundled with a single stat or pie. 

:+1:

**Comment by utkarshcmu** [comment]
+1 for gauge

**Comment by keis** [comment]
I've started to work on splitting this out to new repo but I'll leave this pr open to allow further discussion.

Btw is there some directory of grafana plugins available? A github search does not turn up a lot and mostly backend plugins

**Comment by utkarshcmu** [comment]
@keis Can you please pull new version of jquey.flot.gauge? There was a bug I opened a while back with it, which is fixed now. 
https://github.com/toyoty99/flot.gauge/issues/1

**Comment by utkarshcmu** [comment]
@keis Awesome work in this PR !!!

**Comment by keis** [comment]
New code is available at https://github.com/keis/panel-plugin-gauge/tree/gauge-panel

**Comment by torkelo** [comment]
interested in merging this, can you sign the CLA? https://cla-assistant.io/grafana/grafana?pullRequest=3688

**Comment by keis** [comment]
I pinged legal about this and they said it looked fine but wanted to check something, should hear back from them this week.

However if doing this as a plugin instead I guess that's not really needed anymore :)

**Comment by torkelo** [comment]
thinking that this kind of makes sense as a feature in the singlestat panel

**Comment by keis** [comment]
I'm fine with whatever really. If going the singelstat route I have a few small patches to bring over.

One that is perhaps a bit problematic where I started treating the second series as the Max value of the gauge to be able to do things like showing used resources out of some dynamic total resources.

**Comment by mattttt** [comment]
Couple remarks (not to overcomplicate):

There is existing demand for adding images into singlestat currently ( https://github.com/grafana/grafana/issues/1999). If we include gauge in the core singlestat panel, need to think about how the configuration will grow.


Also, other issues referenced with this PR:
 - SingleStat support more shape styles https://github.com/grafana/grafana/issues/1351
 - Support for drawing Gauges https://github.com/grafana/grafana/issues/129

**Comment by keis** [comment]
Ok, Finally got around to pressing that button :cat: 

Comparing the two versions of this code there is a lot of options from singlestat that don't really make sense for the gauge (e.g sparkline and background coloring) and some that could be implemented but I don't really see the value in (font size, prefix and suffix). However not having those work would be confusing.

**Comment by herveleclerc** [comment]
+1 for gauge

**Comment by torkelo** [comment]
@keis did some refactoring / merge against master, here https://github.com/grafana/grafana/commit/4b9836bffe04afa3b0edfc466489ffbcbfe32c9b 

Can update this PR from that branch? Also the position and size seems work very poorly, it it too small for the panel and to far down

**Comment by keis** [comment]
Sure, merged!

also updated jquery.flot.gauge to the upstream version

**Comment by RichiH** [comment]
I am late to the game, but I think having a new type of Panel type in addition to Graph, Singlestat, etc makes more sense going forward.

Having a second, and possibly third, metric to get dynamic thresholds from will be very useful.

Is there any chance of this being merged a day or three before FOSDEM? If yes, expect to see it used on a publicly accessible dashboard during FOSDEM :)

**Comment by keis** [comment]
Got the size situation improved by sending in the full width/height and disabling a label that the gauge canvas was trying to draw

**Comment by bergquist** [comment]
Dynamic thresholds seems like an interesting idea. But lets stay with statically defined tresholds with this pr :)

**Comment by utkarshcmu** [comment]
@bergquist Can we get a new repo for this as panel-plugin-gauge? Then we can see the issues related to gauges and can fix them. Thanks. :)

**Comment by keis** [comment]
Rebased on master but a bit broken right now because the editor does not load.

**Comment by keis** [comment]
Got the editor working again. Also broken on master so you might want to cherry pick ff834c6e316bd10767fd5bcde377c404573cbd31.

However the rendering also seems more broken than before after the rebase

**Comment by originalrecipe** [comment]
Oh wow this is amazing! This would be a great addition to Grafana's core.

**Comment by utkarshcmu** [comment]
@keis do u think we chose the wrong library for drawing gauges? I know you have put in a lot of effort in building this pmel. But should we look for any other option for drawing gauges instead of float based lib? Or you think we can make it stable?

**Comment by keis** [comment]
@utkarshcmu In retrospect it would have made more sense to roll some arc drawing by hand even. But except for the outstanding issue with the labels I think it looks pretty stable now.

**Comment by keis** [comment]
Rebased again. @torkelo any chance of getting this basic version merged to ease keeping up with all the changes going on in master?

**Comment by RichiH** [comment]
@keis Do you have a screenshot of what you have working, now?

Also, do you have any interest in developing gauges into something that could replace a [weathermap](https://www.google.de/search?q=weathermap&source=lnms&tbm=isch)?

**Comment by keis** [comment]
@RichiH more or less the same as the earlier screendump

gauge

No idea how it would replace a weathermap but my interest is pretty much only being able to create the dashboard I want for myself.

**Comment by utkarshcmu** [comment]
@keis  I think Gauge panel is looking good and ready to use as a panel-plugin. :+1: for panel-plugin

May be you can open an issue or submit a PR in https://github.com/toyoty99/flot.gauge to help us resolve the labels issue. But this work can be done after having a separate plugin repo too.

**Comment by RichiH** [comment]
@keis Looks nice. I like the way the colours & limits snake around the gauge area.

As to weathermap: Double-headed arrows between hardware which change colours based on limits. The problem is that that the arrows would need to be arranged more or less freely on a canvas and that's not something Grafana seems to support very well, at the moment.

**Comment by keis** [comment]
I already opened the PR at toyoty99/flot.gauge/pull/4

**Comment by krise3k** [comment]
@keis Thanks for great work with gauges. I use it for couple of days and it works fine, but I found that it's look a bit weird on light theme.

cpu_light

**Comment by keis** [comment]
Hmm. right. The background is hard coded for now. I wonder if there is a good way of getting the colour from the theme without doing computedStyle tricks

**Comment by utkarshcmu** [comment]
@keis In gauge plugin , are you using toyoty99/flot.gauge or your fork keis/flot.gauge ?

**Comment by keis** [comment]
Started updating that yesterday but looks like I forgot the flot library and it ended up loaded the one from grafana vendor which was still on my branch.

It needs my fork for now to work properly

**Comment by runner-mei** [comment]
+1

**Comment by max3163** [comment]
+1

**Comment by Azef1** [comment]
+1 !

**Comment by bergquist** [comment]
@keis sorry for the slow response on this PR.

Would you please merge these two commits? 
https://github.com/bergquist/grafana/commit/8a32142abfa7061ef78cf4e9b6c4e8af6b3a851c
https://github.com/bergquist/grafana/commit/35ec9b0633ac5337bd9af2fceda6283b4b8c9919

After that I think this is ready to be merge.

**Comment by keis** [comment]
No worries @bergquist , rebased and applied those two commits

**Comment by utkarshcmu** [comment]
This will be awesome. 👍

**Comment by Azef1** [comment]
Will Gauge be a plugin ? as "pie chart on https://grafana.net/plugins

**Comment by bergquist** [comment]
@Azef1 gauges will be a setting in singlestat panel and available in grafana core.

**Comment by RichiH** [comment]
Thanks @bergquist !

**Comment by keis** [comment]
woo

**Comment by bergquist** [comment]
This PR have been reverted.
We found a bug and I have to go afk. Will fix and merge this later.

**Comment by bergquist** [comment]
1. Create new dashboard.
2. Create two single stat panels
3. Mark one as gauge.

Then both new panels gets gauge.

**Pull request merged**
