### PR TITLE
Dashboard: Spelling corrections in end-user visible dialogs

### PR DESCRIPTION
**Pull request by al-x**
**What this PR does / why we need it**:

Eliminating spelling errors increases end-user confidence in the project's attention to detail.

**Which issue(s) this PR fixes**:

None that I know of.

Fixes #

**Special notes for your reviewer**:

I organized the PR into 3 separable commits:
1. End-user visible changes
2. Service-maintainer visible changes (ie. documentation, tests, and a CSS class)
3. Developer visible changes (ie. comments)

Even if you reject this particular PR, I recommend you implement the type 1 changes, as they will improve public perception of Grafana.

Type 2 and 3 changes are obviously less critical, but I think it's a good policy to choose consistency over the alternative.

Thanks for Grafana!

### CODE REVIEW

**Review by axelavargas — APPROVED** [review]
Hello @al-x 👋🏾, thanks for contributing to Grafana, I really like the structure of the commits, it made the review easy 🙌🏾

**Review by chri2547 — APPROVED** [review]

**Review by knylander-grafana — COMMENTED** [review]
Great catches on spelling mistakes and corrections! Those updates look correct.

**Comment by axelavargas** [comment]
@al-x can you update your branch with the latest main? Also, make sure that `docs/sources/visualizations/node-graph.md` is running prettier? Our CI is failing because of that 😅

**Comment by al-x** [comment]
I'm looking at the `prettier` issue now. If I can't figure that out quickly, I will just jettison that file from the commit.

**Comment by axelavargas** [comment]
Thank you @al-x for contributing to Grafana 🙌🏾 

ps, `Enterprise PR check / dispatch (pull_request) ` failed because the PR comes from a fork, I tested the changes with Enterprise locally, and it works as expected 🥳

**Pull request merged**
