### PR TITLE
Docs: moves reporting docs per customer request

### PR DESCRIPTION
**Pull request by chri2547**
This PR moves the reporting docs from panels to dashboards.

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Don't we also need to update the link to reporting from https://grafana.com/docs/grafana/latest/enterprise/

**Comment by chri2547** [comment]
> Don't we also need to update the link to reporting from https://grafana.com/docs/grafana/latest/enterprise/

Thanks, just updated all relrefs broken by this change.

**Review by torkelo — COMMENTED** [review]
the dashboards index page is linking to Reporting with an incorrect link (linking to share page). 

Screenshot from 2022-09-07 19-26-29

The doc menu (side anv) has this page as "Create and manage reports" that is 3 whole words I have to read until I get to the one I am scanning for making it very hard to find this page. Is there a way we can have this just say "Reporting" in the nav menu? Think there is a menuTitle attribute we can use

**Comment by chri2547** [comment]
> the dashboards index page is linking to Reporting with an incorrect link (linking to share page).
> 
> Screenshot from 2022-09-07 19-26-29
> 
> The doc menu (side anv) has this page as "Create and manage reports" that is 3 whole words I have to read until I get to the one I am scanning for making it very hard to find this page. Is there a way we can have this just say "Reporting" in the nav menu? Think there is a menuTitle attribute we can use

Corrected both of those issues. Thanks!

**Review by torkelo — APPROVED** [review]

**Pull request merged**
