### PR TITLE
Slug: Use urlencoding to support non-ASCII characters

### LINKED ISSUE #66373: Dashboard Title Slug does not support the mix of English and Chinese in 9.4.1
**What happened**: 
When I create a dashboard with one title consisting both English and Chinese，the dashboard slug after creation will ignore the Chinese part.  This prevents making the second dashboard with the same English prefix.

e.g. 
the first dashboard title is "aws测试", the second dashboard title is "aws生产".
The first dashboard will be created with no error, while the second one will cause a dashboard conflict warning.

**What you expected to happen**:
The second dashboard will be created with no error or warning.

I went through the code, and found [the slug change](https://github.com/grafana/grafana/blame/main/pkg/infra/slugify/slugify_test.go#L15)
and [this PR](https://github.com/grafana/grafana/pull/59517).

It seems that the slug change causes this unexpected behavior. 

I did a test in TestSlugifyTitle, which is my input and expected result.
image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version:
- OS Grafana is installed on: centos7
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by sakjur**
**What is this feature?**

Support a combination of URL safe and non-URL safe characters in our slug generation.

**Why do we need this feature?**

The previous generation of the slugify function first tries to generate a slug without special characters based on a small character translation map, and if that's successful that is used as the slug. This omits a number of characters that aren't supported in URLs. If _no_ characters can be used to generate a slug, a urlencoded version of the string is used. If that string is more than 50 characters, a UUID is used instead.

The problem here lies in the urlencoding, because that only happens when there are exclusively non-slug compatible characters, so a dashboard named using both latin characters and non-latin characters could conflict based on just the latin part.

This solution squashes together the two options and urlencodes all the characters that aren't explicitly supported, replaced, or omitted, and leaving the URL safe characters as-is. The 50 character size limit is also now applied to _all_ slugs, not only urlencoded slugs.

```mermaid
flowchart TD

old[Old flow]-->oldGenASCII[Generate slug based on the latin and latin-like characters in the title]
oldGenASCII-->oldASCIIEmpty{Slug empty?}
oldASCIIEmpty-->|Yes| oldUrlencodeString[Generate a URL-encoded variant for the slug]
oldASCIIEmpty-->|No| oldReturn[Return the resulting slug]
oldUrlencodeString-->oldTooLong{Is the slug more than 50 characters?}
oldTooLong-->|Yes| oldUUIDv5[Generate a UUIDv5 based on the title]
oldTooLong-->|No| oldReturn
oldUUIDv5-->oldReturn

new[New flow]-->newGen[Generate slug, urlencode non-latin like characters]
newGen-->newEmpty{Slug empty or more than 50 characters?}
newEmpty-->|Yes| newUUIDv5[Generate a UUIDv5 based on the title]
newEmpty-->|No| newReturn[Return the resulting slug]
newUUIDv5-->newReturn
```

**Who is this feature for?**

Fixes a bug for editors managing dashboards.

**Which issue(s) does this PR fix?**:

Fixes #66373

**Special notes for your reviewer:**

While this is a bug fix, I've chosen not to put this up for backporting to allow for testing the fix for a bit of an extended time. This has a lower urgency than https://github.com/grafana/grafana/pull/65184 and https://github.com/grafana/grafana/pull/70723 .

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by mildwonkey — APPROVED** [review]
LGTM! I tested it out locally using the example in the linked issue and everything worked (and looks) great:


Screenshot 2023-07-10 at 2 14 56 PM

**Comment by alexandnpu** [comment]
I really appreciate your work to get this fixed!

Will this be backported to v9.4.x? @sakjur

**Comment by sakjur** [comment]
@alexandnpu Thank you!

Unfortunately this’ll have to wait until 10.1, as for 9.4 specifically, this has a hard dependency on #70723 being fixed (…to avoid breaking even more slugs) and that’s done at the earliest in the incoming patch releases for 9.5 and 10.0. The severity of this is slightly lower than that of #70723, so I made the call that we don’t have to backport this. Timing-wise, this shouldn’t affect when the patch is released.

**Comment by alexandnpu** [comment]
hmmm,  I can wait for v10.1. Is it safe to upgrade from v9.4.x to v10.1?
will there be something incompatible?

**Comment by sakjur** [comment]
@alexandnpu Sorry for the slow response! For most people, upgrading from 9.4 to 10.1 should be safe, we always recommend backing up the database beforehand to be able to rollback if something unexpected happens. There is a documentation page for [breaking changes in v10](https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v10-0/), which lists quite a few features, but it shouldn't be anything that affects most installations.

**Comment by alexandnpu** [comment]
@sakjur , thanks for your info, the changes listed in you link seem to be OK to me. I will give v10.1 a try when it is out.

**Comment by DanCech** [comment]
While this change works in theory, we recently ran into an issue where a literal percentage symbol in a dashboard title (and since this change url-encoded into the slug) resulted in a dashboard that would not load (possibly due to inconsistent url-encoding when using slugs in urls).  In any case putting a pre-url-encoded character into a slug is not a good idea, since we should be url-encoding all components at the time we assemble urls, and if we pre-encode the slug then we *should* end up with a double-encoded url.

At the very least we need to add `%` to the list of omitted characters, but I would strongly recommend that we revisit this change and avoid producing slugs that rely on urlencoding to be url-safe.

**Comment by mildwonkey** [comment]
Hey @DanCech - I am not entirely sure how this PR caused that issue; a literal `%` in a dashboard title is stripped for the slug (i added some test cases locally to check):

```
	results["hello-playground"] = "Hello, playground"
	results["hello-playground"] = "Hello%, %playground"
	results["hello-playground"] = "Hello, playground"
```

Do you have any more info about the issue you saw? I wonder if there's another issue; maybe we're using the `slug` in place of `title` for a search somewhere still

**Pull request merged**
