### PR TITLE
Alerting: adds support for federated rules

### PR DESCRIPTION
**Pull request by gillesdemey**
**What this PR does / why we need it**:

This PR adds support for the `source_tenants` property in rule groups. This allows federated alert rules to be retrieved without throwing an exception. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ortuman — APPROVED** [review]
lgtm 👍

**Comment by grobinson-grafana** [comment]
The `source_tenants` field is ignored right, this is just to stop Grafana returning a 400 error because it doesn't expect `source_tenants` to be present in the JSON?

**Review by grobinson-grafana — APPROVED** [review]

**Comment by gotjosh** [comment]
Great work @gillesdemey, if you change the swagger model definition I believe you'll have to run `make swagger-api-spec` or `make swagger-api-spec-mac` -- @papagian would know more about this.

**Comment by papagian** [comment]
> Great work @gillesdemey, if you change the swagger model definition I believe you'll have to run `make swagger-api-spec` or `make swagger-api-spec-mac` -- @papagian would know more about this.

hmm, it seems that something in the Makefile is off so that it does not regenerates the grafana alerting specification (post.json) if it already exists (even though there are changes in the definition files) so until I fix this you need:
```
rm pkg/services/ngalert/api/tooling/*.json
make swagger-api-spec
```

**Comment by gillesdemey** [comment]
I've updated the Swagger spec; the non-deterministic nature of the generator makes asserting the changes on the spec files a bit troublesome but I think they're correct.

@papagian if you have some time a quick confirmation that I'm not committing anything incorrect to the Swagger spec would be most helpful! 🙏

**Review by papagian — APPROVED** [review]
The specification LGTM

**Pull request merged**
