### PR TITLE
Dashboards: Migrate from aria-label e2e selectors to data-testid

### PR DESCRIPTION
**Pull request by khushijain21**
Part of https://github.com/grafana/grafana/issues/78409

Corrects following file
 1 issue in `public/app/features/dashboard-scene/inspect/InspectJsonTab.tsx`
4 issues in `public/app/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx`
4 issues in` public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx`
1 issue in `public/app/features/dashboard/components/PanelEditor/OptionsPane.tsx`
2 issues in `public/app/features/dashboard/components/PanelEditor/OptionsPaneCategory.tsx`
1 issue in `public/app/features/dashboard/components/PanelEditor/OptionsPaneItemDescriptor.tsx`
3 issues in `public/app/features/dashboard/components/PanelEditor/PanelEditor.tsx`

### CODE REVIEW

**Comment by khushijain21** [comment]
@joshhunt here I made the first set of changes

**Comment by joshhunt** [comment]
Neat @khushijain21 - this changeset looks much more manageable 🙌 

Running _all_ unit tests locally is a bit tricky, slow, and I think some may fail locally for some unknown reason (something for us to look into).

You should be able to run tests for just the parts you changed though with this command

```bash
DEBUG_PRINT_LIMIT=0 yarn test --watch public/app/features/dashboard
```

Note - we set the `DEBUG_PRINT_LIMIT=0` [variable to limit debug output](https://testing-library.com/docs/dom-testing-library/api-debugging/), which can easily overwhelm. 

At the moment I see that one file is failing:

```ts
const thresholdsSection = screen.getByLabelText(selectors.components.OptionsGroup.group('Thresholds'));
```

because it's still expecting the old aria-label. This probably should be changed to something like 

```ts
const thresholdsSection = screen.getByTestId(selectors.components.OptionsGroup.group('Thresholds'));
```

See my other PR for other ways to improve selectors in unit tests https://github.com/grafana/grafana/pull/78399/files 

Just a small aside - I've edited your PR body to not say you've _fixed_ the issue, because this doesn't completely fix it, and it'll close it if we keep that in 👍

**Comment by khushijain21** [comment]
@joshhunt any update?

**Review by L-M-K-B — COMMENTED** [review]
Hi @khushijain21, I just checked your current changes and it all looks good to me. Since there are conflicts can you please rebase this branch to the current version of main?

**Review by L-M-K-B — CHANGES_REQUESTED** [review]
Hi @khushijain21, I ran our CI pipeline and found an error regarding betterer and some failing e2e tests. 
For betterer there is a [section in our documentation](https://github.com/grafana/grafana/blob/main/contribute/create-pull-request.md#betterer) about how to solve the issue. 
The following e2e tests are currently breaking:

- dashboard-live-streaming.spec.ts
- import-dashboard.spec.ts
- filter-annotations.spec.ts
- inspect-drawer.spec.ts

You can have a look at the [build pipeline](https://drone.grafana.net/grafana/grafana/153141/3/13) and run each of the tests locally by using `yarn e2e:dev`.

Can you please take care of this?

**Comment by khushijain21** [comment]
@L-M-K-B 
image
I'm assuming this is because aria-label was visible before and data-test id is not? Should I remove the line of code checking this? or let me know if this should be modified?

**Comment by khushijain21** [comment]
@L-M-K-B any update?

**Comment by L-M-K-B** [comment]
In order to solve the issue with playwright tests not running successfully a [PR](https://github.com/grafana/plugin-tools/pull/874) in grafana/plugin-tools needs to get merged (incl. npm package release). Until then this PR is blocked.

**Review by L-M-K-B — APPROVED** [review]

**Pull request merged**
