### PR TITLE
Chore: Update test database initialization

### PR DESCRIPTION
**Pull request by DanCech**
This PR explores using temporary SQLite databases on disk for testing rather than in memory, which will allow us to run tests with WAL mode enabled rather than using in-memory databases with the deprecated shared cache mode.

To be able to support this I refactored the way the test databases are initialized somewhat, there is definitely more work that could be done here to clean things up further.

Currently the branch defaults to using on-disk databases with WAL mode enabled, but this can be overridden by setting environment variables `SQLITE_INMEMORY=true` or `SQLITE_JOURNAL_MODE=false`.

This ended up being far more of a rabbit hole than I anticipated, due to the way that we manage the test databases and how we reduce the number of times that we run the db migrations.

When the tests are run, go starts a separate process for each package, and runs the tests for multiple packages in parallel. By default test are run in `GOMAXPROCS` processes, unless the `-p 1` flag is specified in which case each package is tested sequentially. We pass `-p=1` for the mysql and postgres integration tests since otherwise we would have different packages all trying to use the same database at once (we could potentially improve integration test performance by using a separate database for each test package and running them in parallel instead). For the SQLite-backed tests we stick with the default to improve performance, meaning that we need a separate sqlite database for each process to avoid race conditions.

Side Note: `-p` is a separate flag and not an alias for `-parallel`, which controls the number of tests *within* each package that call `t.Parallel()` that will be run in parallel and also defaults to `GOMAXPROCS`.

Within a given package tests that do not call `t.Parallel()` are run sequentially, and we take advantage of that to reuse the same test database for multiple tests without running the migrations separately for each test.  We do this by keeping a global variable `testSQLStore`, and `initTestDB` will initialize it when the first test runs (and run all the mirgations), then truncate the tables and return the same database handle to subsequent tests within the same package (because they run within the same process).

We can leverage this to create a separate on-disk SQLite db for each package, but cleaning them up becomes a problem, since if we remove the temporary database file in `t.Cleanup` (which runs at the end of the test) then it won't be available to the next test. We need to remove the db files after all tests in the package are run. Go does not provide any mechanism for us to register a shutdown handler, but we can use `TestMain` to take control of package-level test execution and perform cleanup after all the tests. It's clunky, but it works. The major downside of this approach is that if a package uses a test database and does not declare `TestMain` (and call `db.CleanupTestDB()`) then the temporary database files will be left behind and need to be cleaned up manually.

I ended up solving this problem by creating a new `testsuite` package which provides a helper for defining `TestMain`:
```go
package mypkg

import (
	"testing"

	"github.com/grafana/grafana/pkg/tests/testsuite"
)

func TestMain(m *testing.M) {
	testsuite.Run(m)
}
```

Internally `testsuite.Run` calls `db.SetupTestDB`, runs the tests, then calls `db.CleanupTestDB`. `SetupTestDB` just sets a flag to let `initTestDB` know that the `CleanupTestDB` function will run and it's safe to create a test database. If `initTestDB` does not detect that flag, it will end the test run with an error telling the user how to define `TestMain` and linking them to the docs in the style guide.

With this arrangement, it's safe to use `testsuite.Run` regardless of whether the package needs a test database, and we can be sure that test databases will always be cleaned up (unless the test process itself crashes).

It also provides us with a place we could inject other package-level setup/teardown tasks if desired, I have not implemented that in this PR but could do so in a followup PR if there is interest in that capability.

### CODE REVIEW

**Review by papagian — COMMENTED** [review]
LGTM but enterprise needs syncing
also do we want to use on-disk databases with WAL mode enabled in CI as well or keep using the in memory database?

**Comment by DanCech** [comment]
This turned out to be more involved than I anticipated, but is working well now.

If anyone has a better suggestion than TestMain for cleaning up the temporary databases please share.

**Comment by marefr** [comment]
> If anyone has a better suggestion than TestMain for cleaning up the temporary databases please share.

Not really :cry: I'm aware of https://github.com/stretchr/testify?tab=readme-ov-file#suite-package, but never used it. Would also require a lot more changes I imagine. But what we get with your `TestMain` approach is basically a suite - setup/teardown per package. Seems like we possibly could create a Grafana base suite with this construct :shrug: 

> One solution to this problem would be to move the initialization of the test database into TestMain also, which would mean that tests couldn't use a test database without cleaning it up, but I thought that this PR had grown large enough already that it would be better to leave that for a separate PR.

I think that would make things more explicit and easier to reason about :+1: Right now, it feels a bit hidden/magic and I'm not sure what would happen if I forgot to add the `TestMain` and/or how I would realize I forgot that. Can we help/guide developers in this regard?

I did explore a bit using multiple in-memory sqlite databases in these tests https://github.com/grafana/grafana-enterprise/pull/6189/files#diff-f6ef8f358b67b60183c76d2516ea7666d62e4b2d8e0328db95dfb5e523d13962. I guess your suggested WAL solution with temporary database files could be replaced with multiple in-memory databases. Well, more options.

My main concern with the `SQLStore` and I have been banging my head many times is all the logic and the global state of things in regards to tests. One thing I've been thinking is what if we remove all logic from `SQLStore` and you instantiate it with only an `*xorm.Engine` and possibly some other dependencies. Then the responsibility of creating the engine would live outside the `SQLStore` itself. Then in regards to instantiating/bootstrapping Grafana and test databases (`SQLStore`) it would be a matter of instantiating the engine. I'm not sure maybe we would just move the problem to the instantiation of the engine instead :shrug: 

Related to above exploration wanted to use multiple SQLite in-memory database I had to hack around that due to this https://github.com/grafana/grafana/compare/main...poc_mt_datasources

I'm happy to discuss more if needed

**Comment by DanCech** [comment]
I updated this so that we now have a testsuite package we can use for these kinds of setup/teardown tasks.

I kept the refactor very lightweight right now, just having initTestDB verify that it's being run after SetupTestDB so that we also know that the cleanup task will be run.  We can expand on this in future PRs to move more of the test database setup/teardown logic out of the sqlstore and into a dedicated package.

**Comment by DanCech** [comment]
This should now be mergeable, we'll need to do some education around using `testsuite.Run`, but it should also be fairly self-explanatory for developers with the inline message about what they need to do for their tests to run properly.

**Review by ryantxu — APPROVED** [review]
🌮 looks great -- things behaved as expected

**Review by marefr — APPROVED** [review]
LGTM 🎉

**Pull request merged**
