### PR TITLE
Build: Replace babel-loader with esbuild-loader

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

This PR replaces babel-loader with esbuild-loader in Grafana's Webpack configs for a quick win with build times.

Running the minified `yarn build` command locally (on an i5-1038NG7 CPU @ 2.00GHz) gives numbers along the lines of:

**Before (with babel)**
`webpack 5.74.0 compiled with 2 warnings in 230587 ms`

**After (with esbuild)**
`webpack 5.74.0 compiled with 2 warnings in 92193 ms`

In CI we're looking at similar gains:

| Before (with babel) | After (with esbuild) |
| --- | --- |
| Screenshot 2022-10-28 at 17 32 02 | Screenshot 2022-10-28 at 17 32 27 |

**Why do we need this feature?**

To speed up CI builds and get us closer to more modern build tools.

**Who is this feature for?**

Anyone that contributes to the Grafana codebase.

**Special notes for your reviewer**:
~I'm slightly stuck with moving this beyond WIP as I'm not familiar enough with babels `ng-annotate` plugin to understand how to update the few remaining parts of the angular codebase to remove the dependency. I tried running some codemods that used the babel plugin to update the source code but when running in the browser angular couldn't find things.~

I was seeing some oddness around monaco editor crashing the app when running a minified build. This was also apparent in a failing e2e test. Having bumped to the latest version of esbuild this seems to have been resolved. For anyone that wants to test it locally please clear the `public/build` directory and then run `yarn build`. Other than general clicking around, anywhere monaco editor is used and / or angular plugins are worth checking IMHO.

### CODE REVIEW

**Comment by torkelo** [comment]
We could get rid of ng-annotate, but we need to manually update all angular functions and classes that depend on it.

See more details here on what it does. 
https://github.com/schmod/babel-plugin-angularjs-annotate

Not sure how much work it is for the remaining angular code. Should be boring but maybe not that bad :) 

I tried switching to es-build before but it was not as forgiving of circular dependencies (Which we have MAAANY of). But maybe they fixed that as it seems like you have not run into that.

**Comment by torkelo** [comment]
@jackw pushed an update to fix the ngInject issues (replaced with manual injects), 

The app works now in minimized / prod build. 

But double check https://github.com/grafana/grafana/pull/57837/commits/6a7d969baa429c9d64c61042a96a0e60e893e7f9 that I have not made any mistakes

**Comment by jackw** [comment]
Wow thanks so much for helping out with this @torkelo. I really appreciate it given what a mundane task it was. I'll take it for a spin and check some angular plugins too.

**Review by gabor — APPROVED** [review]
LGTM!

i cannot comment on the angular changes, sorry.

the diff in the script-files looks reasonable, i tried to run this and the loki-monaco-editor works ok.

**Review by leventebalogh — APPROVED** [review]
Nice work! 👏 

Looks good to me, although I haven't tested out the angular changes.

**Review by academo — COMMENTED** [review]
The best of the PR is removing the `ngInject`!

I did some local benchmarking in my computer:

With babel-loader

```
❯ hyperfine --runs 4 'yarn build' --prepare "rm -rf public/build && rm -rf .yarn/.cache/webpack"
Benchmark 1: yarn build
  Time (mean ± σ):     138.706 s ± 10.384 s    [User: 192.546 s, System: 5.251 s]
  Range (min … max):   129.955 s … 153.766 s    4 runs
```

With esbuild-loader
```
❯ hyperfine --runs 4 'yarn build' --prepare "rm -rf public/build && rm -rf .yarn/.cache/webpack"
Benchmark 1: yarn build
  Time (mean ± σ):     59.435 s ±  2.341 s    [User: 99.625 s, System: 4.784 s]
  Range (min … max):   56.682 s … 62.408 s    4 runs
```
That's a reduction of around 58% in compile time.

I still need to test it locally to see nothing is broken (thus not approved yet)

**Comment by itsmylife** [comment]
I will test `ngInject` but in that regard, @bohandley is the best person to reach out to since he was the person who removed the angular support/code. But he is sick. I will check everything is fine and he will give us more information when he is back.

**Review by itsmylife — APPROVED** [review]
Graphite and InfluxDB are ok. I think we can even remove them. cc: @bohandley 

Here is the PR to remove them https://github.com/grafana/grafana/pull/61251
But I'll wait till this PR will be merged. So there won't be any conflicts here.

**Review by zoltanbedi — APPROVED** [review]
Let's go!

**Review by academo — APPROVED** [review]
I did some light testing and everything was fine. I didn't directly test an angular plugin or angular-specific functionality.

**Comment by codeincarnate** [comment]
Wanted to check this out as builds are already fairly fast on Apple silicon. Was still an impressive gain. Here are the results for an M1 Pro. Without this PR:

```
 webpack 5.74.0 compiled with 2 warnings in 192864 ms
```

With this PR:
```
webpack 5.74.0 compiled with 2 warnings in 56690 ms
````

A 70% performance improvement is nothing to sniff at. Awesome change!

**Comment by jackw** [comment]
Thanks to all for taking the time to review this PR. I've tested a few angular panels and the angular clickhouse datasource plugin and they seem to function as expected.

**Comment by leeoniya** [comment]
@jackw any chance of spreading the love to `build:nominify`, too? :pray:

**Comment by jackw** [comment]
@leeoniya I'm not sure this will speed up `build:nominify` once the webpack cache is in place. A cold cache will see some benefit but I think most of the performance gains here come from replacing terser.

**Comment by leeoniya** [comment]
> but I think most of the performance gains here come from replacing terser.

esbuild has historically produced bigger bundles because it is less thorough and more conservative. do you have the size stats on hand?

**Comment by jackw** [comment]
> esbuild has historically produced bigger bundles because it is less thorough and more conservative. do you have the size stats on hand?

@leeoniya sorry for not replying sooner I didn't have the stats on hand and I've struggled to get hold of them due to the size of the json file that's generated. Anyhow... stats match your statement. 

This PR adds ~460KB according to webpacks bundle analyser analysis:

| Before | After |
| --- | --- |
| Screenshot 2023-01-19 at 12 39 41 | Screenshot 2023-01-19 at 12 39 53 |

Zipped we're looking at ~280KB:

| Before | After |
| --- | --- |
| Screenshot 2023-01-19 at 12 37 20 | Screenshot 2023-01-19 at 12 37 46 |

**Comment by jackw** [comment]
> do you think there's any future path to using Terser for releases / tagged builds which end up shipping to users? that way we can have our cake and eat it, too.

Yep we can certainly look into that without too much trouble. Might be able to trim some of the fat elsewhere too while we're at it. 👍

**Pull request merged**
