### PR TITLE
Docs: Update tracesToLogs provisioning example for mapped tags

### PR DESCRIPTION
**Pull request by alfredo-d**
**What is this feature?**

Doc update to expand `tracesToLogsV2` example for mapped tags.

**Why do we need this feature?**

Current example only show how to handle tag without mapping. This change provide additional example for mapped tags as well.
This will align to previous `tracesToLogs` provisioning example that shows both non-mapped tag (`tags`) and mapped tag (`mappedTags`).

**Who is this feature for?**

Users who use Grafana provisioning to configure their datasources.

**Which issue(s) does this PR fix?**:
N/A

### CODE REVIEW

**Review by knylander-grafana — APPROVED** [review]
Thank you for adding an example to the docs. 

Kim

**Comment by knylander-grafana** [comment]
@alfredo-d  You have the right tags on the PR. I'm not sure why the error messages are still showing up on the checks. I've prompted the PR to rerun the checks, but the messages about backport and release are still there. One message indicates that prettier needs to be run on the file as well.

**Comment by alfredo-d** [comment]
@knylander-grafana I've fixed the prettier error.

**Comment by knylander-grafana** [comment]
@alfredo-d I'm going to ask a Grafana writer to review. They will have merging rights and will know about any possible need to backport.

**Pull request closed without merging**
