### PR TITLE
v6.2.1 cherry picks

### PR DESCRIPTION
**Pull request by marefr**
Changes going into v6.2.1 release:
* Explore: Fixes so clicking in a Prometheus Table the query is filtered by clicked value, (#17083), merge-sha: fdd421e24c38e92c9ea67d326ad56d00563713bb                                                                                                    
* fix filter for building msi during release, (#17236), merge-sha: 972df40af8b2af356de17ba08b6df628c61797ac                                                                                                                                                 
* Singlestat: Fixes issue with value placement and line wraps, (#17249), merge-sha: 6acc7d37dad262a5f0a2442b2ec80c29fcdd1151
* Update: Update jQuery to 3.4.1 to fix issue on iOS 10 based browers as well as Chrome 53.x , (#17290), merge-sha: df6a4914c4eca3ae87068df3ca29ad9eb101f03c
* CLI: Add command to migrate all datasources to use encrypted password fields , (#17118), merge-sha: 151b24b95fb52a777533c9fd76db48ae8967a74e
* Chore: Update jquery to 3.4.1 in grafana ui, (#17295), merge-sha: 3dda812f12653479084c567cbf63fa83be2a0659
* Gauge/BarGauge: Improvements to auto value font size , (#17292), merge-sha: 5358c5fe6b0a966dcfe0495b47b06d18155ed647

Backports:
* Auth Proxy: Resolve database is locked errors (#17274)
* Auth Proxy: Log any error in middleware (#17296)
* Database: Retry transaction if sqlite returns busy error (#17297)
* Backport parts of #17065

### CODE REVIEW

**Comment by bergquist** [comment]
missing https://github.com/grafana/grafana/pull/17118

**Comment by marefr** [comment]
Yes I know @bergquist, but don't think it was merged when I did the cherry pick. Going to try again.

**Comment by marefr** [comment]
Got "too many files open" error for one proxy request error, but besides that no "database is locked" errors.

```
> ./run.sh -d 15m -v 20 -c auth_proxy_test -u http://127.0.0.1:10080/grafana

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: src/auth_proxy_test.js

    duration: 15m0s, iterations: -
         vus: 20,    max: 20

    done [==========================================================] 15m0s / 15m0s

    █ auth proxy test

      █ batch proxy requests

        ✗ response status is 200
         ↳  99% — ✓ 275999 / ✗ 1

    checks.....................: 99.99% ✓ 275999 ✗ 1
    data_received..............: 5.3 GB 5.9 MB/s
    data_sent..................: 86 MB  96 kB/s
    group_duration.............: avg=14.5s    min=761.72ms med=15.04s   max=24.33s   p(90)=18.1s   p(95)=19.05s
    http_req_blocked...........: avg=156.69µs min=758ns    med=2.75µs   max=174.56ms p(90)=4.74µs  p(95)=411.75µs
    http_req_connecting........: avg=142.49µs min=0s       med=0s       max=174.5ms  p(90)=0s      p(95)=304.21µs
    http_req_duration..........: avg=929.65ms min=1.45ms   med=975.68ms max=3.57s    p(90)=1.35s   p(95)=1.5s
    http_req_receiving.........: avg=53.05µs  min=9.29µs   med=40.33µs  max=32.03ms  p(90)=58.66µs p(95)=70.51µs
    http_req_sending...........: avg=62.75µs  min=5.54µs   med=21.76µs  max=135.22ms p(90)=35.51µs p(95)=69.83µs
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s       max=0s       p(90)=0s      p(95)=0s
    http_req_waiting...........: avg=929.53ms min=1.4ms    med=975.59ms max=3.57s    p(90)=1.35s   p(95)=1.5s
    http_reqs..................: 278517 309.463306/s
    iteration_duration.........: avg=19.45s   min=2.15µs   med=20.02s   max=29.33s   p(90)=23.11s  p(95)=24.05s
    iterations.................: 912    1.013333/s
    vus........................: 20     min=20   max=20
    vus_max....................: 20     min=20   max=20
```

**Comment by bergquist** [comment]
@marefr could you please try cherry-picking https://github.com/grafana/grafana/pull/17213 ? 
commit: https://github.com/grafana/grafana/commit/3ff3e0f2acb37388f6a01cca97dbde631052ca38
https://github.com/grafana/grafana/pull/17213/files#diff-21f89324b16a1ac91222160b871178bbR319

might help

**Comment by marefr** [comment]
@bergquist I don't see how those changes has any effect in the datasource proxy?

**Comment by bergquist** [comment]
Absolutely true. 

Weird. Never `seen too many files open` during load testing. Not a blocker in this case.

**Review by bergquist — APPROVED** [review]
LGTM

I guess we should rebase this instead of squashing? :)

**Comment by marefr** [comment]
Yes we should :+1:

**Pull request merged**
