### PR TITLE
Currency: Adds Indonesian IDR currency

### PR DESCRIPTION
**Pull request by hiddenrebel**
**What this PR does / why we need it**: 
Add new option for Indonesian IDR currency
And Fix typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kaydelaney — APPROVED** [review]
LGTM! Thanks for your contribution. You'll need to sign the contributor license agreement before this can be merged, however

**Review by hugohaggmark — APPROVED** [review]
I agree with @kaydelaney, splendid work with this. You need to sign the CLA so we can merge this into master.

Also, I think you can use custom data units for this https://grafana.com/blog/2020/01/27/grafana-v6.6-released/#custom-data-units

**Comment by hiddenrebel** [comment]
> I agree with @kaydelaney, splendid work with this. You need to sign the CLA so we can merge this into master.
> 
> Also, I think you can use custom data units for this https://grafana.com/blog/2020/01/27/grafana-v6.6-released/#custom-data-units

sorry I am new here.
I try to sign the CLA and try to find out how to do it :D 

I hope with this merge can help Indonesian user easy to use their own currency with the option that already exists

**Comment by ryantxu** [comment]
@hiddenrebel -- look up in this thread and you will see a post from the CLA assistant, it will look like:  
image

Click on the part that says "not signed" and you will go to a form that lets you fill it out

thanks!

**Comment by hiddenrebel** [comment]
> @hiddenrebel -- look up in this thread and you will see a post from the CLA assistant, it will look like:
> image
> 
> Click on the part that says "not signed" and you will go to a form that lets you fill it out
> 
> thanks!

i did it
image
but still can't sign

**Comment by hugohaggmark** [comment]
> > @hiddenrebel -- look up in this thread and you will see a post from the CLA assistant, it will look like:
> > image
> > Click on the part that says "not signed" and you will go to a form that lets you fill it out
> > thanks!
> 
> i did it
> image
> but still can't sign

I think I understand why, the commit was commited by __Muhammad Hendry__ and your github user is @hiddenrebel. You need to add the email adress for  __Muhammad Hendry__ to your github user. Thank you

**Comment by hiddenrebel** [comment]
> > > @hiddenrebel -- look up in this thread and you will see a post from the CLA assistant, it will look like:
> > > image
> > > Click on the part that says "not signed" and you will go to a form that lets you fill it out
> > > thanks!
> > 
> > 
> > i did it
> > image
> > but still can't sign
> 
> I think I understand why, the commit was commited by **Muhammad Hendry** and your github user is @hiddenrebel. You need to add the email adress for **Muhammad Hendry** to your github user. Thank you

Awesome, thank you for your kind 👍 
Thanks all for helping me. 😃

**Pull request merged**
