### PR TITLE
Add Pushover alert notifications

### PR DESCRIPTION
**Pull request by alfredkrohmer**
Pushover is a service for getting real-time notifications on your mobile devices and desktop computers: https://pushover.net

### CODE REVIEW

**Comment by bergquist** [comment]
Please include a link to the service or at least a short summary :)

**Comment by devkid** [comment]
@bergquist I have updated the description. Is that sufficient or should I also update the commit message?

**Comment by Mic92** [comment]
works for me: https://dl.thalheim.io/Q9L2GHSYeJj10KJ7-45fhQ/8a1abbac-c665-4754-bfc4-a649e7a8b363.jpg

**Comment by Mic92** [comment]
Anything left to be done from the contributor site?

**Comment by torkelo** [comment]
@devkid can you investigate https://github.com/grafana/grafana/issues/8006 ?

**Pull request merged**
