### PR TITLE
GCS image uploader: Add tests

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:

* Rewrite the GCS image uploader to use interfaces in front of the Google SDK, to make the code testable (to avoid network requests to Google services)
* Add test mocks of the SDK interfaces
* Add a test for unsigned URLs
* Add a test for signed URLs

These tests should be really useful, since I recently had to stop a PR from accidentally removing the signed URL functionality.

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]
Looks good to me. I'm not clear on what generates the file? Do we need any comments somewhere on how/when one might regen that?

**Comment by aknuds1** [comment]
> Looks good to me. I'm not clear on what generates the file? Do we need any comments somewhere on how/when one might regen that?

@kylebrandt Good point, maybe I should add some automation for regenerating the mock.

**Review by kylebrandt — CHANGES_REQUESTED** [review]
Oops just noticed, I think you might be including an extra PR in here by mistake? https://github.com/grafana/grafana/pull/28525

**Comment by aknuds1** [comment]
@kylebrandt Ugh, oops indeed.

**Comment by aknuds1** [comment]
Will fix those issues.

**Comment by aknuds1** [comment]
Rebased the branch to get rid of the unintended changes.

**Review by kylebrandt — APPROVED** [review]

**Pull request merged**
