### PR TITLE
Docs: Change Angular text references to AngularJS

### PR DESCRIPTION
**Pull request by zigiprimo**
**What is this feature?**
updating docs - Grafana is deprecating AngularJS 

AngularJS support has officially ended as of January 2022 
Visit [angular.io](https://angular.io/) for the actively supported Angular.

**Why do we need this feature?**
to remove any ambiguity: AngularJS vs Angular

**Who is this feature for?**
anyone who read the docs 

**Which issue(s) does this PR fix?**:
Document reference to a particular library's name: AngularJS
which is very different to Angular (Web Development framework)

Fixes #
update library name reference in docs.

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by zigiprimo** [comment]
add label no-changelog

**Review by Eve832 — APPROVED** [review]
lgtm

**Comment by Eve832** [comment]
I think we need a technical review though. I'll add another reviewer

**Review by tolzhabayev — APPROVED** [review]

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
lgtm, but please resolve the merge conflicts first / update your branch with the latest main.

**Comment by zigiprimo** [comment]
> lgtm, but please resolve the merge conflicts first / update your branch with the latest main.

thank you @tolzhabayev - addressed the conflicts and branch updated.

**Review by tolzhabayev — APPROVED** [review]

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Pull request closed without merging**
