### PR TITLE
Escape backslashes in Loki queries (#45809).

### LINKED ISSUE #45809: Loki: If label value includes backslash it is not escaped and query is invalid
**What happened**:
In log browser, we are not escaping backslash, but it seems like we do it for Prometheus. We should probably do the same here and also look at autocomplete.

**What you expected to happen**:

When I choose value from autocomplete or label browser, backslash it should be correctly escaped.

**How to reproduce it (as minimally and precisely as possible)**:
1. You have to have logs with label values that include backslash
2. Open log browser and pick label + value with backslash
3. backslash should be escaped and query should produce result without error

### PR DESCRIPTION
**Pull request by glintik**
**Which issue(s) this PR fixes**:

Fixes #45809

**Special notes for your reviewer**:

Not sure changed line is a proper place to escape, so feel free to move/refactor it.

### CODE REVIEW

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
Hello @glintik and thank you so much for looking into this. 🙏

I've reviewed the bug report and started to look into where the issue happens and I've discovered that we have problem at couple of places: 
1. Highlighter in Typeahead.tsx `packages/grafana-ui/src/components/Typeahead/TypeaheadItem.tsx`  component causes editor to crash. We should probably add there `autoEscape={true}` parameter to make sure that anything that user types is escaped and doesn't causes regexp error. More here https://github.com/bvaughn/react-highlight-words
2. In LokiLabelBrowser `public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx` we should escape suggestions in the same way as we do in Prometheus Metric Browser to produce correct query if the label includes character that needs to be escaped.
3. In LokiQueryField `public/app/plugins/datasource/loki/components/LokiQueryField.tsx` we should also escape chosen suggestions so it produces correct query.

As I was exploring this, I created branch where I tried to fix it, but it still has issues. If you want to look into it and continue - let me know.  This is the branch: https://github.com/grafana/grafana/compare/ivana/loki-escaping?expand=1

Otherwise I'll continue once I finish other things I am working on.

**Comment by glintik** [comment]
> Hello @glintik and thank you so much for looking into this. 🙏
> 
> I've reviewed the bug report and started to look into where the issue happens and I've discovered that we have problem at couple of places:
> 
>     1. Highlighter in Typeahead.tsx `packages/grafana-ui/src/components/Typeahead/TypeaheadItem.tsx`  component causes editor to crash. We should probably add there `autoEscape={true}` parameter to make sure that anything that user types is escaped and doesn't causes regexp error. More here https://github.com/bvaughn/react-highlight-words
> 
>     2. In LokiLabelBrowser `public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx` we should escape suggestions in the same way as we do in Prometheus Metric Browser to produce correct query if the label includes character that needs to be escaped.
> 
>     3. In LokiQueryField `public/app/plugins/datasource/loki/components/LokiQueryField.tsx` we should also escape chosen suggestions so it produces correct query.
> 
> 
> As I was exploring this, I created branch where I tried to fix it, but it still has issues. If you want to look into it and continue - let me know. This is the branch: https://github.com/grafana/grafana/compare/ivana/loki-escaping?expand=1
> 
> Otherwise I'll continue once I finish other things I am working on.

Hi @ivanahuckova,

Thank you for details, appreciated. Looks like the issue with Loki query has many items. May you give me few days to do more research, i.e. until end of this week?

**Comment by ivanahuckova** [comment]
Absolutely! 🧡  You can also split this into separate smaller PRs tackling individual issues - crashing editor, label browser, selecting option from suggestions.

**Comment by glintik** [comment]
Closed. Preparing a new one.

**Pull request closed without merging**
