### PR TITLE
Docs: Updated table docs, moved annotations notice down

### PR DESCRIPTION
**Pull request by torkelo**
Just noticed this notice at the top of this page, it felt out of place and distracting. So moved it down to a new section at the bottom. 

Screenshot from 2020-09-22 16-06-11

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

**Review by oddlittlebird — CHANGES_REQUESTED** [review]
The note does not need its own h3. Please leave it at or near the top. This was added because several people asked why annotations weren't working in tables.

As for the unnecessary content, that's why we don't just copy and past stuff from other topics and drop them into different topics. The content was necessary when it was in its previous place.

**Comment by torkelo** [comment]
Well then the top sections of most features would be littered with long list of notices for features that where removed or changed. 

I do not think a minor feature change to the table visualizations belongs in the top section. If you have a better idea other than moving this to its own section then please let me know.

**Comment by oddlittlebird** [comment]
As I recall, you said that annotation support would be added to the new table in the near future. This is a temporary band-aid and can be removed once support is added. 

It's here and very visible because right now, users are confused and asking about it. I am attempting to answer their question. It's a short, very visible, one-line note, answering a question that is on the minds of our users.

**Comment by torkelo** [comment]
When annotation support will be added it will get it's own section, so why have it at the top? This way if they miss annotations they can find this notice if they search annotations on this page, or search for table annotations in the docs search. 

We get hundreds of questions every week, not sure the top of each reference page is best for common Q&As

**Comment by oddlittlebird** [comment]
@ryantxu just told me that annotations only work for graph and maybe heatmap panels. If that is the case, then what about moving this information out of the note and somewhere in the Annotations topic?

**Comment by torkelo** [comment]
updated wording a bit, think it still makes sense to have a small section on this page for those missing the feature.

**Review by oddlittlebird — APPROVED** [review]
Works for me.

**Pull request merged**
