### PR TITLE
Multipart query conditions for alerts

### PR DESCRIPTION
**Pull request by melissapruit**
Enables two part queries for alerting. [Issue #6593 ](https://github.com/grafana/grafana/issues/6593)

### CODE REVIEW

**Comment by torkelo** [comment]
for context on previous attempts at solving this, and the discussion of ideas of how to support this without duplicating everything in QueryCondition, 

https://github.com/grafana/grafana/pull/8931#issuecomment-321231970

**Comment by MrNeuronix** [comment]
Please, add this functional asap

**Comment by bergquist** [comment]
Write some thoughts about this in the issue.

**Comment by ltning** [comment]
@bergquist This is something we've been drooling over for some time. How's that review coming along?

**Comment by deepakksahu** [comment]
Please, add this functional asap

+1

**Comment by torkelo** [comment]
I am not a big fan of this approach as it basically duplicates everything QueryCondition in a more complex scenario. Would prefer an approach that could combine the result of many QueryConditions and compare the results, something like what is outlined here: https://github.com/grafana/grafana/pull/8931#issuecomment-321231970

We are about to start a big alerting project where we will be rethinking some of the fundamentals (sepratating alert rule definitions form the dashboard, etc). Think features like this is better solved in the actual query (via sub queries etc)

**Pull request closed without merging**
