### PR TITLE
docs: Update "Annotate Vizualizations" to be more clear

### PR DESCRIPTION
**Pull request by skeilson**
The original wording was unclear. Suggest re-phrasing to make it clear as to where the newly added annotation(s) are visible.

### CODE REVIEW

**Review by imatwawana — APPROVED** [review]
Thanks for the contribution! LGTM!

**Comment by imatwawana** [comment]
@skeilson - Can you please sign the [CLA agreement](https://cla-assistant.io/grafana/grafana?pullRequest=70760), so we can merge this.

**Comment by skeilson** [comment]
@imatwawana I've never seen this CLA agreement before. Do all Grafana employees need to agree to this?

**Comment by imatwawana** [comment]
> @imatwawana I've never seen this CLA agreement before. Do all Grafana employees need to agree to this?

Yes, all contributors (employees or external contributors) to this repository have to sign it in order for PRs they author to be merged.

**Pull request closed without merging**
