### PR TITLE
Navigation: change `Search Dashboards` back to sentence case (`Search dashboards`)

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana yeah i can't think of anything (nice) to do about that. you got any thoughts? 🤔

**Comment by JoaoSilvaGrafana** [comment]
> @JoaoSilvaGrafana yeah i can't think of anything (nice) to do about that. you got any thoughts? 🤔

Nah would have to hack something that would probably break in some scenarios. I guess a question is do we have naming conventions for plugins? And if they suggest capitalizing every word, maybe it's not too bad to keep the navigation consistent with that.

**Review by axelavargas — APPROVED** [review]
Looks good to me 🚀

**Comment by ashharrison90** [comment]
> > @JoaoSilvaGrafana yeah i can't think of anything (nice) to do about that. you got any thoughts? 🤔
> 
> Nah would have to hack something that would probably break in some scenarios. I guess a question is do we have naming conventions for plugins? And if they suggest capitalizing every word, maybe it's not too bad to keep the navigation consistent with that.

@grafana/plugins-platform-frontend do we have any naming conventions for plugins? e.g. `Sentence case` vs `Title Case`?

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
