### PR TITLE
Alerting: Fix panic in dingding notifier 

### LINKED ISSUE #9771: dingding alert panic
When alert message include JSON data, process be panic...

ERROR LOG:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x771972]

goroutine 3320373 [running]:
github.com/grafana/grafana/pkg/components/simplejson.(*Json).MarshalJSON(0x0, 0x117860b, 0x1a, 0xc420ac26c0, 0x4, 0x4)
        /go/src/github.com/grafana/grafana/pkg/components/simplejson/simplejson.go:75 +0x22
github.com/grafana/grafana/pkg/services/alerting/notifiers.(*DingDingNotifier).Notify(0xc420833090, 0xc420585e00, 0xc420d99788, 0xc420d02a00)
        /go/src/github.com/grafana/grafana/pkg/services/alerting/notifiers/dingding.go:77 +0x63a
github.com/grafana/grafana/pkg/services/alerting.(*notificationService).sendNotifications.func1(0x8, 0x11c5ad8)
        /go/src/github.com/grafana/grafana/pkg/services/alerting/notifier.go:69 +0x38
github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420ac2600, 0xc420391c00)
        /go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66

### PR DESCRIPTION
**Pull request by csyangchen**
**What this PR does / why we need it**:

dingding notifier fails to send alert messages containing JSON, this PR use map and `json.Marshal` to always produce valid JSON body.

**Which issue(s) this PR fixes**: #9771

Fixes #9771

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thanks. Can you please add a test that before this change resulted in panic and now doesn't panic with your changes? Please sign the CLA as well - if you commited using an email address that's not registered in GitHub you'll need to register that one in your GitHub account.

**Comment by csyangchen** [comment]
split into two commits:
- split out the `genBody` method to make a test that fails
- the actual commit to allow for any input in json body

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
