### PR TITLE
Dashboard: Fix global variable "__org.id"

### LINKED ISSUE #23340: Templating: Global variable __orgName has wrong value
**What happened**:
The new global variable __org is interpolate to user id
**What you expected to happen**:
The variable is interpolated to de org ir
**How to reproduce it (as minimally and precisely as possible)**:
every query that uses $__org
**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/816b611eb9d294a2aa768987388ca5aae16a1f20/public/app/features/templating/variable_srv.ts#L65-L71
**Environment**:
- Grafana version: 6.7

### PR DESCRIPTION
**Pull request by vikkyomkar**
**Which issue(s) this PR fixes**:

#23340

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
This is sadly changing the wrong file, we just switched to ou new variable system (still have to remove the old code).

The new code is here:
https://github.com/grafana/grafana/blob/c7ffc1199cdb331c34cf8d95a60ed602b14e76b5/public/app/features/variables/state/actions.ts#L97

**Comment by vikkyomkar** [comment]
made the change in new file

**Comment by mckn** [comment]
We also have this one: #23378

**Review by torkelo — APPROVED** [review]
Looks good, thanks for this contribution!

**Pull request merged**
