### PR TITLE
Added Table View Panel

### PR DESCRIPTION
**Pull request by craftytrickster**
# Table View

**Summary**
Added a new panel that allows for the rendering of data in a table. 

In this first iteration of the Table View we are able to render data from a datasource, complete with paging and sorting. The data can be delivered in real time just like with the graph panel.

If this pull request is accepted, future features may include column filtering, and data cell highlighting based on a specific input criteria (such as standard deviation).

**Datasource**

The changes that I made to the datasource in order to use the table panel have been removed. It can now work with any datasource without any modification. Currently only tested on InluxDb 0.8x

**Closing**
Please let me know if you would like any changes in order to accept this pull request.

As seen in [issue 215](https://github.com/grafana/grafana/issues/215)

screen shot 2015-04-01 at 3 19 06 pm

### CODE REVIEW

**Comment by torkelo** [comment]
it might take a few weeks before I have time to look at this, it will probably need some big modifications to be more general, for example handle multiple queries, and other data sources. Only supporting influxdb 0.8 is kind of bad as influxdb 0.9 is so radically different (no longer support for columns, only single value metrics and tags).

But just a first glance at the code (I have not looked at it running yet, a screenshot would be nice), this looks like a solid foundation for a table panel, with unit tests and everything, so stands a very good change of being merged in some form in the coming 1-2 months.

**Comment by craftytrickster** [comment]
screen shot 2015-04-01 at 3 19 06 pm

Sounds good, thank you for the update. 

As for InfluxDb0.9, they are constantly changing Release Candidates, it is a bit of a moving target. When they release a stable version my next step would be to make sure the datasources line up.

I am not sure how to handle multiple queries exactly, since tables naturally seem to fit a single query/multi column select format. Having said that, since the tablePanel directive is not tightly coupled to a datasource, it would not be impossible if there is a use case.

**Comment by craftytrickster** [comment]
Hello Torkel,

I have improved the pull request in two different ways:

I have removed all of the modifications of the datasource on Influx .8x, which was needed to render the table. This is beneficial because fewer files have been changed and, it should now work with any datasource without any further modification (in theory). 

Additionally, I have removed my implementation of a multicolumn sort, as I would prefer to depend on an established library to provide this functionality.

Overall, I was able to reduce about 5 files worth of changes.

**Comment by torkelo** [comment]
That sounds great

**Comment by craftytrickster** [comment]
This pull request was based off develop when active Grafana 2.0 development was not done on master yet. I am resubmitting request based off of master now

**Pull request closed without merging**
