### PR TITLE
i18n: Mark up Query History for translations

### LINKED ISSUE #73981: i18n: Mark up Query History for translations
### Requirements ###

Add support for i18n in Query History components. All text presented in the UI should have i18n keys.

#### Details

* No translations need to be provided, just i18n keys
* Follow guidelines described in https://github.com/grafana/grafana/blob/main/contribute/internationalization.md
* Add `<Trans i18nKey ...` to all components in `explore/RichHistory` 
* Prefix `i18nKey` with `explore.history.`
* Don't change translation files. After adding new `<Trans i18nKey ...` run `yarn i18n:extract`

<details><summary>screenshots</summary>

Screenshot 2023-08-29 at 10 11 58

Screenshot 2023-08-29 at 10 12 04

</details>

#### Notes

* Change the language in user profile
* Translations are saved in public/locales/

🚧 Outstanding questions

...

### PR DESCRIPTION
**Pull request by RoxanaAnamariaTurc**
**What is this feature?**

Marked up strings for translation in Explore > Query History

**Why do we need this feature?**

To ensure translation across Grafana

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #73981

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ifrost** [comment]
Hi @RoxanaAnamariaTurc! There's already a PR opened for this issue https://github.com/grafana/grafana/pull/75975 that is close to being done. There was no-one assigned to https://github.com/grafana/grafana/issues/73981 because usually we don't do that with external PRs (maybe we should start though to avoid confusion). It's always good to check if there's a PR opened already.

**Comment by RoxanaAnamariaTurc** [comment]
> Hi @RoxanaAnamariaTurc! There's already a PR opened for this issue #75975 that is close to being done. There was no-one assigned to #73981 because usually we don't do that with external PRs (maybe we should start though to avoid confusion). It's always good to check if there's a PR opened already.

Hello @ifrost , I only noticed that after I opened the PR, sorry about the mixing , I will pick up other issues more carefully :) what can I do about this PR now?

**Comment by ifrost** [comment]
> Hello @ifrost , I only noticed that after I opened the PR, sorry about the mixing , I will pick up other issues more carefully :) what can I do about this PR now?

Sorry, but we'll need to close it :(

**Comment by RoxanaAnamariaTurc** [comment]
Hello,
No problem at all :)

**Pull request closed without merging**
