### PR TITLE
Added a Promise stub for phantomJS

### PR DESCRIPTION
**Pull request by zachry-dunton-DH**
Added a promise.js polyfill that fixes phantomJS's lack of Promises
which broke renderToPng for scripted dashboards.

### CODE REVIEW

**Comment by torkelo** [comment]
There is no usage of the Promise api in grafana.

**Comment by zachry-dunton-DH** [comment]
There is in getDash.js

**Comment by zachry-dunton-DH** [comment]
Scripted dashboards that use promises to grab data may have to deal with this issue. This change doesn't change anything for anyone that doesn't use Promises, other than injecting a small chuck of JS using a localpath.

**Comment by torkelo** [comment]
should use angular js promies then as that is already included and used by the reset of the code base

**Pull request closed without merging**
