### PR TITLE
Access Control: Add fine-grained access control to explore

### PR DESCRIPTION
**Pull request by kalleep**
**What this PR does / why we need it**:
Add fgac support for explore feature. This would make it possible to configure permission to allow users to use the explore feature.

**Special notes for your reviewer**:
If a user has access to explore without the viewerCanEdit flag enabled the return to dashboard with changes button will be hidden.

Viewer with permission to use explore:

explore_dropdown

image

Viewer without access to explorer:

image

image

### CODE REVIEW

**Comment by vtorosyan** [comment]
@Clarity-89 would appreciate if you could also double check the changes, since it is touching the frontend components.

**Review by Clarity-89 — COMMENTED** [review]
Code looks good, but I think someone from observability squad needs to double check it to be sure.

**Review by ivanahuckova — APPROVED** [review]
The explore & frontend part of the code looks good (I have left just 1 super tiny nit pick comment). I am not 💯 sure about the fine-grained access control & backend part as I am not familiar with that part of the codebase, so I would rely on someone else's review of that part. 

Good work on this! 🔝  I really like how you considered all edge cases/features (back to dashboard button & internal links).

**Review by gamab — APPROVED** [review]
LGTM ! Discussed it with you live. I did not check the frontend part. :+1:

**Pull request merged**
