### PR TITLE
Cloudwatch: Add AWS/EMRServerless and AWS/KafkaConnect Metrics 

### PR DESCRIPTION
**Pull request by DugeraProve**
Adding MSK Connect Metrics for Cloudwatch Datasource.

### CODE REVIEW

**Comment by idastambuk** [comment]
Hi @DugeraProve, thanks for the contribution! 
We ask for a bit of patience with this one, as we're checking with AWS regarding  the docs for AWS/KafkaConnect namespace. In the meantime, you can add the namespace manually by typing the name in the dropdown then hitting Enter.

**Comment by idastambuk** [comment]
Hi @DugeraProve sorry for the delay, AWS has just confirmed the namespace [name](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html). However, I can't see the dimension name in their docs, can you update to remove the key for this in NamespaceDimensionKeysMap? As soon as we do that we will merge it. Thanks for your patience!

**Comment by DugeraProve** [comment]
Hi @idastambuk the dimensions I add I got from the AWS Docs here https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/app-job-metrics.html are these not correct?

**Comment by idastambuk** [comment]
Hi @DugeraProve, the EMR metrics are correct, I meant the one for MSK - ConnectorName . I should have been more clear, sorry!

**Comment by DugeraProve** [comment]
Ah thanks for the clarification @idastambuk . I have removed it.

**Review by idastambuk — APPROVED** [review]

**Comment by idastambuk** [comment]
Hi @DugeraProve it looks like the build is failing - can you rebase main and we can try again? Thanks!

**Comment by DugeraProve** [comment]
I have updated branch to pick up latest main branch changes.

**Pull request merged**
