### PR TITLE
Kairosdb alerting

### PR DESCRIPTION
**Pull request by larshanson**
https://github.com/grafana/grafana/issues/5858
Alerting support for kairosdb.

### CODE REVIEW

**Comment by torkelo** [comment]
Since KairosDB is an external plugin, with a relatively small user base, I think this has to wait until add support for backend plugins

**Comment by larshanson** [comment]
Do you have a time line for backend plugins?

**Comment by torkelo** [comment]
No but hopefully some time in next 6-12 months

**Comment by carlosemg64** [comment]
+1 for supporting KairosDB!

**Pull request closed without merging**
