### PR TITLE
Devenv: Fix fake data gen to target mysql server

### PR DESCRIPTION
**Pull request by gamab**
**What this PR does / why we need it**:
I did not see any data in the mysql devenv source when running `make devenv sources=mysql`. Investigating a bit I noticed the fake data generator threw a bunch of `randomWalk:  ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT`. Providing `FD_SERVER` to the `fake-mysql-data` container solved the issue.

image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Jguer — APPROVED** [review]

**Comment by gamab** [comment]
I'm using the latest fake-data-gen:
```bash
docker pull grafana/fake-data-gen
Using default tag: latest
latest: Pulling from grafana/fake-data-gen
Digest: sha256:dc97cce49113f1a4b5f89b90f9a90ec01d8be3fda046507732821f8d51f70e64
Status: Image is up to date for grafana/fake-data-gen:latest
docker.io/grafana/fake-data-gen:latest
```
And here is the logs I was getting.
```bash
docker logs --tail 100 <id>
      ...
randomWalk:  ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at /usr/src/fake-data-gen/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19
    at tryCatcher (/usr/src/fake-data-gen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/fake-data-gen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/fake-data-gen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/fake-data-gen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/fake-data-gen/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/fake-data-gen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/fake-data-gen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/fake-data-gen/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/fake-data-gen/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21) {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/usr/src/fake-data-gen/node_modules/mysql2/lib/connection.js:169:17)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/usr/src/fake-data-gen/node_modules/mysql2/lib/connection.js:169:17)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}
```

But from what I understand, we default to `localhost` if the server is unspecified right?
https://github.com/grafana/fake-data-gen/blob/master/src/app.js#L50

Since in the compose file we are not specifying to use the host network, the `fake-data-gen` container is trying to connect to itself, isn't it? Am I missing something?

**Comment by marefr** [comment]
Verified I got the same problem. Something must have changed in fake-data-gen recently :thinking: This [change](https://github.com/grafana/fake-data-gen/pull/21) probably. Tried to run the postgres docker block and it doesn't work at all even with a change similar to yours

**Review by marefr — APPROVED** [review]
This change make sense

**Comment by gamab** [comment]
> Tried to run the postgres docker block and it doesn't work at all even with a change similar to yours

I've been trying to fix postgres for the past 2 hours. Specifying the server is not the only error there. Something with `node` version, `sequelize` and `pg` is bugging :/

**Pull request merged**
