### PR TITLE
Chore: Update developer guide with instructions building from Windows

### LINKED ISSUE #40839: Build: Docker build fails due to missing call to gen-go
**What happened**:
Using the following command to build the backend on Windows fails:
`go run build.go build`

**What you expected to happen**:
Would expect the go backend binary to build.

**How to reproduce it (as minimally and precisely as possible)**:
On windows just run the command by following the procedure here for building on windows: https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md

**Anything else we need to know?**:
This is what the log looks like:
```
$ go run build.go build
Version: 8.3.0, Linux Version: 8.3.0, Package Iteration: 1635031358pre  
building binaries build
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/windows-amd64/grafana-server.exe
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go build -ldflags -w -X main.version=8.3.0-pre -X main.commit=f496c31018 -X main.buildstamp=1634921041 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server       
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg\cmd\grafana-server\commands\cli.go:168:12: undefined: server.Initialize
exit status 2
exit status 1
```

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: Windows 10
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: go version go1.17.2 windows/amd64

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Updated the developer guide with additional instructions for building from Windows, i.e. how to generate code using Wire.

Using `make build-docker-full` failed with the below error why I had to change how `local` directory is copied.
```
Step 20/49 : COPY ./local/* ./local/
COPY failed: no source files were specified
make: *** [Makefile:107: build-docker-full] Error 1
```

**Which issue(s) this PR fixes**:
Fixes #40839 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by guicaulada** [comment]
What happens if the local directory is not present?
Do you get any issues?

**Review by guicaulada — APPROVED** [review]

**Review by AgnesToulet — APPROVED** [review]
LGTM! To be able to use the `make` commands on Windows, I updated the .bingo/Variables.mk file with the following changes:
image

If that's working on other platforms, we could make the change in the repo as well.

**Review by atifali — APPROVED** [review]
instructions work as expected on windows👍

**Comment by sylr** [comment]
Can we back-port this on v8.3.x ?

**Comment by marefr** [comment]
@sylr sure thanks

**Pull request merged**
