### PR TITLE
Alert: update story to use controls

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
This PR updates story to use controls instead of knobs
**Which issue(s) this PR fixes**:
Relates to #30182

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
This story was not using any knobs from what I can tell, so no need to adds controls here. But does not hurt I guess

**Review by torkelo — APPROVED** [review]
But works and looks good!

**Comment by hugohaggmark** [comment]
Going through this today, I've noticed the following:

- I think `onRemove` & `onButtonClick` don't add anything to the story
- `buttonText` doesn't work, or I couldn't figure out how it worked
- `buttonContent`, seems strange you need to enter a string surrounded with `""`, can this be improved somehow?

image

**Comment by thisisobate** [comment]
Alright @hugoh.
Would look into this.

**Pull request merged**
