### PR TITLE
Alerting: Load default configuration from status endpoint, if Cortex Alertmanager returns empty user configuration

### LINKED ISSUE #35729: Alerting: if there is no cortex user config, load default from /status endpoint
**What would you like to be added**:

When interacting with a cortex alertmanager, if there is no user config returned from the user config endpoint `/api/alertmanager/{Recipient}/config/api/v1/alerts` we should get the default one from `/api/alertmanager/{Recipient}/api/v1/status` 

**Why is this needed**:

### PR DESCRIPTION
**Pull request by domasx2**
**What this PR does / why we need it**:

For cortex alertmanager, if user config endpoint returns empty config, will load default config from alertmanager status endpoint.

**Which issue(s) this PR fixes**: 

Fixes #35729

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
go.mod changes LGTM. I'll leave the rest for you to review. Or is there something specific in the ngalert changes you would like me to look at?

**Comment by domasx2** [comment]
> go.mod changes LGTM. I'll leave the rest for you to review. Or is there something specific in the ngalert changes you would like me to look at?

I think you were added as reviewer automatically after PR got retargeted, sorry!

**Comment by papagian** [comment]
> go.mod changes LGTM. I'll leave the rest for you to review. Or is there something specific in the ngalert changes you would like me to look at?

sorry, I don't know how I managed to do this (maybe by mistake):
`papagian requested a review from grafana/backend-platform as a code owner 15 hours ago`

**Review by nathanrodman — APPROVED** [review]
LGTM 🚢

**Pull request merged**
