### PR TITLE
Fixing issue 16090 where Grafana uses illegal characters in requests …

### LINKED ISSUE #16090: Grafana uses illegal characters in requests to Prometheus
**What happened**:
Requests to prometheus (and others) that use the `/api/v1/series` URLs have `[` and `]` in the URL, but these characters are illegal with out being escaped.

**What you expected to happen**:
`[` & `]` characters should be encoded to `%5B` and `%5D`
see [here](https://github.com/grafana/grafana/blob/fe1c204d4addbbdd37ba7b6bdb30794a9768b8fc/public/app/plugins/datasource/prometheus/metric_find_query.ts#L135) and [here](https://github.com/grafana/grafana/blob/fe1c204d4addbbdd37ba7b6bdb30794a9768b8fc/public/app/plugins/datasource/prometheus/metric_find_query.ts#L72).

**How to reproduce it (as minimally and precisely as possible)**:
Use a Tomcat server to forward requests to prometheus.
Tomcat will reject urls with invalid characters.

**Anything else we need to know?**:
I tested the requests directly to prometheus with `series?match%5B%5D=blah blah blah` and it works as expected.

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: prometheus
- OS Grafana is installed on: macOS
- User OS & Browser: macOS & Chrome
- Grafana plugins: None
- Others: None

### PR DESCRIPTION
**Pull request by BhartiAgrawalNvidia**
…to Prometheus

**What this PR does / why we need it**: Grafana uses illegal characters in requests to Prometheus

**Which issue(s) this PR fixes**: https://github.com/grafana/grafana/issues/16090

Fixes https://github.com/grafana/grafana/issues/16090

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by BhartiAgrawalNvidia** [comment]
Hi can I get an update as to the ETA for the review on this?

**Comment by BhartiAgrawalNvidia** [comment]
Any updates here?

**Comment by marefr** [comment]
@BhartiAgrawalNvidia sorry. We're planning to review this soon. However, seems like referenced issue #10690 is a PR. Could you please update description to reference the correct issue this PR solves? Thanks

**Comment by BhartiAgrawalNvidia** [comment]
updated to https://github.com/grafana/grafana/issues/16090

**Comment by aocenas** [comment]
Hey @BhartiAgrawalNvidia, hope you don't mind I pushed a commit here. I wanted to check we could make the creation of those params better and not rely on remembering to encode manually each part. So I changed it to use URLSearchParams API. I think this makes it more readable and less error prone but one change this produces is that it encodes space as `+` instead of `%20`. As far as I read it should be fine (see https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20 and https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20 and their comments and links) but it may be better for you to test this version with your server to be sure.

**Comment by BhartiAgrawalNvidia** [comment]
does this encode '[]' I do not see it doing that. We still need to encode the '[]' in this case as well.

**Comment by aocenas** [comment]
@BhartiAgrawalNvidia yes it does you can see that in the test cases. The only change in them was because of the `+` vs `%20` difference.

**Comment by BhartiAgrawalNvidia** [comment]
ok great will test this with my deployment and update here. thanks.

**Comment by aocenas** [comment]
Hey @BhartiAgrawalNvidia does this still work for you or did you encounter any issues?

**Comment by BhartiAgrawalNvidia** [comment]
I have not tested it yet. Will do it this weekend. sorry about the delay.

**Comment by BhartiAgrawalNvidia** [comment]
@aocenas this works for me. Thanks.

**Comment by BhartiAgrawalNvidia** [comment]
Hi, I tested this. It works fine. I thought I added a comment last week but do not see it.

**Comment by BhartiAgrawalNvidia** [comment]
Hi, 

Any updates on this?

**Comment by aknuds1** [comment]
@aocenas @dprokop does this look fit to merge?

**Review by aocenas — APPROVED** [review]

**Comment by aocenas** [comment]
@aknuds1 Can you merge this? Not sure if I cannot merge this because I made some changes here or because there is missing check from build-pipeline.

**Comment by aknuds1** [comment]
@aocenas I'll fix it by merging latest master into it, which should fix CI issues.

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Comment by BhartiAgrawalNvidia** [comment]
Hi, 
Which version of Grafana will this be included in?
Thanks
Bharti.

**Comment by aocenas** [comment]
@BhartiAgrawalNvidia This should be part of 7.0 release.

**Comment by BhartiAgrawalNvidia** [comment]
@aocenas I do not see it listed in the change log for the 7.0 release of Grafana. Did it not make it?

**Comment by BhartiAgrawalNvidia** [comment]
don't see this in 7.1.3 either :(

**Comment by zoltanbedi** [comment]
Hi @BhartiAgrawalNvidia, I can see your fix in 7.1.3 https://github.com/grafana/grafana/blob/v7.1.3/public/app/plugins/datasource/prometheus/language_provider.ts#L411 we don't put every fix in to changelog thats why didn't see it.

**Comment by BhartiAgrawalNvidia** [comment]
great thanks.

**Pull request merged**
