### PR TITLE
Explore: Support fields interpolation in logs panel

### LINKED ISSUE #58235: Glue: Support string interpolation from field values
Make sure that target query can contain variables to be filled in with field values. For example:

For a data frame:

| time | app | level | msg |
|-----|-----|------|------|
| 1 | foo | info | Status OK |
| 2 | foo | error | Error |

It should be possible to use any of `time`, `app`, `level`, `msg` values inside the target query by using variables.

Plugin-based data links use `${__value.raw}` variable to use the value of field. For example in logs panel: if a data link attached to `traceId` it will show a button next to `traceId` and use the value of the traceId to replace `${__value.raw}`

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

The logic to interpolate the query of a data link supports using field values from the same row but to make it work the component needs to pass `DataFrame` object so the interpolation logic can extract it. LogPanel doesn't pass `DataFrame` (I guess because it never intended to support anything else but traceId).

With this change, other field values can be used in the interpolated query in generic data links but it also can be useful in old-fashioned plugin data links inside external URLs.

This will enable more complex flows with generic links (see videos in _How to test it_ section), examples:
* Running metrics query based on multiple fields from the log line
* Running log queries based on metric labels (only in a table view for now [^table])
* It's also now possible to run a trace query using generic data links

**Which issue(s) this PR fixes**:

Relates to #58235

**Special notes for your reviewer**:

<details><summary>How to test it</summary>

* Grab https://github.com/grafana/tns
* Go to `/production/docker`
* Change Grafana port so it doesn't clash with you local Grafana instance
* Spin the docker image

Use the following provisioning file for tns:  https://gist.github.com/ifrost/1bb1340d20c460c85db24406eabd2531

Run sample queries (check comments in provisioning file or videos below):

https://user-images.githubusercontent.com/745532/200581824-9eea6f31-c1f3-4418-8ce4-a39fd16bd46f.mov

https://user-images.githubusercontent.com/745532/200581891-8409b807-1a22-40b9-9af2-91994e1fb883.mov

</details>

[^table]: In the provisioned file there's a link that opens metrics for given log level in a table view (_Show metrics with this level_). This is because adding generic data links with field values to a graph view doesn't make much sense yet. The only fields that can be used in a graph view are `Time` and `Value`. Once we introduce transformations it will be possible to create flows like with the table and opening logs for metrics using not only field values, but also labels.

### CODE REVIEW

**Review by matyax — COMMENTED** [review]
Would it be possible to add testing coverage to at least some of the changes in this PR?

**Comment by ifrost** [comment]
> Would it be possible to add testing coverage to at least some of the changes in this PR?

Since this change affects internals of data links interpolation, we could do some white-box testing (e.g. unit test: assert if data-frames object is passed through all the layers to `getFieldLinksForExplore()`, or at component level: assert if with specific data frames provided a correctly interpolated data link is created and check its internal structure, e.g. mock onSplit function). What would probably bring more value is do Explore-level integration test for test this functionally in full (clicking on the button opens split view). We're planning to add integration tests for new data link related features in https://github.com/grafana/grafana/issues/54888.

**Review by Elfo404 — APPROVED** [review]

**Comment by matyax** [comment]
I understand the component tests can be more challenging, but `public/app/features/logs/components/logParser.ts` could 100% have a test case for those changes.

**Review by matyax — APPROVED** [review]
Approving to unlock progress from my squad, but I still think that having a test for logPaser.ts would be very positive.

**Pull request merged**
