### PR TITLE
Alerting: make `/api/prometheus/grafana/api/v1/rules` faster

### PR DESCRIPTION
**Pull request by domasx2**
**What this PR does / why we need it**:

I was testing API perf, and spent some time messing around with `/api/prometheus/grafana/api/v1/rules` to see if there's any low hanging fruit to make it go faster.

By fetching all alert rules in one db query instead of query per group there's about 40% improvement in response time. With ~3000 rules, sqlite 440ms -> 260ms, postgres 1100ms -> 660ms on my machine

### CODE REVIEW

**Comment by gotjosh** [comment]
Can you plesae post the queries we used to do alongside an example query plan and the new query's query plan?

**Comment by domasx2** [comment]
> Can you plesae post the queries we used to do alongside an example query plan and the new query's query plan?

Did not modify any existing queries or introduce new ones. Refactored API handler to use `GetOrgAlertRules` to get all of the rules at once, instead of sequentially calling `GetRuleGroupAlertRules` for each rule group, essentially a db query per rule. I'll try to get the query plans tomorrow, but I don't think they will be interesting

**Comment by gotjosh** [comment]
I just want to get a gauge on what changed from the database side, if you turn query logging on, you can see which queries we were doing before vs now, I think that'll give us a good idea of where the improvement is coming from.

**Comment by domasx2** [comment]
> I just want to get a gauge on what changed from the database side, if you turn query logging on, you can see which queries we were doing before vs now, I think that'll give us a good idea of where the improvement is coming from.

Oki, so, on `main` we do query below for every rule group. And we have group per rule, so in practice for every rule. 3000 rules, 3000 queries.
```sql
SELECT * FROM alert_rule WHERE org_id = $1 and namespace_uid = $2 and rule_group = $
```
Postgres analysis:

```
Index Scan using IDX_alert_rule_org_id_namespace_uid_rule_group on alert_rule as alert_rule (rows=1 loops=1)
Index Cond: ((org_id = 1) AND ((namespace_uid)::text = 'aDUynZI7z'::text) AND ((rule_group)::text = 'Folder-4-94'::text))
```

On this branch we query below query only once to get all rules:

```sql
SELECT * FROM alert_rule WHERE org_id = $1
```

Postges analysis:

```
Seq Scan on alert_rule as alert_rule (rows=3000 loops=1)
Filter: (org_id = 1)
```


I believe the improvement is coming from removing the overhead of doing N quries to db, one for every result item. 
I tried to get a trace, which would better illustrate the point, but it seems only top level http handlers are instrumented...

**Comment by gerobinson** [comment]
This makes sense to me, and the improvement should be more than 200% for customers who run Grafana and their database on separate hosts. That said I am surprised we are doing `SELECT * FROM alert_rule WHERE org_id = $1` as we will want to avoid doing sequential scans for larger result sets. Perhaps we need to start looking at pagination if we are expecting users to have 1000s of alert rules?

**Comment by gerobinson** [comment]
I think this change will mean I need to change the database index I am adding in #39476 as we are removing the condition on `namespace_uid`.

**Comment by domasx2** [comment]
Maybe somewhat contraversially, I think thousands is not a lot and ok to fetch in one go :)

I only have 1 org currently, so seq scan makes sense. I believe if there were many orgs, and the org currently being retrieved occupied a small percentage of the table, an index scan would be chosen. 

Pagination is tricky with the current UX approach, and I think unlikely to have good perf savings.

I think some smaller improvements could easily be had here by removing `GetOrgRuleGroups` and `GetNamespaces` calls above and doing a join with `dashboard` table instead. 

Big improvement could possibly be had by keeping this data in memory and not doing a db call at all - we already have most of it in memory in the alerting engine anyway?

**Review by gotjosh — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
I'd like us to wait on approval from @gerobinson as well given he's been working around this area more than myself.

**Review by grobinson-grafana — APPROVED** [review]

**Pull request merged**
