### PR TITLE
Feature change title font size

### PR DESCRIPTION
**Pull request by xobust**
Needed this for a project at work, tried my best to create a solution.

Implement: #1875

### CODE REVIEW

**Comment by torkelo** [comment]
Sorry we cannot have this, will make it very hard to do design changes without breaking dashboads. 

You can create rows with visible row titles & set row title heading size (in row options)

**Comment by kennethmac2000** [comment]
Should the need to be able to change the product easily trump the user experience?

Dashboards are generally displayed on digital signage displays, where the need to be able to see important text like titles from a distance is, i would say, a key feature.

Would a compromise be for the product to provide a few predefined title sizes (eg, small, medium and large), rather than allowing arbitrary font sizes to be used?

**Comment by torkelo** [comment]
It's user experience we care about, how to keep dashboards from looking consistent and not like a mess of different font sizes, also we care about about backwards compatibility, so we can update things and not break dashboards, panels with different title sizes will make this hard, given we are about to change dashboard layout engine. 

You can  create rows with row titles with many different font sizes, if you have grafana on a 4k TV increasing the font size browser zoom has a good effect to make titles more legible. 

After we switch panel layout engine we might reconsider panel titles with different font sizes but I still think it can be a big mistake that later will regret or have to revert

**Comment by glajchs** [comment]
>After we switch panel layout engine we might reconsider panel titles with different font sizes but I still think it can be a big mistake that later will regret or have to revert

I can surely sympathize with the extra work incurred in making variable size fonts when trying to layout your graphs.  However I highly doubt this is a feature you'd regret implementing, especially given that you already have the "kiosk" mode built in to your product.  If you were looking to make your software usable in browsers on peoples' personal desktops and laptops only, then I could understand not wanting to pursue bigger font sizes for the titles, labels, axis labels, etc.

But the current font sizes make these graphs pretty worthless on TVs, which is a pretty common use case for these graphs.  I ended up jerry-rigging readable font sizes for all of the above with some CSS I put into a dashboard using the "text/HTML" panel type, and it made it so that our dashboard which was originally not going to be feasible to make and put on the TV, feasible (see my comment [here](https://github.com/grafana/grafana/issues/12227#issuecomment-444982123)).

>if you have grafana on a 4k TV increasing the font size browser zoom has a good effect to make titles more legible.

I found that using browser zoom made the graphs worthless.  It provided almost no data points and everything got out of wack.  Sure it helps on a desktop, but on a TV, no way.  This was using some 4K TVs oriented vertically.

Granted, I'm not trying to say supporting these things will be easy, but if you're going to try and support kiosk mode, it doesn't really feel like an optional feature to implement.

**Comment by torkelo** [comment]
Can you describe why browser zoom did not work? It usually works great

**Comment by glajchs** [comment]
Sorry you'll have to give me a day or so to find free time enough to get some good pictures of this.  Basically what happens is that, to get the text to be big enough to read far away from the TV monitors (not too far, maybe just 10 feet), I had to put the browser zoom all the way up to 200%.  You can emulate the approximate browser size I'm talking about by going to about 1800-1900px in width.  At this point, many of the graphs that used to fit on the TV have fallen off the bottom, while the "singletext" style of widget's inner numbers can be made huge, the titles, labels, and axis labels are even then still pretty small.  It's almost workable, but you get less graphs per screen.  If I do one more zoom level to 250%, every graph is it's own line, and I can fit only a small fraction of the required graphs on one screen.

Whereas what I got by changing the font sizes only was good graph quality still, and each row only had to be a few pixels taller if that.  I'll try to get some screenshots later today.

**Comment by lealceldeiro** [comment]
> Sorry we cannot have this, will make it very hard to do design changes without breaking dashboads.
> 
> You can create rows with visible row titles & set row title heading size (in row options)

As of Grafana 7.3.0 I don't think this is possible.
Under "Row Options" there are only two options:

- Title
- Repeat for

So, @torkelo, could you elaborate on that please?

**Pull request closed without merging**
