### PR TITLE
e2e guide: improves code snippet to be more readable

### PR DESCRIPTION
**Pull request by thisisobate**
**What this PR does / why we need it**:
It was a bit hard for me to understand what was written in the "Aria-Labels vs data-testid" section. This PR improves it.

### CODE REVIEW

**Review by hugohaggmark — COMMENTED** [review]
Hmm, I can't see how this PR makes the code more readable to be honest.

**Comment by thisisobate** [comment]
I felt it makes sense to reference a data-testid value that's already been used in the examples.

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉

**Comment by hugohaggmark** [comment]
> I felt it makes sense to reference a data-testid value that's already been used in the examples.

You're right, reading the whole text it made more sense. Thank you!

**Pull request merged**
