### PR TITLE
Select: Allow custom value for selects

### LINKED ISSUE #19772: Ability to add options to select field
Would like the ability to type custom options into dropdown field. Can be toggled on and off with a prop (ex: allowCustom).

In Angular, we have the ability to add custom options on dropdown fields in Query Editor but now that we are converting to React, we need the same functionality.

### PR DESCRIPTION
**Pull request by torkelo**
Just to get the process started I did a quick test using Creatable seemed promising.

Fixes #19772

Needs to be added to async version as well and then to Segment component (where this will primarily be used)

### CODE REVIEW

**Comment by torkelo** [comment]
@sunker if you can continue and test this next week that be great (and add it to segment)

**Review by sunker — APPROVED** [review]
I think it looks great! Added allowCustomValue prop to segment and segment async.

**Comment by sunker** [comment]
I'd also like to add support for isMulti to segment, but I'll do that in another pr later this week.

**Comment by torkelo** [comment]
unit tests are failing, think we need to update snapshots

**Comment by sunker** [comment]
Ok I'll fix

**Pull request merged**
