### PR TITLE
Added support for heatmaps

### PR DESCRIPTION
**Pull request by jcellary**
I implemented a new panel type - heatmap. It looks like this:
screenshot from 2014-09-12 17 55 38

This addresses the following issue: https://github.com/grafana/grafana/issues/600

As storage I used InfluxDB, I did not test it on other database types. In order to display the data eather the histogram command from InfluxDB  should be used or a custom query with columns named "count" and "bucket_start" (actually we use custom queries, as we have to aggregate the data before it goes to Influx). For drawing I used the "markings" from flot.

I tried no to change too much inside of grafanas core, so I hope merging it won't be too difficult. Also I'm neither Grafana nor AngularJS expert, so I hope I didn't break anything along the way :) 

When developing the new dashboard I concentrated on our companies needs, there are for sure things that could be done to make it easier to use for others. My ideas for improvement:
- The heatmap can only display one data series, so when multiple series are defined the first one containing columns "count" and "bucket_start" is used. It would make sense to block adding multple queries for heatmaps as they are useless in this case, but I didn't want to make changes to the query editor.
- I'm not sure how intuitive the UI for the heatmap is, maybe some hints on how to use it would be useful
- Needs to be tested with other database types
- There are no hints when moving to a specific "pixel" on the heatmap, as there are on datapoints on a graph.
- I couldn't get transparency to work, maybe using it instead of black background color would make the heatmap look nicer.
- I implemented the heatmap by copying the graph and adjusting it, I tried to clean up the code from any unused elements, but It may happen I ommited something, since It tok me a while to understand all the dependencies.

I hope you can make some use of the code I've written, let me know if you have any questions, I'll be happy to answer :)

### CODE REVIEW

**Comment by marco-hoyer** [comment]
+1, would be great to have this in grafana!

**Comment by utkarshcmu** [comment]
+1

**Comment by Dchamard** [comment]
+1

**Comment by ichernetsky** [comment]
Support for heatmaps is a must. +1

**Comment by mtanda** [comment]
+1

**Comment by bergquist** [comment]
Heatmaps would be awesome!
But the state of this PR is kinda tricky. Unmergable and far behind master. Unfortunately these things happens sometime but unless someone give this some love I think we have to close it :(

**Comment by adrianlzt** [comment]
Will be great to get this added

**Comment by evanbreznyik** [comment]
:+1:

**Comment by gedejong** [comment]
+1

**Comment by hailpam** [comment]
I do believe that heatmaps are a must. +1

**Comment by xlash** [comment]
+1

**Comment by dhirajforyou** [comment]
+1

On Sat, Apr 16, 2016 at 10:42 PM, Guillaume Nourry-Marquis <
notifications@github.com> wrote:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/pull/797#issuecomment-210860618>
>



-- 
Thanks and regards,

Govind Dhonddev

**Comment by elvarb** [comment]
Is this closed for good or?

**Comment by bergquist** [comment]
@elvarb this pull request is closed for good. The issue is still open

**Comment by elvarb** [comment]
Right will follow issue then👍

**Comment by dstreppa** [comment]
+1

**Comment by jdbranham** [comment]
I've added a heatmap capability to the diagram plugin, but it shouldn't be too difficult to create a standalone heatmap using the 'table' panel plugin as a guide.

https://github.com/jdbranham/grafana-diagram

Thoughts?

**Comment by elvarb** [comment]
That looks amazing!  Love the weather map, will definitely play with this

**Comment by jdbranham** [comment]
@elvarb Thanks!
Let me know what you think.

**Comment by elvarb** [comment]
@jdbranham as you can see on the issue tracker I'm liking this very much :)

**Comment by rehevkor5** [comment]
Comparable to https://www.datadoghq.com/blog/detecting-outliers-cloud-infrastructure-datadog-heatmaps/

**Pull request closed without merging**
