### PR TITLE
Adjust to make possible to use template variable in tag key for opentsdb datasource

### PR DESCRIPTION
**Pull request by gutomantovani**
Adjust to make possible to use template variable in tag key for opentsdb datasource

### CODE REVIEW

**Comment by bergquist** [comment]
@utkarshcmu any chance that you could take a look on this?

**Comment by utkarshcmu** [comment]
I'll take a look at this PR today.

**Comment by utkarshcmu** [comment]
This PR works but it is missing the UI part. This PR is not ready for merging yet. For example, when i add a tag (key=$something, value=m*). The query editor does not show it in th tag list. AngularJS ignores keys starting with $.

**Comment by utkarshcmu** [comment]
@gutomantovani Some more work is required on query editor ctrl + html, then this PR will be complete.

Anyway, +1 for this feature. This is useful.

**Comment by torkelo** [comment]
closing this due to lack of feature request issue, and unit tests, please reopen when ready.

**Pull request closed without merging**
