### PR TITLE
CloudWatch: Add Route53 DNSQueries metric and dimension

### PR DESCRIPTION
**Pull request by erkolson**
**What this PR does / why we need it**:
Adds the AWS Cloudwatch Route53 `DNSQueries` metric

**Which issue(s) this PR fixes**:
n/a

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM based on https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-hosted-zones-with-cloudwatch.html

**Comment by marefr** [comment]
@erkolson thanks. Can you please rebase/merge with master and then we can merge this.

**Comment by erkolson** [comment]
I think this is up to date now, hopefully it can be merged before master is updated again 😆

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
