### PR TITLE
Set secure headers with unrolled/secure.

### LINKED ISSUE #6820: Feature request: Set security headers
It would be useful if grafana could be configured to set security-related headers (`x-xss-protection`, `x-frame-options`, `content-security-policy`, etc). In my specific use case, I need to add these headers to comply with nist guidelines, but adding them would also add extra protection against xss and other attacks. Would you all be interested in using a library like https://github.com/unrolled/secure, or in adding the headers that it adds manually?

### PR DESCRIPTION
**Pull request by jmcarp**
Set secure headers with unrolled/secure.

[Resolves #6820]

Note: this is a WIP--I'm looking for feedback on approach (I used unrolled/secure, but could set headers manually if you all don't want to include more libraries). If the approach makes sense, I'll add docs etc to get this ready for merge.

### CODE REVIEW

**Comment by torkelo** [comment]
this looks good, will try to find time to review soon.

**Comment by torkelo** [comment]
So this looks great! 

The security options needs to be added to the defaults.ini file and sample.ini file (commented out)
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L138
https://github.com/grafana/grafana/blob/master/conf/sample.ini#L125

I think all the keys should all be prefixed with http_ as they relate to http security, or maybe its own section? ? [security.http] 

They also need to be documented.

**Comment by jmcarp** [comment]
Thanks for reviewing--I moved the new settings to a `[security.http]` section and updated the docs and defaults. I don't have preferences about what the section is called, so I'd be happy to change to prefixing with `http_` if you prefer.

**Comment by jmcarp** [comment]
Hi again! I saw that #6820 was dropped from the 4.1 release. Do you all think this can make into 4.2? LMK if this needs more revisions when you have time.

Thanks!

**Comment by torkelo** [comment]
Yea, sorry, since 4.1 is in beta, wanted to move new features out of 4.1 milestone, added this to 4.2 milestone, merge soon

**Comment by bergquist** [comment]
Looks good. 

But I think all settings should have an example to make it easier for the user to get started. Right now its hard to tell if the property is expecting an int/string or bool unless you look at settings.go

**Comment by jmcarp** [comment]
Agreed! Just added example settings and resolved a small merge conflict.

**Comment by bergquist** [comment]
Looks good. @torkelo I think we should merge this before soon so people can try it as as early as possible.

**Comment by torkelo** [comment]
There features are great, security is very important. But now looking back at this PR it feels that these features are turning Grafana into a fully featured public facing web server. Something that services like nginx / apache / haproxy are much better and are more mature & feature rich. 

Is there a good argument for putting these features into Grafana itself when they can already be added by a http proxy?

thoughts @DanCech @woodsaj ?

**Comment by DanCech** [comment]
I can see the argument for keeping the grafana webserver simple and delegating to a reverse proxy, but at the same time I think that for a tool like grafana that's typically internal-facing there's value in being able to run it standalone without requiring a reverse proxy and still supporting these security features.

**Comment by jmcarp** [comment]
I agree that it's trivial to set these headers using nginx, haproxy, etc, but I also think it's even easier if they're configurable via grafana directly. And this isn't attempting to replicate all the functionality of a reverse proxy--it's just exposing a handful of security-related headers that users might not otherwise think about.

My team has a slight preference for getting this merged, but we're also fine with standing up nginx to add these headers--what do you all think?

**Comment by torkelo** [comment]
My biggest gripe with adding something like this is that i adds 14 new config options to the config file and config docs, bloating those files with settings only a extremely small set of users will ever use. But I do see the value of having this included. 

Just noticed that the defaults are not set in the defaults file. https://github.com/grafana/grafana/pull/6838/files#diff-552efc423e48c03ad779d46cab991752R169

Also the configuration docs does not mention what the value should be set to (true/false, some string, hard to tell).

**Comment by bergquist** [comment]
We decided not to merge this.

Most of these security issues should be address by using a reverse proxy instead. Apache and nginx are much more focused on security then we will ever be. Instead of solving everything we should focus on what we are good at :)

**Pull request closed without merging**
