### PR TITLE
Chore: Upgrade Storybook to 5.3.9

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
There are some new cool feature sin Storybook when it comes to documentation.

### CODE REVIEW

**Comment by dprokop** [comment]
Seems like there is some issue with webpack prod build after bumping the version. Also, didn't manage to run storybook locally, quite a lot of issues like this:

```

ERROR in ./src/components/Forms/Field.mdx 4:0
Module parse failed: Unexpected token (4:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Field } from './Field';
|
> <Meta title="MDX|Field" component={Field} />
|
| # Field
 @ ./src/components/Forms/Field.story.tsx 7:0-30 13:18-21
 @ ./src sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.story\.(js|jsx|ts|tsx|mdx))$
 @ ./.storybook/generated-entry.js
 @ multi /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/core/dist/server/common/polyfills.js /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.ts /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js /Users/dominik/go/src/github.com/grafana/grafana/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

and this pops up when running `yarn storybook`: 
https://gist.github.com/dprokop/1e85eb8f9b6d9ce668bb567b69da65a7#file-gistfile1-txt

**Comment by mckn** [comment]
@dprokop hmm, let me see if I can reproduce this. We should probably upgrade to 5.3.9 as well.

**Comment by mckn** [comment]
> Seems like there is some issue with webpack prod build after bumping the version. Also, didn't manage to run storybook locally, quite a lot of issues like this:
> 
> ```
> 
> ERROR in ./src/components/Forms/Field.mdx 4:0
> Module parse failed: Unexpected token (4:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | import { Field } from './Field';
> |
> > <Meta title="MDX|Field" component={Field} />
> |
> | # Field
>  @ ./src/components/Forms/Field.story.tsx 7:0-30 13:18-21
>  @ ./src sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.story\.(js|jsx|ts|tsx|mdx))$
>  @ ./.storybook/generated-entry.js
>  @ multi /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/core/dist/server/common/polyfills.js /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.ts /Users/dominik/go/src/github.com/grafana/grafana/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js /Users/dominik/go/src/github.com/grafana/grafana/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
> ```
> 
> and this pops up when running `yarn storybook`:
> https://gist.github.com/dprokop/1e85eb8f9b6d9ce668bb567b69da65a7#file-gistfile1-txt

I can't reproduce this error. But it looks like the build is failing due to warnings about peer dependencies. Would be awesome if you have time to help me have a look at that one @dprokop .

**Review by dprokop — APPROVED** [review]
Works like a charm!

**Pull request merged**
