### PR TITLE
CloudWatch: Add eu-south-1 Cloudwatch region

### LINKED ISSUE #31197: [Cloudwatch] Missing region eu-south-1
**What happened**:
Tried to add Cloudwatch monitoring for some elements in eu-south1. However, the region is missing from the list

**What you expected to happen**:
Be able to select eu-south-1 from the dropdown menu

**Environment**:
- Grafana version: 7.4.1

### PR DESCRIPTION
**Pull request by rubycut**
Fixes #31197

### CODE REVIEW

**Comment by joshhunt** [comment]
@sunker I wonder if the list of regions can be fetched from the API? Or is this list further restricted by certain feature availability? 

It looks like some AWS services have a DescribeRegions endpoint, but not Cloudwatch? https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html

**Review by sunker — CHANGES_REQUESTED** [review]
Thanks for contributing @rubycut! 

Unfortunately, there's one hard coded list of region in the backend that needs to be updated too. 
https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L25

**Comment by sunker** [comment]
> @sunker I wonder if the list of regions can be fetched from the API? Or is this list further restricted by certain feature availability?
> 
> It looks like some AWS services have a DescribeRegions endpoint, but not Cloudwatch? https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html

Correct! We already use that [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L332). However, that will only work once you have credentials setup, and that you won't have the first time you enter the configuration page. That's why the regions need to be hard coded too. That's kind of a design flaw of how the config page work IMO.

**Comment by rubycut** [comment]
> Thanks for contributing @rubycut!
> 
> Unfortunately, there's one hard coded list of region in the backend that needs to be updated too.
> https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L25

Second file is changed.

**Comment by igpix** [comment]
> > Thanks for contributing @rubycut!
> > Unfortunately, there's one hard coded list of region in the backend that needs to be updated too.
> > https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L25
> 
> Second file is changed.

@sunker @aocenas waiting for your approval! I have to install grafana as soon as possible, thank you!

**Review by sunker — APPROVED** [review]
Thanks @rubycut!

**Comment by igpix** [comment]
@sunker when could be available release 7.5.0 ?

**Comment by sunker** [comment]
beta release mid March I think

**Comment by igpix** [comment]
> beta release mid March I think

is there a way to use this fix in the current release? is installing grafana from sources an option?
thanks

**Comment by sunker** [comment]
sure! check out the [docs](https://grafana.com/docs/loki/latest/installation/install-from-source/#build-from-source)

**Comment by igpix** [comment]
> sure! check out the [docs](https://grafana.com/docs/loki/latest/installation/install-from-source/#build-from-source)

thanks @sunker. as far I understood loki is more related to log management. my goal instead is to visualize metrics already available in cloudwatch (but data source lacks of eu-south region)

**Pull request merged**
