### PR TITLE
Scuemata: Add test to validate devenv resources

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR is for validating our own devenv resources (dashboards, panels) against scuemata.

**Validation Errors**:
*General (null value related)*:
* `failed validation: Family.lineages.0.0.id: conflicting values null and number (mismatched types null and number) (and 3 more errors)`
* `failed validation: Family.lineages.0.0.panels.0.datasource: conflicting values null and string (mismatched types null and string)`
* `failed validation: Family.lineages.0.0.gnetId: conflicting values null and string (mismatched types null and string)`
* `failed validation: Family.lineages.0.0.refresh: conflicting values false and string (mismatched types bool and string)`
* `failed validation: Family.lineages.0.0.panels.0.options: conflicting values false and {...} (mismatched types bool and struct)`
* `failed validation: Family.lineages.0.0.panels.1.repeat: conflicting values null and string (mismatched types null and string)`
* `failed validation: Family.lineages.0.0.panels.2.fieldConfig.defaults.decimals: conflicting values null and number (mismatched types null and number)`
* `failed validation: Family.lineages.0.0.panels.4.fieldConfig.defaults.decimals: conflicting values "" and number (mismatched types string and number)`
* `failed validation: Family.lineages.0.0.panels.15.fieldConfig.defaults.decimals: conflicting values "2" and number (mismatched types string and number)`
* `failed validation: Family.lineages.0.0.timezone: 2 errors in empty disjunction: (and 2 more errors)` --> timezone was expected to get either "browser" or "utc".
* `failed validation: Family.lineages.0.0.panels.1.type: incomplete value !=""`

*Failed json*:
* `line: 296, "failed validation: illegal byte order mark": in file devenv/dev-dashboards/feature-templating/testdata-nested-variables.json`
* `line: 463, "failed validation: illegal byte order mark": in file devenv/dev-dashboards/panel-table/table_tests_new.json`

### CODE REVIEW

**Comment by sdboyer** [comment]
Kinda hijacked this, sorry. There were a few key things that needed changing, and i figured i'd get them all in one fell swoop.

First, the test introduced here was duplicative of `load.TestDashboardValidity`. That was an outgrowth of `validateResources()` being essentially just a thin wrapper over calls to `VersionedCueSchema.Validate()`. The basic responsibility for validating dashboards most properly resides in that package, as it's where the logic for actually loading the validators lives.

The duplication might not have been such a big deal, but it it turns out that `validateResources()` was actually really slow when called over and over (as the tests do) - the action of loading CUE schema is relatively expensive. I'm pretty sure this is because of the relatively large number of disjunctions, which CUE has some known performance issues with. (They're supposedly improved in v0.4.0; i haven't checked. In any case, we should treat scuemata loading as a possibly-expensive action that we try to cache, if we can.)

Beyond that, more bullet-y:

* I changed the error output to use cue's `errors.Details()`. That's the output that i've been hoping for - it gives us that lovely, line-by-line list of all the places that contribute to unification/validation failure.
* I made it possible to pass a filename to `schema.Resource` in order to make it possible to improve the above line-by-line output. I also changed a bunch of the names used for internal cue `Compile()` calls in order to make at least a bit clearer (and greppable) where those things are. (None of them are actually the cause of failure output, but they show up in the list because of how we compose panels into dashboards)
* I changed `grafana-cli validate-resource` to only do base _or_ dist, with a new param. It defaults to dist.
* I removed ellipses from the dashboard schema to make us validate-closed all the time. We've gotta burn all the issues down, anyway - no sense in breaking it into stages.
* I modified the test to only load devenv dashboards with `schemaVersion` greater than 29. It is not our goal that the schema be able to handle older versions of dashboards (yet), so we only want to use the latest ones.
* I put the `t.Skip()` back into `TestDevenvDashboardValidity()`, as it actually does something now, and it's now our full-on goal to get rid of all these validation issues. I'll be filing an issue presently.
* I added `scripts/validate-devenv-dashboards`, which does essentially the same check as `TestDevenvDashboardValidity()`. The idea is to provide a working example of how to actually use the CLI to do JSON validation, and that it also may be easier for folks who are burning down the schema errors to work with the CLI output than with `go test` output, as the former is more easily diffed.

**Review by sdboyer — APPROVED** [review]
Let's see if i can LGTM what is _technically_ not my PR :)

**Review by ryantxu — APPROVED** [review]

**Comment by ryantxu** [comment]
And that @dsotirakis could never approve!

**Comment by dsotirakis** [comment]
@sdboyer @ryantxu no problem, good that you added changes and merged that. This PR was not to be merged anyway - was only to provide the open/close Scuemata errors. Great to see that at least this turned to be something meaningful! 😁

**Pull request merged**
