### PR TITLE
Alerting: Do not hard fail on templating errors in channels

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does / why we need it**:

We do not want to miss critical errors on templating errors. It is possible that migration will break some templating.

### CODE REVIEW

**Review by gotjosh — COMMENTED** [review]
Looks good so far!

I think we're missing a few instances:

- alertmanager.go:98
- discord.go:103
- email.go:76
- opsgenie.go:96 doesn't have to handle an error anymore
- opsgenie.go:107 what do we do about that one? Maybe have a fallback JSON that's just the labels?
- pagerduty.go:129 isn't that a template error as well?
- slack.go:249 same as above, isn't that a template error as well?

**Comment by codesome** [comment]
> alertmanager.go:98

Not a templating error

> email.go:76

Not exactly templating error (or might be on the evaluation side?), but makes sense to not hard fail on failed URL parsing. That way, this should be fixed for all channels and not just this.

> opsgenie.go:96 doesn't have to handle an error anymore

Not entirely true. There are other errors that can happen

> opsgenie.go:107 what do we do about that one? Maybe have a fallback JSON that's just the labels?

Any solution like this should apply to all channels, most of them have json marshalling. I will keep this for any future PR to fix.

> pagerduty.go:129 isn't that a template error as well?
> slack.go:249 same as above, isn't that a template error as well?

Has parsing URL. So could be treated as non fatal error. But the data should be extended nevertheless else templating will fail for sure. Need to handle it in different way.

**Comment by codesome** [comment]
Working on the URL parsing error now, in the same PR

**Comment by codesome** [comment]
Updated

**Review by gotjosh — APPROVED** [review]

**Pull request merged**
