### PR TITLE
Prometheus: Create AutoSizeInput with dynamic width 

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR creates autosize input for PromQueryEditor. It still needs some works - test it with prefix/suffix, write tests and so on. But for now I would like your feedback on the functionality + code. You can test AutoSizeInput in `Functions -> Label replace`

https://user-images.githubusercontent.com/30407135/154679383-d9b9a0d7-f3ed-41da-80e0-01e81680ed60.mov

https://user-images.githubusercontent.com/30407135/154679396-6ec9a715-7927-411a-9951-929f4a693cec.mov

**Which issue(s) this PR fixes**:
Part of https://github.com/grafana/grafana/issues/44253

### CODE REVIEW

**Comment by torkelo** [comment]
@ivanahuckova sorry for not giving you feedback on this yet, will test now

**Comment by ivanahuckova** [comment]
This is amazing! I didn't know/didn't find `measureText` util. This makes it so much cleaner! I'll test it out and write some tests and create PR from it. Plus I'll change Prom/Loki query builder inputs to AutoSizeInput.

**Comment by ivanahuckova** [comment]
I have added tests for autosize input and used in following parts of PromQueryBuilder:
- Legend input
- Min step input
- Nested query vector matching
- Operation parameters editor (e.g. function -> label replace)

**Review by torkelo — APPROVED** [review]
Took this for another spin! Works great.

**Pull request merged**
