### PR TITLE
Add Polish złoty to currency formatters

### PR DESCRIPTION
**Pull request by mwegrzynek**

### CODE REVIEW

**Comment by marefr** [comment]
Thank you for your first contribution to Grafana! Very appreciated!

**Comment by mwegrzynek** [comment]
Thanks, it was a pleasure :smile: .

**Comment by imranhum1** [comment]
Hi,

I added the 2 lines in respective sections in kbn.ts file under "Grafana\grafana\public\app\core\utils" but it is not showing up in grafana units. My grafana version is 5.1.3.

kbn.valueFormats.currencyAED = kbn.formatBuilders.currency('AED');

{ text: 'Dirhams (AED)', value: 'currencyAED' },

**Comment by marefr** [comment]
@imranhum1 you'll need to rebuild the frontend assets after you've made changes, see [building from source](http://docs.grafana.org/project/building_from_source/#building-grafana-from-source).

**Pull request merged**
