### PR TITLE
[WIP] Dynamic height panels

### LINKED ISSUE #11616: UX: Month/year selection in timepicker lacks styling for dark theme
Month and year selection are in need of some styling for the dark theme.

image

image

### PR DESCRIPTION
**Pull request by ryantxu**
This is a quick and dirty proof-of-conept that aims to start specific discussion on how to best support dynamic height panels in grafana 5. See #10325

This approach:
1. For `scrollable` panels, it adds a user-configured option to save `dynamicHeight`
image

2. `panel_directive.ts` moves the scrollable div above the panel content.  Fixing #11820.  For dynamicHeight panels it passes the div reference to the panel ctrl

3. Use `css-element-queries` to detect height change and trigger relayout

-----
Things to do:
- [ ] Agree on general approach
- [X] Find a reliable place to calculate the height.  `css-element-queries`
- [X] ~~`dynamicHeight` panels should only allow horizontal resizing.~~  The resize behavior seems OK
- [X] Changes to `ctrl.panel.gridPos.h` should not trigger the save dialog
- [ ] Add a note that changing dynamicHeight height property requires save and refresh
- [ ] Testing?  

This is a tricky issue and will need some help 😄

### CODE REVIEW

**Comment by simPod** [comment]
Hey @ryantxu! Thanks, will test it ASAP. What's the role of "only scrollable panels" in this? Why not enable it for all with Dynamic height set to true?

**Comment by torkelo** [comment]
Not sure about this approach, it feels brittle and complex, and will jumpy (the recursive rendering & interaction between panel rendering completed and updating grid dimensions). It will cause an unsaved changes warning as it will update the layout of the dashboard. But not sure what other approaches to take if this is going to be a built-in feature. 

I think to begin with this complexity will have to be handled in each panel that wants dynamic height. So it will have to talk to the grid after each render and update its grid position. But this is just my initial reaction.

**Comment by ryantxu** [comment]
> it feels brittle and complex

ya... My goal here is to find the best solution, and we need to start somewhere :)  This has worked ok in practice and I have not had issues with it being jumpy.

**Comment by ryantxu** [comment]
> Why not enable it for all with Dynamic height set to true?

@simPod -- With the grid layout, the height is set by the grid system, dynamic heights are an edge case so should be an explicit end user option.

**Comment by simPod** [comment]
@ryantxu I meant not to make it default ofc

I meant this condition https://github.com/grafana/grafana/pull/11829/commits/743f50e04c3843144da83edab3c1b3934c772b64#diff-acbf79cc238ab2eaba351bba890ab607R69

but I can see now it's changed to https://github.com/grafana/grafana/pull/11829/files#diff-acbf79cc238ab2eaba351bba890ab607R70 so I guess it's fine

**Comment by ryantxu** [comment]
Here is a panel i wrote to test this under worst case conditions:  `$(jquery).animate()`!
https://github.com/ryantxu/dynamic-height-panel

Animation

**Comment by ryantxu** [comment]
I think the resize behavior is OK.  It is a little weird when making things shorter:

Resize

**Comment by torkelo** [comment]
have been working on react panels (and a new panel editing / changing viz) UX in this branch, https://github.com/grafana/grafana/tree/react-panels 

A ton of work to do, creating a whole new level of base types for metric panels, and reimplmenting panel_directive & metrics panel stuff (but build in another way) but in React. So not sure about adding this feature to the old panel infra, even though the new panel architecture is likely 3-5 months away .

Will create an issue for the react panels & new panel architecture (and migration story) shortly to break it down and show progress & design goals.

**Comment by schmurfy** [comment]
is there a way to have dynamic height panels even with a hack while waiting for a proper implementation ? we also need this feature for table panels and this has been blocking migration to grafana 5 for a while now :/

**Comment by LeDistordu** [comment]
We are stuck in version 5 in the absence of this feature, it is essential for us. Our monitoring screens must be able to retract when it has a lot or a little warning. Would it be possible to integrate this functionality in the next version?

**Comment by torkelo** [comment]
Will sadly close this as don't want add features to the angular panel architecture. 

We are slowly making progress on react panels.  You can enable the current react panels using [panels] enable_alpha = true in ini file 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/gauge/module.tsx

Still some missing things and changes will happen in the next 1-3 months.

**Comment by ryantxu** [comment]
Very little of this is angular based... the only angular change is adding a wrapper around `<ng-transclude></ng-transclude>` in `panel_directive.ts`

I have been merging as changes come to the master branch.  It now works on master with the alpha panels.

This essentially:
1. adds a size listener to the panel content
2. when the size changes, it triggers appropriate changes to the grid system

Can we keep this issue open unless there is a better approach proposed?  The other options I could see are either directly with `react-grid-layout` or a in the dashboard layout

**Comment by ryantxu** [comment]
reopening to get an old fork up-to-date... will close again soon :)

**Pull request closed without merging**
