### PR TITLE
Implementing dashed lines

### PR DESCRIPTION
**Pull request by smalik03**
Adding support for dashed lines using flot.dashes.js #514

### CODE REVIEW

**Comment by smalik03** [comment]
@torkelo / @bergquist Please review/merge this. Thanks!

**Comment by torkelo** [comment]
I am a little hesitant to introduce more flot plugins and render options if it's not very popular feature. Maybe dashed lines is a really important graph feature, not sure :)

**Comment by smalik03** [comment]
We use a lot of dashed lines at work, it is really convenient when plotting averages with the actual data. Also, a lot of people have asked for dashed lines. If we are using flot, the dashed plugins would be the best way to implement it.

**Comment by smalik03** [comment]
@torkelo any updates on this?

**Comment by smalik03** [comment]
sorry had closed it by mistake

**Comment by torkelo** [comment]
no update, will have to wait and see if the interest in this feature is big enough

**Comment by matthiasr** [comment]
Registering interest – came here trying to find out how to do this. Use case is overlaying a not so important line (CPU requests) in without obscuring the important ones (CPU usage).

**Comment by AlucardZero** [comment]
I'm interested.

**Comment by PiR43** [comment]
I'm also interested!

**Comment by jypma** [comment]
👍  Interest here as well. And amazement on the size of an PR to "just" add a line style... of course coming from the background of not knowing the technologies involved at all :-)

**Comment by brandonraphael** [comment]
Interested in this as well. Any progress on this?

**Comment by smalik03** [comment]
@torkelo a lot of people have shown interest in the PR. I have updated it to resolve the conflicts, can this be reviewed and merged now?

**Comment by torkelo** [comment]
@smalik03 I will try to find time to review this

**Comment by ybizeul** [comment]
Definitely interest in this. There is not a lot of options when you need to chart different categories of informations on the same panel. Y1/Y2 is one, bars/lines/dots is another one but it tend to supercharge and very quickly gets hard to read. Dashed line is a right balance of subtle and differentiation.

**Comment by smalik03** [comment]
Hey @torkelo, any updates on this? Can we get this into 4.2.0?

**Comment by IgorGrizzzly** [comment]
+1    Cool feature for baselines and overlays! Like it. When will it be merged?

**Comment by cicciopizza** [comment]
Interested in this as well.

**Comment by mattmattmatt** [comment]
I got here by googling for the feature as well.
Dashed lines would be great to distinguish to different sets of lines in the same graph, e.g. absolute numbers vs. their ratios. Wouldn't want to have to resort to dots or bars as the lines is the most appropriate form for both cases.

**Comment by adslwy** [comment]
Vote for dashed line, it's super important for some of my graph such as showing trendline for a series

**Comment by daniellee** [comment]
image

This PR was merged manually with some changes. We really do not want to introduce lots of new options - there are already a lot. I felt that if I was using this feature I would mostly want it for series overrides rather than make every line dashed. 

Changes made to PR:
- The dashes draw option is only available for series overrides (as in the screenshot above). 
- The series overrides for dash length and dash spaces are removed so only the default values of 10 and 10 can be used.

Thank you very @smalik03 for this PR and apologies that you had to wait so long to get it merged.

**Pull request closed without merging**
