### PR TITLE
Chore: Upgrades jQuery and @types/jQuery to 3.5.1

### LINKED ISSUE #24225: Upgrade jQuery to 3.5.1
Known XSS vulnerability was addressed with jQuery 3.5.0: https://www.infoq.com/news/2020/04/jquery-35-xss-vulnerability-fix/

Pieces of code that might be affected by this version bump:
- flot uses html function - needs verification nothing break
- couple of angular directives uses html function directly (dropdown_typeahead, query part editors, graph_tooltip).

Majority of the usages seems to be safe, but we need to be cautious when updating and do some testing, especially for flot.

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Verification**: 
- [x] build passes for Grafana
- [x] build passes for packages
- [x] tests pass
- [x] gdev dashboards / Panel Tests - Graph
- [x] gdev dashboards / Panel Tests - Graph - Gradient Area Fills
- [x] gdev dashboards / Panel Tests - Graph - Y axis ticks
- [x] gdev dashboards / Panel Tests - Graph Time Regions
- [x] angular-strap.js (**$modal**)
  - [x] BottomNavLinks
  - [x] AlertRuleList
  - [x] ApiKeysPage
  - [x] ShareExport
  - [x] PluginPage
  - [x] pluginlist
- [ ] query_part_editor.ts (couldn't find any usages in Grafana, might be exported and used by external plugins?)
- [x] sql_part_editor.ts 
  - [x] postgres / query editor
  - [x] mysql / query editor
- [x] dropdown_typeahead.ts
  - [x] postgres / query editor
  - [x] mysql / query editor
  - [x] influxdb / query editor
  - [x] graph / tab_series_overrides
  - [x] heatmap / axes_editor
- [x] misc.ts
  - [x] VersionHistory
- [ ] graphite / func_editor.ts 🛑 
  **Before**
  image
  **After, missing left parentheses**
  image
- [x] graph / graph_tooltip.ts
- [x] heatmap / heatmap_tooltip.ts
- [x] singlestat / module.ts (**very hard to verify all possible combinations for this one**)
- [x] table-old / module.ts (**very hard to verify all possible combinations for this one**)
- [ ] datepicker.js (**couldn't find any usages in Grafana**)
- [x] flot.js
  - [x] legend
- [ ] bootstrap.js
  - [x] query_part_editor (**see above**)
  - [x] sql_part_editor (**see above**)
- [x] tagsinput / bootstrap-tagsinput.js
  - [x] event_editor
  - [x] DashLinks / editor
  - [x] DashboardSettings
  - [x] Annotations / editor
  - [x] Alertlist / editor
  - [x] DashList / editor

**Which issue(s) this PR fixes**:
Fixes #24225

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hugohaggmark** [comment]
The only thing I found was that this upgrade broke a bit of the Graphite Query Editor. I could need some help on that one I think @torkelo 
 **Before**
  image
  **After, missing left parentheses**
  image

**Comment by dprokop** [comment]
Great work @hugohaggmark . The parenthesis in the fund editor ring z bell, think @torkelo was finding a very similar issue few months back.

**Comment by torkelo** [comment]
Fixed the graphite editor issue

**Comment by torkelo** [comment]
And tested the query_editor part component it did not have the same problem as the graphite func editor had

**Review by dprokop — APPROVED** [review]
nice!

**Pull request merged**
