### PR TITLE
@grafana/ui: Replace Icons for IconButtons when used as buttons

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:

1. Adds IconButton display name
2. Replace various icons for icon buttons if they are used as buttons (mostly closing icons)
3. I have moved closing button in Dashboard Search from middle of the screen to corner

Before:
image

After:
image

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by ivanahuckova** [comment]
@torkelo Are we going to do some work on modals? Because as a next step, I would like to switch Icons for IconButtons on modal's closing buttons. So just making sure that it makes sense to switch these.

**Comment by Clarity-89** [comment]
My first impression when looking at that icon inside the search field is that it's used to clear search input. Even though the actual `input` takes only half of the row, it looks visually the same as the right part, so should we apply some different styling to the right part of the field?

**Comment by ivanahuckova** [comment]
@Clarity-89 Yeah, you are right. I haven't seen it before, but I see it now. What about change like this:
image
Or should I open a discussion in #ux?

**Comment by Clarity-89** [comment]
@ivanahuckova that looks much clearer to me. Altho I'd keep the search icon inside the input :) 
I think you could mention it in the UX channel because Diana was going to look into this as well, so she might have some better ideas.

**Pull request merged**
