### PR TITLE
Chore: Improve types

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- improves some types across the code base

**Why do we need this feature?**

- 🧹 

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by fabrizio-grafana — APPROVED** [review]
Approving for Tempo and Zipkin plugins!

**Review by itsmylife — APPROVED** [review]
Prometheus, influxdb, graphite and opentsdb LGTM

**Comment by baldm0mma** [comment]
@drew08t looks like there's some `canvas` and `geomap` type updates; the TS transpiler is happy locally, and everything spins up as expected, but can you please verify with your `canvas/geomap` skillz that this is G2G??? 🙏

**Comment by drew08t** [comment]
> @drew08t looks like there's some `canvas` and `geomap` type updates; the TS transpiler is happy locally, and everything spins up as expected, but can you please verify with your `canvas/geomap` skillz that this is G2G??? 🙏

Thanks for the heads up! I'll take a look shortly.

**Review by drew08t — APPROVED** [review]
Everything in Canvas and Geomap impacted by these changes behave as expected. LGTM!

**Pull request merged**
