### PR TITLE
Datasources: Update dashboards

### LINKED ISSUE #22463: Datasources: Update dashboard examples
**What would you like to be added**:
Some datasources dashboards JSON still contain old format data like "rows" and it would be better to upgrade them.

Old dashboards:
- prometheus_stats (Prometheus)
- prometheus_2_stats (Prometheus)
- grafana_stats (Prometheus)
- carbon_metrics (Graphite)

**Why is this needed**:
It can cause trouble if used as is (for example, the reporting feature is not working if we don't save them to upgrade them)

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Upgrade following datasources dashboard examples (remove usage of "rows"):
- prometheus_stats (Prometheus)
- prometheus_2_stats (Prometheus)
- grafana_stats (Prometheus)
- carbon_metrics (Graphite)

It caused trouble for the reporting feature if these dashboards were imported and not modified.

**Which issue(s) this PR fixes**:
Fixes #22463

### CODE REVIEW

**Comment by torkelo** [comment]
@xlson review this when you have time, looks ok to me but have not tested it

**Comment by xlson** [comment]
@torkelo will do.

**Review by xlson — CHANGES_REQUESTED** [review]
Great work.

Sorry for taking so long with the review. A few minor things.

- I'd update the docs link to Grafana docs as the link has changed (there is a redirect, but still)
- Increase the top level version on all of the dashboards from whatever it was before
- I'd remove the top-right panel that is supposed to show the Grafana and Prometheus logo on the Grafana metrics dashboard. Since 6.0 (I think) we sanitize html by default, which means the image links won't work. I'm not entirely sure, but I don't think we can easily fix that.

**Review by xlson — APPROVED** [review]
LGTM!

**Pull request merged**
