### PR TITLE
Add ability to set a global time interval

### PR DESCRIPTION
**Pull request by felixbarny**
The interval is configurable in the data source.
This commit only adds the ability to Elasticsearch datasources

bildschirmfoto 2015-10-23 um 09 33 23

### CODE REVIEW

**Comment by torkelo** [comment]
seems like a this broke some tests

**Comment by felixbarny** [comment]
Hm, I'll take a look on it.

**Comment by felixbarny** [comment]
looks good now

**Comment by bergquist** [comment]
I like this idea. But I think It should be added to all datasources in core grafana before it's merged. 

@torkelo If you agree with me I will add it to the rest of the datasources.

**Comment by torkelo** [comment]
Its tricky to add it to all data sources. I mean sure as a default, but usually you have metrics that are written at different intervals, so is a default really that useful?

**Pull request merged**
