### PR TITLE
Units: Add currency and energy units

### PR DESCRIPTION
**Pull request by anirudh-ramesh**
**What this PR does / why we need it**: Adds units - currency and energy - mostly useful for viewing metrics related to electricity small and large by the scientific community

**Which issue(s) this PR fixes**: N/A

Fixes #

**Special notes for your reviewer**: N/A

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
Thanks for contributing! 

We will gladly merge this but before that, it would be good with a unit test for each new unit.

**Comment by anirudh-ramesh** [comment]
Yes, I'd made a rebase after submitting the PR since I realized the order of the commits happened to be incorrect - that could potentially be a red flag - so thanks for taking this for a rigorous unit test.

**Comment by torkelo** [comment]
Do you know when you will have time to add unit tests for your changes?

**Comment by anirudh-ramesh** [comment]
Hi, @torkelo, I'm sorry I get a chance to spend time on this only on weekends.

I've added unit tests to `valueFormats.test.ts` for the proposed energy units, and to `symbolFormatters.test.ts` for the currency unit.

I've also rebased commit history to fast-track changes to the upstream master since this PR was originally submitted, and to reorder commits within this PR.

Thanks again for considering adding these units!

**Review by dprokop — APPROVED** [review]

**Review by torkelo — APPROVED** [review]
LGTM

**Pull request merged**
