### PR TITLE
[WIP] Collapse mode for Opentsdb queries & Support for Gexp (Graphite Expressions)

### PR DESCRIPTION
**Pull request by utkarshcmu**
Implements #3805 

- [x] Collapse Query
- [x] UI for Expressions
- [x] Backward Compatibility
- [x] Gexp & Display with metrics
- [ ] Write tests if any
- [ ] Backend Query implementation for alerting

This is still work in progress, please do not merge this yet!

For screenshot please see #3805

### CODE REVIEW

**Comment by ninja-** [comment]
Will this be merged?

**Comment by Bulls1986** [comment]
When can the plan be merged?

**Comment by torkelo** [comment]
looks still to be a work in progress PR so waiting for it to be finished

**Comment by utkarshcmu** [comment]
I am sorry but I don't think so I will have time and resources anytime soon to work on this PR. Anyone else, feel free to take this work forward.

**Comment by torkelo** [comment]
closing this as having WIP PRs that are stalled seems like a bad idea.

**Comment by gnydick** [comment]
What release is this targeted for?

**Pull request closed without merging**
