### PR TITLE
Plugins: Set plugin admin enabled if user is grafana admin

### PR DESCRIPTION
**Pull request by wbrowne**

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by ryantxu** [comment]
@daniellee thoughts here?  This change makes it more conservative, so that is probably good as a first pass -- that said if we have this limited to Grafana admins, should we change the default PluginAdminEnabled=true?

**Comment by daniellee** [comment]
Changing to Grafana Admin is the right move. For smaller instances, then most people are probably Grafana admins and for larger instances, Grafana admins are more likely to be aware of any security risks than the average user.

**Comment by oddlittlebird** [comment]
@achatterjee-grafana, what this means is that the user needs to have be both a Grafana Admin on the server and an Organization Admin for the organization that they want to manage plugins for.

**Comment by wbrowne** [comment]
They should only need to be a Grafana admin now @oddlittlebird

**Comment by oddlittlebird** [comment]
If a user is not an Organization Admin, then they cannot access the Configuration menu, which is where you manage plugins. This is true even if they are a Grafana Server Admin.

**Comment by marefr** [comment]
Maybe more related to your other PR and manage in cloud. There no user will be grafana admin so might need special logic in case you haven't already thought about this

**Pull request merged**
