### PR TITLE
Explore: Fix Query History flakey test

### LINKED ISSUE #59116: Explore: Query history test times out
**What happened**:

Query history test times out every now and then with:

```
FAIL public/app/features/explore/spec/queryHistory.test.tsx (87.731 s)
  ● Explore: Query History › updates the state in both Explore panes
```

It happened before (see https://github.com/grafana/grafana/issues/47635). Last time the issue was that some backend requests were not mocked properly. Needs to be investigated again.

### LINKED ISSUE #70158: Explore: Fix skipped flaky test
https://github.com/grafana/grafana/pull/70157 is skipping a flaky test, we should investigate on why that is happening and try to fix it.

### PR DESCRIPTION
**Pull request by ifrost**
This PR is to improve the execution time of a flakey query history test. 

Based on findings from [here](https://github.com/grafana/grafana/issues/59116#issuecomment-1398434676). The test still takes a lot of time on CI, but hopefully, this will avoid timeouts.

<details><summary>Approach 1</summary>

This approach was to use test id on the RichHistoryCard and use it to get all cards instead of using getAllByRole

Benchmark tests (3 runs each):

Locally (~20-30% faster):
* Before 15.8-16.5s
* After 11.1-12.4s

CI: (https://github.com/grafana/grafana/pull/71189) (~20-30% faster)
* Before 21.8-23.6s
* After 16.3-18.1s

Fixes: #70158
Fixes: #59116

If it becomes a problem again, I'd suggest splitting the test into 2 (for starring and deleting separately)

</details>

Approach 2

As described by Gio in [the comment below](https://github.com/grafana/grafana/pull/71190#pullrequestreview-1518728122). Additionally, I've split the test into 3 separate tests getting locally times around these values:

    updates the state in both Explore panes
      ✓ initial state is in sync (5005 ms)
      ✓ starred queries are synced (8569 ms)
      ✓ deleted queries are synced (5851 ms)

Previously, entire test would take ~16s. Now each test is max 9s with extra 3s added in total because of repeating same logic on each test that was split.

### CODE REVIEW

**Review by Elfo404 — COMMENTED** [review]
I think maybe we can be a bit smarter and avoid losing test accuracy (using test id instead of the proper selectors)

on my machine, i get similar times compared to you, so the fix would execute that test in ~12 seconds.

if we, instead of setting a test id on the buttons, set a test-id on the tab, we can restrict the selector to only look inside that tab when looking for buttons, something like

```ts
  const selector = within(withinExplore(exploreId).getByTestId('history-queries-tab'));

  const starButtons = selector.getAllByRole('button', { name: /[un]?star query/i });
```

while this is still a bit slower than your approach (~12.5s - 13s on my machine), it doesn't have the drawback of using a suboptimal selector, and potentially we can use the same to speed up also other tests that look for elements inside the explore drawer. wdyt?

**Comment by harisrozajac** [comment]
The test numbers are slightly different on my machine:
 ✓ adds new query history items after the query is run. (2267 ms)
 ✓ adds recently added query if the query history panel is already open (1224 ms)
 ✓ updates the state in both Explore panes (5923 ms)
 ✓ add comments to query history (3344 ms)
 ✓ updates query history settings (1817 ms)
 ✓ pagination (1460 ms)

It looks like flakey test takes 5.9 seconds. Am I missing something?

**Comment by ifrost** [comment]
@harisrozajac, we need to start building Grafana on your machine :D

> The test numbers are slightly different on my machine:

Interesting. I'm getting (with Gio's suggestion):

    ✓ adds new query history items after the query is run. (3655 ms)
    ✓ adds recently added query if the query history panel is already open (2390 ms)
    ✓ updates the state in both Explore panes (14091 ms)
    ✓ add comments to query history (5823 ms)
    ✓ updates query history settings (3301 ms)
    ✓ pagination (2346 ms)

What's your machine? I'm testing it on MacBook Pro 2019, 2,3 GHz 8-Core Intel Core i9


@Elfo404 

>  think maybe we can be a bit smarter and avoid losing test accuracy

I've tested it and locally I the improvement is less significant

* main 15.8-16.5s
* test id on the card: 11.1-12.4s (~67-78% vs main)
* test id on the container: 13.6-15.1s (~82%-96% vs main)

and on the CI

* main 21.8-23.6s
* test id on the card: 16.3-18.1s (~69%-83% vs main)
* test id on the container: 18.5-20.4s (~78%-94% vs main)

I can also try splitting the test into 2. The entire suite will run slower but individual tests should be faster

**Comment by harisrozajac** [comment]
@ifrost mine is MacBook Pro 2023 with M2 Pro chip and 12 cores. I think M2 Pro chip makes a difference 😃

**Comment by ifrost** [comment]
@Elfo404 I've applied your suggestion but also split the test into 3 separate tests, locally getting times (before all tests in one would take ~16s):

    updates the state in both Explore panes
      ✓ initial state is in sync (5005 ms)
      ✓ starred queries are synced (8569 ms)
      ✓ deleted queries are synced (5851 ms)

**Review by Elfo404 — APPROVED** [review]

**Pull request merged**
