### PR TITLE
Chore: bump grafana-ui version to 6.3

### PR DESCRIPTION
**Pull request by ryantxu**
update the version

### CODE REVIEW

**Comment by dprokop** [comment]
Why 6.3?

**Comment by ryantxu** [comment]
to match the grafana version it builds with...

https://github.com/grafana/grafana/blob/master/package.json#L8

**Comment by dprokop** [comment]
Oh, was sure Grafana's still at 6.2 :)

**Review by dprokop — APPROVED** [review]

**Comment by ryantxu** [comment]
ha -- Grafana 6.2 is soooo last week :)   

We may want/need to update the release & branching guides to keep the library versions in sync with the release.  Check:
https://github.com/grafana/grafana/blob/v6.2.x/packages/grafana-ui/package.json
the 6.2 compatible grafana-ui is marked 6.0.1-alpha.0

**Pull request merged**
