### PR TITLE
Tempo: Run search query with keyboard shortcut from duration fields

### PR DESCRIPTION
**Pull request by connorlindsey**
**What this PR does / why we need it**:
Allows users to run Tempo search with Ctrl/shift+enter from all text fields in the search UI (tags + duration fields). 

**Which issue(s) this PR fixes**:
Relates to #39241

**Special notes for your reviewer**:
I didn't switch the 'Limit' field because it's a number input which doesn't work with QueryField. Happy to change that (or find another way to run the query with the shortcut) if you think the user should be able to run the query from the limit field.

### CODE REVIEW

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
I think we were correctly using `<Input />` fields here. The `<QueryField />` holds a lot of logic/autocomplete functionality and should be used mostly for inputing query. Instead of this, you could create and pass `onKeyDown` function as param `<Input />`.  `onKeyDown` would hold the running function when enter + shift pressed logic. 

Something like:

```
  const onKeyDown = (keyEvent: React.KeyboardEvent) => {
    if (keyEvent.key === 'Enter' && (keyEvent.shiftKey || keyEvent.ctrlKey)) {
      onRunQuery();
    }
  };
```
a potom 
```
<Input
  onKeyDown={onKeyDown}
  ...
```

**Comment by ifrost** [comment]
> I think we were correctly using `<Input />` fields here. (...)

`QueryField` also takes care of debouncing onChange while typing and gives some basic syntax highlighting (which makes tags input more readable), so I guess it makes sense to use it if we need these features.

> [a potom](https://translate.google.com/?sl=sk&tl=en&text=a%20potom&op=translate)

😃 ❤️

**Review by ifrost — APPROVED** [review]
I think it should be okay to use `QueryField` for now though having a reusable input with Shift+Enter functionality could be nice addition in query editor with many inputs.

**Comment by connorlindsey** [comment]
I'll go back to `Input` because it has a better focus state and doesn't trap focus like the QueryEditor does. I was following Olof's changes when he made the Trace ID's inputs into QueryField's to allow running with shift+enter, but I think @ivanahuckova's recommendation will work really well

**Review by ivanahuckova — APPROVED** [review]
LGTM! 👌

**Pull request merged**
