### PR TITLE
Email: Use MJML email templates

### LINKED ISSUE #53879: Newlines not being preserved in certain email clients
**What happened**:
- I modified the `Message` component of a test contact point to include newlines
- I tested this contact point and read the received email in two different clients:
    - Gmail: newlines are preserved
    - Outlook (Windows Mail): newlines are not preserved and are replaced with spaces

**What you expected to happen**:
Newlines should be preserved in as many email clients as possible

**How to reproduce it (as minimally and precisely as possible)**:
- Open any Grafana version post 9.0.4 (this test was done on 9.0.7)
- Navigate to Alerts
- Create a new Contact Point, type Email, and add a multi-line message such as
   ```
   a
   b
   c
   ```
- Test the contact point and read the email through the two aforementioned clients (Gmail web and Windows Mail desktop)

**Anything else we need to know?**:
- This issue causes the comment over here https://github.com/grafana/grafana/pull/52253#issuecomment-1213333817
- This issue does lie technically on the Windows Mail client, but the support for `white-space` is far from perfect and this means that behavior might vary a lot depending on the user (see https://www.caniemail.com/features/css-white-space/)

- I've dug a bit into this one and found a fix that our team will use locally.
    For Windows Mail (and likely most of the Outlook versions that use the Word HTML rendering engine internally) this can be solved by switching to a supported component such as `<pre>`. This doesn't affect templating, as it happens before any values are escaped and rendered. 
    Here's the modification in `public/emails/ng_alert_notification.html`, replace this section https://github.com/grafana/grafana/blob/fdaf6b5e8d36e726745a77c400f960e24cc4bb72/public/emails/ng_alert_notification.html#L288-L290 with 
    ```html
    {{ if gt (len .Message) 0 }}
      <div align="left"><pre>{{ .Message }}</pre>
    {{ else }}
    ```
    There might be other changes needed to make the `pre` block look more like the text Grafana uses, as most browsers will render this in a monospaced font.

    I can do a PR if it makes sense, but I don't know enough about this part of Grafana to understand fully the implications of that change and if that might affect the workflow of other users. Let me know if you think it makes sense.

Thanks for all the hard work on Grafana !

**Environment**:
- Grafana version: 9.x (9.0.4, 9.0.5 and 9.0.7 tested)
- Data source type & version: Not applicable
- OS Grafana is installed on: Tested on `grafana/grafana` Docker container
- User OS & Browser: Linux + Gmail, Windows + Windows Mail
- Grafana plugins: Not applicable
- Others: None

### PR DESCRIPTION
**Pull request by gillesdemey**
# New email templates

This PR is rather large and makes some significant changes to how we compile email templates.

Additionally it updates the design of the existing email templates, I'll have some screenshots down below.

## Context

While working on a better email template for alerting I've decided to look in to another email template solution that didn't involve manually [editing a large HTML file](https://github.com/grafana/grafana/blob/998093a280e43c43ce9988ef058170923f93022c/emails/templates/ng_alert_notification.html) and hoping it worked in multiple mail clients.

I've settled on trying to migrate it to MJML, an intermediate syntax that compiles to email-valid HTML + CSS. 

It'll mostly prevent us from writing invalid and illegal HTML / CSS that might not work in all supported mail clients (all the way back to Outlook 2003 👴).

## The most notable changes are;

* [MJML](https://github.com/mjmlio/mjml) is used to define email templates and compile them to the final email HTML output
* All email templates have an updated design
* Added [sprig](http://masterminds.github.io/sprig/) functions to the email templates
* The copyright year is now always up to date 🤷‍♀️
* Removed premailer as a dependency, the MJML compiler handles this for us

Templates are responsive and columns stack on mobile.

I've also added links that can be copied and pasted in to the browser to most email templates, this is pretty standard in case corporate proxies strip buttons and such from emails or when someone is using something ancient like Lotus Notes.

I've tested it as best as I could in the email clients I have access to – though those are modern email clients.

## Screenshots

<details>
  <summary>Alert Notifications (new alerting)</summary>
Screenshot 2022-10-20 at 17 19 38
</details>

<details>
  <summary>Forgot Password</summary>
image
</details>

<details>
  <summary>Verify Email on Signup</summary>
image
</details>

<details>
  <summary>Welcome Email</summary>
image
</details>

<details>
  <summary>Invited to Organisation</summary>
image
</details>

<details>
  <summary>Added to Organisation</summary>
image
</details>

**Special notes for your reviewer**:

I'm unsure if anything needs to be updated in the CI pipeline; as far as I could tell the compilation of email templates happens out of band (on the developer's machine).

Fixes https://github.com/grafana/grafana/issues/53879

### CODE REVIEW

**Comment by jackw** [comment]
Amazing stuff @gillesdemey ! I'd planned to look at this for a hackathon project but looks like you've beaten me to it. 😄

**Comment by gillesdemey** [comment]
Unfortunately not, the whole setup is rather limited and importing external stuff seems nigh impossible so we have to settle with manually syncing the color hex codes for now – there's also the current outstanding issue of the mail template(s) in `grafana-enterprise` that are manually sync with the templates here (although to be fair it was also the case before this PR).

**Comment by santihernandezc** [comment]
This looks awesome! 🎉 
Have you explored the option of having colors and style-related stuff defined as constants/functions in Go? This way the template parser can use the correct values even if we decide to change them.

**Comment by gillesdemey** [comment]
Yea this has been on my mind; eventually we should also respect the org's dark / light mode preference where we can inject the right colors in to the email templates 🌓

**Review by papagian — APPROVED** [review]
LGTM

**Review by gotjosh — APPROVED** [review]
LGTM

**Pull request merged**
