### PR TITLE
Annotations: Fix blank panels for queries with unknown data sources

### LINKED ISSUE #38985: Annotations: errors in DashboardQueryRunner don't bubble up
Grafana 8.1.2

1. Create a new dashboard
2. Save the dashboard
2. Add an annotation query using the `-- Grafana --` data source for instance
3. Add an empty time series panel
4. Save the dashboard
5. Open dashboard settings => JSON Model
6. Change the second annotations entry to
```json
{
        "datasource": "Unknown ds that does not exists",
        "enable": true,
        "hide": false,
        "iconColor": "red",
        "name": "test",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [
            "env:prod"
          ],
          "type": "tags"
        }
}
```
7. Save the changes
8. Reload dashboard
9. Notice how time series panel doesn't show any data or grid **[NOT OK]**

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
We're using the rxjs function `reduce` in `DashboardQueryRunner` and `AnnotationsWorker` to keep re-renders to one. One challenge with using `reduce` is that all observables involved need to be completed before any value is emitted. Having an unhandled exception in that chain will cause the reduce to never emit a value which explains #38985.

This PR adds error handling for the call to datasourceSrv.get so we always emit values even if one of the data sources is missing.

**Which issue(s) this PR fixes**:
Fixes #38985

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
looks good to me, nice catch! 🙌

**Comment by hugohaggmark** [comment]
@ashharrison90 did you have a minute to test it out too?

**Comment by ashharrison90** [comment]
yeah, worked perfectly for me and surfaced the error to the user. although i only tested the scenario you mentioned in the issue - i'm a little unsure what else to test in that area 😅

**Comment by hugohaggmark** [comment]
> yeah, worked perfectly for me and surfaced the error to the user. although i only tested the scenario you mentioned in the issue - i'm a little unsure what else to test in that area 😅

Thank you, that's more than enough!

**Pull request merged**
