### PR TITLE
fixed alert tab order and fixed some console logging issues

### PR DESCRIPTION
**Pull request by torkelo**
* Fixed alert tab order

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Think you need to fix time range tab order as well - should be the last one. Otherwise LGTM

**Comment by torkelo** [comment]
oh, good catch, don't understand how I did not notice that. 

I found the real cause for this that fixed the order of both :)

**Review by marefr — CHANGES_REQUESTED** [review]
Hmm think some earlier changes made to `addEditorTab` introduced a breaking change since you needed to change the order of calling `addEditorTab`. This could be a breaking change for panel plugins. What's your thought on this?

**Comment by torkelo** [comment]
No, I think I made the change to order of the tabs when testing a few things and this restores it:
see now same order as in 5.3.3:
https://github.com/grafana/grafana/blob/v5.3.4/public/app/plugins/panel/graph/module.ts

**Review by marefr — APPROVED** [review]
Got it!

**Pull request merged**
