### PR TITLE
CircleCi: Run End-to-End tests for release builds

### LINKED ISSUE #17897: Run End-to-End tests for release builds
**What would you like to be added**:
Run End-to-End tests for release builds (tags).

**Why is this needed**:
We currently only run End-to-End tests for the master branch workflow, see [circleci config](https://github.com/grafana/grafana/blob/master/.circleci/config.yml#L689), and we want to run this for the [relases workflow](https://github.com/grafana/grafana/blob/master/.circleci/config.yml#L697) to get some automated verification of releases.

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Introduces and new CicleCi job `end-to-end-test-release` in the `release` workflow for enabling end to end test execution in for release builds.

**Which issue(s) this PR fixes**:

Fixes #17897

**Special notes for your reviewer**:
The `end-to-end-test-release` job only differs from the existing `end-to-end-test` in the docker image therefore ideally this one should have been reused instead. However, [executors](https://circleci.com/docs/2.0/reusing-config/#executor) are only supported in CircleCi since 2.1.
Another alternative would be to create two [contexts](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-context) (one for master and another for releases) and define an environmental variable for which grafana image to be used in each case. Then it would be enough to [set the appropriate job context](https://circleci.com/docs/2.0/configuration-reference/#context) to each workflow (master and release). However, this also was not possible in this specific case since CircleCI does not support interpolation when setting environment variables.
Finally, since the modifications are in the release workflow I haven't test them properly in action!

### CODE REVIEW

**Review by xlson — APPROVED** [review]
Great work!

Too bad we had to duplicate the entire config but that's fine for now. I didn't know about the executors feature, that sounds really promising. Do you know what we need to do to be able to use them? If it's enough to update the version of our build in config.yml it would be good to give that a try as soon as 6.3 dev is finished so that we can simplify the build for 6.4.

**Comment by gotjosh** [comment]
Are we good to get this in @papagian?

Also, do we need to update [the release guide](https://docs.google.com/document/d/1vc7gU1l1Z2Lc_B0dr1z5MTOLSYaYTCU53osT1PSbj6A/edit#heading=h.abka9lk123ul)? With this in place, seems like we no longer need to manually run the e2e tests as part of the testing phase.

**Comment by xlson** [comment]
I merged it now. But yes, good catch, we do need to update the release guide. Can you do that @papagian?

**Comment by papagian** [comment]
@gotjosh @xlson
Concerning the release guide update I agree but I would propose to update it after we go through it during the next release and we have seen this working in action.

Concerning the CI version we use, even though I'm really beginner to this, I see a potential upgrading it but that requires an extra work to be put on rewriting appropriately and testing our CI config.

**Pull request merged**
