### PR TITLE
Add on datasource change to optional components -- alt --

### PR DESCRIPTION
**Pull request by MasslessParticle**
This is an alternative approach to #40164. In this approach, the `QueryGroup` keeps track of the queries it is responsibe for and makes sure they all have a datasource. As a result, the `create recorded query modal` no longer has to take `onChangeDataSource`

This PR still passes `onChangeDataSource` to the `add recorded query modal` because this modal actually adds a query to the group and should be mixed.

An interesing result of the PR is that the logic inside `onDataSourceChange` has become simpler because we don't repeatedly add and remove the datasource name.

What are folks thoughts on this approach?

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
think this makes sense, so this basically changes things so the query model always have a data source property (no matter if panel data source is mixed or not). This should help things for cue  think? @ryantxu thoughts?

**Review by hugohaggmark — COMMENTED** [review]
I agree with Torkel that this seems like a more viable solution. One thing that concerns me is the refactor of `onChangeDataSource` to `updateQueries`. Seems this would need some manual testing to make sure it doesn't introduce unforeseen issues.

**Comment by MasslessParticle** [comment]
@hugohaggmark womp, womp... thanks!

**Review by bossinc — APPROVED** [review]

**Comment by bossinc** [comment]
I did manual testing on `updateQueries`.
Creating, deleting, changing to mixed, changing to another data source, and changing mixed back to a data source seem to all work as they did before. 😃  As well as saving and reloading dashboards and general poking at it.

I found a few odd things that exists here and in `main`. I probably should make bugs for these.

First, the `Query Inspector` does not show all the queries when the panel's data source is `mixed` and the query's data sources differ.

Second,
Set your data source in a panel to `mixed`.
Add another query with a different data source than the query that is currently there.
Set your data source in the panel to another data source.
All the queries created will switch to the new panel data source instead of deleting the queries that do not use the data source.

**Review by torkelo — APPROVED** [review]
Let's go!

**Pull request merged**
