### PR TITLE
grafana-ui: Switching default JSON parser to custom Fixes #55856

### LINKED ISSUE #55856: Logs:  JSON prettify rounds long numbers
**What happened**:
When grafana loki log prettify function is used, long numbers are getting rounded and does not correspond actual log line:
Before pretty:
image
After pretty:
image

**What you expected to happen**:
Prettyfier should not change any log value. 

**How to reproduce it (as minimally and precisely as possible)**:
Can be checked via console:
image

**Environment**:
- Grafana version: checked 8 and 9
- Data source type & version: Loki (any)
- OS Grafana is installed on: k8s, Windows
- User OS & Browser: Windows, Chrome
- Grafana plugins: N/A
- Others: N/A

This is known issue of JSON.parse. Custom library should be used instead to avoid such behavior.

### PR DESCRIPTION
**Pull request by andrejshapal**
**What this PR does / why we need it**:
loseless-json library prevents numbers being rounded as it is done in default JSON.parse
image

**Which issue(s) this PR fixes**:
Fixes #55856

**Special notes for your reviewer**:
Doing it for the first time. Apologies if something is wrong.

### CODE REVIEW

**Comment by leeoniya** [comment]
some more info: https://gist.github.com/JosePedroDias/0bc225493329e877ec0c49212bab644e

the other solution linked from there is to use a regex to wrap all 16+ digit nums with strings, and then use normal `JSON.parse()`. though this'd probably end up displaying as `{"key": '-137198070982544818'}` without another post-pretty-print regex pass that removes the wrapping quotes.

might be interesting to benchmark all 3 approaches which are likely very different and might matter if rendering thousands of log lines. if it's just for unfolding then we can probably do the 2-pass regex approach and avoid a dependency and custom json parser?

**Comment by matyax** [comment]
Like it's mentioned in the [repo](https://github.com/josdejong/lossless-json), lossless-json is much slower than native. Ran the benchmark in my machine, with the following result:

```
 yarn benchmark      
yarn run v1.22.19
$ babel-node test/benchmark/run.js
JSON.parse: 19.794ms
LosslessJSON.parse: 153.612ms

JSON.stringify: 11.526ms
LosslessJSON.stringify: 46.998ms
✨  Done in 0.75s.
```

I think the extra dependency and the performance difference are worth a double check, so I'll bring this up to the team for further evaluation. For now, I'll close this one.

Thank you @andrejshapal !

**Comment by gabor** [comment]
@leeoniya 

> the other solution linked from there is to use a regex to wrap all 16+ digit nums with strings, and then use normal `JSON.parse()`. though this'd probably end up displaying as `"-137198070982544818"` without another post-pretty-print regex pass that removes the wrapping quotes.

hmm.. i don't think you can make this perfect, right? i mean, the post-pretty-print step might un-quote things that were quoted originally.

**Comment by gabor** [comment]
another approach might be to do a fast "detect problem-case" pass with the regex and go with the slow-mode library for the  problematic cases, or just not-prettify lines with the problem-cases.

**Comment by leeoniya** [comment]
yeah, it won't be perfect, but could be good enough for no one to notice :), you can wrap in `"`-137198070982544818`"` or some other bizzare thing that will ~never happen in real life. it may not actually be necessary to re-unwrap it if the intent is to view it. if the intent is to copy/paste it, it's not safe anyways since this falls outside the recommended numeric range in most json implmentations.

**Comment by leeoniya** [comment]
so, i think a regex approach is quite viable here, even if we want to add the complexity of de-quotifying after pretty print. i personally don't think the post-processing pass is necessary and we can just leave them as strings.

here's a bench i threw together that shows a **36ms overhead when processing 162,000 strings/phrases**. worth noting that it likely rarely gets a match to replace in my corpus, but i expect these to be uncommon in real world cases as well.

`testdata.json` is from my super secret project ;)

https://github.com/leeoniya/uFuzzy/blob/main/demos/testdata.json

```js
const fs = require('fs');

const datasets = JSON.parse(fs.readFileSync('./testdata.json'));

/*
// handles common patterns of long numbers after commas, colons and opening brackets
[7, 29.5, -25533333.38999885]
{"key":-25533333.38999885}
[-25533333.389998857, 29.5, 17]
*/
let re = /([\[:,]\s*)(-?[\d.]{16,})/g;

console.time('quoteBigs');

for (let k in datasets) {
    let d = datasets[k];

    for (let i = 0; i < d.length; i++) {
        d[i] = d[i].replace(re, '$1"$2"');
    }
}

console.timeEnd('quoteBigs');
```

**Comment by matyax** [comment]
@leeoniya Not sure if I'm misreading the whole thing, but I understood the regex replace would take place before `JSON.parse()`?

**Comment by andrejshapal** [comment]
Hello, 

I tried to test few options:
`import Benchmark from 'benchmark'
const suite = new Benchmark.Suite();
import fs from 'fs'
const datasets = fs.readFileSync('./test.json', "utf8");
import { parse, stringify, isInteger } from 'lossless-json'
import * as JSONbig from 'json-bigint'
import * as JSONbignumber from 'json-bignumber'

function native(data) {
    const parsedData = (JSON.stringify(JSON.parse(data), undefined, 2))
    return (parsedData)
}

function without(data) {
    return (data)
}

function loseless(data) {
    const parsedData = (JSON.stringify(parse(data), undefined, 2))
    return (parsedData)
}
function regexp(data) {
    const regex = /([\[:])?(-?\d{16,})([,\}\]])/g
    const data_reg = data.replaceAll(regex, '$1"$2"$3')
    const parsedData = (JSON.stringify(JSON.parse(data_reg), undefined, 2))
    return (parsedData)
}

function big(data) {
    const parsedData = (JSON.stringify(JSONbig.parse(data), undefined, 2))
    return (parsedData)
}

function bignum(data) {
    const parsedData = (JSON.stringify(JSONbignumber.parse(data), undefined, 2))
    return (parsedData)
}

suite
    .add('native-parser', () => {
        const processed = native(datasets);
     //   fs.writeFileSync("./native.json", processed);
    })
    //    .add('Without', () => {
    //        const processed = without(datasets);
    //    })
    .add('lossless-json', () => {
        const processed = loseless(datasets);
     //   fs.writeFileSync("./loseless.json", processed);
    })
    .add('regular-expression', () => {
        const processed = regexp(datasets);
     //   fs.writeFileSync("./regex.json", processed);
    })
    .add('json-bigint', () => {
        const processed = big(datasets);
      //  fs.writeFileSync("./JSONbig.json", processed);
    })
    .add('json-bignumber', () => {
        const processed = big(datasets);
      //  fs.writeFileSync("./JSONbignumber.json", processed);
    })
    .on('cycle', event => {
        const benchmark = event.target;
        const aa = event;

        console.log(benchmark.toString() + " mean time " + benchmark.stats.mean.toFixed(10) + " sec");
    })
    .on('complete', event => {
        const suite = event.currentTarget;
        const fastestOption = suite.filter('fastest').map('name');

        console.log(`The fastest option is ${fastestOption}`);
    })
    .run();`

I did tests in 2 phases:

1. Test small file covering different cases for quality.
2. Test big file (332567 log lines) for quantity. 

Sample data:
`[{"marker":"BusinessEvent","timestamp":"2022-09-29T23:59:59.643Z","id":-234709376548944734,"curency":"GBP"},
{"marker":"BusinessEvent","timestamp":"2022-09-29T23:59:59.643Z", "test": {"test":-234709376548944734}, "testa": [-234709376548944734, -234709376548944734], "testb":-234709376548944734}]
`

**Quantity test showed the following:**
`native-parser x 0.80 ops/sec ±6.79% (6 runs sampled) mean time 1.2514890333 sec
lossless-json x 0.11 ops/sec ±11.24% (5 runs sampled) mean time 8.7173744600 sec
regular-expression x 0.48 ops/sec ±5.35% (6 runs sampled) mean time 2.0909496167 sec
json-bigint x 0.24 ops/sec ±5.64% (5 runs sampled) mean time 4.1698058000 sec
json-bignumber x 0.19 ops/sec ±22.99% (5 runs sampled) mean time 5.2409987600 sec`

**Quality test:**

native-parser:
`[
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "id": -234709376548944740,
    "curency": "GBP"
  },
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "test": {
      "test": -234709376548944740
    },
    "testa": [
      -234709376548944740,
      -234709376548944740
    ],
    "testb": -234709376548944740
  }
]`

regular-expression:
`[
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "id": "-234709376548944734",
    "curency": "GBP"
  },
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "test": {
      "test": "-234709376548944734"
    },
    "testa": [
      "-234709376548944734",
      "-234709376548944734"
    ],
    "testb": "-234709376548944734"
  }
]`

lossless-json:
`[
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "id": -234709376548944734,
    "curency": "GBP"
  },
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "test": {
      "test": -234709376548944734
    },
    "testa": [
      -234709376548944734,
      -234709376548944734
    ],
    "testb": -234709376548944734
  }
]`

json-bigint:
`[
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "id": "-234709376548944734",
    "curency": "GBP"
  },
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "test": {
      "test": "-234709376548944734"
    },
    "testa": [
      "-234709376548944734",
      "-234709376548944734"
    ],
    "testb": "-234709376548944734"
  }
]`

json-bignumber:
`[
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "id": "-234709376548944734",
    "curency": "GBP"
  },
  {
    "marker": "BusinessEvent",
    "timestamp": "2022-09-29T23:59:59.643Z",
    "test": {
      "test": "-234709376548944734"
    },
    "testa": [
      "-234709376548944734",
      "-234709376548944734"
    ],
    "testb": "-234709376548944734"
  }
]`

1. native-parser is the fastest, regular-expression is taking twice longer time to finish (but 1s difference is not huge when 30k logs are parsed). 
2. native-parser is showing incorrect data, while the rest of approaches shows correct. 

I want to emphasize how severe this issue is. Users unaware of the issue could have multiple errors while using the logs (copying data via ui, calculating something etc). I am surprised this issue was not reported before. I assume it is just because the users did not find the source of issue. We found it when started to investigate data discrepancy.

**Pull request closed without merging**
