### PR TITLE
issue #4747 - add date and time units to singlestat panel.

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Add date and time units to singlestat panel.

### CODE REVIEW

**Comment by bergquist** [comment]
@alexanderzobnin Sorry for merging and reverting this. But when thinking more about this I don't think this belongs in kbn. 

This should only be available in the singlestate panel. All kbn convertions should be available for all panels. Ex graph panel.

**Comment by torkelo** [comment]
yea, this should be local formats in added in the singlestat panel, sorry for not mentioning this @alexanderzobnin  .  

So with this code we can show a date based on an epoch value (either second epoch or ms epoch). 

It would be nice to add this  as well to local time format (to show duration using the momemt fromNow function (so the metric value is ms or seconds and you subtract that from now and then use the fromNow()) to get a duration string ,.
https://github.com/grafana/grafana/issues/2971

**Comment by alexanderzobnin** [comment]
Ok, I'll try to implement this option for singlestat panel only.

**Comment by alexanderzobnin** [comment]
Folks, what do you think - should it be a menu item (like from `kbn`) or special control?

**Comment by torkelo** [comment]
@alexanderzobnin you can use the same unit control.  

Just add a few singelstat specific unit formats here: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L85

**Comment by torkelo** [comment]
but wait, lets add them to kbn, because I think some of these will be useful for the table panel as well, not only singlestat

**Comment by alexanderzobnin** [comment]
So... Can I leave this version of PR?

**Comment by dhenneke** [comment]
What is the status here? I would really like to use this feature in the singlestat panel.

**Comment by StasGoshtein** [comment]
+1

**Pull request merged**
