### PR TITLE
Sort unsorted

### PR DESCRIPTION
**Pull request by ilgizar**
First, if you do not specify a sort. Second, if the metrics are more than ten. Then the legend elements will be mixed by the next pressing on any of them. The same happens with the tooltip elements.
unsorted
I suggest to sort elements of legend and tooltip in order of metrics, when the sorting is not explicitly specified.

### CODE REVIEW

**Comment by torkelo** [comment]
> First, if you do not specify a sort. Second, if the metrics are more than ten. Then the legend elements will be mixed by the next pressing on any of them. The same happens with the tooltip elements.

Can you describe in more detail? "First, if you do not specify a sort." Is not a complete sentence. Can you include exact metric query and response and detail the issue your trying to solve? We have no other reports of sort order determined by metric query is wrong in legend or tooltip (please open bug report if this is the case) .

**Comment by ilgizar** [comment]
Issue #10551
My solve: include index of metric to data array. If not was setted sorting then sort by index

**Comment by torkelo** [comment]
This is strange, though why is this happening. Was able to replicate the issue you detailed in https://github.com/grafana/grafana/issues/10551 but not sure I want to fix it like this before understanding why it's happening, and why at more than 10 series.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/10617

**Pull request closed without merging**
