### PR TITLE
Query Validation: accept any parser to validate query and integrate with Prom query editor

### PR DESCRIPTION
**Pull request by matyax**
We have a lot of components in common, with similar tools, adding query validation for other data sources that use a Lezer parser could be trivial, so I quickly came up with this PR, where:
- The validation function accepts a parser parameter.
- Integrated the validator with the Prometheus Monaco component.

If we want to support other data sources and  be friendly with external data sources, we should ideally move this to an external repo.

**Special notes for your reviewer:**

https://github.com/grafana/grafana/assets/1069378/0956b0c4-0b01-426c-99b4-33a6955c2e75

### CODE REVIEW

**Comment by matyax** [comment]
@grafana/observability-metrics Would you be interested in this feature? I wouldn't mind moving it elsewhere where other data sources could use this.

**Comment by gtk-grafana** [comment]
This is a good refactor and a win IMO even if we don't pursue a shared lib
@bohandley, what do you think?

**Comment by bohandley** [comment]
I agree @gtk-grafana, this looks good to me!

**Review by bohandley — APPROVED** [review]

**Comment by matyax** [comment]
Added unit tests for PromQL. Any concern about merging this @gtk-grafana @bohandley ?

**Review by gtk-grafana — APPROVED** [review]

**Comment by matyax** [comment]
Thank you all! If there's any issue with this feel free to just ping 👍

**Pull request merged**
