### PR TITLE
AzureMonitor: Allow multiple resources in the API for Metrics

### LINKED ISSUE #56102: Adapt model to multiple resource groups and resource names
For Metrics. Pass over multiple resources to the Azure API. Parse the response as a new frame.

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

List of changes:

 - Upgraded API version to 2021-05-01 (this is necessary to use the new filter format).
 - Deprecated `resourceGroup` and  `resourceName` from the AzureMonitorQuery model
 - Added `resources` as a list of resources
 - Added `region` which is necessary when requesting multiple resources
 - When multiple resources are set, do the `/metrics` query at the subscription level. To reduce the result, it's necessary to set a `region` and a list of resource IDs in the `filter`.
 - Moved the `filter` from a URL param to the body of a POST request, this is to avoid the limit of 2048 characters for an URL (which is something that we can hit if there are multiple resources selected). 

**Which issue(s) this PR fixes**:

Fixes #56102

**Special notes for your reviewer**:

Full info at https://github.com/grafana/grafana/issues/55372

If you want to try this changes in real life, you can do it with a request like:

```
curl 'http://localhost:3000/api/ds/query' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: grafana_session=FILL_THIS' \
  -H 'Origin: http://localhost:3000' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'content-type: application/json' \
  -H 'x-grafana-org-id: 1' \
  --data-raw '{"subscription":"FILL_THIS", "queries":[{"azureMonitor":{"region":"northeurope","resources":[{"resourceGroup":"cloud-datasources","resourceName":"GithubTestDataVM"},{"resourceGroup":"cloud-datasources","resourceName":"cloud-datasources"}],"metricNamespace":"Microsoft.Compute/virtualMachines","customNamespace":"","timeGrain":"auto","allowedTimeGrainsMs":[60000,300000,900000,1800000,3600000,21600000,43200000,86400000],"metricName":"Percentage CPU","aggregation":"Average","dimensionFilters":[],"top":"10"},"datasource":{"uid":"w5FOjP_7z","type":"grafana-azure-monitor-datasource"},"queryType":"Azure Monitor","refId":"A","datasourceId":1,"intervalMs":120000,"maxDataPoints":468}],"range":{"from":"2022-09-28T15:33:05.042Z","to":"2022-09-29T15:33:05.042Z","raw":{"from":"now-24h","to":"now"}},"from":"1664379185042","to":"1664465585042"}' \
  --compressed
```

### CODE REVIEW

**Review by asimpson — APPROVED** [review]
LGTM I was able to step through the changes in the debugger and tests pass locally. 

The `curl` command you provided returned a 400 for me (I did fill in the cookie and subscription values correctly). Maybe I missed something else with that?

**Comment by andresmgot** [comment]
Thanks!

> The `curl` command you provided returned a 400 for me (I did fill in the cookie and subscription values correctly). Maybe I missed something else with that?

I noticed that the dashboard also needs to be changed for other instances (`"datasource":{"uid":"FILL_THIS","type":"grafana-azure-monitor-datasource"}`). Maybe it's easier if you copy any `query` request from your browser and add two resources instead of one.

**Review by aangelisc — APPROVED** [review]
Very thorough 👍

**Comment by andresmgot** [comment]
I am going to merge this since it's backend-only and does not affect the current UX

**Pull request merged**
