### PR TITLE
SQL: Define primary key for tables without it

### LINKED ISSUE #12971: All database tables doesn't have a primary key column
When using Grafana with MariaDB with Galera cluster the database migration/creation fails because of a the setting `innodb_force_primary_key=1`, which is required for Galera cluster to work properly.  You don't need to set up a Galera cluster to reproduce this issue, you can do it by setting that property on a normal MariaDB instance.

I have corrected the issue in [PR 12970](https://github.com/grafana/grafana/pull/12970).

### What Grafana version are you using?
5.2.2
### What OS are you running grafana on?
RHEL 7.3
### What did you do?
bin/grafana-server web
### What was the expected result?
Successful service start
### What happened instead?
```bash
EROR[08-17|10:29:06] Executing migration failed               logger=migrator id="Create annotation_tag table v2" error="Error 1173: This table type requires a primary key"
EROR[08-17|10:29:06] Exec failed                              logger=migrator error="Error 1173: This table type requires a primary key" sql="CREATE TABLE IF NOT EXISTS `annotation_tag` (\n`annotation_id` BIGINT(20) NOT NULL\n, `tag_id` BIGINT(20) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;"
EROR[08-17|10:29:06] Server shutdown                          logger=server reason="Service init failed: Migration failed err: Error 1173: This table type requires a primary key"
```

### PR DESCRIPTION
**Pull request by azhiltsov**
The `annotation_tag` and `alert_rule_tag` tables did not have
PRIMARY KEY defined what cause problems with migration to
MariaDB with Galera setup with
 `innodb_force_primary_key=1`
Or MySQL > 8.0.13 with
 `sql_require_primary_key=ON`

Which can manifest as follows:

```
MariaDB
Error 1173: This table type requires a primary key
```

```
MySQL
ERROR 3750 (HY000): Unable to create or change a table
without a primary key, when the system variable 'sql_require_primary_key' is set.
```

Extra reading for curious:
https://jfg-mysql.blogspot.com/2017/08/danger-no-pk-with-RBR-and-mariadb-protection.html

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #12971

**Special notes for your reviewer**:
I screwed https://github.com/grafana/grafana/pull/21387 and github have closed it. 
Resubmitting as new.

### CODE REVIEW

**Comment by azhiltsov** [comment]
I fixed integration test for sqlite and mysql mentioned here https://github.com/grafana/grafana/pull/21387#issuecomment-573057358 by adding Default value to migration (simillar to this https://github.com/grafana/grafana/blob/c1160d9bc238685ac1ec06826dd4c07fc115a6ca/pkg/services/sqlstore/migrations/annotation_mig.go#L121) but it still broken for postgres.

Can someone lend me a hand with postgres integration or point me to documentation how to run integration tests for the postgres locally? 

Adding a primary key is not a problem here I believe. The problem is the framework used to wrap migrations and that is where I am struggling.

**Comment by aknuds1** [comment]
Could you merge in latest Grafana master, in order to fix the CI build?

**Review by marefr — CHANGES_REQUESTED** [review]
To be able to pull this off so that we could possibly accept it you'll need to create a new table, migrate data, drop the old table and rename the new table. Similar to what we did here: https://github.com/grafana/grafana/blob/31ad86ffc086d1f04e1b7b570456d7e2c1621cb3/pkg/services/sqlstore/migrations/dashboard_mig.go#L56-L90

**Comment by azhiltsov** [comment]
@marefr I followed your advise and implemented the fix
@aknuds1 CI is currently broken due to https://github.com/grafana/grafana/pull/23171#issuecomment-605654849

**Comment by aknuds1** [comment]
@azhiltsov Yeah sorry, working on it.

**Comment by marefr** [comment]
@azhiltsov if you merge in latest master you should resolve CI.

**Comment by azhiltsov** [comment]
@marefr I updated the PR.

**Comment by marefr** [comment]
@azhiltsov thank you for the contribution. This looks ready to be merged :+1: However, we have Grafana v7 coming up and we have decided to not merge this until after Grafana v7 have been released.

**Comment by azhiltsov** [comment]
I rebased the PR on the top of current master. 
Is there a plan to merge it?

**Comment by marefr** [comment]
@azhiltsov yes, but we've been crazy busy lately. Will merge this to target v7.2 eventually.

**Comment by marefr** [comment]
@azhiltsov sorry for the slow response. Due to other recent changes of the database schema we didn't want to stress this  to reduce the risk of putting to many large database migrations in the same release. The current plan is to review and merge this for Grafana v7.4.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Sorry it took some time. Thank you for contributing to Grafana!

**Pull request merged**
