### PR TITLE
Tempo: Escape backslash in span name for promsql query

### LINKED ISSUE #79791: Tempo Service Graph bad_data error when span has regex in name
### What happened?

When going to the Explore page, selecting Tempo as datasource and selecting query type 'Service Graph' I see the following error:
image

This only happens when fetching spans which opentelemetry collects from kafka. These spans have a regex in their name. Here some examples:

- http delete /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**
- http get /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**
- http post /esb/{service:[a-za-z]+[\w-]*}/{version:[\d\.]*}/{serviceinstance:[a-za-z]+[\w-]*}/{operation:[a-za-z]+[\w-]*}
- http put /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**

I checked passed issues on this topic and found:

- https://github.com/grafana/grafana/issues/4234
- https://github.com/grafana/grafana/issues/54849

Also there has been a [PR](https://github.com/grafana/grafana/pull/66301) which was supposed to fix this issue but apparently there are still some edge cases.

Let me know if this is an issue in Grafana or if we have to fix something on our side. Thank you!

### What did you expect to happen?

Service Graph is displayed

### Did this work before?

It worked before we started collecting spans from kafka where we store esb traces. These contain some regex in their name (see above)

### How do we reproduce it?

1. I provided the span names with the regex (I hope thats enought)
2.
3.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

- Firefox 115.5.0esr (64-bit)
- Chrome 120.0.6099.110
- Grafana 10.2.2
- tempo 2.3.0
- opentelemetry-collector-contrib 0.86.0-krb5fix (collecting spans from kafka)
- opentelemetry-collector-contrib 0.82.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo, Prometheus

### PR DESCRIPTION
**Pull request by ttshivers**
In promsql, backslashes in regexes must be doubly escaped for them to be interpreted as a literal backslash character.

Fixes #79791

**What is this feature?**

Fix for the tempo service graph when dealing with spans with backslashes in their names.

**Why do we need this feature?**

In promsql, backslashes in regexes must be doubly escaped for them to be interpreted as a literal backslash character.

**Who is this feature for?**

Anyone who uses the service graph

**Which issue(s) does this PR fix?**:

Fixes #79791

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ttshivers** [comment]
Comment to scare off stale bot

**Comment by aocenas** [comment]
Hey @ttshivers sorry for looking at this so late. Just looked at the code and I am not sure this actually changes anything. You used the string version of replace so for the test it does not have any effect because `/\\/g` is used as a literal string instead of regex so it does match only literal `/\\/g` and the test also fails.

So the original regex is doing the `test\\path` -> `test\\\\\\path` with your addition (if it wasn't used as a string but regex) it would do `test\\\\\\\\\\\\path` which I think is a few too many `\` :D.

So I still need to test and reproduce the original error as I don't have an env for it right now.

**Comment by aocenas** [comment]
I pushed a change to the regex. There seems to be the same code in prometheus codebase but would be bit more work to reuse it right now.

**Review by aocenas — APPROVED** [review]

**Comment by ttshivers** [comment]
Thank you for fixing this up

**Pull request merged**
