### PR TITLE
Chore: Move from master to main branch

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Move from master to main branch and upgrade build pipeline tool to v2, which is ready for the change to main.

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good, 

Found master in github actions as well:
https://github.com/grafana/grafana/blob/master/.github/workflows/codeql-analysis.yml#L10
https://github.com/grafana/grafana/blob/master/.github/workflows/publish.yml#L6

opened this as well:
https://github.com/grafana/grafana-github-actions/pull/22

**Comment by aknuds1** [comment]
> Looks good,
> 
> Found master in github actions as well:
> https://github.com/grafana/grafana/blob/master/.github/workflows/codeql-analysis.yml#L10
> https://github.com/grafana/grafana/blob/master/.github/workflows/publish.yml#L6
> 
> opened this as well:
> [grafana/grafana-github-actions#22](https://github.com/grafana/grafana-github-actions/pull/22)

Thanks, will look.

**Comment by osg-grafana** [comment]
@jongyllen, @jhunthrop, @09jvilla, and @mjseaman  how about the timing of this merge wrt GE*? Any foreseeable issues with CI/CD dependencies?

**Comment by osg-grafana** [comment]
cc @robbymilo

**Review by dprokop — APPROVED** [review]

**Comment by aknuds1** [comment]
> Looks good,
> 
> Found master in github actions as well:
> https://github.com/grafana/grafana/blob/master/.github/workflows/codeql-analysis.yml#L10
> https://github.com/grafana/grafana/blob/master/.github/workflows/publish.yml#L6
> 
> opened this as well:
> [grafana/grafana-github-actions#22](https://github.com/grafana/grafana-github-actions/pull/22)

@torkelo think I fixed the GitHub actions. Want to have another look?

**Review by torkelo — APPROVED** [review]

**Review by osg-grafana — APPROVED** [review]

**Comment by aknuds1** [comment]
We're waiting for @xlson to give the thumbs up on behalf of the Enterprise team.

**Pull request merged**
