### PR TITLE
Adding support for MS SQL server

### PR DESCRIPTION
**Pull request by linuxchips**
Hi, i have added the basic support for mssql server datasource, based on the mysql and postgres files. I used the go-mssqldb driver.
I have also added a doc file for the datasource
any suggested changes would be much appreciated

### CODE REVIEW

**Comment by svenklemm** [comment]
Hello, nice to see support for more sql databases. I havent tested your patch but I glanced over a couple files.

Have you considered naming the time_column just `time` and support sql server native time datatypes directly instead of having to convert it to unix timestamp. Your macros seems to always subtract timezone difference, will that work with timezone aware datatypes when the servertime is not utc?

**Comment by linuxchips** [comment]
well, I looked at how the mysql plugin works and just copied that. and did not feel confident making too much changes. however, I ll take a look and test it out to see what I can do about the time field. any hints would be helpful :)
good point about the timezone issue, have not payed attention to. I assumed that the dates are in the local timezone, which is always our case. to get a correct unix time stamp, the best way I could think of is to do this "ugly" datediff thing, not sure if there is a better way. I ll do some test and adjust the code if I find any issue.
though I have not tested it with timezone aware data types, yet, as we are not using it in our databases. but i do not think it will work if the timezone of the field differ from the timezone of the server, even if the server is at utc. and i am unable to come up with a unified solution, maybe a different macro for each case? not sure...

**Comment by svenklemm** [comment]
The postgres datasource does handle native datetime types and also can derive metric names from column names and can handle multiple value columns per row. Would be nice to have similar features in other sql datasources.

**Comment by linuxchips** [comment]
I am adding the native support for sql datatypes of time. and it turned out that the time offset aware datatype (TIMEDATEOFFSET) is converted to the correct epoch based on the offset in the returned value when doing (Time.Inux()).
so I was wondering what would be best to do with the macros if we have TIMEDATEOFFSET, do we need to handle the cases of the timezone there or just note in the help that one do not need them in such case?

**Comment by svenklemm** [comment]
Neither postgres nor mysql tries to "fix" timezone differences in the macros. I think the proper way to do it is to use timezone aware datatypes if you need that functionality or store times in utc.

**Comment by linuxchips** [comment]
the reason both did not need to is because the database engine takes care of it, where mssql have no concept of "unix timestamp", not until v2016 at least. according to the docs, mysql UNIX_TIMESTAMP(date) function converts the time to utc (https://mariadb.com/kb/en/library/unix_timestamp/). postgres dose a similar job with extract(epoch ), check (https://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT)
I also can see the shift in the presented data from my mixed environment of both databases (mysql and mssql), in fact I had hard time debugging the shift until it hit me and remembered that unix timestamp is always at utc.
plus the macros will not hurt, and even if not complete, it may bring the issue to the attention of the users.

**Comment by daniellee** [comment]
@linuxchips a note from the Grafana team: 

Thank you for submitting this PR and we do intend to merge it. It looks extremely good for being your first PR ever (at least it looks like it is your first PR?). But at the moment, our focus is on the upcoming Grafana 5.0 release so it will be a 4-6 weeks  before we have time to test it properly. 

(Although @svenklemm has already given you some good feedback - thanks Sven!).

**Comment by linuxchips** [comment]
@daniellee thanks for your kind words, this is my first contribution in 7 years :)
and no problem for the delay, i ll get to have more testing in our environment, and may add a couple of things if i have the time for them.
would it be appropriate if I reflect the changes to the mysql driver? i.e. the native datetime and multi value time series, not sure i ll have the time for them though.

**Comment by ianpmurphy** [comment]
I'm unfamilar with both github and the procedures used in integrating changes of this type. I would guess that the fact that they have been submitted doesn't mean they have been integrated into the nightly build. I pulled down the latest build sources but couldn't find the code listed above anywhere in the tree. Could be my bad but I get the impression they are pending acceptance. 

Is there any way I can pull down these versions to try and compile them on my end? I'm interested in trying out the modifications.

**Comment by linuxchips** [comment]
you can clone my repo, and build it
do
`go get github.com/linuxchips/grafana`
then rename "linuxchips" to "grafana" so the code would compile
`mv ~/go/src/github.com/linuxchips ~/go/src/github.com/grafana`
then follow the procedure to build it from the README file

**Comment by ianpmurphy** [comment]
Thanks linuxchips. I just managed to get the build to compile. For those who are trying something similar you will also need to: install golang, install github client.

Once both are installed, open a command shell and the 'go' command should work:
`go get github.com/linuxchips/grafana`
If you have a vanilla install like me, this will pull down a copy to c:\users\yourprofile\go\
You will then need to do:
`setx gopath c:\users\yourprofile\go\`
close and reopen command shell so it picks up gopath as an environment variable
`cd %GOPATH%`
`cd src\github.com\`
`rename linuxchips grafana`
`cd grafana\grafana`
`go run build.go setup`
`go run build.go build`

The 'go run build.go setup' was rather critical as the build process couldn't find files until I had done this.

Download and install the gcc compiler from here http://tdm-gcc.tdragon.net/download
Download and install nodejs  from here  https://nodejs.org/en/download/ 
Installing nodejs will mean you can execute npm.exe. Open a command shell as administrator and do the following:
`npm --add-python-to-path='true' --debug install --global windows-build-tools`

now back to your normal shell window in the grafana directory:

`npm install -g yarn`
`yarn install --pure-lockfile`
`npm run build`

This last stage seems to be never ending on my machine. I'll leave it run overnight. node.exe is eating cpu and doing little else. Is this normal?

**Comment by ianpmurphy** [comment]
Any idea what the dependencies are in the tree? 

I built this on my machine, where it allows me to add a datasource, but when I zip up the bin,conf,data,public,scripts & vendor directories and copy this over to another box (where I had grafana 4), it reports 'index out of bounds' error when I try to add a data source. 

Obviously something is missing, but my machine now has a ton of stuff on it which is linked to building grafana and I'm not sure what is required to just run it.

**Comment by linuxchips** [comment]
the behavior of all the data sources that I tried require the port. so I thought to go along with the convention.
I am sure the others have more solid opinion about whether we should make a default or not

**Comment by ianpmurphy** [comment]
In the code the comment mentions making it the default port - which would certainly make sense. Having gone back through the process, I can see that the prompt requests localhost:1433, so I should have realised that it would require the ':' and to specify the port.

**Comment by AhmedAzzabi** [comment]
Can this be merged please, as it is much requested feature and looks good, when can we expect it to be released ?

**Comment by AhmedAzzabi** [comment]
When can this be merged ?

**Comment by aszumski** [comment]
Works Great.

Hope it get's merged soon.

**Comment by Ineptsmeagol** [comment]
I agree this would be a great feature.  I cannot wait for this to be merged

**Comment by biiiipy** [comment]
We're also delaying our deployment until this is merged

**Comment by jotdeh** [comment]
We would love to have this! 
Any idea when this would be available in the master, or if it can be made available as a data source plug-in?

**Comment by marefr** [comment]
We have created a new branch [mssql_datasource](https://github.com/grafana/grafana/tree/mssql_datasource) from your work @linuxchips. We have merged the latest changes from master to this branch and fixed conflicts due to Grafana v5.0 and recent changes in postgres/mysql datasources. Right now everything builds and seems to work.

We're aiming to do some changes so that the mssql datasource implementation is similar to the postgres and mysql datasource implementations and also to make the mssql datasource more feature complete (more macro function etc). Hopefully we can also create some common code that can be shared between all three sql datasources.

We're aiming at implementing these changes and test it out thoroughly and hopefully merge it to master soon.

Thanks a lot once again for your great contribution @linuxchips

**Comment by ianpmurphy** [comment]
@jotdeh Linuxchips build works fine and should be ok until they bring out the merged version. The instructions I posted above should just work and leave you with a working build.

**Comment by havedill** [comment]
Very excited for this

**Comment by marefr** [comment]
Hey @linuxchips where did you find the Microsoft SQL Server logo? Do you have any source for that?

**Comment by bladefist** [comment]
Not LinuxChips but eager to see this merged and released:
https://worldvectorlogo.com/logo/microsoft-sql-server
https://github.com/konpa/devicon/issues/4

**Comment by linuxchips** [comment]
@marefr I really can not remember, all I remember is that I looked hard till I found this one. I ll post a link if I found it in my browsing history.

**Comment by marefr** [comment]
Oh right. No worries. Was just interested in license due to possible legal aspect. We'll probably try and reach out to Microsoft to get an official logo. Until then we can merge data source to master and fix logo later. Thanks

**Pull request merged**
