### PR TITLE
Dashboard: do not repeat alert in panel

### LINKED ISSUE #21141: Repeat field also repeat alert
**What happened**:
after setting alert on a repeating panel,
all repeated panel will have same alert,
and click save will leading backend has duplicate alert which belong to repeat panel

**What you expected to happen**:
repeat panel do not repeat alert

**How to reproduce it (as minimally and precisely as possible)**:
1. add a repeat panel
2. set alert on first repeat panel and save
3. refresh page, and all repeat panel has alert, and save
image
image

4. there are duplicate alert in backend

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins: N/A
- Others:

### PR DESCRIPTION
**Pull request by okhowang**
**What this PR does / why we need it**:

repeat panel's alert make backend have duplicate alert

**Which issue(s) this PR fixes**:

Fixes #21141

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Thanks for contributing!

**Comment by torkelo** [comment]
However, template variables are not supported in alert queries, so this use cases won't work.

We are planning to make alerts standalone rules you create & maintain separately from dashboards & graphs. So this won't be something we will ever support.

**Comment by okhowang** [comment]
repeat panel can also has non template query and alert
which will be duplicate when repeating

one more thing, new standalone alert looks like to be not compatible with current alerts,
why do not accept enhancement/bugfix about current alert, at least there is no better alert module in grafana now.
and about new standalone alerts, is there some detail plan or roadmap?

**Comment by torkelo** [comment]
Why create duplicate identical rules then?

Standalone alert rules will be compatible, just a different UI to create and edit them outside of a dashboard 

No detailed roadmap yet, mostly design docs

**Comment by okhowang** [comment]
> Why create duplicate identical rules then?

for example I have a template query for each cgi process time, and repeat it with cgi.
but I also want to compare `avg process time of all cgi` and `avg process time of specific cgi`
then I have a repeat panel with query A(non-template query) and B(template query)
at last i need add alert for query A, when A is too large, we need be notified

**Pull request closed without merging**
