### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by altmas5**
**What this PR does / why we need it**:
Remove consecutive occurrences of 'the'

**Which issue(s) this PR fixes**:
Trivial typos

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]
<3

**Review by aknuds1 — APPROVED** [review]
Nice!

**Review by oddlittlebird — APPROVED** [review]
You rock. Thanks for contributing!

**Comment by altmas5** [comment]
It was nothing, actually you rock!

**Pull request merged**
