### PR TITLE
Explore: Remove support for legacy, compact format URLs

### LINKED ISSUE #48174: Explore: Remove support for compact Explore URLs [9.0.0]
follow up to https://github.com/grafana/grafana/pull/44385.

support for compact URLs in explore was deprecated and it should be removed in a future release.

there is a parameter to be removed in https://github.com/grafana/grafana/blob/ea48d131ee27ad3723958f0f02319dbb76b5bedf/packages/grafana-data/src/utils/url.ts#L205 and in https://github.com/grafana/grafana/blob/6415b9a54dec6e9763f2faee076ce6578564b072/public/app/core/utils/explore.ts#L220 the parsing logic can be cleaned up. 

In the PR it's mentioned to remove it for Grafana 9, but this is subject to change.

### PR DESCRIPTION
**Pull request by gelicia**
**What this PR does / why we need it**:
In #44385 we deprecated the compact format for URLs. This completes the deprecation and removes all relevant logic for 9.0.0. 

**Which issue(s) this PR fixes**:
Fixes #48174

### CODE REVIEW

**Review by Elfo404 — DISMISSED** [review]
Looks great! 🚀 

can we also remove the second argument from `serializeStateToUrlParam` in https://github.com/grafana/grafana/blob/ea48d131ee27ad3723958f0f02319dbb76b5bedf/packages/grafana-data/src/utils/url.ts#L205 ?

**Comment by gelicia** [comment]
> can we also remove the second argument from `serializeStateToUrlParam` in
> 
> https://github.com/grafana/grafana/blob/ea48d131ee27ad3723958f0f02319dbb76b5bedf/packages/grafana-data/src/utils/url.ts#L205

Good catch!

When I looked at this again, it seems to me we'd only be using that function for type-checking the incoming object. I removed the function altogether in this and removed its usage but I'm wondering if we should keep it for checking that type? Let me know what you think

**Comment by Elfo404** [comment]
the main issue i see with removing the function altogether is that it wasn't marked as deprecated (we only marked the second argument as deprecated, my bad) so i'm not sure if removing it from `@grafana/data` is the best option.

I don't expect it to be widely used (if at all) but i'd personally rather keep it. wdyt?

**Comment by gelicia** [comment]
> the main issue i see with removing the function altogether is that it wasn't marked as deprecated (we only marked the second argument as deprecated, my bad) so i'm not sure if removing it from `@grafana/data` is the best option.
> 
> I don't expect it to be widely used (if at all) but i'd personally rather keep it. wdyt?

Makes sense we wouldn't want to just remove a function without deprecating it first. Removed those changes and removed the deprecated parameter instead.

**Review by Elfo404 — APPROVED** [review]
GR8! 🚀

**Pull request merged**
