### PR TITLE
Add Histogram rendering support

### PR DESCRIPTION
**Pull request by woodsaj**
This pull request adds support for rendering data as a histogram (#600).

image

### CODE REVIEW

**Comment by jaingaurav** [comment]
Can this PR be merged? Would really be great to have histograms in grafana.

**Comment by torkelo** [comment]
@jaingaurav it needs a little more work, and there is so much else to do :(

**Comment by makapuf** [comment]
:+1: !

**Comment by Dieterbe** [comment]
aww what ever happened to this. it looks nice :)

**Comment by jeromegit** [comment]
That'd be great if it could be added/merged

**Comment by szibis** [comment]
Nice :+1:

**Comment by jamtur01** [comment]
@woodsaj Any chance you might revisit with the tests @torkelo suggested? Happy to help.

**Comment by StianOvrevage** [comment]
+1!

**Comment by comcomservices** [comment]
Histograms would be awesome!!  Please let me know what needs to be done before this can be merged and I'll work on it

**Comment by shoonoise** [comment]
:+1:

**Comment by willowpet** [comment]
+1

**Comment by juanmaneo** [comment]
Very nice :+1: 
Any chance of getting this merged ?

**Comment by mabdullah2010** [comment]
+1. Would love to see this merged.

**Comment by comcomservices** [comment]
Working on learning golang so I can fix this baby :)

**Comment by Dieterbe** [comment]
@comcomservices 
> Working on learning golang so I can fix this baby :)

this is all client side rendering in javascript AFAIK :)

**Comment by shoonoise** [comment]
Seems like the PR for Grafana 1.x, so it needs to be rewrite.

**Comment by mtanda** [comment]
+1

**Comment by bergquist** [comment]
I'm closing this due to inactivity.

Feel free to reopen as a new pull requests once it's been merged with master and include tests.

**Comment by karelstriegel** [comment]
+1. Would love to see this merged.

**Comment by mtanda** [comment]
@karelstriegel  I create panel plugin, if you want, you can use it.

https://github.com/grafana/grafana/issues/600#issuecomment-168665407
https://github.com/mtanda/grafana-panel-plugin-histogram

**Pull request closed without merging**
