### PR TITLE
Plugins: add env variables needed for the secure socks proxy in the plugins sdk

### PR DESCRIPTION
**Pull request by stephaniehingtgen**
**What this PR does / why we need it**:

This PR adds the necessary environment variables for https://github.com/grafana/grafana-plugin-sdk-go/pull/667, so that plugins can begin using the functionality

**Which issue(s) this PR fixes**:

Relates to https://github.com/grafana/hosted-grafana/issues/3369

### CODE REVIEW

**Comment by stephaniehingtgen** [comment]
Converting to draft until SDK changes are in

**Review by wbrowne — COMMENTED** [review]
Code LGTM, but looks like you need to update your existing tests!

**Comment by stephaniehingtgen** [comment]
> Code LGTM, but looks like you need to update your existing tests!

Ah good call - now the sdk ensures it's a bool, that section of the unit test can be removed

**Review by chaudyg — APPROVED** [review]
Also LGTM.

**Review by wbrowne — APPROVED** [review]

**Pull request merged**
