### PR TITLE
/api/search doc: Clarify documented behaviour of `page` parameter of /api/search

### PR DESCRIPTION
**Pull request by antonysouthworth-halter**
**What is this feature?**

IMO this is not very clear:

> Numbering starts at 1.

...So if I got a response with max number of items, should my next request say `page=1` or `page=2`?

Instead make it clear that, when omitted, it's the same as saying `page=1` and therefore the next request obviously should be `page=2`.

**Why do we need this feature?**

Disambiguate documentation.

**Who is this feature for?**

Any user of the API.

**Which issue(s) does this PR fix?**:

None.

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Eve832** [comment]
This PR needs a tech review for accuracy

**Comment by antonysouthworth-halter** [comment]
bump? (btw please let me know if this is not ok to do)

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

**Comment by antonysouthworth-halter** [comment]
(bump)

**Review by inf0rmer — APPROVED** [review]

**Pull request closed without merging**
