### PR TITLE
E2C: Empty and Loading snapshot states

### LINKED ISSUE #89537: E2C: Status polling
When loading a migration page (or after clicking create snapshot/upload buttons?), poll the `/cloudmigrations/migration/{uid}/run/{uid}/status` endpoint and display the status in the UI.

If the status endpoint shows an error (in the middle of polling), display the error in a modal and stop polling.

### LINKED ISSUE #90039: E2C: No snapshot empty state
Once you're entered your token, there's a new CTA in the empty state before you've created a snapshot

### LINKED ISSUE #90044: E2C: Migrate snapshot async API

### PR DESCRIPTION
**Pull request by joshhunt**
High-level UI update to the Async Snapshot workflow in Cloud Migration

 - Splits the migration summary info into a seperate component, and added placeholder time and counts
 - Adds an empty state call to action to build the snapshot 
7812_2024-07-04-11-22_firefox
 - Adds an in-progress state with a button to cancel snapshot creation 
7813_2024-07-04-11-22_firefox

Note - at the moment the PENDING_UPLOAD state is a bit wonky. My understanding is that in the future (before release) we'll get back a list of resources here that we can display  
7814_2024-07-04-11-23_firefox

Fixes https://github.com/grafana/grafana/issues/89537  
Fixes https://github.com/grafana/grafana/issues/90039
Fixes https://github.com/grafana/grafana/issues/90044

### CODE REVIEW

**Comment by joshhunt** [comment]
@eledobleefe We'll need to use API to turn on the feature toggle and developer_mode config for the test instance

**Comment by eledobleefe** [comment]
The code looks good and it works well on local. I just found this when narrowing the screen:

Captura de pantalla 2024-07-04 a las 17 41 45

**Review by eledobleefe — APPROVED** [review]
LGTM! Good job 🎉

**Pull request merged**
