### PR TITLE
Alerting: Add provisioning endpoint to fetch all rules

### PR DESCRIPTION
**Pull request by alexweav**
**What is this feature?**

This adds a simple endpoint to the Provisioning API - GET `/api/v1/provisioning/alert-rules`. It supplements the existing GET `/api/v1/provisioning/alert-rules/{uid}` by allowing a caller to list all existing rules.

**Why do we need this feature?**

API completeness/consistency. Allows callers to fetch all existing rules through the provisioning API.
They can already do this via GET `/api/ruler/grafana/v1/rules`, but the format is different, the provisioning API is easier to use and more visible, so that's where users expect it.

**Who is this feature for?**

Users who implement tooling against the provisioning API.

Fixes: n/a

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alexweav** [comment]
No pagination for now. Overall, this endpoint returns less data than `/api/ruler/grafana/v1/rules`, so it's not a bottleneck. It's also designed in such a way that pagination can be added without breaking the json format.

**Review by alexmobo — APPROVED** [review]
LGTM

**Comment by gelicia** [comment]
@alexweav FYI the docs around this endpoint currently mark UID as required

**Comment by alexweav** [comment]
@gelicia correct, we have not yet regenerated those docs. I think we want to wait a bit on this though, as we have more than one route also being added to that subpath. The OpenAPI doc is the most up to date reference.

**Comment by danfinn** [comment]
Without this feature, how can one get a list of all of their alert UIDs?  Will the output that is returned from this API be able to be used to provision from a file (without modification)?

**Comment by alexweav** [comment]
1. It will return a list of all rules, each with UID.
2. There is another route for that, being added in separate PR (that is already open). We are adding `/export` endpoints that give the yaml.

**Comment by danfinn** [comment]
Is there a way that I can track that /export feature?  What I'm trying to do is configure alerts via the UI, export via the API (or UI if possible) and then provision from a file.  It's currently not at all clear how to do that from any documentation that I can find but it sounds like this /export endpoint is what I need?

**Comment by alexweav** [comment]
Sure, it's this PR: https://github.com/grafana/grafana/pull/58623

**Comment by alexweav** [comment]
Yes, also that issue.

**Comment by laa88rf** [comment]
Please add status of alert-rule
Firing/Pending/Normal etc.

I see only in `/api/prometheus/grafana/api/v1/rules`

**Comment by alexweav** [comment]
Hi @laa88rf, such a change would be orthogonal to this PR as the single-rule endpoint doesn't do this either. We'd be happy to accept a [feature request](https://github.com/grafana/grafana/discussions/categories/alerting) for this.

**Pull request merged**
