### PR TITLE
Add iLert Grafana alerting integration to documentation

### PR DESCRIPTION
**Pull request by BirolYildiz**
Signed-off-by: Birol Yildiz birol@ilert.com

**What this PR does / why we need it**:

This PR adds iLert to the list of supported notifiers in the Grafana docu.

**Which issue(s) this PR fixes**:
None

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
Looks good. Needs a dev review. Adding alerting squad to the review.

**Comment by davidmparrott** [comment]
I'm not in favor of this change because we don't actually support the iLert integration and do not have a notifier for it. This implies that we have some control over, and knowledge or, iLert by saying we support it, which is not that case.

**Comment by BirolYildiz** [comment]
> I'm not in favor of this change because we don't actually support the iLert integration and do not have a notifier for it. This implies that we have some control over, and knowledge or, iLert by saying we support it, which is not that case.

This was supposed to complement your current list of webhook based notifiers. We have added support for Grafana [2 years ago](https://www.ilert.com/blog/ilert-grafana-integration) and thought it's worth mentioning that iLert is fully supported as a notification channel through Grafana's webhook notifier.

**Comment by BirolYildiz** [comment]
Any updates on this? @davidmparrott @achatterjee-grafana

**Comment by BirolYildiz** [comment]
Maybe I'm missing something. How is this PR different from the [current list](https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/) of webhook integrations, @davidmparrott?

image

**Pull request closed without merging**
