### PR TITLE
AzureMonitor: Add Microsoft.Insights/components metric namespace

### LINKED ISSUE #37435: can not select application insights ResourceType in china
**What happened**:
can not select application insights resource type
image

but i edit in query inspector like this
image
it can show application insights data 
image
 
i am use azure montor in china 

image

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Azure Monitor & 3.0.1 (AzureChina)
- OS Grafana is installed on: Windows 2016
- User OS & Browser: Microsoft Edge 92
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

The metric `Microsoft.Insights/components` was missing for other clouds than the public cloud.

**Which issue(s) this PR fixes**:

Fixes #37435 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by vickyyyyyyy — APPROVED** [review]

**Comment by virtualcca** [comment]
i found in module.js also missing "Microsoft.Insights/components", whether it needs to be added as well？

**Comment by andresmgot** [comment]
@virtualcca I think you may be looking to the compiled version of grafana (there is no module.js in the source code here). The only place in which metric namespaces are defined is in the file this PR modifies. In any case, I could be missing something, what's the path of the file you are referring to?

**Comment by virtualcca** [comment]
I tried to change the code here in my local grafana as well, but I found that the options for appsights still couldn't be displayed without effect
So I tried to search globally for the content and then found it
(I mainly use the chinaazure)

image

**Comment by andresmgot** [comment]
@virtualcca depending on how you are running grafana, you may need to restart the server or re-build it. Can you verify if the new code is running? (for example printing something with `console.log`).

**Comment by virtualcca** [comment]
I just directly modified the source file in my deployed program and restart it, which may not be correct, and I'm testing it when the next beta package comes in

**Comment by virtualcca** [comment]
I upgrade to 8.3.0 and find applicationInsights
but it was shown twice

image


At least it's working now

**Comment by andresmgot** [comment]
That could be because there are different resources with the same name but different namespace ID (probably a different case of the ID e.g. `Microsoft.Insights/component` vs `microsoft.insights/autoscalesettings`)

**Comment by virtualcca** [comment]
I found in "Log" also can not show app insights
image
image
image

Same as the previous metric
I forcibly modify the resource in the json in the "query inspector" to work, but it can't be selected on the page

image

**Comment by andresmgot** [comment]
thanks @virtualcca that seems like a different problem. Can you open a new issue with that info?

**Pull request merged**
