### PR TITLE
[WIP] Add prometheus datasource

### PR DESCRIPTION
**Pull request by jimmidyson**
We'd love to make Prometheus a first class datasource in Grafana. This PR takes the code from [grafana-plugins](https://github.com/grafana/grafana-plugins/tree/master/datasources/prometheus) & tweaks it to work with grafana master.

I'm not 100% sure what you'd require for this to be accepted, hence marked as WIP, Let me know & I can try to add it in.

/cc @fabxc

### CODE REVIEW

**Comment by torkelo** [comment]
please add unit tests under the plugins/datasource/prometheus/specs/ folder (see graphite or elasticsearch for examples),  also naming of files should be from now on underscore (not pascal case), only applies to file names (a lot of js files in grafana do not follow this, as it is a new convention I am moving to).

**Comment by torkelo** [comment]
pleasantly  surprised by the low amount of code the PR :)

**Comment by torkelo** [comment]
Been testing this. Been working ok when time range is bigger than  30m, whenever I go below 30m I get no datapoints (be it relative or absolute range (Which I guess does not matter as it is always sent as absolute epochs).

Is there a limit in Prometheus where you cant query for small time ranges?

**Comment by fabxc** [comment]
Thanks for doing this @jimmidyson.

@torkelo none whatsoever.
We got reports about a possible regression in the grafana-plugins repository. As this is the same code, there's probably a bug buried somewhere.

**Comment by torkelo** [comment]
Is Prometheus like OpenTSDB in that there is no generic way to do roll ups? (Like graphite where you can specify a roll up scheme that is applied to all metrics)

**Comment by jimmidyson** [comment]
@torkelo OK looks like a problem in how the step is calculated. Working on it.

**Comment by jimmidyson** [comment]
@torkelo @fabxc Interval should be fixed up now.

**Comment by torkelo** [comment]
@jimmidyson I can't see any more commits to this PR

**Comment by jimmidyson** [comment]
@torkelo I'd squashed them - would you prefer I push multiple in future?

**Comment by torkelo** [comment]
that is very problematic as I started testing this (and adding prometheus docker stuff) to prometheus branch, I cannot pull from this branch any more. Its very bad practice to change pushed commits

**Comment by jimmidyson** [comment]
@torkelo Sorry if you think it's bad practice. I work on many open source projects who actively ask for squashed commits in PRs. I will remember that you don't like it though. Sorry again.

I guess it shouldn't be too bad for you to rebase against this branch now & I'll push new commits without squashing going forward?

**Comment by torkelo** [comment]
yes, I mean squashing could be fine right before a merge maybe but will cause merge issues for anyone pulling from this PR branch as it will fail with a bunch of conflicts.

**Comment by juliusv** [comment]
Oh, adding this to Grafana proper would be awesome - thanks @jimmidyson! I'll be happy to add improvements to this plugin later on - improved Prometheus support in Grafana will be very useful for many people.

@torkelo Ah, that's what you mean regarding squashes. Hmm, interesting - instead of merging, I usually do a `git fetch -a` and `git checkout origin/<branchname>` for testing PR branches locally. But yeah, if you merge every time, then it's better to not squash in between.

**Comment by jimmidyson** [comment]
Sure. I didn't know you were actually doing anything with it beyond running it & trying it out TBH. New commits being pushed now ;)

**Comment by jimmidyson** [comment]
@juliusv Right now this is looking pretty good. Just tested out the templating stuff & works nicely, albeit a little unintuitively. Can use labels endpoint or use `count(up{...}) by (...)` trick & extract labels via regex in the normal grafana way. Would like some more eyes on it if you get the chance.

**Comment by juliusv** [comment]
@jimmidyson Awesome, I will play with this until tomorrow!

**Comment by torkelo** [comment]
This PR will need a lot of continued work from me and who ever want to contribute, unit tests, refactoring, improvements to the editor etc before a merge into master, so I created a Prometheus branch for that. not sure how to best manage that process as this PR is against master

**Comment by torkelo** [comment]
maybe close this PR and further improvements are PRs against prometheus branch?

**Comment by jimmidyson** [comment]
@torkelo Closing & will reopen against prometheus branch. Thanks for your help with this!

**Pull request closed without merging**
