### PR TITLE
CloudMonitoring: Avoid to escape regexps in filters

### LINKED ISSUE #41706: GCP Google Cloud Monitoring variable regex escaping forward slash incorrectly
**What happened**:
When using the regex filters with a Google Cloud Monitoring "Metrics" query that has a variable value that contains a forward slash (`/`) and leveraging the `=~` filter, using that variable results in an invalid query due to the `/` being escaped when it shouldn't.

**What you expected to happen**:
The forward slash `/` should not be escaped when creating a GCP metrics query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to dashboard variables
2. Create "custom" dashboard variable of type `custom`, call it "ApiMethod", set the custom option values to be `/` (screenshot 1)
3. Create a panel with a GCP metrics query, create a regex filter `=~` and have the value be the `ApiMethod` template variable (screenshot 2)
4. See the error message in the Query 
```
query failed: { "error": { "code": 400, "message": "Field filter had an invalid value of \"metric.type=\"logging.googleapis.com/user/MyExampleMetricCount\" metric.label.method=monitoring.regex.full_match(\"\\/\")\": Could not parse filter \"metric.type=\\\"logging.googleapis.com/user/MyExampleMetricCount\\\" metric.label.method=monitoring.regex.full_match(\\\"\\\\/\\\")\"; unsupported escape sequence in a string literal at line 1, column 106, token '\"\\/\"'", "status": "INVALID_ARGUMENT" } }
```

**Anything else we need to know?**:
It appears (though not explicitly stated in the docs), that the forward slash should NOT be escaped when using `monitoring.regex.full_match`

**Environment**:
- Grafana version: v8.2.3
- Data source type & version: "Google Cloud Monitoring" version default
- OS Grafana is installed on: Official grafana docker image (`docker pull grafana/grafana:8.2.3`)
- User OS & Browser: N/A
- Grafana plugins: None other than defaults
- Others:

image

image

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

Using regexps or special characters in the filter section of a Cloud Monitoring query causes an error. See more context at #41706 and #41751.

This field is not meant to be escaped so I am removing that logic.

**Which issue(s) this PR fixes**:

Fixes #41706

**Special notes for your reviewer**:

cc/  @MatthewLymer

### CODE REVIEW

**Review by sunker — APPROVED** [review]
Looks good to me, but would be great to get a :+1: from @MatthewLymer since he caught the issue in the first place.

**Comment by MatthewLymer** [comment]
Thanks for this change, I'm trying to build the docker file so I can do my testing, but I'm running into issues.  I'll let you know when I get it figured out.

**Comment by MatthewLymer** [comment]
This seems to have broken all my queries that leverage a regex variable.

```
filters:Array[11]
0:"metric.label.module"
1:"="
2:"httpsOnRequestApi"
3:"AND"
4:"metric.label.status"
5:"=~"
6:"{failed,succeeded}"
7:"AND"
8:"metric.label.method"
9:"=~"
10:"{POST /2020-04/labels.create,POST /2020-04/tracking.get,POST /2020-10/labels.bulk.create,POST /2020-04/labels.delete,POST /2020-04/rates.get,POST /2020-10/labels.create,POST /2020-04/labels.print,POST /2021-09/rates.bulk.get}"
```

where for `6:` I would expect `(failed|succeeded)`, and for `10:` I would expect:
```(POST /2020-04/labels\.create|POST /2020-04/tracking\.get|POST /2020-10/labels\.bulk\.create|POST /2020-04/labels\.delete|POST /2020-04/rates\.get|POST /2020-10/labels\.create|POST /2020-04/labels\.print|POST /2021-09/rates\.bulk\.get)```

**Comment by andresmgot** [comment]
That's what I meant with that this would be a breaking change in https://github.com/grafana/grafana/pull/41751#issuecomment-972700559.

You would need to replace your variable: `$Method` with `${Method:regex}`. The problem with that is that it would escape the slashes again (the same behavior without this PR I assume) so it would not work either.

Another option would be to just add the wrapping `(elem|...)` rather than `{elem,...` which is the default now in case the variable is multi-value but that would require more custom logic. Not sure if that's the path we want to follow.

**Comment by andresmgot** [comment]
@MatthewLymer could you try again? it should work for all your cases now

**Comment by MatthewLymer** [comment]
I feel like there's a misunderstanding as to what the problem is.  The template variables still need to be escaped for REGEX, but they need to be escaped in a way that's valid for GCP (the Google RE2 format).

I've created a PR to merge into this branch that I feel solves the issue, I've tested this locally and there's no backwards compatibility issues either.

https://github.com/grafana/grafana/pull/42325

Thank you for your consideration.

**Comment by andresmgot** [comment]
> The template variables still need to be escaped for REGEX, but they need to be escaped in a way that's valid for GCP (the Google RE2 format).

Not really, if you select the operator `=~` that should mean that whatever comes next is already an expression (not like the  `=` operator, which expect a perfect match). If you'd really want to use a valid RE2 regex, as the function supports, and you escape it, it wouldn't be possible. See my comment in your PR.

**Comment by MatthewLymer** [comment]
I've always had to use `=~` when leveraging any sort of multivalue template variable.

My use case is I have a multivalue template variable, such as `statuses = ["succeeded", "failed"]`, or `paths = ["POST /users", "GET /me"]` and I've ALWAYS had to use `=~` in order to get my query to do what I want.

Is the real problem that the `=` is behaving incorrectly, and instead should be sending a regex match behind the scenes?

image

Where in this, the match for `metric.label.status` should be `=~` and not `=`, as obviously the label's value will not have the verbatim `(succeeded|failed)` as its value.

I'm sorry for the confusion here, but either the `=` does not work in any capacity for multiple value template variables and I shouldn't even be attempting to use `=~` at all for my use-case (which is match ANY of the provided values), OR, the `=~` is working as expected with the exception of incorrectly escaping `/`, my assumption was the latter because the former is a major, common use-case.

Can you please clarify my understanding?

**Comment by andresmgot** [comment]
Yes, you understand it correctly! It's not possible to use the operator `=` if you are trying to match against multiple values (sorry if my previous message made you think otherwise).

So let me elaborate (this may be a bit confusing). You can use the operator `=~` for two cases:
 1. You want match against possible multiple values (your use case). 
 2. You want to match against a regex. This is not working in the `main` branch at the moment, because you get the same error that you found, but for different characters. This is because our process to escape regexps is not compatible with Google RE2.

With this PR both of the use cases above should work (so this code should work for all your dashboards). Your PR (#42325) fixes the bug for 1. but still doesn't allow the second.

Hope that makes sense. Let us know if you are able to verify that this indeed fixes the bug for you without causing regressions.

**Comment by MatthewLymer** [comment]
Thank you for the clear explanation, it makes sense to me now.

The change indeed works for my use-case.

For case 1, however, could this be a breaking change if a user's template variable may have a special regex character?  In either case I'm good with the change as it doesn't affect me, but just making sure others won't be affected.

**Comment by andresmgot** [comment]
> For case 1, however, could this be a breaking change if a user's template variable may have a special regex character? In either case I'm good with the change as it doesn't affect me, but just making sure others won't be affected.

Yes, this is a bug/feature situation. There may be edge cases in which a someone was using a special character (for example the dot `.`) and not escaping it might result on matching a different result. In that case, the "bug" was beneficial but the remediation is simple (manually escaping the character or specifying a more specific value). The other way around is not possible.

Thanks for the feedback!

**Pull request merged**
