### PR TITLE
extracts alertmanager from DI, including migrations

### PR DESCRIPTION
**Pull request by owen-d**
This PR does a few things
1) Removes the Alertmanager struct from the DI framework. This makes testing & instantiation much simpler and paves the way for future improvements, such as introducing more non-global Prometheus metrics.
2) Extracts related DB migration from the DI code
3) Prefer a pointer to `DBStore` in methods & usage, given that we have other struct-specific fields and I want to protect from by-value semantics.

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]
LGTM

**Review by papagian — COMMENTED** [review]
thanks, I really like removing it from the DI!

It seems that the test fails [here](https://github.com/grafana/grafana/blob/66020b419cd1626df4784871bd6c513fdda99d25/pkg/services/ngalert/notifier/alerts.go#L109)  because dispatcher is not initialised.
This is instantiated inside [applyConfig()](https://github.com/grafana/grafana/blob/1a649afdd88f96764bdd1ed03c23703c6a0a7673/pkg/services/ngalert/notifier/alertmanager.go#L335)
~I think that you need to call [am.SyncAndApplyConfigFromDatabase()](https://github.com/grafana/grafana/blob/1a649afdd88f96764bdd1ed03c23703c6a0a7673/pkg/services/ngalert/notifier/alertmanager.go#L172) which it was used to be called by Run().~ I think you need to call Run() [after creating it](https://github.com/grafana/grafana/blob/3618b11222c39b17ab2f0f202343d04530d81051/pkg/services/ngalert/ngalert.go#L70).

**Comment by owen-d** [comment]
Thanks for the review @papagian. I've sync'd it up to the parent run method now.

**Comment by torkelo** [comment]
@owen-d 
this is not making it into v8 (no backport)  

v8 beta1 released today, any PR needs a backport v8.0.x to be released in v8

**Comment by gotjosh** [comment]
I just ran into a bit of trouble because this is not backported I'm on it.

**Pull request merged**
