### PR TITLE
Chore: update typescript and tslib versions

### PR DESCRIPTION
**Pull request by ryantxu**
Hoping vscode will complain less about spread operators with an updated tslib :crossed_fingers:

### CODE REVIEW

**Comment by Clarity-89** [comment]
Seems like there are a few type issues that need to be fixed. No issues on the Enterprise side though.

**Review by aocenas — APPROVED** [review]
makes sense I guess we can merge after build is fixed

**Review by dprokop — APPROVED** [review]
LGTM, @ryantxu. I've fixed the ts issues.

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌 

i pushed an empty commit since drone was stuck 🤷

**Comment by ryantxu** [comment]
:scream: 
image

**Pull request merged**
