### PR TITLE
Docs: Update stat-panel.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Adds aliases for the Singlestat panel.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**: #251 in Weaveworks (hopefully)

Fixes #251

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

**Comment by dholbach** [comment]
Apparently https://github.com/grafana/grafana/runs/713322093 failed.

**Comment by oddlittlebird** [comment]
Not because of this PR.

**Comment by dholbach** [comment]
Sure. Just wanted to raise it, so everybody's aware this didn't land yet.

**Comment by dholbach** [comment]
:checkered_flag:

**Pull request merged**
