### PR TITLE
Docs: Update the service account HTTP API documentation

### PR DESCRIPTION
**Pull request by ZPascal**
**What is this feature?**

Update the documentation and add the missing part of the service account deletion.

**Why do we need this feature?**

A good documentation is necessary to call the API correctly.

**Who is this feature for?**

For all people who use the service account API.

**Labels and Milestones:**
I'm an external contributor, so for me, it's not possible to add any related labels or milestones, but I would suggest to back port the documentation change.

backport v9.3.0
backport v9.2.x
backport v9.1.x
backport v9.0.x
backport v8.5.x
no-changelog

### CODE REVIEW

**Comment by ZPascal** [comment]
@Eve832 Could you please have a look?

**Review by Eve832 — APPROVED** [review]
lgtm; however, do you want to backport these changes to previous versions? What version are these updates tied to?
do you want the changes reflected in the changelog?

**Comment by ZPascal** [comment]
Hi @Eve832,

I've checked the history of the change and would back port it to the following releases:
backport v9.3.0
backport v9.2.x
backport v9.1.x
backport v9.0.x
backport v8.5.x

I think a potential changelog change is not necessary.

**Comment by ZPascal** [comment]
@Eve832 Could you please have a look to further drive this topic?

**Comment by ZPascal** [comment]
Could someone please assist here?

**Comment by tonypowa** [comment]
👋 @Eve832 
Hi Eve
Whenever possible, could you please follow up with the author?
Thank you

**Review by Eve832 — APPROVED** [review]

**Pull request merged**
