### PR TITLE
Fix: Pinning github actions publish_docs node version

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What this PR does / why we need it**:
Pinning the publish docs action should resolve yarn install issues like https://github.com/grafana/grafana/runs/8115122455?check_suite_focus=true#step:7:1827

This has to be backported to the `v9.x` branch

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]
approving tentatively, but would like to go back `node-version: '16'` once we fix the root cause.

**Comment by jackw** [comment]
I'm not sure this should be merged this to main. 🤔 Maybe I'm missing something but if the specific issue is version incompatibilities between dependencies in the v9.0.x branch isn't it preferable to address it in that branch rather than also in `main`?

**Comment by ashharrison90** [comment]
alternative here: https://github.com/grafana/grafana/pull/55016

**Comment by ashharrison90** [comment]
superseded by https://github.com/grafana/grafana/pull/55016

**Pull request closed without merging**
