### PR TITLE
s3uploader: updated credentials chain to support ECS (#12570)

### PR DESCRIPTION
**Pull request by maxvw**
This PR adds supports for AWS ECS Task IAM Roles (#12570)

I have used the same approach that I found in a PR to make CloudWatch compatible with ECS, hopefully this will find it's way in a release soon.

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo To test this PR in my env, I need to build docker image.
Would you tell me how to build Grafana docker image?

**Comment by mtanda** [comment]
@torkelo Thanks, when the PR is merged, start to test this PR.

**Comment by xlson** [comment]
@mtanda #12798 has been merged and will allow you to build a Grafana docker image locally easily if you are running on linux/amd64.

Use `make build-docker-dev` which will give you an image tagged `grafana/grafana:dev`. If you are not on linux you will have to wait for #10655 instead.

**Comment by mtanda** [comment]
Sorry, I can't have time to test this...
If anybody can review/test this, please take over.

**Comment by maxvw** [comment]
@torkelo since @mtanda said he does not have time to test this, is there anyone else you can assign for review?

**Pull request closed without merging**
