### PR TITLE
GraphNG: support auto and explicit axis width

### LINKED ISSUE #4469: [Feature Request] Option to align/match Y-axis width
I would love to have the Y-axises' width aligned on multiple graphs. 

For example on the below screenshot, I have 2 graphs with information about a given humidity sensor, and at the bottom a graph that shows the speed of my ventilation. However, the different type of axis data cause the axises to have a different width. This makes it harder to compare the graphs because they are basically shifted and stretched compared to each other.

grafana_alignment

I'm running versoin 2.6.0

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #4469

Explicit:
image

Auto:
image

### CODE REVIEW

**Comment by leeoniya** [comment]
a proper fix for the linked issue has to address:

- explicit sizing of all y axes (secondary, tertiary, etc)
- explicit sizing of x gutters (the y side which contains no axes)

without these, the requirement shown in the image with the initial report cannot be satisfied.

**Comment by ryantxu** [comment]
I'm pretty sure we support:
> explicit sizing of all y axes (secondary, tertiary, etc)

The caveat is that the scale&axis settings are derived from the union of all the fields that share the same unit -- it is a little weird, but in practice I think that makes the most sense and fits with existing infrastructure pretty clearly

**Comment by dprokop** [comment]
> > I'm pretty sure we support:

> explicit sizing of all y axes (secondary, tertiary, etc)

Yeah, with the changes in this PR that makes field config's axis width being used back again, we can size axes using the overrides.

**Review by dprokop — APPROVED** [review]
Just tested this, and it works as expected!

**Review by torkelo — APPROVED** [review]
LGTM

**Comment by leeoniya** [comment]
this is not a complete fix for #4469 without explicit x gutter size control.

**Pull request merged**
