### PR TITLE
Storybook: Fix broken stories

### LINKED ISSUE #22953: Storybook: Fix broken stories
- [x] PieChart
- [x] Select generateOptions
- [x] ThresholdsEditor

### PR DESCRIPTION
**Pull request by tskarhed**
Fixes #22953
#22958

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]
Looks good!

**Comment by tskarhed** [comment]
Might also fix some the other broken stories in the PR too.

**Comment by Clarity-89** [comment]
Not broken, but I noticed `TagInput` story also uses the old story format.

**Comment by tskarhed** [comment]
@Clarity-89 Yeah, there are a couple of them, but I guess we'll fix them along the way.

**Review by Clarity-89 — APPROVED** [review]

**Pull request merged**
