### PR TITLE
CUE: Add `cue fmt` to pre-commit hook

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR is responsible for adding CUE formatting to pre-commit hook.

**Which issue(s) this PR fixes**:

Resolves task in epic #33139

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by sdboyer** [comment]
Just realized that i'm concerned this will make committing fail for anyone who doesn't have the `cue` binary installed. We've avoided making it a develoment-time dependency so far, and if we can continue, that'd be good.

Is there a way we can make this work conditionally on the binary being present, but then check formatted-ness in CI? Or is that too much of a pain, and it's better to just bite the bullet and expect people to install CUE? If the latter is the case, docs will probably need updating

**Review by sdboyer — CHANGES_REQUESTED** [review]
Just realized that i'm concerned this will make committing fail for anyone who doesn't have the cue binary installed. We've avoided making it a develoment-time dependency so far, and if we can continue, that'd be good.

Is there a way we can make this work conditionally on the binary being present, but then check formatted-ness in CI? Or is that too much of a pain, and it's better to just bite the bullet and expect people to install CUE? If the latter is the case, docs will probably need updating

**Comment by marefr** [comment]
> Just realized that i'm concerned this will make committing fail for anyone who doesn't have the cue binary installed.

Only if you make any change to .cue files that is. If you do that think we can require everyone to have the cue binary installed?

**Pull request closed without merging**
