### PR TITLE
(prometheus) support new legend format (with backward compatibility)

### PR DESCRIPTION
**Pull request by mtanda**
In this line, replace "{{job}}" to {{labels.job}}". (this is bad implementation, sorry)
https://github.com/grafana/grafana/compare/master...mtanda:prometheus_legend_format_improve?expand=1#diff-a59431ca1f1f94cdb3ae176c50a585b2R267

### CODE REVIEW

**Comment by torkelo** [comment]
what's the point of this, can't understand how this solves https://github.com/grafana/grafana/pull/5096

**Comment by mtanda** [comment]
Sorry the problem fix by this PR, is https://github.com/grafana/grafana/issues/3545#issuecomment-189526119 .
Without "options.variable" setting, the legend format rendering doesn't work correctly.
> That sounds like a problem when random JS vars collide with Prometheus label names.

To fix the problem, need to specify "options.variable", but it cause another backward compatibility problem.
This PR try to fix both problems.

**Comment by torkelo** [comment]
is it no easier to change from underscore template and just use a regex replace?

**Comment by mtanda** [comment]
not sure if user already use underscore template specific feature.

**Comment by torkelo** [comment]
well that is not documented so should be fine I think. And its a big security issue any that should be fixed (dashboards that contain js code)

**Comment by mtanda** [comment]
Yes, I'm worried about security issue recently too.
Okay, I'll change to use regex replace like this https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.js#L324-L329 .

**Comment by grobie** [comment]
Please make sure that whitespace around label names are option. E.g. `{{foo}}` and `{{ foo }}` should all work.

I'm pretty sure quite a few people are using javascript already, so it'll break some dashboards. I agree that it doesn't make sense to allow arbitrary js code execution, but #3545 becomes an even bigger issue now.

**Comment by mtanda** [comment]
Would you tell me the usecase of js code execution if you know.

**Comment by grobie** [comment]
We don't use it at soundcloud, but I've been asked a few times about support for promdash like filters as desribed in #3545. Providing a regex function/filter should cover the majority of use cases I believe.

**Comment by mtanda** [comment]
Thanks for answer.
Now, support legend format like ```{{ foo }}```.

I don't include regex function in this PR. So, this PR is ready to merge.

**Pull request merged**
