### PR TITLE
Fix change admin password after first login

### LINKED ISSUE #11882: Change admin password view after first login
This will be a second step the first time a user logs in to Grafana.
After logging in the user will come to a second view and be instructed to change password. 

newuserchangepassword_v3part1

### PR DESCRIPTION
**Pull request by Ijin08**
added view to change password
added transitions between views
added function to change password

fixes #11882

### CODE REVIEW

**Review by daniellee — DISMISSED** [review]
Change password form should be submitted when pressing enter.

The user cannot change a password if ldap is enabled. Maybe we have to make a change in the backend to allow the admin password to be changed even if ldap is enabled.

**Review by marefr — CHANGES_REQUESTED** [review]
Need to check if ldap/auth proxy is enabled and in that case not render the change password view.

These settings are already available client side and are named:
*authProxyEnabled* and *ldapEnabled*. Example of usage [here](https://github.com/grafana/grafana/blob/master/public/app/features/org/change_password_ctrl.ts#L8-L9)

**Review by marefr — CHANGES_REQUESTED** [review]
Shouldn't be able to change password if authproxy enabled.

Change password with different password in field result in javascript error:
image

**Review by marefr — APPROVED** [review]
Great :+1:

**Pull request merged**
