### PR TITLE
Update alerting_provisioning.md

### PR DESCRIPTION
**Pull request by espyra88**
In order to help users, i provide a quick and easy to use template, to create alert-rules!

**What is this feature?**

This is a doc contribution to help user to easily create alert-rules through api. I had a lot of issues before finally complete this working template. Caring is sharing!

**Why do we need this feature?**

Absolutely no ready-to-use/helping template on the net, nor the documentation. 

**Who is this feature for?**

Every users using API call to create alert-rules

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ X] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [W ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Eve832** [comment]
@brendamuir can you please route this to the right set of eyes? I shouldn't be a blocker, but I have no idea how to review this.

**Comment by brendamuir** [comment]
@JohnnyQQQQ could you review this? and lmk if we should backport..thank you!

**Comment by brendamuir** [comment]
@yuri-tceretian @alexweav can you review for me please? thanks!

**Comment by brendamuir** [comment]
Hi there-thanks for the contribution. We think it's great - but would belong better in this doc: https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/.  Could you add it here under point 2: Use the Alerting Provisioning HTTP API. Reason is the text in the other doc is generated from swagger, so your template would get deleted in the next round of codegen. Thanks!!

**Comment by espyra88** [comment]
https://github.com/grafana/grafana/pull/81937

i add some issues trying to edit patch-2, so to be as clean as possible i did a new pull request and il will let you close this one. i'm sorry about this.

**Pull request closed without merging**
