### PR TITLE
Postgres: Support Unix domain sockets with colons in path

### LINKED ISSUE #29680: Database: Using Unix socket for Postgres fails when path has non-port-separator colons
**What happened**:
When supplying environment variable GF_DATABASE_HOST as /cloudsql/some:connection:name for postgresql, the container is unable to start with the following errors:

```
net.SplitHostPort failed for '/cloudsql/some:connection:name
Invalid host specifier '/cloudsql/some:connection:name'
```

**What you expected to happen**:
I expected Grafana to accept unix socket as hostname for postgresql

**How to reproduce it (as minimally and precisely as possible)**:
Using Cloud Run, with latest image from grafana. Supply postgresql database configuration, with unix socket in GF_DATABASE_HOST(make sure the socket path has multiple colons, f.ex. /cloudsql/some:connection:name).

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version: postgresql11, backend
- OS Grafana is installed on: ubuntu container image
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Postgres Unix domain socket paths might have legitimate colons in them, so we can't just assume that they're port separators.

I think before finalizing this PR we might have to implement colon escaping with backslashes, so colon can still be used as a port separator with Unix sockets.

- [x] Add test
- [x] Support port specifier (protect colons in path with backslashes?)

**Which issue(s) this PR fixes**:

Fixes #29680.

### CODE REVIEW

**Review by ying-jeanne — APPROVED** [review]

**Comment by ying-jeanne** [comment]
@aknuds1 Arve I just add 3 unit test + specified port logic, pls take a look and let me know.

**Comment by aknuds1** [comment]
Having a look @ying-jeanne, thanks.

**Comment by aknuds1** [comment]
Pushed some language fixes plus changing tests to use standard library instead of goconvey.

**Comment by gfrankliu** [comment]
What about using database.url configuration? Will something like below work?

```
[database]
url = postgres:///db_name?host=/cloudsql/project:region:cloudsql_db&user=db_user&password=db_pass
```

**Comment by mpomarole** [comment]
Is this merged yet? I am trying to run grafana on Google Run with a host like `/cloudsql/project:us-central1:db`

**Comment by mgreenw** [comment]
Would love for this to be merged

**Comment by laetho** [comment]
Would also love for this to be merged/supported.

**Comment by smipi1** [comment]
Would love to see this merged as well

**Pull request closed without merging**
