### PR TITLE
WIP: Merge dataframes

### PR DESCRIPTION
**Pull request by torkelo**
In order to change Explore to use DataFrame and the new table component, we need it to use the DataFrame model. 

So we need to support merging (joining) many dataframes into one. 
This PR needs to match the logic for the current mergeTablesIntoModel function defined here:
https://github.com/grafana/grafana/blob/master/public/app/core/table_model.ts#L90

Joining the fields on name was super easy, how to match up the values / "rows", in a performance way will be a bit tricky. 

@ryantxu have you thought about a good way to do that? 

Example

DataFrame A

| Server  | DataCenter |
| ------------- | ------------- |
| A  | EU  |
| B | US  |

DataFrame B

| Status  | DataCenter |
| ------------- | ------------- |
| High  | EU |  
| Low | US |

DataFrame Joined

| Server  | DataCenter | Status |
| ------------- | ------------- | ------------- |
| A | EU  | | 
| B | US  | | 
|  | EU  | High | 
|  | US  | Low |

### CODE REVIEW

**Comment by ryantxu** [comment]
For JOIN -- I think the field name is one of the arguments.  In the existing table it can only do 'time;

Joining by time is a little more complicated (and maybe with any ordered number?) because we the exact values may not line up, and we could/should interleave the results

**Comment by torkelo** [comment]
yes, this is more like a merge

**Comment by torkelo** [comment]
@ryantxu merging dataframes looks very complicated. We did some pair programming but got stuck, so we opted to use the old mergeTables code and migrate data frame -> table -> merge -> back to dataframe in order to merge new table component. 

Regarding working with data frames, we found this. Looks interesting, looks like it has some stuff we can copy / be inspired by
https://github.com/data-forge/data-forge-ts/blob/master/src/lib/dataframe.ts#L3165

**Comment by jjmaestro** [comment]
Just an idea, instead of re-implementing or copy-inspiring, have you thought of using [Zebras](https://zebrasjs.com)? :-?

From their own website,
> Zebras is a data manipulation and analysis library written in JavaScript offering the convenience of pandas or R.

Such a library already provides functions such as [`merge`](https://zebrasjs.com/Z.html#.merge) and [`concat`](https://zebrasjs.com/Z.html#.concat) plus other useful functionality.

Also, it would be awesome if the dataframe implementation was "standard" (e.g. Pandas in the backend and Zebras in the frontend). It could open the door to easier integrations with data science tools such as notebooks.

**Pull request closed without merging**
