### PR TITLE
Graph: On over highlight series

### PR DESCRIPTION
**Pull request by mtanda**
Another approach for https://github.com/grafana/grafana/pull/4417 .

### CODE REVIEW

**Comment by bergquist** [comment]
I love this PR. 

But changes in flot makes it very hard to merge..

**Comment by mtanda** [comment]
The plugin reuse "drawSeries" function to draw highlighted series.
I'm not sure how we can do same thing without modifying flot...

**Comment by bergquist** [comment]
I just love this feature so much. @torkelo I think we should merge this. What do you think? Since flot is not maintained anymore we might as well modify our version.

**Comment by torkelo** [comment]
Will take a look

**Comment by torkelo** [comment]
This needs to be rebased / remade, graph has changed some (moved to typescript and been refactored)

**Comment by mtanda** [comment]
If I remade this, is there any chance to review this?
"will take look" means you consider to merge this, if the code is good?

**Pull request closed without merging**
