### PR TITLE
Changed the table transformation to allow for removing certain columns

### PR DESCRIPTION
**Pull request by bmundt**
This is related to feature requests that multiple people have requested about customizing what columns are displayed in the table for the table panel. I have implemented a way to remove table columns from the display for the table transformation.

Related: [#3551](https://github.com/grafana/grafana/issues/3551)

### CODE REVIEW

**Comment by bmundt** [comment]
I'm going to put this in a new rp in a different branch

**Comment by Abhishekpan** [comment]
@bmundt I tested this on windows server .. its working fine .. thanks for this .. but can you please tell me how to apply the same fix on unix box ? because we cant create build on unix box due to access issue. If I transfer .js file from windows box to unix box is it work ? I tried this but its not working .. may be I copied wrong file here .. Need your help ..

**Comment by Abhishekpan** [comment]
@bmundt are you going to merge it ? its a very helpful feature.

**Comment by bmundt** [comment]
This pull request was made off of a fork that I have deleted, because of problems with cla assistant. I still have the code locally though, and will make a new pull request.

**Comment by Abhishekpan** [comment]
@bmundt I much appreciate your efforts... I really don't know how I would say thanks but yes "THANK YOU SO MUCH". One more question do you have any idea when it will be available through RPM? (because we are using RPM here).

**Comment by bmundt** [comment]
When, and if it gets merged is  not really up to me. It is up to those that have write access to the grafana repository. Also, if this does get merged it will likely not make it to the actual build until 4.0 .
However you can build your own rpm of grafana from source and use that for now. Also, it would probably help if you showed some support in the new pull request that I made, since this one is closed.

**Pull request closed without merging**
