### PR TITLE
Very alpha pie chart

### PR DESCRIPTION
**Pull request by torkelo**
Start of a pie chart panel. Very alpha state, few options etc. 

This is the same as PR https://github.com/grafana/grafana/pull/15511 with some minor changes, changed name of Pie Chart panel to Pie Chart v2 and used newly designed panel icon/logo so it's distinct from the current external pie chart. 

Thinking of merging this in this very early state (marked as alpha so will only be available to test for users who have enabled alpha panels). Think it could be useful to have this in master when we experiment with the new TableData unification and stats calculation. 

This is currently using this data model

```
export interface PieChartDataPoint {
  value: number;
  name: string;
  color: string;
}

export interface Props extends Themeable {
  datapoints: PieChartDataPoint[];
....
}
```

replace with DisplayValue[] ? 

thoughts @ryantxu ?

### CODE REVIEW

**Comment by ryantxu** [comment]
+1 for an early alpha commit.

In particular, the pie chart is an interesting place to test different stats options ().  The most obvious is percentage of total / time.

**Comment by ryantxu** [comment]
also... its exciting to see all the new panel types!

**Comment by ryantxu** [comment]
> replace with DisplayValue[] ?

For sure!  that was the point -- since almost every component needs this

but we can do that once it is in alpha

**Comment by torkelo** [comment]
Yea, with this new react architecture in place, and the visualization selection etc, I am more open to have more visualizations / panel types in core Grafana. 

btw, did you catch https://twitter.com/torkelo/status/1106838816772550656 ? still needs a lot more work but exciting.

**Comment by ryantxu** [comment]
looks great.  Super exciting that the changes coming are in visualisations, not just "now it works with react!" 😄

**Pull request merged**
