### PR TITLE
Chore: Remove `jwilder/Dockerize` leftovers

### PR DESCRIPTION
**Pull request by dsotirakis**
Backport of https://github.com/grafana/grafana/pull/39960

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Some conflicts to resolve

**Comment by malcolmholmes** [comment]
Has this branch already been upgraded to the correct build-image version?

**Comment by marefr** [comment]
Yes, via #39968 I believe

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
