### PR TITLE
(cloudwatch) multiple CloudWatch alarm annotation support

### PR DESCRIPTION
**Pull request by mtanda**
This is enhancement of CloudWatch alarm annotation.
Support to add multiple metric/dimension/... alarm annotation by one annotation setting.

For example, if user want to annotate all RDS alarm, user only need to specify region and namespace.
rds_annotation

User can filter alarm by prefix of action or alarm name.

### CODE REVIEW

**Comment by mtanda** [comment]
resolve conflict.

**Comment by torkelo** [comment]
Annotation code for cloudwatch is starting be very complex with multiple chains of requests to fetch alarms and alarm history. 

Is there any way we can simplify and refactor this code? Maybe move annoation query code to it's own class and seperate tests? Can we move some of the code in annotationsQuery to the backend?

**Comment by mtanda** [comment]
> Is there any way we can simplify and refactor this code? Maybe move annoation query code to it's own class and seperate tests? Can we move some of the code in annotationsQuery to the backend? 

I'll move annotation query code to another class.
Moving some of code to backend is hard, these code is very tight coupling.

**Comment by mtanda** [comment]
refactor code.

**Comment by mtanda** [comment]
broken again...
resolve conflict.

**Comment by mtanda** [comment]
When is this PR merged?

**Comment by mtanda** [comment]
@torkelo I already change the code as you told. Please update tag "changes needed" and if you have time check this code.

**Comment by mtanda** [comment]
Is there any schedule to merge this PR?

**Comment by bergquist** [comment]
@mtanda sorry for slow response. I will look at this tomorrow.

**Comment by mtanda** [comment]
Sorry, I understand you are very busy preparing next release.
This PR is ready to merge, if it is possible to include this in next release, I hope to merge this soon...

**Comment by bergquist** [comment]
:+1:

**Comment by mtanda** [comment]
Thanks so much!!

**Pull request merged**
