### PR TITLE
API and Inspector UI text edits

### PR DESCRIPTION
**Pull request by oddlittlebird**
A few minor UI text edits for the API keys and Inspector.

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]

**Comment by oddlittlebird** [comment]
@dsotirakis, could you check on why the build is failing?

**Comment by dsotirakis** [comment]
@oddlittlebird fixed (same as [this](https://github.com/grafana/grafana/pull/32455#issuecomment-809674245))

**Comment by oddlittlebird** [comment]
Darn it, thought I hadn't extended the line length anywhere. Thank you!

**Comment by oddlittlebird** [comment]
@dsotirakis, any idea why this is still failing?

**Review by dsotirakis — COMMENTED** [review]
Snapshot problem again - a really weird one though, as if it couldn't let me remove spaces or remove/add newlines. Was auto-linting 🤷 

Fixed!

**Pull request merged**
