### PR TITLE
TimePicker: TimeRangePicker tooltip visibility fix

### LINKED ISSUE #51037: TimePicker: The tooltip is always shown after selecting a quick time range. requiring a click to hide
Screenshot from 2022-06-17 15-04-31

Replicate
* Click time range picker
* Select a quick range
* See tooltip being shown 

Not sure when this started happening or why.

### PR DESCRIPTION
**Pull request by Seyaji**
**What this PR does / why we need it**:

Fixes #51037

https://user-images.githubusercontent.com/67058118/176217943-c8ac2870-df30-4610-9d89-5863a9ec9aaa.mov

After some investigation I decided to override the 'show' prop with new state variables in the TimeRangePicker: 
[tooltipVis, setTooltipVis]

It seems like the default 'show' state wasn't resetting properly and when you click out of the range options box it re-renders the ToolbarButton with the previous open state. 

Hope this is ok, happy if anyone has a better solution. 🙂

### CODE REVIEW

**Comment by oscarkilhed** [comment]
Hey! Thanks for your contribution! I think this solution is treating the symptom and not the problem. It also disables the feature where the tooltip is shown when using the keyboard to navigate to the time picker.

The problem here is that the `FocusScope` component on line [137 (in your branch)](https://github.com/grafana/grafana/pull/51511/files#diff-46f59683e9f02dfe23d8d036c745c44f0c1d3386dae55db799a7619da991c1eaR137) restores the focus to the `ToolBarButton` when the time picker is closed. When focus is set to the `ToolbarButton` the tooltip is shown.

**Comment by Seyaji** [comment]
@oscarkilhed Thanks for your comments! I agree the solution is not ideal, I was wondering exactly why it was happening and you have explained it well. I don't know too much about the `FocusScope` component, but I can investigate a solution that works with it. (unless you guys would like to fix this yourselves)

If the focus is somehow reset/changed on the close of the time picker modal then I'm wondering where the user would be as they are navigating with a keyboard. It seems like even though the tooltip is appearing after the close it's actually behaving correctly (from a keyboard standpoint) as the keyboard focus was returning to the last navigation point.

**Comment by oscarkilhed** [comment]
Yes, when navigating to the timepicker with a keyboard it is working as expected. But we also have to consider that a user might open the timepicker with the mouse and close it by hitting escape. There's no easy and perfect solution here I think.

The dashboard settings control has the same issue. If you click it and go back the tooltip is still visible. Ideally the solution should work for both.

**Comment by Seyaji** [comment]
Yeah, its a tricky one for sure

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/51836

**Comment by torkelo** [comment]
Closing this, simple fix here https://github.com/grafana/grafana/pull/51836

**Pull request closed without merging**
