### PR TITLE
Add oauth scopes verification

### PR DESCRIPTION
**Pull request by amenzhinsky**
https://github.com/grafana/grafana/issues/6809

### CODE REVIEW

**Comment by DanCech** [comment]
Looks good to me

**Comment by amenzhinsky** [comment]
Probably we could add some option like `enable_scopes_verification`

**Comment by torkelo** [comment]
It needs to be different depending on OAuth implementation as there appears to be no standard here, has github and Google both return scopes differently

**Comment by amenzhinsky** [comment]
@torkelo, yep I see you point, github uses [custom http headers](https://developer.github.com/v3/oauth/#scopes), unfortunately it's not adapter-agnostic feature.

**Comment by amenzhinsky** [comment]
We could add `VerifyScopes(accessToken string) error` to `social.SocialConnector` interface.
What's your take on that?

**Comment by torkelo** [comment]
that interface does not work for github and google auth, need to send in the whole context

**Comment by amenzhinsky** [comment]
Opened new PR #7430

**Pull request closed without merging**
