### PR TITLE
Traces: Align APM table names

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:

This PR ensures that all col values are ordered according to rate names order. We first query for the rate and order the first three columns based on that order. The remaining columns (errorRate and duration) must be ordered according to the first 3 columns. When querying for the errorRate and duration there is no guarantee that the results will come back in the same order as they did for the rate query.

### CODE REVIEW

**Comment by connorlindsey** [comment]
Might be missing something locally, but I'm missing the error and duration columns running this branch. 

Also could be good to add a test case for `getApmTable` that make sure the order is correct. 

Screen Shot 2022-07-21 at 8 37 16 AM

**Comment by joey-grafana** [comment]
> Might be missing something locally, but I'm missing the error and duration columns running this branch.
> 
> Also could be good to add a test case for `getApmTable` that make sure the order is correct.

Are you receiving any rate/duration data in the query response? Specifically are `errorRate` & `duration` populated above [this line](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L649)?

There is a test for [checking the order](https://github.com/grafana/grafana/pull/52591/commits/e7bad312213ef55027916e5aa3c55460c34f456e#diff-9c80e0527586d1d31ee03afc0cb2cd79e02bb52b1e9202a0bc129bc6ac8c89d7R525) currently, lmk if this is not what you were thinking :)

**Comment by connorlindsey** [comment]
They're empty although in the linked prometheus instance there is data for `traces_spanmetrics_calls_total`

**Comment by joey-grafana** [comment]
> They're empty although in the linked prometheus instance there is data for `traces_spanmetrics_calls_total`

If there is no data in the response then there will be none in the table. Perhaps there are no spans with an error `sum(rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR",span_name="HTTP GET"}[$__rate_interval]))`. Can you confirm that your network inspector is returning no data for second and third query that are run after pressing the run query button?

Screenshot 2022-07-22 at 11 41 25
Screenshot 2022-07-22 at 11 41 35


Can we also confirm it's caused by this PR by checking the table against main and seeing if all columns populate there? I'm also using one of the [latest tempo images](https://hub.docker.com/layers/tempo/grafana/tempo/main-aa19e23-arm64/images/sha256-2fca14e3893dc5874329d130a48dacc9c54b1b5692c7f97c68ac4804b76925de?context=explore) (but was using an older one up until today and it was fine).

**Comment by connorlindsey** [comment]
Yeah, you're right. The TNS demo sets status_code = 0 or 1 instead of 'STATUS_CODE_ERROR' so there's no data for the table. In that case, lgtm

**Review by connorlindsey — APPROVED** [review]

**Pull request merged**
