### PR TITLE
Graph: Make old graph panel thresholds work even if ngalert is enabled 

### LINKED ISSUE #38596: Graph(old): It no longer renders thresholds in 8.1+
Noticed on play site that the old graph is no longer showing any thresholds. 

* Example https://play.grafana.org/d/000000074/alerting?orgId=1&editPanel=4

### PR DESCRIPTION
**Pull request by domasx2**
**What this PR does / why we need it**:

With https://github.com/grafana/grafana/pull/33850 I mistakenly entirely disabled threshold visualization feature for graph panels. The intention was, if `ngalert` is enabled, to not show threshold for old panel alert which might still be on the panel model. Determining threshold value for any ng alert(s) connected to the panel is not implemented yet.

~~This PR undoes the change and insted does not set `panel.alert` if `ngalert` is enabled.~~

This PR makes sure `panel.alert` is ignored if `ngalert` is enabled.

However, I think there is a problem: it seems that panel alert threshold was persisted to `panel.thresholds`. So even if `panel.alert` is no longer there, the threshold is still shown. While initially this threshold kinda makes sense because panel alert was converted to ng alert which is still attached to the panel, it is no longer synchronized with any changes to the ngalert. I think this would be a source of confusion in the future. However if we delete or disable the threshold, user won't be able to edit thresholds manually.

Maybe ngalert migration should clear `panel.thresholds` for any panels that have a panel alert? If `ngalert` flag is unsert, I think `ThresholdMapper` would populate it again

@hugohaggmark  @torkelo  WDYT, how to proceed here?

**Which issue(s) this PR fixes**:

Fixes #38596

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hugohaggmark** [comment]
Maybe we should use DashboardMigrator for this? This is a bit out of my knowledge of dashboards, graph and thresholds so I'm not sure at all.

**Comment by domasx2** [comment]
Hm, now I'm thinking this PR solution isn't great either... If we remove alert from panel model and user saves it again, alert will be gone, right? Then if `ngalert` is unflipped, existing panel alert is lost

**Comment by domasx2** [comment]
> Maybe we should use DashboardMigrator for this? 

It runs every time right? Would have to remove thresholds only once to not kill those added by user later

**Comment by hugohaggmark** [comment]
> > Maybe we should use DashboardMigrator for this?
> 
> It runs every time right? Would have to remove thresholds only once to not kill those added by user later

Yes, but only upgrades once for each version

**Comment by domasx2** [comment]
> > > Maybe we should use DashboardMigrator for this?
> > 
> > 
> > It runs every time right? Would have to remove thresholds only once to not kill those added by user later
> 
> Yes, but only upgrades once for each version

Hm, we should do the migration when `ngalert` flag is flipped though...

I guess the key question is: once `ngalert` is flipped and panel alerts are migrated, should the threshold (previously copied from panel alert) remain on panel config and still be visible & user editable, or should it be deleted?
Consider that migrated alerts are now entirely separate from panels, and editing them will not update panel threshold, if any panel is linked. 

@torkelo  would appreciate any opinion :bow:

**Comment by davkal** [comment]
Let's not delete anything until we have a migration feature that won't deprive the user of the visible threshold. Note that this can also be shipped in a later release when thresholds can be dynamically drawn based on the rule, then we can remove the explicit threshold line based on some heuristic.

**Comment by domasx2** [comment]
> Let's not delete anything until we have a migration feature that won't deprive the user of the visible threshold. Note that this can also be shipped in a later release when thresholds can be dynamically drawn based on the rule, then we can remove the explicit threshold line based on some heuristic.

Then this PR is good to go I think. "legacy" alert thresholds will essentially become configured on the panels and remain for the time being

**Review by peterholmberg — APPROVED** [review]
Looks good to me. I agree with @davkal about leaving thresholds in place on the panel even though they can get outdated.

**Pull request merged**
