### PR TITLE
Docs: Add linking topic

### PR DESCRIPTION
**Pull request by oddlittlebird**
I used @marcusolsson's [blog past about linking](https://grafana.com/blog/2019/12/10/pro-tips-dashboard-navigation-using-links/) as a starting point and wrote an article describing how to create and use navigation links in Grafana.

**Which issue(s) this PR fixes**: Almost total lack of information about the linking features

**Special notes for your reviewer**: I have questions about a couple of options in the Dashboard links section. Please answer them.

Also, please let me know if there are examples or additional information that we could add to make this topic better.

### CODE REVIEW

**Review by daniellee — CHANGES_REQUESTED** [review]
Really clear and logical - mostly LGTM

Added a few comments for the `?What this do?` parts - hope that explains them and that you can find better words to explain them clearly.

**Review by daniellee — APPROVED** [review]
LGTM

**Comment by torkelo** [comment]
In the application we refer to this as Dashboard links not navigation links, should align this (in app or docs) 

Screen Shot 2020-04-27 at 09 46 10

**Comment by torkelo** [comment]
And this article is in the wrong location, should be under dashboard features, not directly under features.

**Comment by oddlittlebird** [comment]
If this was just about dashboard links, then I would agree with you. However, this topic discusses panel links and data links as well.

**Pull request merged**
