### PR TITLE
Devenv: Create new Elasticsearch dashboards for data in data source

### PR DESCRIPTION
**Pull request by ivanahuckova**
In this PR, we are:

- adding 2 new dashboards inspired by previous dashboards, adjusted to new `gdev-elasticsearch` data source
- adjusting data in `gdev-elasticsearch`
- creating temporary `migration` dashboard where we are comparing queries/results executed trough frontend and backend (using expressions). This will be used to ensure backward compatibility of migration and we can delete it after migration is completed. 

image
image
image

To test:
1. Run `make devenv sources=elastic`
2. Run `cd devenv` and then `./setup.sh` to create new dashboards
3. Don't forget to restart server `make run`
4. Go to Grafana, gdev dahshboards and find these 3

### CODE REVIEW

**Comment by ryantxu** [comment]
@slim-bean I think you are still running a cluster with this and periodically debugging our cluster with it.

If not we can remove it, but seems low risk to keep

**Comment by ivanahuckova** [comment]
Oh, I didn't realize anyone was using this. We can definitely keep the panels, if it is still used by anyone.

**Review by gabor — APPROVED** [review]
LGTM

**Comment by ivanahuckova** [comment]
I am going to merge this, but @slim-bean, @ryantxu let me know if I should bring these old ES dashboards back.

**Pull request merged**
