### PR TITLE
SMTP: Update email templates to include populated <title> tag

### PR DESCRIPTION
**Pull request by mmandrus**
**What is this feature?**

Updates email templates and parsing logic to ensure that the <title> tag is populated in the compiled emails. It also re-enables a previously skipped integration test and fixes it (presumably, it was disabled because it wasn't working at all, not because it was flaky).

It also creates a HiddenSubject template func and uses it for txt templates, to avoid repeating ourselves in the templates

**Why do we need this feature?**

We currently have an empty <title> tag in all of our emails. Populating this tag with a value is just good practice. 

**Special notes for your reviewer**:

I came across this while creating a new email template, and thought that having compiled templates with blank `<title>` tags was kind of odd. The options become leave it (perfectly fine, but it seems like a nice enhancement to change it), remove the title tags all together, or this option.

Enterprise PR https://github.com/grafana/grafana-enterprise/pull/4372

### CODE REVIEW

**Comment by mmandrus** [comment]
After further investigation, it looks like this has no practical use.

**Comment by gillesdemey** [comment]
I'm not sure if we want to also include the title in the `.txt` templates – I don't have a strong opinion here but repeating the title in the first sentence might be a bit weird?

**Review by gillesdemey — APPROVED** [review]
Works as intended! 👍 

As an aside, there's also a few templates in [the enterprise repository](https://github.com/grafana/grafana-enterprise/tree/main/src/emails) that we might want to update too.

**Comment by mmandrus** [comment]
> I'm not sure if we want to also include the title in the `.txt` templates – I don't have a strong opinion here but repeating the title in the first sentence might be a bit weird?

@gillesdemey this is a good point... I was thinking of just removing the extra title lines, but the subject isn't always a good substitute. For example, the welcome email has:

```
[[Subject .Subject .TemplateData "Welcome to Grafana"]]

Hi [[.Name]],
```

Here, having the Subject at all feels weird, and I would just want to keep the `Hi [[.Name]]`.

A few ideas:
1. I could add _yet another_ argument to the Subject func that takes in a bool to hide or show. Having to overload the helper that much might indicate it's a bad idea, though.
2. Create a new func definition for text templates that returns an empty string
3. have `subjectTemplateFunc` do different things depending on if it's html or txt
4. Close this PR, more trouble than it's worth and there is no use complicating this 😄 

What do you think?

**Comment by gillesdemey** [comment]
Could we have separate functions defined, like `Subject` and `HiddenSubject`? I think that would be

* Very clear what those are supposed to do
* Allow the most flexibility where to use them

**Review by gillesdemey — APPROVED** [review]
This is awesome – LGTM! 🚀

**Pull request merged**
