### PR TITLE
Encryption: Use secrets service

### PR DESCRIPTION
**Pull request by undef1nd**
**What this PR does / why we need it**:
Enables envelope encryption in Grafana.
Replaces EncryptionService usages with SecretsService introduced in https://github.com/grafana/grafana/pull/40331

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Design doc can be found in related enterprise issue.

### CODE REVIEW

**Review by sakjur — COMMENTED** [review]
🤔 I'm not sure we should use `sqlstore.InitTestDB(t)` for the datastore unless it's already initialized in the test already, wdyt?

**Review by joanlopez — COMMENTED** [review]
It generally looks good, great job!! 💪🏻 
There area only two things I think we need to consider before merging:
1. Finally decide if we should use the secrets service on the old alerting code base.
~~2. Consider @sakjur's comment. I added a question on that comment to take a decision all together and go ahead. It shouldn't be a big change but a repetitive and boring one.~~

Thanks!!

----

So, in relation with the first point, could someone from @grafana/alerting-squad bring some feedback, please? 🙏🏻 

@undef1nd and I agreed to do not introduce envelope encryption (i.e. secrets service) into the old alerting system because it's not trivial to make migration encrypt/decrypt secrets with envelope encryption. So, the idea is to only introduce it on the new alerting system. Therefore, as the secrets service is backward compatible with the old encryption, the new alerting system would work with old secrets and use envelope encryption for new secrets, and the old alerting system would remain untouched in that sense.

**Review by joanlopez — APPROVED** [review]
Looks good, but I'd prefer to wait for some else because we paired or discussed multiple parts of this pull requests, so would be much better to have an alien pair of eyes.

The only thing I'm wondering is whether we should document EncryptionService vs SecretsService usage somewhere (either on the type definition, implementation or usages).
What do you think? 🤔

**Review by papagian — APPROVED** [review]
LGTM; I've tested also the alerting migration and it works.

**Pull request merged**
