### PR TITLE
Slider: Adjusts input to enforce min/max values on blur

### PR DESCRIPTION
**Pull request by jewbetcha**
**What this PR does / why we need it**:
We've had a couple Synthetic Monitoring users reach out about undesirable behavior with the input on the `<Slider />` component. When entering custom values and the slider has a set `min/max`, on first keystroke the component thinks you're going above/below the allowed values and defaults to either `min` or `max` values.

See [editing probe frequency on our SM instance for an example](https://syntheticmonitoring.grafana.net/a/grafana-synthetic-monitoring-app/?page=checks&id=47). 

This PR changes the enforcing of min/max on input blur, so that users can enter values freely until leaving.

**Special notes for your reviewer**:
First time contributing to Grafana, let me know if I missed anything :)

### CODE REVIEW

**Review by ashharrison90 — COMMENTED** [review]
couple of minor comments

**Comment by jewbetcha** [comment]
@ashharrison90 👋 ok to merge this one?

**Review by ashharrison90 — APPROVED** [review]
apologies, didn't notice your changes. 😱 
lgtm 🙌 

idk whether you need someone from @grafana/plugins-platform to have a look, since technically i think they own the components in `@grafana/ui`

**Comment by jewbetcha** [comment]
sounds good, thank you!

**Review by mckn — APPROVED** [review]
LGTM! Great work. Thanks to @ashharrison90 for awesome feedback on this review.

**Pull request merged**
