### PR TITLE
Improves visibility of Tags within Dashboard Search

### LINKED ISSUE #22804: Number of Total Characters in Tags used for Dashboard
Good day,
total number of characters through all tags used for one dashboard is limited in the way that it creates undesired readability issues.

**What happened**:
there is no usable way to have a freedom of creating any number of tags for a dashboard.

**What you expected to happen**:
I expect to be able to create several tags with a combination of longer words (especially in German language words are combined together and create a longer character chain) and not to worry that within dashboard search area they will be all visible and the dashboard name would be readable.

**How to reproduce it (as minimally and precisely as possible)**:
Enter a long name for a dashboard (around 30 chars) and add 5-7 Tags to it averaging with about 10 chars each.
Screenshot 2020-03-16 at 13 06 38

**Expected Result**
Screenshot 2020-03-16 at 13 06 10

**Anything else we need to know?**:
These changes to code make it happen:
```
.search-item {
  align-items: center;
  height: auto;
  min-height: 37px;
  white-space: initial;
}

.search-item__tags {
  display: flex;
  flex: 1 1 auto;
  flex-wrap: wrap;
  justify-content: flex-end;
  margin-top: -2px;
}

.search-results-container .label-tag {
  margin-top: 2px;
}
```

**Environment**:
- Grafana version: 6.7.0-pre
- Data source type & version: Simple Streaming Example demo 
- OS Grafana is installed on: MAC OS
- User OS & Browser: Chrome, Firefox

### PR DESCRIPTION
**Pull request by MaximKipot**
**What this PR does / why we need it**:

As stated in the issue

**Which issue(s) this PR fixes**:

Fixes #22804

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aknuds1** [comment]
Could you please make the title more descriptive of what the PR does, instead of referring to an issue?

**Comment by aknuds1** [comment]
Try merging with latest master please, in order to fix build.

**Comment by MaximKipot** [comment]
> Try merging with latest master please, in order to fix build.

I tried, unfortunately, it did not bring anything

**Comment by aknuds1** [comment]
Very sorry, we have another issue with CircleCI that we're working to fix.

**Comment by MaximKipot** [comment]
Ok, got it, let me know if I need to do smth

**Comment by aknuds1** [comment]
Please merge with latest Grafana master, the build issues should be fixed.

**Comment by MaximKipot** [comment]
Updated, done.

**Review by torkelo — APPROVED** [review]
looks ok

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Comment by aknuds1** [comment]
Thanks for your contribution to Grafana!

**Pull request merged**
