### PR TITLE
Alerting: Rework template docs and add examples

### LINKED ISSUE #42896: Alerting: Add examples of using templating functions to docs
Existing documentation for templating functions do not provide any examples of usage. We should include an example for each function, including inputs and outputs, to help users better understand how to build templates for notifications.

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/template-data/#functions

### PR DESCRIPTION
**Pull request by davidmparrott**
**What this PR does / why we need it**:
Reworks docs that contained information about templating functions and adds examples for supported template functions

**Which issue(s) this PR fixes**:
Fixes #42896

**Special notes for your reviewer**:

### CODE REVIEW

**Review by santihernandezc — APPROVED** [review]
LG(reat)TM 👍 , very detailed!

**Comment by achatterjee-grafana** [comment]
Hi @grafana/alerting-squad, when we write end-user documentation, we must consider user goals and not just talk of implementation details. I can help you polish that critical aspect of documentation. 
Can I request you to not merge docs PRs unless I am on PTO? Thanks a lot.

**Comment by armandgrillet** [comment]
@achatterjee-grafana This makes sense, what is the best way to proceed now that the PR has been merged? Revert or improve on what has been written in that PR based on the docs team feedback?

**Comment by achatterjee-grafana** [comment]
> @achatterjee-grafana This makes sense, what is the best way to proceed now that the PR has been merged? Revert or improve on what has been written in that PR based on the docs team feedback?

We do not need to revert. @davidmparrott and I briefly chatted about the information architecture of the content in this case. And I can make updates when working on other improvements if needed. 

I was proposing a best practice for alerting docs, going forward. Thanks!

**Pull request merged**
