### PR TITLE
Vagrant file to simplify the setup process of a development environment

### PR DESCRIPTION
**Pull request by inbilla**
Pull request adding a vagrant file to grafana as described in the issue:
https://github.com/grafana/grafana/issues/7438

### CODE REVIEW

**Comment by bergquist** [comment]
I like the idea! But perhaps we can have this in a separate repo? Grafana/grafana-vagrant

**Comment by inbilla** [comment]
I'm just tweaking it a bit to get it working properly, there were a couple of bits not quite up to scratch. Update on the way..

@bergquist I'm not sure of the value of putting it in a different repository. But most of the value is achieved by it simply being available. So if it were referenced in the grafana/grafana/readme.md then at least people would be able to find it and use it with ease.

Though in reality - It is a single file in the repository (I could even move it somewhere else in the repository if you like - away from the root).
I've worked with other repo's that just have the dev environment checked into the root as a vagrant file though. It's quite convenient!

**Comment by inbilla** [comment]
Anyway, I'm open to suggestions, I'm just keen for people to be able to benefit from it :)
In the meantime, I'll get on with trying to help by adding/tweaking the little things I want in grafana itself!

The latest version in this PR should do the trick

**Comment by jifwin** [comment]
How about adding go get grafana? It would be nice to have it already in place.

**Comment by inbilla** [comment]
It's actually already in place in this example. Because you checkout grafana from git in your host (I.e. windows). Then type vagrant up. Vagrant will map the vagrantfile's directory to the /vagrant folder. This is the grafana checkout. I've then symlinked that folder to the right place in the go workspace. This means you can use all the git and source editing tools of your normal environment.

**Comment by jifwin** [comment]
Ahh.. That makes sense. Thanks.

**Comment by inbilla** [comment]
@jifwin please try it out!
I tried to put some instructions in the vagrant file itself. I've also added a cheatsheet to the MOTD so when you login to the box through vagrant SSH it will give you a reminder of commands and locations of files.

**Comment by jifwin** [comment]
According to http://docs.grafana.org/project/building_from_source/ Grafana now needs Go 1.8.

**Comment by jifwin** [comment]
Also one more thing I would add to make it clear is to mention that this Vagrantfile must be cloned together with Grafana repo. I'm quite used to Vagrantfiles being independent of anything.

**Comment by torkelo** [comment]
thanks for contributing and wanting make Grafana better! 

The feature request (https://github.com/grafana/grafana/issues/7438) has not received any reactions/love/demand. 

Reluctant to merge this as non in the core team use vagrant

**Comment by inbilla** [comment]
No problem! I think it's discoverable here anyway. So if anyone else wants to look into it they can in future.

**Pull request closed without merging**
