### PR TITLE
Select: Support option groups in virtualised `Select`s

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- enables select option groups for virtualised `Select`s

**Why do we need this feature?**

- so people can use option groups in virtualised `Select`s

**Who is this feature for?**

- everyone!

**Which issue(s) does this PR fix?**:

For https://github.com/grafana/hyperion-planning/issues/33

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
@ashharrison90  - i've tested Select story and couldn't see any regressions. The thing I'm missing is the virtualised select with groups story.

**Comment by ashharrison90** [comment]
> @ashharrison90 - i've tested Select story and couldn't see any regressions. The thing I'm missing is the virtualised select with groups story.

yeah i was just using the normal groups story and adding `virtualized` to it. do you want me to add a separate story for that as well? 🤔

**Comment by dprokop** [comment]
I di the same, tho would be nice if that demo had maybe more options? It currently has just 9 or sth so hard to even tell if the virtualization kicks in, right?

**Review by joshhunt — APPROVED** [review]

**Review by dprokop — APPROVED** [review]
Works great

**Pull request merged**
