### PR TITLE
Chore: support clearing secureJson fields

### LINKED ISSUE #22552: Empty SecureJsonData values returning true in SecureJsonFields
When you reset or empty a secret/key field and save. The field will be disabled as if there were a value saved. 
An empty string was posted and none is returned which means it understood that no secret was saved- however, the key's value in SecureJsonFields will be set to true.

I was able to produce this in both Azure Monitor and Cloudwatch with all key fields.

Screen Shot 2020-03-03 at 4 32 49 PM

Screen Shot 2020-03-03 at 4 33 04 PM

### PR DESCRIPTION
**Pull request by ryantxu**
Should fix #22552

🤕 despite all my efforts in this PR to remove fields... it seems to have zero effect.   help please!

Here are steps to reproduce:
https://github.com/grafana/grafana/issues/22552#issuecomment-606861180

### CODE REVIEW

**Comment by ryantxu** [comment]
@marefr @bergquist -- perhaps I just do not understand how this works!

**Comment by marefr** [comment]
Don't think key with empty value should be set in secureJsonData in frontend for this to work as expected. Haven't had time to verify with old Grafana version, but since I cannot find any changes in Grafana backend it must be a frontend behavior that changed.

**Comment by torkelo** [comment]
Looking at this, not sure how it ever worked (been going back to 5.x), even if the frontend would not set an empty value the backend would never clear any fields as it always copies existing secure fields if the frontend does not provide a value for it. The backend either needs to delete empty strings, or add secureJsonFields to the update command DTO and check if this is false then delete the field.

**Comment by marefr** [comment]
@torkelo seems you're right. Tested with v4.6.4 as well and same behavior there. Earlier on think we've had a enable/disable checkbox with additional text input fields, for example for tls certs so if not enabled the value of text input fields is not used. Different with azure for example which only have a text input field

**Comment by bergquist** [comment]
Closing this for now. Might come back to this later :)

**Comment by gw0** [comment]
If I understand correctly the blocker for this PR is that a key with an empty value should not be used for removing? What about using `null` values that are supported by JSON as a marker for this.

To me it seems that this encryption fields are not implemented correctly and this is the reason why there are so many issues related to that. An alternative could be an option to disable encryption or a Grafana CLI command to migrate back to unencrypted fields.

**Pull request closed without merging**
