### PR TITLE
Dashboard: Add guidance about reload required after updating shared cursor/tooltip setting.

### PR DESCRIPTION
**Pull request by Bostwickenator**
This PR adds the user guidance from @zoltanbedi on #46581. This is a work around to address the updating shared cursor/tooltip setting issue by asking users to reload the page. Language of user prompt used is copied from the existing "Read-only" control for consistency. 

Relates to #46581

**Special notes for your reviewer**:
I'm not sure if there is snapshot test coverage for the text here. I can't see any but happy to update it if needed.

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Hey @Bostwickenator,
Thanks for creating this pr. There is no need to update any snapshot test. This is good as it is. In order to merge this we need you to sign the cla. At the same time I think the best way would be to fix this error. Maybe add a todo comment above that says that remove that line once the issue is fixed? What do you think?

**Review by zoltanbedi — APPROVED** [review]
Thanks @Bostwickenator. Looks like the prettier check is failing. Please run `yarn lint:fix`

**Comment by zoltanbedi** [comment]
Is it ready to merge now? I'm only asking because it is still in draft @Bostwickenator

**Comment by Bostwickenator** [comment]
Ready from my perspective. Sorry for the high number of touches needed on your end. I appreciate the guidance.

**Comment by zoltanbedi** [comment]
No worries. Thanks for creating this pr! @Bostwickenator

**Pull request merged**
