### PR TITLE
fix(alerting): fixed evaluation for no_value condition, fixes #7244

### LINKED ISSUE #7244: [Bug] Alerting HAS NO VALUE is not working
- What Grafana version are you using?
4.1.1 (same behavior with 4.0.2)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.n
- What did you do?
Created a new dashboard
Created a new graph panel in new dashboard
Created a graphite target query that returned all null values
Created an alert with when sum() of ... "HAS NO VALUE"
Set the "If no data or all values are null" state to "alerting" in the alert
Clicked "Test Rule"
- What was the expected result?
The alert should fire since all values are nulls
- What happened instead?
The alert did not fire during testing (firing:false), it did however work as expected when the dashboard was saved (i.e. it went into "firing" state)

screen shot 2017-01-12 at 1 26 28 pm

### PR DESCRIPTION
**Pull request by torkelo**
removed the continue from the query condition loop. 

@bergquist can you take a look? What implications does this have?

### CODE REVIEW

**Review by bergquist — APPROVED** [review]
Looks good. 

Not sure what the intention was for the `continue` statement but I cant find any reason to keep it. I suspect it was not removed during the latest condition refactoring. 

Feel free to merge :)

**Review by bergquist — CHANGES_REQUESTED** [review]
blank

**Comment by torkelo** [comment]
> EvalMatch should use nullable float64

Not sure I understand, it is using that. what did I miss

**Comment by bergquist** [comment]
@torkelo sorry. That was a dummie message. Just wanted to see if I could update my review status.

**Review by bergquist — APPROVED** [review]

**Pull request merged**
