### PR TITLE
fix shortcode usage

### PR DESCRIPTION
**Pull request by robbymilo**
fixes needed for https://github.com/grafana/website/issues/14172, https://github.com/grafana/website/pull/14175

### CODE REVIEW

**Review by jdbaldry — APPROVED** [review]
Thanks for fixing this.

I checked it locally with `make docs` and it LGTM.

**Comment by jdbaldry** [comment]
Might need backporting to more branches?

**Comment by jdbaldry** [comment]
I think only `v10.0.x` is needed. I don't see the file in `v9.5.x`.

**Comment by robbymilo** [comment]
Thanks, if you have merge ability, please merge @jdbaldry.

**Pull request merged**
