### PR TITLE
Alerting: Support Prometheus durations in Provisioning API

### LINKED ISSUE #58117: Alerting: Provisioning API does not support all time durations
**What happened**:

Grafana supports `For` durations that have `d` units.

Screenshot 2022-11-03 at 09 22 00

However, the Provisioning API requires that the `For` duration is compatible with Go `time.ParseDuration` which supports `s`, `m` and `h` units.

```
func (a *ProvisionedAlertRule) UpstreamModel() (models.AlertRule, error) {
	forDur, err := time.ParseDuration(a.For.String())
	if err != nil {
		return models.AlertRule{}, err
	}
	....
}
```

**What you expected to happen**:

We should support the same units in the Provisioning API as we do via the UI.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by bartpeeters**
Make provisioning API support durations containing 'd' by using prometheus Duration instead of time Duration.

Fixes #58117

Not sure if we need a test to check it works with 'd' in duration and if so where I should write this test.

### CODE REVIEW

**Review by JohnnyQQQQ — CHANGES_REQUESTED** [review]
Thanks for your contribution. Unfortunately, we have to change a few things. 

The model in the `models` package shouldn't change. Only the parsing in the provisioning needs to be changed (using the Prometheus duration model) and the API model in the provisioning API must be changed and mapped.

**Comment by bartpeeters** [comment]
@JohnnyQQQQ Thanks for your feedback.

I updated the PR, not sure if I'm on the right track now.

**Comment by JohnnyQQQQ** [comment]
> @JohnnyQQQQ Thanks for your feedback.
> 
> I updated the PR, not sure if I'm on the right track now.

Thanks for addressing the feedback. That looks perfect! Can we perhaps add a test for this (unit test should be enough) to ensure we don't regress anytime soon?

**Comment by bartpeeters** [comment]
Added unit tests for durations with 'd'.

Are these OK?

**Comment by JohnnyQQQQ** [comment]
Sorry, I am at a conference this week, so I don't check-in in GitHub often. LGTM!

**Review by JohnnyQQQQ — APPROVED** [review]

**Review by grobinson-grafana — APPROVED** [review]

**Pull request merged**
