### PR TITLE
Filter field by values transformer

### PR DESCRIPTION
**Pull request by oscarkilhed**
**What is this feature?**

Adds a transformation for filtering fields where all values match a value matcher.

**Why do we need this feature?**

Users want to be able to filter series that only have null or 0 values.

**Which issue(s) does this PR fix?**:

https://github.com/grafana/grafana/discussions/38299

Todo:
- [ ] clean up
- [ ] naming
- [ ] ui to add transformation

The implementation is naive in terms of performance, could possibly be sped up by bisecting the values vector since strings of non null/zero values will likely occur.

### CODE REVIEW

**Comment by leeoniya** [comment]
we discussed this over slack yesterday.

i think internally we should add a few special-case filtering funcs for these to keep things fast (without relying on a hot `valueMatcher()` loop):

`0`
`1`
`null`
`Infinity`
`-Infinity`
`NaN`
`true`
`false`
`''`

we should also add a toggle to either fully remove the field, or dynamically set its `hideFrom` settings, since maintaining the full field list in the legend and tooltip is useful even if we hide them in the viz dynamically based on values.

**Comment by dumistoklus** [comment]
Any news here?

**Comment by leeoniya** [comment]
still aiming to get this into 9.3.0. will have some updates in next couple days.

**Comment by leeoniya** [comment]
re-targeting for 9.4.0, but may land sooner in 9.3.x.

discovered some inconsistencies with how different panels treat `hideFrom`: viz/tooltip/legend combos, so we'll want to fix that before proceeding here.

**Comment by fmad** [comment]
After trying, in vain, for several hours, to find out how to do this, I've landed in this "feature request". I'm surprised that something useful like this was removed! We'd like to implement some charts for metrics that are, for the most part, empty for several hundred of pods, but we'd like to see those w/ non-zero values... Having 200+ values in a chart when we may only need to see 10, at most, is just not useful...
What was the last version of Grafana where we could do this, as I'm seriously considering downgrading at this stage?

**Comment by BenoitPoulet** [comment]
@fmad In our case we stay in 8.5.3 for this feature.

**Comment by prwood** [comment]
Just wanted to ping and say that this is still a feature that I'm hoping will come back. My main use case is for graphs where I am selecting on a wildcard that includes a large set of deprecated and inactive metrics, and I'd rather just have Grafana hide all metrics that are only zero or null, rather than having to manually select only the active metrics.

**Comment by max-matiukhin** [comment]
+1 for this feature.
I also was googling it and just found this feature request

**Comment by leeoniya** [comment]
@oscarkilhed thanks for your work on this!

after some further investigation we've decided to take a different approach that will hopefully be more powerful: https://github.com/grafana/grafana/pull/64477

**Pull request closed without merging**
