### PR TITLE
Dashboards: Check if Grafana Javascript agent is enabled before using faro.api

### PR DESCRIPTION
**Pull request by tokoro10g**
The `grafanaJavascriptAgent.enabled` configuration must be `true` to use faro.
This PR fixes the issue.

### CODE REVIEW

**Comment by tokoro10g** [comment]
@bfmatei @Sergej-Vlasov Let me know if any clarification is needed. Thanks!

**Review by mdvictor — APPROVED** [review]

**Comment by mdvictor** [comment]
Hey @tokoro10g. Thank you for opening this PR, this is great! It's approved and ready to go!

**Comment by tokoro10g** [comment]
@mdvictor Thanks! I merged the main branch again to rerun the test that was failing due to other PRs. Could you approve running the workflow?

**Comment by mdvictor** [comment]
@tokoro10g merged, thank you for your contribution!

**Pull request merged**
