### PR TITLE
Fixed intervalFormat for Graphite Alerting

### LINKED ISSUE #6423: [Bug Alerting Graphite]: Transform time intervals to graphite time intervals in query (5m -> 5min)
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Master branch
- What datasource are you using? Graphite
- What OS are you running grafana on? MacOS
- What did you do? I wrote a Graphite query with "hitCount" function and created an alert for it.
- What was the expected result? "Test Rule" should have resulted in true/false depending on the result of the alerting result handler.
- What happened instead? 500 Internal Server Error from Graphite.

The catch is that the metric (containing "hitcount" function) is giving the correct datapoints back to the graph and datapoints are plotted on the graph without any issues . But when alert is test for the same query, it results in "500 Internal Server Error". Looks like Graphite alert checks are missing something.

### PR DESCRIPTION
**Pull request by utkarshcmu**
Resolves #6423

### CODE REVIEW

**Comment by utkarshcmu** [comment]
This regex matching in Golang was kind of complex and not straightforward as javascript. Please modify if you a have a better way to transform and review/merge. Thanks!

**Comment by bergquist** [comment]
Some unit tests for this would be great :)

**Comment by utkarshcmu** [comment]
Added tests, please review/merge!

**Comment by bergquist** [comment]
Gah... I really wish github would allow med to commit to your PR :)

This test does not pass
```
Convey("should not override query", func() {
			timeRange := formatTimeRange("app.grafana.*.dashboards.views.1M.count")
			So(timeRange, ShouldEqual, "app.grafana.*.dashboards.views.1M.count")
		})
```

**Comment by utkarshcmu** [comment]
No worries, I will test this case and re-push.

**Comment by utkarshcmu** [comment]
I am not sure whats wrong in the function as my go playground spits outs the correct output but go tests fail :(

https://play.golang.org/p/El6gby13yZ

**Comment by utkarshcmu** [comment]
@bergquist When I add the test which you suggested above to graphite_test.go, go tests fail. But when I verify the code on this line (https://github.com/grafana/grafana/pull/6446/files#diff-032b3ce7e377dc58eb70d2fd238250b5R166) for different queries, the code works. I am not sure why go tests are failing.

**Comment by utkarshcmu** [comment]
Here is the go playground code which is used in the function as it is: https://play.golang.org/p/av9MR2v8y1

**Comment by bergquist** [comment]
@utkarshcmu Strange... I dont understand why :confused:

**Comment by utkarshcmu** [comment]
@bergquist I have added the tests to graphite_test.go file and commented them for now so that we do not forget that we need to fix the failing tests. At least the Graphite alerting bug should be fixed if we merge this PR and we can always come back and try to fix the two failing tests. What do you think?

**Comment by utkarshcmu** [comment]
I was able to fix the failing tests. The problem was that I was using the wrong function name. :|

**Comment by bergquist** [comment]
Great! :bomb:

**Pull request merged**
