### PR TITLE
prometheus nested query support

### PR DESCRIPTION
**Pull request by mtanda**
https://github.com/grafana/grafana/issues/8791

### CODE REVIEW

**Comment by bergquist** [comment]
This needs some tests before we merge it. I guess it would make sense to extract it to a new function for that purpose.

**Review by bergquist — CHANGES_REQUESTED** [review]
This needs some tests before we merge it. I guess it would make sense to extract it to a new function for that purpose.

**Comment by mtanda** [comment]
@bergquist Add test. Please check.

**Review by bergquist — APPROVED** [review]

**Comment by bergquist** [comment]
Merged this too early... 
We also need support for this in the backend to support alerting on nested queries.

**Pull request merged**
