### PR TITLE
Adding option to disable sticky headers on table panels

### PR DESCRIPTION
**Pull request by jonstout**
This change introduces the 'Sticky header' option to the table panel
plugin. This option toggles the position attribute on the table header
elements' div between absolute and relative. This change is backwards
compatible with the existing table panel plugin and defaults to the
pre-existing behavior.

The effect of this change allows the user to specify if the table's
header should stay in a fixed location as the user scrolls, or scroll
away with the adjacent rows.

This also resolves a display issue encountered when a table contains a
large number of columns. When a large number of columns exist, the
absolute positioning of the table header cells force the header cells'
content to be rendered over each other. Toggling to to relative
positioning allows the header cells' content to render as normally
expected.

### CODE REVIEW

**Comment by jonstout** [comment]
fixes #11043

**Review by Ijin08 — CHANGES_REQUESTED** [review]
Hi,

Looks good and I agree with that there is an issue with the header when there are many columns but I will let @daniellee decide if this is a feature we need. 

If so here are some things that needs to be fixed:
When I uncheck Sticky header the table header background lies above the table header which looks a bit strange. The background becomes a thick border that takes up space and has fixed position. 

tablereview1

So it would be good if the table-bg div is hidden and the header row gets the background-color. Like this:
tablereview2

**Comment by jonstout** [comment]
@Ijin08 I've made some css modifications to address your request.

**Comment by IntegersOfK** [comment]
Does this address #4157? I'd really like to have long table headers without them going off the page, can we get this merged?

**Comment by torkelo** [comment]
Closing this, think this will be solved or improved by the new react panel we are working on, it will have both vertical and horizontal scroll (when you have many columns).

https://github.com/grafana/grafana/pull/15842

**Comment by busi91** [comment]
Hi @jonstout, 
I have modified the files but nothing has changed (if I inspect the web page there aren't changes). 
How can I apply the changes?
I'm running Grafana 5.4 in docker version.

**Pull request closed without merging**
