### PR TITLE
Postgres/MySQL/MSSQL: Do not  show field name prefix for fields with labels 

### LINKED ISSUE #35390: Grafana 8.0 incorrectly adding prefix label to grouped data
**What happened**:
Updated to Grafana 8.0. I'm noticing all of my plots are adding as a prefix the variable name used. If a function is used (i.e. `COUNT()`, the function would be prefixed

**What you expected to happen**:
- Plot legend to display as expected

**How to reproduce it (as minimally and precisely as possible)**:
- Upgrade to Grafana 8.0
- Create a timeseries or  plot using psql

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.0 (41f0542c1e)
- Data source type & version: PSQL 10
- OS Grafana is installed on: Linux
- User OS & Browser: OSX, Chrome
- Grafana plugins: None
- Others:
image

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #35390 (partially)

The new postgres/sql data source backend return series name in a field label, this is big change compared to v7.5 as it then makes use of Grafana's automatic field naming for field and field labels.

But postgres queries (old and new) does not follow the standard time series field naming convention of naming value field as `Value` (capital V), field names named `Value` are handled
a bit differently in the field naming logic. I changed this to have same behavior now for `value` but I am afraid this will not solve all use scenarios. I can see that other field
value names migth also cause issues with this change.

Not sure what the solution is, it's not trivial to know if field name should be used in field name or just labels.

### CODE REVIEW

**Comment by ryantxu** [comment]
I am a bit nervous about this -- but not sure what the best solution is.  This looks like it expands the "magic" (VERY hard to explain) naming strategies when the field is named "value" in addition to "Value"

Could we get acceptable behavior by just removing the field name in SQL when it equals "value"?

That would be a backend change that affects only SQL datasources rather than expanding the magic naming strategy

**Comment by marefr** [comment]
Trying to understand the implications of this bug/fix. If we would change fields named `value` to `Value` in sql backend we're all good?

**Comment by marefr** [comment]
To me it would make sense any combination of lower/upper case of time, value and metric (for time-series) would be allowed. But I'm probably not aware of potential problems allowing this.

**Comment by torkelo** [comment]
@marefr @ryantxu I think I have an ok solution, improving the frontend naming logic. So instead of checking of field !== Value to know if the we should add the field name I check if there exists other field names. So if there is time, count, count  fields or time, value, value  fields the field name will not be added. I have to have a special condition for the time field and exclude that when checking for other field names, but since time fields never have labels that field name is added anyway later. This is only for the condition of if Grafana should add the field name before the labels. And so the logic now is to only do that if there exists other field names (that is not the time field) .

**Comment by torkelo** [comment]
New logic: "If the field name is Value or the field has labels skip the field name"  

Question is will we regret adding this logic?  (The new logic being skip adding field names if the field has label keys)

**Comment by torkelo** [comment]
@marefr it's not only about upper or lowercase the field name can be anything (set in SQL query). I really unsure how we should fix this, change so that Labels are not set in SQL time series to wide? just use field name instead? Or change the logic for how we show field names (ignore field name if there are labels), very unsure if that will bite us in the future

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/91de51771c79f4f38ddd14a51baeae72140ec828/pkg/tsdb/sqleng/sql_engine.go#L310

**Comment by marefr** [comment]
@torkelo haven't really looked into the details of this bug to understand it enough. Need to take it for a spin I think. The problem is that series names are constructed in the frontend based on field name and labels? Can we implement something in backend on field that says this is the series name - don't touch it?

**Comment by torkelo** [comment]
>  Can we implement something in backend on field that says this is the series name - don't touch it? 

Yes you can use the field name or move the label name to field config displayNameFromDS

**Comment by torkelo** [comment]
But hard to read the LongToWide code, not sure I understand it https://github.com/grafana/grafana-plugin-sdk-go/blob/72bea444e1f771be290f25c8f54d064bcaaf2630/data/time_series.go#L206

**Comment by torkelo** [comment]
"During conversion: String and bool Fields in the longFrame become Labels on the Fields of wideFrame. The name of each string or bool Field becomes a label key, and the values of that Field become label values" 

So not sure if we can change that

**Comment by marefr** [comment]
We're already doing some post-processing after the SDK has done it's thing: 
https://github.com/grafana/grafana/blob/8e827337ea79728914da8542f6ddcfc6cab3aa23/pkg/tsdb/sqleng/sql_engine.go#L309

So I guess we should be able to change things however we like

**Review by marefr — APPROVED** [review]
This works as expected when testing with Postgres, dashboard "Datasource tests - Postgres". Have randomly tested some other gdev dashboards and seems to work as expected :+1: I might miss something though

**Comment by torkelo** [comment]
Yes, this works and fixes the problem. But this changes the logic so that for fields with labels we will never show the field name just the labels. 
So a wide time series like this 
Time  |  Value (server=A) | Count = (Server=A) | Position (Server=B)  

Will always be shown as series
*  A
*  A
*  B 

As we will ignore the field name. There is a more advanced version we could use in a case like that if the field names are different then we prefix the labels with the field name

**Comment by torkelo** [comment]
@marefr closing this as it will break many other scenarios where data sources return fields with labels, https://github.com/grafana/grafana/pull/35839  looks much more promising

**Pull request closed without merging**
