### PR TITLE
Logs Panel: Add milliseconds to download file

### LINKED ISSUE #75035: Logs: Add millisecond to log downloads
love this change but is it possible to get this in the Download Logs as well?

_Originally posted by @michaelswierszcz in https://github.com/grafana/grafana/issues/64372#issuecomment-1723791282_
            

Follow up on functionality added in https://github.com/grafana/grafana/pull/64372,
`2023-09-18T12:56:02-05:00	ts=2023-09-18T17:56:02.535555875Z caller=manager.go:170 level=warn msg="ERROR"`
Should be
`2023-09-18T12:56:02.535-05:00	ts=2023-09-18T17:56:02.535555875Z caller=manager.go:170 level=warn msg="ERROR"`

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**
Adding milliseconds to (txt) log panel download feature.

**Why do we need this feature?**
Adds more precision to downloaded logs.

**Who is this feature for?**
Logs users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/75035

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
JSON already has the full ISO date string, so I don't think we'll want to add another time parameter to the JSON download.

**Comment by matyax** [comment]
Before: 2023-09-20T14:18:06+02:00	_entry="log text  [247036162]" counter=8283 float=64.477 wave=0.8090169943748909 label=val2 level=error

After: 2023-09-20 14:19:57.816	_entry="log text  [312142800]" counter=8462 float=45.362 wave=0.5877852522922484 label=val1 level=info

I'm unsure if we're missing important information by removing the TZ part. What do you think @grafana/observability-logs ?

**Review by matyax — APPROVED** [review]
From a logs perspective, LGTM!

**Comment by gtk-grafana** [comment]
@axelavargas @kaydelaney It looks like ya'll are the owners of the download code, does this look good to you?

**Review by axelavargas — APPROVED** [review]
Hey @gtk-grafana 👋🏾 , from the dashboard's point of view, It looks good :).

**Pull request merged**
