### PR TITLE
[v10.3.x] Docs:  Fixed a typo in the Azure config page

### PR DESCRIPTION
**Pull request by lwandz13**
Backport f727e2187362bb707fc23853f199446de759e6d6 from #84475

---

Andreas reached out in the Docs channel to point out typo - GitLab UI should be Grafana UI

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
It looks to me that this backport includes changes to docs that we might not necessarily want in these versions but I'm not best placed to say which bits should stay and go.

Do we need the new content?
The typo was introduced in a section (Configure Azure AD authentication client using the Grafana UI) that is brand new to this branch. Perhaps we can just close this backport?

If that documentation is useful to this version of Grafana, we should check the rest and make sure that bits like https://github.com/grafana/grafana/pull/84861/files#diff-bfa1b4cd0e2abcc4997b5443bbca3b62fdccf8fa51b1df6aa1f72a282e0d6e42R174-R176 are removed.

**Comment by lwandz13** [comment]
@aangelisc shoud dthe admonition be backported to Grafan 10.3?

**Comment by aangelisc** [comment]
Hey @lwandz13, I think this would be one for the @grafana/identity-access-team as (I think) they own the OAuth flows 😊

**Comment by mgyongyosi** [comment]
Hi @lwandz13, this shouldn't be backported to 10.3. These changes have been introduced in 10.4. I think we can close this PR.

**Comment by lwandz13** [comment]
> Hi @lwandz13, this shouldn't be backported to 10.3. These changes have been introduced in 10.4. I think we can close this PR.

Thanks Misi!  I'll delete this PR, but merge 10.4 PR.

**Comment by lwandz13** [comment]
Apologies, I should have checked more carefully on backporting this to 10.3

**Pull request closed without merging**
