### PR TITLE
Parse database host correctly when using IPv6

### PR DESCRIPTION
**Pull request by ellisvlad**
#13711

- Support for ipv6 parsing of host:port in database configuration for Postgres and Mssql

### CODE REVIEW

**Comment by bergquist** [comment]
Thank you for contributing to Grafana!

Could you please add a test for this?

**Comment by ellisvlad** [comment]
I've added some test cases and moved the Ip / Port string parser into it's own function in the util package, as net.SplitHostPort doesn't behave if the port is missing

**Review by marefr — APPROVED** [review]
Looking good!

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
