### PR TITLE
Docs: Add 7.5.0-beta1 release notes link

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Add link for release notes 7.5.0-beta to _index.md

### CODE REVIEW

**Review by oddlittlebird — APPROVED** [review]
LGTM

**Review by wbrowne — COMMENTED** [review]
We didn't do this for 7.4, but assuming this is alright considering the +1 @oddlittlebird?

**Comment by oddlittlebird** [comment]
@achatterjee-grafana, could you check on the 7.4 links?

**Comment by dsotirakis** [comment]
https://grafana.com/docs/grafana/latest/release-notes/ have a look, and please let us know if it's not needed :)

**Comment by oddlittlebird** [comment]
@dsotirakis, when the stable release is posted, we should update the beta link with the stable. I believe that's what happened last time.

**Comment by dsotirakis** [comment]
Great @oddlittlebird, I'll pin it for then

**Pull request merged**
