### PR TITLE
PluginExtensions: Add category to link extensions

### LINKED ISSUE #69291: Plugins: Introduce a category header for extensions in panel menu
## Description

Introduce a category header for the `Dashboard -> Panel -> Extensions` menu to improve the UI. It would remove the need of repetition since you can group menu items that belongs together. It would also make it more explicit from which plugin the extensions is added.

https://www.figma.com/file/1f91vXfh82kvrphRHloYPp/UIAudit_Designs?type=design&node-id=103-2405&t=PSz23O3RTUlgeeDD-0

### PR DESCRIPTION
**Pull request by mckn**
**What is this feature?**
To prevent extensions for repeating their origin as part of the title we have introduced the possibility to define a category that the extensions will be group below.

Before:
Screenshot 2023-07-21 at 14 05 43

After:
Screenshot 2023-07-21 at 13 32 31

**Why do we need this feature?**
It will improve the user experience and make it easier for the end user to find what they are looking for.

**Who is this feature for?**
plugin developers, end users

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/69291

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by mckn** [comment]
@sd2k maybe something we can use in ML?

**Comment by sd2k** [comment]
Yep this looks useful for ML! Should be backwards compatible too which is ace 🎉

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Comment by sd2k** [comment]
> Should be backwards compatible too which is ace 🎉

Hmm I'm not actually sure this is backwards compatible - if I add the `category` field to my extension link then they aren't shown in Grafana 10.0 😞 I guess there's something in Grafana's `getExtensionLinks` which checks for unknown properties? Not much that can be done about that now though, I'll just wait for this to be released before adding the category.

**Comment by sd2k** [comment]
The error I see in the logs is:

> [Plugin Extensions] Invalid extension "Create forecast". Trying to override not-allowed properties: category

**Comment by mckn** [comment]
> > Should be backwards compatible too which is ace 🎉
> 
> Hmm I'm not actually sure this is true (in some senses) - if I add the `category` field to my extension link then they aren't shown in Grafana 10.0 😞 I guess there's something in Grafana's `getExtensionLinks` which checks for unknown properties? Not much that can be done about that now though, I'll just wait for this to be released before adding the category.
> 
> Edit:
> 
> FYI the error I see in the logs is:
> 
> > [Plugin Extensions] Invalid extension "Create forecast". Trying to override not-allowed properties: category

Is it a warning or an error? We probably print something like this for the developers but I will make sure it is an error and that it only is printed if you are running Grafana in development mode.

**Comment by sd2k** [comment]
It's logged to the console as a warning 👍

**Comment by sd2k** [comment]
It disables the extension 😞 (just to make sure, I'm talking about when trying to use extensions with a `category` with Grafana versions older than this PR)

**Comment by mckn** [comment]
Thanks for reporting this! 🙏🏻 I will fix this during the day tomorrow.

**Pull request merged**
