### PR TITLE
Docs: Refactor administration docs

### PR DESCRIPTION
**Pull request by gguillotte-grafana**
**What this PR does / why we need it**:

This moves and reorganizes Grafana administration documentation per @torkelo's Docs Admin section plan from 8 June 2022.

**Which issue(s) this PR fixes**:

Fixes grafana/technical-documentation#333

**Special notes for your reviewer**:

This PR may be too large to review on GitHub. Recommend building the docs site (`make docs` from the `grafana/docs` directory) to view the resulting changes to the left sidebar nav, or see below:

image

These changes break many relrefs across the docs. Aliases should handle many or all of these cases. Due to time constraints, I'm fixing as many as I can pending review of the broader structural changes; this should NOT block reviewing or merging.

This should not be a detailed review of the content, beyond ensuring that none has been removed and it is organized as expected.

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Think this looks great! 

I have some simplifications that I think will help make this more future-proof and easier to find topics. 

* Move Server administration / server user management  -> Administration / User management  (add link to user management index page) 
* Move Server administration / Configure Docker Image -> Setup / 
* Move the rest the remaining Server administration / *  to the root Administration / category 

Will make things less nested, and easier to find. In the coming UI navigation change, the org administration and server administration will be available in the same sub-section nav. So we don't need this segregation in the docs.

**Comment by gguillotte-grafana** [comment]
>     * Move Server administration / server user management  -> Administration / User management  (add link to user management index page)
>     * Move Server administration / Configure Docker Image -> Setup /
>     * Move the rest the remaining Server administration / *  to the root Administration / category

This is complete. The majority of changes in these commits, especially moving server-administration to administration, are to update affected relrefs from other docs.

Expanded sidebar nav is now this:

image

**Review by torkelo — APPROVED** [review]
Really great job this! I know this is not the easiest/rewarding work. 

I have not tested it but I think it looks good and might be good to merge this asap to avoid future merge conflicts and iterate fixes in future PRs

**Comment by gguillotte-grafana** [comment]
Kicked CLA check via https://cla-assistant.io/check/grafana/grafana?pullRequest=50592

**Comment by gguillotte-grafana** [comment]
Waited an hour, kicked the CLA check again

**Comment by torkelo** [comment]
@gguillotte-grafana used my admin powers to merge

**Comment by torkelo** [comment]
@gguillotte-grafana since this is not marked for backport will you do a manual sync of all docs in main to 9.0.x branch?

**Comment by gguillotte-grafana** [comment]
Filed #50989 to backport.

**Pull request merged**
