### PR TITLE
Formatting Currency without abbreviation

### LINKED ISSUE #37838: Formatting Currency without abbreviation
**What happened**:
Wanted to output a currency value as the full value, without abbreviation, a currency symbol and thousand commas for readability. 

**What you expected to happen**:
To get something like $53,456.75 instead of $53.46K or $53456.75 or 53,456.75

**How to reproduce it (as minimally and precisely as possible)**:
Set a values units in the following ways:

* Currency / Dollar ($) - this gives you the abbreviated version which is no good for reporting.
* prefix:$ - this gives you an unabbreviated version but without the commas, making large numbers hard to read.
* Misc / Locale Format - this gives you the unabbreviated version with the commas but no currency sign.

None of these get the formatting required.

**Anything else we need to know?**:
I would suggest there are couple of options to fix this, either:

* Add "prefix" as a separate option for a value so it can have both a "prefix" and a unit type attached to it. In this way we could prefix it with $ and set the unit to "Misc / Locale Format".

OR 

* Add an extra option to the "Currency" unit option to allow for the abbreviation to be turned off.

I think the first of these offers the most flexibility but the second is more intuitive.

Forum post: https://community.grafana.com/t/formatting-currency-without-abbreviation/50287

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: MySQL 8.0.19
- OS Grafana is installed on: Docker
- User OS & Browser: Mac / Chrome
- Grafana plugins: None

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Adds option to format currency without abbreviation in tables

**Which issue(s) this PR fixes**:

Fixes #37838

**Special notes for your reviewer**:
https://www.loom.com/share/7fd037c2f29c435ebd44620d0b99b975

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @dprokop @codeincarnate please review the PR 🙏

**Comment by mellieA** [comment]
@gitstart thank you for contributing 🎉 

I've added this to the dashboards project for the squad to review.

**Comment by mellieA** [comment]
This PR adds another option to format currency in **Standard Options**:

Screen Shot 2022-09-16 at 5 53 14 PM

**Comment by ivanortegaalba** [comment]
Here is the units documentation to help reviewers with the PR https://grafana.com/docs/grafana/latest/panels/configure-standard-options/

**Review by axelavargas — COMMENTED** [review]
Hi @gitstart 👋🏾, 

Thanks again for opening this PR, I brought this proposal to the team and after an interesting conversation we noticed some drawbacks with the PR and would like to propose an alternative :)

#### Drawbacks:

- Because we are duplicating the currency format, it will increase the maintainability of this part of the code, especially if we need to deprecate a currency
- We also support a [custom unit](https://grafana.com/docs/grafana/latest/panels/configure-standard-options/#unit) for currencies, with this approach we will need to support "Full Currency" there as well

#### Alternative:

We suggest as a short-term solution to allow the following **extension to the custom currency unit**: `currency:<format=financial>:<unit> `instead of creating duplicate variants of the same currency. `currency:<unit>` would still be the default, but one could format the value.

Something like:

image


Also, in the long term, we want to revisit this area and create a better number formatting strategy https://github.com/grafana/grafana/issues/35838

**Comment by gitstart** [comment]
Thank you for the review @axelavargas, will get back to you with required changes

**Comment by gitstart** [comment]
Hi @axelavargas! Kindly review the new changes

**Review by dprokop — COMMENTED** [review]
This now looks way better with the formatter! We also need to update the documentation to cover the new format.

Two more things to consider:
1. The formatter currently assumes US format. What about using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat to ensure user's locale is respected?
2. Seems like this new format does not respect decimals config - (10000000.12345 produces $10,000,000.12345 regardless of the decimals settings). Think we should allow this - any thoughts?

**Comment by gitstart** [comment]
Hey @dprokop! requested changes has been made, please review the new changes

**Review by axelavargas — COMMENTED** [review]
Hey @gitstart awesome changes 🙌🏾, thanks a lot for following up with this PR, I think there are a couple of minor things to get this feature ready to merge:

- Add unit test for `fullCurrency`, you can do that on symbolFormatters.test.ts
- Add this new feature to the documentation, you can do that by modifying this MDX file: https://github.com/grafana/grafana/blob/main/docs/sources/panels-visualizations/configure-standard-options/index.md#custom-units 

Thank you 🤗

**Comment by leeoniya** [comment]
i'm currently touching some of the formatting code in https://github.com/grafana/grafana/pull/57386, which will affect this PR.

the `decimals` arg here is specifically meant for minimum decimals required to discern adjacent y axis ticks. it can probably be ignored for this case. (i've renamed this function arg in the PR prior to the one linked above).

also, please extract and cache the Intl objects out of this function, they're expensive to re-create and this function can be called very rapidly during mousemoves, or whole-dataset processing.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#performance

**Comment by dprokop** [comment]
Please open the PR in a way that you can sing the CLA :) Thanks!

**Comment by 0xyei** [comment]
I see this PR was not merged. Is something pending? I find this PR really useful.

**Comment by lpil** [comment]
Could someone with the CLA signed reopen this PR please?

**Comment by Niek** [comment]
Any way this can be merged? It's a shame that this is waiting for a year now to be merged.

**Comment by brysn** [comment]
I'm surprised that there isn't a good way to format currency with precision...  Can this be re-opened?

**Comment by konstk1** [comment]
Also would like to have this.

**Comment by lefoy** [comment]
I would also like to have this PR

**Comment by aviudezgonzalez** [comment]
I'd like to have this PR too

**Comment by tonypowa** [comment]
hi @gitstart 

Could you please let us know if you are still willing to make the requested changes from @leeoniya and sign the CLA? 

Otherwise, I'd like to encourage anybody else watching this conversation that would be happy to contribute, to open a new PR and continue working on this where it was left off.

**Comment by Niek** [comment]
@natellium what is the reason for closing this PR? See also issue https://github.com/grafana/grafana/issues/37838 - this feature is highly needed and it seems like 90%+ was implemented.

**Comment by natellium** [comment]
Hey @Niek it's been a while, but looking at the history the CLA wasn't signed so the PR couldn't be merged, and seems the author didn't get back to it. As mentioned above, anyone is welcome to pick it up where it was left and reopen a new one :)

**Pull request closed without merging**
