### PR TITLE
Updated cloudwatch plugin to allow specific tag selection

### LINKED ISSUE #7294: [Bug] [AWS Cloudwatch] It is not possible to get a single tag value by its key
It seems that it is not possible that you can get single tag values from AWS cloudwatch.

Please include this information:
- What Grafana version are you using?
4.2
- What datasource are you using?
CloudWatch and Graphite
- What OS are you running grafana on?
Docker on CentOS
- What did you do?
I tried to create a template variable with the content of the EC2 instance name tag. I tried different queries but it didn't work. The only thing I found out was that I can get the indexes by their id, as example:
```
ec2_instance_attribute(eu-central-1, Tags[0].Value, {"instance-id": ["$instanceid"]})
ec2_instance_attribute(eu-central-1, Tags[1], {"instance-id": ["$instanceid"]})
```
But the order isn't the same all the time, so this is no solution. 

- What was the expected result?
I can get the value from an single ec2 instance tag by the name of the key. I want something like this:
```
ec2_instance_attribute(eu-central-1, Tags[Name].Value, {"instance-id": ["$instanceid"]})
```

- What happened instead?
I can only get all tags of an EC2 instance as JSON object, but I'm not able to get only one tag.
In the end I want the value of the tag with the key "Name", in the following example "models-int-p".

## Some screenshots
bildschirmfoto_2017-01-18_17-40-46
The identifier of our systems is the AWS EC2 Instance Id which I can get from Graphite. The JSON with the tags from AWS is displayed weird.

bildschirmfoto_2017-01-18_17-41-52
Here you can see the query. It seems that Grafana gets some JSON object from AWS.

Thanks for fixing that in advance.

### PR DESCRIPTION
**Pull request by paco3346**
Tags come back from AWS as a key value pair inside an array
This array is now converted to an object
Tags can be selected when using the 'ec2_instance_attribute' query
Example: `ec2_instance_attribute(us-east-1, Tags.Name, { "tag:Grafana": [ "true" ] })`

Fixes #7294

### CODE REVIEW

**Comment by torkelo** [comment]
could you add a unit test for this case, and add an example to the docs that describe this scenario?

https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/cloudwatch.md#ec2_instance_attribute-json-filters

**Comment by jason913** [comment]
could we get this same tagging capability for all CW metrics, so we can filter any resource by tag?

EBS as example??

**Comment by lobsterdore** [comment]
@paco3346 this is a much needed change, any chance of adding the unit test so this can be merged?

**Comment by paco3346** [comment]
I started working on writing some tests but TBH I don't know where to start. I'll see if I can chip away at this during this week.

**Comment by paco3346** [comment]
@jason913 That's a great idea but not that this PR is for grabbing tag data and using it in the UI. The actual filtering is handled by AWS' metrics API.

Unless you meant to add this functionality for grabbing tag data for the UI for other services as well?

**Comment by paco3346** [comment]
@torkelo This should be ready now.

**Comment by paco3346** [comment]
@torkelo My apologies for bumping this but I did just want to throw out a reminder that the tests and docs tag are no longer applicable. This is ready for a review / merge.

**Comment by canstudios-louisem** [comment]
@torkelo any chance this could get merged we are a bit blocked on a project waiting for this.

**Comment by paco3346** [comment]
@torkelo Is there anything I can do to help get this merged?

**Comment by maiconbaumx** [comment]
Is this update available in Version 4.4.1 (commit: 6a9f8ca)?
I'm trying to get the value of tag-key Name and it's not working...

**Comment by paco3346** [comment]
@maiconbaumx Although merged, this has not been released yet.
If you'd like to retrofit it into your existing installation see this diff:
https://github.com/paco3346/grafana/commit/525da95f49350711d5fdc1f724a4b3b313f46edc

**Comment by kamalvpm777** [comment]
@paco3346 , we are also very interested in retrieving the EC2 name tag and currently blocked on this. we are with Grafana v3.1.1 version right  now. Could you let us know in which latest version of grafana  we can get this new features that allow us to pull the EC name tag as well.

Also wondering if below is the right query to pull the EC2 tag name using the instance id
ec2_instance_attribute($region,Tags.Name, {"instance-id": ["$instanceid"]})

**Comment by kamalvpm777** [comment]
@paco3346 , we are also very interested in retrieving the EC2 name tag and currently blocked on this. we are with Grafana v3.1.1 version right  now. Could you let us know in which latest version of grafana  we can get this new features that allow us to pull the EC name tag as well.

Also wondering if below is the right query to pull the EC2 tag name using the instance id
ec2_instance_attribute($region,Tags.Name, {"instance-id": ["$instanceid"]})

**Comment by paco3346** [comment]
@kamalvpm777 There are no releases with this in it. You'll need to manually put this into your current version. See my comment above.

**Comment by paco3346** [comment]
For those interested in how to show the Name but use the InstanceId in the background:

image

image

image

image

**Comment by TryTryAgain** [comment]
Patience is a virtue. Looks like things are coming together. I'd also love for this to work across the board. `LinkedAccount`, specifically. As you can see in my question https://github.com/grafana/grafana/issues/9054

**Comment by paco3346** [comment]
@TryTryAgain I'm not sure I quite understand your question about `LinkedAccount`. Are you looking for a way to display a name but use a value in the background?

**Comment by TryTryAgain** [comment]
@paco3346 ...looking to display `account-alias`, tag, or anything else that's a human-readable-name to refer to the `LinkedAccount` ID/number, and use throughout grafana, like we would any other template variable, rather than the `LinkedAccount` ID. If I go through our master billing payer account, browsing it like:
`us-east-1 -> AWS/Billing -> EstimatedCharges -> LinkedAccount` --> This next dimension is a list of all our accounts linked to the master billing account. I'd be happy if https://github.com/grafana/grafana/pull/5590 was working/had been merged, I think that would give me what I want, in that I'd at least be able to match known account numbers/IDs to account names/aliases/tags/anything, and albeit more manual than I'd like we could at least display those names rather than writing them/scripting them into the dashboard...also a manual task up front at least, we'd like to avoid all that.

**Comment by greg-jaunt** [comment]
We could use the same, but using ELB tags on ELB namespace CloudWatch metrics.

**Comment by KurtKnudsen** [comment]
It looks like this functionality has been removed due to this commit: https://github.com/grafana/grafana/commit/8fba6dcb0d26e8a46de607c67a8048b1af9406c5#diff-a8259c8cbce476f0faab44ef81675dfb

It seems the function was refactored and perhaps this filtering functionality wasn't implemented into the backend query properly as anything entered for the filter, as long as it's JSON, will return the full list, not the filtered one.

**Comment by paco3346** [comment]
@KurtKnudsen I finally got around to testing the new code and it seems to work for the `Name` tag but I can't get it to work for any other tags. I'll poke around and see what I can figure out.

**Comment by mass-ltd** [comment]
@paco3346 good to hear, I look forward to what you can find.

**Comment by KurtKnudsen** [comment]
@paco3346 good to hear, I look forward to what you can find.

**Comment by EugeneAbramchuk** [comment]
@paco3346 Any success yet? `AWS/RDS` namespace is a bit easier since it shares both Id and Name, thus you can query with `dimension_values`. Sadly `AWS/EC2` requires more magic to make it easier to filter by name.

**Comment by deepanshululla** [comment]
Hi all
Is there an update to this. Did anyone found a way or workaround to do it

**Comment by darkl0rd** [comment]
Second that, how to display the "$name" in the Alias?
Also, due to the filtering on Tag, I don't see a way to make this "multi-value" anymore - ideas?

I would like to select several of my cluster nodes at once, by their friendly name, and show them in the same graph.

**Comment by juliofalbo** [comment]
Is it possible to create a panel to monitor more than 1 instance (like a regex in the name tag)?

**Comment by juliofalbo** [comment]
@darkl0rd , I have the same problem. Could you share your solution, please?

**Comment by bdelamatre** [comment]
@darkl0rd I managed to get multi-value to work by using the advanced formatting option to output json. For example, instead of embedding $name inside of a string value of a JSON array, I just passed the selection as a JSON array.

ec2_instance_attribute($region,InstanceId, {"tag:Name":${name:json}})

I then enabled "Include All option" which is the default selected value. Every time I select multiple names, the instance ids are populated into the other variable and with "all" selected I can use the server variable as a multi-value.

I am still trying to figure out how to translate the ids back to a name. I would have expected something like this to work:

ec2_instance_attribute($region,InstanceId,{"InstanceId":"$instanceId"})

but it seems that filtering ignores InstanceId for reasons that I am not clear on.

**Comment by m-stojanovic** [comment]
Hi, can you tell in which version was this released? @paco3346

**Comment by jangaraj** [comment]
@m-stojanovic See github https://github.com/grafana/grafana/commit/aa3a737fea8a77a858d5d022c3ce70766e161d35 it was released in the 6.1.6 release.

**Comment by DeveloperMujtaba** [comment]
> Second that, how to display the "$name" in the Alias? Also, due to the filtering on Tag, I don't see a way to make this "multi-value" anymore - ideas?
> 
> I would like to select several of my cluster nodes at once, by their friendly name, and show them in the same graph.

Hello I'm facing same issue. Can you please share your solution? Thanks. I really need this.

**Comment by wpcarro** [comment]
Grafana/AWS noob here: Is there a sandbox in which I can run and inspect/troubleshoot the return values from these queries? I'm not sure how I would come-up with these myself.

I'm kind of just cargo culting code I find on threads like this, but I'd like to have a more hands-on approach.

**Comment by wpcarro** [comment]
Two more questions:

1) should we expect an empty list for the `$name` (labelled "Server") variable?

image

2) Should I expect to be able to supply regex values in the `$name` input?

**Comment by 0evang77** [comment]
does any one know if this approach for replacing the instanceID with instance name still works in version 9.4?

**Comment by jsomontan** [comment]
Hi, I'm using version 11.0 and running it as a container.  Is this method supported?  I'm new to Grafana and don't see how to this up.  Any documentation would be helpful.  Thanks!

**Comment by jsomontan** [comment]
So I think I got this set up correctly as I'm able to get the tags with a variable.  However, when I try to assign "InstanceId=$name" in the dashboard, it shows blank.  I'm only able to get the InstanceId to work when "InstanceId=*".  Any help is much appreciated!  Thanks!

image
image

**Comment by jsomontan** [comment]
I got the answer here: https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/tree/master/aws-ec2

You can only get the info by single instance selection.  I was hoping to get a group of them.  I'll have to figure out the json configuration to get what I need.

**Pull request merged**
