### PR TITLE
Feature/Graph: added series override option to have hidden_series by default

### LINKED ISSUE #4645: [Feature Request] Save graph series visibility
Maybe this option exists but I can't find it.

I want to preserve graph series visibility in legend.

For example:
2016-04-11 13_50_10-grafana - single energy meter

I want to keep Qt, St and Remain time series displayed in legend but hidden from graph.

Is that possible?

### PR DESCRIPTION
**Pull request by Gauravshah**
**What this PR does / why we need it**:
This helps you set default hidden visibility for series on a graph

**Which issue(s) this PR fixes**:
Fixes #4645

**Special notes for your reviewer**:
`hiddenSeriesTainted` is useful to let people customize it via panel instead of forcing to use what is set on overrides

### CODE REVIEW

**Comment by Gauravshah** [comment]
@ryantxu can you help with a review?

**Comment by Gauravshah** [comment]
ping

**Comment by Gauravshah** [comment]
ping @dprokop

**Comment by Gauravshah** [comment]
Is there a reason as to why this PR is getting no review ?

**Comment by Gauravshah** [comment]
Some issues with merging master I can redo commits if required

**Comment by smurfix** [comment]
I need this too. Please try to get traction to get it implemented.

**Comment by Gauravshah** [comment]
reopened a new PR in https://github.com/grafana/grafana/pull/20124

**Pull request closed without merging**
