### PR TITLE
[v.8.1.x] Chore: Backport for missing tslib import

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
Hmm I think this branch is also based on something old and not that actual:
image

image

So I'm not able to verify the fix 😞

**Comment by hugohaggmark** [comment]
@joshhunt this branch needs a rebase too

**Comment by joshhunt** [comment]
@hugohaggmark updated!

**Review by hugohaggmark — APPROVED** [review]
Verified and correct base branch 🙌  👍 

image

**Comment by axelavargas** [comment]
Closing this PR, in favor of https://github.com/grafana/grafana/pull/43556 , because we could get a version missmatch between the typescript version used to build the plugin and the one used to build Grafana.

**Pull request closed without merging**
