### PR TITLE
Support multi and all for datasource variables

### PR DESCRIPTION
**Pull request by mauve**
This PR enables multi-selection and an 'All' option for datasource template variables.

### CODE REVIEW

**Comment by torkelo** [comment]
This does not solve the real problem of supporting multi valued data source variables. They can be used in data source selection in panel metrics tab, and as data source for other template variables. That is incredibly complicated to solve, not sure that complexity is worth the effort & maintainability cost.

**Comment by mauve** [comment]
We _need_ (or: would like) to have this because we have one datasource per region because we need to have one AWS account per region due to internal policies. Not being able to iterate over datasources is huge restriction for us.

**Comment by torkelo** [comment]
you need create custom variable in that case. As you are not really using it as a datasource variable but a region variable.

**Comment by mauve** [comment]
@torkelo that doesnt work because we have several stages per region all with different accounts, e.g. we have `beta-us-east-1`, `gamma-us-east-1` and `prod-us-east-1`

**Comment by torkelo** [comment]
then how will this PR solve your use case? This will not make each value in the variable use different datasources as the PR only make it possible to have multiple values, nothing here that actually uses the fact that it can be multiple (the hard part).

**Comment by mauve** [comment]
@torkelo it allows us to repeat a panel based on a datasource variable?

**Comment by torkelo** [comment]
yes, but if you don't repeat or use it in a query variable data source picker?

**Comment by mauve** [comment]
If you select multiple values and use the variable in a panel which does not have repeat, then it will break; that is right; but that breakage is possible already today. It is relatively easy to create nonsensical combinations using the templating feature as is.

I don't understand the question about query variable data source picker.

**Comment by mauve** [comment]
As a future enhancement I would like to add repetition on a query-level, so that if you have a datasource variable with multi-select but no panel repetition then the query is repeated in the panel. 

We have an internal datasource plugin which has a similar feature which is very well-received by our internal users (the datasource plugin is not meaningful for external people so I cannot share the code).

**Comment by torkelo** [comment]
> But that breakage is possible already today

For data source variables? The reason I want hesitant here is that adding options that only work in a very limited scenario and otherwise breaks creates a very poor trial and error user experience and a high support burden for us.

**Comment by mauve** [comment]
No the breakage is possible for variables in general.

In the metrics editor, I guess it should be possible to show a warning if the variable expands to more than one value? So that if the user forgets to enable repeat on the panel then we pick only the first value of the expansion and show a warning?

**Comment by bergquist** [comment]
Another solution that might work for you is to use [simple-json-datasource](https://grafana.com/plugins/grafana-simple-json-datasource) plugin to create template variables. You would have to write your own backend for it but then you can return anything you like.  

Does that make sense?

**Comment by mauve** [comment]
- rebased

@bergquist I don't think I can use a another type of template variable (at least I don't understand how), our setup looks like this:

- stage beta-us-east-1 (account 1)
- stage preview-us-east-1 (account 2)
- stage prod-us-east-1 (account 3)
- ... 17 more

Switching between these stages using a template variables works fine (type datasource/cloudwatch), however for some dashboards I want to use repetition in order to be able to get an overview (which is what I am trying to achieve using this change).

**Comment by torkelo** [comment]
I am leaning toward closing this. I know that is not what you want to hear. This is a popular request but I am afraid that supporting multi-valued data source variable values is going to be something we regret and it's going to become a technical burden, especially when it's only partially supported, since it can never be full supported since repeating on query level is never going to happen.

**Comment by mauve** [comment]
I understand that it cannot go in as-is but I would like to play with this some more and try to come up with a solution which is easy to support but still supports the basic use-case. Separating by account is the standard and recommended way to separate resources in AWS.

Also why is query-repetition never going to happen? That sounds like a feature which is very useful.

We have an internal datasource (amzn-only) which actually supports repetition on a query-level which is really nice. So when you select multiple regions (for example) instead of getting multiple panels you get multiple series in the graph.

**Comment by torkelo** [comment]
closing this as there has been no solution to the problem of supporting multi-valued data source variable in non repeat scenarios.

**Pull request closed without merging**
