### PR TITLE
WIP: Restartable playlist & Playlist based on template variables

### PR DESCRIPTION
**Pull request by utkarshcmu**
Now, a dashboard can have a playlist based on selected template variables. A playlist can have some non-changing variables and some changing variables. The dashboard will display all the possible combinations of the changing variables depending on the playlist interval. 

Please review the code, and suggest if anything needs modification.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
For screenshots please refer #773

**Comment by utkarshcmu** [comment]
Circle CI had some bug in my last push to this PR, so triggering another.

screen shot 2015-09-30 at 11 35 03 am

**Comment by torkelo** [comment]
Looks good, some unit tests would be good. Especially for playlistCtrl and its methods

**Comment by utkarshcmu** [comment]
Thanks for the review. :) Sure, will add tests. This feature will be so useful to everyone.

**Comment by torkelo** [comment]
yes, its a very highly voted feature request! Not sure if it will make into 2.5 as that is very close to beta release. Maybe, no promises.

**Comment by utkarshcmu** [comment]
I completely understand the priority of release as compared to merging this feature. Feel free to accept the PR at your own pace. Also, as this PR has conflicts with the master branch, let me know if you want me to merge the PR with the latest commit in master branch, I can do that. Thanks for this awesome piece of software. Grafana has been super useful to us. Keep up the good work. :)

**Comment by torkelo** [comment]
why does it have conflicts?

**Comment by utkarshcmu** [comment]
Conflict is due to changes in "public/app/partials/playlist.html" file. #2831 fix changed this file and is merged into grafana master while I was working on this feature on my forked repo. I can merge the conflicts and push another commit to this PR. Do you want me to do that?

**Comment by utkarshcmu** [comment]
Added couple of unit tests, merged with Grafana's master branch.

**Comment by utkarshcmu** [comment]
As now the 2.5v release date is moved ahead to Oct 15th, is there a chance that we merge this PR for #773, I am just curios? :)

**Comment by torkelo** [comment]
no, so much to do before then (docs, release article/blog, whats new in 2.5 docs) and need to finish cloudwatch data source supports

**Comment by utkarshcmu** [comment]
@torkelo : Any chances of this #773 P0:Critical feature getting merged in the upcoming release?

**Comment by torkelo** [comment]
not sure, would like to combine this and the persisted playlist feature and do a major overhaul of the playlist feature, not sure when there will be time for that

**Comment by utkarshcmu** [comment]
Sure, let me know if there is any help needed.

**Comment by utkarshcmu** [comment]
I understand you would like to have a major overhaul of the playlist feature, which is the best solution for playlist feature and I agree with you on that. But in my opinion, we can also work step by step, one step at a time. As the first step we can go ahead with this feature in the next release(2.5.1 or 2.6), so that playlist feature is much more richer than before.

Then as the second step or an improvement, we can work on persisted playlists in (2.6 or 3.0) future releases, completing the rest of the work you want for playlist feature. Until then let users use this feature and make full use of it as this is one of the most asked features.

Honestly, I do not see any harm in providing this feature to the users right now, it will only make their lives easy and make Grafana more powerful. :)

**Comment by utkarshcmu** [comment]
I am starting to work on the persisted playlist in this same PR.

**Comment by utkarshcmu** [comment]
Closing this PR, will open another one with enhanced playlist features.

**Pull request closed without merging**
