### PR TITLE
[draft] K8s thema validation & translation

### PR DESCRIPTION
**Pull request by mildwonkey**
(this is not going to be merged)

This adds SchemaValidate Validation and SchemaTranslate Mutation plugins. I'm pretty sure absolutely everything about the implementation is wrong, and since we have the mutation plugin there's no reason to keep the Validation step, but I wanted to play with the code.

### CODE REVIEW

**Comment by sdboyer** [comment]
this PR is _amazing_. i wish i'd seen it earlier!

At least the validation admission handler is clearly useful on its own (i'm less sure about the mutating translation admission handler), and it gives us a really clear integration point to hang a bunch of other stuff on.

i had a bunch of comments i started making inline, but then realized the better thing to do was just make another PR against this one to really show it: #70728

**Comment by sdboyer** [comment]
> since we have the mutation plugin there's no reason to keep the Validation step, but I wanted to play with the code.

this did occur to me while i was doing my refactors - it's true that translation entails validation, so there's duplication involved. But, even understanding that this isn't intended to be merged, i'm also not sure that using admission controllers for translation is quite where that belongs. It's certainly a fine place to start, but i think we need to be looking at how webhook conversions work with conventional CRDs, and improving on that

**Comment by mildwonkey** [comment]
hey @sdboyer please don't close PRs on my behalf. I'm still working with this.

**Comment by sdboyer** [comment]
apologies!

**Pull request closed without merging**
