### PR TITLE
Drone: Fix releasing of next NPM packages

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Fix releasing of next NPM packages under Drone.

### CODE REVIEW

**Review by stevenvachon — APPROVED** [review]
LGTM; with the understanding that the hash is generated and injected into the *package.json* file as part of the build step instead.

**Comment by aknuds1** [comment]
@stevenvachon I tested that, and it looks fine.

**Comment by mckn** [comment]
> LGTM; with the understanding that the hash is generated and injected into the _package.json_ file as part of the build step instead.

Yes, that is correct. I can update the comments to make that more obvious.

**Comment by aknuds1** [comment]
Is it ready now @mckn?

**Comment by mckn** [comment]
> Is it ready now @mckn?

`  # Frontend packages have already been versioned and built by the 
  # build-frontend step in drone. We will only unpublish the previous 
  # canary version and publish the current built version as the new 
  # latest canary build.`

**Comment by aknuds1** [comment]
@mckn I don't have any opinion on the comments.

**Review by mckn — APPROVED** [review]

**Pull request merged**
