### PR TITLE
Platform: Add support for Postgresql pgpass file

### PR DESCRIPTION
**Pull request by gjacquet**
**What is this feature?**

lib/pq has built-in support to use pgpass file for authentication when no password has been provided. However this requires that the connection does not contain the password parameter at all.

Removing password parameter when postgresql password is empty in both SQL store and postgres datasource.

**Why do we need this feature?**

This allows using postgresql pgpass file with Grafana with makes it possible to use dynamic credentials for postgresql.

**Who is this feature for?**

Anyone using postgresql with Grafana

**Which issue(s) does this PR fix?**:

Related to https://github.com/grafana/grafana/discussions/61516

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sakjur** [comment]
As far as I can tell we need to pick supporting this for either the database for Grafana or the data source.

A data source is not supposed to use the same credentials as Grafana’s database since that would provide anyone with access to that data source with read-write access to Grafana’s database. We need to strongly separate dynamic secrets available to Grafana itself and available for data sources.

**Comment by gjacquet** [comment]
I fully agree a datasource and grafana itself should use a separate set of of credentials.
This is supposed  to be supported out of the box by the postgres driver for go.

pgpass file follows those specification (this is postgres standard file): https://www.postgresql.org/docs/current/libpq-pgpass.html

It allows specifying different set of credentials on each line, each line containing hostname, port, user and password.

It would be perfectly possible to support both grafana sql store and any number of datasources with each distinct credentials.

pgpass file would look like this:

```
# Format: hostname:port:database:username:password
grafaba-db-host:5432:grafana:grafana:randompassword
datasource1-host:5432:ds1:somedb:randompassword2
datasource2-host:5432:ds2:someotherdb:randompassword3
```

In my case I would be using a sidecar to regenerate the credentials as needed but the file could also be mounted as a kubernetes secret or provisioned with something like ansible.

**Comment by gjacquet** [comment]
Is there something I can do to get things rolling with this PR?

**Comment by codeincarnate** [comment]
Hey @gjacquet, this falls in a bit of a strange spot as it likely touches on multiple areas of responsibility. I'm going to try to take some time to look at this in the next week. Can't promise I'll get to it but will do what I can to move this along.

**Comment by gjacquet** [comment]
@codeincarnate thanks for looking into it!

I thought bundling what is essentially the same change in two places would be the easiest but I understand how it could cause some ownership issue.

If you think it would make things easier, I could split the PR in two and open a separate one for PG datasource.

**Comment by gjacquet** [comment]
@codeincarnate @sakjur Trying a different approach to get the ball rolling...

I reverted the change to the datasource and I am keeping the sqlstore change only. I believe the sqlstore is the most likely to benefit from this kind of feature (at least it is for my use case).

What do you think?

**Comment by gjacquet** [comment]
I just resolved a conflict in the test file.
Is there anything else I can do on this PR?

**Review by sakjur — APPROVED** [review]
LGTM!

Thank you for your patience and let's get this merged 🙂

**Pull request merged**
