### PR TITLE
[MYSQL] convert explicitely smallint and tinyint

### LINKED ISSUE #35876: "convert value to float failed: metricIndex 1 type can't be converted to float" after upgrade to 8.0.2
**What happened**:
After upgrade to Grafana 8.0.2 some simple graphs broke, which were showing integer data.
Error message: "convert value to float failed: metricIndex 1 type can't be converted to float"
The data types triggering the bug are smallint and tinyint unsigned from a MySQL database.

**What you expected to happen**:
Successful conversion to float values.

**How to reproduce it (as minimally and precisely as possible)**:
Plot a graph with smallint or tinyint column data from a MySQL database.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: 10.3.27-MariaDB-0+deb10u1
- OS Grafana is installed on: Debian Stable
- User OS & Browser: 
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #35876

**Special notes for your reviewer**:

seems when smallint or tinyint is nullable or not would impact its scantype. when they are nullable, scantype becomes nullableint64, for which we would generate the default string converter.

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Looks good I think. Added some comments and a suggestion to get the CI to not run mysql_tests during the integration tests when database is sqlite.

> To avoid this kind of issue, maybe it makes more sense to think about enhance convert value to float64 to support also string type?

Maybe. Is the type really string, isn't it string array? If you would like to evaluate that, please push changes to this PR or open an alternative PR so that we can understand what it actually means in terms of code and changes.

**Comment by ying-jeanne** [comment]
> Looks good I think. Added some comments and a suggestion to get the CI to not run mysql_tests during the integration tests when database is sqlite.
> 
> > To avoid this kind of issue, maybe it makes more sense to think about enhance convert value to float64 to support also string type?
> 
> Maybe. Is the type really string, isn't it string array? If you would like to evaluate that, please push changes to this PR or open an alternative PR so that we can understand what it actually means in terms of code and changes.

i think this fix is urgent, let's fix the issue and i would create a ticket for the improvement, we can discuss that next week.

**Review by kminehart — APPROVED** [review]

**Comment by kminehart** [comment]
Are these specifically for NULLABLE smallint / tinyint? will this also work for non-nullable columns with these types?

**Comment by ying-jeanne** [comment]
> Are these specifically for NULLABLE smallint / tinyint? will this also work for non-nullable columns with these types?

they are working for both nullable and no nullable.

**Pull request merged**
