### PR TITLE
Fix array display from url

### PR DESCRIPTION
**Pull request by simPod**
Changes this
screen shot 2018-07-22 at 00 20 22

to this 

screen shot 2018-07-22 at 00 35 43

when array is passed via url (no text is set then)

### CODE REVIEW

**Comment by simPod** [comment]
@marefr yup, that code from PR is present in my grafana [version](ad4d71740acad939f5e6b8ff7c10955dec601ba6). 

I see the tests fail so this will eventually require more work.

**Comment by marefr** [comment]
Understood. Are there any issue open tracking this bug? If so, please include a reference to that in description. Fix the failing tests and we'll have a look at it.

**Comment by simPod** [comment]
@marefr should be good now

**Comment by marefr** [comment]
@simPod could you please describe a test case in text that this PR solves. Having some problem seeing exactly what it fixes  based on the updated tests. Too me this seems to solve the same problem as #11968 so would be good with a step by step description of case that #11968 didn't solve but that this PR solves. After this I'll have all I need to be able to test and hopefully merge this. Thanks

**Pull request merged**
