### PR TITLE
Graphite: Process multiple queries to Graphite plugin

### LINKED ISSUE #59601: Public dashboard only showing one query per panel
**What happened**:

When viewing public dashboard only one query is shown per panel.

**What you expected to happen**:

Panel should show all queries as seen when viewing dashboard normally.

**How to reproduce it (as minimally and precisely as possible)**:

 * Clean install.
 * Add graphite data source.
 * Create new dashboard.
 * Create new panel. 
 * Select a graphite metric.
 * Add another query and select different graphite metric.
 * Apply
 * See graph with two lines, one per query.
 * Save dashboard.
 * Share dashboard as public.
 * Go to public URL. 
 * See graph only has one line.

**Anything else we need to know?**:

It appears to be showing only the last query. If I change order of queries then I see the other line is shown. If I use wildcard query then multiple lines of that query shown if that query is the last but still no other queries show.

image

Also tried with Gauge panel, same issue.

**Environment**:
- Grafana version: 9.3.0 and 9.4.0-90933pre 
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, FF.
- Grafana plugins: None
- Others:

### PR DESCRIPTION
**Pull request by mmandrus**
**What is this feature?**

Updates the Graphite datasource plugin to handle multiple queries, instead of just the last one in the list. It aliases each query in order to correlate queries with results.

**Why do we need this feature?**

The current behavior is causing issues in public dashboards, which we had previously not seen because the front end sends graphite queries to Graphite through the proxy instead of through /ds/query.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/59601

**Special notes for your reviewer**:

There is some less-than-ideal code in here to handle associating graphite query results with requests, but based on my research, it would not be safe to rely on result order aligning with query order. Using aliases seemed to be the safest approach.

An alternative would have been to send off multiple different queries to Graphite, but this seemed preferred to minimize the impact of errors.

### CODE REVIEW

**Review by itsmylife — APPROVED** [review]
LGTM
It would be nice if you could provide unit tests for this.

**Review by bohandley — APPROVED** [review]
LGTM!

**Comment by bobemoe** [comment]
Hi, thanks for the fix. Unfortunately looks like this may have now broken the wildcard queries. While I can now confirm this fixes the original issue, now any wildcard metrics are only showing the last match of the set. Shall I open new issue with screenshots etc?

**Comment by bobemoe** [comment]
Just to note wildcards were working in the original issue and were the only way to get multiple lines. This is now kind of the reverse!

**Pull request merged**
