### PR TITLE
Further Prometheus unit tests

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by torkelo** [comment]
Great, the prometheus unit tests should be moved to app/plugins/datasource/prometheus/specs, and to typescript , please take a look at the graphite, or influxdb tests for how those look

**Comment by jimmidyson** [comment]
Ah OK - was basing it on the ones from `public/test/specs`. Will convert.

**Comment by torkelo** [comment]
yea, its recent change (trying to clean up the frontend code structure and unit tests), most data source tests should now live in their respective plugins dir

**Comment by jimmidyson** [comment]
Cool - working on it now.

**Comment by jimmidyson** [comment]
Converted to typescript - minimal changes actually.

**Comment by torkelo** [comment]
great

**Pull request merged**
