### PR TITLE
Separate Control for Refresh Picker Size in Explore

### PR DESCRIPTION
**Pull request by kavindunilshan**
What is this feature?

This feature introduces a separate variable, showSmallRefreshPicker, to control the size of the refresh picker independently from the time range picker.

Why do we need this feature?

The goal is to prioritize the display of the time range over the "Run Query" text, as it is crucial for users to see the execution time range clearly. The refresh button remains identifiable by its icon and color, making the text less critical. 

For now, the current threshold size remains at 1210px, but having a separate variable allows for more flexibility in the future.

Who is this feature for?

This feature is for Grafana users who need to see the selected time range clearly, even in smaller container widths, while still being able to identify the refresh button by its icon and color.

Which issue(s) does this PR fix?

This PR does not address a specific issue but enhances the UI for better usability in displaying the time range and refresh picker.

### CODE REVIEW

**Comment by gelicia** [comment]
@kavindunilshan hello, thank you for this PR! Sorry if any of my chatter is annoying, I'm trying to push this to an ephemeral instance so our team member on the UX side can take a peek at it easily. If it doesnt work for some reason I'll communicate it internally with screenshots for everyone interested. Thanks in advance for your patience and thanks for contributing to Grafana!

**Comment by kavindunilshan** [comment]
Hi @gelicia,

Thank you for your message! No worries at all, your chatter is not annoying. I appreciate the effort to push this to an ephemeral instance for the UX team to review. Please let me know if there's anything else you need from my side or if there are any issues. Thanks for your support and for the opportunity to contribute to Grafana!

**Comment by gelicia** [comment]
> I appreciate the effort to push this to an ephemeral instance for the UX team to review. 

Unfortunately it looks like the ephemerals require branches to be on grafana/grafana. I created a draft PR with your change to create the ephemeral only. That branch and PR will not be merged and will be deleted as soon as the ephemeral is not needed, as I want to be sure you get credit for your work. Hopefully you understand, and if not I can delete the branch/PR ASAP and will use another method to communicate this change our UXer.

**Comment by kavindunilshan** [comment]
Hi @gelicia,

Thank you for setting up the draft PR. I understand the need for ephemerals to be on grafana/grafana. I can create a branch on grafana/grafana and apply the exact changes if everything works as expected. Please let me know the results from the draft branch, and I'll proceed accordingly. Thanks for your support and assistance!

**Comment by gelicia** [comment]
@kavindunilshan  - [the draft branch worked](https://github.com/grafana/grafana/pull/89966#issuecomment-2204110626), and I checked and it is true that the ephemeral process doesn't work off forks, just branches off grafana/grafana. If you don't want to re-create the branch, we can just use that ephemeral, otherwise if you would rather re-create the branch, please do and I will delete the draft PR.

Thanks again for all the back and forth with this.

I also wanted to ask - is there a window width that demonstrates your change vs what exists in Grafana now? If youd like, you can use https://play.grafana.org/explore to look at a Grafana instance that does not have your change

**Comment by kavindunilshan** [comment]
Hi @gelicia,

I don't have permissions to create a branch directly in the grafana/grafana repository. Could you please grant me the necessary permissions, or alternatively, could someone from the team create the branch based on my fork? I'm happy to proceed in whichever way is most convenient.

Regarding the window width, the change should be noticeable in containers smaller than 1210px. I'll use the provided Grafana instance to compare and provide some screenshots to illustrate the difference.

**Comment by gelicia** [comment]
> I don't have permissions to create a branch directly in the grafana/grafana repository. 

Ah, my mistake. Sorry about the bad advice. I cant give you access and I'm afraid if someone makes the branch for you, you won't be able to push to it. Are you okay with proceeding with this PR as is and using the ephemeral at https://ephemeral1511182189966gelicia.grafana-dev.net/ for UX validation?

**Comment by kavindunilshan** [comment]
Hi @gelicia,

No problem at all! I understand the situation. I'm okay with proceeding as planned with this PR and using the ephemeral instance for UX validation. Just to confirm, after validation, will the changes be merged into the main repository from the branch where they were tested on the ephemeral instance? Thanks for your help and understanding!

**Comment by gelicia** [comment]
@kavindunilshan I'm still struggling to see the difference in your change. `showSmallRefreshPicker` and `showSmallTimePicker` have equivalent logic, so changing one to the other does not make a difference that I can see. Is there something I'm missing?

**Comment by kavindunilshan** [comment]
Hi @gelicia 

For now, the current threshold size remains at 1210px, but having a separate variable allows for more flexibility in the future. If you are suggesting changing the threshold accordingly, I can do it.

**Comment by kavindunilshan** [comment]
Hi @gelicia, Thank you for your feedback and suggestions.
I understand your concern about the elements condensing at different sizes. However, having a separate variable for the refresh picker provides more flexibility for the time range selector. The "Run Query" button is easily identifiable by its icon and color, making the text less critical. In contrast, displaying the time range is crucial because it's not practical to hover over the tooltip every time.
Additionally, on a typical laptop screen with the sidebar open, the current solution hides the selected time range. In my solution, as shown in the screenshot, the time range remains visible even when the sidebar is on.

Existing solution.
image

My Solution
image

I hope this clarifies the benefits of the separate variable. Looking forward to your thoughts.

**Comment by gelicia** [comment]
Hello again @kavindunilshan , thank you for your contribution.

Unfortunately, our designer is going through and redesigning the toolbar in Explore, including the elements' look at different screen sizes. We discussed this as a team and decided to hold off on any improvements to the toolbar, as it will be reworked extensively then. Unfortunately a lot of the work on what we're doing is currently internal because it's in the research and design phase by our UXer, but the ticket to track progress is https://github.com/grafana/grafana/issues/87796

This ticket was passed along to him so he can note your feedback and possibly incorporate it into the future work for that project.

Thank you for patience and contributing to Grafana!

**Pull request closed without merging**
