### PR TITLE
Canvas: Fix vertices connection indexes issue

### LINKED ISSUE #84606: Canvas: Cant add vertices to existing connection
For existing connections created before vertex editing feature was added, users are unable to add vertices.

Mar-15-2024 09-58-47

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

This PR fixes the wrong connection vertices indexation.

**Which issue(s) does this PR fix?**:

Fixes #84606 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Develer** [comment]
> Vertfixes!

Sorry, not a native speaker 😁

**Comment by drew08t** [comment]
Tested locally, still seeing some issues.
Mar-22-2024 11-02-18

**Review by baldm0mma — APPROVED** [review]
Worked as expected locally!

**Comment by adela-almasan** [comment]
Leaving these here for better tracking.
Issues found while testing this PR (some might be unrelated regressions):

1. When moving elements that have connections, the connections are becoming erratic 

https://github.com/grafana/grafana/assets/88068998/9334b1d5-ab5e-4368-8e13-4c11909f70e0

2. Regression - if you're removing the target element, the connections appear disconnected from the source element when moving

https://github.com/grafana/grafana/assets/88068998/53bb20ac-ebac-4a09-b5cb-3170235e1295

3. Noticing an odd behavior with selection - sometimes the wrong element is selected, sometimes there's a group selection (although just one element was selected). Can't reproduce it consistently.

multiple_elements_selected

**Comment by nmarrs** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/85026

**Pull request closed without merging**
