### PR TITLE
Query Splitting: Display progress of sub-requests using annotations

### LINKED ISSUE #65104: Loki: Query Splitting - Display progress of sub-requests
When query splitting is in use, any query will now involve more than one network request. Besides the loading indicator, the user does not have access to any clue indicating how many subrequests have been run at a given point in time. This situation is more noticeable when every subrequest creates a slow query, or if a request does not return any data.

Specially for queries that do not return results, we don't show any kind of progression or feedback when each partitioned subquery is being resolved.

We need to consider the feasibility of displaying something to the user indicating how many subrequests have been executed and returned with or without data.

### PR DESCRIPTION
**Pull request by matyax**
Alternative implementation to https://github.com/grafana/grafana/pull/65905, where instead of finding a place to display the progress of split requests, we add a loading frame that is updated as we receive data.

https://user-images.githubusercontent.com/1069378/233137075-b30f8eff-1f5a-49f1-8255-41ea63dea1f5.mov

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/65104

**Special notes for your reviewer:**

Updated implementation using annotations:

Note when testing: these changes currently trigger some errors which are going to resolved after https://github.com/grafana/grafana/pull/66877 is merged.

### CODE REVIEW

**Comment by matyax** [comment]
I will validate this with UX, but any feedback in advance will be much appreciated.

**Comment by matyax** [comment]
I'm pretty satisfied with how it looks and works. Opening for review.

**Comment by matyax** [comment]
FYI @niat22

**Comment by svennergr** [comment]
Getting some errors when hovering the frame:


https://user-images.githubusercontent.com/8092184/233292580-cc96632b-5592-4703-b011-8a419cb2c209.mov

```
notationMarker.tsx:100 Uncaught TypeError: canEditAnnotations is not a function
    at AnnotationMarker.tsx:100:18
    at AnnotationMarker (AnnotationMarker.tsx:146:14)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
(anonymous) @ AnnotationMarker.tsx:100
AnnotationMarker @ AnnotationMarker.tsx:146
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
queue.<computed> @ task.js:61
run @ task.js:35
eventListener @ task.js:46
AnnotationMarker.tsx:100 Uncaught TypeError: canEditAnnotations is not a function
    at AnnotationMarker.tsx:100:18
    at AnnotationMarker (AnnotationMarker.tsx:146:14)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
(
```

**Comment by svennergr** [comment]
Also not sure if this Log Volume Histogramm issue is caused by this?


https://user-images.githubusercontent.com/8092184/233293604-11e908e5-9d11-4946-81ca-355063a7533f.mov

**Comment by matyax** [comment]
> Getting some errors when hovering the frame:

Yesterday I was told we could try to fix those on our own or report it if it gets too difficult.

I'll check the logs volume, must be related.

**Comment by matyax** [comment]
@leeoniya FYI.

**Comment by gabor** [comment]
my personal opinion:
- i love, love, love the visual effect 👍 . i think it is very useful for these progresssively-displayed graphs
- but i'd like this to be somehow deeper integrated with the timeseries-panel, maybe a meta-tag in the dataframe-header or something else. what do you think @grafana/dataviz-squad ?

**Pull request closed without merging**
