### PR TITLE
Support Node v12

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by dprokop** [comment]
@simPod thanks for the PR. Why are you requesting to add that? Recently we decided to stick with Node's active LTS.

**Comment by simPod** [comment]
@dprokop thanks for quick reply. It jumped out on me when trying to build grafana locally. I though it's a mistake that it is not allowed yet.

**Comment by dprokop** [comment]
No, it's a conscious decision to be on active LTS. For now I suggest switching to Node 10.

**Comment by simPod** [comment]
I'll rather run `yarn install --ignore-engines`. Thanks

**Pull request closed without merging**
