### PR TITLE
Build: Release packages under next tag when changes detected on master

### PR DESCRIPTION
**Pull request by dprokop**
- Introduces new job to `build-master` workflow that will publish all packages under `next` tag when changes in any of the packages are detected. Packages will be released under current lerna.json version appended by `-COMMIT_SHA`

### CODE REVIEW

**Comment by dprokop** [comment]
@ryantxu FYI:

For an unclear reason the packages fail to build:

https://circleci.com/gh/grafana/grafana/123290?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

I have added `any` annotation in https://github.com/grafana/grafana/pull/18062/commits/e58e7cb4c5b6cc870b0f2113b7b4a7f8212d2e3e that helped. But not sure what is the sustainable way forward for such cases. Couldn't reproduce locally at all

**Comment by dprokop** [comment]
TODO: 
- [ ] Packages are not published, most probably because we run `git reset --hard` before publishing, and lerna publish's `--contents` still operates on the original package directory, not `dist`. Anb because that version is already published to npm, it skips publishing. We need to commit those changes to package.json/lerna.json after version bump (BUT don't check those in!!!),as lerna publish requires us to be on clean branch.

**Comment by dprokop** [comment]
@ryantxu I have noticed that running `lerna changed` always checks for changes since v6.0.0-beta1 tag. Under the hood they run `git describe --always --long --dirty`(https://github.com/lerna/lerna/blob/master/utils/describe-ref/lib/describe-ref.js#L49) which in our case returns that tag. Been trying to figure out why describe returns that particular tag, but did not come to any meaningful conclusions. Can you pls verify that? I know that in your case it detected  changes only in some of the packages, while for me it always detects changes in all of them.

**Comment by dprokop** [comment]
TODO:
- [ ] use `git diff HEAD~1..HEAD --name-only -- packages` instead of `lerna changed` due to the `changed` being tag dependant

**Review by ryantxu — APPROVED** [review]
LGTM

**Pull request merged**
