### PR TITLE
Forms: Fix input suffix position (caret-down in Select) 

### PR DESCRIPTION
**Pull request by torkelo**
For some reason this position fix is no longer needed

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]

**Comment by tskarhed** [comment]
Seems like those two pixels did something.
Screenshot from 2020-03-13 14-26-07

**Comment by Clarity-89** [comment]
@tskarhed that's weird, I quickly tested it with Input suffix and it was looking good, maybe it's only relevant to caret icon 🤔

**Comment by tskarhed** [comment]
> @tskarhed that's weird, I quickly tested it with Input suffix and it was looking good, maybe it's only relevant to caret icon

I tried the zoom-glass which looked fine,maybe it's a question of 1px or just prioritize an icon

**Comment by Clarity-89** [comment]
> I tried the zoom-glass which looked fine,maybe it's a question of 1px or just prioritize an icon

Yeah, that also looks fine for me, maybe we could just exclude caret icons with `> .fa:not([class*='fa-caret-']) {`

**Comment by torkelo** [comment]
> Seems like those two pixels did something. 

Screenshot from 2020-03-13 14-26-07 

Where is this? Cannot find one that looks off now

**Comment by tskarhed** [comment]
> > Seems like those two pixels did something.
> 
> Screenshot from 2020-03-13 14-26-07
> 
> Where is this? Cannot find one that looks off now

It's in Storybook, which can include all icons.

**Pull request merged**
