### PR TITLE
github: add issues to observability squad projects

### PR DESCRIPTION
**Pull request by gabor**
the observability squad structure changed, now there are 3 separate squads, we adjusted the auto-assign config.

### CODE REVIEW

**Review by meanmina — APPROVED** [review]
We still need to add actions for each of the 3 new Squad labels but this looks good so far :)

**Review by yesoreyeram — CHANGES_REQUESTED** [review]
Is there any specific reason we don't have `datasource/Graphite` here?  Can we add if that was a mistake?

**Review by joey-grafana — APPROVED** [review]

**Comment by joey-grafana** [comment]
> Is there any specific reason we don't have `datasource/Graphite` here? Can we add if that was a mistake?

I think there are just some that were never added. I could add more from [here](https://docs.google.com/spreadsheets/d/1ILr-NYAFapP52K9_wnp2aDjnBHxCnQeag57mW4_UUrw/edit#gid=623522083 ).

Or I could add all of the tags for our three teams?

**Comment by joey-grafana** [comment]
> > > Is there any specific reason we don't have `datasource/Graphite` here? Can we add if that was a mistake?
> > 
> > 
> > I think there are just some that were never added. I could add more from [here](https://docs.google.com/spreadsheets/d/1ILr-NYAFapP52K9_wnp2aDjnBHxCnQeag57mW4_UUrw/edit#gid=623522083).
> > Or I could add all of the tags for our three teams?
> 
> @joey-grafana - yes please.

Added a few more actions for those ds's that already have labels.

Those that don't have a label
Metrics: AppDynamics, DataDog, Dynatrace, Honeycomb, NewRelic, SignalFX, Wavefront
Logs&Traces: Opensearch, Sentry

Should we add labels for each of the above ds's?

Also other areas like logs panel, recorded queries etc. don't have labels - I'm thinking some of them may be too specific to have labels. What do you think?

**Comment by gabor** [comment]
> Added a few more actions for those ds's that already have labels.

nice work!

> 
> Those that don't have a label Metrics: AppDynamics, DataDog, Dynatrace, Honeycomb, NewRelic, SignalFX, Wavefront Logs&Traces: Opensearch, Sentry
> 
> Should we add labels for each of the above ds's?

i think the problem is that some (all?) of those datasources live in separate github repositories, like https://github.com/grafana/opensearch-datasource .

i would recommend to merge the changes as they are in this version, and we can tune the list later, if necessary.

**Review by yesoreyeram — APPROVED** [review]

**Pull request merged**
