### PR TITLE
Chore/extend plugin schema json

### PR DESCRIPTION
**Pull request by tolzhabayev**
Allowing additional properties in `routes.tokenAuth` and `routes.jwtTokenAuth` so that it matches our backend behavior.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by sdboyer** [comment]
LGTM, too - even though we've just introduced the new pluginmeta coremodel to replace this file, this change would have no effect (it was effectively _already_ `additionalProperties: true` in CUE)

**Comment by tolzhabayev** [comment]
> LGTM, too - even though we've just introduced the new pluginmeta coremodel to replace this file, this change would have no effect (it was effectively _already_ `additionalProperties: true` in CUE)

it will have an effect here: https://github.com/grafana/plugin-validator/blob/a36fe1f22e6ae16a30825e3e54ec36e503a42559/pkg/cmd/plugincheck/main.go#L38

**Comment by sdboyer** [comment]
sorry, to be clear, i meant this change would have no effect on the new coremodel schema, so there's no need to change anything there to keep it in sync with this change.

Not that it wouldn't have the intended effect in places where the JSON schema is used - still everywhere, since we haven't ported anything over yet :)

**Pull request merged**
