### PR TITLE
Alerting: Add ability to include aliases with hyphen in InfluxDB 

### LINKED ISSUE #31284: Slack Notification (Alert) doesn't resolve tag value if the tag key contains hyphen (-)
We have a query defined in this way:
image

The query includes alias that uses two tags: `cluster_name` and `operation-global-id`: 
```
[[tag_cluster_name]] - [[tag_operation-global-id]]
```

This is the graph is looks like:
image
As you can see, the alias looks good.

When we define an alert to slack on that query, this is how it looks in the slack channel:
image
The tag without hyphen was resolved but the one with hyphen wasn't

**Environment**:
- Grafana version: 7.3.2
- Data source type & version: Influx
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: Safari / Slack
- Grafana plugins: Slack Notification

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Tiny fix, to make InfluxDB metrics include hyphens (`-`) in their names when aliasing. 

**Which issue(s) this PR fixes**:

Fixes #31284

**Special notes for your reviewer**:

Steps:
* Needs an InfluxDB datasource running.
* Used basic cpu exporter - exports `cpu` and `host` metrics.
* Tweaked metrics locally to transform `cpu` and `host` to `cpu-a` and `host-a` to reproduce.

Before:

image

After:

image

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

There's some room for improvement of the tests, but not a blocker for this PR
- Convert to [Go standard tests](https://github.com/grafana/grafana/blob/master/contribute/style-guides/backend.md#testing) 
- Seems like table-driven tests could be a good fit for some of the tests

**Comment by dsotirakis** [comment]
> LGTM
> 
> There's some room for improvement of the tests, but not a blocker for this PR
> 
> * Convert to [Go standard tests](https://github.com/grafana/grafana/blob/master/contribute/style-guides/backend.md#testing)
> * Seems like table-driven tests could be a good fit for some of the tests

Agree @marefr, should we create a broader ticket to start do some refactoring?

**Comment by marefr** [comment]
@dsotirakis Our approach is to try and fix things as we change code. For this one you can probably create an issue if that helps. 

Note that this has milestone 7.5.0 and needs to be backported into v7.5.x branch for it to actually be included in the release build. Please add backport label

**Comment by marefr** [comment]
You probably want to add "add to changelog" label so that it show up in the changelog for the release. Title can be improved a bit I think. We normally uses the alerting tag for the title, see for example https://github.com/grafana/grafana/blob/master/CHANGELOG.md#features-and-enhancements-1

**Pull request merged**
