### PR TITLE
Document elasticsearch maxConcurrentShardRequests parameter

### PR DESCRIPTION
**Pull request by perjahn**
Documented elasticsearch maxConcurrentShardRequests parameter for datasource provisioning, also added an example of the latest esVersion parameter. (And some whitespace formatting).

### CODE REVIEW

**Review by Elfo404 — CHANGES_REQUESTED** [review]
hello @perjahn, thanks for contributing!

I don't think a link to github to where this parameter is referenced in ES code would add much value for users. There's some documentation at  https://www.elastic.co/guide/en/elasticsearch/reference/master/search-multi-search.html about this parameter, maybe we can write something similar?

**Comment by achatterjee-grafana** [comment]
@perjahn, following up to see whether you got a chance to check out @Elfo404's review.

**Comment by perjahn** [comment]
Sure!

**Comment by Elfo404** [comment]
@achatterjee-grafana the parameter mentioned defaults to 5 if esVersion is `>= 7.0.0`, 256 if `esVersion` is `>=5.6.0, <7.0.0`, and ignored if `<5.6.0`. how can we phrase it here?

**Comment by achatterjee-grafana** [comment]
> @achatterjee-grafana the parameter mentioned defaults to 5 if esVersion is `>= 7.0.0`, 256 if `esVersion` is `>=5.6.0, <7.0.0`, and ignored if `<5.6.0`. how can we phrase it here?

How about:
Maximum number of concurrent shard requests that each sub-search request executes per node. Defaults to 5 if esVersion is greater than or equals 7.0.0. When the esVersion is less than 7.0.0 and greater than or equals 5.6.0, then the default value is 256. Option is ignored when esVersion is less than 5.6.0.

**Review by Elfo404 — APPROVED** [review]

**Comment by Elfo404** [comment]
@achatterjee-grafana if you are ok with the changes I'll merge

**Review by achatterjee-grafana — APPROVED** [review]

**Pull request merged**
