### PR TITLE
Plugin extensions: Make sure core features use new hooks

### PR DESCRIPTION
**Pull request by sunker**
**What is this feature?**

This PR replaces the usage of the now deprecated `usePluginExtensions` hook with the new `usePluginLinks` hook and the `usePluginComponents` hook. 

Note that this PR does not entirely remove the usage of the deprecated `usePluginComponentExtensions` hook, as the new `usePluginComponents` does not yet have feature parity with the old hook. I'll handle this in a follow up PR. 

**Why do we need this feature?**

`usePluginExtensions` is deprecated and will be removed in future releases of Grafana.

**Who is this feature for?**

Maintainers of Grafana 

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Comment by tomratcliffe** [comment]
The alerting test changes look good to me (but I think @konrad147 should check the app logic as well if possible)

I would say that a lot of the test changes (definitely within alerting) could be solved by removing the mock behaviour altogether, and instead setting up the necessary plugin logic in the jest setup (or in the render helper methods that we have)

e.g. if we had the below in `setupTests.ts` (which mirrors what's actually done in `app.ts`), then a lot of the mocks in the tests can just be removed altogether

```
beforeAll(() => {
  const pluginExtensionsRegistries = setupPluginExtensionRegistries();
  setPluginLinksHook(createUsePluginLinks(pluginExtensionsRegistries.addedLinksRegistry));
});
```

I'm not suggesting we necessarily do this in this PR though - just saying that we should probably fix the tests so they aren't so tied to the inner workings of hooks etc. anyway. That's a historical problem with some of the test code/the fact that we render larger component trees in alerting

I can remove the plugin logic from alerting tests in a followup PR so we don't have this kind of problem in the future 🤞

**Review by leventebalogh — APPROVED** [review]
Nice! 👏

**Comment by tomratcliffe** [comment]
(I have a draft PR [here](https://github.com/grafana/grafana/pull/92983) with the changes that I was thinking of to generalise this away so future changes like this aren't as arduous. I can merge that to `main` after this is in)

**Comment by sunker** [comment]
> (I have a draft PR [here](https://github.com/grafana/grafana/pull/92983) with the changes that I was thinking of to generalise this away so future changes like this aren't as arduous. I can merge that to `main` after this is in)

@tomratcliffe had a look at your PR and it totally makes sense. I'm gonna go ahead and merge this PR now. Thanks for thorough thoughts and raising the follow up PR!

**Pull request merged**
