### PR TITLE
Datasources: Ensure the 'Host' custom header functions as expected.

### PR DESCRIPTION
**Pull request by tan9**
**What is this feature?**

Ensure the functionality of the `Host` custom header is properly implemented and functioning as intended.

The issue related to this has already been addressed in the upstream project as https://github.com/grafana/grafana-plugin-sdk-go/pull/848. However, until the upstream project accepts this pull request and rolls out a new version, our test case will continue to encounter issues.

**Why do we need this feature?**

In the current Grafana datasource configuration, users have the flexibility to set the "Host" header just like any other header, but this approach often leads to unexpected behavior. This pull request addresses this issue by proposing a more robust and effective solution.

**Who is this feature for?**

DataSource users who need the flexibility to override the `Host` header. This feature is especially useful in situations where configuring domain resolution is challenging or impractical.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Waiting for https://github.com/grafana/grafana-plugin-sdk-go/pull/848 to be merged and published.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by tan9** [comment]
https://github.com/grafana/grafana-plugin-sdk-go/pull/848 has been merged and released in [`0.199.0`](https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.199.0).

@andresmgot Could you please review this Pull Request? Your feedback would be invaluable. Thank you!

**Review by andresmgot — APPROVED** [review]
LGTM, it seems there is an unrelated error for the integration tests. Can you merge latest `main` here?

**Comment by tan9** [comment]
@andresmgot done the merging.

**Comment by tan9** [comment]
@andresmgot  , after rebasing with `main`, the pipeline still encountered failures during the `pr-integration-tests/wait-for-remote-alertmanager` phase. Here are some examples:

- Failed Builds:
  - [Build #154319](https://drone.grafana.net/grafana/grafana/154319/4/25)
  - [Build #154395](https://drone.grafana.net/grafana/grafana/154395/4/25)
  - [Build #154473](https://drone.grafana.net/grafana/grafana/154473/4/25)
  - [Build #154488](https://drone.grafana.net/grafana/grafana/154488/4/25)

Additionally, there are some builds that have been pending for a while:

- Pending Builds:
  - [Build #154318](https://drone.grafana.net/grafana/grafana/154318)
  - [Build #154472](https://drone.grafana.net/grafana/grafana/154472)
  - [Build #154517](https://drone.grafana.net/grafana/grafana/154517)
  - [Build #154560](https://drone.grafana.net/grafana/grafana/154560)

Do you have any insights on what actions can be taken right now to address these issues, or do you know who we can reach out to for assistance in resolving these pipeline problems? Your guidance would be greatly appreciated.

**Comment by andresmgot** [comment]
Sorry, not sure why that's failing. I have merged a PR to update the SDK dependency and that seemed to work: https://github.com/grafana/grafana/pull/80590 Can you merge this PR with main again and avoid changes to the go.mod/go.sum files?

**Comment by andresmgot** [comment]
This kept failing so I ended up cherry-picking your commit and merging https://github.com/grafana/grafana/pull/80715. This can be closed, now. Thanks!

**Pull request closed without merging**
