### PR TITLE
Fix misspell issues

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @torkelo @bergquist,

Related to #14205, I fixed some misspelling issues detected by [misspell](https://github.com/client9/misspell) and [codespell](https://github.com/codespell-project/codespell).

### CODE REVIEW

**Review by kylebrandt — APPROVED** [review]
I wanna thank you for this! ;-)

**Comment by bergquist** [comment]
Merged master to trigger the build.

**Comment by bergquist** [comment]
Why doesn't the CI trigger? :(

**Review by papagian — APPROVED** [review]
Thank you for your contribution!

**Comment by marefr** [comment]
Super strange! Would suggest trying to close this. Rebase commits and open a new PR?

**Comment by mjtrangoni** [comment]
@marefr will do tomorrow. It fails mostly on enterprise builds.

**Comment by mjtrangoni** [comment]
@marefr My bad, the problem was that I had CircleCI enabled on my fork for testing some linter integration I did in the past, and it seems to be overwriting the environment variables.
Feel free to remove all unnecessary commits.

**Pull request merged**
