### PR TITLE
Explore: Fix vector(5) syntax error in loki log explore

### PR DESCRIPTION
**Pull request by liguozhong**
**What is this feature?**
We upgraded from grafana 7.5 to grafana 9.0 this month, and found that some log explore changes are relatively large.

fix vector(5) error.
https://grafana.com/docs/loki/latest/logql/metric_queries/#functions
LogQL supports a set of built-in functions.
vector(s scalar): returns the scalar s as a vector with no labels. This behaves identically to the [Prometheus vector() function](https://prometheus.io/docs/prometheus/latest/querying/functions/#vector). vector is mainly used to return a value for a series that would otherwise return nothing; this can be useful when using LogQL to define an alert.

**Why do we need this feature?**
a bugfix
image
**Who is this feature for?**
loki logql use log explore

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:
fixed in my dev env.
image

### CODE REVIEW

**Comment by liguozhong** [comment]
@gabor  can you help me complete this PR？ thanks.
It's the first time I submit a PR in grafana/grafana, the merge is blocked, there are too many check rules.

**Comment by liguozhong** [comment]
no-backport

**Comment by matyax** [comment]
Thanks for the PR @liguozhong , it looks great! Could you please update `lezer-logql` depedency to `0.1.2` to sync with https://github.com/grafana/lezer-logql/pull/22? Thank you.

**Comment by liguozhong** [comment]
> Thanks for the PR @liguozhong , it looks great! Could you please update `lezer-logql` depedency to `0.1.2` to sync with [grafana/lezer-logql#22](https://github.com/grafana/lezer-logql/pull/22)? Thank you.

done，thank

**Comment by liguozhong** [comment]
> Thanks for the PR @liguozhong , it looks great! Could you please update `lezer-logql` depedency to `0.1.2` to sync with [grafana/lezer-logql#22](https://github.com/grafana/lezer-logql/pull/22)? Thank you.

continuous-integration/drone/pr  fail
@matyax ,I update `lezer-logql` depedency to `0.1.2` ,but CI  run fail. 
can you help me? how to fix this dependency conflict?

    "monaco-editor": "0.34.0",
    "monaco-promql": "1.7.4",
    "@grafana/monaco-logql": "^0.0.7",



```
➤ YN0000: │  
➤ YN0000: │  "@grafana/monaco-logql@npm:^0.0.6":
➤ YN0000: │ @@ -21988,9 +21987,9 @@
➤ YN0000: │      "@grafana/experimental": 1.1.0
➤ YN0000: │      "@grafana/faro-core": 1.0.0-beta2
➤ YN0000: │      "@grafana/faro-web-sdk": 1.0.0-beta2
➤ YN0000: │      "@grafana/google-sdk": 0.0.4
➤ YN0028: │ -    "@grafana/lezer-logql": 0.1.1
➤ YN0028: │ +    "@grafana/lezer-logql": 0.1.2
➤ YN0000: │      "@grafana/monaco-logql": ^0.0.6
➤ YN0000: │      "@grafana/runtime": "workspace:*"
➤ YN0000: │      "@grafana/scenes": ^0.0.14
➤ YN0000: │      "@grafana/schema": "workspace:*"
➤ YN0000: │ 
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
```

**Comment by matyax** [comment]
Sure.

**Comment by liguozhong** [comment]
> Sure.

thanks,CI run success.

**Comment by liguozhong** [comment]
I'm sure vector syntax is no longer parser error.

image

**Review by matyax — APPROVED** [review]
Great work! Thank you for your contribution!

**Pull request merged**
