### PR TITLE
AzureMonitor: Add support for Virtual WAN namespaces

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

Adds support for monitoring Virtual WANs with Azure Monitor

**Special notes for your reviewer**:

This is tough to test, as it relies on resources we just can't set up in our Azure account. I have created a Virtual WAN, but with no additional sub-subresources. While the Virtual WANs show up in the plugin now, It doesn't list any metric namespaces. I'm not sure if this is due to the resources not being set up completely, if additional changes are required to support this, or a limitation of Azure Monitor Metrics + Virtual WANs.

image

I was playing in the Azure Portal and it appears Virtual WANs cannot be monitored through Azure Monitor > Metrics, you must view it from Virtual WANs > Metrics. Not sure if this points to limitations of the Azure Monitor Metrics API or not.

### CODE REVIEW

**Comment by yesoreyeram** [comment]
As seen in [azure docs](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported), there is no real support for Virtual WAN through Monitor API. You can confirm this through [azure portal](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/metrics).

**Comment by joshhunt** [comment]
Virtual WANs don't appear to be supported resources for Azure Monitor Metrics, rather you query metrics for a Virtual WAN's resources, such as VPN Gateways.

**Review by sunker — APPROVED** [review]
LGTM

**Review by sunker — APPROVED** [review]
LGTM

**Pull request merged**
