### PR TITLE
Gravatar: Use HTTPS by default

### LINKED ISSUE #20955: Use https to fetch gravatar images by default
**What would you like to be added**:
Use https to fetch gravatar images by default.
**Why is this needed**:
this weekend I found that my avatar in Grafana does not shown. I found that the HTTP request had been hijacked, because it use HTTP protocol. why not use https by default?
```go
func UpdateGravatarSource() {
	srcCfg := "//secure.gravatar.com/avatar/"

	gravatarSource = srcCfg
	if strings.HasPrefix(gravatarSource, "//") {
		gravatarSource = "http:" + gravatarSource
	} else if !strings.HasPrefix(gravatarSource, "http://") &&
		!strings.HasPrefix(gravatarSource, "https://") {
		gravatarSource = "http://" + gravatarSource
	}
}
```

### PR DESCRIPTION
**Pull request by jiajunhuang**
**What this PR does / why we need it**:

HTTP protocol is based on plain text, so it may be hijacked, use HTTPs by default to prevent it.

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/20955#issuecomment-563142364

Fixes #20955 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jiajunhuang** [comment]
It seems that the logic in `UpdateGravatarSource` is verbose, I don't know why does it need to give the value to `gravatarSource` and then check if it is start with `//` or something else, it is already.

so just use a const.

**Review by aknuds1 — APPROVED** [review]
LGTM! I also don't understand the need for `UpdateGravatarSource`.

**Comment by aknuds1** [comment]
Can you sign the CLA please?

**Comment by jiajunhuang** [comment]
signed

**Review by papagian — COMMENTED** [review]
Only thing I can think of given that the function is exported is that potentially the `gravatarSource` can be overridden.  But I don't know if this is a requirement of any existing use case.
Otherwise LGTM.

**Comment by aknuds1** [comment]
> Only thing I can think of given that the function is exported is that potentially the `gravatarSource` can be overridden. But I don't know if this is a requirement of any existing use case.
> Otherwise LGTM.

@papagian `UpdateGravatarSource` always sets `gravatarSource` to the same value though, so `gravatarSource` (which is private) can't really be overridden right?

**Comment by papagian** [comment]
> @papagian `UpdateGravatarSource` always sets `gravatarSource` to the same value though, so `gravatarSource` (which is private) can't really be overridden right?

That's true, you are right.

**Review by papagian — APPROVED** [review]

**Comment by aknuds1** [comment]
Thanks @jiajunhuang!

**Pull request merged**
