### PR TITLE
(stackdriver) Get token from GCE metadata server

### PR DESCRIPTION
**Pull request by mtanda**
I think this is fundamental feature.

### CODE REVIEW

**Comment by torkelo** [comment]
thanks @mtanda ! :heart:

**Comment by mtanda** [comment]
To avoid jwt token auth error message, add condition to do jwt token auth.
Not sure what field is best, I check `privateKey` field.

**Comment by sunker** [comment]
Great @mtanda! Testing this i rather cumbersome, but hopefully I'll be able to do it today. 
Thanks!

**Comment by sunker** [comment]
@mtanda what are the premises / scenario behind for this if statement to be truthy?  
`if req.Header.Get("Authorization") == "" && ds.Type == "stackdriver" {
... 
}`
The only way I can test this is to upload a JWT file in the stackdriver config page, save it and then reset the current configuration and then hit save again. To me this seems like a pretty hacky approach, but maybe I'm missing something here? If not, a more intuitive solution might be to have a checkbox in the config page saying something like "Use GCE authentication"? What do you think?

**Comment by mtanda** [comment]
@sunker 
> If not, a more intuitive solution might be to have a checkbox in the config page saying something like "Use GCE authentication"?

Like CloudWatch datasource, we need to add checkbox or dropdown.

**Comment by mtanda** [comment]
@sunker Don't mind.
I'm not good at UI, I don't want to do it...
Please add the checkbox :-)

**Comment by sunker** [comment]
Okay I'll do it, not a problem @mtanda :)

**Comment by daniellee** [comment]
@mtanda just to let you know, @sunker has been working on this and testing it with provisioning. Think we will be merging it next week.

**Pull request closed without merging**
