### PR TITLE
[Backport] Chore: add setting to skip org assignment for external users (#34834)

### PR DESCRIPTION
**Pull request by sakjur**
* Chore: add setting to skip org assignment for external users

Introduce 'skip_org_role_update_sync' setting to skip any kind of org assignment during the login of external users.
As a consequence manual organization assignments won't be overridden during the upsert of an external user.

Part of #22605

* Chore: Rename skip_org_role_update_sync to oauth_skip_org_role_update_sync and relocate it to auth section

* Chore: replace global setting access where possible

(cherry picked from commit 6beba5a0498eeffa53241be03e01abab76ea191c)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Would perhaps keep this to be released for 8.5 since it's somewhat a new feature. WDYT?

**Comment by stefanpetter** [comment]
Hi @marefr 

Ik would be really nice if this little feature could find it's way to Grafana asap. As mentioned in the other pull request (#34834), lack of this feature stalls implementation of Grafana in a multi-tenancy way for a lot of users.

@sakjur mentioned in the other pull request: 
"I'm targeting this for an 8.4.2 release, it seems small and safe, you've waited a long time to get this in, and since 8.4.0 came out yesterday it's going to be a while until 8.5.0 comes around. In case anyone looks to this in the future, that's exceptional and this shouldn't be used as an argument for adding features to patch releases"

**Comment by sakjur** [comment]
@marefr Normally, yes. My reasoning is what Stefan cited above 👆. WDYT?

**Comment by marefr** [comment]
Sure sounds good. Just wanted a discussion about it :+1:

**Review by kalleep — APPROVED** [review]

**Pull request merged**
