### PR TITLE
configure amount of used connections for databases

### PR DESCRIPTION
**Pull request by t-8ch**
Implements #11711 

## Open points

- [ ] How to generalize the UI to all SQL datasources
  * Copy paste everywhere
  * Implement a custom ctrl + partial
- [ ] We could also add support for the ConnMaxLifetime while we are at it.

### CODE REVIEW

**Comment by marefr** [comment]
Could you please sign the CLA? 

We have plans on generalizing the SQL datasources eventually. Agree that it's cumbersome right now with a lot of duplicated code. We greatly appreciate any ideas of how to best do this.

Took a quick look and this looks pretty good. Would really like the same settings to be added for postgres and mssql just to make them somewhat consequent in features - this will greatly help that day when we want to generalize the implementation.

Would be good if you could update the Data source options documentation for mysql, postgres and mssql as well. You find these files in https://github.com/grafana/grafana/tree/master/docs/sources/features/datasources.

**Comment by t-8ch** [comment]
@marefr 
I was not aware of the CLA before and it is currently being reviewed by my employer, I will sign it as soon as possible.
I'll take a look at a possible unification.
The docs are also coming.

**Comment by t-8ch** [comment]
@marefr Could you provide me any hints on how to have my employer sign the entity variant of the CLA?

**Comment by marefr** [comment]
@t-8ch that's a good question. Let me come back with an answer regarding that.

**Comment by marefr** [comment]
@t-8ch usually an employee can sign the CLA if the employer agree to this. If the employer really wants/need to sign the CLA we have a manual process - in this case please send an email to torkel at grafana.com and take it from there. Thanks

**Comment by t-8ch** [comment]
@marefr Thanks for the investigation. I will ask internally.

**Comment by marefr** [comment]
@t-8ch haven't received any response in long time so closing this for now. Will consider reopen on request.

**Comment by t-8ch** [comment]
The CLA part is still ongoing. I will reopen this PR as soon as I can continue working on it.

**Comment by marefr** [comment]
Thanks. Then we know

**Pull request closed without merging**
