### PR TITLE
Explore: Fix filter by series level in logs graph

### LINKED ISSUE #17769: Loki: Filter by level no longer works
**What happened**:
Filtering by log levels in the Loki graph legend does not change the log row output. It does change the graph, however. This worked fine in 6.2.4.

**What you expected to happen**:
Log row output filtered according to log level label selected.

**How to reproduce it (as minimally and precisely as possible)**:
grafana-loki-level-bug

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.0-pre (5aa13ee)
- Data source type & version: Loki 0.1.0
- OS Grafana is installed on: Uubntu 18.04
- User OS & Browser: Firefox on MacOS
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by marefr**
**What this PR does / why we need it**:
Adds back support for filtering log messages by series level in logs graph which seem to have been broken since merging of #17027.

**Which issue(s) this PR fixes**:
Fixes #17769 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hugohaggmark — COMMENTED** [review]
Works as expected, Set is a lot more performant then Array so there might be a use case here that I'm not sure we should change.

**Comment by marefr** [comment]
@hugohaggmark yeah I was a bit unsure going from Set to array, but looked at the referenced PR and it removed the usage of Set ([code](https://github.com/grafana/grafana/pull/17027/files#diff-7c466efb827e0e37e79ab05400966ed0L171)) and changed it to array ([code](https://github.com/grafana/grafana/pull/17027/files#diff-7c466efb827e0e37e79ab05400966ed0R212)).

@dprokop any pointers here on why usage of `Set` was removed?

**Comment by dprokop** [comment]
@marefr can't remember why I did it. Since legend in Explore is not dependant on the `hiddenSeries` directly, I think Set is a way to go. Sorry about that!

**Review by hugohaggmark — APPROVED** [review]
LGTM, the change to Set doesn't impact the PR.

**Comment by marefr** [comment]
> LGTM, the change to Set doesn't impact the PR.

It can do :smiley: But will try to not break it!

**Comment by marefr** [comment]
Tried to revert this to use a Set instead, but couldn't get it to work. Will merged this now and we have to reconsider in the future if this becomes a performance problem.

**Pull request merged**
