### PR TITLE
Support ICQ as alert notifier

### LINKED ISSUE #14538: Support ICQ as alert notifier
https://en.wikipedia.org/wiki/ICQ

### PR DESCRIPTION
**Pull request by nolequen**
Fixes #14538

### CODE REVIEW

**Comment by torkelo** [comment]
ICQ still exists? :)

We are not accepting more notifiers, we hope to soon make this a pluggable feature (ie support backend plugins to add more)

**Comment by nolequen** [comment]
Yes, it exists and we are using it as a corporate messenger. We really need such notifier.

**Comment by bergquist** [comment]
@nolequen you can always write a small web app and send webhooks to it, then pass that information to ICQ yourself until we support plugins.

**Comment by bergquist** [comment]
If you open source your web app we are happy to link to it from our docs. Once we support plugins everyone can use the same plugin. Until then we are very restrictive about how many third-party API's we integrate with since it puts the maintenance burden on us.

**Comment by nolequen** [comment]
@bergquist I understand your point. But the maintenance burden is not only on your shoulders. The community helps you to develop new features, support them in future, fix bugs and so on. Why get in the way of that...

**Comment by nolequen** [comment]
hi @torkelo @bergquist 
how about pluggable notifiers feature? is there any progress?

**Pull request closed without merging**
