### PR TITLE
Component/Icon: Exposes all available unicons for use

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Previously only a small subset of the icons available with the `react-unicons` package were exposed via the `Icon` component. This PR makes the remaining icons available.

**Special notes for your reviewer**:
The `Icon` component takes the `name` prop, converts it to pascal case, and prepends it with `Uil` in order to access the icon as it's exported via the `react-unicons` package. This works with every icon except `Uil500px`, which, when converted from the name `500px` becomes `Uil500Px` after conversion to pascal case. For the sake of simplicity I opted to leave this particular icon out, but if it's necessary we can add  some special case code such that it's included.

### CODE REVIEW

**Comment by Clarity-89** [comment]
Was there a reason we need all the icons to be exposed? I'm just thinking that in case there are similar icons the users might chose either of them which would result in not-so uniform UI where different icons are used for similar use cases.

**Comment by kaydelaney** [comment]
This change was mostly prompted by some designs for a new feature making use of icons that weren't exposed. If we don't want to expose all the icons in one big chunk but rather on an as-needed basis that could work as well though.

**Comment by torkelo** [comment]
@ivanahuckova @jessover9000 what are your thoughts on exposing all unicon icon? might lead to some inconsistent icon usage for icons that are similar / alts

**Comment by ivanahuckova** [comment]
Yeah, we exposed only some of the icons on purpose - for consistency reasons. So the developers are more likely to look into the icons that we already use at first, and then add/request the new icon. The next step should probably be [to better document which icons are used where any why](https://github.com/grafana/grafana/issues/28748). I have already [started a little](https://github.com/grafana/grafana/pull/29056/files), but didn't have time to finish this (I am also mentioning that new icons can be easily requested). So I would prefer to just expose the new icons that we want to use, than all of them.

**Comment by kaydelaney** [comment]
Closing this since it seems like it makes more sense to just add icons on an as-needed basis.

**Pull request closed without merging**
