### PR TITLE
Add image build for ppc64le architecture

### PR DESCRIPTION
**Pull request by carlosedp**
**What this PR does / why we need it**:

This PR adds to the CI image building for ppc64le architecture.

Signed-off-by: Carlos de Paula <me@carlosedp.com>

### CODE REVIEW

**Comment by aknuds1** [comment]
Hi and thanks for your PR, but we won't provide official ppc64le packages at this time. Instead we suggest you create a feature request, so we can gauge eventual demand for it.

**Comment by kishen-v** [comment]
Hi @aknuds1, 
I see a discussion regarding the availability of official images for ppc64le arch (https://github.com/grafana/grafana/discussions/39583). Please let me know if I can have an issue created to track the feature request. 

Thank you.

**Comment by lehrig** [comment]
@aknuds1, I also think it is nowadays much easier to add another architecture; especially since you already build multi-arch images. Is there anything particular blocking this to move forward?

**Comment by eric-aquaronne** [comment]
Hello, I have IBM Power moving to Linux on Power asking me for this OR an alternative on Power. Can you revisit your negative response, if nothing happens by the summer, they will find an alternative on IBM Power

**Pull request closed without merging**
