### PR TITLE
Tempo: Update TraceQLStreaming feature toggle stage

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Updates TraceQLStreaming feature toggle stage.

### CODE REVIEW

**Review by 09jvilla — APPROVED** [review]
Approving. As I read the PR, this means that traceQL streaming will be on by default in Grafana 11. 

@joey-grafana , just to confirm, if the user is on Grafana 11 with TraceQL streaming enabled in Grafana but is using a version of Tempo that doesn't have streaming, what would happen? Would it break? or would it just not stream? Want to make sure we're messaging if there's a breaking change here appropriately.

**Review by knylander-grafana — APPROVED** [review]
Approving doc updates. Does this change require a changelog entry?

**Comment by 09jvilla** [comment]
^^ Heads up on the above @knylander-grafana for documentation purposes.

**Comment by joey-grafana** [comment]
> Ok so in Grafana 11 its marked as 'generally available', but is still off by default. Plan would then move to 'on by default' with feature flag removed in 11.1 I would think?

Yeah I think that's fair. We can even decide to toggle it on by default for all users (OSS, cloud, enterprise) in 11.1 and then completely remove the toggle in 11.2 as well if necessary but I'm happy with either approach :)

**Comment by 09jvilla** [comment]
> Yeah I think that's fair. We can even decide to toggle it on by default for all users (OSS, cloud, enterprise) in 11.1 and then completely remove the toggle in 11.2 as well if necessary but I'm happy with either approach :)

Sounds good. I don't feel strongly either way. Happy to defer to your judgement and/or wait till we get any more open source user feedback after the 11.0 release.

**Pull request merged**
