### PR TITLE
Chore: Update Inter font files

### PR DESCRIPTION
**Pull request by joshhunt**
Updates the Inter font files to the latest official versions from https://rsms.me/inter/.

Main reason for updating the files is to bring in proper tabular-numerals/tnum support, that was lacking in the original files from Google Fonts.

I initially went down the path of subsetting the fonts to create smaller files for individual character sets ([archived here](https://gist.github.com/joshhunt/2d3240c0d6ff722b9abebae09f23df75)) like we currently have, but there were a few reasons why I stopped doing this:

 - the files were not significantly smaller
 - the subsetting process broke some obscure font feature that we were unlikely to use anyway (such as `ccmp` substitutions) 
 - was a bunch of complication and maintance headache for marginal benefit

I also discovered that the font files we had before were actually Variable fonts, even though we were only using them for 400 and 500 weights. I've replaced these with individual static weights for smaller files, but if we add individual weights we should consider switching back to variable.

### CODE REVIEW

**Review by gillesdemey — APPROVED** [review]
Not sure why our team got tagged; but LGTM :shipit:

**Review by codeincarnate — APPROVED** [review]
Took a look at the storybook (which is great addition by the way) and looks good to me!

**Review by JoaoSilvaGrafana — APPROVED** [review]
Nice! 👏

**Pull request merged**
