### PR TITLE
Tooltip: New styles

### PR DESCRIPTION
**Pull request by Develer**
**What is this feature?**

The PR provides styles for new tooltip [designs](https://www.figma.com/file/tW8PMdzLb7hYYyBpb2xaYR/Universal-Tooltip).

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by adela-almasan** [comment]
Tested it with heatmap and xy and it looks good! 🎉 I noticed that the color indicator is not aligned with the header and the close button is also no longer aligned (noticed you removed the `top` property) - I think we should fix that before merging, just to keep it aligned with the design 😁

alignment

**Comment by Develer** [comment]
Looks like it applied incorrectly, it should be without gaps on top and additional padding for the whole tooltip.
e.g. here is the status history tooltip:
Screenshot 2023-10-24 at 10 27 42

I'll check 🙂

**Comment by Develer** [comment]
I've fixed the xy chart tooltips and aligned the close button. Let's check the heatmap together.
Screenshot 2023-10-24 at 13 43 02

**Review by adela-almasan — APPROVED** [review]
:star:

**Pull request merged**
