### PR TITLE
Cloudwatch: Convert go convey tests to standard test library

### LINKED ISSUE #20157: Cloudwatch: Convert go convey tests to standard test library
At the moment, all CloudWatch datasource backend tests are implemented using Go Convey. They should be rewritten using the go standard testing library. See https://github.com/grafana/grafana/blob/master/contribute/style-guides/backend.md#testing for more information.

### PR DESCRIPTION
**Pull request by mattheusv**
**What this PR does / why we need it**:
I changed all tests of `pkg/tsdb/cloudwatch` package to use standard library and testify following the documentation: https://github.com/grafana/grafana/blob/master/contribute/style-guides/backend.md#testing

**Which issue(s) this PR fixes**:

Fixes #20157

**Special notes for your reviewer**:
I tried to leave the descriptive tests as it was before with the go convey, so please let me know if any changes were not good enough.

### CODE REVIEW

**Comment by aknuds1** [comment]
Thanks for the PR. I found a lot of nits though, and fixed them locally. Do you mind if I push them to your branch?

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Thanks for taking care of this chore! I found many nits however. I fixed them locally, so with your permission, I'll push the fixes to your branch.

**Comment by msAlcantara** [comment]
No problem, I would like to see the improvements too.

**Comment by aknuds1** [comment]
@msAlcantara I don't have the permission to push to your branch: 

```
$ git push -u msalcantara HEAD
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 32 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 2.99 KiB | 2.99 MiB/s, done.
Total 14 (delta 11), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (11/11), completed with 8 local objects.
To github.com:msAlcantara/grafana.git
 ! [remote rejected]       HEAD -> chore/20157 (permission denied)
error: failed to push some refs to 'github.com:msAlcantara/grafana.git'
```

**Comment by msAlcantara** [comment]
I'm sorry for this. I gave access to my repository, can you try again? I don't think I've ever given access to another push to my repository, I'm sorry for that.

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by aknuds1** [comment]
@msAlcantara Sorry, it was actually my fault. I was pushing to the wrong branch.

**Comment by msAlcantara** [comment]
I changed the order of the parameters in the asserts ... Thanks for the review.

**Comment by aknuds1** [comment]
Thanks for the contribution!

**Comment by aknuds1** [comment]
With `assert.Equal`, the expected value should come before the actual value. That's why I changed the order around.

**Pull request merged**
