### PR TITLE
Draggable: only set drag handle props on the drag handle itself

### LINKED ISSUE #49867: Mixed datasource UI does not work in 9x
**What happened**:

In 9x, when you select "-- Mixed --" datasource, the dropdown to select datasource does not accept input 😬   (NOTE: the gif does not show me clicking lots on the dropdown!)

I can get the dropdown to open using `tab` and then arrows, but the mouse does not do anything.

**What you expected to happen**:

open on click

**How to reproduce it (as minimally and precisely as possible)**:

Use the mixed datasource

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- https://github.com/grafana/grafana/pull/49142 updated our version of `react-select`
  - this includes [this pr](https://github.com/JedWatson/react-select/pull/5134) which short circuits the `onControlMouseDown` function in `react-select` if `event.defaultPrevented = true`
- `react-beatiful-dnd` sets `event.preventDefault()` on it's drag handlers
- we were incorrectly spreading `dragHandleProps` onto elements that weren't the drag handles themselves, but instead the whole row.
- changed it to spread the props onto the correct elements.
  - this also makes it so that rows can no longer be dragged from anywhere, only the appropriate drag handle. 

**Which issue(s) this PR fixes**:

Fixes #49867 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by joshhunt — COMMENTED** [review]
Excellent job tracking down the cause of this and coming up with a _good_ fix! I want to demo this first to see what it's like in practice.

Not super in love with defining functions inline in (functional) components - a lot of the times it's just components within components, especially more so since the argument is called "props" 😅. Maybe we can just hoist this out to a component to this file?

**Comment by joshhunt** [comment]
Hmmm..... In practice, I think the drag handle is quite small _and_ awfully close to the no-confirm Delete button 

image


We could give the handle a bunch of padding and offset that with negative margins (to make the drag handle flush with the outer bounds of the row), and push it a bit away from the action buttons? 

image

(red bg mine, to show the target size)

quick inspector CSS:

```css
    padding: 7px;
    margin: -9px;
    margin-left: calc(16px - 7px);
```

**Review by gillesdemey — APPROVED** [review]
Works like a charm, LGTM! :shipit:

**Review by axelavargas — APPROVED** [review]
👏🏾

**Pull request merged**
