### PR TITLE
Make colorization of prefix and postfix optional in singlestat

### PR DESCRIPTION
**Pull request by ApsOps**
Some users may want to make #11143 optional.
Refer: https://github.com/grafana/grafana/pull/11143#commitcomment-28903249

image

### CODE REVIEW

**Comment by ApsOps** [comment]
Ping @bergquist :)

**Comment by dehrax** [comment]
Thanks for the PR!

I noticed this does not work if you have a gauge. You might want to have a look at https://github.com/grafana/grafana/blob/75e378b6890db29af708ff11dce580a0c3a3a54c/public/app/plugins/panel/singlestat/module.ts#L620
`getBigValueHtml()` is only called from that line. 

Some unit tests would also be nice! [Here you have the Jest tests for the singlestat panel](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/specs/singlestat_panel.jest.ts)

**Comment by ApsOps** [comment]
@dehrax Thanks! Looks like guage doesn't even support the font size options yet? The whole prefix+value+postfix comes as a single string. So I'd prefer to keep it in another PR.

I tried adding the testcases but not sure how to go about that. `applyColoringThresholds` is not an exported function, and it doesn't look straight-forward to export it and use in test cases.
Any pointers please :)

**Comment by dehrax** [comment]
@ApsOps You're correct! It seems to be the same problem as in #9884. I think making the checkboxes inactive when the gauge is activated would be a good alternative.

I am currently looking into the tests; it isn't very straight forward. I'll get back to you if I figure something out!

**Comment by ApsOps** [comment]
@dehrax Thanks! I'm making this change and the existing function [`canChangeFontSize()`](https://github.com/grafana/grafana/pull/10573/files#diff-e593190b57ddfe3f482e43e7b8248993R201) is making be uncomfortable. It returns `true` when gauge is enabled - which means it can't change font size! I see it's used with `ng-disabled` so value needs to be true, but it's just weird/confusing.

I don't think there's a `ng-enabled` directive, is there? Should we refactor this or should I just create another function called `canChangeColor()` and leave this for the future? :P

**Comment by dehrax** [comment]
@ApsOps Go ahead and refactor! :) Maybe rename it to `canModifyText()` and make it return the negated value of `panel.gauge.show`

**Comment by ApsOps** [comment]
@dehrax Done!

**Comment by dehrax** [comment]
Nice! Looks good to me! :)
@daniellee @bergquist Merge possible?

**Pull request merged**
