### PR TITLE
Docs: Update alerting provisioning example

### PR DESCRIPTION
**Pull request by maxlerebourg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gguillotte-grafana** [comment]
Deferring to @brendamuir - if `expression` is now `expr`, then does the `Data` property example in https://github.com/grafana/grafana/blob/main/docs/sources/developers/http_api/alerting_provisioning.md#-alertrule, which uses `expression`, also need updating?

**Comment by brendamuir** [comment]
@armandgrillet can you assign an engineer to help validate?

**Review by JohnnyQQQQ — CHANGES_REQUESTED** [review]
LGTM, but we should then also update the example in `conf/provisioning/alerting/sample.yaml`

**Comment by armandgrillet** [comment]
@maxlerebourg Can you update your PR following reviews or shall we close this?

**Pull request closed without merging**
