### PR TITLE
Dashboard: Add Max time range and Oldest 'From' settings

### PR DESCRIPTION
**Pull request by torkelo**
Continuation of work from https://github.com/grafana/grafana/pull/36384 

I could not push to the authors remote so had to open a new PR

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]
Looks great! A very useful feature @torkelo 👏🏻 @MukherjeeJeet

Should we limit the options in the time range picker to obey is preference, so invalid options are not shown?

e.g. I selected 30d as my max range, so "Last 6 months" should not be shown as an option as it exceeds this.

1405_2022-03-30-15-52_chrome

Would be fine if we addressed this in a separate PR.

**Comment by torkelo** [comment]
> Should we limit the options in the time range picker to obey is preference, so invalid options are not shown?

Yes, both the quick range options and calendar should resepect/limit so you cannot select a time range wider than max, dam I thought the original PR already had done that

**Comment by MukherjeeJeet** [comment]
> > Should we limit the options in the time range picker to obey is preference, so invalid options are not shown?
> 
> Yes, both the quick range options and calendar should resepect/limit so you cannot select a time range wider than max, dam I thought the original PR already had done that

ok I will try to do these

**Comment by kamakazikamikaze** [comment]
Any progress/updates on this?

**Comment by MukherjeeJeet** [comment]
I am busy in my current project. No update till now. Sorry for the inconvenience.

**Pull request closed without merging**
