### PR TITLE
CloudWatch Logs: "limit" query command now respected

### LINKED ISSUE #25182: CloudWatch Logs: "limit" parameter in Insights query ignored
**What happened**:
When using a simple CloudWatch Insights query with a limit parameter, the limit parameter is ignored, and more results are shown.

**What you expected to happen**:
Only show as many results as the limit requests.

**How to reproduce it (as minimally and precisely as possible)**:
 Query a log group over a time period that contains more than 20 entries, and use a limit parameter in the query, e.g.
```
fields﻿ ﻿@timestamp﻿,﻿ ﻿@message
|﻿ ﻿sort﻿ ﻿@timestamp﻿ ﻿desc
|﻿ ﻿limit﻿ ﻿20
```
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.1 (ef5b586d7d)
- Data source type & version: CloudWatch
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Mac OS 10.15.4, Chrome 83.0.4103.61
- Grafana plugins: NA
- Others: NA

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Previously the `StartQuery` action was dispatched with a default `limit` parameter of 1000, which seems to override any use of the `limit` command in a CloudWatch Logs query.
The `limit` parameter is now only used in the action payload if explicitly provided.

**Which issue(s) this PR fixes**:
Closes #25182

### CODE REVIEW

**Comment by aocenas** [comment]
> The limit parameter is now only used in the action payload if explicitly provided.

In what cases do we provide that?

**Review by aknuds1 — APPROVED** [review]
Looks good AFAICT.

**Comment by aknuds1** [comment]
@bergquist You know if this is a sensible change?

**Comment by aknuds1** [comment]
@kaydelaney Which milestone should this have? I removed the cherry-pick needed label, since we don't know if it's actually headed for cherry picking.

**Review by aocenas — APPROVED** [review]

**Pull request merged**
