### PR TITLE
Introduce alert debouncing

### LINKED ISSUE #6202: feature request: hysteresis for alerts
hysteresis is a very fancy word, but basically it means having a different condition to go from state B to A then the condition used to go from A to B.

for example, let's say i have an alert for latency, with a threshold at 1000ms.
if the number is fluctuating around 1000 (maybe 980->1010->990->1020-> etc), then each of those will trigger a change between critical and ok. constantly flapping.

with hysterisis I could say:
- go to critical when it goes over 1000ms
- only go back to normal when it goes under 900ms.

this way it won't flap.

### LINKED ISSUE #7886: Alerting - Flap detection
It would be nice to have some kind of flap detection. I got ~60 Email+SMS alerts over a 4 hour period

not sure how this would work, or if its possible.
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html
 
screen shot 2017-03-20 at 12 52 28

### PR DESCRIPTION
**Pull request by bergquist**
This PR introduces an option that will require an alert rule to be firing longer than the configured debounce duration before switching to alerting/sending notifications

closes #7886
closes #6202

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Did a code review. Some comments and probably a change needed related to database. Would like to test this out manually as well. But so far looks really good :+1:

**Review by marefr — COMMENTED** [review]
Did some simple tests on single Grafana instance to start with. That seems to work as expected :+1: 

However found some UI/UX related issues.

**Annotations:**
An annotation is rendered for each pending state - looks weird to me. Would it be possible to render a range annotation from alert rule became pending and to it became in alerting state? 
image

`No data` annotation doesn't look correct - should it render as annotation?
image

**Alert rules:**
Think we need to be able to filter by pending
image

**Alert list panel:**
Think we need to be able to filter by pending in the state filter
image

**Comment by marefr** [comment]
Think we need to do some changes to [alertmanager notifier](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/alertmanager.go#L53): 
* Handle For?
* Look at unkown instead of pending?

**Comment by bergquist** [comment]
- [ ] Make sure Alert manager notifier handles the new pending state
 - [ ] UI fixes for annotations
 - [ ] Alertlist
 - [ ] AlertListPanel

**Comment by marefr** [comment]
Have found one issue:
* Single instance of Grafana
* Alert rule, Evaluate every 10s For 1m
* Expected it to transition from OK -> Pending, but instead it transition from OK -> Alerting

image

**Comment by marefr** [comment]
Alertlist & AlertListPanel works as expected :+1:

**Comment by marefr** [comment]
Pushed fix for showing exclamation icon in annotation tooltip. It can be discussed whether panel titles should have other icons for NO_DATA/pending. No data right now looks like the alert rule haven't evaluated yet.

image

**Review by marefr — APPROVED** [review]
Tested with both single and multiple (HA) Grafana instances. Now alert debouncing works as expected and I've also verified that notifications and notification reminders are sent as expected.

**Pull request merged**
