### PR TITLE
Org: Fix redirection logic to work consistently

### LINKED ISSUE #96262: Port number 3000 added to URL when switching organization and connection time-out error
### What happened?

I recently updated to Grafana 11.2.3 and now I noticed that each time that I switch organization, the port number 3000 is added to the url (`https://mygrafana.com:3000/grafana/?orgId=10`) and I get a connection time-out error.

### What did you expect to happen?

Having a proper redirection.

### Did this work before?

Yes. v10.3.12.

### How do we reproduce it?

Grafana:
```
[server]
  2 protocol = https
  3 http_port = 3000
  4 domain = mygrafana.com
  5 root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
  6 serve_from_sub_path = true
```

Nginx:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream grafana {
  server localhost:3000;
}

server {

  server_name mygrafana.com;
  listen 443;
  ssl on;
  ssl_certificate /etc/grafana/grafana.crt;
  ssl_certificate_key /etc/grafana/grafana.key;
  charset UTF-8;
  root /usr/share/nginx/www;
  index index.html index.htm;

  location /grafana/ {
    proxy_set_header Host $http_host;
    proxy_pass https://grafana;
  }

  # Proxy Grafana Live WebSocket connections.
  location /grafana/api/live/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $http_host;
    proxy_pass https://grafana;
  }
}

server {
    if ($host = www.mygrafana.com) {
        return 301 https://$host$request_uri;
    }

    if ($host = mygrafana.com) {
        return 301 https://$host$request_uri;
    }

    server_name mygrafana.com;
    listen 80;
    return 404;
}
```

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: v11.2.3 (ecc4799abc)
OS: SUSE Linux Enterprise Server 15 SP5
Browser: Firefox132.0.1 (64-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by yincongcyincong**
Fixes #96262

i change `cfg.AppURL` to `cfg.AppSubURL`, bacause `cfg.AppURL` contain domain and port . it will change domain and port. if just redirect path, it's ok.

### CODE REVIEW

**Comment by yincongcyincong** [comment]
@dessen-xu bro, could you please take a look this pr?

**Comment by yincongcyincong** [comment]
@bergquist bro, could you please take a look this pr?

**Comment by yincongcyincong** [comment]
@tskarhed bro, could you please add some reviewer for this pr. there are two relative issure for this pr.

**Review by ashharrison90 — APPROVED** [review]
lgtm, thanks 🙌

**Comment by QuentinBisson** [comment]
Hey as an FYI it's highely likely this change caused this new issue https://github.com/grafana/grafana/issues/100599

**Comment by QuentinBisson** [comment]
@ashharrison90  Am I wrong to think the original issue could have been solved by setting the value of server.root_url to the actual external endpoint instead of using the default value?

**Pull request merged**
