### PR TITLE
remove button when click items on query builder

### LINKED ISSUE #73778: InfluxDB: Remove `remove` button when you click the items on query builder
Since we have this explicit delete button in place https://github.com/grafana/grafana/pull/72825, we don't need the `remove` buttons in the pop-up. 
It should be removed.

Image

### PR DESCRIPTION
**Pull request by siddhikhapare**
**What is this feature?**

Remove remove button when you click the items on query builder.

**Why do we need this feature?**

The remove buttons within the pop-up are unnecessary and should be eliminated.

**Which issue(s) does this PR fix?**: 

Fixes #73778 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by itsmylife** [comment]
Hi @siddhikhapare. Thanks for the PR. 
But unfortunately, the PR is addressing the wrong thing. The buttons you removed should stay. 
The thing it needs to be gone is the "remove" button in pop up. 
See:
image

**Review by itsmylife — CHANGES_REQUESTED** [review]
The wrong button was removed. The button in the pop-up when you click on a tag or filter must be gone

**Comment by siddhikhapare** [comment]
> Hi @siddhikhapare. Thanks for the PR. But unfortunately, the PR is addressing the wrong thing. The buttons you removed should stay. The thing it needs to be gone is the "remove" button in pop up. See: image

Okay. I will do it.

**Comment by siddhikhapare** [comment]
@itsmylife I have made PR. Please review it once. Thanks.

**Comment by itsmylife** [comment]
@siddhikhapare Thanks for the update but it is still not correct. We want this `remove` menu item removed from all possible places in influxdb components.
See: 
image

But in your PR you removed the close button. See:
image

We want to remove the `remove` menu item when you click for instance `mean()` function. Since there is a close button already we don't need the `remove`.

**Comment by siddhikhapare** [comment]
@itsmylife Thank you for your feedback. I'm really sorry I took so long to get back to this issue

**Comment by itsmylife** [comment]
@siddhikhapare Thanks for your time. I see you opened a new [PR](https://github.com/grafana/grafana/pull/76552) for this. So I am closing this one.

**Pull request closed without merging**
