### PR TITLE
Added metadata info panel

### PR DESCRIPTION
**Pull request by utkarshcmu**
Currently, info show created and updated time. But in the future it can show created by and updated by fields too. Also, this dropdown can be extended to show some other info also in the future.

### CODE REVIEW

**Comment by utkarshcmu** [comment]
This PR adds some features requested in #3047

**Comment by utkarshcmu** [comment]
Hover on info icon:
screen shot 2015-11-21 at 6 37 05 am

Click on info icon:
screen shot 2015-11-21 at 6 37 14 am

**Comment by torkelo** [comment]
not sure this deserves a top bar icon, maybe have the info in the dashboard settings

**Comment by utkarshcmu** [comment]
Thanks for the review, will make the change asap.

**Comment by utkarshcmu** [comment]
@torkelo Removed the top bar icon and included metadata in settings dropdown

**Comment by utkarshcmu** [comment]
New snapshots:

screen shot 2015-11-21 at 7 35 52 pm

screen shot 2015-11-21 at 7 35 57 pm

We will be putting more information(created by, updated by, etc) in metadata in the future so it is better to have a separate view for it as show above. :)

**Comment by utkarshcmu** [comment]
Haha, finally I can access this PR :) 

@torkelo Please review/merge this PR. Thanks.

**Comment by utkarshcmu** [comment]
Is there anything else I can do to get this PR merged? Would be great if we can get this info available in the next release.

Anyway, the next step in this direction will be adding Created by and Updated by fields. :)

**Comment by torkelo** [comment]
I was thinking that this info would go under a dashboard settings tab, and not a in the settings menu

**Comment by utkarshcmu** [comment]
screen shot 2015-12-02 at 4 18 08 am

Done. Please review/merge.

**Comment by utkarshcmu** [comment]
Should I add dashboard Id also or this information is sufficient right now to get this feature rolled out?

**Comment by utkarshcmu** [comment]
@torkelo Will this feature go into 2.6?

**Comment by Qtax** [comment]
@utkarshcmu the format is hard coded? I would at least prefer the international ISO 8601 format (24h time).

**Comment by utkarshcmu** [comment]
@Qtax yes the format is hardcoded right now. We can change it to whtever we want to. I am fine with any format if it shows up to a second's granularity. My main goal for this PR is to know when are these dashboards last modified and when were they created. Which will help us maintaining 100s of dashboards. The next step after this PR will be , who created them and who updated them. I ll try to include these two fields too asap in the same panel as time permits.

**Comment by utkarshcmu** [comment]
@torkelo What do you think about the hard coded format?

**Comment by bergquist** [comment]
The placement of such info is hard. If more info are to be added I think a special tab for it makes sense.

**Pull request merged**
