### PR TITLE
[WIP] Webpack 4

### PR DESCRIPTION
**Pull request by simPod**
Needs more testing

### CODE REVIEW

**Comment by davkal** [comment]
Yup, this is very early stages.

- `yarn start` is failing with `file-loader` related errors
- `yarn run watch` compiles, but page loads throws angular errors
- `yarn run build` worked, and loaded. Took 625s on my MBA (`master` currently takes 405s).

The chunk-related changes here will be needed when moving to webpack4, but I reckon the existing loader versions are causing errors. My suggestion is to upgrade loaders in a separate PR, since they they should be backwards-compatible. Then rebase and give this another run.

**Comment by davkal** [comment]
Rebased it, and tried it. But I'm still getting the angular errors in `yarn run dev` and `yarn start`. At least the file-loader issue is fixed. `yarn run build` still takes longer than in master.
(Couldnt push my rebase because the fork has member pushes turned off.)

I'll pause my work for now. Perhaps someone else want to give this a shot?

**Comment by simPod** [comment]
@davkal do you know when can I enable the member pushes? Searched repository settings but didn't find any.

**Comment by davkal** [comment]
See https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by simPod** [comment]
Weird, it's on the whole time 🤔 
image

**Comment by torkelo** [comment]
Had some merge conflicts that caused some strange error that I did not figure out, so opened new PR for this. https://github.com/grafana/grafana/pull/12098  with some comments on what is left to work on, I will not have more time to work on it this week so any help to continue on it would be helpfull, think it is close, just some more work on fixing the prod & minification stuff

**Pull request closed without merging**
