### PR TITLE
Azure Monitor: Fix autocomplete behaviour in cloud environments

### PR DESCRIPTION
**Pull request by ashharrison90**
**What is this feature?**

- setting a `cdn_url` and running locally, when switching to the code view in explore you can see that whilst monaco itself is loaded from the CDN url, kusto is just loaded from `/public/lib/...`
- thanks @jackw for spotting this - https://raintank-corp.slack.com/archives/C04BERE83D5/p1680102081908319?thread_ts=1680018713.713969&cid=C04BERE83D5 for context
- logging out `window.__grafana_public_path__` at the root of the kusto file shows it's `undefined` at this point
- comparing this to `ReactMonacoEditor` (which loads monaco), you can see this happens in an `initMonaco` function which is called from within a component
- by moving it inside the `loadKusto` function, we guarantee `window.__grafana_public_path__` is defined
  - can log this out and confirm it's now defined correctly 🥳 
- can't find a nice way to test the full thing locally... by setting a `cdn_url` in config, it fetches the built app from there as well so any local changes aren't picked up. any ideas? 🤔 

**Why do we need this feature?**

- so autocomplete works in cloud environments

**Who is this feature for?**

- anyone using the Azure Data Explorer or Azure Monitor data sources

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/support-escalations/issues/5348

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by jackw** [comment]
I took this PR for a spin locally. I'm sorry to say that whilst the scripts are now loaded from the CDN, the issue remains. 😞 

I've pushed a simple nginx docker setup to this branch that can be found in `devenv/local-cdn` which helped me test this. It will serve locally built assets which hopefully can help debug the issue better.

**Comment by joshhunt** [comment]
Ash and I have paired on this to try and troubleshoot this further and we're unclear what's happening. 

The best thought we have at the moment is that worker scripts have cross-origin restrictions on them that prevent the loading of additional. I would like to dig deeper and try to reproduce in an isolated environment (outside of grafana, with just generic worker scripts without kusto) to confirm suspicions.

**Comment by aangelisc** [comment]
On review I'd like to get this PR merged in with the change to the `kusto` loader. When looking in a HG instance the structure doesn't include the `grafana-assets` path: 
image

However, I hardcoded the `grafana-assets` path in the loader as below and everything loads fine:
image

I've also compared this to AzMG where the paths match as expected. It's only in HG that the paths are mismatched. I'm curious as to why the scenario @jackw set up fails but haven't had time to dig into it in greater detail.

**Comment by aangelisc** [comment]
> The best thought we have at the moment is that worker scripts have cross-origin restrictions on them that prevent the loading of additional. I would like to dig deeper and try to reproduce in an isolated environment (outside of grafana, with just generic worker scripts without kusto) to confirm suspicions.

FWIW I carried out the above and can 100% confirm now that the issue is CORs related (reaffirming what I found a few weeks back). We can close this PR and I'll continue to investigate if there's a way we can load the required scripts :/

**Pull request closed without merging**
