### PR TITLE
[v10.2.x] Docs: Update example docs for 

### PR DESCRIPTION
**Pull request by imatwawana**
Backport ad679c62c60efb51ab58829b7ff55e0fd4de3f59 from #86627

---

**What is this feature?**

Needed update to docs per issue #53362 

**Why do we need this feature?**

Docs are important, m'cay?

**Who is this feature for?**

All users

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by imatwawana** [comment]
@baldm0mma - When I backported this to 10.2, there were a bunch of changes that happened that stripped out alt text for some images. I updated the two typescript files and the changes from `generate-transformations.ts` are reflected in the markdown file, but not the changes from `content.ts` (lines 78, 345, 793, and 801). I'm not sure what I've done wrong. Can you take a look?

**Comment by baldm0mma** [comment]
> @baldm0mma - When I backported this to 10.2, there were a bunch of changes that happened that stripped out alt text for some images. I updated the two typescript files and the changes from `generate-transformations.ts` are reflected in the markdown file, but not the changes from `content.ts` (lines 78, 345, 793, and 801). I'm not sure what I've done wrong. Can you take a look?

I think I know the issue. It looks like the `buildImageContent` function back in 10.2 looks like this:
```
function buildImageContent(source: string, imageRenderType: ImageRenderType, imageName?: string) {
  return imageRenderType === 'shortcodeFigure'
    ? // This will build a Hugo Shortcode "figure" image template, which shares the same default class and max-width.
      `{{< figure src="${source}" class="docs-image--no-shadow" max-width= "1100px" >}}` <----- no "alt" prop
    : // This will build generic Markdown image syntax for UI rendering.
      `![${imageName} helper image](https://grafana.com${source})`;
}
```
But I added the alt prop in the markdown builder later:
```
function buildImageContent(source: string, imageRenderType: ImageRenderType, imageAltText: string) {
  return imageRenderType === 'shortcodeFigure'
    ? // This will build a Hugo Shortcode "figure" image template, which shares the same default class and max-width.
      `{{< figure src="${source}" class="docs-image--no-shadow" max-width= "1100px" **_alt="${imageAltText}"_** >}}`
    : // This will build generic Markdown image syntax for UI rendering.
      `![${imageAltText}](https://grafana.com${source})`;
}
```

**Comment by baldm0mma** [comment]
@imatwawana  I think I fixed it with manually updating some code. Building locally to assure. Can you double check to see if everything is indeed here you needed?

**Comment by imatwawana** [comment]
> @imatwawana I think I fixed it with manually updating some code. Building locally to assure. Can you double check to see if everything is indeed here you needed?

Yes this looks good to me!

**Review by baldm0mma — APPROVED** [review]
LGTM

**Pull request merged**
