### PR TITLE
Alerting docs: clean up Cloud links

### PR DESCRIPTION
**Pull request by ppcano**
This PR updates a few inconsistent `{{% docs/reference %}}` in Alerting docs.

1 - Cloud links are now always set up like  `[reference_name]: /docs/grafana-cloud/ -> /docs/grafana-cloud/xyz`

The issue with the previous setup was that if the Cloud URL was unavailable, the user was redirected to the OSS page. This may not be perceived and could be confusing.
 
Now, if the Cloud URL is not available, the CI/CD should catch the failure, and the tech. writer should fix the wrong link. 

2 - References to doc pages without a Cloud version are set up like:  `[reference_name]:  /docs/  -> /docs/grafana/<GRAFANA_VERSION>/xyz`

The benefit of using this pattern that it may be easy to find these references. Please, let me know if there is other preferred method.

### CODE REVIEW

**Comment by jdbaldry** [comment]
I'll need to update `doc-validator` on this branch because it is not aware of the new linking patterns. If you don't mind, I'll push a commit with that update.

**Comment by jdbaldry** [comment]
> The issue with the previous setup was that if the Cloud URL was unavailable, the user was redirected to the OSS page. This may not be perceived and could be confusing.

It's not that there was a redirect but that we explicitly wrote all the Cloud versions of the links to point at the OSS page to begin with with the intent that over time, they would be updated to the appropriate Cloud destination when links were reviewed.

There's no redirection involved, the link destinations are resolved by pattern matching at build time and use `relref` in the implementation so that the existence of the destination file is checked before the relative permalink for the destination file is  returned.

**Review by jdbaldry — APPROVED** [review]
:heart: thank you for this!

**Review by brendamuir — APPROVED** [review]

**Comment by brendamuir** [comment]
thank you, @ppcano!

**Pull request merged**
