### PR TITLE
Prototype adding time series query to Elasticsearch datasource

### PR DESCRIPTION
**Pull request by aheinz-sg**
Partial implementation of #1034. Needs some additional tweaks to query editor UI and deletion of unused copy pasta, but generally works with an acceptable response time. There is some tuning to be done on the ES side of things (such as using keyword analyzers for most strings), but I should have this running in production this week and will have better insight into performance.

### CODE REVIEW

**Comment by portante** [comment]
We wrote a shim of sorts to make an ES instance look like a graphite instance without changes to Grafana.

https://github.com/distributed-system-analysis/es-graphite-shim

**Comment by bechtoldt** [comment]
+1 for native ES support

**Comment by StefanSa** [comment]
also +1 for a native ES support

**Comment by aheinz-sg** [comment]
ATTN #1034 We haven't had any trouble running this in production for the last couple months, but the UI is still crude. Migrated deprecated facets to aggregations and also added group by ability.

**Comment by torkelo** [comment]
I have been working on elasticsearch support. I have not used much of this PR as almost all was pretty incomplete or nonfunctional. 

You can select multiple aggregations in single series (aggregations other than count need to be numbers datatype in elasticsearch). 

You can also add multiple group bys (nested terms in elasticsearch speak)

elasticsearch4

**Pull request merged**
