### PR TITLE
show error notification on flot error

### PR DESCRIPTION
**Pull request by mtanda**
Not developer can't notice error message output by "console.log".

### CODE REVIEW

**Comment by torkelo** [comment]
firstly you should use `scope.appEvent('alert-error', ['title', 'desc'])` instead of alertSrv directly.  

I am a bit hesitant to merge this, plot seems to throw some strange errors from time to time.

**Comment by mtanda** [comment]
> firstly you should use scope.appEvent('alert-error', ['title', 'desc']) instead of alertSrv directly.

Sorry, I know that. It's a mistake :-)

> I am a bit hesitant to merge this, plot seems to throw some strange errors from time to time.

I encounter flot error due to invalid dashboard json. Some flot option values become invalid value due to the invalid json, the graph isn't displayed correctly.
But, I don't want to confuse user.
If flot sometimes throw strange errors, we should not notify all error to user.

Maybe, adding error notification for dashboard migration is enough, so I'm OK to close this PR.

**Comment by torkelo** [comment]
found a better solution for this, https://github.com/grafana/grafana/commit/6a8c774dcc42fff845d7ae27ab39de9a57e3dcc9  

Shows error icon instead of popup, so if it's just a random error it will go away automatically

**Comment by mtanda** [comment]
Thanks for fix it!

**Pull request closed without merging**
