### PR TITLE
Stalebot: Automatically label PRs with no activity after 14 days as stale, then after 30 days close

### PR DESCRIPTION
**Pull request by torkelo**
need some help with good message texts when label is added and when the issue closed. 

Currently, these are exempt 
  - help wanted
  - type/bug
  - type/feature-request
  - Epic
  - no stalebot

possibly we want to close stale feature-requests?

inspired by: https://github.com/istio/istio/blob/master/.github/stale.yml 

another example: https://github.com/rails/rails/blob/master/.github/stale.yml

### CODE REVIEW

**Comment by marefr** [comment]
Great initiative. Is this marking stale when there's no activity at all in issue or only when author haven't answered in X days?

Regarding istio seems like they're not using GitHub actions and have a bot instead, see https://github.com/istio/istio/issues/15992#issuecomment-549002222 for example. The comment doesn't add up with what's configured.

`type/roadmap` should probably be added to exempt.

By installing the probot will the author of the commit be probot-stale bot or do we create a specific github user for that?

Should maybe add some stuff to the config:
```yaml
# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true
```

I'm still not convinced that closing feature requests is the way forward. Would like to wait with that.

**Comment by torkelo** [comment]
Looks like they switched to running a custom Probot themselves?

**Review by oddlittlebird — COMMENTED** [review]
Who are you addressing with this message? The language is very passive, so it is unclear who you are talking to. 

If I were talking directly to a contributor, I would say something like, "Are you still working on this? We have not logged any activity on this pull request in the last two weeks, so the system marked it as stale. Please feel free to give a status update now, ping for review, or re-open the PR when you're ready. This PR will be closed after 30 days of inactivity.

Thank you for your contributions!

**Comment by torkelo** [comment]
Perfect, feedback on the language of the message was exactly what I was looking for. ❤️ 

What about the close message: 
>  This pull request has been automatically closed because it has not had activity in the last 30 days. Please feel free to give a status update now, ping for review, or re-open when it's ready.
Thank you for your contributions!

**Comment by oddlittlebird** [comment]
I think the close message is fine as-is.

**Review by davkal — APPROVED** [review]
Great first step. Let's try it.

**Pull request merged**
