### PR TITLE
@grafana/ui: Replace various icons using Icon component

### LINKED ISSUE #23491: Old form styles label icon has wrong alignment
For some reason labels info icon is now left aligned:

image

### PR DESCRIPTION
**Pull request by ivanahuckova**
Fixes #23491

### CODE REVIEW

**Comment by torkelo** [comment]
Starred and Recent missing icons 
image

**Comment by torkelo** [comment]
Still issue with info icons in labels
image

**Comment by Clarity-89** [comment]
@ivanahuckova I've fixed the Recent and Starred icons in my Search branch so you can cherry pick [the commit](https://github.com/grafana/grafana/commit/dffbf73119b026bc91b393e0f255efa6b7b3f93c) if you want :)

**Comment by ivanahuckova** [comment]
@Clarity-89 thank you! 🙏 Cherry-picked. 🙂

**Comment by ivanahuckova** [comment]
@torkelo 
- tootltip icon being too close is fixed
image
- also missing icons are added (I have also tried out using orange and filled icon for star and I liked it. Let me know what do you think and I'll replace it if you don't like it. 🙂)
image

**Comment by torkelo** [comment]
Great job ivana! 

Screen Shot 2020-04-09 at 19 13 11

* Would prefer we skip the monochrome / colored icons here, looks a bit out of place. 
* The new dashboard icon makes no sense, looks like an add panel icon use regular dashboard icon instead. 
* For the find more dashboards on grafana.com use search icon for now

**Comment by torkelo** [comment]
hm.. maybe some color is nice :) 

What about our light blue95 color? 

Screen Shot 2020-04-09 at 19 17 28

**Comment by ivanahuckova** [comment]
> hm.. maybe some color is nice :)
> 
> What about our light blue95 color?


I like the blue95!

**Review by torkelo — APPROVED** [review]

**Pull request merged**
