### PR TITLE
Docs: Update canvas panel data links section with additional steps 

### PR DESCRIPTION
**Pull request by mellieA**
Add additional steps to the Data Links section needed to associate a field value with a data link. A dashboard data link (previously referenced) displays for all elements.

**What is this feature?**

Doc update 

**Why do we need this feature?**

The previous steps created a dashboard datalink that will display on all field/text elements

**Special notes for your reviewer**:

Researched this answering community post: https://community.grafana.com/t/clickable-links-in-canvas-panel-elements/82254

Tested on this demo dashboard: 

https://play.grafana.org/d/canvas-examples/panel-tests-canvas-examples?orgId=1&from=1678219129599&to=1678240729599

### CODE REVIEW

**Review by nmarrs — APPROVED** [review]
Looks great! Thanks for improving the docs and also providing a play dashboard to verify workflow with 💯

**Comment by imatwawana** [comment]
Hey @mellieA, a little late to the party, but I still wanted to provide feedback you asked for on that last section about the multiple elements. I'm pretty new and still trying learning the intricacies of what you can do with a panel, but I couldn't personally make the leap from those two sentences to the lovely steps you laid out in the Community post. In your opinion, is it reasonable to assume someone using this visualization would have a strong understanding of how to use transform options already or should we not be assuming that?

**Comment by mellieA** [comment]
@imatwawana I'm not sure either. From a docs perspective do you think it makes more sense to add the steps as they're written in the community post? I think an advanced user could make the leap, but a newer user might not.

**Comment by imatwawana** [comment]
> @imatwawana I'm not sure either. From a docs perspective do you think it makes more sense to add the steps as they're written in the community post? I think an advanced user could make the leap, but a newer user might not.

If you think a new user might not make that leap, then I'd say yeah, the steps should be added.

**Pull request merged**
