### PR TITLE
Explore: Fix timepicker when browsing back after switching datasource

### LINKED ISSUE #20933: Explore: Browsing back after switching datasource changes time picker
0. Explore with 2 prometheus datasources
1. Make sure time picker uses a relative time like Last 1h
2. Run a query in first promtheus
3. Run a query in second prometheus
4. Use browser button to go back

Result: Time picker now has an absolute range.
Expected: Time picker should keep relative range.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
Browsing back after switching datasource used to change time picker (see issue).

This issue was caused by suppling[ incorrect argument](https://github.com/grafana/grafana/blob/master/public/app/features/explore/state/actions.ts#L268) in `initializeExplore` function used in `refreshExplore`. This function requires `rawRange`, but `range` was supplied which resulted in the above mentioned bug. This PR fixes this. 

ezgif com-video-to-gif (20)

**Which issue(s) this PR fixes**:
Fixes #20933

### CODE REVIEW

**Review by Estrax — APPROVED** [review]
went out to be just a small change - LGTM.

**Review by davkal — APPROVED** [review]
Yup works great!

Since this is a bug fix, I would have liked to see some sort of improvement to make this less likely from happening again, either via stricter types or a test case.

**Comment by ivanahuckova** [comment]
@davkal @Estrax I have added stronger typing for `RawTimeRange`.

**Comment by davkal** [comment]
Since the fix uses the raw time range, should the payload types not change? See https://github.com/grafana/grafana/blob/d135f1229d0f9e463282efd73b2931aa31ff0f1d/public/app/features/explore/state/actionTypes.ts#L66

**Comment by ivanahuckova** [comment]
> Since the fix uses the raw time range, should the payload types not change?

`InitializeExplorePayload` with `range: TimeRange` was used in `InitializeExploreAction`. However, `InitializeExplore` that dispatched `InitializeExploreAction` expected `rawRange: RawTimeRange`. After discussion and guidance from @aocenas, I have changed `InitializeExplore` prop from `rawRange` to `range` to keep it consistent. 

This resulted in change in [Explore.ts](https://github.com/grafana/grafana/pull/21454/files#diff-81d11644057049047dc91bef44afc282) where instead of supplying `rawRange` as `initialRange`, we supply `range`.

**Pull request merged**
