### PR TITLE
Chore: Add missing tls_skip_verify_insecure for GitLab Oauth

### LINKED ISSUE #64648: [OAuth]TLS skip verify(GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE) environment option for GtiLab OAuth does not override defaults
**What happened**:

TLS skip verify environment option for GtiLab OAuth does not override defaults.
`GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: true`

- It is copy from Generic OAuth issue, see also:
  - https://github.com/grafana/grafana/issues/12747
    - https://github.com/grafana/grafana/pull/12748
    - https://community.grafana.com/t/tls-skip-verify-for-generic-oauth/9197

**What you expected to happen**:

TLS skip verify environment option for GtiLab OAuth does override defaults.
`GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: true`

GitLab Oauth can TLS skip verify (just like Generic Oauth).

**How to reproduce it (as minimally and precisely as possible)**:

- configure docker compose 
  - GitLab self-managed
    - enable https with self-signed cert
    - configure grafana oauth
  - Grafana
    - configure [GitLab oauth](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/gitlab/)
    - set enviroment variables `GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: true`

**Anything else we need to know?**:

At first glance it may look like a configuration issue (question), but if I set any bool in ini, I can override it correctly

**before editing grafana.ini**

- empty `[auth.gitlab]tls_skip_verify_insecure`

image

- login failed with error "x509: certificate signed by unknown authority"

image

```
2023-03-11 15:17:03 logger=context userId=0 orgId=0 uname= t=2023-03-11T06:17:03.543129033Z level=error msg=login.OAuthLogin(NewTransportWithCode) error="Post \"https://gitlab.example.com/oauth/token\": x509: certificate signed by unknown authority"
```

**after editing grafana.ini**

Now set `tls_skip_verify_insecure = false ` in `/etc/grafana/grafana.ini`, it could override it.
`[auth.gitlab]tls_skip_verify_insecure = true`

```2023-03-11 15:22:40 logger=settings t=2023-03-11T06:22:40.776628566Z level=info msg="Config overridden from Environment variable" var="GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE=true"
```

image

- login succeed.

```
2023-03-11 15:28:16 logger=oauth t=2023-03-11T06:28:16.698963314Z level=info msg="state check" queryState=ba3974f6afe34bd9a778c0fd268d1863c978922fee50b9aba8c23d60ab020d23 cookieState=ba3974f6afe34bd9a778c0fd268d1863c978922fee50b9aba8c23d60ab020d23
2023-03-11 15:28:17 logger=http.server t=2023-03-11T06:28:17.420056028Z level=info msg="Successful Login" User=admin@example.com
2023-03-11 15:28:17 logger=context userId=0 orgId=0 uname= t=2023-03-11T06:28:17.420126328Z level=info msg="Request Completed" method=GET path=/login/gitlab status=302 remote_addr=172.19.0.1 time_ms=731 duration=731.734288ms size=24 referer=https://gitlab.example.com/ handler=/login/:name
```

image

**Environment**:

- Grafana version: 9.4.3
- Data source type & version: none
- OS Grafana is installed on: alpine linux
- User OS & Browser: none
- Grafana plugins:
- Others:
  - use docker compose. see below:
  - Gitlab self-managed with self-signed cert.

```yaml
services:
  grafana:
    image: 'grafana/grafana:9.4.3'
    restart: always
    environment:
      GF_SERVER_ROOT_URL: https://grafana.example.com
      GF_AUTH_GITLAB_ENABLED: true
      GF_AUTH_GITLAB_ALLOW_SIGNUP: true
      GF_AUTH_GITLAB_CLIENT_ID: 174d59efb736621770baa45dd8a9a40689a24854fc4e99b74a869a863d8690c2
      GF_AUTH_GITLAB_CLIENT_SECRET: fc82b0c710a99cc9201d1687d9b38b7ddbb3dc4e6714a425e6bb78afcf37e599
      GF_AUTH_GITLAB_ROLE_ATTRIBUTE_PATH: is_admin && 'Admin' || 'Viewer'
      GF_AUTH_GITLAB_SCOPES: read_user,read_api
      GF_AUTH_GITLAB_AUTH_URL:  https://gitlab.example.com/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: https://gitlab.example.com/oauth/token
      GF_AUTH_GITLAB_API_URL:   https://gitlab.example.com/api/v4
      #  This variable only works when `tls_skip_verify_insecure = (true or false)` is present in the ini
      GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: true
```

- maybe
  - https://github.com/grafana/grafana/labels/area%2Fadmin%2Fuser
  - https://github.com/grafana/grafana/labels/area%2Fpermissions
  - https://github.com/grafana/grafana/labels/type%2Fbug

### PR DESCRIPTION
**Pull request by arukiidou**
**What is this feature?**

- Add missing tls_skip_verify_insecure for GitLab Oauth
  - support `GF_AUTH_GITLAB_TLS_SKIP_VERIFY_INSECURE: true`

**Why do we need this feature?**

- enable GitLab oauth with self-managed GitLab under self-signed cert

**Who is this feature for?**

- Self-managed GitLab user.

**Which issue(s) does this PR fix?**:

- Fixes #64648

**Special notes for your reviewer**:

- It is copy from Generic OAuth issue, see also:
  - https://github.com/grafana/grafana/issues/12747
    - https://github.com/grafana/grafana/pull/12748
    - https://community.grafana.com/t/tls-skip-verify-for-generic-oauth/9197

- I did not do these in this PR.  Please request if you need it in this PR.
  - 他の環境変数の追加
    - `GF_AUTH_GITLAB_TLS_CLIENT_CERT`
    - `GF_AUTH_GITLAB_TLS_CLIENT_KEY`
    - `GF_AUTH_GITLAB_TLS_CLIENT_CA`
    - `GF_AUTH_GITLAB_USE_PKCE`
  - 追記する https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#auth

- maybe
  - https://github.com/grafana/grafana/labels/area%2Fadmin%2Fuser
  - https://github.com/grafana/grafana/labels/area%2Fpermissions

### CODE REVIEW

**Review by chri2547 — COMMENTED** [review]
The docs look fine to me. Looking for Engr review and approval @IevaVasiljeva @linoman

**Comment by arukiidou** [comment]
@chri2547 
Just to be clear, please note that it is not just a change in documentation.
i have changed ini

If that is not a problem, thanks!

**Comment by chri2547** [comment]
> @chri2547 Just to be clear, please note that it is not just a change in documentation. i have changed ini
> 
> If that is not a problem, thanks!

Understood, I've tagged a couple of Engineers to also review. Thank you!

**Comment by linoman** [comment]
@arukiidou thank you for your contribution. This is definitely needed! We would love to include this in the documentation in order to raise awareness about the configuration options.

This behavior should be included under GitLab and GitHub docs since this is already available in [Generic Oauth docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-generic-oauth-authentication).

We can include the missing changes to your PR if you're ok with that, or you can include them yourself.

Thank you for your contribution!

**Comment by arukiidou** [comment]
>

> @arukiidou thank you for your contribution. This is definitely needed! We would love to include this in the documentation in order to raise awareness about the configuration options.
> 
> This behavior should be included under GitLab and GitHub docs since this is already available in [Generic Oauth docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-generic-oauth-authentication).
> 
> We can include the missing changes to your PR if you're ok with that, or you can include them yourself.
> 
> Thank you for your contribution!

Thanks your review, I got it.
Expand a bit,I want to add trust specific self-signed certificate, add enable [PKCE](https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce) 

CT
- GF_AUTH_GITLAB_TLS_CLIENT_CERT
- GF_AUTH_GITLAB_TLS_CLIENT_KEY
- GF_AUTH_GITLAB_TLS_CLIENT_CA
- GF_AUTH_GITLAB_USE_PKCE

**Comment by linoman** [comment]
@arukiidou Do you plan on adding more changes to your current PR? I'd suggest keeping the PRs as atomical as possible and just including the documentation changes and leaving all other changes for future PRs.

**Comment by arukiidou** [comment]
> @arukiidou Do you plan on adding more changes to your current PR? I'd suggest keeping the PRs as atomical as possible and just including the documentation changes and leaving all other changes for future PRs.

@linoman 

Following your recommendation, we will make no more changes here. Thank you!

PKCE and self-signed cert trusts make the following PR

**Comment by chri2547** [comment]
@linoman , are you ready to approve this PR? Does it need to be backported?

**Comment by arukiidou** [comment]
If you have something for me to do, let me know.

**Review by linoman — APPROVED** [review]
I missed this from my radar. I added the missing milestone and I'm approving this PR.

Thank you for your contribution @arukiidou

**Comment by linoman** [comment]
Thank you for the ping @chri2547!

**Pull request merged**
