### PR TITLE
Update documentation-style-guide.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Added "intro, introduction" to Word Usage.

### CODE REVIEW

**Review by marcusolsson — APPROVED** [review]
LGTM

**Comment by oddlittlebird** [comment]
@bergquist , any idea why the build-pipeline is still not completed? It's been over a day.

**Comment by aknuds1** [comment]
@oddlittlebird Try merging in latest master. That will hopefully fix it.

**Comment by bergquist** [comment]
merged master into your branch. Should be fine soon

**Pull request merged**
