### PR TITLE
Azure Monitor: Added Microsoft.Cdn/profiles to supported namespace list

### LINKED ISSUE #42743: Azure Monitor - Microsoft.Cdn/profiles resources not showing in the metrics query drop down
**What happened**:
I have a Azure Front Door Premium Resource ("Microsoft.Cdn/profiles") and would like to surface it's metrics (https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcdnprofiles) in Grafana. 

I have a Azure AD App Registration that has Contributor roles RBAC permissions to the subscription level to rule out a permissions issue. 

I have created a data source using the app registration details, interesting when I click save and test I get this:
image

I have created a dashboard, added a panel, selected the data source, selected the Azure Subscription from the drop down, select the resource group from the drop down. But when I come to select resource type or resource name. This is missing the Front Door resource. See below:

When I got to the Azure Resource Overview dashboard (I think this comes with Grafana out of the box right?) I correctly identifies the Microsoft.Cdn/profiles as being detected:
image
 
**What you expected to happen**:
I expect to see the Front Door resource (Microsoft.Cdn/profiles) and then select it's metrics as documented here: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcdnprofiles

**How to reproduce it (as minimally and precisely as possible)**:
- In Auzre - Create a Microsoft.Cdn/profiles resource (Front Door Standard/Premium NOT the old Front Door resource type)
- In Grafana - Wire up a Grafana Azure Monitor Data Source that can reach that resource
- Observe that you can't select the resource or it's metrics

**Anything else we need to know?**:
The Front Door resources Diagnostic Settings are pointing to a Log Analytics workspace in a separate subscription, working fine. I can't see how this would be an issue but flagging anyway. I've also tried increasing the RBAC permissions of the App Registration to included that separate subscription but that hasn't made a difference

**Environment**:
- Grafana version: v8.3.0 (914fcedb7)
- Data source type & version: Azure Monitor v0.3.0
- OS Grafana is installed on: Ubuntu 18.03-LTS
- User OS & Browser: Windows 10, FireFox 94
- Grafana plugins: Azure Monitor
- Others:

### PR DESCRIPTION
**Pull request by danijam**
Microsoft.Cdn/profiles is the Azure Front Door Standard/Premium resource which is not present in the supported namespaces. I would like to use it's platform metrics in Grafana.

**What this PR does / why we need it**:
I raised #42743 and discovered the supported namespace file that I have changed in this PR, which I am under the assumption will resolve this issue. It's needed otherwise the new Azure Front Door resource metrics can't be used with Grafana.

**Which issue(s) this PR fixes**:
Fixes #42743 

**Special notes for your reviewer**:
I don't know if any other changes are required, please do advise.

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
Thanks for the PR @danijam ! Taking a look to the documentation, it seems that [Microsoft.Cdn CdnWebApplicationFirewallPolicies](https://docs.microsoft.com/en-us/azure/templates/microsoft.cdn/cdnwebapplicationfirewallpolicies?tabs=bicep) is another possible metric namespace, can you add it too?

Also, can you add the metrics to the rest of clouds below? (govazuremonitor, germanyazuremonitor...).

**Comment by danijam** [comment]
> Thanks for the PR @danijam ! Taking a look to the documentation, it seems that [Microsoft.Cdn CdnWebApplicationFirewallPolicies](https://docs.microsoft.com/en-us/azure/templates/microsoft.cdn/cdnwebapplicationfirewallpolicies?tabs=bicep) is another possible metric namespace, can you add it too?
> 
> Also, can you add the metrics to the rest of clouds below? (govazuremonitor, germanyazuremonitor...).

Thanks @andresmgot, On inspecting the Azure Monitor supported resource page it is indeed available as `Microsoft.Cdn/cdnwebapplicationfirewallpolicies` see https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcdncdnwebapplicationfirewallpolicies

Happy to add although the only oddity is there is only 1 Metric exposed under the namespace `Microsoft.Cdn/cdnwebapplicationfirewallpolicies` yet the same metric seems to appear under `Microsoft.Cdn/profiles` namespace. See metric name `WebApplicationFirewallRequestCount` is defined in both in the above docs page.

**Comment by danijam** [comment]
@andresmgot done

**Review by andresmgot — APPROVED** [review]
Thanks for checking!

**Comment by danijam** [comment]
@andresmgot Thanks. If I wanted to consume a build (not one I've built) does this merged change to branch main end up in your nightly builds? https://grafana.com/grafana/download/nightly?platform=docker

**Comment by andresmgot** [comment]
yes, that will be part of the nightly build (or `grafana/grafana:main`)

**Pull request merged**
