### PR TITLE
Logs Navigation: Scroll to first log when using pagination

### LINKED ISSUE #61842: Explore logs: Click on older/newer logs and pages should take you to the top of the logs
**What happened**:

Feedback from slack:

Older logs button works in the strange way. After clicking it, users are moved to the bottom of new downloaded logs, when it should be the opposite. So when user finishes checking oldest logs and wants to see more logs, button should move user to the freshest part of older logs. 

Screnshot:
image

### PR DESCRIPTION
**Pull request by matyax**
This PR adds a new behavior when clicking on the logs navigation buttons (newer logs, logs pages, and older logs), to reset the scroll to the first log. This allows users to have a slightly enhanced workflow when looking for logs, by being taken to the first log of the updated log list.

This has been achieved by keeping a new reference to the start of the logs list, and reset the scroll to that position on every pagination change. This was done to keep the viewport focused on the log list, so the user can continuosly see the pagination buttons (newer, older):

imagen

Otherwise, if we use the original scroll to top reference, the pagination is partially displayed (or partially hidden):

imagen

The other reference remains unchanged for the "scroll to top" button, which scrolls to a slightly higher position.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/61842

**Special notes for your reviewer:**

Old behavior:

In the current version, when the user uses pagination, they have to manually scroll to the top to see the new first log.

https://user-images.githubusercontent.com/1069378/230944627-12562060-7256-4173-a03f-86247a158345.mov

In the update version, when the user uses pagination, the viewport is reset to the start of the list, allowing users to see the first log, while the pagination controls continue to be visible.

New behavior:

### CODE REVIEW

**Review by ivanahuckova — COMMENTED** [review]
We already have `topLogsRef` used for scroll on the top of the logs button. Can't we just reuse/adjust that?

**Comment by matyax** [comment]
@ivanahuckova I tried to explain it in the description. If I use that reference, it takes the user to above the list of logs, to the list controls, and it hides the "older logs" button:

imagen

The new reference points to the start of the list of logs, and keeps the pagination controls in display:

imagen

I could change the reference of the "scroll to top" button, but it will affect the current behavior of going to the controls, which might be helpful/expected.

**Comment by ivanahuckova** [comment]
> I could change the reference of the "scroll to top" button, but it will affect the current behavior of going to the controls, which might be helpful/expected.

I would do that rather than having 2 almost same functionalities. The difference is so small, that I would rather include it in the changelog, than having code for both of these functionalities.

**Comment by matyax** [comment]
Alright, let's do that. Thanks!

**Comment by ivanahuckova** [comment]
@matyax What do you think about adding div with ref above `<LogsMetaRow>` to make it more clear that we scrolled to the top of the view? That way, we have all buttons, but we also see that we are on the top of the log rows. 

image

**Comment by matyax** [comment]
Sure.

**Review by ivanahuckova — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
