### PR TITLE
Alerting: Change settings column type to mediumtext

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
Fixes `Error 1406: Data too long for column 'settings'` error (reported from HG customer) when trying to save a dashboard that contains an alert that exceeds the settings column size.

This fix introduces a database migration for MySQL  (similar to the [modification](https://github.com/grafana/grafana/blob/41d432b5ae68c0fc2261e607289206b79410fcfa/pkg/services/sqlstore/migrations/dashboard_mig.go#L93) made for the `data_source.data` column) that changes the settings column type from `text` to `mediumtext`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
If have tested with `mysql`, `sqlite`, `postgres`. (This migration applies only to `mysql` database; other databases should not be affected)

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
Any idea if the front-end test failure in CI is connected to your change?

**Comment by papagian** [comment]
> Any idea if the front-end test failure in CI is connected to your change?

I don't know; I have rerun it and it was successful this time.

**Comment by aknuds1** [comment]
@papagian OK so it was just a flake. It didn't immediately look like a flake to me, so had to ask.

**Comment by papagian** [comment]
> @papagian OK so it was just a flake. It didn't immediately look like a flake to me, so had to ask.

It does not contain any frontend modifications anyway

**Comment by aknuds1** [comment]
@papagian Yeah, I just wondered if the failing test might be invoking back-end somehow :)

**Pull request merged**
