### PR TITLE
Alerting: Make regex notification routing preview consistent with notification policies implementation

### PR DESCRIPTION
**Pull request by tomratcliffe**
**What is this feature?**

When previewing notification routing for an alert rule on the create/edit page, regex matching was inconsistent.

With a regex matcher of `foo ~= bar`, in AM, this wouldn't match against a label/value of `foo = somethingbar` on the notification policies page. However, our preview of the routing on the alert page would say that this _does_ match. 

This is because our UI implementation of the check wasn't anchoring the regex, but alertmanager does anchor the match: https://github.com/prometheus/alertmanager/blob/fd37ce9c95898ca68be1ab4d4529517174b73c33/pkg/labels/matcher.go#L69

**Why do we need this feature?**

Consistency of alerting routing/matching between the notification policies page and the alert rule create/edit pages

**Who is this feature for?**

Alerting users

### CODE REVIEW

**Comment by gillesdemey** [comment]
I'd love to also see a test added to `matchLabels` or `isLabelMatch` with some simple regex scenarios for anchoring

Something akin to this perhaps

```
it('should not match unanchored regular expressions', () => {
    const labels: Label[] = [['foo', 'barbarbar']];
    const matchers: ObjectMatcher[] = [['foo', MatcherOperator.regex, 'bar']];

    expect(matchLabels(matchers, labels)).toHaveProperty('matches', false);
  });
```

**Review by gillesdemey — APPROVED** [review]
Code changes LGTM but would love to see a simple regression test :)

**Comment by tomratcliffe** [comment]
:+1: I've added this in now. I'm also implicitly testing this behaviour in the other test of the notification routing preview - that test fails when you revert the fix in here

**Review by gillesdemey — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
