### PR TITLE
Revert "Add metrics for AWS/ElasticBeanstalk"

### PR DESCRIPTION
**Pull request by bergquist**
Reverts grafana/grafana#5195

### CODE REVIEW

**Comment by nitrag** [comment]
Hey, why the revert?

**Comment by mtanda** [comment]
@bergquist I think you should explain why you revert this...

**Comment by mtanda** [comment]
Ah, sorry, I misunderstand. you don't revert.
This PR is closed before merge.

**Comment by bergquist** [comment]
@nitrag @mtanda Sorry about the confusion! Creating this PR was a mistake :(

**Pull request closed without merging**
