### PR TITLE
chore: Remove gh-form and LegacyForms from InfluxInfluxQLConfig

### PR DESCRIPTION
**Pull request by papidb**
**What is this feature?**
Remove gh-form and LegacyForms from InfluxInfluxQLConfig

[Add a brief description of what the feature or update does.]

Before: 
image

After: 
image

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #
#76107 and #65513

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by itsmylife** [comment]
Hi @papidb thanks for your contribution. The `InlineField` and `InlineRow` components are going to be deprecated. So could you please update your PR without them? You can check [this PR](https://github.com/grafana/grafana/pull/76038) as an example.

**Comment by papidb** [comment]
Hi @itsmylife, I'm unable to find components in the [PR](https://github.com/grafana/grafana/pull/76038) you provided or the [UI library](https://developers.grafana.com/ui/latest/index.html) that displays the same way the page is meant to show without using `InlineField`, `InlineFieldRow`.

**Comment by itsmylife** [comment]
@papidb Yes the display will be different and that's ok. We just need to use `FieldSet` and `Field`

**Comment by papidb** [comment]
> @papidb Yes the display will be different and that's ok. We just need to use `FieldSet` and `Field`

Okay.

**Comment by papidb** [comment]
Hi @itsmylife I've updated the pr to use Field, please can you review the pr.

**Comment by itsmylife** [comment]
This is after the latest changes. There is `InlineLabel` @catherineymgui is this ok or should we also **not** use it?
image

**Review by itsmylife — APPROVED** [review]
LGTM

**Pull request merged**
