### PR TITLE
Update CloudWatch metrics/dimension list

### PR DESCRIPTION
**Pull request by mtanda**

### CODE REVIEW

**Comment by bergquist** [comment]
Argh. These diffs. 
Did someone do any work of fetching them from cloudwatch from some api?

**Comment by mtanda** [comment]
I scrape official docs by this script.
https://github.com/grafana/grafana/pull/16102/commits/05627ae8fc449a92aff4beace53383de8d9d91a1

**Comment by mtanda** [comment]
And, I sort and dedupe the keyword list.

I check the keyword list by following commands, compare keyword list for each namespace, and confirm that I don't remove the keyword.
I fix a namespace, `KMS` => `AWS/KMS`, some keyword appears in check script output, but the output is expected.

```
❯ metrics_diff=$(git diff 0091b86e9cff903784618649f3b744c76575cd6c..0634373b33e1017a49a5b4b02554fe9bdb88e225 -- pkg/tsdb/cloudwatch/metric_find_query.go | grep -B 10000 dimensionsMap)
for namespace in $(echo $metrics_diff | grep -o '"[^"]*":'); do
echo --- $namespace ---
diff <(echo "$metrics_diff" | grep $namespace | grep '^-' | grep -o '"[^"]*"' | sort | uniq) <(echo "$metrics_diff" | grep $namespace | grep '^\+' | grep -o '"[^"]*"' | sort | uniq)
done | grep '^<'
< "KMS"
< "SecondsUntilKeyMaterialExpiration"
```

```
❯ dimensions_diff=$(git diff 0091b86e9cff903784618649f3b744c76575cd6c..0634373b33e1017a49a5b4b02554fe9bdb88e225 -- pkg/tsdb/cloudwatch/metric_find_query.go | grep -A 10000 dimensionsMap)
for namespace in $(echo $dimensions_diff | grep -o '"[^"]*":'); do
echo --- $namespace ---
diff <(echo "$dimensions_diff" | grep $namespace | grep '^-' | grep -o '"[^"]*"' | sort | uniq) <(echo "$dimensions_diff" | grep $namespace | grep '^\+' | grep -o '"[^"]*"' | sort | uniq)
done | grep '^<'
< "Version"
< "service class"
< "KMS"
< "KeyId"
< "Version"
< "service class"
```

**Comment by mtanda** [comment]
@bergquist This change shouldn't break anything, would you merge this for 6.1 release?

**Pull request merged**
