### PR TITLE
Units: Fixed VAr (Volt-Ampere reactive), VA and kVA capitalization

### PR DESCRIPTION
**Pull request by sebashb**
As the title suggest this PR fixes the casing for the Volt-Ampere reactive units. Volt and Ampere must begin with an upper case letter and the the same applies to the SI symbol VAr and kVAr.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Review by leventebalogh — APPROVED** [review]

**Review by ashharrison90 — APPROVED** [review]
lgtm 🙌

**Comment by sebashb** [comment]
I found a few more typos in the VA and kVA units also.

**Comment by sebashb** [comment]
I see that version 8.3.4 with this fix has been released but after updating I'm still seeing the old unit capitalization. Did I forgotten to fix it somewhere else?

**Comment by ashharrison90** [comment]
hi @sebashb 👋 

this is targeted for 8.4.0, so won't have gone out in the 8.3.4 release.
it will be coming soon™️ 😄

**Comment by sebashb** [comment]
Hi @ashharrison90 

Ohh my bad!

**Pull request merged**
