### PR TITLE
added a css uniqueness for css selectors

### PR DESCRIPTION
**Pull request by kkoehler**
Hi,

we want to "initegrate" Grafana in our Web-application but encountered problems regarding the css "namespace". There are some CSS selector name clashes which causes grafana not to be rendered correctly in our environment.

The patch adds a "global" CSS prefix to all classes within the grafana CSS file (with help of the  the 'grunt-css-selectors' grunt plugin).

Not sure if the global 'id' or a global 'class' should be preferred... This would be a small change to adjust ;-)

For grafana itself the change is not visible and handeled transparently, but for applications integrating or planning to integrate grafana it is necessary. ;-)

Thanks,
Kristian

### CODE REVIEW

**Comment by torkelo** [comment]
Integrate how? Not sure about this PR, sorry but seems like a use case that is beyond what I want to support :(

**Comment by kkoehler** [comment]
Hi,

i suspected to hear that ;-) 

The idea is to integrate parts of Grafana in our "application frame" where we have a menu, footer, header, etc.- our styling, our CSS.

For example we'd like to add a dashboard to our applcation without "losing" the application context (no we don't want iframes).
I uploaded a sample screen to the project.

As said before, for grafana this is a small thing, which can help us a lot.. ;-)

Thanks,
Kristian

**Comment by torkelo** [comment]
@kkoehler in what way do you integrate grafana? Most grafana components require the grafana backend.

**Comment by kkoehler** [comment]
"Answer" here:
https://groups.io/org/groupsio/grafana/thread/integrate_grafana/62899?threado=0

;-)

**Comment by torkelo** [comment]
Responded on email list

**Pull request closed without merging**
