### PR TITLE
Add ethereum as option for currency value

### PR DESCRIPTION
**Pull request by Tocard**
This PR simply add ethereum cryptocurrency as option for currency panel's field

### CODE REVIEW

**Comment by oscarkilhed** [comment]
Unless I'm mistaken, **Ether** is the cryptocurrency of the **Ethereum block chain**.

**Comment by Tocard** [comment]
> Unless I'm mistaken, **Ether** is the cryptocurrency of the **Ethereum block chain**. The name of the unit should probably be Ether.

that's totally exact, here his the patch.

**Review by oscarkilhed — APPROVED** [review]

**Review by osg-grafana — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Not sure we accept additional currencies now when there's support for custom units. @torkelo thoughts?

**Comment by torkelo** [comment]
yea, you can add any currency symbol with a custom unit

**Pull request closed without merging**
