### PR TITLE
Tooltip Plugin: Prevent Tooltip render if field is undefined

### LINKED ISSUE #35953: Time Series: Cannot read property 'type' of undefined
**What happened**: Zooming in or out, or changing time ranges, causes the Time Series panel to error with:

```
TypeError: Cannot read property 'type' of undefined
    at Fc (TooltipPlugin.tsx:164)
    at na (react-dom.production.min.js:157)
    at Ba (react-dom.production.min.js:180)
    at Uu (react-dom.production.min.js:269)
    at Os (react-dom.production.min.js:250)
    at _s (react-dom.production.min.js:250)
    at ws (react-dom.production.min.js:250)
    at ds (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

In react-dom.production.min.js:216 

The graph does not render until a reload of the page happens.

**What you expected to happen**: No error. Graph displayed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.2 (5c5d45e19f)
- Data source type & version: Loki
- OS Grafana is installed on: Docker alpine
- User OS & Browser: MacOS - Chrome Version 91.0.4472.106 (Official Build) (x86_64)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

the problem occurs when you're viewing a graph with multiple series, and you zoom into a region of the graph where some of the series don't occur. in that case, there's a possibility that the `focusedSeriesIdx` is could be out of range of the `data.fields` array in [this code](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L136).

this PR is sort of a band aid fix, basically just not to render the tooltip if that occurs. 
we _could_ also try to detect when the data changes, and adjust the `focusedSeriesIdx` to the new value. but i'm not sure how we'd do that as there doesn't seem to be a unique identifier for each series, and it would require keeping the old data around i think.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/35953

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dprokop** [comment]
@ashharrison90 can you provide a dashboard agains which I can test it? I'm struggling getting this error to occur on main

**Comment by torkelo** [comment]
@dprokop I can replicate it quite easily in Explore, with gdev-testdata set to Logs scenario. Then try to zoom in using graph time region selection. It does not happen every time. But need to move the mouse over the graph as it you zoom in / after. If it does not happen reset time range to 6h and try again 

Screenshot from 2021-07-05 15-28-44

**Comment by ashharrison90** [comment]
another way to simulate:

- use gdev-testdata random walk
- set the series count to 10
- set the tooltip mode to all
- click into the series count input
- hover the timeseries plot so the tooltip is visible
- press backspace so you change the series count from 10 -> 1
- 💥 

it's not very realistic, but it's the same underlying cause i think

**Comment by dprokop** [comment]
@ashharrison90 I've had time to take a look at this. It's a config vs aligned data mismatch that can happen for a (single) render when number of series changes. I think we don't really need to check whether or not the focused index is within the range (it can be, yet point to a different field).

I think checking ainst field existence should be enough for this to mitigate the error being thrown:

```diff --git a/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx b/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx
index 1c4a84785c..e9d4a6e66a 100644
--- a/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx
+++ b/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx
@@ -45,7 +45,6 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
   const [focusedPointIdx, setFocusedPointIdx] = useState<number | null>(null);
   const [coords, setCoords] = useState<CartesianCoords2D | null>(null);
   const plotInstance = plotCtx.plot;
-
   const pluginId = `TooltipPlugin`;
 
   // Debug logs
@@ -135,6 +134,10 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
     if (mode === TooltipDisplayMode.Single && focusedSeriesIdx !== null) {
       const field = otherProps.data.fields[focusedSeriesIdx];
 
+      if (!field) {
+        return null;
+      }
+
       const fieldFmt = field.display || getDisplayProcessor({ field, timeZone, theme });
       const display = fieldFmt(field.values.get(focusedPointIdx));
 
@@ -160,6 +163,7 @@ export const TooltipPlugin: React.FC<TooltipPluginProps> = ({
         const frame = otherProps.data;
         const field = frame.fields[i];
         if (
+          !field ||
           field === xField ||
           field.type === FieldType.time ||
           field.type !== FieldType.number ||
```

https://gist.github.com/dprokop/28548c37407e8b3b4d3d8617e064245e

**Comment by ashharrison90** [comment]
@dprokop have made the changes 👍

**Review by dprokop — APPROVED** [review]

**Pull request merged**
