### PR TITLE
(prometheus) fix label_values() templating

### LINKED ISSUE #4177: Prometheus templating: label_values can not deal with multiple label selectors
When using label helper functions in templating it's not possible to use multiple label selectors. The problem is that functions like `label_values` do not expect the metric to include any commas, which is valid though.

Examples:
* `label_values(my_metric{static="some value", dynamic="$dynamic"}, new_label)`
* `label_values(my_metric{label1="$label1", label2="$label2"}, label3)`

The regular expression `label_values_regex` needs to be changed to not split the expression on comma.

@mtanda

### PR DESCRIPTION
**Pull request by mtanda**
fix https://github.com/grafana/grafana/issues/4177

### CODE REVIEW

**Comment by grobie** [comment]
:+1: Looks great!

**Comment by mtanda** [comment]
Thanks for testing!

**Comment by mtanda** [comment]
@torkelo This is bug fix. Would you merge this?

**Comment by torkelo** [comment]
Yes, of course :)

**Comment by mtanda** [comment]
thanks!

**Pull request merged**
