### PR TITLE
API: Fix logging of dynamic listening port

### LINKED ISSUE #16709: Log Real Http Port
**What would you like to be added**:
When using a dynamic port for grafana server, the real port should be printed to the logs instead of 0. Setting the http port to 0 in the custom.ini file means the port will be dynamically allocated. The problem is that instead of logging the real port allocated, 0 is logged.

**Why is this needed**:
This is needed for a more reliable and cross-platform way to get the port of the running grafana server.

https://github.com/grafana/grafana/blob/532abe2fc2301ce8d87f5625e94316cbc779fedb/pkg/api/http_server.go#L81

### PR DESCRIPTION
**Pull request by oleggator**
**What this PR does / why we need it**:
This pr fixes logging of dynamic listening port
**Which issue(s) this PR fixes**:

Fixes #16709 

**Special notes for your reviewer**:

Before:
```
INFO[10-06|13:29:07] HTTP Server Listen    logger=http.server address=0.0.0.0:0 protocol=http subUrl= socket=

```

Now:
```
INFO[10-06|13:15:59] HTTP Server Listen    logger=http.server address=[::]:63187 protocol=http subUrl= socket=
```

### CODE REVIEW

**Comment by marefr** [comment]
@oleggator Thanks. This looks good and seems to work as expected :+1: The only one thing I'm worried/unsure about is whether TCP keepalives is enabled or not. Using the `ListenAndServe on go 1.12 wraps listener in a `tcpKeepAliveListener` ([code](https://github.com/golang/go/blob/release-branch.go1.12/src/net/http/server.go#L2797)) which in turn calls `Serve` ([code](https://github.com/golang/go/blob/release-branch.go1.12/src/net/http/server.go#L2838)) which is used in this PR instead of `ListenAndServe`. 

We're on go 1.13 now and the `tcpKeepAliveListener` seems to have been removed ([code](https://github.com/golang/go/blob/release-branch.go1.13/src/net/http/server.go#L2825)) and based on [changelog](https://golang.org/doc/go1.13#net) is should be enabled per default. Just wanted to hear if you any thoughts/knowledge to this?

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
@oleggator Thank you for contributing to Grafana!

Totally optional, but may I ask you if you're participating in Hacktoberfest and whether you've find this issue through the hacktoberfest label? Trying to find out if new contributors are finding Grafana due to Hacktoberfest.

**Comment by oleggator** [comment]
@marefr Sorry for late answer.

As I see in [go 1.13 sources](https://github.com/golang/go/blob/release-branch.go1.13/src/net/http/server.go#L2805) `Server.ListenAndServe` uses `Server.Serve` with ordinary `net.Listener` and keep-alives are enabled by default.

I participated in Hacktoberfest and found this issue through `hacktoberfest` label.

**Pull request merged**
