### PR TITLE
Docs: Add cloud label to doc articles

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
**What is this feature?**

Adding cloud label to some doc pages where it was missing.

### CODE REVIEW

**Review by aarongodin — APPROVED** [review]

**Review by jdbaldry — COMMENTED** [review]
Thanks for the contribution! 

To help me review, would you be able to provide a little more context in the description explaining which parts of the topic relate to cloud or if the topics are generally appropriate for cloud.

**Comment by jdbaldry** [comment]
> Thanks for reviewing @jdbaldry! Everything under [grafana.com/docs/grafana/latest/administration/roles-and-permissions](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/) (including the page itself) also applies to cloud. Similarly, service accounts are a feature that's usable in cloud, so I think we should have a cloud label on [grafana.com/docs/grafana/latest/administration/service-accounts](https://grafana.com/docs/grafana/latest/administration/service-accounts/) page.

Awesome, thanks for confirming. I think these pages should definitely have that label

**Review by jdbaldry — APPROVED** [review]

**Comment by ppcano** [comment]
@jdbaldry,  I was wondering where these will pages be available in the [Grafana Cloud docs](https://grafana.com/docs/grafana-cloud/)? Asking because I didn't find any pages from the `Administration` category in the Grafana Cloud docs.


Screenshot 2024-08-19 at 23 50 55

**Comment by jdbaldry** [comment]
> @jdbaldry, I was wondering where these will pages be available in the [Grafana Cloud docs](https://grafana.com/docs/grafana-cloud/)? Asking because I didn't find any pages from the `Administration` category in the Grafana Cloud docs.
> 
> Screenshot 2024-08-19 at 23 50 55

Labeling isn't currently used to generate Grafana Cloud mounts though it was a considered possibility when we introduced labels originally.

Presently, mounts are defined manually in https://github.com/grafana/website/blob/master/config/_default/config.yaml#L173.

I think we'd need to start a thread in the #docs Slack channel to organize adding Administration content to Grafana Cloud.

**Pull request merged**
