### PR TITLE
[8.0.x]Plugins: Remove support for deprecated backend plugin protocol version

### LINKED ISSUE #33959: Backend plugins: Remove support for deprecated backend plugin protocol (v1)
**What would you like to be added**:
Remove support for deprecated backend plugin protocol (v1) including all code referencing github.com/grafana/grafana-plugin-model.

**Why is this needed**:
We did archive https://github.com/grafana/grafana-plugin-model and deprecated [plugin protocol version 1](https://github.com/grafana/grafana/blob/a015bb3a23d13a13429014a6efbdfc4678e04f11/pkg/plugins/backendplugin/grpcplugin/client_v1.go#L22-L23) for Grafana v7 and now it's time to remove it completely. 

For example the following files needs to be deleted/updated:
- https://github.com/grafana/grafana/blob/main/pkg/plugins/backendplugin/grpcplugin/client_v1.go
- https://github.com/grafana/grafana/blob/main/pkg/plugins/backendplugin/grpcplugin/grpc_plugin.go#L66-L71
- https://github.com/grafana/grafana/blob/main/pkg/plugins/backendplugin/grpcplugin/client.go#L58

### PR DESCRIPTION
**Pull request by idafurjes**
…n (#34127)

* 33959: Remove support for deprecated backend plugin protocol (v1)

* 33959: Remove unused methods

* 33959: Remove some additional unused code

* 33959: Remove some additional unused code

* 33959: Remove datasource plugin wrapper with test

* 33959:Remove DefaultProtocolVersion

(cherry picked from commit 1e8e7e34f15e234b16e56b94717613eadc8a182c)

**What this PR does / why we need it**:
Remove support for deprecated backend plugin protocol (v1)

**Which issue(s) this PR fixes**:

Fixes #33959

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
LGTM! 🚀 

BTW @marefr, this could make it into the changelog? WDYT?

**Review by marefr — APPROVED** [review]
LGTM

Please add backport label and prefix PR title with [8.0.x] and milestone 8.0.0-beta2

**Comment by marefr** [comment]
@dsotirakis this is a backport - the originating PR has breaking change label so it will be added to changelog

**Comment by dsotirakis** [comment]
> @dsotirakis this is a backport - the originating PR has breaking change label so it will be added to changelog

Oh, didn't catch that, thanks!

**Pull request merged**
