### PR TITLE
Docker: Upgrade to Alpine 3.13

### PR DESCRIPTION
**Pull request by flori**
**What this PR does / why we need it**:

Use alpine 3.13 as base image and for building.

**Which issue(s) this PR fixes**:

Alpine 3.13.0 and later 3.13.1  were released and had some improvements/fixes.

**Remarks**

In only performed a successful test build of the main Dockerfile. I am not sure how to check the other build scripts, but I assume they will work as well.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Can you also regenerate .drone.yml, via `drone starlark convert`? Otherwise the PR won't build.

**Comment by aknuds1** [comment]
Plus you need to sign the CLA.

**Comment by flori** [comment]
Anything I can do to make this happen? I want to always have somewhat recent alpine installations in our cluster rather than determining if we might be impacted by a security issue or not.

**Comment by aknuds1** [comment]
> Anything I can do to make this happen? I want to always have somewhat recent alpine installations in our cluster rather than determining if we might be impacted by a security issue or not.

Oh hey, sorry, forgot about this PR! This PR is actually no longer necessary, since I upgraded Alpine plus other things in another PR. Thanks though!

**Comment by flori** [comment]
OK, I am looking forward to the next release then…

**Pull request closed without merging**
