### PR TITLE
OAuth: Do not set default role for Azure AD

### LINKED ISSUE #22741: Azure AD OAuth2 authentication shouldn't default to Viewer and should throw Unauthorized error instead
**What happened**:
Following this https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana and according to https://github.com/grafana/grafana/issues/21366#issuecomment-577026143 , if the users aren't assigned any app roles, they shouldn't be allowed to login.

However, in Azure AD, if the user has no app role, `Default Access` role will be assigned to them, and a token will be returned, instead of no token.

And on Grafana side `pkg\login\social\azuread_oauth.go`,  `extractRole()` default to return `Viewer` role.

**What you expected to happen**:
Because, Azure AD token has a group limit of 200, app role is suggested as a consistent way to authorize to certain groups of users. So if users have no assigned app role, `Unauthorized` error should be thrown instead

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.7.0-274a4322pre (5ad8a9722e)
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by twendt**
**What this PR does / why we need it**:
Currently the Azure AD provider sets the viewer role as the default role when no other role is assigned in Azure AD. This will be changed so that an empty string is returned.

This change requires that #22383 will also be implemented. Otherwise if a user is assigned to the admin role and then unassigned from the admin role (without assigning any other grafana role) in Azure AD, the user will keep the admin role in grafana. The issue #22741 is also only completely fixed once both PRs are merged.

**Which issue(s) this PR fixes**:

Fixes #22741 

**Special notes for your reviewer**:
Requires #22383.

### CODE REVIEW

**Comment by aknuds1** [comment]
You'll need to merge with latest Grafana master, in order to fix the CI failures.

**Comment by uvaisibrahim** [comment]
Is this something related to this?

https://github.com/grafana/grafana/issues/22711

**Comment by motoko89** [comment]
Can't wait for this to merge!

**Comment by twendt** [comment]
@uvaisibrahim No this is not related. The Azure AD provider does not support groups at all. It only supports Application Roles. There is not support for mapping users or roles to organizations either.

**Comment by twendt** [comment]
Since #22383 has been rejected I am going to close this PR as well.

**Pull request closed without merging**
