### PR TITLE
Search: use triggers rather code to populate `entity_event`

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
SQL-based alternative to saving events in DB via code from https://github.com/grafana/grafana/pull/47709

### CODE REVIEW

**Comment by ryantxu** [comment]
🤔 interesting -- for sure worth considering.  Though I am skeptical of using advanced DB features across sqlite/postgres/mysql/etc

**Comment by ArturWierzbicki** [comment]
I think it's a pretty straightforward approach which gives us atomicity for free and ensures that we cover _all_ write paths without writing a lot of code. I just wonder if there are any operational issues we might run into when deploying the migration except for having to make sure we use the appropriate sql syntax for each db

**Comment by ryantxu** [comment]
For sure this is worth considering, it is just not a pattern we use anywhere else - so I am cautious.

Some advantages to an explicit code path:
1. we can drop in an implementation with an "at-least-once" message system
2. Single node instances can skip the database entirely
3. While difficult -- we actually trace down everywhere that triggers events we want to react to

**Comment by ArturWierzbicki** [comment]
> For sure this is worth considering, it is just not a pattern we use anywhere else - so I am cautious.

Definitely makes sense, this adds a lot of risk

> we can drop in an implementation with an "at-least-once" message system

I believe thats still possible with triggers and the table if we have a 'message relay' which polls db, publishes the events and marks them as sent.

> While difficult -- we actually trace down everywhere that triggers events we want to react to

That's my least favorite part about the SQL trigger approach - you can't easily figure out the source of events. It's both annoying and interesting at times, especially when it leads you to discover that a single row is updated 10 times within a single business transaction... 🙂

**Comment by ryantxu** [comment]
Lets close this -- i like the approach, but lets see how thigns go with explict callbacks

**Pull request closed without merging**
