### PR TITLE
make name unique to fix issue #22426

### PR DESCRIPTION
**Pull request by jackyq2015**
**What this PR does / why we need it**:
Instead of deleting it, I renamed it to avoid the issue mentioned in #22426 

**Which issue(s) this PR fixes**:
issue #22426

### CODE REVIEW

**Comment by ryantxu** [comment]
Are you able to post a repo or something where this change makes a difference?

**Comment by jackyq2015** [comment]
> Are you able to post a repo or something where this change makes a difference?

I already posted a repo with antd table under the same issue. what I did to test is to remove the mini from chrome devtools and the pagination shows up properly immediately

**Comment by dprokop** [comment]
@jackyq2015 I guess we can rather delete this class name if it's not used. I've just checked it and seems like it isn't.

**Comment by jackyq2015** [comment]
Deleted

**Review by dprokop — APPROVED** [review]

**Pull request merged**
