### PR TITLE
Documentation: Update developer-guide.md

### PR DESCRIPTION
**Pull request by MoonBall**
**What this PR does / why we need it**:

Update document Since `prometheus_mac ` is not in [available data sources](https://github.com/MoonBall/grafana/tree/master/devenv/docker/blocks).

### CODE REVIEW

**Comment by achatterjee-grafana** [comment]
@marcusolsson, can you confirm and approve. Thank you!

**Comment by achatterjee-grafana** [comment]
@MoonBall, you need to sign the CLA.

**Review by marcusolsson — APPROVED** [review]

**Comment by MoonBall** [comment]
> @MoonBall, you need to sign the CLA.

done

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

**Pull request merged**
