### PR TITLE
Make Ldap group composed of  DNs work.

### PR DESCRIPTION
**Pull request by sbskas**
Permit for LDAP groups to be groupofuniquenames composed of uniquename (DN).
For this, propose DN as group_search_filter_user_attribute and DN also for the member_of in the server.attributes section.

DN is processed as a special attribute name which returns the LdapSearchResult.DN field instead of a member of attr array.

* Link the PR to an issue for new features
* Rebase your PR if it gets out of sync with master

**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by sbskas** [comment]
Tests remain unwritten. I'm quite a newbie in Go.
I may need some help to write somes.

**Review by DanCech — COMMENTED** [review]
Interesting, seems to be only a small change. I'll take a look at the tests this afternoon.

**Comment by DanCech** [comment]
Hmm, the circleci failure is now due to a timestamp issue on one of the dashboard tests and not anything related to this PR directly.

**Comment by sbskas** [comment]
Here's the test for this feature
User Alice:
cn=alice,ou=People,dc=foo,dc=com
cn=bob,ou=People,dc=foo,dc=com
cn=conrad,ou=People,dc=foo,dc=com

Group AdminGrafana where Alice is member of:
cn=AdminGrafana,ou=Groups,dc=foo,dc=com
objectclass: groupofuniquenames
uniquename: cn=alice,ou=People,dc=foo,dc=com

Group User where bob is member of
cn=UserGrafana,ou=Groups,dc=foo,dc=com
objectclass: groupofuniquenames
uniquename: cn=bob,ou=People,dc=foo,dc=com

Group Viewer where conrad is member of 
cn=ViewerGrafana,ou=Groups,dc=foo,dc=com
objectclass: groupofuniquenames
uniquename: cn=conrad,ou=People,dc=foo,dc=com

In configuration file ldap.toml:
group_search_filter = "(&(objectClass=groupofuniquenames)(uniqueMember=%s))"
group_search_filter_user_attribute = "DN"
group_search_base_dns = ["dc=foo,dc=com"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
email =  "mail"
member_of = "DN"
[[servers.group_mappings]]
group_dn = "cn=AdminGrafana,ou=groups,dc=foo,dc=com"
org_role = "Admin"
[[servers.group_mappings]]
group_dn = "cn=UserGrafana,ou=groups,dc=foo,dc=com"
org_role = "Editor"
[[servers.group_mappings]]
group_dn = "cn=ViewGrafana,ou=groups,dc=foo,dc=com"
org_role = "Viewer"

Just check then that alice is admin, bob is user, conrad is viewer, anyone else is rejected.
I'll try to figure how to write it down in ldap_test.

**Comment by DanCech** [comment]
@sbskas I was able to resolve the issue with the tests, the CLA is still not showing as signed however.  Can you make sure that the email address in your commit is linked to your github account?

https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by marefr** [comment]
@DanCech I don't know of a way to resolve this besides possibly rewriting the commit and force push. Last time this happened I gave the recommendation to close the PR. Fix the email address, commit the code to different branch using new commit and then submitting a new PR

**Comment by DanCech** [comment]
@marefr If I'm reading the instructions correctly, adding the email address used in the commit to @sbskas github account as an authorized email should be enough to solve the CLA issue.

**Comment by daniellee** [comment]
@sbskas have you signed the CLA?

**Comment by mmolnar** [comment]
There is already a PR that does basically the same thing, so if you merge this close the other one #10970 
Thanks

**Comment by DanCech** [comment]
@mmolnar this solution is the cleaner way, just not sure what the status is with the CLA

**Comment by sbskas** [comment]
@DanCech  I added my professionnal address to my github account.
Please let me check it there's some more action to perform by my side.
I didn't realize my work email got involved in the PR.

**Comment by DanCech** [comment]
Thanks @sbskas , that did the trick!

**Comment by owengo** [comment]
There is a bug:
line 351:
```
	if name == "DN" {
		return result.Entries[0].DN
	}
```

Should be:
```
	if name == "DN" {
		return result.Entries[n].DN
	}
```
Because of the bug the user is  a member of only the first group found..
The test should include these cases:
for exemple Bob could be User in org 1 and Admin in org 2

Could you do the patch ?

**Comment by marefr** [comment]
@owengo would you mind open a bug report issue to track this problem? Thanks

**Comment by owengo** [comment]
Sorry, here is the issue:
https://github.com/grafana/grafana/issues/11891

I do not submit the patch because I am not able to build and test. The PR works well for us ( we use openldap + groupOfUniqueNames  ), except for this issue. Our current workaround is to use member_of = "cn".

**Pull request merged**
