### PR TITLE
Alerting: Promote new alerting detail view

### PR DESCRIPTION
**Pull request by gillesdemey**
**What is this feature?**

This PR enables the new alerting detail view by default and removes the feature flag.

### CODE REVIEW

**Review by soniaAguilarPeiron — COMMENTED** [review]
maybe we should also remove `RuleViewer.v1` file and the test for it?

**Comment by gillesdemey** [comment]
Oops, I meant to do that in this PR and forgot about it 🤦

**Comment by gillesdemey** [comment]
Updated the file names and moved some things out of the `v2` folder so we don't have to keep those around

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM!

**Pull request merged**
