### PR TITLE
JsonEditorSettings: Fix invisible json editor

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Fixes an issue where the dashboard JSON editor wasn't visible.

### CODE REVIEW

**Review by leeoniya — APPROVED** [review]
works for me!

**Comment by torkelo** [comment]
@kaydelaney please wait merging this, I think I now understand why the pageInner had display flex, and think we can fix this in a different way

**Comment by torkelo** [comment]
@kaydelaney alternative fix here: https://github.com/grafana/grafana/pull/56524/

**Comment by kaydelaney** [comment]
Closing in favor of #56524

**Pull request closed without merging**
