### PR TITLE
Theme: Updated font to Inter, updates typography, a start of moving legacy & global styles from sass to emotion 

### PR DESCRIPTION
**Pull request by torkelo**
* [x] Update main font from Roboto to Inter
* [x] Update main mono space font to Roboto Mono
* [x] Update typography 
* [x] Add Typography storybook for the native elements 
* [x] Adds a Typography component that will be implemented later and be similar to https://material-ui.com/components/typography/ 
* [x] Adds a GlobalStyles component and a start/embryo of moving old sass global styles to emotion 
* [x] Rename palette.getHoverColor to palette.emphasize

### CODE REVIEW

**Comment by domasx2** [comment]
600 weight (bold) glyphs were missing for Roboto, which made bold text look smudged on some systems as browser interpolates to 600 from other weight. Maybe we could fix this and add 600 with Inter?

**Comment by torkelo** [comment]
@domasx2 where do you use font-weight 600?

**Comment by domasx2** [comment]
> @domasx2 where do you use font-weight 600?
`theme.typography.weight.bold` is set to `600`, and various designs (eg, unified alerting) call for it to be used

**Comment by torkelo** [comment]
> theme.typography.weight.bold is set to 600, and various designs (eg, unified alerting) call for it to be used
> https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/default.ts#L56

Did not know that we should always use semibold, will map bold to 500

**Pull request merged**
