### PR TITLE
[WIP] JWT Authentication

### LINKED ISSUE #8198: [Feature request] JWT Authentication
By now it would be great to get JWT Authentication support.

One use case for this would be Google IAP (https://cloud.google.com/iap/). In this case Google would do the authentication and passes a JWT Header containing the user information. I guess Google is just the starter for such use cases and other implementations might evolve soon.

There is still the option for OAuth, but this would be redundant for such cases, as OAuth takes already place at the auth proxy and we merely need to parse the passed header. There's also no issue from the security perspective, as the `X-Goog-Authenticated-User-JWT` header is signed. 

Here are the details about their respective headers:
- https://cloud.google.com/iap/docs/identity-howto#getting_the_users_identity_in_compute_name_short_container_name_short_and_gae_name_short_flexible_environment
- https://cloud.google.com/iap/docs/signed-headers-howto

This is in response to #1247

### PR DESCRIPTION
**Pull request by ryantxu**
This PR revives #9166, but focus on Firebase support. 

TODO:
- [x] How do I test: `initContextWithJwtAuth(ctx *m.ReqContext,...` --> `ctx.Handle(500,...`?
- [x] Support firebase tokens
- [x] Support google tokens (but not tested)
- [ ] Improve Documentation
- [ ] Test reload keys via TTL
- [ ] Test expect fields (iss, aud, etc)
- [ ] Test google tokens

Fixes #8198

### CODE REVIEW

**Comment by ryantxu** [comment]
@bergquist can you do a quick smell test?  I tried incorporating your feedback from #9166 into this

**Comment by bergquist** [comment]
Looks like a great start! I'll review this in more details soon :)

I want to see if I can find more providers that we can use this.

We wont have time to review this enough before 6.0 stable but I definitly hope we can get this into 6.1

**Comment by ryantxu** [comment]
@bergquist -- now that #15268 is added, this is the main issue blocking a pretty nice firebase plugin...

Do you have any time to take a look?  My go skilz are poor, so bear with me :)  The biggest issue is things would probably better if I could figure out how to import/use:
```
import (
	"gopkg.in/square/go-jose.v2/jwt"
)
```
rather than trying to parse the claims directly!   Any pointers on that would be great

**Comment by jeremywilliams** [comment]
Any updates on this?

**Comment by marefr** [comment]
@ryantxu explaination here: https://github.com/grafana/grafana/blob/master/CONTRIBUTING.md#backend-dependency-management

But basically you should do:
```bash
grafana/ > GO111MODULE=on go get gopkg.in/square/go-jose.v2/jwt@v2.3.0
grafana/ > GO111MODULE=on go mod tidy
grafana/ > GO111MODULE=on go mod vendor
```

Suggest to merge in latest master before doing above.

**Comment by marefr** [comment]
@ryantxu are you still planning to work on this to get it to a merge:able state?

**Comment by ryantxu** [comment]
@marefr am I missing something... running the following:
image

does not appear to change anything.

Also -- this PR is not a top priority for me now, but I will keep it alive and think it is worth finishing

**Comment by marefr** [comment]
@ryantxu think you need to have `import "gopkg.in/square/go-jose.v2/jwt"` defined in at least one go file before [upgrading dependencies](https://github.com/grafana/grafana/pull/15187#issuecomment-497737724)

**Comment by dekimsey** [comment]
Would this support additional values from the claims something akin to how the auth.proxy let's one set a headers field for additional values to extract/use?

```
# Optionally define more headers to sync other user attributes
# Example `headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS`
headers =
```

Say something like...
```
login_claim = oid
claims = Name:fullname Email:email Groups:roles
```

**Comment by kwiesmueller** [comment]
We could really use this as well.
Haven't contributed to Grafana yet, but would be happy to help if it gets this merged faster.

Would use it with Google IAP.

**Comment by jregistr** [comment]
@ryantxu Are you open to PR's against your branch? I'd be happy to help close out some of these TODO's. 
This change would be immensely helpful for us so that we don't have to type additional auth after the IAP proxy.

**Comment by ryantxu** [comment]
Yes Absolutely -- thins has fallen off my 'must solve' list

**Comment by jregistr** [comment]
@ryantxu 
The `Test google tokens` todo, what does this entail? Is it simply verifying it works by launching Grafana in google cloud behind IAP?

**Comment by ryantxu** [comment]
> The Test google tokens todo, what does this entail? Is it simply verifying it works by launching Grafana in google cloud behind IAP?

It would mean making sure it works on IAP :)  ideally both running it, and adding tokens that match the IAP format to the test suite

**Comment by jregistr** [comment]
Perfect! I launched the branch on app engine flex which has iap enabled and it worked!!
I also tried the test endpoints for iap (https://cloud.google.com/iap/docs/special-urls-and-headers-howto#testing_jwt_verification) and all except the **FUTURE_ISSUE** return expected results.
I started the process of adding/updating tests. A small first PR should be coming soon.

**Comment by jregistr** [comment]
Linking the first PR here: https://github.com/ryantxu/grafana/pull/1

**Comment by jregistr** [comment]
> > The Test google tokens todo, what does this entail? Is it simply verifying it works by launching Grafana in google cloud behind IAP?
> 
> It would mean making sure it works on IAP :) ideally both running it, and adding tokens that match the IAP format to the test suite

Hey @ryantxu I'm jumping back on this. 
For this particular test what would satisfy your todo? Should I document the steps I took to 
verify it works with IAP(such as launching it on app engine flex behind IAP LB) for fellow reviewers? Or did you have some sort of unit test in mind?

**Comment by jregistr** [comment]
Currently, I'm going to tackle these two:
 - [ ] Improve Documentation
 - [ ] Test reload keys via TTL

**Comment by jregistr** [comment]
Hi Stale bot, I'm working on the testing now.

**Comment by jregistr** [comment]
Hi @ryantxu and Stale bot, I've sent the next PR https://github.com/ryantxu/grafana/pull/2

**Comment by felipebn** [comment]
Hi @ryantxu and @bergquist I'm looking to help finish this implementation and get it available in Grafana, but should I try to contribute in this PR itself or better do it in new one?

**Comment by gramidt** [comment]
I'm happy to provide testing for this feature, as I have an immediate use case where this would simplify a project.

**Comment by felipebn** [comment]
Hi again @ryantxu and @bergquist, 

I'm want to contribute with this implementation but would like some feedback from you regarding what is missing and also if you are interest on moving forward with it.

I already have some contributions ready to @jregistr fork that you can check here: https://github.com/jregistr/grafana/pull/1

Could you please share some feedback?


Thanks!

**Comment by jregistr** [comment]
Hey @felipebn, I merged your changes!

**Comment by asasmoyo** [comment]
I would love to see this merged in master especially for Google Cloud IAP use case. Is there anything I can help?

**Comment by jregistr** [comment]
Hello!
I wanted to reach out to @ryantxu and @bergquist.
What could the contributors possibly do to help get this PR ready for merging?
We have this PR: https://github.com/ryantxu/grafana/pull/2 with the goal of tackling the remaining checklists.

I'm curious about what else is left. Or is this kind of update just not currently in the priorities for Grafana, that's fine too, I'd understand it.

**Comment by IntegersOfK** [comment]
This sign-on integration is the final piece to allowing developers to integrate Grafana into their Google Cloud applications where user info is commonly stored in Firebase. I am very interested in seeing this integrated as one of Grafana's native user auth flows.

**Comment by kitos9112** [comment]
Wondering what's left to have this MR ready to be part of a new Grafana release. We're using a custom solution to decode the JWT sent by AWS Application Load balancers upon successful authentication which we'd love to get rid of and simplify our deployment.

**Comment by marshall-lee** [comment]
I revived a JWT work in https://github.com/grafana/grafana/pull/15187

**Comment by marshall-lee** [comment]
I revived a JWT work in #29995

**Pull request closed without merging**
