### PR TITLE
Alerting docs: adds display names to fixed roles for RBAC

### PR DESCRIPTION
**Pull request by brendamuir**
adds display ui names for fixed roles to make it easier to match up. as requested in support ticket https://github.com/grafana/support-escalations/issues/12028

### CODE REVIEW

**Comment by tonypowa** [comment]
The display in the UI looks correct to me

To improve this even more, we could either update the description in the docs to match the tool tip's description, or create a separate PR and update the tool tip according to the docs. At least, so the beginning of the description is the same.  And lastly, display the roles in alphabetical order.

image
image

**Comment by brendamuir** [comment]
i'll check with @yuri-tceretian the logic behind the order of the fixed roles in the UI? otherwise agree with making the descriptions match the ui - i will cross-check and update that one.

**Comment by brendamuir** [comment]
Also @yuri-tceretian by in Grafana and external providers - are we referring to Alertmanagers?

**Review by yuri-tceretian — APPROVED** [review]

**Review by tonypowa — APPROVED** [review]
LGTM 🚀

**Pull request merged**
