### PR TITLE
Docs: InfluxDB doc improvements (#32815)

### PR DESCRIPTION
**Pull request by gabor**
* Create getting-started-influxdb.md

* Update getting-started-prometheus.md

* Update getting-started-sql.md

* data source edits

* single source intro

* Create first-step.md

* Update influxdb.md

* Update getting-started-influxdb.md

* Update influxdb.md

* break up long file

* Update influxdb-templates.md

* more updates

* Update _index.md

* Update _index.md

* Update getting-started-sql.md

* Update _index.md

* edits

* Update docs/sources/datasources/influxdb/_index.md

Co-authored-by: Ursula Kallio <73951760+osg-grafana@users.noreply.github.com>

* Delete influxdb.md

* Update getting-started-influxdb.md

* Update influx-flux.md

* Update _index.md

* Update getting-started-influxdb.md

* Update getting-started-influxdb.md

* content

* content changes

* Update _index.md

* link fixes

* Update getting-started-influxdb.md

* Update getting-started-influxdb.md

* Merge branch 'master' into docs-influxdb

* updated port

Co-authored-by: Ursula Kallio <73951760+osg-grafana@users.noreply.github.com>
(cherry picked from commit c986aaa0a8e7fb167b9d10304129f6aea85ad45c)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by oddlittlebird — APPROVED** [review]
LGTM

**Comment by oddlittlebird** [comment]
Heya Gabor, the CLA thinks you haven't signed it.

**Comment by gabor** [comment]
> Heya Gabor, the CLA thinks you haven't signed it.

i did a hour ago or so 😿 i wonder what's wrong with the cla-thing..

**Comment by oddlittlebird** [comment]
Whatever's wrong, it's blowing up my email with CLA notifications .

**Pull request merged**
