### PR TITLE
Auth: Update Google OAuth conf based on /.well-known #69520

### LINKED ISSUE #69520: Auth: Google OAuth default configuration are different from .well-known/openid-configuration
**What is the chore?**:

- Google OAuth default configuration are different from .[well-known/openid-configuration](https://accounts.google.com/.well-known/openid-configuration)
  - For now the defaults.ini URL will work, but better choose the same endpoints that google provides in compliance with OIDC standards.
  - If implement OIDC in the future, it will only a small change

|| defaults.ini           | /.well-known/openid-configuration             |
|------------------------|-----------------------------------------------|--------------------------------------------------|
| token_endpoint         | https://accounts.google.com/o/oauth2/token    | https://oauth2.googleapis.com/token              |
| authorization_endpoint | https://accounts.google.com/o/oauth2/auth     | https://accounts.google.com/o/oauth2/v2/auth     |
| userinfo_endpoint      | https://www.googleapis.com/oauth2/v1/userinfo | https://openidconnect.googleapis.com/v1/userinfo |
| scope | https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email | openid email profile |

**Is there anything else we need to know?**:

see: https://accounts.google.com/.well-known/openid-configuration

- suggest labels
  - https://github.com/grafana/grafana/labels/area%2Fauth%2Foauth
  - https://github.com/grafana/grafana/labels/team%2Fgrafana-authnz

```json
{
 "issuer": "https://accounts.google.com",
 "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
 "device_authorization_endpoint": "https://oauth2.googleapis.com/device/code",
 "token_endpoint": "https://oauth2.googleapis.com/token",
 "userinfo_endpoint": "https://openidconnect.googleapis.com/v1/userinfo",
 "revocation_endpoint": "https://oauth2.googleapis.com/revoke",
 "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs",
 "response_types_supported": [
  "code",
  "token",
  "id_token",
  "code token",
  "code id_token",
  "token id_token",
  "code token id_token",
  "none"
 ],
 "subject_types_supported": [
  "public"
 ],
 "id_token_signing_alg_values_supported": [
  "RS256"
 ],
 "scopes_supported": [
  "openid",
  "email",
  "profile"
 ],
 "token_endpoint_auth_methods_supported": [
  "client_secret_post",
  "client_secret_basic"
 ],
 "claims_supported": [
  "aud",
  "email",
  "email_verified",
  "exp",
  "family_name",
  "given_name",
  "iat",
  "iss",
  "locale",
  "name",
  "picture",
  "sub"
 ],
 "code_challenge_methods_supported": [
  "plain",
  "S256"
 ],
 "grant_types_supported": [
  "authorization_code",
  "refresh_token",
  "urn:ietf:params:oauth:grant-type:device_code",
  "urn:ietf:params:oauth:grant-type:jwt-bearer"
 ]
}
```

### PR DESCRIPTION
**Pull request by arukiidou**
**What is this feature?**

- Update Google OAuth conf based on [/.well-known/openid-configuration](https://accounts.google.com/.well-known/openid-configuration)
- Scope adjusted to be equivalent to azuread

|| defaults.ini           | /.well-known/openid-configuration             |
|------------------------|-----------------------------------------------|--------------------------------------------------|
| token_endpoint         | https://accounts.google.com/o/oauth2/token    | https://oauth2.googleapis.com/token              |
| authorization_endpoint | https://accounts.google.com/o/oauth2/auth     | https://accounts.google.com/o/oauth2/v2/auth     |
| userinfo_endpoint      | https://www.googleapis.com/oauth2/v1/userinfo | https://openidconnect.googleapis.com/v1/userinfo |
| scope | https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email | openid email profile |

**Why do we need this feature?**

- Complies with OIDC configurations

**Who is this feature for?**

- Google Oauth user.

**Which issue(s) does this PR fix?**:

- Fixes #69520

**Special notes for your reviewer:**

- If any concern about adding an `openid` scope, I would remove it.

- suggest labels
  - https://github.com/grafana/grafana/labels/area%2Fauth%2Foauth
  - https://github.com/grafana/grafana/labels/add%20to%20changelog

- may conflicts #69579. Wait if necessary.

- Tested with docker compose

```yaml:compose.yml
  grafana:
    image: "grafana/grafana:main"
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_GOOGLE_ENABLED: true
      GF_AUTH_GOOGLE_CLIENT_ID: ******
      GF_AUTH_GOOGLE_CLIENT_SECRET: ******
      GF_AUTH_GOOGLE_ROOT_URL: http://localhost:3000

      # It works fine now.
      GF_AUTH_GOOGLE_AUTH_URL:  https://accounts.google.com/o/oauth2/v2/auth
      GF_AUTH_GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
      GF_AUTH_GOOGLE_API_URL: https://openidconnect.googleapis.com/v1/userinfo
      GF_AUTH_GOOGLE_SCOPES:  openid,email,profile
```

https://github.com/grafana/grafana/assets/10738333/92966f95-6e93-4d3c-a032-d44e392b1bb8

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by chri2547** [comment]
@IevaVasiljeva , could you please take a look at this PR? Thank you!

**Review by IevaVasiljeva — APPROVED** [review]

**Review by IevaVasiljeva — CHANGES_REQUESTED** [review]
Hey! We've tested this some more, and found that `https://openidconnect.googleapis.com/v1/userinfo` returns the user info in a different format than `https://www.googleapis.com/oauth2/v1/userinfo` does. We rely on the `id` field being present, but for the newer endpoint the id info is located under `sub` field. Therefore we'll need to do more work to make sure that we parse user info correctly.

I'll create an issue for extending our user info parsing, and we'll try to pick it up soon (and of course you're more than welcome to work on it yourself if you have the capacity). But I'm afraid that we can't merge this PR until then.

**Comment by IevaVasiljeva** [comment]
Created https://github.com/grafana/grafana/issues/70081

**Comment by chri2547** [comment]
Docs approved. Will let @IevaVasiljeva take it from here, removing myself as reviewer.

**Pull request closed without merging**
