### PR TITLE
Fix adhoc filtering is incorrectly enabled for prometheus in table panel

### LINKED ISSUE #12908: [Bug] Adhoc filtering is incorrectly enabled for prometheus in table panel
image

Seems to have been introduced in #12729

### PR DESCRIPTION
**Pull request by marefr**
Fixes #12908

### CODE REVIEW

**Comment by torkelo** [comment]
This feels a bit hacky. Wonder if there is any other way to solve it.

**Comment by torkelo** [comment]
Maybe we can remove the this from Prometheus for now for 5.3 and figure out a new way to add filterable to explore that feels less hacky.

**Comment by marefr** [comment]
Hmm. This hacky implementation I would say is for not breaking explore in master nor 5.3. Guess we can wait until @davkal is back and have a discussion then.

**Comment by torkelo** [comment]
Not sure what you mean, no it’s not breaking anything, this PR is fixing an issue. But fix feels like the explore filtering stuff was added in a inconsistent way that requires this hacky explore specific flag. Maybe we can remove explore filter feature to have something more aligned that does not require a explore specific property

**Comment by marefr** [comment]
Yes, I was just meaning that breaking/removing this feature in explore which people already uses (in master build) maybe is not the smartest thing to do. But I guess we have time to fix this before 5.3 stable so lets put this on hold.

**Comment by davkal** [comment]
The table model didnt have a TS interface, so I couldnt know that `filterable` existed when I added it for Explore.

This PR is a good hotfix because it places the flag correctly, on the table model, like done in this PR. It uses the model as the interface between datasource and panel. A bad alternative could place it on the datasource, e.g., via `supportsAdhocFiltering`, this would couple datasources and table panels. (not a fan).

For a post-hotfix solution we could bring adhoc filtering to the prom+tablepanel by using a similar mechanism as used for ES, which so far is the only DS using adhoc filtering. 

Pro: consistency across DS, even if ES is the only other one.

Con: when filtering it's not really obvious whether the panel source has been modified (the reason why we created Explore in the first place).

From a UX point of view, it's a crutch unless there was another button to make the filtering permanent by applying the filter to the query visibly in its field, which has the effect of asking to store the modification when navigating away.

Rough design:

1. remove `exploreFilterable`
2. in prom DS `query()`, get adhoc filters, and run query and filters through `addLabelToQuery()` 
3. (Optional) add button to make filtering permanent.

**Comment by torkelo** [comment]
> Rough design:
1. remove exploreFilterable
2- in prom DS query(), get adhoc filters, and run query and filters through addLabelToQuery()
3. (Optional) add button to make filtering permanent.

Not sure I understand, what does addLabelToQuery to query do for label value filtering? and what does the button to make permanent do? (InfluxDB also supports adhoc filters without any permanent button). 

The exploreFilterable feels wrong to me as the datasource is trying to inform the caller that this column is a key that can be filtered by, same as filterable. But not seeing many alternatives to be honest, just feels like there should be a better option. The only I can think of is to have a explore: true flag in the query model and to have the prom response handler only set filterable: true when processing explore query results but that feels equaly bad.

**Comment by davkal** [comment]
> Not sure I understand, what does addLabelToQuery to query do for label value filtering?

A panel query could be `metric{label="value"}`, when adhoc filtering the user clicks on a cell `bar` in column `foo` which represents a new key/value pair to be added to the selector. We need to inject the `foo="bar"` somewhere without changing the query of the panel. I suppose the best place is in the query function of the DS. There it gets the `foo`/`bar` set from the template engine, and then a call to `addLabelToQuery` returns `metric{foo="bar",label="value"}` as the final query that will be sent.

> and what does the button to make permanent do? (InfluxDB also supports adhoc filters without any permanent button).

This additional button could use the adhoc query expression `metric{foo="bar",label="value"}` to overwrite the existing panel query, leading to a panel edit that needs to be saved.

 > The only I can think of is to have a explore: true flag in the query model and to have the prom response handler only set filterable: true when processing explore query results

Sounds reasonable too, I'll give it a think.

**Comment by davkal** [comment]
I think we need decision about whether we want to accept this PR as a stepping stone, or wait for the comprehensive fix (probably 2 weeks away if I'm doing it).

**Comment by marefr** [comment]
Closing this in favor of #13212

**Pull request closed without merging**
