### PR TITLE
Embed static assets in binary file

### PR DESCRIPTION
**Pull request by mavimo**
First WIP to allow assets embedding in order to have a single binary file to execute grafana.

This is a WIP so please only consider to review and test in in order to send some feedback about it.

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure about the benefits, Grafana is shipped with config files and currently with a linux phantomjs binary (needs to be extended for other platforms or the dependency needs to be handled in some other way).  So even with this there is no "single binary" distribution. Deployment doesnt really get that much easier as well, whats the difference between copying one file vs a couple? I can see that this would be good if there was no config file or other dependencies.

**Comment by mavimo** [comment]
The main benefit (form my use case) is the possibility to have grafana in the bin folder and execute it (for web interface) in any folder I'm in, just specify the config file. I'm not sure we need to have phantomjs as embedded bin, is it used only to build dependencies?

**Comment by torkelo** [comment]
No, phantomjs is used to render images of panels on the server (used from the share panel dialog). 

Grafana can be used from anywhere if you specify config file and homepath. The deb and rpm distributions place the binary in /usr/sbin

**Comment by bergquist** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
