### PR TITLE
[v9.3.x] Docs: Update whats new link

### PR DESCRIPTION
**Pull request by dsotirakis**
**What is this feature?**

What's new link is broken for `9.3.x` releases. This PR fixes the ref.

### CODE REVIEW

**Review by kminehart — APPROVED** [review]

**Comment by jdbaldry** [comment]
I actually don't know where that `package.json` file is used (presumably in the app itself). I think we might need to fix https://github.com/grafana/grafana/blob/v9.3.x/docs/sources/_index.md?plain=1#L73-L76 for the website too.

**Comment by dsotirakis** [comment]
> I actually don't know where that `package.json` file is used (presumably in the app itself). I think we might need to fix https://github.com/grafana/grafana/blob/v9.3.x/docs/sources/_index.md?plain=1#L73-L76 for the website too.

You may be right @jdbaldry 🥷 Should I do that?

**Comment by jdbaldry** [comment]
If we can hold off a sec, I am getting a technical writer to check what needs to be done

**Comment by jdbaldry** [comment]
Just confirmed with the technical writers and pushed a commit to fix that link

**Comment by jdbaldry** [comment]
Thanks for waiting :)

**Pull request merged**
