### PR TITLE
Tracing: Fix OpenTelemetry Jaeger context propagation

### PR DESCRIPTION
**Pull request by zhichli**
**What this PR does / why we need it**:

- **Issue**: The [propagation setting for jaeger of opentelemetry](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#propagation) would always be **ignored** in code, and it would be `w3c` by default. 
  - **After this Fix**: user can give value `jaeger` to the setting and Grafana will respect the setting.

- **Issue**: in the case that a reverse proxy in front of Grafana forwards a jaeger tracing header (e.g. `uber-trace-id: 0af7651916cd43dd8448eb211c80319c:00f067aa0ba902b7:000000000000000:1`, the trace ID in the header would **not** be properly taken as a root trace ID for spans created by Grafana. So newly created child spans in Grafana cannot be correlated with the trace ID in logs/traces of the reverse proxy or any other services upstream, which essentially breaks distributed tracing (context propagation). Technically, [the current code](https://github.com/grafana/grafana/blob/4c02d072e3c9c60761ced406ca44c977a539fb96/pkg/middleware/request_tracing.go#L76) only links the remote trace context to newly created spans in `request_tracing` middleware, but the linking does not set parent span of those new child spans with the remote trace context ([span linking is conceptually different from setting parent span](https://opentelemetry.io/docs/reference/specification/overview/#links-between-spans)).
  - **After the Fix**: the newly created spans would have their parent span being set by the [extracted span context from request context](https://github.com/grafana/grafana/blob/4c02d072e3c9c60761ced406ca44c977a539fb96/pkg/middleware/request_tracing.go#L75) (`wireContext`). Thus all child spans will share the same trace ID as the remote tracing header, and all spans can be viewed under a single trace UI.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This fix is for openTelemetry jaeger only and should be treated as different fix from this #51374 fix for this issue #50079, in which the user uses the deprecated `opentracing` jaeger.

### CODE REVIEW

**Comment by zhichli** [comment]
@taleena @idafurjes

**Review by idafurjes — APPROVED** [review]
LGTM

**Review by zserge — APPROVED** [review]

**Comment by zhichli** [comment]
> LGTM

Thanks. I see there are a few workflows that need to be approved to run. Could you please approve ? And the continuous-integration/drone/pr building is failing, which seems unrelated to this PR. Do you know why and how I should bypass it ?

**Comment by idafurjes** [comment]
@zhichli I think you need to rebase to make drone pass

**Pull request merged**
