### PR TITLE
InfluxDB: Introduce maxDataPoints setting for flux variable query editor

### LINKED ISSUE #84120: InfluxDB: Have maxDataPoints input for flux variable queries
We calculate the maxDataPoints based on the panel size. For the variables there is no panel size so we cannot calculate the maxDataPoints. We use a default value https://github.com/grafana/grafana/blob/main/pkg/services/query/query.go#L324

For flux we have an enforcer https://github.com/grafana/grafana/blob/main/pkg/tsdb/influxdb/flux/executor.go#L32-L33
So it ends up as 1000.

For some cases users might need more than 1000 points. So we will give that option to users by adding maxDataPoints input in VariableEditor. In order to support maxDataPoints we need `CustomVariableSupport`. Loki might be a good example how we can add that support https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/components/VariableQueryEditor.tsx

### LINKED ISSUE #85499: InfluxDB: Flux datasource only loads first 1000 values of the template variable
### What happened?

Hello,

I am using Grafana 10 and influxdb v2.7.4.

I am using below flux code to create grafana variable for my dashboard.
When i test this on influxdb script editor, i can get 3500 Client_Name variable values.
But when i apply this as a variable and open the variable filter on dashboard the values are truncated. In alphabetic order i can only get until variable names starting with f… Nearly %70 of the variable value Client Names are missing in the filter. 

If i open variable configuring page. If i create variable from influx v2.7.4, i can only see 1000 client names at variable creation page by preview of values section at bottom of page.

I also have same data on influxdb 1.8 version. If i create variable from influx 1.8 with influxql, i can see 3500 client names at variable creation page by preview of values section at bottom of page.

Below shows that 3500 clients are coming in the filter with variable from influxdb 1.8 version with influxql.
image

But if i create variable from v2.7.4 influxdb with flux only 1000 clients are shown or searched.
Below shows v2.7.4 same data.
image

Note : Tests are done with same 3500 Client_Name data in influxdb 1.8 and influxdb 2.7.4.

1) If i create variable from influx 2.7.4 with flux with below query only 1000 client names are shown at preview area at variable creation page (Also in dashboard filter):

import "influxdata/influxdb/schema"
schema.tagValues(
    bucket: "VFBckStrg",
    tag: "Client_Name"
)

2) If i create variable from influx 1.8 with influxql with below query all 3500 client names are shown at preview area at variable creation page (Also in dashboard filter):

SHOW TAG VALUES FROM “SELECTBOX_VALUES” WITH KEY = “Client_Name”

### What did you expect to happen?

When I create a Grafana variable with influxql in InfluxDB version 1.8, I can search and find all 3500 clients in the dashboard filter using this variable. However, in InfluxDB version 2.7.4, when I create a variable with flux, I can only list and search for the first 1000 clients in the filter. If I can find each of the 3500 clients in the dashboard filter with InfluxDB 1.8, I want to be able to find each of the 3500 clients in the Grafana variable filter created with the newer version, InfluxDB v2.7.4, using the flux language. I suspect there is an issue with variable integration in Grafana using InfluxDB v2.7 and the flux language.

### Did this work before?

When I create a Grafana 10 variable with influxql in InfluxDB version 1.8, I can search and find all 3500 clients in the dashboard filter using this variable. However, in InfluxDB version 2.7.4, when I create a variable with flux, I can only list and search for the first 1000 clients in the filter.

### How do we reproduce it?

1. Create data with **Client_Name** tag with **3500 sample tag values** on **influxdb 1.8** version.
2. Create data with **Client_Name** tag with **3500 sample tag values** on **influxdb 2.7.4** version.
3. Create grafana variable named XVAR with influxdb 1.8 with Client_Name tag with below influxql query : 

    SHOW TAG VALUES FROM “SELECTBOX_VALUES” WITH KEY = “Client_Name”
    Preview values on variable page and see 3500 values are shown.

4. Create grafana variable named ZVAR with influxdb 2.7.4 with Client_Name tag with below FLUX query :
import "influxdata/influxdb/schema"

schema.tagValues(
    bucket: "VFBckStrg",
    tag: "Client_Name"
)

Preview values on variable page and see only 1000 values are shown.

5. Open dashboard and check XVAR filter. You will be able to search and get all 3500 tag values in the filter.
6. Open dashboard and check ZVAR filter. You will be able to search and get only 1000 tag values in the filter.
7. At the end you will see that you can search and get all 3500 Client_Name values in XVAR filter which is created with influxdb 1.8. You will see that you can search only 1000 Client_Name values in ZVAR filter which is created with influxdb 2.7.4.
8. This means there is a problem with filters created with variables created with influxdb 2.7.4 flux language.  

### Is the bug inside a dashboard panel?

The bug starts in variable creation page. You can see that variables created with flux cannot show preview values more than 1000 values. But variables created with influxql in influxdb 1.8 show preview values more than 1000, even 3500. So when the variable goes to dashboard as a filter, the filter also behaieves like variable. 

### Environment (with versions)?

Grafana: 10.0.0
OS: RedHat Linux
Browser: Chrome Latest

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influxdb 2.7.4 with FLUX

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

Introduce maxDataPoints setting for flux variable query editor. The default value was and is 1000. With this new configuration option users can decide on the right value.

**Who is this feature for?**

InfluxDB Flux language users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/84120
Fixes https://github.com/grafana/grafana/issues/85499

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by NWRichmond — COMMENTED** [review]
I'm having trouble validating this. When using a Flux-type InfluxDB data source connected to the InfluxDB instance created by `make devenv sources=influxdb`, I'm using the following Flux query to create a dashboard variable:

```
from(bucket: "mybucket")
  |> range(start: 1706412430, stop: 1716412430)
  |> filter(fn: (r) => r["_measurement"] != "") |> keys()
```

When I set **Max Data Points** to `5`, I get more than 5 results.

influxdb flux variable

influxdb dashboard show flux variables

**Comment by itsmylife** [comment]
@NWRichmond I see your point. In the backend code there is an `enforcer` number. See: https://github.com/grafana/grafana/blob/main/pkg/tsdb/influxdb/flux/executor.go#L16

Maybe we will just ignore this number when the maxDataPoints is set.

**Review by NWRichmond — APPROVED** [review]
Thank you for those updates, @itsmylife!

**Comment by gefaila** [comment]
I'm having trouble validating this as well.
I have a bunch of dashboards that now don't work at all, or work in a weird way.

On opening our LBBC Data Browser dashboard, it used to set the variables to saved values.  This used to display a set of data for a default host.  This used to look like this
image

Now when you open the data browser it looks like this
image

Clicking on “List1” used to display all the *chosen* variables and all the *possible* variables
image

Now clicking on “List1” displays *nothing* and resets all the chosen variables
image

Zooming in on the above used to display data from a specific time
image

Zooming now displays
image

Testing the variable behind “_Field” with “run query” used to display a list of variables returned.
Now Testing the query returns nothing
image

We use this Grafana dashboard company-wide to troubleshoot data for all our IoT connected machines.
It looks like the recent committed changes have broken things.
As a customer, I'm concerned that I don't get a chance to test things before accepting changes.
They get done whether we like it or not and now we're left with having to document the malfunction.

I don't think this was the process we were expecting by being Grafana cloud users.

**Comment by itsmylife** [comment]
Hi @gefaila Thanks for your test and feedback. I appreciate such detailed feedback. 
Thanks for your patience. I had a health issue so I wasn't able to answer quickly.
I am sorry that you had a poor experience. There was indeed a bug and I failed to test well and act fast on it. 
The problem should have been fixed with this https://github.com/grafana/grafana/pull/88809 
But I see your instance didn't get the changes neither the feature nor the bug fix because of the release channel preference. 
After the new rollout if you'll still face an issue please feel free to create a support ticket. 
In the mean time, I'll test things once more to make sure everything works fine.

**Comment by gefaila** [comment]
Hey @itsmylife thanks for your response.  It was much appreciated. Hope you are feeling fine now. :-)

Yes you are correct.  Support have informed me that the new fix will take 4 wks to hit our instance.
That's fine.

Can you advise if there is a way that we can see in advance if any fixes have broken any functionality *before* we accept the fix?
I was thinking if we had *two* instances which were synchronised, one (sandbox) which gets things quickly and is less fussy, and one (production) which is more conservative and only gets mature changes.  Then we can beta test things and notify in advance before the problems hit our production instance.  Can you advise?

**Comment by itsmylife** [comment]
@gefaila I feel not fully good but definitely better. Thanks for asking. 

In normal process, this should've been detected before hitting to people's instances. But in that case, the issue was not tested properly or not tested enough. That is on me and also my status affected the case. 

Your thinking is quite valid and useful. You can create two instances one is let's say dev and the other is prod. dev is on a faster release cycle and prod is a bit slow. So on dev, you'll see the latest features quite fast (nightly or daily). So you can see if there are any unwanted side effects. 

In the meantime, I'll create a ticket for us to have more tests in place to catch potential bugs.

**Comment by gefaila** [comment]
HI @itsmylife , 
I can report that the fix has apparently again hit my instance but can also report that it breaks our dashboards.
However (the good news), I know what the problem is.

My variables use a flux query referring to "v.timeRangeStop"
      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)

The fix that has been implemented has broken any queries referring to v.timeRangeStop

The start working again when you implement the following hack
    |> range(start: v.timeRangeStart, stop: now())

So v.v.timeRangeStart works but after the fix v.timeRangeStop doesn't

However, I'm again now really worried that we can have untested fixes that hit our instance.
I'll take this up with support and refer to this github issue.

Meanwhile, can you reproduce and fix?

**Comment by itsmylife** [comment]
@gefaila I think the `v.timeRangeStop` issue related to something else. And I think I've already fixed it (I am suspecting about some other problem) but maybe not yet hit your instance. But just to make sure please create a support ticket and I'll check and confirm my theory. I'll keep you posted.

**Comment by itsmylife** [comment]
@gefaila I checked your instance and [the fix](https://github.com/grafana/grafana/pull/89347) wasn't rolled out yet to your instance. I suggest you open a support ticket and we will continue from there.

**Pull request merged**
