### PR TITLE
Plugins: allow dashboards for plugins to be restriced to Grafana versions

### PR DESCRIPTION
**Pull request by gingerwizard**
## Overview

This PR introduces allows dashboards for plugins to be limited to specific Grafana versions. It extends the `includes` schema to allow a `supportedVersions` property to be specified. This is a full semantic version and is effectively a constraint on the grafana version. If the constraint is not satisfied when the dashboard is considered for import, it is not made available to the user.

If the dashboard has already been imported and does not satisfy the constraint, it is marked as incompatible - the user is allowed to remove only. Currently, we don't support allowing dashboards to be upgraded if they are incompatible - see below.

## What does this solve?

Dashboards are compatible with specific releases of Grafana. As new major and minor releases of Grafana introduce new visualizations, there is an opportunity to improve existing dashboards through more useful and appropriate visualizations. Updating visualizations introduces challenges of backwards compatibility. Currently, we would be required to distribute all versions of the dashboards with the plugin and require the user to select the appropriate one to install - possibly based on naming. This is obviously not sustainable and would require us to remove dashboards from plugins as they become deprecated. Dashboards can also rely on specific plugin features, however e.g. if a type of query is only supported by a specific plugin release.

## Assumptions

1. We assume all dashboards in the plugin have a unique uid - this **PR enforces this ignoring dashboards which don't have one**. This is a breaking change - we may want to list dashboards without a uid but prevent install and include a message. If an existing dashboard needs to be made available for a new version of Grafana it should be saved with a new uid. It can be named the same as previous versions which can remain. 
2. We rely on the user ensuring the constraints limit installation appropriately and don't check for overlaps (as we have no concept of dashboard groups or de-duping through allowing the same uid). This could lead to the "same" dashboard being listed multiple times if the constraints permitted. In future we could have a grouping id or allow identical uuids and de-duplicate to the highest compatible version.
3. We still support the upgrade functionality if the revision number changes in the dashboard file.
4. Compatibility is tested for installed dashboards and upgrades offered where appropriate - delete only if no upgrade and incompatible.

## Minor notes

1. We use semver and strip off the pre-release. The current semver lib [doesn't support pre-release ](https://github.com/Masterminds/semver#working-with-prerelease-versions)comparisons - this breaks testing on beta releases and during dev. Its unlikely a dashboard would be limited to specific beta releases so this seemed reasonable.
2. Dashboard deletion now uses uid. Previously it was relying on uri which was resulting in "not found" issues. Uid is used on the main Grafana dashboard listing to delete dashboards and now this is being proposed as mandatory it made sense to use this.

## Screenshots

**Imported incompatible dashboard**

image

### CODE REVIEW

**Comment by gingerwizard** [comment]
A simple enhancement to this PR might be to detect when a imported dashboard is no longer compatible but the version on disk is - offering the user an upgrade. The uid should allow us to do this. We would still assume dashboard uids within a plugin were unique i.e. only one dashboard per uid (we could check this). If a user wanted to update a dashboard they would then have 2 options:

1. Update the dashboard, retaining the uid, and update its compatible versions in the plugin.json
2. Create a new dashboard with a different uid, adding it to the plugin.json with the compatible versions.

(2) would mean the user would see the old version imported (marked as incompatible) AND the new one. This should be sufficiently flexible.

@josiahg

**Comment by gingerwizard** [comment]
We appear to have a service https://github.com/grafana/grafana/blob/main/pkg/plugins/plugindashboards/service.go#L55 responsible for auto-updating dashboards. This should still work but we might want to make sure we're comfortable with this behaviour.

**Comment by gingerwizard** [comment]
thanks @toddtreece this should be a fairly easy change. I think we still want to render old dashboards of type "dashboard" as well.

Can we maybe think of having a transition path here? We ideally won't want to keep both sets of types around.

We could wait until 8.2 is no longer supported by plugins to transition entirely to dashboard-versioned (allow dashboard at this point as well for versioned dashboards) - this won't be until 9.x is released I assume?

**Comment by bergquist** [comment]
Closing this since it's out of date.

**Pull request closed without merging**
