### PR TITLE
Add FolderUID for library elements

### PR DESCRIPTION
**Pull request by idafurjes**
Reverts grafana/grafana#83776

### CODE REVIEW

**Review by papagian — COMMENTED** [review]
I have managed to reproduce the failure before 27610b03f7fd5f775bc38bf35256544ff16c1694 and verified that this commit fixes it 🎉 

The steps to reproduce are:
1. Create in `main` an hierarchy like:
* folder 1
    * dashboard 1
    * dashboard 2
2. create a library panel under `folder 1`
3. switch to this branch
4. revert 27610b03f7fd5f775bc38bf35256544ff16c1694
5. start the server; the migration fails
6. revert step 4 (eg hard reset to the `origin/revert-83776-revert-79572-deprecate_folderid_library_elements`)
7. start the server; the migration succeeds

**Review by kaydelaney — APPROVED** [review]

**Comment by kaydelaney** [comment]
Do you think we could backport this? Fixes an issue related to an escalation: https://github.com/grafana/support-escalations/issues/9996 @idafurjes

**Pull request merged**
