### PR TITLE
Chore: explore possibilities of using makefile

### PR DESCRIPTION
**Pull request by markelog**
This is an exploratory commit - I wanted to see how
revive/gosec linters could be integrated with makefile and our build scripts.

Looks better then I expected :)

-- 

Additionally, revive execution was not supplied with path, when you correct it, there is couple errors popped up - so I fixed them

### CODE REVIEW

**Comment by bergquist** [comment]
Whats the upsides of this solution? Given we dont really use make for anything else.

**Comment by markelog** [comment]
> Given we dont really use make for anything else.

If the proposed general approach is good enough, I would like to expand capabilities of the our makefile (like most of the `backend-lint`). 
And implementing more integration and benchmark tests

> Whats the upsides of this solution?

There is two types of befenifits I think specific for this case and in more general sense. For this case - 

1. It's now easier to execute revive and gosec tools separatly - you wouldn't have to execute the whole `backend-lint` script
1. With repetitve use (contrast to `backend-lint`), go will not try to download those linters again
1. With local go.mod we wouldn't have faced #16764

In the long run I think it would allow simplification and speed ups of our CI set up as well.

Going forward I would want to implement more integration and benchmark tests with makefile

**Comment by torkelo** [comment]
that is interesting, sounds like some good upsides. 

@xlson any thoughts?

**Comment by xlson** [comment]
I think this is great. While we obviously need to support developers who don't have access to make, we already do that by having access to the vital build functionality via build.go. Adding stuff like linters to the Makefile makes it a lot easier to use locally than having to use the bash scripts. Not sure if we can get ci improvements out of the Makefile (as the caching functionality wont work out of the box), but if that's possible that'd be great.

**Review by xlson — APPROVED** [review]

**Comment by markelog** [comment]
Yeey! So happy :)

Regards,
Oleg

**Pull request merged**
