### PR TITLE
MSSQL: Add support for macro function calls

### LINKED ISSUE #59843: MSSQL: Cannot interpolate commas in macros
**What happened**:
During editing of queries for an SQL Server datasource the following bug (imo) with macros happens.
If you use commas inside of a grafana macro, the comma which is part of the SQL Query is incorreclty parsed as part of the macro.
1) Comma when no parameters exepcted:
`$__time(try_convert(datetime, Timestamp))` => `try_convert(datetime AS time)`❌
this results in an SQL error: `db query error: mssql: Incorrect syntax near the keyword 'AS'.`
2) Comma when multiple parameters exepcted:
`$__timeGroup(try_convert(datetime, Timestamp), 30m)` => ❌
this results in a grafana error: `error: interpolation failed: error parsing interval Timestamp`

**What you expected to happen**:
The interpollation of macro's should take parenthesis into account. Or comma's should be able to be escaped.
1) `$__time(try_convert(datetime, Timestamp))` => `try_convert(datetime, Timestamp) AS time` ✔
2) `$__timeGroup(try_convert(datetime, Timestamp), 30m)` => `FLOOR(DATEDIFF(second, '1970-01-01', try_convert(datetime, Timestamp))/1800)*1800` ✔

**How to reproduce it (as minimally and precisely as possible)**:
Use a comma inside of a parameter of a macro.

**Environment**:
- Grafana version: 9.2.6
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None
- Others: SQL Server 15.0.4188.2

### PR DESCRIPTION
**Pull request by mdvictor**
**What is this feature?**

Add support in the MSSQL DS for function calls to be used as parameters in macros

**Why do we need this feature?**

Add possibility for users to use function calls as params in macros

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #59843

### CODE REVIEW

**Review by zoltanbedi — COMMENTED** [review]
Can you please add tests?

**Comment by zoltanbedi** [comment]
Can you also check if we can use https://github.com/grafana/grafana-plugin-sdk-go/pull/594 ?

**Review by baldm0mma — APPROVED** [review]
Nice!

**Comment by mdvictor** [comment]
> Can you also check if we can use [grafana/grafana-plugin-sdk-go#594](https://github.com/grafana/grafana-plugin-sdk-go/pull/594) ?

Looked over the helpers but it seems they do not take into account nested parantheses (function calls). I've mostly looked at this parsing method: https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-8d3ae64630cf5679400666d740706df993625a011531ce7b9530d24f4bf7ed73R137

**Comment by zoltanbedi** [comment]
> > Can you also check if we can use [grafana/grafana-plugin-sdk-go#594](https://github.com/grafana/grafana-plugin-sdk-go/pull/594) ?
> 
> Looked over the helpers but it seems they do not take into account nested parantheses (function calls). I've mostly looked at this parsing method: https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-8d3ae64630cf5679400666d740706df993625a011531ce7b9530d24f4bf7ed73R137

What about this test? https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-72bd1749e19ef2bd3ce26341beafb45a3c52779680c43f1893144d61e85df14dR111

**Comment by mdvictor** [comment]
> > > Can you also check if we can use [grafana/grafana-plugin-sdk-go#594](https://github.com/grafana/grafana-plugin-sdk-go/pull/594) ?
> > 
> > 
> > Looked over the helpers but it seems they do not take into account nested parantheses (function calls). I've mostly looked at this parsing method: https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-8d3ae64630cf5679400666d740706df993625a011531ce7b9530d24f4bf7ed73R137
> 
> What about this test? https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-72bd1749e19ef2bd3ce26341beafb45a3c52779680c43f1893144d61e85df14dR111

oh man, I should've looked better on those :)) thanks Zoltan! Seems like they are supported. I will look better and use that implementation

**Comment by mdvictor** [comment]
@zoltanbedi The `sqlutil` helpers are really great and we could/should refactor all our sql-based datasources to use it. I've tried it out on a separate branch and it would reduce our code to a couple steps: adapting the query to `sqlutil.Query`, overriding macro logic for specific language usecase and calling `sqlutil.Interpolate` with the query and macro.

The problem with this, for now, is that it breaks on comma when splitting the arg list. In [data/sqlutil/macros.go:230](https://github.com/grafana/grafana-plugin-sdk-go/pull/594/files#diff-8d3ae64630cf5679400666d740706df993625a011531ce7b9530d24f4bf7ed73R230) the arguments are split by comma, which would, for a function call param with multiple arguments result in an error.

e.g: For a query containing `$__timeGroup(try_convert(datetime, Timestamp), 30m)`, we would have the param string after stripping macro name and parantheses `try_convert(datetime, Timestamp), 30m`, which would then be split by comma resulting in: `try_convert(datetime`, `Timestamp)`, `30m`.

I'll contact the plugin sdk devs and present this issue to them. In the meantime, I'd say we can move forward with this implementation and later on dedicate some time for a more thorough refactor against all our sql-based datasources when a fix gets implemented in the library? What do you think?

**Comment by zoltanbedi** [comment]
@mdvictor thanks for taking a look. 

> I'll contact the plugin sdk devs and present this issue to them. In the meantime, I'd say we can move forward with this implementation and later on dedicate some time for a more thorough refactor against all our sql-based datasources when a fix gets implemented in the library? What do you think?

Sounds good.

**Pull request merged**
