### PR TITLE
Table: Support nested data frames for chart cells 

### PR DESCRIPTION
**Pull request by torkelo**
Revisiting https://github.com/grafana/grafana/pull/41994 

* New transform named `Time series table` that turns multiple time series frames into a single frame, by turning labels to fields, and the whole frame gets added as the frame field value. Missing lots of options, and a way to group by label to group frames together to a single row (with multiple data frame fields to have a single table that have say 3 chart columns ) 
* New table option for cell height (sm, md, lg) 

TODO
* [ ] How to show value as well for the frame (last,  avg, etc) 
* [ ] Sort by the frame field 
* [ ] Refine transform with options and way to group series (to have multiple charts in one row) 
* [ ] Possibly create a new panel that takes the transform + table to create `Time series table` visualization 

Ideally, the subData feature could also be rewritten to use a data frame field instead (marked for use as subData). 

Waiting for
https://github.com/grafana/grafana/pull/59363

**Unrelated** 
Table.tsx is in great need of a major refactoring, the use of useState for the expanded items is super messy, should use the Table reducer instead, not sure why we have two state systems for the Table component. 

Screenshot from 2022-12-28 08-17-41

### CODE REVIEW

**Comment by domasx2** [comment]
This is great, really looking forward to it!

Re

**Comment by domasx2** [comment]
This is great, really looking forward to it!

> How to show value as well for the frame (last, avg, etc)
Could just be a separate column driven by a separate query?

**Comment by torkelo** [comment]
> Could just be a separate column driven by a separate query?

@domasx2 

why would it be a separate query? would require more complex joining transform. But sure it's possible. But I think it's unnecessary we have the data already (just need to calc the avg or pick the last value from the time series data points). And having it represented as a separate column is a bit strange. I think the time series chart column should still be sortable, for it to be sortable it needs to represent a value.

**Comment by domasx2** [comment]
@torkelo 

> why would it be a separate query? would require more complex joining transform. But sure it's possible. But I think it's unnecessary we have the data already (just need to calc the avg or pick the last value from the time series data points).

Last value is easy, but it might not always be possible  for example  to accurately calculate an average? Say if you have a series of average durations per interval, I think you can't use it to accurate calculate an average duration for the entire range because weights for each value are not known

**Comment by domasx2** [comment]
Closing in favor of new iteration: https://github.com/grafana/grafana/pull/63182

**Pull request closed without merging**
