### PR TITLE
Auth Proxy improvements

### PR DESCRIPTION
**Pull request by roelgerrits**
- adds the option to use ldap groups for authorization in combination with an auth proxy
- adds an option to limit where auth proxy requests come from by configure a list of ip's
- fixes a security issue, session could be reused

Related issue: #2549

### CODE REVIEW

**Comment by utkarshcmu** [comment]
#4280 issue failed CircleCi build for this PR too. Please re-trigger this PR's CircleCI build too. :)

**Comment by torkelo** [comment]
Is there a reason why this needs to be integrated into grafana? Can you not use LDAP authentication in the nginx proxy / http proxy and then use the the auth_proxy feature as usual?

**Comment by roelgerrits** [comment]
Hi @torkelo,

This PR is an improvement of the authentication proxy feature to integrate the ldap authorization functionality for role/org management.

Currently there are two options for our use case:
- Use ldap authentication and authorization with ldap groups
- Use the auth proxy feature and manage roles manually in grafana

With this PR grafana can delegate (two-factor) authentication to a proxy and manage authorization with ldap groups. It's totally optional, when the ldap feature is not configured the auth proxy still works as it used to.

As a security improvement I added the option to whitelist trusted authentication proxies that can provide the authentication header.

On top of this I added a small fix to the authentication proxy to completely clear the session in case the authentication header changes and the cookie remains the same.

There are more people interested in this feature see issue: #2549

Maybe there is another way?
Let me know what you think about it,

Roel

**Comment by seuf** [comment]
Is it possible to rebase and merge this PR ? This feature is very important for us :)

**Comment by torkelo** [comment]
closing this as it seems to have drifted a bit from master, 

Feel like we have enough auth options in Grafana, they can (and will approve), but combining both auth proxy and ldap integration seems like a special case that is better handled outside grafana (where ldap can be handled in the auth proxy). 

More rich integrated auth options will hopefully be added via backend plugins (when that concept has been implemented, https://github.com/grafana/grafana/issues/6841). 

If this is a very important feature, please vote on the feature request (https://github.com/grafana/grafana/issues/2549)

**Pull request closed without merging**
