### PR TITLE
Tracing: Trace to metrics default range

### LINKED ISSUE #64872: tracesToMetrics uses exact time not a range when jumps to metrics so the graph is empty
**Describe the bug**
If you setup "tracesToMetrics" and click on the Metrics link on a Span, the dashboard that will be opened will have the exact same timestamp for `From` and `To`, e.g.:
```
From: 2023-03-15 13:45:38
To:   2023-03-15 13:45:38
```

This will result in an empty panel. Though if the user will select a time range, data shows up.

**To Reproduce**
0. Setup Tempo and enable tracesToMetrics feature (see example setup below)
1. Start Tempo `2.0.1` ot `latest`
2. Open a trace, click on the metrics link of one of the spans
3. See that no data is on the rendered graph
4. Modify the time range of the dashboard, the data should show up

**Expected behavior**
Data should be visible out of the box so some kind of default time-range should be defined.

**Environment:**
 - Infrastructure: local, Docker
 - Deployment tool: Docker Compose

**Additional Context**
Example setup:
```
tracesToMetrics:
  datasourceUid: prometheus
  tags: [...]
  queries:
    - name: "Throughput"
      query: "sum(rate(http_server_requests_seconds_count{$$__tags}[$$__rate_interval]))"
```
You can find my whole setup here: [datasource.yml](https://github.com/jonatan-ivanov/teahouse/blob/7c8eacbf3f728bc07ae07b5c775bf7b91de48ee3/docker/grafana/provisioning/datasources/datasource.yml#L26-L33)

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Adds a default range to our trace to metrics feature.

**Why do we need this feature?**

So trace to metrics works out of the box with useful results.

**Who is this feature for?**

Tracing users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/64872

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by adrapereira — APPROVED** [review]

**Comment by aocenas** [comment]
@joey-grafana why 2m? Seems very arbitrary and not necessary for long spans. Why don't we just make the time range have some minimal value like 1s or 1m if it is smaller?

**Comment by joey-grafana** [comment]
So we discussed a time range of about 5 minutes during stand up/in the linked issue a few times so thought that an even 2 either side would suffice. Why is this not necessary for long spans? Are you suggesting to change the start range to -1s and end range to 1s (or 1m)? Up until now we we had no range which meant a trace to metrics link click would basically not show any data in the metrics query unless the range was manually was configured. Now it will work out of the box and I am hoping we get feedback over time so we can tweak the default range.

**Comment by joey-grafana** [comment]
To be clear, what I mean here is that we don't have a large enough range to show any results. I'm aware we don't show <1s so but the user never actually sees any metrics for their trace at all because of the range. 

I think with logs we have to be a lot more careful as there can literally be thousands of logs over a very short amount of time but with metrics we're rendering a graph over time and it's easier to drill down into the results they want. Again, with the previous default range of 0 users would see no metrics at all. The goal here was to present the user with some data as opposed to no data, while allowing us time to gather feedback and adjust as necessary. 

Agreed that we want to keep the time ranges as close to the span start-end while also getting data. Definitely don't want to present the user with too much metrics data when they click through a link but I'm just not sure what is the best range and why. It feels like a bit of a guess at this point in time. If there is a particular time range you have in mind, please lmk.

**Comment by aocenas** [comment]
@joey-grafana
As I mentioned in the comment one of these approaches would work better imho:
- min(span.timerange, N * scrape interval)
- arbitrary timerange offset but highlight the span.timerange region in the graph
- or probably a combination of those even

Seems like you fish for a particular value but as I said I don't think that makes sense overall and there is no "good" value whoever we would ask. That is why I think we should change the approach here.

**Comment by joey-grafana** [comment]
Highlighting the timerange in the graph would be neat. I didn't fully understand what you were suggesting before but this makes more sense. Not sure how plausible these are atm but with some work could improve on our current approach :) I'll open an issue for this.

**Pull request merged**
