### PR TITLE
Add comma delimiter option to export data modal and file export

### PR DESCRIPTION
**Pull request by jwilles**
Fixing issue #9748 by adding option to delimit CSV export with comma instead of default semicolon.

### CODE REVIEW

**Comment by torkelo** [comment]
This does not seem to truly solve the underlying problem of https://github.com/grafana/grafana/issues/9748  which is that escaping should be delimiter aware and double escape the delimiter? 

Can't see where the escaping happens though in file_export https://github.com/jwilles/grafana/blob/3b69c101408070eb7dbb7398ef373491458eae83/public/app/core/utils/file_export.ts

**Comment by jwilles** [comment]
Yeah you're right that it does not necessarily address the underlying problem but I thought it might be a good fix because I noticed a number of other requests for the option.

I haven't looked into the escaping itself yet. I assume that it is done on view and not in the export though.

**Comment by jwilles** [comment]
Perhaps the better option would be to double quote the fields on export?

**Comment by torkelo** [comment]
think this is fixed by https://github.com/grafana/grafana/pull/11740

**Pull request closed without merging**
