### PR TITLE
AzureMonitor: Update allowed namespaces

### PR DESCRIPTION
**Pull request by jcolladokuri**
**What this PR does / why we need it**: Adds a new resource type for the public cloud. See https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/when-to-use-hyperscale-citus-to-scale-out-postgres/ba-p/1958269#:~:text=Hyperscale%20%28Citus%29%20is%20the%20integration%20of%20the%20Citus,options%20available%20to%20you.%20%28See%20Figure%201%20below.%29

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
Thanks @jcolladokuri! Checking this [doc page](https://docs.microsoft.com/en-us/azure/governance/resource-graph/reference/supported-tables-resources), it seems that there are some other namespaces missing too:

```patch
Microsoft.DBforPostgreSQL/flexibleServers
+ Microsoft.DBforPostgreSQL/serverGroups
+ Microsoft.DBforPostgreSQL/serverGroupsv2
Microsoft.DBforPostgreSQL/servers
+ Microsoft.DBforPostgreSQL/serversv2
```
Could you also add those?

**Comment by jcolladokuri** [comment]
@andresmgot thank you for pointing them out, I have added them as well.

**Review by andresmgot — APPROVED** [review]
LGTM. Thanks!

**Comment by taleena** [comment]
@andresmgot looks like the milestone was removed by the bot, did this end up making it out?

**Comment by daniellee** [comment]
@taleena it didn't make 8.5.2. It just missed the cut-off time. The backport is for 8.5.3 which will be released this week probably: https://github.com/grafana/grafana/pull/48634

**Pull request merged**
