### PR TITLE
Navigation: add breadcrumbs in Explore page

### LINKED ISSUE #54271: Page layout: Explore
- [x] Add breadcrumbs using `pageNav`

### PR DESCRIPTION
**Pull request by eledobleefe**
**What this PR does / why we need it**:
This PR will add the breadcrumbs needed on the Explore page

**Which issue(s) this PR fixes**:
Fixes #54271

**Special notes for your reviewer**:
It is done using the `layout` prop instead of `pageNav`.

### CODE REVIEW

**Comment by gelicia** [comment]
@eledobleefe Just to be clear here, what is added is only visible for people with the topnav feature flag on?

**Comment by gelicia** [comment]
There is a margin difference even with the topnav off. I personally don't feel like that should block this, but the team should give a 👍 .

Screen Shot 2022-08-31 at 12 24 26 PM

**Comment by Elfo404** [comment]
I think this needs more work before being merged.
aside from the issue mentioned by @gelicia (which i personally think is quite important, especially in split view when those extra pixels makes a difference) it is not impossible to scroll each pane separately (you can reproduce this by splitting the explore view and having one query for each pane showing some results in the page.


something else that needs some attention IMHO (but i don't think should block this PR, and should be on our squad, just food for thoughts) is the toolbar itself. I think we can make use of the breadcrumb area more efficiently like in  dashboards:
- we probably can remove the icon & Explore title from the left pane given it's present in the breadcrumb
Screenshot 2022-08-31 at 20 52 11

- the share button can be moved like in dashboards (we got feedback that the share button is not really discoverable, making it look exactly the same as dashboards would probably improve the situation)
Screenshot 2022-08-31 at 20 57 32

- the split button may be moved to the right section of the "breadcrumb" given it's a page level action (up to debate, it may also be confusing to have the split button up there and close buttons in each pane)
Screenshot 2022-08-31 at 21 00 50

- dashboards have the time picker in this area. i know we struggled a bit with the active state for the buttons, but maybe we can move the range picker up there when it's in in the "linked" state given - as per the previous point - it affects both panes.
Screenshot 2022-08-31 at 21 01 38
Screenshot 2022-08-31 at 21 04 51

The new layout looks great btw, it'd be awesome if we could fix the padding and scrolling issue before merging 🚀

**Comment by eledobleefe** [comment]
Hi @Elfo404, hi @gelicia! Thanks for your comments :) I'll look for another workaround to avoid the padding and scrolling issues.

**Comment by eledobleefe** [comment]
As `Explore` is a unique case, we decided to get rid of the `Page` component, which triggers more cons than pros, and show the breadcrumbs using Grafana Context. What do you think @Elfo404 @gelicia?

**Review by Elfo404 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
