### PR TITLE
Devenv: OpenLDAP-Mac improvements

### PR DESCRIPTION
**Pull request by mgyongyosi**
**What is this feature?**

This PR improves the openldap-mac development environment by removing unnecessary module setup and changes the seed data to work correctly. 

**Why do we need this feature?**

With the current setup the `memberOf` attribute is not set in LDAP thus `ldap-editor` does get the Viewer role after a successful login. Based on https://github.com/osixia/docker-openldap/issues/258#issuecomment-433903239 the seed data has been changed to use `groupOfUniqueNames` and `uniqueMember` and then the `memberOf` attribute is set correctly.

**Special notes for your reviewer**:

Please test it on MacOS.

### CODE REVIEW

**Comment by eleijonmarck** [comment]
@mgyongyosi I have a similar improvement that I have tested out.

@linoman you wanted to see if daniel would take a look with it? 🤔 
https://github.com/grafana/grafana/pull/56364/files

**Comment by mgyongyosi** [comment]
@eleijonmarck Are you sure that your changes work correctly? My biggest issue was the missing `memberOf` attributes: when I logged in with `ldap-editor` the user could successfully logged in but with Viewer role. That's why I had to change `groupOfNames` to `groupOfUniqueNames` as suggested by the linked comment.

**Review by IevaVasiljeva — APPROVED** [review]
I just tested (logged in with ldap-admin, ldap-editor and ldap-viewer, and made sure that the correct roles are assigned to them), and this works great! Thanks for adding it!

**Review by linoman — APPROVED** [review]
There seem to be 2 problems here.

1. `ldap-editor` was being set with a `viewer` role for this docker block. This is being corrected by the changes in `devenv/docker/blocks/auth/openldap-mac/prepopulate/3_groups.ldif`
2. We're fixing these blocks only in little pieces. My suggestion is to get @bergquist (not daniel) involved. He might know the context of this block and help design scenarios that need to be covered by this devenv.

We could approve these changes (and thus @eleijonmarck PR) for now.

I can set up a meeting with @bergquist to see if we can design more robust documentation on these devenvs.

**Pull request merged**
