### PR TITLE
Plugins: Wrap original check health error

### LINKED ISSUE #69765: Plugins: Incorrectly dropping the original check health error
When returning an error from `CheckHealth` the original error (coming from a backend plugin) is dropped/lost which makes it hard for users/operators to understand what the original error is. The code in question:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/plugins/manager/client/client.go#L199

The API error handling:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/api/plugins.go#L504-L506

Currently, the Grafana log message becomes the following, notice the error:
"logger=context orgId=1 t=2023-05-25T21:50:53.22+0200 lvl=eror msg="Plugin health check failed" error="failed to check plugin health: health check failed""

Should be noted that the original error would be logged if the following logic evaluates to true:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/plugins/backendplugin/instrumentation/instrumentation.go#L84
Which is based on the following setting:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/conf/defaults.ini#L1401

### PR DESCRIPTION
**Pull request by kousikmitra**
**What is this feature?**

Wrap the original health check error

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #69765 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Thank you. It would be nice to add a/some tests for this that verifies `errors.Is(err, backendplugin.ErrHealthCheckFailed)` is true. Maybe you can copy and modify below to a TestCheckHealth? https://github.com/grafana/grafana/blob/f649619e20accdcbb78f628c968b51a75d403be5/pkg/plugins/manager/client/client_test.go#L18

Let us know if you're up for this.

**Review by marefr — APPROVED** [review]
LGTM great work

**Review by xnyo — APPROVED** [review]
LGTM, great work! Thank you!

**Comment by marefr** [comment]
@kousikmitra thank you for contributing to Grafana

**Pull request merged**
