### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Update changelog for version 6.7.0-beta1.

### CODE REVIEW

**Comment by xlson** [comment]
You should run the script that gathers the changelog for this release and add it to this PR

**Comment by aknuds1** [comment]
@xlson OK thanks

**Comment by aknuds1** [comment]
@xlson Please have another look.

**Review by xlson — CHANGES_REQUESTED** [review]
Need to add these as well:

https://github.com/grafana/grafana-enterprise/pulls?q=is%3Apr+is%3Aclosed+label%3Aadd-to-changelog+milestone%3A6.7.0-beta1

**Review by xlson — APPROVED** [review]
Looks good!

**Pull request merged**
