### PR TITLE
TimeSeries: Fix memory leak on viz re-init caused by KeyboardPlugin

### LINKED ISSUE #53310: Explore: investigate potential memory leaks
https://raintank-corp.slack.com/archives/CKF4X4H1D/p1658236452772189

### LINKED ISSUE #53313: __Potential memory leak__ The web-app crashes as long as you don't interact with it long enough
**What happened**:
The Grafana dashboard page was left up on display.
The dashboard has 6 panels that use transformation methods.
The memory used by the page was observed to be increasing non-stop.
The page would eventually crash. (seen reach 5 GB at one point)
Interacting with the page resets the memory usage to 150~300 MB.

**What you expected to happen**:
Leaving the page on display on an android device
with 2GB of RAM shouldn't cause the web-app to crash within an hour.
(or at all for that matter)

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana.
Login to a dashboard that has 6 panels that use the transformation feature.
Leave it open without interacting with it. (you can interact with anything else)
Observe the memory used by the tab/page/process going up.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 9
- Data source type & version:
   -- Prometheus, with Prometheus v2.36.2 server
   -- queries are many, about 20 of the following sort:
       ---- "sum( rate(ifInOctets{instance=\~"switch0[1-3].\*"}[2m]) + rate(ifOutOctets{instance=\~"switch0[1-3].\*"}[2m]) ) * 8"
       ---- *5* "Add field from calculation" transformations followed by *1* "Organize fields" transformation in **ONE** of the panels.
       ---- *1* "Rename by regex" transformation in **ONE** of the other panels.
- OS Grafana is installed on: Linux
- User OS & Browser: (Windows 10 / Windows 11 / Android 9) & (Chrome / Firefox / Brave / Opera)
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by leeoniya**
Fixes https://github.com/grafana/grafana/issues/53310
Fixes https://github.com/grafana/grafana/issues/53313

you can verify in Chrome's task manager (Shift+Esc) by doing 20x refreshes of this 10-series random-walk Explore page:

http://localhost:3000/explore?orgId=1&left=%7B%22datasource%22:%22PD8C576611E62080A%22,%22queries%22:%5B%7B%22scenarioId%22:%22random_walk%22,%22refId%22:%22A%22,%22seriesCount%22:10%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Nice!

Sucha a dummy mistake we made :(

**Comment by hoerup** [comment]
Could this solve #50820 as well ?

**Review by Elfo404 — APPROVED** [review]
<3 sweet!

**Comment by leeoniya** [comment]
> Could this solve https://github.com/grafana/grafana/issues/50820 as well ?

yes, likely, but i don't _think_ we have plans to do non-security backports/releases of 8.4.x at this point, so you'll probably have to apply the changes yourself and rebuild.

**Comment by leeoniya** [comment]
> Sucha a dummy mistake we made :(

but also Explore force-invalidates and re-inits the plot on every data update, which doesnt help the situation, @Elfo404 wanna look into that ;) ?

**Comment by Elfo404** [comment]
@leeoniya will do :)

**Pull request merged**
