### PR TITLE
graph: initial histogram support #600

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Support of Histogram mode for Graph panel, issue #600
This is initial implementation for review and discussion.

### CODE REVIEW

**Comment by torkelo** [comment]
This looks really great @alexanderzobnin , would be great to move the histogram related parts to its own file (graph.ts is so long already) and maybe add 2-3 unit tests.

**Comment by alexanderzobnin** [comment]
@torkelo yea, also thought about that. Also I use some code parts from heatmap, it makes sense to share this functions between panels. May be as a part of refactor.

**Comment by torkelo** [comment]
yea, sharing code is a good idea, can be put into app/core/

**Comment by torkelo** [comment]
great work alex!

**Pull request merged**
