### PR TITLE
@grafana/ui: EditorField tooltip interactive

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

I want to add a link in a `EditorField` tooltip and for it to be clickable the tooltip should be `interactive`. AFAIK, there is no harm making it interactive but let me know if this should be an option, I can move the setting to a property.

**Special notes for your reviewer**:

I know there is [a conversation to move (at least part of) this components to @grafana/experimental](https://github.com/grafana/grafana/pull/52421#issuecomment-1266896771) but it's not there yet so I am adding the patch here, hopefully this patch will be migrated as well if needed.

### CODE REVIEW

**Comment by joshhunt** [comment]
Not up to me, but I would recommend against putting links/interactable content in tooltips tbh.

**Comment by andresmgot** [comment]
> Not up to me, but I would recommend against putting links/interactable content in tooltips tbh.

why?

**Comment by andresmgot** [comment]
That sounds like something that should be decided by the author of the tooltip? For example, having a short tooltip: `Using "foo" will cause "bar". See the [documentation](link) for more information.` sounds better to me to try to summarize complicated stuff in a tooltip. 

There are many cases in which tooltips can have useful links but if we want to default to discourage it, we can keep the default of not making them interactive.

**Review by JoaoSilvaGrafana — APPROVED** [review]
As part of the design system work, our guidance for `Tooltip` will be for it to never be interactive and instead use another component that works differently from `Tooltip` in terms of how to open/close/etc (probably named `ToggleTip`). However, that component does not exist yet and since we do this in other places I think it is ok to add `interactive` here as well. We can change this to that component once it is created.

**Pull request merged**
