### PR TITLE
[wip] feat(graph): allow suppression of empty panels

### PR DESCRIPTION
**Pull request by vitorboschi**
Adds feature #4470 

I still want to make the changes take effect immediately, but for now there's a need to refresh the dashboard.

### CODE REVIEW

**Comment by vitorboschi** [comment]
When editing the panel, there's a new option to suppress the panel when no data is received:
image


And panel suppression can be disabled on dashboard settings:
image

**Comment by torkelo** [comment]
I am not sure if this is the best way to solve this feature, of if it's a big enough issue or a problem to warrant a complex new option an handling. Very wary to add new features that only a very small fraction of users will use but will have to be supported and maintained for all eternity :)

**Comment by vitorboschi** [comment]
I'm not sure this is the best way to solve the problem, but this issue seriously limit my ability to make use of repeated panels, and I guess the same happens with other opentsdb users. I'm not sure if this is a problem for other backends though

**Comment by nerk01** [comment]
I've got some dashboards that end up with graphs that have no matching data when used with templates.  It would be nice to have those graphs not render.

**Comment by tfylling** [comment]
I would love this feature on both row and template repeats, alternatively on a dashboard level.
A few examples where it would be extremely useful is when selecting multiple network interfaces from multiple hosts, where some are using ethX and others are using emX, have different vlans etc. A dashboard where half the panels are empty has no value, and there is no good way to work around the issue.

Another example is statistics from multiple databases with different names across hosts.

**Comment by torkelo** [comment]
closing this as it has been [wip] for a long time and drifted from master

**Pull request closed without merging**
