### PR TITLE
Prometheus: Fix problem where changing display name in Field tab has no effect

### LINKED ISSUE #29437: Prometheus: Field display name has no effect
image

I haven't found a way to change this ...

Can you tell me how to do this?

grafana 7.3.3

### PR DESCRIPTION
**Pull request by zoltanbedi**
**Which issue(s) this PR fixes**:

Fixes #29437 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
I can still see two places where displayName is set 
Small/large aren't necessarily for handling resolution or file size, but more for different visuals. SignalFx, for example have both "SignalFx" and "SFx" logos; each with different applications.

**Comment by zoltanbedi** [comment]
That is just the name of the object that is passed to getValueField function. I've changed the property in getValueField. Should I rename these properties?

**Review by torkelo — COMMENTED** [review]
I think that is fine, maybe rename it to just name for that function to avoid confusion

**Review by torkelo — APPROVED** [review]

**Review by ivanahuckova — APPROVED** [review]
LGTM! 🍧 I also like that you have renamed `displayNameFromDS` in `getValueField` so it is more clear what is happening. 👍 for test.

**Pull request merged**
