### PR TITLE
Auth: Add dynamic regex organization mapping

### PR DESCRIPTION
**Pull request by exolicious**
**What is this feature?**

This feature introduces a new way to dynamically extract a part of an external role as the organization and another part of an external role as the actual role (Viewer/Editor/Admin) to map the role to the extracted organization (if an organization with that name exists).
It uses a regex that should contain exactly two capture groups and is configured via:

example:
```toml
[auth.generic_oauth]
org_mapping_regex = "^PREFIX_.*_(.*)_.*_(VIEWER|EDITOR|ADMIN)_SUFFIX"
```

**Why do we need this feature?**

In a multi tenant environment with a huge number of organizations and a complex IAM system behind it, adding new mappings is very tedious. 
If you have the mapping implicitly in an external role itself, it can be used instead of potentially having an org mapping length of > 1000 (**while also having to edit that org mapping everytime a new organization gets added**)

**Who is this feature for?**

Everyone whose grafana is connected via an external IDP which has some kind of role concept that already maps an organization to a role.

**Which issue(s) does this PR fix?**:
-

**Special notes for your reviewer:**

Right now there are some caveats and design decisions that i do not want to make alone.
- The Regex needs to have exactly two capture groups (one for the org name and one for the role, typically this would be something like: (Viewer|Editor|Admin))
- Should the strictRoleMapping apply to this new feature?
- To be able to run unit tests the dynamic mapper first turns the org name lowercase then capitalizes the first letter -> what should/could we do here? A variable called org_mapping_regex_mapped_org_case= title_case | upper_case | lower_case ?
- I am sure there is still some stuff wrong with this and not yet ready to merge, but this feature would be really really helpful to us and i believe many others

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

regarding the docs, the create-pull-request-md mentions that if there are configuration changes one should update "docs/sources/administration/configuration.md" however it seems that this file does not exist it, so this feature would still need to be documented somewhere, but i do not know where exactly would be the right place

### CODE REVIEW

**Comment by exolicious** [comment]
@cinaglia could you please have a look at this?

**Comment by exolicious** [comment]
@torkelo @drclau anyone?

**Comment by exolicious** [comment]
@torkelo Is there any chance this gets looked at? Would be great to know if this could be merged - and if not, we can start investing into implementing a pipeline that patches our changes and automatically tests them, when new releases are available. But please let us know, so we can plan accordingly. We really want this feature (and pretty sure it would be very convenient for many others too)

**Comment by exolicious** [comment]
@IevaVasiljeva can you maybe look at this?

**Comment by azlux** [comment]
Is still a PR we can hope on ?

**Pull request closed without merging**
