### PR TITLE
feat: Updated whats-new-in-v11-0.md with release video

### PR DESCRIPTION
**Pull request by Jayclifford345**
Grafana 11 release video added to whats new in Grafana 11 page!

### CODE REVIEW

**Comment by imatwawana** [comment]
Hey @Jayclifford345, congrats on your first contribution! We don't typically add this particular video to the What's new page, but let me loop in someone else to review and get their opinion. @mjseaman, what do you think of this addition as a regular thing?

**Comment by Jayclifford345** [comment]
Hi @imatwawana, ah no worries the content team mentioned I should try and get it posted in the docs under what's new since we also had the feature videos there.

**Comment by imatwawana** [comment]
> Hi @imatwawana, thank you very much :)! I have mostly been in the Loki docs so excited to add something to the main Grafana repo to :D. ah no worries the content team mentioned I should try and get it posted in the docs under what's new since we also had the feature videos there.

I'll leave it up to @mjseaman. If he approves, I'm fine with it!

**Comment by mjseaman** [comment]
I love it; let's give it a try!

**Review by mjseaman — APPROVED** [review]

**Comment by Jayclifford345** [comment]
Hi, @imatwawana do you think we could give this a merge? :)

**Comment by imatwawana** [comment]
> Hi, @imatwawana do you think we could give this a merge? :)

Sorry about that, I was on PTO. Merging now!

**Pull request merged**
