### PR TITLE
Zipkin: Remove `workspace:*` from `package.json`

### PR DESCRIPTION
**Pull request by fabrizio-grafana**
Related to [this](https://github.com/grafana/grafana/pull/83117).

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]

**Review by andresmgot — COMMENTED** [review]
Actually, can you also update the deps versions to its latest? That should also help:

```patch
--- a/public/app/plugins/datasource/zipkin/package.json
+++ b/public/app/plugins/datasource/zipkin/package.json
@@ -6,7 +6,7 @@
   "dependencies": {
     "@emotion/css": "11.11.2",
     "@grafana/data": "11.0.0-pre",
-    "@grafana/experimental": "1.7.8",
+    "@grafana/experimental": "1.7.10",
     "@grafana/o11y-ds-frontend": "11.0.0-pre",
     "@grafana/runtime": "11.0.0-pre",
     "@grafana/ui": "11.0.0-pre",
@@ -18,13 +18,13 @@
   },
   "devDependencies": {
     "@grafana/plugin-configs": "11.0.0-pre",
-    "@testing-library/jest-dom": "6.3.0",
-    "@testing-library/react": "14.1.2",
-    "@types/jest": "29.5.11",
+    "@testing-library/jest-dom": "6.4.2",
+    "@testing-library/react": "14.2.1",
+    "@types/jest": "29.5.12",
     "@types/lodash": "4.14.202",
-    "@types/react": "18.2.48",
+    "@types/react": "18.2.55",
     "ts-node": "10.9.2",
-    "webpack": "5.90.0"
+    "webpack": "5.90.2"
   },
   "peerDependencies": {
     "@grafana/runtime": "*"
```

**Comment by fabrizio-grafana** [comment]
Yep. There is already [another PR on that](https://github.com/grafana/grafana/pull/83143), so I was waiting for that to be merged and then rebase this.

**Comment by jackw** [comment]
FYI - whilst there's no harm in doing this you shouldn't need to for decoupled plugins. It is only an issue for packages that reference other grafana packages in this repo.

**Comment by fabrizio-grafana** [comment]
> FYI - whilst there's no harm in doing this you shouldn't need to for decoupled plugins. It is only an issue for packages that reference other grafana packages in this repo.

Closing this then!

**Pull request closed without merging**
