### PR TITLE
Plugins: add a deprecated state

### PR DESCRIPTION
**Pull request by ryantxu**
We need a panel state that will allow existing dashboards to keep working, but not allow people to create new panels with that visualization.  In particular the `singlestat` and angular `table` panels should prefer the `stat` panel or the react table panel.

This PR adds a `deprecated` state and applies it to the singlestat panel

### CODE REVIEW

**Comment by ryantxu** [comment]
NOTE: totally untested since my master build currently looks like:
image
I will go to sleep now :)

**Review by dprokop — APPROVED** [review]
Legit. Wonder if we should indicate on dashboard view that panel is deprecated? or at least when going to edit mode. Since going to edit mode will no longer display Singlestat panel maybe we could have migration suggestion? Like suggested Stat panel that use clicks and tadam, is migrated.

**Comment by dprokop** [comment]
@ryantxu synced with master, now it works

**Comment by ryantxu** [comment]
Can you merge if it looks ok?

**Comment by dprokop** [comment]
yeah, on it

**Review by dprokop — COMMENTED** [review]
Tested and it works like charm 👍

**Pull request merged**
