### PR TITLE
Chore: enforce feature naming convention

### PR DESCRIPTION
**Pull request by ArturWierzbicki**
This PR adds a test which will enforce `camelCase` naming convention for feature names. The test ignores all already existing feature names breaking the convention ([pattern](https://sirupsen.com/shitlists))

https://raintank-corp.slack.com/archives/CACC9JCFQ/p1650533635827309

### CODE REVIEW

**Comment by eleijonmarck** [comment]
Great to have it available. Nice work.

I wanna see if we instead make a PR check instead of a test

**Comment by ArturWierzbicki** [comment]
> Great to have it available. Nice work.
> 
> I wanna see if we instead make a PR check instead of a test

Any reason for a separate PR check? One of the PR checks already runs the tests, so the PR checks will fail if someone adds a feature with an invalid name.

Also, tests make the feedback loop super tight. In general, you have to run the typescript&golang enum generator (`pkg/services/featuremgmt/toggles_gen_test.go`) before you can use a new feature flag. With this PR, the generator will also let you know if the name is invalid :)

**Comment by eleijonmarck** [comment]
I thought it is outside of test scope.

The reason is there is real no functionality that we have to test. Rather a convention. But the feature toggle is in code and cannot be changed in PR directly (much like we do with backport) now that I think about it.

So might as well have a test for it.

No real preference here.

**Review by eleijonmarck — APPROVED** [review]
Let's do this!

**Review by ryantxu — APPROVED** [review]
this is great

**Pull request merged**
