### PR TITLE
Added caching of proxies for data sources

### PR DESCRIPTION
**Pull request by Tenzer**
As I mentioned in #2236 I implemented a cache of the `ReverseProxy` instances used by the proxy endpoint. It does currently not update when a data source is updated, so any feedback on how this could be added would be much appreciated.

I'm still pretty new to Go so feedback on how it's implemented would also be nice :)

### CODE REVIEW

**Comment by torkelo** [comment]
thanks, but it really needs to handle updating of proxies, and it would be nice if the cache also cached the data source SQL request.

**Comment by Tenzer** [comment]
So what would be the way of making it then? The caching of the SQL request is easy, I don't know why I missed that.

Looking at the bus system I guess sending an event when a change (either update or deletion) happens to a data source, which could clear the cached item for that data source could work. Does that sound like an okay solution?

**Comment by torkelo** [comment]
@Tenzer no, we need a cache abstraction or invalidation method that can be distributed. 

Invalidating the cache in the local instance is not enough as there can be multiple instances (when grafana-server is hosted in a larger fault tolerant setup behind load balancer)

**Comment by Tenzer** [comment]
Okay, got it. I think I'll pass on this then, at least for now.

**Pull request closed without merging**
