### PR TITLE
Fixed reinitialise of Explore

### LINKED ISSUE #15015: Explore: Cannot go from dashboard to explore (or via url)
* Change data source to Loki in explore
* Go to a dashboard with a Graph with Prometheus data source (or any data source)
* Use panel menu to go to explore. Loki data source still selected. 

Seems like the URL state data source cannot change the last local storage saved data source (a guess).

### PR DESCRIPTION
**Pull request by hugohaggmark**
Fixes #15015 

- Cleaning up state when leaving Explore view
- Small boy scouting added CoreActionTypes

### CODE REVIEW

**Review by davkal — COMMENTED** [review]
While this works, I think I prefer it if `initialized` was set to `false` via an action on component unmount. I hope that makes it less brittle than tying it to an URL change event.

**Comment by hugohaggmark** [comment]
Ok will look into firing of an action instead.

**Comment by hugohaggmark** [comment]
Is this better @davkal ?

**Comment by davkal** [comment]
Works well! Are you happy with it @hugohaggmark ?

**Comment by hugohaggmark** [comment]
Yes, much clearer now. Great suggestion!

**Pull request merged**
