### PR TITLE
chore(deps): bump visx/tooltip to 1.7.2

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
@mckn and I found an issue with react-use-measure dependency overwriting the grafana-ui build exports (#31603). The author of react-use-measure has since merged a fix(pmndrs/react-use-measure/pull/38) and published a new version. Airbnb have now brought this into their visx/tooltip dependencies. This PR bumps visx/tooltip to 1.7.2 and removes the need for the interim fork that was created.

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
LGTM! Let's make this thing work!!!  🙏

**Comment by zoltanbedi** [comment]
Wouldn't it be better to upgrade the `@visx/tooltip` instead?

**Comment by zoltanbedi** [comment]
Also we can remove the `RUN apk --no-cache add git` from the dockerfile now, can't we?

**Comment by dsotirakis** [comment]
> Also we can remove the `RUN apk --no-cache add git` from the dockerfile now, can't we?

@zoltanbedi High chances that we may need to add it again. 
I checked the size of the produced docker image in the past when added `git` and nothing changed, so it can still stand there I think.

**Review by mckn — CHANGES_REQUESTED** [review]
I think upgrading visx to this version would be better. Then we can remove the resolution for this.

https://github.com/airbnb/visx/blob/master/CHANGELOG.md#v172-2021-03-18

**Review by mckn — APPROVED** [review]
Booom! LGTM

**Pull request merged**
