### PR TITLE
Search: Adds tests to `SearchView`

### PR DESCRIPTION
**Pull request by JoaoSilvaGrafana**
**What this PR does / why we need it**:

Adds unit tests to the search component `SearchView`

**Which issue(s) this PR fixes**:

Relates to #50856

**Special notes for your reviewer**:

This component is more about being a composition of different components depending on what is selected, so not sure what else to test.

### CODE REVIEW

**Comment by JoaoSilvaGrafana** [comment]
> Do we really need to backport to 9.0? I think targeting 9.1 makes more sense

Sure, makes sense!

**Review by ryantxu — APPROVED** [review]
🌮

**Review by ashharrison90 — APPROVED** [review]
lgtm 👍

**Review by axelavargas — APPROVED** [review]
🚀 really nice!

**Pull request merged**
