### PR TITLE
Explore: collapsible result panels

### LINKED ISSUE #13738: Explore: Graph and Table toggles are not obvious
The toggles for Graph and Table are not obvious. I'd like to create a better experience.

An idea would be to not have buttons above the panels, but rather to have the panels collapsible so that in their collapsed state, the related query is not run.

### PR DESCRIPTION
**Pull request by davkal**
- replace the Graph/Table buttons with toggle control in a wrapper panel
- moved toggle control to left to be close to the label
- removed panel styles from Logs and Graph viewer
- moved loader animation to panel

Fixes #13738

### CODE REVIEW

**Comment by torkelo** [comment]
Nice, any screenshots to share?

**Comment by davkal** [comment]
It's a start. Could be improved. At least it solves the issue with the buttons.

screenshot 2018-11-16 at 19 39 19

**Review by torkelo — APPROVED** [review]
Looks good, but a little bit worried about more custom explore panel component & styles & behaviors are going to make it it trickier to align explore with with the new react visualization components, that I think we should aim to do soon (~1month). So that Explore is using the same Graph, Table components that dashboards panel plugins use. 

https://github.com/grafana/grafana/tree/master/public/app/viz

But should not be that hard to do even with this. but something to keep in mind

**Comment by peterholmberg** [comment]
The label on the toggle changes font size and jumps when toggling. Which means that you can miss the toggle when toggling back and forth.

out

**Comment by davkal** [comment]
@peterholmberg agreed. toggle-ability goes before gimmicky.

**Comment by davkal** [comment]
Removed transition by reverting to approved state.

**Pull request merged**
