### PR TITLE
Chore: remove expressions flag and allow

### PR DESCRIPTION
**Pull request by ryantxu**
DataSources using the new backend infrastructure all hit an endpoint that is guarded by the feature flag `expressions`

This should be removed before 6.7 release

### CODE REVIEW

**Comment by kylebrandt** [comment]
I'm not sure this feature flag should be removed from 6.7, rather perhaps it should only apply to Transformations.

I believe @marefr was looking at something related to move transformations to dedicated rest api endpoint? (or more simply, move it down in the function to before the transformation call.

**Comment by ryantxu** [comment]
the option to add expressions in the UI requires the 'transformations' flag

**Comment by kylebrandt** [comment]
> the option to add expressions in the UI requires the 'transformations' flag

Yes, but at least right now that is a different feature - and backend transformations should still be behind a feature flag I think.

**Review by kylebrandt — CHANGES_REQUESTED** [review]
Backend transform still needs to be behind feature flag for security reasons.

**Review by marefr — APPROVED** [review]
Related to #22643 which splits query and transform into two endpoints. 

I was under the impression that expression feature toggle was used for both frontend and backend - when did that change?

LGTM

**Comment by ryantxu** [comment]
> I was under the impression that expression feature toggle was used for both frontend and backend - when did that change?

It is... there is also a "transformations" flag that is used to show the frontend transformations (not the same as things getting transformed on the backend)

**Review by kylebrandt — APPROVED** [review]
Thanks!

**Pull request merged**
