### PR TITLE
Datasources: Adding EMR Serverless Metrics for Cloudwatch datasource.

### PR DESCRIPTION
**Pull request by DugeraProve**
Adding EMR Serverless Metrics for Cloudwatch datasource.

### CODE REVIEW

**Comment by idastambuk** [comment]
Hi @DugeraProve thanks for you contribution! 

Can you also add the dimensions from the [docs](https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/app-job-metrics.html) in the NamespaceDimensionKeysMap in the same file? Thanks!

**Comment by idastambuk** [comment]
@DugeraProve thanks for the update. One more nit: I notice that the indentation of the new entries is a bit off, can you update it? Thanks!

**Comment by DugeraProve** [comment]
> @DugeraProve thanks for the update. One more nit: I notice that the indentation of the new entries is a bit off, can you update it? Thanks!

@idastambuk sorry about that, I think that should be fixed now.

**Review by idastambuk — APPROVED** [review]

**Comment by idastambuk** [comment]
Hi @DugeraProve, I was just going to merge this but I see that it's been closed. I cant find another equivalent PR, is there a reason you closed it?

**Comment by DugeraProve** [comment]
Sorry I did a second PR for another metrics set AWS Kafka Connect, and it appears that PR caused this one to close

**Comment by DugeraProve** [comment]
Reopening

**Comment by DugeraProve** [comment]
Sorry I lost this work and can't reopen this PR, I have added the changes to my other PR https://github.com/grafana/grafana/pull/79532 Apologies for the messiness of this, first time contributer and ran into issues with my local setup that caused this PR to close.

**Pull request closed without merging**
