### PR TITLE
Tempo: Escape regex-sensitive characters in span name before building promql query

### LINKED ISSUE #54849: Service Graph does not work if `span_name` contains regex-sensitive characters.
**What happened**:
- Go to Explore.
- Select Tempo datasource.
- Select Query type Service Graph.
- Set filter to `namespace` = `abcdef`

Response:
```
Query error
bad_data: invalid parameter "query": 1:104: parse error: unknown escape sequence U+002F '/'
```

image

**What you expected to happen**:

Service Graph displayed without errors.

**How to reproduce it (as minimally and precisely as possible)**:

- Enable exporting metrics to Prometheus from traces
- Create a span with regex-sensitive characters in the span name, for example `some-server.abcdef.svc.cluster.local:9090^\/config.grpc.?(.*)`

Why the weird span name? I have no idea. These traces are generated by [Spring Cloud Sleuth](https://spring.io/projects/spring-cloud-sleuth) and I'm assuming there's some automatic trace gathering and naming in there.

**Anything else we need to know?**:

It seems Grafana does a couple of queries to Prometheus to discover all of the span names.

The second last response to Grafana contains

```
{span_name=\"some-server.abcdef.svc.cluster.local:9090^\\\\/config.grpc.?(.*)\"}
```

That leads to a request with queries like
```
{"refId":"topk(5, sum(rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",namespace=\"abcdef\",span_name=~\"some-server.abcdef.svc.cluster.local:9090^\\/config.grpc.?(.*)|some-server.abcdef.svc.cluster.local:9090/*|some-server.abcdef.svc.cluster.local:8080^\\/config$|^\\/config\\/.*|some-server.abcdef.svc.cluster.local:8080/*\"}[$__range])) by (span_name))"
```

Which leads me to think that Grafana tries to be clever and use regex query (`=~`) to retrieve X time-series in one round-trip. (I.e. filter span_name to be a|b|c|d and then sum by span_name to get all the individual timeseries.

But this fails since Grafana doesn't process and escape the `span_name` before passing it back to Prometheus with the regex-operator.

**Environment**:
- Grafana version: v9.1.2
- Data source type & version: Tempo 1.5.0 and Prometheus 2.35.0

### PR DESCRIPTION
**Pull request by gordeevnm**
**What is this feature?**

Fix for errors like "bad_data: invalid parameter "query": 1:87: parse error: error parsing regexp: invalid nested repetition operator: `**`" or "invalid parameter "query": 1:104: parse error: unknown escape sequence U+002F '/'"

This comment is a copypaste of this comment https://github.com/grafana/grafana/issues/54849#issuecomment-1335517259
I tried it locally and it works as expected

**Who is this feature for?**

Anyone who uses the service graph

**Which issue(s) does this PR fix?**:

Fixes #54849, https://github.com/grafana/grafana/issues/63697

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by adrapereira — CHANGES_REQUESTED** [review]
Thanks for the contribution @gordeevnm! 
Do you mind extracting this new logic to a function and adding some tests? It would be amazing if we could have a couple of tests of cases that were failing before these changes that are now fixed.

**Comment by gordeevnm** [comment]
Oh. Honestly, I'm not familiar with any of grafana's tools and the language. It will take a century for me to learn the stack and write tests 😅
I'll definitely try to find time for that, but it would be cool if someone will make this pr ready to merge

**Review by adrapereira — APPROVED** [review]
LGTM! Left a comment to fix a typo but we can merge otherwise.

**Comment by gordeevnm** [comment]
Guys, your're the best!

**Pull request merged**
