### PR TITLE
Tempo: New Search UI using TraceQL

### PR DESCRIPTION
**Pull request by adrapereira**
**What is this feature?**

This PR adds a new tab to the Tempo datasource with a new Search UI powered by TraceQL, under the `traceqlSearch` feature flag. The goal is to provide an easy to use, point and click interface that users can interact with to generate queries and take advantage of the power of TraceQL to efficiently select traces from Tempo.

Each filter of the UI is backed by a `TraceqlFilter` type that links a `tag`, `operator` and `value` in the following format `tag operator value`. A list of filters is joined by the `&&` operator to generate the final query `{ filter1 && filter2 && ... }`.

**Static fields** are fields that have their tag pre-set and hidden, like for example the `Service Name` or `Duration`. 
**Dynamic fields** are fields that don't have any part pre-set, like for example the fields from the Tags sections. 

In the Tags section it's possible to add and remove fields as required. Since there's no filtering on the tag input for each field, it's possible to have multiple of the same tag in a query. This can be useful if we want to write a query like `{tag > 23 && tag <= 50}`.

All of the fields are stored in the `TempoQuery`, which means that users can share the URL and Grafana will show exactly the same UI to everyone (as long as the Grafana version is the same), same operators, same values, same dynamic tags, etc.

https://user-images.githubusercontent.com/4313971/221829542-8ac65f68-ddac-4e32-bd2c-2de8a3d5d87c.mov

**Why do we need this feature?**

Most users don't want to learn another query language and won't also need all of the features of TraceQL, so providing a UI that can perform most of the work and be easy to use can help drive adoption of Tempo. 

**Who is this feature for?**

All Grafana users that use Tempo for tracing and want to easily use TraceQL to build queries. 

**Which issue(s) does this PR fix?**:

Fixes #63267

**Next steps**

This feature will stay under the feature flag until considered ready for general access, by which point it should replace the current `Search` tab and be renamed accordingly. 
It would also be nice to have a button to quickly copy the generated query to the `TraceQL` tab and navigate there, so users can further customize the query.

### CODE REVIEW

**Comment by aocenas** [comment]
Some functional notes:

For service name and span name we could probably remove some of the operators like `>` `<` as I don't think they make sense there or do they?

Is it possible to use the multiselect without the main `X` button? Seems very close to the dropdown.
Screenshot from 2023-03-01 10-19-08

Maybe it's just me but I am always confused by duration thresholds. Wonder if having 2 labels like `from: [     ] | to: [     ]` or `duration min: [      ] | max: [     ]` would make it easier to parse.

For the tags inputs can we use the UI we have in loki/prometheus?
Screenshot from 2023-03-01 10-16-57

Also similar to prom/loki I would do the traceQL preview not as a read only editor but just syntax highlighted text. This still seems like it is editable input.

**Comment by aocenas** [comment]
Also can we instead of adding a new tab just change the old search tab? I think that will be less confusing, people will be forced to use it when testing which should give us more feedback.

**Review by joey-grafana — COMMENTED** [review]
Just a few observations. Other than our standup chat about the tab and Andrej's comments above I think this looks pretty good.

**Comment by aocenas** [comment]
Looks good but there seems to be an issue with custom values:
Screenshot from 2023-03-03 11-40-06

It seems like the custom value is accepted and saved in state otherwise it probably wouldn't be in the generated traceQL query but isn't shown in the select anymore.

**Review by aocenas — APPROVED** [review]
Nice looks good now

**Comment by 09jvilla** [comment]
> Static fields are fields that have their tag pre-set and hidden, like for example the Service Name or Duration.

> Dynamic fields are fields that don't have any part pre-set, like for example the fields from the Tags sections.


What do you mean by "tag pre-set" and "hidden" here? I'm guessing based on your description that static fields are the ones that always show up and dynamic fields are ones that you can add in the "tags" part of the UI. But I don't see anything that appears "hidden" about service name or duration?

Are the static fields configurable at all today? I know we had some back and forth about what the static fields should be - I think service name and span name are good for now, but on our call with one user they indicated they wanted to choose specific static fields that reflected the tagging convention they used at their company. 

@adrapereira

**Comment by 09jvilla** [comment]
> It's an implementation detail, the "dynamic" fields are what we add in the Tags section, but behind the hood the "static" fields use the same data structure and component but with the tag field already pre-filled so we hide the dropdown to select a tag.

Got it. Thanks for the explanation. 

> They aren't at the moment, but it's relatively easy to make them configurable. I plan to make the required changes to support this soon!

Amazing!

**Comment by cyrille-leclerc** [comment]
This looks great.

**Pull request merged**
