### PR TITLE
#33931 Save timerange to localstorage for restoring

### LINKED ISSUE #33931: [FeatureRequest] Add possibility to copy time range to use the same range in different grafana dashboards
I would like to have copy button to copy time range. 

My scenario is pretty simple. 
1. I open a grafana dashboard with `URL 1` in `browser tab 1`. 
2. I want to analyze data in the same time range, therefore I open grafana dashboard with `URL 2` in `browser tab 2`. 
3. Right now, I have to manually choose time range in the second dashboard tab, but instead of I want just copy it to clipboard from the first tab and insert it to the second tab. 

image

### PR DESCRIPTION
**Pull request by Hixon10**
I've added 2 new buttons for saving and restoring the timerange. 

image

Closes #33931

### CODE REVIEW

**Comment by torkelo** [comment]
Can you open a feature request where you explain the underlying problem / use can you are trying to solve? 

My initial impression is that there might be another solution for the thing these buttons are trying to solve. 

Do you want to move between dashboards and remember/preserve time range? 

The time picker already stores and list past time ranges, what is missing from that feature?

**Comment by Hixon10** [comment]
@torkelo hello! Yep, I've already created a task, connected with this PR - https://github.com/grafana/grafana/issues/33931

Basically, you are right. I want to move between dashboards (opened in different browser tabs) and remember/preserve time range.

Yes, the time picker already stores and list past time ranges, but it seems, it does not work for my case. This list is not updated in my case, when I open several browser tabs with different dashboards and try to troubleshoot an issue using different time ranges. For example, I want to set up some time range in the first opened tab, and use the same range in all different opened tabs (they are already opened, when I set a needed time range in the first tab).

**Comment by Hixon10** [comment]
@mckn @kaydelaney hello! May I ask you to review this PR, when you have some time?

**Comment by Hixon10** [comment]
@torkelo hello! Maybe you have some time to take a look at this PR, or the initial idea :)

**Comment by torkelo** [comment]
Sorry, but think you have to open a feature request that describes your unique scenario and get more demand from the community. As it stand adding these buttons for what feels like a very limited use case is not something we can merge right now.

Is there other ways to solve your problem is the question? This solution feels too much of a hack (making the UI cluttered with buttons)

**Comment by Hixon10** [comment]
Thanks for the response.

**Pull request closed without merging**
