### PR TITLE
Docs: fix the grammar in code-styleguide.md

### PR DESCRIPTION
**Pull request by ademidoff**
**What this PR does / why we need it**:
It fixes the grammar.

**Which issue(s) this PR fixes**:
None

Fixes  - none

**Special notes for your reviewer**:

Please also note, that `https://github.com/grafana/worldmap-panel/blob/master/.eslintrc` does not exist (referenced in `Linting` section) .

### CODE REVIEW

**Review by oddlittlebird — APPROVED** [review]
Good catch! Thanks for contributing to the docs.

**Comment by oddlittlebird** [comment]
@aknuds1 , why is this failing?

**Comment by aknuds1** [comment]
Please merge with latest Grafana master in order to get CI fixes.

**Comment by bergquist** [comment]
Thank you for contributing!

**Pull request merged**
