### PR TITLE
Sparklines should scale to the data range

### LINKED ISSUE #11949: [feature request] Auto-scale singlestat sparklines
The current sparklines seem to always be relative to zero.  I have a metric that is always increasing and I want the sparkline to represent changes in that rate.  When the numbers are big, it is always flat:

image

Even though the values increased by 2000 in that time window

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #11949

Without the patch:
image

With the patch (and option selected):
image

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure I understand this, this seems to use data min/max as the y axis auto range , is this not the default behavior already. 

The two images you show seem strange, must be a bug in the first image to make the slope only show up as a line?

**Comment by ryantxu** [comment]
I was also surprised that the default: `{ yaxis: {show: false} }` does not auto-scale the same way it does in the normal graph panel.  

I tried a few variations to get different behavior, but setting min/max explicitly was the only way I found to get things to look correct

Note that when the numbers are smaller, the slope is noticeable, but at large numbers things look like a flat line.

**Comment by ryantxu** [comment]
Here is a dashboard config using the buildin grafana test data (CSV) that shows the issue:
image

[dashboard_json.txt](https://github.com/grafana/grafana/files/2022308/dashboard_json.txt)

**Comment by torkelo** [comment]
so if you show the y-axis the auto y-axis range is fixed? Maybe there is a bug in the flot rendering code that should be fixed instead. I think you have identified a bug, so the full range options should not needed, right?

**Comment by ryantxu** [comment]
Somethign more complicated then just enabling the x and y axis.  I have poked around trying to make the same settings as the standard graph panel, but still have this:
image

**Comment by torkelo** [comment]
Looks like y axis min is set to zero in the middle singlestat , strange , thought that was set to auto

**Comment by torkelo** [comment]
can test and set yaxis min/max to null , that should trigger the default auto scaling that the graph takes advantage of.

**Comment by ryantxu** [comment]
>  can test and set yaxis min/max to null

yes, i tried:
```
        yaxis: {
          show: false,
          min: null,
          max: null,
        },
```
(and a few other variations), but all give the same behavior.  Looking at the existing code is *seems* correct, and I can't find where the zero is coming from.

**Comment by torkelo** [comment]
I found it!  set lines.zero: false! 

```javascript
var options = {
        legend: { show: false },
        series: {
          lines: {
            show: true,
            fill: 1,
            zero: false,
            lineWidth: 1,
            fillColor: panel.sparkline.fillColor,
          },
        },
        yaxes: { show: false },
        xaxis: {
          show: false,
          mode: 'time',
          min: ctrl.range.from.valueOf(),
          max: ctrl.range.to.valueOf(),
        },
        grid: { hoverable: false, show: false },
      };
```

line 583

**Comment by tecmatia-dp** [comment]
Ups! unpleasant surprise this change in 5.2 ...
In some cases, zero reference is important and needed.
I think automatic range should be configurable.
Best would be can set min/max, but a quick approach is a check for "zero: true" or "zero: false".

**Pull request merged**
