### PR TITLE
Login: UX improvements

### LINKED ISSUE #3698: login / signup form layout
This issue is a suggestion for improving the login and signup. When google authentication is enabled, there is a small red button appears below the form. However, I think it'd be much better if the button was above the login signup form, so that the user will see it first and consider it as first priority, rather than an afterthought, down there, below the form. I think users visually exclude stuff that's out of the way, it says login, so users are thinking, oh I have to login on this form, their eyes aren't looking at other stuff. 

Also besides positioning, the google button could be much much larger in size, there are other google buttons that are easier for the user to notice visually. In conclusion, this is a design issue that would be simple to change and make it easier for users to figure out when to use google as the preferred auth.

### PR DESCRIPTION
**Pull request by bergquist**
make buttons bigger and introduce the login divider.

closes #3698

### CODE REVIEW

**Comment by bergquist** [comment]
image

**Comment by torkelo** [comment]
nice!

**Comment by bergquist** [comment]
Some minor ux improvements. The lines besides "Or login with" are a bit lighter compared to the mock-up.  We currently have 5 shades of gray and this was the best one I could find. I don't think we should are more shades. Let me know what you think @mattttt @bulletfactory 


(50 shades of gray jokes are banned in this PR)

**Comment by bergquist** [comment]
image

**Comment by torkelo** [comment]
looks mergable to me :)

**Pull request merged**
