### PR TITLE
Alerting: Improve default message for SensuGo notifier

### LINKED ISSUE #31140: Defaut output message with metrics in SensuGo
**What would you like to be added**:

Grafana  recently added a new notifier SensuGo in 7.4.0.
We use and appreciate this feature but looking at the default message : "[Grafana Metric Condition Met](https://github.com/grafana/grafana/blob/v7.4.1/pkg/services/alerting/notifiers/sensugo.go)" : it could be more precise.

Inspired from notifier [opsgenie](https://github.com/grafana/grafana/blob/v7.4.1/pkg/services/alerting/notifiers/opsgenie.go#L117), we suggest to use customData as default output : 

```
	customData := ""
	for _, evt := range evalContext.EvalMatches {
		customData += fmt.Sprintf("%s: %v\n", evt.Metric, evt.Value)
	}
	....
	bodyJSON.SetPath([]string{"check", "output"}, customData)
	
```

**Why is this needed**:

Usually with existing notifiers in grafana, the default message in alerting contains the relevant metrics.

I do not master Go to submit a PR in good shape ...
We just copied the parts necessary to have the expected result in our own image.

### PR DESCRIPTION
**Pull request by M4teo**
**What this PR does / why we need it**:

It will replace the default notification message "Grafana Metric Condition Met" by relevant metric(s).
Also adding timestamp in the issued event sent to SensuGo API.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/31140

Event created by alerting and visible in sensuGo UI :

sensugo_ui_result

### CODE REVIEW

**Comment by aknuds1** [comment]
You'll need to accept the CLA, and merge with latest master to fix the build.

@nixwiz WDYT of this change, considering you originally introduced SensuGo?

**Comment by aknuds1** [comment]
You'll need to fix the goimports related build error (plus sign CLA).

**Comment by nixwiz** [comment]
> @nixwiz WDYT of this change, considering you originally introduced SensuGo?

@aknuds1 I am good with it, it's a nice addition. 👍

**Review by aknuds1 — COMMENTED** [review]
Can you add a test for this as well?

**Comment by nixwiz** [comment]
@M4teo if interested, Sensu would like to [recognize your contribution](https://sensu.io/register-your-contribution).

**Comment by M4teo** [comment]
@aknuds1 It will just changed the notifier output for more details.
If it's mandatory, i would need help : it's outside my GO skills ^^
@nixwiz  Ok with pleasure.

**Review by aknuds1 — APPROVED** [review]

**Comment by aknuds1** [comment]
I don't have the time to add tests, so let's just merge it.

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Pull request merged**
