### PR TITLE
Chore: Refactors flaky Frontend test

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
I've seen https://github.com/grafana/grafana/blob/main/public/app/features/query/state/mergePanelAndDashData.test.ts fail for some unknown flakiness on several occasions, unfortunately even during releases. This PR refactors it completely to use marble testing instead but keeping the intention of the previous tests. Let's see if this removes the flakiness.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by mckn — APPROVED** [review]
I think this looks good. I'm not 100% sure it gets easier to understand when using the `runMarbleTest` function. It might be easier to understand just with repeating the marble patterns in each test instead.

**Review by ashharrison90 — APPROVED** [review]
lgtm. i think i agree with @mckn about having the functionality in the test itself, but that's probably a personal preference thing 🤷

**Comment by hugohaggmark** [comment]
> I think this looks good. I'm not 100% sure it gets easier to understand when using the `runMarbleTest` function. It might be easier to understand just with repeating the marble patterns in each test instead.

I removed `runMarbleTests` and repeated everything in the tests instead.

**Comment by hugohaggmark** [comment]
> lgtm. i think i agree with @mckn about having the functionality in the test itself, but that's probably a personal preference thing 🤷

Not sure what I follow @ashharrison90 can you explain which functionality I'm using in the test itself?

**Review by ashharrison90 — APPROVED** [review]
lgtm

**Review by mckn — APPROVED** [review]
Awesome work on this!!

**Pull request merged**
