### PR TITLE
Logs: Infinite scrolling in Explore enabled by default

### PR DESCRIPTION
**Pull request by matyax**
Changing the infinite scrolling feature flag to be enabled by default.

Part of https://github.com/grafana/grafana/issues/71728

### CODE REVIEW

**Comment by svennergr** [comment]
I think we should let it run in cloud for some time before we decide to enable it by default for everyone.

**Comment by matyax** [comment]
Good idea.

**Comment by matyax** [comment]
I think this would be cool to have for 11.1

**Review by svennergr — APPROVED** [review]
Let's gooo!

**Comment by matyax** [comment]
Merging after https://github.com/grafana/grafana/pull/88716

**Comment by matyax** [comment]
FYI @stevendungan

**Pull request merged**
