### PR TITLE
Tests: Replaces truth image

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
Seems like e2e-tests are still breaking because of truth image. This replaces it with the one generated by CircleCI.

**Which issue(s) this PR fixes**: 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by bergquist — APPROVED** [review]
LGTM

**Review by marefr — CHANGES_REQUESTED** [review]
Fails for me when running `yarn e2e-tests` locally:

```
console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3000/dashboards

  ● Login scenario, create test data source, dashboard, panel, and export scenario › should pass

    TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

      59 | 
      60 |     console.log('Trying to navigate to:', this.pageUrl);
    > 61 |     await this.page.goto(this.pageUrl);
         |                     ^
      62 |   };
      63 | 
      64 |   expectSelector = async (config: ExpectSelectorConfig): Promise<void> => {

      at Promise.then (node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:110:27)
      at Page.goto (node_modules/puppeteer-core/lib/Page.js:629:49)
      at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:23)
      at TestPage.<anonymous> (public/e2e-test/core/pages.ts:61:21)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at node_modules/tslib/tslib.js:107:75
      at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
      at TestPage.navigateTo (public/e2e-test/core/pages.ts:57:16)
      at Object.<anonymous> (public/e2e-test/scenarios/smoke.test.ts:64:26)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at fulfilled (node_modules/tslib/tslib.js:104:62)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        41.941s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by hugohaggmark** [comment]
> Fails for me when running `yarn e2e-tests` locally:
> 
> ```
> console.log public/e2e-test/core/pages.ts:60
>       Trying to navigate to: http://localhost:3000/dashboards
> 
>   ● Login scenario, create test data source, dashboard, panel, and export scenario › should pass
> 
>     TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
> 
>       59 | 
>       60 |     console.log('Trying to navigate to:', this.pageUrl);
>     > 61 |     await this.page.goto(this.pageUrl);
>          |                     ^
>       62 |   };
>       63 | 
>       64 |   expectSelector = async (config: ExpectSelectorConfig): Promise<void> => {
> 
>       at Promise.then (node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
>         -- ASYNC --
>       at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:110:27)
>       at Page.goto (node_modules/puppeteer-core/lib/Page.js:629:49)
>       at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:23)
>       at TestPage.<anonymous> (public/e2e-test/core/pages.ts:61:21)
>       at step (node_modules/tslib/tslib.js:133:27)
>       at Object.next (node_modules/tslib/tslib.js:114:57)
>       at node_modules/tslib/tslib.js:107:75
>       at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
>       at TestPage.navigateTo (public/e2e-test/core/pages.ts:57:16)
>       at Object.<anonymous> (public/e2e-test/scenarios/smoke.test.ts:64:26)
>       at step (node_modules/tslib/tslib.js:133:27)
>       at Object.next (node_modules/tslib/tslib.js:114:57)
>       at fulfilled (node_modules/tslib/tslib.js:104:62)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 1 total
> Snapshots:   0 total
> Time:        41.941s
> Ran all test suites.
> error Command failed with exit code 1.
> ```

It's is supposed to run on a clean install @marefr

**Comment by hugohaggmark** [comment]
@marefr 
```bash
docker run -d -p 3003:3000 grafana/grafana-dev:master-fabc6f42412ccaee3c930498d23138b8c463d3b9
ENV BASE_URL=http://localhost:3003 yarn e2e-tests

$ jest --runInBand --config=jest.config.e2e.js
 PASS  public/e2e-test/scenarios/smoke.test.ts (6.99s)
  ● Console

    console.log public/e2e-test/install/install.ts:21
      Checking Chromium
    console.log public/e2e-test/install/install.ts:8
      Found a local revision for browser, exiting install.
    console.log public/e2e-test/core/login.ts:19
      Redirected to login page. Logging in...
    console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3003/login
    console.log public/e2e-test/core/pageObjects.ts:71
      Trying to enter text:admin into: [aria-label="Username input field"]
    console.log public/e2e-test/core/pageObjects.ts:71
      Trying to enter text:admin into: [aria-label="Password input field"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Login button"]
    console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3003/datasources/new
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="TestData DB datasource plugin"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Save and Test button"]
    console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3003/datasources
    console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3003/dashboard/new
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Add Query CTA button"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Queries tab button"]
    console.log public/e2e-test/core/pageObjects.ts:83
      Trying to select text:string:csv_metric_values in dropdown: [aria-label="Scenario Select"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Visualization tab button"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="X-Axis section"] > gf-form-switch
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Save dashboard navbar button"]
    console.log public/e2e-test/core/pageObjects.ts:71
      Trying to enter text:2019-06-13T12:21:36.946Z into: [aria-label="Save dashboard title field"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Save dashboard button"]
    console.log public/e2e-test/core/pages.ts:60
      Trying to navigate to: http://localhost:3003/dashboards
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="2019-06-13T12:21:36.946Z"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Panel Title"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Share panel menu item"]
    console.log public/e2e-test/core/pageObjects.ts:59
      Trying to click on: [aria-label="Link to rendered image"]


Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.423s, estimated 13s
Ran all test suites.
✨  Done in 8.03s.
```

**Review by marefr — APPROVED** [review]

**Pull request merged**
