### PR TITLE
Disable sign out button in case of auth proxy enabled

### LINKED ISSUE #2718: Disable sign out button in case of auth.proxy
It would be cool if the sign out button could be hidden. It is confusing for users it if they login per http auth or something like that. They should not be allowed to sign up or login using the normal grafana login page...

### PR DESCRIPTION
**Pull request by shoonoise**
Closes #2718

### CODE REVIEW

**Comment by shoonoise** [comment]
@torkelo hi! please pay attention to this PR. Is everything ok? May it be merged?  :)

**Comment by shoonoise** [comment]
@torkelo ping

**Comment by torkelo** [comment]
not sure about this, don't like the double check expressions in the html and not sure this warrants new frontend setting

**Comment by shoonoise** [comment]
> not sure about this, don't like the double check expressions in the html and not sure this warrants new frontend setting

@torkelo Do you see any other way to make such changes?

**Comment by torkelo** [comment]
yes, contextSrv.isSignedIn && !authProxyEnabled could be just "showSignup"

**Comment by shoonoise** [comment]
@torkelo I've update PR

**Comment by shoonoise** [comment]
@torkelo will you look at the issue?

**Comment by bergquist** [comment]
Hi

We have been busy stabilizing 2.6.
I'm merging this to master so it will appear in 3.0 or latest once we setup dockerhub with circle ci.

**Comment by solugebefola** [comment]
Is this the only place that the sign out button appears?  It seems as though the sign out button is still visible in the latest version with Auth Proxy enabled.

**Pull request merged**
