### PR TITLE
Loki: Add formatting for annotations

### LINKED ISSUE #29536: Include/Exclude tags from annotations.
**What would you like to be added**:

When doing a Loki query for annotations, it might have too many labels and I may want to select or filter some to show on annotations.

**Why is this needed**:

Loki doesn't support a way to remove labels, not sure it will have that in the future. It seems relatively safe to add.

Example:

image

Here I might want to keep only 2 labels out of those.

### PR DESCRIPTION
**Pull request by fredr**
**What this PR does / why we need it**:
See #29536, when using Loki as a datasource in annotations, all labels are added as tags, and there are lots of tags that are usually not interesting in an annotation, such as filename etc.

**Which issue(s) this PR fixes**:
Fixes #29536

**Special notes for your reviewer**:
Based/copied from the same features in the prometheus datasource.
Default behavior is to show no tags, not sure if that is how we want it? Optionally we could show all, wdyt @ivanahuckova @cyriltovena ?

### CODE REVIEW

**Comment by fredr** [comment]
If you agree with these defaults and this feature, I'll add a better test case

**Comment by Elfo404** [comment]
hi @fredr, thanks for the PR, i'll take a look asap! (looping in also @ivanahuckova )

**Review by ivanahuckova — COMMENTED** [review]
Yaaay! This is amazing. 🤩 Thanks for this contribution @fredr.🧡 Regarding default behaviour, I have reached out to Loki team for their opinion. I personally think, that seeing all tags is a better default behaviour that seeing none. But I see that Prometheus has it opposite way, and it would be nice if we were consistent. 

I am curious, what is your opinion on this?

**Comment by fredr** [comment]
@ivanahuckova I am of the exact same opinion. I did it this way now, since that is how it works in prometheus, but I would rather do the opposite to be backwards compatible for current users of the loki datasource

**Comment by ivanahuckova** [comment]
@fredr Everyone who shared their opinion agrees that all tags should be visible by default. This makes tags more discoverable and as you said, it is backward compatible for current Loki users. So let's just do that. 🙂

**Comment by fredr** [comment]
I've updated the default behavior to include all tags, and added a few test cases

**Review by ivanahuckova — APPROVED** [review]
Looks great! ✨ LGTM.

**Comment by ivanahuckova** [comment]
Let's check if Gio want to check it out. @Elfo404 do you want to look at it or is it okay to be merged? 🙂

**Comment by Elfo404** [comment]
@ivanahuckova @fredr sorry, i really thought to have more time to review this, but I won't probably make it this week. feel free to merge 👍 

just a remark, wouldn't it be better to release this in 8.1 given we are in the middle of a beta and this is adding a new feature?

**Comment by fredr** [comment]
> @ivanahuckova @fredr sorry, i really thought to have more time to review this, but I won't probably make it this week. feel free to merge +1

No worries and no stress, if you want to check it out when you have time, I can wait with merging. Just let me know.

**Comment by ivanahuckova** [comment]
> just a remark, wouldn't it be better to release this in 8.1 given we are in the middle of a beta and this is adding a new feature?
 
I would personally feel confident to add it to 8.0-beta2  as it is well tested feature that was already implemented and is working in prometheus. And it is fully backward compatible. 🙂

**Comment by Elfo404** [comment]
then please, merge :) 🚀

**Comment by fredr** [comment]
Thank you both for taking the time to look at this, squashing it now :rocket:

**Pull request merged**
