### PR TITLE
[wip]added empty list cta to team list

### LINKED ISSUE #12853: Empty Team list has no empty list CTA
skarmavbild 2018-08-09 kl 10 56 20

### PR DESCRIPTION
**Pull request by Ijin08**
if statement toggles view for when the list is empty or not

skarmavbild 2018-08-10 kl 08 54 09

fixes #12853

### CODE REVIEW

**Comment by bulletfactory** [comment]
Visually this looks good but there's a typo in the messaging. Also - what are we going to suggest as a pro-tip? I like the idea, if we have a plan for the content. 

I'm not sure about using the word "defined" here. Maybe created, or added instead. Sounds a little more conversational.

"You haven't created any teams yet."

**Comment by Ijin08** [comment]
Thanks for feedback @bulletfactory 
Changed the messaging.
Not sure about the pro-tip. All I can think of is something about teams and API or permissions. But I don't think we have information on teams and permissions.

**Comment by marefr** [comment]
Seems like we're lacking a specific documentation page for teams why adding a link to protip may be hard or we need to create such a page?

Suggestion:
ProTip: Assign folder and dashboard permissions to teams instead of users to ease administration.

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
