### PR TITLE
[DevEnv] Update `all-panels.json` Dashboard (Include Datasource UID, and v10 Changes)

### PR DESCRIPTION
**Pull request by SeamusGrafana**
**What is this feature?**

This updates the `all-panels.json` Dashboard in the `devenv` folder.

Specifically it adds;

* An explicit Datasource Type and UID to each of the panels (this was missing before and if imported where TestData was not default, it was causing issues)
* Match UID of Panels Datasource to UID of Variables
* Upgrade Panel Config to v10 (previously v8)
* Minor Formatting and Linting Issues.

**Why do we need this feature?**

If importing this Dashboard on an Instance where the TestData Datasource is not the default (for example on GrafanaCloud), the panels would not load and show an error as the Datasource configuration was missing.

**Who is this feature for?**

Developers, Support, anyone who uses the DevEnv and Dashboards.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [X] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by SeamusGrafana** [comment]
Not stale

**Comment by SeamusGrafana** [comment]
Not stale.

@axelavargas or @ivanortegaalba - would either of you be able to take a look at this PR please (not urgent by any means).

Thanks!

**Comment by ivanortegaalba** [comment]
@SeamusGrafana can you take a look at the CI failing? The changes look good so far. Happy to merge it.

**Comment by SeamusGrafana** [comment]
Hey @ivanortegaalba thanks for having a look at this.

I looked at the failing check, but am not sure why its failing, one of them is to do with MySQL which is not something this PR touches, and the other I don't know what its looking at to fail.

Are you able to give me any pointers or suggestions please. Thanks!

**Review by ivanortegaalba — DISMISSED** [review]

**Comment by ivanortegaalba** [comment]
> Hey @ivanortegaalba thanks for having a look at this.
> 
> I looked at the failing check, but am not sure why its failing, one of them is to do with MySQL which is not something this PR touches, and the other I don't know what its looking at to fail.
> 
> Are you able to give me any pointers or suggestions please. Thanks!

Suddenly, I don't have more context than you. I would suggest to dive into the backend tests to see if they are using those panels, and if they have to be updated too.

**Review by axelavargas — COMMENTED** [review]
Hey @SeamusGrafana 👋🏾 , can you update this branch with the main branch? Maybe that will solve the CI failure 🤞🏾

**Pull request closed without merging**
