### PR TITLE
[feature] Add Open-Falcon datasource

### PR DESCRIPTION
**Pull request by hitripod**
[Open-Falcon](https://github.com/xiaomi/open-falcon) is a monitoring system initiated by Xiaomi.

### CODE REVIEW

**Comment by bergquist** [comment]
I'm sorry but we will not merge any new datasources unless they are very popular. I suggest you create an plug-in instead. Please take a look at https://github.com/grafana/datasource-plugin-kairosdb as an example. 

I would suggest you open an issue next time before doing all this work so we could have told you earlier :/

**Comment by hitripod** [comment]
OK, I understand. How do I create a plugin repo for Open-Falcon? 
`https://github.com/grafana/datasource-plugin-openfalcon`

**Comment by laiwei** [comment]
@bergquist 

open-falcon is an open-source,enterprise-level,large-scale service monitoring system and time series database.

Launched by Xiaomi SRE team. which is heavily used in Xiaomi, and now is one of the most popular service monitoring tools in China internet  companies:

- www.mi.com
- www.meituan.com
- www.Xunlei.com
- www.Baidu.com
- www.ksyun.com
- www.douban.com
- www.fastweb.com.cn
- www.ganji.com
- www.upyun.com
- www.xiaojukeji.com
- www.iqiyi.com
- more companies: https://github.com/xiaomi/open-falcon/issues/4

So please reconsider this pull-request, if need any help and more information, please let us know. thanks.
 
Github  http://github.com/xiaomi/open-falcon
Doc  http://book.open-falcon.com

**Comment by modeyang** [comment]
+1

**Comment by langlangago** [comment]
+1

**Comment by heisetukela** [comment]
+1

**Comment by claybbs** [comment]
+1

**Comment by shenghuofei** [comment]
+1

**Comment by wynnfynn** [comment]
+1024

**Comment by fainboy** [comment]
+1

**Comment by zhaoxiaole** [comment]
+1

**Comment by ccj67** [comment]
+1

**Comment by zhangxinlun** [comment]
楼主好人,一生平安.

**Comment by carljiang** [comment]
The best monitor system I ever used!

**Comment by zhouxiaolonggege** [comment]
+1

**Comment by iambocai** [comment]
+1

**Comment by leeypp** [comment]
+1

**Comment by xiaohaoyu** [comment]
+1

**Comment by zbqyexingkong** [comment]
good～

**Comment by workhardcc** [comment]
+1

**Comment by pumpkinmage** [comment]
+1

**Comment by missuzhang** [comment]
+1

**Comment by TuziBen** [comment]
+1

**Comment by freedomkk-qfeng** [comment]
+1

**Comment by masato25** [comment]
+1

**Comment by yy-chen** [comment]
### +++++++1111

**Comment by chlliu** [comment]
+1

**Comment by heafod** [comment]
+1

**Comment by GaoJiasheng** [comment]
Open-Falcon is the best monitor system I have ever used！It helps us cutting down human resources and cost. It is an excellent monitoring system !

**Comment by UlricQin** [comment]
+1

**Comment by yubo** [comment]
+1

**Comment by niean** [comment]
+1

**Comment by JessicaWon** [comment]
Open-Falcon is amazing and popular.

**Comment by crosserclaws** [comment]
+1

**Comment by chyeh** [comment]
+1 lol

**Comment by jumping** [comment]
+1

**Comment by canghai908** [comment]
＋1

**Comment by shenjh369** [comment]
+1

**Comment by H0bby** [comment]
+1

**Comment by kanjianhaian** [comment]
+1

**Comment by kmephistoh** [comment]
Open-falcon is very popular now in China

**Comment by yindashan** [comment]
+1

**Comment by mzycynb** [comment]
+1

**Comment by kozora** [comment]
+1

**Comment by ninjadq** [comment]
+1 
open-falcon is a  scaling friendly monitoring system, both my company and my ex-company are using it to monitor the servers and products

**Comment by 710leo** [comment]
+1

**Comment by soarpenguin** [comment]
+1

**Comment by jolestar** [comment]
+1

**Comment by zhaohongyu** [comment]
+1

**Comment by 51runsky** [comment]
good

**Comment by danche** [comment]
+1

**Comment by wangfakang** [comment]
:kissing_heart:  +1

**Comment by ayouwei** [comment]
+1

**Comment by sanpi** [comment]
+1

**Comment by zuoandeshu** [comment]
+1,please believe in Mr.Lai,thx  (^_^)

**Comment by skyeydemon** [comment]
+1

**Comment by Charlesdong** [comment]
+1

**Comment by chuanxd** [comment]
Open-falcon is very popular monitoring system.
Please reconsider this pull-request.

**Comment by bergquist** [comment]
@hitripod you can create plugins under your own name. But I suggest you wait a few weeks since we are currently working a lot on the plugin system and things might change. After that you can expect some documentation about how to do it.

**Comment by Catchwt** [comment]
+1+1

**Comment by thuhak** [comment]
+1

**Comment by crazw** [comment]
Very good.+1

**Comment by yinchuan** [comment]
expect this!

**Comment by itxx00** [comment]
+1

**Comment by chenchen1750** [comment]
+1

**Comment by itxx00** [comment]
+1

**Comment by bergquist** [comment]
If anyone want to get started working on a plugin for open-falcon you can look at our example implementation of datasource at https://github.com/grafana/simple-json-datasource. Some documentation is available at https://github.com/grafana/grafana/blob/master/docs/sources/plugins/datasources.md

**Comment by itxx00** [comment]
@bergquist  :+1:   thanks for your documentation.

**Comment by lg31415** [comment]
+1

**Comment by lyonliquid** [comment]
Now in weibo,we have applied the open-falcon monitor system to thousands of servers,it satisfy us well！Open-falcon is actrually an amazing ops product！

**Comment by xudong-wen** [comment]
+1

**Comment by bergquist** [comment]
@hitripod @laiwei @lyonliquid any chances you want to help out and make this a plugin? Open falcon seems like an interesting tool but without any English documentation I cant do much.

**Comment by hitripod** [comment]
@bergquist We have created Open-Falcon plugin for Grafana v3.0-beta7, please take a look at: https://github.com/open-falcon/grafana-openfalcon-datasource

Could you please help us publish the plugin so that it could be installed using grafana-cli?

**Comment by bergquist** [comment]
@hitripod I would love to! 

1. First decide who will publish it. you or an organisation? then create an account att grafana.net as yourself or an organisation who will publish this plugin. 
2. Make sure the id in plugin.json matches this format <publisher>-<pluginname>-<type> so in your case it would be hitripod-open-falcon-datasource. 
3. Create some screen shoots of using the plugin like this https://github.com/alexanderzobnin/grafana-zabbix-app/blob/master/plugin.json#L27-L32 Those screenshots will be used on grafana.net
4. Create a PR to https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json to add the open falcon plugin.  

We are working on improving this process :) Ping me if you have any questions!

**Comment by Keleir** [comment]
:+1:

**Comment by teachmyself** [comment]
👍

**Pull request closed without merging**
