### PR TITLE
Modals: Be more consistent with Modal cancel button styling

### PR DESCRIPTION
**Pull request by torkelo**
Most of our modals use secondary outline button for Cancel but many do not. 

image

Already uses outline Cancel:  
* Basic modal storybook story
* Delete library panel
* Create libray panel 
* Add data link modal
* Add value mapping modal
* Add user to organization modal
* Dashboard row options modal
* Save dashboard drawer 
* Save dashbord error modal (When someone else has already updated it before you)
* Unsaved changes model 
* Save provisioned dashboard modal
* Add to dashboard modal
* Open library panel modal

Problem:

Many modals use normal secondary button, even the "ConfirmModal" does which is a generic confirm modal used in many places:

Current: 
image

Decided to go through all modals and update them to outline. 

Updated:

* Confirm modal
* Add notification policy modal
* Select dashboard (for alert rule) modal
* Move modal (dashboard/folder)
* Move to folder modal (there is another one)
* Cloudwatch logs select log groups modal 
* Azure resource picker modal 

Some where not using Modal.ButtonRow so did not have right-aligned buttons so fixed that as well. And some had the cancel button to right of the primary, fixed that as well so that it is always to the left of the primary.

### CODE REVIEW

**Review by aangelisc — APPROVED** [review]

**Review by idastambuk — APPROVED** [review]

**Review by gillesdemey — APPROVED** [review]
Alerting changes LGTM :shipit:

**Review by staton-hyse11 — APPROVED** [review]
Changes look good to me. Before this is considered complete there needs to be documentation accompanying these UI changes

**Comment by torkelo** [comment]
@staton-hyse11 where would that be? In the modal storybook docs?

**Comment by torkelo** [comment]
@staton-hyse11 added this to the modal storybook docs:
image

**Pull request merged**
