### PR TITLE
Replace ts-loader with Babel

### LINKED ISSUE #21586: Migrate ng-annotate to babel-plugin-angularjs-annotate
**Why is this needed**:
[ng-annotate](https://npmjs.com/ng-annotate) is deprecated.

### PR DESCRIPTION
**Pull request by stevenvachon**
This work was originally done in #21554, but it was reverted due to issues described in #21583.
Fixes #21586 

### Test plan: 
- [x] Validate production build
- [x] Validate dev build
- [x] Validate storybook
- [x] Validate against Grafana Enterprise 
- [x] Validate tests are passing
- [x] Validate e2e tests are passing
- [x] Validate plugins loading: test against multiple plugins

### CODE REVIEW

**Comment by dprokop** [comment]
@stevenvachon do you mind cherry picking 822ecdc and 6c636d9

**Comment by stevenvachon** [comment]
@dprokop I already did :)

**Comment by torkelo** [comment]
To help troubleshoot the phantomJS issue I installed chromium 40, building with Babel crashes on that old browser , hopefully same error phantomJS gets (can’t get any error output from phantomJS for this issue) 

But so far unsuccessful in figuring out how to fix Babel config so it passes, errors on const and let statements that are left in code outside strict code

**Comment by dprokop** [comment]
Ok, I have managed to see at least logs from PhantomJS. Using method described here https://phantomjs.org/troubleshooting.html (Remote debugging) I have run https://github.com/grafana/grafana/tree/master/tools/phantomjs binary against https://github.com/grafana/grafana/blob/master/tools/phantomjs/render.js which allowed me to see the console logs:

image

Changing `let` to `var` in the relevant code in vendors chunk fixed the errors in the console, but showed new ones about arrow functions. Basically arrow function syntax is not supported in Phantom, but we have that in the vendors bundle.

**Comment by dprokop** [comment]
@stevenvachon @torkelo I have made PhantomJS work with 3efeb4e71b4cb301de98a0592519633d80f39438 . I have added transpilation step for debug package as suggested in https://github.com/visionmedia/debug/issues/701#issuecomment-505487361.

@ryantxu I think this approach could also solve the arrow issue that you had with Phantom.

**Comment by dprokop** [comment]
Went through the test plan. Seems like all the things work.

Waiting for input from @daniellee about his tests agains his full of plugins instance :D If feel good there I think we are ready to merge this/

**Comment by alexanderzobnin** [comment]
@dprokop Tested it with Zabbix plugin and it seems, all works fine - I didn't notice any errors. Grafana frontend was built with `make build-js`.

**Comment by daniellee** [comment]
@dprokop @stevenvachon tested on a bunch of plugins and everything seems to work as it should. LGTM

**Comment by stevenvachon** [comment]
I'm confused by the commits that have been merged into this PRs branch and why they aren't showing up in the "files changed" tab. I opt for rebases instead. With that, I'm not comfortable merging this myself.

**Comment by torkelo** [comment]
It sure what you mean? Should there be more in files changed?

**Comment by stevenvachon** [comment]
There was a merge at 8742dc318fb5bdf97297b56c6943ed5941db97c0. I'd think that they should show here.

**Comment by torkelo** [comment]
That’s a merge sync with master, so those will not show up in diff as those changes are already in master

**Comment by dprokop** [comment]
> I'm confused by the commits that have been merged into this PRs branch and why they aren't showing up in the "files changed" tab. I opt for rebases instead. With that, I'm not comfortable merging this myself.

@stve

**Comment by dprokop** [comment]
I'm gonna merge this in the morning tomorrow, can't be online this evening so would like to be able to react if something unpredictable happens. Hope this is fine @stevenvachon

**Review by dprokop — APPROVED** [review]

**Pull request merged**
