### PR TITLE
Schema: use almost auto generated models.gen.ts for dashlist and text panels

### PR DESCRIPTION
**Pull request by ryantxu**
This uses a file generated by:
```
./bin/linux-amd64/grafana-cli cue gen-ts --grafana-root .
```
for the news panel.

It updates the text panel so it is almost the one generated by cuetsy

### CODE REVIEW

**Comment by sdboyer** [comment]
i'm still confused on what benefit we derive from merging these before the codegen actually gives us what we want. Seems to me like it just muddies the waters

**Comment by ryantxu** [comment]
> what benefit we derive from merging these before the codegen actually gives us what we want. 

I am trying to find the files that have the least changes required.  I guess minimal value, but at least the diff only parts to the parts that need fixed rather than the rest of the changes too (order etc)

**Comment by ryantxu** [comment]
@sdboyer -- do you see any value in merging this?  The only difference is that when cuetsy can generate this, it will be a 4 line diff not a bunch of reordering.

If not lets close

**Review by sdboyer — APPROVED** [review]
this is good enough, I think

**Pull request merged**
