### PR TITLE
Matyax/coverage test

### PR DESCRIPTION
**Pull request by matyax**
Test for https://github.com/grafana/grafana/pull/60341

Do not merge.

### CODE REVIEW

**Comment by matyax** [comment]
@aangelisc coverage doesn't seem to change with this PR, even with some deleted tests. Can you tell what I am missing?

**Comment by aangelisc** [comment]
@matyax you've just highlighted something I'd never noticed before! There's a bug in the code coverage script that only reports coverage in the route directory. I'll look into fixing this!

**Comment by matyax** [comment]
Cool! Let me know if I can help in any way.

**Comment by aangelisc** [comment]
Hey @matyax. I have a PR up [here](https://github.com/grafana/code-coverage/pull/23) which should fix this issue. Once it's merged we can confirm it works by updating the workflow here to reference the commit before we release.

**Comment by matyax** [comment]
Approved.

**Comment by aangelisc** [comment]
@matyax looks like that change has worked now 😊

**Comment by matyax** [comment]
It did! Great work!

**Pull request closed without merging**
