### PR TITLE
Resolve 14738 log Insight auth

### PR DESCRIPTION
**Pull request by tomdantuit**
@torkelo
resolves 14738 [issue 14738](https://github.com/grafana/grafana/issues/14738)

Add opaque_token_provider with test.

### CODE REVIEW

**Comment by tomd8451** [comment]
At the moment this was just to be used with Log Insight. I'm not aware of any other tools that use a self-issued opaque token for authentication. Given that these changes would be needed for the plugin to work, would it be preferably to actually build the plugin as an internal plugin?

**Comment by torkelo** [comment]
Not sure what you mean, internal plugin?

**Comment by tomd8451** [comment]
By internal, I was referring to the plugins that live in this repo and are exported in [ the built_in_plugins.ts file](https://github.com/grafana/grafana/blob/master/public/app/features/plugins/built_in_plugins.ts).

**Comment by tomd8451** [comment]
Would I be able to do something similar to this, making use of [Backend Plugins](https://github.com/grafana/grafana/issues/6841) so I wouldn't have to make make the code change in the core service?

**Pull request closed without merging**
