### PR TITLE
backend: use latest Go sdk

### PR DESCRIPTION
**Pull request by kylebrandt**
This adds the ExecutedQueryString property to FrameMeta, which is used to display post-interpolated queries in the Query Inspector in the front end.

This also includes the rename of Title to DisplayName on FieldConfig.

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]

**Review by marefr — CHANGES_REQUESTED** [review]
You'll have to update cloudwatch code that will fail in CI. Been there done that :)

**Comment by kylebrandt** [comment]
> You'll have to update cloudwatch code that will fail in CI. Been there done that :)

Not sure what you mean ... but will wait for CI, and then perhaps I will.

**Comment by kylebrandt** [comment]
And I see, didn't see that commit in the sdk :-)

**Comment by kylebrandt** [comment]
@marefr Has been updated, CI passes now.

**Review by ryantxu — APPROVED** [review]

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
