### PR TITLE
Jaeger: Make tags templateable

### PR DESCRIPTION
**Pull request by srclosson**
**What this PR does / why we need it**: This implements templatable tags in the Jaeger datasource

**Which issue(s) this PR fixes**: #41273

Simple enhancement allowing only tags to be templatable

### CODE REVIEW

**Review by connorlindsey — APPROVED** [review]
Works great!

**Review by aocenas — APPROVED** [review]

**Comment by ifrost** [comment]
@connorlindsey @aocenas - do we need to backport it to 8.3?

**Comment by connorlindsey** [comment]
Seems like a small enough change we should get it in

**Comment by ifrost** [comment]
@connorlindsey - opened a backport PR. Feel free to merge it https://github.com/grafana/grafana/pull/42206

**Pull request merged**
