### PR TITLE
TestData: stream via fetch

### PR DESCRIPTION
**Pull request by ryantxu**
This replaces #16059 

image

The StreamHandler should be refactored to make this a little less messy

### CODE REVIEW

**Comment by torkelo** [comment]
Nice! Think we can have it here to test & experiment with for now, but long term if feels a bit strange to have this potentially useful thing hidden in the test data source.

**Comment by ryantxu** [comment]
I'm working on an external plugin that uses this same method.  For a core plugin I am not sure what parameters make sense -- Is it just a URL with template variables?   The fact it needs `fetch` but we don't yet really support all the expected features for fetch (proxy, auth, etc) make me think we should hold off on a core implementation.

**Comment by torkelo** [comment]
Ok, understand. I guess we need an issue for how to migrate from angular $http to fetch :)

Feel free to merge this when it's not WIP

**Comment by ryantxu** [comment]
@seanlaff -- This is pretty close to your solution except it does CSV rather than JSON

Right now it will only works with react panels... but soon #16659 it will work everywhere

**Comment by seanlaff** [comment]
@ryantxu Awesome! Have you given any thought to how to handle stream interruptions? It's something I've started to run into with my original implementation since I stream data from API replicas that can get preempted. Ideally there'd be some logic to restart the stream if the network has an outage, but Im unsure if that's too datasource-specific to exist in core.

**Comment by ryantxu** [comment]
interruptions should be much easier to handle with the new API.  The observer is a callback, not a subject, so the Datasource can just keep calling it whenever it gets new data.

The stream restart logic can be handled entirely in the DataSource

I'm not sure the best way to include this in grafana core.  In particular since this uses `fetch`, it does not go through all the standard checks (security/proxy/etc) that standard datasources do.

**Comment by seanlaff** [comment]
Cool, that sounds good to me :)

**Comment by vetorialnet** [comment]
Hi. I cant get it working for me... How the API expects the CSV format? There is a server side example?

**Comment by thiagodamas** [comment]
Hi. Cant get it working for me... How the API expects the CSV output? Where can I get a server side example?

**Pull request merged**
