### PR TITLE
AppPlugins: Support app plugins with only default nav

### PR DESCRIPTION
**Pull request by torkelo**
Just a test implementation to try to solve the problem of having app plugins that only have default nav and does not want the child item to show up in the nav.

### CODE REVIEW

**Review by leventebalogh — COMMENTED** [review]
**Update:** misunderstood, [here is the final comment](https://github.com/grafana/grafana/pull/43016#pullrequestreview-829887778).

~Although I don't think this is a bad approach, it might causes issues with other already existing plugins. Not crucial issues, but small changes in how they worked before.~

~**Example:**~
~The `grafana-metrics-enterprise-app` plugin as an example has it's [default nav URL](https://github.com/grafana/gex-plugins/blob/master/plugins/grafana-metrics-enterprise-app/src/plugin.json#L28) set to the first (and default) "Tenants" tab here:~
Screenshot 2021-12-13 at 9 11 18

[Deployed plugin example](https://admin-dev-us-central-0.grafana.net/ge-metrics-grafana/a/grafana-metrics-enterprise-app?path=instances)
[Plugin JSON](https://github.com/grafana/gex-plugins/blob/master/plugins/grafana-metrics-enterprise-app/src/plugin.json)

~With this change there's gonna be no "clear" link pointing to the "Tenants" tab from the side menu, which can cause some confusion to users I think. (Although they can still reach it if they click on the logo or on the plugin name, it's just less clear I think).~

**Comment by torkelo** [comment]
@leventebalogh  no that should work exactly like before, the new logic is only when there is one child and that child is default

**Review by leventebalogh — APPROVED** [review]
Ahh, true, I somehow mis-read that condition 🤦 

I think it's all good then.

(Although probably we would like to add some docs on how this can be used for only showing the plugin icon. I will bring it up in the plugin-platform team.)

**Review by dprokop — APPROVED** [review]
👍

**Pull request merged**
