### PR TITLE
Navigation: use navId and pageNav on Alerting - Contact Points page

### LINKED ISSUE #54278: Page layout: Alerting: individual contact point
- [x] convert to use `navId` instead of `navModel`
- [x] add `subTitle`
- [x] add `pageNav` (see `TeamPages`)

note: this shouldn't need to be done behind the feature toggle as it's improving consistency across the board

### PR DESCRIPTION
**Pull request by eledobleefe**
**What this PR does / why we need it**:
Use `navId` instead of `navModel` and add a `subTitle` add `pageNav`.

**Which issue(s) this PR fixes**:
Fixes [#54278](https://github.com/grafana/grafana/issues/54278)

**Special notes for your reviewer**:

Contact Points  
-|
Nav_alerting_contactPoints

Edit Contact Point | New Contact Point
-|-
Nav_alerting_editContactPoint|Nav_alerting_newContactPoint|

### CODE REVIEW

**Review by ashharrison90 — APPROVED** [review]
looks great to me - think we should wait for a review from someone from alerting first though 🙂

**Comment by eledobleefe** [comment]
> looks great to me - think we should wait for a review from someone from alerting first though 🙂

Hi @grafana/alerting-squad-frontend! Could anyone take a look at this, please? 🙏 🙂

**Comment by konrad147** [comment]
Are you planning to do the same for the rest of alerting pages?

**Comment by ashharrison90** [comment]
@konrad147 i believe the other alerting pages were already done by https://github.com/grafana/grafana/pull/51510

if there's any that haven't been converted to use `navId` then yes we'll do those 🙂

**Review by konrad147 — APPROVED** [review]
LGTM!

**Pull request merged**
