### PR TITLE
Transformations: Extract JSON Paths

### PR DESCRIPTION
**Pull request by NiklasCi**
**What is this feature?**

This feature extends the `extractFields` transformer to extract multiple paths from a json source.
It also provides a switch to keep the time field, if the `Replace all Fields` switch is toggled.

Let's asume we have the following source with a value as json object.

*Source*:
```json
{
    "testdata": {
        "source1": {
            "value1": "Hallo World",
            "value2": [
                1,
                2,
                3,
                4
            ],
            "value3": {
                "array": [
                    "1",
                    "2",
                    "3",
                    "4"
                ],
                "number": 100
            }
        },
        "source2": [
            {
                "string": "Hallo",
                "array": [
                    1,
                    2,
                    3,
                    4
                ]
            },
            {
                "string": "World",
                "array": [
                    5,
                    6,
                    7,
                    8
                ]
            }
        ]
    }
}
```
Following example values can be extracted with the extended transformator:
Bildschirmfoto vom 2023-01-12 13-11-10

**Why do we need this feature?**

Our company needs a way to extract json objects coming mostly from a mqtt datasource. We have big nested json objects which are hard to extract via the already provided transformators. This transformator helps us to get the values we want without using 10-15 extract fields transformators.

**Who is this feature for?**

For everyone that wants to extract specific nested values from a json object.

### CODE REVIEW

**Comment by ryantxu** [comment]
I wonder if this makes more sense as an option on the existing extract fields transformer 🤔 

https://github.com/grafana/grafana/tree/main/public/app/features/transformers/extractFields

**Comment by NiklasCi** [comment]
> I wonder if this makes more sense as an option on the existing extract fields transformer thinking
> 
> https://github.com/grafana/grafana/tree/main/public/app/features/transformers/extractFields

Also thought about that. But it only replies to the JSON extractor.

**Comment by NiklasCi** [comment]
> I wonder if this makes more sense as an option on the existing extract fields transformer

Waiting for a decision to keep it as new transformer or add it to the extractField Transformer ?

**Comment by zoltanbedi** [comment]
fyi @grafana/observability-metrics

**Comment by NiklasCi** [comment]
> fyi @grafana/observability-metrics

Sorry i have no clue what this means and didn't find any answer in the internet. Can you explain me please?

**Comment by gtk-grafana** [comment]
Hey @NiklasCi, sorry about that, Zoltan is just alerting our team (observability-metrics) to take a look at this PR. On first glance this looks good, I'll try to find some time and get this tested and fully reviewed.

**Comment by gtk-grafana** [comment]
@NiklasCi After taking a closer look at this, I'd agree with @zoltanbedi, that these new options should be shown in the "Extract fields" transformation when the format is JSON, that keeps the number of transformations down, and provides a somewhat intuitive home for this functionality. 

Thank you so much for taking the time to implement this, I'm still new to MQTT, but after playing around with it a bit, I'm seeing that this type of functionality is necessary to visualize many MQTT broker responses. 

CC @toddtreece @itsmylife

**Comment by NiklasCi** [comment]
> @NiklasCi After taking a closer look at this, I'd agree with @ryantxu, that these new options should be shown in the "Extract fields" transformation when the format is JSON, that keeps the number of transformations down, and provides a somewhat intuitive home for this functionality.
> 
> Thank you so much for taking the time to implement this, I'm still new to MQTT, but after playing around with it a bit, I'm seeing that this type of functionality is necessary to visualize many MQTT broker responses.
> 
> CC @toddtreece @itsmylife

Thanks for the feedback. I will extend the extractFields with this new functionality the next days.
Do you think we need the multiple source selector? In my opinion could be a good addition.

**Comment by gtk-grafana** [comment]
Yeah I could see being able to select multiple sources as a nice feature, but maybe we want to release this functionality for a single field first, and follow up with an additional PR? I'll leave that up to you as the author of this change

**Comment by gtk-grafana** [comment]
Yeah the functionality is behaving as I'd expect: with this simple sample dataset:
`[ "2023-01-11T19:39:16.639Z", 143, 202, 59, 81, 59, -81, 81 ]`

image
This gives me fine grain control over what values I want to consume and the ability to organize them nicely with the alias field. Obviously this also has advantages when working with more complex examples, but if for example this MQTT data was from a collection of iot devices grouped by network (and not necessarily metrics of the same type), this transformation allows me to construct dashboards to fit my use case without having to change my existing data structure.

The code looks good, I'd rather we don't use <br /> tags, and to use <strong> instead of <b>, but if you were able to spend more time on this I'd rather you focus on creating a gdev dashboard (I believe these live in the `/grafana/grafana/devenv/dev-dashboards/transforms` directory), so we can potentially link to that dashboard in the change log notes when this is released (citing you as the author). I can always create one if needed, but I believe it to be more valuable for you to construct the example dashboard, as your use-case is more authentic then what I can mock up (aka you are doing this to solve a real problem that you have).

**Comment by gtk-grafana** [comment]
Also `extractFields.test.ts` is failing in drone due to some type errors

**Comment by bohandley** [comment]
I really like this! This is a really helpful transformation for json, but unfortunately, adding multiple sources is breaking previous extract fields transformations. I created some extract fields transformations before checking out the branch and they were blown away. Unless you can figure out a way to migrate previously saved extract fields transformations to the new interface, I would suggest not implementing multiple sources.

Otherwise, this is really cool!

**Comment by NiklasCi** [comment]
Ok i will remove the mulitple sources and fix stuff you mentioned. We don't need the mutliple sources for now. I wonder if there is a other way to transform multiple sources. Would be a good feature request.

**Comment by NiklasCi** [comment]
@bohandley I removed the multiple sources. Can you check if previous extract field transformation still work?
@gtk-grafana I added a dashboard. I don't know if this is the correct way. It uses the MQTT Datasource plugin. To provide data you need a MQTT Broker and a MQTT Publisher that publish the json object reported in the PR description to the Topic `test/json`. If this use case is to specific, feel free to create a dashboard. I can't see a way to create a dashboard with TestDataDB scenario thats expect complex json.

**Comment by gtk-grafana** [comment]
@NiklasCi I went ahead and extended your example to use the gdev-testdata via the Raw Frames option, this allows us to input arbitrary data frames into the sample dashboards. Feel free to make any updates or add additional panels if you feel like there's more use-cases you want to demonstrate for this functionality.

**Comment by gtk-grafana** [comment]
@leeoniya @ryantxu Looks like y'all were the original authors of this transformation, we're trying to rule out any regression for the JSON parse option of this transformation, the code looks like it shouldn't, but we don't really know what the dataframes are supposed to look like that use this field? Is there some specific usage in Loki that is more common that we can check to make sure that extending this option won't break anyone's existing dashboards?

**Comment by gtk-grafana** [comment]
@NiklasCi Everything is looking good so far, but @bohandley and I want to do some additional testing on this since this could potentially impact existing dashboards. I'd expect we can wrap that up testing next week. Thanks again for all your hard work and patience on this.

**Comment by NiklasCi** [comment]
> @NiklasCi I went ahead and extended your example to use the gdev-testdata via the Raw Frames option, this allows us to input arbitrary data frames into the sample dashboards. Feel free to make any updates or add additional panels if you feel like there's more use-cases you want to demonstrate for this functionality.

Thanks for that. If i find time i will test this dashboard.

> @NiklasCi Everything is looking good so far, but @bohandley and I want to do some additional testing on this since this could potentially impact existing dashboards. I'd expect we can wrap that up testing next week. Thanks again for all your hard work and patience on this.

Let me know if something break and maybe provide the dashboard, so i might can fix stuff.

**Review by gtk-grafana — APPROVED** [review]
Looks good! Thanks again for all of the hard work on this PR!

**Comment by NiklasCi** [comment]
> @NiklasCi Can you merge in the latest main and see if that fixes the backend unit test that's failing?

I have no clue what this means 
```
Token is empty, can't dispatch event. This is expected for PRs coming from forks, please check that the changes are compatible with Enterprise before merging this PR.
/home/runner/work/grafana/grafana/actions/node_modules/@actions/core/lib/core.js:106
        throw new Error(`Input required and not supplied: ${name}`);
```

 My changes are on a fork, maybe thats why the backport workflow fails?

**Pull request merged**
