### PR TITLE
CloudWatch: Add missing Redshift metrics to CloudWatch data source

### LINKED ISSUE #32120: Missing Redshift metrics for CloudWatch data source
**What would you like to be added**:
Missing Redshift metrics listed in AWS docs https://docs.aws.amazon.com/redshift/latest/mgmt/metrics-listing.html

**Why is this needed**:
For monitoring Redshift metrics (especially WLM queues), these new metrics are necessary

Will create a PR to follow this issue

### PR DESCRIPTION
**Pull request by tomdaly**
**What this PR does / why we need it**:

Adds missing Redshift metrics in CloudWatch, to match [AWS docs](https://docs.aws.amazon.com/redshift/latest/mgmt/metrics-listing.html)

**Which issue(s) this PR fixes**:

Fixes #32120

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
LGTM, thanks for your contribution @tomdaly!

**Review by sunker — APPROVED** [review]
LGTM

**Comment by tomdaly** [comment]
Thanks for the approvals @dsotirakis @sunker, is there any estimate on when this will be included in a release? It's blocking some work for my org

**Comment by sunker** [comment]
Yes 8.0 beta is due mid May I think. Stable release will be mid June.

**Pull request merged**
