### PR TITLE
Phlare: Update client code to use v0.1.2 API.

### PR DESCRIPTION
**Pull request by cyriltovena**
**What is this feature?**

Before we were copying the code from Phlare but now we want to depend on the library so that we can receive update seamlessly.

**Why do we need this feature?**

To maintain the API up to date.

**Who is this feature for?**

Phlare and Grafana Team.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aocenas** [comment]
@cyriltovena I am getting `unimplemented: 404 Not Found` for all the requests. I am testing with latest docker image.

**Comment by joey-grafana** [comment]
> @cyriltovena I am getting `unimplemented: 404 Not Found` for all the requests. I am testing with latest docker image.

Same as myself.

**Comment by cyriltovena** [comment]
Yes this is a breaking change. We need to update the server to https://github.com/grafana/phlare/pull/466

I decide to go through anyway since we're still in beta.

**Comment by cyriltovena** [comment]
Let's wait first until we merge the other PR at least.

**Comment by cyriltovena** [comment]
Should be fixed now.

**Review by joey-grafana — APPROVED** [review]
Works for me 👍

**Pull request merged**
