### PR TITLE
Units: add velocity rotation per minutes

### PR DESCRIPTION
**Pull request by TimoM95**
**What this PR does / why we need it**:
Velocity Unit Rotation per minutes
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dprokop** [comment]
@TimoM95 thanks for contribution!

We will gladly merge this but before that, it would be good with a unit test for each new unit.

Also, can you pleas elaborate more about this unit? Feels like it is quite specific, I don't necessarily understand it. Does it represent how much time one rotation takes?

**Review by dprokop — CHANGES_REQUESTED** [review]
@TimoM95 thanks for contribution!

We will gladly merge this but before that, it would be good with a unit test for each new unit.

Also, can you pleas elaborate more about this unit? Feels like it is quite specific, I don't necessarily understand it. Does it represent how much time one rotation takes?

**Comment by TimoM95** [comment]
it represent how often it rotate in one minute

**Comment by torkelo** [comment]
We have just merged support for custom units, so this is no longer needed.
#20763

**Pull request closed without merging**
