### PR TITLE
Traces: More visible span colors

### LINKED ISSUE #54512: Change trace span colors to stop using hex (of the name) for the color values
From internal conversation: 

"We've updated Grafana to 9.1.1 on the SE demo kit, but several SEs have pointed out (and I've also found) that the colour scheme that's been chosen for the set of traces we use are so dark as to be near invisible. It is currently early morning here, there's sunlight in the room I'm working in and honestly, that blue is so dark it's actually black. I literally cannot see the spans for mythical-server , only mythical-requester. Obviously, I'm using dark mode, instead of light, but I shouldn't have to change that to see what my spans look like. Is there something we can do about the palette selection used for these? Thaaaank yooooou! (There's also the issue of contrast, bright white next to a very dark colour also doesn't help colour acuity,)"

"So from what I see the options are:

- Add an issue (to be completed soon) to change the colors to what they used to be about 2 months ago

- Add a different issue to the backlog to further extend the colors to ensure we don't use colors that are either too bright or too dark

- Do nothing and keep the colors the way they are (not great as the color based on the hex of the name varies and can often be to bright or dark depending on the light/dark theme being used)"

Also allowing the user to override color mapping for specific services would be great.

### PR DESCRIPTION
**Pull request by joey-grafana**
**What this PR does / why we need it**:

A couple on months ago we introduced a changed to make span colors consistent across trace views depending on the service name of the span. This introduced some issues depending on light/dark mode being selected where span colors could be either too bright or too dark to be seen properly in the trace view. This change add to that by only allowing colors with a contrast ratio of 3 or above.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/54512

**Special notes for your reviewer**:

Screenshot 2022-09-06 at 13 58 35
Screenshot 2022-09-06 at 13 59 50

### CODE REVIEW

**Review by adrapereira — APPROVED** [review]
LGTM! 👍

**Comment by aocenas** [comment]
@joey-grafana isn't the problem just the set of colors? couldn't we just remove some less contrasting colors from the pallete (just for the traces)?

**Comment by joey-grafana** [comment]
> @joey-grafana isn't the problem just the set of colors? couldn't we just remove some less contrasting colors from the palette (just for the traces)?

It is the set of colors, although the previous set (starting from pos 0 in the colors.ts array was a lot more stable in terms of contrast). I discussed this with @hedss and removing the less contrasting colors is the next step, whereas getting to a more stable set of colors is needed now.

**Comment by aocenas** [comment]
@joey-grafana yes but isn't this PR making the colors less stable? What I imagine the current state (before this PR) is that if you open two traces next to each other, the same services will have the same colors which I assume is desired (I like that personally). This PR reverts that which could be considered a regression sort of. So I wonder if instead, we don't just disallow some colors as a smaller, easier change without the "regression" in behavior.

**Comment by joey-grafana** [comment]
> @joey-grafana yes but isn't this PR making the colors less stable? What I imagine the current state (before this PR) is that if you open two traces next to each other, the same services will have the same colors which I assume is desired (I like that personally). This PR reverts that which could be considered a regression sort of. So I wonder if instead, we don't just disallow some colors as a smaller, easier change without the "regression" in behavior.

Thanks for the feedback. I've updated the screenshots above to reflect colors that have a contrast ration >= 3

**Comment by mdvictor** [comment]
Hey @joey-grafana! Can this be merged today for the release of v9.1.5?

**Pull request merged**
