### PR TITLE
Elasticsearch: rename public/app/plugins/source/elasticsearch/query_def.ts to follow convention

### LINKED ISSUE #55380: Elasticsearch: Rename public/app/plugins/datasource/elasticsearch/query_def.ts to follow convention
**Level: easy**

Some files that are maintained by logs squad have snake_case name. According to convention https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions we should use:
- `camelCase` when the primary export is a function
- `PascalCase` when the primary export is a class or React component. 

Rename following files  in `grafana/grafana` to follow the above-mentioned convention:
- `public/app/plugins/datasource/elasticsearch/query_def.ts`

### PR DESCRIPTION
**Pull request by gitstart**
**What this PR does / why we need it**:
Renames public/app/plugins/source/elasticsearch/query_def.ts to follow convention

**Which issue(s) this PR fixes**:

Fixes #55380 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @ivanahuckova! Please review the PR 🙏

**Review by svennergr — APPROVED** [review]
LGTM.

Thanks for your collaboration. By the way, I don't think there is the need to ping certain people directly. Our squad will handle the review in a timely manner. Thanks for your understanding.

**Review by svennergr — CHANGES_REQUESTED** [review]
Thanks for your attribution.
Described in https://github.com/grafana/grafana/issues/55380 it would be best to move the `query_def.test.ts` out of the `specs` directory.

**Review by svennergr — APPROVED** [review]

**Comment by svennergr** [comment]
@gitstart Could you merge main into this?

**Comment by gitstart** [comment]
> @gitstart Could you merge main into this?

sure

**Comment by gitstart** [comment]
> @gitstart Could you merge main into this?

@svennergr it's done. Thank you for the review

**Pull request merged**
