### PR TITLE
Plugins Catalog: add support for enable/disable app plugins

### PR DESCRIPTION
**Pull request by leventebalogh**
**Related issue(s):** https://github.com/grafana/grafana/issues/40050, https://github.com/grafana/grafana/issues/41772 

### What changed?
- [x] added a Enable / Disable button in the plugin details header for app plugins 
- [x] updated the tests

**After the change:**

https://user-images.githubusercontent.com/9974811/142196271-6de7bd82-c5b1-4905-8731-3296ac58bd0e.mp4

### CODE REVIEW

**Review by jackw — APPROVED** [review]
LGTM! 🚢 🇮🇹 

I think we're gonna need some UX input on that header as it's becoming a bit cluttered now.

**Comment by mckn** [comment]
Yeah, I agree with @jackw! But this works really great.

Some scenarios where the UI might be less optimal. First one where the button is displayed after the error message and the other one where we have two primary actions (we should always only have one per context).

Skärmavbild 2021-11-18 kl  10 59 28
Skärmavbild 2021-11-18 kl  10 59 16

**Comment by leventebalogh** [comment]
Thanks! 🙏 

Yea, I absolutely agree with your notes @jackw and @mckn. 
I think I will create an issue on our board as a "reminder" for revisiting the UI and UX of the header.

**Comment by leventebalogh** [comment]
A question towards the @grafana/cloud-platform team: what do you think, would merging this cause any trouble for you?

Although some app plugins available out there already have their own Enable / Disable functionality implemented on their config page (e.g. Synthetic Monitoring), but we still wanted to ask if having a button for enabling / disabling app plugins in the plugin details header would cause any issues for you, or is it safe to merge from the cloud's perspective?

**After merging this PR it would be possible to _Disable_ the following app plugins:**
- [Grafana OnCall](https://grafana.com/blog/2021/11/09/announcing-grafana-oncall/)
- Grafana Cloud Alerting
- Onboarding

@josiahg @ryantxu for visibility.

**Example for a currently available disable option:**
Screenshot 2021-11-18 at 12 50 56

**Comment by josiahg** [comment]
Agree this will need a UX/UI revisit sometime soon.

In the short term I'd make sure our support and field teams know users can now disable the App Plugins, in case they get a support case for "why doesn't my OnCall work"

We may want to add a mechanism at some point for designating "cannot be disabled" apps, but for now I don't think that's needed.

**Comment by josiahg** [comment]
Can we add some docs for this feature as well? That way support can easily point users with questions to a doc page on how to enable/disable.

**Comment by leventebalogh** [comment]
Sure, I will add some documentation for that @josiahg 👍

**Pull request merged**
