### PR TITLE
Table Component: Improve text-wrapping behavior of cells

### LINKED ISSUE #25623: Table: Support text wrapping
I have a table which presents a long text from database.
The new table plugin does not wrap the text and so I can't use it with the new table.

It would be great if you could preserve the text wrap behavior that the old Table plugin had, or at least, ,allow customization.

### PR DESCRIPTION
**Pull request by ahuarte47**
**What is this feature?**

This PR fixes the visualization of strings in tables that do not fit the space of its cell. Full content is showed when user moves the cursor over the cell.

**Why do we need this feature?**

Long texts in cells are clipped if they do not fit the space if its cell. User can not view the full content of the string.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

It partially improves the issue #25623

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by ahuarte47** [comment]
I attach here a video before the fix, and the final result applying the change.
[before-fix.webm](https://github.com/grafana/grafana/assets/5576272/3d251a82-6068-4175-9a8c-22c85ee17f63)
[after-fix.webm](https://github.com/grafana/grafana/assets/5576272/b9146d77-83f1-4067-b1f2-307071bd8be5)

**Comment by CptHolzschnauz** [comment]
Cool. Do you know where to find this file on a installed Grafana under Linux (Ubuntu). I would like to change it right there with nano. Feasible?

**Comment by ahuarte47** [comment]
> Cool. Do you know where to find this file on a installed Grafana under Linux (Ubuntu). I would like to change it right there with nano. Feasible?

In my understanding, the file that needs to be changed is a TypeScript file that needs to be built or compiled. It is not directly used by grafana like a CSS file.

**Comment by codeincarnate** [comment]
@ahuarte47 thanks for another contribution! I'm going to test this out quickly but generally speaking this seems like a much better way to handle this scenario!

**Review by codeincarnate — CHANGES_REQUESTED** [review]
Just ran through this and at least for the moment I'm unable to get this to work 😢. Did a commit get missed perhaps?

**Comment by ahuarte47** [comment]
Sad of reading that, can I test a dashboard sample? maybe one from dev-dashboard package? 
Anyway, I am attaching here the dashboard that I am showing in the videos.

[My test for text-wrapping.json](https://github.com/grafana/grafana/files/14313659/My.test.for.text-wrapping.json)

**Comment by codeincarnate** [comment]
Re-tested this and appears to be working fine, not sure exactly what I was doing 😕.  It does get cut-off if the table is small enough, but we effectively already have that problem. We can address that as a follow-up PR. Thanks for the contribution!

**Review by codeincarnate — APPROVED** [review]

**Comment by torkelo** [comment]
@ahuarte47 @codeincarnate I would not close and say this fixes https://github.com/grafana/grafana/issues/25623 , that would make a lot of people who voted for that issue upset . They are looking for text wrapping cells (not the hover effect)

**Review by torkelo — COMMENTED** [review]
Tested this PR and looks broken in Chrome Version 121.0.6167.184 (Official Build) (arm64) (OSX)

Screenshot 2024-02-22 at 08 11 53

**Comment by ahuarte47** [comment]
> Tested this PR and looks broken in Chrome Version 121.0.6167.184 (Official Build) (arm64) (OSX)
> 
> Screenshot 2024-02-22 at 08 11 53

I am viewing everything ok as well in `Version 122.0.6261.57 (Official Build) (64-bit) (Ubuntu)`, even with transparent background of panel enabled.

image

Maybe I should to force a background color in hover?

**Comment by ahuarte47** [comment]
Setting wordbreak it works better:
image

**Comment by ahuarte47** [comment]
Please @codeincarnate @torkelo may I ask for your help to review again, tahnks in advance!

**Comment by codeincarnate** [comment]
@ahuarte47 I'll be able to take a look this evening :smiley:

**Comment by codeincarnate** [comment]
Gave it another run-through and it appears to be working fine in each case now. Missed the issue fix label before and very much agree this doesn't close that. Thanks there @torkelo :pray:

**Comment by ahuarte47** [comment]
Thanks a lot @codeincarnate !!!!

**Comment by torkelo** [comment]
@ahuarte47 @codeincarnate this seems to have made it a bit worse for some scenarios, it always wraps and breaks up strings (even when there is no white space)

So large values or single strings that would just extend a bit to the right are now broken up 
Screenshot 2024-02-23 at 13 23 19

Text strings that where somewhat readable in narrow columns now become very hard to read. It seems the hover view is always using the same width as the cell, the whole point of the hover effect was to give the cell more room to show the value and not be constrained by the column width. 
Screenshot 2024-02-23 at 13 25 17

**Comment by ahuarte47** [comment]
I can create other PR with a new option in the ui table settings to enable this. Disabled by default. Do you agree?

**Comment by torkelo** [comment]
@ahuarte47 no I do want a UI option for this, can we make it so that it does not wrap until at the edge of the table? 

The old behavior was so much nicer, except part of it that goes beyond the right side of the table is not visible 
Screenshot 2024-02-23 at 15 09 47

**Comment by ahuarte47** [comment]
> Haven't quite finished it but testing out logic based around string length and seeing how it goes, not much at all right now as I'm mostly playing with it but progress will be in the just linked PR 😸

I like very much this simple but effective solution using the length of the text, thank you very much!

**Comment by codeincarnate** [comment]
Thanks @ahuarte47 :pray: 

A quick update, still working through the specifics but expecting to have PR out of draft today.

**Comment by codeincarnate** [comment]
Made some updates to the mentioned PR, haven't quite gotten it working completely but I'm close and should be able to finish this one later 😄

**Comment by jacksongoode** [comment]
Is there a plan to allow a user to view headers that are too long in the table plugin? It seems weird that this would only be a feature for cells?

**Pull request merged**
