### PR TITLE
Loki: Improve operation ordering when adding new operations

### PR DESCRIPTION
**Pull request by torkelo**
* Makes it so Unrwap is added in the right place
* When adding a range vector function when one already exists it will be replaced

### CODE REVIEW

**Comment by aocenas** [comment]
The code looks good but in general feel like this approach can be a bit confusing. As a user, I would expect if I add something to the list that it's at the end. Having it moved to someplace else or even replacing something I already added seems confusing even though I see that it makes creating correct queries easier.

Personally, I like more approach where the app says what I did was wrong for this and that reason and allows me one-click automatic fix, that way I know why it was wrong and learn something, feel in control, and still have an easy way to fix it.

Maybe a bit late to change it now but wanted to mention this.

**Review by aocenas — APPROVED** [review]

**Comment by torkelo** [comment]
@aocenas not sure I agree

1) There is only 1 valid location for a range vector function, and you can only have one. This is not something new users will know, and allowing them to create an invalid query that they constantly have to move operations into the right place is not great. Especially when you have a lot of operations already and have no idea where it should be. 
2) There is only 1 valid location for line filters, they should be grouped together as early as possible. So a new line filter should be added after the last current line filter
3) a formatter like `json`  or `logfmt` only has a single valid location. They should be after any line filters and before any label filter expressions. 
4) Unwrap should be as late as possible, after any line or label filters expressions 

Having two teach all these rules to new users who have to manually get the ordering right seems like a bad new user experiance. But I agree only doing automatically is maybe also confusing as the user is not know what is happening or why. I think we do 2 things to improve this
1) Highlight the added / replaced operation somehow (flash it, or show it with some different border for 3 seconds after adding)
2) show an info text somewhere that explains the ordering rule.

thoughts @ivanahuckova @diegoadams ?

**Comment by ivanahuckova** [comment]
>a formatter like json or logfmt only has a single valid location.

This is true in a simple loki query, but when we introduce `line_format` for example, you can have formatter later in the query (e.g. `{container_name="docker-compose_app_1"} | logfmt | line_format "line={{.status}}" | logfmt`. But it is not an issue now. 

I like the options to highlight and add info text, but I am also wondering, if we would allow re-ordening if the user decides to do that.

**Comment by diegoadams** [comment]
> I like the options to highlight and add info text, but I am also wondering, if we would allow re-ordening if the user decides to do that.


@ivanahuckova , I may not understand the full context, but I assume letting the user reorder incorrectly always ends in an invalid query? If yes, then we shouldn't allow them to reorder. 

After the user adds an invalid location, I imagine that we autocorrect this with the "info text" and added/replaced "operation" highlighting together, then disappearing together after a few seconds.

**Pull request merged**
