### PR TITLE
update Dockerfile to make it works

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <chuyang@redhat.com>

**What this PR does / why we need it**:

fix the Dockerfile issue to make it works

**Which issue(s) this PR fixes**:

Fixes:
https://github.com/grafana/grafana/issues/39348
https://github.com/grafana/grafana/issues/40618
https://github.com/grafana/grafana/issues/40537
https://github.com/grafana/grafana/issues/40618

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by clyang82** [comment]
If you met this problem `make: /bin/sh: Operation not permitted`, then you need to upgrade the docker. that is `runc` issue, refer to https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Review by malcolmholmes — COMMENTED** [review]
Thanks for this. You're solving something we were just starting to look at!

**Review by kaydelaney — CHANGES_REQUESTED** [review]
Looks good! Just left a comment regarding one change

**Comment by clyang82** [comment]
The changes are in a separated branch `fix_docker_build`. You can checkout that branch to have a try.

**Review by kaydelaney — APPROVED** [review]

**Pull request merged**
