### PR TITLE
Templating: Fix updating of definition to empty string

### PR DESCRIPTION
**Pull request by ivanahuckova**
Fixes https://github.com/grafana/support-escalations/issues/6236

Context:

In Loki in https://github.com/grafana/grafana/pull/54102 we have changed Loki variables editor and also query model. Previously, it was string. Now it is object with properties. However, now when users change something in Loki variable query, the old `definition` is being displayed. This is a bug, because we want to overwrite `definition` to empty string, but this wasn't happening.

This PR fixes it by allowing definition to be updated to empty string.

Here is the demo/debug video:

https://github.com/grafana/grafana/assets/30407135/1394f238-43b3-4881-a167-829022fa1aed

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

**Comment by bohandley** [comment]
Hello! @ivanahuckova and @dprokop This change broke the description for prometheus variables and I'm not sure why. Prometheus is formatting the string in the new object in the `query` field of the object so that the definition is being set like this. 

https://github.com/grafana/grafana/blob/d29124214a27bdd5d46c07b18e1d40866d1ff25f/public/app/features/variables/query/QueryVariableEditor.tsx#LL95C1-L105C5

You can see this in ops that the descriptions are no longer showing up for Prometheus variables. 
https://ops.grafana-ops.net/d/4aa6447917c0599aba81ccfd2bbb4aa4/prometheus-overview?orgId=1&refresh=5s&editview=templating

I'm still confused though. This is only a one line code change, and I tried to remove it, and the effect stayed. The only way I was able to fix this was by checking out the previous commit 9b12d83b66d089000b9dc60be0f23d5f51d88716 and it works here.

**Comment by ivanahuckova** [comment]
@bohandley in https://github.com/grafana/grafana/pull/69786 we switch from showing definition to description, as definition is something that not many data sources produce anymore.

**Comment by bohandley** [comment]
This was a bit of a surprise. As I was working on adding the metric select to the variable editor, once I got it working, I saw the descriptions were no longer updating. I spent the whole day debugging it 🤣 We will have to update Prometheus then. I'll make an issue to do that. Thank you!

**Comment by ivanahuckova** [comment]
What do you mean by "We will have to update Prometheus then."? The description is set by user in the same way as query name. So if there is no description, that the description should be empty.
image

**Comment by bohandley** [comment]
I misunderstood, you are correct, the description is set by the user. I thought the description was another field set automatically like definition. 

This was my understanding that when a user creates a variable, they don't have to write an extra step, updating the description. The definition was there to offload cognitive effort and provide some default information about the variable. This seems like not a good user experience to see the definition disappear and the description is not a clear indicator for seeing the variable has been updated. I think we are going to see some issues come from this. We can chat about this Monday though, thank you for responding! 🙏🏻

**Comment by ivanahuckova** [comment]
I agree that the experience might be slightly worse for prometheus, but it will be better for all other data sources that were migrated to the new templating. The issue is that none of migrated data sources (besides Prometheus) have `query` or `query.query` string which means that definition is for them always empty and there is no additional information provided in the table. You can test it out with Loki, Cloudwatch, CloudMonitoring or Azure Monitor. This way, we at least show possible description, if users fill it out. 

Also the Prometheus variable query is now outdated and to the new users, `label_values(job)` won't say much, as you are now choosing from drop downs and not writing the query. 

But feel free to create a new issue with linked our discussion and bring it in front of Dashboards team and check what they think. 🙂

**Pull request merged**
