### PR TITLE
ValueFormats: Prevent rounding down of values for "Number" format

### LINKED ISSUE #49388: Default number formatter rounds numbers down to 3 significant digits
**What happened**:

Replication dashboard. https://play.grafana.org/d/Jl0M9lunz/truncating-number-decimal-places?orgId=1

Value of `2.34` correctly displays as `2.34`
Value of `222.34` is rounded to `222`.

**What you expected to happen**:

String formatter "resolves" this, but even with the number formatter, the decimals digits should not be dropped.

**How to reproduce it (as minimally and precisely as possible)**:

See replication dashboard. https://play.grafana.org/d/Jl0M9lunz/truncating-number-decimal-places?orgId=1

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Prevents auto decimal handling for the "Number" format, so precision isn't lost.

**Which issue(s) this PR fixes**:
Closes #49388

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]

**Review by leventebalogh — APPROVED** [review]
LGTM 👍

**Comment by torkelo** [comment]
It does not make for a good default experience showing this many decimals in legend, tooltip, stats etc

Screenshot from 2022-06-01 12-00-02
Screenshot from 2022-06-01 11-59-46
Screenshot from 2022-06-01 11-58-38

**Comment by kaydelaney** [comment]
Closing this for now

**Comment by torkelo** [comment]
@kaydelaney @joshhunt how about we add a new number unit that does show all decimals by default?

Not sure what to call it though

**Pull request closed without merging**
