### PR TITLE
Expose immutable to plugins

### LINKED ISSUE #12539: Include immutable for plugin development
What are thoughts on including and exposing immutable to plugins? 

I am working with react component in plugins, and it would be great to start having immutable as a standard component.

It is easy enough to include in the plugins, but since you can not reuse dependencies it is kinda anoying

Thoughts?

### PR DESCRIPTION
**Pull request by ryantxu**
simple patch to include immutable

fixes #12539

### CODE REVIEW

**Comment by davkal** [comment]
`immutable` is a dependency for `slate` and we don't use it anywhere else.
This has implications: a) slate is currently in the `// experimental` section, so `immutable` should be there as well, b) we might move away from slate and would remove its dependencies. Be aware that at that point you need to modify your plugins to ship `immutable`.

As a side note, with the increased use of the spread operator we probably won't be using `immutable` directly in grafana, and rely on creating new objects on modification instead.

@ryantxu if you're happy with these constraints and could move `immutable` to the experimental section of the imports, then I'm happy to merge this.

**Review by davkal — CHANGES_REQUESTED** [review]
if you're happy with these constraints and could move immutable to the experimental section of the imports, then I'm happy to merge this.

**Comment by torkelo** [comment]
If it's only used indirectly by a component we might switch and we do not see us needing to use this ourselves then I hesitate to expose this.

**Comment by davkal** [comment]
Agreed, sub-dependencies should not be exposed. Closing this. Apologies @ryantxu for sending you on this goose chase.

**Pull request closed without merging**
