### PR TITLE
Access Control: Add fgac to datasource query endpoints

### PR DESCRIPTION
**Pull request by kalleep**
**What this PR does / why we need it**:
Add access control to datasource query endpoints.
Register fixed role to viewers to allow them to query datasources. This role does not have a scope by design.

### CODE REVIEW

**Comment by donomii** [comment]
LGTM

**Review by donomii — APPROVED** [review]

**Review by gamab — APPROVED** [review]
Thanks again for the data source permissions meetings :+1: 
This looks good to me. Added a little nit.

Are we changing the `datasources:read` permissions everywhere in another PR?
edit: discussed with @kalleep. No `datasources:query` will only be for proxy endpoints and index settings data sources list.

**Comment by meyerder** [comment]
Looks like this request was opened just a few days prior to my ticket to support but not "quite" what I was looking for..  or maybe it is my request...

Situation:
I have multiple teams
I have some users that are not part of a team (general Access)

I have a "private" data source that I only want one or two people to be able to write queries against
All other teams/users should be able to pull up the dashboard and view it.  But not be able to create any queries against it


The High level ask is to somehow lock a data source down so that other editors can not write queries against it but still be able to view dashboards against the datasource 

I am thinking something like Add Permissions for datasource of "viewer" can query and <user/team> can create a dashboard leveraging that datasource..

Additionally, there should be the ability to do the following... to DENY access to a team at a data source level..  (or even dashboard level)

image

**Comment by sakjur** [comment]
@meyerder Pull requests are not the place for discussions or feature requests.

> I have a "private" data source that I only want one or two people to be able to write queries against
All other teams/users should be able to pull up the dashboard and view it. But not be able to create any queries against it
>
> The High level ask is to somehow lock a data source down so that other editors can not write queries against it but still be able to view dashboards against the datasource

I'd like that too, but that's a significantly larger scope of work than this.

> Additionally, there should be the ability to do the following... to DENY access to a team at a data source level.. (or even dashboard level)

We're not planning for that anytime in the near future. Deny rules introduce too much complexity compared to their utility.

**Pull request merged**
