### PR TITLE
Build pipeline: Cleanup PR pipeline steps

### LINKED ISSUE #38455: Build Packaging: CI/CD Improvements - Pipeline steps dependencies
**What it this issue about**:

This issue is an issue tracker for improvements in CI/CD step dependencies.
Steps with number of vertices and edges written next to their name, cannot be simplified more, since they don't have enough dependences (edges)

- [ ] `test-pr` https://github.com/grafana/grafana/pull/38447
- [ ] `build-main` https://github.com/grafana/grafana/pull/38484
- [x] `windows-main` **Vertices: 3 - Edges: 1**
- [x] `publish-main` **Vertices: 3 - Edges: 1**
- [x] `notify-main` **Vertices: 1 - Edges: 0**
- [ ] `oss-build-release`
- [x] `oss-windows-release` **Vertices: 3 - Edges: 1**
- [ ] `enterprise-build-release`
- [x] `enterprise-windows-release` **Vertices: 4 - Edges: 2**
- [x] `publish-release` **Vertices: 4 - Edges: 2**
- [x] `notify-release` **Vertices: 1 - Edges: 0**
- [ ] `oss-build-test-release`
- [x] `oss-windows-test-release` **Vertices: 3 - Edges: 1**
- [ ] `enterprise-build-test-release`
- [x] `enterprise-windows-test-release` **Vertices: 4 - Edges: 2**
- [x] `publish-test-release` **Vertices: 4 - Edges: 2**
- [x] `notify-test-release` **Vertices: 1 - Edges: 0**
- [ ] `oss-build-release-branch`
- [x] `oss-windows-release-branch` **Vertices: 3 - Edges: 1**
- [ ] `enterprise-build-release-branch`
- [x] `enterprise-windows-release-branch` **Vertices: 4 - Edges: 2**
- [x] `notify-release-branch` **Vertices: 1 - Edges: 0**
- [x] `scan-docker-images` **Vertices: 3 - Edges: 0**

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

After reporting problems with pipeline execution time, we need to revisit and refactor the pipeline step dependencies. This PR cleans up the `test-pr` pipeline.

Step dependency graph:

**Vertices:22, Edges: 36**

test-pr-deps

**Which issue(s) this PR fixes**:

Fixes #38455

**Special notes for your reviewer**:

After cleanup:

**Vertices:22, Edges: 26**

test-pr-clean

### CODE REVIEW

**Comment by marefr** [comment]
#33622 changed so that test-backend is run before lint-backend. Now you have changed this back. Any thoughts about this?

**Comment by dsotirakis** [comment]
@marefr remember that, but in the internal last week there were many voices saying "just fail if `lint` step fails" and I kind of agree. `test-frontend` and `test-backend` take like ~6-8mins, where `lint-backend` takes ~30secs.

**Comment by marefr** [comment]
Sure makes sense

**Review by malcolmholmes — APPROVED** [review]
Looks good to me!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
