### PR TITLE
New config parameter default_theme to set default UI theme

### PR DESCRIPTION
**Pull request by acmnu**
New config parameter default_theme. Allow to set UI default theme globally. 

What is done:
- Hard code in pkg/services/sqlstore/preferences.go:29 has been removed
- New setting "default_theme" has been added.
- Default value is "dark". No changes here.

### CODE REVIEW

**Comment by acmnu** [comment]
Look like I made something wrong. Got so many side commits. I am still bad with git.

**Comment by acmnu** [comment]
Close that request, because there is no way to pass checks for it.

**Comment by bergquist** [comment]
@acmnu I think you branced of master instead of development. Since those branches are not 100% up to date your PR will contain commits from master.

Ive updated the development branch now. So if you create a new PR it should be fine :)

**Comment by acmnu** [comment]
@bergquist, Yes previously I did it from master, but then made rebase on development. Somewhere here I messed it up.

**Pull request closed without merging**
