### PR TITLE
Docs: Fix image in what's new article

### PR DESCRIPTION
**Pull request by torkelo**
Noticed this was using the wrong image.

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

**Comment by achatterjee-grafana** [comment]
Since `latest` is till 8.0, we do not need to backport the changes. TY

**Comment by torkelo** [comment]
@achatterjee-grafana we need to backport this to both v8.1 and v8.0 otherwise it will always be wrong for latest and next and not fixed until we make v8.2 latest

**Comment by achatterjee-grafana** [comment]
@robbymilo and @petros - FYI.

**Comment by petros** [comment]
🤔 no idea why I am mentioned.

**Comment by achatterjee-grafana** [comment]
> 🤔 no idea why I am mentioned.

Sorry - I tagged you by mistake. Please ignore it. TY

**Pull request merged**
