### PR TITLE
Chore: Move identity and errutil to apimachinery module

### PR DESCRIPTION
**Pull request by ryantxu**
This PR moves two key packages (identity and errutil) into the grafana apimachinery module.  The apimachinery module has the minimum required dependencies for future app platform based backends and clients.

This touches many files, but does not change any logic.

The major changes are:
| Before | After |
|--|--|
| pkg/services/auth/identity  →  | pkg/apimachinery/identity |
| pkg/models/roletype/role_type.go.  → | pkg/apimachinery/identity/role_type.go |
| pkg/util/errutil  →  | pkg/apimachinery/errutil |

errhttp depends on apiserver, so we are keeping it in the main module for now:
```
pkg/util/errutil/errhttp → pkg/util/errhttp
```

Everything else is import updates!

### CODE REVIEW

**Review by kalleep — COMMENTED** [review]
Makes sens to move the identity package. I think you should update CODEOWNER file so that @\grafana/identity-access-team is still owner of that package

**Review by kalleep — APPROVED** [review]
LGMT for identity package

**Comment by diegommm** [comment]
Nice! Is this related to https://github.com/grafana/grafana/pull/89071?

**Review by marefr — APPROVED** [review]
LGTM, but there's been discussion using errutil (or some parts of it) in plugins or external repositories so maybe it should be in its own module or otherwise we move around things later again if needed

**Comment by ryantxu** [comment]
> Nice! Is this related to https://github.com/grafana/grafana/pull/89071?

@diegommm  Yes -- I am hoping to split that into two parts:
1. a new module that supports the grpc/protobuf API and all validation etc.  This could be imported into projects that explore alternative storage backends, but keep all the same validation messages etc
2. the actual SQL side... mostly copied from entity API

**Pull request merged**
