### PR TITLE
Graph: New series override transform constant that renders a single point as a line across the whole graph

### LINKED ISSUE #9084: [Feature request] Allow queries for Threshold lines
Please include this information:
- What Grafana version are you using?
4.4.3

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Linux

Prometheus provides some analytics queries, like `quantile_over_time()`. The can be used as "instant" queries that give you one value that could be used to set a Thresholds line. 

A common use case for this would be to display the "95th Percentile" on network graphs.

### PR DESCRIPTION
**Pull request by davkal**
- [x] ability to define a series override that takes the first value of a
timeseries and produces constant series from it.
- [x] error handling and tests 

Screenshot 2019-09-13 at 18 43 36

Fixes #9084
Alternative to #18770

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
This is great! I was about to propose this solution as well! @ryantxu what do you think?

**Review by ryantxu — APPROVED** [review]
Looks great -- simple

**Review by dprokop — APPROVED** [review]
Super duper simple!

**Comment by davkal** [comment]
Will add some docs to this PR.

**Pull request merged**
