### PR TITLE
DashList: Use blue link color on hover instead underline

### PR DESCRIPTION
**Pull request by torkelo**
* Use blue link + underline for hover effect 
* Remove background hover highlight 

Screenshot from 2023-01-19 13-26-23

### CODE REVIEW

**Comment by Ijin08** [comment]
I don't have any strong feelings around it. Both underline and blue text indicates a link.
I think the important part is that it is consistent throughout the product. 

I guess this is a topic for the DS team(@staton-hyse11 @JoaoSilvaGrafana)

**Comment by staton-hyse11** [comment]
I would recommend keeping the underline on hover for accessibility considerations. The secondary text and blue hover don't have enough contrast difference between them to make it accessible for only a color change. 

It is important to have a color and visual change for low-vis users.

**Comment by JoaoSilvaGrafana** [comment]
Agree with Staton on this. This is a bigger work that we need to do to make links more consistent across the product, but the underlining should be something we keep in my opinion.

**Comment by torkelo** [comment]
@Ijin08 @staton-hyse11 What I was trying here was to make users associate blue with link here (something Grafana is not good at). But we can't have all links blue in most views that have many links as it would lead to just blue text (hence github issue lists and many other apps use text color but a hover effect like underline+blue). 

The current hover effect is a highlight on the whole row (+ underline), and it just looked a lot better with blue here and enforces blue = link to another page design. 

What if we make the hover effect underline + blue? 
Proposal: 
Screenshot from 2023-01-19 13-26-23

Current: 
Screenshot from 2023-01-19 13-26-41

**Comment by staton-hyse11** [comment]
I like that!

**Comment by Ijin08** [comment]
LGTM

**Review by Ijin08 — APPROVED** [review]

**Pull request merged**
