### PR TITLE
Runtime: make sure we don't lose nested default config values

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
Prior to this PR we will lose all nested default values if parts of the nested object is set in the override configuration.

**Special notes for your reviewer**:
I just changed to `merge` instead of `extend` which will merge all of the source objects into the current object and skip everything form the source objects that is undefined or not set.

### CODE REVIEW

**Review by hugohaggmark — APPROVED** [review]
LGTM!

**Comment by torkelo** [comment]
The end to end tests fail with new variables

**Comment by mckn** [comment]
@torkelo will have a look at those tomorrow

**Comment by hugohaggmark** [comment]
> @torkelo will have a look at those tomorrow

I think it's awesome that you will look into this @mckn , maybe we should look into it together or maybe you can start and I'll help out if you need any help that is?

**Comment by mckn** [comment]
hmm, the e2e succeeds for me locally.

**Comment by mckn** [comment]
> hmm, the e2e succeeds for me locally.

will try to do a clean installation and try again.

**Comment by hugohaggmark** [comment]
Looks good @mckn, what do you think about removing lines https://github.com/grafana/grafana/blob/f38a269f3ac00b1645401dded40639e75a2921e3/e2e/suite1/specs/queryVariableCrud.spec.ts#L621-L625

**Comment by mckn** [comment]
> Looks good @mckn, what do you think about removing lines
> 
> https://github.com/grafana/grafana/blob/f38a269f3ac00b1645401dded40639e75a2921e3/e2e/suite1/specs/queryVariableCrud.spec.ts#L621-L625

Sounds good to me :)

**Pull request merged**
