### PR TITLE
NavBar: Sanitized NavBar children links to remove angular interpolation

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

Adds sanitization to the navbar children URLs.

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]

**Comment by torkelo** [comment]
do we need this? Does not https://github.com/grafana/grafana/pull/40822 also fix this ?

**Comment by dsotirakis** [comment]
> do we need this? Does not #40822 also fix this ?

@oscarkilhed @axelavargas ^^

**Comment by dprokop** [comment]
It does

**Comment by torkelo** [comment]
@dprokop so this PR is not needed for main/8.3 as #40822 also fixes this

**Comment by dprokop** [comment]
> @dprokop so this PR is not needed for main/8.3 as #40822 also fixes this

Indeed, no need for that as angular doesn't touch non-angular scoped DOM elements anymore.

**Pull request closed without merging**
