### PR TITLE
Loki: Add `unpack` query builder hint

### PR DESCRIPTION
**Pull request by svennergr**
**What is this feature?**

This PR adds hints if users have log lines that are in a `packed` format. Those lines come from the `pack` stage at ingestion: https://grafana.com/docs/loki/latest/clients/promtail/stages/pack/

**Special notes for your reviewer:**

1. Start Grafana and Loki (`make devenv sources=loki`)
2. Write a new LogQL query using the query builder.
3. Select `place` as label key and `moon` as value.
4. See `unpack` parser being suggested.

image

### CODE REVIEW

**Comment by matyax** [comment]
We should also suggest it in Monaco, correct? Like we do with detected parsers.

**Review by matyax — APPROVED** [review]
Looks good!

**Comment by svennergr** [comment]
> We should also suggest it in Monaco, correct? Like we do with detected parsers.

Added in 1bb559aadf0fb55459ce64c48cbe4325e6fff7a5. Let me know if I miss anything!

**Comment by matyax** [comment]
Verified!

imagen

Maybe we should show both json and unpack as detected?

**Review by matyax — APPROVED** [review]
👌

**Pull request merged**
