### PR TITLE
Update sign-a-plugin.md

### PR DESCRIPTION
**Pull request by cfossguy**
Update docs to reflect that "private plugins" are not supported in Grafana Cloud.

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

### CODE REVIEW

**Review by josmperez — APPROVED** [review]
Looks good. It looks like you may have some linting errors caused by not running Prettier. Let me know if you want more info about it.

**Review by leventebalogh — APPROVED** [review]

**Comment by marefr** [comment]
@cfossguy please [sign the CLA](https://github.com/grafana/grafana/pull/65541#issuecomment-1488755542) before we can go ahead and merge this.

**Comment by tolzhabayev** [comment]
I am not sure we need this information in developer documentation, but rather somewhere here https://grafana.com/docs/grafana-cloud/data-configuration/get-started-data/#use-data-sources-to-monitor-existing-databases

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
I would rather update this documentation https://grafana.com/docs/grafana-cloud/data-configuration/get-started-data/#use-data-sources-to-monitor-existing-databases

For example from:
"Note: You can only install signed plugins in Grafana Cloud. To learn more about signing a plugin, see [Sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin)."

To:

"Note: You can only install plugins published to our [plugins catalog](https://grafana.com/grafana/plugins/)."

The one you are currently trying to update is only for How to sign a plugin and has nothing to do with Grafana cloud.

**Comment by tonypowa** [comment]
@cfossguy 

hi and thank you for your contribution 🚀 

could you please review the feedback from @tolzhabayev , and sign the CLA ?

**Pull request closed without merging**
