### PR TITLE
datatrails: add ability to deselect currently metric

### PR DESCRIPTION
**Pull request by darrenjaneczek**
**What is this feature?**

Added an option to remove the currently selected metric, and return to the main metric selector.
image

Creates a new trail node for metric changed.
image
It looks similar to the start node, as it is a sort of restart.

**Special notes for your reviewer:**

- [ ] Decide on which button/menu approach works best
- [ ] Decide how to display the metric change node to indicate that the metric has been deselected
- [x] Use a 'green' start/clear node instead of orange

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by catherineymgui** [comment]
Hey - yeah so the user can use the breadcrumbs to navigate back to the landing page, but we had multiple ask how to keep their filters when selecting a new metric. 

The idea is that they would have filters --> click a button --> this creates a new step for metric select.

What are your thoughts?

Originally we were thinking of just having a button beside the select metric but there were technical complications. This button can also be moved to beside the heatmap / percentile toggles.

Screenshot 2024-03-15 at 10 35 41

**Comment by torkelo** [comment]
> but we had multiple ask how to keep their filters when selecting a new metric.

@catherineymgui the "Related metrics" tab is specifically designed for this use case so maybe we can rename that tab?

**Comment by torkelo** [comment]
@darrenjaneczek why can't we use the related metrics tab? it is designed for when you want to go from one metric name to another while preserving all your filters

**Comment by torkelo** [comment]
Maybe we rename to to "other metrics" ?

**Comment by darrenjaneczek** [comment]
If I understand right, there was a user desire to explicitly deselect the current metric to restore the unsorted view of all metrics, but as a forward-moving step.

**Comment by torkelo** [comment]
@darrenjaneczek beside the sorting it's identical :) 

maybe we can use the breadcrumb toolbar (right side). but not sure what the name / wording should be of this button. Everything that I can think of feels awkward. 

Another solution would be to use the breadcrumb and add a new level "Explore > Metrics > Select metric > metric view"

**Comment by torkelo** [comment]
Another idea is to switch back from the tabs to the original “Action” button design under the main graph we could have “Related metrics” and “Select another metric” if we want to have separate actions for this.

Screenshot 2023-11-28 at 16 54 25

**Comment by catherineymgui** [comment]
I really like the idea of having a breadcrumb that separates Select Metric. However I think this needs more UX consideration and testing and would be out of scope for MVP?

If we move the button elsewhere - we could have it with the other action buttons (explore, share, etc.) and we can keep the current tabs 

Screenshot 2024-03-18 at 09 07 24

**Comment by torkelo** [comment]
@catherineymgui yea, I like your last suggestion there with putting it next to the other action buttons, this way it does not clutter up the UI with adding action buttons in new places :) 

image

**Comment by catherineymgui** [comment]
I think the action here is selecting a new metric (not deselecting the old metric)?

So I think the breadcrumb tooltip can be called
"metric
Select new metric"?

And the button tooltip can be "Remove existing metric and choose a new metric"

**Comment by darrenjaneczek** [comment]
image

image

**Review by catherineymgui — APPROVED** [review]

**Pull request merged**
