### PR TITLE
Upgrade the build pipeline to 2.4.5

### PR DESCRIPTION
**Pull request by bergquist**
Signed-off-by: bergquist <carl.bergquist@gmail.com>

### CODE REVIEW

**Comment by dsotirakis** [comment]
@bergquist , thanks for raising this!
What you have to do for this to work, is to go to:

https://github.com/grafana/grafana/blob/main/scripts/drone/steps/lib.star#L3, make the change there, and then run:

`drone starlark convert`, for the changes to be reflected to .drone.yml.

You also have to sign the drone.yml file, for the build to be approved!

**Review by dsotirakis — CHANGES_REQUESTED** [review]
See comment above!

**Comment by bergquist** [comment]
@dsotirakis thanks for the help! How do I sign it?

**Review by dsotirakis — APPROVED** [review]
LGTM!

**Comment by bergquist** [comment]
:champagne:

**Pull request merged**
