### PR TITLE
grafana/ui: Add DatePicker

### PR DESCRIPTION
**Pull request by Clarity-89**
**What this PR does / why we need it**:
Move `DatePicker` from [ui-enterprise](https://github.com/grafana/ui-enterprise) to grafana/ui. The most major change is that the input value doesn't default to the current date and can be undefined. 

**Special notes for your reviewer**:

Screenshot 2021-06-15 at 15 00 38

Edit: Switched the input component to be type `text` as it makes it easier to work with and we don't use the native picker functionality anyways.

### CODE REVIEW

**Comment by Clarity-89** [comment]
@vickyyyyyyy I moved the components to grafana/ui with some minor changes, I think they can be removed from the ui-enterprise repo now, what do you think?

**Comment by vickyyyyyyy** [comment]
> @vickyyyyyyy I moved the components to grafana/ui with some minor changes, I think they can be removed from the ui-enterprise repo now, what do you think?

Awesome 🔥

I think we will still need this in ui-enterprise, otherwise, our enterprise plugins will require 8.x.x version of Grafana (the release these changes will go out in for @grafana/ui) and we don't want to up our minimum required Grafana versions from 7.x.x. Unless I'm misunderstanding?

**Review by peterholmberg — CHANGES_REQUESTED** [review]
It looks good though I'd like to group this under the TimePicker folder and then rename that folder to DateTimePicker(s).

I'm also missing an mdx doc file with examples.

**Comment by Clarity-89** [comment]
> I think we will still need this in ui-enterprise, otherwise, our enterprise plugins will require 8.x.x version of Grafana (the release these changes will go out in for @grafana/ui) and we don't want to up our minimum required Grafana versions from 7.x.x. Unless I'm misunderstanding?

Hmm, yeah I think that's correct. But not sure how that would work since you can't use any additions/fixes from the latest grafana/ui?

**Review by peterholmberg — APPROVED** [review]

**Comment by vickyyyyyyy** [comment]
> > I think we will still need this in ui-enterprise, otherwise, our enterprise plugins will require 8.x.x version of Grafana (the release these changes will go out in for @grafana/ui) and we don't want to up our minimum required Grafana versions from 7.x.x. Unless I'm misunderstanding?
> 
> Hmm, yeah I think that's correct. But not sure how that would work since you can't use any additions/fixes from the latest grafana/ui?

I think we can do this: https://github.com/grafana/ui-enterprise#unreleased-components to incorporate your changes 👍

**Pull request merged**
