### PR TITLE
Docs: Generate HTTP API markdown from swagger spec

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
First attempt to generate the HTTP API docs from the swagger specification. More specifically, this PR introduces the necessary Makefile targets for automatically generating the HTTP API docs from the [this](https://github.com/grafana/grafana/blob/main/public/api-merged.json) input. The generated markdown is stored under `docs/sources/http_api/markdown.md`.
The output can be further customised by modifying the `pkg/api/docs/markdown/docs.gotmpl` template.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
for generating the markdown:
`make http-api-docs`

after successful generation, one can inspect the output by running:
`cd docs && make docs-no-pull`
and then navigate to: [http://localhost:3002/docs/grafana/next/http_api/markdown](http://localhost:3002/docs/grafana/next/http_api/markdown).

for deleting the generated markdown:
`make http-api-docs-clean`

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
@papagian wdyt about pinning the versions of the used docker images to something else than `latest`? I think it would make the results more reproducible. We had some problems in the alerting team with having two different versions that caused confusion.

**Comment by papagian** [comment]
> @papagian wdyt about pinning the versions of the used docker images to something else than `latest`? I think it would make the results more reproducible. We had some problems in the alerting team with having two different versions that caused confusion.

yes, I think that I would like that. which version would you suggest using? `v0.29.0`

**Comment by JohnnyQQQQ** [comment]
Yeah, works for us, nice 👍

**Review by JohnnyQQQQ — COMMENTED** [review]
I'm not sure if this should be the scope of this or not but one thing that we saw when playing around with it was the representation of `enum`s was lacking allowed values. We could iterate over the enum array in the description field or something like this.

**Comment by papagian** [comment]
> I'm not sure if this should be the scope of this or not but one thing that we saw when playing around with it was the representation of `enum`s was lacking allowed values. We could iterate over the enum array in the description field or something like this.

thank you for trying it!
can you point me to an example of such an enum? how is it defined in the specification?
only example from my side is the [DsPermissionType](http://localhost:3002/docs/grafana/next/http_api/markdown/#span-idds-permission-typespan-dspermissiontype); its swagger decoration can be found [here](https://github.com/grafana/grafana/blob/ff8d96602adaaeac922854d2d5dbc1e5687c9370/pkg/services/datasources/models.go#L195-L201)

**Comment by sdboyer** [comment]
> I'm not sure if this should be the scope of this or not but one thing that we saw when playing around with it was the representation of enums was lacking allowed values. We could iterate over the enum array in the description field or something like this.

Hmm, sounds like it might be an issue with the code generators/schema translators. Could you point to some particular enums where these allowed values seemed to be lacking, so i can investigate?

**Comment by gguillotte-grafana** [comment]
Notes for docs squad reviewers:

- Run `make http-api-docs` from the `grafana` repository root, not from the `docs/` subfolder. While this outputs a file to `docs/sources`, the `make` target is in the Grafana Makefile, not the docs Makefile.
- This requires Go to be installed. If you can build Grafana from source, you're good. If not, you need to install the necessary packages. See the [Grafana developer guide](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md).
  - The version of Go in Ubuntu LTS repos' `golang` package is too old and fails with a `flag provided but not defined: -modfile` error. [Install a newer version.](https://github.com/golang/go/wiki/Ubuntu)

To publish the resulting document to the Grafana website, we'll need the website team to add the `make http-api-docs` step on their end of the publishing pipeline. CC @robbymilo

**Review by gguillotte-grafana — COMMENTED** [review]
Some questions - I don't feel qualified to block or approve the PR, although questions 2 and 3 are the biggest concerns:

1. Running `make http-api-docs` generates considerably different output than the file in this PR, including table formatting and line breaks that would not pass `prettier` checks. 

   For example, the `admin` API on the copy generated when I ran it:

   ```
   ###  admin
   
   The Admin HTTP API does not currently work with an API Token. API Tokens are currently only linked to an organization and an organization role. They cannot be given the permission of server admin, only users can be given that permission. So in order to use these API calls you will have to use Basic Auth and the Grafana user must have the Grafana Admin permission. (The default admin user is called admin and has permission to use this API.)
   
   
   
   | Method  | URI     | Summary |
   |---------|---------|---------|
   | GET | [/api/admin/settings](#admin-get-settings) | Fetch settings. |
   | GET | [/api/admin/stats](#admin-get-stats) | Fetch Grafana Stats. |
   | POST | [/api/admin/pause-all-alerts](#pause-all-alerts) | Pause/unpause all (legacy) alerts. |
   ```

   versus the one in the repo:

   ```
   ### admin

   The Admin HTTP API does not currently work with an API Token. API Tokens are currently only linked to an organization and an organization role. They cannot be given the permission of server admin, only users can be given that permission. So in order to use these API calls you will have to use Basic Auth and the Grafana user must have the Grafana Admin permission. (The default admin user is called admin and has permission to use this API.)

   | Method | URI                                              | Summary                            |
   | ------ | ------------------------------------------------ | ---------------------------------- |
   | GET    | [/api/admin/settings](#admin-get-settings)       | Fetch settings.                    |
   | GET    | [/api/admin/stats](#admin-get-stats)             | Fetch Grafana Stats.               |
   | POST   | [/api/admin/pause-all-alerts](#pause-all-alerts) | Pause/unpause all (legacy) alerts. |
   ```

   Are there additional steps necessary to reproduce the output of the file in the repo?

1. Is this output supposed to replace or supplement the HTTP API docs in `/docs/sources/developers/http_api/`? Is it also supposed to be published to grafana.com?

   If both are true, this might need to output to `/docs/sources/developers/http_api/` instead of `/docs/sources/http_api/`, and with a different filename than `markdown.md` since the filename defines the document path in HTML output when building docs. (In this case, the HTML output path as is would be /docs/grafana/latest/http_api/markdown/.)

1. From a docs maintenance perspective, the repo's copy of the generated output won't be updated automatically when the HTTP API is changed, so I'd expect that developers making changes to the HTTP API must also re-run `make http-api-docs` to update the output and include that in PRs. We should either update CONTRIBUTING.md to require this step on API-related PRs, check and require it as part of CI if the HTTP API is changed, or add `make http-api-docs` as a step to the Grafana release process.

1. Looking at the generated content, most API properties have empty `Schema` sections, and some of these have only a link to a section with no content. For example, the schema section for `adminGetSettings` links to a section called `SettingsBag`, which contains only a link to itself.

   ```
   ### <span id="settings-bag"></span> SettingsBag
   
   [SettingsBag](#settings-bag)
   ```

1. Some sections have Markdown generation issues. For example,  `SearchServiceAccountsResult` has exposed table formatting in rendered Markdown due to line breaks within the Description for `totalCount` breaking the table output.

   ```
   ### <span id="search-service-accounts-result"></span> SearchServiceAccountsResult

   > swagger: model

   **Properties**

   | Name            | Type                                          | Go type                | Required | Default | Description                                    | Example |
   | --------------- | --------------------------------------------- | ---------------------- | :------: | ------- | ---------------------------------------------- | ------- |
   | page            | int64 (formatted integer)                     | `int64`                |          |         |                                                |         |
   | perPage         | int64 (formatted integer)                     | `int64`                |          |         |                                                |         |
   | serviceAccounts | [][serviceaccountdto](#service-account-d-t-o) | `[]*ServiceAccountDTO` |          |         |                                                |         |
   | totalCount      | int64 (formatted integer)                     | `int64`                |          |         | It can be used for pagination of the user list |

   E.g. if totalCount is equal to 100 users and
   the perpage parameter is set to 10 then there are 10 pages of users. | |
   ```

When rendering `markdown.md` in a test build of grafana.com, there are additional issues which might not block this PR, but must be considered if we intend to publish the output to grafana.com:

- Table cells with code blocks have the same issues as elsewhere in the docs site - they overflow without wrapping, and neither the cell nor the page scroll horizontally if the overflow isn't visible. One example is in `ServiceAccountDTO`.

  image
- The template adds HTML `<span>` tags in order to add anchors to headings. Hugo instead adds the span tag and its text to the heading's `id` property (`span-idroute-get-alert-rule-200-schemaspan-schema`), resulting in an unexpected ID that might break some Swagger-generated anchor links.
- Some links to anchors, such as #interface for `interface{}`, don't have corresponding destination anchors and don't work.
- The output lacks an H1 header or Hugo frontmatter, leaving the nav menu entry for it blank in test builds of the output.
  
  image

**Comment by robbymilo** [comment]
> To publish the resulting document to the Grafana website, we'll need the website team to add the `make http-api-docs` step on their end of the publishing pipeline. CC @robbymilo

This would need to run on the docs publish workflow in this repo, similar to how the https://grafana.com/docs/grafana/latest/packages_api/ docs are generated (see https://github.com/grafana/grafana/blob/main/.github/workflows/publish.yml#L19).

**Comment by gtk-grafana** [comment]
Is this still in progress or should we close this?

**Comment by sdboyer** [comment]
Let's keep it open. I think there's a way we incorporate this with other in-flight work.

**Pull request closed without merging**
