### PR TITLE
UI text edits

### PR DESCRIPTION
**Pull request by oddlittlebird**
Minor text edits

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
LGTM

**Comment by oddlittlebird** [comment]
@dsotirakis, could you take a look? I didn't get any complaints from my linter while I was working.

**Comment by dsotirakis** [comment]
> @dsotirakis, could you take a look? I didn't get any complaints from my linter while I was working.

Hm strange - my VS Code did complain 🤔  Fixed!

**Review by dsotirakis — APPROVED** [review]

**Comment by dsotirakis** [comment]
> > > @dsotirakis, could you take a look? I didn't get any complaints from my linter while I was working.
> > 
> > 
> > Hm strange - my VS Code did complain 🤔 Fixed!
> 
> Still not passing. Maybe we can take a look tomorrow morning.

@oddlittlebird yeah some test snapshots (fixed expected test results) needed updating as well so not a doc formatting issue! Maybe we should figure out a way to update those snapshots automatically, since it may be confusing

**Comment by oddlittlebird** [comment]
If you say so. I have no idea what snapshots are in this context, so I'll trust you on that. :P

**Pull request merged**
