### PR TITLE
Arranged http_api docs in a better way

### LINKED ISSUE #3828: Docs: Split http_api doc into multiple files
We should split the http_api.md doc into multiple files in a dedicated http_api directory. The single doc is too long to find stuff and with more docs we can have stuff elaborated. 

Would have helped #3826 and many other tickets.

### PR DESCRIPTION
**Pull request by utkarshcmu**
@bergquist - Resolves #3828

### CODE REVIEW

**Comment by torkelo** [comment]
I can't find a change in the root page, how are you to find the specific pages?

**Comment by utkarshcmu** [comment]
Will look into this ASAP.

**Comment by utkarshcmu** [comment]
The only issue I see in this PR is this:

**search going to another line**

screen shot 2016-02-05 at 1 53 29 am

How can I make it to be in the same line? Any hints?

**Comment by utkarshcmu** [comment]
This looking good now?

**Pull request merged**
