### PR TITLE
 Changed the encrypt default value to false 

### LINKED ISSUE #67492: MSSQL: Change encrypt default value to false
**What is the chore?**:

In the MSSQL data source config page the default value for the encrypt field is disabled but the tooltip and the docs says it is false. We should change the default value to false.

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/mssql/configuration/ConfigurationEditor.tsx#L189

**Is there anything else we need to know?**:

### PR DESCRIPTION
**Pull request by tanishk-agarwal**
Closes https://github.com/grafana/grafana/issues/67492

Changed the encrypt field value to false aligining with the documentation and tooltip.

### CODE REVIEW

**Comment by zoltanbedi** [comment]
@tanishk-agarwal can you please sign the cla?

**Comment by zoltanbedi** [comment]
@tanishk-agarwal looks like you didn't commit this with your email that is associated with GitHub. Please take a look at this https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by tanishk-agarwal** [comment]
@zoltanbedi I have made the necessary changes.

**Comment by zoltanbedi** [comment]
@tanishk-agarwal what change did you do?

**Comment by tanishk-agarwal** [comment]
@zoltanbedi I have changed the email address according to the steps mentioned in the documentation.

**Comment by zoltanbedi** [comment]
@tanishk-agarwal sorry, I thought the guide above also says how to fix the last commit.
Please run:
`git commit --amend --author="Author Name <email@address.com>"`
`git push --force`

This will change the author for your last commit and so GitHub and the cli check will recognize you.

**Comment by zoltanbedi** [comment]
Thanks for creating this PR @tanishk-agarwal. I'm going to close it as we can't merge it without the cla signed.

**Pull request closed without merging**
