### PR TITLE
Chore: Add appcontext.WithUser and appcontext.User

### LINKED ISSUE #50983: Support getting the current user through context.Context
We currently do some gymnastics to pass the current user around to many functions.  In cases where we can not directly do this, it gets pretty weird.  For example see https://github.com/grafana/grafana/blob/main/pkg/services/searchV2/service.go#L79

It would be great fetch the signed in user in a consistent way using some pattern like: https://medium.com/@matryer/context-keys-in-go-5312346a868d

### PR DESCRIPTION
**Pull request by toddtreece**
**What this PR does / why we need it**:

@ArturWierzbicki suggested that this should be split out of #57420. Adds `appcontext.WithUser` and `appcontext.User` based on a suggested interface from @marefr in https://github.com/grafana/grafana/issues/50983#issuecomment-1160600222.

> My idea back then was to introduce a new package, appcontext (in lack of better name)? Having a function With<something> to populate the context and a function <something> to read the value from the context in a typesafe way, e.g.
> 
> ```
> package appcontext
> 
> func WithUser(ctx context.Context, user *models.SignedInUser) context.Context {
>   ...
>   return ctx
> }
> 
> func User(ctx context.Context) *models.SignedInUser {
>   ...
> }
> ```

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/50983

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by toddtreece** [comment]
@ryantxu i will follow up with a PR to do that once this one is approved

**Comment by ArturWierzbicki** [comment]
I'd say this is great! One thing we could add in a comment is strong guidance wrt usage - eg `use it for all new service methods`, or `use it at your own risk - user might be null in X scenario`.

I am not sure how to think about this in context of background jobs, specifically how do we communicate the necessity of putting the user in the context to people who develop new background jobs. Thoughts?

**Comment by toddtreece** [comment]
> I am not sure how to think about this in context of background jobs, specifically how do we communicate the necessity of putting the user in the context to people who develop new background jobs. Thoughts?

@ArturWierzbicki it seems like it might be strange if a background job that wasn't initiated by user activity had a `user.SignedInUser`, but i am not sure i have enough context (no pun intended) about the current patterns in background jobs. @grafana/backend-platform thoughts?

**Comment by ArturWierzbicki** [comment]
> > I am not sure how to think about this in context of background jobs, specifically how do we communicate the necessity of putting the user in the context to people who develop new background jobs. Thoughts?
> 
> @ArturWierzbicki it seems like it might be strange if a background job that wasn't initiated by user activity had a `user.SignedInUser`, but i am not sure i have enough context (no pun intended) about the current patterns in background jobs. @grafana/backend-platform thoughts?

I am thinking about services like reporting or alerting which have to use other backend services that _do_ require the `SignedInUser` (example with a fake 'scheduler' user https://github.com/grafana/grafana/blob/4eb8e4ff669e449f9a225c826f8f74c1a2cc66da/pkg/services/ngalert/eval/eval.go#L209). 

Right now, if a service requires the `SignedInUser` its not a problem - it has to be provided in a parameter (see example). It could become an issue if that requirement were to become implicit, and services started relying on the user to be provided in the ctx. 

But yeah, backends team feedback would be great:)

**Comment by mildwonkey** [comment]
ha! I spent Friday wondering why user and org wasn't part of the request context. I'm very much in favor of this change in concept, though I don't have a strong opinion on the implementation. 

(I'm still the newest person on the backend squad, so I probably have some details wrong.)

I agree that there will be challenges in rolling this out, but what you've described sounds like defensive programming we should be doing anyway. Methods should expect that any request could be initiated by an entity other than a signed in user, and return an error if a required user is nil or empty ("err: humans only"). At most it sounds like using this new feature encourages good coding practices. 

<below is my opinion, free to disagree or ignore>
This is fresh in mind as I've found many places where Grafana assumes that variables always have a set value. It's quite easy to cause panics in our code base by writing tests and passing a `nil` in the wrong place. I know we can't catch everything, but just in general I'd like to see Grafana checking all values which could be empty or nil, even if it's unlikely or unexpected they would ever be unset.

**Comment by marefr** [comment]
> > > I am not sure how to think about this in context of background jobs, specifically how do we communicate the necessity of putting the user in the context to people who develop new background jobs. Thoughts?
> > 
> > 
> > @ArturWierzbicki it seems like it might be strange if a background job that wasn't initiated by user activity had a `user.SignedInUser`, but i am not sure i have enough context (no pun intended) about the current patterns in background jobs. @grafana/backend-platform thoughts?
> 
> I am thinking about services like reporting or alerting which have to use other backend services that _do_ require the `SignedInUser` (example with a fake 'scheduler' user
> 
> https://github.com/grafana/grafana/blob/4eb8e4ff669e449f9a225c826f8f74c1a2cc66da/pkg/services/ngalert/eval/eval.go#L209
> 
> ).
> Right now, if a service requires the `SignedInUser` its not a problem - it has to be provided in a parameter (see example). It could become an issue if that requirement were to become implicit, and services started relying on the user to be provided in the ctx.
> 
> But yeah, backends team feedback would be great:)

Basically same "problem" as I added/tried to describe in https://docs.google.com/document/d/1zltvF7I9UHJSE8NkM3CeHoWcK11VsYwdDrs0xDqtB9Q/edit#heading=h.x6ys3jo952ox

**Review by marefr — APPROVED** [review]
LGTM this is a good first step :+1: 

But I agree with your comments, it could have weird side-effects. Maybe introduce a `MustUser` that would panic if the user is nil? Still to compile-time support for potential nil user.

Nit. Could maybe put this directly under pkg/appcontext, but not sure everyone agree with that?

Nit. Could call `appcontext.WithUser` from those places (contexthandler.go etc) that populates the context with user. Would simplify the `User` function as well and make this package basically only depend on `user.SignedInUser`. Maybe this have some other side-affects though?

**Comment by toddtreece** [comment]
i added a `MustUser` as @marefr suggested and changed it so that `User` now returns an error if a user is missing from the context. @mildwonkey @ArturWierzbicki thoughts?

**Review by ArturWierzbicki — APPROVED** [review]
🚀🚀

**Review by sakjur — APPROVED** [review]
I essentially agree with Kristin. :+1:

I don't think this is intended as or should be a carte blanche to start passing things through the context, but for the things that is part of the `ReqContext` struct I think it'd be generally preferable to pass it like this rather than having a mega-object containing information about unrelated concepts.

**Pull request merged**
