### PR TITLE
Chore: Improve code complexity (Error handling backend)

### LINKED ISSUE #56387: Provisioning API returns generic error for invalid duration
**What happened**:

The Provisioning API returns the following generic error when the `For` field is invalid:

```
{"message":"bad request data","traceID":""}
```

The error is logged here:

```
ERROR[10-05|11:21:33] bad request data logger=context userId=1 orgId=1 uname=admin error="not a valid duration string: \"300\"" remote_addr=127.0.0.1 traceID=
```

However it should also be sent in the response.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by A-5ingh**
**What this PR does / why we need it**: Actually, the issue is not reproducible but looks like the code complexity could be reduced in the function which handles the Response error.

**Which issue(s) this PR fixes**:

Fixes #56387

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sakjur** [comment]
Hi, thank you for your pull request, but it doesn’t fix the problem that @grobinson-grafana wants it to fix (which seems to be to set the error message in prod as well as development).
You don’t want to change anything in the generic web packages to fix that, the support to do so is already present.

I’ll close this PR because it’s preference-based and doesn’t clearly improve legibility and it doesn’t solve the problem it set out to. While refactorings such as these can be valuable, I think that requires a common mindset either in the form of a consensus or a decision 🙂

**Comment by sakjur** [comment]
You are welcome to add and reopen this pull request if you’d like 👍 (let me know if you can’t reopen it yourself)

**Comment by A-5ingh** [comment]
@sakjur Sure, I'm planning to open a new MR. I just have a quick question about generic web package, what does it mean by generic web package or which file are you referring to? 
I was thinking of changing this [line](https://github.com/grafana/grafana/blob/a9c0afcc1fd09418953c9afb343cd97259c246f7/pkg/api/response/response.go#L213) to enable the error logs for production.

**Comment by sakjur** [comment]
Don't do that, there are errors that we don't want to disclose to the end user. You'll want to update the error logging from the endpoint. It seems to be in a generated endpoint that I don't know much about, but this line (and others like it in this file) seems like what you'd want to update with a more appropriate message.

https://github.com/grafana/grafana/blob/b19855922517523cb15aa61689319d5b6dc66aea/pkg/services/ngalert/api/generated_base_api_provisioning.go#L103

**Comment by A-5ingh** [comment]
Oh ok thanks. Let me do some more analysis. I'm new to grafana so will take time to insert.

**Pull request closed without merging**
