### PR TITLE
Loki: Align query interval with step

### PR DESCRIPTION
**Pull request by Dreace**
**What this PR does / why we need it**:
For example, with 15s step:
2020-12-20 10:55:03\~2020-12-20 10:55:18
will align to
2020-12-20 10:55:00\~2020-12-20 10:55:15,
then about-same-time query results look the same.

### CODE REVIEW

**Comment by aocenas** [comment]
@Dreace sorry for taking so long with this PR. We will take a look asap.

**Comment by ivanahuckova** [comment]
Hello @Dreace, can you please provide more information on how to recreate the issue and why is this PR useful/what problem does it solve. Thank you!

**Comment by Dreace** [comment]
> Hello @Dreace, can you please provide more information on how to recreate the issue and why is this PR useful/what problem does it solve. Thank you!

If the time is not aligned, aggregating data over a period of time will result in different data obtained from each aggregation.
For example, if the data is aggregated every fifteen seconds, if the time is not aligned, the starting time period may be 10:00:03, 10:00:17, 10:00:31. If the time is aligned, it will become 10:00:00, 10:00:15, 10:00:30, then stable data can be obtained.
Code reference from:
https://github.com/grafana/grafana/blob/086c77f5e31a0bd21df6394010456f4652828665/public/app/plugins/datasource/prometheus/datasource.ts#L783-L802

**Review by davkal — CHANGES_REQUESTED** [review]
Yeah, we do the alignment in the prometheus datasource to make data from roughly the same time period looks the same. We could (and probably should) do this for Loki metrics queries as well. The problem is that in `createRangeQuery` we currently don't know if the query is a logs or a metrics query. Alignment for logs queries does not make much sense, plus a lot of log lines can be produced in one second (the current static alignment), so the user should be able to trust that the logs show up for the requested second. 

So for this PR to go forward, the alignment has to be limited to metric queries.

**Review by ivanahuckova — COMMENTED** [review]
Also, metrics queries are already aligned by Loki itself. So I am wondering, if this is necessary to do on Grafana's side as well.

**Pull request closed without merging**
