### PR TITLE
AzureMonitor: Automate retrieval of supported Metrics namespaces

### LINKED ISSUE #50239: AzureMonitor: Don't maintain whitelist of supported metric namespaces
### Discussed in https://github.com/grafana/grafana/discussions/41982

<div type='discussions-op-text'>

<sup>Originally posted by **joshhunt** April 13, 2021</sup>
Having a manually maintained list of [`supportedMetricNamespaces`](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts) that controls the metric namespaces that can be queries through Azure Monitor metrics leads to a maintenance burden and feature requests from missing services, such as #28733.

Needs investigating, but we should either remove this list (don't filter on our end) or use an API to get supported metric namespaces. Will need to investigate how National Clouds plays into this.</div>

As far as I can see, there is no need to filter resources by namespace so we can remove the file: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts

### PR DESCRIPTION
**Pull request by aangelisc**
**What this PR does / why we need it**:

This PR automates the retrieval of supported metrics namespaces rather than maintaining a hardcoded list. This process is carried out for each subscription to ensure complete coverage for a user.

**Which issue(s) this PR fixes**:

Fixes #50239 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
LGTM!

**Review by asimpson — APPROVED** [review]

**Comment by aangelisc** [comment]
Not too sure why there have been changes to [pkg/services/ngalert/eval/evaluator_mock.go](https://github.com/grafana/grafana/pull/53203/files#diff-770c0ab65a54e51dca05e1a32e8af59f02bf9624d09376ebe87b388c02c353ba) - @andresmgot would you suggest I revert these manually?

**Comment by andresmgot** [comment]
yes, it seems that something weird happen when merging that. There should be no changes in that file.

**Comment by gguillotte-grafana** [comment]
Noting for posterity: This broke a docs link in the Azure Monitor data source docs, which relied on `metricNamespaces.ts` to list compatibility.

See [/docs/sources/datasources/azuremonitor/_index.md](https://github.com/grafana/grafana/blame/7146f2731c4ebc4f93c8fe0c634359c3dd89c6dc/docs/sources/datasources/azuremonitor/_index.md#L108), #51302, #51302, #50788.

> Not all metrics returned by the Azure Monitor Metrics API have values. To make it easier for you when building a query, the Grafana data source has a list of supported metrics and ignores metrics which will never have values. This list is updated regularly as new services and metrics are added to the Azure cloud. For more information about the list of metrics, refer to [current supported namespaces](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azureMetadata/metricNamespaces.ts).

**Pull request merged**
