### PR TITLE
Core: Add go-datemath library

### PR DESCRIPTION
**Pull request by AgnesToulet**
**What this PR does / why we need it**:
Add go-datemath library to handle dates in the backend as we do in the frontend (used in reporting extension).

### CODE REVIEW

**Review by sakjur — APPROVED** [review]

**Comment by marefr** [comment]
1. When we added support for elasticsearch alerting the initial contributor added this library as well. We ended up adding a small util function instead. Let me see if I can find a link.
1. Wonder if tsdb package don't already have support for what you're looking for?

**Comment by marefr** [comment]
Here's tsdb time range: https://github.com/grafana/grafana/blob/master/pkg/tsdb/time_range.go

**Comment by marefr** [comment]
Here's index pattern parsing which I had in mind for elasticsearch: https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/index_pattern.go

**Comment by sakjur** [comment]
> Here's tsdb time range: https://github.com/grafana/grafana/blob/master/pkg/tsdb/time_range.go

We've been using it as well, but struck into the problem of it using Go's parse duration which does not behave the same as the ElasticSearch duration since all ambiguous durations are dropped (i.e. no support for days, weeks, months, or years).

**Comment by marefr** [comment]
I see. Have you considered updating code for time range to support that? Can you provide examples of some supported in UI, but not in backend?

We also have gtime but it's currently for duration/intervals: https://github.com/grafana/grafana/blob/master/pkg/components/gtime/gtime.go

Not saying that you shouldn't bring in a library. But if bringing in a library probably should replace other parts of the code base to remove code duplication. Could of course happen later/separate PR, but important we don't forget about it.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/blob/master/pkg/components/gtime/gtime.go#L12 Have fairly few usages so I agree that we should replace if it behaves the same.

**Comment by AgnesToulet** [comment]
@marefr every expression containing `d`, `w`, `M` or `y` as this one for example: `now-1d/d`
Updating the code for time range to handle that means rewriting it to do pretty much the same as the library we want to add. We can't just extend what is done as the limitation comes from the Golang function we use.

But yes, if we add this library, we could rewrite https://github.com/grafana/grafana/blob/master/pkg/tsdb/time_range.go to use it. 

@sakjur Do you think I should do it in this PR so we could directly use timerange in the reporting feature or should it be a new issue?

https://github.com/grafana/grafana/blob/master/pkg/components/gtime/gtime.go seems pretty different though

**Comment by sakjur** [comment]
`gtime` looks really promising. Maybe we can update it.

I agree that we should always be skeptical against introducing external dependencies.
One neat thing about this library is that it uses YACC instead of a hand-written parser, but if a simple update to the `gtime` code and changing tsdb to use `gtime` that would be a better option.

**Comment by AgnesToulet** [comment]
`gtime` is pretty far from what we want so it wouldn't be a simple update to do. I can work on it if it's your preferred solution but it will take much more time.

If everyone agrees to add the library, I can work on updating `timerange` to use it. In this case, I can do it in this PR or in another one as you prefer.

**Comment by sakjur** [comment]
Let me try to spec what it is that we require:

- Fixed time (UNIX timestamps, since that's what's being used by Grafana)
- Relative time
  - `now-1h` (supported in tsdb)
  - `now+1h` (not supported in tsdb unless I'm mistaken?)
  - `now-1M` (not supported in tsdb or gtime)
  - `now/M` rounded both down and up (i.e. beginning of this month, end of this month)
  - combination of the above 👆 i.e. `now+2h-3d/w` (why would you do that? No idea. But you can do it, although it does break the current "human readable time difference" behavior in the dropdown 😇, see picture below)

I think the ranges we want to support is at least the `[smhdwMy]`.

Screen Shot 2020-03-24 at 11 51 16

**Comment by bergquist** [comment]
Looking into `go-datemath` a bit more I definitely think we should migrate towards that and replace current versions.

* `go-datemath` handles math on months better. (which `gtime` doesnt`)
* `now/M` would be really nice for those who use Grafana for monthly reports. (yes) 
* Supports business day unit. (we need to add support for this in the frontend)

> Would be nice to also support an advanced combination of the above point_up_2 i.e. now+2h-3d/w

This sure breaks the human-readable aspect as you mentioned. Unless we have a good and common reason for anyone doing it I think we should avoid talking about it :)

@AgnesToulet @sakjur any chance you can take a swing at replacing either `gtime` or tsdb timerange features? with `go-datemath`

**Comment by sakjur** [comment]
I loved their business day addition. Didn't mention it since it's nothing we needed for parity with frontend (which is what we're aiming for).

@AgnesToulet You talked about looking into adding the `gtime`/`tsdb` improvements in addition to adding this as an extensions dependency, right? Otherwise I can take a look at that, either way our team will make sure to do that.

**Comment by AgnesToulet** [comment]
Yes, I'll take a look at that today. 

@bergquist Are you ok to merge this PR and do this in a second PR? (I'll create the issue related to this)

**Comment by bergquist** [comment]
@AgnesToulet Sounds good. Perhaps you could create an issue for migrating other parts of grafana to use the `go-datemath` lib

**Review by bergquist — APPROVED** [review]
LGTMMMM

**Comment by AgnesToulet** [comment]
Other parts than `gtime` and `timerange`? I'm not aware of them but don't hesitate to edit the issue to add them #23100.

**Pull request merged**
