### PR TITLE
feat: added time range as legend to the graph chart

### PR DESCRIPTION
**Pull request by JavierDelgadoFernandez**
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

### CODE REVIEW

**Comment by torkelo** [comment]
Can you please open a feature request issue for this and explain the use case for this feature?

**Comment by JavierDelgadoFernandez** [comment]
Thanks a lot @torkelo, feature request issue opened in #9163

**Comment by torkelo** [comment]
think using the use the timeInfo field that is already there and shown in the upper right is the better solution.

**Comment by JavierDelgadoFernandez** [comment]
Thanks @torkelo, this is how it looks like now:
screenshot_20171004_164346

**Comment by torkelo** [comment]
this sadly needs to be reimplemented due to rewrites in master since this was written. 

Also not sure sure that a setting is needed for this. Maybe just an optional url parameter that can be used for the solo route?

**Pull request closed without merging**
