### PR TITLE
Navigation: Use new page layout in Service accounts item page

### LINKED ISSUE #53967: Page layout: Service accounts item page
- [x] convert to use `navId` instead of `navModel`
- [x] add `subTitle`
- [x] add `pageNav` (see `TeamPages`)
- [x] remove back button

note: this shouldn't need to be done behind the feature toggle as it's improving consistency across the board
see e.g. https://github.com/grafana/grafana/pull/53936

### PR DESCRIPTION
**Pull request by lpskdl**
**What this PR does / why we need it**:

- [x] convert to use navId instead of navModel
- [x] add subTitle
- [x] add pageNav (see TeamPages)
- [x]  remove back button
- [x] adjusted paddings

### main topnav off
main_topnav_off

### main topnav on
main_topnav_on
n

### branch topnav off
branch_topnav_off

### branch topnav on
branch_topnav_on

**Which issue(s) this PR fixes**:

Fixes #53967 

**Special notes for your reviewer**:
- I have to add `height="auto"` in `HorizontalGroup` component to fix the display when `topnav` is toggle is on
- We could check the behaviour of TeamPages as a reference 
- @grafana/docs-squad , I would like to ask if you if the subtitle copy is fine.

### CODE REVIEW

**Comment by torkelo** [comment]
Dam, something is not 100% right, when the feature toggle is off it should get page like Team edit or data source edit

Screenshot 2022-08-25 at 09 59 23

Right now when the feature is off there is no page title at all, so you don't really know what service account you are on. 
Screenshot 2022-08-25 at 09 58 23

I think the reason for this is that the service account item page does not have any children (just single page), where team page and data sources edit page have sub pages (tabs) this causes the old Page component to show the item page layout

**Comment by torkelo** [comment]
Pushed a change so that the old Page component always uses PageNav for header even when there are no children. Had to update the admin user page so it sets the breadcrumbs, for the old PageHeader component the thing that makes it show a breadcrumb in page title is the breadcrumbs array. 

Screenshot 2022-08-25 at 10 15 12

Screenshot 2022-08-25 at 10 14 14

**Comment by torkelo** [comment]
@lpskdl https://github.com/grafana/grafana/pull/54018/  looks like it's not merged into this PR, I synced with main so I could update the orgs item page as well

**Comment by lpskdl** [comment]
Hi @torkelo , thanks a lot for checking and fixing the issue on the `Page` component.

**Comment by lpskdl** [comment]
Hi @torkelo , thanks a lot for for fixing the issues and additional changes.  I've tested all related changes and it works fine.

**Review by torkelo — APPROVED** [review]

**Pull request merged**
