### PR TITLE
InspectDataTab: Use templateSrv.replace with getProcessedData

### PR DESCRIPTION
**Pull request by kaydelaney**
Fixes an issue where internal links weren't being interpolated with template var values.

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
Works as expected!

**Review by axelavargas — COMMENTED** [review]
Hey @kaydelaney , checking the code looks good, but I am really curious to learn why it was working before 🙈 (or even, was it working at all?). 

I haven't noticed any recent changes in this function, so I'm wondering how we were getting interpolated variables before?

**Comment by kaydelaney** [comment]
Hmm, actually, I'm not sure if it was ever working 😢

**Review by ivanortegaalba — APPROVED** [review]
💯

**Review by axelavargas — APPROVED** [review]

**Pull request merged**
