### PR TITLE
Explore: Fixed default data source loading

### LINKED ISSUE #37058: Default datasource shows "-- Mixed --" in Explore UI
Recording 7-21-21 at 3 25 39 PM

**What happened**: On an instance with multiple datasources, including a default one - when selecting a datasource in the Explore UI, and then re-opening the Explore UI, the selected datasource is "-- Mixed --".

**What you expected to happen**: The loaded default datasource should be the one set to be default. 

**How to reproduce it (as minimally and precisely as possible)**: 
1. Define multiple datasources including one default.
2. Open Grafana Explore and select a specific datasource
3. Close the browser tab
4. Reopen Grafana and navigate to Explore
5. Selected datasource is now "-- Mixed --"

**Anything else we need to know?**: 

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: Happens with all types of DSs
- OS Grafana is installed on: Ubuntu/Docker
- User OS & Browser: macOS, Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by assafdayan**
**What this PR does / why we need it**: Bugfix

**Which issue(s) this PR fixes**: #37058

Fixes #37058

**Special notes for your reviewer**: This fixes a bug that was reported after upgrading from 7.5.0 to 7.5.7.
To verify the fix I have tested various versions of Grafana via Docker and made sure this fix is robust. I'm not a React/TS developer or a longtime contributor to Grafana, so I am unsure how to automate testing for this. I have not seen an accompanying test suite next to `public/app/features/explore/ExploreToolbar.tsx`.

If this is acceptable as-is - great. If further additions are needed, please advise on the next steps.

### CODE REVIEW

**Comment by assafdayan** [comment]
The bug was introduced in [this PR](https://github.com/grafana/grafana/pull/32992) (v7.5.5): 
In [public/app/features/explore/state/utils.ts](public/app/features/explore/state/utils.ts):L88 the stored datasource is saved with its UID, instead of name. My PR fixes the part that restores this stored info, by making it expect to load a UID and not a name.

**Comment by aocenas** [comment]
@assafdayan thanks for the contribution but something still seems off. Right now on main branch, only way I can repro this is if I select the internal `--Grafana--` data source and then open Explore in new tab.

With this fix this does not happen but then I cannot select the `--Grafana--` data source anymore. So I think there is some combination of some data sources having issue with this fix.


https://user-images.githubusercontent.com/1014802/126714627-ccb5d64e-bdee-4aea-8ce7-9934b5e05a84.mp4

**Comment by assafdayan** [comment]
Hey @aocenas, thanks for taking a look. Sorry for my tardiness on this one.
I merged my PR into the main branch but did not experience what you posted above. Could you share your data srource configuration?

Here's what I'm getting:
Recording 8-19-21 at 6 06 14 PM

**Comment by aocenas** [comment]
Hey @assafdayan, sorry for really late reply, I missed this after my vacation. Yeah if I merge with main it works, so yeah this looks good. I pushed the merge commit to check if tests are still ok. In the future probably also just push the merge commit, should make it less likely for people to get different results.

But again thank you very much for the contribution and sorry for the delay on this.

**Review by aocenas — APPROVED** [review]

**Pull request merged**
