### PR TITLE
LDAP: move ldap modules to infra folder

### PR DESCRIPTION
**Pull request by markelog**
Since those modules do not defined as services, it feels more
correct to place them in `infra` folder

### CODE REVIEW

**Comment by bergquist** [comment]
I dont think ldap belongs in the infra package. 

It should only be called by the login code. I think the infra package should be for code that have multiple callers. Ex logs, metrics, cache.

**Comment by markelog** [comment]
If not there where do you think more appropriate place to put it? Since, strictly speaking those modules are not services

> It should only be called by the login code.

Before it was like that yes, but now it's used from three places - middleware, login and sync

**Comment by bergquist** [comment]
I think `pkg/login/ldap` makes more sense.

**Comment by markelog** [comment]
> I think pkg/login/ldap makes more sense.

The ldap module is now used by ldap sync and it seems that logic has no connection with `login`? After all refactorings LDAP module deals now only with LDAP resource, at least that was my intention

**Comment by torkelo** [comment]
Then maybe it makes more sense to have all ldap things under pkg/services/ldap ?

**Comment by markelog** [comment]
Yeah! That's why I initially moved it there in the first place, but `ldap` doesn't register itself in DI. Doesn't have this `RegisterService` structure, no `Init`/`Run` doesn't have their own logger etc. 

It's just a lib basically used by several different modules, it seemed to fit `infra` definition, but I guess I misinterpreted something?

**Comment by xlson** [comment]
`pkg/services/ldap` seems like a good place to put it.

infra is for more generic code that is used by a lot of different modules that doesn't necessarily have anything in common. The modules that use ldap will also have some kind of user-management/login scenario in common with each other. While any code in Grafana could use the logging or cache libraries.

**Comment by markelog** [comment]
We had a meeting about it and decided that we need a bit more documentation with explanation of the file structure in more detail.

Right now it can stay where it is

**Pull request closed without merging**
