### PR TITLE
Alerting: Move slow queries in the scheduler to another goroutine

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What this PR does / why we need it**:

This commit moves retrieving alert rules from the database out of `ruleEvaluationLoop` and to another goroutine. This fixes an issue where querying 100s or more alert rules can cause each tick in `ruleEvaluationLoop` to take longer than the tick interval, such that the scheduler cannot keep up with the rate of ticks.

**Which issue(s) this PR fixes**:

#43031

### CODE REVIEW

**Review by yuri-tceretian — COMMENTED** [review]
I agree that the current approach is not effective when access to the database is slow. However, I am pretty sure that even fetching 50k rules would not take that much time (10s) to make the ticker drift. We need strong evidence that it happens because of the call to database.

Regarding the proposed implementation, although it solves the potential problem (which we do not have any proof of existence) the approach is also not effective as we basically duplicate data in memory. One copy is _permanently_ stored in the new `alertRules` field, and another copy is stored in the context of ruleEvaluation. ~In cloud we have customers that already run at 5Gb with 10k rules.~ (upd: wrong interpretation of a metric, it was 100 that produces 10k instances)

I think that more effective approach would be:
1. fetch only rules that were updated since the last check. Considering the fact that rules are updated rarely, this operation will be very fast and almost independent on the number of rules that needs to be fetched.
1.1 To properly handle alert deletion in HA mode we will need to implement soft-delete and then GC every N minutes. In non-HA mode the rule is deleted via the API request.

2. If after that we still want to make fetching outside the rule update loop, then instead of caching rules we can maintain a channel between rule update routine and fetching routine. This will make the rule lifetime much shorter and allow us to avoid storing duplicates in memory.

**Comment by gerobinson** [comment]
I've created https://github.com/grafana/mimir/pull/906 so we can better understand how slow queries are in the scheduler. I can re-open this PR at a later time if we still want to move the queries to another goroutine.

**Comment by gerobinson** [comment]
I've created https://github.com/grafana/grafana/pull/44602 so we can better understand how slow queries are in the scheduler. I can re-open this PR at a later time if we still want to move the queries to another goroutine.

**Comment by gerobinson** [comment]
I've created #44602 so we can better understand if slow queries are an issue in the scheduler. I can re-open this PR at a later time if we still want to move the queries to another goroutine.

**Comment by gerobinson** [comment]
I've created #44602 so we can better understand if slow queries are an issue in the scheduler. I can re-open this PR at a later time if we still want to move the queries to another goroutine.

**Pull request closed without merging**
