### PR TITLE
DashboardSchema: Remove some old panel types

### PR DESCRIPTION
**Pull request by torkelo**
Removes the old angular GraphPanel and Heatmap panel from the schema as it just causes bad typescript errors (they where missing id property so `dashboard.panels(p => p.id === 2)`  causes typescript error that id property does not exist on panel (it does). 

Don't think we need these old panel types here, we don't use the schema to validate anyway, only for code builders and there we should not support / encourage use of these old angular panels.

### CODE REVIEW

**Review by K-Phoen — APPROVED** [review]
Our new code builders ignore these panel types, so not having them in the schema at all works well for us :+1:

**Review by dprokop — APPROVED** [review]
🙏 

@Duologic - will this change have any effect on grafonnet?

**Comment by malcolmholmes** [comment]
As @K-Phoen says, not needed. Thinking about validation, I was about to ask whether we could re-add these if needed when implementing validation at some arbitrary point in the future, when I found myself asking: would these panels even be considered valid? In which case, I see no issue removing them.

Regarding Grafonnet, I can't see the GraphPanel (looking [here](https://github.com/grafana/grafonnet/tree/main/gen/grafonnet-v10.0.0/clean/panel). I do see a HeatMap, but I assume [this](https://github.com/grafana/grafonnet/blob/main/gen/grafonnet-v10.0.0/clean/panel/heatmap.libsonnet) is the new one?

**Comment by Duologic** [comment]
They are also ignored in Grafonnet.

**Pull request merged**
