### PR TITLE
Auth: expose testing API

### PR DESCRIPTION
**Pull request by markelog**
That would simplify testing other libraries that has this one as a dependency

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
What are those other libraries, can you include examples and or code examples of libraries/tests that would use this instead of the `FakeUserAuthTokenService`?

**Comment by markelog** [comment]
@marefr I would like to used over here - https://github.com/grafana/grafana-enterprise/pull/105/files#diff-221a3da85f7f87860ac168a2a7eb2179R61.

mmm, maybe there is better way to do it with `FakeUserAuthTokenService`?

**Comment by marefr** [comment]
So if I understand correctly the referenced tests in question you want to test calls cleanup of auth tokens for a user? If you only need to verify that a certain method was expected to be called and was called the `FakeUserAuthTokenService` should fit perfect I think.

**Comment by markelog** [comment]
ldapsync expects a real auth service, so not sure how can I substitute it with the fake struct 

Regards,
Oleg

**Comment by marefr** [comment]
You want to use/inject an AuthTokenService interface instead of struct pointer, see http server for an example: https://github.com/grafana/grafana/blob/master/pkg/api/http_server.go#L66

**Comment by markelog** [comment]
Why would model be defined as a service in DI? A bit confusing to me?

**Comment by markelog** [comment]
Updated

**Comment by marefr** [comment]
> A bit confusing to me - why would model be defined as a service in DI?

I can understand that it's seems confusing. This change was made in #15239 and https://github.com/grafana/grafana/pull/15239/commits/8678620730b26dfa8a07bd0f01d9345d6b266ffd. 

To give some background, we had some issues with circular dependencies and we didn't want to expose internal fields on structs outside auth package. The solution we came up with was to create user token contracts in model package primaryily as the public contract for the api and middleware packages and used for DI in api package and provided to initiate middlewares. 

Our first thought was to add the user token contracts to the api package, but since both api and middleware packages needs/use this we got a circular dependency. The most straigtforward way was to add it to the models package. Make sense?

> Updated

Had a look at that and that could probably work. I think you can do a similar thing as we did with the user token contracts in model package. If you add a new contract in your package where your service lives and then inject that like this:

```go
package <your service package>

type UserTokenBatchRevokeServce interface
  BatchRevokeAllUserTokens(ctx context.Context, userIds []int64) error
}

type <your service> struct {
  UserTokenBatchRevokingService     UserTokenBatchRevokeService    `inject:""`
}
``` 

By doing this you've basically removed any reference to the auth package and write a simple stub of your `UserTokenBatchRevokeServce` in tests.

What do you think?

**Comment by markelog** [comment]
> The most straigtforward way was to add it to the models package. Make sense?

Yeah, now it does, heh, I wonder if there is a better way tho

> What do you think?

Yeah, makes sense! My only concern that it might create some duplication between the packages. 
Do you want me to do it specifically like that? Or we can leave as is? It seems like both methods are valid, right?

**Comment by marefr** [comment]
Think you need to change it to inject an interface to be able to switch the implementation during tests, but if not I guess this change should be fine.

**Comment by markelog** [comment]
Me and @marefr talked in slack and decided to go with the original commit for now

**Comment by xlson** [comment]
We'll go with using an interface for now. Might revisit this in the future if/when we need the mock.

**Pull request closed without merging**
