### PR TITLE
SQL Datasources: Make QueryEditor lazy loaded

### PR DESCRIPTION
**Pull request by jackw**
**What is this feature?**

This PR makes the QueryEditor that lives in `@grafana/sql` load only when it needs to be rendered.

**Why do we need this feature?**

To reduce the amount of JS we serve when loading a dashboard.

**Who is this feature for?**

Grafana Users

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by zoltanbedi — APPROVED** [review]
LGTM, thanks @jackw

**Comment by jackw** [comment]
@zoltanbedi thanks for the review! I can't find any test credentials easily for the sql editors to fully test but from clicking around [this dashboard in the ephemeral instance](https://ephemeral1511182196179jackw.grafana-dev.net/d/ja9klvh/sql-test?orgId=1&from=now-6h&to=now&timezone=browser) everything loads as I expect.

Are you happy if we merge this or would you like to do further testing first?

**Comment by zoltanbedi** [comment]
@jackw I also clicked around and it seems fine from my side. :shipit:

**Pull request merged**
