### PR TITLE
Jaeger: Extract inline CSS into getStyles

### PR DESCRIPTION
**Pull request by CrypticSignal**
**What this PR does**:
This PR removes inline CSS and instead makes use of a `getStyles` function to be consistent with other parts of the codebase.

### CODE REVIEW

**Review by joey-grafana — COMMENTED** [review]
Can we also extract the `padding: theme.spacing(2)`?

Note: when enterprise fails - that usually means you need to pull the latest code from main into your branch.

**Comment by CrypticSignal** [comment]
> Can we also extract the padding: theme.spacing(2)?

Done! How does [this](https://github.com/grafana/grafana/pull/53385/commits/037f682c8c4eacf220fca4976bd9538a87c44cee) look?

**Comment by joey-grafana** [comment]
Two things that need to be done here:

1. We need enterprise to be passing. My last comment specifies how to fix this. Note: we want the enterprise-ok label in our list of labels.
2. Can you review every line of code you have changed again and make sure you are happy that it's ready for review? I think there is something that needs to be fixed.

**Comment by CrypticSignal** [comment]
@joey-grafana 
> We need enterprise to be passing. My last comment specifies how to fix this. Note: we want the enterprise-ok label in our list of labels.

If I understood correctly, a simple `git pull` will suffice and it seems like I can do this whether I'm on the main branch or on this branch. I have also added the **enterprise-ok** label. I'm not sure if I should remove the **enterprise-failed** label.
> Can you review every line of code you have changed again and make sure you are happy that it's ready for review? I think there is something that needs to be fixed.

Good spot. Fixed in commit [8cc41c9](https://github.com/grafana/grafana/pull/53385/commits/8cc41c97657b4d5e7d4de45681934ee95160358a).

**Comment by CrypticSignal** [comment]
> Note: when enterprise fails - that usually means you need to pull the latest code from main into your branch.

I'm not sure how to do this. From some Googling, it seems like the process is as follows:
1. Switch to the main branch.
2. `git pull --rebase`
3. Switch to my branch.
4. `git rebase main`

Can you confirm whether these are the steps that I should take?

> Note: we want the enterprise-ok label in our list of labels.

I added the **enterprise-ok** label, but I'm not sure if I should've removed the **enterprise-failed** label before doing so?

> Can you review every line of code you have changed again and make sure you are happy that it's ready for review? I think there is something that needs to be fixed.

Good spot. Fixed in commit [8cc41c9](https://github.com/grafana/grafana/pull/53385/commits/8cc41c97657b4d5e7d4de45681934ee95160358a).

**Comment by joey-grafana** [comment]
It's 
1. git checkout main
2. git pull
3. git checkout <my-feature-branch>
4. git merge main

We don't add/remove the enterprise label ourselves. We merge with main and the PR will be updated when the enterprise tests finish running.

I'll discuss these ideas with you in our 1:1 this morning :)

**Review by joey-grafana — APPROVED** [review]
LGTM 👍 

PS: don't forget to add your project to the PR so it is tracked on our board :)

**Pull request merged**
