### PR TITLE
Alerting: Update grafana/alerting to 4f09f51

### PR DESCRIPTION
**Pull request by grobinson-grafana**
**What is this feature?**

This pull request updates [`grafana/alerting`](https://github.com/grafana/alerting) to [`4f09f51`](https://github.com/grafana/alerting/commit/4f09f516596bff4fffc31d8577338dc8e636133a) to fix https://github.com/prometheus/alertmanager/pull/3278.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by JacobsonMT** [comment]
Should we go straight to https://github.com/grafana/alerting/commit/5828396a8aace92ae309be945a27ed019f1e723d?

**Comment by grobinson-grafana** [comment]
> Should we go straight to [grafana/alerting@5828396](https://github.com/grafana/alerting/commit/5828396a8aace92ae309be945a27ed019f1e723d)?

I can just make a second PR. I want to make sure we have an "audit log" that makes it simple to show on GitHub that we got this fix from upstream into Grafana - if that makes sense?

**Comment by gotjosh** [comment]
> I can just make a second PR.

Agree with Matt here, not sure I see a reason for a second PR when https://github.com/grafana/alerting/commit/5828396a8aace92ae309be945a27ed019f1e723d is fairly trivial.

**Comment by grobinson-grafana** [comment]
Perhaps I didn't explain the reasoning well the first time around 🙁 

The reason I wanted to create two separate PRs is so we can have a 1:1 relationship between the issue and the fix. 

```
issue1 -> fix1
issue2 -> fix2
``` 

If we do both in the same PR we have this:

```
issue1 -> fix1and2
issue2 -> fix1and2
```

I wanted to have the former so if or when we go back and look at the issues it's super clear to see which PRs fixed it, rather than having a shared PR that fixes a number of different bugs all at the same time.

**Review by JacobsonMT — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
Thanks! I had to rebase main to fix a conflict in `go.sum`.

**Pull request merged**
