### PR TITLE
bump grabpl version to 0.5.36

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by marefr — CHANGES_REQUESTED** [review]
Comparing with https://github.com/grafana/grafana/pull/30486/files that was the last one updating the version there should be a couple of shell files that needs update as well.

**Comment by ying-jeanne** [comment]
> Comparing with https://github.com/grafana/grafana/pull/30486/files that was the last one updating the version there should be a couple of shell files that needs update as well.

already did, packages/grafana-toolkit/docker/grafana-plugin-ci-alpine/scripts/deploy.sh this is the shell file.

**Comment by marefr** [comment]
@ying-jeanne yes, but also these ,see the files changed in the PR i referenced:
- packages/grafana-toolkit/docker/grafana-plugin-ci-e2e/scripts/deploy.sh 
- packages/grafana-toolkit/docker/grafana-plugin-ci/scripts/deploy.sh

**Comment by ying-jeanne** [comment]
> @ying-jeanne yes, but also these ,see the files changed in the PR i referenced:
> 
> * packages/grafana-toolkit/docker/grafana-plugin-ci-e2e/scripts/deploy.sh
> * packages/grafana-toolkit/docker/grafana-plugin-ci/scripts/deploy.sh

saw it, you were really quick :)

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
