### PR TITLE
OAuth: Introduce new setting for configuring max age of OAuth state cookie

### PR DESCRIPTION
**Pull request by rtrompier**
When using oauth2 authentication with multifactor, the 60s delay may be too short

### CODE REVIEW

**Comment by papagian** [comment]
Thank you for contributing!
Instead of a new hardcoded value would you like to introduce a new setting `oauth_state_cookie_max_age` that defaults to `60`?

For doing so, in addition to this modification when writing the OAuth state cookie, you need to update appropriately [defaults.ini](https://github.com/grafana/grafana/blob/master/conf/defaults.ini), [samples.ini](https://github.com/grafana/grafana/blob/master/conf/sample.ini) and the [docs](https://github.com/grafana/grafana/blob/master/docs/sources/installation/configuration.md).

**Comment by rtrompier** [comment]
Hi @papagian,

I work for the Geneva Hospitals, and we are currently using grafana for COVID19 crisis monitoring. Would it be possible to merge in the state although I agree with you that it would be more elegant via a configuration file ? 

Thank you very much ;)

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by papagian** [comment]
@rtrompier 
I have introduced the new setting. You can override the default behaviour by setting `auth.oauth_state_cookie_max_age` to `500` in your grafana configuration or alternatively by using the environmental variable `GF_AUTH_OAUTH_STATE_COOKIE_MAX_AGE=500`.

Stay strong and let me know if you need additional help.

**Comment by rtrompier** [comment]
Thank you so much guys !
Really appreciate your help.

**Pull request merged**
