### PR TITLE
Included LIMIT, SLIMIT and ORDER BY time for influxdb #6065

### LINKED ISSUE #6065: influxdb query builder support for ORDER BY and LIMIT
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- What datasource are you using?
  influxdb

Would be nice if the query builder supported ORDER BY and LIMIT.

When displaying a table of data these modifiers are nice to have.
Limit is a must have when viewing a year worth of logs.

```
SELECT "request_type" as "type","request","request_status","ip","city" 
FROM "nginx_access" WHERE $timeFilter AND host =~ /p01/ 
ORDER BY time DESC LIMIT 100
```

### PR DESCRIPTION
**Pull request by thuck**
Fixes #6065

### CODE REVIEW

**Comment by thuck** [comment]
This should also close #7232

**Comment by daniellee** [comment]
Feedback:

- For a table panel, the default sorting on the Time column is descending so the order by clause has no effect unless you disable the table sorting. It does work well together with the LIMIT if you want to get the  top x values. What's the use case for order by? Is the default table panel sorting a problem for the average Influxdb user?
- LIMIT and SLIMIT seem to work fine
- The query editor changes look fine except for one thing. Can you change the `ORDER BY time` to look the same as the group by. The label would be `ORDER BY` and `time` would be a non-editable query part. Like the image below but change group by to order by.

image

**Comment by thuck** [comment]
The order by time is applied in the query before the LIMIT, so the effect is basically X first points or X last  points in time.So if you don't have this implemented LIMIT will only apply for the X first points since the default for influx is ASC, so if you want the most recent data to be used with LIMIT you must use order by time desc.
Sure; I'll check the ORDER BY part on the web interface.

**Comment by daniellee** [comment]
If you fix the ux for the ORDER BY then I think this is good to merge. Nice work!

**Comment by thuck** [comment]
It should be fine now, let me know if there is any other changed necessary.

**Comment by daniellee** [comment]
Thanks again @thuck Fourth PR this week! Great to get TOPN functionality for InfluxDB in Grafana.

**Comment by torkelo** [comment]
inclined to revert this change. Just messes up the editor so much with options that you don't use 99.99% of the time. Maybe make the raw query editor mode better would make more sense?

**Comment by thuck** [comment]
@torkelo Maybe you can keep it as it is, considering that influxdb will change their [query language](https://speakerdeck.com/pauldix/time-series-data-models-and-the-future-of-influxdbs-query-language) again not sure if put more effort on the current one is a good investment of time.
Maybe this version of the language should be put in "maintenance" and no more changes that are not bug fixes should be made?
Also I don't think it messes a lot of with the editor, but I get you point of reducing the visual "clunk" of the visual editor.

**Pull request merged**
