### PR TITLE
InfluxDB: Fix sql query generation by adding quotes around the identifiers

### LINKED ISSUE #83717: InfluxDB: Builder-generated SQL identifiers should be double-quoted
### What happened?

A user used the InfluxDB SQL builder to query the `TestMeasurement` table in InfluxDB. The builder generated the following query:

```sql
SELECT AWS, time FROM iox.TestMeasurement WHERE time >= $__timeFrom AND time <= $__timeTo
```

Which, when run, returned the following error:

```
flightsql: rpc error: code = InvalidArgument desc = Error while planning query: Error during planning: table 'public.iox.testmeasurement' not found
```

Notice the case change in the table name (`iox.testmeasurement` vs `iox.TestMeasurment`). In InfluxDB's SQL implementation, identifiers (table and column names) that are not double-quoted are parsed as lowercase.

To prevent casing differences, identifiers in queries generated from the query builder should always be double-quoted:

```sql
SELECT "AWS", "time" FROM "iox.TestMeasurement" WHERE "time" >= $__timeFrom AND "time" <= $__timeTo
```

### What did you expect to happen?

The generated query should run successfully. This should be fixed by double-quoting SQL identifiers in builder-generated queries.

### Did this work before?

This bug has existed since SQL support was introduced to the InfluxDB datasource.

### How do we reproduce it?

1. Create a table/measurement in InfluxDB Cloud Serverless with both upper- and lower-case characters in the name.
2. Use the InfluxDB SQL query builder in Grafana and select the mixed-cased named table/measurement from the **Table** dropdown.
3. Select other columns to query.
4. Run the query.

Because the table name isn't double-quoted in the generated query, the case doesn't match the case of the table in InfluxDB and the query will err.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.3.3
OS: Unsure
Browser: Unsure

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

### PR DESCRIPTION
**Pull request by itsmylife**
**What is this feature?**

In general, it works without quotes too but when you have a capital letter in your identifiers then it gets broken. To handle that and match with the documentation we add quotes around the identifiers. See the documentation https://docs.influxdata.com/influxdb/cloud-serverless/reference/sql/select/

**Why do we need this feature?**

for better querying experience

**Who is this feature for?**

InfluxDB SQL users

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/83717

**Special notes for your reviewer:**

### CODE REVIEW

**Review by bohandley — COMMENTED** [review]
I can confirm the quotes are now added to the table with this fix but I am not sure that this is something we should fix and instead Influx should fix this.

I am confused as to why adding the iox prefix causes this error below. It looks like whenever a user adds the table with quotes like `"iox.mTable"`, influx then makes a query using `'public.iox.iox.mTable'`.  Somehow adding the quotes to the table with the dataset(iox) appends the dataset twice.

```
flightsql: rpc error: code = InvalidArgument desc = Error while planning query: Error during planning: table 'public.iox.iox.mTable' not found
```

Screenshot 2024-03-04 at 10 08 00 AM

**Comment by itsmylife** [comment]
@bohandley According to the documentation, the quotes are needed. Please see https://docs.influxdata.com/influxdb/cloud-serverless/reference/sql/select/

`public` is table catalog and `iox` is table schema
See: https://docs.influxdata.com/influxdb/cloud-serverless/query-data/sql/explore-schema/#list-columns-in-a-measurement
So those are normal.

**Comment by bohandley** [comment]
> public is table catalog and iox is table schema
See: https://docs.influxdata.com/influxdb/cloud-serverless/query-data/sql/explore-schema/#list-columns-in-a-measurement
So those are normal.

Yes, public iox is normal, but doubling "iox" creates an error

This is normal
'public.iox.mTable'

This causes the error
'public.iox.iox.mTable'

The double "iox" only occurs when the table is wrapped in quotes with "iox" appended in the query.

**Comment by itsmylife** [comment]
@bohandley yes you are right. I missed that part. It turned out my `devenv` was broken :)
I fixed both. It should be fine now.

**Review by bohandley — APPROVED** [review]
I think this strategy will work! Removing the "iox.mTable" in favor of just using "mTable" does query successfully.

Screenshot 2024-03-04 at 11 20 48 AM

**Pull request merged**
