### PR TITLE
Document Update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
"an SQLite" to "a SQLite"

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by oddlittlebird — CHANGES_REQUESTED** [review]
If you could fix the capitalization in that sentence, that would be great and I would accept that edit.

However, the "an" is correct. This is because when you say "SQL" it starts with a vowel sound ("ess"), thus it calls for the "an" rather than "a." I know, English is weird.

**Comment by aknuds1** [comment]
@oddlittlebird Actually, "a SQLite" is correct, since it's normally pronounced "sequelite". I think everyone internally pronounces it as such at least, see [Stack Exchange](https://english.stackexchange.com/a/431330/399466) answer on the subject.

**Comment by oddlittlebird** [comment]
> @oddlittlebird Actually, "a SQLite" is correct, since it's normally pronounced "sequelite". I think everyone internally pronounces it as such at least (although an alternative pronunciation is "ess-queue-elite", see [Stack Exchange](https://english.stackexchange.com/a/431330/399466) answer on the subject.

Fair enough. I'll except the change, then. 

@NiteshKoushik, do you want to fix the capitalization as well?

**Comment by NiteshKoushik** [comment]
Changes made - capitalization : "sqlite" to "SQLite"

**Comment by NiteshKoushik** [comment]
Hello @oddlittlebird, Changes made as per the suggestion.

**Comment by NiteshKoushik** [comment]
Hello @oddlittlebird, Please let me know incase of any changes required.

**Comment by oddlittlebird** [comment]
Oh, I didn't realize you were ready. Usually people re-request a review when they are ready for us to look again. I will give it a look now, but here's how to do that in the future.
image

**Review by oddlittlebird — APPROVED** [review]
Looks good! Thanks for contributing to the docs!

**Pull request merged**
