### PR TITLE
fix: remove margin from icon button

### LINKED ISSUE #70348: Grafana/UI: IconButton has right margin
### 
# What went wrong?

IconButton has a right margin:
https://github.com/grafana/grafana/blob/24502c4c4a2ea95659115834d6937377c22993b3/packages/grafana-ui/src/components/IconButton/IconButton.tsx#L108

I don't think library elements should have margins as it is hard to predict in what layout context will they be used.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

Grafana v10.1.0-pre (cc42242)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by ashutosh-rath02**
**What is this feature?**
Bug-fix: This PR removes margin as raised in the issue mentioned below.
**Which issue(s) does this PR fix?**:

Fixes #70348 

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by Lucif3r-in** [comment]
type/bug

**Comment by Lucif3r-in** [comment]
no-backport

**Comment by JoaoSilvaGrafana** [comment]
Hi @Lucif3r-in , thanks for raising this PR! Unfortunately this change needs a bit more discussion as it might have implications for layouts across grafana. See [this comment](https://github.com/grafana/grafana/issues/70346#issuecomment-1597993792). So we won't be able to merge this PR at the moment...

We might reopen it once we have discussed if this is something we want to do 🙏  but still, thank you for contributing to Grafana!

**Comment by Lucif3r-in** [comment]
> Hi @Lucif3r-in , thanks for raising this PR! Unfortunately this change needs a bit more discussion as it might have implications for layouts across grafana. See [this comment](https://github.com/grafana/grafana/issues/70346#issuecomment-1597993792). So we won't be able to merge this PR at the moment...
> 
> We might reopen it once we have discussed if this is something we want to do 🙏  but still, thank you for contributing to Grafana!

Sure sir, no problem!

**Pull request closed without merging**
