### PR TITLE
support mysql2 connection string

### PR DESCRIPTION
**Pull request by bbodenmiller**
**What this PR does / why we need it**:

Currently if you give Grafana a MySQL connection string in the form `mysql2://user:pass@host` as [cloud foundry does](https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#DATABASE-URL) it just errors out. If you take the connection string given by cloud foundry and just replace `mysql2` with `mysql` it works. The goal here is to allow `mysql2` connection string so cloud foundry database service connection string variable can feed straight to Grafana without string manipulation.

Various proof that `mysql2://...` is a real thing CF does:
* https://stackoverflow.com/questions/35955176/cloud-foundry-rails-4-database-yml
* https://blog.arkency.com/database-url-examples-for-rails-db-connection-strings/
* https://github.com/pwnall/node-parse-database-url/pull/5
* https://mnm.at/markus/2014/06/15/cloud-foundry-environment-notes/
* https://www.altoros.com/blog/how-to-install-jenkins-ci-on-cloud-foundry-for-continuous-delivery/#examples

**Which issue(s) this PR fixes**:

Fixes #

Replaces https://github.com/grafana/grafana/pull/14035

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bbodenmiller** [comment]
Not stale. Waiting for maintainer to merge

**Comment by aknuds1** [comment]
Can you merge with latest Grafana master to fix CI?

**Comment by bbodenmiller** [comment]
@aknuds1 done.

**Comment by aknuds1** [comment]
Thanks!

**Comment by aknuds1** [comment]
Do you have any idea why Cloud Foundry uses the "mysql2" protocol instead of the standard "mysql"? I struggle with finding the reason.

**Comment by aknuds1** [comment]
Is the mysql2 protocol supposed to tell the driver to use the [mysql2](https://github.com/brianmario/mysql2) gem? That's the impression I get, and if I'm right it seems wrong to me to use that MySQL URL towards drivers that don't support it.

**Comment by bbodenmiller** [comment]
@aknuds1 I can't find any documentation on why mysql2 is used vs. mysql. The docs give no such requirement to use a specific library.

> Also, how do you pass the connections string provided by Cloud Foundry to Grafana? Do you e.g. just copy-paste it into Grafana settings?

My run script sets as follows

```
export GF_DATABASE_TYPE=mysql
# drop ?reconnect=true from connection string because Grafana doesn't handle it properly
DATABASE_URL=${DATABASE_URL/?reconnect=true}
export GF_DATABASE_URL=${DATABASE_URL/mysql2/mysql} # replace "mysql2://..." which Grafana doesn't understand in $DATABASE_URL with "mysql://..."
```

**Comment by aknuds1** [comment]
Thanks for clarifying how you use Cloud Foundry's `$DATABASE_URL`. I'm going to close this PR, since I agree with @marefr in #14035. I think the "mysql2" URL scheme is non-standard and used by f.ex. the [mysql2](https://github.com/brianmario/mysql2#sequel) Ruby gem as its protocol in adapters. You can for example read this article on how mysql2 is used by RoR to determine the MySQL adapter to use: https://medium.com/@emersonthis/running-rails-with-mysql-on-heroku-4765df033428.

Translating the mysql2 part in the connection URL from CF can also easily be done before passing it to Grafana.

**Pull request closed without merging**
