### PR TITLE
migrated from dep to go modules

### LINKED ISSUE #16088: Replace `dep` with go modules
Since go modules is happening we should migrate away from `dep` to `go modules`.
In go 1.12 the go modules behavior will be on by default so I think its time we get on the bus.

### PR DESCRIPTION
**Pull request by bergquist**
I've added a short guide in `Contributing.md` about how we can use go mod instead of dep. In Golang 1.12 Go modules will be switch to auto, in 1.13 it will be on by default so I think its time we migrate.

closes https://github.com/grafana/grafana/issues/16088

### CODE REVIEW

**Comment by bergquist** [comment]
That's a lot of changes! Let me look into that before we merge this :)
Dont want to make the same mistake I made with dep.

**Comment by torkelo** [comment]
Why has so many vendored source files changed? does go modules move them or organize them differently? Does not look like it.

**Comment by bergquist** [comment]
I think its because we pointed dep at master in some cases. Not sure. Still need to investigate this.

**Comment by bergquist** [comment]
By default go mod scans all files in the folder so make sure to not have any backend plugins in `data/plugins`

**Comment by bergquist** [comment]
This PR checkout be squashed and cleaned before we merge it

**Comment by daniellee** [comment]
@bergquist What was the difference to this PR: https://github.com/grafana/grafana/pull/15556 Seems very similar.

**Comment by bergquist** [comment]
Just me trying to understand go modules better.

**Comment by xlson** [comment]
Looks good to me. I think we should switch over to modules. I played around with it for a bit and my impression is that it is faster than dep, which I always thought was pretty annoying in that regard. It does not seem to clean away non-go files as nicely as dep did, but tI don't think that's a deal-breaker.

You removed some of those non-go files and they will be added back the next time `go mod vendor` is executed, so might as well do that before squash and merge.

**Comment by bergquist** [comment]
The github UI doesn't handle these many file changes well.
You can view the none vendor changes in the CLI

```bash
git diff master HEAD Makefile
git diff master HEAD CONTRIBUTING.md
git diff master HEAD ./pkg
```

@torkelo @xlson do either of you object to merging this?

**Review by torkelo — APPROVED** [review]
LGTM

**Pull request merged**
