### PR TITLE
Avoid sending empty Slack messages altogether

### PR DESCRIPTION
**Pull request by alexweav**
**What this PR does / why we need it**:

The Slack API does not accept empty messages. Ensure any message sent to Slack is never empty, particularly if it stems from a templating failure.

**Which issue(s) this PR fixes**:

Contributes to #43733 

**Special notes for your reviewer**:

Use a simple sentinel value.
Need to test against other user-controllable fields, e.g. Title. I don't believe title is a required field in Slack, I am verifying this before submit.

### CODE REVIEW

**Comment by alexweav** [comment]
Draft, while I do some final manual testing against a test Slack channel.

**Comment by alexweav** [comment]
Whitespace might also be an issue. Checking for this. Also, the "Title" field.

**Comment by gotjosh** [comment]
Alex and I had an offline discussion regarding this PR - we'll investigate a bit more as we saw what we think it's an inconsistent behaviour in the Slack API vs What was reported.

**Comment by alexweav** [comment]
Closing this for now. From my testing, there isn't a a pressing need to avoid sending empty Slack messages - the Slack API seems to accept them with no issue in every configuration (even though a few unrelated errors are logged in case of template evals). If we find a situation where this is needed, will re-open.

**Pull request closed without merging**
