### PR TITLE
Hide the reset password link if using LDAP Auth

### PR DESCRIPTION
**Pull request by tmonk42**
Addresses #2495 

Should also provide a pattern for disabling password reset for other auth methods.

### CODE REVIEW

**Comment by torkelo** [comment]
please sign CLA, https://cla-assistant.io/grafana/grafana?pullRequest=2570

**Comment by bergquist** [comment]
@tmonk42 please sign the CLA or we have to close this PR.

**Comment by bergquist** [comment]
Closing due to unsigned CLA. :(

**Comment by mflamm** [comment]
Can someone please restart this process :)?

**Pull request closed without merging**
