### PR TITLE
Navigation: Add create icons to expanded menu

### PR DESCRIPTION
**Pull request by ashharrison90**
**What this PR does / why we need it**:

- adds plus icons to create items in the expanded menu

| before | after | 
| --- | --- |
| image | image |
- renames the create alert rule option from `Alert rule` to `New alert rule`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by amy-super** [comment]
@ashharrison90 is it `New alert rule` or `Create alert rule`? We use `New` for dashboard items.

**Comment by amy-super** [comment]
@ashharrison90 I feel that `new` is correct but the screenshot says `create` so I got confused.

**Comment by ashharrison90** [comment]
@amy-super OHHHH sorry, i must have taken a screenshot before i changed it to `New` 😂  it's definitely `New`, i'll update the screenshot

**Review by axelavargas — APPROVED** [review]
👏🏾 code looks good to me!

**Pull request merged**
