### PR TITLE
Template variables: Default to first option if URL does not provide

### LINKED ISSUE #35471: Template Variable Defaults Blanked When Using Data Links Back to Same Dashboard
**What happened**:

When creating a data link to essentially "reset" any change in drop-down variables back to the dashboard defaults (On Dashboard Load) - the dashboard loads correctly (with defaults) - and then immediately blanks out all variables defaults.

**What you expected to happen**:

Not sure why there's an additional refresh of the variables after load that blanks out any defaults. It should not blank out the defaults (on dashboard load).

**How to reproduce it (as minimally and precisely as possible)**:

Dashboard with data link:

That pushes new variables back into the same dashboard:

`/d/${__dashboard.uid}﻿﻿/?var-forecast_day_num=﻿${__data.fields["day_num"]}﻿&var-display_date=${__data.fields.day_start_local}&from=now%2B${__data.fields.day_relative}d%2Fd&to=now%2B${__data.fields.day_relative}d%2Fd&var-interval=1h&${station_name:queryparam}&${tz:queryparam}`

Dashboard presented with new parameters correctly.

Click on the panel link to "reset" back to the dashboard URL without any pushed variables (top Left panel has a panel link):

`URL: /d/${__dashboard.uid}`

Takes me back to the same dashboard as expected and proper... And then a split second later, removes all "on dashboard load" variables to:

Them all being blank. (The variables are in the dropdowns - just the default selection has been wiped out...)

**Anything else we need to know?**:

Rolled back to testing on 7.5.7 and this works as expected.

**Environment**: Linux Docker x64
- Grafana version: 8.0.0 Release - but also tested nightly Grafana v8.1.0-25681pre (f4e9dcd40b)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS - Version 91.0.4472.77 (Official Build) (x86_64) and Safari Version 14.1.1 (16611.2.7.1.4)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by tskarhed**
**Which issue(s) this PR fixes**:

Fixes #35471

**Special notes for your reviewer**:

I'm currently looking at writing tests.

### CODE REVIEW

**Comment by tskarhed** [comment]
Am I missing the reason why the selected option needs to have `""`?

```
 when setOptionFromUrl is dispatched with a custom variable (no refresh property) › and urlValue is undefined then correct actions are dispatched

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

    @@ -2,12 +2,12 @@
        Object {
          "payload": Object {
            "data": Object {
              "option": Object {
                "selected": false,
    -           "text": "",
    -           "value": "",
    +           "text": "A",
    +           "value": "A",
              },
            },
            "id": "0",
            "type": "custom",
          },

      110 |     }
      111 |
    > 112 |     expect(dispatchedActions).toEqual(actions);
          |                               ^
      113 |     return instance;
      114 |   };
      115 |

      at Object.thenDispatchedActionsShouldEqual (public/test/core/redux/reduxTester.ts:112:31)
      at public/app/features/variables/state/setOptionFromUrl.test.ts:37:18
      at step (node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/tslib/tslib.js:124:57)
      at fulfilled (node_modules/tslib/tslib.js:114:62)
```

**Review by ashharrison90 — APPROVED** [review]
code lgtm, but does it solve the problem specified in https://github.com/grafana/grafana/issues/35471#issuecomment-877267450? 

seems the problem stated there is that it's defaulting to the first option instead of the option saved in the json. as far as i can tell, this will also default to the first option? it's definitely better than being blank, but idk if it solves the original problem.

**Comment by tskarhed** [comment]
> code lgtm, but does it solve the problem specified in [#35471 (comment)](https://github.com/grafana/grafana/issues/35471#issuecomment-877267450)?
> 
> seems the problem stated there is that it's defaulting to the first option instead of the option saved in the json. as far as i can tell, this will also default to the first option? it's definitely better than being blank, but idk if it solves the original problem.

You're right. I'm not sure how I would approach that though. Defaulting to the first option seems like a better thing than having it blank.

Maybe merge it like this for now and then come back to it?

**Comment by ashharrison90** [comment]
oh yeah absolutely, it's definitely a step forward 🥳

**Review by hugohaggmark — CHANGES_REQUESTED** [review]
I think we need to find a better solution to the root issue here
https://github.com/grafana/grafana/issues/35471#issuecomment-895809796

**Comment by hugohaggmark** [comment]
Superseeded by #37776

**Pull request closed without merging**
