### PR TITLE
ValueMapping: Fixes issue with regex mappings.

### LINKED ISSUE #41265: Value mappings: selected colors not set correctly when using regex rules
**What happened**:
colors of all values after the first regex mapping rule are set to the color in this first regex rule 

**What you expected to happen**:
colors following the regex rules

**How to reproduce it (as minimally and precisely as possible)**:
I used a default state time line panel in the [play.grafana](https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?from=now-12h&to=now&var-app=backend&var-server=backend_01&var-server=backend_03&var-interval=1h&orgId=1) environment
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: gdev-testdata
- OS Grafana is installed on:?
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

image

### PR DESCRIPTION
**Pull request by mcdee**
This fixes an issue where as soon as a regex was encountered in the value mappings list then getValueMappingResult() would return at the end of its evaluation regardless of whether or not a match was made.

getValueMappingResult() will now only return on a regex if the regex pattern matches the value.

Fixes #41265

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
Thanks @mcdee -- this looks great!

**Comment by torkelo** [comment]
@mcdee this breaks regex value mappings that only set color, will have to revert

**Comment by mcdee** [comment]
> @mcdee this breaks regex value mappings that only set color, will have to revert

Okay, will investigate to see what's going on.

**Comment by mcdee** [comment]
Do you have an issue that provides information on the problem?

**Comment by torkelo** [comment]
@mcdee here is a fix: https://github.com/grafana/grafana/pull/42311

**Comment by mcdee** [comment]
Thanks, sounds like I don't need to do anything then.  Feel free to ping me with any issues you would like me to look at with this bit of the codebase.

**Pull request merged**
