### PR TITLE
Azure Monitor: Support for Azure stack

### LINKED ISSUE #26842: AzureMonitor: support for Azure Stack
**What would you like to be added**:

Support for Azure Monitor queries for an Azure Stack instance.

**Why is this needed**:
This is the last cloud type that the Azure Monitor plugin doesn't support yet (already have support for public Azure, Azure China, Azure Gov and Azure Germany).

### PR DESCRIPTION
**Pull request by daniellee**
Fixes #26842

### CODE REVIEW

**Comment by marefr** [comment]
@daniellee is this ready for review?

**Comment by daniellee** [comment]
@marefr will know today - having problems with the test environment for Azure Stack.

**Comment by marefr** [comment]
@daniellee okay. Is this a blocker for 7.2 beta?

**Comment by daniellee** [comment]
@marefr not a blocker for 7.2 beta.

**Comment by daniellee** [comment]
Waiting on a test environment for Azure Stack - not including it in a milestone until I know more.

**Comment by daniellee** [comment]
Closing this until we get a test environment.

**Pull request closed without merging**
