### PR TITLE
Tracing: Support configuring Jaeger client from environment

### LINKED ISSUE #21102: Tracing: Support configuring Jaeger client via environment variables
**What would you like to be added**:

I'd like it to be possible to set the standard `JAEGER_*` environment variables to configure the Jaeger client, rather than the `tracing.jaeger` configuration elements. See the bottom of https://www.jaegertracing.io/docs/1.15/client-features/ for the list of variables that the Jaeger Go client supports.

**Why is this needed**:

This would help Grafana's Jaeger tracing support to be configurable in a more conventional fashion.

(PR incoming)

### PR DESCRIPTION
**Pull request by hairyhenderson**
**What this PR does / why we need it**:

It's conventional for Jaeger clients to support the standard `JAEGER_*` environment variables (see the list at the end of https://www.jaegertracing.io/docs/1.15/client-features/).

I think it would be worthwhile to be able to use `JAEGER_AGENT_HOST`/etc to configure the Jaeger client. I've implemented this as additive - the existing `tracing.jaeger` configuration will be applied first, then any environment variables will override.

**Which issue(s) this PR fixes**:

Fixes #21102

**Special notes for your reviewer**:

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by aknuds1** [comment]
@marefr What do you think, is this something we want?

**Comment by hairyhenderson** [comment]
Maybe just to add another reason why this would be useful/important to me - right now the `tracing.jaeger.address` field is assumed to be a `host:port`, which doesn't match how `JAEGER_AGENT_HOST` works.

In our Kubernetes clusters, we deploy Jaeger Agents as DaemonSets, using the host's network, and then we use the `env.valueFrom` field to set `JAEGER_AGENT_HOST` in the container spec to automatically get the host IP (which is otherwise undiscoverable) at scheduling time:

```yaml
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
```

I've tried to do the same with `GF_TRACING_JAEGER_ADDRESS`, but this fails since no port number is present.

Rather than changing how that particular field works, I think it'd be ideal to support the standard Jaeger client environment variables _anyway_.

Hope this makes sense, and can be merged soon!

**Comment by marefr** [comment]
@aknuds1 I have understood that it makes sense to configure Jaeger client this way and think we should support that. So please go ahead and review this. There are a Jaeger docker block available that you should be able to test this out. 

Would be good to document tracing.jaeger in https://grafana.com/docs/grafana/latest/installation/configuration/ and include note regarding Jaeger client environment variables. Could be sort of a copy of defaults.ini to start with.

**Comment by aknuds1** [comment]
I've tested this and it looks good, thanks! Just making some adjustments before merging.

**Review by aknuds1 — APPROVED** [review]
LGTM, thanks!

**Comment by hairyhenderson** [comment]
> Would be good to document tracing.jaeger in https://grafana.com/docs/grafana/latest/installation/configuration/ and include note regarding Jaeger client environment variables. Could be sort of a copy of defaults.ini to start with.

Good point @marefr - I thought about updating docs when I wrote this PR but couldn't find any existing ones so decided not to complicate things too much in this one. I can work on a followup for docs if you'd like.

**Comment by hairyhenderson** [comment]
@marefr I've added some documentation in https://github.com/grafana/grafana/pull/21181 - PTAL! 😉

**Comment by aknuds1** [comment]
@hairyhenderson thanks, I can have a look at this tomorrow. I already made a note to myself, to try to update the docs.

**Pull request merged**
