### PR TITLE
Dashboards: Fixes timing issue when restoring scroll position

### PR DESCRIPTION
**Pull request by torkelo**
We had some flaky e2e tests due to the timing issue (setTimeout) when restoring the scroll position. 

@Sergej-Vlasov explored one solution in https://github.com/grafana/grafana/pull/92326 but I think this looks a bit simpler.

We check if the scroll position we want to restore is possible and wait until the next animation frame and check again (with max tries set to 10). This way it should be as fast as possible (without noticeable flickering) while on slower CI hardware it can take longer and it will still work. 

The benefit of switching to controlling scrolling via document.documentElement vs window is we can now use the same wrapper for both bodyScolling = true and false.

### CODE REVIEW

**Review by Sergej-Vlasov — APPROVED** [review]
LGTM! This indeed looks simpler than observer approach. Tested with 20x cpu slowdown and it consistently restores scroll position. 

Note: Noticed that when we exit edit mode and discard changes scroll position is reset to top of the page.

**Comment by torkelo** [comment]
> Note: Noticed that when we exit edit mode and discard changes scroll position is reset to top of the page.

@Sergej-Vlasov that is strange, does that not mean it does not work for you? I can't replicate that, discarding change or hitting "back to dashboard" result in the same behavior (restoring position), even on 20x slow down

**Comment by Sergej-Vlasov** [comment]
> > Note: Noticed that when we exit edit mode and discard changes scroll position is reset to top of the page.
> 
> @Sergej-Vlasov that is strange, does that not mean it does not work for you? I can't replicate that, discarding change or hitting "back to dashboard" result in the same behavior (restoring position), even on 20x slow down

@torkelo  this is the example:

https://github.com/user-attachments/assets/5ddc0faa-592c-42da-b0ca-67eb9732b1e1

**Comment by torkelo** [comment]
@Sergej-Vlasov ah, you mean exit dashboard edit (thought you meant panel edit). 

have not added any code to remember the position for this flow, did a quick test, looks a bit tricky to add, needs something new

**Pull request merged**
