### PR TITLE
Versionbump go-ldap for nested LDAP group support

### PR DESCRIPTION
**Pull request by dfwarden**
This bumps the version of go-ldap/ldap to [v2.2.1](https://github.com/go-ldap/ldap/releases/tag/v2.2.1) which includes support for nested/recursive LDAP filters which can be used in group_search_filter to achieve nested LDAP group support in Grafana with LDAP servers that support LDAP_MATCHING_RULE_IN_CHAIN. 

Huge hat tip to @tmalkowski for doing most of the legwork in #2582 and [go-ldap/ldap#28](https://github.com/go-ldap/ldap/issues/28). This should also address #3808.

I am running an RPM build of this branch on Oracle Linux 7.2 (RHEL clone) and was able to log in using nested group membership. The grunt tests before the RPM build passed, but I'm not sure if there is additional testing for me to do.

This does not address the suggestion in #2582 to make the string input to group_search_filter dynamic/based on a user attribute. I know only enough go to build Grafana, so I'm definitely the wrong person to implement that :smiley:

### CODE REVIEW

**Comment by nktl** [comment]
Does this really work?

I am running my build with this PR (also tested with official build straight from master, as this PR has been merged recently) and the Extensible Match matching rule (member:1.2.840.113556.1.4.1941:=) does not seem to be properly understood - regular equality match is done instead.

This is what I am seeing coming from Grafana in tcpdump using this PR (it does not work, of course):

Filter: (member:1.2.840.113556.1.4.1941:=CN=testuser,OU=Users,DC=test,DC=local)
    filter: equalityMatch (3)
        equalityMatch
            attributeDesc: member:1.2.840.113556.1.4.1941:
            assertionValue: CN=testuser,OU=Users,DC=test,DC=local

This is how the query should look like - same query executed direcly via ldapsearch (works fine):

Filter: (member:1.2.840.113556.1.4.1941:=CN=testuser,OU=Users,DC=test,DC=local)
    filter: extensibleMatch (9)
        extensibleMatch member
            matchingRule: 1.2.840.113556.1.4.1941
            type: member
            matchValue: CN=testuser,OU=Users,DC=test,DC=local


My group search filer in ldap.toml is as follows:

group_search_filter =  "(member:1.2.840.113556.1.4.1941:=CN=%s,OU=Users,DC=test,DC=local)"

**Comment by dfwarden** [comment]
I apologize if opening this pull request against the v2.6.x branch was the wrong thing to do. I assumed (perhaps incorrectly) that it was the correct place for this sort of thing. Although the changelog on master has been updated to refer to this PR it seems the underlying commits are not yet in master.

Building from my branch (itself based on v2.6.x) in this PR should've worked, though. Do you have `github.com/go-ldap/ldap.MatchingRuleAssertionMap` in the output of `nm /usr/sbin/grafana-server`? If not, goes `godep restore -v` before trying another build change the result of the `nm` test?

**Comment by torkelo** [comment]
@dfwarden I reverted that PR merge, can you re-create it against master?

**Comment by nktl** [comment]
@dfwarden Thanks, I did most of my tests against latest official 3.0-master package, which seemed to have this PR merged, but in fact it did not (no MatchingRuleAssertionMap)

My own build from your PR works fine, I can confirm it process the filter correctly.

However, there is a limitation that I cannot find a workaround for.

My AD users are login into Grafana using 'short' username (sAMAccountName - i.e. testuser), which is reflected in search filter:

`search_filter = "(sAMAccountName=%s)"`

The CN for the user is a 'verbose' descriptive name like 'Test User Account'.
However, group search filter expects full CN in input, not sAMAccountName. So something like this is not going to work:

`group_search_filter = "(member:1.2.840.113556.1.4.1941:=CN=%s,OU=Users,DC=test,DC=local)"`

This is because %s gets expanded to something like 'testuser', which is not a valid CN, the filter expects string like 'Test User Account' in input - which is not something that is fed by the user directly, but a product of search filter.

Is there any workaround for this problem (potentially some other variable than %s that can be pointed to CN used in filter)?

**Pull request merged**
