### PR TITLE
Explore: Show links to queryless apps

### LINKED ISSUE #94535: Explore: Simple app links
Create a very simple extension point allowing to render a link in the query row pointing to an application plugin. The plugin can render the link based on the current query. 

Only first extension is picked when multiple apps provide links to the same query for now, but will change later.

### PR DESCRIPTION
**Pull request by ifrost**
Fixes #94535

Slightly different approach to https://github.com/grafana/grafana/pull/94532. Instead of cluttering UI in QueryRow the button will be shown only in Explore next the data source picker e.g.:

Screenshot 2024-11-18 at 14 02 34

The button shows up only if the query can be shown in the corresponding app. Test it with https://github.com/grafana/explore-profiles/pull/220

This will also elevate the button to logs apps:

https://github.com/user-attachments/assets/19c6379f-1b1c-4744-8314-31b11ea1098d

This approach uses existing links to Explore Toolbar elevating links coming from queryless apps.

### CODE REVIEW

**Comment by ifrost** [comment]
@gelicia / @harisrozajac would you mind also having a look? 😅

**Comment by gelicia** [comment]
Is having log volume configured required? When I "go queryless" I go to the app with a 404 message in a pop up, then the main screen has a message about log volume has not been configured. When I hit "show logs" the message about log volume disappears but I still get the 404.

**Comment by ifrost** [comment]
> Is having log volume configured required? When I "go queryless" I go to the app with a 404 message in a pop up, then the main screen has a message about log volume has not been configured. When I hit "show logs" the message about log volume disappears but I still get the 404.

Shouldn't be required 🤔 There might be some other set up missing. Was the query returning results in Explore before going to the app? 

Also: the behavior of "Go Queryless" should be the same as "Add > Open in Explore Logs". Is it broken in main as well?

**Comment by ifrost** [comment]
> Right but then I shouldn't be able to see the go queryless button if that isn't the case, right? The logic for what works should be consistent for both, and I'm seeing the go queryless button no matter what.

Could you share recording of your screen? The "Go Queryless" should behave exactly like "Open in Logs" in main so it appears only when there's at least one label selected (and the app is intalled) like below:


https://github.com/user-attachments/assets/2ffd66a1-4641-4bdb-ac29-7775ae252fed

**Comment by matyax** [comment]
Love this! Were other CTA considered for the "Go queryless" button? Like "Browse in app" or "Go to app"? I'm not 100% sure "go queryless" communicates to the user the intentions of the button. We've been talking for long about "queryless experiencies", but that's something internal in Grafana. If this has been discussed before feel free to ignore 👍

**Comment by ifrost** [comment]
> Were other CTA considered for the "Go queryless" button?

Started with "Explore with Logs/Profiles/... app",  then someone suggested "Try our new queryless experience for ..." and shortened it to "Go|Try Queryless" and I went with the shorter :D

**Comment by gelicia** [comment]
`make devenv sources=loki,prometheus`

I have a label selector and it shows the go queryless button but not the option in the add menu.

Screenshot 2024-12-09 at 9 27 37 AM

Something must have changed since the last time I looked at this because the app does show results now instead of the message about log volume. I checked with both this and the `sources=tempo` scenario. I still get the 404 pop up when the app starts, and the 404 is for `api/datasources/uid/gdev-loki/resources/detected_fields`

Can you test this with log volume is off to ensure the button doesnt display? Is there something else I am missing?

**Comment by ifrost** [comment]
> I have a label selector and it shows the go queryless button but not the option in the add menu.

Yep! That's correct! The idea is to move the button to make it more visible so it basically moves from "Add..." to "Go Queryless". BTW. @grafana/explore-squad - do you think it might be disruptive to current users and we should keep the button in "Add..." menu as well?

**Review by gelicia — APPROVED** [review]

**Pull request merged**
