### PR TITLE
Docs: Update dashboard.md

### LINKED ISSUE #21174: Docs refer to time_options field that is obsolete
**Issue**: https://grafana.com/docs/grafana/latest/reference/dashboard/#timepicker shows time_options field in the JSON despite this being a "relic from older Grafana versions" according to issue #14915 
Can be seen in the docs under the latest version (and previous versions)

**What should change**: If it is indeed obsolete, then the sample JSON shouldn't include it and the row in the table below should also be removed.

### PR DESCRIPTION
**Pull request by oddlittlebird**
**What this PR does / why we need it**: Updates dashboard.md to remove obsolete fields and remove "TODO" from table.

**Which issue(s) this PR fixes**:

Fixes #21174 

**Special notes for your reviewer**: Please review the table beneath Timepicker and give content suggestions for everything marked "TODO".

### CODE REVIEW

**Review by torkelo — APPROVED** [review]

**Comment by oddlittlebird** [comment]
@torkelo , can you provide the missing content or delegate someone who can?

**Comment by oddlittlebird** [comment]
Still need content for everything marked "TODO."

**Comment by oddlittlebird** [comment]
@torkelo , @daniellee , I need content to replace the "TODO"s in that table.

**Comment by oddlittlebird** [comment]
@torkelo , @daniellee , I need content to replace the "TODO"s in that table. Feel free to delegate, but they look REALLY tacky and I would like to give our users actual content.

**Comment by ivanahuckova** [comment]
I looked at it, but unfortunately I don't have enough knowledge regarding timepicker metadata. I can (probably in the same way as you) figure out what _refresh_interval_ (how often is dashboard refreshed) and _time_options_ ( custom time options). But this is probably something that @torkelo, @daniellee, @hugohaggmark or @dprokop will be able to answer. 🙂

**Review by ivanahuckova — COMMENTED** [review]
I looked at it, but unfortunately I don't have enough knowledge regarding timepicker metadata. I can (probably in the same way as you) figure out what refresh_interval (how often is dashboard refreshed) and time_options ( custom time options). But this is probably something that @torkelo, @daniellee, @hugohaggmark or @dprokop will be able to answer. 🙂

**Pull request merged**
