### PR TITLE
fix: prevent datasource json data stored as nil

### LINKED ISSUE #14239: nul pointer dereference after upgrade to 5.3.x
Hi,

I am hitting the nil pointer dereference when I upgrade my 5.0.0 container with a couple of dashboards to 5.3.x (both 5.3.2 and 5.3.4 exhibit the same behaviour). Rolling back to 5.2.4 makes this work again (I did not test upgrade from 5.2.4 to 5.3.x).

I was able to gather the logs (from journalctl) :
```
Nov 28 00:02:33 node2 dockerd-current[1122]: t=2018-11-27T23:02:33+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=192.168.33.1 time_ms=4 size=122 referer="http://node2:3000/d/4RWI2hLiz/ceph-at-a-glance?refresh=15s&orgId=1"
Nov 28 00:02:33 node2 dockerd-current[1122]: t=2018-11-27T23:02:33+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x434ed8)\n/usr/local/go/src/runtime/panic.go:82 (0x43402d)\n/usr/local/go/src/runtime/signal_unix.go:390 (0x44adc1)\n/go/src/github.com/grafana/grafana/pkg/components/simplejson/simplejson.go:198 (0xec6978)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a18)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a18)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a18)\n/usr/local/go/src/net/http/httputil/reverseproxy.go:197 (0xa4d24d)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:99 (0xec646c)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:56 (0xf558c1)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:255 (0xf87713)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb2860c)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xb27f27)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:15 (0xb28911)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb27e40)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x82f200)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x812f20)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x812c8b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xb2583d)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x83faa4)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x83a2ae)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x833821)\n/usr/local/go/src/net/http/server.go:2741 (0x6b1c8a)\n/usr/local/go/src/net/http/server.go:1847 (0x6ae045)\n/usr/local/go/src/runtime/asm_amd64.s:1333 (0x465220)\n"
```
You basically get a ton of messages like this in the log and the container restarts all the time. In the grafana web UI, you get `Templating Init failed` (if it loads).

If you re-deploy (purge the old grafana 5.0.0 container with the data and install the 5.3.x container directly), everything works as expected. This only happens when you upgrade the containers while keeping the old grafana data intact.

Let me know if you need any more information on the issue or any more details on how to reproduce the issue.

### PR DESCRIPTION
**Pull request by marefr**
Fixes #14239 

Should we add a database migration converting all null jsonData to `{}` as well/instead?

### CODE REVIEW

**Comment by torkelo** [comment]
yes, this feels like a migration and a single check on write path would be a better option.

**Comment by marefr** [comment]
Updated to use migration. Should we move this to 6.1 milestone then?

**Review by xlson — APPROVED** [review]
LGTM

**Review by bergquist — APPROVED** [review]
LGTM

**Pull request merged**
