### PR TITLE
Saga: Change Tab Design

### PR DESCRIPTION
**Pull request by codeincarnate**
Ongoing work to make tabs more prominent with the transformation UI.

**What is this feature?**

**Why do we need this feature?**

**Who is this feature for?**

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by torkelo** [comment]
should this PR not be named `Saga: Change tab design`  :)

**Comment by codeincarnate** [comment]
Just circling back to this @torkelo . Not sure if we want to change the tab everywhere (or do we? 😄), I'm down to give it a go. I'll shape this up and get it headed in that direction.

**Comment by torkelo** [comment]
Of course this should change the tab everywhere, we do not want two tab design. That would be madness 😃 

Let me review and try this, then we need approval from saga squad designers

**Comment by torkelo** [comment]
After testing this I don't think this design works better, I think it looks worse in most cases. Look okay in panel edit but for normal pages, and scene apps it looks a lot worse.  

And I find the original idea that this makes the Transformations tab more noticeable, it is such a small change I doubt it makes any measurable difference. 

I think adding a "Add transformation" action to the bottom of the Query tab (next to "+ Add query" and "+ Expression"  could be better way

**Comment by codeincarnate** [comment]
@torkelo did make some updates to the design that might change your mind. Would be happy to get your feedback there. Very curious to see what the usage scenarios you had looked at and definitely happy to make more changes 😄

**Comment by torkelo** [comment]
sorry, Looks terrible to me. The design does simply not work with our page designs. What is wrong with the current design? GitHub and many many sites is it :) 

Screenshot from 2023-09-14 08-34-14
Screenshot from 2023-09-14 08-33-36
Screenshot from 2023-09-14 08-33-08

**Comment by codeincarnate** [comment]
That's fair. It was primarily because in the transformation case the controls are getting lost among other elements on the page. I'll close this and we can explore a different method to go forward.

**Pull request closed without merging**
