### PR TITLE
Dashboard: Chore - Remove rudderstack events from panel menu and toolbar 

### PR DESCRIPTION
**Pull request by axelavargas**
**What is this feature?**

Per request, this PR removes the following Rudderstack events across the code:

- dashboards_panelheader_menu
- dashboards_panelheader_description_displayed -- I did not find this event in the code
- dashboards_toolbar_actions_clicked 

**Why do we need this feature?**

Slack thread with the request: https://raintank-corp.slack.com/archives/C03MCTKAJA0/p1721734113935679

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer:**

The removal of these events will affect your analytics if you rely on this data. Before merging this PR, I would like to get confirmation from the respective team owners.

@grafana/sharing-squad  --- The event instrumenting the `share`  action from panel menu is removed
@grafana/dataviz-squad  --- The event instrumenting the `toggleLegend` action is removed
@grafana/dashboards-squad -- All the events instrumenting panel menu options(view, edit, copy, duplicate, etc) and toolbar options(save, settings, refresh, zoom) are removed

### CODE REVIEW

**Comment by aocenas** [comment]
@axelavargas isn't there a way to do this with configuration instead of code change? Like I see this similar to logging where we don't need to have debug level always on but sometimes it can be useful and doing a deploy for that isn't great. Isn't there a setting in rudderstack like an allowlist? Or can't we have something like that in grafana config?

**Review by juanicabanas — APPROVED** [review]
LGTM! From @grafana/sharing-squad 👍🏻

**Review by nmarrs — APPROVED** [review]
Good from @grafana/dataviz-squad perspective 👍🫡

**Comment by axelavargas** [comment]
> @axelavargas isn't there a way to do this with configuration instead of code change? Like I see this similar to logging where we don't need to have debug level always on but sometimes it can be useful and doing a deploy for that isn't great. Isn't there a setting in rudderstack like an allowlist? Or can't we have something like that in grafana config?

Hey @aocenas 👋🏾 , as far as I know, we don't have that option. Our current setup is based on Rudderstack Event Streams, which means we are manually instrumenting data collection. In Grafana, we are using the Javascript SDK within a wrapper called `RudderstackBackend` [(link)](https://github.com/grafana/grafana/blob/7d06a17038923c47afbbd7b084b02d3100aa02db/public/app/core/services/echo/backends/analytics/RudderstackBackend.ts#L40). Unfortunately, to de-instrument (stop sending) any events, we need to remove them from the code. 

P.S. After talking to the sharing squad, I will keep the instrumentation for all events related to `share` feature, I will make this change before merging 😄

**Review by evictorero — APPROVED** [review]

**Pull request merged**
