### PR TITLE
A11y: add copy button to API Key modal

### PR DESCRIPTION
**Pull request by zuchka**
**What this PR does / why we need it**:

Improves A11y:

The current API Key modal displays the API key, but in order to copy it, the user must highlight the key using a mouse or pointer device. This is not very accessible for those who rely on keyboard-only navigation. Adding a `Copy to Clipboard` button allows keyboard users to tab into the modal and copy the key. It's also a little more convenient for mouse-users 😄 

before:

CleanShot 2022-03-09 at 12 59 01@2x

~~after~~, using only keyboard, and with screen reader enabled:

CleanShot 2022-03-09 at 12 38 21@2x

UPDATE: newest version uses inline button:

CleanShot 2022-03-10 at 09 35 47@2x

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by yaelleC — COMMENTED** [review]
Are we being consistent with other copy buttons styling?
The only one I know about is the one when sharing a dashboard: 

Screenshot 2022-03-10 at 09 41 29


It's using:
```
<Field label="Link URL">
            <Input
              id="link-url-input"
              value={shareUrl}
              readOnly
              addonAfter={
                <ClipboardButton variant="primary" getText={this.getShareUrl} onClipboardCopy={this.onShareUrlCopy}>
                  <Icon name="copy" /> Copy
                </ClipboardButton>
              }
            />
 </Field>
```

Could we do the same here?

**Comment by zuchka** [comment]
@yaelleC great catch! I was looking at the `Copy to Clipboard` button inside the `Export --> View JSON` modal.

But your is much more appropriate, I feel:

CleanShot 2022-03-10 at 09 35 47@2x

**Review by yaelleC — APPROVED** [review]
Looks good thanks!

I'll approve but you should probably wait for the owners to ✅  too !

**Review by axelavargas — APPROVED** [review]
Looks great @zuchka 👏🏾

**Pull request merged**
