### PR TITLE
Add record-audio icon for recorded queries

### PR DESCRIPTION
**Pull request by MasslessParticle**
adds a new icon used to indicated recorded queries

### CODE REVIEW

**Comment by MasslessParticle** [comment]
Does adding an Icon count as a breaking change?

**Comment by toddtreece** [comment]
@MasslessParticle i found one more place it looked like it needed to be added and pushed a commit. related PR: https://github.com/grafana/icons/pull/5

**Review by toddtreece — APPROVED** [review]

**Review by leventebalogh — APPROVED** [review]
LGTM 👍 

@MasslessParticle 
> Does adding an Icon count as a breaking change?

It's not, you are right, I will remove the breaking-change label.
I will look into how we could easily identify these with the tool. 
Currently it is still a bit rough around the edges and only looks if the return type has changed of an exported function.

**Comment by ivanahuckova** [comment]
I have added backport label because the milestone is 8.3.4, so the backport PR is created (#43784)

**Pull request merged**
