### PR TITLE
backend: Update xorm

### LINKED ISSUE #15663: time of SQL queries in json log output is not machine parsable
### What Grafana version are you using?
5.4.3
### What datasource are you using?
not related
### What OS are you running grafana on?
CentOS 7 linux
### What did you do?

from grafana.ini
[database]
log_queries = true

[log.console]
level = Trace
format = json

### What was the expected result?
```json
{
  "logger": "sqlstore.xorm",
  "lvl": "info",
  "msg": "[SQL] UPDATE `user` SET `last_seen_at` = ? WHERE `id`=? []interface {}{\"2019-02-26 13:46:35\", 67}",
  "took": "0.7225901",
  "t": "2019-02-26T13:46:36.428585149+01:00"
}
```
### What happened instead?
```json
{
  "logger": "sqlstore.xorm",
  "lvl": "info",
  "msg": "[SQL] UPDATE `user` SET `last_seen_at` = ? WHERE `id`=? []interface {}{\"2019-02-26 13:46:35\", 67} - took: 722.5901ms",
  "t": "2019-02-26T13:46:36.428585149+01:00"
}
```

In json log format time the query took need to be presented in seconds instead of mixed resolutions
for instance
```
took: 848.943µs
took: 85.025291ms
```
and send as a separate json key

### PR DESCRIPTION
**Pull request by roidelapluie**
**What this PR does / why we need it**:

Update xorm to get better logging

**Which issue(s) this PR fixes**:

Fixes #15663

**Special notes for your reviewer**:

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by aknuds1** [comment]
Should this still be a draft?

**Comment by roidelapluie** [comment]
Yes there is a bug in the underlying xorm upgrade that I will investigate, see CI failure.

**Comment by marefr** [comment]
@roidelapluie Thanks. Historically upgrading xorm have unfortunately introduced bugs and in some cases very tricky ones why we're very careful accepting upgrades of xorm. We have to review all commits xorm have done from current version to your suggested version to be sure they haven't done any breaking changes. The version you suggesting is that the first one having log improvements or is it maybe in an earlier version (less commits for us to review)?

**Comment by roidelapluie** [comment]
It is - and they do not respect semver - 1.0.0 is not compatible with 1.0.1

**Pull request closed without merging**
