### PR TITLE
Server: Implement timeout waiting for server to shut down

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Implement timeout while waiting for server to shut down. Should fix issue @davidmparrott has been experiencing of test cleanup code getting stuck waiting for server to stop.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by davidmparrott — APPROVED** [review]
This solves that problem I originally reported. Thanks for the follow-up

**Comment by FZambia** [comment]
Hi, a bit worried whether we masking original problem happened in tests (deadlock in some service?) by introducing this shutdown timeout? I never saw Grafana to shut down in more than 1 second, but still feel that 3 seconds is too small for default termination timeout (maybe this feeling comes from Kubernetes that gives service up to 30 secs by default to shutdown gracefully).

**Comment by aknuds1** [comment]
> Hi, a bit worried whether we masking original problem happened in tests (deadlock in some service?) by introducing this shutdown timeout? I never saw Grafana to shut down in more than 1 second, but still feel that 3 seconds is too small for default termination timeout (maybe this feeling comes from Kubernetes that gives service up to 30 secs by default to shutdown gracefully).

@FZambia what is your suggestion? I think a timeout is good regardless, although how long it should be is unclear. I'm really unsure what would cause `Run` not to close the channel (and thereby make `ShutDown` hang), so don't see any solution to that currently.

**Comment by FZambia** [comment]
I mean that here tests clearly indicate that sth goes wrong and by introducing this timeout we will never have a chance to catch a possible reason.

Agree that having a shut down timeout is a good thing in general. One possible way to go is make it configurable over incoming context. Maybe start with shut down timeout using a safer default like 30 secs for non-test environment. Thus users will benefit from infinite hanging never happen in production.

But I think the blocking issue in tests should be solved eventually since otherwise it may also happen in production (or not) – so maybe we should not shut down with timeout in tests at all (using `context.Background` there) to have a chance to fix a root cause? 

Also I believe if shutdown is not successful in a grace period then Grafana should exit with status > 0.

**Comment by aknuds1** [comment]
@FZambia 

> I mean that here tests clearly indicate that sth goes wrong and by introducing this timeout we will never have a chance to catch a possible reason.

That is a point, but before the change in this PR, our test cleanup code shuts the server down in a goroutine, that's even worse isn't it since if the shutdown is stuck you have a hanging goroutine also?
 
> Agree that having a shut down timeout is a good thing in general. One possible way to go is make it configurable over incoming context. Maybe start with shut down timeout using a safer default like 30 secs for non-test environment. Thus users will benefit from infinite hanging never happen in production.
> 
> But I think the blocking issue in tests should be solved eventually since otherwise it may also happen in production (or not) – so maybe we should not shut down with timeout in tests at all (using `context.Background` there) to have a chance to fix a root cause?
> 
> Also I believe if shutdown is not successful in a grace period then Grafana should exit with status > 0.

Do you have a concrete suggestion for how to improve this PR, without spending too much more time elaborating? Would it be better to e.g. make the timeout configurable so that in non-test usage it's longer (e.g. 30 seconds)?

**Comment by FZambia** [comment]
Sorry if I wrote suggestions in non-clear way. Here is what I think is worth to do:

1) Introduce `Server.Shutdown(ctx context.Context, reason string)`
2) Use `server.Shutdown(context.Background(), "test cleanup")` in tests to have a possibility to find a problem with tests (as far as I understand an issue description there is a sort of deadlock happening).
3) Use `server.Shutdown(context.WithTimeout(context.Background(), 30 * time.Second), "")` for a server shutdown in non-test environment
4) Exit with code 1 if we could not finish shutdown till context canceled.

**Comment by FZambia** [comment]
Thinking more - in tests we can still use timeout I suppose, but tests should fail if shutdown have not finished gracefully.

**Comment by aknuds1** [comment]
@FZambia OK I will see what's possible, after dealing with some other tasks.

**Comment by aknuds1** [comment]
Implemented @FZambia's suggestions.

**Comment by aknuds1** [comment]
I made a fix in [Alertmanager](https://github.com/prometheus/alertmanager/pull/2558) to deal with the deadlock.

**Pull request merged**
