### PR TITLE
Update changelog generation to ignore not merged pull requests

### PR DESCRIPTION
**Pull request by papagian**
**What this PR does / why we need it**:
This fix prevents not merged pull requests (but closed) from being included in the Changelog.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Unfortunately, the only way (I've found so far) to tell that a pull request is merged is by calling [this](https://developer.github.com/v3/pulls/#get-a-single-pull-request) API and checking the `merged_at` field.
This increases significantly the number of requests to github API and slows down considerably the changelog generation.
In addition to this, there is a possibility to face rate-limiting issues, therefore authenticating the requests by setting `GITHUB_ACCESS_TOKEN` and `GITHUB_USERNAME` is most probably required.
Finally, possibly there is room for improvement in the code:
```
const mergedIssues = [];
for (const item of res.data) {
    if (await filterOutNotMerged(item)) {
        mergedIssues.push(item);
    }
}
```

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Seems I mixed up changelog with cherrypick task. Cherrypick task is doing similar thing as you've added:
https://github.com/grafana/grafana/blob/46ccfacb2bcca47c660f3360f8a6b219e2917f32/packages/grafana-toolkit/src/cli/tasks/cherrypick.ts#L39-L41

Found that GitHub have an [api endpoint for checking if pr is merged](https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged). Not sure that one is better?

@torkelo Sanity check: can you confirm that we only want to include PR's in changelog or should we support also issues?

**Comment by papagian** [comment]
> Found that GitHub have an [api endpoint for checking if pr is merged](https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged). Not sure that one is better?

@marefr 
I think it's preferable to use this because the other returns a lot more information we don't need. I've made the changes.

**Review by marefr — APPROVED** [review]
LGTM great

**Review by dprokop — APPROVED** [review]
This is looking good @papagian :)

**Pull request merged**
