### PR TITLE
AzureMonitor: Fix metric namespace clear

### LINKED ISSUE #41870: Azure Monitor: Editing a existing metric query breaks the panel
**What happened**:

I noticed that when I click on "Edit" for an existing (old) query, the "Metric" field gets removed and the query stops working:

Screenshot from 2021-11-18 12-42-22

I does not happen for more recent queries. After a quick look it seems that it's caused by a change on the Azure API that changed the capitalization of the metric name / namespace.

**What you expected to happen**:

All the fields to be automatically filled and query to work.

**How to reproduce it (as minimally and precisely as possible)**:

I has to be with an old query.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
**What this PR does / why we need it**:

There has been a change in the `Metric namespace` that the Azure API returns. For example, while before it returned `Microsoft.Compute/VirtualMachines`, now it returns `microsoft.compute/virtualmachines`. This caused us to recognize the existing namespace as invalid and re-set it with the first namespace returned. After that, the query no longer works because the metric that depends from the namespace is removed (since it may not exist in new namespace).

For fixing that, I could make the comparison a bit less strict and avoid the comparison to be case sensitive but then I realized that we should not be updating the query automatically without user input.

Right now, I have just removed the condition that automatically updated the namespace if the current one is "invalid" but we are doing the same for all the other fields (subscription, resource group, resource type...). Should we be doing this at all? Thoughts?

**Which issue(s) this PR fixes**:

Fixes #41870

**Special notes for your reviewer**:

ccing @joshhunt since this was recently edited by you and you may have more context.

### CODE REVIEW

**Comment by joshhunt** [comment]
I’ve been re-thinking whether we/plugins should even clear “invalid” values in the first place. It makes it impossible for users to set custom values for for some reason we don’t support them, or they don’t come back from the API for whatever reason.

Perhaps only setting a parent field should clear out child fields (if the children are now invalid?). Not sure. Worth at leas aligning all the cloud plugins (which tend to use a lot of drop downs) on this. 

if we do away with clearing what we think are invalid values, then we should do better error messaging to make it more clear where the invalid value could lie.

**Comment by sunker** [comment]
> if we do away with clearing what we think are invalid values, then we should do better error messaging to make it more clear where the invalid value could lie.

Doesn't the api return a error that makes sense for the user? For cloud monitoring and cloudwatch, we don't clear out the values when changing "parent" fields. For both these plugins, I think that's fine because the api is fast, cheap and it returns an error message that makes sense - something like `label x is not supported for metric y`. 

Anyway, completely agree that we should try to align all core plugins here. So in that case, I'm leaning toward not clearing fields since that doesn't mean we have to write code for it. Don't have too strong opinions though, so open for other ideas.

**Comment by andresmgot** [comment]
> Doesn't the api return a error that makes sense for the user? For cloud monitoring and cloudwatch, we don't clear out the values when changing "parent" fields. For both these plugins, I think that's fine because the api is fast, cheap and it returns an error message that makes sense - something like `label x is not supported for metric y`.

In this case, it's not returning an error, it just claims "no data" which could be confusing. In any case, that's not what this PR is fixing? 

> Anyway, completely agree that we should try to align all core plugins here. So in that case, I'm leaning toward not clearing fields since that doesn't mean we have to write code for it. Don't have too strong opinions though, so open for other ideas.

So you agree on the approach of this PR?

**Comment by sunker** [comment]
> In this case, it's not returning an error, it just claims "no data" which could be confusing. In any case, that's not what this PR is fixing?

Yes, got it! 

> So you agree on the approach of this PR?

Yes!

**Review by sunker — APPROVED** [review]
LGTM

**Pull request merged**
