### PR TITLE
Auth: Use camelCase in SSO Settings API

### PR DESCRIPTION
**Pull request by mgyongyosi**
**What is this feature?**
This PR implements a custom Marshaler/Unmarshaler for `SSOSetting` to return the settings field's key in camelCase + accept requests which contains settings with camelCased key.

**Why do we need this feature?**
Easier to work with camelCase on the FE.

**Who is this feature for?**

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by Clarity-89 — APPROVED** [review]
Tested and looks good! 🎉

**Review by dmihai — COMMENTED** [review]
What do you think about defining a `struct` for the settings field in `SSOSettings`? I think it will be cleaner to work with a structure instead of a `map[string]interface{}`. You also don't have to implement custom marshalling functions because you can define json keys in the structure.

**Comment by mgyongyosi** [comment]
> What do you think about defining a `struct` for the settings field in `SSOSettings`? I think it will be cleaner to work with a structure instead of a `map[string]interface{}`. You also don't have to implement custom marshalling functions because you can define json keys in the structure.

Yep, we thought about it, but because one of the goals of this API is to provide a generic way to update SSO settings and there are multiple types of providers will be supported and those have different settings: for example the OAuth providers' setting is different form the SAML provider or from the LDAP. Besides OAuth providers have different settings too (some of those need extra settings like the `force_use_graph_api` in the AzureAD provider) and it's really difficult to create a struct which would cover all of those scenario, so (imho) it's more straightforward to provide a flexible interface. 

However, I'm open for ideas, the current solution is not carved in stone. :)

**Review by dmihai — APPROVED** [review]
Unblocking this PR because we can look into how to optimize it later.

**Pull request merged**
