### PR TITLE
Add Prometheus annotations doc

### PR DESCRIPTION
**Pull request by wkruse**
Documentation for #2873.

### CODE REVIEW

**Comment by bergquist** [comment]
@wkruse Thank you for helping out!

**Comment by wkruse** [comment]
@bergquist Glad to help! :-) Thanks for merging.

**Comment by cemo** [comment]
@wkruse Could you a little bid explain how "A regular metric query" should be formatted? It should include some special labels?

**Comment by cemo** [comment]
For those who are interested in prometheus annotations from regular metrics, your series has to return either 0/1. This can be accomplished by `series > bool 0` . Note that `bool` is mandatory.

**Pull request merged**
