### PR TITLE
Plugins: Add install token and stackId to config

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Add stackId and installation token to configs delivered to the FE

**Why do we need this feature?**

This is necessary for calls like:

```ts
getBackendSrv().post(`${GCOM_API_ROOT}/instances/${instanceId}/plugins`, {
    plugin,
    version,
  }, {
    headers: {
      "Authorization": "Bearer " + config.pluginInstallToken,
    },
  });
 ```
that will be necessary to support cloud plugin installation from grafana catalog.
For more details of the whole solution, check the draft PR: https://github.com/grafana/grafana/pull/75648

**Who is this feature for?**

Developers

**Which issue(s) does this PR fix?**:

This is part of:
 https://github.com/grafana/grafana-plugins-platform-team/issues/26
 https://github.com/grafana/grafana-plugins-platform-team/issues/27

 and necessary for
 https://github.com/grafana/grafana-plugins-platform-team/issues/28
 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by leventebalogh** [comment]
I am bit concerned about making this installation token available for the frontend.

Couldn't we implement a new backend api endpoint that does the call towards GCOM and the frontend would only call this? Like that we would never need to send down the secret itself to the frontend.

E.g.

```typescript
getBackendSrv().post(`${API_ROOT}/install-on-instance`, {
    plugin,
    version,
    instanceId
  }
});
```

**Comment by oshirohugo** [comment]
@leventebalogh thank you for your suggestion. A agree it makes better, but instead of creating a new endpoint, do you see any problem in altering the current plugin installation endpoint (${API_ROOT}/{plugin-id}/install) to call GCOM installation? That would make things simpler since we wouldn't have to pass the stackId up to the frontend and the frontend would also be simpler.

**Comment by leventebalogh** [comment]
So you mean in case we are running in the cloud (probably based on a Grafana setting), then the installing endpoint would behave differently and call out to GCOM? From my perspective that could work, although I don't have too much experience in the backend part, so probably we should ask @wbrowne or @marefr, too.

**Comment by wbrowne** [comment]
> So you mean in case we are running in the cloud (probably based on a Grafana setting), then the installing endpoint would behave differently and call out to GCOM? From my perspective that could work, although I don't have too much experience in the backend part, so probably we should ask @wbrowne or @marefr, too.

Yep good shout @leventebalogh! This would have been the approach I had imagined, thanks for the ping. We even refactored things so that this was possible IE having one implementation in OSS and another than would handle our Cloud use case. LMK if that makes sense @oshirohugo - you'll need to wrangle with Wire a bit, but it should be pretty straightforward I reckon 🤞

**Pull request closed without merging**
