### PR TITLE
Escape postgresql parameter

### LINKED ISSUE #12644: Not escaped postgres parameters
Please include this information:
### What Grafana version are you using?
5.2.1
### What datasource are you using?
Postgres

In 5.2.1 postgresql datasource parameters are not escaped before building connection string.
`func generateConnectionString(datasource *models.DataSource) string {
	password := ""
	for key, value := range datasource.SecureJsonData.Decrypt() {
		if key == "password" {
			password = value
			break
		}
	}

	sslmode := datasource.JsonData.Get("sslmode").MustString("verify-full")
	u := &url.URL{Scheme: "postgres", User: url.UserPassword(datasource.User, password), Host: datasource.Url, Path: datasource.Database, RawQuery: "sslmode=" + sslmode}
	return u.String()
}`

Unescaped RawQuery is very dangerous, as it allows user to pass additional postgres params, like sslcert. A malicious user could utilize any secrets on the machine.

I see that before changing to "net/url" it these options were escaped (v5.0.0)
`
return fmt.Sprintf("postgres://%s:%s@%s/%s?sslmode=%s", url.PathEscape(datasource.User), url.PathEscape(password), url.PathEscape(datasource.Url), url.PathEscape(datasource.Database), url.QueryEscape(sslmode))`

I think "url.QueryEscape" is needed here.

### PR DESCRIPTION
**Pull request by yogyrahmawan**
Fixes #12644 
* Escaping postgres parameter

### CODE REVIEW

**Comment by svenklemm** [comment]
I think the proper fix for this is to escape sslmode and continue using net/url as otherwise ipv6 hosts will not work and ipv6 handling would have to be added to the connection string generation.

**Comment by yogyrahmawan** [comment]
I agree with your solutin @svenklemm  . Will do at my spare time. Thanks

**Comment by yogyrahmawan** [comment]
Fix has been pushed(escaping sslmode on postgresql param)

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
