### PR TITLE
DashboardLinks: Support variable expression in to tooltip - Issue #30409

### PR DESCRIPTION
**Pull request by huynhsamha**
**What this PR does / why we need it**:

This PR support compiling variable expression in the tooltip on the dashboard link.

**Which issue(s) this PR fixes**:

Issue #30409

**Special notes for your reviewer**:

I see this is a simple problem, therefore I've created PR for my issue.

### CODE REVIEW

**Review by dprokop — CHANGES_REQUESTED** [review]
Thanks for the contribution @huynhsamha . Before we merge this one- could you please add a test for the functionality you are adding in this PR?

**Comment by huynhsamha** [comment]
Hi @dprokop, I don't know how to write a test file for this feature, but I've tested it by UI.

This is a screenshot of my simple test

Screenshot from 2021-01-26 21-52-01

Screenshot from 2021-01-26 21-48-29

If you can write a test file for this, please help me with that.

Thanks.

**Comment by jackw** [comment]
Just to reiterate on what @dprokop previously said - thanks so much for this contribution @huynhsamha! 👏 

> If you can write a test file for this, please help me with that.

I've gone ahead and added a couple of commits to this PR which introduce tests for the `getAnchorInfo` and `getLinkUrl` `link_srv` methods. It's getting a little late here now but if you've any questions about these tests please feel free to ask and I'll do my best to answer them.

**Comment by huynhsamha** [comment]
Hi @jackw, thanks for your support about the test.

**Review by dprokop — APPROVED** [review]
Great tests @jackw!

**Pull request merged**
