### PR TITLE
Log Details: Display all field options and remove "show more"

### PR DESCRIPTION
**Pull request by matyax**
During a user interview, we realized that the "eye" icon for the feature "Show this field instead of the message" was not known by the user, which brought back something I recently thought while working with those components: why are we collapsing 2 options behind a "show more" toggle when there is space for all the options? This not only hides the fature, but makes interacting with it a lot more complicated than it should be.

Current implementation:

current

After these changes:

after

**Why do we need this feature?**

To improve visibility of this option and improve the experience of interacting with it with a really simple change.

**Which issue(s) does this PR fix?**:

Can be part of https://github.com/grafana/grafana/issues/61769

**Special notes for your reviewer**:

What do you think? It's a simple change which seems very beneficial for users.

### CODE REVIEW

**Comment by matyax** [comment]
This is such a simple change that I went ahead and created this. What do you think @grafana/observability-logs

**Comment by ivanahuckova** [comment]
Yeah, I agree. I am not sure if I shared this feedback with @svennergr or not, but I agree that at this point I think it does not make sense to hide these functionalities behind submenu. If we introduce next one, I would reconsider.

**Comment by svennergr** [comment]
Would like some eyes from @niat22 on this one because it's based on her design. What do you think, should we go with 4 actions all visible?

**Comment by ivanahuckova** [comment]
Also to provide context - the use case for "eye" button is to select only fields you are interested. This might be multiple fields and if we hide it behind the "dots", it becomes tedious to always click twice every time you want to hide/show field.

**Comment by svennergr** [comment]
@ivanahuckova @matyax 
image

We are going back to the `IconButton` then. As agreed we'll merge this for 9.5.0 and keep being on the lookout for impact.

**Review by svennergr — APPROVED** [review]

**Pull request merged**
