### PR TITLE
Add DoD review tasks to pr template

### PR DESCRIPTION
**Pull request by mjseaman**
**What is this feature?**

Adds a checklist for PR reviewers to make sure new features are tested, documented, placed behind feature toggles, pass the FRR, and if applicable include training for sales and support.

**Why do we need this feature?**

Many PRs are merged without accompanying docs, training, security, etc. This is a simple checklist for reviewers to consider these items when reviewing each PR. This is especially important as Grafana shifts to a continuous deployment model, where each PR can be deployed to users right away.

**Who is this feature for?**

PR reviewers.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tleopold** [comment]
"Check for compatibility issues with older supported versions of Grafana, and plugins"
I think we also need a "what to do" if compatibility issues are found.  E.g. if this is breaking change what should the reviewer be looking out for?  Have the breaking change been documented as such? Do we have customer info to let them know of this breaking change?  Is CS/CX aware of the breaking change and possible impacts to customers? etc

"Make sure the sales and support team has a training on this improvement"
'team has a' -> 'teams have'

Do we need a check for rollbacks?  i.e. can this change be easily rolled back and if not what are the impacts of rolling back?  This is especially important for DB migrations.

When turning on a feature by default is that the same as removing the feature toggle?  Might be worth spelling that out that if we a turning on a feature by default we also have to remove the feature toggle code and close any feature otggle management.

**Comment by mjseaman** [comment]
> Do we need a check for rollbacks? i.e. can this change be easily rolled back and if not what are the impacts of rolling back? This is especially important for DB migrations.

Agree. This is in the [feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) - do you think that's enough?

@bergquist brought up a good point as well - we could put some of this in the [deployment tools documentation](https://github.com/grafana/deployment_tools/tree/master/ksonnet/environments/hosted-grafana/waves/feature-toggles), where squads will switch on feature toggles. I'm removing some content here and will add it there.

**Review by bergquist — APPROVED** [review]
LGTM!

**Review by tleopold — APPROVED** [review]
This is great!  We need to re-enforce this with all reviewers to make sure they run through a proper review process

**Comment by supilee** [comment]
Sounds great and should be part of the overall QA framework. we just need to be careful on how to word the usage to the squads

**Pull request merged**
