### PR TITLE
Added a select box to templates that allows template values to be refreshed on refresh

### PR DESCRIPTION
**Pull request by mtanda**
Rebase https://github.com/grafana/grafana/pull/3507 by @NickG123.

@NickG123 I want this feature, so I rebase your change and create new PR.
If you rebase your PR, I'll close this PR.

### CODE REVIEW

**Comment by bergquist** [comment]
I'm assume 'On Time Change' reloads upon dash dashboard load as well? If so I don't think the UI is very clear about that.

**Comment by mtanda** [comment]
Yes, 'On Time Change' reloads upon dashboard load as well.
Should I change it like 'On Time Change and Dashboard Load', or simply 'Always'?

Or, add checkbox for each option and make 'On Time Change' doesn't reloads upon dashboard load?

**Comment by bergquist** [comment]
I think 'On Time Change and Dashboard Load' would be the best user experience.

**Comment by mtanda** [comment]
Thanks for suggestion! I update the option name.

**Comment by NickG123** [comment]
Hey @mtanda, this is great!  I don't really have time to maintain my pull request, but I would like to see this feature added, so with your approval I will close my PR in favor of this one.

**Comment by torkelo** [comment]
@bergquist it is looking ok:ish, just need to do some minor refactoring before merge

**Comment by mtanda** [comment]
rebase and fix some part of code.

**Comment by mtanda** [comment]
@NickG123 Okay, I continue to maintain this PR :-)
Thanks for your contribution, your code is a good start point for me!

**Comment by mtanda** [comment]
@torkelo minor refactoring is done. please check this :-)

**Comment by bergquist** [comment]
@mtanda for future ref. We are moving away from tight-form and have started using our own grafana version instead. so inputs should have gf-form-input https://github.com/grafana/grafana/commit/f0d1853a668c8d0db38f865b0fcf215eaa1ab053

Thank you both for making grafana better! :)

**Comment by torkelo** [comment]
hm.. had planned to refactor  this PR before merge, dont like the long strings that are used as option values

**Comment by mtanda** [comment]
@bergquist I got it! I'll use gf-form-input.
Thanks for merging this!

**Pull request merged**
