### PR TITLE
Alerting: Add imageURL for dingding notifier

### PR DESCRIPTION
**Pull request by Fury76**
Add imageURL for dingding notifier. to support dingding actionCard.
example:
image
image

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
@Fury76 thanks for your contribution. Please make sure that the build is green before we start reviewing.

**Comment by Fury76** [comment]
> @Fury76 thanks for your contribution. Please make sure that the build is green before we start reviewing.

I'm already fixed it. pls check it again, thank you!

**Comment by JohnnyQQQQ** [comment]
Thanks for fixing it, I added the experts of our team regarding images in notifications, they will review this soon.

**Comment by grobinson-grafana** [comment]
I'm not sure if we should add them to `data.Alerts` as then we would also have to make them templatable in all other channels to be consistent. Would it be possible to just add the images for the time being, there are a number of other channels that can be used for reference?

**Comment by Fury76** [comment]
I just referred to the implementation of webhook, which is the current implementation of webhook.

**Comment by Fury76** [comment]
btw, Can webhook support custom fields? And can use the template

**Pull request closed without merging**
