### PR TITLE
PluginsList: Improve layout for smaller screens

### PR DESCRIPTION
**Pull request by torkelo**
Slight design tweak to improve the plugin list view for smaller screens. 

* Use Select for type instead of a radio button with 4 large options (to wide for a radio group, think select is better)
* Adds field labels to all filter inputs to make it a bit more clear what they do

I get triggered a lot by the plugin list having a broken layout on 14" macbooks:

Before:
Screenshot 2023-01-10 at 15 25 42

After: 
Screenshot 2023-01-10 at 15 24 33

### CODE REVIEW

**Review by leventebalogh — APPROVED** [review]
Nice 👏

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Comment by torkelo** [comment]
@teddyba thought all plugins would go under connections, feels strange to split them into two different places?

**Comment by richardqlam** [comment]
> @teddyba thought all plugins would go under connections, feels strange to split them into two different places?

@torkelo As we talked about Connections more over time, it evolved more into "how do I interact with data as it comes into Grafana". Data sources definitely fit that mold, and apps usually do. There's wide agreement that panel plugins make more sense in the context of better belong directly in world of Visualizations/Dashboard, but no one's done the work to figure out _how_ this would look and work yet.

**Comment by torkelo** [comment]
@teddyba @richardqlam 

sure, but apps, panels, and data sources are all just plugins, so in terms of exploring and installing plugins, and the plugin details view with actions and plugin info seems like something we want some consistency in and not duplicated and spread out different areas. But maybe we can still have some consistency and sharing here even if they are in different areas. 

But it's going to be very blurry what goes into connections and what goes into Admin / Plugins. Think we will have many apps that will blur the line between integration and app. We will have many app plugins that embedded pre-built and connected dashboards.

**Pull request merged**
