### PR TITLE
Fix postgres datasource name

### PR DESCRIPTION
**Pull request by gsauthof**
**What this PR does / why we need it**: It fixes a trivial documentation copy'n'paste error.

**Which issue(s) this PR fixes**: n/a

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by daniellee — APPROVED** [review]
LGTM

**Comment by daniellee** [comment]
@gsauthof would you be able to sign the CLA?

**Review by achatterjee-grafana — APPROVED** [review]

**Comment by gsauthof** [comment]
> @gsauthof would you be able to sign the CLA?

That change is so trivial that any thresholds of creativity/originality required by copyright law aren't reached.

I usually only sign documents that I understand.
Currently, I don't understand your CLA.
And I don't really have the time nor patience right now to talk it over with a lawyer in order to understand its implications.

**Comment by RichiH** [comment]
@gsauthof based on my non-lawyer understanding of German copyright law you're correct, Schaffenshöhe Bordsteinkante, but Grafana is not a German company.

I can understand not wanting to read, parse, and think through the CLA for this change. The short version is "we can use and relicense what you submit", but still, understandable.

On the other hand, not having CLA on commits would put a large and unmaintainable burden on us long-term.

If you prefer not to sign the CLA, the easiest approach would be to close this PR and one of us makes the change ourselves. Would that be OK with you?

**Comment by gsauthof** [comment]
I doubt that the German copyright law is so special and that no other copyright law has similar provisions.

You know, there are better alternatives to CLAs. Most companies and projects don't require them for open source contributions for good reasons. See for example https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/ for some background.

I don't mind if you replicate that trivial change. It's your time you waste that way.

**Pull request closed without merging**
