### PR TITLE
DevEnv: update frontend dependencies - webpack

### PR DESCRIPTION
**Pull request by Estrax**
**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 12 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `webpack` - changes (4.29.6 -> 4.41.5): https://github.com/webpack/webpack/releases
- `webpack-cli` - changes (3.2.3 -> 3.3.10): https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md
- `file-loader` - changes (3.0.1 -> 5.0.2): https://github.com/webpack-contrib/file-loader/blob/master/CHANGELOG.md
- `css-loader` - changes (2.1.1 -> 3.4.2): https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md
- `sass-loader` - changes (7.1.0 -> 8.0.2): https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md
- `style-loader` - changes (0.23.1 -> 1.1.3): https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md
- `fork-ts-checker-webpack-plugin` - changes (1.0.0 -> 4.0.3): https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases

Changes - less significant:
- `webpack-dev-server` - changes (3.2.1 -> 3.10.3): https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md
- `terser-webpack-plugin` - changes (1.2.3 -> 2.3.4): https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/CHANGELOG.md
- `webpack-bundle-analyzer` - changes (3.3.2 -> 3.6.0): https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/CHANGELOG.md
- `webpack-merge` - changes (4.2.1 -> 4.2.2): https://github.com/survivejs/webpack-merge/blob/master/CHANGELOG.md
- `clean-webpack-plugin` - changes (2.0.0 -> 3.0.0): https://github.com/johnagan/clean-webpack-plugin/releases
- `mini-css-extract-plugin` - changes (0.5.0 -> 0.9.0): https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by tskarhed** [comment]
Any tips on commands I can run to verify this?

**Comment by dprokop** [comment]
Core:
- [ ] `yarn build` 
  - [ ] verify the built version is not broken
  - [ ] verify e2e are passing

Toolkit:
- I'll get back to you

**Comment by dprokop** [comment]
Also, this needs to be first synced wih master

**Comment by Estrax** [comment]
@dprokop synced

**Review by torkelo — APPROVED** [review]

**Review by dprokop — APPROVED** [review]

**Pull request merged**
