### PR TITLE
Provisioning: set stable datasource UID with provisioning

### LINKED ISSUE #41763: Provisioned datasources need a stable UID
**What happened**:

In 8.3, we are now using UID rather than name to reference datasources.  When a datasource is provisioned with only a name (and not a UID), it used to behave as a stable name in 8.2, but now gets a new UID with each restart :scream: 

**What you expected to happen**:

keep working like it did in 8.2

**How to reproduce it (as minimally and precisely as possible)**:

provision a datasource without uid, make a dashboard and then restart

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes: #41763

When the UID is not defined the backend will create a new one each time the system is deployed.  This will make the references within dashboards unstable now that we save the UID rather than the name.

----

:thinking: I bet this will break something with real systems in the wild.  This sets a UID if one does not exist -- but I don't fully understand what that will do with existing systems.  Are all the other operations by name?  (also unique?) if so is it ok?

Existing dashboards will be fine since the data-source is looked up by name

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
Looks ok, hard to fully grasp the implications. But better this than constantly changing UID

**Comment by marefr** [comment]
I guess for existing provisioned datasources (that already has a uid stored) will change the uid with these changes which might not be expected/great. But I might miss something with the changes just had a quick look

**Comment by marefr** [comment]
In addition. We probably also need to document and/or somehow recommend/make users aware that we recommend always specify a uid when provisoning datasources even though it's not required. 

In regards to allowing rename of datasource without making dashboards fail uid is important. Changing name of datasource currently using provisioning probably creates a new datasource which is very confusing - even if you have a uid specified 🤷 uid for datasources mainly introduced to support connecting logs to traces and so on, but wasn't fully implemented to support all different use cases with provisioning.

**Comment by ryantxu** [comment]
> that already has a uid stored

Yea -- this is where my head explodes a bit.  Without this change, the uid will change anyway -- it will just become random value rather than a predictable one. 

Is there special code that prefers the UID over name?  maybe we need to first delete things with a matching name?

**Review by malcolmholmes — APPROVED** [review]

**Comment by yuri-tceretian** [comment]
Apparently, it introduced quite a destructive side-effect.
If the provisioned file does not have UID and user upgrades from the previous version to 8.3, provisioning changes UID of existing data sources which breaks other services like alerting. 
Previously, empty UID was treated by XORM as an empty value and it omitted it from the UPDATE query, and therefore did not change it.

**Pull request merged**
