### PR TITLE
Chore: Aligning sample.ini with default ini for paths section

### LINKED ISSUE #62042: Config: the default (commented-out) values in `sample.ini` stray from the default values in `defaults.ini`
**What happened**:

I made a copy of `sample.ini` as `/etc/grafana/grafana.ini`, then looked through all the config options and uncommented those I wanted to customize. If the commented out value was what i wanted I left it alone.  However, in `sample.ini`, you have:

```ini
#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
;data = /var/lib/grafana

# Temporary files in `data` directory older than given duration will be removed
;temp_data_lifetime = 24h

# Directory where grafana can store logs
;logs = /var/log/grafana

# Directory where grafana will automatically scan and look for plugins
;plugins = /var/lib/grafana/plugins
```

but in `defaults.ini` its:

```ini
#################################### Paths ###############################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
data = data

# Temporary files in `data` directory older than given duration will be removed
temp_data_lifetime = 24h

# Directory where grafana can store logs
logs = data/log

# Directory where grafana will automatically scan and look for plugins
plugins = data/plugins
```

The relative paths in `defaults.ini` are getting appended to my `-homepath` so my runtime is definitely not what I expected.

**What you expected to happen**:

I would expect that the commented out values are exactly in line with the defaults. 

**How to reproduce it (as minimally and precisely as possible)**:

 Something like this should be an empty diff:

```bash
diff -u defaults.ini <(sed 's/^;//g' sample.ini)
```

Especially for values that matter:

```bash
(mitre-wsl-rocky9) ltheisen@MM269697-PC ~/egit/grafana-grafana/conf
$ diff -u defaults.ini <(sed 's/^;//g' sample.ini) 2>&1 | grep -A 19 '# Paths #'
-#################################### Paths ###############################
+#################################### Paths ####################################
 [paths]
 # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
-data = data
+data = /var/lib/grafana

 # Temporary files in `data` directory older than given duration will be removed
 temp_data_lifetime = 24h

 # Directory where grafana can store logs
-logs = data/log
+logs = /var/log/grafana

 # Directory where grafana will automatically scan and look for plugins
-plugins = data/plugins
+plugins = /var/lib/grafana/plugins

 # folder that contains provisioning config files that grafana will apply on startup and while running.
 provisioning = conf/provisioning
```

**Anything else we need to know?**:

Nope

**Environment**:
- Grafana version: master branch
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What is this feature?**

Aligning `sample.ini` to have the same values as defaults.ini for `paths` section.

**Which issue(s) does this PR fix?**:

Fixes: #62042

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ying-jeanne — APPROVED** [review]

**Comment by ying-jeanne** [comment]
I saw the ticket before, I am ok to align it, just normally after installation, grafana default log path is `/usr/local/var/log/grafana` so the origin sample.ini is aligned more with the default location. I am not familiar with this, would prefer someone else also give it a look.

**Comment by tolzhabayev** [comment]
yep, this PR is mostly to get feedback and see if this is a bad idea :)

**Comment by tolzhabayev** [comment]
maybe @torkelo can shed some light on if this is a good idea / change?

it seems to be like that for a while:
https://github.com/grafana/grafana/commit/d1767144a88afe42acafa9cddd7cc8e27665356a?diff=split#diff-3f8a56cf48f018d19dd5378a288ed6b9180d60ef82649c98339f93b3523bd7ceR9

**Comment by torkelo** [comment]
not sure this is a good idea: 
https://github.com/grafana/grafana/blob/main/packaging/deb/control/postinst#L31 

sample.ini is what we use for /etc/grafana/grafana.ini  and for deb/rpm these paths are correct

**Comment by tolzhabayev** [comment]
@torkelo got it, I will close this PR then.

**Pull request closed without merging**
