### PR TITLE
Explore: Reuse Dashboard's QueryRows component

### PR DESCRIPTION
**Pull request by Elfo404**
Removes Explore specific implementation and reuse the same QueryRows component from dashboards:
Screenshot 2021-09-14 at 14 12 15

## Noticeable behavior differences compared to the previous version:

1. It's now possible to remove ALL queries
   - This is consistent with dashboards edit, i'd keep this new behavior
1. Latency info has been removed. It wasn't very useful also given that more detailed performance info are shown in the inspector:
Screenshot 2021-09-10 at 14 37 27
Screenshot 2021-09-10 at 14 39 19
3. pre-emptive log highlight has been removed: this was implemented only by loki, it wasn't a documented feature and it doesn't add much value.
   - What was happening was that the logs panel was highlighting logs from the previously ran query when changing (without running) the current one based on the search expression. we felt this feature is barely used and not very useful. I'll follow up with a PR to deprecate the API in grafana and remove the implementation in Loki

https://user-images.githubusercontent.com/1170767/132863356-84ddbc15-1c45-40bc-8c58-a6cd3bc5ed0d.mov

## Issues

1. ~Graphite has a weird behavior (refId changing / editor freezing)~
   - This seems to be a graphite problem, @ifrost is investigating
1. ~Toggling the second query off and on makes it disappear~
   - This happened because when running queries (which happens when toggling one on) we were clearing queries if all of them were empty. this doesn't seem to be useful, so I changed in 426d307b80 so that they are not cleared anymore now.
   - note: this was also happening before when adding multiple empty queries and then removing one was removing all of them but one.
4. ~Removing the query doesn't remove existing logs results~
   - Fixed by 98b52d46e2, queries were being run again after removing a row
1. After copying the first row, drag & drop becomes super slow and laggy
   - when you start draggin there's always a bit of delay (this also happen in dashboards, even with empty queries). after copying thouh i suspect this is because of the amount of data being processed in the FE that is blocking the UI (either loki processing data or the panel rendering). i can also see it happening and doesn't seem related to the QueryRow component. cc @ifrost 

## TODO
 - [ ] Add tests
 - [x] Ref ids changes are not persisted
    - done in e2c4d53fb9
 - [x] add deprecation notice for `getHighlighterExpressions`
    - [x] add deprecation notice for `getHighlighterExpressions` in changelog
 - [x] add deprecation notice for `ExploreQueryFieldProps`
    - [x] add deprecation notice for `ExploreQueryFieldProps` in changelog

# Deprecation notice

`getHighlighterExpressions` in datasource APIs ( used to highlight logs while editing queries) has been deprecated and will be removed in a future release.

# Deprecation notice

`ExploreQueryFieldProps` interface for query editors has been deprecated and will be removed in a future release. Use `QueryEditorProps` instead.

### CODE REVIEW

**Comment by ivanahuckova** [comment]
When manually testing this, I've found following inconsistencies with previous QueryRow:
1. Log highlight - we talked about the fact that this could be probably removed
2. Removed latency
3. You are able to remove last query row. In current query row, you are not able to remove last query row. 
4. New query row has drag-drop function to reorder query rows. I was able to end up with this mixture:
- first row has prometheus name, but graphite editor
- second row has test data data source
I think it has something to do with graphite cause I was able to reproduce only with it. 

https://user-images.githubusercontent.com/30407135/132529431-3292ac45-1a9c-495e-bd0b-28082afc49b3.mov

5. When you have long query and you toggle-hide query row, the query is written in the row and makes whole Explore very long 

https://user-images.githubusercontent.com/30407135/132530581-0ab90f7e-189a-40a6-ae17-3f91e205c71d.mov

**Comment by ifrost** [comment]
A few issues:

**Loki** 

1) It happened only with empty queries. Toggling the second query off and on makes it disappear:

https://user-images.githubusercontent.com/745532/132828289-b833d98c-1dde-49d6-84f0-7a6bc04f0803.mov

---

2) Removing the query doesn't remove existing logs results (maybe the query is not run when a row is removed?)

See how changing visibility changes the graph/results but not removing the row:

https://user-images.githubusercontent.com/745532/132828443-22f17022-22df-4781-a702-b3501e5a91c3.mov

---

3) This seems to be happening only when there's a lot of logs entries rendered  (I had ~800). After copying the first row, drag & drop becomes super slow and laggy:


https://user-images.githubusercontent.com/745532/132829664-572d0bac-eaa5-4917-bde8-86ccb845ec2b.mov

---

**Graphite**

1) This might be something Graphite related so I can have a look what's causing it. When a new row is created and the order changes the RefID gets mixed up (see below how ref id changed to "B" in both rows):

https://user-images.githubusercontent.com/745532/132828766-ebf22b80-52f8-4abf-afb9-7326bc02f213.mov

what's more after switching to a different data source one of the Graphite query remains on the screen.

**Comment by torkelo** [comment]
This PR makes me so happy :heart:

**Comment by Elfo404** [comment]
Marking this as ready for review. 

I'd like it to get in before 8.2 but there are probably a couple of rough edges and some additional love might be needed here and there.

**Review by torkelo — APPROVED** [review]
Looks great! :rocket:

**Review by ivanahuckova — COMMENTED** [review]
Really good job on this!!! 👌 I was still able to reproduce

https://user-images.githubusercontent.com/30407135/132530581-0ab90f7e-189a-40a6-ae17-3f91e205c71d.mov

Otherwise LGTM! 🚀

**Comment by achatterjee-grafana** [comment]
Are there any doc changes or do only the change logs and release notes need an update? Thanks for any clarification.

**Comment by Elfo404** [comment]
@achatterjee-grafana there's only one docs change in `docs/sources/developers/plugins/add-support-for-explore-queries.md` , but I guess you were added as a reviewer because you are a codeowner for that file

**Comment by achatterjee-grafana** [comment]
> @achatterjee-grafana there's only one docs change in `docs/sources/developers/plugins/add-support-for-explore-queries.md` , but I guess you were added as a reviewer because you are a codeowner for that file

Sounds good. I just wanted to make sure we are not missing docs. Thank you!

**Comment by Elfo404** [comment]
@ivanahuckova I'll merge this one and I'll address the panel length issue in a follow-up pr. Thanks again for catching it!

**Pull request merged**
