### PR TITLE
Support auto grid min/max when using log scale

### LINKED ISSUE #3090: Support auto grid min/max when using log scale
When using log scale, it seems the auto grid min/max no longer works.

Here's an example graph using the default "auto" for the axis and a linear scale:

screen shot 2015-10-29 at 20 55 57

With the lowest value around 1.6s, the Y-axis naturally starts around 1s (not 0).

Here's another one:
screen shot 2015-10-29 at 21 02 20

But then when enabling the log scale, the graph essentially becomes unusable without some minimum value due to the long exponential onramp from 0 to 1 taking up the vast majority of the available screen space.

Log scale 2:
screen shot 2015-10-29 at 21 03 00

Log scale 10:
screen shot 2015-10-29 at 21 03 23

Log scale 1024:
screen shot 2015-10-29 at 21 03 09

I'm not sure if it's possible, but it'd be nice if it would result in something like this. (I've hardcoded a grid minimum of 300ms here).
screen shot 2015-10-29 at 21 04 57

---

Part of this was previously mentioned in #2829.

### PR DESCRIPTION
**Pull request by bigbenhur**
Fixes [Issue #3090 ](https://github.com/grafana/grafana/issues/3090)

For a logarithmic axis, it determines the min and max of the graph data series and sets grid min and max accordingly - if they have not been set by the user.

A few notes:
- For the min it rounds down to the next lower logBase factor and for the max it rounds up to have ticks at both ends of the axis while displaying the full data range. 
- It ignores data values and axis values <= 0, as only positive values can be properly displayed on a logarithmic axis. (The previous implementation also displayed zero values, but allthough it might be nice to look at, that was not a real logarithmic axis - at least not a scientific one. Also, this prevents displaying small values - which is an important feature on a logarithmic scale - as they cannot be distinguished from zero.)
- It introduces stats.logmin to determine the smallest positive value (the min for the log axis) of a data series.
- If the axis has no data series, the axis range is set to logBase^-2 .. logBase^+2, thus creating 5 ticks. (This is similar to the axis range -1 .. +1 in steps of 0.5 for the linear axis without data series.)
- The graph_spec tests had to be adjusted to reflect the changes noted above.
- Limitation: the current string conversion of small numbers is lacking: 0.000001 is not very readable. For logarithmic scales exponential notation (1e-6) would make sense. But that would be another feature request...

### CODE REVIEW

**Comment by torkelo** [comment]
looks ok, might need a few more unit tests

**Comment by bigbenhur** [comment]
@torkelo: cheers, do you mean more tests in graph_specs.ts? anything specific or just more tests? (e.g. log2, log32, non-positive numbers and other critical cases)

**Comment by torkelo** [comment]
Well tests that validate the auto ymax/ymin logic

**Comment by bigbenhur** [comment]
@torkelo: further tests are in place, what do you think?
unfortunately ci failed, but i don't think it's because of my code changes. any way to repeat the test or is it irrelevant?

**Comment by djahandarie** [comment]
@torkelo Any chance you could re-triage this since @bigbenhur's latest changes? I'd really like to see this merged in!

**Comment by MostAwesomeDude** [comment]
Hi, does this need more hands or eyeballs? I'm used to using logarithmic scales for working with latency and sadly I get stuff like this:
Somewhere between 1s and 0ns is good, I suppose…

**Comment by bigbenhur** [comment]
@MostAwesomeDude: The current implementation only works for values greater or equal to 1. The patch proposed in this thread would fix this. However, so far it was not merged into the release branch. I don't know exactly why, probably because of lack of interest (from users and/or developers).

**Comment by nagimov** [comment]
Hi, there! Is anyone looking into this? Any chances to merge @bigbenhur's changes anytime soon? I see lots of grafana users from science/engineering labs working with vacuum stuff and asking for log charts with values like `5e-10`. Seems to be pretty useful to me.
Regardless of the final use-cases, log charts as they are right now should be fixed anyways, since they're displayed incorrectly for any values lower than 1.

**Comment by torkelo** [comment]
>  since they're displayed incorrectly for any values lower than 1.

what do you mean?

**Comment by nagimov** [comment]
@torkelo I'm talking about handling values lower than 1.

Here's the example of the log (base 10) chart:
2017-03-08 00_35_03-grafana - isac cryoplants

Log chart shouldn't ever display zeros...

**Comment by torkelo** [comment]
So how should that look? Have not reports on it being wrong

**Comment by nagimov** [comment]
As I see it now (I'm on version 4.1.1) scaling of log charts is only handled properly for values greater than 1.

Example for auto scaling: lowest value is 0 (wrong, log charts shouldn't display zeros):



Examples for custom lower values (spacing in between y axis grid is wrong):

 

It seems to me (from the discussion above) that @bigbenhur's PR is supposed to fix that?

**Comment by bigbenhur** [comment]
Here's an example (using my fix) showing a proper result:
image
The plot shows data in the range from 1e+4 (i.e. 10000) to 1e-7 (i.e. 0.0000001).

The current implementation has a few issues, e.g.
1. The conversion from lin to log adds 0.1 to the value before conversion to log. No matter how small the value is, with 0.1 added to it it's never smaller than 0.1 and thus values like 0.0001 do not show correctly.
2. The 0.1 value is (mis-)labeled as "0" on the y-axis. But zero cannot exist on a pure log axis (as stated by nagimov).
3. Zero and negative values are not properly handled: They cannot be ploted on a log scale and need to be excluded from plotting.

Please let me know if you need more info.

**Comment by nagimov** [comment]
@bigbenhur [off-topic] what data backend do you use? I struggle with zabbix and its 16,4 float precision, so I have to convert readbacks from vacuum sensors on the fly
Also, is that a standard grafana feature used on you pump-out graph displaying green and red pressure ranges?

**Comment by bigbenhur** [comment]
@nagimov: I use python to collect data from vacuum sensors and to put it into influxdb. (I did not encounter any precision bottlenecks.) And yes, it's a standard feature, but I'm currently away and cannot remember how... ...sorry!

**Comment by bigbenhur** [comment]
@torkelo : Should I open a new issue for values<1 being plotted wrong in log scale?
I was hoping to implement the auto log scaling ([Issue #3090](https://github.com/grafana/grafana/issues/3090)) at the same time. But if this is only a "nice to have" and keeps the values<1 bug from being fixed, I'd rather have this fixed seperately.

**Comment by torkelo** [comment]
@bigbenhur thanks for showing whats was wrong for the low values. I see now what you mean. Does this PR already include the fix for values below 1? if you can fix that issue in this PR as well I can see that we can have this merged within a few days. Think having good log scale support is important as more more use Grafana in scientific computing scenarios where good log scale is important (it has it uses outside scientific computing as well). 

there looks to be some merge conflicts with master, can you do a rebase on master when you are at it?

**Comment by bigbenhur** [comment]
@torkelo Yes, this PR includes the fix for values < 1. I can try to rebase on master, but I'm currently away - so it will take at least a week. (If somebody else wants to do it in the meantime, feel free and please leave a note.)

**Comment by torkelo** [comment]
Ok, we might have time to do the rebase and merge  fix

**Comment by daniellee** [comment]
I've pushed a branch -> https://github.com/grafana/grafana/commits/bigbenhur-autologscale, where I merged in the latest master. 

`graph.js` has been upgraded to graph.ts (js to TypeScript) since this PR was submitted (our fault). I did think about rebasing like in this answer from [StackOverflow](http://stackoverflow.com/a/15137607/22688) but went with a merge instead.

After the merge, the tests failed due to other changes in graph.ts. I fixed the following:

- Fix for min and max that were not getting passed into the applyLogScale function
- Fix for when min/max were undefined rather than null
- Fix for decimal ticks, as this PR populates the ticks itself then it also needs to calculate the number of decimal places too. Flot was showing the wrong number of decimal places sometimes otherwise
on the y-axis.

Any other changes we need to make before merging?

**Comment by bigbenhur** [comment]
@daniellee I haven't compiled/tested it, but it looks good. Thanks for your time and I'm looking forward to the next release.

**Comment by bigbenhur** [comment]
@daniellee I finally got around to test it and it looks fine. Thanks for your work!
One issue with the number of decimal places: when scientific notation is used (common for log scales) the number of decimals needs to be calculated differently.
Example: 1e-9 is shown as 1.000000000e-9, which IMHO is too much. If the axis spans more than one order of magnitude 1 or even 0 decimal places are sufficient.
Maybe there is a way to get this change done without a bug report or feature request?

**Comment by torkelo** [comment]
this seems to have introduced a number of strange bugs, Y axis ticks below y-axis and graph plots below y-axis, might have to revert

image

**Comment by bigbenhur** [comment]
@torkelo Thanks for fixing this!
There is still a problem with the axis numbering (precision) for very small numbers:
image
The reason could be in function decimalPlaces(num):
for num=1e-6: num.toString() returns '0.000001' (ok)
for num=1e-7: num.toString() returns '1e-7' (not '0.0000001' as expected by the author)

**Comment by torkelo** [comment]
thats strange, unable to replicate that in latest master / v4.3.x branch:

image

**Comment by bigbenhur** [comment]
@torkelo your plot values are not small enough. Alternatively, just set Y-Min to 1e-7 - it's the same thing.

**Pull request merged**
