### PR TITLE
Devenv: fix prometheus scrape ips

### LINKED ISSUE #23846: Devenv: fix prometheus scraping
**What happened**:

Prometheus scraping in devenv doesn't work as that links to localhost.

**What you expected to happen**:

scrape should point to the docker container

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The bug was introduced in #23321

### PR DESCRIPTION
**Pull request by xlson**
**What this PR does / why we need it**:

Makes sure we scrape the right IPs in our devenv configs for prometheus. Also removes the mac specific docker block as the default one is now compatible with mac.

**Which issue(s) this PR fixes**:

Fixes #23846

**Special notes for your reviewer**:

Afaik there's no good way to fix the grafana scrape on localhost so I changed the config so that it will try to scrape the grafana running in devenv instead. Is that ok? There are potential workarounds if it's important that we solve it.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
Great :+1:

**Review by bergquist — APPROVED** [review]
Thanks :)

Scraping the grafana instance running in devenv should be fine.

**Comment by torkelo** [comment]
this breaks prometheus scraping my local dev grafana instance

**Comment by torkelo** [comment]
@xlson 

> Afaik there's no good way to fix the grafana scrape on localhost so I changed the config so that it will try to scrape the grafana running in devenv instead. Is that ok? There are potential workarounds if it's important that we solve it.

Absolutely not, we all run & develop grafana normally. Super rarely do we develop and run grafana inside docker

**Pull request merged**
