### PR TITLE
Transformation redesign

### PR DESCRIPTION
**Pull request by LudoVio**
**What is this feature?**

This is a redesign of the tranformation tab

**Why do we need this feature?**

User have a hard time finding the right transformation

**Who is this feature for?**

It will be enabled only on Grafana cloud for now

Current tab:
Screenshot 2023-06-16 141405

This PR:
Screenshot 2023-06-16 141500

### CODE REVIEW

**Comment by LudoVio** [comment]
I put that on pause to divide it in multiple smaller PR

**Comment by LudoVio** [comment]
for grafana-ui: https://github.com/grafana/grafana/pull/70245

**Comment by LudoVio** [comment]
For static data about transformations (categories and images):
https://github.com/grafana/grafana/pull/70247

**Comment by catherineymgui** [comment]
Noticed some things along the stuff we talked about re: toggle, descriptions

- [ ]  Content on the page: Could the description always be 8px from the header? (regardless of how much text there is)? And the images are always aligned to the bottom (8px)?

Screenshot 2023-06-27 at 20 30 51

- [ ]  In some cases there’s no padding b/w the Beta badge and the title of the transformation
Screenshot 2023-06-27 at 20 31 27

- [ ] The transformations text + external link icon is responding weirdly on smaller screen sizes
Screenshot 2023-06-27 at 20 33 14

- [ ]  Have 16px margin b/w the rows of transformations

**Pull request closed without merging**
