### PR TITLE
chore: move notifications models into notifications service

### PR DESCRIPTION
**Pull request by mildwonkey**
* renamed pkg/models/notifications.go -> pkg/services/notifications/models.go
* updated references

Corresponding enterprise PR [here](https://github.com/grafana/grafana-enterprise/pull/4321)

### CODE REVIEW

**Review by gotjosh — CHANGES_REQUESTED** [review]
Hi @mildwonkey, thank you for the PR. Could you please explain the reasoning for this?

**Comment by mildwonkey** [comment]
yep @gotjosh - the backend platform squad is moving all models out of the `models` package and into the services that are responsible for them. It's a continuation of the larger project to ensure that service packages contain all the related code: models, api, backend service, store (db layer), etc.

**Comment by mildwonkey** [comment]
All the grafana enterprise PR tests have passed, just not all at the same time 🙄 . I'll keep smashing "restart" till they all pass at once.

**Review by gotjosh — APPROVED** [review]
ty LGTM

**Review by zserge — APPROVED** [review]

**Pull request merged**
