### PR TITLE
FeatureToggles: Support changing feature toggles with URL parameters

### PR DESCRIPTION
**Pull request by ryantxu**
Many feature toggles only apply on the frontend, but require config changes (and restart!) for them to change in the frontend.  This makes it difficult to evaluate if having a toggle on/off makes a difference.

In a few recent PRs, I have explored ways to short-circuit the behavior on demand.  See [#50273](https://github.com/grafana/grafana/pull/50273/files#diff-8e6d1dc8bffebb9fc6d982a51a284e963b36aefdd18a58451fff8abb47068db5R158), [#50229](https://github.com/grafana/grafana/pull/50229/files#diff-bed0eb36cf9df576f54bfe8f0e0d9d63708098ea51076207010bcd22555fec45R85), and the already committed hack to switch search index implementation.

This PR proposes a consistent way to change the configured toggle on startup,

http://localhost:3000/?orgId=1&search=open&__feature.panelTitleSearch=false
vs
http://localhost:3000/?orgId=1&search=open&__feature.panelTitleSearch=true

To make it clear we changed something, I added a notice... but not sure that is a great idea: 

Maybe: 
image

NOTE:
This will only work for frontend toggles -- In general that should be OK because any destructive changes should have backend flags as part of them.

### CODE REVIEW

**Comment by dprokop** [comment]
I would put a human-readable feature name instead of `featureFlag = bool` in the notification IF this is supposed to be used by a wider audience. 
If it's only for dev purposes, this looks good.

**Review by torkelo — APPROVED** [review]
pushed a minor refactoring that uses URLSearchParams, cleaned up the logic a bit.

This feels like mostly a a dev feature so wondering if the notification is needed and we can just do console log instead, will get rid of the need to do a timeout and wait for app to boot

**Review by axelavargas — COMMENTED** [review]
👋🏾  I have a noob question 🙈, how can I know which feature toggles are backend only, frontend only, or both? I was testing this PR with the `previewDashboards` feature toggle and I got the frontend changes, but as soon as I refreshed the page, the toggle was enabled again.

**Comment by torkelo** [comment]
@ryantxu think this is good to merge

**Pull request merged**
