### PR TITLE
Phlare: Support both Phlare and Pyroscope backends and rename to Grafana Pyroscope

### PR DESCRIPTION
**Pull request by aocenas**
Goal is to support both Phlare and Pyroscope backend as a transition step towards new unified profiling backend. To that end this introduces number of changes:

- Adds a Pyroscope client implementation to the data source backend supporting the same functionality as Phlare.
- Adds a select in the data source config to select the backend type between Phlare/Pyroscope with autodetection
- Renames the data source to Grafana Pyroscope

Screenshot from 2023-04-25 14-25-47

Screenshot from 2023-04-25 14-48-31

TODO for future PRs:
- Rename phlare naming in the code

### CODE REVIEW

**Review by petethepig — APPROVED** [review]
Found a little bug (attached a video), other than that it looks and works really well — great job!

https://user-images.githubusercontent.com/662636/233481706-ebb2a16a-514f-4213-914f-434765b7efdc.mov

**Review by cyriltovena — APPROVED** [review]
LGTM

**Review by joey-grafana — APPROVED** [review]
LGTM nice work! 👍 

Nit adding a section heading in the config or removing the extra space between minimal step and backend type would improve the UI. Also, the error message if I select Pyroscrope but don't have it running is perhaps not best err message we could show the user.

Screenshot 2023-04-25 at 12 33 55

**Comment by aocenas** [comment]
@joey-grafana going to merge this right now, will take a look at it in separate PR later on.

**Pull request merged**
