### PR TITLE
Karma to Jest: singlestat

### PR DESCRIPTION
**Pull request by tskarhed**
Ref #12224 
There seemed to be an issue with setting `ctx.ctrl.panel`, as it somehow is shared across tests (rather than being instance-specific). By changing it in one test, it might end up breaking other tests.

### CODE REVIEW

**Comment by dehrax** [comment]
Any idea on hwo to handle the error?
```
>> (node:157) UnhandledPromiseRejectionWarning: TypeError: this.events.emit is not a function
>> (node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
>> (node:157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> (node:157) UnhandledPromiseRejectionWarning: TypeError: this.events.emit is not a function
>> (node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
>> (node:157) UnhandledPromiseRejectionWarning: TypeError: this.events.emit is not a function
>> (node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
It is probably due to some mock, but everything still works.

**Comment by dehrax** [comment]
(All tests pass locally)

**Comment by marefr** [comment]
Still failing test

```
>> FAIL public/app/plugins/panel/singlestat/specs/singlestat.jest.ts
>> ● SingleStatCtrl › showing last iso time instead of value › should set formatted value
>> 
>>     expect(received).toBe(expected) // Object.is equality
>>     
>>     Expected value to be:
>>       true
>>     Received:
>>       false
>> 
>>       88 | 
>>       89 |     it('should set formatted value', function() {
>>     > 90 |       expect(moment(ctx.data.valueFormatted).isSame('2017-09-17 09:56:37')).toBe(true);
>>       91 |     });
>>       92 |   });
>>       93 | 
>>       
>>       at Object.<anonymous> (public/app/plugins/panel/singlestat/specs/singlestat.jest.ts:90:77)
```

Probably a timezone issue. Make sure you're always comparing UTC times. Think it's moment.utc(date) or moment(date).utc().

**Review by marefr — APPROVED** [review]
Looks good :+1:

**Pull request merged**
