### PR TITLE
Dependency: Bump crewjam/saml to the latest master

### PR DESCRIPTION
**Pull request by gotjosh**
We've (the Enterprise team) have made a change in our SAML library https://github.com/crewjam/saml/pull/226 which we need to unblock some work.

I'm a bit surprised this is the output of running:

```bash
$ GO111MODULE=on go get github.com/crewjam/saml@master
go: finding github.com/crewjam/saml master
```

According to [go mod documentation on upgrading and downgrading dependencies](https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies) `go get` will also update direct and indirect dependencies. 

In my eyes, this is a bit scary considering I've now updated very unrelated dependencies such as `prometheus/common` and `prometheus/go-client`

### CODE REVIEW

**Comment by gotjosh** [comment]
Turns out (thanks @xlson) that `golangci-lint` (which crewjam/saml depends on) is the culprit.

**Comment by gotjosh** [comment]
Turns out (after an investigation from @xlson) that `crewjam/saml` has incorrectly added `golangci-lint` to their `go.mod` file when it shouldn't be there. As, this is not a runtime dependency.

**Comment by xlson** [comment]
Hopefully, we can get this PR t(https://github.com/crewjam/saml/pull/228) that removes the `golangci-lint` dependency merged quickly.

**Comment by gotjosh** [comment]
Updated and good for a review!

**Review by xlson — APPROVED** [review]
LGTM!

**Pull request merged**
