### PR TITLE
Build: Remove redundant build_npm_packages_step

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Removes old NPM build scripts that have been superseded by the `build-frontend-packages` step.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dsotirakis — APPROVED** [review]
🚀

**Comment by AgnesToulet** [comment]
Please note that this PR was not included in the v8.5.x branch. If it's backported to v8.4.x branch, I think it should be backported to v8.5.x branch as well.

**Comment by dsotirakis** [comment]
@AgnesToulet it is included, since we branched off from main!

```
$ git log
commit a1ebcd520cdb63f1a52f858e53a1448fae3c3787 (HEAD -> v8.5.x, origin/v8.5.x, origin/main, grafana/main, main)
Author: Jack Westbrook <jack.westbrook@gmail.com>
Date:   Wed Apr 6 14:26:59 2022 +0200

    Build: Remove redundant build_npm_packages_step (#47384)
```

**Comment by dsotirakis** [comment]
@AgnesToulet it is included, since we branched off from main!

```
$ git log
commit a1ebcd520cdb63f1a52f858e53a1448fae3c3787 (HEAD -> v8.5.x, origin/v8.5.x, origin/main, main)
Author: Jack Westbrook <jack.westbrook@gmail.com>
Date:   Wed Apr 6 14:26:59 2022 +0200

    Build: Remove redundant build_npm_packages_step (#47384)
```

**Pull request merged**
