### PR TITLE
Core: Suggestion of how we could improve the scoped event bus

### PR DESCRIPTION
**Pull request by mckn**
**What is this feature?**

This is a suggestion of how we can improve the current scoped event bus to also support some of the use case we would like to provide to plugin developers.

I have added the following capabilities:

- When you create your scoped event bus you can provide two kinds of filters.
   - Subscription filter that will control which events that can be consumed via the event bus.
   - Publish filter that will control which events that can be published and also in what scope.
- The filters are not provided as enums but rather functions. So the consumer of the event bus can either use any of the pre-baked functions or write their own filter function.
- If you removeAllListeners from a scoped event bus it will only clear the subscriptions to that event bus and not all subscriptions to the global event bus.

**Why do we need this feature?**

We would like to expose a scoped event bus to plugins that have limited capabilities. The plugin should be able to publish events internal to the plugin but we would probably want to limit which events the plugin can publish to the global scope. 

The same goes for which events the plugin author can subscribe to. They should not be able to listen to other plugins events or some of the core events in Grafana that might contain sensitive information.

**Who is this feature for?**

Plugin developers

**Special notes for your reviewer:**

This is just a draft PR opened to get early feedback on a suggested solution. Let me know if I should add a couple of tests to provide examples on how it is supposed to be used.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
@mckn can you describe where / how you want to expose it to plugins? Via plugin context? 

what are the use cases?

**Comment by mckn** [comment]
> @mckn can you describe where / how you want to expose it to plugins? Via plugin context?
> 
> what are the use cases?

Sorry for the late reply. I got sick after the offsite and then AFK on holiday.

We could probably expose this via the sandbox so we provide a restricted event bus to plugins. That would result in us swapping the other event bus with a scoped event bus during runtime before it is being passed to the plugin realm.

Regardless how we do it the goal is to have a mechanism to limit what kind of events a plugin both can subscribe to and publish. Both from a UX and security perspective. With something like the suggestion in this PR we can white list which events a plugin should be able to publish/subscribe to a "global" scope and which only should be published to the plugins own scope.

Does this make sense?

**Comment by mckn** [comment]
> > @mckn can you describe where / how you want to expose it to plugins? Via plugin context?
> > what are the use cases?
> 
> Sorry for the late reply. I got sick after the offsite and then AFK on holiday.
> 
> We could probably expose this via the sandbox so we provide a restricted event bus to plugins. That would result in us swapping the other event bus with a scoped event bus during runtime before it is being passed to the plugin realm.
> 
> Regardless how we do it the goal is to have a mechanism to limit what kind of events a plugin both can subscribe to and publish. Both from a UX and security perspective. With something like the suggestion in this PR we can white list which events a plugin should be able to publish/subscribe to a "global" scope and which only should be published to the plugins own scope.
> 
> Does this make sense?

Another thing that I would like to extend this work with is to reference meta data from the source. This would make it possible to track the origin form an event and make filtering on the consumer side of the events as well.

@torkelo did my previous comment make sense?

**Comment by torkelo** [comment]
@mckn not really, I am still a bit confused. where would we want to use this? The eventBus we pass to PanelProps? I think we can come up with a much simpler scoping mechanism there (maybe with an option to bubble events). 

> The plugin should be able to publish events internal to the plugin but we would probably want to limit which events the plugin can publish to the global scope.

If they want internal events, why can't the plugin create it's own bus (by just newing up EventBusSrv exposed in grafana/data)? 

We should identify any need/use of appEvents and figure out if there is not a better more idiomatic react way to do that. 

The only real use of events from plugins I can think of is panels communicating with other panels via the data hover events, and for this they use the eventBus passed via panelProps or pane context

**Comment by mckn** [comment]
> @mckn not really, I am still a bit confused. where would we want to use this? The eventBus we pass to PanelProps? I think we can come up with a much simpler scoping mechanism there (maybe with an option to bubble events).
> 
> > The plugin should be able to publish events internal to the plugin but we would probably want to limit which events the plugin can publish to the global scope.
> 
> If they want internal events, why can't the plugin create it's own bus (by just newing up EventBusSrv exposed in grafana/data)?
> 
> We should identify any need/use of appEvents and figure out if there is not a better more idiomatic react way to do that.
> 
> The only real use of events from plugins I can think of is panels communicating with other panels via the data hover events, and for this they use the eventBus passed via panelProps or pane context

I now realise that I'm explaining this wrong or that we approach this with different point of views. Sorry about that 🙏🏻 
I would argue that the most common usage of the appEvents in plugins is to trigger behaviour in Grafana core such as display an alert, refresh a dashboard etc. There are few plugins, that I know of, that use the eventBus for other things. The goal with this suggestion is not to optimise performance but to limit access to what behaviour a plugin author can trigger in Grafana core. I guess the use case is similar as with the Sandbox. There are no plugin developers that request this but something we probably should do to prevent plugin developers from doing unwanted things.

This was just a suggestion and I'm all ears if you can think of better ways to approach this without introducing too many breaking changes 🙏🏻

**Pull request closed without merging**
