### PR TITLE
Alerting: use hash of labels instead of labels string as the alert state cache key

### PR DESCRIPTION
**Pull request by alexander-akhmetov**
**What is this feature?**

This reduces memory usage when there are many alert instances. It changes the alert state cache key from a string of labels and values to a hash of the same string.

**Why do we need this feature?**

State manager keeps alert rule state in memory in a map: https://github.com/grafana/grafana/blob/3237fc1cc2325cd62c85c89e6fd76f4f2e6d6b8e/pkg/services/ngalert/state/cache.go#L22-L29

Currently, the keys of this map are strings that contain labels of AlertInstances:

https://github.com/grafana/grafana/blob/3237fc1cc2325cd62c85c89e6fd76f4f2e6d6b8e/pkg/services/ngalert/state/manager.go#L188

The key can be pretty big for rules with many labels:

```
cacheID="[[\"__alert_rule_namespace_uid__\",\"some-uid\"],[\"__alert_rule_uid__\",\"some-uid\"],[\"__grafana_autogenerated__\",\"true\"],[\"__grafana_receiver__\",\"grafana-default-email\"],[\"__name__\",\"my_metric_total\"],[\"alertname\",\"test rule\"],[\"grafana_folder\",\"folder 1\"],[\"job\",\"integrations/statsd\"],[\"label-1\",\"some label value\"],[\"label-10\",\"some label value\"],[\"label-11\",\"some label value\"],[\"label-12\",\"some label value\"],[\"label-13\",\"some label value\"],[\"label-14\",\"some label value\"],[\"label-15\",\"some label value\"],[\"label-2\",\"some label value\"],[\"label-3\",\"some label value\"],[\"label-4\",\"some label value\"],[\"label-5\",\"some label value\"],[\"label-6\",\"some label value\"],[\"label-7\",\"some label value\"],[\"label-8\",\"some label value\"],[\"label-9\",\"some label value\"]]"
```

**Who is this feature for?**

This PR changes the `cacheID` from being a list of labels to the hash of the same list, so it looks like this:

```
cacheID=a5994ae58db743a87b108bd6ea9c8b054b595b2b
```

This reduces memory usage when there are many alert instances. It doesn't add any new risk of hash collision, `(rule_org_id, rule_uid, labels_hash)` is already the primary key of the `alert_instance` table.

<details>
  <summary><b>Memory usage graphs</b></summary>

**Four pods, two before the change and two after the change, 400 alert instances each**
image

**localhost, three tests, 20k alert instances**
main branch first, then the change, then the main branch again, etc.

Screenshot 2024-06-10 at 10 25 00
</details>

**Which issue(s) does this PR fix?**:

n/a

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by yuri-tceretian — APPROVED** [review]
LGTM. However, we can improve it further and avoid serialization to calculate the hash. We can use `data.Labels.Fingerprint` which is much more effective.

**Comment by alexander-akhmetov** [comment]
Thanks! Updated to use `data.Labels.Fingerprint`

**Review by yuri-tceretian — APPROVED** [review]
LGTM! Great change!

**Pull request merged**
