### PR TITLE
Chore: Introduce LibrarySrv for interacting with library panels API

### PR DESCRIPTION
**Pull request by kaydelaney**
**What this PR does / why we need it**:
Introduces a new frontend service "LibrarySrv", for interacting with the library panels API.
See also, https://github.com/grafana/grafana/pull/30653

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
not sure this should be a core service, and no need to follow the service class pattern & getLibrarySrv etc here (that is a relic from angularjs services). 

I think it's better to put this as just straight exported functions in features/library-panels/state/api.ts 

similar to https://github.com/grafana/grafana/blob/master/public/app/features/admin/state/apis.ts

**Review by hugohaggmark — COMMENTED** [review]
I agree with Torkel, I think it's better to export the functions. Maybe even as thunks and if we're thinking of having a separate Redux state for Library Panels?

**Comment by kaydelaney** [comment]
Changed to just export the functions themselves.

**Review by torkelo — APPROVED** [review]

**Review by hugohaggmark — APPROVED** [review]
LGTM 🎉 !

**Comment by torkelo** [comment]
Good progress! 

Some point (that can be done in follow-up PRs)
* No Apply button for a library panel (should only be an option to Save or Discard, Esc should open modal so user can choose to discard or save). So no way to leave library panel edit without saving or discarding changes

Add panel view:
* The padding is not aligned (same left and right)
Screenshot from 2021-02-12 15-28-50

The library panel view:

* The heading "Popular panels from the panel library"  should be above the filter & search inputs 
* The `Create new reusable panel`  is something we can wait with I feel to follow-up PR as that requires special logic for discard (needs to delete panel) 

Screenshot from 2021-02-12 15-23-40

**Comment by torkelo** [comment]
ah, sorry the ^ above comment was on the wrong PR

**Review by dprokop — APPROVED** [review]
@kaydelaney looks great with the functions instead of service class!

**Pull request merged**
