### PR TITLE
Tracing: Fix the event attributes in opentelemetry tracing

### PR DESCRIPTION
**Pull request by ying-jeanne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #54104

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ying-jeanne** [comment]
tested with jaeger, after the code, db query is showing correctly.

**Review by marefr — APPROVED** [review]
LGTM 🙏 milestone/backport label looks wrong. This should probable have add to changelog label since it's a bug fix

**Comment by ying-jeanne** [comment]
> LGTM 🙏 milestone/backport label looks wrong. This should probable have add to changelog label since it's a bug fix

The origin tracer seems implemented on v8.4, I saw some other fix/PR on v9. kept for v9 for now.

**Comment by marefr** [comment]
@ying-jeanne hmm since we have released v9.1.x now not sure there will be any 9.0.x releases except security related. Next one 9.1.2 maybe?

**Pull request merged**
