### PR TITLE
Graphite: Migrate to React (part 2: migrate smaller AngularJS directives)

### PR DESCRIPTION
**Pull request by ifrost**
**What this PR does / why we need it**:

Follow-up on #36484 and plan described in #36481. This PR converts a few smaller AngularJS directives used in Graphite to React:

* `<input...>` used as a text editor --> `GraphiteTextEditor`
* `<a ng-click="ctrl.unpause()"...>` --> `PlayButton`
* `<span graphite-add-func></span>` --> `AddGraphiteFunction`

Screen Shot 2021-07-15 at 14 25 20

On top of that more typings clean-up:
* `FunctionDescription` removed and exiting `FuncInstance` is used (they represented the same thing)
* more type definitions in `gfunc`

@grafana/grafana-frontend-platform Also to make the Segment a bit more usable I added `minInputWidth`, without it the input stays at very small width when the value is not defined and it's not visible what's typed inside, like below:

function

**Special notes for your reviewer**:

Depends on https://github.com/grafana/grafana/pull/36484

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Think this looks good!

**Comment by torkelo** [comment]
But I have not tested it :) just scanned the code

**Review by ivanahuckova — COMMENTED** [review]
Code looks *chefs kiss*. Good job! I went trough the manual test that you have listed and found out issues in: 
1. **Tags > change tag value to "dc =~ .*u.*"** didn't return any results:
image
But when I typed `('dc=~.*u.*', 'name=servers.requests.count')` and toggled it, it worked:
image

2. **Adding functions > add a function "aliasByTags"** added 2 functions - alias and aliasByTags:
image

3. **Adding functions > aggregate** Same as above:
image

**Adding functions > change last function param to "aliasByTags(aggregatedBy)"** mentioned bug is not there anymore
image

Otherwise everything worked as expected.

**Comment by ifrost** [comment]
> Code looks _chefs kiss_. Good job! I went trough the manual test that you have listed and found out issues in:

Thanks a lot @ivanahuckova for having a look at it 🙏 
 
> 1. **Tags > change tag value to "dc =~ ._u._"** didn't return any results:
>    ...
>    But when I typed `('dc=~.*u.*', 'name=servers.requests.count')` and toggled it, it worked:
>    ...

When tags are entered the editor is "paused" and the query is run only when "play button" is clicked. This is something we have only in Graphite, because querying for tags with no values results in an error.

> 2. **Adding functions > add a function "aliasByTags"** added 2 functions - alias and aliasByTags:
>   ...
> 3. **Adding functions > aggregate** Same as above:
> ...

This was caused a bug in `Select` component that was fixed in: #36905. It's now synced with this branch.

> **Adding functions > change last function param to "aliasByTags(aggregatedBy)"** mentioned bug is not there anymore
> ...

Oooh 👍 I think this is still a bug it happens only when both params are entered as one as in you just type `dc,server` (with comma) and the editor splits it into two parameters. I'll mention that in manual test scenarios.

**Comment by ivanahuckova** [comment]
@ifrost I have pulled the latest changes but I am still getting that error with Select. 

https://user-images.githubusercontent.com/30407135/126295632-03db4b29-62a4-4425-8d4d-b4208eac77c1.mov

**Comment by ifrost** [comment]
> @ifrost I have pulled the latest changes but I am still getting that error with Select.
> 
>  Screen.Recording.2021-07-20.at.11.15.33.mov

kmn

I didn't push the changes... 🤦 Should be good now :)

**Review by ivanahuckova — APPROVED** [review]
LGTM! Awesome work! Great test scenarios!

**Pull request merged**
