### PR TITLE
Explore: Make the split resizable

### PR DESCRIPTION
**Pull request by davkal**
- adds Resizable to Explore's Wrapper
- had to use percentages to keep panes widths non-absolute
- min width is 30%, max width is 70%

https://user-images.githubusercontent.com/859729/157470087-a73043a5-9c2a-4cc8-8710-f62c486e282d.mov

### CODE REVIEW

**Review by ifrost — CHANGES_REQUESTED** [review]
Looks really cool 🚀 

One thing, not sure why it's happening but after the split the left panel seems to have incorrect height:

https://user-images.githubusercontent.com/745532/158143025-8d3322e6-954d-44a8-ad06-616c5f75124e.mov

I can reproduce it in Chrome and Firefox like in the video - just showing random data and then splitting.

**Comment by gelicia** [comment]
I like the visual aspect of the handle, but limiting the click target for resizing to that handle can be tough to see if the height of the page is a lot and your window is comparatively small. The handle is centered to the height of the column and so it can show a little or not at all. @ifrost this fixes the height bug you found. Wondering what you think about the handle? 

Screen Shot 2022-03-18 at 7 59 10 AM

**Comment by ifrost** [comment]
Maybe we could do something similar to what we have in Dashboards?

panel

**Comment by gelicia** [comment]
> Maybe we could do something similar to what we have in Dashboards?

Did some investigation on this... Good news, that exists as a component already in `SplitPaneWrapper`: https://github.com/grafana/grafana/blob/main/public/app/core/components/SplitPaneWrapper/SplitPaneWrapper.tsx 
Bad news, it's only used in the edit panel section right now and doesn't work out of the box with Explore like the `resizable` library does. This is a pretty big diff from what @davkal was thinking so I tried it in my own branch. I get a "TypeError: Cannot destructure property 'datasourceInstance' of 'exploreItem' as it is undefined." I'm sure we can figure it out, it's just going to be a bit more of a lift than we were thinking and we will probably have to make some modifications to `SplitPaneWrapper` to handle some things that are different with Explore.

I also tried bringing in the `react-split-pane` directly but honestly a lot of the good stuff is in that wrapper, so we would probably want to figure out how to make `SplitPaneWrapper` work for both. 

https://github.com/grafana/grafana/blob/kristina/split-pane-wrapper/public/app/features/explore/Wrapper.tsx#L88

**Pull request closed without merging**
