### PR TITLE
Linear tsbuckets

### LINKED ISSUE #24365: Heatmap: should accommodate variable sized bins in tsbuckets mode
The y-axis is non-sensical when the bins are all equal sized, but represent different y-axis ranges.  If I have a bin from [1,2) it should be have the size of the bin from [2,4).  In other words, using tsbuckets should still make the graph y-axis and data readable.

### PR DESCRIPTION
**Pull request by postwait**
Fixes #24365

### CODE REVIEW

**Comment by aocenas** [comment]
Hey @dprokop adding this to your backlog project, please take a look when you have time.

**Comment by kamelkev** [comment]
@aknuds1 @aocenas can we keep this open without the stale tag? The net result of this work is very significant for users of histograms.

**Comment by aknuds1** [comment]
There's a conflict that needs fixing.

**Comment by kamelkev** [comment]
@aknuds1 @aocenas can we get this reopened? Curious as to what the conflict is that we need to fix.

**Pull request closed without merging**
