### PR TITLE
CircleCI: Build and publish Docker images in same job

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does / why we need it**:
Build and publish Docker images in same CircleCI job, since caching these large files in the shared workspace is very slow.

* Downsize CircleCI jobs to default resource class, except for Go linting
* Change CircleCI dependency graph according to @torkelo's input (tests before compiling)

### CODE REVIEW

**Comment by torkelo** [comment]
Looks like docs website build is still run first, should be after, maybe in package stages?

image

**Comment by aknuds1** [comment]
@torkelo alright, I'll fix it.

**Comment by aknuds1** [comment]
@torkelo Please have another look.

**Comment by aknuds1** [comment]
I've made the change to fuse the jobs to build and publish Docker images @torkelo - please have another look :)

**Comment by marefr** [comment]
Noticed the shellcheck took over 10m to start because it was waiting for a vm - possible to use docker for this as well as most of the others? https://app.circleci.com/pipelines/github/grafana/grafana/4647/workflows/821b6b85-2265-43ef-9831-4b8718ed594b/jobs/318990

**Review by marefr — APPROVED** [review]
LGTM I think

**Comment by aknuds1** [comment]
@marefr I don't even remember why shellcheck uses a VM.

**Comment by aknuds1** [comment]
Merging since I think we're all on the same page now? We can make a followup PR if anything remains.

**Comment by torkelo** [comment]
Yes! Great job, will be interesting to see what impact this has

**Comment by aknuds1** [comment]
@torkelo After seeing master builds, I think we have to remove Grafana packages also from the CircleCI workspace, it still takes way too long to unpack. I'll try using GCS as a cache for the packages and see if it cuts down the time taken to unpack the workspace (which can be about 10 minutes now).

**Comment by torkelo** [comment]
Yea, let’s try that

**Pull request merged**
