### PR TITLE
add manual prebuilt dashboards CTA banner

### LINKED ISSUE #63897: Chore: Update Dashboards banner
On the page https://github.com/grafana/grafana/blob/main/docs/sources/dashboards/_index.md which publishes as https://grafana.com/docs/grafana/latest/dashboards/ we have a banner pointing to our prebuilt dashboards. 

Because the banner is being managed by our CTA tracking tool, it is not being indexed for SEO purposes. 

**What is the chore?**:
Update the markdown file to use a manual CTA, which is evergreen. 

**Is there anything else we need to know?**:
The structure of the banner should look like this:

**Note:** Looking for prebuilt Grafana dashboards? [Check out our full library of dashboards and more→](https://grafana.com/grafana/dashboards/?pg=docs-grafana-latest-dashboards)

### PR DESCRIPTION
**Pull request by imatwawana**
Adds manual CTA banner to this page so it can be indexed for SEO purposes. Current banner is being managed by our CTA tracking tool, which is not being indexed.

Fixes #63897 

TO DO 
- [x] Coordinate with Chieu and/or Olivia to have other banner removed

### CODE REVIEW

**Comment by imatwawana** [comment]
@chieubpham & @omayorga1 - Tagging you regarding removing the automated version of this banner (see related issue for more details). The automated version appears to be in [this file](https://github.com/grafana/website/blob/af117ec14bea8e526a6344b3bcedd34cf5d75090/content/docs/grafana/_index.md) on line 30. I'd guess it's best to not have the banner duplicated, so I'm thinking you stop the automated banner and then we'll merge this PR. Feel free to ping me with any questions.

**Review by Eve832 — APPROVED** [review]
lgtm

**Comment by chieubpham** [comment]
Thanks for the tag - this banner isn't managed via Adobe Target so I don't see any issues with these changes. 

cc @AnneB-SEO2

**Comment by AnneB-SEO2** [comment]
@meganmilan can you pls help us out. I had created a ticket to add the banner to the doc dashboarding landing page. Nick added it but then it was taken down because I thought that my request was added to Chieu's to implement Adobe Target banners. Per Chieu, she's not using Target to generate this banner, and then banner need to be updated, which Isabel (week 7) is trying to, but she can't. Perhaps the Web team needs to update the banner text (?)

**Comment by imatwawana** [comment]
Just to add some more flavour, the banner now shows up as duplicated in the next docs. I can update the markdown to add a manual banner, but the original banner isn't in the markdown of the file and seems to be served from the website in some way from (I think) [this file](https://github.com/grafana/website/blob/af117ec14bea8e526a6344b3bcedd34cf5d75090/content/docs/grafana/_index.md).

First banner is the automated one, second banner is the one I've added:
image

Only the second banner is in the markdown:
image

**Comment by meganmilan** [comment]
Hi all - I see this is merged. Please let me know if you need anything further from the web team!

**Comment by imatwawana** [comment]
We actually reverted this PR in the end. I'm pretty sure @nate-walters-grafana is aware of what we need at this point in terms of updating the existing automated banner.

**Comment by meganmilan** [comment]
@imatwawana should we reassign this ticket to the web team in that case?

**Comment by imatwawana** [comment]
> @imatwawana should we reassign this ticket to the web team in that case?

@GrafanaWriter - does that make the most sense?

**Pull request merged**
