### PR TITLE
Storybook: Add color theme

### PR DESCRIPTION
**Pull request by tskarhed**
This PR adds a color theme and logo/branding to our Storybook. Details with colors etc. should be double checked with design people.

Currently looking into possibility to change theme for entire Storybook at the same time (like a switch between light and dark)

Building works, static files are served correctly

Adds a theme toggle between light/dark too.

### CODE REVIEW

**Comment by mckn** [comment]
I think the code looks really great! Good job!

When testing the Storybook I found a couple of things. Not sure if this is something needed before merging this PR tho:

- When opening the `Docs` tab the theme isn't applied (or I can't get it to be dark).

dark with light docs

- When I am running the dark mode and navigate between different components the white mode renders before the dark mode is applied. Which gives it a feel of a "flashing" light.

dark flash

- When looking at the modal component it seems to be a blue-ish background in the dark mode.

bluish

**Review by mckn — COMMENTED** [review]
Code looks really great! See me comment above for some more feedback.

**Comment by dprokop** [comment]
@tskarhed this looks amazing, really loving the theme! I would only think about making the logo smaller;) Maybe something like we have on the website 
image
 
> When I am running the dark mode and navigate between different components the white mode renders before the dark mode is applied. Which gives it a feel of a "flashing" light.

I'm also seeing this, probably due to the sass theme switch

> When looking at the modal component it seems to be a blue-ish background in the dark mode.

Yeah, this is normal, that's the color of modals overlay

> When opening the Docs tab the theme isn't applied (or I can't get it to be dark).

I think this is good, the addon-docs needs to be styled separately I think

**Review by dprokop — APPROVED** [review]
<3

**Comment by tskarhed** [comment]
I think there needs to be some changes to the light/dark switch addon to make it work properly with the docs.

**Comment by tskarhed** [comment]
I think the big round one looks nicer, but this one serves a better purpose according to branding.
Screenshot from 2020-02-17 10-30-31

**Comment by tskarhed** [comment]
Also, you need to switch between the light and dark logo, which seems to not be straightforward.

**Comment by tskarhed** [comment]
Merging regardless of the known issues, they can be fixed at another time.

**Pull request merged**
