### PR TITLE
add __interval_s

### PR DESCRIPTION
**Pull request by mtanda**
Use the approach which @torkelo mentioned in https://github.com/grafana/grafana/pull/20263#issuecomment-555404000 .

### CODE REVIEW

**Review by torkelo — CHANGES_REQUESTED** [review]
Needs to be added here as well:

https://github.com/grafana/grafana/blob/master/public/app/core/utils/explore.ts#L147 

If you can try to extract that to a utility function that can be shared between explore and PanelQueryRunner

And in docs: 
https://github.com/grafana/grafana/blob/master/docs/sources/reference/templating.md#the-__interval_ms-variable

A unit test (if easy to add), would be good.

**Comment by torkelo** [comment]
Now the biggest problem to this is that I am not sure how to solve is that Prometheus has some special interval logic and overwrites the interval_ms variable. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L358

an alternative approach to the one used in this PR would be to use the interval variable and have different formatting names, like ${__interval:ms} ${__interval:s} 

Then we won't need any new variable.

**Comment by mtanda** [comment]
@torkelo Please tell me the feasibility of https://github.com/grafana/grafana/issues/15903 .

**Comment by torkelo** [comment]
think https://github.com/grafana/grafana/issues/15903 looks good .

for this I think we only need  ${__interval:ms} ${__interval:s}

**Comment by sbason** [comment]
Was this closed because it is being incorporated into another PR? We also need this feature.

**Pull request closed without merging**
