### PR TITLE
Docs: fixing link issue with time range controls in "what's new"

### PR DESCRIPTION
**Pull request by mckn**
**What this PR does / why we need it**:
This will fix the issue with a broken link in the "whats new in Grafana 7.0" article.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by mckn** [comment]
@marefr we don't need to have the cherry-pick flag on this one, right? I mean since it is docs.

**Comment by marefr** [comment]
@mckn that's right, it's not needed.

**Comment by mckn** [comment]
> @mckn that's right, it's not needed.

super, thanks!

**Pull request merged**
