### PR TITLE
Alerting: Remove extra field orgId from notifier.Alertmanager

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What this PR does / why we need it**:
The structure notifier.Alertmanager has two fields `orgID` and `OrgID`. Only the former is populated in the constructor. It seems that these fields are supposed to hold the same information. This PR removes the field `OrgID`.

### CODE REVIEW

**Review by gotjosh — COMMENTED** [review]
This looks good, thank you! Is there any reason why we should keep the public one though? It seems like it's the private one we need.

**Comment by yuri-tceretian** [comment]
> This looks good, thank you! Is there any reason why we should keep the public one though? It seems like it's the private one we need.

I picked the one that was added more recently. Honestly, I did not check the public field for usages but according to git blame it is part of some ongoing changes. So I decided that it may be used in some future PRs and kept it.

**Comment by gotjosh** [comment]
I verified it's the private one that we want - if anything requires that ID outside of this component it should be provided by the `multiorg_alertmanager` which also holds the relation.

**Review by gotjosh — APPROVED** [review]
LGTM!

**Pull request merged**
