### PR TITLE
Feature: An XYZ Panel (Alpha), a 3D scatter plot visulization

### PR DESCRIPTION
**Pull request by codeincarnate**
**What is this feature?**

This PR adds a 3D scatter plot visualization (in alpha status) named XYZ Chart as a companion to the 2D XY Chart.

https://user-images.githubusercontent.com/199847/212264197-95e79292-1165-4623-8f41-32193fabf142.mov

**Why do we need this feature?**

Scatter plots are extremely useful for multivariate analysis in various fields including business, scientific analysis, autonomous vehicles, geographic information systems, and others. Scatter plots, especially 3D ones, allow for easy inference of patterns which can be quickly examined from multiple angles. Additionally, they're information dense and it's possible to have as many as 5 data dimensions by adding point color and point size along with spatial dimensions.

This panel also extends the list of panels that work well with non-timeseries data, and brings 3D capabilities into Grafana core.

**Who is this feature for?**

For users doing multivariate analysis in various fields. Also, for users visualizing complex non-timeseries data for analysis and observation purposes.

**Special notes for your reviewer**:

In terms of implementation, a small 3D chart rendering library is built using [React Three Fiber](https://github.com/pmndrs/react-three-fiber) which is itself a thin wrapper around [Three.js](https://threejs.org/). 

**📢 And a very special thanks to @mdvictor for originating this idea and doing a huge share (probably most 😅) of the code contained herein. 📢**

### CODE REVIEW

**Comment by codeincarnate** [comment]
Some things to do:

- [ ] Use Grafana included Roboto font
- [ ] Remove React.FC usage

**Comment by mdvictor** [comment]
Removed the local font from the folder and refactored usages of React.FC from the package.

I also added it to the panel list. It should appear in the panel list after:
 * Setting the `enable_alpha` flag for `[plugins]` in the config file
 * running `make gen-cue` to regenerate plugin files

Sadly, it won't run :( there's something interesting happening where the entire dashboard page refreshes when trying to feed the visualisation some data and then the panel throws a `Error in plugin` message

**Comment by mdvictor** [comment]
I guess next up to do would be:

- [ ] Fix the texture paths (the dot texture path returns undefined cuz it still follows old external plugin format)
- [ ] Make it work without throwing errors or refreshing the page
- [ ] Cleaner code - betterer throws errors that there are many `any` types
- [ ] Format some files that the linter detected in the build
- [ ] `manager_integration_test.go` fails because we need to add new `XYZChart` plugin testcase in there

**Comment by leeoniya** [comment]
please make make quadruple extra sure that these new 🐘🐘 deps are only loaded on demand; 99.5% of users wont need them.

**Comment by codeincarnate** [comment]
@leeoniya I'll specifically check for that 🙏

**Comment by codeincarnate** [comment]
Another todo:

- [ ] Add cue models

**Comment by ryantxu** [comment]
Thoughts on making this an external plugin first?  Any bennifits to having it internal to start?  I am worried about maintenance/commitments/experimental for this.

**Comment by codeincarnate** [comment]
I'm certainly not opposed to have this start out as external. I do think there is some potential benefit here as being included does potentially expose this to a wider audience, as well as getting more eyes on the code.  If we don't see the usage we're hoping for it seems like it would be fairly straightforward to remove.

I'm happy to go either direction though 😄

**Comment by mdvictor** [comment]
Hey @ryantxu. 

I personally am not against having it as an external plugin at first and am curious about your worries. I'd say that at this point the `XYZChart` is in a similar position to where the `XYChart` was when it launched in alpha, from a functionality pov. I agree that the libraries we use are rather big and we need to have that in mind, but otherwise the `THREE.js` library is a really popular and well maintained one, as well as the react wrapper we use. I believe that this could lay the path for future 3D panel works in Grafana, but am open to futher discussion as to why we would not want it as an internal panel initially.

**Comment by ryantxu** [comment]
Let's move this to external and see what kind of adoption we get.  My concerns are really about keeping the core as focused as possible.  Adding plugins from the marketplace is totally reasonable for any special needs -- and our escalation/maintenance requirements are significantly less with external plugins

**Pull request closed without merging**
