### PR TITLE
Add hide template variable option

### PR DESCRIPTION
**Pull request by mtanda**
https://github.com/grafana/grafana/issues/4146

### CODE REVIEW

**Comment by mtanda** [comment]
@torkelo The original issue is labeled, "P4: nice to have" and "state: help wanted (PR)".
If you missed this, please check this :-)

**Comment by torkelo** [comment]
I think this is good, just one detail that I think needs to be addressed as well, if all variables are hidden the submenu component should also be hidden

**Comment by bergquist** [comment]
@mtanda @torkelo since I didnt catch that condition before merging I will fix it

**Comment by mtanda** [comment]
@bergquist thanks!

**Comment by satyashanmuka** [comment]
what should be the url parameter to be given to hide template variables ? I tried hideVariable=true, but it didn't work as expected.

**Comment by torkelo** [comment]
Hiding a variable is a saved option that can not be changed via url param

**Comment by satyashanmuka** [comment]
@torkelo is there an option to hide template variables via url parameter in recent grafana version ? I have seen an option to hide tool bar i.e kiosk mode. Does that hide template variables too ?

**Comment by Codyooo** [comment]
@satyashanmuka  +1

**Pull request merged**
