### PR TITLE
ButtonGroup: Support nested buttons within button groups

### LINKED ISSUE #35793: Explore: minor styling error for run query buttons
**What happened**:
There's a minor styling issue where the corners on the button to the left of the "run query" button are rounded on the left side. Here's a picture displaying the issue:
Screenshot 2021-06-14 at 15 43 06@2x

**What you expected to happen**:
The top left and bottom left corners should be straight to smoothly blend in with the "run query" button.

### PR DESCRIPTION
**Pull request by torkelo**
Fixes #35793

alternative to https://github.com/grafana/grafana/pull/35821

### CODE REVIEW

**Comment by olbo98** [comment]
@torkelo i tried running your branch but there seems to be something wrong.
This is how it looks like in explore and dashboards for me
Screenshot 2021-06-18 at 08 17 26
Screenshot 2021-06-18 at 08 18 17
Does it look different on your computer?

**Comment by torkelo** [comment]
@olbo98 might have not pushed my last changes, let me check

**Comment by torkelo** [comment]
@olbo98 pushed some fixes

**Review by olbo98 — APPROVED** [review]
Nice! Everything looks good and seems to be working! @torkelo should i remove #35821 then since this looks like a more substantial solution

**Comment by torkelo** [comment]
yes

**Pull request merged**
