### PR TITLE
CloudWatch: Update AWS/IoT metric and dimensions

### LINKED ISSUE #16334: CloudWatch Datasource IoT Missing Dimensions
**What happened**:
I added a AWS/IoT metric and the dimensions list was missing a majority of the available dimensions.

**What you expected to happen**:
To get a complete list of available dimesnions.

**How to reproduce it (as minimally and precisely as possible)**:
- On dashboard, select 'Add Panel' and add a 'Graph'.
- Use Cloudwatch datasource
- Add AWS/IoT dimension
- Select dimension list .

**Anything else we need to know?**:
Complete list can be found:
- https://docs.aws.amazon.com/iot/latest/developerguide/metrics_dimensions.html
-  https://github.com/awsdocs/aws-iot-docs/blob/master/developerguide/metrics_dimensions.md 

Example Screenshot
image

**Environment**:
- Grafana version: v6.0.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10 + Chrome
- Grafana plugins: CloudWatch
- Others:

### PR DESCRIPTION
**Pull request by nonamef**
**What this PR does / why we need it**:
CloudWatch datasource missing dimensions in AWS\IoT metric.

**Which issue(s) this PR fixes**:
Fixes #16334

**Special notes for your reviewer**:
Add dimensions from https://docs.aws.amazon.com/iot/latest/developerguide/metrics_dimensions.html.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
You've included all metrics for `Message Broker Metrics` and `Device Shadow Metrics`. Any reason not including all the other metrics while you're at it?

**Comment by nonamef** [comment]
I thought that there may have been a reason the other pool of metrics were not originally included.
I have corrected the PR to include all metrics and dimensions.

**Comment by mtanda** [comment]
@nonamef Would you sort the add metric names and dimension keys by dictionary order?
It is hard to maintain if it is not sorted, I found some metric name is duplicated when I clean up the list in past PR https://github.com/grafana/grafana/pull/16102 .

**Review by marefr — CHANGES_REQUESTED** [review]
As @mtanda says. Please sort the metric names and dimensions in order.

**Comment by nonamef** [comment]
I noticed the script "gen_map_from_docs.go" is missing a bunch of documents and have hard coded the dimensions/metrics for those missing documents. Wouldn't it be easier to modify the script to include all the missing documents that "https://github.com/awsdocs/*" contain? Would also save future issues being created by others?
I'm happy to make the updates if required.

**Comment by mtanda** [comment]
@nonamef I'm not sure, but when I check "https://github.com/awsdocs/*", it seems to not include all CloudWatch metrics/dimensions.
The reason why I hard code the metrics/dimensions is, I expect all AWS docs use same Markdown format (table with Metric/Dimension title), but it is not, and some Namespace were missing in awsdocs repo.
If it is include in awsdocs and use standard Markdown format, some metrics is missing in official docs...

https://github.com/grafana/grafana/issues/11239 is the issue.

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
