### PR TITLE
InfluxDB DataSource: Fix getting the feature toggles in MT mode

### PR DESCRIPTION
**Pull request by wasim-nihal**
**What is this feature?**

This PR moves to the new way of checking if the feature toggle is enabled on the instance, which is compatible both with single tenant and multi-tenant mode.

**Which issue(s) does this PR fix?**:

Fixes # https://github.com/grafana/grafana/issues/90758

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by wasim-nihal** [comment]
@aangelisc could you please review this change?

**Review by aangelisc — CHANGES_REQUESTED** [review]
Hi @wasim-nihal,

The `featuremgmt` package also needs to be removed in order for this to be appropriate for MT.

Thanks!

**Comment by wasim-nihal** [comment]
> The featuremgmt package also needs to be removed in order for this to be appropriate for MT.

Thank you for your review, @aangelisc! I’m having some difficulty understanding the suggested change. Just to clarify, are you recommending removing the import of string constants such as `FlagInfluxqlStreamingParser`, `FlagInfluxdbBackendMigration`, and `FlagInfluxdbRunQueriesInParallel` from the `featuremgmt` package and defining them locally instead?

**Pull request closed without merging**
