### PR TITLE
[v.8.2.x] Chore: Backport missing tslib import

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by joshhunt — APPROVED** [review]
Smoke tested locally with my test dashboard, looks fine. 👍🏻

**Comment by joshhunt** [comment]
I did notice that the yarn.lock file is changed once i ran `yarn installed`. Unsure if it's caused directly by this change or not. Change is with underscore:

```diff
-underscore@1.7.0:
-  version "1.7.0"
-  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.7.0.tgz#6bbaf0877500d36be34ecaa584e0db9fef035209"
-  integrity sha1-a7rwh3UA02vjTsqlhODbn+8DUgk=
+underscore@1.12.1, underscore@1.7.0:
+  version "1.12.1"
+  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.12.1.tgz#7bb8cc9b3d397e201cf8553336d262544ead829e"
+  integrity sha512-hEQt0+ZLDVUMhebKxL4x1BTtDY7bavVofhZ9KZ4aI26X9SRaE+Y3m83XUL1UP2jn8ynjndwCCpEHdUG+9pP1Tw==
```

**Comment by thisisobate** [comment]
Closing this for now.

**Comment by hugohaggmark** [comment]
Closed in favour of https://github.com/grafana/grafana/pull/43499

**Pull request closed without merging**
