### PR TITLE
Units: Changes FLOP/s to FLOPS and some other rates per second units get /s suffix 

### PR DESCRIPTION
**Pull request by Berbe**
**What this PR does / why we need it**:
Homogoneise units suffixes:
- Use `/` instead of `p` for time rate units suffixes (along with commonly seen units abbreviation, when that was the case)
- Use the generally used `FLOPS` unit instead of `FLOP/s` (as much as I personally prefer the latter, I never saw it being used...)

**Special notes for your reviewer**:
No extra test introduced in `public/app/plugins/panel/table-old/specs/renderer.test.ts`. Shall other units be tested there?

### CODE REVIEW

**Comment by Berbe** [comment]
This PR is threatened with staleness.

@torkelo, @kaydelaney?

**Comment by torkelo** [comment]
Thanks for contributing!

**Review by torkelo — APPROVED** [review]

**Comment by tofurky** [comment]
'cpm' appears to be the accepted unit name for radioactivity i.e. https://en.wikipedia.org/wiki/Counts_per_minute

should at least the 'c/m' be changed back to 'cpm' or is this meant to be more generic?

**Comment by Berbe** [comment]
> 'cpm' appears to be the accepted unit name for radioactivity i.e. https://en.wikipedia.org/wiki/Counts_per_minute
That use is accepted, but shall be the norm?
It looks to me `cpm` comes from US use.

> should at least the 'c/m' be changed back to 'cpm' or is this meant to be more generic?
This PR attempts at homogeneising the way units are being displayed to enhance coherence. Cue commit messages.

**Comment by tofurky** [comment]
i understand wanting to unify things, but some of these appear to be consistently written that way (with the 'p') regardless of whether SI is in use. it feels awkward, like writing 'ppb' or 'ppm' as 'p/b' and 'p/m'. but, maybe that's just my skewed view coming from a (the) non-SI country :)

anyways, i've found that there is a way to override this on a per-graph basis, which will handle my graph affected by this PR:
image

**Pull request merged**
