### PR TITLE
Docs: Made usage of config/configuration consistent 

### LINKED ISSUE #19270: config vs. configuration
Currently the terms "config" and "configuration" are used interchangeably. This is confusing for readers.

Decide on what the rules for one vs. the other should be, then add them to the Documentation style guide and create an issue to apply them.

My suggestion:
Only use "config" when you are specifically referring to a config file, and then use the actual name and file extension. In all other cases, use "configuration."

### PR DESCRIPTION
**Pull request by ndeevy**
Fixes #19270

Hi @oddlittlebird this PR addresses the usages of config vs configuration in the docs. This change means that:

- 'config' is used with 'file'.
- Other instances of 'config have been changed to 'configuration'.
- 'config' in relation to ui elements or parameters remain.

You mentioned to create a new issue for the update to the style guide with the recommendation, is that right?

Thanks!

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]
Looks good. Can you sign the CLA Agreement? Thank you.

**Comment by ndeevy** [comment]
> Looks good. Can you sign the CLA Agreement? Thank you.

Hi @achatterjee-grafana Sorry for the delay, but I work for Red Hat and they've said I need to sign a different CLA that Grafana with Red Hat use for this purpose. Do you know where I could send it once signed?
Thanks!

**Comment by achatterjee-grafana** [comment]
@daniellee, can you guide @ndeevy with his request.

**Comment by oddlittlebird** [comment]
@ndeevy , I don't think our system is set up for group CLAs yet. Is there any problem with just signing the indvidual CLA?

**Comment by ndeevy** [comment]
> @ndeevy , I don't think our system is set up for group CLAs yet. Is there any problem with just signing the indvidual CLA?

Hi Diana, again sorry for the delay! My company has sent the correct, signed CLA to the appropriate folks at Grafana, Torkel Ödegaard and Raj Dutt, on Friday so just waiting on notification that all is good.

**Comment by ndeevy** [comment]
Hi @oddlittlebird Now that my signed CLA is submitted to your legal folks, Red Hat said I'm fine to contribute now. I'm not sure how to workaround this CLA within the PR though. 
I'm, working on resolving the conflicts in the meantime.
Thanks

**Comment by oddlittlebird** [comment]
Thanks, @ndeevy . @grafana/backend-platform , any ideas who can figure out this CLA thing?

**Comment by ndeevy** [comment]
Hi @oddlittlebird Torkel told me by mail my CLA was added to my PR and the 'CLA assistant (our CLA bot), should mark your PR as green.' so not sure what else I can do from my side to move this along. Hopefully it'll go green soon. Thanks for the patience :-)

**Comment by torkelo** [comment]
Not sure why the CLA bot is not approving it, you are added to the list

**Pull request merged**
