### PR TITLE
Chore: cherry-picks for v6.5.2

### PR DESCRIPTION
**Pull request by mckn**
--------------------------------------------------------------------
  Printing PRs with cherry-pick-needed, in ASC merge date order
  --------------------------------------------------------------------
  * Prometheus: Fix caching for default labels request, (#20718), merge-sha: f2574f49447c9d7cb952c3d178750e10eb1275f6
  * Login: Fix fatal error when navigating from reset password page, (#20747), merge-sha: b3816a2727648b579b92d007079189b1e2971b8f
  * Units: Remove SI prefix symbol from new milli/microSievert(/h) units, (#20650), merge-sha: fcde26e2dbd87bb864444714dff155dacc631e97
  * Server: Fail when unable to create log directory, (#20804), merge-sha: b1af28122b33b5fc5e1dc01a53bc24f705c930b1
  * Fix instructions to use @grafana/toolkit package, (#20820), merge-sha: fd2b39a3e98062115fb92b3a8c5b0e2178b3dd09
  * Security: Fix invite link still accessible after completion or revocation, (#20863), merge-sha: abc7893fdc9446569e56e1c7550ebe0c5459b18a
  * Gauge/BarGauge: Added support for value mapping of "no data"-state to text/value, (#20842), merge-sha: 7a710737aeea88c8d735a93077707e05f3aff8cf
  * Graphite: Fixes error with annotation metric queries , (#20857), merge-sha: ad33d95dd31dc696e404a21dff7ad659cd545c8b
  * Graph: Prevent tooltip from being displayed outside of window, (#20874), merge-sha: 5f72bfe6e7747216ada01ed4efa46165c8057bd3
  * TeamPicker: Increase size limit from 10 to 100, (#20882), merge-sha: 9a7a1b86ee4f4e17ceff4cc69828573ee8000fb0
  * AngularPanels: Fixed loading spinner being stuck in some rare cases, (#20878), merge-sha: 62f0aca3e65d03b8070def7c234e286305d7a948
  * CloudWatch: Remove template variable error message, (#20864), merge-sha: 9d9f0e1b8c1957269c489162edfdffac8435a56f
  * AngularPanels: Check for digest cycle on root scope, (#20919), merge-sha: 2a44cbd13754a26a82435440a8ddb1c2d5fe0245
  * CloudWatch: Remove illegal character escaping in inferred expressions, (#20915), merge-sha: a533e006229ff0b95a87d54016595dfb3a7c718c
  * CloudWatch: Fix query editor does not render in Explore, (#20909), merge-sha: ab3df985234a400f9d90ab04d09f7b8fb1caba2e
  * Elasticsearch: Set default port to 9200 in ConfigEditor, (#20948), merge-sha: 4ad8b6f030273b40ea22ab9486ca8739af7a7b9b
  * Prometheus: Run default labels query only once, (#20898), merge-sha: a7f4e4c56ac94c6b42c6cc13e3fa0e7a72637854
  * Alerting: Improve alert threshold handle dragging behavior, (#20922), merge-sha: fc00d8336f2be39aa6af712cd19030ed68b006bc
  * CloudWatch: Use datasource template variable in curated dashboards, (#20917), merge-sha: 93ab0532c7bc858ade609ed1caa2d3e04eb69c27
  * build: adds IANA timezone info to windows build, (#21001), merge-sha: 67d83d1ffc952b63edaf851a9bc8f77ccec86c78
  * MixedDatasources: Do not filter out all mixed data sources in add mixed query dropdown, (#20990), merge-sha: 72ee1b9a949f3f495ac236c2a625d933f56e33b6
  --------------------------------------------------------------------
  Commands (in order of how they should be executed)
  --------------------------------------------------------------------
  git cherry-pick -x f2574f49447c9d7cb952c3d178750e10eb1275f6
  git cherry-pick -x b3816a2727648b579b92d007079189b1e2971b8f
  git cherry-pick -x fcde26e2dbd87bb864444714dff155dacc631e97
  git cherry-pick -x b1af28122b33b5fc5e1dc01a53bc24f705c930b1
  git cherry-pick -x fd2b39a3e98062115fb92b3a8c5b0e2178b3dd09
  git cherry-pick -x abc7893fdc9446569e56e1c7550ebe0c5459b18a
  git cherry-pick -x 7a710737aeea88c8d735a93077707e05f3aff8cf
  git cherry-pick -x ad33d95dd31dc696e404a21dff7ad659cd545c8b
  git cherry-pick -x 5f72bfe6e7747216ada01ed4efa46165c8057bd3
  git cherry-pick -x 9a7a1b86ee4f4e17ceff4cc69828573ee8000fb0
  git cherry-pick -x 62f0aca3e65d03b8070def7c234e286305d7a948
  git cherry-pick -x 9d9f0e1b8c1957269c489162edfdffac8435a56f
  git cherry-pick -x 2a44cbd13754a26a82435440a8ddb1c2d5fe0245
  git cherry-pick -x a533e006229ff0b95a87d54016595dfb3a7c718c
  git cherry-pick -x ab3df985234a400f9d90ab04d09f7b8fb1caba2e
  git cherry-pick -x 4ad8b6f030273b40ea22ab9486ca8739af7a7b9b
  git cherry-pick -x a7f4e4c56ac94c6b42c6cc13e3fa0e7a72637854
  git cherry-pick -x fc00d8336f2be39aa6af712cd19030ed68b006bc
  git cherry-pick -x 93ab0532c7bc858ade609ed1caa2d3e04eb69c27
  git cherry-pick -x 67d83d1ffc952b63edaf851a9bc8f77ccec86c78
  git cherry-pick -x 72ee1b9a949f3f495ac236c2a625d933f56e33b6

### CODE REVIEW

**Comment by mckn** [comment]
Had to resolve merge conflicts in the following cherry-picks:

`git cherry-pick -x 7a710737aeea88c8d735a93077707e05f3aff8cf`, removed `getDisplayValueAlignmentFactors` @torkelo 

------------

`git cherry-pick -x a7f4e4c56ac94c6b42c6cc13e3fa0e7a72637854`, needed to reorganize the imports in `suggestions.tsx` @davkal @aocenas

**Comment by davkal** [comment]
> git cherry-pick -x a7f4e4c56ac94c6b42c6cc13e3fa0e7a72637854, needed to reorganize the imports in suggestions.tsx @davkal @aocenas

LGTM

**Review by torkelo — APPROVED** [review]
Looks good

**Review by dprokop — APPROVED** [review]
LGTM

**Comment by mckn** [comment]
@sunker please verify that all of your PRs are included 🙏

**Comment by aknuds1** [comment]
Has #20842 really been cherry-picked? I tried cherry-picking it myself into this branch, and it was missing.

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
