### PR TITLE
Removed input padding variables

### PR DESCRIPTION
**Pull request by Ijin08**
Removed input padding variables and table cell padding variable. Created new inset variables and used those where padding variables has been used. Removed unused class in _gf-form.

### CODE REVIEW

**Comment by torkelo** [comment]
Not 100% sure removing all component-specific variables and replacing them with generic ones is the way to do. Is there any other UI framework that does this? Is there any other that use inset spacing variables like these? Just want to know more if this is a good idea or not before this particular change is made. It could be a good change but also afraid it will be limited to link all internal component spacing to the same set of variables. 

thoughts @dprokop @jschill ?

**Comment by jschill** [comment]
"Utility"-based css frameworks do this approach by creating classes with spacing that should be reused everywhere instead of component specific.

http://tachyons.io/docs/layout/spacing/
https://tailwindcss.com/docs/spacing

After using it for some time though I've realised that those generic spacings cover 95% of the use cases. For the rest you need to add a custom one (or learn to ignore when its not as exact as you want). But maybe 95% is good enough?

So I think we could use those space-classes but be prepared to create $main-search-padding when needed. I'm not sure i get the `inset` variants.

(A potential problem in this PR is that I realise we're using the same naming convention for the sizes as for the breakpoints; $space-sm, -md etc. It's confusing.)

**Comment by dprokop** [comment]
I personally don't like the inset variables idea since what they do is basically use the same values as basic spacing. 

When it comes to component specific variables. IMO they should not belong to the `GrafanaTheme` type. I think specific component could (and in some case will probably do) define their own variables dynamically. But my thinking here is that, if that happens, the component specifixc variables should use Grafana theme's primitives to make sure, they are sort of aligned with our spacing base.

To illustrate above I can imagine for instance a `Card` component(used on datasources page) that would define its own spacing, that would simply be `let cardPadding: theme.spacing.s * 1.5`.

**Comment by Ijin08** [comment]
Reading about this I found this article that a lot of sense to me:
https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62
So this article has been my main guide and it echoes a lot of what I have read.

@jschill @dprokop  wasn't sure if it was enough to simply have a group of space variables or if it would be good to have inset variable for div paddings in three shapes. I guess the reason for inset would be to encourage stricter padding rules and not creating ones own shapes with the space variable.

**Comment by Ijin08** [comment]
This could actually be a subject to discuss at the Monday frontend meeting. @dprokop

**Comment by dprokop** [comment]
I completely agree with the fact that variable/theme variable should be intentional. However, my point is the from perspective of someone developing custom plugin/app for Grafana the information what is the i.e. `buttonPadding` is redundant. And I think such properties in the `GrafanaTheme` type only can make not only less readable but also confusing.

If, take Button for example, she wants to write her own MyButton component, that's fine. But IMO she needs to encapsulate that component's styling specific information together with that component (meaning define variables based on our theme). Or simply use our Button component instead that has this information already in it (based on `GrafanaTheme` basic properties).

So, if @grafana/ui delivers a building blocks from which someone can build the extension, then I consider `GrafanaTheme` as one of those building blocks, and not repository of information about spacing/colors/etc of other building blocks.

**Comment by dprokop** [comment]
I.e. Bootstrap/ZURB Foundation frameworks use component specific theme variables. But their goal is to enable framework customisation without touching the framework code, but by modifying the variable value. And in that case having such flexible theme is beneficial, because of the need that those frameworks fulfill- customization basically. 

I think that in our case, when people can develop extensions that are integral part of our app, we should strive for as unified look as possible, not necessarily allowing people to use variables, that's intent is driven by different component's needs. Of course, having primitives in the `GrafanaTheme` will not stop anyone from making input's background yellow, but at least the usage will be clearly intentional, as compared to using i.e. `warningButtonBackground` to accomplish that,

**Pull request merged**
