### PR TITLE
Dashboards: Implement natural sort for query variables

### LINKED ISSUE #13179: [Feature] Natural sorting in templating variables
### What Grafana version are you using?

5.2.3

### What datasource are you using?

Prometheus, but doesn't really matter

### What do you want?

I have a bunch of machies called `{number1}{string}{number1}` and I want to sort them as version strings (in `sort -V` sense):

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort -V
16foo1
16foo3
16foo13
```

Grafana can now sort only alphabetically and numerically and both give weird results:

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort
16foo1
16foo13
16foo3
```

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort -n
16foo1
16foo13
16foo3
```

My suggestion is to add version sort to this dropdown:

image

### PR DESCRIPTION
**Pull request by bobrik**
Natural sort is more human friendly than numeric or alphabetic, especially if text contains some structure, such as: `{number}{letter}{number}`.

When sorting it naively, one ends up with sequences like:

* `4m1`
* `4m10`
* `4m11`
* ...
* `4m2`
* `4m20`

Whereas a human would expect:

* `4m1`
* `4m2`
* ...
* `4m10`
* `4m11`
* ...
* `4m20`

This commits adds natural sort for template variables.

Fixes #13179.

### CODE REVIEW

**Comment by bobrik** [comment]
I think we should consider using this as the default sort algorithm for legends as well.

People generally do not want to have their legend sorted like this:

image

**Review by mckn — APPROVED** [review]
LGTM!

**Review by axelavargas — APPROVED** [review]
Thanks for the contribution @bobrik 🥇 , code looks good to me.

**Comment by torkelo** [comment]
@axelavargas if we merge this we need to remember to port it to scenes

**Comment by bobrik** [comment]
Is there anything from me to do for the scenes change?

**Comment by axelavargas** [comment]
@torkelo good catch, I opened the [PR](https://github.com/grafana/scenes/pull/459) on scenes project and added these changes.

@bobrik no need 😄 , I have included your changes on that PR, Thank you, again!.

**Comment by axelavargas** [comment]
@bobrik Actually the CI is complaining about prettier, can you run locally `yarn prettier public/app/features/variables/query/reducer.test.ts --write` .

Thank you 🙏🏾

**Comment by bobrik** [comment]
Is this one good to go? https://github.com/grafana/scenes/pull/459 is already merged.

**Comment by bobrik** [comment]
I made #78494 for the legend sort.

**Pull request merged**
