### PR TITLE
Alerting: updating the victorops alerter to handle the no_data alert type

### PR DESCRIPTION
**Pull request by rrusso1982**
**What this PR does / why we need it**:
Alerts sent to Victorops with the messageType of 'no_data' are invalid.  This changes the messageType sent to a 'WARNING'.  That is an alert type recognized by VictorOps.

### CODE REVIEW

**Review by bergquist — CHANGES_REQUESTED** [review]
Hi! Thank you for taking the time to contribute to Grafana. But I don't think you can assume that everyone wants this behavior.

**Comment by rrusso1982** [comment]
> Hi! Thank you for taking the time to contribute to Grafana. But I don't think you can assume that everyone wants this behavior.

Do you have a suggestion for how this can be altered into an acceptable state?

**Comment by rrusso1982** [comment]
> Hi! Thank you for taking the time to contribute to Grafana. But I don't think you can assume that everyone wants this behavior.

I changed my PR around so that there is a selector in the VictorOps configuration to set what alerting level is sent when a "no_data" alert state is encountered.

**Comment by rrusso1982** [comment]
@bergquist Can you please tell me if this latest change is more in line with what you were thinking would work for people?  Right now sending a "no_data" type to VictorOps causes a 400 error from their API so I am trying to get that behavior corrected.

**Comment by rrusso1982** [comment]
@bergquist I haven’t seen an activity on the PR since the last changes I made.  Is there anything I can do to assist in it’s review?  I’d really love to squash this VictorOps integration bug as it comes up for us daily.  Thank you.

**Comment by bergquist** [comment]
I just haven't had time to review it yet. To long backlog atm.

**Comment by rrusso1982** [comment]
commenting so this does not become auto closed

**Review by bergquist — APPROVED** [review]
LGTM

Thank you for contributing :)

**Comment by rrusso1982** [comment]
@bergquist i was just wondering when this change might be included in a release?  Is there anything else you need me to do for that?  Thanks

**Pull request merged**
