### PR TITLE
ReactTable: adds color text to field options

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
The first commit pretty much solves this task, but I introduced a small refactor to make the DefaultCell more reusable. Please leave feedback if you think this is a good approach or not.

**Which issue(s) this PR fixes**:
Relates #20709

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mckn** [comment]
I think this looks really good but you should be able to add a HOC to solve this scenario a bit more cleaner. What do you think about adding this in the [`TableCell`](/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Table/TableCell.tsx):

```typescript
export const withStyling = (componenToRender: FC<Props>, getStyling: (props: Props) => TableStyles): FC<Props> => {
  return props =>
    componenToRender({
      ...props,
      tableStyles: getStyling(props),
    });
};
```

Then we should be able to do something like this in [`table/utils.ts`](https://github.com/grafana/grafana/blob/hugoh/react-table-color-value/packages/grafana-ui/src/components/Table/utils.ts#L83):

```typescript
function getCellComponent(displayMode: TableCellDisplayMode) {
  switch (displayMode) {
    case TableCellDisplayMode.ColorText:
      return withStyling(TableCell, (props) => {
           // add logic to extend the tableStyles:
           const { tableStyles } = props;
           const textColor = css``;
           return {
               ...tableStyles,
               tableCell: cx(tableStyles.tableCell, textColor),
           };
      });
    case TableCellDisplayMode.ColorBackground:
      return BackgroundColoredCell;
    case TableCellDisplayMode.LcdGauge:
    case TableCellDisplayMode.GradientGauge:
      return BarGaugeCell;
    default:
      return DefaultCell;
  }
}
```

**Comment by mckn** [comment]
> I think this looks really good but you should be able to add a HOC to solve this scenario a bit more cleaner. What do you think about adding this in the [`TableCell`](/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Table/TableCell.tsx):
> 
> ```ts
> export const withStyling = (componenToRender: FC<Props>, getStyling: (props: Props) => TableStyles): FC<Props> => {
>   return props =>
>     componenToRender({
>       ...props,
>       tableStyles: getStyling(props),
>     });
> };
> ```
> 
> Then we should be able to do something like this in [`table/utils.ts`](https://github.com/grafana/grafana/blob/hugoh/react-table-color-value/packages/grafana-ui/src/components/Table/utils.ts#L83):
> 
> ```ts
> function getCellComponent(displayMode: TableCellDisplayMode) {
>   switch (displayMode) {
>     case TableCellDisplayMode.ColorText:
>       return withStyling(TableCell, (props) => {
>            // add logic to extend the tableStyles:
>            const { tableStyles } = props;
>            const textColor = css``;
>            return {
>                ...tableStyles,
>                tableCell: cx(tableStyles.tableCell, textColor),
>            };
>       });
>     case TableCellDisplayMode.ColorBackground:
>       return BackgroundColoredCell;
>     case TableCellDisplayMode.LcdGauge:
>     case TableCellDisplayMode.GradientGauge:
>       return BarGaugeCell;
>     default:
>       return DefaultCell;
>   }
> }
> ```

In this case I would probably extract the arrow-function to its own function. So the `getCellComponent` is only combining TableCell with styles extensions for all of these simple cases like textColor, textAlignment etc.

**Comment by hugohaggmark** [comment]
> > I think this looks really good but you should be able to add a HOC to solve this scenario a bit more cleaner. What do you think about adding this in the [`TableCell`](/Users/marcusandersson/development/go/src/github.com/grafana/grafana/packages/grafana-ui/src/components/Table/TableCell.tsx):
> > ```ts
> > export const withStyling = (componenToRender: FC<Props>, getStyling: (props: Props) => TableStyles): FC<Props> => {
> >   return props =>
> >     componenToRender({
> >       ...props,
> >       tableStyles: getStyling(props),
> >     });
> > };
> > ```
> > 
> > 
> > Then we should be able to do something like this in [`table/utils.ts`](https://github.com/grafana/grafana/blob/hugoh/react-table-color-value/packages/grafana-ui/src/components/Table/utils.ts#L83):
> > ```ts
> > function getCellComponent(displayMode: TableCellDisplayMode) {
> >   switch (displayMode) {
> >     case TableCellDisplayMode.ColorText:
> >       return withStyling(TableCell, (props) => {
> >            // add logic to extend the tableStyles:
> >            const { tableStyles } = props;
> >            const textColor = css``;
> >            return {
> >                ...tableStyles,
> >                tableCell: cx(tableStyles.tableCell, textColor),
> >            };
> >       });
> >     case TableCellDisplayMode.ColorBackground:
> >       return BackgroundColoredCell;
> >     case TableCellDisplayMode.LcdGauge:
> >     case TableCellDisplayMode.GradientGauge:
> >       return BarGaugeCell;
> >     default:
> >       return DefaultCell;
> >   }
> > }
> > ```
> 
> In this case I would probably extract the arrow-function to its own function. So the `getCellComponent` is only combining TableCell with styles extensions for all of these simple cases like textColor, textAlignment etc.

great feedback, I'll try to do something about this! 🎉

**Review by torkelo — APPROVED** [review]
Looks good!

**Comment by hugohaggmark** [comment]
I ran some perf (just out of curiosity). The scenario is a Table panel that has Cell display option set to 'Auto' and then I just start the React Profiler and select Color text instead of Auto and then I stop the profile. The following images show perf info for just that simple change: 

**Using TextColorCell component (code duplication of DefaulCell but with text color styling)** 
Commit: https://github.com/grafana/grafana/pull/23427/commits/4e8d8bfe8542adba25d7fb5a0b675f3023416dd4

image

**Using Default cell but with a prop that enables it to change styles**
Commit: https://github.com/grafana/grafana/pull/23427/commits/235f5c17cdf3f8888967e469d15ebbfb4c1b9aa7

image

**Using HOC as proposed in PR comments**
Commit: https://github.com/grafana/grafana/pull/23427/commits/79d9fb66db47d8e8ae6e18f52748a8a71a668bed

image

Seems like the first commit is faster but I like the last commit the best, WDYT @mckn @dprokop

**Review by mckn — APPROVED** [review]
Looks really good!!

wow

**Comment by mckn** [comment]
@hugohaggmark since you are measuring speed of rendering. It would be super interesting to try to add a memo on the extended styles output. Would be pretty nice to see if that has any impact.

**Comment by dprokop** [comment]
Seems like the HOC being less performant as it basically creates a new component every time. I personally don't feel a need for this abstraction in this fairly simple context, but since you already implemented it maybe let's just stay with it. Also, maybe instead of returning HOC from every `getCellComponent` we could have it statically defined? :

```ts
const ColorTextTableCell = withStyling(TableCell, (props) => {
    ...
  };
});
```

**Comment by hugohaggmark** [comment]
> getCellComponent

Yes, that's a good idea.

**Comment by hugohaggmark** [comment]
> Seems like the HOC being less performant as it basically creates a new component every time. I personally don't feel a need for this abstraction in this fairly simple context, but since you already implemented it maybe let's just stay with it. Also, maybe instead of returning HOC from every `getCellComponent` we could have it statically defined? :
> 
> ```ts
> const ColorTextTableCell = withStyling(TableCell, (props) => {
>     ...
>   };
> });
> ```

great feedback, that should of course be a more performant way.

**Comment by hugohaggmark** [comment]
> Seems like the HOC being less performant as it basically creates a new component every time. I personally don't feel a need for this abstraction in this fairly simple context, but since you already implemented it maybe let's just stay with it. Also, maybe instead of returning HOC from every `getCellComponent` we could have it statically defined? :
> 
> ```ts
> const ColorTextTableCell = withStyling(TableCell, (props) => {
>     ...
>   };
> });
> ```

After testing this, it's weirdly enough slower for this specific scenario. Without the const I get 34-35ms and with the const I get 36-39ms when I run the profiler.

**Comment by dprokop** [comment]
> After testing this, it's weirdly enough slower for this specific scenario. Without the const I get 34-35ms and with the const I get 36-39ms when I run the profiler. 

that's interesting :) Are you importing from another file?

**Comment by hugohaggmark** [comment]
> > After testing this, it's weirdly enough slower for this specific scenario. Without the const I get 34-35ms and with the const I get 36-39ms when I run the profiler.
> 
> that's interesting :) Are you importing from another file?

withTableStyles is in another file, yes!

**Comment by hugohaggmark** [comment]
> @hugohaggmark since you are measuring speed of rendering. It would be super interesting to try to add a memo on the extended styles output. Would be pretty nice to see if that has any impact.

I skipped this as the perf info shown is for first render, I would have to look into second render in my investigation then and it might not be worth it right now.

**Comment by mckn** [comment]
> > @hugohaggmark since you are measuring speed of rendering. It would be super interesting to try to add a memo on the extended styles output. Would be pretty nice to see if that has any impact.
> 
> I skipped this as the perf info shown is for first render, I would have to look into second render in my investigation then and it might not be worth it right now.

Sounds more then okay :)

**Pull request merged**
