### PR TITLE
Added panel refresh

### PR DESCRIPTION
**Pull request by gbrian**
https://github.com/grafana/grafana/issues/3514

### CODE REVIEW

**Comment by torkelo** [comment]
Thanks for wanting to contribute to Grafana! It's an interesting feature, but the implementation seems very complicated, there must be a simpler solution for this.

**Comment by gbrian** [comment]
ok. Let me reformulate.
Was done that way to keep using one interval only and the existing refresh message.

What was done:
- New settings added to panel and row: Override refresh time
- Assign a countdown to each panel and send "ticks"
- Greatest common divisor of all refresh time is used to calculate the interval.
- Send tick on each interval, panels will reduce its countdown
- When the panel got 0, refreshes and restarts the countdown.
- A new structure has been created on rootScope to keep that data.

I can simplify the implementation by removing unneeded data.
BTW any suggestion ? Any specific point/s that looks complicated ?

About testing, can you point me to any existing one that I can use as an example ?

Thanks.

**Comment by torkelo** [comment]
the solution is complicated as it spread out into multiple places and uses global state to keep track of things. Think having the panel itself (panelSrv) handle the panel specific refresh timer might less complex.

As for tests, there are a ton of unit tests in public/tests/specs/  and in many folders names specs under public/app/**

**Comment by gbrian** [comment]
Ok, I'll check tests. Did you see last update? 

About "Think having the panel itself (panelSrv) handle the panel specific refresh timer" do you mean a timer per panel ? 
I tried to avoid that but what if:
* For those panels with refresh override(those ones inheriting from row will be included):
  * Create timer for each
  * Ignore "global/dashboard" refresh event
* All other panels will refresh as today

About tests, ok I'll dig myself and try to find a good example to follow. Hope to find the correct one on first attempt.

Next time I'll ask for a "design" before coding :)

**Comment by gbrian** [comment]
Ok, I think this time is quite simple. 
Please let me know your comments before creating the tests.

When to use $scope.$broadcast and when appEvent ?

**Comment by gbrian** [comment]
Too old. Will implement it again over latest version.

**Pull request closed without merging**
