### PR TITLE
Navigation: Remove monitoring texts for items under Monitoring section

### LINKED ISSUE #58214: Navigation IA: Remove `Grafana` from items under `Alerts and incidents` (e.g. `Grafana OnCall` -> `OnCall`)
- [x] `Grafana OnCall` title should just be `OnCall`
- [ ] `Grafana Incident` title should just be `Incident`

not sure whether we want to actually change this for the plugin (probably not?) or whether we just want to modify the title in the navtree.

potentially useful information: there's an existing function [here](https://github.com/grafana/grafana/blob/main/pkg/services/navtree/models.go#L101) where we _might_ want to do this

### LINKED ISSUE #58215: Navigation IA: Remove `Monitoring` from items under Monitoring section (e.g. `Kubernetes monitoring` -> `Kubernetes`)
- [x] `Synthetic monitoring` title should just be `Synthetics`
- [x] `Kubernetes monitoring` title should just be `Kubernetes`

not sure whether we want to actually change this for the plugin (probably not?) or whether we just want to modify the title in the navtree.

potentially useful information: there's an existing function [here](https://github.com/grafana/grafana/blob/main/pkg/services/navtree/models.go#L101) where we _might_ want to do this

### PR DESCRIPTION
**Pull request by lpskdl**
**What is this feature?**

- [x]  `Synthetic monitoring` title should just be Synthetics
- [x] `Kubernetes monitoring` title should just be Kubernetes
- [x] `Grafana OnCall` title should just be `OnCall`
- [ ] `Grafana Incident` title should just be `Incident`

Screenshot 2022-11-11 at 16 45 29

**Which issue(s) does this PR fix?**:

Fixes #58215
Fixes #58214 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leventebalogh** [comment]
@lpskdl Just as an idea: instead of hardcoding these "overrides" in the core, would it make sense to either provide a setting in the settings INI to override section names for plugins, or to somehow make it possible for plugins to specify what text should be used when they are displayed under a different section?

**Comment by lpskdl** [comment]
Hi @leventebalogh ,

Thank you for your suggestions, I think its great and leaning towards giving the responsibility of handling the texts in the plugin level as you suggested. Would you be happy to guide me how  to do that?

**Review by ashharrison90 — APPROVED** [review]
looks great 🙌

**Comment by lpskdl** [comment]
> @lpskdl Just as an idea: instead of hardcoding these "overrides" in the core, would it make sense to either provide a setting in the settings INI to override section names for plugins, or to somehow make it possible for plugins to specify what text should be used when they are displayed under a different section?

Hi @leventebalogh , I had a chat with @ashharrison90 and he helped me addressed the suggestions you provided.

**Comment by leventebalogh** [comment]
Hey @lpskdl! Sorry for not replying on this before, I was out of office on Friday :)

Nice, just check it out and it's much more generic! 👍 
One nit: I would probably add a test case (or extend the existing test cases) for testing the section name override by the config.

**Pull request merged**
