### PR TITLE
Plugins: Make grafana-com API URL usage consistent

### PR DESCRIPTION
**Pull request by oshirohugo**
**What is this feature?**

Make grafana-com API URL usage consistent, by getting it from `config.GrafanaComAPIURL`.

**Why do we need this feature?**

This is a improvement to make the separation of environments safer and easier.

**Who is this feature for?**

Grafana developers

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
I am not sure I understand the motivation of this. Is there an environment in which the API endpoint is not `GrafanaComURL + /api`?

You would need to also adapt `enterprise` and maybe the runner. @wbrowne will know better.

**Comment by wbrowne** [comment]
> I am not sure I understand the motivation of this. Is there an environment in which the API endpoint is not `GrafanaComURL + /api`?
> 
> You would need to also adapt `enterprise` and maybe the runner. @wbrowne will know better.

Yeah looks like enterprise needs updating - but for the runner itself, that can be updated when the Grafana dependency is bumped there (no rush on that).

**Comment by oshirohugo** [comment]
@andresmgot thank you for your review. I'm also updating the enterprise here:

https://github.com/grafana/grafana-enterprise/pull/6536

Right now  `GrafanaComAPIURL` is not exactly as  `GrafanaComURL + /api` . `GrafanaComURL` is not using IAP URLs:

https://github.com/grafana/grafana-plugins-platform-team/issues/103

and it only works because we have exceptions to allow that. More context here:
https://raintank-corp.slack.com/archives/C0K031RP1/p1712835986654559

The idea would be to use the IAP URL in the backend (right now `GrafanaComAPIURL` is an IAP URL) , so we avoid creating exceptions whenever we want to use a new endpoint that is not covered by existing rules.

**Review by andresmgot — APPROVED** [review]
Got it, thank you for the explanation :+1:

**Pull request merged**
