### PR TITLE
IDToken: Add current user's Username and UID to the ID token

### PR DESCRIPTION
**Pull request by mgyongyosi**
**What is this feature?**
This PR adds the current user's Login attribute to the ID token.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by cinaglia — APPROVED** [review]
LGTM

**Comment by ryantxu** [comment]
UID is still missing -- can we also add that?  or use it instead of the internal id?

**Comment by mgyongyosi** [comment]
@ryantxu Do you need only the UID or the namespaced UID (`user:{uid}`)?

**Comment by ryantxu** [comment]
> Do you need only the UID or the namespaced UID

The better framing is that we don't want things to ever depend on the internal ID.  If I could choose, we would just swap the numeric part for uid, but I suspect that will break too much 😛 

The sooner we stop telling people about a numeric internal id that can change between deployments the better.  But specifically, we are using the namespaced uid (eg "user:xyz") as the identifier for everything in app platform.

(don't get me started on kubernetes namespace vs token namespace 🙃 )

**Pull request merged**
