### PR TITLE
Chore: Fix times in schemas

### PR DESCRIPTION
**Pull request by spinillos**
Contributes with: https://github.com/grafana/schematization-and-as-code-project/issues/27

Looks like that it isn't working when we are using inner times. We aren't able to detect [this](https://github.com/grafana/grafana/blob/main/kinds/dashboard/dashboard_kind.cue#L325) and [this](https://github.com/grafana/grafana/blob/main/kinds/dashboard/dashboard_kind.cue#L341) ones at the moment. Probably we need to fix that in Thema.

### CODE REVIEW

**Comment by sdboyer** [comment]
this does appear to be changing frontend types from numeric to string - what's the reasoning behind thinking that's ok?

**Comment by spinillos** [comment]
@sdboyer I recall that we decided to put `int64` because we didn't know the way of how to set `time.Time`. 

If you check `ServiceAccounts` and `Team` models, `created` and `updated` are only backend fields and by default, we are using `string` for times in frontend.

@gamab could you verify if the change in `ServiceAccounts` is correct?

**Review by sdboyer — APPROVED** [review]
makes sense! LGTM

**Review by Clarity-89 — APPROVED** [review]
There might be some edge cases where using number (number of milliseconds) for time on the front-end, but I can't think of any examples for now.

**Review by nmarrs — APPROVED** [review]

**Pull request merged**
