### PR TITLE
DateTime: Wraps moment

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR tries to wrap moment in Grafanas own DateTimeType so that we can switch to another datetime library if necessary as moment is no longer maintained.

**Which issue(s) this PR fixes**:
Progress #16806

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jschill** [comment]
Awesome PR as usual 👍

**Comment by jschill** [comment]
@hugohaggmark Maybe out of scope, but would it be an idea to add something like https://eslint.org/docs/rules/no-restricted-modules and restrict `moment` from being imported at all, except from via your wrapper?

**Review by marefr — COMMENTED** [review]
This looks great :+1: Guess this can be a breaking change for plugins if they import moment and do some special things, maybe [clock panel](https://github.com/grafana/clock-panel) is a good candidate for testing this? 

Would be nice to fix the mutable issues that moment causes, but I guess that is a later problem. Lets start with this.

I've only some concerns regarding naming. Suggestions instead of `DateTimeType/dateTimeType`:
-  `DateTime/dateTime` (.net related I suppose :smile:, but it's operating on both date and time so logical for me)
- `Time/time`
- `GrafanaTime/grafanaTime` (feels weird)

**Comment by hugohaggmark** [comment]
> @hugohaggmark Maybe out of scope, but would it be an idea to add something like https://eslint.org/docs/rules/no-restricted-modules and restrict `moment` from being imported at all, except from via your wrapper?

Great suggestion, I'll look into that.

**Comment by hugohaggmark** [comment]
> This looks great 👍 Guess this can be a breaking change for plugins if they import moment and do some special things, maybe [clock panel](https://github.com/grafana/clock-panel) is a good candidate for testing this?
> 
> Would be nice to fix the mutable issues that moment causes, but I guess that is a later problem. Lets start with this.
> 
> I've only some concerns regarding naming. Suggestions instead of `DateTimeType/dateTimeType`:
> 
> * `DateTime/dateTime` (.net related I suppose 😄, but it's operating on both date and time so logical for me)
> * `Time/time`
> * `GrafanaTime/grafanaTime` (feels weird)

I've tested the Clock Panel and can't find any issues with it.
I've also renamed DateTimeType, isDateTimeType and dateTime to DateTime, isDateTime and dateTime. Please review again @marefr

**Review by marefr — APPROVED** [review]
Great :+1:

**Pull request merged**
