### PR TITLE
Added feature to insert image to the left of singlestat prefix field.

### PR DESCRIPTION
**Pull request by afflick**
Allows you to specify an image (by path) to display left of the prefix field in the Single Stat panel. 
The image size is controlled by a percentage of the max-width and max-height.  

It may be beneficial later to allow the image to be placed after the postfix field.

screenshot from 2015-05-18 12 20 08

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure about this feature.

**Comment by afflick** [comment]
Every client has asked for this specific feature. I think it is hugely beneficial for foyer displays, when the aim is not only to create an informative display but also an attractive one. Are you not sure about my application of the controls or the feature in general?

**Comment by torkelo** [comment]
Not sure if its an important option. Do not want do add too many config options to panels, options that are only used in 0.01% of cases. 

But I think this option could be useful, especially if it was paired with an option to either show a custom image, or a icon from the font-awesome package http://fontawesome.io/icons/

**Comment by afflick** [comment]
Agreed, the font-awesome icon would be a great addition. Do you have any ideas about ways to incorporate that as well? Maybe remove it from the prefix/value/postfix section and make a separate section?

**Comment by torkelo** [comment]
yea. maybe its own section.

**Comment by afflick** [comment]
@torkelo - I am happy to include Font Awesome icons and move it into a separate section probably titled "Icon". If I made those changes, would you consider merging my pull request?

**Comment by marknoe1** [comment]
+1 for this

**Comment by afflick** [comment]
I have added the features suggested: 

Local image reference:
screenshot from 2015-06-30 16 51 49

Font awesome icon reference:
screenshot from 2015-06-30 16 52 10

Also, added the same styling that applies to prefix right padding.

**Comment by djnym** [comment]
I actually like this feature as I agree with the original poster, that for certain applications having a symbol with a number make a lot of sense.  Any idea if this will get merged?

**Comment by afflick** [comment]
Obviously works for links to images anywhere on the web 
e.g. http://png-5.findicons.com/files/icons/2118/nuvola/128/ksim_cpu.png

screenshot from 2015-07-02 10 17 56

**Comment by alytle** [comment]
+1

**Comment by afflick** [comment]
For workaround, see #1999

**Comment by tino** [comment]
This looks like a very simple and good way to spice up our dashboards and easy recognition of numbers on a bigger screen. Why has this been closed? The workaround is quite clumsy to be honest.

**Comment by SamuelmAsh** [comment]
Sad to see this closed, replacing a pretty elegant and simple solution with sandwiching two panels together?   Thats not a sexy dash :)

**Comment by finkr** [comment]
I use unicode / utf8 symbols :

warn

It isn't a custom image, there's a lot of images/emoji, like:

☀ ☁ ☂ ⚠ ⚡ ✷ ✸ ✓ ✔ ✕ ✖ ✗ ✘ ❶ ❷ ❸ ❹ ❺ ⬛ ⬜ 🡄 🡆 🡅 🡇 ⬀ ⬁ ⬂ ⬃ 🢄 🢅 🢆 🢇
👍 👎 ✊ 💣 💥🔥 ✆ 📟📌 🖈 📍💹 📈 📉 📊 🗠🌎🌍

You can not only use the image as a prefix, but you can also use value mapping (in single stat panels) to replace values 1 become ☀ or 👍, and 0 become ⚠ or 👎.

There are even some color emoji nowadays (browser and computer dependent)

**Comment by finkr** [comment]
Actually, there is a very easy solution : SVG !

Simply paste some svg, drawing in the prefix/suffix or Value Mapping, that's it !

Yes, literally paste the svg file content in the input box (`<svg> ... </svg>`)

rss

(exemple svg file from https://commons.wikimedia.org/wiki/File:Generic_Feed-icon.svg )

**Pull request closed without merging**
