### PR TITLE
NewPanelEditor: minor UI tweaks

### PR DESCRIPTION
**Pull request by dprokop**
See commit messages for an overview

### CODE REVIEW

**Comment by torkelo** [comment]
Sorry our custom tooltip is not usable, I hate them so much. They block so I cannot expand the settings pane now. 

They act like auto popovers (which is useful for a very very few tooltips that have links) but for 99% where you do not need to be able to hover onto tooltip and select / click content they block content instead. Now if come from the top move down I cannot interact with the top section because I am hovering over the tooltip and it stays put :(

**Comment by dprokop** [comment]
@torkelo maybe let's position them to the top? Struggling with the same thigs

**Comment by torkelo** [comment]
yea placement top could work, think there is enough space so they won't block the buttons above.

I wonder if we can fix Tooltip component to auto hide and act more like native tooltips and opt-in to popover behavior

**Comment by dprokop** [comment]
@torkelo ye, we definitely can but maybe post 7.0. More importnant things to do now :)

you can check the top placement now

**Pull request merged**
