### PR TITLE
OAuth: role/group (JMESPath) mapping prefer Userinfo as per doco

### PR DESCRIPTION
**Pull request by dlambda**
**What this PR does / why we need it**:
This PR updates the search order for OAuth roles & group mappings to prefer the UserInfo as per the documentation.
Currently, the ID token is preferred which has caused confusion.

Using a valid Keycloak set-up based on the current documentation, was seeing errors along the lines:
```
lvl=eror msg="Failed to extract role" logger=oauth.generic_oauth error="failed to search user info JSON response with provided path: \"contains(groups[*], 'SRE') && 'Admin'\": Invalid type for: <nil>, expected: []jmespath.jpType{\"array\", \"string\"}"
```
After a bit of digging realised this was because Grafana was checking the ID token which didn't have the claim.

**Special notes for your reviewer**:
Added a line to documenation also stating the ID token is used as fallback in line with:
https://github.com/grafana/grafana/pull/20300#issuecomment-561063918

### CODE REVIEW

**Comment by marefr** [comment]
Please sign the CLA for us to review this

**Comment by kminehart** [comment]
Sorry I wasn't able to review this yesterday. I got hung up on another PR that took me a lot longer to reproduce than expected.

Looking at it now. I really think that the data auth token should take precedence over the data retrieved from the `/userinfo` endpoint. And if I understand correctly, this would make data obtained from `/userinfo` take precedence over data retrieved from the JWT claims?

**Comment by klarrio-dlamb** [comment]
@kminehart No worries - thanks for looking at this.

> And if I understand correctly, this would make data obtained from `/userinfo` take precedence over data retrieved from the JWT claims?

Only for roles & groups, in-line with the documentation.  If you think this is wrong, then I think the documentation needs to be updated - it has caused confusion for not only me: https://github.com/grafana/grafana/pull/20300#issuecomment-555091379

> Currently Grafana will attempt to get the `email` key from the oauth access token first. if it can't, it will send a request to `/userinfo` to try to get it.

Email is still preferred from the ID token - I haven't changed that code:
https://github.com/grafana/grafana/pull/38104/files#diff-b46acd59043805db35c0f101d9d7e84d93fce739d04230852385d02169e448b3R105-R141

There is no specific test to show the fallback for email, but there is one for login which is essentially the same thing (not touched and still passes):
https://github.com/grafana/grafana/pull/38104/files#diff-7d43fe18e9e8e3dc5f21f2a9c3584c88b3b6da9687303ccb7ad80c6d05be83d6L449-L456

**Comment by kminehart** [comment]
Alrighty. I talked to the team about this one, and we agreed that we should be as consistent as possible with evaluating claims and what takes priority.

We should check the token first, and then anything not found in the token should be set by the Userinfo endpoint or other HTTP requests.

We do appreciate the pull request, however we would prefer to update the documentation to reflect this behavior. Would you be willing to update this PR with the necessary documentation changes?

Thanks.

**Comment by klarrio-dlamb** [comment]
No worries - sounds good.
Created https://github.com/grafana/grafana/pull/39066 instead and closing this.

**Pull request closed without merging**
