### PR TITLE
Alerting support for Druid datasource

### PR DESCRIPTION
**Pull request by chinseone**
- Leveraging abhisant-druid-plugin as frontend plugin
- Branched from v4.4.x
- Tried to rebase from master, but got time-out error when using webhook(WIP)

### CODE REVIEW

**Comment by adriangay** [comment]
just thought I'd say huge thanks for working on this. looking forward to alerting on a Druid datasource. this has come at just the right time in a project for us.

**Comment by torkelo** [comment]
Thanks for contributing to Grafana! 

Sadly we are not going to merge this as we have too many data sources in core Grafana already. This will have to to be an external plugin, and for that it needs to wait for our work on backend plugins: https://github.com/grafana/grafana/issues/6841

**Comment by chinseone** [comment]
@adriangay You are welcome to build it and giving any suggestions :)

**Comment by chinseone** [comment]
@torkelo that's exiting feature coming along! any ETA on that?

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/blob/master/ROADMAP.md

Its currently on our 4-8 month roadmap. Just be aware that this might change.

**Comment by lfblue** [comment]
@torkelo what about replacing one of the existing data sources with a druid? :D

**Comment by shyamremella** [comment]
@torkelo;
Considering the increasing adaption of DRUID in building alerting / monitoring systems  , can you please consider adding support for it?  4-8 month roadmap is a bit long to wait.  
@chinseone

**Comment by bergquist** [comment]
@shyamremella Adopting more data sources will slow us down and delay backend plugins even more. 
One of the nice things about open source is that you can build your own version that includes support for druid alerting until we support backend plugins. Plugins in the frontend have enabled lots of people to use Grafana with creating more work for us that's what we want to replicate with backend plugins. 

We appreciate that you want to contribute back but I'm closing this since we won't merge it. Looking forward to helping you turn this into a plugin once we release initial support for backend plugins

@lfblue I like your enthusiasm but that's not gonna happen :)

**Comment by adriangay** [comment]
@chinseone Hi. I finally decided to build a local Grafana. I forked your forked repo and checked out the v4.4.x branch with your Druid alert PR. After lots of fun with Go installation, it builds. Unfortunately, once I define a notification channel and add into an alert on a simple Druid timeseries query, I still get the red "The datasource does not support alerting queries" message box. Any ideas what I have missed?
screen shot 2017-12-18 at 14 58 30

**Comment by bergquist** [comment]
You need to set "alerging" to `true` in the druid plugin.json  ex https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/plugin.json#L11

**Comment by chinseone** [comment]
Hi @adriangay, thanks for your feedback. I believe you have installed the druid plugin. You only need to set alerting property to 'true' in the plugin.json file.
../go/src/github.com/grafana/grafana/data/plugins/druidplugin/dist/plugin.json
`"alerting": true`

**Comment by adriangay** [comment]
@chinseone @bergquist thx both. Working now. Alerting into Slack :)

**Comment by myrah** [comment]
@chinseone, thanks for sharing. I am getting ```error:"tsdb.HandleRequest() error Could not find executor for data source type: abhisant-druid-datasource"``` with after updating to Grafana v5. Any idea what might be a quick fix? thanks!

**Comment by richiesgr** [comment]
Hi
Same problem here I get 
`tsdb.HandleRequest() error Could not find executor for data source type: abhisant-druid-datasource`
when I try to define an alert it's a severe limitation for grafana druid plugins 
Is there any way to bypass this ?

**Comment by richiesgr** [comment]
@chinseone Same problem as myrah could you help us ?
Thanks

**Pull request closed without merging**
