### PR TITLE
Plugins: ReactPanelPlugin to VizPanelPlugin

### LINKED ISSUE #16578: Consider renaming ReactPanelPlugin to VizPanelPlugin
`AngularPanelPlugin` is ok, since it points out a technology that is getting deprecated... ReactPanelPlugin seems kinda clunky and i think will feel dated pretty soon.  It is obviously react, and the name does not need to point that out :)

I think `VizPanelPlugin` makes sense because it points out a key huge difference between the new plugins and the old ones -- the new plugins are only a way to visualize results, they no longer have control of the whole query lifecycle as they did with MetricPanelCtrl

### LINKED ISSUE #16758: react panel export from reactPanel to just plugin
Is there any plan to publish new @grafana/ui

### PR DESCRIPTION
**Pull request by torkelo**
* Rename ReactPanelPlugin to VizPanelPlugin
* Rename expected export for react panels to just plugin to align it with data source plugins. 

Fixes #16578 
Fixes #16758

### CODE REVIEW

**Comment by dprokop** [comment]
Cool, but shouldn't it be `VisPanelPlugin` or explicitly `VisualizationPanelPlugin`? Not sure whit is it `Viz`.

**Comment by torkelo** [comment]
possibly, it's a bit verbose, but probably clearer to use the full term

**Comment by dprokop** [comment]
Agree, but we are verbose in `DataSourcePlugin` so I think it's fine. My biggest concern was the `z` instead of `s` in Vis.

**Comment by torkelo** [comment]
Maybe just VisualizationPlugin only? but that will trigger so much renaming for all the props and editor types that have Panel in then name. VisualizationPanelPlugin feels a bit repetitive. An alternative is just PanelPlugin for simple and short name

**Comment by dprokop** [comment]
Actually `PanelPlugin` is a very good name 👍 Not every panel is a visualisation actually, but every visualisation panel is... well, panel ;)

**Comment by torkelo** [comment]
Only downside with that name is that it conflicts with this type https://github.com/grafana/grafana/blob/master/public/app/types/plugins.ts#L3 

that is already called that, it's an internal type that represents an installed available panel plugin

**Comment by ryantxu** [comment]
Can we change the existing PanelPlugin to PanelPluginMeta?

**Comment by torkelo** [comment]
Renamed PanelPlugin to PanelPluginMeta (makes sense as it extends PluginMeta), and renamed VizPanelPlugin to just PanelPlugin.

**Comment by ryantxu** [comment]
Looks good -- I think this makes a lot more sense

**Pull request merged**
