### PR TITLE
Make tooltip shareable like crosshair

### PR DESCRIPTION
**Pull request by connection-reset**

### CODE REVIEW

**Comment by bergquist** [comment]
@connection-reset Please consider signing the CLA.

**Comment by connection-reset** [comment]
Ok, signed it

**Comment by connection-reset** [comment]
rebased and squashed commits

**Comment by torkelo** [comment]
Merged this to master after a few changes and refactorings. There is now only one option (named Shared Tooltip), currently using the old property sharedCrosshair (will rename later if there is no major complaints). 

Figured there was no great need to have two options (sharedCrosshair & sharedTooltip), so will try to only have one (that does both), and get some feedback on that.

**Comment by connection-reset** [comment]
@towolf you can disable this in dashboard settings.

**Comment by torkelo** [comment]
or with CTRL/MOD+O  , but if there is a good argument to have these as separate options (shared cross & shared tooltip), then that's good to know, maybe it's worth two options

**Comment by towolf** [comment]
@connection-reset @torkelo Shared cross-hair was not a make-or-break feature, But I woul dnot like to lose this, just because shared tooltips do not work for me ...

If you can support both, please do!

**Pull request merged**
