### PR TITLE
NewDataSourcePage: Add Grafana Cloud link

### PR DESCRIPTION
**Pull request by torkelo**
Adds Grafana Cloud Phantom Plugin to Cloud section in the New DataSource Page

Screen Shot 2019-05-28 at 14 09 59

### CODE REVIEW

**Comment by bergquist** [comment]
screenshots! :)

**Comment by bergquist** [comment]
Looks great!

**Comment by dprokop** [comment]
Cool. Out of curiosity, why is it the last one on the cloud plugins list?

**Comment by torkelo** [comment]
because we are humble :)

**Review by dprokop — APPROVED** [review]

**Comment by dprokop** [comment]
> because we are humble :)
<3

**Pull request merged**
