### PR TITLE
IAM - Fix error messages for resource permissions endpoints

### PR DESCRIPTION
**Pull request by aarongodin**
This cleans up the possible bad request errors on the resource permissions API to provide better user feedback where it was missing previously.

Additionally there was a case where any invalid JSON request body would result in an access control error (using the main `deny(..)` func. Previously:

```json
{
  "accessErrorId": "..",
  "message": "You'll need additional permissions to perform this action. Permissions needed: ",
  "title": "Access denied"
}
```

New error:

```json
{
  "message": "invalid request body: unexpected end of JSON input",
  "traceID": ""
}
```

### CODE REVIEW

**Review by gamab — APPROVED** [review]
LGTM

**Review by IevaVasiljeva — COMMENTED** [review]
For this and the other PR - do you think we could utilise Grafana's `errutil` more? It does have the public message option (`errutil.WithPublic`).

The downside is that we don't get to customise the error messages based on user's input (as in, we can have a public error message saying "invalid permission specified", but we can't have "eeeeditor is not a valid permission"). The upside is that error management is easier (we don't need conditionals checking what error it is to return the right status etc), I think we get stats on the error type, and in general this is the recommended way of error handling in Grafana.

**Comment by aarongodin** [comment]
@IevaVasiljeva thanks, I updated the PR to use `errutil` in most cases.

> (as in, we can have a public error message saying "invalid permission specified", but we can't have "eeeeditor is not a valid permission"

I did find a way to do this with the templated errors (and actually this seemed like the most appropriate way to have public messages).

The one error I didn't change over yet is the errors that can come back from calling `web.Bind(..)`. I added an error type for it, but found that it was too difficult to get the right error message to the user as the errors coming from `web.Bind` are pretty low-level (e.g. json decoding errors). [See this slack for more context](https://raintank-corp.slack.com/archives/C06PNGH5H28/p1712633456100129).

The reason I think it's useful to have more verbose error messages for `web.Bind(..)` errors is that there is also a minimal validator through struct tags that is provided by that function. If someone adds a struct tag later, the user would never be able to see that error message. So I'm not sure where to go on that, but perhaps we could tackle it after this PR.

**Comment by aarongodin** [comment]
Here's an example of the kind of message you can get if you try to assign a permission to a team _on_ a team:

```json
{
    "extra": {
        "assignment": "teams"
    },
    "message": "Assignment [teams] is invalid for this resource type",
    "messageId": "resourcePermissions.invalidAssignment",
    "statusCode": 400,
    "traceID": ""
}
```

**Comment by kalleep** [comment]
> I did find a way to do this with the templated errors (and actually this seemed like the most appropriate way to have public messages).

Nice, I haven't seen the templated errors before but yea it seems to be what we wan't to use here

**Review by IevaVasiljeva — APPROVED** [review]
Nice! Cool to see the `errutil` templates, I haven't used them before, but this looks really neat!

**Pull request merged**
