### PR TITLE
Panels: GeomapPanel edit mode fix

### PR DESCRIPTION
**Pull request by juanicabanas**
**What is this feature?**

It fixes geo map edit mode.

**Why do we need this feature?**

When you create/edit a geomap panel, it gets broken

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

**Before**

https://user-images.githubusercontent.com/11707172/230972934-c675cd6d-b285-46b1-bbdf-d26ab2d78169.mov

**After**

https://user-images.githubusercontent.com/11707172/230972695-5cd6b455-c0c2-4a3b-863d-246e0f5d692d.mov

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by ryantxu** [comment]
This only effects main, not the 9.5 branch, correct?

**Comment by juanicabanas** [comment]
> This only effects main, not the 9.5 branch, correct?

@ryantxu no, I just changed it. It seems this bug was introduced by [this PR ](https://github.com/grafana/grafana/pull/65982), which was backported. So, we should backport it as well.
I'm waiting for @torkelo to confirm this fix. I'm not sure if it's ok to render that component although the value is undefined

**Review by nmarrs — APPROVED** [review]
great catch, looking into adding e2e tests to test / verify geomap / other viz types don't crash 😅

**Comment by ryantxu** [comment]
>  I'm not sure if it's ok to render that component although the value is undefined

It is OK

**Comment by nmarrs** [comment]
Looks like the automatic backport failed, though I'm not sure we need to worry about backporting this as it looks like [the related PR](https://github.com/grafana/grafana/pull/65982) was not backported to the v9.5.x branch ([see search here](https://github.com/grafana/grafana/pulls?q=is%3Apr+is%3Aclosed+Transformations%3A+Improve+UX+and+fix+refId+issues))

**Comment by juanicabanas** [comment]
> Looks like the automatic backport failed, though I'm not sure we need to worry about backporting this as it looks like [the related PR](https://github.com/grafana/grafana/pull/65982) was not backported to the v9.5.x branch ([see search here](https://github.com/grafana/grafana/pulls?q=is%3Apr+is%3Aclosed+Transformations%3A+Improve+UX+and+fix+refId+issues))

@nmarrs we shouldn't do anything else?

**Comment by drew08t** [comment]
Great catch!

**Pull request merged**
