### PR TITLE
Elasticsearch: Fix metric names for alert queries

### LINKED ISSUE #37846: Elasticsearch: All metric names are Count for alert queries
**What happened**:
Created ES alert for  `Count` with `Group by`
image
Got multiple metrics in the graph (graph-old or new time series - no matter) with correct names, but all metrics names in the alert are `Count `
image
No matter if aliasing is used or not.

**What you expected to happen**:
Correct metrics names in the alert

**How to reproduce it (as minimally and precisely as possible)**:
See what happen

**Anything else we need to know?**:
8.0.6 was OK

**Environment**:
- Grafana version: Version 8.1.0 (commit: 62e720c06b, branch: HEAD)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Debian
- User OS & Browser: Linux, Firefox
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by dsotirakis**
**What this PR does / why we need it**:

This PR fixes the metric names for alert queries to use the actual metric / metric alias.

**Which issue(s) this PR fixes**:

Fixes #37846

**Special notes for your reviewer**:

Before the fix:
image

After the fix:
image

### CODE REVIEW

**Comment by torkelo** [comment]
Alias patterns does still no work for me: 
Screenshot from 2021-08-13 12-45-29

Still different logic in backend and frontend for auto names. In the frontend, it will automatically only show the term value:
https://github.com/grafana/grafana/blob/81cfc2c347a7a24b6e0948711e655a0c66dd557c/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L330 
This logic used to be mirrored in the backend: 
https://github.com/grafana/grafana/blob/v6.7.0/pkg/tsdb/elasticsearch/response_parser.go#L432

the function getSeriesName seems to have gotten lost

Screenshot from 2021-08-13 12-41-36
Screenshot from 2021-08-13 12-38-12

**Comment by dsotirakis** [comment]
> Alias patterns does still no work for me

Oh, ignore this, this is me - fixing...

> the function getSeriesName seems to have gotten lost

It's now called `getFieldName`, still there.

(cc @torkelo )

**Review by Elfo404 — APPROVED** [review]
Seems to work as expected now 🚀 

Screenshot 2021-08-16 at 11 58 19

**Comment by torkelo** [comment]
@Elfo404 
> Seems to work as expected now 🚀

That screenshot shows that each series name have a "Count "  prefix, that is not expected, the frontend naming logic does not have that (see my screenshot), the metric is only there if user has added multiple metrics in query

**Comment by dsotirakis** [comment]
@torkelo, then also I guess our tests are a bit wrong for some time now? :/

**Comment by torkelo** [comment]
@dsotirakis possibly, check the frontend tests for reference (or see what the name is in the frontend)

**Comment by dsotirakis** [comment]
@torkelo the wrong thing appears on the query - the legend below the panel seem correct. Will fix in a follow up PR.

**Comment by torkelo** [comment]
@dsotirakis did you check in the new alerting rule view as well (so backend implementation is used) ?

**Pull request merged**
