### PR TITLE
Schema: add missing insertNulls to GraphFieldConfig

### LINKED ISSUE #85271: Schema: missing LineConfig.insertNulls?
### What happened?

When working with grafonnet, trying to template a timeSeries graph with withInsertNulls is not possible.

https://github.com/grafana/grafonnet/issues/188

### What did you expect to happen?

I expected it to essentially work the same way as withSpanNulls ...

### Did this work before?

Nope.

### How do we reproduce it?

try templating insertNulls via graphonnet - or verifying a dashboard using it against the schema.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by berlincount**
**What is this feature?**

Schema is missing `insertNulls` in the `GraphFieldConfig` .. this is the fix.

**Why do we need this feature?**

Fixes https://github.com/grafana/grafana/issues/85271

**Who is this feature for?**

Everyone using the Schema directly, or indirectly via Graphonnet

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/85271
https://github.com/grafana/grafonnet/issues/188

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by berlincount** [comment]
> [CLA assistant check](https://cla-assistant.io/grafana/grafana?pullRequest=85861) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=85861) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=85861) it.

Hm. The check doesn't clear, despite signing .... 🤔

**Comment by joshhunt** [comment]
hi @berlincount - the author of the commits (@kotand-stadler) must be the ones to sign the CLA, not the PR author. It's based on the email used for the commit.

**Comment by berlincount** [comment]
> hi @berlincount - the author of the commits (@kotand-stadler) must be the ones to sign the CLA, not the PR author. It's based on the email used for the commit.

oh. argh. good catch. same person, different account. I'll see how I can fix that.

**Comment by berlincount** [comment]
> > hi @berlincount - the author of the commits (@kotand-stadler) must be the ones to sign the CLA, not the PR author. It's based on the email used for the commit.
> 
> oh. argh. good catch. same person, different account. I'll see how I can fix that.

done, thanks for the assist!

**Review by joshhunt — APPROVED** [review]

**Pull request merged**
