### PR TITLE
Logs: Cannot highlight text in safari

### LINKED ISSUE #74135: Explore: Cannot click-drag log lines in Safari
### What happened?

When attempting to click-drag to highlight text in log lines from Loki search results in Safari, the click just opens the labels instead of highlighting text. I only experience this on Safari, Chrome and Firefox work correctly. 

### What did you expect to happen?

Click-dragging text highlights text

### Did this work before?

Unknown, I only recently began using Safari

### How do we reproduce it?

1. Open a Loki datasource in Explore
2. Perform a search
3. Attempt to highlight text in the results

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: Grafana v10.0.3 (eb8dd72637)
OS: Mac OS 14.0 Beta (23A5286i)
Browser: Safari Version 17.0 (19616.1.20.11.3)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by gtk-grafana**
**What is this feature?**

Fix for Safari in which users cannot select text in log lines.

**Why do we need this feature?**

UX in safari should match.

**Who is this feature for?**
Safari users with logs

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/74135

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
pointer events none was breaking a bunch of unit tests, so I think the easiest solution is to move away from a button element and instead replace with a span. But still confused as to why text within this button is not selectable in safari

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
Unfortunately, this breaks keyboard navigation functionality. 

This is how we want this to work:

https://github.com/grafana/grafana/assets/30407135/8fecd49e-aefc-4a34-8407-ad2347f87a86

And this is how it works in this PR:

https://github.com/grafana/grafana/assets/30407135/f73f32a0-1499-4f1a-a381-4709fdb2b04e

**Comment by gtk-grafana** [comment]
@ivanahuckova Good catch, but I noticed that keyboard navigation is also [broken in safari](https://ops.grafana-ops.net/explore?panes=%7B%22WS6%22:%7B%22datasource%22:%22OP27Xzxnk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22grafana%5C%22%7D%20%7C%3D%20%5C%22traceID%5C%22%20%7C%3D%20%5C%22level%3Derror%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22OP27Xzxnk%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1).

It currently doesn't let you tab into the logs panel at all, you can only select the surrounding panel content div, and not drill into logs :'(

**Comment by gtk-grafana** [comment]
Ignore the above, apparently safari requires setting config in preferences before it will let users navigate via the keyboard.

After stripping everything out, safari just won't let you select text within a button, and despite the docs saying that -webkit-user-select: text should work, it clearly does not. 
https://jsfiddle.net/aesfjrup/1/

Confused as to why the pointer-events:none hack was working in Grafana, but not in the jsfiddle... 😕

**Comment by gtk-grafana** [comment]
Sven helped figure it out: https://jsfiddle.net/58g6qdxm/
With border: none and padding:0 and pointer-events:none, button text is selectable in safari, since these styles were already active on the button in grafana, pointer-events:none was "fixing" the inability to select text in safari.

It looks as though this is a bug with Safari, and not Grafana. Although it's worrisome that more people aren't having this same problem.

**Comment by gtk-grafana** [comment]
I submitted a report via https://www.apple.com/feedback/safari.html. Trying to find a public forum for reporting safari bugs but not finding much.

**Pull request closed without merging**
