### PR TITLE
API: Return 404 when deleting nonexistent API key

### LINKED ISSUE #33331: API: When deleting a non-existing api key should return 404 not found
**What happened**:
Deleted a non-existing API key using curl which returned HTTP 200 and a message that it was deleted:
```
curl -XDELETE -H "Accept: application/json" -H  "Content-Type: application/json" "http://admin:admin@localhost:3000/api/auth/keys/:3000" 
{"message":"API key deleted"}
```

**What you expected to happen**:
HTTP 404 and a message that it was not found.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: master (3056f86f767ba2c439cb9ead8024ed5d45779624), but released versions as well.

### PR DESCRIPTION
**Pull request by chaudum**
**What this PR does / why we need it**:

The server needs to return a HTTP 404 (Not Found) when an API key that does not exist is deleted.

**Which issue(s) this PR fixes**:

Fixes #33331 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by chaudum** [comment]
I think the test failure is not related to my changes, is it?

```
FAIL	github.com/grafana/grafana/pkg/services/ngalert/notifier	0.135s
```

**Comment by aknuds1** [comment]
> I think the test failure is not related to my changes, is it?
> 
> ```
> FAIL	github.com/grafana/grafana/pkg/services/ngalert/notifier	0.135s
> ```

Restarted the CI build, but there are some build failures now you'll need to look into.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Build failures need fixing.

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by aknuds1** [comment]
Thanks for contributing to Grafana!

**Pull request merged**
