### PR TITLE
Alerting: Fixing mobile notifications in Microsoft Teams

### PR DESCRIPTION
**Pull request by manacker**
Apparently the summary field in a Microsoft Teams webhook request field gets used for the text displayed in mobile push notifications. If that field contains only whitespace the push notification displays the nonsensical text 

> Card - access it on https://go.skype.com/cards.unsupported

Therefore this commit mirrors the notification title in the summary field.
It also removes the unsupported fields Mention and Recipient from the notifier data struct.

### CODE REVIEW

**Comment by torkelo** [comment]
looks strange to have summary and title be the same (Is title shown in mobile notifications), should summary not use message when there is a message and some fallback like "NA" when no message (so no empty string). Is summary used in other clients?

**Comment by manacker** [comment]
Summary and title seem to be used in different contexts:
teams-alert
Summary seems to be used for the activity feed and notifications, while title is used to render the actual chat message.
Here are the iOS notifications top is with empty summary, bottom with a non-empty summary.
img_8009

Hence I think mirroring the title is better than giving no summary at all.

**Comment by manacker** [comment]
@torkelo Do you need anything else from me to get this PR merged?

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Pull request merged**
