### PR TITLE
plugindef: Move pluginmeta out of coremodels as standalone thema lineage

### LINKED ISSUE #54752: Rename `pluginmeta` coremodel
I picked `pluginmeta` as a name for the coremodel because it seemed more or less OK and i didn't know what else to call it.

Turns out, this collides with an existing term of art, "plugin meta," which is used to refer to some actual data about the state of an installed plugin that's communicated out on the frontend.

`pluginmeta` was never a particularly great name for the coremodel anyway, so that's what should change.

cc @wbrowne @ryantxu

### PR DESCRIPTION
**Pull request by sdboyer**
**What this PR does / why we need it**:

This moves `pkg/coremodel/pluginmeta` to `pkg/plugins/plugindef`, detaching it from the coremodel system. It never really made sense there, anyway - it's not an API or a stored type.

The only thing i really had it there for was to take advantage of the codegen apparatus we'd built for coremodels. However, grafana/thema#72 and other PRs there, as well as systems introduced in #56492 make it easy to turn plugindef codegen into a standalone thing.

Also, i added JSON schema generation, so `docs/sources/developers/plugins/plugin.schema.json` is now generated from the canonical thema lineage. While technically correct, the json schema generator is a bit rough, and it may be desirable to turn it off in this PR, and re-enable it once some of those issues are worked out.

**Which issue(s) this PR fixes**:

Fixes #54752
Fixes grafana/schematization-and-as-code-project#23

**Special notes for your reviewer**:

@wbrowne - i think we only vaguely discussed this before, but this really doesn't change your workflow - you're just editing the file in a different place.

### CODE REVIEW

**Comment by sdboyer** [comment]
cc @ryantxu

**Comment by sdboyer** [comment]
i've enabled JSON schema gen in order to facilitate conversation - while the actual generated fields should be correct, there's definitely some fuzz in here that needs working out.

Some of it should be minor changes in [thema's generator](https://pkg.go.dev/github.com/grafana/thema@v0.0.0-20221021160812-3ef5bd1be3fd/encoding/jsonschema#GenerateSchema) (e.g. it seems i may have inserted `$schema` fields in the wrong place? the JSON schema validator i use vs. my GoLand uses seems to disagree 😱 ). Also, preserving the `paths/components` structure from openapi is...maybe? something to change - i suspect hoisting the root schema def up to the root level, then reference all the other sub-schemas would be more idiomatic.

The other thing that'll we'll probably want to modify is the top-level header that's generated. That one will be for us to fill on the Grafana side - there's no logical place in Thema to pass that through.

The big shift though, obviously, is that we're going from a monolithic JSON Schema to one that's broken up into a bunch of discrete sub-schemas, as that's how we've rewritten pluginmeta/plugindef in order to have it generate friendly Go types.

**Comment by sdboyer** [comment]
> This is OpenAPI - is this fully JSON schema compatible nowadays?

Yes, OpenAPI 3.1 == JSON Schema. It says openapi in the output because the generator i wrote starts from oapi3.0 output and translates to 3.1. 

> FYI we use a tool today to generate the markdown of this page

indeed, this generated page has been a subject of considerable discussion :)

I think that'd be a good way of at least starting the conversation about how well the converted thing works. That said, one of the codegen pipeline outputs for the kind system is intended to be docs, similar to but more than what you have there, so medium-term plugindef can just come along for the ride and use that generator.

(just FYI, there's precedent here - Vector has built [the (considerable) structured data](https://github.com/vectordotdev/vector/tree/master/website#structured-data) on their website from CUE for a couple years now)

**Comment by marefr** [comment]
> Yes, OpenAPI 3.1 == JSON Schema. It says openapi in the output because the generator i wrote starts from oapi3.0 output and translates to 3.1.

Great

> I think that'd be a good way of at least starting the conversation about how well the converted thing works. That said, one of the codegen pipeline outputs for the kind system is intended to be docs, similar to but more than what you have there, so medium-term plugindef can just come along for the ride and use that generator.

I guess it's just a matter of finding the right balance when it make sense to update the generated markdown file, whether now or later. Maybe a middle-way would be to generate a plugin.schema.json v2 side-by-side with the current one as a first step to be able to get this merged and then later figure out the docs situation when codegen for docs is a thing/stable?

> (just FYI, there's precedent here - Vector has built [the (considerable) structured data](https://github.com/vectordotdev/vector/tree/master/website#structured-data) on their website from CUE for a couple years now)

Oh interesting

**Comment by sdboyer** [comment]
With #56492 merged, it's now reasonable to pick this back up. @grafana/plugins-platform-backend have been looking at all of these systems quite a bit recently, and i do want to step back and make space for them to really own this as soon as possible. However, that'll be a _lot_ easier after the transition away from coremodels is complete.

So, i'll get this at least basically into shape first.

**Comment by sdboyer** [comment]
i think this now qualifies as "basically in shape"! i think you folks can drive this PR from here.

If you want to avoid doing JSON schema generation until some of the ergonomics issues are worked out, simply [change this line](https://github.com/grafana/grafana/pull/56765/files#diff-df73deafc225e39302e027d938cdc67264af42022b3b5cf21b0d08b0aa380db0R36) to not add that jenny from the jennylist.

**Comment by chri2547** [comment]
No docs impact, so I am removing @knylander-grafana and myself from this PR. Thanks!

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
