### PR TITLE
Frontend: Migrate `DataSourceHttpSettings.tsx` from aria-label e2e selectors to data-testid

### LINKED ISSUE #78412: Frontend Platform: Migrate from aria-label e2e selectors to data-testid
Hi @grafana/grafana-frontend-platform!

A while back to changed to prefer using `data-testid` for E2E selectors instead of `aria-label`. There's only a few of these old `aria-label`-based selectors left, so we've made this list of files that your team owns so we can tidy them up 🙌.

For some guidance on how exactly to fix these, check out [this comment](https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512).

There are 17 issues over 15 files:

- [x] 1 issue in `packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/DateTimePickers/TimeRangeInput.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/Drawer/Drawer.tsx` 
- [x] 2 issues in `packages/grafana-ui/src/components/Menu/SubMenu.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/PageLayout/PageToolbar.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/PanelChrome/LoadingIndicator.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/QueryField/QueryField.tsx` 
- [x] 1 issue in `public/app/core/components/AppChrome/News/NewsContainer.tsx` 
- [ ] 1 issue in `public/app/core/components/AppChrome/SectionNav/SectionNavItem.tsx` 
- [x] 1 issue in `public/app/core/components/ForgottenPassword/ChangePassword.tsx` 
- [x] 2 issues in `public/app/core/components/Login/LoginForm.tsx` 
- [x] 1 issue in `public/app/core/components/PageHeader/PanelHeaderMenuItem.tsx` 
- [x] 1 issue in `public/app/core/components/PasswordField/PasswordField.tsx` 
- [x] 1 issue in `public/app/core/components/QueryOperationRow/QueryOperationAction.tsx` 
- [x] 1 issue in `public/app/core/components/Select/OldFolderPicker.tsx`

### PR DESCRIPTION
**Pull request by codejagaban**
**What is this feature?**

This PR updates the e2e test labels on `packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx` to use `data-testid`

**Which issue(s) does this PR fix?**:

Related to #78412 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by 0xJamin** [comment]
Hi @tskarhed, I just updated the branch

**Review by tskarhed — APPROVED** [review]
Looks good! Thank you!

**Comment by JoaoSilvaGrafana** [comment]
Hey @0xJamin ! Sorry to ask this again but could you merge main into your branch one more time? 😅  It is detecting some breaking changes that are unrelated to your PR so I think it is because it is out of date with main.

**Comment by codejagaban** [comment]
Hi @JoaoSilvaGrafana  I just merged `main` to the branch but it seems something is still failing😕

**Pull request merged**
