### PR TITLE
Docs: fix image, add nginx code type

### PR DESCRIPTION
**Pull request by robbymilo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
LGTM

**Comment by robbymilo** [comment]
@aknuds1 Would you be able to merge?

**Comment by aknuds1** [comment]
@robbymilo Yes. Do you lack permission to merge yourself though? Usually we let the PR author (unless external) merge.

**Comment by robbymilo** [comment]
Yep, it said not authorized.

**Comment by aknuds1** [comment]
Ok, that's strange. Maybe you need to get your permissions checked?

**Pull request merged**
