### PR TITLE
Save hidden status of graph panel

### PR DESCRIPTION
**Pull request by mtanda**
- https://github.com/grafana/grafana/issues/2055

Need discussion for this feature.

### CODE REVIEW

**Comment by torkelo** [comment]
not sure this should be saved

**Comment by mtanda** [comment]
At least, this is useful for snapshot.
The snapshot should show same view for user who is shared snapshot url.
If there are many series in graph, user may want to show only the irregular pattern series when investigating about ALERT.

I don't think save this in default.
Need to add option for this feature.
- Save status for snapshot only, add option in snapshot dialog
- Add dashboard option whether save status or not

**Comment by torkelo** [comment]
yea, it's true, very useful for snapshot, and for state to be included in urls

**Comment by mtanda** [comment]
"Save status for snapshot only" seems to be good option.
Thanks for feedback :-)

**Comment by torkelo** [comment]
I don't think an graph option is needed though. To many options already.

**Comment by mtanda** [comment]
You means save status in default (without checkbox)?

I intend to change the code like, 
- save hidden status in this code path only https://github.com/grafana/grafana/blob/ec98b7d672f81f9a10130aa6633ceebb1cce69de/public/app/features/dashboard/shareSnapshotCtrl.js#L58
- and other code path for save/export dashboard, don't save hidden status.
- add a checkbox in snapshot dialog

**Comment by torkelo** [comment]
closing this, drifted to far from master, and not that many votes for https://github.com/grafana/grafana/issues/2055

**Pull request closed without merging**
