### PR TITLE
Alerting: use virtualized list of namespaces / groups for cloud rules

### PR DESCRIPTION
**Pull request by gillesdemey**
**What this PR does / why we need it**:

This PR uses a virtualized list for selecting namespaces / groups when authoring Mimir or Loki alert or recording rules.

It also removed a separate "Add new item" option from the bottom of the list as it's not compatible with large lists – instead I've added the `allowCustomValue` property that allows creating custom values by typing in the `Select` component.

**Special notes for your reviewer**:

This also adds a small fix to the `VirtualizedList` when the amount of options is smaller than `maxHeight`.

### CODE REVIEW

**Comment by konrad147** [comment]
Don't we need to do the same for Grafana-managed alerts?
I noticed a filtering issue (I assume it's caused by how virtualization works)
image

I think we need to rethink the `Add new namespace/Add new group` items as we've had many complaints about places where these were missing

**Comment by soniaAguilarPeiron** [comment]
> Don't we need to do the same for Grafana-managed alerts?

💯 I think we should be consistent. This virtualized solution should be applied in **folders**/**namespaces** and **groups**.

> I think we need to rethink the `Add new namespace/Add new group` items as we've had many complaints about places where these were missing We could try to make that option sticky outside of the virtualized component, sth like this (however, might be tricky due to virtual list positioning)

I believe moving this `+Add new` to the first position of the group could be a possible solution.

> 
> ```js
> const MenuList = (
>   props: MenuListProps<ColourOption | FlavourOption, false, GroupedOption>
> ) => {
>   return (
>     <components.MenuList {...props}>
>       <div>+Add New Group</div>
>         <Virtualized>{props.children}</Virtualized>
> 	 <div>+Add New Group</div>
>     </components.MenuList>
>   );
> };
> ```
> 
> As a further step, we could consider a different namespace/group selection method for such cases. E.g If we need to display 1k namespaces or groups maybe we should open a modal where the user can select namespace and group (It would be useful to display the evaluation interval for each group, so the user has some criteria on which the selection could be made)

**Review by soniaAguilarPeiron — APPROVED** [review]
LGTM!
I added a non-blocking comment. 
I think we should do the same for grafana-managed alert rules drop-downs (folders/groups)

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by gillesdemey** [comment]
Yep I agree, I think we should also do this for Grafana managed alerts and come up with a better way than using virtualised lists eventually. I'll create a separate PR for Grafana managed alerts.

As for the issue you're observing with the height, yea that's simply because of how the virtualized list works in combination with the `Select` component – I don't have access to how many hits we have when filtering so I can't update the container height :(

**Pull request merged**
