### PR TITLE
Docs: combines all SAML topics into one topic (#49443)

### PR DESCRIPTION
**Pull request by chri2547**
This PR backports changes to the SAML docs

### CODE REVIEW

**Comment by brendamuir** [comment]
Looks good to me.

**Review by jdbaldry — DISMISSED** [review]
I believe the `docs/sources/enterprise/saml` directory should not exist any more.

**Review by jdbaldry — COMMENTED** [review]
Actually it looks like some of those files were left in place for #49443 too. @chri2547 Can you confirm if all the `/docs/sources/enterprise/saml` files should now be removed? I can remove them in a separate PR if so.

**Comment by chri2547** [comment]
> Actually it looks like some of those files were left in place for #49443 too. @chri2547 Can you confirm if all the `/docs/sources/enterprise/saml` files should now be removed? I can remove them in a separate PR if so.


> Actually it looks like some of those files were left in place for #49443 too. @chri2547 Can you confirm if all the `/docs/sources/enterprise/saml` files should now be removed? I can remove them in a separate PR if so.

They should be removed.

**Review by jdbaldry — APPROVED** [review]

**Pull request merged**
