### PR TITLE
upgrade to golang 1.11

### PR DESCRIPTION
**Pull request by bergquist**
* Link the PR to an issue for new features
* Rebase your PR if it gets out of sync with master

**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

### CODE REVIEW

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/issues/13030

**Comment by torkelo** [comment]
looks like we have to wait a day or two, circle ci don't have an image for it yet

**Comment by bergquist** [comment]
yupp. Kinda dispointing. But I don't think its worth spending time solving that :)

**Comment by mh720** [comment]
circleci/golang:1.11 is now available.

**Comment by bergquist** [comment]
I rerunned CI and it looks like we have a few vetting errors in golang 1.11

**Review by xlson — COMMENTED** [review]
Looks great. We need to update the Grafana build container as well (`grafana/build-container:1.0.0` has go.1.10). I'm rebuilding it as we speak, tried doing it on the build server on Friday but it kept failing for some reason.

**Pull request merged**
