### PR TITLE
Plugins: Refactor Plugin Management

### LINKED ISSUE #40476: Plugin Manager API V2
Bring better shape to the `plugins` and `manager` package so that it is more easier to test, navigate and maintain.

### PR DESCRIPTION
**Pull request by wbrowne**
**What this PR does / why we need it**:
The plugins package has been quite difficult to navigate and maintain in the past, so this PR tries to bring some better shape to it all. This branch originally started with some experimental ideas in a few different directions, hence its age - but this should largely now just be about refactoring to set the stage for changes to come (remote plugins, HA support, consistent Grafana API, to name a few 👼 )

Overview of changes:
- Splitting of the existing Plugin Manager interface into multiple smaller interfaces (`PluginClient`, `PluginStore`, for example) so that dependants only get what they need
- Merging of both existing Plugin Managers into one
- Introduction of a `PluginLoader` component (and sub-components) which are responsible for finding, loading and initializing plugins to make it easier to maintain the intricacies of plugin discover, validation, signing, etc.
- Moves Grafana Pro signature hook `unsignedPluginConditionFunc` used in Enterprise from `Plugin Manager` to new `signature` subpackage
- Moves Grafana version checking into new dedicated service `grafana_update_checker.go`
- Streamlining the plugin request flow (POST `/ds/query` -> `PluginManager.QueryData()`)
- Removing abstractions around plugin types, so now the plugin model is more flexible
- ~Introduce the ability for a renderer plugin to be installed at runtime (some changes required in the [renderer itself](https://github.com/grafana/grafana-image-renderer) before this is ready)~
- Reorganizes the `test` data source plugin to look and feel more like the other Core plugins

**Which issue(s) this PR fixes**:

Fixes #40476 (just for tracking)

Related Enterprise PR: https://github.com/grafana/grafana-enterprise/pull/2123

**Special notes for your reviewer**:

Please note that this is merely the first (albeit large) step to re-imagine how we deal with plugins inside Grafana. This change is already quite large and doesn't necessarily do anything majorly different than what we do already. The intention is to re-organize things so that we are better equipped to make the bigger changes we need to.

### CODE REVIEW

**Review by marefr — COMMENTED** [review]
Some initial comments/suggestions. Great work! Haven't found any big issue yet. Haven't gone through all changes yet and need to take it for a spin as well.

**Review by marefr — COMMENTED** [review]
Added some additional comments/suggestions. Gone through all the code now. Think it looks great. Some things we can continue to iterate on later. I'm going to take it for a spin as well

**Review by marefr — DISMISSED** [review]
Did some tests of the image renderer, see below. Also commented on some code related to plugin loggers. Sorry for the spam

1. Uninstalled grafana-image-renderer v3.0.1
1. Installed grafana-image-renderer latest 
1. Refreshed browser
1. :exclamation: Opened dashboard and direct link rendered image

<details><summary>Details</summary>

runtime error: invalid memory address or nil pointer dereference

Error details
/usr/local/go/src/runtime/panic.go:221 (0x454a66)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:735 (0x454a36)
	sigpanic: panicmem()
/home/marcus/go/src/github.com/grafana/grafana/pkg/services/rendering/plugin_mode.go:43 (0x1311ca1)
	(*RenderingService).renderViaPlugin: rsp, err := rs.renderer().Render(ctx, req)
/home/marcus/go/src/github.com/grafana/grafana/pkg/services/rendering/rendering.go:226 (0x131397c)
	(*RenderingService).render: return rs.renderAction(ctx, renderKey, opts)
/home/marcus/go/src/github.com/grafana/grafana/pkg/services/rendering/rendering.go:154 (0x13130f7)
	(*RenderingService).Render: result, err := rs.render(ctx, opts)
/home/marcus/go/src/github.com/grafana/grafana/pkg/api/render.go:55 (0x20ec447)
	(*HTTPServer).RenderToPng: result, err := hs.RenderService.Render(c.Req.Context(), rendering.Opts{
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0x160f473)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:55 (0x160f462)
	RequestMetrics.func1.1: c.Next()
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0xdc1cfa)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/macaron.go:155 (0xdc1cec)
	(*Macaron).UseMiddleware.func1: c.Next()
/usr/local/go/src/net/http/server.go:2046 (0x6d8b2e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/csp.go:22 (0x160bc72)
	AddCSPHeader.func1.1: next.ServeHTTP(rw, req)
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0xdc1cfa)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/macaron.go:155 (0xdc1cec)
	(*Macaron).UseMiddleware.func1: c.Next()
/usr/local/go/src/net/http/server.go:2046 (0x6d8b2e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/render.go:44 (0xdbc9e6)
	Renderer.func1.1: next.ServeHTTP(rw, req)
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0x160e7ca)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:167 (0x160e7c1)
	Recovery.func1: c.Next()
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:32 (0xdb9afb)
	ContextInvoker.Invoke: invoke(params[0].(*Context))
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:139 (0xdbaa94)
	(*injector).fastInvoke: return f.Invoke(in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:117 (0xdba9bc)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0xdc1cfa)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/macaron.go:155 (0xdc1cec)
	(*Macaron).UseMiddleware.func1: c.Next()
/usr/local/go/src/net/http/server.go:2046 (0x6d8b2e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/gziper.go:75 (0x1610a58)
	Gziper.func1.1: next.ServeHTTP(grw, req)
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0x160c684)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0x160c66d)
	Logger.func1: c.Next()
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:62 (0x1611039)
	(*Context).Next: ctx.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:57 (0x1611028)
	RequestTracing.func1: c.Next()
/usr/local/go/src/reflect/value.go:543 (0x4e5553)
	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
/usr/local/go/src/reflect/value.go:339 (0x4e4b04)
	Value.Call: return v.call("Call", in)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:159 (0xdbad26)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/inject.go:119 (0xdba974)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/context.go:67 (0xdb9c0b)
	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/router.go:156 (0xdbe31d)
	(*Router).Handle.func1: c.run()
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/router.go:223 (0xdbefb1)
	(*Router).ServeHTTP: h(rw, req, p)
/home/marcus/go/src/github.com/grafana/grafana/pkg/macaron/macaron.go:189 (0xdbc330)
	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:2878 (0x6dc09a)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1929 (0x6d7c07)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x471de0)
	goexit: BYTE	$0x90	// NOP
Check the Grafana server logs for the detailed error message.
</details>

5. Restart grafana server 
1. :heavy_check_mark: Render panel via direct link rendered image works as expected 

1. Configuring remote renderer 
1. :exclamation: Render panel via direct link rendered image and seems like the renderer plugin is still used rather than the remote service:

<details><summary>Details</summary>

INFO[10-20|15:05:28] Backend rendering via external http server logger=renderer.http version=3.2.1
DBUG[10-20|15:05:28] starting plugin                          logger=plugin.initializer pluginId=grafana-image-renderer path=/home/marcus/go/src/github.com/grafana/grafana/data/plugins/grafan
a-image-renderer/plugin_start_linux_amd64 args=[/home/marcus/go/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer/plugin_start_linux_amd64]
DBUG[10-20|15:05:28] plugin started                           logger=plugin.initializer pluginId=grafana-image-renderer path=/home/marcus/go/src/github.com/grafana/grafana/data/plugins/grafan
a-image-renderer/plugin_start_linux_amd64 pid=296724                                           
DBUG[10-20|15:05:28] waiting for RPC address                  logger=plugin.initializer pluginId=grafana-image-renderer path=/home/marcus/go/src/github.com/grafana/grafana/data/plugins/grafan
a-image-renderer/plugin_start_linux_amd64      
</details>

**Review by marefr — COMMENTED** [review]
Some additional rendering comments. One suggestion that's needed if we want to continue down the path or revert - see comments.

**Review by marefr — APPROVED** [review]
LGTM :tada:

**Review by jackw — APPROVED** [review]
Amazing work on this @wbrowne. I'm not a backend dev but I took it for a spin locally and attempted installing, uninstalling, updating, loading, and configuring plugins and cannot fault it. 🥇

**Review by mckn — APPROVED** [review]
LGTM! Great work on this

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
