### PR TITLE
Accesscontrol jprice use false not 0

### PR DESCRIPTION
**Pull request by donomii**
What this PR does / why we need it:

This changes the is_service_account column to nullable, to allow graphana cloud to run multiple versions?

Which issue(s) this PR fixes:

is_service_account column should be nullable

### CODE REVIEW

**Review by eleijonmarck — APPROVED** [review]

**Review by sakjur — CHANGES_REQUESTED** [review]
You want to use `mg.Dialect.BooleanStr(false)` to get the appropriate falsy string.

Don't modify the existing migration, add an altering migration since the current version has already been released. (refer to https://github.com/grafana/grafana/blob/main/contribute/architecture/backend/database.md#migrations )

**Review by eleijonmarck — APPROVED** [review]

**Comment by vtorosyan** [comment]
@donomii are there any blockers for addressing the comments? It would be great to have this merged for 8.4 release

**Comment by donomii** [comment]
There are large blockers and this probably won't make it to 8.4 .  SQLite
doesn't like modifying tables, the procedure will be complicated.

**Comment by sakjur** [comment]
Continued in #45541

**Pull request closed without merging**
