### PR TITLE
Chore: Prettier ignore api-merged & api-spec swagger api specs

### PR DESCRIPTION
**Pull request by joshhunt**
**What this PR does / why we need it**:

 - Prevent prettier from formatting the generated api spec files
 - Regenerate api spec files to remove any prettier formatting

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by papagian** [comment]
the enterprise routes are missing; you have to run `make swagger-api-spec` after you have enabled enterprise so that those routes get discovered.
For context: whatever is imported by the work dir that is passed to the swagger command ([pkg/server](https://github.com/grafana/grafana/blob/67d817ff48af54b4767ebd5eecc390193c965b9b/Makefile#L46) in our case)
is scanned for swagger annotations
so the enterprise routes will be discovered only if they exist under [this](https://github.com/grafana/grafana/blob/67d817ff48af54b4767ebd5eecc390193c965b9b/pkg/server/server.go#L19) import

**Comment by papagian** [comment]
we have to exclude also the alerting ones:
- [api.json](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/api.json)
- [post.json](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/post.json)
- [spec.json](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/spec.json)

**Comment by joshhunt** [comment]
@papagian how is alerting's post.json generated? 

I deleted alerting's three specs, ran `make swagger-api-spec`, and it remade api.json and spec.json, but not post.json?


```
> rm pkg/services/ngalert/api/tooling/api.json pkg/services/ngalert/api/tooling/post.json pkg/services/n
galert/api/tooling/spec.json

> git status
On branch joshhunt/prettier-ignore-api-spec
Your branch is up to date with 'origin/joshhunt/prettier-ignore-api-spec'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .prettierignore
        deleted:    pkg/services/ngalert/api/tooling/api.json
        deleted:    pkg/services/ngalert/api/tooling/post.json
        deleted:    pkg/services/ngalert/api/tooling/spec.json

> make swagger-api-spec
[...]

> git status
On branch joshhunt/prettier-ignore-api-spec
Your branch is up to date with 'origin/joshhunt/prettier-ignore-api-spec'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .prettierignore
        modified:   pkg/services/ngalert/api/tooling/api.json
        deleted:    pkg/services/ngalert/api/tooling/post.json
        modified:   pkg/services/ngalert/api/tooling/spec.json
        modified:   public/api-merged.json
        modified:   public/api-spec.json
```

**Comment by papagian** [comment]
> @papagian how is alerting's post.json generated?

unfortunately it's not triggered by `make swagger-api-spec` (I need to investigate/fix it)

try:
`make pkg/services/ngalert/api/tooling/api.json`
or
`make -C pkg/services/ngalert/api/tooling api.json`

**Comment by joshhunt** [comment]
Unfortunately @papagian both those commands generate only api.json :(

Would it be fine if we just didn't prettier-ignore the alerting specs for now?

**Review by papagian — APPROVED** [review]

**Comment by papagian** [comment]
> Would it be fine if we just didn't prettier-ignore the alerting specs for now?

sure, I'll make a follow up PR now that I know how to ignore them 😄

**Pull request merged**
