### PR TITLE
Database: Adds support for enable/disable SQLite Write-Ahead Logging (WAL) via configuration

### PR DESCRIPTION
**Pull request by marefr**
Seen a lot of database locked statements of the Grafana server when E2E tests are run. Not sure that's the main reason though E2E tests are flaky. Trying to use #17912 to see if it makes any difference

First build passed: https://drone.grafana.net/grafana/grafana/87486/5/15
Second build failed, however on the mysql integration tests: https://drone.grafana.net/grafana/grafana/87492/1/1
Third build passed: https://drone.grafana.net/grafana/grafana/87495
Fourth build passed: https://drone.grafana.net/grafana/grafana/87557
Fifth build passed: https://drone.grafana.net/grafana/grafana/87558
Sixth build passed: https://drone.grafana.net/grafana/grafana/87613

### CODE REVIEW

**Comment by DanCech** [comment]
This seems like a good idea, what do you think next steps toward getting it merged should be @marefr ?

**Comment by marefr** [comment]
@DanCech the idea is to enable to run builds of this PR in drone in a cron for a day or something to confirm it doesn't make builds worse. @dsotirakis  going to help with that

**Comment by dsotirakis** [comment]
Triggered some crons having cherry picked your change @marefr. 💪 
We'll come back with results!

**Comment by papagian** [comment]
I agree, this also in accordance to [this go-sqlite3 comment](https://github.com/mattn/go-sqlite3/issues/607#issuecomment-404765142).

**Review by papagian — COMMENTED** [review]
Maybe we should consider turning it also on for [unit](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/services/sqlstore/sqlutil/sqlutil.go#L18) and [testinfra](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/tests/testinfra/testinfra.go#L217) tests.

Also should we include it in the configuration docs?

**Comment by marefr** [comment]
> Maybe we should consider turning it also on for [unit](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/services/sqlstore/sqlutil/sqlutil.go#L18) and [testinfra](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/tests/testinfra/testinfra.go#L217) tests.
> 
> Also should we include it in the configuration docs?

Think those are using sqlite inmemory so not sure using WAL there makes any difference. Do you know?

**Comment by marefr** [comment]
> Triggered some crons having cherry picked your change @marefr. muscle We'll come back with results!

15 runs without an e2e failure. @dsotirakis suggests to merge this :tada: Just need to make sure docs etc are in place.

**Review by dsotirakis — APPROVED** [review]
🚀

**Review by kminehart — APPROVED** [review]

**Comment by papagian** [comment]
> > Maybe we should consider turning it also on for [unit](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/services/sqlstore/sqlutil/sqlutil.go#L18) and [testinfra](https://github.com/grafana/grafana/blob/f2cb248d931b74358aed733810ca9354c5e3a361/pkg/tests/testinfra/testinfra.go#L217) tests.
> > Also should we include it in the configuration docs?
> 
> Think those are using sqlite inmemory so not sure using WAL there makes any difference. Do you know?

good point; unit tests definitely use the in-memory database and so seems to do testinfra: it calls the following function:
https://github.com/grafana/grafana/blob/5d73f7f8e8561bf40fc28c6077c5d006af05b473/pkg/services/sqlstore/sqlstore.go#L93-L95
which makes think whether the present changes have any effect on the tests 🤔 ?

as far as whether it has any effect, from [this](https://sqlite.org/forum/forumpost/1d7f50652d) I understand that not exactly, so most probably you are right.

**Review by papagian — APPROVED** [review]

**Comment by DanCech** [comment]
Hmm, why are we still seeing failures from the enterprise tests?

**Review by chri2547 — APPROVED** [review]

**Comment by dsotirakis** [comment]
@DanCech @marefr flakey tests as always.
People rarely pay attention to the OSS->Enterprise checks **because** of the flakey tests.
Sooner or later we should be able to make this check mandatory provided that there are no flakey tests to block the OSS author for no good reason.
If you have a closer look at the tests which failed in enterprise, you'll realise that they are unrelated.

**Comment by papagian** [comment]
> @DanCech @marefr flakey tests as always. People rarely pay attention to the OSS->Enterprise checks **because** of the flakey tests. Sooner or later we should be able to make this check mandatory provided that there are no flakey tests to block the OSS author for no good reason. If you have a closer look at the tests which failed in enterprise, you'll realise that they are unrelated.

I think that the failure is because of `database is locked` which it seems related

> https://drone.grafana.net/grafana/grafana-enterprise/42231

But I think that the tests fail because they use the in-memory database so present change do not have effect on that.

**Comment by marefr** [comment]
This [build](https://drone.grafana.net/grafana/grafana/89087/1/6) it was only frontend test failing so nothing to do with these changes. Seems like I need to merge with latest main to get rid of some flakyness, I'll do that

**Comment by marefr** [comment]
Seems to me like the redis and memcached integration tests runs all the integration tests again even not all of them using any of this storage - seems like we might be able to exclude those tests, not sure how though

**Comment by marefr** [comment]
Thinking about database locked errors in general I got the impression that integration tests that starts up it's own Grafana instance runs a lot of things in parallel when the instance starts up and they're competing to get access to sqlite. However, this would in my mind be a general problem when Grafana starts up for any user using sqlite so it's very confusing. Guess using sqlite inmemory mode shouldn't affect tests targeting different Grafana test instances, or do they?

**Comment by marefr** [comment]
> Drone build failed: https://drone.grafana.net/grafana/grafana-enterprise/42277

Looking at the failure it's in test-backend step and in pkg/tests/api/alerting - these tests should be prefixed with `TestIntegration`, but they're not. Seems some other tests under pkg/tests has the same problem. We should fix this.

**Comment by marefr** [comment]
> Either way I'd like to find out rather than just assume the tests are flaky and ignore the failures.

@DanCech Agree, but shouldn't be a blocker for this PR so I'm gonna go ahead and merge this. Ok?

**Comment by DanCech** [comment]
> > Either way I'd like to find out rather than just assume the tests are flaky and ignore the failures.
> 
> @DanCech Agree, but shouldn't be a blocker for this PR so I'm gonna go ahead and merge this. Ok?

I agree that this PR should only improve things, and we shouldn't block it from being merged 👍

**Comment by DanCech** [comment]
> Seems to me like the redis and memcached integration tests runs all the integration tests again even not all of them using any of this storage - seems like we might be able to exclude those tests, not sure how though

For MySQL and Postgres I think the intent is that we run all the same integration tests against those backends that we've run against sqlite to make sure that everything works against all 3 databases.

For redis and memcached we could possibly provide a "Cache" flag when we call `go test` and name them something like `TestIntegrationCacheBlah` which would allow those runs to not re-run tests that aren't applicable to the caching.

> Looking at the failure it's in test-backend step and in pkg/tests/api/alerting - these tests should be prefixed with `TestIntegration`, but they're not. Seems some other tests under pkg/tests has the same problem. We should fix this in a separate PR.

Whether tests should be run as part of the integration phase or the main unit testing phase is a separate discussion I think.

> Thinking about database locked errors in general I got the impression that integration tests that starts up it's own Grafana instance runs a lot of things in parallel when the instance starts up and they're competing to get access to sqlite. However, this would in my mind be a general problem when Grafana starts up for any user using sqlite so it's very confusing. Guess using sqlite inmemory mode shouldn't affect tests targeting different Grafana test instances, or do they?

I'm not sure how inmemory mode interacts with this, but I have the same understanding as you and the concern that under load we may see the same behavior in production especially during periods where background tasks are accessing the database.

**Comment by marefr** [comment]
> Whether tests should be run as part of the integration phase or the main unit testing phase is a separate discussion I think.

Sorry forgot to add that we already have some other tests under pkg/tests that uses `TestIntegration` prefix so we should change this to either one to make it consistent. I'm in favor of having all of those as `TestIntegration` so might open a PR to fix that.

> For MySQL and Postgres I think the intent is that we run all the same integration tests against those backends that we've run against sqlite to make sure that everything works against all 3 databases.

Yes exactly
 
> For redis and memcached we could possibly provide a "Cache" flag when we call `go test` and name them something like `TestIntegrationCacheBlah` which would allow those runs to not re-run tests that aren't applicable to the caching.

Sounds like a good suggestion to me. However, looks like we earlier might have used build tags to run integration tests for redis and these tests never run I guess which is not great:
https://github.com/grafana/grafana/blob/d9b8b761e9b2a6da4f9fdc88afc9a646e52f3364/pkg/infra/remotecache/redis_storage_integration_test.go#L1-L2 
https://github.com/grafana/grafana/blob/d9b8b761e9b2a6da4f9fdc88afc9a646e52f3364/pkg/infra/remotecache/memcached_storage_integration_test.go#L1-L2

For enterprise though there are no build tags for redis/memcached integration tests.

> I'm not sure how inmemory mode interacts with this, but I have the same understanding as you and the concern that under load we may see the same behavior in production especially during periods where background tasks are accessing the database.

Yeah I have the same concern. When those problems arise that's when we normally suggest to migrate using MySQL or Postgres :)

**Pull request merged**
