### PR TITLE
fix: do not run apk on non-alpine distros

### PR DESCRIPTION
**Pull request by simPod**
**What is this feature?**

Does not run `apk` when not available.

**Why do we need this feature?**

alpine is not always used:

```
#11 [go-builder  2/22] RUN apk add --no-cache binutils-gold
#11 0.337 /bin/sh: 1: apk: not found
#11 ERROR: process "/bin/sh -c apk add --no-cache binutils-gold" did not complete successfully: exit code: 127
------
 > [go-builder  2/22] RUN apk add --no-cache binutils-gold:
0.337 /bin/sh: 1: apk: not found
------
Dockerfile:44
--------------------
  42 |     
  43 |     # This is required to allow building on arm64 due to https://github.com/golang/go/issues/22040
  44 | >>> RUN apk add --no-cache binutils-gold
  45 |     
  46 |     # Install build dependencies
```

**Who is this feature for?**

I'm using `GO_IMAGE="golang:1.21.6-bullseye"`

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by briangann** [comment]
the apk add could be moved down a couple of lines into the other detect/install section, but this looks good to me.

**Review by briangann — APPROVED** [review]

**Comment by aangelisc** [comment]
Hi @simPod, are you able to follow @briangann's suggestion and move this installation into the existing installation block?

**Comment by simPod** [comment]
@aangelisc I did not want to couple those unrelated RUNs. Is that something you want to do?

**Comment by aangelisc** [comment]
@simPod I think it's fine to have them all in the same location 😊

**Comment by simPod** [comment]
done

**Review by DanCech — APPROVED** [review]
LGTM

**Comment by simPod** [comment]
Fdiye

**Pull request merged**
