### PR TITLE
Prometheus: Metrics browser can now handle label values with special characters.

### LINKED ISSUE #39341: [Metrics Explorer] facetting does not escape double-quotes in label values
**What happened**:

While using the Metrics Explorer with a Prometheus source (and likely with any other source), the facetting system is not escaping double-quotes in label **values**.

We noticed this with Hazelcast Jet JMX metrics being exported to Prometheus, which often have labels that include double-quotes in their values (note how the value itself has double-quotes in this picture):

grafana1

As a result of not escaping the double-quotes in the value, the resulting Prometheus query is invalid (see the arrows in the above picture). If we try to execute the query anyway, naturally we get a parsing error:

grafana2

**What you expected to happen**:

We expected any values in the facetted labels to be properly escaped so the generated Prometheus queries just work. In the above example, if we manually escape the double-quotes in the query, then it works as expected:

grafana3

**How to reproduce it (as minimally and precisely as possible)**:

1. First you will need data in Prometheus whose label **values** contain double-quotes.
2. Then, go to the Grafana Metrics Explorer and open the *Metrics browser* dropdown menu.
3. Now select any metrics whose labels contain double-quotes and then select any of such labels.
4. Once you select a proposed label value with double-quotes in it, notice how they are not escaped in the generated Prometheus query to use.

**Anything else we need to know?**:

We do not have other data sources with double-quotes in the labels, but probably this affect any data source whose query language uses double-quotes for enclosing values, thus needing to escape them for value data.

**Environment**:
- Grafana version: `8.1.4`
- Data source type & version: Prometheus v2.29.2 (not a Prometheus issue)
- OS Grafana is installed on: Docker Swarm running on Linux CentOS
- User OS & Browser: Windows 10 with Google Chrome (not a browser issue)
- Grafana plugins: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by gabor**
fixes https://github.com/grafana/grafana/issues/39341

prometheus label-values can contain basically any character. so in some cases, when we create a promql query, we have to add some escaping:

- for not-regex selectors, we need to escape 3 characters: the newline-character, the double-qoute (`"`) character, and the backslash (`\`) character. for example:
  - if your label-value is `hello"world`, then it has to become: `{val="hello\"world"}`
- for regex selectors, every character that has a special meaning in a regular expression needs to be escaped, for example characters like `*` or `$`. also, after escaping those, we also need to do the escaping mentioned above. for example:
  - if your label-value is `h$$llo`, then it has to become: `{val=~"h\\$\\$llo"}`
  - if your label-value is `h$$llo"world`, then it has to become: `{val=~"h\\$\\$llo\"world"}`

NOTE1: this pull-request only fixes the metrics browser:
  - it does not fix the current query-field, because this might make things slower, and the current query-field is going to get replaced in the future, so it did not make sense to invest effort into fixing that one (i had a fix to see if it can be done, it's like 3 lines of code, but it increases the processing of large lists, so i did not add it for now)
  - it does not fix the new query-field, because i wanted to do that as a separate pull-request, i'm a little worried about having a simple implementation, which could have performance issues
 
NOTE2: this is somewhat hard to test, you need a prometheus-instance with weird label-values. i used the python prometheus-client ( https://github.com/prometheus/client_python ) to generate such label-values, and then modified the devenv-prometheus yaml by adding one more scrape target (my python app). i'll attach my python-script here, but it's a simple modification of the tutorial-app from the prometheus-python-client-repo. you need to install the prometheus-python-client lib before running it.

### CODE REVIEW

**Comment by gabor** [comment]
the python script i used:
```
from prometheus_client import start_http_server, Gauge
import time

GAUGE = Gauge('my_gauge', 'my gauge', ['thing'])

v1 = 'f\\oo'
v2 = 'f"oo'
v3 = 'f\noo'
v4 = 'f+oo'
v5 = 'f$oo'
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
GAUGE.labels(thing=v1).set(200)
GAUGE.labels(thing=v2).set(201)
GAUGE.labels(thing=v3).set(202)
GAUGE.labels(thing=v4).set(203)
GAUGE.labels(thing=v5).set(204)

if __name__ == '__main__':
    start_http_server(8000, 'localhost')
    while True:
        time.sleep(1)
```

**Review by ivanahuckova — COMMENTED** [review]
Can we use for this these functions:  https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L921-L927?

**Comment by gabor** [comment]
> Can we use for this these functions: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L921-L927?

@ivanahuckova 
unfortunately not. those functions do something VERY similar, but they are not exactly the same, and i could not find a way to call them from my functions or vice versa, in a good way.

**Review by ivanahuckova — APPROVED** [review]
LGTM, beautiful! 🤩 

Btw how usually test weird lables/values is just by adding them here:
image

**Comment by gabor** [comment]
> LGTM, beautiful! 🤩
> 
> Btw how usually test weird lables/values is just by adding them here: image

that's a great tip, thanks! 👍

**Pull request merged**
