### PR TITLE
Cloudwatch: Add run query button

### PR DESCRIPTION
**Pull request by sunker**
**What is this feature?**

A common problem across all data source plugin query editors in knowing what user interactions should trigger a query to be executed. In the CloudWatch plugin, it's currently handled differently in all modes:
* In the _Metric Search_ and _Metric Query_ builders, a new query is triggered whenever there's a change in the editor 
* In the _Metric Search_ code mode (Math expressions), a new query is triggered when blurring the code editor  
* In the _Metric Query_ code mode (Metrics Insights), there's a "Run query" button that can be used to trigger a new query
* In the Logs editor, new queries are triggered on blur event from the code editor (not when changing log groups)

To add to the confusion, there's also the "Refresh dashboard" spinner icon in dashboard edit and the "Run query" button in Explore. 

This PR adds a "Run queries" (should be pluralized since refreshing actually executes all queries in the panel) button to the query header and it's displayed in all different query types and modes in the CloudWatch plugin. When the user makes a change in the editor, the run queries button switches from `secondary` to `primary` variant (gray to blue in dark mode). When the user clicks the button, it goes back to being a secondary button until there's more changes to the query. Note that the button is still clickable when it's in secondary mode. 

run-query-button

This work is heavily inspired by the query builder for Prometheus. See a video about it [here](https://raintank-corp.slack.com/archives/C0F5GDR4P/p1648627460282739). 

Even though this will force the user to make one extra click when inside the metric builders, I still think it's worth it as it will streamline the user experience across all different query types and modes within the plugin.

**Special notes for your reviewer**:

Note that this **does not** solve the problem of knowing when the query editor is complete and ready to be executed. However, with a "Run queries" button in place, the query editor will get the characteristics of a typical html form. Next step could be to be to render the whole editor within a [Form](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Forms/Form.tsx#L18) component, add field rules to all inputs and selects and then validate the form when the form is submitted (_Run queries_ button is clicked). 

The `onRunQuery` func was shared by almost all components in this plugin, so removing them caused the trillion changes in this PR. I'd be happy to split it in smaller pieces if we want to move further with this.

### CODE REVIEW

**Review by idastambuk — APPROVED** [review]
I really like this, feels nice to have more control over when a query is run

**Comment by catherineymgui** [comment]
I like this, but I wonder if we should keep the consistency w/ Prometheus and Loki and have the run queries button left of the builder / code toggle?

**Comment by taleena** [comment]
> I like this, but I wonder if we should keep the consistency w/ Prometheus and Loki and have the run queries button left of the builder / code toggle?

Here's is how it looks for a couple other data sources I checked in addition to Prom/Loki:
Screenshot 2022-12-12 at 8 05 24 AM

**Comment by sunker** [comment]
> I like this, but I wonder if we should keep the consistency w/ Prometheus and Loki and have the run queries button left of the builder / code toggle?

Yeah good shout! Moved it so that it's placed left of the builder / code toggle.

**Pull request merged**
