### PR TITLE
Explore: Log message line wrapping options for logs

### LINKED ISSUE #19355: Explore: Logs need line wrap options
This came from @pstibrany:

When scanning logs, sometimes it's more efficient to see one line per log message. 
We could achieve this by adding a switch to the log panel options toolbar to enable/disable line wrapping (default: enabled).

The unwrapped setting would result in horizontal scrolling. (alternative: use ellipsis text rendering). 

This option should be added to 

- [ ] Explore's logs panel
- [ ] Dashboard logs panel
- but is not needed in live view.

### PR DESCRIPTION
**Pull request by ivanahuckova**
**What this PR does / why we need it**:
This PR introduces wrap-line options for logs, as for some users it's more efficient to see one line per log message. Switch has been added to the log panel options toolbar to enable/disable line wrapping. The wrapped-line option is set as a default. Unwrapped setting would result in horizontal scrolling. This new feature is implemented for Explore and Logs Panel. It doesn't affect live tailing.

- [x] Create switch for Explore
- [x] Create switch for Logs Panel
- [x] Horizontal scroll for Explore
- [x] Horizontal scroll for Logs Panel
- [x] Line wrap doesn't affect Live-tailing

**Dashboard Logs Panel**
ezgif com-video-to-gif (10)

**Explore**
ezgif com-video-to-gif (9)

**Which issue(s) this PR fixes**:
Fixes #19355

### CODE REVIEW

**Comment by ivanahuckova** [comment]
Hi @davkal! Here are couple options for the next steps - to get the horizontal scroll instead of vertical:
1. I would have to pass down the width to be able to do the horizontal scroll/ellipsis as we are using css table and we don’t have width of row.
2. Instead of using css table, we could use flexbox for the whole logs Explore section -> not sure if there are any performance issues/blockers.
3. We do vertical scroll and also show everything else is visible when you open details.
4. We show just first line of the message and everything else is visible when you open details.
Or maybe you’ll come up with better idea. 🙂

**Comment by davkal** [comment]
Do you mind rebasing the PR?

**Comment by davkal** [comment]
UX feedback:

- I find the in-line scrolling too hard to use, and it interferes with the outer scrolling (it was a nice idea thought)
- the more I think about it, the less I like the idea of horizontal scrolling, so we can scrap that
- I think it's enough for Explore to show the full line on expanded rows
- for the logs panel, let's try simply not showing the non-wrapped part when wrap is off. If someone wants to see more, they need to make the panel wider (or use line wrap)

**Comment by davkal** [comment]
I'm curious if users really need to see the cut-off area when wrapping is off. @pstibrany

**Comment by pstibrany** [comment]
> I'm curious if users really need to see the cut-off area when wrapping is off. @pstibrany

My usage is with log files like this (https://pastebin.com/1xmdC6DN)... wrapped lines are visually distracting, so I would just turn off wrapping and scroll to the right to find message part that I'm interested in. In this case, it's JSON so there may be other tools (but why bother!?), in practice log files I've worked with have common prefix (eg. datetime, thread name, log level, context info, request ID) and the interesting part starts in the middle of the line.

**Comment by ivanahuckova** [comment]
Thanks again @pstibrany for great feedback on this PR. 🧡Super appreciated! @davkal I have implemented horizontal scroll based on agreed. Can you please review. 🙂

**Comment by pstibrany** [comment]
Thanks Ivana, I love this change already, based on video you shared with me!

**Review by davkal — APPROVED** [review]
Code and UX are Looking great!  This can go in as is.

I wonder if it would speed things up by not doing too much per-line styling and rely on outside container div classes instead.

**Pull request merged**
