### PR TITLE
Azure Monitor: Use defaults from datasource if not saved on dashboard/query

### LINKED ISSUE #19722: Dashboards using Azure Monitor data source shows no data by default
**What happened**:
For dashboard panels using Azure monitor data source, exporting(external) & importing the dashboard does not load data by default. All panels need to be manually edited to choose the workspace (even though data source has a default workspace set).

**What you expected to happen**:
Dashboard panels loads data by default by using the default workspace set in the data source

**How to reproduce it (as minimally and precisely as possible)**:

Create a azure monitor data source. Use 'Log Analytics' service and select/set default subscription & default workspace in the data source.
Import a dashboard that uses azure monitor data source (Log Analytics service) - For reference use the dashboard # 10956
See all panels show error, none of the panels load as default workspace is not set in the queries for any of the panels. One has to edit every single panel to update the workspace !!

**Environment**:
- Grafana version:6.4.1
- Data source type & version: azure monitor 0.3.0
- OS Grafana is installed on: windows & also hosted grafana
- User OS & Browser: chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Grafana plugins:
- Others:

### PR DESCRIPTION
**Pull request by shavonn**
Fixes https://github.com/grafana/grafana/issues/19722

### CODE REVIEW

**Review by briangann — APPROVED** [review]
Works great.  This resolves the issue with importing pre-built dashboards (tested with https://grafana.com/grafana/dashboards/10956)

**Review by daniellee — APPROVED** [review]
This works - however there is one thing that should be fixed:

image

The workspace dropdown in the query editor is showing the workspace id and not the friendly name when I create a new panel.

**Comment by shavonn** [comment]
> This works - however there is one thing that should be fixed:
> 
> image
> 
> The workspace dropdown in the query editor is showing the workspace id and not the friendly name when I create a new panel.

Please let me know if the change works for you.

**Review by daniellee — CHANGES_REQUESTED** [review]
Doesn't work at all for me - still seeing the guid and not the friendly name.

Looks like the if statement on line 541 in the query_ctrl.ts does not work as expect:

`if (list.length > 0 && !this.target.azureLogAnalytics.workspace) {`

 I tried debugging and `this.target.azureLogAnalytics.workspace` is already set to a guid (in my case `f72845a0-9927-4e61-a534-1c94a59e1937`)

**Comment by shavonn** [comment]
> Doesn't work at all for me - still seeing the guid and not the friendly name.
> 
> Looks like the if statement on line 541 in the query_ctrl.ts does not work as expect:
> 
> `if (list.length > 0 && !this.target.azureLogAnalytics.workspace) {`
> 
> I tried debugging and `this.target.azureLogAnalytics.workspace` is already set to a guid (in my case `f72845a0-9927-4e61-a534-1c94a59e1937`)

@daniellee I'm getting the friendly name (with or without the find method - so I removed it). I import the dashboard, select the datasource, save, and click Edit on a panel. Any specific browser of Grafana version? 

Screen Shot 2019-12-11 at 8 43 14 AM

**Review by sunker — APPROVED** [review]
Seems to work on my machine. 

Skärmavbild 2019-12-11 kl  15 23 32

**Comment by shavonn** [comment]
> Doesn't work at all for me - still seeing the guid and not the friendly name.
> 
> Looks like the if statement on line 541 in the query_ctrl.ts does not work as expect:
> 
> `if (list.length > 0 && !this.target.azureLogAnalytics.workspace) {`
> 
> I tried debugging and `this.target.azureLogAnalytics.workspace` is already set to a guid (in my case `f72845a0-9927-4e61-a534-1c94a59e1937`)

Was able to replicate doing a new dashboard and log analytics query. Appears to be something going on with the dropdown itself or implementation. Have made an issue to track. https://github.com/grafana/grafana/issues/21049

**Comment by shavonn** [comment]
@daniellee I figured it out. Needed a method in the `get-options` on the `gf-form-dropdown` directive.

**Review by daniellee — APPROVED** [review]
LGTM - works with the friendly name too in the workspace dropdown.

**Pull request merged**
