### PR TITLE
Tooltip: Add value calculation option for multi tooltip in time series panel

### PR DESCRIPTION
**Pull request by ivanahuckova**
This PR adds value calculation option for multi tooltip in time series panel. 

image

### CODE REVIEW

**Review by codeincarnate — COMMENTED** [review]
I've not been able to get this to work so far 😿 

Screenshot 2024-03-25 at 5 12 31 PM

**Comment by ivanahuckova** [comment]
I implemented it for a new `TimeSeriesTooltip` as @leeoniya mentioned that old one - `TooltipPlugin` will go away soon. I can remove settings from Time series panel settings until we use only `TimeSeriesTooltip`  as we are not storing numeric values in `TooltipPlugin`, so it is not as easy to implement. And redundant as it will go away. 

That way we can use it and as soon as `TimeSeriesTooltip` is default, we can show it in settings.

**Comment by ivanahuckova** [comment]
To be reviewed after https://github.com/grafana/grafana/pull/84420

**Comment by ivanahuckova** [comment]
Changing to draft until we figure out if this is needed.

**Pull request closed without merging**
