### PR TITLE
Chore: Fix faulty clearTimeout type

### LINKED ISSUE #76253: Console: Incorrect type declaration for clearTimeout
### What happened?

These lines give console errors.
https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/annotations/AnnotationMarker.tsx#L66
     
https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/annotations/AnnotationMarker.tsx#L73
     
and 

https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/ExemplarMarker.tsx#L108

### What did you expect to happen?

Console erros to vanish.

### Did this work before?

Yes.

### How do we reproduce it?

- yarn start
- check your console and the respective files mentioned above

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.1.4
OS: mac (m1)
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by krishnemd**
**What is this feature?**

It fixes the console error on  
     https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/annotations/AnnotationMarker.tsx#L66
     
https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/annotations/AnnotationMarker.tsx#L73
     
and 

https://github.com/grafana/grafana/blob/5e14d93530fb8fd55f2bde26195f1bec5dc71868/public/app/plugins/panel/timeseries/plugins/ExemplarMarker.tsx#L108

**Why do we need this feature?**

To fix console error. 

**Who is this feature for?**

Developers.

**Which issue does this PR fixes?**
Fixes https://github.com/grafana/grafana/issues/76253

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Review by adela-almasan — APPROVED** [review]

**Comment by chauchausoup** [comment]
@adela-almasan I can't merge the PR. Or are we waiting for someone's review.

**Comment by adela-almasan** [comment]
@chauchausoup could you please merge latest `main` and push? Thanks!

**Comment by chauchausoup** [comment]
Oh thats the cases. Let me me do it now.

**Comment by chauchausoup** [comment]
It seems that @renovate-bot has fixed the issue in its latest PR. Thats cool. I am closing this PR due to that case.

**Pull request closed without merging**
