### PR TITLE
[v10.4.x] Dashboard: Backport fix to make dashboard search faster

### LINKED ISSUE #69659: Search: navigation bar search very slow for non-admins
### 
# What went wrong?

**What happened**:
After upgrading our grafana instance from 9.4 to 9.5.2, users have started reporting slowness when searching via the new nav bar. Searches are typically taking 12 seconds or longer for both authenticated and non-authenticated users. For authenticated administrators, nav bar searches perform very quickly though.

Searching from the dashboard search page seems fine though. We don't currently have slow query logs enabled on our database.

The below issue seems similar, but our database appears to have the index that was added as the resolution.
https://github.com/grafana/grafana/issues/25688 

Our system has about:
- 4200 dashoards
- 650 users

**What did you expect to happen**:
I expect searches using the nav bar to be performant when non-admins search.

### 
# How do we reproduce it?

**Step 1**:

- Click in the top nav bar and start typing a search while unauthenticated

**Step 2**:

- Wait for the search request to complete and update the results

grafana_query

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

_No response_

### User's Browser?

Chrome, Firefox and Edge all act the same

### Is this a Regression?

None

### Are Datasources involved?

_No response_

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by yufanmou**
**What is this feature?**

Backport #88019 to v10.4.x to fix #69659 

**Why do we need this feature?**

Dashboard search has been very slow for our users, so we hope to improve this without having to upgrade to a new major version.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

#69659 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by diegommm** [comment]
Closing as per [this comment](https://github.com/grafana/grafana/pull/88019#issuecomment-2284292188). Feel free to reopen if needed if your tests show an improvement.

**Comment by knuzhdin** [comment]
I think this was a valid backport. Please see https://github.com/grafana/grafana/pull/88019#issuecomment-2314840162

@diegommm

**Comment by yufanmou** [comment]
@knuzhdin I would love to reopen this PR if possible, but I'm not sure if I have that permission.

**Comment by diegommm** [comment]
Closed in favour of https://github.com/grafana/grafana/pull/94703 to follow our standard backporting protocol.

**Pull request closed without merging**
