### PR TITLE
RefreshPicker: Make valid intervals in url visible in RefreshPicker

### LINKED ISSUE #30468: v7.4-beta1: Auto refresh interval is not visible in refresh picker after re-load
To replicate: 

* Open dashboard
* add `&refresh=13s` **important that the refresh interval is not a existing refresh interval**
* Do a full page reload

The panels still auto refresh every 5s but the refresh selector makes you think there is no refresh active

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR is one way to solve #30468 by making so that any valid refresh interval in url is shown in RefreshPicker. The other alternative would be to open a PR that ignores any refresh interval that is not valid. Let me know what you think.

This PR also refactors out `intervalsToOptions` to a separate function.

Enjoy the review 🎉 

**Which issue(s) this PR fixes**:
Fixes #30468

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by torkelo** [comment]
Not sure the problem is in the picker, is the problem not that an invalid refresh interval is used & trigger refreshes. They should either be ignored (in both refresh picker & timeSrv) or we should pick the closest valid option and use that

**Comment by hugohaggmark** [comment]
> Not sure the problem is in the picker, is the problem not that an invalid refresh interval is used & trigger refreshes. They should either be ignored (in both refresh picker & timeSrv) or we should pick the closest valid option and use that

Sure, this behavior was introduced in https://github.com/grafana/grafana/pull/19416. I'm going to go with picking the closest one in the Picker then.

**Comment by torkelo** [comment]
> Sure, this behavior was introduced in #19416. I'm going to go with picking the closest one in the Picker then.

I think the bug is here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/TimeSrv.ts#L155 

The check there only checks the server min refresh setting, not the options in the dashboard. The refresh picker checks the dashboard options & the server min refresh interval setting, and so shows emtpy (off), but TimeSrv thinks it's valid and uses it

**Comment by hugohaggmark** [comment]
> > Sure, this behavior was introduced in #19416. I'm going to go with picking the closest one in the Picker then.
> 
> I think the bug is here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/TimeSrv.ts#L155
> 
> The check there only checks the server min refresh setting, not the options in the dashboard. The refresh picker checks the dashboard options & the server min refresh interval setting, and so shows emtpy (off), but TimeSrv thinks it's valid and uses it

Gotcha, I'm looking at `this.dashboard.timepicker.refresh_intervals` but this is always undefined. Maybe the dashboard isn't loaded at this stage?

**Comment by hugohaggmark** [comment]
> > > Sure, this behavior was introduced in #19416. I'm going to go with picking the closest one in the Picker then.
> > 
> > 
> > I think the bug is here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/TimeSrv.ts#L155
> > The check there only checks the server min refresh setting, not the options in the dashboard. The refresh picker checks the dashboard options & the server min refresh interval setting, and so shows emtpy (off), but TimeSrv thinks it's valid and uses it
> 
> Gotcha, I'm looking at `this.dashboard.timepicker.refresh_intervals` but this is always undefined within this function at load time. Maybe the dashboard isn't loaded at this stage?

**Comment by hugohaggmark** [comment]
> > > > Sure, this behavior was introduced in #19416. I'm going to go with picking the closest one in the Picker then.
> > > 
> > > 
> > > I think the bug is here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/TimeSrv.ts#L155
> > > The check there only checks the server min refresh setting, not the options in the dashboard. The refresh picker checks the dashboard options & the server min refresh interval setting, and so shows emtpy (off), but TimeSrv thinks it's valid and uses it
> > 
> > 
> > Gotcha, I'm looking at `this.dashboard.timepicker.refresh_intervals` but this is always undefined within this function at load time. Maybe the dashboard isn't loaded at this stage?

Aah I think I understand now, if there is no intervals then defaults apply 🙈

**Comment by hugohaggmark** [comment]
So I pushed my latest changes, this got a lot more complicated than I thought when first looked into this because there are so many variants.

**Review by jackw — APPROVED** [review]
LGTM! 🚀 

Lovely work with the tests Hugo! 👏👏👏

**Comment by hugohaggmark** [comment]
@torkelo any final feedback before I merge this. Have I forgotten something?

**Review by torkelo — APPROVED** [review]
Looks great!

**Pull request merged**
