### PR TITLE
Datasource: Azure Monitor add query by namespace for resources

### LINKED ISSUE #18063: AzureMonitor: Support retrieval of resource names by namespace
**What would you like to be added**:
Azure monitor queries should support the retrieval of resource names by namespace. Currently ResourceNames() supports the following parameters:

* subscriptionId, resourceGroupName, metricName
* resourceGroupName, metricName

The resource manager API supports queries of resources at a subscription level using the filter parameter of the API e.g.

```
https://management.azure.com/subscriptions/xxxxxx/resources?$filter=resourceType EQ 'Microsoft.Insights/components'&api-version=2018-05-01
```

Allowing us to use a query that is formatted like the example below:

```
ResourceNames(Microsoft.Insights/components)
```

**Why is this needed**:
This feature would allow users of the Azure Monitor data source to query resources of a similar type across multiple resource groups in a subscription.

An example of this would be to look at failed requests across multiple app insights instances.

### PR DESCRIPTION
**Pull request by chelnak**
**What this PR does / why we need it**:
This PR adds the ability to return a list of resource names by metric name (resource type) for azure monitor sources.

This will allow users to add a query that uses the following syntax:

```
ResourceNames(Microsoft.Insights/components)
```

It solves an issue where we are unable to create graphs for resources across multiple resource groups in Azure.

Happy to take on board any feedback/suggestions.

**Which issue(s) this PR fixes**:

Fixes #18063

**Special notes for your reviewer**:
If you can point me to some docs for building/testing plugins that are a part of the grafana solution that would be really helpful.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by aaronbutler2** [comment]
my approval clicked by mistake with no option to remove it.

**Comment by marefr** [comment]
@chelnak thanks.

Have you verified there's no existing issue open for this [here](https://github.com/grafana/grafana/labels/datasource%2FAzure%20Monitor)? If there are, please reference it in PR. If not, could you please open an issue to track this feature request and explain what feature you want and how that's different compared to the existing functionality, see [docs](https://grafana.com/docs/features/datasources/azuremonitor/#templating-with-variables-for-the-azure-monitor-service).

**Comment by chelnak** [comment]
@marefr New issue created and PR context updated. 👍

**Comment by daniellee** [comment]
@chelnak I think your issue might have been fixed with this PR: https://github.com/grafana/grafana/pull/17282 which allows you to choose a metric namespace.

Can you test the latest master and see if that works for you.

**Comment by chelnak** [comment]
I’ll take a look, thanks!

**Comment by chelnak** [comment]
@daniellee Just checked the commits in the PR you linked and it appears that it adds the ability to return a list of metric namespaces by resource group.

My suggestion was the ability to return resources in a subscription by namespace.

E.g to replicate

Get-AzResource -ResourceType Microsoft.Insights/components 

Which would return all application insights resources from the current subscription 

Cheers

**Comment by chelnak** [comment]
@daniellee Did you get chance to review this any further? 👍

**Comment by chelnak** [comment]
@daniellee I think this can be closed given that 6.4 has query mode!

**Comment by marefr** [comment]
@chelnak thanks for the heads up.

**Pull request closed without merging**
