### PR TITLE
Dashboards: Enable scenes by default

### PR DESCRIPTION
**Pull request by ivanortegaalba**
Enable Scenes by default for v11.3.0.

This implies running E2E with scenes enabled by default and moving the previous tests to the `old-arch` folder to run them with FF disabled.

Summary of changes:
- Create a new folder `old-arch` where I moved all the `e2e/*-suite/*specs` files. Those runs with old arch only
- Move from `e2e/scenes` to `e2e/` to make Scenes E2E run by default
- Rename variables and paths from Drone
- Touch a couple of tests that needed small adjustments

### CODE REVIEW

**Review by dprokop — APPROVED** [review]
🚀

**Review by axelavargas — APPROVED** [review]
🥳

**Review by bfmatei — APPROVED** [review]
🚀 🌕  🎸 ⭐

**Review by mdvictor — APPROVED** [review]
LET'S GOOO!

**Review by kaydelaney — APPROVED** [review]

**Review by oscarkilhed — APPROVED** [review]
🍾

**Review by Sergej-Vlasov — APPROVED** [review]
🚀 🚀 🚀

**Comment by bobrik** [comment]
This seems like a downgrade for the most common use case of eyeballing the dashboards. Let me highlight the wasted space for two common scenarios I see.

The first one is dashboard with no variables or links:

* Before:

image

* After (the wider your window is, the more prominent the problem looks):

image

The second is a dashboard with a bunch of variables and/or links:

* Before:

image

* After:

image

This doesn't seem like a good direction to take. Is there a PR that does the initial change with some motivation?

I noticed it when upgrading from v11.2 to v11.3 and I bisected the change to this PR:

```
7bca69849f08ac9d0ea96fe04016a11420f3acf3 is the first bad commit
commit 7bca69849f08ac9d0ea96fe04016a11420f3acf3
Author: Ivan Ortega Alba <ivanortegaalba@gmail.com>
Date:   Mon Sep 30 11:49:02 2024 +0200

    Dashboards: Enable scenes by default (#93818)

    * Mark Scenes feature toggles as GA

    * Move old arch e2e to a new folder

    * Run E2E on scenes by default

    * Upgrade e2e-selectors to ensure the tests in Playwright works
```

**Pull request merged**
