### PR TITLE
Plugins: Provide license token directly via plugin environment

### PR DESCRIPTION
**Pull request by DanCech**
This PR updates the way we provide license tokens to backend plugins, providing the content of the token directly via the `GF_ENTERPRISE_LICENSE_TEXT` environment variable.

### CODE REVIEW

**Comment by marefr** [comment]
Why? Any issue?

**Comment by DanCech** [comment]
When tokens are stored in the database the token file will be missing or empty, so the plugin cannot read the token from the file.  The plugins already support the _TEXT environment variable, but Grafana has not passed it (until this PR).

**Comment by marefr** [comment]
Noticed the Enterprise PR now. @ryantxu this will require Enterprise plugins to be updated to be able to support both licenses stored in file and in the database

**Review by marefr — APPROVED** [review]
LGTM

**Review by aknuds1 — APPROVED** [review]
Looks good afaict

**Comment by marefr** [comment]
Added to 7.1-beta2 milestone since this is included in Enterprise 7.1-beta1

**Comment by marefr** [comment]
@DanCech feel free to merge or let us know if you want us to do it.

**Pull request merged**
