### PR TITLE
CodeEditor: Fix broken styles

### LINKED ISSUE #88494: CodeEditor: Recent changes interfere with container styles
## The problem

#88102 introduced changes that prevent styles provided to `@grafana/ui`'s `<CodeEditor />` component's `containerStyles` prop from working as expected. One symptom of this is the the **JSON Model** view of a dashboard's settings page:

### Before

JSON model before state

### After

JSON model after broken styles

### PR DESCRIPTION
**Pull request by NWRichmond**
## What is this change?

A fast-follow update to https://github.com/grafana/grafana/pull/88102. It updates `grafana-ui`'s `ReactMonacoEditorLazy` component (exported as `ReactMonacoEditor`), which is used both directly & indirectly (via `grafana-ui`'s `CodeEditor`) by various data sources, panel plugins, dashboard components, etc.

## Why do we need this change?

To address the problems outlined in #88494.

#### Before

The `containerStyles` supplied to the `<CodeEditor />` were not working as expected. For example, [in `JsonEditorSettings`](https://github.com/grafana/grafana/blob/8f45003192854a476dbf113b5e718e7d13e8d682/public/app/features/dashboard/components/DashboardSettings/JsonEditorSettings.tsx#L33-L40):

dashboard settings json model broken styles

#### After

The `containerStyles` supplied to the `<CodeEditor />` work as they did before. For example, in `JsonEditorSettings`:

demo monaco editor container fix for dashboard settings json model

## Who is this feature for?

All Grafana users.

## Which issue(s) does this PR fix?

Fixes #88494

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by NWRichmond** [comment]
It appears there's an issue with the `data-testid` that's passed to `<ReactMonacoEditor />` [here](https://github.com/grafana/grafana/blob/e25ab252f67eae4928b2d6c6d2901f0188ab14c9/packages/grafana-ui/src/components/Monaco/ReactMonacoEditorLazy.tsx#L50) - it's being stripped from the component, which is causing some tests to fail because they cannot find the component by its `data-testid`.

failing test reactmonacoeditor

I'll work on this, but suggestions are welcome!

**Comment by ashharrison90** [comment]
> It appears there's an issue with the `data-testid` that's passed to `<ReactMonacoEditor />` [here](https://github.com/grafana/grafana/blob/e25ab252f67eae4928b2d6c6d2901f0188ab14c9/packages/grafana-ui/src/components/Monaco/ReactMonacoEditorLazy.tsx#L50) - it's being stripped from the component, which is causing some tests to fail because they cannot find the component by its `data-testid`.
> 
> failing test reactmonacoeditor
> 
> I'll work on this, but suggestions are welcome!

it looks like `ReactMonacoEditor`, and specifically `Editor` from `@monaco-editor/react` does not accept `data-testid` as a prop. assume that's why the container component was there previously 🤔 

ordinarily you'd see a typescript error, but because `useAsyncDependency` just types it's result as `any` you don't get any type validation 😅

**Comment by NWRichmond** [comment]
@ashharrison90 for sure, that `any` definitely makes it sneaky!

Luckily, `@monaco-editor/react`'s `Editor` offers a [`wrapperProps`](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/types.ts#L106-L109) prop that spreads onto the editor's root element. I implemented that in https://github.com/grafana/grafana/pull/88495/commits/f9aa4d6e770df32ef107d91e14bd4a063d5a0cb3 and am seeing the `data-testid` on the expected element:

demo data-testid via wrapperProps

Puzzlingly, `public/app/plugins/datasource/loki/querybuilder/components/LokiQueryCodeEditor.test.tsx`'s `LokiQueryCodeEditor › does not show explain section when showExplain is false` test is still failing in the same place. I'm not sure why yet, but will keep at it :)

**Review by svennergr — APPROVED** [review]
Testchanges in Loki LGTM

**Pull request merged**
