### PR TITLE
Cloud Aggregation: make it work for users with no name

### PR DESCRIPTION
**Pull request by charandas**
**What is this feature?**

While working on delivering Cloud Aggregation in September, we ran into this issue on Grafana users with no name. They couldn't use the aggregation feature. While we were all stumped at first, it came down to Requester (which is SignedInUser) returning an empty Name on `GetName` (the correct behavior should be to return something, or aggregation which depends on X-Remote-User header, doesn't work). [See slack thread](https://raintank-corp.slack.com/archives/C037H5GAY9L/p1725479660977659?thread_ts=1722433605.876979&cid=C037H5GAY9L).

@peterholmberg and his squad has been working around this issue ever since by simply not using a Grafana login with this issue. However, this feature is getting shipped soon and this blocks it.

Here in this PR, I am putting a fix in for such users. Wdyt?

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

Unblocks Grafana users with no name set so they can use the new servicemodel feature in Cloud Apps directly as part of kubectl access against their HG instance.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by toddtreece — APPROVED** [review]

**Review by radiohead — APPROVED** [review]
Makes sense to me as well :shipit:

**Review by ferruvich — APPROVED** [review]
Makes sense to me! Thanks for taking care of this 🚀

**Pull request merged**
