### PR TITLE
Add AWS/CodeBuild namespace for CloudWatch datasource

### PR DESCRIPTION
**Pull request by mmcoltman**
#14167

### CODE REVIEW

**Comment by mmcoltman** [comment]
First time making a PR so please excuse if I've missed something. I've run frontend + backend tests and tested using docker against 'live' data. All seems good.

**Review by marefr — APPROVED** [review]
Verified with https://docs.aws.amazon.com/codebuild/latest/userguide/monitoring-builds.html and it looks good :+1:

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Comment by mmcoltman** [comment]
> Thank you for contributing to Grafana!

You're welcome, thanks for the quick review! Out of interest, I saw there are quite a few similar issues open (missing metrics for various services in CloudWatch). Would it be ok to fix more than one issue in a PR and link them all, or would you want a separate PR for each issue?

**Comment by mmcoltman** [comment]
Ok thanks, I'll see how it works out then.

**Pull request merged**
