### PR TITLE
Added basic support for alerts with crateDB Datasource plugin

### PR DESCRIPTION
**Pull request by Cerfoglg**
As mentioned in an issue a while back ( #9207 )

A basic implementation of an executor to enable Alerts with the [CrateDB Datasource Plugin](https://grafana.com/plugins/crate-datasource).

This is being worked on as part of an effort to deploy Grafana as part of [Orchestra Cities](https://www.orchestracities.com/): a Smart Cities Platform currently in development.

### CODE REVIEW

**Comment by torkelo** [comment]
thanks for wanting to contribute to Grafana. 

We do not want take ownership of more plugins (by adding them to core). There is an undocumented way to create external backend plugins. We have yet to find time to finish work on backend plugin support & write docs for it. 

You can find an example backend plugin here: 
https://github.com/grafana/simple-json-datasource/tree/backend-updated

**Comment by chicco785** [comment]
@torkelo do you confirm that this is going to support Alerts? so far alerts can be only supported via core and in the code you provided as example, I can't find any example of alert support.

**Comment by marefr** [comment]
@chicco785 yes it works with alerting because it will behave like a core backend plugin. Reason this is undocumented is because it needs some more hardening and documentation. Because of this you can't expect that you'll get support around any questions regarding this yet. However,  we're always interested in feedback. We've implemented a few plugins using this and it looks very promising and have been running in some Grafana production environments with good results.

**Comment by chicco785** [comment]
@marefr when will you be able to share anything or allow us to provide feedbacks?

thx

**Comment by marefr** [comment]
@chicco785 you're always welcome to provide feedback. Just meant that questions/support regarding this we may not be able to answer until we officially released this feature. 

We already shared the referenced link above (https://github.com/grafana/simple-json-datasource/tree/backend-updated) should give you a good starting point. No ETA for official release of this yet.

**Comment by marefr** [comment]
We'll not add that now since it can be plugin dependent. For building see [Makefile](https://github.com/grafana/simple-json-datasource/blob/backend-updated/Makefile) and then it's just a matter of having correct [plugin.json](https://github.com/grafana/simple-json-datasource/blob/backend-updated/src/plugin.json#L12-L13) and then install it like you install any other plugin, i.e. put all plugin files in the data/plugins folder.

**Pull request closed without merging**
