### PR TITLE
Dashboards: Fix small drop target for importing dashboards

### LINKED ISSUE #71880: GrafanaUI: FileDropzone does not register full area as a drop target
When dropping a file onto the FileDropzone, it only registers as a file being dragged over (or dropped on) when dropping on the very center of the control, rather than the full area.

Reproducable in Grafana:

 - Go to Dashboard Import /dashboard/import
 - Drag a file to the right side of the drop area 

Image

Expected:
 - control should highlight if a file is dragging over any of the box

Actual:
 - control only highlights when dragged over the very centre of the element

### PR DESCRIPTION
**Pull request by kunxl-gg**
**What is this feature?**
This solves the issue of not being able to upload files outside the centre of the drop zone. As you can see the screenshot below we have solved the issue. 

Screenshot 2023-07-22 at 9 40 02 PM

**Which issue(s) does this PR fix?**:
Fixes #71880 

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by joshhunt** [comment]
Thanks for the contribution @kunxl-gg! Please make sure the email you've configured git with is linked to your github account (see Setting your commit [email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)) for more details, and [sign the CLA](https://cla-assistant.io/grafana/grafana?pullRequest=72170) 👍🏻

**Comment by kunxl-gg** [comment]
> 

I have signed the CLA. and configured my git, What else

**Comment by kunxl-gg** [comment]
> Thanks for the contribution @kunxl-gg! Please make sure the email you've configured git with is linked to your github account (see Setting your commit [email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)) for more details, and [sign the CLA](https://cla-assistant.io/grafana/grafana?pullRequest=72170) 👍🏻
> 
> Note - we're cutting a new release next week so if you get this done before Wednesday it'll go into 10.1 :)

I have signed the CLA and configured my email on git. What next. This is a  new laptop probably that is why I didn't have my email configured.

**Comment by joshhunt** [comment]
Hmm @kunxl-gg, it looks like you'll need to re-commit with the new author details with the proper email address. The problem is with how the commit isn't linked to your user, which can be see by the commit missing your profile photo.

image

`git commit --amend --reset-author --no-edit ` should do the trick. Note, this will rewrite the commit, so you'll need to `git push --force` that commit after.

Once the commit is attributed to your git user correctly, revisit the [CLA link](https://cla-assistant.io/grafana/grafana?pullRequest=72170) to trigger the check again. Then in in the week we will review + merge if all good 👍🏻

**Comment by kunxl-gg** [comment]
Done. Sorry for taking your time. Will take care of these minor details next time.

**Review by joshhunt — APPROVED** [review]
Tested this in both Storybook and in Dashboard import and it works great! Thanks for the contribution @kunxl-gg.

This should go out in the Grafana 10.1 release in the coming weeks 🥳

**Pull request merged**
