### PR TITLE
PostgreSQL: Fix postgresql host-v6 literals

### PR DESCRIPTION
**Pull request by felixdoerre**
Ipv6 literals (like `[::1]`) in postgresql hosts previously worked and were subsequently
broken. This change fixes the parsing and adds additional test cases.

### CODE REVIEW

**Comment by felixdoerre** [comment]
Hi @daniellee, you previously fixed ipv6 literals for the postgresql data source in #11055 but they were subsequently broken in 9285595c50a3e81b6742cc519651d3aa4d776f5c when parsing was adjusted to directly handle unix domain socket paths. Would you mind taking a look at this PR to fix the ipv6 literals again (and add test cases)? Do you know who else I could ask for a review/feedback?

**Comment by kirederik** [comment]
@felixdoerre could you take a look at the lint error? 🙏🏽

**Comment by felixdoerre** [comment]
@kirederik Yes, I was a bit confused by the output of the CI, and didn't pay attention to that step. Its corrected now, the CI passes.

**Review by kirederik — APPROVED** [review]

**Comment by kirederik** [comment]
Thanks @felixdoerre

**Pull request merged**
