### PR TITLE
CloudWatch: Return with error message for empty logs query string

### PR DESCRIPTION
**Pull request by fridgepoet**
**What is this feature?**

This adds an error message in the frontend when a CloudWatch Logs query string is missing.

**Why do we need this feature?**

An empty query string used to be sent to the backend and to AWS, returning with an error and a message which did not explain what went wrong: "An error has occurred in the plugin."
This prevents the backend and AWS from being reached and explains to the user what is missing.

**Special notes for your reviewer**:
In the AWS console, empty query is also not allowed. They seem to fill in a default query upon opening their editor which might be done in https://github.com/grafana/grafana/issues/58205.

### CODE REVIEW

**Review by idastambuk — APPROVED** [review]
LGTM!

**Review by iwysiu — APPROVED** [review]

**Review by sunker — COMMENTED** [review]
My concern with this approach is that now we're gonna show an error the first time you load the logs editor, without the user having even made any changes. The approach we're taken in CW metrics (and I believe in most other plugin editors too), is that the datasource.query method just silently filters out the queries that are incomplete. 

Currently there's no straightforward way to propagate error messages from the datasource file to the query editor. However, I still think it's better to strive for making it clear in the editor what fields are required and what fields are optional so it becomes obvious to the user what to do. 

WDYT @fridgepoet?

**Comment by fridgepoet** [comment]
Alright, let me make the change to silently return in case the query is incomplete

**Comment by fridgepoet** [comment]
Oh that is going to make the logs insight button (where it doesn't have a link loaded) a little bit more obvious https://github.com/grafana/cloud-data-sources/issues/90.

That button needs to be disabled or something before data returns and a URL is generated (or something like that).

**Comment by sunker** [comment]
> That button needs to be disabled or something before data returns and a URL is generated (or something like that).

Maybe for now just disabling the button if an expression is not defined or log groups are not defined would be good enough.

**Comment by fridgepoet** [comment]
> Maybe for now just disabling the button if an expression is not defined or log groups are not defined would be good enough.

Precision on that: With no queries, I think the log insights button does correctly direct to AWS Console log insights.

**Pull request merged**
