### PR TITLE
CSS: use `prefers-reduced-motion` to let users skip animations

### LINKED ISSUE #77859: UI: Make possible to disable animations and css filters
### What happened?

When using Grafana 10.0.1 and 10.2.0, together with VNC to VM, some operations are super slow and hog a lot of vnc server to vnc client bandwidth, especially at higher resolutions.

This problem was not present before in Grafana 9.x, but Grafana 10.x add some extra animations and animated css filter behind few menus, which cause massive amount of screen redraw every frame.

### What did you expect to happen?

Smooth operations.

### Did this work before?

Yes.

### How do we reproduce it?

1. Run Grafana 10.x
2. Run VM, i.e. Fedora, and run desktop under Xvncserver
3. Connect, with high resolution screen
4. Maximise browser (Firefox, Chrome)
5. After login, Click either hamburger menu on the left, or the main search bar at the top.
6. Observe animation and css blue/frost filter applied to the rest of the page behind.

Example:

[grafana10-over-vnc.webm](https://github.com/grafana/grafana/assets/110322/4191054c-14f9-41ee-b684-52105debdc89)

Please note that above video capture, was captured at 30 fps, and AT VM side. On VNC client side it is even worse. The full viewport of the webpage had size 2275 px height x 2685 px tall.

grafana10-example-viewport

Running very same web browser version, at same viewport size, and same grafana server, but on client side (without VNC), is smooth. So this is not a browser, grafana or machine issue, but rather inherent to VNC transfering A LOT of data during these animations.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 10.x
OS: Doesn't matter
Browser: Doesn't matter

### Grafana platform?

None

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by eledobleefe**
**What is this feature?**

We add `prefers-reduced-motion` CSS media feature to skip animations when the user specifies it.

**Why do we need this feature?**

To be able to skip animations when wanted/needed.

**Who is this feature for?**

All who want/need to skip animations.

**Which issue(s) does this PR fix?**:

Fixes #77859

**Special notes for your reviewer:**
1. [`prefers-reduced-motion` documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
2. How to set your preferences to [skip animations](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences)

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by eledobleefe** [comment]
Bloqued while we discuss the best approach to disable animations

**Comment by eledobleefe** [comment]
> Block while we discuss the best approach to disable animations

We agreed on: 
1. Tackling the animations individually
2. We cannot avoid meaningful animations, such as the `LoadingBar`, that should be handled differently, smoothing the animation.

**Review by joshhunt — APPROVED** [review]
Excellent stuff!

**Pull request merged**
