### PR TITLE
Migrate Select components to @grafana/ui

### LINKED ISSUE #14808: Move Select components to @grafana/ui
Located here: 
https://github.com/grafana/grafana/tree/master/public/app/core/components/Select 

Skip the Unit & DataSource picker for now as they might need other stuff to be moved before.

### PR DESCRIPTION
**Pull request by dprokop**
closes #14808 

TODO:
- [x] Figure out missing types for Torkel's `react-select` fork

### CODE REVIEW

**Review by torkelo — APPROVED** [review]
Looks good, would like to rename the PickerOption component to SelectOption align more on Select prefix name

**Comment by dprokop** [comment]
Sure @torkelo

**Comment by dprokop** [comment]
@torkelo I have moved the scss to grafana/ui but not without problems. Select's styling relies on classes order unfortunately (`gf-form-input` / `gf-form-input--form-dropdown` for instance) so I had to move the grafana/ui sass import below the rest of the component's styles imports. I guess we will have to revisit the styles later on, as there might be more components like this down the road.

@peterholmberg @jschill @hugohaggmark  FYI ^^

**Comment by torkelo** [comment]
ok, good to know!

**Pull request merged**
