### PR TITLE
Chore: Update cloudwatch data source plugin to load log context from exectution context

### PR DESCRIPTION
**Pull request by yuri-tceretian**
**What is this feature?**

**What is this feature?**
PR https://github.com/grafana/grafana/pull/57476 added a new log context provider for alerting, which provides rule UID and orgID  (rule key) to log context. PRs https://github.com/grafana/grafana/pull/57708 and https://github.com/grafana/grafana/pull/57777 added the support for loading logger context from the execution context to some data source plugins. This PR adds it to the CloudWatch plugin.

**Why do we need this feature?**
This feature will help trace the requests made by alerting engine. 

**Who is this feature for?**
Grafana developers and administrators. 

**Which issue(s) does this PR fix?**:
Related to https://github.com/grafana/grafana/pull/57476, https://github.com/grafana/grafana/pull/57708 and https://github.com/grafana/grafana/pull/57777

### CODE REVIEW

**Review by fridgepoet — APPROVED** [review]
Will let sunker and kevinwcyu have a look too

**Review by sunker — APPROVED** [review]
LGTM

**Comment by fridgepoet** [comment]
Hi @yuri-tceretian can we merge this?

**Comment by yuri-tceretian** [comment]
> Hi @yuri-tceretian can we merge this?

Sorry, I was OOO. Thanks for reviewing!

**Comment by fridgepoet** [comment]
No problem at all! Thanks!

**Pull request merged**
