### PR TITLE
Live: labels column as default frame format

### PR DESCRIPTION
**Pull request by FZambia**
**What this PR does / why we need it**:

Together with recent updates on client side in #34031 seems a better fit for Telegraf streaming data.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

**Comment by ryantxu** [comment]
Lets wait for: 
https://github.com/grafana/grafana/pull/33673

before we merge

**Review by ryantxu — APPROVED** [review]
update the live SDK so the labels column is at index zero and then we are :fire:

**Comment by FZambia** [comment]
Decided to go with commit version for beta 1 and update to stable tag in beta 2

**Pull request merged**
