### PR TITLE
Tempo: Option to not show variable options in "search" editor

### PR DESCRIPTION
**Pull request by domasx2**
**What is this feature?**

Adds option `addVariablesToOptions` (default `true`) to Tempo query editor to now show variable options.

**Why do we need this feature?**

Variable options make sense in dashboard context, but not for some app plugins like Application Observability, which use variables for internal reasons that are not meant to be exposed to user.

image

**Who is this feature for?**

App plugins that use Tempo query editor variables but do not want to expose the variables to users.

**Notes**

I considered making the change to limit variable options to only when `app=dashboard`. But not a fan of the `app` concept or making decision for all plugins. I think it's best to let user of the component make the decision

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by joey-grafana — APPROVED** [review]
Can you also check for `addVariablesToOptions` in `GroupByField.tsx`? It's the last place we use `withTemplateVariableOptions`.

I realize you don't use that in App O11y but it would be nice to add this for consistency.

Screenshot 2024-05-01 at 10 19 43

**Comment by domasx2** [comment]
> Can you also check for addVariablesToOptions in GroupByField.tsx? It's the last place we use withTemplateVariableOptions.
I realize you don't use that in App O11y but it would be nice to add this for consistency.

@joey-grafana done!

**Review by joey-grafana — APPROVED** [review]
Thanks pal. Last thing, you will need to move up the the `addVariablesToOptions = true` default because it's not getting set for `GroupBy` as it's set to true in `SearchField` which is a sibling in `TraceQLSearch` :D 

You can merge after that.

**Comment by domasx2** [comment]
> Thanks pal. Last thing, you will need to move up the the addVariablesToOptions = true default because it's not getting set for GroupBy as it's set to true in SearchField which is a sibling in TraceQLSearch :D

Glad I asked for re-review, thanks :D 

Moved up defaulting to true to `TraceQLSearch.tsx`

**Pull request merged**
