### PR TITLE
Alerting: Add a new plugin for jira service management

### PR DESCRIPTION
**Pull request by akyuznurettin**
**What is this feature?**

This PR includes some doc changes for a new alerting plugin: jsm

**Why do we need this feature?**

As Atlassian team, we are implementing some Opsgenie features in Jira Service Management. That is why, we are adding this plugin into Grafana. We have also this PR that is waiting for review. https://github.com/grafana/alerting/pull/112

**Who is this feature for?**

Jira Service Management customers

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by armandgrillet** [comment]
> As Atlassian team, we are implementing some Opsgenie features in Jira Service Management.

Could you provide more details about this? Grafana Alerting already supports Opsgenie and the Prometheus Alertmanager does too (https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config). 

A few questions due to this:
- What is the difference between Opsgenie and Jira Service Management today and in the future? 
- Can using a webhook contact point for JSM provide the same features as using the new dedicated contact point?

The content of this PR had not been requested in a GitHub issue (apart from the one you created today) which is why we need more information to move forward.

**Comment by akyuznurettin** [comment]
> > As Atlassian team, we are implementing some Opsgenie features in Jira Service Management.
> 
> Could you provide more details about this? Grafana Alerting already supports Opsgenie and the Prometheus Alertmanager does too (https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config).
> 
> A few questions due to this:
> 
> * What is the difference between Opsgenie and Jira Service Management today and in the future?
> * Can using a webhook contact point for JSM provide the same features as using the new dedicated contact point?
> 
> The content of this PR had not been requested in a GitHub issue (apart from the one you created today) which is why we need more information to move forward.

Thank you @armandgrillet , Opsgenie and JSM are two different products owned by Atlassian. Opsgenie is for on-call and alert management to keep services always on. There is an ongoing project to consolidate two products. After consolidation, Jira Service Management will have some Opsgenie features. It means that both Opsgenie and JSM will live in the future. That is why we are duplicating the Grafana plugin for both products.

**Comment by grobinson-grafana** [comment]
> After consolidation, Jira Service Management will have some Opsgenie features. It means that both Opsgenie and JSM will live in the future.

Hi! I looked at the code and it seems that the endpoints used in the OpsGenie and JSM integration are the same? Given this, is it possible that JSM and OpsGenie could use the same integration in Grafana, just with a different URL? Doing so would avoid the need to create and support a separate integration just for JSM - as each integration we add incurs an ongoing maintenance cost for us.

**Comment by gotjosh** [comment]
> Thank you very much for your contribution @akyuznurettin.
> Sadly, we need to have enough support from the community (e.g. in the form of thumbs-up on an issue) to introduce new contact points.
> I suggest you start by proposing an issue in https://github.com/grafana/grafana and then if we get enough support we can bring back this implementation.


Copied from https://github.com/grafana/alerting/pull/112

**Comment by TuranUgur** [comment]
Hi @gotjosh and @grobinson-grafana, let me share more information about the aim of this PR:
1. Endpoints for Opsgenie and Jira Service Management are not the same, you can check the commit for this.
2. We are bringing alert&on-call capabilities to Jira Service Management natively, so we will have a new integration on Jira Service Management product which will use this plugin as in Opsgenie. The functionality can be seen the same at first but the capabilities of Jira Service Management is much wider than Opsgenie as a product, so having a dedicated plugin will serve for visibility for both products.
3. If we cannot accomplish to merge this PR and publish the plugin, we will need to reconsider the existence of Grafana integration in our upcoming release for Jira Service Management.

Happy to have a call to discuss further and kindly requesting you to review the PR once again. Thanks in advance.

**Pull request closed without merging**
