### PR TITLE
Table Panel: Group Header and Footer Configuration

### PR DESCRIPTION
**Pull request by codeincarnate**
**What is this feature?**

This is a small PR that groups the table header & footer configuration options together. Their previous display was causing them to be displayed apart from each other despite having very similar configuration behavior.

A screenshot of the change:

Screenshot 2022-12-13 at 1 31 05 PM

**Why do we need this feature?**

Improve the UX of table panel configuration.

**Who is this feature for?**

Users that configure table panels.

### CODE REVIEW

**Comment by torkelo** [comment]
The only problem with this is that the new header and footer category shows before the main Table options category

**Comment by codeincarnate** [comment]
Going to have to see why those are grouping above. Not exactly sure why 😕

**Comment by codeincarnate** [comment]
It looks like panel options are getting placed ahead of field options. I'm honestly not 100% sure what broader impact that would have so looking into that at the moment.

**Comment by codeincarnate** [comment]
So it turns out this would require more work as we don't have a good mechanism to change the ordering of panel options and field options. Going to look into that further and hopefully get the chance to revisit this one.

**Pull request closed without merging**
