### PR TITLE
Plugins: Transform plugin support

### PR DESCRIPTION
**Pull request by kylebrandt**
FYI @marefr 

Plugin loads (assuming you change the gel **datasource's** plugin.json type to transform).

However, `func (p *TransformPlugin) spawnSubProcess() error {` doesn't actually register any endpoint yet.

### CODE REVIEW

**Review by torkelo — COMMENTED** [review]
With the addition of a new backend plugin type, I think this will require a bit of refactoring of PluginManager and how we start and manage backend plugin processes. As this duplicated currently for backend plugins and the image rendering plugin. With a some refactoring & new common architecture / interfaces this should be possible to unify. 

This is a comment from an old issue (when I introduced image rendering plugin), I started doing this refactoring but got stuck on trying to to a complete make over of PluginManager (get rid off all global state and how JSON is deserialized) .

So I never got the interesting part detailed below. 

## Backend plugins refactoring

Since this introduced another backend plugin it also caused some duplication in the code that manages the start & keep alive of backend plugins. I have started some work on plugins package refactoring that will make new backend plugins a lot easier to add so they can all share the same startup & keep alive code. But this will be in a another PR. 

Here is taste of it. 

The idea is to replace this 
```go
PluginTypes = map[string]interface{}{
		"panel":      PanelPlugin{},
		"datasource": DataSourcePlugin{},
		"app":        AppPlugin{},
		"renderer":   RendererPlugin{},
	}
```

With more detailed descriptor type (and have plugin types self-register).

```go
type RendererPlugin struct {
	PluginBase
	Executable string `json:"executable,omitempty"`
}

func init() {
	RegisterPluginType(&PluginTypeDescriptor{
		Id:               "renderer",
		PluginModel:      RendererPlugin{},
		ProtocolVersion:  1,
		ServiceInterface: grpcProxy.RendererPluginImpl{},
	})
}

```

**Comment by kylebrandt** [comment]
> With the addition of a new backend plugin type, I think this will require a bit of refactoring of PluginManager and how we start and manage backend plugin processes. As this duplicated currently for backend plugins and the image rendering plugin. With a some refactoring & new common architecture / interfaces this should be possible to unify.
> 
> ## Backend plugins refactoring
> Since this introduced another backend plugin it also caused some duplication in the code that manages the start & keep alive of backend plugins. I have started some work on plugins package refactoring that will make new backend plugins a lot easier to add so they can all share the same startup & keep alive code. But this will be in a another PR.
> 
> Here is taste of it.
> 
> The idea is to replace this
> 
> ```go
> PluginTypes = map[string]interface{}{
> 		"panel":      PanelPlugin{},
> 		"datasource": DataSourcePlugin{},
> 		"app":        AppPlugin{},
> 		"renderer":   RendererPlugin{},
> 	}
> ```
> 
> With more detailed descriptor type (and have plugin types self-register).
> 
> ```go
> type RendererPlugin struct {
> 	PluginBase
> 	Executable string `json:"executable,omitempty"`
> }
> 
> func init() {
> 	RegisterPluginType(&PluginTypeDescriptor{
> 		Id:               "renderer",
> 		PluginModel:      RendererPlugin{},
> 		ProtocolVersion:  1,
> 		ServiceInterface: grpcProxy.RendererPluginImpl{},
> 	})
> }
> ```

Hence this comment :-)

`// TODO we probably want a Backend Plugin Base? Or some way to dedup proc management code`

**Comment by marefr** [comment]
Created an issue for this #20053

**Review by marefr — APPROVED** [review]
LGTM

**Pull request merged**
