### PR TITLE
XYChart: Add time support to x axis

### PR DESCRIPTION
**Pull request by RNabel**
**What is this feature?**

The XYChart only supports "numeric" x-axis data, excl time axes. This feature makes the following changes:

1. X-axis of type time are rendered correctly
2. ... and auto-detected when constructing the panel
3. The axes range is updated when data is re-queried and min/max values have changed.

**Why do we need this feature?**

The XYChart can't render time x-axes correctly because `isTime` is hard-coded to `false`. You can manually set the x-axis to a time column, but this results in the following:
image

This cannot be fixed with field overrides, so this panel cannot be used with time x axis.

**Who is this feature for?**

Users of basic XY Chart, for example when migrating users of the Jaeger UI over to Grafana. This is a blocker for many people as seeing a summary of many traces against time is a common workflow.
image

**Which issue(s) does this PR fix?**:
None currently filed.

**Testing**
I'm not sure how/whether this panel is automatically tested, so I did the following:
1. Use the TestData datasource with the random walk data, see before and after.
image
image

2. Ensured that existing non-time-based panels continue to render correctly: 
image

3. Trigger data reload and different frequencies, which flagged the fact that axes aren't updated correctly
4. Manually ensure that time-based x-axes are correctly picked up the AutoEditor when constructing the panel: 
image

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Comment by leeoniya** [comment]
can you describe why the TimeSeries panel cannot be used?

**Comment by RNabel** [comment]
Thank you for the super-fast response! Makes sense to limit the scope for this panel; bubble charts can be very useful when plotted against time, for example when plotting economic or climate data[0].

> can you describe why the TimeSeries panel cannot be used?

The use-case that I'm trying to solve for is distinct from the existing Time Series panel in a couple of ways:
1. Number of visualized dimensions: the time series panel allows only one dimension to be visualized (AFAIK), so encoding a second dimension in the bubble size is not possible.
2. Discrete events: the time series visualization implies continuity (connected data points), whereas the underlying data in many use cases may be distinct events.
3. (minor) X-axis range and dashboard time range may not be the same: the displayed time range in a Time Series is tied to the dashboard's selected time range, which my data may not be.

There's a also a 4th point: the XYChart silently ignore time-related field overrides on the x-axis, which is a bad user experience.

Given the above, it feels reasonable to at least allow time units on the x-axis, even if time dimensions aren't picked up by the AutoEditor. What do you think?

> what you're trying to do feels closer to using Exemplars in the TimeSeries chart

Yep, the feature you link to would definitely be useful! In general, it would be great to have a couple of special trace overview panels (maybe they're already in the works?), and more integrations between traces and other data types, which seems to be addressed by Correlations!

[0] for example: time against both gdp and population.

**Comment by leeoniya** [comment]
> [0] for example: time against both gdp and population.

can this not be done by a 2-y-axis / 2 series TimeSeries chart? i have never seen an x-time bubble plot, it feels extremely niche/rare: https://www.google.com/search?q=bubble+plots&tbm=isch

while there are 1000 possible ways to visualize any data, we do not want to add every possible option to every panel and make it impossible to recommend any specific one for a certain case. nor do we want the list of core panels to grow indefinitely with 70% feature overlap. the aim should be to support the most common 85% in the core panels, and delegate the rest to external plugins.

adding time=x to XY also has many other implications, like expectation of zoom/re-query when drag-selecting x, hovering all x points at a single timestamp, timeseries panel has multi x with timezone selection. the list goes on.

imo your random walk example is unconvincing because you can already visualize that in TimeSeries and the bubbles-over-time is very uncommon. it would help if you attached a non-theoretical, real-world dataset that cannot be handled by TimeSeries+exemplars.

**Comment by RNabel** [comment]
> while there are 1000 possible ways to visualize any data, we do not want to add every possible option to every panel

Agreed. 

> adding time=x to XY also has many other implications, like expectation of zoom/re-query when drag-selecting x, hovering all x points at a single timestamp, timeseries panel has multi x with timezone selection. the list goes on.

This is convincing.

The most unfortunate part here is: XYChart sounds generic and it is not (quite). Google Sheets, Excel, PowerBI etc. support graphing bubbles/scatter plots against time, so I _assumed_ that the current behavior is a bug (no warning, bad label placement, ignores value overrides) and spent a bunch of time trying to get this to work.

> i have never seen an x-time bubble plot, it feels extremely niche/rare: https://www.google.com/search?q=bubble+plots&tbm=isch

Not 15%, but roughly 5% of the examples have time as x-axis.

Happy to help if you can think of simple things to make it clearer that time as x-axis is intentionally not supported.

**Pull request closed without merging**
