### PR TITLE
CloudWatch: Upgrade aws-sdk-go

### PR DESCRIPTION
**Pull request by mtanda**
**What this PR does / why we need it**:
There is security risk of SSRF if Grafana is running on EC2.

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/20508

### CODE REVIEW

**Comment by sunker** [comment]
Great initiative!

I'll test this as soon as all the beta2 related cloudwatch issues are fixed.

**Review by marefr — CHANGES_REQUESTED** [review]
Need to vendor the dependencies as well. See https://github.com/grafana/grafana/blob/master/UPGRADING_DEPENDENCIES.md#go-dependencies

**Review by marefr — APPROVED** [review]
LGTM

**Comment by marefr** [comment]
Thank you for contributing to Grafana!

**Comment by sunker** [comment]
Nice @mtanda, thanks!

**Pull request merged**
