### PR TITLE
typo: sqllite -> sqlite

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by torkelo** [comment]
thanks! this is merged, not sure why it did not get marked as merged.

**Comment by mattrobenolt** [comment]
You sure? :)

https://github.com/grafana/grafana/commits/develop

Maybe you merged locally and didn't push upstream?

**Comment by mattrobenolt** [comment]
I also still see the typo on https://github.com/grafana/grafana/blob/develop/docs/sources/installation/migrating_to2.md#importing-your-existing-dashboards

**Comment by torkelo** [comment]
develop was merged to master yesterday

**Comment by mattrobenolt** [comment]
Ah, then that's why the PR didn't close. :) The request was to merge into develop, and the commit wasn't merged into develop, it was merged into master instead.

All good here. Thanks. :cake:

**Pull request closed without merging**
