### PR TITLE
WIP: Fit panels to screen height

### PR DESCRIPTION
**Pull request by tskarhed**
Ref #12768 
Add `&autofitpanels` to URL to activate
- [x] Set URL parameter/place to enable/disable
- [ ] Get real available height

### CODE REVIEW

**Comment by dehrax** [comment]
I think some kind of compensation for the panel margin is needed. It acts different if there is one panel row compared to several. If there is one, it overshoots, and becomes bigger than the viewport. If there are more, it seems to undershoot, and has a couple of extra empty rows.

**Comment by dehrax** [comment]
Toggle autofit mode is now possible by pressing `d a`

**Review by marefr — COMMENTED** [review]
Full screen mode of browser (chrome) doesn't adjust correctly - panel at bottom are cut off. Firefox a bit better but leaves some space at the bottom instead.

Would be nice if this could be enabled without reloading the page, but that's probably a later problem. This solution shows the capabilities and you get an idea of how it works :+1:

**Comment by marefr** [comment]
4K resolution, however scaled down by chrome dev tools. Don't know if this can be compared with a screen having 4K resolution. Cutting off panel at the bottom adding scroll

image

**Comment by dehrax** [comment]
@marefr I am aware of this. Not taking in account the height of the navbar, mostly because I assume kiosk mode kill be used. Maybe check if kiosk mode is enabled/disabled and add/remove the height of the navbar?

**Comment by torkelo** [comment]
Did some code moving & refactoring. I tested a couple of scenarios & different dashboards. There are a few cases this approach can't handle due to the rounding but making it better could potentially be very complicated (requiring multiple passes). By having the same scaling factor be applied to all panels simplifies matters a great deal. 

Add a test case or 2 for the code (moved the code to dashboard model so now easier to test). And we can merge this and get some feedback on it.

**Comment by torkelo** [comment]
@dehrax I did a rebase on master, and so had to force push to your 12768-panel-heights branch, so you need to reset your local branch

**Review by marefr — APPROVED** [review]
Redirect bug is solved. Merging this to master to hopefully get some valuable feedback

**Pull request merged**
